### PR TITLE
refactor test matchers

### PR DESCRIPTION
**Pull request by arifogel**
**Includes #821**

---
This change is [Reviewable](https://reviewable.io/reviews/batfish/batfish/822)

### CODE REVIEW

**Comment by dhalperi** [comment]
Am I deferring this review until after #821? A little confused about the code relationship.

---

Reviewed 2 of 22 files at r1.
Review status: 2 of 22 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/822#-:-L2HnIJkMBuAynjTH2YK:bcp9tr2)*

**Comment by arifogel** [comment]
Ready now.

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/822#-:-L2NAMXHKP2e_9MTUcNq:bhurqze)*

**Comment by dhalperi** [comment]
Starting review, but FYI build fails.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/822#-:-L2RWcqqZIMnSVWpTMFf:bnzfuor)*

**Comment by dhalperi** [comment]
*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/InterfaceMatchers.java, line 1 at r2](https://reviewable.io:443/reviews/batfish/batfish/822#-L2RWmug6AJ7bBun4WPN:-L2RWmug6AJ7bBun4WPO:bgw4ozg) ([raw file](https://github.com/batfish/batfish/blob/85214ccab26fe45d002cefc8b89e8ebfcab8a4a8/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/InterfaceMatchers.java#L1)):*
> ```Java
> package org.batfish.datamodel;
> ```

Looks like it needs a rebase?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/822)*

**Comment by dhalperi** [comment]
:lgtm:

---

Reviewed 1 of 22 files at r1, 6 of 21 files at r2, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/822#-:-L2R_p8r3SKz2pi2Vzjw:bnfp4nl)*

**Pull request merged**
