### PR TITLE
porting Ryan's compression code from the batfish-compression branch

### PR DESCRIPTION
**Pull request by anothermattbrown**
Adds useCompression flag to reachability query. Adds a new cache for compressed dataPlanes. Compression happens on-demand when useCompression is enabled. The original plan was to always compute the compressed dataPlane when the uncompressed one is created. This didn't work though as not all network features are supported by compression. Also changed how serialization of dataPlanes is triggered. Previously, BdpDataPlanePlugin called into Batfish to write it out. This is somewhat convoluted (batfish calls the plugin to create the dataplane, the plugin calls batfish to serialize it) and also brittle: once there are two dataplanes BdpDataPlanePlugin now needs to know which dataPlane it is solely to tell Batfish where to write it to. It is cleaner to have batfish make the call to write the dataPlane out. This required simple modifications to some tests that compute a dataPlane and also expect that it is cached.

---
This change is [Reviewable](https://reviewable.io/reviews/batfish/batfish/909)

### CODE REVIEW

**Comment by dhalperi** [comment]
*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 2209 at r1](https://reviewable.io:443/reviews/batfish/batfish/909#-L4ls8IWB9cSlHfK-wSa:-L4ls8IWB9cSlHfK-wSb:bditk62) ([raw file](https://github.com/batfish/batfish/blob/5fcee4d8cc2639153866e59606f3e343eba06e26/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L2209)):*
> ```Java
>     TODO enable once compression supports all networks
>     if (db && !compressedDataPlaneDependenciesExist(_testrigSettings)) {
>       computeCompressedDataPlane();
> ```

why not just make both of these fault-tolerant and have it done?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/909)*

**Comment by anothermattbrown** [comment]
Reviewed 1 of 21 files at r1.
Review status: 0 of 22 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/909)*

**Comment by dhalperi** [comment]
Reviewed 13 of 21 files at r1, 6 of 8 files at r3.
Review status: 19 of 22 files reviewed at latest revision, 15 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/batfish/batfish/909#-L51IzdfRnt-2u4rMjW2:-L51IzdfRnt-2u4rMjW3:b-nszd6w) (no related file):*
Let's set up a time to chat. Some high-level issues:

* javadoc / readability
* unit tests
* abstractions

A lot of this is pre-existing and we should discuss what to address how/now. New code, at least, should be tested.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/DataPlanePlugin.java, line 41 at r1](https://reviewable.io:443/reviews/batfish/batfish/909#-L4lq1_RUeohip9DJm_q:-L4lq1_RUeohip9DJm_r:bm0v034) ([raw file](https://github.com/batfish/batfish/blob/5fcee4d8cc2639153866e59606f3e343eba06e26/projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/DataPlanePlugin.java#L41)):*
> ```Java
>   }
> 
>   public class ComputeDataPlaneResult {
> ```

can this be a `final static` class?

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/DataPlanePlugin.java, line 68 at r3](https://reviewable.io:443/reviews/batfish/batfish/909#-L51DKTCm8dwYK7r0-YW:-L51DKTCm8dwYK7r0-YX:bjnvo6p) ([raw file](https://github.com/batfish/batfish/blob/a9a05022c92369764c03cb8e07e70679e14b1727/projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/DataPlanePlugin.java#L68)):*
> ```Java
>   public abstract List<Flow> getHistoryFlows();
> 
>   public abstract List<Flow> getHistoryFlows(DataPlane dataPlane);
> ```

why do we need all of these new variants? Just port the old ones over?

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/IBatfish.java, line 81 at r3](https://reviewable.io:443/reviews/batfish/batfish/909#-L51DWcGnyy3CMHxJbMn:-L51DWcH0GBTXg8N-2fY:b-duc46) ([raw file](https://github.com/batfish/batfish/blob/a9a05022c92369764c03cb8e07e70679e14b1727/projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/IBatfish.java#L81)):*
> ```Java
>   SortedMap<String, SortedMap<String, SortedSet<AbstractRoute>>> getRoutes();
> 
>   SortedMap<String, SortedMap<String, SortedSet<AbstractRoute>>> getRoutes(boolean useCompression);
> ```

same comment

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 944 at r3](https://reviewable.io:443/reviews/batfish/batfish/909#-L51HBZZjWGlNmVkDk9G:-L51HBZZjWGlNmVkDk9H:b-3xo2qd) ([raw file](https://github.com/batfish/batfish/blob/a9a05022c92369764c03cb8e07e70679e14b1727/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L944)):*
> ```Java
>     // nobody is pointing to.
>     _cachedConfigurations.invalidate(_testrigSettings);
>     loadConfigurations();
> ```

invalidate right here?

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 957 at r3](https://reviewable.io:443/reviews/batfish/batfish/909#-L51HVCaSkZIehDAXeDV:-L51HVCaSkZIehDAXeDW:b-yzckls) ([raw file](https://github.com/batfish/batfish/blob/a9a05022c92369764c03cb8e07e70679e14b1727/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L957)):*
> ```Java
>   }
> 
>   private void isCompressedConfig(Configuration config) {
> ```

looks like it can be static.

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 968 at r3](https://reviewable.io:443/reviews/batfish/batfish/909#-L51HST_WoOHAge8e9zt:-L51HST_WoOHAge8e9zu:b-s88idh) ([raw file](https://github.com/batfish/batfish/blob/a9a05022c92369764c03cb8e07e70679e14b1727/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L968)):*
> ```Java
>               assert i.getGuard() != null;
>             });
>   }
> ```

what is this function for?

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 982 at r3](https://reviewable.io:443/reviews/batfish/batfish/909#-L51HehLf_JUQRsQqVQz:-L51HehLf_JUQRsQqVR-:b-i1r4pz) ([raw file](https://github.com/batfish/batfish/blob/a9a05022c92369764c03cb8e07e70679e14b1727/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L982)):*
> ```Java
>   private void saveDataPlane(ComputeDataPlaneResult result, boolean compressed) {
>     saveDataPlane(result._dataPlane, result._answerElement, compressed);
>   }
> ```

surely we don't need both these functions -- it's a private API.

---

*[projects/batfish/src/main/java/org/batfish/symbolic/abstraction/BatfishCompressor.java, line 84 at r3](https://reviewable.io:443/reviews/batfish/batfish/909#-L51K-OcsYam8Kg4Bx21:-L51K-OcsYam8Kg4Bx22:bnwytfr) ([raw file](https://github.com/batfish/batfish/blob/a9a05022c92369764c03cb8e07e70679e14b1727/projects/batfish/src/main/java/org/batfish/symbolic/abstraction/BatfishCompressor.java#L84)):*
> ```Java
>                             tup.getFirst().getPrefixes(),
>                             entry.getValue().getFirst().getPrefixes()))),
>                 tup.getSecond()));
> ```

This is begging for actual types.

The fact that we can't come up with better names than `newMap` and `oldMap` indicate the murkiness of the semantics of this code.

---

*[projects/batfish/src/main/java/org/batfish/symbolic/abstraction/BatfishCompressor.java, line 97 at r3](https://reviewable.io:443/reviews/batfish/batfish/909#-L51JgTN9RpvppMGPmJr:-L51JgTN9RpvppMGPmJs:b-ttmk9z) ([raw file](https://github.com/batfish/batfish/blob/a9a05022c92369764c03cb8e07e70679e14b1727/projects/batfish/src/main/java/org/batfish/symbolic/abstraction/BatfishCompressor.java#L97)):*
> ```Java
>   }
> 
>   private Prefix makeCanonical(Prefix p) {
> ```

what is this for?

---

*[projects/batfish/src/main/java/org/batfish/symbolic/abstraction/BatfishCompressor.java, line 109 at r3](https://reviewable.io:443/reviews/batfish/batfish/909#-L51Jj2gXizh2Ojf6vDp:-L51Jj2gXizh2Ojf6vDq:b-9unw6p) ([raw file](https://github.com/batfish/batfish/blob/a9a05022c92369764c03cb8e07e70679e14b1727/projects/batfish/src/main/java/org/batfish/symbolic/abstraction/BatfishCompressor.java#L109)):*
> ```Java
>     // System.out.println("Slice DstIps:    " + slice.getHeaderSpace().getDstIps());
>     // System.out.println("Slice NotDstIps: " + slice.getHeaderSpace().getNotDstIps());
>     // System.out.println("Is default case: " + slice.getIsDefaultCase());
> ```

delete?

---

*[projects/batfish/src/main/java/org/batfish/symbolic/abstraction/BatfishCompressor.java, line 149 at r3](https://reviewable.io:443/reviews/batfish/batfish/909#-L51JmzlJtxmyC8Ii2TT:-L51JmzlJtxmyC8Ii2TU:b85se8u) ([raw file](https://github.com/batfish/batfish/blob/a9a05022c92369764c03cb8e07e70679e14b1727/projects/batfish/src/main/java/org/batfish/symbolic/abstraction/BatfishCompressor.java#L149)):*
> ```Java
> 
>   private List<Statement> applyFilters(
>       List<Statement> statements, @Nullable Tuple<PrefixTrie, Boolean> tup) {
> ```

Generally, not a fan of prevalence of tuples. What is this type of tuple for?

---

*[projects/batfish/src/main/java/org/batfish/symbolic/abstraction/BatfishCompressor.java, line 165 at r3](https://reviewable.io:443/reviews/batfish/batfish/909#-L51Jr3alKwTASCJVOzh:-L51Jr3alKwTASCJVOzi:bvsqwyu) ([raw file](https://github.com/batfish/batfish/blob/a9a05022c92369764c03cb8e07e70679e14b1727/projects/batfish/src/main/java/org/batfish/symbolic/abstraction/BatfishCompressor.java#L165)):*
> ```Java
>         elements.add(new RegexAsPathSetElem(_internalRegex));
>         ExplicitAsPathSet expr = new ExplicitAsPathSet(elements);
>         MatchAsPath matchPath = new MatchAsPath(expr);
> ```

comments?

---

*[projects/batfish/src/main/java/org/batfish/symbolic/abstraction/BatfishCompressor.java, line 250 at r3](https://reviewable.io:443/reviews/batfish/batfish/909#-L51JsojweHrdJvU-X9k:-L51JsojweHrdJvU-X9l:b-9unw76) ([raw file](https://github.com/batfish/batfish/blob/a9a05022c92369764c03cb8e07e70679e14b1727/projects/batfish/src/main/java/org/batfish/symbolic/abstraction/BatfishCompressor.java#L250)):*
> ```Java
>         System.out.println("  filter: " + filt);
>       }
>     }); */
> ```

delete.

---

*[projects/batfish/src/main/java/org/batfish/symbolic/abstraction/DestinationClasses.java, line 109 at r3](https://reviewable.io:443/reviews/batfish/batfish/909#-L51KK95ATzQDfa1auFQ:-L51KK95ATzQDfa1auFR:bk1698j) ([raw file](https://github.com/batfish/batfish/blob/a9a05022c92369764c03cb8e07e70679e14b1727/projects/batfish/src/main/java/org/batfish/symbolic/abstraction/DestinationClasses.java#L109)):*
> ```Java
>             .flatMap(e -> e.getValue().stream())
>             .map(pfx -> new IpWildcard(pfx))
>             .collect(Collectors.toList()));
> ```

streams and efficiency -- lets chat?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/909)*

**Comment by anothermattbrown** [comment]
Review status: 19 of 22 files reviewed at latest revision, 15 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/DataPlanePlugin.java, line 68 at r3](https://reviewable.io:443/reviews/batfish/batfish/909#-L51DKTCm8dwYK7r0-YW:-L51T7ke4jl8yeoY2TSA:b-41opgi) ([raw file](https://github.com/batfish/batfish/blob/a9a05022c92369764c03cb8e07e70679e14b1727/projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/DataPlanePlugin.java#L68)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

why do we need all of these new variants? Just port the old ones over?
</blockquote></details>

I figured it made sense to give these new parameters default values. I'm fine either way though.

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 968 at r3](https://reviewable.io:443/reviews/batfish/batfish/909#-L51HST_WoOHAge8e9zt:-L51T_BoYSsvzcqwMxGH:bu7kvth) ([raw file](https://github.com/batfish/batfish/blob/a9a05022c92369764c03cb8e07e70679e14b1727/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L968)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

what is this function for?
</blockquote></details>

Sanity checking. I'll move it to a unit test.

---

*[projects/batfish/src/main/java/org/batfish/symbolic/abstraction/BatfishCompressor.java, line 97 at r3](https://reviewable.io:443/reviews/batfish/batfish/909#-L51JgTN9RpvppMGPmJr:-L51U95ZFhlBa4tlFw9o:b4y9sq8) ([raw file](https://github.com/batfish/batfish/blob/a9a05022c92369764c03cb8e07e70679e14b1727/projects/batfish/src/main/java/org/batfish/symbolic/abstraction/BatfishCompressor.java#L97)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

what is this for?
</blockquote></details>

Unused, so I deleted it.

---

*[projects/batfish/src/main/java/org/batfish/symbolic/abstraction/DestinationClasses.java, line 109 at r3](https://reviewable.io:443/reviews/batfish/batfish/909#-L51KK95ATzQDfa1auFQ:-L54G5cnWazDGI2lw4xF:bvqurqm) ([raw file](https://github.com/batfish/batfish/blob/a9a05022c92369764c03cb8e07e70679e14b1727/projects/batfish/src/main/java/org/batfish/symbolic/abstraction/DestinationClasses.java#L109)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

streams and efficiency -- lets chat?
</blockquote></details>

yes, I'll setup the meeting for monday morning

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/909)*

**Comment by anothermattbrown** [comment]
Review status: 19 of 22 files reviewed at latest revision, 15 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 944 at r3](https://reviewable.io:443/reviews/batfish/batfish/909#-L51HBZZjWGlNmVkDk9G:-L5A5rX4HsJe7MX1t9PD:b-2ibf4t) ([raw file](https://github.com/batfish/batfish/blob/a9a05022c92369764c03cb8e07e70679e14b1727/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L944)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

invalidate right here?
</blockquote></details>

Can't until the after the next line. It would be better to make the configs a parameter to BatfishCompressor instead of Batfish, but that will require refactoring a lot of the abstraction code. That may be better left for later.

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 982 at r3](https://reviewable.io:443/reviews/batfish/batfish/909#-L51HehLf_JUQRsQqVQz:-L5A5kc5CiegzzO7f_1x:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/a9a05022c92369764c03cb8e07e70679e14b1727/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L982)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

surely we don't need both these functions -- it's a private API.
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/symbolic/abstraction/BatfishCompressor.java, line 109 at r3](https://reviewable.io:443/reviews/batfish/batfish/909#-L51Jj2gXizh2Ojf6vDp:-L5A5bp5wjBGgRPnFrp5:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/a9a05022c92369764c03cb8e07e70679e14b1727/projects/batfish/src/main/java/org/batfish/symbolic/abstraction/BatfishCompressor.java#L109)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

delete?
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/symbolic/abstraction/BatfishCompressor.java, line 149 at r3](https://reviewable.io:443/reviews/batfish/batfish/909#-L51JmzlJtxmyC8Ii2TT:-L5A5NjiZ7ylSjEUFnBc:boi21rb) ([raw file](https://github.com/batfish/batfish/blob/a9a05022c92369764c03cb8e07e70679e14b1727/projects/batfish/src/main/java/org/batfish/symbolic/abstraction/BatfishCompressor.java#L149)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Generally, not a fan of prevalence of tuples. What is this type of tuple for?
</blockquote></details>

I'll replace it with something more readable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/909)*

**Comment by dhalperi** [comment]
Reviewed 12 of 12 files at r4.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/DataPlanePlugin.java, line 68 at r3](https://reviewable.io:443/reviews/batfish/batfish/909#-L51DKTCm8dwYK7r0-YW:-L5LyW5ZHYhhas0V__Hr:b-yd6ep6) ([raw file](https://github.com/batfish/batfish/blob/a9a05022c92369764c03cb8e07e70679e14b1727/projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/DataPlanePlugin.java#L68)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

I figured it made sense to give these new parameters default values. I'm fine either way though.
</blockquote></details>

Please port -- less redundancy up front is better.

---

*[projects/batfish/src/main/java/org/batfish/symbolic/abstraction/BatfishCompressor.java, line 149 at r3](https://reviewable.io:443/reviews/batfish/batfish/909#-L51JmzlJtxmyC8Ii2TT:-L5LzmkzxK-cZ5hPGIn5:b-89offq) ([raw file](https://github.com/batfish/batfish/blob/a9a05022c92369764c03cb8e07e70679e14b1727/projects/batfish/src/main/java/org/batfish/symbolic/abstraction/BatfishCompressor.java#L149)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

I'll replace it with something more readable.
</blockquote></details>

Still planned or no?

---

*[projects/batfish/src/test/java/org/batfish/symbolic/abstraction/BatfishCompressionTest.java, line 119 at r4](https://reviewable.io:443/reviews/batfish/batfish/909#-L5LzWoLLT15D9FFA2ar:-L5LzWoLLT15D9FFA2as:b-87yw00) ([raw file](https://github.com/batfish/batfish/blob/ec8bbbc6547aa2e5906fee1bc34ba787dcec307d/projects/batfish/src/test/java/org/batfish/symbolic/abstraction/BatfishCompressionTest.java#L119)):*
> ```Java
> 
>     compressedConfigs.values().forEach(BatfishCompressionTest::assertIsCompressedConfig);
>     assert origFibs.keySet().equals(compressedFibs.keySet());
> ```

use junit asserts instead?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/909)*

**Comment by dhalperi** [comment]
Reviewed 10 of 10 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/test/java/org/batfish/symbolic/abstraction/BatfishCompressionTest.java, line 119 at r4](https://reviewable.io:443/reviews/batfish/batfish/909#-L5LzWoLLT15D9FFA2ar:-L5SJy8HTL5tJjRDptkh:b-ocvw2r) ([raw file](https://github.com/batfish/batfish/blob/ec8bbbc6547aa2e5906fee1bc34ba787dcec307d/projects/batfish/src/test/java/org/batfish/symbolic/abstraction/BatfishCompressionTest.java#L119)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

use junit asserts instead?
</blockquote></details>

OK

trivial comment remaining

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/909)*

**Comment by dhalperi** [comment]
Reviewed 6 of 6 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish/src/test/java/org/batfish/symbolic/abstraction/BatfishCompressionTest.java, line 119 at r4](https://reviewable.io:443/reviews/batfish/batfish/909#-L5LzWoLLT15D9FFA2ar:-L5k71swPjubY7rwAtf9:b-ary8mj) ([raw file](https://github.com/batfish/batfish/blob/ec8bbbc6547aa2e5906fee1bc34ba787dcec307d/projects/batfish/src/test/java/org/batfish/symbolic/abstraction/BatfishCompressionTest.java#L119)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

OK

trivial comment remaining
</blockquote></details>

still see a use of plain `assert` here.

---

*[projects/batfish/src/test/java/org/batfish/symbolic/abstraction/SetMatchers.java, line 9 at r6](https://reviewable.io:443/reviews/batfish/batfish/909#-L5k6py_3lDMkrlwXl_1:-L5k6pyaxucI2XJ_73Ev:b9n2l6j) ([raw file](https://github.com/batfish/batfish/blob/65c189057863f82d1e06f4fc9866dc6f8bf053be/projects/batfish/src/test/java/org/batfish/symbolic/abstraction/SetMatchers.java#L9)):*
> ```Java
> 
> public class SetMatchers {
>   public static <T> Matcher<Set<T>> isSubsetOf(Set<T> superSet) {
> ```

can you just use `Matchers#hasItems`, perhaps backwards?

high-level: suspicious of inventing a new matcher for a base type.  Seems like something that should exist. Are we sure we're not missing an API?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/909)*

**Comment by anothermattbrown** [comment]
Review status: 21 of 27 files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/symbolic/abstraction/BatfishCompressor.java, line 149 at r3](https://reviewable.io:443/reviews/batfish/batfish/909#-L51JmzlJtxmyC8Ii2TT:-L5UcT4ww6YNtfdBiwcH:bb77ufg) ([raw file](https://github.com/batfish/batfish/blob/a9a05022c92369764c03cb8e07e70679e14b1727/projects/batfish/src/main/java/org/batfish/symbolic/abstraction/BatfishCompressor.java#L149)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Still planned or no?
</blockquote></details>

Yes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/909)*

**Comment by dhalperi** [comment]
:lgtm:

---

Reviewed 12 of 12 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/909#-:-L5oIpWNi2umPAfB0lQ_:bnfp4nl)*

**Pull request merged**
