### PR TITLE
simplify the answer for bgpadvertisements question, and remove jackson ids

### PR DESCRIPTION
**Pull request by ratulm**
Also removed the override answerDiff(). With the new structure, the default diff should be good enough.

---
This change is [Reviewable](https://reviewable.io/reviews/batfish/batfish/963)

### CODE REVIEW

**Comment by arifogel** [comment]
Mostly good. Please make suggested immutability changes, and fix typo.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/question/src/main/java/org/batfish/question/BgpAdvertisementsQuestionPlugin.java, line 35 at r1](https://beta.reviewable.io/reviews/batfish/batfish/963#-L5ohXTP0r2DWHLCO_eS:-L5ohXTP0r2DWHLCO_eT:b561i75) ([raw file](https://github.com/batfish/batfish/blob/22432b27cda82093dde3bf2f7a27ee58e50c352e/projects/question/src/main/java/org/batfish/question/BgpAdvertisementsQuestionPlugin.java#L35)):*
> ```Java
>     @JsonCreator
>     public BgpAdvertisementsAnswerElement() {
>       _bgpAdvertisements = new TreeMap<>();
> ```

Use `ImmutableSortedMap.of()`. This map won't be modified anyway. Also, this constructor can probably be private.

---

*[projects/question/src/main/java/org/batfish/question/BgpAdvertisementsQuestionPlugin.java, line 118 at r1](https://beta.reviewable.io/reviews/batfish/batfish/963#-L5ogRu4EwJ4uKwOZ5fv:-L5ogRu4EwJ4uKwOZ5fw:b-igk60g) ([raw file](https://github.com/batfish/batfish/blob/22432b27cda82093dde3bf2f7a27ee58e50c352e/projects/question/src/main/java/org/batfish/question/BgpAdvertisementsQuestionPlugin.java#L118)):*
> ```Java
>       StringBuilder sb = new StringBuilder();
>       for (String hostname : _bgpAdvertisements.keySet()) {
>         for (BgpAdvertisement advert : _bgpAdvertisements.get(hostname)) {
> ```

If you are using both key and value, just do:
`_bgpAdvertisements.forEach((hostname, advert) -> sb.append(advert.prettyPrint(hostname + " "));`

---

*[projects/question/src/main/java/org/batfish/question/BgpAdvertisementsQuestionPlugin.java, line 127 at r1](https://beta.reviewable.io/reviews/batfish/batfish/963#-L5ogLjU09XqSy5QZhUz:-L5ogLjU09XqSy5QZhV-:b-9ob0be) ([raw file](https://github.com/batfish/batfish/blob/22432b27cda82093dde3bf2f7a27ee58e50c352e/projects/question/src/main/java/org/batfish/question/BgpAdvertisementsQuestionPlugin.java#L127)):*
> ```Java
> 
>     @JsonProperty(PROP_BGP_ADVERTISEMENTS)
>     public void setbgpAdvertisements(
> ```

`setbgpAdvertisements` -> `setBgpAdvertisements`

---

*[projects/question/src/main/java/org/batfish/question/BgpAdvertisementsQuestionPlugin.java, line 129 at r1](https://beta.reviewable.io/reviews/batfish/batfish/963#-L5oi3D_1zls06tW3eHI:-L5oi3D_1zls06tW3eHJ:b-2aqmsc) ([raw file](https://github.com/batfish/batfish/blob/22432b27cda82093dde3bf2f7a27ee58e50c352e/projects/question/src/main/java/org/batfish/question/BgpAdvertisementsQuestionPlugin.java#L129)):*
> ```Java
>     public void setbgpAdvertisements(
>         SortedMap<String, SortedSet<BgpAdvertisement>> bgpAdvertisements) {
>       _bgpAdvertisements = bgpAdvertisements;
> ```

Please use:
`_bgpAdvertisements = bgpAdvertisements.entrySet().stream().collect(ImmtuableSortedMap.toImmutableSortedMap(Entry::getKey, e -> ImmutableSortedSet.copyOf(e.getValue()));`. Then call this function at end of constructor(s) that build up `_bgpAdvertisements` (or change strategy so that sets and maps are immutable by the time the field is set).

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/963#-:-L5ojagw4_S6cOLS5xaW:b-dq6s3a)*

**Comment by ratulm** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[projects/question/src/main/java/org/batfish/question/BgpAdvertisementsQuestionPlugin.java, line 35 at r1](https://beta.reviewable.io/reviews/batfish/batfish/963#-L5ohXTP0r2DWHLCO_eS:-L5pMjaNCUgZS1RkmHu6:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/22432b27cda82093dde3bf2f7a27ee58e50c352e/projects/question/src/main/java/org/batfish/question/BgpAdvertisementsQuestionPlugin.java#L35)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Use `ImmutableSortedMap.of()`. This map won't be modified anyway. Also, this constructor can probably be private.
</blockquote></details>

Done.

---

*[projects/question/src/main/java/org/batfish/question/BgpAdvertisementsQuestionPlugin.java, line 118 at r1](https://beta.reviewable.io/reviews/batfish/batfish/963#-L5ogRu4EwJ4uKwOZ5fv:-L5pNbCj9-hPeyGpTz4q:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/22432b27cda82093dde3bf2f7a27ee58e50c352e/projects/question/src/main/java/org/batfish/question/BgpAdvertisementsQuestionPlugin.java#L118)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

If you are using both key and value, just do:
`_bgpAdvertisements.forEach((hostname, advert) -> sb.append(advert.prettyPrint(hostname + " "));`
</blockquote></details>

Done.

---

*[projects/question/src/main/java/org/batfish/question/BgpAdvertisementsQuestionPlugin.java, line 127 at r1](https://beta.reviewable.io/reviews/batfish/batfish/963#-L5ogLjU09XqSy5QZhUz:-L5pNeDDD5YiAn2L8_El:br6krry) ([raw file](https://github.com/batfish/batfish/blob/22432b27cda82093dde3bf2f7a27ee58e50c352e/projects/question/src/main/java/org/batfish/question/BgpAdvertisementsQuestionPlugin.java#L127)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

`setbgpAdvertisements` -> `setBgpAdvertisements`
</blockquote></details>

nixed the function.

---

*[projects/question/src/main/java/org/batfish/question/BgpAdvertisementsQuestionPlugin.java, line 129 at r1](https://beta.reviewable.io/reviews/batfish/batfish/963#-L5oi3D_1zls06tW3eHI:-L5pMi63EEkkWjG6sS9c:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/22432b27cda82093dde3bf2f7a27ee58e50c352e/projects/question/src/main/java/org/batfish/question/BgpAdvertisementsQuestionPlugin.java#L129)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Please use:
`_bgpAdvertisements = bgpAdvertisements.entrySet().stream().collect(ImmtuableSortedMap.toImmutableSortedMap(Entry::getKey, e -> ImmutableSortedSet.copyOf(e.getValue()));`. Then call this function at end of constructor(s) that build up `_bgpAdvertisements` (or change strategy so that sets and maps are immutable by the time the field is set).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/963)*

**Comment by arifogel** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/question/src/main/java/org/batfish/question/BgpAdvertisementsQuestionPlugin.java, line 118 at r1](https://beta.reviewable.io/reviews/batfish/batfish/963#-L5ogRu4EwJ4uKwOZ5fv:-L5pltz_1g4d-D5UryrD:b-snhzhj) ([raw file](https://github.com/batfish/batfish/blob/22432b27cda82093dde3bf2f7a27ee58e50c352e/projects/question/src/main/java/org/batfish/question/BgpAdvertisementsQuestionPlugin.java#L118)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The inner `forEach` can omit parentheses, braces, and `;`

---

*[projects/question/src/main/java/org/batfish/question/BgpAdvertisementsQuestionPlugin.java, line 131 at r2](https://beta.reviewable.io/reviews/batfish/batfish/963#-L5pm4PU4uMtH2Hlht8M:-L5pm4PU4uMtH2Hlht8N:b5v646r) ([raw file](https://github.com/batfish/batfish/blob/10be4233279e3ba3b2a312dabe92dc228bdfa01e/projects/question/src/main/java/org/batfish/question/BgpAdvertisementsQuestionPlugin.java#L131)):*
> ```Java
>           .collect(
>               ImmutableSortedMap.toImmutableSortedMap(
>                   String::compareTo,
> ```

`String::compareTo` -> `Ordering.natural()`. Generally use the latter unless you are overriding default behavior.

---

*[projects/question/src/main/java/org/batfish/question/BgpAdvertisementsQuestionPlugin.java, line 132 at r2](https://beta.reviewable.io/reviews/batfish/batfish/963#-L5pmn9b5y4Sj4gtDXFM:-L5pmn9b5y4Sj4gtDXFN:bhdcs1u) ([raw file](https://github.com/batfish/batfish/blob/10be4233279e3ba3b2a312dabe92dc228bdfa01e/projects/question/src/main/java/org/batfish/question/BgpAdvertisementsQuestionPlugin.java#L132)):*
> ```Java
>               ImmutableSortedMap.toImmutableSortedMap(
>                   String::compareTo,
>                   e -> e.getKey(),
> ```

`e -> e.getKey()` -> `Entry::getKey`

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/963)*

**Comment by arifogel** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/963)*

**Comment by ratulm** [comment]
Review status: 3 of 4 files reviewed at latest revision, all discussions resolved.

---

*[projects/question/src/main/java/org/batfish/question/BgpAdvertisementsQuestionPlugin.java, line 118 at r1](https://beta.reviewable.io/reviews/batfish/batfish/963#-L5ogRu4EwJ4uKwOZ5fv:-L5pp6ZY1ICM8puOIZIb:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/22432b27cda82093dde3bf2f7a27ee58e50c352e/projects/question/src/main/java/org/batfish/question/BgpAdvertisementsQuestionPlugin.java#L118)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

The inner `forEach` can omit parentheses, braces, and `;`
</blockquote></details>

Done.

---

*[projects/question/src/main/java/org/batfish/question/BgpAdvertisementsQuestionPlugin.java, line 131 at r2](https://beta.reviewable.io/reviews/batfish/batfish/963#-L5pm4PU4uMtH2Hlht8M:-L5poVIN45M9hMoGaEuU:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/10be4233279e3ba3b2a312dabe92dc228bdfa01e/projects/question/src/main/java/org/batfish/question/BgpAdvertisementsQuestionPlugin.java#L131)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

`String::compareTo` -> `Ordering.natural()`. Generally use the latter unless you are overriding default behavior.
</blockquote></details>

Done.

---

*[projects/question/src/main/java/org/batfish/question/BgpAdvertisementsQuestionPlugin.java, line 132 at r2](https://beta.reviewable.io/reviews/batfish/batfish/963#-L5pmn9b5y4Sj4gtDXFM:-L5pobwHAdcghqJvMgkT:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/10be4233279e3ba3b2a312dabe92dc228bdfa01e/projects/question/src/main/java/org/batfish/question/BgpAdvertisementsQuestionPlugin.java#L132)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

`e -> e.getKey()` -> `Entry::getKey`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/963)*

**Pull request merged**
