### PR TITLE
Routes: refactor to introduce a generic next hop

### PR DESCRIPTION
**Pull request by progwriter**
Let routes have a generic next hop, and require it always be set to reduce likelihood of nonsense next hop combinations.
Next hop (currently) can be one of: discard, next hop ip, next hop interface (with optional ARP ip). Existing functions to modify next hop kept for backwards compatibility but they are not preferred.

Suggest reviewing commit by commit:
- Core data structures
- Update routes classes and production code
- Fixup test wherever we were making nonsense nexthops, make use of testBuilders for convenience
- Ref updates.

Note: introducing next VRF as a special type of next hop is coming up in a followup PR.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6545)* status: 6 of 139 files reviewed, 4 unresolved discussions (waiting on @dhalperi and @progwriter)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/route/nh/NextHop.java, line 36 at r1](https://reviewable.io/reviews/batfish/batfish/6545#-MQOEnAy4u8livGKecMa:-MQOEnAz4j-uoRoflzBe:b-4czlpj) ([raw file](https://github.com/batfish/batfish/blob/01daede01430c20855a75bbb946cb8eb48b66184/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/route/nh/NextHop.java#L36)):*
> ```
> return NextHopDiscard.instance();
> ```
is this an expected case? when?
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/route/nh/NextHopInterface.java, line 73 at r1](https://reviewable.io/reviews/batfish/batfish/6545#-MQOFKA54uvjJIvyI6fe:-MQOFKA54uvjJIvyI6ff:b-guehy0) ([raw file](https://github.com/batfish/batfish/blob/01daede01430c20855a75bbb946cb8eb48b66184/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/route/nh/NextHopInterface.java#L73)):*
> ```
> This hashcode could be hot,
> ```
is it worth memoizing?
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/route/nh/NextHopInterface.java, line 79 at r1](https://reviewable.io/reviews/batfish/batfish/6545#-MQOFRUs7_Pbz_b11siE:-MQOFRUs7_Pbz_b11siF:bv7m4r9) ([raw file](https://github.com/batfish/batfish/blob/01daede01430c20855a75bbb946cb8eb48b66184/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/route/nh/NextHopInterface.java#L79)):*
> ```Java
>   @Override
>   public String toString() {
>     return MoreObjects.toStringHelper(NextHopInterface.class)
> ```

consider omitNullValues()
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/route/nh/NextHopInterface.java, line 99 at r1](https://reviewable.io/reviews/batfish/batfish/6545#-MQOGfU843bG3cV3vDFq:-MQOGfU92tSiBlI4hIbU:b-urn290) ([raw file](https://github.com/batfish/batfish/blob/01daede01430c20855a75bbb946cb8eb48b66184/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/route/nh/NextHopInterface.java#L99)):*
> ```
> d",
> ```
missing %s?

**Review by dhalperi — COMMENTED** [review]
> Reviewed 42 of 42 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6545)* status: 48 of 139 files reviewed, 9 unresolved discussions (waiting on @progwriter)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/protocols/StaticRouteHelper.java, line 32 at r2](https://reviewable.io/reviews/batfish/batfish/6545#-MQOHEOZ5oQDQ1eO1e9p:-MQOHEOZ5oQDQ1eO1e9q:becl9k9) ([raw file](https://github.com/batfish/batfish/blob/f5e0016b85797e710cd7e529948bf8c85ee2ec36/projects/batfish/src/main/java/org/batfish/dataplane/protocols/StaticRouteHelper.java#L32)):*
> ```Java
>       @Override
>       public Boolean visitNextHopDiscard(NextHopDiscard nextHopDiscard) {
>         return true;
> ```

(I know this is a direct translation)

Why does this happen?
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java, line 3639 at r2](https://reviewable.io/reviews/batfish/batfish/6545#-MQOHi207S4Kc8tEAqBj:-MQOHi207S4Kc8tEAqBk:b-uethir) ([raw file](https://github.com/batfish/batfish/blob/f5e0016b85797e710cd7e529948bf8c85ee2ec36/projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java#L3639)):*
> ```
> return null;
> ```
this should be unreachable, I guess? Warn?
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AbstractRoute.java, line 159 at r2](https://reviewable.io/reviews/batfish/batfish/6545#-MQOIcuY7-RYPZP3VaB2:-MQOIcuY7-RYPZP3VaB3:b-orx8hq) ([raw file](https://github.com/batfish/batfish/blob/f5e0016b85797e710cd7e529948bf8c85ee2ec36/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AbstractRoute.java#L159)):*
> ```Java
>   // Helper package methods
>   @Nonnull
>   static NextHopVisitor<Ip> nextHopIpExtractor() {
> ```

make this a static property and just return that instance?

otherwise a lot of churn anytime this is invoked.

(e.g.,

```
private static NextHopVisitor<I[> IP_VISITOR = new Next...
```
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EigrpInternalRoute.java, line 40 at r2](https://reviewable.io/reviews/batfish/batfish/6545#-MQOLwy8Ba0caUAufgvS:-MQOLwy8Ba0caUAufgvT:btl52ed) ([raw file](https://github.com/batfish/batfish/blob/f5e0016b85797e710cd7e529948bf8c85ee2ec36/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EigrpInternalRoute.java#L40)):*
> ```Java
>       @Nullable @JsonProperty(PROP_NETWORK) Prefix network,
>       @Nullable @JsonProperty(PROP_NEXT_HOP_IP) Ip nextHopIp,
>       @Nullable @JsonProperty(PROP_NEXT_HOP_INTERFACE) String nextHopInterface,
> ```

if this is always present on json model, is this not required?
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/StaticRoute.java, line 93 at r2](https://reviewable.io/reviews/batfish/batfish/6545#-MQON82gDlStbDk6GJ2G:-MQON82gDlStbDk6GJ2H:bmu5mny) ([raw file](https://github.com/batfish/batfish/blob/f5e0016b85797e710cd7e529948bf8c85ee2ec36/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/StaticRoute.java#L93)):*
> ```Java
>   }
> 
>   public static Builder testBuilder() {
> ```

can mark these all as `@VisibleForTesting` to ensure production code doesn't use it.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 88 of 88 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6545)* status: 136 of 139 files reviewed, 9 unresolved discussions (waiting on @progwriter)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6545)* status: all files reviewed, 9 unresolved discussions (waiting on @progwriter)

**Comment by dhalperi** [comment]
*[a discussion](https://reviewable.io/reviews/batfish/batfish/6545#-MQOPf4RAMeRpukucCG_:-MQOPf4RAMeRpukucCGa:b-bm9ozw) (no related file):*
:lgtm: only thing I see missing is some json tests of some routes, that's the main coverage gap

---

**Review by progwriter — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6545)* status: 125 of 139 files reviewed, 1 unresolved discussion (waiting on @dhalperi)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6545#-MQOPf4RAMeRpukucCG_:-MQOqxOa20aN9cZcSCA7:bioy0h9) (no related file):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

:lgtm: only thing I see missing is some json tests of some routes, that's the main coverage gap
</blockquote></details>

yeah... I'm going to try and move in the direction of no routes but static/generated/kernel should be json-serializable.

---
___
*[projects/batfish/src/main/java/org/batfish/dataplane/protocols/StaticRouteHelper.java, line 32 at r2](https://reviewable.io/reviews/batfish/batfish/6545#-MQOHEOZ5oQDQ1eO1e9p:-MQOolB9DZEcEQ28ScyQ:bz87rmo) ([raw file](https://github.com/batfish/batfish/blob/f5e0016b85797e710cd7e529948bf8c85ee2ec36/projects/batfish/src/main/java/org/batfish/dataplane/protocols/StaticRouteHelper.java#L32)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

(I know this is a direct translation)

Why does this happen?
</blockquote></details>

because null routes have to be installed unconditionally, [see code](https://github.com/batfish/batfish/blob/master/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java#L834-L842)

My follow up PR will make this a lot less awkward
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java, line 3639 at r2](https://reviewable.io/reviews/batfish/batfish/6545#-MQOHi207S4Kc8tEAqBj:-MQOpqUE6eWNXIbiYnIO:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/f5e0016b85797e710cd7e529948bf8c85ee2ec36/projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java#L3639)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> return null;
> ```
this should be unreachable, I guess? Warn?
</blockquote></details>

done
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AbstractRoute.java, line 159 at r2](https://reviewable.io/reviews/batfish/batfish/6545#-MQOIcuY7-RYPZP3VaB2:-MQOqIdTEBpdtLe-OSJ9:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/f5e0016b85797e710cd7e529948bf8c85ee2ec36/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AbstractRoute.java#L159)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

make this a static property and just return that instance?

otherwise a lot of churn anytime this is invoked.

(e.g.,

```
private static NextHopVisitor<I[> IP_VISITOR = new Next...
```
</blockquote></details>

done
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EigrpInternalRoute.java, line 40 at r2](https://reviewable.io/reviews/batfish/batfish/6545#-MQOLwy8Ba0caUAufgvS:-MQOqu1f5KTZBIwXY1e_:b-1ny5au) ([raw file](https://github.com/batfish/batfish/blob/f5e0016b85797e710cd7e529948bf8c85ee2ec36/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EigrpInternalRoute.java#L40)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

if this is always present on json model, is this not required?
</blockquote></details>

:facepalm: fixed
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/StaticRoute.java, line 93 at r2](https://reviewable.io/reviews/batfish/batfish/6545#-MQON82gDlStbDk6GJ2G:-MQPAQ812QzAMj4f9M5E:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/f5e0016b85797e710cd7e529948bf8c85ee2ec36/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/StaticRoute.java#L93)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

can mark these all as `@VisibleForTesting` to ensure production code doesn't use it.
</blockquote></details>

done
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/route/nh/NextHop.java, line 36 at r1](https://reviewable.io/reviews/batfish/batfish/6545#-MQOEnAy4u8livGKecMa:-MQPAF306tvjQd2wavOW:b-dylspu) ([raw file](https://github.com/batfish/batfish/blob/01daede01430c20855a75bbb946cb8eb48b66184/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/route/nh/NextHop.java#L36)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> return NextHopDiscard.instance();
> ```
is this an expected case? when?
</blockquote></details>

not intentionally. fixed.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/route/nh/NextHopInterface.java, line 73 at r1](https://reviewable.io/reviews/batfish/batfish/6545#-MQOFKA54uvjJIvyI6fe:-MQOoRAo2y1B5Xrdlp7g:bwqd6qj) ([raw file](https://github.com/batfish/batfish/blob/01daede01430c20855a75bbb946cb8eb48b66184/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/route/nh/NextHopInterface.java#L73)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> This hashcode could be hot,
> ```
is it worth memoizing?
</blockquote></details>

I'm hoping it's not that bad, especially considering the "important" routes already have their hashcode cached. 
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/route/nh/NextHopInterface.java, line 79 at r1](https://reviewable.io/reviews/batfish/batfish/6545#-MQOFRUs7_Pbz_b11siE:-MQOofo741PI77zyCsew:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/01daede01430c20855a75bbb946cb8eb48b66184/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/route/nh/NextHopInterface.java#L79)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

consider omitNullValues()
</blockquote></details>

done
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/route/nh/NextHopInterface.java, line 99 at r1](https://reviewable.io/reviews/batfish/batfish/6545#-MQOGfU843bG3cV3vDFq:-MQOoguM9k35O9jEbm9U:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/01daede01430c20855a75bbb946cb8eb48b66184/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/route/nh/NextHopInterface.java#L99)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> d",
> ```
missing %s?
</blockquote></details>

done

**Review by progwriter — COMMENTED** [review]
> Reviewed 14 of 14 files at r5.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6545)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dhalperi — COMMENTED** [review]
> Reviewed 5 of 14 files at r5.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6545)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
