### PR TITLE
Z3 timeout

### PR DESCRIPTION
**Pull request by anothermattbrown**
Added a batfish setting for Z3's `timeout` parameter. Passed it to Z3 in Minesweeper's `PropertyChecker` and Batfish's `NodJob` and `CompositNodJob` classes. Had to add some plumbing to get the Settings object to `PropertyChecker`.

---
This change is [Reviewable](https://reviewable.io/reviews/batfish/batfish/855)

### CODE REVIEW

**Comment by dhalperi** [comment]
High-level LGTM.

Most of the code gets the settings by calling `Main.getSettings()` or something like that, but I actually prefer injecting it as your SMT changes are structured. Static shared state prevents us from running more than 1 worker in the same process, makes testing harder, etc.

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/basic/z3timeout.ref, line 11 at r1](https://reviewable.io:443/reviews/batfish/batfish/855#-L30H-TTkHAaNFd2T_Z-:-L30H-TTkHAaNFd2T_Z0:bjlbsko) ([raw file](https://github.com/batfish/batfish/blob/55a9823d6cf6e30c650f14d8f135bb54acec31c3/tests/basic/z3timeout.ref#L11)):*
> ```
>         "   at org.batfish.main.Driver$1.run(Driver.java:367)",
>         "Caused by: org.batfish.common.BatfishException: Error executing job",
>         "   at org.batfish.job.BatfishJobExecutor.executeJobs(BatfishJobExecutor.java:129)",
> ```

This test is brittle -- it's going to require updating the ref anytime code changes (Batfish.java line numbers, for example).

I think there's a different test that simply expects an error, try to find that one?

---

*[tests/java-smt/commands, line 143 at r1](https://reviewable.io:443/reviews/batfish/batfish/855#-L30HGEE9Guz2mTMfIbn:-L30HGEE9Guz2mTMfIbo:b-cp73hq) ([raw file](https://github.com/batfish/batfish/blob/55a9823d6cf6e30c650f14d8f135bb54acec31c3/tests/java-smt/commands#L143)):*
> ```
> 
> # z3 timeout - 1 second
> add-batfish-option z3timeout 1000
> ```

why not 1ms?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/855#-:-L34T5dRZxwheE6lmlQg:b-96pkxv)*

**Comment by anothermattbrown** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/basic/z3timeout.ref, line 11 at r1](https://reviewable.io:443/reviews/batfish/batfish/855#-L30H-TTkHAaNFd2T_Z-:-L35dTOElTLRXSez0PxA:bh2hrn2) ([raw file](https://github.com/batfish/batfish/blob/55a9823d6cf6e30c650f14d8f135bb54acec31c3/tests/basic/z3timeout.ref#L11)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

This test is brittle -- it's going to require updating the ref anytime code changes (Batfish.java line numbers, for example).

I think there's a different test that simply expects an error, try to find that one?
</blockquote></details>

Aha, looks like the ref file isn't checked for `-error` tests, so I could use an empty ref file instead.
The only other `-error` test is `tests/basic/error.ref`, which also could be made less brittle by emptying the file.

---

*[tests/java-smt/commands, line 143 at r1](https://reviewable.io:443/reviews/batfish/batfish/855#-L30HGEE9Guz2mTMfIbn:-L35fhqI_5NyfKGnrgqf:b7arimt) ([raw file](https://github.com/batfish/batfish/blob/55a9823d6cf6e30c650f14d8f135bb54acec31c3/tests/java-smt/commands#L143)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

why not 1ms?
</blockquote></details>

good idea

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/855)*

**Comment by dhalperi** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/855)*

**Comment by dhalperi** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/855#-:-L35j_D6eE0H1BVlZi2S:bnfp4nl)*

**Pull request merged**
