### PR TITLE
Add SetAdminCost support to SRP/CRP.

### PR DESCRIPTION
**Pull request by nickgian**
Adds support for SetAdminCost in TransferBDD/SRP/CRP.

### CODE REVIEW

**Review by progwriter — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8807)* status: all files reviewed, 1 unresolved discussion (waiting on @millstein and @nickgian)

___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java` line 776 at r1](https://reviewable.io/reviews/batfish/batfish/8807#-Neng5QdBQmulnVH20gm:-Neng5QdBQmulnVH20gn:bj2xshx) ([raw file](https://github.com/batfish/batfish/blob/a210b5ec582b557763ddcd45673b48378cd2671f/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java#L776)):*
> ```Java
>       curP.getData()
>           .setAdminDist(
>               MutableBDDInteger.makeFromValue(this._factory, 8, ((LiteralInt) ie).getValue()));
> ```

should we check the value actually fits into 8 bits? I don't think `SetAdministrativeCost` enforces this

**Review by nickgian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8807)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @millstein and @progwriter)

___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java` line 776 at r1](https://reviewable.io/reviews/batfish/batfish/8807#-Neng5QdBQmulnVH20gm:-NennugP4YdLtEfVza5c:bloxi13) ([raw file](https://github.com/batfish/batfish/blob/a210b5ec582b557763ddcd45673b48378cd2671f/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java#L776)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

should we check the value actually fits into 8 bits? I don't think `SetAdministrativeCost` enforces this
</blockquote></details>

Actually looking at juniper docs it seems AD can be 0-4,294,967,295. Batfish currently models AD as an IntExpr which I believe is a signed 32-bit Int so that's problematic.
I'll switch to 31-bit Unsigned Int, matching Batfish. There is no point in doing an overflow check here I assume, except maybe that the value of the IntExpr is positive.

The proper fix is to change SetAdministrativeCost to use a LongExpr instead and then use a 32-bit BddInt here, but I don't want to go through this bigger change in this PR. I'll file an issue about it.

**Review by progwriter — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8807)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @millstein)

**Review by nickgian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8807)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @millstein and @progwriter)

___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java` line 795 at r4](https://reviewable.io/reviews/batfish/batfish/8807#-Neo4764C_ET5nFnTPvc:-Neo4764C_ET5nFnTPvd:b4cmky0) ([raw file](https://github.com/batfish/batfish/blob/ac38a5b44ac0c3b8e2b6590c52d74cb53a5b5012/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java#L795)):*
> ```Java
>       }
>       int val = ((LiteralInt) ie).getValue();
>       if (val < 0 || val > 255) {
> ```

based on Dan's comments here: https://github.com/batfish/batfish/issues/8808
I went back to 8-bit. If we feel we absolutely need to support other use cases, let's migrate everything to LongExpr and 32-bit Ints, but it feels like this is not necessary.

**Review by progwriter — COMMENTED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8807)* status: all files reviewed, 1 unresolved discussion (waiting on @millstein)

**Review by progwriter — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8807)* status: all files reviewed, 1 unresolved discussion (waiting on @millstein)

**Review by millstein — COMMENTED** [review]
> Reviewed 3 of 6 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8807)* status: all files reviewed, 3 unresolved discussions (waiting on @nickgian and @progwriter)

___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java` line 795 at r5](https://reviewable.io/reviews/batfish/batfish/8807#-Ney2qDDBCqt77G_f0YD:-Ney2qDDBCqt77G_f0YE:b7bjbgu) ([raw file](https://github.com/batfish/batfish/blob/1559a7fb47af75d3af92c50eeacf4828364ed024/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java#L795)):*
> ```Java
>       }
>       int val = ((LiteralInt) ie).getValue();
>       if (val <= 0 || val > 255) {
> ```

Is the requirement that it not be 0 enforced elsewhere?  I don't see that in the constructor for `SetAdministrativeCost` for example.  It seems weird for the symbolic analysis to enforce stronger constraints than the Batfish data model does.  (I guess the same could be said for the max of 255, but that seems less problematic because it's simply a bit-width constraint.)
___
*[`projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferBDDTest.java` line 1044 at r5](https://reviewable.io/reviews/batfish/batfish/8807#-Ney3PeJAaeqrjy1pRwq:-Ney3PeJAaeqrjy1pRwr:bgkarw9) ([raw file](https://github.com/batfish/batfish/blob/1559a7fb47af75d3af92c50eeacf4828364ed024/projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferBDDTest.java#L1044)):*
> ```Java
>     TransferBDD tbdd = new TransferBDD(_configAPs, policy);
>     List<TransferReturn> paths = tbdd.computePaths(ImmutableSet.of());
>     assertTrue(!paths.isEmpty() && paths.stream().allMatch(p -> p.getFirst().getUnsupported()));
> ```

You could make this check exact, in the same way as in the previous test -- check for exactly a list of one path, whose BDDRoute has the unsupported flag set but is otherwise a generic BDDRoute.

**Review by nickgian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8807)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @millstein and @progwriter)

___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java` line 795 at r5](https://reviewable.io/reviews/batfish/batfish/8807#-Ney2qDDBCqt77G_f0YD:-Ney7-IrE79tqDml6R0C:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/1559a7fb47af75d3af92c50eeacf4828364ed024/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java#L795)):*
<details><summary><i>Previously, millstein (Todd Millstein) wrote…</i></summary><blockquote>

Is the requirement that it not be 0 enforced elsewhere?  I don't see that in the constructor for `SetAdministrativeCost` for example.  It seems weird for the symbolic analysis to enforce stronger constraints than the Batfish data model does.  (I guess the same could be said for the max of 255, but that seems less problematic because it's simply a bit-width constraint.)
</blockquote></details>

Done.
___
*[`projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferBDDTest.java` line 1044 at r5](https://reviewable.io/reviews/batfish/batfish/8807#-Ney3PeJAaeqrjy1pRwq:-Ney6x0k8pk5BvHGzgpe:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/1559a7fb47af75d3af92c50eeacf4828364ed024/projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferBDDTest.java#L1044)):*
<details><summary><i>Previously, millstein (Todd Millstein) wrote…</i></summary><blockquote>

You could make this check exact, in the same way as in the previous test -- check for exactly a list of one path, whose BDDRoute has the unsupported flag set but is otherwise a generic BDDRoute.
</blockquote></details>

Done.

**Review by millstein — COMMENTED** [review]
> Reviewed 1 of 6 files at r4, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8807)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @progwriter)

**Review by progwriter — COMMENTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8807)* status: all files reviewed, 1 unresolved discussion

**Review by millstein — COMMENTED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8807)* status: all files reviewed, 1 unresolved discussion (waiting on @progwriter)

**Review by progwriter — COMMENTED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8807)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
