### PR TITLE
JunOS: parse and warn on no-prepend-global-as

### PR DESCRIPTION
**Pull request by dhalperi**
Add missing warnings for related constructs.

This is for batfish/batfish#6710.

### CODE REVIEW

**Review by ratulm — COMMENTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6711)* status: all files reviewed, 1 unresolved discussion (waiting on @corinaminer and @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 3842 at r1](https://reviewable.io/reviews/batfish/batfish/6711#-MVT4ZfH57VLaGBHjBCM:-MVT4ZfH57VLaGBHjBCN:b-r9rzsy) ([raw file](https://github.com/batfish/batfish/blob/a6c8a48ccffff8f10938e005206fb54efe3464f4/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L3842)):*
> ```Java
>   @Override
>   public void exitBl_no_prepend_global_as(Bl_no_prepend_global_asContext ctx) {
>     todo(ctx);
> ```

I'll double check in a bit but I thought this is what Batfish does by default. If so, we need to warn when something else happens.

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6711)* status: all files reviewed, 1 unresolved discussion (waiting on @corinaminer and @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 3842 at r1](https://reviewable.io/reviews/batfish/batfish/6711#-MVT4ZfH57VLaGBHjBCM:-MVT6kDkD4zPZegZMWaz:b548711) ([raw file](https://github.com/batfish/batfish/blob/a6c8a48ccffff8f10938e005206fb54efe3464f4/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L3842)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

I'll double check in a bit but I thought this is what Batfish does by default. If so, we need to warn when something else happens. 
</blockquote></details>

Judging by the FRR warning behavior (https://github.com/batfish/batfish/blob/e2af1bf9d24d1646ce2bc9619dd998a37a1b78fb/projects/batfish/src/main/java/org/batfish/grammar/cumulus_frr/CumulusFrrConfigurationBuilder.java#L490) which I fixed in consultation with Victor, we implement what in FRR is `no-prepend replace-as`. Per https://docs.frrouting.org/en/latest/bgp.html#clicmd-neighborPEERlocal-asAS-NUMBER[no-prepend][replace-as], this means that (only) local-as will be prepended (not global). 

IIUC, JunOS documentation (https://www.juniper.net/documentation/en_US/junos/topics/reference/configuration-statement/local-as-edit-protocols-bgp.html) says that `no-prepend-global-as` means that only local-as is prepended. 

If I am reading this all right -- no guarantee there -- then we should warn on private/alias options.

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6711)* status: 3 of 8 files reviewed, 1 unresolved discussion (waiting on @corinaminer and @ratulm)

___
*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 3842 at r1](https://reviewable.io/reviews/batfish/batfish/6711#-MVT4ZfH57VLaGBHjBCM:-MVTMn-e656rrvcJdN9z:bb73vv8) ([raw file](https://github.com/batfish/batfish/blob/a6c8a48ccffff8f10938e005206fb54efe3464f4/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L3842)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

Judging by the FRR warning behavior (https://github.com/batfish/batfish/blob/e2af1bf9d24d1646ce2bc9619dd998a37a1b78fb/projects/batfish/src/main/java/org/batfish/grammar/cumulus_frr/CumulusFrrConfigurationBuilder.java#L490) which I fixed in consultation with Victor, we implement what in FRR is `no-prepend replace-as`. Per https://docs.frrouting.org/en/latest/bgp.html#clicmd-neighborPEERlocal-asAS-NUMBER[no-prepend][replace-as], this means that (only) local-as will be prepended (not global). 

IIUC, JunOS documentation (https://www.juniper.net/documentation/en_US/junos/topics/reference/configuration-statement/local-as-edit-protocols-bgp.html) says that `no-prepend-global-as` means that only local-as is prepended. 

If I am reading this all right -- no guarantee there -- then we should warn on private/alias options. 
</blockquote></details>

TAL.

**Review by ratulm — COMMENTED** [review]
> Reviewed 3 of 5 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6711)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

**Pull request merged**
