### PR TITLE
Cisco NX-OS parse and convert track ip route

### PR DESCRIPTION
**Pull request by arifogel**
- add `TrackRoute` `TrackMethod` to datamodel
  - supports matching a route in a main RIB based on:
    - prefix
    - vrf
    - optionally, matching one of a set of protocols

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 16 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7923)* status: 15 of 16 files reviewed, all discussions resolved (waiting on @corinaminer and @dhalperi)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7923#-MtAcf8g3hUcgM9s1VpW:-MtAcf8g3hUcgM9s1VpX:bc9xt8d) (no related file):*
All comments FYI, so lgtm as-is or with addressed.

---
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosParser.g4, line 605 at r1](https://reviewable.io/reviews/batfish/batfish/7923#-MtAXJp-Ak-kOqy7x9Sx:-MtAXJp-Ak-kOqy7x9Sy:bcdrth4) ([raw file](https://github.com/batfish/batfish/blob/21fe3555c5d0626bac765f188b9b09077d68d4c4/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosParser.g4#L605)):*
> ```ANTLR
> ;
> 
> track_ip_route: ROUTE prefix = ip_prefix REACHABILITY HMM? NEWLINE track_ip_route_inner*;
> ```

(FYI) nit: tend to prefer a line break after `NEWLINE` token. Makes reading grammar much easier.
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosParser.g4, line 607 at r1](https://reviewable.io/reviews/batfish/batfish/7923#-MtAY7iB7KU12xLiQK6f:-MtAY7iB7KU12xLiQK6g:b-r6gfpd) ([raw file](https://github.com/batfish/batfish/blob/21fe3555c5d0626bac765f188b9b09077d68d4c4/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosParser.g4#L607)):*
> ```ANTLR
> track_ip_route: ROUTE prefix = ip_prefix REACHABILITY HMM? NEWLINE track_ip_route_inner*;
> 
> track_ip_route_inner: tir_vrf | tir_null;
> ```

(FYI) similarly, prefer unrelated alternatives on different lines for reading.

`UP | DOWN` is the main type of place I do this.



_Code quote:_
```ANTLR
tir_vrf | tir_null;
```
___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java, line 4894 at r1](https://reviewable.io/reviews/batfish/batfish/7923#-MtAcHlI8rgDf_wm4PeC:-MtAcHlI8rgDf_wm4PeD:b-m3voni) ([raw file](https://github.com/batfish/batfish/blob/21fe3555c5d0626bac765f188b9b09077d68d4c4/projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java#L4894)):*
> ```Java
> 
>   @Override
>   public void exitS_track(S_trackContext ctx) {
> ```

I can't tell if tracks are defined and reference-tracked or not. Future work if so.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7923)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7923)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7923)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosParser.g4, line 605 at r1](https://reviewable.io/reviews/batfish/batfish/7923#-MtAXJp-Ak-kOqy7x9Sx:-MtAscS8C2Rof4cVutdn:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/21fe3555c5d0626bac765f188b9b09077d68d4c4/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosParser.g4#L605)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

(FYI) nit: tend to prefer a line break after `NEWLINE` token. Makes reading grammar much easier.
</blockquote></details>

done
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosParser.g4, line 607 at r1](https://reviewable.io/reviews/batfish/batfish/7923#-MtAY7iB7KU12xLiQK6f:-MtAsd3z2jy4VEGVksaJ:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/21fe3555c5d0626bac765f188b9b09077d68d4c4/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosParser.g4#L607)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

(FYI) similarly, prefer unrelated alternatives on different lines for reading.

`UP | DOWN` is the main type of place I do this.
</blockquote></details>

done
___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java, line 4894 at r1](https://reviewable.io/reviews/batfish/batfish/7923#-MtAcHlI8rgDf_wm4PeC:-MtAt5se0tDOY4igqrXJ:b-97yr7e) ([raw file](https://github.com/batfish/batfish/blob/21fe3555c5d0626bac765f188b9b09077d68d4c4/projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java#L4894)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I can't tell if tracks are defined and reference-tracked or not. Future work if so.
</blockquote></details>

They are, but all as concrete structure `TRACK`.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7923)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

**Pull request merged**
