### PR TITLE
IBDP: skip an unnecessary extra iteration and cleanup

### PR DESCRIPTION
**Pull request by dhalperi**
Cleanup and comment the topology iteration code.

Fixed at least one bug: IsisTopology was not being updated every
iteration.

Moving topology iteration to after the dataplane, and pulling one out of
the while loop, also save one iteration of dataplane when the topology
doesn't change.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6189)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @anothermattbrown and @progwriter)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java, line 105 at r1](https://reviewable.io/reviews/batfish/batfish/6189#-MGyx7S-16PmD-w7btza:-MGyx7S-16PmD-w7btzb:b-r6ybxj) ([raw file](https://github.com/batfish/batfish/blob/6e6497d41aa2e0a92937c911636cc88e3d001f67/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java#L105)):*
<details><summary><i alt="summary">Quoted 12 lines of code…</i></summary>

> ```
> initialTopologyContext =
>           callerTopologyContext
>               .toBuilder()
>               .setEigrpTopology(
>                   EigrpTopologyUtils.initEigrpTopology(
>                       configurations, callerTopologyContext.getLayer3Topology()))
>               .setIsisTopology(
>                   IsisTopology.initIsisTopology(
>                       configurations, callerTopologyContext.getLayer3Topology()))
>               .setVxlanTopology(VxlanTopologyUtils.computeVxlanTopology(configurations))
>               .setTunnelTopology(TopologyUtil.computeInitialTunnelTopology(configurations))
>               .build();
> ```
</details>

FYI this code is all gone. None of these fields but `tunnel` was read from `initialTopologyContext` -- EIGRP, ISIS, VLAN are computed on-demand not by pruning edges. I moved tunnel to caller and deleted this in favor of the iterative step. (in doing so, I caught the ISIS not being updated)
___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java, line 162 at r1](https://reviewable.io/reviews/batfish/batfish/6189#-MGywCxaCf3NRmKNxhew:-MGywCxaCf3NRmKNxhex:b-x9s740) ([raw file](https://github.com/batfish/batfish/blob/aa92b42fd27132808f1026815a1ee6545e8eb2d1/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java#L162)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> y
>     LOGGER.info("Updating IS-IS topology");
>     IsisTopology newIsisTopology =
>         IsisTopology.initIsisTopology(configurations, currentTopologyContext.getLayer3Topology());
> ```
</details>

FYI: new addition to the iteration loop
___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java, line 172 at r1](https://reviewable.io/reviews/batfish/batfish/6189#-MGywFzs02by3L6ysZ18:-MGywFzs02by3L6ysZ19:b9lxvg0) ([raw file](https://github.com/batfish/batfish/blob/aa92b42fd27132808f1026815a1ee6545e8eb2d1/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java#L172)):*
> ```
> newLayer2Topology
> ```
FYI: initial -> new
___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java, line 180 at r1](https://reviewable.io/reviews/batfish/batfish/6189#-MGywWbLAkU6yhtvikgE:-MGywWbLAkU6yhtvikgF:b-rcrl2v) ([raw file](https://github.com/batfish/batfish/blob/aa92b42fd27132808f1026815a1ee6545e8eb2d1/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java#L180)):*
> ```Java
>         .setVxlanTopology(newVxlanTopology)
>         .setIpsecTopology(newIpsecTopology)
>         .setIsisTopology(newIsisTopology)
> ```

fyi: new
___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlanePlugin.java, line 38 at r1](https://reviewable.io/reviews/batfish/batfish/6189#-MGywd3L2Qg2P-5vppcg:-MGywd3L2Qg2P-5vppch:bbepjww) ([raw file](https://github.com/batfish/batfish/blob/aa92b42fd27132808f1026815a1ee6545e8eb2d1/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlanePlugin.java#L38)):*
> ```Java
>             .setOspfTopology(topologyProvider.getInitialOspfTopology(snapshot))
>             .setRawLayer1PhysicalTopology(topologyProvider.getRawLayer1PhysicalTopology(snapshot))
>             .setTunnelTopology(topologyProvider.getInitialTunnelTopology(snapshot))
> ```

FYI: by setting tunnel topology here, we no longer need to differentiate in `computeDataplane` between `callerTopologyContext` and `initialTopologyContext`. This was the only "potential" topology we were missing.
___
*[tests/basic/genDp.ref, line 12 at r1](https://reviewable.io/reviews/batfish/batfish/6189#-MGyws-49FqP3AfW8ghA:-MGyws-49FqP3AfW8ghB:b-8s0crf) ([raw file](https://github.com/batfish/batfish/blob/6e6497d41aa2e0a92937c911636cc88e3d001f67/tests/basic/genDp.ref#L12)):*
> ```
>         "5" : 76,
>         "6" : 76,
>         "7" : 76
> ```

FYI: as expected, 3rd identical iteration is gone.

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6189)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @progwriter)

**Review by progwriter — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6189)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6189)* status: 1 of 4 files reviewed, all discussions resolved (waiting on @anothermattbrown and @progwriter)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java, line 105 at r1](https://reviewable.io/reviews/batfish/batfish/6189#-MGyx7S-16PmD-w7btza:-MGz9tpi3cl-xgMottl5:b-8t1caw) ([raw file](https://github.com/batfish/batfish/blob/6e6497d41aa2e0a92937c911636cc88e3d001f67/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java#L105)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> initialTopologyContext =
>           callerTopologyContext
>               .toBuilder()
>               .setEigrpTopology(
>                   EigrpTopologyUtils.initEigrpTopology(
>                       configurations, callerTopologyContext.getLayer3Topology()))
>               .setIsisTopology(
>                   IsisTopology.initIsisTopology(
>                       configurations, callerTopologyContext.getLayer3Topology()))
>               .setVxlanTopology(VxlanTopologyUtils.computeVxlanTopology(configurations))
>               .setTunnelTopology(TopologyUtil.computeInitialTunnelTopology(configurations))
>               .build();
> ```
FYI this code is all gone. None of these fields but `tunnel` was read from `initialTopologyContext` -- EIGRP, ISIS, VLAN are computed on-demand not by pruning edges. I moved tunnel to caller and deleted this in favor of the iterative step. (in doing so, I caught the ISIS not being updated)
</blockquote></details>

(ISIS was reverted, it's an IGP)
___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java, line 180 at r1](https://reviewable.io/reviews/batfish/batfish/6189#-MGywWbLAkU6yhtvikgE:-MGz9wo8-fjsfZ1O86qJ:b-f1pbn0) ([raw file](https://github.com/batfish/batfish/blob/aa92b42fd27132808f1026815a1ee6545e8eb2d1/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java#L180)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

fyi: new
</blockquote></details>

ISIS reverted, IGP

**Pull request merged**
