### PR TITLE
more robust parsing for juniper autonomous system setting

### PR DESCRIPTION
**Pull request by arifogel**

### CODE REVIEW

**Comment by dhalperi** [comment]
:lgtm: modulo tests passing.

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4, line 326 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1120#-L9HDRKo838FSseFbK3y:-L9HDRKo838FSseFbK3z:b-8og6ko) ([raw file](https://github.com/batfish/batfish/blob/a51935614070b78bb9a16beaa29e264bef446eb1/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4#L326)):*
> ```ANTLR
> ;
> 
> ASDOT_NOTATION
> ```

You alphabet poorly.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1120#-:-L9HE3xy2Kv8ldHuryTe:b-pzg99l)*

**Comment by arifogel** [comment]
Review status: 10 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4, line 326 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1120#-L9HDRKo838FSseFbK3y:-L9HG6qa43x5QimxF0Q5:bdx7vlb) ([raw file](https://github.com/batfish/batfish/blob/a51935614070b78bb9a16beaa29e264bef446eb1/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4#L326)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

You alphabet poorly.
</blockquote></details>

how so? (I did fix spacing just now, but I don't think that's what you were talking about.)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1120)*

**Comment by dhalperi** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4, line 326 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1120#-L9HDRKo838FSseFbK3y:-L9HO41j7wT0NTACEi-d:b-e506ku) ([raw file](https://github.com/batfish/batfish/blob/a51935614070b78bb9a16beaa29e264bef446eb1/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4#L326)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

how so? (I did fix spacing just now, but I don't think that's what you were talking about.)
</blockquote></details>

`ALLOW` < `ASDOT`.

This may have been pre-existing incorrect alphabets.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1120)*

**Comment by arifogel** [comment]
Review status: 11 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4, line 326 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1120#-L9HDRKo838FSseFbK3y:-L9HP8sXAY9OsPDJXmlH:b-d4ly0g) ([raw file](https://github.com/batfish/batfish/blob/a51935614070b78bb9a16beaa29e264bef446eb1/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4#L326)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

`ALLOW` < `ASDOT`.

This may have been pre-existing incorrect alphabets.
</blockquote></details>

It was, but fixed now.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1120)*

**Comment by dhalperi** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1120)*

**Pull request merged**
