### PR TITLE
Simplify NOD encoding of reachability analysis

### PR DESCRIPTION
**Pull request by anothermattbrown**
Remove Originate and PostIn states, and replace PreOut with PreOutVrf.
This reduces each of: the overall number of NOD relations, the number of joins between relations, and the size and complexity of constraints in the encoded rules.

### CODE REVIEW

**Comment by arifogel** [comment]
:lgtm:

---

Reviewed 12 of 13 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1328#-:-LBwawv_7rkWA1lKxHwI:bnfp4nl)*

**Comment by anothermattbrown** [comment]
blocking comment. found a bug that tests didn't catch.

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1328#-:-LBwirzv2HVQD2lIgS5K:bqsiyfn)*

**Comment by arifogel** [comment]
Blocking comment needs to be created via "Start a new discussion". You cannot put block on main thread.

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1328#-:-LBwr0XrCbpdv4noZydh:b1wzgjb)*

**Comment by dhalperi** [comment]
Review status: 11 of 14 files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1328#-LC-U9E5B9Msbgawz9wI:-LC-U9E6AeH-RIVBER3y:bwm3vgc) (no related file):*
> found a bug that tests didn't catch.

Please add a new test that would have caught it.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1328)*

**Comment by arifogel** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1328)*

**Comment by arifogel** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1328)*

**Comment by anothermattbrown** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1328#-LC-U9E5B9Msbgawz9wI:-LC4sP5gDX7ljMLBZT1v:bob3kys) (no related file):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> found a bug that tests didn't catch.

Please add a new test that would have caught it.
</blockquote></details>

Turns out the bug is independent (#1336) , fixed in [PR #1344](https://reviewable.io/reviews/batfish/batfish/1344).

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1328)*

**Comment by arifogel** [comment]
Reviewed 9 of 9 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[projects/batfish/src/main/java/org/batfish/z3/Synthesizer.java, line 102 at r1](https://reviewable.io/reviews/batfish/batfish/1328#-LC60rsyAHbtobt2OfC1:-LC60rsyAHbtobt2OfC2:b-j0kq2z) ([raw file](https://github.com/batfish/batfish/blob/62a4fc7ed7e4aaa7d3c1b79f4e4dfb5bb202e5cb/projects/batfish/src/main/java/org/batfish/z3/Synthesizer.java#L102)):*
> ```Java
>                     PostOutEdge.State.INSTANCE,
>                     PreInInterface.State.INSTANCE,
>                     PreOutVrf.State.INSTANCE,
> ```

Why remove this? Didn't you just add this?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1328)*

**Comment by anothermattbrown** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[projects/batfish/src/main/java/org/batfish/z3/Synthesizer.java, line 102 at r1](https://reviewable.io/reviews/batfish/batfish/1328#-LC60rsyAHbtobt2OfC1:-LC6BTtl-lUrekpd1_Hs:bu5focb) ([raw file](https://github.com/batfish/batfish/blob/62a4fc7ed7e4aaa7d3c1b79f4e4dfb5bb202e5cb/projects/batfish/src/main/java/org/batfish/z3/Synthesizer.java#L102)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Why remove this? Didn't you just add this?
</blockquote></details>

merge error

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1328)*

**Comment by anothermattbrown** [comment]
Review status: 11 of 15 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/java/org/batfish/z3/Synthesizer.java, line 102 at r1](https://reviewable.io/reviews/batfish/batfish/1328#-LC60rsyAHbtobt2OfC1:-LC6Jol86aaQgLugvqHy:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/62a4fc7ed7e4aaa7d3c1b79f4e4dfb5bb202e5cb/projects/batfish/src/main/java/org/batfish/z3/Synthesizer.java#L102)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

merge error
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1328)*

**Comment by arifogel** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1328#-:-LC6K9le4iuAJd2z-hUj:bnfp4nl)*

**Pull request merged**
