### PR TITLE
Tools: Palo Alto application-definition generation

### PR DESCRIPTION
**Pull request by sfraint**
Add script and instructions to generate Batfish application definitions from Palo Alto application-definition-query XML.

### CODE REVIEW

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8181)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @dhalperi)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/8181#-MysUe4dCIRrk5sbZXza:-MysUe4dCIRrk5sbZXzb:b-ibhl0q) (no related file):*
Should I leave out the current `palo_alto_applications.xml` file so if a user fails to update it, the script also fails?

---

**Review by dhalperi — COMMENTED** [review]
> Reviewed 4 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8181)* status: 4 of 6 files reviewed, 4 unresolved discussions (waiting on @dhalperi and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/8181#-MysUe4dCIRrk5sbZXza:-MysWjwY1vquDd2VbM2f:bj7pclc) (no related file):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

Should I leave out the current `palo_alto_applications.xml` file so if a user fails to update it, the script also fails?
</blockquote></details>

Not only leave it out, but `.gitignore` it so that it can't be checked in.

---
___
*[WORKSPACE, line 45 at r1](https://reviewable.io/reviews/batfish/batfish/8181#-MysWpAz7IKfv3Alw8rL:-MysWpAz7IKfv3Alw8rM:bhfg4cc) ([raw file](https://github.com/batfish/batfish/blob/4921e10b9d551d587c7d95ec09d84e80826b5dcd/WORKSPACE#L45)):*
> ```Starlark
>     name = "rules_python",
>     sha256 = "a30abdfc7126d497a7698c29c46ea9901c6392d6ed315171a6df5ce433aa4502",
>     strip_prefix = "rules_python-0.6.0",
> ```

any reason not to use current version?



_Code quote:_
```Starlark
0.6.0",
```
___
*[tools/README.md, line 5 at r1](https://reviewable.io/reviews/batfish/batfish/8181#-MysWX6w3oN0oGFCbUux:-MysWX6w3oN0oGFCbUuy:undefined) ([raw file](https://github.com/batfish/batfish/blob/4921e10b9d551d587c7d95ec09d84e80826b5dcd/tools/README.md#L5)):*
> ```Markdown
> Palo Alto application definitions can be pulled from a firewall or Panorama device via their web APIs.
> 
> To pull the definitions you'll need an API key. You can issue a GET request via something like `curl` to the keygen API providing a username and password (replace the IP address and `<USERNAME>` and `<PASSWORD>` below):
> ```


___
*[tools/requirements.txt, line 1 at r1](https://reviewable.io/reviews/batfish/batfish/8181#-MysWeQi4zX2heGZz1WT:-MysWeQi4zX2heGZz1WU:b-a4yvdj) ([raw file](https://github.com/batfish/batfish/blob/4921e10b9d551d587c7d95ec09d84e80826b5dcd/tools/requirements.txt#L1)):*
> ```help
> xmltodict==0.12.0
> ```

move this to `/python`, use ` requirements.in` and `requirements.txt`.

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8181)* status: 4 of 6 files reviewed, 4 unresolved discussions (waiting on @dhalperi and @sfraint)

___
*[tools/README.md, line 5 at r1](https://reviewable.io/reviews/batfish/batfish/8181#-MysWX6w3oN0oGFCbUux:-Mysapp3DlBQCe5VI37B:b-78m80l) ([raw file](https://github.com/batfish/batfish/blob/4921e10b9d551d587c7d95ec09d84e80826b5dcd/tools/README.md#L5)):*
> ```Markdown
> Palo Alto application definitions can be pulled from a firewall or Panorama device via their web APIs.
> 
> To pull the definitions you'll need an API key. You can issue a GET request via something like `curl` to the keygen API providing a username and password (replace the IP address and `<USERNAME>` and `<PASSWORD>` below):
> ```

did you mean to add a comment here too?

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8181)* status: 4 of 6 files reviewed, 4 unresolved discussions (waiting on @dhalperi and @sfraint)

___
*[tools/README.md, line 5 at r1](https://reviewable.io/reviews/batfish/batfish/8181#-MysWX6w3oN0oGFCbUux:-Mysc7FJ92WQ3HMGjk53:b-wrfgzx) ([raw file](https://github.com/batfish/batfish/blob/4921e10b9d551d587c7d95ec09d84e80826b5dcd/tools/README.md#L5)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

did you mean to add a comment here too?
</blockquote></details>

does it not show up as a code suggestion?

**Comment by dhalperi** [comment]
___
*[tools/README.md, line 5 at r1](https://reviewable.io/reviews/batfish/batfish/8181#-MyscC_y2Na2D3w2Hr4P:-MyscC_y2Na2D3w2Hr4Q:b-1va3cn) ([raw file](https://github.com/batfish/batfish/blob/4921e10b9d551d587c7d95ec09d84e80826b5dcd/tools/README.md#L5)):*
> ```Markdown
> Palo Alto application definitions can be pulled from a firewall or Panorama device via their web APIs.
> 
> To pull the definitions you'll need an API key. You can issue a GET request via something like `curl` to the keygen API providing a username and password (replace the IP address and `<USERNAME>` and `<PASSWORD>` below):
> ```

suggestion test

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8181)* status: 4 of 6 files reviewed, 5 unresolved discussions (waiting on @dhalperi and @sfraint)

___
*[tools/README.md, line 5 at r1](https://reviewable.io/reviews/batfish/batfish/8181#-MyscK4lD-RqM8msal-G:-MyscK4lD-RqM8msal-H:undefined) ([raw file](https://github.com/batfish/batfish/blob/4921e10b9d551d587c7d95ec09d84e80826b5dcd/tools/README.md#L5)):*
> ```Markdown
> Palo Alto application definitions can be pulled from a firewall or Panorama device via their web APIs.
> 
> To pull the definitions you'll need an API key. You can issue a GET request via something like `curl` to the keygen API providing a username and password (replace the IP address and `<USERNAME>` and `<PASSWORD>` below):
> ```





_Suggestion:_
```Markdown
request to
```

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8181)* status: 4 of 6 files reviewed, 5 unresolved discussions (waiting on @dhalperi and @sfraint)

___
*[tools/README.md, line 5 at r1](https://reviewable.io/reviews/batfish/batfish/8181#-MyscXYTC4qtY_ZH-6pW:-MyscXYTC4qtY_ZH-6pX:undefined) ([raw file](https://github.com/batfish/batfish/blob/4921e10b9d551d587c7d95ec09d84e80826b5dcd/tools/README.md#L5)):*
> ```Markdown
> Palo Alto application definitions can be pulled from a firewall or Panorama device via their web APIs.
> 
> To pull the definitions you'll need an API key. You can issue a GET request via something like `curl` to the keygen API providing a username and password (replace the IP address and `<USERNAME>` and `<PASSWORD>` below):
> ```





_Suggestion:_
```Markdown
request 
```

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8181)* status: 4 of 6 files reviewed, 5 unresolved discussions (waiting on @dhalperi and @sfraint)

___
*[tools/README.md, line 5 at r1](https://reviewable.io/reviews/batfish/batfish/8181#-MyscK4lD-RqM8msal-G:-MyscZHn35B6LJb4mdyU:b2nhysk) ([raw file](https://github.com/batfish/batfish/blob/4921e10b9d551d587c7d95ec09d84e80826b5dcd/tools/README.md#L5)):*
> ```Markdown
> Palo Alto application definitions can be pulled from a firewall or Panorama device via their web APIs.
> 
> To pull the definitions you'll need an API key. You can issue a GET request via something like `curl` to the keygen API providing a username and password (replace the IP address and `<USERNAME>` and `<PASSWORD>` below):
> ```

ack

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8181)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/8181#-MysUe4dCIRrk5sbZXza:-MysUpOI3s89pZIw3O8C:b4c9lyr) (no related file):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Not only leave it out, but `.gitignore` it so that it can't be checked in.
</blockquote></details>

:thumbsup: 

---
___
*[WORKSPACE, line 45 at r1](https://reviewable.io/reviews/batfish/batfish/8181#-MysWpAz7IKfv3Alw8rL:-MyslEXJ7bbGTTvMWmnG:bvnrpcm) ([raw file](https://github.com/batfish/batfish/blob/4921e10b9d551d587c7d95ec09d84e80826b5dcd/WORKSPACE#L45)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

any reason not to use current version?
</blockquote></details>

updated
___
*[tools/requirements.txt, line 1 at r1](https://reviewable.io/reviews/batfish/batfish/8181#-MysWeQi4zX2heGZz1WT:-MysnFZiChiWJRU_Xb62:bvnrpcm) ([raw file](https://github.com/batfish/batfish/blob/4921e10b9d551d587c7d95ec09d84e80826b5dcd/tools/requirements.txt#L1)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

move this to `/python`, use ` requirements.in` and `requirements.txt`.
</blockquote></details>

updated

**Pull request merged**
