### PR TITLE
NXOS: support deleting static routes

### PR DESCRIPTION
**Pull request by sfraint**
Initial support for deleting static routes

### CODE REVIEW

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7339)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7339#-Mj1-mYdAMOpDCeaRXx5:-Mj1-mYdAMOpDCeaRXx6:b-qa7k8d) (no related file):*
left checkpoint changes in here, will open a PR for those separately

---

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7339)* status: 0 of 11 files reviewed, all discussions resolved (waiting on @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7339#-Mj1-mYdAMOpDCeaRXx5:-Mj11F1e9v17rng395lQ:b-c2mts1) (no related file):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

left checkpoint changes in here, will open a PR for those separately
</blockquote></details>

ok, fixed

---

**Review by dhalperi — COMMENTED** [review]
> Reviewed 7 of 11 files at r1, 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7339)* status: 8 of 11 files reviewed, 5 unresolved discussions (waiting on @dhalperi and @sfraint)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_static.g4, line 20 at r1](https://reviewable.io/reviews/batfish/batfish/7339#-Mj10MIf9Dn144HjFM5W:-Mj10MIf9Dn144HjFM5X:b-v9wxcg) ([raw file](https://github.com/batfish/batfish/blob/e5384737ee0a2fc8cd8d2e94e8e0049b50e61c42/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_static.g4#L20)):*
> ```
> irn
> ```

Reusing grammar implies that the positive and negative commands have exactly the same requirements. Based on other vendors, I am a little skeptical, but this seems ok for now.

rename it from `irn` to `static_route_definition` so it's clear this is now data (a'la OSPF Area ID), not syntax.

Then add a comment somewhere that we may need to split this up if the grammar turns out to be different?
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosLexer.g4, line 731 at r1](https://reviewable.io/reviews/batfish/batfish/7339#-Mj124BM7-9IOo9WyG1Q:-Mj124BM7-9IOo9WyG1R:b-dnjfcg) ([raw file](https://github.com/batfish/batfish/blob/e5384737ee0a2fc8cd8d2e94e8e0049b50e61c42/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosLexer.g4#L731)):*
> ```ANTLR
> ;
> 
> EXTCOMMUNITY_LIST: 'extcommunity_list';
> ```

typo for `extcommunity-list`?
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosParser.g4, line 351 at r1](https://reviewable.io/reviews/batfish/batfish/7339#-Mj10xN15pQHLWmnTm_2:-Mj10xN15pQHLWmnTm_3:b-ggt7pp) ([raw file](https://github.com/batfish/batfish/blob/e5384737ee0a2fc8cd8d2e94e8e0049b50e61c42/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosParser.g4#L351)):*
> ```ANTLR
> :
>   (
>     ACCESS_LIST
> ```

remove access-list, as-path, community-list, and other things we should not silently ignore?
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/grammar/CheckPointGatewayConfigurationBuilder.java, line 0 at r2](https://reviewable.io/reviews/batfish/batfish/7339#-Mj11Ldv9ET_OLRJ4572:-Mj11Ldv9ET_OLRJ4573:b-s7rcrd) ([raw file](https://github.com/batfish/batfish/blob/b70d56a3bbb4407f968a4e53c399a8f8cc123ba4/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/grammar/CheckPointGatewayConfigurationBuilder.java#L0)):*
I think you meant to reset the file, not delete it?

I would tend to do `git checkout origin/master -- projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/grammar/CheckPointGatewayConfigurationBuilder.java`, e.g.,

(here and others)
___
*[projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_no_static_route, line 14 at r1](https://reviewable.io/reviews/batfish/batfish/7339#-Mj11X0k06HX_uXSr4Ve:-Mj11X0k06HX_uXSr4Vf:b2f6uvg) ([raw file](https://github.com/batfish/batfish/blob/e5384737ee0a2fc8cd8d2e94e8e0049b50e61c42/projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_no_static_route#L14)):*
> ```
> ! Different vrf than original route
> no ip route 10.0.1.0/24 Ethernet1/1 10.0.1.1 vrf management
> no ip route 10.0.1.0/24 Ethernet1/1 10.0.1.2
> ```

add the other commands you tried as documentation comments?

```
! Cannot no just a prefix
!no ip route 10.0.1.0/24
! Will be ignored, since nhip does not match
no ip route 10.0.1.0/24 Ethernet1/1
```

etc.

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7339)* status: 2 of 11 files reviewed, 5 unresolved discussions (waiting on @dhalperi)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_static.g4, line 20 at r1](https://reviewable.io/reviews/batfish/batfish/7339#-Mj10MIf9Dn144HjFM5W:-Mj14nDo1RUF7uOIR5PC:bvnrpcm) ([raw file](https://github.com/batfish/batfish/blob/e5384737ee0a2fc8cd8d2e94e8e0049b50e61c42/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_static.g4#L20)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> irn
> ```

Reusing grammar implies that the positive and negative commands have exactly the same requirements. Based on other vendors, I am a little skeptical, but this seems ok for now.

rename it from `irn` to `static_route_definition` so it's clear this is now data (a'la OSPF Area ID), not syntax.

Then add a comment somewhere that we may need to split this up if the grammar turns out to be different?
</blockquote></details>

updated
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosLexer.g4, line 731 at r1](https://reviewable.io/reviews/batfish/batfish/7339#-Mj124BM7-9IOo9WyG1Q:-Mj14rfZADwHKVz_KfRy:bso8x5t) ([raw file](https://github.com/batfish/batfish/blob/e5384737ee0a2fc8cd8d2e94e8e0049b50e61c42/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosLexer.g4#L731)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

typo for `extcommunity-list`?
</blockquote></details>

yep, fixed
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosParser.g4, line 351 at r1](https://reviewable.io/reviews/batfish/batfish/7339#-Mj10xN15pQHLWmnTm_2:-Mj1VPtF1NJJaNW9RUjB:b-hfpv0l) ([raw file](https://github.com/batfish/batfish/blob/e5384737ee0a2fc8cd8d2e94e8e0049b50e61c42/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosParser.g4#L351)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

remove access-list, as-path, community-list, and other things we should not silently ignore?
</blockquote></details>

removed
___
*[projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_no_static_route, line 14 at r1](https://reviewable.io/reviews/batfish/batfish/7339#-Mj11X0k06HX_uXSr4Ve:-Mj1Woa53HZ2bLyPrzES:bvnrpcm) ([raw file](https://github.com/batfish/batfish/blob/e5384737ee0a2fc8cd8d2e94e8e0049b50e61c42/projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_no_static_route#L14)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

add the other commands you tried as documentation comments?

```
! Cannot no just a prefix
!no ip route 10.0.1.0/24
! Will be ignored, since nhip does not match
no ip route 10.0.1.0/24 Ethernet1/1
```

etc.
</blockquote></details>

updated
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/grammar/CheckPointGatewayConfigurationBuilder.java, line  at r2](https://reviewable.io/reviews/batfish/batfish/7339#-Mj11Ldv9ET_OLRJ4572:-Mj14SDt5MrA-bqdLJ9S:b-c5qdjv) ([raw file](https://github.com/batfish/batfish/blob/b70d56a3bbb4407f968a4e53c399a8f8cc123ba4/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/grammar/CheckPointGatewayConfigurationBuilder.java#L)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I think you meant to reset the file, not delete it?

I would tend to do `git checkout origin/master -- projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/grammar/CheckPointGatewayConfigurationBuilder.java`, e.g.,

(here and others)
</blockquote></details>


yep...fixed

**Review by dhalperi — COMMENTED** [review]
> Reviewed 8 of 9 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7339)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7339)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

**Pull request merged**
