### PR TITLE
Cache compressed configs

### PR DESCRIPTION
**Pull request by anothermattbrown**
Until we can debug/optimize compression on large networks, start
caching the compressed configs in addition to the compressed dataplane,
and switch reachability to use general compression, rather than
compressing per-query (which yields better NoD performance).

### CODE REVIEW

**Comment by dhalperi** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 4128 at r1](https://reviewable.io:443/reviews/batfish/batfish/1053#-L7_rBiEU5Gh2r9POH6d:-L7_rBiEU5Gh2r9POH6e:b-uhyk20) ([raw file](https://github.com/batfish/batfish/blob/91dda81ad31d98b55b5b9176ca36ba05039cc638/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L4128)):*
> ```Java
>     Snapshot snapshot = getSnapshot();
>     Map<String, Configuration> configurations =
>         useCompression ? loadCompressedConfigurations(snapshot) : loadConfigurations();
> ```

why not pass snapshot in both places?

---

*[projects/batfish/src/main/java/org/batfish/main/BatfishStorage.java, line 52 at r1](https://reviewable.io:443/reviews/batfish/batfish/1053#-L7_qqHdCgcIxzHY-z2d:-L7_qqHdCgcIxzHY-z2e:b38fjxk) ([raw file](https://github.com/batfish/batfish/blob/91dda81ad31d98b55b5b9176ca36ba05039cc638/projects/batfish/src/main/java/org/batfish/main/BatfishStorage.java#L52)):*
> ```Java
>    */
>   @Nullable
>   public SortedMap<String, Configuration> loadConfigurations(String testrig, boolean compressed) {
> ```

Add separate entry point rather than required boolean. Refactor to minimize common code.

---

*[projects/batfish/src/main/java/org/batfish/main/BatfishStorage.java, line 97 at r1](https://reviewable.io:443/reviews/batfish/batfish/1053#-L7_qvxu9ln-p890riie:-L7_qvxu9ln-p890riif:b-z8ae4n) ([raw file](https://github.com/batfish/batfish/blob/91dda81ad31d98b55b5b9176ca36ba05039cc638/projects/batfish/src/main/java/org/batfish/main/BatfishStorage.java#L97)):*
> ```Java
>   }
> 
>   public void storeCompressedConfigurations(
> ```

Javadoc on all new public functions.

---

*[projects/batfish/src/main/java/org/batfish/main/BatfishStorage.java, line 106 at r1](https://reviewable.io:443/reviews/batfish/batfish/1053#-L7_qhbUh0ceAPuEzRDh:-L7_qhbUh0ceAPuEzRDi:bpmykoi) ([raw file](https://github.com/batfish/batfish/blob/91dda81ad31d98b55b5b9176ca36ba05039cc638/projects/batfish/src/main/java/org/batfish/main/BatfishStorage.java#L106)):*
> ```Java
>     AtomicInteger progressCount = _newBatch.apply(batchName, configurations.size());
> 
>     Path testrigDir = getTestrigDir(testrig);
> ```

Refactor to remove commonality with storeConfigurations.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/1053)*

**Comment by anothermattbrown** [comment]
Review status: 3 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 4128 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1053#-L7_rBiEU5Gh2r9POH6d:-L7_w5cq6nQJRTH4wqCP:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/91dda81ad31d98b55b5b9176ca36ba05039cc638/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L4128)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

why not pass snapshot in both places?
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/main/BatfishStorage.java, line 52 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1053#-L7_qqHdCgcIxzHY-z2d:-L7_w4tAAiLoQNFja0sc:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/91dda81ad31d98b55b5b9176ca36ba05039cc638/projects/batfish/src/main/java/org/batfish/main/BatfishStorage.java#L52)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Add separate entry point rather than required boolean. Refactor to minimize common code.
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/main/BatfishStorage.java, line 97 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1053#-L7_qvxu9ln-p890riie:-L7_w6joCblakVV74kRO:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/91dda81ad31d98b55b5b9176ca36ba05039cc638/projects/batfish/src/main/java/org/batfish/main/BatfishStorage.java#L97)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Javadoc on all new public functions.
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/main/BatfishStorage.java, line 106 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1053#-L7_qhbUh0ceAPuEzRDh:-L7_w7AuBvRghg9rFWWF:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/91dda81ad31d98b55b5b9176ca36ba05039cc638/projects/batfish/src/main/java/org/batfish/main/BatfishStorage.java#L106)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Refactor to remove commonality with storeConfigurations.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1053)*

**Comment by dhalperi** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish/src/main/java/org/batfish/main/BatfishStorage.java, line 69 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1053#-L7_z9sdDvL4ZFL_SRKI:-L7_z9sdDvL4ZFL_SRKJ:bh0mc69) ([raw file](https://github.com/batfish/batfish/blob/6f814e1a031640258e88edd8abe4e4d7129c3226/projects/batfish/src/main/java/org/batfish/main/BatfishStorage.java#L69)):*
> ```Java
>   }
> 
>   public SortedMap<String, Configuration> loadConfigurations(String testrig, Path indepDir) {
> ```

private?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1053#-:-L7_zINR-12xGQMPELL3:bnfp4nl)*

**Comment by dhalperi** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/1053)*

**Comment by anothermattbrown** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[projects/batfish/src/main/java/org/batfish/main/BatfishStorage.java, line 69 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1053#-L7_z9sdDvL4ZFL_SRKI:-L7a0o4iEZR6SvUHoYL3:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/6f814e1a031640258e88edd8abe4e4d7129c3226/projects/batfish/src/main/java/org/batfish/main/BatfishStorage.java#L69)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

private?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1053)*

**Pull request merged**
