### PR TITLE
partial data model support for ios zones, inspection

### PR DESCRIPTION
**Pull request by arifogel**

### CODE REVIEW

**Comment by dhalperi** [comment]
Reviewed 26 of 31 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1232)*

**Comment by sfraint** [comment]
Reviewed 7 of 8 files at r3.
Review status: 30 of 31 files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java, line 576 at r3](https://reviewable.io/reviews/batfish/batfish/1232#-LBMiQ_-DVinBwIdnbdj:-LBMiQ_-DVinBwIdnbdk:b-5aq0a6) ([raw file](https://github.com/batfish/batfish/blob/4f56738c0bafd601779784162c312bdd8a10c53a/projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java#L576)):*
> ```Java
>      */
>     assertThat(c, hasZone("z1", hasMemberInterfaces(not(empty()))));
>     assertThat(c, hasZone("z1", hasMemberInterfaces(not(empty()))));
> ```

Should this be checking `z2` instead?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1232)*

**Comment by arifogel** [comment]
Review status: 30 of 31 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java, line 576 at r3](https://reviewable.io/reviews/batfish/batfish/1232#-LBMiQ_-DVinBwIdnbdj:-LBMl1p14qJMA707KbAk:bt2vr1b) ([raw file](https://github.com/batfish/batfish/blob/4f56738c0bafd601779784162c312bdd8a10c53a/projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java#L576)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

Should this be checking `z2` instead?
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1232)*

**Comment by arifogel** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 2857 at r4](https://reviewable.io/reviews/batfish/batfish/1232#-LBMsh-L2u6ARgCrQ_Ik:-LBMuMwH7Yv_BqxgswBk:b5trqj0) ([raw file](https://github.com/batfish/batfish/blob/1aa21c2cf3062baa1421c7a5722bd6ffde728232/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L2857)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

changes these to `ctx.ICMP`, `ctx.TCP`, ...
</blockquote></details>

I actually caught this and included in my later PR. If you like I can backport it here. However by the end of the day, if the other PR is good, the fix will be in regardless.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1232)*

**Comment by sfraint** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 2857 at r4](https://reviewable.io/reviews/batfish/batfish/1232#-LBMsh-L2u6ARgCrQ_Ik:-LBMuozl1VDisDL1FY6S:b-ra74ya) ([raw file](https://github.com/batfish/batfish/blob/1aa21c2cf3062baa1421c7a5722bd6ffde728232/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L2857)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

I actually caught this and included in my later PR. If you like I can backport it here. However by the end of the day, if the other PR is good, the fix will be in regardless.
</blockquote></details>

Fine by me.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1232)*

**Pull request merged**
