### PR TITLE
Add UdpPort

### PR DESCRIPTION
**Pull request by dhalperi**
It contains all the ports used in NamedApplication, plus a few more
cherry-picked. Starter.

commit-id:10dc710a

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8226)* status: 0 of 1 files reviewed, 1 unresolved discussion

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/UdpPort.java, line 17 at r1](https://reviewable.io/reviews/batfish/batfish/8226#-N-02BuE8D6k7JdaBOKv:-N-02BuE8D6k7JdaBOKw:bigep41) ([raw file](https://github.com/batfish/batfish/blob/3534c340f77bbd7dc4039dfeaa3641f6768d11bb/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/UdpPort.java#L17)):*
> ```Java
>   AOL(5190),
>   /** A Remote Network Server System. */
>   ARNS(384),
> ```

here's a comment

**Review by sfraint — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8226)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown and @arifogel)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/UdpPort.java, line 19 at r2](https://reviewable.io/reviews/batfish/batfish/8226#-N-478Gn6D-RW4gHaW3d:-N-478Gn6D-RW4gHaW3e:btx83h0) ([raw file](https://github.com/batfish/batfish/blob/2c36f5df6f3a577f2560ae77c954b537a30aff80/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/UdpPort.java#L19)):*
> ```Java
>    * ports must be unique.
>    *
>    * <p>Names are autogenerated by replacing _ with - in the name, e.g., "".
> ```

missing example?



_Code quote:_
```Java
e.g., ""
```

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8226)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @anothermattbrown, @arifogel, and @sfraint)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/UdpPort.java, line 19 at r2](https://reviewable.io/reviews/batfish/batfish/8226#-N-478Gn6D-RW4gHaW3d:-N-4QAF06kHtiQomEocL:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/2c36f5df6f3a577f2560ae77c954b537a30aff80/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/UdpPort.java#L19)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

missing example?
</blockquote></details>

Done.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8226)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown and @arifogel)

**Pull request merged**
