### PR TITLE
Fix 'forwarding-options dhcp-security' parse warning for Juniper

### PR DESCRIPTION
**Pull request by saidvandeklundert**
A 'Parse warning' is being triggered by the following configuration:
```
set vlans <name> forwarding-options dhcp-security
```
The `dhcp-security` configuration is valid only under the ‘forwarding-options’ inside the vlans stanza.

This PR addresses the parse warning by extending the lexer/parser.

The configuration statement is documented [here](https://www.juniper.net/documentation/us/en/software/junos/security-services/topics/ref/statement/dhcp-security-edit-vlans.html)

### CODE REVIEW

**Comment by dhalperi** [comment]
Because I'm lazy, I'll just point you at the review I left you on the prior PR https://reviewable.io/reviews/batfish/batfish/8827 :)

**Comment by saidvandeklundert** [comment]
Updated the description of the PR.

Removed lexer/parser rules for the grammar outside the vlans hierarchy since the Juniper syntax is not valid anywhere else.

Also worked on the other comments by reworking the parser rules and the naming of the rules.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8828)* status: all files reviewed, 4 unresolved discussions (waiting on @saidvandeklundert)

___
*[`projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperParser.g4` line 183 at r3](https://reviewable.io/reviews/batfish/batfish/8828#-Nfuj9l71DLU20rqmwwY:-Nfuj9l71DLU20rqmwwZ:b-e6nlrp) ([raw file](https://github.com/batfish/batfish/blob/9d46f5a17ad83868a43ca87ec02649e71e890abb/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperParser.g4#L183)):*
> ```ANTLR
> ;
> 
> vlt_forwarding_options
> ```

can you move this code block to be located after `vlt_filter` in the file?
___
*[`projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperParser.g4` line 192 at r3](https://reviewable.io/reviews/batfish/batfish/8828#-Nfuj10a89TCEMWM1um2:-Nfuj10a89TCEMWM1um3:b-x0q0ea) ([raw file](https://github.com/batfish/batfish/blob/9d46f5a17ad83868a43ca87ec02649e71e890abb/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperParser.g4#L192)):*
> ```ANTLR
> ;
> 
> vlt_fo_null
> ```

`vltfo` -- the prefix is "underscore-less" so that it's clear where the token being recognized begins.
___
*[`projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperParser.g4` line 206 at r3](https://reviewable.io/reviews/batfish/batfish/8828#-NfujErrDavMO2pBcFa1:-NfujErrDavMO2pBcFa2:b-5l4dbv) ([raw file](https://github.com/batfish/batfish/blob/9d46f5a17ad83868a43ca87ec02649e71e890abb/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperParser.g4#L206)):*
> ```ANTLR
>     | vlt_description
>     | vlt_filter
>     | vlt_forwarding_options    
> ```

nit: extra whitespace here.

**Comment by dhalperi** [comment]
*[`projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperParser.g4` line 206 at r3](https://reviewable.io/reviews/batfish/batfish/8828#-NfujErrDavMO2pBcFa1:-Nfujal72dP_tF-3iJeB:b-lulwnl) ([raw file](https://github.com/batfish/batfish/blob/9d46f5a17ad83868a43ca87ec02649e71e890abb/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperParser.g4#L206)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

nit: extra whitespace here.
</blockquote></details>

(four trailing spaces)

**Comment by saidvandeklundert** [comment]
Code block moved, `vltfo_` renamed according to the standard, trailing spaces removed and ran code formatter.

**Pull request merged**
