### PR TITLE
Cisco NX-OS BGP leak configs

### PR DESCRIPTION
**Pull request by arifogel**
- evpn -> bgpv4
- bgpv4 -> evpn
- add e2e tests of NX-OS L3 VNI connectivity

### CODE REVIEW

**Review by corinaminer — COMMENTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7809)* status: all files reviewed, 4 unresolved discussions (waiting on @arifogel)

___
*[projects/batfish/src/test/java/org/batfish/dataplane/EvpnNxosTest.java, line 54 at r1](https://reviewable.io/reviews/batfish/batfish/7809#-Mr-Id9E2X470Qr9NPYU:-Mr-Id9F1dQKREwxlf38:b-vh781) ([raw file](https://github.com/batfish/batfish/blob/9604cf47f3375448b3be9ce02fabc8a79c301f13/projects/batfish/src/test/java/org/batfish/dataplane/EvpnNxosTest.java#L54)):*
> ```Java
> 
>   @Before
>   public void setup() throws IOException {
> ```

please add a brief description of the network -- what's connected, what important routes exist, what leaking is present
___
*[projects/batfish/src/test/java/org/batfish/dataplane/EvpnNxosTest.java, line 54 at r1](https://reviewable.io/reviews/batfish/batfish/7809#-Mr-JMCP5RVdZBb3kPUa:-Mr-JMCP5RVdZBb3kPUb:bey3q9x) ([raw file](https://github.com/batfish/batfish/blob/9604cf47f3375448b3be9ce02fabc8a79c301f13/projects/batfish/src/test/java/org/batfish/dataplane/EvpnNxosTest.java#L54)):*
> ```Java
> 
>   @Before
>   public void setup() throws IOException {
> ```

This could happen once `BeforeClass` instead of before each test
___
*[projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java, line 1682 at r1](https://reviewable.io/reviews/batfish/batfish/7809#-Mr-GA-q7RR9QfVb_J2Y:-Mr-GA-s6DYtqXhiYK_0:b-qrmmxr) ([raw file](https://github.com/batfish/batfish/blob/9604cf47f3375448b3be9ce02fabc8a79c301f13/projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java#L1682)):*
> ```Java
>               .build();
>       RoutingPolicy importPolicy = c.getRoutingPolicies().get(importPolicyName);
>       assertRoutingPolicyPermitsRoute(importPolicy, r);
> ```

for thoroughness this really ought to check a route without the route target too
___
*[projects/batfish/src/test/resources/org/batfish/dataplane/testrigs/evpn-l3-vnis/configs/r1, line 11 at r1](https://reviewable.io/reviews/batfish/batfish/7809#-Mr-KINy-sb0Ti4r-mLw:-Mr-KINy-sb0Ti4r-mLx:b-7gufae) ([raw file](https://github.com/batfish/batfish/blob/9604cf47f3375448b3be9ce02fabc8a79c301f13/projects/batfish/src/test/resources/org/batfish/dataplane/testrigs/evpn-l3-vnis/configs/r1#L11)):*
> ```
> feature nv overlay
> 
> ip route 10.0.4.2/32 10.0.3.2
> ```

why are these static routes necessary?

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7809)* status: 8 of 10 files reviewed, 2 unresolved discussions (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/test/java/org/batfish/dataplane/EvpnNxosTest.java, line 54 at r1](https://reviewable.io/reviews/batfish/batfish/7809#-Mr-JMCP5RVdZBb3kPUa:-Mr-LDLgDFbLI3dkClfH:b-2szbpp) ([raw file](https://github.com/batfish/batfish/blob/9604cf47f3375448b3be9ce02fabc8a79c301f13/projects/batfish/src/test/java/org/batfish/dataplane/EvpnNxosTest.java#L54)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

This could happen once `BeforeClass` instead of before each test
</blockquote></details>

Don't I need to use static fields then? I just wanted to avoid accidentally leaving things around.
FWIW Performance difference isn't noticeable.
___
*[projects/batfish/src/test/java/org/batfish/dataplane/EvpnNxosTest.java, line 54 at r1](https://reviewable.io/reviews/batfish/batfish/7809#-Mr-Id9E2X470Qr9NPYU:-Mr-OVMB-8GIBSBhmtXM:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/9604cf47f3375448b3be9ce02fabc8a79c301f13/projects/batfish/src/test/java/org/batfish/dataplane/EvpnNxosTest.java#L54)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

please add a brief description of the network -- what's connected, what important routes exist, what leaking is present
</blockquote></details>

done
___
*[projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java, line 1682 at r1](https://reviewable.io/reviews/batfish/batfish/7809#-Mr-GA-q7RR9QfVb_J2Y:-Mr-P0Pf25qv14fk8VzS:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/9604cf47f3375448b3be9ce02fabc8a79c301f13/projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java#L1682)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

for thoroughness this really ought to check a route without the route target too
</blockquote></details>

done

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7809)* status: 8 of 10 files reviewed, 2 unresolved discussions (waiting on @corinaminer)

___
*[projects/batfish/src/test/resources/org/batfish/dataplane/testrigs/evpn-l3-vnis/configs/r1, line 11 at r1](https://reviewable.io/reviews/batfish/batfish/7809#-Mr-KINy-sb0Ti4r-mLw:-Mr-PXAUD1HAOyGQStDB:b-rpbjhs) ([raw file](https://github.com/batfish/batfish/blob/9604cf47f3375448b3be9ce02fabc8a79c301f13/projects/batfish/src/test/resources/org/batfish/dataplane/testrigs/evpn-l3-vnis/configs/r1#L11)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

why are these static routes necessary?
</blockquote></details>

To reach the vtep ips in the default vrf

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7809)* status: 6 of 10 files reviewed, 2 unresolved discussions (waiting on @corinaminer)

___
*[projects/batfish/src/test/resources/org/batfish/dataplane/testrigs/evpn-l3-vnis/configs/r1, line 11 at r1](https://reviewable.io/reviews/batfish/batfish/7809#-Mr-KINy-sb0Ti4r-mLw:-Mr-PtwmB5BMB13dOuTI:b4i3v23) ([raw file](https://github.com/batfish/batfish/blob/9604cf47f3375448b3be9ce02fabc8a79c301f13/projects/batfish/src/test/resources/org/batfish/dataplane/testrigs/evpn-l3-vnis/configs/r1#L11)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

To reach the vtep ips in the default vrf
</blockquote></details>

(see added topo comment in test class)

**Review by corinaminer — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7809)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel)

___
*[projects/batfish/src/test/resources/org/batfish/dataplane/testrigs/evpn-l3-vnis/configs/r1, line 11 at r1](https://reviewable.io/reviews/batfish/batfish/7809#-Mr-KINy-sb0Ti4r-mLw:-Mr-S5CwAIBaIo-GgPBC:b-fgxo86) ([raw file](https://github.com/batfish/batfish/blob/9604cf47f3375448b3be9ce02fabc8a79c301f13/projects/batfish/src/test/resources/org/batfish/dataplane/testrigs/evpn-l3-vnis/configs/r1#L11)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

(see added topo comment in test class)
</blockquote></details>

still a little confused because VTEP next hops automatically forward out the NVE interface, so when will this route be used? Is it needed in order for the VXLAN tunnel to come up in the first place?

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7809)* status: all files reviewed, 1 unresolved discussion (waiting on @corinaminer)

___
*[projects/batfish/src/test/resources/org/batfish/dataplane/testrigs/evpn-l3-vnis/configs/r1, line 11 at r1](https://reviewable.io/reviews/batfish/batfish/7809#-Mr-KINy-sb0Ti4r-mLw:-Mr-VtTA6XpTWP2rx-wF:b-s9qlqb) ([raw file](https://github.com/batfish/batfish/blob/9604cf47f3375448b3be9ce02fabc8a79c301f13/projects/batfish/src/test/resources/org/batfish/dataplane/testrigs/evpn-l3-vnis/configs/r1#L11)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

still a little confused because VTEP next hops automatically forward out the NVE interface, so when will this route be used? Is it needed in order for the VXLAN tunnel to come up in the first place?
</blockquote></details>

It's there because it's needed in reality. If we ever implement forwarding of encapsulated packets, this means we won't have to change these configs.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7809)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

___
*[projects/batfish/src/test/resources/org/batfish/dataplane/testrigs/evpn-l3-vnis/configs/r1, line 11 at r1](https://reviewable.io/reviews/batfish/batfish/7809#-Mr-KINy-sb0Ti4r-mLw:-Mr-W7F1BDbHfhpj9SuS:bhs47hf) ([raw file](https://github.com/batfish/batfish/blob/9604cf47f3375448b3be9ce02fabc8a79c301f13/projects/batfish/src/test/resources/org/batfish/dataplane/testrigs/evpn-l3-vnis/configs/r1#L11)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

It's there because it's needed in reality. If we ever implement forwarding of encapsulated packets, this means we won't have to change these configs.
</blockquote></details>

Actually it's needed even now. We do a reachability check on VTEP IPs before bringing up vxlantopology edges.

**Pull request merged**
