### PR TITLE
Docs: Update parser documentation

### PR DESCRIPTION
**Pull request by SLarkworthy**
Adds _null and a pattern to avoid.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8621)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @SLarkworthy)

___
*[`docs/example_code/new_vendor/src/test/resources/org/batfish/grammar/cool_nos/testconfigs/cool.nos.host-name` line 3 at r1](https://reviewable.io/reviews/batfish/batfish/8621#-NJ82rFR5_vmZCsGMgpR:-NJ82rFR5_vmZCsGMgpS:b-nr4r7q) ([raw file](https://github.com/batfish/batfish/blob/bbb70c08ee8a8825d8a573f5b268ba1d1368df90/docs/example_code/new_vendor/src/test/resources/org/batfish/grammar/cool_nos/testconfigs/cool.nos.host-name#L3)):*
> ```
> ! THIS IS A COOL NOS FILE
> 
> log syslog
> ```

This looks like a test of `host-name` (based on filename and contents). Don't add log here, add a new test.



_Code quote:_
```
log syslog
```
___
*[`docs/parsing/README.md` line 632 at r1](https://reviewable.io/reviews/batfish/batfish/8621#-NJ83uEo4P27vSJWLX7f:-NJ83uEo4P27vSJWLX7g:b9mfsu0) ([raw file](https://github.com/batfish/batfish/blob/bbb70c08ee8a8825d8a573f5b268ba1d1368df90/docs/parsing/README.md#L632)):*
> ```Markdown
> This pattern would not be LL(1), so is to be avoided.
> 
> Also note that `ssy_host_name` and `ssy_login_banner` both end in NEWLINE. 
> ```

Can you introduce a new section of some kind here with a heading that explains that you're introducing a new rule? Otherwise, this stuff is hard to find (and hard to link to in review!)
___
*[`docs/parsing/README.md` line 652 at r1](https://reviewable.io/reviews/batfish/batfish/8621#-NJ82gVS1deDcaK-0QBC:-NJ82gVS1deDcaK-0QBD:br8mhop) ([raw file](https://github.com/batfish/batfish/blob/bbb70c08ee8a8825d8a573f5b268ba1d1368df90/docs/parsing/README.md#L652)):*
> ```Markdown
> This is less efficient for recovery.
> 
> If a rule is added with no current plans for further implementation (use in extraction or conversion), the rule should end in "_null".
> ```

Can you split this into 2 PRs, one for each? Would make review a lot easier.

I'll review just the top part here.
___
*[`docs/parsing/README.md` line 652 at r1](https://reviewable.io/reviews/batfish/batfish/8621#-NJ841PiDszLTKwDqkvo:-NJ841PiDszLTKwDqkvp:b45h) ([raw file](https://github.com/batfish/batfish/blob/bbb70c08ee8a8825d8a573f5b268ba1d1368df90/docs/parsing/README.md#L652)):*
> ```Markdown
> This is less efficient for recovery.
> 
> If a rule is added with no current plans for further implementation (use in extraction or conversion), the rule should end in "_null".
> ```





_Suggestion:_
```Markdown
`_null`
```

**Review by SLarkworthy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8621)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @dhalperi and @SLarkworthy)

___
*[`docs/parsing/README.md` line 632 at r1](https://reviewable.io/reviews/batfish/batfish/8621#-NJ83uEo4P27vSJWLX7f:-NJCNzTH70TDU3JjztZa:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/bbb70c08ee8a8825d8a573f5b268ba1d1368df90/docs/parsing/README.md#L632)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Can you introduce a new section of some kind here with a heading that explains that you're introducing a new rule? Otherwise, this stuff is hard to find (and hard to link to in review!)
</blockquote></details>

done
___
*[`docs/parsing/README.md` line 652 at r1](https://reviewable.io/reviews/batfish/batfish/8621#-NJ82gVS1deDcaK-0QBC:-NJCO-D8EhBSGJxueUoP:bouu6su) ([raw file](https://github.com/batfish/batfish/blob/bbb70c08ee8a8825d8a573f5b268ba1d1368df90/docs/parsing/README.md#L652)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Can you split this into 2 PRs, one for each? Would make review a lot easier.

I'll review just the top part here.
</blockquote></details>

Sure - this PR is now just for the NEWLINE part
___
*[`docs/parsing/README.md` line 652 at r1](https://reviewable.io/reviews/batfish/batfish/8621#-NJ841PiDszLTKwDqkvo:-NJCO1xJ1LxAJ3yaTXhA:b8stc53) ([raw file](https://github.com/batfish/batfish/blob/bbb70c08ee8a8825d8a573f5b268ba1d1368df90/docs/parsing/README.md#L652)):*
> ```Markdown
> This is less efficient for recovery.
> 
> If a rule is added with no current plans for further implementation (use in extraction or conversion), the rule should end in "_null".
> ```

will do in followup PR with _null rule
___
*[`docs/example_code/new_vendor/src/test/resources/org/batfish/grammar/cool_nos/testconfigs/cool.nos.host-name` line 3 at r1](https://reviewable.io/reviews/batfish/batfish/8621#-NJ82rFR5_vmZCsGMgpR:-NJCO5O25FvsEEmiN3x5:b-nc4j14) ([raw file](https://github.com/batfish/batfish/blob/bbb70c08ee8a8825d8a573f5b268ba1d1368df90/docs/example_code/new_vendor/src/test/resources/org/batfish/grammar/cool_nos/testconfigs/cool.nos.host-name#L3)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

This looks like a test of `host-name` (based on filename and contents). Don't add log here, add a new test.
</blockquote></details>

will do in follow-up

**Review by dhalperi — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8621)* status: all files reviewed, 3 unresolved discussions (waiting on @SLarkworthy)

___
*[`docs/parsing/README.md` line 634 at r2](https://reviewable.io/reviews/batfish/batfish/8621#-NJCOvyM4k6CmMgS3qLV:-NJCOvyM4k6CmMgS3qLW:bd08dmy) ([raw file](https://github.com/batfish/batfish/blob/d272d359d94fd1b6ae6d65730ae70b475b3b655b/docs/parsing/README.md#L634)):*
> ```Markdown
> #### Parser rule NEWLINE
> 
> Also note that `ssy_host_name` and `ssy_login_banner` both end in NEWLINE. 
> ```

`NEWLINE` and other lexer tokens or parser rules in code font (throughout).



_Code quote:_
```Markdown
NEWLINE
```

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8621)* status: all files reviewed, 4 unresolved discussions (waiting on @SLarkworthy)

___
*[`docs/parsing/README.md` line 652 at r2](https://reviewable.io/reviews/batfish/batfish/8621#-NJs1qAV3VwIPWAmlIzJ:-NJs1qAV3VwIPWAmlIzK:b4a2i4t) ([raw file](https://github.com/batfish/batfish/blob/d272d359d94fd1b6ae6d65730ae70b475b3b655b/docs/parsing/README.md#L652)):*
> ```Markdown
> ...
> ```
> This is less efficient for recovery.
> ```

Including the `NEWLINE` in the parent rule makes the parser more fragile and breaks recovery in the event that a child rule is only partially recognized.

It's not about efficiency.



_Code quote:_
```Markdown
This is less efficient for recovery.
```

**Review by SLarkworthy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8621)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @dhalperi)

___
*[`docs/parsing/README.md` line 634 at r2](https://reviewable.io/reviews/batfish/batfish/8621#-NJCOvyM4k6CmMgS3qLV:-NKOWYPDBhXEI28komck:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/d272d359d94fd1b6ae6d65730ae70b475b3b655b/docs/parsing/README.md#L634)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

`NEWLINE` and other lexer tokens or parser rules in code font (throughout).
</blockquote></details>

done
___
*[`docs/parsing/README.md` line 652 at r2](https://reviewable.io/reviews/batfish/batfish/8621#-NJs1qAV3VwIPWAmlIzJ:-NKOWZbO4TShLtmo_s5w:bvnrpcm) ([raw file](https://github.com/batfish/batfish/blob/d272d359d94fd1b6ae6d65730ae70b475b3b655b/docs/parsing/README.md#L652)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Including the `NEWLINE` in the parent rule makes the parser more fragile and breaks recovery in the event that a child rule is only partially recognized.

It's not about efficiency.
</blockquote></details>

updated

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8621)* status: all files reviewed, 3 unresolved discussions (waiting on @SLarkworthy)

___
*[`docs/parsing/README.md` line 653 at r3](https://reviewable.io/reviews/batfish/batfish/8621#-NKOZmuf0rLdTPJ4OGN1:-NKOZmuf0rLdTPJ4OGN2:b-x79nou) ([raw file](https://github.com/batfish/batfish/blob/167106949da4e27e56f04b4dd1c0b093f6d4d562/docs/parsing/README.md#L653)):*
> ```Markdown
> ```
> This makes the parser more fragile and can break recovery in the event that a child rule is only partially recognized. This means an unrecognized line early in a stanza can take out all the
> rest of the lines.
> ```

Not sure this is right. When recovery breaks, what often happens is that the current block is exited.

For example:

```
interface eth1
  ip address 1.2.3.4/24
  ip address 2.3.4.5/25 unrecognizedmodifier
  ip address 3.4.5.6/26
interface eth2
  ip address 4.5.6.7/24
```

What would happen if recovery works, is that the first and third addresses are applied.

What would happen if recovery breaks is that the parser tries to parse the third line at the top level statement instead of inside `eth1`.

In either case, `eth2` should have its address.

Does that make sense?



_Code quote:_
```Markdown
rest of the lines.
```

**Review by SLarkworthy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8621)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @dhalperi)

___
*[`docs/parsing/README.md` line 653 at r3](https://reviewable.io/reviews/batfish/batfish/8621#-NKOZmuf0rLdTPJ4OGN1:-NKPOiV0CU0ckYsaZFv6:b-r04yjv) ([raw file](https://github.com/batfish/batfish/blob/167106949da4e27e56f04b4dd1c0b093f6d4d562/docs/parsing/README.md#L653)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Not sure this is right. When recovery breaks, what often happens is that the current block is exited.

For example:

```
interface eth1
  ip address 1.2.3.4/24
  ip address 2.3.4.5/25 unrecognizedmodifier
  ip address 3.4.5.6/26
interface eth2
  ip address 4.5.6.7/24
```

What would happen if recovery works, is that the first and third addresses are applied.

What would happen if recovery breaks is that the parser tries to parse the third line at the top level statement instead of inside `eth1`.

In either case, `eth2` should have its address.

Does that make sense?
</blockquote></details>

Makes sense, this is helpful - simplified this.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8621)* status: all files reviewed, 2 unresolved discussions (waiting on @SLarkworthy)

**Pull request merged**
