### PR TITLE
IcmpCode: convert to object

### PR DESCRIPTION
**Pull request by dhalperi**
* add type and code
* add human name
* add getter
* deploy throughout

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8217)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @anothermattbrown)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDIcmpCode.java, line 11 at r1](https://reviewable.io/reviews/batfish/batfish/8217#-MzqRL5rAhTfNCnoT1Ri:-MzqRL5rAhTfNCnoT1Rj:bbw4knu) ([raw file](https://github.com/batfish/batfish/blob/8cac453b0b2db42fb2a14c02efb7d9cb990393bf/projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDIcmpCode.java#L11)):*
> ```Java
> /** Symbolic {@link IcmpCode} variable represented by an 8-bit BDD. */
> public final class BDDIcmpCode {
>   public static final int UNSET = 0xff;
> ```

TODO: why is this here?

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 12 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8217)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @anothermattbrown and @dhalperi)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDIcmpCode.java, line 11 at r1](https://reviewable.io/reviews/batfish/batfish/8217#-MzqRL5rAhTfNCnoT1Ri:-MzqfKbs4K0CHH_6rvJp:b-7hvre0) ([raw file](https://github.com/batfish/batfish/blob/8cac453b0b2db42fb2a14c02efb7d9cb990393bf/projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDIcmpCode.java#L11)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

TODO: why is this here?
</blockquote></details>

good question -- perhaps we used to set that value in `Flow` to mean don't care? looks like we can remove it.

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 1 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8217)* status: 10 of 13 files reviewed, 1 unresolved discussion (waiting on @anothermattbrown and @dhalperi)

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8217)* status: 7 of 13 files reviewed, all discussions resolved (waiting on @anothermattbrown)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDIcmpCode.java, line 11 at r1](https://reviewable.io/reviews/batfish/batfish/8217#-MzqRL5rAhTfNCnoT1Ri:-MzxIhNx8rUV2MIZbDJs:b-7rl0jd) ([raw file](https://github.com/batfish/batfish/blob/8cac453b0b2db42fb2a14c02efb7d9cb990393bf/projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDIcmpCode.java#L11)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

good question -- perhaps we used to set that value in `Flow` to mean don't care? looks like we can remove it.
</blockquote></details>

done.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 7 of 13 files at r1, 3 of 3 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8217)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dhalperi)

**Pull request merged**
