### PR TITLE
DefinedStructure: remove

### PR DESCRIPTION
**Pull request by dhalperi**
All the structures are now defined right when the parser extracts their definitions.

I moved things that used to extend `DefinedStructure` to extending the parent class, which happens to be `ComparableStructure` -- this PR should commute with Matt's work on the latter.

### CODE REVIEW

**Comment by arifogel** [comment]
:lgtm:

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed, 2 unresolved discussions (waiting on @dhalperi and @anothermattbrown)

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/vendor_family/cisco/DocsisPolicy.java, line 17 at r1](https://reviewable.io/reviews/batfish/batfish/1698#-LFKITTL48cPb946EWmb:-LFKITTM6HUqxyAL7QTV:be298lc) ([raw file](https://github.com/batfish/batfish/blob/632d445862007f9c4ac2165a8498cea087845473/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/vendor_family/cisco/DocsisPolicy.java#L17)):*
> ```Java
> 
>   @JsonCreator
>   public DocsisPolicy(@JsonProperty(PROP_NAME) String number) {
> ```

Do you want to have separate static `JsonCreator` so you can have `@Nonnull String number` in constructor?
Applies elsewhere as well.

---

*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 3624 at r1](https://reviewable.io/reviews/batfish/batfish/1698#-LFKJ4L57Iaycb3JUKqf:-LFKJ4L64ybqv2Z3i_rm:bi86pj1) ([raw file](https://github.com/batfish/batfish/blob/632d445862007f9c4ac2165a8498cea087845473/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L3624)):*
> ```Java
>       asPathSet.getElements().add(elem);
>     }
>     _configuration.defineStructure(AS_PATH_SET, name, ctx.name.getStart().getLine());
> ```

Why do you sometimes qualify with `_configuration.` Is this the same as without?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1698#-:-LFKJNSS15HYG6mFvsR1:bnfp4nl)*

**Comment by dhalperi** [comment]
*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 3624 at r1](https://reviewable.io/reviews/batfish/batfish/1698#-LFKJ4L57Iaycb3JUKqf:-LFKK1tC44o7cv8VPVMy:b2wvhv3) ([raw file](https://github.com/batfish/batfish/blob/632d445862007f9c4ac2165a8498cea087845473/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L3624)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Why do you sometimes qualify with `_configuration.` Is this the same as without?
</blockquote></details>

`defineStructure(type, name, ctx)` uses all the lines between ctx.start and ctx.stop.  I should be using that one here.

The reason I was tripped up is because there's no enter rule here, which generally is an indicator of a multiline vs single-line structure.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1698)*

**Comment by dhalperi** [comment]
Review status: 9 of 12 files reviewed, 1 unresolved discussion (waiting on @arifogel, @dhalperi, and @anothermattbrown)

---

*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 3624 at r1](https://reviewable.io/reviews/batfish/batfish/1698#-LFKJ4L57Iaycb3JUKqf:-LFKLFwt7IVRMP4wYGt1:b-bi6kpv) ([raw file](https://github.com/batfish/batfish/blob/632d445862007f9c4ac2165a8498cea087845473/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L3624)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

`defineStructure(type, name, ctx)` uses all the lines between ctx.start and ctx.stop.  I should be using that one here.

The reason I was tripped up is because there's no enter rule here, which generally is an indicator of a multiline vs single-line structure.
</blockquote></details>

Now done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1698)*

**Comment by dhalperi** [comment]
Review status: 9 of 12 files reviewed, all discussions resolved (waiting on @arifogel and @anothermattbrown)

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/vendor_family/cisco/DocsisPolicy.java, line 17 at r1](https://reviewable.io/reviews/batfish/batfish/1698#-LFKITTL48cPb946EWmb:-LFKLNSH7CHGObGrD7q8:b-9n1tif) ([raw file](https://github.com/batfish/batfish/blob/632d445862007f9c4ac2165a8498cea087845473/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/vendor_family/cisco/DocsisPolicy.java#L17)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Do you want to have separate static `JsonCreator` so you can have `@Nonnull String number` in constructor?
Applies elsewhere as well.
</blockquote></details>

These are pre-existing issues I was not planning to tackle in this PR.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1698)*

**Comment by arifogel** [comment]
Reviewed 3 of 3 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown)

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1698)*

**Pull request merged**
