### PR TITLE
IOS-XR community parsing cleanup

### PR DESCRIPTION
**Pull request by arifogel**
- flesh out complete standard community grammar for IOS-XR
  - extract everything
  - leave unimplemented bits in conversion
- use modes for everything to do with community-set and standard
communities
  - delete community in
  - community matches-any/matches-all
  - community-set (definition)
- delete legacy community parsing code

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6851)* status: 0 of 24 files reviewed, 1 unresolved discussion (waiting on @arifogel and @dhalperi)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6851#-MXZ8TQn5791oBu98Vgu:-MXZ8TQn5791oBu98Vgv:bglcgkw) (no related file):*
working on adding tests for coverage

---

**Review by dhalperi — COMMENTED** [review]
> Reviewed 14 of 24 files at r1, 18 of 18 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6851)* status: all files reviewed, 2 unresolved discussions (waiting on @arifogel)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_acl.g4, line 147 at r2](https://reviewable.io/reviews/batfish/batfish/6851#-MXZYNwQCXhZMn_3NmAN:-MXZYNwRDydgSpM39WK8:bt764sr) ([raw file](https://github.com/batfish/batfish/blob/4c777793b86bdd9794425be0030f89565fa6d3df/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_acl.g4#L147)):*
> ```ANTLR
> ;
> 
> community_set_elem_list
> ```

If you end up making other changes in this PR, consider moving out of the _acl file?
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXrLexer.g4, line 952 at r2](https://reviewable.io/reviews/batfish/batfish/6851#-MXZWsXV4EWNhfw9WPza:-MXZWsXV4EWNhfw9WPzb:b1ufqfa) ([raw file](https://github.com/batfish/batfish/blob/4c777793b86bdd9794425be0030f89565fa6d3df/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXrLexer.g4#L952)):*
> ```
> lastTokenType() == SET
> ```

`ltt`?

Elsewhere, you used `switch` for this. No opinion.
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_xr/RoutePolicyDispositionStatement.java, line 72 at r2](https://reviewable.io/reviews/batfish/batfish/6851#-MXZX_CnAEtnOi-62pvw:-MXZX_CnAEtnOi-62pvx:bvvn3r1) ([raw file](https://github.com/batfish/batfish/blob/4c777793b86bdd9794425be0030f89565fa6d3df/projects/batfish/src/main/java/org/batfish/representation/cisco_xr/RoutePolicyDispositionStatement.java#L72)):*
> ```
> if (o == null || getClass() != o.getClass()) {
> ```

I personally prefer `else if (!(o instanceof <class>))` for final classes, but this is what IJ auto-generated isn't it?

Up to you.
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_xr/RoutePolicyDispositionStatement.java, line 81 at r2](https://reviewable.io/reviews/batfish/batfish/6851#-MXZXodqCjryjyyoPR7M:-MXZXodqCjryjyyoPR7N:bjt99ev) ([raw file](https://github.com/batfish/batfish/blob/4c777793b86bdd9794425be0030f89565fa6d3df/projects/batfish/src/main/java/org/batfish/representation/cisco_xr/RoutePolicyDispositionStatement.java#L81)):*
> ```
> Integer.hashCode
> ```
FYI this is the identity function. No action needed.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6851)* status: 19 of 34 files reviewed, 2 unresolved discussions (waiting on @dhalperi)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_acl.g4, line 147 at r2](https://reviewable.io/reviews/batfish/batfish/6851#-MXZYNwQCXhZMn_3NmAN:-MXZaZQR8FHehB_Stc8m:b-szhbky) ([raw file](https://github.com/batfish/batfish/blob/4c777793b86bdd9794425be0030f89565fa6d3df/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_acl.g4#L147)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

If you end up making other changes in this PR, consider moving out of the _acl file?
</blockquote></details>

sure, done.
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXrLexer.g4, line 952 at r2](https://reviewable.io/reviews/batfish/batfish/6851#-MXZWsXV4EWNhfw9WPza:-MXZZZEBCZaDnF8XaJmE:b-y60ovc) ([raw file](https://github.com/batfish/batfish/blob/4c777793b86bdd9794425be0030f89565fa6d3df/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXrLexer.g4#L952)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> lastTokenType() == SET
> ```

`ltt`?

Elsewhere, you used `switch` for this. No opinion.
</blockquote></details>

Fixed.
I started writing a swtich, realized it looked like crap, and went this route instead.,
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_xr/RoutePolicyDispositionStatement.java, line 72 at r2](https://reviewable.io/reviews/batfish/batfish/6851#-MXZX_CnAEtnOi-62pvw:-MXZaWex3DGbx4tbRBl9:bobs4m2) ([raw file](https://github.com/batfish/batfish/blob/4c777793b86bdd9794425be0030f89565fa6d3df/projects/batfish/src/main/java/org/batfish/representation/cisco_xr/RoutePolicyDispositionStatement.java#L72)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> if (o == null || getClass() != o.getClass()) {
> ```

I personally prefer `else if (!(o instanceof <class>))` for final classes, but this is what IJ auto-generated isn't it?

Up to you.
</blockquote></details>

was generated. fixed anyway.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 15 of 15 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6851)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6851)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
