### PR TITLE
Palo Alto: filter NAT rules on HA devices

### PR DESCRIPTION
**Pull request by sfraint**
* Track `high-availability` device id for PA devices
* Track device binding in PA NAT rules, and filter out inapplicable rules

### CODE REVIEW

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 4 of 11 files at r1, 13 of 15 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7650)* status: 18 of 19 files reviewed, 2 unresolved discussions (waiting on @anothermattbrown and @sfraint)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_nat.g4, line 37 at r3](https://reviewable.io/reviews/batfish/batfish/7650#-MnXuLgE68PKlG8C5qmD:-MnXuLgE68PKlG8C5qmE:bwrqtwl) ([raw file](https://github.com/batfish/batfish/blob/d9c38d649b93b796114307adebd1a419dd4648be/projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_nat.g4#L37)):*
> ```
> uint8 // 0 or 1
> ```
can/should we only parse 0 or 1?
___
*[projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java, line 2590 at r3](https://reviewable.io/reviews/batfish/batfish/7650#-MnXukI2DUFcRQAZ1El6:-MnXukI2DUFcRQAZ1El7:b-mpioug) ([raw file](https://github.com/batfish/batfish/blob/d9c38d649b93b796114307adebd1a419dd4648be/projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java#L2590)):*
> ```
> assert id == 1;
> ```
this is not an invariant -- a bad value can occur in the input file and we'll parse it. if we can restrict the grammar, we should probably detect/warn on bad values here

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7650)* status: 17 of 19 files reviewed, 2 unresolved discussions (waiting on @anothermattbrown)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_nat.g4, line 37 at r3](https://reviewable.io/reviews/batfish/batfish/7650#-MnXuLgE68PKlG8C5qmD:-MnXvfeD0CnhoK1UcHq5:b-86pdzn) ([raw file](https://github.com/batfish/batfish/blob/d9c38d649b93b796114307adebd1a419dd4648be/projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_nat.g4#L37)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

> ```
> uint8 // 0 or 1
> ```
can/should we only parse 0 or 1?
</blockquote></details>

it's not immediately apparent from the grammar file, but we do restrict to 0 or 1:
```
  private static final IntegerSpace ACTIVE_ACTIVE_DEVICE_BINDING_SPACE =
      IntegerSpace.of(Range.closed(0, 1));

  private Optional<Integer> toInteger(
      ParserRuleContext ctx, PaloAltoParser.Active_active_device_binding_valContext deviceBinding) {
    return toIntegerInSpace(
        ctx, deviceBinding, ACTIVE_ACTIVE_DEVICE_BINDING_SPACE, "active-active-device-binding");

```
___
*[projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java, line 2590 at r3](https://reviewable.io/reviews/batfish/batfish/7650#-MnXukI2DUFcRQAZ1El6:-MnXvnUY6IGjjTnctQor:byr4ffv) ([raw file](https://github.com/batfish/batfish/blob/d9c38d649b93b796114307adebd1a419dd4648be/projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java#L2590)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

> ```
> assert id == 1;
> ```
this is not an invariant -- a bad value can occur in the input file and we'll parse it. if we can restrict the grammar, we should probably detect/warn on bad values here
</blockquote></details>

see above

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7650)* status: 17 of 19 files reviewed, 2 unresolved discussions (waiting on @anothermattbrown)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_nat.g4, line 37 at r3](https://reviewable.io/reviews/batfish/batfish/7650#-MnXuLgE68PKlG8C5qmD:-MnXvrnFC6k0txiX9LKd:bdoe11q) ([raw file](https://github.com/batfish/batfish/blob/d9c38d649b93b796114307adebd1a419dd4648be/projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_nat.g4#L37)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

it's not immediately apparent from the grammar file, but we do restrict to 0 or 1:
```
  private static final IntegerSpace ACTIVE_ACTIVE_DEVICE_BINDING_SPACE =
      IntegerSpace.of(Range.closed(0, 1));

  private Optional<Integer> toInteger(
      ParserRuleContext ctx, PaloAltoParser.Active_active_device_binding_valContext deviceBinding) {
    return toIntegerInSpace(
        ctx, deviceBinding, ACTIVE_ACTIVE_DEVICE_BINDING_SPACE, "active-active-device-binding");

```
</blockquote></details>

if the value isn't in that range `[0, 1]`, then we warn and don't set a device binding value

I can go ahead and add a test for that as well, so it's clearer

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 1 of 15 files at r2, 1 of 2 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7650)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @sfraint)

**Review by sfraint — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7650)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

**Pull request merged**
