### PR TITLE
Bgp session status

### PR DESCRIPTION
**Pull request by ratulm**
This change is [Reviewable](https://reviewable.io/reviews/batfish/batfish/971)

### CODE REVIEW

**Comment by dhalperi** [comment]
Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---

*[projects/question/src/main/java/org/batfish/question/BgpSessionStatusQuestionPlugin.java, line 275 at r2](https://beta.reviewable.io/reviews/batfish/batfish/971#-L5uRe2h80kfkGPtfSkv:-L5uRe2h80kfkGPtfSkw:b-hmhpr1) ([raw file](https://github.com/batfish/batfish/blob/7301cd49ff1b2a2a8dbf0bcdb4bbf5d6d2b36b95/projects/question/src/main/java/org/batfish/question/BgpSessionStatusQuestionPlugin.java#L275)):*
> ```Java
>       }
>       return answerElement;
>     }
> ```

general Q: why is any of this code here? It looks like it belongs in/conflicts with/reimplements data plane or similar. Is there a piece of the (standard computed) data model we could hook into instead and not need to recompute it here?

---

*[projects/question/src/main/java/org/batfish/question/BgpSessionStatusQuestionPlugin.java, line 288 at r2](https://beta.reviewable.io/reviews/batfish/batfish/971#-L5uRKIk4j5Pot5s8Y6I:-L5uRKIk4j5Pot5s8Y6J:b-1d9krj) ([raw file](https://github.com/batfish/batfish/blob/7301cd49ff1b2a2a8dbf0bcdb4bbf5d6d2b36b95/projects/question/src/main/java/org/batfish/question/BgpSessionStatusQuestionPlugin.java#L288)):*
> for (String owner : owners) {
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>
>         if (includeNodes2.contains(owner)) {
>           return true;
>         }
>       }
>       return false;
</details>

`return !Sets.intersection(includeNodes2, owners).isEmpty();` ?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/971)*

**Comment by dhalperi** [comment]
*[projects/question/src/main/java/org/batfish/question/BgpSessionStatusQuestionPlugin.java, line 275 at r2](https://beta.reviewable.io/reviews/batfish/batfish/971#-L5uRe2h80kfkGPtfSkv:-L5uRtpf1kqiagxgHvM7:bs3mjec) ([raw file](https://github.com/batfish/batfish/blob/7301cd49ff1b2a2a8dbf0bcdb4bbf5d6d2b36b95/projects/question/src/main/java/org/batfish/question/BgpSessionStatusQuestionPlugin.java#L275)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

general Q: why is any of this code here? It looks like it belongs in/conflicts with/reimplements data plane or similar. Is there a piece of the (standard computed) data model we could hook into instead and not need to recompute it here?
</blockquote></details>

@arifogel @progwriter ?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/971)*

**Comment by progwriter** [comment]
*[projects/question/src/main/java/org/batfish/question/BgpSessionStatusQuestionPlugin.java, line 275 at r2](https://beta.reviewable.io/reviews/batfish/batfish/971#-L5uRe2h80kfkGPtfSkv:-L5uSSjTDo8UBYZMcnnN:b-e17x53) ([raw file](https://github.com/batfish/batfish/blob/7301cd49ff1b2a2a8dbf0bcdb4bbf5d6d2b36b95/projects/question/src/main/java/org/batfish/question/BgpSessionStatusQuestionPlugin.java#L275)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

@arifogel @progwriter ?
</blockquote></details>

afaik, no "clean" hooks just yet.
There is some overlap, however. I've definitely pulled out a `BgpSession` object (that acts as a wrapper around `BgpNeighbor`s) in ibdp and it implements a subset of this functionality. We should probably standardize the interface and make that part of the datamodel.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/971)*

**Comment by arifogel** [comment]
Reviewed 2 of 5 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/question/src/main/java/org/batfish/question/BgpSessionStatusQuestionPlugin.java, line 275 at r2](https://beta.reviewable.io/reviews/batfish/batfish/971#-L5uRe2h80kfkGPtfSkv:-L5v2AvM7BOxlJmnVinc:bg07fwl) ([raw file](https://github.com/batfish/batfish/blob/7301cd49ff1b2a2a8dbf0bcdb4bbf5d6d2b36b95/projects/question/src/main/java/org/batfish/question/BgpSessionStatusQuestionPlugin.java#L275)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

so, the verdict is to leave this stuff here for now and move/harmonize later? 
</blockquote></details>

Both DP and this class call `initRemoteBgpNeighbors`, so they are consistent that far.

---

*[projects/question/src/main/java/org/batfish/question/BgpSessionStatusQuestionPlugin.java, line 227 at r3](https://beta.reviewable.io/reviews/batfish/batfish/971#-L5v1sxS3RaLPhw-YEBp:-L5v1sxS3RaLPhw-YEBq:brvnzwn) ([raw file](https://github.com/batfish/batfish/blob/ab4ba535da78e3eadb683110fb090546f663063e/projects/question/src/main/java/org/batfish/question/BgpSessionStatusQuestionPlugin.java#L227)):*
> ```Java
>               Ip localIp = bgpNeighbor.getLocalIp();
>               Ip remoteIp = bgpNeighbor.getAddress();
>               if (bgpNeighbor.getPrefix().getPrefixLength() != 32) { // why is this here?
> ```

This is for passive BGP sessions, where you listen on a network (<32) rather than connect to a peer (32). BTW please use `Prefix.MAX_PREFIX_LENGTH` instead of `32`.
Currently it looks like we have very little support for passive sessions.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/971)*

**Comment by ratulm** [comment]
Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[projects/question/src/main/java/org/batfish/question/BgpSessionStatusQuestionPlugin.java, line 227 at r3](https://beta.reviewable.io/reviews/batfish/batfish/971#-L5v1sxS3RaLPhw-YEBp:-L5wIcVeC3Wd9no6OZQp:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/ab4ba535da78e3eadb683110fb090546f663063e/projects/question/src/main/java/org/batfish/question/BgpSessionStatusQuestionPlugin.java#L227)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

This is for passive BGP sessions, where you listen on a network (<32) rather than connect to a peer (32). BTW please use `Prefix.MAX_PREFIX_LENGTH` instead of `32`.
Currently it looks like we have very little support for passive sessions.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/971)*

**Comment by dhalperi** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/971#-:-L5yW1FC7gxP4UzK-7pj:bnfp4nl)*

**Pull request merged**
