### PR TITLE
Infer policies for named structures

### PR DESCRIPTION
**Pull request by millstein**
Infer likely role consistency polices for named structures, of the form:

* all nodes in the same role should have same-named structures of type T (e.g., IpAccessList, RouteMap)

* all nodes in the same role should have the same definition for same-named structures of type T

---
This change is [Reviewable](https://reviewable.io/reviews/batfish/batfish/863)

### CODE REVIEW

**Comment by corinaminer** [comment]
Reviewed 4 of 5 files at r1.
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/question/src/main/java/org/batfish/question/InferPoliciesQuestionPlugin.java, line 42 at r1](https://reviewable.io:443/reviews/batfish/batfish/863#-L3G3UvryMgFboYYKoDa:-L3G3UvryMgFboYYKoDb:b-anmd4x) ([raw file](https://github.com/batfish/batfish/blob/badb3b7f66e57f8eb76c1db8b47533657df5749c/projects/question/src/main/java/org/batfish/question/InferPoliciesQuestionPlugin.java#L42)):*
> ```Java
>     private static final String PROP_ROLE_CONSISTENCY_POLICIES = "roleConsistencyPolicies";
> 
>     private List<RoleConsistencyPolicy> _roleConsistencyPolicies;
> ```

Why make this a `List` rather than a `SortedSet` like your other policy collections?

---

*[projects/question/src/main/java/org/batfish/question/InferPoliciesQuestionPlugin.java, line 69 at r1](https://reviewable.io:443/reviews/batfish/batfish/863#-L3G0LPFwEGMLJg4mELz:-L3G0LPFwEGMLJg4mEM-:bsqwru8) ([raw file](https://github.com/batfish/batfish/blob/badb3b7f66e57f8eb76c1db8b47533657df5749c/projects/question/src/main/java/org/batfish/question/InferPoliciesQuestionPlugin.java#L69)):*
> ```Java
>             break;
>           default:
>             throw new BatfishException("this case should be unreachable");
> ```

`"Unrecognized hypothesis " + policy.getHypothesis()` would make the error message more useful.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/863)*

**Comment by corinaminer** [comment]
Reviewed 1 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/863)*

**Comment by millstein** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/question/src/main/java/org/batfish/question/InferPoliciesQuestionPlugin.java, line 69 at r1](https://reviewable.io:443/reviews/batfish/batfish/863#-L3G0LPFwEGMLJg4mELz:-L3Gde7HBzySUTrxrgg4:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/e2944ba8e6a15f2f80294be9a71522156f5966fb/projects/question/src/main/java/org/batfish/question/InferPoliciesQuestionPlugin.java#L69)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

`"Unrecognized hypothesis " + policy.getHypothesis()` would make the error message more useful.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/863)*

**Comment by millstein** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/question/src/main/java/org/batfish/question/InferPoliciesQuestionPlugin.java, line 42 at r1](https://reviewable.io:443/reviews/batfish/batfish/863#-L3G3UvryMgFboYYKoDa:-L3GdpdVzfVDUQDzZLTv:b-7ybxji) ([raw file](https://github.com/batfish/batfish/blob/e2944ba8e6a15f2f80294be9a71522156f5966fb/projects/question/src/main/java/org/batfish/question/InferPoliciesQuestionPlugin.java#L42)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Why make this a `List` rather than a `SortedSet` like your other policy collections?
</blockquote></details>

I use the SortedSets to sort the results within each hypothesis in alphabetical order of the node property (e.g., DnsServers, IpAccessList, etc.).  But now  I just want to concatenate these sorted sets to one another.  So using a list seemed more natural than making a new SortedSet, whose comparator would have to say to sort first by hypothesis and second by node property.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/863)*

**Pull request merged**
