### PR TITLE
allow getting answer status without workid

### PR DESCRIPTION
**Pull request by ratulm**
This change is [Reviewable](https://reviewable.io/reviews/batfish/batfish/712)

### CODE REVIEW

**Comment by corinaminer** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java, line 574 at r1](https://reviewable.io:443/reviews/batfish/batfish/712#-L-mBReIvaYJCGWeIgx4:-L-mB2BvjuxqX1nXXyp2:b-74cdvm) ([raw file](https://github.com/batfish/batfish/blob/26d29cb5ef58b9eb1a54d662f360f3d03085b2f8/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java#L574)):*
> ```Java
>             || !workItem.getTestrigName().equals(testrigName)) {
>           return failureResponse(
>               "Mismatch in parameters: WorkItem is not for the supplied container or testrig");
> ```

Is this intended to prevent users getting information about containers they shouldn't be able to access? Why do we need to check that testrig names match, or is that just for easier debugging?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/712)*

**Comment by ratulm** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java, line 574 at r1](https://reviewable.io:443/reviews/batfish/batfish/712#-L-mBReIvaYJCGWeIgx4:-L-mGMJFcotO3kwiWYcs:bbpu5uz) ([raw file](https://github.com/batfish/batfish/blob/26d29cb5ef58b9eb1a54d662f360f3d03085b2f8/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java#L574)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Is this intended to prevent users getting information about containers they shouldn't be able to access? Why do we need to check that testrig names match, or is that just for easier debugging?
</blockquote></details>

Both. Prevent unauthorized users, and catch bad client calls. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/712)*

**Comment by corinaminer** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/712#-:-L-mH1HydRbqE_6Fp0vk:bnfp4nl)*

**Comment by dhalperi** [comment]
:lgtm:

---

Reviewed 2 of 4 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/712#-:-L-m_e8bwNguw6MJejG9:bnfp4nl)*

**Pull request merged**
