### PR TITLE
Juniper fix icmp type and code handling

### PR DESCRIPTION
**Pull request by arifogel**
- support application matching of icmp-type and icmp-code, which was previously silently ignored
- fix lexing for keywords in `M_SubRange`
- use parse warnings instead of red flags for unmapped icmp types and codes

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8147)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclLineMatchExprs.java, line 237 at r1](https://reviewable.io/reviews/batfish/batfish/8147#-MyEj4x_DPQEAN1mdULQ:-MyEj4x_DPQEAN1mdULR:b-ij5ujs) ([raw file](https://github.com/batfish/batfish/blob/3b65daf6c1d0146f7c27891ea08b5a351161112b/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclLineMatchExprs.java#L237)):*
> ```Java
>   }
> 
>   public static @Nonnull AclLineMatchExpr matchIcmpCode(int icmpType) {
> ```

nit: code?



_Code quote:_
```Java
icmpType
```

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8147)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclLineMatchExprs.java, line 237 at r1](https://reviewable.io/reviews/batfish/batfish/8147#-MyEj4x_DPQEAN1mdULQ:-MyEjn9sBxCoepqmkMa8:b-7ql1td) ([raw file](https://github.com/batfish/batfish/blob/3b65daf6c1d0146f7c27891ea08b5a351161112b/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclLineMatchExprs.java#L237)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

nit: code?
</blockquote></details>

fixed

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8147)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8147)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Pull request merged**
