### PR TITLE
FortiOS: provide metadata for converted address and groups

### PR DESCRIPTION
**Pull request by dhalperi**
Example trace: Screen Shot 2021-04-08 at 4 31 10 PM

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6883)* status: 0 of 3 files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6883#-MXnpPba92GPycUEemS2:-MXnpPba92GPycUEemS3:b-nphvgi) (no related file):*
FYI hoping existing tests will fail.

---

**Comment by dhalperi** [comment]
Screen Shot 2021-04-08 at 4 35 37 PM

**Review by corinaminer — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6883#-:-MXrps6C8IVuF4ZuStOv:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6883#-MXnpPba92GPycUEemS2:-MXrpt_t7eCyY_DmICCL:bva37h1) (no related file):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

FYI hoping existing tests will fail.
</blockquote></details>

We haven't added grammar tests for traces afaik

---

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6883)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6883#-MXnpPba92GPycUEemS2:-MXrv5PmA_yyAEn3IBcu:b-cpw52s) (no related file):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

We haven't added grammar tests for traces afaik
</blockquote></details>

Yeah I added some unit tests, will have to add some trace tests too.

---

**Pull request merged**
