### PR TITLE
fix bug where serial line missing from data model for ASA devices

### PR DESCRIPTION
**Pull request by erikljungman**
if serial line not found in config, serial line wouldn't be added to data model

### CODE REVIEW

**Comment by anothermattbrown** [comment]
Reviewed 1 of 4 files at r1.
Review status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @erikljungman, @anothermattbrown, @dhalperi, and @arifogel)

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/LineMatchers.java, line 24 at r2](https://reviewable.io/reviews/batfish/batfish/1768#-LG140oq7YQ5eL_FKTKe:-LG140oq7YQ5eL_FKTKf:b9gbpm6) ([raw file](https://github.com/batfish/batfish/blob/e82c6043940cddc0f45a43db5132ae2e83d7fde6/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/LineMatchers.java#L24)):*
> ```Java
> 
>   /**
>    * Provides a matcher that matches when the {@link Line}'s {@code AaaAuthenticationLoginList} is
> ```

do you also want to consider if the list is non-null but empty?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1768)*

**Comment by erikljungman** [comment]
Review status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @anothermattbrown, @erikljungman, @dhalperi, and @arifogel)

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/LineMatchers.java, line 24 at r2](https://reviewable.io/reviews/batfish/batfish/1768#-LG140oq7YQ5eL_FKTKe:-LG1MyWOE4bPYCZ23VfN:b7anmnw) ([raw file](https://github.com/batfish/batfish/blob/e82c6043940cddc0f45a43db5132ae2e83d7fde6/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/LineMatchers.java#L24)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

do you also want to consider if the list is non-null but empty?
</blockquote></details>

good call

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1768)*

**Comment by arifogel** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
Review status: all files reviewed, 3 unresolved discussions (waiting on @anothermattbrown, @erikljungman, and @dhalperi)

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/LineMatchers.java, line 30 at r3](https://reviewable.io/reviews/batfish/batfish/1768#-LG1ZdVk7T83FUy6LhWk:-LG1ZdVk7T83FUy6LhWl:boklq8x) ([raw file](https://github.com/batfish/batfish/blob/95cc7bfc0c270ff38ba13c97d6e3d106c043acc8/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/LineMatchers.java#L30)):*
> ```Java
>    */
>   public static HasAuthenticationLoginList hasAuthenticationLoginList() {
>     return new HasAuthenticationLoginList(both(hasMethods()).and(notNullValue()));
> ```

Isn't the trailing `notNullValue()` redundant here? How could you assert something substantive about it if it's `null`?

---

*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 1730 at r3](https://reviewable.io/reviews/batfish/batfish/1768#-LG1ZqcEDxKGuz-RdeEg:-LG1ZqcEDxKGuz-RdeEh:bfk6tox) ([raw file](https://github.com/batfish/batfish/blob/95cc7bfc0c270ff38ba13c97d6e3d106c043acc8/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L1730)):*
> ```Java
>       // serial line may not be anywhere in the config so add it here to make sure the serial line
>       // is in the data model
>       _configuration.getCf().getLines().computeIfAbsent("serial", Line::new);
> ```

Please extract `"serial"` to a constant. Use that constant in the places where you are repeating the literal.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1768)*

**Comment by erikljungman** [comment]
Review status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @arifogel, @anothermattbrown, @erikljungman, and @dhalperi)

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/LineMatchers.java, line 30 at r3](https://reviewable.io/reviews/batfish/batfish/1768#-LG1ZdVk7T83FUy6LhWk:-LG1cIGl8xrniuBXlIk1:b-33cd9d) ([raw file](https://github.com/batfish/batfish/blob/95cc7bfc0c270ff38ba13c97d6e3d106c043acc8/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/LineMatchers.java#L30)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Isn't the trailing `notNullValue()` redundant here? How could you assert something substantive about it if it's `null`?
</blockquote></details>

yes it was redundant

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1768)*

**Comment by arifogel** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed, 2 unresolved discussions (waiting on @anothermattbrown, @erikljungman, and @dhalperi)

---

*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 1132 at r4](https://reviewable.io/reviews/batfish/batfish/1768#-LG1d6a07O61i0i0eI6x:-LG1d6a07O61i0i0eI6y:b-wh2bs0) ([raw file](https://github.com/batfish/batfish/blob/24917812d85912fdea1c6bd26aa7ca7d04cf9479/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L1132)):*
> ```Java
>   private static final String F_ACL_OBJECT = "acl match object";
> 
>   private static final String SERIAL_LINE = "serial";
> ```

You were using this literal elsewhere in the PR (in a test I believe).
You could make this constant package-private, and annotate it with `@VisibleForTesting` so you can use it in the test in place of the literals 

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1768)*

**Comment by arifogel** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed, 1 unresolved discussion (waiting on @anothermattbrown and @dhalperi)

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1768#-:-LG1yWaYAexpntiYptqa:bnfp4nl)*

**Pull request merged**
