### PR TITLE
Save the original zip file uploaded by the user

### PR DESCRIPTION
**Pull request by dhalperi**
Keeping the exact data around in its original form will help us iterate
on issues.

---
This change is [Reviewable](https://reviewable.io/reviews/batfish/batfish/766)

### CODE REVIEW

**Comment by arifogel** [comment]
:lgtm: except for one requested change.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, line 1219 at r1](https://reviewable.io:443/reviews/batfish/batfish/766#-L0LXUo1V3punh240LVy:-L0LXUo2ngGi0BgWTLTz:bt5yn8w) ([raw file](https://github.com/batfish/batfish/blob/fe0e706b47e16e9c3c71c817ddda96cbdc5daa7a/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java#L1219)):*
> ```Java
>       throw new BatfishException("Failed to create directory: '" + originalDir + "'");
>     }
>     Path zipFile = originalDir.resolve("testrig.zip");
> ```

`testrig.zip` should be a constant in `BfConsts`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/766#-:-L0LXol3Ta2ztyNpG-U4:b9snbtv)*

**Comment by dhalperi** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, line 1219 at r1](https://reviewable.io:443/reviews/batfish/batfish/766#-L0LXUo1V3punh240LVy:-L0LYZgoQiTyyNmMnFWI:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/fe0e706b47e16e9c3c71c817ddda96cbdc5daa7a/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java#L1219)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

`testrig.zip` should be a constant in `BfConsts`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/766)*

**Comment by arifogel** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/766)*

**Comment by ratulm** [comment]
are we messing with the original data anywhere? i thought we only unzip it and never write anything else to it. if that is the case, can we not retrieve the original by zipping the "testrig" directory under the testrig?

**Pull request merged**
