### PR TITLE
Simple parsing changes

### PR DESCRIPTION
**Pull request by jkhourybbn**

### CODE REVIEW

**Comment by arifogel** [comment]
Review status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @jkhourybbn and @arifogel)

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1771#-LG1dalK2FXJ5IVASIm7:-LG1dalK2FXJ5IVASIm8:b-hpfzs4) (no related file):*
I could have sworn we are handling these lines. So this may in fact be a breaking change.
Can you please provide example lines you are trying to handle? I'd like to know how this will impact our collection of SNMP servers DNS servers into the data model.

If we do end up going with your grammar change, please note that we require test cases for all new parsing changes.
Since these lines are being ignored, you could add unit test lines in `test_rigs/unit-tests/configs`. 
But please hold off unless we know this change is appropriate.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1771)*

**Comment by arifogel** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed, 1 unresolved discussion (waiting on @jkhourybbn)

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1771)*

**Comment by jkhourybbn** [comment]
@arifogel Here are config snippets that were not being parsed by batfish

The BATFISH parser doesn't accept:
```
no ip name-server
no snmp-server
```

The parser doesn't accept the `no ip mask-reply` directive in the interface-specific area

**Comment by arifogel** [comment]
Review status: all files reviewed, 3 unresolved discussions (waiting on @jkhourybbn)

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1771#-LG1dalK2FXJ5IVASIm7:-LG1vAD1DALKiqWVSnny:bv1q2t6) (no related file):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

I could have sworn we are handling these lines. So this may in fact be a breaking change.
Can you please provide example lines you are trying to handle? I'd like to know how this will impact our collection of SNMP servers DNS servers into the data model.

If we do end up going with your grammar change, please note that we require test cases for all new parsing changes.
Since these lines are being ignored, you could add unit test lines in `test_rigs/unit-tests/configs`. 
But please hold off unless we know this change is appropriate.
</blockquote></details>

Based on your above comment,  your changes to `Cisco_ignored.g4` are breaking, since they may interfere with the grammar rules for the positive versions of those lines.
To prevent that, you can wrap the tokens you added with `NO`.
I added suggestions for how to do this.

Please add the test cases in appropriate files in `test_rigs/unit-tests/configs/`.

After you have made the other grammar changes I suggested, run `.travis/build.sh` from the root of the repository. This will generated `XXX.ref.testout` files which should be copied over the corresponding `XXX.ref` files if the changes look right.

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_ignored.g4, line 688 at r1](https://reviewable.io/reviews/batfish/batfish/1771#-LG1vz0QE7b7jbvltXfR:-LG1vz0R6_Y4zwlLwA9s:b-yts9pp) ([raw file](https://github.com/batfish/batfish/blob/097273355a68c9a2e8d169f6b7da9a93c7a4dfc4/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_ignored.g4#L688)):*
> ```ANTLR
>             | LOAD_SHARING
>             | LOCAL
>             | NAME_SERVER
> ```

move this out of the positive `IP` parenthetical expression:
```
|
( NO IP (NAME_SERVER))
```

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_ignored.g4, line 885 at r1](https://reviewable.io/reviews/batfish/batfish/1771#-LG1w4lI37MJYQ1Hxoc8:-LG1w4lI37MJYQ1Hxoc9:b-1c6woe) ([raw file](https://github.com/batfish/batfish/blob/097273355a68c9a2e8d169f6b7da9a93c7a4dfc4/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_ignored.g4#L885)):*
> ```ANTLR
>       | SMTP_SERVER
>       | SNMP
>       | SNMP_SERVER
> ```

wrap with `NO`:
```
| (NO SNMP_SERVER)
```

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_interface.g4, line 538 at r1](https://reviewable.io/reviews/batfish/batfish/1771#-LG1wL8Y4UTXiLFvaLX1:-LG1wL8Y4UTXiLFvaLX2:b-4a2sg5) ([raw file](https://github.com/batfish/batfish/blob/097273355a68c9a2e8d169f6b7da9a93c7a4dfc4/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_interface.g4#L538)):*
> ```ANTLR
>             | IRDP
>             | LOAD_SHARING
>             | MASK_REPLY
> ```

This is fine.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1771)*

**Comment by jkhourybbn** [comment]
@arifogel did what you suggested but wasn't sure how to interpret the test diffs -- parsing is successful 
Let me know if there is anything else

**Comment by arifogel** [comment]
Your updated ref file looks good in isolation. However, when merged, it looks like it would be off.
I think your code is probably just out of date.
Please merge with master, rebuild the testout file, and recopy it over the ref.
Otherwise everything :lgtm:

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed, 1 unresolved discussion (waiting on @jkhourybbn)

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1771#-:-LGQrDQz5_OhAKTxuz8z:be4jlze)*

**Comment by jkhourybbn** [comment]
pushed

**Comment by arifogel** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1771)*

**Pull request merged**
