### PR TITLE
IOS XR: update route-policy default action

### PR DESCRIPTION
**Pull request by sfraint**
Routes that are modified in route-policies are treated as default-pass instead of default-drop. From [Cisco docs](https://www.cisco.com/c/en/us/td/docs/routers/xr12000/software/xr12k_r4-0/routing/configuration/guide/rc40xr12k_chapter7.html#con_1118699):

> Default Drop Disposition
> All route policies have a default action to drop the route under evaluation unless the route has been modified by a policy action or explicitly passed. Applied (nested) policies implement this disposition as though the applied policy were pasted into the point where it is applied.

### CODE REVIEW

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6971)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @corinaminer and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6971#-MZPoDtIAahisML5YW-N:-MZPoDtM2yHRvTNUZl94:bejr54u) (no related file):*
test updates still in-progress

---

**Review by corinaminer — COMMENTED** [review]
> Reviewed 7 of 8 files at r1, 6 of 7 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6971)* status: all files reviewed, 2 unresolved discussions (waiting on @sfraint)

___
*[projects/batfish/src/test/java/org/batfish/grammar/cisco_xr/XrGrammarTest.java, line 645 at r2](https://reviewable.io/reviews/batfish/batfish/6971#-MZQ5sBi3Zj-AmisCzoU:-MZQ5sBjE16DL-P-LWMe:b-hhqpzx) ([raw file](https://github.com/batfish/batfish/blob/cf051bf8abeece11be54cb068ae5c5217d1737e9/projects/batfish/src/test/java/org/batfish/grammar/cisco_xr/XrGrammarTest.java#L645)):*
> ```Java
>     // No match / no route update should use default-deny
>     Bgpv4Route bgpNoMatch = baseBgp.setNetwork(prefixNoMatch).build();
>     assertRoutingPolicyDeniesRoute(rp, bgpNoMatch);
> ```

I think this test should avoid sharing builders, just to be sure that the route is modified when it's expected to be modified (as opposed to somehow having picked up the expected attribute in one of the previous routing policy calls).
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfExternalRoute.java, line 136 at r1](https://reviewable.io/reviews/batfish/batfish/6971#-MZP5u4d42dB060Xsczz:-MZP5u4d42dB060Xsd--:bed3uea) ([raw file](https://github.com/batfish/batfish/blob/d141d695a0b10d2070c8ed10fdd419c5ebdfc8f0/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfExternalRoute.java#L136)):*
> ```Java
>   /** Return a route builder with pre-filled mandatory values. To be used in tests only */
>   @VisibleForTesting
>   public static Builder testBuilder() {
> ```

Rather than adding this, you can just use `OspfExternalType1Route.testBuilder()`.

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6971)* status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @corinaminer)

___
*[projects/batfish/src/test/java/org/batfish/grammar/cisco_xr/XrGrammarTest.java, line 645 at r2](https://reviewable.io/reviews/batfish/batfish/6971#-MZQ5sBi3Zj-AmisCzoU:-MZQAlum0qONjMSWYMyU:bvnrpcm) ([raw file](https://github.com/batfish/batfish/blob/cf051bf8abeece11be54cb068ae5c5217d1737e9/projects/batfish/src/test/java/org/batfish/grammar/cisco_xr/XrGrammarTest.java#L645)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

I think this test should avoid sharing builders, just to be sure that the route is modified when it's expected to be modified (as opposed to somehow having picked up the expected attribute in one of the previous routing policy calls).
</blockquote></details>

updated
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfExternalRoute.java, line 136 at r1](https://reviewable.io/reviews/batfish/batfish/6971#-MZP5u4d42dB060Xsczz:-MZQ9ykg9JvPc2X0u4KD:bvnrpcm) ([raw file](https://github.com/batfish/batfish/blob/d141d695a0b10d2070c8ed10fdd419c5ebdfc8f0/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfExternalRoute.java#L136)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Rather than adding this, you can just use `OspfExternalType1Route.testBuilder()`.
</blockquote></details>

updated

**Review by corinaminer — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6971#-:-MZQBOtG5lGJjyCGzcbK:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
