### PR TITLE
TransferBDD: optionally combine paths with equal results on the fly

### PR DESCRIPTION
**Pull request by dhalperi**
**Stack**:
- #9148
- #9147 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/9147)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dhalperi)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/9147#-O3jP-4z9INROQGKnqKn:-O3jP-4z9INROQGKnqKo:bfs2fe5) (no related file):*
Still needs tests.

___

**Review by nickgian — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/9147)* status: all files reviewed, 3 unresolved discussions (waiting on @dhalperi and @millstein)

___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java` line 293 at r2](https://reviewable.io/reviews/batfish/batfish/9147#-O3lVH9g9wtAkQD_CVO1:-O3lVH9g9wtAkQD_CVO2:b-vilzus) ([raw file](https://github.com/batfish/batfish/blob/c482f28b57c9dcc18b1bdcb72ddfd19812c6b2a7/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java#L293)):*
> ```Java
>    */
>   private List<TransferResult> compute(
>       BooleanExpr expr, TransferBDDState state, Context context, boolean retainAllPaths)
> ```

Do you have any intuition about how different it would be if you combined paths only in the "main" `compute` function (the one that takes a list of statements)?

For correctness I assume it is the same, for performance it is more difficult to say. It depends on the VI structure, which is not fresh in my memory right now. I have a suspicion it would be a small number of paths you combine in the expr/statement `compute` functions, and the majority of reduction comes from the main `compute` - but I might be totally wrong :)

1. Doing it only in one `compute` function would reduce complexity (though no strong feelings about it), and might even end up being faster if we are wasting a lot of effort trying to combine elsewhere. Would be useful to have some measurements on how much this helps and at which point paths get combined.
2. Side-q: It is always safe to miss/forget to combine paths in one of these branches, right?
___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java` line 1515 at r2](https://reviewable.io/reviews/batfish/batfish/9147#-O3mCnz9CHV9WhI_OF7t:-O3mCnz9CHV9WhI_OF7u:bf9ar9t) ([raw file](https://github.com/batfish/batfish/blob/c482f28b57c9dcc18b1bdcb72ddfd19812c6b2a7/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java#L1515)):*
> ```Java
>     grouped.forEach(
>         (state, inputConstraints) ->
>             ret.add(replaceInputConstraint.apply(factory.orAll(inputConstraints), state)));
> ```

`orAllAndFree` works I think.
___
*[`projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferBDDTest.java` line 3791 at r2](https://reviewable.io/reviews/batfish/batfish/9147#-O3mEPQtEgKPJuZwkzfN:-O3mEPQtEgKPJuZwkzfO:b-xss0fc) ([raw file](https://github.com/batfish/batfish/blob/c482f28b57c9dcc18b1bdcb72ddfd19812c6b2a7/projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferBDDTest.java#L3791)):*
> ```Java
>     initial =
>         new TransferBDDState(new TransferParam(routeParam, false), new TransferResult(routeParam));
>     assertThat(tbdd.computePaths(initial, manyMatchesSameResult, context, false), hasSize(2));
> ```

nice :D

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/9147)* status: all files reviewed, 2 unresolved discussions (waiting on @millstein and @nickgian)

___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java` line 293 at r2](https://reviewable.io/reviews/batfish/batfish/9147#-O3lVH9g9wtAkQD_CVO1:-O3mSfwM7DPFizCE18M3:b-5hsbh4) ([raw file](https://github.com/batfish/batfish/blob/c482f28b57c9dcc18b1bdcb72ddfd19812c6b2a7/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java#L293)):*
<details><summary><i>Previously, nickgian (Nick Giannarakis) wrote…</i></summary><blockquote>

Do you have any intuition about how different it would be if you combined paths only in the "main" `compute` function (the one that takes a list of statements)?

For correctness I assume it is the same, for performance it is more difficult to say. It depends on the VI structure, which is not fresh in my memory right now. I have a suspicion it would be a small number of paths you combine in the expr/statement `compute` functions, and the majority of reduction comes from the main `compute` - but I might be totally wrong :)

1. Doing it only in one `compute` function would reduce complexity (though no strong feelings about it), and might even end up being faster if we are wasting a lot of effort trying to combine elsewhere. Would be useful to have some measurements on how much this helps and at which point paths get combined.
2. Side-q: It is always safe to miss/forget to combine paths in one of these branches, right?
</blockquote></details>

2 is easier to answer: I claim it's always safe to miss/forget, as long as there is only 1 main entry point to this code that has it on all exit paths. (I think this is true, a'la your question 1).

1 is a bit nuanced. Given that the way we implement `continue` is with many-deep `CallExpr` chains, I'm concerned we need this for `BooleanExpr` too. (Tho `CallExpr` does go back to the `List<Statements>` version I guess)

But, thinking about it, there were other confounding factors when I wrote this PR. Specifically, the filtering out of unreachables in `Conjunction`/`Disjunction` (#9148) turns out to have been really important. Had I realized that first, I might have seen different intermediate results on the way.

For context, your intuition is right. In my "hard profiling test case" that analyzes ~1k devices with hundreds of thousands of policies in a single go, much of the time is now being spent in combining. The tradeoff may have shifted to where these inner combines become less useful.

[That case went from (>24h) to <8m with these changes so far.]

I'd vote for looking at it again later, as this is a 2-way door.
___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java` line 1515 at r2](https://reviewable.io/reviews/batfish/batfish/9147#-O3mCnz9CHV9WhI_OF7t:-O3mUYEkC89E6-UnFUnv:bu9tsaf) ([raw file](https://github.com/batfish/batfish/blob/c482f28b57c9dcc18b1bdcb72ddfd19812c6b2a7/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java#L1515)):*
<details><summary><i>Previously, nickgian (Nick Giannarakis) wrote…</i></summary><blockquote>

`orAllAndFree` works I think.
</blockquote></details>

I'm really unsure of the ownership invariants around BDDs in this library. We often replace one field but leave the input the same, for example. That said, I think you're right.

I want to try to establish those invariants (and put in `assert` statements) before freeing BDDs outside the code context (function/line/etc) where they are created. Follow-on work.

**Review by nickgian — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/9147#-:-O3mcdUX0wbQxB3p8ZO0:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi and @millstein)

___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java` line 293 at r2](https://reviewable.io/reviews/batfish/batfish/9147#-O3lVH9g9wtAkQD_CVO1:-O3mcIHl9Xtj22z7C5DY:b-36550t) ([raw file](https://github.com/batfish/batfish/blob/c482f28b57c9dcc18b1bdcb72ddfd19812c6b2a7/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java#L293)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

2 is easier to answer: I claim it's always safe to miss/forget, as long as there is only 1 main entry point to this code that has it on all exit paths. (I think this is true, a'la your question 1).

1 is a bit nuanced. Given that the way we implement `continue` is with many-deep `CallExpr` chains, I'm concerned we need this for `BooleanExpr` too. (Tho `CallExpr` does go back to the `List<Statements>` version I guess)

But, thinking about it, there were other confounding factors when I wrote this PR. Specifically, the filtering out of unreachables in `Conjunction`/`Disjunction` (#9148) turns out to have been really important. Had I realized that first, I might have seen different intermediate results on the way.

For context, your intuition is right. In my "hard profiling test case" that analyzes ~1k devices with hundreds of thousands of policies in a single go, much of the time is now being spent in combining. The tradeoff may have shifted to where these inner combines become less useful.

[That case went from (>24h) to <8m with these changes so far.]

I'd vote for looking at it again later, as this is a 2-way door.
</blockquote></details>

Sounds good, agreed this is not a blocker, we can always revisit.

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/9147)* status: all files reviewed, 1 unresolved discussion (waiting on @millstein and @nickgian)

___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java` line 293 at r2](https://reviewable.io/reviews/batfish/batfish/9147#-O3lVH9g9wtAkQD_CVO1:-O3ntn5i3KMd_cFEI-rD:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/f3796d53b1ea2299ba72cb205f1fef3e28907cbf/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java#L293)):*
<details><summary><i>Previously, nickgian (Nick Giannarakis) wrote…</i></summary><blockquote>

Sounds good, agreed this is not a blocker, we can always revisit.
</blockquote></details>

Done.

**Review by dhalperi — COMMENTED** [review]
> Dismissed @nickgian from a discussion.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/9147)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @millstein)

**Pull request merged**
