### PR TITLE
TableAnswerElement: make final

### PR DESCRIPTION
**Pull request by dhalperi**

### CODE REVIEW

**Comment by dhalperi** [comment]
*[a discussion](https://reviewable.io/reviews/batfish/batfish/1516#-LDiY18pBUTpgFvOYxeM:-LDiY18qCz3PeWi8w4bZ:b-relxwh) (no related file):*
Blocked on all downstream clients not needing to extend.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1516)*

**Comment by ratulm** [comment]
:lgtm: 

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/TableAnswerElement.java, line 18 at r1](https://reviewable.io/reviews/batfish/batfish/1516#-LDibs7bBImDdBO7RkcO:-LDibs7bBImDdBO7RkcP:bd3zesv) ([raw file](https://github.com/batfish/batfish/blob/a62d1fa8d75a87d8082037b34453416719ded713/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/TableAnswerElement.java#L18)):*
> ```Java
> import org.batfish.datamodel.questions.Question;
> 
> /** A base class for tabular answers */
> ```

"A base class" -> "The class"

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1516#-:-LDic17sCSYEnowgH-cb:bg7igkv)*

**Comment by ratulm** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1516)*

**Comment by dhalperi** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1516)*

**Pull request merged**
