### PR TITLE
compute port-channel bandwidth from underlying interfaces

### PR DESCRIPTION
**Pull request by arifogel**
- add support for interface 'speed' command on EOS and IOS

### CODE REVIEW

**Comment by dhalperi** [comment]
Reviewed 2 of 14 files at r1, 8 of 27 files at r2.
Review status: 10 of 33 files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 4513 at r2](https://reviewable.io/reviews/batfish/batfish/1453#-LD5NIwy9XxpafS4jUq1:-LD5NIwy9XxpafS4jUq2:butgevw) ([raw file](https://github.com/batfish/batfish/blob/7b4b29a99cc2fb20b743a7628f5fa5e71b1862ac/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L4513)):*
> ```Java
>   }
> 
>   private String computeAggregatedInterfaceName(int num, ConfigurationFormat format) {
> ```

@Nullable

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 3157 at r2](https://reviewable.io/reviews/batfish/batfish/1453#-LD5NYiD-cqmfvGYQ6Fp:-LD5NYiD-cqmfvGYQ6Fq:b143qbl) ([raw file](https://github.com/batfish/batfish/blob/7b4b29a99cc2fb20b743a7628f5fa5e71b1862ac/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L3157)):*
> ```Java
>                                             .addAll(portChannel.getChannelGroupMembers())
>                                             .add(ifaceName)
>                                             .build());
> ```

Rewrite this to be more readable -- what's going on here?

You should be able to unnest a few levels using flatMap, temp variables, and/or other helper functions. This is unreadable as-is.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/Interface.java, line 97 at r2](https://reviewable.io/reviews/batfish/batfish/1453#-LD5O5rcAaMuM19_0BfC:-LD5O5rcAaMuM19_0BfD:b-2yrno5) ([raw file](https://github.com/batfish/batfish/blob/7b4b29a99cc2fb20b743a7628f5fa5e71b1862ac/projects/batfish/src/main/java/org/batfish/representation/cisco/Interface.java#L97)):*
> ```Java
>     } else if (name.startsWith("Loopback")) {
>       bandwidth = LOOPBACK_BANDWIDTH;
>     } else if (name.startsWith("Port-Channel")) {
> ```

Do you not want the same logic as below? Tunnel and Bundle-Ethernet too?

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/Interface.java, line 567 at r2](https://reviewable.io/reviews/batfish/batfish/1453#-LD5OBShATxc449CYPRy:-LD5OBShATxc449CYPRz:bmvkthq) ([raw file](https://github.com/batfish/batfish/blob/7b4b29a99cc2fb20b743a7628f5fa5e71b1862ac/projects/batfish/src/main/java/org/batfish/representation/cisco/Interface.java#L567)):*
> ```Java
>   }
> 
>   public static boolean isSelfReferencingInterface(String name) {
> ```

is "self-referencing" really the salient feature of these interfaces? I'm not sure what this is really for.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1453)*

**Comment by dhalperi** [comment]
Reviewed 2 of 14 files at r1, 2 of 27 files at r2.
Review status: 14 of 33 files reviewed at latest revision, 4 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 1331 at r2](https://reviewable.io/reviews/batfish/batfish/1453#-LD5OsTa88-F3Y1_H19P:-LD5OsTa88-F3Y1_H19Q:b4mjtxr) ([raw file](https://github.com/batfish/batfish/blob/7b4b29a99cc2fb20b743a7628f5fa5e71b1862ac/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L1331)):*
> ```Java
>       if (Interface.isSelfReferencingInterface(name)) {
>         _configuration.referenceStructure(INTERFACE, name, INTERFACE_SELF_REFERENCE, line);
>       }
> ```

This changes is invasive enough that it should be separated out into their own PR and reviewed on its own merits. Not coupled with changes to speed, etc.

---

*[tests/aws/init-example-aws.ref, line 225 at r2](https://reviewable.io/reviews/batfish/batfish/1453#-LD5OZp0A7X4xEwbon7k:-LD5OZp0A7X4xEwbon7l:b-hyilxp) ([raw file](https://github.com/batfish/batfish/blob/7b4b29a99cc2fb20b743a7628f5fa5e71b1862ac/tests/aws/init-example-aws.ref#L225)):*
> ```
>               116
>             ],
>             "numReferrers" : 0
> ```

self-referencing?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1453)*

**Comment by arifogel** [comment]
Review status: 7 of 13 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 1331 at r2](https://reviewable.io/reviews/batfish/batfish/1453#-LD5OsTa88-F3Y1_H19P:-LD835iGCQ4yaSWW7o9x:b-3qbpak) ([raw file](https://github.com/batfish/batfish/blob/7b4b29a99cc2fb20b743a7628f5fa5e71b1862ac/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L1331)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

This changes is invasive enough that it should be separated out into their own PR and reviewed on its own merits. Not coupled with changes to speed, etc.
</blockquote></details>

I removed the reference stuff

---

*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 4513 at r2](https://reviewable.io/reviews/batfish/batfish/1453#-LD5NIwy9XxpafS4jUq1:-LD83cAR7t-VXOYeljcF:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/7b4b29a99cc2fb20b743a7628f5fa5e71b1862ac/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L4513)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

@Nullable
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 3157 at r2](https://reviewable.io/reviews/batfish/batfish/1453#-LD5NYiD-cqmfvGYQ6Fp:-LD885ZuAhLDlHSViq6x:b-qev2zc) ([raw file](https://github.com/batfish/batfish/blob/7b4b29a99cc2fb20b743a7628f5fa5e71b1862ac/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L3157)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Rewrite this to be more readable -- what's going on here?

You should be able to unnest a few levels using flatMap, temp variables, and/or other helper functions. This is unreadable as-is.
</blockquote></details>

flatMap ended up being just as verbose.
I did break apart though.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/Interface.java, line 97 at r2](https://reviewable.io/reviews/batfish/batfish/1453#-LD5O5rcAaMuM19_0BfC:-LD88PquDlH58L4TsViz:b-7uk58d) ([raw file](https://github.com/batfish/batfish/blob/7b4b29a99cc2fb20b743a7628f5fa5e71b1862ac/projects/batfish/src/main/java/org/batfish/representation/cisco/Interface.java#L97)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Do you not want the same logic as below? Tunnel and Bundle-Ethernet too?
</blockquote></details>

added bundle-ethernet. not touching tunnel for now, as i am unsure of semantics.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/Interface.java, line 567 at r2](https://reviewable.io/reviews/batfish/batfish/1453#-LD5OBShATxc449CYPRy:-LD88UstBIyLM5YO1MZ-:bo1y3mc) ([raw file](https://github.com/batfish/batfish/blob/7b4b29a99cc2fb20b743a7628f5fa5e71b1862ac/projects/batfish/src/main/java/org/batfish/representation/cisco/Interface.java#L567)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

is "self-referencing" really the salient feature of these interfaces? I'm not sure what this is really for.
</blockquote></details>

removed for now.

---

*[tests/aws/init-example-aws.ref, line 225 at r2](https://reviewable.io/reviews/batfish/batfish/1453#-LD5OZp0A7X4xEwbon7k:-LD88YCM8prTZCd-_DBE:bo1y3mc) ([raw file](https://github.com/batfish/batfish/blob/7b4b29a99cc2fb20b743a7628f5fa5e71b1862ac/tests/aws/init-example-aws.ref#L225)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

self-referencing?
</blockquote></details>

removed for now.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1453)*

**Comment by dhalperi** [comment]
:lgtm:

---

Reviewed 6 of 14 files at r1, 3 of 27 files at r2, 13 of 24 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1453#-:-LD8D-lA-aUE6GndRoKp:bnfp4nl)*

**Pull request merged**
