### PR TITLE
Avoid failure in the case of multiple partially blocking lines

### PR DESCRIPTION
**Pull request by corinaminer**
It is possible for ACL reachability to crash because of unreachable lines with no single blocking line:
```
 permit	ip any 0.0.0.0    0.255.255.255
 permit	ip any 1.0.0.0    0.255.255.255
 permit	ip any 0.0.0.0    1.255.255.255      // unreachable
```
This change avoids that crash by providing a dummy answer for those cases. Still TBD how we will extract the line numbers for multiple blocking lines to provide better information to the user.

### CODE REVIEW

**Comment by arifogel** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1310#-:-LBhd6WY8_KjYMvORA-2:bg7igkv)*

**Comment by dhalperi** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 783 at r1](https://reviewable.io/reviews/batfish/batfish/1310#-LBhebWYEBymxFYXfE-t:-LBnp7TzCz5NYVMvmQpB:b81qjzj) ([raw file](https://github.com/batfish/batfish/blob/b76d5acdf4d0521f4799d35c2a0850c0b2f01fed/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L783)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

please add test :)
</blockquote></details>

Making unblocking since I'm traveling

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1310)*

**Comment by arifogel** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1310#-LBrSgpf7QXc_AIWVpUC:-LBrSgpg8PXsgVTgr1fD:barr84l) (no related file):*
This PR includes and relies on #1272, but not #1315 which reverts it. As such, it must be resolved against the conflicts introduced by the revert PR.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1310)*

**Comment by arifogel** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1310#-LBrTCNvDHJIUia4w1e7:-LBrTCNw5kaVyovVHX82:bncujcj) (no related file):*
Functionality introduced in PR #1317 duplicates that introduced in this PR. The important pieces should make it in here, and #1317 should be closed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1310)*

**Comment by arifogel** [comment]
:lgtm: again

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1310#-:-LC0erAS8DvXChAy4zgg:b-865gvj)*

**Comment by corinaminer** [comment]
Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 783 at r1](https://reviewable.io/reviews/batfish/batfish/1310#-LBhebWYEBymxFYXfE-t:-LC0jB0l2klYaK7hbcLk:b3moqbj) ([raw file](https://github.com/batfish/batfish/blob/b76d5acdf4d0521f4799d35c2a0850c0b2f01fed/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L783)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Making unblocking since I'm traveling
</blockquote></details>

Improved the test implemented in #1329

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1310)*

**Comment by arifogel** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1310)*

**Pull request merged**
