### PR TITLE
cisco support extended acl using object-group

### PR DESCRIPTION
**Pull request by arifogel**
- added IpSpaceReference
- need to pass definitions to named IpSpaces around in lots of places
- may need to be split because HeaderSpace now uses IpSpace for dstIp,
  srcIp, etc. This causes far-reaching consequences.

### CODE REVIEW

**Comment by arifogel** [comment]
Review status: 0 of 111 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[a discussion](https://beta.reviewable.io/reviews/batfish/batfish/1210#-LAUOAzl8Nj9gXCP5GUl:-LAUOAzl8Nj9gXCP5GUm:b-jb66bn) (no related file):*
REVIEWERS: please review only changes to cisco classes and tests. The rest is not yet ready.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1210)*

**Comment by arifogel** [comment]
Review status: 0 of 119 files reviewed at latest revision, 3 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EmptyIpSpace.java, line 31 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1210#-LAUldNz34Xc_uSIBin2:-LAVM-lW1HsIqj256eki:b-tam1y6) ([raw file](https://github.com/batfish/batfish/blob/06e67a7a878a3098877337768563e0661fb6fd84/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EmptyIpSpace.java#L31)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> Map<String, IpSpace> namedIpSpaces
> ```

To be slightly forward, I'd suggest introducing a context class rather than just supplying a `Map`.  Next week, there will be another thing you want to pass that you can just add to the context.
</blockquote></details>

How about I do that next time? I honestly think this might be the last one.
However I am open to cleaning up anyway afterwards.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpSpace.java, line 22 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1210#-LAUm1As-arPrYjKWaB9:-LAVLvEZCfVy8CAxRKP-:b-6k2u6c) ([raw file](https://github.com/batfish/batfish/blob/06e67a7a878a3098877337768563e0661fb6fd84/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpSpace.java#L22)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

are we certain that complement and accept don't need context?
</blockquote></details>

Not if  you implement them in a context-free way. I'd rather leave the choice to the visitor (which would have the context).

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1210)*

**Comment by sfraint** [comment]
Reviewed 17 of 115 files at r1, 1 of 14 files at r2, 5 of 44 files at r7, 4 of 25 files at r10, 1 of 23 files at r11.
Review status: 28 of 144 files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Flow.java, line 897 at r11](https://reviewable.io/reviews/batfish/batfish/1210#-LAsUAOZC0a8asiZKaK-:-LAsUAOZC0a8asiZKaK0:b-sxf6ug) ([raw file](https://github.com/batfish/batfish/blob/6bc726d078e7e7a442234ab93be326cdd38565ef/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Flow.java#L897)):*
> ```Java
>   }
> 
>   public Builder rebuild() {
> ```

Maybe call this `toBuilder` for consistency with other classes

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/OrMatchExpr.java, line 19 at r11](https://reviewable.io/reviews/batfish/batfish/1210#-LAsXbjn1ZN-T1ZcdBQ5:-LAsXbjn1ZN-T1ZcdBQ6:bwq45jo) ([raw file](https://github.com/batfish/batfish/blob/6bc726d078e7e7a442234ab93be326cdd38565ef/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/OrMatchExpr.java#L19)):*
> ```Java
> 
>   @JsonCreator
>   public OrMatchExpr(@JsonProperty(PROP_DISJUNCTS) Collection<AclLineMatchExpr> disjuncts) {
> ```

Why use a `collection` here instead of `iterable`?
Also, if it makes sense here, maybe it also makes sense in `AndMatchExpr`

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1210)*

**Comment by arifogel** [comment]
Review status: 42 of 144 files reviewed at latest revision, 4 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Flow.java, line 897 at r11](https://reviewable.io/reviews/batfish/batfish/1210#-LAsUAOZC0a8asiZKaK-:-LAsfhNHEkimMqh1jFqk:b-k2trc8) ([raw file](https://github.com/batfish/batfish/blob/6bc726d078e7e7a442234ab93be326cdd38565ef/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Flow.java#L897)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

Maybe call this `toBuilder` for consistency with other classes
</blockquote></details>

I was following pattern from `HeaderSpace`, but looks like that is the minority. Changed.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/OrMatchExpr.java, line 19 at r11](https://reviewable.io/reviews/batfish/batfish/1210#-LAsXbjn1ZN-T1ZcdBQ5:-LAsai6392ymBkzUkvCW:b-48jgz4) ([raw file](https://github.com/batfish/batfish/blob/6bc726d078e7e7a442234ab93be326cdd38565ef/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/OrMatchExpr.java#L19)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

Why use a `collection` here instead of `iterable`?
Also, if it makes sense here, maybe it also makes sense in `AndMatchExpr`
</blockquote></details>

I was playing around with `isEmpty`, which is not part of `Iterable`. Looks like my final implementation doesn't use it though, so I relaxed back to `Iterable` as suggested. As it turns out, `AndMatchExpr` is already using `Iterable`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1210)*

**Comment by sfraint** [comment]
Reviewed 12 of 115 files at r1, 1 of 14 files at r2, 1 of 43 files at r6, 13 of 44 files at r7, 1 of 25 files at r10, 5 of 23 files at r11, 2 of 2 files at r12, 4 of 14 files at r13.
Review status: 79 of 144 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1210)*

**Comment by sfraint** [comment]
Reviewed 7 of 115 files at r1, 1 of 14 files at r2, 18 of 43 files at r6, 6 of 44 files at r7, 2 of 14 files at r9, 12 of 25 files at r10, 9 of 23 files at r11, 6 of 14 files at r13.
Review status: 140 of 144 files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish/src/main/java/org/batfish/symbolic/bdd/AclLineMatchExprToBDD.java, line 183 at r13](https://reviewable.io/reviews/batfish/batfish/1210#-LAxsCHqDK9X6AB2pBA7:-LAxsCHqDK9X6AB2pBA8:b-kjdqby) ([raw file](https://github.com/batfish/batfish/blob/8f8c8c917f2cc87c9067aca57bc2d871229aa742/projects/batfish/src/main/java/org/batfish/symbolic/bdd/AclLineMatchExprToBDD.java#L183)):*
> ```Java
>   @Override
>   public BDD visitPermittedByAcl(PermittedByAcl permittedByAcl) {
>     throw new BatfishException("TODO: PermittedByAcl");
> ```

Just a nitpick, but I'd stick with the same style exception message here as above:
`PermittedByAcl is unsupported` (similar comment applies in a few other files)

---

*[projects/batfish/src/main/java/org/batfish/symbolic/smt/BoolExprOps.java, line 24 at r13](https://reviewable.io/reviews/batfish/batfish/1210#-LAxzzNi5YUjT37Tpj1O:-LAxzzNi5YUjT37Tpj1P:b-bgtkwe) ([raw file](https://github.com/batfish/batfish/blob/8f8c8c917f2cc87c9067aca57bc2d871229aa742/projects/batfish/src/main/java/org/batfish/symbolic/smt/BoolExprOps.java#L24)):*
> ```Java
> 
>   public BoolExpr or(BoolExpr... disjuncts) {
>     return andNonNull(Arrays.stream(disjuncts).filter(Objects::nonNull).toArray(BoolExpr[]::new));
> ```

Is this supposed to be `orNonNull`?

---

*[projects/batfish/src/main/java/org/batfish/symbolic/bdd/IpSpaceToBDD.java, line 97 at r13](https://reviewable.io/reviews/batfish/batfish/1210#-LAxwitu4h_hD1bNlIjC:-LAxwitu4h_hD1bNlIjD:bb4hq8a) ([raw file](https://github.com/batfish/batfish/blob/8f8c8c917f2cc87c9067aca57bc2d871229aa742/projects/batfish/src/main/java/org/batfish/symbolic/bdd/IpSpaceToBDD.java#L97)):*
> ```Java
>   @Override
>   public BDD visitIpSpaceReference(IpSpaceReference ipSpaceReference) {
>     throw new UnsupportedOperationException(
> ```

Make the exceptions in this class match, exception type and message style.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1210)*

**Comment by arifogel** [comment]
Review status: 137 of 144 files reviewed at latest revision, 3 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/symbolic/bdd/AclLineMatchExprToBDD.java, line 183 at r13](https://reviewable.io/reviews/batfish/batfish/1210#-LAxsCHqDK9X6AB2pBA7:-LAz9HSF4B6vi78nvi2k:b-q7dant) ([raw file](https://github.com/batfish/batfish/blob/8f8c8c917f2cc87c9067aca57bc2d871229aa742/projects/batfish/src/main/java/org/batfish/symbolic/bdd/AclLineMatchExprToBDD.java#L183)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

Just a nitpick, but I'd stick with the same style exception message here as above:
`PermittedByAcl is unsupported` (similar comment applies in a few other files)
</blockquote></details>

Fixed by @anothermattbrown

---

*[projects/batfish/src/main/java/org/batfish/symbolic/smt/BoolExprOps.java, line 24 at r13](https://reviewable.io/reviews/batfish/batfish/1210#-LAxzzNi5YUjT37Tpj1O:-LAz9_iL98nXh8HJpreI:b-q7dant) ([raw file](https://github.com/batfish/batfish/blob/8f8c8c917f2cc87c9067aca57bc2d871229aa742/projects/batfish/src/main/java/org/batfish/symbolic/smt/BoolExprOps.java#L24)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

Is this supposed to be `orNonNull`?
</blockquote></details>

Fixed by @anothermattbrown

---

*[projects/batfish/src/main/java/org/batfish/symbolic/bdd/IpSpaceToBDD.java, line 97 at r13](https://reviewable.io/reviews/batfish/batfish/1210#-LAxwitu4h_hD1bNlIjC:-LAz9Zam3Ax0K7GcyheL:b-q7dant) ([raw file](https://github.com/batfish/batfish/blob/8f8c8c917f2cc87c9067aca57bc2d871229aa742/projects/batfish/src/main/java/org/batfish/symbolic/bdd/IpSpaceToBDD.java#L97)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

Make the exceptions in this class match, exception type and message style.
</blockquote></details>

Fixed by @anothermattbrown

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1210)*

**Comment by anothermattbrown** [comment]
Reviewed 4 of 115 files at r1, 12 of 44 files at r7, 4 of 23 files at r11, 1 of 2 files at r12.
Review status: 137 of 144 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/OrMatchExpr.java, line 19 at r12](https://reviewable.io/reviews/batfish/batfish/1210#-LAuI5Sq1jbj4Hhx59M4:-LAuI5Sq1jbj4Hhx59M5:brog94o) ([raw file](https://github.com/batfish/batfish/blob/ba06565d48bcc54c0a2effaacd805d402d6a6999/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/OrMatchExpr.java#L19)):*
> ```Java
>   @JsonCreator
>   public OrMatchExpr(@JsonProperty(PROP_DISJUNCTS) Iterable<AclLineMatchExpr> disjuncts) {
>     _disjuncts = disjuncts != null ? ImmutableSortedSet.copyOf(disjuncts) : ImmutableSortedSet.of();
> ```

can we make `disjuncts` be `@Nonnull`?

---

*[projects/batfish/src/main/java/org/batfish/symbolic/smt/BoolExprOps.java, line 24 at r13](https://reviewable.io/reviews/batfish/batfish/1210#-LAxzzNi5YUjT37Tpj1O:-LAyhSxsDj4rhtBOg5bH:bjse4k) ([raw file](https://github.com/batfish/batfish/blob/8f8c8c917f2cc87c9067aca57bc2d871229aa742/projects/batfish/src/main/java/org/batfish/symbolic/smt/BoolExprOps.java#L24)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

Is this supposed to be `orNonNull`?
</blockquote></details>

yikes! yes

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1210)*

**Comment by arifogel** [comment]
Review status: 137 of 144 files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/OrMatchExpr.java, line 19 at r12](https://reviewable.io/reviews/batfish/batfish/1210#-LAuI5Sq1jbj4Hhx59M4:-LAzGdDn3YeqE8P5BJrZ:b1m536c) ([raw file](https://github.com/batfish/batfish/blob/ba06565d48bcc54c0a2effaacd805d402d6a6999/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/OrMatchExpr.java#L19)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

can we make `disjuncts` be `@Nonnull`?
</blockquote></details>

No. With our current Jackson settings, empty collections are omitted from the output JSON. When you deserialize using a `@JsonCreator`, those fields come in as null. Contrast to `HeaderSpace` (no `@JsonCreator`)  which initializes collections to empty in its constructor. The lack of a setter there is no problem, since no further modification occurs. But here in `OrMatchExpr`, we MUST set a value in the constructor based on the deserialization of the object.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1210)*

**Comment by anothermattbrown** [comment]
Review status: 137 of 144 files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/OrMatchExpr.java, line 19 at r12](https://reviewable.io/reviews/batfish/batfish/1210#-LAuI5Sq1jbj4Hhx59M4:-LAzI0Wn5NAMfhJiQ_Ab:b32w0x) ([raw file](https://github.com/batfish/batfish/blob/ba06565d48bcc54c0a2effaacd805d402d6a6999/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/OrMatchExpr.java#L19)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

No. With our current Jackson settings, empty collections are omitted from the output JSON. When you deserialize using a `@JsonCreator`, those fields come in as null. Contrast to `HeaderSpace` (no `@JsonCreator`)  which initializes collections to empty in its constructor. The lack of a setter there is no problem, since no further modification occurs. But here in `OrMatchExpr`, we MUST set a value in the constructor based on the deserialization of the object.
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1210)*

**Comment by arifogel** [comment]
Reviewed 1 of 14 files at r2, 2 of 43 files at r6, 1 of 25 files at r10, 3 of 4 files at r14.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/java/org/batfish/datamodel/visitors/IpSpaceMayNotContainWildcard.java, line 107 at r14](https://reviewable.io/reviews/batfish/batfish/1210#-LAzP2V35KzKZBqpyIYD:-LAzP2V35KzKZBqpyIYE:bwcj3w2) ([raw file](https://github.com/batfish/batfish/blob/a5dadf1bf1d851fa3d23ed9e4066faf7a8a42445/projects/batfish/src/main/java/org/batfish/datamodel/visitors/IpSpaceMayNotContainWildcard.java#L107)):*
> ```Java
>   @Override
>   public Boolean visitPrefixIpSpace(PrefixIpSpace prefixIpSpace) {
>     return !new IpWildcard(prefixIpSpace.getPrefix()).supersetOf(_ipWildcard);
> ```

Is this strict superset?

---

*[projects/batfish/src/main/java/org/batfish/z3/expr/BooleanExpr.java, line 49 at r14](https://reviewable.io/reviews/batfish/batfish/1210#-LAzMSgG6A4iIqbmPdX-:-LAzMSgG6A4iIqbmPdX0:b-uwbrre) ([raw file](https://github.com/batfish/batfish/blob/a5dadf1bf1d851fa3d23ed9e4066faf7a8a42445/projects/batfish/src/main/java/org/batfish/z3/expr/BooleanExpr.java#L49)):*
> ```Java
>       return new NotExpr(expr);
>     }
>   }
> ```

All three of these functions are doing simplification. Why not just do construction and leave simplification to the simplifier?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1210)*

**Comment by sfraint** [comment]
Reviewed 1 of 115 files at r1, 2 of 14 files at r2, 1 of 43 files at r6, 1 of 25 files at r10, 1 of 23 files at r11, 3 of 4 files at r14.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish/src/test/java/org/batfish/symbolic/smt/IpAccessListToBoolExprTest.java, line 26 at r13](https://reviewable.io/reviews/batfish/batfish/1210#-LAyDCFO0W3LjQAcP_QW:-LAyDCFO0W3LjQAcP_QX:b-lez2if) ([raw file](https://github.com/batfish/batfish/blob/8f8c8c917f2cc87c9067aca57bc2d871229aa742/projects/batfish/src/test/java/org/batfish/symbolic/smt/IpAccessListToBoolExprTest.java#L26)):*
> ```Java
> 
>   @Test
>   public void testAndMatchExpr() {}
> ```

Was this intentionally left empty?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1210)*

**Comment by arifogel** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[projects/batfish/src/test/java/org/batfish/symbolic/smt/IpAccessListToBoolExprTest.java, line 26 at r13](https://reviewable.io/reviews/batfish/batfish/1210#-LAyDCFO0W3LjQAcP_QW:-LAzPzXCC4uu1E8aT-0x:b-4v21fq) ([raw file](https://github.com/batfish/batfish/blob/8f8c8c917f2cc87c9067aca57bc2d871229aa742/projects/batfish/src/test/java/org/batfish/symbolic/smt/IpAccessListToBoolExprTest.java#L26)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

Was this intentionally left empty?
</blockquote></details>

(Also testOrMatchExpr)

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1210)*

**Comment by anothermattbrown** [comment]
Reviewed 5 of 115 files at r1, 2 of 14 files at r2, 1 of 43 files at r6, 4 of 44 files at r7, 2 of 25 files at r10, 6 of 23 files at r11, 4 of 14 files at r13.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/z3/expr/BooleanExpr.java, line 49 at r14](https://reviewable.io/reviews/batfish/batfish/1210#-LAzMSgG6A4iIqbmPdX-:-LAzQLFFEHq3kRgomaw7:b-yqp7zr) ([raw file](https://github.com/batfish/batfish/blob/a5dadf1bf1d851fa3d23ed9e4066faf7a8a42445/projects/batfish/src/main/java/org/batfish/z3/expr/BooleanExpr.java#L49)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

All three of these functions are doing simplification. Why not just do construction and leave simplification to the simplifier?
</blockquote></details>

I think I had the same though, because these aren't being used anymore. I'll remove them.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1210)*

**Comment by anothermattbrown** [comment]
*[projects/batfish/src/main/java/org/batfish/z3/expr/BooleanExpr.java, line 49 at r14](https://reviewable.io/reviews/batfish/batfish/1210#-LAzMSgG6A4iIqbmPdX-:-LAzRdb-0YgcHTZ72eqP:bitfr8x) ([raw file](https://github.com/batfish/batfish/blob/a5dadf1bf1d851fa3d23ed9e4066faf7a8a42445/projects/batfish/src/main/java/org/batfish/z3/expr/BooleanExpr.java#L49)):*
> though
thought

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1210)*

**Comment by arifogel** [comment]
Reviewed 1 of 1 files at r15, 1 of 1 files at r16.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1210)*

**Comment by anothermattbrown** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1210#-:-LAzSYt9Bm7Ab7paLjPD:bnfp4nl)*

**Comment by anothermattbrown** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/datamodel/visitors/IpSpaceMayNotContainWildcard.java, line 107 at r14](https://reviewable.io/reviews/batfish/batfish/1210#-LAzP2V35KzKZBqpyIYD:-LAzShXp7zt4FqhxfKYb:b-luujqf) ([raw file](https://github.com/batfish/batfish/blob/a5dadf1bf1d851fa3d23ed9e4066faf7a8a42445/projects/batfish/src/main/java/org/batfish/datamodel/visitors/IpSpaceMayNotContainWildcard.java#L107)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Is this strict superset?
</blockquote></details>

no. I'm adding a unit test for that too

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1210)*

**Comment by arifogel** [comment]
Reviewed 1 of 1 files at r17.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1210)*

**Comment by arifogel** [comment]
Reviewed 1 of 1 files at r18.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1210)*

**Pull request merged**
