### PR TITLE
Sonic VLANs

### PR DESCRIPTION
**Pull request by ratulm**

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7818)* status: all files reviewed, 5 unresolved discussions (waiting on @ratulm)

___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConfiguration.java, line 114 at r1](https://reviewable.io/reviews/batfish/batfish/7818#-Mr0UEik-P78muUClm_u:-Mr0UEil6Aed5JTCjUAU:b-drl19o) ([raw file](https://github.com/batfish/batfish/blob/235acc5a1857a8863d64787958a63f5207b1f278/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConfiguration.java#L114)):*
> ```Java
>         || _configDb.getLoopbacks().containsKey(ifaceName)
>         || _configDb.getMgmtPorts().containsKey(ifaceName)
>         || _configDb.getVlans().containsKey(ifaceName);
> ```

Shouldn't this be `getVlanInterfaces`?
Same question for `getInterfaceVrf` and `getInterfaceAddresses`.
___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConversions.java, line 128 at r1](https://reviewable.io/reviews/batfish/batfish/7818#-Mr0W_CB5TZhR26k6UzJ:-Mr0W_CB5TZhR26k6UzK:b55fcfa) ([raw file](https://github.com/batfish/batfish/blob/235acc5a1857a8863d64787958a63f5207b1f278/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConversions.java#L128)):*
> ```Java
>   // Super simple name to type conversion
>   // TODO: expand later as needed
>   private static InterfaceType interfaceNameToType(String interfaceName) {
> ```

nit: `@Nonnull`
___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/VlanMember.java, line 19 at r1](https://reviewable.io/reviews/batfish/batfish/7818#-Mr0V5d00mHeTWMiH8Vh:-Mr0V5d10XOVNdv9_TsO:b-ozk9vm) ([raw file](https://github.com/batfish/batfish/blob/235acc5a1857a8863d64787958a63f5207b1f278/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/VlanMember.java#L19)):*
> ```Java
>   private @Nullable final String _taggingMode;
> 
>   public @Nullable String getTaggingMode() {
> ```

Should tagging mode be an enum?
___
*[projects/batfish/src/test/java/org/batfish/vendor/sonic/grammar/SonicGrammarTest.java, line 137 at r1](https://reviewable.io/reviews/batfish/batfish/7818#-Mr0VEAlArXRm_Wo3KnU:-Mr0VEAlArXRm_Wo3KnV:bge9m3l) ([raw file](https://github.com/batfish/batfish/blob/235acc5a1857a8863d64787958a63f5207b1f278/projects/batfish/src/test/java/org/batfish/vendor/sonic/grammar/SonicGrammarTest.java#L137)):*
> ```Java
>             hasVrfName("default"),
>             hasAddress("172.19.0.1/24"),
>             hasInterfaceType(InterfaceType.VLAN)));
> ```

`hasVlan`?
___
*[projects/batfish/src/test/java/org/batfish/vendor/sonic/representation/SonicConversionsTest.java, line 152 at r1](https://reviewable.io/reviews/batfish/batfish/7818#-Mr0VkS49T4eQ8xSURyN:-Mr0VkS49T4eQ8xSURyO:bn2k5cj) ([raw file](https://github.com/batfish/batfish/blob/235acc5a1857a8863d64787958a63f5207b1f278/projects/batfish/src/test/java/org/batfish/vendor/sonic/representation/SonicConversionsTest.java#L152)):*
> ```Java
>             hasSwitchPortMode(SwitchportMode.ACCESS),
>             hasAccessVlan(1)));
>     // Ethernet2 does not exist in c -- it should have been created
> ```

From here down looks ldentical to above, i.e. you have tests for `Ethernet2` twice

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7818)* status: all files reviewed, 2 unresolved discussions (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConfiguration.java, line 114 at r1](https://reviewable.io/reviews/batfish/batfish/7818#-Mr0UEik-P78muUClm_u:-Mr0kzV57XMTAOeyvZrv:bvmnidw) ([raw file](https://github.com/batfish/batfish/blob/235acc5a1857a8863d64787958a63f5207b1f278/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConfiguration.java#L114)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Shouldn't this be `getVlanInterfaces`?
Same question for `getInterfaceVrf` and `getInterfaceAddresses`.
</blockquote></details>

The primary place where a vlans are defined is in `VLAN` table. Vlan2 (say) will show up in `VLAN_INTERFACE` table if `Vlan2` is an L3 interface. So, some interfaces may never show in `VLAN_INTERFACE` table. 
___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/VlanMember.java, line 19 at r1](https://reviewable.io/reviews/batfish/batfish/7818#-Mr0V5d00mHeTWMiH8Vh:-Mr0oCM57IVHiTEki_AS:br24o4v) ([raw file](https://github.com/batfish/batfish/blob/235acc5a1857a8863d64787958a63f5207b1f278/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/VlanMember.java#L19)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Should tagging mode be an enum?
</blockquote></details>

probably. did it this way for the ease of surfacing warnings in case a third mode exists. anyway. changed to enum to simplify downstream code.

**Review by arifogel — COMMENTED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7818)* status: all files reviewed, 1 unresolved discussion (waiting on @ratulm)

___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConfiguration.java, line 114 at r1](https://reviewable.io/reviews/batfish/batfish/7818#-Mr0UEik-P78muUClm_u:-Mr3gXYH-90ogFADFh6n:bl753zk) ([raw file](https://github.com/batfish/batfish/blob/235acc5a1857a8863d64787958a63f5207b1f278/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConfiguration.java#L114)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

The primary place where a vlans are defined is in `VLAN` table. Vlan2 (say) will show up in `VLAN_INTERFACE` table if `Vlan2` is an L3 interface. So, some interfaces may never show in `VLAN_INTERFACE` table. 
</blockquote></details>

Seems like you are making my argument for me. You get an IRB interface only if the vlan has an entry in the `VLAN_INTERFACE` table. So why are you checking the `VLAN` table? Hit me up offline if this is not clear.

**Review by arifogel — COMMENTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7818)* status: all files reviewed, 1 unresolved discussion (waiting on @ratulm)

___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConversions.java, line 143 at r3](https://reviewable.io/reviews/batfish/batfish/7818#-Mr4wWUe-pEgK3GfUYk0:-Mr4wWUf7Hl4RRkFGaWN:bk63vgh) ([raw file](https://github.com/batfish/batfish/blob/71d86748177765e71112da05af700399b3522bd3/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConversions.java#L143)):*
> ```Java
>   static boolean checkVlanId(String vlanName, @Nullable Integer vlanId, Warnings w) {
>     if (vlanId == null) {
>       w.redFlag(String.format("%s ignored: vlanid is not configured.", vlanName));
> ```

Aren't you double warning? Once for the whole set difference (via `warnMissingVlans`), and once here for each VLAN_INTERFACE missing a VLAN?

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7818)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConversions.java, line 143 at r3](https://reviewable.io/reviews/batfish/batfish/7818#-Mr4wWUe-pEgK3GfUYk0:-Mr51pTA5SZLRPhYVl1O:b-lh3cof) ([raw file](https://github.com/batfish/batfish/blob/71d86748177765e71112da05af700399b3522bd3/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConversions.java#L143)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Aren't you double warning? Once for the whole set difference (via `warnMissingVlans`), and once here for each VLAN_INTERFACE missing a VLAN?
</blockquote></details>

Don't think so. Missing `warnMissingVlans` is only for names that are defined under `VLAN_INTERFACE` but not in `VLAN`. `checkVlanId` is only called for things under `VLAN`.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7818)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ratulm)

___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConversions.java, line 143 at r3](https://reviewable.io/reviews/batfish/batfish/7818#-Mr4wWUe-pEgK3GfUYk0:-Mr5EbXb76nnP-pyVLAp:b-jesrwc) ([raw file](https://github.com/batfish/batfish/blob/71d86748177765e71112da05af700399b3522bd3/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConversions.java#L143)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

Don't think so. Missing `warnMissingVlans` is only for names that are defined under `VLAN_INTERFACE` but not in `VLAN`. `checkVlanId` is only called for things under `VLAN`.
</blockquote></details>

Got it, misread before.

**Review by ratulm — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7818)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ratulm)

**Review by ratulm — COMMENTED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7818)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ratulm)

**Pull request merged**
