### PR TITLE
Enable Z3 parallelism for OSX

### PR DESCRIPTION
**Pull request by arifogel**
This change is [Reviewable](https://reviewable.io/reviews/batfish/batfish/879)

### CODE REVIEW

**Comment by arifogel** [comment]
Note that I have updated the [batfish Z3 release](https://github.com/batfish/z3/releases/download/z3-2018-01-12-450f3c9b459d128135abb5bbd4fa0508fe26bfae/z3-2018-01-12-450f3c9b459d128135abb5bbd4fa0508fe26bfae-x64-osx-10.13.2.zip) to include and be compiled against OpenMP,

**Comment by dhalperi** [comment]
How did you change how z3 works without changing the sha?

Where is the current version of the code?

Are your changes in review by z3 team?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/879#-:-L3nV5pyov7-6ykT5UOM:b-j1xmqb)*

**Comment by dhalperi** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/879)*

**Comment by dhalperi** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/879#-:-L42J26TrurokEEETc7T:bnfp4nl)*

**Pull request merged**
