### PR TITLE
fix reachability parameter passing inconsistencies

### PR DESCRIPTION
**Pull request by arifogel**

### CODE REVIEW

**Comment by anothermattbrown** [comment]
Reviewed 5 of 9 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/IBatfish.java, line 193 at r2](https://reviewable.io:443/reviews/batfish/batfish/1061#-L7kAgsVvaMsTRov2KGU:-L7kAgsWZWM5alYKJgn4:b3w65ez) ([raw file](https://github.com/batfish/batfish/blob/5479268fe209c616de61530bc2c45602b2ae61d0/projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/IBatfish.java#L193)):*
> ```Java
> 
>   AnswerElement standard(
>       ReachabilitySettings.Builder reachabilitySettingsBuilder,
> ```

why can't we just pass in `ReachabilitySettings`?

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 2582 at r2](https://reviewable.io:443/reviews/batfish/batfish/1061#-L7kAnuVmcNgNr3AlZoM:-L7kAnuVmcNgNr3AlZoN:b-duc46) ([raw file](https://github.com/batfish/batfish/blob/5479268fe209c616de61530bc2c45602b2ae61d0/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L2582)):*
> ```Java
>   @Override
>   public AnswerElement multipath(
>       ReachabilitySettings.Builder reachabilitySettingsBuilder, boolean useCompression) {
> ```

same comment

---

*[projects/question/src/main/java/org/batfish/question/ReachabilityQuestionPlugin.java, line 536 at r2](https://reviewable.io:443/reviews/batfish/batfish/1061#-L7kC22_HR3P2n4BnIrs:-L7kC22_HR3P2n4BnIrt:b-l1l3mk) ([raw file](https://github.com/batfish/batfish/blob/5479268fe209c616de61530bc2c45602b2ae61d0/projects/question/src/main/java/org/batfish/question/ReachabilityQuestionPlugin.java#L536)):*
> ```Java
>     @JsonProperty(PROP_DST_IPS)
>     public void setDstIps(SortedSet<IpWildcard> dstIps) {
>       _reachabilitySettings.getHeaderSpace().setDstIps(new TreeSet<>(dstIps));
> ```

use `ImmutableSortedSet`?

---

*[projects/question/src/main/java/org/batfish/question/ReachabilityQuestionPlugin.java, line 541 at r2](https://reviewable.io:443/reviews/batfish/batfish/1061#-L7kCHW4sKVslDcqBvw8:-L7kCHW4sKVslDcqBvw9:b-l1l3mk) ([raw file](https://github.com/batfish/batfish/blob/5479268fe209c616de61530bc2c45602b2ae61d0/projects/question/src/main/java/org/batfish/question/ReachabilityQuestionPlugin.java#L541)):*
> ```Java
>     @JsonProperty(PROP_DST_PORTS)
>     public void setDstPorts(SortedSet<SubRange> dstPorts) {
>       _reachabilitySettings.getHeaderSpace().setDstPorts(new TreeSet<>(dstPorts));
> ```

use `ImmutableSortedSet`?

---

*[projects/question/src/main/java/org/batfish/question/ReachabilityQuestionPlugin.java, line 547 at r2](https://reviewable.io:443/reviews/batfish/batfish/1061#-L7kCIIr2-7ilcu0CVrH:-L7kCIIr2-7ilcu0CVrI:b-l1l3mk) ([raw file](https://github.com/batfish/batfish/blob/5479268fe209c616de61530bc2c45602b2ae61d0/projects/question/src/main/java/org/batfish/question/ReachabilityQuestionPlugin.java#L547)):*
> ```Java
>     @JsonProperty(PROP_DST_PROTOCOLS)
>     public void setDstProtocols(SortedSet<Protocol> dstProtocols) {
>       _reachabilitySettings.getHeaderSpace().setDstProtocols(new TreeSet<>(dstProtocols));
> ```

use `ImmutableSortedSet`?

---

*[projects/question/src/main/java/org/batfish/question/ReachabilityQuestionPlugin.java, line 566 at r2](https://reviewable.io:443/reviews/batfish/batfish/1061#-L7kDTx1s6VWXlK28-Gj:-L7kDTx1s6VWXlK28-Gk:bjxobef) ([raw file](https://github.com/batfish/batfish/blob/5479268fe209c616de61530bc2c45602b2ae61d0/projects/question/src/main/java/org/batfish/question/ReachabilityQuestionPlugin.java#L566)):*
> ```Java
>     @JsonProperty(PROP_ICMP_TYPES)
>     public void setIcmpTypes(SortedSet<SubRange> icmpTypes) {
>       _reachabilitySettings.getHeaderSpace().setIcmpTypes(new TreeSet<>(icmpTypes));
> ```

How is this possible? I thought headerSpace is a HeaderSpace, and I though HeaderSpace has no setters.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/1061)*

**Comment by arifogel** [comment]
Review status: 0 of 10 files reviewed at latest revision, 6 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/IBatfish.java, line 193 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1061#-L7kAgsVvaMsTRov2KGU:-L7kWFgM8QJO8Bbmfg8O:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/5479268fe209c616de61530bc2c45602b2ae61d0/projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/IBatfish.java#L193)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

why can't we just pass in `ReachabilitySettings`?
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 2582 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1061#-L7kAnuVmcNgNr3AlZoM:-L7kWPKX1se6neQjmX-Q:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/5479268fe209c616de61530bc2c45602b2ae61d0/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L2582)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

same comment
</blockquote></details>

Done.

---

*[projects/question/src/main/java/org/batfish/question/ReachabilityQuestionPlugin.java, line 536 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1061#-L7kC22_HR3P2n4BnIrs:-L7kWSHg0Jq3YVFWwItD:b97f95o) ([raw file](https://github.com/batfish/batfish/blob/5479268fe209c616de61530bc2c45602b2ae61d0/projects/question/src/main/java/org/batfish/question/ReachabilityQuestionPlugin.java#L536)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

use `ImmutableSortedSet`?
</blockquote></details>

Will address when fixing #1062

---

*[projects/question/src/main/java/org/batfish/question/ReachabilityQuestionPlugin.java, line 541 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1061#-L7kCHW4sKVslDcqBvw8:-L7kWZPC19mhrr2IrT9p:b97f95o) ([raw file](https://github.com/batfish/batfish/blob/5479268fe209c616de61530bc2c45602b2ae61d0/projects/question/src/main/java/org/batfish/question/ReachabilityQuestionPlugin.java#L541)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

use `ImmutableSortedSet`?
</blockquote></details>

Will address when fixing #1062

---

*[projects/question/src/main/java/org/batfish/question/ReachabilityQuestionPlugin.java, line 547 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1061#-L7kCIIr2-7ilcu0CVrH:-L7kWZp2430p-sn9Bpal:b97f95o) ([raw file](https://github.com/batfish/batfish/blob/5479268fe209c616de61530bc2c45602b2ae61d0/projects/question/src/main/java/org/batfish/question/ReachabilityQuestionPlugin.java#L547)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

use `ImmutableSortedSet`?
</blockquote></details>

Will address when fixing #1062

---

*[projects/question/src/main/java/org/batfish/question/ReachabilityQuestionPlugin.java, line 566 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1061#-L7kDTx1s6VWXlK28-Gj:-L7kWa3q9UIsutjKzAle:b97f95o) ([raw file](https://github.com/batfish/batfish/blob/5479268fe209c616de61530bc2c45602b2ae61d0/projects/question/src/main/java/org/batfish/question/ReachabilityQuestionPlugin.java#L566)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

How is this possible? I thought headerSpace is a HeaderSpace, and I though HeaderSpace has no setters.
</blockquote></details>

Will address when fixing #1062

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1061)*

**Comment by anothermattbrown** [comment]
Reviewed 8 of 10 files at r3.
Review status: 8 of 10 files reviewed at latest revision, 6 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/IBatfish.java, line 193 at r2](https://reviewable.io:443/reviews/batfish/batfish/1061#-L7kAgsVvaMsTRov2KGU:-L7kW7qZB3In72mVYuNS:b32wtd) ([raw file](https://github.com/batfish/batfish/blob/5479268fe209c616de61530bc2c45602b2ae61d0/projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/IBatfish.java#L193)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

why can't we just pass in `ReachabilitySettings`?
</blockquote></details>

ok

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 2582 at r2](https://reviewable.io:443/reviews/batfish/batfish/1061#-L7kAnuVmcNgNr3AlZoM:-L7kW_HF6hkSJJ_2fxKT:b32wtd) ([raw file](https://github.com/batfish/batfish/blob/5479268fe209c616de61530bc2c45602b2ae61d0/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L2582)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

same comment
</blockquote></details>

ok

---

*[projects/question/src/main/java/org/batfish/question/ReachabilityQuestionPlugin.java, line 541 at r2](https://reviewable.io:443/reviews/batfish/batfish/1061#-L7kCHW4sKVslDcqBvw8:-L7kWsUt6RhZfPTDBlwS:b-huyy1s) ([raw file](https://github.com/batfish/batfish/blob/5479268fe209c616de61530bc2c45602b2ae61d0/projects/question/src/main/java/org/batfish/question/ReachabilityQuestionPlugin.java#L541)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Will address when fixing #1062
</blockquote></details>

just remove the set copy -- headerspace does already copies to `ImmutableSortedSet`.

---

*[projects/question/src/main/java/org/batfish/question/ReachabilityQuestionPlugin.java, line 547 at r2](https://reviewable.io:443/reviews/batfish/batfish/1061#-L7kCIIr2-7ilcu0CVrH:-L7kWzX1EpY8RkYcbbKk:b-duc46) ([raw file](https://github.com/batfish/batfish/blob/5479268fe209c616de61530bc2c45602b2ae61d0/projects/question/src/main/java/org/batfish/question/ReachabilityQuestionPlugin.java#L547)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Will address when fixing #1062
</blockquote></details>

same comment

---

*[projects/question/src/main/java/org/batfish/question/ReachabilityQuestionPlugin.java, line 566 at r2](https://reviewable.io:443/reviews/batfish/batfish/1061#-L7kDTx1s6VWXlK28-Gj:-L7kX0PHAOW7JvekKCth:b32wtd) ([raw file](https://github.com/batfish/batfish/blob/5479268fe209c616de61530bc2c45602b2ae61d0/projects/question/src/main/java/org/batfish/question/ReachabilityQuestionPlugin.java#L566)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Will address when fixing #1062
</blockquote></details>

ok

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/1061)*

**Comment by anothermattbrown** [comment]
Reviewed 2 of 10 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[projects/question/src/main/java/org/batfish/question/ReachabilityQuestionPlugin.java, line 536 at r2](https://reviewable.io:443/reviews/batfish/batfish/1061#-L7kC22_HR3P2n4BnIrs:-L7kXAKw4sW_srhBaYif:b-7tn2tp) ([raw file](https://github.com/batfish/batfish/blob/5479268fe209c616de61530bc2c45602b2ae61d0/projects/question/src/main/java/org/batfish/question/ReachabilityQuestionPlugin.java#L536)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Will address when fixing #1062
</blockquote></details>

just remove the set copy -- headerspace already copies to `ImmutableSortedSet`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/1061)*

**Comment by arifogel** [comment]
Review status: 9 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[projects/question/src/main/java/org/batfish/question/ReachabilityQuestionPlugin.java, line 536 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1061#-L7kC22_HR3P2n4BnIrs:-L7kgFK90tYlFxiUnokt:b-gqnxpl) ([raw file](https://github.com/batfish/batfish/blob/5479268fe209c616de61530bc2c45602b2ae61d0/projects/question/src/main/java/org/batfish/question/ReachabilityQuestionPlugin.java#L536)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

just remove the set copy -- headerspace already copies to `ImmutableSortedSet`
</blockquote></details>

The new copy will be a NOP if done twice and prevents relying on backend setter behavior.

---

*[projects/question/src/main/java/org/batfish/question/ReachabilityQuestionPlugin.java, line 541 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1061#-L7kCHW4sKVslDcqBvw8:-L7kgLiqCIddYwJR5a7G:b-gqnxpl) ([raw file](https://github.com/batfish/batfish/blob/5479268fe209c616de61530bc2c45602b2ae61d0/projects/question/src/main/java/org/batfish/question/ReachabilityQuestionPlugin.java#L541)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

just remove the set copy -- headerspace does already copies to `ImmutableSortedSet`.
</blockquote></details>

The new copy will be a NOP if done twice and prevents relying on backend setter behavior.

---

*[projects/question/src/main/java/org/batfish/question/ReachabilityQuestionPlugin.java, line 547 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1061#-L7kCIIr2-7ilcu0CVrH:-L7kgMc9D6o6Vs9gEvwW:b-gqnxpl) ([raw file](https://github.com/batfish/batfish/blob/5479268fe209c616de61530bc2c45602b2ae61d0/projects/question/src/main/java/org/batfish/question/ReachabilityQuestionPlugin.java#L547)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

same comment
</blockquote></details>

The new copy will be a NOP if done twice and prevents relying on backend setter behavior.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1061)*

**Comment by anothermattbrown** [comment]
:lgtm:

---

Review status: 9 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1061#-:-L7kk2DK1ruySF2BntxC:bnfp4nl)*

**Comment by anothermattbrown** [comment]
Reviewed 1 of 10 files at r3.
Review status: 9 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1061)*

**Comment by anothermattbrown** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1061)*

**Pull request merged**
