### PR TITLE
Finalize Configuration: erase invalid `VendorStructureId`s

### PR DESCRIPTION
**Pull request by sfraint**
Erase invalid `VendorStructureId`s during `finalizeConfiguration`

Only handles `IpAccessLists` and their `TraceElements` for now, but this should be easily expandable.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 8 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8371)* status: 7 of 11 files reviewed, 10 unresolved discussions (waiting on @dhalperi and @sfraint)

___
*[`projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java` line 1487 at r2](https://reviewable.io/reviews/batfish/batfish/8371#-N5680MU8uS3aXHKPRGj:-N5680MU8uS3aXHKPRGk:b-58so6z) ([raw file](https://github.com/batfish/batfish/blob/b33d33822464c06ca5cb7ed8c68bd85a9ed81c0d/projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java#L1487)):*
> ```Java
>   @Override
>   public void enterS_address_definition(S_address_definitionContext ctx) {
> ```

needed?
___
*[`projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java` line 434 at r2](https://reviewable.io/reviews/batfish/batfish/8371#-N5689654fAK9M3AsSZC:-N5689654fAK9M3AsSZD:b-2keoc8) ([raw file](https://github.com/batfish/batfish/blob/b33d33822464c06ca5cb7ed8c68bd85a9ed81c0d/projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java#L434)):*
> ```Java
>   static void removeInvalidVendorStructureIds(Configuration c, VendorConfiguration vc, Warnings w) {
>     if (vc.getAnswerElement() == null) {
>       return;
> ```

What is the valid context where this is null?
___
*[`projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java` line 449 at r2](https://reviewable.io/reviews/batfish/batfish/8371#-N568P1vDgJBFPLDqceT:-N568P1vDgJBFPLDqceU:b2ui79a) ([raw file](https://github.com/batfish/batfish/blob/b33d33822464c06ca5cb7ed8c68bd85a9ed81c0d/projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java#L449)):*
> ```Java
>                             .setLines(
>                                 e.getValue().getLines().stream()
>                                     .map(vsidEraser::visit)
> ```

make the eraser visit an ACL, simplify this code.



_Code quote:_
```Java
vsidEraser::visit
```
___
*[`projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java` line 476 at r2](https://reviewable.io/reviews/batfish/batfish/8371#-N569jG_9ib473q5eQg0:-N569jG_9ib473q5eQg1:bzhzevy) ([raw file](https://github.com/batfish/batfish/blob/b33d33822464c06ca5cb7ed8c68bd85a9ed81c0d/projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java#L476)):*
> ```Java
>               line -> {
>                 assert line.equals(eraser.visit(line));
>               });
> ```

just use a for loop. forEach adds no value, corrupts stack ,etc.



_Code quote:_
```Java
      acl.getLines()
          .forEach(
              line -> {
                assert line.equals(eraser.visit(line));
              });
```
___
*[`projects/batfish/src/main/java/org/batfish/job/InvalidVendorStructureIdEraser.java` line 47 at r2](https://reviewable.io/reviews/batfish/batfish/8371#-N569y3G4YT2yo8diC4A:-N569y3G4YT2yo8diC4B:b-l2rxiw) ([raw file](https://github.com/batfish/batfish/blob/b33d33822464c06ca5cb7ed8c68bd85a9ed81c0d/projects/batfish/src/main/java/org/batfish/job/InvalidVendorStructureIdEraser.java#L47)):*
> ```Java
>    */
>   @VisibleForTesting
>   boolean isVendorStructureIdValid(VendorStructureId vendorStructureId) {
> ```

for testing, make a static function that includes the `_definedStructures` as an argument. Then the member function is a trivial call and the tests are much simpler (no need to construct Eraser)



_Code quote:_
```Java
boolean isVendorStructureIdValid(VendorStructureId vendorStructureId) 
```
___
*[`projects/batfish/src/main/java/org/batfish/job/InvalidVendorStructureIdEraser.java` line 90 at r2](https://reviewable.io/reviews/batfish/batfish/8371#-N56AHIP-ViVE5DMGEZy:-N56AHIP-ViVE5DMGEZz:b2n9p5r) ([raw file](https://github.com/batfish/batfish/blob/b33d33822464c06ca5cb7ed8c68bd85a9ed81c0d/projects/batfish/src/main/java/org/batfish/job/InvalidVendorStructureIdEraser.java#L90)):*
> ```Java
>                 builder.add(lf.getText());
>               }
>             });
> ```

same for loop comment.



_Code quote:_
```Java
    traceElement
        .getFragments()
        .forEach(
            f -> {
              if (f instanceof TraceElement.TextFragment) {
                builder.add(f.getText());
                return;
              }
              assert f instanceof TraceElement.LinkFragment;
              TraceElement.LinkFragment lf = (TraceElement.LinkFragment) f;
              if (isVendorStructureIdValid(lf.getVendorStructureId())) {
                builder.add(lf);
              } else {
                // Convert invalid link fragment to text fragment, to preserve useful text
                builder.add(lf.getText());
              }
            });
```
___
*[`projects/batfish/src/main/java/org/batfish/job/InvalidVendorStructureIdEraser.java` line 146 at r2](https://reviewable.io/reviews/batfish/batfish/8371#-N56AjQUBbP3YAB21Y1Q:-N56AjQUBbP3YAB21Y1R:bc6t6jy) ([raw file](https://github.com/batfish/batfish/blob/b33d33822464c06ca5cb7ed8c68bd85a9ed81c0d/projects/batfish/src/main/java/org/batfish/job/InvalidVendorStructureIdEraser.java#L146)):*
> ```Java
>   @Override
>   public AclLineMatchExpr visitMatchHeaderSpace(MatchHeaderSpace matchHeaderSpace) {
>     // TODO erase within IpSpaces if/when we add TraceElements to them
> ```

Is this not in IpSpaceMetadata?
___
*[`projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java` line 3016 at r2](https://reviewable.io/reviews/batfish/batfish/8371#-N56BSQU9sn6msBdN9GR:-N56BSQU9sn6msBdN9GS:b-hay66i) ([raw file](https://github.com/batfish/batfish/blob/b33d33822464c06ca5cb7ed8c68bd85a9ed81c0d/projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java#L3016)):*
> ```Java
>     //                    filename,
>     //                    AristaStructureType.IP_ACCESS_LIST_STANDARD_LINE.getDescription(),
>     //                    aclLineStructureName(standardAclName, standard.getName())))));
> ```

revert?



_Code quote:_
```Java
    assertThat(c, hasIpAccessList(standardAclName, hasLines(hasSize(1))));
    // TODO: re-add once VSID is valid
    // VSID is currently invalid, so it is pruned during configuration finalization
    //    AclLine standard = c.getIpAccessLists().get(standardAclName).getLines().get(0);
    //    assertThat(
    //        standard.getVendorStructureId(),
    //        equalTo(
    //            Optional.of(
    //                new VendorStructureId(
    //                    filename,
    //                    AristaStructureType.IP_ACCESS_LIST_STANDARD_LINE.getDescription(),
    //                    aclLineStructureName(standardAclName, standard.getName())))));
```
___
*[`projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java` line 4426 at r2](https://reviewable.io/reviews/batfish/batfish/8371#-N56BUX-9R9Ih6P41kLo:-N56BUX-9R9Ih6P41kLp:b-hay66i) ([raw file](https://github.com/batfish/batfish/blob/b33d33822464c06ca5cb7ed8c68bd85a9ed81c0d/projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java#L4426)):*
> ```Java
>                                 .add("Matched application object ")
>                                 .add("ssh")
>                                 .build(),
> ```

revert?



_Code quote:_
```Java
                            // TODO: fix ssh trace element
                            // ssh VSID is currently invalid, so it's pruned during config
                            // finalization
                            TraceElement.builder()
                                .add("Matched application object ")
                                .add("ssh")
                                .build(),
```
___
*[`projects/batfish/src/test/java/org/batfish/job/InvalidVendorStructureIdEraserTest.java` line 129 at r2](https://reviewable.io/reviews/batfish/batfish/8371#-N56C1EYCkD96Kz2DsWt:-N56C1EYCkD96Kz2DsWu:bapvqxt) ([raw file](https://github.com/batfish/batfish/blob/b33d33822464c06ca5cb7ed8c68bd85a9ed81c0d/projects/batfish/src/test/java/org/batfish/job/InvalidVendorStructureIdEraserTest.java#L129)):*
> ```Java
>       assertEquals(exprValid, eraser.visit(exprValid));
>       // Invalid VSID is removed
>       assertEquals(exprInvalidErased, eraser.visit(exprInvalid));
> ```

I'd probably make a helper that handles all of these. It seems you can have a static defined structures, a static eraser, and pass in a Callable<TE> for the creator, and then have asserts that use the 3 TEs cleanly.

Something like:

```
private static <T implements AclMatchExpr> assertExprHandled(Callable<TE, T> creator) {
   assertThat(erarser.call(creator.call(validTE)), equalTo(creator.call(validTE));
   assertThat(eraser.call(creator.call(invalidTE)), equalTo(creator.call(erasedTE));
}
```

and then you can use that to get rid of approximately 50 lines of redundant code and comments.



_Code quote:_
```Java
      List<AclLineMatchExpr> validInners = ImmutableList.of(new TrueExpr(validTe));
      List<AclLineMatchExpr> invalidInners = ImmutableList.of(new TrueExpr(invalidTe));
      List<AclLineMatchExpr> erasedInners = ImmutableList.of(new TrueExpr(erasedVsid));
      AndMatchExpr exprValid = new AndMatchExpr(validInners, validTe);
      AndMatchExpr exprInvalid = new AndMatchExpr(invalidInners, invalidTe);
      AndMatchExpr exprInvalidErased = new AndMatchExpr(erasedInners, erasedVsid);
      // Valid VSID is left alone
      assertEquals(exprValid, eraser.visit(exprValid));
      // Invalid VSID is removed
      assertEquals(exprInvalidErased, eraser.visit(exprInvalid));
```

**Review by dhalperi — COMMENTED** [review]
> Reviewed 3 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8371)* status: 10 of 11 files reviewed, 11 unresolved discussions (waiting on @dhalperi and @sfraint)

___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/TraceElement.java` line 102 at r2](https://reviewable.io/reviews/batfish/batfish/8371#-N56Cs-jBXbrsaH3G5xC:-N56Cs-k01peIaZrbbZT:bsyk16r) ([raw file](https://github.com/batfish/batfish/blob/b33d33822464c06ca5cb7ed8c68bd85a9ed81c0d/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/TraceElement.java#L102)):*
> ```Java
>     @JsonProperty(PROP_TEXT)
>     @Nonnull
>     public String getText() {
> ```

We tend to put nullity annotations for return values on the return type -- clearer that way especially as there's already a stack of function annotations:

```
public @Nonnull String getText()
```



_Code quote:_
```Java
    @Nonnull
    public String getText() {
```

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8371)* status: 6 of 11 files reviewed, 6 unresolved discussions (waiting on @dhalperi and @sfraint)

___
*[`projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java` line 434 at r2](https://reviewable.io/reviews/batfish/batfish/8371#-N5689654fAK9M3AsSZC:-N5C7aZH7oXxf_6O3zmi:b-cw2clx) ([raw file](https://github.com/batfish/batfish/blob/b33d33822464c06ca5cb7ed8c68bd85a9ed81c0d/projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java#L434)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

What is the valid context where this is null?
</blockquote></details>

this isn't needed, removed
___
*[`projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java` line 449 at r2](https://reviewable.io/reviews/batfish/batfish/8371#-N568P1vDgJBFPLDqceT:-N5CB7yjCidbEumEHjCh:bvnrpcm) ([raw file](https://github.com/batfish/batfish/blob/b33d33822464c06ca5cb7ed8c68bd85a9ed81c0d/projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java#L449)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

make the eraser visit an ACL, simplify this code.
</blockquote></details>

updated
___
*[`projects/batfish/src/main/java/org/batfish/job/InvalidVendorStructureIdEraser.java` line 146 at r2](https://reviewable.io/reviews/batfish/batfish/8371#-N56AjQUBbP3YAB21Y1Q:-N5CD4tb38tLFO0C3eZw:b4bx6vq) ([raw file](https://github.com/batfish/batfish/blob/b33d33822464c06ca5cb7ed8c68bd85a9ed81c0d/projects/batfish/src/main/java/org/batfish/job/InvalidVendorStructureIdEraser.java#L146)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Is this not in IpSpaceMetadata?
</blockquote></details>

That's right, we will need to handle `IpSpaceMetadata`s as well
___
*[`projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java` line 3016 at r2](https://reviewable.io/reviews/batfish/batfish/8371#-N56BSQU9sn6msBdN9GR:-N5CDFXo5EbVwwn-k-XE:b-ykaan5) ([raw file](https://github.com/batfish/batfish/blob/b33d33822464c06ca5cb7ed8c68bd85a9ed81c0d/projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java#L3016)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

revert?
</blockquote></details>

Are you suggesting reverting this and marking the test `@Ignore`? or am I misunderstanding what you're saying here
___
*[`projects/batfish/src/test/java/org/batfish/job/InvalidVendorStructureIdEraserTest.java` line 129 at r2](https://reviewable.io/reviews/batfish/batfish/8371#-N56C1EYCkD96Kz2DsWt:-N5CGkwZ-6ue1XI2pKy7:bvnrpcm) ([raw file](https://github.com/batfish/batfish/blob/b33d33822464c06ca5cb7ed8c68bd85a9ed81c0d/projects/batfish/src/test/java/org/batfish/job/InvalidVendorStructureIdEraserTest.java#L129)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I'd probably make a helper that handles all of these. It seems you can have a static defined structures, a static eraser, and pass in a Callable<TE> for the creator, and then have asserts that use the 3 TEs cleanly.

Something like:

```
private static <T implements AclMatchExpr> assertExprHandled(Callable<TE, T> creator) {
   assertThat(erarser.call(creator.call(validTE)), equalTo(creator.call(validTE));
   assertThat(eraser.call(creator.call(invalidTE)), equalTo(creator.call(erasedTE));
}
```

and then you can use that to get rid of approximately 50 lines of redundant code and comments.
</blockquote></details>

updated

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8371)* status: all files reviewed, 1 unresolved discussion (waiting on @sfraint)

**Pull request merged**
