### PR TITLE
implement juniper insert command

### PR DESCRIPTION
**Pull request by arifogel**
- can move an ordered term before or after another term

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6627)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @arifogel)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6627#-MTNy7IX1x3nzSf3uizn:-MTNy7IX1x3nzSf3uizo:bkpptno) (no related file):*
After batfish/batfish#6625

---

**Comment by dhalperi** [comment]
___
*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/InsertDeleteApplicator.java, line 255 at r3](https://reviewable.io/reviews/batfish/batfish/6627#-MTOHrLt9WG1hYoBoX3O:-MTOHrLt9WG1hYoBoX3P:bx975oc) ([raw file](https://github.com/batfish/batfish/blob/30c4f33e9317858bfd6c61929b8d18ab38725881/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/InsertDeleteApplicator.java#L255)):*
> ```Java
>     lastDstWord = lastWord;
>     StatementTree parent = treeToMove.getParent();
>     parent.deleteSubtree(lastSrcWord);
> ```

Worth confirming that the next to last word in insertsrx is the same as the first word in the new part? And that insertsrc is at least 2 deep?

**Review by dhalperi — COMMENTED** [review]
> Reviewed 7 of 9 files at r1, 4 of 5 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6627)* status: all files reviewed, 2 unresolved discussions (waiting on @arifogel)

___
*[projects/batfish/src/test/resources/org/batfish/main/testconfigs/preprocess-flat-before, line 26 at r3](https://reviewable.io/reviews/batfish/batfish/6627#-MTOHb9W079yNZmnkLZF:-MTOHb9W079yNZmnkLZG:b-oo0eqt) ([raw file](https://github.com/batfish/batfish/blob/30c4f33e9317858bfd6c61929b8d18ab38725881/projects/batfish/src/test/resources/org/batfish/main/testconfigs/preprocess-flat-before#L26)):*
> ```
> set policy-options policy-statement p1 term t4 then accept
> insert policy-options policy-statement p1 term t3 before term t1
> delete policy-options policy-statement p1 term t1 then accept
> ```

Delete everything after t1? Usually terms are deleted whole hog

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6627)* status: 7 of 10 files reviewed, all discussions resolved (waiting on @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/InsertDeleteApplicator.java, line 255 at r3](https://reviewable.io/reviews/batfish/batfish/6627#-MTOHrLt9WG1hYoBoX3O:-MTbHZgpE0VF_EugSJGg:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/30c4f33e9317858bfd6c61929b8d18ab38725881/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/InsertDeleteApplicator.java#L255)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Worth confirming that the next to last word in insertsrx is the same as the first word in the new part? And that insertsrc is at least 2 deep?
</blockquote></details>

done
___
*[projects/batfish/src/test/resources/org/batfish/main/testconfigs/preprocess-flat-before, line 26 at r3](https://reviewable.io/reviews/batfish/batfish/6627#-MTOHb9W079yNZmnkLZF:-MTbQvQsAqQrKpsPo8lO:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/30c4f33e9317858bfd6c61929b8d18ab38725881/projects/batfish/src/test/resources/org/batfish/main/testconfigs/preprocess-flat-before#L26)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Delete everything after t1? Usually terms are deleted whole hog
</blockquote></details>

done

**Review by dhalperi — COMMENTED** [review]
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6627)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
