### PR TITLE
Fortios: add interface class

### PR DESCRIPTION
**Pull request by sfraint**
Add VS model interface class for Fortios.

Not fully fleshed out, but has what we'll need to get started.

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6675)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @corinaminer and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6675#-MUodN8q9mQr4kcumOrA:-MUodN8q9mQr4kcumOrB:b-5bmdtz) (no related file):*
I'd recommend parsing first or together with VS structure PRs. I don't see what meaningful tests you can write otherwise (you have none currently), nor is there any contextual justification of the structure here.

---

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6675)* status: all files reviewed, 2 unresolved discussions (waiting on @corinaminer and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/Interface.java, line 28 at r1](https://reviewable.io/reviews/batfish/batfish/6675#-MUoinq936gni7Db7dub:-MUoinq936gni7Db7duc:b1sxb4z) ([raw file](https://github.com/batfish/batfish/blob/e741a9d674bca6df5c000b35be536b18ac6bb74c/projects/batfish/src/main/java/org/batfish/representation/fortios/Interface.java#L28)):*
> ```Java
>   public static final boolean DEFAULT_STATUS = true;
> 
>   @Nonnull private final String _name;
> ```

nit: latest style is to sort first by visibility (public, package-private, private), then by static over non-static, then fields over methods.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6675)* status: all files reviewed, 3 unresolved discussions (waiting on @corinaminer and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/Interface.java, line 10 at r1](https://reviewable.io/reviews/batfish/batfish/6675#-MUojuem3j9rTf9wQtfQ:-MUojuen5SGsQ_KqsM5h:bfptm87) ([raw file](https://github.com/batfish/batfish/blob/e741a9d674bca6df5c000b35be536b18ac6bb74c/projects/batfish/src/main/java/org/batfish/representation/fortios/Interface.java#L10)):*
> ```Java
> 
> /** FortiOS datamodel component containing interface configuration */
> @ParametersAreNonnullByDefault
> ```

nit: This annotation is redundant because this package contains `package-info.java` that applies this annotation to all classes within.

**Comment by sfraint** [comment]
closing in favor of https://github.com/batfish/batfish/pull/6679

**Pull request closed without merging**
