### PR TITLE
Logs for data-plane generation meta-data and additional test-rigs data

### PR DESCRIPTION
**Pull request by haverma**
Logs to capture info about
1. Number of data-plane iterations and # log entries per node
2. Whether hosts config, topology, bgp, routing tables provided with testrig

---
This change is [Reviewable](https://reviewable.io/reviews/batfish/batfish/801)

### CODE REVIEW

**Comment by dhalperi** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/java/org/batfish/bdp/BdpDataPlanePlugin.java, line 59 at r1](https://reviewable.io:443/reviews/batfish/batfish/801#-L1OPxxAL-4fHhUdOPx_:-L1OPxxAL-4fHhUdOPxa:b-4fnj2x) ([raw file](https://github.com/batfish/batfish/blob/ccb71b90c852e69d492c4371274c7d7d5a56f79e/projects/batfish/src/main/java/org/batfish/bdp/BdpDataPlanePlugin.java#L59)):*
> ```Java
>             .orElse(0.00d);
>     _logger.infof(
>         "Generated data-plane for testrig %s; iterations:%s, avg entries per node:%.2f\n",
> ```

Nice, only one comment: sometimes you are doing `a:%b` other times `a %b` -- aka, space vs colon. Can you choose and document a consistent method? What are the principles by which these messages should be structured so that we can extract the right values later?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/801#-:-L1OPworpL27r9PPd3wq:bnfp4nl)*

**Comment by haverma** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/java/org/batfish/bdp/BdpDataPlanePlugin.java, line 59 at r1](https://reviewable.io:443/reviews/batfish/batfish/801#-L1OPxxAL-4fHhUdOPx_:-L1Tk0-gdr7zKyMfHebl:b-7n7ofp) ([raw file](https://github.com/batfish/batfish/blob/ccb71b90c852e69d492c4371274c7d7d5a56f79e/projects/batfish/src/main/java/org/batfish/bdp/BdpDataPlanePlugin.java#L59)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Nice, only one comment: sometimes you are doing `a:%b` other times `a %b` -- aka, space vs colon. Can you choose and document a consistent method? What are the principles by which these messages should be structured so that we can extract the right values later?
</blockquote></details>

I was keeping all the logs in the format "Operation; metadata", meta data had variable:value pairs. I have changed all the variables in the Operation part as well also to have colons separated values, to be consistent. Though it will not make much difference for the logstash parsing patterns, unless the logs are json objects(which will not need any patterns written for parsing.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/801)*

**Comment by haverma** [comment]
Made formatting consistent with colon separated values

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/801#-:-L1TlCdkudbXsO8cH37S:blifr6r)*

**Comment by dhalperi** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/801#-:-L1U6udEORpfB89WhITo:bnfp4nl)*

**Pull request merged**
