### PR TITLE
IOS: Support route-map match interface for NAT

### PR DESCRIPTION
**Pull request by corinaminer**
Adds support for `match interface IFACE` in route-maps when used for NAT, where this line means "match traffic that will be forwarded out IFACE" (as per last paragraph [here](https://www.cisco.com/c/en/us/support/docs/ip/network-address-translation-nat/13739-nat-routemap.html)). Since we already make transformations on a per-interface basis, this PR modifies transformations to ignore any route-map clause with a `match interface` line that doesn't match the current interface. When a route-map clause has a `match interface` line that does match, the line is converted as a `TRUE` match expr.

Does not support `match interface` in the context of route filtering, where it would mean "match routes whose next hop interface is IFACE" (search for "match interface" [here](https://www.cisco.com/c/en/us/td/docs/security/asa/asa91/configuration/general/asa_91_general_config/route_maps.pdf)).

### CODE REVIEW

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6594)* status: 0 of 12 files reviewed, all discussions resolved (waiting on @anothermattbrown and @dhalperi)

___
*[projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-nat-dynamic-route-maps, line 15 at r1](https://reviewable.io/reviews/batfish/batfish/6594#-MRxbYyHCUh0l973s9gb:-MRxbYyHCUh0l973s9gc:btg5q1e) ([raw file](https://github.com/batfish/batfish/blob/612b9e1dc92e68b0c82f24cfd97646c76ce1c6ba/projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-nat-dynamic-route-maps#L15)):*
> ```
>  match ip address 10
> route-map 11 permit 10
>  match ip address 11
> ```

this route-map was unused

**Review by dhalperi — COMMENTED** [review]
:lgtm:

> Reviewed 7 of 12 files at r1, 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6594#-:-MS-mEw95It4ElgbRfm2:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @anothermattbrown and @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 6815 at r2](https://reviewable.io/reviews/batfish/batfish/6594#-MS-kQ0S-il2A06b2uyM:-MS-kQ0S-il2A06b2uyN:bxlbg8y) ([raw file](https://github.com/batfish/batfish/blob/6da4a02d1b5c12de2792f20ba79ca475c9a40f99/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L6815)):*
> ```Java
>   }
> 
>   public void exitMatch_extcommunity_rm_stanza(Match_extcommunity_rm_stanzaContext ctx) {
> ```

add missing override back?

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6594)* status: 12 of 13 files reviewed, all discussions resolved (waiting on @anothermattbrown and @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 6815 at r2](https://reviewable.io/reviews/batfish/batfish/6594#-MS-kQ0S-il2A06b2uyM:-MS-nP3Q8v4yViozNMS7:b-7sjn7t) ([raw file](https://github.com/batfish/batfish/blob/6da4a02d1b5c12de2792f20ba79ca475c9a40f99/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L6815)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

add missing override back?
</blockquote></details>

oops, lost in merge conflict resolution

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6594)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown)

**Pull request merged**
