### PR TITLE
IOS-XR handle undefined aggregate-address route-policy

### PR DESCRIPTION
**Pull request by arifogel**

### CODE REVIEW

**Review by corinaminer — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7079)* status: all files reviewed, 2 unresolved discussions (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConversions.java, line 331 at r2](https://reviewable.io/reviews/batfish/batfish/7079#-McW9z-C8iNhFPCSmmgO:-McW9z-C8iNhFPCSmmgP:bkqrwh0) ([raw file](https://github.com/batfish/batfish/blob/80ed5c6798327e0d0da659f64a41c3f633ed3a85/projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConversions.java#L331)):*
> ```Java
>         Optional.ofNullable(vsAggregate.getRoutePolicy())
>             .filter(c.getRoutingPolicies()::containsKey)
>             .orElse(null);
> ```

did you check behavior on the device? if not, at least include a todo to check real behavior when route-policy is undefined here
___
*[tests/parsing-tests/unit-tests-vimodel.ref, line 0 at r2](https://reviewable.io/reviews/batfish/batfish/7079#-McWAjqc5hiraGt1YTEJ:-McWAjqc5hiraGt1YTEK:bv6ivtz) ([raw file](https://github.com/batfish/batfish/blob/80ed5c6798327e0d0da659f64a41c3f633ed3a85/tests/parsing-tests/unit-tests-vimodel.ref#L0)):*
ugh, our ref tests really have undefined route-policies? Do you know if this is expected, and/or can you check if the config has any indication that route-policy `AGGREGATE_POLICY` is intentionally undefined?

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7079)* status: all files reviewed, 2 unresolved discussions (waiting on @corinaminer and @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConversions.java, line 331 at r2](https://reviewable.io/reviews/batfish/batfish/7079#-McW9z-C8iNhFPCSmmgO:-McWKLck-No74Y5LfG2E:b741v2n) ([raw file](https://github.com/batfish/batfish/blob/80ed5c6798327e0d0da659f64a41c3f633ed3a85/projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConversions.java#L331)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

did you check behavior on the device? if not, at least include a todo to check real behavior when route-policy is undefined here
</blockquote></details>

There is no behavior on the device. You cannot have undefined references. This is best effort. User will be warned.
@dhalperi and I are debating whether this should instead throw `WillNotCommitException`.
___
*[tests/parsing-tests/unit-tests-vimodel.ref, line  at r2](https://reviewable.io/reviews/batfish/batfish/7079#-McWAjqc5hiraGt1YTEJ:-McWKY6t4igAUSohuOm-:b-yidtx2) ([raw file](https://github.com/batfish/batfish/blob/80ed5c6798327e0d0da659f64a41c3f633ed3a85/tests/parsing-tests/unit-tests-vimodel.ref#L)):*
> ugh, our ref tests really have undefined route-policies?

All over the place.
These tests are mostly for grammar coverage. AFAIR none of these files are real in any way. This is not worth our time.

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7079)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConversions.java, line 331 at r2](https://reviewable.io/reviews/batfish/batfish/7079#-McW9z-C8iNhFPCSmmgO:-McWOFLzAjtSXzABXNo9:b8mmpkg) ([raw file](https://github.com/batfish/batfish/blob/80ed5c6798327e0d0da659f64a41c3f633ed3a85/projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConversions.java#L331)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

There is no behavior on the device. You cannot have undefined references. This is best effort. User will be warned.
@dhalperi and I are debating whether this should instead throw `WillNotCommitException`.
</blockquote></details>

Ack. resolving, you can merge when you and dan come to a consensus

**Review by corinaminer — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7079)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Review by corinaminer — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7079)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7079)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConversions.java, line 331 at r2](https://reviewable.io/reviews/batfish/batfish/7079#-McW9z-C8iNhFPCSmmgO:-Mcjl8vFEneduI_jKS8r:br35pnq) ([raw file](https://github.com/batfish/batfish/blob/80ed5c6798327e0d0da659f64a41c3f633ed3a85/projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConversions.java#L331)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Ack. resolving, you can merge when you and dan come to a consensus
</blockquote></details>

Added a warning for if the route-policy is undefined; other than that no one seems to have a strong opinion on how we should handle this, so leaving as-is.

**Pull request merged**
