### PR TITLE
Setting Static route preference for Juniper

### PR DESCRIPTION
**Pull request by haverma**
- preference is treated as admin distance
 - corrected conversion of Juniper static routes where we were storing metric as admin cost

### CODE REVIEW

**Comment by arifogel** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java, line 1625 at r1](https://reviewable.io/reviews/batfish/batfish/1482#-LDEbs_21FYq7ekI2ohc:-LDEbs_21FYq7ekI2ohd:bm9n5ag) ([raw file](https://github.com/batfish/batfish/blob/27f30d7f8923c53a44f2052e2ce50cd04a256725/projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java#L1625)):*
> ```Java
> 
>   @Test
>   public void testStaticRoutePreference() throws IOException {
> ```

Can you add another test for a static route that does not override distance?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1482)*

**Comment by haverma** [comment]
Review status: 1 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java, line 1625 at r1](https://reviewable.io/reviews/batfish/batfish/1482#-LDEbs_21FYq7ekI2ohc:-LDF5s70CLY6l34-wIT9:beekpci) ([raw file](https://github.com/batfish/batfish/blob/27f30d7f8923c53a44f2052e2ce50cd04a256725/projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java#L1625)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Can you add another test for a static route that does not override distance?
</blockquote></details>

Added test and initializing the default value of 5 for static route admin distance(https://www.juniper.net/documentation/en_US/junos/topics/reference/general/routing-protocols-default-route-preference-values.html)

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1482)*

**Comment by arifogel** [comment]
Reviewed 1 of 2 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java, line 1625 at r1](https://reviewable.io/reviews/batfish/batfish/1482#-LDEbs_21FYq7ekI2ohc:-LDIGFYp0wCKBTFNMR1h:b2ujmhx) ([raw file](https://github.com/batfish/batfish/blob/27f30d7f8923c53a44f2052e2ce50cd04a256725/projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java#L1625)):*
<details><summary><i>Previously, haverma (Harsh Verma) wrote…</i></summary><blockquote>

Added test and initializing the default value of 5 for static route admin distance(https://www.juniper.net/documentation/en_US/junos/topics/reference/general/routing-protocols-default-route-preference-values.html)
</blockquote></details>

Can you put that URL in the javadoc for the DEFAULT_ADMIN_DISTANCE?

---

*[projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java, line 1628 at r3](https://reviewable.io/reviews/batfish/batfish/1482#-LDIGTeABK_a1qGPwd0s:-LDIGTeABK_a1qGPwd0t:b-qqc4a) ([raw file](https://github.com/batfish/batfish/blob/b18c0f6b9f1396df0eaa7d16ac6f16ab3eb1e7a9/projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java#L1628)):*
> ```Java
>     Configuration c = parseConfig("ospf-router-id");
> 
>     assertThat(c, hasVrf("default", hasOspfProcess(hasRouterId(equalTo(new Ip("1.0.0.0"))))));
> ```

Why is this here?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1482)*

**Comment by haverma** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/StaticRoute.java, line 14 at r4](https://reviewable.io/reviews/batfish/batfish/1482#-LDIVDUp9AMSseWnz8id:-LDIX3fo39uEA3RdSPL0:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/2f3564ea45eb093c6005e721d269a513de7e4d7b/projects/batfish/src/main/java/org/batfish/representation/juniper/StaticRoute.java#L14)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Sorry to nitpick, but can you try to keep this URL on one line so it is clickable? I hope autoformat didn't do that.
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1482)*

**Comment by arifogel** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1482#-:-LDJ4Yle0BPvFJsi-FbD:bnfp4nl)*

**Pull request merged**
