### PR TITLE
InterfaceNameComparator: implement and test

### PR DESCRIPTION
**Pull request by dhalperi**

### CODE REVIEW

**Review by ratulm — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7204#-:-MffstdC5IofZFZxF2ir:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown)

**Review by ratulm — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7204)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown)

**Review by ratulm — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7204)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown)

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7204)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dhalperi)

**Pull request merged**
