### PR TITLE
Fix various main RIB resolvability backup route bug

### PR DESCRIPTION
**Pull request by arifogel**
- fix nonrecursive static route changes not being processed for side effects
- fix crash on demotion of nhip route to backup

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7238)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @arifogel and @corinaminer)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7238#-Mgwwk4D1_92S1qS2ZL4:-Mgwwk4D1_92S1qS2ZL5:b-wlfa79) (no related file):*
need to revert some static route stuff

---

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7238)* status: all files reviewed, 3 unresolved discussions (waiting on @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/rib/Rib.java, line 213 at r2](https://reviewable.io/reviews/batfish/batfish/7238#-MgxJsqP0h29PHTcigw-:-MgxrC1e8u29MqaLOC4F:b-8rux7m) ([raw file](https://github.com/batfish/batfish/blob/c0bb718728aaf939c412f795772cb09390496f36/projects/batfish/src/main/java/org/batfish/dataplane/rib/Rib.java#L213)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

If `affectedRoute` is a backup route (regardless of whether it's recursive) can we return immediately here? All routes affected by its prefix must already be in `remainingAffectedRoutes` because the merge that made `affectedRoute` a backup route would have added them
</blockquote></details>

Yes, actually. Moved.
___
*[projects/batfish/src/main/java/org/batfish/dataplane/rib/Rib.java, line 222 at r2](https://reviewable.io/reviews/batfish/batfish/7238#-MgxJb4P6_2Qwn0G-x-2:-MgxqvBl7fPMqnJa59Vz:b-7mpk17) ([raw file](https://github.com/batfish/batfish/blob/c0bb718728aaf939c412f795772cb09390496f36/projects/batfish/src/main/java/org/batfish/dataplane/rib/Rib.java#L222)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

did we decide that `_backupRoutes` contains all routes including active routes? If so, the `_backupRoutes.containsEntry(...)` check will always be true and we can determine whether it's a backup route just based on whether it's in `extractRoutes`
</blockquote></details>

That's not true for non-recursive routes, which will not be in `_routesByNextHopIp`.
___
*[projects/batfish/src/test/java/org/batfish/dataplane/rib/RibTest.java, line 673 at r2](https://reviewable.io/reviews/batfish/batfish/7238#-MgxIEoP8l9HvhwVbpCs:-Mgxv7YIAqaYd8l7Whc1:bbu1zbn) ([raw file](https://github.com/batfish/batfish/blob/c0bb718728aaf939c412f795772cb09390496f36/projects/batfish/src/test/java/org/batfish/dataplane/rib/RibTest.java#L673)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Is this test's purpose to ensure that the deactivation cascade works when it goes through a nonrecursive route? Just want to ascertain that you expect it to pass in master as well as this branch (because it does pass in master)
</blockquote></details>

Right. The behavior tested here was not working somewhere in the middle of my implementation. I added the test to make sure the final version didn't leave it broken.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7238)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/rib/Rib.java, line 222 at r2](https://reviewable.io/reviews/batfish/batfish/7238#-MgxJb4P6_2Qwn0G-x-2:-MgxxNGr6A_J36HPu__F:b2pf30o) ([raw file](https://github.com/batfish/batfish/blob/c0bb718728aaf939c412f795772cb09390496f36/projects/batfish/src/main/java/org/batfish/dataplane/rib/Rib.java#L222)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

That's not true for non-recursive routes, which will not be in `_routesByNextHopIp`.
</blockquote></details>

FYI for our sanity we should make `_backupRoute` not contain active routes at some point, but that may have some unexpected side effects.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7238)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @corinaminer)

___
*[projects/batfish/src/test/java/org/batfish/dataplane/rib/RibTest.java, line 673 at r2](https://reviewable.io/reviews/batfish/batfish/7238#-MgxIEoP8l9HvhwVbpCs:-MgxxrlH6SeVNo4SX01K:bk3hyfw) ([raw file](https://github.com/batfish/batfish/blob/c0bb718728aaf939c412f795772cb09390496f36/projects/batfish/src/test/java/org/batfish/dataplane/rib/RibTest.java#L673)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Right. The behavior tested here was not working somewhere in the middle of my implementation. I added the test to make sure the final version didn't leave it broken.
</blockquote></details>

By the way, I originally did more in this test. But then I realized I couldn't make it pass unless I added activation/deactivation logic for nonrecursive routes. That is currently handled in the next iteration by `StaticRouteHelper`. Implementing it here would require another resolution trie. It would not have fixed any bug, so I skipped it.

**Review by corinaminer — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7238)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/rib/Rib.java, line 222 at r2](https://reviewable.io/reviews/batfish/batfish/7238#-MgxJb4P6_2Qwn0G-x-2:-Mh-X0Sf82bdXLkpCMcP:b2nhysk) ([raw file](https://github.com/batfish/batfish/blob/c0bb718728aaf939c412f795772cb09390496f36/projects/batfish/src/main/java/org/batfish/dataplane/rib/Rib.java#L222)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

FYI for our sanity we should make `_backupRoute` not contain active routes at some point, but that may have some unexpected side effects.
</blockquote></details>

ack
___
*[projects/batfish/src/main/java/org/batfish/dataplane/rib/Rib.java, line 232 at r3](https://reviewable.io/reviews/batfish/batfish/7238#-Mh-XOklCKorLeTcHgYv:-Mh-XOklCKorLeTcHgYw:b-hnhpwd) ([raw file](https://github.com/batfish/batfish/blob/38cf8b5ecd0908a132cc3e79d3eba288ffd3b35f/projects/batfish/src/main/java/org/batfish/dataplane/rib/Rib.java#L232)):*
> ```Java
>             .get(affectedRoute.getRoute().getNextHopIp())
>             .contains(affectedRoute)) {
>           // The affected route was explicitly removed by a client merge or remove call. Such a
> ```

nit: has to be by a remove call, right? nonblocking

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7238)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/rib/Rib.java, line 232 at r3](https://reviewable.io/reviews/batfish/batfish/7238#-Mh-XOklCKorLeTcHgYv:-Mh04S0e2TTQEPmOkNMe:b-qwqyyk) ([raw file](https://github.com/batfish/batfish/blob/38cf8b5ecd0908a132cc3e79d3eba288ffd3b35f/projects/batfish/src/main/java/org/batfish/dataplane/rib/Rib.java#L232)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

nit: has to be by a remove call, right? nonblocking
</blockquote></details>

Right, this doesn't apply to explicit merges. Think I got confused about backups or something.

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7238)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Pull request merged**
