### PR TITLE
A10: Virtual Server question

### PR DESCRIPTION
**Pull request by ratulm**

### CODE REVIEW

**Review by sfraint — COMMENTED** [review]
> Reviewed 6 of 9 files at r1, 3 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7775)* status: 9 of 11 files reviewed, 2 unresolved discussions (waiting on @ratulm and @sfraint)

___
*[projects/question/src/main/java/org/batfish/question/a10/A10VirtualServerConfigurationAnswerer.java, line 122 at r2](https://reviewable.io/reviews/batfish/batfish/7775#-MqabjlT76uEQ9leBoSI:-MqabjlT76uEQ9leBoSJ:b-lkg8q9) ([raw file](https://github.com/batfish/batfish/blob/d7935ad0bcb5b5d61dc2ff7685ce204859bff749/projects/question/src/main/java/org/batfish/question/a10/A10VirtualServerConfigurationAnswerer.java#L122)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
>        .add(new ColumnMetadata(COL_SERVERS, Schema.set(Schema.STRING), "Servers", false, true))
> ...
>                               String.format(
>                                   "%s:%s:%s",
>                                   member.getName(),
>                                   member.getPort(),
>                                   getServerTarget(member.getName(), a10Vc)))
> ```
</details>

Have a couple questions here:
* Why is `servers` a flattened String rather than separate columns or a smarter object, with fields for its various values the user cares about?
* Why is it encoded like this when flattened to a string? would it make more sense to put `ip` before `port`?
___
*[questions/experimental/a10VirtualServerConfiguration.json, line 8 at r2](https://reviewable.io/reviews/batfish/batfish/7775#-MqadOaL54EaJ0q1cawi:-MqadOaL54EaJ0q1cawj:bb3cxlz) ([raw file](https://github.com/batfish/batfish/blob/d7935ad0bcb5b5d61dc2ff7685ce204859bff749/questions/experimental/a10VirtualServerConfiguration.json#L8)):*
> ```
> Lists all the Virtual Server to service group to server mappings in A10 configurations.
> ```
should we use the device-specific wording / formatting here? lowercase and hyphenated, e.g. `virtual-server`, `service-group`

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7775)* status: 9 of 11 files reviewed, 2 unresolved discussions (waiting on @sfraint)

___
*[projects/question/src/main/java/org/batfish/question/a10/A10VirtualServerConfigurationAnswerer.java, line 122 at r2](https://reviewable.io/reviews/batfish/batfish/7775#-MqabjlT76uEQ9leBoSI:-MqaeDJG7i0UalMtGJQI:b-tt9m1y) ([raw file](https://github.com/batfish/batfish/blob/d7935ad0bcb5b5d61dc2ff7685ce204859bff749/projects/question/src/main/java/org/batfish/question/a10/A10VirtualServerConfigurationAnswerer.java#L122)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
>        .add(new ColumnMetadata(COL_SERVERS, Schema.set(Schema.STRING), "Servers", false, true))
> ...
>                               String.format(
>                                   "%s:%s:%s",
>                                   member.getName(),
>                                   member.getPort(),
>                                   getServerTarget(member.getName(), a10Vc)))
> ```
Have a couple questions here:
* Why is `servers` a flattened String rather than separate columns or a smarter object, with fields for its various values the user cares about?
* Why is it encoded like this when flattened to a string? would it make more sense to put `ip` before `port`?

</blockquote></details>

1. I was trying to stay within the confines of our Schema, and mirroring what was done for f5Vip. Separate columns won't work because the number is variable. What smarter encoding do you have in mind? 
2. I picked this ordering based on how one might walk from a VS -> SG -> Servername, port (part of SG definition) and then Ip (part of Server definition). But I don't have a strong opinion here, and can switch it around. 
___
*[questions/experimental/a10VirtualServerConfiguration.json, line 8 at r2](https://reviewable.io/reviews/batfish/batfish/7775#-MqadOaL54EaJ0q1cawi:-MqafFo3ALnEGOhS_I0T:bme6bh1) ([raw file](https://github.com/batfish/batfish/blob/d7935ad0bcb5b5d61dc2ff7685ce204859bff749/questions/experimental/a10VirtualServerConfiguration.json#L8)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
> Lists all the Virtual Server to service group to server mappings in A10 configurations.
> ```
should we use the device-specific wording / formatting here? lowercase and hyphenated, e.g. `virtual-server`, `service-group`
</blockquote></details>

Sure. Changing, while I wait on your respond to the bigger question about encoding.

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7775)* status: 7 of 11 files reviewed, 2 unresolved discussions (waiting on @sfraint)

___
*[projects/question/src/main/java/org/batfish/question/a10/A10VirtualServerConfigurationAnswerer.java, line 122 at r2](https://reviewable.io/reviews/batfish/batfish/7775#-MqabjlT76uEQ9leBoSI:-Mqai7fL38ziunGaPCmx:b8nxsdj) ([raw file](https://github.com/batfish/batfish/blob/d7935ad0bcb5b5d61dc2ff7685ce204859bff749/projects/question/src/main/java/org/batfish/question/a10/A10VirtualServerConfigurationAnswerer.java#L122)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

1. I was trying to stay within the confines of our Schema, and mirroring what was done for f5Vip. Separate columns won't work because the number is variable. What smarter encoding do you have in mind? 
2. I picked this ordering based on how one might walk from a VS -> SG -> Servername, port (part of SG definition) and then Ip (part of Server definition). But I don't have a strong opinion here, and can switch it around. 
</blockquote></details>

PS: Another schema option for servers list is `List<List<String>>`, which is a more usable but renders worse on notebooks.

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7775)* status: 7 of 11 files reviewed, 2 unresolved discussions (waiting on @ratulm and @sfraint)

___
*[projects/question/src/main/java/org/batfish/question/a10/A10VirtualServerConfigurationAnswerer.java, line 122 at r2](https://reviewable.io/reviews/batfish/batfish/7775#-MqabjlT76uEQ9leBoSI:-MqahYNh1uLHVqo60N7B:b-x1d4sa) ([raw file](https://github.com/batfish/batfish/blob/d7935ad0bcb5b5d61dc2ff7685ce204859bff749/projects/question/src/main/java/org/batfish/question/a10/A10VirtualServerConfigurationAnswerer.java#L122)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

1. I was trying to stay within the confines of our Schema, and mirroring what was done for f5Vip. Separate columns won't work because the number is variable. What smarter encoding do you have in mind? 
2. I picked this ordering based on how one might walk from a VS -> SG -> Servername, port (part of SG definition) and then Ip (part of Server definition). But I don't have a strong opinion here, and can switch it around. 
</blockquote></details>

Ack on separate columns.

We should just add a new schema for a (`A10`)`server` then (and we probably should have done this for F5 as well)

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7775)* status: 7 of 11 files reviewed, 2 unresolved discussions (waiting on @ratulm and @sfraint)

___
*[projects/question/src/main/java/org/batfish/question/a10/A10VirtualServerConfigurationAnswerer.java, line 122 at r2](https://reviewable.io/reviews/batfish/batfish/7775#-MqabjlT76uEQ9leBoSI:-MqalwGU9wfP0YSxHLdi:b-mdtzhk) ([raw file](https://github.com/batfish/batfish/blob/d7935ad0bcb5b5d61dc2ff7685ce204859bff749/projects/question/src/main/java/org/batfish/question/a10/A10VirtualServerConfigurationAnswerer.java#L122)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

Ack on separate columns.

We should just add a new schema for a (`A10`)`server` then (and we probably should have done this for F5 as well)
</blockquote></details>

Like we chatted about offline, List<List<String>> should work for now, we can rev later if needed

**Review by sfraint — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7775)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ratulm)

**Pull request merged**
