### PR TITLE
InferPoliciesQuestionPlugin: add display hints to generated questions

### PR DESCRIPTION
**Pull request by dhalperi**
Needed to do a bit of refactoring to make it fit:

* IRoleConsistencyQuestion from interface to abstract Question so it can be embedded.
* Add the ability to configure display hints in a JsonPath question.
* Add some helpers.

### CODE REVIEW

**Comment by dhalperi** [comment]
*[a discussion](https://reviewable.io:443/reviews/batfish/batfish/1079#-L84MmACra9_0eAihEB-:-L84MmACra9_0eAihEB0:b-chvyo8) (no related file):*
Blocked by #1077  and #1078 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/1079)*

**Comment by dhalperi** [comment]
Still pending tests, but for playing around with should you desire.

**Comment by ratulm** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/1079#-:-L84lHvNwLvns2s8R8YP:bnfp4nl)*

**Comment by ratulm** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/1079#-:-L84rVFytP4KcoNpGEKV:bnfp4nl)*

**Comment by dhalperi** [comment]
Reviewed 2 of 3 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/1079)*

**Comment by millstein** [comment]
Looks good, thanks!

**Pull request merged**
