### PR TITLE
another exception can show when comparing tests

### PR DESCRIPTION
**Pull request by ratulm**
This change is [Reviewable](https://reviewable.io/reviews/batfish/batfish/810)

### CODE REVIEW

**Comment by dhalperi** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish-client/src/main/java/org/batfish/client/Client.java, line 3030 at r1](https://reviewable.io:443/reviews/batfish/batfish/810#-L1TthLs3i6CDhm2-IYV:-L1TthLs3i6CDhm2-IYW:b-20r7ys) ([raw file](https://github.com/batfish/batfish/blob/2f2a8e67771f4ba3fef0d852fe584a6252db7235/projects/batfish-client/src/main/java/org/batfish/client/Client.java#L3030)):*
> ```Java
>           Answer testAnswer = mapper.readValue(testOutput, Answer.class);
>           testAnswerString = mapper.writeValueAsString(testAnswer);
>         } catch (JsonParseException | UnrecognizedPropertyException e) {
> ```

Do you need a similar change here?

---

*[projects/batfish-client/src/main/java/org/batfish/client/Client.java, line 3047 at r1](https://reviewable.io:443/reviews/batfish/batfish/810#-L1TtNmx5a92ic5INt0k:-L1TtNmyxan3WtQR546P:b-kg3yzj) ([raw file](https://github.com/batfish/batfish/blob/2f2a8e67771f4ba3fef0d852fe584a6252db7235/projects/batfish-client/src/main/java/org/batfish/client/Client.java#L3047)):*
> ```Java
>             referenceAnswer = mapper.readValue(referenceOutput, Answer.class);
>             referenceAnswerString = mapper.writeValueAsString(referenceAnswer);
>           } catch (JsonParseException | MismatchedInputException e) {
> ```

Is there a reason we don't just use `JsonProcessingException` which is the parent of all these?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/810)*

**Comment by ratulm** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish-client/src/main/java/org/batfish/client/Client.java, line 3030 at r1](https://reviewable.io:443/reviews/batfish/batfish/810#-L1TthLs3i6CDhm2-IYV:-L1UGm6x-yPyD2xIK-G-:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/2f2a8e67771f4ba3fef0d852fe584a6252db7235/projects/batfish-client/src/main/java/org/batfish/client/Client.java#L3030)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Do you need a similar change here?
</blockquote></details>

Done.

---

*[projects/batfish-client/src/main/java/org/batfish/client/Client.java, line 3047 at r1](https://reviewable.io:443/reviews/batfish/batfish/810#-L1TtNmx5a92ic5INt0k:-L1UGmgseYQbdKTls3Lc:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/2f2a8e67771f4ba3fef0d852fe584a6252db7235/projects/batfish-client/src/main/java/org/batfish/client/Client.java#L3047)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Is there a reason we don't just use `JsonProcessingException` which is the parent of all these?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/810)*

**Comment by dhalperi** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/810)*

**Comment by dhalperi** [comment]
:lgtm: when green

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/810#-:-L1UJ4oMxq4V2fQBK3Zk:brr0024)*

**Pull request merged**
