### PR TITLE
Bdd improvements

### PR DESCRIPTION
**Pull request by rabeckett**
This is a collection of refactorings and improvements to the BDD code. Some of the main changes are:

* Created a BDDNetFactory object that manages things like variable ordering and translation back from a BDD to a headerspace, set of route advertisements, etc.
* BDDPacket and BDDRoute objects are now managed by BDDNetFactory and use the same underlying BDDFactory, so they can now be mixed freely (e.g., can apply an ACL to the IP addresses covered by a prefix).
* Adds a BDDNetConfig object that can be used to configure what fields of headers/advertisements are modeled or not modeled by the BDD.
* Separates out commonly used BDD helper functions into BDDUtils.java
* Fixes a bug where BDD transfer function results were accidentally cached across different test rigs.
* Various performance improvements by tweaking the variable ordering and setting the initial BDD node table and cache sizes based on the network size.
* Added unit tests in BDDNetFactoryTest

### CODE REVIEW

**Comment by anothermattbrown** [comment]
Reviewed 9 of 21 files at r1.
Review status: 8 of 17 files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish/src/main/java/org/batfish/symbolic/bdd/BDDNetConfig.java, line 3 at r1](https://reviewable.io/reviews/batfish/batfish/1455#-LD7y9gL9cMlglq-tpoY:-LD7y9gL9cMlglq-tpoZ:b-p1bd47) ([raw file](https://github.com/batfish/batfish/blob/bcd2aedfd993d70ff0adfc3f9e795b58df94048c/projects/batfish/src/main/java/org/batfish/symbolic/bdd/BDDNetConfig.java#L3)):*
> ```Java
> package org.batfish.symbolic.bdd;
> 
> public class BDDNetConfig {
> ```

Javadoc please

---

*[projects/batfish/src/main/java/org/batfish/symbolic/bdd/BDDNetFactory.java, line 341 at r1](https://reviewable.io/reviews/batfish/batfish/1455#-LD7yhc1DD3ClxMs13pX:-LD7yhc1DD3ClxMs13pY:bpu7xb6) ([raw file](https://github.com/batfish/batfish/blob/bcd2aedfd993d70ff0adfc3f9e795b58df94048c/projects/batfish/src/main/java/org/batfish/symbolic/bdd/BDDNetFactory.java#L341)):*
> ```Java
>   }
> 
>   public String dot(BDD bdd) {
> ```

should this live in `BDDUtils`? Perhaps its own class.

---

*[projects/batfish/src/main/java/org/batfish/symbolic/bdd/BDDNetFactory.java, line 384 at r1](https://reviewable.io/reviews/batfish/batfish/1455#-LD7zHYTBVxT0EB5f38-:-LD7zHYTBVxT0EB5f380:b-69zy8b) ([raw file](https://github.com/batfish/batfish/blob/bcd2aedfd993d70ff0adfc3f9e795b58df94048c/projects/batfish/src/main/java/org/batfish/symbolic/bdd/BDDNetFactory.java#L384)):*
> ```Java
> 
>   /*
>    * Helper class for translating back from a BDD to a human-understandable
> ```

This just gets one example/model, right?

---

*[projects/batfish/src/main/java/org/batfish/symbolic/bdd/BDDNetFactory.java, line 389 at r1](https://reviewable.io/reviews/batfish/batfish/1455#-LD7z85C0mHFuT9TFug2:-LD7z85C0mHFuT9TFug3:bs0sk1j) ([raw file](https://github.com/batfish/batfish/blob/bcd2aedfd993d70ff0adfc3f9e795b58df94048c/projects/batfish/src/main/java/org/batfish/symbolic/bdd/BDDNetFactory.java#L389)):*
> ```Java
>    * field in BDDRoute and/or BDDPacket.
>    */
>   public class SatAssigment {
> ```

Move to a its own file?

---

*[projects/batfish/src/main/java/org/batfish/symbolic/bdd/BDDNetFactory.java, line 576 at r1](https://reviewable.io/reviews/batfish/batfish/1455#-LD8-lj990o6aLOLR9uQ:-LD8-ZVsC-z8R4b-juPf:b-p1bd47) ([raw file](https://github.com/batfish/batfish/blob/bcd2aedfd993d70ff0adfc3f9e795b58df94048c/projects/batfish/src/main/java/org/batfish/symbolic/bdd/BDDNetFactory.java#L576)):*
> ```Java
>   }
> 
>   public List<SatAssigment> allSat(BDD x) {
> ```

Javadoc please

---

*[projects/batfish/src/main/java/org/batfish/symbolic/bdd/BDDNetFactory.java, line 587 at r1](https://reviewable.io/reviews/batfish/batfish/1455#-LD8-nFbEeVWwcV6mL9Y:-LD8-VqY0DjQ0GwTrt1D:b-p1bd47) ([raw file](https://github.com/batfish/batfish/blob/bcd2aedfd993d70ff0adfc3f9e795b58df94048c/projects/batfish/src/main/java/org/batfish/symbolic/bdd/BDDNetFactory.java#L587)):*
> ```Java
>   }
> 
>   public SatAssigment satOne(BDD x) {
> ```

Javadoc please

---

*[projects/batfish/src/main/java/org/batfish/symbolic/bdd/BDDNetFactory.java, line 872 at r1](https://reviewable.io/reviews/batfish/batfish/1455#-LD80bpj0Fgx6WuXbB09:-LD80bpj0Fgx6WuXbB0A:b-cgws6f) ([raw file](https://github.com/batfish/batfish/blob/bcd2aedfd993d70ff0adfc3f9e795b58df94048c/projects/batfish/src/main/java/org/batfish/symbolic/bdd/BDDNetFactory.java#L872)):*
> ```Java
> 
>     /*
>      * Create a BDDRecord from another. Because BDDs are immutable,
> ```

* Naming: `BDDRecord` vs `BDDRoute`.
* BDDs are not immutable, and are in fact mutated in this class via the destructive `*With` methods. Can we move away from those?

---

*[projects/batfish/src/main/java/org/batfish/symbolic/bdd/BDDNetFactory.java, line 1206 at r1](https://reviewable.io/reviews/batfish/batfish/1455#-LD81i-pD9I2ulhp4PH1:-LD81i-pD9I2ulhp4PH2:b-438blj) ([raw file](https://github.com/batfish/batfish/blob/bcd2aedfd993d70ff0adfc3f9e795b58df94048c/projects/batfish/src/main/java/org/batfish/symbolic/bdd/BDDNetFactory.java#L1206)):*
> ```Java
>    *
>    */
>   public class BDDPacket {
> ```

Can this be moved to its own file?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1455)*

**Comment by anothermattbrown** [comment]
Reviewed 10 of 21 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[projects/batfish/src/main/java/org/batfish/symbolic/bdd/BDDNetwork.java, line 103 at r1](https://reviewable.io/reviews/batfish/batfish/1455#-LD9FbCx3eKq79gZVRdu:-LD9FbCx3eKq79gZVRdv:b-8jw9tl) ([raw file](https://github.com/batfish/batfish/blob/bcd2aedfd993d70ff0adfc3f9e795b58df94048c/projects/batfish/src/main/java/org/batfish/symbolic/bdd/BDDNetwork.java#L103)):*
> ```Java
>    * representation of the import and export policies on this interface.
>    */
>   private void computeInterfacePolicies() {
> ```

Can you add tests for this method?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1455)*

**Comment by rabeckett** [comment]
*[projects/batfish/src/main/java/org/batfish/symbolic/bdd/BDDNetConfig.java, line 3 at r1](https://reviewable.io/reviews/batfish/batfish/1455#-LD7y9gL9cMlglq-tpoY:-LD9hPKX9KMNHo2hxr4d:brtixyw) ([raw file](https://github.com/batfish/batfish/blob/bcd2aedfd993d70ff0adfc3f9e795b58df94048c/projects/batfish/src/main/java/org/batfish/symbolic/bdd/BDDNetConfig.java#L3)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

Javadoc please
</blockquote></details>

Sure. BTW, do you know how I make changes and link them to this thread. Do I just push changes to the same branch?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1455)*

**Comment by ratulm** [comment]
Yes, push to branch.

**Comment by rabeckett** [comment]
*[projects/batfish/src/main/java/org/batfish/symbolic/bdd/BDDNetFactory.java, line 384 at r1](https://reviewable.io/reviews/batfish/batfish/1455#-LD7zHYTBVxT0EB5f38-:-LD9iguY6_RMWE75shWp:b-h75v64) ([raw file](https://github.com/batfish/batfish/blob/bcd2aedfd993d70ff0adfc3f9e795b58df94048c/projects/batfish/src/main/java/org/batfish/symbolic/bdd/BDDNetFactory.java#L384)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

This just gets one example/model, right?
</blockquote></details>

Yes, it is useful for getting a single counterexample (e.g., find out what packet two ACLs differ on). The allSat() method returns more examples.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1455)*

**Comment by rabeckett** [comment]
*[projects/batfish/src/main/java/org/batfish/symbolic/bdd/BDDNetFactory.java, line 872 at r1](https://reviewable.io/reviews/batfish/batfish/1455#-LD80bpj0Fgx6WuXbB09:-LD9jHJrEyn_G63R4kZ0:bou0n8p) ([raw file](https://github.com/batfish/batfish/blob/bcd2aedfd993d70ff0adfc3f9e795b58df94048c/projects/batfish/src/main/java/org/batfish/symbolic/bdd/BDDNetFactory.java#L872)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

* Naming: `BDDRecord` vs `BDDRoute`.
* BDDs are not immutable, and are in fact mutated in this class via the destructive `*With` methods. Can we move away from those?
</blockquote></details>

Yeah, that sounds good. 

One thing I ran into that is worth mentioning is that the *With methods actually are useful because they consume the argument, decrementing the reference count on the consumed BDD. This is useful because otherwise JavaBDD will not be able to reclaim unused memory when it does a GC sweep. If we don't use the *With methods, we should try to remember to explicitly call free() on the BDDs when they are not needed. For example, the *With methods are still useful for local accumulator-like variables that can be updated in place.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1455)*

**Comment by rabeckett** [comment]
*[projects/batfish/src/main/java/org/batfish/symbolic/bdd/BDDNetwork.java, line 103 at r1](https://reviewable.io/reviews/batfish/batfish/1455#-LD9FbCx3eKq79gZVRdu:-LD9koX550y3Zo6kkrk9:buq3j6r) ([raw file](https://github.com/batfish/batfish/blob/bcd2aedfd993d70ff0adfc3f9e795b58df94048c/projects/batfish/src/main/java/org/batfish/symbolic/bdd/BDDNetwork.java#L103)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

Can you add tests for this method?
</blockquote></details>

This is already tested pretty well with this integration test

https://github.com/batfish/batfish/blob/master/tests/java-smt/commands#L144

It has a bunch different interface policies doing things like adding and removing communities, prepending to the AS path, matching different prefixes and port ranges, and so on, and uses computeInterfacePolicies() to group the policies that are equivalent. The unit tests are actually embedded in this configuration as pairs of interfaces that should be equivalent:

https://github.com/batfish/batfish/blob/master/test_rigs/smt-examples/BDD1/configs/R1.cfg#L55

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1455)*

**Comment by anothermattbrown** [comment]
Reviewed 2 of 15 files at r2.
Review status: 6 of 16 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[projects/batfish/src/main/java/org/batfish/symbolic/bdd/BDDNetFactory.java, line 872 at r1](https://reviewable.io/reviews/batfish/batfish/1455#-LD80bpj0Fgx6WuXbB09:-LDClHPz8Lk9CGjQvB6b:b-otkmur) ([raw file](https://github.com/batfish/batfish/blob/bcd2aedfd993d70ff0adfc3f9e795b58df94048c/projects/batfish/src/main/java/org/batfish/symbolic/bdd/BDDNetFactory.java#L872)):*
<details><summary><i>Previously, rabeckett (Ryan Beckett) wrote…</i></summary><blockquote>

Yeah, that sounds good. 

One thing I ran into that is worth mentioning is that the *With methods actually are useful because they consume the argument, decrementing the reference count on the consumed BDD. This is useful because otherwise JavaBDD will not be able to reclaim unused memory when it does a GC sweep. If we don't use the *With methods, we should try to remember to explicitly call free() on the BDDs when they are not needed. For example, the *With methods are still useful for local accumulator-like variables that can be updated in place.
</blockquote></details>

Interesting. If we leak BDDs in this way, how long will they be retained? Will they be collected after all references from java-land to the BDD, factory, etc. are collected by the java GC?

Moving forward, please document any uses of *With, pointing out in particular that the calls are destructive, that we know the consumed BDD has no other references, and why it's needed for perf/bloat issues. 

Even better would be to keep all uses of *With in a single class named something like `UnsafeBDDUtils`. Just an idea though; feel free to ignore.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1455)*

**Comment by rabeckett** [comment]
*[projects/batfish/src/main/java/org/batfish/symbolic/bdd/BDDNetFactory.java, line 872 at r1](https://reviewable.io/reviews/batfish/batfish/1455#-LD80bpj0Fgx6WuXbB09:-LDDffBS1BaqvGoEXU9S:b26dz8z) ([raw file](https://github.com/batfish/batfish/blob/bcd2aedfd993d70ff0adfc3f9e795b58df94048c/projects/batfish/src/main/java/org/batfish/symbolic/bdd/BDDNetFactory.java#L872)):*

Yeah, they should be freed when the references to the BDDFactory are unreachable. But this doesn't help with peak memory usage. By freeing the nodes explicitly, the peak memory went down a lot in my own tests, around 50-75% in some cases. I'll try to document this moving forward, but it happens often. The main place I use these methods often now is when I have a local accumulator variable, and I assign the the same variable like this:

```
temp = temp.andWith(bdd)
```

>that we know the consumed BDD has no other references, and why it's needed for perf/bloat issues.

Fortunately, the Javabdd will throw an exception if you try to reuse a bdd node that has been freed like the one in the above example.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1455)*

**Comment by anothermattbrown** [comment]
Reviewed 6 of 15 files at r2.
Review status: 12 of 16 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[projects/batfish/src/main/java/org/batfish/symbolic/bdd/BDDNetConfig.java, line 5 at r2](https://reviewable.io/reviews/batfish/batfish/1455#-LDIo8li3lxYKFVUg1fu:-LDIo8li3lxYKFVUg1fv:b2w13qs) ([raw file](https://github.com/batfish/batfish/blob/3fee03eb2e9b188ed1fc29d1d71960d4e30b7608/projects/batfish/src/main/java/org/batfish/symbolic/bdd/BDDNetConfig.java#L5)):*
> ```Java
> public class BDDNetConfig {
> 
>   private boolean _keepLp;
> ```

can these be final?

---

*[projects/batfish/src/main/java/org/batfish/symbolic/bdd/BDDNetConfig.java, line 21 at r2](https://reviewable.io/reviews/batfish/batfish/1455#-LDInvKsEvbPFRJwSFPt:-LDInvKsEvbPFRJwSFPu:bxyasfg) ([raw file](https://github.com/batfish/batfish/blob/3fee03eb2e9b188ed1fc29d1d71960d4e30b7608/projects/batfish/src/main/java/org/batfish/symbolic/bdd/BDDNetConfig.java#L21)):*
> ```Java
>   private boolean _keepRouters;
> 
>   /*
> ```

probably belongs on the class

---

*[projects/batfish/src/main/java/org/batfish/symbolic/bdd/BDDNetwork.java, line 103 at r1](https://reviewable.io/reviews/batfish/batfish/1455#-LD9FbCx3eKq79gZVRdu:-LDIpnnj-PkZc_F3pB9U:b-82t8eb) ([raw file](https://github.com/batfish/batfish/blob/bcd2aedfd993d70ff0adfc3f9e795b58df94048c/projects/batfish/src/main/java/org/batfish/symbolic/bdd/BDDNetwork.java#L103)):*
<details><summary><i>Previously, rabeckett (Ryan Beckett) wrote…</i></summary><blockquote>

This is already tested pretty well with this integration test

https://github.com/batfish/batfish/blob/master/tests/java-smt/commands#L144

It has a bunch different interface policies doing things like adding and removing communities, prepending to the AS path, matching different prefixes and port ranges, and so on, and uses computeInterfacePolicies() to group the policies that are equivalent. The unit tests are actually embedded in this configuration as pairs of interfaces that should be equivalent:

https://github.com/batfish/batfish/blob/master/test_rigs/smt-examples/BDD1/configs/R1.cfg#L55

</blockquote></details>

Unit tests would provide additional value, but if you'd prefer I'll try to write some myself.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1455)*

**Comment by dhalperi** [comment]
Seems like Matt has a handle on review. Happy to take a final look if requested, but for now unassigning and assuming i'm not needed.

**Comment by anothermattbrown** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1455)*

**Comment by anothermattbrown** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1455#-:-LDmCxJW0nnmNUOw_XjG:bnfp4nl)*

**Comment by rabeckett** [comment]
*[projects/batfish/src/main/java/org/batfish/symbolic/bdd/BDDNetwork.java, line 103 at r1](https://reviewable.io/reviews/batfish/batfish/1455#-LD9FbCx3eKq79gZVRdu:-LDsMo7Z30-JaUyWjrD2:be9mw0w) ([raw file](https://github.com/batfish/batfish/blob/bcd2aedfd993d70ff0adfc3f9e795b58df94048c/projects/batfish/src/main/java/org/batfish/symbolic/bdd/BDDNetwork.java#L103)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

Unit tests would provide additional value, but if you'd prefer I'll try to write some myself.
</blockquote></details>

I'm happy to add unit tests if that would be helpful. Do you have any specific kinds of tests in mind?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1455)*

**Comment by rabeckett** [comment]
*[projects/batfish/src/main/java/org/batfish/symbolic/bdd/BDDNetConfig.java, line 5 at r2](https://reviewable.io/reviews/batfish/batfish/1455#-LDIo8li3lxYKFVUg1fu:-LDsNelB5MqBB1VAkRxY:bb74ce2) ([raw file](https://github.com/batfish/batfish/blob/3fee03eb2e9b188ed1fc29d1d71960d4e30b7608/projects/batfish/src/main/java/org/batfish/symbolic/bdd/BDDNetConfig.java#L5)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

can these be final?
</blockquote></details>

Sure

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1455)*

**Comment by anothermattbrown** [comment]
Review status: 14 of 16 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[projects/batfish/src/main/java/org/batfish/symbolic/bdd/BDDNetwork.java, line 103 at r1](https://reviewable.io/reviews/batfish/batfish/1455#-LD9FbCx3eKq79gZVRdu:-LDsotvG2nhDGYijnKk4:byod92d) ([raw file](https://github.com/batfish/batfish/blob/bcd2aedfd993d70ff0adfc3f9e795b58df94048c/projects/batfish/src/main/java/org/batfish/symbolic/bdd/BDDNetwork.java#L103)):*
<details><summary><i>Previously, rabeckett (Ryan Beckett) wrote…</i></summary><blockquote>

I'm happy to add unit tests if that would be helpful. Do you have any specific kinds of tests in mind?
</blockquote></details>

Some ideas: 
  intensional: test that the BDD generated for a import policy/export policy/interface/config/etc is exactly what you expect
  extensional: test that the BDD behaves as expected
  test that two interface policies are equivalent, that two are non-equivalent, etc.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1455)*

**Comment by anothermattbrown** [comment]
Review status: 15 of 16 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1455)*

**Comment by dhalperi** [comment]
Given how out of date this PR is, closing as stale.

**Pull request closed without merging**
