### PR TITLE
SearchRoutePolicies: Allow community-list names as constraints

### PR DESCRIPTION
**Pull request by millstein**
Updates the SearchRoutePolicies question to allow named community structures to be used as input/output constraints on routes.  Previously only community literals and regexes were supported.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 5 of 7 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8861)* status: all files reviewed, 3 unresolved discussions (waiting on @backesj and @millstein)

___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/RegexConstraint.java` line 96 at r2](https://reviewable.io/reviews/batfish/batfish/8861#-NiMGV-eAQw-0CdmpdWA:-NiMGV-eAQw-0CdmpdWB:b-bvopre) ([raw file](https://github.com/batfish/batfish/blob/f21945b3108c8c52f96ca7fea91da8bfd375cb41/projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/RegexConstraint.java#L96)):*
> ```Java
>       }
>     } else {
>       throw new BatfishException("Invalid regex constraint: " + s);
> ```

future reference: use IllegalArgumentException for this kind of thing.
___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesAnswerer.java` line 583 at r2](https://reviewable.io/reviews/batfish/batfish/8861#-NiMFx4I4TT9hA6vu6ky:-NiMFx4I4TT9hA6vu6kz:bry7wv3) ([raw file](https://github.com/batfish/batfish/blob/f21945b3108c8c52f96ca7fea91da8bfd375cb41/projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesAnswerer.java#L583)):*
> ```Java
>   private Stream<Row> searchPoliciesForNode(
>       String node, Set<RoutingPolicy> policies, NetworkSnapshot snapshot) {
>     Configuration config = _batfish.loadConfigurations(snapshot).get(node);
> ```

use snapshot context for this type of thing.
___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesAnswerer.java` line 598 at r2](https://reviewable.io/reviews/batfish/batfish/8861#-NiMGAQo8MG3-jle40vb:-NiMGAQo8MG3-jle40vc:bb127ah) ([raw file](https://github.com/batfish/batfish/blob/f21945b3108c8c52f96ca7fea91da8bfd375cb41/projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesAnswerer.java#L598)):*
> ```Java
>                         case STRUCTURE_NAME:
>                           CommunityMatchExpr cme = config.getCommunityMatchExprs().get(regex);
>                           checkArgument(cme != null, "Unknown named community list: " + regex);
> ```

do this in a pre-validation step in rather than putting it in the engine.

**Review by millstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8861)* status: all files reviewed, 1 unresolved discussion (waiting on @backesj and @dhalperi)

___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesAnswerer.java` line 583 at r2](https://reviewable.io/reviews/batfish/batfish/8861#-NiMFx4I4TT9hA6vu6ky:-NiMZJZ78UsSozTWVOYd:b-cp9xw7) ([raw file](https://github.com/batfish/batfish/blob/f21945b3108c8c52f96ca7fea91da8bfd375cb41/projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesAnswerer.java#L583)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

use snapshot context for this type of thing.
</blockquote></details>

I guess you mean specifier context.  Updated.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8861)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @backesj and @millstein)

___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesAnswerer.java` line 629 at r3](https://reviewable.io/reviews/batfish/batfish/8861#-NiMgb4b-iLsYmkqsS4w:-NiMgb4b-iLsYmkqsS4x:b-fjf1s9) ([raw file](https://github.com/batfish/batfish/blob/e31eb78fe15b72ca5869db527814f34acb182d95/projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesAnswerer.java#L629)):*
> ```Java
>             .addAll(_outputConstraints.getCommunities().getRegexConstraints())
>             .build()
>             .stream()
> ```

Don't know if this is relevant, because I didn't look at the underlying types, but I think you can do something like

```
Stream.concat(l1.stream(), l2.stream()).distinct()
```

Instead of

```
ImmutableSet.builder.addAll(l1).addAll(l2).build().stream()
```

1. if you just wanted to build a combined stream, you can concat them
2. if you wanted deduping, you can use distinct. Which does a streaming dedup, I assume using a hashtable.

**Comment by dhalperi** [comment]
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesAnswerer.java` line 639 at r3](https://reviewable.io/reviews/batfish/batfish/8861#-NiMhRND9JLKMwFCpTEa:-NiMhRND9JLKMwFCpTEb:bfrq6dl) ([raw file](https://github.com/batfish/batfish/blob/e31eb78fe15b72ca5869db527814f34acb182d95/projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesAnswerer.java#L639)):*
> ```Java
>                     checkArgument(
>                         context.getConfigs().get(node).getCommunityMatchExprs().containsKey(cme),
>                         "Node " + node + "has no CommunityMatchExpr named " + cme)));
> ```

FYI `checkArgument` has built-in support for `%s`, so you can do `"Node %s has no..", node`.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8861)* status: all files reviewed, 1 unresolved discussion (waiting on @backesj and @millstein)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8861)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @backesj)

**Pull request merged**
