### PR TITLE
added support for more junos applications

### PR DESCRIPTION
**Pull request by erikljungman**

### CODE REVIEW

**Comment by dhalperi** [comment]
Reviewed 5 of 8 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/JunosApplication.java, line 22 at r2](https://reviewable.io/reviews/batfish/batfish/1313#-LBhypCT8wltL8co6Zos:-LBhypCT8wltL8co6Zot:b-toe7wx) ([raw file](https://github.com/batfish/batfish/blob/6a35e34379ff8b51401310690bacd1291515ee18/projects/batfish/src/main/java/org/batfish/representation/juniper/JunosApplication.java#L22)):*
> ```Java
> public enum JunosApplication implements Application {
>   /**
>    * TODO: separate applications from application-sets the list below inlcudes both applications and
> ```

Can you update this comment to point to a github issue? Something like

```
TODO(https://github.com/batfish/batfish/issues1234): separate applications from application-sets
```

And leave the details in the github issue.

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/JunosApplication.java, line 249 at r2](https://reviewable.io/reviews/batfish/batfish/1313#-LBhz2_M1ouT-2_PPXU_:-LBhz2_M1ouT-2_PPXUa:bxxyqqr) ([raw file](https://github.com/batfish/batfish/blob/6a35e34379ff8b51401310690bacd1291515ee18/projects/batfish/src/main/java/org/batfish/representation/juniper/JunosApplication.java#L249)):*
> ```Java
>       @Nullable Integer portRangeStart,
>       @Nullable Integer portRangeEnd) {
>     if (ip != null) hb.setIpProtocols(ImmutableSet.of(ip));
> ```

all `if` statements should always have `{}`. I suspect this will cause a checkstyle bug. If it hasn't, we've got a problem in our config :)

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/JunosApplication.java, line 284 at r2](https://reviewable.io/reviews/batfish/batfish/1313#-LBhzNRG-FQ2zwTOQmIz:-LBhzNRG-FQ2zwTOQmJ-:byzfa6g) ([raw file](https://github.com/batfish/batfish/blob/6a35e34379ff8b51401310690bacd1291515ee18/projects/batfish/src/main/java/org/batfish/representation/juniper/JunosApplication.java#L284)):*
> ```
> BIFFudp_OR_EXECtcp
> ```
?

Never mind, ari filled me in. We have to stop using enums for this -- it was a nice shrotcut, while it lasted.

OUtside the scope of this PR.

---

*[projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java, line 319 at r2](https://reviewable.io/reviews/batfish/batfish/1313#-LBi-CBlD4hXOLSxvjuD:-LBi-CBlD4hXOLSxvjuE:b-2yh7ei) ([raw file](https://github.com/batfish/batfish/blob/6a35e34379ff8b51401310690bacd1291515ee18/projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java#L319)):*
> ```Java
>     Batfish batfish = getBatfishForConfigurationNames("pre-defined-junos-applications");
>     InitInfoAnswerElement answer = batfish.initInfo(false, true);
>     System.out.println(answer.prettyPrint());
> ```

no printlns allowed

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1313)*

**Comment by arifogel** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/NamedPort.java, line 38 at r2](https://reviewable.io/reviews/batfish/batfish/1313#-LBiVdJo7ScUidBQjACo:-LBwOjfS9Z2c_1NBmYFs:b-x8i6e0) ([raw file](https://github.com/batfish/batfish/blob/6a35e34379ff8b51401310690bacd1291515ee18/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/NamedPort.java#L38)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Looks suspect. Did you intend to put `0` here?
</blockquote></details>

For reference, this was removed because we don't want to handle SCTP yet. Plus 0 makes no since since it violates SCTP RFC.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1313)*

**Comment by arifogel** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1313#-:-LBwPHN17HsA1uMBHZE4:bnfp4nl)*

**Comment by arifogel** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1313)*

**Pull request merged**
