### PR TITLE
fix numResults in unique ip assignments question

### PR DESCRIPTION
**Pull request by anothermattbrown**

### CODE REVIEW

**Comment by dhalperi** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[projects/question/src/main/java/org/batfish/question/UniqueIpAssignmentsQuestionPlugin.java, line 60 at r1](https://reviewable.io/reviews/batfish/batfish/1231#-LAvPCkYA6EXBsGaQrTk:-LAvPCkYA6EXBsGaQrTl:b-9hkvd0) ([raw file](https://github.com/batfish/batfish/blob/5d913e3b2fd9b3e3cabbeb2f89c4a1f1c8c39f73/projects/question/src/main/java/org/batfish/question/UniqueIpAssignmentsQuestionPlugin.java#L60)):*
> ```
>  hey
> ```

?

---

*[projects/question/src/main/java/org/batfish/question/UniqueIpAssignmentsQuestionPlugin.java, line 75 at r1](https://reviewable.io/reviews/batfish/batfish/1231#-LAvPNWZAQgWxh0aJLZ2:-LAvPNWZAQgWxh0aJLZ3:bbb3x51) ([raw file](https://github.com/batfish/batfish/blob/5d913e3b2fd9b3e3cabbeb2f89c4a1f1c8c39f73/projects/question/src/main/java/org/batfish/question/UniqueIpAssignmentsQuestionPlugin.java#L75)):*
> ```Java
> 
>   public static class UniqueIpAssignmentsAnswerer extends Answerer {
>     private final UniqueIpAssignmentsQuestion _question;
> ```

is this shadowing the `super` field? seems inadvisable.

---

*[projects/question/src/main/java/org/batfish/question/UniqueIpAssignmentsQuestionPlugin.java, line 119 at r1](https://reviewable.io/reviews/batfish/batfish/1231#-LAvQ2O53ExS0ISCvufN:-LAvQ2O53ExS0ISCvufO:bnb5tk9) ([raw file](https://github.com/batfish/batfish/blob/5d913e3b2fd9b3e3cabbeb2f89c4a1f1c8c39f73/projects/question/src/main/java/org/batfish/question/UniqueIpAssignmentsQuestionPlugin.java#L119)):*
> ```Java
>                                               .add(
>                                                   new NodeInterfacePair(
>                                                       config.getHostname(), iface.getName())))));
> ```

this seems like an abuse of streams. We have a forEach 3-deep in lambdas? This can't be the best way to do this.

Some suggestions:

* stream over nodes, not configurations.
* use flatMap instead of forEach, where you can.
* consider using MultiMap?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1231)*

**Comment by dhalperi** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/question/src/main/java/org/batfish/question/UniqueIpAssignmentsQuestionPlugin.java, line 75 at r1](https://reviewable.io/reviews/batfish/batfish/1231#-LAvPNWZAQgWxh0aJLZ2:-LAyDn9a4Lnpsi9dZipl:b-d4371w) ([raw file](https://github.com/batfish/batfish/blob/5d913e3b2fd9b3e3cabbeb2f89c4a1f1c8c39f73/projects/question/src/main/java/org/batfish/question/UniqueIpAssignmentsQuestionPlugin.java#L75)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Kind of a meta-question would be why add this field if there parent already has it? Is it that the interface is crappy and you want to do the annoying cast earlier?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1231)*

**Comment by anothermattbrown** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/question/src/main/java/org/batfish/question/UniqueIpAssignmentsQuestionPlugin.java, line 75 at r1](https://reviewable.io/reviews/batfish/batfish/1231#-LAvPNWZAQgWxh0aJLZ2:-LAycIhK1D8cRsaIS_s5:b-dsfc52) ([raw file](https://github.com/batfish/batfish/blob/5d913e3b2fd9b3e3cabbeb2f89c4a1f1c8c39f73/projects/question/src/main/java/org/batfish/question/UniqueIpAssignmentsQuestionPlugin.java#L75)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Kind of a meta-question would be why add this field if there parent already has it? Is it that the interface is crappy and you want to do the annoying cast earlier?
</blockquote></details>

yes, though I'd be fine removing it. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1231)*

**Comment by anothermattbrown** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/question/src/main/java/org/batfish/question/UniqueIpAssignmentsQuestionPlugin.java, line 75 at r1](https://reviewable.io/reviews/batfish/batfish/1231#-LAvPNWZAQgWxh0aJLZ2:-LAyjuOh1VuOMvbTVS-C:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/5d913e3b2fd9b3e3cabbeb2f89c4a1f1c8c39f73/projects/question/src/main/java/org/batfish/question/UniqueIpAssignmentsQuestionPlugin.java#L75)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

yes, though I'd be fine removing it. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1231)*

**Comment by dhalperi** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1231#-:-LAyqRAF7R3aFzlJGSYj:bnfp4nl)*

**Pull request merged**
