### PR TITLE
Bdp: refactor BGP to to simplify dataflow and speed up a bit

### PR DESCRIPTION
**Pull request by progwriter**
Several improvements:
- Clear VR -> BgpRoutingProcess pipeline that conforms to the redistribute/pull model (like other processes). Moved nearly all BGP code into BgpRoutingProcess
- Clear(er) endOfRound calls for VR and BGP
- No more re-queuing of entire RIBs on each iteration: keep track of previous round's main RIB delta
- No more processing of external advertisements each iteration, only once
- Got rid of `newSessionEstablishedHook` and inlined logic into
`getOutgoingRoutesPerEdge`
- Fewer occurrences of crazy rib delta merging

### CODE REVIEW

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 9 of 10 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6251)* status: all files reviewed, 6 unresolved discussions (waiting on @progwriter)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java, line 398 at r2](https://reviewable.io/reviews/batfish/batfish/6251#-MIS4hoj4c8GA6L3jkus:-MIS4hoj4c8GA6L3jkut:bajr63e) ([raw file](https://github.com/batfish/batfish/blob/64e23e99bd9836bba51a27ba8485a7cbf08e5e0e/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java#L398)):*
> ```
>   assert _bgpv4DeltaBuilder.isEmpty();
> ```
should this be removed or uncommented?
what (other) invariants hold here (that would be useful for understanding the code)
___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java, line 504 at r2](https://reviewable.io/reviews/batfish/batfish/6251#-MIS58eDCjEG1wrrf2Ea:-MIS58eDCjEG1wrrf2Eb:b-leigd5) ([raw file](https://github.com/batfish/batfish/blob/64e23e99bd9836bba51a27ba8485a7cbf08e5e0e/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java#L504)):*
> ```
> _toRedistribute.put(srcVrfName, mainRibDelta);
> ```
can we assert that there wasn't already something there?
___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java, line 516 at r2](https://reviewable.io/reviews/batfish/batfish/6251#-MIS5Y-G9OzIkhd4n1z9:-MIS5Y-G9OzIkhd4n1zA:bbbfssz) ([raw file](https://github.com/batfish/batfish/blob/64e23e99bd9836bba51a27ba8485a7cbf08e5e0e/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java#L516)):*
> ```
> endOfRound has been called BEFORE
> ```
1) may be a good idea to summarize how this method is used in a javadoc comment
2) are we expecting nothing to happen between `endOfRound` and `isDirty`? Can we assert that?
___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java, line 537 at r2](https://reviewable.io/reviews/batfish/batfish/6251#-MIS5RwGEYMEmtdZA99l:-MIS5RwGEYMEmtdZA99m:b-5wiff0) ([raw file](https://github.com/batfish/batfish/blob/64e23e99bd9836bba51a27ba8485a7cbf08e5e0e/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java#L537)):*
> ```
> assert _bgpv4DeltaBuilder.isEmpty();
> ```
should this be removed or uncommented?
___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java, line 653 at r2](https://reviewable.io/reviews/batfish/batfish/6251#-MIS5o811bT378B6LybZ:-MIS5o811bT378B6Lyb_:b-xpw4dd) ([raw file](https://github.com/batfish/batfish/blob/64e23e99bd9836bba51a27ba8485a7cbf08e5e0e/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java#L653)):*
> ```
> assert _bgpv4DeltaBuilder.isEmpty();
> ```
remove or uncomment?
___
*[tests/basic/genDp.ref, line 5 at r2](https://reviewable.io/reviews/batfish/batfish/6251#-MIS9eYRA0eu3O8ylPvT:-MIS9eYRA0eu3O8ylPvU:b-8qpxgi) ([raw file](https://github.com/batfish/batfish/blob/64e23e99bd9836bba51a27ba8485a7cbf08e5e0e/tests/basic/genDp.ref#L5)):*
> ```
> bgpBestPathRibRoutesByIteration
> ```
the total changed from 434 to 560. is that expected?

**Review by anothermattbrown — COMMENTED** [review]
awesome! :tada: 

> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6251#-:-MIS9waeCQOSrjz7rkwn:b-ioovn)* status: all files reviewed, 6 unresolved discussions (waiting on @progwriter)

**Review by progwriter — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6251)* status: 9 of 11 files reviewed, 3 unresolved discussions (waiting on @anothermattbrown and @progwriter)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java, line 398 at r2](https://reviewable.io/reviews/batfish/batfish/6251#-MIS4hoj4c8GA6L3jkus:-MIUwOffC8piDSfzg-d5:bosm1j8) ([raw file](https://github.com/batfish/batfish/blob/64e23e99bd9836bba51a27ba8485a7cbf08e5e0e/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java#L398)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

> ```
>   assert _bgpv4DeltaBuilder.isEmpty();
> ```
should this be removed or uncommented?
what (other) invariants hold here (that would be useful for understanding the code)
</blockquote></details>

removing all of these for now. 
___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java, line 516 at r2](https://reviewable.io/reviews/batfish/batfish/6251#-MIS5Y-G9OzIkhd4n1z9:-MIUwbA61XJaEpuNDaRE:b1dyqsg) ([raw file](https://github.com/batfish/batfish/blob/64e23e99bd9836bba51a27ba8485a7cbf08e5e0e/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java#L516)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

> ```
> endOfRound has been called BEFORE
> ```
1) may be a good idea to summarize how this method is used in a javadoc comment
2) are we expecting nothing to happen between `endOfRound` and `isDirty`? Can we assert that?
</blockquote></details>

1. it's documented in `RoutingProcess`, but I've expanded a bit
2. correct, but it's no obvious how.
___
*[tests/basic/genDp.ref, line 5 at r2](https://reviewable.io/reviews/batfish/batfish/6251#-MIS9eYRA0eu3O8ylPvT:-MIUwUHI0tN6oUSmWwRA:b-mex59f) ([raw file](https://github.com/batfish/batfish/blob/64e23e99bd9836bba51a27ba8485a7cbf08e5e0e/tests/basic/genDp.ref#L5)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

> ```
> bgpBestPathRibRoutesByIteration
> ```
the total changed from 434 to 560. is that expected? 
</blockquote></details>

say more? these counts are already cumulative. only the last iteration is the total.

**Review by anothermattbrown — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6251)* status: 9 of 11 files reviewed, 2 unresolved discussions (waiting on @anothermattbrown and @progwriter)

___
*[tests/basic/genDp.ref, line 5 at r2](https://reviewable.io/reviews/batfish/batfish/6251#-MIS9eYRA0eu3O8ylPvT:-MIV0yAjElbxeo1chJ_v:b-js6rk0) ([raw file](https://github.com/batfish/batfish/blob/64e23e99bd9836bba51a27ba8485a7cbf08e5e0e/tests/basic/genDp.ref#L5)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

say more? these counts are already cumulative. only the last iteration is the total.
</blockquote></details>

aha, I didn't realize they were cumulative. so if the last 3 rounds add nothing, we should be skipping them?

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6251)* status: all files reviewed, 1 unresolved discussion (waiting on @progwriter)

**Review by progwriter — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6251)* status: 10 of 11 files reviewed, all discussions resolved (waiting on @anothermattbrown)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java, line 504 at r2](https://reviewable.io/reviews/batfish/batfish/6251#-MIS58eDCjEG1wrrf2Ea:-MIV3kVt4J9ZjcGmuTTN:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/64e23e99bd9836bba51a27ba8485a7cbf08e5e0e/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java#L504)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

> ```
> _toRedistribute.put(srcVrfName, mainRibDelta);
> ```
can we assert that there wasn't already something there?
</blockquote></details>

done
___
*[tests/basic/genDp.ref, line 5 at r2](https://reviewable.io/reviews/batfish/batfish/6251#-MIS9eYRA0eu3O8ylPvT:-MIV1TUQDWvVAiKRrjH8:b3g5xeh) ([raw file](https://github.com/batfish/batfish/blob/64e23e99bd9836bba51a27ba8485a7cbf08e5e0e/tests/basic/genDp.ref#L5)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

aha, I didn't realize they were cumulative. so if the last 3 rounds add nothing, we should be skipping them?
</blockquote></details>

yes. still have to figure this one out.

**Review by progwriter — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6251)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
