### PR TITLE
FortiOS: Improve address extraction/warnings

### PR DESCRIPTION
**Pull request by corinaminer**
Implements address edit block validation and handles when address blocks switch type. Currently there are three supported address types: `ipmask`, `iprange`, and `wildcard`. All three are configured with two IPs:
- `ipmask` takes a subnet with an IP and a mask
- `iprange` takes a start and end IP
- `ipwildcard` takes a wildcard with an IP and a mask

It seems that under the hood, the CLI just stores two IPs (which both default to 0.0.0.0), and reinterprets them when you change type. For example, if you have an address with this configuration:
```
set type ipmask
set subnet 1.1.1.0 255.255.255.0
```
and then you change the type to `iprange`, you'll now have:
```
set type iprange
set start-ip 1.1.1.0
set end-ip 255.255.255.0
```

A couple of unintuitive findings to note:
1. For type `ipmask`, if you enter a subnet with an invalid subnet mask, the subnet IP will be canonicalized as if you entered a wildcard. For example, if you enter `set subnet 1.1.1.1 255.0.255.0`, the address will show `set subnet 1.0.1.0 255.0.255.0` (which will still be rejected at `next`).
2. If you switch an address from `iprange` to either of the other supported types, no canonicalization will be applied. So if you start with an `iprange` address with endpoints 1.1.1.1 and 255.0.0.0 and then switch it to type `ipmask`, the address will show `set subnet 1.1.1.1 255.0.0.0` (which will not be rejected, but afaik isn't possible to get any other way).

### CODE REVIEW

**Review by sfraint — COMMENTED** [review]
> Reviewed 9 of 10 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6733)* status: all files reviewed, 5 unresolved discussions (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 273 at r2](https://reviewable.io/reviews/batfish/batfish/6733#-MVx3qfRC1UQzrQark5N:-MVx3qfRC1UQzrQark5O:bke6jdr) ([raw file](https://github.com/batfish/batfish/blob/8ebf93772a4aed720753d4d25d054b6161ba926c/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L273)):*
> ```
>     _currentAddressValid = name.isPresent();
> ```
similar to the comment below, but if this is strictly about address name being valid, would be clearer if that is part of the var name
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 370 at r2](https://reviewable.io/reviews/batfish/batfish/6733#-MVx1hBZ3NT3zeNOsbze:-MVx1hBZ3NT3zeNOsbzf:b-3e8cez) ([raw file](https://github.com/batfish/batfish/blob/8ebf93772a4aed720753d4d25d054b6161ba926c/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L370)):*
> ```
> Prefix.parse(ctx.subnet.ip_prefix().getText());
> ```
looks like a good place to use a `toPrefix(...)` method
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 372 at r2](https://reviewable.io/reviews/batfish/batfish/6733#-MVx5dyw0OHXxJmQ5WcP:-MVx5dyw0OHXxJmQ5WcQ:bovfkml) ([raw file](https://github.com/batfish/batfish/blob/8ebf93772a4aed720753d4d25d054b6161ba926c/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L372)):*
> ```
>         _currentAddress.getTypeSpecificFields().setIp2(prefix.getPrefixWildcard().inverted());
> ```
nit: comment about inversion
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 377 at r2](https://reviewable.io/reviews/batfish/batfish/6733#-MVx5x_Z-CzR-gSGT-Cg:-MVx5x_Z-CzR-gSGT-Ch:b-7pm2l9) ([raw file](https://github.com/batfish/batfish/blob/8ebf93772a4aed720753d4d25d054b6161ba926c/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L377)):*
> ```
>         IpWildcard wildcard = toIpWildcard(ctx.subnet.ip, ctx.subnet.mask);
>         _currentAddress.getTypeSpecificFields().setIp1(wildcard.getIp());
>         _currentAddress.getTypeSpecificFields().setIp2(toIp(ctx.subnet.mask));
> ```
no explicit inversion here; is that intentional/right? seems a little confusing give the consistent inversions elsewhere
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 1283 at r2](https://reviewable.io/reviews/batfish/batfish/6733#-MVx6UWS35iOtKf61YmA:-MVx6UWS35iOtKf61YmB:b-mm4a1a) ([raw file](https://github.com/batfish/batfish/blob/8ebf93772a4aed720753d4d25d054b6161ba926c/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L1283)):*
> ```
> service
> ```
address :slightly_smiling_face: 
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 1286 at r2](https://reviewable.io/reviews/batfish/batfish/6733#-MVx3eiL4ztWCSubX__f:-MVx3eiMBoFVCtIeZqPk:bfsoyp5) ([raw file](https://github.com/batfish/batfish/blob/8ebf93772a4aed720753d4d25d054b6161ba926c/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L1286)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>   public static @Nullable String addressValid(Address a, boolean valid) {
>     ...
>     if (!valid) {
>       return "name is invalid"; // currently, only invalid name can cause valid to be false
>     }
> ```
</details>

if `valid` is only used for name validity, maybe rename it to something like `nameValid`

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6733)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @arifogel and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 370 at r2](https://reviewable.io/reviews/batfish/batfish/6733#-MVx1hBZ3NT3zeNOsbze:-MVxHOHl2EMzTb8msiJO:be6r33) ([raw file](https://github.com/batfish/batfish/blob/8ebf93772a4aed720753d4d25d054b6161ba926c/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L370)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
> Prefix.parse(ctx.subnet.ip_prefix().getText());
> ```
looks like a good place to use a `toPrefix(...)` method
</blockquote></details>

Added a `toPrefix(Ip_prefixContext)` method. I'd rather not create a `toPrefix` method for `Ip_address_with_maybe_invalid_mask_or_prefixContext` mainly because i think it's cleaner to handle the ip/mask format completely separately. can talk about pros and cons offline if you want.
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 372 at r2](https://reviewable.io/reviews/batfish/batfish/6733#-MVx5dyw0OHXxJmQ5WcP:-MVxHp9NB8Y4psmNbMYj:b-t948zx) ([raw file](https://github.com/batfish/batfish/blob/8ebf93772a4aed720753d4d25d054b6161ba926c/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L372)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
>         _currentAddress.getTypeSpecificFields().setIp2(prefix.getPrefixWildcard().inverted());
> ```
nit: comment about inversion
</blockquote></details>

added.
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 377 at r2](https://reviewable.io/reviews/batfish/batfish/6733#-MVx5x_Z-CzR-gSGT-Cg:-MVxHrkA0zIeKUNtF_Ip:bxdci3l) ([raw file](https://github.com/batfish/batfish/blob/8ebf93772a4aed720753d4d25d054b6161ba926c/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L377)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
>         IpWildcard wildcard = toIpWildcard(ctx.subnet.ip, ctx.subnet.mask);
>         _currentAddress.getTypeSpecificFields().setIp1(wildcard.getIp());
>         _currentAddress.getTypeSpecificFields().setIp2(toIp(ctx.subnet.mask));
> ```
no explicit inversion here; is that intentional/right? seems a little confusing give the consistent inversions elsewhere
</blockquote></details>

Yeah, the inversion from FortiOS format to IpWildcard format is implemented inside `toIpWildcard`. I thought about adding a boolean parameter `invert` to that function, but i think it'd always be `true`. If we were using the wildcard's mask as `ip2`, we'd have to invert it to get it back in FortiOS format.

Added javadocs to the `toWildcard` methods to try to make this less opaque.
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 1286 at r2](https://reviewable.io/reviews/batfish/batfish/6733#-MVx3eiL4ztWCSubX__f:-MVxNg5gCLlt98pE85QL:b-xf8c4p) ([raw file](https://github.com/batfish/batfish/blob/8ebf93772a4aed720753d4d25d054b6161ba926c/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L1286)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
>   public static @Nullable String addressValid(Address a, boolean valid) {
>     ...
>     if (!valid) {
>       return "name is invalid"; // currently, only invalid name can cause valid to be false
>     }
> ```
if `valid` is only used for name validity, maybe rename it to something like `nameValid`
</blockquote></details>

yeah. renamed this local variable as well as `_currentAddressValid`

**Review by corinaminer — COMMENTED** [review]
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6733)* status: 8 of 10 files reviewed, 2 unresolved discussions (waiting on @arifogel and @sfraint)

___
*[projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java, line 407 at r3](https://reviewable.io/reviews/batfish/batfish/6733#-MVxUsJxBBmzN87ADb2z:-MVxUsJxBBmzN87ADb3-:bdd81gp) ([raw file](https://github.com/batfish/batfish/blob/2995588ae346f2af22a23f88a91c8babff7585d1/projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java#L407)):*
> ```Java
>             IpWildcard.ipWithWildcardMask(Ip.parse("2.2.2.2"), Ip.parse("0.255.255.0"))
>                 .toIpSpace()
>                 .accept(_srcIpBdd)));
> ```

these changes are just fallout from making static bdd fields non-static (#6731)

**Review by sfraint — COMMENTED** [review]
> Reviewed 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6733)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Pull request merged**
