### PR TITLE
FRR fix Layer2 VNIs

### PR DESCRIPTION
**Pull request by arifogel**
- put `Layer2Vni`s in default VRF following batfish/batfish#7731

### CODE REVIEW

**Review by corinaminer — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7737)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel and @sfraint)

___
*[projects/batfish/src/test/java/org/batfish/grammar/cumulus_concatenated/CumulusConcatenatedGrammarTest.java, line 318 at r1](https://reviewable.io/reviews/batfish/batfish/7737#-MpnWv7C4j7YtiklDIyv:-MpnWv7E6G_wLs3WzaQL:b-ygc5xo) ([raw file](https://github.com/batfish/batfish/blob/f59d61354144aa9749f842fc105e8b050b8a28bc/projects/batfish/src/test/java/org/batfish/grammar/cumulus_concatenated/CumulusConcatenatedGrammarTest.java#L318)):*
> ```Java
>     assertTrue(c.getDefaultVrf().getLayer3Vnis().isEmpty());
>     assertTrue(vrf1.getLayer2Vnis().isEmpty());
>     assertTrue(vrf1.getLayer3Vnis().isEmpty());
> ```

Is there any point to keeping vrf1 in this config?

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7737)* status: all files reviewed, 1 unresolved discussion (waiting on @corinaminer and @sfraint)

___
*[projects/batfish/src/test/java/org/batfish/grammar/cumulus_concatenated/CumulusConcatenatedGrammarTest.java, line 318 at r1](https://reviewable.io/reviews/batfish/batfish/7737#-MpnWv7C4j7YtiklDIyv:-MpojU2u7MnNiCFrc2rz:b2syxgp) ([raw file](https://github.com/batfish/batfish/blob/f59d61354144aa9749f842fc105e8b050b8a28bc/projects/batfish/src/test/java/org/batfish/grammar/cumulus_concatenated/CumulusConcatenatedGrammarTest.java#L318)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Is there any point to keeping vrf1 in this config?
</blockquote></details>

If you look at `bgp_vnis`, it still has `vrf1` configured in such a way that is not redundant with the other two vrfs. I'd suggest leaving it.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7737)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @corinaminer and @sfraint)

___
*[projects/batfish/src/test/java/org/batfish/grammar/cumulus_concatenated/CumulusConcatenatedGrammarTest.java, line 318 at r1](https://reviewable.io/reviews/batfish/batfish/7737#-MpnWv7C4j7YtiklDIyv:-MpojwvI4_xs5FCWdKjb:b-j63xqf) ([raw file](https://github.com/batfish/batfish/blob/f59d61354144aa9749f842fc105e8b050b8a28bc/projects/batfish/src/test/java/org/batfish/grammar/cumulus_concatenated/CumulusConcatenatedGrammarTest.java#L318)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

If you look at `bgp_vnis`, it still has `vrf1` configured in such a way that is not redundant with the other two vrfs. I'd suggest leaving it.
</blockquote></details>

I updated the description to make it a little more clear

**Review by corinaminer — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7737)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

**Review by sfraint — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7737)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Pull request merged**
