### PR TITLE
CiscoCombinedParser: start a NX-OS-specific BGP parser

### PR DESCRIPTION
**Pull request by dhalperi**
So far:

* manually expanded grammar, omitting any `no` commands
* code to switch to this combined parser for NX-OS format files.
* the beginnings of extraction, vendor-specific data model (Global, VRF,
  Address Family; no Neighbors or Templates yet).
* the beginnings of conversion from vendor-specific to
  vendor-independent data model.

To enable incremental review and merging, add the ability to toggle the
new NX-OS parser, and disable it except in tests.

(Will rebase after #1243)

### CODE REVIEW

**Comment by arifogel** [comment]
Reviewed 12 of 26 files at r1.
Review status: 12 of 26 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/grammar/GrammarSettings.java, line 6 at r1](https://reviewable.io/reviews/batfish/batfish/1246#-LB04E3pAmjUL76dM_s-:-LB04E3q7ilAQR2qja0S:b-m6b93t) ([raw file](https://github.com/batfish/batfish/blob/05c6464e08df6794153b720f99ef5f19d8b69424/projects/batfish-common-protocol/src/main/java/org/batfish/grammar/GrammarSettings.java#L6)):*
> ```Java
> public interface GrammarSettings {
> 
>   /** Returns true iff the Cisco NX-OS specific parser is enabled. */
> ```

This would be the first setting here specific to a configuration format. You sure you want this here?

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_bgp_nxos.g4, line 400 at r1](https://reviewable.io/reviews/batfish/batfish/1246#-LB05PHT9_xNfyondpTB:-LB05PHUEfE2gapE72tN:b-qa7s7u) ([raw file](https://github.com/batfish/batfish/blob/05c6464e08df6794153b720f99ef5f19d8b69424/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_bgp_nxos.g4#L400)):*
> ```ANTLR
>     // Is this a good idea? Almost exactly the same set of commands are valid
>     // (just missing inherit and default. Extractor would need to know about DEFAULT.)
>     DEFAULT rbnx_n_af_inner
> ```

What I've done in other places is make a `xxx_common` rule which does not contain the exceptions. That is, it would contain the contents of `rbnx_n_af_inner` except the default and inherit rules. Then in this rule you could just refer to the common rule.
However you go about naming, the idea is not to be overly permissive - *especially* with rules that recurse.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1246)*

**Comment by dhalperi** [comment]
Review status: 7 of 22 files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/grammar/GrammarSettings.java, line 6 at r1](https://reviewable.io/reviews/batfish/batfish/1246#-LB04E3pAmjUL76dM_s-:-LB0GxBX1z8z2-xSCvJy:b-w1zut8) ([raw file](https://github.com/batfish/batfish/blob/05c6464e08df6794153b720f99ef5f19d8b69424/projects/batfish-common-protocol/src/main/java/org/batfish/grammar/GrammarSettings.java#L6)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

This would be the first setting here specific to a configuration format. You sure you want this here?
</blockquote></details>

I couldn't quite tell from this question whether you meant "here in GrammarSettings" or "as an option at all". For the former, I removed it from here and now it's only in Batfish Settings.

For the latter, I only want it as a short-term feature to easy incremental review/migration, but it needs to be in settings somehow so that the java unit tests can reconfigure it. (see CiscoNxosTest of router id)

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1246)*

**Comment by arifogel** [comment]
Reviewed 12 of 26 files at r1, 4 of 5 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 1947 at r2](https://reviewable.io/reviews/batfish/batfish/1246#-LB2vicJ7D0VT2x_NaIm:-LB2vicJ7D0VT2x_NaIn:b-l0ylbp) ([raw file](https://github.com/batfish/batfish/blob/a4e3293101a0a786547941b5b114cda7d7f664a7/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L1947)):*
> ```Java
>         CiscoStructureType.ROUTE_MAP,
>         name,
>         CiscoStructureUsage.BGP_ROUTE_MAP_OTHER,
> ```

At some point you should change these usages to be specific.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 1287 at r2](https://reviewable.io/reviews/batfish/batfish/1246#-LB2wXa61CcTqHJMNdx0:-LB2wXa74TzbiiCHSlgj:b8uadb9) ([raw file](https://github.com/batfish/batfish/blob/a4e3293101a0a786547941b5b114cda7d7f664a7/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L1287)):*
> ```Java
>     newBgpProcess.setRouterId(CiscoNxConversions.getNxBgpRouterId(c, nxBgpVrf, v));
> 
>     // From NX-OS docs for `bestpath as-path multipath-relax`
> ```

Please:
 ```
/*
 * comment line 1
 * comment line 2
 */
```
 for multiline comments. It makes it more obvious when comments on different lines are part of the same block (vs. two unrelated comments one after the other).

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoNxConversions.java, line 36 at r2](https://reviewable.io/reviews/batfish/batfish/1246#-LB2xe7H1eRDebJ80rqV:-LB2xe7IElWneqnQS5JZ:b-vuphb2) ([raw file](https://github.com/batfish/batfish/blob/a4e3293101a0a786547941b5b114cda7d7f664a7/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoNxConversions.java#L36)):*
> ```Java
>             .entrySet()
>             .stream()
>             .filter(e -> e.getValue().getAddress() != null)
> ```

Interface must also be active! Also below.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/nx/package-info.java, line 1 at r2](https://reviewable.io/reviews/batfish/batfish/1246#-LB2y93d2lQMiA9ec2Qc:-LB2y93d2lQMiA9ec2Qd:btcc0ao) ([raw file](https://github.com/batfish/batfish/blob/a4e3293101a0a786547941b5b114cda7d7f664a7/projects/batfish/src/main/java/org/batfish/representation/cisco/nx/package-info.java#L1)):*
> ```Java
> @ParametersAreNonnullByDefault
> ```

What is this file?

---

*[projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/nxosBgpRouterId, line 4 at r2](https://reviewable.io/reviews/batfish/batfish/1246#-LB2td-i45hu3L_iB033:-LB2td-i45hu3L_iB034:b-7xainf) ([raw file](https://github.com/batfish/batfish/blob/a4e3293101a0a786547941b5b114cda7d7f664a7/projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/nxosBgpRouterId#L4)):*
> ```
> !Time: Wed Apr 25 23:55:08 2018
> 
> ! Real config from NX-OS emulator in GNS3, edited heavily to remote unrelated bits.
> ```

`remote` -> `remove`?

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/grammar/GrammarSettings.java, line 6 at r1](https://reviewable.io/reviews/batfish/batfish/1246#-LB04E3pAmjUL76dM_s-:-LB2yKrP8chKNQ0f6Gqa:b-inr63n) ([raw file](https://github.com/batfish/batfish/blob/05c6464e08df6794153b720f99ef5f19d8b69424/projects/batfish-common-protocol/src/main/java/org/batfish/grammar/GrammarSettings.java#L6)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I couldn't quite tell from this question whether you meant "here in GrammarSettings" or "as an option at all". For the former, I removed it from here and now it's only in Batfish Settings.

For the latter, I only want it as a short-term feature to easy incremental review/migration, but it needs to be in settings somehow so that the java unit tests can reconfigure it. (see CiscoNxosTest of router id)
</blockquote></details>

I meant the former. Your change is good.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1246)*

**Comment by dhalperi** [comment]
Review status: 18 of 22 files reviewed at latest revision, 6 unresolved discussions.

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_bgp_nxos.g4, line 400 at r1](https://reviewable.io/reviews/batfish/batfish/1246#-LB05PHT9_xNfyondpTB:-LBN15Ua2OMG22-hEcdS:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/05c6464e08df6794153b720f99ef5f19d8b69424/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_bgp_nxos.g4#L400)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

What I've done in other places is make a `xxx_common` rule which does not contain the exceptions. That is, it would contain the contents of `rbnx_n_af_inner` except the default and inherit rules. Then in this rule you could just refer to the common rule.
However you go about naming, the idea is not to be overly permissive - *especially* with rules that recurse.
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 1947 at r2](https://reviewable.io/reviews/batfish/batfish/1246#-LB2vicJ7D0VT2x_NaIm:-LBN17Hc3OY_OpDNhJNZ:b2nhb2c) ([raw file](https://github.com/batfish/batfish/blob/a4e3293101a0a786547941b5b114cda7d7f664a7/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L1947)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

At some point you should change these usages to be specific.
</blockquote></details>

Ack

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 1287 at r2](https://reviewable.io/reviews/batfish/batfish/1246#-LB2wXa61CcTqHJMNdx0:-LBA3Alb9tD31IU055UH:b-mn83zh) ([raw file](https://github.com/batfish/batfish/blob/a4e3293101a0a786547941b5b114cda7d7f664a7/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L1287)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Please:
 ```
/*
 * comment line 1
 * comment line 2
 */
```
 for multiline comments. It makes it more obvious when comments on different lines are part of the same block (vs. two unrelated comments one after the other).
</blockquote></details>

For implementation comments, I typically prefer this style. a) doesn't have the ~blank lines at top and bottom, and b) autoformatter doesn't muck with `//` blocks. In this particular case, I'm using a block-quote type of comment and I don't want autoformatter to mess with it.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoNxConversions.java, line 36 at r2](https://reviewable.io/reviews/batfish/batfish/1246#-LB2xe7H1eRDebJ80rqV:-LBAOpps-M5sDTqyhCn8:b-xsyzx8) ([raw file](https://github.com/batfish/batfish/blob/a4e3293101a0a786547941b5b114cda7d7f664a7/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoNxConversions.java#L36)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Interface must also be active! Also below.
</blockquote></details>

Not on NXOS, apparently. Try the config in an emulator, and it'll pick the shutdown interface.

But also, in testing this I've found the behavior to be non-deterministic - it will change upon reboot. Seems like the only good thing to do here is pick something deterministically for batfish and warn.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/nx/package-info.java, line 1 at r2](https://reviewable.io/reviews/batfish/batfish/1246#-LB2y93d2lQMiA9ec2Qc:-LBA4BXy4ClzP1su5Ld_:bl0cmi1) ([raw file](https://github.com/batfish/batfish/blob/a4e3293101a0a786547941b5b114cda7d7f664a7/projects/batfish/src/main/java/org/batfish/representation/cisco/nx/package-info.java#L1)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

What is this file?
</blockquote></details>

In general, `package-info.java` is where you can modify Java package-level attributes. Two common uses are annotations and documentation.

I'm using it for the former -- namely, to say that within this package any parameter not annotated `@Nullable` should be treated as being annotated `@Nonnull`. Will help me catch a lot of bugs.

---

*[projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/nxosBgpRouterId, line 4 at r2](https://reviewable.io/reviews/batfish/batfish/1246#-LB2td-i45hu3L_iB033:-LBA4qkm1RSyrpsXie94:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/a4e3293101a0a786547941b5b114cda7d7f664a7/projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/nxosBgpRouterId#L4)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

`remote` -> `remove`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1246)*

**Comment by dhalperi** [comment]
Updated with better documentation, router-id warnings, and a few of the requested changes.

---







*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1246#-:-LBN1HqXDZjjxjbE3FYf:b-o1zgqd)*

**Comment by arifogel** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoNxConversions.java, line 36 at r2](https://reviewable.io/reviews/batfish/batfish/1246#-LB2xe7H1eRDebJ80rqV:-LBN7DGR1YMXk3_vpw0Q:b-8zmngm) ([raw file](https://github.com/batfish/batfish/blob/a4e3293101a0a786547941b5b114cda7d7f664a7/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoNxConversions.java#L36)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Not on NXOS, apparently. Try the config in an emulator, and it'll pick the shutdown interface.

But also, in testing this I've found the behavior to be non-deterministic - it will change upon reboot. Seems like the only good thing to do here is pick something deterministically for batfish and warn.
</blockquote></details>

God help us.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1246)*

**Comment by arifogel** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1246#-:-LBN82TX8u--9J8nVw1i:bnfp4nl)*

**Pull request merged**
