### PR TITLE
Cisco ospf cost

### PR DESCRIPTION
**Pull request by dhalperi**
For #873.

This change is [Reviewable](https://reviewable.io/reviews/batfish/batfish/897)

### CODE REVIEW

**Comment by progwriter** [comment]
:lgtm:

---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/897#-:-L4cHtLG97_wkLhH-F3p:bnfp4nl)*

**Comment by arifogel** [comment]
Looks fine functionally. Some suggestions regarding tests.

---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java, line 117 at r1](https://reviewable.io:443/reviews/batfish/batfish/897#-L4cb8Dln9GXQHAHvnSu:-L4cb8Dln9GXQHAHvnSv:b-qfupzy) ([raw file](https://github.com/batfish/batfish/blob/7bd8e3f55a12f4d2f4a5c19e80f8d622dceb033a/projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java#L117)):*
> ```Java
>             .getSummaries()
>             .get(Prefix.parse("10.0.0.0/16"));
>     assertThat(summary.getAdvertise(), is(false));
> ```

Please add newline, description of what is being asserted.
Also, I generally prefer that you use feature matchers for things like this, i.e. `assertThat(summary, isAdvertise(false))` or `assertThat(summary, not(isAdvertise())` (see `InterfaceMatchers.isActive`)

---

*[projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java, line 129 at r1](https://reviewable.io:443/reviews/batfish/batfish/897#-L4cbsz-gwHqnyyjnNSI:-L4cbsz-gwHqnyyjnNSJ:bz2qol) ([raw file](https://github.com/batfish/batfish/blob/7bd8e3f55a12f4d2f4a5c19e80f8d622dceb033a/projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java#L129)):*
> ```Java
>             .getSummaries()
>             .get(Prefix.parse("10.0.0.0/16"));
>     assertThat(summary.getAdvertise(), is(true));
> ```

Please add newline, description of what is being asserted.
Also, I generally prefer that you use feature matchers for things like this, i.e. `assertThat(summay, isAdvertise(true))` or `assertThat(summary, isAdvertise())` (see `InterfaceMatchers.isActive`)
and `assertThat(summary, hasMetric(nullValue()))`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/897#-:-L4ccKO7EKBgWi6n782w:b6z6gkw)*

**Comment by sfraint** [comment]
Reviewed 12 of 13 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/897)*

**Comment by sfraint** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java, line 107 at r1](https://reviewable.io:443/reviews/batfish/batfish/897#-L4cdBj0VaDeEGFge9ZW:-L4cdBj0VaDeEGFge9ZX:b-myhwxj) ([raw file](https://github.com/batfish/batfish/blob/7bd8e3f55a12f4d2f4a5c19e80f8d622dceb033a/projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java#L107)):*
> ```Java
> 
>   @Test
>   public void testSummaryMetricCost() throws IOException {
> ```

Just a nitpick here, but `MetricCost` seems redundant; maybe call it something like `testOspfSummaryRouteMetric` or just `testOspfSummaryRoute` instead?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/897)*

**Comment by dhalperi** [comment]
Review status: 12 of 16 files reviewed at latest revision, 3 unresolved discussions.

---

*[projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java, line 107 at r1](https://reviewable.io:443/reviews/batfish/batfish/897#-L4cdBj0VaDeEGFge9ZW:-L4ckVZHlRPA3rWP72Tg:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/7bd8e3f55a12f4d2f4a5c19e80f8d622dceb033a/projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java#L107)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

Just a nitpick here, but `MetricCost` seems redundant; maybe call it something like `testOspfSummaryRouteMetric` or just `testOspfSummaryRoute` instead?
</blockquote></details>

Done.

---

*[projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java, line 117 at r1](https://reviewable.io:443/reviews/batfish/batfish/897#-L4cb8Dln9GXQHAHvnSu:-L4ckVEHumjN_RpH50h_:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/7bd8e3f55a12f4d2f4a5c19e80f8d622dceb033a/projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java#L117)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Please add newline, description of what is being asserted.
Also, I generally prefer that you use feature matchers for things like this, i.e. `assertThat(summary, isAdvertise(false))` or `assertThat(summary, not(isAdvertise())` (see `InterfaceMatchers.isActive`)
</blockquote></details>

Done.

---

*[projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java, line 129 at r1](https://reviewable.io:443/reviews/batfish/batfish/897#-L4cbsz-gwHqnyyjnNSI:-L4ckT1FU33F6Lj7Sl56:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/7bd8e3f55a12f4d2f4a5c19e80f8d622dceb033a/projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java#L129)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Please add newline, description of what is being asserted.
Also, I generally prefer that you use feature matchers for things like this, i.e. `assertThat(summay, isAdvertise(true))` or `assertThat(summary, isAdvertise())` (see `InterfaceMatchers.isActive`)
and `assertThat(summary, hasMetric(nullValue()))`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/897)*

**Comment by arifogel** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/897#-:-L4dKlTeOt3Zu6pxsSbL:bnfp4nl)*

**Pull request merged**
