### PR TITLE
Sonic: Reduce warnings

### PR DESCRIPTION
**Pull request by ratulm**
1. Add more ignored tables
2. Allow for FRR files starting with newlines
3. Ignore unknown properties in TACPLUS
4. Catch deserialization failures of a TABLE; log warning and do the rest.

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7850)* status: all files reviewed, 2 unresolved discussions (waiting on @ratulm)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/frr/FrrParser.g4, line 14 at r1](https://reviewable.io/reviews/batfish/batfish/7850#-MrPb8Y-4AflsAk9w5En:-MrPb8Y-4AflsAk9w5Eo:b82gjaq) ([raw file](https://github.com/batfish/batfish/blob/f116da5d161b87694237e836f400869455c85937/projects/batfish/src/main/antlr4/org/batfish/grammar/frr/FrrParser.g4#L14)):*
> ```ANTLR
> frr_configuration
> :
>   NEWLINE* statement+ EOF
> ```

May want to use nxos style for NEWLINE, F_Newline, and F_NewlineChar. This will reduce extraneous tokens.

If you do that, then you should use `NEWLINE?` here. And you may be able to eliminate the BLANK_LINE token.
___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/ConfigDb.java, line 137 at r1](https://reviewable.io/reviews/batfish/batfish/7850#-MrPbYeC61IcpOz0IR50:-MrPbYeC61IcpOz0IR51:b-qtdhgj) ([raw file](https://github.com/batfish/batfish/blob/f116da5d161b87694237e836f400869455c85937/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/ConfigDb.java#L137)):*
> ```Java
>           "POLICY_BINDING_TABLE",
>           "POLICY_SECTIONS_TABLE",
>           "POLICY_TABLE",
> ```

We will never extract anything with POLICY?

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7850)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/ConfigDb.java, line 137 at r1](https://reviewable.io/reviews/batfish/batfish/7850#-MrPbYeC61IcpOz0IR50:-MrPprl28zIWhHUu6ANK:bx4we5i) ([raw file](https://github.com/batfish/batfish/blob/f116da5d161b87694237e836f400869455c85937/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/ConfigDb.java#L137)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

We will never extract anything with POLICY?
</blockquote></details>

There is no documentation for these POLICY* tables here: https://github.com/Azure/SONiC/wiki/Configuration

What I see in the data I have appears QoS related, so ignoring for now. Will revive we understand more.

**Review by arifogel — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7850)* status: all files reviewed, 1 unresolved discussion (waiting on @ratulm)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/frr/FrrLexer.g4, line 857 at r2](https://reviewable.io/reviews/batfish/batfish/7850#-MrTxEis5h0oWt2gngR_:-MrTxEit485FE62-GwSa:b-gurz25) ([raw file](https://github.com/batfish/batfish/blob/f9b4c81d6b5f2239a4f755e7fd62e173132d02cc/projects/batfish/src/main/antlr4/org/batfish/grammar/frr/FrrLexer.g4#L857)):*
> ```ANTLR
> // Any number of newlines, allowing whitespace in between
> fragment
> F_Newline
> ```

looks good. optionally turn any `F_Newline+` or `F_Newline*` into `F_Newline` / `F_Newline?` respectively in rest of lexer, if present.

**Review by ratulm — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7850)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ratulm)

**Pull request merged**
