### PR TITLE
Transitions: mergeComposed rule for Or . Constraint

### PR DESCRIPTION
**Pull request by anothermattbrown**
Merge an Or composed with a Constraint by composing each disjunct with the Constraint. Limit to Ors with 10 or fewer disjuncts.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8290)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @anothermattbrown and @dhalperi)

___
*[`projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transitions.java` line 217 at r1](https://reviewable.io/reviews/batfish/batfish/8290#-N15ouW52VftDP4aLgh_:-N15ouW52VftDP4aLgha:bcq9843) ([raw file](https://github.com/batfish/batfish/blob/1f2ec83ecef7401ba7603e7fc48285f3f3561799/projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transitions.java#L217)):*
> ```Java
>       return eraseAndSet(var, add.getSourceBdd());
>     }
>     if (t1 instanceof Or && t2 instanceof Constraint) {
> ```

dumb Q, not blocking. Is there a reason not to also do it swapped?

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8290)* status: all files reviewed, 1 unresolved discussion (waiting on @anothermattbrown)

**Review by anothermattbrown — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8290)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[`projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transitions.java` line 217 at r1](https://reviewable.io/reviews/batfish/batfish/8290#-N15ouW52VftDP4aLgh_:-N15pEse4XsLH5GoEBW9:b-hutwyb) ([raw file](https://github.com/batfish/batfish/blob/1f2ec83ecef7401ba7603e7fc48285f3f3561799/projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transitions.java#L217)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

dumb Q, not blocking. Is there a reason not to also do it swapped?
</blockquote></details>

no, I'm just focused on a particular use case at the moment :)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8290)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi)

**Pull request merged**
