### PR TITLE
FortiOS: secondaryip

### PR DESCRIPTION
**Pull request by sfraint**
Parsing, extraction, and conversion for `secondaryip`.

### CODE REVIEW

**Review by corinaminer — COMMENTED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6870)* status: all files reviewed, 5 unresolved discussions (waiting on @arifogel and @sfraint)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_interface.g4, line 17 at r1](https://reviewable.io/reviews/batfish/batfish/6870#-MXiL3AH0NnCn4WZkwAS:-MXiL3AH0NnCn4WZkwAT:bzhcyaj) ([raw file](https://github.com/batfish/batfish/blob/db884575e85c9abf871fedf29d56b0d522f92182/projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_interface.g4#L17)):*
> ```ANTLR
> csiec_secondaryip: SECONDARYIP newline csiecsip_edit* END newline;
> 
> csiecsip_edit: EDIT sip_number newline csiecsipe_set* NEXT newline;
> ```

we should probably make a habit of making an edit-stanza-line rule (`csiecsipe`) that matches `csiecsipe_set | (UNSET | SELECT |...) unimplemented`
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 698 at r1](https://reviewable.io/reviews/batfish/batfish/6870#-MXiPjo80FlgCYQkjwiG:-MXiPjo80FlgCYQkjwiH:b-a91vgk) ([raw file](https://github.com/batfish/batfish/blob/db884575e85c9abf871fedf29d56b0d522f92182/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L698)):*
> ```Java
>         number
>             .map(Objects::toString)
>             .map(i -> _currentInterface.getSecondaryip().get(i))
> ```

I think we need to be cloning this. If `_secondaryIp` is not enabled, `_currentInterface.getSecondaryip()` may not be empty, but its contents should not be modified.

In general, regardless of the specific reasons that edit blocks can be rejected, it seems safer to clone by default in case of future changes to the edit block validation logic.
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 741 at r1](https://reviewable.io/reviews/batfish/batfish/6870#-MXiQXipETg7mYHM0zAA:-MXiQXipETg7mYHM0zAB:b-gastyx) ([raw file](https://github.com/batfish/batfish/blob/db884575e85c9abf871fedf29d56b0d522f92182/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L741)):*
> ```Java
> 
>     ConcreteInterfaceAddress sip = toConcreteInterfaceAddress(ctx.ip);
>     if (_currentInterface.getIp().getIp().equals(sip.getIp())) {
> ```

nit: could use `pip.getIp()`
___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/Interface.java, line 187 at r1](https://reviewable.io/reviews/batfish/batfish/6870#-MXiREfI5HY-zfeh9g1S:-MXiREfI5HY-zfeh9g1T:b2zk20s) ([raw file](https://github.com/batfish/batfish/blob/db884575e85c9abf871fedf29d56b0d522f92182/projects/batfish/src/main/java/org/batfish/representation/fortios/Interface.java#L187)):*
> ```Java
> 
>   public void setSecondaryIp(Boolean secondaryIp) {
>     _secondaryIp = secondaryIp;
> ```

Should this clear `_secondaryip` if setting to false? If not, the new conversion code needs to check if `_secondaryIp` is enabled and make `secondaryAddresses` an empty list if not.
___
*[projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/iface, line 44 at r1](https://reviewable.io/reviews/batfish/batfish/6870#-MXiU-b88HQM9IFpqsvm:-MXiU-b88HQM9IFpqsvn:bubodcv) ([raw file](https://github.com/batfish/batfish/blob/db884575e85c9abf871fedf29d56b0d522f92182/projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/iface#L44)):*
> ```
>         set interface port1
>         set vrf 31
>         set secondary-IP disable
> ```

for this one, could you expand it to enable `secondary-IP`, set a secondary IP, and then disable `secondary-IP`? Then in extraction and conversion tests, check the secondary IPs. Should definitely be empty in VI; i'm not sure if they should be populated in VS, depends on whether secondary IPs persevere through disabling and reenabling `secondary-IP`.

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6870)* status: all files reviewed, 5 unresolved discussions (waiting on @arifogel, @corinaminer, and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 698 at r1](https://reviewable.io/reviews/batfish/batfish/6870#-MXiPjo80FlgCYQkjwiG:-MXiXywN0nJjhN7gxAU8:b7anmnw) ([raw file](https://github.com/batfish/batfish/blob/db884575e85c9abf871fedf29d56b0d522f92182/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L698)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

I think we need to be cloning this. If `_secondaryIp` is not enabled, `_currentInterface.getSecondaryip()` may not be empty, but its contents should not be modified.

In general, regardless of the specific reasons that edit blocks can be rejected, it seems safer to clone by default in case of future changes to the edit block validation logic.
</blockquote></details>

good call

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6870)* status: 4 of 9 files reviewed, 3 unresolved discussions (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_interface.g4, line 17 at r1](https://reviewable.io/reviews/batfish/batfish/6870#-MXiL3AH0NnCn4WZkwAS:-MXia0er4v3DIZn--Uom:b-7tfmjp) ([raw file](https://github.com/batfish/batfish/blob/db884575e85c9abf871fedf29d56b0d522f92182/projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_interface.g4#L17)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

we should probably make a habit of making an edit-stanza-line rule (`csiecsipe`) that matches `csiecsipe_set | (UNSET | SELECT |...) unimplemented`
</blockquote></details>

added
___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/Interface.java, line 187 at r1](https://reviewable.io/reviews/batfish/batfish/6870#-MXiREfI5HY-zfeh9g1S:-MXiYu5qA4itx3FxISp_:b-yjw7d2) ([raw file](https://github.com/batfish/batfish/blob/db884575e85c9abf871fedf29d56b0d522f92182/projects/batfish/src/main/java/org/batfish/representation/fortios/Interface.java#L187)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Should this clear `_secondaryip` if setting to false? If not, the new conversion code needs to check if `_secondaryIp` is enabled and make `secondaryAddresses` an empty list if not.
</blockquote></details>

it should not be cleared - fixed
___
*[projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/iface, line 44 at r1](https://reviewable.io/reviews/batfish/batfish/6870#-MXiU-b88HQM9IFpqsvm:-MXiYwvQ3iMPIugk3mqU:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/db884575e85c9abf871fedf29d56b0d522f92182/projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/iface#L44)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

for this one, could you expand it to enable `secondary-IP`, set a secondary IP, and then disable `secondary-IP`? Then in extraction and conversion tests, check the secondary IPs. Should definitely be empty in VI; i'm not sure if they should be populated in VS, depends on whether secondary IPs persevere through disabling and reenabling `secondary-IP`.
</blockquote></details>

done

**Review by corinaminer — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6870#-:-MXjQZ0b1NbkmP76sAQU:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Review by sfraint — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6870)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Review by sfraint — COMMENTED** [review]
> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6870)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Pull request merged**
