### PR TITLE
No  BGP  neighbor 

### PR DESCRIPTION
**Pull request by jawyoonis**
-  No neighbor under `ipv4 Unicas family address` was not parse for no neigbor for `ipv6`
- So this has been fixed

### CODE REVIEW

**Review by ratulm — COMMENTED** [review]
> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6647)* status: 1 of 140 files reviewed, 2 unresolved discussions (waiting on @jawyoonis)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6647#-MTw8OA76x8xc7V2IJIe:-MTw8OA76x8xc7V2IJIf:bi83dv8) (no related file):*
Please remove all these files -- they either do not belong in source control  or shouldn't be modified 
 - .idea/*
 - projects/.idea/*
 - projects/batfish/gen
 - tests/parsing-tests/*.testout

In essence, the only files that should remain are
  - cumulusfrr_bgp.g4
  - cumulusfrrconfigurationbuilder.java
  - cumulusfrrgrammartest.java

---
___
*[projects/batfish/src/main/java/org/batfish/representation/cumulus/BgpNeighborIpv4UnicastAddressFamily.java, line 24 at r3](https://reviewable.io/reviews/batfish/batfish/6647#-MTw9VLC0m-gnSqf6l_E:-MTw9VLC0m-gnSqf6l_F:bv3k2qe) ([raw file](https://github.com/batfish/batfish/blob/165087051c854038403569419e481dc5ca5912e4/projects/batfish/src/main/java/org/batfish/representation/cumulus/BgpNeighborIpv4UnicastAddressFamily.java#L24)):*
> ```Java
>   }
> 
>   public BgpNeighborIpv4UnicastAddressFamily setActivated(@Nullable Boolean activated) {
> ```

Why this change?

**Review by ratulm — COMMENTED** [review]
> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6647)* status: 2 of 140 files reviewed, 5 unresolved discussions (waiting on @jawyoonis)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrr_bgp.g4, line 368 at r3](https://reviewable.io/reviews/batfish/batfish/6647#-MTwB-u53Xie_qQ8eIEy:-MTwB-u53Xie_qQ8eIEz:bq9evu4) ([raw file](https://github.com/batfish/batfish/blob/165087051c854038403569419e481dc5ca5912e4/projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrr_bgp.g4#L368)):*
> ```ANTLR
> 
> :
>   NO NEIGHBOR (ip=IP_ADDRESS | ip=IPV6_ADDRESS | name = word)
> ```

variables for both IP_ADDRESS and IPV6_ADDRESS are named `ip`. should be different names.
___
*[projects/batfish/src/main/java/org/batfish/grammar/cumulus_frr/CumulusFrrConfigurationBuilder.java, line 658 at r3](https://reviewable.io/reviews/batfish/batfish/6647#-MTwBa-r4XeZcnWI8auX:-MTwBa-r4XeZcnWI8auY:b6cbsou) ([raw file](https://github.com/batfish/batfish/blob/165087051c854038403569419e481dc5ca5912e4/projects/batfish/src/main/java/org/batfish/grammar/cumulus_frr/CumulusFrrConfigurationBuilder.java#L658)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
>       if (ctx.ip != null) {
>         name = ctx.ip.getText();
>       } else if (ctx.name != null) {
>         name = ctx.name.getText();
>       } else {
>         throw new BatfishException("neightbor name or address");
>       }
> ```
</details>

if you introduce a new variable name for ipv6 address in the grammar, another if statement will be needed here. 
___
*[projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java, line 279 at r3](https://reviewable.io/reviews/batfish/batfish/6647#-MTwA8z0DhQ69guSsdV3:-MTwA8z0DhQ69guSsdV4:b-9qfnn9) ([raw file](https://github.com/batfish/batfish/blob/165087051c854038403569419e481dc5ca5912e4/projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java#L279)):*
> ```Java
>         "address-family ipv4 unicast",
>         "redistribute connected",
>         "no neighbor N activate",
> ```

since not being activated is the default, it might be a good idea to have a line that activates the neighbor before this one. that will make sure that the deactivation is indeed happening.

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6647)* status: 2 of 140 files reviewed, 5 unresolved discussions (waiting on @jawyoonis)

___
*[projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java, line 279 at r3](https://reviewable.io/reviews/batfish/batfish/6647#-MTwA8z0DhQ69guSsdV3:-MTwBuqw5Bgg8mPcRtrW:bg4kj8j) ([raw file](https://github.com/batfish/batfish/blob/165087051c854038403569419e481dc5ca5912e4/projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java#L279)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

since not being activated is the default, it might be a good idea to have a line that activates the neighbor before this one. that will make sure that the deactivation is indeed happening. 
</blockquote></details>

also, since the grammar you added allows for other types of neighbors (ipv4 and ipv6 address, and not just names), perhaps add those neighbors here too.

**Comment by jawyoonis** [comment]
___
*[projects/batfish/src/main/java/org/batfish/grammar/cumulus_frr/CumulusFrrConfigurationBuilder.java, line 658 at r3](https://reviewable.io/reviews/batfish/batfish/6647#-MTwBa-r4XeZcnWI8auX:-MTwDi731X3VO3pbIaTU:b699dtt) ([raw file](https://github.com/batfish/batfish/blob/165087051c854038403569419e481dc5ca5912e4/projects/batfish/src/main/java/org/batfish/grammar/cumulus_frr/CumulusFrrConfigurationBuilder.java#L658)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

> ```
>       if (ctx.ip != null) {
>         name = ctx.ip.getText();
>       } else if (ctx.name != null) {
>         name = ctx.name.getText();
>       } else {
>         throw new BatfishException("neightbor name or address");
>       }
> ```
if you introduce a new variable name for ipv6 address in the grammar, another if statement will be needed here. 
</blockquote></details>

i changed ipv6 and also added else if statement in the code to check if that variable is used.

**Comment by jawyoonis** [comment]
___
*[projects/batfish/src/main/java/org/batfish/representation/cumulus/BgpNeighborIpv4UnicastAddressFamily.java, line 24 at r3](https://reviewable.io/reviews/batfish/batfish/6647#-MTw9VLC0m-gnSqf6l_E:-MTwBeHg5wN9jn2SgOCq:b-53wxnl) ([raw file](https://github.com/batfish/batfish/blob/165087051c854038403569419e481dc5ca5912e4/projects/batfish/src/main/java/org/batfish/representation/cumulus/BgpNeighborIpv4UnicastAddressFamily.java#L24)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

Why this change? 
</blockquote></details>

I am not sure why this changed. I was looking into them.

**Comment by jawyoonis** [comment]
___
*[projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java, line 279 at r3](https://reviewable.io/reviews/batfish/batfish/6647#-MTwA8z0DhQ69guSsdV3:-MTwESjO6IpFnfPMTVcE:b-imvjdi) ([raw file](https://github.com/batfish/batfish/blob/165087051c854038403569419e481dc5ca5912e4/projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java#L279)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

also, since the grammar you added allows for other types of neighbors (ipv4 and ipv6 address, and not just names), perhaps add those neighbors here too. 
</blockquote></details>

u meant another assert statement before the deactivation happens ?

**Comment by jawyoonis** [comment]
___
*[projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java, line 279 at r3](https://reviewable.io/reviews/batfish/batfish/6647#-MTwA8z0DhQ69guSsdV3:-MTwEgFICb3MigHarXg9:b-o8boww) ([raw file](https://github.com/batfish/batfish/blob/165087051c854038403569419e481dc5ca5912e4/projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java#L279)):*
<details><summary><i>Previously, jawyoonis wrote…</i></summary><blockquote>

u meant another assert statement before the deactivation happens ?
</blockquote></details>

I did not understand what you meant for the second statement?

**Comment by jawyoonis** [comment]
*[a discussion](https://reviewable.io/reviews/batfish/batfish/6647#-MTw8OA76x8xc7V2IJIe:-MTwFGEM07UpZByGyOgl:bnyfqjh) (no related file):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

Please remove all these files -- they either do not belong in source control  or shouldn't be modified 
 - .idea/*
 - projects/.idea/*
 - projects/batfish/gen
 - tests/parsing-tests/*.testout

In essence, the only files that should remain are
  - cumulusfrr_bgp.g4
  - cumulusfrrconfigurationbuilder.java
  - cumulusfrrgrammartest.java
</blockquote></details>

I  am not sure the first four files. I do not know where they came from. I may have committed them by accident.

---

**Comment by jawyoonis** [comment]
___
*[projects/batfish/src/main/java/org/batfish/representation/cumulus/BgpNeighborIpv4UnicastAddressFamily.java, line 24 at r3](https://reviewable.io/reviews/batfish/batfish/6647#-MTw9VLC0m-gnSqf6l_E:-MTwGLccDrcK5wd6K0KO:bvisxo8) ([raw file](https://github.com/batfish/batfish/blob/165087051c854038403569419e481dc5ca5912e4/projects/batfish/src/main/java/org/batfish/representation/cumulus/BgpNeighborIpv4UnicastAddressFamily.java#L24)):*
<details><summary><i>Previously, jawyoonis wrote…</i></summary><blockquote>

I am not sure why this changed. I was looking into them.
</blockquote></details>

i added new functionality deactivate but we agreed on that activate will work. so i may have removed this method but nothing changed its content

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6647)* status: 2 of 140 files reviewed, 4 unresolved discussions (waiting on @jawyoonis and @ratulm)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6647#-MTw8OA76x8xc7V2IJIe:-MTwGUHS0GDOa9i3QdvD:b-wooztn) (no related file):*
<details><summary><i>Previously, jawyoonis wrote…</i></summary><blockquote>

I  am not sure the first four files. I do not know where they came from. I may have committed them by accident.
</blockquote></details>

Ok, please remove

---
___
*[projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java, line 279 at r3](https://reviewable.io/reviews/batfish/batfish/6647#-MTwA8z0DhQ69guSsdV3:-MTwGrWl3LKuPhBYKFq2:bmgm7hb) ([raw file](https://github.com/batfish/batfish/blob/165087051c854038403569419e481dc5ca5912e4/projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java#L279)):*
<details><summary><i>Previously, jawyoonis wrote…</i></summary><blockquote>

I did not understand what you meant for the second statement?
</blockquote></details>


I was suggesting that you change the config lines to 

```
 router bgp 1
      neighbor N interface description N
       address-family ipv4 unicast
            redistribute connected
            neighbor N activate.      --> added line
             no neighbor N activate
      exit-address-family
```

**Comment by jawyoonis** [comment]
___
*[projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java, line 279 at r3](https://reviewable.io/reviews/batfish/batfish/6647#-MTwA8z0DhQ69guSsdV3:-MTwHj7a3AZbKZhNfunq:bgx8rag) ([raw file](https://github.com/batfish/batfish/blob/a91df94e5dc119c965903c7538b00a0f27ce3709/projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java#L279)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>


I was suggesting that you change the config lines to 

```
 router bgp 1
      neighbor N interface description N
       address-family ipv4 unicast
            redistribute connected
            neighbor N activate.      --> added line
             no neighbor N activate
      exit-address-family
```

</blockquote></details>

oh i got  u now

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6647)* status: 1 of 140 files reviewed, 7 unresolved discussions (waiting on @jawyoonis and @ratulm)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrr_bgp.g4, line 21 at r4](https://reviewable.io/reviews/batfish/batfish/6647#-MTwMUsw8QX9R5LCI9Gl:-MTwMUsw8QX9R5LCI9Gm:b-t4mum9) ([raw file](https://github.com/batfish/batfish/blob/5fe5c32091762aae2d4837610eaf8f5e4165e53b/projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrr_bgp.g4#L21)):*
> ```ANTLR
>   | sb_redistribute
>   | sbafi_neighbor
>   | sbafi_no_neighbor
> ```

Keep the parser LL1: This needs to be under `sb_no`, probably as `sbafino_neighbor`.
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrr_bgp.g4, line 136 at r4](https://reviewable.io/reviews/batfish/batfish/6647#-MTwM3mWEJTSFkD2MNzr:-MTwM3mWEJTSFkD2MNzs:b-3adqae) ([raw file](https://github.com/batfish/batfish/blob/5fe5c32091762aae2d4837610eaf8f5e4165e53b/projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrr_bgp.g4#L136)):*
> ```ANTLR
>     | sbafi_network
>     | sbafi_neighbor
>     | sbafi_no_neighbor
> ```

Keep the parser LL1: Keep this `sbafi_no`, and make `sbafino_neighbor` a rule underneath that, and `sbafinon_activate` a rule under that.
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrr_bgp.g4, line 372 at r4](https://reviewable.io/reviews/batfish/batfish/6647#-MTwM9xA-odJCmSIwvga:-MTwM9xB4aEhaHz7tTAJ:bkvo4y8) ([raw file](https://github.com/batfish/batfish/blob/5fe5c32091762aae2d4837610eaf8f5e4165e53b/projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrr_bgp.g4#L372)):*
> ```ANTLR
>    sbafi_no_activate
>    )
>    NEWLINE
> ```

this newline goes with `sbafinon_activate`. Putting required text after a child rule generally breaks parser recovery.

**Comment by jawyoonis** [comment]
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrr_bgp.g4, line 21 at r4](https://reviewable.io/reviews/batfish/batfish/6647#-MTwMUsw8QX9R5LCI9Gl:-MTxO4_5DvfOeUYfol0F:b4vgbs0) ([raw file](https://github.com/batfish/batfish/blob/5fe5c32091762aae2d4837610eaf8f5e4165e53b/projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrr_bgp.g4#L21)):*
> sb_no

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6647)* status: 1 of 140 files reviewed, 6 unresolved discussions (waiting on @dhalperi, @jawyoonis, and @ratulm)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrr_bgp.g4, line 21 at r4](https://reviewable.io/reviews/batfish/batfish/6647#-MTwMUsw8QX9R5LCI9Gl:-MU0LIa43w8ftPFWfP-2:b4p42ur) ([raw file](https://github.com/batfish/batfish/blob/5fe5c32091762aae2d4837610eaf8f5e4165e53b/projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrr_bgp.g4#L21)):*
<details><summary><i>Previously, jawyoonis wrote…</i></summary><blockquote>

> sb_no
</blockquote></details>

@jawyoonis - in case Dan's suggestion wasn't clear, he is recommending that the chain of rules should be 
s_bgp -> sb_no -> sbafino_neighbor -> sbafinon_activate

while functionally it is the similar to what you have, the suggested chain has better performance. essentially, you are picking off one token at a time.
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrr_bgp.g4, line 136 at r4](https://reviewable.io/reviews/batfish/batfish/6647#-MTwM3mWEJTSFkD2MNzr:-MU0MW8R77M-BRfs2Eg7:b-vy842o) ([raw file](https://github.com/batfish/batfish/blob/5fe5c32091762aae2d4837610eaf8f5e4165e53b/projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrr_bgp.g4#L136)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Keep the parser LL1: Keep this `sbafi_no`, and make `sbafino_neighbor` a rule underneath that, and `sbafinon_activate` a rule under that.
</blockquote></details>

@jawyoonis - the suggestion here is to make the following rule chain
 sbag_ipv4_unicast -> sbafi_no -> sbafino_neighbor -> sbafinon_activate
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrr_bgp.g4, line 372 at r4](https://reviewable.io/reviews/batfish/batfish/6647#-MTwM9xA-odJCmSIwvga:-MU0NATq6tcMy_eX6Te2:b-72bvfx) ([raw file](https://github.com/batfish/batfish/blob/5fe5c32091762aae2d4837610eaf8f5e4165e53b/projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrr_bgp.g4#L372)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

this newline goes with `sbafinon_activate`. Putting required text after a child rule generally breaks parser recovery.
</blockquote></details>

@jawyoonis - i assume that this suggestion is clear. (this is a slightly different from what is happening in the non-no version of activate, so understandable that you did it this way.)

**Pull request closed without merging**
