### PR TITLE
toString for VendorFamily, so it can be inserted into properties table

### PR DESCRIPTION
**Pull request by ratulm**

### CODE REVIEW

**Comment by arifogel** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/vendor_family/VendorFamilyTest.java, line 15 at r3](https://reviewable.io/reviews/batfish/batfish/1571#-LE9upWe7R4j96iyPAwM:-LE9upWf47U_4dxe8gvu:b-p4kiqn) ([raw file](https://github.com/batfish/batfish/blob/1ece0424cf068cb0b5527af9f2c9ae298cc48882/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/vendor_family/VendorFamilyTest.java#L15)):*
> ```Java
> 
>   @Test
>   public void toStringMulitipleFamilies() {
> ```

When does this happen?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1571)*

**Comment by ratulm** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/vendor_family/VendorFamilyTest.java, line 15 at r3](https://reviewable.io/reviews/batfish/batfish/1571#-LE9upWe7R4j96iyPAwM:-LEANobN5gEblN2zJYx1:b-46nsap) ([raw file](https://github.com/batfish/batfish/blob/1ece0424cf068cb0b5527af9f2c9ae298cc48882/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/vendor_family/VendorFamilyTest.java#L15)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

When does this happen?
</blockquote></details>

I don't think it happens but the structure of the class permits it. So,  I just made toString compatible with it.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1571)*

**Comment by arifogel** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/vendor_family/VendorFamilyTest.java, line 15 at r3](https://reviewable.io/reviews/batfish/batfish/1571#-LE9upWe7R4j96iyPAwM:-LEAY4P83hIm1_dy90E7:bli00vz) ([raw file](https://github.com/batfish/batfish/blob/1ece0424cf068cb0b5527af9f2c9ae298cc48882/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/vendor_family/VendorFamilyTest.java#L15)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

I don't think it happens but the structure of the class permits it. So,  I just made toString compatible with it.
</blockquote></details>

Future-proof I guess

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1571)*

**Comment by arifogel** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1571#-:-LEAY7Py3xk_RBPj1mji:bnfp4nl)*

**Pull request merged**
