### PR TITLE
Added version arg for batfish

### PR DESCRIPTION
**Pull request by sfraint**
* Added `-version` arg for `batfish`
* Added z3 version to `allinone` `-version`

### CODE REVIEW

**Comment by dhalperi** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/allinone/src/main/java/org/batfish/allinone/config/Settings.java, line 192 at r1](https://reviewable.io/reviews/batfish/batfish/1423#-LCoYRvP3wcdqAx8-YIu:-LCoYRvP3wcdqAx8-YIv:b-1ohicn) ([raw file](https://github.com/batfish/batfish/blob/89a77e3d228c33c55e383e8f2f446286abd6c64d/projects/allinone/src/main/java/org/batfish/allinone/config/Settings.java#L192)):*
> ```Java
>     if (getBooleanOptionValue(ARG_VERSION)) {
>       System.out.printf("Batfish version: %s\n", Version.getVersion());
>       System.out.printf("Z3 version: %s\n", com.microsoft.z3.Version.getString());
> ```

can this crash or fail in any way if the JNI bindings are not present? if so, need to handle gracefully.

Can we move all this into the common protocol somehow -- seems like we should have one uniform place to get the "complete" version string.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1423)*

**Comment by sfraint** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/allinone/src/main/java/org/batfish/allinone/config/Settings.java, line 192 at r1](https://reviewable.io/reviews/batfish/batfish/1423#-LCoYRvP3wcdqAx8-YIu:-LCocLVw-fq2D-cUDXW5:bg5lbki) ([raw file](https://github.com/batfish/batfish/blob/89a77e3d228c33c55e383e8f2f446286abd6c64d/projects/allinone/src/main/java/org/batfish/allinone/config/Settings.java#L192)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

can this crash or fail in any way if the JNI bindings are not present? if so, need to handle gracefully.

Can we move all this into the common protocol somehow -- seems like we should have one uniform place to get the "complete" version string.
</blockquote></details>

Done; how does that look?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1423)*

**Comment by dhalperi** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/Version.java, line 73 at r2](https://reviewable.io/reviews/batfish/batfish/1423#-LCofooq8tWquslgy6S3:-LCofooq8tWquslgy6S4:bdxcpyf) ([raw file](https://github.com/batfish/batfish/blob/28eab7e3101aa5bba78e0f6152b7ff92c8429254/projects/batfish-common-protocol/src/main/java/org/batfish/common/Version.java#L73)):*
> ```Java
>     try {
>       return com.microsoft.z3.Version.getString();
>     } catch (Exception e) {
> ```

Have you tested this? Make sure it works in practice.

(For context, my hackles are up because I have this ancestral memory that makes me think a lot of the native errors might not be caught by `Exception`)

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1423)*

**Comment by sfraint** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/Version.java, line 73 at r2](https://reviewable.io/reviews/batfish/batfish/1423#-LCofooq8tWquslgy6S3:-LCpCI5G3SFH1intAQ3B:b-vdjm69) ([raw file](https://github.com/batfish/batfish/blob/28eab7e3101aa5bba78e0f6152b7ff92c8429254/projects/batfish-common-protocol/src/main/java/org/batfish/common/Version.java#L73)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Have you tested this? Make sure it works in practice.

(For context, my hackles are up because I have this ancestral memory that makes me think a lot of the native errors might not be caught by `Exception`)
</blockquote></details>

Looks like if `z3` is missing an `UnsatisfiedLinkError` occurs.  Catching that as well now.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1423)*

**Comment by dhalperi** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/Version.java, line 73 at r2](https://reviewable.io/reviews/batfish/batfish/1423#-LCofooq8tWquslgy6S3:-LCpDOoU37euY66h4lHS:b5ylhhj) ([raw file](https://github.com/batfish/batfish/blob/28eab7e3101aa5bba78e0f6152b7ff92c8429254/projects/batfish-common-protocol/src/main/java/org/batfish/common/Version.java#L73)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

Looks like if `z3` is missing an `UnsatisfiedLinkError` occurs.  Catching that as well now.
</blockquote></details>

Cool! Looks like we should just `catch (Throwable` then, because `Throwable` is a common ancestor of `Exception` and `Error`. I think actually that might always work for any of these weird `Error` classes.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1423)*

**Comment by dhalperi** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1423)*

**Comment by anothermattbrown** [comment]
Reviewed 4 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1423)*

**Comment by anothermattbrown** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1423)*

**Comment by arifogel** [comment]
Reviewed 4 of 5 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/allinone/pom.xml, line 31 at r3](https://reviewable.io/reviews/batfish/batfish/1423#-LCpEjMqA0W7SK3mHEBV:-LCpEjMr-ix5vB7DnSHT:bucol0h) ([raw file](https://github.com/batfish/batfish/blob/3b19436c034d2320b076c677719b8956f8e86452/projects/allinone/pom.xml#L31)):*
> ```XML
>                   <ignoredUnusedDeclaredDependency>org.slf4j:slf4j-jdk14
>                   </ignoredUnusedDeclaredDependency>
>                   <ignoredUnusedDeclaredDependency>org.batfish:question
> ```

Is this result of autoformat? Looks bizarre.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/Version.java, line 73 at r2](https://reviewable.io/reviews/batfish/batfish/1423#-LCofooq8tWquslgy6S3:-LCpF-1iCk9JXpxKSI_t:bw6j05u) ([raw file](https://github.com/batfish/batfish/blob/28eab7e3101aa5bba78e0f6152b7ff92c8429254/projects/batfish-common-protocol/src/main/java/org/batfish/common/Version.java#L73)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Cool! Looks like we should just `catch (Throwable` then, because `Throwable` is a common ancestor of `Exception` and `Error`. I think actually that might always work for any of these weird `Error` classes.
</blockquote></details>

Why return UNKNOWN_VERSION? Why not just say it isn't installed or the library could not be found?

By the way, the error you end up catching when the library cannot be loaded is usually wrong.
This is because the fine folks who maintain Z3 java bindings are doing some funky exception catching themselves.
In particular, multiple possible names for the libraries are tried. But if loading fails, only the last possible name is reported as being missing. I suppose this isn't important if you aren't leaking that exception message, but thought you might like to know.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1423)*

**Comment by sfraint** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/allinone/pom.xml, line 31 at r3](https://reviewable.io/reviews/batfish/batfish/1423#-LCpEjMqA0W7SK3mHEBV:-LCpGQuL-Brc8waH7EJM:bua88q7) ([raw file](https://github.com/batfish/batfish/blob/3b19436c034d2320b076c677719b8956f8e86452/projects/allinone/pom.xml#L31)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Is this result of autoformat? Looks bizarre.
</blockquote></details>

It is, may just be splitting to multiple lines because the line length was getting up there.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/Version.java, line 73 at r2](https://reviewable.io/reviews/batfish/batfish/1423#-LCofooq8tWquslgy6S3:-LCpGr9HCObQ6kH5k07n:bx4nh62) ([raw file](https://github.com/batfish/batfish/blob/28eab7e3101aa5bba78e0f6152b7ff92c8429254/projects/batfish-common-protocol/src/main/java/org/batfish/common/Version.java#L73)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Why return UNKNOWN_VERSION? Why not just say it isn't installed or the library could not be found?

By the way, the error you end up catching when the library cannot be loaded is usually wrong.
This is because the fine folks who maintain Z3 java bindings are doing some funky exception catching themselves.
In particular, multiple possible names for the libraries are tried. But if loading fails, only the last possible name is reported as being missing. I suppose this isn't important if you aren't leaking that exception message, but thought you might like to know.
</blockquote></details>

Done and done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1423)*

**Comment by dhalperi** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1423)*

**Comment by dhalperi** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1423#-:-LCpIj-z1RBPXgV9VxvI:bnfp4nl)*

**Pull request merged**
