### PR TITLE
HSRP: priority-update support

### PR DESCRIPTION
**Pull request by sfraint**
Add initial VI support for updating Hot Standby Router Protocol (HSRP) priority based on tracking interface active status.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7064)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @arifogel and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7064#-McBX0ms40lY-fWvJ8PQ:-McBX0ms40lY-fWvJ8PR:b-vqdfrm) (no related file):*
FYI I think I'll let @arifogel review this one - seems more up his alley. A few nits that jumped out.

---
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/IpOwners.java, line 369 at r1](https://reviewable.io/reviews/batfish/batfish/7064#-McBX6xs7qipt9fINf0U:-McBX6xs7qipt9fINf0V:ba5t0o9) ([raw file](https://github.com/batfish/batfish/blob/5ac79f098cea17b6469a32735b92fd9026cf7284/projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/IpOwners.java#L369)):*
> ```Java
>               TrackMethod trackMethod = trackMethods.get(trackName);
>               if (trackMethod != null && trackMethod.evaluate(c)) {
>                 priority.set(action.apply(new HsrpPriorityEvaluator(priority.get())));
> ```

Did you consider putting the priority in the evaluator, and persisting the evaluator?

Then you can get it at the end, and you don't need this atomic business just because you're using a lambda.

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7064)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @arifogel and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7064#-McBX0ms40lY-fWvJ8PQ:-McBXQJMBUac2BGQLtP5:b-rfbfgy) (no related file):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

FYI I think I'll let @arifogel review this one - seems more up his alley. A few nits that jumped out.
</blockquote></details>

-reviewer:@dhalperi

---

**Review by arifogel — COMMENTED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7064)* status: all files reviewed, 4 unresolved discussions (waiting on @sfraint)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/GenericTrackActionVisitor.java, line 6 at r1](https://reviewable.io/reviews/batfish/batfish/7064#-McG46JT5mDSx9IXXD_p:-McG46JT5mDSx9IXXD_q:bnkno95) ([raw file](https://github.com/batfish/batfish/blob/5ac79f098cea17b6469a32735b92fd9026cf7284/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/GenericTrackActionVisitor.java#L6)):*
> ```Java
> public interface GenericTrackActionVisitor<R> {
> 
>   default R visit(TrackAction trackAction) {
> ```

What is the purpose of this? How is this more concise than inlining its definition (which results in fewer stack frames too)?
Also, doesn't seem like it's used anywhere.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/TrackAction.java, line 9 at r1](https://reviewable.io/reviews/batfish/batfish/7064#-McG4fQTA3UrlN9sVSCk:-McG4_rJ15dvHFoFNzNA:b6yemnd) ([raw file](https://github.com/batfish/batfish/blob/5ac79f098cea17b6469a32735b92fd9026cf7284/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/TrackAction.java#L9)):*
> ```Java
> @JsonTypeInfo(use = JsonTypeInfo.Id.CLASS, property = "class")
> public interface TrackAction extends Serializable {
>   <R> R apply(GenericTrackActionVisitor<R> visitor);
> ```

nit: the standard term is `accept` for a visitor, not `apply`.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/TrackMethod.java, line 15 at r1](https://reviewable.io/reviews/batfish/batfish/7064#-McG5KEx1_TbS5fwuDt8:-McG5KEx1_TbS5fwuDt9:b-hhis4g) ([raw file](https://github.com/batfish/batfish/blob/5ac79f098cea17b6469a32735b92fd9026cf7284/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/TrackMethod.java#L15)):*
> ```Java
> 
>   /** Evaluate if this track method is triggered on the specified {@link Configuration}. */
>   boolean evaluate(Configuration configuration);
> ```

Why have an evaluate function here, but use visitors for evaluation elsewhere? Is it just because you only have one use case now (evaluate)?

I think in general we prefer to keep dynamic execution code like this in visitors (like an evaluator) to aid in alternate analyses like symbolic execution, plus simplification and caching.

Definitely not meant to be blocking, but something to consider.

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7064)* status: 4 of 10 files reviewed, 4 unresolved discussions (waiting on @arifogel, @dhalperi, and @sfraint)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/IpOwners.java, line 369 at r1](https://reviewable.io/reviews/batfish/batfish/7064#-McBX6xs7qipt9fINf0U:-McGEuA_8N5gSRo5Af80:bvnrpcm) ([raw file](https://github.com/batfish/batfish/blob/5ac79f098cea17b6469a32735b92fd9026cf7284/projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/IpOwners.java#L369)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Did you consider putting the priority in the evaluator, and persisting the evaluator?

Then you can get it at the end, and you don't need this atomic business just because you're using a lambda.
</blockquote></details>

updated
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/GenericTrackActionVisitor.java, line 6 at r1](https://reviewable.io/reviews/batfish/batfish/7064#-McG46JT5mDSx9IXXD_p:-McGFQTs3t2ri6klVDQ0:bozszii) ([raw file](https://github.com/batfish/batfish/blob/5ac79f098cea17b6469a32735b92fd9026cf7284/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/GenericTrackActionVisitor.java#L6)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

What is the purpose of this? How is this more concise than inlining its definition (which results in fewer stack frames too)?
Also, doesn't seem like it's used anywhere.
</blockquote></details>

copied from other visitors, but it is not needed
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/TrackAction.java, line 9 at r1](https://reviewable.io/reviews/batfish/batfish/7064#-McG4fQTA3UrlN9sVSCk:-McGDMFX3BSjthV1iaPJ:bvnrpcm) ([raw file](https://github.com/batfish/batfish/blob/5ac79f098cea17b6469a32735b92fd9026cf7284/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/TrackAction.java#L9)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

nit: the standard term is `accept` for a visitor, not `apply`.
</blockquote></details>

updated
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/TrackMethod.java, line 15 at r1](https://reviewable.io/reviews/batfish/batfish/7064#-McG5KEx1_TbS5fwuDt8:-McGDWft8R-NfoUrLEab:b9xd3t9) ([raw file](https://github.com/batfish/batfish/blob/5ac79f098cea17b6469a32735b92fd9026cf7284/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/TrackMethod.java#L15)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Why have an evaluate function here, but use visitors for evaluation elsewhere? Is it just because you only have one use case now (evaluate)?

I think in general we prefer to keep dynamic execution code like this in visitors (like an evaluator) to aid in alternate analyses like symbolic execution, plus simplification and caching.

Definitely not meant to be blocking, but something to consider.
</blockquote></details>

I thought about using the visitor/evaluator pattern here, but it seemed overkill since there is only one way to evaluate each kind of track method and that will always return a boolean indicating if an action is triggered.

Though I do prefer the idea of extracting the logic, I could go ahead and add something here to split out the track method evaluation

**Review by arifogel — COMMENTED** [review]
> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7064)* status: all files reviewed, 3 unresolved discussions (waiting on @arifogel, @dhalperi, and @sfraint)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/HsrpPriorityEvaluator.java, line 7 at r2](https://reviewable.io/reviews/batfish/batfish/7064#-McGV9Q8--p9M0UFFYOT:-McGV9Q8--p9M0UFFYOU:buj15k0) ([raw file](https://github.com/batfish/batfish/blob/909c8dc1d6b8d6adca0c6e3744666c98a057798e/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/HsrpPriorityEvaluator.java#L7)):*
> ```Java
>  * action returns the updated priority value after applying the action.
>  */
> public class HsrpPriorityEvaluator implements GenericTrackActionVisitor<Integer> {
> ```

Who is using the return value `<Integer>` of the visitor methods now?

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7064)* status: 1 of 12 files reviewed, 2 unresolved discussions (waiting on @arifogel)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/HsrpPriorityEvaluator.java, line 7 at r2](https://reviewable.io/reviews/batfish/batfish/7064#-McGV9Q8--p9M0UFFYOT:-McG_836-cTS7_NTFzwt:b-rsdo2n) ([raw file](https://github.com/batfish/batfish/blob/909c8dc1d6b8d6adca0c6e3744666c98a057798e/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/HsrpPriorityEvaluator.java#L7)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Who is using the return value `<Integer>` of the visitor methods now?
</blockquote></details>

No one other than tests, updated
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/TrackMethod.java, line 15 at r1](https://reviewable.io/reviews/batfish/batfish/7064#-McG5KEx1_TbS5fwuDt8:-McGjqutA5GkMy6w-eAH:bvnrpcm) ([raw file](https://github.com/batfish/batfish/blob/5ac79f098cea17b6469a32735b92fd9026cf7284/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/TrackMethod.java#L15)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

I thought about using the visitor/evaluator pattern here, but it seemed overkill since there is only one way to evaluate each kind of track method and that will always return a boolean indicating if an action is triggered.

Though I do prefer the idea of extracting the logic, I could go ahead and add something here to split out the track method evaluation
</blockquote></details>

updated

**Review by arifogel — COMMENTED** [review]
> Reviewed 11 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7064)* status: all files reviewed, 1 unresolved discussion (waiting on @sfraint)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/PredicateTrackMethodEvaluator.java, line 11 at r3](https://reviewable.io/reviews/batfish/batfish/7064#-McGyRjc8D_j8jiem5H7:-McGyRjc8D_j8jiem5H8:b-yvyoio) ([raw file](https://github.com/batfish/batfish/blob/81c786085dae8e5aff5f9706e85c99fbd89cd8aa/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/PredicateTrackMethodEvaluator.java#L11)):*
> ```Java
>  * false} otherwise.
>  */
> public class PredicateTrackMethodEvaluator implements GenericTrackMethodVisitor<Boolean> {
> ```

nit: `@ParamatersAreNonnullByDefault` or use `package-info.java` to do the same. Add `@Nonnull to `_configuration`.
Take care of any other missing null annotations in this PR.

**Review by arifogel — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7064#-:-McGzArP5uv-cvhdw9nA:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @sfraint)

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7064)* status: 9 of 12 files reviewed, 1 unresolved discussion (waiting on @arifogel)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/PredicateTrackMethodEvaluator.java, line 11 at r3](https://reviewable.io/reviews/batfish/batfish/7064#-McGyRjc8D_j8jiem5H7:-McH3kxx2i-B59_vtfkX:bvnrpcm) ([raw file](https://github.com/batfish/batfish/blob/81c786085dae8e5aff5f9706e85c99fbd89cd8aa/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/PredicateTrackMethodEvaluator.java#L11)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

nit: `@ParamatersAreNonnullByDefault` or use `package-info.java` to do the same. Add `@Nonnull to `_configuration`.
Take care of any other missing null annotations in this PR.
</blockquote></details>

updated

**Review by sfraint — COMMENTED** [review]
> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7064)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

**Pull request merged**
