### PR TITLE
Checkpoint fix manual hide translated source handling

### PR DESCRIPTION
**Pull request by arifogel**
- fix hierarchy
- allow AddressRange
- disallow IPv6 entities

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7368)* status: all files reviewed, 3 unresolved discussions (waiting on @arifogel and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversions.java, line 146 at r1](https://reviewable.io/reviews/batfish/batfish/7368#-MjD26KP4p4G0PenM_M1:-MjD26KP4p4G0PenM_M2:b-mdpytq) ([raw file](https://github.com/batfish/batfish/blob/04319b4114dcfc1383ea971786d84c740e2cbc27/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversions.java#L146)):*
> ```
> unsupported
> ```
unsupported or invalid?

Also, we should not warn for any IPv6 types.
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversions.java, line 157 at r1](https://reviewable.io/reviews/batfish/batfish/7368#-MjD2Pc5-dTEdOHubyXU:-MjD2Pc5-dTEdOHubyXV:b-bfwzhl) ([raw file](https://github.com/batfish/batfish/blob/04319b4114dcfc1383ea971786d84c740e2cbc27/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversions.java#L157)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
>     if (!(dst instanceof Original)) {
>       warnings.redFlag(
>           String.format(
>               "Manual Hide NAT rule translated-destination %s has unsupported type %s and will be"
>                   + " ignored",
>               dst.getName(), dst.getClass()));
>       valid = false;
>     }
> ```
</details>


1. are these unsupported (Batfish should support them, but doesn't) or invalid? 
2. why do we keep the boolean valid around? just return false at first one. No point in 4 warnings.
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/NatTranslatedSourceVisitor.java, line 4 at r1](https://reviewable.io/reviews/batfish/batfish/7368#-MjD2sjT0boAz8uzQpAD:-MjD2sjT0boAz8uzQpAE:b-ewmadc) ([raw file](https://github.com/batfish/batfish/blob/04319b4114dcfc1383ea971786d84c740e2cbc27/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/NatTranslatedSourceVisitor.java#L4)):*
> ```Java
> 
> /** Visitor for {@link NatTranslatedSource} */
> public interface NatTranslatedSourceVisitor<T> {
> ```

There's a missing visit method in all these.

```
default T visit(NatTranslatedSource source) {
   return source.accept(this);
}
```

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7368)* status: all files reviewed, 3 unresolved discussions (waiting on @dhalperi and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversions.java, line 146 at r1](https://reviewable.io/reviews/batfish/batfish/7368#-MjD26KP4p4G0PenM_M1:-MjDB6hFBNnKri-bSF6B:bxjvbo8) ([raw file](https://github.com/batfish/batfish/blob/04319b4114dcfc1383ea971786d84c740e2cbc27/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversions.java#L146)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> unsupported
> ```
unsupported or invalid?

Also, we should not warn for any IPv6 types.
</blockquote></details>

cleaned up
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversions.java, line 157 at r1](https://reviewable.io/reviews/batfish/batfish/7368#-MjD2Pc5-dTEdOHubyXU:-MjDBFmtEJTTzBMiQlOu:b-uh0kii) ([raw file](https://github.com/batfish/batfish/blob/04319b4114dcfc1383ea971786d84c740e2cbc27/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversions.java#L157)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
>     if (!(dst instanceof Original)) {
>       warnings.redFlag(
>           String.format(
>               "Manual Hide NAT rule translated-destination %s has unsupported type %s and will be"
>                   + " ignored",
>               dst.getName(), dst.getClass()));
>       valid = false;
>     }
> ```

1. are these unsupported (Batfish should support them, but doesn't) or invalid? 
2. why do we keep the boolean valid around? just return false at first one. No point in 4 warnings.
</blockquote></details>

1. invalid AFAIR. We can adjust if we later learn there is a valid exception to `Original`.
2. done
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/NatTranslatedSourceVisitor.java, line 4 at r1](https://reviewable.io/reviews/batfish/batfish/7368#-MjD2sjT0boAz8uzQpAD:-MjDBVI7Cxgv4SViO1Z4:baf2rme) ([raw file](https://github.com/batfish/batfish/blob/04319b4114dcfc1383ea971786d84c740e2cbc27/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/NatTranslatedSourceVisitor.java#L4)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

There's a missing visit method in all these.

```
default T visit(NatTranslatedSource source) {
   return source.accept(this);
}
```
</blockquote></details>

All these what? Visitors?
Personally I don't like `visit` because IMO it pollutes the stack with a function call that is no less verbose.

If you feel strongly, I can switch to it.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7368)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/NatTranslatedSourceVisitor.java, line 4 at r1](https://reviewable.io/reviews/batfish/batfish/7368#-MjD2sjT0boAz8uzQpAD:-MjFe5DM-tfhSNAHM3XJ:b-o87ojo) ([raw file](https://github.com/batfish/batfish/blob/04319b4114dcfc1383ea971786d84c740e2cbc27/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/NatTranslatedSourceVisitor.java#L4)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

All these what? Visitors?
Personally I don't like `visit` because IMO it pollutes the stack with a function call that is no less verbose.

If you feel strongly, I can switch to it.
</blockquote></details>

The thing about the `visit` method is that it is the only place you implement central logic like memoization or cycle-breaking. Look at MemoizedIpAccessListToBdd, or the visitor I added last week.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7368)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/NatTranslatedSourceVisitor.java, line 4 at r1](https://reviewable.io/reviews/batfish/batfish/7368#-MjD2sjT0boAz8uzQpAD:-MjFno1f4Td37_S33b0n:b-nc7edn) ([raw file](https://github.com/batfish/batfish/blob/04319b4114dcfc1383ea971786d84c740e2cbc27/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/NatTranslatedSourceVisitor.java#L4)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

The thing about the `visit` method is that it is the only place you implement central logic like memoization or cycle-breaking. Look at MemoizedIpAccessListToBdd, or the visitor I added last week.
</blockquote></details>

Ah, gotcha.
Switched, though neither of the current implementations would necessarily benefit.

**Review by arifogel — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7368)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

**Pull request merged**
