### PR TITLE
TransferBDD: Support TrackSucceeded and MatchSourceVrf

### PR DESCRIPTION
**Pull request by millstein**
Adds support to the symbolic route analysis for matching on "tracks" in route maps, which represent predicates about the environment, such as whether a specific route exists.  Also updates the SearchRoutePolicies and CompareRoutePolicies questions to appropriately convert results from the symbolic route analysis into concrete routes and executions that respect the tracks.

### CODE REVIEW

**Review by nickgian — COMMENTED** [review]
> Reviewed 12 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8705)* status: 12 of 18 files reviewed, 1 unresolved discussion (waiting on @anothermattbrown and @millstein)

___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/ModelGeneration.java` line 226 at r1](https://reviewable.io/reviews/batfish/batfish/8705#-NTGA0_y22TV1vR6PtYf:-NTGA0_y22TV1vR6PtYg:b-33z5bn) ([raw file](https://github.com/batfish/batfish/blob/ff9a0de64f46744a4b4979eb52cfcdb3720cd4ba/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/ModelGeneration.java#L226)):*
> ```Java
>     for (int i = 0; i < aps.length; i++) {
>       if (aps[i].andSat(fullModel)) {
>         successfulTracks.add(tracks.get(i));
> ```

Does `aps[i].andSat(fullModel)` mean that `aps[i]` might be true or that it must be true?
If the former, does this code mean that we prefer to default tracks to true?

**Review by millstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8705)* status: 12 of 18 files reviewed, 1 unresolved discussion (waiting on @anothermattbrown and @nickgian)

___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/ModelGeneration.java` line 226 at r1](https://reviewable.io/reviews/batfish/batfish/8705#-NTGA0_y22TV1vR6PtYf:-NTGMDJvBRtmGeOsY5wh:b88a7lr) ([raw file](https://github.com/batfish/batfish/blob/ff9a0de64f46744a4b4979eb52cfcdb3720cd4ba/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/ModelGeneration.java#L226)):*
<details><summary><i>Previously, nickgian (Nick Giannarakis) wrote…</i></summary><blockquote>

Does `aps[i].andSat(fullModel)` mean that `aps[i]` might be true or that it must be true?
If the former, does this code mean that we prefer to default tracks to true?
</blockquote></details>

Since `fullModel` has a valuation for every BDD variable, `aps[i]` is either true or false in the model.  This is checking whether it is true.  So we're just checking what the model says, rather than preferring a certain choice.

**Review by nickgian — COMMENTED** [review]
> Reviewed 6 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8705)* status: all files reviewed, 1 unresolved discussion (waiting on @anothermattbrown and @millstein)

___
*[`projects/minesweeper/src/test/java/org/batfish/minesweeper/question/compareroutepolicies/CompareRoutePoliciesAnswererTest.java` line 1372 at r1](https://reviewable.io/reviews/batfish/batfish/8705#-NTZga0MAtRqHCy7v-KV:-NTZga0MAtRqHCy7v-KW:b-krwilc) ([raw file](https://github.com/batfish/batfish/blob/ff9a0de64f46744a4b4979eb52cfcdb3720cd4ba/projects/minesweeper/src/test/java/org/batfish/minesweeper/question/compareroutepolicies/CompareRoutePoliciesAnswererTest.java#L1372)):*
> ```Java
>                 hasColumn(COL_POLICY_NAME, equalTo(POLICY_NEW_NAME), Schema.STRING),
>                 hasColumn(COL_REFERENCE_POLICY_NAME, equalTo(POLICY_REFERENCE_NAME), Schema.STRING),
>                 hasColumn(COL_INPUT_ROUTE, equalTo(inputRoute), Schema.BGP_ROUTE),
> ```

I am a bit confused, does the track difference show up here in some way, i.e., in the input route?
I wonder if we need a new column for Environment or something.

**Review by millstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8705)* status: all files reviewed, 1 unresolved discussion (waiting on @anothermattbrown and @nickgian)

___
*[`projects/minesweeper/src/test/java/org/batfish/minesweeper/question/compareroutepolicies/CompareRoutePoliciesAnswererTest.java` line 1372 at r1](https://reviewable.io/reviews/batfish/batfish/8705#-NTZga0MAtRqHCy7v-KV:-NTZp_ZqAcASy1mVD1nZ:b-vtut4y) ([raw file](https://github.com/batfish/batfish/blob/ff9a0de64f46744a4b4979eb52cfcdb3720cd4ba/projects/minesweeper/src/test/java/org/batfish/minesweeper/question/compareroutepolicies/CompareRoutePoliciesAnswererTest.java#L1372)):*
<details><summary><i>Previously, nickgian (Nick Giannarakis) wrote…</i></summary><blockquote>

I am a bit confused, does the track difference show up here in some way, i.e., in the input route?
I wonder if we need a new column for Environment or something.
</blockquote></details>

Good question - I thought about that as well.  Right now the track difference will show up implicitly in the provided trace -- the trace will show that we matched on stanza 30, for example, and that stanza is matching on a track.  We could in the future add another column as you suggest.

**Review by nickgian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8705)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown)

___
*[`projects/minesweeper/src/test/java/org/batfish/minesweeper/question/compareroutepolicies/CompareRoutePoliciesAnswererTest.java` line 1372 at r1](https://reviewable.io/reviews/batfish/batfish/8705#-NTZga0MAtRqHCy7v-KV:-NTZsNWX9rv8v88bqaFT:bpje7lt) ([raw file](https://github.com/batfish/batfish/blob/ff9a0de64f46744a4b4979eb52cfcdb3720cd4ba/projects/minesweeper/src/test/java/org/batfish/minesweeper/question/compareroutepolicies/CompareRoutePoliciesAnswererTest.java#L1372)):*
<details><summary><i>Previously, millstein (Todd Millstein) wrote…</i></summary><blockquote>

Good question - I thought about that as well.  Right now the track difference will show up implicitly in the provided trace -- the trace will show that we matched on stanza 30, for example, and that stanza is matching on a track.  We could in the future add another column as you suggest.
</blockquote></details>

Good enough for now.

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 2 of 18 files at r1, 24 of 24 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8705)* status: all files reviewed, 2 unresolved discussions (waiting on @millstein)

___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/ConfigAtomicPredicates.java` line 207 at r2](https://reviewable.io/reviews/batfish/batfish/8705#-NVCga9E559Xfl1XfwT0:-NVCga9E559Xfl1XfwT1:b-aczm4y) ([raw file](https://github.com/batfish/batfish/blob/c284ec7e75fd0134b680f5d64e75aaa088ea45e5/projects/minesweeper/src/main/java/org/batfish/minesweeper/ConfigAtomicPredicates.java#L207)):*
> ```Java
>       sourceVRFs.addAll(findAllSourceVrfs(referencePolicies, referenceConfiguration));
>     }
>     _tracks = tracks.stream().collect(ImmutableList.toImmutableList());
> ```

simpler: `ImmutableList.copyOf(tracks)`
___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/ConfigAtomicPredicates.java` line 217 at r2](https://reviewable.io/reviews/batfish/batfish/8705#-NVCgt8X4hxwevR8-FSB:-NVCgt8X4hxwevR8-FSC:b-617ci8) ([raw file](https://github.com/batfish/batfish/blob/c284ec7e75fd0134b680f5d64e75aaa088ea45e5/projects/minesweeper/src/main/java/org/batfish/minesweeper/ConfigAtomicPredicates.java#L217)):*
> ```Java
>     _asPathRegexAtomicPredicates =
>         new AsPathRegexAtomicPredicates(other._asPathRegexAtomicPredicates);
>     _tracks = new LinkedList<>(other._tracks);
> ```

why are you using `ImmutableList` above and `LinkedList` here? can you standardize on `ImmutableList`?
___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/ConfigAtomicPredicates.java` line 279 at r2](https://reviewable.io/reviews/batfish/batfish/8705#-NVChdAuEaUiVsK9qC3Q:-NVChdAuEaUiVsK9qC3R:b-4ti4dh) ([raw file](https://github.com/batfish/batfish/blob/c284ec7e75fd0134b680f5d64e75aaa088ea45e5/projects/minesweeper/src/main/java/org/batfish/minesweeper/ConfigAtomicPredicates.java#L279)):*
> ```Java
>    * user-specified constraints for symbolic analysis.
>    */
>   private static <T> Set<T> findAllMatchItems(
> ```

not important, but I think this could be simplified (and remove a bunch of intermediate sets) by turning this into a generic traversal. make the BooleanVisitor return a `Void` (of which the only element is `null`) and make these methods `void`. The visitor can just collect the items into a set that's an instance variable.
___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/BDDRoute.java` line 397 at r2](https://reviewable.io/reviews/batfish/batfish/8705#-NVCmUUZ8EpKXnApY8qz:-NVCmUUZ8EpKXnApY8r-:b-6j16uk) ([raw file](https://github.com/batfish/batfish/blob/c284ec7e75fd0134b680f5d64e75aaa088ea45e5/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/BDDRoute.java#L397)):*
> ```Java
> 
>   /** Produce a constraint that at most one of the given array of BDDs is true. */
>   private BDD atMostOneOf(BDD[] bdds) {
> ```

reminder: you can simplify by reusing `BDDFiniteDomain`. it's also more efficient

**Review by nickgian — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8705#-:-NVG-hr-0eWm8pbXmoYM:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @millstein)

**Review by millstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8705)* status: 24 of 27 files reviewed, 1 unresolved discussion (waiting on @anothermattbrown and @nickgian)

___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/BDDRoute.java` line 397 at r2](https://reviewable.io/reviews/batfish/batfish/8705#-NVCmUUZ8EpKXnApY8qz:-NVKe_O17UKgS3xy3KIA:bzf7fb8) ([raw file](https://github.com/batfish/batfish/blob/c284ec7e75fd0134b680f5d64e75aaa088ea45e5/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/BDDRoute.java#L397)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

reminder: you can simplify by reusing `BDDFiniteDomain`. it's also more efficient
</blockquote></details>

I started to make that change but it's not a perfect fit here, because I also want to allow the possibility (which is the common case) that none of the options are chosen.  So I want "at most one" rather than "exactly one" and trying to handle that by adding a special null value wasn't working very easily.

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8705)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @millstein)

**Review by anothermattbrown — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8705#-:-NW10-xG9R7QfT0H1OaO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @millstein)

**Pull request merged**
