### PR TITLE
Fix XStream serialization

### PR DESCRIPTION
**Pull request by dspicuzzbbn**
- Flush isn't sufficient, need to close the output stream

### CODE REVIEW

**Comment by dhalperi** [comment]
In general, if someone passes you a stream they've opened, you can't close it. So this can't be the right fix. But I'll look into it.

(E.g, what if I want to serialize 3 objects back to back?)

**Comment by dspicuzzbbn** [comment]
The stream is created in that same function, how is it incorrect to close it in that function?

**Comment by dspicuzzbbn** [comment]
Using this function as currently implemented, I believe xstream serialization will produce invalid XML if you try to serialize 3 objects back to back.

**Comment by dhalperi** [comment]
> I believe xstream serialization will produce invalid XML 

Agree that Xstream serialization is currently broken.

> The stream is created in that same function, how is it incorrect to close it in that function?

Closing the `oos` closes the stream passed into the function:

```java
package org.batfish.common.plugin;

import com.thoughtworks.xstream.XStream;
import com.thoughtworks.xstream.io.xml.DomDriver;
import java.io.FileOutputStream;
import java.io.ObjectOutputStream;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TemporaryFolder;
import org.junit.runner.RunWith;
import org.junit.runners.JUnit4;

@RunWith(JUnit4.class)
public class PluginConsumerTest {
  @Rule public TemporaryFolder _folder = new TemporaryFolder();

  @Test
  public void test() throws Exception {
    FileOutputStream out = new FileOutputStream(_folder.newFile("foo"));
    out.write(5);

    XStream xstream = new XStream(new DomDriver("UTF-8"));
    ObjectOutputStream oos = xstream.createObjectOutputStream(out);
    oos.close();

    out.write(4);  // this throws an exception. Closing oos closes out.
  }
}
```

**Comment by dspicuzzbbn** [comment]
Oh interesting, I wouldn't have expected it to close the other stream.

**Comment by dhalperi** [comment]
Check out #479, which now has tests (that should have been there all along :/)

**Comment by dspicuzzbbn** [comment]
Closing in favor of #479

**Pull request closed without merging**
