### PR TITLE
BGP redistribution: set MED to IGP metric

### PR DESCRIPTION
**Pull request by progwriter**
In the fullness of time this would be probably be done by routing policy because vendors may have knobs to control this behavior, but for now this is a default that seems to apply to big vendors

### CODE REVIEW

**Review by corinaminer — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6425)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by progwriter** [comment]
Did not expect this much difference in behavior. Closing pending some closer validation

**Comment by progwriter** [comment]
A more detailed investigation reveals that the main RIB for the example network is not affected. the BGP ribs are already not-as-correct-as-we-like so the changes reflected in the DP ref test do not make the situation any worse.

**Review by corinaminer — COMMENTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6425)* status: all files reviewed, 1 unresolved discussion (waiting on @progwriter)

___
*[projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java, line 3985 at r2](https://reviewable.io/reviews/batfish/batfish/6425#-MNjcWrkAC3vE9fEXJ5l:-MNjcWrlEHcwBCzyoK_E:b-4fseyc) ([raw file](https://github.com/batfish/batfish/blob/54a39f6db53b8bf69559ebc6db5c19371cba1b43/projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java#L3985)):*
> ```Java
>     EigrpRoute noMatchEigrp = internalRb.setNetwork(noMatchRm).build();
> 
>     // TODO BGP metric should match original route's metric
> ```

can remove this todo :heart_eyes:
looks like you already rooted it out in the nxos test.

**Review by progwriter — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6425)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @corinaminer)

___
*[projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java, line 3985 at r2](https://reviewable.io/reviews/batfish/batfish/6425#-MNjcWrkAC3vE9fEXJ5l:-MNjiovN5RP-AQzXm6bC:b-bfjh7l) ([raw file](https://github.com/batfish/batfish/blob/54a39f6db53b8bf69559ebc6db5c19371cba1b43/projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java#L3985)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

can remove this todo :heart_eyes:
looks like you already rooted it out in the nxos test.
</blockquote></details>

to-done.

**Review by progwriter — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6425)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
