### PR TITLE
add descriptions to AclLineMatchExpr, ios-xe policy pieces

### PR DESCRIPTION
**Pull request by arifogel**

### CODE REVIEW

**Comment by dhalperi** [comment]
Reviewed 15 of 16 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 3647 at r2](https://reviewable.io/reviews/batfish/batfish/1311#-LBi7G853slli1QWOguH:-LBi7G853slli1QWOguI:b-uzrof3) ([raw file](https://github.com/batfish/batfish/blob/e075f2781feac867e931b2d0c9dc0465e6268119/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L3647)):*
> ```
>  %s
> ```
Don't much care myself, but for consistency I'd probably keep the use of `'` surrounding `%s`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1311)*

**Comment by dhalperi** [comment]
LGTM as-is or with 1 minor comment. Feel free to dismiss & ship.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1311#-:-LBi80QdB1kxcc96uKF3:b-f2w6hd)*

**Comment by arifogel** [comment]
Review status: 16 of 17 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 3647 at r2](https://reviewable.io/reviews/batfish/batfish/1311#-LBi7G853slli1QWOguH:-LBiT7_4E87IcrTDq_8h:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/e075f2781feac867e931b2d0c9dc0465e6268119/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L3647)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
>  %s
> ```
Don't much care myself, but for consistency I'd probably keep the use of `'` surrounding `%s`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1311)*

**Comment by dhalperi** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1311)*

**Comment by dhalperi** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1311#-:-LBnncAy387bZr6WZpQd:bnfp4nl)*

**Pull request merged**
