### PR TITLE
A10: convert ACLs

### PR DESCRIPTION
**Pull request by sfraint**
Add initial conversion for `ip access-list`s. These are converted into `PacketPolicy` along with NAT transformations.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 10 of 19 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7856)* status: all files reviewed, 2 unresolved discussions (waiting on @arifogel and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/vendor/a10/representation/A10Configuration.java, line 664 at r2](https://reviewable.io/reviews/batfish/batfish/7856#-MrU_mzP02GYG5V7JeFd:-MrU_mzP02GYG5V7JeFe:bqzvxj9) ([raw file](https://github.com/batfish/batfish/blob/813e2c4cbc7dbec164e126bacc97145f2988e17e/projects/batfish/src/main/java/org/batfish/vendor/a10/representation/A10Configuration.java#L664)):*
> ```Java
>   private Statement toStatement(VirtualServerPort port) {
>     ImmutableList.Builder<Statement> trueStatements = ImmutableList.builder();
>     String aclName = port.getAccessList();
> ```

do we need to handle undefined refs here?

if not, at least add an assert or something.
___
*[projects/batfish/src/main/java/org/batfish/vendor/a10/representation/A10Conversion.java, line 864 at r2](https://reviewable.io/reviews/batfish/batfish/7856#-MrUa3NfBtR-QAmvWKl-:-MrUa3NfBtR-QAmvWKl0:bokddzn) ([raw file](https://github.com/batfish/batfish/blob/813e2c4cbc7dbec164e126bacc97145f2988e17e/projects/batfish/src/main/java/org/batfish/vendor/a10/representation/A10Conversion.java#L864)):*
> ```Java
>             "Default deny all",
>             traceElementForAccessListDefaultDeny(acl.getName(), filename),
>             vsid));
> ```

why is this needed? is that not the default behavior of an ACL? (and handled already by tracing infra)



_Code quote:_
```Java
    lines.add(
        new ExprAclLine(
            LineAction.DENY,
            TrueExpr.INSTANCE,
            "Default deny all",
            traceElementForAccessListDefaultDeny(acl.getName(), filename),
            vsid));
```

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7856)* status: 15 of 19 files reviewed, 2 unresolved discussions (waiting on @arifogel and @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/vendor/a10/representation/A10Configuration.java, line 664 at r2](https://reviewable.io/reviews/batfish/batfish/7856#-MrU_mzP02GYG5V7JeFd:-MrUbUhOCgNnanjmV-kK:b-y1mqzg) ([raw file](https://github.com/batfish/batfish/blob/813e2c4cbc7dbec164e126bacc97145f2988e17e/projects/batfish/src/main/java/org/batfish/vendor/a10/representation/A10Configuration.java#L664)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

do we need to handle undefined refs here?

if not, at least add an assert or something.
</blockquote></details>

Added an assert.

`A10` doesn't allow undefined refs (at least here and the few other places I checked).
___
*[projects/batfish/src/main/java/org/batfish/vendor/a10/representation/A10Conversion.java, line 864 at r2](https://reviewable.io/reviews/batfish/batfish/7856#-MrUa3NfBtR-QAmvWKl-:-MrUdRiH3SmQdHAcgMhG:b9x7my8) ([raw file](https://github.com/batfish/batfish/blob/813e2c4cbc7dbec164e126bacc97145f2988e17e/projects/batfish/src/main/java/org/batfish/vendor/a10/representation/A10Conversion.java#L864)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

why is this needed? is that not the default behavior of an ACL? (and handled already by tracing infra)
</blockquote></details>

Removed.

There's no explicit trace added in this case, but the behavior is correct.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7856)* status: 17 of 19 files reviewed, 2 unresolved discussions (waiting on @arifogel and @dhalperi)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7856)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Pull request merged**
