### PR TITLE
IOS: rewrite parser numbers to add uint8, 16, 32

### PR DESCRIPTION
**Pull request by dhalperi**
And migrate ext-community parsing to it.

Starts work discussed in #6688 .

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 29 of 31 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6702)* status: all files reviewed, 4 unresolved discussions (waiting on @dhalperi)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_common.g4, line 189 at r3](https://reviewable.io/reviews/batfish/batfish/6702#-MVI72RY69jgpvhmjQvy:-MVI72RZEYIgaTjtNBsN:b-gos99d) ([raw file](https://github.com/batfish/batfish/blob/fb78c26687c42bd0160df4e1491830527d399156/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_common.g4#L189)):*
> ```ANTLR
>       (
>         name_middle_parts += M_Interface_PREFIX
>       )? name_middle_parts += (DEC | UINT8 | UINT16 | UINT32)
> ```

Why not just use `dec` rule here? This is its definition.
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_common.g4, line 716 at r3](https://reviewable.io/reviews/batfish/batfish/6702#-MVI7JFVE60OcIY6Bgwo:-MVI7JFVE60OcIY6Bgwp:brx8od9) ([raw file](https://github.com/batfish/batfish/blob/fb78c26687c42bd0160df4e1491830527d399156/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_common.g4#L716)):*
> ```ANTLR
> vlan_id
> :
>   v = (DEC | UINT8 | UINT16)
> ```

So you want `DEC` but not `UINT32`? Is there a real advantage over using `dec`?
___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 1268 at r3](https://reviewable.io/reviews/batfish/batfish/6702#-MVI8S9z9YG5hwwNubij:-MVI8S9z9YG5hwwNubik:b-4jhry6) ([raw file](https://github.com/batfish/batfish/blob/fb78c26687c42bd0160df4e1491830527d399156/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L1268)):*
> ```Java
> 
>   private static int toInteger(DecContext ctx) {
>     return Integer.parseInt(ctx.getText());
> ```

Better to warn in interim or crash when out of range? Applies to any coverter taking `DecContext`.
___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 9307 at r3](https://reviewable.io/reviews/batfish/batfish/6702#-MVI8s9s6Yp8PznM1AWu:-MVI8s9s6Yp8PznM1AWv:b-4eur3j) ([raw file](https://github.com/batfish/batfish/blob/fb78c26687c42bd0160df4e1491830527d399156/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L9307)):*
> ```Java
>   }
> 
>   private @Nonnull Optional<ExtendedCommunity> toExtendedCommunity(Ecgalal_asdot_colonContext ctx) {
> ```

None of these `Ecgalal_` cases need return `Optional` any longer.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6702)* status: all files reviewed, 4 unresolved discussions (waiting on @dhalperi)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_common.g4, line 716 at r3](https://reviewable.io/reviews/batfish/batfish/6702#-MVI7JFVE60OcIY6Bgwo:-MVIA6y_AgJPqafmEzDL:bicoyxf) ([raw file](https://github.com/batfish/batfish/blob/fb78c26687c42bd0160df4e1491830527d399156/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_common.g4#L716)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

So you want `DEC` but not `UINT32`? Is there a real advantage over using `dec`?
</blockquote></details>

That is, I would either just use `uint16` or `dec` here (rules not tokens).

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6702)* status: 30 of 31 files reviewed, 3 unresolved discussions (waiting on @arifogel)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_common.g4, line 189 at r3](https://reviewable.io/reviews/batfish/batfish/6702#-MVI72RY69jgpvhmjQvy:-MVIACaV7L8whiFtqpCX:b-wy6wzz) ([raw file](https://github.com/batfish/batfish/blob/fb78c26687c42bd0160df4e1491830527d399156/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_common.g4#L189)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Why not just use `dec` rule here? This is its definition.
</blockquote></details>

ANTLR didn't let me -- elsewhere `name_middle_parts` is a token, so it made me use all tokens.
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_common.g4, line 716 at r3](https://reviewable.io/reviews/batfish/batfish/6702#-MVI7JFVE60OcIY6Bgwo:-MVIAFLN-9tkaFjVeOmk:b-rxm6ba) ([raw file](https://github.com/batfish/batfish/blob/fb78c26687c42bd0160df4e1491830527d399156/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_common.g4#L716)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

That is, I would either just use `uint16` or `dec` here (rules not tokens).
</blockquote></details>

ANTLR didn't let me: can't use `{isVlanId($v)}` with `DEC`.
___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 1268 at r3](https://reviewable.io/reviews/batfish/batfish/6702#-MVI8S9z9YG5hwwNubij:-MVIAWTT-fsAXC6dkGCL:b-9iweq6) ([raw file](https://github.com/batfish/batfish/blob/fb78c26687c42bd0160df4e1491830527d399156/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L1268)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Better to warn in interim or crash when out of range? Applies to any coverter taking `DecContext`.
</blockquote></details>

Not sure what you mean by this? This is just meant to be the closest thing to a no-op (after replacing `DEC` with `dec`). The old version (the one that took TerminalNode and was deleted) used for `ctx.DEC()` didn't have any warnings or checks.

The hope is that `dec` will never have a range, instead all uses of `DecContext` will eventually. be removed.
___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 9307 at r3](https://reviewable.io/reviews/batfish/batfish/6702#-MVI8s9s6Yp8PznM1AWu:-MVIJbnjEBE1Qfd6XCyl:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/fb78c26687c42bd0160df4e1491830527d399156/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L9307)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

None of these `Ecgalal_` cases need return `Optional` any longer.
</blockquote></details>

Done.

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6702)* status: all files reviewed, 4 unresolved discussions (waiting on @dhalperi)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_common.g4, line 189 at r3](https://reviewable.io/reviews/batfish/batfish/6702#-MVI72RY69jgpvhmjQvy:-MVIKqAB5Gs5XRzteqx4:b-pamjns) ([raw file](https://github.com/batfish/batfish/blob/fb78c26687c42bd0160df4e1491830527d399156/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_common.g4#L189)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

ANTLR didn't let me -- elsewhere `name_middle_parts` is a token, so it made me use all tokens.
</blockquote></details>

Ugh we really need to murder this rule and start over. OK for now.
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_common.g4, line 716 at r3](https://reviewable.io/reviews/batfish/batfish/6702#-MVI7JFVE60OcIY6Bgwo:-MVIL-t-80-f_qkGThx0:b-vpbkzh) ([raw file](https://github.com/batfish/batfish/blob/fb78c26687c42bd0160df4e1491830527d399156/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_common.g4#L716)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

ANTLR didn't let me: can't use `{isVlanId($v)}` with `DEC`.
</blockquote></details>

This is the only place it's used I think, so I would just change `isVlanId` in `CiscoBaseParser` to take `xxxContext`.
___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 1268 at r3](https://reviewable.io/reviews/batfish/batfish/6702#-MVI8S9z9YG5hwwNubij:-MVILFFg6dpB0m-UoiGw:b-nbna8s) ([raw file](https://github.com/batfish/batfish/blob/fb78c26687c42bd0160df4e1491830527d399156/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L1268)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Not sure what you mean by this? This is just meant to be the closest thing to a no-op (after replacing `DEC` with `dec`). The old version (the one that took TerminalNode and was deleted) used for `ctx.DEC()` didn't have any warnings or checks.

The hope is that `dec` will never have a range, instead all uses of `DecContext` will eventually. be removed.
</blockquote></details>

This is fine. But in interim until we get rid of uses of `DecContext`, I was wondering if we should make it less crashy for bad values.
Probably too much work for this PR.
___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 9271 at r4](https://reviewable.io/reviews/batfish/batfish/6702#-MVILfmj0uVrrC6l0K3-:-MVILfmj0uVrrC6l0K30:b-69yydg) ([raw file](https://github.com/batfish/batfish/blob/67b224fb526c193d59e99a63f4a9e0af21b39f08/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L9271)):*
> ```Java
>   private @Nonnull List<ExtendedCommunity> toExtendedCommunities(
>       ParserRuleContext messageCtx, List<Extended_community_route_targetContext> communities) {
>     ImmutableList.Builder<ExtendedCommunity> builder = ImmutableList.builder();
> ```

optional: this whole thing could be done as a stream chain now.
`return communities.stream().map(communityCtx -> toExtendedCommunity(messageCtx, communityCtx)).collect(ImmutableList.toImmutableList());`

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6702)* status: all files reviewed, 4 unresolved discussions (waiting on @dhalperi)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_common.g4, line 716 at r3](https://reviewable.io/reviews/batfish/batfish/6702#-MVI7JFVE60OcIY6Bgwo:-MVIMDucBbPfpbfe9EIE:bkwxa5v) ([raw file](https://github.com/batfish/batfish/blob/fb78c26687c42bd0160df4e1491830527d399156/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_common.g4#L716)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

This is the only place it's used I think, so I would just change `isVlanId` in `CiscoBaseParser` to take `xxxContext`.
</blockquote></details>

Actually that's not possible due to inheritance hierarchy, so never mind.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6702)* status: all files reviewed, 4 unresolved discussions (waiting on @dhalperi)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_common.g4, line 716 at r3](https://reviewable.io/reviews/batfish/batfish/6702#-MVI7JFVE60OcIY6Bgwo:-MVIMNO44ZrISc5Zvm2H:bl985un) ([raw file](https://github.com/batfish/batfish/blob/fb78c26687c42bd0160df4e1491830527d399156/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_common.g4#L716)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Actually that's not possible due to inheritance hierarchy, so never mind.
</blockquote></details>

(unless you want to do it in extractor)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6702)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
