### PR TITLE
parse nxos ospf settings for non default vrf

### PR DESCRIPTION
**Pull request by arifogel**
- test for config -> datamodel
- test for datamodel -> ospfNeighbors
- fix disableUnrecognized setting for CiscoGrammarTest tests
- refactor initRemoteOspfNeighbors out of Batfish
- add various relevant Matchers
- fix incorrect ignores in Cisco_interface

---
This change is [Reviewable](https://reviewable.io/reviews/batfish/batfish/940)

### CODE REVIEW

**Comment by dhalperi** [comment]
Reviewed 20 of 20 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_ospf.g4, line 372 at r1](https://reviewable.io:443/reviews/batfish/batfish/940#-L5AthJfJmU53zucO-vw:-L5AthJfJmU53zucO-vx:bvt8fba) ([raw file](https://github.com/batfish/batfish/blob/90417fad4e8082f6009aa021c1c0e44cc41cc2fb/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_ospf.g4#L372)):*
> ```ANTLR
>       | ro_redistribute_connected
>       | ro_redistribute_rip
>       | ro_redistribute_static
> ```

can you add a comment indicating how you know these are the only valid clauses for a vrf declared/configured inside an OSPF router definition?

---

*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 1798 at r1](https://reviewable.io:443/reviews/batfish/batfish/940#-L5AsJ2Z0nE76JE8KDAw:-L5AsJ2Z0nE76JE8KDAx:b-3acce) ([raw file](https://github.com/batfish/batfish/blob/90417fad4e8082f6009aa021c1c0e44cc41cc2fb/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L1798)):*
> ```Java
>       currentVrf().setOspfProcess(proc);
>       proc.setRouterId(routerId);
>     }
> ```

what is the multiplicity of OSPF processes with a given name? are they per-vrf or per device?

(aka, why not just set a pointer instead of doing a 3-field clone of the current OSPF process?)

---

*[projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java, line 479 at r1](https://reviewable.io:443/reviews/batfish/batfish/940#-L5AsZmboaovFIB5IhpS:-L5AsZmboaovFIB5IhpT:b-6qhh0s) ([raw file](https://github.com/batfish/batfish/blob/c02929d5ac4027cca969713dd8690ca7329de640/projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java#L479)):*
> ```Java
>                 .build(),
>             _folder);
>     batfish.getSettings().setDisableUnrecognized(false);
> ```

Not sure I understand this change -- don't we want to require that all tests (except where whitelisted) have configs that fully parse?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/940)*

**Comment by arifogel** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_ospf.g4, line 372 at r1](https://reviewable.io:443/reviews/batfish/batfish/940#-L5AthJfJmU53zucO-vw:-L5Av8qfnXs5YeVsDfPK:b-e58d2) ([raw file](https://github.com/batfish/batfish/blob/90417fad4e8082f6009aa021c1c0e44cc41cc2fb/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_ospf.g4#L372)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

can you add a comment indicating how you know these are the only valid clauses for a vrf declared/configured inside an OSPF router definition?
</blockquote></details>

These are the only clauses I have seen so far. I envision several more being added as we get more configuration data. If you like, I can at least add some lines to the unit test configs for these clauses.

---

*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 1798 at r1](https://reviewable.io:443/reviews/batfish/batfish/940#-L5AsJ2Z0nE76JE8KDAw:-L5AuFErom60V4Jh9rbj:b-ehkp9r) ([raw file](https://github.com/batfish/batfish/blob/90417fad4e8082f6009aa021c1c0e44cc41cc2fb/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L1798)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

what is the multiplicity of OSPF processes with a given name? are they per-vrf or per device?

(aka, why not just set a pointer instead of doing a 3-field clone of the current OSPF process?)
</blockquote></details>

As is, it's per-vrf. This is how the data model is structured for all routing processes. It would be very difficult to rearrange. As far as just setting a pointer, this would be a negligible difference in overhead, so I don't see the value. In particular, I don't currently envision any other fields being inherited.

---

*[projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java, line 479 at r1](https://reviewable.io:443/reviews/batfish/batfish/940#-L5AsZmboaovFIB5IhpS:-L5AurvxyZBLhtCX77fx:blh5a4v) ([raw file](https://github.com/batfish/batfish/blob/c02929d5ac4027cca969713dd8690ca7329de640/projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java#L479)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Not sure I understand this change -- don't we want to require that all tests (except where whitelisted) have configs that fully parse?
</blockquote></details>

The default for tests is already `setDisableUnrecognized(true)`. By removing the line we are using that default, i.e. requiring full recognition of all lines. Does that clear things up?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/940)*

**Comment by dhalperi** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_ospf.g4, line 372 at r1](https://reviewable.io:443/reviews/batfish/batfish/940#-L5AthJfJmU53zucO-vw:-L5Ayy9bKTW7hhDIeogK:b-hg06qa) ([raw file](https://github.com/batfish/batfish/blob/90417fad4e8082f6009aa021c1c0e44cc41cc2fb/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_ospf.g4#L372)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

These are the only clauses I have seen so far. I envision several more being added as we get more configuration data. If you like, I can at least add some lines to the unit test configs for these clauses.
</blockquote></details>

OK Up to you.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/940#-:-L5Az0abFuXQHiube_h1:bnfp4nl)*

**Comment by arifogel** [comment]
Review status: 18 of 26 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_ospf.g4, line 372 at r1](https://reviewable.io:443/reviews/batfish/batfish/940#-L5AthJfJmU53zucO-vw:-L5BEHhZeaUD_BSfTH1O:b-z0zm2j) ([raw file](https://github.com/batfish/batfish/blob/90417fad4e8082f6009aa021c1c0e44cc41cc2fb/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_ospf.g4#L372)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

OK Up to you.
</blockquote></details>

I removed alternatives for which I did not have justifying snippets.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/940)*

**Comment by dhalperi** [comment]
Reviewed 8 of 8 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/940)*

**Comment by dhalperi** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/940)*

**Pull request merged**
