### PR TITLE
changes for tracing in coordinator, allinone, worker and client

### PR DESCRIPTION
**Pull request by haverma**
screen shot 2017-11-08 at 9 15 40 pm
screen shot 2017-11-08 at 9 17 45 pm
screen shot 2017-11-08 at 9 20 37 pm

1. The client side operations are being named by Http method names(GET, POST) since I am not creating any named active parent spans for them

2. Inittracer takes 11-12sec to return because of latency in some network operation during Jaeger Tracer initialization

3. The code only contains traces by jax-rs endpoints,

4. Had to format the whole file for AllInOne.java, coordinator/Main.java, Client.java, client/Settings.java and Driver.java to pass through google-java-format check in travis.

---
This change is [Reviewable](https://reviewable.io/reviews/batfish/batfish/659)

### CODE REVIEW

**Comment by dhalperi** [comment]
Reviewed 1 of 17 files at r1.
Review status: 1 of 17 files reviewed at latest revision, 9 unresolved discussions.

---

*[projects/pom.xml, line 59 at r1](https://reviewable.io:443/reviews/batfish/batfish/659#-KyUGhXkFSgr_vuP6qyU:-KyUGhXkFSgr_vuP6qyV:bi40xiq) ([raw file](https://github.com/batfish/batfish/blob/483ea212370fa80e0d8560c01769df49cb4155c4/projects/pom.xml#L59)):*
> ```XML
>     <hamcrest.version>1.3</hamcrest.version>
>     <jackson.version>2.9.0</jackson.version>
>     <jaeger.version>0.20.5</jaeger.version>
> ```

Was 20.5 a specific choice? They're up to 21 now. (and 22 RCs are out, but maybe we stick with last stable release for time being?)

---

*[projects/pom.xml, line 70 at r1](https://reviewable.io:443/reviews/batfish/batfish/659#-KyUFj83dvUiarIAw-p0:-KyUFj83dvUiarIAw-p1:b-cdca97) ([raw file](https://github.com/batfish/batfish/blob/483ea212370fa80e0d8560c01769df49cb4155c4/projects/pom.xml#L70)):*
> ```XML
>     <jackson-jsonschema.version>1.0.11-batfish-internal</jackson-jsonschema.version>
>     <opentrace-jaxrs.version>0.0.8</opentrace-jaxrs.version>
>     <opentracing-opentracing.version>0.30.0</opentracing-opentracing.version>
> ```

1. use consistent names -- `opentrace` vs `opentracing` -- why the difference? I'd probably opt for `opentracing` given that's what the library is called.

2. Prefer that these properties are named either directly like the jars or more generally. So,
    a. for `opentracing-opentracing.version`: if `io.opentracing:opentracing-api` is the main artifact, and things not under `io.opentracing.contrib` will have the same version, just call it `opentracing.version`.
    b. for `opentracing-jaxrs.version`, the artifact is called `opentracing-jaxrs2` -- why drop the 2?

---

*[projects/pom.xml, line 518 at r1](https://reviewable.io:443/reviews/batfish/batfish/659#-KyUH9aRK_7H1NCUbJ4r:-KyUH9aRK_7H1NCUbJ4s:b-r76i0) ([raw file](https://github.com/batfish/batfish/blob/483ea212370fa80e0d8560c01769df49cb4155c4/projects/pom.xml#L518)):*
> ```XML
> 
>       <dependency>
>         <groupId>com.uber.jaeger</groupId>
> ```

this should go after `com.thoughtworks`.

---

*[projects/pom.xml, line 530 at r1](https://reviewable.io:443/reviews/batfish/batfish/659#-KyUGp8tVkCQk1Tn1ThV:-KyUGp8tVkCQk1Tn1ThW:b-8ngtd5) ([raw file](https://github.com/batfish/batfish/blob/483ea212370fa80e0d8560c01769df49cb4155c4/projects/pom.xml#L530)):*
> ```XML
> 
>       <dependency>
>         <groupId>io.opentracing.contrib</groupId>
> ```

These are supposed to be alphabetized.

1. `io.opentracing.contrib` comes after `io.opentracing`.
2. `io.opentracing*` goes much lower: after `com*` and before `j*` below. (Presumably this is because of the pre-existing below issue).

---

*[projects/pom.xml, line 547 at r1](https://reviewable.io:443/reviews/batfish/batfish/659#-KyUHE0Jd3eK-i0NPK9M:-KyUHE0Jd3eK-i0NPK9N:bwgid5f) ([raw file](https://github.com/batfish/batfish/blob/483ea212370fa80e0d8560c01769df49cb4155c4/projects/pom.xml#L547)):*
> ```XML
>       </dependency>
> 
>       <dependency>
> ```

this looks like it was added at the wrong place, too. (I didn't add it or review it, so didn't catch.) move it to the right place?

---

*[projects/allinone/pom.xml, line 27 at r1](https://reviewable.io:443/reviews/batfish/batfish/659#-KyUHSJYjYuE0xv11Dom:-KyUHSJYjYuE0xv11Don:brqd575) ([raw file](https://github.com/batfish/batfish/blob/483ea212370fa80e0d8560c01769df49cb4155c4/projects/allinone/pom.xml#L27)):*
> ```XML
>                 <ignoredUnusedDeclaredDependencies>
>                   <ignoredUnusedDeclaredDependency>org.slf4j:slf4j-jdk14
>                   </ignoredUnusedDeclaredDependency>
> ```

these should be on one line.

---

*[projects/allinone/pom.xml, line 34 at r1](https://reviewable.io:443/reviews/batfish/batfish/659#-KyUHV0caH9fJRpaiEtT:-KyUHV0caH9fJRpaiEtU:brdshvb) ([raw file](https://github.com/batfish/batfish/blob/483ea212370fa80e0d8560c01769df49cb4155c4/projects/allinone/pom.xml#L34)):*
> ```XML
>                   <ignoredUnusedDeclaredDependency>io.opentracing:opentracing-api
>                   </ignoredUnusedDeclaredDependency>
>                   <ignoredUnusedDeclaredDependency>io.opentracing:opentracing-util
> ```

this doesn't seem right -- compile-scope dependencies are used by definition. I'd only ever expect to see `runtime` or `test` scope artifacts here. Also, this list doesn't really make any sense. Which of these does `allinone` itself need to provide, which the other modules it depends on don't provide?

---

*[projects/allinone/pom.xml, line 111 at r1](https://reviewable.io:443/reviews/batfish/batfish/659#-KyUHk_lIiHNfxaJmJjc:-KyUHk_lIiHNfxaJmJjd:b-3vnpxb) ([raw file](https://github.com/batfish/batfish/blob/483ea212370fa80e0d8560c01769df49cb4155c4/projects/allinone/pom.xml#L111)):*
> ```XML
>        <groupId>org.batfish</groupId>
>        <artifactId>question</artifactId>
>     </dependency>
> ```

looks like `<scope>runtime</scope>` was missed here when this dependency was added last week -- please fix and move below to the `<--- Runtime dependencies ...` section?

---

*[projects/allinone/src/main/java/org/batfish/allinone/AllInOne.java, line 15 at r1](https://reviewable.io:443/reviews/batfish/batfish/659#-KyUI5PapbG8Yi30L1ci:-KyUI5PapbG8Yi30L1cj:b-vb8d5h) ([raw file](https://github.com/batfish/batfish/blob/7fb2a3c7b9445989a055a23bfc0e14875575c448/projects/allinone/src/main/java/org/batfish/allinone/AllInOne.java#L15)):*
> ```Java
> public class AllInOne {
> 
>   private static String[] getArgArrayFromString(String argString) {
> ```

please undo any reordering in this PR that isn't relevant to your changes. My guess is you accidentally checked the box to `rearrange code` in the autoformatter -- suggest you uncheck it?

Seems this happened in more than a few files, will continue reviewing after this is fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/659)*

**Comment by haverma** [comment]
*[projects/allinone/src/main/java/org/batfish/allinone/AllInOne.java, line 15 at r1](https://reviewable.io:443/reviews/batfish/batfish/659#-KyUI5PapbG8Yi30L1ci:-KyUpNxCBuLJUVAZyKJL:b-p9itce) ([raw file](https://github.com/batfish/batfish/blob/7fb2a3c7b9445989a055a23bfc0e14875575c448/projects/allinone/src/main/java/org/batfish/allinone/AllInOne.java#L15)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

please undo any reordering in this PR that isn't relevant to your changes. My guess is you accidentally checked the box to `rearrange code` in the autoformatter -- suggest you uncheck it?

Seems this happened in more than a few files, will continue reviewing after this is fixed.
</blockquote></details>

Reverted unrelated formatting changes 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/659)*

**Comment by haverma** [comment]
Review status: 0 of 16 files reviewed at latest revision, 9 unresolved discussions.

---

*[projects/pom.xml, line 70 at r1](https://reviewable.io:443/reviews/batfish/batfish/659#-KyUFj83dvUiarIAw-p0:-KyV8g-ZN7e1jiPZ0FSL:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/483ea212370fa80e0d8560c01769df49cb4155c4/projects/pom.xml#L70)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

1. use consistent names -- `opentrace` vs `opentracing` -- why the difference? I'd probably opt for `opentracing` given that's what the library is called.

2. Prefer that these properties are named either directly like the jars or more generally. So,
    a. for `opentracing-opentracing.version`: if `io.opentracing:opentracing-api` is the main artifact, and things not under `io.opentracing.contrib` will have the same version, just call it `opentracing.version`.
    b. for `opentracing-jaxrs.version`, the artifact is called `opentracing-jaxrs2` -- why drop the 2?
</blockquote></details>

done

---

*[projects/pom.xml, line 518 at r1](https://reviewable.io:443/reviews/batfish/batfish/659#-KyUH9aRK_7H1NCUbJ4r:-KyV8n7GyrD5q2hmPMWs:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/483ea212370fa80e0d8560c01769df49cb4155c4/projects/pom.xml#L518)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

this should go after `com.thoughtworks`.
</blockquote></details>

done

---

*[projects/pom.xml, line 530 at r1](https://reviewable.io:443/reviews/batfish/batfish/659#-KyUGp8tVkCQk1Tn1ThV:-KyV8nwzWxilrfeAKuNp:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/483ea212370fa80e0d8560c01769df49cb4155c4/projects/pom.xml#L530)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

These are supposed to be alphabetized.

1. `io.opentracing.contrib` comes after `io.opentracing`.
2. `io.opentracing*` goes much lower: after `com*` and before `j*` below. (Presumably this is because of the pre-existing below issue).
</blockquote></details>

done

---

*[projects/pom.xml, line 547 at r1](https://reviewable.io:443/reviews/batfish/batfish/659#-KyUHE0Jd3eK-i0NPK9M:-KyV8p5KYkkAaBJ3Cgrh:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/483ea212370fa80e0d8560c01769df49cb4155c4/projects/pom.xml#L547)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

this looks like it was added at the wrong place, too. (I didn't add it or review it, so didn't catch.) move it to the right place?
</blockquote></details>

done

---

*[projects/allinone/pom.xml, line 27 at r1](https://reviewable.io:443/reviews/batfish/batfish/659#-KyUHSJYjYuE0xv11Dom:-KyV8q1VX3SV1JzSNTLQ:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/483ea212370fa80e0d8560c01769df49cb4155c4/projects/allinone/pom.xml#L27)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

these should be on one line.
</blockquote></details>

done

---

*[projects/allinone/pom.xml, line 111 at r1](https://reviewable.io:443/reviews/batfish/batfish/659#-KyUHk_lIiHNfxaJmJjc:-KyV9G9lxEgKECBILs_F:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/483ea212370fa80e0d8560c01769df49cb4155c4/projects/allinone/pom.xml#L111)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

looks like `<scope>runtime</scope>` was missed here when this dependency was added last week -- please fix and move below to the `<--- Runtime dependencies ...` section?
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/659)*

**Comment by haverma** [comment]
*[projects/pom.xml, line 59 at r1](https://reviewable.io:443/reviews/batfish/batfish/659#-KyUGhXkFSgr_vuP6qyU:-KyVA6s0ZEnWk9sATwDo:b-sa9bgt) ([raw file](https://github.com/batfish/batfish/blob/483ea212370fa80e0d8560c01769df49cb4155c4/projects/pom.xml#L59)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Was 20.5 a specific choice? They're up to 21 now. (and 22 RCs are out, but maybe we stick with last stable release for time being?)
</blockquote></details>

changed to 0.21.0

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/659)*

**Comment by dhalperi** [comment]
Reviewed 3 of 17 files at r1.
Review status: 3 of 16 files reviewed at latest revision, 7 unresolved discussions.

---

*[projects/allinone/src/main/java/org/batfish/allinone/AllInOne.java, line 133 at r3](https://reviewable.io:443/reviews/batfish/batfish/659#-KyX71nycQK0MdAObaXs:-KyX71nycQK0MdAObaXt:b-wznnox) ([raw file](https://github.com/batfish/batfish/blob/cc86285cb0b3a84c7acaf9da994ded106cde83a3/projects/allinone/src/main/java/org/batfish/allinone/AllInOne.java#L133)):*
> ```Java
>         new Configuration(
>                 BfConsts.PROP_ALLINONE_SERVICE,
>                 new SamplerConfiguration(ProbabilisticSampler.TYPE, 1),
> ```

why not `ConstSampler` configured with `true` instead of probabilistic sampler. Seems more lightweight.

---

*[projects/allinone/src/main/java/org/batfish/allinone/AllInOne.java, line 141 at r3](https://reviewable.io:443/reviews/batfish/batfish/659#-KyX77TYk5LI9wwLdQSS:-KyX77TYk5LI9wwLdQST:b-s67m5v) ([raw file](https://github.com/batfish/batfish/blob/cc86285cb0b3a84c7acaf9da994ded106cde83a3/projects/allinone/src/main/java/org/batfish/allinone/AllInOne.java#L141)):*
> ```Java
>                     // flush internal in ms
>                     10000)
>                 // max buffered Spans
> ```

fix these comments?

Usually, the way to do this in languages that have `/*`-style inline comments:

```java
/* flush interval in ms */ 1000,
```

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/BfConsts.java, line 177 at r3](https://reviewable.io:443/reviews/batfish/batfish/659#-KyX7_qvTAK_4cwWfTw4:-KyX7_qvTAK_4cwWfTw5:b-embwc5) ([raw file](https://github.com/batfish/batfish/blob/cc86285cb0b3a84c7acaf9da994ded106cde83a3/projects/batfish-common-protocol/src/main/java/org/batfish/common/BfConsts.java#L177)):*
> ```Java
>   public static final String SVC_TASKID_KEY = "taskid";
> 
>   public static final String PROP_ALLINONE_SERVICE = "batfish-allinone";
> ```

move these up in the `PROP_` list above.

---

*[projects/coordinator/pom.xml, line 34 at r3](https://reviewable.io:443/reviews/batfish/batfish/659#-KyX8eTa2ZuxlAJ2ZMa3:-KyX8eTa2ZuxlAJ2ZMa4:b-opbg0b) ([raw file](https://github.com/batfish/batfish/blob/cc86285cb0b3a84c7acaf9da994ded106cde83a3/projects/coordinator/pom.xml#L34)):*
> ```XML
>                   <ignoredUnusedDeclaredDependency>org.slf4j:slf4j-jdk14</ignoredUnusedDeclaredDependency>
>                   <ignoredUnusedDeclaredDependency>io.opentracing:opentracing-api</ignoredUnusedDeclaredDependency>
>                   <ignoredUnusedDeclaredDependency>io.opentracing:opentracing-util</ignoredUnusedDeclaredDependency>
> ```

Suspect neither of these lines is correct -- the code in `WorkMgrService` does actually directly depend on `util`, so it should not be unused. And (per below) I think you should not be explicitly including a dependence on `api`, and after removing that incorrect dependency, you will not have it listed as declared and hence unused.

---

*[projects/coordinator/pom.xml, line 123 at r3](https://reviewable.io:443/reviews/batfish/batfish/659#-KyX8RCMu7XCeXdWdDVy:-KyX8RCMu7XCeXdWdDVz:bjyotud) ([raw file](https://github.com/batfish/batfish/blob/cc86285cb0b3a84c7acaf9da994ded106cde83a3/projects/coordinator/pom.xml#L123)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>
>     <dependency>
>       <groupId>io.opentracing</groupId>
>       <artifactId>opentracing-api</artifactId>
>     </dependency>
</details>

Suspect you do not need to declare this -- you don't seem to compile against it.

---

*[projects/coordinator/pom.xml, line 125 at r3](https://reviewable.io:443/reviews/batfish/batfish/659#-KyX91-Oqmgy_vyipBuW:-KyX91-Oqmgy_vyipBuX:bfb9dwb) ([raw file](https://github.com/batfish/batfish/blob/cc86285cb0b3a84c7acaf9da994ded106cde83a3/projects/coordinator/pom.xml#L125)):*
> ```XML
>     </dependency>
> 
>     <dependency>
> ```

make the same changes (as needed) in the other `pom.xml` files.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/659)*

**Comment by dhalperi** [comment]
Reviewed 3 of 17 files at r1, 5 of 6 files at r2, 5 of 5 files at r4.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[projects/pom.xml, line 69 at r4](https://reviewable.io:443/reviews/batfish/batfish/659#-KyXM2Mm4MrI2nNjERCc:-KyXM2Mm4MrI2nNjERCd:b-uyoz9n) ([raw file](https://github.com/batfish/batfish/blob/770b09370d1742a138e639259e30d662a16d554c/projects/pom.xml#L69)):*
> ```XML
>     <junit.version>4.12</junit.version>
>     <jackson-jsonschema.version>1.0.11-batfish-internal</jackson-jsonschema.version>
>     <opentracing-jaxrs2.version>0.0.8</opentracing-jaxrs2.version>
> ```

They're up to `0.0.10`, btw.

---

*[projects/allinone/pom.xml, line 126 at r4](https://reviewable.io:443/reviews/batfish/batfish/659#-KyXMSBH4VCrYuAwPiQe:-KyXMSBH4VCrYuAwPiQf:b2f2mpu) ([raw file](https://github.com/batfish/batfish/blob/770b09370d1742a138e639259e30d662a16d554c/projects/allinone/pom.xml#L126)):*
>   <dependency>
>       <groupId>io.opentracing.contrib</groupId>
>       <artifactId>opentracing-jaxrs2</artifactId>
>       <scope>runtime</scope>
>  
>  
>  
>  
>     </dependency>
>  

I think this is not needed (and should be removed from unusedUndeclared...

---

*[projects/batfish/pom.xml, line 206 at r4](https://reviewable.io:443/reviews/batfish/batfish/659#-KyXMdSm69naaQU6LKX5:-KyXMdSm69naaQU6LKX6:bd5l6mr) ([raw file](https://github.com/batfish/batfish/blob/770b09370d1742a138e639259e30d662a16d554c/projects/batfish/pom.xml#L206)):*
> ```XML
>     <dependency>
>       <groupId>net.sf.javabdd</groupId>
>       <artifactId>bdd</artifactId>
> ```

thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/659)*

**Comment by dhalperi** [comment]
Reviewed 7 of 7 files at r5.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/659)*

**Comment by dhalperi** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/659#-:-KyXlQQdyYIZZM_BbuOO:bnfp4nl)*

**Pull request merged**
