### PR TITLE
juniper conversion for 'from condition'

### PR DESCRIPTION
**Pull request by arifogel**
- add route policy primitives for getting main rib routes
- add route policy primitives for checking presence of another route in
the main rib matching some condition
- implement conversion for juniper 'from condition' based on new route
policy primitives

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 24 of 26 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6749)* status: all files reviewed, 1 unresolved discussion (waiting on @anothermattbrown and @arifogel)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/HasMatchingRoute.java, line 46 at r2](https://reviewable.io/reviews/batfish/batfish/6749#-MWAjfPADtoPSM3ywT8K:-MWAjfPBBTuay6pnsSJ2:btd5wck) ([raw file](https://github.com/batfish/batfish/blob/d8b5092d7ae9ce7b75da53a7779ad1bc76de6cc2/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/HasMatchingRoute.java#L46)):*
> ```
>     Collection<AbstractRoute> routeCandidates =
>         _routesExpr.accept(RoutesExprEvaluator.instance(), environment);
> ```

This feels really heavyweight - build a collection of all the routes in the main RIB as a precursor to any work, when the most typical (only known?) is "is this prefix present". Is there a better way?

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6749)* status: 3 of 36 files reviewed, 1 unresolved discussion (waiting on @anothermattbrown and @dhalperi)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/HasMatchingRoute.java, line 46 at r2](https://reviewable.io/reviews/batfish/batfish/6749#-MWAjfPADtoPSM3ywT8K:-MWBysRT5r4gE2qH1j-f:b-yj9iga) ([raw file](https://github.com/batfish/batfish/blob/d8b5092d7ae9ce7b75da53a7779ad1bc76de6cc2/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/HasMatchingRoute.java#L46)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
>     Collection<AbstractRoute> routeCandidates =
>         _routesExpr.accept(RoutesExprEvaluator.instance(), environment);
> ```

This feels really heavyweight - build a collection of all the routes in the main RIB as a precursor to any work, when the most typical (only known?) is "is this prefix present". Is there a better way?
</blockquote></details>

Now `GenericRib` has function to check intersection with a `PrefixSpace`, which should be much more efficient.

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 2 of 37 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6749)* status: 5 of 36 files reviewed, 1 unresolved discussion (waiting on @dhalperi)

**Review by anothermattbrown — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6749)* status: 5 of 36 files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/PrefixTrieMultiMap.java, line 254 at r3](https://reviewable.io/reviews/batfish/batfish/6749#-MWQD4S74ho801WkHEes:-MWQD4S74ho801WkHEet:bq2lyh4) ([raw file](https://github.com/batfish/batfish/blob/eeb797b9c2a71bca75494a58cdfb27049587f9a9/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/PrefixTrieMultiMap.java#L254)):*
> ```
> return true.
> ```
probably worth documenting here that this `this node has any elements` means `_prefix` is a key.

**Review by dhalperi — COMMENTED** [review]
:lgtm:

> Reviewed 35 of 37 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6749#-:-MWQGDfk8W8MLtL7CwGJ:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @arifogel)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/GenericRibReadOnly.java, line 56 at r3](https://reviewable.io/reviews/batfish/batfish/6749#-MWQDYDf8_VSuNWBEN77:-MWQDYDf8_VSuNWBEN78:bjsmggw) ([raw file](https://github.com/batfish/batfish/blob/eeb797b9c2a71bca75494a58cdfb27049587f9a9/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/GenericRibReadOnly.java#L56)):*
> ```
>  to routes in this rib
> ```

Is it worth clarifying what we mean by this? Active routes, installed routes, forwarding routes, routing routes, etc?
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/route/nh/NextHop.java, line 19 at r3](https://reviewable.io/reviews/batfish/batfish/6749#-MWQDfeQ9tuaUEdOcJlO:-MWQDfeQ9tuaUEdOcJlP:b-v0g0gs) ([raw file](https://github.com/batfish/batfish/blob/eeb797b9c2a71bca75494a58cdfb27049587f9a9/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/route/nh/NextHop.java#L19)):*
> ```
> 4 
> ```
revert?
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/RoutingPolicy.java, line 243 at r3](https://reviewable.io/reviews/batfish/batfish/6749#-MWQDrtA2degJef9qv3B:-MWQDrtA2degJef9qv3C:b-ojrctd) ([raw file](https://github.com/batfish/batfish/blob/eeb797b9c2a71bca75494a58cdfb27049587f9a9/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/RoutingPolicy.java#L243)):*
> ```
> public boolean processBgpRoute(
> ```

kill this one? When we have a ton of them, it just leads to us using the wrong one over and over again.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/RibIntersectsPrefixSpace.java, line 50 at r3](https://reviewable.io/reviews/batfish/batfish/6749#-MWQEeKg1e8GxdgfYGq_:-MWQEeKg1e8GxdgfYGqa:bm9bnb0) ([raw file](https://github.com/batfish/batfish/blob/eeb797b9c2a71bca75494a58cdfb27049587f9a9/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/RibIntersectsPrefixSpace.java#L50)):*
> ```
> Cannot check RIB routes outside of data plane generation
> ```

Maybe something that's mildly more user-facing (just less specific to Batfish internals), such as "Cannot check RIB routes; main RIB state is not available at this time"

Also would be robust to code where we call the wrong `process` function and forget to build environment correctly.
___
*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/MockRib.java, line 83 at r3](https://reviewable.io/reviews/batfish/batfish/6749#-MWQFHnh1tO3YSl-iN_4:-MWQFHnh1tO3YSl-iN_5:b-4ni5pt) ([raw file](https://github.com/batfish/batfish/blob/eeb797b9c2a71bca75494a58cdfb27049587f9a9/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/MockRib.java#L83)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
>     return !new PrefixSpace(
>             _routes.stream()
>                 .map(AnnotatedRoute::getNetwork)
>                 .map(PrefixRange::fromPrefix)
>                 .collect(ImmutableList.toImmutableList()))
>         .intersection(prefixSpace)
>         .isEmpty();
> ```
</details>


optional: can this not be moved inside the stream / no collection needed?

Also: PrefixSpace has `overlaps` for `intersection!empty` and also has `containsPrefix` which is maybe even simpler?

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6749)* status: 30 of 39 files reviewed, 3 unresolved discussions (waiting on @anothermattbrown and @dhalperi)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/GenericRibReadOnly.java, line 56 at r3](https://reviewable.io/reviews/batfish/batfish/6749#-MWQDYDf8_VSuNWBEN77:-MWQLRItDoMlTCsdo_7v:b-h7llx2) ([raw file](https://github.com/batfish/batfish/blob/eeb797b9c2a71bca75494a58cdfb27049587f9a9/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/GenericRibReadOnly.java#L56)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
>  to routes in this rib
> ```

Is it worth clarifying what we mean by this? Active routes, installed routes, forwarding routes, routing routes, etc?
</blockquote></details>

It means any routes in this rib. Is there a need to clarify when there is no restriction?
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/PrefixTrieMultiMap.java, line 254 at r3](https://reviewable.io/reviews/batfish/batfish/6749#-MWQD4S74ho801WkHEes:-MWQNxw0BvxvpaUoMxYc:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/eeb797b9c2a71bca75494a58cdfb27049587f9a9/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/PrefixTrieMultiMap.java#L254)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

> ```
> return true.
> ```
probably worth documenting here that this `this node has any elements` means `_prefix` is a key. 
</blockquote></details>

done
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/route/nh/NextHop.java, line 19 at r3](https://reviewable.io/reviews/batfish/batfish/6749#-MWQDfeQ9tuaUEdOcJlO:-MWQMQ9z7w67jdNmWDEo:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/eeb797b9c2a71bca75494a58cdfb27049587f9a9/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/route/nh/NextHop.java#L19)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> 4 
> ```
revert?
</blockquote></details>

done
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/RoutingPolicy.java, line 243 at r3](https://reviewable.io/reviews/batfish/batfish/6749#-MWQDrtA2degJef9qv3B:-MWQN8sICyboLTMXUG3W:b-ivqdxo) ([raw file](https://github.com/batfish/batfish/blob/eeb797b9c2a71bca75494a58cdfb27049587f9a9/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/RoutingPolicy.java#L243)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> public boolean processBgpRoute(
> ```

kill this one? When we have a ton of them, it just leads to us using the wrong one over and over again.
</blockquote></details>

ok. i feel like more cleanup is warranted, but stopping at removing this one for now.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/RibIntersectsPrefixSpace.java, line 50 at r3](https://reviewable.io/reviews/batfish/batfish/6749#-MWQEeKg1e8GxdgfYGq_:-MWQKMwsAhuZSoKCX9cu:b-n9tkhd) ([raw file](https://github.com/batfish/batfish/blob/eeb797b9c2a71bca75494a58cdfb27049587f9a9/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/RibIntersectsPrefixSpace.java#L50)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> Cannot check RIB routes outside of data plane generation
> ```

Maybe something that's mildly more user-facing (just less specific to Batfish internals), such as "Cannot check RIB routes; main RIB state is not available at this time"

Also would be robust to code where we call the wrong `process` function and forget to build environment correctly.
</blockquote></details>

changed
___
*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/MockRib.java, line 83 at r3](https://reviewable.io/reviews/batfish/batfish/6749#-MWQFHnh1tO3YSl-iN_4:-MWQL8UF331bg_7IAlvf:bnvkaot) ([raw file](https://github.com/batfish/batfish/blob/eeb797b9c2a71bca75494a58cdfb27049587f9a9/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/MockRib.java#L83)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
>     return !new PrefixSpace(
>             _routes.stream()
>                 .map(AnnotatedRoute::getNetwork)
>                 .map(PrefixRange::fromPrefix)
>                 .collect(ImmutableList.toImmutableList()))
>         .intersection(prefixSpace)
>         .isEmpty();
> ```

optional: can this not be moved inside the stream / no collection needed?

Also: PrefixSpace has `overlaps` for `intersection!empty` and also has `containsPrefix` which is maybe even simpler?
</blockquote></details>

simplified

**Review by dhalperi — COMMENTED** [review]
> Reviewed 10 of 10 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6749)* status: all files reviewed, 2 unresolved discussions (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java, line 821 at r4](https://reviewable.io/reviews/batfish/batfish/6749#-MWQPkZ451isUw57hxC9:-MWQPkZ451isUw57hxCA:b-xro2ue) ([raw file](https://github.com/batfish/batfish/blob/e9749687bd4d357585f827a104fda9c4bddaf28e/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java#L821)):*
> ```Java
>           acceptIncoming =
>               importPolicy.processBgpRoute(
>                   remoteRoute, transformedIncomingRouteBuilder, sessionProperties, IN, null);
> ```

So now I'm confused which parts of the pipeline need the evaluator. Isn't importing routes from peers the main one?
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/GenericRibReadOnly.java, line 56 at r3](https://reviewable.io/reviews/batfish/batfish/6749#-MWQDYDf8_VSuNWBEN77:-MWQQ2Dr4anLidSPdNwF:bsqwmh1) ([raw file](https://github.com/batfish/batfish/blob/eeb797b9c2a71bca75494a58cdfb27049587f9a9/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/GenericRibReadOnly.java#L56)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

It means any routes in this rib. Is there a need to clarify when there is no restriction?
</blockquote></details>

I guess it depends on what "in" means? The RIB has transitive pointers to backup routes, non-forwarding routes, (maybe?) non-routing routes, etc.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6749)* status: all files reviewed, 2 unresolved discussions (waiting on @arifogel and @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java, line 821 at r4](https://reviewable.io/reviews/batfish/batfish/6749#-MWQPkZ451isUw57hxC9:-MWQTcrsDM0rNSsjq-yN:b-u4w69w) ([raw file](https://github.com/batfish/batfish/blob/e9749687bd4d357585f827a104fda9c4bddaf28e/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java#L821)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

So now I'm confused which parts of the pipeline need the evaluator. Isn't importing routes from peers the main one?
</blockquote></details>

On XR, any part of the pipeline can use the evaluator. Seems the most common is generating default routes for various protocols.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6749)* status: all files reviewed, 2 unresolved discussions (waiting on @arifogel and @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java, line 821 at r4](https://reviewable.io/reviews/batfish/batfish/6749#-MWQPkZ451isUw57hxC9:-MWQTw2B058GEEqFeRPw:buat58i) ([raw file](https://github.com/batfish/batfish/blob/e9749687bd4d357585f827a104fda9c4bddaf28e/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java#L821)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

On XR, any part of the pipeline can use the evaluator. Seems the most common is generating default routes for various protocols.
</blockquote></details>

..but on Juniper, I think it's really _any_ part that uses a policy.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6749)* status: 38 of 39 files reviewed, 2 unresolved discussions (waiting on @dhalperi)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/GenericRibReadOnly.java, line 56 at r3](https://reviewable.io/reviews/batfish/batfish/6749#-MWQDYDf8_VSuNWBEN77:-MWQXjbk-ApLnybw_3il:bvnrpcm) ([raw file](https://github.com/batfish/batfish/blob/eeb797b9c2a71bca75494a58cdfb27049587f9a9/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/GenericRibReadOnly.java#L56)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Offline discussion; "in the rib" means "returned by `{@link #getRoutes}`"
</blockquote></details>

updated

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6749)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6749)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6749)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
