### PR TITLE
Junos firewall DSCP

### PR DESCRIPTION
**Pull request by ratulm**
1. Definition of custom code-point aliases for DSCP under class-of-service
2. Using constants or custom/builtin aliases in firewall filters

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 11 of 14 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7945)* status: all files reviewed, 10 unresolved discussions (waiting on @ratulm)

___
*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 4050 at r2](https://reviewable.io/reviews/batfish/batfish/7945#-Mt_huL47sLQBFTqcT53:-Mt_huL47sLQBFTqcT54:bgnt8to) ([raw file](https://github.com/batfish/batfish/blob/367e4f73d53a0e853e640cc8cd3a6e7bae1e38c7/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L4050)):*
> ```Java
>     String aliasName = ctx.variable().getText();
>     FwFromDscp from = new FwFromDscp(aliasName);
>     _currentFwTerm.getFroms().add(from);
> ```

add reference if not builtin
___
*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 5778 at r2](https://reviewable.io/reviews/batfish/batfish/7945#-Mt_hwF11Z329pKHrOQt:-Mt_hwF2-NneyQRHAmQP:b-tqejss) ([raw file](https://github.com/batfish/batfish/blob/367e4f73d53a0e853e640cc8cd3a6e7bae1e38c7/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L5778)):*
> ```Java
>       return;
>     }
>     _currentLogicalSystem.getDscpAliases().put(aliasName, value);
> ```

add structure definition
___
*[projects/batfish/src/main/java/org/batfish/representation/juniper/DscpUtil.java, line 9 at r2](https://reviewable.io/reviews/batfish/batfish/7945#-Mt_hrJQ29Au18qVHYZ1:-Mt_hrJQ29Au18qVHYZ2:b5fubzl) ([raw file](https://github.com/batfish/batfish/blob/367e4f73d53a0e853e640cc8cd3a6e7bae1e38c7/projects/batfish/src/main/java/org/batfish/representation/juniper/DscpUtil.java#L9)):*
> ```Java
> 
> @ParametersAreNonnullByDefault
> public final class DscpUtil {
> ```

javadoc
___
*[projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromDscp.java, line 34 at r2](https://reviewable.io/reviews/batfish/batfish/7945#-Mt_i4hC0VhY9W29PMhy:-Mt_i4hC0VhY9W29PMhz:b-tdat01) ([raw file](https://github.com/batfish/batfish/blob/367e4f73d53a0e853e640cc8cd3a6e7bae1e38c7/projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromDscp.java#L34)):*
> ```Java
>   }
> 
>   private HeaderSpace toHeaderspace(JuniperConfiguration jc, Warnings w) {
> ```

No new uses of `HeaderSpace`.
Just use `AclLineMatchExprs.matchDscp` or `AclLineMatchExprs.FALSE` in the above function.
___
*[projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromDscp.java, line 50 at r2](https://reviewable.io/reviews/batfish/batfish/7945#-Mt_idqWCvzGi4rLwBbx:-Mt_idqWCvzGi4rLwBby:bodp8h2) ([raw file](https://github.com/batfish/batfish/blob/367e4f73d53a0e853e640cc8cd3a6e7bae1e38c7/projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromDscp.java#L50)):*
> ```Java
>   }
> 
>   private static Optional<Integer> toDscpValue(
> ```

nit: `@Nonnull` here and for many other functions you defined.
___
*[projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromDscp.java, line 67 at r2](https://reviewable.io/reviews/batfish/batfish/7945#-Mt_ikszDqwDs2OLPJZO:-Mt_ikszDqwDs2OLPJZP:bfh2xs0) ([raw file](https://github.com/batfish/batfish/blob/367e4f73d53a0e853e640cc8cd3a6e7bae1e38c7/projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromDscp.java#L67)):*
> ```Java
> 
>       if (!value.isPresent()) {
>         w.redFlag("Reference to unknown DSCP alias \"" + spec + "\"");
> ```

Unnecessary if you use structure definition/reference in `ConfigurationBuilder`
___
*[projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java, line 6524 at r2](https://reviewable.io/reviews/batfish/batfish/7945#-Mt_jDbH6O4ILWbFK1Dc:-Mt_jDbH6O4ILWbFK1Dd:bkislj1) ([raw file](https://github.com/batfish/batfish/blob/367e4f73d53a0e853e640cc8cd3a6e7bae1e38c7/projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java#L6524)):*
> ```Java
>         containsInAnyOrder(
>             hasComment(
>                 "200000 is not a legal code-point. Must be of form xxxxxx, where x is 1 or 0."),
> ```

Test for structure def/ref warnings instead
___
*[projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/ignored-class-of-service, line 1 at r2](https://reviewable.io/reviews/batfish/batfish/7945#-Mt_k3xV3G3n9UbozfLE:-Mt_k3xV3G3n9UbozfLF:bjn2lwj) ([raw file](https://github.com/batfish/batfish/blob/367e4f73d53a0e853e640cc8cd3a6e7bae1e38c7/projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/ignored-class-of-service#L1)):*
> ```
> #
> ```

For changes requested for lines in this file, you can keep using `_null` suffix if you still want them to be flagged as silent syntax (but not TODOs). If you want TODOs, use `todo(ctx)` in listener functions.
___
*[projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/ignored-class-of-service, line 5 at r2](https://reviewable.io/reviews/batfish/batfish/7945#-Mt_je6T3mOL-a-SEdpb:-Mt_je6T3mOL-a-SEdpc:bimyou1) ([raw file](https://github.com/batfish/batfish/blob/367e4f73d53a0e853e640cc8cd3a6e7bae1e38c7/projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/ignored-class-of-service#L5)):*
> ```
> #
> # the following (and some other) commands are ignored
> set class-of-service classifiers dscp match-dscp forwarding-class ef loss-priority low code-points ef
> ```

can this match custom name(s)? If so, add structure refs when not built-in
___
*[projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/ignored-class-of-service, line 10 at r2](https://reviewable.io/reviews/batfish/batfish/7945#-Mt_jMz96ZQCES3cjPSq:-Mt_jMz96ZQCES3cjPSr:b-8y6i8f) ([raw file](https://github.com/batfish/batfish/blob/367e4f73d53a0e853e640cc8cd3a6e7bae1e38c7/projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/ignored-class-of-service#L10)):*
> ```
> set class-of-service restricted-queues forwarding-class be 0
> set class-of-service traffic-control-profiles bfin-cos-8q-100 scheduler-map bfin-cos-8q
> set class-of-service interfaces ge-0/0/7 unit 512 output-traffic-control-profile bfin-cos-8q-2
> ```

Add listener function for this line that adds interface reference.
Optionally, also add structure defs/refs for `output-traffic-control-profile` argument if that is user-defined

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7945)* status: all files reviewed, 4 unresolved discussions (waiting on @arifogel and @ratulm)

___
*[projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java, line 6524 at r2](https://reviewable.io/reviews/batfish/batfish/7945#-Mt_jDbH6O4ILWbFK1Dc:-MtbSW_kC6fecNLzUmUj:byz5ohm) ([raw file](https://github.com/batfish/batfish/blob/367e4f73d53a0e853e640cc8cd3a6e7bae1e38c7/projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java#L6524)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Test for structure def/ref warnings instead
</blockquote></details>

added def/ref test.

("instead"? illegal definitions are not even being logged.) 
___
*[projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/ignored-class-of-service, line 5 at r2](https://reviewable.io/reviews/batfish/batfish/7945#-Mt_je6T3mOL-a-SEdpb:-MtbSqG59u-n3kVvV6fx:b-ijby6s) ([raw file](https://github.com/batfish/batfish/blob/367e4f73d53a0e853e640cc8cd3a6e7bae1e38c7/projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/ignored-class-of-service#L5)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

can this match custom name(s)? If so, add structure refs when not built-in
</blockquote></details>

Don't know. Leaving as is. 
___
*[projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/ignored-class-of-service, line 10 at r2](https://reviewable.io/reviews/batfish/batfish/7945#-Mt_jMz96ZQCES3cjPSq:-MtbYgfS4gpP6ZwCdHrz:brx54wa) ([raw file](https://github.com/batfish/batfish/blob/367e4f73d53a0e853e640cc8cd3a6e7bae1e38c7/projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/ignored-class-of-service#L10)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Add listener function for this line that adds interface reference.
Optionally, also add structure defs/refs for `output-traffic-control-profile` argument if that is user-defined
</blockquote></details>

properly fleshing out the class-of-service grammar is beyond the scope of this PR. leaving as is for now.

**Review by arifogel — COMMENTED** [review]
> Reviewed 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7945)* status: all files reviewed, 4 unresolved discussions (waiting on @ratulm)

___
*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 4054 at r3](https://reviewable.io/reviews/batfish/batfish/7945#-MtdLJLsEORXfOuMo2nW:-MtdLJLt5AolPfvJok39:b-c1vj9p) ([raw file](https://github.com/batfish/batfish/blob/5fde4f71ff49ddeab41d2c7d20eb5d999efd3d8f/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L4054)):*
> ```Java
>     FwFromDscp from = new FwFromDscp(dscpSpec);
>     try {
>       Integer.parseInt(dscpSpec);
> ```

suggestion: Use google primitives' `Ints.tryParse` (returns null instead of throwing) for cleaner code flow. Personally I prefer `Xs.tryParse` over the builtins whenever the otherwise-exceptional case is not an error path.
___
*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 4056 at r3](https://reviewable.io/reviews/batfish/batfish/7945#-MtdR86E5XJl_zVek9q0:-MtdPTzL0iF5Yt9g8Usw:b4dlhew) ([raw file](https://github.com/batfish/batfish/blob/5fde4f71ff49ddeab41d2c7d20eb5d999efd3d8f/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L4056)):*
> ```Java
>       Integer.parseInt(dscpSpec);
>     } catch (NumberFormatException ignored) {
>       // if it is not a builtin alias or it has been overridden, we add a reference
> ```

Should probably fix, but TODO is fine for now
___
*[projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromDscp.java, line 37 at r3](https://reviewable.io/reviews/batfish/batfish/7945#-MtdQHV00V7rdDZc7Yg7:-MtdQHV00V7rdDZc7Yg8:bhcph9x) ([raw file](https://github.com/batfish/batfish/blob/5fde4f71ff49ddeab41d2c7d20eb5d999efd3d8f/projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromDscp.java#L37)):*
> ```Java
>     return dscpValue
>         .map(value -> AclLineMatchExprs.matchDscp(value, getTraceElement()))
>         .orElse(new FalseExpr(getTraceElement()));
> ```

Use different trace element for false case, e.g. "Treating match undefined dscp whatever as not matching".
___
*[projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java, line 6524 at r2](https://reviewable.io/reviews/batfish/batfish/7945#-Mt_jDbH6O4ILWbFK1Dc:-MtdRZNqAWL-WfriBxsI:b-mvyrn8) ([raw file](https://github.com/batfish/batfish/blob/367e4f73d53a0e853e640cc8cd3a6e7bae1e38c7/projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java#L6524)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

added def/ref test.

("instead"? illegal definitions are not even being logged.) 
</blockquote></details>

Misread what was being tested on this line, never mind.
___
*[projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/ignored-class-of-service, line 10 at r2](https://reviewable.io/reviews/batfish/batfish/7945#-Mt_jMz96ZQCES3cjPSq:-MtdRrT819ypgn1Kh--A:bxov0ao) ([raw file](https://github.com/batfish/batfish/blob/367e4f73d53a0e853e640cc8cd3a6e7bae1e38c7/projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/ignored-class-of-service#L10)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

properly fleshing out the class-of-service grammar is beyond the scope of this PR. leaving as is for now. 
</blockquote></details>

That's fine, but please add TODO right here.

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7945)* status: 14 of 18 files reviewed, 1 unresolved discussion (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 4054 at r3](https://reviewable.io/reviews/batfish/batfish/7945#-MtdLJLsEORXfOuMo2nW:-MtdaWUpErHrq5ftBSMf:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/5fde4f71ff49ddeab41d2c7d20eb5d999efd3d8f/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L4054)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

suggestion: Use google primitives' `Ints.tryParse` (returns null instead of throwing) for cleaner code flow. Personally I prefer `Xs.tryParse` over the builtins whenever the otherwise-exceptional case is not an error path.
</blockquote></details>

Done.

**Review by arifogel — COMMENTED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7945)* status: all files reviewed, 2 unresolved discussions (waiting on @ratulm)

___
*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 4053 at r4](https://reviewable.io/reviews/batfish/batfish/7945#-Mte887-9KXmlUisKwrU:-Mte887-9KXmlUisKwrV:bo5vl6b) ([raw file](https://github.com/batfish/batfish/blob/b0fe145a00e8eda0df6ac7fb212bf5d70bd1b67d/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L4053)):*
> ```Java
>   public void exitFftf_dscp(Fftf_dscpContext ctx) {
>     String dscpSpec = ctx.variable().getText();
>     FwFromDscp from = new FwFromDscp(dscpSpec);
> ```

Optional: split FwFromDscp into variants for literal and reference to clean up the API and have simpler individual implementations.
___
*[projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromDscp.java, line 41 at r4](https://reviewable.io/reviews/batfish/batfish/7945#-Mte7JOM6CknRcBwTTKG:-Mte7JONBCWG9plCvBHe:bgh7pk0) ([raw file](https://github.com/batfish/batfish/blob/b0fe145a00e8eda0df6ac7fb212bf5d70bd1b67d/projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromDscp.java#L41)):*
> ```Java
>           : new FalseExpr(
>               TraceElement.of(
>                   String.format("Treated illegal DSCP value '%d' as not matching", value)));
> ```

To clarify, the box doesn't immediately reject illegal numeric DSCP values? It just never matches them?

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7945)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromDscp.java, line 41 at r4](https://reviewable.io/reviews/batfish/batfish/7945#-Mte7JOM6CknRcBwTTKG:-Mte9GYY7e2QfI1o2YG9:bdlqe75) ([raw file](https://github.com/batfish/batfish/blob/b0fe145a00e8eda0df6ac7fb212bf5d70bd1b67d/projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromDscp.java#L41)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

To clarify, the box doesn't immediately reject illegal numeric DSCP values? It just never matches them?
</blockquote></details>

Yeah, I could type and successfully commit any value. I didn't do a post-commit behavior check.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7945)* status: all files reviewed, 1 unresolved discussion (waiting on @ratulm)

___
*[projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromDscp.java, line 41 at r4](https://reviewable.io/reviews/batfish/batfish/7945#-Mte7JOM6CknRcBwTTKG:-MteETup5w2zg5i3yW4x:b-c6dgbs) ([raw file](https://github.com/batfish/batfish/blob/b0fe145a00e8eda0df6ac7fb212bf5d70bd1b67d/projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromDscp.java#L41)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

Yeah, I could type and successfully commit any value. I didn't do a post-commit behavior check. 
</blockquote></details>

If you didn't test, add a TODO or just test it and confirm behavior (always/never matches)

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7945)* status: all files reviewed, 1 unresolved discussion (waiting on @ratulm)

___
*[projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromDscp.java, line 41 at r4](https://reviewable.io/reviews/batfish/batfish/7945#-Mte7JOM6CknRcBwTTKG:-MteEm4Q4xV7Mj74iFIM:b-otu4m8) ([raw file](https://github.com/batfish/batfish/blob/b0fe145a00e8eda0df6ac7fb212bf5d70bd1b67d/projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromDscp.java#L41)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

If you didn't test, add a TODO or just test it and confirm behavior (always/never matches)
</blockquote></details>

Does an undefined name not commit? If undefined name commits, then invalid values might be treated as names.

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7945)* status: 17 of 18 files reviewed, 1 unresolved discussion (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromDscp.java, line 41 at r4](https://reviewable.io/reviews/batfish/batfish/7945#-Mte7JOM6CknRcBwTTKG:-MteFrgCB-nIrJaIMwQz:b-xfel3n) ([raw file](https://github.com/batfish/batfish/blob/b0fe145a00e8eda0df6ac7fb212bf5d70bd1b67d/projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromDscp.java#L41)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Does an undefined name not commit? If undefined name commits, then invalid values might be treated as names.
</blockquote></details>

Undefined names also commit. I added a TODO about not having tested behavior. 

I'll open an issue and try to come back to it.

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7945)* status: 17 of 18 files reviewed, 1 unresolved discussion (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromDscp.java, line 41 at r4](https://reviewable.io/reviews/batfish/batfish/7945#-Mte7JOM6CknRcBwTTKG:-MteMRnM4HfBnDRw8Exo:b8pbl7t) ([raw file](https://github.com/batfish/batfish/blob/b0fe145a00e8eda0df6ac7fb212bf5d70bd1b67d/projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromDscp.java#L41)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

Undefined names also commit. I added a TODO about not having tested behavior. 

I'll open an issue and try to come back to it. 
</blockquote></details>

https://github.com/batfish/batfish/issues/7950

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7945)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ratulm)

**Pull request merged**
