### PR TITLE
bdp: optimize to run fewer topology iterations

### PR DESCRIPTION
**Pull request by progwriter**
No need to run extra routing iterations if the topology didn't change.

### CODE REVIEW

**Comment by dhalperi** [comment]
This is a functional 5-line version, but let me try to resurrect my proper fix PR (and port it forward)? That had a lot more improvements.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6309)* status: all files reviewed, 1 unresolved discussion (waiting on @progwriter)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java, line 277 at r1](https://reviewable.io/reviews/batfish/batfish/6309#-MJ_Id92-lODeDRCwCNi:-MJ_Id92-lODeDRCwCNj:b-51xk4y) ([raw file](https://github.com/batfish/batfish/blob/91b7acfaa272efe215987e6422ddfd08e7aaa4aa/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java#L277)):*
> ```
> computeFibs(nodes);
> ```

This should no longer be necessary, because fibs were computed in `nextTopologyContext`

**Review by progwriter — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6309)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java, line 277 at r1](https://reviewable.io/reviews/batfish/batfish/6309#-MJ_Id92-lODeDRCwCNi:-MJ_Jdir4su_nFk-CqTo:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/91b7acfaa272efe215987e6422ddfd08e7aaa4aa/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java#L277)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> computeFibs(nodes);
> ```

This should no longer be necessary, because fibs were computed in `nextTopologyContext`
</blockquote></details>

done

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6309)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
