### PR TITLE
IOS: Support VRF-specific NAT rules

### PR DESCRIPTION
**Pull request by corinaminer**

### CODE REVIEW

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6524)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @progwriter)

___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 6246 at r1](https://reviewable.io/reviews/batfish/batfish/6524#-MPCYFbO0Gv0G_JmVYPY:-MPCYFbO0Gv0G_JmVYPZ:b-r8nhrq) ([raw file](https://github.com/batfish/batfish/blob/4202df8757582874ee165086f6d5fa6a097a5c54/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L6246)):*
> ```Java
> 
>   @Override
>   public void exitIpnios_static_addr(Ipnios_static_addrContext ctx) {
> ```

@progwriter I saw that you wrote the `ipnios_static_addr` and `ipnios_static_network` extraction functions in #6385, but I couldn't figure out why they were both implementing the `enter` functions or why only `ipnios_static_addr` was clearing `_currentIosSourceNat` on exit. I updated them to use only the `exit` functions and leave `_currentIosSourceNat` set (so its VRF can be set later if necessary), but let me know if there's some reason it has to be weird.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 3 of 7 files at r1, 1 of 1 files at r2, 2 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6524)* status: 6 of 9 files reviewed, 2 unresolved discussions (waiting on @corinaminer and @progwriter)

___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 6248 at r3](https://reviewable.io/reviews/batfish/batfish/6524#-MPH89BK6ZEaTjkn_6C4:-MPH89BK6ZEaTjkn_6C5:btbnpne) ([raw file](https://github.com/batfish/batfish/blob/5868a621f953872965d233e580772f0c28ea5ff5/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L6248)):*
> ```Java
>   @Override
>   public void exitIpnios_static_addr(Ipnios_static_addrContext ctx) {
>     CiscoIosStaticNat staticNat = new CiscoIosStaticNat();
> ```

Corina is right the old pattern is wrong, but the new pattern doesn't feel safe. 

The invariant that is safest is that enter/exit rules are paired in setting and clearing the property, and all rules that rely on the property being set are children of the parent.

```
enterP
   set _currentFoo
    exitChild
       use currentFoo
 exitP
   clear currentFoo
```

Instead, we're setting in siblings and clearing in parent. Feels risky.

```
enterP
   exitSpecialChild
      set currentFoo
    exitChild
      use currentFoo
exitP
   clear currentFoo
```

I'd rewrite the rules to maintain the expected invariant.
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 1997 at r3](https://reviewable.io/reviews/batfish/batfish/6524#-MPH8yKAAxTL0cNJUHPg:-MPH8yKAAxTL0cNJUHPh:b665n5j) ([raw file](https://github.com/batfish/batfish/blob/5868a621f953872965d233e580772f0c28ea5ff5/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L1997)):*
> ```Java
> 
>     // whether this interface is in the default VRF
>     boolean inDefaultVrf = vrfName.equals(Configuration.DEFAULT_VRF_NAME);
> ```

simpler:

```
String natVrf = firstNonNull(nat.getVrf(), Configuration.DEFAULT_VRF_NAME);
```

and then use `natVrf` everywhere below

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6524)* status: 4 of 9 files reviewed, 1 unresolved discussion (waiting on @dhalperi and @progwriter)

___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 6248 at r3](https://reviewable.io/reviews/batfish/batfish/6524#-MPH89BK6ZEaTjkn_6C4:-MPHJiaF7dSFzNAIZ0mc:bcnj0z4) ([raw file](https://github.com/batfish/batfish/blob/5868a621f953872965d233e580772f0c28ea5ff5/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L6248)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Corina is right the old pattern is wrong, but the new pattern doesn't feel safe. 

The invariant that is safest is that enter/exit rules are paired in setting and clearing the property, and all rules that rely on the property being set are children of the parent.

```
enterP
   set _currentFoo
    exitChild
       use currentFoo
 exitP
   clear currentFoo
```

Instead, we're setting in siblings and clearing in parent. Feels risky.

```
enterP
   exitSpecialChild
      set currentFoo
    exitChild
      use currentFoo
exitP
   clear currentFoo
```

I'd rewrite the rules to maintain the expected invariant.
</blockquote></details>

Agree that that's a good pattern to maintain. Updated so that the parent (`ipnis_static` or `ipnos_static` both sets and clears `_currentIosStaticNat`. Setup is still a little weird, though, because the nat isn't added to the configuration until its local and global IPs are set in `ipnios_static_addr` or `ipnios_static_network`. What do you think is best?
1. Current setup: add `_currentIosStaticNat` to configuration once its IPs are configured (in child that configures IPs)
2. Add `_currentIosStaticNat` to configuration as soon as it's created, and make conversion robust to invalid NAT rules (missing IPs)
3. Check if `_currentIosStaticNat` is valid (has IPs set) when exiting `ipnis_static` or `ipnos_static`, right before clearing it, and if so add it to the configuration there
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 1997 at r3](https://reviewable.io/reviews/batfish/batfish/6524#-MPH8yKAAxTL0cNJUHPg:-MPHAHQd6uAoBHlxZFxk:b4nrn97) ([raw file](https://github.com/batfish/batfish/blob/5868a621f953872965d233e580772f0c28ea5ff5/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L1997)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

simpler:

```
String natVrf = firstNonNull(nat.getVrf(), Configuration.DEFAULT_VRF_NAME);
```

and then use `natVrf` everywhere below
</blockquote></details>

done, plus a bit more refactoring. for loop makes more sense than streams here

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 7 files at r1, 2 of 4 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6524)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @progwriter)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6524)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @progwriter)

**Pull request merged**
