### PR TITLE
Checkpoint: add ServiceOther

### PR DESCRIPTION
**Pull request by dhalperi**

### CODE REVIEW

**Review by sfraint — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7353)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7353)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel and @dhalperi)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7353#-Mj68msS43A6463salIt:-Mj68msS43A6463salIu:bb6ue6z) (no related file):*
Pending: `match` and `match-any` and what to do for these.

---

**Review by arifogel — COMMENTED** [review]
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7353)* status: all files reviewed, 4 unresolved discussions (waiting on @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/ServiceOther.java, line 44 at r3](https://reviewable.io/reviews/batfish/batfish/7353#-MjaBxy40SOgzBuGs-GE:-MjaBxy40SOgzBuGs-GF:boecrxl) ([raw file](https://github.com/batfish/batfish/blob/7b354a69be4f3e7ca6e3c121bfc0af6598478293/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/ServiceOther.java#L44)):*
> ```Java
>   @Override
>   public String toString() {
>     return baseToStringHelper().add(PROP_IP_PROTOCOL, _ipProtocol).toString();
> ```

What about match string?
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/ServiceToMatchExpr.java, line 62 at r3](https://reviewable.io/reviews/batfish/batfish/7353#-MjaCHXg43Uyt-4ZXs0O:-MjaCHXh-UlZYHzBJRhS:by3orci) ([raw file](https://github.com/batfish/batfish/blob/7b354a69be4f3e7ca6e3c121bfc0af6598478293/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/ServiceToMatchExpr.java#L62)):*
> ```Java
>     if (Strings.isNullOrEmpty(serviceOther.getMatch())) {
>       HeaderSpace.Builder hsb = HeaderSpace.builder();
>       hsb.setIpProtocols(IpProtocol.fromNumber(serviceOther.getIpProtocol()));
> ```

Could just do `AclLinematchExprs.matchIpProtocol` and ditch HeaderSpace
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/ServiceToMatchExpr.java, line 65 at r3](https://reviewable.io/reviews/batfish/batfish/7353#-MjaCgkj0EKgsdYUrD3q:-MjaCgkj0EKgsdYUrD3r:brmk1zo) ([raw file](https://github.com/batfish/batfish/blob/7b354a69be4f3e7ca6e3c121bfc0af6598478293/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/ServiceToMatchExpr.java#L65)):*
> ```Java
>       return AclLineMatchExprs.match(hsb.build(), serviceOtherTraceElement(serviceOther));
>     }
>     if (serviceOther.getMatch().equals("uh_dport > 33000, (IPV4_VER (ip_ttl < 30))")) {
> ```

Out of scope since a lot of work, but we should probably support matching TTL in header at some point.
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/ServiceToMatchExpr.java, line 68 at r3](https://reviewable.io/reviews/batfish/batfish/7353#-MjaCMd2AV1t_GAGnHJK:-MjaCMd2AV1t_GAGnHJL:b-nunp2a) ([raw file](https://github.com/batfish/batfish/blob/7b354a69be4f3e7ca6e3c121bfc0af6598478293/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/ServiceToMatchExpr.java#L68)):*
> ```Java
>       HeaderSpace.Builder hsb = HeaderSpace.builder();
>       hsb.setIpProtocols(IpProtocol.fromNumber(serviceOther.getIpProtocol()));
>       hsb.setDstPorts(new SubRange(33001, 65535));
> ```

Could do `AclLineMatchExprs.matchDst` and ditch HeaderSpace

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7353)* status: all files reviewed, 4 unresolved discussions (waiting on @dhalperi)

**Pull request closed without merging**
