### PR TITLE
IOS-XR as-path set and as-path boolean parsing

### PR DESCRIPTION
**Pull request by arifogel**
- redo lexing/parsing for all of as-path-set and as-path boolean
- remove broken extractor implementations for various as-path booleans
- begin transition to listener-based policy extraction, as opposed to recursion-based

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 8 of 8 files at r1, 5 of 5 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6986)* status: all files reviewed, 3 unresolved discussions (waiting on @arifogel, @corinaminer, and @sfraint)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_as_path_set.g4, line 18 at r1](https://reviewable.io/reviews/batfish/batfish/6986#-MZzpnnJ-4G32g9sIFU3:-MZzpnnJ-4G32g9sIFU4:bimrtoc) ([raw file](https://github.com/batfish/batfish/blob/f8953e4e5f5035a7a2a22c1924a527750f441d93/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_as_path_set.g4#L18)):*
> ```ANTLR
> :
>    // no elements
>    | elems += as_path_set_elem (COMMA elems += as_path_set_elem)*
> ```

Do we need the REMARK handling here like in extcomm-set or whatever it was?
___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java, line 8118 at r2](https://reviewable.io/reviews/batfish/batfish/6986#-MZzrumQBU-O0ZWIGue7:-MZzrumQBU-O0ZWIGue8:b-84ygxi) ([raw file](https://github.com/batfish/batfish/blob/5755e0017c87a2f699fa40425eb57671db5de2ea/projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java#L8118)):*
> ```
>     _asPathBooleansByCtx.put(
>         ctx, firstNonNull(_currentAsPathBoolean, UnimplementedBoolean.instance()));
> ```

TBH I can't really tell how this works, but if it's short-term and WFY then great.
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_xr/AsPathSet.java, line 30 at r2](https://reviewable.io/reviews/batfish/batfish/6986#-MZzqyM-Akr6Tm3QI6GA:-MZzqyM09rFoIwweXlNS:b-s4v3t5) ([raw file](https://github.com/batfish/batfish/blob/5755e0017c87a2f699fa40425eb57671db5de2ea/projects/batfish/src/main/java/org/batfish/representation/cisco_xr/AsPathSet.java#L30)):*
> ```
> builder()
> ```

FYI: can use BuilderWithExpectedSize in such cases, likely won't matter in practice. Probably defaults to 16 which captures all sensible sets.
___
*[projects/batfish/src/test/resources/org/batfish/grammar/cisco_xr/testconfigs/xr-as-path-set, line 16 at r1](https://reviewable.io/reviews/batfish/batfish/6986#-MZzqWFN2s-KvOGnGtdk:-MZzqWFN2s-KvOGnGtdl:b-99wx2w) ([raw file](https://github.com/batfish/batfish/blob/f8953e4e5f5035a7a2a22c1924a527750f441d93/projects/batfish/src/test/resources/org/batfish/grammar/cisco_xr/testconfigs/xr-as-path-set#L16)):*
> ```
>  length le 7,
>  length le 8 all,
>  neighbor-is '1 [2..3]',
> ```

Same Q re remark lines

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6986)* status: all files reviewed, 2 unresolved discussions (waiting on @corinaminer, @dhalperi, and @sfraint)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_as_path_set.g4, line 18 at r1](https://reviewable.io/reviews/batfish/batfish/6986#-MZzpnnJ-4G32g9sIFU3:-MZzsqFP81oTJaNWNlof:b8pfvm4) ([raw file](https://github.com/batfish/batfish/blob/f8953e4e5f5035a7a2a22c1924a527750f441d93/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_as_path_set.g4#L18)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Do we need the REMARK handling here like in extcomm-set or whatever it was?
</blockquote></details>

This structure is analogous to what we just used for `rd-set` grammar. Just checked.

Remarks are thrown away in the lexer. I copied the pattern for that as well. Seems to be working fine. 
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_xr/AsPathSet.java, line 30 at r2](https://reviewable.io/reviews/batfish/batfish/6986#-MZzqyM-Akr6Tm3QI6GA:-MZztwwhB56M87I0sc0m:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/5755e0017c87a2f699fa40425eb57671db5de2ea/projects/batfish/src/main/java/org/batfish/representation/cisco_xr/AsPathSet.java#L30)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> builder()
> ```

FYI: can use BuilderWithExpectedSize in such cases, likely won't matter in practice. Probably defaults to 16 which captures all sensible sets.
</blockquote></details>

done
___
*[projects/batfish/src/test/resources/org/batfish/grammar/cisco_xr/testconfigs/xr-as-path-set, line 16 at r1](https://reviewable.io/reviews/batfish/batfish/6986#-MZzqWFN2s-KvOGnGtdk:-MZztLtf9y0PvmmFGLzI:b-e6cf59) ([raw file](https://github.com/batfish/batfish/blob/f8953e4e5f5035a7a2a22c1924a527750f441d93/projects/batfish/src/test/resources/org/batfish/grammar/cisco_xr/testconfigs/xr-as-path-set#L16)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Same Q re remark lines
</blockquote></details>

Added some remarks here for coverage.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6986)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer and @sfraint)

___
*[projects/batfish/src/test/resources/org/batfish/grammar/cisco_xr/testconfigs/xr-as-path-set, line 16 at r1](https://reviewable.io/reviews/batfish/batfish/6986#-MZzqWFN2s-KvOGnGtdk:-MZzuIss9hUVWIqEak0K:b-tmzwb7) ([raw file](https://github.com/batfish/batfish/blob/f8953e4e5f5035a7a2a22c1924a527750f441d93/projects/batfish/src/test/resources/org/batfish/grammar/cisco_xr/testconfigs/xr-as-path-set#L16)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Added some remarks here for coverage.
</blockquote></details>

Thank. Forgot we fixed it in Lex.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6986)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer and @sfraint)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6986)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer and @sfraint)

**Pull request merged**
