### PR TITLE
Add support for some servers in PAN data model

### PR DESCRIPTION
**Pull request by sfraint**
Add extraction and conversion of `DNS` and `NTP` servers defined in PAN configs

### CODE REVIEW

**Comment by arifogel** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_deviceconfig.g4, line 45 at r2](https://reviewable.io/reviews/batfish/batfish/1604#-LEMj0-r5TdQTiXJlP1R:-LEMj0-r5TdQTiXJlP1S:b-e9cgmw) ([raw file](https://github.com/batfish/batfish/blob/acda877c11bd61e1233a3d2d5269df500f335693/projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_deviceconfig.g4#L45)):*
> ```ANTLR
>    (
>       PRIMARY primary_name = IP_ADDRESS
>       | SECONDARY secondary_name = IP_ADDRESS
> ```

Only two allowed? This is unusual. Are you sure you cannot have more secondaries? Applies to other server types as well. What if you specify only one secondary per line, but have more than one secondary line? Does it use all of them or only the last one?

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4, line 87 at r2](https://reviewable.io/reviews/batfish/batfish/1604#-LEMjE0f44Nf4SDZ8OHy:-LEMjE0f44Nf4SDZ8OHz:b-j2myxx) ([raw file](https://github.com/batfish/batfish/blob/acda877c11bd61e1233a3d2d5269df500f335693/projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4#L87)):*
> ```ANTLR
> IP_PREFIX
> :
>    F_IpAddress '/' F_Digit
> ```

Just one digit?

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4, line 111 at r2](https://reviewable.io/reviews/batfish/batfish/1604#-LEMjcPH6_u_MDkKflGG:-LEMjcPH6_u_MDkKflGH:b-uaqnp8) ([raw file](https://github.com/batfish/batfish/blob/acda877c11bd61e1233a3d2d5269df500f335693/projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4#L111)):*
> ```ANTLR
> :
>    (
>    F_Digit
> ```

Indentation

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4, line 120 at r2](https://reviewable.io/reviews/batfish/batfish/1604#-LEMjNFp54JQn8cvqbDx:-LEMjNFp54JQn8cvqbDy:b-4kwe35) ([raw file](https://github.com/batfish/batfish/blob/acda877c11bd61e1233a3d2d5269df500f335693/projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4#L120)):*
> ```ANTLR
> F_DecByteThreeDigit
> :
>    [12] F_Digit F_Digit
> ```

This rule allows e.g. 260, which is not a byte value in [0-255]

---

*[projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java, line 77 at r2](https://reviewable.io/reviews/batfish/batfish/1604#-LEMjpaQBLIfpAstpOYl:-LEMjpaQBLIfpAstpOYm:b-eoyjn) ([raw file](https://github.com/batfish/batfish/blob/acda877c11bd61e1233a3d2d5269df500f335693/projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java#L77)):*
> ```Java
>   public void exitSdsn_ntp_server_address(Sdsn_ntp_server_addressContext ctx) {
>     if (_currentNtpServerPrimary) {
>       _configuration.setNtpServerPrimary(ctx.IP_ADDRESS().getText());
> ```

If NTP server does not have to be IP address, then parser rule for it should be more liberal. Same applies for other server types.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1604)*

**Comment by sfraint** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_deviceconfig.g4, line 45 at r2](https://reviewable.io/reviews/batfish/batfish/1604#-LEMj0-r5TdQTiXJlP1R:-LEMnAwA0ctFiftvrSLz:b8qxasy) ([raw file](https://github.com/batfish/batfish/blob/acda877c11bd61e1233a3d2d5269df500f335693/projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_deviceconfig.g4#L45)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Only two allowed? This is unusual. Are you sure you cannot have more secondaries? Applies to other server types as well. What if you specify only one secondary per line, but have more than one secondary line? Does it use all of them or only the last one?
</blockquote></details>

It is a little odd
If you set secondary multiple times, only the most recent one takes effect

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4, line 87 at r2](https://reviewable.io/reviews/batfish/batfish/1604#-LEMjE0f44Nf4SDZ8OHy:-LEMnNFK7Gv9c8yDyVZO:bepcxvn) ([raw file](https://github.com/batfish/batfish/blob/acda877c11bd61e1233a3d2d5269df500f335693/projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4#L87)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Just one digit?
</blockquote></details>

Woops, fixed.

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4, line 111 at r2](https://reviewable.io/reviews/batfish/batfish/1604#-LEMjcPH6_u_MDkKflGG:-LEQG28iBvuuEcIGyhDG:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/acda877c11bd61e1233a3d2d5269df500f335693/projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4#L111)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Indentation
</blockquote></details>

Done.

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4, line 120 at r2](https://reviewable.io/reviews/batfish/batfish/1604#-LEMjNFp54JQn8cvqbDx:-LEMnQom0J4ibL8j28Rg:b-7dbb3m) ([raw file](https://github.com/batfish/batfish/blob/acda877c11bd61e1233a3d2d5269df500f335693/projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4#L120)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

This rule allows e.g. 260, which is not a byte value in [0-255]
</blockquote></details>

Yeah, I was going to put a comment here about this:
How strict do we want to be about this? I think `cisco` and `juniper` are even less strict than this (iirc any non-zero leading digit works)
Should we enforce only up to 255? or leave it relaxed for simplicity?

---

*[projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java, line 77 at r2](https://reviewable.io/reviews/batfish/batfish/1604#-LEMjpaQBLIfpAstpOYl:-LEMo3Ad5PYU0G0TEMXy:b-68sebs) ([raw file](https://github.com/batfish/batfish/blob/acda877c11bd61e1233a3d2d5269df500f335693/projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java#L77)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

If NTP server does not have to be IP address, then parser rule for it should be more liberal. Same applies for other server types.
</blockquote></details>

Good catch, it looks like `ntp` server can be something other than an ip address here

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1604)*

**Comment by anothermattbrown** [comment]
Reviewed 1 of 7 files at r1, 2 of 6 files at r3.
Review status: 4 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4, line 120 at r2](https://reviewable.io/reviews/batfish/batfish/1604#-LEMjNFp54JQn8cvqbDx:-LEQbU4p5gQfZvz-aVUv:b-pju0w6) ([raw file](https://github.com/batfish/batfish/blob/acda877c11bd61e1233a3d2d5269df500f335693/projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4#L120)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

Yeah, I was going to put a comment here about this:
How strict do we want to be about this? I think `cisco` and `juniper` are even less strict than this (iirc any non-zero leading digit works)
Should we enforce only up to 255? or leave it relaxed for simplicity?
</blockquote></details>

Parsing may not be the right place to deal with this, unless the whether the value is in the allowed range affects how the rest of the file is parsed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1604)*

**Comment by arifogel** [comment]
Reviewed 5 of 6 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4, line 87 at r2](https://reviewable.io/reviews/batfish/batfish/1604#-LEMjE0f44Nf4SDZ8OHy:-LEQd3vwEz6K1J13_7oH:b-pobfnj) ([raw file](https://github.com/batfish/batfish/blob/acda877c11bd61e1233a3d2d5269df500f335693/projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4#L87)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

Woops, fixed.
</blockquote></details>

I actually think it's important to get this right.
There are two solutions:
1. semantic check after second digit that integer value is in [0.32]
2. definition that imposes this.
I like 2 better.

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4, line 120 at r2](https://reviewable.io/reviews/batfish/batfish/1604#-LEMjNFp54JQn8cvqbDx:-LEQdM88Eiiw4cqEFE-4:b-l3qdqm) ([raw file](https://github.com/batfish/batfish/blob/acda877c11bd61e1233a3d2d5269df500f335693/projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4#L120)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

Parsing may not be the right place to deal with this, unless the whether the value is in the allowed range affects how the rest of the file is parsed.
</blockquote></details>

Lexing is in fact the right place to do this, because if the value is higher than 255 the whole thing is interpreted as a dns name I believe.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1604)*

**Comment by arifogel** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4, line 120 at r2](https://reviewable.io/reviews/batfish/batfish/1604#-LEMjNFp54JQn8cvqbDx:-LEQdoEAC0TZJD5nrw8x:b-279dkl) ([raw file](https://github.com/batfish/batfish/blob/acda877c11bd61e1233a3d2d5269df500f335693/projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4#L120)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Lexing is in fact the right place to do this, because if the value is higher than 255 the whole thing is interpreted as a dns name I believe.
</blockquote></details>

@anothermattbrown I think if you don't catch it here, then there is no reason to even restrict the number of digits

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1604)*

**Comment by sfraint** [comment]
Review status: 5 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4, line 87 at r2](https://reviewable.io/reviews/batfish/batfish/1604#-LEMjE0f44Nf4SDZ8OHy:-LEQtcL-4tWx-ZZ8lyfJ:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/acda877c11bd61e1233a3d2d5269df500f335693/projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4#L87)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

I actually think it's important to get this right.
There are two solutions:
1. semantic check after second digit that integer value is in [0.32]
2. definition that imposes this.
I like 2 better.
</blockquote></details>

Done.

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4, line 120 at r2](https://reviewable.io/reviews/batfish/batfish/1604#-LEMjNFp54JQn8cvqbDx:-LEQtjsPAG7v9anUukmG:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/acda877c11bd61e1233a3d2d5269df500f335693/projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4#L120)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

@anothermattbrown I think if you don't catch it here, then there is no reason to even restrict the number of digits
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1604)*

**Comment by arifogel** [comment]
Reviewed 1 of 6 files at r3, 1 of 3 files at r4, 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1604)*

**Comment by arifogel** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1604#-:-LER5xc20NMDa8RkkIpf:bnfp4nl)*

**Comment by arifogel** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1604)*

**Pull request merged**
