### PR TITLE
Improve flow dispositions for network/broadcast IPs

### PR DESCRIPTION
**Pull request by anothermattbrown**
Previously, network or broadcast IPs always failed with INSUFFICIENT_INFO, even at their connected network. Now they succeed with DELIVERED_TO_SUBNET at their connected network, and fail with INSUFFICIENT_INFO everywhere else.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 7 files at r1, 6 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7127)* status: 8 of 9 files reviewed, 3 unresolved discussions (waiting on @anothermattbrown)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysisImpl.java, line 1312 at r2](https://reviewable.io/reviews/batfish/batfish/7127#-Meb36Qu8s3cpAEh58mM:-Meb36Qw0__QGUwvS-SZ:b-fxmzf5) ([raw file](https://github.com/batfish/batfish/blob/d09b44a3483aa44af65cf830eb366f85d732694f/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysisImpl.java#L1312)):*
> ```
>    * @param interfaceExternalArpIps Set of IPs for which some external device (not modeled by
>    *     Batfish) would reply to ARP in the real world.
> ```
optionally update here and computeDTS to reflect new logic
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysisImpl.java, line 1362 at r2](https://reviewable.io/reviews/batfish/batfish/7127#-Meb3Dc23GqvGh4BE7Oa:-Meb3Dc23GqvGh4BE7Ob:bxzzsku) ([raw file](https://github.com/batfish/batfish/blob/d09b44a3483aa44af65cf830eb366f85d732694f/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysisImpl.java#L1362)):*
> ```Java
>                                     interfaceExternalArpIps.get(hostname).get(ifaceName));
> 
>                             // case 1: arp for dst ip, dst ip is internal but not in any subnet of
> ```

maybe some of this needs updating?
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysisImpl.java, line 1651 at r2](https://reviewable.io/reviews/batfish/batfish/7127#-Meb3H9NB8jiAkMRdm3P:-Meb3H9NB8jiAkMRdm3Q:bslxrdl) ([raw file](https://github.com/batfish/batfish/blob/d09b44a3483aa44af65cf830eb366f85d732694f/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysisImpl.java#L1651)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>                       if (!leftOnly.isZero()) {
>                         System.out.println(
>                             Ip.create(toBDD.getBDDInteger().getValueSatisfying(leftOnly).get()));
>                         leftOnly.isZero();
>                       }
> ```
</details>

guessing some of this should not stay.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7127)* status: all files reviewed, 3 unresolved discussions (waiting on @anothermattbrown)

**Review by anothermattbrown — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7127)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysisImpl.java, line 1362 at r2](https://reviewable.io/reviews/batfish/batfish/7127#-Meb3Dc23GqvGh4BE7Oa:-MebdHQG-1X2pxGP_dRL:b-d8t5ii) ([raw file](https://github.com/batfish/batfish/blob/d09b44a3483aa44af65cf830eb366f85d732694f/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysisImpl.java#L1362)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

maybe some of this needs updating?
</blockquote></details>

I don't think so. We just changed the meaning of `ipElsewhere`.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7127)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown)

**Pull request merged**
