### PR TITLE
XR: parse and extract `l2vpn`

### PR DESCRIPTION
**Pull request by sfraint**
See [here for some details on BVI/l2vpn configuration](https://www.cisco.com/c/en/us/td/docs/routers/asr9000/software/asr9k_r6-1/interfaces/configuration/guide/b-interfaces-cg-asr9k-61x/b-interfaces-cg-asr9k-61x_chapter_0111.html).

Quick summary:
* `bridge group` is just a grouping of `bridge-domain`s within `l2vpn`
* `bridge-domain` defines a "switch" that bridges all `interfaces` in that domain
* `routed interface` is the L3 `BVI` interface that is used to route interfaces in the `bridge-domain`

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 7 of 9 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7106)* status: all files reviewed, 1 unresolved discussion (waiting on @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java, line 4862 at r2](https://reviewable.io/reviews/batfish/batfish/7106#-Md3uBNy1JHHmnECZuJx:-Md3uBNz1G-d3vPHH0IB:b4xgyl2) ([raw file](https://github.com/batfish/batfish/blob/6061a83b3bb719b4b4ab91e9afd9546205733282/projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java#L4862)):*
> ```Java
>   @Override
>   public void exitLbgbd_routed_interface(Lbgbd_routed_interfaceContext ctx) {
>     _currentBridgeDomain.setRoutedInterface(getOrAddInterface(ctx.interface_name()).getName());
> ```

Ref tracking?

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7106)* status: 7 of 13 files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java, line 4862 at r2](https://reviewable.io/reviews/batfish/batfish/7106#-Md3uBNy1JHHmnECZuJx:-Md41ht86ZYaghLyeiO0:b-7tfmjp) ([raw file](https://github.com/batfish/batfish/blob/6061a83b3bb719b4b4ab91e9afd9546205733282/projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java#L4862)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Ref tracking?
</blockquote></details>

added

**Review by dhalperi — COMMENTED** [review]
> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7106)* status: all files reviewed, 1 unresolved discussion (waiting on @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java, line 4859 at r3](https://reviewable.io/reviews/batfish/batfish/7106#-Md4NigT-dhHHNWAl6Uz:-Md4NigT-dhHHNWAl6V-:b-vqyat0) ([raw file](https://github.com/batfish/batfish/blob/a41b1cac8d20cc233de2c7bd5df62c535ce431ec/projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java#L4859)):*
> ```Java
>   @Override
>   public void exitLbgbd_interface(Lbgbd_interfaceContext ctx) {
>     Interface iface = getOrAddInterface(ctx.interface_name());
> ```

Not sure we should use `getOrAddInterface` here -- does this actually create one if not defined?

(I think almost all uses of that will be wrong on XR)

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7106)* status: 10 of 13 files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java, line 4859 at r3](https://reviewable.io/reviews/batfish/batfish/7106#-Md4NigT-dhHHNWAl6Uz:-Md4Q9Sf4Uajn-oaFLat:b-92bnre) ([raw file](https://github.com/batfish/batfish/blob/a41b1cac8d20cc233de2c7bd5df62c535ce431ec/projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java#L4859)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Not sure we should use `getOrAddInterface` here -- does this actually create one if not defined?

(I think almost all uses of that will be wrong on XR)
</blockquote></details>

Hmm, good call. It's not created, but the reference/link is allowed and the device will end up saying the interface state is "unresolved" under `show l2vpn bridge-domain`

**Review by dhalperi — COMMENTED** [review]
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7106)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7106)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 4 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7106)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

**Pull request merged**
