### PR TITLE
Sort testrigs

### PR DESCRIPTION
**Pull request by ratulm**
This change is [Reviewable](https://reviewable.io/reviews/batfish/batfish/870)

### CODE REVIEW

**Comment by corinaminer** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, line 1095 at r1](https://reviewable.io:443/reviews/batfish/batfish/870#-L3Z6snjVfk3EeqR5UCf:-L3Z6snk03jREEOiJ3Rd:bwdfj9c) ([raw file](https://github.com/batfish/batfish/blob/9d68a3287f62ad8b5ed13429c9138abfdd59d096/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java#L1095)):*
> ```Java
>                                 TestrigMetadataMgr.getTestrigCreationTimestampOrMin(
>                                     containerName, t1)))
>                 .collect(Collectors.toList()));
> ```

Why do you surround this with `new ArrayList<>()`? Doesn't `Collectors.toList()` create a `List`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/870)*

**Comment by ratulm** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, line 1095 at r1](https://reviewable.io:443/reviews/batfish/batfish/870#-L3Z6snjVfk3EeqR5UCf:-L3ZLVWbg4tMacMHEXyl:bh3c0qf) ([raw file](https://github.com/batfish/batfish/blob/9d68a3287f62ad8b5ed13429c9138abfdd59d096/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java#L1095)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Why do you surround this with `new ArrayList<>()`? Doesn't `Collectors.toList()` create a `List`?
</blockquote></details>

yes, it does. brokenness from before. fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/870)*

**Comment by corinaminer** [comment]
:lgtm: but please check last comment before merging.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, line 1095 at r1](https://reviewable.io:443/reviews/batfish/batfish/870#-L3Z6snjVfk3EeqR5UCf:-L3ZNw1pSYQKlt8oL9O1:b-pwt7uu) ([raw file](https://github.com/batfish/batfish/blob/9d68a3287f62ad8b5ed13429c9138abfdd59d096/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java#L1095)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

yes, it does. brokenness from before. fixed.
</blockquote></details>

on the other hand, the `Collectors.toList()` [documentation](https://docs.oracle.com/javase/8/docs/api/java/util/stream/Collectors.html#toList--) says "There are no guarantees on the type, mutability, serializability, or thread-safety of the List returned". Maybe worth keeping `ArrayList<>()`? Your call; if it works as-is then great.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/870#-:-L3ZQdzuGDCpCl2jqOn8:b-8w8ki9)*

**Comment by ratulm** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, line 1095 at r1](https://reviewable.io:443/reviews/batfish/batfish/870#-L3Z6snjVfk3EeqR5UCf:-L3ZRFpX9tUdqo1UtCy-:bt7gvdl) ([raw file](https://github.com/batfish/batfish/blob/9d68a3287f62ad8b5ed13429c9138abfdd59d096/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java#L1095)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

on the other hand, the `Collectors.toList()` [documentation](https://docs.oracle.com/javase/8/docs/api/java/util/stream/Collectors.html#toList--) says "There are no guarantees on the type, mutability, serializability, or thread-safety of the List returned". Maybe worth keeping `ArrayList<>()`? Your call; if it works as-is then great.
</blockquote></details>

the consumer code is mainly using List<> interface which i assume makes no guarantees either, so we should be good.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/870)*

**Pull request merged**
