### PR TITLE
bugfix: add route reflector configuration for Arista EVPN neighbors

### PR DESCRIPTION
**Pull request by Chensjian**
This commit adds support for the route reflector configuration in the EVPN neighbor conversion process for Arista. Without this configuration, the spine cannot reflect EVPN routes in the iBGP VXLAN configuration.

### CODE REVIEW

**Comment by dhalperi** [comment]
Thank you for the contribution! It looks like some of the automated checks aren't passing; can you please check out the contributing notes: https://github.com/batfish/batfish/blob/875218ce32cb30588f424f59dd653013aa0bd28d/docs/contributing/README.md#prerequisites

**Comment by Chensjian** [comment]
> Thank you for the contribution! It looks like some of the automated checks aren't passing; can you please check out the contributing notes: https://github.com/batfish/batfish/blob/875218ce32cb30588f424f59dd653013aa0bd28d/docs/contributing/README.md#prerequisites

Thank you for your feedback! I appreciate the guidance regarding the automated checks. I have reviewed the contributing notes and addressed the issues related to the checks.
I will ensure all checks pass before my next submission.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/9226)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Chensjian)

**Comment by dhalperi** [comment]
I don't have an Arista emulator I can play with any more, but I found a lot of evidence online that this configuration applies to all address families. For example, this article from Arista itself: https://arista.my.site.com/AristaCommunity/s/article/Arista-Layer-2-VTEP-EVPN-VxLAN-Route-Type-1-Support

So approving and merging once automated tests pass.

**Comment by Chensjian** [comment]
Thank you for your feedback! I have analyzed two VXLAN configurations using Batfish. One is eBGP EVPN, which works correctly without any issues. The other configuration uses iBGP EVPN and uses a route reflector to reflect EVPN routes. However, when reviewing the EVPN routes, I noticed that the leaf devices' route information is only being sent to the spine, and the spine is not reflecting these routes back to other leaf devices. After debugging, I discovered that the EVPN address family lacks route reflector configuration, which is preventing proper route reflection.

**Pull request merged**
