### PR TITLE
Add VI support for reachability tracking

### PR DESCRIPTION
**Pull request by arifogel**
- given a destination IP and source VRF, track reachability succeeds if a corresponding flow with
  any of one or more inferred source IPs can succeed bidirectionally.
- like route tracks, precompute reachability tracks between iterations

Follow-on work:
- add support for individual vendors
- (maybe) support specific source IP or output interface

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 10 of 36 files at r1, 26 of 33 files at r2, 3 of 4 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8006)* status: 35 of 46 files reviewed, all discussions resolved (waiting on @arifogel)

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8006)* status: 35 of 46 files reviewed, 1 unresolved discussion (waiting on @arifogel)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/8006#-Mv1k7nG5EUJ8gUlkCV4:-Mv1k7nG5EUJ8gUlkCV5:b-xwdhon) (no related file):*
after batfish/batfish#8000

---

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8006)* status: 0 of 48 files reviewed, 2 unresolved discussions (waiting on @arifogel, @corinaminer, and @dhalperi)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/8006#-Mv4xFqq2iNQrILj8YLr:-Mv4xFqq2iNQrILj8YLs:b-1y0n84) (no related file):*
currently importing a static function from BgpTopologyUtil in IncrementalBdpEngine.
Need to either copy or factor it out.

---
___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java, line 641 at r10](https://reviewable.io/reviews/batfish/batfish/8006#-Mv4xVBYC_xIDqUeMV8M:-Mv4xVBYC_xIDqUeMV8N:b-d7w13s) ([raw file](https://github.com/batfish/batfish/blob/0548ac2eedf505a7fc0caa6cbf12aebe14b48697/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java#L641)):*
> ```Java
>           tracerouteEngine.computeTracesAndReverseFlows(ImmutableSet.of(flow), false);
>       List<TraceAndReverseFlow> traceAndReverseFlows = tracerouteResult.get(flow);
>       if (traceAndReverseFlows != null
> ```

I'm going to add more checks here: At minimum, reverse flow should be accepted at the forward flow originating vrf.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 6 of 7 files at r7, 1 of 1 files at r8, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8006)* status: 9 of 48 files reviewed, 2 unresolved discussions (waiting on @arifogel and @corinaminer)

**Review by corinaminer — COMMENTED** [review]
> Reviewed 1 of 1 files at r8, 1 of 3 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8006)* status: 9 of 49 files reviewed, 4 unresolved discussions (waiting on @arifogel, @corinaminer, and @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java, line 463 at r12](https://reviewable.io/reviews/batfish/batfish/8006#-Mv63RnfD8iCUzIk2SqN:-Mv63Rng73hI26OOsjWm:b6hku61) ([raw file](https://github.com/batfish/batfish/blob/3f1730c6f34be04c32ad5c6b4a0b8f7108502301/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java#L463)):*
> ```Java
>                   .collect(ImmutableList.toImmutableList());
>           if (!trackReachabilities.isEmpty()) {
>             builder.put(hostname, trackReachabilities);
> ```

is it possible for `trackReachabilities` to contain duplicates? If so, i think they should be culled
___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java, line 583 at r12](https://reviewable.io/reviews/batfish/batfish/8006#-Mv63l32CPlZm4DVxh-P:-Mv63l32CPlZm4DVxh-Q:b-q5pfwn) ([raw file](https://github.com/batfish/batfish/blob/3f1730c6f34be04c32ad5c6b4a0b8f7108502301/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java#L583)):*
> ```Java
>    *       the beginning of an iteration anyway). Since saving routes of a VRF can be expensive, we
>    *       instead use pre-evaluated {@link org.batfish.datamodel.tracking.TrackRoute} {@link
>    *       org.batfish.datamodel.tracking.TrackReachability} results here.
> ```

nit: missing "and"
___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/TrackReachabilityUtils.java, line 70 at r12](https://reviewable.io/reviews/batfish/batfish/8006#-Mv67RJT42RPmHzWe_oD:-Mv67RJT42RPmHzWe_oE:b-7sued8) ([raw file](https://github.com/batfish/batfish/blob/3f1730c6f34be04c32ad5c6b4a0b8f7108502301/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/TrackReachabilityUtils.java#L70)):*
> ```Java
>             .setIngressNode(originatingNode.getHostname())
>             .setIngressVrf(originatingVrf)
>             // TODO: support other flow types
> ```

do you know what real devices use to test track reachability?
___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/TrackReachabilityUtils.java, line 130 at r12](https://reviewable.io/reviews/batfish/batfish/8006#-Mv66L1hANTW-3-FZtO3:-Mv66L1hANTW-3-FZtO4:b-comg6o) ([raw file](https://github.com/batfish/batfish/blob/3f1730c6f34be04c32ad5c6b4a0b8f7108502301/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/TrackReachabilityUtils.java#L130)):*
> ```Java
>    * {@code dstIp} originating on the given {@link Configuration} with the given {@code fibs}
>    * indexed by vrf, to be resolved in the given {@code initialSenderVrf}, Concretely, finds LPM
>    * routes for {@code dstIp} and returns the IPs and VRFs of those routes' forwarding interfaces.
> ```

If the dst IP matches a next VRF route, this code will have us use the address of the outgoing interface (in the next VRF) as src IP. Isn't that unrealistic, if the packet is supposed to start in `initialSenderVrf`?

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8006)* status: 9 of 49 files reviewed, 4 unresolved discussions (waiting on @arifogel, @corinaminer, and @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java, line 463 at r12](https://reviewable.io/reviews/batfish/batfish/8006#-Mv63RnfD8iCUzIk2SqN:-Mv68gXt9U-WiuwrNbVf:b-zbo3h8) ([raw file](https://github.com/batfish/batfish/blob/3f1730c6f34be04c32ad5c6b4a0b8f7108502301/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java#L463)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

is it possible for `trackReachabilities` to contain duplicates? If so, i think they should be culled
</blockquote></details>

yeah, if something is both at top level and nested.
fixed.
___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java, line 583 at r12](https://reviewable.io/reviews/batfish/batfish/8006#-Mv63l32CPlZm4DVxh-P:-Mv69L7N6SqLJQMoHFLf:bb7gj1y) ([raw file](https://github.com/batfish/batfish/blob/3f1730c6f34be04c32ad5c6b4a0b8f7108502301/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java#L583)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

nit: missing "and"
</blockquote></details>

fxed
___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/TrackReachabilityUtils.java, line 70 at r12](https://reviewable.io/reviews/batfish/batfish/8006#-Mv67RJT42RPmHzWe_oD:-Mv69Nqw73V3Qtrkxgej:bbu71ot) ([raw file](https://github.com/batfish/batfish/blob/3f1730c6f34be04c32ad5c6b4a0b8f7108502301/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/TrackReachabilityUtils.java#L70)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

do you know what real devices use to test track reachability?
</blockquote></details>

The initial use case is A10, which uses ICMP by default (and in configs of interest). It can do other types, but we don't care yet.
___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/TrackReachabilityUtils.java, line 130 at r12](https://reviewable.io/reviews/batfish/batfish/8006#-Mv66L1hANTW-3-FZtO3:-Mv69_7-9aHuVt77JYmr:bh216bv) ([raw file](https://github.com/batfish/batfish/blob/3f1730c6f34be04c32ad5c6b4a0b8f7108502301/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/TrackReachabilityUtils.java#L130)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

If the dst IP matches a next VRF route, this code will have us use the address of the outgoing interface (in the next VRF) as src IP. Isn't that unrealistic, if the packet is supposed to start in `initialSenderVrf`?
</blockquote></details>

It doesn't start in `initialSenderVrf`. It starts in the vrf of the resolved interface.
`initialSenderVrf` is just the first vrf where lpm is performed.

Adjusted doc slightly

**Review by corinaminer — COMMENTED** [review]
> Reviewed 2 of 40 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8006)* status: 9 of 52 files reviewed, all discussions resolved (waiting on @arifogel, @corinaminer, and @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/TrackReachabilityUtils.java, line 70 at r12](https://reviewable.io/reviews/batfish/batfish/8006#-Mv67RJT42RPmHzWe_oD:-Mv6BHf78PnGOo2cT4PN:bb6mt9b) ([raw file](https://github.com/batfish/batfish/blob/3f1730c6f34be04c32ad5c6b4a0b8f7108502301/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/TrackReachabilityUtils.java#L70)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

The initial use case is A10, which uses ICMP by default (and in configs of interest). It can do other types, but we don't care yet.
</blockquote></details>

:+1:

**Review by corinaminer — COMMENTED** [review]
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8006)* status: 9 of 52 files reviewed, all discussions resolved (waiting on @arifogel, @corinaminer, and @dhalperi)

**Review by corinaminer — COMMENTED** [review]
> Reviewed 1 of 3 files at r11.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8006)* status: 10 of 52 files reviewed, all discussions resolved (waiting on @arifogel, @corinaminer, and @dhalperi)

**Review by arifogel — COMMENTED** [review]
> Reviewed 4 of 35 files at r2, 38 of 40 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8006)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Pull request merged**
