### PR TITLE
Table diff v1

### PR DESCRIPTION
**Pull request by ratulm**
Diff-ing tables. A related, needed change was to introduce the "Set" Schema, so we could do set differences. Many of the things in node properties are sets, which we were treating as lists.

### CODE REVIEW

**Comment by ratulm** [comment]
Review status: 0 of 18 files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1561#-LE5dbfo1-wa5PEcxJzd:-LE5dbfp4Qp9TbjsXXEL:b-h4ld5l) (no related file):*
Found a design flaw. Fixing and writing a design doc.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1561)*

**Comment by ratulm** [comment]
Ping on this PR: let me know if you need more info/context.

**Comment by progwriter** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/Rows.java, line 81 at r4](https://reviewable.io/reviews/batfish/batfish/1561#-LEGnIVADXKHLdMpRbAR:-LEGnIVADXKHLdMpRbAS:b-7tjji0) ([raw file](https://github.com/batfish/batfish/blob/451ae2894e72cf71bff9e02b60dba275adecb47f/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/Rows.java#L81)):*
> ```Java
>    * @param metadata ColumnMetadata used as reference to extract keys from rows.
>    */
>   public Row getRow(Object key, List<ColumnMetadata> metadata) {
> ```

Please annotate with `@Nullable`

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/TableDiff.java, line 64 at r4](https://reviewable.io/reviews/batfish/batfish/1561#-LEGpC_yBVVldY_lRXFR:-LEGpC_yBVVldY_lRXFS:b-hujkhs) ([raw file](https://github.com/batfish/batfish/blob/451ae2894e72cf71bff9e02b60dba275adecb47f/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/TableDiff.java#L64)):*
> ```Java
>    * Computes the String representation of the difference for base and delta values.
>    *
>    * <p>The underlying Schema of both values should be the same, though onr or both values may be
> ```

nit: typo "onr" -> "one"

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/TableDiff.java, line 68 at r4](https://reviewable.io/reviews/batfish/batfish/1561#-LEGpSpkDfrKvf1ErWtm:-LEGpSpkDfrKvf1ErWtn:b-pd9sje) ([raw file](https://github.com/batfish/batfish/blob/451ae2894e72cf71bff9e02b60dba275adecb47f/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/TableDiff.java#L68)):*
> ```Java
>    */
>   @VisibleForTesting
>   static String diffCells(Object baseValue, Object deltaValue, Schema schema) {
> ```

Also add annotations: nullable, nullable, nonnull, if I understand correctly.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1561)*

**Comment by ratulm** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/Rows.java, line 81 at r4](https://reviewable.io/reviews/batfish/batfish/1561#-LEGnIVADXKHLdMpRbAR:-LEGtzhIENKnB2tiL_Dg:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/451ae2894e72cf71bff9e02b60dba275adecb47f/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/Rows.java#L81)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

Please annotate with `@Nullable`
</blockquote></details>

Done.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/TableDiff.java, line 68 at r4](https://reviewable.io/reviews/batfish/batfish/1561#-LEGpSpkDfrKvf1ErWtm:-LEGv7Ul4v9NInEtI884:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/451ae2894e72cf71bff9e02b60dba275adecb47f/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/TableDiff.java#L68)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

Also add annotations: nullable, nullable, nonnull, if I understand correctly.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1561)*

**Comment by dhalperi** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1561#-LE5dbfo1-wa5PEcxJzd:-LEHOnR29qyVk20C7H-I:b-2gft1f) (no related file):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

Found a design flaw. Fixing and writing a design doc.
</blockquote></details>

I think this is the only blocking comment. Were you looking for more?

(Do I know which design doc this is?)

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1561)*

**Pull request merged**
