### PR TITLE
Add option to print line number when printing parse trees

### PR DESCRIPTION
**Pull request by sfraint**
Add option to print line numbers when printing parse trees

### CODE REVIEW

**Comment by arifogel** [comment]
:lgtm:

---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed, 1 unresolved discussion (waiting on @sfraint and @corinaminer)

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1675#-LFDsyU4DOnB4ytL6BRZ:-LFDsyU534LJ2A804U5g:b-ee3cs3) (no related file):*
I was actually hoping you'd have a lighter-weight reference file mechanism. But perhaps this is fine for now. Maybe @dhalperi has a suggestion, but I suppose this can be merged as is.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/grammar/ParseTreePrettyPrinter.java, line 24 at r1](https://reviewable.io/reviews/batfish/batfish/1675#-LFDrbGp7ambt80Bblro:-LFDrbGqA24-dbvDlwmQ:bbiecjr) ([raw file](https://github.com/batfish/batfish/blob/315bbfbf97e1b8cec6069804bf18f514a191c19b/projects/batfish-common-protocol/src/main/java/org/batfish/grammar/ParseTreePrettyPrinter.java#L24)):*
> ```Java
>   private int _indent;
>   private ParseTreeSentences _ptSentences;
>   private Boolean _printLineNumbers;
> ```

Can this be a primitive?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1675#-:-LFDtLqO27MktJoedXQ2:bnfp4nl)*

**Comment by sfraint** [comment]
Review status: 12 of 14 files reviewed, 1 unresolved discussion (waiting on @arifogel, @sfraint, and @corinaminer)

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/grammar/ParseTreePrettyPrinter.java, line 24 at r1](https://reviewable.io/reviews/batfish/batfish/1675#-LFDrbGp7ambt80Bblro:-LFIpE0i3t4GI8tq67gF:b60r506) ([raw file](https://github.com/batfish/batfish/blob/315bbfbf97e1b8cec6069804bf18f514a191c19b/projects/batfish-common-protocol/src/main/java/org/batfish/grammar/ParseTreePrettyPrinter.java#L24)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Can this be a primitive?
</blockquote></details>

Yes, done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1675)*

**Comment by dhalperi** [comment]
*[tests/parsing-tests/commands, line 51 at r2](https://reviewable.io/reviews/batfish/batfish/1675#-LFJJlXN7ggos8qxrdPV:-LFJJlXN7ggos8qxrdPW:b-37ikhn) ([raw file](https://github.com/batfish/batfish/blob/3f9319544f0b8a997f82fc56c88da092afb60bae/tests/parsing-tests/commands#L51)):*
> ```
> 
> #make sure line-numbers show up when that option is set
> test -compareall tests/parsing-tests/line-numbers.ref init-testrig test_rigs/line-numbers
> ```

Unit test, not ref test.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1675)*

**Comment by arifogel** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed, 1 unresolved discussion (waiting on @sfraint and @corinaminer)

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/grammar/BatfishLexerErrorListener.java, line 48 at r2](https://reviewable.io/reviews/batfish/batfish/1675#-LFJNqLA8dip3xxmMO6h:-LFJNqLA8dip3xxmMO6i:bqt2osn) ([raw file](https://github.com/batfish/batfish/blob/3f9319544f0b8a997f82fc56c88da092afb60bae/projects/batfish-common-protocol/src/main/java/org/batfish/grammar/BatfishLexerErrorListener.java#L48)):*
> ```Java
>         ParseTreePrettyPrinter.print(ctx, _combinedParser, _settings.getPrintParseTreeLineNums()));
>     sb.append("\n");
>     sb.append("Lexer mode: " + lexer.getMode() + "\n");
> ```

Why so indecisive?

---

*[tests/parsing-tests/commands, line 51 at r2](https://reviewable.io/reviews/batfish/batfish/1675#-LFJJlXN7ggos8qxrdPV:-LFJOD9P4WOHYuX_zsQR:b-wd0rcv) ([raw file](https://github.com/batfish/batfish/blob/3f9319544f0b8a997f82fc56c88da092afb60bae/tests/parsing-tests/commands#L51)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Unit test, not ref test.
</blockquote></details>

@dhalperi Do you mean to do the same thing (compare against reference output) but in JUnit? Or to just do assertions?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1675)*

**Comment by corinaminer** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi)

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/grammar/BatfishLexerErrorListener.java, line 48 at r2](https://reviewable.io/reviews/batfish/batfish/1675#-LFJNqLA8dip3xxmMO6h:-LFK4AuJ-CmG6Bsbp4H6:b-jkq4ar) ([raw file](https://github.com/batfish/batfish/blob/3f9319544f0b8a997f82fc56c88da092afb60bae/projects/batfish-common-protocol/src/main/java/org/batfish/grammar/BatfishLexerErrorListener.java#L48)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Why so indecisive?
</blockquote></details>

maybe a good area for some `String.format()`?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1675)*

**Comment by dhalperi** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @sfraint)

---

*[tests/parsing-tests/commands, line 51 at r2](https://reviewable.io/reviews/batfish/batfish/1675#-LFJJlXN7ggos8qxrdPV:-LFK4a7LAtJPGv241_rM:by03iad) ([raw file](https://github.com/batfish/batfish/blob/3f9319544f0b8a997f82fc56c88da092afb60bae/tests/parsing-tests/commands#L51)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

@dhalperi Do you mean to do the same thing (compare against reference output) but in JUnit? Or to just do assertions?
</blockquote></details>

I would hope we could do this with a proper unit test, and no reference file at all. In a pinch, we could have a ref file but use as little code as possible necessary to exercise line printing. (*)

(*) that's the other (meta-) point: don't use a 103-line input to see whether we can print line numbers next to tokens. The current `n1` file seems like it could have a lot of upkeep overhead as we change parsing any number of constructs.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1675)*

**Comment by sfraint** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @arifogel)

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/grammar/BatfishLexerErrorListener.java, line 48 at r2](https://reviewable.io/reviews/batfish/batfish/1675#-LFJNqLA8dip3xxmMO6h:-LFJYflFB0OtTTcrAXKu:b-lz4b1y) ([raw file](https://github.com/batfish/batfish/blob/3f9319544f0b8a997f82fc56c88da092afb60bae/projects/batfish-common-protocol/src/main/java/org/batfish/grammar/BatfishLexerErrorListener.java#L48)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

maybe a good area for some `String.format()`?
</blockquote></details>

These unrelated styling changes added untested lines that pushed test coverage below the threshold, decided to just leave these out.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1675)*

**Comment by dhalperi** [comment]
Reviewed 3 of 5 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1675)*

**Pull request merged**
