### PR TITLE
Add ospf type 5 filtering

### PR DESCRIPTION
**Pull request by SLarkworthy**
Adds the ability to filter type 5 OSPF LSAs.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
Overall looks good. I left some style/bar raiser comments in and I'll let Ari look at functionality.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8720#-:-NVkNiGo0VZhYWLcWIsf:b-b6jep8)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @arifogel and @SLarkworthy)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/8720#-NVkMZ0zD0jB5LGHHyei:-NVkMZ0zD0jB5LGHHyej:b-7vqqck) (no related file):*
Please improve commit message. Run a `git log -- projects/batfish/src/main/java/org/batfish/dataplane` for comparison of what they usually look like?

___
___
*[`projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java` line 1382 at r1](https://reviewable.io/reviews/batfish/batfish/8720#-NVkMesj2JHf1NkE3bz-:-NVkMesj2JHf1NkE3bz0:b3lol0o) ([raw file](https://github.com/batfish/batfish/blob/c2cb9c739962e2da76fe5086b36503c01c74ecde/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java#L1382)):*
> ```Java
>   @VisibleForTesting
>   <T extends OspfExternalRoute> Stream<RouteAdvertisement<T>> filterExternalRoutesOnExport(
>       RibDelta<T> delta, OspfArea areaConfig, Optional<RoutingPolicy> type5filterRoutingPolicy) {
> ```

`Optional` is only suitable as a return value from an API, not a parameter. Just use `@Nullable` and save code RAM and CPU.
___
*[`projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java` line 1402 at r1](https://reviewable.io/reviews/batfish/batfish/8720#-NVkMmqP9CzfJof-hVdu:-NVkMmqP9CzfJof-hVdv:b-puw6hp) ([raw file](https://github.com/batfish/batfish/blob/c2cb9c739962e2da76fe5086b36503c01c74ecde/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java#L1402)):*
> ```Java
>               action ->
>                   type5filterRoutingPolicy
>                       .get()
> ```

Note that as-is this is unboxing the optional on the hot path. Simpler just to have the local variable, which is `non-null`.



_Code quote:_
```Java
                  type5filterRoutingPolicy
                      .get()
```
___
*[`projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java` line 1403 at r1](https://reviewable.io/reviews/batfish/batfish/8720#-NVkN5T75Sko_C2pc00X:-NVkN5T75Sko_C2pc00Y:bog62gv) ([raw file](https://github.com/batfish/batfish/blob/c2cb9c739962e2da76fe5086b36503c01c74ecde/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java#L1403)):*
> ```Java
>                   type5filterRoutingPolicy
>                       .get()
>                       .process(action.getRoute(), action.getRoute().toBuilder(), Direction.OUT));
> ```

Longer term, so just think about it: If this policy can't transform, would be good to have an API that returns a `boolean` and doesn't take a builder. The `toBuilder()` call is expensive here.



_Code quote:_
```Java
process(action.getRoute(), action.getRoute().toBuilder(), Direction.OUT));
```
___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfInterfaceSettings.java` line 367 at r1](https://reviewable.io/reviews/batfish/batfish/8720#-NVkNNre4Dn02JFmcseE:-NVkNNre4Dn02JFmcseF:b7nn5nc) ([raw file](https://github.com/batfish/batfish/blob/c2cb9c739962e2da76fe5086b36503c01c74ecde/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfInterfaceSettings.java#L367)):*
> ```Java
>    */
>   @JsonProperty(PROP_TYPE_5_FILTER_POLICY)
>   @Nullable
> ```

`@Nullable String` - in general, put the modifier next to the type it modifies. Not all old code does this right, but new code should.
___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfInterfaceSettings.java` line 384 at r1](https://reviewable.io/reviews/batfish/batfish/8720#-NVkNWGE88rFNg_s90Rt:-NVkNWGE88rFNg_s90Ru:b-k08k50) ([raw file](https://github.com/batfish/batfish/blob/c2cb9c739962e2da76fe5086b36503c01c74ecde/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfInterfaceSettings.java#L384)):*
> ```Java
>   }
> 
>   public void setType5FilterPolicy(String type5FilterPolicy) {
> ```

This isn't `@Nullable`?

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8720)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @arifogel and @SLarkworthy)

___
*[`projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java` line 1382 at r1](https://reviewable.io/reviews/batfish/batfish/8720#-NVkMesj2JHf1NkE3bz-:-NVkT_c04nW3bC4frnvv:b-4qec4d) ([raw file](https://github.com/batfish/batfish/blob/c2cb9c739962e2da76fe5086b36503c01c74ecde/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java#L1382)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

`Optional` is only suitable as a return value from an API, not a parameter. Just use `@Nullable` and save code RAM and CPU.
</blockquote></details>

More color: https://stackoverflow.com/a/31923105/1715495

**Review by SLarkworthy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8720)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @arifogel and @dhalperi)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/8720#-NVkMZ0zD0jB5LGHHyei:-NVk_q6j4uhquLn9XkGr:bb7f2mf) (no related file):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Please improve commit message. Run a `git log -- projects/batfish/src/main/java/org/batfish/dataplane` for comparison of what they usually look like?
</blockquote></details>

done

___
___
*[`projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java` line 1382 at r1](https://reviewable.io/reviews/batfish/batfish/8720#-NVkMesj2JHf1NkE3bz-:-NVkSM709cw3ggWcfpIh:b-xlh2pb) ([raw file](https://github.com/batfish/batfish/blob/c2cb9c739962e2da76fe5086b36503c01c74ecde/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java#L1382)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

More color: https://stackoverflow.com/a/31923105/1715495
</blockquote></details>

makes sense, done. Thanks for the explanation! 
___
*[`projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java` line 1402 at r1](https://reviewable.io/reviews/batfish/batfish/8720#-NVkMmqP9CzfJof-hVdu:-NVkUvpl7nn2Tqt6TZfE:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/c2cb9c739962e2da76fe5086b36503c01c74ecde/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java#L1402)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Note that as-is this is unboxing the optional on the hot path. Simpler just to have the local variable, which is `non-null`.
</blockquote></details>

done
___
*[`projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java` line 1403 at r1](https://reviewable.io/reviews/batfish/batfish/8720#-NVkN5T75Sko_C2pc00X:-NVkTEf9DNwavwrw3SOH:b67n6fj) ([raw file](https://github.com/batfish/batfish/blob/c2cb9c739962e2da76fe5086b36503c01c74ecde/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java#L1403)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Longer term, so just think about it: If this policy can't transform, would be good to have an API that returns a `boolean` and doesn't take a builder. The `toBuilder()` call is expensive here.
</blockquote></details>

Oh beautiful, I did think this was gross and I just noticed we already have an API for this. I had looked at all of the process options but didn't notice processReadOnly.
___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfInterfaceSettings.java` line 367 at r1](https://reviewable.io/reviews/batfish/batfish/8720#-NVkNNre4Dn02JFmcseE:-NVkVHEg657zCM8gLhSg:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/c2cb9c739962e2da76fe5086b36503c01c74ecde/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfInterfaceSettings.java#L367)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

`@Nullable String` - in general, put the modifier next to the type it modifies. Not all old code does this right, but new code should.
</blockquote></details>

done
___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfInterfaceSettings.java` line 384 at r1](https://reviewable.io/reviews/batfish/batfish/8720#-NVkNWGE88rFNg_s90Rt:-NVkVY8tE-2BnuJi9ZTF:b-7tfmjp) ([raw file](https://github.com/batfish/batfish/blob/c2cb9c739962e2da76fe5086b36503c01c74ecde/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfInterfaceSettings.java#L384)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

This isn't `@Nullable`?
</blockquote></details>

added

**Review by dhalperi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8720)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @arifogel and @SLarkworthy)

___
*[`projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java` line 1382 at r1](https://reviewable.io/reviews/batfish/batfish/8720#-NVkMesj2JHf1NkE3bz-:-NVkbbdw04VxXVKh2Njb:bvyo3tv) ([raw file](https://github.com/batfish/batfish/blob/c2cb9c739962e2da76fe5086b36503c01c74ecde/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java#L1382)):*
<details><summary><i>Previously, SLarkworthy (Sarah Larkworthy) wrote…</i></summary><blockquote>

makes sense, done. Thanks for the explanation! 
</blockquote></details>

@Nullable?

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8720)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel and @SLarkworthy)

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8720)* status: all files reviewed, 3 unresolved discussions (waiting on @SLarkworthy)

___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfInterfaceSettings.java` line 50 at r2](https://reviewable.io/reviews/batfish/batfish/8720#-NVlFOqZELl2ERf9jOkG:-NVlFOqZELl2ERf9jOkH:b1rqry6) ([raw file](https://github.com/batfish/batfish/blob/a243ee9b2c7af3de2e5aa969be44b66779ec80f9/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfInterfaceSettings.java#L50)):*
> ```Java
>     private Boolean _ospfPassive;
>     private String _ospfProcess;
>     private String _ospfType5FilterPolicy;
> ```

`@Nullable` [new field](https://github.com/batfish/batfish/blob/master/docs/contributing/README.md#null-annotations-maintainability-legibility)
___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfInterfaceSettings.java` line 116 at r2](https://reviewable.io/reviews/batfish/batfish/8720#-NVlFLhW3s7un_O4SRu-:-NVlFLhXDqw-GEM0PAwi:bqnpn7k) ([raw file](https://github.com/batfish/batfish/blob/a243ee9b2c7af3de2e5aa969be44b66779ec80f9/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfInterfaceSettings.java#L116)):*
> ```Java
>     }
> 
>     public Builder setType5FilterPolicy(String ospfType5FilterPolicy) {
> ```

`@Nullable`[param for new function](https://github.com/batfish/batfish/blob/master/docs/contributing/README.md#null-annotations-maintainability-legibility)

**Review by SLarkworthy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8720)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @arifogel and @dhalperi)

___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfInterfaceSettings.java` line 50 at r2](https://reviewable.io/reviews/batfish/batfish/8720#-NVlFOqZELl2ERf9jOkG:-NVlH0AYDQXUJafW6Q3D:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/a243ee9b2c7af3de2e5aa969be44b66779ec80f9/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfInterfaceSettings.java#L50)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

`@Nullable` [new field](https://github.com/batfish/batfish/blob/master/docs/contributing/README.md#null-annotations-maintainability-legibility)
</blockquote></details>

done
___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfInterfaceSettings.java` line 116 at r2](https://reviewable.io/reviews/batfish/batfish/8720#-NVlFLhW3s7un_O4SRu-:-NVlH0fuAiZVt_jCwUao:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/a243ee9b2c7af3de2e5aa969be44b66779ec80f9/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfInterfaceSettings.java#L116)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

`@Nullable`[param for new function](https://github.com/batfish/batfish/blob/master/docs/contributing/README.md#null-annotations-maintainability-legibility)
</blockquote></details>

done

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8720)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel)

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8720)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[`projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java` line 1382 at r1](https://reviewable.io/reviews/batfish/batfish/8720#-NVkMesj2JHf1NkE3bz-:-NVlJYNd0l8c4mVyVwHC:b6q6iko) ([raw file](https://github.com/batfish/batfish/blob/c2cb9c739962e2da76fe5086b36503c01c74ecde/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java#L1382)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

@Nullable?
</blockquote></details>

still missing `@Nullable`

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8720)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SLarkworthy)

**Pull request merged**
