### PR TITLE
BDDFactory: introduce andAll and use it a bit

### PR DESCRIPTION
**Pull request by dhalperi**
1. Introduce BDDFactory#andAll, essentially an exact copy of #orAll.
2. Use it in a few places to reduce BDD garbage.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7849)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @anothermattbrown)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDInteger.java, line 197 at r1](https://reviewable.io/reviews/batfish/batfish/7849#-MrPL23yBgYUbIaOQDKU:-MrPL23yBgYUbIaOQDKV:b-fpnloh) ([raw file](https://github.com/batfish/batfish/blob/e57226219c04082e0d34123e8ad9d51dc5d85667/projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDInteger.java#L197)):*
> ```Java
>    * Create a BDD representing the exact value
>    */
>   public BDD value(long val) {
> ```

FYI this felt like the most compelling place to start
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDInteger.java, line 201 at r1](https://reviewable.io/reviews/batfish/batfish/7849#-MrPKVoU1jQ0a1kxYfFw:-MrPKVoU1jQ0a1kxYfFx:bomvj52) ([raw file](https://github.com/batfish/batfish/blob/e57226219c04082e0d34123e8ad9d51dc5d85667/projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDInteger.java#L201)):*
> ```Java
>     checkArgument(val <= _maxVal, "value %s is out of range [0, %s]", val, _maxVal);
>     long currentVal = val;
>     BDD[] bits = new BDD[_bitvec.length];
> ```

FYI could make this permanent array next to maxVal, but I doubt these allocations matter much.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDInteger.java, line 214 at r1](https://reviewable.io/reviews/batfish/batfish/7849#-MrPKb7G90g98goX1fkZ:-MrPKb7G90g98goX1fk_:b3ro7oe) ([raw file](https://github.com/batfish/batfish/blob/e57226219c04082e0d34123e8ad9d51dc5d85667/projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDInteger.java#L214)):*
> ```Java
>     for (BDD b : bits) {
>       b.free();
>     }
> ```

FYI was considering not freeing, but if the `_bitvec[i]` are not variables (aka, minesweeper) this is a lot of garbage.



_Code quote:_
```Java
    for (BDD b : bits) {
      b.free();
    }
```
___
*[projects/bdd/src/main/java/net/sf/javabdd/JFactory.java, line 1651 at r1](https://reviewable.io/reviews/batfish/batfish/7849#-MrPKo189rpDb3aOQxG-:-MrPKo189rpDb3aOQxG0:b-c0b3ub) ([raw file](https://github.com/batfish/batfish/blob/e57226219c04082e0d34123e8ad9d51dc5d85667/projects/bdd/src/main/java/net/sf/javabdd/JFactory.java#L1651)):*
> ```Java
>   }
> 
>   private int andAll_rec(int[] operands) {
> ```

FYI this is orAll swapping `or` for `and` and `1/0` for `0/1`.

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7849)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @anothermattbrown)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDInteger.java, line 207 at r1](https://reviewable.io/reviews/batfish/batfish/7849#-MrPLaYiEfA83TlOsDzn:-MrPLaYiEfA83TlOsDzo:b-nr826) ([raw file](https://github.com/batfish/batfish/blob/e57226219c04082e0d34123e8ad9d51dc5d85667/projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDInteger.java#L207)):*
> ```Java
>         bits[i] = b.id();
>       } else {
>         bits[i] = b.not();
> ```

Hmm, if this BDD is complex (not variables) then these `not` operations could be pretty expensive (in principle `diff` could be faster). Could do something faster like grouping them into bins and orAll / andAll / diff.

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7849)* status: all files reviewed, 1 unresolved discussion (waiting on @anothermattbrown)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7849)* status: all files reviewed, 1 unresolved discussion (waiting on @anothermattbrown)

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7849)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dhalperi)

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7849)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dhalperi)

**Pull request merged**
