### PR TITLE
XR: Improve BGP pipeline

### PR DESCRIPTION
**Pull request by corinaminer**
Two main changes that make XR behavior more correct and less Juniper-like:
- Local BGP routes are now present in the BGP RIB. These routes include redistributed routes, network-statement routes, and aggregate routes. Previously, they were exported upon creation without storing them anywhere on the device that generated them.
- BGP routes are now exported from the BGP RIB instead of the main RIB.

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7048)* status: all files reviewed, 3 unresolved discussions (waiting on @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java, line 269 at r1](https://reviewable.io/reviews/batfish/batfish/7048#-MbOIGIR24BH2Cqr7Rey:-MbOIGIR24BH2Cqr7Rez:b2ryvjo) ([raw file](https://github.com/batfish/batfish/blob/daf898a740079a4adf0f3909a9718eff5b9d75ce/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java#L269)):*
> ```Java
> 
>     // TODO Should probably create a special field in Configuration or Vrf to track this
>     _exportFromBgpRib =
> ```

Get it from `Configuration` as discussed offline.
___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java, line 550 at r1](https://reviewable.io/reviews/batfish/batfish/7048#-MbOIgCcCnPe_gxVCaGR:-MbOIgCcCnPe_gxVCaGS:b-n8rsuf) ([raw file](https://github.com/batfish/batfish/blob/daf898a740079a4adf0f3909a9718eff5b9d75ce/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java#L550)):*
> ```Java
>     if (!_exportFromBgpRib) {
>       assert _toRedistribute.values().stream().allMatch(RibDelta::isEmpty);
>       _toRedistribute.put(srcVrfName, mainRibDelta);
> ```

Why is this line in the `if`? How else are you going to get the stuff to redistribute?
Does this only pass because we have no vrf leaking implementation/tests on XR?
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConfiguration.java, line 858 at r1](https://reviewable.io/reviews/batfish/batfish/7048#-MbONlgCBJEWkS8NX9ob:-MbONlgCBJEWkS8NX9oc:b-wm4ftn) ([raw file](https://github.com/batfish/batfish/blob/c9c89d89dd1496d147dfd1cb7e8091dbd8fa150b/projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConfiguration.java#L858)):*
> ```Java
>         // TODO update to route-policy if valid, or delete grammar and VS
>       }
>       exportAggregateConditions.add(bgpRedistributeWithEnvironmentExpr(weInterior, OriginType.IGP));
> ```

Where are you setting origin type for redistributed routes? `SetOrigin` has been removed from refs.

**Review by arifogel — COMMENTED** [review]
> Reviewed 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7048)* status: all files reviewed, 3 unresolved discussions (waiting on @corinaminer)

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7048)* status: 16 of 17 files reviewed, 2 unresolved discussions (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java, line 269 at r1](https://reviewable.io/reviews/batfish/batfish/7048#-MbOIGIR24BH2Cqr7Rey:-MbORDIo4Drqeoun_4PR:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/daf898a740079a4adf0f3909a9718eff5b9d75ce/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java#L269)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Get it from `Configuration` as discussed offline.
</blockquote></details>

done
___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java, line 550 at r1](https://reviewable.io/reviews/batfish/batfish/7048#-MbOIgCcCnPe_gxVCaGR:-MbOVQVv-J5FL86skA71:btbqzxg) ([raw file](https://github.com/batfish/batfish/blob/daf898a740079a4adf0f3909a9718eff5b9d75ce/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java#L550)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Why is this line in the `if`? How else are you going to get the stuff to redistribute?
Does this only pass because we have no vrf leaking implementation/tests on XR?
</blockquote></details>

I'm not clear on the history of this field, but it is currently only used to preserve the main RIB delta (from our own VRF) in order to export those main RIB routes to neighbors later (despite being a map of VRFs to routes, it only ever has an entry for our VRF). It should never be populated or used when `_exportFromBgpRib` is set. Renamed and refactored to make this clearer.

In fact, `_mainRibPrev` also shouldn't be populated or used when `_exportFromBgpRib` is set. Cleaned that up too.
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConfiguration.java, line 858 at r1](https://reviewable.io/reviews/batfish/batfish/7048#-MbONlgCBJEWkS8NX9ob:-MbOXKvo7RWWSDZVXjyx:b-owmdsu) ([raw file](https://github.com/batfish/batfish/blob/c9c89d89dd1496d147dfd1cb7e8091dbd8fa150b/projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConfiguration.java#L858)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Where are you setting origin type for redistributed routes? `SetOrigin` has been removed from refs.
</blockquote></details>

yes, i thought it would be safe to remove because not only is `INCOMPLETE` the default origin type, but we also explicitly set redistributed routes' origin type to `INCOMPLETE` in `BgpProtocolHelper.convertNonBgpRouteToBgpRoute` (which we use on IGP routes to convert them to BGP before applying the redistribution policy).

Could set origin type to `INCOMPLETE` explicitly in the redistribution policy to be safe, i just don't think it will ever make a difference.

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7048)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java, line 550 at r1](https://reviewable.io/reviews/batfish/batfish/7048#-MbOIgCcCnPe_gxVCaGR:-MbOnhs-D1umyLx1z27J:b-8ukczg) ([raw file](https://github.com/batfish/batfish/blob/daf898a740079a4adf0f3909a9718eff5b9d75ce/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java#L550)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

I'm not clear on the history of this field, but it is currently only used to preserve the main RIB delta (from our own VRF) in order to export those main RIB routes to neighbors later (despite being a map of VRFs to routes, it only ever has an entry for our VRF). It should never be populated or used when `_exportFromBgpRib` is set. Renamed and refactored to make this clearer.

In fact, `_mainRibPrev` also shouldn't be populated or used when `_exportFromBgpRib` is set. Cleaned that up too.
</blockquote></details>

OK, I guess we'll find out if changes are needed when porting is done for formats that have BGP vrf leaking tests.
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConfiguration.java, line 858 at r1](https://reviewable.io/reviews/batfish/batfish/7048#-MbONlgCBJEWkS8NX9ob:-MbOo_lL21JDP29CHBXq:b12gkgh) ([raw file](https://github.com/batfish/batfish/blob/c9c89d89dd1496d147dfd1cb7e8091dbd8fa150b/projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConfiguration.java#L858)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

yes, i thought it would be safe to remove because not only is `INCOMPLETE` the default origin type, but we also explicitly set redistributed routes' origin type to `INCOMPLETE` in `BgpProtocolHelper.convertNonBgpRouteToBgpRoute` (which we use on IGP routes to convert them to BGP before applying the redistribution policy).

Could set origin type to `INCOMPLETE` explicitly in the redistribution policy to be safe, i just don't think it will ever make a difference.
</blockquote></details>

Can leave it out of routing policy if unneeded.

**Pull request merged**
