### PR TITLE
PAN: convert security rules per zone pair

### PR DESCRIPTION
**Pull request by sfraint**
Convert `security rules` once for each applicable from-zone, to-zone pair (instead of once per rule).

No functional change in this PR, but setting up for handling `application-override rules`.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6646)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6646)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @corinaminer, @dhalperi, and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java, line 1206 at r3](https://reviewable.io/reviews/batfish/batfish/6646#-MTwKu5A4SQlwb7Ck6BD:-MTwKu5A4SQlwb7Ck6BE:b74aw2q) ([raw file](https://github.com/batfish/batfish/blob/bc6b52c6bbd24d2e07f590de82e9fe9fc7802d79/projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java#L1206)):*
> ```
> ("PMD.UnusedFormalParameter")
> ```

presumably these will be used in a future PR?
___
*[projects/batfish/src/test/java/org/batfish/representation/palo_alto/PaloAltoConfigurationTest.java, line 685 at r3](https://reviewable.io/reviews/batfish/batfish/6646#-MTwLKDE8vEi1SKxDzcx:-MTwLKDE8vEi1SKxDzcy:b-usvjw4) ([raw file](https://github.com/batfish/batfish/blob/bc6b52c6bbd24d2e07f590de82e9fe9fc7802d79/projects/batfish/src/test/java/org/batfish/representation/palo_alto/PaloAltoConfigurationTest.java#L685)):*
> ```Java
> 
>   @Test
>   public void testSecurityRuleAppliesIntrazoneWarn() {
> ```

I don't quite understand why we would warn here.

I thought `securityRuleApplies` *is* the check that should disqualify a rule from applying to AC traffic.

E.g., if the rule is:

```
from-zone A B
to-zone A B
type: universal
```

1. the rule is correct. it means AA and BB, but not AB or BA.
2. But won't `securityRuleApplies` (incorrectly) warn on both AB and BA?

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6646)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @corinaminer, @dhalperi, and @sfraint)

___
*[projects/batfish/src/test/java/org/batfish/representation/palo_alto/PaloAltoConfigurationTest.java, line 685 at r3](https://reviewable.io/reviews/batfish/batfish/6646#-MTwLKDE8vEi1SKxDzcx:-MTwLj8eANhK8vRIDD9d:b-7nuwz7) ([raw file](https://github.com/batfish/batfish/blob/bc6b52c6bbd24d2e07f590de82e9fe9fc7802d79/projects/batfish/src/test/java/org/batfish/representation/palo_alto/PaloAltoConfigurationTest.java#L685)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I don't quite understand why we would warn here.

I thought `securityRuleApplies` *is* the check that should disqualify a rule from applying to AC traffic.

E.g., if the rule is:

```
from-zone A B
to-zone A B
type: universal
```

1. the rule is correct. it means AA and BB, but not AB or BA.
2. But won't `securityRuleApplies` (incorrectly) warn on both AB and BA?
</blockquote></details>

Or better put:

the warning could/should happen if the rule it:

```
from-zone A B
to-zone A B C
type: intrazone
```

(I meant `intrazone` above as well)

And the warning is that `C` only appears in `to-zone`.

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6646)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @corinaminer and @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java, line 1206 at r3](https://reviewable.io/reviews/batfish/batfish/6646#-MTwKu5A4SQlwb7Ck6BD:-MTwNpdbEtJf-ayPLqoR:b-7jzv7t) ([raw file](https://github.com/batfish/batfish/blob/bc6b52c6bbd24d2e07f590de82e9fe9fc7802d79/projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java#L1206)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> ("PMD.UnusedFormalParameter")
> ```

presumably these will be used in a future PR?
</blockquote></details>

right
___
*[projects/batfish/src/test/java/org/batfish/representation/palo_alto/PaloAltoConfigurationTest.java, line 685 at r3](https://reviewable.io/reviews/batfish/batfish/6646#-MTwLKDE8vEi1SKxDzcx:-MTwORQf-kPgMs_yBd-C:b-zduyfm) ([raw file](https://github.com/batfish/batfish/blob/bc6b52c6bbd24d2e07f590de82e9fe9fc7802d79/projects/batfish/src/test/java/org/batfish/representation/palo_alto/PaloAltoConfigurationTest.java#L685)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Or better put:

the warning could/should happen if the rule it:

```
from-zone A B
to-zone A B C
type: intrazone
```

(I meant `intrazone` above as well)

And the warning is that `C` only appears in `to-zone`.
</blockquote></details>

yeah that's right, I will undo this

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6646)* status: all files reviewed, 1 unresolved discussion (waiting on @corinaminer and @sfraint)

___
*[projects/batfish/src/test/java/org/batfish/representation/palo_alto/PaloAltoConfigurationTest.java, line 694 at r4](https://reviewable.io/reviews/batfish/batfish/6646#-MTwbdeCC1sKaV3i6dA4:-MTwbdeD4YYOHg7rGjmI:b-k385gv) ([raw file](https://github.com/batfish/batfish/blob/2df34087146f586ab8943f880c7a6ee86b2a7858/projects/batfish/src/test/java/org/batfish/representation/palo_alto/PaloAltoConfigurationTest.java#L694)):*
> ```Java
>     // valid intrazone
>     rule.setRuleType(RuleType.INTRAZONE);
>     assertTrue(checkIntrazoneValidityAndWarn(rule, new Warnings()));
> ```

should we be also checking no warnings here and above?

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6646)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @corinaminer and @dhalperi)

___
*[projects/batfish/src/test/java/org/batfish/representation/palo_alto/PaloAltoConfigurationTest.java, line 694 at r4](https://reviewable.io/reviews/batfish/batfish/6646#-MTwbdeCC1sKaV3i6dA4:-MTwct2e8fhKBS5U0xmg:bzifi3p) ([raw file](https://github.com/batfish/batfish/blob/2df34087146f586ab8943f880c7a6ee86b2a7858/projects/batfish/src/test/java/org/batfish/representation/palo_alto/PaloAltoConfigurationTest.java#L694)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

should we be also checking no warnings here and above?
</blockquote></details>

sure, checks for that

**Review by dhalperi — COMMENTED** [review]
> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6646)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6646)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java, line 1206 at r3](https://reviewable.io/reviews/batfish/batfish/6646#-MTwKu5A4SQlwb7Ck6BD:-MTx4uQE6WBnBXIDuJ7w:b-c1awbl) ([raw file](https://github.com/batfish/batfish/blob/bc6b52c6bbd24d2e07f590de82e9fe9fc7802d79/projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java#L1206)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

right
</blockquote></details>

(never mind, this will actually go away)

**Pull request merged**
