### PR TITLE
EVPN to BGPv4 VRF leak: Set BGP route admin

### PR DESCRIPTION
**Pull request by corinaminer**

### CODE REVIEW

**Review by sfraint — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7725)* status: all files reviewed, 1 unresolved discussion (waiting on @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java, line 2250 at r1](https://reviewable.io/reviews/batfish/batfish/7725#-MpJ22Vw1f_fFqoK0ICt:-MpJ22Vw1f_fFqoK0ICu:bwmlksu) ([raw file](https://github.com/batfish/batfish/blob/d84f63ffe75ded2e9a705b6976ae11d11173dd96/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java#L2250)):*
> ```
>         throw new IllegalArgumentException(
>             String.format("EVPN route has unexpected protocol %s", route.getProtocol()));
> ```
can this happen?

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7725)* status: all files reviewed, 1 unresolved discussion (waiting on @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java, line 2250 at r1](https://reviewable.io/reviews/batfish/batfish/7725#-MpJ22Vw1f_fFqoK0ICt:-MpJ5R4q968sNVsIc-4-:b-vdf1mq) ([raw file](https://github.com/batfish/batfish/blob/d84f63ffe75ded2e9a705b6976ae11d11173dd96/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java#L2250)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
>         throw new IllegalArgumentException(
>             String.format("EVPN route has unexpected protocol %s", route.getProtocol()));
> ```
can this happen?
</blockquote></details>

shouldn't be able to, no. `BGP`, `IBGP`, and `AGGREGATE` are the only possible protocols for a BGP route (which includes EVPN routes).

(Not even sure if it should be possible to have an `AGGREGATE` EVPN route, but if we did i think this would be the right behavior.)

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7725)* status: all files reviewed, 1 unresolved discussion (waiting on @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java, line 2250 at r1](https://reviewable.io/reviews/batfish/batfish/7725#-MpJ22Vw1f_fFqoK0ICt:-MpJ5xSV1O-u9fr1impa:bpopoz5) ([raw file](https://github.com/batfish/batfish/blob/d84f63ffe75ded2e9a705b6976ae11d11173dd96/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java#L2250)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

shouldn't be able to, no. `BGP`, `IBGP`, and `AGGREGATE` are the only possible protocols for a BGP route (which includes EVPN routes).

(Not even sure if it should be possible to have an `AGGREGATE` EVPN route, but if we did i think this would be the right behavior.)
</blockquote></details>

How about removing the `throw` then? Maybe just merge `IBGP` and `default` cases and `assert` that protocol is `IBGP` under that case?

Just to make it clearer that the throw isn't possible / avoid accidentally adding an exception.

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7725)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java, line 2250 at r1](https://reviewable.io/reviews/batfish/batfish/7725#-MpJ22Vw1f_fFqoK0ICt:-MpJN4zSEEQS3QtA90iR:b-162l94) ([raw file](https://github.com/batfish/batfish/blob/d84f63ffe75ded2e9a705b6976ae11d11173dd96/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java#L2250)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

How about removing the `throw` then? Maybe just merge `IBGP` and `default` cases and `assert` that protocol is `IBGP` under that case?

Just to make it clearer that the throw isn't possible / avoid accidentally adding an exception.
</blockquote></details>

Prefer having the supported cases shown explicitly, but added a comment to clarify that anything else shouldn't be possible.

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7725)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @corinaminer and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java, line 2250 at r1](https://reviewable.io/reviews/batfish/batfish/7725#-MpJ22Vw1f_fFqoK0ICt:-MpJOfRlArPhmrEPUOz6:b-j4qhw7) ([raw file](https://github.com/batfish/batfish/blob/d84f63ffe75ded2e9a705b6976ae11d11173dd96/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java#L2250)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Prefer having the supported cases shown explicitly, but added a comment to clarify that anything else shouldn't be possible.
</blockquote></details>

I meant:
```
case IBGP:
default:
  assert protocol == IBGP;
  admin = _process.getIbgpAdminCost();
```

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7725)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java, line 2250 at r1](https://reviewable.io/reviews/batfish/batfish/7725#-MpJ22Vw1f_fFqoK0ICt:-MpJZJqZAfWEj6pEP22X:bfe5p08) ([raw file](https://github.com/batfish/batfish/blob/d84f63ffe75ded2e9a705b6976ae11d11173dd96/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java#L2250)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

I meant:
```
case IBGP:
default:
  assert protocol == IBGP;
  admin = _process.getIbgpAdminCost();
```
</blockquote></details>

Got it. done

**Review by sfraint — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7725)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

**Pull request merged**
