### PR TITLE
Update NodeProperties for new community structures

### PR DESCRIPTION
**Pull request by arifogel**
- populate NodeProperties facts for the 4 new community processing structures

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6740)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @arifogel)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/NodePropertySpecifier.java, line 91 at r1](https://reviewable.io/reviews/batfish/batfish/6740#-MVxFyZN9YCcvwSGov7V:-MVxFyZN9YCcvwSGov7W:bmabe29) ([raw file](https://github.com/batfish/batfish/blob/35858d0a3f415b606d9bd2c310d03456d6b82c0e/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/NodePropertySpecifier.java#L91)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>               COMMUNITY_LISTS,
>               new PropertyDescriptor<>(
>                   /* TODO rename and break this up as appropriate. For now, every vendor that had
>                   `CommunityList`s should have `CommunitySetMatchExpr`s with the same name.*/
> ```
</details>

Please fix correctly, and update downstream refs.

**Comment by dhalperi** [comment]
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/NodePropertySpecifier.java, line 91 at r1](https://reviewable.io/reviews/batfish/batfish/6740#-MVxFyZN9YCcvwSGov7V:-MVxG7264EYah5rCvV0Q:byhrlga) ([raw file](https://github.com/batfish/batfish/blob/35858d0a3f415b606d9bd2c310d03456d6b82c0e/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/NodePropertySpecifier.java#L91)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
>               COMMUNITY_LISTS,
>               new PropertyDescriptor<>(
>                   /* TODO rename and break this up as appropriate. For now, every vendor that had
>                   `CommunityList`s should have `CommunitySetMatchExpr`s with the same name.*/
> ```
Please fix correctly, and update downstream refs.
</blockquote></details>

Separate issue to remove the COMMUNITY_LIST property, of course.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6740)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel)

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6740)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @dhalperi)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6740#-MVxITi6BY-vcUtg3qdP:-MVxITi6BY-vcUtg3qdQ:bowmrb6) (no related file):*
Updated PR title and description. Just adds entries for the new structures now. Forthcoming pybatfish PR with new facts.

---
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/NodePropertySpecifier.java, line 91 at r1](https://reviewable.io/reviews/batfish/batfish/6740#-MVxFyZN9YCcvwSGov7V:-MVxISxX4tbnS1vGNV4T:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/35858d0a3f415b606d9bd2c310d03456d6b82c0e/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/NodePropertySpecifier.java#L91)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Separate issue to remove the COMMUNITY_LIST property, of course.
</blockquote></details>

done

**Review by dhalperi — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6740#-:-MVxIeN5B1LprFsWFjbD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
