### PR TITLE
CheckPoint: use VS model to determine domain -> gateway association

### PR DESCRIPTION
**Pull request by sfraint**
Don't rely on VI model being populated yet, to determine domain to gateway association.

Also, go ahead and convert management config earlier in the pipeline, so we can use that information for converting other datamodel classes in the future.

### CODE REVIEW

**Review by corinaminer — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7292)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java, line 178 at r1](https://reviewable.io/reviews/batfish/batfish/7292#-MiSQD4m47SayrpBJa_e:-MiSQD4m47SayrpBJa_f:b-27yupg) ([raw file](https://github.com/batfish/batfish/blob/ddda7fe5954352416803878b4284a977657ea974/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java#L178)):*
> ```Java
>     Set<Ip> ips =
>         _interfaces.values().stream()
>             .map(Interface::getAddress)
> ```

do you know if the gateway can be matched to the server using a non-primary IP address? I don't even know for sure that checkpoint interfaces can have secondary addresses, but might be worth a todo. nonblocking

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7292)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java, line 178 at r1](https://reviewable.io/reviews/batfish/batfish/7292#-MiSQD4m47SayrpBJa_e:-MiSQ_gZ6cWCoBycP0M7:b-ctjzvb) ([raw file](https://github.com/batfish/batfish/blob/ddda7fe5954352416803878b4284a977657ea974/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java#L178)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

do you know if the gateway can be matched to the server using a non-primary IP address? I don't even know for sure that checkpoint interfaces can have secondary addresses, but might be worth a todo. nonblocking
</blockquote></details>

Not sure if they can be matched on alternate interface addresses. We don't support those yet anyhow, but I can go ahead and add a TODO

**Review by corinaminer — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7292)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @arifogel)

**Review by corinaminer — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7292)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Pull request merged**
