### PR TITLE
Cisco IOS: fix NatPool construction for first+last Ips within a subnet.

### PR DESCRIPTION
**Pull request by anothermattbrown**
When a pool is configured with first/last IPs and a subnet, update the first and last IPs to be host IPs within the subnet.
Previously, we didn't update when the first IP was the broadcast IP or the last IP was the network IP.

### CODE REVIEW

**Comment by anothermattbrown** [comment]
@sfraint you mentioned that we have similar logic for other vendors -- can you point me at them? I can fix any that need it.

**Review by sfraint — COMMENTED** [review]
The two things I was thinking of are apparently different:

A10: we're *not* altering the provided start and end ip:
https://github.com/batfish/batfish/blob/master/projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java#L680

and CheckPoint: we're using the first ip and last ip for a *network*, which isn't defined by start and end ip:
https://github.com/batfish/batfish/blob/master/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversions.java#L118

> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7712#-:-Mooe17D9qUyFYFqdNQ4:b-vhrnpi)* status: 0 of 3 files reviewed, all discussions resolved

**Review by sfraint — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7712)* status: all files reviewed, 1 unresolved discussion (waiting on @anothermattbrown)

___
*[projects/batfish/src/main/java/org/batfish/representation/cisco/NatPool.java, line 28 at r1](https://reviewable.io/reviews/batfish/batfish/7712#-MooeYnZ9PWXtifyNpXU:-MooeYnZ9PWXtifyNpXV:bkmdqwi) ([raw file](https://github.com/batfish/batfish/blob/6d66c5ccda510fb38816f9bd3c05e714267e38f7/projects/batfish/src/main/java/org/batfish/representation/cisco/NatPool.java#L28)):*
> ```
>     checkArgument(first.compareTo(last) <= 0, "first IP cannot be greater than last IP");
> ```
this throws, right? I think the caller needs to check this first and skip + warn in the case this doesn't hold

we usually also add a grammar test for warnings in situations like this (also implicitly tests that extraction doesn't error out); e.g. see this test https://github.com/batfish/batfish/blob/master/projects/batfish/src/test/java/org/batfish/vendor/a10/grammar/A10GrammarTest.java#L1107-L1129

**Review by anothermattbrown — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7712)* status: all files reviewed, 1 unresolved discussion (waiting on @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/representation/cisco/NatPool.java, line 28 at r1](https://reviewable.io/reviews/batfish/batfish/7712#-MooeYnZ9PWXtifyNpXU:-MoogpWp8ZuHvNhkMRzt:b8gnr6a) ([raw file](https://github.com/batfish/batfish/blob/6d66c5ccda510fb38816f9bd3c05e714267e38f7/projects/batfish/src/main/java/org/batfish/representation/cisco/NatPool.java#L28)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
>     checkArgument(first.compareTo(last) <= 0, "first IP cannot be greater than last IP");
> ```
this throws, right? I think the caller needs to check this first and skip + warn in the case this doesn't hold

we usually also add a grammar test for warnings in situations like this (also implicitly tests that extraction doesn't error out); e.g. see this test https://github.com/batfish/batfish/blob/master/projects/batfish/src/test/java/org/batfish/vendor/a10/grammar/A10GrammarTest.java#L1107-L1129
</blockquote></details>

yes the caller is checking that and won't try to create the nat pool in that case. the code (and presumably test) is already there. I'm just making documenting and checking the invariant

**Review by anothermattbrown — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7712)* status: all files reviewed, 2 unresolved discussions (waiting on @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7712#-MoohQ7_EvBaa6J6OpxW:-MoohQ7_EvBaa6J6OpxX:bd5cx4m) (no related file):*
according to https://learningnetwork.cisco.com/s/question/0D53i00000Lzslh/ip-nat-pool-prefixlength-and-netmask-options, IOS interprets first=last=network as an empty NAT pool. this PR doesn't do that (instead interprets it as first host IP, and similarly first=last=broadcast as last host IP). 

---

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7712)* status: all files reviewed, 1 unresolved discussion (waiting on @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/representation/cisco/NatPool.java, line 28 at r1](https://reviewable.io/reviews/batfish/batfish/7712#-MooeYnZ9PWXtifyNpXU:-MoohyxQERWvdSDMGTh-:b4c9lyr) ([raw file](https://github.com/batfish/batfish/blob/6d66c5ccda510fb38816f9bd3c05e714267e38f7/projects/batfish/src/main/java/org/batfish/representation/cisco/NatPool.java#L28)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

yes the caller is checking that and won't try to create the nat pool in that case. the code (and presumably test) is already there. I'm just making documenting and checking the invariant
</blockquote></details>

:thumbsup:

**Review by anothermattbrown — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7712)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7712#-MoohQ7_EvBaa6J6OpxW:-MooziEDCB9IlNPRVU8L:btfgmnn) (no related file):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

according to https://learningnetwork.cisco.com/s/question/0D53i00000Lzslh/ip-nat-pool-prefixlength-and-netmask-options, IOS interprets first=last=network as an empty NAT pool. this PR doesn't do that (instead interprets it as first host IP, and similarly first=last=broadcast as last host IP). 
</blockquote></details>

updated to interpret this as an empty pool and warn (since we can't currently model IOS semantics for empty pools)

---

**Review by sfraint — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7712)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown)

**Review by sfraint — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7712)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown)

**Pull request merged**
