### PR TITLE
Add a negate flag to HeaderLocationQuestions #831

### PR DESCRIPTION
**Pull request by anothermattbrown**
This change is [Reviewable](https://reviewable.io/reviews/batfish/batfish/852)

### CODE REVIEW

**Comment by rabeckett** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/852#-:-L30B5I6XLFpJCHDYUJX:bnfp4nl)*

**Comment by dhalperi** [comment]
:lgtm:

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/java/org/batfish/symbolic/smt/PropertyChecker.java, line 516 at r1](https://reviewable.io:443/reviews/batfish/batfish/852#-L30Cuk4PmVUJqY9oAzV:-L30Cuk4PmVUJqY9oAzW:b-ytr2fn) ([raw file](https://github.com/batfish/batfish/blob/4c024511d0ef9ac932d88ddb34d82ea211a86027/projects/batfish/src/main/java/org/batfish/symbolic/smt/PropertyChecker.java#L516)):*
> ```Java
>                         }
>                         reachVals.put(nm, val);
>                       });
> ```

Might be more readable using streams:

```java
Map<String, Boolean> reachVals =
    vp.getProp().entrySet().stream()
    .collect(toMap(nm -> nm, expr -> ce.isTrue(expr) ^ q.getNegate()));
```

aka https://stackoverflow.com/a/22744309/1715495

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/852#-:-L30EWxKTfInhGJf26nW:bnfp4nl)*

**Comment by anothermattbrown** [comment]
Review status: 10 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/java/org/batfish/symbolic/smt/PropertyChecker.java, line 516 at r1](https://reviewable.io:443/reviews/batfish/batfish/852#-L30Cuk4PmVUJqY9oAzV:-L3U28oGEfR0Mb_Bk4UW:bhquuw0) ([raw file](https://github.com/batfish/batfish/blob/4c024511d0ef9ac932d88ddb34d82ea211a86027/projects/batfish/src/main/java/org/batfish/symbolic/smt/PropertyChecker.java#L516)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Might be more readable using streams:

```java
Map<String, Boolean> reachVals =
    vp.getProp().entrySet().stream()
    .collect(toMap(nm -> nm, expr -> ce.isTrue(expr) ^ q.getNegate()));
```

aka https://stackoverflow.com/a/22744309/1715495
</blockquote></details>

Sorry, just noticed this is blocked on me. Looks good, pushed a fixup.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/852)*

**Comment by dhalperi** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/852#-:-L3UNoESkf23LYReRDE6:bnfp4nl)*

**Pull request merged**
