### PR TITLE
Checkpoint NAT conversion skeleton

### PR DESCRIPTION
**Pull request by arifogel**
- interfaces and visitors for NAT rule concepts
- partial conversion, but not applied to any interfaces

### CODE REVIEW

**Review by sfraint — COMMENTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7306)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConversions.java, line 52 at r1](https://reviewable.io/reviews/batfish/batfish/7306#-MicBo-S-a65ubIhxVy-:-MicBo-S-a65ubIhxVy0:b9dzzes) ([raw file](https://github.com/batfish/batfish/blob/b1aeb0cf77de3a7906ed3cd75c4c99cf635f8959/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConversions.java#L52)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>     } else {
>       warnings.redFlag(
>           String.format(
>               "NAT rule original-source %s has unsupported type %s and will be ignored",
>               src.getName(), src.getClass()));
>     }
> ```
</details>

a problem for another day, but if we encounter unsupported types - do we want to fail with an unconstrained headerspace? or fail with an unmatchable headerspace?

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7306)* status: 9 of 13 files reviewed, 1 unresolved discussion (waiting on @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConversions.java, line 52 at r1](https://reviewable.io/reviews/batfish/batfish/7306#-MicBo-S-a65ubIhxVy-:-MicIlPr9r5z0mo0fqgC:brx1vod) ([raw file](https://github.com/batfish/batfish/blob/b1aeb0cf77de3a7906ed3cd75c4c99cf635f8959/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConversions.java#L52)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
>     } else {
>       warnings.redFlag(
>           String.format(
>               "NAT rule original-source %s has unsupported type %s and will be ignored",
>               src.getName(), src.getClass()));
>     }
> ```
a problem for another day, but if we encounter unsupported types - do we want to fail with an unconstrained headerspace? or fail with an unmatchable headerspace?
</blockquote></details>

Let's leave for now.
In a follow-up I will ditch the rule entirely if anything is wrong with the original/translated types.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7306)* status: 9 of 13 files reviewed, 1 unresolved discussion (waiting on @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConversions.java, line 52 at r1](https://reviewable.io/reviews/batfish/batfish/7306#-MicBo-S-a65ubIhxVy-:-MicIxYwAjW-d8h4C0Mk:b-t4zhh3) ([raw file](https://github.com/batfish/batfish/blob/b1aeb0cf77de3a7906ed3cd75c4c99cf635f8959/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConversions.java#L52)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Let's leave for now.
In a follow-up I will ditch the rule entirely if anything is wrong with the original/translated types.
</blockquote></details>

So actually this is fine as is, since it's just for the warning.

**Review by sfraint — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7306)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Pull request merged**
