### PR TITLE
Juniper: overhaul apply-groups processing

### PR DESCRIPTION
**Pull request by arifogel**
* fixes batfish/batfish#8818
* correctly prioritize deeper over shallower apply-groups
* correctly prioritize list-like and non-list-like inherited hierarchy nodes
  * low priority list-like nodes appear should be applied later than  higher priority nodes, e.g. inherited default term of a firewall filter
  * non-list-like inherited values should be applied earlier than higher priority nodes which overwrite them, e.g. inherited MTU should be overriden by later explicit MTU
* create maintainable mechanism indicating hierarchy paths to nodes with ordered list children
  * See `JuniperListPaths` class
* retain `apply-groups` and `apply-groups-except` lines
  * correctly preserves hierarchy not otherwise filled out

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 27 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8841)* status: 1 of 27 files reviewed, 3 unresolved discussions (waiting on @arifogel, @sfraint, and @SLarkworthy)

___
*[`projects/batfish/src/test/resources/org/batfish/main/testconfigs/preprocess-flat-after` line 5 at r1](https://reviewable.io/reviews/batfish/batfish/8841#-NguEwzt6I1wB-yKweaR:-NguEwzt6I1wB-yKweaS:bx47hgr) ([raw file](https://github.com/batfish/batfish/blob/41725314ff940ab911f7dab898c1ac501367170c/projects/batfish/src/test/resources/org/batfish/main/testconfigs/preprocess-flat-after#L5)):*
> ```
> set interfaces et-0/0/4 disable
> set interfaces lo0 disable
> set interfaces lo0 apply-groups g1
> ```

I assume there's a reason, but why are we leaving these in now?
___
*[`projects/batfish/src/test/resources/org/batfish/main/testconfigs/preprocess-flat-before` line 4 at r1](https://reviewable.io/reviews/batfish/batfish/8841#-NguEscH-IUijubiQXDt:-NguEscH-IUijubiQXDu:b-b8ymyc) ([raw file](https://github.com/batfish/batfish/blob/41725314ff940ab911f7dab898c1ac501367170c/projects/batfish/src/test/resources/org/batfish/main/testconfigs/preprocess-flat-before#L4)):*
> ```
> 
> ```

what changed here?
___
*[`tests/parsing-tests/unit-tests-vimodel.ref` line 60137 at r1](https://reviewable.io/reviews/batfish/batfish/8841#-NguEbi4-7qGSDdqeEEz:-NguEbi4-7qGSDdqeEF-:bpkaqit) ([raw file](https://github.com/batfish/batfish/blob/41725314ff940ab911f7dab898c1ac501367170c/tests/parsing-tests/unit-tests-vimodel.ref#L60137)):*
> ```
>         "disconnectAdminDownInterfaces" : true,
>         "interfaces" : {
>           "node1::xe-0/0/0:0" : {
> ```

this feels worrisome and like a problem for lots of downstream code. what's happening here?

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8841)* status: 1 of 27 files reviewed, 3 unresolved discussions (waiting on @dhalperi, @sfraint, and @SLarkworthy)

___
*[`projects/batfish/src/test/resources/org/batfish/main/testconfigs/preprocess-flat-after` line 5 at r1](https://reviewable.io/reviews/batfish/batfish/8841#-NguEwzt6I1wB-yKweaR:-NguQjwX8zu3sEDkkHmC:b8rm0to) ([raw file](https://github.com/batfish/batfish/blob/41725314ff940ab911f7dab898c1ac501367170c/projects/batfish/src/test/resources/org/batfish/main/testconfigs/preprocess-flat-after#L5)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I assume there's a reason, but why are we leaving these in now?
</blockquote></details>

In case a group is applied but no lines are pulled in as a result, the apply-groups line should remain in order to fill out the hierarchy.
I believe we have a related existing bug related to apply-path where we don't keep the apply-path line when nothing is pulled in, and then we lose the config leading up to apply-path.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8841)* status: 1 of 27 files reviewed, 3 unresolved discussions (waiting on @dhalperi, @sfraint, and @SLarkworthy)

___
*[`projects/batfish/src/test/resources/org/batfish/main/testconfigs/preprocess-flat-before` line 4 at r1](https://reviewable.io/reviews/batfish/batfish/8841#-NguEscH-IUijubiQXDt:-NguR1hO39HXYeaWcGFS:b-kkbozf) ([raw file](https://github.com/batfish/batfish/blob/41725314ff940ab911f7dab898c1ac501367170c/projects/batfish/src/test/resources/org/batfish/main/testconfigs/preprocess-flat-before#L4)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

what changed here?
</blockquote></details>

Enter key gets stuck on remote desktop intellij when opening file, fun stuff.

Reverted.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8841)* status: 1 of 27 files reviewed, 3 unresolved discussions (waiting on @dhalperi, @sfraint, and @SLarkworthy)

___
*[`tests/parsing-tests/unit-tests-vimodel.ref` line 60137 at r1](https://reviewable.io/reviews/batfish/batfish/8841#-NguEbi4-7qGSDdqeEEz:-NguRTTCDWhivA7aUcvO:bkh0c8q) ([raw file](https://github.com/batfish/batfish/blob/41725314ff940ab911f7dab898c1ac501367170c/tests/parsing-tests/unit-tests-vimodel.ref#L60137)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

this feels worrisome and like a problem for lots of downstream code. what's happening here?
</blockquote></details>

This interface is declared, but only via an apply-groups line. I argued in a comment above that apply-groups lines should be retained to preserve the hierarchy leading up to them. This is an example thereof.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8841)* status: 1 of 27 files reviewed, 3 unresolved discussions (waiting on @dhalperi, @sfraint, and @SLarkworthy)

___
*[`tests/parsing-tests/unit-tests-vimodel.ref` line 60137 at r1](https://reviewable.io/reviews/batfish/batfish/8841#-NguEbi4-7qGSDdqeEEz:-NguRwuNC74k-0fntc_7:biimcdj) ([raw file](https://github.com/batfish/batfish/blob/41725314ff940ab911f7dab898c1ac501367170c/tests/parsing-tests/unit-tests-vimodel.ref#L60137)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

This interface is declared, but only via an apply-groups line. I argued in a comment above that apply-groups lines should be retained to preserve the hierarchy leading up to them. This is an example thereof.
</blockquote></details>

from `tests/parsing-tests/networks/unit-tests/configs/juniper-interfaces`:
```
set interfaces node1:xe-0/0/0 apply-groups MTU_GROUP
set interfaces node1:xe-0/0/0:0 apply-groups MTU_GROUP
set interfaces node1:xe-0/0/0:0.0 apply-groups MTU_GROUP
```

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 27 files at r1, 4 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8841)* status: 7 of 28 files reviewed, 4 unresolved discussions (waiting on @arifogel, @sfraint, and @SLarkworthy)

___
*[`projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ApplyGroupsMarker.java` line 44 at r2](https://reviewable.io/reviews/batfish/batfish/8841#-Ngv5sbbB5pSf5ybVDMU:-Ngv5sbbB5pSf5ybVDMV:b-tsq8fn) ([raw file](https://github.com/batfish/batfish/blob/e44d3b395fe36b18ca8a53eff1a4014c61817b4e/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ApplyGroupsMarker.java#L44)):*
> ```Java
>       return;
>     }
>     _hierarchy.addMasterPath(_currentPath, null, null);
> ```

what's the intuition behind adding the master path before checking presence? Since it doesn't take `ctx`, seems like might not be necessary?
___
*[`projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/Hierarchy.java` line 55 at r2](https://reviewable.io/reviews/batfish/batfish/8841#-Ngv6MNDEDbW3BnB3md2:-Ngv6MNDEDbW3BnB3md3:b-10ix01) ([raw file](https://github.com/batfish/batfish/blob/e44d3b395fe36b18ca8a53eff1a4014c61817b4e/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/Hierarchy.java#L55)):*
> ```Java
>   /** Dump all set lines and error nodes from the main tree. */
>   public @Nonnull List<ParseTree> extractParseTrees() {
>     ImmutableList.Builder<ParseTree> builder = ImmutableList.builder();
> ```

any way to get size here? `builderWithSize` would save a bunch of allocations and copies if accurate.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8841)* status: 6 of 28 files reviewed, 4 unresolved discussions (waiting on @dhalperi, @sfraint, and @SLarkworthy)

___
*[`projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ApplyGroupsMarker.java` line 44 at r2](https://reviewable.io/reviews/batfish/batfish/8841#-Ngv5sbbB5pSf5ybVDMU:-Ngv8F229HRnTavv7Sey:bi0y29f) ([raw file](https://github.com/batfish/batfish/blob/e44d3b395fe36b18ca8a53eff1a4014c61817b4e/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ApplyGroupsMarker.java#L44)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

what's the intuition behind adding the master path before checking presence? Since it doesn't take `ctx`, seems like might not be necessary?
</blockquote></details>

I don't remember why this was here, might be from my abandoned first two implementations or prior to changes to InitialTreeBuilder.
Tests pass with it removed, and I don't see why the path wouldn't already exist.

**Comment by dhalperi** [comment]
*[`projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/Hierarchy.java` line 346 at r4](https://reviewable.io/reviews/batfish/batfish/8841#-NgvBrhzB7dYLAQ1-fTL:-NgvBrhzB7dYLAQ1-fTM:bpeygpp) ([raw file](https://github.com/batfish/batfish/blob/742a9f996911c7b3902bd0d12c2a4467d9cef03e/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/Hierarchy.java#L346)):*
> ```Java
>      * matching node in this tree at each depth.
>      *
>      * <p>TODO: backtracking(?) on wildcard choices that eventually fail at greater depth
> ```

is there a github issue # or failing test or some other indication of what this TODO means for future readers?

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8841)* status: 6 of 28 files reviewed, 3 unresolved discussions (waiting on @dhalperi, @sfraint, and @SLarkworthy)

___
*[`projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/Hierarchy.java` line 55 at r2](https://reviewable.io/reviews/batfish/batfish/8841#-Ngv6MNDEDbW3BnB3md2:-NgvCWJE7XipNVO_4BpW:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/e44d3b395fe36b18ca8a53eff1a4014c61817b4e/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/Hierarchy.java#L55)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

any way to get size here? `builderWithSize` would save a bunch of allocations and copies if accurate.
</blockquote></details>

done

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8841)* status: 6 of 29 files reviewed, 3 unresolved discussions (waiting on @dhalperi, @sfraint, and @SLarkworthy)

___
*[`projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/Hierarchy.java` line 346 at r4](https://reviewable.io/reviews/batfish/batfish/8841#-NgvBrhzB7dYLAQ1-fTL:-NgvKCM43PNs9U9x-8cQ:bskqa66) ([raw file](https://github.com/batfish/batfish/blob/742a9f996911c7b3902bd0d12c2a4467d9cef03e/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/Hierarchy.java#L346)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

is there a github issue # or failing test or some other indication of what this TODO means for future readers?
</blockquote></details>

added  `testApplyGroupsWildcardNestingExtraction`, updated comment here

**Review by dhalperi — COMMENTED** [review]
> Reviewed 17 of 27 files at r1, 1 of 6 files at r2, 1 of 2 files at r4, 2 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8841)* status: 27 of 29 files reviewed, 4 unresolved discussions (waiting on @arifogel, @sfraint, and @SLarkworthy)

___
*[`projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/Hierarchy.java` line 128 at r6](https://reviewable.io/reviews/batfish/batfish/8841#-NgwApM40k816Gul0gHu:-NgwApM40k816Gul0gHv:b-ddny4j) ([raw file](https://github.com/batfish/batfish/blob/d9f345766f1b812a740324b22fdd748d8ba69c23/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/Hierarchy.java#L128)):*
> ```Java
>    * does not matter. Returns {@code true} iff the hierarchy was modified.
>    */
>   private boolean inheritGroupsIntoNonListNode(
> ```

just observing there is a lot of work in these functions -- anyway to detect if it's not needed up front?
___
*[`projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/JuniperListPaths.java` line 23 at r6](https://reviewable.io/reviews/batfish/batfish/8841#-Ngw9XD5C7o-ShSnw1Bj:-Ngw9XD5C7o-ShSnw1Bk:b8lvhui) ([raw file](https://github.com/batfish/batfish/blob/d9f345766f1b812a740324b22fdd748d8ba69c23/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/JuniperListPaths.java#L23)):*
> ```Java
>         "firewall family inet filter <*> term",
>         "firewall filter <*> term",
>         "interfaces <*> unit <*> family inet filter input-list",
> ```

output-list?
___
*[`projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/JuniperListPaths.java` line 26 at r6](https://reviewable.io/reviews/batfish/batfish/8841#-Ngw9YMD7OknQFFfVSh7:-Ngw9YMD7OknQFFfVSh8:bi9cah7) ([raw file](https://github.com/batfish/batfish/blob/d9f345766f1b812a740324b22fdd748d8ba69c23/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/JuniperListPaths.java#L26)):*
> ```Java
>         "policy-options policy-statement <*> term",
>         "security policies from-zone <*> to-zone <*> policy",
>         "system domain-search"
> ```

a few more from our unit tests

```
set protocols bgp group s21 export to-s21  
set protocols bgp group s21 import from-s21
set security nat destination rule-set RULE-SET-ZONE rule RULE1 match source-address-name SA-NAME
set security nat source rule-set SRC-NAT rule SRC-RULE3 then source-nat pool POOL
```

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8841)* status: 27 of 29 files reviewed, 5 unresolved discussions (waiting on @arifogel, @sfraint, and @SLarkworthy)

___
*[`projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/Hierarchy.java` line 133 at r6](https://reviewable.io/reviews/batfish/batfish/8841#-NgwAvq_C1wt02UtIZo_:-NgwAvq_C1wt02UtIZoa:b-gydxtj) ([raw file](https://github.com/batfish/batfish/blob/d9f345766f1b812a740324b22fdd748d8ba69c23/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/Hierarchy.java#L133)):*
> ```Java
>       HierarchyPath inheritorNodePath,
>       List<String> prioritizedGroups,
>       Set<String> exceptGroups) {
> ```

have you tried this on the very large parsing stress tests we have?

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 27 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8841)* status: 28 of 29 files reviewed, 5 unresolved discussions (waiting on @arifogel, @sfraint, and @SLarkworthy)

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8841)* status: 28 of 29 files reviewed, 5 unresolved discussions (waiting on @dhalperi, @sfraint, and @SLarkworthy)

___
*[`projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/Hierarchy.java` line 133 at r6](https://reviewable.io/reviews/batfish/batfish/8841#-NgwAvq_C1wt02UtIZo_:-NgyzmvM5mU_kMp-jozt:b8hqh7x) ([raw file](https://github.com/batfish/batfish/blob/d9f345766f1b812a740324b22fdd748d8ba69c23/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/Hierarchy.java#L133)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

have you tried this on the very large parsing stress tests we have?
</blockquote></details>

I took a large pile of Juniper configs I had lying around and ran master vs this branch:
master: 263 seconds
PR: 323 seconds

Probably worth looking into more optimization, but we could also punt until after correctness is in. Thoughts?

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8841)* status: 28 of 29 files reviewed, 5 unresolved discussions (waiting on @dhalperi, @sfraint, and @SLarkworthy)

___
*[`projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/JuniperListPaths.java` line 23 at r6](https://reviewable.io/reviews/batfish/batfish/8841#-Ngw9XD5C7o-ShSnw1Bj:-Ngz-ez07Us7liARZOLs:b-7tfmjp) ([raw file](https://github.com/batfish/batfish/blob/d9f345766f1b812a740324b22fdd748d8ba69c23/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/JuniperListPaths.java#L23)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

output-list?
</blockquote></details>

added
___
*[`projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/JuniperListPaths.java` line 26 at r6](https://reviewable.io/reviews/batfish/batfish/8841#-Ngw9YMD7OknQFFfVSh7:-Ngz-fPuE896Rpo0J0-s:b-7tfmjp) ([raw file](https://github.com/batfish/batfish/blob/d9f345766f1b812a740324b22fdd748d8ba69c23/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/JuniperListPaths.java#L26)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

a few more from our unit tests

```
set protocols bgp group s21 export to-s21  
set protocols bgp group s21 import from-s21
set security nat destination rule-set RULE-SET-ZONE rule RULE1 match source-address-name SA-NAME
set security nat source rule-set SRC-NAT rule SRC-RULE3 then source-nat pool POOL
```
</blockquote></details>

added

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 3 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8841)* status: all files reviewed, 4 unresolved discussions (waiting on @arifogel, @sfraint, and @SLarkworthy)

___
*[`projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/Hierarchy.java` line 91 at r7](https://reviewable.io/reviews/batfish/batfish/8841#-NgzHpqf8_JlPSWxiF3q:-NgzHpqf8_JlPSWxiF3r:b-y4lpz2) ([raw file](https://github.com/batfish/batfish/blob/6c872eb399eda2218354194d16e113c1076ad977/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/Hierarchy.java#L91)):*
> ```Java
>    * Returns {@code true} iff the hierarchy was modified.
>    */
>   public boolean inheritGroups(
> ```

Do all these different `inheritGroups` functions need to be `public`? Which one is the user facing API / can we simplify it?
___
*[`projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/Hierarchy.java` line 187 at r7](https://reviewable.io/reviews/batfish/batfish/8841#-NgzIIvO7IFmKPhc3JH1:-NgzIIvO7IFmKPhc3JH2:bow0gar) ([raw file](https://github.com/batfish/batfish/blob/6c872eb399eda2218354194d16e113c1076ad977/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/Hierarchy.java#L187)):*
> ```Java
>   /**
>    * Inherit from a given group node's child into a main tree node whose children are either a
>    * scalar value, or whose order does not matter.
> ```

Reading it, I think this comment and name will not convey the critical point that configuration in the main tree will take effect after inherited configuration. Maybe I'd say that, and then explain that Scalars in the main tree will "win" and lists will include inherited configuration ahead of configuration from the main tree. This could be wrong (link to github issue) for lists where order matters.
___
*[`projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/Hierarchy.java` line 747 at r7](https://reviewable.io/reviews/batfish/batfish/8841#-NgzObzWAjUq4cFzB4Ns:-NgzObzX-hdIPCSBxuCg:bxj8uzj) ([raw file](https://github.com/batfish/batfish/blob/6c872eb399eda2218354194d16e113c1076ad977/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/Hierarchy.java#L747)):*
> ```Java
>       HierarchyChildNode matchNode = null;
>       for (int i = 0; i < path._nodes.size(); i++) {
>         HierarchyChildNode currentPathNode = path._nodes.get(i);
> ```

What's happening here? I guess you had to make the change because of modifying `path._nodes` (but only appending so that `i` is useful)?



_Code quote:_
```Java
      for (int i = 0; i < path._nodes.size(); i++) {
        HierarchyChildNode currentPathNode = path._nodes.get(i);
```
___
*[`projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/JuniperListPaths.java` line 26 at r6](https://reviewable.io/reviews/batfish/batfish/8841#-Ngw9YMD7OknQFFfVSh7:-NgzDhKb4JFsYRBqR5xq:b-328x37) ([raw file](https://github.com/batfish/batfish/blob/d9f345766f1b812a740324b22fdd748d8ba69c23/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/JuniperListPaths.java#L26)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

added
</blockquote></details>

This is on me for being lazy in copying lines out of tests. You added the lines I intended, but also more.

Are the `match source-address-name` and `then source-nat pool` themselves lists (where order matters)?

I imagine without checking the first one can be a list where order doesn't matter, but the second one probably not. If so, sorry for being lazy and can you delete those?

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8841)* status: 27 of 29 files reviewed, 4 unresolved discussions (waiting on @dhalperi, @sfraint, and @SLarkworthy)

___
*[`projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/Hierarchy.java` line 128 at r6](https://reviewable.io/reviews/batfish/batfish/8841#-NgwApM40k816Gul0gHu:-Nh2ugom0X10czOPOsiO:b-u56ue1) ([raw file](https://github.com/batfish/batfish/blob/d9f345766f1b812a740324b22fdd748d8ba69c23/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/Hierarchy.java#L128)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

just observing there is a lot of work in these functions -- anyway to detect if it's not needed up front?
</blockquote></details>

Probably, but deferring.
___
*[`projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/Hierarchy.java` line 747 at r7](https://reviewable.io/reviews/batfish/batfish/8841#-NgzObzWAjUq4cFzB4Ns:-Nh2v77VA-IhVWd0KkXi:bus6wex) ([raw file](https://github.com/batfish/batfish/blob/6c872eb399eda2218354194d16e113c1076ad977/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/Hierarchy.java#L747)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

What's happening here? I guess you had to make the change because of modifying `path._nodes` (but only appending so that `i` is useful)?
</blockquote></details>

No need for `i`, was using it in an abandoned implementation and didn't clean it up.
Refactored a bit.
___
*[`projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/JuniperListPaths.java` line 26 at r6](https://reviewable.io/reviews/batfish/batfish/8841#-Ngw9YMD7OknQFFfVSh7:-Nh2xXmoEmYkKdYWmns8:b88sj0k) ([raw file](https://github.com/batfish/batfish/blob/d9f345766f1b812a740324b22fdd748d8ba69c23/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/JuniperListPaths.java#L26)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

This is on me for being lazy in copying lines out of tests. You added the lines I intended, but also more.

Are the `match source-address-name` and `then source-nat pool` themselves lists (where order matters)?

I imagine without checking the first one can be a list where order doesn't matter, but the second one probably not. If so, sorry for being lazy and can you delete those?
</blockquote></details>

looks like source-address-name is list, but pool is not (or not obviously from docs).

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8841)* status: all files reviewed, 2 unresolved discussions (waiting on @arifogel, @sfraint, and @SLarkworthy)

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8841)* status: all files reviewed, 2 unresolved discussions (waiting on @dhalperi, @sfraint, and @SLarkworthy)

___
*[`projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/Hierarchy.java` line 91 at r7](https://reviewable.io/reviews/batfish/batfish/8841#-NgzHpqf8_JlPSWxiF3q:-Nh31jM82fB_69qRTfr-:bmwowp6) ([raw file](https://github.com/batfish/batfish/blob/6c872eb399eda2218354194d16e113c1076ad977/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/Hierarchy.java#L91)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Do all these different `inheritGroups` functions need to be `public`? Which one is the user facing API / can we simplify it?
</blockquote></details>

went through and cleaned up the class a bit more:
1. minimized visibility
2. removed unused functions
___
*[`projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/Hierarchy.java` line 187 at r7](https://reviewable.io/reviews/batfish/batfish/8841#-NgzIIvO7IFmKPhc3JH1:-Nh33-O0ECQYP7eJUsMO:bvnrpcm) ([raw file](https://github.com/batfish/batfish/blob/6c872eb399eda2218354194d16e113c1076ad977/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/Hierarchy.java#L187)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Reading it, I think this comment and name will not convey the critical point that configuration in the main tree will take effect after inherited configuration. Maybe I'd say that, and then explain that Scalars in the main tree will "win" and lists will include inherited configuration ahead of configuration from the main tree. This could be wrong (link to github issue) for lists where order matters.
</blockquote></details>

updated

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8841)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint and @SLarkworthy)

**Pull request merged**
