### PR TITLE
Crypto maps support

### PR DESCRIPTION
**Pull request by haverma**
- Adding support for extractions of crypto-maps(static and dynamic) to VI model
- Adding tests

### CODE REVIEW

**Comment by haverma** [comment]
Review status: 0 of 36 files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java, line 1639 at r1](https://reviewable.io/reviews/batfish/batfish/1634#-LEfAPMR6mFhNv-Nw9gg:-LEfAPMR6mFhNv-Nw9gh:b-pcrrzs) ([raw file](https://github.com/batfish/batfish/blob/045ce86f8052009cc917c29013fb55e47b1edb8d/projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java#L1639)):*
> ```Java
>                                 hasReferredDynamicMapSet(equalTo("mydynamicmap")))))))));
>     /* assertThat(
>     c,
> ```

I had to comment this part of asserting `sequenceNumber` as I was getting a maven build warning saying `unchecked generic array creation for varargs parameter of type Matcher<? super CryptoMapEntry>[]`. I was not able to fix that warning and so had to comment this assertion, I will uncomment/merge it in the above assertion once I figure out the reason and way to get rid of the warning. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1634)*

**Comment by haverma** [comment]
Review status: 0 of 36 files reviewed, 1 unresolved discussion (waiting on @dhalperi)

---

*[projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java, line 1639 at r1](https://reviewable.io/reviews/batfish/batfish/1634#-LEfAPMR6mFhNv-Nw9gg:-LEkMHylBspIhjke84BG:b-o7x2jw) ([raw file](https://github.com/batfish/batfish/blob/045ce86f8052009cc917c29013fb55e47b1edb8d/projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java#L1639)):*
<details><summary><i>Previously, haverma (Harsh Verma) wrote…</i></summary><blockquote>

I had to comment this part of asserting `sequenceNumber` as I was getting a maven build warning saying `unchecked generic array creation for varargs parameter of type Matcher<? super CryptoMapEntry>[]`. I was not able to fix that warning and so had to comment this assertion, I will uncomment/merge it in the above assertion once I figure out the reason and way to get rid of the warning. 
</blockquote></details>

Seems `allOf()` has this problem if it has 1 or >6 elements.  Separating out `sequenceNumbers` assertion to keep the `allOf`parameters to 6 to ensure that

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1634)*

**Comment by dhalperi** [comment]
Review status: 0 of 36 files reviewed, 2 unresolved discussions (waiting on @haverma and @dhalperi)

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1634#-LEkNacf4LnqUuDRtBn0:-LEkNacf4LnqUuDRtBn1:b6mzdw1) (no related file):*
How did you choose the datamodel class to use here?

I'm trying to see if this is the right vendor-independent structure. One way to check is to look at the Juniper and Cisco pages to see if they're using the same names... Seems like they don't, really: https://kb.juniper.net/InfoCenter/index?page=content&id=KB4147&actp=METADATA

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1634)*

**Comment by arifogel** [comment]
Review status: 0 of 36 files reviewed, 2 unresolved discussions (waiting on @arifogel, @haverma, and @dhalperi)

---

*[projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java, line 1639 at r1](https://reviewable.io/reviews/batfish/batfish/1634#-LEfAPMR6mFhNv-Nw9gg:-LEkRSVkDlJAYGhpwGOx:boncqsd) ([raw file](https://github.com/batfish/batfish/blob/045ce86f8052009cc917c29013fb55e47b1edb8d/projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java#L1639)):*
<details><summary><i>Previously, haverma (Harsh Verma) wrote…</i></summary><blockquote>

Seems `allOf()` has this problem if it has 1 or >6 elements.  Separating out `sequenceNumbers` assertion to keep the `allOf`parameters to 6 to ensure that
</blockquote></details>

You can just use a `Collection` of matchers as arg to `allOf`

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1634)*

**Comment by haverma** [comment]
Review status: 0 of 36 files reviewed, 2 unresolved discussions (waiting on @haverma, @dhalperi, and @arifogel)

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1634#-LEkNacf4LnqUuDRtBn0:-LEkUqESDSDN4hCjmR3i:bfhadcy) (no related file):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

How did you choose the datamodel class to use here?

I'm trying to see if this is the right vendor-independent structure. One way to check is to look at the Juniper and Cisco pages to see if they're using the same names... Seems like they don't, really: https://kb.juniper.net/InfoCenter/index?page=content&id=KB4147&actp=METADATA
</blockquote></details>

I have compared Cisco and Juniper constructs in this doc: https://docs.google.com/document/d/1pFuTc-iNpWIeYqn_EGv45dU-OhkkKIM_F_FFqwlS6co/edit?usp=sharing.  Crypto maps are a way to implement policy based VPNs in Cisco, Juniper has a different way to implement the same thing using security policies https://www.juniper.net/documentation/en_US/junos/topics/example/ipsec-policy-based-vpn-configuring.html. I am trying to figure out what can be a common data-model class. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1634)*

**Pull request closed without merging**
