### PR TITLE
Rib: factor out a read-only interface.

### PR DESCRIPTION
**Pull request by progwriter**
This way it is far less likely that BGP/EVPN rib (or other code) can modify the main RIB w/o going through proper channels

### CODE REVIEW

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6244)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/GenericRib.java, line 13 at r1](https://reviewable.io/reviews/batfish/batfish/6244#-MIKU0G74eqn70CcM968:-MIKU0G74eqn70CcM969:bkh2tp9) ([raw file](https://github.com/batfish/batfish/blob/5c050b3dd485a8e3a4e95a87b5163be6312096bd/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/GenericRib.java#L13)):*
> ```
> comparePreference
> ```
this is a read-only operation right? Seems to belong in the RO interface, though I understand no clients of that interface would use it.

**Review by progwriter — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6244)* status: 4 of 8 files reviewed, all discussions resolved (waiting on @anothermattbrown)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/GenericRib.java, line 13 at r1](https://reviewable.io/reviews/batfish/batfish/6244#-MIKU0G74eqn70CcM968:-MIK_ZKYDv5nDYahMPEX:b-yrfvot) ([raw file](https://github.com/batfish/batfish/blob/5c050b3dd485a8e3a4e95a87b5163be6312096bd/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/GenericRib.java#L13)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

> ```
> comparePreference
> ```
this is a read-only operation right? Seems to belong in the RO interface, though I understand no clients of that interface would use it.
</blockquote></details>

that's fair. pulled up.
Also had to pull up `containsRoute` as it became apparent that's needed.

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 2 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6244)* status: 6 of 8 files reviewed, all discussions resolved (waiting on @anothermattbrown)

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 2 of 4 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6244)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
