### PR TITLE
User-facing warning for bad ISP files

### PR DESCRIPTION
**Pull request by ratulm**
(A user and I ran into this problem within an hour of each other today.)

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7426)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel and @ratulm)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java, line 296 at r1](https://reviewable.io/reviews/batfish/batfish/7426#-MkNqm9KB4ynLCjTI4p6:-MkNqm9L8is7MdEfDKH3:b-vew7sd) ([raw file](https://github.com/batfish/batfish/blob/3bba905835f77ed37aefdd33a31fc71d33e7f873/projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java#L296)):*
> ```
> IOException
> ```
Prefer a new ISP-specific exception, rather than just passing IOException up.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7426)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel and @ratulm)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java, line 308 at r2](https://reviewable.io/reviews/batfish/batfish/7426#-MkO_h4e5GgFLkghYbgS:-MkO_h4g9vsnGIkS4xhY:b-8ia7bx) ([raw file](https://github.com/batfish/batfish/blob/28f3e0e60be24db394d39de4087d82251ab26c46/projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java#L308)):*
> ```Java
>               "Could not parse the content of %s. (Is it valid JSON? Does it have the right"
>                   + " information?)",
>               ISP_CONFIGURATION_KEY));
> ```

okay to pass `e` as cause if you want, not requierd.

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7426)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @arifogel and @dhalperi)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java, line 308 at r2](https://reviewable.io/reviews/batfish/batfish/7426#-MkO_h4e5GgFLkghYbgS:-MkOamOU8ksVIQ9EB6lU:bujnnur) ([raw file](https://github.com/batfish/batfish/blob/28f3e0e60be24db394d39de4087d82251ab26c46/projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java#L308)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

okay to pass `e` as cause if you want, not requierd.
</blockquote></details>

meant to do that (and provide more detail to the user).

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7426)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel and @dhalperi)

**Pull request merged**
