### PR TITLE
Batfish: if there are any undefined IpSpaces, create them as empty during conversion

### PR DESCRIPTION
**Pull request by dhalperi**
All undefined spaces get added to initialization issues, and this guarantees they won't
crash.

### CODE REVIEW

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 9 of 11 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7342)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java, line 159 at r1](https://reviewable.io/reviews/batfish/batfish/7342#-Mj1gkTP8t77s8A3cpe4:-Mj1gkTP8t77s8A3cpe5:bnjf5sr) ([raw file](https://github.com/batfish/batfish/blob/372fa5db029da388341fefc6819252026eef5318/projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java#L159)):*
> ```
> new CollectIpSpaceReferences(c);
> ```
If you had `collect` create the set (or immutable set builder), you could pass a consumer to the constructor here, and avoid creating and copying so many intermediate sets. All these `addAll` calls could get expensive in large spaces with lots of references.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AndMatchExpr.java, line 18 at r2](https://reviewable.io/reviews/batfish/batfish/7342#-Mj1iYBw0UJhFz_sStF1:-Mj1iYBw0UJhFz_sStF2:b-mity7i) ([raw file](https://github.com/batfish/batfish/blob/4140fa529ecdb0ffc22224204a8b279de6bb3838/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AndMatchExpr.java#L18)):*
> ```
>   public AndMatchExpr(AclLineMatchExpr... conjuncts) {
>     this(Arrays.asList(conjuncts), (TraceElement) null);
>   }
> ```
this already exists as `AclLineMatchExprs.and`
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/OrMatchExpr.java, line 18 at r2](https://reviewable.io/reviews/batfish/batfish/7342#-Mj1iUmr079LyB-GcXeA:-Mj1iUmr079LyB-GcXeB:b4suva0) ([raw file](https://github.com/batfish/batfish/blob/4140fa529ecdb0ffc22224204a8b279de6bb3838/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/OrMatchExpr.java#L18)):*
> ```
>   public OrMatchExpr(AclLineMatchExpr... disjuncts) {
>     this(Arrays.asList(disjuncts), (TraceElement) null);
>   }
> ```
this already exists as `AclLineMatchExprs.or`

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7342)* status: 7 of 11 files reviewed, all discussions resolved (waiting on @anothermattbrown)

___
*[projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java, line 159 at r1](https://reviewable.io/reviews/batfish/batfish/7342#-Mj1gkTP8t77s8A3cpe4:-Mj1pLXV72ug4DVGQqKm:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/372fa5db029da388341fefc6819252026eef5318/projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java#L159)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

> ```
> new CollectIpSpaceReferences(c);
> ```
If you had `collect` create the set (or immutable set builder), you could pass a consumer to the constructor here, and avoid creating and copying so many intermediate sets. All these `addAll` calls could get expensive in large spaces with lots of references.
</blockquote></details>

Done.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AndMatchExpr.java, line 18 at r2](https://reviewable.io/reviews/batfish/batfish/7342#-Mj1iYBw0UJhFz_sStF1:-Mj1pMRF0M5_0-zxmgex:b-v9ysgg) ([raw file](https://github.com/batfish/batfish/blob/4140fa529ecdb0ffc22224204a8b279de6bb3838/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AndMatchExpr.java#L18)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

> ```
>   public AndMatchExpr(AclLineMatchExpr... conjuncts) {
>     this(Arrays.asList(conjuncts), (TraceElement) null);
>   }
> ```
this already exists as `AclLineMatchExprs.and`
</blockquote></details>

Did not want to use a maybe-optimizing factory method, but instead I just fell back to the list version.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/OrMatchExpr.java, line 18 at r2](https://reviewable.io/reviews/batfish/batfish/7342#-Mj1iUmr079LyB-GcXeA:-Mj1pRjH4S-Cs51-vTrQ:b-v9ysgg) ([raw file](https://github.com/batfish/batfish/blob/4140fa529ecdb0ffc22224204a8b279de6bb3838/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/OrMatchExpr.java#L18)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

> ```
>   public OrMatchExpr(AclLineMatchExpr... disjuncts) {
>     this(Arrays.asList(disjuncts), (TraceElement) null);
>   }
> ```
this already exists as `AclLineMatchExprs.or`
</blockquote></details>

Did not want to use a maybe-optimizing factory method, but instead I just fell back to the list version.

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 2 of 4 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7342)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java, line 210 at r4](https://reviewable.io/reviews/batfish/batfish/7342#-Mj2I0Hf4d9MbR68szFy:-Mj2I0Hf4d9MbR68szFz:bijeh16) ([raw file](https://github.com/batfish/batfish/blob/1a76b11adcdf8c447462c8d7ba776de6f09f2660/projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java#L210)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
>     private void visitAclNamed(String name) {
>       IpAccessList acl = _c.getIpAccessLists().get(name);
>       if (acl == null) {
>         return;
>       }
>       visit(acl);
>     }
> ```
</details>

does this do anything that isn't already done in this for loop in `collect`?
```
      for (IpAccessList acl : c.getIpAccessLists().values()) {
        collector.visit(acl);
      }
```

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7342)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java, line 210 at r4](https://reviewable.io/reviews/batfish/batfish/7342#-Mj2I0Hf4d9MbR68szFy:-Mj2NVa8DA03prIH82ID:btm9064) ([raw file](https://github.com/batfish/batfish/blob/1a76b11adcdf8c447462c8d7ba776de6f09f2660/projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java#L210)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

> ```
>     private void visitAclNamed(String name) {
>       IpAccessList acl = _c.getIpAccessLists().get(name);
>       if (acl == null) {
>         return;
>       }
>       visit(acl);
>     }
> ```
does this do anything that isn't already done in this for loop in `collect`?
```
      for (IpAccessList acl : c.getIpAccessLists().values()) {
        collector.visit(acl);
      }
```
</blockquote></details>

Likely not, but I think it's worth keeping a full traversal- will make it easier to evolve to handle undefined ACLs, and more.

Even without cycles introduced by recursive ACLs, I think not redoing work is useful.

**Pull request merged**
