### PR TITLE
Cisco: a few asa parsing snippets

### PR DESCRIPTION
**Pull request by dhalperi**
@sfraint @arifogel  -- I made the currently-implemented network-object stanzas explicit in the extractor. Are there plans to finish that part off?

### CODE REVIEW

**Comment by sfraint** [comment]
@dhalperi yep, I'm working on #1428

**Comment by dhalperi** [comment]
@sfraint this PR fixes #1428 but does not fix the issue that `List<IpWildcard>` can't, AFAIK, address a named group.

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1437#-:-LD2SiSaDPRdjl0TrK9n:bcheiqr)*

**Comment by arifogel** [comment]
:lgtm:

---

Reviewed 5 of 8 files at r1, 3 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1437#-:-LD2rC5G4xUVDvyddQz8:bnfp4nl)*

**Comment by sfraint** [comment]
:lgtm:

---

Reviewed 5 of 8 files at r1, 3 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1437#-:-LD2rKLfAes3CEkg0ae1:bnfp4nl)*

**Pull request merged**
