### PR TITLE
Update SRX policy encoding and interaction

### PR DESCRIPTION
**Pull request by sfraint**
* Fixed explicit deny behavior for security policies
* Updated IpAccessList and PermittedByAcl to support different default actions
* Update global policy definition tracking

### CODE REVIEW

**Comment by sfraint** [comment]
Review status: 0 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1505#-LDNPAbF2qvb2q-E_A1n:-LDNPAbF2qvb2q-E_A1o:b-4pezqa) (no related file):*
This is what the new security policy method we discussed yesterday looks like (splitting `PermittedByAcl` into explicit deny and explicit accept).
This is not ready yet, structural unit tests related to security policies need to be updated/removed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1505)*

**Comment by anothermattbrown** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpAccessList.java, line 120 at r1](https://reviewable.io/reviews/batfish/batfish/1505#-LDhBt0l1_3SxgfeBrfm:-LDhBt0l1_3SxgfeBrfn:b45utyt) ([raw file](https://github.com/batfish/batfish/blob/5028d24e3ce6c36dab8904ce0aca51b590b65b42/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpAccessList.java#L120)):*
> ```Java
>       Map<String, IpAccessList> availableAcls,
>       Map<String, IpSpace> namedIpSpaces,
>       boolean defaultAccept) {
> ```

minor suggestion: It would seem cleaner to me to change this parameter to the default `LineAction` value.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/PermittedByAcl.java, line 15 at r1](https://reviewable.io/reviews/batfish/batfish/1505#-LDhCIo38OgZw9Buulzl:-LDhCIo38OgZw9Buulzm:b-eo2bfo) ([raw file](https://github.com/batfish/batfish/blob/5028d24e3ce6c36dab8904ce0aca51b590b65b42/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/PermittedByAcl.java#L15)):*
> ```Java
> 
>   private final String _aclName;
>   private final boolean _defaultAccept;
> ```

similar comment as above. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1505)*

**Comment by sfraint** [comment]
Review status: 0 of 8 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpAccessList.java, line 120 at r1](https://reviewable.io/reviews/batfish/batfish/1505#-LDhBt0l1_3SxgfeBrfm:-LDhHH3b32EOIgJpru_m:bohqzsr) ([raw file](https://github.com/batfish/batfish/blob/5028d24e3ce6c36dab8904ce0aca51b590b65b42/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpAccessList.java#L120)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

minor suggestion: It would seem cleaner to me to change this parameter to the default `LineAction` value.
</blockquote></details>

Agreed, done.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/PermittedByAcl.java, line 15 at r1](https://reviewable.io/reviews/batfish/batfish/1505#-LDhCIo38OgZw9Buulzl:-LDhGUfr1_uQaaPqfzZm:b-uwbgng) ([raw file](https://github.com/batfish/batfish/blob/5028d24e3ce6c36dab8904ce0aca51b590b65b42/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/PermittedByAcl.java#L15)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

similar comment as above. 
</blockquote></details>

Was going with boolean style here so serialization will default to `false` and just work if this property is missing.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1505)*

**Comment by sfraint** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java, line 1417 at r3](https://reviewable.io/reviews/batfish/batfish/1505#-LDnMTjd7mTWLhYkLa99:-LDnN22JAWZwoTAJ7EFB:bhieim7) ([raw file](https://github.com/batfish/batfish/blob/bd9f54d51f0369e99225f390decab2ba11bd9ab5/projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java#L1417)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Not being matched by outgoing ACL means ignore zone policy and accept?
</blockquote></details>

no, I shouldn't have pushed that

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1505)*

**Comment by arifogel** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java, line 1417 at r3](https://reviewable.io/reviews/batfish/batfish/1505#-LDnMTjd7mTWLhYkLa99:-LDnRDFW63M5guFgKNqE:bmv7mp2) ([raw file](https://github.com/batfish/batfish/blob/bd9f54d51f0369e99225f390decab2ba11bd9ab5/projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java#L1417)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

no, I shouldn't have pushed that
</blockquote></details>

Waiting for fix

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1505)*

**Comment by arifogel** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1505#-LDNPAbF2qvb2q-E_A1n:-LDnRO6Q071NOXoxkWYp:b-3tv2ez) (no related file):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

This is what the new security policy method we discussed yesterday looks like (splitting `PermittedByAcl` into explicit deny and explicit accept).
This is not ready yet, structural unit tests related to security policies need to be updated/removed.
</blockquote></details>

You're blocking this one FYI

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1505)*

**Comment by sfraint** [comment]
Review status: 6 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1505#-LDNPAbF2qvb2q-E_A1n:-LDnXZ4y5QMvBbI6AB8j:b3ejxx7) (no related file):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

You're blocking this one FYI
</blockquote></details>

Changes have been made, ready for review.

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java, line 1380 at r2](https://reviewable.io/reviews/batfish/batfish/1505#-LDnLmob-rzKXR58-ava:-LDnSwF9CaZUfdAkjVnJ:b-fixwf4) ([raw file](https://github.com/batfish/batfish/blob/c80559ce3f3fe8ac3fcc12d0b7e5a00959868c69/projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java#L1380)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Should `_defaultCrossZoneAction` be used if `srcInterface` is `null`? Shouldn't traffic originating from device be subject to a different default action? Or does it count as cross-zone for some zone based on `srcIp`?`
</blockquote></details>

After some testing, looks like traffic originating from the device is generally allowed (unless it fails an outgoing filter). Fixed.

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java, line 1417 at r3](https://reviewable.io/reviews/batfish/batfish/1505#-LDnMTjd7mTWLhYkLa99:-LDnXgiB7whZYGdWrEIt:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/bd9f54d51f0369e99225f390decab2ba11bd9ab5/projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java#L1417)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Waiting for fix
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1505)*

**Comment by arifogel** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1505)*

**Comment by arifogel** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1505#-:-LDnaZCKB4lcvrAgAF7Q:bnfp4nl)*

**Pull request merged**
