### PR TITLE
Definedstructures

### PR DESCRIPTION
**Pull request by ratulm**
Instead of tracking only unused structures in ConvertConfigurationAnswerElement, track all defined structures and the number of references to it. The reference counting was not standard in a few places, where -1 will be inserted for now. 

The code should automatically upgrade the old ConvertConfigurationAnswerElemement on disk for already processed snapshots.

### CODE REVIEW

**Comment by arifogel** [comment]
Looking pretty good! I think you've vastly improved our tests with this PR. I have scattered comments, but nothing major.

---

Reviewed 35 of 35 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DefinedStructureInfo.java, line 18 at r1](https://reviewable.io/reviews/batfish/batfish/1274#-LBS8nFx2O9XUZlLXkHJ:-LBS3V-33FM2LDDKqkJt:bc92zng) ([raw file](https://github.com/batfish/batfish/blob/e8070df1370ae91fbd12d0f6d7d1af05a55a69d1/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DefinedStructureInfo.java#L18)):*
> ```Java
>   private static final String PROP_NUM_REFERRERS = "numReferrers";
> 
>   private SortedSet<Integer> _definitionLines;
> ```

Why put numReferrers here but not referenceLines/usages? Do you want to record all defined references as well as all defined structures? Or is that out of scope for now?

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DefinedStructureInfo.java, line 26 at r1](https://reviewable.io/reviews/batfish/batfish/1274#-LBS3oHC5u1vogXAKA_n:-LBS3oHC5u1vogXAKA_o:b-9gadys) ([raw file](https://github.com/batfish/batfish/blob/e8070df1370ae91fbd12d0f6d7d1af05a55a69d1/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DefinedStructureInfo.java#L26)):*
> ```Java
>       @JsonProperty(PROP_NUM_REFERRERS) Integer numReferrers) {
>     _definitionLines = MoreObjects.firstNonNull(definitionLines, new TreeSet<>());
>     _numReferrers = MoreObjects.firstNonNull(numReferrers, -1);
> ```

Why not `0`? Are you confusing with `IGNORED_DEFINITION_LINE`?
If intentional, can you use a descriptive constant for `-1` here and wherever else it is used explicitly? The semantics are not clear.

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/ConvertConfigurationAnswerElementMatchers.java, line 200 at r1](https://reviewable.io/reviews/batfish/batfish/1274#-LBS5L1a7bEPfHP-DbSa:-LBS5L1a7bEPfHP-DbSb:b-sujfog) ([raw file](https://github.com/batfish/batfish/blob/e8070df1370ae91fbd12d0f6d7d1af05a55a69d1/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/ConvertConfigurationAnswerElementMatchers.java#L200)):*
> ```Java
>         mismatchDescription.appendText(
>             String.format(
>                 "On host '%s' has defined structure of type '%s' named '%s' has %d referrers",
> ```

Remove first `has`?

---

*[projects/batfish/src/main/java/org/batfish/main/BatfishStorage.java, line 114 at r1](https://reviewable.io/reviews/batfish/batfish/1274#-LBS5jQl--TWIxKLy9Wg:-LBS5jQl--TWIxKLy9Wh:b-90ymcd) ([raw file](https://github.com/batfish/batfish/blob/e8070df1370ae91fbd12d0f6d7d1af05a55a69d1/projects/batfish/src/main/java/org/batfish/main/BatfishStorage.java#L114)):*
> ```Java
>       return deserializeObject(ccaePath, ConvertConfigurationAnswerElement.class);
>     } catch (BatfishException e) {
>       _logger.errorf("Failed to deserialize ConvertConfigurationAnswerElement: %s", e);
> ```

Did you want to swallow the stacktrace from `e`? Perhaps replace `e` with `ExceptionUtils.getStackTrace(e)`?

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 3964 at r1](https://reviewable.io/reviews/batfish/batfish/1274#-LBS62ZqBM9ZmfmJQhaO:-LBS62ZqBM9ZmfmJQhaP:b8yua7h) ([raw file](https://github.com/batfish/batfish/blob/e8070df1370ae91fbd12d0f6d7d1af05a55a69d1/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L3964)):*
> ```Java
>     markSecurityZones(CiscoStructureUsage.ZONE_PAIR_SOURCE_ZONE);
> 
>     // warn about unreferenced data structures
> ```

Seems like this comment should change given code changes below

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java, line 2451 at r1](https://reviewable.io/reviews/batfish/batfish/1274#-LBS7EgN7tfr7t5qIr5P:-LBS7EgO4jGSV8zMGWfZ:b-z8n02b) ([raw file](https://github.com/batfish/batfish/blob/e8070df1370ae91fbd12d0f6d7d1af05a55a69d1/projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java#L2451)):*
> ```Java
>       String name = e.getKey();
>       PrefixList prefixList = e.getValue();
>       // if (!prefixList.getIpv6() && prefixList.isUnused() && !_ignoredPrefixLists.contains(name))
> ```

Please just delete the commented code if this is your intended behavior.

---

*[projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java, line 263 at r1](https://reviewable.io/reviews/batfish/batfish/1274#-LBS7hco7DwW8ChI22Qs:-LBS7hco7DwW8ChI22Qt:b-hhdri7) ([raw file](https://github.com/batfish/batfish/blob/e8070df1370ae91fbd12d0f6d7d1af05a55a69d1/projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java#L263)):*
> ```Java
> 
>     /*
>      * We expect only object-groups to be ogsunused1, ognunused1 to have zero referrers
> ```

Remove `to be`

---

*[projects/question/src/main/java/org/batfish/question/definedstructures/DefinedStructuresAnswerElement.java, line 84 at r1](https://reviewable.io/reviews/batfish/batfish/1274#-LBS97j8BiSXtkDF8jgW:-LBS97j8BiSXtkDF8jgX:bwm69bd) ([raw file](https://github.com/batfish/batfish/blob/e8070df1370ae91fbd12d0f6d7d1af05a55a69d1/projects/question/src/main/java/org/batfish/question/definedstructures/DefinedStructuresAnswerElement.java#L84)):*
> ```Java
>                   new TypeReference<SortedSet<Integer>>() {});
>     } catch (IOException e) {
>       // what do we here? -- change throws to IOException
> ```

Did you mean to change this? Seems like you are happy to throw an exception of type `JsonProcessingException` here, so why not just throw `IOException` in signature?

---

*[projects/question/src/main/java/org/batfish/question/definedstructures/DefinedStructuresQuestion.java, line 11 at r1](https://reviewable.io/reviews/batfish/batfish/1274#-LBS9Upv2DiuYKf1EHS2:-LBS9Upv2DiuYKf1EHS3:bgsl7m3) ([raw file](https://github.com/batfish/batfish/blob/e8070df1370ae91fbd12d0f6d7d1af05a55a69d1/projects/question/src/main/java/org/batfish/question/definedstructures/DefinedStructuresQuestion.java#L11)):*
> ```Java
>  * which nodes are fetched.
>  */
> public class DefinedStructuresQuestion extends IPacketTraceQuestion {
> ```

Why `IPacketTraceQuestion`? Code reuse? This will be confusing to maintainers. Consider either renaming `IPacketTraceQuestion`, or altering the hierarchy so they both extend from something common.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1274#-:-LBSAIYC7QU_dRIlIpxV:b-mj2qi1)*

**Comment by dhalperi** [comment]
+ @sfraint since he'll be curating the unused/undefined checks

**Comment by ratulm** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DefinedStructureInfo.java, line 18 at r1](https://reviewable.io/reviews/batfish/batfish/1274#-LBS8nFx2O9XUZlLXkHJ:-LBSuAEmDJLOw6aIkrR-:beh73wh) ([raw file](https://github.com/batfish/batfish/blob/e8070df1370ae91fbd12d0f6d7d1af05a55a69d1/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DefinedStructureInfo.java#L18)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Why put numReferrers here but not referenceLines/usages? Do you want to record all defined references as well as all defined structures? Or is that out of scope for now?
</blockquote></details>

out of scope. we can add if someone has a use case. should be easy to evolve now that there is a separate class.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DefinedStructureInfo.java, line 26 at r1](https://reviewable.io/reviews/batfish/batfish/1274#-LBS3oHC5u1vogXAKA_n:-LBSuKzm31Uj5Vu4YfuY:b-lqoaan) ([raw file](https://github.com/batfish/batfish/blob/e8070df1370ae91fbd12d0f6d7d1af05a55a69d1/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DefinedStructureInfo.java#L26)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Why not `0`? Are you confusing with `IGNORED_DEFINITION_LINE`?
If intentional, can you use a descriptive constant for `-1` here and wherever else it is used explicitly? The semantics are not clear.
</blockquote></details>

Done. 

0 is for cases where we know there are zero references. if i understand the current code correctly, references are not being correctly counted for some structures; this constant is for those cases.

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/ConvertConfigurationAnswerElementMatchers.java, line 200 at r1](https://reviewable.io/reviews/batfish/batfish/1274#-LBS5L1a7bEPfHP-DbSa:-LBSwECv0kptfR2-o9sf:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/e8070df1370ae91fbd12d0f6d7d1af05a55a69d1/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/ConvertConfigurationAnswerElementMatchers.java#L200)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Remove first `has`?
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/main/BatfishStorage.java, line 114 at r1](https://reviewable.io/reviews/batfish/batfish/1274#-LBS5jQl--TWIxKLy9Wg:-LBSwV3SBa2iHShTaQ60:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/e8070df1370ae91fbd12d0f6d7d1af05a55a69d1/projects/batfish/src/main/java/org/batfish/main/BatfishStorage.java#L114)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Did you want to swallow the stacktrace from `e`? Perhaps replace `e` with `ExceptionUtils.getStackTrace(e)`?
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 3964 at r1](https://reviewable.io/reviews/batfish/batfish/1274#-LBS62ZqBM9ZmfmJQhaO:-LBUY7lN-C45qnhnc6z8:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/e8070df1370ae91fbd12d0f6d7d1af05a55a69d1/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L3964)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Seems like this comment should change given code changes below
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java, line 2451 at r1](https://reviewable.io/reviews/batfish/batfish/1274#-LBS7EgN7tfr7t5qIr5P:-LBUYCJbDp12uQ4Jsnfd:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/e8070df1370ae91fbd12d0f6d7d1af05a55a69d1/projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java#L2451)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Please just delete the commented code if this is your intended behavior.
</blockquote></details>

Done.

---

*[projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java, line 263 at r1](https://reviewable.io/reviews/batfish/batfish/1274#-LBS7hco7DwW8ChI22Qs:-LBUYDW9CQm-03zb6LFR:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/e8070df1370ae91fbd12d0f6d7d1af05a55a69d1/projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java#L263)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Remove `to be`
</blockquote></details>

Done.

---

*[projects/question/src/main/java/org/batfish/question/definedstructures/DefinedStructuresAnswerElement.java, line 84 at r1](https://reviewable.io/reviews/batfish/batfish/1274#-LBS97j8BiSXtkDF8jgW:-LBUYFsH4rscBYCcgWHJ:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/e8070df1370ae91fbd12d0f6d7d1af05a55a69d1/projects/question/src/main/java/org/batfish/question/definedstructures/DefinedStructuresAnswerElement.java#L84)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Did you mean to change this? Seems like you are happy to throw an exception of type `JsonProcessingException` here, so why not just throw `IOException` in signature?
</blockquote></details>

Done.

---

*[projects/question/src/main/java/org/batfish/question/definedstructures/DefinedStructuresQuestion.java, line 11 at r1](https://reviewable.io/reviews/batfish/batfish/1274#-LBS9Upv2DiuYKf1EHS2:-LBUYHAS-lm3lhRoepGZ:b-2jsvxj) ([raw file](https://github.com/batfish/batfish/blob/e8070df1370ae91fbd12d0f6d7d1af05a55a69d1/projects/question/src/main/java/org/batfish/question/definedstructures/DefinedStructuresQuestion.java#L11)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Why `IPacketTraceQuestion`? Code reuse? This will be confusing to maintainers. Consider either renaming `IPacketTraceQuestion`, or altering the hierarchy so they both extend from something common.
</blockquote></details>

cut-n-paste oversight. fixed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1274)*

**Comment by sfraint** [comment]
Reviewed 1 of 9 files at r2.
Review status: 28 of 36 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/ConvertConfigurationAnswerElement.java, line 156 at r1](https://reviewable.io/reviews/batfish/batfish/1274#-LBWi65s1z0TRMaovz9n:-LBWi65s1z0TRMaovz9o:b9ijtam) ([raw file](https://github.com/batfish/batfish/blob/e8070df1370ae91fbd12d0f6d7d1af05a55a69d1/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/ConvertConfigurationAnswerElement.java#L156)):*
> ```Java
>     _definedStructures.forEach(
>         (hostname, byType) -> {
>           sb.append("\n  " + hostname + "[Unused structures]\n");
> ```

I think this should be updated (unused -> defined).

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java, line 2201 at r2](https://reviewable.io/reviews/batfish/batfish/1274#-LBWjJ80CvoeU8JpZCnq:-LBWjJ80CvoeU8JpZCnr:b-p06g3) ([raw file](https://github.com/batfish/batfish/blob/cc7cff2b038ef4dc10c189897d1c2a17ead3ef0c/projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java#L2201)):*
> ```Java
>         JuniperStructureType.FIREWALL_FILTER, JuniperStructureUsage.INTERFACE_FILTER, _filters);
> 
>     // warn about unreferenced data structures
> ```

I would update this comment too, since we're looking at defined instead of unreferenced structures now.

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java, line 2204 at r2](https://reviewable.io/reviews/batfish/batfish/1274#-LBWio4M3kyNwXyBYdIb:-LBWio4M3kyNwXyBYdIc:bzc5ap) ([raw file](https://github.com/batfish/batfish/blob/cc7cff2b038ef4dc10c189897d1c2a17ead3ef0c/projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java#L2204)):*
> ```Java
>     recordStructure(_applications, JuniperStructureType.APPLICATION);
>     recordStructure(_applicationSets, JuniperStructureType.APPLICATION_SET);
>     warnUnreferencedAuthenticationKeyChains();
> ```

Maybe rename these `warnUnref...` to `record...` like in `CiscoConfiguration.java`

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1274)*

**Pull request merged**
