### PR TITLE
Add VI VRRP priority tracking

### PR DESCRIPTION
**Pull request by arifogel**
- factor out common bits of HSRP tracking

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7998)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel and @corinaminer)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/PriorityEvaluator.java, line 4 at r2](https://reviewable.io/reviews/batfish/batfish/7998#-MuwAOv46N2M1Yv4cKS5:-MuwAOv51qPSJPjDs92T:b-tngij0) ([raw file](https://github.com/batfish/batfish/blob/d7ea2ded504a9abed73fbd1867a80909e0ec8f08/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/PriorityEvaluator.java#L4)):*
> ```Java
> 
> /**
>  * Evaluates the action of a {@link TrackAction} on a given HSRP {@code priority}. Visiting an
> ```

HSRP/VRRP/



_Code quote:_
```Java
HSRP 
```

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7998)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel and @corinaminer)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/PriorityEvaluator.java, line 4 at r2](https://reviewable.io/reviews/batfish/batfish/7998#-MuwAOv46N2M1Yv4cKS5:-MuwAYau3KyhtUx85R89:b-wdy646) ([raw file](https://github.com/batfish/batfish/blob/d7ea2ded504a9abed73fbd1867a80909e0ec8f08/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/PriorityEvaluator.java#L4)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

HSRP/VRRP/
</blockquote></details>

(nit, at discretion)

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7998)* status: all files reviewed, 1 unresolved discussion (waiting on @corinaminer and @dhalperi)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/PriorityEvaluator.java, line 4 at r2](https://reviewable.io/reviews/batfish/batfish/7998#-MuwAOv46N2M1Yv4cKS5:-MuwEPIA0-ZEErCba3DY:b-7ql1td) ([raw file](https://github.com/batfish/batfish/blob/d7ea2ded504a9abed73fbd1867a80909e0ec8f08/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/PriorityEvaluator.java#L4)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

(nit, at discretion)
</blockquote></details>

fixed

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7998)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7998)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

**Pull request merged**
