### PR TITLE
TransferBDD: Support formats that use output attributes

### PR DESCRIPTION
**Pull request by millstein**
Updates the symbolic route analysis to properly handle configuration formats that use output attributes for matching, rather than the attributes of the original route.

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7159)* status: all files reviewed, 1 unresolved discussion (waiting on @millstein)

___
*[projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java, line 672 at r1](https://reviewable.io/reviews/batfish/batfish/7159#-MeWzFtHCEWggP56Zobb:-MeWzFtHCEWggP56Zobc:bu8bwx4) ([raw file](https://github.com/batfish/batfish/blob/197dbe00481ea20919accaf9dc601d785525a8b0/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java#L672)):*
> ```Java
>           sc.getCommunitySetExpr();
>       CommunityAPDispositions dispositions =
>           setExpr.accept(new SetCommunitiesVisitor(), new Arg(this, _originalRoute));
> ```

Why doesn't this use `routeForMaching`?

**Review by millstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7159)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel)

___
*[projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java, line 672 at r1](https://reviewable.io/reviews/batfish/batfish/7159#-MeWzFtHCEWggP56Zobb:-MeX0OfB3W1e68Ja0IMh:b-atrd59) ([raw file](https://github.com/batfish/batfish/blob/197dbe00481ea20919accaf9dc601d785525a8b0/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java#L672)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Why doesn't this use `routeForMaching`?
</blockquote></details>

In this PR I added a comment about this at the top of the SetCommunitiesVisitor class, but I can put one here too.  In this situation the route is just being used to obtain the atomic predicates associated with each community regex (indirectly via a BDD, since we already have visitors that convert things to BDDs), so it needs to be a "fresh" route rather than the current one.  When we actually do the updates via the updateCommunities() function called below, we use the current route.

Separately, I do have a semantic question about how the actual update should work.  Consider an IOS route policy that does "set 30:40" followed by "add 40:40".  This becomes in our VI model (roughly) SetCommunities(30:40) followed by SetCommunities(InputCommunities U 40:40).  In my modeling we always consider InputCommunities to be the current route in this scenario, so we end up with both communities 30:40 and 40:40.  But SetCommunities::execute will treat InputCommunities as the original route and hence end up with just 40:40.  Which is correct?

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7159)* status: all files reviewed, 1 unresolved discussion (waiting on @millstein)

___
*[projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java, line 672 at r1](https://reviewable.io/reviews/batfish/batfish/7159#-MeWzFtHCEWggP56Zobb:-MeX2dsJ46B_g1MsbxnW:bvcoj9k) ([raw file](https://github.com/batfish/batfish/blob/197dbe00481ea20919accaf9dc601d785525a8b0/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java#L672)):*
<details><summary><i>Previously, millstein (Todd Millstein) wrote…</i></summary><blockquote>

In this PR I added a comment about this at the top of the SetCommunitiesVisitor class, but I can put one here too.  In this situation the route is just being used to obtain the atomic predicates associated with each community regex (indirectly via a BDD, since we already have visitors that convert things to BDDs), so it needs to be a "fresh" route rather than the current one.  When we actually do the updates via the updateCommunities() function called below, we use the current route.

Separately, I do have a semantic question about how the actual update should work.  Consider an IOS route policy that does "set 30:40" followed by "add 40:40".  This becomes in our VI model (roughly) SetCommunities(30:40) followed by SetCommunities(InputCommunities U 40:40).  In my modeling we always consider InputCommunities to be the current route in this scenario, so we end up with both communities 30:40 and 40:40.  But SetCommunities::execute will treat InputCommunities as the original route and hence end up with just 40:40.  Which is correct?
</blockquote></details>

I think each device has its own semantics for this.
A set followed by an add is dumb. An operator should just use a set.
IIRC some devices actually only allow either add or set, and may replace the other.
But a delete may be followed by an add or a set. So the problem remains.

**Review by millstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7159)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @arifogel)

___
*[projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java, line 672 at r1](https://reviewable.io/reviews/batfish/batfish/7159#-MeWzFtHCEWggP56Zobb:-MeX6ecZArIOWE3CNggE:b2041vi) ([raw file](https://github.com/batfish/batfish/blob/197dbe00481ea20919accaf9dc601d785525a8b0/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java#L672)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

I think each device has its own semantics for this.
A set followed by an add is dumb. An operator should just use a set.
IIRC some devices actually only allow either add or set, and may replace the other.
But a delete may be followed by an add or a set. So the problem remains.
</blockquote></details>

Ok, thanks.  Regarding your original question, I added a comment here.

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7159)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @millstein)

**Pull request merged**
