### PR TITLE
Proper handling of OSPF stub and not-so-stubby areas

### PR DESCRIPTION
**Pull request by arifogel**
- Cisco implementation
- Juniper implementation

### CODE REVIEW

**Comment by arifogel** [comment]
Requesting review by BOTH @dhalperi  and @progwriter, but especially @progwriter.

---

Review status: 0 of 40 files reviewed, all discussions resolved (waiting on @progwriter and @dhalperi)

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1648#-:-LEqgkJg8H6-sE-rPgcY:b-y9hdki)*

**Comment by progwriter** [comment]
:lgtm: only some small nits

---

Reviewed 40 of 40 files at r1.
Review status: all files reviewed, 4 unresolved discussions (waiting on @arifogel and @dhalperi)

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/NssaSettings.java, line 10 at r1](https://reviewable.io/reviews/batfish/batfish/1648#-LEqqTlG9-XKocJ3_KL3:-LEqqTlG9-XKocJ3_KL4:b-146e1m) ([raw file](https://github.com/batfish/batfish/blob/c9b58c33e4db019da8b4a778fc576913c3b09733/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/NssaSettings.java#L10)):*
> ```Java
> import javax.annotation.Nonnull;
> 
> public class NssaSettings implements Serializable {
> ```

Javadoc please (same for StubSettings).

---

*[projects/batfish/src/main/java/org/batfish/dataplane/protocols/OspfProtocolHelper.java, line 12 at r1](https://reviewable.io/reviews/batfish/batfish/1648#-LEuUXA90fnnz7hUvfhx:-LEuUXA90fnnz7hUvfhy:b9nveyd) ([raw file](https://github.com/batfish/batfish/blob/c9b58c33e4db019da8b4a778fc576913c3b09733/projects/batfish/src/main/java/org/batfish/dataplane/protocols/OspfProtocolHelper.java#L12)):*
> ```Java
> import org.batfish.datamodel.StubType;
> import org.batfish.dataplane.ibdp.Node;
> import org.batfish.dataplane.ibdp.VirtualRouter;
> ```

My original intent with creating helpers was that they would not depend on any specific engine classes and only on datamodel classes. Seems like in this case VirtualRouter is only used to get OspfProcess so we can refactor to pass that into appropriate functions instead.

---

*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 6455 at r1](https://reviewable.io/reviews/batfish/batfish/1648#-LEuQCC3--eEPOxzFEtj:-LEuQCC3--eEPOxzFEtk:bwnxl23) ([raw file](https://github.com/batfish/batfish/blob/c9b58c33e4db019da8b4a778fc576913c3b09733/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L6455)):*
> ```Java
>     OspfProcess proc = _currentOspfProcess;
>     long area = (ctx.area_int != null) ? toLong(ctx.area_int) : toIp(ctx.area_ip).asLong();
>     NssaSettings settings = proc.getNssas().computeIfAbsent(area, a -> new NssaSettings());
> ```

nit: `NssaSettings::new` ?

---

*[projects/batfish/src/test/java/org/batfish/dataplane/ibdp/OspfTest.java, line 317 at r1](https://reviewable.io/reviews/batfish/batfish/1648#-LEuSCzt3FnAOYh3wt7y:-LEuSCzt3FnAOYh3wt7z:bgqkddz) ([raw file](https://github.com/batfish/batfish/blob/c9b58c33e4db019da8b4a778fc576913c3b09733/projects/batfish/src/test/java/org/batfish/dataplane/ibdp/OspfTest.java#L317)):*
> ```
>  &#8592;
> ```
Maybe just ascii arrows instead of unicode?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1648#-:-LEuVNKD9cRj15lbjj_d:bwzkqai)*

**Comment by arifogel** [comment]
Review status: all files reviewed, 4 unresolved discussions (waiting on @arifogel and @dhalperi)

---

*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 6455 at r1](https://reviewable.io/reviews/batfish/batfish/1648#-LEuQCC3--eEPOxzFEtj:-LEu_iM26HxcOdftrOo9:b-yo3raa) ([raw file](https://github.com/batfish/batfish/blob/c9b58c33e4db019da8b4a778fc576913c3b09733/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L6455)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

nit: `NssaSettings::new` ?
</blockquote></details>

That won't work because `NssaSettings::new` is not a `Function<Long,NssaSettings>`. It is a `Supplier<NssaSettings>`

---

*[projects/batfish/src/test/java/org/batfish/dataplane/ibdp/OspfTest.java, line 317 at r1](https://reviewable.io/reviews/batfish/batfish/1648#-LEuSCzt3FnAOYh3wt7y:-LEu_ulGEVvtgufElLG9:byjojnn) ([raw file](https://github.com/batfish/batfish/blob/c9b58c33e4db019da8b4a778fc576913c3b09733/projects/batfish/src/test/java/org/batfish/dataplane/ibdp/OspfTest.java#L317)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

> ```
>  &#8592;
> ```
Maybe just ascii arrows instead of unicode?
</blockquote></details>

`<` and `>` do not render in javadoc, as they are treated as tags.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1648)*

**Comment by arifogel** [comment]
Review status: 36 of 40 files reviewed, 2 unresolved discussions (waiting on @progwriter and @dhalperi)

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/NssaSettings.java, line 10 at r1](https://reviewable.io/reviews/batfish/batfish/1648#-LEqqTlG9-XKocJ3_KL3:-LEud6n82Oi_hTqzZbw-:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/c9b58c33e4db019da8b4a778fc576913c3b09733/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/NssaSettings.java#L10)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

Javadoc please (same for StubSettings).
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/dataplane/protocols/OspfProtocolHelper.java, line 12 at r1](https://reviewable.io/reviews/batfish/batfish/1648#-LEuUXA90fnnz7hUvfhx:-LEuryIz178EIRYIAo1w:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/c9b58c33e4db019da8b4a778fc576913c3b09733/projects/batfish/src/main/java/org/batfish/dataplane/protocols/OspfProtocolHelper.java#L12)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

My original intent with creating helpers was that they would not depend on any specific engine classes and only on datamodel classes. Seems like in this case VirtualRouter is only used to get OspfProcess so we can refactor to pass that into appropriate functions instead.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1648)*

**Comment by progwriter** [comment]
Reviewed 4 of 4 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dhalperi)

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1648)*

**Comment by progwriter** [comment]
Reviewed 4 of 4 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dhalperi)

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1648)*

**Comment by dhalperi** [comment]
:lgtm:, minor comments

---

Reviewed 14 of 40 files at r1, 4 of 4 files at r2.
Review status: all files reviewed, 5 unresolved discussions (waiting on @arifogel)

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/NssaSettings.java, line 31 at r3](https://reviewable.io/reviews/batfish/batfish/1648#-LEw6JkZ4MGKbz16uhZ8:-LEw6JkZ4MGKbz16uhZ9:bbsqqmd) ([raw file](https://github.com/batfish/batfish/blob/43c21e69a1ae6654977975ce06d911177e92455a/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/NssaSettings.java#L31)):*
> ```Java
>       _suppressType3 = suppressType3;
>       return this;
>     }
> ```

private constructor, so folks always go through super.builder()?

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfProcess.java, line 318 at r3](https://reviewable.io/reviews/batfish/batfish/1648#-LEw6pv693ySR1PC3AOV:-LEw6pv693ySR1PC3AOW:b-wkz6z5) ([raw file](https://github.com/batfish/batfish/blob/43c21e69a1ae6654977975ce06d911177e92455a/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfProcess.java#L318)):*
> ```Java
>     Set<Long> areas = _areas.keySet();
>     return areas.contains(0L) && areas.stream().anyMatch(area -> area != 0L);
>   }
> ```

up to you, second half could probably be simplified to `areas.size() > 1`. (and likely, size check is faster than contains so could swap if desired).

Either way, probably deserves a comment.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/StubSettings.java, line 1 at r3](https://reviewable.io/reviews/batfish/batfish/1648#-LEw7Di_27yy3XJw1xes:-LEw7Di_27yy3XJw1xet:b-o6pwye) ([raw file](https://github.com/batfish/batfish/blob/43c21e69a1ae6654977975ce06d911177e92455a/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/StubSettings.java#L1)):*
> ```Java
> package org.batfish.datamodel;
> ```

no strong opinion, here, just asking: is it worth adding a `datamodel.ospf` package and migrating there?

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/StubSettings.java, line 22 at r3](https://reviewable.io/reviews/batfish/batfish/1648#-LEw75NV6VcC6Y1ixugv:-LEw75NV6VcC6Y1ixugw:b-w12hfc) ([raw file](https://github.com/batfish/batfish/blob/43c21e69a1ae6654977975ce06d911177e92455a/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/StubSettings.java#L22)):*
> ```Java
>       return this;
>     }
>   }
> ```

private constructor? (same comment as before)

---

*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java, line 1828 at r3](https://reviewable.io/reviews/batfish/batfish/1648#-LEw7gp03Pmy40uKLkM-:-LEw7gp03Pmy40uKLkM0:b7q28ic) ([raw file](https://github.com/batfish/batfish/blob/43c21e69a1ae6654977975ce06d911177e92455a/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java#L1828)):*
> ```Java
>       Interface neighborInterface,
>       int adminCost,
>       Long linkAreaNum) {
> ```

`@Nullable Long` or `long`?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1648#-:-LEw8EE75gocedTRPIQS:b-kl4b7g)*

**Comment by arifogel** [comment]
Review status: 15 of 80 files reviewed, 1 unresolved discussion (waiting on @dhalperi, @progwriter, and @arifogel)

---

*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java, line 1828 at r3](https://reviewable.io/reviews/batfish/batfish/1648#-LEw7gp03Pmy40uKLkM-:-LEwR-JM0H9qL4G6i8dX:bb7k6ip) ([raw file](https://github.com/batfish/batfish/blob/43c21e69a1ae6654977975ce06d911177e92455a/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java#L1828)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

`@Nullable Long` or `long`?
</blockquote></details>

long

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfProcess.java, line 318 at r3](https://reviewable.io/reviews/batfish/batfish/1648#-LEw6pv693ySR1PC3AOV:-LEwPF5J96Y5HFB3wuG_:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/43c21e69a1ae6654977975ce06d911177e92455a/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfProcess.java#L318)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

up to you, second half could probably be simplified to `areas.size() > 1`. (and likely, size check is faster than contains so could swap if desired).

Either way, probably deserves a comment.
</blockquote></details>

done

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/NssaSettings.java, line 31 at r3](https://reviewable.io/reviews/batfish/batfish/1648#-LEw6JkZ4MGKbz16uhZ8:-LEwQk9y9z0FnH6Qxpap:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/43c21e69a1ae6654977975ce06d911177e92455a/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/NssaSettings.java#L31)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

private constructor, so folks always go through super.builder()?
</blockquote></details>

done

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/StubSettings.java, line 1 at r3](https://reviewable.io/reviews/batfish/batfish/1648#-LEw7Di_27yy3XJw1xes:-LEwQIDv1c5xN7T4inCd:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/43c21e69a1ae6654977975ce06d911177e92455a/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/StubSettings.java#L1)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

no strong opinion, here, just asking: is it worth adding a `datamodel.ospf` package and migrating there?
</blockquote></details>

done

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/StubSettings.java, line 22 at r3](https://reviewable.io/reviews/batfish/batfish/1648#-LEw75NV6VcC6Y1ixugv:-LEwQlHq0htf4Pm8-MUo:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/43c21e69a1ae6654977975ce06d911177e92455a/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/StubSettings.java#L22)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

private constructor? (same comment as before)
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1648)*

**Comment by dhalperi** [comment]
Reviewed 60 of 65 files at r4, 5 of 5 files at r5.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1648)*

**Pull request merged**
