### PR TITLE
Transitions.or: merge Transforms when possible

### PR DESCRIPTION
**Pull request by anothermattbrown**
Transitions.or is a smart factory method that simplifies/optimizes the input set of disjuncts. Add a case for the Transform transitions, merging any that transform the same set of variables.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 3 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8258)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @anothermattbrown and @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transform.java, line 137 at r2](https://reviewable.io/reviews/batfish/batfish/8258#-N0NFglQ6VACG9Kf-EjT:-N0NFglQ6VACG9Kf-EjU:bzofbc) ([raw file](https://github.com/batfish/batfish/blob/c54ebbe51c3fae8a826f77db220bd00bacd24ceb/projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transform.java#L137)):*
> ```Java
>         && _vars.equals(transform._vars)
>         && Objects.equals(_reverseRelation, transform._reverseRelation)
>         && Objects.equals(_swapPairing, transform._swapPairing);
> ```

This seems wrong -- these things are dynamic so equal transforms might not have them both initialized?

(same for hashCode)



_Code quote:_
```Java
        && Objects.equals(_reverseRelation, transform._reverseRelation)
        && Objects.equals(_swapPairing, transform._swapPairing);
```
___
*[projects/batfish/src/test/java/org/batfish/bddreachability/transition/TransformTest.java, line 206 at r2](https://reviewable.io/reviews/batfish/batfish/8258#-N0NFs7-EFlP0YwbbnI6:-N0NFs7-EFlP0YwbbnI7:by7m2ce) ([raw file](https://github.com/batfish/batfish/blob/c54ebbe51c3fae8a826f77db220bd00bacd24ceb/projects/batfish/src/test/java/org/batfish/bddreachability/transition/TransformTest.java#L206)):*
> ```Java
>   }
> 
>   @Test
> ```

Missing equalsTest.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPairingFactory.java, line 70 at r2](https://reviewable.io/reviews/batfish/batfish/8258#-N0NG7TR1wW691ktx6xL:-N0NG7TR1wW691ktx6xM:b7osaku) ([raw file](https://github.com/batfish/batfish/blob/c54ebbe51c3fae8a826f77db220bd00bacd24ceb/projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPairingFactory.java#L70)):*
> ```Java
>     return Arrays.hashCode(_domain)
>         + 31 * Arrays.hashCode(_codomain)
>         + 31 * 31 * _domainVars.hashCode();
> ```

it it's worth inlining, is it worth memoizing?



_Code quote:_
```Java
  public int hashCode() {
    return Arrays.hashCode(_domain)
        + 31 * Arrays.hashCode(_codomain)
        + 31 * 31 * _domainVars.hashCode();
```

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8258)* status: all files reviewed, 3 unresolved discussions (waiting on @anothermattbrown)

**Review by anothermattbrown — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8258)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[`projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transform.java` line 137 at r2](https://reviewable.io/reviews/batfish/batfish/8258#-N0NFglQ6VACG9Kf-EjT:-N0kxcw4-5ymtFqqKknW:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/c54ebbe51c3fae8a826f77db220bd00bacd24ceb/projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transform.java#L137)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

This seems wrong -- these things are dynamic so equal transforms might not have them both initialized?

(same for hashCode)
</blockquote></details>

done
___
*[`projects/batfish/src/test/java/org/batfish/bddreachability/transition/TransformTest.java` line 206 at r2](https://reviewable.io/reviews/batfish/batfish/8258#-N0NFs7-EFlP0YwbbnI6:-N0kzOug1_Hcgfp2ClHG:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/c54ebbe51c3fae8a826f77db220bd00bacd24ceb/projects/batfish/src/test/java/org/batfish/bddreachability/transition/TransformTest.java#L206)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Missing equalsTest.
</blockquote></details>

done
___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPairingFactory.java` line 70 at r2](https://reviewable.io/reviews/batfish/batfish/8258#-N0NG7TR1wW691ktx6xL:-N0kzQMp6CVurC0psmZI:b6szgun) ([raw file](https://github.com/batfish/batfish/blob/c54ebbe51c3fae8a826f77db220bd00bacd24ceb/projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPairingFactory.java#L70)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

it it's worth inlining, is it worth memoizing?
</blockquote></details>

I don't think it's worth memoizing. un-inlined.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8258)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown)

**Pull request merged**
