### PR TITLE
Configuration: finalize more maps and sets

### PR DESCRIPTION
**Pull request by dhalperi**

### CODE REVIEW

**Review by progwriter — COMMENTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6283)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/communities/CommunityMatchExprEvaluator.java, line 68 at r1](https://reviewable.io/reviews/batfish/batfish/6283#-MIz5HKiDPM_AeiyjtgE:-MIz5HKiDPM_AeiyjtgF:b-vpsuoa) ([raw file](https://github.com/batfish/batfish/blob/5cfb195dfd11828bbf94ac1a3964178896968624/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/communities/CommunityMatchExprEvaluator.java#L68)):*
> ```Java
>   public @Nonnull Boolean visitCommunityMatchAll(
>       CommunityMatchAll communityMatchAll, Community arg) {
>     for (CommunityMatchExpr expr : communityMatchAll.getExprs()) {
> ```

presumably not relevant to this pr? some perf optimization?

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6283)* status: 5 of 6 files reviewed, all discussions resolved

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/communities/CommunityMatchExprEvaluator.java, line 68 at r1](https://reviewable.io/reviews/batfish/batfish/6283#-MIz5HKiDPM_AeiyjtgE:-MIzA0mk-7B8hj4n_Rc7:bwvyox4) ([raw file](https://github.com/batfish/batfish/blob/5cfb195dfd11828bbf94ac1a3964178896968624/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/communities/CommunityMatchExprEvaluator.java#L68)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

presumably not relevant to this pr? some perf optimization?
</blockquote></details>

Reverted

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6283)* status: 5 of 6 files reviewed, all discussions resolved

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6283)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
