### PR TITLE
TransferReturn: improve readability

### PR DESCRIPTION
**Pull request by dhalperi**
1. Add fields and named getters, get rid of Tuple
2. Inline a few non-obvious defaults especially if used in only one place.
3. Improve comments mildly.

---

**Stack**:
- #9096
- #9095
- #9094
- #9093
- #9092 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/9092)* status: 0 of 8 files reviewed, all discussions resolved

___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferReturn.java` line 36 at r1](https://reviewable.io/reviews/batfish/batfish/9092#-O0lsEsuEuph6Byu4a3w:-O0lsEsuEuph6Byu4a3x:beglm6b) ([raw file](https://github.com/batfish/batfish/blob/d336ceeb1e0ad1f0460cfd611ed1f461aca70062/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferReturn.java#L36)):*
> ```Java
>   }
> 
>   public @Nonnull BDDRoute getOutputRoute() {
> ```

@millstein @nickgian -- welcome better names for these two fields if you have preferences.

**Review by millstein — COMMENTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/9092)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi and @nickgian)

___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferReturn.java` line 30 at r1](https://reviewable.io/reviews/batfish/batfish/9092#-O0pJEepEpu5aXTGycGb:-O0pJEepEpu5aXTGycGc:b-hz9r7v) ([raw file](https://github.com/batfish/batfish/blob/f8984701d70364372ee21980aeb9c651c0e933c6/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferReturn.java#L30)):*
> ```Java
>   private final boolean _accepted;
> 
>   TransferReturn(BDDRoute r, BDD b, boolean accepted) {
> ```

Label r and b as Nonnull or use the ParametersNonnullByDefault annotation on the class?
___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferReturn.java` line 36 at r1](https://reviewable.io/reviews/batfish/batfish/9092#-O0lsEsuEuph6Byu4a3w:-O0pJRXBDL8_Kq3g35LH:baohqlr) ([raw file](https://github.com/batfish/batfish/blob/f8984701d70364372ee21980aeb9c651c0e933c6/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferReturn.java#L36)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

@millstein @nickgian -- welcome better names for these two fields if you have preferences.
</blockquote></details>

I like OutputRoute.  In symbolic execution terminology the "input BDD" is called a "path condition" -- the condition that takes you down this particular execution path.  But maybe that's confusing.  An alternative would be something like "inputConstraint" so that it's more descriptive, since "BDD" is too implementation-specific (we could swap out BDDs for any other representation of a predicate)

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/9092)* status: 1 of 8 files reviewed, 1 unresolved discussion (waiting on @millstein and @nickgian)

___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferReturn.java` line 30 at r1](https://reviewable.io/reviews/batfish/batfish/9092#-O0pJEepEpu5aXTGycGb:-O0pNi2PBJgFLA3oQ4kj:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/f8984701d70364372ee21980aeb9c651c0e933c6/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferReturn.java#L30)):*
<details><summary><i>Previously, millstein (Todd Millstein) wrote…</i></summary><blockquote>

Label r and b as Nonnull or use the ParametersNonnullByDefault annotation on the class?
</blockquote></details>

Done.
___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferReturn.java` line 36 at r1](https://reviewable.io/reviews/batfish/batfish/9092#-O0lsEsuEuph6Byu4a3w:-O0pNj9mCKu8Ye4UtoL-:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/f8984701d70364372ee21980aeb9c651c0e933c6/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferReturn.java#L36)):*
<details><summary><i>Previously, millstein (Todd Millstein) wrote…</i></summary><blockquote>

I like OutputRoute.  In symbolic execution terminology the "input BDD" is called a "path condition" -- the condition that takes you down this particular execution path.  But maybe that's confusing.  An alternative would be something like "inputConstraint" so that it's more descriptive, since "BDD" is too implementation-specific (we could swap out BDDs for any other representation of a predicate)
</blockquote></details>

Done.

**Review by millstein — COMMENTED** [review]
:lgtm:

> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/9092#-:-O0puIIU9UUuJGROiMsQ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nickgian)

**Pull request merged**
