### PR TITLE
ip as-path access list reference tracking

### PR DESCRIPTION
**Pull request by vasu018**
For Cisco ip as-path access list reference tracking: Added referenceStructure along with the markConcreteStructures in the code, updated the DefinedStructure -> ComparableStructure and the definition Line calculation.

### CODE REVIEW

**Comment by dhalperi** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 1879 at r1](https://reviewable.io/reviews/batfish/batfish/1577#-LEBAi7S89yMR6v-uABS:-LEBAi7T2z3f9PHV4jPo:buoohmb) ([raw file](https://github.com/batfish/batfish/blob/20ca1cad2d004c0b5956bfc515ff381bff20de87/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L1879)):*
> ```
> n -> new IpAsPathAccessList(n)
> ```

`IpAsPathAccessList::new`

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1577#-:-LEBAn9--4LeJ5VPowYo:bnfp4nl)*

**Comment by dhalperi** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1577#-LECHvoQE_Zz4p6KgM0P:-LECHvoR5JDVXYDOQKFr:b7j10jh) (no related file):*
Please fix name of PR from "ip access list reference checking". Two very minor conceptual bugs:

1. This is `ip as-path access-list`, not `ip access-list`. So the name talks about the wrong concept.
2. This isn't "reference checking", it's "reference tracking".

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1577)*

**Comment by vasu018** [comment]
*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 1879 at r1](https://reviewable.io/reviews/batfish/batfish/1577#-LEBAi7S89yMR6v-uABS:-LECOtwQ341TomhuS8qv:bt2vr1b) ([raw file](https://github.com/batfish/batfish/blob/20ca1cad2d004c0b5956bfc515ff381bff20de87/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L1879)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> n -> new IpAsPathAccessList(n)
> ```

`IpAsPathAccessList::new`
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1577)*

**Comment by dhalperi** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1577#-LECQ-4mEufaxWK3P5fn:-LECQ-4mEufaxWK3P5fo:b-2n6n08) (no related file):*
Based on the coverage report, looks like this codepath is not used.

Please work with @sfraint or @haverma to add a unit test of it, and confirm that refs are correctly tracked.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1577)*

**Comment by vasu018** [comment]
*[a discussion](https://reviewable.io/reviews/batfish/batfish/1577#-LECHvoQE_Zz4p6KgM0P:-LECc0JH5YM9b_O_YgNv:b4awmlb) (no related file):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Please fix name of PR from "ip access list reference checking". Two very minor conceptual bugs:

1. This is `ip as-path access-list`, not `ip access-list`. So the name talks about the wrong concept.
2. This isn't "reference checking", it's "reference tracking".
</blockquote></details>

Taken care.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1577)*

**Comment by vasu018** [comment]
*[a discussion](https://reviewable.io/reviews/batfish/batfish/1577#-LECQ-4mEufaxWK3P5fn:-LEMm6BV0QkZT8mvFPpN:bx2z545) (no related file):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Based on the coverage report, looks like this codepath is not used.

Please work with @sfraint or @haverma to add a unit test of it, and confirm that refs are correctly tracked.
</blockquote></details>

Added Unit test.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1577)*

**Comment by dhalperi** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoStructureUsage.java, line 20 at r4](https://reviewable.io/reviews/batfish/batfish/1577#-LEMqrzK1SCXg56ub_ym:-LEMqojv--YMWoyuu64A:b40a2br) ([raw file](https://github.com/batfish/batfish/blob/8556a708660dd4f04dcf52382b346e9d40227df3/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoStructureUsage.java#L20)):*
> ```Java
>   BGP_NEIGHBOR_REMOTE_AS_ROUTE_MAP("bgp neighbor remote-as route-map"),
>   // TODO: Client Configuration to be supported for bgp neighbor as-path access-list
>   // BGP_NEIGHBOR_FILTER_AS_PATH_ACCESS_LIST("bgp neighbor filter-list access-list"),
> ```

Good catch!

Looks like we actually already have (at last part of) the grammar for this usage. On a sample network, here's a parse tree that is produced:

```
      (router_bgp_stanza_tail
        (neighbor_flat_rb_stanza
          NEIGHBOR:'neighbor'  <== mode:DEFAULT_MODE
          ip = IP_ADDRESS:'1.2.3.4'  <== mode:M_NEIGHBOR
          (filter_list_bgp_tail
            FILTER_LIST:'filter-list'  <== mode:DEFAULT_MODE
            num = DEC:'1'  <== mode:DEFAULT_MODE
            OUT:'out'  <== mode:DEFAULT_MODE
            NEWLINE:'\n'  <== mode:DEFAULT_MODE)))
```

So what we should do is just add a reference in the extractor, and put a TODO comment to actually implement the filter-list handling in batfish.

```java
  @Override
  public void exitFilter_list_bgp_tail(Filter_list_bgp_tailContext ctx) {
    // add ref
  }

```

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1577)*

**Comment by dhalperi** [comment]
Looks like you will need to merge master and resolve conflicts before we can ship this.

But, :lgtm: !

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 2669 at r5](https://reviewable.io/reviews/batfish/batfish/1577#-LENSIKR0M3iTezCx2nX:-LENSIKR0M3iTezCx2nY:b-bh4g4n) ([raw file](https://github.com/batfish/batfish/blob/00c8c98d70f0cfcc2809b22bd2e8bbab4480a1e5/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L2669)):*
> ```Java
>         BGP_NEIGHBOR_FILTER_AS_PATH_ACCESS_LIST,
>         ctx.getStart().getLine());
>     // TODO: Handle filter-list in batfish
> ```

please alphabetize this in the file (near exitFlan_interface), rather than in the middle of the `Rbnx` part of the config.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoStructureUsage.java, line 19 at r5](https://reviewable.io/reviews/batfish/batfish/1577#-LENSE9VEUeR_XP5M-r1:-LENSE9VEUeR_XP5M-r2:bdltk7c) ([raw file](https://github.com/batfish/batfish/blob/00c8c98d70f0cfcc2809b22bd2e8bbab4480a1e5/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoStructureUsage.java#L19)):*
> ```Java
>   BGP_INHERITED_SESSION("inherited BGP peer-session"),
>   BGP_NEIGHBOR_REMOTE_AS_ROUTE_MAP("bgp neighbor remote-as route-map"),
>   BGP_NEIGHBOR_FILTER_AS_PATH_ACCESS_LIST("bgp neighbor filter-list access-list"),
> ```

please alphabetize this (F before R)

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1577#-:-LENSTx1DGP1E_LF8iaG:bfn9zmb)*

**Comment by arifogel** [comment]
Review status: 5 of 10 files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 4503 at r7](https://reviewable.io/reviews/batfish/batfish/1577#-LEQa1253GfwJfvEl7uy:-LEQa1262ONBsFS-yU8C:b24nlaa) ([raw file](https://github.com/batfish/batfish/blob/876587955b6f342870bf56f82792feab14fa7cae/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L4503)):*
> ```Java
>     String filterList = ctx.getText();
>     _configuration.referenceStructure(
>         AS_PATH_ACCESS_LIST,
> ```

I don't think this is an as-path access-list

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1577)*

**Comment by dhalperi** [comment]
*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 4503 at r7](https://reviewable.io/reviews/batfish/batfish/1577#-LEQa1253GfwJfvEl7uy:-LEQbWPB7eeq1WMdI2Kl:bgaqtve) ([raw file](https://github.com/batfish/batfish/blob/876587955b6f342870bf56f82792feab14fa7cae/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L4503)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

I don't think this is an as-path access-list
</blockquote></details>

https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/iproute_bgp/command/irg-cr-book/bgp-m1.html#wp4505123410 claims it is:

```
neighbor filter-list
To set up a BGP filter, use the neighbor filter-list command in address family or router configuration mode. To disable this function, use the no form of this command.

neighbor { ip-address | peer-group-name } filter-list access-list-number { in | out }

no neighbor { ip-address | peer-group-name } filter-list access-list-number { in | out }

Syntax Description
ip-address

IP address of the neighbor.

peer-group-name

Name of a BGP peer group.

access-list-number

Number of an autonomous system path access list. You define this access list with the ip as-path access-list command.

in

Access list is applied to incoming routes.

out

Access list is applied to outgoing routes.
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1577)*

**Comment by dhalperi** [comment]
Reviewed 5 of 5 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1577)*

**Comment by arifogel** [comment]
Reviewed 1 of 3 files at r1, 3 of 9 files at r4, 5 of 5 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 4503 at r7](https://reviewable.io/reviews/batfish/batfish/1577#-LEQa1253GfwJfvEl7uy:-LEQbnW77yJupHGUN6kb:blye7am) ([raw file](https://github.com/batfish/batfish/blob/876587955b6f342870bf56f82792feab14fa7cae/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L4503)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/iproute_bgp/command/irg-cr-book/bgp-m1.html#wp4505123410 claims it is:

```
neighbor filter-list
To set up a BGP filter, use the neighbor filter-list command in address family or router configuration mode. To disable this function, use the no form of this command.

neighbor { ip-address | peer-group-name } filter-list access-list-number { in | out }

no neighbor { ip-address | peer-group-name } filter-list access-list-number { in | out }

Syntax Description
ip-address

IP address of the neighbor.

peer-group-name

Name of a BGP peer group.

access-list-number

Number of an autonomous system path access list. You define this access list with the ip as-path access-list command.

in

Access list is applied to incoming routes.

out

Access list is applied to outgoing routes.
```
</blockquote></details>

Yeah sorry I confused with distribute-list, looked it up, then retracted.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 3549 at r7](https://reviewable.io/reviews/batfish/batfish/1577#-LEQbP3GE-Q7aiswEzt4:-LEQbP3GE-Q7aiswEzt5:b-gowkml) ([raw file](https://github.com/batfish/batfish/blob/876587955b6f342870bf56f82792feab14fa7cae/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L3549)):*
> ```Java
>     markConcreteStructure(
>         CiscoStructureType.AS_PATH_ACCESS_LIST,
>         CiscoStructureUsage.ROUTE_MAP_MATCH_AS_PATH_ACCESS_LIST);
> ```

What about  `BGP_NEIGHBOR_FILTER_AS_PATH_ACCESS_LIST`?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1577)*

**Comment by arifogel** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 3549 at r7](https://reviewable.io/reviews/batfish/batfish/1577#-LEQbP3GE-Q7aiswEzt4:-LEQbyyL-OXDhO5jGNWa:bame8sh) ([raw file](https://github.com/batfish/batfish/blob/876587955b6f342870bf56f82792feab14fa7cae/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L3549)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

What about  `BGP_NEIGHBOR_FILTER_AS_PATH_ACCESS_LIST`?
</blockquote></details>

Just to note - this should be caught with a unit test for that usage.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1577)*

**Comment by arifogel** [comment]
Reviewed 1 of 9 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1577)*

**Comment by vasu018** [comment]
*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 3549 at r7](https://reviewable.io/reviews/batfish/batfish/1577#-LEQbP3GE-Q7aiswEzt4:-LEQeQsbBEeCzeBy2Hhn:b-tkwyfm) ([raw file](https://github.com/batfish/batfish/blob/876587955b6f342870bf56f82792feab14fa7cae/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L3549)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Just to note - this should be caught with a unit test for that usage.
</blockquote></details>

Its a TODO not implemented yet. Will take it up separately in different PR.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1577)*

**Comment by arifogel** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 3549 at r7](https://reviewable.io/reviews/batfish/batfish/1577#-LEQbP3GE-Q7aiswEzt4:-LEQekQlCy7fEdS9MIlD:bayq08u) ([raw file](https://github.com/batfish/batfish/blob/876587955b6f342870bf56f82792feab14fa7cae/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L3549)):*
<details><summary><i>Previously, vasu018 (Vasudevan Nagendra) wrote…</i></summary><blockquote>

Its a TODO not implemented yet. Will take it up separately in different PR.
</blockquote></details>

I don't understand. I saw you add reference for it in `CiscoControlPlaneExtractor`. The only other thing to do is mark it here.
@dhalperi  am I missing something?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1577)*

**Comment by vasu018** [comment]
*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 3549 at r7](https://reviewable.io/reviews/batfish/batfish/1577#-LEQbP3GE-Q7aiswEzt4:-LERN7YO7wkZ1FiMYjjO:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/876587955b6f342870bf56f82792feab14fa7cae/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L3549)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

I don't understand. I saw you add reference for it in `CiscoControlPlaneExtractor`. The only other thing to do is mark it here.
@dhalperi  am I missing something?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1577)*

**Comment by arifogel** [comment]
Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 3549 at r7](https://reviewable.io/reviews/batfish/batfish/1577#-LEQbP3GE-Q7aiswEzt4:-LERSRcMB7eHewNQpWdF:bl16axn) ([raw file](https://github.com/batfish/batfish/blob/876587955b6f342870bf56f82792feab14fa7cae/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L3549)):*
<details><summary><i>Previously, vasu018 (Vasudevan Nagendra) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Did this not result in a ref change? If not, you need to add a line of this form to one of the unit test configs.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1577)*

**Comment by vasu018** [comment]
*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 3550 at r7](https://reviewable.io/reviews/batfish/batfish/1577#-LERdtWk1-wJwvjc1Eg5:-LERdtWk1-wJwvjc1Eg6:bx7r86c) ([raw file](https://github.com/batfish/batfish/blob/876587955b6f342870bf56f82792feab14fa7cae/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L3550)):*
> ```
>  
>     // record references to defined structures
> ```

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1577)*

**Comment by vasu018** [comment]
*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 3549 at r7](https://reviewable.io/reviews/batfish/batfish/1577#-LEQbP3GE-Q7aiswEzt4:-LERAGxd6Xj24W5M2cYu:b-mnvl7w) ([raw file](https://github.com/batfish/batfish/blob/876587955b6f342870bf56f82792feab14fa7cae/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L3549)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Did this not result in a ref change? If not, you need to add a line of this form to one of the unit test configs.
</blockquote></details>

Added the ref changes required for the new structure and configuration changes.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1577)*

**Comment by arifogel** [comment]
Reviewed 4 of 5 files at r9.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/parsing-tests/unit-tests-undefined.ref, line 30 at r9](https://reviewable.io/reviews/batfish/batfish/1577#-LEVCA3S7OybniGzN2Wz:-LEVFruWBBkoFLEixqbH:bwv70qc) ([raw file](https://github.com/batfish/batfish/blob/0caacb3c1afb8fff205f74d19a02e29a69cc3d64/tests/parsing-tests/unit-tests-undefined.ref#L30)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> filter-list20in
> ```

There's something wrong in the way we get name out in CiscoControlPlaneExtractor. Rather than thinking the name is `20`, it thinks the name is `filter-list20in`.

So we're getting false positives for unused and undefined here.
</blockquote></details>

That's not consistent with the parse tree in `unit-tests.ref`. How odd

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1577)*

**Comment by dhalperi** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r10.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1577#-:-LEVox00B65D5wuMRruO:bnfp4nl)*

**Comment by dhalperi** [comment]
Ready to be squashed when you are!

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1577#-:-LEVozUY5kOIEtSwCJJp:b1gz7ak)*

**Comment by vasu018** [comment]
Review status: 10 of 11 files reviewed at latest revision, all discussions resolved.

---

*[tests/parsing-tests/unit-tests-undefined.ref, line 30 at r9](https://reviewable.io/reviews/batfish/batfish/1577#-LEVCA3S7OybniGzN2Wz:-LEVUL1a7_fzDG6C77-7:b-g0xnj7) ([raw file](https://github.com/batfish/batfish/blob/0caacb3c1afb8fff205f74d19a02e29a69cc3d64/tests/parsing-tests/unit-tests-undefined.ref#L30)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

That's not consistent with the parse tree in `unit-tests.ref`. How odd
</blockquote></details>

Yes. I extracted the complete text rather than simply number from the configuration line.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1577)*

**Comment by dhalperi** [comment]
Reviewed 1 of 1 files at r11.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1577)*

**Pull request merged**
