### PR TITLE
configure exception/assertions for a question; cleanup of related classes

### PR DESCRIPTION
**Pull request by ratulm**
This change is [Reviewable](https://reviewable.io/reviews/batfish/batfish/888)

### CODE REVIEW

**Comment by corinaminer** [comment]
nice!

---

Reviewed 20 of 20 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[projects/batfish-client/src/main/java/org/batfish/client/Client.java, line 831 at r1](https://reviewable.io:443/reviews/batfish/batfish/888#-L4DwKRXVyyRN8kdPOhb:-L4DwKRXVyyRN8kdPOhc:bhce6xr) ([raw file](https://github.com/batfish/batfish/blob/e35fbf693875687a15ab95e7b10a829e7d6caa6b/projects/batfish-client/src/main/java/org/batfish/client/Client.java#L831)):*
> ```Java
>     }
>     if (exceptions == null && assertion == null && params.size() > 0) {
>       throw new BatfishException("Unknown parameter(s): " + params.keySet());
> ```

technically shouldn't this error also occur if one parameter is unknown and the other is `exception` or `assertion`?

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java, line 199 at r1](https://reviewable.io:443/reviews/batfish/batfish/888#-L4DLWNKwMwVQ_paue_s:-L4DLWNKwMwVQ_paue_t:b-9aiswe) ([raw file](https://github.com/batfish/batfish/blob/e35fbf693875687a15ab95e7b10a829e7d6caa6b/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java#L199)):*
> ```Java
>    * @param clientVersion The version of the client
>    * @param questionTemplate The template to extend (JSON string)
>    * @param exceptions The exceptions to add (JSON string
> ```

missing end parenthesis

---

*[projects/question/src/test/java/org/batfish/question/jsonpath/JsonPathQuestionPluginTest.java, line 19 at r1](https://reviewable.io:443/reviews/batfish/batfish/888#-L4DmcHTmza2NDC5eCXi:-L4DmcHTmza2NDC5eCXj:b-ozg12h) ([raw file](https://github.com/batfish/batfish/blob/e35fbf693875687a15ab95e7b10a829e7d6caa6b/projects/question/src/test/java/org/batfish/question/jsonpath/JsonPathQuestionPluginTest.java#L19)):*
> ```Java
> 
>   @Test
>   public void configureTemplateTest() throws IOException {
> ```

Is this test redundant with the new test in the commands file that creates a template with assertions and exceptions?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/888#-:-L4DxQfPj9It3W56GW9H:b-7m74ox)*

**Comment by ratulm** [comment]
Review status: 15 of 21 files reviewed at latest revision, 3 unresolved discussions.

---

*[projects/batfish-client/src/main/java/org/batfish/client/Client.java, line 831 at r1](https://reviewable.io:443/reviews/batfish/batfish/888#-L4DwKRXVyyRN8kdPOhb:-L4EhrIj3flYK6-sWKNS:b4h8s32) ([raw file](https://github.com/batfish/batfish/blob/e35fbf693875687a15ab95e7b10a829e7d6caa6b/projects/batfish-client/src/main/java/org/batfish/client/Client.java#L831)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

technically shouldn't this error also occur if one parameter is unknown and the other is `exception` or `assertion`?
</blockquote></details>

yes. fixed.

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java, line 199 at r1](https://reviewable.io:443/reviews/batfish/batfish/888#-L4DLWNKwMwVQ_paue_s:-L4Ei55dUi10ZFRg8Jua:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/e35fbf693875687a15ab95e7b10a829e7d6caa6b/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java#L199)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

missing end parenthesis
</blockquote></details>

Done.

---

*[projects/question/src/test/java/org/batfish/question/jsonpath/JsonPathQuestionPluginTest.java, line 19 at r1](https://reviewable.io:443/reviews/batfish/batfish/888#-L4DmcHTmza2NDC5eCXi:-L4Ei6u4rt17LEEYjKs6:bt4m51) ([raw file](https://github.com/batfish/batfish/blob/e35fbf693875687a15ab95e7b10a829e7d6caa6b/projects/question/src/test/java/org/batfish/question/jsonpath/JsonPathQuestionPluginTest.java#L19)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Is this test redundant with the new test in the commands file that creates a template with assertions and exceptions?
</blockquote></details>

in terms of core functionality, yes. the difference is unit vs e2e test. (unit test failures are easier to debug, so that's valuable even when their target functionality in exercised by an e2e test.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/888)*

**Comment by corinaminer** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish-client/src/main/java/org/batfish/client/Client.java, line 831 at r2](https://reviewable.io:443/reviews/batfish/batfish/888#-L4HVk0EdbW1ElHTrj1F:-L4HVk0FCRxzcLHIQxUk:bzfahl5) ([raw file](https://github.com/batfish/batfish/blob/378a4818dad6284d4da976dccedc7bdf634e099e/projects/batfish-client/src/main/java/org/batfish/client/Client.java#L831)):*
> ```Java
>       throw new BatfishException("Template not found: '" + oldTemplateName + "'");
>     }
>     if (!Sets.difference(params.keySet(), Sets.newHashSet("exceptions", "assertion")).isEmpty()) {
> ```

Based on your `isValidArgument` call, isn't it acceptable to for there to be 1 or 0 params?`Sets.difference` will not be empty if params are missing "exceptions" or "assertion"

---

*[projects/question/pom.xml, line 104 at r2](https://reviewable.io:443/reviews/batfish/batfish/888#-L4HVIJPsWsggxPJ9l76:-L4HVIJQpRj4ELj2NAWt:b-wph6fx) ([raw file](https://github.com/batfish/batfish/blob/378a4818dad6284d4da976dccedc7bdf634e099e/projects/question/pom.xml#L104)):*
> ```XML
>     <dependency>
>       <groupId>com.google.code.findbugs</groupId>
>       <artifactId>jsr305</artifactId>
> ```

is this file supposed to be included?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/888)*

**Comment by ratulm** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish-client/src/main/java/org/batfish/client/Client.java, line 831 at r2](https://reviewable.io:443/reviews/batfish/batfish/888#-L4HVk0EdbW1ElHTrj1F:-L4Hdf4sPmAx9TA5VN8u:b-icjrp) ([raw file](https://github.com/batfish/batfish/blob/378a4818dad6284d4da976dccedc7bdf634e099e/projects/batfish-client/src/main/java/org/batfish/client/Client.java#L831)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Based on your `isValidArgument` call, isn't it acceptable to for there to be 1 or 0 params?`Sets.difference` will not be empty if params are missing "exceptions" or "assertion"
</blockquote></details>

Set difference is one-way: All elements in Set1 that are not in Set2. (I was trying to safeguard against the params being (GARBAGE, exceptions), in which case the difference will be GARBAGE).

---

*[projects/question/pom.xml, line 104 at r2](https://reviewable.io:443/reviews/batfish/batfish/888#-L4HVIJPsWsggxPJ9l76:-L4HdyIwLZrBsjhXaqeB:b-wn6t7y) ([raw file](https://github.com/batfish/batfish/blob/378a4818dad6284d4da976dccedc7bdf634e099e/projects/question/pom.xml#L104)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

is this file supposed to be included?
</blockquote></details>

yes. needed for Nullable annotation. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/888)*

**Comment by corinaminer** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish-client/src/main/java/org/batfish/client/Client.java, line 831 at r2](https://reviewable.io:443/reviews/batfish/batfish/888#-L4HVk0EdbW1ElHTrj1F:-L4HeZnGtbnK-R2Og8MB:b7vildb) ([raw file](https://github.com/batfish/batfish/blob/378a4818dad6284d4da976dccedc7bdf634e099e/projects/batfish-client/src/main/java/org/batfish/client/Client.java#L831)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

Set difference is one-way: All elements in Set1 that are not in Set2. (I was trying to safeguard against the params being (GARBAGE, exceptions), in which case the difference will be GARBAGE).
</blockquote></details>

oh ok, misunderstood the method :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/888#-:-L4HehZxcpyevqVLeshu:bnfp4nl)*

**Pull request merged**
