### PR TITLE
CheckPoint: Warn about unhandled object types

### PR DESCRIPTION
**Pull request by sfraint**
* Slightly reorganize object conversion
* Add warnings about unhandled object types

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7305)* status: all files reviewed, 3 unresolved discussions (waiting on @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java, line 167 at r1](https://reviewable.io/reviews/batfish/batfish/7305#-MicDHU8EeNyxdl7GN8F:-MicDHU8EeNyxdl7GN8G:b1jb2oe) ([raw file](https://github.com/batfish/batfish/blob/ce105c4879bab5075d4e9397649e16ef5c56c352/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java#L167)):*
> ```Java
> 
>   /**
>    * Convert specified objects to their VI model equivalent representation(s) if applicable, and add
> ```

The doc should be more detailed about what is passed in here. In particular, if you need multiple files' versions of an object (that will have the same UID), they both cannot be passed in at once in the same dictionary.
You can actually just resolve this by having the argument be a collection rather than a map.
In either case, the doc should be explicit about what happens when duplicate objects are encountered (whether same UID but different types/content; or identical).
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java, line 183 at r1](https://reviewable.io/reviews/batfish/batfish/7305#-MicFcGj134ftJ_9mh8B:-MicFcGj134ftJ_9mh8C:b5h6ta) ([raw file](https://github.com/batfish/batfish/blob/ce105c4879bab5075d4e9397649e16ef5c56c352/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java#L183)):*
> ```Java
>               }
> 
>               if (obj instanceof UnknownTypedManagementObject) {
> ```

Either use `if/else if/else` chain or put this at the top with a return after the warning.
BTW this is a fantastic place to use a visitor (non-blocking).
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java, line 199 at r1](https://reviewable.io/reviews/batfish/batfish/7305#-MicBmQ9A32rvW28sEl5:-MicBmQ9A32rvW28sEl6:b-hskgl7) ([raw file](https://github.com/batfish/batfish/blob/ce105c4879bab5075d4e9397649e16ef5c56c352/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java#L199)):*
> ```Java
>    */
>   private void convertPackage(@Nullable ManagementPackage pakij) {
>     Optional.ofNullable(pakij.getNatRulebase())
> ```

minor, optional: extract out first two statements into `convertObjects(ManagementPackage)` for max high-level legibility of this function.

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7305)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java, line 167 at r1](https://reviewable.io/reviews/batfish/batfish/7305#-MicDHU8EeNyxdl7GN8F:-MicHQkbCT8imMJ_uhJg:b-bapyy4) ([raw file](https://github.com/batfish/batfish/blob/ce105c4879bab5075d4e9397649e16ef5c56c352/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java#L167)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

The doc should be more detailed about what is passed in here. In particular, if you need multiple files' versions of an object (that will have the same UID), they both cannot be passed in at once in the same dictionary.
You can actually just resolve this by having the argument be a collection rather than a map.
In either case, the doc should be explicit about what happens when duplicate objects are encountered (whether same UID but different types/content; or identical).

</blockquote></details>

this function only converts a single dict of `uid` to `obj`, we probably need to (separately) do more iteration and/or a real design for versioned objects - since they presumably will co-exist in the VI model as well

added a blurb about overwriting same-named objects for now - that seem good enough?
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java, line 183 at r1](https://reviewable.io/reviews/batfish/batfish/7305#-MicFcGj134ftJ_9mh8B:-MicIXygAtzCsqy3MWfC:b-k6ar13) ([raw file](https://github.com/batfish/batfish/blob/ce105c4879bab5075d4e9397649e16ef5c56c352/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java#L183)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Either use `if/else if/else` chain or put this at the top with a return after the warning.
BTW this is a fantastic place to use a visitor (non-blocking).
</blockquote></details>

I specifically avoided `if`/`else if` here in case an object needs to be converted multiple times / into different types of VI model constructs

moved to the top for now
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java, line 199 at r1](https://reviewable.io/reviews/batfish/batfish/7305#-MicBmQ9A32rvW28sEl5:-MicL2j_0nilSCfzfXfy:bvnrpcm) ([raw file](https://github.com/batfish/batfish/blob/ce105c4879bab5075d4e9397649e16ef5c56c352/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java#L199)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

minor, optional: extract out first two statements into `convertObjects(ManagementPackage)` for max high-level legibility of this function.
</blockquote></details>

updated

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7305)* status: all files reviewed, 1 unresolved discussion (waiting on @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java, line 167 at r1](https://reviewable.io/reviews/batfish/batfish/7305#-MicDHU8EeNyxdl7GN8F:-MicLTEu-KlbcjDZkmS6:b-pcb5sd) ([raw file](https://github.com/batfish/batfish/blob/ce105c4879bab5075d4e9397649e16ef5c56c352/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java#L167)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

this function only converts a single dict of `uid` to `obj`, we probably need to (separately) do more iteration and/or a real design for versioned objects - since they presumably will co-exist in the VI model as well

added a blurb about overwriting same-named objects for now - that seem good enough?
</blockquote></details>

When you say versioned objects, do you mean different versions over time?
I wouldn't worry about revisions for now at all.

I was just talking about different schemas for the same object in different files, like simple-gateway in show-gateways-and-servers.json vs show-objects.json.

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7305)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java, line 167 at r1](https://reviewable.io/reviews/batfish/batfish/7305#-MicDHU8EeNyxdl7GN8F:-MicqHKb9q3wanPoDSKx:b-6u4m7h) ([raw file](https://github.com/batfish/batfish/blob/ce105c4879bab5075d4e9397649e16ef5c56c352/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java#L167)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

When you say versioned objects, do you mean different versions over time?
I wouldn't worry about revisions for now at all.

I was just talking about different schemas for the same object in different files, like simple-gateway in show-gateways-and-servers.json vs show-objects.json.

</blockquote></details>

I did, but my comment still stands wrt same-named objects from different dicts, and at this point I think we can assume same-named objects defined in different object-dictionaries will be the same

**Review by sfraint — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7305)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

**Review by arifogel — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7305)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7305)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

**Pull request merged**
