### PR TITLE
Juniper: implement and/or warn for PsThen clauses

### PR DESCRIPTION
**Pull request by dhalperi**

### CODE REVIEW

**Comment by progwriter** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/PsThenMetricAdd.java, line 10 at r1](https://reviewable.io/reviews/batfish/batfish/1539#-LDr4hWO5X1akbNNezNa:-LDr4hWO5X1akbNNezNb:b8keb1l) ([raw file](https://github.com/batfish/batfish/blob/82c91045402c126a4ec61cb065fdc06639f0395d/projects/batfish/src/main/java/org/batfish/representation/juniper/PsThenMetricAdd.java#L10)):*
> ```Java
> import org.batfish.datamodel.routing_policy.statement.Statement;
> 
> public final class PsThenMetricAdd extends PsThen {
> ```

I'd suggest javadocing these top level classes

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/PsThenNextHopSelf.java, line 25 at r1](https://reviewable.io/reviews/batfish/batfish/1539#-LDr5Rtj6MQoMfXZCPrN:-LDr5Rtj6MQoMfXZCPrO:b2nh4fg) ([raw file](https://github.com/batfish/batfish/blob/82c91045402c126a4ec61cb065fdc06639f0395d/projects/batfish/src/main/java/org/batfish/representation/juniper/PsThenNextHopSelf.java#L25)):*
> ```Java
>       Configuration c,
>       Warnings w) {
>     // TODO: what is the meaning of destinationVrf?
> ```

:) 

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1539)*

**Comment by sfraint** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1539#-:-LDrECh1AFG0BKU3beR7:bnfp4nl)*

**Comment by arifogel** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_policy_options.g4, line 588 at r1](https://reviewable.io/reviews/batfish/batfish/1539#-LDrESYu3cjTSqc704GN:-LDrESYv0N4Gp7OELzMw:b-vi3icu) ([raw file](https://github.com/batfish/batfish/blob/82c91045402c126a4ec61cb065fdc06639f0395d/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_policy_options.g4#L588)):*
> ```ANTLR
> popst_next_hop_self
> :
>    NEXT_HOP SELF
> ```

Why take this out but not `PEER_ADDRESS`?

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/PsThenAsPathPrepend.java, line 31 at r1](https://reviewable.io/reviews/batfish/batfish/1539#-LDrEsvQECogy61zqpLq:-LDrEsvQECogy61zqpLr:b-wod506) ([raw file](https://github.com/batfish/batfish/blob/82c91045402c126a4ec61cb065fdc06639f0395d/projects/batfish/src/main/java/org/batfish/representation/juniper/PsThenAsPathPrepend.java#L31)):*
> ```Java
>       Configuration c,
>       Warnings w) {
>     List<AsExpr> asList = _asPath.stream().map(ExplicitAs::new).collect(Collectors.toList());
> ```

Can you use `ImmutableList` here? We've been burned in the past by accidental modification of as-path.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1539)*

**Comment by arifogel** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1539)*

**Comment by dhalperi** [comment]
Review status: 10 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_policy_options.g4, line 588 at r1](https://reviewable.io/reviews/batfish/batfish/1539#-LDrESYu3cjTSqc704GN:-LDrFg8A6I-V0QfLiXZz:b-wt9fz3) ([raw file](https://github.com/batfish/batfish/blob/82c91045402c126a4ec61cb065fdc06639f0395d/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_policy_options.g4#L588)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Why take this out but not `PEER_ADDRESS`?
</blockquote></details>

Because I do not know the semantics of peer address (do you?) and it did not seem relevant for this PR.

(In this PR, I only implemented things I see used in real configs)

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/PsThenAsPathPrepend.java, line 31 at r1](https://reviewable.io/reviews/batfish/batfish/1539#-LDrEsvQECogy61zqpLq:-LDrG-o31BXZ93ausrtx:bxvjsgk) ([raw file](https://github.com/batfish/batfish/blob/82c91045402c126a4ec61cb065fdc06639f0395d/projects/batfish/src/main/java/org/batfish/representation/juniper/PsThenAsPathPrepend.java#L31)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Can you use `ImmutableList` here? We've been burned in the past by accidental modification of as-path.
</blockquote></details>

This is the callee's responsibility, not the caller's. Added an implementation there.

(The callee does not care if the list is mutated, since it's a temp local)

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1539)*

**Comment by dhalperi** [comment]
Review status: 10 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/PsThenAsPathPrepend.java, line 31 at r1](https://reviewable.io/reviews/batfish/batfish/1539#-LDrEsvQECogy61zqpLq:-LDrG9xs4msGUofGTB3e:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/82c91045402c126a4ec61cb065fdc06639f0395d/projects/batfish/src/main/java/org/batfish/representation/juniper/PsThenAsPathPrepend.java#L31)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

This is the callee's responsibility, not the caller's. Added an implementation there.

(The callee does not care if the list is mutated, since it's a temp local)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1539)*

**Comment by dhalperi** [comment]
Review status: 10 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_policy_options.g4, line 588 at r1](https://reviewable.io/reviews/batfish/batfish/1539#-LDrESYu3cjTSqc704GN:-LDrGckRBGWJVExo4HNh:b-ex2d6r) ([raw file](https://github.com/batfish/batfish/blob/82c91045402c126a4ec61cb065fdc06639f0395d/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_policy_options.g4#L588)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Because I do not know the semantics of peer address (do you?) and it did not seem relevant for this PR.

(In this PR, I only implemented things I see used in real configs)
</blockquote></details>

(The calleR does not care...)

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1539)*

**Comment by arifogel** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_policy_options.g4, line 588 at r1](https://reviewable.io/reviews/batfish/batfish/1539#-LDrESYu3cjTSqc704GN:-LDrH9lz2yzY_JrCSFTR:bcc62nk) ([raw file](https://github.com/batfish/batfish/blob/82c91045402c126a4ec61cb065fdc06639f0395d/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_policy_options.g4#L588)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

(The calleR does not care...)
</blockquote></details>

Peer address means the IP address of the other end of the session. We already have a `RoutingPolicy` primitive for it, I believe. Your call whether to implement in this PR.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1539)*

**Comment by arifogel** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1539)*

**Comment by arifogel** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1539#-:-LDrJN_b6Pt6Xo2Ro_Dq:bnfp4nl)*

**Pull request merged**
