### PR TITLE
Aws region hierarchy

### LINKED ISSUE #714: process AWS regions
currently, batfish does not pay attention to regions while processing aws configuration. since region information is not present in json configuration itself, we need to change the input format for aws configuration (e.g., the top-level folder under aws_configs is <region> and all json files for this region go under this folder). further changes will then be needed for vendor-specific configuration to remember this information.

### PR DESCRIPTION
**Pull request by ratulm**
Fixes #714

---
This change is [Reviewable](https://reviewable.io/reviews/batfish/batfish/812)

### CODE REVIEW

**Comment by dhalperi** [comment]
:lgtm: when green

---

Reviewed 121 of 121 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/812#-:-L1UMu_FBB_xClLmbUFt:brr0024)*

**Comment by dhalperi** [comment]
*[tests/basic/nodes-unit-tests.ref, line 12432 at r3](https://reviewable.io:443/reviews/batfish/batfish/812#-L1UN4Hb5nG3yMNWBCW9:-L1UN4Hb5nG3yMNWBCWA:b-udxjji) ([raw file](https://github.com/batfish/batfish/blob/367380c478c9cb4d5674f3a5636a2c9fb201030f/tests/basic/nodes-unit-tests.ref#L12432)):*
> ```
>           "vendorFamily" : {
>             "aws" : {
>               "region" : "aws_configs"
> ```

this looks suspicious. Test data wrong?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/812)*

**Comment by dhalperi** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/812)*

**Comment by ratulm** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/basic/nodes-unit-tests.ref, line 12432 at r3](https://reviewable.io:443/reviews/batfish/batfish/812#-L1UN4Hb5nG3yMNWBCW9:-L1UNRT9S1y7dQKzm-XH:b-mqfkfh) ([raw file](https://github.com/batfish/batfish/blob/367380c478c9cb4d5674f3a5636a2c9fb201030f/tests/basic/nodes-unit-tests.ref#L12432)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

this looks suspicious. Test data wrong?
</blockquote></details>

things are region-embedded for parsing unit tests. the code still works as it assume region is the parent folder.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/812)*

**Comment by ratulm** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/basic/nodes-unit-tests.ref, line 12432 at r3](https://reviewable.io:443/reviews/batfish/batfish/812#-L1UN4Hb5nG3yMNWBCW9:-L1UNe0VSxV7S8dzqVXv:bb14kuw) ([raw file](https://github.com/batfish/batfish/blob/367380c478c9cb4d5674f3a5636a2c9fb201030f/tests/basic/nodes-unit-tests.ref#L12432)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

things are region-embedded for parsing unit tests. the code still works as it assume region is the parent folder.
</blockquote></details>

i meant: yes, it is a data quirk, and things are NOT region-embedded.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/812)*

**Comment by dhalperi** [comment]
:lgtm: when green

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/812#-:-L1UO4FR8c1mvZv6AEry:brr0024)*

**Pull request merged**
