### PR TITLE
Recognizing IP wildcard in Source/Destination address of firewall

### PR DESCRIPTION
**Pull request by haverma**

### CODE REVIEW

**Comment by sfraint** [comment]
Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 2694 at r2](https://reviewable.io/reviews/batfish/batfish/1297#-LBg_PzcDOVRRGo50K89:-LBg_PzdC2ZF6k7ppEmx:b-wzjuy6) ([raw file](https://github.com/batfish/batfish/blob/472565b6db78a0c3cce6b68dd5e8c6441a815a71/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L2694)):*
> ```Java
> 
>   @Override
>   public void exitFftf_destination_address(Fftf_destination_addressContext ctx) {
> ```

Seems like this logic can be simplified a little (I see a few pieces of duplicate code `ctx.EXCEPT() != null`, `_currentFwTerm.getFroms().add(from)`).  Maybe:
```
IpWildcard ipWildcard;
if (ip and wildcard != null) {
  ipWildcard = new IpWildcard(...);
} else if (ip != null) {
  ipWildcard = new IpWildcard(...);
} else if (prefix != null) {
  ipWildcard = new IpWildcard(...);
}

if (ipWildcard != null) {
  if (except) {
    from = new FwFromDestinationAddressExcept(ipWildcard);
  } else {
    from = new FwFromDestinationAddress(ipWildcard);
  }
  add(from);
}
```

Similar idea applies to src address below as well.

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromDestinationAddress.java, line 18 at r2](https://reviewable.io/reviews/batfish/batfish/1297#-LBgbI4K4FvyBJBPlzlY:-LBgbI4K4FvyBJBPlzlZ:b-t9aajq) ([raw file](https://github.com/batfish/batfish/blob/472565b6db78a0c3cce6b68dd5e8c6441a815a71/projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromDestinationAddress.java#L18)):*
> ```Java
>   @Nullable private final IpWildcard _ipWildcard;
> 
>   @Nullable private final Prefix _prefix;
> ```

Any reason not to just use `IpWildcard` here? (same question applies below)

---

*[projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java, line 961 at r2](https://reviewable.io/reviews/batfish/batfish/1297#-LBgcMiPAb7DPKBgL7Lo:-LBgcMiPAb7DPKBgL7Lp:b-ychiv9) ([raw file](https://github.com/batfish/batfish/blob/472565b6db78a0c3cce6b68dd5e8c6441a815a71/projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java#L961)):*
> ```Java
>         Iterables.getOnlyElement(fwSourceAddressAcl.getLines()),
>         equalTo(
>             IpAccessListLine.builder()
> ```

Use matchers here for more useful output.
See `CiscoGrammarTest.java` for quite a few examples (look for `hasIpAccessList(`

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1297)*

**Comment by arifogel** [comment]
Reviewed 8 of 10 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_firewall.g4, line 131 at r2](https://reviewable.io/reviews/batfish/batfish/1297#-LBgcRH_2WWaZG1F-92A:-LBgcRHaEkqsLxtfa9aZ:b-el3cof) ([raw file](https://github.com/batfish/batfish/blob/472565b6db78a0c3cce6b68dd5e8c6441a815a71/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_firewall.g4#L131)):*
> ```ANTLR
>       | IPV6_ADDRESS
>       | IPV6_PREFIX
>       | ip_address = IP_ADDRESS FORWARD_SLASH wildcard_mask = IP_ADDRESS
> ```

Could you fold this into the top alternative as `(FORWARD_SLASH wildcard_mask = IP_ADDRESS)?`? Same in rule below.

---

*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 2697 at r2](https://reviewable.io/reviews/batfish/batfish/1297#-LBgd0ix6Uutn9Eor8-Z:-LBgd0ix6Uutn9Eor8-_:b-yfkhmm) ([raw file](https://github.com/batfish/batfish/blob/472565b6db78a0c3cce6b68dd5e8c6441a815a71/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L2697)):*
> ```Java
>     if (ctx.ip_address != null && ctx.wildcard_mask != null) {
>       IpWildcard ipWildcard =
>           new IpWildcard(new Ip(ctx.ip_address.getText()), new Ip(ctx.wildcard_mask.getText()));
> ```

I think this `Ip` needs to be inverted ;`IpWildcard` expects Cisco-style wildcard mask, which is opposite of Juniper-style wildcard mask.
Also below, though that code should probably just be factored out.

---

*[projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java, line 961 at r2](https://reviewable.io/reviews/batfish/batfish/1297#-LBgcMiPAb7DPKBgL7Lo:-LBgdREC1FYRMqWkeaQB:b-opo2jw) ([raw file](https://github.com/batfish/batfish/blob/472565b6db78a0c3cce6b68dd5e8c6441a815a71/projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java#L961)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

Use matchers here for more useful output.
See `CiscoGrammarTest.java` for quite a few examples (look for `hasIpAccessList(`
</blockquote></details>

Further, I would suggest using semantic test rather than syntactic one. Look for use of `IpAccessListMatchers.accepts/rejects`. It's better to have tests for behavior rather than shape.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1297)*

**Comment by haverma** [comment]
Review status: 2 of 10 files reviewed at latest revision, 5 unresolved discussions.

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_firewall.g4, line 131 at r2](https://reviewable.io/reviews/batfish/batfish/1297#-LBgcRH_2WWaZG1F-92A:-LBiGBKLBdDinlJyJovf:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/472565b6db78a0c3cce6b68dd5e8c6441a815a71/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_firewall.g4#L131)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Could you fold this into the top alternative as `(FORWARD_SLASH wildcard_mask = IP_ADDRESS)?`? Same in rule below.
</blockquote></details>

done

---

*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 2694 at r2](https://reviewable.io/reviews/batfish/batfish/1297#-LBg_PzcDOVRRGo50K89:-LBiGEOd9bbqGjfpqO_T:b2r6p1w) ([raw file](https://github.com/batfish/batfish/blob/472565b6db78a0c3cce6b68dd5e8c6441a815a71/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L2694)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

Seems like this logic can be simplified a little (I see a few pieces of duplicate code `ctx.EXCEPT() != null`, `_currentFwTerm.getFroms().add(from)`).  Maybe:
```
IpWildcard ipWildcard;
if (ip and wildcard != null) {
  ipWildcard = new IpWildcard(...);
} else if (ip != null) {
  ipWildcard = new IpWildcard(...);
} else if (prefix != null) {
  ipWildcard = new IpWildcard(...);
}

if (ipWildcard != null) {
  if (except) {
    from = new FwFromDestinationAddressExcept(ipWildcard);
  } else {
    from = new FwFromDestinationAddress(ipWildcard);
  }
  add(from);
}
```

Similar idea applies to src address below as well.
</blockquote></details>

restructured and refactored out the duplicated code

---

*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 2697 at r2](https://reviewable.io/reviews/batfish/batfish/1297#-LBgd0ix6Uutn9Eor8-Z:-LBiGJ7H5IMv2dsl8UDG:b-u4mgqf) ([raw file](https://github.com/batfish/batfish/blob/472565b6db78a0c3cce6b68dd5e8c6441a815a71/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L2697)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

I think this `Ip` needs to be inverted ;`IpWildcard` expects Cisco-style wildcard mask, which is opposite of Juniper-style wildcard mask.
Also below, though that code should probably just be factored out.
</blockquote></details>

inverted the mask and factored out the duplicated code

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromDestinationAddress.java, line 18 at r2](https://reviewable.io/reviews/batfish/batfish/1297#-LBgbI4K4FvyBJBPlzlY:-LBiGfeLCoYiT0R5jPTg:b4zdjih) ([raw file](https://github.com/batfish/batfish/blob/472565b6db78a0c3cce6b68dd5e8c6441a815a71/projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromDestinationAddress.java#L18)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

Any reason not to just use `IpWildcard` here? (same question applies below)
</blockquote></details>

done, removed `Prefix`

---

*[projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java, line 961 at r2](https://reviewable.io/reviews/batfish/batfish/1297#-LBgcMiPAb7DPKBgL7Lo:-LBiGmND35vOpUBGgHUd:b5ijale) ([raw file](https://github.com/batfish/batfish/blob/472565b6db78a0c3cce6b68dd5e8c6441a815a71/projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java#L961)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Further, I would suggest using semantic test rather than syntactic one. Look for use of `IpAccessListMatchers.accepts/rejects`. It's better to have tests for behavior rather than shape.
</blockquote></details>

Using `Matchers`

Added behavioral tests 

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1297)*

**Comment by arifogel** [comment]
Reviewed 8 of 8 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_firewall.g4, line 127 at r3](https://reviewable.io/reviews/batfish/batfish/1297#-LBiUfaGCiTTcecTwzkl:-LBiUfaGCiTTcecTwzkm:b4k2mes) ([raw file](https://github.com/batfish/batfish/blob/f8874f79397b092b5bf1bb8a7b5f4d899b2862c1/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_firewall.g4#L127)):*
> ```ANTLR
>    DESTINATION_ADDRESS
>    (
>       ip_address = IP_ADDRESS (FORWARD_SLASH wildcard_mask = IP_ADDRESS)?
> ```

While you are refactoring the code that uses this, why not refactor this list of alternatives into a separate grammar rule? Then your `formIpWildcard` function could just take an instance of that new rule context type as an argument.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1297)*

**Comment by sfraint** [comment]
Reviewed 5 of 8 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromSourceAddress.java, line 18 at r3](https://reviewable.io/reviews/batfish/batfish/1297#-LBvWI26E_y7B29brbaW:-LBvWI2773qytBo9DEGt:b-o2qyf7) ([raw file](https://github.com/batfish/batfish/blob/f8874f79397b092b5bf1bb8a7b5f4d899b2862c1/projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromSourceAddress.java#L18)):*
> ```Java
>   @Nullable private final IpWildcard _ipWildcard;
> 
>   @Nullable private final Prefix _prefix;
> ```

Remove prefix from this class as well.

---

*[projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java, line 1020 at r3](https://reviewable.io/reviews/batfish/batfish/1297#-LBvXUVX0j-BNV49yoXA:-LBvXUVX0j-BNV49yoXB:bpz54gb) ([raw file](https://github.com/batfish/batfish/blob/f8874f79397b092b5bf1bb8a7b5f4d899b2862c1/projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java#L1020)):*
> ```Java
>     assertThat(c.getIpAccessLists().keySet(), hasSize(1));
> 
>     Flow whileListedSrc = createFlow("1.8.3.9", "2.5.6.7");
> ```

nitpick: think this should be `whiteListedSrc`

---

*[projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java, line 1038 at r3](https://reviewable.io/reviews/batfish/batfish/1297#-LBvXZPSD3Rkjb3QMu9I:-LBvXZPSD3Rkjb3QMu9J:bpz54gb) ([raw file](https://github.com/batfish/batfish/blob/f8874f79397b092b5bf1bb8a7b5f4d899b2862c1/projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java#L1038)):*
> ```Java
>     assertThat(c.getIpAccessLists().keySet(), hasSize(1));
> 
>     Flow whileListedDst = createFlow("2.5.6.7", "1.8.3.9");
> ```

nitpick: think this should be `whiteListedSrc`

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1297)*

**Comment by haverma** [comment]
Review status: 6 of 12 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_firewall.g4, line 127 at r3](https://reviewable.io/reviews/batfish/batfish/1297#-LBiUfaGCiTTcecTwzkl:-LBvlwNkCCurbNZ-iTVa:bv3hd0t) ([raw file](https://github.com/batfish/batfish/blob/f8874f79397b092b5bf1bb8a7b5f4d899b2862c1/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_firewall.g4#L127)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

While you are refactoring the code that uses this, why not refactor this list of alternatives into a separate grammar rule? Then your `formIpWildcard` function could just take an instance of that new rule context type as an argument.
</blockquote></details>

took out ip address, mask and prefix(needed by `formIpWildcard`) in a separate rule

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromSourceAddress.java, line 18 at r3](https://reviewable.io/reviews/batfish/batfish/1297#-LBvWI26E_y7B29brbaW:-LBvmDgF6SlTVK3M8DnE:b-tnkzih) ([raw file](https://github.com/batfish/batfish/blob/f8874f79397b092b5bf1bb8a7b5f4d899b2862c1/projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromSourceAddress.java#L18)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

Remove prefix from this class as well.
</blockquote></details>

thanks for catching that

---

*[projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java, line 1020 at r3](https://reviewable.io/reviews/batfish/batfish/1297#-LBvXUVX0j-BNV49yoXA:-LBvmGhVDygFOOM-PF3K:b-tnkzih) ([raw file](https://github.com/batfish/batfish/blob/f8874f79397b092b5bf1bb8a7b5f4d899b2862c1/projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java#L1020)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

nitpick: think this should be `whiteListedSrc`
</blockquote></details>

thanks for catching that

---

*[projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java, line 1038 at r3](https://reviewable.io/reviews/batfish/batfish/1297#-LBvXZPSD3Rkjb3QMu9I:-LBvmQtEDcJ1NSxemqga:b-tnkzih) ([raw file](https://github.com/batfish/batfish/blob/f8874f79397b092b5bf1bb8a7b5f4d899b2862c1/projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java#L1038)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

nitpick: think this should be `whiteListedSrc`
</blockquote></details>

thanks for catching that

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1297)*

**Comment by sfraint** [comment]
Reviewed 4 of 6 files at r4.
Review status: 10 of 12 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1297)*

**Comment by arifogel** [comment]
Reviewed 5 of 6 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1297)*

**Comment by arifogel** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1297#-:-LBw_jYV2AgaJz5D1yPp:bnfp4nl)*

**Pull request merged**
