### PR TITLE
CheckPoint: `RulebaseAction` object type

### PR DESCRIPTION
**Pull request by sfraint**
Add VS model support for `RulebaseAction` object type.

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7277)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @corinaminer and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/RulebaseAction.java, line 42 at r1](https://reviewable.io/reviews/batfish/batfish/7277#-Mi8v4Oz7782qIffavAo:-Mi8uIEXDdOXGkhAJqmt:bqvnnr5) ([raw file](https://github.com/batfish/batfish/blob/65e073ab8d9523fe50a810f3c3b999c56491d685/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/RulebaseAction.java#L42)):*
> ```Java
> 
>   /** Get the {@link Action} for this {@code RulebaseAction} object. */
>   public @Nonnull Action getAction() {
> ```

Is there any reason to put this here and not just in conversion code?

Even if you leave it here, why do it dynamically and not on construction?

Also an alternative is to use the pattern for deserializing globals, i.e. make `RulebaseAction` an abstract class, and have a single `JsonCreator`, equals, `hashCode`, `toString` in it, and choose subclass in the `JsonCreator` based on `action`.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7277)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @corinaminer and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/RulebaseAction.java, line 42 at r1](https://reviewable.io/reviews/batfish/batfish/7277#-Mi8v4Oz7782qIffavAo:-Mi8w2YT6_r3Leib7kNR:b-rr7xwh) ([raw file](https://github.com/batfish/batfish/blob/65e073ab8d9523fe50a810f3c3b999c56491d685/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/RulebaseAction.java#L42)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Is there any reason to put this here and not just in conversion code?

Even if you leave it here, why do it dynamically and not on construction?

Also an alternative is to use the pattern for deserializing globals, i.e. make `RulebaseAction` an abstract class, and have a single `JsonCreator`, equals, `hashCode`, `toString` in it, and choose subclass in the `JsonCreator` based on `action`.
</blockquote></details>

If you do the alternative, extend `NamedManagementObject` instead of `TypedManagementObject` so you can have different `@JsonTypeInfo`. Works better for visitor pattern if you end up using it, but using enum instead of classes is obviously equivalent.

**Review by arifogel — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7277)* status: all files reviewed, 1 unresolved discussion (waiting on @corinaminer and @sfraint)

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7277)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/RulebaseAction.java, line 42 at r1](https://reviewable.io/reviews/batfish/batfish/7277#-Mi8v4Oz7782qIffavAo:-Mi8w9fM9czoChJBxIlh:buxlgon) ([raw file](https://github.com/batfish/batfish/blob/65e073ab8d9523fe50a810f3c3b999c56491d685/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/RulebaseAction.java#L42)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

If you do the alternative, extend `NamedManagementObject` instead of `TypedManagementObject` so you can have different `@JsonTypeInfo`. Works better for visitor pattern if you end up using it, but using enum instead of classes is obviously equivalent.
</blockquote></details>

Now computing on construction

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7277)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

**Pull request merged**
