### PR TITLE
FortiOS: ignore policy uuid, service categories

### PR DESCRIPTION
**Pull request by dhalperi**

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 4 of 7 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6892)* status: 5 of 9 files reviewed, all discussions resolved (waiting on @corinaminer, @dhalperi, and @sfraint)

**Review by corinaminer — COMMENTED** [review]
> Reviewed 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6892)* status: all files reviewed, 2 unresolved discussions (waiting on @dhalperi and @sfraint)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_service.g4, line 57 at r4](https://reviewable.io/reviews/batfish/batfish/6892#-MXsj2KN6LjFt0qN6R-J:-MXsj2KN6LjFt0qN6R-K:bhww576) ([raw file](https://github.com/batfish/batfish/blob/9dc21a9f30f730ae3cbe9461e29108e4d9498bac/projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_service.g4#L57)):*
> ```ANTLR
> cfsc_set_udp_portrange: UDP_PORTRANGE value = service_port_ranges newline;
> 
> cfsc_set_visibility: VISIBILITY enable_or_disable newline;
> ```

If visibility and category are both going to be ignored by batfish forever, they could get bundled in a `cfsc_set_null` rule.
___
*[projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/firewall_policy, line 52 at r4](https://reviewable.io/reviews/batfish/batfish/6892#-MXsl0uc4EkB1CVPzCkS:-MXsl0uc4EkB1CVPzCkT:b-6plezz) ([raw file](https://github.com/batfish/batfish/blob/9dc21a9f30f730ae3cbe9461e29108e4d9498bac/projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/firewall_policy#L52)):*
> ```
>     next
>     edit ALL
>         set category "General"
> ```

why test categories here but visibility in `service_custom`?

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6892)* status: 3 of 5 files reviewed, all discussions resolved (waiting on @corinaminer and @sfraint)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_service.g4, line 57 at r4](https://reviewable.io/reviews/batfish/batfish/6892#-MXsj2KN6LjFt0qN6R-J:-MXsn01z4dW6lfV9YNPC:b-aegquv) ([raw file](https://github.com/batfish/batfish/blob/9dc21a9f30f730ae3cbe9461e29108e4d9498bac/projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_service.g4#L57)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

If visibility and category are both going to be ignored by batfish forever, they could get bundled in a `cfsc_set_null` rule.
</blockquote></details>

It's not obvious to me that either will be ignored forever. We might decide we need to extract and track refs to categories, for example. We might find (but I hope not) that invisible services are not defined...

Side note: in general, I avoid `_null` rules especially for simple grammar. They lead to laziness, unnecessary performance hits and bloat. E.g., both of these rules only take one token, whereas `null_rest_of_line` permits everything (slower, more permissive, larger file size).
___
*[projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/firewall_policy, line 52 at r4](https://reviewable.io/reviews/batfish/batfish/6892#-MXsl0uc4EkB1CVPzCkS:-MXso8mOCVmG7fON4Ms8:bqfooec) ([raw file](https://github.com/batfish/batfish/blob/9dc21a9f30f730ae3cbe9461e29108e4d9498bac/projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/firewall_policy#L52)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

why test categories here but visibility in `service_custom`?
</blockquote></details>

No reason, just had many test files open. Moved.

**Review by corinaminer — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6892#-:-MXswckG46g70P2MAbCl:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

**Pull request merged**
