### PR TITLE
Minor clean up of external bgp advertisement parsing

### PR DESCRIPTION
**Pull request by ratulm**
1/ separate json creator and constructor
2/ canonicalize node names (a slack user tripped up, the impetus of going into this file).

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6373)* status: all files reviewed, 2 unresolved discussions (waiting on @arifogel and @ratulm)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6373#-MKq5NSi2hPILF7MUBe8:-MKq5NSi2hPILF7MUBe9:b-zbisfl) (no related file):*
Test of canonicalization?

---
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpAdvertisement.java, line 275 at r1](https://reviewable.io/reviews/batfish/batfish/6373#-MKq5Dr83rNMVqXOqWSB:-MKq5Dr83rNMVqXOqWSC:bxo6hch) ([raw file](https://github.com/batfish/batfish/blob/ef240a805555e23c3be847397c30e8d0e4c23836/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpAdvertisement.java#L275)):*
> ```Java
> 
>   @JsonCreator
>   private BgpAdvertisement create(
> ```

this needs to be `static`, I think.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6373)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @arifogel, @dhalperi, and @ratulm)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpAdvertisement.java, line 276 at r2](https://reviewable.io/reviews/batfish/batfish/6373#-MKq8RUT97bjpwsTBqxd:-MKq8RUT97bjpwsTBqxe:b3843ln) ([raw file](https://github.com/batfish/batfish/blob/3c9c73d6b71fce9e61cc7e4dc9c642e82ff822dc/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpAdvertisement.java#L276)):*
> ```Java
>   @JsonCreator
>   private static BgpAdvertisement create(
>       @JsonProperty(PROP_TYPE) @Nonnull BgpAdvertisementType type,
> ```

All objects parameters must be `@Nullable`. Why else would you `checkNotNull`?
It's the constructor that should have them `@Nonnull`

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6373)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @arifogel, @dhalperi, and @ratulm)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpAdvertisement.java, line 276 at r2](https://reviewable.io/reviews/batfish/batfish/6373#-MKq8RUT97bjpwsTBqxd:-MKq8i_cCYLRXNal5FAQ:b-78n6jn) ([raw file](https://github.com/batfish/batfish/blob/3c9c73d6b71fce9e61cc7e4dc9c642e82ff822dc/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpAdvertisement.java#L276)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

All objects parameters must be `@Nullable`. Why else would you `checkNotNull`?
It's the constructor that should have them `@Nonnull`
</blockquote></details>

Also, don't have primitives (e.g. use `@Nullable Long`) unless you are comfortable with default values when missing.

**Review by arifogel — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6373)* status: all files reviewed, 2 unresolved discussions (waiting on @ratulm)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpAdvertisement.java, line 351 at r2](https://reviewable.io/reviews/batfish/batfish/6373#-MKq9BEU8Jpw2X8nT8pH:-MKq9BEU8Jpw2X8nT8pI:badgw3c) ([raw file](https://github.com/batfish/batfish/blob/3c9c73d6b71fce9e61cc7e4dc9c642e82ff822dc/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpAdvertisement.java#L351)):*
> ```Java
>     _nextHopIp = nextHopIp;
>     _srcNode = srcNode.toLowerCase(); // canonicalize node names
>     _srcVrf = srcVrf;
> ```

VRFs should be case-sensitive? Do we canonicalize elsewhere?

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6373)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpAdvertisement.java, line 276 at r2](https://reviewable.io/reviews/batfish/batfish/6373#-MKq8RUT97bjpwsTBqxd:-MKqAkev9iLlEtNFEoGJ:b-1px2t1) ([raw file](https://github.com/batfish/batfish/blob/3c9c73d6b71fce9e61cc7e4dc9c642e82ff822dc/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpAdvertisement.java#L276)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Also, don't have primitives (e.g. use `@Nullable Long`) unless you are comfortable with default values when missing.
</blockquote></details>

These annotations are very weird, Ari is right, but since this didn't change much in this PR it's okay to defer I think. We can fix in a follow-up.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpAdvertisement.java, line 351 at r2](https://reviewable.io/reviews/batfish/batfish/6373#-MKq9BEU8Jpw2X8nT8pH:-MKqAunJ9_KBOObcQ1c0:b6vcu2y) ([raw file](https://github.com/batfish/batfish/blob/3c9c73d6b71fce9e61cc7e4dc9c642e82ff822dc/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpAdvertisement.java#L351)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

VRFs should be case-sensitive? Do we canonicalize elsewhere?
</blockquote></details>

VRFs are case sensitive in our VI model, yes.

**Comment by dhalperi** [comment]
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpAdvertisement.java, line 306 at r2](https://reviewable.io/reviews/batfish/batfish/6373#-MKqBYvi-sjTDz-27AjF:-MKqBYvi-sjTDz-27AjG:bkycz7q) ([raw file](https://github.com/batfish/batfish/blob/3c9c73d6b71fce9e61cc7e4dc9c642e82ff822dc/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpAdvertisement.java#L306)):*
<details><summary><i alt="summary">Quoted 13 lines of code…</i></summary>

> ```
>     checkNotNull(type, "type must be specified for BgpAdvertisement");
>     checkNotNull(network, "network must be specified for BgpAdvertisement");
>     checkNotNull(nextHopIp, "nextHopIp must be specified for BgpAdvertisement");
>     checkNotNull(srcNode, "srcNode must be specified for BgpAdvertisement");
>     checkNotNull(srcVrf, "srcVrf must be specified for BgpAdvertisement");
>     checkNotNull(srcIp, "srcIp must be specified for BgpAdvertisement");
>     checkNotNull(dstNode, "dstNode must be specified for BgpAdvertisement");
>     checkNotNull(dstVrf, "dstVrf must be specified for BgpAdvertisement");
>     checkNotNull(dstIp, "dstIp must be specified for BgpAdvertisement");
>     checkNotNull(srcProtocol, "srcProtocol must be specified for BgpAdvertisement");
>     checkNotNull(originType, "originType must be specified for BgpAdvertisement");
>     checkNotNull(originatorIp, "originatorIp must be specified for BgpAdvertisement");
>     checkNotNull(asPath, "asPath must be specified for BgpAdvertisement");
> ```
</details>

FYI all of these will give 500 errors (server crash) instead of 400 errors (user bug) if the user sends bad data.

The pattern we usually use is: `checkArgument(foo != null, "Missing %s", PROP_FOO)`

**Review by arifogel — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6373)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
