### PR TITLE
Implement track method conjunction

### PR DESCRIPTION
**Pull request by arifogel**

### CODE REVIEW

**Review by progwriter — COMMENTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8673)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown and @dhalperi)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8673)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8673)* status: all files reviewed, 1 unresolved discussion (waiting on @anothermattbrown and @arifogel)

___
*[`projects/batfish/src/main/java/org/batfish/dataplane/ibdp/DataplaneTrackEvaluator.java` line 59 at r2](https://reviewable.io/reviews/batfish/batfish/8673#-NPdxBCv3zpgKGPSbQ8Z:-NPdxBCv3zpgKGPSbQ8_:bjmr2k3) ([raw file](https://github.com/batfish/batfish/blob/3830a2d80cd3b41480a437d37f2bad031efa182d/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/DataplaneTrackEvaluator.java#L59)):*
> ```Java
>   @Override
>   public Boolean visitTrackAll(TrackAll trackAll) {
>     return trackAll.getConjuncts().stream().allMatch(this::visit);
> ```

Will this be used in a hot path? If so, or maybe regardless, `for` loop would be much faster.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8673)* status: all files reviewed, 1 unresolved discussion (waiting on @anothermattbrown and @dhalperi)

___
*[`projects/batfish/src/main/java/org/batfish/dataplane/ibdp/DataplaneTrackEvaluator.java` line 59 at r2](https://reviewable.io/reviews/batfish/batfish/8673#-NPdxBCv3zpgKGPSbQ8Z:-NPdxRQmE6dvU0Tz0hDP:b1vkcqt) ([raw file](https://github.com/batfish/batfish/blob/3830a2d80cd3b41480a437d37f2bad031efa182d/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/DataplaneTrackEvaluator.java#L59)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Will this be used in a hot path? If so, or maybe regardless, `for` loop would be much faster.
</blockquote></details>

The intended use case is much less hot than the alternative (routing policy conjunction).
And in the intended case, each conjunction will be evaluated once per topology iteration. Nevertheless, easy to change, so done.

**Review by progwriter — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8673)* status: all files reviewed, 1 unresolved discussion (waiting on @anothermattbrown and @dhalperi)

**Pull request merged**
