### PR TITLE
Factor out maven repo in WORKSPACE, use more canonical antlr4 jar url

### PR DESCRIPTION
**Pull request by arifogel**

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
FYI, you may want to read more about `rules_jvm_external_deps` and Coursier at the `rules_jvm_external` repo, if you haven't already.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8579#-:-NFfd3TXAwOdJnAyD80G:b-sbsfb7)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel and @sfraint)

___
*[`WORKSPACE` line 39 at r1](https://reviewable.io/reviews/batfish/batfish/8579#-NFfcOT99OtJ3ZDTx1QI:-NFfcOT99OtJ3ZDTx1QJ:b665kfj) ([raw file](https://github.com/batfish/batfish/blob/d9604412820529c7da280a817d41839cc622da28/WORKSPACE#L39)):*
> ```Starlark
> load(":library_deps.bzl", "BATFISH_MAVEN_ARTIFACTS")
> 
> MAVEN_REPO = "https://repo1.maven.org/maven2"
> ```

`MAVEN_CENTRAL_REPOSITORY_URL` would probably be better.

Maven in general is just a tool; `repo1.maven.org` is usually called "Maven central". And the rest for the obvious naming clarity.



_Code quote:_
```Starlark
MAVEN_REPO
```

**Comment by arifogel** [comment]
*[`WORKSPACE` line 114 at r1](https://reviewable.io/reviews/batfish/batfish/8579#-NFgQ8N43IZyVmekx0HR:-NFgQ8N43IZyVmekx0HS:b-ejlefv) ([raw file](https://github.com/batfish/batfish/blob/d9604412820529c7da280a817d41839cc622da28/WORKSPACE#L114)):*
> ```Starlark
>     name = "antlr4_tool",
>     sha256 = "6852386d7975eff29171dae002cc223251510d35f291ae277948f381a7b380b4",
>     url = "%s/antlr/antlr4/4.7.2/antlr4-4.7.2-complete.jar" % MAVEN_REPO,
> ```

This URL is wrong. I'm guessing CI passed due to caching.

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8579)* status: all files reviewed, 2 unresolved discussions (waiting on @arifogel and @sfraint)

___
*[`WORKSPACE` line 114 at r1](https://reviewable.io/reviews/batfish/batfish/8579#-NFgQ8N43IZyVmekx0HR:-NFgR7m74UdPz00GfFV8:bhdg3e3) ([raw file](https://github.com/batfish/batfish/blob/d9604412820529c7da280a817d41839cc622da28/WORKSPACE#L114)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

This URL is wrong. I'm guessing CI passed due to caching.
</blockquote></details>

MAVEN_REPO is the wrong value here -- the original URLs were not the same.

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8579)* status: all files reviewed, 2 unresolved discussions (waiting on @arifogel and @sfraint)

___
*[`WORKSPACE` line 114 at r1](https://reviewable.io/reviews/batfish/batfish/8579#-NFgQ8N43IZyVmekx0HR:-NFgRP5l-kk3A6-yjgi-:bvwhjtn) ([raw file](https://github.com/batfish/batfish/blob/d9604412820529c7da280a817d41839cc622da28/WORKSPACE#L114)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

MAVEN_REPO is the wrong value here -- the original URLs were not the same.
</blockquote></details>

Ahh, catching up. Indeed..

**Comment by arifogel** [comment]
Interesting. We can fetch antlr4-complete via:
```
maven.artifact(group = "org.antlr", artifact = "antlr4", version = "4.7.2", classifier = "complete"),
```
in `library_deps.bzl`.

Then presumably, we could change things like this:
```
genrule(
    name = "cisco_generated",
    ...
    cmd = """
java -cp $(location @antlr4_tool//jar) \
   ...
    tools = ["@antlr4_tool//jar"],
)
```

To use `@maven//:something` instead of `@antlr4_tool//jar`. As an aside, all of those genrules really should be factored out into a macro in some`.bzl` file.

I will note that adding antlr4-complete to `library_deps.bzl` does toss a lot of dependencies into `maven_install.json`.  I'm not exactly sure why, if the complete jar already contains them.

For now, I'd say if we are going to touch antlr4-complete, we should start by refactoring and doing things right.
Closing.

**Pull request closed without merging**
