### PR TITLE
RoutesQuestion: Add more match criteria

### PR DESCRIPTION
**Pull request by ratulm**
For the main RIB only.

### CODE REVIEW

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 11 of 12 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7714)* status: all files reviewed, 4 unresolved discussions (waiting on @ratulm)

___
*[projects/question/src/main/java/org/batfish/question/routes/RoutesAnswererUtil.java, line 176 at r2](https://reviewable.io/reviews/batfish/batfish/7714#-Mot9MPnACmtADd0HiFK:-Mot9MPnACmtADd0HiFL:b-jc5xh4) ([raw file](https://github.com/batfish/batfish/blob/4bc76d6fcadb166e0926e599e10358c63fb55201/projects/question/src/main/java/org/batfish/question/routes/RoutesAnswererUtil.java#L176)):*
> ```
> mainRib
> ```
Is any of this specific to the main RIB? Can we rename to `rib`? 
___
*[projects/question/src/main/java/org/batfish/question/routes/RoutesAnswererUtil.java, line 202 at r2](https://reviewable.io/reviews/batfish/batfish/7714#-Mot97xP8o6cwV3OMRdu:-Mot97xP8o6cwV3OMRdv:b-hdzu06) ([raw file](https://github.com/batfish/batfish/blob/4bc76d6fcadb166e0926e599e10358c63fb55201/projects/question/src/main/java/org/batfish/question/routes/RoutesAnswererUtil.java#L202)):*
> ```
>       case LONGEST_PREFIX_MATCH: // handled separately
>       default:
>         throw new IllegalArgumentException("Illegal PrefixMatchType " + prefixMatchType);
> ```
To make our lives easier if/when we add more match types, I would distinguish between illegal (LPM) and unimplemented new match types. 
___
*[projects/question/src/main/java/org/batfish/question/routes/RoutesQuestion.java, line 60 at r2](https://reviewable.io/reviews/batfish/batfish/7714#-Mot9pIi4BI7Ka2Lv9w_:-Mot9pIi4BI7Ka2Lv9wa:b5s059s) ([raw file](https://github.com/batfish/batfish/blob/4bc76d6fcadb166e0926e599e10358c63fb55201/projects/question/src/main/java/org/batfish/question/routes/RoutesQuestion.java#L60)):*
> ```
> all prefixes equal or longer than the input network; can return multiple prefixes
> ```
only matches prefixes contained by the input network?
___
*[projects/question/src/main/java/org/batfish/question/routes/RoutesQuestion.java, line 62 at r2](https://reviewable.io/reviews/batfish/batfish/7714#-Mot9lOLDld1Tn7T5XOE:-Mot9lOLDld1Tn7T5XOF:b-1vbhyr) ([raw file](https://github.com/batfish/batfish/blob/4bc76d6fcadb166e0926e599e10358c63fb55201/projects/question/src/main/java/org/batfish/question/routes/RoutesQuestion.java#L62)):*
> ```
> all prefixes equal or shorter than the input network; can return multiple prefixes 
> ```
only matches prefixes that contain the input network?
___
*[projects/question/src/main/java/org/batfish/question/routes/RoutesQuestion.java, line 68 at r2](https://reviewable.io/reviews/batfish/batfish/7714#-Mot9yPkAsyLYJDeiivv:-Mot9yPl9K2yu86hymJh:bkxe06r) ([raw file](https://github.com/batfish/batfish/blob/4bc76d6fcadb166e0926e599e10358c63fb55201/projects/question/src/main/java/org/batfish/question/routes/RoutesQuestion.java#L68)):*
> ```
> only for main RIB
> ```
why doesn't this work for other RIBs?
___
*[projects/question/src/test/java/org/batfish/question/routes/RoutesAnswererUtilTest.java, line 945 at r2](https://reviewable.io/reviews/batfish/batfish/7714#-MotAIal266hklxybZ3u:-MotAIal266hklxybZ3v:b-s32l6x) ([raw file](https://github.com/batfish/batfish/blob/4bc76d6fcadb166e0926e599e10358c63fb55201/projects/question/src/test/java/org/batfish/question/routes/RoutesAnswererUtilTest.java#L945)):*
> ```
> testPrefixMatches() 
> ```
please add test cases for longer/shorter prefixes without containment

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7714)* status: all files reviewed, 3 unresolved discussions (waiting on @anothermattbrown)

___
*[projects/question/src/main/java/org/batfish/question/routes/RoutesAnswererUtil.java, line 176 at r2](https://reviewable.io/reviews/batfish/batfish/7714#-Mot9MPnACmtADd0HiFK:-MotKtCp5dt8sWjYaiZe:b63xlfd) ([raw file](https://github.com/batfish/batfish/blob/4bc76d6fcadb166e0926e599e10358c63fb55201/projects/question/src/main/java/org/batfish/question/routes/RoutesAnswererUtil.java#L176)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

> ```
> mainRib
> ```
Is any of this specific to the main RIB? Can we rename to `rib`? 
</blockquote></details>

This code is not specific. So, renamed. But it will be called only on the main RIB.
___
*[projects/question/src/main/java/org/batfish/question/routes/RoutesQuestion.java, line 60 at r2](https://reviewable.io/reviews/batfish/batfish/7714#-Mot9pIi4BI7Ka2Lv9w_:-MotLSXf6s5u6894pAjH:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/4bc76d6fcadb166e0926e599e10358c63fb55201/projects/question/src/main/java/org/batfish/question/routes/RoutesQuestion.java#L60)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

> ```
> all prefixes equal or longer than the input network; can return multiple prefixes
> ```
only matches prefixes contained by the input network?
</blockquote></details>

Done.
___
*[projects/question/src/main/java/org/batfish/question/routes/RoutesQuestion.java, line 62 at r2](https://reviewable.io/reviews/batfish/batfish/7714#-Mot9lOLDld1Tn7T5XOE:-MotLT7D38sGSaiG1rr5:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/4bc76d6fcadb166e0926e599e10358c63fb55201/projects/question/src/main/java/org/batfish/question/routes/RoutesQuestion.java#L62)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

> ```
> all prefixes equal or shorter than the input network; can return multiple prefixes 
> ```
only matches prefixes that contain the input network?
</blockquote></details>

Done.
___
*[projects/question/src/main/java/org/batfish/question/routes/RoutesQuestion.java, line 68 at r2](https://reviewable.io/reviews/batfish/batfish/7714#-Mot9yPkAsyLYJDeiivv:-MotLUnWDCveO6Hwgk37:bgbikyr) ([raw file](https://github.com/batfish/batfish/blob/4bc76d6fcadb166e0926e599e10358c63fb55201/projects/question/src/main/java/org/batfish/question/routes/RoutesQuestion.java#L68)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

> ```
> only for main RIB
> ```
why doesn't this work for other RIBs?
</blockquote></details>

FWICT, protocol RIBs do not appear to be stored as RIB but as set of routes. So, LPM on that is extra work.

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 2 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7714)* status: 9 of 13 files reviewed, 2 unresolved discussions (waiting on @anothermattbrown and @ratulm)

___
*[projects/question/src/main/java/org/batfish/question/routes/RoutesQuestion.java, line 68 at r2](https://reviewable.io/reviews/batfish/batfish/7714#-Mot9yPkAsyLYJDeiivv:-MotV2JcD9mcpydEb8DQ:b-uzjjih) ([raw file](https://github.com/batfish/batfish/blob/4bc76d6fcadb166e0926e599e10358c63fb55201/projects/question/src/main/java/org/batfish/question/routes/RoutesQuestion.java#L68)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

FWICT, protocol RIBs do not appear to be stored as RIB but as set of routes. So, LPM on that is extra work. 
</blockquote></details>

it should be easy/efficient enough to create a `PrefixTrieMultiMap` containing the matching routes and then call `longestPrefixMatch(Ip address, int maxPrefixLength)`.

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 1 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7714)* status: 10 of 13 files reviewed, 1 unresolved discussion (waiting on @anothermattbrown and @ratulm)

___
*[projects/question/src/main/java/org/batfish/question/routes/RoutesQuestion.java, line 68 at r2](https://reviewable.io/reviews/batfish/batfish/7714#-Mot9yPkAsyLYJDeiivv:-MotVvAm-zUmnPVcmaYE:bnaqngz) ([raw file](https://github.com/batfish/batfish/blob/4bc76d6fcadb166e0926e599e10358c63fb55201/projects/question/src/main/java/org/batfish/question/routes/RoutesQuestion.java#L68)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

it should be easy/efficient enough to create a `PrefixTrieMultiMap` containing the matching routes and then call `longestPrefixMatch(Ip address, int maxPrefixLength)`. 
</blockquote></details>

or just do it directly -- find the max length of matching networks, then do exact match. doesn't seem like that much extra work

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7714)* status: 10 of 13 files reviewed, 1 unresolved discussion (waiting on @anothermattbrown)

___
*[projects/question/src/main/java/org/batfish/question/routes/RoutesQuestion.java, line 68 at r2](https://reviewable.io/reviews/batfish/batfish/7714#-Mot9yPkAsyLYJDeiivv:-MotWbj39f4C48xH8mnD:bu04434) ([raw file](https://github.com/batfish/batfish/blob/4bc76d6fcadb166e0926e599e10358c63fb55201/projects/question/src/main/java/org/batfish/question/routes/RoutesQuestion.java#L68)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

or just do it directly -- find the max length of matching networks, then do exact match. doesn't seem like that much extra work
</blockquote></details>

sure, on it.

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 2 of 6 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7714)* status: all files reviewed, 1 unresolved discussion (waiting on @anothermattbrown)

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 10 of 10 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7714)* status: all files reviewed, 5 unresolved discussions (waiting on @ratulm)

___
*[projects/question/src/main/java/org/batfish/question/routes/RoutesAnswererUtil.java, line 687 at r3](https://reviewable.io/reviews/batfish/batfish/7714#-Mouqg3q7aSS0yzd1Fsu:-Mouqg3q7aSS0yzd1Fsv:bbjldyb) ([raw file](https://github.com/batfish/batfish/blob/94d2095ad1c7f836283b197e9d97bcd39325fda2/projects/question/src/main/java/org/batfish/question/routes/RoutesAnswererUtil.java#L687)):*
> ```
> BgpRouteStatus.
> ```
why remove qualification here but not elsewhere?
___
*[projects/question/src/main/java/org/batfish/question/routes/RoutesAnswererUtil.java, line 305 at r5](https://reviewable.io/reviews/batfish/batfish/7714#-MoupzFz5Nu6HbEaX16H:-MoupzFz5Nu6HbEaX16I:b-or3ffh) ([raw file](https://github.com/batfish/batfish/blob/ada267a98f3e455ca9531570b0781fa4a82c6de0/projects/question/src/main/java/org/batfish/question/routes/RoutesAnswererUtil.java#L305)):*
> ```
>    * <p>It the prefix match type is LONGEST_PREFIX_MATCH, the returned prefix is decided based on
>    * LPM on the best routes table.
> ```
this is based on the invariant that the backup table won't contain any longer prefixes (because they would not be backing anything up)? would be helpful to document that.
___
*[projects/question/src/main/java/org/batfish/question/routes/RoutesAnswererUtil.java, line 334 at r5](https://reviewable.io/reviews/batfish/batfish/7714#-MouqPvDDIsClJlrgauf:-MouqPvDDIsClJlrgaug:b-h7x9t2) ([raw file](https://github.com/batfish/batfish/blob/ada267a98f3e455ca9531570b0781fa4a82c6de0/projects/question/src/main/java/org/batfish/question/routes/RoutesAnswererUtil.java#L334)):*
> ```
> PrefixMatchType.EXACT
> ```
why hard-code exact here?
___
*[projects/question/src/test/java/org/batfish/question/routes/RoutesAnswererUtilTest.java, line 1159 at r5](https://reviewable.io/reviews/batfish/batfish/7714#-MoutGkl-fhARGjBI3wO:-MoutGkl-fhARGjBI3wP:b-gaucwz) ([raw file](https://github.com/batfish/batfish/blob/ada267a98f3e455ca9531570b0781fa4a82c6de0/projects/question/src/test/java/org/batfish/question/routes/RoutesAnswererUtilTest.java#L1159)):*
> ```
> EXACT
> ```
this block says it's testing LPM
___
*[projects/question/src/test/java/org/batfish/question/routes/RoutesAnswererUtilTest.java, line 1194 at r5](https://reviewable.io/reviews/batfish/batfish/7714#-MoutVFH7uKmBU9HztBV:-MoutVFH7uKmBU9HztBW:b-rg41s6) ([raw file](https://github.com/batfish/batfish/blob/ada267a98f3e455ca9531570b0781fa4a82c6de0/projects/question/src/test/java/org/batfish/question/routes/RoutesAnswererUtilTest.java#L1194)):*
> ```
> multi-prefix matcher
> ```
for LONGER_PREFIXES, we should test that equal prefixes are included and shorter prefixes are excluded (and similarly for shorter).

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7714)* status: all files reviewed, 5 unresolved discussions (waiting on @anothermattbrown)

___
*[projects/question/src/main/java/org/batfish/question/routes/RoutesAnswererUtil.java, line 687 at r3](https://reviewable.io/reviews/batfish/batfish/7714#-Mouqg3q7aSS0yzd1Fsu:-Mouv_QM7BeqPwH7tTse:b-ov0kvn) ([raw file](https://github.com/batfish/batfish/blob/94d2095ad1c7f836283b197e9d97bcd39325fda2/projects/question/src/main/java/org/batfish/question/routes/RoutesAnswererUtil.java#L687)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

> ```
> BgpRouteStatus.
> ```
why remove qualification here but not elsewhere?
</blockquote></details>

IDE ... 
___
*[projects/question/src/main/java/org/batfish/question/routes/RoutesAnswererUtil.java, line 305 at r5](https://reviewable.io/reviews/batfish/batfish/7714#-MoupzFz5Nu6HbEaX16H:-MouvODs4cDWl2ZDFybu:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/ada267a98f3e455ca9531570b0781fa4a82c6de0/projects/question/src/main/java/org/batfish/question/routes/RoutesAnswererUtil.java#L305)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

> ```
>    * <p>It the prefix match type is LONGEST_PREFIX_MATCH, the returned prefix is decided based on
>    * LPM on the best routes table.
> ```
this is based on the invariant that the backup table won't contain any longer prefixes (because they would not be backing anything up)? would be helpful to document that.
</blockquote></details>

Done.
___
*[projects/question/src/main/java/org/batfish/question/routes/RoutesAnswererUtil.java, line 334 at r5](https://reviewable.io/reviews/batfish/batfish/7714#-MouqPvDDIsClJlrgauf:-MouvSncEgPQXkItc02Y:bvn3hlq) ([raw file](https://github.com/batfish/batfish/blob/ada267a98f3e455ca9531570b0781fa4a82c6de0/projects/question/src/main/java/org/batfish/question/routes/RoutesAnswererUtil.java#L334)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

> ```
> PrefixMatchType.EXACT
> ```
why hard-code exact here?
</blockquote></details>

ooooh. BUG! 
___
*[projects/question/src/test/java/org/batfish/question/routes/RoutesAnswererUtilTest.java, line 1159 at r5](https://reviewable.io/reviews/batfish/batfish/7714#-MoutGkl-fhARGjBI3wO:-MouvlRc40izPWt1-MwQ:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/ada267a98f3e455ca9531570b0781fa4a82c6de0/projects/question/src/test/java/org/batfish/question/routes/RoutesAnswererUtilTest.java#L1159)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

> ```
> EXACT
> ```
this block says it's testing LPM
</blockquote></details>

Done.
___
*[projects/question/src/test/java/org/batfish/question/routes/RoutesAnswererUtilTest.java, line 1194 at r5](https://reviewable.io/reviews/batfish/batfish/7714#-MoutVFH7uKmBU9HztBV:-Mouvoc7BiXY6ns_B8Ue:b-ewg3rq) ([raw file](https://github.com/batfish/batfish/blob/ada267a98f3e455ca9531570b0781fa4a82c6de0/projects/question/src/test/java/org/batfish/question/routes/RoutesAnswererUtilTest.java#L1194)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

> ```
> multi-prefix matcher
> ```
for LONGER_PREFIXES, we should test that equal prefixes are included and shorter prefixes are excluded (and similarly for shorter).
</blockquote></details>

That testing is there in `testPrefixMatches`. The function being tested here delegates to `prefixMatches`. You see value in doing it here too?

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7714)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ratulm)

___
*[projects/question/src/main/java/org/batfish/question/routes/RoutesAnswererUtil.java, line 324 at r6](https://reviewable.io/reviews/batfish/batfish/7714#-Mov22Mb9sE5p9v5xn6w:-Mov22McA7Z9Cq57HuEq:b-ifh3mi) ([raw file](https://github.com/batfish/batfish/blob/72f68da290e96aae6fa0ec7a2d7870926ed8fbf0/projects/question/src/main/java/org/batfish/question/routes/RoutesAnswererUtil.java#L324)):*
> ```
>    * A consequence of these semantics is that if the user asks only for backup routes (via
>    * routeStatus), nothing may be reported in cases where the LPM-based matching on the best table
>    * leads to prefix P1 but P1 is not present in the backup table.
> ```
This seems like a weird UX, though I'm not sure what the use case of LPM matching over only backup routes would be...
___
*[projects/question/src/test/java/org/batfish/question/routes/RoutesAnswererUtilTest.java, line 1194 at r5](https://reviewable.io/reviews/batfish/batfish/7714#-MoutVFH7uKmBU9HztBV:-Mov2jlI3h1sLZmLYPZh:bctnvas) ([raw file](https://github.com/batfish/batfish/blob/ada267a98f3e455ca9531570b0781fa4a82c6de0/projects/question/src/test/java/org/batfish/question/routes/RoutesAnswererUtilTest.java#L1194)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

That testing is there in `testPrefixMatches`. The function being tested here delegates to `prefixMatches`. You see value in doing it here too?
</blockquote></details>

nope that sounds right

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7714)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ratulm)

___
*[projects/question/src/main/java/org/batfish/question/routes/RoutesAnswererUtil.java, line 324 at r6](https://reviewable.io/reviews/batfish/batfish/7714#-Mov22Mb9sE5p9v5xn6w:-MovTz1iCiIvDvPTVCVQ:b-3xw4kx) ([raw file](https://github.com/batfish/batfish/blob/72f68da290e96aae6fa0ec7a2d7870926ed8fbf0/projects/question/src/main/java/org/batfish/question/routes/RoutesAnswererUtil.java#L324)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

> ```
>    * A consequence of these semantics is that if the user asks only for backup routes (via
>    * routeStatus), nothing may be reported in cases where the LPM-based matching on the best table
>    * leads to prefix P1 but P1 is not present in the backup table.
> ```
This seems like a weird UX, though I'm not sure what the use case of LPM matching over only backup routes would be...
</blockquote></details>

FWIW, a similar issue is happening with protocol filters: do LPM first, and then filter. This semantics is consistent with what is happening there. 

We can revisit if it seems counter-intuitive to users. Need to lookup what routers do as well.

**Review by ratulm — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7714)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ratulm)

**Pull request merged**
