### PR TITLE
NodeSpecifierFactory and NameRegexNodeSpecifier

### PR DESCRIPTION
**Pull request by anothermattbrown**
Previously added NodeSpecifier, but was creating them directly. This PR introduces the NodeSpecifierFactory, which provides a pluggable API for adding new ways of building NodeSpecifiers. Also added a new NodeSpecifier using regex on node names, and a factory for it.

### CODE REVIEW

**Comment by anothermattbrown** [comment]
Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1623#-LEVDUjG33zCkwg0iRes:-LEVDUjG33zCkwg0iRet:b-hy1qsa) (no related file):*
Don't merge until base is master.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1623)*

**Comment by dhalperi** [comment]
Reviewed 3 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/specifier/NameRegexNodeSpecifierFactory.java, line 18 at r2](https://reviewable.io/reviews/batfish/batfish/1623#-LEXBvIg3tkiy_vRwwAk:-LEXBvIg3tkiy_vRwwAl:b7dcnoz) ([raw file](https://github.com/batfish/batfish/blob/adcfb772fe0a27284544f3fd3193df2227c1cca2/projects/batfish-common-protocol/src/main/java/org/batfish/specifier/NameRegexNodeSpecifierFactory.java#L18)):*
> ```
> Preconditions.checkArgumen
> ```
normally this is static imported. just a convention.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1623)*

**Comment by dhalperi** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed, 1 unresolved discussion (waiting on @anothermattbrown)

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1623)*

**Comment by anothermattbrown** [comment]
Review status: :shipit: complete! all files reviewed, all discussions resolved

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1623#-LEVDUjG33zCkwg0iRes:-LEkP3PPDcidOkqq0TDh:bb6un1j) (no related file):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

Don't merge until base is master.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1623)*

**Comment by dhalperi** [comment]
Reviewed 2 of 2 files at r4.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1623)*

**Pull request merged**
