### PR TITLE
Speed up Layer 2 topology computation

### PR DESCRIPTION
**Pull request by progwriter**
Compute the topology vertices based on ranges of VLANs instead of
individual VLANs. This trims a pretty significant constant factor off of
the complexity and lets L2 computation scale to larger networks.

As an additional optimization, I also removed Comparable implementation
from L2 nodes and edges

### CODE REVIEW

**Review by progwriter — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6505)* status: 0 of 11 files reviewed, all discussions resolved

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/Layer2Edge.java, line 91 at r1](https://reviewable.io/reviews/batfish/batfish/6505#-MOV4XMkD6TxcYD61QSy:-MOV4XMkD6TxcYD61QSz:b29oibd) ([raw file](https://github.com/batfish/batfish/blob/2c06e0219e4fbbbb740e0b3bc096e5bfc93510d3/projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/Layer2Edge.java#L91)):*
> ```Java
> 
>   @JsonProperty(PROP_ENCAPSULATED_VLAN_ID)
>   public @Nullable Integer getEncapsulatedVlanId() {
> ```

this was not used anywhere so removed for simplicity
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/Layer2Topology.java, line 130 at r1](https://reviewable.io/reviews/batfish/batfish/6505#-MOV4cb207JOWobPj2eM:-MOV4cb207JOWobPj2eN:b-w9twoq) ([raw file](https://github.com/batfish/batfish/blob/9a5af25362886b10998ea9e1c6a889ed7eaead68/projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/Layer2Topology.java#L130)):*
> ```Java
>                   }
>                   Layer2Node repr =
>                       domain.stream().max(Comparator.comparingInt(Layer2Node::hashCode)).get();
> ```

since hashcodes are cached, figured this should be faster, and not affect correctness
___
*[projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/TopologyUtilTest.java, line 339 at r1](https://reviewable.io/reviews/batfish/batfish/6505#-MOV4m9z2r5dtiFAKC3M:-MOV4m9z2r5dtiFAKC3N:bglrtbb) ([raw file](https://github.com/batfish/batfish/blob/2c06e0219e4fbbbb740e0b3bc096e5bfc93510d3/projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/TopologyUtilTest.java#L339)):*
> ```Java
>       String c3Name = "c3";
>       String c3i1Name = "c3i1";
>       Configuration c3 = _cb.setHostname(c3Name).build();
> ```

had to move this up to initialization of the test, otherwise missing it from the `configs`, would cause an NPE, given new code

**Comment by dhalperi** [comment]
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TopologyUtil.java, line 101 at r2](https://reviewable.io/reviews/batfish/batfish/6505#-MOXIrhyCxSfMlXVFHza:-MOXIrhyCxSfMlXVFHzb:b-xuyekf) ([raw file](https://github.com/batfish/batfish/blob/d9af57de340c4be117e49313496bebdc819b9f15/projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TopologyUtil.java#L101)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>         edges.accept(
>             new Layer2Edge(
>                 node1,
>                 node1Ranges.getRange(i1.getNativeVlan()),
>                 node2,
>                 node2Ranges.getRange(i1.getNativeVlan())));
> ```
</details>


Not sure I understand how this works. Shouldn't it be `i2`'s native vlan?

That is, an untagged frame sent by i1 and received by i2 will be on an `i2`-configuration-dependent vlan. (These not agreeing is a common source of leaks/bugs)

**Review by progwriter — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6505)* status: 0 of 11 files reviewed, all discussions resolved (waiting on @dhalperi)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TopologyUtil.java, line 101 at r2](https://reviewable.io/reviews/batfish/batfish/6505#-MOXIrhyCxSfMlXVFHza:-MOXlBtBBx4NuDmLLkrA:b-53g7h3) ([raw file](https://github.com/batfish/batfish/blob/d9af57de340c4be117e49313496bebdc819b9f15/projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TopologyUtil.java#L101)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
>         edges.accept(
>             new Layer2Edge(
>                 node1,
>                 node1Ranges.getRange(i1.getNativeVlan()),
>                 node2,
>                 node2Ranges.getRange(i1.getNativeVlan())));
> ```

Not sure I understand how this works. Shouldn't it be `i2`'s native vlan?

That is, an untagged frame sent by i1 and received by i2 will be on an `i2`-configuration-dependent vlan. (These not agreeing is a common source of leaks/bugs)
</blockquote></details>

yeah, i was just rewriting existing code, but yeah, it is possible to misalign native vlans and get unexpected behavior.

**Review by arifogel — COMMENTED** [review]
> Reviewed 9 of 11 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6505)* status: all files reviewed, 4 unresolved discussions (waiting on @progwriter)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/Layer2Node.java, line 53 at r3](https://reviewable.io/reviews/batfish/batfish/6505#-MOXnxHb-5LTpf1eb6j7:-MOXnxHb-5LTpf1eb6j8:bml1gzk) ([raw file](https://github.com/batfish/batfish/blob/437bb0942dc62377fd4788c480fa058ac681e338/projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/Layer2Node.java#L53)):*
> ```Java
>   }
> 
>   public Layer2Node(@Nonnull String hostname, @Nonnull String interfaceName, int vlan) {
> ```

I assume remaining usages of this should not be refactored into ranges?
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/Layer2Topology.java, line 130 at r1](https://reviewable.io/reviews/batfish/batfish/6505#-MOV4cb207JOWobPj2eM:-MOXoPbqADZ1_3Yh0fTh:b-q1gw1m) ([raw file](https://github.com/batfish/batfish/blob/9a5af25362886b10998ea9e1c6a889ed7eaead68/projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/Layer2Topology.java#L130)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

since hashcodes are cached, figured this should be faster, and not affect correctness
</blockquote></details>

you lose stability here, but that almost certainly doesn't matter.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TopologyUtil.java, line 92 at r3](https://reviewable.io/reviews/batfish/batfish/6505#-MOXpBuJB0-VY7AZCYcc:-MOXpBuJB0-VY7AZCYcd:bptmxa4) ([raw file](https://github.com/batfish/batfish/blob/437bb0942dc62377fd4788c480fa058ac681e338/projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TopologyUtil.java#L92)):*
> ```Java
>       for (Range<Integer> sharedRange : node1Ranges.intersect(i1.getName(), i2.getAllowedVlans())) {
>         // This frame will be tagged by i1 and we can directly check whether i2 allows.
>         edges.accept(new Layer2Edge(node1, sharedRange, node2, sharedRange));
> ```

Could this improperly add incompatible native vlans?
Let's say device 1 has untagged native vlan 5, and device 2 has untagged native vlan 6. Would the edge improperly include both 5 and 6 in the range?

This is part of a larger worry about the removal of encapsulationVlanId from the edges.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TopologyUtil.java, line 273 at r3](https://reviewable.io/reviews/batfish/batfish/6505#-MOXvXQc-9bMt-P8tWM2:-MOXvXQc-9bMt-P8tWM3:b-scojye) ([raw file](https://github.com/batfish/batfish/blob/437bb0942dc62377fd4788c480fa058ac681e338/projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TopologyUtil.java#L273)):*
> ```Java
>         .asMap()
>         .forEach(
>             (vlanRange, interfaceNames) -> {
> ```

To confirm, all the `vlanRange`s iterated over here disjoint?
___
*[projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/InterfacesByVlanRangeTest.java, line 75 at r3](https://reviewable.io/reviews/batfish/batfish/6505#-MOXxsm7-CbRCWN_oTcR:-MOXxsm7-CbRCWN_oTcS:b-zamf5d) ([raw file](https://github.com/batfish/batfish/blob/437bb0942dc62377fd4788c480fa058ac681e338/projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/InterfacesByVlanRangeTest.java#L75)):*
> ```Java
>             hasEntry(Range.open(10, 20), set3),
>             hasEntry(Range.closed(20, 25), ImmutableSet.of("iface2", "iface3")),
>             hasEntry(Range.openClosed(25, 30), set2)));
> ```

Is it just me, or are these tests 3rd-party-implementation-specific wrt range types? That is, they seem syntactic.
I mean, conceptually, these could all be closed ranges since this is a discrete domain.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 4 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6505)* status: all files reviewed, 5 unresolved discussions (waiting on @progwriter)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/InterfacesByVlanRange.java, line 99 at r2](https://reviewable.io/reviews/batfish/batfish/6505#-MOXfof7Dql2tVwJyznj:-MOXfof7Dql2tVwJyznk:b-t9iqgn) ([raw file](https://github.com/batfish/batfish/blob/d9af57de340c4be117e49313496bebdc819b9f15/projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/InterfacesByVlanRange.java#L99)):*
> ```Java
>    */
>   @Nonnull
>   public Set<Range<Integer>> intersect(String interfaceName, IntegerSpace otherVlanSpace) {
> ```

I don't see how this will handle untagged vlans gracefully.  Maybe by removing untagged vlans at caller and handling them manually?

**Comment by dhalperi** [comment]
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TopologyUtil.java, line 91 at r3](https://reviewable.io/reviews/batfish/batfish/6505#-MOY-Ehl-XzUG1Fnf_BO:-MOY-EhmB9dZWc8ZC8fF:b4vvqn6) ([raw file](https://github.com/batfish/batfish/blob/437bb0942dc62377fd4788c480fa058ac681e338/projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TopologyUtil.java#L91)):*
> ```
> This frame will be tagged by i1
> ```
Seems like to make this part of the comment accurate we have to remove i1's native vlan

**Review by progwriter — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6505)* status: all files reviewed, 3 unresolved discussions (waiting on @arifogel and @dhalperi)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/InterfacesByVlanRange.java, line 99 at r2](https://reviewable.io/reviews/batfish/batfish/6505#-MOXfof7Dql2tVwJyznj:-MOYpvYL9ArimWp3zPzv:bhng2ae) ([raw file](https://github.com/batfish/batfish/blob/d9af57de340c4be117e49313496bebdc819b9f15/projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/InterfacesByVlanRange.java#L99)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I don't see how this will handle untagged vlans gracefully.  Maybe by removing untagged vlans at caller and handling them manually?
</blockquote></details>

See new behavior at caller, treating native vlans as singleton callers
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/Layer2Node.java, line 53 at r3](https://reviewable.io/reviews/batfish/batfish/6505#-MOXnxHb-5LTpf1eb6j7:-MOYh8FY0A5MGR0inPB3:b-jp377f) ([raw file](https://github.com/batfish/batfish/blob/437bb0942dc62377fd4788c480fa058ac681e338/projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/Layer2Node.java#L53)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

I assume remaining usages of this should not be refactored into ranges?
</blockquote></details>

correct
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TopologyUtil.java, line 91 at r3](https://reviewable.io/reviews/batfish/batfish/6505#-MOY-Ehl-XzUG1Fnf_BO:-MOYpryO1DUl6EbBGmxe:bfix1oa) ([raw file](https://github.com/batfish/batfish/blob/437bb0942dc62377fd4788c480fa058ac681e338/projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TopologyUtil.java#L91)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> This frame will be tagged by i1
> ```
Seems like to make this part of the comment accurate we have to remove i1's native vlan
</blockquote></details>

ok, I think fixed
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TopologyUtil.java, line 92 at r3](https://reviewable.io/reviews/batfish/batfish/6505#-MOXpBuJB0-VY7AZCYcc:-MOYq3oL6o91DFihVo5C:b-zaq2h9) ([raw file](https://github.com/batfish/batfish/blob/437bb0942dc62377fd4788c480fa058ac681e338/projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TopologyUtil.java#L92)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Could this improperly add incompatible native vlans?
Let's say device 1 has untagged native vlan 5, and device 2 has untagged native vlan 6. Would the edge improperly include both 5 and 6 in the range?

This is part of a larger worry about the removal of encapsulationVlanId from the edges.
</blockquote></details>

see updated version, where native vlans are treated as singleton ranges.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TopologyUtil.java, line 273 at r3](https://reviewable.io/reviews/batfish/batfish/6505#-MOXvXQc-9bMt-P8tWM2:-MOYhClS8dyE7kJAxMcp:b2nign6) ([raw file](https://github.com/batfish/batfish/blob/437bb0942dc62377fd4788c480fa058ac681e338/projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TopologyUtil.java#L273)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

To confirm, all the `vlanRange`s iterated over here disjoint?
</blockquote></details>

yes
___
*[projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/InterfacesByVlanRangeTest.java, line 75 at r3](https://reviewable.io/reviews/batfish/batfish/6505#-MOXxsm7-CbRCWN_oTcR:-MOYhGlV69qEBwjafQ8i:b-vtrt41) ([raw file](https://github.com/batfish/batfish/blob/437bb0942dc62377fd4788c480fa058ac681e338/projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/InterfacesByVlanRangeTest.java#L75)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Is it just me, or are these tests 3rd-party-implementation-specific wrt range types? That is, they seem syntactic.
I mean, conceptually, these could all be closed ranges since this is a discrete domain.
</blockquote></details>

technically, we could canonicalize them, but this doesn't affect correctness

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6505)* status: 9 of 11 files reviewed, 4 unresolved discussions (waiting on @arifogel, @dhalperi, and @progwriter)

___
*[projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/TopologyUtilTest.java, line 899 at r4](https://reviewable.io/reviews/batfish/batfish/6505#-MOYtMcS2Baa_RZavKGq:-MOYtMcS2Baa_RZavKGr:bfjrhyd) ([raw file](https://github.com/batfish/batfish/blob/2a3469d456f6c7732fbd4f92ab6a5e12f1cd80b9/projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/TopologyUtilTest.java#L899)):*
> ```Java
>    * Even though two interfaces are mis-configured (native VLANs differ) we should still make an
>    * edge to accurately model the mis-configuration that is present. Access ports will end up in the
>    * saem broadcast domain even though one is vlan 5 on n1 and another vlan 6 on n2
> ```

typo: saem

**Review by arifogel — COMMENTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6505)* status: all files reviewed, 2 unresolved discussions (waiting on @dhalperi and @progwriter)

**Review by progwriter — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6505)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @arifogel and @dhalperi)

___
*[projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/TopologyUtilTest.java, line 899 at r4](https://reviewable.io/reviews/batfish/batfish/6505#-MOYtMcS2Baa_RZavKGq:-MOYvB815bBp6Sw6a70G:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/2a3469d456f6c7732fbd4f92ab6a5e12f1cd80b9/projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/TopologyUtilTest.java#L899)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

typo: saem
</blockquote></details>

done

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6505)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi)

**Pull request merged**
