### PR TITLE
Use Location and IpSpace specifiers in traceroute2 question

### LINKED ISSUE #1650: New traceroute
In branch traceroute2, I moved the old traceroute code and had it generate tables. But now that we are touching it, it could use further modernization to make it consistent with the new reachability stuff. 

- [ ] Provide more control over how/where the packet is injected (e.g., ingress interface should be specifiable).
- [ ] Simplify how those controls are articulated (e.g., use the new specifiers)

[nice to have]

- [ ] If the specifiers correspond to multiple starting points or multiple destination addresses, do multiple traceroutes

@anothermattbrown - Would you be up for this?

### PR DESCRIPTION
**Pull request by anothermattbrown**
Fixes #1650:
- Added `sourceLocationSpecifierFactory` and `sourceIpSpaceSpecifierFactory` to support multiple ways of specifying source locations and ip spaces.
  - Default location specifier is `FlexibleLocationSpecifierFactory`
  - Default IpSpace specifier is `InferFromLocationIpSpaceSpecifierFactory`
- Generates a `Flow` for each specified location, and returns traces for each flow.
  - The flow is assigned a representative Ip in the specified IpSpace.

### CODE REVIEW

**Comment by ratulm** [comment]
This smells right to me but answers to the questions in the command and ref files will help me review the code.

---

Review status: 0 of 7 files reviewed, 5 unresolved discussions (waiting on @anothermattbrown and @ratulm)

---

*[tests/basic/commands, line 38 at r1](https://reviewable.io/reviews/batfish/batfish/1742#-LFt0CX1B5QmNUSv5ixl:-LFt0CX1B5QmNUSv5ixm:bqfa1mm) ([raw file](https://github.com/batfish/batfish/blob/f00408a9b8152a2346fc284aa548c78d4d3fb8dc/tests/basic/commands#L38)):*
> ```
> test tests/basic/traceroute-1-2-ignoreAcls.ref get traceroute ingressNode="as1core1", dst="host1", ignoreAcls=true
> test tests/basic/traceroute-2-1.ref get traceroute ingressNode="host2", dst="1.0.1.1"
> test tests/basic/traceroute2-1-2.ref get traceroute2 sourceLocation="node=as1core1", dst="host1"
> ```

1) What is the semantics of this command? Judging from the ref, it is not identical to the command it edited.

---

*[tests/basic/commands, line 39 at r1](https://reviewable.io/reviews/batfish/batfish/1742#-LFt0VRt-y4bwUTa0v9h:-LFt0VRt-y4bwUTa0v9i:b-2vsp08) ([raw file](https://github.com/batfish/batfish/blob/f00408a9b8152a2346fc284aa548c78d4d3fb8dc/tests/basic/commands#L39)):*
> ```
> test tests/basic/traceroute-2-1.ref get traceroute ingressNode="host2", dst="1.0.1.1"
> test tests/basic/traceroute2-1-2.ref get traceroute2 sourceLocation="node=as1core1", dst="host1"
> test tests/basic/traceroute2-2-1.ref get traceroute2 sourceLocationSpecifierFactory="NodeNameRegexInterfaceLocationSpecifierFactory", sourceLocation="host2", dst="1.0.1.1"
> ```

Why not make NodeNameRegexInterfaceLocationSpecifierFactory the default in the question? New users will want to always use simple node names as parameter values, and then get fancy if needed.

---

*[tests/basic/traceroute2-1-2.ref, line 72 at r1](https://reviewable.io/reviews/batfish/batfish/1742#-LFt-E6eAJ392ETSgdE0:-LFt-E6eAJ392ETSgdE1:b72bji0) ([raw file](https://github.com/batfish/batfish/blob/f00408a9b8152a2346fc284aa548c78d4d3fb8dc/tests/basic/traceroute2-1-2.ref#L72)):*
> ```
>           "ipProtocol" : "IP",
>           "packetLength" : 0,
>           "srcIp" : "0.0.0.0",
> ```

Why is the srcIp 0.0.0.0 ?

---

*[tests/basic/traceroute2-1-2.ref, line 99 at r1](https://reviewable.io/reviews/batfish/batfish/1742#-LFsypfv8AaBF3Aaq59q:-LFsypfv8AaBF3Aaq59r:b-bnwanh) ([raw file](https://github.com/batfish/batfish/blob/f00408a9b8152a2346fc284aa548c78d4d3fb8dc/tests/basic/traceroute2-1-2.ref#L99)):*
> ```
>                   "node2" : "as1core1",
>                   "node2interface" : "Loopback0"
>                 }
> ```

This is a "fake" hop?

---

*[tests/basic/traceroute2-1-2.ref, line 1520 at r1](https://reviewable.io/reviews/batfish/batfish/1742#-LFt-kqh1-bidBDc6KmL:-LFt-kqi48FY3yWytunL:b-2jpjbb) ([raw file](https://github.com/batfish/batfish/blob/f00408a9b8152a2346fc284aa548c78d4d3fb8dc/tests/basic/traceroute2-1-2.ref#L1520)):*
> ```
>     ],
>     "summary" : {
>       "notes" : "Found 4 results",
> ```

Why 4 flows given the test? (I suppose I don't quite understand the new semantics. Answering the questions in this review round should greatly help.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1742#-:-LFt0usw9F01CLpDXxz3:b3tnu4e)*

**Comment by anothermattbrown** [comment]
Review status: 0 of 7 files reviewed, 5 unresolved discussions (waiting on @anothermattbrown and @ratulm)

---

*[tests/basic/commands, line 38 at r1](https://reviewable.io/reviews/batfish/batfish/1742#-LFt0CX1B5QmNUSv5ixl:-LFt3E8NC3queXsM722h:blrqkyt) ([raw file](https://github.com/batfish/batfish/blob/f00408a9b8152a2346fc284aa548c78d4d3fb8dc/tests/basic/commands#L38)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

1) What is the semantics of this command? Judging from the ref, it is not identical to the command it edited.
</blockquote></details>

The sourceLocation parameter means "all interface links on node as1core1". This will match multiple interfaces, and create a flow for each one. 

---

*[tests/basic/commands, line 39 at r1](https://reviewable.io/reviews/batfish/batfish/1742#-LFt0VRt-y4bwUTa0v9h:-LFt3T5bBlEZhtVxuskS:b-3yvuve) ([raw file](https://github.com/batfish/batfish/blob/f00408a9b8152a2346fc284aa548c78d4d3fb8dc/tests/basic/commands#L39)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

Why not make NodeNameRegexInterfaceLocationSpecifierFactory the default in the question? New users will want to always use simple node names as parameter values, and then get fancy if needed.
</blockquote></details>

My goal was for the default factory to be expressive enough and to have good enough defaults that it would be the right choice for a large percentage of use cases. It also showcases the power of the new specifier framework (beyond just being pluggable). It doesn't have to be the default, and/or we can iterate on the design. 

One strength of this factory is that you can be much more precise, e.g. by enumerating the exact set of locations you want: `sourceLocation="node=node1,name=iface1;node=node2,name=iface2;..."`.

There's also some defaulting to improve expressiveness. Currently `sourceLocation="foo"` means the same thing as `sourceLocation="name=foo"`, but we could change it to mean `sourceLocation="node=foo"`.  

---

*[tests/basic/traceroute2-1-2.ref, line 72 at r1](https://reviewable.io/reviews/batfish/batfish/1742#-LFt-E6eAJ392ETSgdE0:-LFt6UFYA88u-vK9YE8O:br3v62o) ([raw file](https://github.com/batfish/batfish/blob/f00408a9b8152a2346fc284aa548c78d4d3fb8dc/tests/basic/traceroute2-1-2.ref#L72)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

Why is the srcIp 0.0.0.0 ?
</blockquote></details>

The default source IpSpace specifier is `InferFromLocationIpSpaceSpecifier` -- the set of IPs owned by the location. For this location (link of interface Loopback0 on as1core1) we get the empty IpSpace, because the subnet is a `/32` and we exclude the IP of the interface itself from the IpSpace of its link. In other words, interface link locations are meant to model external hosts connected through that interface, and that's impossible for a `/32`.  When this happens, my code just defaults to `0.0.0.0`, though that was an arbitrary choice. Another possible choice would be to remove this flow entirely since there's no possible choice of source IP.

---

*[tests/basic/traceroute2-1-2.ref, line 99 at r1](https://reviewable.io/reviews/batfish/batfish/1742#-LFsypfv8AaBF3Aaq59q:-LFt22fhCXEGxQ9dJaTA:bqskk8j) ([raw file](https://github.com/batfish/batfish/blob/f00408a9b8152a2346fc284aa548c78d4d3fb8dc/tests/basic/traceroute2-1-2.ref#L99)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

This is a "fake" hop?
</blockquote></details>

Yes. Traceroute does this for interface link location types, to simulate the traffic originating from a host outside the network. Interface link is the default location type, but we can also originate from interfaces themselves, in which case traffic originates from the VRF that contains that interface.

---

*[tests/basic/traceroute2-1-2.ref, line 1520 at r1](https://reviewable.io/reviews/batfish/batfish/1742#-LFt-kqh1-bidBDc6KmL:-LFt5xkiEFN3CeS6g0Vn:b4amezr) ([raw file](https://github.com/batfish/batfish/blob/f00408a9b8152a2346fc284aa548c78d4d3fb8dc/tests/basic/traceroute2-1-2.ref#L1520)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

Why 4 flows given the test? (I suppose I don't quite understand the new semantics. Answering the questions in this review round should greatly help.
</blockquote></details>

The source location specifier matches the four interfaces on node as1core1, and we generate a flow for each one.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1742)*

**Comment by ratulm** [comment]
Review status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @ratulm)

---

*[tests/basic/commands, line 39 at r1](https://reviewable.io/reviews/batfish/batfish/1742#-LFt0VRt-y4bwUTa0v9h:-LFxmMkI47PqLks6Qgxe:b2xi7h) ([raw file](https://github.com/batfish/batfish/blob/f00408a9b8152a2346fc284aa548c78d4d3fb8dc/tests/basic/commands#L39)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

My goal was for the default factory to be expressive enough and to have good enough defaults that it would be the right choice for a large percentage of use cases. It also showcases the power of the new specifier framework (beyond just being pluggable). It doesn't have to be the default, and/or we can iterate on the design. 

One strength of this factory is that you can be much more precise, e.g. by enumerating the exact set of locations you want: `sourceLocation="node=node1,name=iface1;node=node2,name=iface2;..."`.

There's also some defaulting to improve expressiveness. Currently `sourceLocation="foo"` means the same thing as `sourceLocation="name=foo"`, but we could change it to mean `sourceLocation="node=foo"`.  
</blockquote></details>

not sure for other use cases, but for traceroute the default being node=foo certainly makes sense, as people think of a traceroute from a source node to a destination. 

---

*[tests/basic/traceroute2-1-2.ref, line 72 at r1](https://reviewable.io/reviews/batfish/batfish/1742#-LFt-E6eAJ392ETSgdE0:-LFxnWrT7NVNohBaGZXT:byayltu) ([raw file](https://github.com/batfish/batfish/blob/f00408a9b8152a2346fc284aa548c78d4d3fb8dc/tests/basic/traceroute2-1-2.ref#L72)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

The default source IpSpace specifier is `InferFromLocationIpSpaceSpecifier` -- the set of IPs owned by the location. For this location (link of interface Loopback0 on as1core1) we get the empty IpSpace, because the subnet is a `/32` and we exclude the IP of the interface itself from the IpSpace of its link. In other words, interface link locations are meant to model external hosts connected through that interface, and that's impossible for a `/32`.  When this happens, my code just defaults to `0.0.0.0`, though that was an arbitrary choice. Another possible choice would be to remove this flow entirely since there's no possible choice of source IP.
</blockquote></details>

How  does one express a packet originating from the node?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1742)*

**Comment by ratulm** [comment]
Reviewed 1 of 7 files at r1.
Review status: 1 of 7 files reviewed, 2 unresolved discussions (waiting on @anothermattbrown and @ratulm)

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1742)*

**Comment by ratulm** [comment]
Reviewed 1 of 7 files at r1.
Review status: 2 of 7 files reviewed, 2 unresolved discussions (waiting on @anothermattbrown and @ratulm)

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1742)*

**Comment by ratulm** [comment]
Reviewed 2 of 7 files at r1.
Review status: 4 of 7 files reviewed, 2 unresolved discussions (waiting on @anothermattbrown and @ratulm)

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1742)*

**Comment by ratulm** [comment]
Reviewed 2 of 7 files at r1.
Review status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @anothermattbrown and @ratulm)

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1742)*

**Comment by anothermattbrown** [comment]
Review status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @anothermattbrown and @ratulm)

---

*[tests/basic/commands, line 39 at r1](https://reviewable.io/reviews/batfish/batfish/1742#-LFt0VRt-y4bwUTa0v9h:-LFxv2jnB1AEDTDoYaNb:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/f00408a9b8152a2346fc284aa548c78d4d3fb8dc/tests/basic/commands#L39)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

not sure for other use cases, but for traceroute the default being node=foo certainly makes sense, as people think of a traceroute from a source node to a destination. 
</blockquote></details>

Done.

---

*[tests/basic/traceroute2-1-2.ref, line 72 at r1](https://reviewable.io/reviews/batfish/batfish/1742#-LFt-E6eAJ392ETSgdE0:-LFxv9MoDZXp4avMmEzV:bjugqwj) ([raw file](https://github.com/batfish/batfish/blob/f00408a9b8152a2346fc284aa548c78d4d3fb8dc/tests/basic/traceroute2-1-2.ref#L72)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

How  does one express a packet originating from the node?
</blockquote></details>

Currently they would use the `interface` location type, e.g. `srcLocation="interface:node=as1core1"`.  A limitation of is is that it could match multiple interfaces and therefore return multiple flows when only one is desired.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1742)*

**Comment by ratulm** [comment]
Review status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @ratulm and @anothermattbrown)

---

*[projects/question/src/main/java/org/batfish/question/traceroute/TracerouteAnswerer.java, line 173 at r1](https://reviewable.io/reviews/batfish/batfish/1742#-LG-_Zd2ANXm8GCJ9-m8:-LG-_Zd2ANXm8GCJ9-m9:bs1ihmq) ([raw file](https://github.com/batfish/batfish/blob/6b72637f0670b2c0307eb802b5e435ad3bf966b0/projects/question/src/main/java/org/batfish/question/traceroute/TracerouteAnswerer.java#L173)):*
> ```Java
> 
>   private void setDstIp(Flow.Builder flowBuilder) {
>     // TODO: better automatic source ip, considering VRFs and routing
> ```

This comment should be deleted, right?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1742)*

**Comment by ratulm** [comment]
:lgtm: 

one non-blocking suggestion below. the nomenclature changes we discussed go in another PR i assume.

---

Reviewed 1 of 7 files at r1.
Review status: all files reviewed, 2 unresolved discussions (waiting on @ratulm and @anothermattbrown)

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1742#-:-LG-_ndQ2nIlxsWG5VcF:b-sz8tce)*

**Comment by anothermattbrown** [comment]
Review status: 6 of 7 files reviewed, all discussions resolved (waiting on @ratulm)

---

*[projects/question/src/main/java/org/batfish/question/traceroute/TracerouteAnswerer.java, line 173 at r1](https://reviewable.io/reviews/batfish/batfish/1742#-LG-_Zd2ANXm8GCJ9-m8:-LG10NgfD3aSRQy9BwUd:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/6b72637f0670b2c0307eb802b5e435ad3bf966b0/projects/question/src/main/java/org/batfish/question/traceroute/TracerouteAnswerer.java#L173)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

This comment should be deleted, right?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1742)*

**Comment by ratulm** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1742)*

**Comment by dhalperi** [comment]
This PR has broken many downstream users, our demos, etc.

Why was Traceroute (not Traceroute2) changed in this PR?

@anothermattbrown @ratulm

**Comment by dhalperi** [comment]
Example:

```
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "ingressNode" (class org.batfish.question.traceroute.TracerouteQuestion), not marked as ignorable (34 known properties: "assertion", "fragmentOffset", "ingressInterface", "dst", "tcpUrg", "icmpCode", "packetLength", "ecn", "state", "instance", "icmpType", "ignoreAcls", "srcProtocol", "tcpCwr", "ipProtocol", "includeOneTableKeys", "exclusions", "dstPort", "tcpSyn", "tcpAck", "displayHints", "srcIp", "sourceLocation", "tcpRst", "differential", "dscp", "dstProtocol", "sourceIpSpace", "sourceIpSpaceSpecifierFactory", "tcpPsh", "tcpEce", "tcpFin", "sourceLocationSpecifierFactory", "srcPort"])
```

**Pull request merged**
