### PR TITLE
Question development documentation

### PR DESCRIPTION
**Pull request by ratulm**
Move over content from https://github.com/batfish/batfish/wiki/Developer-notes. Something is better than nothing.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/9186)* status: all files reviewed, 6 unresolved discussions (waiting on @arifogel and @ratulm)

___
*[`docs/question_development/README.md` line 5 at r1](https://reviewable.io/reviews/batfish/batfish/9186#-O5nbq8wEJKCI4Jl8VjE:-O5nbq8x2Sw-eQQWR8rG:b45h) ([raw file](https://github.com/batfish/batfish/blob/55bafb89af78db811a01d69724e7b1637ebb15af/docs/question_development/README.md#L5)):*
> ```Markdown
> The high-level architecture of questions is as follows.
> 
> What is called via pybtafish (bf.q.<foo>) is a JSON template. See example templates inside the subfolders of [questions in the Batfish repository](https://github.com/batfish/batfish/tree/master/questions).
> ```





_Suggestion:_
```Markdown
pybatfish 
```
___
*[`docs/question_development/README.md` line 5 at r1](https://reviewable.io/reviews/batfish/batfish/9186#-O5nbuWODz1fEudT5vmJ:-O5nbuWODz1fEudT5vmK:undefined) ([raw file](https://github.com/batfish/batfish/blob/55bafb89af78db811a01d69724e7b1637ebb15af/docs/question_development/README.md#L5)):*
> ```Markdown
> The high-level architecture of questions is as follows.
> 
> What is called via pybtafish (bf.q.<foo>) is a JSON template. See example templates inside the subfolders of [questions in the Batfish repository](https://github.com/batfish/batfish/tree/master/questions).
> ```





_Suggestion:_
```Markdown
`bf.q.<foo>`
```
___
*[`docs/question_development/README.md` line 11 at r1](https://reviewable.io/reviews/batfish/batfish/9186#-O5ncsnw2Hz-Y0M1xzHV:-O5ncsnw2Hz-Y0M1xzHW:b3fy9wc) ([raw file](https://github.com/batfish/batfish/blob/55bafb89af78db811a01d69724e7b1637ebb15af/docs/question_development/README.md#L11)):*
> ```Markdown
> ### Adding a new Java question
> 
> See an existing question (e.g., `CompareFiltersQuestionPlugin`) for the various classes that are needed, as well as the structure of each class and their relationships among one another.
> ```

consider adding a link to the question module
___
*[`docs/question_development/README.md` line 13 at r1](https://reviewable.io/reviews/batfish/batfish/9186#-O5nc-RY-5xSxc7Z7b2z:-O5nc-RY-5xSxc7Z7b3-:b-73l6ra) ([raw file](https://github.com/batfish/batfish/blob/55bafb89af78db811a01d69724e7b1637ebb15af/docs/question_development/README.md#L13)):*
> ```Markdown
> See an existing question (e.g., `CompareFiltersQuestionPlugin`) for the various classes that are needed, as well as the structure of each class and their relationships among one another.
> 
> Small but important note:  the getName() method in your subclass of Question must return a String that is all lowercase. Otherwise clients will not be able to find your question when looking for it on the classpath.
> ```

and code font throughout?



_Suggestion:_
```Markdown
`getName()` 
```
___
*[`docs/question_development/README.md` line 13 at r1](https://reviewable.io/reviews/batfish/batfish/9186#-O5ncEtv7HLveWVmnM6_:-O5ncEtv7HLveWVmnM6a:b-dfn2ap) ([raw file](https://github.com/batfish/batfish/blob/55bafb89af78db811a01d69724e7b1637ebb15af/docs/question_development/README.md#L13)):*
> ```Markdown
> See an existing question (e.g., `CompareFiltersQuestionPlugin`) for the various classes that are needed, as well as the structure of each class and their relationships among one another.
> 
> Small but important note:  the getName() method in your subclass of Question must return a String that is all lowercase. Otherwise clients will not be able to find your question when looking for it on the classpath.
> ```

do you know more about this? A bunch that I spot checked don't have names that are all lowercase. https://github.com/batfish/batfish/blob/master/projects/question/src/main/java/org/batfish/question/initialization/FileParseStatusQuestion.java#L14



_Code quote:_
```Markdown
ust return a String that is all lowercase
```
___
*[`docs/question_development/README.md` line 17 at r1](https://reviewable.io/reviews/batfish/batfish/9186#-O5ncpkOBS8DQGSy2KPS:-O5ncpkOBS8DQGSy2KPT:bg1rs1j) ([raw file](https://github.com/batfish/batfish/blob/55bafb89af78db811a01d69724e7b1637ebb15af/docs/question_development/README.md#L17)):*
> ```Markdown
> ### Adding a new template
> 
> Follow examples in the existing templates.
> ```

consider adding a link direct into the templates folder.

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/9186)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @arifogel and @dhalperi)

___
*[`docs/question_development/README.md` line 5 at r1](https://reviewable.io/reviews/batfish/batfish/9186#-O5nbq8wEJKCI4Jl8VjE:-O5sxsTk-IlEwm76S-xP:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/55bafb89af78db811a01d69724e7b1637ebb15af/docs/question_development/README.md#L5)):*
> ```Markdown
> The high-level architecture of questions is as follows.
> 
> What is called via pybtafish (bf.q.<foo>) is a JSON template. See example templates inside the subfolders of [questions in the Batfish repository](https://github.com/batfish/batfish/tree/master/questions).
> ```

done

**Review by dhalperi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/9186)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @arifogel and @ratulm)

___
*[`docs/question_development/README.md` line 11 at r2](https://reviewable.io/reviews/batfish/batfish/9186#-O5sxzD9ARwLPWWnU29i:-O5sxzD9ARwLPWWnU29j:b-fnsj22) ([raw file](https://github.com/batfish/batfish/blob/ecac166725612369a487ae46ab8f5ba8b2cec3c3/docs/question_development/README.md#L11)):*
> ```Markdown
> See existing questions (e.g., [CompareFilters](https://github.com/batfish/batfish/tree/master/projects/question/src/main/java/org/batfish/question/comparefilters)) for example of how to extend these classes. 
> 
> NB: the `getName()` method in your subclass of Question must return a String that is unique across all questions. Batfish finds questions using this name. The names are case-insensitive (so, `FooBar` is the same name as `fooBar` and `foobar`).
> ```

I bet `pybatfish` generated names are sourced from it, too.

So `fileParseStatus` -> `bf.q.fileParseStatus`.

If you can confirm, consider updating again :p. Sorry.



_Code quote:_
```Markdown
Batfish finds questions using this name
```

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/9186)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @arifogel and @dhalperi)

___
*[`docs/question_development/README.md` line 11 at r2](https://reviewable.io/reviews/batfish/batfish/9186#-O5sxzD9ARwLPWWnU29i:-O5v_ymvDLYcPPgf9V3Z:b-rwnodq) ([raw file](https://github.com/batfish/batfish/blob/ecac166725612369a487ae46ab8f5ba8b2cec3c3/docs/question_development/README.md#L11)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I bet `pybatfish` generated names are sourced from it, too.

So `fileParseStatus` -> `bf.q.fileParseStatus`.

If you can confirm, consider updating again :p. Sorry.
</blockquote></details>

Updated with my understanding.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/9186)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Pull request merged**
