### PR TITLE
A10: parse and ignore `rba` `role`s

### PR DESCRIPTION
**Pull request by sfraint**
Parse and ignore `rba` `role`s since they have hostname lines that look like actually configuring the hostname.

e.g. in the following snippet, the device hostname should be `some_hostname`, not `read`:
```
!BATFISH_FORMAT: a10_acos
hostname some_hostname
!
rba role ROLENAME
  access-list write
  admin oper
  hostname read
  banner no-access
!
```

### CODE REVIEW

**Comment by ratulm** [comment]
An occurrence that is not handled:

```
rba role SystemAdmin default-privilege no-access 
  version read 
  clock read 
  system.hardware read 
  system.environment read 
  system.memory read 
  system-cpu.ctrl-cpu read 
  system-cpu.data-cpu read 
  clock.show write 
  rrd read 
  vcs write 
  vcs-vblades write 
  device-context write 
  syslog write 
  sys-audit-log write 
  restore write 
  upgrade.cf write 
  upgrade.hd write 
  backup.log write 
  backup-periodic write 
  backup.system write 
  terminal write 
  banner write 
  enable-management write 
  disable-management write 
  reboot write 
  reload write 
  shutdown write 
  ssh-login-grace-time write 
  monitor write 
  tftp write 
  multi-config write 
  web-service write 
  file.web-service-cert-key write 
  configure.sync write 
  bootimage write 
  logging write 
  ntp.server write 
  ntp.auth-key write 
  timezone write 
  ntp-status write 
  ntp.trusted-key write 
  system.resource-usage write 
  cgnv6.resource-usage write 
  slb.resource-usage write 
  system.resource-accounting write 
  partition write 
  partition-all write 
  ldap-server.host write 
  tacacs-server write 
  radius-server write 
  authentication write 
  partition-group write 
  admin-lockout write 
  file.glm-license write 
  delete.glm-license write 
  admin write 
  rba write 
  snmp-server write 
  smtp write 
  ip.dns write 
  hostname write 
  glm write 
  scm.license-src-info write 
  admin-session read 
  admin-detail write 
  file.template write 
  write.memory write 
  file.techsupport write 
  interface.ethernet read 
  interface.ve read 
  interface.management read 
  network.vlan read 
  ipv6.access-list read 
  access-list read 
  delete.partition write 
  export write 
  import write 
  active-partition write 
  system.upgrade-status read 
  file.startup-config write 
  link.startup-config write 
  delete.startup-config write 
  system.gui-image-list read 
!
```

missing keyword?

**Review by sfraint — COMMENTED** [review]
yep, doing another pass now to add in other keywords

> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7432#-:-MkO2oab7cWwAhv0MxEP:b-eeeinj)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @arifogel)

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7432)* status: 1 of 7 files reviewed, 2 unresolved discussions (waiting on @arifogel and @sfraint)

___
*[projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10_common.g4, line 13 at r1](https://reviewable.io/reviews/batfish/batfish/7432#-MkO3-xQ5CTsMDW9pGlb:-MkO3-xQ5CTsMDW9pGlc:b-67k6zb) ([raw file](https://github.com/batfish/batfish/blob/53dfc59a329ef8610579e4f58ef25b4ef7ca1ea8/projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10_common.g4#L13)):*
> ```ANTLR
> word: WORD_SEPARATOR word_content;
> 
> hostname: word | WORD_SEPARATOR (NO_ACCESS | OPER | READ | WRITE);
> ```

Note that this is no longer LL(1), since WORD_SEPARATOR is also the first token of `word`. However, getting it to be LL(1) will be very ugly, so maybe better to give up. You shouldn't get many of these rules in one file anyway.

I'd suggest replacing `(NO_ACCESS...)` with `srr_privilege` or a renamed version of it shoved in common.
___
*[projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10_rba.g4, line 16 at r1](https://reviewable.io/reviews/batfish/batfish/7432#-MkO4N5n6JMg5BR5VFe6:-MkO4N5n6JMg5BR5VFe7:bjjhd7k) ([raw file](https://github.com/batfish/batfish/blob/53dfc59a329ef8610579e4f58ef25b4ef7ca1ea8/projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10_rba.g4#L16)):*
> ```ANTLR
> 
> // Allow WORD_SEPARATOR here since M_Hostname will add it
> srr_privilege: WORD_SEPARATOR? (NO_ACCESS | OPER | READ | WRITE);
> ```

I would ditch `WORD_SEPARATOR?` here, and put `WORD_SEPARATOR` on the `HOSTNAME line below`.

**Review by arifogel — COMMENTED** [review]
> Reviewed 6 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7432)* status: 4 of 7 files reviewed, 6 unresolved discussions (waiting on @arifogel and @sfraint)

___
*[projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Lexer.g4, line 22 at r1](https://reviewable.io/reviews/batfish/batfish/7432#-MkO58dHBzXWLGApgf5g:-MkO58dIBbJfJOX9Y7BL:b-yxsyr8) ([raw file](https://github.com/batfish/batfish/blob/53dfc59a329ef8610579e4f58ef25b4ef7ca1ea8/projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Lexer.g4#L22)):*
> ```ANTLR
> ADMIN_SESSION: 'admin-session';
> AUTHENTICATION: 'authentication';
> BACKUP_LOG: 'backup.log';
> ```

I'm concerned that the list of new such tokens containing a `.` may include the entire configuration hierarchy (or at least the first two levels). Perhaps ditch the `.` in these token definitions and break up into two? Then the rule alternatives could be `TOKEN1 PERIOD TOKEN2`

Does the CLI let you put spaces between first word, period, second word? If so, they definitely should not be combined into single token.
___
*[projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Lexer.g4, line 320 at r1](https://reviewable.io/reviews/batfish/batfish/7432#-MkO64lE1SqvXqXoN7ow:-MkO64lF0qZ7tfRh5Vbz:b-q100b3) ([raw file](https://github.com/batfish/batfish/blob/53dfc59a329ef8610579e4f58ef25b4ef7ca1ea8/projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Lexer.g4#L320)):*
> ```ANTLR
> M_HostnameValue_SINGLE_QUOTE: ['] -> type(SINGLE_QUOTE), pushMode(M_SingleQuote);
> M_HostnameValue_WORD: F_Word -> type(WORD);
> M_HostnameValue_WRITE: WRITE -> type(WRITE), popMode;
> ```

Doesn't this need to be above `F_Word`? I'd put all tokens matching fixed text at the top.
___
*[projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Parser.g4, line 16 at r1](https://reviewable.io/reviews/batfish/batfish/7432#-MkO6KYY4DgsOV3sGjx0:-MkO6KYY4DgsOV3sGjx1:b-xxeepm) ([raw file](https://github.com/batfish/batfish/blob/53dfc59a329ef8610579e4f58ef25b4ef7ca1ea8/projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Parser.g4#L16)):*
> ```ANTLR
> a10_configuration: NEWLINE? statement+ NEWLINE* EOF;
> 
> statement: s_hostname | s_interface | s_rba | s_vlan;
> ```

Time to put one per line?
___
*[projects/batfish/src/test/resources/org/batfish/vendor/a10/grammar/testconfigs/hostname_after_rba, line 7 at r1](https://reviewable.io/reviews/batfish/batfish/7432#-MkO6_6uAPO6ZDJKko-H:-MkO6_6uAPO6ZDJKko-I:b-s3xvic) ([raw file](https://github.com/batfish/batfish/blob/53dfc59a329ef8610579e4f58ef25b4ef7ca1ea8/projects/batfish/src/test/resources/org/batfish/vendor/a10/grammar/testconfigs/hostname_after_rba#L7)):*
> ```
>   access-list write
>   admin oper
>   hostname read
> ```

To test suggested mode fix, add `hostname write` etc. as well.

**Review by arifogel — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7432)* status: all files reviewed, 7 unresolved discussions (waiting on @sfraint)

___
*[projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10_rba.g4, line 13 at r2](https://reviewable.io/reviews/batfish/batfish/7432#-MkO6vKG7UhIk8-KCvJG:-MkO6vKG7UhIk8-KCvJH:bxb6vhj) ([raw file](https://github.com/batfish/batfish/blob/e3436fa892562c5c46860b7bf8d39e478bd852dd/projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10_rba.g4#L13)):*
> ```ANTLR
> sr_role: ROLE name = rba_role_name srr_tail? NEWLINE srr_definition+;
> 
> srr_tail: DEFAULT_PRIVILEGE srr_privilege PARTITION_ONLY?;
> ```

`PARTITION_ONLY` is both a privilege and follows a privilege?

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7432)* status: 2 of 8 files reviewed, 6 unresolved discussions (waiting on @arifogel)

___
*[projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10_common.g4, line 13 at r1](https://reviewable.io/reviews/batfish/batfish/7432#-MkO3-xQ5CTsMDW9pGlb:-MkO8_Ng3i5jwUIMKDrv:bvnrpcm) ([raw file](https://github.com/batfish/batfish/blob/53dfc59a329ef8610579e4f58ef25b4ef7ca1ea8/projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10_common.g4#L13)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Note that this is no longer LL(1), since WORD_SEPARATOR is also the first token of `word`. However, getting it to be LL(1) will be very ugly, so maybe better to give up. You shouldn't get many of these rules in one file anyway.

I'd suggest replacing `(NO_ACCESS...)` with `srr_privilege` or a renamed version of it shoved in common.
</blockquote></details>

updated
___
*[projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10_rba.g4, line 16 at r1](https://reviewable.io/reviews/batfish/batfish/7432#-MkO4N5n6JMg5BR5VFe6:-MkO8g0qAxAP9QUIs5-I:bvnrpcm) ([raw file](https://github.com/batfish/batfish/blob/53dfc59a329ef8610579e4f58ef25b4ef7ca1ea8/projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10_rba.g4#L16)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

I would ditch `WORD_SEPARATOR?` here, and put `WORD_SEPARATOR` on the `HOSTNAME line below`.
</blockquote></details>

updated
___
*[projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10_rba.g4, line 13 at r2](https://reviewable.io/reviews/batfish/batfish/7432#-MkO6vKG7UhIk8-KCvJG:-MkO8aMl9dGksG8WEgHj:b1oirll) ([raw file](https://github.com/batfish/batfish/blob/e3436fa892562c5c46860b7bf8d39e478bd852dd/projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10_rba.g4#L13)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

`PARTITION_ONLY` is both a privilege and follows a privilege?
</blockquote></details>

yep, looks that way...
___
*[projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Lexer.g4, line 22 at r1](https://reviewable.io/reviews/batfish/batfish/7432#-MkO58dHBzXWLGApgf5g:-MkO8-Lq1bQUQyIXm_QH:buo4b07) ([raw file](https://github.com/batfish/batfish/blob/53dfc59a329ef8610579e4f58ef25b4ef7ca1ea8/projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Lexer.g4#L22)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

I'm concerned that the list of new such tokens containing a `.` may include the entire configuration hierarchy (or at least the first two levels). Perhaps ditch the `.` in these token definitions and break up into two? Then the rule alternatives could be `TOKEN1 PERIOD TOKEN2`

Does the CLI let you put spaces between first word, period, second word? If so, they definitely should not be combined into single token.
</blockquote></details>

you cannot put spaces between the words
___
*[projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Lexer.g4, line 320 at r1](https://reviewable.io/reviews/batfish/batfish/7432#-MkO64lE1SqvXqXoN7ow:-MkO8C4526BP8dkoUmC0:bvnrpcm) ([raw file](https://github.com/batfish/batfish/blob/53dfc59a329ef8610579e4f58ef25b4ef7ca1ea8/projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Lexer.g4#L320)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Doesn't this need to be above `F_Word`? I'd put all tokens matching fixed text at the top.
</blockquote></details>

updated
___
*[projects/batfish/src/test/resources/org/batfish/vendor/a10/grammar/testconfigs/hostname_after_rba, line 7 at r1](https://reviewable.io/reviews/batfish/batfish/7432#-MkO6_6uAPO6ZDJKko-H:-MkO8Xy4A5zJyqNXsAhg:b-2tyq15) ([raw file](https://github.com/batfish/batfish/blob/53dfc59a329ef8610579e4f58ef25b4ef7ca1ea8/projects/batfish/src/test/resources/org/batfish/vendor/a10/grammar/testconfigs/hostname_after_rba#L7)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

To test suggested mode fix, add `hostname write` etc. as well.
</blockquote></details>

added in the other config

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7432)* status: 2 of 8 files reviewed, 6 unresolved discussions (waiting on @arifogel)

___
*[projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Lexer.g4, line 22 at r1](https://reviewable.io/reviews/batfish/batfish/7432#-MkO58dHBzXWLGApgf5g:-MkOCowJ3Wl3U2v4QyFl:b-vfgk0x) ([raw file](https://github.com/batfish/batfish/blob/53dfc59a329ef8610579e4f58ef25b4ef7ca1ea8/projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Lexer.g4#L22)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

you cannot put spaces between the words
</blockquote></details>

also, its unclear how deep the hierarchy goes, but it is at least 6 levels: `ip.nat.inside.source.list.acl-name-list`

**Review by arifogel — COMMENTED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7432)* status: all files reviewed, 6 unresolved discussions (waiting on @sfraint)

___
*[projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10_common.g4, line 13 at r1](https://reviewable.io/reviews/batfish/batfish/7432#-MkO3-xQ5CTsMDW9pGlb:-MkOHQi90nkTzzwX_8au:b-gpenpx) ([raw file](https://github.com/batfish/batfish/blob/53dfc59a329ef8610579e4f58ef25b4ef7ca1ea8/projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10_common.g4#L13)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

updated
</blockquote></details>

revert as discussed offline
___
*[projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10_rba.g4, line 16 at r1](https://reviewable.io/reviews/batfish/batfish/7432#-MkO4N5n6JMg5BR5VFe6:-MkOHc915-oIo5W7Wa9s:b-z35inc) ([raw file](https://github.com/batfish/batfish/blob/53dfc59a329ef8610579e4f58ef25b4ef7ca1ea8/projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10_rba.g4#L16)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

updated
</blockquote></details>

Ignore portion of suggestion regarding `HOSTNAME`, which will disappear as discussed offline.
Looks like you implemented the rest of the suggestion.
___
*[projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10_rba.g4, line 11 at r3](https://reviewable.io/reviews/batfish/batfish/7432#-MkOHy4l25LvIve9UBSX:-MkOHy4l25LvIve9UBSY:b-8048ds) ([raw file](https://github.com/batfish/batfish/blob/9f3cb081137d18dcdb435cd40c5b73f335e089c2/projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10_rba.g4#L11)):*
> ```ANTLR
> s_rba: RBA sr_role;
> 
> sr_role: ROLE name = rba_role_name srr_tail? NEWLINE srr_definition+;
> ```

change `srr_definition` to some token for the whole definition line
___
*[projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10_rba.g4, line 15 at r3](https://reviewable.io/reviews/batfish/batfish/7432#-MkOHsG_9amvJawXQRyH:-MkOHsG_9amvJawXQRyI:bbhlhu7) ([raw file](https://github.com/batfish/batfish/blob/9f3cb081137d18dcdb435cd40c5b73f335e089c2/projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10_rba.g4#L15)):*
> ```ANTLR
> srr_tail: DEFAULT_PRIVILEGE administration_privilege PARTITION_ONLY?;
> 
> srr_definition
> ```

ditch entirely
___
*[projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Lexer.g4, line 22 at r1](https://reviewable.io/reviews/batfish/batfish/7432#-MkO58dHBzXWLGApgf5g:-MkOI9WH864D_jGhM1Kg:bqle8d1) ([raw file](https://github.com/batfish/batfish/blob/53dfc59a329ef8610579e4f58ef25b4ef7ca1ea8/projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Lexer.g4#L22)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

also, its unclear how deep the hierarchy goes, but it is at least 6 levels: `ip.nat.inside.source.list.acl-name-list`
</blockquote></details>

ditch all keywords added for left side of rba line as discussed offline
___
*[projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Lexer.g4, line 320 at r1](https://reviewable.io/reviews/batfish/batfish/7432#-MkO64lE1SqvXqXoN7ow:-MkOIGcY7hHo6zMuFaWE:b-yqxmg1) ([raw file](https://github.com/batfish/batfish/blob/53dfc59a329ef8610579e4f58ef25b4ef7ca1ea8/projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Lexer.g4#L320)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

updated
</blockquote></details>

revert entirely as discussed offline
___
*[projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java, line 393 at r3](https://reviewable.io/reviews/batfish/batfish/7432#-MkOIN5S4Vk9XHlmiQ0_:-MkOIN5S4Vk9XHlmiQ0a:b-gpenpx) ([raw file](https://github.com/batfish/batfish/blob/9f3cb081137d18dcdb435cd40c5b73f335e089c2/projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java#L393)):*
> ```Java
>   private @Nonnull Optional<String> toString(ParserRuleContext messageCtx, HostnameContext ctx) {
>     if (ctx.word() != null) {
>       return toString(messageCtx, ctx.word(), "hostname", HOSTNAME_PATTERN);
> ```

revert as discussed offline
___
*[projects/batfish/src/test/resources/org/batfish/vendor/a10/grammar/testconfigs/hostname_after_rba, line 7 at r1](https://reviewable.io/reviews/batfish/batfish/7432#-MkO6_6uAPO6ZDJKko-H:-MkOIQdD0VXpzEpElkpZ:b-bopgfk) ([raw file](https://github.com/batfish/batfish/blob/53dfc59a329ef8610579e4f58ef25b4ef7ca1ea8/projects/batfish/src/test/resources/org/batfish/vendor/a10/grammar/testconfigs/hostname_after_rba#L7)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

added in the other config
</blockquote></details>

unnecessary now, but can leave it.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7432)* status: all files reviewed, 7 unresolved discussions (waiting on @sfraint)

___
*[projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Lexer.g4, line 370 at r3](https://reviewable.io/reviews/batfish/batfish/7432#-MkOIZm29TfWY3rNh5kN:-MkOIZm29TfWY3rNh5kO:b-anqc7z) ([raw file](https://github.com/batfish/batfish/blob/9f3cb081137d18dcdb435cd40c5b73f335e089c2/projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Lexer.g4#L370)):*
> ```ANTLR
> M_WordValue_WS: F_Whitespace+ -> skip, popMode;
> M_WordValue_NEWLINE: F_Newline -> type(NEWLINE), popMode;
> ```

Offline discussion:
- make mode with two tokens that rba header ends in (at newline)
  1. token that consumes entire rba line
  2. token that ends at word boundary, calls `less`, and pops mode

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7432)* status: all files reviewed, 7 unresolved discussions (waiting on @sfraint)

___
*[projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Lexer.g4, line 370 at r3](https://reviewable.io/reviews/batfish/batfish/7432#-MkOIZm29TfWY3rNh5kN:-MkOJ1pE-IhpPtZEG32j:b-bmvt3p) ([raw file](https://github.com/batfish/batfish/blob/9f3cb081137d18dcdb435cd40c5b73f335e089c2/projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Lexer.g4#L370)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Offline discussion:
- make mode with two tokens that rba header ends in (at newline)
  1. token that consumes entire rba line
  2. token that ends at word boundary, calls `less`, and pops mode
</blockquote></details>

iii. comment line

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7432)* status: all files reviewed, 7 unresolved discussions (waiting on @sfraint)

___
*[projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Lexer.g4, line 370 at r3](https://reviewable.io/reviews/batfish/batfish/7432#-MkOIZm29TfWY3rNh5kN:-MkOJAhh3eUrcMcq9PgB:bvxnv2k) ([raw file](https://github.com/batfish/batfish/blob/9f3cb081137d18dcdb435cd40c5b73f335e089c2/projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Lexer.g4#L370)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

iii. comment line
</blockquote></details>

iv. NEWLINE (and make rba-line token not consume the newline so you don't have to special-case newline handling)

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7432)* status: all files reviewed, 7 unresolved discussions (waiting on @sfraint)

___
*[projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Lexer.g4, line 370 at r3](https://reviewable.io/reviews/batfish/batfish/7432#-MkOIZm29TfWY3rNh5kN:-MkOJQxCDMuJT-jN5J76:b3ia0fi) ([raw file](https://github.com/batfish/batfish/blob/9f3cb081137d18dcdb435cd40c5b73f335e089c2/projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Lexer.g4#L370)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

iv. NEWLINE (and make rba-line token not consume the newline so you don't have to special-case newline handling)
</blockquote></details>

v. WHITESPACE -> skip

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7432)* status: 4 of 8 files reviewed, 5 unresolved discussions (waiting on @arifogel and @sfraint)

___
*[projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10_common.g4, line 13 at r1](https://reviewable.io/reviews/batfish/batfish/7432#-MkO3-xQ5CTsMDW9pGlb:-MkOMgzyDPH0VGso52Tp:bvth56w) ([raw file](https://github.com/batfish/batfish/blob/53dfc59a329ef8610579e4f58ef25b4ef7ca1ea8/projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10_common.g4#L13)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

revert as discussed offline
</blockquote></details>

reverted
___
*[projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10_rba.g4, line 11 at r3](https://reviewable.io/reviews/batfish/batfish/7432#-MkOHy4l25LvIve9UBSX:-MkOMjRFCU3l_OojE5at:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/9f3cb081137d18dcdb435cd40c5b73f335e089c2/projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10_rba.g4#L11)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

change `srr_definition` to some token for the whole definition line
</blockquote></details>

Done.
___
*[projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10_rba.g4, line 15 at r3](https://reviewable.io/reviews/batfish/batfish/7432#-MkOHsG_9amvJawXQRyH:-MkOMsKG8ds4UJeX9Z-M:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/9f3cb081137d18dcdb435cd40c5b73f335e089c2/projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10_rba.g4#L15)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

ditch entirely
</blockquote></details>

Done.
___
*[projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Lexer.g4, line 320 at r1](https://reviewable.io/reviews/batfish/batfish/7432#-MkO64lE1SqvXqXoN7ow:-MkOLdae6JjEMSa6qXIA:bvnrpcm) ([raw file](https://github.com/batfish/batfish/blob/53dfc59a329ef8610579e4f58ef25b4ef7ca1ea8/projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Lexer.g4#L320)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

revert entirely as discussed offline
</blockquote></details>

updated
___
*[projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java, line 393 at r3](https://reviewable.io/reviews/batfish/batfish/7432#-MkOIN5S4Vk9XHlmiQ0_:-MkOLoD7A7tBCR0pi5mA:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/9f3cb081137d18dcdb435cd40c5b73f335e089c2/projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java#L393)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

revert as discussed offline
</blockquote></details>

done

**Review by arifogel — COMMENTED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7432)* status: all files reviewed, 3 unresolved discussions (waiting on @sfraint)

___
*[projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10_common.g4, line 46 at r4](https://reviewable.io/reviews/batfish/batfish/7432#-MkOWXnd3K48N00RLrzl:-MkOWXnd3K48N00RLrzm:bgqfxnp) ([raw file](https://github.com/batfish/batfish/blob/c9afd5a94f2a1a40e1cb74411a1ad8768b9b9784/projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10_common.g4#L46)):*
> ```ANTLR
> uint32: UINT8 | UINT16 | UINT32;
> 
> administration_privilege: NO_ACCESS | OPER | PARTITION_ONLY | READ | WRITE;
> ```

Does this actually need to be shared? Same question for `rba_role_name`. In fact it looks like in this revision you aren't even using this rule.
___
*[projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10_rba.g4, line 11 at r3](https://reviewable.io/reviews/batfish/batfish/7432#-MkOHy4l25LvIve9UBSX:-MkOWyT45CXYG95L-TqF:baa0bdh) ([raw file](https://github.com/batfish/batfish/blob/9f3cb081137d18dcdb435cd40c5b73f335e089c2/projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10_rba.g4#L11)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Should use `*` instead of `+`
___
*[projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Lexer.g4, line 29 at r4](https://reviewable.io/reviews/batfish/batfish/7432#-MkOX2qM396mrDdbj-pq:-MkOX2qM396mrDdbj-pr:btsooff) ([raw file](https://github.com/batfish/batfish/blob/c9afd5a94f2a1a40e1cb74411a1ad8768b9b9784/projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Lexer.g4#L29)):*
> ```ANTLR
> NO_ACCESS: 'no-access';
> OPER: 'oper';
> PARTITION_ONLY: 'partition-only';
> ```

You aren't using any of these currently.

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7432)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel)

___
*[projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10_common.g4, line 46 at r4](https://reviewable.io/reviews/batfish/batfish/7432#-MkOWXnd3K48N00RLrzl:-MkOYJXu9MkICArjExTV:b-lg4pu6) ([raw file](https://github.com/batfish/batfish/blob/c9afd5a94f2a1a40e1cb74411a1ad8768b9b9784/projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10_common.g4#L46)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Does this actually need to be shared? Same question for `rba_role_name`. In fact it looks like in this revision you aren't even using this rule.
</blockquote></details>

yep, (re)moved

**Review by arifogel — COMMENTED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7432)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

**Pull request merged**
