### PR TITLE
Parsing and storing interface VLANs for juniper

### PR DESCRIPTION
**Pull request by haverma**
- ref changed as default port mode should be `ACCESS` ([Juniper doc](https://www.juniper.net/documentation/en_US/junos/topics/reference/configuration-statement/port-mode-interfaces.html))

### CODE REVIEW

**Comment by arifogel** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 2491 at r1](https://reviewable.io/reviews/batfish/batfish/1330#-LC01mUfCoy82q8nDPub:-LC01mUg42MrU9ql1HNH:b-mossty) ([raw file](https://github.com/batfish/batfish/blob/e5c859a27f8b2fcd92730b1bc4d12140e14d4c59/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L2491)):*
> ```Java
>   public void enterS_vlans_named(S_vlans_namedContext ctx) {
>     if (ctx.name != null) {
>       _currentVlanName = ctx.name.getText();
> ```

This field should be set to null in an exit function for this rule.

---

*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 3080 at r1](https://reviewable.io/reviews/batfish/batfish/1330#-LC00CE23Kw6N_Xk8P4k:-LC00CE35ycx17Uflc0x:b-njup9m) ([raw file](https://github.com/batfish/batfish/blob/e5c859a27f8b2fcd92730b1bc4d12140e14d4c59/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L3080)):*
> ```Java
>         subRanges.forEach(subRange -> _currentInterface.getAllowedVlans().add(subRange));
>       }
>     } else if (ctx.name != null) {
> ```

What is the expected value of `getSwitchportMode()` in this case? Why is it acceptable to overwrite it? If you are overwriting it, why does the initial value matter?

---

*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 4223 at r1](https://reviewable.io/reviews/batfish/batfish/1330#-LC01U8K7Ge9Ab8fcBrq:-LC01U8K7Ge9Ab8fcBrr:b8uxaar) ([raw file](https://github.com/batfish/batfish/blob/e5c859a27f8b2fcd92730b1bc4d12140e14d4c59/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L4223)):*
> ```Java
>   @Override
>   public void exitVlt_vlan_id(Vlt_vlan_idContext ctx) {
>     if (ctx.name != null) {
> ```

How could `ctx.name` be null? There is no other way to match this rule.

---

*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 4224 at r1](https://reviewable.io/reviews/batfish/batfish/1330#-LC01dfP5rkqyIwb2eF8:-LC01dfP5rkqyIwb2eF9:b-gvlunt) ([raw file](https://github.com/batfish/batfish/blob/e5c859a27f8b2fcd92730b1bc4d12140e14d4c59/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L4224)):*
> ```Java
>   public void exitVlt_vlan_id(Vlt_vlan_idContext ctx) {
>     if (ctx.name != null) {
>       if (_currentVlanName != null) {
> ```

How could `_currentVlanName` be null? This should be a guaranteed precondition of reaching this parser rule.

---

*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 4228 at r1](https://reviewable.io/reviews/batfish/batfish/1330#-LC00Xxf4pUkfhP9Y_TO:-LC00Xxf4pUkfhP9Y_TP:b72ktlk) ([raw file](https://github.com/batfish/batfish/blob/e5c859a27f8b2fcd92730b1bc4d12140e14d4c59/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L4228)):*
> ```Java
>           _configuration
>               .getVlanNameToIds()
>               .put(_currentVlanName, Integer.valueOf(ctx.name.getText()));
> ```

Why are you getting an integer out of a `VariableContext`? If a number is expected here, why isn't the rule reflective of that?

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java, line 218 at r1](https://reviewable.io/reviews/batfish/batfish/1330#-LC02nGG4JMIGuVFzSy5:-LC02nGG4JMIGuVFzSy6:b-t1iybm) ([raw file](https://github.com/batfish/batfish/blob/e5c859a27f8b2fcd92730b1bc4d12140e14d4c59/projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java#L218)):*
> ```Java
>   private ConfigurationFormat _vendor;
> 
>   private Map<String, Integer> _vlanNameToIds;
> ```

We didn't talk about this in our offline structure, but instead of `Integer` the value type here should be a class extending `DefinedStructure`. Then in the `ConfigurationBuilder` you need to construct that class with the name and the definition line so we can handle named vlan references. You will need to add an enum instance to `JuniperStructureType`.
See the code in this file resolving references so we can identify references to undefined named vlans.
A reference needs to be added in `ConfigurationBuilder` when an interface refers to a named vlan. This will require adding a usage to `JuniperStructureUsage`, and resolution somewhere in this file.

You should also add tests on unused structures and undefined references. See other tests in `FlatJuniperGrammarTest` for a concise way to do this.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1330)*

**Comment by haverma** [comment]
Review status: 4 of 16 files reviewed at latest revision, 6 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 2491 at r1](https://reviewable.io/reviews/batfish/batfish/1330#-LC01mUfCoy82q8nDPub:-LC2-QFg64OCaMM8QtXH:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/e5c859a27f8b2fcd92730b1bc4d12140e14d4c59/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L2491)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

This field should be set to null in an exit function for this rule.
</blockquote></details>

done

---

*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 3080 at r1](https://reviewable.io/reviews/batfish/batfish/1330#-LC00CE23Kw6N_Xk8P4k:-LC2-_jy-6qG9aEVOfn6:btt2wo8) ([raw file](https://github.com/batfish/batfish/blob/e5c859a27f8b2fcd92730b1bc4d12140e14d4c59/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L3080)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

What is the expected value of `getSwitchportMode()` in this case? Why is it acceptable to overwrite it? If you are overwriting it, why does the initial value matter?
</blockquote></details>

as per the parser rule, here the expected value of `getSwitchPortMode()` can be either `ACCESS` or `NONE`, `NONE` will be the case where `port-mode` was not specified, and then `ACCESS` can be assumed to be the default (which is the intent behind overwriting both the cases with same value of `SwitchPortMode.ACCESS`).  

---

*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 4223 at r1](https://reviewable.io/reviews/batfish/batfish/1330#-LC01U8K7Ge9Ab8fcBrq:-LC20vr1Euuso3ZrXPVN:bnl9wct) ([raw file](https://github.com/batfish/batfish/blob/e5c859a27f8b2fcd92730b1bc4d12140e14d4c59/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L4223)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

How could `ctx.name` be null? There is no other way to match this rule.
</blockquote></details>

removed all redundant null checks

---

*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 4224 at r1](https://reviewable.io/reviews/batfish/batfish/1330#-LC01dfP5rkqyIwb2eF8:-LC21-Tg7Nu-1cTqCh7Z:bnl9wct) ([raw file](https://github.com/batfish/batfish/blob/e5c859a27f8b2fcd92730b1bc4d12140e14d4c59/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L4224)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

How could `_currentVlanName` be null? This should be a guaranteed precondition of reaching this parser rule.
</blockquote></details>

removed all redundant null checks

---

*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 4228 at r1](https://reviewable.io/reviews/batfish/batfish/1330#-LC00Xxf4pUkfhP9Y_TO:-LC213zO6rPHS079mwAk:b-pomqiz) ([raw file](https://github.com/batfish/batfish/blob/e5c859a27f8b2fcd92730b1bc4d12140e14d4c59/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L4228)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Why are you getting an integer out of a `VariableContext`? If a number is expected here, why isn't the rule reflective of that?
</blockquote></details>

replaced `variable` with `DEC`

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java, line 218 at r1](https://reviewable.io/reviews/batfish/batfish/1330#-LC02nGG4JMIGuVFzSy5:-LC21Cng4L04P-fiENGA:b1yx8eq) ([raw file](https://github.com/batfish/batfish/blob/e5c859a27f8b2fcd92730b1bc4d12140e14d4c59/projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java#L218)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

We didn't talk about this in our offline structure, but instead of `Integer` the value type here should be a class extending `DefinedStructure`. Then in the `ConfigurationBuilder` you need to construct that class with the name and the definition line so we can handle named vlan references. You will need to add an enum instance to `JuniperStructureType`.
See the code in this file resolving references so we can identify references to undefined named vlans.
A reference needs to be added in `ConfigurationBuilder` when an interface refers to a named vlan. This will require adding a usage to `JuniperStructureUsage`, and resolution somewhere in this file.

You should also add tests on unused structures and undefined references. See other tests in `FlatJuniperGrammarTest` for a concise way to do this.
</blockquote></details>

Took care of undefined references. Added `StructureType` and `StructureUsage` for `vlan` and `interface vlans`

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1330)*

**Comment by arifogel** [comment]
Reviewed 12 of 12 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 3080 at r1](https://reviewable.io/reviews/batfish/batfish/1330#-LC00CE23Kw6N_Xk8P4k:-LC5GIcf06xff610aiY_:b-6omosb) ([raw file](https://github.com/batfish/batfish/blob/e5c859a27f8b2fcd92730b1bc4d12140e14d4c59/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L3080)):*
<details><summary><i>Previously, haverma (Harsh Verma) wrote…</i></summary><blockquote>

as per the parser rule, here the expected value of `getSwitchPortMode()` can be either `ACCESS` or `NONE`, `NONE` will be the case where `port-mode` was not specified, and then `ACCESS` can be assumed to be the default (which is the intent behind overwriting both the cases with same value of `SwitchPortMode.ACCESS`).  
</blockquote></details>

Can you add a comment to that effect?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1330)*

**Comment by haverma** [comment]
Added comment

---

Review status: 15 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 3080 at r1](https://reviewable.io/reviews/batfish/batfish/1330#-LC00CE23Kw6N_Xk8P4k:-LC5MciD2WsMXJMQ23LW:b-7tfmjp) ([raw file](https://github.com/batfish/batfish/blob/e5c859a27f8b2fcd92730b1bc4d12140e14d4c59/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L3080)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Can you add a comment to that effect?
</blockquote></details>

added

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1330#-:-LC5M_4p91qWx3YZVdOL:b-bttoee)*

**Comment by arifogel** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1330)*

**Pull request merged**
