### PR TITLE
Frr: Liberation step 5: Final bits of conversion

### PR DESCRIPTION
**Pull request by ratulm**
After #7692

### CODE REVIEW

**Comment by ratulm** [comment]
@arifogel - FYI, this PR is ready for review. it is codecov failing, not buildkite.

**Review by arifogel — COMMENTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7693)* status: all files reviewed, 1 unresolved discussion (waiting on @ratulm)

___
*[projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConversions.java, line 1712 at r1](https://reviewable.io/reviews/batfish/batfish/7693#-MoeJJWwEjj7uU_GV6bs:-MoeJJWwEjj7uU_GV6bt:bqb1rgw) ([raw file](https://github.com/batfish/batfish/blob/8c80874c41abcc7ff9f9c2654f93bc39b0564de9/projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConversions.java#L1712)):*
> ```Java
>     c.setMlags(
>         ImmutableMap.of(
>             FRR_CLAG_DOMAIN_ID,
> ```

Doesn't `CLAG` stand for Cumulus LAG? Should this actually be ported? Is it supported on FRR generally?

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7693)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConversions.java, line 1712 at r1](https://reviewable.io/reviews/batfish/batfish/7693#-MoeJJWwEjj7uU_GV6bs:-Mof3BFn1yqU_Ibcn3nQ:bs6fu7t) ([raw file](https://github.com/batfish/batfish/blob/8c80874c41abcc7ff9f9c2654f93bc39b0564de9/projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConversions.java#L1712)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Doesn't `CLAG` stand for Cumulus LAG? Should this actually be ported? Is it supported on FRR generally?
</blockquote></details>

yeah, CLAG stands for Cumulus LAG -- Cumulus docs say it is basically MLAG: https://docs.nvidia.com/networking-ethernet-software/cumulus-linux-41/Layer-2/Multi-Chassis-Link-Aggregation-MLAG/

FRR has MLAG. Not sure if the Cumulus version is based on FRR or something. We can split off later if we find differences in semantics.  In the meanwhile, I'll fix the terminology in the FRR world to be MLAG. 

Sounds like a good plan?

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7693)* status: all files reviewed, 1 unresolved discussion (waiting on @ratulm)

___
*[projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConversions.java, line 1712 at r1](https://reviewable.io/reviews/batfish/batfish/7693#-MoeJJWwEjj7uU_GV6bs:-MofEjlJ6mLJGwzsrJJA:b-l2j0zl) ([raw file](https://github.com/batfish/batfish/blob/8c80874c41abcc7ff9f9c2654f93bc39b0564de9/projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConversions.java#L1712)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

yeah, CLAG stands for Cumulus LAG -- Cumulus docs say it is basically MLAG: https://docs.nvidia.com/networking-ethernet-software/cumulus-linux-41/Layer-2/Multi-Chassis-Link-Aggregation-MLAG/

FRR has MLAG. Not sure if the Cumulus version is based on FRR or something. We can split off later if we find differences in semantics.  In the meanwhile, I'll fix the terminology in the FRR world to be MLAG. 

Sounds like a good plan?
</blockquote></details>

I don't know if anything is proprietary with clag. I know in NCLU the configuration constructs use `clag` and not `mlag`. Not sure about non-NCLU.
And no idea if other FRR-based vendors use the same configuration. I'd leave it in Cumulus for now, or at least use the name `clag` until you determine that the configuration is identical for non-cumulus mlag.

**Review by arifogel — COMMENTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7693)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ratulm)

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7693)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ratulm)

**Pull request merged**
