### PR TITLE
IOS: Use regexes on individual communities where possible

### PR DESCRIPTION
**Pull request by millstein**
When converting IOS community-set regexes to the VI model, if a regex only requires that some community matching a particular format exists, then we represent it as a community regex rather than a community-set regex.  Community regexes have a simpler semantics, and some questions (e.g., SearchRoutePolicies) don't handle community-set regexes.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6773)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @arifogel)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6773#-MWUzm5b1JO-yntkf5po:-MWUzm5b1JO-yntkf5pp:b-o1abz3) (no related file):*
@arifogel can you take a look at this? I think you'll be more thorough.

Questions I have:
* any cases where this transformation is wrong? (aka, HasCommunity does not have same semantics as CSME)
* any easy missed cases? [okay to not handle all cases]
* why are the regexes still so complicated? Shouldn't the HasCommunity regexes be simpler? Aka, no need to handle `{}` or `,` or ` `.

+reviewer:@arifogel -reviewer:@dhalperi 

---

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6773)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @millstein)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6773#-MWWC2IR7nKKkgiwB6GS:-MWWC2IR7nKKkgiwB6GT:b-dcsf00) (no related file):*
As discussed offline:
- please move converter functions to `CiscoConversions`, and test them in `CiscoConversionsTest`.
  - refactor the actual conversion code into separate functions guarded by the regex check
- test whether correct converter is used for various inputs, rather than directly testing the converted structure

---

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6773)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @millstein)

___
*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 3852 at r1](https://reviewable.io/reviews/batfish/batfish/6773#-MWWC_hp14pSv-i7QaHX:-MWWC_hp14pSv-i7QaHY:b4uk6nu) ([raw file](https://github.com/batfish/batfish/blob/b6faf3330211f292dc7d9bc1e5c49a358fc47a20/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L3852)):*
> ```Java
>     // Regexes on individual communities have a simpler semantics, and some questions
>     // (e.g. SearchRoutePolicies) do not handle arbitrary community-set regexes.
>     String halfCommRegex = "(_?\\d+)?";
> ```

Reminder from offline discussion:
`halfCommRegex` has the underscore in the wrong position if used as the right half following the colon.

**Review by arifogel — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6773)* status: all files reviewed, 2 unresolved discussions (waiting on @millstein)

**Review by millstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6773)* status: 2 of 6 files reviewed, all discussions resolved (waiting on @arifogel)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6773#-MWUzm5b1JO-yntkf5po:-MWWoeViCkrmsQnrKLfl:b-t69ynd) (no related file):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

@arifogel can you take a look at this? I think you'll be more thorough.

Questions I have:
* any cases where this transformation is wrong? (aka, HasCommunity does not have same semantics as CSME)
* any easy missed cases? [okay to not handle all cases]
* why are the regexes still so complicated? Shouldn't the HasCommunity regexes be simpler? Aka, no need to handle `{}` or `,` or ` `.

+reviewer:@arifogel -reviewer:@dhalperi 
</blockquote></details>

1. The transformation is correct when the regex only matches a single community, but the original check for that had a bug, which is now fixed.
2. There were a few easy cases missed, like _34 and 34_, which are now supported.
3. _ can still appear in regexes that only apply to individual communities, so while we could remove them in this case, they still have to be handled in general.

---
*[a discussion](https://reviewable.io/reviews/batfish/batfish/6773#-MWWC2IR7nKKkgiwB6GS:-MWWp4mzASkWWZlTCPqE:bb7f2mf) (no related file):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

As discussed offline:
- please move converter functions to `CiscoConversions`, and test them in `CiscoConversionsTest`.
  - refactor the actual conversion code into separate functions guarded by the regex check
- test whether correct converter is used for various inputs, rather than directly testing the converted structure
</blockquote></details>

done

---
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 3852 at r1](https://reviewable.io/reviews/batfish/batfish/6773#-MWWC_hp14pSv-i7QaHX:-MWWp7b0C3FAbXmvY-7f:b15d7j6) ([raw file](https://github.com/batfish/batfish/blob/b6faf3330211f292dc7d9bc1e5c49a358fc47a20/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L3852)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Reminder from offline discussion:
`halfCommRegex` has the underscore in the wrong position if used as the right half following the colon.
</blockquote></details>

Done, and extended to handle regexes that don't contain a colon.

**Review by arifogel — COMMENTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6773)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by arifogel — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6773#-:-MWWrZQG9BAp4zaIXCnM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
