### PR TITLE
IOSXE: Redistribute EIGRP into BGP

### PR DESCRIPTION
**Pull request by corinaminer**
The resulting BGP routes do not yet have the correct metric (should be copied from EIGRP route's metric).

### CODE REVIEW

**Review by progwriter — COMMENTED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6475)* status: all files reviewed, 1 unresolved discussion (waiting on @corinaminer)

___
*[projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-xe-eigrp-to-bgp, line 4 at r1](https://reviewable.io/reviews/batfish/batfish/6475#-MNasI_87AiyFmqifVUs:-MNasI_87AiyFmqifVUt:b-9t0zn9) ([raw file](https://github.com/batfish/batfish/blob/9368d7b1359e6570200f07282d89da11f7e8f80a/projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-xe-eigrp-to-bgp#L4)):*
> ```
> hostname ios-xe-eigrp-to-bgp
> !
> !interface Ethernet1
> ```

why is the interface commented out, do you even need it?

**Review by progwriter — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6475)* status: all files reviewed, 1 unresolved discussion (waiting on @corinaminer)

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6475)* status: 9 of 10 files reviewed, all discussions resolved (waiting on @progwriter)

___
*[projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-xe-eigrp-to-bgp, line 4 at r1](https://reviewable.io/reviews/batfish/batfish/6475#-MNasI_87AiyFmqifVUs:-MNedsS_5nluIGSflo6-:bgfyj5h) ([raw file](https://github.com/batfish/batfish/blob/9368d7b1359e6570200f07282d89da11f7e8f80a/projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-xe-eigrp-to-bgp#L4)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

why is the interface commented out, do you even need it?
</blockquote></details>

oh. no, i commented it to see if it was necessary. good catch

**Review by progwriter — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6475)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
