### PR TITLE
Use ReachabilityParameters in reachability analysis

### PR DESCRIPTION
**Pull request by anothermattbrown**

### CODE REVIEW

**Comment by dhalperi** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1513#-LDiH5zy4UebDFICC4c0:-LDiH5zy4UebDFICC4c1:b-5dy6v9) (no related file):*
Consider which classes should be `final`

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/ReachabilitySettings.java, line 354 at r1](https://reviewable.io/reviews/batfish/batfish/1513#-LDiAHy29kj4uEHOHX4_:-LDiAHy29kj4uEHOHX4a:b-und75v) ([raw file](https://github.com/batfish/batfish/blob/50f0e3da17e396d24de93eac8fe7df658adeed4a/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/ReachabilitySettings.java#L354)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>     // remove src IPs from headerspace since they're specified via an IpSpaceSpecifier
>     IpSpace nullIpSpace = null;
>     HeaderSpace headerSpace =
>         _headerSpace.toBuilder().setNotSrcIps(nullIpSpace).setSrcIps(nullIpSpace).build();
>  
> ```
</details>


not quite sure I understand this code. Is this a workaround for simply storing srcIps and dstIps in the question instead of in the internal headerspace?

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/question/ResolvedReachabilityParameters.java, line 48 at r1](https://reviewable.io/reviews/batfish/batfish/1513#-LDiAax93TObY1zNlQ0E:-LDiAax93TObY1zNlQ0F:b-2czhn7) ([raw file](https://github.com/batfish/batfish/blob/50f0e3da17e396d24de93eac8fe7df658adeed4a/projects/batfish-common-protocol/src/main/java/org/batfish/question/ResolvedReachabilityParameters.java#L48)):*
> ```
> InvalidReachabilitySettingsException
> ```

Is this the right name? ("Settings" vs "Parameters"?)

Is this better than the built-in illegalargument / illegalstate exception?

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 3481 at r1](https://reviewable.io/reviews/batfish/batfish/1513#-LDiB1fL17uA3z7kc5p-:-LDiB1fMCq9JlBGNzh8s:b-ld7k05) ([raw file](https://github.com/batfish/batfish/blob/50f0e3da17e396d24de93eac8fe7df658adeed4a/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L3481)):*
> ```Java
> 
>   @Override
>   public AnswerElement reducedReachability(ReachabilitySettings reachabilitySettings) {
> ```

Is there a reason not to make this `ReachabiltiyParameters` and keep `ReachabilitySettings` truly internal to the `ReachabilityQuestionPlugin`?

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 3497 at r1](https://reviewable.io/reviews/batfish/batfish/1513#-LDiFkxNDuy0PZQh92jZ:-LDiFkxNDuy0PZQh92j_:boi9e9w) ([raw file](https://github.com/batfish/batfish/blob/50f0e3da17e396d24de93eac8fe7df658adeed4a/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L3497)):*
> ```
>  snapshot);
> ```

does this need to be a delta snapshot?

---

*[projects/batfish/src/main/java/org/batfish/z3/CompositeNodJob.java, line 25 at r1](https://reviewable.io/reviews/batfish/batfish/1513#-LDiGMZuEQpTuvWQoNGN:-LDiGMZuEQpTuvWQoNGO:b-llikwg) ([raw file](https://github.com/batfish/batfish/blob/50f0e3da17e396d24de93eac8fe7df658adeed4a/projects/batfish/src/main/java/org/batfish/z3/CompositeNodJob.java#L25)):*
> ```
> null
> ```

Does this even work? It looks like `super` is not annotated `@Nullable` and if my browser-based-tracing of this code is correct, we'll end up doing things like `ImmutableMap.copyOf(null)` and `null.getKeys()`.

---

*[projects/batfish/src/main/java/org/batfish/z3/IngressLocationConstraintGenerator.java, line 3 at r1](https://reviewable.io/reviews/batfish/batfish/1513#-LDiDFBi51UZB-TjsLrP:-LDiDFBi51UZB-TjsLrQ:b3kre) ([raw file](https://github.com/batfish/batfish/blob/50f0e3da17e396d24de93eac8fe7df658adeed4a/projects/batfish/src/main/java/org/batfish/z3/IngressLocationConstraintGenerator.java#L3)):*
> ```Java
> package org.batfish.z3;
> 
> public class IngressLocationConstraintGenerator {
> ```

?

---

*[projects/batfish/src/main/java/org/batfish/z3/IngressLocationInstrumentation.java, line 29 at r1](https://reviewable.io/reviews/batfish/batfish/1513#-LDiDJJt-xz17cZZlKzJ:-LDiDJJt-xz17cZZlKzK:b-qgd5tz) ([raw file](https://github.com/batfish/batfish/blob/50f0e3da17e396d24de93eac8fe7df658adeed4a/projects/batfish/src/main/java/org/batfish/z3/IngressLocationInstrumentation.java#L29)):*
> ```
> IngressPoints
> ```

`{@link IngressLocation ingress locations}`?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1513)*

**Comment by dhalperi** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1513)*

**Comment by anothermattbrown** [comment]
Review status: 26 of 30 files reviewed at latest revision, 8 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/ReachabilitySettings.java, line 354 at r1](https://reviewable.io/reviews/batfish/batfish/1513#-LDiAHy29kj4uEHOHX4_:-LDlmK4CBcu0IXvvdo-n:bdfiok1) ([raw file](https://github.com/batfish/batfish/blob/50f0e3da17e396d24de93eac8fe7df658adeed4a/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/ReachabilitySettings.java#L354)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
>     // remove src IPs from headerspace since they're specified via an IpSpaceSpecifier
>     IpSpace nullIpSpace = null;
>     HeaderSpace headerSpace =
>         _headerSpace.toBuilder().setNotSrcIps(nullIpSpace).setSrcIps(nullIpSpace).build();
>  
> ```

not quite sure I understand this code. Is this a workaround for simply storing srcIps and dstIps in the question instead of in the internal headerspace?
</blockquote></details>

Yes, we moved the src IPs to a specifier, so I didn't want to leave them here too, as it could cause confusion. I'd prefer to use a different data type that doesn't have srcIp fields, but I figured I shouldn't introduce that in this PR. This seemed like the next best thing.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/question/ResolvedReachabilityParameters.java, line 48 at r1](https://reviewable.io/reviews/batfish/batfish/1513#-LDiAax93TObY1zNlQ0E:-LDlniIn58p63xxHqQGB:b-5xybcx) ([raw file](https://github.com/batfish/batfish/blob/50f0e3da17e396d24de93eac8fe7df658adeed4a/projects/batfish-common-protocol/src/main/java/org/batfish/question/ResolvedReachabilityParameters.java#L48)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

(really, I mean to ask whether this should really be a checked vs an unchecked exception).
</blockquote></details>

I'm not sure if there is an advantage to this over the built-in unchecked exceptions. I'm using it to minimize the delta. One difference is that `InvalidReachabilitySettingsException` has a method to return a `StringAnswerElement` containing the exception message, which we return as the answer (without a stacktrace) when the exception is thrown. 

I'll rename it for now. I'm happy to remove it if you think I should.

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 3481 at r1](https://reviewable.io/reviews/batfish/batfish/1513#-LDiB1fL17uA3z7kc5p-:-LDm8vxUC_bq6ueEnnfz:b2jsv2z) ([raw file](https://github.com/batfish/batfish/blob/50f0e3da17e396d24de93eac8fe7df658adeed4a/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L3481)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Is there a reason not to make this `ReachabiltiyParameters` and keep `ReachabilitySettings` truly internal to the `ReachabilityQuestionPlugin`?
</blockquote></details>

I planned on doing that in a later PR. 

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 3497 at r1](https://reviewable.io/reviews/batfish/batfish/1513#-LDiFkxNDuy0PZQh92jZ:-LDlqt6nAfOni6abEt6R:b-hslpom) ([raw file](https://github.com/batfish/batfish/blob/50f0e3da17e396d24de93eac8fe7df658adeed4a/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L3497)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
>  snapshot);
> ```

does this need to be a delta snapshot?
</blockquote></details>

That makes sense. I guess the fact that no tests broke means the resolved parameters were the same for the base and delta snapshots. In the future, it might be better to have a single `ResolvedReducedReachabilityParameters` instead of two `ResolvedReachabilityParameters` that only differ in some fields. 

---

*[projects/batfish/src/main/java/org/batfish/z3/CompositeNodJob.java, line 25 at r1](https://reviewable.io/reviews/batfish/batfish/1513#-LDiGMZuEQpTuvWQoNGN:-LDm-oeo1aitXuqfAY_g:blng5kq) ([raw file](https://github.com/batfish/batfish/blob/50f0e3da17e396d24de93eac8fe7df658adeed4a/projects/batfish/src/main/java/org/batfish/z3/CompositeNodJob.java#L25)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> null
> ```

Does this even work? It looks like `super` is not annotated `@Nullable` and if my browser-based-tracing of this code is correct, we'll end up doing things like `ImmutableMap.copyOf(null)` and `null.getKeys()`.
</blockquote></details>

Weird. fixed

---

*[projects/batfish/src/main/java/org/batfish/z3/IngressLocationInstrumentation.java, line 29 at r1](https://reviewable.io/reviews/batfish/batfish/1513#-LDiDJJt-xz17cZZlKzJ:-LDm-llW3iJnuFpUjQGB:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/50f0e3da17e396d24de93eac8fe7df658adeed4a/projects/batfish/src/main/java/org/batfish/z3/IngressLocationInstrumentation.java#L29)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> IngressPoints
> ```

`{@link IngressLocation ingress locations}`?
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/z3/IngressLocationConstraintGenerator.java, line 3 at r1](https://reviewable.io/reviews/batfish/batfish/1513#-LDiDFBi51UZB-TjsLrP:-LDm-Z3w5OQWEydzz-_R:bss4a2b) ([raw file](https://github.com/batfish/batfish/blob/50f0e3da17e396d24de93eac8fe7df658adeed4a/projects/batfish/src/main/java/org/batfish/z3/IngressLocationConstraintGenerator.java#L3)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

?
</blockquote></details>

Removed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1513)*

**Comment by anothermattbrown** [comment]
Review status: 24 of 30 files reviewed at latest revision, 7 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1513#-LDiH5zy4UebDFICC4c0:-LDmE0FO59AOLRME3Ukp:b-896fix) (no related file):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Consider which classes should be `final`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1513)*

**Comment by dhalperi** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1513#-:-LDmOo1m0UqvKVXXtUHa:bnfp4nl)*

**Pull request merged**
