### PR TITLE
fix issues with static interface routes

### PR DESCRIPTION
**Pull request by arifogel**
- fix bug where static next-hop-interface-only routes never made it to
  FIB
- don't crash when static route with next-hop-interface refers to
  interface not on any edge
- add tests for fixes

---
This change is [Reviewable](https://reviewable.io/reviews/batfish/batfish/708)

### CODE REVIEW

**Comment by dhalperi** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/batfish/batfish/708#-L-jdWjME7xuiaSriWem:-L-jdWjME7xuiaSriWen:blvuoku) (no related file):*
I can't quite reconcile the PR with the first bullet: "fix bug where static next-hop-interface-only routes never made it to FIB" -- looks like there was no way for the previous code to not crash in any case where the new code was hit. Am I missing something?

---

*[projects/batfish/src/main/java/org/batfish/bdp/BdpDataPlane.java, line 172 at r1](https://reviewable.io:443/reviews/batfish/batfish/708#-L-jcNKhpV3BLOkCbCUj:-L-jcNKhpV3BLOkCbCUk:b-vunl89) ([raw file](https://github.com/batfish/batfish/blob/c552b4140ece3f9024480c08b5fb5f9e347a2627/projects/batfish/src/main/java/org/batfish/bdp/BdpDataPlane.java#L172)):*
> ```Java
>                                         .get(new NodeInterfacePair(hostname, srNextHopInterface));
>                                 if (edges == null) {
>                                   if (_flowSinks.contains(srNextHopInterface)) {
> ```

Does this not warn in Eclipse? This is a type mismatch - `_flowSinks` doesn't contain `String`.

Same warning 3x in this file, and in a few other places in Batfish apparently.

---

*[projects/batfish/src/main/java/org/batfish/bdp/BdpDataPlane.java, line 239 at r1](https://reviewable.io:443/reviews/batfish/batfish/708#-L-jdPlgbiu-UhhUnFhD:-L-jdPlhHQ3JyX4EqTCv:b-r16rkt) ([raw file](https://github.com/batfish/batfish/blob/c552b4140ece3f9024480c08b5fb5f9e347a2627/projects/batfish/src/main/java/org/batfish/bdp/BdpDataPlane.java#L239)):*
> ```Java
>                                             Interface.NULL_INTERFACE_NAME));
>                                   }
>                                 } else {
> ```

Is this exactly the same code as above?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/708)*

**Comment by dhalperi** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/708)*

**Comment by arifogel** [comment]
Review status: 1 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/batfish/batfish/708#-L-jdWjME7xuiaSriWem:-L-mgn1LLj0gRkdUxV4J:bd58its) (no related file):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I can't quite reconcile the PR with the first bullet: "fix bug where static next-hop-interface-only routes never made it to FIB" -- looks like there was no way for the previous code to not crash in any case where the new code was hit. Am I missing something?
</blockquote></details>

You missed an exclamation point that was removed. Without that change, the block was never entered.

---

*[projects/batfish/src/main/java/org/batfish/bdp/BdpDataPlane.java, line 172 at r1](https://reviewable.io:443/reviews/batfish/batfish/708#-L-jcNKhpV3BLOkCbCUj:-L-jkudTp09he8tYPgN9:b-dkzjvy) ([raw file](https://github.com/batfish/batfish/blob/c552b4140ece3f9024480c08b5fb5f9e347a2627/projects/batfish/src/main/java/org/batfish/bdp/BdpDataPlane.java#L172)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Does this not warn in Eclipse? This is a type mismatch - `_flowSinks` doesn't contain `String`.

Same warning 3x in this file, and in a few other places in Batfish apparently.
</blockquote></details>

I added a fix and test for this case.

---

*[projects/batfish/src/main/java/org/batfish/bdp/BdpDataPlane.java, line 203 at r1](https://reviewable.io:443/reviews/batfish/batfish/708#-L-mMjbJO3dXONu6ED4K:-L-mMjbKtF90PgGfUJ4o:b-u844h7) ([raw file](https://github.com/batfish/batfish/blob/c552b4140ece3f9024480c08b5fb5f9e347a2627/projects/batfish/src/main/java/org/batfish/bdp/BdpDataPlane.java#L203)):*
> ```Java
>                               }
>                               break;
>                             } else if (srNextHopIp.equals(Route.UNSET_ROUTE_NEXT_HOP_IP)
> ```

Note the removed exclamation point here. This code previously was never hit, so didn't crash.

---

*[projects/batfish/src/main/java/org/batfish/bdp/BdpDataPlane.java, line 239 at r1](https://reviewable.io:443/reviews/batfish/batfish/708#-L-jdPlgbiu-UhhUnFhD:-L-mgtl1iFU9Lhiwgfoy:bf1har5) ([raw file](https://github.com/batfish/batfish/blob/c552b4140ece3f9024480c08b5fb5f9e347a2627/projects/batfish/src/main/java/org/batfish/bdp/BdpDataPlane.java#L239)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Is this exactly the same code as above?
</blockquote></details>

Taken care of in refactoring.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/708)*

**Comment by dhalperi** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/708#-:-L-mkp3XdPynEGUysosg:bnfp4nl)*

**Pull request merged**
