### PR TITLE
Basic prefix tracing question

### PR DESCRIPTION
**Pull request by progwriter**
First pass on exposing prefix tracing info to a user.
Supports filtering based on prefix and nodeRegex, return results as a table (columns being node/vrf/prefix/peer/action taken).

### CODE REVIEW

**Comment by dhalperi** [comment]
*[projects/question/src/test/java/org/batfish/question/prefixtracer/PrefixTracerAnswererTest.java, line 45 at r1](https://reviewable.io/reviews/batfish/batfish/1597#-LELGElmCU358nv2-gl7:-LELGElmCU358nv2-gl8:boklu07) ([raw file](https://github.com/batfish/batfish/blob/8f4e0e3246302918d45408f062d0e0ce6bc6c58f/projects/question/src/test/java/org/batfish/question/prefixtracer/PrefixTracerAnswererTest.java#L45)):*
> ```Java
>   }
> 
>   public void testMatchesAllPrefixesWithoutSpecifying() {
> ```

Without the missing `@Test` annotations, these don't run.

Noticed because of codedov (cc: @anothermattbrown )

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1597)*

**Comment by dhalperi** [comment]
Review status: 5 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[projects/question/src/test/java/org/batfish/question/prefixtracer/PrefixTracerAnswererTest.java, line 26 at r1](https://reviewable.io/reviews/batfish/batfish/1597#-LELH6f0-6-C4vspbXth:-LELH6f0-6-C4vspbXti:b10t6wm) ([raw file](https://github.com/batfish/batfish/blob/8f4e0e3246302918d45408f062d0e0ce6bc6c58f/projects/question/src/test/java/org/batfish/question/prefixtracer/PrefixTracerAnswererTest.java#L26)):*
> ```Java
> 
>   @BeforeClass
>   public void setup() {
> ```

I am also told that this is a misuse of JUnit as well: must be `static` if you have `@BeforeClass` on it.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1597)*

**Comment by progwriter** [comment]
Review status: 5 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/question/src/test/java/org/batfish/question/prefixtracer/PrefixTracerAnswererTest.java, line 26 at r1](https://reviewable.io/reviews/batfish/batfish/1597#-LELH6f0-6-C4vspbXth:-LELIENY0KXKKvnzClA0:bb6un1j) ([raw file](https://github.com/batfish/batfish/blob/8f4e0e3246302918d45408f062d0e0ce6bc6c58f/projects/question/src/test/java/org/batfish/question/prefixtracer/PrefixTracerAnswererTest.java#L26)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I am also told that this is a misuse of JUnit as well: must be `static` if you have `@BeforeClass` on it.
</blockquote></details>

Done

---

*[projects/question/src/test/java/org/batfish/question/prefixtracer/PrefixTracerAnswererTest.java, line 45 at r1](https://reviewable.io/reviews/batfish/batfish/1597#-LELGElmCU358nv2-gl7:-LELICGK7XQMrg1hGoL8:b4855pb) ([raw file](https://github.com/batfish/batfish/blob/8f4e0e3246302918d45408f062d0e0ce6bc6c58f/projects/question/src/test/java/org/batfish/question/prefixtracer/PrefixTracerAnswererTest.java#L45)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Without the missing `@Test` annotations, these don't run.

Noticed because of codedov (cc: @anothermattbrown )
</blockquote></details>

Thanks! Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1597)*

**Comment by dhalperi** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/question/src/main/java/org/batfish/question/prefixtracer/PrefixTracerQuestion.java, line 18 at r2](https://reviewable.io/reviews/batfish/batfish/1597#-LELeWHH9FsmV_xbS1B2:-LELeWHH9FsmV_xbS1B3:bfu7w9t) ([raw file](https://github.com/batfish/batfish/blob/29195f57b3ee5b8b5df8fa1fee035969835a5836/projects/question/src/main/java/org/batfish/question/prefixtracer/PrefixTracerQuestion.java#L18)):*
> ```
> PROP_PRERIX
> ```
prefix

---

*[projects/question/src/test/java/org/batfish/question/prefixtracer/PrefixTracerQuestionTest.java, line 11 at r2](https://reviewable.io/reviews/batfish/batfish/1597#-LELeG9aA73ptelIceyj:-LELeG9aA73ptelIceyk:bi31b61) ([raw file](https://github.com/batfish/batfish/blob/29195f57b3ee5b8b5df8fa1fee035969835a5836/projects/question/src/test/java/org/batfish/question/prefixtracer/PrefixTracerQuestionTest.java#L11)):*
> ```
> testConstuctorHasDeafaultNodeSpecifier
> ```

Typos: constructor, default

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1597)*

**Comment by dhalperi** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1597#-:-LENTHjT6m0y_v-uHQle:bnfp4nl)*

**Comment by progwriter** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1597)*

**Pull request merged**
