### PR TITLE
cleanup testrig metadata if needed

### LINKED ISSUE #868: Make testrig state machine robust to crashes and 'kill -9' events
FYI, @dhalperi, @corinaminer

### PR DESCRIPTION
**Pull request by ratulm**
Fixes #868

---
This change is [Reviewable](https://reviewable.io/reviews/batfish/batfish/869)

### CODE REVIEW

**Comment by dhalperi** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkQueueMgr.java, line 86 at r1](https://reviewable.io:443/reviews/batfish/batfish/869#-L3ZiuAelRFpPlyl6PxY:-L3ZiuAelRFpPlyl6PxZ:b3c69ru) ([raw file](https://github.com/batfish/batfish/blob/c2286ea6b5cbd302faca779ba03bd660e5217654/projects/coordinator/src/main/java/org/batfish/coordinator/WorkQueueMgr.java#L86)):*
> ```Java
>       }
>     } else if (envMetadata.getProcessingStatus() == ProcessingStatus.DATAPLANING) {
>       if (getIncompleteWork(container, testrig, environment, WorkType.DATAPLANING) == null) {
> ```

the PMD complaints make sense to me -- why not combine these ifs in both cases.

if (parsing && no parsing work) {
  // set parsing fail;
} elseif (dataplaning && no dataplaning work) {
  // set dataplaning fail;
}

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/869#-:-L3Zj8wVAET9x-jkx45d:bnfp4nl)*

**Comment by dhalperi** [comment]
*[a discussion](https://reviewable.io:443/reviews/batfish/batfish/869#-L3ZjDb9Nme4efgXlq_r:-L3ZjDbAY3i4P2OblFtW:b-7b3gkz) (no related file):*
You said this fixed #868 -- does that mean we can now rerun dataplaning work manually?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/869)*

**Comment by ratulm** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/batfish/batfish/869#-L3ZjDb9Nme4efgXlq_r:-L3_0rCCapzgMov3HW3b:b1pa1h) (no related file):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

You said this fixed #868 -- does that mean we can now rerun dataplaning work manually?
</blockquote></details>

Yes. Are you not seeing that?

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkQueueMgr.java, line 86 at r1](https://reviewable.io:443/reviews/batfish/batfish/869#-L3ZiuAelRFpPlyl6PxY:-L3ZjhPYGgIdHbbtRM9m:b6z56ir) ([raw file](https://github.com/batfish/batfish/blob/c2286ea6b5cbd302faca779ba03bd660e5217654/projects/coordinator/src/main/java/org/batfish/coordinator/WorkQueueMgr.java#L86)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

the PMD complaints make sense to me -- why not combine these ifs in both cases.

if (parsing && no parsing work) {
  // set parsing fail;
} elseif (dataplaning && no dataplaning work) {
  // set dataplaning fail;
}
</blockquote></details>

that combination forces an extra check when 'parsing' is true but there is parsing work :) i can combine for code readability if you prefer that way. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/869)*

**Comment by dhalperi** [comment]
*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkQueueMgr.java, line 86 at r1](https://reviewable.io:443/reviews/batfish/batfish/869#-L3ZiuAelRFpPlyl6PxY:-L3_1oglCjb2Fh7a4HVF:b-u48upm) ([raw file](https://github.com/batfish/batfish/blob/c2286ea6b5cbd302faca779ba03bd660e5217654/projects/coordinator/src/main/java/org/batfish/coordinator/WorkQueueMgr.java#L86)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

that combination forces an extra check when 'parsing' is true but there is parsing work :) i can combine for code readability if you prefer that way. 
</blockquote></details>

are you talking about an enum equality check? I'm not worried about the CPU overhead there.

```java
ProcessingStatus status = envMetadata.getProcessingStatus();
if (status == PARSING && ...) {
} else if (status == DATAPLANING && ...) {
}
```

?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/869)*

**Comment by ratulm** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkQueueMgr.java, line 86 at r1](https://reviewable.io:443/reviews/batfish/batfish/869#-L3ZiuAelRFpPlyl6PxY:-L3_3TtAAfhHY3I8ePNV:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/c2286ea6b5cbd302faca779ba03bd660e5217654/projects/coordinator/src/main/java/org/batfish/coordinator/WorkQueueMgr.java#L86)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

are you talking about an enum equality check? I'm not worried about the CPU overhead there.

```java
ProcessingStatus status = envMetadata.getProcessingStatus();
if (status == PARSING && ...) {
} else if (status == DATAPLANING && ...) {
}
```

?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/869)*

**Comment by dhalperi** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/869#-:-L3_3mnNxbPvEsfkvQ7f:bnfp4nl)*

**Pull request merged**
