### PR TITLE
Add api version to /v2/version

### PR DESCRIPTION
**Pull request by arifogel**
- use fixed constant in common.properties
- initialize to 2.1.0

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8467)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @arifogel and @dhalperi)

___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/version/WorkMgrV2ApiVersion.java` line 11 at r1](https://reviewable.io/reviews/batfish/batfish/8467#-N9YA95U4XLmF3BKejY0:-N9YA95U4XLmF3BKejY1:bv0yhec) ([raw file](https://github.com/batfish/batfish/blob/7bfad31b0d8f40e0402ff5115079358749167014/projects/batfish-common-protocol/src/main/java/org/batfish/version/WorkMgrV2ApiVersion.java#L11)):*
> ```Java
> @AutoService(Versioned.class)
> public class WorkMgrV2ApiVersion implements Versioned {
>   @VisibleForTesting static final String PROPERTIES_PATH = "org/batfish/common/common.properties";
> ```

Should not depend on anything in `common`, should be `coordinator` specific.



_Code quote:_
```Java
g PROPERTIES_PATH = "org/batfish/common/common.properties";
```

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8467)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/version/WorkMgrV2ApiVersion.java` line 11 at r1](https://reviewable.io/reviews/batfish/batfish/8467#-N9YA95U4XLmF3BKejY0:-N9YFUe11Lg1KhlGGZPV:b-7mmp82) ([raw file](https://github.com/batfish/batfish/blob/7bfad31b0d8f40e0402ff5115079358749167014/projects/batfish-common-protocol/src/main/java/org/batfish/version/WorkMgrV2ApiVersion.java#L11)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Should not depend on anything in `common`, should be `coordinator` specific.
</blockquote></details>

moved

**Review by dhalperi — COMMENTED** [review]
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8467)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8467)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel)

___
*[`projects/coordinator/src/main/java/org/batfish/coordinator/version/WorkMgrV2ApiVersion.java` line 16 at r2](https://reviewable.io/reviews/batfish/batfish/8467#-N9YWdQo0rXqlrmAQ6In:-N9YWey37rcv4XWOd2oX:b-49n1mt) ([raw file](https://github.com/batfish/batfish/blob/beb1110d093b5d0f03dc0061d665d7efdcd0df40/projects/coordinator/src/main/java/org/batfish/coordinator/version/WorkMgrV2ApiVersion.java#L16)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

can we fix this name?
</blockquote></details>

Why is it not `api_version`?

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8467)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

___
*[`projects/coordinator/src/main/java/org/batfish/coordinator/version/WorkMgrV2ApiVersion.java` line 16 at r2](https://reviewable.io/reviews/batfish/batfish/8467#-N9YWdQo0rXqlrmAQ6In:-N9Yv19X-sNgZCWKkF-o:b-7rl0jd) ([raw file](https://github.com/batfish/batfish/blob/beb1110d093b5d0f03dc0061d665d7efdcd0df40/projects/coordinator/src/main/java/org/batfish/coordinator/version/WorkMgrV2ApiVersion.java#L16)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Why is it not `api_version`?
</blockquote></details>

done.

**Review by arifogel — COMMENTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8467)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Pull request merged**
