### PR TITLE
FortiOS: initial VLAN interface validation

### PR DESCRIPTION
**Pull request by sfraint**
Add basic, initial edit-block validation for VLAN interfaces.
Also required updating a lot of test configs as they're invalid.

### CODE REVIEW

**Review by corinaminer — COMMENTED** [review]
> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6830)* status: all files reviewed, 1 unresolved discussion (waiting on @sfraint)

___
*[projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/iface, line 32 at r1](https://reviewable.io/reviews/batfish/batfish/6830#-MXIn8qlERwlDmF7rGW-:-MXIn8qlERwlDmF7rGW0:bus3zdt) ([raw file](https://github.com/batfish/batfish/blob/136fd4dd30e10195880d8f6fbc06c2e3ef9d16ae/projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/iface#L32)):*
> ```
>         set vlanid 1235
>         set interface port1
>         set vrf 31
> ```

This config is used for an extraction test, right? The VS properties for the new lines should be tested.

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6830)* status: all files reviewed, 1 unresolved discussion (waiting on @corinaminer)

___
*[projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/iface, line 32 at r1](https://reviewable.io/reviews/batfish/batfish/6830#-MXIn8qlERwlDmF7rGW-:-MXIoQlk4sCXe3NKE33A:b7h873x) ([raw file](https://github.com/batfish/batfish/blob/136fd4dd30e10195880d8f6fbc06c2e3ef9d16ae/projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/iface#L32)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

This config is used for an extraction test, right? The VS properties for the new lines should be tested.
</blockquote></details>

these properties are already tested for the `vlan` interface below

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6830)* status: all files reviewed, 1 unresolved discussion (waiting on @sfraint)

___
*[projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/iface, line 32 at r1](https://reviewable.io/reviews/batfish/batfish/6830#-MXIn8qlERwlDmF7rGW-:-MXJ0bTR2Jwxm4RXlL1J:b3l1fiq) ([raw file](https://github.com/batfish/batfish/blob/136fd4dd30e10195880d8f6fbc06c2e3ef9d16ae/projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/iface#L32)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

these properties are already tested for the `vlan` interface below
</blockquote></details>

it's fine to just test one interface, but the test doesn't actually check those properties afaict. If we're only extracting them in order to get correct edit block validation, that's ok, but i think they will be used in conversion, right?

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6830)* status: all files reviewed, 1 unresolved discussion (waiting on @corinaminer)

___
*[projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/iface, line 32 at r1](https://reviewable.io/reviews/batfish/batfish/6830#-MXIn8qlERwlDmF7rGW-:-MXJ97EQERchUlwpqC1P:b-7e69om) ([raw file](https://github.com/batfish/batfish/blob/136fd4dd30e10195880d8f6fbc06c2e3ef9d16ae/projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/iface#L32)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

it's fine to just test one interface, but the test doesn't actually check those properties afaict. If we're only extracting them in order to get correct edit block validation, that's ok, but i think they will be used in conversion, right?
</blockquote></details>

For these interfaces it is just for edit block validation. When we add VLAN conversion, at least the `interface` property will effectively be checked for all of the VLAN interfaces.

For the `vlan` interface we are checking both vlanid and interface: https://github.com/batfish/batfish/blob/master/projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java#L856-L858

**Pull request merged**
