### PR TITLE
NXOS: support VRF nameservers

### PR DESCRIPTION
**Pull request by progwriter**
Main goal: keep parser context. Secondary goal: actually plumb through so that DNS sever verification works

### CODE REVIEW

**Review by progwriter — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6388)* status: 0 of 5 files reviewed, all discussions resolved

___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java, line 6118 at r1](https://reviewable.io/reviews/batfish/batfish/6388#-MLJuBm36WNcHjI6wCOM:-MLJuBm36WNcHjI6wCON:bg621rz) ([raw file](https://github.com/batfish/batfish/blob/ff851d28ab1f2588aa1d9355bcb47e75e2facf91/projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java#L6118)):*
> ```
> _c.getIpNameServersByUseVrf()
> ```

Decided to use existing (but unexercised) infra. Happy to move to nameservers to `Vrf` if we want to keep VS model more accurate.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6388)* status: all files reviewed, 1 unresolved discussion (waiting on @progwriter)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_vrf.g4, line 76 at r1](https://reviewable.io/reviews/batfish/batfish/6388#-MLJue2OAzgNiMFeOMiQ:-MLJue2P7EeJitH86I3u:b-zc104) ([raw file](https://github.com/batfish/batfish/blob/ff851d28ab1f2588aa1d9355bcb47e75e2facf91/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_vrf.g4#L76)):*
> ```ANTLR
>   (
>     ip_route
>     | vc_ip_name_server
> ```

should we delete the top-level rule, replace it with this one?
___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java, line 6118 at r1](https://reviewable.io/reviews/batfish/batfish/6388#-MLJuBm36WNcHjI6wCOM:-MLJukhm4nFA6vcE9Guh:buey5py) ([raw file](https://github.com/batfish/batfish/blob/ff851d28ab1f2588aa1d9355bcb47e75e2facf91/projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java#L6118)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

> ```
> _c.getIpNameServersByUseVrf()
> ```

Decided to use existing (but unexercised) infra. Happy to move to nameservers to `Vrf` if we want to keep VS model more accurate. 
</blockquote></details>

yes, please :p

**Review by progwriter — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6388)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_vrf.g4, line 76 at r1](https://reviewable.io/reviews/batfish/batfish/6388#-MLJue2OAzgNiMFeOMiQ:-MLK94jEEQBRuq2PTE0R:bsz561c) ([raw file](https://github.com/batfish/batfish/blob/ff851d28ab1f2588aa1d9355bcb47e75e2facf91/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_vrf.g4#L76)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

should we delete the top-level rule, replace it with this one?
</blockquote></details>

ah, missed the other one. Now trying to get the best of both worlds

**Review by dhalperi — COMMENTED** [review]
:lgtm:

> Reviewed 7 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6388#-:-MLKA7PC0QnNnXihYJUe:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
