### PR TITLE
Symbolic route analysis:  Support the communities data model

### PR DESCRIPTION
**Pull request by millstein**
Adds support to the symbolic route analysis for the data model in org.batfish.datamodel.routing_policy.communities.  Specifically we now support route policies that contain the SetCommunities statement and the MatchCommunities boolean expression.  Previously we only supported the simpler community-related expressions and statements that appear in  org.batfish.datamodel.routing_policy.expr and org.batfish.datamodel.routing_policy.statement.  This update allows the symbolic route analysis to work on Juniper and IOS XR route policies that involve communities.

### CODE REVIEW

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 23 of 23 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6224)* status: all files reviewed, 3 unresolved discussions (waiting on @millstein)

___
*[projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/CommunityMatchExprToBDD.java, line 128 at r1](https://reviewable.io/reviews/batfish/batfish/6224#-MHrFvIRBVXVAgAxIhAG:-MHrFvIRBVXVAgAxIhAH:b-53hgav) ([raw file](https://github.com/batfish/batfish/blob/fdd2333825c657e9c5379c7e8273cdbf66799cf3/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/CommunityMatchExprToBDD.java#L128)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> // to negate a predicate on a single community, we diff it from a predicate representing
>     // all possible communities: the disjunction of all community atomic predicates.  simply
>     // negating toBeNegated is not sufficient because it could allow a model where all atomic
>     // predicates are false, which doesn't correspond to any concrete communities.
> ```
</details>

I think it would be worth moving this to the BDDRoute. Could name it something like `anyCommunity`
___
*[projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java, line 638 at r1](https://reviewable.io/reviews/batfish/batfish/6224#-MI1JdI327_v9GA2P6Kd:-MI1JdI43X2TrDLL69T_:b-intuj0) ([raw file](https://github.com/batfish/batfish/blob/fdd2333825c657e9c5379c7e8273cdbf66799cf3/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java#L638)):*
> ```
> since for example some of them may be negated in the expression
> ```
we can't normalize to the set of APs form in this case?
___
*[projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java, line 654 at r1](https://reviewable.io/reviews/batfish/batfish/6224#-MI1K8TT4e1UGg4dNU8D:-MI1K8TU31viT7O-4I1P:bhsgudh) ([raw file](https://github.com/batfish/batfish/blob/fdd2333825c657e9c5379c7e8273cdbf66799cf3/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java#L654)):*
> ```
> setCommunities(comms, curP, result);
> ```
please add comments explaining why this case is different from the previous case

**Review by millstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6224)* status: 21 of 24 files reviewed, 1 unresolved discussion (waiting on @anothermattbrown)

___
*[projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/CommunityMatchExprToBDD.java, line 128 at r1](https://reviewable.io/reviews/batfish/batfish/6224#-MHrFvIRBVXVAgAxIhAG:-MI1qOFF4907ocMmii85:bb6un1j) ([raw file](https://github.com/batfish/batfish/blob/fdd2333825c657e9c5379c7e8273cdbf66799cf3/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/CommunityMatchExprToBDD.java#L128)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

> ```
> // to negate a predicate on a single community, we diff it from a predicate representing
>     // all possible communities: the disjunction of all community atomic predicates.  simply
>     // negating toBeNegated is not sufficient because it could allow a model where all atomic
>     // predicates are false, which doesn't correspond to any concrete communities.
> ```
I think it would be worth moving this to the BDDRoute. Could name it something like `anyCommunity`
</blockquote></details>

Done
___
*[projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java, line 638 at r1](https://reviewable.io/reviews/batfish/batfish/6224#-MI1JdI327_v9GA2P6Kd:-MI1qSzb5yQQrEf4gX-j:bc9aam9) ([raw file](https://github.com/batfish/batfish/blob/fdd2333825c657e9c5379c7e8273cdbf66799cf3/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java#L638)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

> ```
> since for example some of them may be negated in the expression
> ```
we can't normalize to the set of APs form in this case?
</blockquote></details>

I think we can; we just haven't done so yet.  I added a comment to this effect.
___
*[projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java, line 654 at r1](https://reviewable.io/reviews/batfish/batfish/6224#-MI1K8TT4e1UGg4dNU8D:-MI1qY1p5Wbgr8N_eQe-:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/fdd2333825c657e9c5379c7e8273cdbf66799cf3/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java#L654)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

> ```
> setCommunities(comms, curP, result);
> ```
please add comments explaining why this case is different from the previous case
</blockquote></details>

Done.

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6224)* status: 23 of 24 files reviewed, all discussions resolved (waiting on @anothermattbrown)

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6224)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
