### PR TITLE
IOS-XR: allow remarks on any line in a community set

### PR DESCRIPTION
**Pull request by dhalperi**

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6953)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_community_set.g4, line 23 at r1](https://reviewable.io/reviews/batfish/batfish/6953#-MZ0M536ERZvjOt1Hqrt:-MZ0M536ERZvjOt1Hqru:boq5e7h) ([raw file](https://github.com/batfish/batfish/blob/20746f953489e5df35f8055d61161e6a525349bb/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_community_set.g4#L23)):*
> ```ANTLR
> community_set_elem
> :
>   NEWLINE*
> ```

Can you also do `rd_set_elem`? May have to touch another mode, too.

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6953)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_community_set.g4, line 23 at r1](https://reviewable.io/reviews/batfish/batfish/6953#-MZ0M536ERZvjOt1Hqrt:-MZ0Mm6QCdGVNCV4oYuV:biao8to) ([raw file](https://github.com/batfish/batfish/blob/20746f953489e5df35f8055d61161e6a525349bb/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_community_set.g4#L23)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Can you also do `rd_set_elem`? May have to touch another mode, too.
</blockquote></details>

If this looks good, that's for another PR.

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6953)* status: 3 of 6 files reviewed, all discussions resolved (waiting on @arifogel)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_community_set.g4, line 23 at r1](https://reviewable.io/reviews/batfish/batfish/6953#-MZ0M536ERZvjOt1Hqrt:-MZ0O9Y_EkIT8iVHaCXD:b-4nl3zg) ([raw file](https://github.com/batfish/batfish/blob/20746f953489e5df35f8055d61161e6a525349bb/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_community_set.g4#L23)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

If this looks good, that's for another PR.
</blockquote></details>

Just did it :)

**Review by arifogel — COMMENTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6953)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
