### PR TITLE
find representative Ips in an IpSpace

### PR DESCRIPTION
**Pull request by anothermattbrown**

### CODE REVIEW

**Comment by arifogel** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed, 1 unresolved discussion (waiting on @anothermattbrown)

---

*[projects/batfish/src/test/java/org/batfish/datamodel/visitors/IpSpaceRepresentativeTest.java, line 52 at r1](https://reviewable.io/reviews/batfish/batfish/1653#-LEuUvkYBV-6wYxrXoTz:-LEuUvkZEZoJYUbObVtT:b-u3jzyb) ([raw file](https://github.com/batfish/batfish/blob/a9a13b33a7489efe83782261d69eb8bf7be5f4b4/projects/batfish/src/test/java/org/batfish/datamodel/visitors/IpSpaceRepresentativeTest.java#L52)):*
> ```Java
>             .thenPermitting(ip2.toIpSpace())
>             .build();
>     assertThat(getRepresentative(ipSpace), equalTo(Optional.of(ip1)));
> ```

Why must it be `ip1`?
In particular, what behavior are you trying to test in all of these functions? That a representative exists and is in the space, or always that a particular representative is chosen?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1653)*

**Comment by anothermattbrown** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @anothermattbrown)

---

*[projects/batfish/src/test/java/org/batfish/datamodel/visitors/IpSpaceRepresentativeTest.java, line 52 at r1](https://reviewable.io/reviews/batfish/batfish/1653#-LEuUvkYBV-6wYxrXoTz:-LEuXpj22QkdqdN6Rlrt:b-qbmc9t) ([raw file](https://github.com/batfish/batfish/blob/a9a13b33a7489efe83782261d69eb8bf7be5f4b4/projects/batfish/src/test/java/org/batfish/datamodel/visitors/IpSpaceRepresentativeTest.java#L52)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Why must it be `ip1`?
In particular, what behavior are you trying to test in all of these functions? That a representative exists and is in the space, or always that a particular representative is chosen?
</blockquote></details>

Both. I'd like it to pick an intuitive representative (at least for comprehensible `IpSpace`s).  `ip1` was chosen because the algorithm prefers 0 to 1, and greedily picks bits from low to high order. I swapped the order to make it more understandable, improved the test, and added comments.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1653)*

**Comment by arifogel** [comment]
Reviewed 2 of 2 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1653)*

**Comment by arifogel** [comment]
:lgtm: if the interface/plugin stuff we discussed offline is separable

---

Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1653#-:-LEuc74d5xb9naXk3cdI:bcclm4j)*

**Comment by arifogel** [comment]
Reviewed 3 of 4 files at r3.
Review status: all files reviewed, 1 unresolved discussion (waiting on @anothermattbrown)

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/visitors/IpSpaceRepresentative.java, line 13 at r3](https://reviewable.io/reviews/batfish/batfish/1653#-LEusQUl3Bmtx8-sISgA:-LEusQUm-OIMZF8SmxwS:b-1g525h) ([raw file](https://github.com/batfish/batfish/blob/63a9aa03261b5d8f475d2b73efdac870fa137471/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/visitors/IpSpaceRepresentative.java#L13)):*
> ```Java
> 
> public interface IpSpaceRepresentative {
>   static Optional<Ip> representative(IpSpace ipSpace) {
> ```

Do I understand correctly that you are loading the service every time you want a representative?
Why not just have a static method that returns a `IpSpaceRepresentative` concrete class instance?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1653)*

**Comment by anothermattbrown** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @arifogel)

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/visitors/IpSpaceRepresentative.java, line 13 at r3](https://reviewable.io/reviews/batfish/batfish/1653#-LEusQUl3Bmtx8-sISgA:-LEuzf1q7AqkGrFkJiGL:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/63a9aa03261b5d8f475d2b73efdac870fa137471/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/visitors/IpSpaceRepresentative.java#L13)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Do I understand correctly that you are loading the service every time you want a representative?
Why not just have a static method that returns a `IpSpaceRepresentative` concrete class instance?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1653)*

**Comment by arifogel** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed, 1 unresolved discussion (waiting on @anothermattbrown)

---

*[projects/batfish/src/test/java/org/batfish/datamodel/visitors/IpSpaceRepresentativeTest.java, line 29 at r4](https://reviewable.io/reviews/batfish/batfish/1653#-LEvBv1HBibjjn4IjdHe:-LEvBv1HBibjjn4IjdHf:b-7vg4sn) ([raw file](https://github.com/batfish/batfish/blob/87c5050651d7b14f24357a43a27f1c3001bb1bc4/projects/batfish/src/test/java/org/batfish/datamodel/visitors/IpSpaceRepresentativeTest.java#L29)):*
> ```Java
>             .build();
>     assertThat(
>         IpSpaceRepresentative.load().getRepresentative(ipSpace),
> ```

..you could just load this in setup, or once for the whole class. less important since this is a test class, but still..

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1653)*

**Comment by anothermattbrown** [comment]
Review status: 1 of 3 files reviewed, all discussions resolved (waiting on @arifogel)

---

*[projects/batfish/src/test/java/org/batfish/datamodel/visitors/IpSpaceRepresentativeTest.java, line 29 at r4](https://reviewable.io/reviews/batfish/batfish/1653#-LEvBv1HBibjjn4IjdHe:-LEvCDDs-Xr4oSfwR89Q:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/87c5050651d7b14f24357a43a27f1c3001bb1bc4/projects/batfish/src/test/java/org/batfish/datamodel/visitors/IpSpaceRepresentativeTest.java#L29)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

..you could just load this in setup, or once for the whole class. less important since this is a test class, but still..
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1653)*

**Comment by arifogel** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r5.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1653#-:-LEvFe0A9UvWZ-JFiQO_:bnfp4nl)*

**Pull request merged**
