### PR TITLE
ImmutableBDDInteger: optimize toBDD(IpWildcard) 

### PR DESCRIPTION
**Pull request by anothermattbrown**
Speedups per BenchmarkIpWildcardToBdd:
- 3.56x for IPs
- 1.72x for prefixes (tested with /24s)
- 1.12x for wildcards (tested with second octet wildcarded)

Also, we are now using andLiterals, which avoids putting trivial operations into the BDD operator cache.

### CODE REVIEW

**Comment by dhalperi** [comment]
*[`library_deps.bzl` line 65 at r1](https://reviewable.io/reviews/batfish/batfish/8448#-N8kJr2s9ZKJcIroFjol:-N8kJr2s9ZKJcIroFjom:b-5q9sgr) ([raw file](https://github.com/batfish/batfish/blob/3de743380ff20d0d5d26f66f2d31c2060556246a/library_deps.bzl#L65)):*
> ```Starlark
>     "org.jgrapht:jgrapht-core:1.3.1",
>     "org.jline:jline:3.13.1",
>     "org.openjdk.jmh:jmh-core:1.35",
> ```

Since JMH is GPL, I'd not like it to even be in the same `@maven` scope. For JOL, I created a separate `maven_install.json`.



_Code quote:_
```Starlark
org.openjdk.jmh:jmh-cor
```

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8448)* status: 2 of 6 files reviewed, 2 unresolved discussions (waiting on @anothermattbrown and @dhalperi)

___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/ImmutableBDDInteger.java` line 92 at r1](https://reviewable.io/reviews/batfish/batfish/8448#-N8kLIvfBSVSxEduJ2X7:-N8kLIvfBSVSxEduJ2X8:b-uz1l01) ([raw file](https://github.com/batfish/batfish/blob/3de743380ff20d0d5d26f66f2d31c2060556246a/projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/ImmutableBDDInteger.java#L92)):*
> ```Java
>       bit <<= 1;
>     }
>     assert sigBits < Prefix.MAX_PREFIX_LENGTH;
> ```

https://docs.oracle.com/javase/7/docs/api/java/lang/Long.html#bitCount(long) ? Note that can use the built-in popcount instruction on some architectures.



_Code quote:_
```Java
    int sigBits = 0;
    int bit = 1;
    for (int i = 0; i < Prefix.MAX_PREFIX_LENGTH; i++) {
      if ((wildcard & bit) == 0) {
        sigBits++;
      }
      bit <<= 1;
    }
    assert sigBits < Prefix.MAX_PREFIX_LENGTH;
```
___
*[`tools/benchmarks/BenchmarkIpWildcardToBdd.java` line 37 at r1](https://reviewable.io/reviews/batfish/batfish/8448#-N8kM6yr3p0odgH1WFQ7:-N8kM6yr3p0odgH1WFQ8:b-k9otcz) ([raw file](https://github.com/batfish/batfish/blob/3de743380ff20d0d5d26f66f2d31c2060556246a/tools/benchmarks/BenchmarkIpWildcardToBdd.java#L37)):*
> ```Java
>     return Ip.create(Math.abs(_rng.nextInt()));
>   }
> ```

Wondering: using random in the hot code doesn't mess up the results? It's been a long time, but I am more used to, say, pre-allocating some large number of values during setUp and just cycling over them in the benchmark.



_Code quote:_
```Java
  private Ip randomIp() {
    return Ip.create(Math.abs(_rng.nextInt()));
  }
```

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8448)* status: 2 of 6 files reviewed, 3 unresolved discussions (waiting on @anothermattbrown and @dhalperi)

___
*[`skylark/jmh.bzl` line 14 at r2](https://reviewable.io/reviews/batfish/batfish/8448#-N8kMTphECvCNDZ4ylak:-N8kMTphECvCNDZ4ylal:bl6sk9) ([raw file](https://github.com/batfish/batfish/blob/517fcba91c1d95f54092031ad137164c98c4c30d/skylark/jmh.bzl#L14)):*
> ```Starlark
>         visibility = ["//visibility:private"],
>         tags = tags,
>     )
> ```

can we not just create the same plugin once and use the same one for every target? That's what we do for AutoService, e.g.,



_Code quote:_
```Starlark
    plugin_name = "_{}_jmh_annotation_processor".format(name)
    native.java_plugin(
        name = plugin_name,
        deps = ["@maven//:org_openjdk_jmh_jmh_generator_annprocess"],
        processor_class = "org.openjdk.jmh.generators.BenchmarkProcessor",
        visibility = ["//visibility:private"],
        tags = tags,
    )
```

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8448)* status: all files reviewed, 3 unresolved discussions (waiting on @anothermattbrown)

**Review by dhalperi — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8448#-:-N8yLyrMA7bgSc_rKN5U:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown)

**Review by anothermattbrown — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8448)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown)

___
*[`library_deps.bzl` line 65 at r1](https://reviewable.io/reviews/batfish/batfish/8448#-N8kJr2s9ZKJcIroFjol:-N8kQJYA9tOjsjJlv1xa:b-b7bvq) ([raw file](https://github.com/batfish/batfish/blob/3de743380ff20d0d5d26f66f2d31c2060556246a/library_deps.bzl#L65)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Since JMH is GPL, I'd not like it to even be in the same `@maven` scope. For JOL, I created a separate `maven_install.json`.
</blockquote></details>

makes sense. I'll do that
___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/ImmutableBDDInteger.java` line 92 at r1](https://reviewable.io/reviews/batfish/batfish/8448#-N8kLIvfBSVSxEduJ2X7:-N8kQRxrDvHTpEA6uGus:bfndei) ([raw file](https://github.com/batfish/batfish/blob/3de743380ff20d0d5d26f66f2d31c2060556246a/projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/ImmutableBDDInteger.java#L92)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

https://docs.oracle.com/javase/7/docs/api/java/lang/Long.html#bitCount(long) ? Note that can use the built-in popcount instruction on some architectures.
</blockquote></details>

oooh fancy!

**Pull request merged**
