### PR TITLE
Arista EOS warn on varp syntax and grammar fix

### PR DESCRIPTION
**Pull request by arifogel**
- top-level: `ip virtual-router mac-address`
- interface: `ip virtual-router address`
  - support either IP address or prefix argument

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7866)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/arista/Legacy_interface.g4, line 616 at r1](https://reviewable.io/reviews/batfish/batfish/7866#-MryBR5hEgZYpylEW6PE:-MryBR5hEgZYpylEW6PF:bm18hrz) ([raw file](https://github.com/batfish/batfish/blob/006ccad187e2c57499ed659d7d41734ddb92ba12/projects/batfish/src/main/antlr4/org/batfish/grammar/arista/Legacy_interface.g4#L616)):*
> ```ANTLR
> ;
> 
> if_ip_virtual_router
> ```

If you actually fleshed the grammar out, can you move it to `Arista_interface.g4`?
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/arista/Legacy_interface.g4, line 621 at r1](https://reviewable.io/reviews/batfish/batfish/7866#-MryB_O-1gj_J-CoW4X6:-MryB_O-1gj_J-CoW4X7:b-louaeu) ([raw file](https://github.com/batfish/batfish/blob/006ccad187e2c57499ed659d7d41734ddb92ba12/projects/batfish/src/main/antlr4/org/batfish/grammar/arista/Legacy_interface.g4#L621)):*
> ```ANTLR
> ;
> 
> if_ipv6
> ```

(FYI) were you going to delete from the other grammars?

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7866)* status: 4 of 9 files reviewed, all discussions resolved (waiting on @dhalperi)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/arista/Legacy_interface.g4, line 616 at r1](https://reviewable.io/reviews/batfish/batfish/7866#-MryBR5hEgZYpylEW6PE:-MryGjAS1SVkkqg6LVYc:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/006ccad187e2c57499ed659d7d41734ddb92ba12/projects/batfish/src/main/antlr4/org/batfish/grammar/arista/Legacy_interface.g4#L616)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

If you actually fleshed the grammar out, can you move it to `Arista_interface.g4`?
</blockquote></details>

done
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/arista/Legacy_interface.g4, line 621 at r1](https://reviewable.io/reviews/batfish/batfish/7866#-MryB_O-1gj_J-CoW4X6:-MryGhfx-33DqGWiLu11:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/006ccad187e2c57499ed659d7d41734ddb92ba12/projects/batfish/src/main/antlr4/org/batfish/grammar/arista/Legacy_interface.g4#L621)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

(FYI) were you going to delete from the other grammars?
</blockquote></details>

done

**Review by dhalperi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7866)* status: 4 of 9 files reviewed, 1 unresolved discussion (waiting on @arifogel and @dhalperi)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/arista/Legacy_interface.g4, line 582 at r2](https://reviewable.io/reviews/batfish/batfish/7866#-MryH9al1-sDLHL_gBj1:-MryH9al1-sDLHL_gBj2:blsidf0) ([raw file](https://github.com/batfish/batfish/blob/70649cde9267e4ea1d02e497a9f7c54a1073cd41/projects/batfish/src/main/antlr4/org/batfish/grammar/arista/Legacy_interface.g4#L582)):*
> ```ANTLR
> ;
> 
> ifipp_sparse_mode_eos
> ```

gosh dang it, I meant add `_eos` suffix is apparently the convention in this interface grammar.

Too many different conventions to keep them all straight, sorry.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7866)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7866)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel)

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7866)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/arista/Legacy_interface.g4, line 582 at r2](https://reviewable.io/reviews/batfish/batfish/7866#-MryH9al1-sDLHL_gBj1:-MryLWFJ8uJGywc01-8z:bo5bbuj) ([raw file](https://github.com/batfish/batfish/blob/70649cde9267e4ea1d02e497a9f7c54a1073cd41/projects/batfish/src/main/antlr4/org/batfish/grammar/arista/Legacy_interface.g4#L582)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

gosh dang it, I meant add `_eos` suffix is apparently the convention in this interface grammar.

Too many different conventions to keep them all straight, sorry.
</blockquote></details>

as discussed offline, will keep this move and move other rules afterwards.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7866)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @arifogel)

**Review by dhalperi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7866)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Pull request merged**
