### PR TITLE
bazel: move more test targets into src/test

### PR DESCRIPTION
**Pull request by dhalperi**

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8519)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dhalperi)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 13 of 14 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8519)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dhalperi)

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8519)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[`projects/bdd/src/test/java/BUILD` line 23 at r1](https://reviewable.io/reviews/batfish/batfish/8519#-NAglvMz8_kxDq_eRVgu:-NAglvN-55Sx4vK6oZsx:bd6en89) ([raw file](https://github.com/batfish/batfish/blob/ea5d80df5c56092468f89bdb60216b246cbd2178/projects/bdd/src/test/java/BUILD#L23)):*
> ```Starlark
> 
> pmd_test(
>     name = "bdd_testlib_pmd",
> ```

No biggy, but would have preferred you left this in as manual. Not worth more than a minute of your time.

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8519)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dhalperi)

___
*[`projects/bdd/src/test/java/BUILD` line 23 at r1](https://reviewable.io/reviews/batfish/batfish/8519#-NAglvMz8_kxDq_eRVgu:-NAjgmDZ9giVtnR6nEwe:brienp2) ([raw file](https://github.com/batfish/batfish/blob/ea5d80df5c56092468f89bdb60216b246cbd2178/projects/bdd/src/test/java/BUILD#L23)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

No biggy, but would have preferred you left this in as manual. Not worth more than a minute of your time.
</blockquote></details>

This project isn't suitable for PMD, it was written with different standards. If someone wants to fix that, it will be no trouble for them to add back in the useless target.

**Pull request merged**
