### PR TITLE
Adding more logs for insights

### PR DESCRIPTION
**Pull request by haverma**
Starting with some logs to capture information about

1. A new container, its API key
2. Testrigs associated with a container
3. List of analyses
4. Question associated with analyses
5. Parameters for analysis questions
6. Computation time per analysis question
7. Analysis Questions needing data plane
8. Status of Analysis questions

---
This change is [Reviewable](https://reviewable.io/reviews/batfish/batfish/789)

### CODE REVIEW

**Comment by haverma** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 519 at r1](https://reviewable.io:443/reviews/batfish/batfish/789#-L0p46CL_FmuI_s9wlbL:-L0p46CL_FmuI_s9wlbM:bf8y0gx) ([raw file](https://github.com/batfish/batfish/blob/e3a3c7ddd8fdcaee18cc30b1d1f45add331b784e/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L519)):*
> ```Java
>                     String.format(
>                         "Ran question %s from analysis %s: %s\n",
>                         questionName, analysisName, mapper.writeValueAsString(answerInfo)));
> ```

I will need to log container name as well here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/789)*

**Comment by dhalperi** [comment]
*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 509 at r1](https://reviewable.io:443/reviews/batfish/batfish/789#-L0pa-XvL2vbqr6KNTxj:-L0pa-XvL2vbqr6KNTxk:bhu6wc9) ([raw file](https://github.com/batfish/batfish/blob/e3a3c7ddd8fdcaee18cc30b1d1f45add331b784e/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L509)):*
> ```Java
>             long beforeTime = System.currentTimeMillis();
>             Answer currentAnswer = answer();
>             double timeTakenInSeconds = _logger.getElapsedTime(beforeTime);
> ```

Why not just log started answering question and finished answering question?

There's a tension/tradeoff in monitoring between the complexity of the logging code vs the ability to assemble the things you need later. In this case, I think a start timestamp and a stop timestamp would be good enough as long as we can join on work item ID / open tracing span etc.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/789)*

**Comment by dhalperi** [comment]
Review status: 0 of 7 files reviewed at latest revision, 6 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/BatfishLogger.java, line 252 at r1](https://reviewable.io:443/reviews/batfish/batfish/789#-L0p__-rHL-fKMgPH5wL:-L0p__-rHL-fKMgPH5wM:bf34kjl) ([raw file](https://github.com/batfish/batfish/blob/e3a3c7ddd8fdcaee18cc30b1d1f45add331b784e/projects/batfish-common-protocol/src/main/java/org/batfish/common/BatfishLogger.java#L252)):*
> ```Java
>   }
> 
>   public double getElapsedTime(long beforeTime) {
> ```

this internal utility method should not become public.

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 507 at r1](https://reviewable.io:443/reviews/batfish/batfish/789#-L0paej__UqdPCVj0wnw:-L0paej__UqdPCVj0wnx:b-3il7tv) ([raw file](https://github.com/batfish/batfish/blob/e3a3c7ddd8fdcaee18cc30b1d1f45add331b784e/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L507)):*
> ```Java
>             Path analysisQuestionPath = analysisQuestionDir.resolve(BfConsts.RELPATH_QUESTION_FILE);
>             _settings.setQuestionPath(analysisQuestionPath);
>             long beforeTime = System.currentTimeMillis();
> ```

Why isn't this something that we trace? We should be able to join logs and traces eventually.

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 519 at r1](https://reviewable.io:443/reviews/batfish/batfish/789#-L0paXjEueRgG0Z8hu9e:-L0paXjEueRgG0Z8hu9f:b-mz0arl) ([raw file](https://github.com/batfish/batfish/blob/e3a3c7ddd8fdcaee18cc30b1d1f45add331b784e/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L519)):*
> ```Java
>                     String.format(
>                         "Ran question %s from analysis %s: %s\n",
>                         questionName, analysisName, mapper.writeValueAsString(answerInfo)));
> ```

Don't construct an entire class just to be able to print some things out. Just log the things.

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java, line 1651 at r1](https://reviewable.io:443/reviews/batfish/batfish/789#-L0p_kqDr6lEaYEBT1dX:-L0p_kqDr6lEaYEBT1dY:bcsxk49) ([raw file](https://github.com/batfish/batfish/blob/e3a3c7ddd8fdcaee18cc30b1d1f45add331b784e/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java#L1651)):*
> ```Java
> 
>       Main.getWorkMgr().uploadTestrig(containerName, testrigName, fileStream, autoAnalyze);
>       _logger.info(
> ```

The logger functions have `infof` forms that include the formatting internally. please use those.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/789)*

**Comment by dhalperi** [comment]
*[a discussion](https://reviewable.io:443/reviews/batfish/batfish/789#-L0pbi4OqnDBW_JMziVV:-L0pbi4OqnDBW_JMziVW:bchdrgs) (no related file):*
I think a meta comment would be: what makes good logs for use in these types of applications? What can we do to get our logs to be in that format?

I suspect we should soon abandon BatfishLogger and switch back to one of the standard logging frameworks which has a standard structured logging integration.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/789)*

**Comment by haverma** [comment]
Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/batfish/batfish/789#-L0pbi4OqnDBW_JMziVV:-L0wgpouK5CQ9madEBn3:b-wgqi0a) (no related file):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I think a meta comment would be: what makes good logs for use in these types of applications? What can we do to get our logs to be in that format?

I suspect we should soon abandon BatfishLogger and switch back to one of the standard logging frameworks which has a standard structured logging integration.
</blockquote></details>

Discussed in person 

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 507 at r1](https://reviewable.io:443/reviews/batfish/batfish/789#-L0paej__UqdPCVj0wnw:-L0wgT6iKPu3ieSc76AH:b-ys6ow9) ([raw file](https://github.com/batfish/batfish/blob/e3a3c7ddd8fdcaee18cc30b1d1f45add331b784e/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L507)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Why isn't this something that we trace? We should be able to join logs and traces eventually.
</blockquote></details>

Now tracing this part so duration will be stored in span

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 509 at r1](https://reviewable.io:443/reviews/batfish/batfish/789#-L0pa-XvL2vbqr6KNTxj:-L0wgZipiWDGiOVMN-Jb:bklrsae) ([raw file](https://github.com/batfish/batfish/blob/e3a3c7ddd8fdcaee18cc30b1d1f45add331b784e/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L509)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Why not just log started answering question and finished answering question?

There's a tension/tradeoff in monitoring between the complexity of the logging code vs the ability to assemble the things you need later. In this case, I think a start timestamp and a stop timestamp would be good enough as long as we can join on work item ID / open tracing span etc.
</blockquote></details>

tracing obviated the need to capture start time and stop time

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 519 at r1](https://reviewable.io:443/reviews/batfish/batfish/789#-L0paXjEueRgG0Z8hu9e:-L0wgkWN02PmYm5WtpC-:b-hfpv0l) ([raw file](https://github.com/batfish/batfish/blob/e3a3c7ddd8fdcaee18cc30b1d1f45add331b784e/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L519)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Don't construct an entire class just to be able to print some things out. Just log the things.
</blockquote></details>

removed

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 519 at r1](https://reviewable.io:443/reviews/batfish/batfish/789#-L0p46CL_FmuI_s9wlbL:-L0whEaF1ZE7O-D7ICWJ:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/e3a3c7ddd8fdcaee18cc30b1d1f45add331b784e/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L519)):*
<details><summary><i>Previously, haverma (Harsh Verma) wrote…</i></summary><blockquote>

I will need to log container name as well here
</blockquote></details>

Done.

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java, line 1651 at r1](https://reviewable.io:443/reviews/batfish/batfish/789#-L0p_kqDr6lEaYEBT1dX:-L0wgm3-WWg9Vd55px6t:bb7q05e) ([raw file](https://github.com/batfish/batfish/blob/e3a3c7ddd8fdcaee18cc30b1d1f45add331b784e/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java#L1651)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

The logger functions have `infof` forms that include the formatting internally. please use those.
</blockquote></details>

used

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/BatfishLogger.java, line 252 at r1](https://reviewable.io:443/reviews/batfish/batfish/789#-L0p__-rHL-fKMgPH5wL:-L0wgnRYB-S6uFJCPhQB:bvth56w) ([raw file](https://github.com/batfish/batfish/blob/e3a3c7ddd8fdcaee18cc30b1d1f45add331b784e/projects/batfish-common-protocol/src/main/java/org/batfish/common/BatfishLogger.java#L252)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

this internal utility method should not become public.
</blockquote></details>

reverted

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/789)*

**Comment by dhalperi** [comment]
:lgtm: Nice

---

Reviewed 4 of 7 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 507 at r1](https://reviewable.io:443/reviews/batfish/batfish/789#-L0paej__UqdPCVj0wnw:-L0zb0VWfuEhr3psEbRy:bb70w76) ([raw file](https://github.com/batfish/batfish/blob/e3a3c7ddd8fdcaee18cc30b1d1f45add331b784e/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L507)):*
<details><summary><i>Previously, haverma (Harsh Verma) wrote…</i></summary><blockquote>

Now tracing this part so duration will be stored in span
</blockquote></details>

Nice

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/789#-:-L0zbCjH5xMpS_NUckWp:bb6m2cs)*

**Pull request merged**
