### PR TITLE
JunOS: Support As-Path-Group

### PR DESCRIPTION
**Pull request by ktaegyum**
Add support for as-path-group in JunOS.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8613)* status: all files reviewed, 7 unresolved discussions (waiting on @ktaegyum)

___
*[`projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java` line 3007 at r1](https://reviewable.io/reviews/batfish/batfish/8613#-NIZ18qB8JfjP77tYGfl:-NIZ18qB8JfjP77tYGfm:b-n6pnfc) ([raw file](https://github.com/batfish/batfish/blob/8032c215cbe220f2a82017d723d0ceda11b46397/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L3007)):*
> ```Java
>   public void exitPo_as_path_group(Po_as_path_groupContext ctx) {
>       String name = toString(ctx.name);
>       _configuration.referenceStructure(
> ```

`as-path-group` should not have a self reference, should it? It should be tracked as an unused structure if it's not referred to.
___
*[`projects/batfish/src/main/java/org/batfish/representation/juniper/AsPathGroup.java` line 31 at r1](https://reviewable.io/reviews/batfish/batfish/8613#-NIZ1NUQEr-z9_YExpHO:-NIZ1NUQEr-z9_YExpHP:bmkgdxt) ([raw file](https://github.com/batfish/batfish/blob/8032c215cbe220f2a82017d723d0ceda11b46397/projects/batfish/src/main/java/org/batfish/representation/juniper/AsPathGroup.java#L31)):*
> ```Java
>   }
> 
>   public @Nonnull List<String> getAsPathRegexes() {
> ```

why is this needed here? This seems like a thing to do in conversion.
___
*[`projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java` line 3144 at r1](https://reviewable.io/reviews/batfish/batfish/8613#-NIZ1S9c1ACRZe1nOu-u:-NIZ1S9c1ACRZe1nOu-v:b-g8za6p) ([raw file](https://github.com/batfish/batfish/blob/8032c215cbe220f2a82017d723d0ceda11b46397/projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java#L3144)):*
> ```Java
>       conj.getConjuncts().add(new Disjunction(toBooleanExprs(froms.getFromAsPaths())));
>     }
>     if (!froms.getFromAsPathGroups().isEmpty()) {
> ```

please add a TODO: can you have both as-path and as-path-group together, and how does it work?
___
*[`projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperStructureUsage.java` line 11 at r1](https://reviewable.io/reviews/batfish/batfish/8613#-NIZ1_YmEFqKjBVVhXp9:-NIZ1_YmEFqKjBVVhXpA:bn26jfq) ([raw file](https://github.com/batfish/batfish/blob/8032c215cbe220f2a82017d723d0ceda11b46397/projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperStructureUsage.java#L11)):*
> ```Java
>   APPLICATION_SET_MEMBER_APPLICATION("application-set member application"),
>   APPLICATION_SET_MEMBER_APPLICATION_SET("application-set member application-set"),
>   AS_PATH_GROUP_SELF_REFERENCE("as-path-group"),
> ```

as discussed, drop?
___
*[`projects/batfish/src/main/java/org/batfish/representation/juniper/PsFromAsPathGroup.java` line 39 at r1](https://reviewable.io/reviews/batfish/batfish/8613#-NIZ1jh6-SY-LMC90xi2:-NIZ1jh6-SY-LMC90xi3:b6ujzul) ([raw file](https://github.com/batfish/batfish/blob/8032c215cbe220f2a82017d723d0ceda11b46397/projects/batfish/src/main/java/org/batfish/representation/juniper/PsFromAsPathGroup.java#L39)):*
> ```Java
>             asPathGroup
>                     .getAsPathRegexes()
>                     .forEach(
> ```

please just use a regular for loop. This code is so hard to read.
___
*[`projects/batfish/src/main/java/org/batfish/representation/juniper/PsFromAsPathGroup.java` line 44 at r1](https://reviewable.io/reviews/batfish/batfish/8613#-NIZ1oQL0a4ibHsEBFiB:-NIZ1oQL0a4ibHsEBFiC:b-nbvkg3) ([raw file](https://github.com/batfish/batfish/blob/8032c215cbe220f2a82017d723d0ceda11b46397/projects/batfish/src/main/java/org/batfish/representation/juniper/PsFromAsPathGroup.java#L44)):*
> ```Java
>                                             org.batfish.representation.juniper.parboiled.AsPathRegex.convertToJavaRegex(
>                                                     regex)));
>             String ORedRegexes = String.join(" | ", javaRegex);
> ```

Moving this into the regex is the wrong way to do it. Don't we have an `OrExpr`?
___
*[`tests/parsing-tests/networks/unit-tests/configs/juniper_policy_statement` line 46 at r1](https://reviewable.io/reviews/batfish/batfish/8613#-NIZ28C6DnaLUldr96-v:-NIZ28C6DnaLUldr96-w:b-2yrt6r) ([raw file](https://github.com/batfish/batfish/blob/8032c215cbe220f2a82017d723d0ceda11b46397/tests/parsing-tests/networks/unit-tests/configs/juniper_policy_statement#L46)):*
> ```
> set policy-options as-path ORIGINATED_IN_65535 ".* 65535"
> set policy-options as-path UNUSED_ORIGINATED_IN_65535 ".* 65535"
> set policy-options as-path-group AS_PATH_GROUP as-path ASN714 ".* 714$"
> ```

use private ASes for this. Maybe 65535 and 65534?



_Code quote:_
```
ASN714 "
```

**Comment by ktaegyum** [comment]
*[`projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java` line 3007 at r1](https://reviewable.io/reviews/batfish/batfish/8613#-NIZ18qB8JfjP77tYGfl:-NIZdHbNEs8v5fP7sKEK:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/8032c215cbe220f2a82017d723d0ceda11b46397/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L3007)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

`as-path-group` should not have a self reference, should it? It should be tracked as an unused structure if it's not referred to.
</blockquote></details>

done

**Review by ktaegyum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8613)* status: 3 of 11 files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[`projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java` line 3144 at r1](https://reviewable.io/reviews/batfish/batfish/8613#-NIZ1S9c1ACRZe1nOu-u:-NIZdJk_6gg6Is4xnve6:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/8032c215cbe220f2a82017d723d0ceda11b46397/projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java#L3144)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

please add a TODO: can you have both as-path and as-path-group together, and how does it work?
</blockquote></details>

done
___
*[`projects/batfish/src/main/java/org/batfish/representation/juniper/PsFromAsPathGroup.java` line 39 at r1](https://reviewable.io/reviews/batfish/batfish/8613#-NIZ1jh6-SY-LMC90xi2:-NIZdKyQ5chzqvb-N0A7:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/8032c215cbe220f2a82017d723d0ceda11b46397/projects/batfish/src/main/java/org/batfish/representation/juniper/PsFromAsPathGroup.java#L39)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

please just use a regular for loop. This code is so hard to read.
</blockquote></details>

done
___
*[`projects/batfish/src/main/java/org/batfish/representation/juniper/PsFromAsPathGroup.java` line 44 at r1](https://reviewable.io/reviews/batfish/batfish/8613#-NIZ1oQL0a4ibHsEBFiB:-NIZdLfk4Wrl5R3g_LTo:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/8032c215cbe220f2a82017d723d0ceda11b46397/projects/batfish/src/main/java/org/batfish/representation/juniper/PsFromAsPathGroup.java#L44)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Moving this into the regex is the wrong way to do it. Don't we have an `OrExpr`?
</blockquote></details>

done
___
*[`tests/parsing-tests/networks/unit-tests/configs/juniper_policy_statement` line 46 at r1](https://reviewable.io/reviews/batfish/batfish/8613#-NIZ28C6DnaLUldr96-v:-NIZdMqmElXI7ou15fZk:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/8032c215cbe220f2a82017d723d0ceda11b46397/tests/parsing-tests/networks/unit-tests/configs/juniper_policy_statement#L46)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

use private ASes for this. Maybe 65535 and 65534?
</blockquote></details>

done
___
*[`projects/batfish/src/main/java/org/batfish/representation/juniper/AsPathGroup.java` line 31 at r1](https://reviewable.io/reviews/batfish/batfish/8613#-NIZ1NUQEr-z9_YExpHO:-NIZdNj21u1RAzwa91UW:b-hfpv0l) ([raw file](https://github.com/batfish/batfish/blob/8032c215cbe220f2a82017d723d0ceda11b46397/projects/batfish/src/main/java/org/batfish/representation/juniper/AsPathGroup.java#L31)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

why is this needed here? This seems like a thing to do in conversion.
</blockquote></details>

removed
___
*[`projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperStructureUsage.java` line 11 at r1](https://reviewable.io/reviews/batfish/batfish/8613#-NIZ1_YmEFqKjBVVhXp9:-NIZdP6lDlDkoRxdyMVJ:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/8032c215cbe220f2a82017d723d0ceda11b46397/projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperStructureUsage.java#L11)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

as discussed, drop?
</blockquote></details>

done

**Review by dhalperi — COMMENTED** [review]
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8613)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ktaegyum)

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8613)* status: all files reviewed, 1 unresolved discussion (waiting on @ktaegyum)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/8613#-NIZkSf1-f9IsL2e6kLd:-NIZkSf1-f9IsL2e6kLe:b-k9j9rm) (no related file):*
Missing test coverage! I think we need to extend the tests here. 

https://github.com/batfish/batfish/blob/6b9b5be49693fadaffff237b8f84e2b2a969b331/projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-policy-statement-term#L23

and here

https://github.com/batfish/batfish/blob/6b9b5be49693fadaffff237b8f84e2b2a969b331/projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java#L4477

___

**Review by ktaegyum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8613)* status: 11 of 13 files reviewed, 1 unresolved discussion (waiting on @dhalperi)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/8613#-NIZkSf1-f9IsL2e6kLd:-NI_4xLsENsLaDfXhsEP:b-xql2uh) (no related file):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Missing test coverage! I think we need to extend the tests here. 

https://github.com/batfish/batfish/blob/6b9b5be49693fadaffff237b8f84e2b2a969b331/projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/juniper-policy-statement-term#L23

and here

https://github.com/batfish/batfish/blob/6b9b5be49693fadaffff237b8f84e2b2a969b331/projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java#L4477
</blockquote></details>

test added.

___

**Pull request merged**
