### PR TITLE
Cisco IOS object-group network (partial)

### PR DESCRIPTION
**Pull request by arifogel**

### CODE REVIEW

**Comment by arifogel** [comment]
Review status: 0 of 25 files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://beta.reviewable.io/reviews/batfish/batfish/1204#-LAPfw5C93yFXhdcUveE:-LAPfw5C93yFXhdcUveF:b-dru77m) (no related file):*
After #1203

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1204)*

**Comment by sfraint** [comment]
Reviewed 23 of 25 files at r1.
Review status: 22 of 25 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-acl-object-group, line 1 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1204#-LAPwWp07jAvWQ2KgUDs:-LAPwWp19zLr3926BRpy:bus3u8o) ([raw file](https://github.com/batfish/batfish/blob/46c482c2e90c567748a795608085829983e78bb6/projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-acl-object-group#L1)):*
> ```
> !
> ```

What is this file used for?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1204)*

**Comment by arifogel** [comment]
Review status: 22 of 24 files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-acl-object-group, line 1 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1204#-LAPwWp07jAvWQ2KgUDs:-LAQ-jez4bo8Iiqb9PlW:b-d0qjd6) ([raw file](https://github.com/batfish/batfish/blob/46c482c2e90c567748a795608085829983e78bb6/projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-acl-object-group#L1)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

What is this file used for?
</blockquote></details>

Meant for different PR. Removed.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1204)*

**Comment by dhalperi** [comment]
Reviewed 1 of 25 files at r1, 5 of 19 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[test_rigs/parsing-tests/unit-tests-nodes.ref, line 8078 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1204#-LARYmaa9ucW55dMeZcg:-LARYmaa9ucW55dMeZch:baxl6m8) ([raw file](https://github.com/batfish/batfish/blob/75d6654d99cb1418555786962ba75456f5f20cf0/test_rigs/parsing-tests/unit-tests-nodes.ref#L8078)):*
> ```
>           },
>           "ntp_servers" : {
>             "class" : "org.batfish.datamodel.IpWildcardSetIpSpace"
> ```

I believe this is Cisco_qos, right?

```
object-group network dns_servers
 description External DNS Servers
 network-object host 1.2.2.1
object-group network ntp_servers
 description External NTP Servers
 network-object host 1.1.1.1
```

Looks like the hosts are missing?

---

*[test_rigs/parsing-tests/unit-tests-nodes.ref, line 8079 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1204#-LARZRYe0P66agWNmIhE:-LARZRYe0P66agWNmIhF:b-9fm6l6) ([raw file](https://github.com/batfish/batfish/blob/75d6654d99cb1418555786962ba75456f5f20cf0/test_rigs/parsing-tests/unit-tests-nodes.ref#L8079)):*
> ```
>           "ntp_servers" : {
>             "class" : "org.batfish.datamodel.IpWildcardSetIpSpace"
>           }
> ```

Is the description in the data model?

---

*[test_rigs/parsing-tests/unit-tests-nodes.ref, line 8080 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1204#-LARZTXZEkxzErb-GPtK:-LARZTXZEkxzErb-GPtL:b329vt9) ([raw file](https://github.com/batfish/batfish/blob/75d6654d99cb1418555786962ba75456f5f20cf0/test_rigs/parsing-tests/unit-tests-nodes.ref#L8080)):*
> ```
>             "class" : "org.batfish.datamodel.IpWildcardSetIpSpace"
>           }
>         },
> ```

Reference one of the two object groups somewhere, so we can confirm it doesn't show as unused?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1204)*

**Comment by arifogel** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[test_rigs/parsing-tests/unit-tests-nodes.ref, line 8078 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1204#-LARYmaa9ucW55dMeZcg:-LAS9_XBAb277Wo_6wSV:bpy28cp) ([raw file](https://github.com/batfish/batfish/blob/75d6654d99cb1418555786962ba75456f5f20cf0/test_rigs/parsing-tests/unit-tests-nodes.ref#L8078)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I believe this is Cisco_qos, right?

```
object-group network dns_servers
 description External DNS Servers
 network-object host 1.2.2.1
object-group network ntp_servers
 description External NTP Servers
 network-object host 1.1.1.1
```

Looks like the hosts are missing?
</blockquote></details>

We don't yet use 'network-object' line. It's out of scope for this PR (different language).

---

*[test_rigs/parsing-tests/unit-tests-nodes.ref, line 8079 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1204#-LARZRYe0P66agWNmIhE:-LAS9dl12ZIri-QJyf4O:b4yfq71) ([raw file](https://github.com/batfish/batfish/blob/75d6654d99cb1418555786962ba75456f5f20cf0/test_rigs/parsing-tests/unit-tests-nodes.ref#L8079)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Is the description in the data model?
</blockquote></details>

We don't yet use 'description' line. It's out of scope for this PR (different language).

---

*[test_rigs/parsing-tests/unit-tests-nodes.ref, line 8080 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1204#-LARZTXZEkxzErb-GPtK:-LAS9yLu4EaTPp73tPGz:b4p8g1k) ([raw file](https://github.com/batfish/batfish/blob/75d6654d99cb1418555786962ba75456f5f20cf0/test_rigs/parsing-tests/unit-tests-nodes.ref#L8080)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Reference one of the two object groups somewhere, so we can confirm it doesn't show as unused?
</blockquote></details>

I'm planning that in a different branch `ari-ios-acl-object-group` intended for a future PR. If you think it must go here, we should discuss.
But in that branch, see changes to `CiscoConfiguration.java`

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1204)*

**Comment by dhalperi** [comment]
All good -- just always reviewing the refs and spotting issues. As long as you are satisfied with how/when you'll make the changes, LGTM.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1204#-:-LATu2F-5i2XkpNANFG0:b-2os8sq)*

**Pull request merged**
