### PR TITLE
Use parallel streams for input routes in testRoutePolicies

### PR DESCRIPTION
**Pull request by ratulm**

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7875)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @millstein and @ratulm)

___
*[projects/question/src/main/java/org/batfish/question/testroutepolicies/TestRoutePoliciesAnswerer.java, line 143 at r1](https://reviewable.io/reviews/batfish/batfish/7875#-MsBs_1fB7uCf_WS8dYg:-MsBs_1fB7uCf_WS8dYh:b-4schjd) ([raw file](https://github.com/batfish/batfish/blob/e74945546b73c7938dcd0800b0b7819aa2b9c1f6/projects/question/src/main/java/org/batfish/question/testroutepolicies/TestRoutePoliciesAnswerer.java#L143)):*
> ```Java
>             .flatMap(
>                 policy ->
>                     _inputRoutes.parallelStream()
> ```

this does nothing, you cannot make an inner stream parallel.

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7875)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @millstein and @ratulm)

___
*[projects/question/src/main/java/org/batfish/question/testroutepolicies/TestRoutePoliciesAnswerer.java, line 160 at r1](https://reviewable.io/reviews/batfish/batfish/7875#-MsBtKTsEzIEg17XFYg_:-MsBtKTt2IQ5tdODgiKU:bl0oels) ([raw file](https://github.com/batfish/batfish/blob/e74945546b73c7938dcd0800b0b7819aa2b9c1f6/projects/question/src/main/java/org/batfish/question/testroutepolicies/TestRoutePoliciesAnswerer.java#L160)):*
> ```Java
>             policyId ->
>                 configs.get(policyId.getNode()).getRoutingPolicies().get(policyId.getPolicy()));
>   }
> ```

What the heck is going on here? It looks like we're creating `RoutingPolicyId` only to never use it -- immediately strip it off when used.

I think someone got stream-happy without thinking about clear code....



_Code quote:_
```Java
  private Stream<RoutingPolicy> getResults(
      SpecifierContext context, SortedSet<RoutingPolicyId> policies) {
    Map<String, Configuration> configs = context.getConfigs();
    return policies.stream()
        .map(
            policyId ->
                configs.get(policyId.getNode()).getRoutingPolicies().get(policyId.getPolicy()));
```

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7875)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @millstein and @ratulm)

**Review by millstein — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7875)* status: all files reviewed, 2 unresolved discussions (waiting on @dhalperi and @ratulm)

___
*[projects/question/src/main/java/org/batfish/question/testroutepolicies/TestRoutePoliciesAnswerer.java, line 160 at r1](https://reviewable.io/reviews/batfish/batfish/7875#-MsBtKTsEzIEg17XFYg_:-MsCAaxB6sXvdnu1RgL4:b-p237f1) ([raw file](https://github.com/batfish/batfish/blob/e74945546b73c7938dcd0800b0b7819aa2b9c1f6/projects/question/src/main/java/org/batfish/question/testroutepolicies/TestRoutePoliciesAnswerer.java#L160)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

What the heck is going on here? It looks like we're creating `RoutingPolicyId` only to never use it -- immediately strip it off when used.

I think someone got stream-happy without thinking about clear code....
</blockquote></details>

Yes, it looks unnecessary. I didn't write this code though so don't know the original rationale.

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7875)* status: all files reviewed, 2 unresolved discussions (waiting on @dhalperi)

___
*[projects/question/src/main/java/org/batfish/question/testroutepolicies/TestRoutePoliciesAnswerer.java, line 143 at r1](https://reviewable.io/reviews/batfish/batfish/7875#-MsBs_1fB7uCf_WS8dYg:-MsCBqDG4yOPyWcmljJO:b-ge3ivv) ([raw file](https://github.com/batfish/batfish/blob/e74945546b73c7938dcd0800b0b7819aa2b9c1f6/projects/question/src/main/java/org/batfish/question/testroutepolicies/TestRoutePoliciesAnswerer.java#L143)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

this does nothing, you cannot make an inner stream parallel.
</blockquote></details>

Hmm...is there a good pointer? Trying to understand semantics. 

In the code below, `outList` comes out unordered. 

```
  public void testTest() {
    final List<Integer> outList = new LinkedList<>();
    List<Integer> listOfNumbers = Arrays.asList(1, 2, 3, 4);
    listOfNumbers.stream()
        .forEach(number -> listOfNumbers.parallelStream().forEach(n2 -> outList.add(n2)));
  }
```

Is what happens is: Ordering is messed up but parallelism is not achieved?

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7875)* status: all files reviewed, 2 unresolved discussions (waiting on @dhalperi and @ratulm)

___
*[projects/question/src/main/java/org/batfish/question/testroutepolicies/TestRoutePoliciesAnswerer.java, line 143 at r1](https://reviewable.io/reviews/batfish/batfish/7875#-MsBs_1fB7uCf_WS8dYg:-MsCEXPv0oj4apTznF03:b-c0411q) ([raw file](https://github.com/batfish/batfish/blob/e74945546b73c7938dcd0800b0b7819aa2b9c1f6/projects/question/src/main/java/org/batfish/question/testroutepolicies/TestRoutePoliciesAnswerer.java#L143)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

Hmm...is there a good pointer? Trying to understand semantics. 

In the code below, `outList` comes out unordered. 

```
  public void testTest() {
    final List<Integer> outList = new LinkedList<>();
    List<Integer> listOfNumbers = Arrays.asList(1, 2, 3, 4);
    listOfNumbers.stream()
        .forEach(number -> listOfNumbers.parallelStream().forEach(n2 -> outList.add(n2)));
  }
```

Is what happens is: Ordering is messed up but parallelism is not achieved?

</blockquote></details>

the code you tested is different than the code being commented on....

flatmapping a stream to a parallelstream does nothing.

**Comment by dhalperi** [comment]
___
*[projects/question/src/main/java/org/batfish/question/testroutepolicies/TestRoutePoliciesAnswerer.java, line 143 at r1](https://reviewable.io/reviews/batfish/batfish/7875#-MsBs_1fB7uCf_WS8dYg:-MsCEhxXCMUarTdGphzD:bsosz0l) ([raw file](https://github.com/batfish/batfish/blob/e74945546b73c7938dcd0800b0b7819aa2b9c1f6/projects/question/src/main/java/org/batfish/question/testroutepolicies/TestRoutePoliciesAnswerer.java#L143)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

the code you tested is different than the code being commented on....

flatmapping a stream to a parallelstream does nothing.
</blockquote></details>

so if you did

```
listOfNumbers.stream().flatMap(n -> listOfNumbers.parallelStream()).forEach(outList::add);
```

They should not be out of order.

**Comment by dhalperi** [comment]
___
*[projects/question/src/main/java/org/batfish/question/testroutepolicies/TestRoutePoliciesAnswerer.java, line 143 at r1](https://reviewable.io/reviews/batfish/batfish/7875#-MsBs_1fB7uCf_WS8dYg:-MsCFppg2P2Ss4AY2QpE:bs0t568) ([raw file](https://github.com/batfish/batfish/blob/e74945546b73c7938dcd0800b0b7819aa2b9c1f6/projects/question/src/main/java/org/batfish/question/testroutepolicies/TestRoutePoliciesAnswerer.java#L143)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

so if you did

```
listOfNumbers.stream().flatMap(n -> listOfNumbers.parallelStream()).forEach(outList::add);
```

They should not be out of order.
</blockquote></details>

After fixing concurrency, I get this with the two algorithms:

```
Yours (with concurrency fixed):
[3, 4, 1, 2, 3, 4, 2, 1, 3, 2, 4, 1, 3, 2, 4, 1]

FlatMap:
[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]
```

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7875)* status: all files reviewed, 2 unresolved discussions (waiting on @dhalperi and @ratulm)

___
*[projects/question/src/main/java/org/batfish/question/testroutepolicies/TestRoutePoliciesAnswerer.java, line 143 at r1](https://reviewable.io/reviews/batfish/batfish/7875#-MsBs_1fB7uCf_WS8dYg:-MsCG5yK92jMmIJm_a_l:bo6bdt2) ([raw file](https://github.com/batfish/batfish/blob/e74945546b73c7938dcd0800b0b7819aa2b9c1f6/projects/question/src/main/java/org/batfish/question/testroutepolicies/TestRoutePoliciesAnswerer.java#L143)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

After fixing concurrency, I get this with the two algorithms:

```
Yours (with concurrency fixed):
[3, 4, 1, 2, 3, 4, 2, 1, 3, 2, 4, 1, 3, 2, 4, 1]

FlatMap:
[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]
```
</blockquote></details>

https://stackoverflow.com/questions/24411313/parallelism-and-flatmap-in-java-8-streams

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7875)* status: all files reviewed, 2 unresolved discussions (waiting on @dhalperi)

___
*[projects/question/src/main/java/org/batfish/question/testroutepolicies/TestRoutePoliciesAnswerer.java, line 143 at r1](https://reviewable.io/reviews/batfish/batfish/7875#-MsBs_1fB7uCf_WS8dYg:-MsCGpwi9s4t6ODC8F-D:b-k75l4w) ([raw file](https://github.com/batfish/batfish/blob/e74945546b73c7938dcd0800b0b7819aa2b9c1f6/projects/question/src/main/java/org/batfish/question/testroutepolicies/TestRoutePoliciesAnswerer.java#L143)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

https://stackoverflow.com/questions/24411313/parallelism-and-flatmap-in-java-8-streams
</blockquote></details>

Got it. So, I wanted to make the case of many inputRoutes perform better. 

Given that `rowResultFor(policy, route, _direction)` does the heavy lift, will its execution be parallelized (across input routes) in the way I did things? 

(No reason to not parallelize over policies too, but that wasn't the immediate goal.)

**Review by dhalperi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7875)* status: all files reviewed, 2 unresolved discussions (waiting on @dhalperi and @ratulm)

___
*[projects/question/src/main/java/org/batfish/question/testroutepolicies/TestRoutePoliciesAnswerer.java, line 143 at r1](https://reviewable.io/reviews/batfish/batfish/7875#-MsBs_1fB7uCf_WS8dYg:-MsCLmDODYmmp6KqdRMY:b-or7znn) ([raw file](https://github.com/batfish/batfish/blob/e74945546b73c7938dcd0800b0b7819aa2b9c1f6/projects/question/src/main/java/org/batfish/question/testroutepolicies/TestRoutePoliciesAnswerer.java#L143)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

Got it. So, I wanted to make the case of many inputRoutes perform better. 

Given that `rowResultFor(policy, route, _direction)` does the heavy lift, will its execution be parallelized (across input routes) in the way I did things? 

(No reason to not parallelize over policies too, but that wasn't the immediate goal.)
</blockquote></details>

Looking at the code as it currently is, (I had to jump into an editor to see) I don't think that either change will actually improve parallelism. Might be worth a call.

**Comment by ratulm** [comment]
Closing in favor of a better approach.

**Pull request closed without merging**
