### PR TITLE
Cisco IOS implement route-map set as-path replace

### PR DESCRIPTION
**Pull request by arifogel**
Fixes batfish/batfish#8059

- parse and convert route-map statement `set as-path replace`
- add new VI Statement for replacing elements of an as-path
- for now, just support replacing with local-as

Follow-on work:
- On IOS, should use confed insetad of local-as if in confed and neighbor is not in the confed

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 6 of 15 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8081)* status: 7 of 15 files reviewed, 3 unresolved discussions (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/representation/cisco/RouteMapSetAsPathReplaceAnyLine.java, line 30 at r2](https://reviewable.io/reviews/batfish/batfish/8081#-Mwj8GMbA58eDYolt33h:-Mwj8GMbA58eDYolt33i:b-v4w241) ([raw file](https://github.com/batfish/batfish/blob/670551263e1efeb1cbf079881ca86131656ce401/projects/batfish/src/main/java/org/batfish/representation/cisco/RouteMapSetAsPathReplaceAnyLine.java#L30)):*
> ```Java
>   public void applyTo(
>       List<Statement> statements, CiscoConfiguration cc, Configuration c, Warnings w) {
>     // TODO: confirm prepend occurs after replace
> ```

Docs say: https://content.cisco.com/chapter.sjs?uri=/searchable/chapter/content/en/us/td/docs/ios-xml/ios/iproute_bgp/configuration/xe-17/irg-xe-17-book/bgp-replace-ASNs.html.xml

* loop detection
* replace
* prepend

in that order
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco/RouteMapSetAsPathReplaceAnyLine.java, line 30 at r2](https://reviewable.io/reviews/batfish/batfish/8081#-Mwj8OqS1MdRox8dlS9s:-Mwj8OqS1MdRox8dlS9t:b-mpt5bt) ([raw file](https://github.com/batfish/batfish/blob/670551263e1efeb1cbf079881ca86131656ce401/projects/batfish/src/main/java/org/batfish/representation/cisco/RouteMapSetAsPathReplaceAnyLine.java#L30)):*
> ```Java
>   public void applyTo(
>       List<Statement> statements, CiscoConfiguration cc, Configuration c, Warnings w) {
>     // TODO: confirm prepend occurs after replace
> ```

Where is this implemented?
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/ReplaceAsesInAsSequence.java, line 58 at r2](https://reviewable.io/reviews/batfish/batfish/8081#-Mwj9MQJ32Uy5iTkTXAG:-Mwj9MQJ32Uy5iTkTXAH:b-vwggqr) ([raw file](https://github.com/batfish/batfish/blob/670551263e1efeb1cbf079881ca86131656ce401/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/ReplaceAsesInAsSequence.java#L58)):*
> ```Java
>   }
> 
>   private static final class AnyAs implements AsSequenceExpr {
> ```

This all needs to be public, right? Otherwise, how will searchRoutePolicies do its thing?

cc: @millstein

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8081)* status: 7 of 15 files reviewed, 3 unresolved discussions (waiting on @corinaminer, @dhalperi, and @millstein)

___
*[projects/batfish/src/main/java/org/batfish/representation/cisco/RouteMapSetAsPathReplaceAnyLine.java, line 30 at r2](https://reviewable.io/reviews/batfish/batfish/8081#-Mwj8GMbA58eDYolt33h:-MwjGStEALtF7JVq9vCE:bk9oyg8) ([raw file](https://github.com/batfish/batfish/blob/670551263e1efeb1cbf079881ca86131656ce401/projects/batfish/src/main/java/org/batfish/representation/cisco/RouteMapSetAsPathReplaceAnyLine.java#L30)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Docs say: https://content.cisco.com/chapter.sjs?uri=/searchable/chapter/content/en/us/td/docs/ios-xml/ios/iproute_bgp/configuration/xe-17/irg-xe-17-book/bgp-replace-ASNs.html.xml

* loop detection
* replace
* prepend

in that order
</blockquote></details>

Loop detection should happen before incoming transformation, and is irrelevant for outgoing transformation, so that much is fine.
Updated conversion to ensure prepend is after all replaces.
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco/RouteMapSetAsPathReplaceAnyLine.java, line 30 at r2](https://reviewable.io/reviews/batfish/batfish/8081#-Mwj8OqS1MdRox8dlS9s:-MwjGlZ6Bi2YGJ9o2uSW:b-lbv2xr) ([raw file](https://github.com/batfish/batfish/blob/670551263e1efeb1cbf079881ca86131656ce401/projects/batfish/src/main/java/org/batfish/representation/cisco/RouteMapSetAsPathReplaceAnyLine.java#L30)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Where is this implemented?
</blockquote></details>

Where is what implemented?
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/ReplaceAsesInAsSequence.java, line 58 at r2](https://reviewable.io/reviews/batfish/batfish/8081#-Mwj9MQJ32Uy5iTkTXAG:-MwjGpIi3LYyw51wSQsC:bt2vr1b) ([raw file](https://github.com/batfish/batfish/blob/670551263e1efeb1cbf079881ca86131656ce401/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/ReplaceAsesInAsSequence.java#L58)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

This all needs to be public, right? Otherwise, how will searchRoutePolicies do its thing?

cc: @millstein 
</blockquote></details>

Fixed.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 7 of 15 files at r1, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8081)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8081)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @corinaminer)

**Review by arifogel — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8081)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

**Pull request merged**
