### PR TITLE
Jax-RS: add @PreMatching to filters

### PR DESCRIPTION
**Pull request by dhalperi**
These filters should run unconditionally before any resource expansion
happens.

### CODE REVIEW

**Comment by dhalperi** [comment]
*[a discussion](https://reviewable.io/reviews/batfish/batfish/1752#-LFuXNis7p3C9Uvv1Usi:-LFuXNis7p3C9Uvv1Usj:bq0cq8k) (no related file):*
Working on tests

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1752)*

**Comment by dhalperi** [comment]
Does this fix the issue you were seeing?

---

Review status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @dhalperi, @haverma, and @sfraint)

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1752#-:-LFuXQ2c6LPt61TQiuf2:bwosrf7)*

**Comment by dhalperi** [comment]
Review status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @dhalperi, @haverma, and @sfraint)

---

*[projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrServiceV2Test.java, line 111 at r2](https://reviewable.io/reviews/batfish/batfish/1752#-LFu_lviD-WY1SMYdRvo:-LFu_lvj-QZjxyvd2o0H:b-n66m3c) ([raw file](https://github.com/batfish/batfish/blob/52af50f55dbd833e6ea03e4623e9849622c908bb/projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrServiceV2Test.java#L111)):*
> ```Java
>             .get();
>     assertThat(resp.getStatus(), equalTo(UNAUTHORIZED.getStatusCode()));
>     assertThat(resp.readEntity(String.class), equalTo("Authorizer: 'wrongKey' is NOT a valid key"));
> ```

well this shows the wrong thing was happening - authorizer was not kicking in early enough.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1752)*

**Comment by sfraint** [comment]
:thumbsup: yes, I think it does

---

Review status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @dhalperi, @haverma, and @sfraint)

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1752#-:-LFubtEI9o-USzhac2J3:be8pjlt)*

**Comment by sfraint** [comment]
Reviewed 3 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r4.
Review status: 4 of 5 files reviewed, all discussions resolved (waiting on @sfraint and @haverma)

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1752#-LFuXNis7p3C9Uvv1Usi:-LFxMCPFBp3_BdkXW9dv:b-7td9x7) (no related file):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Ready for review now.
</blockquote></details>

Is the `VersionCompatibilityFilter` tested anywhere?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1752)*

**Comment by dhalperi** [comment]
Reviewed 1 of 1 files at r3, 1 of 1 files at r5.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haverma)

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1752)*

**Pull request merged**
