### PR TITLE
PAN: preserve error nodes when rebuilding, and when printing, the tree

### PR DESCRIPTION
**Pull request by dhalperi**

### CODE REVIEW

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6787)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @arifogel)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6787#-MWfFdMw8P2h8viEcg8v:-MWfFdMw8P2h8viEcg8w:b-ep33yu) (no related file):*
is this just for debugging?
the commented-out, preprocessed lines won't affect the normal parsing right? / won't be visible to end-users under normal circumstances?

---

**Review by sfraint — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6787)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Review by arifogel — COMMENTED** [review]
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6787)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6787)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6787)* status: :shipit: complete! all files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6787#-MWfFdMw8P2h8viEcg8v:-MWfT-E70sGqBc2cxBHD:b-pw1eng) (no related file):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

is this just for debugging?
the commented-out, preprocessed lines won't affect the normal parsing right? / won't be visible to end-users under normal circumstances?
</blockquote></details>

The printing part is just for debugging.

Keeping error nodes in the tree after a `move` or `delete` line is not just for debugging: it actually fixes missing parse warnings.

---

**Pull request merged**
