### PR TITLE
add a reachability parameter to save the nod program to disk

### PR DESCRIPTION
**Pull request by anothermattbrown**
currently saves to /tmp.

### CODE REVIEW

**Comment by dhalperi** [comment]
Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://beta.reviewable.io/reviews/batfish/batfish/1117#-L9GZlPK19FUBJPVYOG8:-L9GZlPM-Q7dcEutvWl1:blp9qe) (no related file):*
Let's chat. A few things that seem wrong right now:

* /tmp is not portable, and for many deployments is not actually very large.
* having this parameter on the question itself vs a global setting.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1117)*

**Comment by anothermattbrown** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/batfish/batfish/1117#-L9GZlPK19FUBJPVYOG8:-L9GtYqeCVvLf-EE0nKp:bfqlbyq) (no related file):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Let's chat. A few things that seem wrong right now:

* /tmp is not portable, and for many deployments is not actually very large.
* having this parameter on the question itself vs a global setting.
</blockquote></details>

I guess either the directory should be configurable, or it should be where question log files go. Preferences?

I think we need the per-question granularity because the generated files are huge, and generating them is expensive. Having it always on or always off would impede debugging.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1117)*

**Comment by dhalperi** [comment]
:lgtm:

---

Reviewed 4 of 7 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/batfish/batfish/1117#-L9GZlPK19FUBJPVYOG8:-L9QzPltCi2Skr_AENQo:bb6mt9b) (no related file):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

I guess either the directory should be configurable, or it should be where question log files go. Preferences?

I think we need the per-question granularity because the generated files are huge, and generating them is expensive. Having it always on or always off would impede debugging.
</blockquote></details>

:+1:

---

*[projects/batfish/src/main/java/org/batfish/z3/NodJob.java, line 72 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1117#-L9QzSl40IBYrRFpPqFZ:-L9QzSl40IBYrRFpPqF_:bbrb6qk) ([raw file](https://github.com/batfish/batfish/blob/992a5470648a5f85a3a11f6e97bbb248fbcd91bd/projects/batfish/src/main/java/org/batfish/z3/NodJob.java#L72)):*
> ```Java
>     if (debugFlags != null && debugFlags.contains("saveNodProgram")) {
>       saveNodProgram(program);
>     }
> ```

Maybe add this to `Settings` as a general utility method? `if (_settings.debugFlagEnabled("saveNodProgram"))`.

---

*[projects/batfish/src/main/java/org/batfish/z3/NodJob.java, line 88 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1117#-L9Qs-M1-YwucXkv0xkx:-L9Qs-M1-YwucXkv0xky:bh2xipo) ([raw file](https://github.com/batfish/batfish/blob/992a5470648a5f85a3a11f6e97bbb248fbcd91bd/projects/batfish/src/main/java/org/batfish/z3/NodJob.java#L88)):*
> ```
> System.currentTimeMillis()
> ```

Generally, prefer RFC3339 timestamps (same as ISO8601, essentially) over millis-since-epoch-in-local-timezone. The easiest way in java 8 is just [Instant.now()#toString()](https://docs.oracle.com/javase/8/docs/api/java/time/Instant.html#toString--) -- and you don't even need the `toString` here since you're passing it to `format`. You can also do proper formatting if you don't love this.

---

*[projects/batfish/src/main/java/org/batfish/z3/NodJob.java, line 92 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1117#-L9QrwFrAIsnI2c2YOBv:-L9QrwFsAvxpG4SgCspK:bd2f3s1) ([raw file](https://github.com/batfish/batfish/blob/992a5470648a5f85a3a11f6e97bbb248fbcd91bd/projects/batfish/src/main/java/org/batfish/z3/NodJob.java#L92)):*
> ```
> e.printStackTrace();
> ```

Log this as a warning/error instead of print it to stderr?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1117#-:-L9QzmOY2bxwFiBeXJBV:bnfp4nl)*

**Comment by anothermattbrown** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/z3/NodJob.java, line 72 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1117#-L9QzSl40IBYrRFpPqFZ:-L9R6Ofi5vUEtTSrb9mW:b-ovwaw7) ([raw file](https://github.com/batfish/batfish/blob/992a5470648a5f85a3a11f6e97bbb248fbcd91bd/projects/batfish/src/main/java/org/batfish/z3/NodJob.java#L72)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Maybe add this to `Settings` as a general utility method? `if (_settings.debugFlagEnabled("saveNodProgram"))`.
</blockquote></details>

Good idea.

---

*[projects/batfish/src/main/java/org/batfish/z3/NodJob.java, line 88 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1117#-L9Qs-M1-YwucXkv0xkx:-L9R6nL36r_nmeGGFoVR:bb6u032) ([raw file](https://github.com/batfish/batfish/blob/992a5470648a5f85a3a11f6e97bbb248fbcd91bd/projects/batfish/src/main/java/org/batfish/z3/NodJob.java#L88)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> System.currentTimeMillis()
> ```

Generally, prefer RFC3339 timestamps (same as ISO8601, essentially) over millis-since-epoch-in-local-timezone. The easiest way in java 8 is just [Instant.now()#toString()](https://docs.oracle.com/javase/8/docs/api/java/time/Instant.html#toString--) -- and you don't even need the `toString` here since you're passing it to `format`. You can also do proper formatting if you don't love this.
</blockquote></details>

Cool

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1117)*

**Comment by dhalperi** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1117#-:-L9RrECNE7npjZCgzLvM:bnfp4nl)*

**Pull request merged**
