### PR TITLE
Make CRP a differential question.

### PR DESCRIPTION
**Pull request by nickgian**
This PR makes CRP act as a differential question on two snapshots rather than on a single snapshot.
It also adapts the terminology throughout the code and the results to be closer to what Batfish uses (e.g., "reference" replaces uses of "current", "proposed" is eliminated).
The only difference in the symbolic execution is that APs now contain predicates from both snapshots, rather than just one of the two. No changes in the actual symbolic execution (`TransferBDD`) are required.

The API/interface has two modes of operation:
1. You can provide a list of policies and this will compare the policies with the same name across the two snapshots (normal Batfish differential question).
2. You can provide two lists of policies (`policies`, `referencePolicies`) and this will do a cross-comparison of all the policies in the two lists - the names don't have to match up. This API allows you to compare route-maps that have different names (e.g., because of versioning).

The approach we discussed with @ratulm is to keep this question as a "hidden" API and add a new question that only provides the first interface which matches exactly the compareFilters question. Happy to add that at a later PR or as a revision, if you all agree on this approach.

### CODE REVIEW

**Review by progwriter — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8655)* status: all files reviewed, 3 unresolved discussions (waiting on @anothermattbrown, @millstein, and @nickgian)

___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/question/compareRoutePolicies/CompareRoutePoliciesAnswerer.java` line 100 at r1](https://reviewable.io/reviews/batfish/batfish/8655#-NOMHKnj86XOViXBQPel:-NOMHKnk8yyiytpHITZ-:b-it8knd) ([raw file](https://github.com/batfish/batfish/blob/bb1124105ba041e1b8b0135fa3a6d1ee034b0246/projects/minesweeper/src/main/java/org/batfish/minesweeper/question/compareRoutePolicies/CompareRoutePoliciesAnswerer.java#L100)):*
> ```Java
>    *
>    * @param referencePolicy the first route policy that was analyzed
>    * @param policy the first route policy that was analyzed
> ```

what does "the first" mean now?  
___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/question/compareRoutePolicies/CompareRoutePoliciesAnswerer.java` line 346 at r1](https://reviewable.io/reviews/batfish/batfish/8655#-NOMJ2X023PqE2SjPHnw:-NOMJ2X023PqE2SjPHnx:b-r7ey0a) ([raw file](https://github.com/batfish/batfish/blob/bb1124105ba041e1b8b0135fa3a6d1ee034b0246/projects/minesweeper/src/main/java/org/batfish/minesweeper/question/compareRoutePolicies/CompareRoutePoliciesAnswerer.java#L346)):*
> ```Java
>       // In this case we only compare policies with the same name.
>       // Create a map from policy name to a tuple (currentPolicy, referencePolicy)
>       Map<String, Tuple<RoutingPolicy, RoutingPolicy>> policiesMap = new HashMap<>();
> ```

this logic seems complex. 

aren't you guaranteed that at this point both lists are identical due to filtering above? so maybe just sorting them and walking over them in a single pass enough to get the `k, v`? or am I missing something?
___
*[`questions/experimental/compareRoutePolicies.json` line 3 at r1](https://reviewable.io/reviews/batfish/batfish/8655#-NOMDqxI0eQKhIoKGgye:-NOMDqxI0eQKhIoKGgyf:b-rnl7lv) ([raw file](https://github.com/batfish/batfish/blob/bb1124105ba041e1b8b0135fa3a6d1ee034b0246/questions/experimental/compareRoutePolicies.json#L3)):*
> ```JSON
> {
>   "class": "org.batfish.minesweeper.question.compareRoutePolicies.CompareRoutePoliciesQuestion",
>   "differential": false,
> ```

I think you need to flip this to `true`?

**Review by nickgian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8655)* status: 4 of 6 files reviewed, all discussions resolved (waiting on @anothermattbrown, @millstein, and @progwriter)

___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/question/compareRoutePolicies/CompareRoutePoliciesAnswerer.java` line 100 at r1](https://reviewable.io/reviews/batfish/batfish/8655#-NOMHKnj86XOViXBQPel:-NOQUlE1DUIvZ-2-kwXT:b-4tnjty) ([raw file](https://github.com/batfish/batfish/blob/bb1124105ba041e1b8b0135fa3a6d1ee034b0246/projects/minesweeper/src/main/java/org/batfish/minesweeper/question/compareRoutePolicies/CompareRoutePoliciesAnswerer.java#L100)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

what does "the first" mean now?  
</blockquote></details>

Fixed the comments.
___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/question/compareRoutePolicies/CompareRoutePoliciesAnswerer.java` line 346 at r1](https://reviewable.io/reviews/batfish/batfish/8655#-NOMJ2X023PqE2SjPHnw:-NOQOY6v4IoadgQntals:b-ph06jz) ([raw file](https://github.com/batfish/batfish/blob/bb1124105ba041e1b8b0135fa3a6d1ee034b0246/projects/minesweeper/src/main/java/org/batfish/minesweeper/question/compareRoutePolicies/CompareRoutePoliciesAnswerer.java#L346)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

this logic seems complex. 

aren't you guaranteed that at this point both lists are identical due to filtering above? so maybe just sorting them and walking over them in a single pass enough to get the `k, v`? or am I missing something?
</blockquote></details>

This sounds more elegant, I adjusted the code to do this.
___
*[`questions/experimental/compareRoutePolicies.json` line 3 at r1](https://reviewable.io/reviews/batfish/batfish/8655#-NOMDqxI0eQKhIoKGgye:-NOQUNvLAfZGhudtzSlr:b-80bnw2) ([raw file](https://github.com/batfish/batfish/blob/bb1124105ba041e1b8b0135fa3a6d1ee034b0246/questions/experimental/compareRoutePolicies.json#L3)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

I think you need to flip this to `true`?
</blockquote></details>

True!

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8655)* status: 2 of 8 files reviewed, 4 unresolved discussions (waiting on @millstein, @nickgian, and @progwriter)

___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/ConfigAtomicPredicates.java` line 28 at r3](https://reviewable.io/reviews/batfish/batfish/8655#-NOVGjIdE2MxkMi1y21I:-NOVGjIdE2MxkMi1y21J:b-mf0i2x) ([raw file](https://github.com/batfish/batfish/blob/dbe725b97d1e009552ee1ec3866cd7b343dfad2a/projects/minesweeper/src/main/java/org/batfish/minesweeper/ConfigAtomicPredicates.java#L28)):*
> ```Java
>  * configuration.
>  */
> public class ConfigAtomicPredicates {
> ```

does this class have subclasses? If no, please make it `final`. Makes it easier to read/review.



_Code quote:_
```Java
public class ConfigAtomicPredicates
```
___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/ConfigAtomicPredicates.java` line 30 at r3](https://reviewable.io/reviews/batfish/batfish/8655#-NOVElofE_wmfDg9r1z4:-NOVElofE_wmfDg9r1z5:bwgd4oi) ([raw file](https://github.com/batfish/batfish/blob/dbe725b97d1e009552ee1ec3866cd7b343dfad2a/projects/minesweeper/src/main/java/org/batfish/minesweeper/ConfigAtomicPredicates.java#L30)):*
> ```Java
> public class ConfigAtomicPredicates {
> 
>   Configuration _configuration;
> ```

why is this no longer private+final?



_Code quote:_
```Java
  Configuration _configuration;
```
___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/ConfigAtomicPredicates.java` line 32 at r3](https://reviewable.io/reviews/batfish/batfish/8655#-NOVGDp-0AV9ZRMBzXkO:-NOVGDp-0AV9ZRMBzXkP:bummby9) ([raw file](https://github.com/batfish/batfish/blob/dbe725b97d1e009552ee1ec3866cd7b343dfad2a/projects/minesweeper/src/main/java/org/batfish/minesweeper/ConfigAtomicPredicates.java#L32)):*
> ```Java
>   Configuration _configuration;
> 
>   Configuration _referenceConfiguration;
> ```

what is this field for? I don't see it used outside the constructor.



_Code quote:_
```Java
  Configuration _referenceConfiguration;
```
___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/ConfigAtomicPredicates.java` line 191 at r3](https://reviewable.io/reviews/batfish/batfish/8655#-NOVH-uSD0DzH699dxJh:-NOVH-uSD0DzH699dxJi:bk89ix9) ([raw file](https://github.com/batfish/batfish/blob/dbe725b97d1e009552ee1ec3866cd7b343dfad2a/projects/minesweeper/src/main/java/org/batfish/minesweeper/ConfigAtomicPredicates.java#L191)):*
> ```Java
>    * user-specified community constraints for symbolic analysis.
>    */
>   private Set<CommunityVar> findAllCommunities(
> ```

can this be static? (it seems like a lot of these methods can be?)



_Code quote:_
```Java
private Set<CommunityVar> findAllCommunities(
```

**Review by nickgian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8655)* status: 1 of 8 files reviewed, 2 unresolved discussions (waiting on @anothermattbrown, @millstein, and @progwriter)

___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/ConfigAtomicPredicates.java` line 28 at r3](https://reviewable.io/reviews/batfish/batfish/8655#-NOVGjIdE2MxkMi1y21I:-NOW1RGdCKsp5tOX__9u:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/dbe725b97d1e009552ee1ec3866cd7b343dfad2a/projects/minesweeper/src/main/java/org/batfish/minesweeper/ConfigAtomicPredicates.java#L28)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

does this class have subclasses? If no, please make it `final`. Makes it easier to read/review.
</blockquote></details>

Done.
___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/ConfigAtomicPredicates.java` line 30 at r3](https://reviewable.io/reviews/batfish/batfish/8655#-NOVElofE_wmfDg9r1z4:-NOW1UwF2_fJx-SzULdd:b-59tqbd) ([raw file](https://github.com/batfish/batfish/blob/dbe725b97d1e009552ee1ec3866cd7b343dfad2a/projects/minesweeper/src/main/java/org/batfish/minesweeper/ConfigAtomicPredicates.java#L30)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

why is this no longer private+final?
</blockquote></details>

Not sure tbh. Made the private+final again.
___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/ConfigAtomicPredicates.java` line 32 at r3](https://reviewable.io/reviews/batfish/batfish/8655#-NOVGDp-0AV9ZRMBzXkO:-NOW1_2oCEmfqXM-BkY6:b2q609e) ([raw file](https://github.com/batfish/batfish/blob/dbe725b97d1e009552ee1ec3866cd7b343dfad2a/projects/minesweeper/src/main/java/org/batfish/minesweeper/ConfigAtomicPredicates.java#L32)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

what is this field for? I don't see it used outside the constructor.
</blockquote></details>

Neither is `_configuration`. I decided to keep them both because in the future it might be useful to know which config was used to generate the given APs, but I can remove if you have strong feelings about it.
___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/ConfigAtomicPredicates.java` line 191 at r3](https://reviewable.io/reviews/batfish/batfish/8655#-NOVH-uSD0DzH699dxJh:-NOW1p5ACgcjSidYvtF6:b77s7rz) ([raw file](https://github.com/batfish/batfish/blob/dbe725b97d1e009552ee1ec3866cd7b343dfad2a/projects/minesweeper/src/main/java/org/batfish/minesweeper/ConfigAtomicPredicates.java#L191)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

can this be static? (it seems like a lot of these methods can be?)
</blockquote></details>

Made these methods static (+ the ones about as-path regexes).

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 1 of 6 files at r1, 6 of 6 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8655)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @millstein)

___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/ConfigAtomicPredicates.java` line 32 at r3](https://reviewable.io/reviews/batfish/batfish/8655#-NOVGDp-0AV9ZRMBzXkO:-NOa52V89JK2zzi_YGEl:b-awo39i) ([raw file](https://github.com/batfish/batfish/blob/dbe725b97d1e009552ee1ec3866cd7b343dfad2a/projects/minesweeper/src/main/java/org/batfish/minesweeper/ConfigAtomicPredicates.java#L32)):*
<details><summary><i>Previously, nickgian (Nick Giannarakis) wrote…</i></summary><blockquote>

Neither is `_configuration`. I decided to keep them both because in the future it might be useful to know which config was used to generate the given APs, but I can remove if you have strong feelings about it.
</blockquote></details>

Not a strong opinion, but I do think the code will be easier to read+understand if you remove it. Can easily add it later if necessary. I'll leave it up to you.
___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/question/compareroutepolicies/CompareRoutePoliciesAnswerer.java` line 338 at r4](https://reviewable.io/reviews/batfish/batfish/8655#-NOa5uD58Esckpsglpyw:-NOa5uD58Esckpsglpyx:b-5l5db9) ([raw file](https://github.com/batfish/batfish/blob/530f50095097f2e703501daeb849a5deb835dbaa/projects/minesweeper/src/main/java/org/batfish/minesweeper/question/compareroutepolicies/CompareRoutePoliciesAnswerer.java#L338)):*
> ```Java
>             referencePoliciesList);
> 
>     if (crossPolicies) {
> ```

what's the use case for comparing all pairs, beyond the case when both lists are singletons?



_Code quote:_
```Java
if (crossPolicies) {
```
___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/question/compareroutepolicies/CompareRoutePoliciesAnswerer.java` line 361 at r4](https://reviewable.io/reviews/batfish/batfish/8655#-NOa78to39vhcxkJL4d6:-NOa78to39vhcxkJL4d7:b4w56wb) ([raw file](https://github.com/batfish/batfish/blob/530f50095097f2e703501daeb849a5deb835dbaa/projects/minesweeper/src/main/java/org/batfish/minesweeper/question/compareroutepolicies/CompareRoutePoliciesAnswerer.java#L361)):*
> ```Java
> 
>       // Since they have been sorted by name the policies at each index should have the same name.
>       Stream<Tuple<RoutingPolicy, RoutingPolicy>> zippedPolicies =
> ```

this intermediate stream can be removed, which I think would simplify the code.



_Code quote:_
```Java
Stream<Tuple<RoutingPolicy, RoutingPolicy>> zippedPolicies =
```

**Review by anothermattbrown — COMMENTED** [review]
:lgtm:

all suggestions optional. if you make those changes, feel free to self-review and merge at will

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8655#-:-NOevIVp4Gc1VMKa3_s1:bop5r2j)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @millstein)

___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/ConfigAtomicPredicates.java` line 127 at r5](https://reviewable.io/reviews/batfish/batfish/8655#-NOetm2t15-6YHXcauSX:-NOetm2t15-6YHXcauSY:bs8jhl0) ([raw file](https://github.com/batfish/batfish/blob/6121f65b79ad15a6451d4ed866b42179108e6e90/projects/minesweeper/src/main/java/org/batfish/minesweeper/ConfigAtomicPredicates.java#L127)):*
> ```Java
>       @Nonnull Collection<RoutingPolicy> policies,
>       @Nullable Collection<RoutingPolicy> referencePolicies) {
>     Configuration configuration = batfish.loadConfigurations(snapshot).get(router);
> ```

these can be combined into a 1-liner, making `referenceConfiguration` effectively final (which is simpler):

```
Configuration referenceConfiguration =
  reference == null ? null : batfish.loadConfigurations(reference).get(router);
```



_Code quote:_
```Java
    Configuration referenceConfiguration = null;
    if (reference != null) {
      referenceConfiguration = batfish.loadConfigurations(reference).get(router);


    }
```
___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/question/compareroutepolicies/CompareRoutePoliciesAnswerer.java` line 367 at r5](https://reviewable.io/reviews/batfish/batfish/8655#-NOeuP9VEMMXRJa2h0KN:-NOeuP9VEMMXRJa2h0KO:bdj2kce) ([raw file](https://github.com/batfish/batfish/blob/6121f65b79ad15a6451d4ed866b42179108e6e90/projects/minesweeper/src/main/java/org/batfish/minesweeper/question/compareroutepolicies/CompareRoutePoliciesAnswerer.java#L367)):*
> ```Java
>                     .get(i)
>                     .getName()
>                     .equals(currentPoliciesList.get(i).getName()));
> ```

Even simpler:
```
return IntStream.range(0, currentPoliciesList.size())

          .mapToObj(
              i -> {
                assert (referencePoliciesList
                    .get(i)
                    .getName()
                    .equals(currentPoliciesList.get(i).getName()));
                return new Tuple<>(referencePoliciesList.get(i), currentPoliciesList.get(i));
              })
          .flatMap(Function.identity());

              policyTuple ->
                  comparePolicies(policyTuple.getFirst(), policyTuple.getSecond(), configAPs)
                      .stream());
```



_Suggestion:_
```Java
      return IntStream.range(0, currentPoliciesList.size())
          .mapToObj(
              i -> {
                assert (referencePoliciesList
                    .get(i)
                    .getName()
                    .equals(currentPoliciesList.get(i).getName()));
                return comparePolicies(referencePoliciesList.get(i), currentPoliciesList.get(i), configAPs);
              })
          .flatMap(Collection::stream);
```

**Pull request merged**
