### PR TITLE
PAN: use new built-in apps

### PR DESCRIPTION
**Pull request by sfraint**
* Use new built-in application definitions
  * Add support for `application-container`s (basically built-in `application-group`s)
  * Add definition -> existing datamodel conversion
* Delete old, manually built `ApplicationBuiltIn` definitions

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 5 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8189)* status: 5 of 14 files reviewed, 1 unresolved discussion (waiting on @dhalperi and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/Conversions.java, line 384 at r2](https://reviewable.io/reviews/batfish/batfish/8189#-MyyKMPt3aZXDlJaIGS0:-MyyKMPt3aZXDlJaIGS1:b-bq4yjf) ([raw file](https://github.com/batfish/batfish/blob/e03c8bb3deb51ff3b66b84ade08860b0cfe9320e/projects/batfish/src/main/java/org/batfish/representation/palo_alto/Conversions.java#L384)):*
> ```Java
>       case "icmp":
>         return service.setIpProtocol(IpProtocol.ICMP).build();
>       case "icmp6":
> ```

I think this should just return Optional#empty or whatever. Won't appear in an IPv4 packet.



_Code quote:_
```Java
      case "icmp6":
        return service.setIpProtocol(IpProtocol.IPV6_ICMP).build();
```

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8189)* status: 4 of 14 files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/Conversions.java, line 384 at r2](https://reviewable.io/reviews/batfish/batfish/8189#-MyyKMPt3aZXDlJaIGS0:-Mz1-6qJ-hPAabQWV-d2:bvnrpcm) ([raw file](https://github.com/batfish/batfish/blob/e03c8bb3deb51ff3b66b84ade08860b0cfe9320e/projects/batfish/src/main/java/org/batfish/representation/palo_alto/Conversions.java#L384)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I think this should just return Optional#empty or whatever. Won't appear in an IPv4 packet.
</blockquote></details>

updated

**Review by dhalperi — COMMENTED** [review]
> Reviewed 7 of 14 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8189)* status: all files reviewed, 2 unresolved discussions (waiting on @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/application_definitions/ApplicationDefinition.java, line 60 at r3](https://reviewable.io/reviews/batfish/batfish/8189#-MzG_uVh1cBzjB7zmUXB:-MzG_uVh1cBzjB7zmUXC:bv056z6) ([raw file](https://github.com/batfish/batfish/blob/d4f2dca98605a31daaa16206747fb666738f428f/projects/batfish/src/main/java/org/batfish/representation/palo_alto/application_definitions/ApplicationDefinition.java#L60)):*
> ```Java
>   @VisibleForTesting
>   @JsonCreator
>   public static @Nonnull ApplicationDefinition create(
> ```

prefer not this. Keep it private, keep a package-private for testing.

If you need to make a `public` version, do it in a testlib that also has bazel `testonly` set.



_Code quote:_
```Java
  @VisibleForTesting
  @JsonCreator
  public static @Nonnull ApplicationDefinition create(
```
___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/application_definitions/Port.java, line 43 at r3](https://reviewable.io/reviews/batfish/batfish/8189#-MzGa8eB63QN1gl5of88:-MzGa8eB63QN1gl5of89:b-rqxvo7) ([raw file](https://github.com/batfish/batfish/blob/d4f2dca98605a31daaa16206747fb666738f428f/projects/batfish/src/main/java/org/batfish/representation/palo_alto/application_definitions/Port.java#L43)):*
> ```Java
> 
>   @VisibleForTesting
>   public static @Nonnull Port create(@Nonnull List<String> member) {
> ```

ditto.



_Code quote:_
```Java
  @VisibleForTesting
  public static @Nonnull Port create(@Nonnull List<String> member) {
```

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8189)* status: 10 of 17 files reviewed, 2 unresolved discussions (waiting on @dhalperi and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/application_definitions/ApplicationDefinition.java, line 60 at r3](https://reviewable.io/reviews/batfish/batfish/8189#-MzG_uVh1cBzjB7zmUXB:-MzHLF3O6sbZPR23-FZL:bvfmr4w) ([raw file](https://github.com/batfish/batfish/blob/d4f2dca98605a31daaa16206747fb666738f428f/projects/batfish/src/main/java/org/batfish/representation/palo_alto/application_definitions/ApplicationDefinition.java#L60)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

prefer not this. Keep it private, keep a package-private for testing.

If you need to make a `public` version, do it in a testlib that also has bazel `testonly` set.
</blockquote></details>

Added `Creators.java` - is this what you meant?

**Review by dhalperi — COMMENTED** [review]
> Reviewed 5 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8189)* status: 15 of 17 files reviewed, 5 unresolved discussions (waiting on @dhalperi and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/application_definitions/ApplicationDefinition.java, line 60 at r4](https://reviewable.io/reviews/batfish/batfish/8189#-MzHNDAr4GoCJyVJRiGC:-MzHNDAr4GoCJyVJRiGD:bf5vc6v) ([raw file](https://github.com/batfish/batfish/blob/9d26f16f346be2537688020b023502b9d90b5f0f/projects/batfish/src/main/java/org/batfish/representation/palo_alto/application_definitions/ApplicationDefinition.java#L60)):*
> ```Java
>   @VisibleForTesting
>   @JsonCreator
>   static @Nonnull ApplicationDefinition create(
> ```

Prefer for `@JsonCreator` methods to always be private and named something like `jsonCreator`. Whenever we don't do that, we end up mixing JSON-only invariants (every field can be nullable) with app invariants.

I'd just have a visible for testing, package-private constructor.
___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/application_definitions/Default.java, line 53 at r4](https://reviewable.io/reviews/batfish/batfish/8189#-MzHNa7e9NiPBg4aNw0C:-MzHNa7e9NiPBg4aNw0D:b6e99re) ([raw file](https://github.com/batfish/batfish/blob/9d26f16f346be2537688020b023502b9d90b5f0f/projects/batfish/src/main/java/org/batfish/representation/palo_alto/application_definitions/Default.java#L53)):*
> ```Java
> 
>   @VisibleForTesting
>   static @Nonnull Default create(
> ```

What is the point of this method? Why not just the constructor?
___
*[projects/batfish/src/test/java/org/batfish/representation/palo_alto/application_definitions/BUILD, line 16 at r4](https://reviewable.io/reviews/batfish/batfish/8189#-MzHNjiu67nlkrRjiz2H:-MzHNjiu67nlkrRjiz2I:b-wlrtjc) ([raw file](https://github.com/batfish/batfish/blob/9d26f16f346be2537688020b023502b9d90b5f0f/projects/batfish/src/test/java/org/batfish/representation/palo_alto/application_definitions/BUILD#L16)):*
> ```Starlark
>         ],
>         exclude = ["**/*Test.java"],
>     ),
> ```

prefer just listing over globs, for new test utility libraries.



_Code quote:_
```Starlark
    srcs = glob(
        [
            "**/*.java",
        ],
        exclude = ["**/*Test.java"],
    ),
```
___
*[projects/batfish/src/test/java/org/batfish/representation/palo_alto/application_definitions/Creators.java, line 9 at r4](https://reviewable.io/reviews/batfish/batfish/8189#-MzHNmTj7rhc7qKu-qEx:-MzHNmTj7rhc7qKu-qEy:b-njwvd0) ([raw file](https://github.com/batfish/batfish/blob/9d26f16f346be2537688020b023502b9d90b5f0f/projects/batfish/src/test/java/org/batfish/representation/palo_alto/application_definitions/Creators.java#L9)):*
> ```Java
> 
> /** Helper class to create {@link ApplicationDefinition}s and dependent objects for testing. */
> public class Creators {
> ```

`TestApplicationDefinitions`?

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8189)* status: 11 of 17 files reviewed, 4 unresolved discussions (waiting on @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/application_definitions/ApplicationDefinition.java, line 60 at r4](https://reviewable.io/reviews/batfish/batfish/8189#-MzHNDAr4GoCJyVJRiGC:-MzHQrvHAzaXI-phKVwf:bvnrpcm) ([raw file](https://github.com/batfish/batfish/blob/9d26f16f346be2537688020b023502b9d90b5f0f/projects/batfish/src/main/java/org/batfish/representation/palo_alto/application_definitions/ApplicationDefinition.java#L60)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Prefer for `@JsonCreator` methods to always be private and named something like `jsonCreator`. Whenever we don't do that, we end up mixing JSON-only invariants (every field can be nullable) with app invariants.

I'd just have a visible for testing, package-private constructor.
</blockquote></details>

updated
___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/application_definitions/Default.java, line 53 at r4](https://reviewable.io/reviews/batfish/batfish/8189#-MzHNa7e9NiPBg4aNw0C:-MzHQBS4BjtgeuMODAKt:bzwddl) ([raw file](https://github.com/batfish/batfish/blob/9d26f16f346be2537688020b023502b9d90b5f0f/projects/batfish/src/main/java/org/batfish/representation/palo_alto/application_definitions/Default.java#L53)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

What is the point of this method? Why not just the constructor?
</blockquote></details>

Yep, not needed. Removed
___
*[projects/batfish/src/test/java/org/batfish/representation/palo_alto/application_definitions/BUILD, line 16 at r4](https://reviewable.io/reviews/batfish/batfish/8189#-MzHNjiu67nlkrRjiz2H:-MzHQRE--jbzi24iaiw3:bvnrpcm) ([raw file](https://github.com/batfish/batfish/blob/9d26f16f346be2537688020b023502b9d90b5f0f/projects/batfish/src/test/java/org/batfish/representation/palo_alto/application_definitions/BUILD#L16)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

prefer just listing over globs, for new test utility libraries.
</blockquote></details>

updated
___
*[projects/batfish/src/test/java/org/batfish/representation/palo_alto/application_definitions/Creators.java, line 9 at r4](https://reviewable.io/reviews/batfish/batfish/8189#-MzHNmTj7rhc7qKu-qEx:-MzHQXAfBtSf_2DIaeGk:bvnrpcm) ([raw file](https://github.com/batfish/batfish/blob/9d26f16f346be2537688020b023502b9d90b5f0f/projects/batfish/src/test/java/org/batfish/representation/palo_alto/application_definitions/Creators.java#L9)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

`TestApplicationDefinitions`?
</blockquote></details>

updated

**Review by dhalperi — COMMENTED** [review]
> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8189)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

**Pull request merged**
