### PR TITLE
Warning for the use of ttl in ACLs

### PR DESCRIPTION
**Pull request by ratulm**
A more targeted warning when ttl appears in ACLs. Meant to reduce user confusion like that in https://github.com/batfish/batfish/issues/8232

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8324)* status: all files reviewed, 1 unresolved discussion (waiting on @ratulm)

___
*[`tests/parsing-tests/unit-tests-warnings.ref` line 225 at r1](https://reviewable.io/reviews/batfish/batfish/8324#-N2iEc-Z4ERBtxPIB54C:-N2iEc-Z4ERBtxPIB54D:byp6t8g) ([raw file](https://github.com/batfish/batfish/blob/ca5366e1c0cadd5747e1b3abf317ab5da60e317b/tests/parsing-tests/unit-tests-warnings.ref#L225)):*
> ```
>         "Text" : "60 permit tcp any any eq mlag ttl eq 255",
>         "Parser_Context" : "[extended_access_list_tail extended_access_list_stanza stanza cisco_configuration]",
>         "Comment" : "Unsupported clause in extended access list: ttleq255"
> ```

need to fix the output text, too.

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8324)* status: all files reviewed, 2 unresolved discussions (waiting on @ratulm)

___
*[`projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java` line 4965 at r1](https://reviewable.io/reviews/batfish/batfish/8324#-N2iFuTK0CXCbE-NE4Le:-N2iFuTK0CXCbE-NE4Lf:bdnn8po) ([raw file](https://github.com/batfish/batfish/blob/9fd512c066764388710b599574a27736bc1daaff/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L4965)):*
> ```Java
>           // "ttl eq 255" is a common pattern to limit traffic to neighboring routers
>           warn(ctx, "Batfish does not model packet TTLs");
>           return UnimplementedAccessListServiceSpecifier.INSTANCE;
> ```

Won't this change behavior? Is that desirable?

E.g., what if single-hop ebgp session has that set.

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8324)* status: all files reviewed, 2 unresolved discussions (waiting on @dhalperi and @ratulm)

___
*[`projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java` line 4965 at r1](https://reviewable.io/reviews/batfish/batfish/8324#-N2iFuTK0CXCbE-NE4Le:-N2izpoU5QyUS-sKF2xG:b-nd3z21) ([raw file](https://github.com/batfish/batfish/blob/9fd512c066764388710b599574a27736bc1daaff/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L4965)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Won't this change behavior? Is that desirable?

E.g., what if single-hop ebgp session has that set.
</blockquote></details>

I am missing something. How might this change behavior? 

The return value before the PR was the same one. The code is confusing perhaps, which I can change.

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8324)* status: all files reviewed, 2 unresolved discussions (waiting on @dhalperi and @ratulm)

___
*[`tests/parsing-tests/unit-tests-warnings.ref` line 225 at r1](https://reviewable.io/reviews/batfish/batfish/8324#-N2iEc-Z4ERBtxPIB54C:-N2miwWzCk88CfthNbpf:bx3sq2n) ([raw file](https://github.com/batfish/batfish/blob/ca5366e1c0cadd5747e1b3abf317ab5da60e317b/tests/parsing-tests/unit-tests-warnings.ref#L225)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

need to fix the output text, too.
</blockquote></details>

FYI this is https://github.com/batfish/batfish/pull/8327

**Pull request merged**
