### PR TITLE
Interface status overhaul

### PR DESCRIPTION
**Pull request by arifogel**
- add adminUp interface property
- add lineUp interface property
  - refactored from blacklisted property, with value reversed
  - null for non-physical interfaces
- add inactiveReason interface property for interfaces that are inactive
- privatize status setters in `Interface`. Instead, use:
  - `administrativelyDisable` to set admin down, inactive
  - `disconnect` to set line down, inactive on physical interfaces

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7939)* status: 0 of 88 files reviewed, all discussions resolved (waiting on @dhalperi)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7939#-MtdLJAv63FAfGY5_R5v:-MtdLJAwCgyWwK1PxMmP:b-l0077u) (no related file):*
I think someone who's not me should review this to get a new set of eyes on it.

-reviewer:@dhalperi 

---

**Review by corinaminer — COMMENTED** [review]
> Reviewed 6 of 39 files at r1, 76 of 82 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7939)* status: 82 of 88 files reviewed, 11 unresolved discussions (waiting on @arifogel, @corinaminer, and @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 1871 at r2](https://reviewable.io/reviews/batfish/batfish/7939#-MtgYDkQCdud45aR_RIe:-MtgYDkQCdud45aR_RIf:b-k1jdww) ([raw file](https://github.com/batfish/batfish/blob/9038acb350e176ac53d24de2e4913fb75bb80586/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L1871)):*
> ```Java
>         .filter(Optional::isPresent)
>         .map(Optional::get)
>         .filter(Interface::hasLineStatus)
> ```

This means user-provided runtime data can no longer deactivate interfaces without line status, right? I think that makes sense because the runtime data for interfaces is supposed to be line data, but i'm sure some users have been using it as a shortcut to indicate admin down. This may break some existing users.
___
*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 1901 at r2](https://reviewable.io/reviews/batfish/batfish/7939#-MtgZGtaENM4OrWqhjrB:-MtgZGtaENM4OrWqhjrC:b-ax5ja2) ([raw file](https://github.com/batfish/batfish/blob/9038acb350e176ac53d24de2e4913fb75bb80586/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L1901)):*
> ```Java
>                         || MANAGEMENT_VRFS.matcher(iface.getVrfName()).find())) {
>                   if (iface.hasLineStatus() && iface.getLineUp()) {
>                     iface.disconnect();
> ```

are management interfaces actually not connected? (trying to understand why you wouldn't `deactivate(IGNORE_MGMT)` for all active management interfaces)
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/InactiveReason.java, line 16 at r2](https://reviewable.io/reviews/batfish/batfish/7939#-Mtgcv8u3wwtqT1YX4jQ:-Mtgcv8u3wwtqT1YX4jR:b-2lqvge) ([raw file](https://github.com/batfish/batfish/blob/9038acb350e176ac53d24de2e4913fb75bb80586/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/InactiveReason.java#L16)):*
> ```Java
>   LINE_DOWN("Line down"),
>   NO_ACTIVE_MEMBERS("No operational member interfaces"),
>   NO_MEMBERS("Not configured member interfaces"),
> ```

typo: "no", not "not"
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java, line 69 at r2](https://reviewable.io/reviews/batfish/batfish/7939#-MtecIS43eiR73Xxmo3u:-MtecIS43eiR73Xxmo3v:brlsikp) ([raw file](https://github.com/batfish/batfish/blob/9038acb350e176ac53d24de2e4913fb75bb80586/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java#L69)):*
> ```Java
>     private Transformation _incomingTransformation;
>     private IsisInterfaceSettings _isis;
>     private transient @Nullable Boolean _lineUp;
> ```

Why does transience matter in a builder?
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java, line 1755 at r2](https://reviewable.io/reviews/batfish/batfish/7939#-MteeDrLArN3BxZoeba7:-MteeDrLArN3BxZoeba8:baasjdd) ([raw file](https://github.com/batfish/batfish/blob/9038acb350e176ac53d24de2e4913fb75bb80586/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java#L1755)):*
> ```Java
>   @JsonProperty(PROP_LINE_UP)
>   private void setLineUp(@Nullable Boolean lineUp) {
>     _lineUp = lineUp;
> ```

Annoying that we can't maintain the invariant that lineUp is nonnull iff `hasLineStatus()`. Maybe we could update `lineUp` when `setInterfaceType()` is called?
```
if (!hasLineStatus(newType)) {
  _lineUp = null;
} else if (_lineUp == null) {
  _lineUp = true;
}
```
I could see this making a useful difference if there are places where an interface is initially type `UNKNOWN` but can later be set to types without line status.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java, line 1964 at r2](https://reviewable.io/reviews/batfish/batfish/7939#-MtgQGHtDBpgwEGcB47r:-MtgQGHtDBpgwEGcB47s:bgtezh1) ([raw file](https://github.com/batfish/batfish/blob/9038acb350e176ac53d24de2e4913fb75bb80586/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java#L1964)):*
> ```Java
> 
>   /**
>    * Nark this interface as disconnected, after which {@link #getActive()} and {@link #getLineUp()}
> ```

typo: "mark" not "nark" :space_invader: 
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java, line 1993 at r2](https://reviewable.io/reviews/batfish/batfish/7939#-MtgR00jDtMnqEzCupxq:-MtgR00jDtMnqEzCupxr:b-ha7nn2) ([raw file](https://github.com/batfish/batfish/blob/9038acb350e176ac53d24de2e4913fb75bb80586/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java#L1993)):*
> ```Java
>    *
>    * <p>Calling with {@link InactiveReason#LINE_DOWN} is equivalent to calling {@link
>    * #disconnect()}.
> ```

Technically not equivalent to calling `disconnect()` because `deactivate(LINE_DOWN)` will throw if the interface is inactive but line up, whereas `disconnect()` succeeds. Does this matter? (Seems semantically reasonable -- you can "disconnect" an inactive interface, but can't "deactivate by disconnecting" it since it's already inactive.)
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/interface_dependency/InterfaceDependencies.java, line 189 at r2](https://reviewable.io/reviews/batfish/batfish/7939#-MtgSuhu6EXVZDFo1-x4:-MtgSuhu6EXVZDFo1-x5:b47xaa8) ([raw file](https://github.com/batfish/batfish/blob/9038acb350e176ac53d24de2e4913fb75bb80586/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/interface_dependency/InterfaceDependencies.java#L189)):*
> ```Java
>               if (iface.getInterfaceType() == InterfaceType.AGGREGATED) {
>                 // AGGREGATED interface with more than 2 logical L1 neighbors. Probably would break
>                 // LACP, so disable. Warn, since something is probably wrong with L1 input.
> ```

I don't know the difference between `AGGREGATED` and `REDUNDANT` -- I take it redundant interfaces can have more than 2 logical L1 neighbors?
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/interface_dependency/InterfaceDependencies.java, line 365 at r2](https://reviewable.io/reviews/batfish/batfish/7939#-MtgUyu78wby1MV8MjOe:-MtgUyu78wby1MV8MjOf:b61valx) ([raw file](https://github.com/batfish/batfish/blob/9038acb350e176ac53d24de2e4913fb75bb80586/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/interface_dependency/InterfaceDependencies.java#L365)):*
> ```Java
>                   // is only reachable if each side has at least one member interface that is up.
>                   // TODO: Seems like you should only lose an L3 edge, not an L1 edge. But if you do
>                   //       lose an L1 edge, best guess is LACP failures.
> ```

i'm not clear on what this TODO means. Do we need to investigate ways an L1 edge could get lost here, or ascertain that that's possible?
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/InterfacePropertySpecifier.java, line 83 at r2](https://reviewable.io/reviews/batfish/batfish/7939#-MtgWyzs8hvzodb4xn__:-MtgWyzs8hvzodb4xn_a:b3ufpy8) ([raw file](https://github.com/batfish/batfish/blob/9038acb350e176ac53d24de2e4913fb75bb80586/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/InterfacePropertySpecifier.java#L83)):*
> ```Java
> 
>   private static boolean getBlacklisted(@Nonnull Interface i) {
>     return i.hasLineStatus() && !i.getLineUp();
> ```

This relies on the invariant that lineUp is nonnull if `i.hasLineStatus()`, which isn't guaranteed because `Interface.setInterfaceType()` is public. see my other comment suggesting how to enforce that invariant.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/InterfacePropertySpecifier.java, line 87 at r2](https://reviewable.io/reviews/batfish/batfish/7939#-MtgX5jpBrQaVU98havb:-MtgX5jpBrQaVU98havc:b-n2yzeq) ([raw file](https://github.com/batfish/batfish/blob/9038acb350e176ac53d24de2e4913fb75bb80586/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/InterfacePropertySpecifier.java#L87)):*
> ```Java
> 
>   private static boolean getLineUp(@Nonnull Interface i) {
>     return i.hasLineStatus() && !i.getLineUp();
> ```

doesn't seem like the correct implementation -- and this method is unused, i think
___
*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/InterfaceTest.java, line 55 at r2](https://reviewable.io/reviews/batfish/batfish/7939#-MtgfVKw3QuoPFzUSMMz:-MtgfVKw3QuoPFzUSMN-:b-w56l3m) ([raw file](https://github.com/batfish/batfish/blob/9038acb350e176ac53d24de2e4913fb75bb80586/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/InterfaceTest.java#L55)):*
> ```Java
>     assertThat(
>         Interface.builder().setName("foo").setType(LOGICAL).setAdminUp(false).build(),
>         allOf(isActive(false), isAdminUp(false), hasInactiveReason(ADMIN_DOWN)));
> ```

At least one of these should check that `_lineUp` is null

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7939)* status: 68 of 91 files reviewed, 10 unresolved discussions (waiting on @corinaminer and @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 1871 at r2](https://reviewable.io/reviews/batfish/batfish/7939#-MtgYDkQCdud45aR_RIe:-MtjEuwsCcPKCXVNdqx6:bkup8ic) ([raw file](https://github.com/batfish/batfish/blob/9038acb350e176ac53d24de2e4913fb75bb80586/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L1871)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

This means user-provided runtime data can no longer deactivate interfaces without line status, right? I think that makes sense because the runtime data for interfaces is supposed to be line data, but i'm sure some users have been using it as a shortcut to indicate admin down. This may break some existing users.
</blockquote></details>

Right. This is intentional.
___
*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 1901 at r2](https://reviewable.io/reviews/batfish/batfish/7939#-MtgZGtaENM4OrWqhjrB:-Mtimlnt997Kf3BwA31X:b-bw8e14) ([raw file](https://github.com/batfish/batfish/blob/9038acb350e176ac53d24de2e4913fb75bb80586/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L1901)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

are management interfaces actually not connected? (trying to understand why you wouldn't `deactivate(IGNORE_MGMT)` for all active management interfaces)
</blockquote></details>

Updated.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/InactiveReason.java, line 16 at r2](https://reviewable.io/reviews/batfish/batfish/7939#-Mtgcv8u3wwtqT1YX4jQ:-MtjGZjYD3gpkD4j5lx6:b-7ql1td) ([raw file](https://github.com/batfish/batfish/blob/9038acb350e176ac53d24de2e4913fb75bb80586/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/InactiveReason.java#L16)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

typo: "no", not "not"
</blockquote></details>

fixed
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java, line 69 at r2](https://reviewable.io/reviews/batfish/batfish/7939#-MtecIS43eiR73Xxmo3u:-MtjGcza0vCReToJ6JQh:b-7ql1td) ([raw file](https://github.com/batfish/batfish/blob/9038acb350e176ac53d24de2e4913fb75bb80586/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java#L69)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Why does transience matter in a builder?
</blockquote></details>

fixed
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java, line 1755 at r2](https://reviewable.io/reviews/batfish/batfish/7939#-MteeDrLArN3BxZoeba7:-MtjIpa4-S7XQ1wcPY69:bmq2zm7) ([raw file](https://github.com/batfish/batfish/blob/9038acb350e176ac53d24de2e4913fb75bb80586/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java#L1755)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Annoying that we can't maintain the invariant that lineUp is nonnull iff `hasLineStatus()`. Maybe we could update `lineUp` when `setInterfaceType()` is called?
```
if (!hasLineStatus(newType)) {
  _lineUp = null;
} else if (_lineUp == null) {
  _lineUp = true;
}
```
I could see this making a useful difference if there are places where an interface is initially type `UNKNOWN` but can later be set to types without line status.
</blockquote></details>

Factored out `updateInterfaceType` from constructor, and made it reset values for `_blacklisted` and `_lineUp`. Replaced test calls to `setInterfaceType` with `updateInterfaceType`.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java, line 1964 at r2](https://reviewable.io/reviews/batfish/batfish/7939#-MtgQGHtDBpgwEGcB47r:-MtjJ5RACzktqpl7IM8U:b-7ql1td) ([raw file](https://github.com/batfish/batfish/blob/9038acb350e176ac53d24de2e4913fb75bb80586/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java#L1964)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

typo: "mark" not "nark" :space_invader: 
</blockquote></details>

fixed
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java, line 1993 at r2](https://reviewable.io/reviews/batfish/batfish/7939#-MtgR00jDtMnqEzCupxq:-MtjJ7RUDN3omW8MMHwC:b-886gsx) ([raw file](https://github.com/batfish/batfish/blob/9038acb350e176ac53d24de2e4913fb75bb80586/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java#L1993)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Technically not equivalent to calling `disconnect()` because `deactivate(LINE_DOWN)` will throw if the interface is inactive but line up, whereas `disconnect()` succeeds. Does this matter? (Seems semantically reasonable -- you can "disconnect" an inactive interface, but can't "deactivate by disconnecting" it since it's already inactive.)
</blockquote></details>

Fixed
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/interface_dependency/InterfaceDependencies.java, line 189 at r2](https://reviewable.io/reviews/batfish/batfish/7939#-MtgSuhu6EXVZDFo1-x4:-MtjJAk7Ey4PBaS0Qcoq:b-v0g9fe) ([raw file](https://github.com/batfish/batfish/blob/9038acb350e176ac53d24de2e4913fb75bb80586/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/interface_dependency/InterfaceDependencies.java#L189)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

I don't know the difference between `AGGREGATED` and `REDUNDANT` -- I take it redundant interfaces can have more than 2 logical L1 neighbors?
</blockquote></details>

redundant interfaces don't have an issue being connected to more than 2 neighbors, because there is no LACP negotiation.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/interface_dependency/InterfaceDependencies.java, line 365 at r2](https://reviewable.io/reviews/batfish/batfish/7939#-MtgUyu78wby1MV8MjOe:-MtjMgXWDOo19Qo5OS3W:b-cypxrc) ([raw file](https://github.com/batfish/batfish/blob/9038acb350e176ac53d24de2e4913fb75bb80586/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/interface_dependency/InterfaceDependencies.java#L365)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

i'm not clear on what this TODO means. Do we need to investigate ways an L1 edge could get lost here, or ascertain that that's possible?
</blockquote></details>

updated.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/InterfacePropertySpecifier.java, line 83 at r2](https://reviewable.io/reviews/batfish/batfish/7939#-MtgWyzs8hvzodb4xn__:-MtjNH6s9zfn55iTOgcX:bxzorjs) ([raw file](https://github.com/batfish/batfish/blob/9038acb350e176ac53d24de2e4913fb75bb80586/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/InterfacePropertySpecifier.java#L83)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

This relies on the invariant that lineUp is nonnull if `i.hasLineStatus()`, which isn't guaranteed because `Interface.setInterfaceType()` is public. see my other comment suggesting how to enforce that invariant.
</blockquote></details>

updated semantics and implementation
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/InterfacePropertySpecifier.java, line 87 at r2](https://reviewable.io/reviews/batfish/batfish/7939#-MtgX5jpBrQaVU98havb:-MtjNMWa8di9JKdB-mwd:b-hfpv0l) ([raw file](https://github.com/batfish/batfish/blob/9038acb350e176ac53d24de2e4913fb75bb80586/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/InterfacePropertySpecifier.java#L87)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

doesn't seem like the correct implementation -- and this method is unused, i think
</blockquote></details>

removed
___
*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/InterfaceTest.java, line 55 at r2](https://reviewable.io/reviews/batfish/batfish/7939#-MtgfVKw3QuoPFzUSMMz:-MtjQTLb-syF9iFwdG4s:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/9038acb350e176ac53d24de2e4913fb75bb80586/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/InterfaceTest.java#L55)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

At least one of these should check that `_lineUp` is null
</blockquote></details>

done

**Review by corinaminer — COMMENTED** [review]
> Reviewed 17 of 23 files at r3, 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7939)* status: 85 of 91 files reviewed, 3 unresolved discussions (waiting on @arifogel, @corinaminer, and @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/representation/aws/AwsConfiguration.java, line 360 at r4](https://reviewable.io/reviews/batfish/batfish/7939#-MtlJtjM0a7PxidqV7VZ:-MtlJtjM0a7PxidqV7V_:b-ubymji) ([raw file](https://github.com/batfish/batfish/blob/61d0b20109ff49af08733db1c8d575a9de32c264/projects/batfish/src/main/java/org/batfish/representation/aws/AwsConfiguration.java#L360)):*
> ```Java
>             LinkLocalAddress.of(LINK_LOCAL_IP),
>             "To AWS services");
>     outInterface.updateInterfaceType(InterfaceType.PHYSICAL);
> ```

This was only supposed to be used by tests and interface constructor, right? It's called in at least AWS and Cumulus conversion.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java, line 1996 at r4](https://reviewable.io/reviews/batfish/batfish/7939#-MtlEbgQ6MAaNyvjCbyG:-MtlEbgQ6MAaNyvjCbyH:b-g0sz9g) ([raw file](https://github.com/batfish/batfish/blob/61d0b20109ff49af08733db1c8d575a9de32c264/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java#L1996)):*
> ```Java
>    * Blacklist an interface because input data suggests it is down for maintenance, after which
>    * {@link #getActive()}, {@link #getLineUp()}, and {@link #getBlacklisted()} will return {@code
>    * false}. {@link #getInactiveReason()} will return {@link InactiveReason#BLACKLISTED} afterwards
> ```

`getBlacklisted()` will return true, yes?
```
{@link #getActive()}, {@link #getLineUp()}, and {@link #getBlacklisted()} will return {@code
   * false}.
```
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/InterfacePropertySpecifier.java, line 153 at r4](https://reviewable.io/reviews/batfish/batfish/7939#-MtlFqzoC9VHkc_AykQV:-MtlFqzoC9VHkc_AykQW:b-mqw0ea) ([raw file](https://github.com/batfish/batfish/blob/61d0b20109ff49af08733db1c8d575a9de32c264/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/InterfacePropertySpecifier.java#L153)):*
> ```Java
>                   Interface::getBlacklisted,
>                   Schema.BOOLEAN,
>                   "Whether the interface is considered down for maintenance"))
> ```

not blocking, but this description could be clearer -- e.g. "whether the interface is marked as down in provided runtime data". I think the current description makes it sound like this property is inferred from configs. Same thought about the description for `InactiveReason.BLACKLISTED`.
___
*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/InterfaceMatchersImpl.java, line 554 at r4](https://reviewable.io/reviews/batfish/batfish/7939#-MtlI_qx8MiqkpcUot1Y:-MtlI_qx8MiqkpcUot1Z:bfr8oek) ([raw file](https://github.com/batfish/batfish/blob/61d0b20109ff49af08733db1c8d575a9de32c264/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/InterfaceMatchersImpl.java#L554)):*
> ```Java
>   static final class IsBlacklisted extends FeatureMatcher<Interface, Boolean> {
>     IsBlacklisted(@Nonnull Matcher<? super Boolean> subMatcher) {
>       super(subMatcher, "an Interface with lineUp:", "lineUp");
> ```

update lineUp -> blacklisted

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7939)* status: 85 of 91 files reviewed, 3 unresolved discussions (waiting on @corinaminer and @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/representation/aws/AwsConfiguration.java, line 360 at r4](https://reviewable.io/reviews/batfish/batfish/7939#-MtlJtjM0a7PxidqV7VZ:-MtnkJEB7yq28uBGR2fD:b-k2rwtz) ([raw file](https://github.com/batfish/batfish/blob/61d0b20109ff49af08733db1c8d575a9de32c264/projects/batfish/src/main/java/org/batfish/representation/aws/AwsConfiguration.java#L360)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

This was only supposed to be used by tests and interface constructor, right? It's called in at least AWS and Cumulus conversion.
</blockquote></details>

Good catch. Fixed.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java, line 1996 at r4](https://reviewable.io/reviews/batfish/batfish/7939#-MtlEbgQ6MAaNyvjCbyG:-MtnlT5v3VITZWYDxI-N:b-886gsx) ([raw file](https://github.com/batfish/batfish/blob/61d0b20109ff49af08733db1c8d575a9de32c264/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java#L1996)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

`getBlacklisted()` will return true, yes?
```
{@link #getActive()}, {@link #getLineUp()}, and {@link #getBlacklisted()} will return {@code
   * false}.
```
</blockquote></details>

Fixed
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/InterfacePropertySpecifier.java, line 153 at r4](https://reviewable.io/reviews/batfish/batfish/7939#-MtlFqzoC9VHkc_AykQV:-MtnlVef4gMTj-qaqlQI:b-8q0ge0) ([raw file](https://github.com/batfish/batfish/blob/61d0b20109ff49af08733db1c8d575a9de32c264/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/InterfacePropertySpecifier.java#L153)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

not blocking, but this description could be clearer -- e.g. "whether the interface is marked as down in provided runtime data". I think the current description makes it sound like this property is inferred from configs. Same thought about the description for `InactiveReason.BLACKLISTED`.
</blockquote></details>

I actually had planned a description like yours. But after a discussion with @dhalperi, we decided to leave the description for now since the semantics will change soon to something slightly different than both the old description and your suggestion.
___
*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/InterfaceMatchersImpl.java, line 554 at r4](https://reviewable.io/reviews/batfish/batfish/7939#-MtlI_qx8MiqkpcUot1Y:-MtnmKIH6nOKdkkq_XbO:b-7ql1td) ([raw file](https://github.com/batfish/batfish/blob/61d0b20109ff49af08733db1c8d575a9de32c264/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/InterfaceMatchersImpl.java#L554)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

update lineUp -> blacklisted
</blockquote></details>

fixed

**Review by corinaminer — COMMENTED** [review]
:lgtm:

> Reviewed 6 of 23 files at r3, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7939#-:-MtnynZ-7IjfyBsBwL3k:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Pull request merged**
