### PR TITLE
Preserve original line numbers after on-the-fly flattening

### LINKED ISSUE #1131: Need mechanism to track line-numbers when flattening Juniper config
BF does not currently maintain the original line-number of a configuration construct when flattening a juniper configuration. Errors that reference a line-number are therefore hard to map back to the original config, since BF returns the line-number of the flattened configuration.

### PR DESCRIPTION
**Pull request by sfraint**
Previously, when configs were flattened on the fly, the artificial, flat line numbers were used for tracking structure definitions, red flags, etc, making mapping issues back to the original config difficult.

This PR adds line maps (introduced in #1707) to Palo Alto and Juniper parsers to help preserve original (nested or hierarchical) line numbers when on-the-fly flattening is performed.

Fixes #1131

### CODE REVIEW

**Comment by sfraint** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @sfraint and @anothermattbrown)

---

*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/FlatJuniperCombinedParser.java, line 22 at r2](https://reviewable.io/reviews/batfish/batfish/1732#-LFd84V64KUVdKQr34GD:-LFdDXXxBBse-vSgBBXk:b-kv55km) ([raw file](https://github.com/batfish/batfish/blob/3ca5d68d6f0052b6026a898bfaa517d11b2194fd/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/FlatJuniperCombinedParser.java#L22)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Why two constructors? This is inconsistent with `PaloAltoCombinedParser`? Also, `@Nullable`?
</blockquote></details>

The two-parameter constructor was already in use in a few places for `FlatJuniperCombinedParser`, I figured it was cleaner to leave those using the two-parameter constructor than supply `null` there. (and a two-param `PaloAltoCombinedParser` constructor is not yet needed)
Also,  re:`@Nullable` done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1732)*

**Comment by arifogel** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @arifogel and @anothermattbrown)

---

*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/FlatJuniperCombinedParser.java, line 22 at r2](https://reviewable.io/reviews/batfish/batfish/1732#-LFd84V64KUVdKQr34GD:-LFdVvHV-pyaTwlRmxdR:b-vmj3vf) ([raw file](https://github.com/batfish/batfish/blob/3ca5d68d6f0052b6026a898bfaa517d11b2194fd/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/FlatJuniperCombinedParser.java#L22)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

The two-parameter constructor was already in use in a few places for `FlatJuniperCombinedParser`, I figured it was cleaner to leave those using the two-parameter constructor than supply `null` there. (and a two-param `PaloAltoCombinedParser` constructor is not yet needed)
Also,  re:`@Nullable` done.
</blockquote></details>

I don't see any change for `@Nullable`

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1732)*

**Comment by arifogel** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown)

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1732)*

**Comment by arifogel** [comment]
:lgtm:

---

Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown)

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1732#-:-LFdWAf32iHArMJ7m9LK:bnfp4nl)*

**Pull request merged**
