### PR TITLE
Flow dispositions doc

### PR DESCRIPTION
**Pull request by anothermattbrown**

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8541)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown)

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8541)* status: all files reviewed, 2 unresolved discussions (waiting on @anothermattbrown)

___
*[`docs/flow_dispositions/README.md` line 6 at r1](https://reviewable.io/reviews/batfish/batfish/8541#-NBURnT8-KtVX66w0ENJ:-NBURnT8-KtVX66w0ENK:b3sm595) ([raw file](https://github.com/batfish/batfish/blob/271baa3d2137f93e1e6fd639b82d303f301c2baf/docs/flow_dispositions/README.md#L6)):*
> ```Markdown
> dispositions `ACCEPTED`, `DELIVERED_TO_SUBNET`, and `EXITS_NETWORK` mean the network delivered the flow somewhere
> (a specific endpoint or network boundary); the _failure_ dispositions `DENIED_IN`, `DENIED_OUT`, `INSUFFICIENT_INFO`, `LOOP`, `NEIGHBOR_UNREACHABLE`, `NO_ROUTE`, and `NULL_ROUTE`
> mean the network dropped the flow for some reason. 
> ```

Optional: discuss how these reflect in the symbolic graph? There are parameterless versions that correspond to disopsitions, but different algs may in fact look for interface-specific, vrf-specific, node-specific,  etc.
___
*[`docs/flow_dispositions/README.md` line 10 at r1](https://reviewable.io/reviews/batfish/batfish/8541#-NBURv9sDIDu23YiovNl:-NBURv9sDIDu23YiovNm:bt51xx1) ([raw file](https://github.com/batfish/batfish/blob/271baa3d2137f93e1e6fd639b82d303f301c2baf/docs/flow_dispositions/README.md#L10)):*
> ```Markdown
> 
> ## Flow disposition meanings
> Since batfish snapshots are not expected to be complete (e.g. there may be other peer networks or ISPs excluded from the snapshot), we use
> ```

Nit:, if making other edits only - `B`atfish



_Code quote:_
```Markdown
ba
```

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8541)* status: all files reviewed, 1 unresolved discussion (waiting on @anothermattbrown)

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8541)* status: all files reviewed, 1 unresolved discussion (waiting on @anothermattbrown)

**Pull request merged**
