### PR TITLE
Frr: Test ip reuse

### PR DESCRIPTION
**Pull request by ratulm**

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7793)* status: all files reviewed, 1 unresolved discussion (waiting on @ratulm)

___
*[projects/batfish/src/test/resources/org/batfish/grammar/cumulus_concatenated/testconfigs/ip_reuse, line 81 at r2](https://reviewable.io/reviews/batfish/batfish/7793#-Mqq6u6E1_7BG9IGiIN4:-Mqq6u6F26fdUO-fMWso:b-n490u7) ([raw file](https://github.com/batfish/batfish/blob/34b1aad68f093e8ec7341e13cd928fedbb760afc/projects/batfish/src/test/resources/org/batfish/grammar/cumulus_concatenated/testconfigs/ip_reuse#L81)):*
> ```
>  ip address 10.1.1.2/32
>  ip ospf area 0
>  ip address 10.2.1.1/24
> ```

Please update comments as appropriate

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7793)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @arifogel)

___
*[projects/batfish/src/test/resources/org/batfish/grammar/cumulus_concatenated/testconfigs/ip_reuse, line 81 at r2](https://reviewable.io/reviews/batfish/batfish/7793#-Mqq6u6E1_7BG9IGiIN4:-Mqq_fexC5sv94eX0Qsv:b69vcp4) ([raw file](https://github.com/batfish/batfish/blob/34b1aad68f093e8ec7341e13cd928fedbb760afc/projects/batfish/src/test/resources/org/batfish/grammar/cumulus_concatenated/testconfigs/ip_reuse#L81)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Please update comments as appropriate
</blockquote></details>

Decoupled the test interfaces and added comments.

**Review by arifogel — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7793)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ratulm)

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7793)* status: all files reviewed, 1 unresolved discussion (waiting on @ratulm)

___
*[projects/batfish/src/test/java/org/batfish/grammar/cumulus_concatenated/CumulusConcatenatedGrammarTest.java, line 978 at r3](https://reviewable.io/reviews/batfish/batfish/7793#-Mr0Xzs8Eiea6YfWaPhX:-Mr0Xzs8Eiea6YfWaPhY:b-7iycdl) ([raw file](https://github.com/batfish/batfish/blob/d2284d73a417812b8ac6d120e8980e48dd8cc908/projects/batfish/src/test/java/org/batfish/grammar/cumulus_concatenated/CumulusConcatenatedGrammarTest.java#L978)):*
> ```Java
>   }
> 
>   @Test
> ```

You can xfail this for now if you want to merge:
```
@Test(expected = AssertionError.class) // xfail this until (description and/or issue link) is fixed```
```

**Review by ratulm — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7793)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ratulm)

**Pull request merged**
