### PR TITLE
Cisco: set BGP origin type when using default originate

### PR DESCRIPTION
**Pull request by progwriter**
*Context*:
Routing policy would not set OriginType on default routes, causing ibdp to crash

*Fix*:
When matching default routes, also use `SetOrigin` statements.
Since there is no easy way to nest put an `If` into a disjuction, just pulled this out into a separate policy, hence the ref changes.

*Note*
Made test for IOS; Test for nxos already exists, but is skipped (it needs more dataplane support, coming soon).

### CODE REVIEW

**Comment by arifogel** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 2077 at r1](https://reviewable.io/reviews/batfish/batfish/1528#-LDnJx-d8902qlaXNRro:-LDnJx-d8902qlaXNRrp:bbzy8qu) ([raw file](https://github.com/batfish/batfish/blob/e7270c28a244ccf0be0b5f22d862a797c9c68c23/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L2077)):*
> ```Java
>                     matchDefaultRoute,
>                     ImmutableList.of(
>                         new SetOrigin(new LiteralOrigin(OriginType.IGP, null)),
> ```

Is this always `IGP`? I thought it was configuration-format-dependent, or even always `INCOMPLETE`.
Applies in multiple places.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1528)*

**Comment by arifogel** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 2077 at r1](https://reviewable.io/reviews/batfish/batfish/1528#-LDnJx-d8902qlaXNRro:-LDnRekn3NbH26KLjoch:b-7j1uib) ([raw file](https://github.com/batfish/batfish/blob/e7270c28a244ccf0be0b5f22d862a797c9c68c23/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L2077)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

For IOS definitely `IGP` (checked in GNS3).
My understanding is redistribution gives you `INCOMPLETE` while network statements and default-originate (which are essentially "fake" network statements) will result in `IGP`.
</blockquote></details>

What about Arista?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1528)*

**Comment by progwriter** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 2077 at r1](https://reviewable.io/reviews/batfish/batfish/1528#-LDnJx-d8902qlaXNRro:-LDom50d483RqJis6LZH:bkzshxu) ([raw file](https://github.com/batfish/batfish/blob/e7270c28a244ccf0be0b5f22d862a797c9c68c23/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L2077)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

What about Arista?
</blockquote></details>

ugh.... So in Arista it's incomplete. Without spending hours on trying every possible os variant covered by the parser (and doing a giant switch), I propose the following compromise: incomplete seems like a safer bet, unless it's ios and we know it's IGP.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoNxConversions.java, line 349 at r1](https://reviewable.io/reviews/batfish/batfish/1528#-LDnZjmd12AVgbp4Esmw:-LDol_ti8V7_ES6Pvybb:bfbq99i) ([raw file](https://github.com/batfish/batfish/blob/e7270c28a244ccf0be0b5f22d862a797c9c68c23/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoNxConversions.java#L349)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Why so verbose? Since it's always a disjunction of 1 thing, just inline MATCH_DEFAULT_ROUTE in the `IF` below?
</blockquote></details>

Good point, done.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoNxConversions.java, line 359 at r1](https://reviewable.io/reviews/batfish/batfish/1528#-LDnZqxE-Q6nS8nJ3zHs:-LDolfvX1u0pFWtyF4li:b-5dj3pu) ([raw file](https://github.com/batfish/batfish/blob/e7270c28a244ccf0be0b5f22d862a797c9c68c23/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoNxConversions.java#L359)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I worked fairly hard to have some sort of logical structure to the code here... ideally, nothing is defined "well before it's used" and the things that have effects outside of this scope are last.

Any reason not to put this line absolutely last?

(Also, use your own discretion on what logical structure means...)
</blockquote></details>

not sure what you mean by absolutely last... the `add` happens after the `defaultRouteExportPolicy` has been fully defined, but before moving on to construction of generation policy, which seems logical. Am I just thinking about this wrong?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1528)*

**Comment by dhalperi** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1528#-:-LDooboQ0RSY8icpeH0l:bnfp4nl)*

**Pull request merged**
