### PR TITLE
Introduce Layer1Topologies[Factory]

### PR DESCRIPTION
**Pull request by dhalperi**
The logic for generating the various shapes of L1 topology is scattered and
repeated throughout the code. Move it all into one place, add clear
documentation for what's going on, improve warnings.

Use this to simplify TopologyProvider, TopologyContext, and the L3Adajacencies
factories.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7207)* status: 0 of 29 files reviewed, all discussions resolved (waiting on @anothermattbrown)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/Layer1Topologies.java, line 155 at r1](https://reviewable.io/reviews/batfish/batfish/7207#-MfsFSTX4dxpkB0dq03V:-MfsFSTX4dxpkB0dq03W:bz241i0) ([raw file](https://github.com/batfish/batfish/blob/fbd0082e65bf0da631edb9c28b1ff623d0598889/projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/Layer1Topologies.java#L155)):*
> ```Java
> 
>   /** {@link #_logicalL1} filtered to active-active edges and making all edges bidirectional. */
>   private final Layer1Topology _activeLogicalL1;
> ```

FYI the `activeLogicalL1` topology is the thing that was called `logicalLayer1Topology` before.

One of the key goals of this change is to make more intermediate steps available. For example, there was previously no way to get access to the logical topology, but not non-cleaned-and-symmetricalized, without recomputing it from basics.

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7207)* status: 0 of 29 files reviewed, all discussions resolved (waiting on @anothermattbrown)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/HybridL3Adjacencies.java, line 56 at r1](https://reviewable.io/reviews/batfish/batfish/7207#-MfsFrLb2hCK4BQE1C_m:-MfsFrLb2hCK4BQE1C_n:b-851xjk) ([raw file](https://github.com/batfish/batfish/blob/fbd0082e65bf0da631edb9c28b1ff623d0598889/projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/HybridL3Adjacencies.java#L56)):*
> ```Java
>       Map<String, Configuration> configurations) {
>     Set<String> nodesWithL1Topology =
>         layer1Topologies.getCombinedL1().getGraph().edges().stream()
> ```

FYI this code used to take both `raw` and `logical` because `logical` was pre-filtered to only active edges. Therefore, we needed to go back to `raw` in order to find nodes that had no active edges.

Now we can just look at the combined topology, since that has not yet been filtered and will have all nodes mentioned in either raw or synthesized topology, which is a strict superset of all nodes mentioned in the logical topology (and should be equal to raw union logical).

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7207)* status: 0 of 29 files reviewed, all discussions resolved (waiting on @anothermattbrown)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/broadcast/L3AdjacencyComputer.java, line 51 at r1](https://reviewable.io/reviews/batfish/batfish/7207#-MfsGUr0CUQiyexwwfQX:-MfsGUr0CUQiyexwwfQY:b-klecp2) ([raw file](https://github.com/batfish/batfish/blob/fbd0082e65bf0da631edb9c28b1ff623d0598889/projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/broadcast/L3AdjacencyComputer.java#L51)):*
> ```Java
>     _physicalInterfaces = computePhysicalInterfaces(configs);
>     _ethernetHubs =
>         computeEthernetHubs(configs, _physicalInterfaces, _layer1Topologies.getActiveLogicalL1());
> ```

FYI this is still `activeLogicalL1` as that is the version that has no behavior change from before. That will change later, but in this PR I didn't want to change the behavior here.

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 29 of 29 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7207)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dhalperi)

**Pull request merged**
