### PR TITLE
Docs: proposal for new l3 adjacencies algorithm

### PR DESCRIPTION
**Pull request by arifogel**
Add proposal for new l3 adjacencies algorithm and older resources

Co-authored-by: Ari Fogel <ari@fogelti.me>
Co-authored-by: Dan Halperin <dan@intentionet.com>

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8549)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel)

___
*[`docs/proposals/extensible_l3_adjacencies/resources/l3_edge_establishment_and_relation_to_l1_l2/README.md` line 108 at r3](https://reviewable.io/reviews/batfish/batfish/8549#-NCfoUKdD5J97bv1xJcx:-NCfoUKdD5J97bv1xJcy:b-xedg38) ([raw file](https://github.com/batfish/batfish/blob/29299156b9d05700c4caaced29f25d727b612d90/docs/proposals/extensible_l3_adjacencies/resources/l3_edge_establishment_and_relation_to_l1_l2/README.md#L108)):*
> ```Markdown
> networks.
> 
> _Aside: We have other plans [Broadcast domain discovery] to reimplement the current L2 broadcast
> ```

Is this meant to be a link?



_Code quote:_
```Markdown
[Broadcast domain discovery] 
```

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8549)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[`docs/proposals/extensible_l3_adjacencies/resources/l3_edge_establishment_and_relation_to_l1_l2/README.md` line 108 at r3](https://reviewable.io/reviews/batfish/batfish/8549#-NCfoUKdD5J97bv1xJcx:-NCfvSZ29gEG23cpqdRK:b3rdove) ([raw file](https://github.com/batfish/batfish/blob/29299156b9d05700c4caaced29f25d727b612d90/docs/proposals/extensible_l3_adjacencies/resources/l3_edge_establishment_and_relation_to_l1_l2/README.md#L108)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Is this meant to be a link?
</blockquote></details>

Thought I was missing something!  Added the other doc and linked.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8549)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel)

___
*[`docs/proposals/extensible_l3_adjacencies/resources/broadcast_domain_discovery/README.md` line 63 at r4](https://reviewable.io/reviews/batfish/batfish/8549#-NCfypdN-774Efy2wvje:-NCfypdN-774Efy2wvjf:bjxty6r) ([raw file](https://github.com/batfish/batfish/blob/c79a8de4f2f2fe30c303439078cb06c415c40b88/docs/proposals/extensible_l3_adjacencies/resources/broadcast_domain_discovery/README.md#L63)):*
> ```Markdown
> 
> We have since tried reducing complexity by using ranges of VLANs that have similar behavior. This
> has proved challenging to get correct (Imperva found a bunch of bugs in the first version) and
> ```

"Open Source users on Slack from Imperva"?

(I'm imagining that's why it's okay we put this here?)



_Code quote:_
```Markdown
Imperva
```

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8549)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8549)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

___
*[`docs/proposals/extensible_l3_adjacencies/resources/broadcast_domain_discovery/README.md` line 63 at r4](https://reviewable.io/reviews/batfish/batfish/8549#-NCfypdN-774Efy2wvje:-NCg1hvy6LRMsYN0y4Ij:b-jfu3cc) ([raw file](https://github.com/batfish/batfish/blob/c79a8de4f2f2fe30c303439078cb06c415c40b88/docs/proposals/extensible_l3_adjacencies/resources/broadcast_domain_discovery/README.md#L63)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

"Open Source users on Slack from Imperva"?

(I'm imagining that's why it's okay we put this here?)
</blockquote></details>

Adjusted the language

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8549)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Pull request merged**
