### PR TITLE
Sonic: Deserialize and convert resolve.conf

### PR DESCRIPTION
**Pull request by ratulm**
After #8204 and #8207

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 7 of 17 files at r1, 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8208)* status: all files reviewed, 4 unresolved discussions (waiting on @dhalperi and @ratulm)

___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/grammar/SonicControlPlaneExtractor.java, line 77 at r2](https://reviewable.io/reviews/batfish/batfish/8208#-MzXOywTCNRO3Eky9C2w:-MzXOywTCNRO3Eky9C2x:b-tcegyv) ([raw file](https://github.com/batfish/batfish/blob/a80788b937dd12e5c45ded4a35209331a5638003/projects/batfish/src/main/java/org/batfish/vendor/sonic/grammar/SonicControlPlaneExtractor.java#L77)):*
> ```Java
>           ResolveConf.deserialize(
>               _fileTexts.get(resolveConfFilename),
>               _fileResults.get(configDbFilename).getWarnings());
> ```

Should this be `resolveConfFilename`?
___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/ResolveConf.java, line 21 at r2](https://reviewable.io/reviews/batfish/batfish/8208#-MzXPTRB-KBiHk4k8aGF:-MzXPTRB-KBiHk4k8aGG:b-mggmz4) ([raw file](https://github.com/batfish/batfish/blob/a80788b937dd12e5c45ded4a35209331a5638003/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/ResolveConf.java#L21)):*
> ```Java
>   private @Nonnull final List<Ip6> _nameservers6;
> 
>   public ResolveConf(List<Ip> nameservers, List<Ip6> nameservers6) {
> ```

Perhaps make this private and make the immutable copies in `deserialize`?
I don't see any other usages in this PR.
___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/ResolveConf.java, line 26 at r2](https://reviewable.io/reviews/batfish/batfish/8208#-MzXPMKR5tZvKAAmhT0f:-MzXPMKR5tZvKAAmhT0g:blred2o) ([raw file](https://github.com/batfish/batfish/blob/a80788b937dd12e5c45ded4a35209331a5638003/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/ResolveConf.java#L26)):*
> ```Java
>   }
> 
>   public static ResolveConf deserialize(String resolveConfText, Warnings warnings) {
> ```

nit: `@Nonnull` return type
___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/ResolveConf.java, line 32 at r2](https://reviewable.io/reviews/batfish/batfish/8208#-MzXQOQ0C0v2VluOgzlF:-MzXQOQ0C0v2VluOgzlG:b9yefq) ([raw file](https://github.com/batfish/batfish/blob/a80788b937dd12e5c45ded4a35209331a5638003/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/ResolveConf.java#L32)):*
> ```Java
>     String[] lines = resolveConfText.split("\n");
>     for (String line : lines) {
>       String[] parts = line.split("\\s");
> ```

From my read of `split` javadoc, this won't work with leading whitespace.
Rather than splitting by lines and then by whitespace, why not just iterate over the file with a line regex until no more matches are found?
Something like `"(?m)^\\s*nameserver\\s+(^[#\\s]+).*$"`, then grab group 1.
Note this also handles trailing comments.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8208)* status: all files reviewed, 4 unresolved discussions (waiting on @dhalperi and @ratulm)

___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/ResolveConf.java, line 32 at r2](https://reviewable.io/reviews/batfish/batfish/8208#-MzXQOQ0C0v2VluOgzlF:-MzXSPBzADJIPoxsTWNU:b9lnjnb) ([raw file](https://github.com/batfish/batfish/blob/a80788b937dd12e5c45ded4a35209331a5638003/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/ResolveConf.java#L32)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

From my read of `split` javadoc, this won't work with leading whitespace.
Rather than splitting by lines and then by whitespace, why not just iterate over the file with a line regex until no more matches are found?
Something like `"(?m)^\\s*nameserver\\s+(^[#\\s]+).*$"`, then grab group 1.
Note this also handles trailing comments.
</blockquote></details>

stricter: `"(?m)^\\s*nameserver\\s+(^[#\\s]+)\\s*(#.*)?$"`

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8208)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel and @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/ResolveConf.java, line 32 at r2](https://reviewable.io/reviews/batfish/batfish/8208#-MzXQOQ0C0v2VluOgzlF:-MzX_STP3619Q_byLT_k:bs495p3) ([raw file](https://github.com/batfish/batfish/blob/a80788b937dd12e5c45ded4a35209331a5638003/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/ResolveConf.java#L32)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

stricter: `"(?m)^\\s*nameserver\\s+(^[#\\s]+)\\s*(#.*)?$"`
</blockquote></details>

made it robust to extra whitespace while keeping the line-by-line splitting approach. 

are those trailing comments legal? i couldn't find a pointer.

**Review by arifogel — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8208)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi and @ratulm)

___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/ResolveConf.java, line 32 at r2](https://reviewable.io/reviews/batfish/batfish/8208#-MzXQOQ0C0v2VluOgzlF:-MzXbveK1c9ccNRXK54w:bhga2lh) ([raw file](https://github.com/batfish/batfish/blob/a80788b937dd12e5c45ded4a35209331a5638003/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/ResolveConf.java#L32)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

made it robust to extra whitespace while keeping the line-by-line splitting approach. 

are those trailing comments legal? i couldn't find a pointer. 
</blockquote></details>

Yes they are valid, just tested. They are generally valid in all linux `.conf` files

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8208)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi and @ratulm)

___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/ResolveConf.java, line 32 at r2](https://reviewable.io/reviews/batfish/batfish/8208#-MzXQOQ0C0v2VluOgzlF:-MzXcc5tC9OfrmM4JtMU:bsiciw2) ([raw file](https://github.com/batfish/batfish/blob/a80788b937dd12e5c45ded4a35209331a5638003/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/ResolveConf.java#L32)):*
Also, on linux (Ubuntu 18.04 at least), only up to 3 nameservers may be used:
> Up to MAXNS (currently 3, see <resolv.h>) name servers may be listed, one per keyword.

It's not clear if that's 3 ipv4 and 3 ipv6, or 3 total. My guess is total.

We can probably defer limiting for now.

**Review by arifogel — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8208)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dhalperi)

**Pull request merged**
