### PR TITLE
Delete the temp directories created while forking

### PR DESCRIPTION
**Pull request by ratulm**

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6358)* status: all files reviewed, 2 unresolved discussions (waiting on @ratulm and @sfraint)

___
*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, line 1549 at r1](https://reviewable.io/reviews/batfish/batfish/6358#-MKNiWo_0bn-TsVDuzDu:-MKNiWoaA_w1IgZby0Hg:b3hrz77) ([raw file](https://github.com/batfish/batfish/blob/06d4d2a85197f0209c577f41730942d1ae582272/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java#L1549)):*
> ```Java
> 
>       // do not need this directory anymore
>       CommonUtil.deleteDirectory(unzipDir);
> ```

FYI `CommonUtil.createTempDirectory` calls:
```
tempDir.toFile().deleteOnExit();
```
I hope the explicit deletion does not interfere.
___
*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, line 1598 at r1](https://reviewable.io/reviews/batfish/batfish/6358#-MKNjP-f5uagO_rvCbMA:-MKNjP-f5uagO_rvCbMB:b-qixsnz) ([raw file](https://github.com/batfish/batfish/blob/06d4d2a85197f0209c577f41730942d1ae582272/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java#L1598)):*
> ```Java
>       throw new BatfishException(String.format("Error forking snapshot: %s", e.getMessage()), e);
>     } finally {
>       CommonUtil.deleteDirectory(newSnapshotInputsDir);
> ```

Just use `FileUtils.deleteDirectory` in both places. This function already throws `IOException`. No new `BatfishException`s.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6358)* status: all files reviewed, 3 unresolved discussions (waiting on @ratulm and @sfraint)

___
*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, line 1596 at r1](https://reviewable.io/reviews/batfish/batfish/6358#-MKNja6KCUJhNBukbKae:-MKNja6KCUJhNBukbKaf:b6fnloz) ([raw file](https://github.com/batfish/batfish/blob/06d4d2a85197f0209c577f41730942d1ae582272/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java#L1596)):*
> ```Java
>           baseSnapshotId);
>     } catch (Exception e) {
>       throw new BatfishException(String.format("Error forking snapshot: %s", e.getMessage()), e);
> ```

We really need to clean up these exceptions.
FWICT `e` can be narrowed to `BatfishException | UncheckedIOException`. 
Eventually we should get rid of `BatfishException`. I'd prefer you didn't throw a new one here, but you can defer fixing that until `initSnapshot` exceptions are improved.

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6358)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @arifogel and @sfraint)

___
*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, line 1549 at r1](https://reviewable.io/reviews/batfish/batfish/6358#-MKNiWo_0bn-TsVDuzDu:-MKNngU76Vu2A4UGWvkO:b-e48frx) ([raw file](https://github.com/batfish/batfish/blob/06d4d2a85197f0209c577f41730942d1ae582272/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java#L1549)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

FYI `CommonUtil.createTempDirectory` calls:
```
tempDir.toFile().deleteOnExit();
```
I hope the explicit deletion does not interfere.
</blockquote></details>

I don't think it does, and we are using this pattern in upload snapshot.

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6358)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

**Pull request merged**
