### PR TITLE
A10: VLAN and VirtualEthernet conversion

### PR DESCRIPTION
**Pull request by sfraint**
* Add support for converting VLANs (which configure switchport properties on converted `tagged` and `untagged` interfaces)
* Add support for extracting and converting VirtualEthernet interfaces (which correspond to VI model VLAN interfaces)

### CODE REVIEW

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7424)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @arifogel and @corinaminer)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7424#-MkE19kM9MN9rqVMmlgw:-MkE19kM9MN9rqVMmlgx:b1hdxwc) (no related file):*
will add reference tracking separately

---

**Review by corinaminer — COMMENTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7424)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/vendor/a10/representation/A10Configuration.java, line 75 at r1](https://reviewable.io/reviews/batfish/batfish/7424#-MkE69Ig26RRO5e8Ie3A:-MkE69IhDvXo03JtRxlH:bmpm2hu) ([raw file](https://github.com/batfish/batfish/blob/e1ceca505b2434f5c141c2b9b5bf64847a5da109/projects/batfish/src/main/java/org/batfish/vendor/a10/representation/A10Configuration.java#L75)):*
> ```Java
>       case VE:
>       default:
>         return true;
> ```

should this throw (or `assert false`) in the `default` case to force developers to check this for new interface types?

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7424)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/vendor/a10/representation/A10Configuration.java, line 75 at r1](https://reviewable.io/reviews/batfish/batfish/7424#-MkE69Ig26RRO5e8Ie3A:-MkEBRw95qtGadaTX9Dy:b-t1bxla) ([raw file](https://github.com/batfish/batfish/blob/e1ceca505b2434f5c141c2b9b5bf64847a5da109/projects/batfish/src/main/java/org/batfish/vendor/a10/representation/A10Configuration.java#L75)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

should this throw (or `assert false`) in the `default` case to force developers to check this for new interface types?
</blockquote></details>

sure, added

**Review by corinaminer — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7424#-:-MkECqKV9eBnYg_erHjb:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Pull request merged**
