### PR TITLE
NXOS fix aggregate-address implementation

### PR DESCRIPTION
**Pull request by arifogel**
- fix lexing for aggregate-address route-map keywords
- use BGP process-level aggregates instead of vrf-level following batfish/batfish#7067

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7081)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @arifogel and @corinaminer)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7081#-McW9DNe0fq4iI8znIlI:-McW9DNe0fq4iI8znIlJ:bjdbzof) (no related file):*
Should not merge until exportFromBgpRib is implemented for NX-OS

---

**Review by corinaminer — COMMENTED** [review]
> Reviewed 5 of 7 files at r1, 2 of 2 files at r2.
> Dismissed @arifogel from a discussion.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7081)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7081#-McW9DNe0fq4iI8znIlI:-McjYx4WCMYeKtzfAPIA:b-verypz) (no related file):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Should not merge until exportFromBgpRib is implemented for NX-OS
</blockquote></details>

done in #7087

---

**Review by corinaminer — COMMENTED** [review]
+reviewer:@dhalperi for last revision

> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7081#-:-McjelHUC_XGEiE1vUC6:bajeje)* status: 5 of 7 files reviewed, all discussions resolved (waiting on @corinaminer and @dhalperi)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7081)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Pull request merged**
