### PR TITLE
CI: Add GitHub Actions version of Pre-Commit

### PR DESCRIPTION
**Pull request by sfraint**
GitHub Actions version of the Buildkite pre-commit pipeline. See [the successful run here](https://github.com/batfish/batfish/actions/runs/2828347961).

----

Changes from the pipeline:
* Run on bare `runners` instead of inside containers
  * ran into some permissions issues, see related issue https://github.com/actions/runner/issues/691
* Combine bazel steps into a single job and use GitHub Actions cache
* Combine ref tests into a single job
  * though it is possible to split them back out if we want

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8456)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @arifogel)

___
*[`.github/workflows/pre-commit.yml` line 102 at r2](https://reviewable.io/reviews/batfish/batfish/8456#-N93rXd07Ppb9MvSN86D:-N93rXd07Ppb9MvSN86E:br2cfxq) ([raw file](https://github.com/batfish/batfish/blob/0405574e77188f3652178ad13250bdb110f660c5/.github/workflows/pre-commit.yml#L102)):*
> ```YAML
>         with:
>           path: "~/.cache/bazel"
>           key: ${{runner.os}}-bazel-${{ hashFiles('WORKSPACE') }}-${{ hashFiles('maven_install.json') }}-${{ needs.get_date.outputs.ymd }}
> ```

FYI, hashFiles takes a list and also has globs, which seems cleaner.



_Code quote:_
```YAML
hashFiles('WORKSPACE') }}-${{ hashFiles('maven_install.json')
```

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8456)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @arifogel and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/8456#-N94EAVa5KQOyYBS3lNe:-N94EAVa5KQOyYBS3lNf:bfgudjq) (no related file):*
- Does it work if you PR from your fork?

- I'm having trouble with codecov results: the `Details` link in the checks table is busted. I wonder if we're supposed to be using the codecov action?

___

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8456)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @arifogel and @dhalperi)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/8456#-N94EAVa5KQOyYBS3lNe:-N97IuPz0M_cjpRSKjR4:b-aich8x) (no related file):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

- Does it work if you PR from your fork?

- I'm having trouble with codecov results: the `Details` link in the checks table is busted. I wonder if we're supposed to be using the codecov action?
</blockquote></details>

1. I don't think that will work yet - I was looking at triggers and there is one for `pull_requests` (https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request), so it should be easy to add
2. Ack, I'll TAL

___

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8456)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dhalperi and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/8456#-N94EAVa5KQOyYBS3lNe:-N98PxP52984CaBHQXa6:bup91sg) (no related file):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

1. I don't think that will work yet - I was looking at triggers and there is one for `pull_requests` (https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request), so it should be easy to add
2. Ack, I'll TAL
</blockquote></details>

Ugh, there's apparently [not a trivial way to have it run on any push and any PR update without having it run twice on PRs originating in the main repo](https://github.com/orgs/community/discussions/26741). I'll see if theres something else we can do

___

**Comment by dhalperi** [comment]
Can you not just restrict push builds to master?

**Comment by sfraint** [comment]
You can restrict it to master but then feature branches don't run CI until they're in PR. I guess that's fine

**Comment by dhalperi** [comment]
Isn't that the behavior we already have?

**Review by sfraint — COMMENTED** [review]
Yeah, I think you're right; updated

> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8456#-:-N98S6io56EHi3iqDk0T:bexrspa)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @arifogel and @sfraint)

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8456)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8456)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8456)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8456)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

**Pull request merged**
