### PR TITLE
Parsing for Junos static ipv6 routes

### PR DESCRIPTION
**Pull request by SLarkworthy**
Adds support for parsing ipv6 static routes. Changes the behavior of  `routing-options rib` to only accept certain patterns for rib name. 

Junos docs referenced:
https://www.juniper.net/documentation/us/en/software/junos/static-routing/topics/topic-map/config_junos_routing_table.html#id-example-exporting-specific-routes-from-one-routing-table-into-another-routing-table
https://www.juniper.net/documentation/us/en/software/junos/vpn-l3/topics/topic-map/l3-vpns-routing-instances.html#id-configuring-routing-instances-on-pe-routers-in-vpns__d57160e331

### CODE REVIEW

**Comment by dhalperi** [comment]
*[`projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_routing_instances.g4` line 340 at r1](https://reviewable.io/reviews/batfish/batfish/9241#-O8ghfD-DcRHcDccyyoa:-O8ghfD-DcRHcDccyyob:b3waipy) ([raw file](https://github.com/batfish/batfish/blob/075caa34f3035e85d498bafab945921b5c96ffee/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_routing_instances.g4#L340)):*
> ```ANTLR
> ;
> 
> ro_static6
> ```

I might suggest this should be `ror6_static`:

`routing-options rib <somethingv6 like inet6.0>` is why I put the 6 there after the `r` for `rib`. Then it's just `static`.

This would imply more for child prefixes.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/9241)* status: all files reviewed, 8 unresolved discussions (waiting on @SLarkworthy)

___
*[`projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_common.g4` line 245 at r1](https://reviewable.io/reviews/batfish/batfish/9241#-O8gge0mBCdBPXr8nGPF:-O8gge0mBCdBPXr8nGPG:b9j3pyc) ([raw file](https://github.com/batfish/batfish/blob/075caa34f3035e85d498bafab945921b5c96ffee/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_common.g4#L245)):*
> ```ANTLR
> ipv6_prefix: IPV6_PREFIX;
> 
> ipv6_address: IPV6_ADDRESS;
> ```

isn't this the same as 2 lines up?
___
*[`projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_routing_instances.g4` line 661 at r1](https://reviewable.io/reviews/batfish/batfish/9241#-O8gguH-C9st0nd0ZbEU:-O8gguH-C9st0nd0ZbEV:bxfw2n2) ([raw file](https://github.com/batfish/batfish/blob/075caa34f3035e85d498bafab945921b5c96ffee/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_routing_instances.g4#L661)):*
> ```ANTLR
> :
>     ROUTE
>    (
> ```

you can get rid of the parens now to clean it up.
___
*[`projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_routing_instances.g4` line 662 at r1](https://reviewable.io/reviews/batfish/batfish/9241#-O8ghuaa2s2HybMjiko4:-O8ghuaa2s2HybMjiko5:bjbn1n8) ([raw file](https://github.com/batfish/batfish/blob/075caa34f3035e85d498bafab945921b5c96ffee/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_routing_instances.g4#L662)):*
> ```ANTLR
>     ROUTE
>    (
>       prefix = ip_prefix_default_32
> ```

note I refer to this one below.
___
*[`projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_routing_instances.g4` line 673 at r1](https://reviewable.io/reviews/batfish/batfish/9241#-O8ggxszEg3LcxRvVmf6:-O8ggxszEg3LcxRvVmf7:bjq42rj) ([raw file](https://github.com/batfish/batfish/blob/075caa34f3035e85d498bafab945921b5c96ffee/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_routing_instances.g4#L673)):*
> ```ANTLR
> :
>     ROUTE
>    (
> ```

ditto on parens.
___
*[`projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_routing_instances.g4` line 674 at r1](https://reviewable.io/reviews/batfish/batfish/9241#-O8ggz2D7EZ2oAV0qvBG:-O8ggz2D7EZ2oAV0qvBH:b-3s67nj) ([raw file](https://github.com/batfish/batfish/blob/075caa34f3035e85d498bafab945921b5c96ffee/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_routing_instances.g4#L674)):*
> ```ANTLR
>     ROUTE
>    (
>        prefix = ipv6_prefix
> ```

you may want ipv6_prefix_default_128 like we have `ip_prefix_default_32`. It's basically prefix or address both allowed, and if address we make it a /128.
___
*[`projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4` line 2388 at r1](https://reviewable.io/reviews/batfish/batfish/9241#-O8giGWGAH0DbaFsoU4z:-O8giGWGAH0DbaFsoU5-:bqrk40u) ([raw file](https://github.com/batfish/batfish/blob/075caa34f3035e85d498bafab945921b5c96ffee/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4#L2388)):*
> ```ANTLR
> RIB: 'rib'
>     {
>         switch(lastTokenType()) {
> ```

yeah let's chat about this one. Probably totally reasonable, not sure.
___
*[`projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4` line 3629 at r1](https://reviewable.io/reviews/batfish/batfish/9241#-O8giLcK6cD-6NcU1VQd:-O8giLcK6cD-6NcU1VQe:b-pbwiae) ([raw file](https://github.com/batfish/batfish/blob/075caa34f3035e85d498bafab945921b5c96ffee/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4#L3629)):*
> ```ANTLR
> F_RoutingInstanceNameChar
> :
>    [A-Za-z] | '-'
> ```

maybe add a link?
___
*[`projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4` line 4983 at r1](https://reviewable.io/reviews/batfish/batfish/9241#-O8giWfdE3VLZUKyX-U2:-O8giWfdE3VLZUKyX-U3:b-g46fmg) ([raw file](https://github.com/batfish/batfish/blob/075caa34f3035e85d498bafab945921b5c96ffee/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4#L4983)):*
> ```ANTLR
> M_RibName_PERIOD: '.' -> type(PERIOD);
> M_RibName_UINT8: F_Uint8 -> type(UINT8), popMode;
> M_RibName_WS: F_WhitespaceChar+ -> skip;
> ```

hmm this is what I expected would handle those spaces, so what the heck :)
___
*[`projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java` line 6504 at r1](https://reviewable.io/reviews/batfish/batfish/9241#-O8gitg_13Qz4E6Ud_r8:-O8gitg_13Qz4E6Ud_r9:b-dlz6o1) ([raw file](https://github.com/batfish/batfish/blob/075caa34f3035e85d498bafab945921b5c96ffee/projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java#L6504)):*
> ```Java
>             .get("TEST-VRF.inet6.0");
>     {
>       assertTrue(routesDefault.getStaticRoutes().isEmpty());
> ```

since the variable names are different we don't need the scoping `{}`. That's needed only if you want to prevent leaks out of context.

I might say:

```
assertThat(c.getMasterLogicalSystem().getRoutingInstances().get("default").getRibs().get(...).getStaticRoutes(),
    isEmpty())
``` or something like that.

The use of `isEmpty()` is nice because it will not just present failure, it will say "expected empty, but got [...]"
```

**Review by SLarkworthy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/9241)* status: 1 of 8 files reviewed, 5 unresolved discussions (waiting on @dhalperi)

___
*[`projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_common.g4` line 245 at r1](https://reviewable.io/reviews/batfish/batfish/9241#-O8gge0mBCdBPXr8nGPF:-O8i72e253B7b7R6o8yN:b-90hcp1) ([raw file](https://github.com/batfish/batfish/blob/075caa34f3035e85d498bafab945921b5c96ffee/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_common.g4#L245)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

isn't this the same as 2 lines up?
</blockquote></details>

whoops, removed.
___
*[`projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_routing_instances.g4` line 340 at r1](https://reviewable.io/reviews/batfish/batfish/9241#-O8ghfD-DcRHcDccyyoa:-O8i7IaH4mA6wlE4ZeWh:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/075caa34f3035e85d498bafab945921b5c96ffee/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_routing_instances.g4#L340)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I might suggest this should be `ror6_static`:

`routing-options rib <somethingv6 like inet6.0>` is why I put the 6 there after the `r` for `rib`. Then it's just `static`.

This would imply more for child prefixes.
</blockquote></details>

done
___
*[`projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_routing_instances.g4` line 661 at r1](https://reviewable.io/reviews/batfish/batfish/9241#-O8gguH-C9st0nd0ZbEU:-O8i7SXk-euVMHX7_A0H:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/075caa34f3035e85d498bafab945921b5c96ffee/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_routing_instances.g4#L661)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

you can get rid of the parens now to clean it up.
</blockquote></details>

done
___
*[`projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_routing_instances.g4` line 674 at r1](https://reviewable.io/reviews/batfish/batfish/9241#-O8ggz2D7EZ2oAV0qvBG:-O8i7a8m9uez-SUHMNAX:bwjpf9b) ([raw file](https://github.com/batfish/batfish/blob/075caa34f3035e85d498bafab945921b5c96ffee/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_routing_instances.g4#L674)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

you may want ipv6_prefix_default_128 like we have `ip_prefix_default_32`. It's basically prefix or address both allowed, and if address we make it a /128.
</blockquote></details>

I was wondering about that - done.
___
*[`projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4` line 2388 at r1](https://reviewable.io/reviews/batfish/batfish/9241#-O8giGWGAH0DbaFsoU4z:-O8i7z_44BDQrYMxe3uT:b-y975ot) ([raw file](https://github.com/batfish/batfish/blob/075caa34f3035e85d498bafab945921b5c96ffee/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4#L2388)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

yeah let's chat about this one. Probably totally reasonable, not sure.
</blockquote></details>

As discussed, changed the lexer so the name is a single token.
___
*[`projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4` line 3629 at r1](https://reviewable.io/reviews/batfish/batfish/9241#-O8giLcK6cD-6NcU1VQd:-O8i8BnH92nmT_-YukKd:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/075caa34f3035e85d498bafab945921b5c96ffee/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4#L3629)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

maybe add a link?
</blockquote></details>

done
___
*[`projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java` line 6504 at r1](https://reviewable.io/reviews/batfish/batfish/9241#-O8gitg_13Qz4E6Ud_r8:-O8iAgsTBY1zFfIulfnJ:b-lbloxa) ([raw file](https://github.com/batfish/batfish/blob/075caa34f3035e85d498bafab945921b5c96ffee/projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java#L6504)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

since the variable names are different we don't need the scoping `{}`. That's needed only if you want to prevent leaks out of context.

I might say:

```
assertThat(c.getMasterLogicalSystem().getRoutingInstances().get("default").getRibs().get(...).getStaticRoutes(),
    isEmpty())
``` or something like that.

The use of `isEmpty()` is nice because it will not just present failure, it will say "expected empty, but got [...]"
```

</blockquote></details>

I couldn't find a matcher for an empty map, but there is one for an empty collection, so I went with making sure the keySet was empty. 

Also I know it's weird to factor out the routesDefault/routesTestVrf vars but I'll be adding more tests for each of them once extraction is implemented.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/9241)* status: all files reviewed, 1 unresolved discussion (waiting on @SLarkworthy)

___
*[`projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4` line 4972 at r2](https://reviewable.io/reviews/batfish/batfish/9241#-O8iHMwz2l038c_ZlzmR:-O8iHMx-7rI86AjqaWLI:b-k3q389) ([raw file](https://github.com/batfish/batfish/blob/c7d75439bd5c213f6c8f7ba25bb4c027cff7f60d/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4#L4972)):*
> ```ANTLR
> M_RibName_INET: (F_RoutingInstanceNameChar+ PERIOD)? INET PERIOD UINT8 -> type(INET_RIB_NAME), popMode;
> M_RibName_INET6: (F_RoutingInstanceNameChar+ PERIOD)? INET6 PERIOD UINT8 -> type(INET6_RIB_NAME), popMode;
> M_RibName_MPLS: MPLS PERIOD UINT8 -> type(MPLS_RIB_NAME), popMode;
> ```

why omit VRF names here? I assume they're still relevant.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/9241)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SLarkworthy)

**Pull request merged**
