### PR TITLE
AWS: fix routes for ngw in subnets

### PR DESCRIPTION
**Pull request by ratulm**

### CODE REVIEW

**Comment by dhalperi** [comment]
___
*[projects/batfish/src/main/java/org/batfish/representation/aws/Subnet.java, line 650 at r1](https://reviewable.io/reviews/batfish/batfish/6263#-MIXcvxSD_xZcaWykQWR:-MIXcvxT43XVGpJQyYj9:b-o5zmvj) ([raw file](https://github.com/batfish/batfish/blob/c48ec374d979a49a48d485a7911d046df7f493d3/projects/batfish/src/main/java/org/batfish/representation/aws/Subnet.java#L650)):*
> ```Java
>             // instead of ignoring it because it is the correct model and users expect routes in AWS
>             // and Batfish to line up.
>             nexthopInterfaceName = instancesInterfaceName(_subnetId);
> ```

Hmm. IIUC we usually send packets between two nodes communicating in the same subnet p2p -- e.g., instances send directly to each other instead of through subnet node, right? Didn't we run into problems with filtering otherwise?

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6263)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @dhalperi, @progwriter, and @ratulm)

___
*[projects/batfish/src/main/java/org/batfish/representation/aws/Subnet.java, line 643 at r1](https://reviewable.io/reviews/batfish/batfish/6263#-MIXdMrf7wsXGjyzOP14:-MIXdMrf7wsXGjyzOP15:b-qq7lg7) ([raw file](https://github.com/batfish/batfish/blob/c48ec374d979a49a48d485a7911d046df7f493d3/projects/batfish/src/main/java/org/batfish/representation/aws/Subnet.java#L643)):*
> ```
> send it directly.
> ```
update comment?

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6263)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dhalperi, @progwriter, and @ratulm)

___
*[projects/batfish/src/main/java/org/batfish/representation/aws/Subnet.java, line 650 at r1](https://reviewable.io/reviews/batfish/batfish/6263#-MIXcvxSD_xZcaWykQWR:-MIXdWINAq5jGtJ6sjVo:b8g94gm) ([raw file](https://github.com/batfish/batfish/blob/c48ec374d979a49a48d485a7911d046df7f493d3/projects/batfish/src/main/java/org/batfish/representation/aws/Subnet.java#L650)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Hmm. IIUC we usually send packets between two nodes communicating in the same subnet p2p -- e.g., instances send directly to each other instead of through subnet node, right? Didn't we run into problems with filtering otherwise?
</blockquote></details>

nm, I misunderstood the context. What was happening before? Did that next hop interface not exist?

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6263)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dhalperi and @progwriter)

___
*[projects/batfish/src/main/java/org/batfish/representation/aws/Subnet.java, line 650 at r1](https://reviewable.io/reviews/batfish/batfish/6263#-MIXcvxSD_xZcaWykQWR:-MIXeggQDMWkC-PjR71y:b-v7yo90) ([raw file](https://github.com/batfish/batfish/blob/c48ec374d979a49a48d485a7911d046df7f493d3/projects/batfish/src/main/java/org/batfish/representation/aws/Subnet.java#L650)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

nm, I misunderstood the context. What was happening before? Did that next hop interface not exist?
</blockquote></details>

yeah, the wrong interface name was being used, so the route was not getting wiped out.

**Review by dhalperi — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6263#-:-MIXfBknECo-qoBRHfSg:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @progwriter)

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6263)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @progwriter)

___
*[projects/batfish/src/main/java/org/batfish/representation/aws/Subnet.java, line 650 at r1](https://reviewable.io/reviews/batfish/batfish/6263#-MIXcvxSD_xZcaWykQWR:-MIXf8sG5wiBjesaVs6e:b-q2tdvx) ([raw file](https://github.com/batfish/batfish/blob/c48ec374d979a49a48d485a7911d046df7f493d3/projects/batfish/src/main/java/org/batfish/representation/aws/Subnet.java#L650)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

yeah, the wrong interface name was being used, so the route was not getting wiped out. 
</blockquote></details>

was getting wiped out

**Pull request merged**
