### PR TITLE
Checkpoint vs management containers

### PR DESCRIPTION
**Pull request by arifogel**
- ManagementPackage containing all data for a package
- update ManagementDomain to contain `ManagementPackage`s instead of
  `Package`s

### CODE REVIEW

**Review by corinaminer — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7256)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/ManagementPackage.java, line 9 at r1](https://reviewable.io/reviews/batfish/batfish/7256#-Mh_91so3Y4W0uo2yz0i:-Mh_91so3Y4W0uo2yz0j:b885khg) ([raw file](https://github.com/batfish/batfish/blob/5a983b29f084117271035062eff203e4d26e405f/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/ManagementPackage.java#L9)):*
> ```Java
> public final class ManagementPackage extends NamedManagementObject {
> 
>   public ManagementPackage(@Nullable NatRulebase natRulebase, Package pakij) {
> ```

doesn't this need to keep `pakij` in a `_pakij` field? (how will we now find installation targets for a package?)

**Review by corinaminer — COMMENTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7256)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel)

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7256)* status: all files reviewed, 1 unresolved discussion (waiting on @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/ManagementPackage.java, line 9 at r1](https://reviewable.io/reviews/batfish/batfish/7256#-Mh_91so3Y4W0uo2yz0i:-Mh_B8-I91ESjRveIkGS:byfvwb8) ([raw file](https://github.com/batfish/batfish/blob/5a983b29f084117271035062eff203e4d26e405f/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/ManagementPackage.java#L9)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

doesn't this need to keep `pakij` in a `_pakij` field? (how will we now find installation targets for a package?)
</blockquote></details>

ah whoops. fixed.

**Review by corinaminer — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7256)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Pull request merged**
