### PR TITLE
CP: automatic hide NAT rules

### PR DESCRIPTION
**Pull request by corinaminer**
Uses `NatSettings` to add automatic hide NAT rules to the existing NAT transformation in conversion.

### CODE REVIEW

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7393)* status: 0 of 20 files reviewed, 2 unresolved discussions (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversions.java, line 247 at r1](https://reviewable.io/reviews/batfish/batfish/7393#-MjhCZjHBp0O7SEifZw_:-MjhCZjIBlgCzGcyX3B8:b-tx6n48) ([raw file](https://github.com/batfish/batfish/blob/6c7f53a48972123fd1d0cd178aebf6f935099ee0/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversions.java#L247)):*
> ```
> NAT settings on %s %s are invalid: type is HIDE, but hide-behind is missing
> ```
nit: call out that the rule is ignored
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversions.java, line 252 at r1](https://reviewable.io/reviews/batfish/batfish/7393#-MjhD_hODyiw67nmks6t:-MjhD_hP1t9sr0eS-ZIf:b9jxzfi) ([raw file](https://github.com/batfish/batfish/blob/6c7f53a48972123fd1d0cd178aebf6f935099ee0/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversions.java#L252)):*
> ```
>       // TODO What does it mean if install-on is missing?
> ```
fyi: there's probably another invariant we can assert when constructing natSettings, like if `auto-rule` is `true`, then `install-on` needs to exist

might also be true for the case above, where `hide-behind` should always exist for `hide` type rules
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversions.java, line 262 at r1](https://reviewable.io/reviews/batfish/batfish/7393#-MjhCfUfCzmWosVxhYik:-MjhCfUfCzmWosVxhYil:b-gi88fj) ([raw file](https://github.com/batfish/batfish/blob/6c7f53a48972123fd1d0cd178aebf6f935099ee0/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversions.java#L262)):*
<details><summary><i alt="summary">Quoted 16 lines of code…</i></summary>

> ```
>     IpSpace originalIpSpace =
>         new HasNatSettingsVisitor<IpSpace>() {
>           @Override
>           public IpSpace visitAddressRange(AddressRange addressRange) {
>             return addressRange.accept(toIpSpaceVisitor);
>           }
>           @Override
>           public IpSpace visitHost(Host host) {
>             return host.accept(toIpSpaceVisitor);
>           }
>           @Override
>           public IpSpace visitNetwork(Network network) {
>             return network.accept(toIpSpaceVisitor);
>           }
>         }.visit(hasNatSettings);
>     AclLineMatchExpr matchOriginalSrc = matchSrc(originalIpSpace);
> ```
</details>

seems like we should not create more IP spaces for these objects (since we know all HasNatSettings will also be AddressSpaces, and we already have named IP spaces for these objects)

Also, can just use something like `AddrSpaceToMatchExpr` to directly build the Match Exprs
___
*[projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversionsTest.java, line 446 at r1](https://reviewable.io/reviews/batfish/batfish/7393#-MjhFCSu2nsIIPNUTQe0:-MjhFCSu2nsIIPNUTQe1:b-ms40rd) ([raw file](https://github.com/batfish/batfish/blob/6c7f53a48972123fd1d0cd178aebf6f935099ee0/projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversionsTest.java#L446)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>       // Manual and automatic both empty
> ...
>       // One manual transformation
> ...
>       // Two manual transformations
> ...
> ```
</details>

I don't think we're going to want to maintain this pattern when we have four different types of rules to merge, probably best to pare this down a bit

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7393)* status: 0 of 20 files reviewed, 1 unresolved discussion (waiting on @arifogel and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversions.java, line 247 at r1](https://reviewable.io/reviews/batfish/batfish/7393#-MjhCZjHBp0O7SEifZw_:-Mjja8h73AvodXrq9reZ:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/6c7f53a48972123fd1d0cd178aebf6f935099ee0/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversions.java#L247)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
> NAT settings on %s %s are invalid: type is HIDE, but hide-behind is missing
> ```
nit: call out that the rule is ignored
</blockquote></details>

done
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversions.java, line 252 at r1](https://reviewable.io/reviews/batfish/batfish/7393#-MjhD_hODyiw67nmks6t:-MjjaBZ27KXu0MyXlk_u:b2bry0z) ([raw file](https://github.com/batfish/batfish/blob/6c7f53a48972123fd1d0cd178aebf6f935099ee0/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversions.java#L252)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
>       // TODO What does it mean if install-on is missing?
> ```
fyi: there's probably another invariant we can assert when constructing natSettings, like if `auto-rule` is `true`, then `install-on` needs to exist

might also be true for the case above, where `hide-behind` should always exist for `hide` type rules
</blockquote></details>

given that management data isn't (usually) touched by human hands, i think it makes sense to have a "soft" assumption that everything is valid, and only actually confirm validity when conversion code depends on it. Also, if we put validity checks in VS constructors, those VS classes would need access to warnings
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversions.java, line 262 at r1](https://reviewable.io/reviews/batfish/batfish/7393#-MjhCfUfCzmWosVxhYik:-MjjbknA3izjWsqbEek8:b-8kczqu) ([raw file](https://github.com/batfish/batfish/blob/6c7f53a48972123fd1d0cd178aebf6f935099ee0/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversions.java#L262)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
>     IpSpace originalIpSpace =
>         new HasNatSettingsVisitor<IpSpace>() {
>           @Override
>           public IpSpace visitAddressRange(AddressRange addressRange) {
>             return addressRange.accept(toIpSpaceVisitor);
>           }
>           @Override
>           public IpSpace visitHost(Host host) {
>             return host.accept(toIpSpaceVisitor);
>           }
>           @Override
>           public IpSpace visitNetwork(Network network) {
>             return network.accept(toIpSpaceVisitor);
>           }
>         }.visit(hasNatSettings);
>     AclLineMatchExpr matchOriginalSrc = matchSrc(originalIpSpace);
> ```
seems like we should not create more IP spaces for these objects (since we know all HasNatSettings will also be AddressSpaces, and we already have named IP spaces for these objects)

Also, can just use something like `AddrSpaceToMatchExpr` to directly build the Match Exprs
</blockquote></details>

Done: made `HasNatSettings` extend `AddressSpace`, and used `AddrSpaceToMatchExpr`. Deleted `HasNatSettingsVisitor` as it was no longer used.
___
*[projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversionsTest.java, line 446 at r1](https://reviewable.io/reviews/batfish/batfish/7393#-MjhFCSu2nsIIPNUTQe0:-MjjZTPC6iM-RB9CSLCJ:b-fnlplu) ([raw file](https://github.com/batfish/batfish/blob/6c7f53a48972123fd1d0cd178aebf6f935099ee0/projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversionsTest.java#L446)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
>       // Manual and automatic both empty
> ...
>       // One manual transformation
> ...
>       // Two manual transformations
> ...
> ```
I don't think we're going to want to maintain this pattern when we have four different types of rules to merge, probably best to pare this down a bit
</blockquote></details>

I think what's really going to happen is that we'll be forced to refactor in order to apply different transformations at different interfaces. That'll probably be as soon as we support any static NAT.

Considering that that's coming up soon, is there any particular refactoring of this function you want to see in this PR? Not sure what you mean by pare it down

**Review by sfraint — COMMENTED** [review]
> Reviewed 12 of 20 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7393)* status: all files reviewed, 4 unresolved discussions (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java, line 323 at r2](https://reviewable.io/reviews/batfish/batfish/7393#-MjkAntyAranUG60mKZd:-MjkAntyAranUG60mKZe:b-rsy5md) ([raw file](https://github.com/batfish/batfish/blob/67df577602d176e854369327fa92e4f3319bb5d4/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java#L323)):*
> ```
>     AddressSpaceToMatchExpr toMatchExprVisitor = new AddressSpaceToMatchExpr(objects);
> ```
one of these already exists in this context, a few lines above: `addressSpaceToMatchExpr`
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java, line 326 at r2](https://reviewable.io/reviews/batfish/batfish/7393#-MjkAyNx90U01sDbiTI7:-MjkAyNx90U01sDbiTI8:bw7k0la) ([raw file](https://github.com/batfish/batfish/blob/67df577602d176e854369327fa92e4f3319bb5d4/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java#L326)):*
> ```
> o -> o instanceof HasNatSettings
> ```
nit: I think you can just do something like `HasNatSettings.class::instanceof` (not that that is any shorter or really any clearer...)
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java, line 333 at r2](https://reviewable.io/reviews/batfish/batfish/7393#-MjkBBya1TWpATrvaqVF:-MjkBBya1TWpATrvaqVG:b-4tombe) ([raw file](https://github.com/batfish/batfish/blob/67df577602d176e854369327fa92e4f3319bb5d4/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java#L333)):*
> ```
> // TODO: What is the correct order in which to apply automatic hide rules?
> ```
could be slightly more concrete here - and say something like `TODO consult generated rules for automatic hide rule ordering`
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversions.java, line 262 at r1](https://reviewable.io/reviews/batfish/batfish/7393#-MjhCfUfCzmWosVxhYik:-MjkBgXb-ssoHXWm_gd9:b4c9lyr) ([raw file](https://github.com/batfish/batfish/blob/6c7f53a48972123fd1d0cd178aebf6f935099ee0/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversions.java#L262)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Done: made `HasNatSettings` extend `AddressSpace`, and used `AddrSpaceToMatchExpr`. Deleted `HasNatSettingsVisitor` as it was no longer used.
</blockquote></details>

:thumbsup: 
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/NatHideBehind.java, line 18 at r2](https://reviewable.io/reviews/batfish/batfish/7393#-MjkEjM4AvRLrUyL0ZVK:-MjkEjM4AvRLrUyL0ZVL:btfom4s) ([raw file](https://github.com/batfish/batfish/blob/67df577602d176e854369327fa92e4f3319bb5d4/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/NatHideBehind.java#L18)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>     if (jsonText.equals(NAME_GATEWAY)) {
>       return NatHideBehindGateway.INSTANCE;
>     }
>     return new NatHideBehindIp(Ip.parse(jsonText));
> ```
</details>

if we get some other `jsonText` (not an IP or `gateway`), will this crash during parsing? we should probably be more graceful here
___
*[projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversionsTest.java, line 446 at r1](https://reviewable.io/reviews/batfish/batfish/7393#-MjhFCSu2nsIIPNUTQe0:-MjjjwiDEPz8TvOJYoyV:b-r3axbz) ([raw file](https://github.com/batfish/batfish/blob/6c7f53a48972123fd1d0cd178aebf6f935099ee0/projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversionsTest.java#L446)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

I think what's really going to happen is that we'll be forced to refactor in order to apply different transformations at different interfaces. That'll probably be as soon as we support any static NAT.

Considering that that's coming up soon, is there any particular refactoring of this function you want to see in this PR? Not sure what you mean by pare it down
</blockquote></details>

this is fine for now and feel free to defer, I just meant this pattern isn't sustainable to do the cross product when we add more lists of rules

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7393)* status: 15 of 21 files reviewed, all discussions resolved (waiting on @arifogel and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java, line 323 at r2](https://reviewable.io/reviews/batfish/batfish/7393#-MjkAntyAranUG60mKZd:-MjkHOVp3SJH3teowzgh:bkd386u) ([raw file](https://github.com/batfish/batfish/blob/67df577602d176e854369327fa92e4f3319bb5d4/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java#L323)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
>     AddressSpaceToMatchExpr toMatchExprVisitor = new AddressSpaceToMatchExpr(objects);
> ```
one of these already exists in this context, a few lines above: `addressSpaceToMatchExpr`
</blockquote></details>

oh so it does. fixed
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java, line 326 at r2](https://reviewable.io/reviews/batfish/batfish/7393#-MjkAyNx90U01sDbiTI7:-MjkHY3m0-SiXZFzIN_p:b-fizo04) ([raw file](https://github.com/batfish/batfish/blob/67df577602d176e854369327fa92e4f3319bb5d4/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java#L326)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
> o -> o instanceof HasNatSettings
> ```
nit: I think you can just do something like `HasNatSettings.class::instanceof` (not that that is any shorter or really any clearer...)
</blockquote></details>

done anyway
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java, line 333 at r2](https://reviewable.io/reviews/batfish/batfish/7393#-MjkBBya1TWpATrvaqVF:-MjkHvIT5JjJ-GscSnZq:bmgri5k) ([raw file](https://github.com/batfish/batfish/blob/67df577602d176e854369327fa92e4f3319bb5d4/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java#L333)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
> // TODO: What is the correct order in which to apply automatic hide rules?
> ```
could be slightly more concrete here - and say something like `TODO consult generated rules for automatic hide rule ordering`
</blockquote></details>

done. Fyi i wasn't sure how to identify an auto hide NAT rule as corresponding to a specific object's NatSettings, which is why i didn't already implement ordering
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/NatHideBehind.java, line 18 at r2](https://reviewable.io/reviews/batfish/batfish/7393#-MjkEjM4AvRLrUyL0ZVK:-MjkKlvWCGZSJt42A3PB:b-zhhz1b) ([raw file](https://github.com/batfish/batfish/blob/67df577602d176e854369327fa92e4f3319bb5d4/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/NatHideBehind.java#L18)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
>     if (jsonText.equals(NAME_GATEWAY)) {
>       return NatHideBehindGateway.INSTANCE;
>     }
>     return new NatHideBehindIp(Ip.parse(jsonText));
> ```
if we get some other `jsonText` (not an IP or `gateway`), will this crash during parsing? we should probably be more graceful here
</blockquote></details>

done, added `UnhandledNatHideBehind`
___
*[projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversionsTest.java, line 446 at r1](https://reviewable.io/reviews/batfish/batfish/7393#-MjhFCSu2nsIIPNUTQe0:-MjkKq-a-RsLvEK6WFRS:b-ougns5) ([raw file](https://github.com/batfish/batfish/blob/6c7f53a48972123fd1d0cd178aebf6f935099ee0/projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversionsTest.java#L446)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

this is fine for now and feel free to defer, I just meant this pattern isn't sustainable to do the cross product when we add more lists of rules
</blockquote></details>

yeah i agree (but deferring)

**Review by sfraint — COMMENTED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7393)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java, line 333 at r2](https://reviewable.io/reviews/batfish/batfish/7393#-MjkBBya1TWpATrvaqVF:-MjkQmLm157uglwqmI5y:b8ffbvl) ([raw file](https://github.com/batfish/batfish/blob/67df577602d176e854369327fa92e4f3319bb5d4/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java#L333)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

done. Fyi i wasn't sure how to identify an auto hide NAT rule as corresponding to a specific object's NatSettings, which is why i didn't already implement ordering
</blockquote></details>

ack - I was thinking you can just compare uid of the obj versus uid of original address in the rule, but we can figure those details out in another pass

**Pull request merged**
