### PR TITLE
New reachability question using specifiers

### PR DESCRIPTION
**Pull request by anothermattbrown**

### CODE REVIEW

**Comment by anothermattbrown** [comment]
Review status: 0 of 11 files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1624#-LEVGK3MAwt23pwkEJKW:-LEVGK3N6DH1YAM7q0H6:b-xdrbha) (no related file):*
Working to get base merged into master

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1624)*

**Comment by dhalperi** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed, 6 unresolved discussions (waiting on @anothermattbrown)

---

*[projects/question/src/main/java/org/batfish/question/specifiers/SpecifiersReachabilityQuestion.java, line 70 at r1](https://reviewable.io/reviews/batfish/batfish/1624#-LEjvYW2EcXcnoFvJmVa:-LEjvYW2EcXcnoFvJmVb:b-x8yuon) ([raw file](https://github.com/batfish/batfish/blob/1f034c275a845591951d720b109d684a42e174e2/projects/question/src/main/java/org/batfish/question/specifiers/SpecifiersReachabilityQuestion.java#L70)):*
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>

> ```
>   private static NodeSpecifier getNodeSpecifier(String factory, String input) {
>     if (factory == null && input == null) {
>       return NoNodesNodeSpecifier.INSTANCE;
>     }
>     if (factory == null) {
>       return new NameRegexNodeSpecifierFactory().buildNodeSpecifier(input);
>     }
>     return NodeSpecifierFactory.load(factory).buildNodeSpecifier(input);
>   }
> ```
</details>


Suggested improvements:

* Add `@Nullable` to arguments, add `@ParametersAreNonNullByDefault` to `package-info.java` to set defaults for the whole java package.

Rename function to indicate it's not for generic specifiers, but only for transit specifiers.

---

*[projects/question/src/main/java/org/batfish/question/specifiers/SpecifiersReachabilityQuestion.java, line 120 at r1](https://reviewable.io/reviews/batfish/batfish/1624#-LEjwfqqCO6HFOwdBlL5:-LEjwfqqCO6HFOwdBlL6:b-rin5vy) ([raw file](https://github.com/batfish/batfish/blob/1f034c275a845591951d720b109d684a42e174e2/projects/question/src/main/java/org/batfish/question/specifiers/SpecifiersReachabilityQuestion.java#L120)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
>   @JsonProperty(PROP_FINAL_NODES_SPECIFIER_FACTORY)
>   public String getFinalNodesSpecifierFactory() {
>     return _finalNodesNodeSpecifierFactory;
>   }
>  
>   @JsonProperty(PROP_FINAL_NODES_SPECIFIER_INPUT)
>   public String getFinalNodesSpecifierInput() {
>     return _finalNodesNodeSpecifierInput;
> ```
</details>


Why is this two properties, not 1? Seems error prone.

(If the answer is this is a toy/demo question we don't expect users to use, that's a fine answer.)

---

*[projects/question/src/main/java/org/batfish/question/specifiers/SpecifiersReachabilityQuestion.java, line 171 at r1](https://reviewable.io/reviews/batfish/batfish/1624#-LEjxHIB-U7h5Q1UqyaQ:-LEjxHIB-U7h5Q1UqyaR:b-p0m4qs) ([raw file](https://github.com/batfish/batfish/blob/1f034c275a845591951d720b109d684a42e174e2/projects/question/src/main/java/org/batfish/question/specifiers/SpecifiersReachabilityQuestion.java#L171)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>     if (_sourceIpSpaceSpecifierFactory == null) {
>       return new ConstantWildcardSetIpSpaceSpecifierFactory()
>           .buildIpSpaceSpecifier(_sourceIpSpaceSpecifierInput);
>     }
>     return IpSpaceSpecifierFactory.load(_sourceIpSpaceSpecifierFactory)
>         .buildIpSpaceSpecifier(_sourceIpSpaceSpecifierInput);
> ```
</details>


I might find this easier to read if we did:

```
Factory f = (factory == null) ? Const : load(factory);
return f.build(input);
```

---

*[projects/question/src/main/java/org/batfish/question/specifiers/SpecifiersReachabilityQuestion.java, line 218 at r1](https://reviewable.io/reviews/batfish/batfish/1624#-LEjyaMY92YNUNmTxudB:-LEjyaMY92YNUNmTxudC:b-1qrmjp) ([raw file](https://github.com/batfish/batfish/blob/1f034c275a845591951d720b109d684a42e174e2/projects/question/src/main/java/org/batfish/question/specifiers/SpecifiersReachabilityQuestion.java#L218)):*
> ```Java
> 
>   @JsonProperty(PROP_ACTIONS)
>   public void setActions(SortedSet<ForwardingAction> actionSet) {
> ```

accept `Iterable` or something easier to produce than `SortedSet`?

---

*[projects/question/src/test/java/org/batfish/question/specifiers/SpecifiersReachabilityQuestionTest.java, line 60 at r1](https://reviewable.io/reviews/batfish/batfish/1624#-LEkGm00CpWgcXBKck9p:-LEkGm00CpWgcXBKck9q:beov1dp) ([raw file](https://github.com/batfish/batfish/blob/1f034c275a845591951d720b109d684a42e174e2/projects/question/src/test/java/org/batfish/question/specifiers/SpecifiersReachabilityQuestionTest.java#L60)):*
> ```
>     exception.expect(BatfishException.class);
>     exception.expectMessage("Could not find NodeSpecifierFactory with name foo");
> ```

Move this exactly before the sole line that is expected to throw the exception. Makes the test more readable, protects against unexpected behavior.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1624)*

**Comment by anothermattbrown** [comment]
Review status: 9 of 15 files reviewed, 2 unresolved discussions (waiting on @dhalperi and @anothermattbrown)

---

*[projects/question/src/main/java/org/batfish/question/specifiers/SpecifiersReachabilityQuestion.java, line 70 at r1](https://reviewable.io/reviews/batfish/batfish/1624#-LEjvYW2EcXcnoFvJmVa:-LEkVsBv9ZzbyymOZj7h:bb8r8n1) ([raw file](https://github.com/batfish/batfish/blob/1f034c275a845591951d720b109d684a42e174e2/projects/question/src/main/java/org/batfish/question/specifiers/SpecifiersReachabilityQuestion.java#L70)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
>   private static NodeSpecifier getNodeSpecifier(String factory, String input) {
>     if (factory == null && input == null) {
>       return NoNodesNodeSpecifier.INSTANCE;
>     }
>     if (factory == null) {
>       return new NameRegexNodeSpecifierFactory().buildNodeSpecifier(input);
>     }
>     return NodeSpecifierFactory.load(factory).buildNodeSpecifier(input);
>   }
> ```

Suggested improvements:

* Add `@Nullable` to arguments, add `@ParametersAreNonNullByDefault` to `package-info.java` to set defaults for the whole java package.

Rename function to indicate it's not for generic specifiers, but only for transit specifiers.
</blockquote></details>

Done. Instead of your last suggestion, added a default NodeSpecifier argument and used it in more places.

---

*[projects/question/src/main/java/org/batfish/question/specifiers/SpecifiersReachabilityQuestion.java, line 120 at r1](https://reviewable.io/reviews/batfish/batfish/1624#-LEjwfqqCO6HFOwdBlL5:-LEkQP0_80uVuOKt0K5K:b-us0oby) ([raw file](https://github.com/batfish/batfish/blob/1f034c275a845591951d720b109d684a42e174e2/projects/question/src/main/java/org/batfish/question/specifiers/SpecifiersReachabilityQuestion.java#L120)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
>   @JsonProperty(PROP_FINAL_NODES_SPECIFIER_FACTORY)
>   public String getFinalNodesSpecifierFactory() {
>     return _finalNodesNodeSpecifierFactory;
>   }
>  
>   @JsonProperty(PROP_FINAL_NODES_SPECIFIER_INPUT)
>   public String getFinalNodesSpecifierInput() {
>     return _finalNodesNodeSpecifierInput;
> ```

Why is this two properties, not 1? Seems error prone.

(If the answer is this is a toy/demo question we don't expect users to use, that's a fine answer.)
</blockquote></details>

My thought was more along the lines that this is a pre-release version of the question, and we'll iterate on the front-end. This is the simplest starting point I could think of.

---

*[projects/question/src/main/java/org/batfish/question/specifiers/SpecifiersReachabilityQuestion.java, line 171 at r1](https://reviewable.io/reviews/batfish/batfish/1624#-LEjxHIB-U7h5Q1UqyaQ:-LEkVRxBE6QI9l83x1Ew:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/1f034c275a845591951d720b109d684a42e174e2/projects/question/src/main/java/org/batfish/question/specifiers/SpecifiersReachabilityQuestion.java#L171)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
>     if (_sourceIpSpaceSpecifierFactory == null) {
>       return new ConstantWildcardSetIpSpaceSpecifierFactory()
>           .buildIpSpaceSpecifier(_sourceIpSpaceSpecifierInput);
>     }
>     return IpSpaceSpecifierFactory.load(_sourceIpSpaceSpecifierFactory)
>         .buildIpSpaceSpecifier(_sourceIpSpaceSpecifierInput);
> ```

I might find this easier to read if we did:

```
Factory f = (factory == null) ? Const : load(factory);
return f.build(input);
```
</blockquote></details>

Done.

---

*[projects/question/src/main/java/org/batfish/question/specifiers/SpecifiersReachabilityQuestion.java, line 218 at r1](https://reviewable.io/reviews/batfish/batfish/1624#-LEjyaMY92YNUNmTxudB:-LEkVSQ75O_A2BpT1-CI:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/1f034c275a845591951d720b109d684a42e174e2/projects/question/src/main/java/org/batfish/question/specifiers/SpecifiersReachabilityQuestion.java#L218)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

accept `Iterable` or something easier to produce than `SortedSet`?
</blockquote></details>

Done.

---

*[projects/question/src/test/java/org/batfish/question/specifiers/SpecifiersReachabilityQuestionTest.java, line 60 at r1](https://reviewable.io/reviews/batfish/batfish/1624#-LEkGm00CpWgcXBKck9p:-LEkViV02jFGjpYO0eAN:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/1f034c275a845591951d720b109d684a42e174e2/projects/question/src/test/java/org/batfish/question/specifiers/SpecifiersReachabilityQuestionTest.java#L60)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
>     exception.expect(BatfishException.class);
>     exception.expectMessage("Could not find NodeSpecifierFactory with name foo");
> ```

Move this exactly before the sole line that is expected to throw the exception. Makes the test more readable, protects against unexpected behavior.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1624)*

**Comment by dhalperi** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed, 1 unresolved discussion (waiting on @anothermattbrown)

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1624)*

**Comment by anothermattbrown** [comment]
Review status: 9 of 11 files reviewed, all discussions resolved (waiting on @dhalperi)

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1624#-LEVGK3MAwt23pwkEJKW:-LElWCXZ3ldb3xHCfMRF:b-896fix) (no related file):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

Working to get base merged into master
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1624)*

**Comment by dhalperi** [comment]
Review status: 9 of 11 files reviewed, 2 unresolved discussions (waiting on @dhalperi and @anothermattbrown)

---

*[projects/question/src/main/java/org/batfish/question/specifiers/SpecifiersReachabilityQuestion.java, line 65 at r2](https://reviewable.io/reviews/batfish/batfish/1624#-LElbzbR44ZEAdTMr_-6:-LElbzbR44ZEAdTMr_-7:b-1bdvyf) ([raw file](https://github.com/batfish/batfish/blob/b771b33a0160e250136a081a561776db061dd382/projects/question/src/main/java/org/batfish/question/specifiers/SpecifiersReachabilityQuestion.java#L65)):*
> ```Java
> 
>   private static LocationSpecifier getLocationSpecifier(
>       @Nullable String factoryName, @Nullable String input, @Nonnull LocationSpecifier def) {
> ```

regression?

---

*[projects/question/src/test/java/org/batfish/question/specifiers/SpecifiersReachabilityQuestionTest.java, line 59 at r3](https://reviewable.io/reviews/batfish/batfish/1624#-LElc-ez0u3ibGjRk8uo:-LElc-ez0u3ibGjRk8up:b-1bdvyf) ([raw file](https://github.com/batfish/batfish/blob/0dbb7ea3b80feb92cf3d15afdfee2279092a3ad0/projects/question/src/test/java/org/batfish/question/specifiers/SpecifiersReachabilityQuestionTest.java#L59)):*
> ```Java
>   @Test
>   public void getFinalNodes_factoryNonNull_exception() {
>     exception.expect(BatfishException.class);
> ```

regression?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1624)*

**Comment by anothermattbrown** [comment]
Review status: 9 of 11 files reviewed, all discussions resolved (waiting on @dhalperi)

---

*[projects/question/src/main/java/org/batfish/question/specifiers/SpecifiersReachabilityQuestion.java, line 65 at r2](https://reviewable.io/reviews/batfish/batfish/1624#-LElbzbR44ZEAdTMr_-6:-LEomxmPDnKq7X_k6ZXJ:bc25idm) ([raw file](https://github.com/batfish/batfish/blob/b771b33a0160e250136a081a561776db061dd382/projects/question/src/main/java/org/batfish/question/specifiers/SpecifiersReachabilityQuestion.java#L65)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

regression?
</blockquote></details>

Done. bad merge.

---

*[projects/question/src/test/java/org/batfish/question/specifiers/SpecifiersReachabilityQuestionTest.java, line 59 at r3](https://reviewable.io/reviews/batfish/batfish/1624#-LElc-ez0u3ibGjRk8uo:-LEonO4t1_G8YYPMOthk:bb6un1j) ([raw file](https://github.com/batfish/batfish/blob/0dbb7ea3b80feb92cf3d15afdfee2279092a3ad0/projects/question/src/test/java/org/batfish/question/specifiers/SpecifiersReachabilityQuestionTest.java#L59)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

regression?
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1624)*

**Comment by anothermattbrown** [comment]
Reviewed 8 of 11 files at r1, 3 of 3 files at r4.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1624)*

**Pull request merged**
