### PR TITLE
Junos: parse `input-vlan-map` and `output-vlan-map`

### PR DESCRIPTION
**Pull request by zergling-aws**

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8885)* status: all files reviewed, 2 unresolved discussions (waiting on @zergling-aws)

___
*[`projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_interfaces.g4` line 220 at r1](https://reviewable.io/reviews/batfish/batfish/8885#-NlxnzA11cBDIxKr0UDA:-NlxnzA11cBDIxKr0UDB:b-yoi1gk) ([raw file](https://github.com/batfish/batfish/blob/8f6a9016fe4ee2e6c6ac19bdeb02fe2df62dc265/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_interfaces.g4#L220)):*
> ```ANTLR
> i_input_vlan_map
> :
>    INPUT_VLAN_MAP PUSH
> ```

Given the simplicity of this grammar, can you please add all the options: https://www.juniper.net/documentation/us/en/software/junos/multicast-l2/topics/ref/statement/output-vlan-map-edit-interfaces-ge.html

```
i_input_vlan_map: INPUT_VLAN_MAP action = (PUSH | ...);
```

Can do this for both input and output.
___
*[`projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_interfaces.g4` line 290 at r1](https://reviewable.io/reviews/batfish/batfish/8885#-NlxoEBJ9ReLKC2Rwpq2:-NlxoEBJ9ReLKC2Rwpq3:b-xp08oc) ([raw file](https://github.com/batfish/batfish/blob/8f6a9016fe4ee2e6c6ac19bdeb02fe2df62dc265/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_interfaces.g4#L290)):*
> ```ANTLR
> ;
> 
> i_unit
> ```

FYI confirmed these are only valid under units. Nice work.
___
*[`projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_interfaces.g4` line 300 at r1](https://reviewable.io/reviews/batfish/batfish/8885#-NlxngGQD9ZxdsLelIRf:-NlxngGR4xwYc7RHk3Cn:bqq64ge) ([raw file](https://github.com/batfish/batfish/blob/8f6a9016fe4ee2e6c6ac19bdeb02fe2df62dc265/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_interfaces.g4#L300)):*
> ```ANTLR
>       i_common
>       | i_bandwidth
>       | i_input_vlan_map
> ```

please warn on both of these, they related to L2/L3 inference that we don't yet support.

(FYI no need to add a test that the warning is present, codecov will show us it got hit.)

**Review by zergling-aws — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8885)* status: 3 of 5 files reviewed, all discussions resolved (waiting on @dhalperi)

___
*[`projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_interfaces.g4` line 220 at r1](https://reviewable.io/reviews/batfish/batfish/8885#-NlxnzA11cBDIxKr0UDA:-NlxtduV7LTMz90eJUx1:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/8f6a9016fe4ee2e6c6ac19bdeb02fe2df62dc265/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_interfaces.g4#L220)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Given the simplicity of this grammar, can you please add all the options: https://www.juniper.net/documentation/us/en/software/junos/multicast-l2/topics/ref/statement/output-vlan-map-edit-interfaces-ge.html

```
i_input_vlan_map: INPUT_VLAN_MAP action = (PUSH | ...);
```

Can do this for both input and output.
</blockquote></details>

done
___
*[`projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_interfaces.g4` line 300 at r1](https://reviewable.io/reviews/batfish/batfish/8885#-NlxngGQD9ZxdsLelIRf:-Nly2xZf12W81HBpj4c1:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/8f6a9016fe4ee2e6c6ac19bdeb02fe2df62dc265/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_interfaces.g4#L300)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

please warn on both of these, they related to L2/L3 inference that we don't yet support.

(FYI no need to add a test that the warning is present, codecov will show us it got hit.)
</blockquote></details>

done

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8885)* status: all files reviewed, 3 unresolved discussions (waiting on @zergling-aws)

___
*[`projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_interfaces.g4` line 220 at r2](https://reviewable.io/reviews/batfish/batfish/8885#-Nly3uLA4eKX7LJJwjFz:-Nly3uLB6tBVJ23EVFG0:b6zst42) ([raw file](https://github.com/batfish/batfish/blob/22ad5d26cedb314b32f4325bb5f26ebb90e13cf8/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_interfaces.g4#L220)):*
> ```ANTLR
> i_input_vlan_map
> :
>    INPUT_VLAN_MAP (POP | PUSH)
> ```

please include all the action alternatives: https://www.juniper.net/documentation/us/en/software/junos/multicast-l2/topics/ref/statement/input-vlan-map-edit-interfaces-ge.html

```
(pop | pop-pop | pop-swap | push | push-push | swap | swap-push | swap-swap);
```
___
*[`projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_interfaces.g4` line 266 at r2](https://reviewable.io/reviews/batfish/batfish/8885#-Nly3eG_-SGPwsb1ITMS:-Nly3eG_-SGPwsb1ITMT:b-kc8nym) ([raw file](https://github.com/batfish/batfish/blob/22ad5d26cedb314b32f4325bb5f26ebb90e13cf8/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_interfaces.g4#L266)):*
> ```ANTLR
> i_output_vlan_map
> :
>    OUTPUT_VLAN_MAP (POP | PUSH)
> ```

please include all the action alternative:

```
(pop | pop-pop | pop-swap | push | push-push | swap | swap-push | swap-swap);
```

https://www.juniper.net/documentation/us/en/software/junos/multicast-l2/topics/ref/statement/output-vlan-map-edit-interfaces-ge.html
___
*[`projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java` line 4940 at r2](https://reviewable.io/reviews/batfish/batfish/8885#-Nly4-Xc3uagKTEoQwSp:-Nly4-Xc3uagKTEoQwSq:b-p7xkif) ([raw file](https://github.com/batfish/batfish/blob/22ad5d26cedb314b32f4325bb5f26ebb90e13cf8/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L4940)):*
> ```Java
>   @Override
>   public void exitI_output_vlan_map(I_output_vlan_mapContext ctx) {
>     warn(ctx, "Batfish does not support output-vlan-map");
> ```

Please follow the standard format for unsupported:

```
todo(ctx);
```

(on both)

**Review by zergling-aws — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8885)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @zergling-aws)

___
*[`projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_interfaces.g4` line 220 at r2](https://reviewable.io/reviews/batfish/batfish/8885#-Nly3uLA4eKX7LJJwjFz:-NlyBf5tEj0As50uOden:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/22ad5d26cedb314b32f4325bb5f26ebb90e13cf8/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_interfaces.g4#L220)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

please include all the action alternatives: https://www.juniper.net/documentation/us/en/software/junos/multicast-l2/topics/ref/statement/input-vlan-map-edit-interfaces-ge.html

```
(pop | pop-pop | pop-swap | push | push-push | swap | swap-push | swap-swap);
```
</blockquote></details>

done
___
*[`projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_interfaces.g4` line 266 at r2](https://reviewable.io/reviews/batfish/batfish/8885#-Nly3eG_-SGPwsb1ITMS:-NlyBh845FMMJ628vd4p:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/22ad5d26cedb314b32f4325bb5f26ebb90e13cf8/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_interfaces.g4#L266)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

please include all the action alternative:

```
(pop | pop-pop | pop-swap | push | push-push | swap | swap-push | swap-swap);
```

https://www.juniper.net/documentation/us/en/software/junos/multicast-l2/topics/ref/statement/output-vlan-map-edit-interfaces-ge.html
</blockquote></details>

done
___
*[`projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java` line 4940 at r2](https://reviewable.io/reviews/batfish/batfish/8885#-Nly4-Xc3uagKTEoQwSp:-Nly5pPJ1WsEFOu0aCFD:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/22ad5d26cedb314b32f4325bb5f26ebb90e13cf8/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L4940)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Please follow the standard format for unsupported:

```
todo(ctx);
```

(on both)
</blockquote></details>

done

**Review by dhalperi — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8885)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @zergling-aws)

**Pull request merged**
