### PR TITLE
Cumulus FRR only assign duplicated addresses to single interface per vrf

### PR DESCRIPTION
**Pull request by arifogel**
- First assign addresses from interfaces file
  - interface init order is from top to bottom, considering only first declaration of each interface
  - all of an interface's addresses are assigned on init
    - previously assigned addresses in the same VRF are skipped
- Now assign addresses from frr file
  - interface init order is from bottom to top, considering only last declaration of each interface
  - all of an interface's addresses are assigned on init
    - previously assigned addresses in the same VRF are skipped,
      including those from interfaces file

### CODE REVIEW

**Review by corinaminer — COMMENTED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7030)* status: all files reviewed, 6 unresolved discussions (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/grammar/cumulus_frr/CumulusFrrConfigurationBuilder.java, line 267 at r1](https://reviewable.io/reviews/batfish/batfish/7030#-Mb7z5WjBUaDyEpIzK8I:-Mb7z5WjBUaDyEpIzK8J:b-k5r42k) ([raw file](https://github.com/batfish/batfish/blob/18153645ed370e9d85c8dddaed8f5edc4290eeec/projects/batfish/src/main/java/org/batfish/grammar/cumulus_frr/CumulusFrrConfigurationBuilder.java#L267)):*
> ```Java
>   private OspfArea _currentOspfArea;
>   private OspfVrf _currentOspfVrf;
>   private Set<String> _reverseInterfaceInitOrder;
> ```

please add a comment for clarity here that interfaces in the FRR file are inited from bottom to top.
___
*[projects/batfish/src/main/java/org/batfish/grammar/cumulus_interfaces/CumulusInterfacesConfigurationBuilder.java, line 175 at r1](https://reviewable.io/reviews/batfish/batfish/7030#-Mb7zSbXCoWWWDDoGpIX:-Mb7zSbXCoWWWDDoGpIY:ba47a8w) ([raw file](https://github.com/batfish/batfish/blob/18153645ed370e9d85c8dddaed8f5edc4290eeec/projects/batfish/src/main/java/org/batfish/grammar/cumulus_interfaces/CumulusInterfacesConfigurationBuilder.java#L175)):*
> ```Java
>   public void enterS_iface(S_ifaceContext ctx) {
>     _currentIfaceName = ctx.interface_name().getText();
>     _interfaceInitOrder.add(_currentIfaceName);
> ```

does this need to handle repeat interface declarations? i'm guessing no, since calling `add` with a name already in the set has no effect (including on set order). If so, i think it's worth adding a comment to clarify that that's the intended behavior for repeats.
___
*[projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConcatenatedConfiguration.java, line 128 at r1](https://reviewable.io/reviews/batfish/batfish/7030#-Mb8-ads-OY4bWHLwdu5:-Mb8-adt6eFgl3qQZKqx:b-1grak) ([raw file](https://github.com/batfish/batfish/blob/18153645ed370e9d85c8dddaed8f5edc4290eeec/projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConcatenatedConfiguration.java#L128)):*
> ```Java
>   }
> 
>   private void initializeVrfIpOwners() {}
> ```

remove or implement -- looks like you're using `ownedPrefixesByVrf()` instead
___
*[projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConcatenatedConfiguration.java, line 306 at r1](https://reviewable.io/reviews/batfish/batfish/7030#-Mb83J-r1am4rr8mMH6b:-Mb83J-r1am4rr8mMH6c:b-mh5rq) ([raw file](https://github.com/batfish/batfish/blob/18153645ed370e9d85c8dddaed8f5edc4290eeec/projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConcatenatedConfiguration.java#L306)):*
> ```Java
>     List<ConcreteInterfaceAddress> ownedIpAddresses = ownedIpAddressesBuilder.build();
>     if (!ownedIpAddresses.isEmpty()) {
>       viIface.setAddress(ownedIpAddresses.get(0));
> ```

This doesn't seem right -- FRR interfaces can have a primary address that's shared with other interfaces, right? I think we should leave primary address null and only populate secondary addresses if the interface's first address is shared.
___
*[projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConcatenatedConfiguration.java, line 312 at r1](https://reviewable.io/reviews/batfish/batfish/7030#-Mb83kC0CSLmWmmWtKqZ:-Mb83kC0CSLmWmmWtKq_:bb43nfr) ([raw file](https://github.com/batfish/batfish/blob/18153645ed370e9d85c8dddaed8f5edc4290eeec/projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConcatenatedConfiguration.java#L312)):*
> ```Java
>               .addAll(ownedIpAddresses)
>               .build());
>     }
> ```

i'd refactor this logic into a separate function to be used here and in `populateCommonInterfaceProperties()`. non-blocking
___
*[projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusFrrConfiguration.java, line 139 at r1](https://reviewable.io/reviews/batfish/batfish/7030#-Mb84KSZ6wVS0BW5i33F:-Mb84KSZ6wVS0BW5i33G:b-vsv63g) ([raw file](https://github.com/batfish/batfish/blob/18153645ed370e9d85c8dddaed8f5edc4290eeec/projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusFrrConfiguration.java#L139)):*
> ```Java
>         _interfaceInitOrder,
>         // for ease of testing
>         Collections.unmodifiableSet(_interfaces.keySet()));
> ```

is this order guaranteed? or figuring that for the purpose of tests it doesn't matter? (if it does matter, i'd recommend `_interfaces.keySet().stream().sorted().collect(...)` for predictability)
___
*[projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java, line 2524 at r1](https://reviewable.io/reviews/batfish/batfish/7030#-Mb85MEW8N2jQecpOZ8k:-Mb85MEW8N2jQecpOZ8l:bksd7y3) ([raw file](https://github.com/batfish/batfish/blob/18153645ed370e9d85c8dddaed8f5edc4290eeec/projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java#L2524)):*
> ```Java
> 
>     // init from the back
>     assertThat(_frr.getInterfaceInitOrder(), contains("swp3", "swp1", "swp2"));
> ```

what happens if you reinit an interface in a different VRF?

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7030)* status: all files reviewed, 5 unresolved discussions (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConcatenatedConfiguration.java, line 306 at r1](https://reviewable.io/reviews/batfish/batfish/7030#-Mb83J-r1am4rr8mMH6b:-Mb8GZ7d2Of20NcMwOlP:b-nmlujo) ([raw file](https://github.com/batfish/batfish/blob/18153645ed370e9d85c8dddaed8f5edc4290eeec/projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConcatenatedConfiguration.java#L306)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

This doesn't seem right -- FRR interfaces can have a primary address that's shared with other interfaces, right? I think we should leave primary address null and only populate secondary addresses if the interface's first address is shared.
</blockquote></details>

Discussed offline. Resolving because:
1. we're not sure batfish is robust to interfaces with secondary addresses but no primary address
2. primary address is largely a cisco-centric concept; as far as batfish is concerned, it just provides a preferred source IP for packets sent from the interface
3. shared addresses are only likely to be used when trying to conserve IPs, so it's unlikely that an interface with shared addresses will also have non-shared addresses

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7030)* status: all files reviewed, 4 unresolved discussions (waiting on @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/grammar/cumulus_frr/CumulusFrrConfigurationBuilder.java, line 267 at r1](https://reviewable.io/reviews/batfish/batfish/7030#-Mb7z5WjBUaDyEpIzK8I:-Mb8HGy61jMqSGa8Rkh7:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/18153645ed370e9d85c8dddaed8f5edc4290eeec/projects/batfish/src/main/java/org/batfish/grammar/cumulus_frr/CumulusFrrConfigurationBuilder.java#L267)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

please add a comment for clarity here that interfaces in the FRR file are inited from bottom to top.
</blockquote></details>

done
___
*[projects/batfish/src/main/java/org/batfish/grammar/cumulus_interfaces/CumulusInterfacesConfigurationBuilder.java, line 175 at r1](https://reviewable.io/reviews/batfish/batfish/7030#-Mb7zSbXCoWWWDDoGpIX:-Mb8HP4TDyj0N4VEauO6:b5lkirb) ([raw file](https://github.com/batfish/batfish/blob/18153645ed370e9d85c8dddaed8f5edc4290eeec/projects/batfish/src/main/java/org/batfish/grammar/cumulus_interfaces/CumulusInterfacesConfigurationBuilder.java#L175)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

does this need to handle repeat interface declarations? i'm guessing no, since calling `add` with a name already in the set has no effect (including on set order). If so, i think it's worth adding a comment to clarify that that's the intended behavior for repeats.
</blockquote></details>

That's the contract of `LinkedHashSet`. Added comment for clarity.
___
*[projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConcatenatedConfiguration.java, line 128 at r1](https://reviewable.io/reviews/batfish/batfish/7030#-Mb8-ads-OY4bWHLwdu5:-Mb8E0tFB_J0jkzIV4Ks:b-5aq4c4) ([raw file](https://github.com/batfish/batfish/blob/18153645ed370e9d85c8dddaed8f5edc4290eeec/projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConcatenatedConfiguration.java#L128)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

remove or implement -- looks like you're using `ownedPrefixesByVrf()` instead
</blockquote></details>

Yeah that was abandoned. Removed.
___
*[projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusFrrConfiguration.java, line 139 at r1](https://reviewable.io/reviews/batfish/batfish/7030#-Mb84KSZ6wVS0BW5i33F:-Mb8GizTCwR-kiH4zaAn:b2ikwem) ([raw file](https://github.com/batfish/batfish/blob/18153645ed370e9d85c8dddaed8f5edc4290eeec/projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusFrrConfiguration.java#L139)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

is this order guaranteed? or figuring that for the purpose of tests it doesn't matter? (if it does matter, i'd recommend `_interfaces.keySet().stream().sorted().collect(...)` for predictability)
</blockquote></details>

This order is not any different that before this PR. IMO it makes no sense to introduce yet a third ordering.
Either we require tests to initialize interfaceInitOrder (lots of work for little benefit), or we add this hack.
___
*[projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java, line 2524 at r1](https://reviewable.io/reviews/batfish/batfish/7030#-Mb85MEW8N2jQecpOZ8k:-Mb8H0yjEv0wiOEpAt39:bagsucg) ([raw file](https://github.com/batfish/batfish/blob/18153645ed370e9d85c8dddaed8f5edc4290eeec/projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java#L2524)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

what happens if you reinit an interface in a different VRF?
</blockquote></details>

You can't on FRR.

**Review by corinaminer — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7030#-:-Mb8YacQAwsMPR-qC0BG:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusFrrConfiguration.java, line 139 at r1](https://reviewable.io/reviews/batfish/batfish/7030#-Mb84KSZ6wVS0BW5i33F:-Mb8YSu4-vKpA6wgkqO4:b-uogant) ([raw file](https://github.com/batfish/batfish/blob/18153645ed370e9d85c8dddaed8f5edc4290eeec/projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusFrrConfiguration.java#L139)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

This order is not any different that before this PR. IMO it makes no sense to introduce yet a third ordering.
Either we require tests to initialize interfaceInitOrder (lots of work for little benefit), or we add this hack.
</blockquote></details>

hack sgtm

**Pull request merged**
