### PR TITLE
CheckPoint: initial `Service` support in `AccessRule`s

### PR DESCRIPTION
**Pull request by sfraint**

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7347)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7347)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7347#-Mj5YVZG60W4UdpFsID-:-Mj5YVZG60W4UdpFsID0:bozgb6q) (no related file):*
still need to fix multiple-service matching

---

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7347)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @arifogel and @dhalperi)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7347#-Mj5YVZG60W4UdpFsID-:-Mj5hh4GDTdGGub0CVLM:bvnrpcm) (no related file):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

still need to fix multiple-service matching
</blockquote></details>

updated

---

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7347)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7347)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Pull request merged**
