### PR TITLE
Junos: support as-path-group as-path regex `!.*`

### PR DESCRIPTION
**Pull request by zergling-aws**
Added special cased support for the as-path regex !.*

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
Nice work.

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8921#-:-NnkPqiM1tfTThlI9IC1:bdtx8rj)* status: all files reviewed, 7 unresolved discussions (waiting on @zergling-aws)

___
*[`projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4` line 3788 at r1](https://reviewable.io/reviews/batfish/batfish/8921#-NnkIaDb3Yt6J63xMP3N:-NnkIaDb3Yt6J63xMP3O:bssz1bu) ([raw file](https://github.com/batfish/batfish/blob/cba89a79bd5533880abb8e3a0c48c1a079ad09ac/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4#L3788)):*
> ```ANTLR
> F_QuotedAsPathRegex
> :
>   '"' '!'? F_QuotedAsPathRegexChar+ '"'
> ```

I see why you did it here, but I think in the vnedor it can be anywhere. I would do this in `F_QuotedAsPathRegexChar` instead. Note we can still warn if it appears in the middle of the regex.



_Code quote:_
```ANTLR
 '!'? 
```
___
*[`projects/batfish/src/main/java/org/batfish/representation/juniper/AsPathMatchExprParser.java` line 137 at r1](https://reviewable.io/reviews/batfish/batfish/8921#-NnkIqc89sFO_HWRNRME:-NnkIqc89sFO_HWRNRMF:b-vazkg5) ([raw file](https://github.com/batfish/batfish/blob/cba89a79bd5533880abb8e3a0c48c1a079ad09ac/projects/batfish/src/main/java/org/batfish/representation/juniper/AsPathMatchExprParser.java#L137)):*
> ```Java
>    */
>   public static BooleanExpr convertToBooleanExpr(String asPathRegex) {
>     Matcher asPathMatchNone = AS_PATH_MATCH_NONE.matcher(asPathRegex);
> ```

Why use regex for this vs just String#equals?
___
*[`projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java` line 8115 at r1](https://reviewable.io/reviews/batfish/batfish/8921#-NnkP_mX8dU4YBmBi5dz:-NnkP_mX8dU4YBmBi5e-:b-pb44rm) ([raw file](https://github.com/batfish/batfish/blob/cba89a79bd5533880abb8e3a0c48c1a079ad09ac/projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java#L8115)):*
> ```Java
>   public void testJuniperAsPathExclamationRegex() {
>     Configuration c = parseConfig("juniper-as-path-exclamation-regex");
>     Prefix testPrefix = Prefix.parse("1.1.1.1/28");
> ```

inline
___
*[`projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java` line 8116 at r1](https://reviewable.io/reviews/batfish/batfish/8921#-NnkPaj49FxfOqT3hONi:-NnkPaj49FxfOqT3hONj:boe9p7e) ([raw file](https://github.com/batfish/batfish/blob/cba89a79bd5533880abb8e3a0c48c1a079ad09ac/projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java#L8116)):*
> ```Java
>     Configuration c = parseConfig("juniper-as-path-exclamation-regex");
>     Prefix testPrefix = Prefix.parse("1.1.1.1/28");
>     Result result;
> ```

inline or put on same line as assignment.
___
*[`projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java` line 8121 at r1](https://reviewable.io/reviews/batfish/batfish/8921#-NnkPcZV0yV61VP1fzym:-NnkPcZV0yV61VP1fzyn:bo38aw) ([raw file](https://github.com/batfish/batfish/blob/cba89a79bd5533880abb8e3a0c48c1a079ad09ac/projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java#L8121)):*
> ```Java
>     AS_PATH_GROUP_POLICY should accept routes from as-path within as-path-group
>     set policy-options policy-statement AS_PATH_GROUP_POLICY term T1 from as-path-group AS_PATH_GROUP
>     */
> ```

drop this comment, the text speaks for itself.
___
*[`projects/batfish/src/test/java/org/batfish/representation/juniper/AsPathMatchExprParserTest.java` line 155 at r1](https://reviewable.io/reviews/batfish/batfish/8921#-NnkJAPg0pvGNBnRntsu:-NnkJAPg0pvGNBnRntsv:b-mmp26k) ([raw file](https://github.com/batfish/batfish/blob/cba89a79bd5533880abb8e3a0c48c1a079ad09ac/projects/batfish/src/test/java/org/batfish/representation/juniper/AsPathMatchExprParserTest.java#L155)):*
> ```Java
>   public void testAsPathMatchNone() {
>     BooleanExpr res1 = convertToBooleanExpr("!.*");
>     assertTrue(res1 == BooleanExprs.FALSE);
> ```

`assertThat(res1, equalTo(BooleanExprs.FALSE))` instead of `assert( ==)`.

if you want instance equality, use `sameInstanceAs` [I think, might be `sameInstance`].
___
*[`projects/batfish/src/test/java/org/batfish/representation/juniper/AsPathMatchExprParserTest.java` line 158 at r1](https://reviewable.io/reviews/batfish/batfish/8921#-NnkJLKR1idqg491hzd2:-NnkJLKR1idqg491hzd3:b8lea9f) ([raw file](https://github.com/batfish/batfish/blob/cba89a79bd5533880abb8e3a0c48c1a079ad09ac/projects/batfish/src/test/java/org/batfish/representation/juniper/AsPathMatchExprParserTest.java#L158)):*
> ```Java
> 
>     BooleanExpr res2 = convertToBooleanExpr(".* 1234 .*");
>     assertThat(res2, instanceOf(MatchAsPath.class));
> ```

can we inline res1 and res2?

`assertThat(convertToBooleanExpr("!.*"), sameInstance(BooleanExprs.FALSE))` e.g.

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8921)* status: all files reviewed, 7 unresolved discussions (waiting on @zergling-aws)

___
*[`projects/batfish/src/test/java/org/batfish/representation/juniper/AsPathMatchExprParserTest.java` line 155 at r1](https://reviewable.io/reviews/batfish/batfish/8921#-NnkJAPg0pvGNBnRntsu:-NnkPzI6D9zPZa-U90KM:b-b9b701) ([raw file](https://github.com/batfish/batfish/blob/cba89a79bd5533880abb8e3a0c48c1a079ad09ac/projects/batfish/src/test/java/org/batfish/representation/juniper/AsPathMatchExprParserTest.java#L155)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

`assertThat(res1, equalTo(BooleanExprs.FALSE))` instead of `assert( ==)`.

if you want instance equality, use `sameInstanceAs` [I think, might be `sameInstance`].
</blockquote></details>

Also PMD failed recommending `assertSame`, would also be better if you prefer.

**Review by zergling-aws — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8921)* status: 3 of 7 files reviewed, 2 unresolved discussions (waiting on @dhalperi)

___
*[`projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4` line 3788 at r1](https://reviewable.io/reviews/batfish/batfish/8921#-NnkIaDb3Yt6J63xMP3N:-NnkUaMa3Nj1EGYd4NaO:bghdacv) ([raw file](https://github.com/batfish/batfish/blob/cba89a79bd5533880abb8e3a0c48c1a079ad09ac/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4#L3788)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I see why you did it here, but I think in the vnedor it can be anywhere. I would do this in `F_QuotedAsPathRegexChar` instead. Note we can still warn if it appears in the middle of the regex.
</blockquote></details>

Ok, I checked in emulation that ! can be in middle of regex. Fixed.
___
*[`projects/batfish/src/main/java/org/batfish/representation/juniper/AsPathMatchExprParser.java` line 137 at r1](https://reviewable.io/reviews/batfish/batfish/8921#-NnkIqc89sFO_HWRNRME:-NnkWIheCTjUqLQowy6j:bzgjrbp) ([raw file](https://github.com/batfish/batfish/blob/cba89a79bd5533880abb8e3a0c48c1a079ad09ac/projects/batfish/src/main/java/org/batfish/representation/juniper/AsPathMatchExprParser.java#L137)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Why use regex for this vs just String#equals?
</blockquote></details>

I was trying to follow the existing pattern which was matching regex constants defined at the top; I've now simplified it to just use string equality.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8921)* status: all files reviewed, 1 unresolved discussion (waiting on @zergling-aws)

___
*[`projects/batfish/src/main/java/org/batfish/representation/juniper/AsPathMatchExprParser.java` line 141 at r2](https://reviewable.io/reviews/batfish/batfish/8921#-NnkeaQN9oyPOu_Bzghl:-NnkeaQN9oyPOu_Bzghm:bv0pe6u) ([raw file](https://github.com/batfish/batfish/blob/cf3ae1a1237f7f253d95de08981a9417c440806e/projects/batfish/src/main/java/org/batfish/representation/juniper/AsPathMatchExprParser.java#L141)):*
> ```Java
>       // return Not(MatchAsPath.of(InputAsPath.instance(),
>       // convertToAsPathMatchExpr(asPathRegex.substring(1))));
>       throw new IllegalArgumentException();
> ```

In my opinion this is a "local minimum" for what to do here, because we throw an exception with no context. I'd prefer:

1. Drop this entire `else if` block and let it fail later (will get better error messages), like unhandled regex.
2. Keep it, but add some context like "Unsupported regex: ..."
3. Implement it. It's not much different code than is in there already I think.

Up to you.



_Code quote:_
```Java
      // TODO: match the complement of what follows the "!" with something like this:
      // return Not(MatchAsPath.of(InputAsPath.instance(),
      // convertToAsPathMatchExpr(asPathRegex.substring(1))));
      throw new IllegalArgumentException();
```

**Review by zergling-aws — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8921)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[`projects/batfish/src/main/java/org/batfish/representation/juniper/AsPathMatchExprParser.java` line 141 at r2](https://reviewable.io/reviews/batfish/batfish/8921#-NnkeaQN9oyPOu_Bzghl:-NnksA3b66ejDWtV-krH:bpyis9k) ([raw file](https://github.com/batfish/batfish/blob/cf3ae1a1237f7f253d95de08981a9417c440806e/projects/batfish/src/main/java/org/batfish/representation/juniper/AsPathMatchExprParser.java#L141)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

In my opinion this is a "local minimum" for what to do here, because we throw an exception with no context. I'd prefer:

1. Drop this entire `else if` block and let it fail later (will get better error messages), like unhandled regex.
2. Keep it, but add some context like "Unsupported regex: ..."
3. Implement it. It's not much different code than is in there already I think.

Up to you.
</blockquote></details>

I changed it to approach #1 of dropping

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8921)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @zergling-aws)

**Pull request merged**
