### PR TITLE
reference github issues in ignored tests

### PR DESCRIPTION
**Pull request by anothermattbrown**

### CODE REVIEW

**Comment by dhalperi** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed, 1 unresolved discussion (waiting on @anothermattbrown)

---

*[projects/allinone/src/test/java/org/batfish/symbolic/smt/SmtReachabilityTwoLinkPerDstIpTest.java, line 152 at r1](https://reviewable.io/reviews/batfish/batfish/1725#-LFZAgeYDzu8KidkjoS5:-LFZAgeYDzu8KidkjoS6:b-cxaxhd) ([raw file](https://github.com/batfish/batfish/blob/1be9bd1ddbb29918d65c05cbceabb3912f590d2d/projects/allinone/src/test/java/org/batfish/symbolic/smt/SmtReachabilityTwoLinkPerDstIpTest.java#L152)):*
> ```Java
>    *
>    * <p>{@link Ignore Ignored} because of issue #1723: adding a dstIp constraint seems to cause
>    * minesweeper to ignore the failures constraint.
> ```

What we've done in past is put this as the `reason` of the `@Ignore`:

https://github.com/batfish/batfish/commit/7fd136ee8b85453912a309d405551358661321ce#diff-2cb39dbb5444ea3090356eaebe591a26L110

Some tools surface this information when skipping JUnit tests.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1725)*

**Comment by anothermattbrown** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @anothermattbrown)

---

*[projects/allinone/src/test/java/org/batfish/symbolic/smt/SmtReachabilityTwoLinkPerDstIpTest.java, line 152 at r1](https://reviewable.io/reviews/batfish/batfish/1725#-LFZAgeYDzu8KidkjoS5:-LFdEkBUAQEgdXfQXOjy:basnjb0) ([raw file](https://github.com/batfish/batfish/blob/1be9bd1ddbb29918d65c05cbceabb3912f590d2d/projects/allinone/src/test/java/org/batfish/symbolic/smt/SmtReachabilityTwoLinkPerDstIpTest.java#L152)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

What we've done in past is put this as the `reason` of the `@Ignore`:

https://github.com/batfish/batfish/commit/7fd136ee8b85453912a309d405551358661321ce#diff-2cb39dbb5444ea3090356eaebe591a26L110

Some tools surface this information when skipping JUnit tests.
</blockquote></details>

aha, cool.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1725)*

**Comment by dhalperi** [comment]
Reviewed 1 of 2 files at r2.
Review status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @dhalperi and @anothermattbrown)

---

*[projects/allinone/src/test/java/org/batfish/symbolic/smt/SmtReachabilityTwoLinkTest.java, line 62 at r2](https://reviewable.io/reviews/batfish/batfish/1725#-LFdaL_s3snceP-rWiDJ:-LFdaL_s3snceP-rWiDK:b-m3jvly) ([raw file](https://github.com/batfish/batfish/blob/7bb747a768140672fd93b66b179f26ea82caa8a5/projects/allinone/src/test/java/org/batfish/symbolic/smt/SmtReachabilityTwoLinkTest.java#L62)):*
> ```Java
> 
>   /**
>    * Negation of the above test, i.e. verify unreachability under 1 failure. False, because
> ```

"verify unreachability for all failure scenarios up to 1 link (aka, unreachability both in 0 failures or 1 failures)." ? I guess discussion is continuing on the issue.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1725)*

**Comment by dhalperi** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed, 1 unresolved discussion (waiting on @anothermattbrown)

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1725)*

**Comment by anothermattbrown** [comment]
Review status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @dhalperi and @anothermattbrown)

---

*[projects/allinone/src/test/java/org/batfish/symbolic/smt/SmtReachabilityTwoLinkTest.java, line 62 at r2](https://reviewable.io/reviews/batfish/batfish/1725#-LFdaL_s3snceP-rWiDJ:-LFs3NSUEgOq2FiwWE7c:brmk5ip) ([raw file](https://github.com/batfish/batfish/blob/7bb747a768140672fd93b66b179f26ea82caa8a5/projects/allinone/src/test/java/org/batfish/symbolic/smt/SmtReachabilityTwoLinkTest.java#L62)):*
> verify unreachability for all failure scenarios up to 1 link (aka, unreachability both in 0 failures or 1 failures).
Done. I think the discussion is largely resolved, at least for what the current behavior is. It's still unclear if we should change or extend it, but it doesn't need to happen now.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1725)*

**Comment by dhalperi** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1725)*

**Comment by dhalperi** [comment]
:lgtm:

---

Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1725#-:-LFs59259yYSBOwrHVxm:bnfp4nl)*

**Pull request merged**
