### PR TITLE
IntelliJ: automated inspection-driven fixes 2/ 

### PR DESCRIPTION
**Pull request by dhalperi**

### CODE REVIEW

**Comment by dhalperi** [comment]
*[a discussion](https://reviewable.io/reviews/batfish/batfish/1783#-LG6b00HCMPcWGT3Ne14:-LG6b00HCMPcWGT3Ne15:b-88jbfj) (no related file):*
Comment to force reviewable to stay in commit-by-commit mode.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1783)*

**Comment by dhalperi** [comment]
*[projects/batfish/src/main/java/org/batfish/z3/IpAccessListSpecializer.java, line 77 at r6](https://reviewable.io/reviews/batfish/batfish/1783#-LG6cBtH8JR0iLcKgr1i:-LG6cBtH8JR0iLcKgr1j:bvmw01b) ([raw file](https://github.com/batfish/batfish/blob/524727132b96f4fc6359d0fef8d61b5ba7366e15/projects/batfish/src/main/java/org/batfish/z3/IpAccessListSpecializer.java#L77)):*
> ```Java
>     _canSpecialize =
>         _dstIpSpaceSpecializer != null
>             || _srcIpSpaceSpecializer != null
> ```

matt: is this indicative of an issue? The assertion from IntelliJ was that the third one is always null.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1783)*

**Comment by dhalperi** [comment]
*[projects/batfish/src/main/java/org/batfish/z3/IpAccessListSpecializer.java, line 77 at r6](https://reviewable.io/reviews/batfish/batfish/1783#-LG6cBtH8JR0iLcKgr1i:-LG6cLgyAmyxNQzKH44g:b41ij3v) ([raw file](https://github.com/batfish/batfish/blob/524727132b96f4fc6359d0fef8d61b5ba7366e15/projects/batfish/src/main/java/org/batfish/z3/IpAccessListSpecializer.java#L77)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

matt: is this indicative of an issue? The assertion from IntelliJ was that the third one is always null.
</blockquote></details>

at least, if the first two are.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1783)*

**Comment by anothermattbrown** [comment]
Reviewed 1 of 1 files at r1, 11 of 11 files at r2, 2 of 2 files at r3, 7 of 9 files at r4, 5 of 7 files at r5, 14 of 14 files at r6, 1 of 1 files at r7, 2 of 2 files at r8, 3 of 3 files at r9, 3 of 3 files at r10, 3 of 3 files at r11, 1 of 1 files at r12, 1 of 1 files at r13, 1 of 1 files at r14, 12 of 12 files at r15, 5 of 5 files at r16, 3 of 3 files at r17, 1 of 1 files at r18, 2 of 2 files at r19.
Review status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi and @progwriter)

---

*[projects/batfish/src/main/java/org/batfish/z3/LocationToIngressLocation.java, line 10 at r15](https://reviewable.io/reviews/batfish/batfish/1783#-LG6qGoIDryigRYIb393:-LG6qGoIDryigRYIb394:b5dufcn) ([raw file](https://github.com/batfish/batfish/blob/524727132b96f4fc6359d0fef8d61b5ba7366e15/projects/batfish/src/main/java/org/batfish/z3/LocationToIngressLocation.java#L10)):*
> ```Java
> 
> /**
>  * Converts {@link Location}s to {@link IngressLocation}s, mapping {@link InterfaceLinkLocation}s to
> ```

Is this the right fix? Was the original problem that `Location` isn't imported? Maybe it should be `{@link org.batfish.specifier.Location locations}`

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1783)*

**Comment by dhalperi** [comment]
*[projects/batfish/src/main/java/org/batfish/z3/LocationToIngressLocation.java, line 10 at r15](https://reviewable.io/reviews/batfish/batfish/1783#-LG6qGoIDryigRYIb393:-LG6x3AvD-P5r3vDxX3g:b-abq6eo) ([raw file](https://github.com/batfish/batfish/blob/524727132b96f4fc6359d0fef8d61b5ba7366e15/projects/batfish/src/main/java/org/batfish/z3/LocationToIngressLocation.java#L10)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

Is this the right fix? Was the original problem that `Location` isn't imported? Maybe it should be `{@link org.batfish.specifier.Location locations}`
</blockquote></details>

See if new javadoc is better now. I linked the other words that are actually types here too.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1783)*

**Comment by anothermattbrown** [comment]
Reviewed 1 of 1 files at r20.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @progwriter)

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1783)*

**Pull request merged**
