### PR TITLE
FRR: Make `allowas-in <num>` to be optional

### PR DESCRIPTION
**Pull request by ton31337**
FRR accepts this command without a number as well.

Signed-off-by: Donatas Abraitis <donatas.abraitis@gmail.com>

Closes https://github.com/batfish/batfish/issues/7680

### CODE REVIEW

**Review by ratulm — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7694)* status: all files reviewed, 1 unresolved discussion (waiting on @ton31337)

___
*[projects/batfish/src/main/java/org/batfish/grammar/frr/FrrConfigurationBuilder.java, line 1104 at r1](https://reviewable.io/reviews/batfish/batfish/7694#-MoZdjFy5KZPZYPCBRJ8:-MoZdjFy5KZPZYPCBRJ9:bwkjdbe) ([raw file](https://github.com/batfish/batfish/blob/9f123f53a88bfa3565557aacf587230f9831fc83/projects/batfish/src/main/java/org/batfish/grammar/frr/FrrConfigurationBuilder.java#L1104)):*
> ```Java
>           Integer.parseInt(ctx.count.getText()));
>     } else {
>       _currentBgpNeighborIpv4UnicastAddressFamily.setAllowAsIn(3);
> ```

Why 3? is that the default value?

**Comment by ton31337** [comment]
Currently yes.

**Comment by ratulm** [comment]
> Currently yes.

Ok, please leave a comment to that effect in the code.

**Comment by ton31337** [comment]
> > Currently yes.
> 
> Ok, please leave a comment to that effect in the code.

Added.

**Review by ratulm — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7694)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ton31337)

**Pull request merged**
