### PR TITLE
Fix route reflection

### LINKED ISSUE #849: Route Reflection does not work for Juniper configurations
This is because Cluster Id is never set for Juniper Configuration Format

### PR DESCRIPTION
**Pull request by arifogel**
- Add tests
- Add implementation for Juniper
- Fixes #849

---
This change is [Reviewable](https://reviewable.io/reviews/batfish/batfish/862)

### CODE REVIEW

**Comment by dhalperi** [comment]
:lgtm:

---

Reviewed 19 of 19 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpProcess.java, line 153 at r1](https://reviewable.io:443/reviews/batfish/batfish/862#-L37CTFfDPQHglr8H1Nh:-L37CTFfDPQHglr8H1Ni:buvnyjh) ([raw file](https://github.com/batfish/batfish/blob/a2be82eb7e96166fb12ae47226f2b32c3502a6b6/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpProcess.java#L153)):*
> ```Java
> 
>   public void initClusterIds() {
>     _clusterIds =
> ```

is there any guards that should apply here. Run this code whenever neighbors is set, error if _clusterIds is set, etc? lazy init in the getter?

---

*[projects/batfish/src/main/java/org/batfish/bdp/BdpEngine.java, line 430 at r1](https://reviewable.io:443/reviews/batfish/batfish/862#-L37DnSMcbMDH7y-zfZ2:-L37DnSMcbMDH7y-zfZ3:b-i2s8w4) ([raw file](https://github.com/batfish/batfish/blob/a2be82eb7e96166fb12ae47226f2b32c3502a6b6/projects/batfish/src/main/java/org/batfish/bdp/BdpEngine.java#L430)):*
> ```Java
>           .flatMap(Collection::stream)
>           .filter(v -> v.getBgpProcess() != null)
>           .map(Vrf::getBgpProcess)
> ```

do this before the filter so the filter is just proc -> proc != null?

---

*[projects/batfish/src/main/java/org/batfish/bdp/BdpEngine.java, line 431 at r1](https://reviewable.io:443/reviews/batfish/batfish/862#-L37DsKooUbsVIWYNOGZ:-L37DsKooUbsVIWYNOG_:b-xcidys) ([raw file](https://github.com/batfish/batfish/blob/a2be82eb7e96166fb12ae47226f2b32c3502a6b6/projects/batfish/src/main/java/org/batfish/bdp/BdpEngine.java#L431)):*
> ```Java
>           .filter(v -> v.getBgpProcess() != null)
>           .map(Vrf::getBgpProcess)
>           .forEach(proc -> proc.initClusterIds());
> ```

::initClusterIds?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/862#-:-L37H0i9PMeEPFJqMso8:bnfp4nl)*

**Comment by progwriter** [comment]
:lgtm: only requests for clarification comments, especially for tests

---

Reviewed 19 of 19 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[projects/batfish/src/test/java/org/batfish/bdp/RouteReflectionTest.java, line 108 at r1](https://reviewable.io:443/reviews/batfish/batfish/862#-L3AFzs_sBWvUdXaoaXj:-L3AFzs_sBWvUdXaoaXk:b1d7wek) ([raw file](https://github.com/batfish/batfish/blob/a2be82eb7e96166fb12ae47226f2b32c3502a6b6/projects/batfish/src/test/java/org/batfish/bdp/RouteReflectionTest.java#L108)):*
> ```Java
> 
>   private SortedMap<String, SortedMap<String, SortedSet<AbstractRoute>>> generateRoutesOneReflector(
>       boolean edge1RouteReflectorClient, boolean edge2RouteReflectorClient) {
> ```

Please add javadoc/comment as to what is being setup here. Is this just two nodes connected to 1 RR?

---

*[projects/batfish/src/test/java/org/batfish/bdp/RouteReflectionTest.java, line 344 at r1](https://reviewable.io:443/reviews/batfish/batfish/862#-L3AGNbVHhq6J_kgL4wq:-L3AGNbVHhq6J_kgL4wr:b-pkfax8) ([raw file](https://github.com/batfish/batfish/blob/a2be82eb7e96166fb12ae47226f2b32c3502a6b6/projects/batfish/src/test/java/org/batfish/bdp/RouteReflectionTest.java#L344)):*
> ```Java
> 
>   @Before
>   public void setup() {
> ```

Please add javadoc/comments as to what exactly is being setup here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/862#-:-L3AHIaZPYiMoxYYnOYs:b9ej60t)*

**Comment by arifogel** [comment]
Review status: 16 of 18 files reviewed at latest revision, 5 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpProcess.java, line 153 at r1](https://reviewable.io:443/reviews/batfish/batfish/862#-L37CTFfDPQHglr8H1Nh:-L3FpIDcsYAYveByGCzn:b-2ffynv) ([raw file](https://github.com/batfish/batfish/blob/a2be82eb7e96166fb12ae47226f2b32c3502a6b6/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpProcess.java#L153)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

is there any guards that should apply here. Run this code whenever neighbors is set, error if _clusterIds is set, etc? lazy init in the getter?
</blockquote></details>

Added lazy init, javadoc warning about when to call.

---

*[projects/batfish/src/test/java/org/batfish/bdp/RouteReflectionTest.java, line 108 at r1](https://reviewable.io:443/reviews/batfish/batfish/862#-L3AFzs_sBWvUdXaoaXj:-L3G34NXdyUzwDgKFOFc:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/a2be82eb7e96166fb12ae47226f2b32c3502a6b6/projects/batfish/src/test/java/org/batfish/bdp/RouteReflectionTest.java#L108)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

Please add javadoc/comment as to what is being setup here. Is this just two nodes connected to 1 RR?
</blockquote></details>

Done.

---

*[projects/batfish/src/test/java/org/batfish/bdp/RouteReflectionTest.java, line 344 at r1](https://reviewable.io:443/reviews/batfish/batfish/862#-L3AGNbVHhq6J_kgL4wq:-L3G35ey8Bk0XZGIiECV:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/a2be82eb7e96166fb12ae47226f2b32c3502a6b6/projects/batfish/src/test/java/org/batfish/bdp/RouteReflectionTest.java#L344)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

Please add javadoc/comments as to what exactly is being setup here
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/bdp/BdpEngine.java, line 430 at r1](https://reviewable.io:443/reviews/batfish/batfish/862#-L37DnSMcbMDH7y-zfZ2:-L3FpdPUTq9bLWxMXq0B:bb70dyk) ([raw file](https://github.com/batfish/batfish/blob/a2be82eb7e96166fb12ae47226f2b32c3502a6b6/projects/batfish/src/main/java/org/batfish/bdp/BdpEngine.java#L430)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

do this before the filter so the filter is just proc -> proc != null?
</blockquote></details>

Moot

---

*[projects/batfish/src/main/java/org/batfish/bdp/BdpEngine.java, line 431 at r1](https://reviewable.io:443/reviews/batfish/batfish/862#-L37DsKooUbsVIWYNOGZ:-L3FppV3hYyTDcS2qssZ:bb70dyk) ([raw file](https://github.com/batfish/batfish/blob/a2be82eb7e96166fb12ae47226f2b32c3502a6b6/projects/batfish/src/main/java/org/batfish/bdp/BdpEngine.java#L431)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

::initClusterIds?
</blockquote></details>

Moot

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/862)*

**Comment by dhalperi** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/862)*

**Comment by progwriter** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/862)*

**Comment by dhalperi** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/862)*

**Pull request merged**
