### PR TITLE
Traceroute2

### PR DESCRIPTION
**Pull request by ratulm**
Code copied from the old traceroute, which will eventually be deleted. Most functionality is being tested via ref tests; one junit test on Row construction. (Ideas/contributions on improving testing of this type of code welcome.)

### CODE REVIEW

**Comment by anothermattbrown** [comment]
Reviewed 4 of 4 files at r1.
Review status: 4 of 8 files reviewed, all discussions resolved (waiting on @anothermattbrown)

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1651#-LEtxyV26dLZKjknRGzJ:-LEtxyV26dLZKjknRGzK:b-8xzrqa) (no related file):*
Are the refs providing new coverage over the JUnit tests in `TracerouteAnswererTest` and `TracerouteEngineTest`? I can covert the refs to JUnit tests for whatever features we need to test.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1651)*

**Comment by anothermattbrown** [comment]
Reviewed 4 of 4 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1651)*

**Comment by anothermattbrown** [comment]
:lgtm:

---

Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1651#-:-LEu31BAC9KiqWjuG5nL:bnfp4nl)*

**Comment by ratulm** [comment]
Not sure what TracerouteEngine tests are covering. The Junit test I wrote checks that traceroute information to Row conversion is as expected. It does not cover the generation of the traceroute. If the Engine tests cover that, we don't need the ref tests.

**Pull request merged**
