### PR TITLE
IOS: Convert route-map-based NAT rules

### PR DESCRIPTION
**Pull request by corinaminer**
Same basic idea as ACL-based NAT rules. So far, only limited support for content of route-maps that are used in NAT rules. The rule will be ignored if the route-map has:
- deny clauses
- set lines
- match lines other than matching IPv4 ACLs
- references to undefined ACLs

### CODE REVIEW

**Review by progwriter — COMMENTED** [review]
> Reviewed 6 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6570)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoIosNatUtil.java, line 66 at r1](https://reviewable.io/reviews/batfish/batfish/6570#-MR75Epd5VXm6f2nnliF:-MR75Epe2-DfAajqhcMo:b9fl5o9) ([raw file](https://github.com/batfish/batfish/blob/126efffbab156a971c566f7ed65ca54ac5d27ea7/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoIosNatUtil.java#L66)):*
> ```Java
>     for (RouteMapClause clause : routeMap.getClauses().values()) {
>       if (clause.getAction() != LineAction.PERMIT) {
>         // TODO Support NAT rules referencing route-maps with deny clauses
> ```

can we surface these unsupported features somehow? if not in convert warnings, at least with error logs so we devs know when we encounter this?

**Review by progwriter — COMMENTED** [review]
> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6570)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6570)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @progwriter)

___
*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoIosNatUtil.java, line 66 at r1](https://reviewable.io/reviews/batfish/batfish/6570#-MR75Epd5VXm6f2nnliF:-MR7M288CdtB3u5owEBx:bxhot8a) ([raw file](https://github.com/batfish/batfish/blob/126efffbab156a971c566f7ed65ca54ac5d27ea7/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoIosNatUtil.java#L66)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

can we surface these unsupported features somehow? if not in convert warnings, at least with error logs so we devs know when we encounter this?
</blockquote></details>

yes, surfaced a bunch of warnings that cause NAT rules to be ignored.

**Review by progwriter — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6570)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
