### PR TITLE
Check Point Gateway: initial grammar and VS model skeleton

### PR DESCRIPTION
**Pull request by sfraint**
Add initial grammar and VS model skeleton for Check Point gateways.

----

Went ahead and changed the package organization a bit for these new files - now the grammar and representation are both under `vendor/<vendor_name>`.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 22 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7142)* status: all files reviewed, 2 unresolved discussions (waiting on @sfraint)

___
*[projects/batfish/pom.xml, line 310 at r1](https://reviewable.io/reviews/batfish/batfish/7142#-MdxrUdm1FfceswBimfT:-MdxrUdm1FfceswBimfU:b-kfkr1c) ([raw file](https://github.com/batfish/batfish/blob/556960fed7c2a9354acbf4dbd85641d338729426/projects/batfish/pom.xml#L310)):*
> ```
> **/check_point_gateway/grammar/*.g4
> ```
can probably do **/check_point_gateway/**/*.g4 to be simpler
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ConfigurationFormat.java, line 14 at r1](https://reviewable.io/reviews/batfish/batfish/7142#-MdxrsAY61ihSCHcs7sw:-MdxrsAY61ihSCHcs7sx:b8celkk) ([raw file](https://github.com/batfish/batfish/blob/556960fed7c2a9354acbf4dbd85641d338729426/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ConfigurationFormat.java#L14)):*
> ```Java
>   CISCO_ASA("cisco"),
>   CISCO_IOS("cisco"),
>   CISCO_IOS_XR("cisco"),
> ```

Add an entry to DeviceModel?

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7142)* status: 19 of 23 files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[projects/batfish/pom.xml, line 310 at r1](https://reviewable.io/reviews/batfish/batfish/7142#-MdxrUdm1FfceswBimfT:-MdxtsF5AL6WRFx6qrTD:bvnrpcm) ([raw file](https://github.com/batfish/batfish/blob/556960fed7c2a9354acbf4dbd85641d338729426/projects/batfish/pom.xml#L310)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> **/check_point_gateway/grammar/*.g4
> ```
can probably do **/check_point_gateway/**/*.g4 to be simpler
</blockquote></details>

updated
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ConfigurationFormat.java, line 14 at r1](https://reviewable.io/reviews/batfish/batfish/7142#-MdxrsAY61ihSCHcs7sw:-MdxttHtEpBC1H9amzUt:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/556960fed7c2a9354acbf4dbd85641d338729426/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ConfigurationFormat.java#L14)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Add an entry to DeviceModel?
</blockquote></details>

done

**Review by dhalperi — COMMENTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7142)* status: all files reviewed, 1 unresolved discussion (waiting on @sfraint)

___
*[projects/batfish/pom.xml, line 310 at r1](https://reviewable.io/reviews/batfish/batfish/7142#-MdxrUdm1FfceswBimfT:-Mdxul8G9IDoh51sgmv_:buaeocy) ([raw file](https://github.com/batfish/batfish/blob/556960fed7c2a9354acbf4dbd85641d338729426/projects/batfish/pom.xml#L310)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

updated
</blockquote></details>

This was meant to say `**/check_point_gateway/**/*.g4`, but I missed code font.

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7142)* status: 22 of 23 files reviewed, all discussions resolved (waiting on @dhalperi)

___
*[projects/batfish/pom.xml, line 310 at r1](https://reviewable.io/reviews/batfish/batfish/7142#-MdxrUdm1FfceswBimfT:-MdxvBry0hnAgpM4HOMK:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/556960fed7c2a9354acbf4dbd85641d338729426/projects/batfish/pom.xml#L310)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

This was meant to say `**/check_point_gateway/**/*.g4`, but I missed code font.
</blockquote></details>

done

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7142)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

**Pull request merged**
