### PR TITLE
Validate template

### PR DESCRIPTION
**Pull request by ratulm**
A command to validate templates by parsing them. Useful for testing templates.

### CODE REVIEW

**Comment by dhalperi** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish-client/src/main/java/org/batfish/client/Client.java, line 142 at r1](https://reviewable.io/reviews/batfish/batfish/1425#-LCoZWUH5W1WFh5Z6XjK:-LCoZWUH5W1WFh5Z6XjL:b-963v25) ([raw file](https://github.com/batfish/batfish/blob/2e6bd5ef197ec93118166906117c4752815851f9/projects/batfish-client/src/main/java/org/batfish/client/Client.java#L142)):*
> ```Java
>   private static final String STARTUP_FILE = ".batfishclientrc";
> 
>   public static void fillTemplate(
> ```

Please test this function (or its use in validation) with all the bugs you can think of. Here's some thoughts of mine:

- pass on valid template + args
- fail with useful error message on args missing
- fail with useful error message on extra args
- fail with useful error message on args in wrong place in the template.

etc.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1425)*

**Comment by arifogel** [comment]
Reviewed 3 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish-client/src/main/java/org/batfish/client/Client.java, line 142 at r1](https://reviewable.io/reviews/batfish/batfish/1425#-LCpDjR_E433Wi6g9Xob:-LCpDjRa14td3NggYmED:b-p1bd47) ([raw file](https://github.com/batfish/batfish/blob/2e6bd5ef197ec93118166906117c4752815851f9/projects/batfish-client/src/main/java/org/batfish/client/Client.java#L142)):*
> ```Java
>   private static final String STARTUP_FILE = ".batfishclientrc";
> 
>   public static void fillTemplate(
> ```

Javadoc please

---

*[projects/batfish-client/src/main/java/org/batfish/client/Command.java, line 355 at r1](https://reviewable.io/reviews/batfish/batfish/1425#-LCpDuAW0y5eKSutyWR0:-LCpDuAW0y5eKSutyWR1:bube94b) ([raw file](https://github.com/batfish/batfish/blob/2e6bd5ef197ec93118166906117c4752815851f9/projects/batfish-client/src/main/java/org/batfish/client/Command.java#L355)):*
> ```Java
>     descs.put(
>         VALIDATE_TEMPLATE,
>         new Pair<>("<template-file> [param1=value1 [param2=value2] ...]", "Validate the template"));
> ```

What does it mean to validate a template?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1425)*

**Comment by arifogel** [comment]
Reviewed 1 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1425)*

**Comment by ratulm** [comment]
Review status: 1 of 15 files reviewed at latest revision, 3 unresolved discussions.

---

*[projects/batfish-client/src/main/java/org/batfish/client/Client.java, line 142 at r1](https://reviewable.io/reviews/batfish/batfish/1425#-LCoZWUH5W1WFh5Z6XjK:-LCyYUxE9krUX4TPwCso:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/2e6bd5ef197ec93118166906117c4752815851f9/projects/batfish-client/src/main/java/org/batfish/client/Client.java#L142)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Please test this function (or its use in validation) with all the bugs you can think of. Here's some thoughts of mine:

- pass on valid template + args
- fail with useful error message on args missing
- fail with useful error message on extra args
- fail with useful error message on args in wrong place in the template.

etc.
</blockquote></details>

Done.

---

*[projects/batfish-client/src/main/java/org/batfish/client/Command.java, line 355 at r1](https://reviewable.io/reviews/batfish/batfish/1425#-LCpDuAW0y5eKSutyWR0:-LCyYSSr4v733Uy-GQ6Y:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/2e6bd5ef197ec93118166906117c4752815851f9/projects/batfish-client/src/main/java/org/batfish/client/Command.java#L355)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

What does it mean to validate a template?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1425)*

**Comment by ratulm** [comment]
Review status: 1 of 15 files reviewed at latest revision, 3 unresolved discussions.

---

*[projects/batfish-client/src/main/java/org/batfish/client/Client.java, line 142 at r1](https://reviewable.io/reviews/batfish/batfish/1425#-LCpDjR_E433Wi6g9Xob:-LCyYa2k9_jYj6YtmOaP:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/2e6bd5ef197ec93118166906117c4752815851f9/projects/batfish-client/src/main/java/org/batfish/client/Client.java#L142)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Javadoc please
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1425)*

**Comment by dhalperi** [comment]
:lgtm:

---

Reviewed 14 of 14 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1425#-:-LCyca4W7NR6Ozv1hUiA:bnfp4nl)*

**Comment by dhalperi** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1425)*

**Pull request merged**
