### PR TITLE
refactored traceroute and added tests

### PR DESCRIPTION
**Pull request by anothermattbrown**
New tests are currently failing; fixes haven't been implemented yet.

### CODE REVIEW

**Comment by progwriter** [comment]
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java, line 47 at r1](https://reviewable.io/reviews/batfish/batfish/1362#-LC74CIGCwGftE18dXK0:-LC74CIH8CpVA0aoJW4b:b-stj8dw) ([raw file](https://github.com/batfish/batfish/blob/cd418c95abcfbc6cffcfe69aa7179986b1b0a4bb/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java#L47)):*
> ```Java
>     private LineAction _defaultInboundAction;
> 
>     public Builder(NetworkFactory networkFactory) {
> ```

No need for visibility changes. One can access builders though `NetworkFactory.configurationBuilder()`
(Similar for Interface, Vrf) below

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1362)*

**Comment by anothermattbrown** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java, line 47 at r1](https://reviewable.io/reviews/batfish/batfish/1362#-LC74CIGCwGftE18dXK0:-LCAIOnr-8rwTQ5oGmX-:b-cjmhn2) ([raw file](https://github.com/batfish/batfish/blob/cd418c95abcfbc6cffcfe69aa7179986b1b0a4bb/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java#L47)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

No need for visibility changes. One can access builders though `NetworkFactory.configurationBuilder()`
(Similar for Interface, Vrf) below
</blockquote></details>

aha, thanks

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1362)*

**Comment by anothermattbrown** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java, line 47 at r1](https://reviewable.io/reviews/batfish/batfish/1362#-LC74CIGCwGftE18dXK0:-LCCKqi6-f3LWkUcw8LK:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/cd418c95abcfbc6cffcfe69aa7179986b1b0a4bb/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java#L47)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

aha, thanks
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1362)*

**Comment by progwriter** [comment]
Reviewed 1 of 6 files at r1, 11 of 19 files at r2.
Review status: 11 of 17 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java, line 293 at r2](https://reviewable.io/reviews/batfish/batfish/1362#-LCCtWE_E_8YOMSGdB0T:-LCCtWE_E_8YOMSGdB0U:bobmm48) ([raw file](https://github.com/batfish/batfish/blob/c7a9427504d07777b23ec4b2b420fa524ced7663/projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java#L293)):*
> ```Java
>     Map<String, Map<String, Set<Ip>>> ownedIps = new HashMap<>();
> 
>     ipInterfaceOwners.forEach(
> ```

I think it's easier to use `entrySet()` streams and collect directly to ImmutableMap in one go.  (E.g., https://github.com/batfish/batfish/blob/master/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java#L599)

---

*[projects/batfish/src/main/java/org/batfish/dataplane/TracerouteEngineImpl.java, line 119 at r2](https://reviewable.io/reviews/batfish/batfish/1362#-LCCsW7M2s6oqpI_7r-_:-LCCsW7M2s6oqpI_7r-a:b-lerjb) ([raw file](https://github.com/batfish/batfish/blob/c7a9427504d07777b23ec4b2b420fa524ced7663/projects/batfish/src/main/java/org/batfish/dataplane/TracerouteEngineImpl.java#L119)):*
> ```Java
>                     dataPlane.getFibs(),
>                     ingressNodeName,
>                     Configuration.DEFAULT_VRF_NAME,
> ```

Should this not be `flow.getIngressVrf()`? And only if that's unset, then fallback to default vrf? Seems unsafe to assume all flows start in default VRF.

---

*[projects/batfish/src/test/java/org/batfish/dataplane/TracerouteEngineTest.java, line 163 at r2](https://reviewable.io/reviews/batfish/batfish/1362#-LCCr7Pk2f0sMDsazrSG:-LCCr7Pl2P5GgYF1i9LS:bc6sbx5) ([raw file](https://github.com/batfish/batfish/blob/c7a9427504d07777b23ec4b2b420fa524ced7663/projects/batfish/src/test/java/org/batfish/dataplane/TracerouteEngineTest.java#L163)):*
> ```Java
>     // Compute data plane
>     SortedMap<String, Configuration> configs = ImmutableSortedMap.of(config.getHostname(), config);
>     TemporaryFolder tmp = new TemporaryFolder();
> ```

Crete a field `@Rule public TemporaryFolder _folder = new TemporaryFolder();` and temp folder will be automatically inited for all tests (see `DynamicBgpTest` as an example

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1362)*

**Comment by progwriter** [comment]
Reviewed 6 of 19 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1362)*

**Comment by anothermattbrown** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java, line 293 at r2](https://reviewable.io/reviews/batfish/batfish/1362#-LCCtWE_E_8YOMSGdB0T:-LCESR0fBOLiWGnv-3OM:biq59w6) ([raw file](https://github.com/batfish/batfish/blob/c7a9427504d07777b23ec4b2b420fa524ced7663/projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java#L293)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

I think it's easier to use `entrySet()` streams and collect directly to ImmutableMap in one go.  (E.g., https://github.com/batfish/batfish/blob/master/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java#L599)
</blockquote></details>

I don't think that works well here, because the new map doesn't have the same shape (wrt key structure) as the old one (unlike your example). 

---

*[projects/batfish/src/main/java/org/batfish/dataplane/TracerouteEngineImpl.java, line 119 at r2](https://reviewable.io/reviews/batfish/batfish/1362#-LCCsW7M2s6oqpI_7r-_:-LCEbJtD7rYrW4L1puPO:b-fe75uu) ([raw file](https://github.com/batfish/batfish/blob/c7a9427504d07777b23ec4b2b420fa524ced7663/projects/batfish/src/main/java/org/batfish/dataplane/TracerouteEngineImpl.java#L119)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

Should this not be `flow.getIngressVrf()`? And only if that's unset, then fallback to default vrf? Seems unsafe to assume all flows start in default VRF.
</blockquote></details>

good catch, thanks

---

*[projects/batfish/src/test/java/org/batfish/dataplane/TracerouteEngineTest.java, line 163 at r2](https://reviewable.io/reviews/batfish/batfish/1362#-LCCr7Pk2f0sMDsazrSG:-LCEX2RY1jv6Qc4Ja3I3:b-7xsw8z) ([raw file](https://github.com/batfish/batfish/blob/c7a9427504d07777b23ec4b2b420fa524ced7663/projects/batfish/src/test/java/org/batfish/dataplane/TracerouteEngineTest.java#L163)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

Crete a field `@Rule public TemporaryFolder _folder = new TemporaryFolder();` and temp folder will be automatically inited for all tests (see `DynamicBgpTest` as an example
</blockquote></details>

I'm not sure that's better in this case, because most tests in this class don't need a temp folder, and because we'd need to do `tmp.create` far from the object creation to complete the initialization. So instead I added a variant of `getBatfish` that creates the temp folder itself.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1362)*

**Comment by progwriter** [comment]
Reviewed 1 of 4 files at r3.
Review status: 15 of 18 files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java, line 293 at r2](https://reviewable.io/reviews/batfish/batfish/1362#-LCCtWE_E_8YOMSGdB0T:-LCFFGsQ9M94Dio-gBHW:bnnku9) ([raw file](https://github.com/batfish/batfish/blob/c7a9427504d07777b23ec4b2b420fa524ced7663/projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java#L293)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

I don't think that works well here, because the new map doesn't have the same shape (wrt key structure) as the old one (unlike your example). 
</blockquote></details>

Oh, gotcha. Sorry I was misreading the details.

---

*[projects/batfish/src/test/java/org/batfish/dataplane/TracerouteEngineTest.java, line 163 at r2](https://reviewable.io/reviews/batfish/batfish/1362#-LCCr7Pk2f0sMDsazrSG:-LCFEGzRBHy_h6HSyFPg:b-39igli) ([raw file](https://github.com/batfish/batfish/blob/c7a9427504d07777b23ec4b2b420fa524ced7663/projects/batfish/src/test/java/org/batfish/dataplane/TracerouteEngineTest.java#L163)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

I'm not sure that's better in this case, because most tests in this class don't need a temp folder, and because we'd need to do `tmp.create` far from the object creation to complete the initialization. So instead I added a variant of `getBatfish` that creates the temp folder itself.
</blockquote></details>

1) You don't need to use `tmp.create` (see https://junit.org/junit4/javadoc/4.12/org/junit/rules/TemporaryFolder.html#create())
2) I believe that it is the `@Rule` annotation which automatically cleans up the temp folder after the test finishes, which is a good reason to use it. In your current implementation cleanup would not occur. In my opinion, the cost hit per test is not significant enough to worry about it, even if some tests don't use it. 
3) Finally, if you feel like making it cleaner, split the tests into two classes. Seems like existing tests in this class can be moved out into `TracerouteNatTest` as it's all they really they deal with.

---

*[projects/batfish/src/test/java/org/batfish/main/BatfishTestUtils.java, line 179 at r3](https://reviewable.io/reviews/batfish/batfish/1362#-LCFGA6NCGYm7IpFS1uL:-LCFGA6NCGYm7IpFS1uM:b-drar1i) ([raw file](https://github.com/batfish/batfish/blob/0ba52c3df12b6d2ba2894e64f19c73eee905b73e/projects/batfish/src/test/java/org/batfish/main/BatfishTestUtils.java#L179)):*
> ```Java
>    * @return New Batfish instance
>    */
>   public static Batfish getBatfish(SortedMap<String, Configuration> configurations)
> ```

Don't believe this is necessary

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1362)*

**Comment by arifogel** [comment]
Reviewed 1 of 6 files at r1, 13 of 19 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/MockDataPlane.java, line 44 at r3](https://reviewable.io/reviews/batfish/batfish/1362#-LCFSYMIDM5xvw1yNOh3:-LCFSYMIDM5xvw1yNOh4:b-ze4hxx) ([raw file](https://github.com/batfish/batfish/blob/0ba52c3df12b6d2ba2894e64f19c73eee905b73e/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/MockDataPlane.java#L44)):*
> ```Java
> 
>     public MockDataPlane build() {
>       return new MockDataPlane(
> ```

Time to refactor the `MockDataPlane` constructor to accept just the builder instance. Let's avoid constructors with more than 4 args or so in future.

---

*[projects/batfish/src/main/java/org/batfish/dataplane/TracerouteEngineImpl.java, line 116 at r3](https://reviewable.io/reviews/batfish/batfish/1362#-LCFSom7-vEDfmFcmNPD:-LCFSom7-vEDfmFcmNPE:b-ew1tyg) ([raw file](https://github.com/batfish/batfish/blob/0ba52c3df12b6d2ba2894e64f19c73eee905b73e/projects/batfish/src/main/java/org/batfish/dataplane/TracerouteEngineImpl.java#L116)):*
> ```Java
>                     ignoreAcls);
>               } else {
>                 collectFlowTraces(
> ```

Optional: If you're brave, maybe refactor this function so we aren't passing so many things? 

---

*[projects/batfish/src/main/java/org/batfish/dataplane/TracerouteEngineImpl.java, line 285 at r3](https://reviewable.io/reviews/batfish/batfish/1362#-LCFTGeiDTiF-j3YH1sW:-LCFTGeiDTiF-j3YH1sX:b-58o41s) ([raw file](https://github.com/batfish/batfish/blob/0ba52c3df12b6d2ba2894e64f19c73eee905b73e/projects/batfish/src/main/java/org/batfish/dataplane/TracerouteEngineImpl.java#L285)):*
> ```Java
>             .getNextHopInterfaces(arpIp)
>             .isEmpty()
>         && iface.getAllAddresses().stream().noneMatch(addr -> addr.getPrefix().containsIp(arpIp));
> ```

Why this last bit? If it is meant to implement 3, it is insufficient. In particular, it only checks connected routes, but should apply to all routes.
Please make sure you have tests that exercise proxy-arp for both connected and dynamic routes in final version.

---

*[projects/batfish/src/test/resources/org/batfish/grammar/cisco/testrigs/bgp-dynamic-session-misconfigured/configs/r1, line 1 at r3](https://reviewable.io/reviews/batfish/batfish/1362#-LCFUOGD7Dk6hkitz5sv:-LCFUOGD7Dk6hkitz5sw:b-bnnvkx) ([raw file](https://github.com/batfish/batfish/blob/ecf38b7924ff1014ab2ecd76dc6c046fdc6a637a/projects/batfish/src/test/resources/org/batfish/grammar/cisco/testrigs/bgp-dynamic-session-misconfigured/configs/r1#L1)):*
> ```
> ! boot system flash:EOS.swi
> ```

This line you removed forces this config to be detected as Arista EOS. I believe that afterward it will be detected as IOS. Is this your intention?
One possible consequence is different default proxy-arp for interfaces.
Applies elsewhere as well.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1362)*

**Comment by progwriter** [comment]
*[projects/batfish/src/test/resources/org/batfish/grammar/cisco/testrigs/bgp-dynamic-session-misconfigured/configs/r1, line 1 at r3](https://reviewable.io/reviews/batfish/batfish/1362#-LCFUOGD7Dk6hkitz5sv:-LCFV2WuCXMXq7vaRSJE:b-pkfu1m) ([raw file](https://github.com/batfish/batfish/blob/ecf38b7924ff1014ab2ecd76dc6c046fdc6a637a/projects/batfish/src/test/resources/org/batfish/grammar/cisco/testrigs/bgp-dynamic-session-misconfigured/configs/r1#L1)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

This line you removed forces this config to be detected as Arista EOS. I believe that afterward it will be detected as IOS. Is this your intention?
One possible consequence is different default proxy-arp for interfaces.
Applies elsewhere as well.
</blockquote></details>

That was the intention. We had an offline discussion about this. It was my mistake originally that those lines snuck in. Configs were tested in GNS3 using Cisco devices, thus they should be cisco in batfish as well.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1362)*

**Comment by anothermattbrown** [comment]
Review status: 17 of 18 files reviewed at latest revision, 5 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/dataplane/TracerouteEngineImpl.java, line 116 at r3](https://reviewable.io/reviews/batfish/batfish/1362#-LCFSom7-vEDfmFcmNPD:-LCG1I0TCsaNqTdlFEmP:b-ayroo8) ([raw file](https://github.com/batfish/batfish/blob/0ba52c3df12b6d2ba2894e64f19c73eee905b73e/projects/batfish/src/main/java/org/batfish/dataplane/TracerouteEngineImpl.java#L116)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Optional: If you're brave, maybe refactor this function so we aren't passing so many things? 
</blockquote></details>

I'll leave that for a separate PR.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1362)*

**Comment by anothermattbrown** [comment]
Review status: 17 of 18 files reviewed at latest revision, 5 unresolved discussions.

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/MockDataPlane.java, line 44 at r3](https://reviewable.io/reviews/batfish/batfish/1362#-LCFSYMIDM5xvw1yNOh3:-LCG6btk81Fksz4LsiTX:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/0ba52c3df12b6d2ba2894e64f19c73eee905b73e/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/MockDataPlane.java#L44)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Time to refactor the `MockDataPlane` constructor to accept just the builder instance. Let's avoid constructors with more than 4 args or so in future.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1362)*

**Comment by anothermattbrown** [comment]
Review status: 15 of 17 files reviewed at latest revision, 4 unresolved discussions.

---

*[projects/batfish/src/test/java/org/batfish/dataplane/TracerouteEngineTest.java, line 163 at r2](https://reviewable.io/reviews/batfish/batfish/1362#-LCCr7Pk2f0sMDsazrSG:-LCGCcKX8vGI8_VYonbh:b-locel6) ([raw file](https://github.com/batfish/batfish/blob/c7a9427504d07777b23ec4b2b420fa524ced7663/projects/batfish/src/test/java/org/batfish/dataplane/TracerouteEngineTest.java#L163)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

1) You don't need to use `tmp.create` (see https://junit.org/junit4/javadoc/4.12/org/junit/rules/TemporaryFolder.html#create())
2) I believe that it is the `@Rule` annotation which automatically cleans up the temp folder after the test finishes, which is a good reason to use it. In your current implementation cleanup would not occur. In my opinion, the cost hit per test is not significant enough to worry about it, even if some tests don't use it. 
3) Finally, if you feel like making it cleaner, split the tests into two classes. Seems like existing tests in this class can be moved out into `TracerouteNatTest` as it's all they really they deal with.
</blockquote></details>

Ok thanks.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1362)*

**Comment by arifogel** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1362)*

**Comment by progwriter** [comment]
Reviewed 1 of 2 files at r6.
Review status: 19 of 20 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1362)*

**Comment by arifogel** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/test/java/org/batfish/dataplane/TracerouteEngineTest.java, line 224 at r5](https://reviewable.io/reviews/batfish/batfish/1362#-LCUtX9Z4w3LIIGifXCK:-LCVNymK0YWtlXnz2L6-:b-uoj6xw) ([raw file](https://github.com/batfish/batfish/blob/0e3bb49cb6c3c55aec576c412ac0e223df0470fb/projects/batfish/src/test/java/org/batfish/dataplane/TracerouteEngineTest.java#L224)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

I put the IP on i4 because we need to distinguish between when `i4` is the destination and when the route to the destination goes through `i4`. If I were to put addresses on the other interfaces, they would have subnets that don't include the arpIp. My understanding was that that case would be the same as for no address wrt arp replying. Is there a different behavior when the interface doesn't have an address? If yes, we need a test for that.
</blockquote></details>

I'm not sure an interface ever responds to ARP requests if it has no IP assigned. This should be tested in emulation.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1362)*

**Comment by arifogel** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/test/java/org/batfish/dataplane/TracerouteEngineTest.java, line 224 at r5](https://reviewable.io/reviews/batfish/batfish/1362#-LCUtX9Z4w3LIIGifXCK:-LCVOORH7yxN1HqYHDxG:brq60yw) ([raw file](https://github.com/batfish/batfish/blob/0e3bb49cb6c3c55aec576c412ac0e223df0470fb/projects/batfish/src/test/java/org/batfish/dataplane/TracerouteEngineTest.java#L224)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

I'm not sure an interface ever responds to ARP requests if it has no IP assigned. This should be tested in emulation.
</blockquote></details>

I should also note that at least for Batfish, we would not assume an adjacency between interfaces where one has no IP assigned. But again, this may not matter when using mocked structures.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1362)*

**Comment by progwriter** [comment]
Reviewed 1 of 3 files at r4, 3 of 5 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1362)*

**Comment by anothermattbrown** [comment]
Review status: 18 of 20 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/test/java/org/batfish/dataplane/TracerouteEngineTest.java, line 224 at r5](https://reviewable.io/reviews/batfish/batfish/1362#-LCUtX9Z4w3LIIGifXCK:-LCWGDVV4IbR9_mb40hK:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/0e3bb49cb6c3c55aec576c412ac0e223df0470fb/projects/batfish/src/test/java/org/batfish/dataplane/TracerouteEngineTest.java#L224)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

I should also note that at least for Batfish, we would not assume an adjacency between interfaces where one has no IP assigned. But again, this may not matter when using mocked structures.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1362)*

**Comment by arifogel** [comment]
Reviewed 2 of 2 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish/src/main/java/org/batfish/dataplane/TracerouteEngineImpl.java, line 275 at r7](https://reviewable.io/reviews/batfish/batfish/1362#-LCWHB4k4cB_I7yTGI9C:-LCWHB4k4cB_I7yTGI9D:b-hwv6hn) ([raw file](https://github.com/batfish/batfish/blob/a68c735025791427c4a569046bfc3bf9215b1e0a/projects/batfish/src/main/java/org/batfish/dataplane/TracerouteEngineImpl.java#L275)):*
> ```Java
>   static boolean interfaceRepliesToArpRequestForIp(Interface iface, Fib ifaceFib, Ip arpIp) {
>     // interfaces without addresses never reply
>     if (iface.getAllAddresses().isEmpty()) {
> ```

Is this case handled correctly for reachability?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1362)*

**Comment by arifogel** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1362#-:-LCZmxqL8XuRLJ1PZbDN:bnfp4nl)*

**Pull request merged**
