### PR TITLE
Checkpoint: Support vlan logical interfaces

### PR DESCRIPTION
**Pull request by corinaminer**

### CODE REVIEW

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7229)* status: 0 of 8 files reviewed, 4 unresolved discussions (waiting on @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java, line 178 at r1](https://reviewable.io/reviews/batfish/batfish/7229#-MgO-D500qyOozYMye4t:-MgO-D500qyOozYMye4u:b-k6felw) ([raw file](https://github.com/batfish/batfish/blob/9bbbcadd27ef3fcee920be9addab25a24d094d17/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java#L178)):*
> ```Java
> 
>     Optional<Integer> parentBondingGroupOpt = getParentBondingGroupNumber(iface);
>     if (parentBondingGroupOpt.isPresent()) {
> ```

todo: should state of the iface in the bonding group be preserved? Currently we do not `setActive` in this `if`, which means interfaces default to active if they're in bonding groups even if they're set to off in the config
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java, line 195 at r1](https://reviewable.io/reviews/batfish/batfish/7229#-MgO-_5p2NYSiumtKcxV:-MgO-_5p2NYSiumtKcxW:bk4cjy1) ([raw file](https://github.com/batfish/batfish/blob/9bbbcadd27ef3fcee920be9addab25a24d094d17/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java#L195)):*
> ```Java
> 
>     if (iface.getVlanId() != null) {
>       newIface.setVlan(iface.getVlanId());
> ```

todo: is this the right field to populate
___
*[projects/batfish/src/test/resources/org/batfish/vendor/check_point_gateway/grammar/testconfigs/vlan_interface, line 10 at r1](https://reviewable.io/reviews/batfish/batfish/7229#-MgO-gsO0YtWg0zDCOoB:-MgO-gsO0YtWg0zDCOoC:b-a2i9z3) ([raw file](https://github.com/batfish/batfish/blob/9bbbcadd27ef3fcee920be9addab25a24d094d17/projects/batfish/src/test/resources/org/batfish/vendor/check_point_gateway/grammar/testconfigs/vlan_interface#L10)):*
> ```
> #
> add bonding group 2 interface eth0
> add bonding group 3 interface eth1
> ```

todo: test a vlan in a bonding group where all the group members are inactive
___
*[projects/batfish/src/test/resources/org/batfish/vendor/check_point_gateway/grammar/testconfigs/vlan_interface, line 35 at r1](https://reviewable.io/reviews/batfish/batfish/7229#-MgO-svD4X6DsnDsCQfd:-MgO-svD4X6DsnDsCQfe:b-vyn8tr) ([raw file](https://github.com/batfish/batfish/blob/9bbbcadd27ef3fcee920be9addab25a24d094d17/projects/batfish/src/test/resources/org/batfish/vendor/check_point_gateway/grammar/testconfigs/vlan_interface#L35)):*
> ```
> set interface eth11.4093 state on
> set interface eth11.4093 ipv4-address 11.11.11.1 mask-length 24
> set interface eth12.4094 state off
> ```

todo: test property inheritance, e.g. bandwidth

**Review by dhalperi — COMMENTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7229)* status: all files reviewed, 5 unresolved discussions (waiting on @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java, line 195 at r1](https://reviewable.io/reviews/batfish/batfish/7229#-MgRojm93rrHU01YIqiT:-MgRojm93rrHU01YIqiU:b-2wpj9d) ([raw file](https://github.com/batfish/batfish/blob/9bbbcadd27ef3fcee920be9addab25a24d094d17/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java#L195)):*
> ```Java
> 
>     if (iface.getVlanId() != null) {
>       newIface.setVlan(iface.getVlanId());
> ```

no. enapsulation vlan

vlanid is for interface type vlan.

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7229)* status: all files reviewed, 4 unresolved discussions (waiting on @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java, line 195 at r1](https://reviewable.io/reviews/batfish/batfish/7229#-MgO-_5p2NYSiumtKcxV:-MgRoql1DZ9yIUthphaF:brvz19w) ([raw file](https://github.com/batfish/batfish/blob/9bbbcadd27ef3fcee920be9addab25a24d094d17/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java#L195)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

todo: is this the right field to populate
</blockquote></details>

whoops, responded wrong

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7229)* status: 6 of 8 files reviewed, all discussions resolved (waiting on @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java, line 178 at r1](https://reviewable.io/reviews/batfish/batfish/7229#-MgO-D500qyOozYMye4t:-MgSpVoC2HloByyr5uNR:bea50s1) ([raw file](https://github.com/batfish/batfish/blob/9bbbcadd27ef3fcee920be9addab25a24d094d17/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java#L178)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

todo: should state of the iface in the bonding group be preserved? Currently we do not `setActive` in this `if`, which means interfaces default to active if they're in bonding groups even if they're set to off in the config
</blockquote></details>

Looks right. You can't set the state of an interface in a bonding group, and if it's in `state off` when added to a bonding group, it automatically switches to `state on`.
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java, line 195 at r1](https://reviewable.io/reviews/batfish/batfish/7229#-MgRojm93rrHU01YIqiT:-MgS48ut53rUWQmdunsC:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/9bbbcadd27ef3fcee920be9addab25a24d094d17/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java#L195)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

no. enapsulation vlan

vlanid is for interface type vlan.
</blockquote></details>

done
___
*[projects/batfish/src/test/resources/org/batfish/vendor/check_point_gateway/grammar/testconfigs/vlan_interface, line 10 at r1](https://reviewable.io/reviews/batfish/batfish/7229#-MgO-gsO0YtWg0zDCOoB:-MgSq3EXBzWLSxsRWPa_:byb0p70) ([raw file](https://github.com/batfish/batfish/blob/9bbbcadd27ef3fcee920be9addab25a24d094d17/projects/batfish/src/test/resources/org/batfish/vendor/check_point_gateway/grammar/testconfigs/vlan_interface#L10)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

todo: test a vlan in a bonding group where all the group members are inactive
</blockquote></details>

No such thing; members of bonding groups are automatically active
___
*[projects/batfish/src/test/resources/org/batfish/vendor/check_point_gateway/grammar/testconfigs/vlan_interface, line 35 at r1](https://reviewable.io/reviews/batfish/batfish/7229#-MgO-svD4X6DsnDsCQfd:-MgSrU6Y9-VVtOLcMKjL:b-6gvwvu) ([raw file](https://github.com/batfish/batfish/blob/9bbbcadd27ef3fcee920be9addab25a24d094d17/projects/batfish/src/test/resources/org/batfish/vendor/check_point_gateway/grammar/testconfigs/vlan_interface#L35)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

todo: test property inheritance, e.g. bandwidth
</blockquote></details>

bandwidth test will have to wait until we add more support for physical interfaces' speeds. It does not appear that other properties are automatically inherited by bond or eth subinterfaces (checked on GNS3 for MTU).

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7229)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

**Pull request merged**
