### PR TITLE
Fix L2 bug: avoid extra trunk interface Layer2Nodes

### PR DESCRIPTION
**Pull request by corinaminer**

### CODE REVIEW

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6997)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @arifogel)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TopologyUtil.java, line 77 at r1](https://reviewable.io/reviews/batfish/batfish/6997#-M_bcOrM1N4fPwqLg80K:-M_bcOrM1N4fPwqLg80L:bpmt068) ([raw file](https://github.com/batfish/batfish/blob/03fa87014d6ed74f2f6df8b2b29e24c391991ab4/projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TopologyUtil.java#L77)):*
> ```Java
>       Consumer<Layer2Edge> edges,
>       Layer1Node l2Node1,
>       Layer1Node l2Node2,
> ```

fyi: renamed to reduce the chance of mixing up devices with L2 nodes, which is probably what led to `node1Ranges` and `node2Ranges` being used as if they were specific to `l2Node1` and `l2Node2` when in fact they're only specific to the L2 nodes' devices (not their interfaces).
___
*[projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/TopologyUtilTest.java, line 659 at r1](https://reviewable.io/reviews/batfish/batfish/6997#-M_bcye168t6IXv-SmKD:-M_bcye168t6IXv-SmKE:b-3vq6xx) ([raw file](https://github.com/batfish/batfish/blob/03fa87014d6ed74f2f6df8b2b29e24c391991ab4/projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/TopologyUtilTest.java#L659)):*
> ```Java
>     Layer2Node c2i1 = new Layer2Node(c2Name, i1Name, range1);
>     Layer2Node c2i2 = new Layer2Node(c2Name, i2Name, range2);
>     assertThat(layer2Topology.getNodes(), containsInAnyOrder(c1i1, c1i2, c2i1, c2i2));
> ```

fyi: in master this assertion fails, because there are extra Layer2Nodes of the form `new Layer2Node(c1Name, i1Name, range2)` -- that is, interfaces with VLAN ranges that shouldn't be associated with them. All the other assertions *pass* in master because they only assert on the nodes we expect to exist. that's why it was necessary to add the `getNodes()` api, to more robustly assert on what's in the `Layer2Topology`

**Review by arifogel — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6997)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TopologyUtil.java, line 77 at r1](https://reviewable.io/reviews/batfish/batfish/6997#-M_bcOrM1N4fPwqLg80K:-M_bdfAZ3RmVu_s4Ai-v:b-64yk6e) ([raw file](https://github.com/batfish/batfish/blob/03fa87014d6ed74f2f6df8b2b29e24c391991ab4/projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TopologyUtil.java#L77)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

fyi: renamed to reduce the chance of mixing up devices with L2 nodes, which is probably what led to `node1Ranges` and `node2Ranges` being used as if they were specific to `l2Node1` and `l2Node2` when in fact they're only specific to the L2 nodes' devices (not their interfaces).
</blockquote></details>

Gotcha, but these are `Layer1Node`s. Maybe call them `l1Node1` and `l1Node2`?
Or `i1L1Node` and `i2L1Node` or something like that?
___
*[projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/TopologyUtilTest.java, line 659 at r1](https://reviewable.io/reviews/batfish/batfish/6997#-M_bcye168t6IXv-SmKD:-M_be17M9cf1xjaJRv5X:b8eg0rd) ([raw file](https://github.com/batfish/batfish/blob/03fa87014d6ed74f2f6df8b2b29e24c391991ab4/projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/TopologyUtilTest.java#L659)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

fyi: in master this assertion fails, because there are extra Layer2Nodes of the form `new Layer2Node(c1Name, i1Name, range2)` -- that is, interfaces with VLAN ranges that shouldn't be associated with them. All the other assertions *pass* in master because they only assert on the nodes we expect to exist. that's why it was necessary to add the `getNodes()` api, to more robustly assert on what's in the `Layer2Topology`
</blockquote></details>

Right.
Not necessary, but if you want to add a test immune to future changes, you could put IRB interfaces on each device in each range, and make sure they don't have crossing L3 edges.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6997)* status: all files reviewed, 1 unresolved discussion (waiting on @corinaminer)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6997#-M_bfO2kEGauSlpohAXH:-M_bfO2kEGauSlpohAXI:bq3t1ma) (no related file):*
Resolve after addressing my replies to your informational comments.

---

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6997)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @arifogel)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TopologyUtil.java, line 77 at r1](https://reviewable.io/reviews/batfish/batfish/6997#-M_bcOrM1N4fPwqLg80K:-M_bfv7b-l6RSgs8bNFt:b-llho82) ([raw file](https://github.com/batfish/batfish/blob/03fa87014d6ed74f2f6df8b2b29e24c391991ab4/projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TopologyUtil.java#L77)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Gotcha, but these are `Layer1Node`s. Maybe call them `l1Node1` and `l1Node2`?
Or `i1L1Node` and `i2L1Node` or something like that?
</blockquote></details>

oh yeah lol
___
*[projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/TopologyUtilTest.java, line 659 at r1](https://reviewable.io/reviews/batfish/batfish/6997#-M_bcye168t6IXv-SmKD:-M_brCfGCg4CnwE-3C3w:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/03fa87014d6ed74f2f6df8b2b29e24c391991ab4/projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/TopologyUtilTest.java#L659)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Right.
Not necessary, but if you want to add a test immune to future changes, you could put IRB interfaces on each device in each range, and make sure they don't have crossing L3 edges.
</blockquote></details>

done

**Review by arifogel — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6997)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

___
*[projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/TopologyUtilTest.java, line 679 at r2](https://reviewable.io/reviews/batfish/batfish/6997#-M_bsx7-50ECh_bZIwMb:-M_bsx7-50ECh_bZIwMc:b7hn4no) ([raw file](https://github.com/batfish/batfish/blob/25f6ba22fa4321ca7e43b2f4f7da715619fcf8c9/projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/TopologyUtilTest.java#L679)):*
> ```Java
> 
>     // Pin down L2 topology: should have broadcast domains for VLANs 1 and 2.
>     // TODO: Why do L3 ifaces have entries both with and without a VLAN range? Is that necessary?
> ```

I addressed this as something to optimize out in an earlier offline conversation we had. We can fix this later, but shouldn't matter for now.

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6997)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

___
*[projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/TopologyUtilTest.java, line 679 at r2](https://reviewable.io/reviews/batfish/batfish/6997#-M_bsx7-50ECh_bZIwMb:-M_buS2QBuhQnBxAOAPS:bb7cwne) ([raw file](https://github.com/batfish/batfish/blob/25f6ba22fa4321ca7e43b2f4f7da715619fcf8c9/projects/batfish-common-protocol/src/test/java/org/batfish/common/topology/TopologyUtilTest.java#L679)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

I addressed this as something to optimize out in an earlier offline conversation we had. We can fix this later, but shouldn't matter for now.
</blockquote></details>

ack.

**Pull request merged**
