### PR TITLE
Add device type (host, router, or switch) to configurations

### PR DESCRIPTION
**Pull request by corinaminer**
Ignoring firewalls for now, and not attempting to identify devices as on a border. Let me know if the logic for identifying device type will work. Next step is to make this information available on the front end.

---
This change is [Reviewable](https://reviewable.io/reviews/batfish/batfish/661)

### CODE REVIEW

**Comment by progwriter** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java, line 272 at r1](https://reviewable.io:443/reviews/batfish/batfish/661#-KyXkpTHoybVLYmytSSi:-KyXkpTHoybVLYmytSSj:b-ffxn) ([raw file](https://github.com/batfish/batfish/blob/65ae0d8cc8807059651b22072dcef3a833898a77/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java#L272)):*
> ```Java
>       }
>       // If it's not a host and doesn't have BGP, OSPF, or RIP, it's a switch
>       _deviceType = DeviceType.SWITCH;
> ```

Wouldn't this override previously set `_deviceType`? Need to return after first successful setting of `_deviceType` in each case.

Also, consider having a separate UKNOWN device type? Unless you're absolutely sure you want to have anything un-identified flagged as a switch, and SWITCH won't be used for any specific purpose.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/661)*

**Comment by progwriter** [comment]
Logic looks fine. We now need two things, in order of priority: 1) Unit tests to ensure `getDeviceType` works as intended when creating `Configuration`s programmatically *and* parsing from files. 2) Updates to the refs since device type is now looks to be part of the datamodel. 

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/661#-:-KyXpTfcMjkSF5h7pO0a:b-7je2i6)*

**Comment by corinaminer** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java, line 272 at r1](https://reviewable.io:443/reviews/batfish/batfish/661#-KyXkpTHoybVLYmytSSi:-KyXoSMtp0ntOQOYrC3X:b-mm6v5g) ([raw file](https://github.com/batfish/batfish/blob/65ae0d8cc8807059651b22072dcef3a833898a77/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java#L272)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

Wouldn't this override previously set `_deviceType`? Need to return after first successful setting of `_deviceType` in each case.

Also, consider having a separate UKNOWN device type? Unless you're absolutely sure you want to have anything un-identified flagged as a switch, and SWITCH won't be used for any specific purpose.
</blockquote></details>

Good point on the return statements, just fixed.

Is there a test that could positively prove that a device *is* a switch? If so, I could add that test and set anything that doesn't pass to UNKNOWN.

I think the current version should be reasonably good at identifying switches, though, since there shouldn't be other devices without routing protocols. The "default" choice here ends up being routers. We'll eventually want to identify routing devices more carefully.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/661)*

**Comment by progwriter** [comment]
Followup: perhaps tests that parse files are not necessary, to avoid complicating things. Programmatic unit tests should suffice.  

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java, line 272 at r1](https://reviewable.io:443/reviews/batfish/batfish/661#-KyXkpTHoybVLYmytSSi:-KyXu2uKVWTxmDldfUCM:b-yp52i5) ([raw file](https://github.com/batfish/batfish/blob/65ae0d8cc8807059651b22072dcef3a833898a77/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java#L272)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Good point on the return statements, just fixed.

Is there a test that could positively prove that a device *is* a switch? If so, I could add that test and set anything that doesn't pass to UNKNOWN.

I think the current version should be reasonably good at identifying switches, though, since there shouldn't be other devices without routing protocols. The "default" choice here ends up being routers. We'll eventually want to identify routing devices more carefully.
</blockquote></details>

Switches can do VLAN tagging (as can routers I believe; but if it doesn't route, and has vlan tagging, it's probably a switch). I don't know if we currently track that with our parsing/configuration.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/661#-:-KyXuYANKLh3zBS3wjkl:bhurtju)*

**Comment by corinaminer** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java, line 272 at r1](https://reviewable.io:443/reviews/batfish/batfish/661#-KyXkpTHoybVLYmytSSi:-KyXwa8qCN9yYSNwwfkR:bsjyu6n) ([raw file](https://github.com/batfish/batfish/blob/65ae0d8cc8807059651b22072dcef3a833898a77/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java#L272)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

Switches can do VLAN tagging (as can routers I believe; but if it doesn't route, and has vlan tagging, it's probably a switch). I don't know if we currently track that with our parsing/configuration.
</blockquote></details>

Do all switches do VLAN tagging? I wouldn't want to identify all switches that don't do VLAN tagging as UNKNOWN. The ideal test would be something that all switches do, and maybe routers or hosts, but nothing else. (Though I imagine that if there were such a thing, you or Samir would already have told me.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/661)*

**Comment by progwriter** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java, line 272 at r1](https://reviewable.io:443/reviews/batfish/batfish/661#-KyXkpTHoybVLYmytSSi:-KyYhAM87Hd1CQFQLcud:baxmpi6) ([raw file](https://github.com/batfish/batfish/blob/65ae0d8cc8807059651b22072dcef3a833898a77/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java#L272)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Do all switches do VLAN tagging? I wouldn't want to identify all switches that don't do VLAN tagging as UNKNOWN. The ideal test would be something that all switches do, and maybe routers or hosts, but nothing else. (Though I imagine that if there were such a thing, you or Samir would already have told me.)
</blockquote></details>

You are right, it is conceivable that a switch will not have VLAN tagging configured. I suppose the way it stands now, if we mis-categorize some 'rare' device as a switch we're fine.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/661)*

**Comment by arifogel** [comment]
Changes required.

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java, line 257 at r2](https://reviewable.io:443/reviews/batfish/batfish/661#-KzBynoAPuhcsNMfH2C-:-KzBynoBaB67bE_OB5_w:bxotp6w) ([raw file](https://github.com/batfish/batfish/blob/aef5107dce270b86f667012786bd146efbcc7c9f/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java#L257)):*
> ```Java
>   }
> 
>   public DeviceType getDeviceType() {
> ```

This won't work without a corresponding `setDeviceType()` function. Jackson will barf deserializing Configuration JSON text that includes the `deviceType` field.
Furthermore, the user cannot manually set device type with this getter implementation. I would recommend setting the deviceType in the function that finalizes Configurations (don't remember it's name, but I think it does some OSPF interface cost setting), and just having a standard getter and setter for this.
Also, please make appropriate `PROP_XXX` constant and `JsonProperty(PROP_XXX)` annotations for the getter and setter.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/661#-:-KzBzORzcXXYU8Q9e-BC:bgvtebx)*

**Comment by arifogel** [comment]
Functionality looks fine.

Please switch to Builder pattern in tests. See my many comments. Look at OspfTest for usage examples.

---

Reviewed 9 of 9 files at r3.
Review status: all files reviewed at latest revision, 21 unresolved discussions.

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/DeviceTypeTest.java, line 15 at r3](https://reviewable.io:443/reviews/batfish/batfish/661#-L-Y2sjf9EjHm8guvErK:-L-Y2sjgk5Xdsoix6VsU:b16pye6) ([raw file](https://github.com/batfish/batfish/blob/886b214b367619be63a8f0438345a65531f68179/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/DeviceTypeTest.java#L15)):*
> ```Java
>   @Test
>   public void emptyConfigurationIsSwitch() {
>     Configuration c = new Configuration("hostname", ConfigurationFormat.CISCO_IOS);
> ```

Use `Configuration.Builder` instead of constructor. In this case particularly, it allows you to omit the hostname. All builders are accessible via `NetworkFactory`.

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/DeviceTypeTest.java, line 22 at r3](https://reviewable.io:443/reviews/batfish/batfish/661#-L-Y2zzGNZQ2bJt-IH0J:-L-Y2zzGNZQ2bJt-IH0K:bbawlgb) ([raw file](https://github.com/batfish/batfish/blob/886b214b367619be63a8f0438345a65531f68179/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/DeviceTypeTest.java#L22)):*
> ```Java
>   @Test
>   public void hostConfigIsHost() {
>     Configuration c = new Configuration("hostname", ConfigurationFormat.HOST);
> ```

Use `Configuration.Builder` instead of constructor. In this case particularly, it allows you to omit the hostname.

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/DeviceTypeTest.java, line 29 at r3](https://reviewable.io:443/reviews/batfish/batfish/661#-L-Y3-n_Ft3mNHSjpRFb:-L-Y3-n_Ft3mNHSjpRFc:bbawlgb) ([raw file](https://github.com/batfish/batfish/blob/886b214b367619be63a8f0438345a65531f68179/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/DeviceTypeTest.java#L29)):*
> ```Java
>   @Test
>   public void hostWithBgpIsHost() {
>     Configuration c = new Configuration("hostname", ConfigurationFormat.HOST);
> ```

Use `Configuration.Builder` instead of constructor. In this case particularly, it allows you to omit the hostname.

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/DeviceTypeTest.java, line 30 at r3](https://reviewable.io:443/reviews/batfish/batfish/661#-L-Y30P9tWsr_KVW27iX:-L-Y30P9tWsr_KVW27iY:b-cgg23b) ([raw file](https://github.com/batfish/batfish/blob/886b214b367619be63a8f0438345a65531f68179/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/DeviceTypeTest.java#L30)):*
> ```Java
>   public void hostWithBgpIsHost() {
>     Configuration c = new Configuration("hostname", ConfigurationFormat.HOST);
>     Vrf vrf = new Vrf("vrfName");
> ```

Use `Vrf.Builder` instead of constructor. In this case particularly, it allows you to omit the name and registration in `c.getVrfs()`.

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/DeviceTypeTest.java, line 32 at r3](https://reviewable.io:443/reviews/batfish/batfish/661#-L-Y3HtJZXlAfNFwSedl:-L-Y3HtJZXlAfNFwSedm:b-lthw6f) ([raw file](https://github.com/batfish/batfish/blob/886b214b367619be63a8f0438345a65531f68179/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/DeviceTypeTest.java#L32)):*
> ```Java
>     Vrf vrf = new Vrf("vrfName");
>     vrf.setBgpProcess(new BgpProcess());
>     c.getVrfs().put("sampleVrf", vrf);
> ```

redundant with builder

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/DeviceTypeTest.java, line 39 at r3](https://reviewable.io:443/reviews/batfish/batfish/661#-L-Y38uNtLkiOEiGU68j:-L-Y38uNtLkiOEiGU68k:b-vo9r0q) ([raw file](https://github.com/batfish/batfish/blob/886b214b367619be63a8f0438345a65531f68179/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/DeviceTypeTest.java#L39)):*
> ```Java
>   @Test
>   public void configWithFirstVrfEmptyIsRouter() {
>     Configuration c = new Configuration("hostname", ConfigurationFormat.CISCO_IOS);
> ```

builder

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/DeviceTypeTest.java, line 40 at r3](https://reviewable.io:443/reviews/batfish/batfish/661#-L-Y39iDWqmsSKosXKNR:-L-Y39iDWqmsSKosXKNS:b-vo9r0q) ([raw file](https://github.com/batfish/batfish/blob/886b214b367619be63a8f0438345a65531f68179/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/DeviceTypeTest.java#L40)):*
> ```Java
>   public void configWithFirstVrfEmptyIsRouter() {
>     Configuration c = new Configuration("hostname", ConfigurationFormat.CISCO_IOS);
>     Vrf emptyVrf = new Vrf("empty");
> ```

builder

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/DeviceTypeTest.java, line 41 at r3](https://reviewable.io:443/reviews/batfish/batfish/661#-L-Y3A6QusIgSzggrQAi:-L-Y3A6RtqQa_z9UZBy5:b-vo9r0q) ([raw file](https://github.com/batfish/batfish/blob/886b214b367619be63a8f0438345a65531f68179/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/DeviceTypeTest.java#L41)):*
> ```Java
>     Configuration c = new Configuration("hostname", ConfigurationFormat.CISCO_IOS);
>     Vrf emptyVrf = new Vrf("empty");
>     Vrf vrf = new Vrf("vrfName");
> ```

builder

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/DeviceTypeTest.java, line 42 at r3](https://reviewable.io:443/reviews/batfish/batfish/661#-L-Y3NJUh2WEkOwxPbHN:-L-Y3NJUh2WEkOwxPbHO:b-59o1my) ([raw file](https://github.com/batfish/batfish/blob/886b214b367619be63a8f0438345a65531f68179/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/DeviceTypeTest.java#L42)):*
> ```Java
>     Vrf emptyVrf = new Vrf("empty");
>     Vrf vrf = new Vrf("vrfName");
>     vrf.setBgpProcess(new BgpProcess());
> ```

redundant with builder. I.e. use `BgpProcess.Builder.setVrf(vrf).build()` I think.

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/DeviceTypeTest.java, line 43 at r3](https://reviewable.io:443/reviews/batfish/batfish/661#-L-Y3Frbk-R-hdasDvXU:-L-Y3Frbk-R-hdasDvXV:b-lthw6f) ([raw file](https://github.com/batfish/batfish/blob/886b214b367619be63a8f0438345a65531f68179/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/DeviceTypeTest.java#L43)):*
> ```Java
>     Vrf vrf = new Vrf("vrfName");
>     vrf.setBgpProcess(new BgpProcess());
>     c.getVrfs().put("emptyVrf", emptyVrf);
> ```

redundant with builder

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/DeviceTypeTest.java, line 44 at r3](https://reviewable.io:443/reviews/batfish/batfish/661#-L-Y3H9iYAVjB9hMXHaM:-L-Y3H9iYAVjB9hMXHaN:b-lthw6f) ([raw file](https://github.com/batfish/batfish/blob/886b214b367619be63a8f0438345a65531f68179/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/DeviceTypeTest.java#L44)):*
> ```Java
>     vrf.setBgpProcess(new BgpProcess());
>     c.getVrfs().put("emptyVrf", emptyVrf);
>     c.getVrfs().put("sampleVrf", vrf);
> ```

redundant with builder

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/DeviceTypeTest.java, line 51 at r3](https://reviewable.io:443/reviews/batfish/batfish/661#-L-Y3mihlXqkypDT7Rdn:-L-Y3mihlXqkypDT7Rdo:b-vo9r0q) ([raw file](https://github.com/batfish/batfish/blob/886b214b367619be63a8f0438345a65531f68179/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/DeviceTypeTest.java#L51)):*
> ```Java
>   @Test
>   public void configWithBgpIsRouter() {
>     Configuration c = new Configuration("hostname", ConfigurationFormat.CISCO_IOS);
> ```

builder

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/DeviceTypeTest.java, line 52 at r3](https://reviewable.io:443/reviews/batfish/batfish/661#-L-Y3nFEG10ql6LyNRF0:-L-Y3nFEG10ql6LyNRF1:b-vo9r0q) ([raw file](https://github.com/batfish/batfish/blob/886b214b367619be63a8f0438345a65531f68179/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/DeviceTypeTest.java#L52)):*
> ```Java
>   public void configWithBgpIsRouter() {
>     Configuration c = new Configuration("hostname", ConfigurationFormat.CISCO_IOS);
>     Vrf vrf = new Vrf("vrfName");
> ```

builder

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/DeviceTypeTest.java, line 53 at r3](https://reviewable.io:443/reviews/batfish/batfish/661#-L-Y3o1z2AOfRMKR3p-6:-L-Y3o1z2AOfRMKR3p-7:b-lthw6f) ([raw file](https://github.com/batfish/batfish/blob/886b214b367619be63a8f0438345a65531f68179/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/DeviceTypeTest.java#L53)):*
> ```Java
>     Configuration c = new Configuration("hostname", ConfigurationFormat.CISCO_IOS);
>     Vrf vrf = new Vrf("vrfName");
>     vrf.setBgpProcess(new BgpProcess());
> ```

redundant with builder

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/DeviceTypeTest.java, line 54 at r3](https://reviewable.io:443/reviews/batfish/batfish/661#-L-Y3pYyLJ_eyhk4rp-6:-L-Y3pYyLJ_eyhk4rp-7:b-lthw6f) ([raw file](https://github.com/batfish/batfish/blob/886b214b367619be63a8f0438345a65531f68179/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/DeviceTypeTest.java#L54)):*
> ```Java
>     Vrf vrf = new Vrf("vrfName");
>     vrf.setBgpProcess(new BgpProcess());
>     c.getVrfs().put("sampleVrf", vrf);
> ```

redundant with builder

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/DeviceTypeTest.java, line 63 at r3](https://reviewable.io:443/reviews/batfish/batfish/661#-L-Y3seciXUEUWnh4OIH:-L-Y3seciXUEUWnh4OII:bx5yqo8) ([raw file](https://github.com/batfish/batfish/blob/886b214b367619be63a8f0438345a65531f68179/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/DeviceTypeTest.java#L63)):*
> ```Java
>     Configuration c = new Configuration("hostname", ConfigurationFormat.CISCO_IOS);
>     Vrf vrf = new Vrf("vrfName");
>     vrf.setOspfProcess(new OspfProcess());
> ```

use builder / redundant with builder

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/DeviceTypeTest.java, line 64 at r3](https://reviewable.io:443/reviews/batfish/batfish/661#-L-Y3vyQNXdJXJ2QbDxY:-L-Y3vyQNXdJXJ2QbDxZ:b-lthw6f) ([raw file](https://github.com/batfish/batfish/blob/886b214b367619be63a8f0438345a65531f68179/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/DeviceTypeTest.java#L64)):*
> ```Java
>     Vrf vrf = new Vrf("vrfName");
>     vrf.setOspfProcess(new OspfProcess());
>     c.getVrfs().put("sampleVrf", vrf);
> ```

redundant with builder

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/DeviceTypeTest.java, line 71 at r3](https://reviewable.io:443/reviews/batfish/batfish/661#-L-Y3xXABlTGtiJSLH84:-L-Y3xXABlTGtiJSLH85:b-vo9r0q) ([raw file](https://github.com/batfish/batfish/blob/886b214b367619be63a8f0438345a65531f68179/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/DeviceTypeTest.java#L71)):*
> ```Java
>   @Test
>   public void configWithRipIsRouter() {
>     Configuration c = new Configuration("hostname", ConfigurationFormat.CISCO_IOS);
> ```

builder

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/DeviceTypeTest.java, line 72 at r3](https://reviewable.io:443/reviews/batfish/batfish/661#-L-Y3y560ooeDp4YCVwT:-L-Y3y560ooeDp4YCVwU:b-vo9r0q) ([raw file](https://github.com/batfish/batfish/blob/886b214b367619be63a8f0438345a65531f68179/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/DeviceTypeTest.java#L72)):*
> ```Java
>   public void configWithRipIsRouter() {
>     Configuration c = new Configuration("hostname", ConfigurationFormat.CISCO_IOS);
>     Vrf vrf = new Vrf("vrfName");
> ```

builder

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/DeviceTypeTest.java, line 73 at r3](https://reviewable.io:443/reviews/batfish/batfish/661#-L-Y3ypfSSkLwoNWv3R7:-L-Y3ypfSSkLwoNWv3R8:b-cqae1o) ([raw file](https://github.com/batfish/batfish/blob/886b214b367619be63a8f0438345a65531f68179/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/DeviceTypeTest.java#L73)):*
> ```Java
>     Configuration c = new Configuration("hostname", ConfigurationFormat.CISCO_IOS);
>     Vrf vrf = new Vrf("vrfName");
>     vrf.setRipProcess(new RipProcess());
> ```

builder / redundant with builder.. you might actually have to implement `RipProcess.Builder` for this one.

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/DeviceTypeTest.java, line 74 at r3](https://reviewable.io:443/reviews/batfish/batfish/661#-L-Y43mo2_0UTw_pKF3u:-L-Y43mo2_0UTw_pKF3v:b-lthw6f) ([raw file](https://github.com/batfish/batfish/blob/886b214b367619be63a8f0438345a65531f68179/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/DeviceTypeTest.java#L74)):*
> ```Java
>     Vrf vrf = new Vrf("vrfName");
>     vrf.setRipProcess(new RipProcess());
>     c.getVrfs().put("sampleVrf", vrf);
> ```

redundant with builder

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/661#-:-L-Y4KDoosA8BcVCinpj:b-d6rgi3)*

**Comment by corinaminer** [comment]
@arifogel I believe I've incorporated builders to the full extent dictated by your many comments.

---

Review status: 9 of 13 files reviewed at latest revision, 21 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/661#-:-L-YaNVuehY8GfvmWnpS:bxar01s)*

**Comment by arifogel** [comment]
Minor style changes requested.

---

Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/DeviceTypeTest.java, line 27 at r4](https://reviewable.io:443/reviews/batfish/batfish/661#-L-Yse0jZJAg8rCZF3m6:-L-Yse0jZJAg8rCZF3m7:b-p2kgc2) ([raw file](https://github.com/batfish/batfish/blob/96d3fcd1f727df5f78ad85ed5ce53a893517ce4a/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/DeviceTypeTest.java#L27)):*
> ```Java
>   @Test
>   public void emptyConfigurationIsSwitch() {
>     Configuration c = _cb.build();
> ```

Can calls to `_cb.setConfigurationFormat` elsewhere in this file affect the builder's configuration format here?

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/DeviceTypeTest.java, line 42 at r4](https://reviewable.io:443/reviews/batfish/batfish/661#-L-YrzRhzsBDTTbfgOf9:-L-YrzRhzsBDTTbfgOfA:b64rsgk) ([raw file](https://github.com/batfish/batfish/blob/96d3fcd1f727df5f78ad85ed5ce53a893517ce4a/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/DeviceTypeTest.java#L42)):*
> ```Java
>   @Test
>   public void hostConfigIsHost() {
>     Configuration c = this._cb.setConfigurationFormat(ConfigurationFormat.HOST).build();
> ```

For style consistency, please omit `this.` when referring to fields.

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/DeviceTypeTest.java, line 49 at r4](https://reviewable.io:443/reviews/batfish/batfish/661#-L-Ys6qga5CKQeiNl5yt:-L-Ys6qga5CKQeiNl5yu:b64rsgk) ([raw file](https://github.com/batfish/batfish/blob/96d3fcd1f727df5f78ad85ed5ce53a893517ce4a/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/DeviceTypeTest.java#L49)):*
> ```Java
>   @Test
>   public void hostWithBgpIsHost() {
>     Configuration c = this._cb.setConfigurationFormat(ConfigurationFormat.HOST).build();
> ```

For style consistency, please omit `this.` when referring to fields.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/661#-:-L-YtfJGGzJhncGRlSJE:b4g1r24)*

**Comment by corinaminer** [comment]
Review status: 12 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/DeviceTypeTest.java, line 27 at r4](https://reviewable.io:443/reviews/batfish/batfish/661#-L-Yse0jZJAg8rCZF3m6:-L-Yu13iTOKZ23ii5VzE:b-80spfe) ([raw file](https://github.com/batfish/batfish/blob/96d3fcd1f727df5f78ad85ed5ce53a893517ce4a/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/DeviceTypeTest.java#L27)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Can calls to `_cb.setConfigurationFormat` elsewhere in this file affect the builder's configuration format here?
</blockquote></details>

No, because `initializeBuilders()` reinitializes `_cb` before every test (thanks to the `@Before` tag).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/661)*

**Comment by arifogel** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/661#-:-L-YwnE-3PWNnau6xJwp:bnfp4nl)*

**Comment by dhalperi** [comment]
(When you have a PR where the individual commits are not semantically meaningful, please squash rather than merge the PR. It's not worth having 13 commits named things like "review comments" or "fix foo" in the final master branch.)

**Pull request merged**
