### PR TITLE
Cleanly rewrite static route handling for ibdp

### LINKED ISSUE #1375: ibdp: keep dependency information for static routes
In a case where a static route's next hop IP is reachable via a route that can be withdrawn (e.g., BGP, OSPF external) ibdp will not deactivate the route (i.e., remove from main RIB).
Seems like a corner case but we should definitely handle it.

### PR DESCRIPTION
**Pull request by progwriter**
Supersedes #1348 
Fixes #1375 
Implementation & tests for static route logic in ibdp.

### CODE REVIEW

**Comment by arifogel** [comment]
Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish/src/test/java/org/batfish/dataplane/protocols/StaticRouteHelperTest.java, line 52 at r1](https://reviewable.io/reviews/batfish/batfish/1466#-LD8rBIWDB4wsNPPtXhL:-LD8rBIXDYMMr1YPuz2u:bvc78od) ([raw file](https://github.com/batfish/batfish/blob/45df452af9e36e878e4a417e1b8675f0bed38bfe/projects/batfish/src/test/java/org/batfish/dataplane/protocols/StaticRouteHelperTest.java#L52)):*
> ```Java
> 
>     // Null interface + nextHopIp
>     sr = sb.setNextHopInterface(Interface.NULL_INTERFACE_NAME).setNextHopIp(someIp).build();
> ```

This particular case is invalid, since ARP is not performed on null interface. That is, there is no defined behavior to assert. Perhaps we want to prevent instantiation of such routes.

---

*[projects/batfish/src/test/java/org/batfish/dataplane/protocols/StaticRouteHelperTest.java, line 76 at r1](https://reviewable.io/reviews/batfish/batfish/1466#-LD8sWtDE6Z_QMchKjQK:-LD8sWtDE6Z_QMchKjQL:b-tz0ik3) ([raw file](https://github.com/batfish/batfish/blob/45df452af9e36e878e4a417e1b8675f0bed38bfe/projects/batfish/src/test/java/org/batfish/dataplane/protocols/StaticRouteHelperTest.java#L76)):*
> ```Java
>   public void testShouldActivateNoMatch() {
>     Ip nextHop = new Ip("1.1.1.1");
>     _rib.mergeRoute(new ConnectedRoute(Prefix.parse("1.1.1.2/32"), "Eth0"));
> ```

Using a 32-bit prefix here (and in your other tests) is super-confusing. Is this even allowed? Even if so, it seems like a corner case.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1466)*

**Comment by arifogel** [comment]
Reviewed 3 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1466)*

**Comment by progwriter** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish/src/test/java/org/batfish/dataplane/protocols/StaticRouteHelperTest.java, line 52 at r1](https://reviewable.io/reviews/batfish/batfish/1466#-LD8rBIWDB4wsNPPtXhL:-LD9GhT-3-56rJHhTXZk:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/45df452af9e36e878e4a417e1b8675f0bed38bfe/projects/batfish/src/test/java/org/batfish/dataplane/protocols/StaticRouteHelperTest.java#L52)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

This particular case is invalid, since ARP is not performed on null interface. That is, there is no defined behavior to assert. Perhaps we want to prevent instantiation of such routes.
</blockquote></details>

Done.

---

*[projects/batfish/src/test/java/org/batfish/dataplane/protocols/StaticRouteHelperTest.java, line 76 at r1](https://reviewable.io/reviews/batfish/batfish/1466#-LD8sWtDE6Z_QMchKjQK:-LD9Ght87U_X4tFqwthG:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/45df452af9e36e878e4a417e1b8675f0bed38bfe/projects/batfish/src/test/java/org/batfish/dataplane/protocols/StaticRouteHelperTest.java#L76)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Using a 32-bit prefix here (and in your other tests) is super-confusing. Is this even allowed? Even if so, it seems like a corner case.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1466)*

**Comment by progwriter** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[projects/batfish/src/test/java/org/batfish/dataplane/protocols/StaticRouteHelperTest.java, line 52 at r1](https://reviewable.io/reviews/batfish/batfish/1466#-LD8rBIWDB4wsNPPtXhL:-LD9MeEC311-kQaRBdBT:b-x90z1z) ([raw file](https://github.com/batfish/batfish/blob/45df452af9e36e878e4a417e1b8675f0bed38bfe/projects/batfish/src/test/java/org/batfish/dataplane/protocols/StaticRouteHelperTest.java#L52)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

What is the change addressing this comment?
</blockquote></details>

Sorry, didn't mean to click done. 
Tested this in GNS3, looks like the route is installed. Do we need special handling for this in FibImpl?

---

*[projects/batfish/src/test/java/org/batfish/dataplane/protocols/StaticRouteHelperTest.java, line 170 at r2](https://reviewable.io/reviews/batfish/batfish/1466#-LD9JhOIAH5UmRKKcJAd:-LD9LyYE2mi_8An5ShDo:b9ea5un) ([raw file](https://github.com/batfish/batfish/blob/56c0cf051557a61237b319f5a437c6e57220dfb2/projects/batfish/src/test/java/org/batfish/dataplane/protocols/StaticRouteHelperTest.java#L170)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Just a note that this precondition seems implausible, since 2.2.2/0 would not have been installed without a route to `9.9.9.9`. But if beforehand you augment it with a route for `9.9.9.9` that is not loopy, then I could see this happening.  I assume you've verified that the loopy one gets installed in practice.

I hope we have handling in fib resolution that avoids crashing on this loop.
</blockquote></details>

It does get installed in practice (at least on Ios).
You could have a more specific route to 9.9.9.9 (e.g., /31) that triggers the base case install.

Currently it looks like we will crash in FIB resolution. I can fix that.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1466)*

**Comment by arifogel** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[projects/batfish/src/test/java/org/batfish/dataplane/protocols/StaticRouteHelperTest.java, line 52 at r1](https://reviewable.io/reviews/batfish/batfish/1466#-LD8rBIWDB4wsNPPtXhL:-LD9PCWd-LZH54k_U4HR:b2ywf0g) ([raw file](https://github.com/batfish/batfish/blob/45df452af9e36e878e4a417e1b8675f0bed38bfe/projects/batfish/src/test/java/org/batfish/dataplane/protocols/StaticRouteHelperTest.java#L52)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

Sorry, didn't mean to click done. 
Tested this in GNS3, looks like the route is installed. Do we need special handling for this in FibImpl?
</blockquote></details>

I don't think it will have an impact. We can leave test as is for now.

---

*[projects/batfish/src/test/java/org/batfish/dataplane/protocols/StaticRouteHelperTest.java, line 170 at r2](https://reviewable.io/reviews/batfish/batfish/1466#-LD9JhOIAH5UmRKKcJAd:-LD9PM3ABLkzU46lZl3l:b-yn1xr3) ([raw file](https://github.com/batfish/batfish/blob/56c0cf051557a61237b319f5a437c6e57220dfb2/projects/batfish/src/test/java/org/batfish/dataplane/protocols/StaticRouteHelperTest.java#L170)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

It does get installed in practice (at least on Ios).
You could have a more specific route to 9.9.9.9 (e.g., /31) that triggers the base case install.

Currently it looks like we will crash in FIB resolution. I can fix that.


</blockquote></details>

Defer to future PR.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1466)*

**Comment by progwriter** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/test/java/org/batfish/dataplane/protocols/StaticRouteHelperTest.java, line 122 at r2](https://reviewable.io/reviews/batfish/batfish/1466#-LD9IsSs-odoBuzBiJYG:-LD9QEiC2HG5MQRHgosn:b8w8qjk) ([raw file](https://github.com/batfish/batfish/blob/56c0cf051557a61237b319f5a437c6e57220dfb2/projects/batfish/src/test/java/org/batfish/dataplane/protocols/StaticRouteHelperTest.java#L122)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

I don't see a route to the next-hop IP. That is, `1.1.1.1` is not routable in this test.
</blockquote></details>

Good catch, thanks. Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1466)*

**Comment by arifogel** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1466#-:-LD9RAdwATeYGXdug8eV:bnfp4nl)*

**Pull request merged**
