### PR TITLE
Fix (non)transitNodes in reachability query

### LINKED ISSUE #993: Fix (not)TransitNodes in reachability query
Adding support for NAT in reachability queries has broken the implementation of transitNodes and notTransitNodes constraints.

### PR DESCRIPTION
**Pull request by anothermattbrown**
Fixes #993

We add two new single-bit fields to the NOD programs, one to track transited transitNodes and one to track transited nonTransitNodes. If any specified (non) transit node is transited (i.e. we enter a `PostOutEdge` state for which the outgoing interface belongs to the node), we set the bit.

We conditionally add two new SMT constraints: if the set of transit nodes is non-empty, require the transitNodes bit to be set. If the set of non-transit nodes is non-empty, require the nonTransitNodes bit to not be set.

### CODE REVIEW

**Comment by dhalperi** [comment]
CC: @jkhourybbn  -- this fixes 1-hop waypointing that I believe you wanted.

**Comment by arifogel** [comment]
Reviewed 6 of 12 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish/src/main/java/org/batfish/z3/StandardReachabilityQuerySynthesizer.java, line 231 at r2](https://reviewable.io/reviews/batfish/batfish/1241#-LAzWMUr6ttEJMeRyv3K:-LAzWMUr6ttEJMeRyv3L:b-hpvvyl) ([raw file](https://github.com/batfish/batfish/blob/d1f9e2b2a2c09f27500cb3e15b0d0ea9c084ea65/projects/batfish/src/main/java/org/batfish/z3/StandardReachabilityQuerySynthesizer.java#L231)):*
> ```Java
>             ? TrueExpr.INSTANCE
>             : new EqExpr(
>                 new VarIntExpr(input.getTransitedTransitNodesField()), new LitIntExpr(1, 1));
> ```

It would be clearer and more maintainable if  `LitIntExpr(1,1)` were an appropriately named constant. Same goes for below. You use this in a bunch of places in this PR.

---

*[projects/batfish/src/main/java/org/batfish/z3/SynthesizerInputImpl.java, line 52 at r2](https://reviewable.io/reviews/batfish/batfish/1241#-LAzVvQy5l4gzEXvgJMx:-LAzVvQy5l4gzEXvgJMy:b-vd7op5) ([raw file](https://github.com/batfish/batfish/blob/d1f9e2b2a2c09f27500cb3e15b0d0ea9c084ea65/projects/batfish/src/main/java/org/batfish/z3/SynthesizerInputImpl.java#L52)):*
> ```Java
>   static final String TRANSITED_TRANSIT_NODES_FIELD_NAME = "TRANSITED_NODES";
> 
>   static final String TRANSITED_NON_TRANSIT_NODES_FIELD_NAME = "NON_TRANSIT_NODES";
> ```

This field name is not consistent with the one above.

---

*[projects/batfish/src/main/java/org/batfish/z3/SynthesizerInputImpl.java, line 172 at r2](https://reviewable.io/reviews/batfish/batfish/1241#-LAzWBJo2oydibFxFwpi:-LAzWBJo2oydibFxFwpj:bj64s6s) ([raw file](https://github.com/batfish/batfish/blob/d1f9e2b2a2c09f27500cb3e15b0d0ea9c084ea65/projects/batfish/src/main/java/org/batfish/z3/SynthesizerInputImpl.java#L172)):*
> ```Java
> 
>     public Builder setNonTransitNodes(Set<String> nonTransitNodes) {
>       _nonTransitNodes = nonTransitNodes;
> ```

immutable copy like for transitnodes please

---

*[projects/batfish/src/main/java/org/batfish/z3/SynthesizerInputImpl.java, line 359 at r2](https://reviewable.io/reviews/batfish/batfish/1241#-LAzWifs1F8qXddFDaDX:-LAzWifs1F8qXddFDaDY:b-2ijwyi) ([raw file](https://github.com/batfish/batfish/blob/d1f9e2b2a2c09f27500cb3e15b0d0ea9c084ea65/projects/batfish/src/main/java/org/batfish/z3/SynthesizerInputImpl.java#L359)):*
> ```Java
>   private Field computeTransitedTransitNodesField() {
>     /* Need a bit for each transit node */
>     return new Field(TRANSITED_TRANSIT_NODES_FIELD_NAME, 1);
> ```

This implementation doesn't really match the comment. This is exactly 1 bit independently of how many transit nodes there are. Same goes for below.

---

*[tests/basic/example-iptables-transit.ref, line 3 at r2](https://reviewable.io/reviews/batfish/batfish/1241#-LAzYF639XOhdZWSuIYe:-LAzYF639XOhdZWSuIYf:b-fqsjnr) ([raw file](https://github.com/batfish/batfish/blob/d1f9e2b2a2c09f27500cb3e15b0d0ea9c084ea65/tests/basic/example-iptables-transit.ref#L3)):*
> ```
> [
>   {
>     "class" : "org.batfish.datamodel.FlowHistory"
> ```

Is this intentional?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1241)*

**Comment by arifogel** [comment]
Reviewed 6 of 7 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1241)*

**Comment by anothermattbrown** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[projects/batfish/src/main/java/org/batfish/z3/StandardReachabilityQuerySynthesizer.java, line 231 at r2](https://reviewable.io/reviews/batfish/batfish/1241#-LAzWMUr6ttEJMeRyv3K:-LB2zIUy8q-nqKP1xZsJ:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/d1f9e2b2a2c09f27500cb3e15b0d0ea9c084ea65/projects/batfish/src/main/java/org/batfish/z3/StandardReachabilityQuerySynthesizer.java#L231)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

It would be clearer and more maintainable if  `LitIntExpr(1,1)` were an appropriately named constant. Same goes for below. You use this in a bunch of places in this PR.
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/z3/SynthesizerInputImpl.java, line 52 at r2](https://reviewable.io/reviews/batfish/batfish/1241#-LAzVvQy5l4gzEXvgJMx:-LB2zKOu4BiBdQrg0k7H:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/d1f9e2b2a2c09f27500cb3e15b0d0ea9c084ea65/projects/batfish/src/main/java/org/batfish/z3/SynthesizerInputImpl.java#L52)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

This field name is not consistent with the one above.
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/z3/SynthesizerInputImpl.java, line 172 at r2](https://reviewable.io/reviews/batfish/batfish/1241#-LAzWBJo2oydibFxFwpi:-LB2zLUt2p6sVmvqXL-K:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/d1f9e2b2a2c09f27500cb3e15b0d0ea9c084ea65/projects/batfish/src/main/java/org/batfish/z3/SynthesizerInputImpl.java#L172)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

immutable copy like for transitnodes please
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/z3/SynthesizerInputImpl.java, line 359 at r2](https://reviewable.io/reviews/batfish/batfish/1241#-LAzWifs1F8qXddFDaDX:-LB2zMo10_37u88cHLwW:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/d1f9e2b2a2c09f27500cb3e15b0d0ea9c084ea65/projects/batfish/src/main/java/org/batfish/z3/SynthesizerInputImpl.java#L359)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

This implementation doesn't really match the comment. This is exactly 1 bit independently of how many transit nodes there are. Same goes for below.
</blockquote></details>

Done.

---

*[tests/basic/example-iptables-transit.ref, line 3 at r2](https://reviewable.io/reviews/batfish/batfish/1241#-LAzYF639XOhdZWSuIYe:-LB2zPYM8jg66PT12WrC:b7fvoza) ([raw file](https://github.com/batfish/batfish/blob/d1f9e2b2a2c09f27500cb3e15b0d0ea9c084ea65/tests/basic/example-iptables-transit.ref#L3)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Is this intentional?
</blockquote></details>

yes, because the previous revision was before `-compareall` was introduced, and we don't want to use `-compareall`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1241)*

**Comment by arifogel** [comment]
Reviewed 7 of 8 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1241)*

**Comment by arifogel** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1241#-:-LB3-uZU7p0QJ9JTK0QC:bnfp4nl)*

**Comment by anothermattbrown** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1241)*

**Pull request merged**
