### PR TITLE
Arista: redo and simplify ACL logic

### PR DESCRIPTION
**Pull request by dhalperi**
After #6758 

Arista ACLs are much simpler than IOS ACLs.

* Move them into LL1 part of the grammar
* Rewrite standard ACL from scratch
* Shallow extension of extended ACL
* Rename structure type to be more accurate
* Simplify VS model
* Delete eth and session-type ACLs
* Delete support for things like DCP, ECNs, type-from-acl-number
* Structure Legacy_acl.g4 to identify what's been ported and what hasn't
* Add support for out-of-order lines
* Delete a bunch of grammar for pseudo-tokens that aren't used
* Minor cleanup to community lists to not break them

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6761)* status: 4 of 22 files reviewed, all discussions resolved (waiting on @arifogel and @dhalperi)

**Review by arifogel — COMMENTED** [review]
> Reviewed 18 of 18 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6761)* status: 8 of 23 files reviewed, 1 unresolved discussion (waiting on @arifogel and @dhalperi)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/arista/Legacy_acl.g4, line 813 at r2](https://reviewable.io/reviews/batfish/batfish/6761#-MWQPQcv9TBPfT7nwZkY:-MWQPQcv9TBPfT7nwZkZ:bs35wm8) ([raw file](https://github.com/batfish/batfish/blob/710cd9985804e5cb764728478f2523082a76ebc5/projects/batfish/src/main/antlr4/org/batfish/grammar/arista/Legacy_acl.g4#L813)):*
> ```ANTLR
>   | aclstd_fragment_rules
>   | aclstd_no
>   // | aclstd_requence
> ```

I know it's commented, but `requence`?

**Review by arifogel — COMMENTED** [review]
> Reviewed 9 of 9 files at r1, 1 of 1 files at r3, 1 of 1 files at r4, 3 of 3 files at r5, 4 of 4 files at r6, 6 of 6 files at r7, 3 of 3 files at r8, 4 of 4 files at r9, 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6761)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6761)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
