### PR TITLE
Updates to RoutingStep and related classes for NextHopVtep routes

### PR DESCRIPTION
**Pull request by arifogel**

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
-reviewer:@corinaminer 

> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7857#-:-MrUqM-M3MDIOJL3l8C5:b-yw8lxy)* status: 0 of 21 files reviewed, all discussions resolved (waiting on @sfraint)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 12 of 21 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7857)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/traceroute/TracerouteUtils.java, line 99 at r2](https://reviewable.io/reviews/batfish/batfish/7857#-MrxLrPo6z0roAsHCT9t:-MrxLrPp4pP3NvSDrrjG:b-a3eks7) ([raw file](https://github.com/batfish/batfish/blob/73a2db2bc8f0d28f2d79960880f12ffa58a53e03/projects/batfish/src/main/java/org/batfish/dataplane/traceroute/TracerouteUtils.java#L99)):*
> ```Java
>                     route.getNextHop(),
>                     route.getNextHopIp(),
>                     AbstractRoute.NEXT_VRF_EXTRACTOR.visit(route.getNextHop()),
> ```

delete these arguments, derive from NextHop if needed internally?



_Code quote:_
```Java
                    route.getNextHopIp(),
                    AbstractRoute.NEXT_VRF_EXTRACTOR.visit(route.getNextHop()),
```

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7857)* status: 15 of 22 files reviewed, all discussions resolved (waiting on @dhalperi and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/traceroute/TracerouteUtils.java, line 99 at r2](https://reviewable.io/reviews/batfish/batfish/7857#-MrxLrPo6z0roAsHCT9t:-Mrxo_964CTPccOICgHO:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/73a2db2bc8f0d28f2d79960880f12ffa58a53e03/projects/batfish/src/main/java/org/batfish/dataplane/traceroute/TracerouteUtils.java#L99)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

delete these arguments, derive from NextHop if needed internally?
</blockquote></details>

done

**Review by dhalperi — COMMENTED** [review]
> Reviewed 5 of 7 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7857)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

**Pull request merged**
