### PR TITLE
palo alto implement move in preprocessor

### PR DESCRIPTION
**Pull request by arifogel**
- generalize `PreprocessJuniperXXX` to `PreprocessXXX`
- add preprocessor implementation of move for Palo Alto
- minor related Juniper preprocessor fixup

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, 6 of 6 files at r2, 3 of 3 files at r3, 4 of 4 files at r4, 5 of 5 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6642)* status: all files reviewed, 4 unresolved discussions (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/job/PreprocessJob.java, line 75 at r2](https://reviewable.io/reviews/batfish/batfish/6642#-MTrYluCCjRwV5h4EIoV:-MTrYluCCjRwV5h4EIoW:bq5haoo) ([raw file](https://github.com/batfish/batfish/blob/2cda13a63e5da40cf8f2bdfc9fb28d99eb3fe365/projects/batfish/src/main/java/org/batfish/job/PreprocessJob.java#L75)):*
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>

> ```
>       case JUNIPER:
>         header =
>             firstNonNull(
>                 header, VendorConfigurationFormatDetector.BATFISH_FLATTENED_JUNIPER_HEADER);
>       case PALO_ALTO_NESTED:
>         header =
>             firstNonNull(
>                 header, VendorConfigurationFormatDetector.BATFISH_FLATTENED_PALO_ALTO_HEADER);
>         {
> ```
</details>

oh this fallthrough + firstNonNull is quite the abuse of syntax, yes? I guess Maven complained about this too.

Would it be simpler to:

1) abandon switch statements, they're not adding any value here and actually make the code less clear (e.g., unreachable default statements, etc).
2) Streamline code with no-op flatteners and preprocessors, so all vendors can follow the same path?
3) Clean up some of the APIs? (e.g., why are there two function calls to either flattener or the new preprocessor? Seems like they're really one call: do this, give me the result. We never call `flatten` twice, we never call `processParseTree` twice.
___
*[projects/batfish/src/main/java/org/batfish/job/PreprocessJob.java, line 125 at r2](https://reviewable.io/reviews/batfish/batfish/6642#-MTra1glA_GjCxQkkk42:-MTra1glA_GjCxQkkk43:b5gehar) ([raw file](https://github.com/batfish/batfish/blob/2cda13a63e5da40cf8f2bdfc9fb28d99eb3fe365/projects/batfish/src/main/java/org/batfish/job/PreprocessJob.java#L125)):*
> ```
> IllegalArgumentException
> ```
This is `IllegalStateException`, right? No parameters are wrong, rather the internal consistency of this function is violated.
___
*[projects/batfish/src/main/java/org/batfish/main/Preprocess.java, line 48 at r2](https://reviewable.io/reviews/batfish/batfish/6642#-MTrZ9a09qk7FoHR-lQz:-MTrZ9a09qk7FoHR-lR-:bkahj5c) ([raw file](https://github.com/batfish/batfish/blob/2cda13a63e5da40cf8f2bdfc9fb28d99eb3fe365/projects/batfish/src/main/java/org/batfish/main/Preprocess.java#L48)):*
> ```
> Non-preprocessible configs are copied unprocessed.
> ```
"Depending on vendor, pre-processing may be a no-op"?
___
*[projects/batfish/src/test/java/org/batfish/main/PreprocessTest.java, line 74 at r2](https://reviewable.io/reviews/batfish/batfish/6642#-MTrZMma7O-C4FQncs3z:-MTrZMma7O-C4FQncs4-:b-9z507e) ([raw file](https://github.com/batfish/batfish/blob/2cda13a63e5da40cf8f2bdfc9fb28d99eb3fe365/projects/batfish/src/test/java/org/batfish/main/PreprocessTest.java#L74)):*
> ```
> testNonJuniper
> ```
NoOp?

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6642)* status: 15 of 21 files reviewed, 2 unresolved discussions (waiting on @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/job/PreprocessJob.java, line 75 at r2](https://reviewable.io/reviews/batfish/batfish/6642#-MTrYluCCjRwV5h4EIoV:-MTrf9Nl4wuybuhzP9HN:b-k892af) ([raw file](https://github.com/batfish/batfish/blob/2cda13a63e5da40cf8f2bdfc9fb28d99eb3fe365/projects/batfish/src/main/java/org/batfish/job/PreprocessJob.java#L75)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
>       case JUNIPER:
>         header =
>             firstNonNull(
>                 header, VendorConfigurationFormatDetector.BATFISH_FLATTENED_JUNIPER_HEADER);
>       case PALO_ALTO_NESTED:
>         header =
>             firstNonNull(
>                 header, VendorConfigurationFormatDetector.BATFISH_FLATTENED_PALO_ALTO_HEADER);
>         {
> ```
oh this fallthrough + firstNonNull is quite the abuse of syntax, yes? I guess Maven complained about this too.

Would it be simpler to:

1) abandon switch statements, they're not adding any value here and actually make the code less clear (e.g., unreachable default statements, etc).
2) Streamline code with no-op flatteners and preprocessors, so all vendors can follow the same path?
3) Clean up some of the APIs? (e.g., why are there two function calls to either flattener or the new preprocessor? Seems like they're really one call: do this, give me the result. We never call `flatten` twice, we never call `processParseTree` twice.
</blockquote></details>

I was able to easily use a NopFlattener to clean up the upper switch case (by modifying a different one in another file).

I tried for a bit to clean up preprocessing, but after an hour I didn't have anything I liked better than the original code. Leaving for now - it can be cleaned up later if desired.
___
*[projects/batfish/src/main/java/org/batfish/job/PreprocessJob.java, line 125 at r2](https://reviewable.io/reviews/batfish/batfish/6642#-MTra1glA_GjCxQkkk42:-MTrpS6C43NuywPKNknC:bb7ktjg) ([raw file](https://github.com/batfish/batfish/blob/2cda13a63e5da40cf8f2bdfc9fb28d99eb3fe365/projects/batfish/src/main/java/org/batfish/job/PreprocessJob.java#L125)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> IllegalArgumentException
> ```
This is `IllegalStateException`, right? No parameters are wrong, rather the internal consistency of this function is violated.
</blockquote></details>

moot
___
*[projects/batfish/src/main/java/org/batfish/main/Preprocess.java, line 48 at r2](https://reviewable.io/reviews/batfish/batfish/6642#-MTrZ9a09qk7FoHR-lQz:-MTrrPaU3UbRV5Bss4mo:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/2cda13a63e5da40cf8f2bdfc9fb28d99eb3fe365/projects/batfish/src/main/java/org/batfish/main/Preprocess.java#L48)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> Non-preprocessible configs are copied unprocessed.
> ```
"Depending on vendor, pre-processing may be a no-op"?
</blockquote></details>

done
___
*[projects/batfish/src/test/java/org/batfish/main/PreprocessTest.java, line 74 at r2](https://reviewable.io/reviews/batfish/batfish/6642#-MTrZMma7O-C4FQncs3z:-MTrrFaK8-oJIyF7Lj6P:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/2cda13a63e5da40cf8f2bdfc9fb28d99eb3fe365/projects/batfish/src/test/java/org/batfish/main/PreprocessTest.java#L74)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> testNonJuniper
> ```
NoOp?
</blockquote></details>

done

**Review by dhalperi — COMMENTED** [review]
> Reviewed 3 of 3 files at r7, 3 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6642)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6642)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6642#-MTvRaDg1ofnk931O1P4:-MTvRaDg1ofnk931O1P5:b-e06oei) (no related file):*
LGTM, just missing a ref update

---

**Pull request merged**
