### PR TITLE
VI,JunOS: add support for from community-count

### PR DESCRIPTION
**Pull request by dhalperi**
To implement this, I had to add a CommunitySetMatchExpr to match against
CommunitySet size.

commit-id:1728e706

---

**Stack**:
- #8603
- #8602 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Comment by dhalperi** [comment]
Review: @arifogel / @sfraint for the policies, @millstein for the placeholder impl for various minesweeper code.

**Review by arifogel — COMMENTED** [review]
> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8602)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @millstein and @sfraint)

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8602)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @millstein and @sfraint)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8602)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @millstein and @sfraint)

**Review by arifogel — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8602)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @millstein and @sfraint)

**Review by millstein — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8602#-:-NHl4Cx39CSemuIoKsgE:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

**Pull request merged**
