### PR TITLE
NXOS: Support removing BGP neighbors

### PR DESCRIPTION
**Pull request by corinaminer**
Adds support for removal of BGP neighbors via `no neighbor` command, including all permutations of:
- Active or passive
- IPv4 or IPv6
- Inside or outside of VRF context
- With or without remote AS specified

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7887)* status: all files reviewed, 2 unresolved discussions (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_bgp.g4, line 548 at r2](https://reviewable.io/reviews/batfish/batfish/7887#-MsXJYkOAT8L2NahFKrd:-MsXJYkOAT8L2NahFKre:b-xnao02) ([raw file](https://github.com/batfish/batfish/blob/aacbb833794bd4df14ec297fc997f46f134f18cd/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_bgp.g4#L548)):*
> ```ANTLR
>   (
>     REMOTE_AS asn = bgp_asn
>   )? NEWLINE
> ```

there is a `remote-as route-map` variant for passive, too.



_Code quote:_
```ANTLR
  (
    REMOTE_AS asn = bgp_asn
  )? NEWLINE
```
___
*[projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_bgp_no_neighbor, line 14 at r2](https://reviewable.io/reviews/batfish/batfish/7887#-MsXJm_Q7SdREFlp5KG-:-MsXJm_Q7SdREFlp5KG0:bwo0faa) ([raw file](https://github.com/batfish/batfish/blob/aacbb833794bd4df14ec297fc997f46f134f18cd/projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_bgp_no_neighbor#L14)):*
> ```
>     neighbor 10.0.0.4 remote-as 65002
>   ! Remove undefined neighbor: no effect, no warning
>     no neighbor 5.5.5.5
> ```

why no warning? Seems like this would be good to see in an IDE...

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7887)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @arifogel and @dhalperi)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_bgp.g4, line 548 at r2](https://reviewable.io/reviews/batfish/batfish/7887#-MsXJYkOAT8L2NahFKrd:-MsXLpc32LPFY8B_R2dI:blbi74w) ([raw file](https://github.com/batfish/batfish/blob/aacbb833794bd4df14ec297fc997f46f134f18cd/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_bgp.g4#L548)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

there is a `remote-as route-map` variant for passive, too.
</blockquote></details>

aha. I looked for that in the CLI, but didn't try with passive neighbors.

Looks like arbitrary route-maps may be specified without rendering the `no neighbor` command ineffective. Let me know if you think this merits additional testing.
___
*[projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_bgp_no_neighbor, line 14 at r2](https://reviewable.io/reviews/batfish/batfish/7887#-MsXJm_Q7SdREFlp5KG-:-MsXM7vj7bgKWPcrTUz5:blwi5qc) ([raw file](https://github.com/batfish/batfish/blob/aacbb833794bd4df14ec297fc997f46f134f18cd/projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_bgp_no_neighbor#L14)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

why no warning? Seems like this would be good to see in an IDE...
</blockquote></details>

I followed the CLI's example in not providing user feedback when this happens, but warnings do seem reasonable in this case. Added.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7887)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel and @dhalperi)

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7887)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

___
*[projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_bgp_no_neighbor, line 14 at r2](https://reviewable.io/reviews/batfish/batfish/7887#-MsXJm_Q7SdREFlp5KG-:-MsXRWO_0eD4B_8gZOlL:b-67cxq) ([raw file](https://github.com/batfish/batfish/blob/aacbb833794bd4df14ec297fc997f46f134f18cd/projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_bgp_no_neighbor#L14)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

I followed the CLI's example in not providing user feedback when this happens, but warnings do seem reasonable in this case. Added.
</blockquote></details>

Optional: add vrf name to warning.

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7887)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

___
*[projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_bgp_no_neighbor, line 14 at r2](https://reviewable.io/reviews/batfish/batfish/7887#-MsXJm_Q7SdREFlp5KG-:-MsXRfiQ0fGojVfjpNub:bofpgz1) ([raw file](https://github.com/batfish/batfish/blob/aacbb833794bd4df14ec297fc997f46f134f18cd/projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_bgp_no_neighbor#L14)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Optional: add vrf name to warning.
</blockquote></details>

Figured it wouldn't add much since the presence of a `no neighbor` command implies the user is editing the config manually (so probably has immediate access to the context).

**Pull request merged**
