### PR TITLE
FortiOS: addrgrp VS support

### PR DESCRIPTION
**Pull request by sfraint**
Initial `addrgrp` parsing and extraction

Note: this PR does not handle all validation cases. e.g. it skips handling:
* members can only be in a single `addrgrp` if that `addrgrp` has type `folder`
* `exclude` can only be enabled if certain types of `address` objects are referenced by an `addrgrp`
* similarly `address` objects cannot have their types changed to incompatible types when they're used in an `addrgrp` with `exclude` enabled

### CODE REVIEW

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6781)* status: 0 of 16 files reviewed, all discussions resolved (waiting on @corinaminer)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6781#-MWaZmnA9tfaTd1oKv9d:-MWaZmnA9tfaTd1oKv9e:b6gdao4) (no related file):*
Will handle renaming and conversion in separate PRs

---

**Review by corinaminer — COMMENTED** [review]
> Reviewed 15 of 16 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6781)* status: all files reviewed, 3 unresolved discussions (waiting on @sfraint)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_addrgrp.g4, line 21 at r2](https://reviewable.io/reviews/batfish/batfish/6781#-MWbO748AtIdTUHDF2qW:-MWbO748AtIdTUHDF2qX:b-p3fzyv) ([raw file](https://github.com/batfish/batfish/blob/cee95da8d0ebf4b70a6b1ab19ba18d71fc2b9ecd/projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_addrgrp.g4#L21)):*
> ```ANTLR
>         | SELECT cfaddrgrp_set_lists
>         | APPEND cfaddrgrp_append_lists
>     )
> ```

nit: outer parentheses aren't needed
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 253 at r2](https://reviewable.io/reviews/batfish/batfish/6781#-MWcrdio83pH5FxAxWPK:-MWcrdio83pH5FxAxWPL:bk4314w) ([raw file](https://github.com/batfish/batfish/blob/cee95da8d0ebf4b70a6b1ab19ba18d71fc2b9ecd/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L253)):*
> ```Java
>    * org.batfish.representation.fortios.FortiosRenameableObject} names
>    */
>   private Set<String> toNames(Set<BatfishUUID> uuids) {
> ```

nice :sunglasses: 
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 536 at r2](https://reviewable.io/reviews/batfish/batfish/6781#-MWcuz91Dld0-gNBool3:-MWcuz91Dld0-gNBool4:btkzj5x) ([raw file](https://github.com/batfish/batfish/blob/cee95da8d0ebf4b70a6b1ab19ba18d71fc2b9ecd/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L536)):*
> ```Java
>               Set<BatfishUUID> addrs = _currentAddrgrp.getExcludeMemberUUIDs();
>               addrs.clear();
>               addrs.addAll(addresses);
> ```

Did you check if it lets you exclude an address that's already explicitly included in `members`, or vice versa? Will it reject it or remove the address from the other list? or does it just let you have the same address in both?
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 1440 at r2](https://reviewable.io/reviews/batfish/batfish/6781#-MWcu3wM822ULi-z63eE:-MWcu3wM822ULi-z63eF:bu4hvfr) ([raw file](https://github.com/batfish/batfish/blob/cee95da8d0ebf4b70a6b1ab19ba18d71fc2b9ecd/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L1440)):*
> ```Java
>     Set<BatfishUUID> members = parent.getMemberUUIDs();
>     if (parent.getBatfishUUID().equals(uuid) || members.contains(uuid)) {
>       return true;
> ```

Should it also check excluded members? I think it ought to count as a cycle when you add a member to an address group and the member already has that address group as an excluded member, but perhaps worth testing behavior.
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 1753 at r2](https://reviewable.io/reviews/batfish/batfish/6781#-MWcw4eP50FqCl93SUii:-MWcw4eP50FqCl93SUij:bz8iz09) ([raw file](https://github.com/batfish/batfish/blob/cee95da8d0ebf4b70a6b1ab19ba18d71fc2b9ecd/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L1753)):*
> ```Java
>     } else {
>       assert addrgrpCtx.FOLDER() != null;
>       warn(ctx, "Addrgrp type folder is not yet supported");
> ```

Is the plan to just not convert `folder` address groups until we support them? or convert as unmatchable?

Point being, once conversion is done, will users be confused at this warning because it looks like their `folder`-type groups are working?

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6781)* status: 12 of 16 files reviewed, 3 unresolved discussions (waiting on @corinaminer)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_addrgrp.g4, line 21 at r2](https://reviewable.io/reviews/batfish/batfish/6781#-MWbO748AtIdTUHDF2qW:-MWeGPq873ImNHnecl2f:bh9tat0) ([raw file](https://github.com/batfish/batfish/blob/cee95da8d0ebf4b70a6b1ab19ba18d71fc2b9ecd/projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_addrgrp.g4#L21)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

nit: outer parentheses aren't needed
</blockquote></details>

:thumbsup: cleaned up a bit
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 536 at r2](https://reviewable.io/reviews/batfish/batfish/6781#-MWcuz91Dld0-gNBool3:-MWeGZxV1m0u4hqcAWjo:bqlpwb) ([raw file](https://github.com/batfish/batfish/blob/cee95da8d0ebf4b70a6b1ab19ba18d71fc2b9ecd/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L536)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Did you check if it lets you exclude an address that's already explicitly included in `members`, or vice versa? Will it reject it or remove the address from the other list? or does it just let you have the same address in both?
</blockquote></details>

yeah...you can have the same address in both :slightly_frowning_face: 
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 1440 at r2](https://reviewable.io/reviews/batfish/batfish/6781#-MWcu3wM822ULi-z63eE:-MWeJEsA2Zel6g7Nk37F:b-dv08vo) ([raw file](https://github.com/batfish/batfish/blob/cee95da8d0ebf4b70a6b1ab19ba18d71fc2b9ecd/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L1440)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Should it also check excluded members? I think it ought to count as a cycle when you add a member to an address group and the member already has that address group as an excluded member, but perhaps worth testing behavior.
</blockquote></details>

Good question; I added excluded members after this and forgot to go back over the config builder helpers.

You can't actually add groups as `exclude-member`s, so I went ahead and forked the `toAddr...` method.
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 1753 at r2](https://reviewable.io/reviews/batfish/batfish/6781#-MWcw4eP50FqCl93SUii:-MWePnfM7sW2hDmPQ4d8:bydruqi) ([raw file](https://github.com/batfish/batfish/blob/cee95da8d0ebf4b70a6b1ab19ba18d71fc2b9ecd/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L1753)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Is the plan to just not convert `folder` address groups until we support them? or convert as unmatchable?

Point being, once conversion is done, will users be confused at this warning because it looks like their `folder`-type groups are working?
</blockquote></details>

I'm torn here - for `folder`s that have only valid references, Batfish will be able to trivially do the right thing.
It is only when there are invalid references/reused references in `folder`s that Batfish might accept lines that the device would reject.

Maybe it would be best to just not convert `folder` type groups for now to eliminate confusion, but there are still pathological cases where Batfish could do something different from the device...

**Review by corinaminer — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6781#-:-MWeo8_S-vRWgx76Z14o:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 536 at r2](https://reviewable.io/reviews/batfish/batfish/6781#-MWcuz91Dld0-gNBool3:-MWem2odAplSyaXHCZ4n:biqv1qm) ([raw file](https://github.com/batfish/batfish/blob/cee95da8d0ebf4b70a6b1ab19ba18d71fc2b9ecd/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L536)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

yeah...you can have the same address in both :slightly_frowning_face: 
</blockquote></details>

hah. well, that's easy enough for us :partly_sunny: 
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 1753 at r2](https://reviewable.io/reviews/batfish/batfish/6781#-MWcw4eP50FqCl93SUii:-MWenbRu-qxtAg8j_Ghi:by0iy15) ([raw file](https://github.com/batfish/batfish/blob/cee95da8d0ebf4b70a6b1ab19ba18d71fc2b9ecd/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L1753)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

I'm torn here - for `folder`s that have only valid references, Batfish will be able to trivially do the right thing.
It is only when there are invalid references/reused references in `folder`s that Batfish might accept lines that the device would reject.

Maybe it would be best to just not convert `folder` type groups for now to eliminate confusion, but there are still pathological cases where Batfish could do something different from the device...
</blockquote></details>

Well, it's nonblocking for this pr anyway. we can discuss offline
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 1516 at r3](https://reviewable.io/reviews/batfish/batfish/6781#-MWembVp6Imi32F9nmBc:-MWembVp6Imi32F9nmBd:b1lk4ac) ([raw file](https://github.com/batfish/batfish/blob/2e748080d963202d249eb26854896e5556e82d43/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L1516)):*
> ```Java
>         _c.undefined(FortiosStructureType.ADDRESS, name, usage, line);
>         warn(ctx, String.format("Address %s is undefined and cannot be referenced", name));
>         return Optional.empty();
> ```

i just realized that if we return here, we'll miss references to any valid addr groups that come after the undefined one.

Not urgent, and we have this pattern in a bunch of places, so it's probably worth punting to another PR.

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6781)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 1516 at r3](https://reviewable.io/reviews/batfish/batfish/6781#-MWembVp6Imi32F9nmBc:-MWeuCXm3HNQhPkchpO8:b-sekw99) ([raw file](https://github.com/batfish/batfish/blob/2e748080d963202d249eb26854896e5556e82d43/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L1516)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

i just realized that if we return here, we'll miss references to any valid addr groups that come after the undefined one.

Not urgent, and we have this pattern in a bunch of places, so it's probably worth punting to another PR.
</blockquote></details>

Yeah, that is intentional - we've (for now) stuck with the pattern to record refs as we see them even if they ultimately don't make it into the VS model / line or block is rejected

**Pull request merged**
