### PR TITLE
FortiOS: Start BGP parsing/extraction

### PR DESCRIPTION
**Pull request by corinaminer**
Currently parses and extracts local AS and router ID and neighbors' IPs and ASes.

### CODE REVIEW

**Review by sfraint — COMMENTED** [review]
> Reviewed 10 of 11 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6774)* status: all files reviewed, 4 unresolved discussions (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/FortiosLexer.g4, line 42 at r2](https://reviewable.io/reviews/batfish/batfish/6774#-MWVuqq83MqGEp-vJ9A9:-MWVuqq83MqGEp-vJ9AA:bj7dc91) ([raw file](https://github.com/batfish/batfish/blob/9ae37c387abb510019154a27ac8732a975e81dd0/projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/FortiosLexer.g4#L42)):*
> ```
> CONNECTED: 'connected';
> ```
are all of these new tokens used / needed?
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 545 at r2](https://reviewable.io/reviews/batfish/batfish/6774#-MWW0MdhC50vvoeHXpby:-MWW0MdhC50vvoeHXpbz:b-ezytck) ([raw file](https://github.com/batfish/batfish/blob/9ae37c387abb510019154a27ac8732a975e81dd0/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L545)):*
> ```
>       _currentBgpNeighbor = new BgpNeighbor(neighborId.orElse(Ip.ZERO));
> ```
nit: for our other structures, the "name" associated with the current structure contains the name they typed in the config, even if invalid

would be better to keep it consistent here...but not really worth it if it is a huge hassle
___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/BgpProcess.java, line 12 at r2](https://reviewable.io/reviews/batfish/batfish/6774#-MWVzL6F7jzzA1IUgA2p:-MWVzL6F7jzzA1IUgA2q:b-npvs7c) ([raw file](https://github.com/batfish/batfish/blob/9ae37c387abb510019154a27ac8732a975e81dd0/projects/batfish/src/main/java/org/batfish/representation/fortios/BgpProcess.java#L12)):*
<details><summary><i alt="summary">Quoted 21 lines of code…</i></summary>

> ```
>   private @Nullable Long _as;
>   private @Nullable Ip _routerId;
>   private final Map<Ip, BgpNeighbor> _neighbors;
>   public BgpProcess() {
>     _neighbors = new HashMap<>();
>   }
>   public @Nullable Long getAs() {
>     return _as;
>   }
>   public @Nonnull Map<Ip, BgpNeighbor> getNeighbors() {
>     return _neighbors;
>   }
>   public @Nullable Ip getRouterId() {
>     return _routerId;
>   }
>   public void setAs(Long as) {
>     _as = as;
>   }
>   public void setRouterId(Ip routerId) {
>     _routerId = routerId;
>   }
> ```
</details>

nit: [from Ari](https://github.com/batfish/batfish/pull/6675#pullrequestreview-602265852): the new formatting guideline is to sort first by visibility (public, package-private, private), then by static over non-static, then fields over methods
___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosConfiguration.java, line 41 at r2](https://reviewable.io/reviews/batfish/batfish/6774#-MWW2ajc9YThTtYRtIIo:-MWW2ajc9YThTtYRtIIp:b-qm6qar) ([raw file](https://github.com/batfish/batfish/blob/9ae37c387abb510019154a27ac8732a975e81dd0/projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosConfiguration.java#L41)):*
> ```
>     _bgpProcess = new BgpProcess();
> ```
is this standard for VS models, to instantiate a BGP process even if not configured?
___
*[projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java, line 525 at r2](https://reviewable.io/reviews/batfish/batfish/6774#-MWW4BUZBvzdhS94c_jW:-MWW4BU_6O02cspe7o7v:b-wyp2ci) ([raw file](https://github.com/batfish/batfish/blob/9ae37c387abb510019154a27ac8732a975e81dd0/projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java#L525)):*
> ```
>     assertThat(neighbors.keySet(), containsInAnyOrder(ip2222, ip3333));
> ```
nit: can use `hasKeys` instead
___
*[projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java, line 548 at r2](https://reviewable.io/reviews/batfish/batfish/6774#-MWW4dZ66Kpkkb2lb1rC:-MWW4dZ66Kpkkb2lb1rD:bq6o50r) ([raw file](https://github.com/batfish/batfish/blob/9ae37c387abb510019154a27ac8732a975e81dd0/projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java#L548)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>             hasComment("Expected BGP AS in range 0-4294967295, but got '4294967296'"),
> ...
>             hasComment("Expected BGP remote AS in range 1-4294967295, but got '0'"),
>             hasComment("Expected BGP remote AS in range 1-4294967295, but got '4294967296'"),
> ```
</details>

maybe also test non-numeric ASes? (since we're accepting `str` in that context)
___
*[projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/bgp, line 6 at r2](https://reviewable.io/reviews/batfish/batfish/6774#-MWW5Tjd5CGc48i-ZybJ:-MWW5Tjd5CGc48i-ZybK:b-4bsf5o) ([raw file](https://github.com/batfish/batfish/blob/9ae37c387abb510019154a27ac8732a975e81dd0/projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/bgp#L6)):*
> ```
>     set as 4294967295
> ```
do you need to explicitly check that no warnings were added due to this line? i.e. if it were an invalid number would the test still pass?

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6774)* status: 4 of 11 files reviewed, 1 unresolved discussion (waiting on @arifogel and @sfraint)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/FortiosLexer.g4, line 42 at r2](https://reviewable.io/reviews/batfish/batfish/6774#-MWVuqq83MqGEp-vJ9A9:-MWWEycdAOqN62J3VkzF:b-f3h7g0) ([raw file](https://github.com/batfish/batfish/blob/9ae37c387abb510019154a27ac8732a975e81dd0/projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/FortiosLexer.g4#L42)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
> CONNECTED: 'connected';
> ```
are all of these new tokens used / needed?
</blockquote></details>

ah, no, not yet (was going to use them for redistribute support). removed
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 545 at r2](https://reviewable.io/reviews/batfish/batfish/6774#-MWW0MdhC50vvoeHXpby:-MWW6X163NrB28zUIL0U:b85qyea) ([raw file](https://github.com/batfish/batfish/blob/9ae37c387abb510019154a27ac8732a975e81dd0/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L545)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
>       _currentBgpNeighbor = new BgpNeighbor(neighborId.orElse(Ip.ZERO));
> ```
nit: for our other structures, the "name" associated with the current structure contains the name they typed in the config, even if invalid

would be better to keep it consistent here...but not really worth it if it is a huge hassle

</blockquote></details>

yeahh, i didn't want to have the IP field be a string just so BgpNeighbors could retain their invalid names, especially since neighbors with invalid names shouldn't make it into the VS config anyhow. I don't think we lose anything by leaving the invalid name out
___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosConfiguration.java, line 41 at r2](https://reviewable.io/reviews/batfish/batfish/6774#-MWW2ajc9YThTtYRtIIo:-MWWAYgT7XmqKiK62wFj:bpjfz6k) ([raw file](https://github.com/batfish/batfish/blob/9ae37c387abb510019154a27ac8732a975e81dd0/projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosConfiguration.java#L41)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
>     _bgpProcess = new BgpProcess();
> ```
is this standard for VS models, to instantiate a BGP process even if not configured?
</blockquote></details>

Doesn't look like it. I changed it to remain null until initialized.
___
*[projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java, line 525 at r2](https://reviewable.io/reviews/batfish/batfish/6774#-MWW4BUZBvzdhS94c_jW:-MWWCq3QDPyyrO8YZxbE:b-p5jyx3) ([raw file](https://github.com/batfish/batfish/blob/9ae37c387abb510019154a27ac8732a975e81dd0/projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java#L525)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
>     assertThat(neighbors.keySet(), containsInAnyOrder(ip2222, ip3333));
> ```
nit: can use `hasKeys` instead
</blockquote></details>

there isn't any actual advantage to that other than slightly improved readability, is there? i prefer pulling the collection out of the object in cases like this, just because it puts the `contains` matcher an indent level shallower :see_no_evil:
___
*[projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java, line 548 at r2](https://reviewable.io/reviews/batfish/batfish/6774#-MWW4dZ66Kpkkb2lb1rC:-MWWEdxw7AP4G5HfmS90:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/9ae37c387abb510019154a27ac8732a975e81dd0/projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java#L548)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
>             hasComment("Expected BGP AS in range 0-4294967295, but got '4294967296'"),
> ...
>             hasComment("Expected BGP remote AS in range 1-4294967295, but got '0'"),
>             hasComment("Expected BGP remote AS in range 1-4294967295, but got '4294967296'"),
> ```
maybe also test non-numeric ASes? (since we're accepting `str` in that context)
</blockquote></details>

done
___
*[projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/bgp, line 6 at r2](https://reviewable.io/reviews/batfish/batfish/6774#-MWW5Tjd5CGc48i-ZybJ:-MWWDizw-ZQts-8nOI06:bhizrkh) ([raw file](https://github.com/batfish/batfish/blob/9ae37c387abb510019154a27ac8732a975e81dd0/projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/bgp#L6)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
>     set as 4294967295
> ```
do you need to explicitly check that no warnings were added due to this line? i.e. if it were an invalid number would the test still pass?
</blockquote></details>

done. good catch

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6774)* status: 4 of 11 files reviewed, 1 unresolved discussion (waiting on @arifogel and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 247 at r3](https://reviewable.io/reviews/batfish/batfish/6774#-MWWGLC11gf0ufR8g4Pi:-MWWGLC26KLnt2ZiEjxd:b1n2p3q) ([raw file](https://github.com/batfish/batfish/blob/c614c48f05a8ce346338c123c360d43e8d839405/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L247)):*
> ```Java
>               .map(u -> _c.getRenameableObjects().get(u).getName())
>               .collect(ImmutableSet.toImmutableSet()));
>     }
> ```

(this is just from rebasing, not sure why it's not lumped in with other base commit changes)

**Review by sfraint — COMMENTED** [review]
> Reviewed 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6774)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

___
*[projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java, line 525 at r2](https://reviewable.io/reviews/batfish/batfish/6774#-MWW4BUZBvzdhS94c_jW:-MWWI37bBaDQTOCz8w4O:b-aqy2er) ([raw file](https://github.com/batfish/batfish/blob/9ae37c387abb510019154a27ac8732a975e81dd0/projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java#L525)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

there isn't any actual advantage to that other than slightly improved readability, is there? i prefer pulling the collection out of the object in cases like this, just because it puts the `contains` matcher an indent level shallower :see_no_evil:
</blockquote></details>

yeah just readability here and failed assertion output, not a big deal

**Pull request merged**
