### PR TITLE
Sonic: Basic parsing

### PR DESCRIPTION
**Pull request by ratulm**

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 23 of 24 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7755)* status: all files reviewed, 12 unresolved discussions (waiting on @ratulm)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7755#-MqHZYxz26xWuzMWfJxy:-MqHZYxz26xWuzMWfJxz:b-pjlljv) (no related file):*
All new packages should have `package-info.java` with `@ParametersAreNonnullByDefault`

---
___
*[projects/batfish/src/main/java/org/batfish/job/ParseVendorConfigurationJob.java, line 764 at r2](https://reviewable.io/reviews/batfish/batfish/7755#-MqHTG1n6vPB69vlzCg6:-MqHTG1n6vPB69vlzCg7:bvyz2ma) ([raw file](https://github.com/batfish/batfish/blob/482cee1ce0c001c725206ce10e8add6e41ed93ff/projects/batfish/src/main/java/org/batfish/job/ParseVendorConfigurationJob.java#L764)):*
> ```Java
> 
>   /** Returns a string, made up of filenames, used in warnings */
>   static String jobFilenamesToString(Collection<String> filenames) {
> ```

nit: `@Nonnull` return type here and for several other functions in this PR
___
*[projects/batfish/src/main/java/org/batfish/job/ParseVendorConfigurationJob.java, line 779 at r2](https://reviewable.io/reviews/batfish/batfish/7755#-MqHTdsdD6AqOGfmdViN:-MqHTdsdD6AqOGfmdViO:b8mq66a) ([raw file](https://github.com/batfish/batfish/blob/482cee1ce0c001c725206ce10e8add6e41ed93ff/projects/batfish/src/main/java/org/batfish/job/ParseVendorConfigurationJob.java#L779)):*
> ```Java
>    * can upgrade those APIs.
>    */
>   @SuppressWarnings("unused")
> ```

Is something still unused? Surprised you got no complaint.
___
*[projects/batfish/src/main/java/org/batfish/job/ParseVendorConfigurationJob.java, line 806 at r2](https://reviewable.io/reviews/batfish/batfish/7755#-MqHUAmm93-Qu1EaWSm-:-MqHUAmm93-Qu1EaWSm0:bnp5upu) ([raw file](https://github.com/batfish/batfish/blob/482cee1ce0c001c725206ce10e8add6e41ed93ff/projects/batfish/src/main/java/org/batfish/job/ParseVendorConfigurationJob.java#L806)):*
> ```Java
>     // The file starting with '{' is a cheap way to check it is configdb.json. Valid frr.conf
>     // files cannot start with '{'.
>     String fileText1 = fileTexts.get(filename1).trim();
> ```

Trimming two large files will use extra memory to store copies of the (potentially large) configs. Why not just run format detector on each, checking for FRR?
Or if the detector is tuned for concatenated files, just check for regex `^frr version `. Note that your test files should then include something identifiable that matches that regex / format detection.
___
*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 2698 at r2](https://reviewable.io/reviews/batfish/batfish/7755#-MqHVUwe5t3K54H74QuD:-MqHVUwe5t3K54H74QuE:b-os5ne0) ([raw file](https://github.com/batfish/batfish/blob/482cee1ce0c001c725206ce10e8add6e41ed93ff/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L2698)):*
> ```Java
>         // add devices in the 'configs' folder
>         try (Stream<String> keys = _storage.listInputNetworkConfigurationsKeys(snapshot)) {
>           jobs.addAll(
> ```

Instead of materializing a list and then running `addAll` on the result, just do `.forEach(jobs::add)`. Applies multiple places.
___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/ConfigDb.java, line 33 at r2](https://reviewable.io/reviews/batfish/batfish/7755#-MqHXrQ8Dws4quaV4fZe:-MqHXWLIEJbssPbHS-0N:b-ho10e7) ([raw file](https://github.com/batfish/batfish/blob/482cee1ce0c001c725206ce10e8add6e41ed93ff/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/ConfigDb.java#L33)):*
> ```Java
> 
>   @JsonCreator
>   private static ConfigDb create(Map<String, JsonNode> objects) throws JsonProcessingException {
> ```

Why are you using `JsonNode`? If the top-level json is an object, why not just use PROPS and standard Batfish pattern for Jackson deserialization? Then there would be no need to re-delegate to batfish object mapper.

I don't see the need for `ConfigDbObject` nor `ConfigDbObject.Type`. Those enum keys should be PROPS, and instead you should have `_deviceMetadata` and `_interface` fields/getters.
___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/ConfigDb.java, line 77 at r2](https://reviewable.io/reviews/batfish/batfish/7755#-MqHYkx97Vk-9n0uXGlP:-MqHYkx97Vk-9n0uXGlQ:bk8vxlf) ([raw file](https://github.com/batfish/batfish/blob/482cee1ce0c001c725206ce10e8add6e41ed93ff/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/ConfigDb.java#L77)):*
> ```Java
>     }
>     ConfigDb data = (ConfigDb) o;
>     return Objects.equals(_objects, data._objects);
> ```

Just use `_objects.equals` since it is non-null.
But moot if you restructure deserialization.
___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/ConfigDb.java, line 82 at r2](https://reviewable.io/reviews/batfish/batfish/7755#-MqHYnib2aVZwlcM2ij1:-MqHYnib2aVZwlcM2ij2:b2ndd9s) ([raw file](https://github.com/batfish/batfish/blob/482cee1ce0c001c725206ce10e8add6e41ed93ff/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/ConfigDb.java#L82)):*
> ```Java
>   @Override
>   public int hashCode() {
>     return Objects.hash(_objects);
> ```

Just use `_objects.hashCode()` since it is non-null.
But moot if you restructure deserialization.
___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/DeviceMetadata.java, line 27 at r2](https://reviewable.io/reviews/batfish/batfish/7755#-MqHZp3_2rQzyqiga1BB:-MqHZp3_2rQzyqiga1BC:bjb9pw4) ([raw file](https://github.com/batfish/batfish/blob/482cee1ce0c001c725206ce10e8add6e41ed93ff/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/DeviceMetadata.java#L27)):*
> ```Java
> 
>   @JsonCreator
>   private static DeviceMetadata create(Map<String, Map<String, String>> properties) {
> ```

Same comment as for `ConfigDb` regarding standard deserialization.
___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/InterfaceDb.java, line 18 at r2](https://reviewable.io/reviews/batfish/batfish/7755#-MqH_AbzEDOTkEe7mQj1:-MqH_Ac-7elLl39tXuHZ:b91wsu3) ([raw file](https://github.com/batfish/batfish/blob/482cee1ce0c001c725206ce10e8add6e41ed93ff/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/InterfaceDb.java#L18)):*
> ```Java
> public class InterfaceDb implements ConfigDbObject {
> 
>   public static class Interface implements Serializable {
> ```

Why is this an inner class?
___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/InterfaceDb.java, line 55 at r2](https://reviewable.io/reviews/batfish/batfish/7755#-MqH_F_KBUbNA_DcCUyv:-MqH_F_KBUbNA_DcCUyw:bjb9pw4) ([raw file](https://github.com/batfish/batfish/blob/482cee1ce0c001c725206ce10e8add6e41ed93ff/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/InterfaceDb.java#L55)):*
> ```Java
> 
>   @JsonCreator
>   private static InterfaceDb create(Map<String, Object> interfaces) {
> ```

Same comment as for `ConfigDb` regarding standard deserialization.
___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConfiguration.java, line 18 at r2](https://reviewable.io/reviews/batfish/batfish/7755#-MqH_KIZ4mpvtl3K0FwN:-MqH_KIZ4mpvtl3K0FwO:b-aepwpo) ([raw file](https://github.com/batfish/batfish/blob/482cee1ce0c001c725206ce10e8add6e41ed93ff/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConfiguration.java#L18)):*
> ```Java
> // TODO: implement conversion
> 
> @ParametersAreNonnullByDefault
> ```

remove here and anywhere else in this package in favor of `package-info.java`.
Also needs javadoc.

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7755)* status: 12 of 28 files reviewed, 2 unresolved discussions (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/job/ParseVendorConfigurationJob.java, line 806 at r2](https://reviewable.io/reviews/batfish/batfish/7755#-MqHUAmm93-Qu1EaWSm-:-MqI0HdN2MQ2dKEzntax:bplprtw) ([raw file](https://github.com/batfish/batfish/blob/482cee1ce0c001c725206ce10e8add6e41ed93ff/projects/batfish/src/main/java/org/batfish/job/ParseVendorConfigurationJob.java#L806)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Trimming two large files will use extra memory to store copies of the (potentially large) configs. Why not just run format detector on each, checking for FRR?
Or if the detector is tuned for concatenated files, just check for regex `^frr version `. Note that your test files should then include something identifiable that matches that regex / format detection.
</blockquote></details>

The example FRR files I have do not have tell-tale signs of them being FRR, and I wanted to not impose specific markers.  I hope the use of regexes instead of trimming in the new commit addresses your concern. 
___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/InterfaceDb.java, line 55 at r2](https://reviewable.io/reviews/batfish/batfish/7755#-MqH_F_KBUbNA_DcCUyv:-MqINK8tDvbgriAcEcYE:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/482cee1ce0c001c725206ce10e8add6e41ed93ff/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/InterfaceDb.java#L55)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Same comment as for `ConfigDb` regarding standard deserialization.
</blockquote></details>

Done.

**Review by arifogel — COMMENTED** [review]
> Reviewed 16 of 16 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7755)* status: all files reviewed, 12 unresolved discussions (waiting on @ratulm)

___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/ConfigDb.java, line 33 at r3](https://reviewable.io/reviews/batfish/batfish/7755#-MqLcoUwD5GFxRUax9EL:-MqLcoUwD5GFxRUax9EM:b2o1utw) ([raw file](https://github.com/batfish/batfish/blob/f3fc85480ed3b6163bc7426de254677c0ade6733/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/ConfigDb.java#L33)):*
> ```Java
>   private final @Nonnull Map<String, L3Interface> _interfaces;
> 
>   public ConfigDb(Map<String, DeviceMetadata> deviceMetadata, Map<String, L3Interface> interfaces) {
> ```

Shouldn't this be private?
___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/ConfigDb.java, line 43 at r3](https://reviewable.io/reviews/batfish/batfish/7755#-MqLNP_JA99_W2YiSy-c:-MqLNP_JA99_W2YiSy-d:b-vpp5ob) ([raw file](https://github.com/batfish/batfish/blob/f3fc85480ed3b6163bc7426de254677c0ade6733/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/ConfigDb.java#L43)):*
> ```Java
>       @Nullable @JsonProperty(PROP_INTERFACE) Map<String, Object> interfacesMap) {
>     return new ConfigDb(
>         firstNonNull(deviceMetadata, ImmutableMap.of()),
> ```

Wrap final maps with `ImmutableMap.copyOf`, since when non-null jackson may use a mutable map implementation. Could also just do it in builder and use the builder here.
___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/ConfigDb.java, line 44 at r3](https://reviewable.io/reviews/batfish/batfish/7755#-MqLS5d43-fKnSNLySmk:-MqLS5d51sRPrxZfRbJw:bdcbp2l) ([raw file](https://github.com/batfish/batfish/blob/f3fc85480ed3b6163bc7426de254677c0ade6733/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/ConfigDb.java#L44)):*
> ```Java
>     return new ConfigDb(
>         firstNonNull(deviceMetadata, ImmutableMap.of()),
>         createInterfaces(firstNonNull(interfacesMap, ImmutableMap.<String, Object>of()).keySet()));
> ```

Please comment that all the data is in the keys, and the values are always `{}`. This justifies passing in only the keyset to `createInterfaces`.
___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/ConfigDb.java, line 49 at r3](https://reviewable.io/reviews/batfish/batfish/7755#-MqLQ7DV7LIHSY1pv1Vr:-MqLQ7DV7LIHSY1pv1Vs:boft4u2) ([raw file](https://github.com/batfish/batfish/blob/f3fc85480ed3b6163bc7426de254677c0ade6733/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/ConfigDb.java#L49)):*
> ```Java
>   /**
>    * Converts configdb's interface multi-level key encoding for interfaces, where keys are
>    * "Ethernet", "Ethernet|1.1.1.1", to a map of interfaces.
> ```

Please be a bit more explicit, noting that:
- individual keys in the input map are not necessarily for distinct interfaces (it's not obvious from the current comment you could have both of `Ethernet` and `Ethernet|1.1.1.1`)
  - data for a given interface may be encoded in multiple keys that start with that interface's name
  - the interface's name may also appear by itself.
___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/ConfigDb.java, line 52 at r3](https://reviewable.io/reviews/batfish/batfish/7755#-MqL_Cuw9DDmkFfq6qQc:-MqL_Cuw9DDmkFfq6qQd:b-rjl4fk) ([raw file](https://github.com/batfish/batfish/blob/f3fc85480ed3b6163bc7426de254677c0ade6733/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/ConfigDb.java#L52)):*
> ```Java
>    */
>   @VisibleForTesting
>   static Map<String, L3Interface> createInterfaces(Set<String> interfaceKeys) {
> ```

Optional: move static helper functions like this one to a `SonicConversions` utility class (and add tests for it) like for other vendors.
___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/ConfigDb.java, line 65 at r3](https://reviewable.io/reviews/batfish/batfish/7755#-MqLT2Am7EFoUMotplsg:-MqLT2Am7EFoUMotplsh:bvtjvln) ([raw file](https://github.com/batfish/batfish/blob/f3fc85480ed3b6163bc7426de254677c0ade6733/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/ConfigDb.java#L65)):*
> ```Java
>             interfaces.put(parts[0], new L3Interface(v4Address));
>           } catch (IllegalArgumentException e) {
>             // ignore -- could be v6 address
> ```

Should you not at least create an interface in this case? Are you always guaranteed to get the `|`-less version as well?
If more properties are possible generally, may want to use a builder instead until done reading the input. Then build and finalize at the end of the loop.

If more properties are not possible, then can ignore indefinitely.

Could probably use some comments justifying your implementation
___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/ConfigDb.java, line 75 at r3](https://reviewable.io/reviews/batfish/batfish/7755#-MqLZkhF8cCCJNaz9oZL:-MqLZkhF8cCCJNaz9oZM:b682er8) ([raw file](https://github.com/batfish/batfish/blob/f3fc85480ed3b6163bc7426de254677c0ade6733/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/ConfigDb.java#L75)):*
> ```Java
>   }
> 
>   public Optional<String> getHostname() {
> ```

nit: `@Nonnull` here, and for all the `Builder` functions
___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/ConfigDb.java, line 128 at r3](https://reviewable.io/reviews/batfish/batfish/7755#-MqL_Xoa-KxZkpdD_Wzj:-MqL_Xob8g11_hUM1dVg:bkw87y6) ([raw file](https://github.com/batfish/batfish/blob/f3fc85480ed3b6163bc7426de254677c0ade6733/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/ConfigDb.java#L128)):*
> ```Java
>     public ConfigDb build() {
>       return new ConfigDb(
>           firstNonNull(_deviceMetadata, ImmutableMap.of()),
> ```

nit: wrap these in `ImmutableMap.copyOf`
___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/DeviceMetadata.java, line 23 at r3](https://reviewable.io/reviews/batfish/batfish/7755#-MqLdaKn4i0YZ6RB-Lk5:-MqLdaKn4i0YZ6RB-Lk6:bu7199i) ([raw file](https://github.com/batfish/batfish/blob/f3fc85480ed3b6163bc7426de254677c0ade6733/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/DeviceMetadata.java#L23)):*
> ```Java
>   }
> 
>   public DeviceMetadata(@Nullable String hostname) {
> ```

Is this the only property? If not, might be better to use a builder.
___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/DeviceMetadata.java, line 51 at r3](https://reviewable.io/reviews/batfish/batfish/7755#-MqLawfRAKsb655kg1EE:-MqLawfRAKsb655kg1EF:bdluakw) ([raw file](https://github.com/batfish/batfish/blob/f3fc85480ed3b6163bc7426de254677c0ade6733/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/DeviceMetadata.java#L51)):*
> ```Java
>   @Override
>   public String toString() {
>     return MoreObjects.toStringHelper(this).add("hostname", _hostname).toString();
> ```

Optional if it's what you want: add `omitNullValues()`. Will probably want it anyway once there are more properties (assuming that happens). Applies to all your `toString`s.
___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/L3Interface.java, line 9 at r3](https://reviewable.io/reviews/batfish/batfish/7755#-MqLb9GmDQg_910ap8Ht:-MqLb9GmDQg_910ap8Hu:b5fubzl) ([raw file](https://github.com/batfish/batfish/blob/f3fc85480ed3b6163bc7426de254677c0ade6733/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/L3Interface.java#L9)):*
> ```Java
> import org.batfish.datamodel.ConcreteInterfaceAddress;
> 
> public class L3Interface implements Serializable {
> ```

javadoc
___
*[projects/batfish/src/test/java/org/batfish/vendor/sonic/representation/ConfigDbTest.java, line 83 at r3](https://reviewable.io/reviews/batfish/batfish/7755#-MqLcxsc3UsVUn6W5zgl:-MqLcxsc3UsVUn6W5zgm:b34t5ab) ([raw file](https://github.com/batfish/batfish/blob/f3fc85480ed3b6163bc7426de254677c0ade6733/projects/batfish/src/test/java/org/batfish/vendor/sonic/representation/ConfigDbTest.java#L83)):*
> ```Java
>   }
> 
>   @SuppressWarnings("UnstableApiUsage")
> ```

Wasn't aware of this one. Pretty sure it only affects intellij warnings, but fine to use I guess.
___
*[projects/batfish/src/test/java/org/batfish/vendor/sonic/representation/ConfigDbTest.java, line 88 at r3](https://reviewable.io/reviews/batfish/batfish/7755#-MqLdB495t1iofZjcnKG:-MqLdB495t1iofZjcnKH:b-5ykq7l) ([raw file](https://github.com/batfish/batfish/blob/f3fc85480ed3b6163bc7426de254677c0ade6733/projects/batfish/src/test/java/org/batfish/vendor/sonic/representation/ConfigDbTest.java#L88)):*
> ```Java
>     ConfigDb.Builder builder = ConfigDb.builder();
>     new EqualsTester()
>         .addEqualityGroup(ConfigDb.builder().build(), ConfigDb.builder().build())
> ```

nit: why not just `builder.build()`

**Review by arifogel — COMMENTED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7755)* status: all files reviewed, 2 unresolved discussions (waiting on @ratulm)

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7755)* status: all files reviewed, 2 unresolved discussions (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/ConfigDb.java, line 52 at r3](https://reviewable.io/reviews/batfish/batfish/7755#-MqL_Cuw9DDmkFfq6qQc:-MqLpM7O0y5u8ajcG0Vr:b-o54y78) ([raw file](https://github.com/batfish/batfish/blob/f3fc85480ed3b6163bc7426de254677c0ade6733/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/ConfigDb.java#L52)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Optional: move static helper functions like this one to a `SonicConversions` utility class (and add tests for it) like for other vendors.
</blockquote></details>

Might move later to another location. This is not a conversion-time method though. 
___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/ConfigDb.java, line 65 at r3](https://reviewable.io/reviews/batfish/batfish/7755#-MqLT2Am7EFoUMotplsg:-MqLp_ZW9JIAtwftPm76:b-doi89b) ([raw file](https://github.com/batfish/batfish/blob/f3fc85480ed3b6163bc7426de254677c0ade6733/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/ConfigDb.java#L65)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Should you not at least create an interface in this case? Are you always guaranteed to get the `|`-less version as well?
If more properties are possible generally, may want to use a builder instead until done reading the input. Then build and finalize at the end of the loop.

If more properties are not possible, then can ignore indefinitely.

Could probably use some comments justifying your implementation
</blockquote></details>

Not sure what legal options exist -- so covered the case of an interface only appearing with a v6 address.
___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/DeviceMetadata.java, line 23 at r3](https://reviewable.io/reviews/batfish/batfish/7755#-MqLdaKn4i0YZ6RB-Lk5:-MqLqfq_6wvWEHY0pVDR:bqr4r1i) ([raw file](https://github.com/batfish/batfish/blob/f3fc85480ed3b6163bc7426de254677c0ade6733/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/DeviceMetadata.java#L23)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Is this the only property? If not, might be better to use a builder.
</blockquote></details>

only one of interest for now that I am aware of.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7755)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ratulm)

___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/ConfigDb.java, line 52 at r3](https://reviewable.io/reviews/batfish/batfish/7755#-MqL_Cuw9DDmkFfq6qQc:-MqLtCZE4IXffSUsBYpU:bxppeii) ([raw file](https://github.com/batfish/batfish/blob/f3fc85480ed3b6163bc7426de254677c0ade6733/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/ConfigDb.java#L52)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

Might move later to another location. This is not a conversion-time method though. 
</blockquote></details>

ah, fair point.
___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/ConfigDb.java, line 65 at r3](https://reviewable.io/reviews/batfish/batfish/7755#-MqLT2Am7EFoUMotplsg:-MqLtIr12UYili2_5bBQ:b-qk6304) ([raw file](https://github.com/batfish/batfish/blob/f3fc85480ed3b6163bc7426de254677c0ade6733/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/ConfigDb.java#L65)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

Not sure what legal options exist -- so covered the case of an interface only appearing with a v6 address.
</blockquote></details>

yup, looks good

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7755)* status: all files reviewed, 1 unresolved discussion (waiting on @ratulm)

___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/ConfigDb.java, line 133 at r4](https://reviewable.io/reviews/batfish/batfish/7755#-MqLz6cx2t9mwpeb4vHq:-MqLz6cx2t9mwpeb4vHr:b-oh921w) ([raw file](https://github.com/batfish/batfish/blob/a1c05fe2417edd2442ca8d761b843bbe64925512/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/ConfigDb.java#L133)):*
> ```Java
>     public @Nonnull ConfigDb build() {
>       return new ConfigDb(
>           firstNonNull(ImmutableMap.copyOf(_deviceMetadata), ImmutableMap.of()),
> ```

The `ImmutableMap.copyOf` needs to go on the outside. Otherwise you could be taking a copy of `null`.

**Review by ratulm — COMMENTED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7755)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ratulm)

**Pull request merged**
