### PR TITLE
Support Juniper SRX application-set

### PR DESCRIPTION
**Pull request by arifogel**

### CODE REVIEW

**Comment by arifogel** [comment]
Review status: 0 of 23 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[a discussion](https://beta.reviewable.io/reviews/batfish/batfish/1164#-LA1_B6YEXa-48SW3YN7:-LA1_B6YEXa-48SW3YN8:b-dru7t7) (no related file):*
After #1161

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1164)*

**Comment by dhalperi** [comment]
:lgtm:

---

Reviewed 18 of 23 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperStructureUsage.java, line 7 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1164#-LA1k9SlBaNmJp61Jq12:-LA1k9SlBaNmJp61Jq13:b-cc1ky0) ([raw file](https://github.com/batfish/batfish/blob/3c2735564cf01999135dcf3e88c0d5e53115cd49/projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperStructureUsage.java#L7)):*
> ```Java
> public enum JuniperStructureUsage implements StructureUsage {
>   APPLICATION_SET_APPLICATION("application-set application"),
>   APPLICATION_SET_APPLICATION_SET("application-set application-set"),
> ```

Optional: consider renaming to clarify? I find these hard to read, though I agree they are correct.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1164#-:-LA1klJSBtOpVoVJLlKw:bnfp4nl)*

**Comment by arifogel** [comment]
*[projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperStructureUsage.java, line 7 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1164#-LA1k9SlBaNmJp61Jq12:-LA5PnAc2CMT8UPln2sU:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/3c2735564cf01999135dcf3e88c0d5e53115cd49/projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperStructureUsage.java#L7)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Optional: consider renaming to clarify? I find these hard to read, though I agree they are correct.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1164)*

**Comment by dhalperi** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1164)*

**Pull request merged**
