### PR TITLE
 Generalize VRF leaking datamodel

### PR DESCRIPTION
**Pull request by progwriter**
Encapsulate in a separate object, allow leaking as BGP.
No new functionality in this PR, just prepping for future work.

### CODE REVIEW

**Review by progwriter — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6516)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @corinaminer)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Vrf.java, line 123 at r1](https://reviewable.io/reviews/batfish/batfish/6516#-MP5RGjEEKaU46hF96Wu:-MP5RGjEEKaU46hF96Wv:bbyhr8) ([raw file](https://github.com/batfish/batfish/blob/1dd6d0fa5a763ad8b4df0f5ebb09a055a165398e/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Vrf.java#L123)):*
> ```Java
>   private Map<Integer, Layer2Vni> _layer2Vnis;
>   private Map<Integer, Layer3Vni> _layer3Vnis;
>   private Set<VrfLeakingConfig> _vrfLeakConfigs;
> ```

@corinaminer I did not think order was important here. If you believe it is, based on your previous work, let me know I can make this a list.

**Review by corinaminer — COMMENTED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6516)* status: all files reviewed, 2 unresolved discussions (waiting on @progwriter)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Vrf.java, line 123 at r1](https://reviewable.io/reviews/batfish/batfish/6516#-MP5RGjEEKaU46hF96Wu:-MP6FhwA2CwMM6_dgO8n:b-rajgj2) ([raw file](https://github.com/batfish/batfish/blob/1dd6d0fa5a763ad8b4df0f5ebb09a055a165398e/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Vrf.java#L123)):*
hmm... i think it does matter in this scenario:
- vrf1 imports routes from vrf2 and vrf3
- vrf2 and vrf3 both leak an identical route
- vrf1 has some export policy with a `from instance vrf2` term
- will the route match that term if vrf1's instance-import policy has vrf3 first?

I vaguely remember testing this, but that was before I was keeping good records of GNS3 experiments. The javadoc for `getVrfsReferencedByPolicies` is specific about order, which makes me suspect tests showed that it mattered (i.e. that the answer to the question above was no):
> returns a list of the VRFs referenced in those policies, in the order in which they appear (within each policy and within the list of policies)

Not certain that the VRF import order is really the order they are referenced in instance-import policies, but we should use a list anyway to ensure routes remain consistent.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Vrf.java, line 275 at r1](https://reviewable.io/reviews/batfish/batfish/6516#-MP6A5qz4EmEuMA8ZZqC:-MP6A5qz4EmEuMA8ZZqD:bezmh7d) ([raw file](https://github.com/batfish/batfish/blob/1dd6d0fa5a763ad8b4df0f5ebb09a055a165398e/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Vrf.java#L275)):*
> ```Java
>   }
> 
>   public Collection<VrfLeakingConfig> getVrfLeakConfigs() {
> ```

Missing JSON property annotation (also on setter)
___
*[tests/parsing-tests/unit-tests-vimodel.ref, line 0 at r1](https://reviewable.io/reviews/batfish/batfish/6516#-MP6F823-XNv6lb7uPLF:-MP6F823-XNv6lb7uPLG:b-vjyd07) ([raw file](https://github.com/batfish/batfish/blob/1dd6d0fa5a763ad8b4df0f5ebb09a055a165398e/tests/parsing-tests/unit-tests-vimodel.ref#L0)):*
The instance-import configuration in `juniper_routing_options` no longer makes it into the VI model because its instance import policy doesn't reference any VRFs. Please update the ref config to either have a `VrfLeakingConfig` in its VI model or not exercise instance-import.

**Review by progwriter — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6516)* status: 5 of 9 files reviewed, all discussions resolved (waiting on @corinaminer)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Vrf.java, line 123 at r1](https://reviewable.io/reviews/batfish/batfish/6516#-MP5RGjEEKaU46hF96Wu:-MP7AWUT9pp5_CAljD7A:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/1dd6d0fa5a763ad8b4df0f5ebb09a055a165398e/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Vrf.java#L123)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

hmm... i think it does matter in this scenario:
- vrf1 imports routes from vrf2 and vrf3
- vrf2 and vrf3 both leak an identical route
- vrf1 has some export policy with a `from instance vrf2` term
- will the route match that term if vrf1's instance-import policy has vrf3 first?

I vaguely remember testing this, but that was before I was keeping good records of GNS3 experiments. The javadoc for `getVrfsReferencedByPolicies` is specific about order, which makes me suspect tests showed that it mattered (i.e. that the answer to the question above was no):
> returns a list of the VRFs referenced in those policies, in the order in which they appear (within each policy and within the list of policies)

Not certain that the VRF import order is really the order they are referenced in instance-import policies, but we should use a list anyway to ensure routes remain consistent.
</blockquote></details>

done
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Vrf.java, line 275 at r1](https://reviewable.io/reviews/batfish/batfish/6516#-MP6A5qz4EmEuMA8ZZqC:-MP7AXRgB7eQgMmwf4XU:b-7rl0jr) ([raw file](https://github.com/batfish/batfish/blob/1dd6d0fa5a763ad8b4df0f5ebb09a055a165398e/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Vrf.java#L275)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Missing JSON property annotation (also on setter)
</blockquote></details>

done 
___
*[tests/parsing-tests/unit-tests-vimodel.ref, line  at r1](https://reviewable.io/reviews/batfish/batfish/6516#-MP6F823-XNv6lb7uPLF:-MP7AYwG9FJohg2idyNu:b-6rlfie) ([raw file](https://github.com/batfish/batfish/blob/1dd6d0fa5a763ad8b4df0f5ebb09a055a165398e/tests/parsing-tests/unit-tests-vimodel.ref#L)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

The instance-import configuration in `juniper_routing_options` no longer makes it into the VI model because its instance import policy doesn't reference any VRFs. Please update the ref config to either have a `VrfLeakingConfig` in its VI model or not exercise instance-import.
</blockquote></details>

removed since we have better grammar tests no need to keep this ref test imo.

**Review by corinaminer — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6516#-:-MP7Bhvc1EyOOVIeFGJi:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by corinaminer — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6516)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
