### PR TITLE
Symbolic Route Analysis: Better support for next-hops

### PR DESCRIPTION
**Pull request by millstein**
This PR is identical to the reverted PR #8740 except that it is backward-compatible with the existing API for the route analysis questions like TestRoutePolicies and SearchRoutePolicies.  In particular the BgpRoute class used for input/output in those questions has been updated in a way that retains backward compatibility.

Adds support to the symbolic route analysis and associated questions (SearchRoutePolicies and CompareRoutePolicies) for several next-hop-related route-map constructs:

    Matching on the interface name of the next hop
    Setting the next hop to the local IP address
    Setting the next hop to the remote IP address

### CODE REVIEW

**Review by nickgian — COMMENTED** [review]
> Reviewed 15 of 32 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8786)* status: 15 of 32 files reviewed, 1 unresolved discussion (waiting on @anothermattbrown and @millstein)

___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpRoute.java` line 204 at r1](https://reviewable.io/reviews/batfish/batfish/8786#-NcrabhLAeImB4cqh5fI:-NcrabhLAeImB4cqh5fJ:btyyupo) ([raw file](https://github.com/batfish/batfish/blob/d46dbfa5ba707c8e0a58420881f44678109a2e43/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpRoute.java#L204)):*
> ```Java
> 
>   @JsonProperty(PROP_NEXT_HOP_IP)
>   private @Nullable Ip getNextHopIpJson() {
> ```

How would we go about using this richer result type in Pybatfish? Why don't we just update that too? Are we trying to maintain compatibility with older versions of Pybatfish (or other unknown clients that use JSON)?

**Review by millstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8786)* status: 15 of 32 files reviewed, 1 unresolved discussion (waiting on @anothermattbrown and @nickgian)

___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpRoute.java` line 204 at r1](https://reviewable.io/reviews/batfish/batfish/8786#-NcrabhLAeImB4cqh5fI:-NcsaToWDVH2WlgNtfO9:b-iy6rz1) ([raw file](https://github.com/batfish/batfish/blob/d46dbfa5ba707c8e0a58420881f44678109a2e43/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpRoute.java#L204)):*
<details><summary><i>Previously, nickgian (Nick Giannarakis) wrote…</i></summary><blockquote>

How would we go about using this richer result type in Pybatfish? Why don't we just update that too? Are we trying to maintain compatibility with older versions of Pybatfish (or other unknown clients that use JSON)?
</blockquote></details>

The original PR for this change modified the BgpRoute class in a way that was not backward-compatible, and also updated things on the pybatfish side.  But the lack of backward compatibility was a problem -- it broke various clients.  This version is backward compatible.  Because of that, for this PR there is no need to update pybatfish, but we can separately do that at a later time in order to enable clients to make use of the new expressiveness.

**Review by nickgian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8786)* status: 15 of 32 files reviewed, all discussions resolved (waiting on @anothermattbrown)

___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpRoute.java` line 204 at r1](https://reviewable.io/reviews/batfish/batfish/8786#-NcrabhLAeImB4cqh5fI:-Nd0iatRBrSZK2gMc_Kb:b1tzxa5) ([raw file](https://github.com/batfish/batfish/blob/d46dbfa5ba707c8e0a58420881f44678109a2e43/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpRoute.java#L204)):*
<details><summary><i>Previously, millstein (Todd Millstein) wrote…</i></summary><blockquote>

The original PR for this change modified the BgpRoute class in a way that was not backward-compatible, and also updated things on the pybatfish side.  But the lack of backward compatibility was a problem -- it broke various clients.  This version is backward compatible.  Because of that, for this PR there is no need to update pybatfish, but we can separately do that at a later time in order to enable clients to make use of the new expressiveness.
</blockquote></details>

Oh I think my worry was that we throw away the result in non-concrete cases, but I realize that we would use a new `JsonProperty` tag to store the richer result type.

**Review by nickgian — COMMENTED** [review]
:lgtm:

> Reviewed 17 of 32 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8786#-:-Nd0l7xK5HiaKnuiI6lh:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown)

**Review by millstein — COMMENTED** [review]
@anothermattbrown There are still CI failures for pybatfish on master, and apparently there are no immediate plans to address them. But I have verified that the Analyzing Routing Policies notebook behaves identically whether we use Batfish master or this branch, so it is backward compatible.

> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8786#-:-NeObGem2uSTJ2dUpJBu:b-rfiukf)* status: 29 of 32 files reviewed, all discussions resolved (waiting on @anothermattbrown and @nickgian)

**Review by dhalperi — COMMENTED** [review]
Please fix pybatfish. If you think there are missing instructions or other tools needed, please file an issue.

> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8786#-:-NeOchDt3Uo8z8ovHjD9:brxgcyo)* status: 29 of 32 files reviewed, all discussions resolved (waiting on @anothermattbrown and @nickgian)

**Review by millstein — COMMENTED** [review]
Done (thanks for the help).  I can confirm now that this PR does not break any integration tests on the pybatfish side.

> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8786#-:-NeQ2XxPE3YEaJbF5BrD:bqy9fov)* status: 29 of 32 files reviewed, all discussions resolved (waiting on @anothermattbrown and @nickgian)

**Review by millstein — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8786#-:-NeiP9eJE-MzsGmBPYpq:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @millstein)

**Review by millstein — COMMENTED** [review]
> Reviewed 23 of 32 files at r1, 3 of 3 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8786)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @millstein)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8786)* status: all files reviewed, 1 unresolved discussion (waiting on @millstein)

___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/Schema.java` line 79 at r3](https://reviewable.io/reviews/batfish/batfish/8786#-NeiPvqaCzGpDv_WT6Mg:-NeiPvqaCzGpDv_WT6Mh:b-5hx0we) ([raw file](https://github.com/batfish/batfish/blob/2a90746fd3d297d12b9ced9b246d591d342f5986/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/Schema.java#L79)):*
> ```Java
>   public static final Schema LONG = new Schema("Long");
>   public static final Schema NEXT_HOP = new Schema("NextHop");
>   public static final Schema NEXT_HOP_RESULT = new Schema("NextHopResult");
> ```

This will require changes in pybatfish FYI. Deserialization, docs, etc.

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 8 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8786)* status: all files reviewed, 1 unresolved discussion (waiting on @millstein)

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8786)* status: all files reviewed, 1 unresolved discussion (waiting on @millstein)

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8786)* status: all files reviewed, 4 unresolved discussions (waiting on @millstein)

___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpRoute.java` line 72 at r4](https://reviewable.io/reviews/batfish/batfish/8786#-NeiRghN6x83VxC5lyU2:-NeiRghN6x83VxC5lyU3:b-uughje) ([raw file](https://github.com/batfish/batfish/blob/ebac4a64043f5158300290d46e949e8174dbd199/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpRoute.java#L72)):*
> ```Java
>   @Nullable private final Integer _pathId;
>   @Nonnull private final RoutingProtocol _protocol;
>   @Nullable private final RoutingProtocol _srcProtocol;
> ```

Please undo this regression.
___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpRoute.java` line 214 at r4](https://reviewable.io/reviews/batfish/batfish/8786#-NeiRj_S8UQ34TBe7l39:-NeiRj_S8UQ34TBe7l3A:undefined) ([raw file](https://github.com/batfish/batfish/blob/ebac4a64043f5158300290d46e949e8174dbd199/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpRoute.java#L214)):*
> ```Java
>   @JsonProperty(PROP_NEXT_HOP)
>   public NextHopResult getNextHop() {
>     return _nextHop;
> ```





_Suggestion:_
```Java
  @JsonProperty(PROP_NEXT_HOP)
  public @Nonnull NextHopResult getNextHop() {
    return _nextHop;
```
___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpRoute.java` line 372 at r4](https://reviewable.io/reviews/batfish/batfish/8786#-NeiRnQB6BFtpjozUfwm:-NeiRnQB6BFtpjozUfwn:b-nlgstm) ([raw file](https://github.com/batfish/batfish/blob/ebac4a64043f5158300290d46e949e8174dbd199/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpRoute.java#L372)):*
> ```Java
>     @Nullable private RoutingProtocol _srcProtocol;
>     private long _tag;
>     private @Nullable TunnelEncapsulationAttribute _tunnelEncapsulationAttribute;
> ```

please undo this regression.

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8786)* status: all files reviewed, 10 unresolved discussions (waiting on @millstein)

___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/ConfigAtomicPredicates.java` line 66 at r4](https://reviewable.io/reviews/batfish/batfish/8786#-NeiS9YnAzwR9m1FqViO:-NeiS9YnAzwR9m1FqViP:bmm6aow) ([raw file](https://github.com/batfish/batfish/blob/ebac4a64043f5158300290d46e949e8174dbd199/projects/minesweeper/src/main/java/org/batfish/minesweeper/ConfigAtomicPredicates.java#L66)):*
> ```Java
>   /** The list of source VRFs that appear in the given configuration. */
>   private final ImmutableList<String> _sourceVrfs;
> ```

Usually we don't do this. Why add the `Immutable`?
___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/ConfigAtomicPredicates.java` line 395 at r4](https://reviewable.io/reviews/batfish/batfish/8786#-NeiSGvE3-08Z8518R8a:-NeiSGvE3-08Z8518R8b:b-wp98se) ([raw file](https://github.com/batfish/batfish/blob/ebac4a64043f5158300290d46e949e8174dbd199/projects/minesweeper/src/main/java/org/batfish/minesweeper/ConfigAtomicPredicates.java#L395)):*
> ```Java
>   public ImmutableList<String> getSourceVrfs() {
>     return _sourceVrfs;
>   }
> ```

Also typically don't do this.
___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesAnswerer.java` line 82 at r4](https://reviewable.io/reviews/batfish/batfish/8786#-NeiSbAo446QVgw8ThM4:-NeiSbAo446QVgw8ThM5:bfa0dg8) ([raw file](https://github.com/batfish/batfish/blob/ebac4a64043f5158300290d46e949e8174dbd199/projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesAnswerer.java#L82)):*
> ```Java
>   @Nonnull private final RoutingPolicySpecifier _policySpecifier;
>   @Nonnull private final LineAction _action;
> ```

please undo this regression
___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesAnswerer.java` line 95 at r4](https://reviewable.io/reviews/batfish/batfish/8786#-NeiSdV3AQ2u05vY_34g:-NeiSdV3AQ2u05vY_34h:undefined) ([raw file](https://github.com/batfish/batfish/blob/ebac4a64043f5158300290d46e949e8174dbd199/projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesAnswerer.java#L95)):*
> ```Java
>    */
>   @Nonnull
>   public static BgpSessionProperties DUMMY_BGP_SESSION_PROPERTIES =
> ```





_Suggestion:_
```Java
  public static @Nonnull BgpSessionProperties DUMMY_BGP_SESSION_PROPERTIES =
```
___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesQuestion.java` line 47 at r4](https://reviewable.io/reviews/batfish/batfish/8786#-NeiSkE8CN25wXDTuubd:-NeiSkE8CN25wXDTuube:bfa0dg8) ([raw file](https://github.com/batfish/batfish/blob/ebac4a64043f5158300290d46e949e8174dbd199/projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesQuestion.java#L47)):*
> ```Java
>   @Nonnull private final BgpRouteConstraints _inputConstraints;
>   @Nonnull private final BgpRouteConstraints _outputConstraints;
>   @Nonnull private final LineAction _action;
> ```

please undo this regression
___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesQuestion.java` line 169 at r4](https://reviewable.io/reviews/batfish/batfish/8786#-NeiSnjA4DrOCUeBGewd:-NeiSnjA4DrOCUeBGewe:bfa0dg8) ([raw file](https://github.com/batfish/batfish/blob/ebac4a64043f5158300290d46e949e8174dbd199/projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesQuestion.java#L169)):*
> ```Java
>   @JsonProperty(PROP_ACTION)
>   @Nonnull
>   public LineAction getAction() {
> ```

please undo this regression

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8786)* status: all files reviewed, 9 unresolved discussions (waiting on @millstein)

___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpRoute.java` line 214 at r4](https://reviewable.io/reviews/batfish/batfish/8786#-NeiRj_S8UQ34TBe7l39:-Neik--P3H9HDqvEUUFc:bpo9ytm) ([raw file](https://github.com/batfish/batfish/blob/ebac4a64043f5158300290d46e949e8174dbd199/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpRoute.java#L214)):*
<details><summary><i>Previously, millstein (Todd Millstein) wrote…</i></summary><blockquote>

I'm confused. Where should the nonnull attribute go?  The other getters in this class use the existing style, and that also seems consistent with your comment above (to move the nullable attribute first for the tunnel field).
</blockquote></details>

The principle is "the Nullity annotation modifies the type". When it's possible to do that, we do.

Having a hard time finding good tool enforcement in cases where they're not on the same line, however.
___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/ConfigAtomicPredicates.java` line 66 at r4](https://reviewable.io/reviews/batfish/batfish/8786#-NeiS9YnAzwR9m1FqViO:-NeikJtJE_RTrjQrXikI:b-n2bufu) ([raw file](https://github.com/batfish/batfish/blob/ebac4a64043f5158300290d46e949e8174dbd199/projects/minesweeper/src/main/java/org/batfish/minesweeper/ConfigAtomicPredicates.java#L66)):*
<details><summary><i>Previously, millstein (Todd Millstein) wrote…</i></summary><blockquote>

I think of immutability as part of the type.  Maybe more important for the public API (see my response to your next comment) but also useful documentation internally.  Is there a reason not to do it?
</blockquote></details>

The standard assumption in Batfish is immutability, especially for returned values from APIs. So the practice is to NOT document it unless the return value is mutable.

Also, unfortunately, `ImmutableList` is not a language feature like `const`, it's a concrete type from a library. It's bad practice to force callers to take on API dependencies they don't have to.

The relevant EJ/PMD/etc are I think:

EJ 15: prefer immutability
PMD LooseCoupling

I wonder if there are type annotations that fit with what you're trying to do, like we did for nullity. (aka, `@Nonnull List` vs `NonnullList` vs `/** Unmodifiable. */ List`).

Maybe https://errorprone.info/bugpattern/Immutable, but we haven't taken that on yet.

**Review by millstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8786)* status: 29 of 32 files reviewed, 4 unresolved discussions (waiting on @anothermattbrown, @dhalperi, and @nickgian)

___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesQuestion.java` line 47 at r4](https://reviewable.io/reviews/batfish/batfish/8786#-NeiSkE8CN25wXDTuubd:-Nek8fTQ1v0RMl0jlaT8:b-56m9lp) ([raw file](https://github.com/batfish/batfish/blob/ebac4a64043f5158300290d46e949e8174dbd199/projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesQuestion.java#L47)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

please undo this regression
</blockquote></details>

Are you talking about the move to `LineAction`?  I did that because I saw that TRP was already using that to represent route policy actions in results, but if you prefer this question to have its own enum (for backward compatibility or otherwise) that's fine.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 3 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8786)* status: all files reviewed, 1 unresolved discussion (waiting on @millstein)

___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesQuestion.java` line 47 at r4](https://reviewable.io/reviews/batfish/batfish/8786#-NeiSkE8CN25wXDTuubd:-NenBcm_DFkOtLm_AMab:b-cvolmf) ([raw file](https://github.com/batfish/batfish/blob/ebac4a64043f5158300290d46e949e8174dbd199/projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesQuestion.java#L47)):*
<details><summary><i>Previously, millstein (Todd Millstein) wrote…</i></summary><blockquote>

Are you talking about the move to `LineAction`?  I did that because I saw that TRP was already using that to represent route policy actions in results, but if you prefer this question to have its own enum (for backward compatibility or otherwise) that's fine.
</blockquote></details>

Was just talking about the annotations. That's fixed, leave the types alone as you see fit :)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 32 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8786)* status: all files reviewed, 1 unresolved discussion (waiting on @millstein)

___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpRoute.java` line 163 at r6](https://reviewable.io/reviews/batfish/batfish/8786#-NenBrfwEfPHOhmAGp5o:-NenBrfwEfPHOhmAGp5p:bewsrwl) ([raw file](https://github.com/batfish/batfish/blob/dfe380c4caa819fdcfbf293898a4f43b58ec6a18/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpRoute.java#L163)):*
> ```Java
>   private static NextHopResult ipToNextHopResult(@Nullable Ip nextHopIp) {
>     NextHop nh;
>     if (nextHopIp == null || nextHopIp.equals(UNSET_ROUTE_NEXT_HOP_IP)) {
> ```

FYI, I don't think it matters in practice but there's `Ip.valid()` (maybe `isValid()`; memory is weak) which captures this and other invalid IP addresses.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8786)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @millstein)

**Pull request merged**
