### PR TITLE
Better error handling in coordinator

### PR DESCRIPTION
**Pull request by dhalperi**
This change is [Reviewable](https://reviewable.io/reviews/batfish/batfish/924)

### CODE REVIEW

**Comment by ratulm** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/924)*

**Comment by ratulm** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/924#-:-L4rVOXQI6zlWHy_Du4S:bnfp4nl)*

**Comment by ratulm** [comment]
This change is problematic. Metadata should be created by initTestrig. The Git plugin calls that function (without calling uploadTestrig).

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/924#-:-L4raIqFoeTL255ZOXg9:bk7sdaz)*

**Comment by dhalperi** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/924)*

**Pull request merged**
