### PR TITLE
Cisco_bgp: parse redistribute ospfv3

### PR DESCRIPTION
**Pull request by dhalperi**
Is `null` the right approach for ospfv3 or should I do something more sophisticated?

### CODE REVIEW

**Comment by arifogel** [comment]
Something more sophisticated.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_bgp.g4, line 204 at r1](https://beta.reviewable.io/reviews/batfish/batfish/995#-L6T272E2IU773XGFlS8:-L6T272E2IU773XGFlS9:b6bmay4) ([raw file](https://github.com/batfish/batfish/blob/dd69ff87b4b92438857b9e8cf53a1fbf4bd70ef0/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_bgp.g4#L204)):*
> ```ANTLR
>    | redistribute_connected_bgp_tail
>    | redistribute_ospf_bgp_tail
>    | redistribute_ospfv3_null
> ```

Instead of this, just copy the `redistribute_ospf_bgp_tail` so we can grab the route-map reference. You will need to make changes to `CiscoControlPlaneExtractor`.

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_bgp.g4, line 784 at r1](https://beta.reviewable.io/reviews/batfish/batfish/995#-L6T2DmDDTxchqSlnWAw:-L6T2DmDDTxchqSlnWAx:b-3c5j95) ([raw file](https://github.com/batfish/batfish/blob/dd69ff87b4b92438857b9e8cf53a1fbf4bd70ef0/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_bgp.g4#L784)):*
> ```ANTLR
> ;
> 
> redistribute_ospfv3_null
> ```

Remove this rule.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/995#-:-L6T2wKNCRmcSXSb06LS:b-tibsz8)*

**Comment by dhalperi** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_bgp.g4, line 204 at r1](https://reviewable.io:443/reviews/batfish/batfish/995#-L6T272E2IU773XGFlS8:-L6TTH7_ZOT1v64i9wSn:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/dd69ff87b4b92438857b9e8cf53a1fbf4bd70ef0/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_bgp.g4#L204)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Instead of this, just copy the `redistribute_ospf_bgp_tail` so we can grab the route-map reference. You will need to make changes to `CiscoControlPlaneExtractor`.
</blockquote></details>

Done.

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_bgp.g4, line 784 at r1](https://reviewable.io:443/reviews/batfish/batfish/995#-L6T2DmDDTxchqSlnWAw:-L6TTHgPlkfS8K-gJY0H:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/dd69ff87b4b92438857b9e8cf53a1fbf4bd70ef0/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_bgp.g4#L784)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Remove this rule.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/995)*

**Comment by dhalperi** [comment]
Done, and confirmed that it successfully does not create a new unused reference. Please take another look.

---

Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/995#-:-L6TTMXCTuNrqKtqTWeU:b7px8d1)*

**Comment by arifogel** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/995#-:-L6Tajdx8pEyb7ipBmk5:bnfp4nl)*

**Pull request merged**
