### PR TITLE
support basic NAT logic when considering whether IPSEC VPN connections are up

### PR DESCRIPTION
**Pull request by arifogel**
This change is [Reviewable](https://reviewable.io/reviews/batfish/batfish/752)

### CODE REVIEW

**Comment by dhalperi** [comment]
:lgtm:

---

Reviewed 29 of 29 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpSpace.java, line 8 at r1](https://reviewable.io:443/reviews/batfish/batfish/752#-L0DW0LBFSiqGSQkVlpm:-L0DW0LBFSiqGSQkVlpn:b-chehkb) ([raw file](https://github.com/batfish/batfish/blob/88cf090cb0b3f9b6931cd294ca7dd06b4579dd4c/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpSpace.java#L8)):*
> ```Java
> 
> /** Represents a space of IPv4 addresses. */
> public class IpSpace implements Serializable {
> ```

needs tests.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpSpace.java, line 17 at r1](https://reviewable.io:443/reviews/batfish/batfish/752#-L0DWEGLign8KHxnquz1:-L0DWEGLign8KHxnquz2:b2xu7a4) ([raw file](https://github.com/batfish/batfish/blob/88cf090cb0b3f9b6931cd294ca7dd06b4579dd4c/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpSpace.java#L17)):*
> ```Java
>   private final Set<IpWildcard> _whitelist;
> 
>   public IpSpace(Set<IpWildcard> blacklist, Set<IpWildcard> whitelist) {
> ```

this seems like an error-prone constructor. Sketchy-suggestion: consider named methods on a builder, something like `IpSpace.builder().including().excluding().build();` or something along those lines.

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 2186 at r1](https://reviewable.io:443/reviews/batfish/batfish/752#-L0DXQ6XaQ8J6Acg16s6:-L0DXQ6XaQ8J6Acg16s7:bxsu8sf) ([raw file](https://github.com/batfish/batfish/blob/88cf090cb0b3f9b6931cd294ca7dd06b4579dd4c/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L2186)):*
> ```Java
>           Set<IpsecVpn> reciprocalVpns = externalAddresses.get(reciprocalRemoteAddress);
>           IpSpace privateIpsBehindReciprocalRemoteAddress =
>               privateIpsByPublicIp.get(reciprocalRemoteAddress);
> ```

put inside the `if`?

---

*[projects/batfish/src/test/java/org/batfish/grammar/host/HostTest.java, line 22 at r1](https://reviewable.io:443/reviews/batfish/batfish/752#-L0DUuUnsSXuzrmKw0rG:-L0DUuUoAzGNxpMt3zDc:b-55q69b) ([raw file](https://github.com/batfish/batfish/blob/88cf090cb0b3f9b6931cd294ca7dd06b4579dd4c/projects/batfish/src/test/java/org/batfish/grammar/host/HostTest.java#L22)):*
> ```Java
> import org.junit.rules.TemporaryFolder;
> 
> public class HostTest {
> ```

what is the file containing the code under test? Is this `HostInterfaceTest`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/752#-:-L0DXhwIUVQgRp4zQJms:bnfp4nl)*

**Comment by dhalperi** [comment]
*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 2244 at r2](https://reviewable.io:443/reviews/batfish/batfish/752#-L0GFnd4ymDC0gmAvK3u:-L0GFnd4ymDC0gmAvK3v:b788xvq) ([raw file](https://github.com/batfish/batfish/blob/d2a66626c501f6e963bb6fd4152aec039075f6d4/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L2244)):*
> ```Java
>       //   1) Collect references to ACLs and NAT pools.
>       //   2) For valid CiscoSourceNat rules, add them to the newIface source NATs list.
>       newIface.setSourceNats(
> ```

the previous code seemed to think it was possible for `newIface` to already have `sourceNats` set, and took care not to override them. Can you confirm that's not the case?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/752)*

**Comment by dhalperi** [comment]
*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 2244 at r2](https://reviewable.io:443/reviews/batfish/batfish/752#-L0GFnd4ymDC0gmAvK3u:-L0GFyKS8V9jKPijdJdY:bnbg029) ([raw file](https://github.com/batfish/batfish/blob/d2a66626c501f6e963bb6fd4152aec039075f6d4/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L2244)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

the previous code seemed to think it was possible for `newIface` to already have `sourceNats` set, and took care not to override them. Can you confirm that's not the case?
</blockquote></details>

I should say, took care to make sure they weren't forgotten when adding these ones.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/752)*

**Comment by dhalperi** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/752)*

**Comment by arifogel** [comment]
Review status: 26 of 29 files reviewed at latest revision, 5 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpSpace.java, line 8 at r1](https://reviewable.io:443/reviews/batfish/batfish/752#-L0DW0LBFSiqGSQkVlpm:-L0Gjk92ohe_TaLaeW0j:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/88cf090cb0b3f9b6931cd294ca7dd06b4579dd4c/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpSpace.java#L8)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

needs tests.
</blockquote></details>

Done.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpSpace.java, line 17 at r1](https://reviewable.io:443/reviews/batfish/batfish/752#-L0DWEGLign8KHxnquz1:-L0Gjkgl7W5WZ5kX7Llp:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/88cf090cb0b3f9b6931cd294ca7dd06b4579dd4c/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpSpace.java#L17)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

this seems like an error-prone constructor. Sketchy-suggestion: consider named methods on a builder, something like `IpSpace.builder().including().excluding().build();` or something along those lines.
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 2186 at r1](https://reviewable.io:443/reviews/batfish/batfish/752#-L0DXQ6XaQ8J6Acg16s6:-L0Gjqn3QsiHj_enM8N3:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/88cf090cb0b3f9b6931cd294ca7dd06b4579dd4c/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L2186)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

put inside the `if`?
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 2244 at r2](https://reviewable.io:443/reviews/batfish/batfish/752#-L0GFnd4ymDC0gmAvK3u:-L0GHHs7q6Y4Aw9j8KGG:b-pgpx4t) ([raw file](https://github.com/batfish/batfish/blob/d2a66626c501f6e963bb6fd4152aec039075f6d4/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L2244)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I should say, took care to make sure they weren't forgotten when adding these ones.
</blockquote></details>

This is what the code used to do. I don't see any reason for it to continue to do so. The new code simply replaces them.

---

*[projects/batfish/src/test/java/org/batfish/grammar/host/HostTest.java, line 22 at r1](https://reviewable.io:443/reviews/batfish/batfish/752#-L0DUuUnsSXuzrmKw0rG:-L0GjzywSJDGRSEYGdnz:bh5tx13) ([raw file](https://github.com/batfish/batfish/blob/88cf090cb0b3f9b6931cd294ca7dd06b4579dd4c/projects/batfish/src/test/java/org/batfish/grammar/host/HostTest.java#L22)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

what is the file containing the code under test? Is this `HostInterfaceTest`?
</blockquote></details>

`Batfish.java` and ``HostInterface.java`contain changes that cause these tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/752)*

**Comment by arifogel** [comment]
Review status: 26 of 29 files reviewed at latest revision, 3 unresolved discussions.

---

*[projects/batfish/src/test/java/org/batfish/grammar/host/HostTest.java, line 22 at r1](https://reviewable.io:443/reviews/batfish/batfish/752#-L0DUuUnsSXuzrmKw0rG:-L0GklfWkKEssCy65xYh:bjnedjd) ([raw file](https://github.com/batfish/batfish/blob/88cf090cb0b3f9b6931cd294ca7dd06b4579dd4c/projects/batfish/src/test/java/org/batfish/grammar/host/HostTest.java#L22)):*
> java`contain changes that cause these tests.
*cause these tests **to pass**

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/752)*

**Comment by dhalperi** [comment]
*[projects/batfish/src/test/java/org/batfish/grammar/host/HostTest.java, line 22 at r1](https://reviewable.io:443/reviews/batfish/batfish/752#-L0DUuUnsSXuzrmKw0rG:-L0GrnRbEYJwmf0lMDgF:bq6mww1) ([raw file](https://github.com/batfish/batfish/blob/88cf090cb0b3f9b6931cd294ca7dd06b4579dd4c/projects/batfish/src/test/java/org/batfish/grammar/host/HostTest.java#L22)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

> java`contain changes that cause these tests.
*cause these tests **to pass**
</blockquote></details>

Unit tests should be testing specific code, not end-to-end functionality. If the particular function under test is in Batfish, add to `BatfishTest.java` if it's in `HostInterface.java`, add to `HostInterfaceTest.java`. If it's spread across both these two, rethink either the test design or the code under test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/752)*

**Comment by dhalperi** [comment]
Reviewed 3 of 3 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/test/java/org/batfish/grammar/host/HostTest.java, line 22 at r1](https://reviewable.io:443/reviews/batfish/batfish/752#-L0DUuUnsSXuzrmKw0rG:-L0GxHGHyH2t8hZp5xOW:byguld1) ([raw file](https://github.com/batfish/batfish/blob/88cf090cb0b3f9b6931cd294ca7dd06b4579dd4c/projects/batfish/src/test/java/org/batfish/grammar/host/HostTest.java#L22)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Unit tests should be testing specific code, not end-to-end functionality. If the particular function under test is in Batfish, add to `BatfishTest.java` if it's in `HostInterface.java`, add to `HostInterfaceTest.java`. If it's spread across both these two, rethink either the test design or the code under test.
</blockquote></details>

Marking satisfied per discussion.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/752)*

**Comment by dhalperi** [comment]
Self-merge once green.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/752#-:-L0HAF9-FoKr-OoJb_9t:b-fbgfcq)*

**Pull request merged**
