### PR TITLE
Transform: use identity relations to merge more

### PR DESCRIPTION
**Pull request by anothermattbrown**
Identity functions are encoded as a relation between unprimed and primed variables by `unprimedVar.biimp(primedVar)` (biimp is "if and only if").

We use them to merge two Transform transitions that operate on different domains: we use identity relations to expand each transition to operate on the union of the two domains.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8318)* status: all files reviewed, 4 unresolved discussions (waiting on @anothermattbrown)

___
*[`projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transform.java` line 105 at r1](https://reviewable.io/reviews/batfish/batfish/8318#-N2O0b4wAntLamZXc5Tb:-N2O0b4wAntLamZXc5Tc:b-w72mqz) ([raw file](https://github.com/batfish/batfish/blob/1a6deb411a06b3c8aa655efeadfa8ab4b8f82182/projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transform.java#L105)):*
> ```Java
>    * two transforms to have equal domains.
>    */
>   public Optional<Transform> tryOr(Transform other) {
> ```

worth renaming to `or` and dropping `Optional`?



_Code quote:_
```Java
Optional<Transform> tryOr
```
___
*[`projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transform.java` line 114 at r1](https://reviewable.io/reviews/batfish/batfish/8318#-N2O1cfx9vGLyX3Ly_cT:-N2O1cfx9vGLyX3Ly_cU:bdb5gm0) ([raw file](https://github.com/batfish/batfish/blob/1a6deb411a06b3c8aa655efeadfa8ab4b8f82182/projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transform.java#L114)):*
> ```Java
>       BDD otherNewRel = otherIdRel.andEq(other._forwardRelation);
>       return Optional.of(
>           new Transform(newRel.orWith(otherNewRel), _pairingFactory.union(other._pairingFactory)));
> ```

dumb q: why not expandTo in here?



_Code quote:_
```Java
      BDD idRel =
          _pairingFactory.identityRelation(var -> !other._pairingFactory.domainIncludes(var));
      BDD otherIdRel =
          other._pairingFactory.identityRelation(var -> !_pairingFactory.domainIncludes(var));
      BDD newRel = idRel.andEq(_forwardRelation);
      BDD otherNewRel = otherIdRel.andEq(other._forwardRelation);
      return Optional.of(
          new Transform(newRel.orWith(otherNewRel), _pairingFactory.union(other._pairingFactory)));
```
___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPairingFactory.java` line 97 at r1](https://reviewable.io/reviews/batfish/batfish/8318#-N2O-s4PCPmLs0erPT8p:-N2O-s4PCPmLs0erPT8q:b4w2567) ([raw file](https://github.com/batfish/batfish/blob/1a6deb411a06b3c8aa655efeadfa8ab4b8f82182/projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPairingFactory.java#L97)):*
> ```Java
>    */
>   public BDD identityRelation(Predicate<BDD> includeDomainVar) {
>     return _bddFactory.andAll(
> ```

do you care about avoiding BDD leaks?
___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPairingFactory.java` line 115 at r1](https://reviewable.io/reviews/batfish/batfish/8318#-N2O00LDApUa_2Xw3lXm:-N2O00LDApUa_2Xw3lXn:bvle1r4) ([raw file](https://github.com/batfish/batfish/blob/1a6deb411a06b3c8aa655efeadfa8ab4b8f82182/projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPairingFactory.java#L115)):*
> ```Java
> 
>   public BDDPairingFactory union(BDDPairingFactory other) {
>     if (this.equals(other)) {
> ```

consider changing to includes?



_Code quote:_
```Java
equals
```

**Review by anothermattbrown — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8318)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown)

___
*[`projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transform.java` line 105 at r1](https://reviewable.io/reviews/batfish/batfish/8318#-N2O0b4wAntLamZXc5Tb:-N2SDdHW98gV7AUiZlYq:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/1a6deb411a06b3c8aa655efeadfa8ab4b8f82182/projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transform.java#L105)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

worth renaming to `or` and dropping `Optional`?
</blockquote></details>

done
___
*[`projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transform.java` line 114 at r1](https://reviewable.io/reviews/batfish/batfish/8318#-N2O1cfx9vGLyX3Ly_cT:-N2SCON8Ckci6Y7cegLE:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/1a6deb411a06b3c8aa655efeadfa8ab4b8f82182/projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transform.java#L114)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

dumb q: why not expandTo in here?
</blockquote></details>

done
___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPairingFactory.java` line 97 at r1](https://reviewable.io/reviews/batfish/batfish/8318#-N2O-s4PCPmLs0erPT8p:-N2SDvNi2cSjekxLHWek:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/1a6deb411a06b3c8aa655efeadfa8ab4b8f82182/projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPairingFactory.java#L97)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

do you care about avoiding BDD leaks?
</blockquote></details>

done
___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPairingFactory.java` line 115 at r1](https://reviewable.io/reviews/batfish/batfish/8318#-N2O00LDApUa_2Xw3lXm:-N2SDo6e9FuJmfYKJP-H:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/1a6deb411a06b3c8aa655efeadfa8ab4b8f82182/projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPairingFactory.java#L115)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

consider changing to includes?
</blockquote></details>

done

**Review by dhalperi — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8318)* status: all files reviewed, 1 unresolved discussion (waiting on @anothermattbrown)

___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPairingFactory.java` line 104 at r2](https://reviewable.io/reviews/batfish/batfish/8318#-N2SZTx_BwlNMNkUi2R1:-N2SZTx_BwlNMNkUi2R2:bu0lwrf) ([raw file](https://github.com/batfish/batfish/blob/4fc83aeccbaadd05004a2db377f4db1184596d1a/projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPairingFactory.java#L104)):*
> ```Java
>                   return includeDomainVar.test(domVar)
>                       ? domVar.biimp(_bddFactory.ithVar(varPair.getNewVar()))
>                       : null;
> ```

we are still leaking the `ithVar`s here, but this probably does not matter.



_Code quote:_
```Java
                  BDD domVar = _bddFactory.ithVar(varPair.getOldVar());
                  return includeDomainVar.test(domVar)
                      ? domVar.biimp(_bddFactory.ithVar(varPair.getNewVar()))
                      : null;
```

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8318)* status: all files reviewed, 1 unresolved discussion (waiting on @anothermattbrown)

___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPairingFactory.java` line 104 at r2](https://reviewable.io/reviews/batfish/batfish/8318#-N2SZTx_BwlNMNkUi2R1:-N2SZb_F55AeZPWW0j57:bvq00pt) ([raw file](https://github.com/batfish/batfish/blob/4fc83aeccbaadd05004a2db377f4db1184596d1a/projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPairingFactory.java#L104)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

we are still leaking the `ithVar`s here, but this probably does not matter.
</blockquote></details>

(okay to self-resolve and merge in other words)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8318)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown)

**Pull request merged**
