### PR TITLE
support juniper local route export

### PR DESCRIPTION
**Pull request by arifogel**

### CODE REVIEW

**Comment by arifogel** [comment]
Review status: 5 of 12 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Vrf.java, line 27 at r1](https://reviewable.io/reviews/batfish/batfish/1358#-LC7UmD5Bo5cdN6Jt2wI:-LCFPujF0x6D5BWzDD6F:bkkgo5h) ([raw file](https://github.com/batfish/batfish/blob/a660cf4e1d429b881d54ab747ee209804e9b59d5/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Vrf.java#L27)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

This seems like the wrong abstraction – overly specific to how to Juniper chose to do this. Why isn't this treated like an export / redistribution policy on local routes?
</blockquote></details>

I had mixed feelings about this. Perhaps worth an offline discussion.

---

*[projects/batfish/src/main/java/org/batfish/dataplane/bdp/VirtualRouter.java, line 747 at r1](https://reviewable.io/reviews/batfish/batfish/1358#-LC7USui9I7KicZELhR7:-LCFPn6P236hZHo1NNPD:b26wab8) ([raw file](https://github.com/batfish/batfish/blob/a660cf4e1d429b881d54ab747ee209804e9b59d5/projects/batfish/src/main/java/org/batfish/dataplane/bdp/VirtualRouter.java#L747)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Why ignore /32?
</blockquote></details>

Because then the direct route would be a /32 and preempt the local route. You don't see local routes that are /32 empirically.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1358)*

**Comment by dhalperi** [comment]
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Vrf.java, line 27 at r1](https://reviewable.io/reviews/batfish/batfish/1358#-LC7UmD5Bo5cdN6Jt2wI:-LCM1x30ClSoEYwiJc4p:bp1u3pq) ([raw file](https://github.com/batfish/batfish/blob/a660cf4e1d429b881d54ab747ee209804e9b59d5/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Vrf.java#L27)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

I had mixed feelings about this. Perhaps worth an offline discussion.
</blockquote></details>

Happy to chat. Sorry I was too meeting-y on Friday.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1358)*

**Comment by arifogel** [comment]
Review status: 3 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Vrf.java, line 27 at r1](https://reviewable.io/reviews/batfish/batfish/1358#-LC7UmD5Bo5cdN6Jt2wI:-LCVuBDy91nuVToVpv1F:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/a660cf4e1d429b881d54ab747ee209804e9b59d5/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Vrf.java#L27)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Happy to chat. Sorry I was too meeting-y on Friday.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1358)*

**Comment by progwriter** [comment]
:lgtm:

---

Reviewed 6 of 12 files at r1, 18 of 21 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1358#-:-LCWFsNn5SwvueohO3_X:bnfp4nl)*

**Comment by dhalperi** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1358#-:-LCWIzNU3OTBH9_2SEJE:bnfp4nl)*

**Pull request merged**
