### PR TITLE
Autocompletion for TR sources

### PR DESCRIPTION
**Pull request by ratulm**
Reviewing the first commit (which has no functional changes) might help.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 11 of 14 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6409)* status: all files reviewed, 7 unresolved discussions (waiting on @anothermattbrown and @ratulm)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/autocomplete/LocationCompletionMetadata.java, line 25 at r2](https://reviewable.io/reviews/batfish/batfish/6409#-MLogGLICCfSgTyRxUm_:-MLogGLICCfSgTyRxUma:bxh7cwy) ([raw file](https://github.com/batfish/batfish/blob/010fb5384337b75ddb6c8a5231c1fe873e08fc96/projects/batfish-common-protocol/src/main/java/org/batfish/common/autocomplete/LocationCompletionMetadata.java#L25)):*
> ```
>   private final boolean _isSource;
>   private final boolean _isTracerouteSource;
> ```

naming here is weird. It seems like the implication should be that isTracerouteSource => isSource, but it's actually the other way around right?

Maybe isSourceWithIps?
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/autocomplete/LocationCompletionMetadata.java, line 27 at r2](https://reviewable.io/reviews/batfish/batfish/6409#-MLobHm29cNARTx_RFSh:-MLobHm3Bzyb8E56lMF1:b-ku6gta) ([raw file](https://github.com/batfish/batfish/blob/010fb5384337b75ddb6c8a5231c1fe873e08fc96/projects/batfish-common-protocol/src/main/java/org/batfish/common/autocomplete/LocationCompletionMetadata.java#L27)):*
> ```
> isSource, true
> ```
why is the third argument `true` not `isSource`?
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/autocomplete/LocationCompletionMetadata.java, line 42 at r2](https://reviewable.io/reviews/batfish/batfish/6409#-MLobSBE1iNZjy3RGvvB:-MLobSBE1iNZjy3RGvvC:b-dctee3) ([raw file](https://github.com/batfish/batfish/blob/010fb5384337b75ddb6c8a5231c1fe873e08fc96/projects/batfish-common-protocol/src/main/java/org/batfish/common/autocomplete/LocationCompletionMetadata.java#L42)):*
> ```
> Location
> ```
%s, PROP_LOCATION

and the same for the below 2. That keeps the error and the `@JsonProperty` in sync, they are all different here.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CompletionMetadataUtils.java, line 238 at r2](https://reviewable.io/reviews/batfish/batfish/6409#-MLobhRK5vmEJp6CyiTy:-MLobhRK5vmEJp6CyiTz:brf8w59) ([raw file](https://github.com/batfish/batfish/blob/010fb5384337b75ddb6c8a5231c1fe873e08fc96/projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CompletionMetadataUtils.java#L238)):*
> ```
> getSourceLocations
> ```

getLocationCompletionMetadata?
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CompletionMetadataUtils.java, line 284 at r2](https://reviewable.io/reviews/batfish/batfish/6409#-MLofPYnC2RfImTruTYe:-MLofPYnC2RfImTruTYf:br09iqu) ([raw file](https://github.com/batfish/batfish/blob/010fb5384337b75ddb6c8a5231c1fe873e08fc96/projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CompletionMetadataUtils.java#L284)):*
> ```
> location instanceof InterfaceLinkLocation
> ```
need to eliminate L2 interfaces here, I think.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/AutoCompleteUtils.java, line 782 at r2](https://reviewable.io/reviews/batfish/batfish/6409#-MLocGmWDXV-mBYQdH6d:-MLocGmWDXV-mBYQdH6e:bwk0hbh) ([raw file](https://github.com/batfish/batfish/blob/010fb5384337b75ddb6c8a5231c1fe873e08fc96/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/AutoCompleteUtils.java#L782)):*
> ```
> completion
> ```
typo: completion
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/AutoCompleteUtils.java, line 793 at r2](https://reviewable.io/reviews/batfish/batfish/6409#-MLofxQxEhvdnA6HhSH6:-MLofxQxEhvdnA6HhSH7:btizgx7) ([raw file](https://github.com/batfish/batfish/blob/010fb5384337b75ddb6c8a5231c1fe873e08fc96/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/AutoCompleteUtils.java#L793)):*
> ```
>                     .sorted(
>                         (loc1, loc2) ->
>                             loc1.isSource() == loc2.isSource() ? 0 : loc1.isSource() ? -1 : 1)
> ```
I don't think this is guaranteed to be sensible (it might produce totally weird behavior, and different across successive calls, since it's not a total order).

Probably just materialize the list and then concatenate the two halves?

**Review by dhalperi — COMMENTED** [review]
> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6409)* status: all files reviewed, 1 unresolved discussion (waiting on @anothermattbrown and @ratulm)

___
*[.idea/vcs.xml, line 5 at r3](https://reviewable.io/reviews/batfish/batfish/6409#-MLpA57z1A2NmSAXL4d5:-MLpA57z1A2NmSAXL4d6:bb7f4vo) ([raw file](https://github.com/batfish/batfish/blob/62c2e45a28518ceefda538abf6cac686bd057457/.idea/vcs.xml#L5)):*
> ```XML
>   <component name="VcsDirectoryMappings">
>     <mapping directory="$PROJECT_DIR$" vcs="Git" />
>     <mapping directory="$PROJECT_DIR$/bazel-batfish" vcs="Git" />
> ```

drop

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6409)* status: 13 of 14 files reviewed, 1 unresolved discussion (waiting on @anothermattbrown, @dhalperi, and @ratulm)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/autocomplete/LocationCompletionMetadata.java, line 27 at r2](https://reviewable.io/reviews/batfish/batfish/6409#-MLobHm29cNARTx_RFSh:-MLp3D6S1B4GZkSdnUZE:b-e85138) ([raw file](https://github.com/batfish/batfish/blob/010fb5384337b75ddb6c8a5231c1fe873e08fc96/projects/batfish-common-protocol/src/main/java/org/batfish/common/autocomplete/LocationCompletionMetadata.java#L27)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> isSource, true
> ```
why is the third argument `true` not `isSource`?
</blockquote></details>

good point.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/AutoCompleteUtils.java, line 782 at r2](https://reviewable.io/reviews/batfish/batfish/6409#-MLocGmWDXV-mBYQdH6d:-MLp9WZm9m74OdTRg-HR:b32vmt) ([raw file](https://github.com/batfish/batfish/blob/010fb5384337b75ddb6c8a5231c1fe873e08fc96/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/AutoCompleteUtils.java#L782)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> completion
> ```
typo: completion
</blockquote></details>

??
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/AutoCompleteUtils.java, line 793 at r2](https://reviewable.io/reviews/batfish/batfish/6409#-MLofxQxEhvdnA6HhSH6:-MLpZk935BxDYXs0hlhs:b9847hq) ([raw file](https://github.com/batfish/batfish/blob/010fb5384337b75ddb6c8a5231c1fe873e08fc96/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/AutoCompleteUtils.java#L793)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
>                     .sorted(
>                         (loc1, loc2) ->
>                             loc1.isSource() == loc2.isSource() ? 0 : loc1.isSource() ? -1 : 1)
> ```
I don't think this is guaranteed to be sensible (it might produce totally weird behavior, and different across successive calls, since it's not a total order).

Probably just materialize the list and then concatenate the two halves?
</blockquote></details>

yeah, that logic was totally busted because of passing through a map.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6409)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown)

**Pull request merged**
