### PR TITLE
FortiOS: support policy reordering

### PR DESCRIPTION
**Pull request by sfraint**

### CODE REVIEW

**Review by corinaminer — COMMENTED** [review]
> Reviewed 6 of 9 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6836)* status: all files reviewed, 2 unresolved discussions (waiting on @arifogel and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 1032 at r2](https://reviewable.io/reviews/batfish/batfish/6836#-MXKFeaaEUY-tGM-6E1m:-MXKFeaaEUY-tGM-6E1n:b-ebub8a) ([raw file](https://github.com/batfish/batfish/blob/4c213940450e43b9a0f1c3aec17f1a37b4e66f5b/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L1032)):*
> ```Java
>     if (!nameOpt.isPresent() || !pivotOpt.isPresent()) {
>       return;
>     }
> ```

is there any point converting to longs? do we care to have "foo isn't a legal policy number" messages, rather than "no such policy as foo" messages?
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 1045 at r2](https://reviewable.io/reviews/batfish/batfish/6836#-MXKGGZ-4aRpH3-mscpx:-MXKGGZ-4aRpH3-mscpy:b560rp2) ([raw file](https://github.com/batfish/batfish/blob/4c213940450e43b9a0f1c3aec17f1a37b4e66f5b/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L1045)):*
> ```Java
>     }
>     if (!_c.getPolicies().containsKey(pivot)) {
>       warn(ctx, "Cannot move around a non-existent policy");
> ```

Since there are two policies mentioned in the line, I'd format the warnings to include the nonexistent policy name, just for extra clarity.

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6836)* status: all files reviewed, 2 unresolved discussions (waiting on @arifogel and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 1032 at r2](https://reviewable.io/reviews/batfish/batfish/6836#-MXKFeaaEUY-tGM-6E1m:-MXKH6lB7RC09HtNUrs4:b-i10a7u) ([raw file](https://github.com/batfish/batfish/blob/4c213940450e43b9a0f1c3aec17f1a37b4e66f5b/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L1032)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

is there any point converting to longs? do we care to have "foo isn't a legal policy number" messages, rather than "no such policy as foo" messages?
</blockquote></details>

(thought our general approach was to validate names in definitions, but not references)

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6836)* status: 5 of 9 files reviewed, 2 unresolved discussions (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 1032 at r2](https://reviewable.io/reviews/batfish/batfish/6836#-MXKFeaaEUY-tGM-6E1m:-MXKIvo90LUB2g8CbnBS:b-41l00b) ([raw file](https://github.com/batfish/batfish/blob/4c213940450e43b9a0f1c3aec17f1a37b4e66f5b/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L1032)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

(thought our general approach was to validate names in definitions, but not references)
</blockquote></details>

yeah, simplified it a bit
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 1045 at r2](https://reviewable.io/reviews/batfish/batfish/6836#-MXKGGZ-4aRpH3-mscpx:-MXKKfeX0PRp0hCD1rSn:bvnrpcm) ([raw file](https://github.com/batfish/batfish/blob/4c213940450e43b9a0f1c3aec17f1a37b4e66f5b/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L1045)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Since there are two policies mentioned in the line, I'd format the warnings to include the nonexistent policy name, just for extra clarity.
</blockquote></details>

updated

**Review by corinaminer — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6836#-:-MXKN8BS4L0rXPkpqwJi:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Pull request merged**
