### PR TITLE
Default role dimension

### PR DESCRIPTION
**Pull request by ratulm**
Per discussion to improve usability.

### CODE REVIEW

**Comment by millstein** [comment]
Review status: 0 of 11 files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/role/NodeRolesData.java, line 80 at r1](https://reviewable.io/reviews/batfish/batfish/1458#-LD7SeWQ7xqh15Wd7ZRP:-LD7SeWQ7xqh15Wd7ZRQ:b2n7f2t) ([raw file](https://github.com/batfish/batfish/blob/840f5f7f094b4c6b792c1a96bc753aa26bb1f811/projects/batfish-common-protocol/src/main/java/org/batfish/role/NodeRolesData.java#L80)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>     if (opt.isPresent()) {
>       return opt.get();
>     } else {
>       throw new NoSuchElementException(String.format("Role dimension '%s' not found", dimension));
> ```
</details>


The orElseThrow method in Optional is a simpler way to do this:

return opt.orElseThrow(() -> new NoSuchElementException(...))

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1458)*

**Comment by millstein** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/role/NodeRolesData.java, line 118 at r1](https://reviewable.io/reviews/batfish/batfish/1458#-LD7TBNEC3fcDpRNdZZe:-LD7TBNEC3fcDpRNdZZf:bh5vm9b) ([raw file](https://github.com/batfish/batfish/blob/840f5f7f094b4c6b792c1a96bc753aa26bb1f811/projects/batfish-common-protocol/src/main/java/org/batfish/role/NodeRolesData.java#L118)):*
> ```
>     return null;
>   }
> ```

I hate null.  Why not return an Optional if you are going to do it this way, so you force the caller to deal with the possibility that nothing is returned?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1458)*

**Comment by millstein** [comment]
Review status: 0 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/role/NodeRolesData.java, line 57 at r1](https://reviewable.io/reviews/batfish/batfish/1458#-LD7WMFNB7NUGs_7UAsA:-LD7WMFNB7NUGs_7UAsB:b-8ycbzn) ([raw file](https://github.com/batfish/batfish/blob/840f5f7f094b4c6b792c1a96bc753aa26bb1f811/projects/batfish-common-protocol/src/main/java/org/batfish/role/NodeRolesData.java#L57)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>   private Optional<NodeRoleDimension> getNodeRoleDimension(String dimension) {
>     return _roleDimensions.stream().filter(d -> d.getName().equals(dimension)).findFirst();
>  
>   }
> ```
</details>


As I understand it, this code used to throw a NoSuchElementException but now it returns an Optional instead.  So I think you need to update the getMatchingNodes method in NodesSpecifier, which is catching a NoSuchElementException.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1458)*

**Comment by ratulm** [comment]
Review status: 0 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/role/NodeRolesData.java, line 57 at r1](https://reviewable.io/reviews/batfish/batfish/1458#-LD7WMFNB7NUGs_7UAsA:-LD7ol0PEsWMAuysDT3J:b-iqavje) ([raw file](https://github.com/batfish/batfish/blob/840f5f7f094b4c6b792c1a96bc753aa26bb1f811/projects/batfish-common-protocol/src/main/java/org/batfish/role/NodeRolesData.java#L57)):*
<details><summary><i>Previously, millstein wrote…</i></summary><blockquote>

> ```
>   private Optional<NodeRoleDimension> getNodeRoleDimension(String dimension) {
>     return _roleDimensions.stream().filter(d -> d.getName().equals(dimension)).findFirst();
>  
>   }
> ```

As I understand it, this code used to throw a NoSuchElementException but now it returns an Optional instead.  So I think you need to update the getMatchingNodes method in NodesSpecifier, which is catching a NoSuchElementException.
</blockquote></details>

This function wasn't being called directly. The calling context was throwing the exception. Anyway, the point is moot now with other changes. 

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/role/NodeRolesData.java, line 118 at r1](https://reviewable.io/reviews/batfish/batfish/1458#-LD7TBNEC3fcDpRNdZZe:-LD7pAAZCtMXyBPq4D3C:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/840f5f7f094b4c6b792c1a96bc753aa26bb1f811/projects/batfish-common-protocol/src/main/java/org/batfish/role/NodeRolesData.java#L118)):*
<details><summary><i>Previously, millstein wrote…</i></summary><blockquote>

> ```
>     return null;
>   }
> ```

I hate null.  Why not return an Optional if you are going to do it this way, so you force the caller to deal with the possibility that nothing is returned?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1458)*

**Comment by ratulm** [comment]
Review status: 0 of 13 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/role/NodeRolesData.java, line 80 at r1](https://reviewable.io/reviews/batfish/batfish/1458#-LD7SeWQ7xqh15Wd7ZRP:-LD7pDBT7r_EK20eb51b:b2nhl1i) ([raw file](https://github.com/batfish/batfish/blob/840f5f7f094b4c6b792c1a96bc753aa26bb1f811/projects/batfish-common-protocol/src/main/java/org/batfish/role/NodeRolesData.java#L80)):*
<details><summary><i>Previously, millstein wrote…</i></summary><blockquote>

> ```
>     if (opt.isPresent()) {
>       return opt.get();
>     } else {
>       throw new NoSuchElementException(String.format("Role dimension '%s' not found", dimension));
> ```

The orElseThrow method in Optional is a simpler way to do this:

return opt.orElseThrow(() -> new NoSuchElementException(...))
</blockquote></details>

Nice. Used in other places.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1458)*

**Pull request merged**
