### PR TITLE
Track non-local interface dependencies

### PR DESCRIPTION
**Pull request by anothermattbrown**
Previously, we tracked _local_ interface dependencies: e.g. a portchannel depends on at least one of its members interfaces being active, a subinterface depends on its superinterface being active, etc. This PR adds _non-local_ interface dependency tracking: for physical or LACP interfaces, if the `Layer1Topology` identifies a neighbor interface, depend on that neighbor being active.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7407)* status: all files reviewed, 1 unresolved discussion (waiting on @anothermattbrown)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/interface_dependency/InterfaceDependencies.java, line 136 at r1](https://reviewable.io/reviews/batfish/batfish/7407#-MjpyFn8BVTP6WQ4uQtb:-MjpyFn8BVTP6WQ4uQtc:b-dbzv4l) ([raw file](https://github.com/batfish/batfish/blob/2f67a4ae6705617caa0c95ddbf8a3919b75f6012/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/interface_dependency/InterfaceDependencies.java#L136)):*
> ```
>  _depGraph.addVertex(src);
> ```
I have some memory that this crashes if you do it twice. Can you deny / config+comment why we're okay?

**Review by anothermattbrown — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7407)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/interface_dependency/InterfaceDependencies.java, line 136 at r1](https://reviewable.io/reviews/batfish/batfish/7407#-MjpyFn8BVTP6WQ4uQtb:-MjpzTnm9g2kJ4CoPZov:bblvmho) ([raw file](https://github.com/batfish/batfish/blob/2f67a4ae6705617caa0c95ddbf8a3919b75f6012/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/interface_dependency/InterfaceDependencies.java#L136)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
>  _depGraph.addVertex(src);
> ```
I have some memory that this crashes if you do it twice. Can you deny / config+comment why we're okay?
</blockquote></details>

I can confirm you can re-add. You can't add an edge if the vertices don't exist though. Added a comment

**Review by dhalperi — COMMENTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7407#-:-Mjq13GD6r1UsNtzmj81:bnfp4nl)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @dhalperi)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7407)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown)

**Pull request merged**
