### PR TITLE
Cisco OSPF reference bandwidth

### PR DESCRIPTION
**Pull request by dhalperi**
Draft PR to set up larger work on #873

---
This change is [Reviewable](https://reviewable.io/reviews/batfish/batfish/886)

### CODE REVIEW

**Comment by arifogel** [comment]
Mostly good. Seems like a prime candidate for junit tests.

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/886#-:-L48O3tKo-AZbTiI2Soq:b-20kpgl)*

**Comment by arifogel** [comment]
:lgtm:

---

Reviewed 12 of 13 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/OspfProcess.java, line 87 at r2](https://reviewable.io:443/reviews/batfish/batfish/886#-L49hYqRCLK7IC_GRAxL:-L4D41C3H_qofIo80QHW:bo92v56) ([raw file](https://github.com/batfish/batfish/blob/b093414647ea5462bc9382650db0ea9a089b6684/projects/batfish/src/main/java/org/batfish/representation/cisco/OspfProcess.java#L87)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

@arifogel which other vendors use the Cisco parser?

Before the recent revision, the code would have crashed on Arista devices (since the default throws), but it was not caught by any existing test.

Should I make the default just use IOS default?
</blockquote></details>

I don't remember offhand which other vendors use that parse, but it's easy enough to check the switch case in `ParseVendorConfigurationJob`.
I don't think it's a good idea to have a default. I'd rather it throw by default.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/886#-:-L4D619-lhG0WITLRgOF:bnfp4nl)*

**Comment by dhalperi** [comment]
Review status: 19 of 20 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/OspfProcess.java, line 87 at r2](https://reviewable.io:443/reviews/batfish/batfish/886#-L49hYqRCLK7IC_GRAxL:-L4DrfZ_Tfl_a73CSZes:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/b093414647ea5462bc9382650db0ea9a089b6684/projects/batfish/src/main/java/org/batfish/representation/cisco/OspfProcess.java#L87)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

I don't remember offhand which other vendors use that parse, but it's easy enough to check the switch case in `ParseVendorConfigurationJob`.
I don't think it's a good idea to have a default. I'd rather it throw by default.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/886)*

**Comment by dhalperi** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/886)*

**Pull request merged**
