### PR TITLE
Fix Juniper flattening of hierarchical mixed with flat

### PR DESCRIPTION
**Pull request by arifogel**
- add lines monotonically during flattening
- implement 'replace' directives by inserting 'delete' line before inserting set lines for deeper elements
- implement 'inactive' directives by inserting 'deactivate' lines before inserting set lines for deeper elements

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 11 of 11 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8667)* status: all files reviewed, 2 unresolved discussions (waiting on @anothermattbrown, @arifogel, @progwriter, and @sfraint)

___
*[`projects/batfish/src/main/java/org/batfish/grammar/juniper/JuniperFlattener.java` line 192 at r1](https://reviewable.io/reviews/batfish/batfish/8667#-NP-yiHZ4A230VNIGDKs:-NP-yiH_8u6coG_c8_dF:bacpaxe) ([raw file](https://github.com/batfish/batfish/blob/e8faef7df43a49858d5af8c6abae28615102251c/projects/batfish/src/main/java/org/batfish/grammar/juniper/JuniperFlattener.java#L192)):*
> ```Java
>     for (int i = 0; i < suffixWords.size(); i++) {
>       _currentStatement.remove(_currentStatement.size() - 1);
>     }
> ```

I'm sure I'm missing something, but I can't figure out where `suffixWords` are used. I see `_currentStatement` changing, but where is it used in the body?



_Code quote:_
```Java
    _currentStatement.addAll(suffixWords);

    StringBuilder sb = new StringBuilder();
    sb.append(command);
    for (List<WordContext> line : _stack) {
      int originalLine = _allFlatStatements.size() + _headerLineCount;
      for (WordContext wordCtx : line) {
        sb.append(" ");
        // Offset new line number by header line count
        _lineMap.setOriginalLine(originalLine, sb.length(), wordCtx.WORD().getSymbol().getLine());
        sb.append(wordCtx.getText());
      }
    }
    String setStatementText = sb.toString();
    // Record index of new statement in the current subtree

    _allFlatStatements.add(setStatementText);

    for (int i = 0; i < suffixWords.size(); i++) {
      _currentStatement.remove(_currentStatement.size() - 1);
    }
```
___
*[`tests/parsing-tests/unit-tests-undefined.ref` line 2619 at r1](https://reviewable.io/reviews/batfish/batfish/8667#-NP-z4WW6zCXxPC4jxV6:-NP-z4WW6zCXxPC4jxV7:bcbcepu) ([raw file](https://github.com/batfish/batfish/blob/e8faef7df43a49858d5af8c6abae28615102251c/tests/parsing-tests/unit-tests-undefined.ref#L2619)):*
> ```
>           "filename" : "configs/gh-2658-juniper-vrf-import-export.cfg",
>           "lines" : [
>             87
> ```

This is surprising, right? I wouldn't have thought this would change without input changes.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8667)* status: all files reviewed, 2 unresolved discussions (waiting on @anothermattbrown, @dhalperi, @progwriter, and @sfraint)

___
*[`projects/batfish/src/main/java/org/batfish/grammar/juniper/JuniperFlattener.java` line 192 at r1](https://reviewable.io/reviews/batfish/batfish/8667#-NP-yiHZ4A230VNIGDKs:-NP01hB6CQrrRjA8XP0_:bf1mxka) ([raw file](https://github.com/batfish/batfish/blob/e8faef7df43a49858d5af8c6abae28615102251c/projects/batfish/src/main/java/org/batfish/grammar/juniper/JuniperFlattener.java#L192)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I'm sure I'm missing something, but I can't figure out where `suffixWords` are used. I see `_currentStatement` changing, but where is it used in the body?
</blockquote></details>

`_currentStatement` is the top element of `_stack` at this point. Perhaps it would be clearer to just explicitly grab the top element of the stack, rather than rely on this (unwritten) invariant.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8667)* status: all files reviewed, 2 unresolved discussions (waiting on @anothermattbrown, @dhalperi, @progwriter, and @sfraint)

___
*[`tests/parsing-tests/unit-tests-undefined.ref` line 2619 at r1](https://reviewable.io/reviews/batfish/batfish/8667#-NP-z4WW6zCXxPC4jxV6:-NP02_PJ5Bu_YSHeFpzn:bsin049) ([raw file](https://github.com/batfish/batfish/blob/e8faef7df43a49858d5af8c6abae28615102251c/tests/parsing-tests/unit-tests-undefined.ref#L2619)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

This is surprising, right? I wouldn't have thought this would change without input changes.
</blockquote></details>

I admit I'm a bit lost here. Neither the before nor after lines could not be referring to the hierarchical text FWICT.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8667)* status: all files reviewed, 2 unresolved discussions (waiting on @anothermattbrown, @dhalperi, @progwriter, and @sfraint)

___
*[`tests/parsing-tests/unit-tests-undefined.ref` line 2619 at r1](https://reviewable.io/reviews/batfish/batfish/8667#-NP-z4WW6zCXxPC4jxV6:-NP02m9K2lorhkCx17YP:b-l1a2u4) ([raw file](https://github.com/batfish/batfish/blob/e8faef7df43a49858d5af8c6abae28615102251c/tests/parsing-tests/unit-tests-undefined.ref#L2619)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

I admit I'm a bit lost here. Neither the before nor after lines could not be referring to the hierarchical text FWICT.
</blockquote></details>

*neither could be referring

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8667)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @anothermattbrown, @dhalperi, @progwriter, and @sfraint)

___
*[`projects/batfish/src/main/java/org/batfish/grammar/juniper/JuniperFlattener.java` line 192 at r1](https://reviewable.io/reviews/batfish/batfish/8667#-NP-yiHZ4A230VNIGDKs:-NP044ji9XwiSmsDcWNx:b-1qb34x) ([raw file](https://github.com/batfish/batfish/blob/e8faef7df43a49858d5af8c6abae28615102251c/projects/batfish/src/main/java/org/batfish/grammar/juniper/JuniperFlattener.java#L192)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

`_currentStatement` is the top element of `_stack` at this point. Perhaps it would be clearer to just explicitly grab the top element of the stack, rather than rely on this (unwritten) invariant.
</blockquote></details>

Meh, went with just documenting it and adding a documentary assertion.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8667)* status: all files reviewed, 2 unresolved discussions (waiting on @anothermattbrown, @arifogel, @progwriter, and @sfraint)

___
*[`projects/batfish/src/main/java/org/batfish/grammar/juniper/JuniperFlattener.java` line 192 at r1](https://reviewable.io/reviews/batfish/batfish/8667#-NP-yiHZ4A230VNIGDKs:-NP3Emak8rjpydwEhEeY:bek9uf4) ([raw file](https://github.com/batfish/batfish/blob/e8faef7df43a49858d5af8c6abae28615102251c/projects/batfish/src/main/java/org/batfish/grammar/juniper/JuniperFlattener.java#L192)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Meh, went with just documenting it and adding a documentary assertion.
</blockquote></details>

Good doc, nice assertion, and the assertion is failing :) So maybe that helps us understand?

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8667)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @anothermattbrown, @dhalperi, @progwriter, and @sfraint)

___
*[`projects/batfish/src/main/java/org/batfish/grammar/juniper/JuniperFlattener.java` line 192 at r1](https://reviewable.io/reviews/batfish/batfish/8667#-NP-yiHZ4A230VNIGDKs:-NP3bFuZBL6DjjbHP0T3:byi5jc5) ([raw file](https://github.com/batfish/batfish/blob/e8faef7df43a49858d5af8c6abae28615102251c/projects/batfish/src/main/java/org/batfish/grammar/juniper/JuniperFlattener.java#L192)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Good doc, nice assertion, and the assertion is failing :) So maybe that helps us understand?
</blockquote></details>

Yeah, so assertion wasn't true for most callers of `constructSetLine` (which don't add suffix words anyway).
So I just removed the assertion and explicitly grabbed the last list. However, for those callers, the last element was often an immutable list. So I added a check that suffixWords is nonempty before trying to modify that list. The unspoken assumption is that if there are suffixwords to add, it's because those words would be added anyway later during the visitation (therefore the current list is not immutable).

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8667)* status: all files reviewed, 1 unresolved discussion (waiting on @anothermattbrown, @arifogel, @progwriter, and @sfraint)

___
*[`tests/parsing-tests/unit-tests-undefined.ref` line 2619 at r1](https://reviewable.io/reviews/batfish/batfish/8667#-NP-z4WW6zCXxPC4jxV6:-NP4FijA6NWM2WO9G_G4:b-cy8vd6) ([raw file](https://github.com/batfish/batfish/blob/e8faef7df43a49858d5af8c6abae28615102251c/tests/parsing-tests/unit-tests-undefined.ref#L2619)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

*neither could be referring
</blockquote></details>

We should TAL at this, I'll try to find time.

**Review by dhalperi — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8667#-:-NP4GRWW4QKjiqAACB1E:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @anothermattbrown, @arifogel, @progwriter, and @sfraint)

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8667)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown, @progwriter, and @sfraint)

___
*[`tests/parsing-tests/unit-tests-undefined.ref` line 2619 at r1](https://reviewable.io/reviews/batfish/batfish/8667#-NP-z4WW6zCXxPC4jxV6:-NP58lAK5o7fCezDiCcs:bwxk8te) ([raw file](https://github.com/batfish/batfish/blob/e8faef7df43a49858d5af8c6abae28615102251c/tests/parsing-tests/unit-tests-undefined.ref#L2619)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

We should TAL at this, I'll try to find time.
</blockquote></details>

This reference is actually on L231, so I have no clue what's going on. The old value was wrong, too.

Good enough for me!

**Pull request merged**
