### PR TITLE
make AnswerElement an abstract class 

### PR DESCRIPTION
**Pull request by ratulm**
enables getting and setting AnswerSummary, without each subclass having to override it

### CODE REVIEW

**Comment by dhalperi** [comment]
Reviewed 1 of 65 files at r1.
Review status: 1 of 75 files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/BdpAnswerElement.java, line 11 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1075#-L7yrUiSCUGT---rA0wG:-L7yrUiSCUGT---rA0wH:b-5lmpgi) ([raw file](https://github.com/batfish/batfish/blob/44c6b15bcef006fbdc301a502b24a46c1580c9b7/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/BdpAnswerElement.java#L11)):*
> ```Java
> import org.batfish.datamodel.Prefix;
> 
> public class BdpAnswerElement extends DataPlaneAnswerElement implements Serializable {
> ```

`implements Serializable` should not be in a class that `extends AbstractElement` -- it's inherited.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1075)*

**Comment by dhalperi** [comment]
Reviewed 64 of 65 files at r1, 10 of 10 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/DataPlaneAnswerElement.java, line 6 at r3](https://beta.reviewable.io/reviews/batfish/batfish/1075#-L7zYZCH9K8D9ws1-S2p:-L7zYZCH9K8D9ws1-S2q:b-s81gdp) ([raw file](https://github.com/batfish/batfish/blob/4bc963656c72c6c8d46caf8d63de988a704d9f3e/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/DataPlaneAnswerElement.java#L6)):*
>  implements Serializable

Drop? Actually, I see these issues (in a few other places too) were already there? So never mind.

---

*[projects/question/src/main/java/org/batfish/question/jsonpath/JsonPathQuestionPlugin.java, line 129 at r3](https://beta.reviewable.io/reviews/batfish/batfish/1075#-L7zZKzF5xaOBtm0Y37s:-L7zZKzF5xaOBtm0Y37t:bidv9xu) ([raw file](https://github.com/batfish/batfish/blob/4bc963656c72c6c8d46caf8d63de988a704d9f3e/projects/question/src/main/java/org/batfish/question/jsonpath/JsonPathQuestionPlugin.java#L129)):*
> ```Java
>     @Override
>     public void setSummary(AnswerSummary summary) {
>       _summary = summary;
> ```

is this needed? Isn't this in the base abstract class?

(actually, should the base functions be `final`?)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1075)*

**Comment by ratulm** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/DataPlaneAnswerElement.java, line 6 at r3](https://beta.reviewable.io/reviews/batfish/batfish/1075#-L7zYZCH9K8D9ws1-S2p:-L7zj3MD0sDC4l-SEhrn:b-djgwg7) ([raw file](https://github.com/batfish/batfish/blob/4bc963656c72c6c8d46caf8d63de988a704d9f3e/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/DataPlaneAnswerElement.java#L6)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

>  implements Serializable

Drop? Actually, I see these issues (in a few other places too) were already there? So never mind.
</blockquote></details>

I believe that this is needed because we use java serialization for dataplane? 

---

*[projects/question/src/main/java/org/batfish/question/jsonpath/JsonPathQuestionPlugin.java, line 129 at r3](https://beta.reviewable.io/reviews/batfish/batfish/1075#-L7zZKzF5xaOBtm0Y37s:-L7zjSuJ9Jz-doSX2PQf:b-adwid0) ([raw file](https://github.com/batfish/batfish/blob/4bc963656c72c6c8d46caf8d63de988a704d9f3e/projects/question/src/main/java/org/batfish/question/jsonpath/JsonPathQuestionPlugin.java#L129)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

is this needed? Isn't this in the base abstract class?

(actually, should the base functions be `final`?)
</blockquote></details>

ah, leftover. good catch. made final.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1075)*

**Comment by dhalperi** [comment]
Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/DataPlaneAnswerElement.java, line 6 at r3](https://reviewable.io:443/reviews/batfish/batfish/1075#-L7zYZCH9K8D9ws1-S2p:-L8-NjKHvIyrrw6HaXNV:bfbtcg6) ([raw file](https://github.com/batfish/batfish/blob/4bc963656c72c6c8d46caf8d63de988a704d9f3e/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/DataPlaneAnswerElement.java#L6)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

I believe that this is needed because we use java serialization for dataplane? 
</blockquote></details>

Surely we don't serialize the AnswerElement as part of the data plane, do we? That would be absurd. But no clue, maybe it's correct.

We definitely should not be serializing the same class two different ways.

---

*[projects/question/src/main/java/org/batfish/question/UndefinedReferencesQuestionPlugin.java, line 30 at r4](https://reviewable.io:443/reviews/batfish/batfish/1075#-L8-N60rVbm0taK1HjMZ:-L8-N60rVbm0taK1HjM_:b-hd4x7x) ([raw file](https://github.com/batfish/batfish/blob/f70c322ae083d60b3310c9db7abc71d3fe975376/projects/question/src/main/java/org/batfish/question/UndefinedReferencesQuestionPlugin.java#L30)):*
> ```Java
> 
>     public UndefinedReferencesAnswerElement() {
>       _summary = new AnswerSummary();
> ```

why expose vs just call setter? Or set in the constructor of parent?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/1075)*

**Comment by ratulm** [comment]
Review status: 74 of 77 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/DataPlaneAnswerElement.java, line 6 at r3](https://reviewable.io:443/reviews/batfish/batfish/1075#-L7zYZCH9K8D9ws1-S2p:-L8-SKpXg4MKIvC5HG6D:b9d5r43) ([raw file](https://github.com/batfish/batfish/blob/4bc963656c72c6c8d46caf8d63de988a704d9f3e/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/DataPlaneAnswerElement.java#L6)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Surely we don't serialize the AnswerElement as part of the data plane, do we? That would be absurd. But no clue, maybe it's correct.

We definitely should not be serializing the same class two different ways.
</blockquote></details>

Lines 1000 and 2372 of Batfish.java start failing if DataPlaneAnswerElement is not Serializable. Or, perhaps you are talking about something else?

---

*[projects/question/src/main/java/org/batfish/question/UndefinedReferencesQuestionPlugin.java, line 30 at r4](https://reviewable.io:443/reviews/batfish/batfish/1075#-L8-N60rVbm0taK1HjMZ:-L8-S_5G5685PTkEi_7Q:b-ijancl) ([raw file](https://github.com/batfish/batfish/blob/f70c322ae083d60b3310c9db7abc71d3fe975376/projects/question/src/main/java/org/batfish/question/UndefinedReferencesQuestionPlugin.java#L30)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

why expose vs just call setter? Or set in the constructor of parent?
</blockquote></details>

called setting. setting in parent of the constructor has an issue at the moment because not all subclasses are filling the summary field. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/1075)*

**Comment by dhalperi** [comment]
Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/DataPlaneAnswerElement.java, line 6 at r3](https://reviewable.io:443/reviews/batfish/batfish/1075#-L7zYZCH9K8D9ws1-S2p:-L8-T1-kk7-z8OkmXG5q:b56ekdo) ([raw file](https://github.com/batfish/batfish/blob/4bc963656c72c6c8d46caf8d63de988a704d9f3e/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/DataPlaneAnswerElement.java#L6)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

Lines 1000 and 2372 of Batfish.java start failing if DataPlaneAnswerElement is not Serializable. Or, perhaps you are talking about something else?
</blockquote></details>

This makes me very sad. But no issue in this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/1075)*

**Comment by dhalperi** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/1075#-:-L8-T8R-jpnPtkv43T2h:bnfp4nl)*

**Pull request merged**
