### PR TITLE
Add PAN interface extractions

### PR DESCRIPTION
**Pull request by sfraint**
Add initial Palo Alto Networks interface extractions

### CODE REVIEW

**Comment by arifogel** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed, 1 unresolved discussion (waiting on @sfraint, @anothermattbrown, and @haverma)

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_network.g4, line 37 at r1](https://reviewable.io/reviews/batfish/batfish/1646#-LEqfNuV8dhFmTLlxVTi:-LEqfNuW93VVWeArKgw1:bhamnrn) ([raw file](https://github.com/batfish/batfish/blob/fdce5998fe771e0fedc6c9e5efc764c282804eb3/projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_network.g4#L37)):*
> ```ANTLR
> snie_comment
> :
>     COMMENT text = variable
> ```

You almost certainly want to use a lexer mode here. That mode should emit a single token consisting of everything until the end of the line. You should enter the mode after the `COMMENT` token is emitted.

Ignore if the only valid multiword comment is a double-quoted string. In this case, make sure to unquote the text before you store it.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1646)*

**Comment by haverma** [comment]
Review status: all files reviewed, 8 unresolved discussions (waiting on @sfraint and @anothermattbrown)

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java, line 639 at r1](https://reviewable.io/reviews/batfish/batfish/1646#-LEqjZR15d2dVelo9bZj:-LEqjZR15d2dVelo9bZk:b-slbgkk) ([raw file](https://github.com/batfish/batfish/blob/fdce5998fe771e0fedc6c9e5efc764c282804eb3/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java#L639)):*
> ```Java
> 
>   public Interface(String name, Configuration owner) {
>     this(name, owner, null);
> ```

I would suggest passing `UNKNOWN` instead of `null`, it would also make the code more readable as meaning of `null` is not clear but `interfaceType`:`UNKNOWN` is easier to interpret

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java, line 642 at r1](https://reviewable.io/reviews/batfish/batfish/1646#-LEqkF7vAtfe0Tdet8aq:-LEqkF7vAtfe0Tdet8ar:b-2vror9) ([raw file](https://github.com/batfish/batfish/blob/fdce5998fe771e0fedc6c9e5efc764c282804eb3/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java#L642)):*
> ```Java
>   }
> 
>   public Interface(String name, Configuration owner, InterfaceType interfaceType) {
> ```

If we decide on passing `null` then please annotate with `@Nullable`

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java, line 661 at r1](https://reviewable.io/reviews/batfish/batfish/1646#-LEqkf5-Dn8WBOEZ2d81:-LEqkf5-Dn8WBOEZ2d82:bx8ipse) ([raw file](https://github.com/batfish/batfish/blob/fdce5998fe771e0fedc6c9e5efc764c282804eb3/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java#L661)):*
> ```Java
> 
>     // Set interface type after setting owner
>     _interfaceType = (interfaceType == null) ? computeInterfaceType() : interfaceType;
> ```

If we are decide on passing `null` then we can use `firstNonNull` here to assign `interfaceType`

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java, line 669 at r1](https://reviewable.io/reviews/batfish/batfish/1646#-LEql8BHBaxkKD-CLtHG:-LEql8BHBaxkKD-CLtHH:bd4w7oj) ([raw file](https://github.com/batfish/batfish/blob/fdce5998fe771e0fedc6c9e5efc764c282804eb3/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java#L669)):*
> ```Java
> 
>   private InterfaceType computeInterfaceType() {
>     return ((_key == null) || (_owner == null))
> ```

passing `UNKNOWN` will also get rid of one of the branches in this `if:else` statement 

---

*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/Interface.java, line 8 at r1](https://reviewable.io/reviews/batfish/batfish/1646#-LEqlgSw13C9wOvQM0Uv:-LEqlgSw13C9wOvQM0Uw:bn99d07) ([raw file](https://github.com/batfish/batfish/blob/fdce5998fe771e0fedc6c9e5efc764c282804eb3/projects/batfish/src/main/java/org/batfish/representation/palo_alto/Interface.java#L8)):*
> ```Java
> import org.batfish.datamodel.InterfaceAddress;
> 
> /** Datamodel component containing interface configuration */
> ```

Sorry to nitpick but I think this is not a `Datamodel` component, may be `Palo Alto Datamodel` ?

---

*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java, line 28 at r1](https://reviewable.io/reviews/batfish/batfish/1646#-LEqnOXB3p0wMrSSioxy:-LEqnOXB3p0wMrSSioxz:bgbbpgl) ([raw file](https://github.com/batfish/batfish/blob/fdce5998fe771e0fedc6c9e5efc764c282804eb3/projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java#L28)):*
> ```Java
>   private String _hostname;
> 
>   private final Map<String, Interface> _interfaces;
> ```

I may be wrong, but should not we use the `SortedMap` or `NavigableMap` interface with a `TreeMap` implementation for consistency ?

---

*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java, line 115 at r1](https://reviewable.io/reviews/batfish/batfish/1646#-LEqo4HwDHzyFGoNNgen:-LEqo4HwDHzyFGoNNgeo:bzcy5yb) ([raw file](https://github.com/batfish/batfish/blob/fdce5998fe771e0fedc6c9e5efc764c282804eb3/projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java#L115)):*
> ```Java
>     }
>     if (iface.getAddress() != null) {
>       newIface.setAddress(iface.getAddress());
> ```

I think the non `null` check is redundant here as the setter will be a no-op for a `null ` value

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1646)*

**Comment by sfraint** [comment]
Review status: all files reviewed, 7 unresolved discussions (waiting on @sfraint, @haverma, and @anothermattbrown)

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java, line 639 at r1](https://reviewable.io/reviews/batfish/batfish/1646#-LEqjZR15d2dVelo9bZj:-LEtyl3-4VgjSUp43ZHB:b-48vilg) ([raw file](https://github.com/batfish/batfish/blob/fdce5998fe771e0fedc6c9e5efc764c282804eb3/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java#L639)):*
<details><summary><i>Previously, haverma (Harsh Verma) wrote…</i></summary><blockquote>

I would suggest passing `UNKNOWN` instead of `null`, it would also make the code more readable as meaning of `null` is not clear but `interfaceType`:`UNKNOWN` is easier to interpret
</blockquote></details>

Good call, done.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java, line 642 at r1](https://reviewable.io/reviews/batfish/batfish/1646#-LEqkF7vAtfe0Tdet8aq:-LEtymT4CCNKacuoytd_:bb6zoc3) ([raw file](https://github.com/batfish/batfish/blob/fdce5998fe771e0fedc6c9e5efc764c282804eb3/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java#L642)):*
<details><summary><i>Previously, haverma (Harsh Verma) wrote…</i></summary><blockquote>

If we decide on passing `null` then please annotate with `@Nullable`
</blockquote></details>

N/A.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java, line 661 at r1](https://reviewable.io/reviews/batfish/batfish/1646#-LEqkf5-Dn8WBOEZ2d81:-LEtzxXF-2Kf5hwDmXGf:bb6zoc3) ([raw file](https://github.com/batfish/batfish/blob/fdce5998fe771e0fedc6c9e5efc764c282804eb3/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java#L661)):*
<details><summary><i>Previously, haverma (Harsh Verma) wrote…</i></summary><blockquote>

If we are decide on passing `null` then we can use `firstNonNull` here to assign `interfaceType`
</blockquote></details>

N/A.

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_network.g4, line 37 at r1](https://reviewable.io/reviews/batfish/batfish/1646#-LEqfNuV8dhFmTLlxVTi:-LEtzQ807__ADONJHgRt:b-ux4w9e) ([raw file](https://github.com/batfish/batfish/blob/fdce5998fe771e0fedc6c9e5efc764c282804eb3/projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAlto_network.g4#L37)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

You almost certainly want to use a lexer mode here. That mode should emit a single token consisting of everything until the end of the line. You should enter the mode after the `COMMENT` token is emitted.

Ignore if the only valid multiword comment is a double-quoted string. In this case, make sure to unquote the text before you store it.
</blockquote></details>

The multiword comments must be in quotes (though, it looks like single quotes also work).

---

*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/Interface.java, line 8 at r1](https://reviewable.io/reviews/batfish/batfish/1646#-LEqlgSw13C9wOvQM0Uv:-LEu9uPl4o51w3aHeDZz:bm9l57c) ([raw file](https://github.com/batfish/batfish/blob/fdce5998fe771e0fedc6c9e5efc764c282804eb3/projects/batfish/src/main/java/org/batfish/representation/palo_alto/Interface.java#L8)):*
<details><summary><i>Previously, haverma (Harsh Verma) wrote…</i></summary><blockquote>

Sorry to nitpick but I think this is not a `Datamodel` component, may be `Palo Alto Datamodel` ?
</blockquote></details>

Meant vendor model, not vendor independent model.  Clarified.

---

*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java, line 28 at r1](https://reviewable.io/reviews/batfish/batfish/1646#-LEqnOXB3p0wMrSSioxy:-LEuDXPj6qEtllbxsavd:b-n062c2) ([raw file](https://github.com/batfish/batfish/blob/fdce5998fe771e0fedc6c9e5efc764c282804eb3/projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java#L28)):*
<details><summary><i>Previously, haverma (Harsh Verma) wrote…</i></summary><blockquote>

I may be wrong, but should not we use the `SortedMap` or `NavigableMap` interface with a `TreeMap` implementation for consistency ?
</blockquote></details>

Seems reasonable, done.

---

*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java, line 115 at r1](https://reviewable.io/reviews/batfish/batfish/1646#-LEqo4HwDHzyFGoNNgen:-LEuDWtK1DJjBHIcD2wk:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/fdce5998fe771e0fedc6c9e5efc764c282804eb3/projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java#L115)):*
<details><summary><i>Previously, haverma (Harsh Verma) wrote…</i></summary><blockquote>

I think the non `null` check is redundant here as the setter will be a no-op for a `null ` value
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1646)*

**Comment by arifogel** [comment]
Reviewed 7 of 7 files at r2.
Review status: all files reviewed, 6 unresolved discussions (waiting on @haverma and @anothermattbrown)

---

*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java, line 28 at r1](https://reviewable.io/reviews/batfish/batfish/1646#-LEqnOXB3p0wMrSSioxy:-LEuU8ZGCvYlAIMFgWWy:b-cdpxqt) ([raw file](https://github.com/batfish/batfish/blob/fdce5998fe771e0fedc6c9e5efc764c282804eb3/projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java#L28)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

Seems reasonable, done.
</blockquote></details>

This only matters in the vendor-independent model.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1646)*

**Comment by haverma** [comment]
:lgtm:

---

Review status: all files reviewed, 1 unresolved discussion (waiting on @sfraint and @anothermattbrown)

---

*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java, line 28 at r1](https://reviewable.io/reviews/batfish/batfish/1646#-LEqnOXB3p0wMrSSioxy:-LEuVQAj6cfQ9U5t_pqb:bq86zog) ([raw file](https://github.com/batfish/batfish/blob/fdce5998fe771e0fedc6c9e5efc764c282804eb3/projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java#L28)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

This only matters in the vendor-independent model.
</blockquote></details>

Right, order should not be important here. `HashMap<>` will also be sufficient

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1646#-:-LEuVinZ0rQGH7AE7tYJ:bnfp4nl)*

**Comment by arifogel** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @sfraint and @anothermattbrown)

---

*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java, line 28 at r1](https://reviewable.io/reviews/batfish/batfish/1646#-LEqnOXB3p0wMrSSioxy:-LEu_-Dd70F_xDnZSktj:b-urww6j) ([raw file](https://github.com/batfish/batfish/blob/fdce5998fe771e0fedc6c9e5efc764c282804eb3/projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java#L28)):*
<details><summary><i>Previously, haverma (Harsh Verma) wrote…</i></summary><blockquote>

Right, order should not be important here. `HashMap<>` will also be sufficient
</blockquote></details>

To be clear, `HashMap` should never be the declared type, but would be an acceptable actual type. `Map` would be fine.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1646)*

**Comment by haverma** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @sfraint and @anothermattbrown)

---

*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java, line 28 at r1](https://reviewable.io/reviews/batfish/batfish/1646#-LEqnOXB3p0wMrSSioxy:-LEu_Skk-wgg0KVAttAs:bal87ij) ([raw file](https://github.com/batfish/batfish/blob/fdce5998fe771e0fedc6c9e5efc764c282804eb3/projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java#L28)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

To be clear, `HashMap` should never be the declared type, but would be an acceptable actual type. `Map` would be fine.
</blockquote></details>

Correct, I was talking about the implementation type 

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1646)*

**Comment by anothermattbrown** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed, 2 unresolved discussions (waiting on @sfraint)

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java, line 661 at r1](https://reviewable.io/reviews/batfish/batfish/1646#-LEq_hzO4YsU_V1syPbs:-LEq_hzO4YsU_V1syPbt:bsinxbf) ([raw file](https://github.com/batfish/batfish/blob/fdce5998fe771e0fedc6c9e5efc764c282804eb3/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java#L661)):*
> ```Java
> 
>     // Set interface type after setting owner
>     _interfaceType = (interfaceType == null) ? computeInterfaceType() : interfaceType;
> ```

Can we move this to the new two-argument constructor, and make `interfaceType` be `@Nonnull`? 
Might make sense to inline `computeInterfaceType` or make it static.

---

*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/Interface.java, line 9 at r1](https://reviewable.io/reviews/batfish/batfish/1646#-LEqaDgqB122tFBPk5bx:-LEqaDgqB122tFBPk5by:b-1ws1yz) ([raw file](https://github.com/batfish/batfish/blob/fdce5998fe771e0fedc6c9e5efc764c282804eb3/projects/batfish/src/main/java/org/batfish/representation/palo_alto/Interface.java#L9)):*
> ```Java
> 
> /** Datamodel component containing interface configuration */
> public class Interface extends ComparableStructure<String> {
> ```

can this be `final`?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1646)*

**Comment by anothermattbrown** [comment]
:lgtm:

---

Review status: all files reviewed, 2 unresolved discussions (waiting on @sfraint)

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1646#-:-LEul8Os0rII9wHmd4i3:bnfp4nl)*

**Comment by arifogel** [comment]
Reviewed 6 of 6 files at r3.
Review status: all files reviewed, 2 unresolved discussions (waiting on @sfraint)

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1646)*

**Comment by arifogel** [comment]
:lgtm:

---

Review status: all files reviewed, 2 unresolved discussions (waiting on @sfraint)

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1646#-:-LEuthGPCqe1w4-xsUBg:bnfp4nl)*

**Comment by sfraint** [comment]
Review status: all files reviewed, 2 unresolved discussions (waiting on @arifogel and @anothermattbrown)

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java, line 661 at r1](https://reviewable.io/reviews/batfish/batfish/1646#-LEq_hzO4YsU_V1syPbs:-LEuuOoQAiar_EXx3Sg8:b-h1azym) ([raw file](https://github.com/batfish/batfish/blob/fdce5998fe771e0fedc6c9e5efc764c282804eb3/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java#L661)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

Can we move this to the new two-argument constructor, and make `interfaceType` be `@Nonnull`? 
Might make sense to inline `computeInterfaceType` or make it static.
</blockquote></details>

Done, done, and done.

---

*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/Interface.java, line 9 at r1](https://reviewable.io/reviews/batfish/batfish/1646#-LEqaDgqB122tFBPk5bx:-LEurGUS09Mwjb26DgOw:b-9f087b) ([raw file](https://github.com/batfish/batfish/blob/fdce5998fe771e0fedc6c9e5efc764c282804eb3/projects/batfish/src/main/java/org/batfish/representation/palo_alto/Interface.java#L9)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

can this be `final`?
</blockquote></details>

Yep, done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1646)*

**Comment by arifogel** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed, 2 unresolved discussions (waiting on @arifogel and @anothermattbrown)

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1646)*

**Comment by anothermattbrown** [comment]
Reviewed 1 of 7 files at r2, 5 of 6 files at r3, 1 of 1 files at r4.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1646)*

**Pull request merged**
