### PR TITLE
BDDFactory: make getPair cache insensitive to order of variables

### PR DESCRIPTION
**Pull request by anothermattbrown**
getPair caches the BDDPairings it creates to improve cache performance of BDD::replace. Previously, this cache was sensitive to the order of the oldvars/newvars arrays, which is sensitive to the order in which BDDPairingFactory objects are composed.

We now use an unordered set of BDDVarPair objects as the cache key. This allows us to simplify BDDPairingFactory and Transform.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8304)* status: all files reviewed, 5 unresolved discussions (waiting on @anothermattbrown)

___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPairingFactory.java` line 27 at r1](https://reviewable.io/reviews/batfish/batfish/8304#-N1oxRxwDs6Cmxy5JACZ:-N1oxRxx9u31ZdxFVENi:b-1glq0) ([raw file](https://github.com/batfish/batfish/blob/e0d146170d28e8cee474da54c0eea27fc384f5b9/projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPairingFactory.java#L27)):*
> ```Java
>   public BDDPairingFactory(BDDFactory bddFactory, Set<BDDVarPair> varPairs) {
>     checkArgument(!varPairs.isEmpty(), "BDDPairingFactory must have at least one variable pair.");
>     assert varPairsInvariants(varPairs);
> ```

why doesn't this run all the time?



_Code quote:_
```Java
assert varPairsInvariants(varPairs);
```
___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPairingFactory.java` line 57 at r1](https://reviewable.io/reviews/batfish/batfish/8304#-N1oxo_7CsRYtx41SQgB:-N1oxo_7CsRYtx41SQgC:bpk1key) ([raw file](https://github.com/batfish/batfish/blob/e0d146170d28e8cee474da54c0eea27fc384f5b9/projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPairingFactory.java#L57)):*
> ```Java
>         _bddFactory == other._bddFactory,
>         "Cannot compose with a BDDPairingFactory for a different BDDFactory");
>     assert Sets.intersection(_varPairs, other._varPairs).isEmpty()
> ```

same q here.



_Code quote:_
```Java
assert 
```
___
*[`projects/bdd/src/main/java/net/sf/javabdd/BDDVarPair.java` line 5 at r1](https://reviewable.io/reviews/batfish/batfish/8304#-N1oveImBDc7IZX_oQ56:-N1oveInCjXLO3Y5gm65:b-11j9ck) ([raw file](https://github.com/batfish/batfish/blob/e0d146170d28e8cee474da54c0eea27fc384f5b9/projects/bdd/src/main/java/net/sf/javabdd/BDDVarPair.java#L5)):*
> ```Java
> import com.google.common.base.Objects;
> 
> public final class BDDVarPair {
> ```

please document
___
*[`projects/bdd/src/main/java/net/sf/javabdd/BDDVarPair.java` line 9 at r1](https://reviewable.io/reviews/batfish/batfish/8304#-N1ovgLy3_uwEdnVQGew:-N1ovgLz4xJV4hysAKHR:bxszpzf) ([raw file](https://github.com/batfish/batfish/blob/e0d146170d28e8cee474da54c0eea27fc384f5b9/projects/bdd/src/main/java/net/sf/javabdd/BDDVarPair.java#L9)):*
> ```Java
>   private final int _newVar;
> 
>   public BDDVarPair(BDD oldVar, BDD newVar) {
> ```

are there invariants on these (e.g., they should have been created via `.ithVar()`)? Or is it okay to use an arbitrary BDD.
___
*[`projects/bdd/src/main/java/net/sf/javabdd/BDDVarPair.java` line 13 at r1](https://reviewable.io/reviews/batfish/batfish/8304#-N1ovmvf8E8s1pvubrat:-N1ovmvf8E8s1pvubrau:bj09ecz) ([raw file](https://github.com/batfish/batfish/blob/e0d146170d28e8cee474da54c0eea27fc384f5b9/projects/bdd/src/main/java/net/sf/javabdd/BDDVarPair.java#L13)):*
> ```Java
>   }
> 
>   public BDDVarPair(int oldVar, int newVar) {
> ```

Do we want to prevent ==? (Or would it be ignored in a pairing?) If so comment that.

**Review by anothermattbrown — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8304)* status: all files reviewed, 5 unresolved discussions (waiting on @anothermattbrown and @dhalperi)

___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPairingFactory.java` line 27 at r1](https://reviewable.io/reviews/batfish/batfish/8304#-N1oxRxwDs6Cmxy5JACZ:-N1ozouE7nxwnMrZQ5tq:bx8m0d2) ([raw file](https://github.com/batfish/batfish/blob/e0d146170d28e8cee474da54c0eea27fc384f5b9/projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPairingFactory.java#L27)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

why doesn't this run all the time?
</blockquote></details>

just because it's relatively expensive (i.e. not constant time). do you prefer to always check it (and/or the one below)? I'm fine with that if you think it's better

**Review by anothermattbrown — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8304)* status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @anothermattbrown and @dhalperi)

___
*[`projects/bdd/src/main/java/net/sf/javabdd/BDDVarPair.java` line 5 at r1](https://reviewable.io/reviews/batfish/batfish/8304#-N1oveImBDc7IZX_oQ56:-N1p1MEV2z_e0rtUhftx:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/e0d146170d28e8cee474da54c0eea27fc384f5b9/projects/bdd/src/main/java/net/sf/javabdd/BDDVarPair.java#L5)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

please document
</blockquote></details>

done
___
*[`projects/bdd/src/main/java/net/sf/javabdd/BDDVarPair.java` line 9 at r1](https://reviewable.io/reviews/batfish/batfish/8304#-N1ovgLy3_uwEdnVQGew:-N1p1Mpl6Q4XPLgfi6cB:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/e0d146170d28e8cee474da54c0eea27fc384f5b9/projects/bdd/src/main/java/net/sf/javabdd/BDDVarPair.java#L9)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

are there invariants on these (e.g., they should have been created via `.ithVar()`)? Or is it okay to use an arbitrary BDD.
</blockquote></details>

done
___
*[`projects/bdd/src/main/java/net/sf/javabdd/BDDVarPair.java` line 13 at r1](https://reviewable.io/reviews/batfish/batfish/8304#-N1ovmvf8E8s1pvubrat:-N1p2-HfBBSUZZYpM6M8:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/e0d146170d28e8cee474da54c0eea27fc384f5b9/projects/bdd/src/main/java/net/sf/javabdd/BDDVarPair.java#L13)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Do we want to prevent ==? (Or would it be ignored in a pairing?) If so comment that.
</blockquote></details>

done

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8304)* status: all files reviewed, 3 unresolved discussions (waiting on @anothermattbrown)

___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPairingFactory.java` line 27 at r1](https://reviewable.io/reviews/batfish/batfish/8304#-N1oxRxwDs6Cmxy5JACZ:-N1p6ien0ktisfTsqNt6:bqb94nn) ([raw file](https://github.com/batfish/batfish/blob/e0d146170d28e8cee474da54c0eea27fc384f5b9/projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPairingFactory.java#L27)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

just because it's relatively expensive (i.e. not constant time). do you prefer to always check it (and/or the one below)? I'm fine with that if you think it's better 
</blockquote></details>

unless the code is particularly hot, I'd say do it. You know better than I do tho.
___
*[`projects/bdd/src/main/java/net/sf/javabdd/BDDVarPair.java` line 57 at r2](https://reviewable.io/reviews/batfish/batfish/8304#-N1p53tNCekD3V5F86si:-N1p53tOD5VuQudSIAXu:bbod2hu) ([raw file](https://github.com/batfish/batfish/blob/730763efc45174427b7ed9c60206e759bdb871ed/projects/bdd/src/main/java/net/sf/javabdd/BDDVarPair.java#L57)):*
> ```Java
> 
>   private static int bddVarId(BDD bdd) {
>     checkArgument(bdd.high().isOne() && bdd.low().isZero(), "bdd is not a single variable");
> ```

lol/sigh: creating garbage.

Might be best to just document and let it usually-work if users happen to pass BDDs with top bit set.



_Code quote:_
```Java
bdd.high().isOne()
```

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8304)* status: all files reviewed, 1 unresolved discussion (waiting on @anothermattbrown)

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8304)* status: all files reviewed, 1 unresolved discussion (waiting on @anothermattbrown)

___
*[`projects/bdd/src/main/java/net/sf/javabdd/BDDVarPair.java` line 57 at r2](https://reviewable.io/reviews/batfish/batfish/8304#-N1p53tNCekD3V5F86si:-N1pCbyiDQ3b0m8-9vNJ:bkdql5q) ([raw file](https://github.com/batfish/batfish/blob/730763efc45174427b7ed9c60206e759bdb871ed/projects/bdd/src/main/java/net/sf/javabdd/BDDVarPair.java#L57)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

lol/sigh: creating garbage.

Might be best to just document and let it usually-work if users happen to pass BDDs with top bit set.
</blockquote></details>

or to be fair this garbage is going to be 0/1 so never freed anyway, and if it crashes then the entire computation is effed. so maybe no need to care?

**Review by anothermattbrown — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8304)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[`projects/bdd/src/main/java/net/sf/javabdd/BDDVarPair.java` line 57 at r2](https://reviewable.io/reviews/batfish/batfish/8304#-N1p53tNCekD3V5F86si:-N1pCMlR7LMWEJTyrzIm:bl2uvkn) ([raw file](https://github.com/batfish/batfish/blob/730763efc45174427b7ed9c60206e759bdb871ed/projects/bdd/src/main/java/net/sf/javabdd/BDDVarPair.java#L57)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

or to be fair this garbage is going to be 0/1 so never freed anyway, and if it crashes then the entire computation is effed. so maybe no need to care?
</blockquote></details>

i don't think it matters. just a couple short-lived java objects, no worse than the sets we're creating to check the other invariants

**Pull request merged**
