### PR TITLE
Support junos application sets

### PR DESCRIPTION
**Pull request by erikljungman**
junos application-sets now supported

### CODE REVIEW

**Comment by arifogel** [comment]
Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/CiscoLexer.tokens, line 0 at r1](https://reviewable.io/reviews/batfish/batfish/1463#-LD8COaSBD3jmmHGRZTo:-LD8COaSBD3jmmHGRZTp:b-ze0b7k) ([raw file](https://github.com/batfish/batfish/blob/b1c11b00e068e4a6aec1a6f8f09895bb5d09a641/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/CiscoLexer.tokens#L0)):*
Delete this file.

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.tokens, line 0 at r1](https://reviewable.io/reviews/batfish/batfish/1463#-LD8Cc740prgLobdprD1:-LD8Cc740prgLobdprD2:b-ze0b7k) ([raw file](https://github.com/batfish/batfish/blob/b1c11b00e068e4a6aec1a6f8f09895bb5d09a641/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.tokens#L0)):*
Delete this file.

---

*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 1042 at r1](https://reviewable.io/reviews/batfish/batfish/1463#-LD8ClR4B5ggaQnrZpho:-LD8ClR4B5ggaQnrZphp:bpfoa1f) ([raw file](https://github.com/batfish/batfish/blob/b1c11b00e068e4a6aec1a6f8f09895bb5d09a641/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L1042)):*
> ```Java
>       return JunosApplicationSet.JUNOS_SUN_RPC_YPSERV;
>     } else {
>       throw new BatfishException(
> ```

We have helper function for this. Do:
`throw convError(JunosApplicationSet.class, ctx);`

---

*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 1664 at r1](https://reviewable.io/reviews/batfish/batfish/1463#-LD8OA-J378WEMi-HCOt:-LD8OA-J378WEMi-HCOu:brmxgek) ([raw file](https://github.com/batfish/batfish/blob/b1c11b00e068e4a6aec1a6f8f09895bb5d09a641/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L1664)):*
> ```Java
>       _configuration
>           .getApplicationSets()
>           .putIfAbsent(name, junosApplicationSet.getApplicationSet());
> ```

Don't register predefined structures as discussed offline.

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/ApplicationOrApplicationSetReference.java, line 12 at r1](https://reviewable.io/reviews/batfish/batfish/1463#-LD8O5YPErUN2qsQLGkJ:-LD8O5YPErUN2qsQLGkK:bl0tx43) ([raw file](https://github.com/batfish/batfish/blob/b1c11b00e068e4a6aec1a6f8f09895bb5d09a641/projects/batfish/src/main/java/org/batfish/representation/juniper/ApplicationOrApplicationSetReference.java#L12)):*
> ```Java
>   }
> 
>   public ApplicationOrApplicationSetReference(Application application) {
> ```

Remove as discussed offline.

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/ApplicationSetMemberReference.java, line 12 at r1](https://reviewable.io/reviews/batfish/batfish/1463#-LD8EljGCkeBuwfJ2Pdh:-LD8EljGCkeBuwfJ2Pdi:brgr36o) ([raw file](https://github.com/batfish/batfish/blob/b1c11b00e068e4a6aec1a6f8f09895bb5d09a641/projects/batfish/src/main/java/org/batfish/representation/juniper/ApplicationSetMemberReference.java#L12)):*
> ```Java
>   protected final String _name;
> 
>   protected final Application _application;
> ```

Remove `_application` as discussed offline.

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromApplicationSet.java, line 10 at r1](https://reviewable.io/reviews/batfish/batfish/1463#-LD8NxSA8WaLWVVC0v9c:-LD8NxSA8WaLWVVC0v9d:b-7w8vsp) ([raw file](https://github.com/batfish/batfish/blob/b1c11b00e068e4a6aec1a6f8f09895bb5d09a641/projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromApplicationSet.java#L10)):*
> ```Java
> import org.batfish.datamodel.LineAction;
> 
> public class FwFromApplicationSet implements Serializable {
> ```

Just have `FwFromApplicationOrApplicationSet` as discussed offline.

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/FwTerm.java, line 15 at r1](https://reviewable.io/reviews/batfish/batfish/1463#-LD8OhSx1jnltj3gyQnA:-LD8OhSx1jnltj3gyQnB:bx7qt1l) ([raw file](https://github.com/batfish/batfish/blob/b1c11b00e068e4a6aec1a6f8f09895bb5d09a641/projects/batfish/src/main/java/org/batfish/representation/juniper/FwTerm.java#L15)):*
> ```Java
> 
>   private final List<FwFromApplicationSet> _fromApplicationSets;
> ```

This will need restructuring after changes discussed offline.

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/JunosApplicationSet.java, line 326 at r1](https://reviewable.io/reviews/batfish/batfish/1463#-LD8OqfAAoUZVTYXLsBA:-LD8OqfAAoUZVTYXLsBB:boxxgf0) ([raw file](https://github.com/batfish/batfish/blob/b1c11b00e068e4a6aec1a6f8f09895bb5d09a641/projects/batfish/src/main/java/org/batfish/representation/juniper/JunosApplicationSet.java#L326)):*
> ```Java
> 
>     for (JunosApplication app : applications) {
>       applicationSetMemberBuilder.add(new ApplicationOrApplicationSetReference(app));
> ```

Don't inline here as discussed offline.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1463)*

**Comment by erikljungman** [comment]
Review status: 8 of 17 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 1042 at r1](https://reviewable.io/reviews/batfish/batfish/1463#-LD8ClR4B5ggaQnrZpho:-LD9ONG8EIdBDzgkDCSH:bgvx3bh) ([raw file](https://github.com/batfish/batfish/blob/b1c11b00e068e4a6aec1a6f8f09895bb5d09a641/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L1042)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

We have helper function for this. Do:
`throw convError(JunosApplicationSet.class, ctx);`
</blockquote></details>

convError is a non-static member function and so can't be accessed from the static member function toJunosApplicationSet - do you think we should make toJunosApplicationSet a non-static member function?

---

*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 1664 at r1](https://reviewable.io/reviews/batfish/batfish/1463#-LD8OA-J378WEMi-HCOt:-LD9Oq0k4iQYCaxRXjVz:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/b1c11b00e068e4a6aec1a6f8f09895bb5d09a641/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L1664)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Don't register predefined structures as discussed offline.
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/FwTerm.java, line 15 at r1](https://reviewable.io/reviews/batfish/batfish/1463#-LD8OhSx1jnltj3gyQnA:-LD9P7UP15aSYX7dgRed:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/b1c11b00e068e4a6aec1a6f8f09895bb5d09a641/projects/batfish/src/main/java/org/batfish/representation/juniper/FwTerm.java#L15)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

This will need restructuring after changes discussed offline.
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/JunosApplicationSet.java, line 326 at r1](https://reviewable.io/reviews/batfish/batfish/1463#-LD8OqfAAoUZVTYXLsBA:-LD9PDBG8dlQPEp03QQF:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/b1c11b00e068e4a6aec1a6f8f09895bb5d09a641/projects/batfish/src/main/java/org/batfish/representation/juniper/JunosApplicationSet.java#L326)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Don't inline here as discussed offline.
</blockquote></details>

Done.

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/CiscoLexer.tokens, line  at r1](https://reviewable.io/reviews/batfish/batfish/1463#-LD8COaSBD3jmmHGRZTo:-LD9PEmX4VMRbgdqN7P8:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/b1c11b00e068e4a6aec1a6f8f09895bb5d09a641/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/CiscoLexer.tokens#L)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Delete this file.
</blockquote></details>

Done.

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.tokens, line  at r1](https://reviewable.io/reviews/batfish/batfish/1463#-LD8Cc740prgLobdprD1:-LD9PFRRCWFHPvFukxeH:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/b1c11b00e068e4a6aec1a6f8f09895bb5d09a641/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.tokens#L)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Delete this file.
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/ApplicationOrApplicationSetReference.java, line 12 at r1](https://reviewable.io/reviews/batfish/batfish/1463#-LD8O5YPErUN2qsQLGkJ:-LD9PGw83HEMgVvbFHkb:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/b1c11b00e068e4a6aec1a6f8f09895bb5d09a641/projects/batfish/src/main/java/org/batfish/representation/juniper/ApplicationOrApplicationSetReference.java#L12)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Remove as discussed offline.
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/ApplicationSetMemberReference.java, line 12 at r1](https://reviewable.io/reviews/batfish/batfish/1463#-LD8EljGCkeBuwfJ2Pdh:-LD9PHzJCF2qSHtzAPBr:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/b1c11b00e068e4a6aec1a6f8f09895bb5d09a641/projects/batfish/src/main/java/org/batfish/representation/juniper/ApplicationSetMemberReference.java#L12)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Remove `_application` as discussed offline.
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromApplicationSet.java, line 10 at r1](https://reviewable.io/reviews/batfish/batfish/1463#-LD8NxSA8WaLWVVC0v9c:-LD9PJYg3zjCAE33E4cA:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/b1c11b00e068e4a6aec1a6f8f09895bb5d09a641/projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromApplicationSet.java#L10)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Just have `FwFromApplicationOrApplicationSet` as discussed offline.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1463)*

**Comment by arifogel** [comment]
Looking much better. Lots of refactoring suggestions, but functionally looks good.

---

Reviewed 15 of 16 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 1042 at r1](https://reviewable.io/reviews/batfish/batfish/1463#-LD8ClR4B5ggaQnrZpho:-LD9ROJO3ZPoCyhmjxno:b58ad48) ([raw file](https://github.com/batfish/batfish/blob/b1c11b00e068e4a6aec1a6f8f09895bb5d09a641/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L1042)):*
<details><summary><i>Previously, erikljungman wrote…</i></summary><blockquote>

convError is a non-static member function and so can't be accessed from the static member function toJunosApplicationSet - do you think we should make toJunosApplicationSet a non-static member function?
</blockquote></details>

Yup, for exactly this reason. Also we want to control logging centrally.

---

*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 1643 at r2](https://reviewable.io/reviews/batfish/batfish/1463#-LD9Rpsh5i8y2aG01ivt:-LD9RpsiAifq7Sx3chp5:b-ctmq7o) ([raw file](https://github.com/batfish/batfish/blob/72806155fcf5cf5f17fa9a91cf6f5624b86355fe/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L1643)):*
> ```Java
>           ImmutableList.<ApplicationSetMemberReference>builder()
>               .addAll(_currentApplicationSet.getMembers())
>               .add(new ApplicationOrApplicationSetReference(name))
> ```

Shouldn't this just be `ApplicationReference`?

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromJunosApplication.java, line 16 at r2](https://reviewable.io/reviews/batfish/batfish/1463#-LD9SpoxBXUeqC3XN-wQ:-LD9SpoxBXUeqC3XN-wR:biyegat) ([raw file](https://github.com/batfish/batfish/blob/72806155fcf5cf5f17fa9a91cf6f5624b86355fe/projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromJunosApplication.java#L16)):*
> ```Java
>   private final String _junosApplicationName;
> 
>   public FwFromJunosApplication(String junosApplicationName) {
> ```

Rather than store the name, just store the `JunosApplication`. Then you don't need to do `valueOf` later.
Also applies to `FwFromJunosApplicationSet`, and JunosXReference classes.

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java, line 1449 at r2](https://reviewable.io/reviews/batfish/batfish/1463#-LD9TCkF9uAG95TCJ-81:-LD9TCkF9uAG95TCJ-82:bobk468) ([raw file](https://github.com/batfish/batfish/blob/72806155fcf5cf5f17fa9a91cf6f5624b86355fe/projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java#L1449)):*
> ```Java
>         from.applyTo(lines, _w);
>       }
>       for (FwFromApplicationOrApplicationSet fromApplicationOrApplicationSet :
> ```

All three of these now are used exactly the same way. Why not instead have them inherit a common interface and just store a single list?

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromApplicationOrApplicationSet.java, line 10 at r2](https://reviewable.io/reviews/batfish/batfish/1463#-LD9Sk7X2fNlL9k7XWnJ:-LD9Sk7X2fNlL9k7XWnK:bxdedz2) ([raw file](https://github.com/batfish/batfish/blob/72806155fcf5cf5f17fa9a91cf6f5624b86355fe/projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromApplicationOrApplicationSet.java#L10)):*
> ```Java
> import org.batfish.datamodel.LineAction;
> 
> public class FwFromApplicationOrApplicationSet implements Serializable {
> ```

Why no longer final?

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromApplicationOrApplicationSet.java, line 14 at r2](https://reviewable.io/reviews/batfish/batfish/1463#-LD9SWuj332Q-OPfSvbz:-LD9SWuj332Q-OPfSvc-:bat00k3) ([raw file](https://github.com/batfish/batfish/blob/72806155fcf5cf5f17fa9a91cf6f5624b86355fe/projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromApplicationOrApplicationSet.java#L14)):*
> ```Java
>   private static final long serialVersionUID = 1L;
> 
>   private final String _applicationName;
> ```

Could you rename this to `_applicationOrApplicationSetName` for clarity?

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromApplicationOrApplicationSet.java, line 31 at r2](https://reviewable.io/reviews/batfish/batfish/1463#-LD9SIHV9xTD2GDPBE-6:-LD9SIHV9xTD2GDPBE-7:bpj1k4i) ([raw file](https://github.com/batfish/batfish/blob/72806155fcf5cf5f17fa9a91cf6f5624b86355fe/projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromApplicationOrApplicationSet.java#L31)):*
> ```Java
>     }
>     if (application == null) {
>       w.redFlag("Reference to undefined application: \"" + _applicationName + "\"");
> ```

Remove the red-flag warning, which is inaccurate anyhow; this should be handled by our reference tracking code. We only need one branch for the `if` now.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1463#-:-LD9TfBFAIH55oxbChJz:b-an37rb)*

**Comment by erikljungman** [comment]
Review status: 5 of 22 files reviewed at latest revision, 7 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 1042 at r1](https://reviewable.io/reviews/batfish/batfish/1463#-LD8ClR4B5ggaQnrZpho:-LDDNco498DBtic3lNjY:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/b1c11b00e068e4a6aec1a6f8f09895bb5d09a641/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L1042)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Yup, for exactly this reason. Also we want to control logging centrally.
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 1643 at r2](https://reviewable.io/reviews/batfish/batfish/1463#-LD9Rpsh5i8y2aG01ivt:-LDDNeiF1hw9xbC24Ztr:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/72806155fcf5cf5f17fa9a91cf6f5624b86355fe/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L1643)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Shouldn't this just be `ApplicationReference`?
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromJunosApplication.java, line 16 at r2](https://reviewable.io/reviews/batfish/batfish/1463#-LD9SpoxBXUeqC3XN-wQ:-LDDO6230SSPC75TtWrV:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/72806155fcf5cf5f17fa9a91cf6f5624b86355fe/projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromJunosApplication.java#L16)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Rather than store the name, just store the `JunosApplication`. Then you don't need to do `valueOf` later.
Also applies to `FwFromJunosApplicationSet`, and JunosXReference classes.
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java, line 1449 at r2](https://reviewable.io/reviews/batfish/batfish/1463#-LD9TCkF9uAG95TCJ-81:-LDDO9g_CyzRRM7C0RWn:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/72806155fcf5cf5f17fa9a91cf6f5624b86355fe/projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java#L1449)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

All three of these now are used exactly the same way. Why not instead have them inherit a common interface and just store a single list?
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromApplicationOrApplicationSet.java, line 10 at r2](https://reviewable.io/reviews/batfish/batfish/1463#-LD9Sk7X2fNlL9k7XWnJ:-LDDNkuK1HSYCDir3Jyd:b-2unb1h) ([raw file](https://github.com/batfish/batfish/blob/72806155fcf5cf5f17fa9a91cf6f5624b86355fe/projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromApplicationOrApplicationSet.java#L10)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Why no longer final?
</blockquote></details>

it looks like most of the other FwFrom.* classes are not final - is there a reason for those one's not being final?

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromApplicationOrApplicationSet.java, line 14 at r2](https://reviewable.io/reviews/batfish/batfish/1463#-LD9SWuj332Q-OPfSvbz:-LDDNyjCD6Zeq5-oFTxf:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/72806155fcf5cf5f17fa9a91cf6f5624b86355fe/projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromApplicationOrApplicationSet.java#L14)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Could you rename this to `_applicationOrApplicationSetName` for clarity?
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromApplicationOrApplicationSet.java, line 31 at r2](https://reviewable.io/reviews/batfish/batfish/1463#-LD9SIHV9xTD2GDPBE-6:-LDDO-sz0JqIrB6uXKLn:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/72806155fcf5cf5f17fa9a91cf6f5624b86355fe/projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromApplicationOrApplicationSet.java#L31)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Remove the red-flag warning, which is inaccurate anyhow; this should be handled by our reference tracking code. We only need one branch for the `if` now.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1463)*

**Comment by arifogel** [comment]
Reviewed 3 of 5 files at r3, 14 of 15 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromApplicationOrApplicationSet.java, line 10 at r2](https://reviewable.io/reviews/batfish/batfish/1463#-LD9Sk7X2fNlL9k7XWnJ:-LDDRJgx065aa90vCM1Z:b5cb0bl) ([raw file](https://github.com/batfish/batfish/blob/72806155fcf5cf5f17fa9a91cf6f5624b86355fe/projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromApplicationOrApplicationSet.java#L10)):*
<details><summary><i>Previously, erikljungman wrote…</i></summary><blockquote>

it looks like most of the other FwFrom.* classes are not final - is there a reason for those one's not being final?
</blockquote></details>

no, just laziness. Pretty much everything should be declared final until there is a need otherwise. but that is out of scope for this PR; just don't make it worse here (i see you've fixed it already).

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromApplicationOrApplicationSet.java, line 31 at r2](https://reviewable.io/reviews/batfish/batfish/1463#-LD9SIHV9xTD2GDPBE-6:-LDDRjQC5RjZT3pzW2Tk:bualya8) ([raw file](https://github.com/batfish/batfish/blob/72806155fcf5cf5f17fa9a91cf6f5624b86355fe/projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromApplicationOrApplicationSet.java#L31)):*
<details><summary><i>Previously, erikljungman wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You still need to make sure the application is not `null` in order to call `applyTo`, or you will get NPE. Just don't do anything else if it is `null`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1463)*

**Comment by erikljungman** [comment]
Review status: 19 of 22 files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 1643 at r2](https://reviewable.io/reviews/batfish/batfish/1463#-LD9Rpsh5i8y2aG01ivt:-LDDZp4BB1tnfIETpD1F:borx6xc) ([raw file](https://github.com/batfish/batfish/blob/72806155fcf5cf5f17fa9a91cf6f5624b86355fe/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L1643)):*
<details><summary><i>Previously, erikljungman wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Actually this needs to be ApplicationOrApplicationSetReference. It is possible to specify an application-set after the keyword application - one of our tests caught this

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromApplicationOrApplicationSet.java, line 31 at r2](https://reviewable.io/reviews/batfish/batfish/1463#-LD9SIHV9xTD2GDPBE-6:-LDD_9ujArkGzKzOLeSx:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/72806155fcf5cf5f17fa9a91cf6f5624b86355fe/projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromApplicationOrApplicationSet.java#L31)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

You still need to make sure the application is not `null` in order to call `applyTo`, or you will get NPE. Just don't do anything else if it is `null`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1463)*

**Comment by arifogel** [comment]
Reviewed 3 of 4 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 1643 at r2](https://reviewable.io/reviews/batfish/batfish/1463#-LD9Rpsh5i8y2aG01ivt:-LDDvPy04N9LPWOOz5j6:b3cndhj) ([raw file](https://github.com/batfish/batfish/blob/72806155fcf5cf5f17fa9a91cf6f5624b86355fe/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L1643)):*
<details><summary><i>Previously, erikljungman wrote…</i></summary><blockquote>

Actually this needs to be ApplicationOrApplicationSetReference. It is possible to specify an application-set after the keyword application - one of our tests caught this
</blockquote></details>

Please test the reverse and implement your findings.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1463)*

**Comment by erikljungman** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 1643 at r2](https://reviewable.io/reviews/batfish/batfish/1463#-LD9Rpsh5i8y2aG01ivt:-LDE9mfFCuQD5NL116s9:bhqn8k3) ([raw file](https://github.com/batfish/batfish/blob/72806155fcf5cf5f17fa9a91cf6f5624b86355fe/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L1643)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Please test the reverse and implement your findings.
</blockquote></details>

I think this should work - after the keyword application you can reference either an application (user-defined or pre-defined) or an application-set (user-defined but not pre-defined) but after the keyword application-set you can only reference an application-set (user-defined or pre-defined)

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1463)*

**Pull request merged**
