### PR TITLE
MutableBDDInteger: internal leak checking and fixes

### PR DESCRIPTION
**Pull request by dhalperi**
There were no tests of MutableBDDInteger#sub or #toBDD(IpWildcard), or #and, so
I implemented minimal versions of those as well.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/9059)* status: 0 of 2 files reviewed, all discussions resolved

___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/MutableBDDInteger.java` line 245 at r1](https://reviewable.io/reviews/batfish/batfish/9059#-Nzd-I2d8EmE3BV_zpbD:-Nzd-I2d8EmE3BV_zpbE:b-hn5kwa) ([raw file](https://github.com/batfish/batfish/blob/8cda802e99c164b4cabf7e97657ff9e85f0f19b7/projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/MutableBDDInteger.java#L245)):*
> ```Java
>   public MutableBDDInteger ite(BDD b, MutableBDDInteger other) {
>     long startBDDCount = _factory.numOutstandingBDDs();
>     MutableBDDInteger val = new MutableBDDInteger(_factory, _bitvec.length);
> ```

FYI this was a fun one that took me a while to figure out: the copy constructor duplicates `this._bitvec`, then we overwrote it. This constructor allocates a new empty array.

(I think there were 2 or 3 of these).
___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/MutableBDDInteger.java` line 299 at r1](https://reviewable.io/reviews/batfish/batfish/9059#-Nzd-eic7VwaX7N1Khul:-Nzd-eidBU5Z1tPH3-if:b-7hpbv5) ([raw file](https://github.com/batfish/batfish/blob/8cda802e99c164b4cabf7e97657ff9e85f0f19b7/projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/MutableBDDInteger.java#L299)):*
> ```Java
>    * Subtract one BDD from another bitwise to create a new BDD
>    */
>   public MutableBDDInteger sub(MutableBDDInteger other) {
> ```

FYI this one deserves scrutiny, I tried to rename the variables to things I understood. But since there were no tests...
___
*[`projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/MutableBDDIntegerTest.java` line 116 at r1](https://reviewable.io/reviews/batfish/batfish/9059#-Nzd-lzI863r1b5LBLcn:-Nzd-lzI863r1b5LBLco:b-6mr6a2) ([raw file](https://github.com/batfish/batfish/blob/8cda802e99c164b4cabf7e97657ff9e85f0f19b7/projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/MutableBDDIntegerTest.java#L116)):*
> ```Java
>   @Test
>   public void testSub() {
>     BDDFactory factory = BDDUtils.bddFactory(10);
> ```

FYI these tests are basic copies of `testAdd` tweaked. But I may have made errors in the tweaking.

**Review by millstein — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/9059)* status: all files reviewed, 2 unresolved discussions (waiting on @dhalperi and @nickgian)

___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/MutableBDDInteger.java` line 127 at r1](https://reviewable.io/reviews/batfish/batfish/9059#-Nzeq0R1CeSoV6DvYJO9:-Nzeq0R1CeSoV6DvYJOA:b-tcrgfl) ([raw file](https://github.com/batfish/batfish/blob/2b0803414d1a651533674fa60bdce38cb7fe8e0e/projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/MutableBDDInteger.java#L127)):*
> ```Java
>     checkArgument(length <= _bitvec.length, "Not enough bits");
>     long startBDDCount = _factory.numOutstandingBDDs();
>     checkState(_trues.isEmpty(), "Unexpected array state");
> ```

I never noticed this _trues and _falses stuff before.  Is this done to save Java memory?  Otherwise it seems like these lists could be local variables instead of instance variables.
___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/MutableBDDInteger.java` line 149 at r1](https://reviewable.io/reviews/batfish/batfish/9059#-Nzeqe3s7RmxO5X8X_Bo:-Nzeqe3s7RmxO5X8X_Bp:b-y9xap7) ([raw file](https://github.com/batfish/batfish/blob/2b0803414d1a651533674fa60bdce38cb7fe8e0e/projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/MutableBDDInteger.java#L149)):*
> ```Java
>   public BDD toBDD(IpWildcard ipWildcard) {
>     checkArgument(_bitvec.length >= Prefix.MAX_PREFIX_LENGTH);
>     long startBDDCount = _factory.numOutstandingBDDs() + _bitvec.length;
> ```

Why the `+ _bitvec.length` part?
___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/MutableBDDInteger.java` line 299 at r1](https://reviewable.io/reviews/batfish/batfish/9059#-Nzd-eic7VwaX7N1Khul:-NzewqHy8yKfx9HIptWn:b-izfpzr) ([raw file](https://github.com/batfish/batfish/blob/2b0803414d1a651533674fa60bdce38cb7fe8e0e/projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/MutableBDDInteger.java#L299)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

FYI this one deserves scrutiny, I tried to rename the variables to things I understood. But since there were no tests...
</blockquote></details>

Looks good to me, but another pair of eyes wouldn't hurt

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/9059)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @millstein and @nickgian)

___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/MutableBDDInteger.java` line 127 at r1](https://reviewable.io/reviews/batfish/batfish/9059#-Nzeq0R1CeSoV6DvYJO9:-Nzf-zA87f99RRNMYeGp:b-drowau) ([raw file](https://github.com/batfish/batfish/blob/2b0803414d1a651533674fa60bdce38cb7fe8e0e/projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/MutableBDDInteger.java#L127)):*
<details><summary><i>Previously, millstein (Todd Millstein) wrote…</i></summary><blockquote>

I never noticed this _trues and _falses stuff before.  Is this done to save Java memory?  Otherwise it seems like these lists could be local variables instead of instance variables.
</blockquote></details>

It's done to save allocs. They showed up on benchmarks pretty heavily.
___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/MutableBDDInteger.java` line 149 at r1](https://reviewable.io/reviews/batfish/batfish/9059#-Nzeqe3s7RmxO5X8X_Bo:-Nzf02szAjwLlxCHnRf0:b3a4ief) ([raw file](https://github.com/batfish/batfish/blob/2b0803414d1a651533674fa60bdce38cb7fe8e0e/projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/MutableBDDInteger.java#L149)):*
<details><summary><i>Previously, millstein (Todd Millstein) wrote…</i></summary><blockquote>

Why the `+ _bitvec.length` part?
</blockquote></details>

Good catch, it was wrong. This code was untested, and I wrote trivial tests. Not great ones, but better than nothing.

**Review by millstein — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/9059)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dhalperi and @nickgian)

___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/MutableBDDInteger.java` line 149 at r1](https://reviewable.io/reviews/batfish/batfish/9059#-Nzeqe3s7RmxO5X8X_Bo:-Nzf1f5Q3A_tUxWysnOf:b-j5veps) ([raw file](https://github.com/batfish/batfish/blob/2b0803414d1a651533674fa60bdce38cb7fe8e0e/projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/MutableBDDInteger.java#L149)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Good catch, it was wrong. This code was untested, and I wrote trivial tests. Not great ones, but better than nothing.
</blockquote></details>

The same thing is done in the `and` method below.  Is that also unintended?

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/9059)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @millstein and @nickgian)

___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/MutableBDDInteger.java` line 149 at r1](https://reviewable.io/reviews/batfish/batfish/9059#-Nzeqe3s7RmxO5X8X_Bo:-Nzf3l3G1Zo5i-aWPIAw:bnj9o9i) ([raw file](https://github.com/batfish/batfish/blob/2b0803414d1a651533674fa60bdce38cb7fe8e0e/projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/MutableBDDInteger.java#L149)):*
<details><summary><i>Previously, millstein (Todd Millstein) wrote…</i></summary><blockquote>

The same thing is done in the `and` method below.  Is that also unintended?
</blockquote></details>

OMG so much untested code.

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/9059)* status: all files reviewed, 1 unresolved discussion (waiting on @millstein and @nickgian)

___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/MutableBDDInteger.java` line 147 at r3](https://reviewable.io/reviews/batfish/batfish/9059#-Nzi6dzeEoIJXLu2NnGp:-Nzi8ySo3R-Cpvq-sloI:bagjoy0) ([raw file](https://github.com/batfish/batfish/blob/a063b5992118f92e0a0302796601d46a0bd9402f/projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/MutableBDDInteger.java#L147)):*
<details><summary><i>Previously, millstein (Todd Millstein) wrote…</i></summary><blockquote>

Maybe add a comment or some documentation on what this method does, while you're at it :)
</blockquote></details>

It's on the parent class and would be inherited in IDEs.

```
/** Build a constraint that matches the {@link Ip IPs} matched by the input {@link IpWildcard}. */
```

**Review by millstein — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/9059#-:-NziApFc3-fgC9XwMcfS:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nickgian)

**Pull request merged**
