### PR TITLE
checkstyle: catch more misplaced nullity annotations

### PR DESCRIPTION
**Pull request by dhalperi**
And fix a bunch of problems.

Interestingly, found multiple annotations that were bogus, e.g., on void types.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 454 of 454 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8854)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dhalperi)

**Review by arifogel — COMMENTED** [review]
> Reviewed 6 of 454 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8854)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dhalperi)

**Review by arifogel — COMMENTED** [review]
> Reviewed 148 of 454 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8854)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dhalperi)

**Review by arifogel — COMMENTED** [review]
> Reviewed 46 of 454 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8854)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/NumberSpace.java` line 46 at r1](https://reviewable.io/reviews/batfish/batfish/8854#-Nhs2I6nE3bUf5LV4T-B:-Nhs2I6nE3bUf5LV4T-C:bys93rn) ([raw file](https://github.com/batfish/batfish/blob/ab64f24275da1ddc8ff332eaa374d82e1bdd972b/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/NumberSpace.java#L46)):*
> ```Java
>      * method
>      */
>     @Nonnull
> ```

Double-checking the removal is intentional

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8854)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dhalperi)

___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/NumberSpace.java` line 46 at r1](https://reviewable.io/reviews/batfish/batfish/8854#-Nhs2I6nE3bUf5LV4T-B:-Nhs3FUR3n3G9l5WoSx3:b-r8otpa) ([raw file](https://github.com/batfish/batfish/blob/ab64f24275da1ddc8ff332eaa374d82e1bdd972b/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/NumberSpace.java#L46)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Double-checking the removal is intentional
</blockquote></details>

yeah the actual return type is `void`. This is one of the cases mentioned in the description :)

**Pull request merged**
