### PR TITLE
Identify metamako configuration format

### PR DESCRIPTION
**Pull request by corinaminer**
Identifies Metamako configurations by the phrase "username admin secret". As far as I could tell with the configurations at hand, that phrase appears in only and all Metamako device configurations. @saparikh @arifogel will that work more broadly, as far as you know?

### CODE REVIEW

**Comment by dhalperi** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/java/org/batfish/grammar/VendorConfigurationFormatDetector.java, line 188 at r1](https://reviewable.io:443/reviews/batfish/batfish/1042#-L77RCbYBqzXTty8D9DI:-L77RCbZbGkTcPmudanh:betw8jp) ([raw file](https://github.com/batfish/batfish/blob/34a813938e14fd3e0cd54240b9cf78c8b2ec4844/projects/batfish/src/main/java/org/batfish/grammar/VendorConfigurationFormatDetector.java#L188)):*
> ```Java
>   @Nullable
>   private ConfigurationFormat checkMetamako() {
>     if (_fileText.contains("username admin secret")) {
> ```

So the goal of this part of the code is to find something that is unique to the vendor at hand. In this case, I think this is actually very common (Metamako, like many others, seems to be Cisco-like).

The better detector might be something that finds lines like these:

```
! device: <foo> (A32-A7, MOS-0.13.25)
! device: <foo> (A32-A5, MOS-0.14.0)
```

Especially since the `MOS-#.#.#` is the part that relates to Metamako's "Metamako Operating System (MOS)".

I would use a gracious regex to catch lines like this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/1042)*

**Comment by corinaminer** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/java/org/batfish/grammar/VendorConfigurationFormatDetector.java, line 188 at r1](https://reviewable.io:443/reviews/batfish/batfish/1042#-L77RCbYBqzXTty8D9DI:-L77SS_D941mpWeA5-N9:b8t1y7c) ([raw file](https://github.com/batfish/batfish/blob/34a813938e14fd3e0cd54240b9cf78c8b2ec4844/projects/batfish/src/main/java/org/batfish/grammar/VendorConfigurationFormatDetector.java#L188)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

So the goal of this part of the code is to find something that is unique to the vendor at hand. In this case, I think this is actually very common (Metamako, like many others, seems to be Cisco-like).

The better detector might be something that finds lines like these:

```
! device: <foo> (A32-A7, MOS-0.13.25)
! device: <foo> (A32-A5, MOS-0.14.0)
```

Especially since the `MOS-#.#.#` is the part that relates to Metamako's "Metamako Operating System (MOS)".

I would use a gracious regex to catch lines like this.
</blockquote></details>

isn't that a comment that could be changed arbitrarily? seems like most of the other possible formats are identified by unique phrases in the config text.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/1042)*

**Comment by corinaminer** [comment]
Devices are now identified as Metamako if they have any of the following:
- the phrase "application metamux"
- the phrase "application metawatch"
- a line `! device: `[at least one non-newline char]` MOS-`[number]`.`[number]`.`[number]`)`

Of 29 sample Metamako configurations, 21 matched (at least) one of the first two criteria; all of them matched the third.

---

Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/java/org/batfish/grammar/VendorConfigurationFormatDetector.java, line 188 at r1](https://reviewable.io:443/reviews/batfish/batfish/1042#-L77RCbYBqzXTty8D9DI:-L77ipJ6mIl1jW3EWfPe:b-vdxyt4) ([raw file](https://github.com/batfish/batfish/blob/34a813938e14fd3e0cd54240b9cf78c8b2ec4844/projects/batfish/src/main/java/org/batfish/grammar/VendorConfigurationFormatDetector.java#L188)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

isn't that a comment that could be changed arbitrarily? seems like most of the other possible formats are identified by unique phrases in the config text.
</blockquote></details>

Added better identification criteria.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/1042#-:-L77iu5EY8b4K7NyQv0A:b-mwkbcg)*

**Comment by dhalperi** [comment]
Tests are failing because there are tests for it. I'm of mixed opinion -- we don't have grammar or interesting tests of this stuff -- as indicated by the failing cisco-assumptions that led to this work -- but we do parse its structure somewhat usefully in a cisco-like way right now.

@arifogel thoughts?

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[projects/batfish/src/main/java/org/batfish/grammar/VendorConfigurationFormatDetector.java, line 191 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1042#-L78LXJ66FX3ciLq0_JD:-L78LXJ7DZuNMIaQhhkI:bwt3zrq) ([raw file](https://github.com/batfish/batfish/blob/802c0a369c22d7503d435b762bda6ec6fdaa9cbb/projects/batfish/src/main/java/org/batfish/grammar/VendorConfigurationFormatDetector.java#L191)):*
> ```Java
>       return ConfigurationFormat.METAMAKO;
>     }
>     Matcher deviceDescription =
> ```

why two ifs vs three things `||` together?

---

*[projects/batfish/src/main/java/org/batfish/grammar/VendorConfigurationFormatDetector.java, line 192 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1042#-L78LhlO4TPM_qktEJNJ:-L78LhlO4TPM_qktEJNK:bv5rcxh) ([raw file](https://github.com/batfish/batfish/blob/802c0a369c22d7503d435b762bda6ec6fdaa9cbb/projects/batfish/src/main/java/org/batfish/grammar/VendorConfigurationFormatDetector.java#L192)):*
> ```Java
>     }
>     Matcher deviceDescription =
>         Pattern.compile("(?m)^! device: [^\\n]+ MOS-\\d+\\.\\d+\\.\\d+\\)$").matcher(_fileText);
> ```

compile the regex once (`private static final METAMAKO_MOS_PATTERN = Pattern.compile..`), then use the compiled Pattern's function instead to do the match.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1042#-:-L78QDAw8TzBI2-kfU6R:bvcp1da)*

**Comment by dhalperi** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/1042)*

**Comment by arifogel** [comment]
As discussed offline, this format for now should be detected but unsupported.

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1042#-:-L7B4jp75ggOcaeerZvt:b5l0h3l)*

**Comment by corinaminer** [comment]
Review status: 2 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/grammar/VendorConfigurationFormatDetector.java, line 191 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1042#-L78LXJ66FX3ciLq0_JD:-L7Bm5td2Z_eYmLtRuEq:b-1m2yml) ([raw file](https://github.com/batfish/batfish/blob/802c0a369c22d7503d435b762bda6ec6fdaa9cbb/projects/batfish/src/main/java/org/batfish/grammar/VendorConfigurationFormatDetector.java#L191)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

why two ifs vs three things `||` together?
</blockquote></details>

it was to avoid creating the matcher for ~75% of metamako configurations. new setup manages to do that without splitting up the if.

---

*[projects/batfish/src/main/java/org/batfish/grammar/VendorConfigurationFormatDetector.java, line 192 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1042#-L78LhlO4TPM_qktEJNJ:-L7B68wH06MdCMjf1R4K:b-a8r419) ([raw file](https://github.com/batfish/batfish/blob/802c0a369c22d7503d435b762bda6ec6fdaa9cbb/projects/batfish/src/main/java/org/batfish/grammar/VendorConfigurationFormatDetector.java#L192)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

compile the regex once (`private static final METAMAKO_MOS_PATTERN = Pattern.compile..`), then use the compiled Pattern's function instead to do the match.
</blockquote></details>

done for this and all other patterns in the file

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1042)*

**Comment by dhalperi** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/java/org/batfish/grammar/VendorConfigurationFormatDetector.java, line 192 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1042#-L78LhlO4TPM_qktEJNJ:-L7BswYW5Qdv6sM1eVtU:b-j7kwj7) ([raw file](https://github.com/batfish/batfish/blob/802c0a369c22d7503d435b762bda6ec6fdaa9cbb/projects/batfish/src/main/java/org/batfish/grammar/VendorConfigurationFormatDetector.java#L192)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

done for this and all other patterns in the file
</blockquote></details>

In future, would prefer wide-scale refactoring changes in a separate PR. It confuses this PR (e.g., if we want to revert this PR we revert the refactoring) and is not a blocker for this PR.

LGTM.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1042#-:-L7Bt61m3yzSWYL5eybf:bnfp4nl)*

**Pull request merged**
