### PR TITLE
Aggregate interfaces: EIGRP metrics after BW calculation

### PR DESCRIPTION
**Pull request by corinaminer**

### CODE REVIEW

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6401)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @progwriter)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6401#-MLSCDXX-lETiW6mc6R1:-MLSCDXX-lETiW6mc6R2:bkq1o6k) (no related file):*
+reviewer:@progwriter
Opening for review, but needs to be tested.

---

**Review by progwriter — COMMENTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6401)* status: all files reviewed, 2 unresolved discussions (waiting on @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 692 at r1](https://reviewable.io/reviews/batfish/batfish/6401#-MLTfL54Ctb77rpsluDE:-MLTfL55ANbX5IDlaaME:bh13vhe) ([raw file](https://github.com/batfish/batfish/blob/d3fe7a42841cc5f03dc91be7ec54f923c9547123/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L692)):*
> ```Java
>               }
>             })
>         // Recalculate EIGRP metrics now that bandwidths are accurate
> ```

I'd split this into a separate method, just like we do for `postProcessOspfCosts`
___
*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 701 at r1](https://reviewable.io/reviews/batfish/batfish/6401#-MLTmqFXDoG8uWpwkj91:-MLTmqFXDoG8uWpwkj92:b-4mp4tc) ([raw file](https://github.com/batfish/batfish/blob/d3fe7a42841cc5f03dc91be7ec54f923c9547123/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L701)):*
> ```Java
>               EigrpMetric metric = eigrp.getMetric();
>               EigrpMetricValues metricValues = metric.getValues();
>               EigrpMetricValues newValues = metricValues.toBuilder().setBandwidth(bw).build();
> ```

this doesn't save the previous value. IIUC, the precedence is: explicitly configured bandwidth part of metric of eigrp, then interface bandwidth (set or inferred)

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6401)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @progwriter)

___
*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 692 at r1](https://reviewable.io/reviews/batfish/batfish/6401#-MLTfL54Ctb77rpsluDE:-MLihPcB-tEo-pY7r8_l:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/d3fe7a42841cc5f03dc91be7ec54f923c9547123/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L692)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

I'd split this into a separate method, just like we do for `postProcessOspfCosts`
</blockquote></details>

done
___
*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 701 at r1](https://reviewable.io/reviews/batfish/batfish/6401#-MLTmqFXDoG8uWpwkj91:-MLihQiP2u-ooTesDpmO:b-7w12p0) ([raw file](https://github.com/batfish/batfish/blob/d3fe7a42841cc5f03dc91be7ec54f923c9547123/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L701)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

this doesn't save the previous value. IIUC, the precedence is: explicitly configured bandwidth part of metric of eigrp, then interface bandwidth (set or inferred)
</blockquote></details>

done:
- `EigrpMetricValues._bandwidth` is now nullable and settable
- postprocessing sets EIGRP bandwidth iff it wasn't already set (which now implies it was explicitly configured for EIGRP)

**Review by progwriter — COMMENTED** [review]
> Reviewed 6 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6401)* status: all files reviewed, 2 unresolved discussions (waiting on @corinaminer)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6401#-MLionSd43h-b_rBCCyr:-MLionSe7MP7uXBy1er4:bcrygrs) (no related file):*
Should add a test (single-device should suffice)

---
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 1893 at r2](https://reviewable.io/reviews/batfish/batfish/6401#-MLioOmM1CxpU9Cl5td-:-MLioOmM1CxpU9Cl5td0:bx8qif) ([raw file](https://github.com/batfish/batfish/blob/6a3d660ae02e529da3ddcac7f2040444b92cd632/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L1893)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>     if (bw == null && iface.getChannelGroup() == null) {
>       _w.redFlag(
>           String.format("Missing bandwidth for %s, EIGRP metric will be wrong", iface.getName()));
>       bw = (long) 1e9; // default to 1e9 kbps
>     }
> ```
</details>

surely we can just remove this, and not warn?

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6401)* status: all files reviewed, 2 unresolved discussions (waiting on @corinaminer and @progwriter)

___
*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 1893 at r2](https://reviewable.io/reviews/batfish/batfish/6401#-MLioOmM1CxpU9Cl5td-:-MLj34Op6Nfn1nq7jIeh:bb50aud) ([raw file](https://github.com/batfish/batfish/blob/6a3d660ae02e529da3ddcac7f2040444b92cd632/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L1893)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

> ```
>     if (bw == null && iface.getChannelGroup() == null) {
>       _w.redFlag(
>           String.format("Missing bandwidth for %s, EIGRP metric will be wrong", iface.getName()));
>       bw = (long) 1e9; // default to 1e9 kbps
>     }
> ```
surely we can just remove this, and not warn?
</blockquote></details>

i wasn't sure, are port-channels the only type of interface for which bandwidth may not be set?

**Review by progwriter — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6401)* status: all files reviewed, 3 unresolved discussions (waiting on @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 1893 at r2](https://reviewable.io/reviews/batfish/batfish/6401#-MLioOmM1CxpU9Cl5td-:-MLjUJGm6MmBMSEVG7PE:bh046qr) ([raw file](https://github.com/batfish/batfish/blob/6a3d660ae02e529da3ddcac7f2040444b92cd632/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L1893)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

i wasn't sure, are port-channels the only type of interface for which bandwidth may not be set?
</blockquote></details>

At this point, likely yes. Also, even if we're wrong we'll quickly see the errors in VI land
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/eigrp/EigrpMetricValues.java, line 75 at r2](https://reviewable.io/reviews/batfish/batfish/6401#-MLjVAAl5IZC15IcEFT6:-MLjVAAl5IZC15IcEFT7:b-dxd2dc) ([raw file](https://github.com/batfish/batfish/blob/6a3d660ae02e529da3ddcac7f2040444b92cd632/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/eigrp/EigrpMetricValues.java#L75)):*
> ```Java
>   }
> 
>   public void setBandwidth(@Nullable Long bandwidth) {
> ```

qq: why allow a non-primitive here if you expect a non-null value?
also you may need a `@JsonIgnore` just to be on safe side to prevent jackson form ever using the setter.

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6401)* status: 3 of 8 files reviewed, all discussions resolved (waiting on @progwriter)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6401#-MLionSd43h-b_rBCCyr:-MLoS_MZEqhIrpCrreKZ:bb7f2mf) (no related file):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

Should add a test (single-device should suffice)
</blockquote></details>

done

---
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 1893 at r2](https://reviewable.io/reviews/batfish/batfish/6401#-MLioOmM1CxpU9Cl5td-:-MLoTRYY6jb2QVqImJva:bqq3ctf) ([raw file](https://github.com/batfish/batfish/blob/6a3d660ae02e529da3ddcac7f2040444b92cd632/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L1893)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

At this point, likely yes. Also, even if we're wrong we'll quickly see the errors in VI land
</blockquote></details>

ok, removed.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/eigrp/EigrpMetricValues.java, line 75 at r2](https://reviewable.io/reviews/batfish/batfish/6401#-MLjVAAl5IZC15IcEFT6:-MLoScCI2asEu5i27qJD:b-bqqofk) ([raw file](https://github.com/batfish/batfish/blob/6a3d660ae02e529da3ddcac7f2040444b92cd632/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/eigrp/EigrpMetricValues.java#L75)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

qq: why allow a non-primitive here if you expect a non-null value?
also you may need a `@JsonIgnore` just to be on safe side to prevent jackson form ever using the setter. 
</blockquote></details>

because i was using this method in the constructor. but i stopped doing that and switched this to take in a primitive.

**Review by progwriter — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6401#-:-MLoZ_7k7uGmkJLEvoHR:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-portchannel-eigrp, line 5 at r3](https://reviewable.io/reviews/batfish/batfish/6401#-MLoZO5kCCBHTQk3uhzS:-MLoZO5l75Y6H4YVe_is:brf7hfb) ([raw file](https://github.com/batfish/batfish/blob/666d233fafcb82d675f16a93d19dc309e6ff9606/projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-portchannel-eigrp#L5)):*
> ```
> !
> !
> vrf definition vrf_100
> ```

nit: this extra vrf doesn't seem relevant

**Review by progwriter — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6401)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
