### PR TITLE
Sort cluster list in bgp rib answer output for determinism

### PR DESCRIPTION
**Pull request by arifogel**
* already done for communities

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8849)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel, @progwriter, @sfraint, and @SLarkworthy)

___
*[`projects/question/src/main/java/org/batfish/question/routes/RoutesAnswererUtil.java` line 461 at r1](https://reviewable.io/reviews/batfish/batfish/8849#-NhZ-kGV1bX3M4Yx1CZs:-NhZ-kGV1bX3M4Yx1CZt:b7pr506) ([raw file](https://github.com/batfish/batfish/blob/3d38d7155aa077d682231cbb41d6fc1b0f724808/projects/question/src/main/java/org/batfish/question/routes/RoutesAnswererUtil.java#L461)):*
> ```Java
>             bgpv4Route.getClusterList().isEmpty()
>                 ? null
>                 : bgpv4Route.getClusterList().stream()
> ```

might be simpler to do `ImmutableSortedSet.copyOf()` but this is fine too.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8849)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi, @progwriter, @sfraint, and @SLarkworthy)

___
*[`projects/question/src/main/java/org/batfish/question/routes/RoutesAnswererUtil.java` line 461 at r1](https://reviewable.io/reviews/batfish/batfish/8849#-NhZ-kGV1bX3M4Yx1CZs:-NhZ04YkCFHOo9INWKWo:b-qn87ie) ([raw file](https://github.com/batfish/batfish/blob/3d38d7155aa077d682231cbb41d6fc1b0f724808/projects/question/src/main/java/org/batfish/question/routes/RoutesAnswererUtil.java#L461)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

might be simpler to do `ImmutableSortedSet.copyOf()` but this is fine too.
</blockquote></details>

I started with that, but it looked weird since the schema is a list instead of a set. Maybe it doesn't matter.

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8849)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @progwriter, @sfraint, and @SLarkworthy)

**Review by arifogel — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8849)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @progwriter, @sfraint, and @SLarkworthy)

**Pull request merged**
