### PR TITLE
Fix test L1 interfaces with overlapping tags on sub-interfaces

### PR DESCRIPTION
**Pull request by arifogel**
- prep for new l3 adjacencies

### CODE REVIEW

**Review by sfraint — COMMENTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8219)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel and @corinaminer)

___
*[tests/parsing-tests/networks/example-juniper/configs/as1border1.cfg, line 5 at r1](https://reviewable.io/reviews/batfish/batfish/8219#-Mzw0zdz-C7uAHDpAFaJ:-Mzw0ze-DTc0TVKfME1T:bz7pdn2) ([raw file](https://github.com/batfish/batfish/blob/53867bcb8529381bcc8ef6e1df3c382b4f210001/tests/parsing-tests/networks/example-juniper/configs/as1border1.cfg#L5)):*
> ```INI
> set interfaces lo0 unit 0 family inet address 1.1.1.1/32
> set interfaces fe-0/0/0 unit 0  family inet address 1.0.1.1/24
> set interfaces fe-0/0/0 unit 1  family inet address 10.12.11.1/24
> ```

why make these changes?



_Code quote:_
```INI
set interfaces fe-0/0/0 unit 1  family inet address 10.12.11.1/24
```

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8219)* status: all files reviewed, 1 unresolved discussion (waiting on @corinaminer and @sfraint)

___
*[tests/parsing-tests/networks/example-juniper/configs/as1border1.cfg, line 5 at r1](https://reviewable.io/reviews/batfish/batfish/8219#-Mzw0zdz-C7uAHDpAFaJ:-Mzw669dB33-pcnddI62:b-q24dla) ([raw file](https://github.com/batfish/batfish/blob/53867bcb8529381bcc8ef6e1df3c382b4f210001/tests/parsing-tests/networks/example-juniper/configs/as1border1.cfg#L5)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

why make these changes?
</blockquote></details>

If you're asking why make these changes at all, it's because you cannot have two different units that accept the same tags. In this case, unit 0 and unit 1 were both configured to accept untagged frames (kind of - unit 1 without ip and without vlan-tag is probably illegal by itself on  Juniper).

If you're asking why I separated into multiple interfaces instead of setting vlan-ids, it's because there is no L1 topology file for this network and I don't want it to choke when we swich to new l3 adjacencies (no other interfaces would be attached to switch for tagged frame for any given tag).

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8219)* status: all files reviewed, 1 unresolved discussion (waiting on @corinaminer and @sfraint)

___
*[tests/parsing-tests/networks/example-juniper/configs/as1border1.cfg, line 5 at r1](https://reviewable.io/reviews/batfish/batfish/8219#-Mzw0zdz-C7uAHDpAFaJ:-Mzw6vzj6lEjqQalAOz6:b-g3zft7) ([raw file](https://github.com/batfish/batfish/blob/53867bcb8529381bcc8ef6e1df3c382b4f210001/tests/parsing-tests/networks/example-juniper/configs/as1border1.cfg#L5)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

If you're asking why make these changes at all, it's because you cannot have two different units that accept the same tags. In this case, unit 0 and unit 1 were both configured to accept untagged frames (kind of - unit 1 without ip and without vlan-tag is probably illegal by itself on  Juniper).

If you're asking why I separated into multiple interfaces instead of setting vlan-ids, it's because there is no L1 topology file for this network and I don't want it to choke when we swich to new l3 adjacencies (no other interfaces would be attached to switch for tagged frame for any given tag).
</blockquote></details>

Correction:`... unit 1 _with_ ip ...`

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8219)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

___
*[tests/parsing-tests/networks/example-juniper/configs/as1border1.cfg, line 5 at r1](https://reviewable.io/reviews/batfish/batfish/8219#-Mzw0zdz-C7uAHDpAFaJ:-Mzw7Hly1zTB5YOCE_C5:bsg7dj2) ([raw file](https://github.com/batfish/batfish/blob/53867bcb8529381bcc8ef6e1df3c382b4f210001/tests/parsing-tests/networks/example-juniper/configs/as1border1.cfg#L5)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Correction:`... unit 1 _with_ ip ...`
</blockquote></details>

yeah I was asking about the vlan IDs

**Pull request merged**
