### PR TITLE
A10: Generate IP space from NAT pool definition

### PR DESCRIPTION
**Pull request by ratulm**

### CODE REVIEW

**Review by sfraint — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7832#-:-Mr9n81GAktR6w_22tQ4:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ratulm)

___
*[projects/batfish/src/main/java/org/batfish/vendor/a10/representation/A10Configuration.java, line 359 at r1](https://reviewable.io/reviews/batfish/batfish/7832#-Mr9kztQ5lcbHEL5DNlS:-Mr9kztQ5lcbHEL5DNlT:bk8t5h4) ([raw file](https://github.com/batfish/batfish/blob/6fac2d516b55510361bca6a0a8c115b89e951116/projects/batfish/src/main/java/org/batfish/vendor/a10/representation/A10Configuration.java#L359)):*
> ```Java
>     markStructures();
> 
>     // these make internal data accessible
> ```

this comment doesn't seem very clear to me, can you elaborate?

or maybe just leave the old comment and add a new comment about adding named IP spaces so NAT pools exist within the VI model



_Code quote:_
```Java
    // these make internal data accessible
```

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7832)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/vendor/a10/representation/A10Configuration.java, line 359 at r1](https://reviewable.io/reviews/batfish/batfish/7832#-Mr9kztQ5lcbHEL5DNlS:-Mr9pyt0948jDMgXcil1:bmfzwet) ([raw file](https://github.com/batfish/batfish/blob/6fac2d516b55510361bca6a0a8c115b89e951116/projects/batfish/src/main/java/org/batfish/vendor/a10/representation/A10Configuration.java#L359)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

this comment doesn't seem very clear to me, can you elaborate?

or maybe just leave the old comment and add a new comment about adding named IP spaces so NAT pools exist within the VI model
</blockquote></details>

Removed the comment. It isn't adding any value. The method names and javadoc are good enough.

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7832)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/vendor/a10/representation/A10Configuration.java, line 359 at r1](https://reviewable.io/reviews/batfish/batfish/7832#-Mr9kztQ5lcbHEL5DNlS:-Mr9qFAO6dkH1Ai8SBZU:b4c9lyr) ([raw file](https://github.com/batfish/batfish/blob/6fac2d516b55510361bca6a0a8c115b89e951116/projects/batfish/src/main/java/org/batfish/vendor/a10/representation/A10Configuration.java#L359)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

Removed the comment. It isn't adding any value. The method names and javadoc are good enough. 
</blockquote></details>

:thumbsup:

**Review by sfraint — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7832)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ratulm)

**Pull request merged**
