### PR TITLE
Factor out dispositionState method

### PR DESCRIPTION
**Pull request by anothermattbrown**

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8729)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown)

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8729)* status: all files reviewed, 2 unresolved discussions (waiting on @anothermattbrown)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/8729#-NXHy3DNCauUEjrObuti:-NXHy3DNCauUEjrObutj:b-8dws15) (no related file):*
Please fix commit message pattern. Need a noun in the commit message like "BDDReachabilityUtils: ..." - there are thousands of files in the project.

___
___
*[`projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityUtils.java` line 261 at r1](https://reviewable.io/reviews/batfish/batfish/8729#-NXHxwV9CuqZtsFtIpQ1:-NXHxwV9CuqZtsFtIpQ2:bbchpsj) ([raw file](https://github.com/batfish/batfish/blob/0512a80aaa67e221d90561f8bfb52a749b77ea01/projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityUtils.java#L261)):*
> ```Java
>   }
> 
>   public static StateExpr dispositionState(FlowDisposition disposition) {
> ```

Now that it's factored out, add javadoc. Note the cases it doesn't handle.

**Review by anothermattbrown — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8729)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @dhalperi)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/8729#-NXHy3DNCauUEjrObuti:-NXI4L0K24CEhYNAnblg:b32wtd) (no related file):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Please fix commit message pattern. Need a noun in the commit message like "BDDReachabilityUtils: ..." - there are thousands of files in the project.
</blockquote></details>

ok

___
___
*[`projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityUtils.java` line 261 at r1](https://reviewable.io/reviews/batfish/batfish/8729#-NXHxwV9CuqZtsFtIpQ1:-NXI4PgvBX6QUMbZ7b8v:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/0512a80aaa67e221d90561f8bfb52a749b77ea01/projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityUtils.java#L261)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Now that it's factored out, add javadoc. Note the cases it doesn't handle.
</blockquote></details>

done

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8729)* status: all files reviewed, 1 unresolved discussion (waiting on @anothermattbrown)

**Pull request merged**
