### PR TITLE
Implement dataplane tracking for static routes

### PR DESCRIPTION
**Pull request by arifogel**
- static routes with tracks are now subject to an activation condition
- support tracking routes, interface line status

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 14 of 15 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7926)* status: 13 of 27 files reviewed, 1 unresolved discussion (waiting on @arifogel)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7926#-MtB9tSABztxajFFoHBA:-MtB9tSB7Sm1nQP_4Sv5:b-xwdxy2) (no related file):*
after batfish/batfish#7925

---

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 41 files at r4, 8 of 14 files at r5, 2 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7926)* status: 11 of 41 files reviewed, 2 unresolved discussions (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java, line 589 at r8](https://reviewable.io/reviews/batfish/batfish/7926#-MtEntx3-_Xl69EykbbP:-MtEntx3-_Xl69EykbbQ:b44v6a5) ([raw file](https://github.com/batfish/batfish/blob/247a4a7b319255311a9de5cf594e5bc9fe6250e1/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java#L589)):*
> ```Java
>       // property of conditioanl RIB
>       assert sr.hasNextHopIp() || sr.getTrack() != null;
>       if ((!sr.hasNextHopIp() || shouldActivateNextHopIpRoute(sr, _mainRib, _resolutionRestriction))
> ```

this could be a regression for NHINT+IP+Track routes, right?

I think this should be factored out into a method of one route, probably with its own NextHop visitor and that checks tracks.

Not sure "hasNextHopIp" is actually useful.



_Code quote:_
```Java
sr.hasNextHopIp() || shouldActivateNextHopIpRoute(sr, _mainRib, _resolutionRestriction)
```
___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java, line 1018 at r8](https://reviewable.io/reviews/batfish/batfish/7926#-MtEoke41R-f9pkj9TlX:-MtEoke41R-f9pkj9TlY:b-howa2l) ([raw file](https://github.com/batfish/batfish/blob/247a4a7b319255311a9de5cf594e5bc9fe6250e1/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java#L1018)):*
> ```Java
>         public Void visitNextHopInterface(NextHopInterface nextHopInterface) {
>           // We have an interface route, check that interface exists and is active
>           Interface iface = _c.getAllInterfaces().get(nextHopInterface.getInterfaceName());
> ```

Having a hard time reading this function.. it's doing a lot in shared state and lambdas.

I was going to propose that we should factor out a function `boolean isConditional(StaticRoute sr)` and use that to pick the RIB here. Would be a lot simpler, I think. Otherwise lots of redundant logic in the visitor, etc.

But that makes it hard to throw away nhint routes with down interfaces. Might even be cleaner (and future proof) to consider nhint routes as conditional.

Take it or leave it.



_Code quote:_
```Java
    for (StaticRoute sr : _vrf.getStaticRoutes()) {
      new NextHopVisitor<Void>() {

        @Override
        public Void visitNextHopIp(NextHopIp nextHopIp) {
          // Always conditional when there is only a next-hop IP
          _staticConditionalRib.mergeRouteGetDelta(sr);
          return null;
        }

        @Override
        public Void visitNextHopInterface(NextHopInterface nextHopInterface) {
          // We have an interface route, check that interface exists and is active
          Interface iface = _c.getAllInterfaces().get(nextHopInterface.getInterfaceName());
```

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7926)* status: 8 of 41 files reviewed, 2 unresolved discussions (waiting on @arifogel, @corinaminer, and @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java, line 589 at r8](https://reviewable.io/reviews/batfish/batfish/7926#-MtEntx3-_Xl69EykbbP:-MtFMS326nM9FD4AyiHg:b58oi2n) ([raw file](https://github.com/batfish/batfish/blob/247a4a7b319255311a9de5cf594e5bc9fe6250e1/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java#L589)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

this could be a regression for NHINT+IP+Track routes, right?

I think this should be factored out into a method of one route, probably with its own NextHop visitor and that checks tracks.

Not sure "hasNextHopIp" is actually useful.
</blockquote></details>

should be fixed
___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java, line 1018 at r8](https://reviewable.io/reviews/batfish/batfish/7926#-MtEoke41R-f9pkj9TlX:-MtFMQhS1CKCutVGvcxw:b-qtds2k) ([raw file](https://github.com/batfish/batfish/blob/247a4a7b319255311a9de5cf594e5bc9fe6250e1/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java#L1018)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Having a hard time reading this function.. it's doing a lot in shared state and lambdas.

I was going to propose that we should factor out a function `boolean isConditional(StaticRoute sr)` and use that to pick the RIB here. Would be a lot simpler, I think. Otherwise lots of redundant logic in the visitor, etc.

But that makes it hard to throw away nhint routes with down interfaces. Might even be cleaner (and future proof) to consider nhint routes as conditional.

Take it or leave it.
</blockquote></details>

refactored and:
- made interface routes conditional
- throw on non-existent interfaces
- fixed some tests

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 15 files at r3, 14 of 41 files at r4, 2 of 14 files at r5, 1 of 4 files at r6, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7926)* status: 13 of 41 files reviewed, 3 unresolved discussions (waiting on @arifogel, @corinaminer, and @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java, line 600 at r10](https://reviewable.io/reviews/batfish/batfish/7926#-MtFOIHs4m7NSHuFbBxm:-MtFOIHs4m7NSHuFbBxn:b9vm8ld) ([raw file](https://github.com/batfish/batfish/blob/9b1eb59687b4e8bf7c5cac8e5bb5a50b1e24bb86/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java#L600)):*
> ```Java
> 
>   private boolean shouldActivateConditionalStaticRoute(StaticRoute sr) {
>     if (sr.getNextHop() instanceof NextHopIp) {
> ```

visitor, not `instanceof` -- right?



_Code quote:_
```Java
instanceof NextHopIp
```
___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java, line 624 at r10](https://reviewable.io/reviews/batfish/batfish/7926#-MtFOD3U57EVJ6l7JnbN:-MtFOD3U57EVJ6l7JnbO:bwl9io2) ([raw file](https://github.com/batfish/batfish/blob/9b1eb59687b4e8bf7c5cac8e5bb5a50b1e24bb86/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java#L624)):*
> ```Java
> 
>   private boolean isConditionalStaticRoute(StaticRoute sr) {
>     return isConditionalStaticRouteNextHop(sr.getNextHop()) || sr.getTrack() != null;
> ```

Flip the `||`?
___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java, line 642 at r10](https://reviewable.io/reviews/batfish/batfish/7926#-MtFNxMp0l8YFEMV2wj_:-MtFNxMp0l8YFEMV2wja:b-6lyx2g) ([raw file](https://github.com/batfish/batfish/blob/9b1eb59687b4e8bf7c5cac8e5bb5a50b1e24bb86/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java#L642)):*
> ```Java
>           // TODO: remove invalid static routes in post-processing, and change to assertion
>           checkState(
>               _c.getAllInterfaces().containsKey(nextHopInterface.getInterfaceName()),
> ```

Is this enforced elsewhere? E.g., `finalizeConfiguration`?

If so, then we can just `assert` instead of `checkArgument`.

If not, this is probably risky - unpredictable crashes at runtime based on conversion imprecision. Log and return `true` instead.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7926)* status: 15 of 43 files reviewed, all discussions resolved (waiting on @arifogel, @corinaminer, and @dhalperi)

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7926)* status: 15 of 43 files reviewed, 1 unresolved discussion (waiting on @arifogel, @corinaminer, and @dhalperi)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7926#-MtG8sXQAzUKk-N7ngwd:-MtG8sXR-m33dPczMkAy:bpebkbt) (no related file):*
need to fix tests that expect broken static routes

---

**Review by dhalperi — COMMENTED** [review]
> Reviewed 7 of 7 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7926)* status: 22 of 49 files reviewed, all discussions resolved (waiting on @arifogel, @corinaminer, and @dhalperi)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 15 of 15 files at r1, 26 of 41 files at r4, 3 of 14 files at r5.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7926)* status: 28 of 49 files reviewed, all discussions resolved (waiting on @corinaminer and @dhalperi)

**Review by arifogel — COMMENTED** [review]
> Reviewed 7 of 14 files at r5, 3 of 4 files at r6, 1 of 2 files at r10, 1 of 3 files at r11.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7926)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

**Pull request merged**
