### PR TITLE
a new implementation of bgp session status that tracks dynamic neighbors

### PR DESCRIPTION
**Pull request by ratulm**
did a completely new plugin so we could use a simpler output format and not break old stuff. 

@progwriter - most stuff is old so perhaps OK, but i am particularly curious if i used the initBgpTopology API properly. thanks.

### CODE REVIEW

**Comment by progwriter** [comment]
Mostly good; API use seems good. Only asking for some clarifications, and small naming nits.

---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerer.java, line 46 at r1](https://reviewable.io/reviews/batfish/batfish/1245#-LB-6R752e0-ODc0LgEs:-LB-6R752e0-ODc0LgEt:b34ty3r) ([raw file](https://github.com/batfish/batfish/blob/dc4adc46605f20ab7f30c433342c75c3c7c95b5c/projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerer.java#L46)):*
> ```Java
>     Set<Ip> allInterfaceIps = new HashSet<>();
>     Set<Ip> loopbackIps = new HashSet<>();
>     Map<Ip, Set<String>> ipOwners = new HashMap<>();
> ```

Any reason to not to use `computeIpOwners` from `CommonUtil`? That handles vrrp, so seems more comprehensive/accurate. (something I've noticed even in the old version)

---

*[projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerer.java, line 56 at r1](https://reviewable.io/reviews/batfish/batfish/1245#-LB-AERg7KFUvyMAAJEc:-LB-AERg7KFUvyMAAJEd:bsx83l3) ([raw file](https://github.com/batfish/batfish/blob/dc4adc46605f20ab7f30c433342c75c3c7c95b5c/projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerer.java#L56)):*
> ```Java
>               loopbackIps.add(ip);
>             }
>             allInterfaceIps.add(ip);
> ```

Seems like `allInterfaces` is equivalent to `currentIpOwners.keySet()`. I guess this improves readability? Up to you on whether to keep it.

---

*[projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerer.java, line 67 at r1](https://reviewable.io/reviews/batfish/batfish/1245#-LB-6ya7E0mOTSBnLcbm:-LB-6ya7E0mOTSBnLcbn:b-1f9j75) ([raw file](https://github.com/batfish/batfish/blob/dc4adc46605f20ab7f30c433342c75c3c7c95b5c/projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerer.java#L67)):*
> ```Java
>         CommonUtil.initBgpTopology(configurations, ipOwners, true);
> 
>     Network<BgpNeighbor, BgpSession> dynamicBgpTopology =
> ```

Small nit: I feel like dynamic is getting overloaded here. Perhaps "configured" vs "computed" (or "established") bgp topology?

---

*[projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerer.java, line 109 at r1](https://reviewable.io/reviews/batfish/batfish/1245#-LB-7qKM5nLXAhManDbY:-LB-7qKM5nLXAhManDbZ:bkf4xaq) ([raw file](https://github.com/batfish/batfish/blob/dc4adc46605f20ab7f30c433342c75c3c7c95b5c/projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerer.java#L109)):*
> ```Java
>       Ip localIp = bgpNeighbor.getLocalIp();
>       if (bgpNeighbor.getDynamic()) {
>         bgpSessionInfo._staticStatus = SessionStatus.PASSIVE;
> ```

I've been wading through cisco/juniper docs and it seems that it is possible for a non-dynamic peer to be passive, which is not what this captures. What we really mean is the "listening end of a dynamic peering". Perhaps rename to "DYNAMIC" or "DYNAMIC_LISTEN"? 

---

*[projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerer.java, line 143 at r1](https://reviewable.io/reviews/batfish/batfish/1245#-LB-9dom41NP7_g3tTV8:-LB-9dom41NP7_g3tTV9:b-2fpou9) ([raw file](https://github.com/batfish/batfish/blob/dc4adc46605f20ab7f30c433342c75c3c7c95b5c/projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerer.java#L143)):*
> ```Java
> 
>       bgpSessionInfo._dynamicNeighbors =
>           dynamicBgpTopology != null && dynamicBgpTopology.nodes().contains(bgpNeighbor)
> ```

Shouldn't this conjunction also include `bgpNeighbor.getDynamic()`?  Otherwise we set this field even for non-dynamic peers.

---

*[tests/basic/bgpSessionStatusNew.ref, line 35 at r1](https://reviewable.io/reviews/batfish/batfish/1245#-LB-B9k-6HmQOBTDwHg_:-LB-B9k-6HmQOBTDwHga:b-dch0cu) ([raw file](https://github.com/batfish/batfish/blob/dc4adc46605f20ab7f30c433342c75c3c7c95b5c/tests/basic/bgpSessionStatusNew.ref#L35)):*
> ```
>           "name" : "as2border2",
>           "id" : "node-as2border2",
>           "type" : "UNKNOWN"
> ```

Can't quite grok what node type "unknown" means here. Is this expected to be unknown?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1245#-:-LB-Aw5R0_U04uCx0P6K:b-sfimi7)*

**Comment by ratulm** [comment]
Review status: 7 of 22 files reviewed at latest revision, 5 unresolved discussions.

---

*[projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerer.java, line 46 at r1](https://reviewable.io/reviews/batfish/batfish/1245#-LB-6R752e0-ODc0LgEs:-LB-VmjvA_b3m4Tpio4R:bk0aj2) ([raw file](https://github.com/batfish/batfish/blob/dc4adc46605f20ab7f30c433342c75c3c7c95b5c/projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerer.java#L46)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

Any reason to not to use `computeIpOwners` from `CommonUtil`? That handles vrrp, so seems more comprehensive/accurate. (something I've noticed even in the old version)
</blockquote></details>

The other thing happening in that loop was labeling loopback IPs, which I realized was buggy (as it wasn't tracking which loopback IPs were for which node). See the new implementation in ComminUtil. Do I need to worry about VRFs there?

---

*[projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerer.java, line 67 at r1](https://reviewable.io/reviews/batfish/batfish/1245#-LB-6ya7E0mOTSBnLcbm:-LB-EgUgBevQEcmCnyAr:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/dc4adc46605f20ab7f30c433342c75c3c7c95b5c/projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerer.java#L67)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

Small nit: I feel like dynamic is getting overloaded here. Perhaps "configured" vs "computed" (or "established") bgp topology?
</blockquote></details>

Done.

---

*[projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerer.java, line 109 at r1](https://reviewable.io/reviews/batfish/batfish/1245#-LB-7qKM5nLXAhManDbY:-LB-EyJY47V5je0-d9_I:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/dc4adc46605f20ab7f30c433342c75c3c7c95b5c/projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerer.java#L109)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

I've been wading through cisco/juniper docs and it seems that it is possible for a non-dynamic peer to be passive, which is not what this captures. What we really mean is the "listening end of a dynamic peering". Perhaps rename to "DYNAMIC" or "DYNAMIC_LISTEN"? 
</blockquote></details>

Done.

---

*[projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerer.java, line 143 at r1](https://reviewable.io/reviews/batfish/batfish/1245#-LB-9dom41NP7_g3tTV8:-LB-F6FC1mfiOCbLDp82:bt2jkql) ([raw file](https://github.com/batfish/batfish/blob/dc4adc46605f20ab7f30c433342c75c3c7c95b5c/projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerer.java#L143)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

Shouldn't this conjunction also include `bgpNeighbor.getDynamic()`?  Otherwise we set this field even for non-dynamic peers.
</blockquote></details>

that is the intent. the degree for a non-dynamic, configured session that is healthy could be 0 (e.g., because of ACLs) and is something to be flagged. 

---

*[tests/basic/bgpSessionStatusNew.ref, line 35 at r1](https://reviewable.io/reviews/batfish/batfish/1245#-LB-B9k-6HmQOBTDwHg_:-LB-Kevm6n-oKCvRbWqH:b-s8c0u0) ([raw file](https://github.com/batfish/batfish/blob/dc4adc46605f20ab7f30c433342c75c3c7c95b5c/tests/basic/bgpSessionStatusNew.ref#L35)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

Can't quite grok what node type "unknown" means here. Is this expected to be unknown?
</blockquote></details>

tweaked the object to not force a type

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1245)*

**Comment by dhalperi** [comment]
*[tests/aws/topology-example-aws.ref, line 8 at r2](https://reviewable.io/reviews/batfish/batfish/1245#-LB1oWYo5Mbpjx6aM9h7:-LB1oWYo5Mbpjx6aM9h8:bp3ln6w) ([raw file](https://github.com/batfish/batfish/blob/6fcc23e23b378ca6baec3721433acd94c20dfd19/tests/aws/topology-example-aws.ref#L8)):*
> ```
>       "contents" : [
>         "node-vpc-f8fad69d",
>         "aggregate-subnet-d9cafabc",
> ```

Why would this ref change?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1245)*

**Comment by dhalperi** [comment]
*[a discussion](https://reviewable.io/reviews/batfish/batfish/1245#-LB1paPwA1jUae9_e18a:-LB1paPwA1jUae9_e18b:b-x1obbf) (no related file):*
There seems to be something funky with the reporting? If I supply node1regex and node2regex, in the same vrf I get both UNIQUE_MATCH (with both node and remoteNode populated) and DYNAMIC_LISTEN (with only node populated). This latter one doesn't seem that useful in this context -- probably worth discussing in person.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1245)*

**Comment by ratulm** [comment]
Review status: 7 of 22 files reviewed at latest revision, 7 unresolved discussions.

---

*[tests/aws/topology-example-aws.ref, line 8 at r2](https://reviewable.io/reviews/batfish/batfish/1245#-LB1oWYo5Mbpjx6aM9h7:-LB1sIHw50bZy4YTppzR:bnnrult) ([raw file](https://github.com/batfish/batfish/blob/6fcc23e23b378ca6baec3721433acd94c20dfd19/tests/aws/topology-example-aws.ref#L8)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Why would this ref change?
</blockquote></details>

The object is using Set and not SortedSet. I'll change as part of another PR.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1245)*

**Comment by ratulm** [comment]
Review status: 7 of 22 files reviewed at latest revision, 7 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1245#-LB1paPwA1jUae9_e18a:-LB1syx33FzczxkgINI6:b8f55mu) (no related file):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

There seems to be something funky with the reporting? If I supply node1regex and node2regex, in the same vrf I get both UNIQUE_MATCH (with both node and remoteNode populated) and DYNAMIC_LISTEN (with only node populated). This latter one doesn't seem that useful in this context -- probably worth discussing in person.
</blockquote></details>

What arguments were you using? 

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1245)*

**Comment by progwriter** [comment]
Reviewed 15 of 15 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerer.java, line 46 at r1](https://reviewable.io/reviews/batfish/batfish/1245#-LB-6R752e0-ODc0LgEs:-LB1uut49O6lSoHEd43-:b-3r3xer) ([raw file](https://github.com/batfish/batfish/blob/dc4adc46605f20ab7f30c433342c75c3c7c95b5c/projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerer.java#L46)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

The other thing happening in that loop was labeling loopback IPs, which I realized was buggy (as it wasn't tracking which loopback IPs were for which node). See the new implementation in ComminUtil. Do I need to worry about VRFs there?
</blockquote></details>

:thumbsup: I don't think you need to worry about vrfs here.

---

*[projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerer.java, line 143 at r1](https://reviewable.io/reviews/batfish/batfish/1245#-LB-9dom41NP7_g3tTV8:-LB1uJ2hCaBckR_1nYWY:byhwt9s) ([raw file](https://github.com/batfish/batfish/blob/dc4adc46605f20ab7f30c433342c75c3c7c95b5c/projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerer.java#L143)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

that is the intent. the degree for a non-dynamic, configured session that is healthy could be 0 (e.g., because of ACLs) and is something to be flagged. 
</blockquote></details>

Gotcha, this is much clearer after renaming. My bad.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1245)*

**Comment by dhalperi** [comment]
Review status: 18 of 21 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1245#-LB1paPwA1jUae9_e18a:-LBA2l5b-zOueX-zvBUx:bpnn4p8) (no related file):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

    "node1Regex": "<node1>",
    "node2Regex": "<node2>"

Happy to show you the specific network in person.
</blockquote></details>

Marking myself satisfied, you have the repro information to know if it's correct.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1245)*

**Comment by ratulm** [comment]
@progwriter - since you asked, i should let you know that this is blocked on you at this point  :)

**Comment by progwriter** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1245#-:-LBB2NEP8-aMpw9io9tt:bnfp4nl)*

**Pull request merged**
