### PR TITLE
Make BDDReachabilityAnalysis serializable

### PR DESCRIPTION
**Pull request by anothermattbrown**
Add serialization for everything contained in BDDReachabilityAnalysis, so they can be
reused across questions.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 32 of 34 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8349)* status: 32 of 38 files reviewed, 3 unresolved discussions (waiting on @anothermattbrown and @dhalperi)

___
*[`projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityAnalysis.java` line 64 at r1](https://reviewable.io/reviews/batfish/batfish/8349#-N3fYhIC7KpUMSKgJsCI:-N3fYhIC7KpUMSKgJsCJ:b-mhay9x) ([raw file](https://github.com/batfish/batfish/blob/b5645111b82e0c64e39921040cce8501e620653a/projects/batfish/src/main/java/org/batfish/bddreachability/BDDReachabilityAnalysis.java#L64)):*
> ```Java
>   private final BDD _queryHeaderSpaceBdd;
> 
>   public BDDReachabilityAnalysis(
> ```

can't tell yet why this change



_Code quote:_
```Java
ublic 
```
___
*[`projects/bdd/src/main/java/net/sf/javabdd/JFactory.java` line 104 at r1](https://reviewable.io/reviews/batfish/batfish/8349#-N3fYDCV3I5FEdLiPxCU:-N3fYDCV3I5FEdLiPxCV:bjs3uye) ([raw file](https://github.com/batfish/batfish/blob/b5645111b82e0c64e39921040cce8501e620653a/projects/bdd/src/main/java/net/sf/javabdd/JFactory.java#L104)):*
> ```Java
>     _bddReuse = new LinkedList<>();
>     quantvarset = new int[bddvarnum];
>   }
> ```

This one I'd really rather have a serialized form and a readReplace if possible. Keep the fields final, etc.
___
*[`projects/bdd/src/test/java/net/sf/javabdd/JFactoryTest.java` line 585 at r1](https://reviewable.io/reviews/batfish/batfish/8349#-N3fYWjU1LSu-N3a9D7-:-N3fYWjV52SxOa-IFvmk:b5ptl6h) ([raw file](https://github.com/batfish/batfish/blob/b5645111b82e0c64e39921040cce8501e620653a/projects/bdd/src/test/java/net/sf/javabdd/JFactoryTest.java#L585)):*
> ```Java
>     BDD bdd2 = _factory.ithVar(2);
>     BDD bdd = bdd1.xor(bdd2);
>     BDD bddClone = deepClone(bdd, bdd.getClass());
> ```

What does this do that `SerializationUtils.clone` does not?



_Code quote:_
```Java
deepClone
```

**Review by dhalperi — COMMENTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8349)* status: 34 of 38 files reviewed, 2 unresolved discussions (waiting on @anothermattbrown and @dhalperi)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 34 files at r1, 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8349)* status: all files reviewed, 2 unresolved discussions (waiting on @anothermattbrown)

**Review by anothermattbrown — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8349)* status: 37 of 39 files reviewed, 1 unresolved discussion (waiting on @anothermattbrown and @dhalperi)

___
*[`projects/bdd/src/main/java/net/sf/javabdd/JFactory.java` line 104 at r1](https://reviewable.io/reviews/batfish/batfish/8349#-N3fYDCV3I5FEdLiPxCU:-N3uIQFYAPp4AwS9M_6g:b2pcmqi) ([raw file](https://github.com/batfish/batfish/blob/b5645111b82e0c64e39921040cce8501e620653a/projects/bdd/src/main/java/net/sf/javabdd/JFactory.java#L104)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

This one I'd really rather have a serialized form and a readReplace if possible. Keep the fields final, etc.
</blockquote></details>

as discussed offline, will leave as-is for now
___
*[`projects/bdd/src/test/java/net/sf/javabdd/JFactoryTest.java` line 585 at r1](https://reviewable.io/reviews/batfish/batfish/8349#-N3fYWjU1LSu-N3a9D7-:-N3g09do8cEsoU7XA-iV:b-hfpv0l) ([raw file](https://github.com/batfish/batfish/blob/b5645111b82e0c64e39921040cce8501e620653a/projects/bdd/src/test/java/net/sf/javabdd/JFactoryTest.java#L585)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

What does this do that `SerializationUtils.clone` does not?
</blockquote></details>

removed

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8349)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8349)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown)

**Pull request merged**
