### PR TITLE
Problem with creating test rig directory on windows

### PR DESCRIPTION
**Pull request by jkhourybbn**
There is only one line change 295b28f

The previous commits were already merged

### CODE REVIEW

**Comment by dhalperi** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[a discussion](https://beta.reviewable.io/reviews/batfish/batfish/1209#-LATnSGX8J3idEgOtRbE:-LATnSGX8J3idEgOtRbF:br2631a) (no related file):*
Can you please merge master into this branch -- can not merge it otherwise

---

*[a discussion](https://beta.reviewable.io/reviews/batfish/batfish/1209#-LATr4tV2bxZ2-VO0RJc:-LATr4tV2bxZ2-VO0RJd:bsmxapr) (no related file):*
Btw -- the email you write these commits with -- `jkhoury@bbn.com` -- is not affiliated with your github account. This is fine, but it means you may miss notifications of comments on your PRs, etc. You may want to add it.

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, line 1543 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1209#-LATnV8m6ZNEESIJdZvE:-LATnV8m6ZNEESIJdZvF:b-nwbkw6) ([raw file](https://github.com/batfish/batfish/blob/295b28ff4e38b0fea7416f61cf0c67772c5ff181/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java#L1543)):*
> ```Java
>         containerDir
>             .resolve(BfConsts.RELPATH_ORIGINAL_DIR)
>             .resolve(testrigName + "_" + Instant.now().toString().replaceAll(":", "-"));
> ```

Oy, I forgot how terrible Windows is. Of course the recommended, "os-independent" functions to build paths in Java doesn't actually work, because Windows literally has no way to escape paths.

Looks good, but please replace with a `DateTimeFormatter` that takes in a human-readable format. https://stackoverflow.com/questions/25229124/format-instant-to-string

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1209)*

**Comment by jkhourybbn** [comment]
Isn't the DateTimeFormatter overkill for this? How about we totally remove the Instant() from the directory name?

**Comment by dhalperi** [comment]
No, timestamp is needed -- see https://github.com/batfish/batfish/issues/944

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1209#-:-LATwdF1-lRqQeXD3IQO:b-vmafdu)*

**Comment by jkhourybbn** [comment]
@dhalperi back to you -- updated date format and sync'd my fork

**Comment by dhalperi** [comment]
*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, line 1549 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1209#-LAUiKNs5i-q4vliHS4a:-LAUZqYb2Ktqcin-f9tp:bcimnbz) ([raw file](https://github.com/batfish/batfish/blob/eedec2f049de62341041bbd27ff36f526eb9b42d/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java#L1549)):*
> ```Java
>                     + "_"
>                     + DateTimeFormatter.ofPattern("yyyy-MM-dd-HH-mm-ss")
>                         .format(LocalDateTime.now()));
> ```

I decided not to make you deal with the new issues introduced here, see #1212.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1209)*

**Pull request closed without merging**
