### PR TITLE
XR OSPF: Better logic for determining router ID

### PR DESCRIPTION
**Pull request by corinaminer**

### CODE REVIEW

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7912)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @dhalperi and @ratulm)

___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConfiguration.java, line 1401 at r1](https://reviewable.io/reviews/batfish/batfish/7912#-Msq59mj13wsekSwNUd_:-Msq59mj13wsekSwNUda:bml050h) ([raw file](https://github.com/batfish/batfish/blob/78cffcb1c71d5523b5e1cfe52b44cdab0b4bd179/projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConfiguration.java#L1401)):*
> ```Java
>     Ip routerId = proc.getRouterId();
>     if (routerId == null) {
>       routerId = CiscoXrConversions.getHighestIp(oldConfig.getInterfaces());
> ```

fyi: this function is still used to determine EIGRP router ID, which may also need updating at some point.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7912)* status: all files reviewed, 1 unresolved discussion (waiting on @corinaminer and @ratulm)

___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConversions.java, line 249 at r1](https://reviewable.io/reviews/batfish/batfish/7912#-Msq5y_6-W_w2TYaW_hs:-Msq5y_6-W_w2TYaW_ht:b-rosdsd) ([raw file](https://github.com/batfish/batfish/blob/5124d73f92d7b18885a35d6e0810736ebb0aea2b/projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConversions.java#L249)):*
> ```Java
>     // No valid loopback interfaces. Use the first interface in the process.
>     Optional<Ip> firstProcIfaceIp =
>         // TODO Source router-id from all areas? In area ID order?
> ```

I believe @ratulm said "first interface in the config" aka first interface by name, globally.

ok for now if you don't want to change.

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7912)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConversions.java, line 249 at r1](https://reviewable.io/reviews/batfish/batfish/7912#-Msq5y_6-W_w2TYaW_hs:-MsqAuV_EjKIJZ3Kzv_f:bbq2sh8) ([raw file](https://github.com/batfish/batfish/blob/5124d73f92d7b18885a35d6e0810736ebb0aea2b/projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConversions.java#L249)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I believe @ratulm said "first interface in the config" aka first interface by name, globally.

ok for now if you don't want to change.
</blockquote></details>

I didn't check methodically about area ID order (each trial was long :() but it from what I could tell, yes, it seemed to be the order in which interfaces are listed in the configs.

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7912)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConversions.java, line 249 at r1](https://reviewable.io/reviews/batfish/batfish/7912#-Msq5y_6-W_w2TYaW_hs:-MsqBSydDfMDU6Gd_x0I:b288jm6) ([raw file](https://github.com/batfish/batfish/blob/5124d73f92d7b18885a35d6e0810736ebb0aea2b/projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConversions.java#L249)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

I didn't check methodically about area ID order (each trial was long :() but it from what I could tell, yes, it seemed to be the order in which interfaces are listed in the configs. 
</blockquote></details>

(like Dan said, OK to leave as is for now)

**Pull request merged**
