### PR TITLE
FortiOS: fix stale references / track UUIDs

### PR DESCRIPTION
**Pull request by sfraint**
This PR changes how we track renamable structure references. Instead of keeping track of object references, we now track a Batfish-specific UUID for each object, which is converted to a name at the end of extraction (when rename operations are complete).

This allows us to still rename structures without affecting references, correctly clone and replace objects (i.e. speculatively build a modified object before we know if a config block is value), avoid serializing graphs, etc.

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 4 of 7 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6709)* status: all files reviewed, 2 unresolved discussions (waiting on @corinaminer and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 703 at r2](https://reviewable.io/reviews/batfish/batfish/6709#-MVS_Le94JGO3oYnjBGp:-MVS_Le94JGO3oYnjBGq:b-1r7bhd) ([raw file](https://github.com/batfish/batfish/blob/e4c5f128b05d028d0cf3a7bdfb433fb5c34d5026/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L703)):*
> ```Java
>    * Optional#empty()} if invalid.
>    */
>   private Optional<Set<String>> toAddresses(Address_namesContext ctx) {
> ```

I strongly recommend using a hashable UUID class instead of String to avoid type confusion with object names.
As is, the toXXX functions in this PR now have inconsistent return type semantics. Please add `UUID` to the end of converters that return UUIDs.
___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosRenameableObject.java, line 3 at r2](https://reviewable.io/reviews/batfish/batfish/6709#-MVSa1Ou5vO5_j4F41Yx:-MVSa1Ou5vO5_j4F41Yy:b5fubzl) ([raw file](https://github.com/batfish/batfish/blob/e4c5f128b05d028d0cf3a7bdfb433fb5c34d5026/projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosRenameableObject.java#L3)):*
> ```Java
> package org.batfish.representation.fortios;
> 
> public interface FortiosRenameableObject {
> ```

javadoc

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6709)* status: all files reviewed, 3 unresolved discussions (waiting on @corinaminer and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6709#-MVSdWgx3eFpqXna_FWf:-MVSdWgx3eFpqXna_FWg:b253fas) (no related file):*
Repeating Dan's comment here:
> Side note: we don't need proper UUIDs for parsing, right? Even an in-memory sequence number would work?

That is, maybe just have a static counter and grab and increment when you need a new UUID.

---

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6709)* status: all files reviewed, 3 unresolved discussions (waiting on @corinaminer and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6709#-MVSdWgx3eFpqXna_FWf:-MVSdtE5-aeyeM043Xse:b-lf6zgr) (no related file):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Repeating Dan's comment here:
> Side note: we don't need proper UUIDs for parsing, right? Even an in-memory sequence number would work?

That is, maybe just have a static counter and grab and increment when you need a new UUID.
</blockquote></details>

or non-static counter, kept in extractor

---

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6709)* status: 1 of 10 files reviewed, 3 unresolved discussions (waiting on @arifogel and @corinaminer)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6709#-MVSdWgx3eFpqXna_FWf:-MVSnuBM0Apyrfh9SErN:b-7tfmjp) (no related file):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

or non-static counter, kept in extractor
</blockquote></details>

added

---
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 703 at r2](https://reviewable.io/reviews/batfish/batfish/6709#-MVS_Le94JGO3oYnjBGp:-MVSntMY95o9JJ1p85nx:b-7tfmjp) ([raw file](https://github.com/batfish/batfish/blob/e4c5f128b05d028d0cf3a7bdfb433fb5c34d5026/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L703)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

I strongly recommend using a hashable UUID class instead of String to avoid type confusion with object names.
As is, the toXXX functions in this PR now have inconsistent return type semantics. Please add `UUID` to the end of converters that return UUIDs.
</blockquote></details>

added
___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosRenameableObject.java, line 3 at r2](https://reviewable.io/reviews/batfish/batfish/6709#-MVSa1Ou5vO5_j4F41Yx:-MVSnsGTBZkmkyuR_rcO:b-7tfmjp) ([raw file](https://github.com/batfish/batfish/blob/e4c5f128b05d028d0cf3a7bdfb433fb5c34d5026/projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosRenameableObject.java#L3)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

javadoc
</blockquote></details>

added

**Review by arifogel — COMMENTED** [review]
> Reviewed 9 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6709)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

**Review by sfraint — COMMENTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6709)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

**Pull request merged**
