### PR TITLE
Vendor Configuration: support structure renaming

### PR DESCRIPTION
**Pull request by sfraint**
Add support for renaming structures (definitions and references) in `VendorConfiguration`.

### CODE REVIEW

**Review by corinaminer — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6674)* status: 1 of 2 files reviewed, 9 unresolved discussions (waiting on @arifogel, @dhalperi, and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6674#-MUlLbt-8hw6aPm9b-x9:-MUlLbt-8hw6aPm9b-xA:b-5j65jm) (no related file):*
Looks like this does not address @dhalperi's concern about definitions/references with abstract structure types. If that comes up, I imagine we'll want to update the `renameStructure` API to take in a set of types that the structure might be, and then we'll have to check all of them for rename validity (could get complicated if, for example, new name exists as an abstract type that may or may not be the same actual type).

Did we decide not to worry about this for now? If we find we need to change the API later, it shouldn't be any harder then than it would be now, right?

---
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java, line 182 at r1](https://reviewable.io/reviews/batfish/batfish/6674#-MUlDh0RDU7NiY_BY5gA:-MUlDh0SB_ZDH3I02TVj:brna6xf) ([raw file](https://github.com/batfish/batfish/blob/44b4607d73f10bd4689a8653d4b38607e86c86dc/projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java#L182)):*
> ```Java
>    * warn if not.
>    */
>   private boolean isRenameValid(StructureType type, String orgName, String newName) {
> ```

nit: is that meant to be `origName`? i keep reading as "organization name" :(
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java, line 184 at r1](https://reviewable.io/reviews/batfish/batfish/6674#-MUlEAPlCzkpHWGKVBKL:-MUlEAPlCzkpHWGKVBKM:b-n5ptpq) ([raw file](https://github.com/batfish/batfish/blob/44b4607d73f10bd4689a8653d4b38607e86c86dc/projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java#L184)):*
> ```Java
>   private boolean isRenameValid(StructureType type, String orgName, String newName) {
>     SortedMap<String, DefinedStructureInfo> defsByName =
>         _structureDefinitions.computeIfAbsent(type.getDescription(), m -> new TreeMap<>());
> ```

`computeIfAbsent` will add an entry to `_structureDefinitions` if it's not already there, which doesn't seem necessary in this function (though it probably wouldn't do any harm). i'd just use `get` and then change the first `if` condition to `defsByName == null || !defsByName.contains(orgName)`.

But, this isn't applicable if you combine this with `renameStructureDefinition`; see next comment.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java, line 201 at r1](https://reviewable.io/reviews/batfish/batfish/6674#-MUlG1d11oZmF_zRsNGa:-MUlG1d21VMyIlqsojEI:b-54wams) ([raw file](https://github.com/batfish/batfish/blob/44b4607d73f10bd4689a8653d4b38607e86c86dc/projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java#L201)):*
> ```Java
>    * called if a definition exists for the specified structure.
>    */
>   private void renameStructureDefinition(StructureType type, String orgName, String newName) {
> ```

I'd combine this with `isRenameValid` and have it return a boolean indicating whether the rename was successful. Cleaner and you don't have to rely on the caller.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java, line 204 at r1](https://reviewable.io/reviews/batfish/batfish/6674#-MUlGUgJBvHqXMIA5UAu:-MUlGUgJBvHqXMIA5UAv:b-r1iarn) ([raw file](https://github.com/batfish/batfish/blob/44b4607d73f10bd4689a8653d4b38607e86c86dc/projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java#L204)):*
> ```Java
>     SortedMap<String, DefinedStructureInfo> defsByName =
>         _structureDefinitions.computeIfAbsent(type.getDescription(), m -> new TreeMap<>());
>     DefinedStructureInfo def = defsByName.get(orgName);
> ```

simplification: you can do `defsByName.remove(orgName)` here, since `remove` returns the removed value
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java, line 214 at r1](https://reviewable.io/reviews/batfish/batfish/6674#-MUlHDrz0g-hmy7jykcf:-MUlHDrz0g-hmy7jykcg:b19896i) ([raw file](https://github.com/batfish/batfish/blob/44b4607d73f10bd4689a8653d4b38607e86c86dc/projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java#L214)):*
> ```Java
>   private void renameStructureReferences(StructureType type, String orgName, String newName) {
>     SortedMap<String, SortedMap<StructureUsage, SortedMultiset<Integer>>> refsByName =
>         _structureReferences.computeIfAbsent(type, m -> new TreeMap<>());
> ```

would recommend using `get` here and then check for null on the next line, to avoid unnecessarily modifying `_structureReferences`. Or `getOrDefault` would let you skip the null check without modifying the map.
___
*[projects/batfish-common-protocol/src/test/java/org/batfish/vendor/VendorConfigurationTest.java, line 57 at r1](https://reviewable.io/reviews/batfish/batfish/6674#-MUlIuhC1B7PAghh1d94:-MUlIuhC1B7PAghh1d95:b-zhkuav) ([raw file](https://github.com/batfish/batfish/blob/44b4607d73f10bd4689a8653d4b38607e86c86dc/projects/batfish-common-protocol/src/test/java/org/batfish/vendor/VendorConfigurationTest.java#L57)):*
> ```Java
> 
>   private final TestStructureType _testStructureType = TestStructureType.TEST_STRUCTURE_TYPE1;
>   private final TestStructureUsage _testStructureUsage = TestStructureUsage.TEST_STRUCTURE_USAGE1;
> ```

these can be static
___
*[projects/batfish-common-protocol/src/test/java/org/batfish/vendor/VendorConfigurationTest.java, line 102 at r1](https://reviewable.io/reviews/batfish/batfish/6674#-MUlJ_fEAZNhKf9wGISf:-MUlJ_fEAZNhKf9wGISg:buednjc) ([raw file](https://github.com/batfish/batfish/blob/44b4607d73f10bd4689a8653d4b38607e86c86dc/projects/batfish-common-protocol/src/test/java/org/batfish/vendor/VendorConfigurationTest.java#L102)):*
> ```Java
>       // Produce an appropriate warning
>       assertThat(
>           c.getWarnings(), hasRedFlag(hasText("Cannot rename undefined structure orgName.")));
> ```

in practice, these red flags will have config line numbers with them, right? If not, the messages should probably have a little more context, like "Cannot rename [structureType] [orgName] to [newName]: [orgName] is undefined"
___
*[projects/batfish-common-protocol/src/test/java/org/batfish/vendor/VendorConfigurationTest.java, line 149 at r1](https://reviewable.io/reviews/batfish/batfish/6674#-MUlLQ9A76R1NHH8e6Nh:-MUlLQ9A76R1NHH8e6Ni:bf05h7q) ([raw file](https://github.com/batfish/batfish/blob/44b4607d73f10bd4689a8653d4b38607e86c86dc/projects/batfish-common-protocol/src/test/java/org/batfish/vendor/VendorConfigurationTest.java#L149)):*
> ```Java
>           c.getAnswerElement(),
>           hasReferencedStructure(FILENAME, _testStructureType, newName, _testStructureUsage));
>       // Unaffected reference should persist
> ```

for completeness, should also confirm that unaffected definition persists

**Review by corinaminer — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6674)* status: all files reviewed, 9 unresolved discussions (waiting on @arifogel, @dhalperi, and @sfraint)

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6674)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @arifogel, @corinaminer, and @dhalperi)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6674#-MUlLbt-8hw6aPm9b-x9:-MUo8eyJAa6yBGVsM9ec:bvecdhj) (no related file):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Looks like this does not address @dhalperi's concern about definitions/references with abstract structure types. If that comes up, I imagine we'll want to update the `renameStructure` API to take in a set of types that the structure might be, and then we'll have to check all of them for rename validity (could get complicated if, for example, new name exists as an abstract type that may or may not be the same actual type).

Did we decide not to worry about this for now? If we find we need to change the API later, it shouldn't be any harder then than it would be now, right?
</blockquote></details>

I was originally thinking we would want to just avoid abstract references period, however I think you’re right and we do need to handle abstract types for renaming to avoid collisions between struct types that share the same namespace.

Added support for that.

---
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java, line 182 at r1](https://reviewable.io/reviews/batfish/batfish/6674#-MUlDh0RDU7NiY_BY5gA:-MUo9OTS34IOi3zTEwp3:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/44b4607d73f10bd4689a8653d4b38607e86c86dc/projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java#L182)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

nit: is that meant to be `origName`? i keep reading as "organization name" :(
</blockquote></details>

done
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java, line 184 at r1](https://reviewable.io/reviews/batfish/batfish/6674#-MUlEAPlCzkpHWGKVBKL:-MUoBBcH-e9BL33bt_rv:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/44b4607d73f10bd4689a8653d4b38607e86c86dc/projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java#L184)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

`computeIfAbsent` will add an entry to `_structureDefinitions` if it's not already there, which doesn't seem necessary in this function (though it probably wouldn't do any harm). i'd just use `get` and then change the first `if` condition to `defsByName == null || !defsByName.contains(orgName)`.

But, this isn't applicable if you combine this with `renameStructureDefinition`; see next comment.
</blockquote></details>

done
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java, line 201 at r1](https://reviewable.io/reviews/batfish/batfish/6674#-MUlG1d11oZmF_zRsNGa:-MUo9iTo0u_gQG7j0K69:b-azzi7x) ([raw file](https://github.com/batfish/batfish/blob/44b4607d73f10bd4689a8653d4b38607e86c86dc/projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java#L201)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

I'd combine this with `isRenameValid` and have it return a boolean indicating whether the rename was successful. Cleaner and you don't have to rely on the caller.
</blockquote></details>

I had considered this but I thought it would be cleaner to separate the rename and validity logic. Happy to switch it over.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java, line 204 at r1](https://reviewable.io/reviews/batfish/batfish/6674#-MUlGUgJBvHqXMIA5UAu:-MUoBVHv-DhC8-XPB8ve:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/44b4607d73f10bd4689a8653d4b38607e86c86dc/projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java#L204)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

simplification: you can do `defsByName.remove(orgName)` here, since `remove` returns the removed value
</blockquote></details>

done
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java, line 214 at r1](https://reviewable.io/reviews/batfish/batfish/6674#-MUlHDrz0g-hmy7jykcf:-MUoBl9Q8btjOyKnM-wl:bvnrpcm) ([raw file](https://github.com/batfish/batfish/blob/44b4607d73f10bd4689a8653d4b38607e86c86dc/projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java#L214)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

would recommend using `get` here and then check for null on the next line, to avoid unnecessarily modifying `_structureReferences`. Or `getOrDefault` would let you skip the null check without modifying the map.
</blockquote></details>

updated
___
*[projects/batfish-common-protocol/src/test/java/org/batfish/vendor/VendorConfigurationTest.java, line 57 at r1](https://reviewable.io/reviews/batfish/batfish/6674#-MUlIuhC1B7PAghh1d94:-MUoBtkW9rJys2v8kNwl:bvnrpcm) ([raw file](https://github.com/batfish/batfish/blob/44b4607d73f10bd4689a8653d4b38607e86c86dc/projects/batfish-common-protocol/src/test/java/org/batfish/vendor/VendorConfigurationTest.java#L57)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

these can be static
</blockquote></details>

updated
___
*[projects/batfish-common-protocol/src/test/java/org/batfish/vendor/VendorConfigurationTest.java, line 102 at r1](https://reviewable.io/reviews/batfish/batfish/6674#-MUlJ_fEAZNhKf9wGISf:-MUoDb5p1cTolxyq_SCa:b9bynpi) ([raw file](https://github.com/batfish/batfish/blob/44b4607d73f10bd4689a8653d4b38607e86c86dc/projects/batfish-common-protocol/src/test/java/org/batfish/vendor/VendorConfigurationTest.java#L102)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

in practice, these red flags will have config line numbers with them, right? If not, the messages should probably have a little more context, like "Cannot rename [structureType] [orgName] to [newName]: [orgName] is undefined"
</blockquote></details>

They won't have line numbers in them, but added a bit more context
___
*[projects/batfish-common-protocol/src/test/java/org/batfish/vendor/VendorConfigurationTest.java, line 149 at r1](https://reviewable.io/reviews/batfish/batfish/6674#-MUlLQ9A76R1NHH8e6Nh:-MUoDqP89oe4wUZ4owPs:bvnrpcm) ([raw file](https://github.com/batfish/batfish/blob/44b4607d73f10bd4689a8653d4b38607e86c86dc/projects/batfish-common-protocol/src/test/java/org/batfish/vendor/VendorConfigurationTest.java#L149)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

for completeness, should also confirm that unaffected definition persists
</blockquote></details>

updated

**Review by corinaminer — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6674)* status: all files reviewed, 3 unresolved discussions (waiting on @arifogel, @dhalperi, and @sfraint)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java, line 207 at r2](https://reviewable.io/reviews/batfish/batfish/6674#-MUon1oAEzHItKnJgFmm:-MUon1oAEzHItKnJgFmn:b-9dzly2) ([raw file](https://github.com/batfish/batfish/blob/4f56a4c9de71f947cd83e47b0496be07604db9ec/projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java#L207)):*
> ```Java
>             String.format(
>                 "Cannot rename structure %s to %s: %s is already in use.",
>                 origName, newName, newName));
> ```

i'd include `newName`'s structure type in this warning, otherwise it could be confusing if its structure type isn't the same as the structure you're trying to rename.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java, line 234 at r2](https://reviewable.io/reviews/batfish/batfish/6674#-MUooGXx2ao22H088QfD:-MUooGXx2ao22H088QfE:bsn5jg7) ([raw file](https://github.com/batfish/batfish/blob/4f56a4c9de71f947cd83e47b0496be07604db9ec/projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java#L234)):*
> ```Java
>           _structureReferences.get(type);
>       if (refsByName != null && refsByName.containsKey(orgName)) {
>         SortedMap<StructureUsage, SortedMultiset<Integer>> refs = refsByName.get(orgName);
> ```

can use `remove` instead of `get` here as well
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java, line 253 at r2](https://reviewable.io/reviews/batfish/batfish/6674#-MUood_D0mErk3A1yh-K:-MUood_D0mErk3A1yh-L:b-7dett7) ([raw file](https://github.com/batfish/batfish/blob/4f56a4c9de71f947cd83e47b0496be07604db9ec/projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java#L253)):*
> ```Java
>   public boolean renameStructure(String origName, String newName, Collection<StructureType> types) {
>     boolean valid = renameStructureDefinition(origName, newName, types);
>     renameStructureReferences(origName, newName, types);
> ```

shouldn't rename references if `renameStructureDefinition` failed

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6674)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @arifogel, @corinaminer, and @dhalperi)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java, line 207 at r2](https://reviewable.io/reviews/batfish/batfish/6674#-MUon1oAEzHItKnJgFmm:-MUosA5374t7ArszEDbM:b-aweool) ([raw file](https://github.com/batfish/batfish/blob/4f56a4c9de71f947cd83e47b0496be07604db9ec/projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java#L207)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

i'd include `newName`'s structure type in this warning, otherwise it could be confusing if its structure type isn't the same as the structure you're trying to rename.
</blockquote></details>

how do the updated warnings look?
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java, line 234 at r2](https://reviewable.io/reviews/batfish/batfish/6674#-MUooGXx2ao22H088QfD:-MUosauP6EJtmpiB_erz:bvnrpcm) ([raw file](https://github.com/batfish/batfish/blob/4f56a4c9de71f947cd83e47b0496be07604db9ec/projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java#L234)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

can use `remove` instead of `get` here as well
</blockquote></details>

updated
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java, line 253 at r2](https://reviewable.io/reviews/batfish/batfish/6674#-MUood_D0mErk3A1yh-K:-MUos_fV9iNJh4IGxMd_:bvnrpcm) ([raw file](https://github.com/batfish/batfish/blob/4f56a4c9de71f947cd83e47b0496be07604db9ec/projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java#L253)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

shouldn't rename references if `renameStructureDefinition` failed
</blockquote></details>

updated

**Review by corinaminer — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6674)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel, @dhalperi, and @sfraint)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java, line 207 at r2](https://reviewable.io/reviews/batfish/batfish/6674#-MUon1oAEzHItKnJgFmm:-MUouTBJAvZp44XH0kmW:bks4lpa) ([raw file](https://github.com/batfish/batfish/blob/4f56a4c9de71f947cd83e47b0496be07604db9ec/projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java#L207)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

how do the updated warnings look?
</blockquote></details>

:lgtm: :)
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java, line 201 at r3](https://reviewable.io/reviews/batfish/batfish/6674#-MUouY5c0p_9foGbD-96:-MUouY5c0p_9foGbD-97:b-g0nv9l) ([raw file](https://github.com/batfish/batfish/blob/1dbe9f4357b920534a0981e045e6dee74d21e6e7/projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java#L201)):*
> ```Java
>     }
> 
>     for (StructureType otherType : sameNamespaceTypes) {
> ```

is there an assumption that `sameNamespaceTypes` will contain `type`? That's ok by me but should be documented and maybe asserted at the beginning of `renameStructure`. Alternatively you could make
`ImmutableSet.builder.addAll(sameNamespaceTypes).add(type).build()`
and iterate through that.

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6674)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @arifogel, @corinaminer, and @dhalperi)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java, line 201 at r3](https://reviewable.io/reviews/batfish/batfish/6674#-MUouY5c0p_9foGbD-96:-MUoyZ2W3NS0kfwLSxOn:bccakzk) ([raw file](https://github.com/batfish/batfish/blob/1dbe9f4357b920534a0981e045e6dee74d21e6e7/projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java#L201)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

is there an assumption that `sameNamespaceTypes` will contain `type`? That's ok by me but should be documented and maybe asserted at the beginning of `renameStructure`. Alternatively you could make
`ImmutableSet.builder.addAll(sameNamespaceTypes).add(type).build()`
and iterate through that.
</blockquote></details>

added an assertion and updated the docstring

**Review by corinaminer — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6674)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel, @dhalperi, and @sfraint)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java, line 240 at r4](https://reviewable.io/reviews/batfish/batfish/6674#-MUozMp00lGK_J69EEqX:-MUozMp00lGK_J69EEqY:b-mjorlo) ([raw file](https://github.com/batfish/batfish/blob/6bd94a06ed38a2ddd8487f9a6af26d94342be9e0/projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java#L240)):*
> ```Java
>    * <p>The specified {@link Collection} of {@link StructureType} should contain all structure types
>    * that share the same namespace (including the specified structure {@code type}); i.e. a rename
>    * will only succeed if a defined structure exists for one of the specified types and the new name
> ```

last nit: the defined structure has to exist for type `type`. Could simplify to "A rename will only succeed if the new name is not already in use by any structures of the specified types"

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6674)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @arifogel, @corinaminer, and @dhalperi)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java, line 240 at r4](https://reviewable.io/reviews/batfish/batfish/6674#-MUozMp00lGK_J69EEqX:-MUp-YKiE6uUx3TbgvYO:bvnrpcm) ([raw file](https://github.com/batfish/batfish/blob/6bd94a06ed38a2ddd8487f9a6af26d94342be9e0/projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java#L240)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

last nit: the defined structure has to exist for type `type`. Could simplify to "A rename will only succeed if the new name is not already in use by any structures of the specified types"
</blockquote></details>

updated

**Review by corinaminer — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6674#-:-MUp0tjg03wSqWZAjQ2l:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel and @dhalperi)

**Pull request merged**
