### PR TITLE
IS-IS data plane implementation

### PR DESCRIPTION
**Pull request by arifogel**
Co-authored-by: Ari Fogel <ari@fogelti.me>                                      
Co-authored-by: Victor Heorhiadi <progwriter@users.noreply.github.com>

- L1 routes
- L2 routes
- propagation of L1 into L2
- L1L2 default routes
- not implemented:
  - Leaking L2 into L1
  - Redistribution
  - Honoring of custom metrics

### CODE REVIEW

**Comment by progwriter** [comment]
Reviewed 20 of 28 files at r1, 1 of 4 files at r3, 2 of 6 files at r6, 5 of 5 files at r7, 2 of 2 files at r8, 2 of 4 files at r9.
Review status: 30 of 32 files reviewed, 1 unresolved discussion (waiting on @progwriter, @arifogel, and @dhalperi)

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IsoAddress.java, line 77 at r8](https://reviewable.io/reviews/batfish/batfish/1734#-LFdbzAo0DGRPgbw-Ygi:-LFdbzAp9k21m9PYJqw7:b-fo190l) ([raw file](https://github.com/batfish/batfish/blob/3cb42d171e86853396e45ec589cd33ff4f29a864/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IsoAddress.java#L77)):*
> ```Java
>   /**
>    * Create an ISO address from hexadecimal digits, optionally interspersed with period (.)
>    * characters that are ignored. See {@link IsoAddres} documentation for canonical text format.
> ```

typo in  link `IsoAddress`

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1734)*

**Comment by arifogel** [comment]
Review status: 29 of 32 files reviewed, 1 unresolved discussion (waiting on @progwriter, @arifogel, and @dhalperi)

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IsoAddress.java, line 77 at r8](https://reviewable.io/reviews/batfish/batfish/1734#-LFdbzAo0DGRPgbw-Ygi:-LFdkxyN0xogrXWDvu0H:b-7ql1td) ([raw file](https://github.com/batfish/batfish/blob/3cb42d171e86853396e45ec589cd33ff4f29a864/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IsoAddress.java#L77)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

typo in  link `IsoAddress`
</blockquote></details>

fixed

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1734)*

**Comment by progwriter** [comment]
Review status: 18 of 34 files reviewed, all discussions resolved (waiting on @progwriter and @dhalperi)

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1734#-LFiQaEUENjrvMcvc3Q6:-LFiQaEUENjrvMcvc3Q7:b4lb7t9) (no related file):*
@dhalperi:
I believe @arifogel and I agree on the logic/functionality/tests even though we know there is room for improvement. 
When you get a chance, please skim for anything blatantly wrong, as you're the only true outside reviewer.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1734)*

**Comment by dhalperi** [comment]
Reviewed 12 of 28 files at r1, 1 of 4 files at r3, 1 of 6 files at r6, 3 of 5 files at r7, 1 of 2 files at r8, 2 of 4 files at r9, 2 of 3 files at r10, 10 of 10 files at r11, 2 of 2 files at r12.
Review status: all files reviewed, 17 unresolved discussions (waiting on @arifogel)

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1734#-LFiQaEUENjrvMcvc3Q6:-LFiqb_H9sFiGlYMXFTr:b-n7h3wz) (no related file):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

@dhalperi:
I believe @arifogel and I agree on the logic/functionality/tests even though we know there is room for improvement. 
When you get a chance, please skim for anything blatantly wrong, as you're the only true outside reviewer.
</blockquote></details>

Took a skim. Lots of little comments, most are optional. Use your own discretion.

1 legit q about a 1/2 bug and identified a few opportunities for abstract code/readability/comment improvements I think :p

---

*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java, line 157 at r12](https://reviewable.io/reviews/batfish/batfish/1734#-LFihK18Bt82ZCK44YTC:-LFihK18Bt82ZCK44YTD:bqig4xm) ([raw file](https://github.com/batfish/batfish/blob/6e1dfe221075c22c5e4f875a01604e628bbcbf73/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java#L157)):*
> ```Java
>             .stream()
>             .map(edge -> IsisEdge.newEdge(edge, configurations))
>             .filter(Objects::nonNull)
> ```

I wouldn't have expected a function called `newEdge` to be able to return null. But I can guess why this happens.

No action needed, unless you think there's a better name for it.

---

*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java, line 256 at r12](https://reviewable.io/reviews/batfish/batfish/1734#-LFihlQD8fmj729oDEgC:-LFihlQD8fmj729oDEgD:b-6pzx0u) ([raw file](https://github.com/batfish/batfish/blob/6e1dfe221075c22c5e4f875a01604e628bbcbf73/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java#L256)):*
> ```Java
>         .forEach(
>             n -> {
>               for (VirtualRouter vr : n.getVirtualRouters().values()) {
> ```

is it important that the VRs for a Node be processed serially?
- If so, please comment to that effect
- If not, consider a flatmap.parallelstream to keep the parallelism going?  (actually, I don't know if this is how parallel streams actually work, so look it up if you care).

(same below).

---

*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java, line 229 at r12](https://reviewable.io/reviews/batfish/batfish/1734#-LFiiKnD5WnkZvuXuLtN:-LFiiKnD5WnkZvuXuLtO:bpf97yv) ([raw file](https://github.com/batfish/batfish/blob/6e1dfe221075c22c5e4f875a01604e628bbcbf73/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java#L229)):*
> ```
> level-1
> ```
level-2?

---

*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java, line 1085 at r12](https://reviewable.io/reviews/batfish/batfish/1734#-LFilBLEE0PMHsQvgZN-:-LFilBLEE0PMHsQvgZN0:b-nn382i) ([raw file](https://github.com/batfish/batfish/blob/6e1dfe221075c22c5e4f875a01604e628bbcbf73/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java#L1085)):*
> ```Java
>         .values()
>         .forEach(
>             iface -> {
> ```

in general, if a function is mainly a for loop around a lot of code, I try to take what's inside the for loop into its own function. Often easier to read and reason about both -- for the inner code, it's clear what's passed in or inherited from outside/previous iterations, for the outer code it's clear that "oh, this is really just doing foo to all the vrfs".

---

*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java, line 1090 at r12](https://reviewable.io/reviews/batfish/batfish/1734#-LFiktXY6f9qPoJF2Ody:-LFiktXY6f9qPoJF2Odz:b-ozo8ih) ([raw file](https://github.com/batfish/batfish/blob/6e1dfe221075c22c5e4f875a01604e628bbcbf73/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java#L1090)):*
> ```Java
>                 return;
>               }
>               IsisInterfaceLevelSettings ifaceL1Settings = ifaceSettings.getLevel1();
> ```

it looks like l1 and l2 are treated exactly the same. is there any refactoring that can be done to reduce common code?

---

*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java, line 1701 at r12](https://reviewable.io/reviews/batfish/batfish/1734#-LFilm7aAceJhasbPWgN:-LFilm7aAceJhasbPWgO:b-7oyqka) ([raw file](https://github.com/batfish/batfish/blob/6e1dfe221075c22c5e4f875a01604e628bbcbf73/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java#L1701)):*
> ```
> TODO: simplify
> ```

I guess this is the comment I made earlier about common L1/L2 code? Still optional, consider doing.

---

*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java, line 2479 at r12](https://reviewable.io/reviews/batfish/batfish/1734#-LFimHWd0mCki6Uas86D:-LFimHWd0mCki6Uas86E:b-nnit9g) ([raw file](https://github.com/batfish/batfish/blob/6e1dfe221075c22c5e4f875a01604e628bbcbf73/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java#L2479)):*
> ```Java
>   }
> 
>   boolean unstageIsisRoutes(
> ```

document. esp return value significance.

---

*[projects/batfish/src/main/java/org/batfish/dataplane/protocols/IsisProtocolHelper.java, line 13 at r12](https://reviewable.io/reviews/batfish/batfish/1734#-LFimSaH8ez29IWgp5Up:-LFimSaI5yZQ0QJmzfvO:b40jdg2) ([raw file](https://github.com/batfish/batfish/blob/6e1dfe221075c22c5e4f875a01604e628bbcbf73/projects/batfish/src/main/java/org/batfish/dataplane/protocols/IsisProtocolHelper.java#L13)):*
> ```
> protcol
> ```

typo: protocol.

---

*[projects/batfish/src/main/java/org/batfish/dataplane/rib/IsisRib.java, line 13 at r12](https://reviewable.io/reviews/batfish/batfish/1734#-LFin3t200U4_-WuQv8F:-LFin3t200U4_-WuQv8G:bb95dzb) ([raw file](https://github.com/batfish/batfish/blob/6e1dfe221075c22c5e4f875a01604e628bbcbf73/projects/batfish/src/main/java/org/batfish/dataplane/rib/IsisRib.java#L13)):*
> ```
> // Lower value is more preferred.
> ```

How is this relevant here? Looks to me like there's no preference -- we're just using a switch statement.

---

*[projects/batfish/src/main/java/org/batfish/dataplane/topology/IsisEdge.java, line 48 at r12](https://reviewable.io/reviews/batfish/batfish/1734#-LFinHU69GOZDMHpqTT6:-LFinHU69GOZDMHpqTT7:b-r6oafa) ([raw file](https://github.com/batfish/batfish/blob/6e1dfe221075c22c5e4f875a01604e628bbcbf73/projects/batfish/src/main/java/org/batfish/dataplane/topology/IsisEdge.java#L48)):*
> ```
> static @Nullable public
> ```

Do we really not get a modifier error here? I wonder if annotations mess it up.

(I think it's always supposed to be `public static`, not `static public`... and I'd put `@Nullable` first in all likelihood. If any tool diagrees with me, of course, ignore.)

---

*[projects/batfish/src/main/java/org/batfish/dataplane/topology/IsisEdge.java, line 50 at r12](https://reviewable.io/reviews/batfish/batfish/1734#-LFinWVh5Gulyo7nf9Kl:-LFinWVh5Gulyo7nf9Km:byk9qbn) ([raw file](https://github.com/batfish/batfish/blob/6e1dfe221075c22c5e4f875a01604e628bbcbf73/projects/batfish/src/main/java/org/batfish/dataplane/topology/IsisEdge.java#L50)):*
> ```Java
>   static @Nullable public IsisEdge newEdge(Edge edge, Map<String, Configuration> configurations) {
>     // vertex1
>     Configuration c1 = configurations.get(edge.getNode1());
> ```

readability q: are the c1 and c2 semantically different (source/destination) or just an arbitrarily-ordered pair?

In former case, might(and only might) be clearer to name them by semantics instead of just 1/2.

---

*[projects/batfish/src/main/java/org/batfish/dataplane/topology/IsisEdge.java, line 90 at r12](https://reviewable.io/reviews/batfish/batfish/1734#-LFintYS65iMMNBHJlQO:-LFintYS65iMMNBHJlQP:bbbnt2q) ([raw file](https://github.com/batfish/batfish/blob/6e1dfe221075c22c5e4f875a01604e628bbcbf73/projects/batfish/src/main/java/org/batfish/dataplane/topology/IsisEdge.java#L90)):*
> ```
> LEVEL_1)
> ```

Hard for me to jive this with above comment (only level 2 is allowed) but this could be a function of not understanding the code. Is this a 1/2 bug?

---

*[projects/batfish/src/main/java/org/batfish/dataplane/topology/IsisEdge.java, line 107 at r12](https://reviewable.io/reviews/batfish/batfish/1734#-LFioemK1Xnhbr25wxon:-LFioemK1Xnhbr25wxoo:b-t1dndz) ([raw file](https://github.com/batfish/batfish/blob/6e1dfe221075c22c5e4f875a01604e628bbcbf73/projects/batfish/src/main/java/org/batfish/dataplane/topology/IsisEdge.java#L107)):*
> ```Java
>   }
> 
>   private static @Nullable IsisLevel union(@Nullable IsisLevel level1, @Nullable IsisLevel level2) {
> ```

intersection and union are probably bad names for these - i get the gist, but there's something else happening, I think. What's really going on here? Consider adding docs.

---

*[projects/batfish/src/main/java/org/batfish/dataplane/topology/IsisEdge.java, line 152 at r12](https://reviewable.io/reviews/batfish/batfish/1734#-LFioznTCU_wtyO5DVTI:-LFioznTCU_wtyO5DVTJ:b-9z6pmu) ([raw file](https://github.com/batfish/batfish/blob/6e1dfe221075c22c5e4f875a01604e628bbcbf73/projects/batfish/src/main/java/org/batfish/dataplane/topology/IsisEdge.java#L152)):*
> ```
> o == null || getClass() != o.getClass()
> ```

`!(o instanceof IsisEdge)` is more concise and efficient, I think.

(Handles null, plus instanceof is just as as strong as class equality since class is final)

else ifs make this function more concise.

---

*[projects/batfish/src/main/java/org/batfish/dataplane/topology/IsisNode.java, line 14 at r12](https://reviewable.io/reviews/batfish/batfish/1734#-LFipHUX0yKc2NZ_Toeh:-LFipHUX0yKc2NZ_Toei:b-qsyuya) ([raw file](https://github.com/batfish/batfish/blob/6e1dfe221075c22c5e4f875a01604e628bbcbf73/projects/batfish/src/main/java/org/batfish/dataplane/topology/IsisNode.java#L14)):*
> ```Java
> import org.batfish.dataplane.ibdp.Node;
> 
> public class IsisNode implements Comparable<IsisNode> {
> ```

final?

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/Interface.java, line 135 at r12](https://reviewable.io/reviews/batfish/batfish/1734#-LFiprEn7frrJeNt1qT_:-LFiprEn7frrJeNt1qTa:b-fj9qbn) ([raw file](https://github.com/batfish/batfish/blob/6e1dfe221075c22c5e4f875a01604e628bbcbf73/projects/batfish/src/main/java/org/batfish/representation/cisco/Interface.java#L135)):*
> ```Java
>   private int _incomingFilterLine;
> 
>   private Long _isisCost;
> ```

add @Nullable to all these?

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/IsisInterfaceLevelSettings.java, line 21 at r12](https://reviewable.io/reviews/batfish/batfish/1734#-LFipuxP5AaV1pNPAf_5:-LFipuxP5AaV1pNPAf_6:b-fj9qbn) ([raw file](https://github.com/batfish/batfish/blob/6e1dfe221075c22c5e4f875a01604e628bbcbf73/projects/batfish/src/main/java/org/batfish/representation/juniper/IsisInterfaceLevelSettings.java#L21)):*
> ```Java
>   private Integer _holdTime;
> 
>   private Long _metric;
> ```

add @Nullable to all these?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1734)*

**Comment by progwriter** [comment]
Review status: 23 of 36 files reviewed, 6 unresolved discussions (waiting on @dhalperi, @progwriter, and @arifogel)

---

*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java, line 256 at r12](https://reviewable.io/reviews/batfish/batfish/1734#-LFihlQD8fmj729oDEgC:-LFjCGHr20le6bXckiQy:b-kidqza) ([raw file](https://github.com/batfish/batfish/blob/6e1dfe221075c22c5e4f875a01604e628bbcbf73/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java#L256)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

is it important that the VRs for a Node be processed serially?
- If so, please comment to that effect
- If not, consider a flatmap.parallelstream to keep the parallelism going?  (actually, I don't know if this is how parallel streams actually work, so look it up if you care).

(same below).
</blockquote></details>

Done. Can definitely simplify here, and the batch is not really needed either (should be a quick operation). Below, not so clear cut, needs more thinking.

---

*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java, line 229 at r12](https://reviewable.io/reviews/batfish/batfish/1734#-LFiiKnD5WnkZvuXuLtN:-LFjCIin039qFzz-Oetj:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/6e1dfe221075c22c5e4f875a01604e628bbcbf73/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java#L229)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> level-1
> ```
level-2?
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java, line 1085 at r12](https://reviewable.io/reviews/batfish/batfish/1734#-LFilBLEE0PMHsQvgZN-:-LFjB6sH08h7kPsxqqCI:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/6e1dfe221075c22c5e4f875a01604e628bbcbf73/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java#L1085)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

in general, if a function is mainly a for loop around a lot of code, I try to take what's inside the for loop into its own function. Often easier to read and reason about both -- for the inner code, it's clear what's passed in or inherited from outside/previous iterations, for the outer code it's clear that "oh, this is really just doing foo to all the vrfs".
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java, line 1090 at r12](https://reviewable.io/reviews/batfish/batfish/1734#-LFiktXY6f9qPoJF2Ody:-LFjB7aLCkUY8HSZCPPH:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/6e1dfe221075c22c5e4f875a01604e628bbcbf73/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java#L1090)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

it looks like l1 and l2 are treated exactly the same. is there any refactoring that can be done to reduce common code?
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java, line 1701 at r12](https://reviewable.io/reviews/batfish/batfish/1734#-LFilm7aAceJhasbPWgN:-LFjB9TuEPLJLHvY5rGZ:bu11s4) ([raw file](https://github.com/batfish/batfish/blob/6e1dfe221075c22c5e4f875a01604e628bbcbf73/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java#L1701)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> TODO: simplify
> ```

I guess this is the comment I made earlier about common L1/L2 code? Still optional, consider doing.
</blockquote></details>

Deferring, as mostly unhappy with Optionals/code that converts routes from L1 to L2 (it was written in a hurry).

---

*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java, line 2479 at r12](https://reviewable.io/reviews/batfish/batfish/1734#-LFimHWd0mCki6Uas86D:-LFj7iPM3vD3V-P17VHU:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/6e1dfe221075c22c5e4f875a01604e628bbcbf73/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java#L2479)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

document. esp return value significance.
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/dataplane/protocols/IsisProtocolHelper.java, line 13 at r12](https://reviewable.io/reviews/batfish/batfish/1734#-LFimSaH8ez29IWgp5Up:-LFizImjAssY5Vaooc2o:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/6e1dfe221075c22c5e4f875a01604e628bbcbf73/projects/batfish/src/main/java/org/batfish/dataplane/protocols/IsisProtocolHelper.java#L13)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> protcol
> ```

typo: protocol.
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/dataplane/rib/IsisRib.java, line 13 at r12](https://reviewable.io/reviews/batfish/batfish/1734#-LFin3t200U4_-WuQv8F:-LFj3NFK5tqr1rTxllqe:b-ty3ef4) ([raw file](https://github.com/batfish/batfish/blob/6e1dfe221075c22c5e4f875a01604e628bbcbf73/projects/batfish/src/main/java/org/batfish/dataplane/rib/IsisRib.java#L13)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> // Lower value is more preferred.
> ```

How is this relevant here? Looks to me like there's no preference -- we're just using a switch statement.
</blockquote></details>

Took a guess at what @arifogel meant. He can correct me.

---

*[projects/batfish/src/main/java/org/batfish/dataplane/topology/IsisEdge.java, line 48 at r12](https://reviewable.io/reviews/batfish/batfish/1734#-LFinHU69GOZDMHpqTT6:-LFj0MGBBSYuMCWCUb_n:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/6e1dfe221075c22c5e4f875a01604e628bbcbf73/projects/batfish/src/main/java/org/batfish/dataplane/topology/IsisEdge.java#L48)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> static @Nullable public
> ```

Do we really not get a modifier error here? I wonder if annotations mess it up.

(I think it's always supposed to be `public static`, not `static public`... and I'd put `@Nullable` first in all likelihood. If any tool diagrees with me, of course, ignore.)
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/dataplane/topology/IsisEdge.java, line 50 at r12](https://reviewable.io/reviews/batfish/batfish/1734#-LFinWVh5Gulyo7nf9Kl:-LFj-NDF78C4bqF4IllF:bnxfjyw) ([raw file](https://github.com/batfish/batfish/blob/6e1dfe221075c22c5e4f875a01604e628bbcbf73/projects/batfish/src/main/java/org/batfish/dataplane/topology/IsisEdge.java#L50)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

readability q: are the c1 and c2 semantically different (source/destination) or just an arbitrarily-ordered pair?

In former case, might(and only might) be clearer to name them by semantics instead of just 1/2.
</blockquote></details>

@arifogel and I had this discussion (about the more general, pervasive pattern of 1/2 naming, e.g. see the edge getters). Decided to defer until we establish where directionality makes sense and settle on terminology (e.g., src/dst, head/tail).

---

*[projects/batfish/src/main/java/org/batfish/dataplane/topology/IsisEdge.java, line 152 at r12](https://reviewable.io/reviews/batfish/batfish/1734#-LFioznTCU_wtyO5DVTI:-LFj0UGT4G1v9sLPs0xs:bkh8zec) ([raw file](https://github.com/batfish/batfish/blob/6e1dfe221075c22c5e4f875a01604e628bbcbf73/projects/batfish/src/main/java/org/batfish/dataplane/topology/IsisEdge.java#L152)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> o == null || getClass() != o.getClass()
> ```

`!(o instanceof IsisEdge)` is more concise and efficient, I think.

(Handles null, plus instanceof is just as as strong as class equality since class is final)

else ifs make this function more concise.
</blockquote></details>

Done. Agree, this was probably Eclipse autogenerated code though :P 

---

*[projects/batfish/src/main/java/org/batfish/dataplane/topology/IsisNode.java, line 14 at r12](https://reviewable.io/reviews/batfish/batfish/1734#-LFipHUX0yKc2NZ_Toeh:-LFj2Q0XBdAuVYPtPXzM:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/6e1dfe221075c22c5e4f875a01604e628bbcbf73/projects/batfish/src/main/java/org/batfish/dataplane/topology/IsisNode.java#L14)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

final?
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/Interface.java, line 135 at r12](https://reviewable.io/reviews/batfish/batfish/1734#-LFiprEn7frrJeNt1qT_:-LFj2Msz2ib1meK-TVy8:bbz1jb) ([raw file](https://github.com/batfish/batfish/blob/6e1dfe221075c22c5e4f875a01604e628bbcbf73/projects/batfish/src/main/java/org/batfish/representation/cisco/Interface.java#L135)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

add @Nullable to all these?
</blockquote></details>

Done. for isis fields at least.

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/IsisInterfaceLevelSettings.java, line 21 at r12](https://reviewable.io/reviews/batfish/batfish/1734#-LFipuxP5AaV1pNPAf_5:-LFj2Kie0OflHA5_CnGT:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/6e1dfe221075c22c5e4f875a01604e628bbcbf73/projects/batfish/src/main/java/org/batfish/representation/juniper/IsisInterfaceLevelSettings.java#L21)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

add @Nullable to all these?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1734)*

**Comment by arifogel** [comment]
Review status: 23 of 36 files reviewed, 4 unresolved discussions (waiting on @dhalperi, @progwriter, and @arifogel)

---

*[projects/batfish/src/main/java/org/batfish/dataplane/rib/IsisRib.java, line 13 at r12](https://reviewable.io/reviews/batfish/batfish/1734#-LFin3t200U4_-WuQv8F:-LFn81t54zG11iPfWQsk:b8odqss) ([raw file](https://github.com/batfish/batfish/blob/6e1dfe221075c22c5e4f875a01604e628bbcbf73/projects/batfish/src/main/java/org/batfish/dataplane/rib/IsisRib.java#L13)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

Took a guess at what @arifogel meant. He can correct me.
</blockquote></details>

This is just hackery. L1 is preferred over L2. This cost function provides an integer mapping for levels so they can be used by a comparator.

---

*[projects/batfish/src/main/java/org/batfish/dataplane/topology/IsisEdge.java, line 90 at r12](https://reviewable.io/reviews/batfish/batfish/1734#-LFintYS65iMMNBHJlQO:-LFn8VjiBvvE2KZ471DW:b-xg3o8i) ([raw file](https://github.com/batfish/batfish/blob/6e1dfe221075c22c5e4f875a01604e628bbcbf73/projects/batfish/src/main/java/org/batfish/dataplane/topology/IsisEdge.java#L90)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> LEVEL_1)
> ```

Hard for me to jive this with above comment (only level 2 is allowed) but this could be a function of not understanding the code. Is this a 1/2 bug?
</blockquote></details>

Level 1 connection is only allowed if same area. So this last line has a bug. The false case should be `LEVEL_2`.
Fixed.

---

*[projects/batfish/src/main/java/org/batfish/dataplane/topology/IsisEdge.java, line 152 at r12](https://reviewable.io/reviews/batfish/batfish/1734#-LFioznTCU_wtyO5DVTI:-LFn93g52luqffVTah1a:bmhn7d3) ([raw file](https://github.com/batfish/batfish/blob/6e1dfe221075c22c5e4f875a01604e628bbcbf73/projects/batfish/src/main/java/org/batfish/dataplane/topology/IsisEdge.java#L152)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

Done. Agree, this was probably Eclipse autogenerated code though :P 
</blockquote></details>

No actually there used to be subclasses here, and I did want exact class to match. The subclasses were removed, so @dhalperi's suggestion should be applied, as @progwriter has done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1734)*

**Comment by arifogel** [comment]
Review status: 23 of 36 files reviewed, 4 unresolved discussions (waiting on @dhalperi, @progwriter, and @arifogel)

---

*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java, line 157 at r12](https://reviewable.io/reviews/batfish/batfish/1734#-LFihK18Bt82ZCK44YTC:-LFrr8Jt8N_kDh8gY2BV:bs7xkmj) ([raw file](https://github.com/batfish/batfish/blob/6e1dfe221075c22c5e4f875a01604e628bbcbf73/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java#L157)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I wouldn't have expected a function called `newEdge` to be able to return null. But I can guess why this happens.

No action needed, unless you think there's a better name for it.
</blockquote></details>

rejiggered.

---

*[projects/batfish/src/main/java/org/batfish/dataplane/topology/IsisEdge.java, line 107 at r12](https://reviewable.io/reviews/batfish/batfish/1734#-LFioemK1Xnhbr25wxon:-LFroyqu-loisDHbtb0_:bxj564d) ([raw file](https://github.com/batfish/batfish/blob/6e1dfe221075c22c5e4f875a01604e628bbcbf73/projects/batfish/src/main/java/org/batfish/dataplane/topology/IsisEdge.java#L107)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

intersection and union are probably bad names for these - i get the gist, but there's something else happening, I think. What's really going on here? Consider adding docs.
</blockquote></details>

deferring

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1734)*

**Comment by dhalperi** [comment]
Reviewed 11 of 13 files at r13, 2 of 2 files at r14.
Review status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi)

---

*[projects/batfish/src/main/java/org/batfish/dataplane/topology/IsisEdge.java, line 90 at r12](https://reviewable.io/reviews/batfish/batfish/1734#-LFintYS65iMMNBHJlQO:-LFrsYDuDWs5XkvWAiVp:bkhvx69) ([raw file](https://github.com/batfish/batfish/blob/6e1dfe221075c22c5e4f875a01604e628bbcbf73/projects/batfish/src/main/java/org/batfish/dataplane/topology/IsisEdge.java#L90)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Level 1 connection is only allowed if same area. So this last line has a bug. The false case should be `LEVEL_2`.
Fixed.
</blockquote></details>

Please add a new test case that would have caught this.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1734)*

**Comment by arifogel** [comment]
Review status: 34 of 39 files reviewed, all discussions resolved (waiting on @dhalperi and @progwriter)

---

*[projects/batfish/src/main/java/org/batfish/dataplane/topology/IsisEdge.java, line 90 at r12](https://reviewable.io/reviews/batfish/batfish/1734#-LFintYS65iMMNBHJlQO:-LFsEoR-C4XhbmqoDhRG:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/6e1dfe221075c22c5e4f875a01604e628bbcbf73/projects/batfish/src/main/java/org/batfish/dataplane/topology/IsisEdge.java#L90)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Please add a new test case that would have caught this.
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1734)*

**Comment by dhalperi** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r15.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1734#-:-LFsFIml1DEi7UlurwLD:bnfp4nl)*

**Comment by dhalperi** [comment]
Reviewed 1 of 1 files at r16.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1734)*

**Pull request merged**
