### PR TITLE
Ensure that not specifying a default iptables rule doesn't crash

### PR DESCRIPTION
**Pull request by dspicuzzbbn**
- Tests issue #252

### CODE REVIEW

**Comment by dhalperi** [comment]
I think your previous comment was correct: removing the `FORWARD` rule is not a good test because `FORWARD` isn't used anywhere else. We should probably remove `INPUT` instead, since that's referred to by following lines.

**Comment by dspicuzzbbn** [comment]
Hm, travis didn't send me a failure notification, I'll have to fix that.

I think for testing the crash issue, removing FORWARD is sufficient -- I wasn't running the tests that are being ran on travis (but I had assumed that the tests would be ran when I did a maven build). I have to catch a flight, but I'll fix the test crash later.

**Comment by dspicuzzbbn** [comment]
Tests updated, I think it should pass now.

**Comment by dhalperi** [comment]
Thanks!

**Pull request merged**
