### PR TITLE
XR: support removing `aggregate-address`

### PR DESCRIPTION
**Pull request by sfraint**
Support the `no` variety of `aggregate-address` statements under `router bgp`

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8269)* status: all files reviewed, 3 unresolved discussions (waiting on @dhalperi and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java, line 3046 at r1](https://reviewable.io/reviews/batfish/batfish/8269#-N0bQPYXAMSDmFt589Bk:-N0bQPYXAMSDmFt589Bl:b-i6wuvu) ([raw file](https://github.com/batfish/batfish/blob/8062b3dfe18c20a83e4cce20d68e8e79cb8a5de2/projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java#L3046)):*
> ```Java
>         || _currentDynamicIpv6PeerGroup != null
>         || _currentNamedPeerGroup != null) {
>       throw new BatfishException("unexpected occurrence in peer group/neighbor context");
> ```

You changed one of these to a warning. Possible to do so here?
___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java, line 3050 at r1](https://reviewable.io/reviews/batfish/batfish/8269#-N0bQ2jgAVx8GLXQe6pI:-N0bQ2jgAVx8GLXQe6pJ:b-w94w3q) ([raw file](https://github.com/batfish/batfish/blob/8062b3dfe18c20a83e4cce20d68e8e79cb8a5de2/projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java#L3050)):*
> ```Java
>   }
> 
>   private Optional<Prefix> toPrefix(CiscoXrParser.Aggregate_address_prefixContext ctx) {
> ```

nit: nonnull
___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java, line 3057 at r1](https://reviewable.io/reviews/batfish/batfish/8269#-N0bQDzFDofK3dSc_sFR:-N0bQDzFDofK3dSc_sFS:b-nzws5n) ([raw file](https://github.com/batfish/batfish/blob/8062b3dfe18c20a83e4cce20d68e8e79cb8a5de2/projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java#L3057)):*
> ```Java
>       return Optional.of(Prefix.create(network, prefixLength));
>     } else if (ctx.prefix != null) {
>       return Optional.of(Prefix.parse(ctx.prefix.getText()));
> ```

Isn't there a `toPrefix(PrefixContext ctx)`? If not, please add one and use it. Same for v6.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8269)* status: all files reviewed, 4 unresolved discussions (waiting on @dhalperi and @sfraint)

___
*[`projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_bgp.g4` line 934 at r1](https://reviewable.io/reviews/batfish/batfish/8269#-N0bqCNB5uriGPOKNUlU:-N0bqCNB5uriGPOKNUlV:bwibqkt) ([raw file](https://github.com/batfish/batfish/blob/8062b3dfe18c20a83e4cce20d68e8e79cb8a5de2/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_bgp.g4#L934)):*
> ```ANTLR
> ;
> 
> aggregate_address_prefix
> ```

I think it would be better to break this up into IPv4 and IPv6 variants, and use two alternatives in the grammar rules.

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8269)* status: 3 of 5 files reviewed, 4 unresolved discussions (waiting on @arifogel and @dhalperi)

___
*[`projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_bgp.g4` line 934 at r1](https://reviewable.io/reviews/batfish/batfish/8269#-N0bqCNB5uriGPOKNUlU:-N0dFoyi3RCliru98W07:b4sxqic) ([raw file](https://github.com/batfish/batfish/blob/8062b3dfe18c20a83e4cce20d68e8e79cb8a5de2/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_bgp.g4#L934)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

I think it would be better to break this up into IPv4 and IPv6 variants, and use two alternatives in the grammar rules.
</blockquote></details>

like that?
___
*[`projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java` line 3046 at r1](https://reviewable.io/reviews/batfish/batfish/8269#-N0bQPYXAMSDmFt589Bk:-N0dBYMe-k6vnMT0zviT:bvnrpcm) ([raw file](https://github.com/batfish/batfish/blob/8062b3dfe18c20a83e4cce20d68e8e79cb8a5de2/projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java#L3046)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

You changed one of these to a warning. Possible to do so here?
</blockquote></details>

updated
___
*[`projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java` line 3050 at r1](https://reviewable.io/reviews/batfish/batfish/8269#-N0bQ2jgAVx8GLXQe6pI:-N0dBdKoC9FrfLtlciRW:bvnrpcm) ([raw file](https://github.com/batfish/batfish/blob/8062b3dfe18c20a83e4cce20d68e8e79cb8a5de2/projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java#L3050)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

nit: nonnull
</blockquote></details>

updated
___
*[`projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java` line 3057 at r1](https://reviewable.io/reviews/batfish/batfish/8269#-N0bQDzFDofK3dSc_sFR:-N0dCZuH463rBlk1N_-F:bor384q) ([raw file](https://github.com/batfish/batfish/blob/8062b3dfe18c20a83e4cce20d68e8e79cb8a5de2/projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java#L3057)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Isn't there a `toPrefix(PrefixContext ctx)`? If not, please add one and use it. Same for v6.
</blockquote></details>

No, there isn't one.  Also there isn't a `prefix` or `ipv6_prefix` rule yet. I prefer not to do that at least in this PR as it will cause name conflicts with lots of "labels" in the Xr grammar.

**Review by arifogel — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8269)* status: all files reviewed, 2 unresolved discussions (waiting on @dhalperi and @sfraint)

___
*[`projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java` line 3057 at r1](https://reviewable.io/reviews/batfish/batfish/8269#-N0bQDzFDofK3dSc_sFR:-N0bpTQF0QmoWoD4nmJM:b-w3t9om) ([raw file](https://github.com/batfish/batfish/blob/8062b3dfe18c20a83e4cce20d68e8e79cb8a5de2/projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java#L3057)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

No, there isn't one.  Also there isn't a `prefix` or `ipv6_prefix` rule yet. I prefer not to do that at least in this PR as it will cause name conflicts with lots of "labels" in the Xr grammar.
</blockquote></details>

Ah didn't realize we're using tokens everywhere instead of rules for prefixes. Let's defer.
___
*[`projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java` line 3094 at r2](https://reviewable.io/reviews/batfish/batfish/8269#-N0gcR2o9KJm9LPnFxS6:-N0gcR2o9KJm9LPnFxS7:bqxx9my) ([raw file](https://github.com/batfish/batfish/blob/f409f25e6b2717af4e74cbc3e7ba1c23a51b1715/projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java#L3094)):*
> ```Java
>       }
>       assert ctx.ipv6_aggregate_address_prefix() != null;
>       toPrefix6(ctx.ipv6_aggregate_address_prefix())
> ```

With the current state of the parser rules, why is an optional needed at all anymore? Aren't these things guaranteed to convert based on the grammar?

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8269)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @arifogel and @dhalperi)

___
*[`projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java` line 3094 at r2](https://reviewable.io/reviews/batfish/batfish/8269#-N0gcR2o9KJm9LPnFxS6:-N0ghULs61FRg6KQfeWr:b835amg) ([raw file](https://github.com/batfish/batfish/blob/f409f25e6b2717af4e74cbc3e7ba1c23a51b1715/projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java#L3094)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

With the current state of the parser rules, why is an optional needed at all anymore? Aren't these things guaranteed to convert based on the grammar?
</blockquote></details>

Yep, updated

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8269)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dhalperi)

**Review by arifogel — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8269)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dhalperi)

**Pull request merged**
