### PR TITLE
Accept 'junos' as rancid content type

### PR DESCRIPTION
**Pull request by ratulm**
I cannot find official documentation for it but have come across this twice over the last month, in configurations from two independent users.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8132)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @arifogel and @ratulm)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/8132#-MxpHjar09izm2uIZhC8:-MxpHjar09izm2uIZhC9:b-sfbiq4) (no related file):*
Looks like his happened here: https://github.com/haussli/rancid/commit/a26ee438a94e5c7179588583d008421adae1ea35

"rancid.types.base: rename juniper -> junos. Add alias for juniper"

Can you figure out if we can extract the SOT from that file automatically?

---

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8132)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @arifogel and @ratulm)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/8132#-MxpHjar09izm2uIZhC8:-MxpI5I-3PSrrNJo7dlj:b-7ght9j) (no related file):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Looks like his happened here: https://github.com/haussli/rancid/commit/a26ee438a94e5c7179588583d008421adae1ea35

"rancid.types.base: rename juniper -> junos. Add alias for juniper"

Can you figure out if we can extract the SOT from that file automatically?
</blockquote></details>

Actually, maybe that's not quite right. We've been using `router.db`, but maybe that is wrong? https://github.com/haussli/rancid/blob/master/man/router.db.5

We should figure out the "right" thing,

---

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8132)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @arifogel and @dhalperi)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/8132#-MxpHjar09izm2uIZhC8:-Mxq6tWLBaQ8Ho5iEI7j:b9i1usz) (no related file):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Actually, maybe that's not quite right. We've been using `router.db`, but maybe that is wrong? https://github.com/haussli/rancid/blob/master/man/router.db.5

We should figure out the "right" thing,
</blockquote></details>

This seems to be right file: https://github.com/haussli/rancid/blob/master/etc/rancid.types.base 

---

**Comment by ratulm** [comment]
Superseded by #8135

**Pull request closed without merging**
