### PR TITLE
Make extractors consistently implement BatfishListener

### PR DESCRIPTION
**Pull request by arifogel**
- Make final-stage xxxExtractor / xxxConfigurationBuilder
  consistently implement BatfishListener
  - remove duplicate code
  - prerequisite for planned warning functionality

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6946)* status: all files reviewed, 2 unresolved discussions (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/grammar/f5_bigip_imish/F5BigipImishConfigurationBuilder.java, line 802 at r1](https://reviewable.io/reviews/batfish/batfish/6946#-MYqNsdOCNDhu15uG0QQ:-MYqNsdOCNDhu15uG0QR:bqjinn1) ([raw file](https://github.com/batfish/batfish/blob/f0a07c33e1e363d4f6f19767c22d6a3be94d227b/projects/batfish/src/main/java/org/batfish/grammar/f5_bigip_imish/F5BigipImishConfigurationBuilder.java#L802)):*
> ```Java
> 
>   @Override
>   public void todo(ParserRuleContext ctx) {
> ```

why only todo, not warn? (The structured one does both)

Add comment to explain why?
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/grammar/BatfishListener.java, line 30 at r1](https://reviewable.io/reviews/batfish/batfish/6946#-MYqOGc1Aw1bH8Im1HqJ:-MYqOGc1Aw1bH8Im1HqK:bvw79jn) ([raw file](https://github.com/batfish/batfish/blob/f0a07c33e1e363d4f6f19767c22d6a3be94d227b/projects/batfish-common-protocol/src/main/java/org/batfish/grammar/BatfishListener.java#L30)):*
> ```
>   default void todo(ParserRuleContext ctx) {
>     getWarnings().todo(ctx, getFullText(ctx), getParser());
>   }
> ```


Given the asymmetric overrides in some vendors, maybe this should be final and just call `warn(ctx, "fixed message")`.

Then vendors who want to change behaviors can only change one place.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6946)* status: 9 of 12 files reviewed, 2 unresolved discussions (waiting on @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/grammar/f5_bigip_imish/F5BigipImishConfigurationBuilder.java, line 802 at r1](https://reviewable.io/reviews/batfish/batfish/6946#-MYqNsdOCNDhu15uG0QQ:-MYqTUqB20cBJjNncxZ-:b-t7pb5r) ([raw file](https://github.com/batfish/batfish/blob/f0a07c33e1e363d4f6f19767c22d6a3be94d227b/projects/batfish/src/main/java/org/batfish/grammar/f5_bigip_imish/F5BigipImishConfigurationBuilder.java#L802)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

why only todo, not warn? (The structured one does both)

Add comment to explain why?
</blockquote></details>

No particular reason. I added default method `getWarningText()` used to get `ParserRuleContext` text by default implementation of `warn` and `todo`.

Now, `todo` and `warn` should generally not be overridden.

See updated javadocs in `BatfishListener`.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/grammar/BatfishListener.java, line 30 at r1](https://reviewable.io/reviews/batfish/batfish/6946#-MYqOGc1Aw1bH8Im1HqJ:-MYqRMDvCL9fJhozBzhD:bm1bipa) ([raw file](https://github.com/batfish/batfish/blob/f0a07c33e1e363d4f6f19767c22d6a3be94d227b/projects/batfish-common-protocol/src/main/java/org/batfish/grammar/BatfishListener.java#L30)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
>   default void todo(ParserRuleContext ctx) {
>     getWarnings().todo(ctx, getFullText(ctx), getParser());
>   }
> ```


Given the asymmetric overrides in some vendors, maybe this should be final and just call `warn(ctx, "fixed message")`.

Then vendors who want to change behaviors can only change one place.
</blockquote></details>

Can't make an interface method final.

But I did my best with updated functions and javadocs in `BatfishListener`.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6946)* status: 9 of 12 files reviewed, 2 unresolved discussions (waiting on @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/grammar/f5_bigip_imish/F5BigipImishConfigurationBuilder.java, line 802 at r1](https://reviewable.io/reviews/batfish/batfish/6946#-MYqNsdOCNDhu15uG0QQ:-MYqXpVL4CcXMC5YxHak:ba51nm5) ([raw file](https://github.com/batfish/batfish/blob/f0a07c33e1e363d4f6f19767c22d6a3be94d227b/projects/batfish/src/main/java/org/batfish/grammar/f5_bigip_imish/F5BigipImishConfigurationBuilder.java#L802)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

No particular reason. I added default method `getWarningText()` used to get `ParserRuleContext` text by default implementation of `warn` and `todo`.

Now, `todo` and `warn` should generally not be overridden.

See updated javadocs in `BatfishListener`.
</blockquote></details>

Actually, `imish` doesn't really need to truncate warnings, since it is not structured. Removed override altogether.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6946)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
