### PR TITLE
XR: Refactor OSPF VS model

### PR DESCRIPTION
**Pull request by corinaminer**
Create VS classes `OspfArea` and `OspfInterfaceSettings`, factor fields out of VS `OspfProcess`. Unlike IOS, XR does not allow configuration of OSPF settings within an interface stanza, which allows this part of the VS model to be less convoluted.

### CODE REVIEW

**Comment by dhalperi** [comment]
___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java, line 2618 at r1](https://reviewable.io/reviews/batfish/batfish/7187#-Mf4U7vT7lurFV1OCndw:-Mf4U7vT7lurFV1OCndx:bxj2uuf) ([raw file](https://github.com/batfish/batfish/blob/0ee4369ebfd61a395b203ebc573472f15c4a1bef/projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java#L2618)):*
> ```
> getInterfaceSettings()
> ```
why isn't this called `getAreaSettings()` or something like that?

**Comment by dhalperi** [comment]
___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java, line 2618 at r1](https://reviewable.io/reviews/batfish/batfish/7187#-Mf4U7vT7lurFV1OCndw:-Mf4V-gf5hMdX7TBoPcC:b3skdcv) ([raw file](https://github.com/batfish/batfish/blob/0ee4369ebfd61a395b203ebc573472f15c4a1bef/projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java#L2618)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> getInterfaceSettings()
> ```
why isn't this called `getAreaSettings()` or something like that?
</blockquote></details>

NM second commit :p.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 15 of 15 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7187)* status: all files reviewed, 1 unresolved discussion (waiting on @corinaminer and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java, line 2625 at r2](https://reviewable.io/reviews/batfish/batfish/7187#-Mf4V97t5BWWyvDIkzzY:-Mf4V97t5BWWyvDIkzzZ:btotxkt) ([raw file](https://github.com/batfish/batfish/blob/e54799b1d4229d68b4c4916e00c39d11b8199745/projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java#L2625)):*
> ```
> Roi
> ```
confirming: despite prefix `roi`, it's only valid under `roa`?

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7187)* status: all files reviewed, 1 unresolved discussion (waiting on @corinaminer and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConfiguration.java, line 1471 at r2](https://reviewable.io/reviews/batfish/batfish/7187#-Mf4UIv3A2IT5qAhrmRc:-Mf4UIv3A2IT5qAhrmRd:bd4y5xv) ([raw file](https://github.com/batfish/batfish/blob/6fba2d058656d3c18fa51e47361b30c764a91515/projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConfiguration.java#L1471)):*
> ```Java
>             (areaId, nssaSettings) -> {
>               if (!areas.containsKey(areaId)) {
>                 return;
> ```

fyi: this struck me as odd because it ignores the NSSA settings (and below, stub settings) if the OSPF area had no interfaces in it. note that it's not guaranteed the area won't be created if it has no interfaces; it will be created below if it has summaries.

In the new version, an area will now be created if it has NSSA or stub settings, even if it doesn't have interfaces or summaries. and NSSA/stub areas with summaries but no interfaces will get converted with the correct stub type.
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_xr/OspfProcess.java, line 63 at r2](https://reviewable.io/reviews/batfish/batfish/7187#-Mf4VYAw171ztHkgnZ5x:-Mf4VYAw171ztHkgnZ5y:b-zfa9xk) ([raw file](https://github.com/batfish/batfish/blob/6fba2d058656d3c18fa51e47361b30c764a91515/projects/batfish/src/main/java/org/batfish/representation/cisco_xr/OspfProcess.java#L63)):*
> ```Java
>   private final String _name;
> 
>   private Set<OspfNetwork> _networks;
> ```

Deleted because afaict, it was only used for interfaces with OSPF settings that were not mentioned in the router OSPF stanza. this is not possible in XR
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_xr/OspfProcess.java, line 75 at r2](https://reviewable.io/reviews/batfish/batfish/7187#-Mf4VMFaDaDEzZ6ojnbj:-Mf4VMFb6EfBmu2uq_mP:bntqfo3) ([raw file](https://github.com/batfish/batfish/blob/6fba2d058656d3c18fa51e47361b30c764a91515/projects/batfish/src/main/java/org/batfish/representation/cisco_xr/OspfProcess.java#L75)):*
> ```Java
>   private boolean _passiveInterfaceDefault;
> 
>   private Set<String> _passiveInterfaces;
> ```

Deleted because it was only used for tracking which interfaces were set to passive within the router OSPF stanza, which is now tracked in OSPF interface settings

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7187)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java, line 2625 at r2](https://reviewable.io/reviews/batfish/batfish/7187#-Mf4V97t5BWWyvDIkzzY:-Mf4WE-i9jdktVDBxbD_:bvca7v5) ([raw file](https://github.com/batfish/batfish/blob/e54799b1d4229d68b4c4916e00c39d11b8199745/projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java#L2625)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> Roi
> ```
confirming: despite prefix `roi`, it's only valid under `roa`?
</blockquote></details>

oh it's sort of ugly... this is the only usage of the extracted rules:
```
roa_interface
:
   INTERFACE iname = interface_name NEWLINE
   (
      ro_common
      | roi_cost
      | roi_network
      | roi_priority
      | roi_passive
   )*
;
```
But `roi_priority`, which is not extracted, also appears under `router ospf`. And as you can see, the `roi` rules don't actually contain info about an interface (e.g. `roi_priority` is just `PRIORITY uint_legacy NEWLINE`). Maybe if we're going to parse priority, we should make a separate `ro_priority` rule to put under `router ospf`. what do you think?

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7187)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java, line 2622 at r2](https://reviewable.io/reviews/batfish/batfish/7187#-Mf4bOmN5DjTyOi15_nG:-Mf4bOmO8e-uIYJPoLHO:b-593jrl) ([raw file](https://github.com/batfish/batfish/blob/6fba2d058656d3c18fa51e47361b30c764a91515/projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java#L2622)):*
> ```Java
>       warn(
>           ctx.iname,
>           String.format("OSPF interface %s not declared before OSPF process", ifaceName));
> ```

fyi, I believe this warning existed just because we were handling this case poorly. you can configure settings for an interface that doesn't exist, you can even commit them without creating the interface

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7187)* status: all files reviewed, 1 unresolved discussion (waiting on @corinaminer and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java, line 2625 at r2](https://reviewable.io/reviews/batfish/batfish/7187#-Mf4V97t5BWWyvDIkzzY:-Mf4lQahCoqZU9lGPBwQ:b-knjsvu) ([raw file](https://github.com/batfish/batfish/blob/e54799b1d4229d68b4c4916e00c39d11b8199745/projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java#L2625)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

oh it's sort of ugly... this is the only usage of the extracted rules:
```
roa_interface
:
   INTERFACE iname = interface_name NEWLINE
   (
      ro_common
      | roi_cost
      | roi_network
      | roi_priority
      | roi_passive
   )*
;
```
But `roi_priority`, which is not extracted, also appears under `router ospf`. And as you can see, the `roi` rules don't actually contain info about an interface (e.g. `roi_priority` is just `PRIORITY uint_legacy NEWLINE`). Maybe if we're going to parse priority, we should make a separate `ro_priority` rule to put under `router ospf`. what do you think?
</blockquote></details>

Yes I would not use `roi_` stuff elsewhere; add `ro_priority`.

Were I doing the work, I would also rename these `roai`, but not required.

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7187)* status: all files reviewed, 2 unresolved discussions (waiting on @corinaminer and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java, line 2626 at r2](https://reviewable.io/reviews/batfish/batfish/7187#-Mf4lnnw-7cN8Xsjp4LE:-Mf4lnnw-7cN8Xsjp4LF:bhswb7w) ([raw file](https://github.com/batfish/batfish/blob/e54799b1d4229d68b4c4916e00c39d11b8199745/projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java#L2626)):*
> ro_common

Also, I don't think this is valid at all.

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7187)* status: all files reviewed, 2 unresolved discussions (waiting on @corinaminer and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java, line 2626 at r2](https://reviewable.io/reviews/batfish/batfish/7187#-Mf4lnnw-7cN8Xsjp4LE:-Mf4m_bt4pprTQXmfWET:b585tx1) ([raw file](https://github.com/batfish/batfish/blob/e54799b1d4229d68b4c4916e00c39d11b8199745/projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java#L2626)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ro_common

Also, I don't think this is valid at all.
</blockquote></details>

That is, the extractor will always put the settings on proc, but if it's configured under ospf -> area -> interface I, it needs to be on I, right?

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7187)* status: 8 of 19 files reviewed, all discussions resolved (waiting on @dhalperi and @sfraint)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_ospf.g4, line 107 at r4](https://reviewable.io/reviews/batfish/batfish/7187#-Mf5N7Y21L0W5PBVY9uT:-Mf5N7Y21L0W5PBVY9uU:bbhof0n) ([raw file](https://github.com/batfish/batfish/blob/6fba2d058656d3c18fa51e47361b30c764a91515/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_ospf.g4#L107)):*
> ```ANTLR
> :
>    ro_authentication
>    | ro_nssa
> ```

fyi NSSA settings are area-specific
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_ospf.g4, line 108 at r4](https://reviewable.io/reviews/batfish/batfish/7187#-Mf5N9ci04EendqJoQCr:-Mf5N9ci04EendqJoQCs:bqr69a8) ([raw file](https://github.com/batfish/batfish/blob/6fba2d058656d3c18fa51e47361b30c764a91515/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_ospf.g4#L108)):*
> ```ANTLR
>    ro_authentication
>    | ro_nssa
>    | ro_rfc1583_compatibility
> ```

fyi XR does not have an RFC 1583 compatibility knob afaict
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_ospf.g4, line 279 at r4](https://reviewable.io/reviews/batfish/batfish/7187#-Mf5NLe018nmmUEma3U7:-Mf5NLe018nmmUEma3U8:b-c0ng76) ([raw file](https://github.com/batfish/batfish/blob/6fba2d058656d3c18fa51e47361b30c764a91515/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_ospf.g4#L279)):*
> ```ANTLR
> ;
> 
> ro_passive_interface
> ```

Fyi there are no `passive-interface` options on XR
___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java, line 2625 at r2](https://reviewable.io/reviews/batfish/batfish/7187#-Mf4V97t5BWWyvDIkzzY:-Mf4n1Rt8vC3447xCLEN:bomxdcr) ([raw file](https://github.com/batfish/batfish/blob/e54799b1d4229d68b4c4916e00c39d11b8199745/projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java#L2625)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Yes I would not use `roi_` stuff elsewhere; add `ro_priority`.

Were I doing the work, I would also rename these `roai`, but not required.
</blockquote></details>

refactored; `ro_priority` is now in `ro_common` along with all the formerly interface-specific rules.
___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java, line 2626 at r2](https://reviewable.io/reviews/batfish/batfish/7187#-Mf4lnnw-7cN8Xsjp4LE:-Mf5Mwve1g3KniWnYUlO:b21vtq) ([raw file](https://github.com/batfish/batfish/blob/e54799b1d4229d68b4c4916e00c39d11b8199745/projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java#L2626)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

That is, the extractor will always put the settings on proc, but if it's configured under ospf -> area -> interface I, it needs to be on I, right?
</blockquote></details>

The previous state was correct-ish, because nothing in `ro_common` was extracted. but now there are correctly-supported rules in it.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 6 files at r3, 10 of 10 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7187)* status: all files reviewed, 1 unresolved discussion (waiting on @corinaminer and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7187#-Mf5QU3m-3TPVl_CWbmA:-Mf5QU3m-3TPVl_CWbmB:bxztp5h) (no related file):*
Beautiful!

---
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_ospf.g4, line 106 at r4](https://reviewable.io/reviews/batfish/batfish/7187#-Mf5OEvRASEtF6dIVkUb:-Mf5OEvRASEtF6dIVkUc:b9wdh8a) ([raw file](https://github.com/batfish/batfish/blob/9cfeac754628cbef21f518f4ee9d380c40221187/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_ospf.g4#L106)):*
> ```
> ro_a
> ```
I think these should be prefixed `roc_` or something like that, so we can tell they're common. (Otherwise it looks like they're `router ospf`-level only).

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7187)* status: 16 of 19 files reviewed, all discussions resolved (waiting on @dhalperi and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7187#-Mf5QU3m-3TPVl_CWbmA:-Mf5ZTigBXIJw7aLCN7y:b-j1we20) (no related file):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Beautiful!
</blockquote></details>

:raised_hands: 

---
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_ospf.g4, line 106 at r4](https://reviewable.io/reviews/batfish/batfish/7187#-Mf5OEvRASEtF6dIVkUb:-Mf5U0ES-wQUZ32SL-dD:b-s5cb5g) ([raw file](https://github.com/batfish/batfish/blob/9cfeac754628cbef21f518f4ee9d380c40221187/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_ospf.g4#L106)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> ro_a
> ```
I think these should be prefixed `roc_` or something like that, so we can tell they're common. (Otherwise it looks like they're `router ospf`-level only).
</blockquote></details>

yeah fair

**Review by dhalperi — COMMENTED** [review]
> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7187)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

**Pull request merged**
