### PR TITLE
ibdp readability improvements, part 1

### PR DESCRIPTION
**Pull request by progwriter**
- No functionality changes
- Pull out the RIBs into a separate package
- Cleanup the `Node` class
   - Create getters for configuration/hostname/virtual routers
   - Make _virtualRouters immutable

### CODE REVIEW

**Comment by dhalperi** [comment]
Reviewed 48 of 66 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/Node.java, line 28 at r1](https://reviewable.io/reviews/batfish/batfish/1314#-LBja5WRB1OxHPE8UzPR:-LBja5WRB1OxHPE8UzPS:bf2uhhb) ([raw file](https://github.com/batfish/batfish/blob/3489ddc73721b4355c783222e3b5d9b92e533df1/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/Node.java#L28)):*
> ```Java
>     super(configuration.getHostname());
>     _c = configuration;
>     Builder<String, VirtualRouter> b = new Builder<>(Comparator.naturalOrder());
> ```

Probably don't import Builder, instead:

```java
ImmutableSortedMap.Builder<String, VirtualRouter> b = ImmutableSortedMap.naturalOrder();
```

alternately, you could:

```java
_virtualRouters = _c.getVrfs().keySet().collect(ImmutableSortedMap.toImmutableSortedMap(Comparator.naturalOrder(), vrf->vrf, vrf->new VirtualRouter(vrf, _c)));
```


---

*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/Node.java, line 47 at r1](https://reviewable.io/reviews/batfish/batfish/1314#-LBj_wLp0POSDUlvIZR-:-LBj_wLp0POSDUlvIZR0:b-pzjy6o) ([raw file](https://github.com/batfish/batfish/blob/3489ddc73721b4355c783222e3b5d9b92e533df1/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/Node.java#L47)):*
> ```Java
>    */
>   SortedMap<String, VirtualRouter> getVirtualRouters() {
>     return ImmutableSortedMap.copyOf(_virtualRouters);
> ```

why do the copy of if we know the property is an immutable sorted map?

---

*[projects/batfish/src/main/java/org/batfish/dataplane/rib/BgpBestPathRib.java, line 189 at r1](https://reviewable.io/reviews/batfish/batfish/1314#-LBjbZbQ0eH_oIgm-RLF:-LBjbZbQ0eH_oIgm-RLG:bh1uvqh) ([raw file](https://github.com/batfish/batfish/blob/3489ddc73721b4355c783222e3b5d9b92e533df1/projects/batfish/src/main/java/org/batfish/dataplane/rib/BgpBestPathRib.java#L189)):*
> ```Java
>       return 0;
>     } else {
>       return 1;
> ```

this would seem to violate the definition of a comparator.

---

*[projects/batfish/src/main/java/org/batfish/dataplane/rib/OspfExternalType1Rib.java, line 8 at r1](https://reviewable.io/reviews/batfish/batfish/1314#-LBjaxTi4YP6KyRTKezR:-LBjaxTi4YP6KyRTKezS:bi3xjw1) ([raw file](https://github.com/batfish/batfish/blob/3489ddc73721b4355c783222e3b5d9b92e533df1/projects/batfish/src/main/java/org/batfish/dataplane/rib/OspfExternalType1Rib.java#L8)):*
> ```Java
> import org.batfish.datamodel.OspfExternalType1Route;
> import org.batfish.datamodel.Prefix;
> import org.batfish.dataplane.ibdp.VirtualRouter;
> ```

Looks like VirtualRouter needs to move out of `ibdp` as well.

---

*[projects/batfish/src/main/java/org/batfish/dataplane/rib/RouteAdvertisement.java, line 7 at r1](https://reviewable.io/reviews/batfish/batfish/1314#-LBjbAvIAkz7wN4lT9YK:-LBjbAvIAkz7wN4lT9YL:b-au2ibg) ([raw file](https://github.com/batfish/batfish/blob/3489ddc73721b4355c783222e3b5d9b92e533df1/projects/batfish/src/main/java/org/batfish/dataplane/rib/RouteAdvertisement.java#L7)):*
> ```Java
> import org.batfish.datamodel.AbstractRoute;
> 
> public class RouteAdvertisement<R extends AbstractRoute> {
> ```

is this class abstract?

---

*[projects/batfish/src/main/java/org/batfish/dataplane/rib/RouteAdvertisement.java, line 10 at r1](https://reviewable.io/reviews/batfish/batfish/1314#-LBjb9IS6NfCAx45opVE:-LBjb9IS6NfCAx45opVF:b-i5ejqp) ([raw file](https://github.com/batfish/batfish/blob/3489ddc73721b4355c783222e3b5d9b92e533df1/projects/batfish/src/main/java/org/batfish/dataplane/rib/RouteAdvertisement.java#L10)):*
> ```Java
>   protected R _route;
>   protected boolean _withdraw;
>   public Reason _reason;
> ```

visibility change seems wrong.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1314)*

**Comment by progwriter** [comment]
Review status: 8 of 30 files reviewed at latest revision, 6 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/Node.java, line 28 at r1](https://reviewable.io/reviews/batfish/batfish/1314#-LBja5WRB1OxHPE8UzPR:-LBwdkEBCzweCISHYTnF:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/3489ddc73721b4355c783222e3b5d9b92e533df1/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/Node.java#L28)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Probably don't import Builder, instead:

```java
ImmutableSortedMap.Builder<String, VirtualRouter> b = ImmutableSortedMap.naturalOrder();
```

alternately, you could:

```java
_virtualRouters = _c.getVrfs().keySet().collect(ImmutableSortedMap.toImmutableSortedMap(Comparator.naturalOrder(), vrf->vrf, vrf->new VirtualRouter(vrf, _c)));
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/Node.java, line 47 at r1](https://reviewable.io/reviews/batfish/batfish/1314#-LBj_wLp0POSDUlvIZR-:-LBwdoZNBBw-EoR6smdS:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/3489ddc73721b4355c783222e3b5d9b92e533df1/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/Node.java#L47)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

why do the copy of if we know the property is an immutable sorted map?
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/dataplane/rib/BgpBestPathRib.java, line 189 at r1](https://reviewable.io/reviews/batfish/batfish/1314#-LBjbZbQ0eH_oIgm-RLF:-LBwf0G8E1QxDeq1yw1C:b-5r1yvo) ([raw file](https://github.com/batfish/batfish/blob/3489ddc73721b4355c783222e3b5d9b92e533df1/projects/batfish/src/main/java/org/batfish/dataplane/rib/BgpBestPathRib.java#L189)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

this would seem to violate the definition of a comparator.
</blockquote></details>

In what way?
Also note we don't currently implement all tie breaking measures anyway (see todos above), but that's a discussion for a different PR.

---

*[projects/batfish/src/main/java/org/batfish/dataplane/rib/OspfExternalType1Rib.java, line 8 at r1](https://reviewable.io/reviews/batfish/batfish/1314#-LBjaxTi4YP6KyRTKezR:-LBweELm-gAMrCdrIS3z:be2dpuk) ([raw file](https://github.com/batfish/batfish/blob/3489ddc73721b4355c783222e3b5d9b92e533df1/projects/batfish/src/main/java/org/batfish/dataplane/rib/OspfExternalType1Rib.java#L8)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Looks like VirtualRouter needs to move out of `ibdp` as well.
</blockquote></details>

Well, since you pulled on this thread.... VR does not have to be pulled out. But, Ribs don't have a good reason not keep a back pointer to their owner. Removed `_owner` from all RIBs.

---

*[projects/batfish/src/main/java/org/batfish/dataplane/rib/RouteAdvertisement.java, line 7 at r1](https://reviewable.io/reviews/batfish/batfish/1314#-LBjbAvIAkz7wN4lT9YK:-LBweiOc4I-3N4AdAjqk:b-mr5bxp) ([raw file](https://github.com/batfish/batfish/blob/3489ddc73721b4355c783222e3b5d9b92e533df1/projects/batfish/src/main/java/org/batfish/dataplane/rib/RouteAdvertisement.java#L7)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

is this class abstract?
</blockquote></details>

No, it's just a wrapper around any given RIB route.

---

*[projects/batfish/src/main/java/org/batfish/dataplane/rib/RouteAdvertisement.java, line 10 at r1](https://reviewable.io/reviews/batfish/batfish/1314#-LBjb9IS6NfCAx45opVE:-LBweo1Z6rXkrh3iJIe9:bfbq99i) ([raw file](https://github.com/batfish/batfish/blob/3489ddc73721b4355c783222e3b5d9b92e533df1/projects/batfish/src/main/java/org/batfish/dataplane/rib/RouteAdvertisement.java#L10)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

visibility change seems wrong.
</blockquote></details>

Good point, done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1314)*
<!-- Sent from Reviewable.io -->

**Comment by dhalperi** [comment]
*[projects/batfish/src/main/java/org/batfish/dataplane/rib/BgpBestPathRib.java, line 189 at r1](https://reviewable.io/reviews/batfish/batfish/1314#-LBjbZbQ0eH_oIgm-RLF:-LC-SJt7A5FY6e8k3-Fj:bqrlny) ([raw file](https://github.com/batfish/batfish/blob/3489ddc73721b4355c783222e3b5d9b92e533df1/projects/batfish/src/main/java/org/batfish/dataplane/rib/BgpBestPathRib.java#L189)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

In what way?
Also note we don't currently implement all tie breaking measures anyway (see todos above), but that's a discussion for a different PR.
</blockquote></details>

It's not legal for a.compare(b) and b.compare(a) to both return `1`. They can both return `0`, but if either one is signed they have to return that sign consistently and flip the sign in the other direction.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1314)*

**Comment by dhalperi** [comment]
Reviewed 22 of 36 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/dataplane/rib/RouteAdvertisement.java, line 7 at r1](https://reviewable.io/reviews/batfish/batfish/1314#-LBjbAvIAkz7wN4lT9YK:-LC-T-xwEayT8phDEWVh:b9n8rre) ([raw file](https://github.com/batfish/batfish/blob/3489ddc73721b4355c783222e3b5d9b92e533df1/projects/batfish/src/main/java/org/batfish/dataplane/rib/RouteAdvertisement.java#L7)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

No, it's just a wrapper around any given RIB route.
</blockquote></details>

Hmm. Designing a concrete class for inheritance is usually done wrong, so I "usually" expect classes to be either abstract or final. Maybe take a look at EJ19 and then we can chat.

Of course, this is outside the scope of this PR so I'll mark this resolved.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1314)*

**Comment by progwriter** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/java/org/batfish/dataplane/rib/BgpBestPathRib.java, line 189 at r1](https://reviewable.io/reviews/batfish/batfish/1314#-LBjbZbQ0eH_oIgm-RLF:-LC-tzdbBvSOinOvkwto:b-mzogd0) ([raw file](https://github.com/batfish/batfish/blob/3489ddc73721b4355c783222e3b5d9b92e533df1/projects/batfish/src/main/java/org/batfish/dataplane/rib/BgpBestPathRib.java#L189)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

It's not legal for a.compare(b) and b.compare(a) to both return `1`. They can both return `0`, but if either one is signed they have to return that sign consistently and flip the sign in the other direction.
</blockquote></details>

Right, but this is not a "true" comparator that is used to establish a total ordering. Nor is this compare function consistent with equals. We merely need to deterministically find a preferred route based on a subset of attributes.

---

*[projects/batfish/src/main/java/org/batfish/dataplane/rib/RouteAdvertisement.java, line 7 at r1](https://reviewable.io/reviews/batfish/batfish/1314#-LBjbAvIAkz7wN4lT9YK:-LC00BAH88dIuiUdNv63:bd0at02) ([raw file](https://github.com/batfish/batfish/blob/3489ddc73721b4355c783222e3b5d9b92e533df1/projects/batfish/src/main/java/org/batfish/dataplane/rib/RouteAdvertisement.java#L7)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Hmm. Designing a concrete class for inheritance is usually done wrong, so I "usually" expect classes to be either abstract or final. Maybe take a look at EJ19 and then we can chat.

Of course, this is outside the scope of this PR so I'll mark this resolved.
</blockquote></details>

Oh I see what you mean. At this time, there is no good reason to design for inheritance here. Switched to private fields.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1314)*

**Comment by dhalperi** [comment]
Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1314)*

**Comment by dhalperi** [comment]
Reviewed 2 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish/src/main/java/org/batfish/dataplane/rib/RibTreeNode.java, line 296 at r4](https://reviewable.io/reviews/batfish/batfish/1314#-LC0lKFh-v0Yr1ejksIA:-LC0lKFh-v0Yr1ejksIB:bcekopb) ([raw file](https://github.com/batfish/batfish/blob/a234ad1a3b64610d08a33667b37f8874b5917e6c/projects/batfish/src/main/java/org/batfish/dataplane/rib/RibTreeNode.java#L296)):*
> ```Java
>        */
>       R oldRoute = _routes.iterator().next();
>       int preferenceComparison = _owner.comparePreference(route, oldRoute);
> ```

newRoute? since its rhs?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1314)*

**Comment by dhalperi** [comment]
*[projects/batfish/src/main/java/org/batfish/dataplane/rib/RibTreeNode.java, line 296 at r4](https://reviewable.io/reviews/batfish/batfish/1314#-LC0lKFh-v0Yr1ejksIA:-LC0yVqp5D2atNYVEB8c:b-g48bjm) ([raw file](https://github.com/batfish/batfish/blob/a234ad1a3b64610d08a33667b37f8874b5917e6c/projects/batfish/src/main/java/org/batfish/dataplane/rib/RibTreeNode.java#L296)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

newRoute? since its rhs?
</blockquote></details>

Never mind, I'm backwards.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1314)*

**Pull request merged**
