### PR TITLE
Junos OSPF inheritance

### PR DESCRIPTION
**Pull request by ratulm**
Prior to this PR, Junos (logical) interfaces were inheriting their OSPF settings from the parent interfaces, along with other settings. This behavior is wrong, and this PR separates the inheritance of interface and OSPF settings.

The OSPF inheritance model is rather simple:
  - the "area X interface all" command adds all interfaces in the routing instance to the area X, with any other settings that following the command (e.g., hello-interval).
  -  if an interface is explicitly added to the area, it does not inherit anything from the "all" settings, even for unset settings. 
  - the "all" command can be used with only one area in the routing instance
  - a corollary is that there is no inheritance across areas

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7946)* status: 2 of 13 files reviewed, 2 unresolved discussions (waiting on @arifogel and @ratulm)

___
*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 2639 at r1](https://reviewable.io/reviews/batfish/batfish/7946#-MtdXZv-4DHP0TdwYsir:-MtdXZv-4DHP0TdwYsis:bsrwp1d) ([raw file](https://github.com/batfish/batfish/blob/471f59e72606ea8f5c2170115085246ca98f34cb/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L2639)):*
> ```Java
>       if (_currentOspfSettings == null) {
>         throw new BatfishException("Could not find interface with ip address: " + ip);
>       }
> ```

Crash or warn? Seems like should just warn and create a dummy settings?



_Code quote:_
```Java
      if (_currentOspfSettings == null) {
        throw new BatfishException("Could not find interface with ip address: " + ip);
      }
```
___
*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 6560 at r1](https://reviewable.io/reviews/batfish/batfish/7946#-MtdY0SD-7MFzKwzjZfv:-MtdY0SD-7MFzKwzjZfw:be1b620) ([raw file](https://github.com/batfish/batfish/blob/471f59e72606ea8f5c2170115085246ca98f34cb/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L6560)):*
> ```Java
>    * logical interfaces are created if they doesn't already exist. If the unit is not explicit in
>    * the configuration text, it is considered to be zero (per Junos semantics).
>    */
> ```

+reviewer:@arifogel should review this bit

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7946)* status: 1 of 14 files reviewed, 1 unresolved discussion (waiting on @arifogel and @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 6560 at r1](https://reviewable.io/reviews/batfish/batfish/7946#-MtdY0SD-7MFzKwzjZfv:-Mtdjowx9mGPci1wD9y1:bqz8pxs) ([raw file](https://github.com/batfish/batfish/blob/471f59e72606ea8f5c2170115085246ca98f34cb/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L6560)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

+reviewer:@arifogel should review this bit
</blockquote></details>

@arifogel - for context, the change is the following:
 
before:
   - on seeing statements, like `set protocols ospf area 0 interface ge-0/0/0`, OSPF settings were attached to interface`ge-0/0/0` and then inherited down to `ge-0/0/0.0`

after:
    OSPF settings are attached to interface`ge-0/0/0.0`

**Review by arifogel — COMMENTED** [review]
> Reviewed 11 of 13 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7946)* status: all files reviewed, 4 unresolved discussions (waiting on @dhalperi and @ratulm)

___
*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 6561 at r2](https://reviewable.io/reviews/batfish/batfish/7946#-Mte9FFu45OazNFlJEDP:-Mte9FFu45OazNFlJEDQ:b-ffgt0s) ([raw file](https://github.com/batfish/batfish/blob/12a61639c49b22be636f5369f28dcd7e2d7354a1/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L6561)):*
> ```Java
>    * Returns a logical interface mentioned in an OSPF or ISIS routing context. The physical and
>    * logical interfaces are created if they doesn't already exist. If the unit is not explicit in
>    * the configuration text, it is considered to be zero (per Junos semantics).
> ```

Can you link the doc? If only determined in lab, please say as much in comments.

Does IS-IS even use subinterfaces? I thought control traffic wasn't layer-3? Haven't looked at it in a while, so not sure on juniper. Please confirm same thing happens for IS-IS (interface x gets recorded as interface x.0).
___
*[projects/batfish/src/main/java/org/batfish/representation/juniper/Interface.java, line 339 at r2](https://reviewable.io/reviews/batfish/batfish/7946#-MteAbFFAuwYQ-bzR6AU:-MteAbFFAuwYQ-bzR6AV:b80ig3l) ([raw file](https://github.com/batfish/batfish/blob/12a61639c49b22be636f5369f28dcd7e2d7354a1/projects/batfish/src/main/java/org/batfish/representation/juniper/Interface.java#L339)):*
> ```Java
>    */
>   public @Nullable OspfInterfaceSettings getEffectiveOspfSettings() {
>     return _ospfSettings != null ? _ospfSettings : _routingInstance.getOspfSettings();
> ```

Really? If you have _any_ ospf setting for an interface, you ignore _all_ other ospf settings for interface `all`?
Please link doc or comment that this was discovered in lab.
___
*[projects/batfish/src/main/java/org/batfish/representation/juniper/RoutingInstance.java, line 147 at r2](https://reviewable.io/reviews/batfish/batfish/7946#-MteAzIF4yMhiMf-HF_l:-MteAzIF4yMhiMf-HF_m:b-ddoop6) ([raw file](https://github.com/batfish/batfish/blob/12a61639c49b22be636f5369f28dcd7e2d7354a1/projects/batfish/src/main/java/org/batfish/representation/juniper/RoutingInstance.java#L147)):*
> ```Java
>   }
> 
>   public OspfInterfaceSettings getOspfSettings() {
> ```

`@Nullable`, right? Please add null annotations all over for new code, including return types and parameters.
Also javadocs for public members.

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7946)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ratulm)

___
*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 6561 at r2](https://reviewable.io/reviews/batfish/batfish/7946#-Mte9FFu45OazNFlJEDP:-MteZSWN71Yf0icBhZbt:b-ruh19s) ([raw file](https://github.com/batfish/batfish/blob/12a61639c49b22be636f5369f28dcd7e2d7354a1/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L6561)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Can you link the doc? If only determined in lab, please say as much in comments.

Does IS-IS even use subinterfaces? I thought control traffic wasn't layer-3? Haven't looked at it in a while, so not sure on juniper. Please confirm same thing happens for IS-IS (interface x gets recorded as interface x.0).
</blockquote></details>

Had tested OSPF earlier. Just tested ISIS. Consistent behavior.

**Review by arifogel — COMMENTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7946)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ratulm)

**Pull request merged**
