### PR TITLE
FortiOS: better `addrgrp` nested block recovery

### PR DESCRIPTION
**Pull request by sfraint**
This PR improves recovery for unsupported `addrgrp` nested blocks.

That is, nested config blocks like `config tagging ... end` won't cause the parser to recover in the wrong context / consume the `end` as the end of the parent config block.

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6803)* status: all files reviewed, 2 unresolved discussions (waiting on @corinaminer and @sfraint)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_common.g4, line 81 at r1](https://reviewable.io/reviews/batfish/batfish/6803#-MX-9fy31JHFvwiUcYcz:-MX-9fy31JHFvwiUcYd-:b-1o8j39) ([raw file](https://github.com/batfish/batfish/blob/8b8e7d9d67fa301acd77ecb9789fc0f0c081406d/projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_common.g4#L81)):*
> ```ANTLR
> ;
> 
> unimplemented: UNIMPLEMENTED_PLACEHOLDER newline;
> ```

Is `UNIMPLEMENTED_PLACEHOLDER` used anywhere else? Does this work if you inline this definition into `unimplemented_edit_stanza`?
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/FortiosLexer.g4, line 137 at r1](https://reviewable.io/reviews/batfish/batfish/6803#-MX-9os84JfgcWCT68E0:-MX-9os84JfgcWCT68E1:b-iyqo2v) ([raw file](https://github.com/batfish/batfish/blob/8b8e7d9d67fa301acd77ecb9789fc0f0c081406d/projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/FortiosLexer.g4#L137)):*
> ```ANTLR
> SYSTEM: 'system';
> TAGGING: 'tagging';
> TAGS: 'tags' -> pushMode(M_Str);
> ```

Hopefully not needed

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6803)* status: all files reviewed, 2 unresolved discussions (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_common.g4, line 81 at r1](https://reviewable.io/reviews/batfish/batfish/6803#-MX-9fy31JHFvwiUcYcz:-MX-A3gf86djLJ5mHyOl:b-m2u59k) ([raw file](https://github.com/batfish/batfish/blob/8b8e7d9d67fa301acd77ecb9789fc0f0c081406d/projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_common.g4#L81)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Is `UNIMPLEMENTED_PLACEHOLDER` used anywhere else? Does this work if you inline this definition into `unimplemented_edit_stanza`?
</blockquote></details>

no, `UNIMPLEMENTED_PLACEHOLDER` is only used here

it does not work if in-lined in `unimplemented_edit_stanza`
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/FortiosLexer.g4, line 137 at r1](https://reviewable.io/reviews/batfish/batfish/6803#-MX-9os84JfgcWCT68E0:-MX-ASEe-sXrz4Hk9h5Z:bbf3m6t) ([raw file](https://github.com/batfish/batfish/blob/8b8e7d9d67fa301acd77ecb9789fc0f0c081406d/projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/FortiosLexer.g4#L137)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Hopefully not needed
</blockquote></details>

right, removed

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6803)* status: all files reviewed, 1 unresolved discussion (waiting on @corinaminer and @sfraint)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_common.g4, line 81 at r1](https://reviewable.io/reviews/batfish/batfish/6803#-MX-9fy31JHFvwiUcYcz:-MX-An7xCuwi2rkduC2W:b-v9xuyy) ([raw file](https://github.com/batfish/batfish/blob/8b8e7d9d67fa301acd77ecb9789fc0f0c081406d/projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_common.g4#L81)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

no, `UNIMPLEMENTED_PLACEHOLDER` is only used here

it does not work if in-lined in `unimplemented_edit_stanza`
</blockquote></details>

weird, ok.

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6803)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel, @corinaminer, and @sfraint)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_common.g4, line 81 at r1](https://reviewable.io/reviews/batfish/batfish/6803#-MX-9fy31JHFvwiUcYcz:-MX-AluU71_0usuylPRe:byql75e) ([raw file](https://github.com/batfish/batfish/blob/8b8e7d9d67fa301acd77ecb9789fc0f0c081406d/projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_common.g4#L81)):*
> it does not work if in-lined in unimplemented_edit_stanza

I'll also add a comment to that effect

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6803)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

**Pull request merged**
