### PR TITLE
add support for arbitrary IpWildcards in IpSpaceToBDD

### LINKED ISSUE #1256: Handle non-prefix wildcards in IpSpaceToBDD

### PR DESCRIPTION
**Pull request by anothermattbrown**
fixes #1256

### CODE REVIEW

**Comment by arifogel** [comment]
I don't exactly understand all of this, but :lgtm: I guess with minor suggestion.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish/src/main/java/org/batfish/symbolic/bdd/IpSpaceToBDD.java, line 72 at r1](https://reviewable.io/reviews/batfish/batfish/1257#-LB8kN9U9Y5lQRIXhK9X:-LB8kN9U9Y5lQRIXhK9Y:b-2237lu) ([raw file](https://github.com/batfish/batfish/blob/f81aa9b99fa37f381aa73ec48357610763929ff0/projects/batfish/src/main/java/org/batfish/symbolic/bdd/IpSpaceToBDD.java#L72)):*
> ```Java
>     long wildcard = ipWildcard.getWildcard().asLong();
>     BDD acc = _factory.one();
>     for (int i = 0; i < 32; i++) {
> ```

Prefix `Prefix.MAX_PREFIX_LENGTH` or related constant over `32`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1257#-:-LB8ki__3zDTalEiaWRX:b-pn5jhc)*

**Comment by haverma** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1257#-:-LBA4vrJEGWqD2WZAiaw:bnfp4nl)*

**Comment by arifogel** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/java/org/batfish/symbolic/bdd/IpSpaceToBDD.java, line 72 at r1](https://reviewable.io/reviews/batfish/batfish/1257#-LB8kN9U9Y5lQRIXhK9X:-LBCpuHr-QrhhbrekyJ_:b-ql6ziq) ([raw file](https://github.com/batfish/batfish/blob/f81aa9b99fa37f381aa73ec48357610763929ff0/projects/batfish/src/main/java/org/batfish/symbolic/bdd/IpSpaceToBDD.java#L72)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Prefix `Prefix.MAX_PREFIX_LENGTH` or related constant over `32`.
</blockquote></details>

That first "Prefix" should be "Prefer"

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1257)*

**Comment by arifogel** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1257)*

**Pull request merged**
