### PR TITLE
FortiOS: Static route support

### PR DESCRIPTION
**Pull request by corinaminer**
Includes parsing/extraction/conversion.

### CODE REVIEW

**Comment by dhalperi** [comment]
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/route/nh/NextHopInterface.java, line 64 at r1](https://reviewable.io/reviews/batfish/batfish/6753#-MWAPmpf1bXUhtUB0a9T:-MWAPmpg3zxSySimmtSU:b4nvfzf) ([raw file](https://github.com/batfish/batfish/blob/ee3ffa824b5b2cefca64c145e5f30696585a6ead/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/route/nh/NextHopInterface.java#L64)):*
> ```
>  of(String interfaceName, @Nullable Ip ip) {
> ```

This is an intentional @Nonnull: use the constructor above which just takes interface.

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6753)* status: 0 of 14 files reviewed, 1 unresolved discussion (waiting on @arifogel, @corinaminer, and @sfraint)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/route/nh/NextHopInterface.java, line 64 at r1](https://reviewable.io/reviews/batfish/batfish/6753#-MWAPmpf1bXUhtUB0a9T:-MWAQEPZ7X8719eVP6ch:b-e797cp) ([raw file](https://github.com/batfish/batfish/blob/ee3ffa824b5b2cefca64c145e5f30696585a6ead/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/route/nh/NextHopInterface.java#L64)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
>  of(String interfaceName, @Nullable Ip ip) {
> ```

This is an intentional @Nonnull: use the constructor above which just takes interface.
</blockquote></details>

(can look at #6545 for how this is typically handled)

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6753)* status: 0 of 13 files reviewed, all discussions resolved (waiting on @arifogel and @sfraint)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/route/nh/NextHopInterface.java, line 64 at r1](https://reviewable.io/reviews/batfish/batfish/6753#-MWAPmpf1bXUhtUB0a9T:-MWAXMetCWSuya4oz2nC:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/ee3ffa824b5b2cefca64c145e5f30696585a6ead/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/route/nh/NextHopInterface.java#L64)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

(can look at #6545 for how this is typically handled)
</blockquote></details>

done

**Review by sfraint — COMMENTED** [review]
> Reviewed 12 of 14 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6753)* status: all files reviewed, 2 unresolved discussions (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_static.g4, line 35 at r2](https://reviewable.io/reviews/batfish/batfish/6753#-MWBj7Hp5KGDh5rMOL4I:-MWBj7Hp5KGDh5rMOL4J:b80a6ml) ([raw file](https://github.com/batfish/batfish/blob/a7d15efc0c67187c3bdad6c8df0a8a5b21347f30/projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_static.g4#L35)):*
> ```
> // 0-4294967295 inclusive
> route_num: str;
> ```
I'm curious, are these values unique across all route types or just for static routes?
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 540 at r2](https://reviewable.io/reviews/batfish/batfish/6753#-MWBqICCC6oEySk1h5UG:-MWBqICD9E1y-BHeCzBR:bup7lak) ([raw file](https://github.com/batfish/batfish/blob/a7d15efc0c67187c3bdad6c8df0a8a5b21347f30/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L540)):*
> ```
>     toString(ctx, ctx.iface).ifPresent(_currentStaticRoute::setDevice);
> ```
does the iface have to exist? if it does have to exist, we should probably warn & discard the line
___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosRouteConversions.java, line 28 at r2](https://reviewable.io/reviews/batfish/batfish/6753#-MWBlm5b6YcfjgxiVBUe:-MWBlm5b6YcfjgxiVBUf:bwu6uii) ([raw file](https://github.com/batfish/batfish/blob/a7d15efc0c67187c3bdad6c8df0a8a5b21347f30/projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosRouteConversions.java#L28)):*
> ```
> // TODO Should SD-WAN
> ```
we should make sure new TODOs are being tracked somewhere - at least in the project for now

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6753)* status: all files reviewed, 2 unresolved discussions (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 540 at r2](https://reviewable.io/reviews/batfish/batfish/6753#-MWBqICCC6oEySk1h5UG:-MWBtqmS7moR9MildEqw:b-f9x62d) ([raw file](https://github.com/batfish/batfish/blob/a7d15efc0c67187c3bdad6c8df0a8a5b21347f30/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L540)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
>     toString(ctx, ctx.iface).ifPresent(_currentStaticRoute::setDevice);
> ```
does the iface have to exist? if it does have to exist, we should probably warn & discard the line
</blockquote></details>

(that is, warn and discard if it has to exist but doesn't)

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6753)* status: 9 of 14 files reviewed, all discussions resolved (waiting on @arifogel and @sfraint)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_static.g4, line 35 at r2](https://reviewable.io/reviews/batfish/batfish/6753#-MWBj7Hp5KGDh5rMOL4I:-MWBtkyFEboNjgCkAj8s:bukbyj9) ([raw file](https://github.com/batfish/batfish/blob/a7d15efc0c67187c3bdad6c8df0a8a5b21347f30/projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_static.g4#L35)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
> // 0-4294967295 inclusive
> route_num: str;
> ```
I'm curious, are these values unique across all route types or just for static routes?
</blockquote></details>

i'm not sure, i didn't check. Figured i'd call it `route_num` for now and if others use this, we can recycle it
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 530 at r2](https://reviewable.io/reviews/batfish/batfish/6753#-MWC4IScDKb0VQUmjDV1:-MWC4IScDKb0VQUmjDV2:b-xiazmm) ([raw file](https://github.com/batfish/batfish/blob/a7d15efc0c67187c3bdad6c8df0a8a5b21347f30/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L530)):*
> ```Java
>     String invalidReason = staticRouteValid(_currentStaticRoute, _currentStaticRouteNumValid);
>     if (invalidReason == null) {
>       // TODO structure definition
> ```

fyi, i don't think we actually need to track structure definition for static routes, unless they can be referenced by sequence number from some other context
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 540 at r2](https://reviewable.io/reviews/batfish/batfish/6753#-MWBqICCC6oEySk1h5UG:-MWBxRePACHMQ8O_Wcux:bezefhi) ([raw file](https://github.com/batfish/batfish/blob/a7d15efc0c67187c3bdad6c8df0a8a5b21347f30/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L540)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

(that is, warn and discard if it has to exist but doesn't)
</blockquote></details>

yes it does, done
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 535 at r3](https://reviewable.io/reviews/batfish/batfish/6753#-MWC4R3u1bLek-DCHFP6:-MWC4R3u1bLek-DCHFP7:bejx7c9) ([raw file](https://github.com/batfish/batfish/blob/338d642c2ec3c4535a8bc8b0c8e68a51d98bc22c/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L535)):*
> ```Java
>           _currentStaticRoute.getDevice(),
>           FortiosStructureUsage.STATIC_ROUTE_DEVICE,
>           ctx.start.getLine());
> ```

this line number won't be exactly right, but i don't know of a good way to identify the last valid `set device` line from here, and i don't want to reference the interface until the edit block goes through. Suggestions are welcome, but i think this is good enough for now -- it's not too egregious for a reference with usage `STATIC_ROUTE_DEVICE` to point to a static route edit block.
___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosRouteConversions.java, line 28 at r2](https://reviewable.io/reviews/batfish/batfish/6753#-MWBlm5b6YcfjgxiVBUe:-MWC1Zx7Cr-8l-4WStCq:b1vep63) ([raw file](https://github.com/batfish/batfish/blob/a7d15efc0c67187c3bdad6c8df0a8a5b21347f30/projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosRouteConversions.java#L28)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
> // TODO Should SD-WAN
> ```
we should make sure new TODOs are being tracked somewhere - at least in the project for now
</blockquote></details>

done (added a note in project)

**Review by sfraint — COMMENTED** [review]
> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6753)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 535 at r3](https://reviewable.io/reviews/batfish/batfish/6753#-MWC4R3u1bLek-DCHFP6:-MWC6MjP3vxXDMkOSXNX:b-onrp2c) ([raw file](https://github.com/batfish/batfish/blob/338d642c2ec3c4535a8bc8b0c8e68a51d98bc22c/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L535)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

this line number won't be exactly right, but i don't know of a good way to identify the last valid `set device` line from here, and i don't want to reference the interface until the edit block goes through. Suggestions are welcome, but i think this is good enough for now -- it's not too egregious for a reference with usage `STATIC_ROUTE_DEVICE` to point to a static route edit block.
</blockquote></details>

I think elsewhere / for other structure we add references as they're extracted even if they're overwritten (i.e. in `toInterface`)
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 1191 at r3](https://reviewable.io/reviews/batfish/batfish/6753#-MWC795k0mTD_j-760FX:-MWC795k0mTD_j-760FY:bafiurh) ([raw file](https://github.com/batfish/batfish/blob/338d642c2ec3c4535a8bc8b0c8e68a51d98bc22c/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L1191)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>     Optional<String> ifaceName = toString(ctx, ifaceNameCtx);
>     if (!ifaceName.isPresent()) {
>       // Warning is handled by toString.
>       // TODO Should this count as an undefined reference?
>       return Optional.empty();
> ```
</details>

I'd maybe opt to simplify this a bit:
1. convert the `str` into a `String` (not `Optional`) - leaving name-validity checking in the definition side of things
2. log anything that doesn't match as an undefined reference
___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosRouteConversions.java, line 28 at r2](https://reviewable.io/reviews/batfish/batfish/6753#-MWBlm5b6YcfjgxiVBUe:-MWC7l0q1dLUTicl2eBW:b4c9lyr) ([raw file](https://github.com/batfish/batfish/blob/a7d15efc0c67187c3bdad6c8df0a8a5b21347f30/projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosRouteConversions.java#L28)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

done (added a note in project)
</blockquote></details>

:thumbsup:

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6753)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 535 at r3](https://reviewable.io/reviews/batfish/batfish/6753#-MWC4R3u1bLek-DCHFP6:-MWC9hVm8RWFVYE4BVKT:b-sde6h5) ([raw file](https://github.com/batfish/batfish/blob/338d642c2ec3c4535a8bc8b0c8e68a51d98bc22c/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L535)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

I think elsewhere / for other structure we add references as they're extracted even if they're overwritten (i.e. in `toInterface`)
</blockquote></details>

that's an undefined reference though -- I thought for valid references, we wanted to hold off adding them until we know the edit block is going to be accepted
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 1191 at r3](https://reviewable.io/reviews/batfish/batfish/6753#-MWC795k0mTD_j-760FX:-MWC9_IC5sLaqBYJP4-h:b-l69fee) ([raw file](https://github.com/batfish/batfish/blob/338d642c2ec3c4535a8bc8b0c8e68a51d98bc22c/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L1191)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
>     Optional<String> ifaceName = toString(ctx, ifaceNameCtx);
>     if (!ifaceName.isPresent()) {
>       // Warning is handled by toString.
>       // TODO Should this count as an undefined reference?
>       return Optional.empty();
> ```
I'd maybe opt to simplify this a bit:
1. convert the `str` into a `String` (not `Optional`) - leaving name-validity checking in the definition side of things
2. log anything that doesn't match as an undefined reference

</blockquote></details>

Sounds good, done

**Review by sfraint — COMMENTED** [review]
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6753)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 535 at r3](https://reviewable.io/reviews/batfish/batfish/6753#-MWC4R3u1bLek-DCHFP6:-MWC8-YT1nY5Yy6Jpmea:b-dmavzg) ([raw file](https://github.com/batfish/batfish/blob/338d642c2ec3c4535a8bc8b0c8e68a51d98bc22c/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L535)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

that's an undefined reference though -- I thought for valid references, we wanted to hold off adding them until we know the edit block is going to be accepted
</blockquote></details>

that's not an undefined reference

we're recording all apparent references when we see them; this is also better for for consistency since we can't un-record old ones we overwrite in subsequent `edit` blocks

**Review by sfraint — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6753)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6753)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 535 at r3](https://reviewable.io/reviews/batfish/batfish/6753#-MWC4R3u1bLek-DCHFP6:-MWCHvEY2qRLFkgDxUvR:bbq8hve) ([raw file](https://github.com/batfish/batfish/blob/338d642c2ec3c4535a8bc8b0c8e68a51d98bc22c/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L535)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

that's not an undefined reference

we're recording all apparent references when we see them; this is also better for for consistency since we can't un-record old ones we overwrite in subsequent `edit` blocks
</blockquote></details>

got it, done

**Pull request merged**
