### PR TITLE
FortiOS: Move validation logic out of VS classes

### PR DESCRIPTION
**Pull request by corinaminer**
No new logic, just moved stuff around. Policy validity tests are copy/pasted from `PolicyTest`; service validity tests are new.

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6729)* status: all files reviewed, 1 unresolved discussion (waiting on @corinaminer)

___
*[projects/batfish/src/test/java/org/batfish/representation/fortios/BUILD, line 17 at r1](https://reviewable.io/reviews/batfish/batfish/6729#-MVrHee2ESRQx4eyMSQ3:-MVrHee3C8bvNlOz3qEF:b-y564fy) ([raw file](https://github.com/batfish/batfish/blob/b34306fe7b6132fdd82e207f24ac4f7eae528ec6/projects/batfish/src/test/java/org/batfish/representation/fortios/BUILD#L17)):*
> ```Starlark
>         "//projects/batfish-common-protocol:common",
>         "//projects/batfish-common-protocol/src/test/java/org/batfish/common/matchers",
>         "//projects/batfish/src/main/java/org/batfish/grammar/fortios",
> ```

Why this dependency? Seems like the wrong direction.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6729)* status: all files reviewed, 2 unresolved discussions (waiting on @corinaminer)

___
*[projects/batfish/src/test/java/org/batfish/representation/fortios/FortiosConfigurationTest.java, line 212 at r1](https://reviewable.io/reviews/batfish/batfish/6729#-MVrI3nmDUr30shPVoiK:-MVrI3nmDUr30shPVoiL:beyego7) ([raw file](https://github.com/batfish/batfish/blob/b34306fe7b6132fdd82e207f24ac4f7eae528ec6/projects/batfish/src/test/java/org/batfish/representation/fortios/FortiosConfigurationTest.java#L212)):*
> ```Java
> 
>   @Test
>   public void testPolicyValid() {
> ```

What do these tests have to do with `FortiosConfiguration`?

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6729)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @corinaminer)

___
*[projects/batfish/src/test/java/org/batfish/representation/fortios/FortiosConfigurationTest.java, line 212 at r1](https://reviewable.io/reviews/batfish/batfish/6729#-MVrI3nmDUr30shPVoiK:-MVrL9wq5BNu_zopHp0t:b-9y929e) ([raw file](https://github.com/batfish/batfish/blob/b34306fe7b6132fdd82e207f24ac4f7eae528ec6/projects/batfish/src/test/java/org/batfish/representation/fortios/FortiosConfigurationTest.java#L212)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

What do these tests have to do with `FortiosConfiguration`?
</blockquote></details>

Moved them

**Review by arifogel — COMMENTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6729)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
