### PR TITLE
Record from all `StructureManager`s for multi-file `VendorConfiguration`s

### PR DESCRIPTION
**Pull request by arifogel**

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8742)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @adrianliaw, @dhalperi, @progwriter, @sfraint, and @SLarkworthy)

___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java` line 89 at r1](https://reviewable.io/reviews/batfish/batfish/8742#-N_-L_S7-EYZ7mfhJ3Ym:-N_-n9Qb3wJHq0CYqe95:b-mb5ne9) ([raw file](https://github.com/batfish/batfish/blob/c4014e2a9e6966d6a23a2399149a20356b5c9cc4/projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java#L89)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Are we missing something for the existing multifile impls?
</blockquote></details>

Best I can tell the only existing multifile vendor with any structure tracking support is Sonic, and it only  tracks structures for `frr.conf`.

Updating Sonic is IMO out of scope for this PR.
___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java` line 94 at r1](https://reviewable.io/reviews/batfish/batfish/8742#-N_-LoGZ-X6k5Y_yX1Z8:-N_01XO9CP2l5-fmzYgB:bj67hiv) ([raw file](https://github.com/batfish/batfish/blob/c4014e2a9e6966d6a23a2399149a20356b5c9cc4/projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java#L94)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

missing test?
</blockquote></details>

added test

**Review by dhalperi — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8742)* status: all files reviewed, 1 unresolved discussion (waiting on @adrianliaw, @arifogel, @progwriter, @sfraint, and @SLarkworthy)

___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java` line 89 at r1](https://reviewable.io/reviews/batfish/batfish/8742#-N_-L_S7-EYZ7mfhJ3Ym:-N_032ph7TtreNCIP8TO:b8ptmag) ([raw file](https://github.com/batfish/batfish/blob/c4014e2a9e6966d6a23a2399149a20356b5c9cc4/projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java#L89)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Best I can tell the only existing multifile vendor with any structure tracking support is Sonic, and it only  tracks structures for `frr.conf`.

Updating Sonic is IMO out of scope for this PR.
</blockquote></details>

Ok. This is the first work separating defs and refs per file, then?

Do you have a handle on whether there are problems with this approach (fundamentally) if the structure definitions and references are in different files.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8742)* status: all files reviewed, 1 unresolved discussion (waiting on @adrianliaw, @dhalperi, @progwriter, @sfraint, and @SLarkworthy)

___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java` line 89 at r1](https://reviewable.io/reviews/batfish/batfish/8742#-N_-L_S7-EYZ7mfhJ3Ym:-N_09XSI6pPi6fxCensk:b4tlfyy) ([raw file](https://github.com/batfish/batfish/blob/c4014e2a9e6966d6a23a2399149a20356b5c9cc4/projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java#L89)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Ok. This is the first work separating defs and refs per file, then?

Do you have a handle on whether there are problems with this approach (fundamentally) if the structure definitions and references are in different files. 
</blockquote></details>

IMO this work is a precursor to supporting cross-file references, while not locking down any particular design. It certainly does not  solve the problem of references appearing undefined if they are actually defined in another file.

I think any solution that takes into account cross-file references needs to be well thought out. For instance, the general solution may involve the `scopes`, so that even within a file a structure with the same name and type may have multiple definitions.

Let me know if you think any of this work needs to be tackled now before changing at least this portion of the API.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8742)* status: all files reviewed, 1 unresolved discussion (waiting on @adrianliaw, @dhalperi, @progwriter, @sfraint, and @SLarkworthy)

___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java` line 89 at r1](https://reviewable.io/reviews/batfish/batfish/8742#-N_-L_S7-EYZ7mfhJ3Ym:-N_0Ano8B8ZYDu4_bW7n:b-i5deq5) ([raw file](https://github.com/batfish/batfish/blob/c4014e2a9e6966d6a23a2399149a20356b5c9cc4/projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java#L89)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

IMO this work is a precursor to supporting cross-file references, while not locking down any particular design. It certainly does not  solve the problem of references appearing undefined if they are actually defined in another file.

I think any solution that takes into account cross-file references needs to be well thought out. For instance, the general solution may involve the `scopes`, so that even within a file a structure with the same name and type may have multiple definitions.

Let me know if you think any of this work needs to be tackled now before changing at least this portion of the API.
</blockquote></details>

To clarify, the problem this PR does solve is allowing a config derived from multiple to declare structures whose definitions point to the right files, instead of a single concatenated or otherwise spurious file.

**Review by dhalperi — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8742#-:-N_0DJRGCcQxBSbke4gY:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @adrianliaw, @progwriter, @sfraint, and @SLarkworthy)

___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java` line 89 at r1](https://reviewable.io/reviews/batfish/batfish/8742#-N_-L_S7-EYZ7mfhJ3Ym:-N_0DM3tCgF_0tf75cgQ:b-d212nv) ([raw file](https://github.com/batfish/batfish/blob/c4014e2a9e6966d6a23a2399149a20356b5c9cc4/projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java#L89)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

To clarify, the problem this PR does solve is allowing a config derived from multiple to declare structures whose definitions point to the right files, instead of a single concatenated or otherwise spurious file.
</blockquote></details>

Makes sense, let's see where it goes :)

**Pull request merged**
