### PR TITLE
Warnings: dedupe

### PR DESCRIPTION
**Pull request by sfraint**
Prevent duplicate unimplemented, pedantic, and redFlag warnings.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 5 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6623)* status: 5 of 13 files reviewed, 1 unresolved discussion (waiting on @sfraint)

___
*[projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java, line 2213 at r1](https://reviewable.io/reviews/batfish/batfish/6623#-MTMHnpEDGteerSr2a2M:-MTMHnpEDGteerSr2a2N:bedbz37) ([raw file](https://github.com/batfish/batfish/blob/8d15533019fe95607907090d2455954c5a9fe6c9/projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java#L2213)):*
> ```Java
>         warnings.getRedFlagWarnings(),
>         contains(
>             equalTo(
> ```

these changes throughout are pretty gross. Worth adding a `WarningsMatchers` class, I think.

**Review by dhalperi — COMMENTED** [review]
:lgtm: nice

> Reviewed 14 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6623#-:-MTND4-_-nfvATwcJt-7:bb76hxo)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6623)* status: 15 of 17 files reviewed, all discussions resolved (waiting on @dhalperi)

___
*[projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java, line 2213 at r1](https://reviewable.io/reviews/batfish/batfish/6623#-MTMHnpEDGteerSr2a2M:-MTNDS3m-lwSjlLVvliV:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/8d15533019fe95607907090d2455954c5a9fe6c9/projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java#L2213)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

these changes throughout are pretty gross. Worth adding a `WarningsMatchers` class, I think.
</blockquote></details>

done

**Review by sfraint — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6623)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6623)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dhalperi — COMMENTED** [review]
> Reviewed 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6623)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
