### PR TITLE
Checkpoint implement cluster virtual IP assignment

### PR DESCRIPTION
**Pull request by arifogel**
- create a VRRP group for each participating cluster member interface
- assign priority that is higher the lower the member's index in
  cluster's cluster-member-names

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 6 of 8 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7367)* status: all files reviewed, 5 unresolved discussions (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java, line 188 at r2](https://reviewable.io/reviews/batfish/batfish/7367#-MjD-PqJ3a64mAxQap_8:-MjD-PqJ3a64mAxQap_9:b-q8mhc7) ([raw file](https://github.com/batfish/batfish/blob/dd0e8d4e4876be79d8434165a5754b08f0d8879c/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java#L188)):*
<details><summary><i alt="summary">Quoted 18 lines of code…</i></summary>

> ```
>     Class<? extends Cluster> clusterClass = ((ClusterMember) gateway).getClusterClass();
>     Optional<Entry<Cluster, Integer>> maybeClusterAndIndex =
>         domain.getGatewaysAndServers().values().stream()
>             .filter(clusterClass::isInstance)
>             .map(Cluster.class::cast)
>             .map(
>                 cluster ->
>                     immutableEntry(
>                         cluster, cluster.getClusterMemberNames().indexOf(gateway.getName())))
>             .filter(clusterAndIndex -> clusterAndIndex.getValue() != -1)
>             .findFirst();
>     if (!maybeClusterAndIndex.isPresent()) {
>       _w.redFlag(
>           String.format(
>               "Could not find matching cluster of type %s for this gateway of type %s",
>               clusterClass.getSimpleName(), gateway.getClass().getSimpleName()));
>       return;
>     }
> ```
</details>

I think this would be a lot simpler and clearer as a for loop.
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java, line 192 at r2](https://reviewable.io/reviews/batfish/batfish/7367#-MjD04KSEp2frvxgu6oh:-MjD04KSEp2frvxgu6oi:b7aicpc) ([raw file](https://github.com/batfish/batfish/blob/dd0e8d4e4876be79d8434165a5754b08f0d8879c/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java#L192)):*
> ```
>     Cluster cluster = clusterAndIndex.getKey();
>     _clusterMemberIndex = clusterAndIndex.getValue();
>     _clusterInterfaces =
> ```
I take it a device can only be a member of one cluster?
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java, line 512 at r2](https://reviewable.io/reviews/batfish/batfish/7367#-MjD08RgAUsflF6muh1v:-MjD08RgAUsflF6muh1w:b-4wg554) ([raw file](https://github.com/batfish/batfish/blob/dd0e8d4e4876be79d8434165a5754b08f0d8879c/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java#L512)):*
> ```
> associeates
> ```
typo: associated?
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java, line 529 at r2](https://reviewable.io/reviews/batfish/batfish/7367#-MjD0He-Bnqx58xPQn2R:-MjD0He-Bnqx58xPQn2S:beean12) ([raw file](https://github.com/batfish/batfish/blob/dd0e8d4e4876be79d8434165a5754b08f0d8879c/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java#L529)):*
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>

> ```
>     newIface.setVrrpGroups(
>         ImmutableSortedMap.of(
>             0,
>             VrrpGroup.builder()
>                 .setVirtualAddress(ConcreteInterfaceAddress.create(ip, maskLength))
>                 // prefer member with lowest cluster member index
>                 .setPriority(VrrpGroup.MAX_PRIORITY - _clusterMemberIndex)
>                 .setPreempt(true)
>                 .build()));
> ```
</details>


can an interface not have more than one cluster IP?
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java, line 579 at r2](https://reviewable.io/reviews/batfish/batfish/7367#-MjD0P-W5-b-_CluP9VL:-MjD0P-XAXsF28w2RoMk:bb8oim1) ([raw file](https://github.com/batfish/batfish/blob/dd0e8d4e4876be79d8434165a5754b08f0d8879c/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java#L579)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>   private transient Transformation _natTransformation;
>   private transient Map<String, org.batfish.vendor.check_point_management.Interface>
>       _clusterInterfaces;
>   private transient int _clusterMemberIndex;
> ```
</details>


Something seems very wrong here. Why do we need transient fields?

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7367)* status: 7 of 8 files reviewed, 4 unresolved discussions (waiting on @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java, line 188 at r2](https://reviewable.io/reviews/batfish/batfish/7367#-MjD-PqJ3a64mAxQap_8:-MjDGA4t3Bz8zRT4DOuv:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/dd0e8d4e4876be79d8434165a5754b08f0d8879c/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java#L188)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
>     Class<? extends Cluster> clusterClass = ((ClusterMember) gateway).getClusterClass();
>     Optional<Entry<Cluster, Integer>> maybeClusterAndIndex =
>         domain.getGatewaysAndServers().values().stream()
>             .filter(clusterClass::isInstance)
>             .map(Cluster.class::cast)
>             .map(
>                 cluster ->
>                     immutableEntry(
>                         cluster, cluster.getClusterMemberNames().indexOf(gateway.getName())))
>             .filter(clusterAndIndex -> clusterAndIndex.getValue() != -1)
>             .findFirst();
>     if (!maybeClusterAndIndex.isPresent()) {
>       _w.redFlag(
>           String.format(
>               "Could not find matching cluster of type %s for this gateway of type %s",
>               clusterClass.getSimpleName(), gateway.getClass().getSimpleName()));
>       return;
>     }
> ```
I think this would be a lot simpler and clearer as a for loop.
</blockquote></details>

done
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java, line 192 at r2](https://reviewable.io/reviews/batfish/batfish/7367#-MjD04KSEp2frvxgu6oh:-MjDEh-y3Lnubwz8mMEc:b-pxoq3s) ([raw file](https://github.com/batfish/batfish/blob/dd0e8d4e4876be79d8434165a5754b08f0d8879c/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java#L192)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
>     Cluster cluster = clusterAndIndex.getKey();
>     _clusterMemberIndex = clusterAndIndex.getValue();
>     _clusterInterfaces =
> ```
I take it a device can only be a member of one cluster?
</blockquote></details>

that's the assumption. added TODO to verify
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java, line 512 at r2](https://reviewable.io/reviews/batfish/batfish/7367#-MjD08RgAUsflF6muh1v:-MjDEmAz0iioqnKh6UEI:b-1l8its) ([raw file](https://github.com/batfish/batfish/blob/dd0e8d4e4876be79d8434165a5754b08f0d8879c/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java#L512)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> associeates
> ```
typo: associated?
</blockquote></details>

associates.
fixed.
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java, line 529 at r2](https://reviewable.io/reviews/batfish/batfish/7367#-MjD0He-Bnqx58xPQn2R:-MjDEy738VIATsedsFOm:b-orcc18) ([raw file](https://github.com/batfish/batfish/blob/dd0e8d4e4876be79d8434165a5754b08f0d8879c/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java#L529)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
>     newIface.setVrrpGroups(
>         ImmutableSortedMap.of(
>             0,
>             VrrpGroup.builder()
>                 .setVirtualAddress(ConcreteInterfaceAddress.create(ip, maskLength))
>                 // prefer member with lowest cluster member index
>                 .setPriority(VrrpGroup.MAX_PRIORITY - _clusterMemberIndex)
>                 .setPreempt(true)
>                 .build()));
> ```

can an interface not have more than one cluster IP?
</blockquote></details>

I don't think so, because the data model for interface appears to only support a single IP address.
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java, line 579 at r2](https://reviewable.io/reviews/batfish/batfish/7367#-MjD0P-W5-b-_CluP9VL:-MjDFEH785jbTlhljf2k:bsbbux3) ([raw file](https://github.com/batfish/batfish/blob/dd0e8d4e4876be79d8434165a5754b08f0d8879c/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java#L579)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
>   private transient Transformation _natTransformation;
>   private transient Map<String, org.batfish.vendor.check_point_management.Interface>
>       _clusterInterfaces;
>   private transient int _clusterMemberIndex;
> ```

Something seems very wrong here. Why do we need transient fields?
</blockquote></details>

The way the code is currently structured, it's easier to compute mgmt metadata applicable to this gateway in a single place to be used later when converting pieces of the actual gateway configuration.

Of course this could all be refactored, but IMO that is out of scope for this PR.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7367)* status: 7 of 8 files reviewed, 4 unresolved discussions (waiting on @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java, line 579 at r2](https://reviewable.io/reviews/batfish/batfish/7367#-MjD0P-W5-b-_CluP9VL:-MjDIvAu1N7wI9RKka0n:bs5k0ah) ([raw file](https://github.com/batfish/batfish/blob/dd0e8d4e4876be79d8434165a5754b08f0d8879c/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java#L579)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

The way the code is currently structured, it's easier to compute mgmt metadata applicable to this gateway in a single place to be used later when converting pieces of the actual gateway configuration.

Of course this could all be refactored, but IMO that is out of scope for this PR.
</blockquote></details>

Of note: keeping the current pattern `_c` should also be transient.

We could:
- not make anything transient, but modify non-final fields as we go along
- not modify fields at all, and make conversion side-effect free for `CheckpointGatewayConfiguration`
- just keep using fields that are modified during conversion (may as well be transient)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7367)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java, line 579 at r2](https://reviewable.io/reviews/batfish/batfish/7367#-MjD0P-W5-b-_CluP9VL:-MjFfUNm5kHArSh75fA9:bbcsh2q) ([raw file](https://github.com/batfish/batfish/blob/dd0e8d4e4876be79d8434165a5754b08f0d8879c/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java#L579)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Of note: keeping the current pattern `_c` should also be transient.

We could:
- not make anything transient, but modify non-final fields as we go along
- not modify fields at all, and make conversion side-effect free for `CheckpointGatewayConfiguration`
- just keep using fields that are modified during conversion (may as well be transient)
</blockquote></details>

Puntable, we can talk later.

**Pull request merged**
