### PR TITLE
Fix aclreachability output for lines with multiple covers

### PR DESCRIPTION
**Pull request by arifogel**
- conflicts and should be merged carefully with #1310 
- currently gives bizarre result for lines whose match condition is independently unsatisfiable

### CODE REVIEW

**Comment by arifogel** [comment]
Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1317#-LBiOWKUDiI93MecMVoR:-LBiOWKUDiI93MecMVoS:b-e1u26c) (no related file):*
Really should be merged somehow into #1310

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1317#-LBiOads-g8F0rXdX2KB:-LBiOads-g8F0rXdX2KC:b-cyfhhf) (no related file):*
Still does not gracefully handle trivially self-unsatisfiable lines

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1317)*

**Comment by dhalperi** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1317)*

**Comment by arifogel** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1317#-LBiOads-g8F0rXdX2KB:-LBxDp_45oi57l6icgHZ:bpztrjc) (no related file):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

it's stretching the scope of this PR a bit, but you could incorporate your work on independently unsatisfiable lines into `answerAclReachability` in the way we discussed this morning:
- find independently unsatisfiable lines and add them to answer (with another hacky -1 answer)
- go through first NoD step as usual
- go through second NoD step, but skip unreachable lines that also appear in independently unsatisfiable lines set

Or I can do that in a separate PR and this one can wait until that gets merged.
</blockquote></details>

Definitely out of scope for this PR

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 806 at r2](https://reviewable.io/reviews/batfish/batfish/1317#-LBx5cHiAZQFKazedCMd:-LBxDWuF5CNQx2GM-uDj:b-hc9dnk) ([raw file](https://github.com/batfish/batfish/blob/27afc37488e4c9a95a25823f0a0dc5efeb786a68/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L806)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Under what circumstance does `ipAccessListLine.getName()` return null?
</blockquote></details>

When `setName` on the builder is not called before building. One solution is to simply require it. Hopefully our tests wouldl catch all the null pointers.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1317)*

**Comment by corinaminer** [comment]
The functionality in this PR has been implemented and merged in #1310.

**Pull request closed without merging**
