### PR TITLE
BGP external announcements: Create a BGP session properties objects for import policy evaluation

### PR DESCRIPTION
**Pull request by ratulm**
This change helps evaluate routing policy statements that rely on the session object, such as set next hop peer address. The behavior prior to this change was to throw an exception when such statements were encountered.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7230)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @ratulm)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/RoutingPolicy.java, line 236 at r1](https://reviewable.io/reviews/batfish/batfish/7230#-MgRVpo4AHDBL5SJXLtJ:-MgRVpo59oMHYOP04vys:bocdrdl) ([raw file](https://github.com/batfish/batfish/blob/ef60aaad588ca5f717b7c1bb6d6312386c5fed68/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/RoutingPolicy.java#L236)):*
> ```Java
> 
>   /** @return True if the policy accepts the route. */
>   public boolean process(
> ```

is there a reason you can't use `processBgpRoute`?

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7230)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @ratulm)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7230#-MgRW2Qu0vCbxJPCmJXq:-MgRW2Qu0vCbxJPCmJXr:b-ap2wno) (no related file):*
Need some test from configs and advertisements, to make sure it works.

---

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7230)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @dhalperi and @ratulm)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7230#-MgRW2Qu0vCbxJPCmJXq:-MgSAHIX-L4tw-7e4LHl:b-twqq8z) (no related file):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Need some test from configs and advertisements, to make sure it works.
</blockquote></details>

Separate PR: https://github.com/batfish/batfish/pull/7231/files

---

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7230)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ratulm)

**Pull request merged**
