### PR TITLE
Handle new firewall encoding in reachability queries

### PR DESCRIPTION
**Pull request by anothermattbrown**

### CODE REVIEW

**Comment by anothermattbrown** [comment]
Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://beta.reviewable.io/reviews/batfish/batfish/1154#-L9rJxfm34CyxlnpKXOD:-L9rJxfm34CyxlnpKXOE:bupclew) (no related file):*
Work in progress. Still needs matching of srcInterface.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1154)*

**Comment by arifogel** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/java/org/batfish/z3/AclLineMatchExprToBooleanExpr.java, line 46 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1154#-L9vdNPi29--xjLBMi2T:-L9vdNPi29--xjLBMi2U:b-8h6uaz) ([raw file](https://github.com/batfish/batfish/blob/a2d84e5b1ddd065bc3a84ca3da7efbac67503404/projects/batfish/src/main/java/org/batfish/z3/AclLineMatchExprToBooleanExpr.java#L46)):*
> ```Java
>   public BooleanExpr visitAndMatchExpr(AndMatchExpr andMatchExpr) {
>     return new AndExpr(
>         andMatchExpr.getConjuncts().stream().map(this::toBooleanExpr).collect(Collectors.toList()));
> ```

I suggest you use `ImmutableList.toImmutableList` whenever possible. It uses less memory and has bonus of preventing accidental mutation.
You can apply this in `visitOrExpr` and `visitPermittedByAcl` as well.

---

*[projects/batfish/src/main/java/org/batfish/z3/AclLineMatchExprToBooleanExpr.java, line 76 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1154#-L9vdzRE29UeTthHaB3y:-L9vdzRE29UeTthHaB3z:blpzq2s) ([raw file](https://github.com/batfish/batfish/blob/a2d84e5b1ddd065bc3a84ca3da7efbac67503404/projects/batfish/src/main/java/org/batfish/z3/AclLineMatchExprToBooleanExpr.java#L76)):*
> ```Java
> 
>   @Override
>   public BooleanExpr visitPermittedByAcl(PermittedByAcl permittedByAcl) {
> ```

Should we cache results of using this? Also may help with cycles.

---

*[projects/batfish/src/main/java/org/batfish/z3/AclLineMatchExprToBooleanExpr.java, line 87 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1154#-L9vcvsvDD-tRqR9PIb0:-L9vcvsvDD-tRqR9PIb1:b-i71xy3) ([raw file](https://github.com/batfish/batfish/blob/a2d84e5b1ddd065bc3a84ca3da7efbac67503404/projects/batfish/src/main/java/org/batfish/z3/AclLineMatchExprToBooleanExpr.java#L87)):*
> ```Java
>     // Right fold. Base case (when no line matches) is not permitted.
>     BooleanExpr expr = org.batfish.z3.expr.FalseExpr.INSTANCE;
>     for (int i = lineExprs.size() - 1; i >= 0; i--) {
> ```

I think this would be cleaner if you just use reverse order iterator. It doesn't look like you need the index explicitly.

---

*[projects/batfish/src/main/java/org/batfish/z3/EarliestMoreGeneralReachableLineQuerySynthesizer.java, line 50 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1154#-L9ve9Ey2NfdC_tD87C2:-L9ve9Ey2NfdC_tD87C3:bxmltoz) ([raw file](https://github.com/batfish/batfish/blob/a2d84e5b1ddd065bc3a84ca3da7efbac67503404/projects/batfish/src/main/java/org/batfish/z3/EarliestMoreGeneralReachableLineQuerySynthesizer.java#L50)):*
> ```Java
>     AclLineMatchExprToBooleanExpr aclLineMatchExprToBooleanExpr =
>         new AclLineMatchExprToBooleanExpr();
>     /* TODO: handle match types other than header space, e.g. conjunction, indirection, etc. */
> ```

Should we remove this comment now? It is implied by your todo in the visitor.

---

*[projects/batfish/src/test/java/org/batfish/z3/AclLineMatchExprToBooleanExprTest.java, line 35 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1154#-L9veZ8Z-HbckuMJMOjt:-L9veZ8Z-HbckuMJMOju:b5r8vlz) ([raw file](https://github.com/batfish/batfish/blob/a2d84e5b1ddd065bc3a84ca3da7efbac67503404/projects/batfish/src/test/java/org/batfish/z3/AclLineMatchExprToBooleanExprTest.java#L35)):*
> ```Java
> 
>   @Test
>   public void testAndMatchExpr() {
> ```

Optional: Move these to separate tests with more specific names like you did for `PermittedByAcl`. Can do this for `testOrMatchExpr` as well.

---

*[projects/batfish/src/test/java/org/batfish/z3/AclLineMatchExprToBooleanExprTest.java, line 60 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1154#-L9velneBRNDzmgOTn3_:-L9velneBRNDzmgOTn3a:b8fog35) ([raw file](https://github.com/batfish/batfish/blob/a2d84e5b1ddd065bc3a84ca3da7efbac67503404/projects/batfish/src/test/java/org/batfish/z3/AclLineMatchExprToBooleanExprTest.java#L60)):*
> ```Java
> 
>   @Test
>   public void testMatchHeaderspace() {
> ```

Can you add a test for unrestricted header space?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1154)*

**Comment by anothermattbrown** [comment]
*[a discussion](https://beta.reviewable.io/reviews/batfish/batfish/1154#-L9rJxfm34CyxlnpKXOD:-LA4Xn2Z5-3oDfpXmMVl:b-lfsngn) (no related file):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

Work in progress. Still needs matching of srcInterface.
</blockquote></details>

Done with MatchSrcInterface

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1154)*

**Comment by anothermattbrown** [comment]
Review status: 1 of 49 files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://beta.reviewable.io/reviews/batfish/batfish/1154#-LA6KUwN9PV74JYX3GDw:-LA6KUwN9PV74JYX3GDx:b-6d4w4k) (no related file):*
TODO: unit tests like NodJobTest that includes NOD.

---

*[a discussion](https://beta.reviewable.io/reviews/batfish/batfish/1154#-LA6Kbr7BKehgntEZDXb:-LA6Kbr7BKehgntEZDXc:b-eo10cy) (no related file):*
TODO: ref tests that exercise new ACL features end-to-end. 

---

*[projects/batfish/src/main/java/org/batfish/z3/AclLineMatchExprToBooleanExpr.java, line 46 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1154#-L9vdNPi29--xjLBMi2T:-LA6Gjet-VlZ1ni4RitZ:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/a2d84e5b1ddd065bc3a84ca3da7efbac67503404/projects/batfish/src/main/java/org/batfish/z3/AclLineMatchExprToBooleanExpr.java#L46)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

I suggest you use `ImmutableList.toImmutableList` whenever possible. It uses less memory and has bonus of preventing accidental mutation.
You can apply this in `visitOrExpr` and `visitPermittedByAcl` as well.
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/z3/AclLineMatchExprToBooleanExpr.java, line 76 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1154#-L9vdzRE29UeTthHaB3y:-LA6Ilky2h4Inr5YxZZW:bpci3ah) ([raw file](https://github.com/batfish/batfish/blob/a2d84e5b1ddd065bc3a84ca3da7efbac67503404/projects/batfish/src/main/java/org/batfish/z3/AclLineMatchExprToBooleanExpr.java#L76)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Should we cache results of using this? Also may help with cycles.
</blockquote></details>

I don't have an opinion on caching. I don't see how it will help with cycles though, at least for this encoding of an ACL as a BooleanExpr -- it will have to be an infinite tree either way. It may be sufficient to detect and report cyclic ACLs as an error. If we need to support them I think we'd have to encode them as NOD relations. What do you think?

---

*[projects/batfish/src/main/java/org/batfish/z3/AclLineMatchExprToBooleanExpr.java, line 87 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1154#-L9vcvsvDD-tRqR9PIb0:-LA6GoLL7C-54xpcrCQ2:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/a2d84e5b1ddd065bc3a84ca3da7efbac67503404/projects/batfish/src/main/java/org/batfish/z3/AclLineMatchExprToBooleanExpr.java#L87)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

I think this would be cleaner if you just use reverse order iterator. It doesn't look like you need the index explicitly.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1154)*

**Comment by anothermattbrown** [comment]
Review status: all files reviewed at latest revision, 16 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/z3/AclLineMatchExprToBooleanExpr.java, line 76 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1154#-L9vdzRE29UeTthHaB3y:-LAEnDmV2D1l0jy7mKBF:bap5wtt) ([raw file](https://github.com/batfish/batfish/blob/a2d84e5b1ddd065bc3a84ca3da7efbac67503404/projects/batfish/src/main/java/org/batfish/z3/AclLineMatchExprToBooleanExpr.java#L76)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

OK so deferring any discussion of caching, we should probably have cycle detection. As you say, the alternative is an infinite loop. There is no need to encode a cycle - we should just break them at some point (probably treat as unmatchable). If you want to deal with this later, please file an issue at least.
</blockquote></details>

Block until filing the issue.

---

*[projects/batfish/src/main/java/org/batfish/z3/EarliestMoreGeneralReachableLineQuerySynthesizer.java, line 71 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1154#-LAEVbMJ2oYUGx7FG-_1:-LAEnbQO2x3xFQUt9eQ-:b-m4rjpg) ([raw file](https://github.com/batfish/batfish/blob/18a25f1b0dcf55c468566c76f035e66be3ada1d3/projects/batfish/src/main/java/org/batfish/z3/EarliestMoreGeneralReachableLineQuerySynthesizer.java#L71)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Why `+ 1`?
</blockquote></details>

Because I reserve 0 for "no source interface" -- e.g. when originating from a Vrf.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1154)*

**Comment by arifogel** [comment]
Reviewed 20 of 20 files at r3.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/EdgeMatchers.java, line 1 at r3](https://beta.reviewable.io/reviews/batfish/batfish/1154#-LAFee3dB0jdK5DOY6XL:-LAFee3dB0jdK5DOY6XM:bbmxuws) ([raw file](https://github.com/batfish/batfish/blob/100920291cab6a0639fc420ff834272cb5fc1917/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/EdgeMatchers.java#L1)):*
> ```Java
> package org.batfish.datamodel;
> ```

Please move to `org.batfish.datamodel.matchers` package.

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/EdgeMatchers.java, line 3 at r3](https://beta.reviewable.io/reviews/batfish/batfish/1154#-LAFezEz2PiIjjPf77ys:-LAFezEz2PiIjjPf77yt:bq9yhfk) ([raw file](https://github.com/batfish/batfish/blob/100920291cab6a0639fc420ff834272cb5fc1917/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/EdgeMatchers.java#L3)):*
> ```Java
> package org.batfish.datamodel;
> 
> import org.hamcrest.Description;
> ```

Please add javadocs for public functions.

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/EdgeMatchers.java, line 26 at r3](https://beta.reviewable.io/reviews/batfish/batfish/1154#-LAFelbO4ZHdiR413Daa:-LAFelbO4ZHdiR413Dab:bmqz1zf) ([raw file](https://github.com/batfish/batfish/blob/100920291cab6a0639fc420ff834272cb5fc1917/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/EdgeMatchers.java#L26)):*
> ```Java
>   private EdgeMatchers() {}
> 
>   private static class HasInt1 extends TypeSafeDiagnosingMatcher<Edge> {
> ```

Why not just use `FeatureMatcher`? See e.g. `InterfaceMatchersImpl`

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1154)*

**Comment by arifogel** [comment]
Reviewed 11 of 11 files at r4.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/EdgeMatchers.java, line 12 at r4](https://beta.reviewable.io/reviews/batfish/batfish/1154#-LAGKbSk-fqJcrh5lCFq:-LAGKbSk-fqJcrh5lCFr:b-4mm5za) ([raw file](https://github.com/batfish/batfish/blob/f9b5e8e9c7bab7d654a4d996430304bc51302c02/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/EdgeMatchers.java#L12)):*
> ```Java
>    * @return A {@Matcher} for the {@Edge}.
>    */
>   public static HasInt1 hasInt1(Matcher<String> subMatcher) {
> ```

All subMatcher should be of type: `Matcher<? super SomeClass>`. Otherwise you wouldn't be able to use say a `Matcher<Object>` on the feature.
If you are getting fatigued, on matchers, just file a cleanup ticket and assign to me. I'll fix after merge.

---

*[projects/batfish/src/test/java/org/batfish/z3/NodJobTest.java, line 468 at r4](https://beta.reviewable.io/reviews/batfish/batfish/1154#-LAGM0NBCkVwKGGF2fzM:-LAGM0NBCkVwKGGF2fzN:b-addvf9) ([raw file](https://github.com/batfish/batfish/blob/f9b5e8e9c7bab7d654a4d996430304bc51302c02/projects/batfish/src/test/java/org/batfish/z3/NodJobTest.java#L468)):*
> ```Java
>         containsInAnyOrder(
>             allOf(
>                 FlowTraceMatchers.hasDisposition(
> ```

static imports will make this more legible: can use for matchers, enums.
Also consider matcher functions that take object directly to avoid passing submatcher of say `equalTo(theobject)`.

In particular I am having trouble deciphering the parts at the with the `contains` and `any`.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1154)*

**Comment by anothermattbrown** [comment]
Review status: 54 of 61 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/EdgeMatchers.java, line 1 at r3](https://beta.reviewable.io/reviews/batfish/batfish/1154#-LAFee3dB0jdK5DOY6XL:-LAH1MStAObVSUGE7veb:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/100920291cab6a0639fc420ff834272cb5fc1917/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/EdgeMatchers.java#L1)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Please move to `org.batfish.datamodel.matchers` package.
</blockquote></details>

Done.

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/EdgeMatchers.java, line 3 at r3](https://beta.reviewable.io/reviews/batfish/batfish/1154#-LAFezEz2PiIjjPf77ys:-LAH1Npg1xsvJWrbID4J:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/100920291cab6a0639fc420ff834272cb5fc1917/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/EdgeMatchers.java#L3)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Please add javadocs for public functions.
</blockquote></details>

Done.

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/EdgeMatchers.java, line 26 at r3](https://beta.reviewable.io/reviews/batfish/batfish/1154#-LAFelbO4ZHdiR413Daa:-LAH1My67SFikYV2UKm3:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/100920291cab6a0639fc420ff834272cb5fc1917/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/EdgeMatchers.java#L26)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Why not just use `FeatureMatcher`? See e.g. `InterfaceMatchersImpl`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1154)*

**Comment by arifogel** [comment]
Reviewed 4 of 6 files at r6, 3 of 3 files at r7.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1154)*

**Comment by anothermattbrown** [comment]
Review status: 56 of 61 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[projects/batfish/src/main/java/org/batfish/z3/AclLineMatchExprToBooleanExpr.java, line 76 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1154#-L9vdzRE29UeTthHaB3y:-LAJTjLk3zlfv6bO61xB:bf9zcgj) ([raw file](https://github.com/batfish/batfish/blob/a2d84e5b1ddd065bc3a84ca3da7efbac67503404/projects/batfish/src/main/java/org/batfish/z3/AclLineMatchExprToBooleanExpr.java#L76)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

Block until filing the issue.
</blockquote></details>

Opened #1184 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1154)*

**Comment by anothermattbrown** [comment]
Review status: 56 of 61 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[projects/batfish/src/main/java/org/batfish/z3/expr/visitors/TransformedVarCollector.java, line 59 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1154#-LAEdcYzAxUwgwR4UCAm:-LAJUjfwCpqor7lv-H-e:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/18a25f1b0dcf55c468566c76f035e66be3ada1d3/projects/batfish/src/main/java/org/batfish/z3/expr/visitors/TransformedVarCollector.java#L59)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Wrap in `ImmutableSet.copyOf` if appropriate. Elsewhere in file as well.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1154)*

**Comment by anothermattbrown** [comment]
Review status: 53 of 62 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://beta.reviewable.io/reviews/batfish/batfish/1154#-LA6Kbr7BKehgntEZDXb:-LAJkAp45ZWeNBBQ63HO:b-1qtzfk) (no related file):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

TODO: ref tests that exercise new ACL features end-to-end. 
</blockquote></details>

In the interest of time, let's leave this for later.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1154)*

**Comment by anothermattbrown** [comment]
Review status: 53 of 62 files reviewed at latest revision, 3 unresolved discussions.

---

*[projects/batfish/src/test/java/org/batfish/z3/NodJobTest.java, line 468 at r4](https://beta.reviewable.io/reviews/batfish/batfish/1154#-LAGM0NBCkVwKGGF2fzM:-LAJkMxeCICtzrfTwGP2:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/f9b5e8e9c7bab7d654a4d996430304bc51302c02/projects/batfish/src/test/java/org/batfish/z3/NodJobTest.java#L468)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

static imports will make this more legible: can use for matchers, enums.
Also consider matcher functions that take object directly to avoid passing submatcher of say `equalTo(theobject)`.

In particular I am having trouble deciphering the parts at the with the `contains` and `any`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1154)*

**Comment by arifogel** [comment]
Reviewed 9 of 9 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/java/org/batfish/z3/expr/visitors/TransformedVarCollector.java, line 34 at r8](https://beta.reviewable.io/reviews/batfish/batfish/1154#-LAJnRpb23pmhcdOX2h-:-LAJnRpb23pmhcdOX2h0:b-wh6oqk) ([raw file](https://github.com/batfish/batfish/blob/dcb768101a5636a57b549f07a5ecdbc27cba1902/projects/batfish/src/main/java/org/batfish/z3/expr/visitors/TransformedVarCollector.java#L34)):*
> ```Java
>   public Set<Field> castToGenericBooleanExprVisitorReturnType(Object o) {
>     @SuppressWarnings("unchecked")
>     Set<Field> set = (Set<Field>) o;
> ```

This is actually dangerous.
I'd prefer one of two solutions:
1. Cast each element and feed into new set (performance penalty).
2. Use a type that extends Set<Field> as the generic return type argument for `TransformedVarCollector` (ugly).

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1154)*

**Comment by anothermattbrown** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/z3/expr/visitors/TransformedVarCollector.java, line 34 at r8](https://beta.reviewable.io/reviews/batfish/batfish/1154#-LAJnRpb23pmhcdOX2h-:-LAJqz442dXBArOJVDpn:bg3ou5j) ([raw file](https://github.com/batfish/batfish/blob/dcb768101a5636a57b549f07a5ecdbc27cba1902/projects/batfish/src/main/java/org/batfish/z3/expr/visitors/TransformedVarCollector.java#L34)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

This is actually dangerous.
I'd prefer one of two solutions:
1. Cast each element and feed into new set (performance penalty).
2. Use a type that extends Set<Field> as the generic return type argument for `TransformedVarCollector` (ugly).
</blockquote></details>

Of the 2 choices, I like 1 better, but I'd prefer to remove the `castToGenericBooleanExprVisitorReturnType` altogether.
What's the risk here?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1154)*

**Comment by arifogel** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/z3/expr/visitors/TransformedVarCollector.java, line 34 at r8](https://beta.reviewable.io/reviews/batfish/batfish/1154#-LAJnRpb23pmhcdOX2h-:-LAKO0SF0xzGhfxIQW5T:b-969npl) ([raw file](https://github.com/batfish/batfish/blob/dcb768101a5636a57b549f07a5ecdbc27cba1902/projects/batfish/src/main/java/org/batfish/z3/expr/visitors/TransformedVarCollector.java#L34)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

Of the 2 choices, I like 1 better, but I'd prefer to remove the `castToGenericBooleanExprVisitorReturnType` altogether.
What's the risk here?
</blockquote></details>

It is required by mock versions of the type(s) you are visiting. If you remove it, they may not compile without truly unsafe casts.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1154)*

**Comment by arifogel** [comment]
:lgtm: with one small complaint.

---

Reviewed 9 of 9 files at r9.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/java/org/batfish/z3/AclLineMatchExprToBooleanExpr.java, line 54 at r9](https://beta.reviewable.io/reviews/batfish/batfish/1154#-LAKvYIE5YGd_oCDRQy6:-LAKvYIE5YGd_oCDRQy7:bcgjvre) ([raw file](https://github.com/batfish/batfish/blob/637ecf1fe04df3e9ddf74217fa3d795853c3be03/projects/batfish/src/main/java/org/batfish/z3/AclLineMatchExprToBooleanExpr.java#L54)):*
> ```Java
> 
>   public BooleanExpr toBooleanExpr(AclLineMatchExpr aclLineMatchExpr) {
>     BooleanExpr expr = aclLineMatchExpr.accept(this);
> ```

Why this change?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1154#-:-LAKveUx9vmnAD_Pd18n:bdq1cbl)*

**Comment by anothermattbrown** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[projects/batfish/src/main/java/org/batfish/z3/AclLineMatchExprToBooleanExpr.java, line 54 at r9](https://beta.reviewable.io/reviews/batfish/batfish/1154#-LAKvYIE5YGd_oCDRQy6:-LAKw6I24Hma3lA_lVNN:b-sydqrk) ([raw file](https://github.com/batfish/batfish/blob/637ecf1fe04df3e9ddf74217fa3d795853c3be03/projects/batfish/src/main/java/org/batfish/z3/AclLineMatchExprToBooleanExpr.java#L54)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Why this change?
</blockquote></details>

debugging. I'll undo it

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1154)*

**Comment by arifogel** [comment]
Reviewed 1 of 1 files at r10.
Review status: 60 of 63 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1154)*

**Comment by arifogel** [comment]
Reviewed 3 of 3 files at r11.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1154)*

**Comment by arifogel** [comment]
Reviewed 1 of 1 files at r12.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1154)*

**Comment by arifogel** [comment]
Reviewed 1 of 1 files at r13.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1154)*

**Comment by arifogel** [comment]
Reviewed 2 of 2 files at r14.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1154)*

**Comment by anothermattbrown** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/batfish/batfish/1154#-LA6Kbr7BKehgntEZDXb:-LAL3rTC3Q8Z9dU8s9K5:b32w0x) (no related file):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

In the interest of time, let's leave this for later.
</blockquote></details>

OK

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1154)*

**Pull request merged**
