### PR TITLE
Extend TrackRoute to support querying routes in the BGP RIB

### PR DESCRIPTION
**Pull request by arifogel**

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8672)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown and @progwriter)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8672)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown and @progwriter)

**Review by progwriter — COMMENTED** [review]
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8672)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown)

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8672)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/8672#-NP_EjTvEO7GSuIgyizc:-NP_EjTvEO7GSuIgyizd:b-of254m) (no related file):*
GitHub actions stalled >30 minutes waiting for runner for code_cov and checkstyle. Merging.

___

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8672)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/8672#-NP_EjTvEO7GSuIgyizc:-NP_ExxWC2-jhQUNqVxt:b-dyckgl) (no related file):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

GitHub actions stalled >30 minutes waiting for runner for code_cov and checkstyle. Merging.
</blockquote></details>

(tested checkstyle manually)

___

**Pull request merged**
