### PR TITLE
CheckPoint: better NAT rulebase merging

### PR DESCRIPTION
**Pull request by sfraint**
Handle merging NAT rulebases even when NatSections are split across pages. Similar to what we're doing for `AccessLayer` page merging https://github.com/batfish/batfish/pull/7370

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7383)* status: all files reviewed, 1 unresolved discussion (waiting on @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/NatSection.java, line 24 at r1](https://reviewable.io/reviews/batfish/batfish/7383#-MjXf2rOEtb9gjqGED1l:-MjXf2rOEtb9gjqGED1m:bj8is5e) ([raw file](https://github.com/batfish/batfish/blob/00aed120e3330f54950d596727cabbb57907a769/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/NatSection.java#L24)):*
> ```Java
>   }
> 
>   @VisibleForTesting
> ```

no longer just for testing

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7383)* status: all files reviewed, 2 unresolved discussions (waiting on @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/parsing/CheckpointManagementParser.java, line 277 at r1](https://reviewable.io/reviews/batfish/batfish/7383#-MjXgd227aQieViMTuxy:-MjXgd233ua2bPa2vpaJ:b-9sajoc) ([raw file](https://github.com/batfish/batfish/blob/00aed120e3330f54950d596727cabbb57907a769/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/parsing/CheckpointManagementParser.java#L277)):*
> ```Java
>       if (items.size() > 1) {
>         Uid uid =
>             first instanceof NatRule ? ((NatRule) first).getUid() : ((NatSection) first).getUid();
> ```

Optional: Make a `HasUid` interface which `ManagementObject`implements and `NatRuleOrSecttion` extends. This would make the introspection and cast unnecessary.

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7383)* status: 1 of 6 files reviewed, 1 unresolved discussion (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/parsing/CheckpointManagementParser.java, line 277 at r1](https://reviewable.io/reviews/batfish/batfish/7383#-MjXgd227aQieViMTuxy:-Mj_SorAB_tMTK8jwynS:bvnrpcm) ([raw file](https://github.com/batfish/batfish/blob/00aed120e3330f54950d596727cabbb57907a769/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/parsing/CheckpointManagementParser.java#L277)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Optional: Make a `HasUid` interface which `ManagementObject`implements and `NatRuleOrSecttion` extends. This would make the introspection and cast unnecessary.
</blockquote></details>

updated

**Review by arifogel — COMMENTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7383)* status: all files reviewed, 1 unresolved discussion (waiting on @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/HasUid.java, line 5 at r2](https://reviewable.io/reviews/batfish/batfish/7383#-Mja8R4QD7-uKJwnxKkr:-Mja8R4R0O7VbMP720Ml:b-qg2z5w) ([raw file](https://github.com/batfish/batfish/blob/5270cc156785c0a86da6c5d03b870251add8fdba/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/HasUid.java#L5)):*
> ```Java
> import javax.annotation.Nonnull;
> 
> public interface HasUid {
> ```

nit: javadoc

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7383)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

**Pull request merged**
