### PR TITLE
XR: Standardize route-policy in OSPF redistribute statements

### PR DESCRIPTION
**Pull request by corinaminer**
Adds support for attaching a route-policy when redistributing BGP or EIGRP into OSPF.

### CODE REVIEW

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7157)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @dhalperi)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_ospf.g4, line 294 at r1](https://reviewable.io/reviews/batfish/batfish/7157#-MeRRO2n8A_lY5gIhMz-:-MeRRO2n8A_lY5gIhMz0:b-rwr1ve) ([raw file](https://github.com/batfish/batfish/blob/a46856a0faea0a1e5bc14cd6184bc141f292c4df/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_ospf.g4#L294)):*
> ```ANTLR
> ro_redistribute_connected
> :
>    REDISTRIBUTE CONNECTED
> ```

fyi [XR documentation](https://www.cisco.com/c/en/us/td/docs/ios_xr_sw/iosxr_r3-7/routing/command/reference/rr37ospf.html#wp1238384) indicates XR always uses `connected`, not `direct`

**Review by dhalperi — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7157)* status: all files reviewed, 2 unresolved discussions (waiting on @corinaminer)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7157#-MeRTLVX5CPlM3Oa6h98:-MeRTLVX5CPlM3Oa6h99:bmentrv) (no related file):*
I don't know if this is feasible here, but on NX-OS we unified these into actually one statement:

```
rb_af4_redistribute
:
  REDISTRIBUTE routing_instance_v4 ROUTE_MAP mapname = route_map_name NEWLINE
;
```

All of the "from protocol" lives inside `routing_instance_v4`.

Optionally, decide whether this is better than one statement per protocol?

---
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_ospf.g4, line 285 at r1](https://reviewable.io/reviews/batfish/batfish/7157#-MeRTXAq-iy9pyIdxWHu:-MeRTXAq-iy9pyIdxWHv:b-gm68rj) ([raw file](https://github.com/batfish/batfish/blob/a46856a0faea0a1e5bc14cd6184bc141f292c4df/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_ospf.g4#L285)):*
> ```
> uint_legacy
> ```
Standardization is a good time to get rid of these. 

Tag can be `route_tag`, I think.
Fairly surprised we don't have an `ospf_metric` yet, but https://www.cisco.com/c/en/us/td/docs/routers/xr12000/software/xr12k_r4-0/routing/command/reference/rr40xr12kbook_chapter4.html#wp1137182627 says 1-16777214

type can be uint8 with 1|2 valid.

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7157)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @dhalperi)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7157#-MeRTLVX5CPlM3Oa6h98:-MeRlI6a4kCVFvYxsP48:b63ffpu) (no related file):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I don't know if this is feasible here, but on NX-OS we unified these into actually one statement:

```
rb_af4_redistribute
:
  REDISTRIBUTE routing_instance_v4 ROUTE_MAP mapname = route_map_name NEWLINE
;
```

All of the "from protocol" lives inside `routing_instance_v4`.

Optionally, decide whether this is better than one statement per protocol?
</blockquote></details>

Yep, this'll work (at the low low cost of replacing the protocol-specific structure references like `OSPF_REDISTRIBUTE_BGP_ROUTE_POLICY` with a single `OSPF_REDISTRIBUTE_ROUTE_POLICY`)

---
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_ospf.g4, line 285 at r1](https://reviewable.io/reviews/batfish/batfish/7157#-MeRTXAq-iy9pyIdxWHu:-MeRlbAg3cD-jIGu68l-:bgow1o1) ([raw file](https://github.com/batfish/batfish/blob/a46856a0faea0a1e5bc14cd6184bc141f292c4df/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_ospf.g4#L285)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> uint_legacy
> ```
Standardization is a good time to get rid of these. 

Tag can be `route_tag`, I think.
Fairly surprised we don't have an `ospf_metric` yet, but https://www.cisco.com/c/en/us/td/docs/routers/xr12000/software/xr12k_r4-0/routing/command/reference/rr40xr12kbook_chapter4.html#wp1137182627 says 1-16777214

type can be uint8 with 1|2 valid.
</blockquote></details>

done. Also made an `eigrp_asn`, although it's only used for redistributing eigrp into ospf (the EIGRP grammar is all still legacy)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7157)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @corinaminer and @dhalperi)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_ospf.g4, line 293 at r2](https://reviewable.io/reviews/batfish/batfish/7157#-MeRnkF75FV_b0lt0wcp:-MeRnkF75FV_b0lt0wcq:b13lgc4) ([raw file](https://github.com/batfish/batfish/blob/72311b0241ee10151f2a0bfb851385141d3a03e2/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_ospf.g4#L293)):*
<details><summary><i alt="summary">Quoted 11 lines of code…</i></summary>

> ```
>    REDISTRIBUTE (
>       (
>          routing_instance_v4 (
>             METRIC metric = ospf_metric
>             | METRIC_TYPE type = ospf_metric_type
>             | ROUTE_POLICY policy = route_policy_name
>             | TAG tag = ospf_tag
>          )* NEWLINE
>       )
>       | routing_instance_v4_null null_rest_of_line
>    )
> ```
</details>


what's happening here?

1/ If you really want two different branches like this, introduce two+ different rules.

2/ If you want `routing_instance_v4` to be ospf-specific, prefix it with `ospf_`? Otherwise it will conflict once we do something similar inside BGP, etc.

3/ If you don't want it to be OSPF-specific, I'd move it to common and handle the "OSPF and RIP aren't valid protocols to redistribute from" issue in extraction instead.

[For context, in NX-OS we use `routing_isntance_v4` for *every* redistribution and IIRC they were all valid - so far at least.)
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_ospf.g4, line 534 at r2](https://reviewable.io/reviews/batfish/batfish/7157#-MeRnUkN1RzAvuMcVDV2:-MeRnUkN1RzAvuMcVDV3:be5e4m3) ([raw file](https://github.com/batfish/batfish/blob/72311b0241ee10151f2a0bfb851385141d3a03e2/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_ospf.g4#L534)):*
> ```
> ospf_tag: type = uint32;
> ```

Is this OSPF specific? Usually tags are cross-protocol so that, e.g., you can redistribute from OSPF into BGP and tag is preserved.

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7157)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @dhalperi)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_ospf.g4, line 293 at r2](https://reviewable.io/reviews/batfish/batfish/7157#-MeRnkF75FV_b0lt0wcp:-MeVGHf70cCssVCZzBpR:b-la6u09) ([raw file](https://github.com/batfish/batfish/blob/72311b0241ee10151f2a0bfb851385141d3a03e2/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_ospf.g4#L293)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
>    REDISTRIBUTE (
>       (
>          routing_instance_v4 (
>             METRIC metric = ospf_metric
>             | METRIC_TYPE type = ospf_metric_type
>             | ROUTE_POLICY policy = route_policy_name
>             | TAG tag = ospf_tag
>          )* NEWLINE
>       )
>       | routing_instance_v4_null null_rest_of_line
>    )
> ```

what's happening here?

1/ If you really want two different branches like this, introduce two+ different rules.

2/ If you want `routing_instance_v4` to be ospf-specific, prefix it with `ospf_`? Otherwise it will conflict once we do something similar inside BGP, etc.

3/ If you don't want it to be OSPF-specific, I'd move it to common and handle the "OSPF and RIP aren't valid protocols to redistribute from" issue in extraction instead.

[For context, in NX-OS we use `routing_isntance_v4` for *every* redistribution and IIRC they were all valid - so far at least.)
</blockquote></details>

Split into more rules.

Not sure if the exact same `routing_instance_v4` (now `rorri_protocol`) will work for redistribution in other protocols. There are some per-protocol options, e.g. `preserve-med` for BGP, that i don't know are available for redistribution in other protocols ([docs link](https://www.cisco.com/c/en/us/td/docs/routers/xr12000/software/xr12k_r4-0/routing/command/reference/rr40xr12kbook_chapter4.html#wp1137182627)). for now keeping this ospf-specific.

OSPF and RIP are valid to redistribute from, we just don't support them yet, and redistributing OSPF has protocol-specific options so can't go in the rule with the supported protocols and get handled in extraction unless we add parsing for those options.
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_ospf.g4, line 534 at r2](https://reviewable.io/reviews/batfish/batfish/7157#-MeRnUkN1RzAvuMcVDV2:-MeVFT-y5olfuhduR9s4:bj9pw3p) ([raw file](https://github.com/batfish/batfish/blob/72311b0241ee10151f2a0bfb851385141d3a03e2/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_ospf.g4#L534)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> ospf_tag: type = uint32;
> ```

Is this OSPF specific? Usually tags are cross-protocol so that, e.g., you can redistribute from OSPF into BGP and tag is preserved.
</blockquote></details>

Not ospf-specific, but i couldn't use `route_tag` because its range starts at 1 for some reason. Renamed this rule to `route_tag_from_0` and moved into common

**Review by dhalperi — COMMENTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7157)* status: all files reviewed, 1 unresolved discussion (waiting on @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java, line 7153 at r3](https://reviewable.io/reviews/batfish/batfish/7157#-MeVV0qu0tOUd1G6vNsF:-MeVV0qu0tOUd1G6vNsG:b-4uomzv) ([raw file](https://github.com/batfish/batfish/blob/18fecf4c9516a855189296dd0c948045aac8fe41/projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java#L7153)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>   private @Nonnull Optional<Long> toLong(
>       ParserRuleContext messageCtx, Route_tag_from_0Context ctx) {
>     return toLongInSpace(messageCtx, ctx, ROUTE_TAG_FROM_0_RANGE, "route tag");
>   }
> ```
</details>

nit: this one can't fail, right? All parsed values are valid.

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7157)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java, line 7153 at r3](https://reviewable.io/reviews/batfish/batfish/7157#-MeVV0qu0tOUd1G6vNsF:-MeVYTX--3eWG1MrSnt8:bv9r8oq) ([raw file](https://github.com/batfish/batfish/blob/18fecf4c9516a855189296dd0c948045aac8fe41/projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java#L7153)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
>   private @Nonnull Optional<Long> toLong(
>       ParserRuleContext messageCtx, Route_tag_from_0Context ctx) {
>     return toLongInSpace(messageCtx, ctx, ROUTE_TAG_FROM_0_RANGE, "route tag");
>   }
> ```
nit: this one can't fail, right? All parsed values are valid.
</blockquote></details>

i think that's right. I'd opt to stick to the pattern, though. if we introduced a new fallible pattern just for this case, it might get copied elsewhere for cases that can fail

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7157)* status: all files reviewed, 1 unresolved discussion (waiting on @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java, line 7153 at r3](https://reviewable.io/reviews/batfish/batfish/7157#-MeVV0qu0tOUd1G6vNsF:-MeVZRePABSPgghljHwK:bnmgvi1) ([raw file](https://github.com/batfish/batfish/blob/18fecf4c9516a855189296dd0c948045aac8fe41/projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java#L7153)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

i think that's right. I'd opt to stick to the pattern, though. if we introduced a new fallible pattern just for this case, it might get copied elsewhere for cases that can fail
</blockquote></details>

We have both patterns :)

See, e.g.,

```
  private static long toLong(Ospf_areaContext ctx) {
```

in this grammar.

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7157)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java, line 7153 at r3](https://reviewable.io/reviews/batfish/batfish/7157#-MeVV0qu0tOUd1G6vNsF:-MeVaxKq67q78Zxfz_EY:b-pqt33p) ([raw file](https://github.com/batfish/batfish/blob/18fecf4c9516a855189296dd0c948045aac8fe41/projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java#L7153)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

We have both patterns :)

See, e.g.,

```
  private static long toLong(Ospf_areaContext ctx) {
```

in this grammar.
</blockquote></details>

gotcha, done

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7157)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

**Pull request merged**
