### PR TITLE
Recognize certain Junos AS Path regexes and convert them to VI construct

### PR DESCRIPTION
**Pull request by samarthdhingra**
Performance optimization for some of Junos AS path regex patterns by converting them to existing VI construct `AsSetsMatchingRanges` . This bypasses converting these junos specific regular expression to java regular expression.  

Following Junos AS Path regex patterns are included : 
- ".\* N .\*" : "AS Path contains N"
- ".\* N" or ".\* N$" : "AS Path ends with N"
- "N .\*" or "^N .\*" : "AS Path starts with N".
- ".\* [start-end] .\*" OR ".\* start-end .\*" : "AS Path contains an ASN in range between start and end included"
- "[start-end]" or "start-end" : "AS Path matches single ASN number in range between start and end included
- "N": "AS Path matches single ASN number"

If one of the above patterns don't match, then fallback to the existing solution of converting to java regex using `AsPathRegex` 

As part of testing using `bf_session.init_snapshot_from_text(..)` for a single device config with multiple range pattern regexes, snapshot initialization time decreased from `~155s` to `~3s`.

### CODE REVIEW

**Review by anothermattbrown — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8770)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @samarthdhingra)

___
*[`projects/batfish/src/test/java/org/batfish/representation/juniper/AsPathMatchExprParserTest.java` line 97 at r1](https://reviewable.io/reviews/batfish/batfish/8770#-NbQhvXf597XZGNyGvD7:-NbQhvXf597XZGNyGvD8:biclif0) ([raw file](https://github.com/batfish/batfish/blob/f803315d8c3a306488f1b4fee01dc2a14db920bc/projects/batfish/src/test/java/org/batfish/representation/juniper/AsPathMatchExprParserTest.java#L97)):*
> ```Java
>     @Test
>     public void testAsPathMatchRegexFallback() {
>         for (String regex : new String[]{"1234", "1234?", "1234{0,1}", "12{1,4} 34", "[123-125]", "123 (56 | 78)?", "()"}) {
> ```

this pattern would be good to optimize 



_Code quote:_
```Java
"[123-125]",
```

**Comment by samarthdhingra** [comment]
> > _[Reviewable](https://reviewable.io/reviews/batfish/batfish/8770)_ status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @samarthdhingra)
> 
> _[`projects/batfish/src/test/java/org/batfish/representation/juniper/AsPathMatchExprParserTest.java` line 97 at r1](https://reviewable.io/reviews/batfish/batfish/8770#-NbQhvXf597XZGNyGvD7:-NbQhvXf597XZGNyGvD8:biclif0) ([raw file](https://github.com/batfish/batfish/blob/f803315d8c3a306488f1b4fee01dc2a14db920bc/projects/batfish/src/test/java/org/batfish/representation/juniper/AsPathMatchExprParserTest.java#L97)):_
> 
> > ```java
> >     @Test
> >     public void testAsPathMatchRegexFallback() {
> >         for (String regex : new String[]{"1234", "1234?", "1234{0,1}", "12{1,4} 34", "[123-125]", "123 (56 | 78)?", "()"}) {
> > ```
> 
> this pattern would be good to optimize
> 
> _Code quote:_
> 
> ```java
> "[123-125]",
> ```

Done. 
Added following new patterns : 

`"N"`: "AS Path matches single ASN number"
`"[start-end]"` or `"start-end"` : "AS Path matches single ASN number in range between start and end included
`".* start-end .*"`  : "AS Path contain ASN number in range between start and end included

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8770)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @samarthdhingra)

**Review by anothermattbrown — COMMENTED** [review]
Have you measured how much this speeds up parsing configs with these patterns, and how much its slow down parsing configs without them?

> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8770#-:-Nb_Mi1fEN_yTsVRwTj6:b4ehbro)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @samarthdhingra)

**Comment by samarthdhingra** [comment]
> Have you measured how much this speeds up parsing configs with these patterns, and how much its slow down parsing configs without them?
> 
> > _[Reviewable](https://reviewable.io/reviews/batfish/batfish/8770#-:-Nb_Mi1fEN_yTsVRwTj6:b4ehbro)_ status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @samarthdhingra)

Depending on the as-path regex pattern, I observe most execution time improvement if the junos regex contains range pattern .* start-end .* or .* \[start-end\] .*  (depending on the different between the ranges).

For the sample config tested using `bf_session.init_snapshot_from_text(..)` the speed up was from ~130s to ~3s

**Review by anothermattbrown — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8770#-:-Nbarr8V6yvPZh1XnJID:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @samarthdhingra)

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8770)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @samarthdhingra)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8770)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @samarthdhingra)

**Pull request merged**
