### PR TITLE
PAN: support for delete lines

### PR DESCRIPTION
**Pull request by progwriter**
Implement a pre-processor for delete lines, similar to that used for Juniper

### CODE REVIEW

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6477)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @arifogel, @progwriter, and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/grammar/palo_alto/Deleter.java, line 42 at r1](https://reviewable.io/reviews/batfish/batfish/6477#-MNeflXz6y6MgjCllsuO:-MNeflXz6y6MgjCllsuP:bufdhq9) ([raw file](https://github.com/batfish/batfish/blob/7dd8c11ad3155d79ddca56c2559725f72bb352cc/projects/batfish/src/main/java/org/batfish/grammar/palo_alto/Deleter.java#L42)):*
> ```
>    * Each time a 'delete' parse-tree is encountered:
>    * - record the words following 'delete'
>    * - for 'set' StatementTrees
> ```
do we need to do anything with other statement types, like `move`?

either way, maybe add a simple `set X`, `move X ...`, `delete X` case to the test config

**Review by arifogel — COMMENTED** [review]
> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6477)* status: all files reviewed, 1 unresolved discussion (waiting on @progwriter)

**Review by sfraint — COMMENTED** [review]
> Reviewed 1 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6477)* status: all files reviewed, 1 unresolved discussion (waiting on @progwriter)

**Review by progwriter — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6477)* status: all files reviewed, 1 unresolved discussion (waiting on @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/grammar/palo_alto/Deleter.java, line 42 at r1](https://reviewable.io/reviews/batfish/batfish/6477#-MNeflXz6y6MgjCllsuO:-MNf54Fx9s5wQpvrP9Vz:bt4sj6l) ([raw file](https://github.com/batfish/batfish/blob/7dd8c11ad3155d79ddca56c2559725f72bb352cc/projects/batfish/src/main/java/org/batfish/grammar/palo_alto/Deleter.java#L42)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
>    * Each time a 'delete' parse-tree is encountered:
>    * - record the words following 'delete'
>    * - for 'set' StatementTrees
> ```
do we need to do anything with other statement types, like `move`?

either way, maybe add a simple `set X`, `move X ...`, `delete X` case to the test config
</blockquote></details>

AFAIK delete lines only undo set lines, one cannot delete a move line, so no need to track those. 
Can you clarify what test you want to see? do you have a specific semantic result in mind or you just want to make sure we do not crash when move and delete lines are mixed?

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6477)* status: all files reviewed, 1 unresolved discussion (waiting on @progwriter)

___
*[projects/batfish/src/main/java/org/batfish/grammar/palo_alto/Deleter.java, line 42 at r1](https://reviewable.io/reviews/batfish/batfish/6477#-MNeflXz6y6MgjCllsuO:-MNfHceJA6Dw1QPDucFU:b-7hwyrg) ([raw file](https://github.com/batfish/batfish/blob/7dd8c11ad3155d79ddca56c2559725f72bb352cc/projects/batfish/src/main/java/org/batfish/grammar/palo_alto/Deleter.java#L42)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

AFAIK delete lines only undo set lines, one cannot delete a move line, so no need to track those. 
Can you clarify what test you want to see? do you have a specific semantic result in mind or you just want to make sure we do not crash when move and delete lines are mixed?
</blockquote></details>

yeah just make sure we don't have warnings/crash when there is are valid `set`, `move`, `delete` lines regarding an object

**Review by progwriter — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6477)* status: 12 of 14 files reviewed, all discussions resolved (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/grammar/palo_alto/Deleter.java, line 42 at r1](https://reviewable.io/reviews/batfish/batfish/6477#-MNeflXz6y6MgjCllsuO:-MNj5jCz03R9qaKV7xh6:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/7dd8c11ad3155d79ddca56c2559725f72bb352cc/projects/batfish/src/main/java/org/batfish/grammar/palo_alto/Deleter.java#L42)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

yeah just make sure we don't have warnings/crash when there is are valid `set`, `move`, `delete` lines regarding an object
</blockquote></details>

done

**Review by arifogel — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6477)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
