### PR TITLE
Add WorkMgrV2 call for initializing network

### PR DESCRIPTION
**Pull request by arifogel**
- POST `/v2/networks?network=n&network_prefix=np`

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8455)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @arifogel, @corinaminer, and @sfraint)

___
*[`projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrServiceV2.java` line 130 at r1](https://reviewable.io/reviews/batfish/batfish/8455#-N93LwHXD8uMolSWRAMq:-N93LwHXD8uMolSWRAMr:bldzabk) ([raw file](https://github.com/batfish/batfish/blob/3aede9552bb562898662c6cb33f54142fc72a2d5/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrServiceV2.java#L130)):*
> ```Java
>   @POST
>   @Path(CoordConstsV2.RSC_INIT_NETWORK)
>   public InitNetworkResponse initNetwork(
> ```

If this corresponds to creating a new network, why is this not simply `POST` to `/networks`?

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8455)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @arifogel, @corinaminer, and @sfraint)

___
*[`projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrServiceV2.java` line 141 at r1](https://reviewable.io/reviews/batfish/batfish/8455#-N93MCqP01vFIX4iLPz1:-N93MCqP01vFIX4iLPz2:bz0338e) ([raw file](https://github.com/batfish/batfish/blob/3aede9552bb562898662c6cb33f54142fc72a2d5/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrServiceV2.java#L141)):*
> ```Java
>         firstNonNull(networkName, ""),
>         CoordConstsV2.QP_NETWORK_PREFIX,
>         firstNonNull(networkPrefix, ""));
> ```

This ought not to be necessary - the Grizzly server has request logging we can turn on if we want, right?



_Code quote:_
```Java
    _logger.infof(
        "%s %s=%s %s=%s\n",
        CoordConstsV2.RSC_INIT_NETWORK,
        CoordConstsV2.QP_NETWORK_NAME,
        firstNonNull(networkName, ""),
        CoordConstsV2.QP_NETWORK_PREFIX,
        firstNonNull(networkPrefix, ""));
```
___
*[`projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrServiceV2.java` line 147 at r1](https://reviewable.io/reviews/batfish/batfish/8455#-N93M4rVAK-rCvBJJEIF:-N93M4rVAK-rCvBJJEIG:buzus13) ([raw file](https://github.com/batfish/batfish/blob/3aede9552bb562898662c6cb33f54142fc72a2d5/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrServiceV2.java#L147)):*
> ```Java
>               "Must supply one of %s or %s as query parameter",
>               CoordConstsV2.QP_NETWORK_NAME, CoordConstsV2.QP_NETWORK_PREFIX));
>     }
> ```

Why would one of these be required? Couldn't we default prefix to something like net_ or network_?



_Code quote:_
```Java
    if (networkName == null && networkPrefix == null) {
      throw new BadRequestException(
          String.format(
              "Must supply one of %s or %s as query parameter",
              CoordConstsV2.QP_NETWORK_NAME, CoordConstsV2.QP_NETWORK_PREFIX));
    }
```

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8455)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @corinaminer, @dhalperi, and @sfraint)

___
*[`projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrServiceV2.java` line 130 at r1](https://reviewable.io/reviews/batfish/batfish/8455#-N93LwHXD8uMolSWRAMq:-N93a59t4kWqQU6cxpGY:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/3aede9552bb562898662c6cb33f54142fc72a2d5/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrServiceV2.java#L130)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

If this corresponds to creating a new network, why is this not simply `POST` to `/networks`?
</blockquote></details>

done
___
*[`projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrServiceV2.java` line 141 at r1](https://reviewable.io/reviews/batfish/batfish/8455#-N93MCqP01vFIX4iLPz1:-N93aA0i0AW_K_jaXZeK:bfo3j1c) ([raw file](https://github.com/batfish/batfish/blob/3aede9552bb562898662c6cb33f54142fc72a2d5/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrServiceV2.java#L141)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

This ought not to be necessary - the Grizzly server has request logging we can turn on if we want, right?
</blockquote></details>

I ported from workmgrservice, but fair point.
Removed logging, and moved the created network log inside work manager
I assume the same argument applies to jersey error logging.

I moved the created network log message to `WorkMgr`, but can remove if you feel that is warranted.
___
*[`projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrServiceV2.java` line 147 at r1](https://reviewable.io/reviews/batfish/batfish/8455#-N93M4rVAK-rCvBJJEIF:-N93a4By4Q-QtFWHJX9k:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/3aede9552bb562898662c6cb33f54142fc72a2d5/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrServiceV2.java#L147)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Why would one of these be required? Couldn't we default prefix to something like net_ or network_?
</blockquote></details>

done

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 4 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8455)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @arifogel, @corinaminer, and @sfraint)

___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/common/CoordConstsV2.java` line 13 at r2](https://reviewable.io/reviews/batfish/batfish/8455#-N93kBaJDEYEOUaJqpj8:-N93kBaKEXMKLl8FRVlQ:buhz002) ([raw file](https://github.com/batfish/batfish/blob/9101cbc3e5b8b72c9e1e825375cc130a0827523a/projects/batfish-common-protocol/src/main/java/org/batfish/common/CoordConstsV2.java#L13)):*
> ```Java
> 
>   public static final String QP_MAX_SUGGESTIONS = "maxsuggestions";
>   public static final String QP_NETWORK_NAME = "network_name";
> ```

name and name_prefix?

The `network` is implicit based on the resource URL.



_Code quote:_
```Java
network_name
```
___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/InitNetworkResponse.java` line 35 at r2](https://reviewable.io/reviews/batfish/batfish/8455#-N93kKsfAiDhCrTsgvt1:-N93kKsfAiDhCrTsgvt2:b2zayxa) ([raw file](https://github.com/batfish/batfish/blob/9101cbc3e5b8b72c9e1e825375cc130a0827523a/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/InitNetworkResponse.java#L35)):*
> ```Java
>   }
> 
>   private static final String PROP_OUTPUT_NETWORK_NAME = "outputNetworkName";
> ```

(10+yo advice follows, be skeptical and find your own preferred style guide)

IIRC, it is usual in a CRUD REST service the result of a successful Create (`POST`) will be the same as the result of a successful Read (`GET`) of the created resource. If that's right, why deviate from there here?



_Code quote:_
```Java
outputNetworkName
```

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8455)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @corinaminer, @dhalperi, and @sfraint)

___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/common/CoordConstsV2.java` line 13 at r2](https://reviewable.io/reviews/batfish/batfish/8455#-N93kBaJDEYEOUaJqpj8:-N93mqbW1iUag4kyrz7u:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/9101cbc3e5b8b72c9e1e825375cc130a0827523a/projects/batfish-common-protocol/src/main/java/org/batfish/common/CoordConstsV2.java#L13)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

name and name_prefix?

The `network` is implicit based on the resource URL.
</blockquote></details>

done
___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/InitNetworkResponse.java` line 35 at r2](https://reviewable.io/reviews/batfish/batfish/8455#-N93kKsfAiDhCrTsgvt1:-N93mvFOEpPxxlpZuFQC:b-qz0cxy) ([raw file](https://github.com/batfish/batfish/blob/9101cbc3e5b8b72c9e1e825375cc130a0827523a/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/InitNetworkResponse.java#L35)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

(10+yo advice follows, be skeptical and find your own preferred style guide)

IIRC, it is usual in a CRUD REST service the result of a successful Create (`POST`) will be the same as the result of a successful Read (`GET`) of the created resource. If that's right, why deviate from there here?
</blockquote></details>

Read up a bit, and modified accordingly.
The POST output should be a 201 with a Location header containing the URI of the newly created resource.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8455)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer and @sfraint)

**Review by arifogel — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8455)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer and @sfraint)

**Pull request merged**
