### PR TITLE
IOS: update EIGRP redistribution policies

### PR DESCRIPTION
**Pull request by progwriter**
Switch from a per-neighbor redistribution to a global redistribution model.

Goal: stop "baking in" the EIGRP process _redistribution_ policy into a per-neighbor _filtering_ policy. This is/was a legacy way of doing things, and in this case we can easily fix it for one vendor before propagating the pattern to other vendors (like NXOS).

In dataplane code: execute redistribution policy on redistribution and keep the resulting routes (both in the the RIB and as a delta). Per neighbor policies now only execute the filtering (e.g., defined via distribute lists). This is a potential speedup because we do not process the same route N times (where N is number of neighbors)

In vendor code (Cisco IOS specifically): stop inlining export policy into neighbor policies. We already had infrastructure for process-global policy, it was just unused.

Note: I did include 1 rename exportPolicy -> redistributionPolicy; my hope is this should make it easier to reason about the code changes.

### CODE REVIEW

**Review by corinaminer — COMMENTED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6405)* status: all files reviewed, 3 unresolved discussions (waiting on @progwriter)

___
*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 1740 at r1](https://reviewable.io/reviews/batfish/batfish/6405#-MLnVE2T0tOwx37OXrtn:-MLnVE2U0-oURx_fumtt:b-oy1jdb) ([raw file](https://github.com/batfish/batfish/blob/089d8da64ca6350ba5f01f86294d0d9ccdb57a82/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L1740)):*
> ```Java
> 
>       List<If> redistributeAndAllowEigrpFromSelfAsn =
>           clearFalseStatementsAndAddMatchOwnAsn(
> ```

is this method now unused?
___
*[projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java, line 2742 at r1](https://reviewable.io/reviews/batfish/batfish/6405#-MLnWKXn5bfb4OXWphgS:-MLnWKXn5bfb4OXWphgT:b-dmc95e) ([raw file](https://github.com/batfish/batfish/blob/4a627e08e80650b90b249e9d4566842d8b75547c/projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java#L2742)):*
> ```Java
>         EigrpExternalRoute.builder(),
>         eigrpProcess1,
>         Direction.IN);
> ```

doesn't seem like this actually tests the redistribution policy, should at least check the result and probably test that the content of the policy is as expected
___
*[projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java, line 2752 at r1](https://reviewable.io/reviews/batfish/batfish/6405#-MLnWqlY9MmoOcApDCer:-MLnWqlY9MmoOcApDCes:b-vn9ly7) ([raw file](https://github.com/batfish/batfish/blob/4a627e08e80650b90b249e9d4566842d8b75547c/projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java#L2752)):*
> ```Java
>                 .setNetwork(Prefix.parse("172.21.30.0/24"))
>                 .setEigrpMetric(metric)
>                 .setProcessAsn(1L)
> ```

is this change intentional? if so, why is it necessary?

**Review by progwriter — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6405)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 1740 at r1](https://reviewable.io/reviews/batfish/batfish/6405#-MLnVE2T0tOwx37OXrtn:-MLo1rju8zda24yLEt_x:b-b13cp7) ([raw file](https://github.com/batfish/batfish/blob/089d8da64ca6350ba5f01f86294d0d9ccdb57a82/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L1740)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

is this method now unused?
</blockquote></details>

yeah, thanks
___
*[projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java, line 2742 at r1](https://reviewable.io/reviews/batfish/batfish/6405#-MLnWKXn5bfb4OXWphgS:-MLo1t1-8NN8-Xcjsn-O:b-q5296b) ([raw file](https://github.com/batfish/batfish/blob/4a627e08e80650b90b249e9d4566842d8b75547c/projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java#L2742)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

doesn't seem like this actually tests the redistribution policy, should at least check the result and probably test that the content of the policy is as expected
</blockquote></details>

:facepalm: added assertion
also tried to clear up the comments
___
*[projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java, line 2752 at r1](https://reviewable.io/reviews/batfish/batfish/6405#-MLnWqlY9MmoOcApDCer:-MLo1yeT0YWDXd82ABje:brcjsez) ([raw file](https://github.com/batfish/batfish/blob/4a627e08e80650b90b249e9d4566842d8b75547c/projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java#L2752)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

is this change intentional? if so, why is it necessary?
</blockquote></details>

yes. this policy no longer does redistribution so it can't allow foreign ASNs. modified the comment.

**Review by corinaminer — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6405)* status: all files reviewed, 1 unresolved discussion (waiting on @progwriter)

___
*[projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java, line 2764 at r2](https://reviewable.io/reviews/batfish/batfish/6405#-MLoC_d801yGb4rhnjgX:-MLoC_d99HGiICrL_TEF:b3eg7et) ([raw file](https://github.com/batfish/batfish/blob/f6657d5fdb13c5d03cf14508da1b7c77406bdd67/projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java#L2764)):*
> ```Java
>                 .setNetwork(Prefix.parse("172.21.31.0/24"))
>                 .setEigrpMetric(metric)
>                 .setProcessAsn(2L)
> ```

i see, so i think this ASN also needs to change in order to confirm the route is denied by the distribute list (rather than denied because of ASN mismatch)

**Review by progwriter — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6405)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java, line 2764 at r2](https://reviewable.io/reviews/batfish/batfish/6405#-MLoC_d801yGb4rhnjgX:-MLoURUeAHehFW6KaGpt:b-th2zke) ([raw file](https://github.com/batfish/batfish/blob/f6657d5fdb13c5d03cf14508da1b7c77406bdd67/projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java#L2764)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

i see, so i think this ASN also needs to change in order to confirm the route is denied by the distribute list (rather than denied because of ASN mismatch)
</blockquote></details>

good call, done

**Review by progwriter — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6405)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
