### PR TITLE
IOS: make router ospf > area LL1

### PR DESCRIPTION
**Pull request by dhalperi**
Remove the IOS-XR block syntax and combine the child lines that all start with `area`.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6860)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @arifogel)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_ospf.g4, line 27 at r1](https://reviewable.io/reviews/batfish/batfish/6860#-MXdFOjX8J6E9_0Uii1c:-MXdFOjX8J6E9_0Uii1d:b-nxttsv) ([raw file](https://github.com/batfish/batfish/blob/c7f97284e92c1f466657db305c41d86cea246051/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_ospf.g4#L27)):*
<details><summary><i alt="summary">Quoted 14 lines of code…</i></summary>

> ```
> ro_area
> :
>    AREA
>    (
>       area_int = dec
>       | area_ip = IP_ADDRESS
>    ) NEWLINE
>    (
>       ro_common
>       | roa_cost
>       | roa_interface
>       | roa_network_null
>       | roa_range
>    )*
> ```
</details>


FYI the old `ro_area` and `roa_*` are the IOS-XR block syntax.

I removed them, created a new `ro_area`, and then made all the existing `ro_area_<foo>` that were children of `router ospf` now children of the new `ro_area` (with the `AREA <area>` part removed to become LL1).

**Review by arifogel — COMMENTED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6860)* status: all files reviewed, 2 unresolved discussions (waiting on @corinaminer, @dhalperi, and @sfraint)

___
*[tests/parsing-tests/unit-tests-vimodel.ref, line 0 at r1](https://reviewable.io/reviews/batfish/batfish/6860#-MXdLPuIEJ4uAQNzWKnO:-MXdLPuIEJ4uAQNzWKnP:b-3t0bli) ([raw file](https://github.com/batfish/batfish/blob/03a703ef242c46131db7baae12b36f41812d1d50/tests/parsing-tests/unit-tests-vimodel.ref#L0)):*
What's with the route filter list changes? They seem to have lost a lot of content.
___
*[tests/parsing-tests/networks/unit-tests/configs/cisco_ospf, line 77 at r1](https://reviewable.io/reviews/batfish/batfish/6860#-MXdL_00C9ZoMxxG6QQk:-MXdL_00C9ZoMxxG6QQl:bopacr6) ([raw file](https://github.com/batfish/batfish/blob/c7f97284e92c1f466657db305c41d86cea246051/tests/parsing-tests/networks/unit-tests/configs/cisco_ospf#L77)):*
> ```
>   timers throttle lsa 0 50 5000
>   timers throttle spf 50 50 5000
>   area 0
> ```

Is this the reason for the loss of route-filter lists in vi-model? Can you port these lines to the right syntax (the ones that survive)?

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6860)* status: all files reviewed, 2 unresolved discussions (waiting on @arifogel, @corinaminer, and @sfraint)

___
*[tests/parsing-tests/unit-tests-vimodel.ref, line  at r1](https://reviewable.io/reviews/batfish/batfish/6860#-MXdLPuIEJ4uAQNzWKnO:-MXdM5xK2L1iJ9Gpvlj6:b-sasuo8) ([raw file](https://github.com/batfish/batfish/blob/03a703ef242c46131db7baae12b36f41812d1d50/tests/parsing-tests/unit-tests-vimodel.ref#L)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

What's with the route filter list changes? They seem to have lost a lot of content.
</blockquote></details>

Deleting XR syntax.
___
*[tests/parsing-tests/networks/unit-tests/configs/cisco_ospf, line 77 at r1](https://reviewable.io/reviews/batfish/batfish/6860#-MXdL_00C9ZoMxxG6QQk:-MXdM7dgE3nDsG513Uoi:b-j9d2sr) ([raw file](https://github.com/batfish/batfish/blob/c7f97284e92c1f466657db305c41d86cea246051/tests/parsing-tests/networks/unit-tests/configs/cisco_ospf#L77)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Is this the reason for the loss of route-filter lists in vi-model? Can you port these lines to the right syntax (the ones that survive)?
</blockquote></details>

Just deleting XR syntax. We can add an XR ref test if we want, not sure why this is useful to add back.

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6860)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer and @sfraint)

___
*[tests/parsing-tests/unit-tests-vimodel.ref, line  at r1](https://reviewable.io/reviews/batfish/batfish/6860#-MXdLPuIEJ4uAQNzWKnO:-MXdNbGT-EuzeP17R89k:bm52g8x) ([raw file](https://github.com/batfish/batfish/blob/03a703ef242c46131db7baae12b36f41812d1d50/tests/parsing-tests/unit-tests-vimodel.ref#L)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Deleting XR syntax.
</blockquote></details>

Actually, it's even better than that. The area, when not expressed as a number, was being taken from the range instead of from the area.

The deleted area is 1.2.3.0, which comes from `area 0.0.0.0 range 1.2.3.0/24 ...`.

So this is a bug fix.

**Comment by dhalperi** [comment]
___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 7557 at r1](https://reviewable.io/reviews/batfish/batfish/6860#-MXdNxS9A-qBiisr-zJh:-MXdNxS9A-qBiisr-zJi:b3wb1zq) ([raw file](https://github.com/batfish/batfish/blob/c7f97284e92c1f466657db305c41d86cea246051/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L7557)):*
> ```
> toIp(ctx.area_ip).asLong();
> ```

This is the bug being fixed: `area_ip` is the prefix being summarized, not the area number.

**Comment by dhalperi** [comment]
___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 7562 at r1](https://reviewable.io/reviews/batfish/batfish/6860#-MXdO4C9-r28gEOBSwhc:-MXdO4C9-r28gEOBSwhd:b7fmjl5) ([raw file](https://github.com/batfish/batfish/blob/c7f97284e92c1f466657db305c41d86cea246051/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L7562)):*
> ```
> area_ip
> ```
FYI you can see its use down here.

**Pull request merged**
