### PR TITLE
ACL tracing API

### PR DESCRIPTION
**Pull request by arifogel**
- API calls and data structures to trace action of `IpAccessList`s and `IpSpace`s on a `Flow`

### CODE REVIEW

**Comment by anothermattbrown** [comment]
Reviewed 1 of 32 files at r1, 4 of 9 files at r2.
Review status: 5 of 32 files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/HeaderSpace.java, line 1432 at r2](https://reviewable.io/reviews/batfish/batfish/1478#-LDEWa1z2HL-0nGFgdRW:-LDEWa1z2HL-0nGFgdRX:b-8y81r9) ([raw file](https://github.com/batfish/batfish/blob/af8e018c2addf96746d08289a76b95bb4b89e643/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/HeaderSpace.java#L1432)):*
> ```Java
>   }
> 
>   public boolean trace(AclTracer aclTracer) {
> ```

this seems a strange place to put this logic. It would be better to have all tracing logic in one place.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpAccessList.java, line 124 at r2](https://reviewable.io/reviews/batfish/batfish/1478#-LDEX2we4SeBQhBXxbbE:-LDEX2we4SeBQhBXxbbF:bu6a3yb) ([raw file](https://github.com/batfish/batfish/blob/af8e018c2addf96746d08289a76b95bb4b89e643/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpAccessList.java#L124)):*
> ```Java
>   }
> 
>   public AclTrace trace(
> ```

this should probably live in AclTracer

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpAccessList.java, line 134 at r2](https://reviewable.io/reviews/batfish/batfish/1478#-LDEZNNT6Jv9lOprgNLF:-LDEZNNT6Jv9lOprgNLG:b-ejnhgp) ([raw file](https://github.com/batfish/batfish/blob/af8e018c2addf96746d08289a76b95bb4b89e643/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpAccessList.java#L134)):*
> ```Java
>   }
> 
>   public boolean trace(AclTracer tracer) {
> ```

this too

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclTracer.java, line 18 at r2](https://reviewable.io/reviews/batfish/batfish/1478#-LDEYXTyClL0tMWa773D:-LDEYXTyClL0tMWa773E:bc23jqm) ([raw file](https://github.com/batfish/batfish/blob/af8e018c2addf96746d08289a76b95bb4b89e643/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclTracer.java#L18)):*
> ```Java
> import org.batfish.datamodel.visitors.IpSpaceTracer;
> 
> public class AclTracer extends Evaluator {
> ```

javadoc please. In particular, what parts of evaluator are being modified? 

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclTracer.java, line 44 at r2](https://reviewable.io/reviews/batfish/batfish/1478#-LDEYw4IEUxNGVfEXpwT:-LDEYw4IEUxNGVfEXpwU:bu56hit) ([raw file](https://github.com/batfish/batfish/blob/af8e018c2addf96746d08289a76b95bb4b89e643/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclTracer.java#L44)):*
> ```Java
> 
>   @Override
>   public Boolean visitAndMatchExpr(AndMatchExpr andMatchExpr) {
> ```

this looks identical to the overridden superclass method. might be true of other methods too

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/DefaultDeniedByAclIpSpace.java, line 8 at r2](https://reviewable.io/reviews/batfish/batfish/1478#-LDEXJyH7cU010Yxwjue:-LDEXJyH7cU010Yxwjuf:b-ruzz6v) ([raw file](https://github.com/batfish/batfish/blob/af8e018c2addf96746d08289a76b95bb4b89e643/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/DefaultDeniedByAclIpSpace.java#L8)):*
> ```Java
> import javax.annotation.Nonnull;
> 
> public class DefaultDeniedByAclIpSpace implements TraceEvent {
> ```

can this be final?

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/DefaultDeniedByIpAccessList.java, line 8 at r2](https://reviewable.io/reviews/batfish/batfish/1478#-LDEXXlm3FZwdNcQKTda:-LDEXXlm3FZwdNcQKTdb:b-qsyuya) ([raw file](https://github.com/batfish/batfish/blob/af8e018c2addf96746d08289a76b95bb4b89e643/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/DefaultDeniedByIpAccessList.java#L8)):*
> ```Java
> import javax.annotation.Nonnull;
> 
> public class DefaultDeniedByIpAccessList implements TraceEvent {
> ```

final?

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/DeniedByAclIpSpaceLine.java, line 9 at r2](https://reviewable.io/reviews/batfish/batfish/1478#-LDEXe345W2hBeO8Yrvk:-LDEXe345W2hBeO8Yrvl:b-qsyuya) ([raw file](https://github.com/batfish/batfish/blob/af8e018c2addf96746d08289a76b95bb4b89e643/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/DeniedByAclIpSpaceLine.java#L9)):*
> ```Java
> import javax.annotation.Nonnull;
> 
> public class DeniedByAclIpSpaceLine implements TraceEvent {
> ```

final?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1478)*

**Comment by arifogel** [comment]
Review status: 1 of 31 files reviewed at latest revision, 8 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/HeaderSpace.java, line 1432 at r2](https://reviewable.io/reviews/batfish/batfish/1478#-LDEWa1z2HL-0nGFgdRW:-LDEeP2f7apup7cFRSoL:b-84847m) ([raw file](https://github.com/batfish/batfish/blob/af8e018c2addf96746d08289a76b95bb4b89e643/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/HeaderSpace.java#L1432)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

this seems a strange place to put this logic. It would be better to have all tracing logic in one place.
</blockquote></details>

Moved

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclTracer.java, line 18 at r2](https://reviewable.io/reviews/batfish/batfish/1478#-LDEYXTyClL0tMWa773D:-LDEgaUO0eroHB95svjh:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/af8e018c2addf96746d08289a76b95bb4b89e643/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclTracer.java#L18)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

javadoc please. In particular, what parts of evaluator are being modified? 
</blockquote></details>

Done.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclTracer.java, line 44 at r2](https://reviewable.io/reviews/batfish/batfish/1478#-LDEYw4IEUxNGVfEXpwT:-LDEfmmR4a6qFF8olIpC:b605fop) ([raw file](https://github.com/batfish/batfish/blob/af8e018c2addf96746d08289a76b95bb4b89e643/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclTracer.java#L44)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

this looks identical to the overridden superclass method. might be true of other methods too
</blockquote></details>

Removed code identical to superclass

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/DefaultDeniedByAclIpSpace.java, line 8 at r2](https://reviewable.io/reviews/batfish/batfish/1478#-LDEXJyH7cU010Yxwjue:-LDEgenrEzC72_sKfo08:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/af8e018c2addf96746d08289a76b95bb4b89e643/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/DefaultDeniedByAclIpSpace.java#L8)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

can this be final?
</blockquote></details>

Done.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/DefaultDeniedByIpAccessList.java, line 8 at r2](https://reviewable.io/reviews/batfish/batfish/1478#-LDEXXlm3FZwdNcQKTda:-LDEgwJP1Z50jpOB11AJ:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/af8e018c2addf96746d08289a76b95bb4b89e643/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/DefaultDeniedByIpAccessList.java#L8)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

final?
</blockquote></details>

Done.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/DeniedByAclIpSpaceLine.java, line 9 at r2](https://reviewable.io/reviews/batfish/batfish/1478#-LDEXe345W2hBeO8Yrvk:-LDEgxFu705gzVPS9wpx:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/af8e018c2addf96746d08289a76b95bb4b89e643/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/DeniedByAclIpSpaceLine.java#L9)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

final?
</blockquote></details>

Done.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpAccessList.java, line 124 at r2](https://reviewable.io/reviews/batfish/batfish/1478#-LDEX2we4SeBQhBXxbbE:-LDEfQyW6VaH0zLGgCoF:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/af8e018c2addf96746d08289a76b95bb4b89e643/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpAccessList.java#L124)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

this should probably live in AclTracer
</blockquote></details>

Done.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpAccessList.java, line 134 at r2](https://reviewable.io/reviews/batfish/batfish/1478#-LDEZNNT6Jv9lOprgNLF:-LDEfRDI28sSBkJDPkP2:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/af8e018c2addf96746d08289a76b95bb4b89e643/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpAccessList.java#L134)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

this too
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1478)*

**Comment by anothermattbrown** [comment]
Reviewed 16 of 32 files at r1, 10 of 14 files at r3.
Review status: 26 of 31 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/HeaderSpace.java, line 563 at r3](https://reviewable.io/reviews/batfish/batfish/1478#-LDHym8U1Y4EMW21oQk3:-LDHym8VC4QjMKTGdoUk:be00t2d) ([raw file](https://github.com/batfish/batfish/blob/e081bf8a5a53a41c7a0983c7646fe3d165edfc97/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/HeaderSpace.java#L563)):*
> ```Java
>   }
> 
>   public static boolean rangesContain(Collection<SubRange> ranges, int num) {
> ```

this should also live somewhere else.

why not do a one-liner with `Stream.anyMatch`?

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/visitors/IpSpaceTracer.java, line 18 at r3](https://reviewable.io/reviews/batfish/batfish/1478#-LDI-64SC2WkSXnacq_1:-LDI-64SC2WkSXnacq_2:bc5s8bg) ([raw file](https://github.com/batfish/batfish/blob/e081bf8a5a53a41c7a0983c7646fe3d165edfc97/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/visitors/IpSpaceTracer.java#L18)):*
> ```Java
> import org.batfish.datamodel.acl.AclTracer;
> 
> public class IpSpaceTracer implements GenericIpSpaceVisitor<Boolean> {
> ```

Javadoc? In particular, what is the meaning of the `Boolean` return value?

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/TraceEventMatchers.java, line 3 at r3](https://reviewable.io/reviews/batfish/batfish/1478#-LDI-nacEvItL89cxMqL:-LDI-nacEvItL89cxMqM:byquu61) ([raw file](https://github.com/batfish/batfish/blob/e081bf8a5a53a41c7a0983c7646fe3d165edfc97/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/TraceEventMatchers.java#L3)):*
> ```Java
> package org.batfish.datamodel.matchers;
> 
> final class TraceEventMatchers {}
> ```

Do we need this?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1478)*

**Comment by arifogel** [comment]
Review status: 24 of 31 files reviewed at latest revision, 3 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/HeaderSpace.java, line 563 at r3](https://reviewable.io/reviews/batfish/batfish/1478#-LDHym8U1Y4EMW21oQk3:-LDITTMV7xRwnBIa4u0c:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/e081bf8a5a53a41c7a0983c7646fe3d165edfc97/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/HeaderSpace.java#L563)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

this should also live somewhere else.

why not do a one-liner with `Stream.anyMatch`?
</blockquote></details>

Done.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/visitors/IpSpaceTracer.java, line 18 at r3](https://reviewable.io/reviews/batfish/batfish/1478#-LDI-64SC2WkSXnacq_1:-LDIUG3w-5DEHZLsvG5z:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/e081bf8a5a53a41c7a0983c7646fe3d165edfc97/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/visitors/IpSpaceTracer.java#L18)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

Javadoc? In particular, what is the meaning of the `Boolean` return value?
</blockquote></details>

Done.

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/TraceEventMatchers.java, line 3 at r3](https://reviewable.io/reviews/batfish/batfish/1478#-LDI-nacEvItL89cxMqL:-LDIUQmS4QEb0URXoEjO:ba3dfob) ([raw file](https://github.com/batfish/batfish/blob/e081bf8a5a53a41c7a0983c7646fe3d165edfc97/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/TraceEventMatchers.java#L3)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

Do we need this?
</blockquote></details>

Removed

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1478)*

**Comment by anothermattbrown** [comment]
:lgtm:

---

Reviewed 3 of 14 files at r3, 5 of 5 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1478#-:-LDInJBm2g28E1TEJjvI:bnfp4nl)*

**Pull request merged**
