### PR TITLE
Recompute kernel routes every dataplane iteration

### PR DESCRIPTION
**Pull request by arifogel**
- fix but where kernel routes depending on ip ownership do not take into account IpOwners changing mid dataplane

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8023)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @arifogel, @corinaminer, and @dhalperi)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/8023#-MvVexHwAFQFCFbjZgzA:-MvVexHxBs6PsTbzg-Cf:b-6noucm) (no related file):*
This is broken. No BGP routes are being created from kernel routes. need to fix and add more tests.

---

**Review by corinaminer — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8023)* status: all files reviewed, 4 unresolved discussions (waiting on @arifogel)

___
*[projects/batfish/src/test/java/org/batfish/dataplane/A10KernelRouteTest.java, line 52 at r2](https://reviewable.io/reviews/batfish/batfish/8023#-MvWQ8mI4abCQ5jkrU4u:-MvWQ8mI4abCQ5jkrU4v:b-thprpc) ([raw file](https://github.com/batfish/batfish/blob/574e82813d89d42b74590f71afcde1bd608771f9/projects/batfish/src/test/java/org/batfish/dataplane/A10KernelRouteTest.java#L52)):*
> ```Java
>    *    <=================>
>    *    ethernet1 ethernet1
>    *    .2  10.0.1.0/24  .1
> ```

nit: r1 has .1s, r2 has .2s
___
*[projects/batfish/src/test/java/org/batfish/dataplane/A10KernelRouteTest.java, line 94 at r2](https://reviewable.io/reviews/batfish/batfish/8023#-MvWQEN71xk7u-lB9jLI:-MvWQEN71xk7u-lB9jLJ:b-uvgmja) ([raw file](https://github.com/batfish/batfish/blob/574e82813d89d42b74590f71afcde1bd608771f9/projects/batfish/src/test/java/org/batfish/dataplane/A10KernelRouteTest.java#L94)):*
> ```Java
>             .filter(KernelRoute.class::isInstance)
>             .collect(ImmutableSet.toImmutableSet()),
>         empty());
> ```

To confirm, r2 doesn't have the kernel route because it doesn't own the floating IP?

The learned BGP route should show up in r2's main rib, right? Could assert on that. (btw, cleaner to assert on contents of `getRoutes(KERNEL_PREFIX)` than `getRoutes()`, especially if you want to check the bgp route)
___
*[projects/batfish/src/test/java/org/batfish/dataplane/ibdp/IncrementalBdpEngineTest.java, line 367 at r2](https://reviewable.io/reviews/batfish/batfish/8023#-MvWUzrFBDP7UzB2FH6V:-MvWUzrFBDP7UzB2FH6W:b-lq3fjq) ([raw file](https://github.com/batfish/batfish/blob/574e82813d89d42b74590f71afcde1bd608771f9/projects/batfish/src/test/java/org/batfish/dataplane/ibdp/IncrementalBdpEngineTest.java#L367)):*
> ```Java
>     r1.setTrackingGroups(
>         ImmutableMap.of(
>             "failReach", NegatedTrackMethod.of(TrackReachability.of(r1Ip, DEFAULT_VRF_NAME))));
> ```

Did you confirm that there's a point during dataplaning when r2 has the kernel route and r1 does not? I can't think of a way to pin that down in the test. Seems strange that r1 would ever be unable to reach r1Ip, though.
___
*[projects/batfish/src/test/java/org/batfish/dataplane/ibdp/IncrementalBdpEngineTest.java, line 392 at r2](https://reviewable.io/reviews/batfish/batfish/8023#-MvWTUtNApwywIMLt22k:-MvWTUtNApwywIMLt22l:b25q8mj) ([raw file](https://github.com/batfish/batfish/blob/574e82813d89d42b74590f71afcde1bd608771f9/projects/batfish/src/test/java/org/batfish/dataplane/ibdp/IncrementalBdpEngineTest.java#L392)):*
> ```Java
>         .setOwner(r2)
>         .setVrf(v2)
>         .setAddress(r1Address)
> ```

should use `r2Address`
___
*[projects/batfish/src/test/java/org/batfish/dataplane/ibdp/IncrementalBdpEngineTest.java, line 405 at r2](https://reviewable.io/reviews/batfish/batfish/8023#-MvWTs9DEU3DF8FmrWGa:-MvWTs9DEU3DF8FmrWGb:b-i54a1r) ([raw file](https://github.com/batfish/batfish/blob/574e82813d89d42b74590f71afcde1bd608771f9/projects/batfish/src/test/java/org/batfish/dataplane/ibdp/IncrementalBdpEngineTest.java#L405)):*
> ```Java
>                 initialTopologyContext,
>                 ImmutableSet.of(),
>                 new TestIpOwners(configurations))
> ```

you confirmed that `TestIpOwners` handles virtual IP ownership correctly?

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8023)* status: 7 of 9 files reviewed, 3 unresolved discussions (waiting on @corinaminer)

___
*[projects/batfish/src/test/java/org/batfish/dataplane/A10KernelRouteTest.java, line 52 at r2](https://reviewable.io/reviews/batfish/batfish/8023#-MvWQ8mI4abCQ5jkrU4u:-MvWWmbrEdEgF93nrm-k:b-7ql1td) ([raw file](https://github.com/batfish/batfish/blob/574e82813d89d42b74590f71afcde1bd608771f9/projects/batfish/src/test/java/org/batfish/dataplane/A10KernelRouteTest.java#L52)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

nit: r1 has .1s, r2 has .2s
</blockquote></details>

fixed
___
*[projects/batfish/src/test/java/org/batfish/dataplane/A10KernelRouteTest.java, line 94 at r2](https://reviewable.io/reviews/batfish/batfish/8023#-MvWQEN71xk7u-lB9jLI:-MvWWnmE3FpuTYPLQZTr:bb2wqxk) ([raw file](https://github.com/batfish/batfish/blob/574e82813d89d42b74590f71afcde1bd608771f9/projects/batfish/src/test/java/org/batfish/dataplane/A10KernelRouteTest.java#L94)):*
> To confirm, r2 doesn't have the kernel route because it doesn't own the floating IP?

Correct.

> The learned BGP route should show up in r2's main rib, right? Could assert on that. (btw, cleaner to assert on contents of getRoutes(KERNEL_PREFIX) than getRoutes(), especially if you want to check the bgp route)

Done.
___
*[projects/batfish/src/test/java/org/batfish/dataplane/ibdp/IncrementalBdpEngineTest.java, line 367 at r2](https://reviewable.io/reviews/batfish/batfish/8023#-MvWUzrFBDP7UzB2FH6V:-MvWXow47XOaiKN2L4Sq:b4124kf) ([raw file](https://github.com/batfish/batfish/blob/574e82813d89d42b74590f71afcde1bd608771f9/projects/batfish/src/test/java/org/batfish/dataplane/ibdp/IncrementalBdpEngineTest.java#L367)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Did you confirm that there's a point during dataplaning when r2 has the kernel route and r1 does not? I can't think of a way to pin that down in the test. Seems strange that r1 would ever be unable to reach r1Ip, though.
</blockquote></details>

Whether there is a transient period where r2 has the kernel route is actually immaterial. 

The reason reachability track is used is because it will always evaluate to false until after IGP. The idea is that if the test passes, that means that we are correctly computing the kernel routes from the result of mid-dataplane IpOwners, rather than initial IpOwners. That is the whole point of this PR.
___
*[projects/batfish/src/test/java/org/batfish/dataplane/ibdp/IncrementalBdpEngineTest.java, line 392 at r2](https://reviewable.io/reviews/batfish/batfish/8023#-MvWTUtNApwywIMLt22k:-MvWY3PB9lqnpBfpblwG:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/574e82813d89d42b74590f71afcde1bd608771f9/projects/batfish/src/test/java/org/batfish/dataplane/ibdp/IncrementalBdpEngineTest.java#L392)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

should use `r2Address`
</blockquote></details>

done
___
*[projects/batfish/src/test/java/org/batfish/dataplane/ibdp/IncrementalBdpEngineTest.java, line 405 at r2](https://reviewable.io/reviews/batfish/batfish/8023#-MvWTs9DEU3DF8FmrWGa:-MvWYDyRCxtL-sHwuyYe:bgeo9xl) ([raw file](https://github.com/batfish/batfish/blob/574e82813d89d42b74590f71afcde1bd608771f9/projects/batfish/src/test/java/org/batfish/dataplane/ibdp/IncrementalBdpEngineTest.java#L405)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

you confirmed that `TestIpOwners` handles virtual IP ownership correctly?
</blockquote></details>

TestIpOwners is defined exactly like `PreDataPlaneIpOwners` (see right below this function) with L3Adjacencies fixed as broadcast no point-to-point. So it should do the right thing. It turns out it doesn't really matter a whole lot what it does, because we replace this with`DataPlaneIpOwners` after IGP.

**Review by corinaminer — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8023)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

___
*[projects/batfish/src/test/java/org/batfish/dataplane/A10KernelRouteTest.java, line 52 at r2](https://reviewable.io/reviews/batfish/batfish/8023#-MvWQ8mI4abCQ5jkrU4u:-MvWi1rlEGr5ovFoNjaw:b8774bp) ([raw file](https://github.com/batfish/batfish/blob/574e82813d89d42b74590f71afcde1bd608771f9/projects/batfish/src/test/java/org/batfish/dataplane/A10KernelRouteTest.java#L52)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

fixed
</blockquote></details>

also on the bgp connection... perhaps not worth holding up the pr though.

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8023)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Pull request merged**
