### PR TITLE
MutableBDDInteger: add subClipping function

### PR DESCRIPTION
**Pull request by dhalperi**
Basically, a copy of addClipping.

---

**Stack**:
- #9143
- #9142
- #9141 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by millstein — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/9141)* status: all files reviewed, 1 unresolved discussion (waiting on @anothermattbrown, @dhalperi, and @nickgian)

___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/MutableBDDInteger.java` line 335 at r1](https://reviewable.io/reviews/batfish/batfish/9141#-O3eB_cWBNkl3ghMcWWD:-O3eB_cWBNkl3ghMcWWE:b-w5o4g3) ([raw file](https://github.com/batfish/batfish/blob/26b649cb5b10bc3a98a4e4c241df52cb98430318/projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/MutableBDDInteger.java#L335)):*
> ```Java
>       cs[i] = as[i].xor(bs[i]).xorEq(borrow);
>       BDD var7 = bs[i].or(borrow).diffEq(as[i]);
>       borrow = as[i].and(bs[i]).andWith(borrow).orWith(var7);
> ```

Optional: seems like a nicer way to do this, which avoids repeating all of the boolean logic, is to have a function that does the subtraction and produces both a MutableBDDInteger and the borrow BDD, and then sub and subClipping can both call that function to do their jobs.  (And the same could be done for add and addClipping.)

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/9141)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @anothermattbrown, @millstein, and @nickgian)

___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/MutableBDDInteger.java` line 335 at r1](https://reviewable.io/reviews/batfish/batfish/9141#-O3eB_cWBNkl3ghMcWWD:-O3eFBdM3JwPv1TJ0uUS:b-zc81ob) ([raw file](https://github.com/batfish/batfish/blob/26b649cb5b10bc3a98a4e4c241df52cb98430318/projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/MutableBDDInteger.java#L335)):*
<details><summary><i>Previously, millstein (Todd Millstein) wrote…</i></summary><blockquote>

Optional: seems like a nicer way to do this, which avoids repeating all of the boolean logic, is to have a function that does the subtraction and produces both a MutableBDDInteger and the borrow BDD, and then sub and subClipping can both call that function to do their jobs.  (And the same could be done for add and addClipping.)
</blockquote></details>

Nice call. I did a refactoring that is similar in spirit but without extra object creation. PTAL.

This also highlighted the (likely unused) ability to pass in `BDDInteger` not just `MutableBDDInteger` so I also loosened the API like `add`.

**Review by nickgian — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/9141#-:-O3g_9bF2-xlR2CDkQuI:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown)

___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/MutableBDDInteger.java` line 306 at r2](https://reviewable.io/reviews/batfish/batfish/9141#-O3gZSnS6MMG3DmxYxhb:-O3gZSnT2HjiPterdkri:b-rrwvaq) ([raw file](https://github.com/batfish/batfish/blob/8d28081fbb4ee06f2c5e3ca30faf7bc5902b4a8f/projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/MutableBDDInteger.java#L306)):*
> ```Java
>     BDD[] bs = other._bitvec;
> 
>     checkArgument(as.length == bs.length, "Cannot add BDDIntegers of different length");
> ```

"Cannot subtract"

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/9141)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown)

**Review by millstein — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/9141#-:-O3hPJwO-3_ApEf3o5o3:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown)

**Pull request merged**
