### PR TITLE
fix spurious circular references in routing policy called policy detection

### PR DESCRIPTION
**Pull request by arifogel**
This change is [Reviewable](https://reviewable.io/reviews/batfish/batfish/701)

### CODE REVIEW

**Comment by dhalperi** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/batfish/batfish/701#-L-_clvYOk6WchnodpHj:-L-_clvYOk6WchnodpHk:b-sem4e6) (no related file):*
Add a new unit test for the bug being fixed.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/CallExpr.java, line 43 at r1](https://reviewable.io:443/reviews/batfish/batfish/701#-L-_c6xnPr05svGiF3ML:-L-_c6xnPr05svGiF3MM:b-fmgfwg) ([raw file](https://github.com/batfish/batfish/blob/50e3dfa6802c0142fac731afb8458d24fb83323d/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/CallExpr.java#L43)):*
> ```Java
>     RoutingPolicy calledPolicy = routingPolicies.get(_calledPolicyName);
>     if (calledPolicy == null) {
>       return Collections.emptySet();
> ```

is this not a warning?

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/If.java, line 39 at r1](https://reviewable.io:443/reviews/batfish/batfish/701#-L-_c_hpClxx5u9EQSiD:-L-_c_hpClxx5u9EQSiE:b-1h304q) ([raw file](https://github.com/batfish/batfish/blob/50e3dfa6802c0142fac731afb8458d24fb83323d/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/If.java#L39)):*
> ```Java
>     ImmutableSet.Builder<String> childSources = ImmutableSet.builder();
>     for (Statement statement : _falseStatements) {
>       childSources.addAll(statement.collectSources(parentSources, routingPolicies, w).iterator());
> ```

why is `.iterator()` necessary? `ImmutableSet.Builder` has a `#addAll(Iterable)`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/701)*

**Comment by arifogel** [comment]
Review status: 6 of 16 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/batfish/batfish/701#-L-_clvYOk6WchnodpHj:-L-cKXaxQ5jVHrWnElO1:bb6un1j) (no related file):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Add a new unit test for the bug being fixed.
</blockquote></details>

Done

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/CallExpr.java, line 43 at r1](https://reviewable.io:443/reviews/batfish/batfish/701#-L-_c6xnPr05svGiF3ML:-L-bmo-PER_As_PhbZ9B:b2pdw4a) ([raw file](https://github.com/batfish/batfish/blob/50e3dfa6802c0142fac731afb8458d24fb83323d/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/CallExpr.java#L43)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

is this not a warning?
</blockquote></details>

Already handled by `undefinedReferences` question. I don't think we should warn every time.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/If.java, line 39 at r1](https://reviewable.io:443/reviews/batfish/batfish/701#-L-_c_hpClxx5u9EQSiD:-L-bmxqzjipRkPb2t4EQ:b-ou9k8b) ([raw file](https://github.com/batfish/batfish/blob/50e3dfa6802c0142fac731afb8458d24fb83323d/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/If.java#L39)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

why is `.iterator()` necessary? `ImmutableSet.Builder` has a `#addAll(Iterable)`
</blockquote></details>

Hmm I might have confused with a different builder that only accepts iterator.
Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/701)*

**Comment by dhalperi** [comment]
*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/routing_policy/RoutingPolicyTests.java, line 8 at r2](https://reviewable.io:443/reviews/batfish/batfish/701#-L-cLqk7_I8tONI_Nal3:-L-cLqk7_I8tONI_Nal4:b1hfe9h) ([raw file](https://github.com/batfish/batfish/blob/a4dc717ca2ff8dc625b50d9787838f5bf04ac2e5/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/routing_policy/RoutingPolicyTests.java#L8)):*
> ```Java
> import static org.junit.Assert.assertThat;
> 
> import jersey.repackaged.com.google.common.collect.ImmutableList;
> ```

import the Guava `ImmutableList` instead.

Does Eclipse not have a way to blacklist auto-imports?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/701)*

**Comment by dhalperi** [comment]
Reviewed 10 of 10 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java, line 289 at r2](https://reviewable.io:443/reviews/batfish/batfish/701#-L-cMrGsx3io1eYgDdMh:-L-cMrGtA4kj7pNJpJiD:bv4qzpb) ([raw file](https://github.com/batfish/batfish/blob/a4dc717ca2ff8dc625b50d9787838f5bf04ac2e5/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java#L289)):*
> ```Java
>       }
>     }
>     // Compute sources for all other policies (previous ones are cached)
> ```

Proposing a small optional tweak might make it clearer.

Invert this: compute them all, then fill in where they're used.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/701)*

**Comment by dhalperi** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/701)*

**Comment by arifogel** [comment]
Review status: 14 of 16 files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java, line 289 at r2](https://reviewable.io:443/reviews/batfish/batfish/701#-L-cMrGsx3io1eYgDdMh:-L-cQIxf52XXM7fCFWwi:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/a4dc717ca2ff8dc625b50d9787838f5bf04ac2e5/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java#L289)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Proposing a small optional tweak might make it clearer.

Invert this: compute them all, then fill in where they're used.
</blockquote></details>

done

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/routing_policy/RoutingPolicyTests.java, line 8 at r2](https://reviewable.io:443/reviews/batfish/batfish/701#-L-cLqk7_I8tONI_Nal3:-L-cQKYuD3m1h5k8ZqA5:b-27gy2x) ([raw file](https://github.com/batfish/batfish/blob/a4dc717ca2ff8dc625b50d9787838f5bf04ac2e5/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/routing_policy/RoutingPolicyTests.java#L8)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

import the Guava `ImmutableList` instead.

Does Eclipse not have a way to blacklist auto-imports?
</blockquote></details>

fixed for now, will look into eclipse way later

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/701)*

**Pull request merged**
