### PR TITLE
Merge abstraction

### PR DESCRIPTION
**Pull request by anothermattbrown**
@rabeckett's abstraction work

---
This change is [Reviewable](https://reviewable.io/reviews/batfish/batfish/890)

### CODE REVIEW

**Comment by dhalperi** [comment]
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/IBatfish.java, line 62 at r5](https://reviewable.io:443/reviews/batfish/batfish/890#-L4FO4LRhoZKQuW9uEDq:-L4FO4LRhoZKQuW9uEDr:bxggbpu) ([raw file](https://github.com/batfish/batfish/blob/6aa045bc868316ff896a9854652d27e3819e98be/projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/IBatfish.java#L62)):*
> ```Java
>   Map<Ip, String> computeIpOwnersSimple(Map<Ip, Set<String>> ipOwners);
> 
>   Topology computeTopology(Map<String, Configuration> configurations);
> ```

It looks to me like there was a bad merge. For example, this function was deleted (renamed) in https://github.com/batfish/batfish/commit/62dea8e97c96c162da09a6d55de716109f53eb45#diff-a18c8f346badc4dfbaa5e21d08025094

The `computeIpOwnersSimple` was moved to `CommonUtil` in https://github.com/batfish/batfish/commit/5ca8653999b8a6a5ae761457938a680f8552c21e

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/890)*

**Comment by dhalperi** [comment]
Reviewed 23 of 185 files at r1, 5 of 15 files at r2, 39 of 64 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[projects/pom.xml, line 603 at r5](https://reviewable.io:443/reviews/batfish/batfish/890#-L4HYv3czLRmnJeDtEuZ:-L4HYv3czLRmnJeDtEu_:bqqo01f) ([raw file](https://github.com/batfish/batfish/blob/6aa045bc868316ff896a9854652d27e3819e98be/projects/pom.xml#L603)):*
> ```XML
>         <artifactId>bdd</artifactId>
>         <version>batfish-internal</version>
>       </dependency>
> ```

I think this is a duplicate block and can be deleted.

A clue that this one is wrong (besides that it's new) is that it's not in the correct alphabetical place by groupId.

---

*[projects/batfish/pom.xml, line 187 at r5](https://reviewable.io:443/reviews/batfish/batfish/890#-L4HZjESTC4ZlIVDRocj:-L4HZjESTC4ZlIVDRock:b-lpouko) ([raw file](https://github.com/batfish/batfish/blob/6aa045bc868316ff896a9854652d27e3819e98be/projects/batfish/pom.xml#L187)):*
> ```XML
>       <groupId>net.sf.javabdd</groupId>
>       <artifactId>bdd</artifactId>
>     </dependency>
> ```

duplicate; please delete (alphabet)

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Topology.java, line 96 at r5](https://reviewable.io:443/reviews/batfish/batfish/890#-L4HZJ0eEBbizhVNLHP3:-L4HZJ0eEBbizhVNLHP4:b-hxqztj) ([raw file](https://github.com/batfish/batfish/blob/6aa045bc868316ff896a9854652d27e3819e98be/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Topology.java#L96)):*
> ```Java
>   }
> 
>   public void removeInterface(NodeInterfacePair iface) {
> ```

On the face of it I can't tell if this is a merge error or deliberate. (aka whether it was made `private` on master and this is a revert, or not. Just confirm that it's need and is used sensibly.

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 987 at r5](https://reviewable.io:443/reviews/batfish/batfish/890#-L4HZXRzg3ICyJ4v4_n-:-L4HZXRzg3ICyJ4v4_n0:bjn8gon) ([raw file](https://github.com/batfish/batfish/blob/6aa045bc868316ff896a9854652d27e3819e98be/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L987)):*
> ```Java
> 
>   @Override
>   public Map<Ip, Set<String>> computeIpOwners(
> ```

This should be deleted -- it goes with the merge error in IBatfish.

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 1063 at r5](https://reviewable.io:443/reviews/batfish/batfish/890#-L4HZaXOXt0gmPw2qr_0:-L4HZaXOXt0gmPw2qr_1:bvibe2i) ([raw file](https://github.com/batfish/batfish/blob/6aa045bc868316ff896a9854652d27e3819e98be/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L1063)):*
> ```Java
> 
>   @Override
>   public Map<Ip, String> computeIpOwnersSimple(Map<Ip, Set<String>> ipOwners) {
> ```

same as above function.

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 1108 at r5](https://reviewable.io:443/reviews/batfish/batfish/890#-L4HZcfce6ryfTQetlpD:-L4HZcfce6ryfTQetlpE:b-2uw036) ([raw file](https://github.com/batfish/batfish/blob/6aa045bc868316ff896a9854652d27e3819e98be/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L1108)):*
> ```Java
> 
>   // TODO: should this be moved out of batfish class?
>   @Override
> ```

Perhaps it has been and this is a merge error? Confirm.

---

*[projects/batfish/src/main/java/org/batfish/symbolic/Graph.java, line 133 at r5](https://reviewable.io:443/reviews/batfish/batfish/890#-L4HXt0idN7eQydxRp4o:-L4HXt0idN7eQydxRp4p:b4s2mx4) ([raw file](https://github.com/batfish/batfish/blob/5012fa7a73d80a67fcf4f3e656ea9aa587da4a07/projects/batfish/src/main/java/org/batfish/symbolic/Graph.java#L133)):*
> ```Java
>     _routers = _configurations.keySet();
> 
>     Topology topology = _batfish.getEnvironmentTopology();
> ```

Check and see if this is related to some bug Ratul fixed recently. I'd look at the github history of this file on master. (which is what I did for other merges).

---

*[projects/batfish/src/main/java/org/batfish/symbolic/utils/PrefixUtils.java, line 56 at r5](https://reviewable.io:443/reviews/batfish/batfish/890#-L4HYVYn5Vg-o9Ml5wU3:-L4HYVYn5Vg-o9Ml5wU4:b3wk438) ([raw file](https://github.com/batfish/batfish/blob/6aa045bc868316ff896a9854652d27e3819e98be/projects/batfish/src/main/java/org/batfish/symbolic/utils/PrefixUtils.java#L56)):*
> ```Java
>     for (Prefix p2 : ps) {
>       // TODO shouldn't p2.equals(p) imply p2.containsPrefix(p)? Add unit tests.
>       if (p2.containsPrefix(p) || p2.equals(p)) {
> ```

Check if we still need this? I think I removed this recently and as for that TODO -- the behavior has been updated as the TODO suggests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/890)*

**Comment by dhalperi** [comment]
Reviewed 7 of 7 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/IBatfish.java, line 57 at r6](https://beta.reviewable.io/reviews/batfish/batfish/890#-L4HpMlS2HUUVNSkmsHT:-L4HpMlS2HUUVNSkmsHU:blue2wu) ([raw file](https://github.com/batfish/batfish/blob/04a9682142e7696d3b5dcb5d01a6ec65bde94e66/projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/IBatfish.java#L57)):*
> ```Java
>       Map<String, Configuration> configurations, boolean differentialContext, Topology topology);
> 
>   Topology computeEnvironmentTopology(Map<String, Configuration> configurations);
> ```

Looks like `computeEnvironmentTopology` is still a new addition -- delete?

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 923 at r6](https://beta.reviewable.io/reviews/batfish/batfish/890#-L4Hqig71ILU2hrMyqjv:-L4Hqig71ILU2hrMyqjw:b-u2wkar) ([raw file](https://github.com/batfish/batfish/blob/04a9682142e7696d3b5dcb5d01a6ec65bde94e66/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L923)):*
> ```Java
>   }
> 
>   @Override
> ```

override, public should be dropped after fixing IBatfish.

---

*[projects/batfish/src/main/java/org/batfish/symbolic/Graph.java, line 149 at r6](https://beta.reviewable.io/reviews/batfish/batfish/890#-L4Hs77ZDJvxfYwCywQg:-L4Hs77ZDJvxfYwCywQh:b-mnoerq) ([raw file](https://github.com/batfish/batfish/blob/5012fa7a73d80a67fcf4f3e656ea9aa587da4a07/projects/batfish/src/main/java/org/batfish/symbolic/Graph.java#L149)):*
> ```Java
>     }
> 
>     initGraph(topology);
> ```

this goes with the other topology issue.

---

*[projects/batfish/src/main/java/org/batfish/symbolic/Graph.java, line 319 at r6](https://beta.reviewable.io/reviews/batfish/batfish/890#-L4Hrr3T11BVv9NQ5ZM8:-L4Hrr3T11BVv9NQ5ZM9:buxvf8b) ([raw file](https://github.com/batfish/batfish/blob/04a9682142e7696d3b5dcb5d01a6ec65bde94e66/projects/batfish/src/main/java/org/batfish/symbolic/Graph.java#L319)):*
> ```Java
>    */
>   private void initGraph() {
>     Topology topology = _batfish.computeEnvironmentTopology(_configurations);
> ```

Looks like there's still a merge issue? -- Topology should come in as a parameter?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/890)*

**Comment by anothermattbrown** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/IBatfish.java, line 57 at r6](https://reviewable.io:443/reviews/batfish/batfish/890#-L4HpMlS2HUUVNSkmsHT:-L4J-zvReIvly9vGBa2s:b1s25dk) ([raw file](https://github.com/batfish/batfish/blob/04a9682142e7696d3b5dcb5d01a6ec65bde94e66/projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/IBatfish.java#L57)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Looks like `computeEnvironmentTopology` is still a new addition -- delete?
</blockquote></details>

This has been deleted; either reviewable is confused or I am...
https://github.com/batfish/batfish/blob/merge-abstraction/projects/batfish-common-protocol/src/main/java/org/batfish/common/plugin/IBatfish.java#L54

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 923 at r6](https://reviewable.io:443/reviews/batfish/batfish/890#-L4Hqig71ILU2hrMyqjv:-L4J5cNPGr8JVnwjnOtY:b6wn03k) ([raw file](https://github.com/batfish/batfish/blob/04a9682142e7696d3b5dcb5d01a6ec65bde94e66/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L923)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

override, public should be dropped after fixing IBatfish.
</blockquote></details>

more confusion...
https://github.com/batfish/batfish/blob/merge-abstraction/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L923

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/890)*

**Comment by dhalperi** [comment]
Reviewed 3 of 3 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/890)*

**Pull request merged**
