### PR TITLE
track defined structures in vendorconfig not answerelement

### PR DESCRIPTION
**Pull request by dhalperi**
The ConvertConfigurationAnswerElement is not available at extraction
time, but that is when we define structures. Instead, the
VendorConfiguration itself should track defined structures and then
populate that information in the CCAE at convert time.

Additionally, the current DefinedStructureInfo is not updateable, so is
not amenable to tracking definitions of and references to structures
separately. Fix this in DefinedStructureInfo.

Finally, to make sure this can work, apply the new code everywhere in
any existing extractor that a DefinedStructure is created.

### CODE REVIEW

**Comment by dhalperi** [comment]
Review status: 0 of 19 files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1370#-LC80xXpB63nJABDDBb2:-LC80xXpB63nJABDDBb3:b-p968nk) (no related file):*
Self-bLocking comment

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1370)*

**Comment by dhalperi** [comment]
This found several new unused structures in the parsing tests and did not introduce any new undefined references.

**Comment by sfraint** [comment]
Looks good so far, my only other comments so far sound like they are being addressed already.

---

Reviewed 18 of 19 files at r1, 1 of 1 files at r2.
Review status: 19 of 20 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 1711 at r2](https://reviewable.io/reviews/batfish/batfish/1370#-LCA7aPW7koLwSl9-4f3:-LCA7aPW7koLwSl9-4f4:b-5bgvgg) ([raw file](https://github.com/batfish/batfish/blob/dcd911f3c17849b1d20ea469a8bab85e4caab144/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L1711)):*
> ```Java
>     }
>     if (_currentFilter == null) {
>       _currentFilter = new FirewallFilter(name, _currentFirewallFamily, definitionLine);
> ```

I think some other structures like `FirewallFilter` need to be defined as well

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1370#-:-LCA5bdR200RO7vGqypS:bjelzq2)*

**Comment by dhalperi** [comment]
Review status: 19 of 20 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 1711 at r2](https://reviewable.io/reviews/batfish/batfish/1370#-LCA7aPW7koLwSl9-4f3:-LCAKcn7EOeIkfT-5hYS:b-xkfiwt) ([raw file](https://github.com/batfish/batfish/blob/dcd911f3c17849b1d20ea469a8bab85e4caab144/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L1711)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

I think some other structures like `FirewallFilter` need to be defined as well
</blockquote></details>

FirewallFilter is not a `DefinedStructure` and was already not being included in these computations, FWICT. It is a non-goal here is to not make any improvements to *which* structures are tracked -- just to move existing structures to better method.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1370)*

**Comment by dhalperi** [comment]
Might be worth checking out https://github.com/batfish/batfish/pull/1372/files to see how the downstream changes look.

- reference everything in extractor
- switch from marking lists of defined/referencecounted structures to marking lists of structure types.

---

Review status: 19 of 20 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1370#-:-LCAP86t7QYtQnGlmBrJ:b-9n24q)*

**Comment by dhalperi** [comment]
Reviewed 1 of 19 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1370)*

**Comment by dhalperi** [comment]
Reviewed 7 of 7 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1370)*

**Pull request merged**
