### PR TITLE
Combine multiple reachability queries into chunks

### PR DESCRIPTION
**Pull request by anothermattbrown**
For queries with the same destination node and header constraints but
with different origination node/vrf, we can combine them into a single
query and use model refinement to find solutions to each original query.

Use a Field class for NoD variables, rather than only the enums in
BasicHeaderField and TransformationHeaderField. Using Field makes it easier to
do instrumention. The enums are still there though, at least for now.
We can consider moving away from them later.

Instrument ReachabilityProgram to solve for OriginateVrf.
The instrumentation adds a field of variable width. The instrumentation
is a post-processing step that runs after Synthesizer. This is for three
reasons: 1st, I wanted to avoid adding complexity to Synthesizer; 2nd,
synthesizer doesn't know what OriginateVrfs to solver for; 3rd, there
are multiple synthesizers involved, and we'd have to modify each of them
to do the instrumentation. This approach is simpler and cleaner, though
I don't like how/where instrumentReachabilityProgram is being called.
The Z3ContextJob class hierarchy should be refactored to make this
cleaner, but I'm not sure how yet. Leaving as-is for now.

AbstractNodJob does the refinement of the model to get one model for
each OriginateVrf. Factored out the call to solver.check and status checking
in AbstractNodJob.

Added maxChunkSize parameter to ReachabilityQuestion

### CODE REVIEW

**Comment by arifogel** [comment]
Reviewed 21 of 21 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 4155 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1037#-L768sTe8liZ-fNLPRV8:-L768sTf59kNxFMwqhc9:bwbb6jn) ([raw file](https://github.com/batfish/batfish/blob/000c40db7bc40e5ec43b79d8bf9a4496e4c086e2/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L4155)):*
> ```Java
>             Math.min(
>                 maxChunkSize,
>                 originateNodeVrfs.size() / Runtime.getRuntime().availableProcessors()));
> ```

This should be squared with the maxjobs setting or whatever it's called `in org.batfish.config.Settings`.

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 4164 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1037#-L769KjH6HnsLcORms8G:-L769KjH6HnsLcORms8H:b3thuod) ([raw file](https://github.com/batfish/batfish/blob/000c40db7bc40e5ec43b79d8bf9a4496e4c086e2/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L4164)):*
> ```Java
>           if (index % chunkSize == 0) {
>             // create a new chunk
>             originateNodeVrfChunks.add(0, new ArrayList<>());
> ```

Why add to beginning? Also shouldn't you use a `LinkedList` if you will always insert at beginning?

---

*[projects/batfish/src/main/java/org/batfish/z3/AbstractNodJob.java, line 53 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1037#-L769hd2BuJ5WWwap9gk:-L769hd2BuJ5WWwap9gl:bd874cb) ([raw file](https://github.com/batfish/batfish/blob/000c40db7bc40e5ec43b79d8bf9a4496e4c086e2/projects/batfish/src/main/java/org/batfish/z3/AbstractNodJob.java#L53)):*
> ```Java
>     solver.add(smtInput._expr);
> 
>     int originateVrfBVSize = _originateVrfInstrumentation.getFieldBits();
> ```

Style: `originateVrfBVSize` -> `originateVrfBvSize`

---

*[projects/batfish/src/main/java/org/batfish/z3/AbstractNodJob.java, line 144 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1037#-L76A6E14RFhvxOvo5GU:-L76A6E14RFhvxOvo5GV:b-p7y0ul) ([raw file](https://github.com/batfish/batfish/blob/000c40db7bc40e5ec43b79d8bf9a4496e4c086e2/projects/batfish/src/main/java/org/batfish/z3/AbstractNodJob.java#L144)):*
> ```Java
>             entry ->
>                 createFlow(
>                     // hostname
> ```

Optional: use `/* hostname */` and similar for below

---

*[projects/batfish/src/main/java/org/batfish/z3/AbstractNodJob.java, line 166 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1037#-L76AIA94tdS-c9tQYTL:-L76AIA94tdS-c9tQYTM:bfivk0) ([raw file](https://github.com/batfish/batfish/blob/000c40db7bc40e5ec43b79d8bf9a4496e4c086e2/projects/batfish/src/main/java/org/batfish/z3/AbstractNodJob.java#L166)):*
> ```Java
>   }
> 
>   @SuppressWarnings("serial")
> ```

Don't suppress this. Just make the id.

---

*[projects/batfish/src/main/java/org/batfish/z3/Field.java, line 23 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1037#-L76AVYU2tMAfN3tbeEd:-L76AVYU2tMAfN3tbeEe:b-blq479) ([raw file](https://github.com/batfish/batfish/blob/000c40db7bc40e5ec43b79d8bf9a4496e4c086e2/projects/batfish/src/main/java/org/batfish/z3/Field.java#L23)):*
> ```Java
> 
>   @Override
>   public boolean equals(Object other) {
> ```

It is standard to first check for instance equality and return true.

---

*[projects/batfish/src/main/java/org/batfish/z3/OriginateVrfInstrumentation.java, line 23 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1037#-L76B9na5diAd8AsCek4:-L76B9na5diAd8AsCek5:b4gy79k) ([raw file](https://github.com/batfish/batfish/blob/000c40db7bc40e5ec43b79d8bf9a4496e4c086e2/projects/batfish/src/main/java/org/batfish/z3/OriginateVrfInstrumentation.java#L23)):*
> ```Java
> 
> /**
>  * A NodInstrumentation that tracks which of several possible OriginateVrf states was used to derive
> ```

The way you write `NodInstrumentation` it looks like a separate class. However I see no such file. Perhaps just write `NOD instrumentation`?

---

*[projects/batfish/src/main/java/org/batfish/z3/Z3ContextJob.java, line 36 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1037#-L76CC9M3ko03Opn8ZnI:-L76CC9M3ko03Opn8ZnJ:b-yixhy4) ([raw file](https://github.com/batfish/batfish/blob/000c40db7bc40e5ec43b79d8bf9a4496e4c086e2/projects/batfish/src/main/java/org/batfish/z3/Z3ContextJob.java#L36)):*
> ```Java
>           .collect(
>               ImmutableMap.toImmutableMap(
>                   // Can't use a method reference here (Enums)
> ```

You could if you add generic argument <HeaderField> to concat.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1037)*

**Comment by anothermattbrown** [comment]
Review status: 16 of 21 files reviewed at latest revision, 7 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/z3/AbstractNodJob.java, line 53 at r1](https://reviewable.io:443/reviews/batfish/batfish/1037#-L769hd2BuJ5WWwap9gk:-L76kWWAcAU_LIehPJwp:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/000c40db7bc40e5ec43b79d8bf9a4496e4c086e2/projects/batfish/src/main/java/org/batfish/z3/AbstractNodJob.java#L53)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Style: `originateVrfBVSize` -> `originateVrfBvSize`
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/z3/AbstractNodJob.java, line 166 at r1](https://reviewable.io:443/reviews/batfish/batfish/1037#-L76AIA94tdS-c9tQYTL:-L76kX6FeYhRy2sIBmWt:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/000c40db7bc40e5ec43b79d8bf9a4496e4c086e2/projects/batfish/src/main/java/org/batfish/z3/AbstractNodJob.java#L166)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Don't suppress this. Just make the id.
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/z3/Field.java, line 23 at r1](https://reviewable.io:443/reviews/batfish/batfish/1037#-L76AVYU2tMAfN3tbeEd:-L76kYNzT0a7tyXWdboz:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/000c40db7bc40e5ec43b79d8bf9a4496e4c086e2/projects/batfish/src/main/java/org/batfish/z3/Field.java#L23)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

It is standard to first check for instance equality and return true.
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/z3/OriginateVrfInstrumentation.java, line 23 at r1](https://reviewable.io:443/reviews/batfish/batfish/1037#-L76B9na5diAd8AsCek4:-L76kZOdEhAAycMqJHIm:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/000c40db7bc40e5ec43b79d8bf9a4496e4c086e2/projects/batfish/src/main/java/org/batfish/z3/OriginateVrfInstrumentation.java#L23)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

Good point. It was a class, but I removed it since there's only one for now.
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/z3/Z3ContextJob.java, line 36 at r1](https://reviewable.io:443/reviews/batfish/batfish/1037#-L76CC9M3ko03Opn8ZnI:-L76k_vxtDBQC2ffKdGl:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/000c40db7bc40e5ec43b79d8bf9a4496e4c086e2/projects/batfish/src/main/java/org/batfish/z3/Z3ContextJob.java#L36)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

You could if you add generic argument <HeaderField> to concat.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/1037)*

**Comment by dhalperi** [comment]
Review status: 16 of 21 files reviewed at latest revision, 7 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 4164 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1037#-L769KjH6HnsLcORms8G:-L76nwvsEp14N8V2wxu8:b-gxnsqf) ([raw file](https://github.com/batfish/batfish/blob/000c40db7bc40e5ec43b79d8bf9a4496e4c086e2/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L4164)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

Because I have to get the current chunk list in subsequent iterations, and don't want to have to walk the whole list to get it. LinkedList is fine; I'll switch to that.
</blockquote></details>

(Drive-by: this looks like a use-case for collect rather than foreach.

https://docs.oracle.com/javase/tutorial/collections/streams/reduction.html#collect)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1037)*

**Comment by dhalperi** [comment]
*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 4164 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1037#-L769KjH6HnsLcORms8G:-L76oT5WAvXmf-w-enWe:b7wxv7r) ([raw file](https://github.com/batfish/batfish/blob/000c40db7bc40e5ec43b79d8bf9a4496e4c086e2/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L4164)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

(Drive-by: this looks like a use-case for collect rather than foreach.

https://docs.oracle.com/javase/tutorial/collections/streams/reduction.html#collect)
</blockquote></details>

Actually no, just use Lists.partition? https://google.github.io/guava/releases/23.0/api/docs/com/google/common/collect/Lists.html#partition-java.util.List-int-

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1037)*

**Comment by anothermattbrown** [comment]
Review status: 16 of 21 files reviewed at latest revision, 7 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 4164 at r1](https://reviewable.io:443/reviews/batfish/batfish/1037#-L769KjH6HnsLcORms8G:-L76rZui6k7ZXKCoAW1A:b6ckia9) ([raw file](https://github.com/batfish/batfish/blob/000c40db7bc40e5ec43b79d8bf9a4496e4c086e2/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L4164)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Actually no, just use Lists.partition? https://google.github.io/guava/releases/23.0/api/docs/com/google/common/collect/Lists.html#partition-java.util.List-int-
</blockquote></details>

ha, just found Lists.partition too :P

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/1037)*

**Comment by arifogel** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 4155 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1037#-L768sTe8liZ-fNLPRV8:-L7B5pflEqgVh5a5sv0z:b-504wr6) ([raw file](https://github.com/batfish/batfish/blob/000c40db7bc40e5ec43b79d8bf9a4496e4c086e2/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L4155)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

Squared how? The comment for `Settings.ARG_JOBS` is "number of threads used by parallel jobs executor". Should I use that instead of `availableProcessors`?
</blockquote></details>

If you look at `BatfishJobExecutor.createExecutorService`, there is a computation based on that setting for how many jobs to execute in parallel. This executor is used for `NodJob`s. The size of the thread pool that it allocates is the actual concurrency level you should assume when deciding how to chunk.

---

*[projects/batfish/src/main/java/org/batfish/z3/AbstractNodJob.java, line 166 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1037#-L76AIA94tdS-c9tQYTL:-L7B6tUA8rBoRfRzSoNb:b-ehf6kr) ([raw file](https://github.com/batfish/batfish/blob/000c40db7bc40e5ec43b79d8bf9a4496e4c086e2/projects/batfish/src/main/java/org/batfish/z3/AbstractNodJob.java#L166)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

FYI The default is usually `1L`.  I have no idea if it matters. I don't care if you change it.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1037)*

**Comment by arifogel** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 4155 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1037#-L768sTe8liZ-fNLPRV8:-L7B7Llu-kibJuXvR66A:b52uwdo) ([raw file](https://github.com/batfish/batfish/blob/000c40db7bc40e5ec43b79d8bf9a4496e4c086e2/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L4155)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

If you look at `BatfishJobExecutor.createExecutorService`, there is a computation based on that setting for how many jobs to execute in parallel. This executor is used for `NodJob`s. The size of the thread pool that it allocates is the actual concurrency level you should assume when deciding how to chunk.
</blockquote></details>

(It would be fine to extract that computation out for less awkward access)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1037)*

**Comment by anothermattbrown** [comment]
Review status: 19 of 23 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 4155 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1037#-L768sTe8liZ-fNLPRV8:-L7BEbA98-_2sdrN3C16:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/000c40db7bc40e5ec43b79d8bf9a4496e4c086e2/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L4155)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

(It would be fine to extract that computation out for less awkward access)
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/z3/AbstractNodJob.java, line 166 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1037#-L76AIA94tdS-c9tQYTL:-L7BEa21A65anyXMrYwl:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/000c40db7bc40e5ec43b79d8bf9a4496e4c086e2/projects/batfish/src/main/java/org/batfish/z3/AbstractNodJob.java#L166)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

FYI The default is usually `1L`.  I have no idea if it matters. I don't care if you change it.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1037)*

**Comment by arifogel** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1037#-:-L7BG4xI97vOGCisUU50:bnfp4nl)*

**Pull request merged**
