### PR TITLE
Add AdministrativeCost in BgpRoute, and in extension for SetAdministrativeCost in TRP.

### PR DESCRIPTION
**Pull request by nickgian**
Adds `PROP_ADMINISTRATIVE_DISTANCE` to BgpRoute, to allow modeling the effect of `SetAdministrativeCost` in TRP/SRP.

### CODE REVIEW

**Review by nickgian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8796)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @dhalperi and @millstein)

___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpRoute.java` line 110 at r1](https://reviewable.io/reviews/batfish/batfish/8796#-NeMC8uy2wGuTWm_-WCK:-NeMC8uz-9aRFLfgvxz0:b82myn8) ([raw file](https://github.com/batfish/batfish/blob/439fe57ad18438f63008af24fb50ecffdea42c57/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpRoute.java#L110)):*
> ```Java
>       @JsonProperty(PROP_ADMINISTRATIVE_DISTANCE) int adminDist,
>       @Nullable @JsonProperty(PROP_AS_PATH) AsPath asPath,
>       @Nullable @JsonProperty(PROP_CLUSTER_LIST) ImmutableSet<Long> clusterList,
> ```

I suspect this was my IDE.

**Review by nickgian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8796)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpRoute.java` line 108 at r3](https://reviewable.io/reviews/batfish/batfish/8796#-NeO1otg2QCSh2Y8Azl8:-NeOFRzB6plcTEXtxifz:b-n5qh4n) ([raw file](https://github.com/batfish/batfish/blob/2c89abe7d3b18a4148804724524dd91b6af342e4/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpRoute.java#L108)):*
<details><summary><i>Previously, millstein (Todd Millstein) wrote…</i></summary><blockquote>

This all looks good.  You should double check that pybatfish tests still all pass, indicating that this change is backward compatible.  Though there's an issue that pybatfish tests are failing currently on master -- @dhalperi  was going to investigate I believe?
</blockquote></details>

Yes, that was my main worry with this PR, I'll ask Dan in person too.

I ran pybatfish tests, there are some failing tests but seem irrelevant to this PR.

One seems to be because of `IGP`/`EGP` in `Analyzing Routing Policy` (not sure when we introduced that, I can push a fix) and one in `Introduction to BGP Analysis`.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8796)* status: all files reviewed, 2 unresolved discussions (waiting on @millstein and @nickgian)

___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpRoute.java` line 108 at r3](https://reviewable.io/reviews/batfish/batfish/8796#-NeO1otg2QCSh2Y8Azl8:-NeORHY_39IY8IgvCTpZ:buu6q5c) ([raw file](https://github.com/batfish/batfish/blob/2c89abe7d3b18a4148804724524dd91b6af342e4/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpRoute.java#L108)):*
<details><summary><i>Previously, nickgian (Nick Giannarakis) wrote…</i></summary><blockquote>

Yes, that was my main worry with this PR, I'll ask Dan in person too.

I ran pybatfish tests, there are some failing tests but seem irrelevant to this PR.

One seems to be because of `IGP`/`EGP` in `Analyzing Routing Policy` (not sure when we introduced that, I can push a fix) and one in `Introduction to BGP Analysis`.
</blockquote></details>

1/ I'm not planning to dig into CI failures. Can't be a SPOF here.

2/ For JSON API input, make this `@Nullable Integer`. Then we are forced to define what the behavior is/should be when the value is not provided. Do we really want it to be 0?

Dumb question: how does this make sense for a *input* route, aka, one received from a neighbor? User should supply process-level default AD?
___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpRoute.java` line 341 at r3](https://reviewable.io/reviews/batfish/batfish/8796#-NeORxMY0NSQV23qA2Qo:-NeORxMY0NSQV23qA2Qp:b-5qx1bd) ([raw file](https://github.com/batfish/batfish/blob/2c89abe7d3b18a4148804724524dd91b6af342e4/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpRoute.java#L341)):*
> ```Java
>   public static final class Builder {
> 
>     private int _adminDist;
> ```

Same here -- do we want this defaulting to 0? Usually we do `@Nullable Integer` and then enforce default at `.build()` (or error).

**Review by dhalperi — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8796)* status: all files reviewed, 3 unresolved discussions (waiting on @millstein and @nickgian)

___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpRoute.java` line 133 at r4](https://reviewable.io/reviews/batfish/batfish/8796#-NeP391o2n4x9kDOEnCy:-NeP391o2n4x9kDOEnCz:b88tcg3) ([raw file](https://github.com/batfish/batfish/blob/7c317fe897a49f767dd9f55cb6ef6ee10044ac79/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpRoute.java#L133)):*
> ```Java
>     checkArgument(protocol != null, "%s must be specified", PROP_PROTOCOL);
>     return new BgpRoute(
>         firstNonNull(adminDist, 0),
> ```

Should probably introduce a question-specific constant for this so if we decide to change it (say, 20 for ebgp, or even 20 ebgp and 200 for ibgp as Cisco does) then we have fewer places to patch.

**Review by nickgian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8796)* status: all files reviewed, 2 unresolved discussions (waiting on @millstein and @progwriter)

___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpRoute.java` line 108 at r3](https://reviewable.io/reviews/batfish/batfish/8796#-NeO1otg2QCSh2Y8Azl8:-NeOzUKe5iBFs4rdlgqO:b-d4i1qt) ([raw file](https://github.com/batfish/batfish/blob/2c89abe7d3b18a4148804724524dd91b6af342e4/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpRoute.java#L108)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

1/ I'm not planning to dig into CI failures. Can't be a SPOF here.

2/ For JSON API input, make this `@Nullable Integer`. Then we are forced to define what the behavior is/should be when the value is not provided. Do we really want it to be 0?

Dumb question: how does this make sense for a *input* route, aka, one received from a neighbor? User should supply process-level default AD?
</blockquote></details>

Done!

Ideally we want it to be whatever the vendor's default is, but threading vendor information through to get the right value did not seem worthwhile - mainly because there are no matches on AdministrativeDistance. The output would look a tad more realistic. Happy to reconsider if people disagree with this take.

I agree it is not useful for the input route, at least for TRP/SRP, but there is no separate input/output BgpRoute class. (though clients may use it to pass a more realistic value for AD)
___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpRoute.java` line 341 at r3](https://reviewable.io/reviews/batfish/batfish/8796#-NeORxMY0NSQV23qA2Qo:-NeP-mvK1X7p8anvAoB-:b-gzz5l6) ([raw file](https://github.com/batfish/batfish/blob/2c89abe7d3b18a4148804724524dd91b6af342e4/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpRoute.java#L341)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Same here -- do we want this defaulting to 0? Usually we do `@Nullable Integer` and then enforce default at `.build()` (or error).
</blockquote></details>

Done. Still defaulting at 0 but at least its explicit now.

**Review by millstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8796)* status: all files reviewed, 2 unresolved discussions (waiting on @nickgian and @progwriter)

___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpRoute.java` line 108 at r3](https://reviewable.io/reviews/batfish/batfish/8796#-NeO1otg2QCSh2Y8Azl8:-NeQ2Ir25CxzIhB4IAJD:bn96o8e) ([raw file](https://github.com/batfish/batfish/blob/2c89abe7d3b18a4148804724524dd91b6af342e4/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpRoute.java#L108)):*
<details><summary><i>Previously, nickgian (Nick Giannarakis) wrote…</i></summary><blockquote>

Done!

Ideally we want it to be whatever the vendor's default is, but threading vendor information through to get the right value did not seem worthwhile - mainly because there are no matches on AdministrativeDistance. The output would look a tad more realistic. Happy to reconsider if people disagree with this take.

I agree it is not useful for the input route, at least for TRP/SRP, but there is no separate input/output BgpRoute class. (though clients may use it to pass a more realistic value for AD)
</blockquote></details>

CI failures are fixed (thanks to a lot of help from Dan) so you should be able to try it now to make sure you didn't break anything.

**Review by nickgian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8796)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @dhalperi and @progwriter)

___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpRoute.java` line 133 at r4](https://reviewable.io/reviews/batfish/batfish/8796#-NeP391o2n4x9kDOEnCy:-NeQBPPP96QUy2mUFxZP:bvsbb5j) ([raw file](https://github.com/batfish/batfish/blob/7c317fe897a49f767dd9f55cb6ef6ee10044ac79/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpRoute.java#L133)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Should probably introduce a question-specific constant for this so if we decide to change it (say, 20 for ebgp, or even 20 ebgp and 200 for ibgp as Cisco does) then we have fewer places to patch.
</blockquote></details>

Pulled this out in a constant, but I think you might had something different in mind?

**Review by nickgian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8796)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @dhalperi, @millstein, and @progwriter)

___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpRoute.java` line 108 at r3](https://reviewable.io/reviews/batfish/batfish/8796#-NeO1otg2QCSh2Y8Azl8:-NeUBjPi617zDAH-EV6H:bkgt687) ([raw file](https://github.com/batfish/batfish/blob/2c89abe7d3b18a4148804724524dd91b6af342e4/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpRoute.java#L108)):*
<details><summary><i>Previously, millstein (Todd Millstein) wrote…</i></summary><blockquote>

CI failures are fixed (thanks to a lot of help from Dan) so you should be able to try it now to make sure you didn't break anything.
</blockquote></details>

Can confirm that Pybatfish tests succeed with this PR.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8796)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @progwriter)

**Pull request merged**
