### PR TITLE
Symbolic route analysis:  support policies that invoke other policies

### PR DESCRIPTION
**Pull request by millstein**
Adds support for route policies calling other route policies in the symbolic route analysis.  Specifically we separately track the return status of the analysis (conditions under which the current policy being analyzed returns) and the exit status of the analysis (conditions under which the entire analysis has reached the end of a path), and we now support analysis of CallStatements.

### CODE REVIEW

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6180)* status: all files reviewed, 2 unresolved discussions (waiting on @millstein)

___
*[projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferResult.java, line 25 at r2](https://reviewable.io/reviews/batfish/batfish/6180#-MGjVmj270NgdW56VKNM:-MGjVmj270NgdW56VKNN:b-wifubj) ([raw file](https://github.com/batfish/batfish/blob/2c3a9fb7ac867dd974b4860f3c94bdde1d1a6532/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferResult.java#L25)):*
> ```
> _fallthroughValue
> ```
what invariants are there for these BDD fields? Presumably they are disjoint?
___
*[projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferBDDTest.java, line 337 at r2](https://reviewable.io/reviews/batfish/batfish/6180#-MGjX3603pIV1T-8dh4g:-MGjX3603pIV1T-8dh4h:b5jb5u2) ([raw file](https://github.com/batfish/batfish/blob/2c3a9fb7ac867dd974b4860f3c94bdde1d1a6532/projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferBDDTest.java#L337)):*
> ```
> public void testPartialReturn() {
> ```
I'm trying to understand what the result will be for a statement like this:
```
if(match(1.0.0.0/8)) {
  set local-pref 2
  return true;
} 
if (match(2.0.0.0/8)) {
  set local-pref 3
  return false;
}
exit accept;
```

My intuition is that we'd have separate BDDs describing the set of routes for which we return true vs false. Then we use those to get the transformed route from the transfer result. But I only see 1 BDD for returns.

**Review by millstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6180)* status: all files reviewed, 2 unresolved discussions (waiting on @anothermattbrown)

___
*[projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferResult.java, line 25 at r2](https://reviewable.io/reviews/batfish/batfish/6180#-MGjVmj270NgdW56VKNM:-MGjia2H1C6JcixaM6Hx:b-3u3twr) ([raw file](https://github.com/batfish/batfish/blob/2c3a9fb7ac867dd974b4860f3c94bdde1d1a6532/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferResult.java#L25)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

> ```
> _fallthroughValue
> ```
what invariants are there for these BDD fields? Presumably they are disjoint?
</blockquote></details>

Good question.  The fields _exitAssignedValue and _returnAssignedValue are disjoint.  _fallthroughValue is a subset of _returnedAssignedValue, the subset of cases where we return and want to signal to move to the next policy.   I will add comments to this effect.   (Note that _fallthroughValue exists from the original version of the symbolic route analysis code and will be necessary for handling certain constructs, but currently it is not tested and is not used for the features that I am supporting at the moment.)
___
*[projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferBDDTest.java, line 337 at r2](https://reviewable.io/reviews/batfish/batfish/6180#-MGjX3603pIV1T-8dh4g:-MGjjuPN4YMWFOCguotW:b2k3kxg) ([raw file](https://github.com/batfish/batfish/blob/2c3a9fb7ac867dd974b4860f3c94bdde1d1a6532/projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferBDDTest.java#L337)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

> ```
> public void testPartialReturn() {
> ```
I'm trying to understand what the result will be for a statement like this:
```
if(match(1.0.0.0/8)) {
  set local-pref 2
  return true;
} 
if (match(2.0.0.0/8)) {
  set local-pref 3
  return false;
}
exit accept;
```

My intuition is that we'd have separate BDDs describing the set of routes for which we return true vs false. Then we use those to get the transformed route from the transfer result. But I only see 1 BDD for returns.
</blockquote></details>

The analysis returns a BDD and a BDDRoute.  The BDD is a predicate representing the cases where the policy permits (or returns true).  Implicitly the negation of this BDD represents the cases where the policy rejects (or returns false).  The BDDRoute represents the conditions under which route updates are made.  So the BDDRoute will include both of the updates in your example -- the BDDInteger for local preference will indicate that it has the value 2 when the prefix is 1.0.0.0/8, the value 3 when the prefix is 2.0.0.0/8, and the original local preference in all other cases.

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6180)* status: all files reviewed, 1 unresolved discussion (waiting on @millstein)

___
*[projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferResult.java, line 25 at r2](https://reviewable.io/reviews/batfish/batfish/6180#-MGjVmj270NgdW56VKNM:-MGjyDSi9pvOEfBQptGz:b-yv4ay5) ([raw file](https://github.com/batfish/batfish/blob/2c3a9fb7ac867dd974b4860f3c94bdde1d1a6532/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferResult.java#L25)):*
<details><summary><i>Previously, millstein (Todd Millstein) wrote…</i></summary><blockquote>

Good question.  The fields _exitAssignedValue and _returnAssignedValue are disjoint.  _fallthroughValue is a subset of _returnedAssignedValue, the subset of cases where we return and want to signal to move to the next policy.   I will add comments to this effect.   (Note that _fallthroughValue exists from the original version of the symbolic route analysis code and will be necessary for handling certain constructs, but currently it is not tested and is not used for the features that I am supporting at the moment.)
</blockquote></details>

Comments help, thanks! It would be even better (for me) to check invariants. Presumably these invariants are currently being (temporarily) violated when you mutate these. It may be better to make these immutable and assert the invariants in the constructor.
___
*[projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferBDDTest.java, line 337 at r2](https://reviewable.io/reviews/batfish/batfish/6180#-MGjX3603pIV1T-8dh4g:-MGjw64I3eIaFH0HEv7N:b5x7vtu) ([raw file](https://github.com/batfish/batfish/blob/2c3a9fb7ac867dd974b4860f3c94bdde1d1a6532/projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferBDDTest.java#L337)):*
<details><summary><i>Previously, millstein (Todd Millstein) wrote…</i></summary><blockquote>

The analysis returns a BDD and a BDDRoute.  The BDD is a predicate representing the cases where the policy permits (or returns true).  Implicitly the negation of this BDD represents the cases where the policy rejects (or returns false).  The BDDRoute represents the conditions under which route updates are made.  So the BDDRoute will include both of the updates in your example -- the BDDInteger for local preference will indicate that it has the value 2 when the prefix is 1.0.0.0/8, the value 3 when the prefix is 2.0.0.0/8, and the original local preference in all other cases.
</blockquote></details>

I don't quite follow this. If `exitAssignedValue` and `returnAssignedValue` are disjoint, then the negation of `returnAssignedValue` will include `exitAssignedValue`. So does that mean we have to subtract `exitAssignedValue` from `returnAssignedValue.not()` to find the inputs for which the policy returns false? What about exit false?

**Review by millstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6180)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @anothermattbrown)

___
*[projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferResult.java, line 25 at r2](https://reviewable.io/reviews/batfish/batfish/6180#-MGjVmj270NgdW56VKNM:-MGkDA1VEohoFMlB-Ayx:bgwkknm) ([raw file](https://github.com/batfish/batfish/blob/2c3a9fb7ac867dd974b4860f3c94bdde1d1a6532/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferResult.java#L25)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

Comments help, thanks! It would be even better (for me) to check invariants. Presumably these invariants are currently being (temporarily) violated when you mutate these. It may be better to make these immutable and assert the invariants in the constructor.
</blockquote></details>

Nice.  I updated as you suggested.
___
*[projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferBDDTest.java, line 337 at r2](https://reviewable.io/reviews/batfish/batfish/6180#-MGjX3603pIV1T-8dh4g:-MGkDDna5tG8fJDERiWR:b-7bnbp6) ([raw file](https://github.com/batfish/batfish/blob/2c3a9fb7ac867dd974b4860f3c94bdde1d1a6532/projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferBDDTest.java#L337)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

I don't quite follow this. If `exitAssignedValue` and `returnAssignedValue` are disjoint, then the negation of `returnAssignedValue` will include `exitAssignedValue`. So does that mean we have to subtract `exitAssignedValue` from `returnAssignedValue.not()` to find the inputs for which the policy returns false? What about exit false?  
</blockquote></details>

Sorry let me try that again.  Above I was only talking about what is returned at the top level.  At an arbitrary point in the analysis we have 4 BDDs plus a BDDRoute -- the TransferResult object holds them all.

BDD1: The conditions under which the current policy either exits and permits the route, or returns true.
BDD2: The conditions under which the current policy exits (either permitting or denying).
BDD3: The conditions under which the current policy returns (either true or false).
BDD4: The conditions under which the current policy signals a fall-through to the next policy.
BDDRoute: The output announcement as a function of the input announcement.

So the scenarios where we exit and permit are (BDD1 && BDD2), the scenarios where we exit and reject are (!BDD1 && BDD2), the scenarios where we return true are (BDD1 && BDD3), and the scenarios where we return false are (!BDD1 && BDD3).

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6180)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @millstein)

___
*[projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferResult.java, line 50 at r4](https://reviewable.io/reviews/batfish/batfish/6180#-MGkKcJU1o0Gfhap0HPs:-MGkKcJU1o0Gfhap0HPt:bag8bko) ([raw file](https://github.com/batfish/batfish/blob/4e94678f84a00048321c7c26fdad179fd08e8011/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferResult.java#L50)):*
> ```
> // the conditions for exiting and returning should be disjoint
> ```
1. you can put this message as the second argument to `checkArgument`, and then it will be included in the exception if the invariant is violated.
2. I tend to use java's `assert` for BDD invariants like this, since these operations can be fairly expensive
___
*[projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferBDDTest.java, line 337 at r2](https://reviewable.io/reviews/batfish/batfish/6180#-MGjX3603pIV1T-8dh4g:-MGkJF6x0GrrkYO0B63Q:bmme4ef) ([raw file](https://github.com/batfish/batfish/blob/2c3a9fb7ac867dd974b4860f3c94bdde1d1a6532/projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferBDDTest.java#L337)):*
<details><summary><i>Previously, millstein (Todd Millstein) wrote…</i></summary><blockquote>

Sorry let me try that again.  Above I was only talking about what is returned at the top level.  At an arbitrary point in the analysis we have 4 BDDs plus a BDDRoute -- the TransferResult object holds them all.

BDD1: The conditions under which the current policy either exits and permits the route, or returns true.
BDD2: The conditions under which the current policy exits (either permitting or denying).
BDD3: The conditions under which the current policy returns (either true or false).
BDD4: The conditions under which the current policy signals a fall-through to the next policy.
BDDRoute: The output announcement as a function of the input announcement.

So the scenarios where we exit and permit are (BDD1 && BDD2), the scenarios where we exit and reject are (!BDD1 && BDD2), the scenarios where we return true are (BDD1 && BDD3), and the scenarios where we return false are (!BDD1 && BDD3).
</blockquote></details>

aha I figured it was something like that, but couldn't quite see it. comments and tests would be appreciated.

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6180)* status: all files reviewed, 1 unresolved discussion (waiting on @millstein)

**Review by millstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6180)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @anothermattbrown)

___
*[projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferResult.java, line 50 at r4](https://reviewable.io/reviews/batfish/batfish/6180#-MGkKcJU1o0Gfhap0HPs:-MGnazID5gbjQk-bKc3K:b-bi4kg4) ([raw file](https://github.com/batfish/batfish/blob/4e94678f84a00048321c7c26fdad179fd08e8011/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferResult.java#L50)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

> ```
> // the conditions for exiting and returning should be disjoint
> ```
1. you can put this message as the second argument to `checkArgument`, and then it will be included in the exception if the invariant is violated.
2. I tend to use java's `assert` for BDD invariants like this, since these operations can be fairly expensive
</blockquote></details>

Switched to asserts, with an error message.
___
*[projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferBDDTest.java, line 337 at r2](https://reviewable.io/reviews/batfish/batfish/6180#-MGjX3603pIV1T-8dh4g:-MGnb3QDAy-G8X5mUTdV:b-guoyd3) ([raw file](https://github.com/batfish/batfish/blob/2c3a9fb7ac867dd974b4860f3c94bdde1d1a6532/projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferBDDTest.java#L337)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

aha I figured it was something like that, but couldn't quite see it. comments and tests would be appreciated.
</blockquote></details>

Added a comment with examples like the ones above, and added some more tests.

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 2 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6180)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @anothermattbrown)

___
*[projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferBDDTest.java, line 337 at r2](https://reviewable.io/reviews/batfish/batfish/6180#-MGjX3603pIV1T-8dh4g:-MGndc1E5lXE6z5hbh2N:bd5l6mr) ([raw file](https://github.com/batfish/batfish/blob/2c3a9fb7ac867dd974b4860f3c94bdde1d1a6532/projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferBDDTest.java#L337)):*
<details><summary><i>Previously, millstein (Todd Millstein) wrote…</i></summary><blockquote>

Added a comment with examples like the ones above, and added some more tests.
</blockquote></details>

thanks!

**Review by anothermattbrown — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6180#-:-MGndna_3-4Kvi7vdt0H:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
