### PR TITLE
Sonic ACLs: Parse ETHER_TYPE

### PR DESCRIPTION
**Pull request by ratulm**

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8231)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ratulm)

___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/AclRule.java, line 78 at r1](https://reviewable.io/reviews/batfish/batfish/8231#-N-5MkF9Ag2UajJUsN1b:-N-5MkF9Ag2UajJUsN1c:bmdc58g) ([raw file](https://github.com/batfish/batfish/blob/2afc67582bcb7a1f57277aa9a639d906dbdcd49a/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/AclRule.java#L78)):*
> ```Java
>       @Nullable @JsonProperty(PROP_PRIORITY) Integer priority,
>       @Nullable @JsonProperty(PROP_PACKET_ACTION) PacketAction packetAction,
>       @Nullable @JsonProperty(PROP_ETHER_TYPE) String etherType /* ignored */) {
> ```

FYI I think this should be extracted. the value 2048 (0x800) is IP (v4), so should be treated as `any ip packet`.

IPv6 is type `0x86DD` = `34525`, and can be skipped.

Other ones should just be marked false/unreachable?



_Code quote:_
```Java
e /* ignored */) {
```

**Review by dhalperi — COMMENTED** [review]
> Reviewed 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8231)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @dhalperi and @ratulm)

___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConversions.java, line 352 at r2](https://reviewable.io/reviews/batfish/batfish/8231#-N-6Kpl7ComcAQqvJPbi:-N-6Kpl7ComcAQqvJPbj:b-w8122p) ([raw file](https://github.com/batfish/batfish/blob/8287f66f547f80a9e75796f309655bafede8d179/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConversions.java#L352)):*
> ```Java
>           aclNameToRules
>               .computeIfAbsent(ruleKeyParts[0], aclName -> new TreeSet<>())
>               .add(new AclRuleWithName(ruleKeyParts[1], value));
> ```

why are we actually modeling IPv6 rules here? Are they not converted somewhere later?



_Code quote:_
```Java
          aclNameToRules
              .computeIfAbsent(ruleKeyParts[0], aclName -> new TreeSet<>())
              .add(new AclRuleWithName(ruleKeyParts[1], value));
```

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8231)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConversions.java, line 352 at r2](https://reviewable.io/reviews/batfish/batfish/8231#-N-6Kpl7ComcAQqvJPbi:-N-6yAaT8CETTAlT2YUU:b-po2rvo) ([raw file](https://github.com/batfish/batfish/blob/8287f66f547f80a9e75796f309655bafede8d179/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConversions.java#L352)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

why are we actually modeling IPv6 rules here? Are they not converted somewhere later?
</blockquote></details>

I actually don't know yet how IPv6 rules are encoded. They could be mixed in with v4 rules, using fields SRC_IPV6 etc., and/or you might need the IP_TYPE field.  (https://gitcode.net/mirrors/Azure/SONiC/-/blob/202006_release_notes/sonic-acl.yang?from_codechina=yes). Currently, parsing will fail (by design) if we see either of those fields.  We'll need to iterate on the model as we see more examples. 

We can go either way on ether_type check at the moment.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8231)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi)

**Pull request merged**
