### PR TITLE
Cisco: split IOS and ASA parsers

### PR DESCRIPTION
**Pull request by dhalperi**

### CODE REVIEW

**Comment by dhalperi** [comment]
*[a discussion](https://reviewable.io/reviews/batfish/batfish/6719#-MVYjbLaE7tCBVc_OGFD:-MVYjbLb17QWRVsFqazY:bgjiqp4) (no related file):*
Working: long way to go, including Maven integration.

---

**Review by arifogel — COMMENTED** [review]
> Reviewed 441 of 441 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6719)* status: 438 of 507 files reviewed, 1 unresolved discussion (waiting on @arifogel and @dhalperi)

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, 51 of 51 files at r3, 17 of 17 files at r4, 10 of 10 files at r5, 5 of 5 files at r6, 10 of 10 files at r7.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6719)* status: all files reviewed, 2 unresolved discussions (waiting on @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 2960 at r3](https://reviewable.io/reviews/batfish/batfish/6719#-MVYpgu64kP2GaGjl8XF:-MVYpgu64kP2GaGjl8XG:b2ni3xm) ([raw file](https://github.com/batfish/batfish/blob/dc481f6b64d97241e6e32f0ad3f7bf41b6e049f2/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L2960)):*
> ```Java
>      * any [inside|outside] interface.
>      */
>     if (_vendor == ConfigurationFormat.CISCO_IOS || _vendor == ConfigurationFormat.CISCO_IOS_XR) {
> ```

hah
___
*[projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java, line 640 at r3](https://reviewable.io/reviews/batfish/batfish/6719#-MVYnfVU5nM2OAbdLm73:-MVYnfVU5nM2OAbdLm74:bvydt9y) ([raw file](https://github.com/batfish/batfish/blob/7868f4ec736043f974845fb27c172ddfb1eb5b53/projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java#L640)):*
> ```Java
>                         hasLogin(hasListForKey(hasMethod(GROUP_USER_DEFINED), "telnet")))))));
> 
>     // test IOS config
> ```

Did you mean to remove this?

**Comment by dhalperi** [comment]
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 2960 at r3](https://reviewable.io/reviews/batfish/batfish/6719#-MVYpgu64kP2GaGjl8XF:-MVZ5O_S9MAMDjeEX-Ri:b-xnuhzm) ([raw file](https://github.com/batfish/batfish/blob/dc481f6b64d97241e6e32f0ad3f7bf41b6e049f2/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L2960)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

hah
</blockquote></details>

Removed in a later commit.

**Comment by dhalperi** [comment]
___
*[projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java, line 640 at r3](https://reviewable.io/reviews/batfish/batfish/6719#-MVYnfVU5nM2OAbdLm73:-MVZ6i81A0Bx6TqdC9YB:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/7868f4ec736043f974845fb27c172ddfb1eb5b53/projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java#L640)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Did you mean to remove this?
</blockquote></details>

Done.

**Review by arifogel — COMMENTED** [review]
> Reviewed 20 of 20 files at r8, 3 of 3 files at r9, 13 of 13 files at r10, 15 of 15 files at r11, 157 of 157 files at r12, 1 of 1 files at r13, 1 of 1 files at r14, 2 of 2 files at r15, 9 of 9 files at r16, 1 of 1 files at r17, 7 of 7 files at r18, 4 of 4 files at r19.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6719)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi)

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r20, 17 of 40 files at r21.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6719)* status: 310 of 323 files reviewed, 1 unresolved discussion (waiting on @arifogel and @dhalperi)

**Review by arifogel — COMMENTED** [review]
> Reviewed 23 of 40 files at r21, 3 of 3 files at r22, 10 of 10 files at r23, 2 of 2 files at r24, 2 of 2 files at r25.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6719)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi)

**Review by arifogel — COMMENTED** [review]
> Reviewed 2 of 2 files at r26, 1 of 1 files at r27.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6719)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by arifogel — COMMENTED** [review]
> Reviewed 29 of 29 files at r28.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6719)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
