### PR TITLE
move ForwardingAnalysis to DataPlane, make IncrementalDataPlane immutable

### PR DESCRIPTION
**Pull request by anothermattbrown**
- move cached ForwardingAnalysis objects out of Batfish and into their
  corresponding DataPlane. This reduces the opportunity for bugs caused
  by using the wrong key to look up the ForwardingAnalysis (thus getting
  the wrong one).
- Made IncrementalDataPlane immutable (except for transient fields) and 
  added a builder. This required some small changes to IncrementalDataPlaneEngine.
- Now that IncrementalDataPlane is immutable, we can cache the results
  of its expensive non-getter methods. This is also how we cache 
  ForwardingAnalysis (so it is still computed lazily).
- Use CommonUtil.toImmutable(Sorted)Map when possible, for improved
  readability.

### CODE REVIEW

**Comment by progwriter** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed, 5 unresolved discussions (waiting on @anothermattbrown)

---

*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlane.java, line 52 at r1](https://reviewable.io/reviews/batfish/batfish/1647#-LEqweO56_tqLrJOTZvt:-LEqweO56_tqLrJOTZvu:b-b0zu4n) ([raw file](https://github.com/batfish/batfish/blob/8f510fc421509f08b5b539e9105f2f87b05b7baf/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlane.java#L52)):*
> ```Java
> 
>     public Builder setIpOwners(Map<Ip, Set<String>> ipOwners) {
>       _ipOwners = ImmutableMap.copyOf(ipOwners);
> ```

FYI: I had actually planned to delete ipOwners & co from DP, since they are simply values computed using CommonUtil functions and then set on DP. Used in very few places, don't rely on them being available in the long run.

---

*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlane.java, line 237 at r1](https://reviewable.io/reviews/batfish/batfish/1647#-LEqzDoG-HBblh__JZM1:-LEqzDoG-HBblh__JZM2:bv80thb) ([raw file](https://github.com/batfish/batfish/blob/8f510fc421509f08b5b539e9105f2f87b05b7baf/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlane.java#L237)):*
> ```Java
>   }
> 
>   private SortedMap<String, SortedMap<String, GenericRib<AbstractRoute>>> initRibs() {
> ```

`initRibs` has a specific meaning in other parts of DP computation (i.e., creating/initializing empty RIBs). This isn't that. I'd suggest renaming for consistency, (e.g., collectRibs or something of that sort).

Similar comment for the FIB function above.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1647)*

**Comment by anothermattbrown** [comment]
Review status: all files reviewed, 4 unresolved discussions (waiting on @anothermattbrown and @progwriter)

---

*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlane.java, line 52 at r1](https://reviewable.io/reviews/batfish/batfish/1647#-LEqweO56_tqLrJOTZvt:-LEr6aO118yVIEyhOpJc:b2nhll9) ([raw file](https://github.com/batfish/batfish/blob/8f510fc421509f08b5b539e9105f2f87b05b7baf/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlane.java#L52)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

FYI: I had actually planned to delete ipOwners & co from DP, since they are simply values computed using CommonUtil functions and then set on DP. Used in very few places, don't rely on them being available in the long run.
</blockquote></details>

Ok.

---

*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlane.java, line 138 at r1](https://reviewable.io/reviews/batfish/batfish/1647#-LEqiWQfBu9kK8cc3xJG:-LEr6v0DB9NuJjqhHFMO:b-3gihs) ([raw file](https://github.com/batfish/batfish/blob/8f510fc421509f08b5b539e9105f2f87b05b7baf/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlane.java#L138)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

See `InlineCommunitySet`
</blockquote></details>

I originally used `Suppliers.memoize`, but that didn't work because this field is `transient`. I figured we don't want to serialize this, do we? 

I can make these `Supplier`s and initialize them here via `_forwardingAnalysis = Suppliers.memoize(this::initForwardingAnalysis)`. Is that better than just making this method `synchronized`?

---

*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlane.java, line 237 at r1](https://reviewable.io/reviews/batfish/batfish/1647#-LEqzDoG-HBblh__JZM1:-LEr7M2i6ikWhm_pBivn:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/8f510fc421509f08b5b539e9105f2f87b05b7baf/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlane.java#L237)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

`initRibs` has a specific meaning in other parts of DP computation (i.e., creating/initializing empty RIBs). This isn't that. I'd suggest renaming for consistency, (e.g., collectRibs or something of that sort).

Similar comment for the FIB function above.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1647)*

**Comment by anothermattbrown** [comment]
Review status: 8 of 10 files reviewed, 4 unresolved discussions (waiting on @arifogel, @progwriter, and @anothermattbrown)

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/MockDataPlane.java, line 24 at r1](https://reviewable.io/reviews/batfish/batfish/1647#-LEqhiPI8EnMg-Qaqfbv:-LEr8qey4Dfq_U6CuegK:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/8f510fc421509f08b5b539e9105f2f87b05b7baf/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/MockDataPlane.java#L24)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

`public` -> `private`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1647)*

**Comment by anothermattbrown** [comment]
Review status: 5 of 21 files reviewed, 4 unresolved discussions (waiting on @arifogel and @progwriter)

---

*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java, line 107 at r1](https://reviewable.io/reviews/batfish/batfish/1647#-LEqhyXC5M16mWuSk-OG:-LErCWY83W-J0rCnZcFn:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/8f510fc421509f08b5b539e9105f2f87b05b7baf/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java#L107)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

I believe this is germane to this PR:
Please get rid of extraneous `ForwardingAnalysis` parameters for functions that take in a `DataPlane`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1647)*

**Comment by arifogel** [comment]
You are become death, destroyer of unnecessary parameters!

---

Reviewed 16 of 16 files at r2.
Review status: all files reviewed, 4 unresolved discussions (waiting on @arifogel, @progwriter, and @anothermattbrown)

---

*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlane.java, line 138 at r1](https://reviewable.io/reviews/batfish/batfish/1647#-LEqiWQfBu9kK8cc3xJG:-LErL6y_ANeNr5qgCV_5:b-97ykc8) ([raw file](https://github.com/batfish/batfish/blob/8f510fc421509f08b5b539e9105f2f87b05b7baf/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlane.java#L138)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

I originally used `Suppliers.memoize`, but that didn't work because this field is `transient`. I figured we don't want to serialize this, do we? 

I can make these `Supplier`s and initialize them here via `_forwardingAnalysis = Suppliers.memoize(this::initForwardingAnalysis)`. Is that better than just making this method `synchronized`?
</blockquote></details>

Don't make the field transient, as indicated above.

---

*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlane.java, line 89 at r2](https://reviewable.io/reviews/batfish/batfish/1647#-LErKTHgExo3-71CiNQU:-LErKTHgExo3-71CiNQV:b-ex677c) ([raw file](https://github.com/batfish/batfish/blob/40ee4b569fa08e39282e1e708cba556e3990f0e9/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlane.java#L89)):*
> ```Java
>   private final transient Network<BgpNeighbor, BgpSession> _bgpTopology;
> 
>   private transient Supplier<Map<String, Configuration>> _configurations;
> ```

I don't think these can be transient. How do they get instantiated? Instead, I believe they should be final. Remember only the Supplier gets Serialized, not the supplied.
Also note that you need to use a serializable supplier. The only way to satisfy all IDEs and style checkers that I've seen is to use a class for that implementing the `Supplier<T>` and `Serializable` interfaces. See `InlineCommunitySet` for an example.

---

*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlane.java, line 172 at r2](https://reviewable.io/reviews/batfish/batfish/1647#-LErKq5P2YwdsvqF7pu6:-LErKq5P2YwdsvqF7pu7:b-ga8qwl) ([raw file](https://github.com/batfish/batfish/blob/40ee4b569fa08e39282e1e708cba556e3990f0e9/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlane.java#L172)):*
> ```Java
>   @Override
>   public ForwardingAnalysis getForwardingAnalysis() {
>     if (_forwardingAnalysis == null) {
> ```

The supplier should be a field. This function would just call the `get` function of the supplier. No null check should occur, since the only field that should exist is the supplier.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1647#-:-LErLvFS18zS1F15vVeZ:b-veowma)*

**Comment by anothermattbrown** [comment]
Review status: 20 of 21 files reviewed, 4 unresolved discussions (waiting on @arifogel, @anothermattbrown, and @progwriter)

---

*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlane.java, line 138 at r1](https://reviewable.io/reviews/batfish/batfish/1647#-LEqiWQfBu9kK8cc3xJG:-LErSCDNEwDD5Y5y4Xml:bb7efny) ([raw file](https://github.com/batfish/batfish/blob/8f510fc421509f08b5b539e9105f2f87b05b7baf/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlane.java#L138)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Don't make the field transient, as indicated above.
</blockquote></details>

cool

---

*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlane.java, line 89 at r2](https://reviewable.io/reviews/batfish/batfish/1647#-LErKTHgExo3-71CiNQU:-LErRyr34Vamt6Vp7gp7:bo3okma) ([raw file](https://github.com/batfish/batfish/blob/40ee4b569fa08e39282e1e708cba556e3990f0e9/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlane.java#L89)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

I don't think these can be transient. How do they get instantiated? Instead, I believe they should be final. Remember only the Supplier gets Serialized, not the supplied.
Also note that you need to use a serializable supplier. The only way to satisfy all IDEs and style checkers that I've seen is to use a class for that implementing the `Supplier<T>` and `Serializable` interfaces. See `InlineCommunitySet` for an example.
</blockquote></details>

OK got it, thanks. Quite a nice solution, now that I can see it :P

---

*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlane.java, line 172 at r2](https://reviewable.io/reviews/batfish/batfish/1647#-LErKq5P2YwdsvqF7pu6:-LErS-dV836htcbEP2qw:b23tvlz) ([raw file](https://github.com/batfish/batfish/blob/40ee4b569fa08e39282e1e708cba556e3990f0e9/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlane.java#L172)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

The supplier should be a field. This function would just call the `get` function of the supplier. No null check should occur, since the only field that should exist is the supplier.
</blockquote></details>

yep yep yep

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1647)*

**Comment by arifogel** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed, 1 unresolved discussion (waiting on @progwriter)

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1647)*

**Comment by arifogel** [comment]
:lgtm:

---

Review status: all files reviewed, 1 unresolved discussion (waiting on @progwriter)

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1647#-:-LEra36J2paT9woXk_0q:bnfp4nl)*

**Comment by arifogel** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @progwriter)

---

*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlane.java, line 83 at r3](https://reviewable.io/reviews/batfish/batfish/1647#-LEro2i28IrI0CuXeWjp:-LEro2i28IrI0CuXeWjq:b-vsv5df) ([raw file](https://github.com/batfish/batfish/blob/47bfe537e0d92ebd4f6e7c5340a4f910614f7ec5/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlane.java#L83)):*
> ```Java
>   }
> 
>   public class ConfigurationsSupplier
> ```

These classes can be `private` and `final`

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1647)*

**Comment by anothermattbrown** [comment]
Review status: 20 of 21 files reviewed, all discussions resolved (waiting on @arifogel)

---

*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlane.java, line 83 at r3](https://reviewable.io/reviews/batfish/batfish/1647#-LEro2i28IrI0CuXeWjp:-LEthhRgBAU-9nG3kHeJ:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/47bfe537e0d92ebd4f6e7c5340a4f910614f7ec5/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlane.java#L83)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

These classes can be `private` and `final`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1647)*

**Comment by anothermattbrown** [comment]
Reviewed 5 of 10 files at r1, 15 of 16 files at r2, 1 of 1 files at r4.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1647)*

**Pull request merged**
