### PR TITLE
BatfishObjectMapper: cleanup APIs and usage

### PR DESCRIPTION
**Pull request by dhalperi**
ObjectMapper/ObjectWriter is threadsafe and should not be mutated after configuration, so why not make it a singleton?

### CODE REVIEW

**Comment by progwriter** [comment]
Reviewed 43 of 43 files at r1.
Review status: 39 of 43 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/1060)*

**Comment by progwriter** [comment]
:lgtm:

---

Review status: 39 of 43 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/1060#-:-L7k9UoRiTygLZxAZtw4:bnfp4nl)*

**Comment by progwriter** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/1060)*

**Comment by arifogel** [comment]
:lgtm: High level: I wonder how many pretty prints don't need to be.

---

Reviewed 39 of 43 files at r1, 4 of 4 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/util/BatfishObjectMapper.java, line 20 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1060#-L7kBsUZ0bjKcaaOfRTD:-L7kBsUZ0bjKcaaOfRTE:b-16b8uf) ([raw file](https://github.com/batfish/batfish/blob/bc78c4c1112bf08e770d8e4c6f6fd7f6b370d81a/projects/batfish-common-protocol/src/main/java/org/batfish/common/util/BatfishObjectMapper.java#L20)):*
> ```Java
>   private static final ObjectMapper MAPPER = baseMapper();
>   private static final ObjectWriter WRITER = MAPPER.writer();
>   private static final PrettyPrinter PRETTY_PRINTER = new PrettyPrinter();
> ```

Newline in between members, please.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/util/BatfishObjectMapper.java, line 28 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1060#-L7kC-Nn9-Pxv1ASwSEO:-L7kC-Nn9-Pxv1ASwSEP:b-16b8uf) ([raw file](https://github.com/batfish/batfish/blob/bc78c4c1112bf08e770d8e4c6f6fd7f6b370d81a/projects/batfish-common-protocol/src/main/java/org/batfish/common/util/BatfishObjectMapper.java#L28)):*
> ```Java
>           .enable(SerializationFeature.INDENT_OUTPUT)
>           .setSerializationInclusion(Include.ALWAYS)
>           .writer(PRETTY_PRINTER);
> ```

Newline in between members, please.

---

*[projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrServiceTest.java, line 72 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1060#-L7kDVPX6AKfOYDYzflF:-L7kDVPX6AKfOYDYzflG:b-83sjoh) ([raw file](https://github.com/batfish/batfish/blob/bc78c4c1112bf08e770d8e4c6f6fd7f6b370d81a/projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrServiceTest.java#L72)):*
> ```Java
>     Response response = _service.getContainer("100", "0.0.0", _containerName);
>     String containerJson = response.getEntity().toString();
>     assertThat(containerJson, equalTo("{\"name\":\"myContainer\"}"));
> ```

Nice!

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1060#-:-L7kVyPT3HXEX8L3mwAw:b-fxkilq)*

**Comment by dhalperi** [comment]
Review status: 42 of 43 files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/util/BatfishObjectMapper.java, line 20 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1060#-L7kBsUZ0bjKcaaOfRTD:-L7kimKn1UBZ2N3QViH6:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/bc78c4c1112bf08e770d8e4c6f6fd7f6b370d81a/projects/batfish-common-protocol/src/main/java/org/batfish/common/util/BatfishObjectMapper.java#L20)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Newline in between members, please.
</blockquote></details>

Done.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/util/BatfishObjectMapper.java, line 28 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1060#-L7kC-Nn9-Pxv1ASwSEO:-L7killlAq_jQgi7hJEF:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/bc78c4c1112bf08e770d8e4c6f6fd7f6b370d81a/projects/batfish-common-protocol/src/main/java/org/batfish/common/util/BatfishObjectMapper.java#L28)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Newline in between members, please.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1060)*

**Comment by arifogel** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1060)*

**Pull request merged**
