### PR TITLE
Checkpoint vs fix up nat rulebase objects

### PR DESCRIPTION
**Pull request by arifogel**
- just serialize objects-dictionary directly
- flesh out special objects like Globals and CpmiAnyObject

### CODE REVIEW

**Review by corinaminer — COMMENTED** [review]
> Reviewed 15 of 15 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7259)* status: all files reviewed, 2 unresolved discussions (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/CpmiAnyObject.java, line 44 at r1](https://reviewable.io/reviews/batfish/batfish/7259#-MhaILLO5IGKR4PP7lXm:-MhaILLO5IGKR4PP7lXn:b-93drak) ([raw file](https://github.com/batfish/batfish/blob/7658461e300dcb139f13b3d641c496224aa8f998/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/CpmiAnyObject.java#L44)):*
> ```Java
>   private static @Nonnull CpmiAnyObject create(
>       @JsonProperty(PROP_NAME) @Nullable String name, @JsonProperty(PROP_UID) @Nullable Uid uid) {
>     checkArgument(name != null, "Missing %s", PROP_NAME);
> ```

should there still be a name?
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/Global.java, line 33 at r2](https://reviewable.io/reviews/batfish/batfish/7259#-MhaKbrg6SCmvgXQyBud:-MhaKbrg6SCmvgXQyBue:b-fbu949) ([raw file](https://github.com/batfish/batfish/blob/2b89ac0255fb1b691cce26c0ac8105d556399995/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/Global.java#L33)):*
> ```Java
> 
>   protected Global(String name, Uid uid) {
>     super(name, uid);
> ```

Why give these names at all? why not just let the class indicate which type of global it is?

If the answer is to debug sources of `UnhandledGlobal`, i think that makes sense

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7259)* status: all files reviewed, 2 unresolved discussions (waiting on @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/CpmiAnyObject.java, line 44 at r1](https://reviewable.io/reviews/batfish/batfish/7259#-MhaILLO5IGKR4PP7lXm:-MhaMD3A3GRMefMiG6SU:bl2xjla) ([raw file](https://github.com/batfish/batfish/blob/7658461e300dcb139f13b3d641c496224aa8f998/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/CpmiAnyObject.java#L44)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

should there still be a name?
</blockquote></details>

For now I want it there in case another name pops up. It should always appear, anyhow.
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/Global.java, line 33 at r2](https://reviewable.io/reviews/batfish/batfish/7259#-MhaKbrg6SCmvgXQyBud:-MhaM7nPEFHfz7VOOaFD:bit37mz) ([raw file](https://github.com/batfish/batfish/blob/2b89ac0255fb1b691cce26c0ac8105d556399995/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/Global.java#L33)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Why give these names at all? why not just let the class indicate which type of global it is?

If the answer is to debug sources of `UnhandledGlobal`, i think that makes sense
</blockquote></details>

The answer is to debug sources of `UnhandledGlobal`.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7259)* status: 15 of 16 files reviewed, 1 unresolved discussion (waiting on @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/CpmiAnyObject.java, line 44 at r1](https://reviewable.io/reviews/batfish/batfish/7259#-MhaILLO5IGKR4PP7lXm:-MhaMgXB06zPUl0JWq2C:b-c604oe) ([raw file](https://github.com/batfish/batfish/blob/7658461e300dcb139f13b3d641c496224aa8f998/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/CpmiAnyObject.java#L44)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

For now I want it there in case another name pops up. It should always appear, anyhow.
</blockquote></details>

..well I guess we aren't using the value. Removed.

**Review by corinaminer — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7259#-:-MhaN4RV-2j8J-sIQZWv:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Pull request merged**
