### PR TITLE
IOS: Add session info to interfaces

### PR DESCRIPTION
**Pull request by corinaminer**

### CODE REVIEW

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6653)* status: all files reviewed, 2 unresolved discussions (waiting on @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 1936 at r2](https://reviewable.io/reviews/batfish/batfish/6653#-MUExKDq848sbEdfmfFQ:-MUExKDrEvAoSSvZWryH:bowvi7d) ([raw file](https://github.com/batfish/batfish/blob/392663063b5abc4d39aa7a8d018183b7363988b1/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L1936)):*
> ```
> Assume each interface has its own session info (sessions are not shared by interfaces).
> ```
Is this a safe assumption? It would seem reasonable to allow return traffic to enter any interface on the same (in/out)side as `newIface`.
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 1951 at r2](https://reviewable.io/reviews/batfish/batfish/6653#-MUEwJjQ24EwwO0nusIG:-MUEwJjQ24EwwO0nusIH:b-ed9tsa) ([raw file](https://github.com/batfish/batfish/blob/392663063b5abc4d39aa7a8d018183b7363988b1/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L1951)):*
> ```
> Action.PRE_NAT_FIB_LOOKUP
> ```
Adding the FirewallSessionInteraceInfo to this (inside) interface will cause sessions to be created for all flows exiting this interface. Presumably we only want to create sessions for flows that entered an outside interface. Can we assume that?

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6653)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @anothermattbrown and @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 1936 at r2](https://reviewable.io/reviews/batfish/batfish/6653#-MUExKDq848sbEdfmfFQ:-MUFMRRjBD9i9JK1Omdv:b-qsr5q4) ([raw file](https://github.com/batfish/batfish/blob/392663063b5abc4d39aa7a8d018183b7363988b1/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L1936)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

> ```
> Assume each interface has its own session info (sessions are not shared by interfaces).
> ```
Is this a safe assumption? It would seem reasonable to allow return traffic to enter any interface on the same (in/out)side as `newIface`.
</blockquote></details>

Good call -- i just checked in GNS3 and you're right. Fixed.
___
*[tests/parsing-tests/unit-tests-vimodel.ref, line 0 at r3](https://reviewable.io/reviews/batfish/batfish/6653#-MUGWjdyBqLIPAD0mIo8:-MUGWjdyBqLIPAD0mIo9:b-xbq08q) ([raw file](https://github.com/batfish/batfish/blob/0ac838207ebeff667e17e06787c447d42e846392/tests/parsing-tests/unit-tests-vimodel.ref#L0)):*
It's upsetting that an interface's session action changed, but it's just because that interface's config has both `ip nat outside` and `ip nat inside`. `ip nat outside` comes second, so `POST_NAT_FIB_LOOKUP` seems like the more correct option. (real interface configs can't have both and configuring one will overwrite the other.)

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6653)* status: all files reviewed, 3 unresolved discussions (waiting on @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 1936 at r2](https://reviewable.io/reviews/batfish/batfish/6653#-MUExKDq848sbEdfmfFQ:-MUPRF9H58teY-RwU1AC:b-x5yywr) ([raw file](https://github.com/batfish/batfish/blob/392663063b5abc4d39aa7a8d018183b7363988b1/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L1936)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Good call -- i just checked in GNS3 and you're right. Fixed.
</blockquote></details>

Does this comment need to be updated?

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6653)* status: all files reviewed, 2 unresolved discussions (waiting on @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 1936 at r2](https://reviewable.io/reviews/batfish/batfish/6653#-MUExKDq848sbEdfmfFQ:-MUUo5f915KUG_E5skxC:b-snxt3g) ([raw file](https://github.com/batfish/batfish/blob/392663063b5abc4d39aa7a8d018183b7363988b1/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L1936)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

Does this comment need to be updated?
</blockquote></details>

no, this comment is specific to ASA. There's a comment addressing non-ASA behavior down with the new conversion code

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6653)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @anothermattbrown)

___
*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 1951 at r2](https://reviewable.io/reviews/batfish/batfish/6653#-MUEwJjQ24EwwO0nusIG:-MUjQNlFAnl_xU01OkAJ:b-7rl0jd) ([raw file](https://github.com/batfish/batfish/blob/392663063b5abc4d39aa7a8d018183b7363988b1/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L1951)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

> ```
> Action.PRE_NAT_FIB_LOOKUP
> ```
Adding the FirewallSessionInteraceInfo to this (inside) interface will cause sessions to be created for all flows exiting this interface. Presumably we only want to create sessions for flows that entered an outside interface. Can we assume that?
</blockquote></details>

done.

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6653)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
