### PR TITLE
SearchRoutePolicies: Handle CallExpr

### PR DESCRIPTION
**Pull request by millstein**
Adds support to SearchRoutePolicies for policies that call other policies via the CallExpr expression.  Doing so also required updating symbolic analysis of expressions to account for possible route updates that can occur in those expressions.

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7002)* status: all files reviewed, 4 unresolved discussions (waiting on @millstein)

___
*[projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java, line 221 at r3](https://reviewable.io/reviews/batfish/batfish/7002#-Ma-lJD65qJ1cAdLMT9z:-Ma-lJD65qJ1cAdLMTA-:b-rb5imk) ([raw file](https://github.com/batfish/batfish/blob/4d3b9c8be799fd30f51e439c48c30d460c0c78d4/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java#L221)):*
> ```Java
>       BDD acc = factory.zero();
>       for (BooleanExpr be : d.getDisjuncts()) {
>         result = compute(be, toTransferBDDState(p.indent(), result));
> ```

Are you keeping transformations caused by early disjuncts that evaluate to FALSE?
___
*[projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java, line 322 at r3](https://reviewable.io/reviews/batfish/batfish/7002#-Ma-l88jBz0o6NNIm1LE:-Ma-l88jBz0o6NNIm1LF:b5q248f) ([raw file](https://github.com/batfish/batfish/blob/4d3b9c8be799fd30f51e439c48c30d460c0c78d4/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java#L322)):*
> ```Java
> 
>       // save callee state
>       BDD oldReturnAssigned = result.getReturnAssignedValue();
> ```

What state exactly is being saved and restored?

My understanding is that any transformations in the called should be kept, regardless of the return value.
___
*[projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferBDDTest.java, line 638 at r3](https://reviewable.io/reviews/batfish/batfish/7002#-Ma-jRi9AmAkJobMij8n:-Ma-jRi9AmAkJobMij8o:bddco6o) ([raw file](https://github.com/batfish/batfish/blob/4d3b9c8be799fd30f51e439c48c30d460c0c78d4/projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferBDDTest.java#L638)):*
> ```Java
>             .setOwner(_baseConfig)
>             .addStatement(
>                 new If(
> ```

Why the `If`?
___
*[projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferBDDTest.java, line 648 at r3](https://reviewable.io/reviews/batfish/batfish/7002#-Ma-hDuPANMYp9HpYNQU:-Ma-hDuQAYLULcQxFMNR:b-tuh970) ([raw file](https://github.com/batfish/batfish/blob/4d3b9c8be799fd30f51e439c48c30d460c0c78d4/projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferBDDTest.java#L648)):*
> ```Java
>             .addStatement(
>                 new If(
>                     new Conjunction(
> ```

FYI There is currently a bug that non-pure conjunctions containing a side-effectful conjunct that evaluates to FALSE will be simplified to FALSE. So while this change is correct, the behavior may temporarily not match the contemporary buggy behavior for `RoutingPolicy` generated via the full pipeline.

This bug affects multiple simplifications.

**Review by millstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7002)* status: all files reviewed, 4 unresolved discussions (waiting on @arifogel)

___
*[projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java, line 221 at r3](https://reviewable.io/reviews/batfish/batfish/7002#-Ma-lJD65qJ1cAdLMT9z:-Ma06t-P5w4NtPdtrKT4:bk0esz4) ([raw file](https://github.com/batfish/batfish/blob/4d3b9c8be799fd30f51e439c48c30d460c0c78d4/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java#L221)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Are you keeping transformations caused by early disjuncts that evaluate to FALSE?
</blockquote></details>

Good question.  Yes, currently that is happening.  What is the intended semantics?  Should any transformations done by disjuncts that evaluate to false be ignored?  Also, should the semantics be short-circuiting, so after the first true disjunct we are done, thereby ignoring later disjuncts and their possible transformations?

Similar question for conjunctions -- should transformations done by conjuncts that evaluate to false be ignored, and should it short-circuit?
___
*[projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java, line 322 at r3](https://reviewable.io/reviews/batfish/batfish/7002#-Ma-l88jBz0o6NNIm1LE:-Ma07LyiDiHMi0-PpaK1:b-uvgbc6) ([raw file](https://github.com/batfish/batfish/blob/4d3b9c8be799fd30f51e439c48c30d460c0c78d4/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java#L322)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

What state exactly is being saved and restored?

My understanding is that any transformations in the called should be kept, regardless of the return value.
</blockquote></details>

This BDD tracks the conditions under which the current policy returns.  So it is policy-local, which is why it is being saved and restored.  I think it's playing a similar role to why CallExpr::evaluate sets the return to false after the call.
___
*[projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferBDDTest.java, line 638 at r3](https://reviewable.io/reviews/batfish/batfish/7002#-Ma-jRi9AmAkJobMij8n:-Ma07mou1CymxrV3fgyR:btzzq3e) ([raw file](https://github.com/batfish/batfish/blob/4d3b9c8be799fd30f51e439c48c30d460c0c78d4/projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferBDDTest.java#L638)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Why the `If`?
</blockquote></details>

There was a bug in handling of Conjunctions that I found during manual testing, where the TransferBDDState that was passed on from one conjunct to the next was not well formed (and so violated an assertion), but it only happens when a new BDDRoute is constructed and that happens in If.
___
*[projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferBDDTest.java, line 648 at r3](https://reviewable.io/reviews/batfish/batfish/7002#-Ma-hDuPANMYp9HpYNQU:-Ma088ol5D6r9DXH5vLX:b-lu18vt) ([raw file](https://github.com/batfish/batfish/blob/4d3b9c8be799fd30f51e439c48c30d460c0c78d4/projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferBDDTest.java#L648)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

FYI There is currently a bug that non-pure conjunctions containing a side-effectful conjunct that evaluates to FALSE will be simplified to FALSE. So while this change is correct, the behavior may temporarily not match the contemporary buggy behavior for `RoutingPolicy` generated via the full pipeline.

This bug affects multiple simplifications.
</blockquote></details>

Ah, this relates to your first comment above.  What is the correct semantics for conjunctions?

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7002)* status: all files reviewed, 2 unresolved discussions (waiting on @millstein)

___
*[projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java, line 221 at r3](https://reviewable.io/reviews/batfish/batfish/7002#-Ma-lJD65qJ1cAdLMT9z:-Ma0t3t5AJXdaLq7-R5S:b3ut1b0) ([raw file](https://github.com/batfish/batfish/blob/4d3b9c8be799fd30f51e439c48c30d460c0c78d4/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java#L221)):*
<details><summary><i>Previously, millstein (Todd Millstein) wrote…</i></summary><blockquote>

Good question.  Yes, currently that is happening.  What is the intended semantics?  Should any transformations done by disjuncts that evaluate to false be ignored?  Also, should the semantics be short-circuiting, so after the first true disjunct we are done, thereby ignoring later disjuncts and their possible transformations?

Similar question for conjunctions -- should transformations done by conjuncts that evaluate to false be ignored, and should it short-circuit?
</blockquote></details>

Transformations cannot be undone, but short-circuiting does occur.
___
*[projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java, line 322 at r3](https://reviewable.io/reviews/batfish/batfish/7002#-Ma-l88jBz0o6NNIm1LE:-Ma0tEm44Da2nzfbI9zQ:b2ni9bh) ([raw file](https://github.com/batfish/batfish/blob/4d3b9c8be799fd30f51e439c48c30d460c0c78d4/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java#L322)):*
<details><summary><i>Previously, millstein (Todd Millstein) wrote…</i></summary><blockquote>

This BDD tracks the conditions under which the current policy returns.  So it is policy-local, which is why it is being saved and restored.  I think it's playing a similar role to why CallExpr::evaluate sets the return to false after the call.
</blockquote></details>

ok.
___
*[projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferBDDTest.java, line 638 at r3](https://reviewable.io/reviews/batfish/batfish/7002#-Ma-jRi9AmAkJobMij8n:-Ma0tZ2c7QYrfz91kKIJ:btzx9gf) ([raw file](https://github.com/batfish/batfish/blob/4d3b9c8be799fd30f51e439c48c30d460c0c78d4/projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferBDDTest.java#L638)):*
<details><summary><i>Previously, millstein (Todd Millstein) wrote…</i></summary><blockquote>

There was a bug in handling of Conjunctions that I found during manual testing, where the TransferBDDState that was passed on from one conjunct to the next was not well formed (and so violated an assertion), but it only happens when a new BDDRoute is constructed and that happens in If.
</blockquote></details>

ok as long as it has value.
___
*[projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferBDDTest.java, line 648 at r3](https://reviewable.io/reviews/batfish/batfish/7002#-Ma-hDuPANMYp9HpYNQU:-Ma0tJgl6HkcCr7hEBA0:biguwmd) ([raw file](https://github.com/batfish/batfish/blob/4d3b9c8be799fd30f51e439c48c30d460c0c78d4/projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferBDDTest.java#L648)):*
<details><summary><i>Previously, millstein (Todd Millstein) wrote…</i></summary><blockquote>

Ah, this relates to your first comment above.  What is the correct semantics for conjunctions?
</blockquote></details>

apply side-effects of false conjunct, short-circuit.

**Review by millstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7002)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @arifogel)

___
*[projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java, line 221 at r3](https://reviewable.io/reviews/batfish/batfish/7002#-Ma-lJD65qJ1cAdLMT9z:-Ma1tQ0559rPqOEx7-Wj:bw8438c) ([raw file](https://github.com/batfish/batfish/blob/4d3b9c8be799fd30f51e439c48c30d460c0c78d4/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java#L221)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Transformations cannot be undone, but short-circuiting does occur.
</blockquote></details>

Updated to handle short circuiting for conjunction and disjunction.

**Review by arifogel — COMMENTED** [review]
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7002)* status: all files reviewed, 1 unresolved discussion (waiting on @millstein)

___
*[projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferBDDTest.java, line 815 at r4](https://reviewable.io/reviews/batfish/batfish/7002#-Ma2lXlL40XTs4t540qa:-Ma2lXlM1pkKPslKGAvI:b-5lcrff) ([raw file](https://github.com/batfish/batfish/blob/0fbc1823404e0f7da3b7cc461d7bfc58010bf8ef/projects/minesweeper/src/test/java/org/batfish/minesweeper/bdd/TransferBDDTest.java#L815)):*
> ```Java
>             .ite(firstDisjunctBDD.not(), localPref));
> 
>     // the updates in the second conjunct should not occur unless the first conjunct is true
> ```

Shouldn't it be, "the updates in the second disjunct should not occur unless the first disjunct is false"?

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7002)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @millstein)

**Pull request merged**
