### PR TITLE
A10: Add enabled columns to questions

### PR DESCRIPTION
**Pull request by ratulm**

### CODE REVIEW

**Review by sfraint — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7824)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @ratulm and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7824#-Mr8kiq-8cIjU9cCkD91:-Mr8kiq-8cIjU9cCkD92:b-19alfb) (no related file):*
what about the real server versions? handling separately?

server `enable` (https://github.com/batfish/batfish/blob/master/projects/batfish/src/main/java/org/batfish/vendor/a10/representation/Server.java#L19) and server port `enable` (https://github.com/batfish/batfish/blob/master/projects/batfish/src/main/java/org/batfish/vendor/a10/representation/ServerPort.java#L49)?

---

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7824)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7824#-Mr8kiq-8cIjU9cCkD91:-Mr8m-IU2ZmyHww-0Ga4:b-awbex2) (no related file):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

what about the real server versions? handling separately?

server `enable` (https://github.com/batfish/batfish/blob/master/projects/batfish/src/main/java/org/batfish/vendor/a10/representation/Server.java#L19) and server port `enable` (https://github.com/batfish/batfish/blob/master/projects/batfish/src/main/java/org/batfish/vendor/a10/representation/ServerPort.java#L49)?
</blockquote></details>

interesting that there are so many of them. 

so, for a server/port to be active via the VIP, each of these must be enabled?
 - service group member
 - server port
 - server

---

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7824)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @ratulm and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7824#-Mr8kiq-8cIjU9cCkD91:-Mr9011nB6HBLc3w4BR9:b-k1tq3v) (no related file):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

interesting that there are so many of them. 

so, for a server/port to be active via the VIP, each of these must be enabled?
 - service group member
 - server port
 - server
</blockquote></details>

Yes, I believe that is the case

---

**Review by sfraint — COMMENTED** [review]
> Reviewed 1 of 4 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7824)* status: all files reviewed, 2 unresolved discussions (waiting on @ratulm)

___
*[projects/allinone/src/test/java/org/batfish/question/a10/A10VirtualServerConfigurationAnswererTest.java, line 85 at r3](https://reviewable.io/reviews/batfish/batfish/7824#-Mr9rAyX7xZJuzCHYBB_:-Mr9rAyX7xZJuzCHYBBa:b-4udfze) ([raw file](https://github.com/batfish/batfish/blob/894be3a53c0ee03f0ea1febeca216c267022f943/projects/allinone/src/test/java/org/batfish/question/a10/A10VirtualServerConfigurationAnswererTest.java#L85)):*
> ```Java
>                         equalTo(
>                             ImmutableSet.of(
>                                 ImmutableList.of("s1", "10000", "1.1.1.1", "active"),
> ```

Is `active`/`inactive` supposed to mean anything other than the configured `enable` status?

If not, I'd suggest sticking with the vendor language (`enable` / `disable` / `enabled`)



_Code quote:_
```Java
active"
```
___
*[projects/question/src/main/java/org/batfish/question/a10/A10VirtualServerConfigurationAnswerer.java, line 154 at r3](https://reviewable.io/reviews/batfish/batfish/7824#-Mr9sjyvCqa7huvMz88C:-Mr9sjyvCqa7huvMz88D:b-50lxyw) ([raw file](https://github.com/batfish/batfish/blob/894be3a53c0ee03f0ea1febeca216c267022f943/projects/question/src/main/java/org/batfish/question/a10/A10VirtualServerConfigurationAnswerer.java#L154)):*
> ```Java
>                   node,
>                   virtualServer.getName(),
>                   firstNonNull(virtualServer.getEnable(), true),
> ```

would be preferable to not duplicate this logic here and in A10 VS code



_Code quote:_
```Java
firstNonNull(virtualServer.getEnable(), true)
```

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7824)* status: all files reviewed, 2 unresolved discussions (waiting on @sfraint)

___
*[projects/allinone/src/test/java/org/batfish/question/a10/A10VirtualServerConfigurationAnswererTest.java, line 85 at r3](https://reviewable.io/reviews/batfish/batfish/7824#-Mr9rAyX7xZJuzCHYBB_:-Mr9tgrACwG53OTb_gbf:b-lm9z1i) ([raw file](https://github.com/batfish/batfish/blob/894be3a53c0ee03f0ea1febeca216c267022f943/projects/allinone/src/test/java/org/batfish/question/a10/A10VirtualServerConfigurationAnswererTest.java#L85)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

Is `active`/`inactive` supposed to mean anything other than the configured `enable` status?

If not, I'd suggest sticking with the vendor language (`enable` / `disable` / `enabled`)
</blockquote></details>

I purposely picked different terminology to avoid confusion with configuration terminology. Enable/Disable is config language for a single thing (member, server, serverport), which then begs the question: what are we showing? Active/inactive doesn't have that baggage and we can define that the mapping is active if everything is enabled. 
___
*[projects/question/src/main/java/org/batfish/question/a10/A10VirtualServerConfigurationAnswerer.java, line 154 at r3](https://reviewable.io/reviews/batfish/batfish/7824#-Mr9sjyvCqa7huvMz88C:-Mr9uX3EEg0RSqFvuNpv:b-j2u157) ([raw file](https://github.com/batfish/batfish/blob/894be3a53c0ee03f0ea1febeca216c267022f943/projects/question/src/main/java/org/batfish/question/a10/A10VirtualServerConfigurationAnswerer.java#L154)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

would be preferable to not duplicate this logic here and in A10 VS code
</blockquote></details>

This exact indication does not exist in A10 VS code. What exists is a combination of virtual server enabled plus any of its ports, and I wanted just the former (to match what the user configured). Didn't want to create a new method there just for this, especially because this pattern is reused for several other things in the answerer.

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7824)* status: all files reviewed, 1 unresolved discussion (waiting on @ratulm)

___
*[projects/allinone/src/test/java/org/batfish/question/a10/A10VirtualServerConfigurationAnswererTest.java, line 85 at r3](https://reviewable.io/reviews/batfish/batfish/7824#-Mr9rAyX7xZJuzCHYBB_:-Mr9wDUu7S6wtSCqN0JY:bl80l7n) ([raw file](https://github.com/batfish/batfish/blob/894be3a53c0ee03f0ea1febeca216c267022f943/projects/allinone/src/test/java/org/batfish/question/a10/A10VirtualServerConfigurationAnswererTest.java#L85)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

I purposely picked different terminology to avoid confusion with configuration terminology. Enable/Disable is config language for a single thing (member, server, serverport), which then begs the question: what are we showing? Active/inactive doesn't have that baggage and we can define that the mapping is active if everything is enabled. 
</blockquote></details>

:thumbsup: 

Also (not really a blocker for this PR, just thinking):

How can these semantics be conveyed to users using this question? and similarly, how can users understand what the various elements are in this list?
___
*[projects/question/src/main/java/org/batfish/question/a10/A10VirtualServerConfigurationAnswerer.java, line 154 at r3](https://reviewable.io/reviews/batfish/batfish/7824#-Mr9sjyvCqa7huvMz88C:-Mr9va3cDYEfCSkm_ZCo:b-ba1jet) ([raw file](https://github.com/batfish/batfish/blob/894be3a53c0ee03f0ea1febeca216c267022f943/projects/question/src/main/java/org/batfish/question/a10/A10VirtualServerConfigurationAnswerer.java#L154)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

This exact indication does not exist in A10 VS code. What exists is a combination of virtual server enabled plus any of its ports, and I wanted just the former (to match what the user configured). Didn't want to create a new method there just for this, especially because this pattern is reused for several other things in the answerer. 
</blockquote></details>

I think the virtual-server-only logic should be easy to split out into a helper.

And there is a method for just virtual-server ports (`isVirtualServerPortEnabled`) that can be used below.

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7824)* status: 2 of 5 files reviewed, all discussions resolved (waiting on @sfraint)

___
*[projects/allinone/src/test/java/org/batfish/question/a10/A10VirtualServerConfigurationAnswererTest.java, line 85 at r3](https://reviewable.io/reviews/batfish/batfish/7824#-Mr9rAyX7xZJuzCHYBB_:-Mr9yB7U8OuE4rUOE886:b-v5zzcy) ([raw file](https://github.com/batfish/batfish/blob/894be3a53c0ee03f0ea1febeca216c267022f943/projects/allinone/src/test/java/org/batfish/question/a10/A10VirtualServerConfigurationAnswererTest.java#L85)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

:thumbsup: 

Also (not really a blocker for this PR, just thinking):

How can these semantics be conveyed to users using this question? and similarly, how can users understand what the various elements are in this list?
</blockquote></details>

Maybe not ideal but question documentation? See this as an example https://pybatfish.readthedocs.io/en/latest/notebooks/routingProtocols.html#BGP-Session-Compatibility

**Review by sfraint — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7824)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ratulm)

**Pull request merged**
