### PR TITLE
a test rig to demo automatic outlier detection

### PR DESCRIPTION
**Pull request by millstein**
After loading the new outliers testrig, you can run these questions to demo various forms of outlier detection:

print bfq.perRoleOutliers(hypothesis='sameServers').answer()
print bfq.perRoleOutliers(hypothesis='sameName').answer()
print bfq.perRoleOutliers(hypothesis='sameDefinition').answer()

There are varied root causes (e.g., missing configuration directives, buggy configuration directives, etc.).

---
This change is [Reviewable](https://reviewable.io/reviews/batfish/batfish/819)

### CODE REVIEW

**Comment by ratulm** [comment]
should we create a new test rig to showcase this functionality or inject bugs into the existing example itself?

**Comment by millstein** [comment]
It probably makes sense to have one test rig used to demo all features, if possible.  Is the "example" testrig the one we currently use for that purpose (e.g., the one Samir demo'ed yesterday)?  Adding in the outliers issues there works, as long as doing so doesn't break whatever else is being demo'ed.

**Comment by millstein** [comment]
updated to modify the example test rig

**Comment by ratulm** [comment]
Reviewed 8 of 30 files at r1, 27 of 50 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/819)*

**Comment by ratulm** [comment]
Looks good, thanks! I've deleted this long branch. Please start a new one for further work.

**Pull request merged**
