### PR TITLE
Junos: Parse misc junos syntax

### PR DESCRIPTION
**Pull request by ratulm**

### CODE REVIEW

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7934)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @arifogel)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_forwarding_options.g4, line 141 at r1](https://reviewable.io/reviews/batfish/batfish/7934#-MtMW7PR-ohfdRbWwer3:-MtMW7PR-ohfdRbWwer4:b-euh0r1) ([raw file](https://github.com/batfish/batfish/blob/fe7471ffb943214a028c2f8c3684628517099baf/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_forwarding_options.g4#L141)):*
> ```ANTLR
> fohb_server_null
> :
>    SERVER variable
> ```

because there can be a `<*>` following SERVER
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4, line 489 at r1](https://reviewable.io/reviews/batfish/batfish/7934#-MtMWJCT5arcsq1wTgjs:-MtMWJCT5arcsq1wTgjt:blp4x14) ([raw file](https://github.com/batfish/batfish/blob/fe7471ffb943214a028c2f8c3684628517099baf/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4#L489)):*
> ```ANTLR
> DTCP_ONLY: 'dtcp-only';
> 
> DUMP_ON_PANIC: 'dump-on-panic';
> ```

this token was misspelled and unused  previously

**Review by arifogel — COMMENTED** [review]
> Reviewed 7 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7934)* status: all files reviewed, 3 unresolved discussions (waiting on @ratulm)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_forwarding_options.g4, line 141 at r1](https://reviewable.io/reviews/batfish/batfish/7934#-MtMW7PR-ohfdRbWwer3:-MtQMjyf5NCjHzBfXuyc:b-z9v74f) ([raw file](https://github.com/batfish/batfish/blob/fe7471ffb943214a028c2f8c3684628517099baf/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_forwarding_options.g4#L141)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

because there can be a `<*>` following SERVER
</blockquote></details>

For that, you should do `wildcard | IP_ADDRESS` so it can be used with apply-path
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_system.g4, line 131 at r2](https://reviewable.io/reviews/batfish/batfish/7934#-MtQN_RF51RKDYqE5AuK:-MtQN_RF51RKDYqE5AuL:b-3r6cne) ([raw file](https://github.com/batfish/batfish/blob/18e63910aed16c48b3c3f2c9da21069ecdefb0bb/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_system.g4#L131)):*
> ```ANTLR
>       | DDOS_PROTECTION
>       | DOMAIN_SEARCH
>       | DUMP_ON_PANIC
> ```

Where is the test config for the additions in this file?
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4, line 489 at r1](https://reviewable.io/reviews/batfish/batfish/7934#-MtMWJCT5arcsq1wTgjs:-MtQNpEE6-9bUj4ccpGW:b32w0x) ([raw file](https://github.com/batfish/batfish/blob/fe7471ffb943214a028c2f8c3684628517099baf/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4#L489)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

this token was misspelled and unused  previously
</blockquote></details>

OK

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7934)* status: all files reviewed, 3 unresolved discussions (waiting on @ratulm)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_forwarding_options.g4, line 141 at r1](https://reviewable.io/reviews/batfish/batfish/7934#-MtMW7PR-ohfdRbWwer3:-MtQO7g70q0edPojg4oM:b2tf975) ([raw file](https://github.com/batfish/batfish/blob/fe7471ffb943214a028c2f8c3684628517099baf/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_forwarding_options.g4#L141)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

For that, you should do `wildcard | IP_ADDRESS` so it can be used with apply-path
</blockquote></details>

Actually not sure about that, but `wildcard | IP_ADDRESS` is definitely better than `variable`

**Review by arifogel — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7934)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ratulm)

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7934)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ratulm)

**Pull request merged**
