### PR TITLE
Juniper: add word mode, allow keywords in term names

### PR DESCRIPTION
**Pull request by dhalperi**

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6195)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_applications.g4, line 51 at r1](https://reviewable.io/reviews/batfish/batfish/6195#-MH3Dhl8BP4prM2K_FhI:-MH3Dhl8BP4prM2K_FhJ:b-8who8b) ([raw file](https://github.com/batfish/batfish/blob/03ca9be7d04351cfa2770fd113ebfb662ec26a3b/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_applications.g4#L51)):*
> ```ANTLR
> aa_term
> :
>    TERM name = WORD aa_common+
> ```

Should you use a `word` rule instead of using a token? Are these names case sensitive, for instance? length-limited?
Can also be done separately if desired.

What about quoted names with spaces?

**Comment by dhalperi** [comment]
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_applications.g4, line 51 at r1](https://reviewable.io/reviews/batfish/batfish/6195#-MH3Dhl8BP4prM2K_FhI:-MHE9N8F-jUbtOiAWR56:b-fe3ku1) ([raw file](https://github.com/batfish/batfish/blob/03ca9be7d04351cfa2770fd113ebfb662ec26a3b/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_applications.g4#L51)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Should you use a `word` rule instead of using a token? Are these names case sensitive, for instance? length-limited?
Can also be done separately if desired.

What about quoted names with spaces?
</blockquote></details>

Added a rule, support for spaces.

Length stuff for another day.

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6195)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @arifogel)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4, line 6734 at r2](https://reviewable.io/reviews/batfish/batfish/6195#-MHEA77kEqS6qq92zTBC:-MHEA77kEqS6qq92zTBD:b7w20wl) ([raw file](https://github.com/batfish/batfish/blob/9e630bb74eaccf67b2fe3a4ab6a1e391e1000fd3/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4#L6734)):*
> ```
> (F_NameChar | ' ')*
> ```

FYI I decided we should support quoted names without spaces, which is why we need `*` here: `"aa"`.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6195)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @arifogel)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4, line 6734 at r2](https://reviewable.io/reviews/batfish/batfish/6195#-MHEA77kEqS6qq92zTBC:-MHERuKq5lY2Hrl8pvb6:b-f6ysnz) ([raw file](https://github.com/batfish/batfish/blob/9e630bb74eaccf67b2fe3a4ab6a1e391e1000fd3/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4#L6734)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> (F_NameChar | ' ')*
> ```

FYI I decided we should support quoted names without spaces, which is why we need `*` here: `"aa"`.
</blockquote></details>

Why does a quoted name need at least two characters?

**Review by arifogel — COMMENTED** [review]
> Reviewed 13 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6195)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6195)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4, line 6734 at r2](https://reviewable.io/reviews/batfish/batfish/6195#-MHET4JdDnQCJZC_exVP:-MHET4JdDnQCJZC_exVQ:b-7ucjqo) ([raw file](https://github.com/batfish/batfish/blob/9e630bb74eaccf67b2fe3a4ab6a1e391e1000fd3/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4#L6734)):*
> ```ANTLR
> F_NameQuoted
> :
>   '"' F_NameChar (F_NameChar | ' ')* F_NameChar '"'
> ```

Repeating comment here to force resolution: Why does a quoted name need at least two `F_NameChar`s?

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6195)* status: 12 of 13 files reviewed, all discussions resolved (waiting on @arifogel)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4, line 6734 at r2](https://reviewable.io/reviews/batfish/batfish/6195#-MHET4JdDnQCJZC_exVP:-MHErdGN0u8tgYeMfK1e:bvwsokd) ([raw file](https://github.com/batfish/batfish/blob/9e630bb74eaccf67b2fe3a4ab6a1e391e1000fd3/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4#L6734)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Repeating comment here to force resolution: Why does a quoted name need at least two `F_NameChar`s?
</blockquote></details>

Ugh. Fixed.

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6195)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by arifogel — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6195#-:-MHEuWF6A-VnY0qx9jGR:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
