### PR TITLE
BDD.ite: skip the operator cache when we're building the BDD bottom-up

### PR DESCRIPTION
**Pull request by anothermattbrown**
Many/most uses of ite are for constructing BDDs bottom up: the condition BDD is a single variable whose level is less than that of either branch BDD. These are inexpensive operations so don't cache them.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7477)* status: all files reviewed, 1 unresolved discussion (waiting on @anothermattbrown)

___
*[projects/bdd/src/main/java/net/sf/javabdd/JFactory.java, line 970 at r1](https://reviewable.io/reviews/batfish/batfish/7477#-MkxWZvL-SKC15niXR5W:-MkxWZvL-SKC15niXR5X:b-jw81sz) ([raw file](https://github.com/batfish/batfish/blob/6afc572d00ee5bca80a48dd06e2a0416cb1366c8/projects/bdd/src/main/java/net/sf/javabdd/JFactory.java#L970)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
>     } else if (HIGH(f) == BDDONE
>         && LOW(f) == BDDZERO
>         && LEVEL(f) < LEVEL(g)
>         && LEVEL(f) < LEVEL(h)) {
>       // f is a single variable BDD, and its level is lower than g's and h's.
>       // this is a common case: we're building a BDD bottom-up
>       // skip the operator cache
>       return bdd_makenode(LEVEL(f), g, h);
> ```
</details>

should this move down 1 else if? Otherwise the BDDs will not be canonical.

In general, how can we ameliorate that risk?

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7477)* status: all files reviewed, 1 unresolved discussion (waiting on @anothermattbrown)

___
*[projects/bdd/src/main/java/net/sf/javabdd/JFactory.java, line 970 at r1](https://reviewable.io/reviews/batfish/batfish/7477#-MkxWZvL-SKC15niXR5W:-MkxX2DE2FJFMGRVldwG:brawenp) ([raw file](https://github.com/batfish/batfish/blob/6afc572d00ee5bca80a48dd06e2a0416cb1366c8/projects/bdd/src/main/java/net/sf/javabdd/JFactory.java#L970)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
>     } else if (HIGH(f) == BDDONE
>         && LOW(f) == BDDZERO
>         && LEVEL(f) < LEVEL(g)
>         && LEVEL(f) < LEVEL(h)) {
>       // f is a single variable BDD, and its level is lower than g's and h's.
>       // this is a common case: we're building a BDD bottom-up
>       // skip the operator cache
>       return bdd_makenode(LEVEL(f), g, h);
> ```
should this move down 1 else if? Otherwise the BDDs will not be canonical.

In general, how can we ameliorate that risk?
</blockquote></details>

(or maybe bdd_makenode handles this)

**Review by anothermattbrown — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7477)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[projects/bdd/src/main/java/net/sf/javabdd/JFactory.java, line 970 at r1](https://reviewable.io/reviews/batfish/batfish/7477#-MkxWZvL-SKC15niXR5W:-MkxXwI7AUTE9rC9eVrB:b-fb6o25) ([raw file](https://github.com/batfish/batfish/blob/6afc572d00ee5bca80a48dd06e2a0416cb1366c8/projects/bdd/src/main/java/net/sf/javabdd/JFactory.java#L970)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

(or maybe bdd_makenode handles this)
</blockquote></details>

makenode handles it:
```
  private int bdd_makenode(int level, int low, int high) {
    assert (ISCONST(low) || level < LEVEL(low)) && (ISCONST(high) || level < LEVEL(high));

    /* check whether childs are equal */
    if (low == high) {
      if (CACHESTATS) {
        cachestats.uniqueTrivial++;
      }
      return low;
    }
```

I originally had this at the bottom of the if/else chain, but I figured this is probably the common case for our code, so moved it up

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7477)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @anothermattbrown and @dhalperi)

___
*[projects/bdd/src/main/java/net/sf/javabdd/JFactory.java, line 970 at r2](https://reviewable.io/reviews/batfish/batfish/7477#-MkxnXzF6DzjQYQqmFGn:-MkxnXzF6DzjQYQqmFGo:bmc91zi) ([raw file](https://github.com/batfish/batfish/blob/35bd97d7b50b2eb4907e2e798d3b71e2b8ce4a1d/projects/bdd/src/main/java/net/sf/javabdd/JFactory.java#L970)):*
> ```
> bdd_makenode(LEVEL(f), g, h);
> ```

The understanding in the second commit message is wrong -- low is the false branch, high is the true branch. The issue is that we needed to do `bdd_makenode(LEVEL(f), h, g)`. That is, `h` should be the low branch, aka, the one we use when `f` is false.

We have optimized for the `negated variable` case right now.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7477)* status: all files reviewed, 1 unresolved discussion (waiting on @anothermattbrown)

**Pull request merged**
