### PR TITLE
cisco ios-xe implement default zone behavior

### PR DESCRIPTION
**Pull request by arifogel**

### CODE REVIEW

**Comment by arifogel** [comment]
@anothermattbrown Please look carefully at the methods I added to `AclLineMatchExpr` visitors.

---

Review status: 0 of 17 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1288#-:-LBZcyciDoep2OzVgvzy:b9mozl5)*

**Comment by anothermattbrown** [comment]
Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/OriginatingFromDevice.java, line 5 at r1](https://reviewable.io/reviews/batfish/batfish/1288#-LBbyPVm0c8vwSTFCCP_:-LBbyPVm0c8vwSTFCCPa:bqkw7qm) ([raw file](https://github.com/batfish/batfish/blob/504f96546f532a8d65d872bfc14fa79a2937c9f8/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/OriginatingFromDevice.java#L5)):*
> ```Java
> import com.google.common.base.MoreObjects;
> 
> public class OriginatingFromDevice extends AclLineMatchExpr {
> ```

javadoc?

---

*[projects/batfish/src/main/java/org/batfish/z3/ContainsMatchSrcInterfaceExprVisitor.java, line 52 at r1](https://reviewable.io/reviews/batfish/batfish/1288#-LBbwWeR29PRj7PWfHw7:-LBbwWeR29PRj7PWfHw8:b7twf55) ([raw file](https://github.com/batfish/batfish/blob/504f96546f532a8d65d872bfc14fa79a2937c9f8/projects/batfish/src/main/java/org/batfish/z3/ContainsMatchSrcInterfaceExprVisitor.java#L52)):*
> ```Java
>   @Override
>   public Boolean visitOriginatingFromDevice(OriginatingFromDevice originatingFromDevice) {
>     return true;
> ```

This is going to require we always track which interface traffic came in on, which could get expensive. It's probably better to add a single bit for whether traffic is originating from the device, and add another class like this called `ContainsOriginatingFromDevice` to determine if we need that instrumentation.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1288)*

**Comment by sfraint** [comment]
Reviewed 9 of 17 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1288)*

**Comment by arifogel** [comment]
Review status: 15 of 18 files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/OriginatingFromDevice.java, line 5 at r1](https://reviewable.io/reviews/batfish/batfish/1288#-LBbyPVm0c8vwSTFCCP_:-LBcZ4H83umkMYgx6CwK:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/504f96546f532a8d65d872bfc14fa79a2937c9f8/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/OriginatingFromDevice.java#L5)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

javadoc?
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/z3/ContainsMatchSrcInterfaceExprVisitor.java, line 52 at r1](https://reviewable.io/reviews/batfish/batfish/1288#-LBbwWeR29PRj7PWfHw7:-LBcYeF44Zg9RW7e6YA-:b-e8ab6u) ([raw file](https://github.com/batfish/batfish/blob/504f96546f532a8d65d872bfc14fa79a2937c9f8/projects/batfish/src/main/java/org/batfish/z3/ContainsMatchSrcInterfaceExprVisitor.java#L52)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

This is going to require we always track which interface traffic came in on, which could get expensive. It's probably better to add a single bit for whether traffic is originating from the device, and add another class like this called `ContainsOriginatingFromDevice` to determine if we need that instrumentation.
</blockquote></details>

Ignoring per offline discussion.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1288)*

**Comment by anothermattbrown** [comment]
:lgtm:

---

Reviewed 4 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1288#-:-LBcaVu_5ir9Z0o_YjqL:bnfp4nl)*

**Pull request merged**
