### PR TITLE
Juniper/Palo Alto don't create hierarchy paths just to delete them

### PR DESCRIPTION
**Pull request by arifogel**

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8682)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown and @progwriter)

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8682)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown and @progwriter)

___
*[`projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/InsertDeleteApplicator.java` line 245 at r1](https://reviewable.io/reviews/batfish/batfish/8682#-NQbHy25-SgvKAp4-m1s:-NQbHy25-SgvKAp4-m1t:b-ci9fh9) ([raw file](https://github.com/batfish/batfish/blob/7c4bd5018feca7a3cdde1d62382b3aee131931b6/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/InsertDeleteApplicator.java#L245)):*
> ```Java
>     String lastWord = null;
>     for (String word : _words) {
>       subtree = subtree.getOrAddSubtree(word);
> ```

No action needed: is this function used elsewhere or can it be deleted too?



_Code quote:_
```Java
tOrAddSubtre
```

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8682)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @anothermattbrown and @progwriter)

___
*[`projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/InsertDeleteApplicator.java` line 245 at r1](https://reviewable.io/reviews/batfish/batfish/8682#-NQbHy25-SgvKAp4-m1s:-NQbICJL4Pa32dKXsvwG:b6ndpvq) ([raw file](https://github.com/batfish/batfish/blob/7c4bd5018feca7a3cdde1d62382b3aee131931b6/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/InsertDeleteApplicator.java#L245)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

No action needed: is this function used elsewhere or can it be deleted too?
</blockquote></details>

Yes, removed from 1 other place and left it in 2 other places.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8682)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown and @progwriter)

**Pull request merged**
