### PR TITLE
Adding rules to allow responses to permitted TCP requests

### PR DESCRIPTION
**Pull request by haverma**
In addition to allowed inbound/outbound packets, also allow packets containing ACK and packets containing reversed inbound/outbound rules

### CODE REVIEW

**Comment by arifogel** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://beta.reviewable.io/reviews/batfish/batfish/1105#-L8cbn1K3FnELrEfhi9C:-L8cbn1K3FnELrEfhi9D:bprvdkv) (no related file):*
Please add tests that check if particular flows are permitted/rejected by the generated `IpAccessList`s. Such tests would have caught the missing calls to `setUseSyn` and `setUseAck`.

---

*[projects/batfish/src/main/java/org/batfish/representation/aws/SecurityGroup.java, line 71 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1105#-L8cba2x6StqRZBvy-6Q:-L8cba2x6StqRZBvy-6R:bxfzi0i) ([raw file](https://github.com/batfish/batfish/blob/fd331a74a337424d0920e75a64465f45f5eaff9b/projects/batfish/src/main/java/org/batfish/representation/aws/SecurityGroup.java#L71)):*
> ```Java
>                         .setSrcPorts(ipAccessListLine.getDstPorts())
>                         .build())
>             .collect(Collectors.toList());
> ```

`Collectors.toList()` -> `ImmutableList.toImmutableList()` for style consistency

---

*[projects/batfish/src/main/java/org/batfish/representation/aws/SecurityGroup.java, line 84 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1105#-L8cbeOp-Joz0rIyDVlx:-L8cbeOq52fviyroUcgK:bxfzi0i) ([raw file](https://github.com/batfish/batfish/blob/fd331a74a337424d0920e75a64465f45f5eaff9b/projects/batfish/src/main/java/org/batfish/representation/aws/SecurityGroup.java#L84)):*
> ```Java
>                         .setSrcPorts(ipAccessListLine.getDstPorts())
>                         .build())
>             .collect(Collectors.toList());
> ```

`Collectors.toList()` -> `ImmutableList.toImmutableList()` for style consistency

---

*[projects/batfish/src/main/java/org/batfish/representation/aws/SecurityGroup.java, line 89 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1105#-L8cbgMLDWNgyjLChMce:-L8cbgMLDWNgyjLChMcf:bkm79ut) ([raw file](https://github.com/batfish/batfish/blob/fd331a74a337424d0920e75a64465f45f5eaff9b/projects/batfish/src/main/java/org/batfish/representation/aws/SecurityGroup.java#L89)):*
> ```Java
>     IpAccessListLine rejectSynOnly =
>         IpAccessListLine.builder()
>             .setTcpFlags(ImmutableSet.of(TcpFlags.builder().setAck(false).setSyn(true).build()))
> ```

You need to `setUseAck(true)` and `setUseSyn(true)`.

---

*[projects/batfish/src/test/java/org/batfish/representation/aws/ElasticsearchDomainTest.java, line 174 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1105#-L8cbUtk3PctsvkI23Kz:-L8cbUtk3PctsvkI23L-:bkm79ut) ([raw file](https://github.com/batfish/batfish/blob/fd331a74a337424d0920e75a64465f45f5eaff9b/projects/batfish/src/test/java/org/batfish/representation/aws/ElasticsearchDomainTest.java#L174)):*
> ```Java
>     IpAccessListLine rejectSynOnly =
>         IpAccessListLine.builder()
>             .setTcpFlags(ImmutableSet.of(TcpFlags.builder().setAck(false).setSyn(true).build()))
> ```

You need to `setUseAck(true)` and `setUseSyn(true)`.

---

*[projects/batfish/src/test/java/org/batfish/representation/aws/RdsInstanceTest.java, line 154 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1105#-L8cbQ0DDu6qlCugNW8w:-L8cbQ0DDu6qlCugNW8x:bkm79ut) ([raw file](https://github.com/batfish/batfish/blob/fd331a74a337424d0920e75a64465f45f5eaff9b/projects/batfish/src/test/java/org/batfish/representation/aws/RdsInstanceTest.java#L154)):*
> ```Java
>     IpAccessListLine rejectSynOnly =
>         IpAccessListLine.builder()
>             .setTcpFlags(ImmutableSet.of(TcpFlags.builder().setAck(false).setSyn(true).build()))
> ```

You need to `setUseAck(true)` and `setUseSyn(true)`.

---

*[projects/batfish/src/test/java/org/batfish/representation/aws/SecurityGroupsTest.java, line 40 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1105#-L8cao-J7NFVJ5fFi2IX:-L8cao-J7NFVJ5fFi2IY:bkm79ut) ([raw file](https://github.com/batfish/batfish/blob/fd331a74a337424d0920e75a64465f45f5eaff9b/projects/batfish/src/test/java/org/batfish/representation/aws/SecurityGroupsTest.java#L40)):*
> ```Java
>     _rejectSynOnly =
>         IpAccessListLine.builder()
>             .setTcpFlags(ImmutableSet.of(TcpFlags.builder().setAck(false).setSyn(true).build()))
> ```

You need to `setUseAck(true)` and `setUseSyn(true)`.

---

*[projects/batfish/src/test/java/org/batfish/representation/aws/SecurityGroupsTest.java, line 244 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1105#-L8cb7DpAjUfGIUo9vp6:-L8cb7DqEmIjBosTn2hD:b-qgn8vk) ([raw file](https://github.com/batfish/batfish/blob/fd331a74a337424d0920e75a64465f45f5eaff9b/projects/batfish/src/test/java/org/batfish/representation/aws/SecurityGroupsTest.java#L244)):*
> ```Java
>         inboundRules,
>         equalTo(
>             Lists.newArrayList(
> ```

`List.newArrayList` -> `ImmutableList.of` for style consistency

---

*[projects/batfish/src/test/java/org/batfish/representation/aws/SecurityGroupsTest.java, line 262 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1105#-L8cbHRKB-uo94BsEF1j:-L8cbHRKB-uo94BsEF1k:b-qgn8vk) ([raw file](https://github.com/batfish/batfish/blob/fd331a74a337424d0920e75a64465f45f5eaff9b/projects/batfish/src/test/java/org/batfish/representation/aws/SecurityGroupsTest.java#L262)):*
> ```Java
>         outboundRules,
>         equalTo(
>             Lists.newArrayList(
> ```

`List.newArrayList` -> `ImmutableList.of` for style consistency

---

*[tests/aws/nodes-example-aws.ref, line 85 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1105#-L8caXy4DRwfsCuOW7M4:-L8caXy4DRwfsCuOW7M5:b-p56aek) ([raw file](https://github.com/batfish/batfish/blob/fd331a74a337424d0920e75a64465f45f5eaff9b/tests/aws/nodes-example-aws.ref#L85)):*
> ```
>                 "negate" : false
>               },
>               {
> ```

None of the tcpFlags bits are used here, i.e. every `useXXX` is false. This tcpFlags will always match, resulting in all traffic matching reaching this line being rejected.

---

*[tests/aws/nodes-example-aws.ref, line 122 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1105#-L8ca9Y_D08-zKSoZtH_:-L8ca9Y_D08-zKSoZtHa:b-p56aek) ([raw file](https://github.com/batfish/batfish/blob/fd331a74a337424d0920e75a64465f45f5eaff9b/tests/aws/nodes-example-aws.ref#L122)):*
> ```
>                 "negate" : false
>               },
>               {
> ```

None of the tcpFlags bits are used here, i.e. every `useXXX` is false. This tcpFlags will always match, resulting in all traffic matching reaching this line being rejected.

---

*[tests/aws/nodes-example-aws.ref, line 3198 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1105#-L8caYbK7g7YlBRHBO_G:-L8caYbK7g7YlBRHBO_H:b-p56aek) ([raw file](https://github.com/batfish/batfish/blob/fd331a74a337424d0920e75a64465f45f5eaff9b/tests/aws/nodes-example-aws.ref#L3198)):*
> ```
>                 "negate" : false
>               },
>               {
> ```

None of the tcpFlags bits are used here, i.e. every `useXXX` is false. This tcpFlags will always match, resulting in all traffic matching reaching this line being rejected.

---

*[tests/aws/nodes-example-aws.ref, line 3261 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1105#-L8caZGq7VWUmG-RcukJ:-L8caZGq7VWUmG-RcukK:b-p56aek) ([raw file](https://github.com/batfish/batfish/blob/fd331a74a337424d0920e75a64465f45f5eaff9b/tests/aws/nodes-example-aws.ref#L3261)):*
> ```
>                 ]
>               },
>               {
> ```

None of the tcpFlags bits are used here, i.e. every `useXXX` is false. This tcpFlags will always match, resulting in all traffic matching reaching this line being rejected.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1105)*

**Comment by haverma** [comment]
Review status: 1 of 7 files reviewed at latest revision, 13 unresolved discussions.

---

*[a discussion](https://beta.reviewable.io/reviews/batfish/batfish/1105#-L8cbn1K3FnELrEfhi9C:-L8d6mnR0J9Ce-sF8tvX:b-aqluy) (no related file):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Please add tests that check if particular flows are permitted/rejected by the generated `IpAccessList`s. Such tests would have caught the missing calls to `setUseSyn` and `setUseAck`.
</blockquote></details>

Added tests to check valid and invalid flows

---

*[projects/batfish/src/main/java/org/batfish/representation/aws/SecurityGroup.java, line 71 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1105#-L8cba2x6StqRZBvy-6Q:-L8d5pSf4XH5B8D4h-PG:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/fd331a74a337424d0920e75a64465f45f5eaff9b/projects/batfish/src/main/java/org/batfish/representation/aws/SecurityGroup.java#L71)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

`Collectors.toList()` -> `ImmutableList.toImmutableList()` for style consistency
</blockquote></details>

done

---

*[projects/batfish/src/main/java/org/batfish/representation/aws/SecurityGroup.java, line 84 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1105#-L8cbeOp-Joz0rIyDVlx:-L8d6XOi1e6YYBg4YmfE:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/fd331a74a337424d0920e75a64465f45f5eaff9b/projects/batfish/src/main/java/org/batfish/representation/aws/SecurityGroup.java#L84)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

`Collectors.toList()` -> `ImmutableList.toImmutableList()` for style consistency
</blockquote></details>

done

---

*[projects/batfish/src/main/java/org/batfish/representation/aws/SecurityGroup.java, line 89 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1105#-L8cbgMLDWNgyjLChMce:-L8d5rSr1PuKGFRW7uZ3:bnkoki2) ([raw file](https://github.com/batfish/batfish/blob/fd331a74a337424d0920e75a64465f45f5eaff9b/projects/batfish/src/main/java/org/batfish/representation/aws/SecurityGroup.java#L89)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

You need to `setUseAck(true)` and `setUseSyn(true)`.
</blockquote></details>

using TcpFlags newconstant for this

---

*[projects/batfish/src/test/java/org/batfish/representation/aws/ElasticsearchDomainTest.java, line 174 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1105#-L8cbUtk3PctsvkI23Kz:-L8d6Tcy7lA21SRF17VW:bjpww40) ([raw file](https://github.com/batfish/batfish/blob/fd331a74a337424d0920e75a64465f45f5eaff9b/projects/batfish/src/test/java/org/batfish/representation/aws/ElasticsearchDomainTest.java#L174)):*
> using TcpFlags new constant for this

---

*[projects/batfish/src/test/java/org/batfish/representation/aws/RdsInstanceTest.java, line 154 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1105#-L8cbQ0DDu6qlCugNW8w:-L8d6bxg1IyQLp09TsV3:b-3zi5k) ([raw file](https://github.com/batfish/batfish/blob/fd331a74a337424d0920e75a64465f45f5eaff9b/projects/batfish/src/test/java/org/batfish/representation/aws/RdsInstanceTest.java#L154)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

You need to `setUseAck(true)` and `setUseSyn(true)`.
</blockquote></details>

using TcpFlags new constant for this

---

*[projects/batfish/src/test/java/org/batfish/representation/aws/SecurityGroupsTest.java, line 40 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1105#-L8cao-J7NFVJ5fFi2IX:-L8d6dgqA245jQCPmWCZ:b-3zi5k) ([raw file](https://github.com/batfish/batfish/blob/fd331a74a337424d0920e75a64465f45f5eaff9b/projects/batfish/src/test/java/org/batfish/representation/aws/SecurityGroupsTest.java#L40)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

You need to `setUseAck(true)` and `setUseSyn(true)`.
</blockquote></details>

using TcpFlags new constant for this

---

*[projects/batfish/src/test/java/org/batfish/representation/aws/SecurityGroupsTest.java, line 244 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1105#-L8cb7DpAjUfGIUo9vp6:-L8d6ffdBqhFUPBiO75e:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/fd331a74a337424d0920e75a64465f45f5eaff9b/projects/batfish/src/test/java/org/batfish/representation/aws/SecurityGroupsTest.java#L244)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

`List.newArrayList` -> `ImmutableList.of` for style consistency
</blockquote></details>

done

---

*[projects/batfish/src/test/java/org/batfish/representation/aws/SecurityGroupsTest.java, line 262 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1105#-L8cbHRKB-uo94BsEF1j:-L8d6gL451yiCVc7B5m6:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/fd331a74a337424d0920e75a64465f45f5eaff9b/projects/batfish/src/test/java/org/batfish/representation/aws/SecurityGroupsTest.java#L262)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

`List.newArrayList` -> `ImmutableList.of` for style consistency
</blockquote></details>

done

---

*[tests/aws/nodes-example-aws.ref, line 85 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1105#-L8caXy4DRwfsCuOW7M4:-L8d6lVh9VlbCQollcK_:b-n9tkhd) ([raw file](https://github.com/batfish/batfish/blob/fd331a74a337424d0920e75a64465f45f5eaff9b/tests/aws/nodes-example-aws.ref#L85)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

None of the tcpFlags bits are used here, i.e. every `useXXX` is false. This tcpFlags will always match, resulting in all traffic matching reaching this line being rejected.
</blockquote></details>

changed

---

*[tests/aws/nodes-example-aws.ref, line 122 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1105#-L8ca9Y_D08-zKSoZtH_:-L8d6sCwBRwyRlpLftdt:b-n9tkhd) ([raw file](https://github.com/batfish/batfish/blob/fd331a74a337424d0920e75a64465f45f5eaff9b/tests/aws/nodes-example-aws.ref#L122)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

None of the tcpFlags bits are used here, i.e. every `useXXX` is false. This tcpFlags will always match, resulting in all traffic matching reaching this line being rejected.
</blockquote></details>

changed

---

*[tests/aws/nodes-example-aws.ref, line 3198 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1105#-L8caYbK7g7YlBRHBO_G:-L8d6vUuA0VOGd1EaZbQ:b-n9tkhd) ([raw file](https://github.com/batfish/batfish/blob/fd331a74a337424d0920e75a64465f45f5eaff9b/tests/aws/nodes-example-aws.ref#L3198)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

None of the tcpFlags bits are used here, i.e. every `useXXX` is false. This tcpFlags will always match, resulting in all traffic matching reaching this line being rejected.
</blockquote></details>

changed

---

*[tests/aws/nodes-example-aws.ref, line 3261 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1105#-L8caZGq7VWUmG-RcukJ:-L8d6xgY9G-npXYxxh1J:b-n9tkhd) ([raw file](https://github.com/batfish/batfish/blob/fd331a74a337424d0920e75a64465f45f5eaff9b/tests/aws/nodes-example-aws.ref#L3261)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

None of the tcpFlags bits are used here, i.e. every `useXXX` is false. This tcpFlags will always match, resulting in all traffic matching reaching this line being rejected.
</blockquote></details>

changed

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1105)*

**Comment by arifogel** [comment]
:lgtm: with one minor change request for `TcpFlags`

---

Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/TcpFlags.java, line 139 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1105#-L8dKFio35NH79xhtDjN:-L8dKFio35NH79xhtDjO:bus7sqo) ([raw file](https://github.com/batfish/batfish/blob/59ba3f2ef94b0b0c6cbb5581a50b69e8a864be3f/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/TcpFlags.java#L139)):*
> ```Java
> 
>   public static final TcpFlags SYN_ONLY =
>       TcpFlags.builder().setSyn(true).setAck(false).setUseSyn(true).setUseAck(true).build();
> ```

Please put this constant in appropriate alphabetic position, and remove redundant qualification: `TcpFlags.builder()` -> `builder()`

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1105#-:-L8dLBeX2lcRtkmE1VP8:b-aaz9a)*

**Comment by arifogel** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1105)*

**Comment by haverma** [comment]
addressed requested change

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/TcpFlags.java, line 139 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1105#-L8dKFio35NH79xhtDjN:-L8dN4XgCFAAykvqlt1G:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/59ba3f2ef94b0b0c6cbb5581a50b69e8a864be3f/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/TcpFlags.java#L139)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Please put this constant in appropriate alphabetic position, and remove redundant qualification: `TcpFlags.builder()` -> `builder()`
</blockquote></details>

done

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1105#-:-L8dN5eK5cn2hkXpIdcI:b-23b2r0)*

**Pull request merged**
