### PR TITLE
bdp: remove queues for sending BGP messages

### PR DESCRIPTION
**Pull request by anothermattbrown**
BGP processes now accumulate outgoing requests to all neighbors in a single RibDelta object, shared by all neighbors, instead of in each neighbor's incoming queue. This reduces memory usage, by reducing the number of copies of BGP routes we have in memory at the same time. For networks with high ECMP, this can be significant.

Each RibDelta is either read-only or write-only in each round. A result of this is that all nodes can run in parallel, rather than having to stagger them according to coloring as we used. This is why the counts changed in `genDp.ref`. Note: I can split this part out if desired.

### CODE REVIEW

**Review by progwriter — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6217)* status: all files reviewed, 5 unresolved discussions (waiting on @anothermattbrown)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java, line 507 at r1](https://reviewable.io/reviews/batfish/batfish/6217#-MHUGk_OB-7_xK1f_OcH:-MHUGk_OB-7_xK1f_OcI:bo5ctjy) ([raw file](https://github.com/batfish/batfish/blob/d7ca33ffe940601f4c018a609a7726023d697885/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java#L507)):*
> ```Java
>       assert innerScope != null; // avoid unused warning
> 
>       List<Entry<VirtualRouter, Map<Bgpv4Rib, RibDelta<Bgpv4Route>>>> routeDeltas =
> ```

I can't untangle this. It's.... a collection of tuples (VR, all route deltas for that VR)?
___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java, line 208 at r1](https://reviewable.io/reviews/batfish/batfish/6217#-MHTnedJEdnwRqsUb5oa:-MHTnedJEdnwRqsUb5ob:beta50m) ([raw file](https://github.com/batfish/batfish/blob/d7ca33ffe940601f4c018a609a7726023d697885/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java#L208)):*
> ```
> _mainRibRouteDelta
> ```

this may be just a naming thing, but this only contains bgp routes that go into the main rib, right?
___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java, line 1513 at r1](https://reviewable.io/reviews/batfish/batfish/6217#-MHUGAWFA3BNHP6dVKDK:-MHUGAWFA3BNHP6dVKDL:bovqa19) ([raw file](https://github.com/batfish/batfish/blob/d7ca33ffe940601f4c018a609a7726023d697885/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java#L1513)):*
> ```Java
>   }
> 
>   private static <R extends AbstractRouteDecorator> RibDelta<R> mergeRibDeltas(
> ```

nit: can probably be a static method on `RibDelta` but not a blocker
___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java, line 1657 at r1](https://reviewable.io/reviews/batfish/batfish/6217#-MHTnMZ5CmrGyUBITSWy:-MHTnMZ63t3GSFhm_o7E:bcp7dfj) ([raw file](https://github.com/batfish/batfish/blob/d7ca33ffe940601f4c018a609a7726023d697885/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java#L1657)):*
> ```Java
>   }
> 
>   void endOfRound() {
> ```

since this is in VR, please doc this only applies to BGP v4 unicast.
___
*[projects/batfish/src/main/java/org/batfish/dataplane/rib/RibDelta.java, line 33 at r1](https://reviewable.io/reviews/batfish/batfish/6217#-MHUGM0N1-kFGjT6lCD6:-MHUGM0O90-s3aE1Uv-O:b-k6ny9a) ([raw file](https://github.com/batfish/batfish/blob/d7ca33ffe940601f4c018a609a7726023d697885/projects/batfish/src/main/java/org/batfish/dataplane/rib/RibDelta.java#L33)):*
> ```Java
>  */
> @ParametersAreNonnullByDefault
> public final class RibDelta<R> implements Serializable {
> ```

why serializable ? was this fixing some bug? my hope is we never materialize these to disk.

**Review by anothermattbrown — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6217)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @anothermattbrown and @progwriter)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java, line 507 at r1](https://reviewable.io/reviews/batfish/batfish/6217#-MHUGk_OB-7_xK1f_OcH:-MHX9Joj3Hlap-S3Tn73:bj3nxl2) ([raw file](https://github.com/batfish/batfish/blob/d7ca33ffe940601f4c018a609a7726023d697885/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java#L507)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

I can't untangle this. It's.... a collection of tuples (VR, all route deltas for that VR)?
</blockquote></details>

refactored and commented for clarity. better I hope?
___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java, line 1657 at r1](https://reviewable.io/reviews/batfish/batfish/6217#-MHTnMZ5CmrGyUBITSWy:-MHX8kS6CU204wUuLlCy:b6yept4) ([raw file](https://github.com/batfish/batfish/blob/d7ca33ffe940601f4c018a609a7726023d697885/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java#L1657)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

since this is in VR, please doc this only applies to BGP v4 unicast.
</blockquote></details>

gave it a more descriptive name
___
*[projects/batfish/src/main/java/org/batfish/dataplane/rib/RibDelta.java, line 33 at r1](https://reviewable.io/reviews/batfish/batfish/6217#-MHUGM0N1-kFGjT6lCD6:-MHXIs7W9hnCbl0YidwR:b8v1zb9) ([raw file](https://github.com/batfish/batfish/blob/d7ca33ffe940601f4c018a609a7726023d697885/projects/batfish/src/main/java/org/batfish/dataplane/rib/RibDelta.java#L33)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

why serializable ? was this fixing some bug? my hope is we never materialize these to disk.
</blockquote></details>

because they are now fields on VirtualRouter, which gets serialized I guess

**Review by progwriter — COMMENTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6217)* status: all files reviewed, 1 unresolved discussion (waiting on @anothermattbrown)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java, line 507 at r1](https://reviewable.io/reviews/batfish/batfish/6217#-MHUGk_OB-7_xK1f_OcH:-MHXJvGI-PftBB3xhFfu:b-k73z76) ([raw file](https://github.com/batfish/batfish/blob/d7ca33ffe940601f4c018a609a7726023d697885/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java#L507)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

refactored and commented for clarity. better I hope?
</blockquote></details>

thanks
___
*[projects/batfish/src/main/java/org/batfish/dataplane/rib/RibDelta.java, line 33 at r1](https://reviewable.io/reviews/batfish/batfish/6217#-MHUGM0N1-kFGjT6lCD6:-MHXK0zfEYh7jMfPZIwp:bb2d7jm) ([raw file](https://github.com/batfish/batfish/blob/d7ca33ffe940601f4c018a609a7726023d697885/projects/batfish/src/main/java/org/batfish/dataplane/rib/RibDelta.java#L33)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

because they are now fields on VirtualRouter, which gets serialized I guess
</blockquote></details>

:disappointed: 
oh right. ok.

**Review by anothermattbrown — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6217)* status: all files reviewed, 1 unresolved discussion (waiting on @progwriter)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java, line 208 at r1](https://reviewable.io/reviews/batfish/batfish/6217#-MHTnedJEdnwRqsUb5oa:-MHXMt7K4hVv22g7-1wm:b-ydhw2n) ([raw file](https://github.com/batfish/batfish/blob/d7ca33ffe940601f4c018a609a7726023d697885/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java#L208)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

> ```
> _mainRibRouteDelta
> ```

this may be just a naming thing, but this only contains bgp routes that go into the main rib, right?
</blockquote></details>

it has two sources:

```
    _mainRibRouteDelta =
        RibDelta.merge(
            _mainRibRouteDelta,
            RibDelta.<AnnotatedRoute<AbstractRoute>>builder()
                .add(_mainRib.getTypedRoutes())
                .build());
```

```
    _mainRibRouteDelta = RibDelta.merge(_mainRibRouteDelta, _mainRibRouteDeltaBuilder.build());
```

These corresponds to the `mainDelta` parameter in the two calls to the old `queueOutgoingBgpRoutes` method.

Is there a better name to use?

**Review by progwriter — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6217)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java, line 208 at r1](https://reviewable.io/reviews/batfish/batfish/6217#-MHTnedJEdnwRqsUb5oa:-MHXhWOM5qIvQx-MBJyE:brrzngr) ([raw file](https://github.com/batfish/batfish/blob/d7ca33ffe940601f4c018a609a7726023d697885/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java#L208)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

it has two sources:

```
    _mainRibRouteDelta =
        RibDelta.merge(
            _mainRibRouteDelta,
            RibDelta.<AnnotatedRoute<AbstractRoute>>builder()
                .add(_mainRib.getTypedRoutes())
                .build());
```

```
    _mainRibRouteDelta = RibDelta.merge(_mainRibRouteDelta, _mainRibRouteDeltaBuilder.build());
```

These corresponds to the `mainDelta` parameter in the two calls to the old `queueOutgoingBgpRoutes` method.

Is there a better name to use?
</blockquote></details>

had offline discussion. have better name. separate is fine.

**Review by progwriter — COMMENTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6217)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
