### PR TITLE
Make `NextHop` jackson-serializable

### PR DESCRIPTION
**Pull request by arifogel**

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 7 of 15 files at r1, 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7778)* status: 11 of 25 files reviewed, 1 unresolved discussion (waiting on @arifogel)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7778#-MqWY8EZ-0bgZJHnVeXH:-MqWY8EZ-0bgZJHnVeXI:b-xwdzb4) (no related file):*
after batfish/batfish#7776

---

**Review by arifogel — COMMENTED** [review]
> Reviewed 7 of 8 files at r5.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7778)* status: 11 of 25 files reviewed, all discussions resolved (waiting on @anothermattbrown, @arifogel, @corinaminer, @dhalperi, and @sfraint)

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7778)* status: 11 of 25 files reviewed, all discussions resolved (waiting on @anothermattbrown, @arifogel, @corinaminer, @dhalperi, and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7778#-MqaSfT_E8nfLP8fW912:-MqaSfT_E8nfLP8fW913:b-59kapq) (no related file):*
ready for review. select between base and r5

---

**Review by corinaminer — COMMENTED** [review]
:lgtm:

> Reviewed 10 of 11 files at r4, 1 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7778#-:-Mqa_VHO6-gkT4TaQYBV:bnfp4nl)* status: 22 of 25 files reviewed, all discussions resolved (waiting on @anothermattbrown, @dhalperi, and @sfraint)

**Review by arifogel — COMMENTED** [review]
> Reviewed 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7778)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown, @dhalperi, and @sfraint)

**Pull request merged**
