### PR TITLE
IOS: define structures for individual route-map clauses

### PR DESCRIPTION
**Pull request by ratulm**

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7116)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ratulm)

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7116)* status: all files reviewed, 1 unresolved discussion (waiting on @ratulm)

___
*[tests/parsing-tests/unit-tests.ref, line 6 at r1](https://reviewable.io/reviews/batfish/batfish/7116#-MdPD-6k5wlG_Rl_P995:-MdPD-6k5wlG_Rl_P996:b29qigo) ([raw file](https://github.com/batfish/batfish/blob/220c695debee1cb62714c128060dcbb22610c0f1/tests/parsing-tests/unit-tests.ref#L6)):*
> ```
>       "class" : "org.batfish.common.BatfishException$BatfishStackTrace",
>       "answer" : [
>         "org.batfish.common.BatfishException: Fatal exception due to failure of at least one job",
> ```

Seems like something is wrong here.

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7116)* status: 7 of 11 files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[tests/parsing-tests/unit-tests.ref, line 6 at r1](https://reviewable.io/reviews/batfish/batfish/7116#-MdPD-6k5wlG_Rl_P995:-MdPGDMY6VR0ZoNZzfLL:b4u9lqg) ([raw file](https://github.com/batfish/batfish/blob/220c695debee1cb62714c128060dcbb22610c0f1/tests/parsing-tests/unit-tests.ref#L6)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Seems like something is wrong here.
</blockquote></details>

oops. didn't account for target-less continue.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7116)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ratulm)

**Pull request merged**
