### PR TITLE
Fix arpFailureTrace IPs, plus FibImpl and ForwardingAnalysis fallout

### PR DESCRIPTION
**Pull request by arifogel**
- Fix bug where dest IP showed up as arp IP for neighbor unreachable
when the interface had no neighbors.
- To ensure we always display real arp IP, remove pathways for `Route.UNSET_NEXT_HOP_IP` to make it
  into `FibForward.getArpIp`.
  - make `FibForward.getArpIp` optional, and disallow `Route.UNSET_NEXT_HOP_IP`.
- Fix bugs and cruft encountered while updating `FibImpl` to use new `FibForward` API
  - Ensure every `Rib` entry results in at least one `FibAction`
    - Make sure unresolvable or looping NextHopIp routes result in `FibNullRoute`, instead of
      silent missing `FibEntry`s
  - Remove unnecessary loop duplicating `Rib.longestPrefixMatch` filtering of non-forwarding routes
  - Ensure non-forwarding routes are never part of the resolution chain
  - Remove unused parameters not caught because the function was called with
    the same parameter value recursively
- Update old/incorrect documentation in `ForwardingAnalysisImpl` near usages of `FibForward`

### CODE REVIEW

**Review by corinaminer — COMMENTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8039)* status: all files reviewed, 6 unresolved discussions (waiting on @anothermattbrown, @arifogel, and @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java, line 1530 at r1](https://reviewable.io/reviews/batfish/batfish/8039#-MvuFJcB2K1q_gcKpnKA:-MvuFJcB2K1q_gcKpnKB:b5stado) ([raw file](https://github.com/batfish/batfish/blob/723c8e7f4c6bb7e18d50dae9ec289ca07f2104d1/projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java#L1530)):*
> ```Java
>                     .setForwardingDetail(
>                         ForwardedOutInterface.of(fibForward.getInterfaceName(), resolvedNextHopIp))
>                     // TODO: remove deprecated arpIp
> ```

i don't see that this is deprecated -- is it just redundant with the forwarding detail's `resolvedNextHopIp`?
___
*[projects/batfish/src/test/java/org/batfish/dataplane/FibImplTest.java, line 217 at r1](https://reviewable.io/reviews/batfish/batfish/8039#-MvuX1WN6lS1syWtR2ct:-MvuX1WN6lS1syWtR2cu:b13bnpj) ([raw file](https://github.com/batfish/batfish/blob/723c8e7f4c6bb7e18d50dae9ec289ca07f2104d1/projects/batfish/src/test/java/org/batfish/dataplane/FibImplTest.java#L217)):*
> ```Java
> 
>     assertThat(fibRoutes, not(hasItem(hasPrefix(Prefix.parse("1.1.1.0/24")))));
>     assertThat(fibRoutes, hasItem(hasPrefix(Prefix.parse("2.2.2.0/24"))));
> ```

should test that the new nonforwarding route is not present
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FibImpl.java, line 84 at r1](https://reviewable.io/reviews/batfish/batfish/8039#-MvuLGCDAFhtm86zwNtX:-MvuLGCDAFhtm86zwNtY:b-9hk5sg) ([raw file](https://github.com/batfish/batfish/blob/723c8e7f4c6bb7e18d50dae9ec289ca07f2104d1/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FibImpl.java#L84)):*
> ```Java
> 
>     public void setUnresolvable(boolean unresolvable) {
>       _unresolvable = true;
> ```

parameter is unused
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FibImpl.java, line 227 at r1](https://reviewable.io/reviews/batfish/batfish/8039#-MvuNgpcE1_-RVH7i_jV:-MvuNgpcE1_-RVH7i_jW:bbffwxb) ([raw file](https://github.com/batfish/batfish/blob/723c8e7f4c6bb7e18d50dae9ec289ca07f2104d1/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FibImpl.java#L227)):*
> ```Java
>         Set<AbstractRoute> lpmRoutes;
>         // For repeat cases, we don't want to keep around the unresolvable children
>         treeNode.getChildren().clear();
> ```

not understanding the context here. What's a repeat case? why won't clearing children mess up the tree -- is it freshly constructed for every lookup?
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FibImpl.java, line 259 at r1](https://reviewable.io/reviews/batfish/batfish/8039#-MvuR32VAY6wai4xLpqF:-MvuR32VAY6wai4xLpqG:blzxe09) ([raw file](https://github.com/batfish/batfish/blob/723c8e7f4c6bb7e18d50dae9ec289ca07f2104d1/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FibImpl.java#L259)):*
> ```Java
>           // will only survive in the final FIB if they do not cause an oscillation during data
>           // plane computation. On other vendors, the main RIB does not activate such routes, so we
>           // will not encounter them here.
> ```

do we actually have this difference implemented for the main RIB (i.e., batfish has a knob for "activate unresolvable/looping routes"?)
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FibImpl.java, line 263 at r1](https://reviewable.io/reviews/batfish/batfish/8039#-MvuUu0BAvKGrk6rj6lB:-MvuUu0BAvKGrk6rj6lC:b-4tjdwe) ([raw file](https://github.com/batfish/batfish/blob/723c8e7f4c6bb7e18d50dae9ec289ca07f2104d1/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FibImpl.java#L263)):*
> ```Java
>           if (depth == 0) {
>             // Add a child node to satisfy invariant that leaf nodes have a parent.
>             ResolutionTreeNode.withParent(route, treeNode, null).setUnresolvable(true);
> ```

why does this invariant exist? if there's a good reason for it, then it seems like this might violate that reason (even though it doesn't break the invariant)
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysisImpl.java, line 1230 at r1](https://reviewable.io/reviews/batfish/batfish/8039#-MvuWZUu4g3GAPTIRlj7:-MvuWZUu4g3GAPTIRlj8:b-s7052v) ([raw file](https://github.com/batfish/batfish/blob/723c8e7f4c6bb7e18d50dae9ec289ca07f2104d1/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysisImpl.java#L1230)):*
> ```Java
>   /**
>    * Mapping: route -&gt; nexthopinterface -&gt; resolved nextHopIps (or Optional.empty() if dest IP
>    * should be used for ARP
> ```

nit, missing closing parenthesis

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8039)* status: all files reviewed, 6 unresolved discussions (waiting on @anothermattbrown, @corinaminer, and @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java, line 1530 at r1](https://reviewable.io/reviews/batfish/batfish/8039#-MvuFJcB2K1q_gcKpnKA:-Mvu_AGyBS2dFAYFEF4g:b-83igrx) ([raw file](https://github.com/batfish/batfish/blob/723c8e7f4c6bb7e18d50dae9ec289ca07f2104d1/projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java#L1530)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

i don't see that this is deprecated -- is it just redundant with the forwarding detail's `resolvedNextHopIp`?
</blockquote></details>

It's not always applicable, so it shouldn't be at the common level. I believe we already stopped reading those fields in pybatfish.
___
*[projects/batfish/src/test/java/org/batfish/dataplane/FibImplTest.java, line 217 at r1](https://reviewable.io/reviews/batfish/batfish/8039#-MvuX1WN6lS1syWtR2ct:-MvuaJZ7Cp3SV2C67Zno:b-7ql1td) ([raw file](https://github.com/batfish/batfish/blob/723c8e7f4c6bb7e18d50dae9ec289ca07f2104d1/projects/batfish/src/test/java/org/batfish/dataplane/FibImplTest.java#L217)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

should test that the new nonforwarding route is not present
</blockquote></details>

fixed
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FibImpl.java, line 84 at r1](https://reviewable.io/reviews/batfish/batfish/8039#-MvuLGCDAFhtm86zwNtX:-MvuaRue1aNKfIBYyVzM:b-7ql1td) ([raw file](https://github.com/batfish/batfish/blob/723c8e7f4c6bb7e18d50dae9ec289ca07f2104d1/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FibImpl.java#L84)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

parameter is unused
</blockquote></details>

fixed
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FibImpl.java, line 227 at r1](https://reviewable.io/reviews/batfish/batfish/8039#-MvuNgpcE1_-RVH7i_jV:-Mvubz5k7GRJvdpgKvl8:b-5dbqci) ([raw file](https://github.com/batfish/batfish/blob/723c8e7f4c6bb7e18d50dae9ec289ca07f2104d1/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FibImpl.java#L227)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

not understanding the context here. What's a repeat case? why won't clearing children mess up the tree -- is it freshly constructed for every lookup?
</blockquote></details>

leftover from abandoned implementation.
removed.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FibImpl.java, line 259 at r1](https://reviewable.io/reviews/batfish/batfish/8039#-MvuR32VAY6wai4xLpqF:-Mvuc5PK4QKJm1ZUZ6y4:b95fsot) ([raw file](https://github.com/batfish/batfish/blob/723c8e7f4c6bb7e18d50dae9ec289ca07f2104d1/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FibImpl.java#L259)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

do we actually have this difference implemented for the main RIB (i.e., batfish has a knob for "activate unresolvable/looping routes"?)
</blockquote></details>

Yes. Resolvability is not enforced when `resolutionRestriction` is `null` here.
```
  /**
   * Create a new empty RIB. If {@code resolutionRestriction} is not {@code null}, then merged
   * recursive routes that are not resolvable under the provided {@code resolutionRestriction} will
   * remain inactive until they become resolvable again. Inactive routes will not be returned by
   * {@link #getRoutes()}, {@link #getTypedRoutes()}, nor {@link #getTypedBackupRoutes()}.
   */
  public Rib(@Nullable ResolutionRestriction<AnnotatedRoute<AbstractRoute>> resolutionRestriction) {
    super(true);
    _resolvabilityEnforcer =
        resolutionRestriction != null ? new ResolvabilityEnforcer(resolutionRestriction) : null;
  }
```
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FibImpl.java, line 263 at r1](https://reviewable.io/reviews/batfish/batfish/8039#-MvuUu0BAvKGrk6rj6lB:-MvucSDuBLmMiWMYiGeu:b7vna9g) ([raw file](https://github.com/batfish/batfish/blob/723c8e7f4c6bb7e18d50dae9ec289ca07f2104d1/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FibImpl.java#L263)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

why does this invariant exist? if there's a good reason for it, then it seems like this might violate that reason (even though it doesn't break the invariant)
</blockquote></details>

Looking over the code, I don't think this invariant is needed anymore.
It's sufficient to throw when we see an NHIP at a leaf that is not marked unresolvable.
Removed.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysisImpl.java, line 1230 at r1](https://reviewable.io/reviews/batfish/batfish/8039#-MvuWZUu4g3GAPTIRlj7:-Mvug8I91yrdff42XaTP:b-7ql1td) ([raw file](https://github.com/batfish/batfish/blob/723c8e7f4c6bb7e18d50dae9ec289ca07f2104d1/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysisImpl.java#L1230)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

nit, missing closing parenthesis
</blockquote></details>

fixed

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8039)* status: 6 of 9 files reviewed, 5 unresolved discussions (waiting on @anothermattbrown, @corinaminer, and @dhalperi)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FibImpl.java, line 263 at r1](https://reviewable.io/reviews/batfish/batfish/8039#-MvuUu0BAvKGrk6rj6lB:-MvvU_lH7iMH9y6bfcUq:bk3x7n4) ([raw file](https://github.com/batfish/batfish/blob/723c8e7f4c6bb7e18d50dae9ec289ca07f2104d1/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FibImpl.java#L263)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Looking over the code, I don't think this invariant is needed anymore.
It's sufficient to throw when we see an NHIP at a leaf that is not marked unresolvable.
Removed.
</blockquote></details>

OK now I see where this is invariant is actually still enforced, based on the test failure. I'll either restore what I had before or change the rest, based on difficulty tomorrow.

**Review by corinaminer — COMMENTED** [review]
> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8039)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @anothermattbrown, @arifogel, @corinaminer, and @dhalperi)

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8039)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @anothermattbrown, @arifogel, @corinaminer, and @dhalperi)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FibImpl.java, line 263 at r1](https://reviewable.io/reviews/batfish/batfish/8039#-MvuUu0BAvKGrk6rj6lB:-MvyWxeR8cs4nOnZuf2t:b-ixrk3w) ([raw file](https://github.com/batfish/batfish/blob/723c8e7f4c6bb7e18d50dae9ec289ca07f2104d1/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FibImpl.java#L263)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

OK now I see where this is invariant is actually still enforced, based on the test failure. I'll either restore what I had before or change the rest, based on difficulty tomorrow.
</blockquote></details>

Having tried a couple things, I can't think of a solution that is any simpler than creating a child node and ending resolution, since that's what we do for all other (terminal) next hop types. We don't need to mark non-terminal nodes as unresolvable though, so removed that.

**Review by corinaminer — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8039)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown and @dhalperi)

**Pull request merged**
