### PR TITLE
fix #638 - update aws code and add init, node tests

### LINKED ISSUE #638: Get AWS working again
Bit rot has set in for AWS code. I fixed some parsing issues in #637. now we get NPE related to VRFs

- [ ] make things for the attached rig
- [ ] write tests so we keep things in shape

[dummy-repo-aws.zip](https://github.com/batfish/batfish/files/1440165/dummy-repo-aws.zip)

### PR DESCRIPTION
**Pull request by arifogel**
This change is [Reviewable](https://reviewable.io/reviews/batfish/batfish/642)

### CODE REVIEW

**Comment by dhalperi** [comment]
Reviewed 35 of 35 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/InternetGateway.java, line 62 at r1](https://reviewable.io:443/reviews/batfish/batfish/642#-KyHxAdFpqK6QSrwCvVt:-KyHxAdFpqK6QSrwCvVu:b-ob8dtb) ([raw file](https://github.com/batfish/batfish/blob/1845ae22668995656515224c548b1a255711a1e8/projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/InternetGateway.java#L62)):*
> ```Java
>       vpcIface.setPrefix(vpcIfacePrefix);
>       vpcConfigNode.getInterfaces().put(vpcIfaceName, vpcIface);
>       vpcConfigNode.initDefaultVrf().getInterfaces().put(vpcIfaceName, vpcIface);
> ```

given that you call the function twice and it may only initialize if not yet present, seems actually better to call it `get` or at least `getOrInit`.

---

*[projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/Subnet.java, line 169 at r1](https://reviewable.io:443/reviews/batfish/batfish/642#-KyHx_3WZySsakf4wgJK:-KyHx_3WZySsakf4wgJL:b-6ih5hr) ([raw file](https://github.com/batfish/batfish/blob/1845ae22668995656515224c548b1a255711a1e8/projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/Subnet.java#L169)):*
> ```Java
>     // add the interface to the vpc router
>     Configuration vpcConfigNode = awsVpcConfiguration.getConfigurationNodes().get(_vpcId);
>     vpcConfigNode.setConfigurationFormat(ConfigurationFormat.AWS_VPC);
> ```

question for self, why was this not done already?

---

*[tests/basic/init-example-aws.ref, line 19 at r1](https://reviewable.io:443/reviews/batfish/batfish/642#-KyHy70fEAFOs0Iip7YX:-KyHy70fEAFOs0Iip7YY:b5kbdbk) ([raw file](https://github.com/batfish/batfish/blob/1845ae22668995656515224c548b1a255711a1e8/tests/basic/init-example-aws.ref#L19)):*
> ```
>     "numFailed" : 0,
>     "numPassed" : 0,
>     "numResults" : 0
> ```

is this the right output for parsing an AWS network? Seems useless.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/642)*

**Comment by arifogel** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/InternetGateway.java, line 62 at r1](https://reviewable.io:443/reviews/batfish/batfish/642#-KyHxAdFpqK6QSrwCvVt:-KyI-8lE2xJ5Yyu1FqlG:b-gsrz0z) ([raw file](https://github.com/batfish/batfish/blob/1845ae22668995656515224c548b1a255711a1e8/projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/InternetGateway.java#L62)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

given that you call the function twice and it may only initialize if not yet present, seems actually better to call it `get` or at least `getOrInit`.
</blockquote></details>

How would you feel about an AWS helper function that generates a Configuration with the right format and a default VRF? Then we could eliminate `Configuration.initVrf()`

---

*[projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/Subnet.java, line 169 at r1](https://reviewable.io:443/reviews/batfish/batfish/642#-KyHx_3WZySsakf4wgJK:-KyI-Icu97c98cOTGHlE:b-htwkv5) ([raw file](https://github.com/batfish/batfish/blob/1845ae22668995656515224c548b1a255711a1e8/projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/Subnet.java#L169)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

question for self, why was this not done already?
</blockquote></details>

See reply about helper function.

---

*[tests/basic/init-example-aws.ref, line 19 at r1](https://reviewable.io:443/reviews/batfish/batfish/642#-KyHy70fEAFOs0Iip7YX:-KyHzpVY-y-_UmFlR3O8:b-z38ljr) ([raw file](https://github.com/batfish/batfish/blob/1845ae22668995656515224c548b1a255711a1e8/tests/basic/init-example-aws.ref#L19)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

is this the right output for parsing an AWS network? Seems useless.
</blockquote></details>

In general, JSON parsing produces no meaningful output when successful. If you are referring only to the `summary` portion, then I would posit that its presence is useless in almost every ref (but that is out  of scope for this PR). Is there a specific modification you propose?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/642)*

**Comment by dhalperi** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/InternetGateway.java, line 62 at r1](https://reviewable.io:443/reviews/batfish/batfish/642#-KyHxAdFpqK6QSrwCvVt:-KyI6D4oQq9i4c2iUj3Q:b-x4rshb) ([raw file](https://github.com/batfish/batfish/blob/1845ae22668995656515224c548b1a255711a1e8/projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/InternetGateway.java#L62)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

How would you feel about an AWS helper function that generates a Configuration with the right format and a default VRF? Then we could eliminate `Configuration.initVrf()`
</blockquote></details>

No strong opinion - I find the code fairly confusing as is.

---

*[tests/basic/init-example-aws.ref, line 19 at r1](https://reviewable.io:443/reviews/batfish/batfish/642#-KyHy70fEAFOs0Iip7YX:-KyI5sR5GtVc-5i3onOI:bdrfk3m) ([raw file](https://github.com/batfish/batfish/blob/1845ae22668995656515224c548b1a255711a1e8/tests/basic/init-example-aws.ref#L19)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

In general, JSON parsing produces no meaningful output when successful. If you are referring only to the `summary` portion, then I would posit that its presence is useless in almost every ref (but that is out  of scope for this PR). Is there a specific modification you propose?
</blockquote></details>

For "normal" testrigs, both `ParseVendorConfiguration` and`InitInfo` answers tell you files they read and devices they set up. I don't think your outstanding #561 changes this. But we're not providing any of that info here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/642)*

**Comment by dhalperi** [comment]
*[projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/InternetGateway.java, line 62 at r1](https://reviewable.io:443/reviews/batfish/batfish/642#-KyHxAdFpqK6QSrwCvVt:-KyI6Nk-vpBG6YH8AjVI:bhuewa5) ([raw file](https://github.com/batfish/batfish/blob/1845ae22668995656515224c548b1a255711a1e8/projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/InternetGateway.java#L62)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

No strong opinion - I find the code fairly confusing as is.
</blockquote></details>

Confusing is wrong .. just complicated :). Not sure I have built a good mental model.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/642)*

**Comment by arifogel** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/InternetGateway.java, line 62 at r1](https://reviewable.io:443/reviews/batfish/batfish/642#-KyHxAdFpqK6QSrwCvVt:-KyIBY5x3gJ1XMu6xUkX:b-5ps1eo) ([raw file](https://github.com/batfish/batfish/blob/1845ae22668995656515224c548b1a255711a1e8/projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/InternetGateway.java#L62)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Confusing is wrong .. just complicated :). Not sure I have built a good mental model.
</blockquote></details>

OK I'll just do it then.

---

*[tests/basic/init-example-aws.ref, line 19 at r1](https://reviewable.io:443/reviews/batfish/batfish/642#-KyHy70fEAFOs0Iip7YX:-KyIBGVzrtIuUtwZLIPr:bdierc6) ([raw file](https://github.com/batfish/batfish/blob/1845ae22668995656515224c548b1a255711a1e8/tests/basic/init-example-aws.ref#L19)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

For "normal" testrigs, both `ParseVendorConfiguration` and`InitInfo` answers tell you files they read and devices they set up. I don't think your outstanding #561 changes this. But we're not providing any of that info here.
</blockquote></details>

Gotcha. What you are looking for could be an addon to whatever we end up doing with #561. I will file defer and file an issue.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/642)*

**Comment by arifogel** [comment]
Review status: 29 of 36 files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/basic/init-example-aws.ref, line 19 at r1](https://reviewable.io:443/reviews/batfish/batfish/642#-KyHy70fEAFOs0Iip7YX:-KyIEwq1h8cAogwNL33F:b3lixf1) ([raw file](https://github.com/batfish/batfish/blob/1845ae22668995656515224c548b1a255711a1e8/tests/basic/init-example-aws.ref#L19)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Gotcha. What you are looking for could be an addon to whatever we end up doing with #561. I will file defer and file an issue.
</blockquote></details>

Filed #647 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/642)*

**Comment by dhalperi** [comment]
Reviewed 7 of 9 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/642)*

**Comment by dhalperi** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/642#-:-KyIG0S319Ct8xRFNeaQ:bnfp4nl)*

**Pull request merged**
