### PR TITLE
partial support for ios object-group network

### PR DESCRIPTION
**Pull request by arifogel**

### CODE REVIEW

**Comment by dhalperi** [comment]
Reviewed 10 of 10 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1182)*

**Comment by arifogel** [comment]
Review status: 10 of 39 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[a discussion](https://beta.reviewable.io/reviews/batfish/batfish/1182#-LAL01tbCedU2e-2UA0e:-LAL01tbCedU2e-2UA0f:b-938waq) (no related file):*
Not ready for review

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1182)*

**Comment by dhalperi** [comment]
Review status: 5 of 59 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://beta.reviewable.io/reviews/batfish/batfish/1182#-LAL01tbCedU2e-2UA0e:-LAMNlCTDfOhj1-0_zOH:befzyjv) (no related file):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Not ready for review
</blockquote></details>

I know this isn't ready for review, so I'll just leave this comment here. It looks like there's going to be a major refactor to support the new Cisco syntax... please refactor that into a separate PR with no new features coupled so it can be reviewed and merged in isolation.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1182)*

**Comment by arifogel** [comment]
Review status: 5 of 59 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://beta.reviewable.io/reviews/batfish/batfish/1182#-LAL01tbCedU2e-2UA0e:-LAPG-Uh-NdWdvFViKWJ:bebrt1w) (no related file):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I know this isn't ready for review, so I'll just leave this comment here. It looks like there's going to be a major refactor to support the new Cisco syntax... please refactor that into a separate PR with no new features coupled so it can be reviewed and merged in isolation.
</blockquote></details>

Will do

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1182)*

**Pull request closed without merging**
