### PR TITLE
Introduce NextHopVtep for forwarding over VXLAN

### PR DESCRIPTION
**Pull request by corinaminer**
The new next hop type specifies a VNI and a VTEP IP, and results in a FibAction that forwards out the VXLAN interface corresponding to the next hop's VNI using the VTEP IP to ARP.

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 9 of 15 files at r1, 3 of 4 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7776)* status: all files reviewed, 2 unresolved discussions (waiting on @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java, line 976 at r2](https://reviewable.io/reviews/batfish/batfish/7776#-MqWGNTZEyx7wkM4pzgQ:-MqWGNTZEyx7wkM4pzgR:bz8bj01) ([raw file](https://github.com/batfish/batfish/blob/2160aad5ef5e6c090be496e51746711b4b093994/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java#L976)):*
> ```Java
>         @Override
>         public Void visitNextHopVtep(NextHopVtep nextHopVtep) {
>           // should not be possible; only EVPN and BGP routes have this next hop type.
> ```

should probably throw
___
*[projects/batfish/src/main/java/org/batfish/dataplane/rib/BgpRib.java, line 440 at r2](https://reviewable.io/reviews/batfish/batfish/7776#-MqWGvD9AdtD1CtvzCZy:-MqWGvD9AdtD1CtvzCZz:b-mzad09) ([raw file](https://github.com/batfish/batfish/blob/2160aad5ef5e6c090be496e51746711b4b093994/projects/batfish/src/main/java/org/batfish/dataplane/rib/BgpRib.java#L440)):*
> ```Java
>               @Override
>               public Long visitNextHopVtep(NextHopVtep nextHopVtep) {
>                 // TODO: something better?
> ```

Might be vendor-dependent, might be assumed equivalent to best (which would be hard to implement). Fine to defer as you've done.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/route/nh/NextHopVtep.java, line 17 at r3](https://reviewable.io/reviews/batfish/batfish/7776#-MqWIMTk39qjDTtEDPFW:-MqWIMTk39qjDTtEDPFX:b-hiw62o) ([raw file](https://github.com/batfish/batfish/blob/c1eb10df2a2fd2a0f6a9f80fa608e1d12072a5f4/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/route/nh/NextHopVtep.java#L17)):*
> ```Java
>  * {@link Ip#AUTO}.
>  */
> @ParametersAreNonnullByDefault
> ```

unnecessary with package-info

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7776)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java, line 976 at r2](https://reviewable.io/reviews/batfish/batfish/7776#-MqWGNTZEyx7wkM4pzgQ:-MqWhfMC-DlAP4p580Rd:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/2160aad5ef5e6c090be496e51746711b4b093994/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java#L976)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

should probably throw
</blockquote></details>

done
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/route/nh/NextHopVtep.java, line 17 at r3](https://reviewable.io/reviews/batfish/batfish/7776#-MqWIMTk39qjDTtEDPFW:-MqWhNmCEEgJGt7LdGKm:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/c1eb10df2a2fd2a0f6a9f80fa608e1d12072a5f4/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/route/nh/NextHopVtep.java#L17)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

unnecessary with package-info
</blockquote></details>

done

**Review by arifogel — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7776)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7776)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/route/nh/NextHopVtep.java, line 1 at r4](https://reviewable.io/reviews/batfish/batfish/7776#-MqXzH2R77TFTLr1ANqV:-MqXzH2R77TFTLr1ANqW:b-1tastm) ([raw file](https://github.com/batfish/batfish/blob/f525c69fbf479766eb190c6b9cdf5ea798f3ea28/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/route/nh/NextHopVtep.java#L1)):*
> ```Java
> package org.batfish.datamodel.route.nh;
> ```

I was going to ask you to add a test for this file. But if you wanna wait, my next PR has tests for all next hop types.

**Pull request merged**
