### PR TITLE
added AaaAuthenticationLoginQuestionPlugin

### PR DESCRIPTION
**Pull request by erikljungman**

### CODE REVIEW

**Comment by anothermattbrown** [comment]
Review status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @erikljungman, @anothermattbrown, @dhalperi, and @arifogel)

---

*[projects/question/src/main/java/org/batfish/question/AaaAuthenticationLoginQuestionPlugin.java, line 30 at r1](https://reviewable.io/reviews/batfish/batfish/1766#-LG11p4h0ahtIMD7Rw1g:-LG11p4i7JgWOLay23mp:b-z6g0n8) ([raw file](https://github.com/batfish/batfish/blob/cd4064aa4ebc16a996e81dfe84118cff2b17a0a6/projects/question/src/main/java/org/batfish/question/AaaAuthenticationLoginQuestionPlugin.java#L30)):*
> ```Java
>     }
> 
>     public SortedMap<String, List<String>> getExposedLines() {
> ```

It's usually a good idea to avoid exposing mutable private fields. In this case, it looks like `answer` can construct the map itself and then pass it to the `AaaAuthenticationAnswerElement` via its constructor, and then the constructor can make an immutable copy using `ImmutableSortedMap.copyOf`. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1766)*

**Comment by erikljungman** [comment]
Review status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @anothermattbrown, @dhalperi, and @arifogel)

---

*[projects/question/src/main/java/org/batfish/question/AaaAuthenticationLoginQuestionPlugin.java, line 30 at r1](https://reviewable.io/reviews/batfish/batfish/1766#-LG11p4h0ahtIMD7Rw1g:-LG1F6ll84KAwgL2p8df:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/cd4064aa4ebc16a996e81dfe84118cff2b17a0a6/projects/question/src/main/java/org/batfish/question/AaaAuthenticationLoginQuestionPlugin.java#L30)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

It's usually a good idea to avoid exposing mutable private fields. In this case, it looks like `answer` can construct the map itself and then pass it to the `AaaAuthenticationAnswerElement` via its constructor, and then the constructor can make an immutable copy using `ImmutableSortedMap.copyOf`. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1766)*

**Comment by anothermattbrown** [comment]
Review status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @anothermattbrown, @dhalperi, and @arifogel)

---

*[projects/question/src/main/java/org/batfish/question/AaaAuthenticationLoginQuestionPlugin.java, line 30 at r1](https://reviewable.io/reviews/batfish/batfish/1766#-LG11p4h0ahtIMD7Rw1g:-LG1agZ7BVlAEd37aYnj:b-eladfr) ([raw file](https://github.com/batfish/batfish/blob/cd4064aa4ebc16a996e81dfe84118cff2b17a0a6/projects/question/src/main/java/org/batfish/question/AaaAuthenticationLoginQuestionPlugin.java#L30)):*
<details><summary><i>Previously, erikljungman wrote…</i></summary><blockquote>

Done.
</blockquote></details>

cool. Also, we try to use `SortedMap` instead of `ImmutableMap` in type declarations (e.g. of the field and method).

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1766)*

**Comment by arifogel** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed, 2 unresolved discussions (waiting on @anothermattbrown, @erikljungman, and @dhalperi)

---

*[projects/question/src/main/java/org/batfish/question/AaaAuthenticationLoginQuestionPlugin.java, line 23 at r2](https://reviewable.io/reviews/batfish/batfish/1766#-LG1aUfFAQM0OzIm_O40:-LG1aUfFAQM0OzIm_O41:b-f7dzck) ([raw file](https://github.com/batfish/batfish/blob/a148b0bbc55ecf05bde37ced70eac43c342a6e86/projects/question/src/main/java/org/batfish/question/AaaAuthenticationLoginQuestionPlugin.java#L23)):*
> ```Java
> public class AaaAuthenticationLoginQuestionPlugin extends QuestionPlugin {
> 
>   public static class AaaAuthenticationAnswerElement extends AnswerElement {
> ```

Please get rid of this class altogether. You can just store the answer as a `TableAnswerElement`. See usage examples elsewhere in the repo. We are trying to move away from custom `AnswerElement` subclasses in general for new questions.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1766)*

**Comment by erikljungman** [comment]
Review status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @arifogel, @anothermattbrown, and @dhalperi)

---

*[projects/question/src/main/java/org/batfish/question/AaaAuthenticationLoginQuestionPlugin.java, line 23 at r2](https://reviewable.io/reviews/batfish/batfish/1766#-LG1aUfFAQM0OzIm_O40:-LG2IE0FE5joPTl1XsR0:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/a148b0bbc55ecf05bde37ced70eac43c342a6e86/projects/question/src/main/java/org/batfish/question/AaaAuthenticationLoginQuestionPlugin.java#L23)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Please get rid of this class altogether. You can just store the answer as a `TableAnswerElement`. See usage examples elsewhere in the repo. We are trying to move away from custom `AnswerElement` subclasses in general for new questions.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1766)*

**Comment by arifogel** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed, 1 unresolved discussion (waiting on @erikljungman and @dhalperi)

---

*[projects/question/src/test/java/org/batfish/question/aaaauthenticationlogin/AaaAuthenticationAnswererTest.java, line 3 at r3](https://reviewable.io/reviews/batfish/batfish/1766#-LG2nTrp6Ow7ZyCq33kG:-LG2nTrp6Ow7ZyCq33kH:b-zdvn8d) ([raw file](https://github.com/batfish/batfish/blob/0b56d7e338083f3a8ca062b41dd6eb9d9c7529f3/projects/question/src/test/java/org/batfish/question/aaaauthenticationlogin/AaaAuthenticationAnswererTest.java#L3)):*
> ```Java
> package org.batfish.question.aaaauthenticationlogin;
> 
> public class AaaAuthenticationAnswererTest {}
> ```

Tests?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1766)*

**Comment by erikljungman** [comment]
Review status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @arifogel and @erikljungman)

---

*[projects/question/src/test/java/org/batfish/question/aaaauthenticationlogin/AaaAuthenticationAnswererTest.java, line 3 at r3](https://reviewable.io/reviews/batfish/batfish/1766#-LG2nTrp6Ow7ZyCq33kG:-LG6ks6g27A_cJZEI6N1:by3orew) ([raw file](https://github.com/batfish/batfish/blob/0b56d7e338083f3a8ca062b41dd6eb9d9c7529f3/projects/question/src/test/java/org/batfish/question/aaaauthenticationlogin/AaaAuthenticationAnswererTest.java#L3)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Tests?
</blockquote></details>

Didn't mean to commit that file last time without writing any tests. Added one but may need to add more to get the diff coverage up

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1766)*

**Comment by arifogel** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed, 1 unresolved discussion (waiting on @arifogel)

---

*[projects/question/src/test/java/org/batfish/question/aaaauthenticationlogin/AaaAuthenticationAnswererTest.java, line 3 at r3](https://reviewable.io/reviews/batfish/batfish/1766#-LG2nTrp6Ow7ZyCq33kG:-LG76lwp2_y0CexvwS8T:b-mxhn8j) ([raw file](https://github.com/batfish/batfish/blob/0b56d7e338083f3a8ca062b41dd6eb9d9c7529f3/projects/question/src/test/java/org/batfish/question/aaaauthenticationlogin/AaaAuthenticationAnswererTest.java#L3)):*
<details><summary><i>Previously, erikljungman wrote…</i></summary><blockquote>

Didn't mean to commit that file last time without writing any tests. Added one but may need to add more to get the diff coverage up
</blockquote></details>

All new code would ideally be tested, or at least executed during testing.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1766)*

**Comment by arifogel** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed, 2 unresolved discussions (waiting on @arifogel and @erikljungman)

---

*[projects/question/src/main/java/org/batfish/question/AaaAuthenticationLoginQuestionPlugin.java, line 47 at r5](https://reviewable.io/reviews/batfish/batfish/1766#-LGBwbJK0OJJbIJZ2N3V:-LGBwbJK0OJJbIJZ2N3W:b-nh91d0) ([raw file](https://github.com/batfish/batfish/blob/90c2600fa094b88cb132fe1a4fbf2595769cb6ad/projects/question/src/main/java/org/batfish/question/AaaAuthenticationLoginQuestionPlugin.java#L47)):*
> ```Java
>      * @return The creates the answer element object.
>      */
>     @VisibleForTesting
> ```

You only need package-private visibility for testing, as long as your test is in the same package.
Likely you can either use that visibility, or remove the annotation is this is supposed to be public outside of a test.

---

*[projects/question/src/test/java/org/batfish/question/aaaauthenticationlogin/AaaAuthenticationAnswererTest.java, line 3 at r3](https://reviewable.io/reviews/batfish/batfish/1766#-LG2nTrp6Ow7ZyCq33kG:-LGBx1Cl6MhcnfQ1RkI2:b-yc1kq3) ([raw file](https://github.com/batfish/batfish/blob/0b56d7e338083f3a8ca062b41dd6eb9d9c7529f3/projects/question/src/test/java/org/batfish/question/aaaauthenticationlogin/AaaAuthenticationAnswererTest.java#L3)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

All new code would ideally be tested, or at least executed during testing.
</blockquote></details>

Hmm.. which parts of new code are not being tested? Ask @anothermattbrown if you don't remember how to figure that out from the codecov tool.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1766)*

**Comment by erikljungman** [comment]
Review status: all files reviewed, 2 unresolved discussions (waiting on @erikljungman)

---

*[projects/question/src/test/java/org/batfish/question/aaaauthenticationlogin/AaaAuthenticationAnswererTest.java, line 3 at r3](https://reviewable.io/reviews/batfish/batfish/1766#-LG2nTrp6Ow7ZyCq33kG:-LGBzV-o-R4UZo9KO7cA:bk3zqp4) ([raw file](https://github.com/batfish/batfish/blob/0b56d7e338083f3a8ca062b41dd6eb9d9c7529f3/projects/question/src/test/java/org/batfish/question/aaaauthenticationlogin/AaaAuthenticationAnswererTest.java#L3)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Hmm.. which parts of new code are not being tested? Ask @anothermattbrown if you don't remember how to figure that out from the codecov tool.
</blockquote></details>

I know how to see which lines are being covered but I'm having a hard time getting the test coverage up because I can't import batfish from this part of the code so I can't create an Answerer or test that entire answer() function. I'm trying to pull out as much as possible from that answer function to test but I'm not sure how much more I can pull out. And then there are a few getters and setters in AaaAuthenticationQuestion that are not tested so I could maybe cover those in a test but I don't know how much that will raise the coverage. Got any ideas?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1766)*

**Comment by erikljungman** [comment]
Review status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @erikljungman, @anothermattbrown, and @arifogel)

---

*[projects/question/src/main/java/org/batfish/question/AaaAuthenticationLoginQuestionPlugin.java, line 47 at r5](https://reviewable.io/reviews/batfish/batfish/1766#-LGBwbJK0OJJbIJZ2N3V:-LGC_ri_BmzvlgbPuQvX:b-u79rqo) ([raw file](https://github.com/batfish/batfish/blob/90c2600fa094b88cb132fe1a4fbf2595769cb6ad/projects/question/src/main/java/org/batfish/question/AaaAuthenticationLoginQuestionPlugin.java#L47)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

You only need package-private visibility for testing, as long as your test is in the same package.
Likely you can either use that visibility, or remove the annotation is this is supposed to be public outside of a test.
</blockquote></details>

The test is not in the same package so I think this needs to be public

---

*[projects/question/src/test/java/org/batfish/question/aaaauthenticationlogin/AaaAuthenticationAnswererTest.java, line 3 at r3](https://reviewable.io/reviews/batfish/batfish/1766#-LG2nTrp6Ow7ZyCq33kG:-LGC_Vb_EBl9Opo3xvdq:byx7l8z) ([raw file](https://github.com/batfish/batfish/blob/0b56d7e338083f3a8ca062b41dd6eb9d9c7529f3/projects/question/src/test/java/org/batfish/question/aaaauthenticationlogin/AaaAuthenticationAnswererTest.java#L3)):*
<details><summary><i>Previously, erikljungman wrote…</i></summary><blockquote>

I know how to see which lines are being covered but I'm having a hard time getting the test coverage up because I can't import batfish from this part of the code so I can't create an Answerer or test that entire answer() function. I'm trying to pull out as much as possible from that answer function to test but I'm not sure how much more I can pull out. And then there are a few getters and setters in AaaAuthenticationQuestion that are not tested so I could maybe cover those in a test but I don't know how much that will raise the coverage. Got any ideas?
</blockquote></details>

moved AaaAuthenticationAnswererTest.java to the allinone package so I could import batfish and now coverage is up to 91%!

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1766)*

**Comment by arifogel** [comment]
:lgtm: with one minor optional suggestion

---

Reviewed 3 of 5 files at r6, 3 of 4 files at r7.
Review status: all files reviewed, 1 unresolved discussion (waiting on @erikljungman)

---

*[projects/allinone/src/test/java/org/batfish/allinone/AaaAuthenticationTest.java, line 49 at r7](https://reviewable.io/reviews/batfish/batfish/1766#-LGQs82aAtioCQOtEvkk:-LGQs82aAtioCQOtEvkl:b3l5ee0) ([raw file](https://github.com/batfish/batfish/blob/e4855ecb80cf63b44a5dc25dd476bcb70e6510c0/projects/allinone/src/test/java/org/batfish/allinone/AaaAuthenticationTest.java#L49)):*
> ```Java
>     TableAnswerElement answer = answerer.answer();
> 
>     assertThat(answer.getRows(), hasSize(1));
> ```

Not super important, but isn't there a `hasRows` matcher so you could assert on the answer directly?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1766#-:-LGQsgoIDb_clx7d8rGP:bncralw)*

**Comment by arifogel** [comment]
Reviewed 1 of 1 files at r8.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1766)*

**Pull request merged**
