### PR TITLE
Cisco: update references to community-lists in route-maps

### PR DESCRIPTION
**Pull request by dhalperi**
Fixed one false unused ref.

### CODE REVIEW

**Comment by dhalperi** [comment]
Review status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @dhalperi, @sfraint, and @arifogel)

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1680#-LF6JtcM14uE-QKXLenC:-LF6JtcM14uE-QKXLenD:b5jcala) (no related file):*
Blocked on parent PR.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1680)*

**Comment by ratulm** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi, @sfraint, and @arifogel)

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1680#-:-LF6LdzS187gQf6CX4yf:bnfp4nl)*

**Comment by arifogel** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi and @sfraint)

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1680#-:-LFE23YQCjrJs6MmfdCd:bnfp4nl)*

**Comment by dhalperi** [comment]
Reviewed 2 of 2 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1680)*

**Pull request merged**
