### PR TITLE
FRR: extract common area token, fix potential parser problems

### PR DESCRIPTION
**Pull request by dhalperi**

### CODE REVIEW

**Comment by dhalperi** [comment]
___
*[projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java, line 1514 at r1](https://reviewable.io/reviews/batfish/batfish/6553#-MQTgYtbC22WyGofEWZY:-MQTgYtc3OgvJV1JUm7F:bh6t24h) ([raw file](https://github.com/batfish/batfish/blob/15ba7f5b2d28783de5acad1a62f1b40add4e6b36/projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java#L1514)):*
> ```
>     assertThat(_frr.getInterfaces().get("swp1").getOspf().getOspfArea(), equalTo(0L));
>   }
> ```
still trying to figure out why these assertions pass. seems wrong.

**Comment by dhalperi** [comment]
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrr_interface.g4, line 81 at r1](https://reviewable.io/reviews/batfish/batfish/6553#-MQTgfAO7TOFXe44_Gjh:-MQTgfAO7TOFXe44_Gji:bs71ac1) ([raw file](https://github.com/batfish/batfish/blob/4a1359bd5259a1be718e0e2bf86cda6200520885/projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrr_interface.g4#L81)):*
> ```
>     ip = IP_ADDRESS
>     | num = UINT8
> ```
FYI problems:

use `ip_address` rule, not `IP_ADDRESS` token
it's a 32-bit value, not an 8-bit value. additionally, use `uint32` rule, not `UINT32` token.

**Review by progwriter — COMMENTED** [review]
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6553)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @corinaminer, @progwriter, and @sfraint)

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6553)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @corinaminer and @sfraint)

___
*[projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java, line 1514 at r1](https://reviewable.io/reviews/batfish/batfish/6553#-MQTgYtbC22WyGofEWZY:-MQTwUVUCgYt-fqDbW2B:bhaoy4r) ([raw file](https://github.com/batfish/batfish/blob/15ba7f5b2d28783de5acad1a62f1b40add4e6b36/projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java#L1514)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
>     assertThat(_frr.getInterfaces().get("swp1").getOspf().getOspfArea(), equalTo(0L));
>   }
> ```
still trying to figure out why these assertions pass. seems wrong.
</blockquote></details>

Figured it out, and added comments to explain.

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6553)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @corinaminer and @sfraint)

___
*[projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java, line 1508 at r1](https://reviewable.io/reviews/batfish/batfish/6553#-MQTwb7O5zRu0T-rfBdD:-MQTwb7O5zRu0T-rfBdE:bz7t105) ([raw file](https://github.com/batfish/batfish/blob/15ba7f5b2d28783de5acad1a62f1b40add4e6b36/projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java#L1508)):*
> ```
> FrrInterface i1 = new FrrInterface("swp1", "VRF");
> ```

FYI this interface was not actually used. The only real effect of this was to get rid of a warning that the `vrf` had not been configured. Note that the problem of the VRF not existing is still there, just that this avoids a warning because we don't have create the warning in extractor if the interface already exists.

Much simpler to just get rid of vrf -- that is not under test here, anyway.
___
*[projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java, line 1513 at r1](https://reviewable.io/reviews/batfish/batfish/6553#-MQTwxNT6no-OjND7YG6:-MQTwxNT6no-OjND7YG7:baubogw) ([raw file](https://github.com/batfish/batfish/blob/15ba7f5b2d28783de5acad1a62f1b40add4e6b36/projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java#L1513)):*
> ```
>     parse("interface swp1 vrf VRF\n ip ospf area 255.0.0.0\n");
>     assertThat(_warnings.getParseWarnings(), empty());
>     assertThat(_frr.getInterfaces().get("swp1").getOspf().getOspfArea(), equalTo(0L));
> ```

FYI the reason this test was passing is because the `parse` function does some bananas things to the test state, so `_frr` is only actually the place changes happen the first time you call `parse`.

As a simple workaround, I just split the two cases up.

**Review by progwriter — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6553)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer and @sfraint)

**Pull request merged**
