### PR TITLE
Update structure usage tracking

### PR DESCRIPTION
**Pull request by sfraint**
* Updated structure tracking to support tracking multiple usages on a single line
* Using new structure tracking strategy for several more Cisco structure types

### CODE REVIEW

**Comment by arifogel** [comment]
Reviewed 17 of 17 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java, line 241 at r1](https://reviewable.io/reviews/batfish/batfish/1422#-LCkZdQt4QHGqRd1EbPC:-LCkZdQu0fn5hwjYv6Ez:b-p1bd47) ([raw file](https://github.com/batfish/batfish/blob/6f9db5d298d02817ab5f2d8a42d3f4400efd96b1/projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java#L241)):*
> ```Java
>   }
> 
>   public void defineStructure(
> ```

Javadoc please

---

*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 4616 at r1](https://reviewable.io/reviews/batfish/batfish/1422#-LCkZy1JB13Y5BsTCDPu:-LCkZy1JB13Y5BsTCDPv:bq2g0ev) ([raw file](https://github.com/batfish/batfish/blob/6f9db5d298d02817ab5f2d8a42d3f4400efd96b1/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L4616)):*
> ```Java
>       currentInterface.setRoutingPolicy(policyName);
>       currentInterface.setRoutingPolicyLine(policyLine);
>       _configuration.referenceStructure(
> ```

Should be taken out of the loop I think

---

*[projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-route-map, line 8 at r1](https://reviewable.io/reviews/batfish/batfish/1422#-LCkg0Tx4SjqtZUOqzK8:-LCkg0Tx4SjqtZUOqzK9:b46qcf1) ([raw file](https://github.com/batfish/batfish/blob/6f9db5d298d02817ab5f2d8a42d3f4400efd96b1/projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-route-map#L8)):*
> ```
>   passive-interface default
>   vrf blah1
>     max-metric router-lsa external-lsa on-startup 86400 wait-for bgp 65601
> ```

Why was this line removed?

---

*[test_rigs/parsing-tests/example.ref, line 11650 at r1](https://reviewable.io/reviews/batfish/batfish/1422#-LCkfVX3A02aiKfkfpw6:-LCkfVX3A02aiKfkfpw7:bz3huvh) ([raw file](https://github.com/batfish/batfish/blob/6f9db5d298d02817ab5f2d8a42d3f4400efd96b1/test_rigs/parsing-tests/example.ref#L11650)):*
> ```
>                 133
>               ],
>               "numReferrers" : 1
> ```

Is this expected? Same goes for all ref changes in number of referrers.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1422)*

**Comment by sfraint** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java, line 241 at r1](https://reviewable.io/reviews/batfish/batfish/1422#-LCkZdQt4QHGqRd1EbPC:-LCkr9m2C2zW5CSx-xTh:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/6f9db5d298d02817ab5f2d8a42d3f4400efd96b1/projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java#L241)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Javadoc please
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 4616 at r1](https://reviewable.io/reviews/batfish/batfish/1422#-LCkZy1JB13Y5BsTCDPu:-LCkhrW74-Cv4vvl1bk3:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/6f9db5d298d02817ab5f2d8a42d3f4400efd96b1/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L4616)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Should be taken out of the loop I think
</blockquote></details>

Done.

---

*[projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-route-map, line 8 at r1](https://reviewable.io/reviews/batfish/batfish/1422#-LCkg0Tx4SjqtZUOqzK8:-LCkgH1K12ARRyzr8ET5:b-d6xs19) ([raw file](https://github.com/batfish/batfish/blob/6f9db5d298d02817ab5f2d8a42d3f4400efd96b1/projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-route-map#L8)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Why was this line removed?
</blockquote></details>

I don't know that it should have been added in the first place; is it necessary?

It looks like removing it does not affect the test.

---

*[test_rigs/parsing-tests/example.ref, line 11650 at r1](https://reviewable.io/reviews/batfish/batfish/1422#-LCkfVX3A02aiKfkfpw6:-LCkgTQhA5DdOp7p3Hcf:b26f50u) ([raw file](https://github.com/batfish/batfish/blob/6f9db5d298d02817ab5f2d8a42d3f4400efd96b1/test_rigs/parsing-tests/example.ref#L11650)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Is this expected? Same goes for all ref changes in number of referrers.
</blockquote></details>

Yes, I grep'd the test configs for these structures and it looks like we are only referencing these once (were double counting them before).

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1422)*

**Comment by dhalperi** [comment]
Reviewed 11 of 17 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 1531 at r3](https://reviewable.io/reviews/batfish/batfish/1422#-LCo_I9Y6CHzfZOuGFoU:-LCo_I9Y6CHzfZOuGFoV:bjx5xqc) ([raw file](https://github.com/batfish/batfish/blob/baa169f39610f43b70fbfa139a873aeedac9994e/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L1531)):*
> ```Java
>     _currentIsakmpPolicy.getProposal().setAuthenticationAlgorithm(IkeAuthenticationAlgorithm.SHA1);
>     // Isakmp policies are not explicitly referenced, so set to have unknownReferrers
>     defineStructure(ISAKMP_POLICY, ctx.name.getText(), ctx, true);
> ```

I do not want more "unknownReferrers" if possible -- that's really just code for "we didn't bother tracking these" AFAIK.

If they're not referenced, how do they take effect? Should we just define a self-reference?

---

*[test_rigs/parsing-tests/unit-tests-undefined.ref, line 867 at r3](https://reviewable.io/reviews/batfish/batfish/1422#-LCoanTrEiMBHdoUbK31:-LCoanTrEiMBHdoUbK32:b-g8as3n) ([raw file](https://github.com/batfish/batfish/blob/baa169f39610f43b70fbfa139a873aeedac9994e/test_rigs/parsing-tests/unit-tests-undefined.ref#L867)):*
> ```
>       },
>       "undefined:route-map:usage:bgp inbound route-map:as1_to_as2" : {
>         "description" : "Undefined reference to structure of type: 'route-map' with usage: 'bgp inbound route-map' named 'as1_to_as2'",
> ```

This seems like a bug (and reflected in the unit-tests.ref, too) -- the line here is `bgp_address_family:26:  neighbor as2 route-map as1_to_as2 out`. Not an inbound route map.

---

*[test_rigs/parsing-tests/unit-tests-undefined.ref, line 1124 at r3](https://reviewable.io/reviews/batfish/batfish/1422#-LCob-Kx7yDlQVQQro9V:-LCob-Kx7yDlQVQQro9W:b-oqv2zt) ([raw file](https://github.com/batfish/batfish/blob/baa169f39610f43b70fbfa139a873aeedac9994e/test_rigs/parsing-tests/unit-tests-undefined.ref#L1124)):*
> ```
>             "bgp inbound route-map" : [
>               28
>             ],
> ```

this bug.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1422)*

**Comment by arifogel** [comment]
Reviewed 2 of 2 files at r3, 7 of 7 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1422)*

**Comment by dhalperi** [comment]
:lgtm:

---

Reviewed 4 of 7 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1422#-:-LCp8pZxAT8F_JOLSsOa:bnfp4nl)*

**Comment by sfraint** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 1531 at r3](https://reviewable.io/reviews/batfish/batfish/1422#-LCo_I9Y6CHzfZOuGFoU:-LCofftv6wdRQWUPZDEk:b-88p5l6) ([raw file](https://github.com/batfish/batfish/blob/baa169f39610f43b70fbfa139a873aeedac9994e/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L1531)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I do not want more "unknownReferrers" if possible -- that's really just code for "we didn't bother tracking these" AFAIK.

If they're not referenced, how do they take effect? Should we just define a self-reference?
</blockquote></details>

As I understand it, this set of structures are just automatically checked in order when ISAKMP is invoked.

Maybe a self-reference would be a good alternative, just need to add a new self-reference usage.

---

*[test_rigs/parsing-tests/unit-tests-undefined.ref, line 867 at r3](https://reviewable.io/reviews/batfish/batfish/1422#-LCoanTrEiMBHdoUbK31:-LCoejmNBF4rf821YpVX:b8gj3mz) ([raw file](https://github.com/batfish/batfish/blob/baa169f39610f43b70fbfa139a873aeedac9994e/test_rigs/parsing-tests/unit-tests-undefined.ref#L867)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

This seems like a bug (and reflected in the unit-tests.ref, too) -- the line here is `bgp_address_family:26:  neighbor as2 route-map as1_to_as2 out`. Not an inbound route map.
</blockquote></details>

Good catch, fixed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1422)*

**Comment by sfraint** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[test_rigs/parsing-tests/unit-tests-undefined.ref, line 1124 at r3](https://reviewable.io/reviews/batfish/batfish/1422#-LCob-Kx7yDlQVQQro9V:-LCpChvF1_Uhwq7ScAN8:b32w0x) ([raw file](https://github.com/batfish/batfish/blob/baa169f39610f43b70fbfa139a873aeedac9994e/test_rigs/parsing-tests/unit-tests-undefined.ref#L1124)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

this bug.
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1422)*

**Comment by dhalperi** [comment]
Reviewed 5 of 17 files at r1, 3 of 7 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 1531 at r3](https://reviewable.io/reviews/batfish/batfish/1422#-LCo_I9Y6CHzfZOuGFoU:-LCpEzxY6zdvj-V4Z1E2:bbvuosh) ([raw file](https://github.com/batfish/batfish/blob/baa169f39610f43b70fbfa139a873aeedac9994e/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L1531)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

As I understand it, this set of structures are just automatically checked in order when ISAKMP is invoked.

Maybe a self-reference would be a good alternative, just need to add a new self-reference usage.
</blockquote></details>

This looks correct, but I think we should redo the structures and comments a little bit to make it clearer.

From the ASA manual [0], I see that this field is a `priority`, not a `name`, and yes they are checked in order. So my suggestions would be:

- rename `name` to `priority` in the grammar.
- pad the name to 2 digits (since there can be more than 10, but not more than 100 in any manual I could find) so that sorting by name "works"
- add a comment for the self-reference.

[0] https://www.cisco.com/c/en/us/td/docs/security/asa/asa72/configuration/guide/conf_gd/ike.html

Of course, a huge caveat here is that all vendors that match this grammar behave the same. If not, we need some sort of switch on ConfigurationFormat.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1422)*

**Comment by dhalperi** [comment]
Reviewed 4 of 4 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 1527 at r5](https://reviewable.io/reviews/batfish/batfish/1422#-LCpOVFBA81Iao3FVi3h:-LCpOVFBA81Iao3FVi3i:b-od8pci) ([raw file](https://github.com/batfish/batfish/blob/52252d787183be2fcafd47f57e41e49bc3eb71df/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L1527)):*
> ```
> %3s
> ```

can't you do `%03s` and avoid the replace?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1422)*

**Comment by arifogel** [comment]
Reviewed 4 of 4 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 1527 at r5](https://reviewable.io/reviews/batfish/batfish/1422#-LCpe6xxD9lRP2qqrQM9:-LCpe6xy7usXtlBd3Q2U:bh6qbp3) ([raw file](https://github.com/batfish/batfish/blob/52252d787183be2fcafd47f57e41e49bc3eb71df/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L1527)):*
> ```Java
>     }
>     /* Pad priority number with zeros, so string sorting sorts in numerical order too */
>     String priority = String.format("%3s", ctx.priority.getText()).replace(' ', '0');
> ```

If priority is a number, perhaps it should be a `DEC` in the grammar?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1422)*

**Comment by sfraint** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 1527 at r5](https://reviewable.io/reviews/batfish/batfish/1422#-LCpOVFBA81Iao3FVi3h:-LCpfyVN6-Hp_YGRoNF4:brqssda) ([raw file](https://github.com/batfish/batfish/blob/52252d787183be2fcafd47f57e41e49bc3eb71df/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L1527)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> %3s
> ```

can't you do `%03s` and avoid the replace?
</blockquote></details>

Using `%03d` after converting the text to an Integer

---

*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 1527 at r5](https://reviewable.io/reviews/batfish/batfish/1422#-LCpe6xxD9lRP2qqrQM9:-LCpg0oE74odq49asCZu:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/52252d787183be2fcafd47f57e41e49bc3eb71df/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L1527)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

If priority is a number, perhaps it should be a `DEC` in the grammar?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1422)*

**Comment by arifogel** [comment]
Reviewed 4 of 4 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 1527 at r6](https://reviewable.io/reviews/batfish/batfish/1422#-LCpnFp1ESbtCH-fVIhv:-LCpnFp1ESbtCH-fVIhw:b-hhlwki) ([raw file](https://github.com/batfish/batfish/blob/4f9880c40e31a92e9dd94544218eb7107050a92a/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L1527)):*
> ```Java
>     }
>     /* Pad priority number with zeros, so string sorting sorts in numerical order too */
>     String priority = String.format("%03d", Integer.parseInt(ctx.priority.getText()));
> ```

We have a helper function `toInteger` you can use on `ctx.priority` to be slightly more concise.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1422)*

**Comment by sfraint** [comment]
Review status: 16 of 20 files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 1527 at r6](https://reviewable.io/reviews/batfish/batfish/1422#-LCpnFp1ESbtCH-fVIhv:-LCppTun1fOcvFJ7SMCg:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/4f9880c40e31a92e9dd94544218eb7107050a92a/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L1527)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

We have a helper function `toInteger` you can use on `ctx.priority` to be slightly more concise.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1422)*

**Comment by arifogel** [comment]
Reviewed 4 of 4 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1422)*

**Pull request merged**
