### PR TITLE
Fix interface status issues

### PR DESCRIPTION
**Pull request by arifogel**
Fixes to bugs introduced by batfish/batfish#7939
- node blacklist should disable all interfaces, not just physical
- node blacklist should not mark individual interfaces as blacklisted
- clean up API
- clean up javadocs

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7960)* status: all files reviewed, 2 unresolved discussions (waiting on @arifogel and @corinaminer)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java, line 211 at r1](https://reviewable.io/reviews/batfish/batfish/7960#-Mtp6hOC728M8xH9qyYd:-Mtp6hOC728M8xH9qyYe:bdjbyva) ([raw file](https://github.com/batfish/batfish/blob/63e8361af662fb658da51641791c36c4e8a52c8e/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java#L211)):*
> ```Java
>       }
>       if (iface.hasLineStatus() && Boolean.FALSE.equals(_lineUp)) {
>         iface.disconnect(FORCED_LINE_DOWN);
> ```

This doesn't look like test code.. is it?
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java, line 2161 at r1](https://reviewable.io/reviews/batfish/batfish/7960#-Mtp7DaUA5Me7W7lu9Yz:-Mtp7DaUA5Me7W7lu9Z-:b-mc1khp) ([raw file](https://github.com/batfish/batfish/blob/63e8361af662fb658da51641791c36c4e8a52c8e/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java#L2161)):*
> ```Java
>    */
>   @VisibleForTesting
>   public void activate() {
> ```

Prefer rename to something like `activateForTest`



_Code quote:_
```Java
activate
```

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7960)* status: all files reviewed, 2 unresolved discussions (waiting on @corinaminer and @dhalperi)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java, line 211 at r1](https://reviewable.io/reviews/batfish/batfish/7960#-Mtp6hOC728M8xH9qyYd:-Mtp8Ayl9AIvW6gve6O7:brpzgfh) ([raw file](https://github.com/batfish/batfish/blob/63e8361af662fb658da51641791c36c4e8a52c8e/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java#L211)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

This doesn't look like test code.. is it?
</blockquote></details>

Technically no, but you only get here if you use `Builder::setLineUp`, which should only be called from tests per its javadoc.

Updated the comment in `deactivate` to note it can be used internally (even though strictly speaking it isn't).
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java, line 2161 at r1](https://reviewable.io/reviews/batfish/batfish/7960#-Mtp7DaUA5Me7W7lu9Yz:-MtpA1Rd0IzoQ7DaJLTV:b-6xjp1f) ([raw file](https://github.com/batfish/batfish/blob/63e8361af662fb658da51641791c36c4e8a52c8e/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java#L2161)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Prefer rename to something like `activateForTest`
</blockquote></details>

changed, and added a test

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7960)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7960)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

**Pull request merged**
