### PR TITLE
pmd: upgrade to latest, fix a few issues and ignore others

### PR DESCRIPTION
**Pull request by dhalperi**

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8871)* status: 0 of 25 files reviewed, all discussions resolved (waiting on @arifogel, @progwriter, and @SLarkworthy)

___
*[`projects/batfish/src/main/java/org/batfish/bddreachability/OriginationStateToTerminationState.java` line 44 at r1](https://reviewable.io/reviews/batfish/batfish/8871#-NkNdrtr9iriGJwwxu-N:-NkNdrtr9iriGJwwxu-O:b8qxnu9) ([raw file](https://github.com/batfish/batfish/blob/058a1b9c8c362d98c8937ee92a0c9f7a090fdb29/projects/batfish/src/main/java/org/batfish/bddreachability/OriginationStateToTerminationState.java#L44)):*
> ```Java
>  * non-origination states.
>  */
> @SuppressWarnings("PMD.ReturnEmptyCollectionRatherThanNull")
> ```

FYI this is just us choosing to use `@Nullable Collection` instead of `Optional<Collection>` to distinguish between two types of output. We do this (kinda silly) thing throughout.
___
*[`projects/batfish/src/main/java/org/batfish/dataplane/rib/Bgpv4Rib.java` line 130 at r1](https://reviewable.io/reviews/batfish/batfish/8871#-NkNdywn2Uob2uIpM52f:-NkNdywn2Uob2uIpM52g:b-5h526n) ([raw file](https://github.com/batfish/batfish/blob/058a1b9c8c362d98c8937ee92a0c9f7a090fdb29/projects/batfish/src/main/java/org/batfish/dataplane/rib/Bgpv4Rib.java#L130)):*
> ```Java
> 
>   @SuppressWarnings("PMD.NonSerializableClass") // this class is never serialized in practice
>   private final @Nonnull ResolvabilityEnforcer _resolvabilityEnforcer;
> ```

FYI @progwriter maybe check me on this weirdness. or @arifogel 
___
*[`projects/batfish/src/main/java/org/batfish/representation/fortios/Service.java` line 61 at r1](https://reviewable.io/reviews/batfish/batfish/8871#-NkNe1SJDS1b4KujyEkp:-NkNe1SJDS1b4KujyEkq:b-blm03p) ([raw file](https://github.com/batfish/batfish/blob/75887c078d414ac3a82ce53fcc8cdcb734016baf/projects/batfish/src/main/java/org/batfish/representation/fortios/Service.java#L61)):*
> ```Java
>   }
> 
>   public @Nullable IpRange getIpRange() {
> ```

fyi this was unused and was in fact a static helper class that makes no sense to use as a member. Caught by the serializable check.
___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfNeighbor.java` line 20 at r1](https://reviewable.io/reviews/batfish/batfish/8871#-NkNeC5T8gD-JCUFHZ0W:-NkNeC5U4a0-S_v07lI-:b-s4buke) ([raw file](https://github.com/batfish/batfish/blob/75887c078d414ac3a82ce53fcc8cdcb734016baf/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfNeighbor.java#L20)):*
> ```Java
> /** Configuration for one end of an OSPF adjacency */
> @ParametersAreNonnullByDefault
> public final class OspfNeighbor implements Serializable, Comparable<OspfNeighbor> {
> ```

FYI this is only json serialized, but it was complaining about a member not being serializable.
___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/InvalidReachabilityParametersException.java` line 7 at r1](https://reviewable.io/reviews/batfish/batfish/8871#-NkNeGvB1dpyGYurHqWi:-NkNeGvB1dpyGYurHqWj:b-6kragx) ([raw file](https://github.com/batfish/batfish/blob/058a1b9c8c362d98c8937ee92a0c9f7a090fdb29/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/InvalidReachabilityParametersException.java#L7)):*
> ```Java
> public class InvalidReachabilityParametersException extends Exception {
> 
>   private final String _invalidParametersMessage;
> ```

FYI exceptions are supposed to be serializable. Was easy to make this one so.
___
*[`skylark/pmd/pmd-ruleset.xml` line 54 at r1](https://reviewable.io/reviews/batfish/batfish/8871#-NkNePWrD3C-tsQ9V2B2:-NkNePWrD3C-tsQ9V2B3:b-hlbaft) ([raw file](https://github.com/batfish/batfish/blob/75887c078d414ac3a82ce53fcc8cdcb734016baf/skylark/pmd/pmd-ruleset.xml#L54)):*
> ```XML
>         <exclude name="AvoidFieldNameMatchingTypeName"/>
>         <exclude name="AvoidLiteralsInIfCondition"/>
>         <exclude name="BeanMembersShouldSerialize"/>
> ```

FYI I made this one pass via those ~3 changes to serializable classes. (It was also renamed)
___
*[`skylark/pmd/pmd-ruleset.xml` line 60 at r1](https://reviewable.io/reviews/batfish/batfish/8871#-NkNeVQl5avmkaqMmDnU:-NkNeVQl5avmkaqMmDnV:b7hyln2) ([raw file](https://github.com/batfish/batfish/blob/058a1b9c8c362d98c8937ee92a0c9f7a090fdb29/skylark/pmd/pmd-ruleset.xml#L60)):*
> ```XML
>         <exclude name="EmptyCatchBlock"/>
>         <exclude name="EmptyIfStmt"/>
>         <exclude name="ImplicitSwitchFallThrough"/>
> ```

FYI this is a rename.
___
*[`skylark/pmd/pmd-ruleset.xml` line 77 at r1](https://reviewable.io/reviews/batfish/batfish/8871#-NkNeX4U0quLOvo02AmG:-NkNeX4U0quLOvo02AmH:bniljvo) ([raw file](https://github.com/batfish/batfish/blob/058a1b9c8c362d98c8937ee92a0c9f7a090fdb29/skylark/pmd/pmd-ruleset.xml#L77)):*
> ```XML
>         </properties>
>     </rule>
> ```

FYI this prevents a false positive on things named `TestFooBar` that we have in our tests, like `TestBatfish`. The default parameter includes things that start or end with `Test` (among other things)

**Review by arifogel — COMMENTED** [review]
> Reviewed 25 of 25 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8871)* status: all files reviewed, 2 unresolved discussions (waiting on @dhalperi, @progwriter, and @SLarkworthy)

___
*[`projects/batfish/src/main/java/org/batfish/dataplane/rib/Bgpv4Rib.java` line 130 at r1](https://reviewable.io/reviews/batfish/batfish/8871#-NkNdywn2Uob2uIpM52f:-NkNigLdA3x8qtySVyBC:b-32wgeo) ([raw file](https://github.com/batfish/batfish/blob/058a1b9c8c362d98c8937ee92a0c9f7a090fdb29/projects/batfish/src/main/java/org/batfish/dataplane/rib/Bgpv4Rib.java#L130)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

FYI @progwriter maybe check me on this weirdness. or @arifogel
</blockquote></details>

I don't understand why Bgpv4Rib is `Serializable` if it's never serialized. Need to dig.
___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/PacketHeaderConstraints.java` line 508 at r1](https://reviewable.io/reviews/batfish/batfish/8871#-NkNgrJKE-cfU5lUyi0S:-NkNgrJKE-cfU5lUyi0T:b-4n6eog) ([raw file](https://github.com/batfish/batfish/blob/058a1b9c8c362d98c8937ee92a0c9f7a090fdb29/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/PacketHeaderConstraints.java#L508)):*
> ```Java
>       @Nullable IntegerSpace icmpCodes)
>       throws IllegalArgumentException {
>     @Nullable
> ```

Interesting that this annotation is not required to be after comment following earlier changes.
___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java` line 112 at r1](https://reviewable.io/reviews/batfish/batfish/8871#-NkNhStUDOPWp6aS1rDw:-NkNhStV4qkf2sOnlycZ:b-r01xsv) ([raw file](https://github.com/batfish/batfish/blob/058a1b9c8c362d98c8937ee92a0c9f7a090fdb29/projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java#L112)):*
> ```Java
> /** A utility class that abstracts the underlying file system storage used by Batfish. */
> @ParametersAreNonnullByDefault
> @SuppressWarnings("PMD.ReturnEmptyCollectionRatherThanNull")
> ```

This is pretty broad at the class level. Where were the actual violations?

Construe this generally
___
*[`projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/LongSpaceTest.java` line 269 at r1](https://reviewable.io/reviews/batfish/batfish/8871#-NkNho731kVkt1sgKSCo:-NkNho731kVkt1sgKSCp:b95c2id) ([raw file](https://github.com/batfish/batfish/blob/058a1b9c8c362d98c8937ee92a0c9f7a090fdb29/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/LongSpaceTest.java#L269)):*
> ```Java
>     assertFalse(
>         "Space does not contain excluded values",
>         space.contains(builder().including(Range.closed(1L, 2L)).build()));
> ```

Why add inconsistent static import?

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8871)* status: all files reviewed, 2 unresolved discussions (waiting on @arifogel, @progwriter, and @SLarkworthy)

___
*[`projects/batfish/src/main/java/org/batfish/dataplane/rib/Bgpv4Rib.java` line 130 at r1](https://reviewable.io/reviews/batfish/batfish/8871#-NkNdywn2Uob2uIpM52f:-NkNjN468DbuIrygSQwc:b7vya7m) ([raw file](https://github.com/batfish/batfish/blob/058a1b9c8c362d98c8937ee92a0c9f7a090fdb29/projects/batfish/src/main/java/org/batfish/dataplane/rib/Bgpv4Rib.java#L130)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

I don't understand why Bgpv4Rib is `Serializable` if it's never serialized. Need to dig.
</blockquote></details>

This inherits from a `Serializable` class (`GenericRib`)
___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java` line 112 at r1](https://reviewable.io/reviews/batfish/batfish/8871#-NkNhStUDOPWp6aS1rDw:-NkNjSkmB0iCpgccOvj2:bhogo4t) ([raw file](https://github.com/batfish/batfish/blob/058a1b9c8c362d98c8937ee92a0c9f7a090fdb29/projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java#L112)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

This is pretty broad at the class level. Where were the actual violations?

Construe this generally
</blockquote></details>

The pattern is all over this class (>10 times). Annoyingly, the suppressions are not inherited from the parent interface.
___
*[`projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/LongSpaceTest.java` line 269 at r1](https://reviewable.io/reviews/batfish/batfish/8871#-NkNho731kVkt1sgKSCo:-NkNjeWCB8iWCYTphhBo:bkxt5gz) ([raw file](https://github.com/batfish/batfish/blob/058a1b9c8c362d98c8937ee92a0c9f7a090fdb29/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/LongSpaceTest.java#L269)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Why add inconsistent static import?
</blockquote></details>

It was already statically imported, as evidence by the lack of change in imports. IntelliJ did this on its own when it fixed the assertions - maybe overzealous optimization for only the lines it changed?

I can revert if that's a blocker.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8871)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @progwriter and @SLarkworthy)

___
*[`projects/batfish/src/main/java/org/batfish/dataplane/rib/Bgpv4Rib.java` line 130 at r1](https://reviewable.io/reviews/batfish/batfish/8871#-NkNdywn2Uob2uIpM52f:-NkNo9HM6l3IOxC-2qF0:b-rvusbw) ([raw file](https://github.com/batfish/batfish/blob/058a1b9c8c362d98c8937ee92a0c9f7a090fdb29/projects/batfish/src/main/java/org/batfish/dataplane/rib/Bgpv4Rib.java#L130)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

This inherits from a `Serializable` class (`GenericRib`)
</blockquote></details>

Ah we only serialize a table of bgp routes now. We should potentially consider removing `Serializable` from RIBs in the future, but way out of scope for now. Resolving.
___
*[`projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/LongSpaceTest.java` line 269 at r1](https://reviewable.io/reviews/batfish/batfish/8871#-NkNho731kVkt1sgKSCo:-NkNoKTK9a_lpe1MVSJN:b5dv303) ([raw file](https://github.com/batfish/batfish/blob/058a1b9c8c362d98c8937ee92a0c9f7a090fdb29/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/LongSpaceTest.java#L269)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

It was already statically imported, as evidence by the lack of change in imports. IntelliJ did this on its own when it fixed the assertions - maybe overzealous optimization for only the lines it changed?

I can revert if that's a blocker.
</blockquote></details>

meh, if we don't enforce it it doesn't matter.

**Comment by dhalperi** [comment]
*[`projects/batfish/src/main/java/org/batfish/dataplane/rib/Bgpv4Rib.java` line 130 at r1](https://reviewable.io/reviews/batfish/batfish/8871#-NkNdywn2Uob2uIpM52f:-NkNsLY-7J2VYvogxr5u:bfjrb48) ([raw file](https://github.com/batfish/batfish/blob/058a1b9c8c362d98c8937ee92a0c9f7a090fdb29/projects/batfish/src/main/java/org/batfish/dataplane/rib/Bgpv4Rib.java#L130)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Ah we only serialize a table of bgp routes now. We should potentially consider removing `Serializable` from RIBs in the future, but way out of scope for now. Resolving.
</blockquote></details>

Done. https://reviewable.io/reviews/batfish/batfish/8872

**Pull request merged**
