### PR TITLE
fix NPE in ForwardingAnalsysis for nodes with no neighbors

### PR DESCRIPTION
**Pull request by arifogel**

### CODE REVIEW

**Comment by anothermattbrown** [comment]
Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ForwardingAnalysisImplTest.java, line 511 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1106#-L8dW99eAb6i3xn4ssM4:-L8dW99eAb6i3xn4ssM5:b-1zo2jw) ([raw file](https://github.com/batfish/batfish/blob/4ca7933da4607706308390331e55597ec44d8257/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ForwardingAnalysisImplTest.java#L511)):*
> ```Java
> 
>   @Test
>   public void testComputeNeighborUnreachableArpDestIpNoNeighbors() {
> ```

Please add a comment describing what's being tested.

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ForwardingAnalysisImplTest.java, line 882 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1106#-L8dWLrt04TBmoFuzht-:-L8dWLrt04TBmoFuzht0:b-1zo2jw) ([raw file](https://github.com/batfish/batfish/blob/4ca7933da4607706308390331e55597ec44d8257/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ForwardingAnalysisImplTest.java#L882)):*
> ```Java
> 
>   @Test
>   public void testComputeRoutesWithNextHopIpFalseForInterfaceMissingHost() {
> ```

Please add a comment describing what's being tested.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1106)*

**Comment by arifogel** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ForwardingAnalysisImplTest.java, line 511 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1106#-L8dW99eAb6i3xn4ssM4:-L8d_d4VAvO9TI0a8n-o:b-7gzlz4) ([raw file](https://github.com/batfish/batfish/blob/4ca7933da4607706308390331e55597ec44d8257/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ForwardingAnalysisImplTest.java#L511)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

Please add a comment describing what's being tested.
</blockquote></details>

Made an attempt

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ForwardingAnalysisImplTest.java, line 882 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1106#-L8dWLrt04TBmoFuzht-:-L8d_eJU7vUKteF-wfPW:b-7gzlz4) ([raw file](https://github.com/batfish/batfish/blob/4ca7933da4607706308390331e55597ec44d8257/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ForwardingAnalysisImplTest.java#L882)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

Please add a comment describing what's being tested.
</blockquote></details>

Made an attempt

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1106)*

**Comment by anothermattbrown** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1106)*

**Comment by anothermattbrown** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1106#-:-L8db0wM-dCCwupwAMUE:bnfp4nl)*

**Pull request merged**
