### PR TITLE
L2: Determine broadcast domains globally

### PR DESCRIPTION
**Pull request by corinaminer**
Fixes a bug where broadcast domains could be incorrectly defined if some set of VLANs was considered equivalent on one node but not on another. This fix identifies unique VLAN ranges globally (across nodes), so all nodes agree on which VLAN ranges are equivalent.

### CODE REVIEW

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6992)* status: 0 of 14 files reviewed, all discussions resolved (waiting on @arifogel)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6992#-M_OA5tkB5QznZ1g6ZKf:-M_OA5tkB5QznZ1g6ZKg:bkx5uuv) (no related file):*
Fyi: Turns out it is useful to retain the `InterfacesByVlanRange` class for a few useful utility methods, as well as to reduce refactoring in `TopologyUtils`. However, under the hood `InterfacesByVlanRange` is now immutable; all the `add` functionality is in `NodeInterfacePairsByVlanRange` (and the tests of that functionality moved to `NodeInterfacePairsByVlanRangeTest`).

---

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6992)* status: 11 of 14 files reviewed, 1 unresolved discussion (waiting on @arifogel)

___
*[projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java, line 857 at r2](https://reviewable.io/reviews/batfish/batfish/6992#-M_RPpB820spCTS_jP2j:-M_YSJJs0uIvKMsi4-fu:bvnrpcm) ([raw file](https://github.com/batfish/batfish/blob/bc33bd92ba72775a0b84b5cf36561cf0bf81f424/projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java#L857)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Please clarify that r1 and r2's subinterfaces are layer-3 subinterfaces using 802.1q encapsulation.

And while I understand, it may be useful to less experienced readers to note that the interfaces with "allowed VLANs" are switchports in _trunk_ mode.
</blockquote></details>

updated
___
*[projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java, line 937 at r2](https://reviewable.io/reviews/batfish/batfish/6992#-M_RPOwV736qFhwS-hs9:-M_YU8L_8bCIeXYmSICM:b-3ra8ng) ([raw file](https://github.com/batfish/batfish/blob/bc33bd92ba72775a0b84b5cf36561cf0bf81f424/projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java#L937)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

To confirm, at least one assertion from layer2 above and layer3 here fails without main code changes, right?
</blockquote></details>

yes, if you run this test on master, at least the first L2 check fails (i expect the second would too) and the L3 topology is empty
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/InterfacesByVlanRange.java, line 30 at r2](https://reviewable.io/reviews/batfish/batfish/6992#-M_RSJOmELfo8dsjFG3A:-M_YZNy07j1xUsZsVpBr:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/bc33bd92ba72775a0b84b5cf36561cf0bf81f424/projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/InterfacesByVlanRange.java#L30)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Please split into two separate check, and add a separate failure message to `checkArgument` for each.
Obviously have to check canonicity first.

Also, add constructor javadoc listing the preconditions.

</blockquote></details>

done
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TopologyUtil.java, line 91 at r2](https://reviewable.io/reviews/batfish/batfish/6992#-M_Re-uF7iu3n75L3WHr:-M_YeGxB64y7cGyvOSCe:b2vioaz) ([raw file](https://github.com/batfish/batfish/blob/bc33bd92ba72775a0b84b5cf36561cf0bf81f424/projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TopologyUtil.java#L91)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

This seems wrong. For every trunk between two hosts, you are creating a layer2 edge for every vlan range common to those nodes? You're not looking at the trunk settings at all.

Seems like the vlan ranges to intersect from each side should be only those intersecting the allowed vlans of that side's interface.

I should note that the original implementation looks half wrong in this regard as well.

Please add a test that a less permissive pair of trunks does not get the same number of edges as a more permissive pair of trunks (say, between the same hosts).
</blockquote></details>

You may well be right. I haven't added the test; I'm not too familiar with trunk settings. Will write it tomorrow.

That said, i'd vote to leave that fix (assuming one is required) for another PR -- I'm pretty confident that the behavior here did not change from master.

**Review by arifogel — COMMENTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6992)* status: all files reviewed, 2 unresolved discussions (waiting on @corinaminer)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/InterfacesByVlanRange.java, line 38 at r3](https://reviewable.io/reviews/batfish/batfish/6992#-M_aqlly9eUVOaMu22Un:-M_aqlly9eUVOaMu22Uo:bfhtyry) ([raw file](https://github.com/batfish/batfish/blob/88851e5f2a6598b866ae44a0a3dcd476f95a2f7b/projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/InterfacesByVlanRange.java#L38)):*
> ```Java
>         ranges.keySet().stream().filter(InterfacesByVlanRange::isInvalidRange).findAny();
>     if (invalidRange.isPresent()) {
>       throw new IllegalArgumentException(
> ```

nit: `if (condition) {throw IllegalArgumentException(String.format(args...)) }` is more concise as `checkArgument(!condition, args...)`
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TopologyUtil.java, line 91 at r2](https://reviewable.io/reviews/batfish/batfish/6992#-M_Re-uF7iu3n75L3WHr:-M_arh9X0dvVjAv8VO7z:b2f9862) ([raw file](https://github.com/batfish/batfish/blob/bc33bd92ba72775a0b84b5cf36561cf0bf81f424/projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TopologyUtil.java#L91)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

You may well be right. I haven't added the test; I'm not too familiar with trunk settings. Will write it tomorrow.

That said, i'd vote to leave that fix (assuming one is required) for another PR -- I'm pretty confident that the behavior here did not change from master.
</blockquote></details>

Fair, but then please add TODO.

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6992)* status: 12 of 14 files reviewed, all discussions resolved (waiting on @arifogel)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/InterfacesByVlanRange.java, line 38 at r3](https://reviewable.io/reviews/batfish/batfish/6992#-M_aqlly9eUVOaMu22Un:-M_auCen943NeHRaSa9G:b-rvmywx) ([raw file](https://github.com/batfish/batfish/blob/88851e5f2a6598b866ae44a0a3dcd476f95a2f7b/projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/InterfacesByVlanRange.java#L38)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

nit: `if (condition) {throw IllegalArgumentException(String.format(args...)) }` is more concise as `checkArgument(!condition, args...)`
</blockquote></details>

oh yeah, i've been using that, dunno why i switched this one
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TopologyUtil.java, line 91 at r2](https://reviewable.io/reviews/batfish/batfish/6992#-M_Re-uF7iu3n75L3WHr:-M_bBsr91Jei-VjXfEhw:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/bc33bd92ba72775a0b84b5cf36561cf0bf81f424/projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/TopologyUtil.java#L91)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Fair, but then please add TODO.
</blockquote></details>

done

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6992)* status: 12 of 14 files reviewed, 1 unresolved discussion (waiting on @arifogel and @corinaminer)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/InterfacesByVlanRange.java, line 39 at r4](https://reviewable.io/reviews/batfish/batfish/6992#-M_bIUDs-RCePmeM_gTY:-M_bIUDs-RCePmeM_gTZ:b7o2q3p) ([raw file](https://github.com/batfish/batfish/blob/38b2cb925eb208179865f48b55060b72016b2473/projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/InterfacesByVlanRange.java#L39)):*
> ```Java
>     checkArgument(
>         !invalidRange.isPresent(),
>         String.format("Range %s cannot be used in InterfacesByVlanRange", invalidRange.get()));
> ```

Get rid of `String.format( )`
checkArguments args from 2 on are varargs passed to String.format (with slight exception that only `%s` is allowed).
It's redundant.

**Review by arifogel — COMMENTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6992)* status: all files reviewed, 1 unresolved discussion (waiting on @corinaminer)

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6992)* status: 13 of 14 files reviewed, all discussions resolved (waiting on @arifogel)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/InterfacesByVlanRange.java, line 39 at r4](https://reviewable.io/reviews/batfish/batfish/6992#-M_bIUDs-RCePmeM_gTY:-M_bJSnJ6kMJhp503IMO:b-fs3brr) ([raw file](https://github.com/batfish/batfish/blob/38b2cb925eb208179865f48b55060b72016b2473/projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/InterfacesByVlanRange.java#L39)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Get rid of `String.format( )`
checkArguments args from 2 on are varargs passed to String.format (with slight exception that only `%s` is allowed).
It's redundant.
</blockquote></details>

done. also tests were failing because `invalidRange.get()` was being invoked even when no invalid range was present, so fixed that.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6992)* status: 13 of 14 files reviewed, 1 unresolved discussion (waiting on @arifogel and @corinaminer)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/InterfacesByVlanRange.java, line 41 at r5](https://reviewable.io/reviews/batfish/batfish/6992#-M_bMCK_A2TVUBqjYjbR:-M_bMCK_A2TVUBqjYjbS:bn7fsup) ([raw file](https://github.com/batfish/batfish/blob/f9be37d8ea0821a68e6a08257e96f5f0580e21c1/projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/InterfacesByVlanRange.java#L41)):*
> ```Java
>             .orElse(null);
>     checkArgument(
>         invalidRange == null, "Range %s cannot be used in InterfacesByVlanRange", invalidRange);
> ```

Should be `invalidRange != null`, and there is still no point printing invalidRange, which will be null in the message.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6992)* status: 13 of 14 files reviewed, all discussions resolved (waiting on @arifogel)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/InterfacesByVlanRange.java, line 41 at r5](https://reviewable.io/reviews/batfish/batfish/6992#-M_bMCK_A2TVUBqjYjbR:-M_bMNfG9z53b-hJ_myv:b3t4hkq) ([raw file](https://github.com/batfish/batfish/blob/f9be37d8ea0821a68e6a08257e96f5f0580e21c1/projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/InterfacesByVlanRange.java#L41)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Should be `invalidRange != null`, and there is still no point printing invalidRange, which will be null in the message.
</blockquote></details>

Wait never, mind, just reread. It's fine.

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6992)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

**Pull request merged**
