### PR TITLE
 Junos : Add parser support for `set protocols isis overload advertise-high-metrics`

### PR DESCRIPTION
**Pull request by pranavbj-amzn**
From [juniper docs](https://www.juniper.net/documentation/us/en/software/junos/is-is/topics/ref/statement/overload-edit-protocols-isis.html#id-11219126__d40056e109):

```
The advertise-high-metric setting is only valid while the routing device is in overload mode. When advertise-high-metric is configured, IS-IS does not set the overload bit. Rather, it sets the metric to 63 or 16,777,214, depending whether wide metrics are enabled. This allows the overloaded routing device to be used for transit as a last resort.

An L1-L2 router in overload mode stops leaking route information between L1 and L2 levels and clears its attached bit. This is also true when advertise-high-metrics is configured.
```

For now marking it as a `todo` to model this correctly. This fix handles the parse warning.

### CODE REVIEW

**Comment by dhalperi** [comment]
*[`projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_isis.g4` line 84 at r1](https://reviewable.io/reviews/batfish/batfish/8888#-Nlzfy52CylMGAZbSayV:-Nlzfy52CylMGAZbSayW:bc0ose) ([raw file](https://github.com/batfish/batfish/blob/a54e44a26372024a59b6ed2b55f1b8b0aaae900d/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_isis.g4#L84)):*
> ```ANTLR
>   (
>     advertise_high_metrics
>     | apply
> ```

`apply` is the junos-specific exception to alphabetization -- it's always first if present. Sorry.

(This is because it's a stupid meta thing that's required for flattening and apply-groups and weird hierarchical config stuff. Sorry.)



_Code quote:_
```ANTLR
    advertise_high_metrics
    | apply
```

**Review by dhalperi — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8888)* status: all files reviewed, 3 unresolved discussions (waiting on @pranavbj-amzn)

___
*[`projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_isis.g4` line 83 at r1](https://reviewable.io/reviews/batfish/batfish/8888#-NlzgEqN35Vm9vo2Niny:-NlzgEqO7piMsBSO6pVn:bkzwt45) ([raw file](https://github.com/batfish/batfish/blob/a54e44a26372024a59b6ed2b55f1b8b0aaae900d/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_isis.g4#L83)):*
> ```ANTLR
>   OVERLOAD
>   (
>     advertise_high_metrics
> ```

`iso_advertise_high_metrics` representing the `iso_` prefix for `isis overload`. Again, `apply` is a weird Junos-specific exception to this. Sorry!



_Code quote:_
```ANTLR
advertise_high_metrics
```
___
*[`projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java` line 1639 at r1](https://reviewable.io/reviews/batfish/batfish/8888#-NlzgZ7a-8Ofi8OubuJE:-NlzgZ7a-8Ofi8OubuJF:b2dh1pa) ([raw file](https://github.com/batfish/batfish/blob/a54e44a26372024a59b6ed2b55f1b8b0aaae900d/projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java#L1639)):*
> ```Java
>         hasParseWarning(
>             "configs/" + hostname, containsString("This feature is not currently supported")));
>   }
> ```

fine as-is, but also you don't need to check for warnings with `todo`. Those can be assumed to just work, and code coverage will make sure the line gets hit.



_Code quote:_
```Java
    String hostname = "juniper-set-protocols-isis";
    Batfish batfish = getBatfishForConfigurationNames(hostname);
    ParseVendorConfigurationAnswerElement pvcae =
        batfish.loadParseVendorConfigurationAnswerElement(batfish.getSnapshot());
    assertEquals(pvcae.getWarnings().size(), 1);
    assertThat(
        pvcae,
        hasParseWarning(
            "configs/" + hostname, containsString("This feature is not currently supported")));
  }
```

**Review by dhalperi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8888)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @pranavbj-amzn)

___
*[`projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java` line 5847 at r2](https://reviewable.io/reviews/batfish/batfish/8888#-NlzqWAg0mgd1PTy2hds:-NlzqWAg0mgd1PTy2hdt:bia737j) ([raw file](https://github.com/batfish/batfish/blob/7a95d18fdbee9335ac803e804dc04f61863939a3/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L5847)):*
> ```Java
> 
>   @Override
>   public void exitAdvertise_high_metrics(Advertise_high_metricsContext ctx) {
> ```

FYI needs to be changed now that you renamed the rule

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8888)* status: all files reviewed, 1 unresolved discussion (waiting on @pranavbj-amzn)

**Review by pranavbj-amzn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8888)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[`projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_isis.g4` line 83 at r1](https://reviewable.io/reviews/batfish/batfish/8888#-NlzgEqN35Vm9vo2Niny:-NlzqNyvBnqGnsFQIhqA:bui05z0) ([raw file](https://github.com/batfish/batfish/blob/a54e44a26372024a59b6ed2b55f1b8b0aaae900d/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_isis.g4#L83)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

`iso_advertise_high_metrics` representing the `iso_` prefix for `isis overload`. Again, `apply` is a weird Junos-specific exception to this. Sorry!
</blockquote></details>

okay interesting, updated accordingly!
___
*[`projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_isis.g4` line 84 at r1](https://reviewable.io/reviews/batfish/batfish/8888#-Nlzfy52CylMGAZbSayV:-Nlzqa5v9EbRDZuysOBc:b-7ql1td) ([raw file](https://github.com/batfish/batfish/blob/a54e44a26372024a59b6ed2b55f1b8b0aaae900d/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_isis.g4#L84)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

`apply` is the junos-specific exception to alphabetization -- it's always first if present. Sorry.

(This is because it's a stupid meta thing that's required for flattening and apply-groups and weird hierarchical config stuff. Sorry.)
</blockquote></details>

fixed
___
*[`projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java` line 5847 at r2](https://reviewable.io/reviews/batfish/batfish/8888#-NlzqWAg0mgd1PTy2hds:-Nlzqd1I4CMGNpCZdhmR:brznp1p) ([raw file](https://github.com/batfish/batfish/blob/7a95d18fdbee9335ac803e804dc04f61863939a3/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L5847)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

FYI needs to be changed now that you renamed the rule
</blockquote></details>

yes , done!
___
*[`projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java` line 1639 at r1](https://reviewable.io/reviews/batfish/batfish/8888#-NlzgZ7a-8Ofi8OubuJE:-Nlzqg5UD1EwWmemYGIr:b-aeqs40) ([raw file](https://github.com/batfish/batfish/blob/a54e44a26372024a59b6ed2b55f1b8b0aaae900d/projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java#L1639)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

fine as-is, but also you don't need to check for warnings with `todo`. Those can be assumed to just work, and code coverage will make sure the line gets hit.
</blockquote></details>

makes sense, will keep in mind.

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8888)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pranavbj-amzn)

___
*[`projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java` line 5847 at r2](https://reviewable.io/reviews/batfish/batfish/8888#-NlzqWAg0mgd1PTy2hds:-NlzqvwV-_2srZofiosa:bt9d90g) ([raw file](https://github.com/batfish/batfish/blob/7a95d18fdbee9335ac803e804dc04f61863939a3/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L5847)):*
<details><summary><i>Previously, pranavbj-amzn (Pranav Bhardwaj) wrote…</i></summary><blockquote>

yes , done!
</blockquote></details>

not pushed yet tho.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8888)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pranavbj-amzn)

**Comment by dhalperi** [comment]
*[`projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java` line 230 at r3](https://reviewable.io/reviews/batfish/batfish/8888#-NlzraesEWo1avEKX7gT:-NlzraesEWo1avEKX7gU:bj1haiq) ([raw file](https://github.com/batfish/batfish/blob/65606a76f64c175342acfa5f1f550f62d4c03bb7/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L230)):*
> ```Java
> import org.batfish.grammar.flatjuniper.FlatJuniperParser.Address_specifierContext;
> import org.batfish.grammar.flatjuniper.FlatJuniperParser.Address_specifier_nameContext;
> import org.batfish.grammar.flatjuniper.FlatJuniperParser.Iso_advertise_high_metricsContext;
> ```

looks like IDE didn't resort imports correctly.



_Code quote:_
```Java
erParser.Iso_ad
```

**Review by pranavbj-amzn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8888)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[`projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java` line 230 at r3](https://reviewable.io/reviews/batfish/batfish/8888#-NlzraesEWo1avEKX7gT:-NlzsbbFC8piGk5m9aT7:b-festrk) ([raw file](https://github.com/batfish/batfish/blob/65606a76f64c175342acfa5f1f550f62d4c03bb7/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L230)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

looks like IDE didn't resort imports correctly.
</blockquote></details>

thanks, 

is there a command to run `formatting` check locally ?

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8888)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pranavbj-amzn)

___
*[`projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java` line 230 at r3](https://reviewable.io/reviews/batfish/batfish/8888#-NlzraesEWo1avEKX7gT:-Nlzszos3qucpFnsP_eh:b-48iy84) ([raw file](https://github.com/batfish/batfish/blob/65606a76f64c175342acfa5f1f550f62d4c03bb7/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L230)):*
<details><summary><i>Previously, pranavbj-amzn (Pranav Bhardwaj) wrote…</i></summary><blockquote>

thanks, 

is there a command to run `formatting` check locally ?
</blockquote></details>

`./tools/fix_java_format.sh` Also, the `pre-commit` hooks you set up if you followed the dev instructions. Also, hopefully, the IDE does it on AutoSave using the google-java-format plugin.

**Pull request merged**
