### PR TITLE
FinalizeConfiguration: reject interfaces that have mixed L2+L3 configuration

### PR DESCRIPTION
**Pull request by dhalperi**
Will help us pin down issues in vendor specific parsing.

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7121)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @dhalperi)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7121#-MdTgWWY7uOebhqUZeID:-MdTgWWY7uOebhqUZeIE:b8g448r) (no related file):*
I suspect we are losing interfaces in VI model because some of those configs have incompatible settings on interfaces purely for grammar coverage.

---

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7121)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @dhalperi)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7121#-MdTgWWY7uOebhqUZeID:-MdTgxJS-XV9peQV9ubE:bncvof3) (no related file):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

I suspect we are losing interfaces in VI model because some of those configs have incompatible settings on interfaces purely for grammar coverage.
</blockquote></details>

Presumably said interfaces should be processed differently during {extraction, conversion}?

---

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7121)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @dhalperi)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7121#-MdTgWWY7uOebhqUZeID:-MdTgvGq9tt14W4zV6-2:b-ozx7tr) (no related file):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Presumably said interfaces should be processed differently during {extraction, conversion}?
</blockquote></details>

Correct. The resulting ref should only have one of l2 or l3 settings.

---

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7121)* status: 0 of 20 files reviewed, all discussions resolved (waiting on @dhalperi)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7121#-MdUWf-F3R3SD-_QHkte:-MdUWf-GA4KVFSleKad7:bwt5hhf) (no related file):*
FYI EOS seems to be the only vendor where we know confidently switchport mode at interface creation. So the rest of them are done in conversion.

---

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 14 of 14 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7121)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dhalperi)

**Review by arifogel — COMMENTED** [review]
> Reviewed 4 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7121)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dhalperi)

**Review by arifogel — COMMENTED** [review]
> Reviewed 5 of 5 files at r7, 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7121)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dhalperi)

**Pull request merged**
