### PR TITLE
IOS-XR extract and warn on vrf import/export route-policy

### PR DESCRIPTION
**Pull request by arifogel**

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 16 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6876)* status: 14 of 18 files reviewed, all discussions resolved (waiting on @arifogel)

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6876)* status: 14 of 18 files reviewed, 1 unresolved discussion (waiting on @arifogel)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6876#-MXj48aX-WIKpHGRKgFD:-MXj48aX-WIKpHGRKgFE:b-xweljz) (no related file):*
after batfish/batfish#6875

---

**Review by dhalperi — COMMENTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6876)* status: all files reviewed, 2 unresolved discussions (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java, line 6394 at r2](https://reviewable.io/reviews/batfish/batfish/6876#-MXj5Sks2XmJx1bTQ187:-MXj5Skt99i4QXCSnOlt:bb7nssx) ([raw file](https://github.com/batfish/batfish/blob/29008471f4ed377e5c6cb9a793198f67d3c7ce0d/projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java#L6394)):*
> ```Java
>   @Override
>   public void exitVrf_afe_route_policy(Vrf_afe_route_policyContext ctx) {
>     todo(ctx);
> ```

ref?

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6876)* status: 13 of 23 files reviewed, 1 unresolved discussion (waiting on @arifogel and @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java, line 6394 at r2](https://reviewable.io/reviews/batfish/batfish/6876#-MXj5Sks2XmJx1bTQ187:-MXjED5i0I3e3f8UlDk2:b7j1uzd) ([raw file](https://github.com/batfish/batfish/blob/29008471f4ed377e5c6cb9a793198f67d3c7ce0d/projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java#L6394)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

ref?
</blockquote></details>

done for ROUTE_POLICY.

I'd prefer to put off VRF references for another PR, as they aren't even defined yet.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6876)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @dhalperi)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6876#-MXjH5Xa0VLa4RTK1-sS:-MXjH5Xa0VLa4RTK1-sT:boeh4al) (no related file):*
Only r8 contains further changes.

---

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 4 files at r7, 3 of 3 files at r8, 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6876)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
