### PR TITLE
SearchRoutePolicies: Better handling of SetCommunities

### PR DESCRIPTION
**Pull request by millstein**
Overhauls the symbolic analysis of the SetCommunities routing statement to handle InputCommunities in a general way.  Previously we identified specific common patterns involving InputCommunities and handled them specially.  Now the symbolic analysis directly accounts for InputCommunities by tracking three sets of community atomic predicates: those definitely set by the SetCommunities statement; those definitely removed by the statement; and those that are in the route afterward if they were in the route beforehand.

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6878)* status: all files reviewed, 4 unresolved discussions (waiting on @millstein)

___
*[projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/CommunityAPDispositions.java, line 68 at r1](https://reviewable.io/reviews/batfish/batfish/6878#-MXmgWI9C_kPCWi3s0ja:-MXmgWI9C_kPCWi3s0jb:b-jeg5ed) ([raw file](https://github.com/batfish/batfish/blob/dff075ff7580059e499d0c16cf445c134c8cc9a4/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/CommunityAPDispositions.java#L68)):*
> ```Java
>   }
> 
>   // produce the set difference of two CommunityAPDispositions; the result is only
> ```

Please either convert to javadoc, or adjust visibility. If for some reason this must be public only for tests, add `@VisibleForTesting`. Applies generally to new public functions.
___
*[projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/CommunityAPDispositions.java, line 126 at r1](https://reviewable.io/reviews/batfish/batfish/6878#-MXrTCrPDDwvYQcFwEDk:-MXrTCrPDDwvYQcFwEDl:ble7qtz) ([raw file](https://github.com/batfish/batfish/blob/dff075ff7580059e499d0c16cf445c134c8cc9a4/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/CommunityAPDispositions.java#L126)):*
> ```Java
>   }
> 
>   public Set<Integer> getMustExist() {
> ```

Dumb question: Is there anything to be saved by using `IntegerSpace` instead of `Set<Integer>`? Would it simplify/obviate any of the helper/visitor function?
___
*[projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/SetCommunitiesVisitor.java, line 68 at r1](https://reviewable.io/reviews/batfish/batfish/6878#-MXrZ9Wa1SoajeTGzGoC:-MXrZ9Wa1SoajeTGzGoD:bvbwd7r) ([raw file](https://github.com/batfish/batfish/blob/dff075ff7580059e499d0c16cf445c134c8cc9a4/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/SetCommunitiesVisitor.java#L68)):*
> ```Java
>         arg.getTransferBDD().getConfiguration().getCommunitySetExprs().get(name);
>     if (setExpr == null) {
>       throw new BatfishException("Cannot find community set expression: " + name);
> ```

Prefer `checkArgument(setExpr != null, ...)`. Please no more `BatfishException`.
___
*[projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java, line 378 at r1](https://reviewable.io/reviews/batfish/batfish/6878#-MXr_tKf80OZI0qtfbWj:-MXr_tKf80OZI0qtfbWk:b-n4z1d3) ([raw file](https://github.com/batfish/batfish/blob/dff075ff7580059e499d0c16cf445c134c8cc9a4/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java#L378)):*
> ```Java
>             "Matching for communities other than the input communities is not supported: " + mc);
>       }
>       // Once we model static statements like SetReadIntermediateBgpAttributes, that will
> ```

Please add literal `TODO` in comment for visibility.
Bonus points for linking an issue.

**Review by millstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6878)* status: 6 of 9 files reviewed, 1 unresolved discussion (waiting on @arifogel)

___
*[projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/CommunityAPDispositions.java, line 126 at r1](https://reviewable.io/reviews/batfish/batfish/6878#-MXrTCrPDDwvYQcFwEDk:-MXtIvWy94bj9FqPScc9:b-6frtg5) ([raw file](https://github.com/batfish/batfish/blob/dff075ff7580059e499d0c16cf445c134c8cc9a4/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/CommunityAPDispositions.java#L126)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Dumb question: Is there anything to be saved by using `IntegerSpace` instead of `Set<Integer>`? Would it simplify/obviate any of the helper/visitor function?
</blockquote></details>

I looked into it, but IntegerSpaces don't support all of the operations I need, like intersection, and they are targeted at sets of contiguous integer ranges, which is not typically what I will have.  So I don't think it would help to switch to that.

**Review by millstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6878)* status: 6 of 9 files reviewed, 1 unresolved discussion (waiting on @arifogel)

___
*[projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/CommunityAPDispositions.java, line 126 at r1](https://reviewable.io/reviews/batfish/batfish/6878#-MXrTCrPDDwvYQcFwEDk:-MXtNa1e-7avWL8r6jzT:b-bp2ir6) ([raw file](https://github.com/batfish/batfish/blob/dff075ff7580059e499d0c16cf445c134c8cc9a4/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/CommunityAPDispositions.java#L126)):*
<details><summary><i>Previously, millstein (Todd Millstein) wrote…</i></summary><blockquote>

I looked into it, but IntegerSpaces don't support all of the operations I need, like intersection, and they are targeted at sets of contiguous integer ranges, which is not typically what I will have.  So I don't think it would help to switch to that.
</blockquote></details>

Actually Dan pointed out that they do support the operations I need (inherited from NumberSpace).  So I will make this change now...

**Review by millstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6878)* status: 4 of 9 files reviewed, all discussions resolved (waiting on @arifogel)

___
*[projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/CommunityAPDispositions.java, line 126 at r1](https://reviewable.io/reviews/batfish/batfish/6878#-MXrTCrPDDwvYQcFwEDk:-MXtWovg07bZ8ORr1Qns:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/dff075ff7580059e499d0c16cf445c134c8cc9a4/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/CommunityAPDispositions.java#L126)):*
<details><summary><i>Previously, millstein (Todd Millstein) wrote…</i></summary><blockquote>

Actually Dan pointed out that they do support the operations I need (inherited from NumberSpace).  So I will make this change now...
</blockquote></details>

Done.

**Review by arifogel — COMMENTED** [review]
> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6878)* status: all files reviewed, 3 unresolved discussions (waiting on @millstein)

___
*[projects/minesweeper/pom.xml, line 113 at r2](https://reviewable.io/reviews/batfish/batfish/6878#-MY5y31RE44UUQhJ0OpF:-MY5y31RE44UUQhJ0OpG:b-a87b38) ([raw file](https://github.com/batfish/batfish/blob/68fb6d021a12c62445965a55b3d882ca05a043b5/projects/minesweeper/pom.xml#L113)):*
> ```XML
> 
>     <dependency>
>         <groupId>org.parboiled</groupId>
> ```

Remove. See comment below on `checkArgument`.
___
*[projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/CommunityAPDispositions.java, line 110 at r2](https://reviewable.io/reviews/batfish/batfish/6878#-MY5xQYO-elaTD3PoAGm:-MY5xQYO-elaTD3PoAGn:b-5563te) ([raw file](https://github.com/batfish/batfish/blob/68fb6d021a12c62445965a55b3d882ca05a043b5/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/CommunityAPDispositions.java#L110)):*
> ```Java
>   public static CommunityAPDispositions exactly(Set<Integer> aps, BDDRoute bddRoute) {
>     int numAPs = bddRoute.getCommunityAtomicPredicates().length;
>     IntegerSpace mustExist = IntegerSpace.builder().including(Ints.toArray(aps)).build();
> ```

nit: can use `IntegerSpace.includingAll(Iterable<int>)` inherited from `NumberSpace` and skip conversion to array.
___
*[projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/SetCommunitiesVisitor.java, line 3 at r2](https://reviewable.io/reviews/batfish/batfish/6878#-MY5yAd0074hbsSKih2o:-MY5yAd0074hbsSKih2p:b-gxuiqk) ([raw file](https://github.com/batfish/batfish/blob/68fb6d021a12c62445965a55b3d882ca05a043b5/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/SetCommunitiesVisitor.java#L3)):*
> ```Java
> package org.batfish.minesweeper.bdd;
> 
> import static org.parboiled.common.Preconditions.checkArgument;
> ```

Wrong checkArgument. Use the one from google. This is why you have a spurious dependency on parboiled.
If you are using Intellij, you should blacklist `org.parboiled.common.Preconditions` from import suggestions.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6878)* status: all files reviewed, 3 unresolved discussions (waiting on @millstein)

___
*[projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/SetCommunitiesVisitor.java, line 3 at r2](https://reviewable.io/reviews/batfish/batfish/6878#-MY5yAd0074hbsSKih2o:-MY5yqOiEN85hx9HXWv6:b-y8ofps) ([raw file](https://github.com/batfish/batfish/blob/68fb6d021a12c62445965a55b3d882ca05a043b5/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/SetCommunitiesVisitor.java#L3)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Wrong checkArgument. Use the one from google. This is why you have a spurious dependency on parboiled.
If you are using Intellij, you should blacklist `org.parboiled.common.Preconditions` from import suggestions.
</blockquote></details>

Specifically, use `import static com.google.common.base.Preconditions.checkArgument;`

**Review by arifogel — COMMENTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6878)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by arifogel — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6878#-:-MY65z_V4TzRPmn1Ky-r:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
