### PR TITLE
Node properties

### PR DESCRIPTION
**Pull request by ratulm**
I'll fill out the properties and add a few more tests if this seem directionally OK. 

on the example testrig, "get nodeproperties" yields:

```
{
  "class" : "org.batfish.question.nodeproperties.NodePropertiesAnswerElement",
  "metadata" : {
    "columnMetadata" : [
      {
        "description" : "Node",
        "isKey" : true,
        "isValue" : false,
        "name" : "node",
        "schema" : "Node"
      },
      {
        "description" : "Property interfaces",
        "isKey" : false,
        "isValue" : true,
        "name" : "interfaces",
        "schema" : "List<String>"
      },
      {
        "description" : "Property ntpServers",
        "isKey" : false,
        "isValue" : true,
        "name" : "ntpServers",
        "schema" : "List<String>"
      },
      {
        "description" : "Property ntpSourceInterface",
        "isKey" : false,
        "isValue" : true,
        "name" : "ntpSourceInterface",
        "schema" : "Object"
      }
    ],
    "displayHints" : {
      "textDesc" : "Properties of node ${node}."
    }
  },
  "rows" : [
    {
      "node" : {
        "id" : "node-as3border2",
        "name" : "as3border2"
      },
      "interfaces" : [
        "Ethernet0/0",
        "GigabitEthernet0/0",
        "GigabitEthernet1/0",
        "Loopback0"
      ],
      "ntpServers" : [
        "18.18.18.18",
        "23.23.23.23"
      ],
      "ntpSourceInterface" : null
    },
    {
      "node" : {
        "id" : "node-host2",
        "name" : "host2"
      },
      "interfaces" : [
        "eth0"
      ],
      "ntpServers" : [ ],
      "ntpSourceInterface" : null
    },
    {
      "node" : {
        "id" : "node-as3core1",
        "name" : "as3core1"
      },
      "interfaces" : [
        "Ethernet0/0",
        "GigabitEthernet0/0",
        "GigabitEthernet1/0",
        "GigabitEthernet2/0",
        "GigabitEthernet3/0",
        "Loopback0"
      ],
      "ntpServers" : [ ],
      "ntpSourceInterface" : null
    },
    {
      "node" : {
        "id" : "node-host1",
        "name" : "host1"
      },
      "interfaces" : [
        "eth0"
      ],
      "ntpServers" : [ ],
      "ntpSourceInterface" : null
    },
    {
      "node" : {
        "id" : "node-as3border1",
        "name" : "as3border1"
      },
      "interfaces" : [
        "Ethernet0/0",
        "GigabitEthernet0/0",
        "GigabitEthernet1/0",
        "Loopback0"
      ],
      "ntpServers" : [
        "18.18.18.18",
        "23.23.23.23"
      ],
      "ntpSourceInterface" : null
    },
    {
      "node" : {
        "id" : "node-as1core1",
        "name" : "as1core1"
      },
      "interfaces" : [
        "Ethernet0/0",
        "GigabitEthernet0/0",
        "GigabitEthernet1/0",
        "Loopback0"
      ],
      "ntpServers" : [ ],
      "ntpSourceInterface" : null
    },
    {
      "node" : {
        "id" : "node-as1border2",
        "name" : "as1border2"
      },
      "interfaces" : [
        "Ethernet0/0",
        "GigabitEthernet0/0",
        "GigabitEthernet1/0",
        "GigabitEthernet2/0",
        "Loopback0"
      ],
      "ntpServers" : [
        "18.18.18.18",
        "23.23.23.23"
      ],
      "ntpSourceInterface" : null
    },
    {
      "node" : {
        "id" : "node-as2border2",
        "name" : "as2border2"
      },
      "interfaces" : [
        "Ethernet0/0",
        "GigabitEthernet0/0",
        "GigabitEthernet1/0",
        "GigabitEthernet2/0",
        "Loopback0"
      ],
      "ntpServers" : [
        "18.18.18.18"
      ],
      "ntpSourceInterface" : null
    },
    {
      "node" : {
        "id" : "node-as2border1",
        "name" : "as2border1"
      },
      "interfaces" : [
        "Ethernet0/0",
        "GigabitEthernet0/0",
        "GigabitEthernet1/0",
        "GigabitEthernet2/0",
        "Loopback0"
      ],
      "ntpServers" : [
        "18.18.18.18",
        "23.23.23.23"
      ],
      "ntpSourceInterface" : null
    },
    {
      "node" : {
        "id" : "node-as2dist2",
        "name" : "as2dist2"
      },
      "interfaces" : [
        "Ethernet0/0",
        "GigabitEthernet0/0",
        "GigabitEthernet1/0",
        "GigabitEthernet2/0",
        "Loopback0"
      ],
      "ntpServers" : [ ],
      "ntpSourceInterface" : null
    },
    {
      "node" : {
        "id" : "node-as2core1",
        "name" : "as2core1"
      },
      "interfaces" : [
        "Ethernet0/0",
        "GigabitEthernet0/0",
        "GigabitEthernet1/0",
        "GigabitEthernet2/0",
        "GigabitEthernet3/0",
        "Loopback0"
      ],
      "ntpServers" : [ ],
      "ntpSourceInterface" : null
    },
    {
      "node" : {
        "id" : "node-as2core2",
        "name" : "as2core2"
      },
      "interfaces" : [
        "Ethernet0/0",
        "GigabitEthernet0/0",
        "GigabitEthernet1/0",
        "GigabitEthernet2/0",
        "GigabitEthernet3/0",
        "Loopback0"
      ],
      "ntpServers" : [ ],
      "ntpSourceInterface" : null
    },
    {
      "node" : {
        "id" : "node-as1border1",
        "name" : "as1border1"
      },
      "interfaces" : [
        "Ethernet0/0",
        "GigabitEthernet0/0",
        "GigabitEthernet1/0",
        "Loopback0"
      ],
      "ntpServers" : [ ],
      "ntpSourceInterface" : null
    },
    {
      "node" : {
        "id" : "node-as2dept1",
        "name" : "as2dept1"
      },
      "interfaces" : [
        "Ethernet0/0",
        "GigabitEthernet0/0",
        "GigabitEthernet1/0",
        "GigabitEthernet2/0",
        "GigabitEthernet3/0",
        "Loopback0"
      ],
      "ntpServers" : [ ],
      "ntpSourceInterface" : null
    },
    {
      "node" : {
        "id" : "node-as2dist1",
        "name" : "as2dist1"
      },
      "interfaces" : [
        "Ethernet0/0",
        "GigabitEthernet0/0",
        "GigabitEthernet1/0",
        "GigabitEthernet2/0",
        "Loopback0"
      ],
      "ntpServers" : [ ],
      "ntpSourceInterface" : null
    }
  ],
  "summary" : {
    "notes" : "Found 15 results",
    "numFailed" : 0,
    "numPassed" : 0,
    "numResults" : 15
  }
}
```

### CODE REVIEW

**Comment by dhalperi** [comment]
Reviewed 4 of 25 files at r1, 3 of 7 files at r2.
Review status: 7 of 8 files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/Schema.java, line 103 at r3](https://reviewable.io/reviews/batfish/batfish/1395#-LCdsI0m5gMFiV_tVW1F:-LCdsI0m5gMFiV_tVW1G:b-phrjrh) ([raw file](https://github.com/batfish/batfish/blob/e863634123038ada6b5f0c2c804e761d7eb43ead/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/Schema.java#L103)):*
> ```Java
>   @Override
>   public boolean equals(Object o) {
>     if (o == null || !(o instanceof Schema)) {
> ```

`o == null` is redundant  here -- `null instanceof Foo` is always false.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/Schema.java, line 111 at r3](https://reviewable.io/reviews/batfish/batfish/1395#-LCdsPySEZBwwGGqT0--:-LCdsPySEZBwwGGqT0-0:b-mk9rf8) ([raw file](https://github.com/batfish/batfish/blob/e863634123038ada6b5f0c2c804e761d7eb43ead/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/Schema.java#L111)):*
> ```Java
> 
>   /**
>    * Infers the {@link Schema} type from provided value. Turns Sets into Lists. The function will
> ```

any {@link Collection} into a {@link List} ?

I'm generally skeptical of this approach... such type inference is really, really hard.

We tried doing this in Beam and it never really worked right. Especially for empty collections, for example.

If you must, must do this then I'd look into how a good library does it. Jackson must do something when it's serializing arbitrary classes to JSON...

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/Schema.java, line 119 at r3](https://reviewable.io/reviews/batfish/batfish/1395#-LCdtkjUCCTYvusqXhbL:-LCdtkjUCCTYvusqXhbM:butgevw) ([raw file](https://github.com/batfish/batfish/blob/e863634123038ada6b5f0c2c804e761d7eb43ead/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/Schema.java#L119)):*
> ```Java
>    * @throws IllegalStateException if the internal schema alias map is corrupted
>    */
>   public static Schema fromValue(Object value) {
> ```

@Nullable

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/Schema.java, line 179 at r3](https://reviewable.io/reviews/batfish/batfish/1395#-LCdtoBt0XF3zmRpuoO0:-LCdtoBt0XF3zmRpuoO1:b43mxqh) ([raw file](https://github.com/batfish/batfish/blob/e863634123038ada6b5f0c2c804e761d7eb43ead/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/Schema.java#L179)):*
> ```Java
> 
>   public boolean isIntOrIntList() {
>     return _baseType.equals(Integer.class);
> ```

Is it obvious this is the way to go? Why downcast Longs to Ints instead of upcasting Ints to longs? Will we never be able to support large 32-bit / 64-bit numbers?

---

*[projects/question/src/main/java/org/batfish/question/nodeproperties/NodePropertiesAnswerer.java, line 82 at r3](https://reviewable.io/reviews/batfish/batfish/1395#-LCdw1zO2vOd3RzwLBE9:-LCdw1zO2vOd3RzwLBEA:bry3rie) ([raw file](https://github.com/batfish/batfish/blob/e863634123038ada6b5f0c2c804e761d7eb43ead/projects/question/src/main/java/org/batfish/question/nodeproperties/NodePropertiesAnswerer.java#L82)):*
> ```Java
>     if (propertyValue == null
>         || (propertyValue instanceof Collection<?> && ((Collection<?>) propertyValue).isEmpty())) {
>       row.put(columnName, propertyValue);
> ```

It looks like this code dynamically infers the schema from first row on this network, that the inferred types are data dependent, and thus the results are potentially different every time the question is invoked. That's gotta be a non-starter for downstream users -- the schema of the implicit "Nodes" table has to be knowable ahead of time and fixed...

---

*[projects/question/src/main/java/org/batfish/question/nodeproperties/NodePropertySpecifier.java, line 28 at r3](https://reviewable.io/reviews/batfish/batfish/1395#-LCdvXSF5BVTaAdSf_ow:-LCdvXSF5BVTaAdSf_ox:bcvl7ws) ([raw file](https://github.com/batfish/batfish/blob/e863634123038ada6b5f0c2c804e761d7eb43ead/projects/question/src/main/java/org/batfish/question/nodeproperties/NodePropertySpecifier.java#L28)):*
> ```Java
>           .put("authentication-key-chains", Configuration::getAuthenticationKeyChains)
>           .put("canonical-ip", Configuration::getCanonicalIp)
>           .put("community-lists", Configuration::getCommunityLists)
> ```

I would almost certainly put the type here rather than rely on dynamic inference.

---

*[projects/question/src/test/java/org/batfish/question/nodeproperties/NodePropertiesAnswererTest.java, line 25 at r3](https://reviewable.io/reviews/batfish/batfish/1395#-LCdvbyuB0LeF3tjH9Uv:-LCdvbyuB0LeF3tjH9Uw:b-blqyz2) ([raw file](https://github.com/batfish/batfish/blob/e863634123038ada6b5f0c2c804e761d7eb43ead/projects/question/src/test/java/org/batfish/question/nodeproperties/NodePropertiesAnswererTest.java#L25)):*
> ```Java
>   @Test
>   public void answer() {
>     // TODO: write an "end-to-end" test here.
> ```

noting todo

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1395)*

**Comment by dhalperi** [comment]
Reviewed 1 of 25 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1395)*

**Comment by ratulm** [comment]
Review status: 7 of 8 files reviewed at latest revision, 7 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/Schema.java, line 103 at r3](https://reviewable.io/reviews/batfish/batfish/1395#-LCdsI0m5gMFiV_tVW1F:-LCeRY3H8FIpkvEE_07b:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/e863634123038ada6b5f0c2c804e761d7eb43ead/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/Schema.java#L103)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

`o == null` is redundant  here -- `null instanceof Foo` is always false.
</blockquote></details>

Done.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/Schema.java, line 119 at r3](https://reviewable.io/reviews/batfish/batfish/1395#-LCdtkjUCCTYvusqXhbL:-LCeRx_87cRveNbAEGsy:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/e863634123038ada6b5f0c2c804e761d7eb43ead/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/Schema.java#L119)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

@Nullable
</blockquote></details>

Done.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/Schema.java, line 179 at r3](https://reviewable.io/reviews/batfish/batfish/1395#-LCdtoBt0XF3zmRpuoO0:-LCeS4wE8nKQhK4-9cMf:bwwmgvc) ([raw file](https://github.com/batfish/batfish/blob/e863634123038ada6b5f0c2c804e761d7eb43ead/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/Schema.java#L179)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Is it obvious this is the way to go? Why downcast Longs to Ints instead of upcasting Ints to longs? Will we never be able to support large 32-bit / 64-bit numbers?
</blockquote></details>

I was thinking that we should just add the Long schema if/when we need to. Maintaining one-to-one mapping simplifies a lot of things. 

---

*[projects/question/src/main/java/org/batfish/question/nodeproperties/NodePropertiesAnswerer.java, line 82 at r3](https://reviewable.io/reviews/batfish/batfish/1395#-LCdw1zO2vOd3RzwLBE9:-LCeSz6v2pMDnPrpRIVk:blhfoq7) ([raw file](https://github.com/batfish/batfish/blob/e863634123038ada6b5f0c2c804e761d7eb43ead/projects/question/src/main/java/org/batfish/question/nodeproperties/NodePropertiesAnswerer.java#L82)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

It looks like this code dynamically infers the schema from first row on this network, that the inferred types are data dependent, and thus the results are potentially different every time the question is invoked. That's gotta be a non-starter for downstream users -- the schema of the implicit "Nodes" table has to be knowable ahead of time and fixed...
</blockquote></details>

If the code is working as expected, downstream users will see only one of two things: Schema.Object if the column has no values or a non-Object Schema. 

I did this to keep the JAVA_MAP easier to maintain. The alternative is to throw an explicit Schema in that map. Is that a better way to go? Other alternatives?

---

*[projects/question/src/main/java/org/batfish/question/nodeproperties/NodePropertySpecifier.java, line 28 at r3](https://reviewable.io/reviews/batfish/batfish/1395#-LCdvXSF5BVTaAdSf_ow:-LCeUM774wxCZTXodq_a:buq883z) ([raw file](https://github.com/batfish/batfish/blob/e863634123038ada6b5f0c2c804e761d7eb43ead/projects/question/src/main/java/org/batfish/question/nodeproperties/NodePropertySpecifier.java#L28)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I would almost certainly put the type here rather than rely on dynamic inference.
</blockquote></details>

Oh, I see this now. Will do. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1395)*

**Comment by dhalperi** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1395)*

**Comment by ratulm** [comment]
Review status: 2 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/Schema.java, line 111 at r3](https://reviewable.io/reviews/batfish/batfish/1395#-LCdsPySEZBwwGGqT0--:-LCf3aA8A_FzDR-YX6vG:b-ypps1m) ([raw file](https://github.com/batfish/batfish/blob/e863634123038ada6b5f0c2c804e761d7eb43ead/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/Schema.java#L111)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

any {@link Collection} into a {@link List} ?

I'm generally skeptical of this approach... such type inference is really, really hard.

We tried doing this in Beam and it never really worked right. Especially for empty collections, for example.

If you must, must do this then I'd look into how a good library does it. Jackson must do something when it's serializing arbitrary classes to JSON...
</blockquote></details>

this and fillProperty stuff was such beautiful intelligence. all gone now :(

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1395)*

**Comment by dhalperi** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1395#-:-LCgGwBc-_CMztjxv1ij:bnfp4nl)*

**Pull request merged**
