### PR TITLE
HeaderSpace: use immutable structures internally

### PR DESCRIPTION
**Pull request by dhalperi**
It looks we're spending an obscene amount of memory in empty `TreeSet` and `ArrayList` classes in `HeaderSpace`-related classes.

There are a few good ways to move forward:

1. Allow `null` for empty collections. Callers should wrap `getX` with null-checks. When they want to add an item to a set, they have to initialize.
    * IMO this is an unfortunate amount of work for the caller.

1. Switch to empty/immutable collections internally. These are generally (much) more memory-efficient. Empty collections are in fact singletons Java-wide; and if we use the Guava classes, we'll likely save some copies when structures are copied/used in multiple places.
    * we can copy-on-set, which also means we could relax the `setX` contract to accept un-sorted sets or even arbitrary collections.
    * Callers only need to write annoying code where they used to modify the result of a getter: i.e.around `getX().add(x)` -> `setX(...make a new collection containing getX and x)`.
    * we could add `addX` forms that are internally equivalent to the above, but callers may have smarter logic (e.g., most of these are in the same function that allocates the interface)

I opted to go with the second.

---
This change is [Reviewable](https://reviewable.io/reviews/batfish/batfish/780)

### CODE REVIEW

**Comment by dhalperi** [comment]
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java, line 378 at r1](https://reviewable.io:443/reviews/batfish/batfish/780#-L0hZc1R7P8VJgGgOUcx:-L0hZc1R7P8VJgGgOUcy:b-90kz33) ([raw file](https://github.com/batfish/batfish/blob/c94cd1df8ad1592617e404cb9fa51f2ef305c068/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java#L378)):*
> ```Java
>   private List<SubRange> _allowedVlans;
> 
>   private SortedSet<Prefix> _allPrefixes;
> ```

Changed this to `Sorted` since it was initialized as a `TreeSet` and the refs broke otherwise.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/780)*

**Comment by dhalperi** [comment]
Review status: 0 of 35 files reviewed at latest revision, 3 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromDestinationPrefixList.java, line 45 at r1](https://reviewable.io:443/reviews/batfish/batfish/780#-L0h_EXqUxW90fA0FQoI:-L0h_EXqUxW90fA0FQoJ:b-szm1qv) ([raw file](https://github.com/batfish/batfish/blob/c94cd1df8ad1592617e404cb9fa51f2ef305c068/projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromDestinationPrefixList.java#L45)):*
> ```Java
>                     } else {
>                       return new IpWildcard(rfLine.getPrefix());
>                     }
> ```

could add a helper getter to `RouteFilterList` to take over these ~10 lines of code, if useful. Used in 4 or 5 `FwFrom` rules.

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromFragmentOffset.java, line 28 at r1](https://reviewable.io:443/reviews/batfish/batfish/780#-L0haZwKDLNK6hd4B6A4:-L0haZwKDLNK6hd4B6A5:bflmsnv) ([raw file](https://github.com/batfish/batfish/blob/c94cd1df8ad1592617e404cb9fa51f2ef305c068/projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromFragmentOffset.java#L28)):*
> ```Java
>     Set<SubRange> offsets = Collections.singleton(_offsetRange);
>     if (_except) {
>       line.setNotFragmentOffsets(offsets);
> ```

this was a `set`, not an `add`, so I kept it that way. Just noting the difference.

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java, line 1210 at r1](https://reviewable.io:443/reviews/batfish/batfish/780#-L0haLWSeXaOpDl4Ar7E:-L0haLWT1w2H-t2pI-sc:b-qy08q6) ([raw file](https://github.com/batfish/batfish/blob/c94cd1df8ad1592617e404cb9fa51f2ef305c068/projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java#L1210)):*
> ```Java
>       newIface.setPrefix(iface.getPrimaryPrefix());
>     }
>     newIface.setAllPrefixes(iface.getAllPrefixes());
> ```

does this not need the primary prefix? Cisco includes it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/780)*

**Comment by dhalperi** [comment]
*[projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java, line 1210 at r1](https://reviewable.io:443/reviews/batfish/batfish/780#-L0haLWSeXaOpDl4Ar7E:-L0hajennGx8nhq6hqXG:bm6a41t) ([raw file](https://github.com/batfish/batfish/blob/c94cd1df8ad1592617e404cb9fa51f2ef305c068/projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java#L1210)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

does this not need the primary prefix? Cisco includes it.
</blockquote></details>

(maybe it's already there, tho. to be investigated)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/780)*

**Comment by arifogel** [comment]
Reviewed 35 of 35 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java, line 378 at r1](https://reviewable.io:443/reviews/batfish/batfish/780#-L0hZc1R7P8VJgGgOUcx:-L0k84tXUYJ33yP8wjCq:b-up4ms1) ([raw file](https://github.com/batfish/batfish/blob/c94cd1df8ad1592617e404cb9fa51f2ef305c068/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java#L378)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Changed this to `Sorted` since it was initialized as a `TreeSet` and the refs broke otherwise.
</blockquote></details>

Hmm somewhere we might need to remember order of secondary ips/prefixes, but this is fine for now.

---

*[projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/NetworkAcl.java, line 95 at r1](https://reviewable.io:443/reviews/batfish/batfish/780#-L0k8vvTTr489wGsR1bh:-L0k8vvUxVNtZQp9al9t:b77e2s9) ([raw file](https://github.com/batfish/batfish/blob/c94cd1df8ad1592617e404cb9fa51f2ef305c068/projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/NetworkAcl.java#L95)):*
> ```Java
>       }
>     }
>     List<IpAccessListLine> lines = new ArrayList<>(lineMap.values());
> ```

Can we use `ImmutableList` here?

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromDestinationPrefixList.java, line 45 at r1](https://reviewable.io:443/reviews/batfish/batfish/780#-L0h_EXqUxW90fA0FQoI:-L0kAOfvNzcCkcz6XvQm:b-zgyzqt) ([raw file](https://github.com/batfish/batfish/blob/c94cd1df8ad1592617e404cb9fa51f2ef305c068/projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromDestinationPrefixList.java#L45)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

could add a helper getter to `RouteFilterList` to take over these ~10 lines of code, if useful. Used in 4 or 5 `FwFrom` rules.
</blockquote></details>

As long as it's well-tested, sure.

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromFragmentOffset.java, line 28 at r1](https://reviewable.io:443/reviews/batfish/batfish/780#-L0haZwKDLNK6hd4B6A4:-L0kAf8kFxjYyUkhaU2Y:blh82b4) ([raw file](https://github.com/batfish/batfish/blob/c94cd1df8ad1592617e404cb9fa51f2ef305c068/projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromFragmentOffset.java#L28)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

this was a `set`, not an `add`, so I kept it that way. Just noting the difference.
</blockquote></details>

Actually most of the places you did concatenation would be fine as `set`, since there is no other place stuff could be added. I don't see it being a particularly important issue at the moment since there is no behavior change.

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java, line 1210 at r1](https://reviewable.io:443/reviews/batfish/batfish/780#-L0haLWSeXaOpDl4Ar7E:-L0kC2yyHK6MCYS-FuZ7:b-24p2sp) ([raw file](https://github.com/batfish/batfish/blob/c94cd1df8ad1592617e404cb9fa51f2ef305c068/projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java#L1210)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

(maybe it's already there, tho. to be investigated)
</blockquote></details>

I think it was already there, unlike Cisco.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/780)*

**Comment by dhalperi** [comment]
*[projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java, line 1210 at r1](https://reviewable.io:443/reviews/batfish/batfish/780#-L0haLWSeXaOpDl4Ar7E:-L0kLRU0rmfozaDrZUsT:b-gl4x9o) ([raw file](https://github.com/batfish/batfish/blob/c94cd1df8ad1592617e404cb9fa51f2ef305c068/projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java#L1210)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

I think it was already there, unlike Cisco.
</blockquote></details>

Yes, it was already there. Found in `enterIfi_address` in ConfigurationBuilder.java

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/780)*

**Comment by dhalperi** [comment]
Review status: 28 of 38 files reviewed at latest revision, 4 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/NetworkAcl.java, line 95 at r1](https://reviewable.io:443/reviews/batfish/batfish/780#-L0k8vvTTr489wGsR1bh:-L0kH19teIKyp6cRg6x9:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/c94cd1df8ad1592617e404cb9fa51f2ef305c068/projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/NetworkAcl.java#L95)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Can we use `ImmutableList` here?
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromDestinationPrefixList.java, line 45 at r1](https://reviewable.io:443/reviews/batfish/batfish/780#-L0h_EXqUxW90fA0FQoI:-L0kKteBna1PU_tEUxnn:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/c94cd1df8ad1592617e404cb9fa51f2ef305c068/projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromDestinationPrefixList.java#L45)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

As long as it's well-tested, sure.
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromFragmentOffset.java, line 28 at r1](https://reviewable.io:443/reviews/batfish/batfish/780#-L0haZwKDLNK6hd4B6A4:-L0kKxBFT9YNn5597lq3:bb6sh2i) ([raw file](https://github.com/batfish/batfish/blob/c94cd1df8ad1592617e404cb9fa51f2ef305c068/projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromFragmentOffset.java#L28)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Actually most of the places you did concatenation would be fine as `set`, since there is no other place stuff could be added. I don't see it being a particularly important issue at the moment since there is no behavior change.
</blockquote></details>

Ack.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/780)*

**Comment by arifogel** [comment]
Reviewed 9 of 9 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 3265 at r2](https://reviewable.io:443/reviews/batfish/batfish/780#-L0kbMxcOCQ9unZfoflM:-L0kbMxdpn_MpqlzFNjY:b-sur0js) ([raw file](https://github.com/batfish/batfish/blob/ad819a726b088adf4665fcf4f730067a21ad24f5/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L3265)):*
> ```Java
>     for (ExtendedAccessListLine fromLine : eaList.getLines()) {
>       RouteFilterLine newLine = toRouteFilterLine(fromLine);
>       newList.addLine(newLine);
> ```

I think this would be much more efficient without calls to `addLine`. That is, just build up the list and set the lines once. We know it's safe because the `RouteFilterList` is created here.

---

*[projects/batfish/src/main/java/org/batfish/representation/vyos/VyosConfiguration.java, line 324 at r2](https://reviewable.io:443/reviews/batfish/batfish/780#-L0kc-oFHVv4A7Wd40yF:-L0kc-oFHVv4A7Wd40yG:bpfrkhy) ([raw file](https://github.com/batfish/batfish/blob/ad819a726b088adf4665fcf4f730067a21ad24f5/projects/batfish/src/main/java/org/batfish/representation/vyos/VyosConfiguration.java#L324)):*
> ```Java
>       RouteFilterLine newLine =
>           new RouteFilterLine(rule.getAction(), rule.getPrefix(), rule.getLengthRange());
>       newList.addLine(newLine);
> ```

We should avoid using `addLine` here and just set the list. If this and my other mention are the only places that function is used, I think we should remove it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/780)*

**Comment by dhalperi** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 3265 at r2](https://reviewable.io:443/reviews/batfish/batfish/780#-L0kbMxcOCQ9unZfoflM:-L0keKQJoQUreUZYSOPE:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/ad819a726b088adf4665fcf4f730067a21ad24f5/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L3265)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

I think this would be much more efficient without calls to `addLine`. That is, just build up the list and set the lines once. We know it's safe because the `RouteFilterList` is created here.
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/representation/vyos/VyosConfiguration.java, line 324 at r2](https://reviewable.io:443/reviews/batfish/batfish/780#-L0kc-oFHVv4A7Wd40yF:-L0keKuifnQPqqnKMOoe:bt2r55r) ([raw file](https://github.com/batfish/batfish/blob/ad819a726b088adf4665fcf4f730067a21ad24f5/projects/batfish/src/main/java/org/batfish/representation/vyos/VyosConfiguration.java#L324)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

We should avoid using `addLine` here and just set the list. If this and my other mention are the only places that function is used, I think we should remove it.
</blockquote></details>

Done.

The function is used in 15 other places, not touched here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/780)*

**Comment by arifogel** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/780#-:-L0lweVVJ79Ls8wLIIUN:bnfp4nl)*

**Pull request merged**
