### PR TITLE
small outlier detection bug fixes / updates

### PR DESCRIPTION
**Pull request by millstein**
Bug fixes in equals and comparesTo methods of outlier sets; changed a nullable field to use the Optional type; added support from Jackson for serializing Optionals properly.

---
This change is [Reviewable](https://reviewable.io/reviews/batfish/batfish/818)

### CODE REVIEW

**Comment by dhalperi** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/collections/AbstractOutlierSet.java, line 27 at r1](https://reviewable.io:443/reviews/batfish/batfish/818#-L21muDMFlwMOKuAikVo:-L21muDMFlwMOKuAikVp:boozqk9) ([raw file](https://github.com/batfish/batfish/blob/82ea2a23a597cf75389719423f54364de42e8375/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/collections/AbstractOutlierSet.java#L27)):*
> ```Java
> 
>   /** An optional role that all of the conformers and outliers play in the network * */
>   private Optional<String> _role;
> ```

Entirely up to you, but my understanding of `Optional` is that it's intended for use only in API return types rather than data model storage. So we'd store it / set it as a `@Nullable`, but create the `Optional` in the getter only.

[if you did this, `Optional.equals(Object)` could be replaced with `Objects.equals(a, b)` which handles nulls gracefully.]

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/collections/NamedStructureOutlierSet.java, line 60 at r1](https://reviewable.io:443/reviews/batfish/batfish/818#-L21nMVcREQposLr7fMX:-L21nMVcREQposLr7fMY:bvi9azt) ([raw file](https://github.com/batfish/batfish/blob/82ea2a23a597cf75389719423f54364de42e8375/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/collections/NamedStructureOutlierSet.java#L60)):*
> ```Java
>   @Override
>   public int compareTo(NamedStructureOutlierSet<T> other) {
>     int superScore = super.compareTo(other);
> ```

is there a simple test that would catch the previous bug? Seeing as how none of the refs changed, hard for me to tell what's being fixed :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/818)*

**Comment by dhalperi** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/818)*

**Comment by millstein** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/collections/AbstractOutlierSet.java, line 27 at r1](https://reviewable.io:443/reviews/batfish/batfish/818#-L21muDMFlwMOKuAikVo:-L22OCdWhSXoqqmP___o:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/82ea2a23a597cf75389719423f54364de42e8375/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/collections/AbstractOutlierSet.java#L27)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Entirely up to you, but my understanding of `Optional` is that it's intended for use only in API return types rather than data model storage. So we'd store it / set it as a `@Nullable`, but create the `Optional` in the getter only.

[if you did this, `Optional.equals(Object)` could be replaced with `Objects.equals(a, b)` which handles nulls gracefully.]
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/818)*

**Comment by millstein** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/collections/NamedStructureOutlierSet.java, line 60 at r1](https://reviewable.io:443/reviews/batfish/batfish/818#-L21nMVcREQposLr7fMX:-L22OIMPODnvySCoiZQI:b-sx64sp) ([raw file](https://github.com/batfish/batfish/blob/82ea2a23a597cf75389719423f54364de42e8375/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/collections/NamedStructureOutlierSet.java#L60)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

is there a simple test that would catch the previous bug? Seeing as how none of the refs changed, hard for me to tell what's being fixed :)
</blockquote></details>

It wasn't a bug per se, but rather that I was testing the various fields in a different order than I decided made sense.  I also refactored things to remove code duplication.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/818)*

**Comment by dhalperi** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/818#-:-L22P5s2j5WTRrBq7qe_:bnfp4nl)*

**Pull request merged**
