### PR TITLE
VI Interfaces: store `IpAccessList` names instead of references

### PR DESCRIPTION
**Pull request by sfraint**
After this PR, interfaces' `IpAccessList`s must exist in their owner `Configuration` (this should already be the case, except in some tests that had to be updated in this PR).

This means that we can now, e.g. overwrite `IpAccessList`s during `finalizeConfiguration` and the updated ACL would take effect as desired.

### CODE REVIEW

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8375)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @dhalperi, @ratulm, and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/8375#-N4mO1kF2Mdd39qW69IM:-N4mO1kG8-iMZCzNGXs_:b-liwvpn) (no related file):*
I'll merge this myself

___

**Review by dhalperi — COMMENTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8375)* status: all files reviewed, 3 unresolved discussions (waiting on @ratulm and @sfraint)

___
*[`projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConversions.java` line 457 at r1](https://reviewable.io/reviews/batfish/batfish/8375#-N4mO8JREqGaSOPycALK:-N4mO8JREqGaSOPycALL:bj4eotq) ([raw file](https://github.com/batfish/batfish/blob/38b269edd9119b26ef199adbc9d02863340dc43f/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConversions.java#L457)):*
> ```Java
>           w.redFlag(
>               String.format(
>                   "Port '%s' referenced in ACL_TABLE '%s' does not exist.", port, aclName));
> ```

how does `aclName` relate to `ipAccessList.getName()`? Are they both needed?



_Code quote:_
```Java
aclName
```
___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java` line 2224 at r1](https://reviewable.io/reviews/batfish/batfish/8375#-N4mOrS18vyJ1ctYN-pT:-N4mOrS18vyJ1ctYN-pU:bxi56yt) ([raw file](https://github.com/batfish/batfish/blob/38b269edd9119b26ef199adbc9d02863340dc43f/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java#L2224)):*
> ```Java
>   @Nullable
>   private IpAccessList getIpAccessList(@Nullable String name) {
>     return _owner == null || name == null ? null : _owner.getIpAccessLists().get(name);
> ```

I'd probably `checkNotNull` the last part?

**Review by dhalperi — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8375)* status: all files reviewed, 1 unresolved discussion (waiting on @ratulm and @sfraint)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8375)* status: all files reviewed, 1 unresolved discussion (waiting on @ratulm and @sfraint)

**Pull request merged**
