### PR TITLE
fixes and improvements to oscillation debugging

### PR DESCRIPTION
**Pull request by arifogel**
- Ensure we always have enough recorded information to report or recover during oscillation handling
- Include information about oscillating prefixes in oscillation exception message

---
This change is [Reviewable](https://reviewable.io/reviews/batfish/batfish/660)

### CODE REVIEW

**Comment by dhalperi** [comment]
Please add tests. Off the top of my head: answer element contains oscillating prefixes, does not contain non-oscillating prefixes, still works when there's no oscillation at all.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/660#-:-KyXBGCeihLHOYczEGAH:b6ra8bk)*

**Comment by arifogel** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[a discussion](https://reviewable.io:443/reviews/batfish/batfish/660#-Kz_OR7riFrB-4JMjADw:-Kz_OR7sqf-mt6JY9JM0:bd8tp1v) (no related file):*
Need to add tests. Adding this comment to ensure this PR has at least one unresolved item.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/660)*

**Comment by arifogel** [comment]
Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io:443/reviews/batfish/batfish/660#-Kz_OR7riFrB-4JMjADw:-L-sO1bahHQa2Abc7EEY:bp88ak) (no related file):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Need to add tests. Adding this comment to ensure this PR has at least one unresolved item.
</blockquote></details>

I added tests, resolved conflicts.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/660)*

**Comment by dhalperi** [comment]
Reviewed 2 of 4 files at r2.
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[projects/batfish/src/test/java/org/batfish/bdp/BdpDataPlanePluginTest.java, line 402 at r2](https://reviewable.io:443/reviews/batfish/batfish/660#-L-z2jO1c_Pty-yFfkC-:-L-z2jO1c_Pty-yFfkC0:b-x4uk2y) ([raw file](https://github.com/batfish/batfish/blob/e4747f22fe6e2d9c5f908f97ba6bdc89e4934957/projects/batfish/src/test/java/org/batfish/bdp/BdpDataPlanePluginTest.java#L402)):*
> ```Java
>     _thrown.expect(
>         allOf(
>             ImmutableList.of(
> ```

You don't need to construct a list to use `allOf` -- it has a vargs form.

---

*[projects/batfish/src/test/java/org/batfish/bdp/BdpDataPlanePluginTest.java, line 439 at r2](https://reviewable.io:443/reviews/batfish/batfish/660#-L-z3CREi03xGgKgg_nE:-L-z3CREi03xGgKgg_nF:b-ev6nhn) ([raw file](https://github.com/batfish/batfish/blob/e4747f22fe6e2d9c5f908f97ba6bdc89e4934957/projects/batfish/src/test/java/org/batfish/bdp/BdpDataPlanePluginTest.java#L439)):*
> ```Java
>                 isA(BdpOscillationException.class),
>                 hasMessage(not(containsString("Changed routes (iteration 2 ==> 3)"))))));
>     testBgpOscillationRecovery(settings);
> ```

I'm not sure what these tests are for -- seems almost identical in setup, but actually identical in assertions. to the couple above. Shouldn't there be different assertions?

---

*[projects/batfish/src/test/java/org/batfish/bdp/BdpDataPlanePluginTest.java, line 463 at r2](https://reviewable.io:443/reviews/batfish/batfish/660#-L-z3rWQjHPNlrKDEAdR:-L-z3rWQjHPNlrKDEAdS:b-8wpxx2) ([raw file](https://github.com/batfish/batfish/blob/e4747f22fe6e2d9c5f908f97ba6bdc89e4934957/projects/batfish/src/test/java/org/batfish/bdp/BdpDataPlanePluginTest.java#L463)):*
> ```Java
>     settings.setBdpRecordAllIterations(false);
>     testBgpOscillationRecovery(settings);
>   }
> ```

add assertions?

---

*[projects/batfish/src/test/java/org/batfish/bdp/BdpOscillationExceptionMatchers.java, line 7 at r2](https://reviewable.io:443/reviews/batfish/batfish/660#-L-z3y-qqeZyFRsN6tD9:-L-z3y-qqeZyFRsN6tDA:bmi850n) ([raw file](https://github.com/batfish/batfish/blob/e4747f22fe6e2d9c5f908f97ba6bdc89e4934957/projects/batfish/src/test/java/org/batfish/bdp/BdpOscillationExceptionMatchers.java#L7)):*
> ```Java
> import org.hamcrest.Matcher;
> 
> public class BdpOscillationExceptionMatchers {
> ```

inline this in the file with the tests it's used for.

We can always extract it later if it's something we want to reuse.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/660)*

**Comment by dhalperi** [comment]
Reviewed 1 of 4 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/660)*

**Comment by arifogel** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[projects/batfish/src/test/java/org/batfish/bdp/BdpDataPlanePluginTest.java, line 402 at r2](https://reviewable.io:443/reviews/batfish/batfish/660#-L-z2jO1c_Pty-yFfkC-:-L0B03zBnpYDSO7oJ3VL:b-smmo3i) ([raw file](https://github.com/batfish/batfish/blob/e4747f22fe6e2d9c5f908f97ba6bdc89e4934957/projects/batfish/src/test/java/org/batfish/bdp/BdpDataPlanePluginTest.java#L402)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

You don't need to construct a list to use `allOf` -- it has a vargs form.
</blockquote></details>

I tried it, but got a warning about constructing an array of generics. I'm not convinced it can be done in a type safe manner that gets the ide, compiler, and our linting tools to shut up.

---

*[projects/batfish/src/test/java/org/batfish/bdp/BdpDataPlanePluginTest.java, line 439 at r2](https://reviewable.io:443/reviews/batfish/batfish/660#-L-z3CREi03xGgKgg_nE:-L0B4I4iypItmvvHzFwH:btiyrw6) ([raw file](https://github.com/batfish/batfish/blob/e4747f22fe6e2d9c5f908f97ba6bdc89e4934957/projects/batfish/src/test/java/org/batfish/bdp/BdpDataPlanePluginTest.java#L439)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I'm not sure what these tests are for -- seems almost identical in setup, but actually identical in assertions. to the couple above. Shouldn't there be different assertions?
</blockquote></details>

I added clarifying comments.

---

*[projects/batfish/src/test/java/org/batfish/bdp/BdpDataPlanePluginTest.java, line 463 at r2](https://reviewable.io:443/reviews/batfish/batfish/660#-L-z3rWQjHPNlrKDEAdR:-L0B4C0uY3CFK4YqFvxB:b6i1xrd) ([raw file](https://github.com/batfish/batfish/blob/e4747f22fe6e2d9c5f908f97ba6bdc89e4934957/projects/batfish/src/test/java/org/batfish/bdp/BdpDataPlanePluginTest.java#L463)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

add assertions?
</blockquote></details>

Assertions are already there. I added clarifying comments.

---

*[projects/batfish/src/test/java/org/batfish/bdp/BdpOscillationExceptionMatchers.java, line 7 at r2](https://reviewable.io:443/reviews/batfish/batfish/660#-L-z3y-qqeZyFRsN6tD9:-L0B4Gco66ZPYQMoKyCV:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/e4747f22fe6e2d9c5f908f97ba6bdc89e4934957/projects/batfish/src/test/java/org/batfish/bdp/BdpOscillationExceptionMatchers.java#L7)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

inline this in the file with the tests it's used for.

We can always extract it later if it's something we want to reuse.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/660)*

**Comment by dhalperi** [comment]
*[projects/batfish/src/test/java/org/batfish/bdp/BdpDataPlanePluginTest.java, line 402 at r2](https://reviewable.io:443/reviews/batfish/batfish/660#-L-z2jO1c_Pty-yFfkC-:-L0BBeReyeW2e8cUzFW_:b-rztlow) ([raw file](https://github.com/batfish/batfish/blob/e4747f22fe6e2d9c5f908f97ba6bdc89e4934957/projects/batfish/src/test/java/org/batfish/bdp/BdpDataPlanePluginTest.java#L402)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

I tried it, but got a warning about constructing an array of generics. I'm not convinced it can be done in a type safe manner that gets the ide, compiler, and our linting tools to shut up.
</blockquote></details>

Hmm, I don't see any warnings with javac. Eclipse's type inference still can't handle this? *sigh*

Probably `Matchers.<BdpOscillationException>allOf` would work, but up to you.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/660)*

**Comment by dhalperi** [comment]
Reviewed 1 of 2 files at r3.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/660)*

**Comment by dhalperi** [comment]
Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/660)*

**Comment by arifogel** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/test/java/org/batfish/bdp/BdpDataPlanePluginTest.java, line 402 at r2](https://reviewable.io:443/reviews/batfish/batfish/660#-L-z2jO1c_Pty-yFfkC-:-L0BI1-rnn0QZi67owxd:b9nc70b) ([raw file](https://github.com/batfish/batfish/blob/e4747f22fe6e2d9c5f908f97ba6bdc89e4934957/projects/batfish/src/test/java/org/batfish/bdp/BdpDataPlanePluginTest.java#L402)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Hmm, I don't see any warnings with javac. Eclipse's type inference still can't handle this? *sigh*

Probably `Matchers.<BdpOscillationException>allOf` would work, but up to you.
</blockquote></details>

It works now. Weird.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/660)*

**Comment by dhalperi** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/660#-:-L0BOu2QMKre-2PDN_Ii:bnfp4nl)*

**Pull request merged**
