### PR TITLE
Jsonpath cleanup for better downstream usage

### PR DESCRIPTION
**Pull request by ratulm**

### CODE REVIEW

**Comment by dhalperi** [comment]
:lgtm: nice cleanup. minor comments.

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/Row.java, line 129 at r1](https://reviewable.io/reviews/batfish/batfish/1363#-LC7-nSTDbW9nCmfVQmA:-LC7-nSTDbW9nCmfVQmB:b-1z8gl) ([raw file](https://github.com/batfish/batfish/blob/9f5bc0185f5081d528862f0cd18357a509c388ff/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/Row.java#L129)):*
> ```Java
>       }
>     }
>     return key.toString();
> ```

add (JUnit) tests for each of these functions.

1. they should be tested, and
2. tests enable reviewer can see what kinds of keys are produced.

It currently looks like it's simply concatenating strings without separators and might not produce unique keys.

---

*[projects/question/src/main/java/org/batfish/question/jsonpathtotable/JsonPathToTableColumn.java, line 9 at r1](https://reviewable.io/reviews/batfish/batfish/1363#-LC7-OMT4SFD8u249sET:-LC7-OMT4SFD8u249sEU:b-611s7o) ([raw file](https://github.com/batfish/batfish/blob/9f5bc0185f5081d528862f0cd18357a509c388ff/projects/question/src/main/java/org/batfish/question/jsonpathtotable/JsonPathToTableColumn.java#L9)):*
> ```Java
> import org.batfish.datamodel.answers.Schema;
> 
> public abstract class JsonPathToTableColumn {
> ```

suggest annotating class with `@ParametersAreNonnullByDefault` and then annotating all `!Nullable` parameters.

See https://github.com/batfish/batfish/blob/nxos-continued/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoNxConversions.java#L52 for an example.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1363#-:-LC70Ifp1CuHqxAohKza:bjdpkr1)*

**Comment by ratulm** [comment]
Review status: 11 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/Row.java, line 129 at r1](https://reviewable.io/reviews/batfish/batfish/1363#-LC7-nSTDbW9nCmfVQmA:-LC7MCVDC7PFi0AuT1u0:b-s1u208) ([raw file](https://github.com/batfish/batfish/blob/9f5bc0185f5081d528862f0cd18357a509c388ff/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/Row.java#L129)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

add (JUnit) tests for each of these functions.

1. they should be tested, and
2. tests enable reviewer can see what kinds of keys are produced.

It currently looks like it's simply concatenating strings without separators and might not produce unique keys.
</blockquote></details>

Done. The quoting of strings in JsonNode's toString() is automatically adding separators. 

---

*[projects/question/src/main/java/org/batfish/question/jsonpathtotable/JsonPathToTableColumn.java, line 9 at r1](https://reviewable.io/reviews/batfish/batfish/1363#-LC7-OMT4SFD8u249sET:-LC7NNh_EVPWJ8E58_YD:bs7wumx) ([raw file](https://github.com/batfish/batfish/blob/9f5bc0185f5081d528862f0cd18357a509c388ff/projects/question/src/main/java/org/batfish/question/jsonpathtotable/JsonPathToTableColumn.java#L9)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

suggest annotating class with `@ParametersAreNonnullByDefault` and then annotating all `!Nullable` parameters.

See https://github.com/batfish/batfish/blob/nxos-continued/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoNxConversions.java#L52 for an example.
</blockquote></details>

Done. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1363)*

**Comment by dhalperi** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/table/RowTest.java, line 55 at r2](https://reviewable.io/reviews/batfish/batfish/1363#-LC7VLOR8KWn1JP6cNnc:-LC7VLOS3cxAl5Qo5LNz:bhlrsl0) ([raw file](https://github.com/batfish/batfish/blob/1873bb2352bbb48a9442da3266967ba0317d8cd8/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/table/RowTest.java#L55)):*
> ```Java
>     assertThat(row.getValue(metadataNoValues), equalTo(""));
>     assertThat(row.getValue(metadataOneValue), equalTo("\"value2\""));
>     assertThat(row.getValue(metadataTwoValues), equalTo("\"value1\"\"value3\""));
> ```

are these keys user-visible in any way?  -- will they appear in any output, log message, etc? If so, I'd make them readable. Maybe `("value1","value2","value3")`?

---

*[projects/question/src/main/java/org/batfish/question/jsonpathtotable/JsonPathToTableAnswerElement.java, line 33 at r2](https://reviewable.io/reviews/batfish/batfish/1363#-LC7VuBLBZYZtIu8NT9p:-LC7VuBLBZYZtIu8NT9q:b-sjw9j9) ([raw file](https://github.com/batfish/batfish/blob/1873bb2352bbb48a9442da3266967ba0317d8cd8/projects/question/src/main/java/org/batfish/question/jsonpathtotable/JsonPathToTableAnswerElement.java#L33)):*
> ```Java
> 
>   public static TableMetadata create(JsonPathToTableQuestion question) {
>     Map<String, ColumnMetadata> columnMetadataMap = new HashMap<>();
> ```

Does this need to be a multimap?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1363)*

**Comment by ratulm** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/table/RowTest.java, line 55 at r2](https://reviewable.io/reviews/batfish/batfish/1363#-LC7VLOR8KWn1JP6cNnc:-LC7WGqt9ok4TIGdXDvX:b-4uxkd) ([raw file](https://github.com/batfish/batfish/blob/1873bb2352bbb48a9442da3266967ba0317d8cd8/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/table/RowTest.java#L55)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

are these keys user-visible in any way?  -- will they appear in any output, log message, etc? If so, I'd make them readable. Maybe `("value1","value2","value3")`?
</blockquote></details>

not user-visible (at least at the moment). i added explicit separators so things are clearer. 

---

*[projects/question/src/main/java/org/batfish/question/jsonpathtotable/JsonPathToTableAnswerElement.java, line 33 at r2](https://reviewable.io/reviews/batfish/batfish/1363#-LC7VuBLBZYZtIu8NT9p:-LC7WURo5nBHLkqg3mSq:b-8yboul) ([raw file](https://github.com/batfish/batfish/blob/1873bb2352bbb48a9442da3266967ba0317d8cd8/projects/question/src/main/java/org/batfish/question/jsonpathtotable/JsonPathToTableAnswerElement.java#L33)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Does this need to be a multimap?
</blockquote></details>

no. (why?)

(down the line, i think i might columnMetadata to a list instead of a map (to preserve ordering), but your issue is different i think.)

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1363)*

**Comment by dhalperi** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/question/src/main/java/org/batfish/question/jsonpathtotable/JsonPathToTableAnswerElement.java, line 33 at r2](https://reviewable.io/reviews/batfish/batfish/1363#-LC7VuBLBZYZtIu8NT9p:-LC7_5e-8ZVEAYhZ_-Wd:bguwtep) ([raw file](https://github.com/batfish/batfish/blob/1873bb2352bbb48a9442da3266967ba0317d8cd8/projects/question/src/main/java/org/batfish/question/jsonpathtotable/JsonPathToTableAnswerElement.java#L33)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

no. (why?)

(down the line, i think i might columnMetadata to a list instead of a map (to preserve ordering), but your issue is different i think.)
</blockquote></details>

Just wondering if key is non-unique (e.g., since it's possible for no columns to be key columns).

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1363)*

**Comment by ratulm** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[projects/question/src/main/java/org/batfish/question/jsonpathtotable/JsonPathToTableAnswerElement.java, line 33 at r2](https://reviewable.io/reviews/batfish/batfish/1363#-LC7VuBLBZYZtIu8NT9p:-LC7_P-46fANBwwSjRaA:bgx6hss) ([raw file](https://github.com/batfish/batfish/blob/1873bb2352bbb48a9442da3266967ba0317d8cd8/projects/question/src/main/java/org/batfish/question/jsonpathtotable/JsonPathToTableAnswerElement.java#L33)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Just wondering if key is non-unique (e.g., since it's possible for no columns to be key columns).
</blockquote></details>

this map is from column names to column metadata. column names are unique, and only one metadata object for each name. the metadata contains information on whether the column  is a key. completely fine for there to be no key columns.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1363)*

**Pull request merged**
