### PR TITLE
NumberSpace: remove dangerous and misleading not methods

### PR DESCRIPTION
**Pull request by dhalperi**
Replace with a straightforward complement-within-bounds function.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7490)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @anothermattbrown and @arifogel)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/NumberSpace.java, line 191 at r1](https://reviewable.io/reviews/batfish/batfish/7490#-MlCkcWIE7wxa0Z6B1U1:-MlCkcWIE7wxa0Z6B1U2:b-hue0i1) ([raw file](https://github.com/batfish/batfish/blob/96216fa2f82efe35fc6fe1539b87908974bdfdce/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/NumberSpace.java#L191)):*
> ```Java
>   /** Compute the difference between two {@link NumberSpace}s */
>   public final S difference(S other) {
>     return toBuilder().excluding(other).build();
> ```

FYI: this was the only use of the removed functions outside tests, including downstream code.

**Review by arifogel — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7490)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown)

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7490)* status: all files reviewed, 1 unresolved discussion (waiting on @anothermattbrown and @dhalperi)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/NumberSpace.java, line 300 at r1](https://reviewable.io/reviews/batfish/batfish/7490#-MlD8O3o6SlfV0dlCyEE:-MlD8O3o6SlfV0dlCyEF:b-phw2dc) ([raw file](https://github.com/batfish/batfish/blob/96216fa2f82efe35fc6fe1539b87908974bdfdce/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/NumberSpace.java#L300)):*
> ```Java
>   public final S complement(Range<T> bounds) {
>     checkArgument(
>         _rangeset.span().encloses(bounds),
> ```

Is this backwards?

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7490)* status: all files reviewed, 1 unresolved discussion (waiting on @anothermattbrown and @arifogel)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/NumberSpace.java, line 300 at r1](https://reviewable.io/reviews/batfish/batfish/7490#-MlD8O3o6SlfV0dlCyEE:-MlD9d5i3hrnRBYvBDUe:bougcv) ([raw file](https://github.com/batfish/batfish/blob/96216fa2f82efe35fc6fe1539b87908974bdfdce/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/NumberSpace.java#L300)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Is this backwards?
</blockquote></details>

I have a fixup PR, but the more alarming thing is all the things that broke. See #7491 for more info.

**Comment by dhalperi** [comment]
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/NumberSpace.java, line 300 at r1](https://reviewable.io/reviews/batfish/batfish/7490#-MlD8O3o6SlfV0dlCyEE:-MlD9jW58V4yEa1zHLOv:bgnltws) ([raw file](https://github.com/batfish/batfish/blob/96216fa2f82efe35fc6fe1539b87908974bdfdce/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/NumberSpace.java#L300)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I have a fixup PR, but the more alarming thing is all the things that broke. See #7491 for more info.
</blockquote></details>

s/fixup PR/fixup commit/

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7490)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @anothermattbrown and @arifogel)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/NumberSpace.java, line 300 at r1](https://reviewable.io/reviews/batfish/batfish/7490#-MlD8O3o6SlfV0dlCyEE:-MlGwBtp15B-RYlThoSp:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/96216fa2f82efe35fc6fe1539b87908974bdfdce/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/NumberSpace.java#L300)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

s/fixup PR/fixup commit/
</blockquote></details>

Done.

**Pull request merged**
