### PR TITLE
Junos: handle apply-flags omit

### PR DESCRIPTION
**Pull request by dhalperi**

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8784)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[`projects/batfish/src/test/java/org/batfish/grammar/juniper/JuniperFlattenerTest.java` line 59 at r1](https://reviewable.io/reviews/batfish/batfish/8784#-NcPShLV0asf9r9zq3ac:-NcPShLV0asf9r9zq3ad:b5mgasc) ([raw file](https://github.com/batfish/batfish/blob/0d03bc03f86740acc67bac3a1142e896160b7083/projects/batfish/src/test/java/org/batfish/grammar/juniper/JuniperFlattenerTest.java#L59)):*
> ```Java
>   }
> 
>   /** Test that sequences of flat lines do not create a linear tree. */
> ```

What does `do not create a linear tree` mean? Isn't the thing you are actually testing here much more straightforward, i.e. lexing/parsing of result of `apply-flags omit`?

**Comment by dhalperi** [comment]
*[`projects/batfish/src/test/java/org/batfish/grammar/juniper/JuniperFlattenerTest.java` line 59 at r1](https://reviewable.io/reviews/batfish/batfish/8784#-NcPShLV0asf9r9zq3ac:-NcPUijF-8zDXQkY-hj1:bsjojuk) ([raw file](https://github.com/batfish/batfish/blob/0d03bc03f86740acc67bac3a1142e896160b7083/projects/batfish/src/test/java/org/batfish/grammar/juniper/JuniperFlattenerTest.java#L59)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

What does `do not create a linear tree` mean? Isn't the thing you are actually testing here much more straightforward, i.e. lexing/parsing of result of `apply-flags omit`?
</blockquote></details>

Copypasta, thanks.

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8784)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @arifogel)

___
*[`projects/batfish/src/test/java/org/batfish/grammar/juniper/JuniperFlattenerTest.java` line 59 at r1](https://reviewable.io/reviews/batfish/batfish/8784#-NcPShLV0asf9r9zq3ac:-NcPVC5r5uNJZviN3Pl4:bt2vr1b) ([raw file](https://github.com/batfish/batfish/blob/0d03bc03f86740acc67bac3a1142e896160b7083/projects/batfish/src/test/java/org/batfish/grammar/juniper/JuniperFlattenerTest.java#L59)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Copypasta, thanks.
</blockquote></details>

Fixed.

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8784)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dhalperi)

**Pull request merged**
