### PR TITLE
Ipsec vpn status

### PR DESCRIPTION
**Pull request by ratulm**
a new question that returns the status of all configured ipsec vpns

### CODE REVIEW

**Comment by dhalperi** [comment]
Reviewed 3 of 3 files at r1, 2 of 3 files at r2.
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[projects/question/src/main/java/org/batfish/question/IpsecVpnStatusQuestionPlugin.java, line 1 at r1](https://reviewable.io:443/reviews/batfish/batfish/1023#-L6pHqlnkrfVEqI7DD1z:-L6pHqlnkrfVEqI7DD2-:bt266th) ([raw file](https://github.com/batfish/batfish/blob/cbe3f043c4aefa14b80b0f9f57562028b0fcf02c/projects/question/src/main/java/org/batfish/question/IpsecVpnStatusQuestionPlugin.java#L1)):*
> ```Java
> package org.batfish.question;
> ```

Following the new pattern, create a new package (`question.ipsec`?) for this question and then create separate Java files for each of the classes as appropriate. No need to throw all these questions into a single directory, and no need to put all question classes as `static` classes in a single nested class file. This is what packages are for.

---

*[projects/question/src/main/java/org/batfish/question/IpsecVpnStatusQuestionPlugin.java, line 76 at r1](https://reviewable.io:443/reviews/batfish/batfish/1023#-L6pJWarCKCuUXdPyG3k:-L6pJWarCKCuUXdPyG3l:bqw44dv) ([raw file](https://github.com/batfish/batfish/blob/cbe3f043c4aefa14b80b0f9f57562028b0fcf02c/projects/question/src/main/java/org/batfish/question/IpsecVpnStatusQuestionPlugin.java#L76)):*
> vpnname

Should this be the same as the JsonProperty name?

---

*[projects/question/src/main/java/org/batfish/question/IpsecVpnStatusQuestionPlugin.java, line 183 at r1](https://reviewable.io:443/reviews/batfish/batfish/1023#-L6pIOURnwhYFUZtoaHA:-L6pIOURnwhYFUZtoaHB:b16lps5) ([raw file](https://github.com/batfish/batfish/blob/cbe3f043c4aefa14b80b0f9f57562028b0fcf02c/projects/question/src/main/java/org/batfish/question/IpsecVpnStatusQuestionPlugin.java#L183)):*
> ```Java
>           SortedSet<Problem> problems = new TreeSet<>();
>           IpsecVpn remoteIpsecVpn = null;
>           if (ipsecVpn.getRemoteIpsecVpn() == null) {
> ```

For unit tests, pull this logic into a separate testable method. Something like

```java
// Private helper, visible for testing.
static Set<Problem> getIpsecProblems(IpSecVPN ipsecVpn) {
   ...
}
```

Then you can construct `IpSecVpn` objects to the helper to exercise the (pretty complicated!) control flow in this function, without needing to have end-to-end configs.

---

*[tests/aws/commands, line 11 at r1](https://reviewable.io:443/reviews/batfish/batfish/1023#-L6pIAKsETaAgB8ogYik:-L6pIAKsETaAgB8ogYil:b-tguscy) ([raw file](https://github.com/batfish/batfish/blob/cbe3f043c4aefa14b80b0f9f57562028b0fcf02c/tests/aws/commands#L11)):*
> ```
> test tests/aws/nodes-example-aws.ref get nodes summary=false
> test tests/aws/topology-example-aws.ref get-object testrig_pojo_topology
> test tests/aws/ipsecvpnstatus-example-aws.ref get ipsecvpnstatus
> ```

The proliferation of ref tests is hurting us. No need for a ref test here, use java unit tests instead.

Some suggestions above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/1023)*

**Comment by ratulm** [comment]
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[projects/question/src/main/java/org/batfish/question/IpsecVpnStatusQuestionPlugin.java, line 1 at r1](https://reviewable.io:443/reviews/batfish/batfish/1023#-L6pHqlnkrfVEqI7DD1z:-L6pLyoqHoF_85ozoahy:bgztzpk) ([raw file](https://github.com/batfish/batfish/blob/cbe3f043c4aefa14b80b0f9f57562028b0fcf02c/projects/question/src/main/java/org/batfish/question/IpsecVpnStatusQuestionPlugin.java#L1)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Following the new pattern, create a new package (`question.ipsec`?) for this question and then create separate Java files for each of the classes as appropriate. No need to throw all these questions into a single directory, and no need to put all question classes as `static` classes in a single nested class file. This is what packages are for.
</blockquote></details>

"new pattern" : are there examples already? (i think i understand the suggestion, so can create the first example if needed but want to follow the patter if an example exists.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/1023)*

**Comment by dhalperi** [comment]
*[projects/question/src/main/java/org/batfish/question/IpsecVpnStatusQuestionPlugin.java, line 1 at r1](https://reviewable.io:443/reviews/batfish/batfish/1023#-L6pHqlnkrfVEqI7DD1z:-L6pNHEZbuuwSoKmFihP:b18jy4a) ([raw file](https://github.com/batfish/batfish/blob/cbe3f043c4aefa14b80b0f9f57562028b0fcf02c/projects/question/src/main/java/org/batfish/question/IpsecVpnStatusQuestionPlugin.java#L1)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

"new pattern" : are there examples already? (i think i understand the suggestion, so can create the first example if needed but want to follow the patter if an example exists.)
</blockquote></details>

BEP#68 I believe

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/1023)*

**Comment by ratulm** [comment]
Review status: 1 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[projects/question/src/main/java/org/batfish/question/IpsecVpnStatusQuestionPlugin.java, line 76 at r1](https://reviewable.io:443/reviews/batfish/batfish/1023#-L6pJWarCKCuUXdPyG3k:-L6pSixl6WgJBnfoxLIy:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/cbe3f043c4aefa14b80b0f9f57562028b0fcf02c/projects/question/src/main/java/org/batfish/question/IpsecVpnStatusQuestionPlugin.java#L76)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> vpnname

Should this be the same as the JsonProperty name?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/1023)*

**Comment by dhalperi** [comment]
Reviewed 8 of 8 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1023)*

**Comment by ratulm** [comment]
Review status: 5 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/aws/commands, line 11 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1023#-L6pIAKsETaAgB8ogYik:-L6tWwFH8ezq2eMIjfbX:b-novtq2) ([raw file](https://github.com/batfish/batfish/blob/cbe3f043c4aefa14b80b0f9f57562028b0fcf02c/tests/aws/commands#L11)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

The proliferation of ref tests is hurting us. No need for a ref test here, use java unit tests instead.

Some suggestions above.
</blockquote></details>

I left this ref test. I think there is a lot of machinery not being tested by the unit test (e.g., building the VPN model itself). Once we add tests to cover those aspects, we should start removing such tests. 

---

*[projects/question/src/main/java/org/batfish/question/IpsecVpnStatusQuestionPlugin.java, line 183 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1023#-L6pIOURnwhYFUZtoaHA:-L6tWvcg5_R-LlGwKsud:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/cbe3f043c4aefa14b80b0f9f57562028b0fcf02c/projects/question/src/main/java/org/batfish/question/IpsecVpnStatusQuestionPlugin.java#L183)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

For unit tests, pull this logic into a separate testable method. Something like

```java
// Private helper, visible for testing.
static Set<Problem> getIpsecProblems(IpSecVPN ipsecVpn) {
   ...
}
```

Then you can construct `IpSecVpn` objects to the helper to exercise the (pretty complicated!) control flow in this function, without needing to have end-to-end configs.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1023)*

**Comment by dhalperi** [comment]
:lgtm: Nice work!

---

Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/1023#-:-L6tafscNDHYA74wVsc-:bcmw7ss)*

**Comment by dhalperi** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/1023)*

**Pull request merged**
