### PR TITLE
Docs: New vendor or feature

### PR DESCRIPTION
**Pull request by ratulm**
Moving over content from the Developer Wiki. Something is better than nothing.

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/9187)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ratulm)

___
*[`docs/adding_new_device_support/README.md` line 6 at r1](https://reviewable.io/reviews/batfish/batfish/9187#-O6Mzvz8ErgGXdg81Tsv:-O6Mzvz8ErgGXdg81Tsw:b-ru7d2x) ([raw file](https://github.com/batfish/batfish/blob/1ebddada81075479a83dc1ed65d6b9ebb9a55ee4/docs/adding_new_device_support/README.md#L6)):*
> ```Markdown
> 
> Detailed notes on adding parsing support for a new configuration format are [here](https://docs.google.com/document/d/1ikGAh5LT4RGAycDLWe92l_EOS5-HclQ6I56VZMc3hws/edit#);
> an outline of the steps is below.
> ```

This doc is woefully out of date after the first page. I would include overview language inline here and ditch the doc reference.

Basically, the overview should be:

------------------
```
Read the following sections of the Batfish developer docs and follow along the steps for creating support for the new fictional CoolNos network configuration language:

1. Read about [parsing](../parsing/README.md)` to learn how to add a parser for your new vendor's configuration syntax
2. Read [extraction](../extraction/README.md)` to learn how to create a vendor-specific data model for your new model that is populated from the parse tree created by your new parser
3. Read `docs/conversion/README.md` to learn how to convert the vendor-specific data model to Batfish's vendor-independent network device model

In most cases, these are the only steps needed to add new vendor support. Reach out on the [Batfish Slack #dev channel](https://batfish-org.slack.com/archives/CL7U2GUUF) if you have more complicated use cases than a single-file DSL-based network configuration language, e.g.
1. JSON/YAML-based network configuration language
2. Multiple configuration files for a single device
```

The caveat here is that the conversion docs are incomplete. Note that the configuration example in the doc you referenced has the wrong API and will not compile. If you want _something_ quick, you could paste a simple `toVendorIndepenedentConfigurations` implementation by paring down the one in `CiscoNxosConfiguration.java` into the conversion doc.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/9187)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ratulm)

___
*[`docs/adding_new_device_support/README.md` line 6 at r1](https://reviewable.io/reviews/batfish/batfish/9187#-O6Mzvz8ErgGXdg81Tsv:-O6N211N-Twff9fIMdc0:b-6b07nd) ([raw file](https://github.com/batfish/batfish/blob/1ebddada81075479a83dc1ed65d6b9ebb9a55ee4/docs/adding_new_device_support/README.md#L6)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

This doc is woefully out of date after the first page. I would include overview language inline here and ditch the doc reference.

Basically, the overview should be:

------------------
```
Read the following sections of the Batfish developer docs and follow along the steps for creating support for the new fictional CoolNos network configuration language:

1. Read about [parsing](../parsing/README.md)` to learn how to add a parser for your new vendor's configuration syntax
2. Read [extraction](../extraction/README.md)` to learn how to create a vendor-specific data model for your new model that is populated from the parse tree created by your new parser
3. Read `docs/conversion/README.md` to learn how to convert the vendor-specific data model to Batfish's vendor-independent network device model

In most cases, these are the only steps needed to add new vendor support. Reach out on the [Batfish Slack #dev channel](https://batfish-org.slack.com/archives/CL7U2GUUF) if you have more complicated use cases than a single-file DSL-based network configuration language, e.g.
1. JSON/YAML-based network configuration language
2. Multiple configuration files for a single device
```

The caveat here is that the conversion docs are incomplete. Note that the configuration example in the doc you referenced has the wrong API and will not compile. If you want _something_ quick, you could paste a simple `toVendorIndepenedentConfigurations` implementation by paring down the one in `CiscoNxosConfiguration.java` into the conversion doc.
</blockquote></details>

Ugh some typos in there, but you get the gist.

**Review by ratulm — COMMENTED** [review]
I see the staleness you are referring to. I think the better path is to just delete the dangling pointer. The content of the file I ported over is just creating more confusion via inconsistencies with the newer documentation. 

> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/9187#-:-O6U2E233VgaDbCQew9Y:b-361lqb)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @arifogel)

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/9187)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @arifogel)

___
*[`docs/adding_new_device_support/README.md` line 6 at r1](https://reviewable.io/reviews/batfish/batfish/9187#-O6Mzvz8ErgGXdg81Tsv:-O6U2dDg9UJllUhzCy1w:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/1ebddada81075479a83dc1ed65d6b9ebb9a55ee4/docs/adding_new_device_support/README.md#L6)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

The other big thing we are probably missing is unit tests. In each case of something missing, if you want something quick just link to Cisco NXOS stuff.
</blockquote></details>

Done.

**Review by arifogel — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/9187)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ratulm)

**Pull request merged**
