### PR TITLE
FortiOS: rename service groups

### PR DESCRIPTION
**Pull request by sfraint**
Add support for renaming service groups.

### CODE REVIEW

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6770)* status: 0 of 15 files reviewed, 1 unresolved discussion (waiting on @corinaminer and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6770#-MWRYm494DWZMWeWhoZS:-MWRYm494DWZMWeWhoZT:bcxyn48) (no related file):*
after https://github.com/batfish/batfish/pull/6768

---

**Review by corinaminer — COMMENTED** [review]
> Reviewed 1 of 15 files at r1, 2 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6770)* status: all files reviewed, 2 unresolved discussions (waiting on @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 798 at r2](https://reviewable.io/reviews/batfish/batfish/6770#-MWVvmFSDMafoKOxl5Ja:-MWVvmFSDMafoKOxl5Jb:b-e9j66p) ([raw file](https://github.com/batfish/batfish/blob/a63bfed0059cb3ebf2908740ba8a1f67285dd3c9/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L798)):*
> ```Java
>     }
>     if (_c.getServices().containsKey(newName) || _c.getServiceGroups().containsKey(newName)) {
>       // TODO handle conflicting renames
> ```

in what sense are conflicting renames not handled?

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6770)* status: all files reviewed, 1 unresolved discussion (waiting on @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 798 at r2](https://reviewable.io/reviews/batfish/batfish/6770#-MWVvmFSDMafoKOxl5Ja:-MWW6E-eANV7x9gdJ692:b-z9qsuf) ([raw file](https://github.com/batfish/batfish/blob/a63bfed0059cb3ebf2908740ba8a1f67285dd3c9/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L798)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

in what sense are conflicting renames not handled?
</blockquote></details>

since conflicting renames triggers an interactive mode on the CLI (e.g. "enter `y/n` to overwrite and proceed"), we had planned on implementing conflicting rename as an implied `y` to overwrite the other structure

but we're not ready to handle that yet

**Review by corinaminer — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6770#-:-MWWGgfo-Kc9758mDcR3:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 798 at r2](https://reviewable.io/reviews/batfish/batfish/6770#-MWVvmFSDMafoKOxl5Ja:-MWWGfZTCmSCn5amTqsH:b32wtd) ([raw file](https://github.com/batfish/batfish/blob/a63bfed0059cb3ebf2908740ba8a1f67285dd3c9/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L798)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

since conflicting renames triggers an interactive mode on the CLI (e.g. "enter `y/n` to overwrite and proceed"), we had planned on implementing conflicting rename as an implied `y` to overwrite the other structure

but we're not ready to handle that yet
</blockquote></details>

ok

**Pull request merged**
