### PR TITLE
A10: grammar and VS model skeleton

### PR DESCRIPTION
**Pull request by sfraint**

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 22 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7400)* status: 22 of 24 files reviewed, 12 unresolved discussions (waiting on @corinaminer and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7400#-MjkcGAFCp8ntb-M0sGC:-MjkcGAFCp8ntb-M0sGD:bjj0syy) (no related file):*
javadoc all new classes, non-trivial visible functions

---
___
*[projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10_common.g4, line 9 at r1](https://reviewable.io/reviews/batfish/batfish/7400#-MjkaGA88MSIlkCd90O_:-MjkaGA88MSIlkCd90Oa:b-nw9kkh) ([raw file](https://github.com/batfish/batfish/blob/02df7ad1c5060970907f1b9fe62ed163271b66ec/projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10_common.g4#L9)):*
> ```ANTLR
> hostname: str;
> 
> str: STR;
> ```

I don't think this should exist unless you need to copy the fortios pattern where strings can be quoted or unquoted, and quote portionss can be interleaved.
For reference:
```
str: STR_SEPARATOR str_content;

// can include whitespace, newlines, html tags, etc.
str_content: (double_quoted_string | single_quoted_string | UNQUOTED_WORD_CHARS)+;
```
___
*[projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Lexer.g4, line 22 at r1](https://reviewable.io/reviews/batfish/batfish/7400#-MjkVvfF1MAa4MoJkFjL:-MjkVvfF1MAa4MoJkFjM:bd4wpkl) ([raw file](https://github.com/batfish/batfish/blob/02df7ad1c5060970907f1b9fe62ed163271b66ec/projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Lexer.g4#L22)):*
> ```ANTLR
> ;
> 
> IP_ADDRESS: F_IpAddress;
> ```

Can you add `SUBNET_MASK`above (I think nexus has it)?
___
*[projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Lexer.g4, line 34 at r1](https://reviewable.io/reviews/batfish/batfish/7400#-MjkW5VH-WmLB0Vmma5D:-MjkW5VH-WmLB0Vmma5E:bg8a96o) ([raw file](https://github.com/batfish/batfish/blob/02df7ad1c5060970907f1b9fe62ed163271b66ec/projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Lexer.g4#L34)):*
> ```ANTLR
> UINT32: F_Uint32;
> 
> WS: F_Whitespace+ -> channel(HIDDEN);
> ```

Use ` -> skip` generally for better performance unless you need to read this from the `HIDDEN` channel (I don't see anything in base lexer or predicates here that does)
___
*[projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Parser.g4, line 10 at r1](https://reviewable.io/reviews/batfish/batfish/7400#-MjkXjKDBtx_PFd8pyMM:-MjkXjKE-6X8VZ_8xJF6:b-qqoplf) ([raw file](https://github.com/batfish/batfish/blob/02df7ad1c5060970907f1b9fe62ed163271b66ec/projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Parser.g4#L10)):*
> ```ANTLR
> }
> 
> a10_configuration: statement+ EOF;
> ```

nexus has this:
```
cisco_nxos_configuration
:
  NEWLINE?
  statement+ EOF
;
```

What happens now if you have a newline at the top of the file? If you end a file without a newline?
___
*[projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java, line 24 at r1](https://reviewable.io/reviews/batfish/batfish/7400#-MjkYSA50FkF_awLJKpr:-MjkYSA50FkF_awLJKps:bcpf5lh) ([raw file](https://github.com/batfish/batfish/blob/02df7ad1c5060970907f1b9fe62ed163271b66ec/projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java#L24)):*
> ```Java
> 
> @ParametersAreNonnullByDefault
> public class A10ConfigurationBuilder extends A10ParserBaseListener implements SilentSyntaxListener {
> ```

Please make `package-info.java` in this package with `@ParamatersAreNonnullByDefault` and remove annotation from classes
___
*[projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java, line 38 at r1](https://reviewable.io/reviews/batfish/batfish/7400#-MjkZlkuAvV5v8ayqBoO:-MjkZlkuAvV5v8ayqBoP:bd4686n) ([raw file](https://github.com/batfish/batfish/blob/02df7ad1c5060970907f1b9fe62ed163271b66ec/projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java#L38)):*
> ```Java
>     _silentSyntax = silentSyntax;
>   }
> ```

Add:
```
  @Override
  public void exitEveryRule(ParserRuleContext ctx) {
    tryProcessSilentSyntax(ctx);
  }
```
___
*[projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java, line 102 at r1](https://reviewable.io/reviews/batfish/batfish/7400#-Mjkbe_ZDDmCiztd9yj1:-MjkbZx4BY9DKCKrWpHI:b-8oob4l) ([raw file](https://github.com/batfish/batfish/blob/02df7ad1c5060970907f1b9fe62ed163271b66ec/projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java#L102)):*
> ```Java
> 
>   private @Nonnull Optional<String> toString(
>       ParserRuleContext messageCtx, StrContext ctx, String type, Pattern pattern) {
> ```

If `str` is unnecessary as I suspect (noted above), second argument should be `ParserRuleContext`.

Also, please use where possible (modify as needed):
```
  /**
   * Return the text of the provided {@code ctx} if its length is within the provided {@link
   * IntegerSpace lengthSpace}, or else {@link Optional#empty}.
   */
  private @Nonnull Optional<String> toStringWithLengthInSpace(
      ParserRuleContext messageCtx, ParserRuleContext ctx, IntegerSpace lengthSpace, String name) {
    String text = ctx.getText();
    if (!lengthSpace.contains(text.length())) {
      warn(
          messageCtx,
          String.format(
              "Expected %s with length in range %s, but got '%s'", text, lengthSpace, name));
      return Optional.empty();
    }
    return Optional.of(text);
  }
```
___
*[projects/batfish/src/test/java/org/batfish/vendor/a10/grammar/A10GrammarTest.java, line 82 at r1](https://reviewable.io/reviews/batfish/batfish/7400#-Mjkcii34nOdXG7hUbTY:-Mjkcii34nOdXG7hUbTZ:b-4egjid) ([raw file](https://github.com/batfish/batfish/blob/02df7ad1c5060970907f1b9fe62ed163271b66ec/projects/batfish/src/test/java/org/batfish/vendor/a10/grammar/A10GrammarTest.java#L82)):*
> ```Java
>       Configuration c =
>           configs.getOrDefault(canonicalHostname, configs.get(canonicalChassisHostname));
>       assertThat(c, hasConfigurationFormat(CHECK_POINT_GATEWAY));
> ```

checkpoint? All of this looks wrong
___
*[projects/batfish/src/test/java/org/batfish/vendor/a10/grammar/A10GrammarTest.java, line 96 at r1](https://reviewable.io/reviews/batfish/batfish/7400#-MjkcsSxAlFty3FdwNFi:-MjkcsSxAlFty3FdwNFj:b-oczdf1) ([raw file](https://github.com/batfish/batfish/blob/02df7ad1c5060970907f1b9fe62ed163271b66ec/projects/batfish/src/test/java/org/batfish/vendor/a10/grammar/A10GrammarTest.java#L96)):*
> ```Java
> 
>   @Test
>   public void testHostname() {
> ```

Call this `testHostnameExtraction`
Add `testHostnameConversion` when you have conversion skeleton.
___
*[projects/batfish/src/test/resources/org/batfish/vendor/a10/grammar/testconfigs/hostname, line 1 at r1](https://reviewable.io/reviews/batfish/batfish/7400#-MjkPixi4ROfsCyyzFY8:-MjkPixi4ROfsCyyzFY9:boewm4b) ([raw file](https://github.com/batfish/batfish/blob/02df7ad1c5060970907f1b9fe62ed163271b66ec/projects/batfish/src/test/resources/org/batfish/vendor/a10/grammar/testconfigs/hostname#L1)):*
> ```
> !version 3.4.5-A6-B78, build 90 (Aug-5-2021,01:23)
> ```

Is there no RANCID header for a10? If not, please add BATFISH format detection header.
___
*[tests/aws/topology-example-aws.ref, line 1104 at r2](https://reviewable.io/reviews/batfish/batfish/7400#-MjkdHJu47QF6YVcK23O:-MjkdHJv5XeMkpwXi7hy:b-5ev3tl) ([raw file](https://github.com/batfish/batfish/blob/051930e7d13d0a7417b5a5a502016f9f410bd046/tests/aws/topology-example-aws.ref#L1104)):*
> ```
>       "properties" : null
>     }
>   ],
> ```

I thought you said there were no ref changes

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7400)* status: 14 of 24 files reviewed, 12 unresolved discussions (waiting on @arifogel, @corinaminer, and @sfraint)

___
*[projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10_common.g4, line 9 at r1](https://reviewable.io/reviews/batfish/batfish/7400#-MjkaGA88MSIlkCd90O_:-Mjken-f7rWqlYsUgL_T:b-2afa6r) ([raw file](https://github.com/batfish/batfish/blob/02df7ad1c5060970907f1b9fe62ed163271b66ec/projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10_common.g4#L9)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

I don't think this should exist unless you need to copy the fortios pattern where strings can be quoted or unquoted, and quote portionss can be interleaved.
For reference:
```
str: STR_SEPARATOR str_content;

// can include whitespace, newlines, html tags, etc.
str_content: (double_quoted_string | single_quoted_string | UNQUOTED_WORD_CHARS)+;
```
</blockquote></details>

so, like this?
___
*[projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Lexer.g4, line 22 at r1](https://reviewable.io/reviews/batfish/batfish/7400#-MjkVvfF1MAa4MoJkFjL:-MjkfIDH8m23f5_6oVtS:b-7tfmjp) ([raw file](https://github.com/batfish/batfish/blob/02df7ad1c5060970907f1b9fe62ed163271b66ec/projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Lexer.g4#L22)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Can you add `SUBNET_MASK`above (I think nexus has it)?
</blockquote></details>

added
___
*[projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Lexer.g4, line 34 at r1](https://reviewable.io/reviews/batfish/batfish/7400#-MjkW5VH-WmLB0Vmma5D:-MjkfIqdAJeuugOZt4UY:b2nhysk) ([raw file](https://github.com/batfish/batfish/blob/02df7ad1c5060970907f1b9fe62ed163271b66ec/projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Lexer.g4#L34)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Use ` -> skip` generally for better performance unless you need to read this from the `HIDDEN` channel (I don't see anything in base lexer or predicates here that does)
</blockquote></details>

ack
___
*[projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Parser.g4, line 10 at r1](https://reviewable.io/reviews/batfish/batfish/7400#-MjkXjKDBtx_PFd8pyMM:-Mjkfac5Dmaibk8PbVPA:bwrwasd) ([raw file](https://github.com/batfish/batfish/blob/02df7ad1c5060970907f1b9fe62ed163271b66ec/projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Parser.g4#L10)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

nexus has this:
```
cisco_nxos_configuration
:
  NEWLINE?
  statement+ EOF
;
```

What happens now if you have a newline at the top of the file? If you end a file without a newline?
</blockquote></details>

how should we handle not ending the file with a newline?
___
*[projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java, line 24 at r1](https://reviewable.io/reviews/batfish/batfish/7400#-MjkYSA50FkF_awLJKpr:-Mjkg0XXEKGqfWT9kBvI:b-7tfmjp) ([raw file](https://github.com/batfish/batfish/blob/02df7ad1c5060970907f1b9fe62ed163271b66ec/projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java#L24)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Please make `package-info.java` in this package with `@ParamatersAreNonnullByDefault` and remove annotation from classes
</blockquote></details>

added
___
*[projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java, line 38 at r1](https://reviewable.io/reviews/batfish/batfish/7400#-MjkZlkuAvV5v8ayqBoO:-Mjkg9Nf0gavt35am5ko:b-sfh3lv) ([raw file](https://github.com/batfish/batfish/blob/02df7ad1c5060970907f1b9fe62ed163271b66ec/projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java#L38)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Add:
```
  @Override
  public void exitEveryRule(ParserRuleContext ctx) {
    tryProcessSilentSyntax(ctx);
  }
```
</blockquote></details>

what is this for? it doesn't exist in all `...ConfigurationBuilder`s today, do we need to add it?
___
*[projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java, line 102 at r1](https://reviewable.io/reviews/batfish/batfish/7400#-Mjkbe_ZDDmCiztd9yj1:-MjkhV1b2Di_TJmaEBi1:b-7tfmjp) ([raw file](https://github.com/batfish/batfish/blob/02df7ad1c5060970907f1b9fe62ed163271b66ec/projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java#L102)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

If `str` is unnecessary as I suspect (noted above), second argument should be `ParserRuleContext`.

Also, please use where possible (modify as needed):
```
  /**
   * Return the text of the provided {@code ctx} if its length is within the provided {@link
   * IntegerSpace lengthSpace}, or else {@link Optional#empty}.
   */
  private @Nonnull Optional<String> toStringWithLengthInSpace(
      ParserRuleContext messageCtx, ParserRuleContext ctx, IntegerSpace lengthSpace, String name) {
    String text = ctx.getText();
    if (!lengthSpace.contains(text.length())) {
      warn(
          messageCtx,
          String.format(
              "Expected %s with length in range %s, but got '%s'", text, lengthSpace, name));
      return Optional.empty();
    }
    return Optional.of(text);
  }
```
</blockquote></details>

added
___
*[projects/batfish/src/test/java/org/batfish/vendor/a10/grammar/A10GrammarTest.java, line 82 at r1](https://reviewable.io/reviews/batfish/batfish/7400#-Mjkcii34nOdXG7hUbTY:-Mjkhqra2P3OJR9iTl79:b-7ql1td) ([raw file](https://github.com/batfish/batfish/blob/02df7ad1c5060970907f1b9fe62ed163271b66ec/projects/batfish/src/test/java/org/batfish/vendor/a10/grammar/A10GrammarTest.java#L82)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

checkpoint? All of this looks wrong
</blockquote></details>

fixed
___
*[projects/batfish/src/test/java/org/batfish/vendor/a10/grammar/A10GrammarTest.java, line 96 at r1](https://reviewable.io/reviews/batfish/batfish/7400#-MjkcsSxAlFty3FdwNFi:-Mjki4fG-0onjwIfvnzE:b-uzkr9v) ([raw file](https://github.com/batfish/batfish/blob/02df7ad1c5060970907f1b9fe62ed163271b66ec/projects/batfish/src/test/java/org/batfish/vendor/a10/grammar/A10GrammarTest.java#L96)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Call this `testHostnameExtraction`
Add `testHostnameConversion` when you have conversion skeleton.
</blockquote></details>

updated and added
___
*[projects/batfish/src/test/resources/org/batfish/vendor/a10/grammar/testconfigs/hostname, line 1 at r1](https://reviewable.io/reviews/batfish/batfish/7400#-MjkPixi4ROfsCyyzFY8:-MjkiLZBDDW0wvL5zVhZ:b-8ngjxu) ([raw file](https://github.com/batfish/batfish/blob/02df7ad1c5060970907f1b9fe62ed163271b66ec/projects/batfish/src/test/resources/org/batfish/vendor/a10/grammar/testconfigs/hostname#L1)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Is there no RANCID header for a10? If not, please add BATFISH format detection header.
</blockquote></details>

no standard rancid header afaict, there already is a batfish format header supported, and tested in this PR
___
*[tests/aws/topology-example-aws.ref, line 1104 at r2](https://reviewable.io/reviews/batfish/batfish/7400#-MjkdHJu47QF6YVcK23O:-MjkiWZI1fRlgySO09G6:b-h1kotn) ([raw file](https://github.com/batfish/batfish/blob/051930e7d13d0a7417b5a5a502016f9f410bd046/tests/aws/topology-example-aws.ref#L1104)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

I thought you said there were no ref changes
</blockquote></details>

keeping enums in alphabetical order results in reordering of a couple refs

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7400)* status: 14 of 24 files reviewed, 12 unresolved discussions (waiting on @arifogel and @corinaminer)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7400#-MjkcGAFCp8ntb-M0sGC:-MjkkYZ-E6T-lzHUwB7k:bp78q2) (no related file):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

javadoc all new classes, non-trivial visible functions
</blockquote></details>

no substantial, visible functions added here, lmk if you see differently

---

**Review by arifogel — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7400)* status: all files reviewed, 7 unresolved discussions (waiting on @corinaminer and @sfraint)

___
*[projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10_common.g4, line 9 at r1](https://reviewable.io/reviews/batfish/batfish/7400#-MjkaGA88MSIlkCd90O_:-Mjkr1J8C8wFUnfWhKvl:b-b3xxmd) ([raw file](https://github.com/batfish/batfish/blob/02df7ad1c5060970907f1b9fe62ed163271b66ec/projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10_common.g4#L9)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

so, like this?
</blockquote></details>

I mean don't have a rule at all unless we need to do something for every `str` or `str_content` or whatever. It bloats the parse tree and is inefficient.
Plus later contributors might be tempted to convert it directly.

Sorry if I may have vacillated on this in the past.

Having other rules use `WORD` is what nexus does, and I'm fine with that.
___
*[projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Parser.g4, line 10 at r1](https://reviewable.io/reviews/batfish/batfish/7400#-MjkXjKDBtx_PFd8pyMM:-Mjks2xI1b25VNJCckOw:byglq7n) ([raw file](https://github.com/batfish/batfish/blob/02df7ad1c5060970907f1b9fe62ed163271b66ec/projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Parser.g4#L10)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

how should we handle not ending the file with a newline?
</blockquote></details>

Might be handled by preprocessor? Can ignore for now if you want.
___
*[projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java, line 24 at r1](https://reviewable.io/reviews/batfish/batfish/7400#-MjkYSA50FkF_awLJKpr:-MjksbIZ5rt_MkbPTOlv:b-ihm3c4) ([raw file](https://github.com/batfish/batfish/blob/02df7ad1c5060970907f1b9fe62ed163271b66ec/projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java#L24)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

added
</blockquote></details>

nit: final
___
*[projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java, line 38 at r1](https://reviewable.io/reviews/batfish/batfish/7400#-MjkZlkuAvV5v8ayqBoO:-MjksCbT8Mngrj-c7SPk:b-u4gwcs) ([raw file](https://github.com/batfish/batfish/blob/02df7ad1c5060970907f1b9fe62ed163271b66ec/projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java#L38)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

what is this for? it doesn't exist in all `...ConfigurationBuilder`s today, do we need to add it?
</blockquote></details>

It's supposed to exist. The problem is that it is defined as nop in generated `xxxBaseListenter`, so it's hard to find if you're not overriding it.
For non-line-based configs, I think it needs special implementation? Or maybe for stuff with apply-groups type crap? Don't worry about fixing other vendors right now.
___
*[projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java, line 140 at r3](https://reviewable.io/reviews/batfish/batfish/7400#-Mjkt0KlB0jwnFB9I4Z3:-Mjkt0KlB0jwnFB9I4Z4:bnveliu) ([raw file](https://github.com/batfish/batfish/blob/babf59e522aa381e499f81e16dad90b042cf66b9/projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java#L140)):*
> ```Java
>   }
> 
>   private static @Nonnull String toString(ParserRuleContext ctx) {
> ```

Please ditch this. It's dangerous.
The low-level multi-arg toString functions can call getText directly.
___
*[projects/batfish/src/main/java/org/batfish/vendor/a10/representation/A10Configuration.java, line 13 at r3](https://reviewable.io/reviews/batfish/batfish/7400#-MjktMnN3rr5HWWt7hze:-MjktMnODVatw244aAMu:b2wemhx) ([raw file](https://github.com/batfish/batfish/blob/babf59e522aa381e499f81e16dad90b042cf66b9/projects/batfish/src/main/java/org/batfish/vendor/a10/representation/A10Configuration.java#L13)):*
> ```Java
> 
> /** Datamodel class representing an A10 device configuration. */
> public class A10Configuration extends VendorConfiguration {
> ```

`final`
___
*[projects/batfish/src/test/resources/org/batfish/vendor/a10/grammar/testconfigs/hostname, line 1 at r1](https://reviewable.io/reviews/batfish/batfish/7400#-MjkPixi4ROfsCyyzFY8:-Mjktes9-LEwEuTcdj56:b-jyo03n) ([raw file](https://github.com/batfish/batfish/blob/02df7ad1c5060970907f1b9fe62ed163271b66ec/projects/batfish/src/test/resources/org/batfish/vendor/a10/grammar/testconfigs/hostname#L1)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

no standard rancid header afaict, there already is a batfish format header supported, and tested in this PR
</blockquote></details>

Right, so use that header in all test configs.
___
*[tests/aws/topology-example-aws.ref, line 1104 at r2](https://reviewable.io/reviews/batfish/batfish/7400#-MjkdHJu47QF6YVcK23O:-MjktWGeAWAX3ZfW0Ye6:b-rrgnga) ([raw file](https://github.com/batfish/batfish/blob/051930e7d13d0a7417b5a5a502016f9f410bd046/tests/aws/topology-example-aws.ref#L1104)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

keeping enums in alphabetical order results in reordering of a couple refs
</blockquote></details>

oh you didn't change it. ok.

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7400)* status: 20 of 24 files reviewed, 1 unresolved discussion (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java, line 140 at r3](https://reviewable.io/reviews/batfish/batfish/7400#-Mjkt0KlB0jwnFB9I4Z3:-MjkyLlN0TpP1EYBkY9k:b-hfpv0l) ([raw file](https://github.com/batfish/batfish/blob/babf59e522aa381e499f81e16dad90b042cf66b9/projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java#L140)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Please ditch this. It's dangerous.
The low-level multi-arg toString functions can call getText directly.
</blockquote></details>

removed

**Review by arifogel — COMMENTED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7400)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

**Pull request merged**
