### PR TITLE
CP mgmt model: Add interface topology leads-to-internet

### PR DESCRIPTION
**Pull request by corinaminer**
Adds to Checkpoint management VS model to capture `interfaces` field of gateways and servers, and within each interface its name and topology including whether it leads to the internet.

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 27 of 27 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7281)* status: all files reviewed, 6 unresolved discussions (waiting on @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/CpmiHostCkp.java, line 29 at r1](https://reviewable.io/reviews/batfish/batfish/7281#-MiNYmWu6CkUuRKqpbHm:-MiNYmWu6CkUuRKqpbHn:bykukzr) ([raw file](https://github.com/batfish/batfish/blob/af6dcf3d07428c2eec01420dee09af34fae36213/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/CpmiHostCkp.java#L29)):*
> ```Java
>     checkArgument(uid != null, "Missing %s", PROP_UID);
>     List<Interface> ifaces =
>         interfaces != null ? ImmutableList.copyOf(interfaces) : ImmutableList.of();
> ```

I think you can just not include this field at all, and always pass `ImmutableList.of()`. Even if it is ever populated, it is never needed for this class AFAICT. A quick check of some data shows this field absent for `CpmiHostCkp` in the one case I looked at. And we don't need to convert `CpmiHostCkp` devices anyway, which I believe are management devices.

For all other devices, you should probably require it be non-null.
Also, for all of these, you can put the equals, hash, toString, and getter in in `GatewayOrServer:: baseEquals/baseHashcode/baseToString/getInterfaces` to avoid duplication.
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/Interface.java, line 43 at r1](https://reviewable.io/reviews/batfish/batfish/7281#-MiN_F4f5vGfK0NKHL_N:-MiN_F4f5vGfK0NKHL_O:b-cnlm0t) ([raw file](https://github.com/batfish/batfish/blob/af6dcf3d07428c2eec01420dee09af34fae36213/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/Interface.java#L43)):*
> ```Java
>       return true;
>     }
>     if (!(o instanceof Interface)) {
> ```

nit: `else if` is our pattern to save a line after autoformat`
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/InterfaceTopology.java, line 45 at r1](https://reviewable.io/reviews/batfish/batfish/7281#-MiN_RU1AueVrvUMxsWB:-MiN_RU1AueVrvUMxsWC:b-e4kudq) ([raw file](https://github.com/batfish/batfish/blob/af6dcf3d07428c2eec01420dee09af34fae36213/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/InterfaceTopology.java#L45)):*
> ```Java
>   @Override
>   public int hashCode() {
>     return Objects.hash(_leadsToInternet);
> ```

nit: can use `_leadsToInternet.hashCode()` or `Boolean.hashCode` or whatever since there is just a single non-null field.
___
*[projects/batfish/src/test/java/org/batfish/vendor/check_point_management/CpmiGatewayClusterTest.java, line 110 at r1](https://reviewable.io/reviews/batfish/batfish/7281#-MiN_z8O5eb92_Dvf65x:-MiN_z8O5eb92_Dvf65y:b-h10q9d) ([raw file](https://github.com/batfish/batfish/blob/af6dcf3d07428c2eec01420dee09af34fae36213/projects/batfish/src/test/java/org/batfish/vendor/check_point_management/CpmiGatewayClusterTest.java#L110)):*
> ```Java
>                 Ip.ZERO,
>                 "foo",
>                 ImmutableList.of(new Interface("iface", new InterfaceTopology(true))),
> ```

This is unnecessary if you test in `CpmiGatewayCluster`, since you already have an instance above.
___
*[projects/batfish/src/test/java/org/batfish/vendor/check_point_management/CpmiHostCkpTest.java, line 1 at r1](https://reviewable.io/reviews/batfish/batfish/7281#-MiNaOHYAJV_XmaDD2a2:-MiNaOHYAJV_XmaDD2a3:b2kaylh) ([raw file](https://github.com/batfish/batfish/blob/af6dcf3d07428c2eec01420dee09af34fae36213/projects/batfish/src/test/java/org/batfish/vendor/check_point_management/CpmiHostCkpTest.java#L1)):*
> ```Java
> package org.batfish.vendor.check_point_management;
> ```

All of this can be reverted if you follow my other suggestion about not processing interfaces for `CpmiHostCkp`.
___
*[projects/batfish/src/test/java/org/batfish/vendor/check_point_management/InterfaceTest.java, line 40 at r1](https://reviewable.io/reviews/batfish/batfish/7281#-MiNakwdAqVJuOUSiknD:-MiNakwdAqVJuOUSiknE:b-5tr1j0) ([raw file](https://github.com/batfish/batfish/blob/af6dcf3d07428c2eec01420dee09af34fae36213/projects/batfish/src/test/java/org/batfish/vendor/check_point_management/InterfaceTest.java#L40)):*
> ```Java
>         .addEqualityGroup(new Interface("foo", new InterfaceTopology(true)))
>         .addEqualityGroup(new Interface("iface", new InterfaceTopology(false)))
>         .addEqualityGroup(new Object())
> ```

I think @dhalperi) said you never need `new Object()`  because apparently this is automatically done by equals tester.

**Review by arifogel — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7281)* status: all files reviewed, 6 unresolved discussions (waiting on @corinaminer)

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7281)* status: 12 of 27 files reviewed, 1 unresolved discussion (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/CpmiHostCkp.java, line 29 at r1](https://reviewable.io/reviews/batfish/batfish/7281#-MiNYmWu6CkUuRKqpbHm:-MiO7wDWE91DF3bwht3e:b-o0z0ow) ([raw file](https://github.com/batfish/batfish/blob/af6dcf3d07428c2eec01420dee09af34fae36213/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/CpmiHostCkp.java#L29)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

I think you can just not include this field at all, and always pass `ImmutableList.of()`. Even if it is ever populated, it is never needed for this class AFAICT. A quick check of some data shows this field absent for `CpmiHostCkp` in the one case I looked at. And we don't need to convert `CpmiHostCkp` devices anyway, which I believe are management devices.

For all other devices, you should probably require it be non-null.
Also, for all of these, you can put the equals, hash, toString, and getter in in `GatewayOrServer:: baseEquals/baseHashcode/baseToString/getInterfaces` to avoid duplication.
</blockquote></details>

Removed interfaces from `CpmiHostCkp` creator and made it required in other `GatewayOrServer` creators.

Already added `_interfaces` to those `GatewayOrServer` methods (and added getter). I don't think that's duplicated anywhere, but correct me if i'm wrong
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/Interface.java, line 43 at r1](https://reviewable.io/reviews/batfish/batfish/7281#-MiN_F4f5vGfK0NKHL_N:-MiO9Tte8IjFVoDjkMkg:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/af6dcf3d07428c2eec01420dee09af34fae36213/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/Interface.java#L43)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

nit: `else if` is our pattern to save a line after autoformat`
</blockquote></details>

done
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/InterfaceTopology.java, line 45 at r1](https://reviewable.io/reviews/batfish/batfish/7281#-MiN_RU1AueVrvUMxsWB:-MiO9Zxg5r6QJizttWjb:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/af6dcf3d07428c2eec01420dee09af34fae36213/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/InterfaceTopology.java#L45)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

nit: can use `_leadsToInternet.hashCode()` or `Boolean.hashCode` or whatever since there is just a single non-null field.
</blockquote></details>

done
___
*[projects/batfish/src/test/java/org/batfish/vendor/check_point_management/CpmiGatewayClusterTest.java, line 110 at r1](https://reviewable.io/reviews/batfish/batfish/7281#-MiN_z8O5eb92_Dvf65x:-MiO9qjn7ywqcUizUeP1:bsh9p96) ([raw file](https://github.com/batfish/batfish/blob/af6dcf3d07428c2eec01420dee09af34fae36213/projects/batfish/src/test/java/org/batfish/vendor/check_point_management/CpmiGatewayClusterTest.java#L110)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

This is unnecessary if you test in `CpmiGatewayCluster`, since you already have an instance above.
</blockquote></details>

confused -- where else is it tested that `equals()` depends on `_interfaces` for `CpmiGatewayCluster`?

(you could make a case that since that dependency is in `baseEquals`, it would be sufficient to test in just one `GatewayOrServer` class, but that's not what we've been doing)
___
*[projects/batfish/src/test/java/org/batfish/vendor/check_point_management/InterfaceTest.java, line 40 at r1](https://reviewable.io/reviews/batfish/batfish/7281#-MiNakwdAqVJuOUSiknD:-MiO6vIZE7X__g8et4jr:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/af6dcf3d07428c2eec01420dee09af34fae36213/projects/batfish/src/test/java/org/batfish/vendor/check_point_management/InterfaceTest.java#L40)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

I think @dhalperi) said you never need `new Object()`  because apparently this is automatically done by equals tester.
</blockquote></details>

done
___
*[projects/batfish/src/test/java/org/batfish/vendor/check_point_management/CpmiHostCkpTest.java, line 1 at r1](https://reviewable.io/reviews/batfish/batfish/7281#-MiNaOHYAJV_XmaDD2a2:-MiOANwmEz_AAMCqjGV4:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/af6dcf3d07428c2eec01420dee09af34fae36213/projects/batfish/src/test/java/org/batfish/vendor/check_point_management/CpmiHostCkpTest.java#L1)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

All of this can be reverted if you follow my other suggestion about not processing interfaces for `CpmiHostCkp`.
</blockquote></details>

done

**Review by arifogel — COMMENTED** [review]
> Reviewed 15 of 15 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7281)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/CpmiHostCkp.java, line 29 at r1](https://reviewable.io/reviews/batfish/batfish/7281#-MiNYmWu6CkUuRKqpbHm:-MiOCIWm4Lz29p8VxOt3:b26aw20) ([raw file](https://github.com/batfish/batfish/blob/af6dcf3d07428c2eec01420dee09af34fae36213/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/CpmiHostCkp.java#L29)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Removed interfaces from `CpmiHostCkp` creator and made it required in other `GatewayOrServer` creators.

Already added `_interfaces` to those `GatewayOrServer` methods (and added getter). I don't think that's duplicated anywhere, but correct me if i'm wrong
</blockquote></details>

You're fine. I thought I was looking at a different file when I say the updates to `baseEquals`, etc.
Since this happened for two files for me in this review, I think either reviewable was transiently showing me the wrong filename (has happened before), or I just need to be more awake.
___
*[projects/batfish/src/test/java/org/batfish/vendor/check_point_management/CpmiGatewayClusterTest.java, line 110 at r1](https://reviewable.io/reviews/batfish/batfish/7281#-MiN_z8O5eb92_Dvf65x:-MiOBkUJ5HtqEFqclM_6:b-pgdqje) ([raw file](https://github.com/batfish/batfish/blob/af6dcf3d07428c2eec01420dee09af34fae36213/projects/batfish/src/test/java/org/batfish/vendor/check_point_management/CpmiGatewayClusterTest.java#L110)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

confused -- where else is it tested that `equals()` depends on `_interfaces` for `CpmiGatewayCluster`?

(you could make a case that since that dependency is in `baseEquals`, it would be sufficient to test in just one `GatewayOrServer` class, but that's not what we've been doing)
</blockquote></details>

Oh my, I just can't read. This is exactly where to test. I thought I was looking at `GatewaysAndServersTest`.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7281)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/CpmiHostCkp.java, line 29 at r1](https://reviewable.io/reviews/batfish/batfish/7281#-MiNYmWu6CkUuRKqpbHm:-MiOCkcG8neD1c8GzJCG:b-rllyek) ([raw file](https://github.com/batfish/batfish/blob/af6dcf3d07428c2eec01420dee09af34fae36213/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/CpmiHostCkp.java#L29)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

You're fine. I thought I was looking at a different file when I say the updates to `baseEquals`, etc.
Since this happened for two files for me in this review, I think either reviewable was transiently showing me the wrong filename (has happened before), or I just need to be more awake.
</blockquote></details>

say -> saw

**Pull request merged**
