### PR TITLE
FortiOS: VS model `access-list` and `access-list rule`

### PR DESCRIPTION
**Pull request by sfraint**
Add VS model support for `access-list` and `access-list rule`

### CODE REVIEW

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6816)* status: 0 of 13 files reviewed, all discussions resolved (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java, line 2233 at r1](https://reviewable.io/reviews/batfish/batfish/6816#-MX4waM_8iCr5E-vRPkm:-MX4waMa5l-dEi8gvFUb:b-iyfday) ([raw file](https://github.com/batfish/batfish/blob/3baa9b15f80a00f124b3eb7f23a59b5b7608a80a/projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java#L2233)):*
> ```
> // Rules should be in insert order
> ```
still need to update the test to check this

**Review by corinaminer — COMMENTED** [review]
> Reviewed 8 of 13 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6816)* status: all files reviewed, 3 unresolved discussions (waiting on @arifogel and @sfraint)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_access_list.g4, line 23 at r2](https://reviewable.io/reviews/batfish/batfish/6816#-MX8ponwDzJIcxFFeqEz:-MX8ponwDzJIcxFFeqF-:b-45jzcp) ([raw file](https://github.com/batfish/batfish/blob/4b66c57197ea471fc92fc32a54fdb3269356984b/projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_access_list.g4#L23)):*
> ```ANTLR
> cralecr_edit: EDIT acl_rule_number newline cralecre* NEXT newline;
> 
> cralecre: cralecre_set;
> ```

don't we normally put `SET` at this level in the pattern (as in `cralecre: SET cralecre_set`)?
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 1420 at r2](https://reviewable.io/reviews/batfish/batfish/6816#-MX8qzkg3JQ7UJE-f_aD:-MX8qzkg3JQ7UJE-f_aE:b-qweamm) ([raw file](https://github.com/batfish/batfish/blob/4b66c57197ea471fc92fc32a54fdb3269356984b/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L1420)):*
> ```Java
>     if (existing != null) {
>       // Make a clone to edit
>       _currentAccessList = SerializationUtils.clone(existing);
> ```

Are access-lists renameable? If not, you don't really need to clone if access lists aren't renameable. (If they are, then `AccessList` needs a uuid.)

Same question with rules.
___
*[projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java, line 2233 at r1](https://reviewable.io/reviews/batfish/batfish/6816#-MX4waM_8iCr5E-vRPkm:-MX8u10U4mPP-NY-nInZ:bk311tj) ([raw file](https://github.com/batfish/batfish/blob/3baa9b15f80a00f124b3eb7f23a59b5b7608a80a/projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java#L2233)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
> // Rules should be in insert order
> ```
still need to update the test to check this
</blockquote></details>

i think `assertThat(acl1.getRules().keySet(), contains("12", "1", "2"));` covers it -- i believe `keySet()` has its order guaranteed for LinkedHashMaps or any other map with a guaranteed iteration order, and `contains` will confirm the keys are in the specified order.
___
*[projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/access_list, line 20 at r2](https://reviewable.io/reviews/batfish/batfish/6816#-MX8tfYcB_y2ilMOGnQa:-MX8tfYcB_y2ilMOGnQb:b-8z9wea) ([raw file](https://github.com/batfish/batfish/blob/4b66c57197ea471fc92fc32a54fdb3269356984b/projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/access_list#L20)):*
> ```
>             next
>             edit 2
>                 set action permit
> ```

switch one of them to `action deny`?

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6816)* status: 10 of 13 files reviewed, 2 unresolved discussions (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_access_list.g4, line 23 at r2](https://reviewable.io/reviews/batfish/batfish/6816#-MX8ponwDzJIcxFFeqEz:-MX967mp9DisTmkFdxFS:b-sruwgl) ([raw file](https://github.com/batfish/batfish/blob/4b66c57197ea471fc92fc32a54fdb3269356984b/projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_access_list.g4#L23)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

don't we normally put `SET` at this level in the pattern (as in `cralecre: SET cralecre_set`)?
</blockquote></details>

yeah, but I was going for more predictability in rule naming a la slack discussion w/ Dan.
i.e. now rules that have a definition like `TOKEN <subrule>` will be named `<rule_prefix>_token`
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 1420 at r2](https://reviewable.io/reviews/batfish/batfish/6816#-MX8qzkg3JQ7UJE-f_aD:-MX99nJ36MJl8Z6e8E7n:b-y1hnn) ([raw file](https://github.com/batfish/batfish/blob/4b66c57197ea471fc92fc32a54fdb3269356984b/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L1420)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Are access-lists renameable? If not, you don't really need to clone if access lists aren't renameable. (If they are, then `AccessList` needs a uuid.)

Same question with rules.
</blockquote></details>

Neither is renameable - simplified this a bit
___
*[projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java, line 2233 at r1](https://reviewable.io/reviews/batfish/batfish/6816#-MX4waM_8iCr5E-vRPkm:-MX9C94z1CD7Jl9uUrGe:bzadbp9) ([raw file](https://github.com/batfish/batfish/blob/3baa9b15f80a00f124b3eb7f23a59b5b7608a80a/projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java#L2233)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

i think `assertThat(acl1.getRules().keySet(), contains("12", "1", "2"));` covers it -- i believe `keySet()` has its order guaranteed for LinkedHashMaps or any other map with a guaranteed iteration order, and `contains` will confirm the keys are in the specified order.
</blockquote></details>

yep, added that and forgot to resolve this comment from before
___
*[projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/access_list, line 20 at r2](https://reviewable.io/reviews/batfish/batfish/6816#-MX8tfYcB_y2ilMOGnQa:-MX9Bzb323bmb-Kr_cK9:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/4b66c57197ea471fc92fc32a54fdb3269356984b/projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/access_list#L20)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

switch one of them to `action deny`?
</blockquote></details>

done

**Review by corinaminer — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6816#-:-MX9HsWH0MgJYvz7eXlx:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_access_list.g4, line 23 at r2](https://reviewable.io/reviews/batfish/batfish/6816#-MX8ponwDzJIcxFFeqEz:-MX9GYjf0d3vIluI9cbb:b32wtd) ([raw file](https://github.com/batfish/batfish/blob/4b66c57197ea471fc92fc32a54fdb3269356984b/projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_access_list.g4#L23)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

yeah, but I was going for more predictability in rule naming a la slack discussion w/ Dan.
i.e. now rules that have a definition like `TOKEN <subrule>` will be named `<rule_prefix>_token`
</blockquote></details>

ok
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 1420 at r2](https://reviewable.io/reviews/batfish/batfish/6816#-MX8qzkg3JQ7UJE-f_aD:-MX9Gmal00hUtO14BVHn:b-up4pd8) ([raw file](https://github.com/batfish/batfish/blob/4b66c57197ea471fc92fc32a54fdb3269356984b/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L1420)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

Neither is renameable - simplified this a bit
</blockquote></details>

cool. (Although, as Ari pointed out to me, cloning doesn't have anything to do with renaming; and we would have to go back to cloning if we find anything that would cause an access-list edit block to be rejected.)

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6816)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 1420 at r2](https://reviewable.io/reviews/batfish/batfish/6816#-MX8qzkg3JQ7UJE-f_aD:-MX9IJIi7BAJR9BYS8dn:b-iad78s) ([raw file](https://github.com/batfish/batfish/blob/4b66c57197ea471fc92fc32a54fdb3269356984b/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L1420)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

cool. (Although, as Ari pointed out to me, cloning doesn't have anything to do with renaming; and we would have to go back to cloning if we find anything that would cause an access-list edit block to be rejected.)
</blockquote></details>

yep, I don't expect access-lists to be rejected for anything other than invalid names, but we can revert that if we need to :slightly_smiling_face:

**Pull request merged**
