### PR TITLE
Change row type

### PR DESCRIPTION
**Pull request by ratulm**
as you suspected, ObjectNode as the type of row was not a good long-term fit. hiding, mostly not entirely, its internal implementation now.

### CODE REVIEW

**Comment by ratulm** [comment]
Review status: 14 of 15 files reviewed at latest revision, 3 unresolved discussions.

---

*[projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerElement.java, line 122 at r1](https://reviewable.io/reviews/batfish/batfish/1285#-LBarK9j2mqtStqdtNoa:-LBb_hgi1yJKdWXSEcGr:b-1wdk65) ([raw file](https://github.com/batfish/batfish/blob/b18975fc1240491dfbac6cf3d994861843a35102/projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerElement.java#L122)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

Yes, I think it can be done by leveraging the Schema. I am putting that off for now, to invest time in building a few more things on top first. I'll come back and clean it up.
</blockquote></details>

Overhauling now actually. I also had some changes to TableMetadata in mind. Doing those too. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1285)*

**Comment by dhalperi** [comment]
Reviewed 11 of 11 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/ColumnMetadata.java, line 17 at r2](https://reviewable.io/reviews/batfish/batfish/1285#-LBeOrd36R-dUrcp8cdv:-LBeOrd36R-dUrcp8cdw:bgv7yrz) ([raw file](https://github.com/batfish/batfish/blob/58f2c0ddc3b66043e181b2e255e86dc76c42d1b5/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/ColumnMetadata.java#L17)):*
> ```Java
> 
>   @Nonnull private String _description;
>   private boolean _isKey;
> ```

I think (but have not yet confirmed) by moving primary key-ness into here, we have lost ordering for composite keys (more than 1 column). Assuming that's correct, are you okay with that?

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/Row.java, line 67 at r2](https://reviewable.io/reviews/batfish/batfish/1285#-LBeR4-13QgFKeqoDjDH:-LBeR4-13QgFKeqoDjDI:b-mby4f2) ([raw file](https://github.com/batfish/batfish/blob/58f2c0ddc3b66043e181b2e255e86dc76c42d1b5/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/Row.java#L67)):*
> ```Java
>    */
>   public <T> T get(String columnName, Class<T> valueType) throws JsonProcessingException {
>     return BatfishObjectMapper.mapper().treeToValue(_data.get(columnName), valueType);
> ```

Throwing on `get` seems horrible for users -- imagine if you had checked exceptions thrown on all calls to accessing an array!

Can we get all the throwing (and general conversion work) over with only on deserialization/deserialization?

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/Rows.java, line 14 at r1](https://reviewable.io/reviews/batfish/batfish/1285#-LBar1HX1D_Rbm35kSBT:-LBePBfq9T2KTW9nKRNn:b-ju38zd) ([raw file](https://github.com/batfish/batfish/blob/5fc8802c69064c74e37ce0a804dbecdc1681030a/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/Rows.java#L14)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

The sorting is done using Row.compareTo. Yes, the thinking is that rows will eventually be sorted by primary key. But the implementation ignores that for now; haven't really found a use case for that yet, so saving time for now and will fix later.  Made that clear in the javadoc. 
</blockquote></details>

Still would prefer that `Rows` not do the sorting. Is there a strong reason for questions not to be able to choose their own ordering?

Fundamentally, at a data model level answers are bags and are typically not sorted sets.

---

*[projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerElement.java, line 49 at r2](https://reviewable.io/reviews/batfish/batfish/1285#-LBePnjI3j2nmFJmLh9z:-LBePnjI3j2nmFJmLhA-:b-khs04d) ([raw file](https://github.com/batfish/batfish/blob/58f2c0ddc3b66043e181b2e255e86dc76c42d1b5/projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerElement.java#L49)):*
> ```Java
>     columnMetadata.put(
>         COL_LOCAL_IP, new ColumnMetadata("Ip", "The local IP of the session", false, false));
>     columnMetadata.put(COL_NODE, new ColumnMetadata("Node", "Node of the session", true, false));
> ```

local node?

---

*[projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerElement.java, line 49 at r2](https://reviewable.io/reviews/batfish/batfish/1285#-LBeQPYM2sLfd-76vyaC:-LBeQPYM2sLfd-76vyaD:b-r9aicb) ([raw file](https://github.com/batfish/batfish/blob/58f2c0ddc3b66043e181b2e255e86dc76c42d1b5/projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerElement.java#L49)):*
> ```Java
>     columnMetadata.put(
>         COL_LOCAL_IP, new ColumnMetadata("Ip", "The local IP of the session", false, false));
>     columnMetadata.put(COL_NODE, new ColumnMetadata("Node", "Node of the session", true, false));
> ```

My inclination would be to use the `Schema`, not the `String`, constructor here for the first argument of column metadata. Any reason this is not better?

---

*[projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerElement.java, line 55 at r2](https://reviewable.io/reviews/batfish/batfish/1285#-LBeQFml8jDmwf2SvLuC:-LBeQFml8jDmwf2SvLuD:bpochkd) ([raw file](https://github.com/batfish/batfish/blob/58f2c0ddc3b66043e181b2e255e86dc76c42d1b5/projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerElement.java#L55)):*
> ```Java
>             "Boolean", "Whether the session was established on loopback interface", false, true));
>     columnMetadata.put(
>         COL_REMOTE_NODE, new ColumnMetadata("Node", "Remote node for this sessions", false, false));
> ```

singular session?

---

*[projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerElement.java, line 62 at r2](https://reviewable.io/reviews/batfish/batfish/1285#-LBePy9O2B1PMi6kNTFj:-LBePy9O2B1PMi6kNTFk:b5rc16d) ([raw file](https://github.com/batfish/batfish/blob/58f2c0ddc3b66043e181b2e255e86dc76c42d1b5/projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerElement.java#L62)):*
> ```Java
>         COL_SESSION_TYPE, new ColumnMetadata("String", "The type of this session", false, false));
>     columnMetadata.put(
>         COL_VRF_NAME, new ColumnMetadata("String", "The VRF for this session", true, false));
> ```

VRF isn't actually a property of a BGP session, right? What does this mean?

I assume this would be local VRF?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1285)*

**Comment by ratulm** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/ColumnMetadata.java, line 17 at r2](https://reviewable.io/reviews/batfish/batfish/1285#-LBeOrd36R-dUrcp8cdv:-LBhdwarCovT-Wozs-zI:bgoe067) ([raw file](https://github.com/batfish/batfish/blob/58f2c0ddc3b66043e181b2e255e86dc76c42d1b5/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/ColumnMetadata.java#L17)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I think (but have not yet confirmed) by moving primary key-ness into here, we have lost ordering for composite keys (more than 1 column). Assuming that's correct, are you okay with that?
</blockquote></details>

I was since it simplified Metadata initialization, and I don't know of a good use for ordering yet. Also, in some other recent changes (not in this PR) the metadata columns are completely ordered, so that brings ordering back. 

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/Row.java, line 67 at r2](https://reviewable.io/reviews/batfish/batfish/1285#-LBeR4-13QgFKeqoDjDH:-LBhhVT05LctnL3S3smo:bav5fsu) ([raw file](https://github.com/batfish/batfish/blob/58f2c0ddc3b66043e181b2e255e86dc76c42d1b5/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/Row.java#L67)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Throwing on `get` seems horrible for users -- imagine if you had checked exceptions thrown on all calls to accessing an array!

Can we get all the throwing (and general conversion work) over with only on deserialization/deserialization?
</blockquote></details>

That would be nice but would complicate things a bit by requiring the row object to be aware of the Schema (and it would do a bunch of possibly unneeded work). If it helps, the analogy here should be to a Row being a map from String-->Object and the user needs to cast the return value and watch for ClassCastException.  I am inclined to leave this for now and focus on flushing out downstream usage; I'll come back to it later. 

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/Rows.java, line 14 at r1](https://reviewable.io/reviews/batfish/batfish/1285#-LBar1HX1D_Rbm35kSBT:-LBhjQsrEnQSrgqdaXvw:blwag3s) ([raw file](https://github.com/batfish/batfish/blob/5fc8802c69064c74e37ce0a804dbecdc1681030a/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/Rows.java#L14)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Still would prefer that `Rows` not do the sorting. Is there a strong reason for questions not to be able to choose their own ordering?

Fundamentally, at a data model level answers are bags and are typically not sorted sets.
</blockquote></details>

No fundamental reason. I did that to introduce stability for ref checking. I reverted that. As long as questions that are involved in ref checking use a sorted set, we should be fine. No reason for Rows itself to enforce that.

---

*[projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerElement.java, line 49 at r2](https://reviewable.io/reviews/batfish/batfish/1285#-LBeQPYM2sLfd-76vyaC:-LBhk5_OAfP1uA7L3ZEJ:bbjjqa0) ([raw file](https://github.com/batfish/batfish/blob/58f2c0ddc3b66043e181b2e255e86dc76c42d1b5/projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerElement.java#L49)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

My inclination would be to use the `Schema`, not the `String`, constructor here for the first argument of column metadata. Any reason this is not better?
</blockquote></details>

Compact code is the only reason ("Ip" versus new Schema("Ip")). I can change if you feel strongly about it. 

---

*[projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerElement.java, line 49 at r2](https://reviewable.io/reviews/batfish/batfish/1285#-LBePnjI3j2nmFJmLh9z:-LBhkVAC84SEP36XNFnT:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/58f2c0ddc3b66043e181b2e255e86dc76c42d1b5/projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerElement.java#L49)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

local node?
</blockquote></details>

Done.

---

*[projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerElement.java, line 55 at r2](https://reviewable.io/reviews/batfish/batfish/1285#-LBeQFml8jDmwf2SvLuC:-LBhkXJr5hqDsYlIWxaF:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/58f2c0ddc3b66043e181b2e255e86dc76c42d1b5/projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerElement.java#L55)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

singular session?
</blockquote></details>

Done.

---

*[projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerElement.java, line 62 at r2](https://reviewable.io/reviews/batfish/batfish/1285#-LBePy9O2B1PMi6kNTFj:-LBhkiCzC_hwn6CbgXB3:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/58f2c0ddc3b66043e181b2e255e86dc76c42d1b5/projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionStatusAnswerElement.java#L62)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

VRF isn't actually a property of a BGP session, right? What does this mean?

I assume this would be local VRF?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1285)*

**Comment by ratulm** [comment]
Review status: 15 of 19 files reviewed at latest revision, 7 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/Row.java, line 67 at r2](https://reviewable.io/reviews/batfish/batfish/1285#-LBeR4-13QgFKeqoDjDH:-LBiTWmX2kbluzMkLFHn:b-2tz8lf) ([raw file](https://github.com/batfish/batfish/blob/58f2c0ddc3b66043e181b2e255e86dc76c42d1b5/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/Row.java#L67)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

That would be nice but would complicate things a bit by requiring the row object to be aware of the Schema (and it would do a bunch of possibly unneeded work). If it helps, the analogy here should be to a Row being a map from String-->Object and the user needs to cast the return value and watch for ClassCastException.  I am inclined to leave this for now and focus on flushing out downstream usage; I'll come back to it later. 
</blockquote></details>

I suppose throwing a RuntimeException be better here in the meanwhile. I'll move to that.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1285)*

**Comment by dhalperi** [comment]
:lgtm: Sorry for delay -- traveling.

---

Reviewed 15 of 15 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1285#-:-LBnonPR66FGQvcjlm08:b2l5mdc)*

**Pull request merged**
