### PR TITLE
BGP propagate all withdrawals 

### PR DESCRIPTION
**Pull request by arifogel**
- previously, we were not propagating withdrawals BGP routes in the
  default case (non-advertise-external, non-advertise-inactive)

Co-authored-by: Daniel Halperin <dan@intentionet.com>
Co-authored-by: Ari Fogel <ari@fogelti.me>

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7403)* status: 9 of 18 files reviewed, all discussions resolved (waiting on @arifogel)

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7403)* status: 9 of 18 files reviewed, 1 unresolved discussion (waiting on @arifogel)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7403#-MjlqzE02XH1NsfZKt7o:-MjlqzE02XH1NsfZKt7p:bkpqf40) (no related file):*
After batfish/batfish#7402

---

**Review by dhalperi — COMMENTED** [review]
> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7403)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7403)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7403)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7403#-MjpKMc1-3luJtN-QdvE:-MjpKMc1-3luJtN-QdvF:b2ufzct) (no related file):*
Still working on local fix and modfiied test.

---

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7403)* status: 11 of 20 files reviewed, 1 unresolved discussion (waiting on @arifogel and @dhalperi)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7403#-MjpKMc1-3luJtN-QdvE:-Mjpm5Zn9zWsk5JCWNa1:bkojotz) (no related file):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Still working on local fix and modfiied test.
</blockquote></details>

testing downstream

---

**Review by dhalperi — COMMENTED** [review]
> Reviewed 8 of 10 files at r1, 7 of 9 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7403)* status: 19 of 20 files reviewed, 1 unresolved discussion (waiting on @arifogel and @dhalperi)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 9 files at r4, 8 of 8 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7403)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel)

**Review by arifogel — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7403)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel)

**Pull request merged**
