### PR TITLE
Including RDS in aws representation

### PR DESCRIPTION
**Pull request by haverma**
Includes:
1)changes for RDS instance
2)changes for allocation of unique Ips from subnet CIDR

---
This change is [Reviewable](https://reviewable.io/reviews/batfish/batfish/872)

### CODE REVIEW

**Comment by ratulm** [comment]
Looks great. 

One question: Possible to add an end-to-end test that shows reachability for the RDS instance? Will test the internal plumbing. 

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/872#-:-L3dEfOiBigL1B75AS_M:bj67ocm)*

**Comment by arifogel** [comment]
Needs some cleanup. I agree with @ratulm that something a bit more end-to-end would may be useful.
I believe there are existing junit tests for AWS networks wrt `Instance`s and `VpnGateway`s you can work from, or possibly extend.

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 13 unresolved discussions, all commit checks successful.

---

*[a discussion](https://reviewable.io:443/reviews/batfish/batfish/872#-L3daxukFvVz7UPyKo6I:-L3daxulUGXi2o3Nxj3u:b-twjusp) (no related file):*
Meta-question: Why aren't we using Jackson for all of this?

---

*[projects/batfish/src/main/java/org/batfish/representation/aws/RdsInstance.java, line 57 at r1](https://reviewable.io:443/reviews/batfish/batfish/872#-L3daAcvpr9R6vDh3Azj:-L3daAcvpr9R6vDh3Azk:b-e6fe4b) ([raw file](https://github.com/batfish/batfish/blob/b83ad7bef62c8b270968690471afa654ee38b900/projects/batfish/src/main/java/org/batfish/representation/aws/RdsInstance.java#L57)):*
> ```Java
>     _multiAz = jObj.getBoolean(JSON_KEY_MULTI_AZ);
>     if (jObj.getString(JSON_KEY_DB_INSTANCE_STATUS).toLowerCase().equals("available")) {
>       _dbInstanceStatus = Status.AVAILABLE;
> ```

What is the value of `_dbInstanceStatus` if the guard isn't true?

---

*[projects/batfish/src/main/java/org/batfish/representation/aws/RdsInstance.java, line 100 at r1](https://reviewable.io:443/reviews/batfish/batfish/872#-L3dbDFY52XhgoVt71QT:-L3dbDFY52XhgoVt71QU:bxphtxj) ([raw file](https://github.com/batfish/batfish/blob/b83ad7bef62c8b270968690471afa654ee38b900/projects/batfish/src/main/java/org/batfish/representation/aws/RdsInstance.java#L100)):*
> ```Java
>     for (int index = 0; index < securityGroupsArray.length(); index++) {
>       JSONObject securityGroup = securityGroupsArray.getJSONObject(index);
>       if (securityGroup.getString(JSON_KEY_STATUS).equals("active")) {
> ```

Should we be case-sensitive here? This is inconsistent with below.

---

*[projects/batfish/src/main/java/org/batfish/representation/aws/RdsInstance.java, line 109 at r1](https://reviewable.io:443/reviews/batfish/batfish/872#-L3db3jhJ4eT-N9nvX65:-L3db3jhJ4eT-N9nvX66:bx6uvh7) ([raw file](https://github.com/batfish/batfish/blob/b83ad7bef62c8b270968690471afa654ee38b900/projects/batfish/src/main/java/org/batfish/representation/aws/RdsInstance.java#L109)):*
> ```Java
>     for (int i = 0; i < subnetsArray.length(); i++) {
>       JSONObject subnet = subnetsArray.getJSONObject(i);
>       if (subnet.getString(JSON_KEY_SUBNET_STATUS).equals("Active")) {
> ```

Should we be case-sensitive here? This is inconsistent with above.

---

*[projects/batfish/src/main/java/org/batfish/representation/aws/RdsInstance.java, line 139 at r1](https://reviewable.io:443/reviews/batfish/batfish/872#-L3dbd9860Mkuz20EnO6:-L3dbd9860Mkuz20EnO7:b-o4ueyv) ([raw file](https://github.com/batfish/batfish/blob/b83ad7bef62c8b270968690471afa654ee38b900/projects/batfish/src/main/java/org/batfish/representation/aws/RdsInstance.java#L139)):*
> ```Java
>     _outAcl = new IpAccessList(sgEgressAclName, outboundRules);
>     cfgNode.getIpAccessLists().put(sgIngressAclName, _inAcl);
>     cfgNode.getIpAccessLists().put(sgEgressAclName, _outAcl);
> ```

Why is any of this generation code here? Aren't security groups independent of RDS instances? Why generate these ACLs for everything that uses them?

---

*[projects/batfish/src/main/java/org/batfish/representation/aws/RdsInstance.java, line 151 at r1](https://reviewable.io:443/reviews/batfish/batfish/872#-L3dc4-32_sD0N4sX-iS:-L3dc4-32_sD0N4sX-iT:binhs8z) ([raw file](https://github.com/batfish/batfish/blob/b83ad7bef62c8b270968690471afa654ee38b900/projects/batfish/src/main/java/org/batfish/representation/aws/RdsInstance.java#L151)):*
> ```Java
>       Subnet subnet = region.getSubnets().get(subnetId);
>       String instancesIfaceName = String.format("%s-%s", _dbInstanceIdentifier, subnetId);
>       Ip instancesIfaceIp = subnet.getNextIp();
> ```

How do you know no one is using this IP?

---

*[projects/batfish/src/main/java/org/batfish/representation/aws/Region.java, line 248 at r1](https://reviewable.io:443/reviews/batfish/batfish/872#-L3deRgeq-NbyHglkPkJ:-L3deRgeq-NbyHglkPkK:bd4mtu5) ([raw file](https://github.com/batfish/batfish/blob/b83ad7bef62c8b270968690471afa654ee38b900/projects/batfish/src/main/java/org/batfish/representation/aws/Region.java#L248)):*
> ```Java
>       AwsConfiguration awsConfiguration, Map<String, Configuration> configurationNodes) {
> 
>     // updating the list of allocated IPs in the subnet
> ```

What subnet? Isn't there more than one?

---

*[projects/batfish/src/main/java/org/batfish/representation/aws/Region.java, line 304 at r1](https://reviewable.io:443/reviews/batfish/batfish/872#-L3deDuL-1Q4XzIfZjTz:-L3dd-v5LuFHb_VQaacq:b47uhuf) ([raw file](https://github.com/batfish/batfish/blob/b83ad7bef62c8b270968690471afa654ee38b900/projects/batfish/src/main/java/org/batfish/representation/aws/Region.java#L304)):*
> ```Java
>   }
> 
>   // updates the Ips which have been allocated already in the subnet
> ```

This doesn't provide any more information than the comment in the caller.

---

*[projects/batfish/src/main/java/org/batfish/representation/aws/Region.java, line 316 at r1](https://reviewable.io:443/reviews/batfish/batfish/872#-L3dcpaDfpy_KycSQY_D:-L3dcpaDfpy_KycSQY_E:bbdw2np) ([raw file](https://github.com/batfish/batfish/blob/b83ad7bef62c8b270968690471afa654ee38b900/projects/batfish/src/main/java/org/batfish/representation/aws/Region.java#L316)):*
> ```Java
>                       .keySet()
>                       .stream()
>                       .map(ip -> ip.asLong())
> ```

`ip -> ip.asLong()` -> `Ip::asLong`

---

*[projects/batfish/src/main/java/org/batfish/representation/aws/Region.java, line 318 at r1](https://reviewable.io:443/reviews/batfish/batfish/872#-L3depFS9Aww96kGk8Rm:-L3depFS9Aww96kGk8Rn:b-iwrjju) ([raw file](https://github.com/batfish/batfish/blob/b83ad7bef62c8b270968690471afa654ee38b900/projects/batfish/src/main/java/org/batfish/representation/aws/Region.java#L318)):*
> ```Java
>                       .map(ip -> ip.asLong())
>                       .collect(Collectors.toSet());
>               _subnets.get(networkInterface.getSubnetId()).getAllocatedIps().addAll(privateIpsLong);
> ```

`privateIpsLong` can be replaced with its definition inline, and the braces and semicolon can be removed.

---

*[projects/batfish/src/test/java/org/batfish/representation/aws/RdsInstanceTest.java, line 33 at r1](https://reviewable.io:443/reviews/batfish/batfish/872#-L3dff-f4PomzFkE1CI9:-L3dff-f4PomzFkE1CIA:bbbjefs) ([raw file](https://github.com/batfish/batfish/blob/b83ad7bef62c8b270968690471afa654ee38b900/projects/batfish/src/test/java/org/batfish/representation/aws/RdsInstanceTest.java#L33)):*
> ```Java
> 
>     // checking the count of RDS initialized
>     assertThat(rdsList.size(), equalTo(1));
> ```

For better messages, change to:
`assertThat(rdsList, hasSize(1));`

---

*[projects/batfish/src/test/java/org/batfish/representation/aws/RdsInstanceTest.java, line 46 at r1](https://reviewable.io:443/reviews/batfish/batfish/872#-L3dftS_uJLcjWHpTFPK:-L3dftS_uJLcjWHpTFPL:b-dvij8t) ([raw file](https://github.com/batfish/batfish/blob/b83ad7bef62c8b270968690471afa654ee38b900/projects/batfish/src/test/java/org/batfish/representation/aws/RdsInstanceTest.java#L46)):*
> ```Java
>     assertThat(rdsInstance.getSecurityGroups(), equalTo(ImmutableList.of("sg-12345")));
>     assertThat(rdsInstance.getMultiAz(), equalTo(false));
>     assertThat(rdsInstance.getVpcId(), equalTo("vpc-1"));
> ```

Please create feature matchers for all of these properties, and use them instead of checking the values of the features directly.
See e.g. `BgpAdvertisementMatchers` and `BgpAdvertisementMatchersImpl`.

Keep the new matchers in the `batfish` project.

---

*[projects/batfish/src/test/java/org/batfish/representation/aws/SubnetTest.java, line 42 at r1](https://reviewable.io:443/reviews/batfish/batfish/872#-L3dgHpfIp2m0hYbkXgl:-L3dgHpg3Y4Gdwum76Wu:b-dvij8t) ([raw file](https://github.com/batfish/batfish/blob/b83ad7bef62c8b270968690471afa654ee38b900/projects/batfish/src/test/java/org/batfish/representation/aws/SubnetTest.java#L42)):*
> ```Java
>     assertThat(subnet.getCidrBlock(), equalTo(Prefix.parse("172.31.0.0/20")));
>     assertThat(subnet.getId(), equalTo("subnet-1"));
>     assertThat(subnet.getVpcId(), equalTo("vpc-1"));
> ```

Please create feature matchers for all of these properties, and use them instead of checking the values of the features directly.
See e.g. `BgpAdvertisementMatchers` and `BgpAdvertisementMatchersImpl`.

Keep the new matchers in the `batfish` project.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/872#-:-L3dgRPWzvfVifeRdq6m:bt7vnpr)*

**Comment by arifogel** [comment]
Review status: 7 of 10 files reviewed at latest revision, 14 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/representation/aws/Subnet.java, line 50 at r2](https://reviewable.io:443/reviews/batfish/batfish/872#-L3dhz1rXoTN5RkP-YTV:-L3dhz1rXoTN5RkP-YTW:b-97mlwr) ([raw file](https://github.com/batfish/batfish/blob/e2c32947c1b95ed6530caf32b9d80be8e4cc1499/projects/batfish/src/main/java/org/batfish/representation/aws/Subnet.java#L50)):*
> ```Java
>   Ip getNextIp() {
>     // skipping (startIp+1) as it is used as the default gateway for instances in this subnet
>     for (Long ipAsLong = _cidrBlock.getStartIp().asLong() + 2;
> ```

Instead of starting at beginning, start at last generated IP. Reduces from O(n^2) to O(n).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/872)*

**Comment by arifogel** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/872)*

**Comment by arifogel** [comment]
Reviewed 9 of 9 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/872)*

**Comment by arifogel** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/872)*

**Comment by haverma** [comment]
@ratulm, I have added tests in RDSInstanceTest class to test connection of RDS to subnet node and existence of default routes, also to check if IPs allocated to RDS were unique

---

Review status: 15 of 23 files reviewed at latest revision, 12 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/batfish/batfish/872#-L3daxukFvVz7UPyKo6I:-L3gAydE5EeKGc4gMXAy:b-ls39pd) (no related file):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Meta-question: Why aren't we using Jackson for all of this?
</blockquote></details>

I think we continued using Jettison for all the aws json configuration deserialization, opened ticket https://github.com/batfish/batfish/issues/875 for this 

---

*[projects/batfish/src/main/java/org/batfish/representation/aws/RdsInstance.java, line 57 at r1](https://reviewable.io:443/reviews/batfish/batfish/872#-L3daAcvpr9R6vDh3Azj:-L3gCQEQC5Ywcdtn7sIc:brhjwme) ([raw file](https://github.com/batfish/batfish/blob/b83ad7bef62c8b270968690471afa654ee38b900/projects/batfish/src/main/java/org/batfish/representation/aws/RdsInstance.java#L57)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

What is the value of `_dbInstanceStatus` if the guard isn't true?
</blockquote></details>

it will be Status.UNAVAILABLE for all other values as there were lots of possible states so I tried encompassing all of them with this.
 https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Overview.DBInstance.Status.html

---

*[projects/batfish/src/main/java/org/batfish/representation/aws/RdsInstance.java, line 100 at r1](https://reviewable.io:443/reviews/batfish/batfish/872#-L3dbDFY52XhgoVt71QT:-L3gCsq-F2PwEflB4ITW:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/b83ad7bef62c8b270968690471afa654ee38b900/projects/batfish/src/main/java/org/batfish/representation/aws/RdsInstance.java#L100)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Should we be case-sensitive here? This is inconsistent with below.
</blockquote></details>

done

---

*[projects/batfish/src/main/java/org/batfish/representation/aws/RdsInstance.java, line 109 at r1](https://reviewable.io:443/reviews/batfish/batfish/872#-L3db3jhJ4eT-N9nvX65:-L3gCtzw12QgLkKr3dVk:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/b83ad7bef62c8b270968690471afa654ee38b900/projects/batfish/src/main/java/org/batfish/representation/aws/RdsInstance.java#L109)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Should we be case-sensitive here? This is inconsistent with above.
</blockquote></details>

done

---

*[projects/batfish/src/main/java/org/batfish/representation/aws/Region.java, line 248 at r1](https://reviewable.io:443/reviews/batfish/batfish/872#-L3deRgeq-NbyHglkPkJ:-L3gCuuG8-t0LkSLwpPy:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/b83ad7bef62c8b270968690471afa654ee38b900/projects/batfish/src/main/java/org/batfish/representation/aws/Region.java#L248)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

What subnet? Isn't there more than one?
</blockquote></details>

done

---

*[projects/batfish/src/main/java/org/batfish/representation/aws/Region.java, line 304 at r1](https://reviewable.io:443/reviews/batfish/batfish/872#-L3deDuL-1Q4XzIfZjTz:-L3gCyIZj2J1eD9pICL3:b-hfpv0l) ([raw file](https://github.com/batfish/batfish/blob/b83ad7bef62c8b270968690471afa654ee38b900/projects/batfish/src/main/java/org/batfish/representation/aws/Region.java#L304)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

This doesn't provide any more information than the comment in the caller.
</blockquote></details>

removed

---

*[projects/batfish/src/main/java/org/batfish/representation/aws/Region.java, line 316 at r1](https://reviewable.io:443/reviews/batfish/batfish/872#-L3dcpaDfpy_KycSQY_D:-L3gCzL1aBHOwIBoSOY7:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/b83ad7bef62c8b270968690471afa654ee38b900/projects/batfish/src/main/java/org/batfish/representation/aws/Region.java#L316)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

`ip -> ip.asLong()` -> `Ip::asLong`
</blockquote></details>

done

---

*[projects/batfish/src/main/java/org/batfish/representation/aws/Region.java, line 318 at r1](https://reviewable.io:443/reviews/batfish/batfish/872#-L3depFS9Aww96kGk8Rm:-L3gD-BffTkjcsAF0Yqc:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/b83ad7bef62c8b270968690471afa654ee38b900/projects/batfish/src/main/java/org/batfish/representation/aws/Region.java#L318)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

`privateIpsLong` can be replaced with its definition inline, and the braces and semicolon can be removed.
</blockquote></details>

done

---

*[projects/batfish/src/main/java/org/batfish/representation/aws/Subnet.java, line 50 at r2](https://reviewable.io:443/reviews/batfish/batfish/872#-L3dhz1rXoTN5RkP-YTV:-L3gD3cp72LIznT6h_t1:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/e2c32947c1b95ed6530caf32b9d80be8e4cc1499/projects/batfish/src/main/java/org/batfish/representation/aws/Subnet.java#L50)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Instead of starting at beginning, start at last generated IP. Reduces from O(n^2) to O(n).
</blockquote></details>

done

---

*[projects/batfish/src/test/java/org/batfish/representation/aws/RdsInstanceTest.java, line 33 at r1](https://reviewable.io:443/reviews/batfish/batfish/872#-L3dff-f4PomzFkE1CI9:-L3gDav-pbg-MJdUX1gY:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/b83ad7bef62c8b270968690471afa654ee38b900/projects/batfish/src/test/java/org/batfish/representation/aws/RdsInstanceTest.java#L33)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

For better messages, change to:
`assertThat(rdsList, hasSize(1));`
</blockquote></details>

done

---

*[projects/batfish/src/test/java/org/batfish/representation/aws/RdsInstanceTest.java, line 46 at r1](https://reviewable.io:443/reviews/batfish/batfish/872#-L3dftS_uJLcjWHpTFPK:-L3gDc410XDYw715ERj7:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/b83ad7bef62c8b270968690471afa654ee38b900/projects/batfish/src/test/java/org/batfish/representation/aws/RdsInstanceTest.java#L46)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Please create feature matchers for all of these properties, and use them instead of checking the values of the features directly.
See e.g. `BgpAdvertisementMatchers` and `BgpAdvertisementMatchersImpl`.

Keep the new matchers in the `batfish` project.
</blockquote></details>

done

---

*[projects/batfish/src/test/java/org/batfish/representation/aws/SubnetTest.java, line 42 at r1](https://reviewable.io:443/reviews/batfish/batfish/872#-L3dgHpfIp2m0hYbkXgl:-L3gDd23qzuVna8oDj94:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/b83ad7bef62c8b270968690471afa654ee38b900/projects/batfish/src/test/java/org/batfish/representation/aws/SubnetTest.java#L42)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Please create feature matchers for all of these properties, and use them instead of checking the values of the features directly.
See e.g. `BgpAdvertisementMatchers` and `BgpAdvertisementMatchersImpl`.

Keep the new matchers in the `batfish` project.
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/872#-:-L3gAezNp3mqhAAzwMEn:br26pe7)*

**Comment by haverma** [comment]
Done some changes

---

Review status: 22 of 23 files reviewed at latest revision, 3 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/representation/aws/RdsInstance.java, line 57 at r1](https://reviewable.io:443/reviews/batfish/batfish/872#-L3daAcvpr9R6vDh3Azj:-L3ivrEPLOgvV4g9m16V:b-5fxsb2) ([raw file](https://github.com/batfish/batfish/blob/b83ad7bef62c8b270968690471afa654ee38b900/projects/batfish/src/main/java/org/batfish/representation/aws/RdsInstance.java#L57)):*
> private Status _dbInstanceStatus = Status.UNAVAILABLE;
I am assigning a default value to it as Status.UNAVAILABLE while declaring it, thought it would be cleaner

---

*[projects/batfish/src/test/java/org/batfish/representation/aws/RdsInstanceTest.java, line 132 at r5](https://reviewable.io:443/reviews/batfish/batfish/872#-L3inB_FD_H7HNylOKXd:-L3izuOjL4ES_2jWdQET:b8vm0sx) ([raw file](https://github.com/batfish/batfish/blob/f1624ecf1d27b803b52b490b4011764da5de1ee3/projects/batfish/src/test/java/org/batfish/representation/aws/RdsInstanceTest.java#L132)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

This test is a little confusing.
Why not collect the IPs of all interfaces into a list. Then convert to set, and make sure they have the same size?
Something like:
```
List<Ip> ipsAsList = configurations.values();.stream().map(Configuration::getInterfaces).map(Map::values).flatMap(Collection::stream).map(Interface::getAllAddresses).flatMap(Collection::stream).map(NetworkAddress::getIp).collect(ImmutableList.toImmutableList());
Set<Ip> ipsAsSet = ImmutableSet.copyOf(ipsAsList);
assertThat(ipsAsList, hasSize(ipsAsSet.size());
```
</blockquote></details>

replaced with suggested snippet

---

*[projects/batfish/src/test/java/org/batfish/representation/aws/RdsInstanceTest.java, line 139 at r5](https://reviewable.io:443/reviews/batfish/batfish/872#-L3ioUr_1b4MnPIxVdB-:-L3ixSUE9zal-B580t4C:bslb8r1) ([raw file](https://github.com/batfish/batfish/blob/f1624ecf1d27b803b52b490b4011764da5de1ee3/projects/batfish/src/test/java/org/batfish/representation/aws/RdsInstanceTest.java#L139)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

What a strange `nextHopIp`. Are you sure that is the intended default gateway (subnet router)? I thought it was supposed to be the second address in the subnet.
</blockquote></details>

It is the first Ip in the subnet as is being returned by computeInstanceIfaceIp() function of Subnet.java, that is why Subnet::nextIp was starting from the second Ip in the subnet(now it starts from lastGeneratedIp+1)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/872#-:-L3j-YsZKyNCWhISAo33:bi4rvn4)*

**Comment by arifogel** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/representation/aws/RdsInstance.java, line 57 at r1](https://reviewable.io:443/reviews/batfish/batfish/872#-L3daAcvpr9R6vDh3Azj:-L3j07AXW1DCwRYdvDPl:b-ws665t) ([raw file](https://github.com/batfish/batfish/blob/b83ad7bef62c8b270968690471afa654ee38b900/projects/batfish/src/main/java/org/batfish/representation/aws/RdsInstance.java#L57)):*
<details><summary><i>Previously, haverma (Harsh Verma) wrote…</i></summary><blockquote>

> private Status _dbInstanceStatus = Status.UNAVAILABLE;
I am assigning a default value to it as Status.UNAVAILABLE while declaring it, thought it would be cleaner
</blockquote></details>

OK, my mistake. That's not the pattern in the rest of the project, but it is the pattern in this package .

---

*[projects/batfish/src/test/java/org/batfish/representation/aws/RdsInstanceTest.java, line 139 at r5](https://reviewable.io:443/reviews/batfish/batfish/872#-L3ioUr_1b4MnPIxVdB-:-L3j2ZtVI9n17Qb53hI1:b-iwbp96) ([raw file](https://github.com/batfish/batfish/blob/f1624ecf1d27b803b52b490b4011764da5de1ee3/projects/batfish/src/test/java/org/batfish/representation/aws/RdsInstanceTest.java#L139)):*
<details><summary><i>Previously, haverma (Harsh Verma) wrote…</i></summary><blockquote>

It is the first Ip in the subnet as is being returned by computeInstanceIfaceIp() function of Subnet.java, that is why Subnet::nextIp was starting from the second Ip in the subnet(now it starts from lastGeneratedIp+1)
</blockquote></details>

Misread the json file. Looks good.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/872#-:-L3j2fFYKH69Keh9V-A6:bnfp4nl)*

**Pull request merged**
