### PR TITLE
Add the IpOwners question in the new table format

### PR DESCRIPTION
**Pull request by progwriter**
"Proper" version of #1291 
- Add the new question, with the `duplicatesOnly` flag, which can function as uniqueIpAssignments
- Return table containing IP and node, vrf, and interface names

### CODE REVIEW

**Comment by ratulm** [comment]
Looks good. Some small suggestions. 

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/question/src/main/java/org/batfish/question/ipowners/IpOwnersAnswerElement.java, line 43 at r1](https://reviewable.io/reviews/batfish/batfish/1452#-LD46EmM9GmOyUJb7eMI:-LD46EmM9GmOyUJb7eMJ:bs6b9up) ([raw file](https://github.com/batfish/batfish/blob/df3d4d959abf3d1640d56aa6334a006a59d867a9/projects/question/src/main/java/org/batfish/question/ipowners/IpOwnersAnswerElement.java#L43)):*
> ```Java
>   private static List<ColumnMetadata> getColumnMetadata() {
>     return ImmutableList.of(
>         new ColumnMetadata(COL_HOSTNAME, Schema.STRING, "Node hostname"),
> ```

It'll perhaps be better for the clients to consume if the Schema were Node. During insertion, you can easily build a node, using new Node(hostname)

---

*[projects/question/src/main/java/org/batfish/question/ipowners/IpOwnersQuestion.java, line 20 at r1](https://reviewable.io/reviews/batfish/batfish/1452#-LD48y1b-k24mpxFipxs:-LD48y1b-k24mpxFipxt:b-1uaczz) ([raw file](https://github.com/batfish/batfish/blob/df3d4d959abf3d1640d56aa6334a006a59d867a9/projects/question/src/main/java/org/batfish/question/ipowners/IpOwnersQuestion.java#L20)):*
> ```Java
> 
>   /** Whether to exclude inactive interfaces from the computation */
>   private boolean _excludeInactive;
> ```

My suggestion would be to get rid of this flag and dump all IPs, along with a field that indicates if the IP is active or not. We are trying to get to a world where we have "wide" basic tables, and other analysis or view generation happens downstream. 

---

*[projects/question/src/test/java/org/batfish/question/ipowners/IpOwnersAnswererTest.java, line 26 at r1](https://reviewable.io/reviews/batfish/batfish/1452#-LD48VN36apcHR3VUGxw:-LD48VN36apcHR3VUGxx:b-r94m5t) ([raw file](https://github.com/batfish/batfish/blob/df3d4d959abf3d1640d56aa6334a006a59d867a9/projects/question/src/test/java/org/batfish/question/ipowners/IpOwnersAnswererTest.java#L26)):*
> ```Java
>   private Ip _noOwnersIp = new Ip("3.3.3.3");
>   private Map<Ip, Map<String, Set<String>>> _ownersMap;
>   private Map<Ip, Map<String, Set<String>>> _interaceMap;
> ```

inter*f*aceMap?

---

*[projects/question/src/test/java/org/batfish/question/ipowners/IpOwnersAnswererTest.java, line 60 at r1](https://reviewable.io/reviews/batfish/batfish/1452#-LD48ALv44xWbYaW69c_:-LD48ALv44xWbYaW69ca:b-2pogfd) ([raw file](https://github.com/batfish/batfish/blob/df3d4d959abf3d1640d56aa6334a006a59d867a9/projects/question/src/test/java/org/batfish/question/ipowners/IpOwnersAnswererTest.java#L60)):*
> ```Java
>     // Do generation for actual data, expect three rows, one for _uniqueIP, two for _duplicateIp
>     rows = IpOwnersAnswerer.generateRows(_ownersMap, _interaceMap, false);
>     assertThat(rows, hasSize(3));
> ```

Check for exact expected set to make it water tight?  assertThat(rows, equalTo(ImmutableMultiset.of(.....) 

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1452#-:-LD49Uzd6LBlGjv_S3mg:b-izt6tg)*

**Comment by dhalperi** [comment]
Happy to take a pass after Ratul approves if needed (or any other review help if needed), but removing myself for now under assumption Ratul's already doing it.

**Comment by progwriter** [comment]
Review status: 2 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[projects/question/src/main/java/org/batfish/question/ipowners/IpOwnersAnswerElement.java, line 43 at r1](https://reviewable.io/reviews/batfish/batfish/1452#-LD46EmM9GmOyUJb7eMI:-LD50qik7dMrdzsWySCM:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/df3d4d959abf3d1640d56aa6334a006a59d867a9/projects/question/src/main/java/org/batfish/question/ipowners/IpOwnersAnswerElement.java#L43)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

It'll perhaps be better for the clients to consume if the Schema were Node. During insertion, you can easily build a node, using new Node(hostname)
</blockquote></details>

Done.

---

*[projects/question/src/main/java/org/batfish/question/ipowners/IpOwnersQuestion.java, line 20 at r1](https://reviewable.io/reviews/batfish/batfish/1452#-LD48y1b-k24mpxFipxs:-LD50QX-1hgoGb2TQbuk:bitjlol) ([raw file](https://github.com/batfish/batfish/blob/df3d4d959abf3d1640d56aa6334a006a59d867a9/projects/question/src/main/java/org/batfish/question/ipowners/IpOwnersQuestion.java#L20)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

My suggestion would be to get rid of this flag and dump all IPs, along with a field that indicates if the IP is active or not. We are trying to get to a world where we have "wide" basic tables, and other analysis or view generation happens downstream. 
</blockquote></details>

Done. Resulted in some changes to the answerer, but functionality should be the same. 

---

*[projects/question/src/test/java/org/batfish/question/ipowners/IpOwnersAnswererTest.java, line 26 at r1](https://reviewable.io/reviews/batfish/batfish/1452#-LD48VN36apcHR3VUGxw:-LD50QrS1rbEVRJA_624:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/df3d4d959abf3d1640d56aa6334a006a59d867a9/projects/question/src/test/java/org/batfish/question/ipowners/IpOwnersAnswererTest.java#L26)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

inter*f*aceMap?
</blockquote></details>

Done.

---

*[projects/question/src/test/java/org/batfish/question/ipowners/IpOwnersAnswererTest.java, line 60 at r1](https://reviewable.io/reviews/batfish/batfish/1452#-LD48ALv44xWbYaW69c_:-LD50Rc26aBlUfKnXI--:b6b3hf0) ([raw file](https://github.com/batfish/batfish/blob/df3d4d959abf3d1640d56aa6334a006a59d867a9/projects/question/src/test/java/org/batfish/question/ipowners/IpOwnersAnswererTest.java#L60)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

Check for exact expected set to make it water tight?  assertThat(rows, equalTo(ImmutableMultiset.of(.....) 
</blockquote></details>

Done, slightly differently. To avoid tons of boilerplate code, checking counts of both IPs.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1452)*

**Comment by progwriter** [comment]
Review status: 5 of 7 files reviewed at latest revision, all discussions resolved.

---

*[projects/question/src/main/java/org/batfish/question/ipowners/IpOwnersAnswerElement.java, line 15 at r3](https://reviewable.io/reviews/batfish/batfish/1452#-LD53Sny05nCC7J_eVlr:-LD5A5MB0-dWzftGYNTg:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/864c8536e4225513a00be837e53a1e4df04538db/projects/question/src/main/java/org/batfish/question/ipowners/IpOwnersAnswerElement.java#L15)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

s/COL_HOSTNAME/COL_NODE/g?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1452)*

**Comment by ratulm** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r4.
Review status: 6 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1452#-:-LD5AJ642U1tViSzrqcc:bnfp4nl)*

**Comment by ratulm** [comment]
Reviewed 1 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1452)*

**Pull request merged**
