### PR TITLE
Parsing and using 'then preference' action in policy statements

### PR DESCRIPTION
**Pull request by haverma**
- Use `preference` action in policy statements to set admin cost in routing policies

### CODE REVIEW

**Comment by arifogel** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1389#-LCWHnhIAapFCfNxWpcB:-LCWHnhIAapFCfNxWpcC:b-ez0id0) (no related file):*
Please add test.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1389)*

**Comment by haverma** [comment]
Review status: 4 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1389#-LCWHnhIAapFCfNxWpcB:-LCp34sL37M_Os2Y0HVC:bdf7sos) (no related file):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Please add test.
</blockquote></details>

added tests in `FlatJuniperGrammarTest`

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1389)*

**Comment by arifogel** [comment]
Reviewed 4 of 4 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java, line 1106 at r3](https://reviewable.io/reviews/batfish/batfish/1389#-LCpB0JBAAzb1ce4XBld:-LCpB0JBAAzb1ce4XBle:bc8i9qy) ([raw file](https://github.com/batfish/batfish/blob/5a62a01120e983dafdd2f9639f1fccd449520d6b/projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java#L1106)):*
> ```Java
> 
>   @Test
>   public void testPsPreferencesBehavior() throws IOException {
> ```

should that be `PsPreference` (no `s`)?

---

*[projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java, line 1153 at r3](https://reviewable.io/reviews/batfish/batfish/1389#-LCpBJ3VADL2mbCmnmnj:-LCpBJ3VADL2mbCmnmnk:b-y1fow7) ([raw file](https://github.com/batfish/batfish/blob/5a62a01120e983dafdd2f9639f1fccd449520d6b/projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java#L1153)):*
> ```Java
>         (SetAdministrativeCost) Iterables.getOnlyElement(i.getTrueStatements());
> 
>     assertThat(setAdminCost.getAdmin().evaluate(eb.build()), equalTo(123));
> ```

This test appears to include assertions from the above test.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1389)*

**Comment by progwriter** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/PsThenPreference.java, line 10 at r3](https://reviewable.io/reviews/batfish/batfish/1389#-LCpCKLl-R7Hdd4B37hp:-LCpCKLl-R7Hdd4B37hq:b2jnove) ([raw file](https://github.com/batfish/batfish/blob/5a62a01120e983dafdd2f9639f1fccd449520d6b/projects/batfish/src/main/java/org/batfish/representation/juniper/PsThenPreference.java#L10)):*
> ```Java
> import org.batfish.datamodel.routing_policy.statement.Statement;
> 
> public final class PsThenPreference extends PsThen {
> ```

Please javadoc all new public classes (applies to `setAdministrativeCost` as well)

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1389)*

**Comment by arifogel** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java, line 1153 at r3](https://reviewable.io/reviews/batfish/batfish/1389#-LCpDWsm7a35XxyOTvzs:-LCpDWsm7a35XxyOTvzt:b8bpt3p) ([raw file](https://github.com/batfish/batfish/blob/5a62a01120e983dafdd2f9639f1fccd449520d6b/projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java#L1153)):*
> ```Java
>         (SetAdministrativeCost) Iterables.getOnlyElement(i.getTrueStatements());
> 
>     assertThat(setAdminCost.getAdmin().evaluate(eb.build()), equalTo(123));
> ```

Please modify your assertion to be on the structure of `getAdmin()` rather than its behavior.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1389)*

**Comment by haverma** [comment]
Review status: 4 of 14 files reviewed at latest revision, 3 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/PsThenPreference.java, line 10 at r3](https://reviewable.io/reviews/batfish/batfish/1389#-LCpCKLl-R7Hdd4B37hp:-LCwrCVEBnJL1UOVFV28:bw9d3zx) ([raw file](https://github.com/batfish/batfish/blob/5a62a01120e983dafdd2f9639f1fccd449520d6b/projects/batfish/src/main/java/org/batfish/representation/juniper/PsThenPreference.java#L10)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

Please javadoc all new public classes (applies to `setAdministrativeCost` as well)
</blockquote></details>

Java doc added for new classes `SetAdministrativeCost` and `PsThenPreference`

---

*[projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java, line 1106 at r3](https://reviewable.io/reviews/batfish/batfish/1389#-LCpB0JBAAzb1ce4XBld:-LCwrL4q49WtOAEacGvn:bbpu81q) ([raw file](https://github.com/batfish/batfish/blob/5a62a01120e983dafdd2f9639f1fccd449520d6b/projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java#L1106)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

should that be `PsPreference` (no `s`)?
</blockquote></details>

yes, changed

---

*[projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java, line 1153 at r3](https://reviewable.io/reviews/batfish/batfish/1389#-LCpDWsm7a35XxyOTvzs:-LCwrN_vEMW1jtDzMivT:b-tnjpu3) ([raw file](https://github.com/batfish/batfish/blob/5a62a01120e983dafdd2f9639f1fccd449520d6b/projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java#L1153)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Please modify your assertion to be on the structure of `getAdmin()` rather than its behavior.
</blockquote></details>

modified to check the structure.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1389)*

**Comment by arifogel** [comment]
:lgtm:

---

Reviewed 10 of 13 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1389#-:-LD2qUhDAK-o_MuOTpcb:bnfp4nl)*

**Pull request merged**
