### PR TITLE
regex-matching-in-node-properties

### PR DESCRIPTION
**Pull request by ratulm**

### CODE REVIEW

**Comment by corinaminer** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/NodePropertySpecifier.java, line 182 at r1](https://reviewable.io/reviews/batfish/batfish/1476#-LDEADTgADIwUXSrXLOt:-LDEADTgADIwUXSrXLOu:b-o4gkde) ([raw file](https://github.com/batfish/batfish/blob/073aae72bc15bb28a1389ee41ebb58c844cd60ff/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/NodePropertySpecifier.java#L182)):*
> ```Java
>     // first add .* version if needed
>     String queryWithStars = ".*" + (finalQuery.isEmpty() ? "" : finalQuery + ".*");
>     if (!finalQuery.endsWith("*") // hack to check if its a regex already
> ```

Seems like the only reason not to suggest `finalQuery + ".*"` would be if `finalQuery` ends with `.*`.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/NodePropertySpecifier.java, line 183 at r1](https://reviewable.io/reviews/batfish/batfish/1476#-LDE9xW51cOoQac1_8Po:-LDE9xW51cOoQac1_8Pp:btw9dwv) ([raw file](https://github.com/batfish/batfish/blob/073aae72bc15bb28a1389ee41ebb58c844cd60ff/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/NodePropertySpecifier.java#L183)):*
> ```Java
>     String queryWithStars = ".*" + (finalQuery.isEmpty() ? "" : finalQuery + ".*");
>     if (!finalQuery.endsWith("*") // hack to check if its a regex already
>         && !finalQuery.startsWith("*")
> ```

I don't think regexes can start with `*`

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/NodePropertySpecifier.java, line 187 at r1](https://reviewable.io/reviews/batfish/batfish/1476#-LDE9FQEBpney5Y6JTgU:-LDE9FQEBpney5Y6JTgV:b-ltca8d) ([raw file](https://github.com/batfish/batfish/blob/073aae72bc15bb28a1389ee41ebb58c844cd60ff/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/NodePropertySpecifier.java#L187)):*
> ```Java
>       suggestions.add(
>           new AutocompleteSuggestion(
>               queryWithStars, false, "All properties matching regex " + queryWithStars));
> ```

I think it's better to suggest just `finalQuery + ".*"` here.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/NodePropertySpecifier.java, line 195 at r1](https://reviewable.io/reviews/batfish/batfish/1476#-LDEAVvW7DOaCgbYi7Yy:-LDEAVvW7DOaCgbYi7Yz:bsu05eh) ([raw file](https://github.com/batfish/batfish/blob/073aae72bc15bb28a1389ee41ebb58c844cd60ff/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/NodePropertySpecifier.java#L195)):*
> ```Java
>             .keySet()
>             .stream()
>             .filter(prop -> Pattern.compile(queryWithStars).matcher(prop).matches())
> ```

Can create the matcher before `suggestions.addAll` to avoid re-creating it for every node property.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/NodePropertySpecifier.java, line 207 at r1](https://reviewable.io/reviews/batfish/batfish/1476#-LDE8qNI22OGocsclHj2:-LDE8qNI22OGocsclHj3:b-bsn9vw) ([raw file](https://github.com/batfish/batfish/blob/073aae72bc15bb28a1389ee41ebb58c844cd60ff/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/NodePropertySpecifier.java#L207)):*
> ```Java
>    * @return The matching set
>    */
>   public Set<String> getMatchingProperties() {
> ```

If this is only used for checking if any matching property exists, it could be modified to `hasMatchingProperty()` and return true as soon as a matching property is found.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1476)*

**Comment by ratulm** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/NodePropertySpecifier.java, line 182 at r1](https://reviewable.io/reviews/batfish/batfish/1476#-LDEADTgADIwUXSrXLOt:-LDEBXsU3YRnpAqoJGPQ:b-x9kn81) ([raw file](https://github.com/batfish/batfish/blob/073aae72bc15bb28a1389ee41ebb58c844cd60ff/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/NodePropertySpecifier.java#L182)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Seems like the only reason not to suggest `finalQuery + ".*"` would be if `finalQuery` ends with `.*`.
</blockquote></details>

expanding 'ntp' to  '.*ntp.*' , so we go both ways. 

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/NodePropertySpecifier.java, line 183 at r1](https://reviewable.io/reviews/batfish/batfish/1476#-LDE9xW51cOoQac1_8Po:-LDEBn3y3eLPmlV9dg0f:b-kl8g3z) ([raw file](https://github.com/batfish/batfish/blob/073aae72bc15bb28a1389ee41ebb58c844cd60ff/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/NodePropertySpecifier.java#L183)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

I don't think regexes can start with `*`
</blockquote></details>

good catch.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/NodePropertySpecifier.java, line 187 at r1](https://reviewable.io/reviews/batfish/batfish/1476#-LDE9FQEBpney5Y6JTgU:-LDEBtSz7x7NsOU40g2_:b-ityays) ([raw file](https://github.com/batfish/batfish/blob/073aae72bc15bb28a1389ee41ebb58c844cd60ff/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/NodePropertySpecifier.java#L187)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

I think it's better to suggest just `finalQuery + ".*"` here.
</blockquote></details>

why do you think that?  we have things like ntp-servers, tacacs-servers, etc. the .* in the beginning will expand 'servers' to '.*servers.*'  why do contains for strings and prefixes for regexes?

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/NodePropertySpecifier.java, line 195 at r1](https://reviewable.io/reviews/batfish/batfish/1476#-LDEAVvW7DOaCgbYi7Yy:-LDECodN9Yp0OZGTVBgZ:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/073aae72bc15bb28a1389ee41ebb58c844cd60ff/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/NodePropertySpecifier.java#L195)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Can create the matcher before `suggestions.addAll` to avoid re-creating it for every node property.
</blockquote></details>

Done.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/NodePropertySpecifier.java, line 207 at r1](https://reviewable.io/reviews/batfish/batfish/1476#-LDE8qNI22OGocsclHj2:-LDECqFfCl1mpWENzz8K:bn3mesn) ([raw file](https://github.com/batfish/batfish/blob/073aae72bc15bb28a1389ee41ebb58c844cd60ff/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/NodePropertySpecifier.java#L207)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

If this is only used for checking if any matching property exists, it could be modified to `hasMatchingProperty()` and return true as soon as a matching property is found.
</blockquote></details>

gets used in other places to get matching things.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1476)*

**Comment by corinaminer** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/NodePropertySpecifier.java, line 182 at r1](https://reviewable.io/reviews/batfish/batfish/1476#-LDEADTgADIwUXSrXLOt:-LDEE9Iw2jkVOwixm5GJ:bftgea8) ([raw file](https://github.com/batfish/batfish/blob/073aae72bc15bb28a1389ee41ebb58c844cd60ff/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/NodePropertySpecifier.java#L182)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

expanding 'ntp' to  '.*ntp.*' , so we go both ways. 
</blockquote></details>

sorry, phrasing was unclear -- i think we can check `endsWith(".*")` instead of `endsWith("*")`, since query could end with `*` without necessarily ending with `.*`.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/NodePropertySpecifier.java, line 187 at r1](https://reviewable.io/reviews/batfish/batfish/1476#-LDE9FQEBpney5Y6JTgU:-LDEEl503Tl02A83CUZO:bnusn7n) ([raw file](https://github.com/batfish/batfish/blob/073aae72bc15bb28a1389ee41ebb58c844cd60ff/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/NodePropertySpecifier.java#L187)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

why do you think that?  we have things like ntp-servers, tacacs-servers, etc. the .* in the beginning will expand 'servers' to '.*servers.*'  why do contains for strings and prefixes for regexes?
</blockquote></details>

Yeah, on second thought `.*servers.*` seems like the right suggestion.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1476)*

**Comment by corinaminer** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/NodePropertySpecifier.java, line 181 at r2](https://reviewable.io/reviews/batfish/batfish/1476#-LDEFpX40nZKlWvHtdFt:-LDEFpX40nZKlWvHtdFu:ba5xgfh) ([raw file](https://github.com/batfish/batfish/blob/a25ca5cfed606eba2cd5cf0cc715414ba6221934/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/NodePropertySpecifier.java#L181)):*
> ```Java
> 
>     // first add .* version if needed
>     String queryWithStars = ".*" + (finalQuery.isEmpty() ? "" : finalQuery + ".*");
> ```

Do we need to add a try/catch to make sure the query is valid java regex?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1476)*

**Comment by ratulm** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/NodePropertySpecifier.java, line 182 at r1](https://reviewable.io/reviews/batfish/batfish/1476#-LDEADTgADIwUXSrXLOt:-LDELunn7YzRDCTwK__x:b50sf3w) ([raw file](https://github.com/batfish/batfish/blob/073aae72bc15bb28a1389ee41ebb58c844cd60ff/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/NodePropertySpecifier.java#L182)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

sorry, phrasing was unclear -- i think we can check `endsWith(".*")` instead of `endsWith("*")`, since query could end with `*` without necessarily ending with `.*`.
</blockquote></details>

I did not want to expand 'ntp*' to 'ntp*.*'  -- if the user entered 'ntp*', they are probably already giving us a regex. I didn't want to be presumptuous and change their regex, and instead want to autocomplete to just suggestions that match the regex. 

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/NodePropertySpecifier.java, line 181 at r2](https://reviewable.io/reviews/batfish/batfish/1476#-LDEFpX40nZKlWvHtdFt:-LDEMGBPD4D_HNODCgo1:bvjosfn) ([raw file](https://github.com/batfish/batfish/blob/a25ca5cfed606eba2cd5cf0cc715414ba6221934/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/NodePropertySpecifier.java#L181)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Do we need to add a try/catch to make sure the query is valid java regex?
</blockquote></details>

Good point. Refactored to account for that.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1476)*

**Comment by corinaminer** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1476#-:-LDEQpap7yrCcAQSPEq3:bnfp4nl)*

**Pull request merged**
