### PR TITLE
Spin off CiscoXr parser

### PR DESCRIPTION
**Pull request by dhalperi**

### CODE REVIEW

**Comment by dhalperi** [comment]
*[a discussion](https://reviewable.io/reviews/batfish/batfish/5129#-Lt1Bz5z4E0MjFBZ_S-5:-Lt1Bz5z4E0MjFBZ_S-6:b-o63j7u) (no related file):*
FYI first 20 commits are in.

---

**Comment by dhalperi** [comment]
*[a discussion](https://reviewable.io/reviews/batfish/batfish/5129#-Lt1Bz5z4E0MjFBZ_S-5:-Lt1CsH_B0imhENdxwrY:br9en24) (no related file):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

FYI first 20 commits are in.
</blockquote></details>

Now 25.

---

**Comment by dhalperi** [comment]
*[a discussion](https://reviewable.io/reviews/batfish/batfish/5129#-Lt1CyOLDXyEy4ISvbzT:-Lt1CyOLDXyEy4ISvbzU:b-yp851q) (no related file):*
FYI Now 25.

---

**Comment by dhalperi** [comment]
*[a discussion](https://reviewable.io/reviews/batfish/batfish/5129#-Lt1DeVv5fx0xyvwNcI7:-Lt1DeVv5fx0xyvwNcI8:ba7w3a) (no related file):*
FYI now 30

---

**Comment by dhalperi** [comment]
*[a discussion](https://reviewable.io/reviews/batfish/batfish/5129#-Lt1GXFG81NY8u2TjSg_:-Lt1GXFG81NY8u2TjSga:bayhk3m) (no related file):*
+reviewer:@arifogel 

---

**Comment by arifogel** [comment]
___
*[projects/batfish/src/test/resources/org/batfish/grammar/cisco_xr/testconfigs/community-set, line 1 at r2](https://reviewable.io/reviews/batfish/batfish/5129#-Lt1Jjxc4WMwynuRbAuP:-Lt1Jjxc4WMwynuRbAuQ:bmhnavb) ([raw file](https://github.com/batfish/batfish/blob/f852aa328f169db9f5f92d2d3305394b40a4b9ed/projects/batfish/src/test/resources/org/batfish/grammar/cisco_xr/testconfigs/community-set#L1)):*
> ```
> !RANCID-CONTENT-TYPE: cisco-xr                                                                                                                                                                                                                 
> ```

whitespace on first line at end


<!-- Sent from Reviewable.io -->

**Comment by dhalperi** [comment]
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_xr/Interface.java, line 268 at r28](https://reviewable.io/reviews/batfish/batfish/5129#-Lt1SznpEAdcCst0vSXM:-Lt1bpWC45Hij1wSJu1l:bjez9fh) ([raw file](https://github.com/batfish/batfish/blob/2c42329371e06b772bf8b90de8b1d550472b06b1/projects/batfish/src/main/java/org/batfish/representation/cisco_xr/Interface.java#L268)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

check XR default proxy arp behavior
</blockquote></details>

Did it.

**Comment by dhalperi** [comment]
Anything like that is out of scope. Relax as long as it's not incorrect

**Pull request merged**
