### PR TITLE
discussion: new forwarding analysis loopback interface tests

### PR DESCRIPTION
**Pull request by anothermattbrown**
The neighbor unreachable IpSpaces are not what I expected. It's possible
that it doesn't matter in practice, but worth taking a look at.

### CODE REVIEW

**Comment by anothermattbrown** [comment]
Review status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @anothermattbrown and @arifogel)

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1717#-LFUIqHl9oHdT678apgB:-LFUIqHl9oHdT678apgC:buylcs6) (no related file):*
Not a real PR; just using reviewable to have an asynchronous discussion

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1717)*

**Comment by anothermattbrown** [comment]
Review status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @anothermattbrown and @arifogel)

---

*[projects/batfish/src/test/java/org/batfish/datamodel/NewForwardingAnalysisImplTest.java, line 53 at r1](https://reviewable.io/reviews/batfish/batfish/1717#-LFUJ3VIDIeZ_Jbep2iN:-LFUJ3VIDIeZ_Jbep2iO:be9bil4) ([raw file](https://github.com/batfish/batfish/blob/344a8235fccaa0444df0973e2a0fb6dc4e4d15c1/projects/batfish/src/test/java/org/batfish/datamodel/NewForwardingAnalysisImplTest.java#L53)):*
> ```Java
> 
>     assertThat(ipSpace, containsIp(prefix.getEndIp()));
>     assertThat(ipSpace, not(containsIp(prefix.getStartIp())));
> ```

this fails

---

*[projects/batfish/src/test/java/org/batfish/datamodel/NewForwardingAnalysisImplTest.java, line 92 at r1](https://reviewable.io/reviews/batfish/batfish/1717#-LFUJ50z3704RcOGEwf_:-LFUJ50z3704RcOGEwfa:be9bil4) ([raw file](https://github.com/batfish/batfish/blob/344a8235fccaa0444df0973e2a0fb6dc4e4d15c1/projects/batfish/src/test/java/org/batfish/datamodel/NewForwardingAnalysisImplTest.java#L92)):*
> ```Java
>             .get(iface.getName());
> 
>     assertThat(ipSpace, not(containsIp(prefix.getStartIp())));
> ```

this fails

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1717)*

**Comment by arifogel** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed, 4 unresolved discussions (waiting on @anothermattbrown and @arifogel)

---

*[projects/batfish/src/test/java/org/batfish/datamodel/NewForwardingAnalysisImplTest.java, line 17 at r1](https://reviewable.io/reviews/batfish/batfish/1717#-LFYVMT_5_4PhiWu6TiI:-LFYVMT_5_4PhiWu6TiJ:b-xetp6g) ([raw file](https://github.com/batfish/batfish/blob/344a8235fccaa0444df0973e2a0fb6dc4e4d15c1/projects/batfish/src/test/java/org/batfish/datamodel/NewForwardingAnalysisImplTest.java#L17)):*
> ```Java
> public class NewForwardingAnalysisImplTest {
>   @Test
>   public void testNeighborUnreachable_loopback31() throws IOException {
> ```

What is loopback-y about a `/31`?

---

*[projects/batfish/src/test/java/org/batfish/datamodel/NewForwardingAnalysisImplTest.java, line 53 at r1](https://reviewable.io/reviews/batfish/batfish/1717#-LFUJ3VIDIeZ_Jbep2iN:-LFYV6x_AlYp079eJcIR:bdg0fyj) ([raw file](https://github.com/batfish/batfish/blob/344a8235fccaa0444df0973e2a0fb6dc4e4d15c1/projects/batfish/src/test/java/org/batfish/datamodel/NewForwardingAnalysisImplTest.java#L53)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

this fails
</blockquote></details>

Seems wrong. What is `ipSpace`?

---

*[projects/batfish/src/test/java/org/batfish/datamodel/NewForwardingAnalysisImplTest.java, line 92 at r1](https://reviewable.io/reviews/batfish/batfish/1717#-LFUJ50z3704RcOGEwf_:-LFYVVEW7ejh_Zd39y0s:bhpvjxz) ([raw file](https://github.com/batfish/batfish/blob/344a8235fccaa0444df0973e2a0fb6dc4e4d15c1/projects/batfish/src/test/java/org/batfish/datamodel/NewForwardingAnalysisImplTest.java#L92)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

this fails
</blockquote></details>

Probably same issue. I have the same question: What is `ipSpace`?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1717)*

**Comment by anothermattbrown** [comment]
Review status: all files reviewed, 4 unresolved discussions (waiting on @anothermattbrown)

---

*[projects/batfish/src/test/java/org/batfish/datamodel/NewForwardingAnalysisImplTest.java, line 17 at r1](https://reviewable.io/reviews/batfish/batfish/1717#-LFYVMT_5_4PhiWu6TiI:-LFYap7I2jlhABWZyNyS:b-x29l03) ([raw file](https://github.com/batfish/batfish/blob/344a8235fccaa0444df0973e2a0fb6dc4e4d15c1/projects/batfish/src/test/java/org/batfish/datamodel/NewForwardingAnalysisImplTest.java#L17)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

What is loopback-y about a `/31`?
</blockquote></details>

haha fair

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1717)*

**Comment by anothermattbrown** [comment]
Review status: all files reviewed, 3 unresolved discussions (waiting on @anothermattbrown)

---

*[projects/batfish/src/test/java/org/batfish/datamodel/NewForwardingAnalysisImplTest.java, line 53 at r1](https://reviewable.io/reviews/batfish/batfish/1717#-LFUJ3VIDIeZ_Jbep2iN:-LFYbCMw-9TDzwPIIMqL:bggg9uf) ([raw file](https://github.com/batfish/batfish/blob/344a8235fccaa0444df0973e2a0fb6dc4e4d15c1/projects/batfish/src/test/java/org/batfish/datamodel/NewForwardingAnalysisImplTest.java#L53)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Seems wrong. What is `ipSpace`?
</blockquote></details>

```
AclIpSpace{
  lines=[
    AclIpSpaceLine{
      ipSpace=AclIpSpace{
        lines=[
          AclIpSpaceLine{action=REJECT, ipSpace=empty}, 
          AclIpSpaceLine{ipSpace=
            AclIpSpace{lines=[
              AclIpSpaceLine{ipSpace=IpWildcardSetIpSpace{blacklist=[], whitelist=[1.0.0.0]}}, 
              AclIpSpaceLine{ipSpace=IpWildcardSetIpSpace{blacklist=[1.0.0.0], whitelist=[1.0.0.0/31]}}
	    ]}
          }
        ]
      }
    },
    AclIpSpaceLine{ipSpace=AclIpSpace{lines=[]}}
  ]
}
```

---

*[projects/batfish/src/test/java/org/batfish/datamodel/NewForwardingAnalysisImplTest.java, line 92 at r1](https://reviewable.io/reviews/batfish/batfish/1717#-LFUJ50z3704RcOGEwf_:-LFYbslr5BW3wDE42xyU:b-qvbrbf) ([raw file](https://github.com/batfish/batfish/blob/344a8235fccaa0444df0973e2a0fb6dc4e4d15c1/projects/batfish/src/test/java/org/batfish/datamodel/NewForwardingAnalysisImplTest.java#L92)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Probably same issue. I have the same question: What is `ipSpace`?
</blockquote></details>

```
AclIpSpace{
  lines=[
    AclIpSpaceLine{
      ipSpace=AclIpSpace{
        lines=[
	  AclIpSpaceLine{action=REJECT, ipSpace=empty},
	  AclIpSpaceLine{
	    ipSpace=AclIpSpace{
	      lines=[
                AclIpSpaceLine{
		  ipSpace=IpWildcardSetIpSpace{blacklist=[], whitelist=[1.0.0.0]}
		}
              ]
	    }
	  }
	]
      }
    },
    AclIpSpaceLine{ipSpace=AclIpSpace{lines=[]}}
  ]
}
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1717)*

**Comment by arifogel** [comment]
Review status: all files reviewed, 3 unresolved discussions (waiting on @anothermattbrown and @arifogel)

---

*[projects/batfish/src/test/java/org/batfish/datamodel/NewForwardingAnalysisImplTest.java, line 53 at r1](https://reviewable.io/reviews/batfish/batfish/1717#-LFUJ3VIDIeZ_Jbep2iN:-LFYckt33-RBTTZ6Fm8j:b-tjxot2) ([raw file](https://github.com/batfish/batfish/blob/344a8235fccaa0444df0973e2a0fb6dc4e4d15c1/projects/batfish/src/test/java/org/batfish/datamodel/NewForwardingAnalysisImplTest.java#L53)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

```
AclIpSpace{
  lines=[
    AclIpSpaceLine{
      ipSpace=AclIpSpace{
        lines=[
          AclIpSpaceLine{action=REJECT, ipSpace=empty}, 
          AclIpSpaceLine{ipSpace=
            AclIpSpace{lines=[
              AclIpSpaceLine{ipSpace=IpWildcardSetIpSpace{blacklist=[], whitelist=[1.0.0.0]}}, 
              AclIpSpaceLine{ipSpace=IpWildcardSetIpSpace{blacklist=[1.0.0.0], whitelist=[1.0.0.0/31]}}
	    ]}
          }
        ]
      }
    },
    AclIpSpaceLine{ipSpace=AclIpSpace{lines=[]}}
  ]
}
```
</blockquote></details>

that first whitelist should not be there.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1717)*

**Comment by arifogel** [comment]
Review status: all files reviewed, 3 unresolved discussions (waiting on @anothermattbrown and @arifogel)

---

*[projects/batfish/src/test/java/org/batfish/datamodel/NewForwardingAnalysisImplTest.java, line 92 at r1](https://reviewable.io/reviews/batfish/batfish/1717#-LFUJ50z3704RcOGEwf_:-LFYd9Pg8IEI2S-sXWAv:bwci88y) ([raw file](https://github.com/batfish/batfish/blob/344a8235fccaa0444df0973e2a0fb6dc4e4d15c1/projects/batfish/src/test/java/org/batfish/datamodel/NewForwardingAnalysisImplTest.java#L92)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

```
AclIpSpace{
  lines=[
    AclIpSpaceLine{
      ipSpace=AclIpSpace{
        lines=[
	  AclIpSpaceLine{action=REJECT, ipSpace=empty},
	  AclIpSpaceLine{
	    ipSpace=AclIpSpace{
	      lines=[
                AclIpSpaceLine{
		  ipSpace=IpWildcardSetIpSpace{blacklist=[], whitelist=[1.0.0.0]}
		}
              ]
	    }
	  }
	]
      }
    },
    AclIpSpaceLine{ipSpace=AclIpSpace{lines=[]}}
  ]
}
```
</blockquote></details>

this should be universe. not sure what is happening.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1717)*

**Comment by arifogel** [comment]
Review status: all files reviewed, 3 unresolved discussions (waiting on @anothermattbrown and @arifogel)

---

*[projects/batfish/src/test/java/org/batfish/datamodel/NewForwardingAnalysisImplTest.java, line 92 at r1](https://reviewable.io/reviews/batfish/batfish/1717#-LFUJ50z3704RcOGEwf_:-LFYdFkG1Mxc6pmcSVbG:b-mbj7yh) ([raw file](https://github.com/batfish/batfish/blob/344a8235fccaa0444df0973e2a0fb6dc4e4d15c1/projects/batfish/src/test/java/org/batfish/datamodel/NewForwardingAnalysisImplTest.java#L92)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

this should be universe. not sure what is happening.
</blockquote></details>

Sorry, universe except 1.0.0.0/32.
But this shouldn't even matter, because you cannot connect to a /32

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1717)*

**Comment by arifogel** [comment]
Review status: all files reviewed, 3 unresolved discussions (waiting on @anothermattbrown and @arifogel)

---

*[projects/batfish/src/test/java/org/batfish/datamodel/NewForwardingAnalysisImplTest.java, line 92 at r1](https://reviewable.io/reviews/batfish/batfish/1717#-LFUJ50z3704RcOGEwf_:-LFYdaMA0G-VzcVLRjpK:b-eglkxw) ([raw file](https://github.com/batfish/batfish/blob/344a8235fccaa0444df0973e2a0fb6dc4e4d15c1/projects/batfish/src/test/java/org/batfish/datamodel/NewForwardingAnalysisImplTest.java#L92)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Sorry, universe except 1.0.0.0/32.
But this shouldn't even matter, because you cannot connect to a /32
</blockquote></details>

I guess it does matter, because in theory you could have both a /32 and a /1-31 on the same interface.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1717)*

**Comment by anothermattbrown** [comment]
Review status: all files reviewed, 3 unresolved discussions (waiting on @anothermattbrown)

---

*[projects/batfish/src/test/java/org/batfish/datamodel/NewForwardingAnalysisImplTest.java, line 92 at r1](https://reviewable.io/reviews/batfish/batfish/1717#-LFUJ50z3704RcOGEwf_:-LFZ0HbX3r1sbZJQ8E44:b-70in9d) ([raw file](https://github.com/batfish/batfish/blob/344a8235fccaa0444df0973e2a0fb6dc4e4d15c1/projects/batfish/src/test/java/org/batfish/datamodel/NewForwardingAnalysisImplTest.java#L92)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

I guess it does matter, because in theory you could have both a /32 and a /1-31 on the same interface.
</blockquote></details>

why universe? I'd expect it to be (interface network - interface ip) = (interface ip - interface ip) = empty.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1717)*

**Comment by arifogel** [comment]
Review status: all files reviewed, 3 unresolved discussions (waiting on @anothermattbrown and @arifogel)

---

*[projects/batfish/src/test/java/org/batfish/datamodel/NewForwardingAnalysisImplTest.java, line 92 at r1](https://reviewable.io/reviews/batfish/batfish/1717#-LFUJ50z3704RcOGEwf_:-LFZjuKyC9uKuYjR0dse:b-7z7n5a) ([raw file](https://github.com/batfish/batfish/blob/344a8235fccaa0444df0973e2a0fb6dc4e4d15c1/projects/batfish/src/test/java/org/batfish/datamodel/NewForwardingAnalysisImplTest.java#L92)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

why universe? I'd expect it to be (interface network - interface ip) = (interface ip - interface ip) = empty.
</blockquote></details>

After review of semantics of `getNeighborUnreachable`, I don't believe it matters whether IPs belonging to the interface are included or not in the `ipSpace`. So we should either leave that  behavior as undefined, or pick a standard for consistency. This applies to both tests.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1717)*

**Comment by arifogel** [comment]
Review status: all files reviewed, 3 unresolved discussions (waiting on @anothermattbrown and @arifogel)

---

*[projects/batfish/src/test/java/org/batfish/datamodel/NewForwardingAnalysisImplTest.java, line 53 at r1](https://reviewable.io/reviews/batfish/batfish/1717#-LFUJ3VIDIeZ_Jbep2iN:-LFZkDQgBy7iba8tlM_N:b36nqq7) ([raw file](https://github.com/batfish/batfish/blob/344a8235fccaa0444df0973e2a0fb6dc4e4d15c1/projects/batfish/src/test/java/org/batfish/datamodel/NewForwardingAnalysisImplTest.java#L53)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

that first whitelist should not be there.
</blockquote></details>

Ignore above comment. See below.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1717)*

**Comment by anothermattbrown** [comment]
Review status: all files reviewed, 3 unresolved discussions (waiting on @anothermattbrown)

---

*[projects/batfish/src/test/java/org/batfish/datamodel/NewForwardingAnalysisImplTest.java, line 92 at r1](https://reviewable.io/reviews/batfish/batfish/1717#-LFUJ50z3704RcOGEwf_:-LFccBwT68cWVtUD8VbA:bmcw087) ([raw file](https://github.com/batfish/batfish/blob/344a8235fccaa0444df0973e2a0fb6dc4e4d15c1/projects/batfish/src/test/java/org/batfish/datamodel/NewForwardingAnalysisImplTest.java#L92)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

After review of semantics of `getNeighborUnreachable`, I don't believe it matters whether IPs belonging to the interface are included or not in the `ipSpace`. So we should either leave that  behavior as undefined, or pick a standard for consistency. This applies to both tests.
</blockquote></details>

I like the idea of choosing and documenting a standard. I'm fine with including the owned ip. So should the official definition of neighbor unreachable be "the entire network minus whatever neighbor interfaces will arp reply to"? In this case of a border interface (no neighbors), this would just be the entire network. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1717)*

**Comment by arifogel** [comment]
Review status: all files reviewed, 3 unresolved discussions (waiting on @anothermattbrown and @arifogel)

---

*[projects/batfish/src/test/java/org/batfish/datamodel/NewForwardingAnalysisImplTest.java, line 92 at r1](https://reviewable.io/reviews/batfish/batfish/1717#-LFUJ50z3704RcOGEwf_:-LFd8l3f9whQXUHv41E6:bovvoaq) ([raw file](https://github.com/batfish/batfish/blob/344a8235fccaa0444df0973e2a0fb6dc4e4d15c1/projects/batfish/src/test/java/org/batfish/datamodel/NewForwardingAnalysisImplTest.java#L92)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

I like the idea of choosing and documenting a standard. I'm fine with including the owned ip. So should the official definition of neighbor unreachable be "the entire network minus whatever neighbor interfaces will arp reply to"? In this case of a border interface (no neighbors), this would just be the entire network. 
</blockquote></details>

I'm fine with whatever you choose.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1717)*

**Pull request closed without merging**
