### PR TITLE
Validation for SearchRoutePolicies and CompareRoutePolicies

### PR DESCRIPTION
**Pull request by millstein**
Adds assertions to compare the results of SearchRoutePolicies and CompareRoutePolicies as predicted by the symbolic route analysis versus that produced by the concrete route simulation.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8758)* status: 2 of 6 files reviewed, 6 unresolved discussions (waiting on @anothermattbrown, @millstein, and @nickgian)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/8758#-NaJRI_f9Zjy0hYMUPVG:-NaJRI_f9Zjy0hYMUPVH:b9tx3mu) (no related file):*
Feedback from writing similar code, use as you see fit.

___
___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/ModelGeneration.java` line 238 at r1](https://reviewable.io/reviews/batfish/batfish/8758#-NaJQCtLCLZlrXE2R7LF:-NaJQCtLCLZlrXE2R7LG:b-73p66x) ([raw file](https://github.com/batfish/batfish/blob/99197280b42f37435a5d70267076cc73f8bf9384/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/ModelGeneration.java#L238)):*
> ```Java
>    * @param expectedResult the expected input-output behavior
>    */
>   public static void validateModel(
> ```

make this function return `true` so you can `assert` at the callsite.

Then the code in here can not use assert and also we can skip work like generating outputRouteFromModel if asserts aren't on.
___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/question/compareroutepolicies/CompareRoutePoliciesAnswerer.java` line 196 at r1](https://reviewable.io/reviews/batfish/batfish/8758#-NaJR1LYAg2Ottz01T7x:-NaJR1LYAg2Ottz01T7y:b-6wuyrn) ([raw file](https://github.com/batfish/batfish/blob/99197280b42f37435a5d70267076cc73f8bf9384/projects/minesweeper/src/main/java/org/batfish/minesweeper/question/compareroutepolicies/CompareRoutePoliciesAnswerer.java#L196)):*
> ```Java
>   }
> 
>   // Check that the results of symbolic analysis are consistent with the given concrete result from
> ```

javadoc style?
___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/question/compareroutepolicies/CompareRoutePoliciesAnswerer.java` line 198 at r1](https://reviewable.io/reviews/batfish/batfish/8758#-NaJQYXGCY6op1F5zHkB:-NaJQYXGCY6op1F5zHkC:bg71afc) ([raw file](https://github.com/batfish/batfish/blob/99197280b42f37435a5d70267076cc73f8bf9384/projects/minesweeper/src/main/java/org/batfish/minesweeper/question/compareroutepolicies/CompareRoutePoliciesAnswerer.java#L198)):*
> ```Java
>   // Check that the results of symbolic analysis are consistent with the given concrete result from
>   // route simulation
>   private void validateModel(
> ```

same `assert` commands if this is similar method.
___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/question/compareroutepolicies/CompareRoutePoliciesAnswerer.java` line 299 at r1](https://reviewable.io/reviews/batfish/batfish/8758#-NaJR5JoA8nvK4RUtOTR:-NaJR5JoA8nvK4RUtOTS:b-tpxiki) ([raw file](https://github.com/batfish/batfish/blob/99197280b42f37435a5d70267076cc73f8bf9384/projects/minesweeper/src/main/java/org/batfish/minesweeper/question/compareroutepolicies/CompareRoutePoliciesAnswerer.java#L299)):*
> ```Java
>             BDD fullModel = constraintsToModel(finalConstraints, configAPs);
>             validateModel(fullModel, otherPath, configAPs, otherResult);
>             validateModel(fullModel, path, configAPs, refResult);
> ```

move this into somewhere it runs only under assertion
___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesAnswerer.java` line 188 at r1](https://reviewable.io/reviews/batfish/batfish/8758#-NaJRAbj5vnIsE1Edvc9:-NaJRAbj5vnIsE1EdvcA:b-7ropln) ([raw file](https://github.com/batfish/batfish/blob/99197280b42f37435a5d70267076cc73f8bf9384/projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesAnswerer.java#L188)):*
> ```Java
>       // As a sanity check, compare the simulated result above with what the symbolic route
>       // analysis predicts will happen.
>       ModelGeneration.validateModel(fullModel, outputRoute, configAPs, _action, _direction, result);
> ```

ditto

**Review by nickgian — COMMENTED** [review]
> Reviewed 4 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8758)* status: all files reviewed, 6 unresolved discussions (waiting on @anothermattbrown and @millstein)

___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/ModelGeneration.java` line 142 at r1](https://reviewable.io/reviews/batfish/batfish/8758#-NaNY3ihBKDuzCeqYfLg:-NaNY3ihBKDuzCeqYfLh:b-vf1vcq) ([raw file](https://github.com/batfish/batfish/blob/99197280b42f37435a5d70267076cc73f8bf9384/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/ModelGeneration.java#L142)):*
> ```Java
>     checkState(
>         trueAPs.size() == 1,
>         "Error in symbolic AS-path analysis: exactly one atomic predicate should be true");
> ```

Is the set `configAPs.getAsPathRegexAtomicPredicates()` always non-empty? I guess if there are no match as-path expressions this correspond to `True` so there is a single AP?
___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/question/compareroutepolicies/CompareRoutePoliciesAnswerer.java` line 203 at r1](https://reviewable.io/reviews/batfish/batfish/8758#-NaN_mOp5gQf91VDWZHw:-NaN_mOq7JHMAFhvXZdY:btsdy6) ([raw file](https://github.com/batfish/batfish/blob/99197280b42f37435a5d70267076cc73f8bf9384/projects/minesweeper/src/main/java/org/batfish/minesweeper/question/compareroutepolicies/CompareRoutePoliciesAnswerer.java#L203)):*
> ```Java
>       ConfigAtomicPredicates configAPs,
>       Result<BgpRoute> result) {
>     // update the atomic predicates to include any prepended ASes
> ```

I was going to say we can probably just update the original configAPs, but now I realize that this need to be done per-path. Perhaps worth augmenting the comment to say "include any prepended ASes for this path".

**Review by millstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8758)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @anothermattbrown and @nickgian)

___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/ModelGeneration.java` line 142 at r1](https://reviewable.io/reviews/batfish/batfish/8758#-NaNY3ihBKDuzCeqYfLg:-NaOJ9lD-TjoP0eeYmGQ:bx04udk) ([raw file](https://github.com/batfish/batfish/blob/99197280b42f37435a5d70267076cc73f8bf9384/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/ModelGeneration.java#L142)):*
<details><summary><i>Previously, nickgian (Nick Giannarakis) wrote…</i></summary><blockquote>

Is the set `configAPs.getAsPathRegexAtomicPredicates()` always non-empty? I guess if there are no match as-path expressions this correspond to `True` so there is a single AP?
</blockquote></details>

Yes, the APs are always non-empty.  They cover the entire space so even if there are no AS-path regexes in the config then there will still be one AP representing `.*`.  Previously we didn't rely on this fact, but in order to properly generate APs for output routes in the presence of AS-path prepending, we now rely on it.

**Review by nickgian — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8758#-:-NaOUr5_3aWoNHaBd46f:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown)

**Pull request merged**
