### PR TITLE
Constant WildcardSet IpSpace Specifier Factory

### PR DESCRIPTION
**Pull request by anothermattbrown**
A new constant IpSpaceSpecifierFactory for ConstantIpSpaceSpecifiers
with IpWildcardSetIpSpaces. Uses a simple format for expressing
IpWildcardSetIpSpaces in a single string:
     W1,W2,... - W3,W4,...
or:  W1,W2,... \ W3,W4,...

etc, where the '-' or '\' separates the whitelist from the blacklist.

Also save the name of ConstantUniverseIpSpaceSpecifierFactory in a
constant field for testing, etc.

### CODE REVIEW

**Comment by anothermattbrown** [comment]
Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1622#-LEVF4Oh7hYEbD9T351A:-LEVF4Oh7hYEbD9T351B:b-xdrbha) (no related file):*
Working to get base merged into master

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1622)*

**Comment by dhalperi** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/specifier/ConstantWildcardSetIpSpaceSpecifierFactory.java, line 22 at r1](https://reviewable.io/reviews/batfish/batfish/1622#-LEXA0ITDj2xd0kj5Io7:-LEXA0ITDj2xd0kj5Io8:b-pqquow) ([raw file](https://github.com/batfish/batfish/blob/834d701d332232c93801b9f160a26f33f8e19c2f/projects/batfish-common-protocol/src/main/java/org/batfish/specifier/ConstantWildcardSetIpSpaceSpecifierFactory.java#L22)):*
> ```Java
> 
>   /**
>    * Parse the following format w1,w2,...wn-wn+1,wn+2,... Wildcards to the left of - are whitelisted
> ```

use `{@code foo}` to make this look better?

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/specifier/ConstantWildcardSetIpSpaceSpecifierFactoryTest.java, line 61 at r1](https://reviewable.io/reviews/batfish/batfish/1622#-LEXAQOw4bQCqhdfeFG4:-LEXAQOw4bQCqhdfeFG5:b-mr29dk) ([raw file](https://github.com/batfish/batfish/blob/834d701d332232c93801b9f160a26f33f8e19c2f/projects/batfish-common-protocol/src/test/java/org/batfish/specifier/ConstantWildcardSetIpSpaceSpecifierFactoryTest.java#L61)):*
> ```Java
>   public void testParseIpSpace_tooManySubtractions() {
>     exception.expect(IllegalArgumentException.class);
>     parseIpSpace("1.0.0.0 - 2.0.0.0/8 \\ 3.0.0.0 \\ 4.0.0.0/32");
> ```

I wonder if this is necessary or if we can be more relaxed. What if it was just you can always add `[whitespace]* modifier [whistepace]* pattern` to the end of any pattern, and the modifier just changes the behavior until the next modifier. Is there any reason to disallow this?

I'm thinking about a completely hypothetical case of writing code to modifying someone else's pattern and just add `+10.0.0.0/12` or `\ 10.1.2.3/5`, without having to do complicated string analysis of the pattern.

[Feel free to say this is too hard or not worth it or a bid idea -- legit just wondering.]

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1622)*

**Comment by anothermattbrown** [comment]
Review status: all files reviewed, 3 unresolved discussions (waiting on @anothermattbrown)

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/specifier/ConstantWildcardSetIpSpaceSpecifierFactory.java, line 22 at r1](https://reviewable.io/reviews/batfish/batfish/1622#-LEXA0ITDj2xd0kj5Io7:-LEk5NRr62wiuQ2IaXUQ:b-ovwaw7) ([raw file](https://github.com/batfish/batfish/blob/834d701d332232c93801b9f160a26f33f8e19c2f/projects/batfish-common-protocol/src/main/java/org/batfish/specifier/ConstantWildcardSetIpSpaceSpecifierFactory.java#L22)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

use `{@code foo}` to make this look better?
</blockquote></details>

Good idea.

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/specifier/ConstantWildcardSetIpSpaceSpecifierFactoryTest.java, line 61 at r1](https://reviewable.io/reviews/batfish/batfish/1622#-LEXAQOw4bQCqhdfeFG4:-LEk4WLK4nC05uqaZEYb:b-whx863) ([raw file](https://github.com/batfish/batfish/blob/834d701d332232c93801b9f160a26f33f8e19c2f/projects/batfish-common-protocol/src/test/java/org/batfish/specifier/ConstantWildcardSetIpSpaceSpecifierFactoryTest.java#L61)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I wonder if this is necessary or if we can be more relaxed. What if it was just you can always add `[whitespace]* modifier [whistepace]* pattern` to the end of any pattern, and the modifier just changes the behavior until the next modifier. Is there any reason to disallow this?

I'm thinking about a completely hypothetical case of writing code to modifying someone else's pattern and just add `+10.0.0.0/12` or `\ 10.1.2.3/5`, without having to do complicated string analysis of the pattern.

[Feel free to say this is too hard or not worth it or a bid idea -- legit just wondering.]
</blockquote></details>

Good idea. That would work well for `AclIpSpace`, where you can alternate between accepting and rejecting as many times as you want. `IpWildcardSetIpSpace` requires all whitelisted wildcards come first. Using `AclIpSpace` with your proposed format may be the better choice long term, but I'd prefer to defer that until a later PR.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1622)*

**Comment by dhalperi** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed, 1 unresolved discussion (waiting on @anothermattbrown)

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1622)*

**Comment by anothermattbrown** [comment]
Review status: :shipit: complete! all files reviewed, all discussions resolved

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1622#-LEVF4Oh7hYEbD9T351A:-LEkBWLLBArwUcyxrYiC:b-896fix) (no related file):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

Working to get base merged into master
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1622)*

**Pull request merged**
