### PR TITLE
Add VNI interfaces to tenant VRFs

### PR DESCRIPTION
**Pull request by arifogel**
- each layer-3 VNI results in an interface in the associated VRF
- generated interface:
  - responds to ARPs for VTEP address
  - has link-local address

Follow-on work: add l3 edges between these generated interfaces based on
                VxlanTopology

### CODE REVIEW

**Review by corinaminer — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7772)* status: all files reviewed, 3 unresolved discussions (waiting on @anothermattbrown, @arifogel, and @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java, line 473 at r1](https://reviewable.io/reviews/batfish/batfish/7772#-MqRtqTD02URXj0pJ5f-:-MqRtqTD02URXj0pJ5f0:bwivvx5) ([raw file](https://github.com/batfish/batfish/blob/8bee19a438ea38ecd2b9c6d4d8a6eca7a06d6abd/projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java#L473)):*
> ```Java
>   }
> 
>   // does this value matter?
> ```

this should be a todo if it's not resolved
___
*[projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java, line 478 at r1](https://reviewable.io/reviews/batfish/batfish/7772#-MqRv1-9B8MFbNo4YRDb:-MqRv1-9B8MFbNo4YRDc:b-wgmwy2) ([raw file](https://github.com/batfish/batfish/blob/8bee19a438ea38ecd2b9c6d4d8a6eca7a06d6abd/projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java#L478)):*
> ```Java
>   /** Add an interface for each l3vni to its tenant VRF to represent endpoints of a VXLAN tunnel. */
>   @VisibleForTesting
>   static void addTenantVniInterfaces(Configuration c) {
> ```

Please add a TODO indicating that we don't yet support VXLAN tunneling on a node using sessions -- we'd have to set the `FirewallSessionInterfaceInfo` for VXLAN interface on such devices, because there's an invariant saying interfaces on a given device either all have or all do not have session info.
___
*[projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java, line 490 at r1](https://reviewable.io/reviews/batfish/batfish/7772#-MqRuh_r0PUByGSfOYjd:-MqRuh_r0PUByGSfOYje:bhc3pnh) ([raw file](https://github.com/batfish/batfish/blob/8bee19a438ea38ecd2b9c6d4d8a6eca7a06d6abd/projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java#L490)):*
> ```Java
>                         Optional.ofNullable(l3vni.getSourceAddress())
>                             .<IpSpace>map(Ip::toIpSpace)
>                             .orElse(EmptyIpSpace.INSTANCE))
> ```

Is there a point to creating an interface when the L3 VNI has no source address? A VXLAN edge must have a VTEP IP at each end, right?

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7772)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @anothermattbrown, @corinaminer, and @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java, line 473 at r1](https://reviewable.io/reviews/batfish/batfish/7772#-MqRtqTD02URXj0pJ5f-:-MqRyFzv4ZFAGGDhfQ4c:b-7rl0jd) ([raw file](https://github.com/batfish/batfish/blob/8bee19a438ea38ecd2b9c6d4d8a6eca7a06d6abd/projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java#L473)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

this should be a todo if it's not resolved
</blockquote></details>

done.
___
*[projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java, line 478 at r1](https://reviewable.io/reviews/batfish/batfish/7772#-MqRv1-9B8MFbNo4YRDb:-MqRyGps7Li66tq-HFIK:b-7rl0jd) ([raw file](https://github.com/batfish/batfish/blob/8bee19a438ea38ecd2b9c6d4d8a6eca7a06d6abd/projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java#L478)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Please add a TODO indicating that we don't yet support VXLAN tunneling on a node using sessions -- we'd have to set the `FirewallSessionInterfaceInfo` for VXLAN interface on such devices, because there's an invariant saying interfaces on a given device either all have or all do not have session info.
</blockquote></details>

done.
___
*[projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java, line 490 at r1](https://reviewable.io/reviews/batfish/batfish/7772#-MqRuh_r0PUByGSfOYjd:-MqRyDol1j3nEoBg3yt7:b6pxe56) ([raw file](https://github.com/batfish/batfish/blob/8bee19a438ea38ecd2b9c6d4d8a6eca7a06d6abd/projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java#L490)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Is there a point to creating an interface when the L3 VNI has no source address? A VXLAN edge must have a VTEP IP at each end, right?
</blockquote></details>

i had something in mind, but can't think of it. removed.

**Review by corinaminer — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7772)* status: all files reviewed, 1 unresolved discussion (waiting on @anothermattbrown, @arifogel, and @dhalperi)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/vxlan/VxlanTopologyUtils.java, line 284 at r2](https://reviewable.io/reviews/batfish/batfish/7772#-MqS2aNZ-o1XOW1ujFDJ:-MqS2aNZ-o1XOW1ujFDK:b-552w78) ([raw file](https://github.com/batfish/batfish/blob/bd67f7052b0d12e9e9a81a9dc396d7e5b61e2233/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/vxlan/VxlanTopologyUtils.java#L284)):*
> ```Java
>                     .setVrf(vrf)
>                     .setAdditionalArpIps(
>                         Optional.ofNullable(l3vni.getSourceAddress())
> ```

this is now known to be nonnull

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7772)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @anothermattbrown, @corinaminer, and @dhalperi)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/vxlan/VxlanTopologyUtils.java, line 284 at r2](https://reviewable.io/reviews/batfish/batfish/7772#-MqS2aNZ-o1XOW1ujFDJ:-MqS4SYQ9rMJJVG-z0sX:b-45j6zd) ([raw file](https://github.com/batfish/batfish/blob/bd67f7052b0d12e9e9a81a9dc396d7e5b61e2233/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/vxlan/VxlanTopologyUtils.java#L284)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

this is now known to be nonnull
</blockquote></details>

whoops, fixed

**Review by corinaminer — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7772)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown and @dhalperi)

**Pull request merged**
