### PR TITLE
docs about reachability engine

### PR DESCRIPTION
**Pull request by anothermattbrown**

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8500)* status: all files reviewed, 1 unresolved discussion (waiting on @anothermattbrown)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/8500#-NAGKveC9yb9yvzvNGI0:-NAGKveC9yb9yvzvNGI1:b-hyy0e0) (no related file):*
A great read, with high value as-is. Some thoughts for follow-ons:

* Recommended path for understanding things. Maybe, 1) go learn about how BDDs work, here's a slide deck we like. Then look at some core section of FilterLineReachability impl (or something similar?) to understand basic operation - and/or/diff/etc. Then go look at ImmutableBDDInteger to understand how numbers work... etc. 

* reachability parameter - heuristics?

* (future-looking/expandable) section on non-obvious-even-if-you-know-the-fundamentals stuff:
    * filterOriginalFlow
    * sessions and graph instrumentation
    * search route policies

*  (future-looking/expandable) section on practical concerns:
    * BDD operation count - Inside the JFactory is better than outside: orAll/andAll/andLiterals/testsVars/...
    * leaks: free/with/eq operations.
    * caching (e.g., fooToBdd) dos and don'ts.
    * convergence
    * thread safety

___
___
*[`docs/symbolic-engine.md` line 77 at r1](https://reviewable.io/reviews/batfish/batfish/8500#-NAGKVlT9U4qlojdfWvF:-NAGKVlT9U4qlojdfWvG:bxnd7yn) ([raw file](https://github.com/batfish/batfish/blob/d01960a411852665d0005e756bad9bd0ec1834eb/docs/symbolic-engine.md#L77)):*
> ```Markdown
> * [BDDInteger](https://github.com/batfish/batfish/blob/master/projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDInteger.java) has methods to create constraints on symbolic integers and IP address, including equality (`value`), inequality (`leq`, `geq`), etc.
> * [IpSpaceToBDD](https://github.com/batfish/batfish/blob/master/projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/IpSpaceToBDD.java) converts Batfish [IpSpaces](https://github.com/batfish/batfish/blob/master/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpSpace.java) to BDD.
> * [HeaderspaceToBDD](https://github.com/batfish/batfish/blob/master/projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/HeaderSpaceToBDD.java) converts Batfish [Headerspace](https://github.com/batfish/batfish/blob/master/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/HeaderSpace.java) constraints (that may occur in filter definitions or question input, for example) to BDD.
> ```

Case: HeaderSpace

Font: When possible, put class names / similar in `CodeFont`?



_Code quote:_
```Markdown
eaderspace
```

**Review by anothermattbrown — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8500)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @dhalperi)

___
*[`docs/symbolic-engine.md` line 77 at r1](https://reviewable.io/reviews/batfish/batfish/8500#-NAGKVlT9U4qlojdfWvF:-NAQg_NR2Bp_9D6wjbN-:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/d01960a411852665d0005e756bad9bd0ec1834eb/docs/symbolic-engine.md#L77)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Case: HeaderSpace

Font: When possible, put class names / similar in `CodeFont`?
</blockquote></details>

done

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8500)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown)

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8500)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown)

**Pull request merged**
