### PR TITLE
Junos: Create a /32 discard route for inactive interfaces

### PR DESCRIPTION
**Pull request by dhalperi**
https://www.juniper.net/documentation/us/en/software/junos/interfaces-fundamentals/topics/topic-map/logical-interface-properties.html#id-disabling-a-logical-interface

### CODE REVIEW

**Review by SLarkworthy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8658)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @dhalperi and @progwriter)

___
*[`projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/inactive_interface_local_route` line 3 at r1](https://reviewable.io/reviews/batfish/batfish/8658#-NOLkHGgA41bZIh4oVy6:-NOLkHGgA41bZIh4oVy7:bgcti00) ([raw file](https://github.com/batfish/batfish/blob/3b1775115c6bf857c23215f5785c355166891893/projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/inactive_interface_local_route#L3)):*
> ```
> #RANCID-CONTENT-TYPE: juniper
> set system host-name inactive_interface_local_route
> set interfaces ae0 unit 0 family inet address 1.1.1.1/24
> ```

curious: the documentation you linked lists "disable" as the way to disable an interface. What makes this interface inactive?

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8658)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @progwriter and @SLarkworthy)

___
*[`projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/inactive_interface_local_route` line 3 at r1](https://reviewable.io/reviews/batfish/batfish/8658#-NOLkHGgA41bZIh4oVy6:-NOLr99E1DouJyxQPoFU:b-732p4u) ([raw file](https://github.com/batfish/batfish/blob/3b1775115c6bf857c23215f5785c355166891893/projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/inactive_interface_local_route#L3)):*
<details><summary><i>Previously, SLarkworthy (Sarah Larkworthy) wrote…</i></summary><blockquote>

curious: the documentation you linked lists "disable" as the way to disable an interface. What makes this interface inactive? 
</blockquote></details>

`ae` is an Aggregated Ethernet interface. It's a virtual interface that needs to have physical interfaces mapped to it in order to be up.

This is the specific use case we saw in our labs, so wanted to use that directly.

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8658)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @progwriter and @SLarkworthy)

___
*[`projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/inactive_interface_local_route` line 3 at r1](https://reviewable.io/reviews/batfish/batfish/8658#-NOLkHGgA41bZIh4oVy6:-NOLrMKDCPAUCf-Hcglm:bcprlfm) ([raw file](https://github.com/batfish/batfish/blob/3b1775115c6bf857c23215f5785c355166891893/projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/inactive_interface_local_route#L3)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

`ae` is an Aggregated Ethernet interface. It's a virtual interface that needs to have physical interfaces mapped to it in order to be up.

This is the specific use case we saw in our labs, so wanted to use that directly.
</blockquote></details>

(there is no physical interface in this config, so the `ae` will be down.)

**Review by SLarkworthy — COMMENTED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8658#-:-NOLsyinBxmCsM3h5es2:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi and @progwriter)

___
*[`projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/inactive_interface_local_route` line 3 at r1](https://reviewable.io/reviews/batfish/batfish/8658#-NOLkHGgA41bZIh4oVy6:-NOLsp580_lbufnZzXVX:b-271ftq) ([raw file](https://github.com/batfish/batfish/blob/3b1775115c6bf857c23215f5785c355166891893/projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/inactive_interface_local_route#L3)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

(there is no physical interface in this config, so the `ae` will be down.)
</blockquote></details>

got it, thanks for clarifying! I assumed it had to do with the lack of connections.

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8658)* status: all files reviewed, 1 unresolved discussion (waiting on @progwriter and @SLarkworthy)

___
*[`projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/inactive_interface_local_route` line 3 at r1](https://reviewable.io/reviews/batfish/batfish/8658#-NOLkHGgA41bZIh4oVy6:-NOLuDUu-r5NFsbiHoko:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/3b1775115c6bf857c23215f5785c355166891893/projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/inactive_interface_local_route#L3)):*
<details><summary><i>Previously, SLarkworthy (Sarah Larkworthy) wrote…</i></summary><blockquote>

got it, thanks for clarifying! I assumed it had to do with the lack of connections.
</blockquote></details>

Done.

**Pull request merged**
