### PR TITLE
use GNU_FIND

### PR DESCRIPTION
**Pull request by anothermattbrown**

### CODE REVIEW

**Comment by arifogel** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[.travis/build.sh, line 2 at r2](https://reviewable.io/reviews/batfish/batfish/1601#-LEL_CvK8JAYBsXg4nKB:-LEL_CvK8JAYBsXg4nKC:b2lj2o7) ([raw file](https://github.com/batfish/batfish/blob/8eb8bdf06a801cc079dec8a027fff1217f931483/.travis/build.sh#L2)):*
> ```Shell
> #!/usr/bin/env bash
> . $(dirname $0)/common.sh
> ```

better:
`. "$(dirname "$0")/common.sh"`
Also please quote all other variables representing paths in this PR, e.g. `"$GNU_FIND"`

---

*[.travis/common.sh, line 1 at r2](https://reviewable.io/reviews/batfish/batfish/1601#-LEL_php0p_N660QoiSV:-LEL_php0p_N660QoiSW:b-q4r4sz) ([raw file](https://github.com/batfish/batfish/blob/8eb8bdf06a801cc079dec8a027fff1217f931483/.travis/common.sh#L1)):*
> ```Shell
> if [[ $(uname) == 'Darwin' && $(which gfind) ]]; then
> ```

`$(which gfind)` -> `-n "$(which gfind)"`

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1601)*

**Comment by anothermattbrown** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[.travis/build.sh, line 2 at r2](https://reviewable.io/reviews/batfish/batfish/1601#-LEL_CvK8JAYBsXg4nKB:-LELoeslEP0oZq_1Y6em:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/8eb8bdf06a801cc079dec8a027fff1217f931483/.travis/build.sh#L2)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

better:
`. "$(dirname "$0")/common.sh"`
Also please quote all other variables representing paths in this PR, e.g. `"$GNU_FIND"`
</blockquote></details>

Done.

---

*[.travis/common.sh, line 1 at r2](https://reviewable.io/reviews/batfish/batfish/1601#-LEL_php0p_N660QoiSV:-LELoeBbCtVDEWsTeN8R:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/8eb8bdf06a801cc079dec8a027fff1217f931483/.travis/common.sh#L1)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

`$(which gfind)` -> `-n "$(which gfind)"`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1601)*

**Comment by arifogel** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[.travis/jacoco-report.sh, line 16 at r3](https://reviewable.io/reviews/batfish/batfish/1601#-LELvbNa18IRgkTrW95I:-LELvbNa18IRgkTrW95J:bpeuevl) ([raw file](https://github.com/batfish/batfish/blob/fd5cad3e72513e4f311dccb99e44d7321127217f/.travis/jacoco-report.sh#L16)):*
> ```Shell
> arg=$1
> 
> if [ -z "$($GNU_FIND -name 'jacoco*.exec')" ]
> ```

wrap `$GNU_FIND` in quotes. the outer quotes do not count inside the parentheses. Applies below as well.

---

*[.travis/jacoco-report.sh, line 25 at r3](https://reviewable.io/reviews/batfish/batfish/1601#-LELvqCJEKZermTBE9H8:-LELvqCJEKZermTBE9H9:b-bonr2j) ([raw file](https://github.com/batfish/batfish/blob/fd5cad3e72513e4f311dccb99e44d7321127217f/.travis/jacoco-report.sh#L25)):*
> ```Shell
> 
> if [ "$arg" = 'junit' ]; then
>   java -jar "$JACOCO_CLI_JAR" merge $($GNU_FIND -name 'jacoco.exec') --destfile $JACOCO_JUNIT_DESTFILE
> ```

quote last arg

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1601)*

**Comment by anothermattbrown** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[.travis/jacoco-report.sh, line 16 at r3](https://reviewable.io/reviews/batfish/batfish/1601#-LELvbNa18IRgkTrW95I:-LEMUWmpEhgvzKLTaWlf:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/fd5cad3e72513e4f311dccb99e44d7321127217f/.travis/jacoco-report.sh#L16)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

wrap `$GNU_FIND` in quotes. the outer quotes do not count inside the parentheses. Applies below as well.
</blockquote></details>

Done.

---

*[.travis/jacoco-report.sh, line 25 at r3](https://reviewable.io/reviews/batfish/batfish/1601#-LELvqCJEKZermTBE9H8:-LEMUXC_5Uf4XvGB1VKa:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/fd5cad3e72513e4f311dccb99e44d7321127217f/.travis/jacoco-report.sh#L25)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

quote last arg
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1601)*

**Comment by dhalperi** [comment]
Dismissed @arifogel from 2 discussions.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1601)*

**Comment by dhalperi** [comment]
Manually verified Ari's explciit requests were honored, then dismissed him in case you need to merge and he's traveling.

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1601#-:-LEMX4LY0vi8hOnSVgW0:b-ly9u0d)*

**Comment by arifogel** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1601#-:-LEMe3d19nvMKgBUkRmI:bnfp4nl)*

**Pull request merged**
