### PR TITLE
Fixing routing policy null pointers + support for dynamic sessions

### PR DESCRIPTION
**Pull request by progwriter**
Context:
- We were crashing with NPE when executing next-hop-self
- Root cause: Passing in wrong VRF when creating environments in (i)bdp, fixed now.

Additional changes: 
- Support not just peer address but also peer prefix in routing policy/environment.
- Better nullable annotations (RoutingPolicy is used for multiple protocols, where we pass `peerAddress==null`
- Builder for `routingpolicy.Enviroment` to make dealing with all of this easier.
- Small fixes to ibdp that were part of #1165 for regular bdp

### CODE REVIEW

**Comment by dhalperi** [comment]
Generally LGTM, someone who understand the code infra around BGP should TAL as well. (@arifogel, I guess)?

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/Environment.java, line 61 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1201#-LAOkOYJ371ESZBlkTzj:-LAOkOYJ371ESZBlkTzk:b-zibnjr) ([raw file](https://github.com/batfish/batfish/blob/6ee63a0cbb5d1431428ea470acd10f8a8b35a615/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/Environment.java#L61)):*
> ```Java
> 
>   private Environment(
>       @Nonnull Configuration configuration,
> ```

Looks like this is now only called here. Suggest either getting rid of it entirely or moving every argument modification to the constructor, and making all fields final?

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/Environment.java, line 229 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1201#-LAOlHQp9VyQrKuUW1ib:-LAOlHQp9VyQrKuUW1ic:b-sonesf) ([raw file](https://github.com/batfish/batfish/blob/6ee63a0cbb5d1431428ea470acd10f8a8b35a615/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/Environment.java#L229)):*
> ```Java
> 
>     public static Builder newEnvironment(@Nonnull Configuration c) {
>       return new Builder(c);
> ```

move to Environment, just call it builder()?

Aka, caller would be `Environment.Builder b = Environment.builder(c);`

Reasoning: more concise, standardized. Like `ImmutableList`, etc.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/Environment.java, line 349 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1201#-LAOnA6sEW2_S-Ec1WF4:-LAOnA6sEW2_S-Ec1WF5:b-erpc4p) ([raw file](https://github.com/batfish/batfish/blob/6ee63a0cbb5d1431428ea470acd10f8a8b35a615/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/Environment.java#L349)):*
> ```Java
>       environment._defaultPolicy = this._defaultPolicy;
>       environment._callExprContext = this._callExprContext;
>       return environment;
> ```

see other comment about Environment constructor.

Suspect it will be easier to confirm that this contains all the fields if they are alphabetized or otherwise ordered.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/PeerAddressNextHop.java, line 9 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1201#-LAOnrIJ6j34QC2X4PVf:-LAOnrIJ6j34QC2X4PVg:bf1ig2l) ([raw file](https://github.com/batfish/batfish/blob/6ee63a0cbb5d1431428ea470acd10f8a8b35a615/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/PeerAddressNextHop.java#L9)):*
> ```Java
> public class PeerAddressNextHop extends NextHopExpr {
> 
>   private static final long serialVersionUID = 1L;
> ```

Looks like this class is a singleton -- actually make it one? Then equals check can be fully simplified to this == other, etc.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/SelfNextHop.java, line 12 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1201#-LAOnzjQApMsWFQlUk5a:-LAOnzjQApMsWFQlUk5b:b-8f7u7s) ([raw file](https://github.com/batfish/batfish/blob/6ee63a0cbb5d1431428ea470acd10f8a8b35a615/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/SelfNextHop.java#L12)):*
> ```Java
> public class SelfNextHop extends NextHopExpr {
> 
>   private static final long serialVersionUID = 1L;
> ```

singleton.

---

*[projects/batfish/src/main/java/org/batfish/ibdp/VirtualRouter.java, line 2244 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1201#-LAOp9O99VbzKI1zn4F7:-LAOp9O99VbzKI1zn4F8:be0592v) ([raw file](https://github.com/batfish/batfish/blob/6ee63a0cbb5d1431428ea470acd10f8a8b35a615/projects/batfish/src/main/java/org/batfish/ibdp/VirtualRouter.java#L2244)):*
> ```Java
>     for (BgpNeighbor neighbor : _vrf.getBgpProcess().getNeighbors().values()) {
>       if (!bgpTopology.nodes().contains(neighbor)) {
>         continue;
> ```

Should these be warned about? Have there already been warnings elsewhere?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1201#-:-LAOpJ9N2me0vOaUvjji:bm3up5b)*

**Comment by arifogel** [comment]
I share @dhalperi's concerns. Looks mostly good.

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/PeerAddressNextHop.java, line 9 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1201#-LAOnrIJ6j34QC2X4PVf:-LAPE_fB2O3ZFaAjIYCN:bpt69fc) ([raw file](https://github.com/batfish/batfish/blob/6ee63a0cbb5d1431428ea470acd10f8a8b35a615/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/PeerAddressNextHop.java#L9)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Looks like this class is a singleton -- actually make it one? Then equals check can be fully simplified to this == other, etc.
</blockquote></details>

Careful! Singleton reference equality is not preserved after deserialization (except for enums)! You should use `instanceof` for equality check.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1201#-:-LAPFKWxCVztu4eiLZk7:b-3swe54)*

**Comment by dhalperi** [comment]
:lgtm:

---

Reviewed 11 of 11 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1201#-:-LAQLL9IEe_QPbpXmQXb:bnfp4nl)*

**Comment by progwriter** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/Environment.java, line 229 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1201#-LAOlHQp9VyQrKuUW1ib:-LAQL0XZBUIxJDOzzp5N:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/6ee63a0cbb5d1431428ea470acd10f8a8b35a615/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/Environment.java#L229)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

move to Environment, just call it builder()?

Aka, caller would be `Environment.Builder b = Environment.builder(c);`

Reasoning: more concise, standardized. Like `ImmutableList`, etc.
</blockquote></details>

Done.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/Environment.java, line 349 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1201#-LAOnA6sEW2_S-Ec1WF4:-LAQL0pK3bOzlm2unhc0:b-wvddb) ([raw file](https://github.com/batfish/batfish/blob/6ee63a0cbb5d1431428ea470acd10f8a8b35a615/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/Environment.java#L349)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

see other comment about Environment constructor.

Suspect it will be easier to confirm that this contains all the fields if they are alphabetized or otherwise ordered.
</blockquote></details>

Done; Can't make all of them final, but made as many as I can.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/PeerAddressNextHop.java, line 9 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1201#-LAOnrIJ6j34QC2X4PVf:-LAQL51b0BVlMiCtKc95:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/6ee63a0cbb5d1431428ea470acd10f8a8b35a615/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/PeerAddressNextHop.java#L9)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Careful! Singleton reference equality is not preserved after deserialization (except for enums)! You should use `instanceof` for equality check.
</blockquote></details>

Done.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/SelfNextHop.java, line 12 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1201#-LAOnzjQApMsWFQlUk5a:-LAQL5_Z1IRAB-0Pto3Y:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/6ee63a0cbb5d1431428ea470acd10f8a8b35a615/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/SelfNextHop.java#L12)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

singleton.
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/ibdp/VirtualRouter.java, line 2244 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1201#-LAOp9O99VbzKI1zn4F7:-LAQL5xn1rJGO9x3s8ti:boktvwg) ([raw file](https://github.com/batfish/batfish/blob/6ee63a0cbb5d1431428ea470acd10f8a8b35a615/projects/batfish/src/main/java/org/batfish/ibdp/VirtualRouter.java#L2244)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Should these be warned about? Have there already been warnings elsewhere?
</blockquote></details>

I can see it either going either way.
- Long term: we need infrastructure to generate and retrieve meaningful DP warnings
- This particular one is not something user needs to know about per se, as it would be a duplicate of a bgpsessionstatus check

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1201)*

**Pull request merged**
