### PR TITLE
switch to javahamcrest 2.0.0.0

### PR DESCRIPTION
**Pull request by arifogel**

### CODE REVIEW

**Comment by arifogel** [comment]
Review status: 0 of 11 files reviewed at latest revision, all discussions resolved.

---

*[projects/pom.xml, line 59 at r2](https://reviewable.io/reviews/batfish/batfish/1400#-LC_EJ8f5JR2BXHOrZaN:-LC_EJ8f5JR2BXHOrZaO:bgv2iqe) ([raw file](https://github.com/batfish/batfish/blob/4239923b9fa86a77ecfb83a13097377d911298a2/projects/pom.xml#L59)):*
> ```XML
>     <grizzly.version>2.3.18</grizzly.version>
>     <guava.version>22.0</guava.version>
>     <hamcrest-junit.version>2.0.0.0</hamcrest-junit.version>
> ```

@dhalperi Should I toss hamcrest-junit? I'm having trouble understanding whether to get rid of it, or make references to it instead of some other thing in our tests.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1400)*

**Comment by dhalperi** [comment]
Reviewed 11 of 11 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/pom.xml, line 59 at r2](https://reviewable.io/reviews/batfish/batfish/1400#-LC_EJ8f5JR2BXHOrZaN:-LC_Gkii8Hh0JqvyDY5t:bxagmoo) ([raw file](https://github.com/batfish/batfish/blob/4239923b9fa86a77ecfb83a13097377d911298a2/projects/pom.xml#L59)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

@dhalperi Should I toss hamcrest-junit? I'm having trouble understanding whether to get rid of it, or make references to it instead of some other thing in our tests.
</blockquote></details>

what's in it? what's it for? I have little info here.

Also, is it versioned separately from the rest of hamcrest? If not, keep the same version anyway.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1400)*

**Comment by arifogel** [comment]
Review status: 10 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/pom.xml, line 59 at r2](https://reviewable.io/reviews/batfish/batfish/1400#-LC_EJ8f5JR2BXHOrZaN:-LC_HMmA9U9Dnww5ds6o:b4yzadp) ([raw file](https://github.com/batfish/batfish/blob/4239923b9fa86a77ecfb83a13097377d911298a2/projects/pom.xml#L59)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

what's in it? what's it for? I have little info here.

Also, is it versioned separately from the rest of hamcrest? If not, keep the same version anyway.
</blockquote></details>

It seems it is prep for a future version of junit that won't have hamcrest stuff built in. See the exclusions added in this PR. Removing for now.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1400)*

**Comment by dhalperi** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1400)*

**Pull request merged**
