### PR TITLE
small reduced reachability fixes

### PR DESCRIPTION
**Pull request by anothermattbrown**
- make sure `_settings.getDiffQuestion()` is true, because otherwise we get no results.
- rename query variables and add comments

### CODE REVIEW

**Comment by dhalperi** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed, 2 unresolved discussions (waiting on @anothermattbrown)

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 3521 at r1](https://reviewable.io/reviews/batfish/batfish/1677#-LF5294T9Mi1rQXsITMh:-LF5294U6_TP45gaKMLn:bae3x37) ([raw file](https://github.com/batfish/batfish/blob/67d8f5e6938153daa6fee5595610b1c964342d94/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L3521)):*
> ```Java
>   public AnswerElement reducedReachability(ReachabilityParameters params) {
>     /* This always should be (and has to be) true, but the question doesn't enforce it. */
>     _settings.setDiffQuestion(true);
> ```

I'm not quite sure how this gets set wrong. How did you trigger this code path?

See https://github.com/batfish/batfish/blob/master/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L610-L617

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 3614 at r1](https://reviewable.io/reviews/batfish/batfish/1677#-LF52TUE0oo6dWnin87o:-LF52TUE0oo6dWnin87p:bayjziw) ([raw file](https://github.com/batfish/batfish/blob/67d8f5e6938153daa6fee5595610b1c964342d94/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L3614)):*
<details><summary><i alt="summary">Quoted 10 lines of code…</i></summary>

> ```
>                   StandardReachabilityQuerySynthesizer deltaQuery =
>                       StandardReachabilityQuerySynthesizer.builder()
>                           .setActions(baseParams.getActions())
>                           .setHeaderSpace(baseParams.getHeaderSpace())
>                           .setFinalNodes(ImmutableSet.of())
>                           .setForbiddenTransitNodes(ImmutableSet.of())
>                           .setRequiredTransitNodes(ImmutableSet.of())
>                           .setSrcIpConstraints(srcIpConstraint)
>                           .setSrcNatted(baseParams.getSrcNatted())
>                           .build();
> ```
</details>


(If you know... ;) Add a comment why we use `baseParams` instead of `deltaParams` here? We only use delta params for synthesizing the data plane, by why...

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1677)*

**Comment by anothermattbrown** [comment]
Review status: all files reviewed, 2 unresolved discussions (waiting on @anothermattbrown)

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 3521 at r1](https://reviewable.io/reviews/batfish/batfish/1677#-LF5294T9Mi1rQXsITMh:-LFIp2PuBhBMF64tFPDF:btay3cl) ([raw file](https://github.com/batfish/batfish/blob/67d8f5e6938153daa6fee5595610b1c964342d94/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L3521)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I'm not quite sure how this gets set wrong. How did you trigger this code path?

See https://github.com/batfish/batfish/blob/master/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L610-L617
</blockquote></details>

This bit me by using `reachability type='reduced'` without `differential=true`

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 3614 at r1](https://reviewable.io/reviews/batfish/batfish/1677#-LF52TUE0oo6dWnin87o:-LFIxEez3ytcKeX7Ci5c:b-8awece) ([raw file](https://github.com/batfish/batfish/blob/67d8f5e6938153daa6fee5595610b1c964342d94/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L3614)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
>                   StandardReachabilityQuerySynthesizer deltaQuery =
>                       StandardReachabilityQuerySynthesizer.builder()
>                           .setActions(baseParams.getActions())
>                           .setHeaderSpace(baseParams.getHeaderSpace())
>                           .setFinalNodes(ImmutableSet.of())
>                           .setForbiddenTransitNodes(ImmutableSet.of())
>                           .setRequiredTransitNodes(ImmutableSet.of())
>                           .setSrcIpConstraints(srcIpConstraint)
>                           .setSrcNatted(baseParams.getSrcNatted())
>                           .build();
> ```

(If you know... ;) Add a comment why we use `baseParams` instead of `deltaParams` here? We only use delta params for synthesizing the data plane, by why...
</blockquote></details>

It's an invariant that `baseParams` and `deltaParams` will always agree on `actions`, `headerSpace,` and `srcNatted` (admittedly this is not at all clear). I'll change this to use `deltaParams` to protect our future sanity :). I'll add a comment too. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1677)*

**Comment by dhalperi** [comment]
*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 3521 at r1](https://reviewable.io/reviews/batfish/batfish/1677#-LF5294T9Mi1rQXsITMh:-LFJ0WTH9Tv2lfkT6yRC:b1fqtzb) ([raw file](https://github.com/batfish/batfish/blob/67d8f5e6938153daa6fee5595610b1c964342d94/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L3521)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

This bit me by using `reachability type='reduced'` without `differential=true`
</blockquote></details>

In that case, you should get an exception before ever reaching this code:

https://github.com/batfish/batfish/blob/master/projects/question/src/main/java/org/batfish/question/ReachabilityQuestionPlugin.java#L45-L52

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1677)*

**Comment by dhalperi** [comment]
*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 3558 at r2](https://reviewable.io/reviews/batfish/batfish/1677#-LFJ5qpb3cgxMJBHMKkM:-LFJ5qpb3cgxMJBHMKkN:b69d980) ([raw file](https://github.com/batfish/batfish/blob/d947381fc1e1b2b8a1bc5659d1b34c6b3401dc97/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L3558)):*
> ```Java
>         || baseParams.getHeaderSpace().equals(deltaParams.getHeaderSpace());
>     assert baseParams.getSpecialize() == deltaParams.getSpecialize();
>     assert baseParams.getSrcNatted().equals(deltaParams.getSrcNatted());
> ```

sanity check: asserts are not run in most environments. You only want this for testing / IDE development, not at runtime?

If you want this to run even in production, use `verify` or `checkState` or something like that.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1677)*

**Comment by dhalperi** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed, 3 unresolved discussions (waiting on @anothermattbrown and @dhalperi)

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1677)*

**Comment by dhalperi** [comment]
:lgtm:

---

Review status: all files reviewed, 3 unresolved discussions (waiting on @anothermattbrown and @dhalperi)

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1677#-:-LFJC_R0BnaHCcA-aFqv:bnfp4nl)*

**Comment by dhalperi** [comment]
Review status: all files reviewed, 3 unresolved discussions (waiting on @anothermattbrown and @dhalperi)

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 3614 at r1](https://reviewable.io/reviews/batfish/batfish/1677#-LF52TUE0oo6dWnin87o:-LFJCeju9vV9Qadypnf4:b32wtd) ([raw file](https://github.com/batfish/batfish/blob/67d8f5e6938153daa6fee5595610b1c964342d94/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L3614)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

It's an invariant that `baseParams` and `deltaParams` will always agree on `actions`, `headerSpace,` and `srcNatted` (admittedly this is not at all clear). I'll change this to use `deltaParams` to protect our future sanity :). I'll add a comment too. 
</blockquote></details>

ok

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1677)*

**Comment by anothermattbrown** [comment]
Review status: all files reviewed, 2 unresolved discussions (waiting on @anothermattbrown)

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 3521 at r1](https://reviewable.io/reviews/batfish/batfish/1677#-LF5294T9Mi1rQXsITMh:-LFJDED44euS3Gzgd-wM:b-wh38bt) ([raw file](https://github.com/batfish/batfish/blob/67d8f5e6938153daa6fee5595610b1c964342d94/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L3521)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

In that case, you should get an exception before ever reaching this code:

https://github.com/batfish/batfish/blob/master/projects/question/src/main/java/org/batfish/question/ReachabilityQuestionPlugin.java#L45-L52

</blockquote></details>

Removed in favor of fixing that elsewhere

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 3558 at r2](https://reviewable.io/reviews/batfish/batfish/1677#-LFJ5qpb3cgxMJBHMKkM:-LFJ92lv7oRYspXIxCAP:b4u1rxr) ([raw file](https://github.com/batfish/batfish/blob/d947381fc1e1b2b8a1bc5659d1b34c6b3401dc97/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L3558)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

sanity check: asserts are not run in most environments. You only want this for testing / IDE development, not at runtime?

If you want this to run even in production, use `verify` or `checkState` or something like that.
</blockquote></details>

Yes this was intentional; I don't see a need to run in production. This will only ever change if a bug is introduced in the parameter resolution code.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1677)*

**Comment by dhalperi** [comment]
(Was already LGTMed and down to non-blocking comments, but I've resolved those explicitly.)

---

Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1677#-:-LFJgmvx2HXqQOHk4I5O:bbiq6qj)*

**Pull request merged**
