### PR TITLE
BDD: progress towards less garbage

### PR DESCRIPTION
**Pull request by dhalperi**
Everything from #7831, with bugfixes.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7847)* status: 10 of 14 files reviewed, all discussions resolved (waiting on @anothermattbrown and @dhalperi)

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7847)* status: 10 of 14 files reviewed, all discussions resolved (waiting on @anothermattbrown and @dhalperi)

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7847)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dhalperi)

**Review by dhalperi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7847)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
