### PR TITLE
Garbage collect network blobs older than oldest snapshot

### PR DESCRIPTION
**Pull request by arifogel**
- fixes batfish/batfish#8546
- during network GC, fetch oldest last modified time of all extant snapshot files
- delete network blobs older than that time, or now minus GC skew allowance if earlier

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8552#-:-NCgaZro3n8jjE9uVF8Q:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @arifogel)

___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java` line 2013 at r1](https://reviewable.io/reviews/batfish/batfish/8552#-NCgZs_z6fFs-fv2YkWB:-NCgZs_z6fFs-fv2YkWC:b-9eqv10) ([raw file](https://github.com/batfish/batfish/blob/0e8587a6ec5f9bb3c266278723529635927c40ce/projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java#L2013)):*
> ```Java
>           oldestExtantSnapshotFileModifiedDate.isBefore(expungeBeforeDate)
>               ? oldestExtantSnapshotFileModifiedDate
>               : expungeBeforeDate;
> ```

does Guava `Comparators.min` work? or do we need special handling?



_Code quote:_
```Java
      Instant blobExpungeBeforeDate =
          oldestExtantSnapshotFileModifiedDate.isBefore(expungeBeforeDate)
              ? oldestExtantSnapshotFileModifiedDate
              : expungeBeforeDate;
```
___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java` line 2059 at r1](https://reviewable.io/reviews/batfish/batfish/8552#-NCg_YAO-3rRDHrkY148:-NCg_YAO-3rRDHrkY149:b-owpgt7) ([raw file](https://github.com/batfish/batfish/blob/0e8587a6ec5f9bb3c266278723529635927c40ce/projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java#L2059)):*
> ```Java
>                     extantSnapshotIds.contains(
>                         new SnapshotId(snapshotDir.getFileName().toString()).toString()))
>             .map(this::getOldestEntryLastModifiedDate)
> ```

Why do we have to recurse the entire snapshot folder? Can't we use directory create time, snapshot metadata, or something else?



_Code quote:_
```Java
getOldestEntryLastModifiedDate
```

**Comment by dhalperi** [comment]
FYI if you merge master we should get coverage data again. Apparently codecov lost their stuff

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8552)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @dhalperi)

___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java` line 2013 at r1](https://reviewable.io/reviews/batfish/batfish/8552#-NCgZs_z6fFs-fv2YkWB:-NCgbSyaD9fa3he0Idr0:brrk9fh) ([raw file](https://github.com/batfish/batfish/blob/0e8587a6ec5f9bb3c266278723529635927c40ce/projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java#L2013)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

does Guava `Comparators.min` work? or do we need special handling?
</blockquote></details>

Thanks, was looking for something like that
___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java` line 2059 at r1](https://reviewable.io/reviews/batfish/batfish/8552#-NCg_YAO-3rRDHrkY148:-NCgbu1v3Q1gu8UOCz4D:b1zeaim) ([raw file](https://github.com/batfish/batfish/blob/0e8587a6ec5f9bb3c266278723529635927c40ce/projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java#L2059)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Why do we have to recurse the entire snapshot folder? Can't we use directory create time, snapshot metadata, or something else?
</blockquote></details>

creation time works, switched to that

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8552)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel)

___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java` line 2059 at r2](https://reviewable.io/reviews/batfish/batfish/8552#-NCggmea1aIO4-Ql2Ox6:-NCggmea1aIO4-Ql2Ox7:b-olawdy) ([raw file](https://github.com/batfish/batfish/blob/5fa027712a11a04e25e8298058bc55ffc332ad5f/projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java#L2059)):*
> ```Java
>                       String.format(
>                           "Error loading snapshot metadata for networkId '%s' snapshotId '%s': %s",
>                           networkId, snapshotId, Throwables.getStackTraceAsString(e)));
> ```

I'm missing something there.

If you only want to stringify all the arguments, drop the String.format and just use logging syntax to do it.

If you want the Log4j2 handling of the exception, keep String.format but pass use the `LOGGER.error(String, Throwable)` API.

I don't think it ever makes sense to use `LOGGER.error(String)` unless `String` is a hardcoded constant.



_Code quote:_
```Java
                  LOGGER.error(
                      String.format(
                          "Error loading snapshot metadata for networkId '%s' snapshotId '%s': %s",
                          networkId, snapshotId, Throwables.getStackTraceAsString(e)));
```

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8552)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java` line 2059 at r2](https://reviewable.io/reviews/batfish/batfish/8552#-NCggmea1aIO4-Ql2Ox6:-NCgilvuD_VDUJMxq9AZ:b-886gsx) ([raw file](https://github.com/batfish/batfish/blob/5fa027712a11a04e25e8298058bc55ffc332ad5f/projects/batfish-common-protocol/src/main/java/org/batfish/storage/FileBasedStorage.java#L2059)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I'm missing something there.

If you only want to stringify all the arguments, drop the String.format and just use logging syntax to do it.

If you want the Log4j2 handling of the exception, keep String.format but pass use the `LOGGER.error(String, Throwable)` API.

I don't think it ever makes sense to use `LOGGER.error(String)` unless `String` is a hardcoded constant.
</blockquote></details>

Fixed

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8552)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi)

**Pull request merged**
