### PR TITLE
Add parsing support for alternate PAN config format

### PR DESCRIPTION
**Pull request by sfraint**
Add support for `filesystem` format PAN configs.

Previously, only `show` format configs were supported, the kind seen when issuing `show` command on the device CLI.

### CODE REVIEW

**Comment by anothermattbrown** [comment]
Reviewed 4 of 4 files at r1, 1 of 1 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

---

*[projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java, line 137 at r2](https://reviewable.io/reviews/batfish/batfish/1656#-LEvkH8U7KNXMpdsQlxR:-LEvkH8U7KNXMpdsQlxS:beo57pd) ([raw file](https://github.com/batfish/batfish/blob/e4705d8c1daa574f485a5287087f68bdbdd5fed3/projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java#L137)):*
> ```Java
>   @Override
>   public void enterSet_line_config_devices(Set_line_config_devicesContext ctx) {
>     if (ctx.name != null) {
> ```

What does it mean when `ctx.name` is `null`? Does it warrant a warning?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1656)*

**Comment by arifogel** [comment]
Reviewed 4 of 4 files at r1, 1 of 1 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1656)*

**Comment by arifogel** [comment]
:lgtm: modulo other review comments

---

Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1656#-:-LEvoenp33Opi-clb9jR:byeyh69)*

**Comment by sfraint** [comment]
Review status: :shipit: complete! all files reviewed, all discussions resolved

---

*[projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java, line 137 at r2](https://reviewable.io/reviews/batfish/batfish/1656#-LEvkH8U7KNXMpdsQlxR:-LEvo-Jq2JvY4qI3s05f:b-fehri2) ([raw file](https://github.com/batfish/batfish/blob/e4705d8c1daa574f485a5287087f68bdbdd5fed3/projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java#L137)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

What does it mean when `ctx.name` is `null`? Does it warrant a warning?
</blockquote></details>

No warning needed, it just means the line is using the simple syntax, not the "verbose" filesystem-style syntax.

For example, the following two lines should produce the same output:
`set deviceconfig system hostname BLAH` (name is null here)
`set config devices localhost.localdomain deviceconfig system hostname BLAH` (name is localhost.localdomain here)

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1656)*

**Comment by sfraint** [comment]
Review status: :shipit: complete! all files reviewed, all discussions resolved

---

*[projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java, line 137 at r2](https://reviewable.io/reviews/batfish/batfish/1656#-LEvkH8U7KNXMpdsQlxR:-LEvqTAk7DRx0DRcO1eG:b-lm2y3n) ([raw file](https://github.com/batfish/batfish/blob/e4705d8c1daa574f485a5287087f68bdbdd5fed3/projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java#L137)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

No warning needed, it just means the line is using the simple syntax, not the "verbose" filesystem-style syntax.

For example, the following two lines should produce the same output:
`set deviceconfig system hostname BLAH` (name is null here)
`set config devices localhost.localdomain deviceconfig system hostname BLAH` (name is localhost.localdomain here)
</blockquote></details>

Alternatively, could split the two syntaxes out:
* Add extra rules in the parser to separately handle the different syntaxes
* Add extra rule-handling-methods in `ConfigurationBuilder` (but be able to skip the null check)

I just opted for this approach since it involved fewer rules and methods.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1656)*

**Pull request merged**
