### PR TITLE
Sonic initial conversion

### PR DESCRIPTION
**Pull request by ratulm**

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7767)* status: all files reviewed, 8 unresolved discussions (waiting on @ratulm)

___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/Port.java, line 14 at r1](https://reviewable.io/reviews/batfish/batfish/7767#-MqN8MlY14_CvZTju4yc:-MqN8MlY14_CvZTju4yd:b-fwmjlh) ([raw file](https://github.com/batfish/batfish/blob/149da56c097b46259325d9fac7e72730b3f38ac7/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/Port.java#L14)):*
> ```Java
> 
> /** Represents PORT object: https://github.com/Azure/SONiC/wiki/Configuration#port */
> @ParametersAreNonnullByDefault
> ```

nit: unnecessary with package-info
___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/Port.java, line 37 at r1](https://reviewable.io/reviews/batfish/batfish/7767#-MqN8Pwv0gE8xLDQ7gKn:-MqN8Pwv0gE8xLDQ7gKo:b9ua6o) ([raw file](https://github.com/batfish/batfish/blob/149da56c097b46259325d9fac7e72730b3f38ac7/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/Port.java#L37)):*
> ```Java
> 
>   @JsonCreator
>   private static Port create(
> ```

nit: `@Nonnull here and for all other applicable functions in this file
___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConfiguration.java, line 44 at r1](https://reviewable.io/reviews/batfish/batfish/7767#-MqN8mCmBVCfM7ewKKk3:-MqN8mCmBVCfM7ewKKk4:b-zayvdr) ([raw file](https://github.com/batfish/batfish/blob/149da56c097b46259325d9fac7e72730b3f38ac7/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConfiguration.java#L44)):*
> ```Java
>   @Override
>   public List<Configuration> toVendorIndependentConfigurations() throws VendorConversionException {
>     checkArgument(_hostname != null, "Conversion called before hostname was set");
> ```

nit: should be `checkState`
___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConfiguration.java, line 84 at r1](https://reviewable.io/reviews/batfish/batfish/7767#-MqN90qX7gxbebObHVNo:-MqN90qX7gxbebObHVNp:bkzergo) ([raw file](https://github.com/batfish/batfish/blob/149da56c097b46259325d9fac7e72730b3f38ac7/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConfiguration.java#L84)):*
> ```Java
>   }
> 
>   @Nullable
> ```

Either this should be `@Nonnull`, the field should be `@Nullable`, or you should just remove the annotations from both.
And you should check state or assert non-null before conversion.
___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConfiguration.java, line 100 at r1](https://reviewable.io/reviews/batfish/batfish/7767#-MqN9PEw3owktL-jzgDw:-MqN9PEw3owktL-jzgDx:b-x07kdz) ([raw file](https://github.com/batfish/batfish/blob/149da56c097b46259325d9fac7e72730b3f38ac7/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConfiguration.java#L100)):*
> ```Java
>   @Override
>   public boolean hasInterface(String ifaceName) {
>     return _configDb.getInterfaces().containsKey(ifaceName);
> ```

What about loopbacks, etc.? Do they also appear in `getInterfaces()`?
___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConfiguration.java, line 110 at r1](https://reviewable.io/reviews/batfish/batfish/7767#-MqN9_Rz3NlfT-iH6CVW:-MqN9_Rz3NlfT-iH6CVX:b-220qz7) ([raw file](https://github.com/batfish/batfish/blob/149da56c097b46259325d9fac7e72730b3f38ac7/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConfiguration.java#L110)):*
> ```Java
>   @Override
>   public String getInterfaceVrf(String ifaceName) {
>     if (!_configDb.getInterfaces().containsKey(ifaceName)) {
> ```

Seems like you should just use `hasInterface` to avoid duplication. Same for `getInterfaceAddresses`.
___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConfiguration.java, line 129 at r1](https://reviewable.io/reviews/batfish/batfish/7767#-MqN9rj-BC3GAZbAQ4SP:-MqN9rj-BC3GAZbAQ4SQ:b-eltz74) ([raw file](https://github.com/batfish/batfish/blob/149da56c097b46259325d9fac7e72730b3f38ac7/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConfiguration.java#L129)):*
> ```Java
>   @Override
>   public Map<String, Vxlan> getVxlans() {
>     throw new UnsupportedOperationException();
> ```

This is an override? Maybe better to just return empty map for now instead of crashing.
___
*[projects/batfish/src/test/java/org/batfish/vendor/sonic/representation/PortTest.java, line 13 at r1](https://reviewable.io/reviews/batfish/batfish/7767#-MqNAG0O-48CzcJtBdPc:-MqNAG0O-48CzcJtBdPd:bfu88kg) ([raw file](https://github.com/batfish/batfish/blob/149da56c097b46259325d9fac7e72730b3f38ac7/projects/batfish/src/test/java/org/batfish/vendor/sonic/representation/PortTest.java#L13)):*
> ```Java
>   @Test
>   public void testJavaSerialization() {
>     Port obj = Port.builder().build();
> ```

nit: we usually set non-null values in this test as a cheap test that subfields are serializable

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7767)* status: all files reviewed, 8 unresolved discussions (waiting on @ratulm)

___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConfiguration.java, line 84 at r1](https://reviewable.io/reviews/batfish/batfish/7767#-MqN90qX7gxbebObHVNo:-MqNAnHE72y_d3-aX_vg:bykdqiv) ([raw file](https://github.com/batfish/batfish/blob/149da56c097b46259325d9fac7e72730b3f38ac7/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConfiguration.java#L84)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Either this should be `@Nonnull`, the field should be `@Nullable`, or you should just remove the annotations from both.
And you should check state or assert non-null before conversion.
</blockquote></details>

Generally I'd recommend removing the annotation altogether and making it de facto nullable. This way you don't have to constantly assert or check it isn't null in deeper conversion functions.

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7767)* status: 3 of 8 files reviewed, 3 unresolved discussions (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConfiguration.java, line 100 at r1](https://reviewable.io/reviews/batfish/batfish/7767#-MqN9PEw3owktL-jzgDw:-MqNGGXY8fGhFPCFUJgU:b-kl8g3z) ([raw file](https://github.com/batfish/batfish/blob/149da56c097b46259325d9fac7e72730b3f38ac7/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConfiguration.java#L100)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

What about loopbacks, etc.? Do they also appear in `getInterfaces()`?
</blockquote></details>

good catch.
___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConfiguration.java, line 110 at r1](https://reviewable.io/reviews/batfish/batfish/7767#-MqN9_Rz3NlfT-iH6CVW:-MqNGMbK938v1fZkPy-z:bofqsic) ([raw file](https://github.com/batfish/batfish/blob/149da56c097b46259325d9fac7e72730b3f38ac7/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConfiguration.java#L110)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Seems like you should just use `hasInterface` to avoid duplication. Same for `getInterfaceAddresses`.
</blockquote></details>

made a different helper.
___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConfiguration.java, line 129 at r1](https://reviewable.io/reviews/batfish/batfish/7767#-MqN9rj-BC3GAZbAQ4SP:-MqNHLWp22nDBmtrsKCt:bdge50l) ([raw file](https://github.com/batfish/batfish/blob/149da56c097b46259325d9fac7e72730b3f38ac7/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConfiguration.java#L129)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

This is an override? Maybe better to just return empty map for now instead of crashing.
</blockquote></details>

I don't expect this function to be called since I haven't seen VXLAN modeling bits in configdb (yet). If it is called, I want to fail loudly.

**Review by arifogel — COMMENTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7767)* status: all files reviewed, 2 unresolved discussions (waiting on @ratulm)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7767#-MqNk1_78coSlphUP8Ax:-MqNk1_78coSlphUP8Ay:b-8v29ko) (no related file):*
is codecov out of date? I'm not seeing any coverage of `toVendorIndependentConfigurations`.
Also no coverage of the overridden functions in `SonicConfiguration`

---
___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConfiguration.java, line 110 at r1](https://reviewable.io/reviews/batfish/batfish/7767#-MqN9_Rz3NlfT-iH6CVW:-MqNii8b9hFbjTjiOcMk:blcdco8) ([raw file](https://github.com/batfish/batfish/blob/149da56c097b46259325d9fac7e72730b3f38ac7/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConfiguration.java#L110)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

made a different helper.
</blockquote></details>

but you've inlined the (negated) definition of hasInterface here still. could just use it instead.

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7767)* status: all files reviewed, 1 unresolved discussion (waiting on @ratulm)

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7767)* status: all files reviewed, 1 unresolved discussion (waiting on @ratulm)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7767#-MqNk1_78coSlphUP8Ax:-MqNlvbD4hCOc61LALaI:byntidq) (no related file):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

is codecov out of date? I'm not seeing any coverage of `toVendorIndependentConfigurations`.
Also no coverage of the overridden functions in `SonicConfiguration`
</blockquote></details>

On review, time for SonicGrammarTest or whatever

---

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7767)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @arifogel)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7767#-MqNk1_78coSlphUP8Ax:-MqNmN8r7VXCp5pkRhBS:b375e6j) (no related file):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

On review, time for SonicGrammarTest or whatever
</blockquote></details>

There is a SonicGrammarTest already. I extended the test there a bit. toVendorIndependentConfigurations will get tested as I add richer conversion scenarios. 

---

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7767)* status: all files reviewed, 1 unresolved discussion (waiting on @ratulm)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7767#-MqNk1_78coSlphUP8Ax:-MqNsBRw1hqylD3TwIh_:b2xj9uv) (no related file):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

There is a SonicGrammarTest already. I extended the test there a bit. toVendorIndependentConfigurations will get tested as I add richer conversion scenarios. 
</blockquote></details>

fine for now, though you're still missing coverage on some the overrides. but as you say, they should get coverage as we do more.

---

**Pull request merged**
