### PR TITLE
Arista: remove _enableIp[v6]Address predicate

### PR DESCRIPTION
**Pull request by dhalperi**

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6771)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @arifogel and @dhalperi)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6771#-MWRl-kQ46D_NiPQwziN:-MWRl-kR7OUV3IOB-Asp:bxdzyx2) (no related file):*
Working on adding more tests.

---
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/arista/AristaLexer.g4, line 5025 at r1](https://reviewable.io/reviews/batfish/batfish/6771#-MWRl26TAy-Dxhw6_6bQ:-MWRl26TAy-Dxhw6_6bR:b3v6ecs) ([raw file](https://github.com/batfish/batfish/blob/25b839bdbd2e2653201e142d618b5e1d628d4b61/projects/batfish/src/main/antlr4/org/batfish/grammar/arista/AristaLexer.g4#L5025)):*
> ```
> VARIABLE
> :
> ```

FYI I basically just took the false branch always, and then moved it last so it didn't dominate the IPV6_ADDRESS / etc tokens.

**Review by arifogel — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6771)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi)

**Review by arifogel — COMMENTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6771)* status: all files reviewed, 2 unresolved discussions (waiting on @dhalperi)

___
*[tests/parsing-tests/networks/unit-tests/configs/arista_vrf, line 10 at r2](https://reviewable.io/reviews/batfish/batfish/6771#-MWS3eIm1WYSpxb83eJN:-MWS3eIn-vu9pdR5yQ2j:bl9mtbz) ([raw file](https://github.com/batfish/batfish/blob/c6c4e3df7503a8c351212c0662984f4836e8392a/tests/parsing-tests/networks/unit-tests/configs/arista_vrf#L10)):*
> ```
> !
> vrf definition ::1
>  description name is ::1 verify it
> ```

Maybe this is out of scope for this change, but what if you put `1:2` as the vrf name?

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6771)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[tests/parsing-tests/networks/unit-tests/configs/arista_vrf, line 10 at r2](https://reviewable.io/reviews/batfish/batfish/6771#-MWS3eIm1WYSpxb83eJN:-MWSFoxK2s9JFP5Uc9DX:bs476yc) ([raw file](https://github.com/batfish/batfish/blob/c6c4e3df7503a8c351212c0662984f4836e8392a/tests/parsing-tests/networks/unit-tests/configs/arista_vrf#L10)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Maybe this is out of scope for this change, but what if you put `1:2` as the vrf name?
</blockquote></details>

As expected, does not work -- but I have a mode-fix in what felt like it should be a follow-up PR.

**Pull request merged**
