### PR TITLE
Use ISP role

### PR DESCRIPTION
**Pull request by ratulm**

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7492)* status: all files reviewed, 3 unresolved discussions (waiting on @ratulm)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/util/isp/IspModelingUtils.java, line 1117 at r1](https://reviewable.io/reviews/batfish/batfish/7492#-MlDw-Pg2uLhaox-w-Rr:-MlDw-Pg2uLhaox-w-Rs:bcdm7ty) ([raw file](https://github.com/batfish/batfish/blob/f418b38c3ad62012d5f1a06395d3fdb933d33fca/projects/batfish-common-protocol/src/main/java/org/batfish/common/util/isp/IspModelingUtils.java#L1117)):*
> ```Java
>                 .setAddressFamilyCapabilities(
>                     AddressFamilyCapabilities.builder()
>                         .setSendCommunity(ispRole == Role.PRIVATE_BACKBONE)
> ```

probably also do extended communities too.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/isp_configuration/IspNodeInfo.java, line 36 at r1](https://reviewable.io/reviews/batfish/batfish/7492#-MlDwPHcCsjBaqtcJ3_O:-MlDwPHcCsjBaqtcJ3_P:bi6t0z6) ([raw file](https://github.com/batfish/batfish/blob/f418b38c3ad62012d5f1a06395d3fdb933d33fca/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/isp_configuration/IspNodeInfo.java#L36)):*
> ```
>      * The ISP mimics a private backbone. Does not connect to the Internet and propagate
>      * communities.
> ```
Got lost in here. Maybe:

>      * The ISP mimics a private backbone. It does not connect to the Internet and so does not provide a default route. It propagates all routes learned between sites(?), including their communities.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/isp_configuration/IspNodeInfo.java, line 63 at r1](https://reviewable.io/reviews/batfish/batfish/7492#-MlDwEQPCHZUaf9hteoW:-MlDwEQPCHZUaf9hteoX:b2m93tx) ([raw file](https://github.com/batfish/batfish/blob/f418b38c3ad62012d5f1a06395d3fdb933d33fca/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/isp_configuration/IspNodeInfo.java#L63)):*
> ```
>  role 
> ```
missing a word, a %s, and the offending role value?

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7492)* status: all files reviewed, 3 unresolved discussions (waiting on @ratulm)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7492)* status: all files reviewed, 1 unresolved discussion (waiting on @ratulm)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/isp_configuration/IspNodeInfo.java, line 65 at r3](https://reviewable.io/reviews/batfish/batfish/7492#-MlE0hq63cyfRLDdYvsB:-MlE0hq63cyfRLDdYvsC:b-w7pchl) ([raw file](https://github.com/batfish/batfish/blob/9fdf831b14317571e65db6fd08e3e38084123576/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/isp_configuration/IspNodeInfo.java#L65)):*
> ```
>         "%s should not be provided unless role is TRANSIT",
>         PROP_ADDITIONAL_ANNOUNCEMENTS_TO_INTERNET,
>         PROP_ROLE);
> ```
there is still only one `%s` but two arguments.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7492)* status: all files reviewed, 1 unresolved discussion (waiting on @ratulm)

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7492)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/isp_configuration/IspNodeInfo.java, line 65 at r3](https://reviewable.io/reviews/batfish/batfish/7492#-MlE0hq63cyfRLDdYvsB:-MlE2NkJAqLACz8ag8Xu:bh03wc) ([raw file](https://github.com/batfish/batfish/blob/9fdf831b14317571e65db6fd08e3e38084123576/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/isp_configuration/IspNodeInfo.java#L65)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
>         "%s should not be provided unless role is TRANSIT",
>         PROP_ADDITIONAL_ANNOUNCEMENTS_TO_INTERNET,
>         PROP_ROLE);
> ```
there is still only one `%s` but two arguments.
</blockquote></details>

argh, thanks, done.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7492)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ratulm)

**Pull request merged**
