### PR TITLE
Juniper partial handling of bridge-domains

### PR DESCRIPTION
**Pull request by arifogel**
- parsing, some extraction and conversion
- set vlan and disable autostate on vlan of IRB in a bridge-domain
- some structure defs and refs

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8179)* status: 0 of 22 files reviewed, 1 unresolved discussion (waiting on @corinaminer, @dhalperi, and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/8179#-MyoAQOX9s9HpWXD1tzK:-MyoAQOX9s9HpWXD1tzL:bvbdbtc) (no related file):*
self-merge only

---

**Review by corinaminer — COMMENTED** [review]
> Reviewed 18 of 22 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8179)* status: 19 of 22 files reviewed, 7 unresolved discussions (waiting on @arifogel, @dhalperi, and @sfraint)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_bridge_domains.g4, line 42 at r2](https://reviewable.io/reviews/batfish/batfish/8179#-Myx_bzVCXu4pvoZhhGK:-Myx_bzWDEbi_lgf5fZz:bmmu2q) ([raw file](https://github.com/batfish/batfish/blob/a4e0c395bf0874e0c17a7b6d7e5dcecaa61f3078/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_bridge_domains.g4#L42)):*
> ```ANTLR
> ;
> 
> bd_vlan_id_list: VLAN_ID_LIST vlan_number;
> ```

a vlan-id-list can only contain one VLAN? or we're just not supporting multiple yet?
___
*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 6788 at r2](https://reviewable.io/reviews/batfish/batfish/8179#-MyxaQFkCs0TaG8KvdVw:-MyxaQFkCs0TaG8KvdVx:bcwudtb) ([raw file](https://github.com/batfish/batfish/blob/a4e0c395bf0874e0c17a7b6d7e5dcecaa61f3078/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L6788)):*
> ```Java
>     if (!_currentRoutingInstance.getBridgeDomains().containsKey(name)) {
>       _configuration.referenceStructure(
>           BRIDGE_DOMAIN, name, BRIDGE_DOMAIN_SELF_REF, ctx.getStart().getLine());
> ```

why wouldn't we add a self ref regardless of whether the bridge domain has already been created?
___
*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 6793 at r2](https://reviewable.io/reviews/batfish/batfish/8179#-Myxb86WASQnrr7tVxGJ:-Myxb86WASQnrr7tVxGK:be6pa85) ([raw file](https://github.com/batfish/batfish/blob/a4e0c395bf0874e0c17a7b6d7e5dcecaa61f3078/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L6793)):*
> ```Java
>     _configuration.defineFlattenedStructure(BRIDGE_DOMAIN, name, ctx, _parser);
>     // until we support bridge domains generally
>     todo(ctx);
> ```

are there any cases where a bridge domain will be supported after this PR? If so, i think we should avoid warning here and instead rely on parse warnings or other `todo(ctx)` calls
___
*[projects/batfish/src/main/java/org/batfish/representation/juniper/BridgeDomainVlanIdVoidVisitor.java, line 5 at r2](https://reviewable.io/reviews/batfish/batfish/8179#-MyxcyeL0KpPU4vIOY-O:-MyxcyeL0KpPU4vIOY-P:b-5092l6) ([raw file](https://github.com/batfish/batfish/blob/a4e0c395bf0874e0c17a7b6d7e5dcecaa61f3078/projects/batfish/src/main/java/org/batfish/representation/juniper/BridgeDomainVlanIdVoidVisitor.java#L5)):*
> ```Java
> public interface BridgeDomainVlanIdVoidVisitor {
> 
>   default void visit(BridgeDomainVlanId bridgeDomainVlanId) {
> ```

why make the visitor interface always return void rather than a generic?
___
*[projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java, line 3777 at r2](https://reviewable.io/reviews/batfish/batfish/8179#-MyxdDkZ3EyZwgqBg4Iz:-MyxdDk_Dl94s8x5kHee:b-9tdo29) ([raw file](https://github.com/batfish/batfish/blob/57fb8874fe9f03f6a059c1075073c9e3908ab869/projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java#L3777)):*
> ```Java
>         JuniperStructureUsage.VLAN_INTERFACE,
>         JuniperStructureUsage.VLAN_L3_INTERFACE,
>         JuniperStructureUsage.VTEP_SOURCE_INTERFACE);
> ```

why is this deleted?
___
*[projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java, line 7155 at r2](https://reviewable.io/reviews/batfish/batfish/8179#-Myxg7TW68vIjVl8NHtz:-Myxg7TW68vIjVl8NHu-:bixxh13) ([raw file](https://github.com/batfish/batfish/blob/a4e0c395bf0874e0c17a7b6d7e5dcecaa61f3078/projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java#L7155)):*
> ```Java
>       assertThat(bd.getVlanId(), equalTo(BridgeDomainVlanIdNumber.of(1)));
>     }
>     // TODO: other bridge domain configurations, i.e. bd2-5
> ```

why not test these? Can at least check vlan-id none and all

**Review by corinaminer — COMMENTED** [review]
> Reviewed 3 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8179)* status: all files reviewed, 7 unresolved discussions (waiting on @arifogel, @dhalperi, and @sfraint)

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8179)* status: 20 of 22 files reviewed, 6 unresolved discussions (waiting on @corinaminer, @dhalperi, and @sfraint)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_bridge_domains.g4, line 42 at r2](https://reviewable.io/reviews/batfish/batfish/8179#-Myx_bzVCXu4pvoZhhGK:-Myxh97i3zsRxxgbjO2v:bdng54c) ([raw file](https://github.com/batfish/batfish/blob/a4e0c395bf0874e0c17a7b6d7e5dcecaa61f3078/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_bridge_domains.g4#L42)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

a vlan-id-list can only contain one VLAN? or we're just not supporting multiple yet?
</blockquote></details>

In flattened config, you get one instance of this line per entry.
So we only need grammar for a single entry.
___
*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 6788 at r2](https://reviewable.io/reviews/batfish/batfish/8179#-MyxaQFkCs0TaG8KvdVw:-MyxhPcXA6AU-hKEV9Jj:b-aqrjb8) ([raw file](https://github.com/batfish/batfish/blob/a4e0c395bf0874e0c17a7b6d7e5dcecaa61f3078/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L6788)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

why wouldn't we add a self ref regardless of whether the bridge domain has already been created?
</blockquote></details>

I guess that's what we do elsewhere. Updated.
___
*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 6793 at r2](https://reviewable.io/reviews/batfish/batfish/8179#-Myxb86WASQnrr7tVxGJ:-Myxhebw6hjTlBm656uK:brk8dko) ([raw file](https://github.com/batfish/batfish/blob/a4e0c395bf0874e0c17a7b6d7e5dcecaa61f3078/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L6793)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

are there any cases where a bridge domain will be supported after this PR? If so, i think we should avoid warning here and instead rely on parse warnings or other `todo(ctx)` calls
</blockquote></details>

The purpose of this PR is just to prevent bridge domain IRBs from being shut down after the recent interface verification PR is un-reverted. Bridge domains will still not be supported in any meaningful sense after this PR.
___
*[projects/batfish/src/main/java/org/batfish/representation/juniper/BridgeDomainVlanIdVoidVisitor.java, line 5 at r2](https://reviewable.io/reviews/batfish/batfish/8179#-MyxcyeL0KpPU4vIOY-O:-Myxhqr1ECC-sZ88YoWv:bs9g3pg) ([raw file](https://github.com/batfish/batfish/blob/a4e0c395bf0874e0c17a7b6d7e5dcecaa61f3078/projects/batfish/src/main/java/org/batfish/representation/juniper/BridgeDomainVlanIdVoidVisitor.java#L5)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

why make the visitor interface always return void rather than a generic?
</blockquote></details>

There are no other usages of this visitor, and I don't anticipate any in the foreseeable future.
We can always make a new visitor or modify this one later if needed.
___
*[projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java, line 3777 at r2](https://reviewable.io/reviews/batfish/batfish/8179#-MyxdDkZ3EyZwgqBg4Iz:-MyxiF336UcIpBKGmcqz:b-ad7ofs) ([raw file](https://github.com/batfish/batfish/blob/57fb8874fe9f03f6a059c1075073c9e3908ab869/projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java#L3777)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

why is this deleted?
</blockquote></details>

We really should delete all of these explicit usages. This is legacy stuff.
We have a better pattern for this elsewhere  where you don't need to even explicitly mark concrete structures at all. However that is out of scope for this PR.

I deleted the explicit usages here because I needed to add another usage, and this is closer to the new pattern than adding another explicit one.
___
*[projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java, line 7155 at r2](https://reviewable.io/reviews/batfish/batfish/8179#-Myxg7TW68vIjVl8NHtz:-MyxjBab9ycBwJx7LZ2q:b-7rl0jd) ([raw file](https://github.com/batfish/batfish/blob/a4e0c395bf0874e0c17a7b6d7e5dcecaa61f3078/projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java#L7155)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

why not test these? Can at least check vlan-id none and all
</blockquote></details>

done.

**Review by corinaminer — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8179#-:-MyxsdYIDW7SdD7Yu6nb:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi and @sfraint)

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8179)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi and @sfraint)

**Pull request merged**
