### PR TITLE
CheckPoint: Associate `AccessRulebase` w/ `ManagementPackage`

### PR DESCRIPTION
**Pull request by sfraint**
Actually parse `AccessRulebase` and associate it w/ `ManagementPackage`, plus a tiny bit of refactoring.

### CODE REVIEW

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7279)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @arifogel, @corinaminer, and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7279#-Mi90PHDBJp5R9OPRjjS:-Mi90PHDBJp5R9OPRjjT:b-qfqj8j) (no related file):*
need to unrestrict the limit of 1 access-rulebase

---

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7279)* status: 0 of 9 files reviewed, all discussions resolved (waiting on @arifogel and @corinaminer)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7279#-Mi90PHDBJp5R9OPRjjS:-Mi99ZT84z1mFzlOgxkd:bvnrpcm) (no related file):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

need to unrestrict the limit of 1 access-rulebase
</blockquote></details>

updated

---

**Review by arifogel — COMMENTED** [review]
> Reviewed 4 of 8 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7279)* status: all files reviewed, 3 unresolved discussions (waiting on @corinaminer and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 1600 at r1](https://reviewable.io/reviews/batfish/batfish/7279#-Mi97WhU58WjyFicsz7N:-Mi97WhU58WjyFicsz7O:b-5nx9ky) ([raw file](https://github.com/batfish/batfish/blob/f2c2b6912e70f5a0f791ec3b84b30e6859087b2a/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L1600)):*
> ```Java
>                     new TypeReference<List<AccessRulebase>>() {})
>             : ImmutableList.of();
>     if (accessRulebases.size() != 1) {
> ```

As discussed offline, remove this constraint.
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/ManagementPackage.java, line 20 at r2](https://reviewable.io/reviews/batfish/batfish/7279#-Mi9HA9nBr1F3ymqe6xg:-Mi9HA9nBr1F3ymqe6xh:b-f13i46) ([raw file](https://github.com/batfish/batfish/blob/77804b47a2c4eadae289dd1666e67be00c32b53d/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/ManagementPackage.java#L20)):*
> ```Java
>       Package pakij) {
>     _accessRulebases =
>         accessRulebase == null ? ImmutableList.of() : ImmutableList.copyOf(accessRulebase);
> ```

Nit: Usually this logic would be done by caller. Looks like it's never null in main code. I'd suggest updating tests to pass `ImmutableList.of()`.
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/ManagementPackage.java, line 25 at r2](https://reviewable.io/reviews/batfish/batfish/7279#-Mi9HMtb2v_ZVsCj7mw7:-Mi9HMtb2v_ZVsCj7mw8:b-97fbis) ([raw file](https://github.com/batfish/batfish/blob/77804b47a2c4eadae289dd1666e67be00c32b53d/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/ManagementPackage.java#L25)):*
> ```Java
>   }
> 
>   public @Nonnull List<AccessRulebase> getAccessRulebases() {
> ```

aside: this class (and fields of this class type) should really be renamed `AccessLayer`. The rulebase is all layers.

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7279)* status: 4 of 9 files reviewed, 2 unresolved discussions (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/ManagementPackage.java, line 20 at r2](https://reviewable.io/reviews/batfish/batfish/7279#-Mi9HA9nBr1F3ymqe6xg:-MiMlgu3DgpIMJiXTnEC:bvnrpcm) ([raw file](https://github.com/batfish/batfish/blob/77804b47a2c4eadae289dd1666e67be00c32b53d/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/ManagementPackage.java#L20)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Nit: Usually this logic would be done by caller. Looks like it's never null in main code. I'd suggest updating tests to pass `ImmutableList.of()`.
</blockquote></details>

updated
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/ManagementPackage.java, line 25 at r2](https://reviewable.io/reviews/batfish/batfish/7279#-Mi9HMtb2v_ZVsCj7mw7:-MiMnFEV9qRoHNK1XzD8:bkfqvtx) ([raw file](https://github.com/batfish/batfish/blob/77804b47a2c4eadae289dd1666e67be00c32b53d/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/ManagementPackage.java#L25)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

aside: this class (and fields of this class type) should really be renamed `AccessLayer`. The rulebase is all layers.
</blockquote></details>

will rename the class separately; fields in ManagementPackage updated

**Review by arifogel — COMMENTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7279)* status: all files reviewed, 1 unresolved discussion (waiting on @corinaminer and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7279#-MiNU8wA9Q9iEGpIsiJj:-MiNU8wA9Q9iEGpIsiJk:b3g31j8) (no related file):*
Really needs some tests. of the code changes in `Batfish`. I can add some test infra to make this possible afterward.

---
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/ManagementPackage.java, line 16 at r3](https://reviewable.io/reviews/batfish/batfish/7279#-MiNSgBt61hgRwB1oOES:-MiNSgBt61hgRwB1oOET:bmcz237) ([raw file](https://github.com/batfish/batfish/blob/780d901eaa2b7824aea570574569b3a62ebf9c86/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/ManagementPackage.java#L16)):*
> ```Java
> 
>   public ManagementPackage(
>       @Nonnull List<AccessRulebase> accessLayers,
> ```

Nitty nit: You can omit `@Nonnull` for parameters, since it is the default in `package-info.java` in this folder.

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7279)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/ManagementPackage.java, line 16 at r3](https://reviewable.io/reviews/batfish/batfish/7279#-MiNSgBt61hgRwB1oOES:-MiNbRvv2CvnYoB5wMY_:bz2go) ([raw file](https://github.com/batfish/batfish/blob/780d901eaa2b7824aea570574569b3a62ebf9c86/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/ManagementPackage.java#L16)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Nitty nit: You can omit `@Nonnull` for parameters, since it is the default in `package-info.java` in this folder.
</blockquote></details>

will remove this in the next, cleanup, PR

**Pull request merged**
