### PR TITLE
Crypto map extractions

### PR DESCRIPTION
**Pull request by haverma**
- Representing crypto map as `Ipsec Policy` and `Ipsec VPN`s
- Crypto maps are used for policy based VPNs in Cisco 
- ([Policy vs Route VPNs](http://packetlife.net/blog/2011/aug/15/policy-based-vs-route-based-vpns-part-1/))
- [Data-model](https://docs.google.com/document/d/1PxBcm8SGWbSC9_XF3HxwiGfvaRgbviJ-mc_JIlgtXsI/edit?usp=sharing) - high level representation

### CODE REVIEW

**Comment by arifogel** [comment]
Reviewed 34 of 34 files at r1.
Review status: all files reviewed, 9 unresolved discussions (waiting on @haverma and @dhalperi)

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpsecVpn.java, line 20 at r1](https://reviewable.io/reviews/batfish/batfish/1670#-LFE3fObEBkqfnw9oh45:-LFE3fOc-aIJUNag8IW8:b-zam5cu) ([raw file](https://github.com/batfish/batfish/blob/c4537b8c7e8281966be799aa5ea6da46f828fb68/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpsecVpn.java#L20)):*
> ```Java
>   private static final String PROP_IPSEC_POLICY = "ipsecPolicy";
> 
>   private static final String PROP_POLICY = "policy";
> ```

What policy is this?

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/InterfaceMatchers.java, line 94 at r1](https://reviewable.io/reviews/batfish/batfish/1670#-LFE3suYBIn4brwZP83B:-LFE3suYBIn4brwZP83C:b-3qxkm0) ([raw file](https://github.com/batfish/batfish/blob/c4537b8c7e8281966be799aa5ea6da46f828fb68/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/InterfaceMatchers.java#L94)):*
> ```Java
>    * crypto map.
>    */
>   public static HasCryptoMap hasCryptoMap(@Nonnull Matcher<? super String> subMatcher) {
> ```

Put `@Nonnull` between `static and `HasCryptoMap`. May apply elsewhere in this PR as well.

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/IpAccessListMatchers.java, line 3 at r1](https://reviewable.io/reviews/batfish/batfish/1670#-LFE46ySBomg6li2nPpN:-LFE46ySBomg6li2nPpO:brvvi6v) ([raw file](https://github.com/batfish/batfish/blob/c4537b8c7e8281966be799aa5ea6da46f828fb68/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/IpAccessListMatchers.java#L3)):*
> ```Java
> package org.batfish.datamodel.matchers;
> 
> import static org.hamcrest.CoreMatchers.equalTo;
> ```

Please prefer `org.hamcrest.Matchers` to `org.hamcrest.CoreMatchers` for consistency. We will eventually blacklist the latter.

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/IpsecPolicyMatchers.java, line 37 at r1](https://reviewable.io/reviews/batfish/batfish/1670#-LFE4QyxEAWSJw6qB-WE:-LFE4QyxEAWSJw6qB-WF:b5m3blf) ([raw file](https://github.com/batfish/batfish/blob/c4537b8c7e8281966be799aa5ea6da46f828fb68/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/IpsecPolicyMatchers.java#L37)):*
> ```Java
>   /**
>    * Provides a matcher that matches if the provided {@code pfsKeyGroup} matches the Ipsec policy's
>    * PfsKeyGroupy
> ```

typo: `PfsKeyGroupy`

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_crypto.g4, line 100 at r1](https://reviewable.io/reviews/batfish/batfish/1670#-LFE4eYl9wMeOkFybuEP:-LFE4eYl9wMeOkFybuEQ:b-xvvs5g) ([raw file](https://github.com/batfish/batfish/blob/c4537b8c7e8281966be799aa5ea6da46f828fb68/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_crypto.g4#L100)):*
> ```ANTLR
> :
>    SET
>       (
> ```

indentation, extraneous newline.

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_crypto.g4, line 714 at r1](https://reviewable.io/reviews/batfish/batfish/1670#-LFE4zQK3TOaYzjte57k:-LFE4zQK3TOaYzjte57l:b-y5um1a) ([raw file](https://github.com/batfish/batfish/blob/c4537b8c7e8281966be799aa5ea6da46f828fb68/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_crypto.g4#L714)):*
> ```ANTLR
> ;
> 
> crypto_map_seq_num
> ```

This doesn't really sound like a sequence number. Rather, it sounds like a full line that starts with a sequence number. Please refactor with appropriate name(s).

---

*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 1823 at r1](https://reviewable.io/reviews/batfish/batfish/1670#-LFE5aGiDE05PA0_n9xw:-LFE5aGiDE05PA0_n9xx:b-iow0lg) ([raw file](https://github.com/batfish/batfish/blob/c4537b8c7e8281966be799aa5ea6da46f828fb68/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L1823)):*
> ```Java
>     // crypto map entry should be created only if seq number is present ahead
>     if (ctx.crypto_map_seq_num() != null
>         && ctx.crypto_map_seq_num().crypto_map_sn_ipsec_isakmp() != null) {
> ```

Why not just create the entry in the enter rule for `crypto_map_sn_ipsec_isakmp` instead of here?
This seems like too early a place to be creating the full structure of the crypto map. May apply elsewhere.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 2129 at r1](https://reviewable.io/reviews/batfish/batfish/1670#-LFE6Fft-kw923CdgQDB:-LFE6Fft-kw923CdgQDC:b9r6ss5) ([raw file](https://github.com/batfish/batfish/blob/c4537b8c7e8281966be799aa5ea6da46f828fb68/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L2129)):*
> ```Java
>           _w.redFlag(
>               String.format(
>                   "Dynamic Crypto map set '%s' referred by crypto map '%s' does not exist",
> ```

Our regular reference tracking should emit a message like this without the need for a message here. You should just do nothing in this case. Applies elsewhere as well.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 2180 at r1](https://reviewable.io/reviews/batfish/batfish/1670#-LFE6WoT-S4nVtsZHsUf:-LFE6WoT-S4nVtsZHsUg:b-dcy0sr) ([raw file](https://github.com/batfish/batfish/blob/c4537b8c7e8281966be799aa5ea6da46f828fb68/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L2180)):*
> ```Java
>             .values()
>             .stream()
>             .filter(iface -> Objects.equals(iface.getCryptoMap(), ipsecVpnName.split(":")[0]))
> ```

This is pretty arcane, and looks brittle. What is happening here? I suspect you are encoding structural information in the name of the `IpsecVpn`, rather than as a separate field inside it.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 2215 at r1](https://reviewable.io/reviews/batfish/batfish/1670#-LFE72IhBIFjzb6Oz2gb:-LFE72Ii3st0WjXmP0K7:b-lj1o35) ([raw file](https://github.com/batfish/batfish/blob/c4537b8c7e8281966be799aa5ea6da46f828fb68/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L2215)):*
> ```Java
>                 .filter(
>                     ikeGateway1 ->
>                         ikeGateway1.getLocalIp() == bindingInterfaceIp
> ```

use `.equals` for `Ip` instead of `==`. This applies in multiple places.

---

*[projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java, line 1640 at r1](https://reviewable.io/reviews/batfish/batfish/1670#-LFE7fxZ06hAqV1wOq_l:-LFE7fxZ06hAqV1wOq_m:b6ergs) ([raw file](https://github.com/batfish/batfish/blob/c4537b8c7e8281966be799aa5ea6da46f828fb68/projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java#L1640)):*
> ```Java
>         c,
>         allOf(
>             hasIpsecPolicy(
> ```

Why not just break this into 2 assertions for legibility? Applies elsewhere as well.

---

*[test_rigs/unit-tests/configs/cisco_crypto, line 209 at r1](https://reviewable.io/reviews/batfish/batfish/1670#-LFE7xtwC6jibvQCiOEA:-LFE7xtwC6jibvQCiOEB:bdayshz) ([raw file](https://github.com/batfish/batfish/blob/c4537b8c7e8281966be799aa5ea6da46f828fb68/test_rigs/unit-tests/configs/cisco_crypto#L209)):*
> ```
> crypto map myothermap redundancy replay-interval inbound 1000 outbound 1000
> crypto map myothermap interface outside
> crypto map VPN 5 ipsec-isakmp
> ```

Why was this removed? Is this not valid syntax? Should it go in another file?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1670)*

**Comment by haverma** [comment]
Review status: 16 of 32 files reviewed, 10 unresolved discussions (waiting on @arifogel, @haverma, and @dhalperi)

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpsecVpn.java, line 20 at r1](https://reviewable.io/reviews/batfish/batfish/1670#-LFE3fObEBkqfnw9oh45:-LFKoJOW78fytoy5955K:b-xwlhvr) ([raw file](https://github.com/batfish/batfish/blob/c4537b8c7e8281966be799aa5ea6da46f828fb68/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpsecVpn.java#L20)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

What policy is this?
</blockquote></details>

This is the policy which decides when a packet will be selected by this VPN for tunneling. This is represented by an ACL/security policy in `crypto-map`/Juniper policy based VPNs respectively. 

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/ConfigurationMatchers.java, line 143 at r2](https://reviewable.io/reviews/batfish/batfish/1670#-LFKso5kCaOlO-n_Z1Lu:-LFKso5kCaOlO-n_Z1Lv:bnz8n9p) ([raw file](https://github.com/batfish/batfish/blob/a53ba27487070d27809440e49ef3a2555c7c5575/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/ConfigurationMatchers.java#L143)):*
> ```Java
>    * Ipsec vpn with specified name.
>    */
>   public static @Nonnull HasIpsecVpn hasIpsecVpn(
> ```

Added `@NonNull` in most of Ipsec matchers, but still most of the matchers in Batfish don't have this annotation

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/IpAccessListMatchers.java, line 3 at r1](https://reviewable.io/reviews/batfish/batfish/1670#-LFE46ySBomg6li2nPpN:-LFKt0qP9dt_Rfw7caFY:bsww1xb) ([raw file](https://github.com/batfish/batfish/blob/c4537b8c7e8281966be799aa5ea6da46f828fb68/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/IpAccessListMatchers.java#L3)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Please prefer `org.hamcrest.Matchers` to `org.hamcrest.CoreMatchers` for consistency. We will eventually blacklist the latter.
</blockquote></details>

repalced

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/IpsecPolicyMatchers.java, line 37 at r1](https://reviewable.io/reviews/batfish/batfish/1670#-LFE4QyxEAWSJw6qB-WE:-LFKt2QL-noOAfKxqmdO:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/c4537b8c7e8281966be799aa5ea6da46f828fb68/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/IpsecPolicyMatchers.java#L37)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

typo: `PfsKeyGroupy`
</blockquote></details>

done

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_crypto.g4, line 100 at r1](https://reviewable.io/reviews/batfish/batfish/1670#-LFE4eYl9wMeOkFybuEP:-LFKt4Q32CFK8NjLv0PL:b-9y4xea) ([raw file](https://github.com/batfish/batfish/blob/c4537b8c7e8281966be799aa5ea6da46f828fb68/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_crypto.g4#L100)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

indentation, extraneous newline.
</blockquote></details>

formatted correctly

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_crypto.g4, line 714 at r1](https://reviewable.io/reviews/batfish/batfish/1670#-LFE4zQK3TOaYzjte57k:-LFKt6o9-8mvSE1gdgR_:b3wfa50) ([raw file](https://github.com/batfish/batfish/blob/c4537b8c7e8281966be799aa5ea6da46f828fb68/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_crypto.g4#L714)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

This doesn't really sound like a sequence number. Rather, it sounds like a full line that starts with a sequence number. Please refactor with appropriate name(s).
</blockquote></details>

renamed to `num`

---

*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 1823 at r1](https://reviewable.io/reviews/batfish/batfish/1670#-LFE5aGiDE05PA0_n9xw:-LFKtC9xCzq57HBS9558:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/c4537b8c7e8281966be799aa5ea6da46f828fb68/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L1823)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Why not just create the entry in the enter rule for `crypto_map_sn_ipsec_isakmp` instead of here?
This seems like too early a place to be creating the full structure of the crypto map. May apply elsewhere.
</blockquote></details>

done

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 2129 at r1](https://reviewable.io/reviews/batfish/batfish/1670#-LFE6Fft-kw923CdgQDB:-LFKxzI_5y5r1HSf2BxY:b-v92kzt) ([raw file](https://github.com/batfish/batfish/blob/c4537b8c7e8281966be799aa5ea6da46f828fb68/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L2129)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Our regular reference tracking should emit a message like this without the need for a message here. You should just do nothing in this case. Applies elsewhere as well.
</blockquote></details>

removed warning

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 2180 at r1](https://reviewable.io/reviews/batfish/batfish/1670#-LFE6WoT-S4nVtsZHsUf:-LFKtNyjBb2A8ECzYcku:bh3g2bx) ([raw file](https://github.com/batfish/batfish/blob/c4537b8c7e8281966be799aa5ea6da46f828fb68/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L2180)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

This is pretty arcane, and looks brittle. What is happening here? I suspect you are encoding structural information in the name of the `IpsecVpn`, rather than as a separate field inside it.
</blockquote></details>

There is not much structural information here, I chose this approach as an interface can refer to a crypto-map set and there can be multiple crypto-map entries in a crypto-map set. Each crypto-map entry can be converted to an IpsecVPN class, so to ensure that all of the Ipsec VPNs generated from them have a unique key(name), I am naming them as `Crypto-map-name:parent-crypto-map-seq-no:referred-crypto-map-seq-num`. This will ensure that while considering an interface we go through the Ipsec VPNs in order of sequence numbers(lexical ordering will be the same). Ipsec VPNs are already stored in a `TreeMap` so the traversal of the keys will be in this order only.  Juniper does not follow any concept of priority/seq numbering for policy based VPNs so I thought of not introducing a field for it in the data-model.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 2215 at r1](https://reviewable.io/reviews/batfish/batfish/1670#-LFE72IhBIFjzb6Oz2gb:-LFKvm4w0i8wp39F8ZLk:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/c4537b8c7e8281966be799aa5ea6da46f828fb68/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L2215)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

use `.equals` for `Ip` instead of `==`. This applies in multiple places.
</blockquote></details>

done

---

*[projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java, line 1640 at r1](https://reviewable.io/reviews/batfish/batfish/1670#-LFE7fxZ06hAqV1wOq_l:-LFKvowh44Vazb_ETywZ:b-dzwxbw) ([raw file](https://github.com/batfish/batfish/blob/c4537b8c7e8281966be799aa5ea6da46f828fb68/projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java#L1640)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Why not just break this into 2 assertions for legibility? Applies elsewhere as well.
</blockquote></details>

refactored into multiple assertions and multiple test cases for legibility

---

*[test_rigs/unit-tests/configs/cisco_crypto, line 209 at r1](https://reviewable.io/reviews/batfish/batfish/1670#-LFE7xtwC6jibvQCiOEA:-LFKw3Qq-nqhspltmjR9:b-kg576q) ([raw file](https://github.com/batfish/batfish/blob/c4537b8c7e8281966be799aa5ea6da46f828fb68/test_rigs/unit-tests/configs/cisco_crypto#L209)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Why was this removed? Is this not valid syntax? Should it go in another file?
</blockquote></details>

I wrongly concluded that these were invalid configs, but these are actually valid Cisco ASA crypto map configs. Adding them back under the name `asadynamicmap` and `asacryptomap`, but right now we are only parsing `IOS` style crypto-maps

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/InterfaceMatchers.java, line 94 at r1](https://reviewable.io/reviews/batfish/batfish/1670#-LFE3suYBIn4brwZP83B:-LFKxoJv7IDUDvVIZ67Y:b-emrhah) ([raw file](https://github.com/batfish/batfish/blob/c4537b8c7e8281966be799aa5ea6da46f828fb68/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/InterfaceMatchers.java#L94)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Put `@Nonnull` between `static and `HasCryptoMap`. May apply elsewhere in this PR as well.
</blockquote></details>

this was unused, but added `@NonNull` elsewhere

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1670)*

**Comment by arifogel** [comment]
Reviewed 17 of 18 files at r2.
Review status: all files reviewed, 5 unresolved discussions (waiting on @arifogel and @haverma)

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpsecVpn.java, line 20 at r1](https://reviewable.io/reviews/batfish/batfish/1670#-LFE3fObEBkqfnw9oh45:-LFOCGAR5Jbn0_Me7PBR:b-b9d358) ([raw file](https://github.com/batfish/batfish/blob/c4537b8c7e8281966be799aa5ea6da46f828fb68/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpsecVpn.java#L20)):*
<details><summary><i>Previously, haverma (Harsh Verma) wrote…</i></summary><blockquote>

This is the policy which decides when a packet will be selected by this VPN for tunneling. This is represented by an ACL/security policy in `crypto-map`/Juniper policy based VPNs respectively. 
</blockquote></details>

Can you please rename this to reflect that description?

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/ConfigurationMatchers.java, line 143 at r2](https://reviewable.io/reviews/batfish/batfish/1670#-LFKso5kCaOlO-n_Z1Lu:-LFOCQ_H67G9sFZ5uBUz:b-d1glbm) ([raw file](https://github.com/batfish/batfish/blob/a53ba27487070d27809440e49ef3a2555c7c5575/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/ConfigurationMatchers.java#L143)):*
<details><summary><i>Previously, haverma (Harsh Verma) wrote…</i></summary><blockquote>

Added `@NonNull` in most of Ipsec matchers, but still most of the matchers in Batfish don't have this annotation
</blockquote></details>

New PRs should use good style.

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_crypto.g4, line 714 at r1](https://reviewable.io/reviews/batfish/batfish/1670#-LFE4zQK3TOaYzjte57k:-LFODxDo-jWNuu5tXRf3:bf6volm) ([raw file](https://github.com/batfish/batfish/blob/c4537b8c7e8281966be799aa5ea6da46f828fb68/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_crypto.g4#L714)):*
<details><summary><i>Previously, haverma (Harsh Verma) wrote…</i></summary><blockquote>

renamed to `num`
</blockquote></details>

Please make changes discussed offline.

---

*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 1870 at r2](https://reviewable.io/reviews/batfish/batfish/1670#-LFOEZP8AGkVjnnLXPUg:-LFOEZP8AGkVjnnLXPUh:bxya3ox) ([raw file](https://github.com/batfish/batfish/blob/a53ba27487070d27809440e49ef3a2555c7c5575/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L1870)):*
> ```Java
>       defineStructure(CRYPTO_MAP_SET, _currentCryptoMapName, ctx);
>     } else if (cryptoMapSet.getDynamic()) {
>       _w.redFlag(
> ```

Would it be possible to prevent this situation earlier via separation in the grammar rules?

---

*[test_rigs/unit-tests/configs/cisco_crypto, line 209 at r1](https://reviewable.io/reviews/batfish/batfish/1670#-LFE7xtwC6jibvQCiOEA:-LFOHqSk9rYMY4byoknG:blk70kc) ([raw file](https://github.com/batfish/batfish/blob/c4537b8c7e8281966be799aa5ea6da46f828fb68/test_rigs/unit-tests/configs/cisco_crypto#L209)):*
<details><summary><i>Previously, haverma (Harsh Verma) wrote…</i></summary><blockquote>

I wrongly concluded that these were invalid configs, but these are actually valid Cisco ASA crypto map configs. Adding them back under the name `asadynamicmap` and `asacryptomap`, but right now we are only parsing `IOS` style crypto-maps
</blockquote></details>

Ah OK. Please just put those in a separate file called `asa_crypto`. If the reset of this is strictly IOS, we should probably rename the remainder of the is file to `ios_crypto`. If you're not sure, leave it. I'm trying to move away from having `cisco_xxx` files, since you can get weird behavior due to only a single format being detected.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1670)*

**Comment by arifogel** [comment]
Review status: all files reviewed, 6 unresolved discussions (waiting on @haverma)

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1670#-LFOLZRz5GFbYsvyFXBi:-LFOLZRz5GFbYsvyFXBj:b-ftngm6) (no related file):*
On nomenclature for what you currently call `CrytpoMap` and `CryptoMapSet`
Please rename to whatever names are used in Cisco documentation for those structures.
If the names already match, disregard.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1670)*

**Comment by arifogel** [comment]
Reviewed 12 of 12 files at r3.
Review status: all files reviewed, 1 unresolved discussion (waiting on @arifogel)

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpsecVpn.java, line 20 at r1](https://reviewable.io/reviews/batfish/batfish/1670#-LFE3fObEBkqfnw9oh45:-LFZifid-MlPrFD7V9GZ:bqn6t6e) ([raw file](https://github.com/batfish/batfish/blob/c4537b8c7e8281966be799aa5ea6da46f828fb68/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpsecVpn.java#L20)):*
<details><summary><i>Previously, haverma (Harsh Verma) wrote…</i></summary><blockquote>

made name more descriptive
</blockquote></details>

Please rename getter as well.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1670)*

**Comment by haverma** [comment]
Review status: 29 of 32 files reviewed, 1 unresolved discussion (waiting on @arifogel and @haverma)

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpsecVpn.java, line 20 at r1](https://reviewable.io/reviews/batfish/batfish/1670#-LFE3fObEBkqfnw9oh45:-LFZkLnW9KBeVjYwAgRw:brqjpwh) ([raw file](https://github.com/batfish/batfish/blob/c4537b8c7e8281966be799aa5ea6da46f828fb68/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpsecVpn.java#L20)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Please rename getter as well.
</blockquote></details>

thanks for catching that, done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1670)*

**Comment by arifogel** [comment]
Reviewed 3 of 3 files at r4.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1670)*

**Comment by arifogel** [comment]
:lgtm: if you are satisfied these are the right abstractions for now.

---

Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1670#-:-LFZkXaS90Ou0wz8Cu4f:bkq7yc7)*

**Pull request merged**
