### PR TITLE
allowing ip access-group in manangement ssh

### PR DESCRIPTION
**Pull request by ratulm**

### CODE REVIEW

**Comment by dhalperi** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[test_rigs/unit-tests/configs/arista_misc, line 27 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1180#-LAHBbLr0yhvN504oQW9:-LAHBbLsDbvw6Qc5CK5Q:b-voat83) ([raw file](https://github.com/batfish/batfish/blob/3f42ff84a98dcc851e80ada6505e2d3350c34a0a/test_rigs/unit-tests/configs/arista_misc#L27)):*
> ```
> management ssh
>  authentication mode password
>  ip access-group abc in
> ```

actually define it, too, so we can confirm it doesn't show as unused.

(may need a `mark` command, as in https://github.com/batfish/batfish/pull/1178/files#diff-936a6b90d388a23a096b1ed30ea8fd10R3818)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1180#-:-LAHBlfc0XC7emhP_7IS:bnfp4nl)*

**Comment by dhalperi** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1180)*

**Comment by dhalperi** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1180)*

**Comment by ratulm** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test_rigs/parsing-tests/unit-tests-unused.ref, line 850 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1180#-LAHD4Yzfs0mIitChyTD-r2-850:-LAHK_U_89keQAZAgy7P:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/b88534cb2f41019fa464bac1bf2778b6f4e80ddd/test_rigs/parsing-tests/unit-tests-unused.ref#L850)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

this is wrong -- you do need the mark statement I guess.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1180)*

**Pull request merged**
