### PR TITLE
PAN: loopback routes are local

### PR DESCRIPTION
**Pull request by dhalperi**
Requires changes to ConnectedRouteMetadata as well.

### CODE REVIEW

**Review by corinaminer — COMMENTED** [review]
> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6677)* status: all files reviewed, 2 unresolved discussions (waiting on @dhalperi and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java, line 2003 at r1](https://reviewable.io/reviews/batfish/batfish/6677#-MUq5axIBzHljNwQNsHS:-MUq5axIBzHljNwQNsHT:b6zeaew) ([raw file](https://github.com/batfish/batfish/blob/0f1bf12bbd9433e1d010dbd63831e17bc76d2a59/projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java#L2003)):*
> ```Java
> 
>       if (iface.getType() == Interface.Type.LOOPBACK) {
>         // On PAN, loopback addresses are not connected routes, they are only local routes.
> ```

Are there no /32s on non-loopback interfaces? or are /32s on loopback interfaces the only ones that count as "loopback addresses"?

more fundamentally: do we need to make customized `ConnectedRouteMetadata` for /32s on non-loopback interfaces?
___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java, line 2005 at r1](https://reviewable.io/reviews/batfish/batfish/6677#-MUq2tm5DCgEhSfxNV9s:-MUq2tm5DCgEhSfxNV9t:b-6mb5hj) ([raw file](https://github.com/batfish/batfish/blob/0f1bf12bbd9433e1d010dbd63831e17bc76d2a59/projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java#L2005)):*
> We have already filtered down to valid addresses, all of which are /32

We didn't actually confirm they're all /32. Should the `allValidAddresses` stream above have another filter to limit loopback interface addresses to /32s? or is there something earlier in the pipeline that would block any other addresses from being attributed to a loopback iface?
___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java, line 2010 at r1](https://reviewable.io/reviews/batfish/batfish/6677#-MUq3Jfa6zKFBujv6DbO:-MUq3Jfa6zKFBujv6DbP:b-pdrjxm) ([raw file](https://github.com/batfish/batfish/blob/0f1bf12bbd9433e1d010dbd63831e17bc76d2a59/projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java#L2010)):*
> ```Java
>                 .collect(
>                     ImmutableMap.toImmutableMap(
>                         a -> a,
> ```

nit: could replace with `Function.identity()`
___
*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ConnectedRouteMetadataTest.java, line 25 at r1](https://reviewable.io/reviews/batfish/batfish/6677#-MUq4zpy3KCX9juNLznw:-MUq4zpy3KCX9juNLznx:bd5ty59) ([raw file](https://github.com/batfish/batfish/blob/62d7db0f28ec6aaef81dfeefd1e76da1048dac9e/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ConnectedRouteMetadataTest.java#L25)):*
> ```Java
>         .addEqualityGroup(builder.setTag(1).build())
>         .addEqualityGroup(builder.setGenerateLocalRoutes(true).build())
>         .addEqualityGroup(builder.setAdmin(1).setGenerateLocalRoutes(true))
> ```

:eyes:

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6677)* status: all files reviewed, 2 unresolved discussions (waiting on @corinaminer, @dhalperi, and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java, line 2005 at r1](https://reviewable.io/reviews/batfish/batfish/6677#-MUq2tm5DCgEhSfxNV9s:-MUqQMlo4-FF2eTiD5pP:b-1pk9f9) ([raw file](https://github.com/batfish/batfish/blob/0f1bf12bbd9433e1d010dbd63831e17bc76d2a59/projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java#L2005)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

> We have already filtered down to valid addresses, all of which are /32

We didn't actually confirm they're all /32. Should the `allValidAddresses` stream above have another filter to limit loopback interface addresses to /32s? or is there something earlier in the pipeline that would block any other addresses from being attributed to a loopback iface?
</blockquote></details>

I don't think you understood the code? Can you take another look and suggest clarifications?

The filtering only applies to loopback interfaces, and only lets /32 through in that case only.

We did confirm they're all /32, and we only want to handle loopback interfaces, and we don't need connected route metadata for other interfaces.
___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java, line 2010 at r1](https://reviewable.io/reviews/batfish/batfish/6677#-MUq3Jfa6zKFBujv6DbO:-MUqQe7zDKX7uj6D2YpS:b-f1jpd4) ([raw file](https://github.com/batfish/batfish/blob/0f1bf12bbd9433e1d010dbd63831e17bc76d2a59/projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java#L2010)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

nit: could replace with `Function.identity()`
</blockquote></details>

Following the Java style recommendations here: this is shorter than function identity

**Comment by dhalperi** [comment]
___
*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ConnectedRouteMetadataTest.java, line 25 at r1](https://reviewable.io/reviews/batfish/batfish/6677#-MUq4zpy3KCX9juNLznw:-MUqRxnF4m_Qo4fC0_VT:b-hddhjk) ([raw file](https://github.com/batfish/batfish/blob/62d7db0f28ec6aaef81dfeefd1e76da1048dac9e/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ConnectedRouteMetadataTest.java#L25)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

:eyes: 
</blockquote></details>

Not sure what this means. But the old tests were confusing and complicated; since the builder keeps state we just need to change each property once and we've covered all the bases: for each property we have a pair that only differ in that.

Additionally I went ahead and made sure that null and false are different, mainly because of paranoia

**Review by corinaminer — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6677#-:-MUqTi0p0MEuVCz2jGku:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java, line 2003 at r1](https://reviewable.io/reviews/batfish/batfish/6677#-MUq5axIBzHljNwQNsHS:-MUqTJYSCvmhW4tJ6TsK:b-dpxzl8) ([raw file](https://github.com/batfish/batfish/blob/0f1bf12bbd9433e1d010dbd63831e17bc76d2a59/projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java#L2003)):*
on your other comment you said:
> we don't need connected route metadata for other interfaces

so i assume this question has been considered. Still not personally clear on whether other interfaces have /32s, but nonblocking
___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java, line 2005 at r1](https://reviewable.io/reviews/batfish/batfish/6677#-MUq2tm5DCgEhSfxNV9s:-MUqSorE0zbPfz_39voD:betwo8n) ([raw file](https://github.com/batfish/batfish/blob/0f1bf12bbd9433e1d010dbd63831e17bc76d2a59/projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java#L2005)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I don't think you understood the code? Can you take another look and suggest clarifications?

The filtering only applies to loopback interfaces, and only lets /32 through in that case only.

We did confirm they're all /32, and we only want to handle loopback interfaces, and we don't need connected route metadata for other interfaces.
</blockquote></details>

Oh, yeah, never mind. Misread the filtering.
___
*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ConnectedRouteMetadataTest.java, line 25 at r1](https://reviewable.io/reviews/batfish/batfish/6677#-MUq4zpy3KCX9juNLznw:-MUqTanm19rcWtKEGxlv:b-ts3kby) ([raw file](https://github.com/batfish/batfish/blob/62d7db0f28ec6aaef81dfeefd1e76da1048dac9e/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ConnectedRouteMetadataTest.java#L25)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Not sure what this means. But the old tests were confusing and complicated; since the builder keeps state we just need to change each property once and we've covered all the bases: for each property we have a pair that only differ in that.

Additionally I went ahead and made sure that null and false are different, mainly because of paranoia
</blockquote></details>

yeah i was just confused by the old version of the test

**Comment by dhalperi** [comment]
___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java, line 2005 at r1](https://reviewable.io/reviews/batfish/batfish/6677#-MUq2tm5DCgEhSfxNV9s:-MUq_Qdd5Q0SnBQrq-9N:b-asfft6) ([raw file](https://github.com/batfish/batfish/blob/0f1bf12bbd9433e1d010dbd63831e17bc76d2a59/projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java#L2005)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Oh, yeah, never mind. Misread the filtering.
</blockquote></details>

Thanks. If this code can be cleaner I'm happy to do it! This is complicated.

Appreciate the detailed review.

**Pull request merged**
