### PR TITLE
Basic Palo Alto Networks parsing support

### PR DESCRIPTION
**Pull request by sfraint**
Set up skeleton for Palo Alto Networks parsing support

### CODE REVIEW

**Comment by dhalperi** [comment]
Suspect Ari will be the right first reviewer.

Please do a thorough job, as I bet we would use this PR as a prototype for all new parsers.

**Comment by arifogel** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4, line 28 at r1](https://reviewable.io/reviews/batfish/batfish/1592#-LELVPqE80VdpXQAOxQ6:-LELVPqE80VdpXQAOxQ7:b-g1kqjy) ([raw file](https://github.com/batfish/batfish/blob/3fed8c627b5bddd5e79f6cdccfb55fed55433f08/projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4#L28)):*
> ```ANTLR
> ;
> ```

extra whitespace

---

*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java, line 14 at r1](https://reviewable.io/reviews/batfish/batfish/1592#-LELW0Fn3wLN1pnLh3NW:-LELW0Fn3wLN1pnLh3NX:b-hecex6) ([raw file](https://github.com/batfish/batfish/blob/3fed8c627b5bddd5e79f6cdccfb55fed55433f08/projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java#L14)):*
> ```Java
>   private static final long serialVersionUID = 1L;
> 
>   Configuration _c;
> ```

Why package visibility?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1592)*

**Comment by sfraint** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4, line 28 at r1](https://reviewable.io/reviews/batfish/batfish/1592#-LELVPqE80VdpXQAOxQ6:-LEL_3X2DnO0ZqZYcZDY:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/3fed8c627b5bddd5e79f6cdccfb55fed55433f08/projects/batfish/src/main/antlr4/org/batfish/grammar/palo_alto/PaloAltoLexer.g4#L28)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

extra whitespace
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java, line 14 at r1](https://reviewable.io/reviews/batfish/batfish/1592#-LELW0Fn3wLN1pnLh3NW:-LEL_4kn0FGEuCPjdIDm:b8hy52t) ([raw file](https://github.com/batfish/batfish/blob/3fed8c627b5bddd5e79f6cdccfb55fed55433f08/projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java#L14)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Why package visibility?
</blockquote></details>

Not needed, fixed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1592)*

**Comment by arifogel** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1592#-:-LELacmc7yFuX2Dibf3v:bnfp4nl)*

**Pull request merged**
