### PR TITLE
A10: extract trunk ports-threshold

### PR DESCRIPTION
**Pull request by sfraint**

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7459)* status: all files reviewed, 2 unresolved discussions (waiting on @corinaminer and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java, line 486 at r1](https://reviewable.io/reviews/batfish/batfish/7459#-MknpFYqD8UiDC3l_QlT:-MknovG29Khh97IYQboK:bdxiujk) ([raw file](https://github.com/batfish/batfish/blob/982a30ed6e00f86fc9ef7ece460c42f6d0c92593/projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java#L486)):*
> ```Java
>                       A10StructureType.INTERFACE,
>                       trunkName,
>                       A10StructureUsage.INTERFACE_SELF_REF,
> ```

Should we use a separate ref for things like this, maybe `LACP_TRUNK_SELF_REF`? "No" is a fine answer.
___
*[projects/batfish/src/test/java/org/batfish/vendor/a10/grammar/A10GrammarTest.java, line 604 at r1](https://reviewable.io/reviews/batfish/batfish/7459#-Mknpyrb5SIwVHyyzafE:-Mknpyrb5SIwVHyyzafF:bbpj1ow) ([raw file](https://github.com/batfish/batfish/blob/982a30ed6e00f86fc9ef7ece460c42f6d0c92593/projects/batfish/src/test/java/org/batfish/vendor/a10/grammar/A10GrammarTest.java#L604)):*
> ```Java
>     // Settings for the LACP trunk
>     assertThat(trunkIface1.getTrunkTypeEffective(), equalTo(TrunkGroup.Type.LACP));
>     assertThat(trunkIface1.getPortsThreshold(), equalTo(2));
> ```

No VI datamodel for this currently?

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7459)* status: all files reviewed, 2 unresolved discussions (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java, line 486 at r1](https://reviewable.io/reviews/batfish/batfish/7459#-MknpFYqD8UiDC3l_QlT:-Mknuv3U8gW6jKYAHIVg:b7hfoco) ([raw file](https://github.com/batfish/batfish/blob/982a30ed6e00f86fc9ef7ece460c42f6d0c92593/projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java#L486)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Should we use a separate ref for things like this, maybe `LACP_TRUNK_SELF_REF`? "No" is a fine answer.
</blockquote></details>

I'm torn...

how should these similar self-refs be treated?
`LACP` type trunk:
```
lacp-trunk 1
   <config>
```

trunk, but not `LACP` type:
```
trunk 1
   <config>
```

maybe `LACP` type, maybe not:
```
interface trunk 1
   <config>
```

should each of these have a different self ref type?
___
*[projects/batfish/src/test/java/org/batfish/vendor/a10/grammar/A10GrammarTest.java, line 604 at r1](https://reviewable.io/reviews/batfish/batfish/7459#-Mknpyrb5SIwVHyyzafE:-MknuWRo5RLjYr9eRyvS:b-dvtvmo) ([raw file](https://github.com/batfish/batfish/blob/982a30ed6e00f86fc9ef7ece460c42f6d0c92593/projects/batfish/src/test/java/org/batfish/vendor/a10/grammar/A10GrammarTest.java#L604)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

No VI datamodel for this currently?
</blockquote></details>

afaik, that is correct

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7459)* status: all files reviewed, 1 unresolved discussion (waiting on @corinaminer and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java, line 486 at r1](https://reviewable.io/reviews/batfish/batfish/7459#-MknpFYqD8UiDC3l_QlT:-MknxLccEiocidIcxYcZ:b-4ilyw) ([raw file](https://github.com/batfish/batfish/blob/982a30ed6e00f86fc9ef7ece460c42f6d0c92593/projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java#L486)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

I'm torn...

how should these similar self-refs be treated?
`LACP` type trunk:
```
lacp-trunk 1
   <config>
```

trunk, but not `LACP` type:
```
trunk 1
   <config>
```

maybe `LACP` type, maybe not:
```
interface trunk 1
   <config>
```

should each of these have a different self ref type?
</blockquote></details>

1. `LACP_TRUNK_SELF_REF`
2. `TRUNK_SELF_REF`
3. `INTERFACE_TRUNK_SELF_REF` or just `INTERFACE_SELF_REF`

Or just leave it? I guess my real issue here is that it seems like on ACOS2 `LACP_TRUNK` and `TRUNK` really should be their own structure type. It's confusing to the user to say that they are `interface`s if you can't configure them there.

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7459)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java, line 486 at r1](https://reviewable.io/reviews/batfish/batfish/7459#-MknpFYqD8UiDC3l_QlT:-MknzDm105iM6SiFgmzV:b-u3woj8) ([raw file](https://github.com/batfish/batfish/blob/982a30ed6e00f86fc9ef7ece460c42f6d0c92593/projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java#L486)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

1. `LACP_TRUNK_SELF_REF`
2. `TRUNK_SELF_REF`
3. `INTERFACE_TRUNK_SELF_REF` or just `INTERFACE_SELF_REF`

Or just leave it? I guess my real issue here is that it seems like on ACOS2 `LACP_TRUNK` and `TRUNK` really should be their own structure type. It's confusing to the user to say that they are `interface`s if you can't configure them there.
</blockquote></details>

yeah, I somewhat agree...but it also feels somewhat wrong to have the same VS concept be different structure types in different OS versions

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7459)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java, line 486 at r1](https://reviewable.io/reviews/batfish/batfish/7459#-MknpFYqD8UiDC3l_QlT:-MknzbjaDBMS-vNyvaAA:by0k9ic) ([raw file](https://github.com/batfish/batfish/blob/982a30ed6e00f86fc9ef7ece460c42f6d0c92593/projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java#L486)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

yeah, I somewhat agree...but it also feels somewhat wrong to have the same VS concept be different structure types in different OS versions
</blockquote></details>

I'm going to leave it for now and we can change `v2` refs / structure types in a separate pass if we decide to go that route

**Pull request merged**
