### PR TITLE
Fixed NAT tests.

### PR DESCRIPTION
**Pull request by anothermattbrown**
- Generate rules to derive NAT Acl relations.
- Make Query a BasicStateExpr
- Transform the consequent of a TransformedBasicRuleStatement
- Move sane and header constraints to origination state rather
  than query state.

### CODE REVIEW

**Comment by arifogel** [comment]
*[projects/batfish/src/main/java/org/batfish/z3/NodProgram.java, line 91 at r1](https://reviewable.io:443/reviews/batfish/batfish/990#-L6Iagwy9QV1bOlMU90B:-L6IagwzEPOzjdsXQsV1:b-2rnvjg) ([raw file](https://github.com/batfish/batfish/blob/749bf35dca35546ca814c30c9f0fadedf8f057fe/projects/batfish/src/main/java/org/batfish/z3/NodProgram.java#L91)):*
> ```Java
> 
>     String[] variablesAsNames =
>         Streams.concat(
> ```

Can we just put a template arg here instead?
`Streams.<HeaderField>concat`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/990)*

**Comment by arifogel** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[projects/batfish/src/main/java/org/batfish/z3/MultipathInconsistencyQuerySynthesizer.java, line 44 at r1](https://reviewable.io:443/reviews/batfish/batfish/990#-L6IbMzPcWxwUzv1phd8:-L6IbMzPcWxwUzv1phd9:b8x1ldp) ([raw file](https://github.com/batfish/batfish/blob/749bf35dca35546ca814c30c9f0fadedf8f057fe/projects/batfish/src/main/java/org/batfish/z3/MultipathInconsistencyQuerySynthesizer.java#L44)):*
> ```Java
>                     new AndExpr(
>                         ImmutableList.of(
>                             SaneExpr.INSTANCE, new HeaderSpaceMatchExpr(_headerSpace))),
> ```

Move Sane and Header space match constraints to originate rule

---

*[projects/batfish/src/main/java/org/batfish/z3/ReachEdgeQuerySynthesizer.java, line 63 at r1](https://reviewable.io:443/reviews/batfish/batfish/990#-L6IbGh6DMdOTENNgk7h:-L6IbGh6DMdOTENNgk7i:b-isy9wa) ([raw file](https://github.com/batfish/batfish/blob/749bf35dca35546ca814c30c9f0fadedf8f057fe/projects/batfish/src/main/java/org/batfish/z3/ReachEdgeQuerySynthesizer.java#L63)):*
> ```Java
>         .setRules(
>             ImmutableList.of(
>                 new BasicRuleStatement(
> ```

Put header space match conditions here

---

*[projects/batfish/src/main/java/org/batfish/z3/SynthesizerInputImpl.java, line 312 at r1](https://reviewable.io:443/reviews/batfish/batfish/990#-L6IberglGM1NGT9q147:-L6IberglGM1NGT9q148:bl7puo) ([raw file](https://github.com/batfish/batfish/blob/749bf35dca35546ca814c30c9f0fadedf8f057fe/projects/batfish/src/main/java/org/batfish/z3/SynthesizerInputImpl.java#L312)):*
> ```Java
>                                 interfaceAcls.add(new Pair<>(aclOut.getName(), aclOut));
>                               }
>                               i.getSourceNats()
> ```

Needs test in `SynthesizerInputImplTest`. Should be an existing one to amend for whatever data structure with public getter gets produced here.

---

*[projects/batfish/src/main/java/org/batfish/z3/Z3ContextJob.java, line 170 at r1](https://reviewable.io:443/reviews/batfish/batfish/990#-L6IcpKHHUkcbOajTWcT:-L6IcpKHHUkcbOajTWcU:b-xz3pvx) ([raw file](https://github.com/batfish/batfish/blob/749bf35dca35546ca814c30c9f0fadedf8f057fe/projects/batfish/src/main/java/org/batfish/z3/Z3ContextJob.java#L170)):*
> ```Java
>           Lists.reverse(
>               Lists.newArrayList(program.getNodContext().getVariablesAsConsts().values()));
>       reversedVars.remove(0); // remove NEW_SRC_IP
> ```

This is getting ridiculous. Let's see if we can do something better with the two-argument constructor for bound variables or whatever is z3 (second argument is a name, for which we currently pass `null`).

---

*[tests/basic/commands, line 83 at r1](https://reviewable.io:443/reviews/batfish/batfish/990#-L6IgWMrUNXgkpR1701l:-L6IgWMsSoO51shvHt8d:b-pk2pue) ([raw file](https://github.com/batfish/batfish/blob/749bf35dca35546ca814c30c9f0fadedf8f057fe/tests/basic/commands#L83)):*
> ```
> test tests/basic/example-iptables-init.ref init-testrig test_rigs/example-iptables example-iptables
> test tests/basic/example-iptables-reachability.ref get reachability ingressNodeRegex="z1-.*", dstIps=["10.0.4.20","10.0.4.21"], srcIps=["10.0.3.0/24"], actions=["DROP"]
> test tests/basic/example-iptables-transit.ref get reachability notIngressNodeRegex="z1-.*", dstIps=["10.0.3.0/24"], notDstIps=["10.0.3.1"], srcIps=["10.0.4.0"], notTransitNodes=["z1-firewall"], actions=["ACCEPT"]
> ```

Undo change to this line and comment it out.
File a ticket to put visited nodes (that you care about) as header fields. That is, visiting such a node involves a transformation.

---

*[tests/basic/example-iptables-transit.ref, line 0 at r1](https://reviewable.io:443/reviews/batfish/batfish/990#-L6IgrhUj3M7BnZj-7NW:-L6IgrhUj3M7BnZj-7NX:bcq0qt5) ([raw file](https://github.com/batfish/batfish/blob/749bf35dca35546ca814c30c9f0fadedf8f057fe/tests/basic/example-iptables-transit.ref#L0)):*
Revert this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/990)*

**Comment by anothermattbrown** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[projects/batfish/src/main/java/org/batfish/z3/NodProgram.java, line 91 at r1](https://reviewable.io:443/reviews/batfish/batfish/990#-L6Iagwy9QV1bOlMU90B:-L6ImN3QphVfF-k2NRWO:b-o5zmvi) ([raw file](https://github.com/batfish/batfish/blob/749bf35dca35546ca814c30c9f0fadedf8f057fe/projects/batfish/src/main/java/org/batfish/z3/NodProgram.java#L91)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Can we just put a template arg here instead?
`Streams.<HeaderField>concat`
</blockquote></details>

Yep, seems to work.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/990)*

**Comment by arifogel** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[projects/batfish/src/main/java/org/batfish/z3/NodProgram.java, line 91 at r1](https://beta.reviewable.io/reviews/batfish/batfish/990#-L6Iagwy9QV1bOlMU90B:-L6IqBN37f8cR8FhEAN8:b-51i0b7) ([raw file](https://github.com/batfish/batfish/blob/749bf35dca35546ca814c30c9f0fadedf8f057fe/projects/batfish/src/main/java/org/batfish/z3/NodProgram.java#L91)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

Yep, seems to work.
</blockquote></details>

OK Please include that change in next update.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/990)*

**Comment by anothermattbrown** [comment]
Review status: 7 of 15 files reviewed at latest revision, 7 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/z3/NodProgram.java, line 91 at r1](https://reviewable.io:443/reviews/batfish/batfish/990#-L6Iagwy9QV1bOlMU90B:-L6J25d3wsg49Z6z04GA:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/749bf35dca35546ca814c30c9f0fadedf8f057fe/projects/batfish/src/main/java/org/batfish/z3/NodProgram.java#L91)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

OK Please include that change in next update.
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/z3/ReachEdgeQuerySynthesizer.java, line 63 at r1](https://reviewable.io:443/reviews/batfish/batfish/990#-L6IbGh6DMdOTENNgk7h:-L6J28rQ7GM-fFrEynAa:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/749bf35dca35546ca814c30c9f0fadedf8f057fe/projects/batfish/src/main/java/org/batfish/z3/ReachEdgeQuerySynthesizer.java#L63)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Put header space match conditions here
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/z3/SynthesizerInputImpl.java, line 312 at r1](https://reviewable.io:443/reviews/batfish/batfish/990#-L6IberglGM1NGT9q147:-L6J2ASPEVM7KjiNRa18:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/749bf35dca35546ca814c30c9f0fadedf8f057fe/projects/batfish/src/main/java/org/batfish/z3/SynthesizerInputImpl.java#L312)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Needs test in `SynthesizerInputImplTest`. Should be an existing one to amend for whatever data structure with public getter gets produced here.
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/z3/Z3ContextJob.java, line 170 at r1](https://reviewable.io:443/reviews/batfish/batfish/990#-L6IcpKHHUkcbOajTWcT:-L6J2BtTHPyactHTj1LM:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/749bf35dca35546ca814c30c9f0fadedf8f057fe/projects/batfish/src/main/java/org/batfish/z3/Z3ContextJob.java#L170)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

This is getting ridiculous. Let's see if we can do something better with the two-argument constructor for bound variables or whatever is z3 (second argument is a name, for which we currently pass `null`).
</blockquote></details>

Done.

---

*[tests/basic/commands, line 83 at r1](https://reviewable.io:443/reviews/batfish/batfish/990#-L6IgWMrUNXgkpR1701l:-L6J2DzXOKgLwLI-8neZ:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/749bf35dca35546ca814c30c9f0fadedf8f057fe/tests/basic/commands#L83)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Undo change to this line and comment it out.
File a ticket to put visited nodes (that you care about) as header fields. That is, visiting such a node involves a transformation.

</blockquote></details>

Done.

---

*[tests/basic/example-iptables-transit.ref, line  at r1](https://reviewable.io:443/reviews/batfish/batfish/990#-L6IgrhUj3M7BnZj-7NW:-L6J2FopvJ_syrWLCeQT:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/749bf35dca35546ca814c30c9f0fadedf8f057fe/tests/basic/example-iptables-transit.ref#L)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Revert this.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/990)*

**Comment by anothermattbrown** [comment]
Review status: 7 of 15 files reviewed at latest revision, 7 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/z3/MultipathInconsistencyQuerySynthesizer.java, line 44 at r1](https://reviewable.io:443/reviews/batfish/batfish/990#-L6IbMzPcWxwUzv1phd8:-L6J2IwnBNVrfp_J1ak0:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/749bf35dca35546ca814c30c9f0fadedf8f057fe/projects/batfish/src/main/java/org/batfish/z3/MultipathInconsistencyQuerySynthesizer.java#L44)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Move Sane and Header space match constraints to originate rule
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/990)*

**Comment by arifogel** [comment]
Reviewed 9 of 9 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/test/java/org/batfish/z3/NodJobTest.java, line 203 at r2](https://beta.reviewable.io/reviews/batfish/batfish/990#-L6JBkocDNUhA2W2EPNn:-L6JBkod1ZGO02GjsMdh:b-447djh) ([raw file](https://github.com/batfish/batfish/blob/4e081f8fce29edd4bbce89ca5a20dbfa499d1311/projects/batfish/src/test/java/org/batfish/z3/NodJobTest.java#L203)):*
> ```Java
>           FlowTraceHop hop = hops.get(0);
>           assertThat(hop.getTransformedFlow(), notNullValue());
>           assertThat(hop.getTransformedFlow().getSrcIp(), isOneOf(new Ip("1.0.0.10")));
> ```

`isOneOf`? You use it other places too. Feel free to ignore comments on this file until your changes have settled.

---

*[projects/batfish/src/test/java/org/batfish/z3/SynthesizerInputImplTest.java, line 552 at r2](https://beta.reviewable.io/reviews/batfish/batfish/990#-L6JAlML-oXK5NoypfuD:-L6JAlML-oXK5NoypfuE:bgfmgnw) ([raw file](https://github.com/batfish/batfish/blob/4e081f8fce29edd4bbce89ca5a20dbfa499d1311/projects/batfish/src/test/java/org/batfish/z3/SynthesizerInputImplTest.java#L552)):*
> ```Java
>     assertThat(
>         inputWithDataPlane,
>         hasAclConditions(
> ```

The test is fine.. However this isn't exactly the right place for it. Can you put this in `computeAclConditions`? Unfortunately it will require a little more setup, but that is the test I want to fail when this stuff isn't working properly, not `testComputeSourceNats`.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/990)*

**Comment by anothermattbrown** [comment]
Reviewed 1 of 9 files at r2.
Review status: 13 of 15 files reviewed at latest revision, 3 unresolved discussions.

---

*[projects/batfish/src/test/java/org/batfish/z3/NodJobTest.java, line 203 at r2](https://reviewable.io:443/reviews/batfish/batfish/990#-L6JBkocDNUhA2W2EPNn:-L6JCjDLs0botP278zns:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/4e081f8fce29edd4bbce89ca5a20dbfa499d1311/projects/batfish/src/test/java/org/batfish/z3/NodJobTest.java#L203)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

`isOneOf`? You use it other places too. Feel free to ignore comments on this file until your changes have settled.
</blockquote></details>

Done.

---

*[projects/batfish/src/test/java/org/batfish/z3/SynthesizerInputImplTest.java, line 552 at r2](https://reviewable.io:443/reviews/batfish/batfish/990#-L6JAlML-oXK5NoypfuD:-L6JGrpdxFDH98LYUEHW:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/4e081f8fce29edd4bbce89ca5a20dbfa499d1311/projects/batfish/src/test/java/org/batfish/z3/SynthesizerInputImplTest.java#L552)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

The test is fine.. However this isn't exactly the right place for it. Can you put this in `computeAclConditions`? Unfortunately it will require a little more setup, but that is the test I want to fail when this stuff isn't working properly, not `testComputeSourceNats`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/990)*

**Comment by anothermattbrown** [comment]
Review status: 13 of 15 files reviewed at latest revision, 3 unresolved discussions.

---

*[tests/basic/example-iptables-transit.ref, line  at r1](https://reviewable.io:443/reviews/batfish/batfish/990#-L6IgrhUj3M7BnZj-7NW:-L6JGunuIw6CfwhYO7M9:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/749bf35dca35546ca814c30c9f0fadedf8f057fe/tests/basic/example-iptables-transit.ref#L)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/990)*

**Comment by arifogel** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/990)*

**Comment by dhalperi** [comment]
*[tests/basic/commands, line 83 at r3](https://beta.reviewable.io/reviews/batfish/batfish/990#-L6JmZHD5W-UtqR8Vk9J:-L6JmZHD5W-UtqR8Vk9K:b-3rztkg) ([raw file](https://github.com/batfish/batfish/blob/b01ec85796790b121bf9deeb4766e11ed9414960/tests/basic/commands#L83)):*
> ```
> test tests/basic/example-iptables-init.ref init-testrig test_rigs/example-iptables
> test tests/basic/example-iptables-reachability.ref get reachability ingressNodeRegex="z1-.*", dstIps=["10.0.4.20","10.0.4.21"], srcIps=["10.0.3.0/24"], actions=["DROP"]
> # TODO fix notTransitNodes
> ```

link to the github issue?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/990)*

**Comment by anothermattbrown** [comment]
Review status: 14 of 15 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/basic/commands, line 83 at r3](https://reviewable.io:443/reviews/batfish/batfish/990#-L6JmZHD5W-UtqR8Vk9J:-L6NXgj3Z4ryAjTVvevC:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/b01ec85796790b121bf9deeb4766e11ed9414960/tests/basic/commands#L83)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

link to the github issue?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/990)*

**Comment by dhalperi** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/990)*

**Pull request merged**
