### PR TITLE
Refactor tests for ISP modeling utils

### PR DESCRIPTION
**Pull request by ratulm**
Mainly pulled out common setup/boilerplate to make it easier to add more variants of tests.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7441)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @arifogel and @ratulm)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7441#-MkcuQlS1KefTtB-aYCf:-MkcuQlS1KefTtB-aYCg:b-9pnyjl) (no related file):*
-reviewer:@dhalperi +reviewer:@arifogel 

This is precisely the type of refactoring for reuse that makes me nervous. Different tests having similar-but-slightly-different code is generally not a problem for me. I especially don't like shared mutable state (`_nf`).

Maybe Ari should take a look, as he's the big advocate of this type of change.

---

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7441)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @arifogel and @dhalperi)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7441#-MkcuQlS1KefTtB-aYCf:-Mkcw6100dveQ31uRpRa:b-3syikm) (no related file):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

-reviewer:@dhalperi +reviewer:@arifogel 

This is precisely the type of refactoring for reuse that makes me nervous. Different tests having similar-but-slightly-different code is generally not a problem for me. I especially don't like shared mutable state (`_nf`).

Maybe Ari should take a look, as he's the big advocate of this type of change.
</blockquote></details>

Interesting view. I went down this road because I wanted to add more tests that are similar, but can reuse the setup. This reduces the cost of writing tests and helps more easily understand the differences between variants.  

Agreed about shared mutable state. I'll pull _nf under setup to avoid that. 

---

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7441)* status: all files reviewed, 2 unresolved discussions (waiting on @dhalperi and @ratulm)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7441#-MkcuQlS1KefTtB-aYCf:-Mkd62Wi71Ywl69ODYbW:br2i1bn) (no related file):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

Interesting view. I went down this road because I wanted to add more tests that are similar, but can reuse the setup. This reduces the cost of writing tests and helps more easily understand the differences between variants.  

Agreed about shared mutable state. I'll pull _nf under setup to avoid that. 
</blockquote></details>

I am certainly not an advocate of of using static builders that are not reinitialized per test.  Indeed, `_nf` should be put under setup if it is to be used.

And in general we should be very conservative about re-using builders that modify multiple fields in the same test for different object builds.

---
___
*[projects/batfish-common-protocol/src/test/java/org/batfish/common/util/isp/IspModelingUtilsTest.java, line 129 at r2](https://reviewable.io/reviews/batfish/batfish/7441#-Mkd6f4kCLfAdsWUroYl:-Mkd6f4kCLfAdsWUroYm:bg03c1w) ([raw file](https://github.com/batfish/batfish/blob/5cc2d34125e632db1296993b58cbe5738732b58f/projects/batfish-common-protocol/src/test/java/org/batfish/common/util/isp/IspModelingUtilsTest.java#L129)):*
> ```Java
>   private static final String _snapshotInterfaceName = "interface";
> 
>   private static final NetworkFactory _nf = new NetworkFactory();
> ```

intiialize in `setup` as discussed, make it non-static for clarity.

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7441)* status: all files reviewed, 1 unresolved discussion (waiting on @ratulm)

___
*[projects/batfish-common-protocol/src/test/java/org/batfish/common/util/isp/IspModelingUtilsTest.java, line 149 at r3](https://reviewable.io/reviews/batfish/batfish/7441#-MkdGakRCfJgKNaDMYfG:-MkdGakRCfJgKNaDMYfH:b-ochunu) ([raw file](https://github.com/batfish/batfish/blob/b7c822947f4a4e4119ba67ce9e061072dfe71b97/projects/batfish-common-protocol/src/test/java/org/batfish/common/util/isp/IspModelingUtilsTest.java#L149)):*
> ```Java
> 
>   private Configuration createBgpNode(
>       NetworkFactory nf, String hostname, String bgpIfaceName, Ip bgpInterfaceIp) {
> ```

Do you ever use any argument other than `_nf`? Optionally remove the arg unless you anticipate passing a different one.

**Pull request merged**
