### PR TITLE
BDDRoute: admin dist is only 8 bits (unsigned)

### PR DESCRIPTION
**Pull request by dhalperi**
Max value is 255

---

**Stack**:
- #8223
- #8222
- #8224 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by millstein — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8224)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @anothermattbrown and @dhalperi)

___
*[projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/BDDRoute.java, line 169 at r1](https://reviewable.io/reviews/batfish/batfish/8224#-N--Iiv2BtlSsT0B805i:-N--Iiv2BtlSsT0B805j:b-s1na2z) ([raw file](https://github.com/batfish/batfish/blob/5dcfb72de688604a5ca3ad286cc8cbc887711837/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/BDDRoute.java#L169)):*
> ```Java
>     _adminDist = MutableBDDInteger.makeFromIndex(factory, 8, idx, false);
>     addBitNames("ad", 8, idx, false);
>     idx += 32;
> ```

This should become idx += 8, and the count of total bits needed (see numNeeded earlier) should be reduced accordingly as well.

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8224)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @anothermattbrown and @millstein)

___
*[projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/BDDRoute.java, line 169 at r1](https://reviewable.io/reviews/batfish/batfish/8224#-N--Iiv2BtlSsT0B805i:-N--NQoZ6aei23M4_tKd:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/5dcfb72de688604a5ca3ad286cc8cbc887711837/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/BDDRoute.java#L169)):*
<details><summary><i>Previously, millstein (Todd Millstein) wrote…</i></summary><blockquote>

This should become idx += 8, and the count of total bits needed (see numNeeded earlier) should be reduced accordingly as well.
</blockquote></details>

Done.

**Review by dhalperi — COMMENTED** [review]
> Dismissed @millstein from a discussion.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8224)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @anothermattbrown)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8224)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown)

**Comment by dhalperi** [comment]
Closing pull request: commit has gone away

**Pull request closed without merging**
