### PR TITLE
auto completing nodes

### PR DESCRIPTION
**Pull request by ratulm**
Basic logic; scaffolding coming. 

(merging into non-master because of some stupidity. i'll clean up things later.)

### CODE REVIEW

**Comment by corinaminer** [comment]
Reviewed 4 of 6 files at r1, 18 of 18 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1323#-LC091A8CVVC41h66eRY:-LC091A8CVVC41h66eRZ:b-tsu6ii) (no related file):*
Looking good. It will definitely be helpful to be able to identify nodes by role/role dimension.

Would be extremely helpful for reviewing and for moving forward to have a design doc, or even just a summary of the changes and why they were made in the PR description. Hard to be sure it's doing the right thing when the code is the only context I have for what it's supposed to do.

As far as the [rich parameter type discussion](https://docs.google.com/document/d/1Ekb2MRqUJNGuJdu_44q9apTUHjY9U0y-XDz7lWXWvEc/edit#heading=h.o80lizak9t7m) from Alb's tech talk, this is a move in the right direction, but does not provide a basis for combining node-identifying parameter types (node, IP, IP range/list) into one rich type. That should probably be done separately.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/AutocompleteSuggestion.java, line 14 at r2](https://reviewable.io/reviews/batfish/batfish/1323#-LC0-Z7z7AGj7W-LvP-3:-LC0-Z7z7AGj7W-LvP-4:b-h98zv1) ([raw file](https://github.com/batfish/batfish/blob/660651518dd1e494eb7ac69abc9b182fc66523d0/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/AutocompleteSuggestion.java#L14)):*
> ```Java
>   }
> 
>   @Nullable private final String _description;
> ```

What's the intent for the description? An AutocompleteSuggestion is just one suggested value, like "as1border1" if the user types "as1", right?

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/questions/NodesSpecifierTest.java, line 96 at r2](https://reviewable.io/reviews/batfish/batfish/1323#-LC06dh08Lh9KdNfL2gK:-LC06dh08Lh9KdNfL2gL:b-bcnykd) ([raw file](https://github.com/batfish/batfish/blob/660651518dd1e494eb7ac69abc9b182fc66523d0/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/questions/NodesSpecifierTest.java#L96)):*
> ```Java
>     assertThat(suggestionsName.get(2).getText(), equalTo("nade1"));
> 
>     // suggestionsRole should have one element: NAME:
> ```

This comment and the one for `suggestionsName` list the expected elements incorrectly. Also the following 3 tests all have comments that refer to `suggestionsName`, but should refer to the names of the suggestion lists in those tests.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1323)*

**Comment by ratulm** [comment]
Review status: 21 of 22 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1323#-LC091A8CVVC41h66eRY:-LC2SZrs-zEUi5kmiJ9Z:b-9xnko6) (no related file):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Looking good. It will definitely be helpful to be able to identify nodes by role/role dimension.

Would be extremely helpful for reviewing and for moving forward to have a design doc, or even just a summary of the changes and why they were made in the PR description. Hard to be sure it's doing the right thing when the code is the only context I have for what it's supposed to do.

As far as the [rich parameter type discussion](https://docs.google.com/document/d/1Ekb2MRqUJNGuJdu_44q9apTUHjY9U0y-XDz7lWXWvEc/edit#heading=h.o80lizak9t7m) from Alb's tech talk, this is a move in the right direction, but does not provide a basis for combining node-identifying parameter types (node, IP, IP range/list) into one rich type. That should probably be done separately.
</blockquote></details>

Good point about missing high-level description. Basic changes:

1/ A new API in WorkServiceService to autocomplete, which takes in a type and the query. Node is the only supported type at the moment. 

2/ What is returned is a list of AutocompleteSuggestion objects.

3/ The javadoc comment for autoComplete in NodesSpecifier talks about that list contains. The auto complete logic sits in this class because this specifier is supposed to encode all the rich methods in which groups of nodes can be specified. Currently, supported methods include picking nodes by name regexes and role (dimensions). 

Does this make sense? Let me know if things still seem unclear.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/AutocompleteSuggestion.java, line 14 at r2](https://reviewable.io/reviews/batfish/batfish/1323#-LC0-Z7z7AGj7W-LvP-3:-LC2ST_4Dr3dwjoVlR4d:bwkue6b) ([raw file](https://github.com/batfish/batfish/blob/660651518dd1e494eb7ac69abc9b182fc66523d0/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/AutocompleteSuggestion.java#L14)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

What's the intent for the description? An AutocompleteSuggestion is just one suggested value, like "as1border1" if the user types "as1", right?
</blockquote></details>

In general, autocomple 

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/questions/NodesSpecifierTest.java, line 96 at r2](https://reviewable.io/reviews/batfish/batfish/1323#-LC06dh08Lh9KdNfL2gK:-LC2UzX24zoKMXvYcwyF:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/660651518dd1e494eb7ac69abc9b182fc66523d0/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/questions/NodesSpecifierTest.java#L96)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

This comment and the one for `suggestionsName` list the expected elements incorrectly. Also the following 3 tests all have comments that refer to `suggestionsName`, but should refer to the names of the suggestion lists in those tests.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1323)*

**Comment by corinaminer** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1323#-LC091A8CVVC41h66eRY:-LC5ERqcEivLKwBFMwD9:b-g9m1hh) (no related file):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

Good point about missing high-level description. Basic changes:

1/ A new API in WorkServiceService to autocomplete, which takes in a type and the query. Node is the only supported type at the moment. 

2/ What is returned is a list of AutocompleteSuggestion objects.

3/ The javadoc comment for autoComplete in NodesSpecifier talks about that list contains. The auto complete logic sits in this class because this specifier is supposed to encode all the rich methods in which groups of nodes can be specified. Currently, supported methods include picking nodes by name regexes and role (dimensions). 

Does this make sense? Let me know if things still seem unclear.
</blockquote></details>

Yep, this clarifies and confirms my understanding from first pass. That said, I do think this work is complex enough to merit a design doc. (There isn't one already, right?)

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/AutocompleteSuggestion.java, line 14 at r2](https://reviewable.io/reviews/batfish/batfish/1323#-LC0-Z7z7AGj7W-LvP-3:-LC5FIDx9c0DRPyAz2Sk:b-k23r97) ([raw file](https://github.com/batfish/batfish/blob/660651518dd1e494eb7ac69abc9b182fc66523d0/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/AutocompleteSuggestion.java#L14)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

In general, autocomple 
</blockquote></details>

Did autocomplete not autocomplete this comment? ;)

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/questions/NodesSpecifierTest.java, line 96 at r2](https://reviewable.io/reviews/batfish/batfish/1323#-LC06dh08Lh9KdNfL2gK:-LC5Du9p1aBRax8kQmM1:b-pzsb1b) ([raw file](https://github.com/batfish/batfish/blob/660651518dd1e494eb7ac69abc9b182fc66523d0/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/questions/NodesSpecifierTest.java#L96)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Looks good except for the comment 6 lines above here: `// suggestionsName should have three elements: NAME:`

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1323)*

**Comment by ratulm** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1323#-LC091A8CVVC41h66eRY:-LC5qvuS77w48xgqTz-S:b-jk4jvo) (no related file):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Yep, this clarifies and confirms my understanding from first pass. That said, I do think this work is complex enough to merit a design doc. (There isn't one already, right?)
</blockquote></details>

There isn't one for this specific feature. Things like roles etc are documented elsewhere. I didn't think it was that complex enough -- the autocompletion returns all valid partial and complete things that the user should have typed give a prefix string that they entered. Let me know if you'd like me to create one now. 

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/AutocompleteSuggestion.java, line 14 at r2](https://reviewable.io/reviews/batfish/batfish/1323#-LC0-Z7z7AGj7W-LvP-3:-LC5qCHV-ROlCJt-g239:b-7ley7z) ([raw file](https://github.com/batfish/batfish/blob/660651518dd1e494eb7ac69abc9b182fc66523d0/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/AutocompleteSuggestion.java#L14)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Did autocomplete not autocomplete this comment? ;)
</blockquote></details>

:) Sorry, I was scatter-brained ...

In general, autocomplete returns both fully formed suggestions (e.g., as2border1) and partial suggestions (e.g., NAME:). I was thinking that the UI might use the description field to explain to the user what each suggestion means. It does not have when we come down to it, but I figured I'll keep it there for now in case it proves useful.

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/questions/NodesSpecifierTest.java, line 96 at r2](https://reviewable.io/reviews/batfish/batfish/1323#-LC06dh08Lh9KdNfL2gK:-LC5qtVd30BX3Q_cbiHM:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/660651518dd1e494eb7ac69abc9b182fc66523d0/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/questions/NodesSpecifierTest.java#L96)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Looks good except for the comment 6 lines above here: `// suggestionsName should have three elements: NAME:`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1323)*

**Comment by corinaminer** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1323#-LC091A8CVVC41h66eRY:-LC5s-hL3tg7WHSb6teQ:b-yq9cyp) (no related file):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

There isn't one for this specific feature. Things like roles etc are documented elsewhere. I didn't think it was that complex enough -- the autocompletion returns all valid partial and complete things that the user should have typed give a prefix string that they entered. Let me know if you'd like me to create one now. 
</blockquote></details>

Your description above is probably good enough for anyone looking to build on this in the future. The main reason I think starting with a design doc would have made sense was that I could have gotten on board with your plan before you started coding -- might have saved a lot of time if I'd thought it was a bad approach.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1323#-:-LC5rzsHBFLep9W5C0nJ:bnfp4nl)*

**Comment by ratulm** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1323#-LC091A8CVVC41h66eRY:-LC5uTAWD0HW2eV7GXm7:b-6oa9tt) (no related file):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Your description above is probably good enough for anyone looking to build on this in the future. The main reason I think starting with a design doc would have made sense was that I could have gotten on board with your plan before you started coding -- might have saved a lot of time if I'd thought it was a bad approach.
</blockquote></details>

ack (for the future). thanks.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1323)*

**Pull request merged**
