### PR TITLE
Cisco NX-OS fix layer-2 and layer-3 VNI instantiation requirements

### PR DESCRIPTION
**Pull request by arifogel**
- remove requirement for l2/l3 VNIs to be mapped to some IRB (Vlan)
  interface
- remove requirement for layer3-vnis to be associated with a vlan

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7797)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_l2_l3_vnis, line 67 at r1](https://reviewable.io/reviews/batfish/batfish/7797#-MqqN2t32GrCo-bz30Me:-MqqN2t32GrCo-bz30Mf:bhrvyr4) ([raw file](https://github.com/batfish/batfish/blob/973ae0f42c7a979831ef98514b0cb154cfb0778f/projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_l2_l3_vnis#L67)):*
<details><summary><i alt="summary">Quoted 11 lines of code…</i></summary>

> ```
> 
> interface Vlan1
>   vrf member tenant1
>   no shutdown
> !
> interface Vlan2
>   no shutdown
> !
> interface Vlan3
>   vrf member tenant1
>   no shutdown
> ```
</details>

something seems sketchy here - there are no interfaces in the tenant vrf but we think we can leak into it?

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7797)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_l2_l3_vnis, line 67 at r1](https://reviewable.io/reviews/batfish/batfish/7797#-MqqN2t32GrCo-bz30Me:-MqqNVnN65NY1sEkcRBD:bha76re) ([raw file](https://github.com/batfish/batfish/blob/973ae0f42c7a979831ef98514b0cb154cfb0778f/projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_l2_l3_vnis#L67)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> 
> interface Vlan1
>   vrf member tenant1
>   no shutdown
> !
> interface Vlan2
>   no shutdown
> !
> interface Vlan3
>   vrf member tenant1
>   no shutdown
> ```
something seems sketchy here - there are no interfaces in the tenant vrf but we think we can leak into it?
</blockquote></details>

(if the claim was we don't need them for the L2 VNIs, that makes sense to me)

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7797)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @corinaminer and @dhalperi)

___
*[projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_l2_l3_vnis, line 67 at r1](https://reviewable.io/reviews/batfish/batfish/7797#-MqqN2t32GrCo-bz30Me:-MqqNRxRALj2SARf8Dxp:bv7yx2g) ([raw file](https://github.com/batfish/batfish/blob/973ae0f42c7a979831ef98514b0cb154cfb0778f/projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_l2_l3_vnis#L67)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

(if the claim was we don't need them for the L2 VNIs, that makes sense to me)
</blockquote></details>

Well, there were not IP addresses on those interfaces, so seems just as sketchy before (for l3vnis).
Added physical interfaces for the l3vni vrfs for sanity.

For l2vnis, you don't leak, so no VRF needed.

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7797)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @corinaminer)

___
*[projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_l2_l3_vnis, line 67 at r1](https://reviewable.io/reviews/batfish/batfish/7797#-MqqN2t32GrCo-bz30Me:-MqqPTS11FPh9B1es8qm:brjsxv6) ([raw file](https://github.com/batfish/batfish/blob/973ae0f42c7a979831ef98514b0cb154cfb0778f/projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_l2_l3_vnis#L67)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Well, there were not IP addresses on those interfaces, so seems just as sketchy before (for l3vnis).
Added physical interfaces for the l3vni vrfs for sanity.

For l2vnis, you don't leak, so no VRF needed.
</blockquote></details>

(also nothing blocking, just asking qs)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7797)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7797#-MqqQ9YjB4uox6N8S-yg:-MqqQ9YjB4uox6N8S-yh:b-uglbtv) (no related file):*
Low confidence LGTM :) Would be happier with @corinaminer taking a look, but also fine if you're happy with it.

---

**Pull request merged**
