### PR TITLE
Cleanup track evaluation

### PR DESCRIPTION
**Pull request by arifogel**
- for tracking an interface, evaluator now returns true when interface is up
- TrackAction now has property getNegateTrack()
  - when true, client of TrackMethod evaluator should negate the result evaluation when deciding
    whether to evaluate TrackAction

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7925)* status: 2 of 15 files reviewed, 1 unresolved discussion (waiting on @arifogel and @dhalperi)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/TrackAction.java, line 8 at r1](https://reviewable.io/reviews/batfish/batfish/7925#-MtB28HU5v8Pazo104vG:-MtB28HVEIKq-6zDes6A:brxkbzu) ([raw file](https://github.com/batfish/batfish/blob/a224fb830cc1eee0ab4e4dd1985ecadd082c4399/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/TrackAction.java#L8)):*
> ```Java
> /** An action to take when a {@link TrackMethod} has been triggered (is down). */
> @JsonTypeInfo(use = JsonTypeInfo.Id.CLASS, property = "class")
> public interface TrackAction extends Serializable {
> ```

This seems like it belongs in the track, not the action, right?

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7925)* status: 2 of 15 files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/TrackAction.java, line 8 at r1](https://reviewable.io/reviews/batfish/batfish/7925#-MtB28HU5v8Pazo104vG:-MtB7Xk01o3sZlaa_4ht:b9u8i0u) ([raw file](https://github.com/batfish/batfish/blob/a224fb830cc1eee0ab4e4dd1985ecadd082c4399/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/TrackAction.java#L8)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

This seems like it belongs in the track, not the action, right?
</blockquote></details>

DO you mean `TrackMethod`? It cannot, since the method is associated with a single index. That is, two callers could refer to the same `TrackMethod` by index, but only one caller would want to negate. The `TrackAction`, in contrast, is associated with the caller.

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7925)* status: 2 of 16 files reviewed, 1 unresolved discussion (waiting on @arifogel and @dhalperi)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/TrackAction.java, line 8 at r1](https://reviewable.io/reviews/batfish/batfish/7925#-MtB28HU5v8Pazo104vG:-MtBEg8rEaT50YNwHs8P:b-m00prs) ([raw file](https://github.com/batfish/batfish/blob/a224fb830cc1eee0ab4e4dd1985ecadd082c4399/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/TrackAction.java#L8)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

DO you mean `TrackMethod`? It cannot, since the method is associated with a single index. That is, two callers could refer to the same `TrackMethod` by index, but only one caller would want to negate. The `TrackAction`, in contrast, is associated with the caller.
</blockquote></details>

I could think of:

1. Add `TrackMethod` `Negate(TrackMethod inner)`. On a VS-basis, create up to two different tracks (one negated, one not) depending on the VS use semantics. Note that as `StaticRoute#_track` is a string, nothing is keeping us from doing, say, `100-up` and `100-down` for VS `track 100`.

2. Add `TrackReference(String idx, boolean negate)`. Replace current `String _track` with `TrackReference` in VI.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7925)* status: 0 of 30 files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/TrackAction.java, line 8 at r1](https://reviewable.io/reviews/batfish/batfish/7925#-MtB28HU5v8Pazo104vG:-MtBHDBo1WEUGIFRnxSz:bl7oz6r) ([raw file](https://github.com/batfish/batfish/blob/a224fb830cc1eee0ab4e4dd1985ecadd082c4399/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/TrackAction.java#L8)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I could think of:

1. Add `TrackMethod` `Negate(TrackMethod inner)`. On a VS-basis, create up to two different tracks (one negated, one not) depending on the VS use semantics. Note that as `StaticRoute#_track` is a string, nothing is keeping us from doing, say, `100-up` and `100-down` for VS `track 100`.

2. Add `TrackReference(String idx, boolean negate)`. Replace current `String _track` with `TrackReference` in VI.
</blockquote></details>

Went with a combination. See how you like it.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 30 of 30 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7925)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/DecrementPriority.java, line 40 at r3](https://reviewable.io/reviews/batfish/batfish/7925#-MtEQnnK5ZZwHw6shJbQ:-MtEQnnK5ZZwHw6shJbR:bh6nrmt) ([raw file](https://github.com/batfish/batfish/blob/b04fe020d9e6a885ebf35cee7f101a45db77b461/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/DecrementPriority.java#L40)):*
> ```Java
>   @Override
>   public int hashCode() {
>     return Objects.hash(_subtrahend);
> ```

why this change? It's a no-op on int btw.

If needed, use `Integer.hashCode` to avoid some work.



_Code quote:_
```Java
Objects.hash(_subtrahend);
```
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/PredicateTrackMethodEvaluator.java, line 36 at r3](https://reviewable.io/reviews/batfish/batfish/7925#-MtEQRUi3HitYw3Qhits:-MtEQRUi3HitYw3Qhitt:bd2w8u9) ([raw file](https://github.com/batfish/batfish/blob/b04fe020d9e6a885ebf35cee7f101a45db77b461/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/PredicateTrackMethodEvaluator.java#L36)):*
> ```Java
>       return false;
>     }
>     return trackedInterface.getActive() && !trackedInterface.getBlacklisted();
> ```

(FYI) why is this necessary? Seems like `active` should already have taken this into account.



_Code quote:_
```Java
 && !trackedInterface.getBlacklisted()
```
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/TrackAction.java, line 8 at r1](https://reviewable.io/reviews/batfish/batfish/7925#-MtB28HU5v8Pazo104vG:-MtERnO33-PIDXeIGdOM:b-9ug5iw) ([raw file](https://github.com/batfish/batfish/blob/a224fb830cc1eee0ab4e4dd1985ecadd082c4399/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/TrackAction.java#L8)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Went with a combination. See how you like it.
</blockquote></details>

Interesting. is there a use case for Reference outside of Negated?

Fine either way.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7925)* status: 29 of 30 files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/DecrementPriority.java, line 40 at r3](https://reviewable.io/reviews/batfish/batfish/7925#-MtEQnnK5ZZwHw6shJbQ:-MtEciFTAjoSV1qoBP49:b2zr20m) ([raw file](https://github.com/batfish/batfish/blob/b04fe020d9e6a885ebf35cee7f101a45db77b461/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/DecrementPriority.java#L40)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

why this change? It's a no-op on int btw.

If needed, use `Integer.hashCode` to avoid some work.
</blockquote></details>

Oh that was a mindless revert. Fixed
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/PredicateTrackMethodEvaluator.java, line 36 at r3](https://reviewable.io/reviews/batfish/batfish/7925#-MtEQRUi3HitYw3Qhits:-MtEcuuq35abOqrKW1Hc:b-nlsn3w) ([raw file](https://github.com/batfish/batfish/blob/b04fe020d9e6a885ebf35cee7f101a45db77b461/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/PredicateTrackMethodEvaluator.java#L36)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

(FYI) why is this necessary? Seems like `active` should already have taken this into account.
</blockquote></details>

Didn't dig into invariants.
Looing now, there are several places in the code that check active and blacklisted together.
E.g. in `IpOwners.computeIpInterfaceOwners`:
```
                  if ((!i.getActive() || i.getBlacklisted()) && excludeInactive) {
                    return;
                  }
```
 I think if there is an invariant that blacklisted -> !active, then, we should fix this in a separate PR for all such usages.

Note this may be ripe for fixing when we add granularity to interface status.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/TrackAction.java, line 8 at r1](https://reviewable.io/reviews/batfish/batfish/7925#-MtB28HU5v8Pazo104vG:-MtEdnX-EchP6whtk3CE:b-x6ox78) ([raw file](https://github.com/batfish/batfish/blob/a224fb830cc1eee0ab4e4dd1985ecadd082c4399/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/TrackAction.java#L8)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Interesting. is there a use case for Reference outside of Negated?

Fine either way.
</blockquote></details>

Just future-proofing in case e.g. XR or Juniper allow boolean combinations or other complex crap.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7925)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi)

**Pull request merged**
