### PR TITLE
juniper parse and partially convert condition

### PR DESCRIPTION
**Pull request by arifogel**
- parse, convert policy-statement from condition
- parse, partially convert policy-options condition if-route-exists
  - TODO: VI design and implementation for checking route existence in RP
    - just return false for if-route-exists for now

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 15 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6658)* status: all files reviewed, 6 unresolved discussions (waiting on @arifogel)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_policy_options.g4, line 41 at r1](https://reviewable.io/reviews/batfish/batfish/6658#-MUM0DlE6V6V5fQIs_OD:-MUM0DlE6V6V5fQIs_OE:b9ptb0a) ([raw file](https://github.com/batfish/batfish/blob/ab93ef3b20ceaab319d0918c1176de82e02ea75b/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_policy_options.g4#L41)):*
> ```
>  (
> ```

please put paren on next line. Better to conform with existing standards. If you want to refactor entire grammar, that can be done, but later.
___
*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 6168 at r1](https://reviewable.io/reviews/batfish/batfish/6658#-MUM0bJE3m778i4KdMBx:-MUM0bJE3m778i4KdMBy:b-dd8oit) ([raw file](https://github.com/batfish/batfish/blob/ab93ef3b20ceaab319d0918c1176de82e02ea75b/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L6168)):*
> ```
> tIfRouteExists().setPrefix(toPrefix(ctx.prefix));
> ```
can't check two prefixes?
___
*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 6173 at r1](https://reviewable.io/reviews/batfish/batfish/6658#-MUM0cn4CWZm6Qe3SGEA:-MUM0cn4CWZm6Qe3SGEB:b-uz2o56) ([raw file](https://github.com/batfish/batfish/blob/ab93ef3b20ceaab319d0918c1176de82e02ea75b/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L6173)):*
> ```
> xists().setTable(unquote(ctx.name.getText()));
> ```
can't check two tables?
___
*[projects/batfish/src/main/java/org/batfish/representation/juniper/Condition.java, line 30 at r1](https://reviewable.io/reviews/batfish/batfish/6658#-MUM0kw2DP_Gx_7ZwGnO:-MUM0kw2DP_Gx_7ZwGnP:bpoijy1) ([raw file](https://github.com/batfish/batfish/blob/ab93ef3b20ceaab319d0918c1176de82e02ea75b/projects/batfish/src/main/java/org/batfish/representation/juniper/Condition.java#L30)):*
> ```Java
>   }
> 
>   private final String _name;
> ```

@Nonnull
___
*[projects/batfish/src/main/java/org/batfish/representation/juniper/PsFromCondition.java, line 5 at r1](https://reviewable.io/reviews/batfish/batfish/6658#-MUM1AXm8iKlOKlbSFb9:-MUM1AXm8iKlOKlbSFbA:b-kur3uu) ([raw file](https://github.com/batfish/batfish/blob/ab93ef3b20ceaab319d0918c1176de82e02ea75b/projects/batfish/src/main/java/org/batfish/representation/juniper/PsFromCondition.java#L5)):*
> ```
> n.base.Objects;
> ```
use java objects, not guava objects. (MoreObjects if guava).
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/HasRoute.java, line 15 at r1](https://reviewable.io/reviews/batfish/batfish/6658#-MUM1Kb7EsFoFvcj0dKz:-MUM1Kb7EsFoFvcj0dL-:bvzjz57) ([raw file](https://github.com/batfish/batfish/blob/ab93ef3b20ceaab319d0918c1176de82e02ea75b/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/HasRoute.java#L15)):*
> ```Java
> 
> @ParametersAreNonnullByDefault
> public final class HasRoute extends BooleanExpr {
> ```

This looks like a never-implemented IOS-XR construct. Let's not add a new dependency on it, but rather just convert as False for now?

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6658)* status: 10 of 14 files reviewed, 3 unresolved discussions (waiting on @dhalperi)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_policy_options.g4, line 41 at r1](https://reviewable.io/reviews/batfish/batfish/6658#-MUM0DlE6V6V5fQIs_OD:-MUM8I5J3yKCEMKi8kUl:b-2ojg2x) ([raw file](https://github.com/batfish/batfish/blob/ab93ef3b20ceaab319d0918c1176de82e02ea75b/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_policy_options.g4#L41)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
>  (
> ```

please put paren on next line. Better to conform with existing standards. If you want to refactor entire grammar, that can be done, but later.
</blockquote></details>

ok, done
___
*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 6168 at r1](https://reviewable.io/reviews/batfish/batfish/6658#-MUM0bJE3m778i4KdMBx:-MUM8BEU0lhOWOb3-ZkY:bb7lgjf) ([raw file](https://github.com/batfish/batfish/blob/ab93ef3b20ceaab319d0918c1176de82e02ea75b/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L6168)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> tIfRouteExists().setPrefix(toPrefix(ctx.prefix));
> ```
can't check two prefixes?
</blockquote></details>

nope
___
*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 6173 at r1](https://reviewable.io/reviews/batfish/batfish/6658#-MUM0cn4CWZm6Qe3SGEA:-MUM8BnqBVdIGuIwEXXG:bb7lgjf) ([raw file](https://github.com/batfish/batfish/blob/ab93ef3b20ceaab319d0918c1176de82e02ea75b/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L6173)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> xists().setTable(unquote(ctx.name.getText()));
> ```
can't check two tables?
</blockquote></details>

nope
___
*[projects/batfish/src/main/java/org/batfish/representation/juniper/Condition.java, line 30 at r1](https://reviewable.io/reviews/batfish/batfish/6658#-MUM0kw2DP_Gx_7ZwGnO:-MUM7ByrDuKLbNDZwvWQ:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/ab93ef3b20ceaab319d0918c1176de82e02ea75b/projects/batfish/src/main/java/org/batfish/representation/juniper/Condition.java#L30)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

@Nonnull
</blockquote></details>

done
___
*[projects/batfish/src/main/java/org/batfish/representation/juniper/PsFromCondition.java, line 5 at r1](https://reviewable.io/reviews/batfish/batfish/6658#-MUM1AXm8iKlOKlbSFb9:-MUM7REU8PcZOe3V0c0w:byoq5j5) ([raw file](https://github.com/batfish/batfish/blob/ab93ef3b20ceaab319d0918c1176de82e02ea75b/projects/batfish/src/main/java/org/batfish/representation/juniper/PsFromCondition.java#L5)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> n.base.Objects;
> ```
use java objects, not guava objects. (MoreObjects if guava).
</blockquote></details>

oops! fixed.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/HasRoute.java, line 15 at r1](https://reviewable.io/reviews/batfish/batfish/6658#-MUM1Kb7EsFoFvcj0dKz:-MUM7v-h79A8iwgGUCJG:b-qfn9fj) ([raw file](https://github.com/batfish/batfish/blob/ab93ef3b20ceaab319d0918c1176de82e02ea75b/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/HasRoute.java#L15)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

This looks like a never-implemented IOS-XR construct. Let's not add a new dependency on it, but rather just convert as False for now?
</blockquote></details>

ok. reverted here, and changed where it was used.

**Review by dhalperi — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6658#-:-MUMFf0TA3VmZkKy1wCw:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_policy_options.g4, line 42 at r2](https://reviewable.io/reviews/batfish/batfish/6658#-MUMFtYG7wS77b_IBYYC:-MUMFtYHEYqQKy6c7tVP:b-jiqtw) ([raw file](https://github.com/batfish/batfish/blob/09e6c8e2d8bb51a92fefd288577328383e4aa471/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_policy_options.g4#L42)):*
> ```ANTLR
> :
>   CONDITION name = junos_name
>   (
> ```

Throughout? Or leave it.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6658)* status: 13 of 14 files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_policy_options.g4, line 42 at r2](https://reviewable.io/reviews/batfish/batfish/6658#-MUMFtYG7wS77b_IBYYC:-MUPdjzR7qIimhlrqoLG:b-80rref) ([raw file](https://github.com/batfish/batfish/blob/09e6c8e2d8bb51a92fefd288577328383e4aa471/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_policy_options.g4#L42)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Throughout? Or leave it.
</blockquote></details>

missed that other one.

WRT other style changes, I'd prefer to leave the one-line rules/tokens that are super simple unless you strongly object prior to a full refactor.

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6658)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
