### PR TITLE
Add PAN syslog host extraction

### PR DESCRIPTION
**Pull request by sfraint**
Add syslog host extraction for Palo Alto Networks

### CODE REVIEW

**Comment by anothermattbrown** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed, 2 unresolved discussions (waiting on @sfraint and @arifogel)

---

*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/Server.java, line 5 at r1](https://reviewable.io/reviews/batfish/batfish/1641#-LEpOxkxBbLhn-pRlmaI:-LEpOxkxBbLhn-pRlmaJ:b-yag61j) ([raw file](https://github.com/batfish/batfish/blob/9611bcb0f13bad6a95a8f6149bbe6db78fa4b177/projects/batfish/src/main/java/org/batfish/representation/palo_alto/Server.java#L5)):*
> ```Java
> import org.batfish.common.util.ComparableStructure;
> 
> public class Server extends ComparableStructure<String> {
> ```

Javadoc please.
Can this be final?

---

*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/ServerProfile.java, line 7 at r1](https://reviewable.io/reviews/batfish/batfish/1641#-LEpP1OW5j1ZOsQDc-XL:-LEpP1OW5j1ZOsQDc-XM:b-j8zydz) ([raw file](https://github.com/batfish/batfish/blob/9611bcb0f13bad6a95a8f6149bbe6db78fa4b177/projects/batfish/src/main/java/org/batfish/representation/palo_alto/ServerProfile.java#L7)):*
> ```Java
> import org.batfish.common.util.ComparableStructure;
> 
> public class ServerProfile extends ComparableStructure<String> {
> ```

javadoc please.
can this be final?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1641#-:-LEpPlJW47KvoKBU2uJG:bnfp4nl)*

**Comment by sfraint** [comment]
Review status: 5 of 8 files reviewed, 1 unresolved discussion (waiting on @anothermattbrown, @sfraint, and @arifogel)

---

*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/ServerProfile.java, line 7 at r1](https://reviewable.io/reviews/batfish/batfish/1641#-LEpP1OW5j1ZOsQDc-XL:-LEpeNiTEe0RDlOaGKMu:b-q2mawj) ([raw file](https://github.com/batfish/batfish/blob/9611bcb0f13bad6a95a8f6149bbe6db78fa4b177/projects/batfish/src/main/java/org/batfish/representation/palo_alto/ServerProfile.java#L7)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

javadoc please.
can this be final?
</blockquote></details>

Per discussion, going to just remove this.

---

*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/Server.java, line 5 at r1](https://reviewable.io/reviews/batfish/batfish/1641#-LEpOxkxBbLhn-pRlmaI:-LEpXWJH774SB2-g-n5I:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/9611bcb0f13bad6a95a8f6149bbe6db78fa4b177/projects/batfish/src/main/java/org/batfish/representation/palo_alto/Server.java#L5)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

Javadoc please.
Can this be final?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1641)*

**Comment by arifogel** [comment]
Reviewed 5 of 9 files at r1, 4 of 4 files at r2.
Review status: all files reviewed, 2 unresolved discussions (waiting on @anothermattbrown and @sfraint)

---

*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java, line 68 at r2](https://reviewable.io/reviews/batfish/batfish/1641#-LEqeJskBPJ3koTbOBRV:-LEqeJskBPJ3koTbOBRW:b5ghnvh) ([raw file](https://github.com/batfish/batfish/blob/d8b44b727dab08f0554fd44ced72638589ba7eb8/projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java#L68)):*
> ```Java
>   }
> 
>   public SortedMap<String, SortedMap<String, SyslogServer>> getSyslogServerGroups() {
> ```

javadoc please detailing structure

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1641)*

**Comment by anothermattbrown** [comment]
Review status: all files reviewed, 2 unresolved discussions (waiting on @sfraint)

---

*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java, line 14 at r2](https://reviewable.io/reviews/batfish/batfish/1641#-LErDex47GD1u-jWAm-Q:-LErDex5DJzNRWMuio6I:b-b5lx32) ([raw file](https://github.com/batfish/batfish/blob/d8b44b727dab08f0554fd44ced72638589ba7eb8/projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java#L14)):*
> ```Java
> import org.batfish.vendor.VendorConfiguration;
> 
> public class PaloAltoConfiguration extends VendorConfiguration {
> ```

Can this be final? In general, please make classes final if possible.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1641)*

**Comment by sfraint** [comment]
Review status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @arifogel and @sfraint)

---

*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java, line 68 at r2](https://reviewable.io/reviews/batfish/batfish/1641#-LEqeJskBPJ3koTbOBRV:-LEtwgil6K1_5Gd3aomM:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/d8b44b727dab08f0554fd44ced72638589ba7eb8/projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java#L68)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

javadoc please detailing structure
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1641)*

**Comment by sfraint** [comment]
Review status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @arifogel and @anothermattbrown)

---

*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java, line 14 at r2](https://reviewable.io/reviews/batfish/batfish/1641#-LErDex47GD1u-jWAm-Q:-LEtwpzC21Ruehtx8DOS:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/d8b44b727dab08f0554fd44ced72638589ba7eb8/projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java#L14)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

Can this be final? In general, please make classes final if possible.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1641)*

**Comment by anothermattbrown** [comment]
Reviewed 1 of 4 files at r2, 2 of 2 files at r3.
Review status: all files reviewed, 2 unresolved discussions (waiting on @arifogel and @sfraint)

---

*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java, line 73 at r3](https://reviewable.io/reviews/batfish/batfish/1641#-LEu0Ke04MV1tp6hbF4X:-LEu0Ke04MV1tp6hbF4Y:b-lfjgwb) ([raw file](https://github.com/batfish/batfish/blob/7e7faf9c012d2d5edd31a0c81b1e0de9dd73e801/projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java#L73)):*
> ```Java
>    */
>   public SortedMap<String, SortedMap<String, SyslogServer>> getSyslogServerGroups() {
>     return _syslogServerGroups;
> ```

Do clients of this class need to mutate `_syslogServerGroups`? If yes, consider adding methods for the specific needs (e.g. an `addSyslogServer(String, String, SyslogServer)` method), or else document why we need to expose private state. If no, please return an immutable copy, e.g. via `CommonUtil.toImmutableSortedMap`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1641)*

**Comment by arifogel** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed, 1 unresolved discussion (waiting on @sfraint)

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1641)*

**Comment by arifogel** [comment]
:lgtm: from my end

---

Review status: all files reviewed, 1 unresolved discussion (waiting on @sfraint)

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1641#-:-LEuRfvN7bZBKNL8W2Mh:bdp6j0u)*

**Comment by sfraint** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @sfraint and @arifogel)

---

*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java, line 73 at r3](https://reviewable.io/reviews/batfish/batfish/1641#-LEu0Ke04MV1tp6hbF4X:-LEuWewc6NngtxEYzeZH:bms194j) ([raw file](https://github.com/batfish/batfish/blob/7e7faf9c012d2d5edd31a0c81b1e0de9dd73e801/projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java#L73)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

Do clients of this class need to mutate `_syslogServerGroups`? If yes, consider adding methods for the specific needs (e.g. an `addSyslogServer(String, String, SyslogServer)` method), or else document why we need to expose private state. If no, please return an immutable copy, e.g. via `CommonUtil.toImmutableSortedMap`.
</blockquote></details>

During configuration building, groups need to be added (and looked up), and within groups servers need to be added (and looked up).
I think `addSyslogServer(...` is a reasonable alternative to this, this was just following the design pattern of other config builders.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1641)*

**Comment by arifogel** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed, 2 unresolved discussions (waiting on @anothermattbrown and @sfraint)

---

*[projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java, line 102 at r4](https://reviewable.io/reviews/batfish/batfish/1641#-LEub61M3T65isHG_wKz:-LEub61M3T65isHG_wL-:b-hehia4) ([raw file](https://github.com/batfish/batfish/blob/22f92bd21b2eb3f4c80993de47ca10608eb5dbae/projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java#L102)):*
> ```Java
>   @Override
>   public void enterSsl_syslog(Ssl_syslogContext ctx) {
>     _currentSyslogServerGroupName = ctx.name.getText();
> ```

Am I correct in assuming we should not be calling `getText` for names now?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1641)*

**Comment by anothermattbrown** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r4.
Review status: all files reviewed, 1 unresolved discussion (waiting on @sfraint)

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1641#-:-LEubp3fB_qZMNPFZq2M:bnfp4nl)*

**Comment by sfraint** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @sfraint)

---

*[projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java, line 102 at r4](https://reviewable.io/reviews/batfish/batfish/1641#-LEub61M3T65isHG_wKz:-LEuboYtAM3htGeG6enq:b1y2645) ([raw file](https://github.com/batfish/batfish/blob/22f92bd21b2eb3f4c80993de47ca10608eb5dbae/projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java#L102)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Am I correct in assuming we should not be calling `getText` for names now?
</blockquote></details>

yes, will merge that in here once this PR or that one is done

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1641)*

**Comment by arifogel** [comment]
Review status: :shipit: complete! all files reviewed, all discussions resolved

---

*[projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java, line 102 at r4](https://reviewable.io/reviews/batfish/batfish/1641#-LEub61M3T65isHG_wKz:-LEucJMV3YrIdb-8O1m4:b32w0x) ([raw file](https://github.com/batfish/batfish/blob/22f92bd21b2eb3f4c80993de47ca10608eb5dbae/projects/batfish/src/main/java/org/batfish/grammar/palo_alto/PaloAltoConfigurationBuilder.java#L102)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

yes, will merge that in here once this PR or that one is done
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1641)*

**Pull request merged**
