### PR TITLE
Update BGP exports after sub-iteration

### PR DESCRIPTION
**Pull request by arifogel**
- Previously, we were updating exports only after all BGP sub-iterations
  completed.
  - This allowed router from later sub-iteration to pull routes from
    router changed during earlier sub-iteration that should not have
    been exported when taking into account those changes.
- Now we update VR BGP state that could be used other VRs in later inner
  rounds at the end of a VR's inner round

### CODE REVIEW

**Comment by dhalperi** [comment]
___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java, line 504 at r1](https://reviewable.io/reviews/batfish/batfish/7396#-Mjfjlpf-AyZ1Jb_4V6K:-Mjfjlpf-AyZ1Jb_4V6L:b6jsi1k) ([raw file](https://github.com/batfish/batfish/blob/4915b79f3e164bc79b9fca23a823129bfbd8f5fa/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java#L504)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>       assert _mainRibPrev.equals(ImmutableSet.of());
>       assert _bgpv4Prev.equals(ImmutableSet.of());
>       assert _bgpv4PrevBestPath.equals(ImmutableSet.of());
>       assert _ebgpv4Prev.equals(ImmutableSet.of());
>       assert _ebgpv4PrevBestPath.equals(ImmutableSet.of());
> ```
</details>

`.isEmpty()`

**Review by dhalperi — COMMENTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7396)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel)

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7396)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java, line 504 at r1](https://reviewable.io/reviews/batfish/batfish/7396#-Mjfjlpf-AyZ1Jb_4V6K:-MjfnJMi6mSSPMA74j_F:bg46ax7) ([raw file](https://github.com/batfish/batfish/blob/4915b79f3e164bc79b9fca23a823129bfbd8f5fa/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java#L504)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
>       assert _mainRibPrev.equals(ImmutableSet.of());
>       assert _bgpv4Prev.equals(ImmutableSet.of());
>       assert _bgpv4PrevBestPath.equals(ImmutableSet.of());
>       assert _ebgpv4Prev.equals(ImmutableSet.of());
>       assert _ebgpv4PrevBestPath.equals(ImmutableSet.of());
> ```
`.isEmpty()`
</blockquote></details>

How embarassing :eyes: 
Fixed.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7396)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7396)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7396#-MjgQYX56ilk34KSgubL:-MjgQYX56ilk34KSgubM:bkpqel8) (no related file):*
After batfish/batfish#7398

---

**Review by dhalperi — COMMENTED** [review]
> Dismissed @arifogel from a discussion.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7396)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7396)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Pull request merged**
