### PR TITLE
IOS: Fix BGP default-information originate

### PR DESCRIPTION
**Pull request by corinaminer**
Currently, we treat `default-information originate` in BGP as equivalent to the per-peer command `default-originate`. However, they mean totally different things; `default-information originate` just makes it *possible* for default routes to be redistributed into BGP with redistribute statements, whereas `default-originate` causes the peer where it's configured to export a default route to neighbors independent of what routes exist on the originator.

To support the new test config, also cleaned up the IOS BGP grammar (second commit). The cleanup includes:
* No longer permitting `vrf VRF1` as a valid BGP VRF stanza opener; the valid IOS syntax is `address-family ipv4 vrf VRF1` (or whatever address-family)
* Address-families always have `exit-address-family` at the end

Also removed address-family declarations from some neighbor stanzas in tests. There's no such thing as neighbor stanzas in IOS; all per-neighbor configuration lines start with `neighbor x.x.x.x`. Leaving grammar cleanup on that front for another PR.

### CODE REVIEW

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7169)* status: 0 of 28 files reviewed, all discussions resolved (waiting on @dhalperi)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_bgp.g4, line 934 at r1](https://reviewable.io/reviews/batfish/batfish/7169#-MebVcxlDNRdoawGBmJO:-MebVcxlDNRdoawGBmJP:b-jmepyd) ([raw file](https://github.com/batfish/batfish/blob/eb1b2e6e993583b9c466623dd6ef0c34b8ebd720/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_bgp.g4#L934)):*
> ```ANTLR
> ;
> 
> template_peer_address_family
> ```

unused

**Review by dhalperi — COMMENTED** [review]
> Reviewed 28 of 28 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7169)* status: all files reviewed, 1 unresolved discussion (waiting on @corinaminer)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_bgp.g4, line 53 at r1](https://reviewable.io/reviews/batfish/batfish/7169#-MebXWmO1gRUuxmHbmyU:-MebXWmO1gRUuxmHbmyV:b-7d74zt) ([raw file](https://github.com/batfish/batfish/blob/0206deac9b6dc4022515fc15881c9f4a77c48cf5/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_bgp.g4#L53)):*
<details><summary><i alt="summary">Quoted 14 lines of code…</i></summary>

> ```
>    (
>       additional_paths_rb_stanza
>       | aggregate_address_rb_stanza
>       | bgp_af_import
>       | bgp_tail
>       | default_information_originate_rb_stanza
>       | neighbor_flat_rb_stanza
>       | no_neighbor_activate_rb_stanza
>       | no_neighbor_shutdown_rb_stanza
>       | null_no_neighbor_rb_stanza
>       | peer_group_assignment_rb_stanza
>       | peer_group_creation_rb_stanza
>       | router_id_rb_stanza
>    )* EXIT_ADDRESS_FAMILY NEWLINE
> ```
</details>


Now that the suffix is mandatory, I think we need to move the inner text into a subrule or recovery will blow up if it's missing.

(Also, I think Ari had `EXIT | EXIT_A_F` -- since manual configs will take either, whereas `exit-a-f` only appear in show run)

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7169)* status: 27 of 29 files reviewed, all discussions resolved (waiting on @dhalperi)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_bgp.g4, line 53 at r1](https://reviewable.io/reviews/batfish/batfish/7169#-MebXWmO1gRUuxmHbmyU:-MebZfxS6EVwkfI1OvH6:b7kyc5w) ([raw file](https://github.com/batfish/batfish/blob/0206deac9b6dc4022515fc15881c9f4a77c48cf5/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_bgp.g4#L53)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
>    (
>       additional_paths_rb_stanza
>       | aggregate_address_rb_stanza
>       | bgp_af_import
>       | bgp_tail
>       | default_information_originate_rb_stanza
>       | neighbor_flat_rb_stanza
>       | no_neighbor_activate_rb_stanza
>       | no_neighbor_shutdown_rb_stanza
>       | null_no_neighbor_rb_stanza
>       | peer_group_assignment_rb_stanza
>       | peer_group_creation_rb_stanza
>       | router_id_rb_stanza
>    )* EXIT_ADDRESS_FAMILY NEWLINE
> ```

Now that the suffix is mandatory, I think we need to move the inner text into a subrule or recovery will blow up if it's missing.

(Also, I think Ari had `EXIT | EXIT_A_F` -- since manual configs will take either, whereas `exit-a-f` only appear in show run)
</blockquote></details>

Done. And `EXIT | EXIT_A_F` made a failing test pass. :+1:

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7169)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7169)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

**Pull request merged**
