### PR TITLE
Checkpoint: Access Rule conversion

### PR DESCRIPTION
**Pull request by sfraint**
Initial `AccessRule`/`AccessSection`/`AccessLayer` conversion. So far, only source and dest matching is supported and only a single `AccessLayer` will be applied to a given flow.

`AccessSection`s and `AccessLayer`s are converted into VI `IpAccessList`s and `AccessRule`s are embedded as lines in their parent's `IpAccessList`.

----

Lots more to come, like trace elements, matching on flow properties beyond source/dest, etc.

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 10 of 12 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7294)* status: all files reviewed, 7 unresolved discussions (waiting on @corinaminer and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7294#-MiTxhsfCoOMzj4yph0h:-MiTxhsfCoOMzj4yph0i:bl83p0z) (no related file):*
High level - normally for ip access list / ipspace / etc. conversion tests I prefer equivalence tests using BDDs.
Up to you whether to do that in this pr.

---
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java, line 147 at r2](https://reviewable.io/reviews/batfish/batfish/7294#-MiTsu6h4I7viSARXvBv:-MiTsu6h4I7viSARXvBw:b-y2sxrl) ([raw file](https://github.com/batfish/batfish/blob/31d7b8212dcca0a878b2a9d76e8a6b607afc6860/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java#L147)):*
> ```Java
>     if (accessLayers.size() > 1) {
>       _w.redFlag(
>           "Batfish currently only supports matching on a single Access Layer, so only the first"
> ```

Is this true? Looks like you are supporting it below.
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java, line 185 at r2](https://reviewable.io/reviews/batfish/batfish/7294#-MiTtY6U3brvjhtZ_9YG:-MiTtY6U3brvjhtZ_9YH:b-l4rxm9) ([raw file](https://github.com/batfish/batfish/blob/31d7b8212dcca0a878b2a9d76e8a6b607afc6860/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java#L185)):*
> ```Java
>                 _c.getIpSpaces().put(obj.getName(), toIpSpace((Network) obj));
>               } else if (obj instanceof CpmiAnyObject) {
>                 _c.getIpSpaces().put(obj.getName(), UniverseIpSpace.INSTANCE);
> ```

So names can't collide? What was the final word on this?
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConversions.java, line 149 at r2](https://reviewable.io/reviews/batfish/batfish/7294#-MiTudy_8yGtZTysFUCL:-MiTudy_8yGtZTysFUCM:b411rdp) ([raw file](https://github.com/batfish/batfish/blob/31d7b8212dcca0a878b2a9d76e8a6b607afc6860/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConversions.java#L149)):*
> ```Java
>     if (obj == null) {
>       // TODO warn
>     } else if (!(obj instanceof RulebaseAction)) {
> ```

This covers null above (see every `equals` implementation we have).
Also, just do the return here, which will be easier to follow.
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/AccessLayer.java, line 29 at r2](https://reviewable.io/reviews/batfish/batfish/7294#-MiTvHXi2qJn9i-zcgdw:-MiTvHXi2qJn9i-zcgdx:b-yjyrn7) ([raw file](https://github.com/batfish/batfish/blob/31d7b8212dcca0a878b2a9d76e8a6b607afc6860/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/AccessLayer.java#L29)):*
> ```Java
> 
>   @JsonCreator
>   public static @Nonnull AccessLayer create(
> ```

A `@JsonCreator` should always be private. If you need _exactly_ this functionality, move it all to another helper and call it from here.
But why not just call the now public constructor?
___
*[projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/grammar/CheckPointGatewayGrammarTest.java, line 226 at r2](https://reviewable.io/reviews/batfish/batfish/7294#-MiTw5MH-K1_WZjIud98:-MiTw5MH-K1_WZjIud99:bj2x1n4) ([raw file](https://github.com/batfish/batfish/blob/31d7b8212dcca0a878b2a9d76e8a6b607afc6860/projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/grammar/CheckPointGatewayGrammarTest.java#L226)):*
> ```Java
>       int destinationPort) {
>     Flow.Builder fb = Flow.builder();
>     fb.setIngressNode("node");
> ```

Why variable and semicolons between method calls?
Can't you just return `Flow.builder()...setXXX()...build()`?
___
*[projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/grammar/CheckPointGatewayGrammarTest.java, line 971 at r2](https://reviewable.io/reviews/batfish/batfish/7294#-MiTwdtb-lJOEo18brZN:-MiTwdtb-lJOEo18brZO:b-76ozzf) ([raw file](https://github.com/batfish/batfish/blob/31d7b8212dcca0a878b2a9d76e8a6b607afc6860/projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/grammar/CheckPointGatewayGrammarTest.java#L971)):*
> ```Java
>             AccessRule.testBuilder(cpmiAnyUid)
>                 .setAction(acceptUid)
>                 .setDestination(ImmutableList.of(Uid.of("12"))) // dst - net2
> ```

may want to factor out UIDs here like you did in the conversions test

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7294)* status: 8 of 12 files reviewed, 7 unresolved discussions (waiting on @arifogel and @corinaminer)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7294#-MiTxhsfCoOMzj4yph0h:-MiXi7RM4q6w1kfStR98:b-4ev991) (no related file):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

High level - normally for ip access list / ipspace / etc. conversion tests I prefer equivalence tests using BDDs.
Up to you whether to do that in this pr.
</blockquote></details>

good call, but maybe best to wrap this PR up and add that separately / at some point in the future

---
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java, line 147 at r2](https://reviewable.io/reviews/batfish/batfish/7294#-MiTsu6h4I7viSARXvBv:-MiXiCBd215uCiSHtOKF:bwx7w7l) ([raw file](https://github.com/batfish/batfish/blob/31d7b8212dcca0a878b2a9d76e8a6b607afc6860/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java#L147)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Is this true? Looks like you are supporting it below.
</blockquote></details>

we'll still only (currently) consider the first match instead of applying all access layers; need to confirm device behavior but I am under the impression the device requires an `accept` on all layers not just the first match
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java, line 185 at r2](https://reviewable.io/reviews/batfish/batfish/7294#-MiTtY6U3brvjhtZ_9YG:-MiXiPG12kRDiyh2r4Qf:b-xbnagd) ([raw file](https://github.com/batfish/batfish/blob/31d7b8212dcca0a878b2a9d76e8a6b607afc6860/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java#L185)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

So names can't collide? What was the final word on this?
</blockquote></details>

right - no name collisions for these types of objects
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConversions.java, line 149 at r2](https://reviewable.io/reviews/batfish/batfish/7294#-MiTudy_8yGtZTysFUCL:-MiXiiu39Bm-80_orUcr:b-k7c3vk) ([raw file](https://github.com/batfish/batfish/blob/31d7b8212dcca0a878b2a9d76e8a6b607afc6860/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConversions.java#L149)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

This covers null above (see every `equals` implementation we have).
Also, just do the return here, which will be easier to follow.
</blockquote></details>

sure, can return here, but I did want unique warnings for not found versus wrong type
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/AccessLayer.java, line 29 at r2](https://reviewable.io/reviews/batfish/batfish/7294#-MiTvHXi2qJn9i-zcgdw:-MiXirqw4guxp2NlJfgH:b-z706qc) ([raw file](https://github.com/batfish/batfish/blob/31d7b8212dcca0a878b2a9d76e8a6b607afc6860/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/AccessLayer.java#L29)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

A `@JsonCreator` should always be private. If you need _exactly_ this functionality, move it all to another helper and call it from here.
But why not just call the now public constructor?
</blockquote></details>

yep, meant to use the public constructor
___
*[projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/grammar/CheckPointGatewayGrammarTest.java, line 226 at r2](https://reviewable.io/reviews/batfish/batfish/7294#-MiTw5MH-K1_WZjIud98:-MiXkB0Q3g8bXoCzppOW:b-xtjz6c) ([raw file](https://github.com/batfish/batfish/blob/31d7b8212dcca0a878b2a9d76e8a6b607afc6860/projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/grammar/CheckPointGatewayGrammarTest.java#L226)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Why variable and semicolons between method calls?
Can't you just return `Flow.builder()...setXXX()...build()`?
</blockquote></details>

yeah, just copied from elsewhere
___
*[projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/grammar/CheckPointGatewayGrammarTest.java, line 971 at r2](https://reviewable.io/reviews/batfish/batfish/7294#-MiTwdtb-lJOEo18brZN:-MiXlDj912Nio2uHNmmv:bvnrpcm) ([raw file](https://github.com/batfish/batfish/blob/31d7b8212dcca0a878b2a9d76e8a6b607afc6860/projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/grammar/CheckPointGatewayGrammarTest.java#L971)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

may want to factor out UIDs here like you did in the conversions test
</blockquote></details>

updated

**Review by arifogel — COMMENTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7294)* status: all files reviewed, 1 unresolved discussion (waiting on @corinaminer and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConversions.java, line 149 at r2](https://reviewable.io/reviews/batfish/batfish/7294#-MiTudy_8yGtZTysFUCL:-MiY3rqpD8rqrIZ2MKR2:btpqdfi) ([raw file](https://github.com/batfish/batfish/blob/31d7b8212dcca0a878b2a9d76e8a6b607afc6860/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConversions.java#L149)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

sure, can return here, but I did want unique warnings for not found versus wrong type
</blockquote></details>

please just add the warnings now

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7294)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConversions.java, line 149 at r2](https://reviewable.io/reviews/batfish/batfish/7294#-MiTudy_8yGtZTysFUCL:-MiYAX0S-apdCHw2iGBu:bilyla5) ([raw file](https://github.com/batfish/batfish/blob/31d7b8212dcca0a878b2a9d76e8a6b607afc6860/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConversions.java#L149)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

please just add the warnings now
</blockquote></details>

I'll do it in follow-on

**Pull request merged**
