### PR TITLE
Added Cisco protocol obj group support

### LINKED ISSUE #1305: Add IOS protocol object-group support
The following IOS object-group is not applied to the vendor model or vendor independent model:
```
object-group protocol objgrp
 protocol-object tcp
```

This should:
* Produce a corresponding vendor model object group (populated in `CiscoControlPlaneExtractor.java`)
* Produce a vendor independent structure (`IpAccessList`) during conversion to VI model (in `CiscoConfiguration.java`)

### PR DESCRIPTION
**Pull request by sfraint**
* Added parsing and vendor model support for protocol object groups
* Added grammar test

Fixes #1305

### CODE REVIEW

**Comment by arifogel** [comment]
Reviewed 8 of 10 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoStructureUsage.java, line 49 at r2](https://reviewable.io/reviews/batfish/batfish/1281#-LBYh11k2XQyQm_pdFkT:-LBYh11k2XQyQm_pdFkU:bv7jsxd) ([raw file](https://github.com/batfish/batfish/blob/c84541a075840841defbca13f9d42ff2e40d61f6/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoStructureUsage.java#L49)):*
> ```Java
>   DOCSIS_POLICY_DOCSIS_POLICY_RULE("cable load-balance docsis-policy rule"),
>   EXTENDED_ACCESS_LIST_NETWORK_OBJECT_GROUP("extended access-list network object-group"),
>   EXTENDED_ACCESS_LIST_PROTOCOL_OBJECT_GROUP("extended access-list protocol object-group"),
> ```

References of this type are never created. You need to do so in `CiscoControlPlaneExtractor`. Also, you should add tests for reference tracking for this usage.
Furthermore, there are no examples of this usage type in any unit test config added in this PR.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1281)*

**Comment by sfraint** [comment]
Review status: 2 of 19 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoStructureUsage.java, line 49 at r2](https://reviewable.io/reviews/batfish/batfish/1281#-LBYh11k2XQyQm_pdFkT:-LCAHfrX8d9Cv8S4IiHF:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/c84541a075840841defbca13f9d42ff2e40d61f6/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoStructureUsage.java#L49)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

References of this type are never created. You need to do so in `CiscoControlPlaneExtractor`. Also, you should add tests for reference tracking for this usage.
Furthermore, there are no examples of this usage type in any unit test config added in this PR.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1281)*

**Comment by arifogel** [comment]
Reviewed 4 of 9 files at r3, 14 of 14 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 1913 at r4](https://reviewable.io/reviews/batfish/batfish/1281#-LCFNoyb1w0GLaRCkuLo:-LCFNoyb1w0GLaRCkuLp:b-r5jpxz) ([raw file](https://github.com/batfish/batfish/blob/8a17649460c1348ca7095f78bb91daf414232ea0/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L1913)):*
> ```Java
>     if (_configuration.getObjectGroups().get(name) != null) {
>       _currentNetworkObjectGroup = new NetworkObjectGroup(name, definitionLine);
>       _w.redFlag("Object group defined multiple times: '" + name + "'");
> ```

This red flag warning is used multiple times. Maybe factor out?

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/ProtocolOrServiceObjectGroupServiceSpecifier.java, line 21 at r4](https://reviewable.io/reviews/batfish/batfish/1281#-LCFOdDtArro2jlDHROi:-LCFOdDu26gKubcXYcqA:bnuhyu2) ([raw file](https://github.com/batfish/batfish/blob/8a17649460c1348ca7095f78bb91daf414232ea0/projects/batfish/src/main/java/org/batfish/representation/cisco/ProtocolOrServiceObjectGroupServiceSpecifier.java#L21)):*
> ```Java
>   @Override
>   @Nonnull
>   public AclLineMatchExpr toAclLineMatchExpr(Map<String, ObjectGroup> objectGroups) {
> ```

This should return `FalseExpr.INSTANCE` if `objectGroups` does not contain a group with that name, or it does not contain a group with that name that is a service or protocol object-group.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/SimpleExtendedAccessListServiceSpecifier.java, line 128 at r4](https://reviewable.io/reviews/batfish/batfish/1281#-LCFP5wx1hV1rqrmeFj9:-LCFP5wx1hV1rqrmeFjA:b7239m9) ([raw file](https://github.com/batfish/batfish/blob/8a17649460c1348ca7095f78bb91daf414232ea0/projects/batfish/src/main/java/org/batfish/representation/cisco/SimpleExtendedAccessListServiceSpecifier.java#L128)):*
> ```Java
> 
>   @Override
>   @Nonnull
> ```

@dhalperi Is this annotation necessary if the superclass has it?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1281)*

**Comment by sfraint** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 1913 at r4](https://reviewable.io/reviews/batfish/batfish/1281#-LCFNoyb1w0GLaRCkuLo:-LCFbGKpEFcBTkzHZEJ6:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/8a17649460c1348ca7095f78bb91daf414232ea0/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L1913)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

This red flag warning is used multiple times. Maybe factor out?
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/ProtocolOrServiceObjectGroupServiceSpecifier.java, line 21 at r4](https://reviewable.io/reviews/batfish/batfish/1281#-LCFOdDtArro2jlDHROi:-LCFekze6hfUHDjylIqc:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/8a17649460c1348ca7095f78bb91daf414232ea0/projects/batfish/src/main/java/org/batfish/representation/cisco/ProtocolOrServiceObjectGroupServiceSpecifier.java#L21)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

This should return `FalseExpr.INSTANCE` if `objectGroups` does not contain a group with that name, or it does not contain a group with that name that is a service or protocol object-group.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1281)*

**Comment by arifogel** [comment]
Reviewed 4 of 4 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/SimpleExtendedAccessListServiceSpecifier.java, line 128 at r4](https://reviewable.io/reviews/batfish/batfish/1281#-LCFP5wx1hV1rqrmeFj9:-LCFjlOqEhZDNCmt9szF:b-c8yazm) ([raw file](https://github.com/batfish/batfish/blob/8a17649460c1348ca7095f78bb91daf414232ea0/projects/batfish/src/main/java/org/batfish/representation/cisco/SimpleExtendedAccessListServiceSpecifier.java#L128)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

@dhalperi Is this annotation necessary if the superclass has it?
</blockquote></details>

Changing to satisfied. Feel free to ignore.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1281)*

**Comment by arifogel** [comment]
:lgtm: when passing

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1281#-:-LCFjq6z2Iw_gzWFeBpn:bddbw3e)*

**Comment by arifogel** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1281)*

**Comment by dhalperi** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/SimpleExtendedAccessListServiceSpecifier.java, line 128 at r4](https://reviewable.io/reviews/batfish/batfish/1281#-LCFP5wx1hV1rqrmeFj9:-LCHX738Bgh3jRpSjaNM:b-w14co2) ([raw file](https://github.com/batfish/batfish/blob/8a17649460c1348ca7095f78bb91daf414232ea0/projects/batfish/src/main/java/org/batfish/representation/cisco/SimpleExtendedAccessListServiceSpecifier.java#L128)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Changing to satisfied. Feel free to ignore.
</blockquote></details>

Different inference engines will do different things, but it doesn't hurt so I recommend keeping it. IIRC, intellij warns (softly) if it's not present.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1281)*

**Pull request merged**
