### PR TITLE
sort by name if timestamps are equal

### PR DESCRIPTION
**Pull request by ratulm**
This change is [Reviewable](https://reviewable.io/reviews/batfish/batfish/871)

### CODE REVIEW

**Comment by corinaminer** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, line 1094 at r1](https://reviewable.io:443/reviews/batfish/batfish/871#-L3_AtTYNUTxn1iIp_HZ:-L3_AtTZ4yU1DNkXSt63:b-m8kvac) ([raw file](https://github.com/batfish/batfish/blob/d46b3ab176557862adadf68d665b2e8efa1c4bd0/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java#L1094)):*
> ```Java
>                   String key2 =
>                       TestrigMetadataMgr.getTestrigCreationTimeOrMin(containerName, t2) + t2;
>                   return key2.compareTo(key1);
> ```

This will sort any testrigs with the same timestamp in reverse alphabetical order, right? Not a big deal since this is presumably an uncommon case, but I'd probably put them in alphabetical order.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/871)*

**Comment by ratulm** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, line 1094 at r1](https://reviewable.io:443/reviews/batfish/batfish/871#-L3_AtTYNUTxn1iIp_HZ:-L3_EfllHx2KfqcjOHO6:b-erlg2x) ([raw file](https://github.com/batfish/batfish/blob/d46b3ab176557862adadf68d665b2e8efa1c4bd0/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java#L1094)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

This will sort any testrigs with the same timestamp in reverse alphabetical order, right? Not a big deal since this is presumably an uncommon case, but I'd probably put them in alphabetical order.
</blockquote></details>

Umm....why does that matter? I might argue that reverse makes sense, if you are going like t1, t2,
 t3; or they are GUIDs, so meaningless anyway.  And I don't know if a compact way to do that :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/871)*

**Comment by corinaminer** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, line 1094 at r1](https://reviewable.io:443/reviews/batfish/batfish/871#-L3_AtTYNUTxn1iIp_HZ:-L3_IjhzRpDKcB0XU7i_:b-koxg4y) ([raw file](https://github.com/batfish/batfish/blob/d46b3ab176557862adadf68d665b2e8efa1c4bd0/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java#L1094)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

Umm....why does that matter? I might argue that reverse makes sense, if you are going like t1, t2,
 t3; or they are GUIDs, so meaningless anyway.  And I don't know if a compact way to do that :)
</blockquote></details>

Fair enough. (it could be done by defining `key1` as `time1 + t2` and `key2` as `time2 + t1`, though :seedling: )

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/871#-:-L3_JfY1-xPBpen28d9L:bnfp4nl)*

**Comment by dhalperi** [comment]
*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, line 1094 at r1](https://reviewable.io:443/reviews/batfish/batfish/871#-L3_AtTYNUTxn1iIp_HZ:-L3_MIoKt8-XSLAwHk7m:b13krh6) ([raw file](https://github.com/batfish/batfish/blob/d46b3ab176557862adadf68d665b2e8efa1c4bd0/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java#L1094)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Fair enough. (it could be done by defining `key1` as `time1 + t2` and `key2` as `time2 + t1`, though :seedling: )
</blockquote></details>

Can you not do the standard multi-line comparator rather than building a single string and comparing on that?

Using Comparator.comparing().thenComparing() seems like what you'd use:

```
public void whenThenComparing_thenSortedByAgeName(){
    Comparator<Employee> employee_Age_Name_Comparator
      = Comparator.comparing(Employee::getAge)
        .thenComparing(Employee::getName);
   
    Arrays.sort(someMoreEmployees, employee_Age_Name_Comparator);
   
    assertTrue(Arrays.equals(someMoreEmployees, sortedEmployeesByAgeName));
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/871)*

**Comment by ratulm** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, line 1094 at r1](https://reviewable.io:443/reviews/batfish/batfish/871#-L3_AtTYNUTxn1iIp_HZ:-L3_niN9J6vZIdaoAT-c:b5cjd6c) ([raw file](https://github.com/batfish/batfish/blob/d46b3ab176557862adadf68d665b2e8efa1c4bd0/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java#L1094)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Can you not do the standard multi-line comparator rather than building a single string and comparing on that?

Using Comparator.comparing().thenComparing() seems like what you'd use:

```
public void whenThenComparing_thenSortedByAgeName(){
    Comparator<Employee> employee_Age_Name_Comparator
      = Comparator.comparing(Employee::getAge)
        .thenComparing(Employee::getName);
   
    Arrays.sort(someMoreEmployees, employee_Age_Name_Comparator);
   
    assertTrue(Arrays.equals(someMoreEmployees, sortedEmployeesByAgeName));
}
```
</blockquote></details>

yeah, we can. but unless convinced otherwise, i still think the current semantics is better. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/871)*

**Comment by dhalperi** [comment]
*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, line 1094 at r1](https://reviewable.io:443/reviews/batfish/batfish/871#-L3_AtTYNUTxn1iIp_HZ:-L3_wWnNcXu56BVwMeZt:b-oy8a0w) ([raw file](https://github.com/batfish/batfish/blob/d46b3ab176557862adadf68d665b2e8efa1c4bd0/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java#L1094)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

yeah, we can. but unless convinced otherwise, i still think the current semantics is better. 
</blockquote></details>

I'm ambivalent to semantics, aka which result is before which.

I think constructing a compound string to do what is semantically a compound comparison is risky.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/871)*

**Comment by ratulm** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, line 1094 at r1](https://reviewable.io:443/reviews/batfish/batfish/871#-L3_AtTYNUTxn1iIp_HZ:-L3b6AbvtOekd1dHGb9D:b3vjs6m) ([raw file](https://github.com/batfish/batfish/blob/d46b3ab176557862adadf68d665b2e8efa1c4bd0/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java#L1094)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I'm ambivalent to semantics, aka which result is before which.

I think constructing a compound string to do what is semantically a compound comparison is risky.
</blockquote></details>

ah, interesting construct (comparing.thenComparing), which i didn't pay attention to originally.  i tried to make it work for my case, but i couldn't in the time i tried (30+ minutes). the problem is that  we are calling a function (TestrigMetadataMgr.getCreation ...) which is not a member of the class being sorted (String). i believe by defining some lambda functions, it can be done, but doing so compactly is testing the limits of my java knowledge. happy to have you take a crack and i'll learn. 

(as for safety of the compound String, toString() of Instant returns a proper, fixed-length timestamp (01:01:01, not 1:1:1) that can be compounded safely in this context.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/871)*

**Comment by ratulm** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, line 1094 at r1](https://reviewable.io:443/reviews/batfish/batfish/871#-L3_AtTYNUTxn1iIp_HZ:-L3bFoYS1U780BPqC-lu:b711ggg) ([raw file](https://github.com/batfish/batfish/blob/d46b3ab176557862adadf68d665b2e8efa1c4bd0/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java#L1094)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

ah, interesting construct (comparing.thenComparing), which i didn't pay attention to originally.  i tried to make it work for my case, but i couldn't in the time i tried (30+ minutes). the problem is that  we are calling a function (TestrigMetadataMgr.getCreation ...) which is not a member of the class being sorted (String). i believe by defining some lambda functions, it can be done, but doing so compactly is testing the limits of my java knowledge. happy to have you take a crack and i'll learn. 

(as for safety of the compound String, toString() of Instant returns a proper, fixed-length timestamp (01:01:01, not 1:1:1) that can be compounded safely in this context.)
</blockquote></details>

Closest I came:

    Comparator<String> firstTime =
        (t1, t2) ->
            TestrigMetadataMgr.getTestrigCreationTimeOrMin(containerName, t2)
                .compareTo(TestrigMetadataMgr.getTestrigCreationTimeOrMin(containerName, t1));
    Comparator<String> thenName = firstTime.thenComparing(Comparator.reverseOrder());

Then, use thenName as argument to sort. (IntelliJ complains if I set up the first comparator as an ascending one.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/871)*

**Comment by dhalperi** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, line 1094 at r1](https://reviewable.io:443/reviews/batfish/batfish/871#-L3_AtTYNUTxn1iIp_HZ:-L3cqncwrKYmg-wEmX6y:bqb6hn2) ([raw file](https://github.com/batfish/batfish/blob/d46b3ab176557862adadf68d665b2e8efa1c4bd0/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java#L1094)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

Closest I came:

    Comparator<String> firstTime =
        (t1, t2) ->
            TestrigMetadataMgr.getTestrigCreationTimeOrMin(containerName, t2)
                .compareTo(TestrigMetadataMgr.getTestrigCreationTimeOrMin(containerName, t1));
    Comparator<String> thenName = firstTime.thenComparing(Comparator.reverseOrder());

Then, use thenName as argument to sort. (IntelliJ complains if I set up the first comparator as an ascending one.)
</blockquote></details>

can be handled later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/871)*

**Pull request merged**
