### PR TITLE
arista use new community processing API

### PR DESCRIPTION
**Pull request by arifogel**
- fix standard community grammar
- implement community route-map match and set constructs using new API

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 23 of 23 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6831)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/representation/arista/RouteMapSetCommunityList.java, line 49 at r2](https://reviewable.io/reviews/batfish/batfish/6831#-MXJNLqw0a3316hzft7v:-MXJNLqw0a3316hzft7w:b88z9nn) ([raw file](https://github.com/batfish/batfish/blob/fce6eb1d1d55c65f5966992390dd2ae17ff9abaa/projects/batfish/src/main/java/org/batfish/representation/arista/RouteMapSetCommunityList.java#L49)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>         w.redFlag(
>             "Expected standard community list in route-map set community community-list line "
>                 + "but got expanded instead: \""
>                 + communityListName
>                 + "\"");
> ```
</details>


Tweak message?

`route-map set community community-list is ignored for expanded community list "name"`

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6831)* status: 24 of 25 files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/representation/arista/RouteMapSetCommunityList.java, line 49 at r2](https://reviewable.io/reviews/batfish/batfish/6831#-MXJNLqw0a3316hzft7v:-MXJZh3y6bzavtJmbXyv:bvnrpcm) ([raw file](https://github.com/batfish/batfish/blob/fce6eb1d1d55c65f5966992390dd2ae17ff9abaa/projects/batfish/src/main/java/org/batfish/representation/arista/RouteMapSetCommunityList.java#L49)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
>         w.redFlag(
>             "Expected standard community list in route-map set community community-list line "
>                 + "but got expanded instead: \""
>                 + communityListName
>                 + "\"");
> ```

Tweak message?

`route-map set community community-list is ignored for expanded community list "name"`
</blockquote></details>

updated

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6831)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi)

**Review by dhalperi — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6831#-:-MXJ_gy11QAi8PKzzmm_:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi)

**Pull request merged**
