### PR TITLE
Ipsec policy extraction improvements

### PR DESCRIPTION
**Pull request by haverma**
- Extracting ISAKMP profile from Cisco IPsec Profiles
- Supporting multiple Transform sets in IPsec profiles/policies
[Cisco](https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/security/a1/sec-a1-cr-book/sec-cr-c3.html), [Juniper](https://www.juniper.net/documentation/en_US/junos/topics/task/configuration/services-ipsec-policies-configuring.html)

### CODE REVIEW

**Comment by dhalperi** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpsecPolicy.java, line 34 at r2](https://reviewable.io/reviews/batfish/batfish/1590#-LEGRfY70AIbDgT5r6Tb:-LEGRfY70AIbDgT5r6Tc:b3gdbtm) ([raw file](https://github.com/batfish/batfish/blob/9d75b9d243c905de042ba1d960b38ddc444191a4/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpsecPolicy.java#L34)):*
> ```Java
>   public IpsecPolicy(@JsonProperty(PROP_NAME) String name) {
>     super(name);
>     _proposals = new LinkedHashMap<>();
> ```

explain why this is important? Document in the private type?

---

*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 7922 at r2](https://reviewable.io/reviews/batfish/batfish/1590#-LEGS7_B38cuud7MZFKa:-LEGS7_B38cuud7MZFKb:by0akc1) ([raw file](https://github.com/batfish/batfish/blob/9d75b9d243c905de042ba1d960b38ddc444191a4/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L7922)):*
> ```
>     } else if (ctx.GROUP1() != null) {
>       return DiffieHellmanGroup.GROUP1;
> ```

redundant?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1590#-:-LEGTOK342NTmL_CbDBC:bnfp4nl)*

**Comment by haverma** [comment]
Review status: 16 of 18 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpsecPolicy.java, line 34 at r2](https://reviewable.io/reviews/batfish/batfish/1590#-LEGRfY70AIbDgT5r6Tb:-LEGjbDz8_IeGUTVWsKq:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/9d75b9d243c905de042ba1d960b38ddc444191a4/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpsecPolicy.java#L34)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

explain why this is important? Document in the private type?
</blockquote></details>

done

---

*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 7922 at r2](https://reviewable.io/reviews/batfish/batfish/1590#-LEGS7_B38cuud7MZFKa:-LEGkUMl27d7EqmpLxGH:b-hfpv0l) ([raw file](https://github.com/batfish/batfish/blob/9d75b9d243c905de042ba1d960b38ddc444191a4/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L7922)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
>     } else if (ctx.GROUP1() != null) {
>       return DiffieHellmanGroup.GROUP1;
> ```

redundant?
</blockquote></details>

removed

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1590)*

**Comment by dhalperi** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpsecPolicy.java, line 30 at r3](https://reviewable.io/reviews/batfish/batfish/1590#-LEGqjlyCXU_OAxQVML4:-LEGqjlyCXU_OAxQVML5:b3x0um1) ([raw file](https://github.com/batfish/batfish/blob/da01672d90c1d235b9f354b0166ead06245a4e03/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpsecPolicy.java#L30)):*
> ```
>   private Map<String, IpsecProposal>
>       _proposals; /* Ipsec proposals are applied in the order they are specified */
>  
> ```

normally this is would be an implementation comment, something like

```
// Use LinkedHashMap to keep insertion order, since IPSEC proposals are applied in the order they are specified
private LinkedHashMap<String, IpsecProposal> _proposals;
```

Btw, does this need to be a `Map` at all? Can it be a `List<IpecProposal>` instead?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1590)*

**Comment by haverma** [comment]
Review status: 11 of 23 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpsecPolicy.java, line 30 at r3](https://reviewable.io/reviews/batfish/batfish/1590#-LEGqjlyCXU_OAxQVML4:-LEHEmrA1PJFASEhYurs:b-b7mb3m) ([raw file](https://github.com/batfish/batfish/blob/da01672d90c1d235b9f354b0166ead06245a4e03/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpsecPolicy.java#L30)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
>   private Map<String, IpsecProposal>
>       _proposals; /* Ipsec proposals are applied in the order they are specified */
>  
> ```

normally this is would be an implementation comment, something like

```
// Use LinkedHashMap to keep insertion order, since IPSEC proposals are applied in the order they are specified
private LinkedHashMap<String, IpsecProposal> _proposals;
```

Btw, does this need to be a `Map` at all? Can it be a `List<IpecProposal>` instead?
</blockquote></details>

moved the comment

Yes, using `Map` is redundant for this.  I followed the pattern from `Configuration` class where everything is represented as a `Map`. Also I wanted to minimize the changes to the data model. But the suggestion makes sense, replaced with a `List`

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1590)*

**Comment by dhalperi** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java, line 1736 at r4](https://reviewable.io/reviews/batfish/batfish/1590#-LEHIV90ACcyKbyogBzf:-LEHIV90ACcyKbyogBzg:b2x07ya) ([raw file](https://github.com/batfish/batfish/blob/43e4ca9875981429b6877daa8ff774b1809088ac/projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java#L1736)):*
> ```
> containsInAnyOrder
> ```

should this be in any order? Since order is important, shouldn't it be in the specific order?

Maybe just `equalTo`?

---

*[projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java, line 1270 at r4](https://reviewable.io/reviews/batfish/batfish/1590#-LEHIc3K3TQ5nUv5x823:-LEHIc3K3TQ5nUv5x824:b-bx4fjw) ([raw file](https://github.com/batfish/batfish/blob/43e4ca9875981429b6877daa8ff774b1809088ac/projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java#L1270)):*
> ```Java
>             allOf(
>                 IpsecPolicyMatchers.hasIpsecProposals(
>                     containsInAnyOrder(
> ```

same comment.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1590)*

**Comment by haverma** [comment]
Review status: 21 of 23 files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java, line 1736 at r4](https://reviewable.io/reviews/batfish/batfish/1590#-LEHIV90ACcyKbyogBzf:-LEHQLgS2bE0BRmZcZXJ:bq15me2) ([raw file](https://github.com/batfish/batfish/blob/43e4ca9875981429b6877daa8ff774b1809088ac/projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java#L1736)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> containsInAnyOrder
> ```

should this be in any order? Since order is important, shouldn't it be in the specific order?

Maybe just `equalTo`?
</blockquote></details>

thanks for catching that, `containsInAnyOrder` was not suitable. `equalTo()` was not working so used `contains()`

---

*[projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java, line 1270 at r4](https://reviewable.io/reviews/batfish/batfish/1590#-LEHIc3K3TQ5nUv5x823:-LEHQvAYB_JpoQ1ogxDd:b-n9tkhd) ([raw file](https://github.com/batfish/batfish/blob/43e4ca9875981429b6877daa8ff774b1809088ac/projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java#L1270)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

same comment.
</blockquote></details>

changed

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1590)*

**Pull request merged**
