### PR TITLE
Compute HMM routes from IPs of HMM-enabled interfaces' neighbors

### PR DESCRIPTION
**Pull request by arifogel**

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 10 of 13 files at r1, 3 of 3 files at r2, 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7920)* status: 19 of 26 files reviewed, 1 unresolved discussion (waiting on @arifogel)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7920#-Mt5tu9LEH_h_rIzzzdL:-Mt5tu9M3X-aPT4DOoAx:bkpqiuj) (no related file):*
After batfish/batfish#7919

---

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7920)* status: 0 of 26 files reviewed, all discussions resolved (waiting on @arifogel, @corinaminer, and @dhalperi)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7920#-Mt5tu9LEH_h_rIzzzdL:-Mt9mFWoADTv_OUJvkJr:b-50r159) (no related file):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

After batfish/batfish#7919
</blockquote></details>

Ready for review. Rebased, so initial review should be between base and r6.

---

**Review by dhalperi — COMMENTED** [review]
> Reviewed 5 of 7 files at r4, 1 of 1 files at r5, 1 of 20 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7920)* status: 7 of 26 files reviewed, all discussions resolved (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java, line 385 at r6](https://reviewable.io/reviews/batfish/batfish/7920#-Mt9sL_21RpwOBN1ceyI:-Mt9sL_35BOz76TVRMZ_:bpafcg0) ([raw file](https://github.com/batfish/batfish/blob/cd06460983a54941164f801a2f72e3293e13839a/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java#L385)):*
> ```Java
>                         ip ->
>                             HmmRoute.builder()
>                                 .setNetwork(Prefix.create(ip, Prefix.MAX_PREFIX_LENGTH))
> ```

fyi `ip.toPrefix()` exists



_Code quote:_
```Java
Prefix.create(ip, Prefix.MAX_PREFIX_LENGTH)
```

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7920)* status: 6 of 26 files reviewed, all discussions resolved (waiting on @arifogel, @corinaminer, and @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java, line 385 at r6](https://reviewable.io/reviews/batfish/batfish/7920#-Mt9sL_21RpwOBN1ceyI:-Mt9tpqK98Zhi1L7IGX-:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/cd06460983a54941164f801a2f72e3293e13839a/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java#L385)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

fyi `ip.toPrefix()` exists
</blockquote></details>

done

**Review by arifogel — COMMENTED** [review]
> Reviewed 19 of 20 files at r6.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7920)* status: 12 of 26 files reviewed, all discussions resolved (waiting on @arifogel, @corinaminer, and @dhalperi)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 14 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7920)* status: 13 of 26 files reviewed, all discussions resolved (waiting on @arifogel and @corinaminer)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 13 of 14 files at r7.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7920)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

**Review by arifogel — COMMENTED** [review]
> Reviewed 2 of 7 files at r4, 1 of 14 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7920)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

**Pull request merged**
