### PR TITLE
VendorConfigurationFormatDetection: stop falling back to NXOS

### PR DESCRIPTION
**Pull request by dhalperi**
CiscoParser is too eager to fallback to NX, when in reality NX has a nice classifier that
usually works -- it's nearly impossible to have a useful config without any feature line.

Instead, fixup the feature detection for NXOS and then always fallback to IOS for Cisco-like files.

### CODE REVIEW

**Comment by dhalperi** [comment]
@arifogel  -- let's chat about what else should be done in this PR to be satisfied with result.

(I'm assuming some more refs will fail... we'll see)

**Comment by arifogel** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[test_rigs/parsing-tests/unit-tests-nodes.ref, line 13421 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1220#-LAok75e4qHetaFN75KQ:-LAok75e4qHetaFN75KR:bbxg8jr) ([raw file](https://github.com/batfish/batfish/blob/41092ce6595fcad6c945ffc6c549600a3f8ea4c3/test_rigs/parsing-tests/unit-tests-nodes.ref#L13421)):*
> ```
>             ]
>           },
>           "~BGP_PEER_EXPORT_POLICY:default:1:1:0:0:0:0:0:0~" : {
> ```

What happened here?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1220)*

**Comment by dhalperi** [comment]
Review status: 13 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[test_rigs/parsing-tests/unit-tests-nodes.ref, line 13421 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1220#-LAok75e4qHetaFN75KQ:-LAomeYr0cj81iFSv33B:bhbj9ro) ([raw file](https://github.com/batfish/batfish/blob/41092ce6595fcad6c945ffc6c549600a3f8ea4c3/test_rigs/parsing-tests/unit-tests-nodes.ref#L13421)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

What happened here?
</blockquote></details>

Some behavior difference between IOS and NX.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1220)*

**Comment by arifogel** [comment]
Review status: 13 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[test_rigs/parsing-tests/unit-tests-nodes.ref, line 13421 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1220#-LAok75e4qHetaFN75KQ:-LAooQxY03XrVb6E8pZZ:b9xsx2x) ([raw file](https://github.com/batfish/batfish/blob/41092ce6595fcad6c945ffc6c549600a3f8ea4c3/test_rigs/parsing-tests/unit-tests-nodes.ref#L13421)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Some behavior difference between IOS and NX.
</blockquote></details>

Is the peer disabled? I don't see any such change. Can you help me understand why these policies only exist in on NXOS?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1220)*

**Comment by dhalperi** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1220)*

**Comment by arifogel** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1220#-:-LAowzIMBqAIrgan13cU:bnfp4nl)*

**Pull request merged**
