### PR TITLE
remove unused/unnecessary code

### PR DESCRIPTION
**Pull request by arifogel**
(low priority, can be split or dropped if necessary)
- remove unnecessary suppress-unused annotation
- remove unused private methods

### CODE REVIEW

**Comment by dhalperi** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed, 1 unresolved discussion (waiting on @arifogel, @corinaminer, and @ratulm)

---

*[projects/batfish/src/test/java/org/batfish/dataplane/ibdp/IsisTest.java, line 298 at r1](https://reviewable.io/reviews/batfish/batfish/1762#-LFxf1Z3Dtf-hg0m5Z4D:-LFxf1Z3Dtf-hg0m5Z4E:b-rtagwg) ([raw file](https://github.com/batfish/batfish/blob/2c21fec036f0e15c3425d5e7a2380b0e68cfd47c/projects/batfish/src/test/java/org/batfish/dataplane/ibdp/IsisTest.java#L298)):*
> ```Java
> 
>   @SuppressWarnings("unused")
>   private static void assertInterAreaRoute(
> ```

delete

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1762)*

**Comment by arifogel** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @arifogel, @corinaminer, and @ratulm)

---

*[projects/batfish/src/test/java/org/batfish/dataplane/ibdp/IsisTest.java, line 298 at r1](https://reviewable.io/reviews/batfish/batfish/1762#-LFxf1Z3Dtf-hg0m5Z4D:-LFxoIQS8rBlBETQyifu:b-daszsa) ([raw file](https://github.com/batfish/batfish/blob/2c21fec036f0e15c3425d5e7a2380b0e68cfd47c/projects/batfish/src/test/java/org/batfish/dataplane/ibdp/IsisTest.java#L298)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

delete
</blockquote></details>

Should I also delete the commented code calling it? I suppose I can just recover it via git history when the referenced issue is tackled.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1762)*

**Comment by dhalperi** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi, @corinaminer, and @ratulm)

---

*[projects/batfish/src/test/java/org/batfish/dataplane/ibdp/IsisTest.java, line 298 at r1](https://reviewable.io/reviews/batfish/batfish/1762#-LFxf1Z3Dtf-hg0m5Z4D:-LFyU9u45A-7Su4OgOUy:b9vzfa3) ([raw file](https://github.com/batfish/batfish/blob/2c21fec036f0e15c3425d5e7a2380b0e68cfd47c/projects/batfish/src/test/java/org/batfish/dataplane/ibdp/IsisTest.java#L298)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Should I also delete the commented code calling it? I suppose I can just recover it via git history when the referenced issue is tackled.
</blockquote></details>

The way to implement what I think you're aiming for here is to not comment out the code.

A typical solution would be to put the code in a running, but `@Ignore`d test with a link to the github issue.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1762)*

**Comment by arifogel** [comment]
Review status: 5 of 6 files reviewed, all discussions resolved (waiting on @dhalperi, @corinaminer, and @ratulm)

---

*[projects/batfish/src/test/java/org/batfish/dataplane/ibdp/IsisTest.java, line 298 at r1](https://reviewable.io/reviews/batfish/batfish/1762#-LFxf1Z3Dtf-hg0m5Z4D:-LG1PFyJ22VDnV2jw-4N:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/2c21fec036f0e15c3425d5e7a2380b0e68cfd47c/projects/batfish/src/test/java/org/batfish/dataplane/ibdp/IsisTest.java#L298)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

The way to implement what I think you're aiming for here is to not comment out the code.

A typical solution would be to put the code in a running, but `@Ignore`d test with a link to the github issue.
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1762)*

**Comment by dhalperi** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed, 1 unresolved discussion (waiting on @arifogel, @corinaminer, and @ratulm)

---

*[projects/batfish/src/test/java/org/batfish/dataplane/ibdp/IsisTest.java, line 304 at r2](https://reviewable.io/reviews/batfish/batfish/1762#-LG1RF5N-TX_BDc-YxEi:-LG1RF5N-TX_BDc-YxEj:b25990g) ([raw file](https://github.com/batfish/batfish/blob/24ccd21df8e1e4ba3368034a9862e1e5aad981a2/projects/batfish/src/test/java/org/batfish/dataplane/ibdp/IsisTest.java#L304)):*
> ```Java
> 
>   /* TODO: https://github.com/batfish/batfish/issues/1703 */
>   @Ignore
> ```

See https://docs.google.com/document/d/1WbM0me-hmJuxVhUEU0ewlV8MlQMSfu-75A-dKFMsX-Y/edit?ts=5b2d9868#heading=h.fyk671yl7qc1 for minor improvement. Basically, you can put the link in the issue value, and it will be surfaced by some tools etc.

Otherwise, LGTM.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1762#-:-LG1RQtCEvyuk9QyfZ0W:bnfp4nl)*

**Comment by dhalperi** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1762)*

**Pull request merged**
