### PR TITLE
PAN: fix application and service references outside current `vsys`

### PR DESCRIPTION
**Pull request by sfraint**
* Update security rule conversion to permit references to shared and panorama applications and services
* Split up panorama and shared objects in VS representation (rather than putting all objects in panorama)
* Change ordering of shared and panorama data in many places to prefer panorama
  * (Not really an issue until this PR split panorama and shared objects)

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7682)* status: all files reviewed, 11 unresolved discussions (waiting on @corinaminer and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/ApplicationOrApplicationGroupReference.java, line 5 at r1](https://reviewable.io/reviews/batfish/batfish/7682#-MoVWacjCoRIiirCRuC9:-MoVWacjCoRIiirCRuCA:by408d5) ([raw file](https://github.com/batfish/batfish/blob/e93e4cb192fe6bec84116f22c9312f8a5acc1f83/projects/batfish/src/main/java/org/batfish/representation/palo_alto/ApplicationOrApplicationGroupReference.java#L5)):*
> ```Java
> import javax.annotation.Nonnull;
> 
> /** Datamodel class that represents a reference to an applicaiton or an applicaiton-group. */
> ```

nit: typo twice: `applicaiton`. And suggest wrapping vendor text in `{@code ...}`, i.e. `{@code application}` and `{@code application-group}`.
Also, nit: `final`
___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/ApplicationOrApplicationGroupReference.java, line 18 at r1](https://reviewable.io/reviews/batfish/batfish/7682#-MoVWxYQ0yWfe22tTR_d:-MoVWxYQ0yWfe22tTR_e:bhrvtke) ([raw file](https://github.com/batfish/batfish/blob/e93e4cb192fe6bec84116f22c9312f8a5acc1f83/projects/batfish/src/main/java/org/batfish/representation/palo_alto/ApplicationOrApplicationGroupReference.java#L18)):*
> ```Java
> 
>   @Override
>   public int compareTo(@Nonnull ApplicationOrApplicationGroupReference o) {
> ```

You must override `equals` and `hashCode` to be consistent with `compareTo` when implementing `compareTo`.

Also nit: redundant `@Nonnull` because of `package-info.java`
___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/ApplicationOrApplicationGroupReference.java, line 24 at r1](https://reviewable.io/reviews/batfish/batfish/7682#-MoVX2gV2cGaEelvWw4m:-MoVX2gV2cGaEelvWw4n:b-91ahd9) ([raw file](https://github.com/batfish/batfish/blob/e93e4cb192fe6bec84116f22c9312f8a5acc1f83/projects/batfish/src/main/java/org/batfish/representation/palo_alto/ApplicationOrApplicationGroupReference.java#L24)):*
> ```Java
>   /** Return the name of the referenced Application or ApplicationGroup */
>   @Override
>   public String getName() {
> ```

nit: `@Nonnull` here and field.
___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java, line 1667 at r1](https://reviewable.io/reviews/batfish/batfish/7682#-MoVXTIGCKa5hGN6UX5m:-MoVXTIGCKa5hGN6UX5n:b-3frpj6) ([raw file](https://github.com/batfish/batfish/blob/e93e4cb192fe6bec84116f22c9312f8a5acc1f83/projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java#L1667)):*
> ```Java
>       }
>       // If the reference is contained by a vsys, should match an application or group above
>       assert false;
> ```

This is weird. Just `assert a != null` above the return statement, and ditch the `if`.
___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java, line 1779 at r1](https://reviewable.io/reviews/batfish/batfish/7682#-MoVYSsw2Jx_fG1CgyfE:-MoVYSsx8Wm8nAKUaD3Q:b-1kkrln) ([raw file](https://github.com/batfish/batfish/blob/e93e4cb192fe6bec84116f22c9312f8a5acc1f83/projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java#L1779)):*
> ```Java
>         }
>         // fall-through
>       default:
> ```

Nit: since there are only three enum values, could you just replace `default` with `SHARED`? Or put `SHARED` above `default` to make it clear that case was considered?
Or perhaps an assert if that is appropriate? It's hard to understand from here what is supposed to happen when the namespace type is `SHARED`.

Also, is there a way to factor out this pattern? Seems error-prone to duplicate as you have done.
___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java, line 2884 at r1](https://reviewable.io/reviews/batfish/batfish/7682#-MoV_ZFs-qF3JRYfdIaC:-MoV_4Pj0GN_gv18hasP:b-wacnpc) ([raw file](https://github.com/batfish/batfish/blob/e93e4cb192fe6bec84116f22c9312f8a5acc1f83/projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java#L2884)):*
> ```Java
> 
>     // Create the target vsyses (shouldn't already exist)
>     Vsys target = new Vsys(PANORAMA_VSYS_NAME, NamespaceType.PANORAMA);
> ```

Seems like `target` is only ever `_panorama`. So why the local variable? If you are going to keep it, call it `targetPanorama` for consistency with `targetShared`.
___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/Reference.java, line 12 at r1](https://reviewable.io/reviews/batfish/batfish/7682#-MoV_kd1Cak9Vouv_769:-MoV_kd1Cak9Vouv_76A:bnu71qm) ([raw file](https://github.com/batfish/batfish/blob/e93e4cb192fe6bec84116f22c9312f8a5acc1f83/projects/batfish/src/main/java/org/batfish/representation/palo_alto/Reference.java#L12)):*
> ```Java
>   <T, U> T accept(ReferenceVisitor<T, U> visitor, U arg);
> 
>   String getName();
> ```

`@Nonnull`?
___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/ReferenceVisitor.java, line 3 at r1](https://reviewable.io/reviews/batfish/batfish/7682#-MoV_rAq2tfvfv_5AiY2:-MoV_rAq2tfvfv_5AiY3:b-svqlv9) ([raw file](https://github.com/batfish/batfish/blob/e93e4cb192fe6bec84116f22c9312f8a5acc1f83/projects/batfish/src/main/java/org/batfish/representation/palo_alto/ReferenceVisitor.java#L3)):*
> ```Java
> package org.batfish.representation.palo_alto;
> 
> /** Visitor for {@link Reference} that takes in an argument. */
> ```

nit: Better to be explicit about both generic args in javadoc for a generic: `takes a generic argument of type {@code U} and returns a generic value of type {@code T}.`
Yes I know we haven't been great about this in the past.
___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/SecurityRule.java, line 90 at r1](https://reviewable.io/reviews/batfish/batfish/7682#-MoVbJ2m-OBdTTRv4_Cl:-MoVbJ2m-OBdTTRv4_Cm:b-2bsrdz) ([raw file](https://github.com/batfish/batfish/blob/e93e4cb192fe6bec84116f22c9312f8a5acc1f83/projects/batfish/src/main/java/org/batfish/representation/palo_alto/SecurityRule.java#L90)):*
> ```Java
> 
>   @Nonnull
>   public SortedSet<ApplicationOrApplicationGroupReference> getApplications() {
> ```

Just to confirm: sorting is important for correctness, right?
___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/ServiceOrServiceGroupReference.java, line 19 at r1](https://reviewable.io/reviews/batfish/batfish/7682#-MoVbSR727N20tEybhab:-MoVbSR727N20tEybhac:bpsiwsg) ([raw file](https://github.com/batfish/batfish/blob/e93e4cb192fe6bec84116f22c9312f8a5acc1f83/projects/batfish/src/main/java/org/batfish/representation/palo_alto/ServiceOrServiceGroupReference.java#L19)):*
> ```Java
> 
>   @Override
>   public int compareTo(@Nonnull ServiceOrServiceGroupReference o) {
> ```

need equals and hashCode
___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/ServiceOrServiceGroupReference.java, line 54 at r1](https://reviewable.io/reviews/batfish/batfish/7682#-MoVbW9H3HRwLfKTh1aQ:-MoVbW9H3HRwLfKTh1aR:b55fcfa) ([raw file](https://github.com/batfish/batfish/blob/e93e4cb192fe6bec84116f22c9312f8a5acc1f83/projects/batfish/src/main/java/org/batfish/representation/palo_alto/ServiceOrServiceGroupReference.java#L54)):*
> ```Java
>   }
> 
>   private final String _name;
> ```

nit: `@Nonnull`

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7682)* status: 6 of 11 files reviewed, 6 unresolved discussions (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/ApplicationOrApplicationGroupReference.java, line 18 at r1](https://reviewable.io/reviews/batfish/batfish/7682#-MoVWxYQ0yWfe22tTR_d:-Mo_mCK2Eim8yP67zk6j:b-3c179h) ([raw file](https://github.com/batfish/batfish/blob/e93e4cb192fe6bec84116f22c9312f8a5acc1f83/projects/batfish/src/main/java/org/batfish/representation/palo_alto/ApplicationOrApplicationGroupReference.java#L18)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

You must override `equals` and `hashCode` to be consistent with `compareTo` when implementing `compareTo`.

Also nit: redundant `@Nonnull` because of `package-info.java`
</blockquote></details>

Fixed (and fixed the place it was copied from)
___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java, line 1667 at r1](https://reviewable.io/reviews/batfish/batfish/7682#-MoVXTIGCKa5hGN6UX5m:-Mo_nBUbB6WyQK8CMF-C:bso8x5t) ([raw file](https://github.com/batfish/batfish/blob/e93e4cb192fe6bec84116f22c9312f8a5acc1f83/projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java#L1667)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

This is weird. Just `assert a != null` above the return statement, and ditch the `if`.
</blockquote></details>

yep, fixed
___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java, line 1779 at r1](https://reviewable.io/reviews/batfish/batfish/7682#-MoVYSsw2Jx_fG1CgyfE:-Mo_p4pN2APMpArDlS_j:b-69swz5) ([raw file](https://github.com/batfish/batfish/blob/e93e4cb192fe6bec84116f22c9312f8a5acc1f83/projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java#L1779)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Nit: since there are only three enum values, could you just replace `default` with `SHARED`? Or put `SHARED` above `default` to make it clear that case was considered?
Or perhaps an assert if that is appropriate? It's hard to understand from here what is supposed to happen when the namespace type is `SHARED`.

Also, is there a way to factor out this pattern? Seems error-prone to duplicate as you have done.
</blockquote></details>

Updated. I'd like to migrate more copies of this logic to use the new code, but it's mostly beyond the scope of this PR.

Also, the general intent with adding the visitor pattern here was to make it easier to get rid of the duplicate logic going forward.
___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java, line 2884 at r1](https://reviewable.io/reviews/batfish/batfish/7682#-MoV_ZFs-qF3JRYfdIaC:-Mo_piqT3nr1N6VhnIPq:b-8yv0a) ([raw file](https://github.com/batfish/batfish/blob/e93e4cb192fe6bec84116f22c9312f8a5acc1f83/projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java#L2884)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Seems like `target` is only ever `_panorama`. So why the local variable? If you are going to keep it, call it `targetPanorama` for consistency with `targetShared`.
</blockquote></details>

cleaned up a bit
___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/ReferenceVisitor.java, line 3 at r1](https://reviewable.io/reviews/batfish/batfish/7682#-MoV_rAq2tfvfv_5AiY2:-Mo_ptt56gQpwx0XbEeU:bvnrpcm) ([raw file](https://github.com/batfish/batfish/blob/e93e4cb192fe6bec84116f22c9312f8a5acc1f83/projects/batfish/src/main/java/org/batfish/representation/palo_alto/ReferenceVisitor.java#L3)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

nit: Better to be explicit about both generic args in javadoc for a generic: `takes a generic argument of type {@code U} and returns a generic value of type {@code T}.`
Yes I know we haven't been great about this in the past.
</blockquote></details>

updated
___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/SecurityRule.java, line 90 at r1](https://reviewable.io/reviews/batfish/batfish/7682#-MoVbJ2m-OBdTTRv4_Cl:-Mo_pvZA83MlqBDrXQWO:b-wvt5qs) ([raw file](https://github.com/batfish/batfish/blob/e93e4cb192fe6bec84116f22c9312f8a5acc1f83/projects/batfish/src/main/java/org/batfish/representation/palo_alto/SecurityRule.java#L90)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Just to confirm: sorting is important for correctness, right?
</blockquote></details>

not really, sorting is just useful for preserving the user-specified order

**Review by arifogel — COMMENTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7682)* status: all files reviewed, 1 unresolved discussion (waiting on @corinaminer and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/SecurityRule.java, line 90 at r1](https://reviewable.io/reviews/batfish/batfish/7682#-MoVbJ2m-OBdTTRv4_Cl:-Mo_y40Z3LrwJGfjkxV9:b-h159g3) ([raw file](https://github.com/batfish/batfish/blob/e93e4cb192fe6bec84116f22c9312f8a5acc1f83/projects/batfish/src/main/java/org/batfish/representation/palo_alto/SecurityRule.java#L90)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

not really, sorting is just useful for preserving the user-specified order
</blockquote></details>

Sorting explicitly does _not_ preserve the user-specified order.

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7682)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/SecurityRule.java, line 90 at r1](https://reviewable.io/reviews/batfish/batfish/7682#-MoVbJ2m-OBdTTRv4_Cl:-MoaDwM-10DlkGvspfdJ:b-13tbbn) ([raw file](https://github.com/batfish/batfish/blob/e93e4cb192fe6bec84116f22c9312f8a5acc1f83/projects/batfish/src/main/java/org/batfish/representation/palo_alto/SecurityRule.java#L90)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Sorting explicitly does _not_ preserve the user-specified order.
</blockquote></details>

Yeah, never mind - sorting here only seems to be for predictable ordering, which I don't think really matters.

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7682)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/SecurityRule.java, line 90 at r1](https://reviewable.io/reviews/batfish/batfish/7682#-MoVbJ2m-OBdTTRv4_Cl:-MoaE5VD5K0kMmHOwByi:b-syxt7k) ([raw file](https://github.com/batfish/batfish/blob/e93e4cb192fe6bec84116f22c9312f8a5acc1f83/projects/batfish/src/main/java/org/batfish/representation/palo_alto/SecurityRule.java#L90)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

Yeah, never mind - sorting here only seems to be for predictable ordering, which I don't think really matters.
</blockquote></details>

(I though we were using LinkedHashSet or w/e)

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7682)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/SecurityRule.java, line 90 at r1](https://reviewable.io/reviews/batfish/batfish/7682#-MoVbJ2m-OBdTTRv4_Cl:-MoaJGu9Cct6f3dKOjM4:b-rujljd) ([raw file](https://github.com/batfish/batfish/blob/e93e4cb192fe6bec84116f22c9312f8a5acc1f83/projects/batfish/src/main/java/org/batfish/representation/palo_alto/SecurityRule.java#L90)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

(I though we were using LinkedHashSet or w/e)
</blockquote></details>

Fine as is.

**Pull request merged**
