### PR TITLE
Connecting the Worker service runTask API to the trace of the client and the coordinator

### PR DESCRIPTION
**Pull request by haverma**
1.) Updating workItem to pass on the spancontext between different threads
2.) Currently using a child_of relationships for all spawned threads, other alternative is follows_from

screen shot 2017-11-22 at 10 00 37 am
screen shot 2017-11-22 at 10 04 33 am

---
This change is [Reviewable](https://reviewable.io/reviews/batfish/batfish/683)

### CODE REVIEW

**Comment by dhalperi** [comment]
Nice work. Lots of questions, but nothing major.

---

Reviewed 2 of 7 files at r1.
Review status: 2 of 7 files reviewed at latest revision, 9 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/WorkItem.java, line 22 at r1](https://reviewable.io:443/reviews/batfish/batfish/683#-Kz_5_nmT3fp-RVGVFkc:-Kz_5_nmT3fp-RVGVFkd:bn2ujbn) ([raw file](https://github.com/batfish/batfish/blob/58648f4a606c6abf71cd7408b7d3b6becd3de555/projects/batfish-common-protocol/src/main/java/org/batfish/common/WorkItem.java#L22)):*
Why create this class instead of a `TextMapInjectAdapter`? The way you're using this class looks like exactly what that adapter is used for.

> A TextMap carrier for use with Tracer.inject() ONLY (it has no read methods).

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/WorkItem.java, line 113 at r1](https://reviewable.io:443/reviews/batfish/batfish/683#-Kz_7kzcoccXpbBwrCSU:-Kz_7kzcoccXpbBwrCSV:b-a4tvwf) ([raw file](https://github.com/batfish/batfish/blob/58648f4a606c6abf71cd7408b7d3b6becd3de555/projects/batfish-common-protocol/src/main/java/org/batfish/common/WorkItem.java#L113)):*
> ```Java
>   }
> 
>   public SpanContext getSourceSpan(Tracer tracer) {
> ```

what's the reason that this takes a `Tracer` instead of just using the `GlobalTracer.get()`?

(not saying it's wrong, just asking).

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/WorkItem.java, line 113 at r1](https://reviewable.io:443/reviews/batfish/batfish/683#-Kz_7s2UjPktopUT-rva:-Kz_7s2UjPktopUT-rvb:b-fw0xs9) ([raw file](https://github.com/batfish/batfish/blob/58648f4a606c6abf71cd7408b7d3b6becd3de555/projects/batfish-common-protocol/src/main/java/org/batfish/common/WorkItem.java#L113)):*
> ```Java
>   }
> 
>   public SpanContext getSourceSpan(Tracer tracer) {
> ```

please document all new member variables and javadoc all new public functions. (In Javadoc, no need to document `@param` but it is good to say what the function does.)

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/WorkItem.java, line 113 at r1](https://reviewable.io:443/reviews/batfish/batfish/683#-Kz_81UGo0Sfv0_ZJgGc:-Kz_81UGo0Sfv0_ZJgGd:b5bqkpv) ([raw file](https://github.com/batfish/batfish/blob/58648f4a606c6abf71cd7408b7d3b6becd3de555/projects/batfish-common-protocol/src/main/java/org/batfish/common/WorkItem.java#L113)):*
> ```Java
>   }
> 
>   public SpanContext getSourceSpan(Tracer tracer) {
> ```

How does this handle the error case when there's no serialized span?

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/WorkItem.java, line 125 at r1](https://reviewable.io:443/reviews/batfish/batfish/683#-Kz_8B3BIZL9B0cortDD:-Kz_8B3BIZL9B0cortDE:b-h69y17) ([raw file](https://github.com/batfish/batfish/blob/58648f4a606c6abf71cd7408b7d3b6becd3de555/projects/batfish-common-protocol/src/main/java/org/batfish/common/WorkItem.java#L125)):*
> ```Java
>   }
> 
>   public void setSourceSpan(Tracer tracer, boolean isRegistered) {
> ```

Why does this take a `Tracer` instead of an `ActiveSpan`, say? Why does this take `isRegistered` instead of calling `GlobalTracer.isRegistered`? Not sure of the API here.

---

*[projects/batfish/src/main/java/org/batfish/main/Driver.java, line 460 at r1](https://reviewable.io:443/reviews/batfish/batfish/683#-Kz_8NKVKQ06X-EpnuAu:-Kz_8NKVKQ06X-EpnuAv:b-vk0nwj) ([raw file](https://github.com/batfish/batfish/blob/58648f4a606c6abf71cd7408b7d3b6becd3de555/projects/batfish/src/main/java/org/batfish/main/Driver.java#L460)):*
> ```Java
>               GlobalTracer.isRegistered()
>                   ? GlobalTracer.get().activeSpan().context()
>                   : NoopActiveSpan.INSTANCE.context();
> ```

just because the global tracer is registered does not mean there's an active span. Why not just build a span for the assign work function?

---

*[projects/batfish/src/main/java/org/batfish/main/Driver.java, line 470 at r1](https://reviewable.io:443/reviews/batfish/batfish/683#-Kz_8UPn_k9khAvH33-s:-Kz_8UPn_k9khAvH33-t:bjvs1lw) ([raw file](https://github.com/batfish/batfish/blob/58648f4a606c6abf71cd7408b7d3b6becd3de555/projects/batfish/src/main/java/org/batfish/main/Driver.java#L470)):*
> ```Java
>                       GlobalTracer.get()
>                           .buildSpan("Run Batfish Service")
>                           .asChildOf(runTaskSpanContext)
> ```

from what I understand the expected relationship for a continuation is not child but follows from.

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, line 141 at r1](https://reviewable.io:443/reviews/batfish/batfish/683#-Kz_8_KOtj-HrDks5GoP:-Kz_8_KOtj-HrDks5GoQ:birpi3m) ([raw file](https://github.com/batfish/batfish/blob/58648f4a606c6abf71cd7408b7d3b6becd3de555/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java#L141)):*
> ```Java
>     try (ActiveSpan assignWorkSpan =
>         GlobalTracer.get().buildSpan("Assign Work").asChildOf(queueWorkSpan).startActive()) {
>       assert assignWorkSpan != null;
> ```

I saw elsewhere that you commented this is to make sure the variable is not unused. Please add that comment here, it's useful :)

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, line 169 at r1](https://reviewable.io:443/reviews/batfish/batfish/683#-Kz_7F6nw757yX7hzM51:-Kz_7F6nw757yX7hzM52:bfvbh2h) ([raw file](https://github.com/batfish/batfish/blob/58648f4a606c6abf71cd7408b7d3b6becd3de555/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java#L169)):*
> ```Java
>               _settings.getSslPoolTruststorePassword());
> 
>       if (GlobalTracer.isRegistered()) {
> ```

Not complaining, but why make this switch?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/683#-:-Kz_8nG1puKVOPwST1M5:b-2bkzt0)*

**Comment by haverma** [comment]
Review status: 1 of 7 files reviewed at latest revision, 9 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/WorkItem.java, line 22 at r1](https://reviewable.io:443/reviews/batfish/batfish/683#-Kz_5_nmT3fp-RVGVFkc:-Kz_Oem0Vu5dA7SD46fp:b-97uptf) ([raw file](https://github.com/batfish/batfish/blob/58648f4a606c6abf71cd7408b7d3b6becd3de555/projects/batfish-common-protocol/src/main/java/org/batfish/common/WorkItem.java#L22)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Why create this class instead of a `TextMapInjectAdapter`? The way you're using this class looks like exactly what that adapter is used for.

> A TextMap carrier for use with Tracer.inject() ONLY (it has no read methods).
</blockquote></details>

you are correct, I don't need this class

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/WorkItem.java, line 113 at r1](https://reviewable.io:443/reviews/batfish/batfish/683#-Kz_7kzcoccXpbBwrCSU:-Kz_NMkty5Aga8F58W4H:b-p0ggmi) ([raw file](https://github.com/batfish/batfish/blob/58648f4a606c6abf71cd7408b7d3b6becd3de555/projects/batfish-common-protocol/src/main/java/org/batfish/common/WorkItem.java#L113)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

what's the reason that this takes a `Tracer` instead of just using the `GlobalTracer.get()`?

(not saying it's wrong, just asking).
</blockquote></details>

WorkItem is a part of batfish-common-protocol and I wanted to keep it independent of where it is getting the tracer instance from, as GlobalTracer.register is called initially in client, worker and coord. Also GlobalTracer is a part of  opentracing-util package, and since workitem will not need a Globaltracer instance anywhere else, I thought it would be redundant to add a dependency on opentracing-util just to get a tracer instance for injection

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/WorkItem.java, line 113 at r1](https://reviewable.io:443/reviews/batfish/batfish/683#-Kz_7s2UjPktopUT-rva:-Kz_YSGlPzEuuhJsCYyx:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/58648f4a606c6abf71cd7408b7d3b6becd3de555/projects/batfish-common-protocol/src/main/java/org/batfish/common/WorkItem.java#L113)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

please document all new member variables and javadoc all new public functions. (In Javadoc, no need to document `@param` but it is good to say what the function does.)
</blockquote></details>

Done.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/WorkItem.java, line 113 at r1](https://reviewable.io:443/reviews/batfish/batfish/683#-Kz_81UGo0Sfv0_ZJgGc:-Kz__v2GbJGO1umpXW8y:b-33ksqo) ([raw file](https://github.com/batfish/batfish/blob/58648f4a606c6abf71cd7408b7d3b6becd3de555/projects/batfish-common-protocol/src/main/java/org/batfish/common/WorkItem.java#L113)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

How does this handle the error case when there's no serialized span?
</blockquote></details>

It returns a null SpanContext, which when used as the parent of any new span will result in the new span creating a new trace entirely

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/WorkItem.java, line 125 at r1](https://reviewable.io:443/reviews/batfish/batfish/683#-Kz_8B3BIZL9B0cortDD:-Kz_YhpvDgzZuNoP2_az:bs70xha) ([raw file](https://github.com/batfish/batfish/blob/58648f4a606c6abf71cd7408b7d3b6becd3de555/projects/batfish-common-protocol/src/main/java/org/batfish/common/WorkItem.java#L125)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Why does this take a `Tracer` instead of an `ActiveSpan`, say? Why does this take `isRegistered` instead of calling `GlobalTracer.isRegistered`? Not sure of the API here.
</blockquote></details>

Because we need a Tracer instance to inject a Span in the carrier(which is a Text Map here)
To separate batfish-common-protocol of any dependency on Tracer as mentioned in the above comment

---

*[projects/batfish/src/main/java/org/batfish/main/Driver.java, line 460 at r1](https://reviewable.io:443/reviews/batfish/batfish/683#-Kz_8NKVKQ06X-EpnuAu:-Kz_br_m4IUQFJoRUCH4:b-nx42r0) ([raw file](https://github.com/batfish/batfish/blob/58648f4a606c6abf71cd7408b7d3b6becd3de555/projects/batfish/src/main/java/org/batfish/main/Driver.java#L460)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

just because the global tracer is registered does not mean there's an active span. Why not just build a span for the assign work function?
</blockquote></details>

Not clear what is meant by this comment:
1. This is part of the Driver class, not assign work function and is called by runTask endpoint api
2. If GlobalTracer  is initialized it will always have an active span as the open-trace jax-rs framework will extract and create a server span when the end point is hit
3. Creating a child will add an unnecessary layer in the trace, logically the RunBafish span should be a direct child of the Run Task span

---

*[projects/batfish/src/main/java/org/batfish/main/Driver.java, line 470 at r1](https://reviewable.io:443/reviews/batfish/batfish/683#-Kz_8UPn_k9khAvH33-s:-Kz_vSDCuJc7A1WY3xWo:bzd0ywf) ([raw file](https://github.com/batfish/batfish/blob/58648f4a606c6abf71cd7408b7d3b6becd3de555/projects/batfish/src/main/java/org/batfish/main/Driver.java#L470)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

from what I understand the expected relationship for a continuation is not child but follows from.
</blockquote></details>

Changed to follows from in both runBatfishThroughService and AssignWork

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, line 141 at r1](https://reviewable.io:443/reviews/batfish/batfish/683#-Kz_8_KOtj-HrDks5GoP:-Kz_xl_JIm7F3ovuTd5P:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/58648f4a606c6abf71cd7408b7d3b6becd3de555/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java#L141)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I saw elsewhere that you commented this is to make sure the variable is not unused. Please add that comment here, it's useful :)
</blockquote></details>

Done.

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, line 169 at r1](https://reviewable.io:443/reviews/batfish/batfish/683#-Kz_7F6nw757yX7hzM51:-Kz_vZrPFQ9anHXG_td_:bb2zaj0) ([raw file](https://github.com/batfish/batfish/blob/58648f4a606c6abf71cd7408b7d3b6becd3de555/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java#L169)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Not complaining, but why make this switch?
</blockquote></details>

I think using the GlobalTracer.isregistered is cleaner and more reliable than using our own flag

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/683)*

**Comment by dhalperi** [comment]
Reviewed 3 of 7 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/WorkItem.java, line 113 at r1](https://reviewable.io:443/reviews/batfish/batfish/683#-Kz_81UGo0Sfv0_ZJgGc:-KzjYKqcknKnper-RyNQ:bwbcn7v) ([raw file](https://github.com/batfish/batfish/blob/58648f4a606c6abf71cd7408b7d3b6becd3de555/projects/batfish-common-protocol/src/main/java/org/batfish/common/WorkItem.java#L113)):*
<details><summary><i>Previously, haverma (Harsh Verma) wrote…</i></summary><blockquote>

It returns a null SpanContext, which when used as the parent of any new span will result in the new span creating a new trace entirely
</blockquote></details>

The documentation for `tracer.extract` says it will throw an exception if the serialized config is wrong.

Also, if this function can return `null` then mark it as `@Nullable`?

http://static.javadoc.io/io.opentracing/opentracing-api/0.30.0/io/opentracing/Tracer.html#extract-io.opentracing.propagation.Format-C-

I think we need some tests of the relevant code with and without active spans.

My biggest concern is that there's crashing when tracing is disable or partially configured. We really don't want an optional feature to hurt the normal use case.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/WorkItem.java, line 125 at r1](https://reviewable.io:443/reviews/batfish/batfish/683#-Kz_8B3BIZL9B0cortDD:-KzjbzWmV6chPstwqaOt:bs0lppi) ([raw file](https://github.com/batfish/batfish/blob/58648f4a606c6abf71cd7408b7d3b6becd3de555/projects/batfish-common-protocol/src/main/java/org/batfish/common/WorkItem.java#L125)):*
<details><summary><i>Previously, haverma (Harsh Verma) wrote…</i></summary><blockquote>

Because we need a Tracer instance to inject a Span in the carrier(which is a Text Map here)
To separate batfish-common-protocol of any dependency on Tracer as mentioned in the above comment
</blockquote></details>

Seems like just taking `Tracer` and ignoring `isRegistered` would be cleaner:

```java
if (tracer.activeSpan() == null) {
    return;
}
tracer.inject...
```

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/WorkItem.java, line 114 at r2](https://reviewable.io:443/reviews/batfish/batfish/683#-KzjZ88fNwBAV0eYd0RQ:-KzjZ88gXOrJ30KFXPLT:b72csiy) ([raw file](https://github.com/batfish/batfish/blob/ce566c4998577c68ef9d4129e9e536ed8543abc6/projects/batfish-common-protocol/src/main/java/org/batfish/common/WorkItem.java#L114)):*
>  Thread}

It's the current Tracer, not the current Thread, right?

---

*[projects/batfish/src/main/java/org/batfish/main/Driver.java, line 460 at r2](https://reviewable.io:443/reviews/batfish/batfish/683#-Kzjd2QQJsNPk3iZX_8K:-Kzjd2QQJsNPk3iZX_8L:bbwn6ev) ([raw file](https://github.com/batfish/batfish/blob/ce566c4998577c68ef9d4129e9e536ed8543abc6/projects/batfish/src/main/java/org/batfish/main/Driver.java#L460)):*
> ```Java
>               GlobalTracer.isRegistered()
>                   ? GlobalTracer.get().activeSpan().context()
>                   : NoopActiveSpan.INSTANCE.context();
> ```

These uses of Noop* seem unnecessary. Why not something like:

```java
@Nullable SpanContext runTaskSpanContext =
    GlobalTracer.get().activeSpan() == null ? null : GlobalTracer.get().activeSpan().context();
```

Note that `addReference(References.FOLLOWS_FROM, null)` is documented to be a no-op.

---

*[projects/batfish/src/main/java/org/batfish/main/Driver.java, line 470 at r2](https://reviewable.io:443/reviews/batfish/batfish/683#-Kzjcf_PuPNVjxNil3fB:-Kzjcf_PuPNVjxNil3fC:b6ufmdx) ([raw file](https://github.com/batfish/batfish/blob/ce566c4998577c68ef9d4129e9e536ed8543abc6/projects/batfish/src/main/java/org/batfish/main/Driver.java#L470)):*
> ```Java
>                       GlobalTracer.get()
>                           .buildSpan("Run Batfish Service")
>                           .addReference("follows_from", runTaskSpanContext)
> ```

Use the existing string constant `References.FOLLOWS_FROM` rather than inlining the string.

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, line 142 at r2](https://reviewable.io:443/reviews/batfish/batfish/683#-KzjclpE-OIk2kf9YC8e:-KzjclpFpARAYV6PdL-U:b6ufmdx) ([raw file](https://github.com/batfish/batfish/blob/ce566c4998577c68ef9d4129e9e536ed8543abc6/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java#L142)):*
> ```Java
>         GlobalTracer.get()
>             .buildSpan("Assign Work")
>             .addReference("follows_from", queueWorkSpan)
> ```

Use the existing string constant `References.FOLLOWS_FROM` rather than inlining the string.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/683)*

**Comment by haverma** [comment]
1. Added test in WorkItemTest, for Noop tracer and a registered tracer as well, initTracer() function will add 8-9 seconds to travis build
2. Added dependency on opentracing-util in batfish-common-protocol to enable testing, so as a side-effect we can just pass in ActiveSpan and WorkItem can get an instance of tracer using GlobalTracer.get() to use for inject/extract

---

Review status: 1 of 8 files reviewed at latest revision, 6 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/WorkItem.java, line 113 at r1](https://reviewable.io:443/reviews/batfish/batfish/683#-Kz_81UGo0Sfv0_ZJgGc:-L-0qfG393ySABm6fyQF:b6me9jn) ([raw file](https://github.com/batfish/batfish/blob/58648f4a606c6abf71cd7408b7d3b6becd3de555/projects/batfish-common-protocol/src/main/java/org/batfish/common/WorkItem.java#L113)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

The documentation for `tracer.extract` says it will throw an exception if the serialized config is wrong.

Also, if this function can return `null` then mark it as `@Nullable`?

http://static.javadoc.io/io.opentracing/opentracing-api/0.30.0/io/opentracing/Tracer.html#extract-io.opentracing.propagation.Format-C-

I think we need some tests of the relevant code with and without active spans.

My biggest concern is that there's crashing when tracing is disable or partially configured. We really don't want an optional feature to hurt the normal use case.
</blockquote></details>

added tests for WorkItem, 

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/WorkItem.java, line 125 at r1](https://reviewable.io:443/reviews/batfish/batfish/683#-Kz_8B3BIZL9B0cortDD:-L-0pIMXPvkmR5YnHUXp:b-xivw3b) ([raw file](https://github.com/batfish/batfish/blob/58648f4a606c6abf71cd7408b7d3b6becd3de555/projects/batfish-common-protocol/src/main/java/org/batfish/common/WorkItem.java#L125)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Seems like just taking `Tracer` and ignoring `isRegistered` would be cleaner:

```java
if (tracer.activeSpan() == null) {
    return;
}
tracer.inject...
```
</blockquote></details>

Now, it just takes an Active Span

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/WorkItem.java, line 114 at r2](https://reviewable.io:443/reviews/batfish/batfish/683#-KzjZ88fNwBAV0eYd0RQ:-L-0pDeSRsA7ezqXw5mA:bwzhxit) ([raw file](https://github.com/batfish/batfish/blob/ce566c4998577c68ef9d4129e9e536ed8543abc6/projects/batfish-common-protocol/src/main/java/org/batfish/common/WorkItem.java#L114)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

>  Thread}

It's the current Tracer, not the current Thread, right?
</blockquote></details>

Function prototype is now changed

---

*[projects/batfish/src/main/java/org/batfish/main/Driver.java, line 460 at r2](https://reviewable.io:443/reviews/batfish/batfish/683#-Kzjd2QQJsNPk3iZX_8K:-L-0qTCUq_LbjLLVbkoV:b-7rl0kd) ([raw file](https://github.com/batfish/batfish/blob/ce566c4998577c68ef9d4129e9e536ed8543abc6/projects/batfish/src/main/java/org/batfish/main/Driver.java#L460)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

These uses of Noop* seem unnecessary. Why not something like:

```java
@Nullable SpanContext runTaskSpanContext =
    GlobalTracer.get().activeSpan() == null ? null : GlobalTracer.get().activeSpan().context();
```

Note that `addReference(References.FOLLOWS_FROM, null)` is documented to be a no-op.
</blockquote></details>

done

---

*[projects/batfish/src/main/java/org/batfish/main/Driver.java, line 470 at r2](https://reviewable.io:443/reviews/batfish/batfish/683#-Kzjcf_PuPNVjxNil3fB:-L-0qaT4d1rZAfmJbjkk:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/ce566c4998577c68ef9d4129e9e536ed8543abc6/projects/batfish/src/main/java/org/batfish/main/Driver.java#L470)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Use the existing string constant `References.FOLLOWS_FROM` rather than inlining the string.
</blockquote></details>

done

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, line 142 at r2](https://reviewable.io:443/reviews/batfish/batfish/683#-KzjclpE-OIk2kf9YC8e:-L-0qbWk6cnQLkTaYeXq:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/ce566c4998577c68ef9d4129e9e536ed8543abc6/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java#L142)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Use the existing string constant `References.FOLLOWS_FROM` rather than inlining the string.
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/683#-:-L-3T6uspyQodLCvwFjh:b-g2xb0k)*

**Comment by dhalperi** [comment]
Real nice work.

---

Reviewed 1 of 1 files at r3, 6 of 6 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[projects/batfish-common-protocol/pom.xml, line 226 at r4](https://reviewable.io:443/reviews/batfish/batfish/683#-L-3g1i3h5A1-aun5EdH:-L-3g1i3h5A1-aun5EdI:b-7aae07) ([raw file](https://github.com/batfish/batfish/blob/ed71d517678ab50038a7bc8a35b7279705a2e733/projects/batfish-common-protocol/pom.xml#L226)):*
> ```XML
>       <groupId>org.slf4j</groupId>
>       <artifactId>slf4j-jdk14</artifactId>
>       <scope>runtime</scope>
> ```

I believe this should be in the `test` scope, right?

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/common/WorkItemTest.java, line 33 at r4](https://reviewable.io:443/reviews/batfish/batfish/683#-L-3f2vYwP6bGS4sZ3rl:-L-3f2vYwP6bGS4sZ3rm:boc38fb) ([raw file](https://github.com/batfish/batfish/blob/ed71d517678ab50038a7bc8a35b7279705a2e733/projects/batfish-common-protocol/src/test/java/org/batfish/common/WorkItemTest.java#L33)):*
> ```Java
>   public static void initTracer() {
>     _tracer =
>         new Configuration(
> ```

For tests, use a `MockTracer` instead of an actual tracer. This will be much simpler code, have fewer dependencies, and save things like reverse-DNS lookups.

https://github.com/opentracing/opentracing-java/tree/master/opentracing-mock

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/common/WorkItemTest.java, line 93 at r4](https://reviewable.io:443/reviews/batfish/batfish/683#-L-3fuEUbGFlC0Yp6Zd6:-L-3fuEUbGFlC0Yp6Zd7:b-vlhk5a) ([raw file](https://github.com/batfish/batfish/blob/ed71d517678ab50038a7bc8a35b7279705a2e733/projects/batfish-common-protocol/src/test/java/org/batfish/common/WorkItemTest.java#L93)):*
> ```Java
>     // flags)
>     assertEquals(activeSpan.context().toString(), sourceSpan.toString());
>   }
> ```

missing test that `setSourceSpan` can be called with `null`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/683#-:-L-3g5rYGirX4jBpwFZu:b-vdmnux)*

**Comment by haverma** [comment]
Review status: 4 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[projects/batfish-common-protocol/pom.xml, line 226 at r4](https://reviewable.io:443/reviews/batfish/batfish/683#-L-3g1i3h5A1-aun5EdH:-L-59CphitvR1VVdxO9C:bwoodv6) ([raw file](https://github.com/batfish/batfish/blob/ed71d517678ab50038a7bc8a35b7279705a2e733/projects/batfish-common-protocol/pom.xml#L226)):*
> 
Right, changed to test scope

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/common/WorkItemTest.java, line 33 at r4](https://reviewable.io:443/reviews/batfish/batfish/683#-L-3f2vYwP6bGS4sZ3rl:-L-58o3qFDroBCWe221J:bb6un1j) ([raw file](https://github.com/batfish/batfish/blob/ed71d517678ab50038a7bc8a35b7279705a2e733/projects/batfish-common-protocol/src/test/java/org/batfish/common/WorkItemTest.java#L33)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

For tests, use a `MockTracer` instead of an actual tracer. This will be much simpler code, have fewer dependencies, and save things like reverse-DNS lookups.

https://github.com/opentracing/opentracing-java/tree/master/opentracing-mock
</blockquote></details>

Done

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/common/WorkItemTest.java, line 93 at r4](https://reviewable.io:443/reviews/batfish/batfish/683#-L-3fuEUbGFlC0Yp6Zd6:-L-58rj2HPMHviB4wkIj:bb6un1j) ([raw file](https://github.com/batfish/batfish/blob/ed71d517678ab50038a7bc8a35b7279705a2e733/projects/batfish-common-protocol/src/test/java/org/batfish/common/WorkItemTest.java#L93)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

missing test that `setSourceSpan` can be called with `null`.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/683)*

**Comment by haverma** [comment]
Added mock tracer, other changes in unit tests

---

Review status: 4 of 8 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/683#-:-L-7vU0Q5-1cK8epeErF:btip7gh)*

**Comment by dhalperi** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish-common-protocol/pom.xml, line 144 at r4](https://reviewable.io:443/reviews/batfish/batfish/683#-L-7x4M2YZoU6d-FPDP1:-L-7x4M3Hn_RJa12Zuk3:bh5llge) ([raw file](https://github.com/batfish/batfish/blob/ed71d517678ab50038a7bc8a35b7279705a2e733/projects/batfish-common-protocol/pom.xml#L144)):*
> ```XML
>       <groupId>com.uber.jaeger</groupId>
>       <artifactId>jaeger-core</artifactId>
>     </dependency>
> ```

nice to not need this dependency here any more.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/683#-:-L-7xOEkbr_rqsZJ_E2_:bnfp4nl)*

**Pull request merged**
