### PR TITLE
Traceroute pipeline: Pre-NAT routing

### PR DESCRIPTION
**Pull request by corinaminer**
This will be needed to support bidirectional traceroute for IOS devices with NAT, because IOS applies NAT _after_ routing for session-matching flows going from inside to outside.

### CODE REVIEW

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6641)* status: 1 of 40 files reviewed, 3 unresolved discussions (waiting on @corinaminer and @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java, line 973 at r2](https://reviewable.io/reviews/batfish/batfish/6641#-MTw8zAy8Sm2dZPtkXbI:-MTw8zAy8Sm2dZPtkXbJ:byknvz1) ([raw file](https://github.com/batfish/batfish/blob/f572693cd81eec1d72f597c84a64f82de4e94208/projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java#L973)):*
> ```
> _currentFlow = transformationResult.getOutputFlow();
> ```
if we defer updating `_currentFlow` until we add the steps, I expect we can maintain our invariants much more simply
___
*[projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java, line 1035 at r2](https://reviewable.io/reviews/batfish/batfish/6641#-MTw7Z0a3Ku8KLy4oboz:-MTw7Z0a3Ku8KLy4obp-:b-mogbjw) ([raw file](https://github.com/batfish/batfish/blob/f572693cd81eec1d72f597c84a64f82de4e94208/projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java#L1035)):*
> ```
> // TODO Confirm this should only check the post-NAT flow
> ```
Unless we have evidence otherwise, I would assume it would accept based on the pre-nat dst IP, i.e. the one used for the forwarding lookup.

More generally, I'd move the code to apply the transformation into each of these visit methods, to be done at the right place. Queuing up future steps seems really complicated.
___
*[projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java, line 1069 at r2](https://reviewable.io/reviews/batfish/batfish/6641#-MTw8iNG0dJZ7E1cfS58:-MTw8iNH2TqlSi4mUxIr:b-pvgr0l) ([raw file](https://github.com/batfish/batfish/blob/f572693cd81eec1d72f597c84a64f82de4e94208/projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java#L1069)):*
> ```
> transformationSteps
> ```
why not just add the steps in the callback?
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FirewallSessionInterfaceInfo.java, line 30 at r2](https://reviewable.io/reviews/batfish/batfish/6641#-MTw6Jjt3Bk-K_c1TMOb:-MTw6Jjt3Bk-K_c1TMOc:b7nvg48) ([raw file](https://github.com/batfish/batfish/blob/f572693cd81eec1d72f597c84a64f82de4e94208/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FirewallSessionInterfaceInfo.java#L30)):*
> ```
> NO_FIB_LOOKUP
> ```
may be better for the name to reflect what will happen instead of what will not happen

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6641)* status: 0 of 40 files reviewed, 3 unresolved discussions (waiting on @anothermattbrown and @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java, line 973 at r2](https://reviewable.io/reviews/batfish/batfish/6641#-MTw8zAy8Sm2dZPtkXbI:-MTxrYhw35dkycURNU5-:b-yymel) ([raw file](https://github.com/batfish/batfish/blob/f572693cd81eec1d72f597c84a64f82de4e94208/projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java#L973)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

> ```
> _currentFlow = transformationResult.getOutputFlow();
> ```
if we defer updating `_currentFlow` until we add the steps, I expect we can maintain our invariants much more simply
</blockquote></details>

yes, i didn't see it but you're right. done.
___
*[projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java, line 1035 at r2](https://reviewable.io/reviews/batfish/batfish/6641#-MTw7Z0a3Ku8KLy4oboz:-MTxaiXX0x6ueeYMCoD7:b-w2mimo) ([raw file](https://github.com/batfish/batfish/blob/f572693cd81eec1d72f597c84a64f82de4e94208/projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java#L1035)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

> ```
> // TODO Confirm this should only check the post-NAT flow
> ```
Unless we have evidence otherwise, I would assume it would accept based on the pre-nat dst IP, i.e. the one used for the forwarding lookup.

More generally, I'd move the code to apply the transformation into each of these visit methods, to be done at the right place. Queuing up future steps seems really complicated.
</blockquote></details>

Tried a setup in GNS3 with 3 devices like this:
```
[ outside ] ---- [ nat ] ---- [ inside ]
```
`outside` pings `inside`, resulting in a return flow that gets routed before NAT. The twist is, the ping's source IP is owned by `nat`, so the post-NAT return flow could be accepted by `nat`. However, it instead returns to `outside`, so looks like you're correct and the return flow can only be accepted before NAT. (This assumes session-matching flows can be accepted at all.)

And, i did move the code to apply the transformation into the visit methods.
___
*[projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java, line 1069 at r2](https://reviewable.io/reviews/batfish/batfish/6641#-MTw8iNG0dJZ7E1cfS58:-MTxrcCOEmYU_o2271eX:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/f572693cd81eec1d72f597c84a64f82de4e94208/projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java#L1069)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

> ```
> transformationSteps
> ```
why not just add the steps in the callback?
</blockquote></details>

done
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FirewallSessionInterfaceInfo.java, line 30 at r2](https://reviewable.io/reviews/batfish/batfish/6641#-MTw6Jjt3Bk-K_c1TMOb:-MTxhf8i2qQyHhZl2GSj:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/f572693cd81eec1d72f597c84a64f82de4e94208/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/FirewallSessionInterfaceInfo.java#L30)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

> ```
> NO_FIB_LOOKUP
> ```
may be better for the name to reflect what will happen instead of what will not happen
</blockquote></details>

done

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6641)* status: 0 of 40 files reviewed, 3 unresolved discussions (waiting on @anothermattbrown and @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java, line 695 at r3](https://reviewable.io/reviews/batfish/batfish/6641#-MTxs342BcHdKDhMpWP_:-MTxs342BcHdKDhMpWPa:b-fgo5j) ([raw file](https://github.com/batfish/batfish/blob/1aa0c13de8300f9f90ad7820e4df8ce600d46996/projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java#L695)):*
> ```Java
> 
>   /** Check if the packet to {@code dstIp} should be accepted in current VRF. No effect on state. */
>   private boolean isAcceptedAtCurrentVrf(Ip dstIp) {
> ```

Could revert this function to its original behavior, but i think this is generally a better pattern. Can revert if you disagree or just don't want it in this PR.

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 15 of 38 files at r1, 2 of 5 files at r2, 23 of 23 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6641)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java, line 973 at r2](https://reviewable.io/reviews/batfish/batfish/6641#-MTw8zAy8Sm2dZPtkXbI:-MU1XLJp0Y2zR7E-NkMw:b-pu0ej2) ([raw file](https://github.com/batfish/batfish/blob/f572693cd81eec1d72f597c84a64f82de4e94208/projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java#L973)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

yes, i didn't see it but you're right. done.
</blockquote></details>

nice, thanks. I think we can avoid adding the `finalTransformationResult` too by making `transformationResult` itself effectively final.
___
*[projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java, line 695 at r3](https://reviewable.io/reviews/batfish/batfish/6641#-MTxs342BcHdKDhMpWP_:-MU1WwIwEUwe-8sgkJPn:b-ndb6oz) ([raw file](https://github.com/batfish/batfish/blob/1aa0c13de8300f9f90ad7820e4df8ce600d46996/projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java#L695)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Could revert this function to its original behavior, but i think this is generally a better pattern. Can revert if you disagree or just don't want it in this PR.
</blockquote></details>

agreed. I'm ok doing it in this PR.

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6641)* status: 37 of 44 files reviewed, all discussions resolved (waiting on @anothermattbrown and @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java, line 973 at r2](https://reviewable.io/reviews/batfish/batfish/6641#-MTw8zAy8Sm2dZPtkXbI:-MU7HMKzAewX8bFO1olw:bljnj3p) ([raw file](https://github.com/batfish/batfish/blob/f572693cd81eec1d72f597c84a64f82de4e94208/projects/batfish/src/main/java/org/batfish/dataplane/traceroute/FlowTracer.java#L973)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

nice, thanks. I think we can avoid adding the `finalTransformationResult` too by making `transformationResult` itself effectively final.
</blockquote></details>

yep, done

**Review by corinaminer — COMMENTED** [review]
> Reviewed 7 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6641)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dhalperi)

**Pull request merged**
