### PR TITLE
Checkpoint management VS data model

### PR DESCRIPTION
**Pull request by arifogel**
everything needed to deserialize:
- show-packages
  - installation-targets
- show-nat-rulebase
  - objects-dictionary
    - only saves objects representing an address space
- show gateways-and-servers

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
-reviewer:@dhalperi 

> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7249#-:-MhUXom3EwufsTBVVAmS:b26ic4y)* status: 0 of 55 files reviewed, all discussions resolved (waiting on @corinaminer)

**Review by corinaminer — COMMENTED** [review]
> Reviewed 36 of 55 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7249)* status: 36 of 55 files reviewed, 2 unresolved discussions (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/AddressRange.java, line 67 at r1](https://reviewable.io/reviews/batfish/batfish/7249#-MhUWT6j43XjLl7rr0Uq:-MhUWT6j43XjLl7rr0Ur:bglizps) ([raw file](https://github.com/batfish/batfish/blob/50c4afc0460fe72f52f303181b6186c04074d5c1/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/AddressRange.java#L67)):*
> ```Java
>     }
>     AddressRange that = (AddressRange) o;
>     return baseEquals(that)
> ```

not necessary to call `baseEquals` again
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/ListInstallationTargets.java, line 9 at r1](https://reviewable.io/reviews/batfish/batfish/7249#-MhU_i5-5ZPIs1c5gkYS:-MhU_i5-5ZPIs1c5gkYT:br0fqp2) ([raw file](https://github.com/batfish/batfish/blob/50c4afc0460fe72f52f303181b6186c04074d5c1/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/ListInstallationTargets.java#L9)):*
> ```Java
> public final class ListInstallationTargets extends InstallationTargets {
> 
>   ListInstallationTargets(List<GatewayOrServer> installationTargets) {
> ```

JSON creator?

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7249)* status: 36 of 55 files reviewed, 2 unresolved discussions (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/ListInstallationTargets.java, line 9 at r1](https://reviewable.io/reviews/batfish/batfish/7249#-MhU_i5-5ZPIs1c5gkYS:-MhWB4yb2jaNv4wwolSf:b-svt34x) ([raw file](https://github.com/batfish/batfish/blob/50c4afc0460fe72f52f303181b6186c04074d5c1/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/ListInstallationTargets.java#L9)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

JSON creator?
</blockquote></details>

No, because it isn't deserialized directly. See `Package.deserializeInstallationTargets`.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7249)* status: 36 of 55 files reviewed, 2 unresolved discussions (waiting on @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/AddressRange.java, line 67 at r1](https://reviewable.io/reviews/batfish/batfish/7249#-MhUWT6j43XjLl7rr0Uq:-MhWBbi99wxGWdUt2KA_:b-7ql1td) ([raw file](https://github.com/batfish/batfish/blob/50c4afc0460fe72f52f303181b6186c04074d5c1/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/AddressRange.java#L67)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

not necessary to call `baseEquals` again
</blockquote></details>

fixed

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7249)* status: 35 of 55 files reviewed, 2 unresolved discussions (waiting on @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/ListInstallationTargets.java, line 9 at r1](https://reviewable.io/reviews/batfish/batfish/7249#-MhU_i5-5ZPIs1c5gkYS:-MhWBtFf4Wqfs0SyIdO0:b-e4m89h) ([raw file](https://github.com/batfish/batfish/blob/50c4afc0460fe72f52f303181b6186c04074d5c1/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/ListInstallationTargets.java#L9)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

No, because it isn't deserialized directly. See `Package.deserializeInstallationTargets`.
</blockquote></details>

Also note this is covered in `PackageTest.java`

**Review by corinaminer — COMMENTED** [review]
:lgtm:

> Reviewed 19 of 55 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7249#-:-MhZWv8vEOt3QPSxa1TI:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Pull request merged**
