### PR TITLE
PAN: switch to custom insert-order data structure for security rules

### PR DESCRIPTION
**Pull request by progwriter**
* Implement a LinkedHashMap-like Map with extra APIs for reordering keys
* Use it in PAN configuration. Lays groundwork for supporting moving of security rules

### CODE REVIEW

**Review by progwriter — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6355)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @progwriter and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6355#-MKMCdhF8NJCm3QU6h8w:-MKMCdhF8NJCm3QU6h8x:b6feq90) (no related file):*
working on a few more API tweaks

---

**Review by progwriter — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6355)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6355#-MKMCdhF8NJCm3QU6h8w:-MKMOI9B40mVS7C5MrbM:bb7f2mf) (no related file):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

working on a few more API tweaks
</blockquote></details>

done

---

**Review by sfraint — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6355)* status: all files reviewed, 1 unresolved discussion (waiting on @progwriter)

___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/Rulebase.java, line 17 at r2](https://reviewable.io/reviews/batfish/batfish/6355#-MKMigYF4OGiksiYpGEP:-MKMigYF4OGiksiYpGEQ:b15828n) ([raw file](https://github.com/batfish/batfish/blob/7c08465749027129e35b9f1f7ffa4cdbe7df783d/projects/batfish/src/main/java/org/batfish/representation/palo_alto/Rulebase.java#L17)):*
> ```
>     _natRules = new LinkedHashMap<>();
> ```
nat rule change coming separately? or deferred for now?
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/collections/InsertOrderedMap.java, line 63 at r2](https://reviewable.io/reviews/batfish/batfish/6355#-MKMk1U47OhUyR-xS1FS:-MKMk1U47OhUyR-xS1FT:bwza598) ([raw file](https://github.com/batfish/batfish/blob/7c08465749027129e35b9f1f7ffa4cdbe7df783d/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/collections/InsertOrderedMap.java#L63)):*
> ```
> key
> ```
nit: value
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/collections/InsertOrderedMap.java, line 87 at r2](https://reviewable.io/reviews/batfish/batfish/6355#-MKMkBjYCMBzhhqQi67c:-MKMkBjYCMBzhhqQi67d:blglpz4) ([raw file](https://github.com/batfish/batfish/blob/7c08465749027129e35b9f1f7ffa4cdbe7df783d/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/collections/InsertOrderedMap.java#L87)):*
> ```
> key
> ```
nit: `key or value`
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/collections/InsertOrderedMap.java, line 178 at r2](https://reviewable.io/reviews/batfish/batfish/6355#-MKMkXOWA3M1EXQP0lpk:-MKMkXOWA3M1EXQP0lpl:b-huyugz) ([raw file](https://github.com/batfish/batfish/blob/7c08465749027129e35b9f1f7ffa4cdbe7df783d/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/collections/InsertOrderedMap.java#L178)):*
> ```
> prior the the
> ```
nit: to
___
*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/collections/InsertOrderedMapTest.java, line 173 at r2](https://reviewable.io/reviews/batfish/batfish/6355#-MKMmIUMEcYG7fp6o-yw:-MKMmIUMEcYG7fp6o-yx:b22kkb6) ([raw file](https://github.com/batfish/batfish/blob/7c08465749027129e35b9f1f7ffa4cdbe7df783d/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/collections/InsertOrderedMapTest.java#L173)):*
> ```Java
> 
>   @Test(expected = IllegalArgumentException.class)
>   public void testMoveAfterRejectNonExistentKey() {
> ```

what happens/should happen if you move `key` after `key`?

**Review by progwriter — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6355)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/Rulebase.java, line 17 at r2](https://reviewable.io/reviews/batfish/batfish/6355#-MKMigYF4OGiksiYpGEP:-MKMpxSREKjhRx6HCXjp:bxj52ve) ([raw file](https://github.com/batfish/batfish/blob/7c08465749027129e35b9f1f7ffa4cdbe7df783d/projects/batfish/src/main/java/org/batfish/representation/palo_alto/Rulebase.java#L17)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
>     _natRules = new LinkedHashMap<>();
> ```
nat rule change coming separately? or deferred for now?
</blockquote></details>

deferred.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/collections/InsertOrderedMap.java, line 63 at r2](https://reviewable.io/reviews/batfish/batfish/6355#-MKMk1U47OhUyR-xS1FS:-MKMpzFZ7B1O3CEFtwtT:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/7c08465749027129e35b9f1f7ffa4cdbe7df783d/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/collections/InsertOrderedMap.java#L63)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
> key
> ```
nit: value
</blockquote></details>

done
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/collections/InsertOrderedMap.java, line 87 at r2](https://reviewable.io/reviews/batfish/batfish/6355#-MKMkBjYCMBzhhqQi67c:-MKMq0kh6RACtmjZLS4A:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/7c08465749027129e35b9f1f7ffa4cdbe7df783d/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/collections/InsertOrderedMap.java#L87)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
> key
> ```
nit: `key or value`
</blockquote></details>

done
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/collections/InsertOrderedMap.java, line 178 at r2](https://reviewable.io/reviews/batfish/batfish/6355#-MKMkXOWA3M1EXQP0lpk:-MKMq1ST8Z9rjdUK8jIj:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/7c08465749027129e35b9f1f7ffa4cdbe7df783d/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/collections/InsertOrderedMap.java#L178)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
> prior the the
> ```
nit: to
</blockquote></details>

done
___
*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/collections/InsertOrderedMapTest.java, line 173 at r2](https://reviewable.io/reviews/batfish/batfish/6355#-MKMmIUMEcYG7fp6o-yw:-MKMq2kp68P8gX9JzbsF:b-87gx22) ([raw file](https://github.com/batfish/batfish/blob/7c08465749027129e35b9f1f7ffa4cdbe7df783d/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/collections/InsertOrderedMapTest.java#L173)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

what happens/should happen if you move `key` after `key`?
</blockquote></details>

good question. I decided it should have no effect, and added short-circuiting.

**Review by sfraint — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6355)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
