### PR TITLE
Add support for ASA network objects

### PR DESCRIPTION
**Pull request by sfraint**
Add Cisco ASA `network object` datamodel support and ref tracking.  Also fixed existing ref tracking using `network object-group` structure type instead of `network object`.

### CODE REVIEW

**Comment by dhalperi** [comment]
Thanks! :lgtm: 

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed, 3 unresolved discussions (waiting on @sfraint, @haverma, and @arifogel)

---

*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 2437 at r1](https://reviewable.io/reviews/batfish/batfish/1778#-LG6F5T3BKJh0QHV18ZO:-LG6F5T3BKJh0QHV18ZP:b-t5dnst) ([raw file](https://github.com/batfish/batfish/blob/bc4de3a6763c0d28c7f59b7db0f99c45e46882d8/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L2437)):*
> ```Java
>   public void exitOn_fqdn(On_fqdnContext ctx) {
>     _currentNetworkObject.setIpSpace(EmptyIpSpace.INSTANCE);
>     _w.redFlag("Cannot convert fqdn to IpSpace: " + getFullText(ctx));
> ```

More user facing? `Unknown how to resolve domain name to IP address(es)`

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoStructureUsage.java, line 97 at r1](https://reviewable.io/reviews/batfish/batfish/1778#-LG6FHN9EUm9iPiTQF0b:-LG6FGZT7t-9bHoonJzd:bjo6nxt) ([raw file](https://github.com/batfish/batfish/blob/ee5c87322364d8363949e170fb9f3762ad718732/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoStructureUsage.java#L97)):*
> ```Java
>   MSDP_PEER_SA_LIST("msdp peer sa-list"),
>   NETWORK_OBJECT_GROUP_GROUP_OBJECT("object-group network group-object"),
>   NETWORK_OBJECT_GROUP_NETWORK_OBJECT("object-group network network-object"),
> ```

From the unit tests, it looks like the syntax is still `network-object`: `object-group network foo` -> `network-object bar`.

Why this change?

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/NetworkObject.java, line 6 at r1](https://reviewable.io/reviews/batfish/batfish/1778#-LG6FS6iBrbFkS9zF0c0:-LG6FS6iBrbFkS9zF0c1:b-bpulek) ([raw file](https://github.com/batfish/batfish/blob/bc4de3a6763c0d28c7f59b7db0f99c45e46882d8/projects/batfish/src/main/java/org/batfish/representation/cisco/NetworkObject.java#L6)):*
> ```
> ComparableStructure<String>
> ```

Does this need to be a ComparableStructure or can it just be an object with a String _name property?

cc: @anothermattbrown 

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1778#-:-LG6G3ET4B4T89wRlYCh:b6duv8n)*

**Comment by sfraint** [comment]
Review status: 9 of 11 files reviewed, 3 unresolved discussions (waiting on @dhalperi and @sfraint)

---

*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 2437 at r1](https://reviewable.io/reviews/batfish/batfish/1778#-LG6F5T3BKJh0QHV18ZO:-LG6LdLC83zmprKptlC1:b-8iw09a) ([raw file](https://github.com/batfish/batfish/blob/bc4de3a6763c0d28c7f59b7db0f99c45e46882d8/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L2437)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

More user facing? `Unknown how to resolve domain name to IP address(es)`
</blockquote></details>

Sounds good.  Done.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoStructureUsage.java, line 97 at r1](https://reviewable.io/reviews/batfish/batfish/1778#-LG6FHN9EUm9iPiTQF0b:-LG6MSK564OC5XAPgI0v:bujisso) ([raw file](https://github.com/batfish/batfish/blob/ee5c87322364d8363949e170fb9f3762ad718732/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoStructureUsage.java#L97)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

From the unit tests, it looks like the syntax is still `network-object`: `object-group network foo` -> `network-object bar`.

Why this change?
</blockquote></details>

I thought it was less redundant and just as clear to specify just the `object` keyword here.  That is the initial keyword used to define a network object (`object network NAME`) and that is the keyword used to reference a network object (`network-object object NAME` vs `network-object INLINE_DEF` for inline definition).

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/NetworkObject.java, line 6 at r1](https://reviewable.io/reviews/batfish/batfish/1778#-LG6FS6iBrbFkS9zF0c0:-LG6N0Px94kEP1zaZkP_:bek36cm) ([raw file](https://github.com/batfish/batfish/blob/bc4de3a6763c0d28c7f59b7db0f99c45e46882d8/projects/batfish/src/main/java/org/batfish/representation/cisco/NetworkObject.java#L6)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> ComparableStructure<String>
> ```

Does this need to be a ComparableStructure or can it just be an object with a String _name property?

cc: @anothermattbrown 
</blockquote></details>

Object with `_name` is fine.  Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1778)*

**Comment by arifogel** [comment]
Reviewed 8 of 11 files at r1, 2 of 2 files at r2.
Review status: all files reviewed, 3 unresolved discussions (waiting on @dhalperi)

---

*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 2437 at r1](https://reviewable.io/reviews/batfish/batfish/1778#-LG6F5T3BKJh0QHV18ZO:-LG6VEWx6rdiMO5iZ_aG:b-bsxrwp) ([raw file](https://github.com/batfish/batfish/blob/bc4de3a6763c0d28c7f59b7db0f99c45e46882d8/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L2437)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

Sounds good.  Done.
</blockquote></details>

Suggestion possibly for another PR:
We could treat domain names as an an undefined/lazily-defined named IpSpace , since that is kinda how they work anyway.
One could provide as metadata DNS entries that would propagate into definitions for these named ipspaces (via the ipspaces passed into `containsIp`).

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1778)*

**Comment by arifogel** [comment]
Reviewed 1 of 11 files at r1.
Review status: all files reviewed, 3 unresolved discussions (waiting on @dhalperi and @sfraint)

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1778)*

**Comment by dhalperi** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi and @arifogel)

---

*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 2437 at r1](https://reviewable.io/reviews/batfish/batfish/1778#-LG6F5T3BKJh0QHV18ZO:-LG6Xhbx4cHvHZVgN_aw:b55x5uq) ([raw file](https://github.com/batfish/batfish/blob/bc4de3a6763c0d28c7f59b7db0f99c45e46882d8/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L2437)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Suggestion possibly for another PR:
We could treat domain names as an an undefined/lazily-defined named IpSpace , since that is kinda how they work anyway.
One could provide as metadata DNS entries that would propagate into definitions for these named ipspaces (via the ipspaces passed into `containsIp`).
</blockquote></details>

@arifogel : +1, but also +1 on for later ;)

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoStructureUsage.java, line 97 at r1](https://reviewable.io/reviews/batfish/batfish/1778#-LG6FHN9EUm9iPiTQF0b:-LG6_c-BCgrCik2oRE4z:bv87bfa) ([raw file](https://github.com/batfish/batfish/blob/ee5c87322364d8363949e170fb9f3762ad718732/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoStructureUsage.java#L97)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

I thought it was less redundant and just as clear to specify just the `object` keyword here.  That is the initial keyword used to define a network object (`object network NAME`) and that is the keyword used to reference a network object (`network-object object NAME` vs `network-object INLINE_DEF` for inline definition).
</blockquote></details>

Per discussion, change suffix to `network-object object` to match the use syntax for this PR.

We can have a separate discussion about adding a hierarchical separator for ease of reading, (e.g., `object-group network > network-object object`?),

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1778)*

**Comment by arifogel** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1778)*

**Comment by arifogel** [comment]
:lgtm:

---

Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1778#-:-LG6aSjeAlSCk79R0dEp:bnfp4nl)*

**Pull request merged**
