### PR TITLE
CheckPoint: allow `Network` objects in Manual Static NAT rules

### PR DESCRIPTION
**Pull request by sfraint**

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7658)* status: all files reviewed, 1 unresolved discussion (waiting on @corinaminer and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversions.java, line 116 at r1](https://reviewable.io/reviews/batfish/batfish/7658#-Mo0wO2H9pdceB3UhmSg:-Mo0wO2I96euwphHZndS:b-kvk87e) ([raw file](https://github.com/batfish/batfish/blob/72c4d27da515ad5192e8cab642fd17d2d9f6bb25/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversions.java#L116)):*
> ```Java
>       assert network.getSubnetMask() != null;
>       Prefix prefix = Prefix.create(network.getSubnet4(), network.getSubnetMask());
>       return ImmutableList.of(assignSourceIp(prefix.getStartIp(), prefix.getEndIp()));
> ```

Are you sure this isn't supposed to be a shift? Can you use networks of different sizes, or not use a network for the original src ip constraint?

Same question for destination.

Also, if not a shift, should the range be the whole prefix or from the first host ip to the last host ip?

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7658)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversions.java, line 116 at r1](https://reviewable.io/reviews/batfish/batfish/7658#-Mo0wO2H9pdceB3UhmSg:-Mo14hrT-KOsfM-NlkEn:b-azd2if) ([raw file](https://github.com/batfish/batfish/blob/72c4d27da515ad5192e8cab642fd17d2d9f6bb25/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversions.java#L116)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Are you sure this isn't supposed to be a shift? Can you use networks of different sizes, or not use a network for the original src ip constraint?

Same question for destination.

Also, if not a shift, should the range be the whole prefix or from the first host ip to the last host ip?
</blockquote></details>

Using host IPs for now and added a `TODO` to confirm device behavior

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7658)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7658)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

**Pull request merged**
