### PR TITLE
 Flip the bit on NX-OS BGP parser, update refs

### PR DESCRIPTION
**Pull request by dhalperi**
Needs improved testing. So far:

- [x] differences to checked-in refs look correct
- [x] better behavior on several real networks
- [x] single-variant parser fixed a bug in one of our unit tests.
- [ ] ipv6 support, at least in the grammar

What other check boxes should we add?

### CODE REVIEW

**Comment by arifogel** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[test_rigs/parsing-tests/unit-tests-nodes.ref, line 8369 at r1](https://reviewable.io/reviews/batfish/batfish/1385#-LCVyJN17o_JSMYmEdJu:-LCVyJN21-PRBuz83lF6:b-hkyew) ([raw file](https://github.com/batfish/batfish/blob/1a5def8b1afb2990bef9f73b75406d0dd75d4399/test_rigs/parsing-tests/unit-tests-nodes.ref#L8369)):*
> ```
>             ]
>           },
>           "~BGP_PEER_EXPORT_POLICY:default:123.123.123.0/24~" : {
> ```

I assume these disappeared because the peers were not activated according to rules of nxos?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1385)*

**Comment by dhalperi** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test_rigs/parsing-tests/unit-tests-nodes.ref, line 8369 at r1](https://reviewable.io/reviews/batfish/batfish/1385#-LCVyJN17o_JSMYmEdJu:-LCW0nWFBIoz_3sccs19:bn9bbub) ([raw file](https://github.com/batfish/batfish/blob/1a5def8b1afb2990bef9f73b75406d0dd75d4399/test_rigs/parsing-tests/unit-tests-nodes.ref#L8369)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

I assume these disappeared because the peers were not activated according to rules of nxos?
</blockquote></details>

Yes.  You may wish to also review the new MISCELLANEOUS warnings.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1385)*

**Comment by arifogel** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test_rigs/parsing-tests/unit-tests-nodes.ref, line 8369 at r1](https://reviewable.io/reviews/batfish/batfish/1385#-LCVyJN17o_JSMYmEdJu:-LCWCMHrB_0NwI7SDlZ4:b-dt6w2z) ([raw file](https://github.com/batfish/batfish/blob/1a5def8b1afb2990bef9f73b75406d0dd75d4399/test_rigs/parsing-tests/unit-tests-nodes.ref#L8369)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Yes.  You may wish to also review the new MISCELLANEOUS warnings.
</blockquote></details>

Oh these are passive! So they never should have been generated most likely. Seems fine then.
FYI I did review MISCELLANEOUS warnings, but that didn't seem to explain this change.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1385)*

**Comment by progwriter** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1385)*

**Comment by dhalperi** [comment]
Not ready.

**Pull request closed without merging**
