### PR TITLE
CheckPoint: merge `AccessLayer` pages

### PR DESCRIPTION
**Pull request by sfraint**
Handle merging `AccessLayer` pages in access-rulebase json input files.

----

Handles merging both:
1. top-level rulebase split across pages
2. rulebase within `AccessSection`s under the top-level rulebase

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7370)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/parsing/CheckpointManagementParser.java, line 166 at r1](https://reviewable.io/reviews/batfish/batfish/7370#-MjGekgs7Af9Y3b0CV6a:-MjGdY3CA5Er6uJwxSoC:b-tqiqhj) ([raw file](https://github.com/batfish/batfish/blob/88e71c74c965602f0ef7018f45ecbec314286e5a/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/parsing/CheckpointManagementParser.java#L166)):*
> ```Java
>   private static @Nonnull AccessLayer mergeAccessLayer(
>       Collection<AccessLayer> pages, ParseVendorConfigurationAnswerElement pvcae) {
>     Uid uid = pages.iterator().next().getUid();
> ```

Just for sanity, assert pages is non-empty.
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/parsing/CheckpointManagementParser.java, line 167 at r1](https://reviewable.io/reviews/batfish/batfish/7370#-MjGdiwu541tm_746ek4:-MjGdiwu541tm_746ek5:byrgnh3) ([raw file](https://github.com/batfish/batfish/blob/88e71c74c965602f0ef7018f45ecbec314286e5a/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/parsing/CheckpointManagementParser.java#L167)):*
> ```Java
>       Collection<AccessLayer> pages, ParseVendorConfigurationAnswerElement pvcae) {
>     Uid uid = pages.iterator().next().getUid();
>     String name = pages.iterator().next().getName();
> ```

Why get an iterator twice? Just grab the next page once.
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/parsing/CheckpointManagementParser.java, line 173 at r1](https://reviewable.io/reviews/batfish/batfish/7370#-MjGfGYr-2l_HXYAm9w1:-MjGfGYr-2l_HXYAm9w2:b84wzli) ([raw file](https://github.com/batfish/batfish/blob/88e71c74c965602f0ef7018f45ecbec314286e5a/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/parsing/CheckpointManagementParser.java#L173)):*
> ```Java
>         .forEach(o -> objs.put(o.getKey(), o.getValue()));
>     return new AccessLayer(
>         objs,
> ```

wrap in `ImmutableMap.copyOf`

**Review by arifogel — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7370)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @sfraint)

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7370)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/parsing/CheckpointManagementParser.java, line 166 at r1](https://reviewable.io/reviews/batfish/batfish/7370#-MjGekgs7Af9Y3b0CV6a:-MjGhbd56Dy2LU5vx6Re:bvnrpcm) ([raw file](https://github.com/batfish/batfish/blob/88e71c74c965602f0ef7018f45ecbec314286e5a/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/parsing/CheckpointManagementParser.java#L166)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Just for sanity, assert pages is non-empty.
</blockquote></details>

updated
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/parsing/CheckpointManagementParser.java, line 167 at r1](https://reviewable.io/reviews/batfish/batfish/7370#-MjGdiwu541tm_746ek4:-MjGhY0n9WZmidyRx-22:bvnrpcm) ([raw file](https://github.com/batfish/batfish/blob/88e71c74c965602f0ef7018f45ecbec314286e5a/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/parsing/CheckpointManagementParser.java#L167)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Why get an iterator twice? Just grab the next page once.
</blockquote></details>

updated
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/parsing/CheckpointManagementParser.java, line 173 at r1](https://reviewable.io/reviews/batfish/batfish/7370#-MjGfGYr-2l_HXYAm9w1:-MjGhalR2s3p8ibn3iMK:bvnrpcm) ([raw file](https://github.com/batfish/batfish/blob/88e71c74c965602f0ef7018f45ecbec314286e5a/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/parsing/CheckpointManagementParser.java#L173)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

wrap in `ImmutableMap.copyOf`
</blockquote></details>

updated

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7370)* status: all files reviewed, 4 unresolved discussions (waiting on @arifogel and @sfraint)

___
*[projects/batfish/src/test/java/org/batfish/vendor/check_point_management/parsing/CheckpointManagementParserTest.java, line 511 at r2](https://reviewable.io/reviews/batfish/batfish/7370#-MjGhxSRA4at1tDb5lVQ:-MjGhxSSBBCIVF7cqt-w:bcriwgt) ([raw file](https://github.com/batfish/batfish/blob/93ceeb54f2f9458e3fa5d50f60d0196b48a13a1e/projects/batfish/src/test/java/org/batfish/vendor/check_point_management/parsing/CheckpointManagementParserTest.java#L511)):*
> ```Java
>     AccessLayer al1b =
>         new AccessLayer(ImmutableMap.of(uidAny, any), ImmutableList.of(rule3), uid1, name1);
>     AccessLayer al1 =
> ```

Testing of al1 seems redundant with above test function.

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7370)* status: all files reviewed, 4 unresolved discussions (waiting on @arifogel)

___
*[projects/batfish/src/test/java/org/batfish/vendor/check_point_management/parsing/CheckpointManagementParserTest.java, line 511 at r2](https://reviewable.io/reviews/batfish/batfish/7370#-MjGhxSRA4at1tDb5lVQ:-MjGiDOZ5JXjXMoqP6m5:braxtvx) ([raw file](https://github.com/batfish/batfish/blob/93ceeb54f2f9458e3fa5d50f60d0196b48a13a1e/projects/batfish/src/test/java/org/batfish/vendor/check_point_management/parsing/CheckpointManagementParserTest.java#L511)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Testing of al1 seems redundant with above test function.
</blockquote></details>

yep, removed

**Review by arifogel — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7370)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

**Pull request merged**
