### PR TITLE
Simplify Coordinator/Batfish communication

### PR DESCRIPTION
**Pull request by dhalperi**
Rather than passing lots of (redundant) paths around, pass a single `storageBase` argument and then also pass other keys (`containerName`).

Other paths, which are fully constructable from things like `storageBase`, `containerName`, `testrigName`, and `questionName`, for example, are constructed from those components.

Suggestions for simplification would be great.

### CODE REVIEW

**Comment by progwriter** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1715#-:-LFT7cvr7wRCpasGySsy:bnfp4nl)*

**Comment by arifogel** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi)

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1715#-LFTodTr1zALMSjfgts0:-LFTodTr1zALMSjfgts1:b4lsglv) (no related file):*
So would `storagebase` be e.g. `x/y/z/containers` or `x/y/z`? That is, is `containers` a special string at all?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1715#-:-LFTpE1I2vo2HcALB1WE:bnfp4nl)*

**Comment by dhalperi** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi)

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1715#-LFTodTr1zALMSjfgts0:-LFTrmRHD7vJe9w0pnxA:b4l2arw) (no related file):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

So would `storagebase` be e.g. `x/y/z/containers` or `x/y/z`? That is, is `containers` a special string at all?
</blockquote></details>

With this change, storage base is `containers` by default and would get replaced by `x/y/z` if the user passed `-containerslocation x/y/z`.

I think this exactly mirrors the current behavior -- the fact that there's a path component called `containers` happens only because the default value of `containerslocation` is `"containers"` -- if the user says `-containerslocation foo`, then container `C` will be at `foo/C`, not `foo/containers/C`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1715)*

**Comment by dhalperi** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi)

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1715#-LFTodTr1zALMSjfgts0:-LFTsyIUAg_Aw4mDC26l:b-kzcq9w) (no related file):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

With this change, storage base is `containers` by default and would get replaced by `x/y/z` if the user passed `-containerslocation x/y/z`.

I think this exactly mirrors the current behavior -- the fact that there's a path component called `containers` happens only because the default value of `containerslocation` is `"containers"` -- if the user says `-containerslocation foo`, then container `C` will be at `foo/C`, not `foo/containers/C`.
</blockquote></details>

Ahh, one clarification. `storagebase` is `<absolutepathto>/containers` by default, and would be `<absolutepathto>/x/y/z` if the user passed `-containerslocation x/y/z`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1715)*

**Pull request merged**
