### PR TITLE
update toSmt2String for transformations

### PR DESCRIPTION
**Pull request by arifogel**

### CODE REVIEW

**Comment by dhalperi** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/z3/NodProgram.java, line 100 at r1](https://reviewable.io:443/reviews/batfish/batfish/978#-L6076qTLq3KPQpuCBCu:-L6076qTLq3KPQpuCBCv:b-c0rjz7) ([raw file](https://github.com/batfish/batfish/blob/87a5f8255b86745bb525ff8a61011d1e6ebc8de1/projects/batfish/src/main/java/org/batfish/z3/NodProgram.java#L100)):*
> ```Java
>     Streams.concat(
>             Arrays.<HeaderField>stream(BasicHeaderField.values()),
>             Arrays.<HeaderField>stream(TransformationHeaderField.values()))
> ```

why do you need types here but not in the same construction above?

---

*[projects/batfish/src/main/java/org/batfish/z3/NodProgram.java, line 106 at r1](https://reviewable.io:443/reviews/batfish/batfish/978#-L607A4m6oOqv1TN3g8P:-L607A4m6oOqv1TN3g8Q:bd648q0) ([raw file](https://github.com/batfish/batfish/blob/87a5f8255b86745bb525ff8a61011d1e6ebc8de1/projects/batfish/src/main/java/org/batfish/z3/NodProgram.java#L106)):*
> ```Java
>                 Function.identity(), v -> String.format("(:var %d)", currentVar.getAndIncrement())))
>         .forEach(
>             (name, var) ->
> ```

`collect` -> `foreach` is a weird pattern, since I don't think the collector is a merging collector. Not sure why you don't just foreach on the input to collect.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/978)*

**Comment by arifogel** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/z3/NodProgram.java, line 100 at r1](https://beta.reviewable.io/reviews/batfish/batfish/978#-L6076qTLq3KPQpuCBCu:-L62tKUT9Ls1Jl52nM7f:ba3dfob) ([raw file](https://github.com/batfish/batfish/blob/87a5f8255b86745bb525ff8a61011d1e6ebc8de1/projects/batfish/src/main/java/org/batfish/z3/NodProgram.java#L100)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

why do you need types here but not in the same construction above?
</blockquote></details>

Removed

---

*[projects/batfish/src/main/java/org/batfish/z3/NodProgram.java, line 106 at r1](https://beta.reviewable.io/reviews/batfish/batfish/978#-L607A4m6oOqv1TN3g8P:-L62tL1jA8mAuikT5LKo:bpjywh6) ([raw file](https://github.com/batfish/batfish/blob/87a5f8255b86745bb525ff8a61011d1e6ebc8de1/projects/batfish/src/main/java/org/batfish/z3/NodProgram.java#L106)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

`collect` -> `foreach` is a weird pattern, since I don't think the collector is a merging collector. Not sure why you don't just foreach on the input to collect.
</blockquote></details>

Adjusted as indicated. However, I'm open to a suggestion about a better pattern than using an array for lack of an `AtomicString`.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/978)*

**Comment by dhalperi** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/java/org/batfish/z3/NodProgram.java, line 106 at r1](https://beta.reviewable.io/reviews/batfish/batfish/978#-L607A4m6oOqv1TN3g8P:-L62uOTa2bhtIfYmcDeF:buzkho1) ([raw file](https://github.com/batfish/batfish/blob/87a5f8255b86745bb525ff8a61011d1e6ebc8de1/projects/batfish/src/main/java/org/batfish/z3/NodProgram.java#L106)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Adjusted as indicated. However, I'm open to a suggestion about a better pattern than using an array for lack of an `AtomicString`.
</blockquote></details>

https://stackoverflow.com/a/1326962/1715495 ?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/978)*

**Comment by dhalperi** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/978#-:-L62uRg35c2Iq5X7w7zV:bnfp4nl)*

**Pull request merged**
