### PR TITLE
Pan: application-override rule conversion

### PR DESCRIPTION
**Pull request by sfraint**
Convert `application-override rules` and use them in `security rule` ACLs.

Includes splitting `service` matching into `service` and `application` components since `application-override rules` can conflict with `service` matching.

----

For an application-override rule that looks like this:
```
set rulebase application-override rules AO_RULE_NAME from z1
set rulebase application-override rules AO_RULE_NAME to z2
set rulebase application-override rules AO_RULE_NAME source ADDR_GRP3
set rulebase application-override rules AO_RULE_NAME destination ADDR_GRP4
set rulebase application-override rules AO_RULE_NAME port 7653
set rulebase application-override rules AO_RULE_NAME protocol tcp
set rulebase application-override rules AO_RULE_NAME application APP_NAME
```

Trace details can look something like this now:
```
Matched security rule SR_RULE_NAME
  Matched source address
    Matched address-group ADDR_GRP1
  Matched destination address
    Matched address-group ADDR_GRP2
  Matched service application-default
    Matched application object APP_NAME
      Matched application-override rule AO_RULE_NAME
        Matched source address
          Matched address-group ADDR_GRP3
        Matched destination address
          Matched address-group ADDR_GRP4
        Matched protocol TCP
        Matched port
```

### CODE REVIEW

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6651)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6651#-MTx9RnS8xeMq0GG27tv:-MTx9RnS8xeMq0GG27tw:b-9q7hah) (no related file):*
Still need to add a couple more tests: trace detail tests w/ app-override rules, app-override conversion warnings

---

**Review by dhalperi — COMMENTED** [review]
> Reviewed 9 of 10 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6651)* status: all files reviewed, 4 unresolved discussions (waiting on @corinaminer and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6651#-MU-iRdi0H1-yEXPxlaK:-MU-iRdi0H1-yEXPxlaL:bshz71k) (no related file):*
I didn't see any tests where the same application is mapped to by multiple rules but with different/conflicting service, e.g., my APP can be running on z1>z2 tcp 50 and z3->z2 tcp 70, and it works well.

---
___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/ApplicationOverrideRule.java, line 123 at r2](https://reviewable.io/reviews/batfish/batfish/6651#-MU-cGOBCxpM4O1fLovx:-MU-cGOBCxpM4O1fLovy:b-i2pte4) ([raw file](https://github.com/batfish/batfish/blob/26a581a7114065468a6c1afb0ca477707f0d5cab/projects/batfish/src/main/java/org/batfish/representation/palo_alto/ApplicationOverrideRule.java#L123)):*
> ```
>     return _protocol == Protocol.TCP
>         ? IpProtocol.TCP
>         : _protocol == Protocol.UDP ? IpProtocol.UDP : null;
> ```
given enum, probably best as a switch?
___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java, line 1506 at r2](https://reviewable.io/reviews/batfish/batfish/6651#-MU-deeO4Zg_Bp3kMg7Z:-MU-deeO4Zg_Bp3kMg7_:bh195iy) ([raw file](https://github.com/batfish/batfish/blob/26a581a7114065468a6c1afb0ca477707f0d5cab/projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java#L1506)):*
> ```
> headerspaces
> ```
packets? (We don't mean `HeaderSpace`, right? that class is on its way out (I hope)).

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6651)* status: 5 of 12 files reviewed, 3 unresolved discussions (waiting on @corinaminer and @dhalperi)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6651#-MTx9RnS8xeMq0GG27tv:-MUB6CmPCYMwqGQvP8Ku:b-7tfmjp) (no related file):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

Still need to add a couple more tests: trace detail tests w/ app-override rules, app-override conversion warnings
</blockquote></details>

added

---
*[a discussion](https://reviewable.io/reviews/batfish/batfish/6651#-MU-iRdi0H1-yEXPxlaK:-MUAHUbU3EWCB751OLEx:bll4hwj) (no related file):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I didn't see any tests where the same application is mapped to by multiple rules but with different/conflicting service, e.g., my APP can be running on z1>z2 tcp 50 and z3->z2 tcp 70, and it works well.
</blockquote></details>

added one in the `shadowing` test config

---
___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/ApplicationOverrideRule.java, line 123 at r2](https://reviewable.io/reviews/batfish/batfish/6651#-MU-cGOBCxpM4O1fLovx:-MUAHSgq0BFHp8_pEaR0:b-p6bue) ([raw file](https://github.com/batfish/batfish/blob/26a581a7114065468a6c1afb0ca477707f0d5cab/projects/batfish/src/main/java/org/batfish/representation/palo_alto/ApplicationOverrideRule.java#L123)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
>     return _protocol == Protocol.TCP
>         ? IpProtocol.TCP
>         : _protocol == Protocol.UDP ? IpProtocol.UDP : null;
> ```
given enum, probably best as a switch?
</blockquote></details>

updated, how's that?
___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java, line 1506 at r2](https://reviewable.io/reviews/batfish/batfish/6651#-MU-deeO4Zg_Bp3kMg7Z:-MUA3kNY876ZKUU0TifM:b-aiivf4) ([raw file](https://github.com/batfish/batfish/blob/26a581a7114065468a6c1afb0ca477707f0d5cab/projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java#L1506)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> headerspaces
> ```
packets? (We don't mean `HeaderSpace`, right? that class is on its way out (I hope)).
</blockquote></details>

right, updated

**Review by dhalperi — COMMENTED** [review]
> Reviewed 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6651)* status: all files reviewed, 1 unresolved discussion (waiting on @corinaminer and @dhalperi)

**Pull request merged**
