### PR TITLE
Add support for ASA service objects

### PR DESCRIPTION
**Pull request by sfraint**
Add Cisco ASA `service object` datamodel support, ref tracking, and improve grammar support.

### CODE REVIEW

**Comment by sfraint** [comment]
Review status: 11 of 13 files reviewed, 1 unresolved discussion (waiting on @arifogel, @sfraint, and @anothermattbrown)

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_common.g4, line 500 at r1](https://reviewable.io/reviews/batfish/batfish/1789#-LGBz46UBQ02NhD1N2Hv:-LGQqi8j89sjU7j2uti0:b6dcp0a) ([raw file](https://github.com/batfish/batfish/blob/af2a59b79ebabf72ecc61879552c8861b332fcac/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_common.g4#L500)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Do these have to appear in this order? If not, you should use a `*` block with both of these parenthetical expressions as alternatives.
</blockquote></details>

They do have to appear in that order.

---

*[projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java, line 2466 at r1](https://reviewable.io/reviews/batfish/batfish/1789#-LGC-8M_ChZcBEN1ZEGC:-LGQr8eO-GwZJ-ZOiCfV:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/af2a59b79ebabf72ecc61879552c8861b332fcac/projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java#L2466)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

can you include the format in the name, e.g. `"asa-service-object"` or whatever?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1789)*

**Comment by arifogel** [comment]
Reviewed 2 of 2 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown)

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1789)*

**Comment by arifogel** [comment]
:lgtm:

---

Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown)

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1789#-:-LGQt9Ih27gE-Oii-6My:bnfp4nl)*

**Comment by sfraint** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown)

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1789)*

**Pull request merged**
