### PR TITLE
Add more rancid types

### PR DESCRIPTION
**Pull request by ratulm**

### CODE REVIEW

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8135)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @arifogel and @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/grammar/VendorConfigurationFormatDetector.java, line 506 at r1](https://reviewable.io/reviews/batfish/batfish/8135#-MxrFP3B51I0B8le1Tpo:-MxrFP3B51I0B8le1Tpp:b-yq1zgr) ([raw file](https://github.com/batfish/batfish/blob/47ecc8615822bc6b033a50276fc2c0978b16fb61/projects/batfish/src/main/java/org/batfish/grammar/VendorConfigurationFormatDetector.java#L506)):*
> ```Java
>       case "zebra":
>       case "frr":
>         // Will this interfere with Cumulus detection?
> ```

FYI, any interference semantics have not changed as part of this PR. Before it, Batfish would have returned `UNKNOWN` preventing further detection. It now returns `FRR` which also prevents further detection.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8135)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @arifogel and @ratulm)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/8135#-MxuBAAh3Dy6-wyjYJLn:-MxuBAAh3Dy6-wyjYJLo:b-6iqjaa) (no related file):*
+reviewer:@arifogel

---
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ConfigurationFormat.java, line 7 at r1](https://reviewable.io/reviews/batfish/batfish/8135#-Mxu8Dzl18F46iRoFz1_:-Mxu8Dzl18F46iRoFz1a:bqhsqi7) ([raw file](https://github.com/batfish/batfish/blob/47ecc8615822bc6b033a50276fc2c0978b16fb61/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ConfigurationFormat.java#L7)):*
> ```Java
>   A10_ACOS("a10_acos"),
>   ALCATEL_AOS("alcatel_aos"),
>   ALTEON("alteon"),
> ```

I do not think we should add more of these that are not supported by Batfish. I think UNKNOWN/UNSUPPORTED is significantly better for users.

@arifogel ?

**Review by arifogel — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8135)* status: all files reviewed, 1 unresolved discussion (waiting on @ratulm)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ConfigurationFormat.java, line 7 at r1](https://reviewable.io/reviews/batfish/batfish/8135#-Mxu8Dzl18F46iRoFz1_:-My967C_CtJIAFUVpVsL:b-pbdqz3) ([raw file](https://github.com/batfish/batfish/blob/47ecc8615822bc6b033a50276fc2c0978b16fb61/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ConfigurationFormat.java#L7)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I do not think we should add more of these that are not supported by Batfish. I think UNKNOWN/UNSUPPORTED is significantly better for users.

@arifogel ?
</blockquote></details>

Agreed.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8135)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ratulm)

**Pull request merged**
