### PR TITLE
Populate CheckpointManagementConfiguration

### PR DESCRIPTION
**Pull request by corinaminer**

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7264)* status: all files reviewed, 7 unresolved discussions (waiting on @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 1582 at r1](https://reviewable.io/reviews/batfish/batfish/7264#-MhowR65CYJtCXncZM81:-MhowR65CYJtCXncZM82:b-j4dr1b) ([raw file](https://github.com/batfish/batfish/blob/7029ec4ff57a4452b5ceb2af95c3846ec5e6590b/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L1582)):*
> ```Java
>   }
> 
>   private CheckpointManagementConfiguration parseCheckpointManagementData(
> ```

We can fix later, but this really should go outside of `Batfish.java`.
Also, `@Nonnull` apparently.
___
*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 1668 at r1](https://reviewable.io/reviews/batfish/batfish/7264#-Mhoz3ww97-Aot3CAV3n:-Mhoz3ww97-Aot3CAV3o:btbvma8) ([raw file](https://github.com/batfish/batfish/blob/7029ec4ff57a4452b5ceb2af95c3846ec5e6590b/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L1668)):*
> ```Java
>                           new TypeReference<List<NatRulebase>>() {})
>                   : ImmutableList.of();
>           NatRulebase natRulebase = natRulebases.isEmpty() ? null : natRulebases.get(0);
> ```

If there is no NAT rulebase, but the package says there should be one (`Package._natPolicy` is `true`), please warn.
Unfortunately the getters are missing, so add `hasNatPolicy` to `Package`.

Also if `_natPolicy` is `false`,  don't try to extract the nat policy.
___
*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 1698 at r1](https://reviewable.io/reviews/batfish/batfish/7264#-Mhozm6mEJI2mXRrAIsj:-Mhozm6mEJI2mXRrAIsk:b-jsluio) ([raw file](https://github.com/batfish/batfish/blob/7029ec4ff57a4452b5ceb2af95c3846ec5e6590b/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L1698)):*
> ```Java
>         ManagementDomain mgmtDomain =
>             new ManagementDomain(domain, gatewaysAndServers.getGatewaysAndServers(), packages);
>         domainsMap.put(domainName, mgmtDomain);
> ```

Either the authoritative domain name is the one in the extracted `Domain`, or it must match the name of the corresponding `folder`. Here you can have a mismatch if the configs are packaged improperly (especially manually), which can be very confusing.
___
*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 2424 at r1](https://reviewable.io/reviews/batfish/batfish/7264#-MhoxE9rEcbMIx2BtRhB:-MhoxE9rEcbMIx2BtRhC:b-2ksv2h) ([raw file](https://github.com/batfish/batfish/blob/7029ec4ff57a4452b5ceb2af95c3846ec5e6590b/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L2424)):*
> ```Java
>       NetworkSnapshot snapshot, ParseVendorConfigurationAnswerElement pvcae) {
>     // Serialize Checkpoint management servers if present
>     _logger.info("\n*** READING CHECKPOINT MANAGEMENT CONFIGS ***\n");
> ```

Use log4j logging either in addition or exclusively for new code.
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/PackageInstallationTarget.java, line 11 at r1](https://reviewable.io/reviews/batfish/batfish/7264#-Mhp0MhA7lt8gqbZILVx:-Mhp0MhA7lt8gqbZILVy:b5fubzl) ([raw file](https://github.com/batfish/batfish/blob/7029ec4ff57a4452b5ceb2af95c3846ec5e6590b/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/PackageInstallationTarget.java#L11)):*
> ```Java
> import javax.annotation.Nullable;
> 
> public class PackageInstallationTarget extends NamedManagementObject {
> ```

javadoc
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/vendor/ConversionContext.java, line 6 at r1](https://reviewable.io/reviews/batfish/batfish/7264#-Mhp-cwICwg76G6P8b0c:-Mhp-cwICwg76G6P8b0d:bog0m2n) ([raw file](https://github.com/batfish/batfish/blob/7029ec4ff57a4452b5ceb2af95c3846ec5e6590b/projects/batfish-common-protocol/src/main/java/org/batfish/vendor/ConversionContext.java#L6)):*
> ```Java
> import javax.annotation.Nullable;
> 
> public final class ConversionContext implements Serializable {
> ```

A little late, but could use javadoc
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorSupplementalInformation.java, line 3 at r1](https://reviewable.io/reviews/batfish/batfish/7264#-Mhp-fN-Atw1Q89e2nOi:-Mhp-fN-Atw1Q89e2nOj:b-kh7ni6) ([raw file](https://github.com/batfish/batfish/blob/7029ec4ff57a4452b5ceb2af95c3846ec5e6590b/projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorSupplementalInformation.java#L3)):*
> ```Java
> package org.batfish.vendor;
> 
> public abstract class VendorSupplementalInformation {}
> ```

javadoc. Also consider making it an interface since there is no inherited behavior.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7264)* status: all files reviewed, 7 unresolved discussions (waiting on @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/PackageInstallationTarget.java, line 11 at r1](https://reviewable.io/reviews/batfish/batfish/7264#-Mhp0MhA7lt8gqbZILVx:-Mhp0VBu2sg950eRzlxr:b-yr4g3c) ([raw file](https://github.com/batfish/batfish/blob/7029ec4ff57a4452b5ceb2af95c3846ec5e6590b/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/PackageInstallationTarget.java#L11)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

javadoc
</blockquote></details>

and final

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7264)* status: all files reviewed, 7 unresolved discussions (waiting on @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 1582 at r1](https://reviewable.io/reviews/batfish/batfish/7264#-MhowR65CYJtCXncZM81:-Mhp0mOm1HoDy1I4vhlj:br4syft) ([raw file](https://github.com/batfish/batfish/blob/7029ec4ff57a4452b5ceb2af95c3846ec5e6590b/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L1582)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

We can fix later, but this really should go outside of `Batfish.java`.
Also, `@Nonnull` apparently.
</blockquote></details>

Also please note that parameters are _not_ nonnull by default in this file.

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7264)* status: 8 of 14 files reviewed, all discussions resolved (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 1582 at r1](https://reviewable.io/reviews/batfish/batfish/7264#-MhowR65CYJtCXncZM81:-Mhp3h1S7tsZvCXj2TzB:b3zkdf) ([raw file](https://github.com/batfish/batfish/blob/7029ec4ff57a4452b5ceb2af95c3846ec5e6590b/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L1582)):*
Added annotations.

> should go outside of `Batfish.java`

Yeah probably. I modeled after the AWS pattern, where `parseAwsConfigurations` is in Batfish, but that should probably go elsewhere too. Punting.
___
*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 1668 at r1](https://reviewable.io/reviews/batfish/batfish/7264#-Mhoz3ww97-Aot3CAV3n:-Mhp9YzJDf9wpuFA0gW-:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/7029ec4ff57a4452b5ceb2af95c3846ec5e6590b/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L1668)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

If there is no NAT rulebase, but the package says there should be one (`Package._natPolicy` is `true`), please warn.
Unfortunately the getters are missing, so add `hasNatPolicy` to `Package`.

Also if `_natPolicy` is `false`,  don't try to extract the nat policy.
</blockquote></details>

done
___
*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 1698 at r1](https://reviewable.io/reviews/batfish/batfish/7264#-Mhozm6mEJI2mXRrAIsj:-MhpBMIa8DwalWqaxUOg:b-q97k0s) ([raw file](https://github.com/batfish/batfish/blob/7029ec4ff57a4452b5ceb2af95c3846ec5e6590b/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L1698)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Either the authoritative domain name is the one in the extracted `Domain`, or it must match the name of the corresponding `folder`. Here you can have a mismatch if the configs are packaged improperly (especially manually), which can be very confusing.
</blockquote></details>

done (now using domain name as extracted from package). Might still be confusing if we try to trace stuff back to source files, though. Also in a worst case scenario, you could have name collisions this way -- e.g. if there are domain directories `A` and `B`, but the packages under `A` say their domain is called `B`.

Probably not doing anything now to address either of these concerns. or we could just be strict and completely ignore packages whose domain doesn't match the name of the domain directory they're in.
___
*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 2424 at r1](https://reviewable.io/reviews/batfish/batfish/7264#-MhoxE9rEcbMIx2BtRhB:-MhpD1CnCHOVZouzEzpb:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/7029ec4ff57a4452b5ceb2af95c3846ec5e6590b/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L2424)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Use log4j logging either in addition or exclusively for new code.
</blockquote></details>

done
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/PackageInstallationTarget.java, line 11 at r1](https://reviewable.io/reviews/batfish/batfish/7264#-Mhp0MhA7lt8gqbZILVx:-MhpDNSYDsa4EGdQ_o_E:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/7029ec4ff57a4452b5ceb2af95c3846ec5e6590b/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/PackageInstallationTarget.java#L11)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

and final
</blockquote></details>

done
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/vendor/ConversionContext.java, line 6 at r1](https://reviewable.io/reviews/batfish/batfish/7264#-Mhp-cwICwg76G6P8b0c:-MhpE5U97IxpCXVSpz3z:b-7tfmjp) ([raw file](https://github.com/batfish/batfish/blob/7029ec4ff57a4452b5ceb2af95c3846ec5e6590b/projects/batfish-common-protocol/src/main/java/org/batfish/vendor/ConversionContext.java#L6)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

A little late, but could use javadoc
</blockquote></details>

added
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorSupplementalInformation.java, line 3 at r1](https://reviewable.io/reviews/batfish/batfish/7264#-Mhp-fN-Atw1Q89e2nOi:-MhpEr1p1RdKBEuMntAW:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/7029ec4ff57a4452b5ceb2af95c3846ec5e6590b/projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorSupplementalInformation.java#L3)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

javadoc. Also consider making it an interface since there is no inherited behavior.
</blockquote></details>

done

**Review by arifogel — COMMENTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7264)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7264)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7264#-MhpInwP6PP5vtKVll_V:-MhpInwQ6IkZ52V7caqb:b-wlawkb) (no related file):*
I guess this is hard to test until something is extracted from it, so can skip for now if other tests pass.

---

**Pull request merged**
