### PR TITLE
use batfish z3 with latest patch addressing #485

### PR DESCRIPTION
**Pull request by arifogel**
This change is [Reviewable](https://reviewable.io/reviews/batfish/batfish/853)

### CODE REVIEW

**Comment by dhalperi** [comment]
Reviewed 5 of 6 files at r1.
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/batfish/batfish/853#-L2vHif7Nezf4H4Ok9y3:-L2vHif8DCCn__zrkF6f:bg4ktx9) (no related file):*
Please update all four Z3 install scripts.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/853)*

**Comment by dhalperi** [comment]
Reviewed 1 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/853)*

**Comment by arifogel** [comment]
Fixes #485

**Comment by arifogel** [comment]
Review status: 5 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/batfish/batfish/853#-L2vHif7Nezf4H4Ok9y3:-L2vUp8lCyulSx60_Ddg:bb6un1j) (no related file):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Please update all four Z3 install scripts.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/853)*

**Comment by dhalperi** [comment]
:lgtm: as long as scripts have been tested and binaries are present.

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/853#-:-L2vxQAuDCldA-j4Gb0Q:bh81rwl)*

**Pull request merged**
