### PR TITLE
CheckPoint NAT: cleanup after #7718

### PR DESCRIPTION
**Pull request by sfraint**
CheckPoint NAT cleanup after #7718

### CODE REVIEW

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7722)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @anothermattbrown and @corinaminer)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7722#-MpI70K5Cumtr7QPBUjo:-MpI70K5Cumtr7QPBUjp:bpidmbo) (no related file):*
meant to just include this in that PR...but anyway here it is

---

**Review by corinaminer — COMMENTED** [review]
:lgtm: 

FYI, no clue if `.iterator()` is faster or otherwise better than collecting to a list in this context, or how either compare to `[nat objects stream].forEach([list builder]::add)`

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7722#-:-MpJau0i23MflfEU-qfi:bmelnam)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown)

**Review by sfraint — COMMENTED** [review]
Collecting iterates over the items another time. `forEach(add)` is shorter and no more work, so I'll just do that

> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7722#-:-MpJkSt60SMa1Sk2ahtA:b-dzmmme)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @anothermattbrown and @corinaminer)

**Review by corinaminer — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7722)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown)

**Pull request merged**
