### PR TITLE
IOS-XR implement VRF leaking

### PR DESCRIPTION
**Pull request by arifogel**
- fix redistributionConditions not being updated when redistributing without policy
- allow attaching multiple route-targets in bgp leak config

### CODE REVIEW

**Review by sfraint — COMMENTED** [review]
> Reviewed 7 of 7 files at r1, 5 of 5 files at r2, 1 of 1 files at r3, 3 of 4 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6974)* status: 17 of 18 files reviewed, 1 unresolved discussion (waiting on @arifogel and @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java, line 561 at r8](https://reviewable.io/reviews/batfish/batfish/6974#-MZZu_LrDDGekLb5PzHO:-MZZu_LrDDGekLb5PzHP:b-cgei1v) ([raw file](https://github.com/batfish/batfish/blob/33162634705fb5fe0de067bd394831d4c7d05b29/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java#L561)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>     RoutingProtocol targetProtocol =
>         route.getAbstractRoute().getProtocol() == RoutingProtocol.BGP
>             ? RoutingProtocol.BGP
>             : RoutingProtocol.IBGP;
> ```
</details>

can/should this change be pulled out into a separate PR? (with appropriate tests as needed)
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConversions.java, line 1995 at r4](https://reviewable.io/reviews/batfish/batfish/6974#-MZZlzuo3aKhara1wvFT:-MZZlzupCfnflEmCce9G:b-6u7si3) ([raw file](https://github.com/batfish/batfish/blob/81947b0d79e7cdd3c0f4628e11d96aba646bd9fe/projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConversions.java#L1995)):*
> ```
> fromt
> ```
nit: stray `t`

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6974)* status: 16 of 18 files reviewed, 1 unresolved discussion (waiting on @arifogel, @dhalperi, and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java, line 561 at r8](https://reviewable.io/reviews/batfish/batfish/6974#-MZZu_LrDDGekLb5PzHO:-MZsf8kC-el0cf2FB-il:b-v06pwl) ([raw file](https://github.com/batfish/batfish/blob/33162634705fb5fe0de067bd394831d4c7d05b29/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java#L561)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
>     RoutingProtocol targetProtocol =
>         route.getAbstractRoute().getProtocol() == RoutingProtocol.BGP
>             ? RoutingProtocol.BGP
>             : RoutingProtocol.IBGP;
> ```
can/should this change be pulled out into a separate PR? (with appropriate tests as needed)
</blockquote></details>

Yes, especially since it's wrong.
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConversions.java, line 1995 at r4](https://reviewable.io/reviews/batfish/batfish/6974#-MZZlzuo3aKhara1wvFT:-MZsfMu67Mf3B2xmHc7h:b-7ql1td) ([raw file](https://github.com/batfish/batfish/blob/81947b0d79e7cdd3c0f4628e11d96aba646bd9fe/projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConversions.java#L1995)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
> fromt
> ```
nit: stray `t`
</blockquote></details>

fixed

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6974)* status: 0 of 19 files reviewed, 2 unresolved discussions (waiting on @arifogel, @dhalperi, and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6974#-MZtcumJDn1YcBvOBGg9:-MZtcumJDn1YcBvOBGgA:bkppw0t) (no related file):*
After batfish/batfish#6981

---

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6974)* status: 0 of 19 files reviewed, 1 unresolved discussion (waiting on @arifogel, @dhalperi, and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java, line 561 at r8](https://reviewable.io/reviews/batfish/batfish/6974#-MZZu_LrDDGekLb5PzHO:-MZtdIRf3LWxZoI-SogA:b-ova4ef) ([raw file](https://github.com/batfish/batfish/blob/33162634705fb5fe0de067bd394831d4c7d05b29/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java#L561)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Yes, especially since it's wrong.
</blockquote></details>

Now includes batfish/batfish#6981, (r11 through r13) which does this "correctly".

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6974)* status: 0 of 19 files reviewed, 1 unresolved discussion (waiting on @arifogel and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6974#-MZtethI3AO8iBWKI0K_:-MZtethJ42ywjNVu8fv1:b26ic4y) (no related file):*
-reviewer:@dhalperi 

---

**Review by sfraint — COMMENTED** [review]
> Reviewed 1 of 1 files at r10, 4 of 16 files at r11, 3 of 4 files at r12, 12 of 12 files at r13, 1 of 1 files at r14, 1 of 1 files at r16.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6974)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
