### PR TITLE
fix #643: store RoutingPolicy recursive references

### LINKED ISSUE #643: Explicitly mentioned routing policy structures not easily viewable in data model
When a route-map (Cisco) or policy-statement (Juniper) is applied in some direction to a BGP neighbor, Batfish does not always directly reference the converted form of that structure in the definition of that neighbor in the data model. This is because Batfish sometimes generates universal logic wrapping such structures that depends on the exact usage and vendor language. In such cases the generated logic is given a name, and it is this that is referred to as the import/export policy in the data model.

The problem with the current implementation is that there is no uniform method of discovering which named structures from the vendor configurations are being applied to a BGP peer. Such a method should be provided.

### PR DESCRIPTION
**Pull request by arifogel**
- wherever `RoutingPolicy` objects are used in datamodel as `xxx`, add a field `xxxSources` containing
  names of all route-maps/route-policies/policy-statements referenced by that `RoutingPolicy`,
  directly or indirectly
- add tests
- update refs

---
This change is [Reviewable](https://reviewable.io/reviews/batfish/batfish/648)

### CODE REVIEW

**Comment by dhalperi** [comment]
Generally makes sense, would be good to discuss in person to understand philosophy. E.g., wondering why the string description is useful in the output model and if we shouldn't just make that more structured instead.

---

Review status: 0 of 24 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/648#-:-KyK1aUo-XlVgnr4PeC0:b-te8s2v)*

**Comment by arifogel** [comment]
Need to refresh context; Are we good to merge?

---

Review status: 0 of 24 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/648#-:-Kz_R2oCpFE1HX_1kEhP:b-iejbhc)*

**Comment by dhalperi** [comment]
Reviewed 15 of 24 files at r1, 10 of 10 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/batfish/batfish/648#-L-J3vpFcsXQHT7oexiM:-L-J3vpFcsXQHT7oexiN:bb1qes1) (no related file):*
We should probably have a test that involves multiple policies to make sure we handle that correctly.

---

*[a discussion](https://reviewable.io:443/reviews/batfish/batfish/648#-L-J6PajQYL36gZlSyis:-L-J6PajQYL36gZlSyit:b-ffvi3c) (no related file):*
you asked yourself about whether thread safety is relevant here.

---

*[a discussion](https://reviewable.io:443/reviews/batfish/batfish/648#-L-J6XAjgQZcHDpU2tGI:-L-J6XAjgQZcHDpU2tGJ:b-cnmk8w) (no related file):*
you also asked whether there was a functional way to handle passing in a list of sources to collect sources.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java, line 257 at r2](https://reviewable.io:443/reviews/batfish/batfish/648#-L-J5SPg3PkaSPphSg0q:-L-J5SPg3PkaSPphSg0r:bbl2rf5) ([raw file](https://github.com/batfish/batfish/blob/5d349a8a9ee70b51a6e03d077e76d8afffea15e3/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java#L257)):*
> ```Java
>     routingPolicy.computeSources(sources, _routingPolicies, w);
>     return new TreeSet<>(
>         sources.stream().filter(s -> !RoutingPolicy.isGenerated(s)).collect(Collectors.toSet()));
> ```

question came up in discussion: is there a way to not construct two sets by using a right collector?

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java, line 257 at r2](https://reviewable.io:443/reviews/batfish/batfish/648#-L-J5Y2dMlUDFQr7jqv-:-L-J5Y2dMlUDFQr7jqv0:b-beowov) ([raw file](https://github.com/batfish/batfish/blob/5d349a8a9ee70b51a6e03d077e76d8afffea15e3/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java#L257)):*
> ```Java
>     routingPolicy.computeSources(sources, _routingPolicies, w);
>     return new TreeSet<>(
>         sources.stream().filter(s -> !RoutingPolicy.isGenerated(s)).collect(Collectors.toSet()));
> ```

also did you want to use `Predicates.not(RoutingPolicy::isGenerated)` instead? Not sure why to prefer one over the other honestly unless it helps readability.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/CallExpr.java, line 32 at r2](https://reviewable.io:443/reviews/batfish/batfish/648#-L-J35caDkH9Aolid0_x:-L-J35caDkH9Aolid0_y:b-kd0lj9) ([raw file](https://github.com/batfish/batfish/blob/5d349a8a9ee70b51a6e03d077e76d8afffea15e3/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/CallExpr.java#L32)):*
> ```Java
>       Set<String> sources, Map<String, RoutingPolicy> routingPolicies, Warnings w) {
>     if (sources.contains(_calledPolicyName)) {
>       w.redFlag("Circular reference to routing policy: '" + _calledPolicyName + "'");
> ```

maybe add something like "detected at expression <this>", e.g.?

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ConfigurationTests.java, line 105 at r2](https://reviewable.io:443/reviews/batfish/batfish/648#-L-J47c1jVoLGzkxF0o-:-L-J47c3r2MtLgp9elaH:b-s6bsvl) ([raw file](https://github.com/batfish/batfish/blob/5d349a8a9ee70b51a6e03d077e76d8afffea15e3/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ConfigurationTests.java#L105)):*
> ```Java
>     // OSPF tests
>     assertThat(ospfExportPolicyName, isIn(ospfProcess.getExportPolicySources()));
>     assertThat(ospfExportSubPolicyName, isIn(ospfProcess.getExportPolicySources()));
> ```

why not check both in the same assertion? maybe, `containsInAnyOrder`? 

also these last two assertions are backwards:

```java
assertThat(thingComputedByYourTestCode, matches(expectation));
```

so it should be something like

```java
assertThat(ospfProcess.getExportPolicySources(), containsInAnyOrder(ospfExportPolicyName, ospfExportSubPolicyName));
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/648)*

**Comment by arifogel** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/batfish/batfish/648#-L-J6XAjgQZcHDpU2tGI:-L-JGWcyV3x2v6sDkG5T:b-b7uuzk) (no related file):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

you also asked whether there was a functional way to handle passing in a list of sources to collect sources.
</blockquote></details>

decided the current way is fine

---

*[a discussion](https://reviewable.io:443/reviews/batfish/batfish/648#-L-J6PajQYL36gZlSyis:-L-JGYJioy1cT8pX66vo:bfox22) (no related file):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

you asked yourself about whether thread safety is relevant here.
</blockquote></details>

it isn't unless someone else decides to call those functions in a non-thread-safe way. not worth it for now.

---

*[a discussion](https://reviewable.io:443/reviews/batfish/batfish/648#-L-J3vpFcsXQHT7oexiM:-L-JGexCMhvPmta2ap_5:b-ius7be) (no related file):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

We should probably have a test that involves multiple policies to make sure we handle that correctly.
</blockquote></details>

we do.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java, line 257 at r2](https://reviewable.io:443/reviews/batfish/batfish/648#-L-J5SPg3PkaSPphSg0q:-L-JDi919XPmhHwm8LEv:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/5d349a8a9ee70b51a6e03d077e76d8afffea15e3/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java#L257)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

question came up in discussion: is there a way to not construct two sets by using a right collector?
</blockquote></details>

done

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java, line 257 at r2](https://reviewable.io:443/reviews/batfish/batfish/648#-L-J5Y2dMlUDFQr7jqv-:-L-JE2dWcPP10iRUu-7v:b-5j3n6y) ([raw file](https://github.com/batfish/batfish/blob/5d349a8a9ee70b51a6e03d077e76d8afffea15e3/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java#L257)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

also did you want to use `Predicates.not(RoutingPolicy::isGenerated)` instead? Not sure why to prefer one over the other honestly unless it helps readability.
</blockquote></details>

I decided to use `not` as a static import for maximum readability.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/CallExpr.java, line 32 at r2](https://reviewable.io:443/reviews/batfish/batfish/648#-L-J35caDkH9Aolid0_x:-L-JEx8nBMgHv7fuzS7O:bn5agv9) ([raw file](https://github.com/batfish/batfish/blob/5d349a8a9ee70b51a6e03d077e76d8afffea15e3/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/CallExpr.java#L32)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

maybe add something like "detected at expression <this>", e.g.?
</blockquote></details>

done, and also in `CallStatement`.

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ConfigurationTests.java, line 105 at r2](https://reviewable.io:443/reviews/batfish/batfish/648#-L-J47c1jVoLGzkxF0o-:-L-JGV5wqpO8qalgRDpm:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/5d349a8a9ee70b51a6e03d077e76d8afffea15e3/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ConfigurationTests.java#L105)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

why not check both in the same assertion? maybe, `containsInAnyOrder`? 

also these last two assertions are backwards:

```java
assertThat(thingComputedByYourTestCode, matches(expectation));
```

so it should be something like

```java
assertThat(ospfProcess.getExportPolicySources(), containsInAnyOrder(ospfExportPolicyName, ospfExportSubPolicyName));
```
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/648)*

**Comment by dhalperi** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/648#-:-L-JKPoIlZ-QHGKgvWJ1:bnfp4nl)*

**Pull request merged**
