### PR TITLE
Add metric for static routes

### PR DESCRIPTION
**Pull request by sfraint**
Add metric for static routes in vendor independent model.

### CODE REVIEW

**Comment by progwriter** [comment]
Review status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @sfraint, @haverma, @progwriter, and @dhalperi)

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/StaticRoute.java, line 77 at r1](https://reviewable.io/reviews/batfish/batfish/1701#-LFO-QSZ1GSOc7U_t0p9:-LFO-QSZ1GSOc7U_t0pA:b-8hhb4h) ([raw file](https://github.com/batfish/batfish/blob/42bfb4fb3241768cb7ea9629812bff3fa593c6ba/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/StaticRoute.java#L77)):*
> ```Java
> 
>   @Override
>   @JsonIgnore(false)
> ```

Why not just remove the annotation?

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/StaticRoute.java, line 151 at r1](https://reviewable.io/reviews/batfish/batfish/1701#-LFO-TFpEr6ESJMl0owJ:-LFO-TFpEr6ESJMl0owK:bha9qso) ([raw file](https://github.com/batfish/batfish/blob/42bfb4fb3241768cb7ea9629812bff3fa593c6ba/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/StaticRoute.java#L151)):*
> ```Java
>           _nextHopInterface,
>           _administrativeCost,
>           this.getMetric(),
> ```

I believe `this.` is not required here.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1701)*

**Comment by progwriter** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed, 2 unresolved discussions (waiting on @sfraint, @haverma, and @dhalperi)

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1701)*

**Comment by dhalperi** [comment]
Review status: all files reviewed, 3 unresolved discussions (waiting on @sfraint and @haverma)

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/StaticRoute.java, line 52 at r1](https://reviewable.io/reviews/batfish/batfish/1701#-LFO-i5TCxLMrc2z_5iv:-LFO-i5TCxLMrc2z_5iw:b-ei5gi2) ([raw file](https://github.com/batfish/batfish/blob/42bfb4fb3241768cb7ea9629812bff3fa593c6ba/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/StaticRoute.java#L52)):*
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>

> ```
>   public StaticRoute(
>       @JsonProperty(PROP_NETWORK) Prefix network,
>       @Nullable @JsonProperty(PROP_NEXT_HOP_IP) Ip nextHopIp,
>       @Nullable @JsonProperty(PROP_NEXT_HOP_INTERFACE) String nextHopInterface,
>       @JsonProperty(PROP_ADMINISTRATIVE_COST) int administrativeCost,
>       @JsonProperty(PROP_TAG) int tag) {
>     this(
>         network, nextHopIp, nextHopInterface, administrativeCost, DEFAULT_STATIC_ROUTE_METRIC, tag);
>   }
> ```
</details>


there should only be 1 Json-annotated constructor (and it should have `@JsonCreator` annotation).

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1701)*

**Comment by sfraint** [comment]
Review status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @progwriter, @sfraint, and @haverma)

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/StaticRoute.java, line 52 at r1](https://reviewable.io/reviews/batfish/batfish/1701#-LFO-i5TCxLMrc2z_5iv:-LFODgrxBWY6j_966JUI:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/42bfb4fb3241768cb7ea9629812bff3fa593c6ba/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/StaticRoute.java#L52)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
>   public StaticRoute(
>       @JsonProperty(PROP_NETWORK) Prefix network,
>       @Nullable @JsonProperty(PROP_NEXT_HOP_IP) Ip nextHopIp,
>       @Nullable @JsonProperty(PROP_NEXT_HOP_INTERFACE) String nextHopInterface,
>       @JsonProperty(PROP_ADMINISTRATIVE_COST) int administrativeCost,
>       @JsonProperty(PROP_TAG) int tag) {
>     this(
>         network, nextHopIp, nextHopInterface, administrativeCost, DEFAULT_STATIC_ROUTE_METRIC, tag);
>   }
> ```

there should only be 1 Json-annotated constructor (and it should have `@JsonCreator` annotation).
</blockquote></details>

Done.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/StaticRoute.java, line 77 at r1](https://reviewable.io/reviews/batfish/batfish/1701#-LFO-QSZ1GSOc7U_t0p9:-LFODiLSBsZavjGpez6U:bpbpvnt) ([raw file](https://github.com/batfish/batfish/blob/42bfb4fb3241768cb7ea9629812bff3fa593c6ba/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/StaticRoute.java#L77)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

Why not just remove the annotation?
</blockquote></details>

Was following the style of the rest of the annotated properties in this file.  Removed all of those `false` annotations.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/StaticRoute.java, line 151 at r1](https://reviewable.io/reviews/batfish/batfish/1701#-LFO-TFpEr6ESJMl0owJ:-LFODqUi8pU9ykv5gL_b:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/42bfb4fb3241768cb7ea9629812bff3fa593c6ba/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/StaticRoute.java#L151)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

I believe `this.` is not required here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1701)*

**Comment by progwriter** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haverma)

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1701)*

**Comment by dhalperi** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @sfraint and @haverma)

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/StaticRoute.java, line 28 at r2](https://reviewable.io/reviews/batfish/batfish/1701#-LFOFbeR0cOwTu6cLq65:-LFOFbeR0cOwTu6cLq66:bfbfr1s) ([raw file](https://github.com/batfish/batfish/blob/ec42e3e148317b1360952c0bd1e0a8266220ab22/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/StaticRoute.java#L28)):*
> ```
> public
> ```

This should also be private - it should only be for Jackson to use, not others to call.

Usually, this one will call the default constructor rather than the other way around.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1701)*

**Comment by sfraint** [comment]
Review status: 5 of 6 files reviewed, all discussions resolved (waiting on @progwriter and @haverma)

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/StaticRoute.java, line 28 at r2](https://reviewable.io/reviews/batfish/batfish/1701#-LFOFbeR0cOwTu6cLq65:-LFOYIJI4jghMonqNR-c:bs7wumx) ([raw file](https://github.com/batfish/batfish/blob/ec42e3e148317b1360952c0bd1e0a8266220ab22/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/StaticRoute.java#L28)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> public
> ```

This should also be private - it should only be for Jackson to use, not others to call.

Usually, this one will call the default constructor rather than the other way around.
</blockquote></details>

Done. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1701)*

**Comment by dhalperi** [comment]
Reviewed 5 of 5 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haverma)

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1701)*

**Comment by dhalperi** [comment]
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haverma)

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/StaticRoute.java, line 77 at r4](https://reviewable.io/reviews/batfish/batfish/1701#-LFOw9zo9Slboc9y7pFd:-LFOwV8j4uj7YIJT17U8:bx38lvb) ([raw file](https://github.com/batfish/batfish/blob/7dbd20724d22566c6fd6294f4ff52d3297f0f6f4/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/StaticRoute.java#L77)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

(This one is the one you shouldn't need. But, it's really dumb that we do this at all :p. I can fix in a follow-up PR.)
</blockquote></details>

Wait you do need this, too. NM.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1701)*

**Pull request merged**
