### PR TITLE
feat: add regex to as path access lists

### PR DESCRIPTION
**Pull request by lukaskoenen**
Use a regular expression to match AS_PATH in access-list instead of converting a single integer to a regular expression.

- update lexer / parser
- update conversion
- update tests

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7250)* status: all files reviewed, 6 unresolved discussions (waiting on @lukaskoenen)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4, line 1111 at r1](https://reviewable.io/reviews/batfish/batfish/7250#-MjgfNZC14M8y_84eDah:-MjgfNZDAzYYF_acOh04:br053up) ([raw file](https://github.com/batfish/batfish/blob/40956437099dff0253b1f6f408e3c21f5b258ec3/projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4#L1111)):*
> ```ANTLR
> M_AccessList_DENY
> :
>    'deny' -> type( DENY )
> ```

nit: you don't need to follow the garbage produced by the autoformatter we abandoned.
Can ditch the spaces inside the parentheses.
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrParser.g4, line 42 at r1](https://reviewable.io/reviews/batfish/batfish/7250#-MjgfASyCorJK6eOs40d:-MjgfASyCorJK6eOs40e:b-penbhw) ([raw file](https://github.com/batfish/batfish/blob/40956437099dff0253b1f6f408e3c21f5b258ec3/projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrParser.g4#L42)):*
> ```ANTLR
> ip_as_path
> :
>   AS_PATH ACCESS_LIST name = word action = access_list_action as_path_regex = word NEWLINE
> ```

Is `access_list_action` required by FRR?
___
*[projects/batfish/src/main/java/org/batfish/grammar/cumulus_frr/CumulusFrrConfigurationBuilder.java, line 1782 at r1](https://reviewable.io/reviews/batfish/batfish/7250#-Mjge21CE-vVh6gTaY3C:-Mjge21CE-vVh6gTaY3D:b-lslkb0) ([raw file](https://github.com/batfish/batfish/blob/40956437099dff0253b1f6f408e3c21f5b258ec3/projects/batfish/src/main/java/org/batfish/grammar/cumulus_frr/CumulusFrrConfigurationBuilder.java#L1782)):*
> ```Java
>     if (ctx.PERMIT() != null) {
>       return LineAction.PERMIT;
>     } else if (ctx.DENY() != null) {
> ```

Make this an `else`, and `assert ctx.DENY() != null`. I believe this is guaranteed by the grammar.
No need for the last branch.
___
*[projects/batfish/src/main/java/org/batfish/grammar/cumulus_frr/CumulusFrrConfigurationBuilder.java, line 1795 at r1](https://reviewable.io/reviews/batfish/batfish/7250#-MjgeUYy9nouzJ4K1P4s:-MjgeUYy9nouzJ4K1P4t:bwlneff) ([raw file](https://github.com/batfish/batfish/blob/40956437099dff0253b1f6f408e3c21f5b258ec3/projects/batfish/src/main/java/org/batfish/grammar/cumulus_frr/CumulusFrrConfigurationBuilder.java#L1795)):*
> ```Java
>     String name = ctx.name.getText();
>     LineAction action = toLineAction(ctx.action);
>     String regex = ctx.as_path_regex.getText();
> ```

Is this always treated as a regex? For instance, if you put `4`, does it match `44` or just `4`? If the latter, then `IpAsPathAccessListLine` should be broken up into two classes to be converted separately.
Otherwise this is fine.
___
*[projects/batfish/src/main/java/org/batfish/representation/cumulus/IpAsPathAccessListLine.java, line 29 at r1](https://reviewable.io/reviews/batfish/batfish/7250#-Mjgd8sjBZCG4HNYzQZq:-Mjgd8sjBZCG4HNYzQZr:bdss5g2) ([raw file](https://github.com/batfish/batfish/blob/40956437099dff0253b1f6f408e3c21f5b258ec3/projects/batfish/src/main/java/org/batfish/representation/cumulus/IpAsPathAccessListLine.java#L29)):*
> ```Java
>   public AsPathAccessListLine toAsPathAccessListLine() {
>     String regex = CumulusConversions.toJavaRegex(_regex);
>     return new AsPathAccessListLine(_action, regex);
> ```

`AsPathAccessList` is deprecated, broken in certain circumstances, and will not be fixed.
Please use `AsPathMatchExpr` and associated classes in that package.
See `CiscoXrConverions.AsPathSetElemToAsPathMatchExpr` and related visitors.
___
*[projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java, line 1450 at r1](https://reviewable.io/reviews/batfish/batfish/7250#-Mjger6dAJAP-0DnRVMH:-Mjger6dAJAP-0DnRVMI:bdrgz8g) ([raw file](https://github.com/batfish/batfish/blob/40956437099dff0253b1f6f408e3c21f5b258ec3/projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java#L1450)):*
> ```Java
>   public void testCumulusFrrIpAsPathAccessList() {
>     String name = "NAME";
>     String as1 = "^11111$";
> ```

Rather than modifying this test, make a new one for the syntax you are trying to support.

**Comment by lukaskoenen** [comment]
Hi @arifogel,
first of all thank you for your review. The following is my input on what was addressed. If no comment exists, the suggestion was accepted and implemented.

> _[projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrParser.g4, line 42 at r1](https://reviewable.io/reviews/batfish/batfish/7250#-MjgfASyCorJK6eOs40d:-MjgfASyCorJK6eOs40e:b-penbhw) ([raw file](https://github.com/batfish/batfish/blob/40956437099dff0253b1f6f408e3c21f5b258ec3/projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrParser.g4#L42)):_
> 
> > ```antlr
> > ip_as_path
> > :
> >   AS_PATH ACCESS_LIST name = word action = access_list_action as_path_regex = word NEWLINE
> > ```
> 
> As far as I can tell from the documentation the `access_list_action` is necessary. 
> -> `bgp as-path access-list WORD [seq (0-4294967295)] permit|deny LINE`
>
> _[projects/batfish/src/main/java/org/batfish/grammar/cumulus_frr/CumulusFrrConfigurationBuilder.java, line 1795 at r1](https://reviewable.io/reviews/batfish/batfish/7250#-MjgeUYy9nouzJ4K1P4s:-MjgeUYy9nouzJ4K1P4t:bwlneff) ([raw file](https://github.com/batfish/batfish/blob/40956437099dff0253b1f6f408e3c21f5b258ec3/projects/batfish/src/main/java/org/batfish/grammar/cumulus_frr/CumulusFrrConfigurationBuilder.java#L1795)):_
> 
> > ```java
> >     String name = ctx.name.getText();
> >     LineAction action = toLineAction(ctx.action);
> >     String regex = ctx.as_path_regex.getText();
> > ```
> 
> I've just tested this. When defining the regex as `0` the output included all AS including a `0` so for example `65001`. So it seem the implementation is fine.
> 
> _[projects/batfish/src/main/java/org/batfish/representation/cumulus/IpAsPathAccessListLine.java, line 29 at r1](https://reviewable.io/reviews/batfish/batfish/7250#-Mjgd8sjBZCG4HNYzQZq:-Mjgd8sjBZCG4HNYzQZr:bdss5g2) ([raw file](https://github.com/batfish/batfish/blob/40956437099dff0253b1f6f408e3c21f5b258ec3/projects/batfish/src/main/java/org/batfish/representation/cumulus/IpAsPathAccessListLine.java#L29)):_
> 
> > ```java
> >   public AsPathAccessListLine toAsPathAccessListLine() {
> >     String regex = CumulusConversions.toJavaRegex(_regex);
> >     return new AsPathAccessListLine(_action, regex);
> > ```
> 
> I've only modified the existing class here. My Question therefore is if I should rewrite the whole thing to use `AsPathMatchExpr` or is this something planned from your side.
>
> _[projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java, line 1450 at r1](https://reviewable.io/reviews/batfish/batfish/7250#-Mjger6dAJAP-0DnRVMH:-Mjger6dAJAP-0DnRVMI:bdrgz8g) ([raw file](https://github.com/batfish/batfish/blob/40956437099dff0253b1f6f408e3c21f5b258ec3/projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java#L1450)):_
> 
> > ```java
> >   public void testCumulusFrrIpAsPathAccessList() {
> >     String name = "NAME";
> >     String as1 = "^11111$";
> > ```
> 
> I thought this test case was only there to ensure the correct 
>
>I thought this tests exists to ensure the correct generation of the respective data structure. I have extended the test accordingly with another possible regular expression. While doing so I saw that some required characters led to parsing errors which I also fixed. 
>
> _[projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrParser.g4, line 42 at r1](https://reviewable.io/reviews/batfish/batfish/7250#-MjgfASyCorJK6eOs40d:-MjgfASyCorJK6eOs40e:b-penbhw) ([raw file](https://github.com/batfish/batfish/blob/40956437099dff0253b1f6f408e3c21f5b258ec3/projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrParser.g4#L811)):_
>
>>  ```antlr
>> fragment
>> F_WordChar
>> :
>>   [0-9A-Za-z!@#$^*_=+.;:{}\\[\]|()]
>>   | '-'
>> ;
>> ```
>
> This meant extending the valid characters for the word token. Since I am not sure whether this can lead to problems I would be grateful for feedback.

**Comment by lukaskoenen** [comment]
I've just read the last comment on my other PR and I'm afraid that before doing so I just rebased this PR I hope this does not lead to additional problems.

**Review by arifogel — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7250)* status: all files reviewed, 4 unresolved discussions (waiting on @lukaskoenen)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4, line 1111 at r1](https://reviewable.io/reviews/batfish/batfish/7250#-MjgfNZC14M8y_84eDah:-Mjk-tyo1RNNyOmKlSzE:b-bs2dnl) ([raw file](https://github.com/batfish/batfish/blob/40956437099dff0253b1f6f408e3c21f5b258ec3/projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4#L1111)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

nit: you don't need to follow the garbage produced by the autoformatter we abandoned.
Can ditch the spaces inside the parentheses.
</blockquote></details>

Missed a couple, but no need to spend any more time on it. In the end they are all over the file, and one day when we are bored we will fix in an automated fashion.
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4, line 811 at r3](https://reviewable.io/reviews/batfish/batfish/7250#-Mjk-aL793IzGvtDg3Dw:-Mjk-aL84ApY3OqbzVKN:bxxycaf) ([raw file](https://github.com/batfish/batfish/blob/be20039cea9092195c1235e965662af78bb71e65/projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4#L811)):*
> ```ANTLR
> F_WordChar
> :
>   [0-9A-Za-z!@#$^*_=+.;:{}\\[\]|()]
> ```

I missed this the first time around.
Please do not alter this lexer fragment to make a regex char.

Instead, make and use a separate `fragment F_RegexChar` (and `fragment F_Regex: F_RegexChar+;`)
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4, line 1119 at r3](https://reviewable.io/reviews/batfish/batfish/7250#-Mjk4goL4l352gIrUALV:-Mjk4goL4l352gIrUALW:bfyxfrc) ([raw file](https://github.com/batfish/batfish/blob/be20039cea9092195c1235e965662af78bb71e65/projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4#L1119)):*
> ```ANTLR
> ;
> 
> M_AsPathAccessList_WORD
> ```

Does a regex terminate after a single word? What if you have spaces in the middle? Does it use the whole rest of the line, or just the first word? Is there any form of quoting? Will a regex with spaces never match?
It's fine to defer addressing this question, but if you do, please leave a `// TODO: is it always a single word?` comment or something like that around here.

Also, this should use `F_Regex` as suggested above.
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrParser.g4, line 42 at r1](https://reviewable.io/reviews/batfish/batfish/7250#-MjgfASyCorJK6eOs40d:-Mjk1BpMEx0zM5aWpn_D:b-8cjgq4) ([raw file](https://github.com/batfish/batfish/blob/40956437099dff0253b1f6f408e3c21f5b258ec3/projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrParser.g4#L42)):*
> As far as I can tell from the documentation the access_list_action is necessary.
> -> bgp as-path access-list WORD [seq (0-4294967295)] permit|deny LINE

When I ask if something is required by FRR, I mean, "Is it is accepted in `vtysh` when you type it and hit return? And does the exact line, or something else, appear in the config afterward hitting return?"  I ask because as we are both familiar, there is a disconnect between what is documented and what is implemented. Many vendors even have a disconnect between what is tab-completed, what pops up when you hit `?`, what the box actually accepts, and what the config looks like if you dump it right after entering the command.

While it is possible we had implemented something that was incorrect, we need to be extra careful not to make breaking changes for other users. And this is clearly a breaking change from the syntax we previously allowed.
Please test on the box and share your results.
___
*[projects/batfish/src/main/java/org/batfish/grammar/cumulus_frr/CumulusFrrConfigurationBuilder.java, line 1795 at r1](https://reviewable.io/reviews/batfish/batfish/7250#-MjgeUYy9nouzJ4K1P4s:-Mjk3NTrEwr7hC7RO_DB:b-6a1823) ([raw file](https://github.com/batfish/batfish/blob/40956437099dff0253b1f6f408e3c21f5b258ec3/projects/batfish/src/main/java/org/batfish/grammar/cumulus_frr/CumulusFrrConfigurationBuilder.java#L1795)):*
> I've just tested this. When defining the regex as 0 the output included all AS including a 0 so for example 65001. So it seem the implementation is fine.

:thumbsup: 
___
*[projects/batfish/src/main/java/org/batfish/representation/cumulus/IpAsPathAccessListLine.java, line 29 at r1](https://reviewable.io/reviews/batfish/batfish/7250#-Mjgd8sjBZCG4HNYzQZq:-Mjk3n8N-X4ulMUvaiFv:b-i8ucd3) ([raw file](https://github.com/batfish/batfish/blob/40956437099dff0253b1f6f408e3c21f5b258ec3/projects/batfish/src/main/java/org/batfish/representation/cumulus/IpAsPathAccessListLine.java#L29)):*
> I've only modified the existing class here. My Question therefore is if I should rewrite the whole thing to use AsPathMatchExpr or is this something planned from your side.

A couple things, now that I've looked more closely.
1. Please remove conversion code from this class, and leave it in `CumulusConversions` where it was before. Our current patten is for vendor-specific representation classes to contain data only, and not behavior.
2. The more I look at this, the more I realize we are going to want to optimize this in a way that is unreasonable to ask from an outsider not familiar with the new API. So you can keep your changes as long as they are passing (but again, move the changes to `CumulusConversions`).
___
*[projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java, line 1450 at r1](https://reviewable.io/reviews/batfish/batfish/7250#-Mjger6dAJAP-0DnRVMH:-Mjk7m9j20IraytHZ4x0:b-2a5aho) ([raw file](https://github.com/batfish/batfish/blob/40956437099dff0253b1f6f408e3c21f5b258ec3/projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java#L1450)):*
> I thought this tests exists to ensure the correct generation of the respective data structure. I have extended the test accordingly with another possible regular expression. While doing so I saw that some required characters led to parsing errors which I also fixed (see b65c72a).

Sorry, I misinterpreted the purpose of this test while reviewing late at night.
I see you are adding grammar coverage for different regex strings. This is fine.

**Review by lukaskoenen — COMMENTED** [review]
Hi @arifogel,
thanks again for the detailed Feedback! I've also tried to figure out a way to use `AsPathMatchExpr` instead of `AsPathAccessList` but currently don't see how to integrate the `action`. If I see how, I'm happy to implement this as well.

> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7250)* status: 5 of 8 files reviewed, 4 unresolved discussions (waiting on @arifogel)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4, line 811 at r3](https://reviewable.io/reviews/batfish/batfish/7250#-Mjk-aL793IzGvtDg3Dw:-Mjmio2w2r0TB72099Rj:bpjdz7m) ([raw file](https://github.com/batfish/batfish/blob/be20039cea9092195c1235e965662af78bb71e65/projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4#L811)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

I missed this the first time around.
Please do not alter this lexer fragment to make a regex char.

Instead, make and use a separate `fragment F_RegexChar` (and `fragment F_Regex: F_RegexChar+;`)
</blockquote></details>

I added a new fragment like you suggested. I checked what characters are supported using `vtysh`.
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4, line 1119 at r3](https://reviewable.io/reviews/batfish/batfish/7250#-Mjk4goL4l352gIrUALV:-Mjmj4jd7-UWXiZlKm1w:b-hzrteb) ([raw file](https://github.com/batfish/batfish/blob/be20039cea9092195c1235e965662af78bb71e65/projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4#L1119)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Does a regex terminate after a single word? What if you have spaces in the middle? Does it use the whole rest of the line, or just the first word? Is there any form of quoting? Will a regex with spaces never match?
It's fine to defer addressing this question, but if you do, please leave a `// TODO: is it always a single word?` comment or something like that around here.

Also, this should use `F_Regex` as suggested above.


</blockquote></details>

I've checked this using `vtysh`. Using a space inside the regular expression leads to a `unknown command`.
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrParser.g4, line 42 at r1](https://reviewable.io/reviews/batfish/batfish/7250#-MjgfASyCorJK6eOs40d:-Mjmjl1O79ElUYIaW8VJ:b-qym64w) ([raw file](https://github.com/batfish/batfish/blob/40956437099dff0253b1f6f408e3c21f5b258ec3/projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrParser.g4#L42)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

> As far as I can tell from the documentation the access_list_action is necessary.
> -> bgp as-path access-list WORD [seq (0-4294967295)] permit|deny LINE

When I ask if something is required by FRR, I mean, "Is it is accepted in `vtysh` when you type it and hit return? And does the exact line, or something else, appear in the config afterward hitting return?"  I ask because as we are both familiar, there is a disconnect between what is documented and what is implemented. Many vendors even have a disconnect between what is tab-completed, what pops up when you hit `?`, what the box actually accepts, and what the config looks like if you dump it right after entering the command.

While it is possible we had implemented something that was incorrect, we need to be extra careful not to make breaking changes for other users. And this is clearly a breaking change from the syntax we previously allowed.
Please test on the box and share your results.
</blockquote></details>

Thank you for the clarification! Creating an access-list without `permit|deny` results in an `unknown command`.
___
*[projects/batfish/src/main/java/org/batfish/representation/cumulus/IpAsPathAccessListLine.java, line 29 at r1](https://reviewable.io/reviews/batfish/batfish/7250#-Mjgd8sjBZCG4HNYzQZq:-MjmkOq72XvuBNpJxEnT:bjcj5ds) ([raw file](https://github.com/batfish/batfish/blob/40956437099dff0253b1f6f408e3c21f5b258ec3/projects/batfish/src/main/java/org/batfish/representation/cumulus/IpAsPathAccessListLine.java#L29)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

> I've only modified the existing class here. My Question therefore is if I should rewrite the whole thing to use AsPathMatchExpr or is this something planned from your side.

A couple things, now that I've looked more closely.
1. Please remove conversion code from this class, and leave it in `CumulusConversions` where it was before. Our current patten is for vendor-specific representation classes to contain data only, and not behavior.
2. The more I look at this, the more I realize we are going to want to optimize this in a way that is unreasonable to ask from an outsider not familiar with the new API. So you can keep your changes as long as they are passing (but again, move the changes to `CumulusConversions`).
</blockquote></details>

Moved Conversion to `CumulusConversions`

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 3 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7250)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaskoenen)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4, line 1132 at r5](https://reviewable.io/reviews/batfish/batfish/7250#-MjqDyR3-TGtGuIQu1tS:-MjqDyR3-TGtGuIQu1tT:baej7am) ([raw file](https://github.com/batfish/batfish/blob/f83aadab8e6b0894bf41305a2161c5beade1ed98/projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4#L1132)):*
> ```ANTLR
> ;
> 
> M_AsPathAccessList_REGEX
> ```

nit: please use same suffix as the type you are setting (`REGEX` vs `REGEXP`)

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7250)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaskoenen)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4, line 1132 at r5](https://reviewable.io/reviews/batfish/batfish/7250#-MjqDyR3-TGtGuIQu1tS:-MjqETUO0UtQtPqpPsif:bzcs7x3) ([raw file](https://github.com/batfish/batfish/blob/f83aadab8e6b0894bf41305a2161c5beade1ed98/projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4#L1132)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

nit: please use same suffix as the type you are setting (`REGEX` vs `REGEXP`)
</blockquote></details>

I would suggest changing `REGEXP` -> `REGEX`.
If either `regexp` or `regex` is an FRR keyword, then use something else entirely.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7250)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaskoenen)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4, line 1132 at r5](https://reviewable.io/reviews/batfish/batfish/7250#-MjqDyR3-TGtGuIQu1tS:-MjqEk0I0UGa3LauhGgP:b6bhb5l) ([raw file](https://github.com/batfish/batfish/blob/f83aadab8e6b0894bf41305a2161c5beade1ed98/projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4#L1132)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

I would suggest changing `REGEXP` -> `REGEX`.
If either `regexp` or `regex` is an FRR keyword, then use something else entirely.
</blockquote></details>

I mean if both are

**Review by lukaskoenen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7250)* status: 5 of 8 files reviewed, 1 unresolved discussion (waiting on @arifogel)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4, line 1132 at r5](https://reviewable.io/reviews/batfish/batfish/7250#-MjqDyR3-TGtGuIQu1tS:-MjsUiJU6twlhTxTNvDG:bxtylui) ([raw file](https://github.com/batfish/batfish/blob/f83aadab8e6b0894bf41305a2161c5beade1ed98/projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4#L1132)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

I mean if both are
</blockquote></details>

Hi @arifogel,
I've fixed the suffix and changed `REGEXP` to `REGEX`. I also removed the `regexp` statement from `CumulusFrr_common.g4`, since I don't see a reason why this would be needed (correct me if I'm wrong).

**Review by arifogel — COMMENTED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7250)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaskoenen)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4, line 1132 at r5](https://reviewable.io/reviews/batfish/batfish/7250#-MjqDyR3-TGtGuIQu1tS:-Mk4Cqn9DJUDRNmqCRZc:b-x7l62) ([raw file](https://github.com/batfish/batfish/blob/f83aadab8e6b0894bf41305a2161c5beade1ed98/projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4#L1132)):*
<details><summary><i>Previously, lukaskoenen wrote…</i></summary><blockquote>

Hi @arifogel,
I've fixed the suffix and changed `REGEXP` to `REGEX`. I also removed the `regexp` statement from `CumulusFrr_common.g4`, since I don't see a reason why this would be needed (correct me if I'm wrong).
</blockquote></details>

There is a reason to leave the parser rule that is not worth getting into. The team can address it later when we get a chance clean up this parser. You don't need to worry about it, and can leave as is.

**Review by arifogel — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7250#-:-Mk4DBH34TlObgKOctSt:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaskoenen)

**Pull request merged**
