### PR TITLE
Arista: fix ACL line VSIDs

### PR DESCRIPTION
**Pull request by sfraint**
Fix Standard ACL line conversion/naming to line up with structure definition; fixes VSIDs based on that conversion.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8407)* status: all files reviewed, 1 unresolved discussion (waiting on @sfraint)

___
*[`projects/batfish/src/main/java/org/batfish/representation/arista/StandardAccessListActionLine.java` line 48 at r1](https://reviewable.io/reviews/batfish/batfish/8407#-N5kAziH0ygL4Xt8jVv2:-N5kAziIAUqZ6tcefidh:b-rs1utd) ([raw file](https://github.com/batfish/batfish/blob/07c4077638078efbc4ab450ea74f8c4a2826b0b4/projects/batfish/src/main/java/org/batfish/representation/arista/StandardAccessListActionLine.java#L48)):*
> ```Java
>     return Optional.ofNullable(
>         ExtendedAccessListLine.builder()
>             .setName(String.valueOf(_seq)) // Use sequence number instead of line content (_name)
> ```

`Long.toString(_seq)` is better. No unnecessary null check nor unnecessary auto-boxing.

(Probably java JITs this away, but FYI).



_Code quote:_
```Java
String.valueOf(_seq)
```

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8407)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[`projects/batfish/src/main/java/org/batfish/representation/arista/StandardAccessListActionLine.java` line 48 at r1](https://reviewable.io/reviews/batfish/batfish/8407#-N5kAziH0ygL4Xt8jVv2:-N5kBtDFDRPdnf-n6cp4:b4c9lyr) ([raw file](https://github.com/batfish/batfish/blob/07c4077638078efbc4ab450ea74f8c4a2826b0b4/projects/batfish/src/main/java/org/batfish/representation/arista/StandardAccessListActionLine.java#L48)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

`Long.toString(_seq)` is better. No unnecessary null check nor unnecessary auto-boxing.

(Probably java JITs this away, but FYI).
</blockquote></details>

:thumbsup:

**Review by dhalperi — COMMENTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8407)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8407)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

**Pull request merged**
