### PR TITLE
Cleanup abstract route

### PR DESCRIPTION
**Pull request by progwriter**
- Simplify comparators
- Be more stringent with annotations

### CODE REVIEW

**Comment by arifogel** [comment]
:lgtm: with request to revert `IsisRoute`

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed, 1 unresolved discussion (waiting on @progwriter)

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IsisRoute.java, line 91 at r1](https://reviewable.io/reviews/batfish/batfish/1702#-LFOBjnRD_P2CM1RZFVV:-LFOBjnRD_P2CM1RZFVW:b-puqsqv) ([raw file](https://github.com/batfish/batfish/blob/3447b920b3dbdd8ef8e2fdd892464631e67eeacd/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IsisRoute.java#L91)):*
> ```Java
> 
>   @Override
>   public int routeCompare(@Nonnull AbstractRoute rhs) {
> ```

Please revert this file if possible, as this will only create conflict with ongoing IS-IS PR.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1702#-:-LFOC-6yDtCMvg-PuZQI:b-vzq2mg)*

**Comment by progwriter** [comment]
Review status: 10 of 12 files reviewed, all discussions resolved (waiting on @arifogel)

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IsisRoute.java, line 91 at r1](https://reviewable.io/reviews/batfish/batfish/1702#-LFOBjnRD_P2CM1RZFVV:-LFOES8M5HivJMmVA0ms:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/3447b920b3dbdd8ef8e2fdd892464631e67eeacd/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IsisRoute.java#L91)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Please revert this file if possible, as this will only create conflict with ongoing IS-IS PR.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1702)*

**Comment by arifogel** [comment]
Reviewed 3 of 3 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AbstractRoute.java, line 61 at r1](https://reviewable.io/reviews/batfish/batfish/1702#-LFOLCgMCjtGGMoKiIpt:-LFOLCgNAR3_7pK1Po6U:b6msabj) ([raw file](https://github.com/batfish/batfish/blob/3447b920b3dbdd8ef8e2fdd892464631e67eeacd/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AbstractRoute.java#L61)):*
> ```Java
> 
>   @Override
>   public final int compareTo(@Nonnull AbstractRoute rhs) {
> ```

Why the change? Does this violate the contract of `compareTo`?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1702)*

**Comment by progwriter** [comment]
Review status: 11 of 12 files reviewed, all discussions resolved (waiting on @arifogel)

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AbstractRoute.java, line 61 at r1](https://reviewable.io/reviews/batfish/batfish/1702#-LFOLCgMCjtGGMoKiIpt:-LFONNmd16k9DQODPS7C:bb6un1j) ([raw file](https://github.com/batfish/batfish/blob/3447b920b3dbdd8ef8e2fdd892464631e67eeacd/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AbstractRoute.java#L61)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Why the change? Does this violate the contract of `compareTo`?
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1702)*

**Comment by progwriter** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1702)*

**Comment by dhalperi** [comment]
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AbstractRoute.java, line 61 at r1](https://reviewable.io/reviews/batfish/batfish/1702#-LFOLCgMCjtGGMoKiIpt:-LFONdhLAiAC_QBcsaTm:b9mi27c) ([raw file](https://github.com/batfish/batfish/blob/3447b920b3dbdd8ef8e2fdd892464631e67eeacd/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AbstractRoute.java#L61)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

Done
</blockquote></details>

This change actually correctly reflects the contract of `compareTo` :)

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1702)*

**Comment by arifogel** [comment]
Review status: :shipit: complete! all files reviewed, all discussions resolved

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AbstractRoute.java, line 61 at r1](https://reviewable.io/reviews/batfish/batfish/1702#-LFOLCgMCjtGGMoKiIpt:-LFOOaRwBplu9Fx6hoVz:bkditug) ([raw file](https://github.com/batfish/batfish/blob/3447b920b3dbdd8ef8e2fdd892464631e67eeacd/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AbstractRoute.java#L61)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

This change actually correctly reflects the contract of `compareTo` :)
</blockquote></details>

Which change? Is it good now as I suspect?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1702)*

**Comment by dhalperi** [comment]
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AbstractRoute.java, line 61 at r3](https://reviewable.io/reviews/batfish/batfish/1702#-LFOP3Dg-T_NrcFi7cj8:-LFOP3Dh3b8mHKhGAxUv:bv086tn) ([raw file](https://github.com/batfish/batfish/blob/eea752637417a7e26641923a238272a4f162e9eb/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AbstractRoute.java#L61)):*
> ```Java
> 
>   @Override
>   public final int compareTo(@Nullable AbstractRoute rhs) {
> ```

yeah, this is wrong now.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1702)*

**Comment by progwriter** [comment]
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AbstractRoute.java, line 61 at r1](https://reviewable.io/reviews/batfish/batfish/1702#-LFOLCgMCjtGGMoKiIpt:-LFOOuSMBipo2dPuPcRN:b-19qlru) ([raw file](https://github.com/batfish/batfish/blob/3447b920b3dbdd8ef8e2fdd892464631e67eeacd/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AbstractRoute.java#L61)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Which change? Is it good now as I suspect?
</blockquote></details>

https://docs.oracle.com/javase/8/docs/api/java/lang/Comparable.html

compareTo does not take `null`. so with `@ParametersAreNonnullByDefault` this should have no annotation

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1702)*

**Comment by dhalperi** [comment]
Reviewed 1 of 1 files at r4.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AbstractRoute.java, line 61 at r3](https://reviewable.io/reviews/batfish/batfish/1702#-LFOP3Dg-T_NrcFi7cj8:-LFOPHJh-BAduIKmQxoi:bo9si3m) ([raw file](https://github.com/batfish/batfish/blob/eea752637417a7e26641923a238272a4f162e9eb/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AbstractRoute.java#L61)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

yeah, this is wrong now.
</blockquote></details>

Oklay, NOW it's fixed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1702)*

**Comment by arifogel** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1702)*

**Comment by arifogel** [comment]
Reviewed 1 of 1 files at r4.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1702)*

**Pull request merged**
