### PR TITLE
FortiOS: Better policy conversion

### PR DESCRIPTION
**Pull request by corinaminer**
Incorporates zones and fixes a bug where we were using `DeniedByAcl` but only wanted to match traffic explicitly denied by the ACL. Easiest to review the first two commits first, separately; the first commit is just the changes in #6743, and the second commit just refactors `convertPolicy` into  separate `FortiosPolicyConversions` file.

The policy conversion structure is now modeled closely after Palo Alto's. There are two main steps:
1. Generate all the cross-zone policies. These policies are generated ACLs specific to traffic from one zone or interface to another (or to the same one). Each cross-zone policy has one `AclLine` representing each applicable policy (excluding disabled and IPSEC policies), followed by one line to apply the default action. They do NOT reflect the policies' src/dst interface/zone matching.
2. Generate an outgoing policy for each zone and unzoned interface. These outgoing policies contain two lines for each cross-zone policy with the outgoing zone/interface as its "to" zone/interface:
    ```
    permit and(from the CZP's source zone, permitted by the CZP)
    deny and(from the CZP's source zone, denied by the CZP)
    ```
    These two lines will match all traffic from the cross-zone policy's source zone (or interface), and with all cross-zone policies pointed to the outgoing zone/interface built into the outgoing filter this way, traffic from any source interface is guaranteed to match something. There is one more line in the outgoing filter to handle traffic originating from the device (not actually sure what the correct behavior is for that; there's a todo).

Once those two steps are completed, all the necessary IpAccessLists exist. Finally, in interface conversion, each interface just looks up its outgoing filter in the VI config's ACLs.

### CODE REVIEW

**Review by sfraint — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 2 of 2 files at r2, 10 of 10 files at r3, 1 of 1 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6744)* status: all files reviewed, 4 unresolved discussions (waiting on @arifogel and @corinaminer)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6744#-MW0ldxr52anFcfQXYu4:-MW0ldxr52anFcfQXYu5:b-30ck27) (no related file):*
need more tests: several for policies with zones, trace elements, warnings, etc.

but feel free to split off additional work into other PR(s) to unblock other work sooner

---
___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosPolicyConversions.java, line 65 at r3](https://reviewable.io/reviews/batfish/batfish/6744#-MW0IHRN5WrIV6bgJCTn:-MW0IHRN5WrIV6bgJCTo:b-inqeuy) ([raw file](https://github.com/batfish/batfish/blob/99dd95a02294048ff4415878ad81bf1b54c6039c/projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosPolicyConversions.java#L65)):*
> ```
> given supplied definitions for all {@code sharedGateways} and {@code virtualSystems}
> ```
update docstring
___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosPolicyConversions.java, line 72 at r3](https://reviewable.io/reviews/batfish/batfish/6744#-MW0ZmEy-AnBi0LsOzkl:-MW0ZmEy-AnBi0LsOzkm:bhel4v5) ([raw file](https://github.com/batfish/batfish/blob/99dd95a02294048ff4415878ad81bf1b54c6039c/projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosPolicyConversions.java#L72)):*
> ```
>     // TODO Should originated traffic always be rejected? Is it subject to default intrazone action?
>     lines.add(ExprAclLine.rejecting().setMatchCondition(ORIGINATING_FROM_DEVICE).build());
> ```
if anything, I'd assume we should add this after/at the end of cross-zone rules

with that said, we do need to confirm actual device behavior at some point
___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosPolicyConversions.java, line 280 at r5](https://reviewable.io/reviews/batfish/batfish/6744#-MW0jlcG4jq5sOVuuDJU:-MW0jlcG4jq5sOVuuDJV:bbjdi93) ([raw file](https://github.com/batfish/batfish/blob/9860636cf1cbc2cfe5f209a68444cb6a7e844e27/projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosPolicyConversions.java#L280)):*
> ```
>     String numAndName = name == null ? number : String.format("%s (%s)", number, name);
> ```
should this be centralized in a `compute...Name` function?

also, any reason for it to be different than the text that shows up in the trace (`1234 named foobar`)
___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosPolicyConversions.java, line 303 at r5](https://reviewable.io/reviews/batfish/batfish/6744#-MW0kLDj-LmyItUWjbAF:-MW0kLDj-LmyItUWjbAG:bcj82o6) ([raw file](https://github.com/batfish/batfish/blob/9860636cf1cbc2cfe5f209a68444cb6a7e844e27/projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosPolicyConversions.java#L303)):*
> ```
>     // Make sure references were finalized
>     assert srcAddrs != null && dstAddrs != null && services != null;
> ```
somewhere,  we need to check the `srcintfZones` and `dst...Zones` were finalized / non-null, maybe here?
___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosTraceElementCreators.java, line 71 at r3](https://reviewable.io/reviews/batfish/batfish/6744#-MW0a-PLDH6o0dcItg3W:-MW0a-PMDWjNTcoyxrSl:b-h256fc) ([raw file](https://github.com/batfish/batfish/blob/99dd95a02294048ff4415878ad81bf1b54c6039c/projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosTraceElementCreators.java#L71)):*
> ```
> "accepted"
> ```
for anything user-facing, we should stick to `allowed`/`denied` wording to match the device wording

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6744)* status: all files reviewed, 5 unresolved discussions (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosPolicyConversions.java, line 218 at r5](https://reviewable.io/reviews/batfish/batfish/6744#-MW1fFnV1jjxqmOPltUA:-MW1fFnV1jjxqmOPltUB:b-sryops) ([raw file](https://github.com/batfish/batfish/blob/9860636cf1cbc2cfe5f209a68444cb6a7e844e27/projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosPolicyConversions.java#L218)):*
> ```
> return String.format("%s~%s~intrazone", fromType, from);
> ```
also, any reason to special-case this generated name?

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6744)* status: all files reviewed, 6 unresolved discussions (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosPolicyConversions.java, line 220 at r5](https://reviewable.io/reviews/batfish/batfish/6744#-MW1lRDN763bmjHJKmHr:-MW1lRDh-qRKIUrOERvh:b-o6oyho) ([raw file](https://github.com/batfish/batfish/blob/9860636cf1cbc2cfe5f209a68444cb6a7e844e27/projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosPolicyConversions.java#L220)):*
> ```
>     return String.format("%s~%s~to~%s~%s", fromType, from, toType, to);
> ```
additionally, this isn't sticking to the canonical cross-zone filter name scheme (`zone~NAME1~to~zone~NAME2`)

is that intentional? is it okay / is that going to make our lives more complicated?

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6744)* status: 9 of 11 files reviewed, 3 unresolved discussions (waiting on @arifogel and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosPolicyConversions.java, line 72 at r3](https://reviewable.io/reviews/batfish/batfish/6744#-MW0ZmEy-AnBi0LsOzkl:-MW1qy6jCIBCuWNT8_4i:b-86x425) ([raw file](https://github.com/batfish/batfish/blob/99dd95a02294048ff4415878ad81bf1b54c6039c/projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosPolicyConversions.java#L72)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
>     // TODO Should originated traffic always be rejected? Is it subject to default intrazone action?
>     lines.add(ExprAclLine.rejecting().setMatchCondition(ORIGINATING_FROM_DEVICE).build());
> ```
if anything, I'd assume we should add this after/at the end of cross-zone rules

with that said, we do need to confirm actual device behavior at some point
</blockquote></details>

It shouldn't matter if this is at the beginning or end of cross-zone rules, because the cross-zone rules can only match traffic from specific source interfaces (which is mutually exclusive with traffic that can match `ORIGINATING_FROM_DEVICE`). But it's conceivable that originating traffic should be subjected to the intrazone filter; updated comment.
___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosPolicyConversions.java, line 218 at r5](https://reviewable.io/reviews/batfish/batfish/6744#-MW1fFnV1jjxqmOPltUA:-MW1vFMjCN0r9hq3VgGh:b-nw3xfn) ([raw file](https://github.com/batfish/batfish/blob/9860636cf1cbc2cfe5f209a68444cb6a7e844e27/projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosPolicyConversions.java#L218)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
> return String.format("%s~%s~intrazone", fromType, from);
> ```
also, any reason to special-case this generated name?
</blockquote></details>

Not really, just didn't see a reason not to, and figured that clearer filter names are better.
___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosPolicyConversions.java, line 220 at r5](https://reviewable.io/reviews/batfish/batfish/6744#-MW1lRDN763bmjHJKmHr:-MW1rh-2AJnGmmIlZaok:b-2y5dji) ([raw file](https://github.com/batfish/batfish/blob/9860636cf1cbc2cfe5f209a68444cb6a7e844e27/projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosPolicyConversions.java#L220)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
>     return String.format("%s~%s~to~%s~%s", fromType, from, toType, to);
> ```
additionally, this isn't sticking to the canonical cross-zone filter name scheme (`zone~NAME1~to~zone~NAME2`)

is that intentional? is it okay / is that going to make our lives more complicated?
</blockquote></details>

I think it's ok. It shouldn't make our lives more complicated; nothing relies on VI filters being named in a specific way across all vendors (and nothing should need to). This method is public, and if some VI code needs to identify a FortiOS cross-zone filter later, it can use this method to look up the right name.

Also, i'll note that it is still the canonical form if both structures are zones; i just figured it'd be confusing to have filters named `zone~IFACE1~to~zone~IFACE2`.
___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosPolicyConversions.java, line 280 at r5](https://reviewable.io/reviews/batfish/batfish/6744#-MW0jlcG4jq5sOVuuDJU:-MW1tQYE6_w_g0xeypMy:b-19153) ([raw file](https://github.com/batfish/batfish/blob/9860636cf1cbc2cfe5f209a68444cb6a7e844e27/projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosPolicyConversions.java#L280)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
>     String numAndName = name == null ? number : String.format("%s (%s)", number, name);
> ```
should this be centralized in a `compute...Name` function?

also, any reason for it to be different than the text that shows up in the trace (`1234 named foobar`)
</blockquote></details>

This code isn't new in this PR (just moved out of `FortiosConfiguration`), so i'm going to leave it for now. the reason why there's no centralized function for this is because `numAndName` is only used in warnings, and the warnings that use it are only in this function. could reasonably have a function to compute it, or use the text from a trace, but i think it's OK as-is
___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosPolicyConversions.java, line 303 at r5](https://reviewable.io/reviews/batfish/batfish/6744#-MW0kLDj-LmyItUWjbAF:-MW1uePSEl3gH7REknB9:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/9860636cf1cbc2cfe5f209a68444cb6a7e844e27/projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosPolicyConversions.java#L303)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
>     // Make sure references were finalized
>     assert srcAddrs != null && dstAddrs != null && services != null;
> ```
somewhere,  we need to check the `srcintfZones` and `dst...Zones` were finalized / non-null, maybe here?
</blockquote></details>

done
___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosTraceElementCreators.java, line 71 at r3](https://reviewable.io/reviews/batfish/batfish/6744#-MW0a-PLDH6o0dcItg3W:-MW1v6QhAo3ryDOZz0Uz:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/99dd95a02294048ff4415878ad81bf1b54c6039c/projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosTraceElementCreators.java#L71)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
> "accepted"
> ```
for anything user-facing, we should stick to `allowed`/`denied` wording to match the device wording
</blockquote></details>

done

**Review by sfraint — COMMENTED** [review]
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6744)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosPolicyConversions.java, line 72 at r3](https://reviewable.io/reviews/batfish/batfish/6744#-MW0ZmEy-AnBi0LsOzkl:-MW5hMUHDVNm1qA3O5hJ:b4c9lyr) ([raw file](https://github.com/batfish/batfish/blob/99dd95a02294048ff4415878ad81bf1b54c6039c/projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosPolicyConversions.java#L72)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

It shouldn't matter if this is at the beginning or end of cross-zone rules, because the cross-zone rules can only match traffic from specific source interfaces (which is mutually exclusive with traffic that can match `ORIGINATING_FROM_DEVICE`). But it's conceivable that originating traffic should be subjected to the intrazone filter; updated comment.
</blockquote></details>

:thumbsup: 
___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosPolicyConversions.java, line 280 at r5](https://reviewable.io/reviews/batfish/batfish/6744#-MW0jlcG4jq5sOVuuDJU:-MW5mqQVEk8eYNMSxp9F:b-ne11sj) ([raw file](https://github.com/batfish/batfish/blob/9860636cf1cbc2cfe5f209a68444cb6a7e844e27/projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosPolicyConversions.java#L280)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

This code isn't new in this PR (just moved out of `FortiosConfiguration`), so i'm going to leave it for now. the reason why there's no centralized function for this is because `numAndName` is only used in warnings, and the warnings that use it are only in this function. could reasonably have a function to compute it, or use the text from a trace, but i think it's OK as-is
</blockquote></details>

ack; I definitely prefer consistent naming across warnings and TraceElements, but we can just do that separately

**Review by sfraint — COMMENTED** [review]
> Reviewed 2 of 2 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6744)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel and @sfraint)

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6744)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosPolicyConversions.java, line 220 at r5](https://reviewable.io/reviews/batfish/batfish/6744#-MW1lRDN763bmjHJKmHr:-MW67b7A28YvG979H0sL:byjgx6e) ([raw file](https://github.com/batfish/batfish/blob/9860636cf1cbc2cfe5f209a68444cb6a7e844e27/projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosPolicyConversions.java#L220)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

I think it's ok. It shouldn't make our lives more complicated; nothing relies on VI filters being named in a specific way across all vendors (and nothing should need to). This method is public, and if some VI code needs to identify a FortiOS cross-zone filter later, it can use this method to look up the right name.

Also, i'll note that it is still the canonical form if both structures are zones; i just figured it'd be confusing to have filters named `zone~IFACE1~to~zone~IFACE2`.
</blockquote></details>

discussed offline, decided it's ok to leave as-is for now at least

**Pull request merged**
