### PR TITLE
clear cached configuration in reachability question

### LINKED ISSUE #335: Error running reduced reachability twice in a row
Command log:

```
init-testrig test_rigs/example
get environmentcreation interfaceBlacklist=[{hostname="as2border2",interface="GigabitEthernet0/0"}]
get reachability type=reduced
get reachability type=reduced
```

the first time the get command succeeds, the second time it fails:

```
WMS:getObject tr_040c5622-9146-437d-ac75-3b94d591c877 --> 557cc005-da67-4472-823e-e608f6137813.log
200 OK InboundJaxrsResponse{context=ClientResponse{method=POST, uri=http://localhost:9997/batfishworkmgr/getobject, status=200, reason=OK}}
org.batfish.common.QuestionException: Exception answering question
	at org.batfish.datamodel.answers.Answer.append(Answer.java:42)
	at org.batfish.main.Batfish.run(Batfish.java:3861)
	at org.batfish.main.Driver$1.run(Driver.java:370)
Caused by: org.batfish.common.BatfishException: Failed to answer question
	at org.batfish.main.Batfish.answer(Batfish.java:536)
	... 2 more
Caused by: org.batfish.common.BatfishException: Cannot disable non-existent interface 'GigabitEthernet0/0' on node 'as2border2'

	at org.batfish.main.Batfish.processInterfaceBlacklist(Batfish.java:3378)
	at org.batfish.main.Batfish.loadConfigurations(Batfish.java:2406)
	at org.batfish.main.Batfish.reducedReachability(Batfish.java:3591)
	at org.batfish.question.ReachabilityQuestionPlugin$ReachabilityAnswerer.reducedReachability(ReachabilityQuestionPlugin.java:77)
	at org.batfish.question.ReachabilityQuestionPlugin$ReachabilityAnswerer.answerDiff(ReachabilityQuestionPlugin.java:57)
	at org.batfish.main.Batfish.answer(Batfish.java:531)
	... 2 more
```

### PR DESCRIPTION
**Pull request by kidsbear**
For issues #335. Cause: The function call [synthesizeDataPlane](https://github.com/batfish/batfish/blob/master/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L3502) calls the constructor of [Synthesizer](https://github.com/batfish/batfish/blob/master/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L4224), which will modify the configurations in cachedConfiguration, [code here](https://github.com/batfish/batfish/blob/master/projects/batfish/src/main/java/org/batfish/z3/Synthesizer.java#L909). The next reachability question loads the configurations from [cachedConfiguration](https://github.com/batfish/batfish/blob/master/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L2311), which is actually been modified in the previous call. Solution: clear cachedConfiguration before returning from methods which could modify the configurations. 
This fixes #335

### CODE REVIEW

**Comment by kidsbear** [comment]
Since get reachability command takes long time to run on example testrig, I created a small testrig with 2 configs for testing. The second get reachability will throw exception without the modifications.

**Comment by dhalperi** [comment]
Probably Ari is best to review this. If we have to clear the cache for many runs, it may be that the cache is currently used incorrectly. Let's discuss, once Ari has a chance to review.

**Comment by dhalperi** [comment]
Ari will take a look at this once he's back from travel.

**Comment by kidsbear** [comment]
Will be handled by Ari~ Close now~

**Pull request closed without merging**
