### PR TITLE
Batfish: minor cleanup / code deduplication

### PR DESCRIPTION
**Pull request by dhalperi**
A step on the way to rationalizing the output code that @corinaminer worked on earlier this week.

---
This change is [Reviewable](https://reviewable.io/reviews/batfish/batfish/711)

### CODE REVIEW

**Comment by corinaminer** [comment]
Would you rather I wait to review until Travis is passing?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/711#-:-L-npfQJh0IMNj0wrmJc:bynsm63)*

**Comment by dhalperi** [comment]
Travis isn't passing because of a bug somewhere else that this PR exposed. (See #721). It should be ready for review now, although obviously I can't merge until the bug underlying 721 is handled.

**Comment by corinaminer** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 2655 at r1](https://reviewable.io:443/reviews/batfish/batfish/711#-L-rPl6Hnd-WZBGISuXo:-L-rPl6Hnd-WZBGISuXp:b65umpn) ([raw file](https://github.com/batfish/batfish/blob/558a18443ca5901c70354e4dffa8470a96687eb6/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L2655)):*
> ```Java
>   }
> 
>   private void outputAnswer(Answer answer) {
> ```

Should this be private? Seems like it ought to be the public handle for outputting an answer without a log.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/711)*

**Comment by dhalperi** [comment]
*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 2655 at r1](https://reviewable.io:443/reviews/batfish/batfish/711#-L-rPl6Hnd-WZBGISuXo:-L-rVn97Sil5FlU8KAYI:bocf0kg) ([raw file](https://github.com/batfish/batfish/blob/558a18443ca5901c70354e4dffa8470a96687eb6/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L2655)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Should this be private? Seems like it ought to be the public handle for outputting an answer without a log.
</blockquote></details>

AFAICT the only code that should be outputting answers is already in this class.

Though one could imagine that such code should soon move elsewhere ;). By locking it down now we are just guaranteeing that calls won't proliferate in such a way that makes the later cleanup work harder.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/711)*

**Comment by corinaminer** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 2655 at r1](https://reviewable.io:443/reviews/batfish/batfish/711#-L-rPl6Hnd-WZBGISuXo:-L-rXgiIRayeTyVDRLlt:b-5vksrc) ([raw file](https://github.com/batfish/batfish/blob/558a18443ca5901c70354e4dffa8470a96687eb6/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L2655)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

AFAICT the only code that should be outputting answers is already in this class.

Though one could imagine that such code should soon move elsewhere ;). By locking it down now we are just guaranteeing that calls won't proliferate in such a way that makes the later cleanup work harder.
</blockquote></details>

So then why do we want `outputAnswerWithLog` to be public?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/711)*

**Comment by dhalperi** [comment]
*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 2655 at r1](https://reviewable.io:443/reviews/batfish/batfish/711#-L-rPl6Hnd-WZBGISuXo:-L-rYcepTvclAIJhZRO7:b6n2uml) ([raw file](https://github.com/batfish/batfish/blob/558a18443ca5901c70354e4dffa8470a96687eb6/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L2655)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

So then why do we want `outputAnswerWithLog` to be public?
</blockquote></details>

It is currently used outside of this class.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/711)*

**Comment by dhalperi** [comment]
*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 2655 at r1](https://reviewable.io:443/reviews/batfish/batfish/711#-L-rPl6Hnd-WZBGISuXo:-L-rYh00gGiQTApBuC6U:b-hso1o7) ([raw file](https://github.com/batfish/batfish/blob/558a18443ca5901c70354e4dffa8470a96687eb6/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L2655)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

It is currently used outside of this class.
</blockquote></details>

"Want" is a strong word -- just making this as locked down as they can be now without changing too much.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/711)*

**Comment by corinaminer** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 2655 at r1](https://reviewable.io:443/reviews/batfish/batfish/711#-L-rPl6Hnd-WZBGISuXo:-L-rYrFJiKh1-3Pvg-Ec:bltrbhr) ([raw file](https://github.com/batfish/batfish/blob/558a18443ca5901c70354e4dffa8470a96687eb6/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L2655)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

"Want" is a strong word -- just making this as locked down as they can be now without changing too much.
</blockquote></details>

OK gotcha

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/711)*

**Pull request merged**
