### PR TITLE
ignore deleted aws vpc peering connections, add test

### LINKED ISSUE #705: AWS VpcPeeringConnections parser error
If the VpcPeeringConnections-<region>.json file has a stanza for Acceptor and Requestor VPC info, which is missing the CidrBlock entry

   "CidrBlock": "10.194.0.0/16", 
    "CidrBlockSet": [
     {
      "CidrBlock": "10.194.0.0/16"
     }

then it fails. This scenario could arise if the VpcPeeringConnection was deleted (as shown below):

{
   "AccepterVpcInfo": {
    "OwnerId": "118292266645", 
    "VpcId": "vpc-6ee90d17"
   }, 
   "RequesterVpcInfo": {
    "OwnerId": "118292266645", 
    "VpcId": "vpc-56c5212f"
   }, 
   "Status": {
    "Code": "deleted", 
    "Message": "Deleted by 118292266645"
   },

### PR DESCRIPTION
**Pull request by arifogel**
Fixes #705

---
This change is [Reviewable](https://reviewable.io/reviews/batfish/batfish/707)

### CODE REVIEW

**Comment by dhalperi** [comment]
:lgtm:

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish/src/test/java/org/batfish/grammar/aws/AwsParsingTests.java, line 22 at r1](https://reviewable.io:443/reviews/batfish/batfish/707#-L-jhCtqqoQqpjJUL3MY:-L-jhCtqqoQqpjJUL3MZ:bt5mb5p) ([raw file](https://github.com/batfish/batfish/blob/291fbcfef5e3788ba26865729eb8af5b2c8df997/projects/batfish/src/test/java/org/batfish/grammar/aws/AwsParsingTests.java#L22)):*
> ```Java
> import org.junit.rules.TemporaryFolder;
> 
> public class AwsParsingTests {
> ```

Name the test class by the code under test: `AwsVpcConfigurationTest` in this case, I think. This convention makes a clear connection between code and how it's tested -- otherwise it's hard to tell which tests are for which code.

---

*[projects/batfish/src/test/java/org/batfish/main/BatfishTestUtils.java, line 74 at r1](https://reviewable.io:443/reviews/batfish/batfish/707#-L-jgts2_KSkbVmK9cV1:-L-jgts2_KSkbVmK9cV2:buxvw5u) ([raw file](https://github.com/batfish/batfish/blob/291fbcfef5e3788ba26865729eb8af5b2c8df997/projects/batfish/src/test/java/org/batfish/main/BatfishTestUtils.java#L74)):*
> ```Java
>   private static Batfish initBatfishFromTestrigText(
>       @Nullable SortedMap<String, String> configurationText,
>       @Nullable SortedMap<String, String> awsText,
> ```

Note: this type of thing can't be sustainable. We can't add 1 parameter per thing that we support and then have to change all callers every time.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/707#-:-L-jhoHAX2f6SbUtVhWa:bnfp4nl)*

**Comment by arifogel** [comment]
I added a bunch of refactoring of testrig initialization in junit tests. This can probably be split off into another PR. Let me know if you'd like me to do so. It may block the rest of this PR.

---

Review status: 2 of 11 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/707#-:-L-kZ0Bkbh8V9fUP5mRp:b-lvbwa0)*

**Comment by arifogel** [comment]
Review status: 2 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish/src/test/java/org/batfish/grammar/aws/AwsVpcConfigurationTest.java, line 22 at r1](https://reviewable.io:443/reviews/batfish/batfish/707#-L-jhCtqqoQqpjJUL3MY:-L-mM8RR3Mxzr0p01XxY:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/291fbcfef5e3788ba26865729eb8af5b2c8df997/projects/batfish/src/test/java/org/batfish/grammar/aws/AwsVpcConfigurationTest.java#L22)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Name the test class by the code under test: `AwsVpcConfigurationTest` in this case, I think. This convention makes a clear connection between code and how it's tested -- otherwise it's hard to tell which tests are for which code.
</blockquote></details>

Done.

---

*[projects/batfish/src/test/java/org/batfish/main/BatfishTestUtils.java, line 74 at r1](https://reviewable.io:443/reviews/batfish/batfish/707#-L-jgts2_KSkbVmK9cV1:-L-mLsnUpzRmcqa5zRg5:b-ws0aff) ([raw file](https://github.com/batfish/batfish/blob/291fbcfef5e3788ba26865729eb8af5b2c8df997/projects/batfish/src/test/java/org/batfish/main/BatfishTestUtils.java#L74)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Note: this type of thing can't be sustainable. We can't add 1 parameter per thing that we support and then have to change all callers every time.
</blockquote></details>

I used a scalable discipline here.
I cleaned up all other usages in #715, which includes this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/707)*

**Comment by dhalperi** [comment]
:lgtm:

---

Reviewed 6 of 11 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/707#-:-L-mb-SL1K-zjpSkSLs4:bnfp4nl)*

**Pull request merged**
