### PR TITLE
CheckPoint: cluster member policy inheritance

### PR DESCRIPTION
**Pull request by sfraint**
For cluster members, apply the policy from the cluster.

### CODE REVIEW

**Review by corinaminer — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7653)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java, line 641 at r2](https://reviewable.io/reviews/batfish/batfish/7653#-MngICQZA67loBhJdFOv:-MngICQZA67loBhJdFOw:bqjqsbs) ([raw file](https://github.com/batfish/batfish/blob/7bbd4f313cc51c71eebde56b61a46fddbd533048/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java#L641)):*
> ```Java
>         cluster.isPresent()
>             ? cluster.get().getPolicy().getAccessPolicyName()
>             : gateway.getPolicy().getAccessPolicyName();
> ```

did we determine that the cluster member *can't* have a policy configured? or have we just not seen that?

If the latter, I think we should at least check and warn if a policy is configured on the cluster member

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7653)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java, line 641 at r2](https://reviewable.io/reviews/batfish/batfish/7653#-MngICQZA67loBhJdFOv:-MngJ_3a16pZwxAQR5VQ:b-sycogf) ([raw file](https://github.com/batfish/batfish/blob/7bbd4f313cc51c71eebde56b61a46fddbd533048/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java#L641)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

did we determine that the cluster member *can't* have a policy configured? or have we just not seen that?

If the latter, I think we should at least check and warn if a policy is configured on the cluster member
</blockquote></details>

It sounds like the policy should be defined on the cluster object.  So, the members should never have policies directly attached.

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7653)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java, line 641 at r2](https://reviewable.io/reviews/batfish/batfish/7653#-MngICQZA67loBhJdFOv:-MngV5Q40wvhE1icSHnB:b5xf2zd) ([raw file](https://github.com/batfish/batfish/blob/7bbd4f313cc51c71eebde56b61a46fddbd533048/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java#L641)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

It sounds like the policy should be defined on the cluster object.  So, the members should never have policies directly attached.
</blockquote></details>

ok, easy enough to change later if we were to out differently

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7653)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java, line 641 at r2](https://reviewable.io/reviews/batfish/batfish/7653#-MngICQZA67loBhJdFOv:-MngVFiK-fdAQ8T3VYqn:b-2o8es4) ([raw file](https://github.com/batfish/batfish/blob/7bbd4f313cc51c71eebde56b61a46fddbd533048/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java#L641)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

ok, easy enough to change later if we were to out differently
</blockquote></details>

*find out

**Pull request merged**
