### PR TITLE
IPv6: remove VI constructs and stop converting to them

### PR DESCRIPTION
**Pull request by dhalperi**
- Delete IPv6-related filtering and routing constructs from VI model
- Deprecate (but leave alone) properties related to them
- Mostly leave VS models intact, but remove conversion.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8400)* status: 0 of 105 files reviewed, 2 unresolved discussions (waiting on @arifogel and @dhalperi)

___
*[`projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java` line 8474 at r1](https://reviewable.io/reviews/batfish/batfish/8400#-N5Hn6UgAJbm_d2uEdgQ:-N5Hn6UgAJbm_d2uEdgR:b-ce2mra) ([raw file](https://github.com/batfish/batfish/blob/9a9f32ade32aa530ed6ce8a60595432f179ae6d8/projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java#L8474)):*
> ```Java
>       } else {
>         return new RoutePolicyInlinePrefixSet(prefixSpace);
>       }
> ```

@arifogel - can these not be mixed? (existing issue, unchanged)



_Code quote:_
```Java
      if (!entriesV6.isEmpty()) {
        return new RoutePolicyInlinePrefix6Set(entriesV6);
      } else {
        return new RoutePolicyInlinePrefixSet(prefixSpace);
      }
```
___
*[`projects/batfish/src/main/java/org/batfish/representation/cisco_xr/RoutePolicyInlinePrefix6Set.java` line 13 at r1](https://reviewable.io/reviews/batfish/batfish/8400#-N5Hnroj4w0LRW2EfRe-:-N5Hnroj4w0LRW2EfRe0:b-ygdwze) ([raw file](https://github.com/batfish/batfish/blob/756b9fa797b9c0001bf29b51d88a8571e80222db/projects/batfish/src/main/java/org/batfish/representation/cisco_xr/RoutePolicyInlinePrefix6Set.java#L13)):*
> ```Java
> public class RoutePolicyInlinePrefix6Set extends RoutePolicyPrefixSet {
> 
>   private Prefix6Space _prefix6Space;
> ```

FYI since I deleted open source `Prefix6Space` I just added a simple VS representation that's closer to what the configs had anyway.
___
*[`projects/batfish/src/main/java/org/batfish/representation/cisco_xr/RoutePolicyNextHopIP6.java` line 22 at r1](https://reviewable.io/reviews/batfish/batfish/8400#-N5Ho1kf9nB3nCauWOzQ:-N5Ho1kf9nB3nCauWOzR:biwmehq) ([raw file](https://github.com/batfish/batfish/blob/9a9f32ade32aa530ed6ce8a60595432f179ae6d8/projects/batfish/src/main/java/org/batfish/representation/cisco_xr/RoutePolicyNextHopIP6.java#L22)):*
> ```Java
>   @Override
>   public NextHopExpr toNextHopExpr(CiscoXrConfiguration cc, Configuration c, Warnings w) {
>     return null;
> ```

I think this needs more.



_Code quote:_
```Java
return null;
```

**Review by arifogel — COMMENTED** [review]
> Reviewed 105 of 105 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8400)* status: all files reviewed, 3 unresolved discussions (waiting on @dhalperi)

___
*[`projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java` line 8474 at r1](https://reviewable.io/reviews/batfish/batfish/8400#-N5Hn6UgAJbm_d2uEdgQ:-N5I8SGx8aRaowy4QUyf:bzbfo0k) ([raw file](https://github.com/batfish/batfish/blob/9a9f32ade32aa530ed6ce8a60595432f179ae6d8/projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java#L8474)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

@arifogel - can these not be mixed? (existing issue, unchanged)
</blockquote></details>

I believe you cannot commit a combo.
___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java` line 994 at r1](https://reviewable.io/reviews/batfish/batfish/8400#-N5IBfZ68bpabVLreNfY:-N5IBfZ68bpabVLreNfZ:bhideof) ([raw file](https://github.com/batfish/batfish/blob/756b9fa797b9c0001bf29b51d88a8571e80222db/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java#L994)):*
> ```Java
>    * Set the {@link LocationInfo} for {@link Location locations} on this node. Any missing locations
>    * will have their {@link LocationInfo} created automatically. See {@link
>    * org.batfish.specifier.LocationInfoUtils#computeLocationInfo(Map)}.
> ```

This change on purpose?

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8400)* status: 103 of 105 files reviewed, 2 unresolved discussions (waiting on @arifogel and @dhalperi)

___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java` line 994 at r1](https://reviewable.io/reviews/batfish/batfish/8400#-N5IBfZ68bpabVLreNfY:-N5M3b9n2RuH0oeWAYBH:bagec93) ([raw file](https://github.com/batfish/batfish/blob/756b9fa797b9c0001bf29b51d88a8571e80222db/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java#L994)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

This change on purpose?
</blockquote></details>

yes, was an invalid javadoc.

**Review by arifogel — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8400)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi)

**Review by arifogel — COMMENTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8400)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi)

**Review by arifogel — COMMENTED** [review]
> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8400)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi)

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8400)* status: 104 of 112 files reviewed, all discussions resolved (waiting on @arifogel)

___
*[`projects/batfish/src/main/java/org/batfish/representation/cisco_xr/RoutePolicySetNextHop.java` line 11 at r5](https://reviewable.io/reviews/batfish/batfish/8400#-N6tVKJ8-UP62DUJe7N7:-N6tVKJ8-UP62DUJe7N8:bvftey2) ([raw file](https://github.com/batfish/batfish/blob/5a78a7ae2e2e2de5f0bfdc7d2aeeaf911545c4d0/projects/batfish/src/main/java/org/batfish/representation/cisco_xr/RoutePolicySetNextHop.java#L11)):*
> ```Java
> public class RoutePolicySetNextHop extends RoutePolicySetStatement {
> 
>   private static final Comment UNSUPPORTED = new Comment("(unsupported next-hop expression)");
> ```

FYI I copied this pattern from community set versions

**Review by arifogel — COMMENTED** [review]
> Reviewed 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8400)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dhalperi)

**Pull request merged**
