### PR TITLE
Update Palo Alto Networks config format detection

### PR DESCRIPTION
**Pull request by sfraint**
Update format detection to find other palo alto lines and differentiate between normal and flat (set) format.

### CODE REVIEW

**Comment by arifogel** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish/src/test/java/org/batfish/grammar/VendorConfigurationFormatDetectorTest.java, line 64 at r2](https://reviewable.io/reviews/batfish/batfish/1557#-LDxACR91ZeQ6IMDhXxV:-LDxACRA3V_oPPx2sfEY:bmz4da5) ([raw file](https://github.com/batfish/batfish/blob/6acd1fbe756612ee4574c844c45f603934d3a130/projects/batfish/src/test/java/org/batfish/grammar/VendorConfigurationFormatDetectorTest.java#L64)):*
> ```Java
> 
>   @Test
>   public void recognizePaloAlto() {
> ```

Could you add a negative example?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1557)*

**Comment by sfraint** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/test/java/org/batfish/grammar/VendorConfigurationFormatDetectorTest.java, line 64 at r2](https://reviewable.io/reviews/batfish/batfish/1557#-LDxACR91ZeQ6IMDhXxV:-LDxGGmXBTaTGD3fVD58:bb6un1j) ([raw file](https://github.com/batfish/batfish/blob/6acd1fbe756612ee4574c844c45f603934d3a130/projects/batfish/src/test/java/org/batfish/grammar/VendorConfigurationFormatDetectorTest.java#L64)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Could you add a negative example?
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1557)*

**Comment by dhalperi** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/test/java/org/batfish/grammar/VendorConfigurationFormatDetectorTest.java, line 64 at r2](https://reviewable.io/reviews/batfish/batfish/1557#-LDxACR91ZeQ6IMDhXxV:-LDxHLOPDH6-n8w-pqM1:b-5pp86o) ([raw file](https://github.com/batfish/batfish/blob/6acd1fbe756612ee4574c844c45f603934d3a130/projects/batfish/src/test/java/org/batfish/grammar/VendorConfigurationFormatDetectorTest.java#L64)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

Done
</blockquote></details>

? Why?

Aren't all the other tests effectively negative examples?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1557)*

**Comment by sfraint** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/test/java/org/batfish/grammar/VendorConfigurationFormatDetectorTest.java, line 64 at r2](https://reviewable.io/reviews/batfish/batfish/1557#-LDxACR91ZeQ6IMDhXxV:-LDxHT7O7og-3lnw0TCE:b-g8h8gp) ([raw file](https://github.com/batfish/batfish/blob/6acd1fbe756612ee4574c844c45f603934d3a130/projects/batfish/src/test/java/org/batfish/grammar/VendorConfigurationFormatDetectorTest.java#L64)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

? Why?

Aren't all the other tests effectively negative examples?
</blockquote></details>

I think it at least makes sense to test `unknown`

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1557)*

**Comment by dhalperi** [comment]
*[projects/batfish/src/test/java/org/batfish/grammar/VendorConfigurationFormatDetectorTest.java, line 64 at r2](https://reviewable.io/reviews/batfish/batfish/1557#-LDxACR91ZeQ6IMDhXxV:-LDxI4wA-u99y1ZYBOyN:b-q7fgr6) ([raw file](https://github.com/batfish/batfish/blob/6acd1fbe756612ee4574c844c45f603934d3a130/projects/batfish/src/test/java/org/batfish/grammar/VendorConfigurationFormatDetectorTest.java#L64)):*
Unknown: sure, but unrelated I think.

This seems completely useless:
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```java
>  
>     /* Make sure non-Palo Alto config line is not misidentified */
>     assertThat(
>         VendorConfigurationFormatDetector.identifyConfigurationFormat(notPaloAlto),
>         not(
>             anyOf(
>                 equalTo(ConfigurationFormat.FLAT_PALO_ALTO),
>                 equalTo(ConfigurationFormat.PALO_ALTO))));
> ```
</details>


---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1557)*

**Comment by arifogel** [comment]
Review status: 3 of 4 files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish/src/test/java/org/batfish/grammar/VendorConfigurationFormatDetectorTest.java, line 64 at r2](https://reviewable.io/reviews/batfish/batfish/1557#-LDxACR91ZeQ6IMDhXxV:-LDxdvph7SCDaACAML4H:bd2ihj1) ([raw file](https://github.com/batfish/batfish/blob/6acd1fbe756612ee4574c844c45f603934d3a130/projects/batfish/src/test/java/org/batfish/grammar/VendorConfigurationFormatDetectorTest.java#L64)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Unknown: sure, but unrelated I think.

This seems completely useless:

> ```java
>  
>     /* Make sure non-Palo Alto config line is not misidentified */
>     assertThat(
>         VendorConfigurationFormatDetector.identifyConfigurationFormat(notPaloAlto),
>         not(
>             anyOf(
>                 equalTo(ConfigurationFormat.FLAT_PALO_ALTO),
>                 equalTo(ConfigurationFormat.PALO_ALTO))));
> ```

</blockquote></details>

I didn't realize we had other tests. This was supposed to be a failsafe in their absence. If they are there, then sure, this is unnecessary.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1557)*

**Comment by arifogel** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1557)*

**Comment by arifogel** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1557#-:-LDxe7i32t-6lUCFaIN5:bnfp4nl)*

**Pull request merged**
