### PR TITLE
Add PAN virtual router interface extraction

### PR DESCRIPTION
**Pull request by sfraint**
* Add extraction and VI model conversion for interfaces associated with virtual routers
* Add support for parsing lists of variables for PAN configs

### CODE REVIEW

**Comment by haverma** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed, 1 unresolved discussion (waiting on @sfraint and @anothermattbrown)

---

*[projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/virtual-router-interfaces, line 3 at r1](https://reviewable.io/reviews/batfish/batfish/1731#-LFcUXO29BZL2AuzoVjO:-LFcUXO3A4vJlRW-T9l3:b-z0xej8) ([raw file](https://github.com/batfish/batfish/blob/3574cd0d56522c131f9065c4b3a0a69bd6992f68/projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/virtual-router-interfaces#L3)):*
> ```
> set deviceconfig system hostname virtual-router-interfaces
> set network virtual-router default interface ethernet1/1
> set network virtual-router somename interface [ ethernet1/2 ethernet1/3 ]
> ```

Is there a possibility that we can see a line like:
`set network virtual-router somename interface ` or `set network virtual-router somename interface [ ]`

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1731)*

**Comment by sfraint** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @sfraint and @anothermattbrown)

---

*[projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/virtual-router-interfaces, line 3 at r1](https://reviewable.io/reviews/batfish/batfish/1731#-LFcUXO29BZL2AuzoVjO:-LFcYPCl38WHtzBnxE2a:b-da0xjc) ([raw file](https://github.com/batfish/batfish/blob/3574cd0d56522c131f9065c4b3a0a69bd6992f68/projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/virtual-router-interfaces#L3)):*
<details><summary><i>Previously, haverma (Harsh Verma) wrote…</i></summary><blockquote>

Is there a possibility that we can see a line like:
`set network virtual-router somename interface ` or `set network virtual-router somename interface [ ]`
</blockquote></details>

It won't show up in a config file, but I think it is a valid line to enter on a device.  I was considering making the variable list support 0 elements, which I suppose won't hurt anything.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1731)*

**Comment by haverma** [comment]
:lgtm:

---

Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown)

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1731#-:-LFc_Xhn8rRUgXnAf4ax:bnfp4nl)*

**Comment by haverma** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed, 1 unresolved discussion (waiting on @sfraint and @anothermattbrown)

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Vrf.java, line 159 at r2](https://reviewable.io/reviews/batfish/batfish/1731#-LFcltho7eG2vkHnNWEk:-LFcltho7eG2vkHnNWEl:bsnwmlk) ([raw file](https://github.com/batfish/batfish/blob/9ec7e8d4ebc05116b5cb96f78a2ac0627e42c2a1/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Vrf.java#L159)):*
> ```Java
>   public SortedSet<String> getInterfaceNames() {
>     if (_interfaces != null && !_interfaces.isEmpty()) {
>       return new TreeSet<>(_interfaces.keySet());
> ```

`_interfaces` cannot be null in any case, we are initializing it to `TreeMap<>()` in the only constructor of this class.
So in the `else` part of the condition, why should we return `_interfaceNames` when `_interfaces` is empty ? Can `_interfaces` and `_interfaceNames` become out of sync ever ? 
ideally we should just return _interfaces.keySet()
Also why create a new `TreeSet` to return from this getter, why not just return the same `_interfaces.keySet()` ?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1731)*

**Comment by haverma** [comment]
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown)

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Vrf.java, line 159 at r2](https://reviewable.io/reviews/batfish/batfish/1731#-LFcltho7eG2vkHnNWEk:-LFct6R2BDk73LCoM6yL:b-n47xcy) ([raw file](https://github.com/batfish/batfish/blob/9ec7e8d4ebc05116b5cb96f78a2ac0627e42c2a1/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Vrf.java#L159)):*
<details><summary><i>Previously, haverma (Harsh Verma) wrote…</i></summary><blockquote>

`_interfaces` cannot be null in any case, we are initializing it to `TreeMap<>()` in the only constructor of this class.
So in the `else` part of the condition, why should we return `_interfaceNames` when `_interfaces` is empty ? Can `_interfaces` and `_interfaceNames` become out of sync ever ? 
ideally we should just return _interfaces.keySet()
Also why create a new `TreeSet` to return from this getter, why not just return the same `_interfaces.keySet()` ?
</blockquote></details>

so, it seems `_interfaces` can be null and `_interfacesNames` can become out of sync with `_interfaces` after an offline discussion

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1731)*

**Pull request merged**
