### PR TITLE
Reference & Definition tracking: support delete

### PR DESCRIPTION
**Pull request by sfraint**
Add support for deleting a structure's references and definitions.

### CODE REVIEW

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6854)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @arifogel and @corinaminer)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6854#-MXZZIA03gJ80IE3hbnI:-MXZZIA1CmWpRzzbGlki:b-vnh04c) (no related file):*
Related to https://github.com/batfish/batfish/pull/6674

---

**Review by arifogel — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6854)* status: all files reviewed, 1 unresolved discussion (waiting on @corinaminer and @sfraint)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java, line 314 at r1](https://reviewable.io/reviews/batfish/batfish/6854#-MXdixqH8205ZkPSAmqs:-MXdixqIEQ6aAk5XSrjI:bntkc7j) ([raw file](https://github.com/batfish/batfish/blob/98a93293d200e2782e35d04359f56ccf241c8422/projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java#L314)):*
> the specified structure in its definition

nit: This grammar is funky.

How about:
> Delete the definition of and any references to the specified structure`

**Review by corinaminer — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6854)* status: all files reviewed, 4 unresolved discussions (waiting on @sfraint)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java, line 292 at r1](https://reviewable.io/reviews/batfish/batfish/6854#-MXdg8kUACN1TCPnJUV9:-MXdg8kUACN1TCPnJUVA:bebyfj5) ([raw file](https://github.com/batfish/batfish/blob/98a93293d200e2782e35d04359f56ccf241c8422/projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java#L292)):*
> ```Java
>     SortedMap<String, DefinedStructureInfo> defsByName =
>         _structureDefinitions.get(type.getDescription());
>     if (defsByName == null) {
> ```

shouldn't this branch also be taken if `defsByName` exists but doesn't contain the specified `name`?
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java, line 307 at r1](https://reviewable.io/reviews/batfish/batfish/6854#-MXdgmXJ3njoOYajTqdq:-MXdgmXJ3njoOYajTqdr:b-uhonww) ([raw file](https://github.com/batfish/batfish/blob/98a93293d200e2782e35d04359f56ccf241c8422/projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java#L307)):*
> ```Java
>   private void deleteStructureReferences(String name, StructureType type) {
>     SortedMap<String, SortedMap<StructureUsage, SortedMultiset<Integer>>> refsByName =
>         _structureReferences.get(type);
> ```

I think this needs to take in a collection of structure types to check for references. For FortiOS, it'll always be a size-1 collection since we always know the exact type of a reference when we encounter it (unless it's undefined), but in general references may not be filed under the structure's exact type.
___
*[projects/batfish-common-protocol/src/test/java/org/batfish/vendor/VendorConfigurationTest.java, line 96 at r1](https://reviewable.io/reviews/batfish/batfish/6854#-MXdkL3_1y8Pq-N1V1LY:-MXdkL3_1y8Pq-N1V1LZ:bop4yux) ([raw file](https://github.com/batfish/batfish/blob/98a93293d200e2782e35d04359f56ccf241c8422/projects/batfish-common-protocol/src/test/java/org/batfish/vendor/VendorConfigurationTest.java#L96)):*
> ```Java
> 
>   @Test
>   public void testDeleteStructureUndefined() {
> ```

I'd add a similar test where there's a structure of the same type you're trying to delete, but with a different name. i think you actually have a bug in that case.

(and that test really should be separate from this one, because it's useful to test delete when no structures of the specified type are defined.)

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6854)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @arifogel, @corinaminer, and @sfraint)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java, line 292 at r1](https://reviewable.io/reviews/batfish/batfish/6854#-MXdg8kUACN1TCPnJUV9:-MXdrTQd6Bxk9pfqY_1J:b-pvdnp1) ([raw file](https://github.com/batfish/batfish/blob/98a93293d200e2782e35d04359f56ccf241c8422/projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java#L292)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

shouldn't this branch also be taken if `defsByName` exists but doesn't contain the specified `name`?
</blockquote></details>

good call, updated
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java, line 307 at r1](https://reviewable.io/reviews/batfish/batfish/6854#-MXdgmXJ3njoOYajTqdq:-MXdrZWC4pRzOpAMwbrS:b-1swwni) ([raw file](https://github.com/batfish/batfish/blob/98a93293d200e2782e35d04359f56ccf241c8422/projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java#L307)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

I think this needs to take in a collection of structure types to check for references. For FortiOS, it'll always be a size-1 collection since we always know the exact type of a reference when we encounter it (unless it's undefined), but in general references may not be filed under the structure's exact type.
</blockquote></details>

Maybe we will want that eventually, but it doesn't seem necessary yet.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java, line 314 at r1](https://reviewable.io/reviews/batfish/batfish/6854#-MXdixqH8205ZkPSAmqs:-MXdsIJR9ZHROSbnvzsG:bmrj2p3) ([raw file](https://github.com/batfish/batfish/blob/98a93293d200e2782e35d04359f56ccf241c8422/projects/batfish-common-protocol/src/main/java/org/batfish/vendor/VendorConfiguration.java#L314)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

> the specified structure in its definition

nit: This grammar is funky.

How about:
> Delete the definition of and any references to the specified structure`
</blockquote></details>

yuck, apparently I didn't proof read after copy-pasting...updated

**Review by corinaminer — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6854#-:-MXdxf-LEtxR92T7z-Yy:bnfp4nl)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @corinaminer)

**Review by corinaminer — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6854)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
