### PR TITLE
Add tunnel attribute in BgpRoute

### PR DESCRIPTION
**Pull request by corinaminer**
Adds a tunnel attribute field in `BgpRoute` and routing policy statements to set and clear it. No vendors currently create these statements in conversion.

After #8350, just because it relies on the `TunnelAttribute` class existing.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8352)* status: 0 of 27 files reviewed, all discussions resolved (waiting on @dhalperi)

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8352)* status: 0 of 30 files reviewed, all discussions resolved (waiting on @dhalperi)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/8352#-N3bM2_bCIBUfdx1RU7b:-N3bM2_bCIBUfdx1RU7c:b-7q13s) (no related file):*
Fyi: No longer dependent on #8350

___

**Review by dhalperi — COMMENTED** [review]
> Reviewed 30 of 30 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8352)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8352)* status: all files reviewed, 1 unresolved discussion (waiting on @corinaminer)

___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpRoute.java` line 27 at r2](https://reviewable.io/reviews/batfish/batfish/8352#-N3gA_F04XmnraNX4h3C:-N3gA_F04XmnraNX4h3D:b-z4ekxt) ([raw file](https://github.com/batfish/batfish/blob/c4489219a7dd82e442cff3d413a5361ed7f7704e/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpRoute.java#L27)):*
> ```Java
> import org.batfish.datamodel.bgp.community.Community;
> import org.batfish.datamodel.bgp.community.ExtendedCommunity;
> import org.batfish.datamodel.bgp.community.StandardCommunity;
> ```

missing new equals tests

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8352)* status: all files reviewed, 1 unresolved discussion (waiting on @corinaminer)

___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpRoute.java` line 160 at r2](https://reviewable.io/reviews/batfish/batfish/8352#-N3gAiR38TLhxTVQK_ld:-N3gAiR38TLhxTVQK_le:b-pw9835) ([raw file](https://github.com/batfish/batfish/blob/c4489219a7dd82e442cff3d413a5361ed7f7704e/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpRoute.java#L160)):*
> ```Java
>                 + (_tunnelEncapsulationAttribute == null
>                     ? 0
>                     : _tunnelEncapsulationAttribute.hashCode());
> ```

this can be replaced with `Objects.hashCode(_tunnelEncapsulationAttribute)` (or `.hash`, I forget which. I think former) but same impl.



_Code quote:_
```Java
                + (_tunnelEncapsulationAttribute == null
                    ? 0
                    : _tunnelEncapsulationAttribute.hashCode());
```

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8352)* status: 29 of 31 files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpRoute.java` line 27 at r2](https://reviewable.io/reviews/batfish/batfish/8352#-N3gA_F04XmnraNX4h3C:-N3h4q8i0at0iPSqwWXB:b2dvat7) ([raw file](https://github.com/batfish/batfish/blob/c4489219a7dd82e442cff3d413a5361ed7f7704e/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpRoute.java#L27)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

missing new equals tests
</blockquote></details>

added serialization/equality test for `BgpRouteAttributes`. Perhaps inappropriate to have a json serialization test since the class doesn't have its own json serialization; happy to remove it in that case
___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpRoute.java` line 160 at r2](https://reviewable.io/reviews/batfish/batfish/8352#-N3gAiR38TLhxTVQK_ld:-N3h4k1y0q5ASXslWzE3:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/c4489219a7dd82e442cff3d413a5361ed7f7704e/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpRoute.java#L160)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

this can be replaced with `Objects.hashCode(_tunnelEncapsulationAttribute)` (or `.hash`, I forget which. I think former) but same impl.
</blockquote></details>

done

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8352)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

**Pull request merged**
