### PR TITLE
Truncate parser error output with really large rules

### PR DESCRIPTION
**Pull request by dspicuzzbbn**
- Should only be useful for development

---
This change is [Reviewable](https://reviewable.io/reviews/batfish/batfish/510)

### CODE REVIEW

**Comment by dspicuzzbbn** [comment]
.. and if travis fails, I didn't bother running the tests yet, but I found this useful during parser rule development.

**Comment by arifogel** [comment]
This cannot be the default behavior, because it would hide changes during parsing testing where rules are large. If you want to make this an option in `org.batfish.config.Settings` that is disabled by default (something like `maxparsererrorlines` where `0` is unlimited), then we could integrate this.

**Comment by dhalperi** [comment]
I think this is a great idea, seems really useful. Given that Dustin did the initial work and has found it useful in his own work, I think we can take on the work of adding the flag.

**Comment by dhalperi** [comment]
Hey @sfraint , Can you take a look at this, too? I think you will find it educational and hopefully simple. Let's chat at your leisure.

**Comment by dhalperi** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/510)*

**Comment by arifogel** [comment]
Closed via #675

**Pull request closed without merging**
