### PR TITLE
Typedrow

### PR DESCRIPTION
**Pull request by ratulm**
Facility to provide type safety during Row construction. Uses a new builder. 

I found one illegal usage of Row in the process. SpecifiersAnswerer was putting a non-Schema type into the table. @anothermattbrown should confirm in that the two Specifiers* files modified in this PR preserve his intent.

### CODE REVIEW

**Comment by anothermattbrown** [comment]
Reviewed 2 of 18 files at r1.
Review status: 2 of 18 files reviewed, 1 unresolved discussion (waiting on @ratulm, @anothermattbrown, and @dhalperi)

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/SchemaUtils.java, line 28 at r1](https://reviewable.io/reviews/batfish/batfish/1645#-LEqZJFK9f149ZHh1RHc:-LEqZJFK9f149ZHh1RHd:b-q6xpcp) ([raw file](https://github.com/batfish/batfish/blob/dac0bba4fa5e8fa95203165437663be28232e29a/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/SchemaUtils.java#L28)):*
> ```Java
>     }
>     try {
>       switch (schema.getType()) {
> ```

How easy is it to add a new type of `Schema`?  I see above that we have `Schema.ACL_TRACE` -- would it make sense to add other types (e.g. `IpSpace` and `Location` for my stuff)? What operations would we need to implement for a new schema type?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1645)*

**Comment by ratulm** [comment]
Review status: 2 of 18 files reviewed, 1 unresolved discussion (waiting on @ratulm, @anothermattbrown, and @dhalperi)

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/SchemaUtils.java, line 28 at r1](https://reviewable.io/reviews/batfish/batfish/1645#-LEqZJFK9f149ZHh1RHc:-LEqbC3c004l_FkTS7YR:b6wlf6o) ([raw file](https://github.com/batfish/batfish/blob/dac0bba4fa5e8fa95203165437663be28232e29a/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/SchemaUtils.java#L28)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

How easy is it to add a new type of `Schema`?  I see above that we have `Schema.ACL_TRACE` -- would it make sense to add other types (e.g. `IpSpace` and `Location` for my stuff)? What operations would we need to implement for a new schema type?
</blockquote></details>

Adding schemas on the server side is easy. If you see in Schema.java, it is a mapping from name to the underlying class. In general, we have been doing for things that we want the clients to have a structured object for for richer manipulation or presentation when showing answers. Does your information have that property?  If you don't know yet, you can start with encoding things as STRING  or OBJECT and refine later.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1645)*

**Comment by anothermattbrown** [comment]
Review status: 2 of 18 files reviewed, all discussions resolved (waiting on @anothermattbrown and @dhalperi)

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/SchemaUtils.java, line 28 at r1](https://reviewable.io/reviews/batfish/batfish/1645#-LEqZJFK9f149ZHh1RHc:-LEqd5AQCDfeIGpjZXeI:b-h1uk8v) ([raw file](https://github.com/batfish/batfish/blob/dac0bba4fa5e8fa95203165437663be28232e29a/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/SchemaUtils.java#L28)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

Adding schemas on the server side is easy. If you see in Schema.java, it is a mapping from name to the underlying class. In general, we have been doing for things that we want the clients to have a structured object for for richer manipulation or presentation when showing answers. Does your information have that property?  If you don't know yet, you can start with encoding things as STRING  or OBJECT and refine later.
</blockquote></details>

Cool. I suspect we will want to expose the structure of such things, but STRING is good for now. Thanks.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1645)*

**Comment by dhalperi** [comment]
Reviewed 4 of 18 files at r1.
Review status: 5 of 18 files reviewed, 2 unresolved discussions (waiting on @ratulm and @dhalperi)

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/SchemaUtils.java, line 23 at r1](https://reviewable.io/reviews/batfish/batfish/1645#-LEx3XE6A7F54-Ne5tbZ:-LEx3XE701P_c9Ak_F7K:b-y6tshn) ([raw file](https://github.com/batfish/batfish/blob/dac0bba4fa5e8fa95203165437663be28232e29a/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/SchemaUtils.java#L23)):*
> ```Java
>    * @throws ClassCastException if the conversion fails
>    */
>   public static Object convertType(JsonNode jsonNode, Schema schema) {
> ```

`@Nullable`?

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/Row.java, line 31 at r1](https://reviewable.io/reviews/batfish/batfish/1645#-LEx43tKCRhbLq2vqp9A:-LEx43tKCRhbLq2vqp9B:b-rswrn7) ([raw file](https://github.com/batfish/batfish/blob/dac0bba4fa5e8fa95203165437663be28232e29a/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/Row.java#L31)):*
> ```Java
> public class Row implements Comparable<Row> {
> 
>   public static class RowBuilder {
> ```

I don't understand having both RowBuilder and TypedRowBuilder. There should only be one way to build row. If Row has to have a schema, then make the Row.builder static function take a schema.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1645)*

**Comment by dhalperi** [comment]
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/RowUtils.java, line 34 at r1](https://reviewable.io/reviews/batfish/batfish/1645#-LEx4QOlAaUpiyjRaLQh:-LEx4QOlAaUpiyjRaLQi:b-yd9qcl) ([raw file](https://github.com/batfish/batfish/blob/dac0bba4fa5e8fa95203165437663be28232e29a/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/RowUtils.java#L34)):*
> ```Java
> 
>   public static String getString(Row row, String column) {
>     return (String) row.get(column, Schema.STRING);
> ```

why not just have these on row?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1645)*

**Comment by ratulm** [comment]
Review status: 5 of 18 files reviewed, 1 unresolved discussion (waiting on @ratulm and @dhalperi)

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/Row.java, line 31 at r1](https://reviewable.io/reviews/batfish/batfish/1645#-LEx43tKCRhbLq2vqp9A:-LExKgqW1Up7LWNUxJvu:b-y9o11v) ([raw file](https://github.com/batfish/batfish/blob/dac0bba4fa5e8fa95203165437663be28232e29a/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/Row.java#L31)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I don't understand having both RowBuilder and TypedRowBuilder. There should only be one way to build row. If Row has to have a schema, then make the Row.builder static function take a schema.
</blockquote></details>

As things stand, Row does not have to have a schema. It is a dumb holder of data (and close to what is (de)serialized).

But that also opens up the possibility of bugs. TypedRowBuilder is a helper to safely build Rows that are consistent with a given schema. 

(I don't mind getting rid of the old RowBuilder entirely. We'll just have to modify a bunch of code, most of which sits in tests where we have been less adherent to schema.)

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1645)*

**Comment by dhalperi** [comment]
Review status: 4 of 18 files reviewed, 1 unresolved discussion (waiting on @dhalperi and @ratulm)

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/Row.java, line 31 at r1](https://reviewable.io/reviews/batfish/batfish/1645#-LEx43tKCRhbLq2vqp9A:-LEzZRNb2k-xRbKrO-SM:b-viek3x) ([raw file](https://github.com/batfish/batfish/blob/dac0bba4fa5e8fa95203165437663be28232e29a/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/Row.java#L31)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

As things stand, Row does not have to have a schema. It is a dumb holder of data (and close to what is (de)serialized).

But that also opens up the possibility of bugs. TypedRowBuilder is a helper to safely build Rows that are consistent with a given schema. 

(I don't mind getting rid of the old RowBuilder entirely. We'll just have to modify a bunch of code, most of which sits in tests where we have been less adherent to schema.)
</blockquote></details>

Ok, makes sense for now.

My proposal for keeping a simple API would be:

* Make RowBuilder an abstract class.
* Create UntypedRowBuilder and TypedRowBuilder as `final` classes inside of `Row` (keep `RowBuilder()` private). [feel free to much with names, e.g., AbstractRowBuilder/RowBuilder, etc.]
* Make `Row.builder()` and `Row.builder(metadata)` return these classes directly.

Does that make sense?

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/RowUtils.java, line 6 at r2](https://reviewable.io/reviews/batfish/batfish/1645#-LEz_-Yv7KivDvkDK4vx:-LEz_-Yv7KivDvkDK4vy:b-9unw6p) ([raw file](https://github.com/batfish/batfish/blob/c6b5b6e7c1c8428551948ac7f13be9532df981eb/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/RowUtils.java#L6)):*
> ```Java
> 
> @ParametersAreNonnullByDefault
> public class RowUtils {}
> ```

delete?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1645)*

**Comment by ratulm** [comment]
Review status: 3 of 17 files reviewed, all discussions resolved (waiting on @dhalperi and @anothermattbrown)

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/Row.java, line 31 at r1](https://reviewable.io/reviews/batfish/batfish/1645#-LEx43tKCRhbLq2vqp9A:-LF-JlDzAfcc8QALUcEq:b6lk0d9) ([raw file](https://github.com/batfish/batfish/blob/dac0bba4fa5e8fa95203165437663be28232e29a/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/Row.java#L31)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Ok, makes sense for now.

My proposal for keeping a simple API would be:

* Make RowBuilder an abstract class.
* Create UntypedRowBuilder and TypedRowBuilder as `final` classes inside of `Row` (keep `RowBuilder()` private). [feel free to much with names, e.g., AbstractRowBuilder/RowBuilder, etc.]
* Make `Row.builder()` and `Row.builder(metadata)` return these classes directly.

Does that make sense?
</blockquote></details>

Yes, I like that organization. Executed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1645)*

**Comment by dhalperi** [comment]
Reviewed 7 of 18 files at r1, 2 of 4 files at r2, 5 of 8 files at r3.
Review status: all files reviewed, 3 unresolved discussions (waiting on @ratulm)

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/RowMatchers.java, line 21 at r3](https://reviewable.io/reviews/batfish/batfish/1645#-LF4FiM7A9LvVnBHLPng:-LF4FiM7A9LvVnBHLPnh:bapcn4j) ([raw file](https://github.com/batfish/batfish/blob/5e3f3287b4ee317e9776011004ee0a54ebf079af/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/RowMatchers.java#L21)):*
> ```Java
>       @Nonnull Matcher<? super String> keyMatcher,
>       @Nonnull Matcher<? super V> valueMatcher,
>       @Nonnull TypeReference<V> valueTypeReference) {
> ```

don't you still need this one for the case of an `Object` schema?

---

*[projects/question/src/main/java/org/batfish/question/specifiers/SpecifiersAnswerer.java, line 41 at r3](https://reviewable.io/reviews/batfish/batfish/1645#-LF4G84T0s9WEII-F8MG:-LF4G84T0s9WEII-F8MH:b-vdgwlb) ([raw file](https://github.com/batfish/batfish/blob/5e3f3287b4ee317e9776011004ee0a54ebf079af/projects/question/src/main/java/org/batfish/question/specifiers/SpecifiersAnswerer.java#L41)):*
> ```Java
>           Row.of(
>               "Locations",
>               entry.getLocations().toArray(new Location[0]),
> ```

This is the case that I thought above would be problematic. Isn't the intent of the `Object` schema to allow actually putting in objects, not forcing you to convert them to strings?

---

*[projects/question/src/test/java/org/batfish/question/ipowners/IpOwnersAnswererTest.java, line 78 at r3](https://reviewable.io/reviews/batfish/batfish/1645#-LF4GHyqD-3PudzN_HVI:-LF4GHyqD-3PudzN_HVJ:bnrc7v3) ([raw file](https://github.com/batfish/batfish/blob/4fe7b88f41ec0d13a55639f398aca1263f4d006b/projects/question/src/test/java/org/batfish/question/ipowners/IpOwnersAnswererTest.java#L78)):*
> ```Java
>     Map<Ip, Long> counts =
>         rows.stream()
>             .map(r -> (Ip) r.get(IpOwnersAnswerer.COL_IP, Schema.IP))
> ```

getIp? and below

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1645)*

**Comment by ratulm** [comment]
Review status: all files reviewed, 3 unresolved discussions (waiting on @ratulm)

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/RowMatchers.java, line 21 at r3](https://reviewable.io/reviews/batfish/batfish/1645#-LF4FiM7A9LvVnBHLPng:-LF5-BgN13mVBlh2B0ve:b-1cp5y0) ([raw file](https://github.com/batfish/batfish/blob/5e3f3287b4ee317e9776011004ee0a54ebf079af/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/RowMatchers.java#L21)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

don't you still need this one for the case of an `Object` schema?
</blockquote></details>

I was thinking that if needed, it would be done on the outside. As far as Row knows, it stores Schema objects. This is consistent with Row.get now only supporting pulling things out by Schema (and not typereference like before). 

---

*[projects/question/src/main/java/org/batfish/question/specifiers/SpecifiersAnswerer.java, line 41 at r3](https://reviewable.io/reviews/batfish/batfish/1645#-LF4G84T0s9WEII-F8MG:-LF5-ZJI1ov6wQsroiQ1:b96ekx5) ([raw file](https://github.com/batfish/batfish/blob/5e3f3287b4ee317e9776011004ee0a54ebf079af/projects/question/src/main/java/org/batfish/question/specifiers/SpecifiersAnswerer.java#L41)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

This is the case that I thought above would be problematic. Isn't the intent of the `Object` schema to allow actually putting in objects, not forcing you to convert them to strings?
</blockquote></details>

I asked Matt about this one, and he seemed OK with string encoding here. He has specified Schema.STRING in the metadata anyway, but he wasn't converting them to string though.

---

*[projects/question/src/test/java/org/batfish/question/ipowners/IpOwnersAnswererTest.java, line 78 at r3](https://reviewable.io/reviews/batfish/batfish/1645#-LF4GHyqD-3PudzN_HVI:-LF50JSj-YMk_sRJsqtw:b5be1nn) ([raw file](https://github.com/batfish/batfish/blob/4fe7b88f41ec0d13a55639f398aca1263f4d006b/projects/question/src/test/java/org/batfish/question/ipowners/IpOwnersAnswererTest.java#L78)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

getIp? and below
</blockquote></details>

oh, i don't remember touching this part. changed though.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1645)*

**Comment by dhalperi** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1645#-:-LF51hp431dFXL-1cQJf:bnfp4nl)*

**Pull request merged**
