### PR TITLE
IOS:Supports multi-AS redistribution by EIGRP

### PR DESCRIPTION
**Pull request by NobutakaNiiya**
#8568
PR for the above issues.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8591)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @NobutakaNiiya)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/8591#-NM-Wd8w5pcCXc5mqRJI:-NM-Wd8w5pcCXc5mqRJJ:b-kixzxm) (no related file):*
Can you look at `MatchProtocol` to see how to make `MatchProcessAsn` handle multiple values? In particular,

1. use immutable data structures (sets), not arrays
2. type things correctly -- `Long`, not `Object`
3. Make sure all the new functionality is tested.

___

**Comment by dhalperi** [comment]
*[`projects/batfish/src/main/java/org/batfish/representation/cisco/RedistributionPolicy.java` line 13 at r3](https://reviewable.io/reviews/batfish/batfish/8591#-NMm6d-D70NvmHqtm1Si:-NMm6d-D70NvmHqtm1Sj:b-5v3fm6) ([raw file](https://github.com/batfish/batfish/blob/1bf08b970d940ce9fdde99c0207bab4a201d9128/projects/batfish/src/main/java/org/batfish/representation/cisco/RedistributionPolicy.java#L13)):*
> ```Java
>   protected String _routeMap;
> 
>   protected final RoutingProtocol _sourceProtocol;
> ```

I'm concerned about this change as-is. What happens if the user does:

```
redistribute eigrp 20 route-map RM20
redistribute eigrp 30 route-map RM30
```

Because we group only on source protocol, it looks to me like they can't have different route maps.

I suspect that if you want to implement this, you'll need to take the model from NX-OS where there is a key `<Protocol, ProtocolInstanceId>` instead of just `Protocol`. Check out the `RoutingProtocolInstance` class in NX-OS.

**Comment by NobutakaNiiya** [comment]
@dhalperi 
Thank you for your response.

Regarding this matter, we would like to implement a new `RoutingProtocolInstance` class in the IOS model and incorporate an implementation that returns a `Map<RoutingProtocolInstance, EigrpRedistributionPolicy>` type in the `getRedistributionPolicies()` method of the EigrpProcess class to address the issue. Do you see any issues with this approach?

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8591)* status: 0 of 21 files reviewed, 5 unresolved discussions (waiting on @NobutakaNiiya)

___
*[`projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java` line 7241 at r3](https://reviewable.io/reviews/batfish/batfish/8591#-NMm5IRK-8DKrKvDNP1t:-NMm5IRK-8DKrKvDNP1u:b-ixpg8m) ([raw file](https://github.com/batfish/batfish/blob/1bf08b970d940ce9fdde99c0207bab4a201d9128/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L7241)):*
> ```Java
>       r = new EigrpRedistributionPolicy(sourceProtocol);
>       _currentEigrpProcess.getRedistributionPolicies().put(sourceProtocol, r);
>     }
> ```

why not use `computeIfAbsent` like you did below? Seems like a nice simplification.



_Code quote:_
```Java
    EigrpRedistributionPolicy r;
    RoutingProtocol sourceProtocol = RoutingProtocol.EIGRP;
    if (_currentEigrpProcess.getRedistributionPolicies().containsKey(sourceProtocol)) {
      r = _currentEigrpProcess.getRedistributionPolicies().get(sourceProtocol);
    } else {
      r = new EigrpRedistributionPolicy(sourceProtocol);
      _currentEigrpProcess.getRedistributionPolicies().put(sourceProtocol, r);
    }
```
___
*[`projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java` line 1568 at r4](https://reviewable.io/reviews/batfish/batfish/8591#-NOVBVeg-5qQfoRMtVXw:-NOVBVeg-5qQfoRMtVXx:beu33ji) ([raw file](https://github.com/batfish/batfish/blob/7a5f03243c50857a0d8677399c74ac6a4d034e19/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L1568)):*
> ```Java
> 
>   /*
>    * Set this when moving to different stanzas (e.g., ro_vrf) inside "router ospf"
> ```

Can you please double-check that your IDE is using the same format settings as the project (`google-java-format`) and undo these whitespace changes to comments?
___
*[`projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java` line 7898 at r4](https://reviewable.io/reviews/batfish/batfish/8591#-NOVC9pw2r6fOLnKQ5Bv:-NOVC9pw2r6fOLnKQ5Bw:bmzzn73) ([raw file](https://github.com/batfish/batfish/blob/7a5f03243c50857a0d8677399c74ac6a4d034e19/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L7898)):*
> ```Java
>       BgpRedistributionPolicy r = new BgpRedistributionPolicy(RoutingProtocolInstance.eigrp());
>       proc.getRedistributionPolicies().put(r.getInstance(), r);
>       // TODO match specific EIGRP process ID (ctx.id)
> ```

I think the EIGRP process ID needs to be inside the `RoutingProtocolInstance` -- that is the whole point of this change.

That will enable the `proc.getRedistributionPolicies()` map keyed differently for different EIGRP processes enabling different policies per instance.



_Code quote:_
```Java
 // TODO match specific EIGRP process ID (ctx.id)
```

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8591)* status: 0 of 21 files reviewed, 8 unresolved discussions (waiting on @NobutakaNiiya)

___
*[`projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java` line 3615 at r7](https://reviewable.io/reviews/batfish/batfish/8591#-NPY3BpO9MmKA2_7IzT1:-NPY3BpP5jHFbHBiiHXu:b-6bf9z) ([raw file](https://github.com/batfish/batfish/blob/2aa4d5f2d58c9d478b85ffe5b84f0e35e0f0e251/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L3615)):*
> ```Java
>     assert ctx.ROUTING() != null ^ ctx.LINE_PROTOCOL() != null;
>     // You can change the interface and the subtype, but you can't change to a
>     // different top-level
> ```

revert change here



_Code quote:_
```Java
    // You can change the interface and the subtype, but you can't change to a
    // different top-level
```
___
*[`projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java` line 4781 at r7](https://reviewable.io/reviews/batfish/batfish/8591#-NPY3DOZBZZ2ICKudO_r:-NPY3DOZBZZ2ICKudO_s:b-6bf9z) ([raw file](https://github.com/batfish/batfish/blob/2aa4d5f2d58c9d478b85ffe5b84f0e35e0f0e251/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L4781)):*
> ```Java
>        * no autonomous-system
>        * The result should be a process with ASN 1, but instead the result is an
>        * invalid EIGRP
> ```

revert change here



_Code quote:_
```Java
       * The result should be a process with ASN 1, but instead the result is an
       * invalid EIGRP
```
___
*[`projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java` line 5532 at r7](https://reviewable.io/reviews/batfish/batfish/8591#-NPY3F1f2nMBQbAMpOYU:-NPY3F1f2nMBQbAMpOYV:b-l6hdjr) ([raw file](https://github.com/batfish/batfish/blob/2aa4d5f2d58c9d478b85ffe5b84f0e35e0f0e251/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L5532)):*
> ```Java
>     // currentInterface.setRoutingPolicy(policyName);
>     // }
>     _configuration.referenceStructure(
> ```

revert



_Code quote:_
```Java
    // for (Interface currentInterface : _currentInterfaces) {
    // currentInterface.setRoutingPolicy(policyName);
    // }
    _configuration.referenceStructure(
```
___
*[`projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java` line 7188 at r7](https://reviewable.io/reviews/batfish/batfish/8591#-NPY3Jdz5-VAgNn6ROwW:-NPY3Jdz5-VAgNn6ROwX:bmb53ys) ([raw file](https://github.com/batfish/batfish/blob/2aa4d5f2d58c9d478b85ffe5b84f0e35e0f0e251/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L7188)):*
> ```Java
>       return;
>     }
>     EigrpRedistributionPolicy r = new EigrpRedistributionPolicy(RoutingProtocolInstance.bgp());
> ```

The `as` should be a parameter to BGP, shouldn't it? I had thought this was clear in the NX_OS code I pointed you at. That is the only way that you will be able to have different policies for different BGP ASes.

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8591)* status: 0 of 21 files reviewed, 10 unresolved discussions (waiting on @NobutakaNiiya)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/8591#-NPY3ywV2EON--srh2PR:-NPY3ywV2EON--srh2PS:b-t69ewc) (no related file):*
I expect to see a new parsing test where there is an IOS configuration  with multiple redistreibution statements from different instances of the same protocol, and that this is correctly modeled in Batfish. I am not seeing this yet.

___
___
*[`projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java` line 1950 at r7](https://reviewable.io/reviews/batfish/batfish/8591#-NPY3oZWEFxKnYrLpgKM:-NPY3oZWEFxKnYrLpgKN:bjv8fio) ([raw file](https://github.com/batfish/batfish/blob/2aa4d5f2d58c9d478b85ffe5b84f0e35e0f0e251/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L1950)):*
> ```Java
>         // Use a generated route that will only be generated if a default route exists
>         // in RIB
>         String defaultRouteGenerationPolicyName =
> ```

Revert all whitespace change in unrelated code, throughout



_Code quote:_
```Java
        // Use a generated route that will only be generated if a default route exists
        // in RIB
        String defaultRouteGenerationPolicyName =
```

**Review by dhalperi — COMMENTED** [review]
> Reviewed 11 of 21 files at r4, 2 of 2 files at r7, 8 of 8 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8591)* status: all files reviewed, 12 unresolved discussions (waiting on @NobutakaNiiya)

___
*[`projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java` line 7241 at r3](https://reviewable.io/reviews/batfish/batfish/8591#-NMm5IRK-8DKrKvDNP1t:-NQQqxaZ9h4HjayFbGIZ:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/1bf08b970d940ce9fdde99c0207bab4a201d9128/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L7241)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

why not use `computeIfAbsent` like you did below? Seems like a nice simplification.
</blockquote></details>

Done.
___
*[`projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java` line 7898 at r4](https://reviewable.io/reviews/batfish/batfish/8591#-NOVC9pw2r6fOLnKQ5Bv:-NQQrAwn9JjnTd35BMM1:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/7a5f03243c50857a0d8677399c74ac6a4d034e19/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L7898)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I think the EIGRP process ID needs to be inside the `RoutingProtocolInstance` -- that is the whole point of this change.

That will enable the `proc.getRedistributionPolicies()` map keyed differently for different EIGRP processes enabling different policies per instance.
</blockquote></details>

Done.
___
*[`projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java` line 7188 at r7](https://reviewable.io/reviews/batfish/batfish/8591#-NPY3Jdz5-VAgNn6ROwW:-NQQqPG41wJEWzGVV4Xg:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/2aa4d5f2d58c9d478b85ffe5b84f0e35e0f0e251/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L7188)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

The `as` should be a parameter to BGP, shouldn't it? I had thought this was clear in the NX_OS code I pointed you at. That is the only way that you will be able to have different policies for different BGP ASes.
</blockquote></details>

Done.
___
*[`projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java` line 7239 at r8](https://reviewable.io/reviews/batfish/batfish/8591#-NQQqTdb8A9pCQrwpex-:-NQQqTdb8A9pCQrwpex0:bdls4hr) ([raw file](https://github.com/batfish/batfish/blob/8f98dc1ce63acd713e8a901e4ff87e0fd0d21237/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L7239)):*
> ```Java
>             .getRedistributionPolicies()
>             .computeIfAbsent(instance, key -> new EigrpRedistributionPolicy(instance));
>     r.getSpecialAttributes().put(EigrpRedistributionPolicy.EIGRP_AS_NUMBER, asn);
> ```

This should be removed now, right? It is redundant with the ASN in the instance, and we don't want two sources of truth.



_Code quote:_
```Java
r.getSpecialAttributes().put(EigrpRedistributionPolicy.EIGRP_AS_NUMBER, asn);
```
___
*[`projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java` line 1950 at r7](https://reviewable.io/reviews/batfish/batfish/8591#-NPY3oZWEFxKnYrLpgKM:-NQQrqQoEWdTe5CB_qmn:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/2aa4d5f2d58c9d478b85ffe5b84f0e35e0f0e251/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L1950)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Revert all whitespace change in unrelated code, throughout
</blockquote></details>

Done.
___
*[`projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java` line 1205 at r8](https://reviewable.io/reviews/batfish/batfish/8591#-NQQs8B35NcB532CX3AS:-NQQs8B35NcB532CX3AT:b-wlk86a) ([raw file](https://github.com/batfish/batfish/blob/8f98dc1ce63acd713e8a901e4ff87e0fd0d21237/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L1205)):*
> ```Java
>             .findFirst()
>             .map(Map.Entry::getValue)
>             .orElse(null);
> ```

Why only the first one? Shouldn't they all be handled?

Again, I'd look at how NX-OS did this.



_Code quote:_
```Java
    RedistributionPolicy redistributionPolicy =
        bgpProcess.getRedistributionPolicies().entrySet().stream()
            .filter(entry -> entry.getValue().getSourceProtocol().equals(srcProtocol))
            .findFirst()
            .map(Map.Entry::getValue)
            .orElse(null);
```
___
*[`projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java` line 2089 at r8](https://reviewable.io/reviews/batfish/batfish/8591#-NQQsG8s91sB0E5hIFTD:-NQQsG8s91sB0E5hIFTE:b722dly) ([raw file](https://github.com/batfish/batfish/blob/8f98dc1ce63acd713e8a901e4ff87e0fd0d21237/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L2089)):*
> ```Java
>             .findFirst()
>             .map(Map.Entry::getValue)
>             .orElse(null);
> ```

I think here you can just `.get(RoutingProtocolInstance.connected())`, right? There's only one.

Similar for static and others that don't have an instance parameter.



_Code quote:_
```Java
        proc.getRedistributionPolicies().entrySet().stream()
            .filter(entry -> entry.getValue().getSourceProtocol().equals(RoutingProtocol.CONNECTED))
            .findFirst()
            .map(Map.Entry::getValue)
            .orElse(null);
```
___
*[`projects/batfish/src/main/java/org/batfish/representation/cisco/OspfProcess.java` line 142 at r8](https://reviewable.io/reviews/batfish/batfish/8591#-NQQsWNl9f_kE3ChB4cl:-NQQsWNm4Wll0sVJ7Jq8:bt7d7rk) ([raw file](https://github.com/batfish/batfish/blob/8f98dc1ce63acd713e8a901e4ff87e0fd0d21237/projects/batfish/src/main/java/org/batfish/representation/cisco/OspfProcess.java#L142)):*
> ```Java
>     _stubs = new HashMap<>();
>     _wildcardNetworks = new TreeSet<>();
>     _redistributionPolicies = new LinkedHashMap<>();
> ```

Why `LinkedHashMap`? Why is order important here?



_Code quote:_
```Java
    _redistributionPolicies = new LinkedHashMap<>();
    _summaries = new TreeMap<>();
```
___
*[`projects/batfish/src/main/java/org/batfish/representation/cisco/RedistributionPolicy.java` line 13 at r3](https://reviewable.io/reviews/batfish/batfish/8591#-NMm6d-D70NvmHqtm1Si:-NQQsajI0kkI4dR1GQNX:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/1bf08b970d940ce9fdde99c0207bab4a201d9128/projects/batfish/src/main/java/org/batfish/representation/cisco/RedistributionPolicy.java#L13)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I'm concerned about this change as-is. What happens if the user does:

```
redistribute eigrp 20 route-map RM20
redistribute eigrp 30 route-map RM30
```

Because we group only on source protocol, it looks to me like they can't have different route maps.

I suspect that if you want to implement this, you'll need to take the model from NX-OS where there is a key `<Protocol, ProtocolInstanceId>` instead of just `Protocol`. Check out the `RoutingProtocolInstance` class in NX-OS.
</blockquote></details>

Done.
___
*[`projects/batfish/src/main/java/org/batfish/representation/cisco/RedistributionPolicy.java` line 28 at r8](https://reviewable.io/reviews/batfish/batfish/8591#-NQQsdnW0Jt8mPtW3dvc:-NQQsdnW0Jt8mPtW3dvd:b3eyo0n) ([raw file](https://github.com/batfish/batfish/blob/8f98dc1ce63acd713e8a901e4ff87e0fd0d21237/projects/batfish/src/main/java/org/batfish/representation/cisco/RedistributionPolicy.java#L28)):*
> ```Java
>   public RoutingProtocol getSourceProtocol() {
>     return _instance.getProtocol();
>   }
> ```

This chance concerns me. I'd think this function ought to be unnecessary, and any caller that uses it might be doing the wrong thing. Have you audited to see if this function is really needed?

I'd think all callers should just use the new function you added below.



_Code quote:_
```Java
  public RoutingProtocol getSourceProtocol() {
    return _instance.getProtocol();
  }
```
___
*[`projects/batfish/src/main/java/org/batfish/representation/cisco/RoutingProtocolInstance.java` line 10 at r8](https://reviewable.io/reviews/batfish/batfish/8591#-NQQsqpZ4A-NZ1bLz001:-NQQsqpZ4A-NZ1bLz002:by9q9d4) ([raw file](https://github.com/batfish/batfish/blob/8f98dc1ce63acd713e8a901e4ff87e0fd0d21237/projects/batfish/src/main/java/org/batfish/representation/cisco/RoutingProtocolInstance.java#L10)):*
> ```Java
> import org.batfish.datamodel.RoutingProtocol;
> 
> public class RoutingProtocolInstance implements Serializable {
> ```

Please add javadoc.
___
*[`projects/batfish/src/main/java/org/batfish/representation/cisco/RoutingProtocolInstance.java` line 11 at r8](https://reviewable.io/reviews/batfish/batfish/8591#-NQQsrmM7yZozezfLxpY:-NQQsrmM7yZozezfLxpZ:bvqefaw) ([raw file](https://github.com/batfish/batfish/blob/8f98dc1ce63acd713e8a901e4ff87e0fd0d21237/projects/batfish/src/main/java/org/batfish/representation/cisco/RoutingProtocolInstance.java#L11)):*
> ```Java
> 
> public class RoutingProtocolInstance implements Serializable {
>   public static RoutingProtocolInstance bgp(Long tag) {
> ```

Why is this `Long`? Is the ASN not required?

Similar throughout.
___
*[`projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java` line 3829 at r8](https://reviewable.io/reviews/batfish/batfish/8591#-NQQtNM44YJ2p1yB0O1Y:-NQQtNM44YJ2p1yB0O1Z:b-6nowz6) ([raw file](https://github.com/batfish/batfish/blob/8f98dc1ce63acd713e8a901e4ff87e0fd0d21237/projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java#L3829)):*
> ```Java
>     assert bgpProc != null;
>     BgpRedistributionPolicy eigrpRedist =
>         bgpProc.getRedistributionPolicies().entrySet().stream()
> ```

I'd just get the one for the instance you're looking for. (Throughout)
___
*[`projects/batfish/src/test/java/org/batfish/representation/cisco/RoutingProtocolInstanceTest.java` line 34 at r8](https://reviewable.io/reviews/batfish/batfish/8591#-NQQt_1y4SyHajoVDlB-:-NQQt_1y4SyHajoVDlB0:b-kfjd8t) ([raw file](https://github.com/batfish/batfish/blob/8f98dc1ce63acd713e8a901e4ff87e0fd0d21237/projects/batfish/src/test/java/org/batfish/representation/cisco/RoutingProtocolInstanceTest.java#L34)):*
> ```Java
>     RoutingProtocolInstance staticRoutingProtocol = RoutingProtocolInstance.staticRoutingProtocol();
>     assertThat(staticRoutingProtocol.getProtocol(), equalTo(RoutingProtocol.STATIC));
>   }
> ```

You can probably ditch this. The equals tester does most of this, if used right, I'd think.



_Code quote:_
```Java
  @Test
  public void testConstruction() {
    RoutingProtocolInstance bgp = RoutingProtocolInstance.bgp(10L);
    assertThat(bgp.getProtocol(), equalTo(RoutingProtocol.BGP));

    RoutingProtocolInstance connected = RoutingProtocolInstance.connected();
    assertThat(connected.getProtocol(), equalTo(RoutingProtocol.CONNECTED));

    RoutingProtocolInstance eigrp = RoutingProtocolInstance.eigrp(10L);
    assertThat(eigrp.getProtocol(), equalTo(RoutingProtocol.EIGRP));

    RoutingProtocolInstance ospf = RoutingProtocolInstance.ospf();
    assertThat(ospf.getProtocol(), equalTo(RoutingProtocol.OSPF));

    RoutingProtocolInstance rip = RoutingProtocolInstance.rip();
    assertThat(rip.getProtocol(), equalTo(RoutingProtocol.RIP));

    RoutingProtocolInstance isis_l1 = RoutingProtocolInstance.isis_l1();
    assertThat(isis_l1.getProtocol(), equalTo(RoutingProtocol.ISIS_L1));

    RoutingProtocolInstance staticRoutingProtocol = RoutingProtocolInstance.staticRoutingProtocol();
    assertThat(staticRoutingProtocol.getProtocol(), equalTo(RoutingProtocol.STATIC));
  }
```
___
*[`projects/batfish/src/test/java/org/batfish/representation/cisco/RoutingProtocolInstanceTest.java` line 39 at r8](https://reviewable.io/reviews/batfish/batfish/8591#-NQQteZL6boIN16xp8_k:-NQQteZL6boIN16xp8_l:by0493k) ([raw file](https://github.com/batfish/batfish/blob/8f98dc1ce63acd713e8a901e4ff87e0fd0d21237/projects/batfish/src/test/java/org/batfish/representation/cisco/RoutingProtocolInstanceTest.java#L39)):*
> ```Java
>   public void testEquals() {
>     new EqualsTester()
>         .addEqualityGroup(RoutingProtocolInstance.bgp(10L))
> ```

1. Want an equality group that two distinct instances are considered equal. That is usually `addEqualityGroup(bgp(10L), bgp(10L))` for all protocols.
2. Want to test that different ASN / tag etc. are NOT equal. That is usually `.addEqualityGroup(bgp(10L)).addEqualityGroup(bgp(20L))` for all protocols.

If you do that, you'll have tested that equals checks both protocol and asn, and also that different protocols are considered different.

**Comment by NobutakaNiiya** [comment]
*[`projects/batfish/src/main/java/org/batfish/representation/cisco/RoutingProtocolInstance.java` line 11 at r8](https://reviewable.io/reviews/batfish/batfish/8591#-NQQsrmM7yZozezfLxpY:-NRHmMzSAqpLIw0m7U6C:b-6l6c2r) ([raw file](https://github.com/batfish/batfish/blob/8f98dc1ce63acd713e8a901e4ff87e0fd0d21237/projects/batfish/src/main/java/org/batfish/representation/cisco/RoutingProtocolInstance.java#L11)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Why is this `Long`? Is the ASN not required?

Similar throughout.
</blockquote></details>

Fixed by referring to the NX-OS RoutingProtocolinstance class.
Should I correct it to a string type?



_Code quote:_
```Java
RoutingProtocolInstance 
```

**Review by NobutakaNiiya — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8591)* status: 10 of 21 files reviewed, 3 unresolved discussions (waiting on @dhalperi)

___
*[`projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java` line 1205 at r8](https://reviewable.io/reviews/batfish/batfish/8591#-NQQs8B35NcB532CX3AS:-NRHjwZqDeQB-TWDYINO:b-bbcywt) ([raw file](https://github.com/batfish/batfish/blob/8f98dc1ce63acd713e8a901e4ff87e0fd0d21237/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L1205)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Why only the first one? Shouldn't they all be handled?

Again, I'd look at how NX-OS did this.
</blockquote></details>

Fixed according to the implementation of NX-OS.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 11 of 11 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8591)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @NobutakaNiiya)

___
*[`projects/batfish/src/main/java/org/batfish/representation/cisco/RoutingProtocolInstance.java` line 11 at r8](https://reviewable.io/reviews/batfish/batfish/8591#-NQQsrmM7yZozezfLxpY:-NRK4lLJB7NSzR0Nlw7W:b-3td6x0) ([raw file](https://github.com/batfish/batfish/blob/8f98dc1ce63acd713e8a901e4ff87e0fd0d21237/projects/batfish/src/main/java/org/batfish/representation/cisco/RoutingProtocolInstance.java#L11)):*
<details><summary><i>Previously, NobutakaNiiya (Niiya218) wrote…</i></summary><blockquote>

Fixed by referring to the NX-OS RoutingProtocolinstance class.
Should I correct it to a string type?
</blockquote></details>

I think it's fine. I took a quick look and confirmed that ASNs do seem to be required by the Batfish grammar, so this is safe.

On NX-OS, they are not, which is why it was `@Nullable`.

**Comment by dhalperi** [comment]
Thanks!

**Pull request merged**
