### PR TITLE
IOS: Support for portgroup in extended ACLs

### LINKED ISSUE #7681: Cisco portgroup is unrecognized
Hi have meny rows in our cofig thats use the portgroup syntax.

example

```json                
{
                    "Details": "This syntax is unrecognized",
                    "Line_Text": "permit tcp any host 172.17.111.16 portgroup SG-NFS-fs",
                    "Nodes": null,
                    "Parser_Context": "[extended_access_list_stanza stanza cisco_configuration]",
                    "Source_Lines": [
                        {
                            "filename": "configs/sw-c1.cfg",
                            "lines": [
                                10204
                            ]
                        }
                    ],
                    "Type": "Parse warning"
                }

```

the group corresponds to this
```
!
object-group ip port SG-NFS-fs
 eq 111
 eq 635
 eq 2049
 eq 4045
 eq 4046
!
```
``` json
   {
                    "description": "The type of issues identified",                   
                    "Line_Text": "object-group ip port SG-NFS-fs",
                    "Nodes": null,
                    "Parser_Context": "[s_object_group stanza cisco_configuration]",
                    "Source_Lines": [
                        {
                            "filename": "configs/sw-c1.cfg",
                            "lines": [
                                816
                            ]
                        }
                    ],
                    "Type": "Parse warning"
                },
```

### PR DESCRIPTION
**Pull request by ratulm**
Fixes #7681 

The best documentation that I could find about this stuff was https://www.cisco.com/en/US/docs/general/Test/dwerblo/broken_guide/acl.pdf

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 15 of 17 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7684)* status: all files reviewed, 10 unresolved discussions (waiting on @ratulm)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7684#-MoVUbcADt2Ky_09mHCp:-MoVUbcADt2Ky_09mHCq:b-fgrj61) (no related file):*
High level: `object-group ip port` is not available on the IOSv lab VM I checked. Is this IOS-XE? If so, please note as much in grammar and javadocs.

---
___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 10317 at r2](https://reviewable.io/reviews/batfish/batfish/7684#-MoVSqk62bk8pJTgenSh:-MoVSqk62bk8pJTgenSi:blnmomz) ([raw file](https://github.com/batfish/batfish/blob/8fde6bd5d90ea65f554eca6b492bb2b904f7ce6c/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L10317)):*
> ```Java
>       return new PortObjectGroupPortSpec(portgroupName);
>     }
>     warn(ctx, "Unhandled port specifier");
> ```

Rather than making this nullable, just assert after the first `if` that `ctx.eacl_portgroup() != null`. Then simplify calling code.
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 3155 at r2](https://reviewable.io/reviews/batfish/batfish/7684#-MoVT6qSCJ_mL4BvWuzn:-MoVT6qSCJ_mL4BvWuzo:bycnub2) ([raw file](https://github.com/batfish/batfish/blob/8fde6bd5d90ea65f554eca6b492bb2b904f7ce6c/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L3155)):*
> ```Java
>         CiscoStructureType.IP_PORT_OBJECT_GROUP,
>         CiscoStructureUsage.EXTENDED_ACCESS_LIST_PORTGROUP);
>     markConcreteStructure(
> ```

Out of scope, but we should convert marking function here to new style which does not require manual enumeration.
See e.g. `CiscoNxosConfiguration`:
```
  private void markStructures() {
    CiscoNxosStructureType.CONCRETE_STRUCTURES.forEach(this::markConcreteStructure);
    CiscoNxosStructureType.ABSTRACT_STRUCTURES
        .asMap()
        .forEach(this::markAbstractStructureAllUsages);
  }
```

Requires changes to enums.
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco/LiteralPortSpec.java, line 10 at r2](https://reviewable.io/reviews/batfish/batfish/7684#-MoVTf3YDj7_o7PJe2NS:-MoVTf3YDj7_o7PJe2NT:blw0cjh) ([raw file](https://github.com/batfish/batfish/blob/8fde6bd5d90ea65f554eca6b492bb2b904f7ce6c/projects/batfish/src/main/java/org/batfish/representation/cisco/LiteralPortSpec.java#L10)):*
> ```Java
> import org.batfish.datamodel.SubRange;
> 
> /** A {@link PortSpec} consisting of a literal port ranges. */
> ```

nit: remove `a`
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco/LiteralPortSpec.java, line 15 at r2](https://reviewable.io/reviews/batfish/batfish/7684#-MoVTk2wBUu4DFVKUNCw:-MoVTk2wBUu4DFVKUNCx:b55fcfa) ([raw file](https://github.com/batfish/batfish/blob/8fde6bd5d90ea65f554eca6b492bb2b904f7ce6c/projects/batfish/src/main/java/org/batfish/representation/cisco/LiteralPortSpec.java#L15)):*
> ```Java
>   public static LiteralPortSpec ALL_PORTS = new LiteralPortSpec(IntegerSpace.PORTS.getSubRanges());
> 
>   private final List<SubRange> _ports;
> ```

nit: `@Nonnull`
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco/PortObjectGroupLine.java, line 10 at r2](https://reviewable.io/reviews/batfish/batfish/7684#-MoVU2C52_s-n90qTSyn:-MoVU2C52_s-n90qTSyo:b-ir9vie) ([raw file](https://github.com/batfish/batfish/blob/8fde6bd5d90ea65f554eca6b492bb2b904f7ce6c/projects/batfish/src/main/java/org/batfish/representation/cisco/PortObjectGroupLine.java#L10)):*
> ```Java
> import org.batfish.datamodel.SubRange;
> 
> /** Represents an individual line of {@link PortObjectGroupPortSpec} */
> ```

nit: `of` -> `of a`
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco/PortObjectGroupPortSpec.java, line 6 at r2](https://reviewable.io/reviews/batfish/batfish/7684#-MoVU6Ic2OYlo8SRxlAJ:-MoVU6Ic2OYlo8SRxlAK:b-b68aoi) ([raw file](https://github.com/batfish/batfish/blob/8fde6bd5d90ea65f554eca6b492bb2b904f7ce6c/projects/batfish/src/main/java/org/batfish/representation/cisco/PortObjectGroupPortSpec.java#L6)):*
> ```Java
> import javax.annotation.ParametersAreNonnullByDefault;
> 
> /** Represents an 'ip port-group' */
> ```

nit: `'ip port-group'` -> `{@code ip port-group}`
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco/PortSpecVisitor.java, line 3 at r2](https://reviewable.io/reviews/batfish/batfish/7684#-MoVUIky27TGtwbk4YIr:-MoVUIky27TGtwbk4YIs:b-ddza6r) ([raw file](https://github.com/batfish/batfish/blob/8fde6bd5d90ea65f554eca6b492bb2b904f7ce6c/projects/batfish/src/main/java/org/batfish/representation/cisco/PortSpecVisitor.java#L3)):*
> ```Java
> package org.batfish.representation.cisco;
> 
> /** A visitor of {@link PortSpec}. */
> ```

nit: please add `that returns a generic value` to describe the purpose of the generic class argument
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco/SimpleExtendedAccessListServiceSpecifier.java, line 28 at r2](https://reviewable.io/reviews/batfish/batfish/7684#-MoVV2UQ-ebYqFw_6xXg:-MoVV2UQ-ebYqFw_6xXh:bytzccx) ([raw file](https://github.com/batfish/batfish/blob/8fde6bd5d90ea65f554eca6b492bb2b904f7ce6c/projects/batfish/src/main/java/org/batfish/representation/cisco/SimpleExtendedAccessListServiceSpecifier.java#L28)):*
> ```Java
>     private Set<Integer> _dscps = ImmutableSet.of();
> 
>     private PortSpec _dstPorts;
> ```

nit: null annotations for new code, please. Note the enclosing class does not currently use `@ParametersAreNonnullByDefault`.
___
*[projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java, line 1951 at r2](https://reviewable.io/reviews/batfish/batfish/7684#-MoVRafE9g1RA7rgsC-J:-MoVRafE9g1RA7rgsC-K:bkg6pxg) ([raw file](https://github.com/batfish/batfish/blob/8fde6bd5d90ea65f554eca6b492bb2b904f7ce6c/projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java#L1951)):*
> ```Java
> 
>     /* The base acl permits in flows and rejects out flows */
>     assertThat(c, hasIpAccessList("aclBase", accepts(inFlowSrc, null, c)));
> ```

This is fine for now since the ACLs are so simple, but in the future please do bdd equality tests rather than flow tests.
___
*[projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java, line 1961 at r2](https://reviewable.io/reviews/batfish/batfish/7684#-MoVVfbp157JHguv5aJT:-MoVVfbp157JHguv5aJU:b-bnsqq8) ([raw file](https://github.com/batfish/batfish/blob/8fde6bd5d90ea65f554eca6b492bb2b904f7ce6c/projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java#L1961)):*
> ```Java
>     assertThat(c, hasIpAccessList("aclDuplicate", rejects(inFlowSrc, null, c)));
> 
>     /* The undefined acl reject in flows because the earlier (empty) definition wins */
> ```

This description seems wrong. Copypaste error from above?
Also, did you test that undefined port group rejects?
___
*[projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-acl-portgroup, line 11 at r2](https://reviewable.io/reviews/batfish/batfish/7684#-MoVQtOBC8Ll9R2ilWWn:-MoVQtOBC8Ll9R2ilWWo:bkh82ht) ([raw file](https://github.com/batfish/batfish/blob/8fde6bd5d90ea65f554eca6b492bb2b904f7ce6c/projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-acl-portgroup#L11)):*
> ```
> !
> object-group ip port  ogipDuplicate
> ! Redefining this object group with a new object should have no effect
> ```

Are you sure about this? Did you test on the CLI?
The linked doc suggests some changes are only merged on exit of the current configuration mode, rather than every line.
Did you exit out of configuration before testing? Does `eq 111` not show up in this object-group after you exit completely out of config mode?

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7684)* status: all files reviewed, 10 unresolved discussions (waiting on @ratulm)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7684#-MoVUbcADt2Ky_09mHCp:-MoVW-pI49q9eOaYOJbQ:b-5gqpb8) (no related file):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

High level: `object-group ip port` is not available on the IOSv lab VM I checked. Is this IOS-XE? If so, please note as much in grammar and javadocs.
</blockquote></details>

I looked at the linked doc again, and it seems this is for straight IOS. Any idea what conditions must exist for this feature to be available? Is the `SX` in `12.2SX` important maybe?

---

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7684)* status: 18 of 20 files reviewed, 2 unresolved discussions (waiting on @arifogel)

___
*[projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java, line 1961 at r2](https://reviewable.io/reviews/batfish/batfish/7684#-MoVVfbp157JHguv5aJT:-Mom7jYRE8_oEapvhIf6:bxahydu) ([raw file](https://github.com/batfish/batfish/blob/8fde6bd5d90ea65f554eca6b492bb2b904f7ce6c/projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java#L1961)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

This description seems wrong. Copypaste error from above?
Also, did you test that undefined port group rejects?
</blockquote></details>

Good catch. The code (not so much the description) was wrong; fixed.

Couldn't test; went with the semantics of protocol groups. 
___
*[projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-acl-portgroup, line 11 at r2](https://reviewable.io/reviews/batfish/batfish/7684#-MoVQtOBC8Ll9R2ilWWn:-Mom8-umCHvtFIz4V79x:b-ka9fzr) ([raw file](https://github.com/batfish/batfish/blob/8fde6bd5d90ea65f554eca6b492bb2b904f7ce6c/projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-acl-portgroup#L11)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Are you sure about this? Did you test on the CLI?
The linked doc suggests some changes are only merged on exit of the current configuration mode, rather than every line.
Did you exit out of configuration before testing? Does `eq 111` not show up in this object-group after you exit completely out of config mode?
</blockquote></details>

couldn't test. went by the semantics of protocol groups.

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 2 files at r3, 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7684)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ratulm)

**Pull request merged**
