### PR TITLE
Simplify transformations in reachability analysis

### PR DESCRIPTION
**Pull request by anothermattbrown**
Simplify transformation: 
TransformationStateExpr no longer has both SRC_IP and NEW_SRC_IP fields.

### CODE REVIEW

**Comment by arifogel** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1050)*

**Comment by arifogel** [comment]
Reviewed 58 of 58 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish/src/main/java/org/batfish/z3/expr/visitors/BoolExprTransformer.java, line 64 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1050#-L7_ZN3n-ipcBYjX_thV:-L7_ZN3n-ipcBYjX_thW:brpjcjq) ([raw file](https://github.com/batfish/batfish/blob/ca4d1204f93d1d0b8e40561a94ba4f7f3f3878e9/projects/batfish/src/main/java/org/batfish/z3/expr/visitors/BoolExprTransformer.java#L64)):*
> ```Java
>   public static BoolExpr toBoolExpr(
>       StateExpr stateExpr, SynthesizerInput input, NodContext nodContext) {
>     return new BoolExprTransformer(input, nodContext).transformStateExpr(stateExpr);
> ```

Isn't this less efficient? Doesn't it introduce at least .. extra call?

---

*[projects/batfish/src/main/java/org/batfish/z3/expr/visitors/BoolExprTransformer.java, line 217 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1050#-L7_Z42GA3nhnAaAjRj7:-L7_Z42H7T--t-fFePHv:bs453ky) ([raw file](https://github.com/batfish/batfish/blob/ca4d1204f93d1d0b8e40561a94ba4f7f3f3878e9/projects/batfish/src/main/java/org/batfish/z3/expr/visitors/BoolExprTransformer.java#L217)):*
> ```Java
>   @Override
>   public BoolExpr visitQueryStatement(QueryStatement queryStatement) {
>     return transformStateExpr(queryStatement.getSubExpression());
> ```

Isn't this less efficient? Doesn't it introduce at least one extra call?

---

*[projects/batfish/src/main/java/org/batfish/z3/expr/visitors/RelationCollector.java, line 41 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1050#-L7_Zkqi2yV26wWgPceu:-L7_Zkqi2yV26wWgPcev:bs453ky) ([raw file](https://github.com/batfish/batfish/blob/ca4d1204f93d1d0b8e40561a94ba4f7f3f3878e9/projects/batfish/src/main/java/org/batfish/z3/expr/visitors/RelationCollector.java#L41)):*
> ```Java
>   @Override
>   public void visitBasicRuleStatement(BasicRuleStatement basicRuleStatement) {
>     basicRuleStatement.getPreconditionStates().forEach(this::visitStateExpr);
> ```

Isn't this less efficient? Doesn't it introduce at least one extra call?

---

*[projects/batfish/src/main/java/org/batfish/z3/expr/visitors/RelationCollector.java, line 50 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1050#-L7_ZsFy0EtVfSNMVtbI:-L7_ZsFy0EtVfSNMVtbJ:bs453ky) ([raw file](https://github.com/batfish/batfish/blob/ca4d1204f93d1d0b8e40561a94ba4f7f3f3878e9/projects/batfish/src/main/java/org/batfish/z3/expr/visitors/RelationCollector.java#L50)):*
> ```Java
>   @Override
>   public void visitQueryStatement(QueryStatement queryStatement) {
>     visitStateExpr(queryStatement.getSubExpression());
> ```

Isn't this less efficient? Doesn't it introduce at least one extra call?

---

*[projects/batfish/src/main/java/org/batfish/z3/expr/visitors/RelationCollector.java, line 64 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1050#-L7_ZuBU135ygrt4UJYV:-L7_ZuBU135ygrt4UJYW:bs453ky) ([raw file](https://github.com/batfish/batfish/blob/ca4d1204f93d1d0b8e40561a94ba4f7f3f3878e9/projects/batfish/src/main/java/org/batfish/z3/expr/visitors/RelationCollector.java#L64)):*
> ```Java
>     transformationRuleStatement
>         .getPreconditionPreTransformationStates()
>         .forEach(this::visitStateExpr);
> ```

Isn't this less efficient? Doesn't it introduce at least one extra call?

---

*[projects/batfish/src/main/java/org/batfish/z3/expr/visitors/RelationCollector.java, line 67 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1050#-L7_Zu_aAEje1L6NeHlU:-L7_Zu_aAEje1L6NeHlV:bs453ky) ([raw file](https://github.com/batfish/batfish/blob/ca4d1204f93d1d0b8e40561a94ba4f7f3f3878e9/projects/batfish/src/main/java/org/batfish/z3/expr/visitors/RelationCollector.java#L67)):*
> ```Java
>     transformationRuleStatement
>         .getPreconditionPostTransformationStates()
>         .forEach(this::visitStateExpr);
> ```

Isn't this less efficient? Doesn't it introduce at least one extra call?

---

*[projects/batfish/src/main/java/org/batfish/z3/expr/visitors/RelationCollector.java, line 68 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1050#-L7_ZwJM4gdHlUb_hasI:-L7_ZwJM4gdHlUb_hasJ:bs453ky) ([raw file](https://github.com/batfish/batfish/blob/ca4d1204f93d1d0b8e40561a94ba4f7f3f3878e9/projects/batfish/src/main/java/org/batfish/z3/expr/visitors/RelationCollector.java#L68)):*
> ```Java
>         .getPreconditionPostTransformationStates()
>         .forEach(this::visitStateExpr);
>     visitStateExpr(transformationRuleStatement.getPostconditionTransformationState());
> ```

Isn't this less efficient? Doesn't it introduce at least one extra call?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1050)*

**Comment by arifogel** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[a discussion](https://reviewable.io:443/reviews/batfish/batfish/1050#-L7_fwHMRfSypNMzbxvR:-L7_fwHMRfSypNMzbxvS:bp9kkhe) (no related file):*
Please rename `getSubExpression` where return type is a `StateExpr` to something that doesn't sound so general.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/1050)*

**Comment by arifogel** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/batfish/batfish/1050#-L7_g1qemWImMSga4MZm:-L7_g1qemWImMSga4MZn:b7hdibs) (no related file):*
Please rename `visitStateExpr` where it is not actually a visitor method.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/1050)*

**Comment by anothermattbrown** [comment]
Reviewed 1 of 58 files at r2.
Review status: 52 of 61 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/batfish/batfish/1050#-L7_fwHMRfSypNMzbxvR:-L7_jotMJlbr-jqPH937:b-896fix) (no related file):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Please rename `getSubExpression` where return type is a `StateExpr` to something that doesn't sound so general.
</blockquote></details>

Done.

---

*[a discussion](https://reviewable.io:443/reviews/batfish/batfish/1050#-L7_g1qemWImMSga4MZm:-L7_jpUFqsBcaSHTfJLY:b-896fix) (no related file):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Please rename `visitStateExpr` where it is not actually a visitor method.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/1050)*

**Comment by arifogel** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/1050#-:-L7_lNadXp95wbzN6iL5:bnfp4nl)*

**Pull request merged**
