### PR TITLE
FlatJuniperLexer: flesh out community regex

### PR DESCRIPTION
**Pull request by dhalperi**
Many more tokens are valid in a community regex, like

    set policy-options community COMM members "_12:34_"

See: https://www.juniper.net/documentation/en_US/junose15.1/topics/concept/routing-policy-regular-expressions-using.html

### CODE REVIEW

**Comment by dhalperi** [comment]
Open Q: is this actually correct?

**Comment by dhalperi** [comment]
Looks like yes; https://www.juniper.net/documentation/en_US/junose15.1/topics/concept/routing-policy-regular-expressions-using.html

**Comment by dhalperi** [comment]
Review status: 0 of 4 files reviewed, all discussions resolved (waiting on @progwriter and @arifogel)

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1790#-LGBZnnA44hQAeKfI8vR:-LGBkqQUEoCW7yoNI7ko:b-1ajm46) (no related file):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Working on fleshing this out for the entire list of supported characters
</blockquote></details>

Okay, I added the entire set of characters that are valid according to the linked document. No information as to whether they are properly handled downstream, of course.

Some of these are new entirely to the Lexer, so I doubt it. (Also, this surprised me. -- @arifogel , am I doing something wrong?)

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1790)*

**Comment by progwriter** [comment]
:lgtm: as far as I can tell, but please file the downstream handling issue. I am certain there are issues there.

---

Reviewed 4 of 4 files at r1.
Review status: 0 of 4 files reviewed, all discussions resolved (waiting on @progwriter and @arifogel)

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1790#-:-LGBlELC71xs5qzPn6QX:b9d7ox9)*

**Comment by arifogel** [comment]
:lgtm: with minor suggestions.

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi)

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1790#-LGBZnnA44hQAeKfI8vR:-LGByjKtA2H2kVVYYf0A:b1qwb2y) (no related file):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Okay, I added the entire set of characters that are valid according to the linked document. No information as to whether they are properly handled downstream, of course.

Some of these are new entirely to the Lexer, so I doubt it. (Also, this surprised me. -- @arifogel , am I doing something wrong?)
</blockquote></details>

nah looks fine. juniper is less diverse, so this is not unexpected.

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4, line 5279 at r2](https://reviewable.io/reviews/batfish/batfish/1790#-LGBxxiKCmOuTrhBobrh:-LGBxxiKCmOuTrhBobri:bytgv5e) ([raw file](https://github.com/batfish/batfish/blob/59457755dfd22cf049e8d7c4173a8f49c89f95e6/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4#L5279)):*
> ```ANTLR
> ;
> 
> BACKWARD_SLASH
> ```

Not a big deal, but.. doesn't everyone call this `BACKSLASH`?
Also, if this isn't valid outside of community regex, you should just make this a virtual token or whatever at the top in the `tokens { ... }` block instead of here with a definition.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1790#-:-LGByoGvD-rSv918U41M:btnun05)*

**Comment by dhalperi** [comment]
Reviewed 2 of 2 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4, line 5279 at r2](https://reviewable.io/reviews/batfish/batfish/1790#-LGBxxiKCmOuTrhBobrh:-LGC1akF25RWhjdtwidL:b-xjehyb) ([raw file](https://github.com/batfish/batfish/blob/59457755dfd22cf049e8d7c4173a8f49c89f95e6/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4#L5279)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Not a big deal, but.. doesn't everyone call this `BACKSLASH`?
Also, if this isn't valid outside of community regex, you should just make this a virtual token or whatever at the top in the `tokens { ... }` block instead of here with a definition.
</blockquote></details>

Lol, I tossed a mental coin on whether you'd prefer natural name or parallel structure to `FORWARD_SLASH`. Fixed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1790)*

**Pull request merged**
