### PR TITLE
Generalize receivedFromIp to ReceivedFrom

### PR DESCRIPTION
**Pull request by arifogel**
Generalize BgpRoute attribute receivedFromIp to be one of:
- ReceivedFromIp: for numbered session
- ReceivedFromInterface: for unnumbered session
- ReceivedFromSelf: for originated route

### CODE REVIEW

**Review by corinaminer — COMMENTED** [review]
> Reviewed 45 of 47 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8396)* status: all files reviewed, 2 unresolved discussions (waiting on @arifogel)

___
*[`projects/batfish/src/test/java/org/batfish/dataplane/rib/Bgpv4RibTest.java` line 1108 at r2](https://reviewable.io/reviews/batfish/batfish/8396#-N5Gxs4AE9kGTBlFsTrj:-N5Gxs4AE9kGTBlFsTrk:b-w91jcs) ([raw file](https://github.com/batfish/batfish/blob/31fd8ef350d8c836cfb33ba00deaf9bfcfdfdcf9/projects/batfish/src/test/java/org/batfish/dataplane/rib/Bgpv4RibTest.java#L1108)):*
> ```Java
>             .setOriginatorIp(Ip.ZERO)
>             .setProtocol(RoutingProtocol.IBGP)
>             .setReceivedFrom(ReceivedFromSelf.instance());
> ```

doesn't look like it's necessary to set receivedFrom on this builder at all -- it gets overwritten below. Not a blocker though.
___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpRoute.java` line 498 at r2](https://reviewable.io/reviews/batfish/batfish/8396#-N5H29SI9AHj7dwjhQG-:-N5H29SI9AHj7dwjhQG0:b-3eldnp) ([raw file](https://github.com/batfish/batfish/blob/31fd8ef350d8c836cfb33ba00deaf9bfcfdfdcf9/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpRoute.java#L498)):*
> ```Java
>     _attributes = attributes;
>     _nextHop = nextHop;
>     _receivedFrom = receivedFrom;
> ```

did you consider doing any sanity-checking that the receivedFrom is compatible with the origin mechanism? Not sure if it's a good idea, but worth making a conscious decision one way or the other.
___
*[`projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ReceivedFromInterfaceTest.java` line 15 at r2](https://reviewable.io/reviews/batfish/batfish/8396#-N5H2bjiDpqw5F2bYYt_:-N5H2bjiDpqw5F2bYYta:b-h13lvz) ([raw file](https://github.com/batfish/batfish/blob/31fd8ef350d8c836cfb33ba00deaf9bfcfdfdcf9/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ReceivedFromInterfaceTest.java#L15)):*
> ```Java
> 
>   @Test
>   public void testJacksonSerialiation() {
> ```

Considering that `ReceivedFromInterface` is interned, would it make sense to have the serialization tests test object equality, as in `assertThat(cloned version, is(original))`? same thought for `ReceivedFromIp`.

**Comment by arifogel** [comment]
*[`projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpRoute.java` line 498 at r2](https://reviewable.io/reviews/batfish/batfish/8396#-N5H29SI9AHj7dwjhQG-:-N5H6OLZ-ftozBR1DSZA:b-3rt5b3) ([raw file](https://github.com/batfish/batfish/blob/31fd8ef350d8c836cfb33ba00deaf9bfcfdfdcf9/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpRoute.java#L498)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

did you consider doing any sanity-checking that the receivedFrom is compatible with the origin mechanism? Not sure if it's a good idea, but worth making a conscious decision one way or the other.
</blockquote></details>

I did, but we'd have to rewrite a lot of tests that already have nonsensical combinations of properties. For instance, a bunch of tests have routes with originator Ip.ZERO but OriginationMechanism.LEARNED, which should not be possible.
Not worth the effort in this PR IMO.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8396)* status: all files reviewed, 2 unresolved discussions (waiting on @corinaminer)

___
*[`projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ReceivedFromInterfaceTest.java` line 15 at r2](https://reviewable.io/reviews/batfish/batfish/8396#-N5H2bjiDpqw5F2bYYt_:-N5H6jP70xZ7Ccf_-DH8:btegz3w) ([raw file](https://github.com/batfish/batfish/blob/31fd8ef350d8c836cfb33ba00deaf9bfcfdfdcf9/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/ReceivedFromInterfaceTest.java#L15)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Considering that `ReceivedFromInterface` is interned, would it make sense to have the serialization tests test object equality, as in `assertThat(cloned version, is(original))`? same thought for `ReceivedFromIp`.
</blockquote></details>

Fixed and done

**Review by corinaminer — COMMENTED** [review]
:lgtm:

> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8396#-:-N5IFIQx89VCv8ZijH2P:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpRoute.java` line 498 at r2](https://reviewable.io/reviews/batfish/batfish/8396#-N5H29SI9AHj7dwjhQG-:-N5IEpXp6KgP9IVd7p4U:b190y2l) ([raw file](https://github.com/batfish/batfish/blob/31fd8ef350d8c836cfb33ba00deaf9bfcfdfdcf9/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpRoute.java#L498)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

I did, but we'd have to rewrite a lot of tests that already have nonsensical combinations of properties. For instance, a bunch of tests have routes with originator Ip.ZERO but OriginationMechanism.LEARNED, which should not be possible.
Not worth the effort in this PR IMO.
</blockquote></details>

ack, resolving.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8396)* status: all files reviewed, 1 unresolved discussion (waiting on @corinaminer)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/8396#-N5IFIDo84eio-0qid2Y:-N5IFIDo84eio-0qid2Z:b-8j58zh) (no related file):*
self merge only

___

**Review by corinaminer — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8396)* status: all files reviewed, 1 unresolved discussion (waiting on @corinaminer)

**Review by corinaminer — COMMENTED** [review]
> Reviewed 14 of 14 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8396)* status: all files reviewed, 1 unresolved discussion (waiting on @corinaminer)

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8396)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Pull request merged**
