### PR TITLE
implement ios-xe policy-map class-default

### PR DESCRIPTION
**Pull request by arifogel**

### CODE REVIEW

**Comment by arifogel** [comment]
Review status: 0 of 9 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1318#-LBiOwrm7q16M1Q8jYRG:-LBiOwrm7q16M1Q8jYRH:b-dru6fy) (no related file):*
After #1317

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1318)*

**Comment by dhalperi** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1318)*

**Comment by sfraint** [comment]
Reviewed 8 of 9 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1318)*

**Comment by dhalperi** [comment]
Reviewed 2 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1318)*

**Comment by sfraint** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1318#-:-LC06D9e9XZPAiWGqbsQ:bnfp4nl)*

**Comment by sfraint** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1318)*

**Pull request merged**
