### PR TITLE
JunOS: rework SRX cross-zone-policy

### PR DESCRIPTION
**Pull request by dhalperi**
We want to be able to analyze the pure-packet-header
parts of the cross-zone policy. To support this, move the
"matchSourceInterface in from-zone" part of the filter
from inside the zone~A~to~zone~B filter to the parent.

The traces change a little, for the better. Instead of "Matched
cross-zone policy", it's now "Permitted by .." and "Denied by ..".

Additionally, since from-zone junos-host is a real thing, moved the
"permit from junos-host" term to after cross-zone policy evaluation.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6352)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @anothermattbrown, @corinaminer, and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6352#-MKDTGtK77NVhj004HNT:-MKDTGtK77NVhj004HNU:bcpm598) (no related file):*
Note that in the first commit I flesh out the parsing test to have real useful policy, in the second commit I make the change. Worth diffing the refs in addition to reviewing the code and test updates.

---

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6352)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @anothermattbrown, @corinaminer, and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java, line 2436 at r2](https://reviewable.io/reviews/batfish/batfish/6352#-MKDTdOWAEEzrbjJkpXm:-MKDTdOWAEEzrbjJkpXn:bf8qkeu) ([raw file](https://github.com/batfish/batfish/blob/342cda6016bce7d4872df2aaf739a6345507af20/projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java#L2436)):*
> ```
> not a global security policy
> ```
note that this no longer applies where I moved this to. Now it's just `junos-host`.

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6352)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @anothermattbrown, @corinaminer, and @sfraint)

___
*[projects/batfish/src/test/java/org/batfish/representation/juniper/JuniperConfigurationTest.java, line 679 at r2](https://reviewable.io/reviews/batfish/batfish/6352#-MKDTmLg5XfP_iAHxg83:-MKDTmLg5XfP_iAHxg84:bm1ng3q) ([raw file](https://github.com/batfish/batfish/blob/b9cafecdda02f14c0646fc840383b2f07a557bf8/projects/batfish/src/test/java/org/batfish/representation/juniper/JuniperConfigurationTest.java#L679)):*
> ```
>         new ConcreteFirewallFilter(zoneToZoneFilter("junos-host", "toZone"), Family.INET);
>     zone.getFromZonePolicies().put(crossZoneFilter.getName(), crossZoneFilter);
> ```
FYI this is just making the test honor the VS /parser semantics.

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6352)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @anothermattbrown, @corinaminer, @dhalperi, and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6352#-MKG8jEe--m3u_lKyL4d:-MKG8jEe--m3u_lKyL4e:bq78hje) (no related file):*
do we have semantic tests (i.e. using `AclTracer`) of the VI ACLs?

---
___
*[projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java, line 2248 at r2](https://reviewable.io/reviews/batfish/batfish/6352#-MKG6Vgb1IjEqZZRKa7S:-MKG6Vgb1IjEqZZRKa7T:b-yg1974) ([raw file](https://github.com/batfish/batfish/blob/b9cafecdda02f14c0646fc840383b2f07a557bf8/projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java#L2248)):*
> ```
>                     new AndMatchExpr(
>                         ImmutableList.of(matchSrcInterface, new PermittedByAcl(filterName))))
> ```
This expr is identical to the one from the previous line, so it seems to always be blocked. Should this be `not(permittedByAcl(filterName))`?
___
*[projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java, line 2256 at r2](https://reviewable.io/reviews/batfish/batfish/6352#-MKG7Yy---3Rso-b4nsu:-MKG7Yy---3Rso-b4nsv:b8avfx8) ([raw file](https://github.com/batfish/batfish/blob/b9cafecdda02f14c0646fc840383b2f07a557bf8/projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java#L2256)):*
> ```
> zoneAclLines.add(
> ```
is the idea that this will be intentionally blocked if a `FirewallFilter` in the loop above has no `fromZone` (i.e. so we use the `.orElse(OriginatingFromDevice.INSTANCE)`)?

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6352)* status: all files reviewed, 3 unresolved discussions (waiting on @corinaminer, @dhalperi, and @sfraint)

**Comment by dhalperi** [comment]
Replaced by #6360

**Pull request closed without merging**
