### PR TITLE
Ipsec proposals (transform-sets) - improve extraction

### PR DESCRIPTION
**Pull request by haverma**
- Included representation for  authentication algorithms  using the `Authentication Header` protocol in Cisco and Juniper transform-sets to the data-model([cisco](https://www.cisco.com/c/en/us/td/docs/ios/12_2/security/command/reference/srfipsec.html#wp1017694), [juniper](https://www.juniper.net/documentation/en_US/junos/topics/task/configuration/services-ipsec-proposals-configuring.html))

- Added rules for parsing  Aruba ESP encryption algorithm names  having the format - `esp-aes[XXX]`

### CODE REVIEW

**Comment by dhalperi** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1579#-LEBsHpv2JJfuocrv1aX:-LEBsHpv2JJfuocrv1aY:br8ncpi) (no related file):*
Add parsing examples for missing algorithms.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpsecProposal.java, line 62 at r2](https://reviewable.io/reviews/batfish/batfish/1579#-LEBmz7D6_R4nxprFdmG:-LEBmz7D6_R4nxprFdmH:b-1kab9a) ([raw file](https://github.com/batfish/batfish/blob/c9fc2ba9e198a10d516f3b6f9420c3fd8d9bf4ab/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpsecProposal.java#L62)):*
> ```Java
>     IpsecProposal p = new IpsecProposal("NOPFS_ESP_DES_MD5");
>     p.getProtocols().add(IpsecProtocol.ESP);
>     ;
> ```

delete empty statement.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpsecProposal.java, line 148 at r2](https://reviewable.io/reviews/batfish/batfish/1579#-LEBn3KuE7ZXCjm04va2:-LEBn3KuE7ZXCjm04va3:betktuu) ([raw file](https://github.com/batfish/batfish/blob/c9fc2ba9e198a10d516f3b6f9420c3fd8d9bf4ab/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpsecProposal.java#L148)):*
> ```Java
>   }
> 
>   public void setProtocols(SortedSet<IpsecProtocol> protocol) {
> ```

add a deprecated setter for the old `protocol` field that just calls `setProtocols(singleton)`. This will support old data easily.

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/IpsecProposalMatchers.java, line 37 at r2](https://reviewable.io/reviews/batfish/batfish/1579#-LEBnKAPBke7SYQliEnH:-LEBnKAPBke7SYQliEnI:b-xt26x) ([raw file](https://github.com/batfish/batfish/blob/c9fc2ba9e198a10d516f3b6f9420c3fd8d9bf4ab/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/IpsecProposalMatchers.java#L37)):*
> ```Java
>    * specified {@code protocols}
>    */
>   public static HasProtocols hasProtocols(SortedSet<IpsecProtocol> protocols) {
> ```

Make this more graceful in what it accepts. Just `Set`?

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_security.g4, line 114 at r2](https://reviewable.io/reviews/batfish/batfish/1579#-LEBpuot2HmcxN05qQ7Q:-LEBpuot2HmcxN05qQ7R:bawtvzq) ([raw file](https://github.com/batfish/batfish/blob/c9fc2ba9e198a10d516f3b6f9420c3fd8d9bf4ab/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_security.g4#L114)):*
> ```ANTLR
>    AH
>    | ESP
>    | BUNDLE
> ```

alphabetize. please.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1579)*

**Comment by dhalperi** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EncryptionAlgorithm.java, line 15 at r3](https://reviewable.io/reviews/batfish/batfish/1579#-LECyaCjAOjtsDlDj7wz:-LECyaCjAOjtsDlDj7x-:b-65qvxq) ([raw file](https://github.com/batfish/batfish/blob/b8eae2357976caa2a27f382fe6955f812b2c4715/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EncryptionAlgorithm.java#L15)):*
> ```
> AES_SEAL_160,
> ```

I don't think this is a flavor of AES. Is this a typo?

---

*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 8039 at r3](https://reviewable.io/reviews/batfish/batfish/1579#-LECzbQH-zUwVeT6jlMA:-LECzbQH-zUwVeT6jlMB:b-55qfg) ([raw file](https://github.com/batfish/batfish/blob/b8eae2357976caa2a27f382fe6955f812b2c4715/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L8039)):*
> ```Java
> 
>   private EncryptionAlgorithm toEncryptionAlgorithm(Ipsec_encryptionContext ctx) {
>     int strength;
> ```

keep the local variable inside the `if`s below? Is there any reason it needs to leak between clauses?

---

*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 8041 at r3](https://reviewable.io/reviews/batfish/batfish/1579#-LECzjtCExa3NTLdIqxt:-LECzjtCExa3NTLdIqxu:bwbbwrp) ([raw file](https://github.com/batfish/batfish/blob/b8eae2357976caa2a27f382fe6955f812b2c4715/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L8041)):*
> ```Java
>     int strength;
>     if (ctx.ESP_AES() != null) {
>       strength = ctx.strength == null ? 128 : toInteger(ctx.strength);
> ```

keep `int strength =` here...

---

*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 8057 at r3](https://reviewable.io/reviews/batfish/batfish/1579#-LECzmSm8n0stGAa-y3H:-LECzmSm8n0stGAa-y3I:b-ny7fr8) ([raw file](https://github.com/batfish/batfish/blob/b8eae2357976caa2a27f382fe6955f812b2c4715/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L8057)):*
> ```Java
>       return EncryptionAlgorithm.THREEDES_CBC;
>     } else if (ctx.ESP_GCM() != null) {
>       strength = ctx.strength == null ? 128 : toInteger(ctx.strength);
> ```

and you can also declare `int strength` here...

---

*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 8069 at r3](https://reviewable.io/reviews/batfish/batfish/1579#-LECzogl6ZioW-mmrXoh:-LECzogl6ZioW-mmrXoi:b-dckpbc) ([raw file](https://github.com/batfish/batfish/blob/b8eae2357976caa2a27f382fe6955f812b2c4715/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L8069)):*
> ```Java
>       }
>     } else if (ctx.ESP_GMAC() != null) {
>       strength = ctx.strength == null ? 128 : toInteger(ctx.strength);
> ```

and here.

even though it seems redundant, I'd argue it keeps the code easier to read since the strengths are local to the `if` clauses.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1579)*

**Comment by dhalperi** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1579#-:-LED7JYkAr2TUVWMaZW-:bnfp4nl)*

**Comment by haverma** [comment]
Review status: 20 of 21 files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EncryptionAlgorithm.java, line 15 at r3](https://reviewable.io/reviews/batfish/batfish/1579#-LECyaCjAOjtsDlDj7wz:-LED6y9z8CkR0Ai1X1aC:bam53dc) ([raw file](https://github.com/batfish/batfish/blob/b8eae2357976caa2a27f382fe6955f812b2c4715/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EncryptionAlgorithm.java#L15)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> AES_SEAL_160,
> ```

I don't think this is a flavor of AES. Is this a typo?
</blockquote></details>

It was not a typo, I misinterpreted it as an AES variant, but it is actually an alternative to AES according to https://www.cisco.com/c/en/us/support/docs/security-vpn/ipsec-negotiation-ike-protocols/50880-seal-rtr-tunnel-confg.html

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1579)*

**Pull request merged**
