### PR TITLE
FRR: Adding max-metric router-lsa administrative support

### PR DESCRIPTION
**Pull request by kylehoferamzn**
Nothing special here.  Should generally align with FRR documentation and is setup similar to Cisco's implementation.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6577)* status: all files reviewed, 4 unresolved discussions (waiting on @kylehoferamzn)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrr_ospf.g4, line 18 at r1](https://reviewable.io/reviews/batfish/batfish/6577#-MRSEtjwEKjW1aPi90_I:-MRSEtjwEKjW1aPi90_J:babyg39) ([raw file](https://github.com/batfish/batfish/blob/e8a97fb6b3b638e013388146ca47fd947d4d45fc/projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrr_ospf.g4#L18)):*
> ```
> ro_max_metric_router_lsa_administrative
> ```

move up to alphabetize?
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4, line 741 at r1](https://reviewable.io/reviews/batfish/batfish/6577#-MRSFq257d0x9CVN4crO:-MRSFq257d0x9CVN4crP:b-j03qz5) ([raw file](https://github.com/batfish/batfish/blob/e8a97fb6b3b638e013388146ca47fd947d4d45fc/projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4#L741)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> ROUTER_LSA
> :
>   'router-lsa'
> ;
> ```
</details>

move down 1 to alphabetize?
___
*[projects/batfish/src/main/java/org/batfish/grammar/cumulus_frr/CumulusFrrConfigurationBuilder.java, line 692 at r1](https://reviewable.io/reviews/batfish/batfish/6577#-MRSFtOm1rT46hGFeeV9:-MRSFtOm1rT46hGFeeVA:beosqjp) ([raw file](https://github.com/batfish/batfish/blob/e8a97fb6b3b638e013388146ca47fd947d4d45fc/projects/batfish/src/main/java/org/batfish/grammar/cumulus_frr/CumulusFrrConfigurationBuilder.java#L692)):*
> ```
> _max_metric_router_lsa_administ
> ```
move up to alphabetize?
___
*[projects/batfish/src/main/java/org/batfish/representation/cumulus/OspfProcess.java, line 21 at r1](https://reviewable.io/reviews/batfish/batfish/6577#-MRSG1a8BqNXBorGIH-2:-MRSG1a8BqNXBorGIH-3:bcdnlhe) ([raw file](https://github.com/batfish/batfish/blob/e8a97fb6b3b638e013388146ca47fd947d4d45fc/projects/batfish/src/main/java/org/batfish/representation/cumulus/OspfProcess.java#L21)):*
> ```Java
> 
>   private Map<CumulusRoutingProtocol, RedistributionPolicy> _redistributionPolicies;
>   private boolean _maxMetricRouterLsa;
> ```

normally we make these `@Nullable Boolean` so we can distinguish between whether they've been configured (to true or false).

Then we can enforce the default explicitly during conversion rather than implicitly during class construction.

Using `boolean value = firstNonNull(o.getNullableBoolean(), Boolean.FALSE)`.

**Review by kylehoferamzn — COMMENTED** [review]
Updated per comments

> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6577#-:-MRSLURuCiyWLgRQD91g:b1l8cch)* status: 2 of 7 files reviewed, all discussions resolved (waiting on @dhalperi)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6577)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6577)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
