### PR TITLE
Allinone: add a first example of a unit test

### PR DESCRIPTION
**Pull request by dhalperi**
This is for #1084

Thoughts?

### CODE REVIEW

**Comment by dhalperi** [comment]
*[a discussion](https://beta.reviewable.io/reviews/batfish/batfish/1202#-LAPJ4he6nAaRrjVP113:-LAPJ4he6nAaRrjVP114:b-iu0zfh) (no related file):*
Prevent merge.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1202)*

**Comment by dhalperi** [comment]
Reviewed 17 of 22 files at r1.
Review status: 17 of 22 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1202)*

**Comment by dhalperi** [comment]
*[projects/allinone/src/test/java/org/batfish/allinone/ExampleTests.java, line 93 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1202#-LAPKN2DBGIY5IDm6ahO:-LAPKN2DBGIY5IDm6ahP:b-il3gpp) ([raw file](https://github.com/batfish/batfish/blob/cf016dd58b514425c5c5595ac59f67bc7635620b/projects/allinone/src/test/java/org/batfish/allinone/ExampleTests.java#L93)):*
> ```Java
>   public void aclReachability() throws IOException {
>     AclReachabilityQuestion q = new AclReachabilityQuestion();
>     AclReachabilityAnswerer a = new AclReachabilityAnswerer(q, _batfish);
> ```

should clone question with BatfishObjectMapper to ensure it's re-serializable.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1202)*

**Comment by arifogel** [comment]
Reviewed 21 of 22 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/allinone/src/test/java/org/batfish/allinone/ExampleTests.java, line 93 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1202#-LAPKN2DBGIY5IDm6ahO:-LAPsX2m3RYdJlOaJEqn:bqun6ax) ([raw file](https://github.com/batfish/batfish/blob/cf016dd58b514425c5c5595ac59f67bc7635620b/projects/allinone/src/test/java/org/batfish/allinone/ExampleTests.java#L93)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

should clone question with BatfishObjectMapper to ensure it's re-serializable.
</blockquote></details>

Would it also be useful here to check that deserialized/cloned answer `equals` original answer?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1202)*

**Comment by ratulm** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/allinone/src/test/java/org/batfish/allinone/ExampleTests.java, line 93 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1202#-LAPKN2DBGIY5IDm6ahO:-LAX2i2hC8sddwGoOODD:btg315l) ([raw file](https://github.com/batfish/batfish/blob/cf016dd58b514425c5c5595ac59f67bc7635620b/projects/allinone/src/test/java/org/batfish/allinone/ExampleTests.java#L93)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Would it also be useful here to check that deserialized/cloned answer `equals` original answer?
</blockquote></details>

Seems like a test of (de)serialization should be as junit tests for specific questions and don't need the example testrig at all. In the interest of speed, we should perhaps focus just on getting the answers right.

---

*[projects/allinone/src/test/java/org/batfish/allinone/ExampleTests.java, line 97 at r3](https://beta.reviewable.io/reviews/batfish/batfish/1202#-LAX39XL6kxc2y1Enyjb:-LAX39XL6kxc2y1Enyjc:b3zixru) ([raw file](https://github.com/batfish/batfish/blob/2b1b010b2a9017cff5f8f8578580b60fb0387724/projects/allinone/src/test/java/org/batfish/allinone/ExampleTests.java#L97)):*
> ```Java
>     assertThat(
>         BatfishObjectMapper.writePrettyString(e),
>         equalTo(getResourceString(REF_PATH + "/aclReachability.ref")));
> ```

Ref testing is one option. Would we stick with that or move to directly looking for what is expected in the answer? Ref tests are certainly easier to write and cover most things about the answer (but that also introduces fragility). I suppose we can also go test by test.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1202)*

**Comment by ratulm** [comment]
Overall, looks like we need something like this. Would be nice if these tests were triggered as a special command (batfish_test_e2e) and ignored as part of what is currently batfish_test_all. 

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1202#-:-LAX3kSL5dNgLfNVZ5v6:b-wd3s3s)*

**Comment by arifogel** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[projects/allinone/src/test/java/org/batfish/allinone/ExampleTests.java, line 93 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1202#-LAPKN2DBGIY5IDm6ahO:-LAZ8ZP3D3og0Co7MI8G:bm3bkks) ([raw file](https://github.com/batfish/batfish/blob/cf016dd58b514425c5c5595ac59f67bc7635620b/projects/allinone/src/test/java/org/batfish/allinone/ExampleTests.java#L93)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

Seems like a test of (de)serialization should be as junit tests for specific questions and don't need the example testrig at all. In the interest of speed, we should perhaps focus just on getting the answers right.
</blockquote></details>

@ratulm Agreed

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1202)*

**Comment by dhalperi** [comment]
Others have used this as a model, closing.

**Pull request closed without merging**
