### PR TITLE
update pathDiff to use the sourceIpAssignment

### PR DESCRIPTION
**Pull request by anothermattbrown**
Go back to removing srcIp from headerspace when converting ReachabilitySettings to ReachabilityParameters.

Now we modify pathDiff to give meaning to the location and srcIp specifiers: we only originate from edges for which the source interface is a specified source location, and we use the source Ip constraint corresponding to that location.

### CODE REVIEW

**Comment by dhalperi** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 2987 at r1](https://reviewable.io/reviews/batfish/batfish/1562#-LDytNya70h7hKcAlPqb:-LDytNya70h7hKcAlPqc:b-bn8hts) ([raw file](https://github.com/batfish/batfish/blob/83b0bfbcd12e0047a645c171d081a85d292e015b/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L2987)):*
> ```Java
> 
>   @Override
>   public AnswerElement pathDiff(ReachabilityParameters reachabilityParameters) {
> ```

How can we test this?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1562)*

**Comment by dhalperi** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/allinone/src/test/java/org/batfish/allinone/PathDiffTest.java, line 33 at r2](https://reviewable.io/reviews/batfish/batfish/1562#-LEBt4sWCv3LetOIAtft:-LEBt4sWCv3LetOIAtfu:budp183) ([raw file](https://github.com/batfish/batfish/blob/6f6f0cc1262b668c6f78b0d142839cc4938623eb/projects/allinone/src/test/java/org/batfish/allinone/PathDiffTest.java#L33)):*
> ```Java
> public class PathDiffTest {
>   /** 3.3.3.3/32 <--- A B ---> 4.4.4.4/32 */
>   private static SortedMap<String, Configuration> disconnectedTwoNodeNetwork() {
> ```

This looks right to me. Maybe @progwriter can take a quick lookthrough and see if it needs anything? He's written many more of these tests than I.

---

*[projects/batfish/src/test/java/org/batfish/main/BatfishTestUtils.java, line 106 at r2](https://reviewable.io/reviews/batfish/batfish/1562#-LEBtQRl1b-pv6mfyfHn:-LEBtQRl1b-pv6mfyfHo:b-wemtn4) ([raw file](https://github.com/batfish/batfish/blob/6f6f0cc1262b668c6f78b0d142839cc4938623eb/projects/batfish/src/test/java/org/batfish/main/BatfishTestUtils.java#L106)):*
> ```Java
>     Path containerDir = tempFolder.newFolder().toPath();
>     settings.setContainerDir(containerDir);
>     if (!baseConfigs.isEmpty()) {
> ```

Am I reading correctly that the code relies on these to be `@Nonnull`? If so, please annotate.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1562#-:-LEBtbjh2RTZPnUcfjPR:bnfp4nl)*

**Comment by progwriter** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/allinone/src/test/java/org/batfish/allinone/PathDiffTest.java, line 33 at r2](https://reviewable.io/reviews/batfish/batfish/1562#-LEBt4sWCv3LetOIAtft:-LEBwVFp1bE3EbLy_cv7:b-v7usg1) ([raw file](https://github.com/batfish/batfish/blob/6f6f0cc1262b668c6f78b0d142839cc4938623eb/projects/allinone/src/test/java/org/batfish/allinone/PathDiffTest.java#L33)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

This looks right to me. Maybe @progwriter can take a quick lookthrough and see if it needs anything? He's written many more of these tests than I.
</blockquote></details>

Construction looks of the test looks fine to me.

---

*[projects/allinone/src/test/java/org/batfish/allinone/PathDiffTest.java, line 129 at r2](https://reviewable.io/reviews/batfish/batfish/1562#-LEBwFWW-aa-5TSvrfQ5:-LEBwFWW-aa-5TSvrfQ6:bd3k9f2) ([raw file](https://github.com/batfish/batfish/blob/6f6f0cc1262b668c6f78b0d142839cc4938623eb/projects/allinone/src/test/java/org/batfish/allinone/PathDiffTest.java#L129)):*
> ```Java
>   public void testPathDiff() throws IOException {
>     TemporaryFolder tmp = new TemporaryFolder();
>     tmp.create();
> ```

fyi you can make tmp folder a `@Rule`

---

*[projects/allinone/src/test/java/org/batfish/allinone/PathDiffTest.java, line 154 at r2](https://reviewable.io/reviews/batfish/batfish/1562#-LEBxHWU73Q8JpQoI3Nl:-LEBxHWU73Q8JpQoI3Nm:bbzx9yq) ([raw file](https://github.com/batfish/batfish/blob/6f6f0cc1262b668c6f78b0d142839cc4938623eb/projects/allinone/src/test/java/org/batfish/allinone/PathDiffTest.java#L154)):*
> ```Java
> 
>     assertThat(flowHistory.getTraces().entrySet(), hasSize(2));
>     assertThat(
> ```

Not immediately clear why this assertion should be true, and where is the "diff"; but that could be because I don't remember how flow history works. (this is non-blocking).

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1562)*

**Comment by anothermattbrown** [comment]
Review status: 4 of 6 files reviewed at latest revision, all discussions resolved.

---

*[projects/allinone/src/test/java/org/batfish/allinone/PathDiffTest.java, line 129 at r2](https://reviewable.io/reviews/batfish/batfish/1562#-LEBwFWW-aa-5TSvrfQ5:-LEC3RXPCG8takJ86mc6:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/6f6f0cc1262b668c6f78b0d142839cc4938623eb/projects/allinone/src/test/java/org/batfish/allinone/PathDiffTest.java#L129)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

fyi you can make tmp folder a `@Rule`
</blockquote></details>

Done.

---

*[projects/allinone/src/test/java/org/batfish/allinone/PathDiffTest.java, line 154 at r2](https://reviewable.io/reviews/batfish/batfish/1562#-LEBxHWU73Q8JpQoI3Nl:-LEByZdS8bvcKBf1_XRB:b-hwz405) ([raw file](https://github.com/batfish/batfish/blob/6f6f0cc1262b668c6f78b0d142839cc4938623eb/projects/allinone/src/test/java/org/batfish/allinone/PathDiffTest.java#L154)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

Not immediately clear why this assertion should be true, and where is the "diff"; but that could be because I don't remember how flow history works. (this is non-blocking).
</blockquote></details>

The diff is in the values of the traces map. I'm only matching on the keys because I wanted a high-level check.

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 2987 at r1](https://reviewable.io/reviews/batfish/batfish/1562#-LDytNya70h7hKcAlPqb:-LEByryn0julAnRC_O_i:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/83b0bfbcd12e0047a645c171d081a85d292e015b/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L2987)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

How can we test this?
</blockquote></details>

Done.

---

*[projects/batfish/src/test/java/org/batfish/main/BatfishTestUtils.java, line 106 at r2](https://reviewable.io/reviews/batfish/batfish/1562#-LEBtQRl1b-pv6mfyfHn:-LEC3OoN92f-uTLMzIrw:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/6f6f0cc1262b668c6f78b0d142839cc4938623eb/projects/batfish/src/test/java/org/batfish/main/BatfishTestUtils.java#L106)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Am I reading correctly that the code relies on these to be `@Nonnull`? If so, please annotate.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1562)*

**Pull request merged**
