### PR TITLE
Prune ACL reachability jobs to find blocking lines

### PR DESCRIPTION
**Pull request by corinaminer**
Moves method `optimizedProgram()` from `NodJob` to its grandparent `Z3ContextJob` so that `NodJob`'s aunt/uncle (auncle?) `NodFirstUnsatJob` can also make use of it.

### CODE REVIEW

**Comment by arifogel** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish/src/main/java/org/batfish/z3/NodFirstUnsatJob.java, line 72 at r1](https://reviewable.io/reviews/batfish/batfish/1387#-LCW0Gcl-WzvA7zPO56-:-LCW0GcmDnLgLOiRMmQz:bhh1k75) ([raw file](https://github.com/batfish/batfish/blob/4e79cf7f2fbc39a144782d314784c2ae1f0693aa/projects/batfish/src/main/java/org/batfish/z3/NodFirstUnsatJob.java#L72)):*
> ```Java
> 
>   @Nonnull
>   private NodProgram getNodProgram(Context ctx) {
> ```

Could this function also be moved up to an ancestor class? Looks like the code that uses it in `NodJob` is identical.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1387)*

**Comment by anothermattbrown** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1387)*

**Comment by corinaminer** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/java/org/batfish/z3/NodFirstUnsatJob.java, line 72 at r1](https://reviewable.io/reviews/batfish/batfish/1387#-LCW0Gcl-WzvA7zPO56-:-LCW0pUf-R9Ub45fzENF:b-sb0i0t) ([raw file](https://github.com/batfish/batfish/blob/4e79cf7f2fbc39a144782d314784c2ae1f0693aa/projects/batfish/src/main/java/org/batfish/z3/NodFirstUnsatJob.java#L72)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Could this function also be moved up to an ancestor class? Looks like the code that uses it in `NodJob` is identical.
</blockquote></details>

only the return statement is identical. I considered raising some abstracted version of this function to an ancestor class, but didn't seem worth it.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1387)*

**Comment by arifogel** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[projects/batfish/src/main/java/org/batfish/z3/NodFirstUnsatJob.java, line 72 at r1](https://reviewable.io/reviews/batfish/batfish/1387#-LCW0Gcl-WzvA7zPO56-:-LCW4ZTHEsHoV4nq-Gg2:b-3dueee) ([raw file](https://github.com/batfish/batfish/blob/4e79cf7f2fbc39a144782d314784c2ae1f0693aa/projects/batfish/src/main/java/org/batfish/z3/NodFirstUnsatJob.java#L72)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

only the return statement is identical. I considered raising some abstracted version of this function to an ancestor class, but didn't seem worth it.
</blockquote></details>

Oh right, never mind.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1387)*

**Pull request merged**
