### PR TITLE
infrastructure for Eclipse external annotations

### PR DESCRIPTION
**Pull request by arifogel**
@dhalperi Please review pom changes

### CODE REVIEW

**Comment by dhalperi** [comment]
Review status: 108 of 120 files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1560#-LDxH_PTE5lbNSMdZC9z:-LDxH_PTE5lbNSMdZCA-:b-5btpy7) (no related file):*
Reviewing this, I have become very confused. Why does any of this, at all, go in Batfish? Can't you just build yourself an annotation database and configure Eclipse to use it?

Nothing about `eea-parent` seems related to Batfish.

---

*[projects/pom.xml, line 85 at r1](https://reviewable.io/reviews/batfish/batfish/1560#-LDxGQRKB8XBsrwO8SHd:-LDxGQRKB8XBsrwO8SHe:b-igicn6) ([raw file](https://github.com/batfish/batfish/blob/d2ff64fc1a46d5de5477e2c9133abb519db0db1d/projects/pom.xml#L85)):*
> ```XML
> 
>     
>     <m2e.jdt.annotationpath>${project.basedir}/../eea-parent/eea-all/target/eea-all-${version}.jar</m2e.jdt.annotationpath>
> ```

this seems fishy. Should not ever see any `..` in these.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1560)*

**Comment by arifogel** [comment]
Review status: 7 of 16 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1560#-LDxH_PTE5lbNSMdZC9z:-LEAXTVy-gSFTwxNa4O0:brx61w9) (no related file):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Reviewing this, I have become very confused. Why does any of this, at all, go in Batfish? Can't you just build yourself an annotation database and configure Eclipse to use it?

Nothing about `eea-parent` seems related to Batfish.
</blockquote></details>

I have removed `eea-parent` in interest of proper separation of concerns. We lost some functionality, but nothing critical. See comment in parent pom.

---

*[projects/pom.xml, line 85 at r1](https://reviewable.io/reviews/batfish/batfish/1560#-LDxGQRKB8XBsrwO8SHd:-LEAXh_D1OoBVa9gl_7I:b-886gsx) ([raw file](https://github.com/batfish/batfish/blob/d2ff64fc1a46d5de5477e2c9133abb519db0db1d/projects/pom.xml#L85)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

this seems fishy. Should not ever see any `..` in these.
</blockquote></details>

Fixed

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1560)*

**Comment by dhalperi** [comment]
Review status: 8 of 16 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[projects/allinone/pom.xml, line 142 at r3](https://reviewable.io/reviews/batfish/batfish/1560#-LEL_2UZ9nAFY-ewtn5y:-LEL_2UZ9nAFY-ewtn5z:btia7km) ([raw file](https://github.com/batfish/batfish/blob/af6afe7485821e97cbf004ed464094c9b332c3b7/projects/allinone/pom.xml#L142)):*
> ```XML
>       <groupId>org.lastnpe.eea</groupId>
>       <artifactId>jdk-eea</artifactId>
>     </dependency>
> ```

this adds these jars as compile-time dependencies for all our code -- this doesn't seem right, as they shouldn't be shipped with our jars.

Is there a proper way to integrate this just for eclipse IDE work (using, say, m2eclipse config for example)?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1560)*

**Comment by arifogel** [comment]
Review status: 8 of 16 files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/allinone/pom.xml, line 142 at r3](https://reviewable.io/reviews/batfish/batfish/1560#-LEL_2UZ9nAFY-ewtn5y:-LELfvHx2WinH5xStvvC:b-6qs2ed) ([raw file](https://github.com/batfish/batfish/blob/af6afe7485821e97cbf004ed464094c9b332c3b7/projects/allinone/pom.xml#L142)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

this adds these jars as compile-time dependencies for all our code -- this doesn't seem right, as they shouldn't be shipped with our jars.

Is there a proper way to integrate this just for eclipse IDE work (using, say, m2eclipse config for example)?
</blockquote></details>

Could not figure out how to do it in eclipse-specific fashion.
However I changed to `prodded` scope so it doesn't get built into the jars.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1560)*

**Comment by arifogel** [comment]
Review status: 8 of 16 files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/allinone/pom.xml, line 142 at r3](https://reviewable.io/reviews/batfish/batfish/1560#-LEL_2UZ9nAFY-ewtn5y:-LELg0R45BoSQicYqlm-:bajwg8y) ([raw file](https://github.com/batfish/batfish/blob/af6afe7485821e97cbf004ed464094c9b332c3b7/projects/allinone/pom.xml#L142)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Could not figure out how to do it in eclipse-specific fashion.
However I changed to `prodded` scope so it doesn't get built into the jars.
</blockquote></details>

`provided`

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1560)*

**Comment by dhalperi** [comment]
Review status: 12 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1560#-LDxH_PTE5lbNSMdZC9z:-LEM5w6L6E7OmoIFPi0c:blqumix) (no related file):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

I have removed `eea-parent` in interest of proper separation of concerns. We lost some functionality, but nothing critical. See comment in parent pom.
</blockquote></details>

How did you choose provided vs optional? If `optional` works in Eclipse, that might be more correct.

`provided` means that we expect at runtime the jar will be there.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1560)*

**Comment by arifogel** [comment]
Review status: 12 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1560#-LDxH_PTE5lbNSMdZC9z:-LEMfO_e3rMlO07FM2KO:b-pyu9m4) (no related file):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

How did you choose provided vs optional? If `optional` works in Eclipse, that might be more correct.

`provided` means that we expect at runtime the jar will be there.
</blockquote></details>

From my read of:
https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.htm 
It sounds like we do want it to be an optional dependency, but that optional-ness is orthogonal to scope. I just chose `provided` scope so that the eaa files would not be included in the bundle. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1560)*

**Pull request merged**
