### PR TITLE
Tests for WorkMgrServiceV2, ensure correct api key header is used

### PR DESCRIPTION
**Pull request by progwriter**
As promised, adding tests for #754. Combining a straight-forward in-memory authorizer with jersey tests to check that the API key is extracted from the correct HTTP header.

---
This change is [Reviewable](https://reviewable.io/reviews/batfish/batfish/764)

### CODE REVIEW

**Comment by dhalperi** [comment]
minor comments 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/authorizer/MapAuthorizer.java, line 10 at r1](https://reviewable.io:443/reviews/batfish/batfish/764#-L0LGtUVCEmTL30vYeEA:-L0LGtUVCEmTL30vYeEB:b-1g3vls) ([raw file](https://github.com/batfish/batfish/blob/8a871b8b32403822819726ea8a3b50a9f1c1766d/projects/coordinator/src/main/java/org/batfish/coordinator/authorizer/MapAuthorizer.java#L10)):*
> ```Java
> public class MapAuthorizer implements Authorizer {
>   private HashMap<String, List<String>> _permissionMap;
> ```

Do you anticipate this being used more broadly, or just for testing?

If former, suggest adding tests and also thinking about thread safety.

If latter, move it into the `test` part of the code instead of `main`?

---

*[projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrServiceV2Test.java, line 148 at r1](https://reviewable.io:443/reviews/batfish/batfish/764#-L0LGqtH44V2q-VPAZ7P:-L0LGqtINhmZYHoMqXoa:bois2ay) ([raw file](https://github.com/batfish/batfish/blob/8a871b8b32403822819726ea8a3b50a9f1c1766d/projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrServiceV2Test.java#L148)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>
>     // And ensure that right key, but in the wrong (old) header field does not work either
>     resp =
>         getContainersTarget()
>             .path(containerName)
>             .request()
>             .header(CoordConsts.SVC_KEY_API_KEY, myKey)
>             .get();
>     assertThat(resp.getStatus(), equalTo(FORBIDDEN.getStatusCode()));
</details>

Can drop this part I think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/764#-:-L0LI1NmnSuZIGWd-Mb4:b-ti0l9g)*

**Comment by progwriter** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/authorizer/MapAuthorizer.java, line 10 at r1](https://reviewable.io:443/reviews/batfish/batfish/764#-L0LGtUVCEmTL30vYeEA:-L0L_ft4ePfQZi8fzOvn:b-i02nq5) ([raw file](https://github.com/batfish/batfish/blob/8a871b8b32403822819726ea8a3b50a9f1c1766d/projects/coordinator/src/main/java/org/batfish/coordinator/authorizer/MapAuthorizer.java#L10)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Do you anticipate this being used more broadly, or just for testing?

If former, suggest adding tests and also thinking about thread safety.

If latter, move it into the `test` part of the code instead of `main`?
</blockquote></details>

My intention was testing only. Moved.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/764)*

**Comment by dhalperi** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/764)*

**Comment by progwriter** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrServiceV2Test.java, line 148 at r1](https://reviewable.io:443/reviews/batfish/batfish/764#-L0LGqtH44V2q-VPAZ7P:-L0Lh08lVhd-00gqvMKJ:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/8a871b8b32403822819726ea8a3b50a9f1c1766d/projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrServiceV2Test.java#L148)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

>     // And ensure that right key, but in the wrong (old) header field does not work either
>     resp =
>         getContainersTarget()
>             .path(containerName)
>             .request()
>             .header(CoordConsts.SVC_KEY_API_KEY, myKey)
>             .get();
>     assertThat(resp.getStatus(), equalTo(FORBIDDEN.getStatusCode()));

Can drop this part I think?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/764)*

**Pull request merged**
