### PR TITLE
Setting IP perms for AWS security groups correctly

### PR DESCRIPTION
**Pull request by haverma**
the `from` and `to` ports of `IpPermissions` are for ranges of ports and apply to only `DstPorts` for `ingress` and `egress` rules

### CODE REVIEW

**Comment by dhalperi** [comment]
Good catch!

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[projects/batfish/src/main/java/org/batfish/representation/aws/IpPermissions.java, line 104 at r2](https://reviewable.io:443/reviews/batfish/batfish/1088#-L8EMkaj-CPULIKc1kKx:-L8EMkaj-CPULIKc1kKy:b-qap7xj) ([raw file](https://github.com/batfish/batfish/blob/689bb4b330f0245c21a7c9285525b2d6ed3ffaf7/projects/batfish/src/main/java/org/batfish/representation/aws/IpPermissions.java#L104)):*
> ```Java
>     if (_fromPort != -1 && _toPort != -1) {
>       line.setDstPorts(Collections.singleton(new SubRange(_fromPort, _toPort)));
>     }
> ```

I agree that it should be talking only about dst ports, since that's what security groups express.

The `if` seems suspicious to me, unless it's the case that it's impossible that only one be `-1`.

---

*[projects/batfish/src/test/resources/org/batfish/representation/aws/SecurityGroupTest.json, line 38 at r2](https://reviewable.io:443/reviews/batfish/batfish/1088#-L8ENYjR_ydddLBgdsdt:-L8ENYjR_ydddLBgdsdu:bg4edxw) ([raw file](https://github.com/batfish/batfish/blob/689bb4b330f0245c21a7c9285525b2d6ed3ffaf7/projects/batfish/src/test/resources/org/batfish/representation/aws/SecurityGroupTest.json#L38)):*
> ```JSON
>       "VpcId": "vpc-123456"
>     }
>   ]
> ```

Add tests with no ports, with half-open (e.g., 0-22), closed (e.g., 45-100), and half-open (e.g., 65000-65535) ranges, and full range (0-65535) too.

   (note that AWS 'ALL' dialog is different than Custom + 0-65535)

Also, make sure that you're not crafting by hand, but actually creating a test security group on AWS and downloading it. Too many weird things might happen.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/1088#-:-L8EOlG1CukXPLvgHEXU:b6zrrk4)*

**Comment by haverma** [comment]
addressed comments

---

Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/representation/aws/IpPermissions.java, line 104 at r2](https://reviewable.io:443/reviews/batfish/batfish/1088#-L8EMkaj-CPULIKc1kKx:-L8Fz6-4F6VHeX0-Pp9B:b-6n2x41) ([raw file](https://github.com/batfish/batfish/blob/689bb4b330f0245c21a7c9285525b2d6ed3ffaf7/projects/batfish/src/main/java/org/batfish/representation/aws/IpPermissions.java#L104)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I agree that it should be talking only about dst ports, since that's what security groups express.

The `if` seems suspicious to me, unless it's the case that it's impossible that only one be `-1`.
</blockquote></details>

Seems both should either be unset or both be set, added the check in else

---

*[projects/batfish/src/test/resources/org/batfish/representation/aws/SecurityGroupTest.json, line 38 at r2](https://reviewable.io:443/reviews/batfish/batfish/1088#-L8ENYjR_ydddLBgdsdt:-L8FzII8bRw45e0U2ew8:b-78z2xq) ([raw file](https://github.com/batfish/batfish/blob/689bb4b330f0245c21a7c9285525b2d6ed3ffaf7/projects/batfish/src/test/resources/org/batfish/representation/aws/SecurityGroupTest.json#L38)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Add tests with no ports, with half-open (e.g., 0-22), closed (e.g., 45-100), and half-open (e.g., 65000-65535) ranges, and full range (0-65535) too.

   (note that AWS 'ALL' dialog is different than Custom + 0-65535)

Also, make sure that you're not crafting by hand, but actually creating a test security group on AWS and downloading it. Too many weird things might happen.
</blockquote></details>

added the tests, I guess by no ports you meant `Allow All Traffic`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/1088#-:-L8FzWa0NQeo5RTof8g5:brat57q)*

**Comment by dhalperi** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/representation/aws/IpPermissions.java, line 104 at r2](https://reviewable.io:443/reviews/batfish/batfish/1088#-L8EMkaj-CPULIKc1kKx:-L8G3Ky8AfnZWFBQP5vx:b-2xot81) ([raw file](https://github.com/batfish/batfish/blob/689bb4b330f0245c21a7c9285525b2d6ed3ffaf7/projects/batfish/src/main/java/org/batfish/representation/aws/IpPermissions.java#L104)):*
<details><summary><i>Previously, haverma (Harsh Verma) wrote…</i></summary><blockquote>

Seems both should either be unset or both be set, added the check in else
</blockquote></details>

This seems like a mistake -- if this case happens, what to do is obvious, right?

Why not just make the code more robust, something like

```java
fromPort = (0 <= fromPort && fromPort <= 65535) ? fromPort : 0;
toPort = (0 <= toPort && toPort <= 65535) ? toPort : 65535;

// if the range isn't all ports, set it in ACL.
if (fromPort != 0 || toPort != 65535) {
  line.setDstPorts(Collections.singleton(new SubRange(fromPort, toPort)));
}
```

For that matter, instead of letting it be -1 just initialize them to 0 and 65535 when deserializing them, and skip the -1 altogether.

Any reason not to?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/1088)*

**Comment by haverma** [comment]
added more tests for invalid `to` or `from` ports and addressed comments

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[projects/batfish/src/main/java/org/batfish/representation/aws/IpPermissions.java, line 104 at r2](https://reviewable.io:443/reviews/batfish/batfish/1088#-L8EMkaj-CPULIKc1kKx:-L8Gy5Ml8bqBiGMJSL-M:b-243ihi) ([raw file](https://github.com/batfish/batfish/blob/689bb4b330f0245c21a7c9285525b2d6ed3ffaf7/projects/batfish/src/main/java/org/batfish/representation/aws/IpPermissions.java#L104)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

This seems like a mistake -- if this case happens, what to do is obvious, right?

Why not just make the code more robust, something like

```java
fromPort = (0 <= fromPort && fromPort <= 65535) ? fromPort : 0;
toPort = (0 <= toPort && toPort <= 65535) ? toPort : 65535;

// if the range isn't all ports, set it in ACL.
if (fromPort != 0 || toPort != 65535) {
  line.setDstPorts(Collections.singleton(new SubRange(fromPort, toPort)));
}
```

For that matter, instead of letting it be -1 just initialize them to 0 and 65535 when deserializing them, and skip the -1 altogether.

Any reason not to?
</blockquote></details>

That makes sense. Set the default values for `toPort` and `fromPort` to 0 and 65535 while deserializing, 
now resetting invalid values to default values for ports

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/1088#-:-L8GycaFjP7kKXlj5zX6:bq2lv4r)*

**Comment by dhalperi** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/java/org/batfish/representation/aws/IpPermissions.java, line 101 at r3](https://reviewable.io:443/reviews/batfish/batfish/1088#-L8IZvrPOI2SD5rgOD0S:-L8IZvrQI_m5Mk0_4ur5:b-97lzvw) ([raw file](https://github.com/batfish/batfish/blob/c747f5152014c1f7f772b86677d4b6df12f6daff/projects/batfish/src/main/java/org/batfish/representation/aws/IpPermissions.java#L101)):*
> ```Java
>     }
>     // filtering invalid values
>     _fromPort = (0 <= _fromPort && _fromPort <= 65535) ? _fromPort : 0;
> ```

move this logic, if needed, to the place these variables are assigned. If it is possible for it to be a bad value, should catch it on initial assignment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/1088)*

**Comment by haverma** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/java/org/batfish/representation/aws/IpPermissions.java, line 101 at r3](https://reviewable.io:443/reviews/batfish/batfish/1088#-L8IZvrPOI2SD5rgOD0S:-L8ItNlSPYju9om8NkeE:b-7mmp82) ([raw file](https://github.com/batfish/batfish/blob/c747f5152014c1f7f772b86677d4b6df12f6daff/projects/batfish/src/main/java/org/batfish/representation/aws/IpPermissions.java#L101)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

move this logic, if needed, to the place these variables are assigned. If it is possible for it to be a bad value, should catch it on initial assignment.
</blockquote></details>

moved

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/1088)*

**Comment by dhalperi** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/1088#-:-L8Ivc8UEa3MtGX-HYsg:bnfp4nl)*

**Pull request merged**
