### PR TITLE
FortiOS: Convert route-maps

### PR DESCRIPTION
**Pull request by corinaminer**
Still not yet attached to anything (BGP processes/neighbors)

### CODE REVIEW

**Review by sfraint — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6847)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosBgpConversions.java, line 171 at r1](https://reviewable.io/reviews/batfish/batfish/6847#-MXYsKDT5gtiGoqlDMxM:-MXYsKDU7nYE7iOTr9sS:b-oo27rg) ([raw file](https://github.com/batfish/batfish/blob/f00a0e372695c02a230993418b807d9de797e1d2/projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosBgpConversions.java#L171)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
>                     if (!c.getRouteFilterLists().containsKey(listName)) {
>                       w.redFlag(
>                           String.format(
>                               "Ignoring rule %s in route-map %s: List %s does not exist or was not"
>                                   + " converted",
>                               rule.getNumber(), rmName, listName));
>                       return null;
> ```
</details>

is this possible? if so, should add a test for it

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6847)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @arifogel and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosBgpConversions.java, line 171 at r1](https://reviewable.io/reviews/batfish/batfish/6847#-MXYsKDT5gtiGoqlDMxM:-MXZ-4IJ20NQFTbtCIkG:b-abj3j5) ([raw file](https://github.com/batfish/batfish/blob/f00a0e372695c02a230993418b807d9de797e1d2/projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosBgpConversions.java#L171)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
>                     if (!c.getRouteFilterLists().containsKey(listName)) {
>                       w.redFlag(
>                           String.format(
>                               "Ignoring rule %s in route-map %s: List %s does not exist or was not"
>                                   + " converted",
>                               rule.getNumber(), rmName, listName));
>                       return null;
> ```
is this possible? if so, should add a test for it
</blockquote></details>

I don't believe it's currently possible because all access-lists are converted to RouteFilterLists, and extraction prevents references to undefined access-lists. Could become possible in the future (e.g., if we add support for access-list deletion without checking references, or don't convert some access-lists for some reason, or add incomplete prefix-list support).

I wouldn't be very opposed to switching this out for `assert c.getRouteFilterLists().containsKey()` if you think that's better.

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6847)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @arifogel, @corinaminer, and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosBgpConversions.java, line 171 at r1](https://reviewable.io/reviews/batfish/batfish/6847#-MXYsKDT5gtiGoqlDMxM:-MXZ6yVR-JMh10GoLSzE:b-d5tdyq) ([raw file](https://github.com/batfish/batfish/blob/f00a0e372695c02a230993418b807d9de797e1d2/projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosBgpConversions.java#L171)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

I don't believe it's currently possible because all access-lists are converted to RouteFilterLists, and extraction prevents references to undefined access-lists. Could become possible in the future (e.g., if we add support for access-list deletion without checking references, or don't convert some access-lists for some reason, or add incomplete prefix-list support).

I wouldn't be very opposed to switching this out for `assert c.getRouteFilterLists().containsKey()` if you think that's better.
</blockquote></details>

ack, slight preference to do the `assert` but feel free to resolve as you see fit

**Review by sfraint — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6847)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel and @corinaminer)

**Pull request merged**
