### PR TITLE
Re-evaluate BGP route exports subject to Juniper `condition` when its value changes

### PR DESCRIPTION
**Pull request by arifogel**
* Fixes iBDP bug where Juniper never exports a route that depends on the condition that another route that has not yet arrived is installed, even if the latter route arrives later
* Convert Juniper `condition` to `TrackRoute` instead of `RoutingPolicy` containing `RibIntersectsPrefixSpace`
* Convert `policy-statement` `from condition` to new `TrackSucceded` `BooleanExpr` instead of `CallExpr`
* record names of `TrackMethod`s that affect BGP export in `BgpProcess`
* In `BgpRoutingProcess`, send full set of advertisements as for new sessions when BGP-related `TrackMethod` values have changed
* Remove `RibIntersectsPrefixSpace` and related code
  * Only effective usage was for Juniper conditions
  * Did not support alternate VRFs, while `TrackRoute` does
  * While its match condition was more general than `TrackRoute` so it could eventually support IOS-XR `rib-has-route`, we can add a new `TrackMethod` to restore this generality at such time as we want to support `rib-has-route`.

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8639)* status: 0 of 39 files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/batfish/batfish/8639#-NMG_FaA1hohMvgKeGv7:-NMG_FaA1hohMvgKeGv8:bvbdbtc) (no related file):*
self-merge only

___

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8639)* status: 0 of 39 files reviewed, 1 unresolved discussion (waiting on @progwriter)

___
*[`projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/JuniperConditionTest.java` line 76 at r1](https://reviewable.io/reviews/batfish/batfish/8639#-NMGay-W5OXdlGlweO8S:-NMGay-XCtRZkB7weL89:b-shvssl) ([raw file](https://github.com/batfish/batfish/blob/9229392c62adaf5494158955eda252ab68df9cce/projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/JuniperConditionTest.java#L76)):*
> ```Java
>         rBgpRoutes,
>         containsInAnyOrder(
>             hasPrefix(Prefix.strict("1.0.0.1/32")),
> ```

FYI only this assertion for `1.0.0.1/32` passes when this test is added without any other Batfish changes.

**Review by progwriter — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, 13 of 13 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, 7 of 7 files at r5, 9 of 9 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8639)* status: all files reviewed, 4 unresolved discussions (waiting on @arifogel)

___
*[`projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java` line 307 at r2](https://reviewable.io/reviews/batfish/batfish/8639#-NMUiqTW9Df45Psa75i_:-NMUiqTW9Df45Psa75ia:b-lc5of6) ([raw file](https://github.com/batfish/batfish/blob/0300c82fe41c2999121f1d3a8481019235aa8dd4/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java#L307)):*
> ```Java
>   private @Nonnull Set<String> _successfulWatchedTracksPrev;
> 
>   // Helper to avoid recomputation of track states for each neighbor pulling from this process in a
> ```

is there an invariant we can document for when this should be updated? end of iteration? beginning of iteration?
___
*[`projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java` line 431 at r2](https://reviewable.io/reviews/batfish/batfish/8639#-NMUiKw8Bt00ZOIPtQoK:-NMUiKw8Bt00ZOIPtQoL:b-py70ej) ([raw file](https://github.com/batfish/batfish/blob/0300c82fe41c2999121f1d3a8481019235aa8dd4/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java#L431)):*
> ```Java
>    * <p>Must be called between rounds, aka, all delta builder should be empty.
>    *
>    * @param topologyContext The various network topologies
> ```

please update javadoc w/ new argument
___
*[`projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java` line 449 at r2](https://reviewable.io/reviews/batfish/batfish/8639#-NMUfn7-1lXMWoMtQBp4:-NMUfn7-1lXMWoMtQBp5:b-ks0q83) ([raw file](https://github.com/batfish/batfish/blob/0300c82fe41c2999121f1d3a8481019235aa8dd4/projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java#L449)):*
> ```Java
>             .build();
> 
>     // TODO: something more granular
> ```

granular w.r.t. what?

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8639)* status: 35 of 39 files reviewed, 3 unresolved discussions (waiting on @progwriter)

___
*[`projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java` line 307 at r2](https://reviewable.io/reviews/batfish/batfish/8639#-NMUiqTW9Df45Psa75i_:-NMVBAn97xQxRNr1wcTD:b-t9lvpx) ([raw file](https://github.com/batfish/batfish/blob/0300c82fe41c2999121f1d3a8481019235aa8dd4/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java#L307)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

is there an invariant we can document for when this should be updated? end of iteration? beginning of iteration?
</blockquote></details>

I added/updated javadocs for this field and the update method that I hope addresses your question.
___
*[`projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java` line 431 at r2](https://reviewable.io/reviews/batfish/batfish/8639#-NMUiKw8Bt00ZOIPtQoK:-NMVBtw-0o2UZDw4Guti:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/0300c82fe41c2999121f1d3a8481019235aa8dd4/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java#L431)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

please update javadoc w/ new argument
</blockquote></details>

done
___
*[`projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java` line 449 at r2](https://reviewable.io/reviews/batfish/batfish/8639#-NMUfn7-1lXMWoMtQBp4:-NMVG1wIABc38eAe_Ec5:bndcfj6) ([raw file](https://github.com/batfish/batfish/blob/0300c82fe41c2999121f1d3a8481019235aa8dd4/projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java#L449)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

granular w.r.t. what? 
</blockquote></details>

clarified.

**Review by progwriter — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8639#-:-NMVJq3DEfVwBlk-8TSB:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
