### PR TITLE
EVPN RIB separate routes by route-distinguisher

### PR DESCRIPTION
**Pull request by arifogel**
- can have up to one best route per <prefix,RD>
- simplify EVPN RIB
  - always best-path
  - don't pass in main RIB, since resolution would have to happen in other VRFs

### CODE REVIEW

**Review by corinaminer — COMMENTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7697)* status: all files reviewed, 2 unresolved discussions (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/rib/EvpnMasterRib.java, line 36 at r2](https://reviewable.io/reviews/batfish/batfish/7697#-MofImdO-YqqymYMQIPy:-MofImdO-YqqymYMQIPz:b-jefm1p) ([raw file](https://github.com/batfish/batfish/blob/88e70b2b0cc6ddda502193bbe00a83cd076564d8/projects/batfish/src/main/java/org/batfish/dataplane/rib/EvpnMasterRib.java#L36)):*
> ```Java
>   }
> 
>   public @Nonnull Set<R> getTypedRoutes() {
> ```

Is it necessary for this and `getTypedBackupRoutes` to return sets? There can't be identical routes within a rib or in different ribs.
___
*[projects/batfish/src/main/java/org/batfish/dataplane/rib/EvpnMasterRib.java, line 43 at r2](https://reviewable.io/reviews/batfish/batfish/7697#-MofIP1ECa8yZiIxl42j:-MofIP1F6LxupZjqPhPc:b7hfjs0) ([raw file](https://github.com/batfish/batfish/blob/88e70b2b0cc6ddda502193bbe00a83cd076564d8/projects/batfish/src/main/java/org/batfish/dataplane/rib/EvpnMasterRib.java#L43)):*
> ```Java
> 
>   public @Nonnull RibDelta<R> removeRouteGetDelta(R route) {
>     return getOrCreateRib(route.getRouteDistinguisher()).removeRouteGetDelta(route);
> ```

if there isn't already a route with this route distinguisher, might be worth avoiding creating a rib for it here

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7697)* status: all files reviewed, 2 unresolved discussions (waiting on @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/rib/EvpnMasterRib.java, line 36 at r2](https://reviewable.io/reviews/batfish/batfish/7697#-MofImdO-YqqymYMQIPy:-MofLHct2KNpbTniKmqt:b4jouah) ([raw file](https://github.com/batfish/batfish/blob/88e70b2b0cc6ddda502193bbe00a83cd076564d8/projects/batfish/src/main/java/org/batfish/dataplane/rib/EvpnMasterRib.java#L36)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Is it necessary for this and `getTypedBackupRoutes` to return sets? There can't be identical routes within a rib or in different ribs.
</blockquote></details>

Just following the API it copies from. It's useful for faster `contains` on returned collection.
___
*[projects/batfish/src/main/java/org/batfish/dataplane/rib/EvpnMasterRib.java, line 43 at r2](https://reviewable.io/reviews/batfish/batfish/7697#-MofIP1ECa8yZiIxl42j:-MofLbWI0t02-CgujWLU:bi7u3ha) ([raw file](https://github.com/batfish/batfish/blob/88e70b2b0cc6ddda502193bbe00a83cd076564d8/projects/batfish/src/main/java/org/batfish/dataplane/rib/EvpnMasterRib.java#L43)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

if there isn't already a route with this route distinguisher, might be worth avoiding creating a rib for it here
</blockquote></details>

I thought about that, but this code is nice and simple. Realistically, this will probably never happen.

**Review by corinaminer — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7697#-:-MofeUA16uNaeS9jtcbM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Review by arifogel — COMMENTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7697)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Pull request merged**
