### PR TITLE
Independently unmatchable ACL lines

### PR DESCRIPTION
**Pull request by corinaminer**
Handles ACLs with independently unmatchable lines in `answerAclReachability`. Process:
- Get unreachable lines
- Find any independently unmatchable lines among those unreachable lines
- Find earlier more general reachable lines (this could be improved by skipping unreachable lines that are independently unmatchable)
- For each unreachable line:
    - If it's independently unmatchable, add to answer with appropriate message
    - If earlier more general line isn't null, add it to answer normally
    - Else add answer for multiple blocking lines

### CODE REVIEW

**Comment by anothermattbrown** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 841 at r1](https://reviewable.io/reviews/batfish/batfish/1343#-LC2MX-gDejAv3E8IRau:-LC2MX-h6ZsqYvur0LUA:bfysqdi) ([raw file](https://github.com/batfish/batfish/blob/9644f9d9ce92af692d5d26b1a20fbd61847fd33f/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L841)):*
> ```Java
>         if (unmatchableLinesOnThisAcl.contains(lineNumber)) {
>           reachabilityEntry.setEarliestMoreGeneralLineIndex(-1);
>           reachabilityEntry.setEarliestMoreGeneralLineName(
> ```

Similar comment here. If it's not always a name, we shouldn't call it one.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1343)*

**Comment by corinaminer** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 840 at r1](https://reviewable.io/reviews/batfish/batfish/1343#-LC2BLP9DdLeToWqlMn8:-LC4ugpV2gVXc78wYZGz:b-os30pn) ([raw file](https://github.com/batfish/batfish/blob/9644f9d9ce92af692d5d26b1a20fbd61847fd33f/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L840)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

It would be cleaner and more understandable to indicate that no earlier more general line exists (e.g. with a separate boolean variable in `reachabilityEntry` called `earlierMoreGeneralLineExists`). Then we could remove these case values for index and name.

If there's some reason why we must do it this way, rename the "index" to something like "earliest more general line indicator". If it's not always an index, we shouldn't call it one.
</blockquote></details>

I agree with your instincts here, but I don't think there's much we can do without reformulating the JsonPath answer structure for ACL reachability. Could rename `earliestMoreGeneralLineIndex` and `earliestMoreGeneralLineName`, but I'm actually hesitant even to do that because those names serve to remind us how the display hint will interpret them:
"[This line is] covered by line '-1: Multiple earlier lines partially block this line, making it unreachable.'"

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1343)*

**Comment by anothermattbrown** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 840 at r1](https://reviewable.io/reviews/batfish/batfish/1343#-LC2BLP9DdLeToWqlMn8:-LC4wvCK1Rdka0MRGlWW:b-kvnk2j) ([raw file](https://github.com/batfish/batfish/blob/9644f9d9ce92af692d5d26b1a20fbd61847fd33f/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L840)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

I agree with your instincts here, but I don't think there's much we can do without reformulating the JsonPath answer structure for ACL reachability. Could rename `earliestMoreGeneralLineIndex` and `earliestMoreGeneralLineName`, but I'm actually hesitant even to do that because those names serve to remind us how the display hint will interpret them:
"[This line is] covered by line '-1: Multiple earlier lines partially block this line, making it unreachable.'"
</blockquote></details>

It turns out that this is temporary stop-gap measure and will go away at some point in the future. For now, let's just add a comment at the declarations of `earliestMoreGeneralLineIndex` and `earliestMoreGeneralLineName` describing what non-index/name values are being used, why, and when they will be removed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1343)*

**Comment by corinaminer** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 840 at r1](https://reviewable.io/reviews/batfish/batfish/1343#-LC2BLP9DdLeToWqlMn8:-LC55eRp53rh130ZCGP9:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/9644f9d9ce92af692d5d26b1a20fbd61847fd33f/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L840)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

It turns out that this is temporary stop-gap measure and will go away at some point in the future. For now, let's just add a comment at the declarations of `earliestMoreGeneralLineIndex` and `earliestMoreGeneralLineName` describing what non-index/name values are being used, why, and when they will be removed.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1343)*

**Comment by anothermattbrown** [comment]
Reviewed 1 of 3 files at r1, 1 of 2 files at r2.
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 841 at r1](https://reviewable.io/reviews/batfish/batfish/1343#-LC2MX-gDejAv3E8IRau:-LC565JA0Hf1-lZt6wvS:b32w0x) ([raw file](https://github.com/batfish/batfish/blob/9644f9d9ce92af692d5d26b1a20fbd61847fd33f/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L841)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

Similar comment here. If it's not always a name, we shouldn't call it one.
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1343)*

**Comment by anothermattbrown** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1343#-:-LC56INUDhlBkVKQiiGp:bnfp4nl)*

**Comment by arifogel** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 845 at r3](https://reviewable.io/reviews/batfish/batfish/1343#-LC58VUn6tnXREkmT93W:-LC58VUn6tnXREkmT93X:bwdggu8) ([raw file](https://github.com/batfish/batfish/blob/bea7e39025a11ed8c5c17c50ab68a5a56eba7a5d/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L845)):*
> ```Java
>          * For right now, it's hard to fix because the JsonPathAnswerElement for ACL reachability
>          * doesn't account for these two cases and changing that would be a breaking change.
>          * TODO Stop using the earliestMoreGeneralLine variables for other answer categories.
> ```

TODO should always include a link to a filed issue. I think this applies elsewhere in your PR as well.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1343)*

**Comment by corinaminer** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[projects/allinone/src/test/java/org/batfish/allinone/AclReachabilityTest.java, line 139 at r1](https://reviewable.io/reviews/batfish/batfish/1343#-LC57Pz736ynU9EIfCOE:-LC5BJQP4xnOkKP1H9Zi:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/9644f9d9ce92af692d5d26b1a20fbd61847fd33f/projects/allinone/src/test/java/org/batfish/allinone/AclReachabilityTest.java#L139)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Optionally, the last two can be constructed from an `Ip`
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 670 at r1](https://reviewable.io/reviews/batfish/batfish/1343#-LC56Qt94eK2i0JFw6Ru:-LC5CMVu7ZG8GCvgnI6w:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/9644f9d9ce92af692d5d26b1a20fbd61847fd33f/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L670)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

You changed the function signature, but you still need to update the javadoc.
Further, consider whether the parameter name should still be `representatives`.
</blockquote></details>

Done.

---

*[projects/batfish/src/test/java/org/batfish/z3/AclLineIndependentSatisfiabilityTest.java, line 61 at r1](https://reviewable.io/reviews/batfish/batfish/1343#-LC575Wn6gNtFqdxUBCq:-LC5AKvC9NMS-sFaDRW-:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/9644f9d9ce92af692d5d26b1a20fbd61847fd33f/projects/batfish/src/test/java/org/batfish/z3/AclLineIndependentSatisfiabilityTest.java#L61)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Let me clarify: please factor out a function, period. The latter part of my previous comment refers to construction of the `Set<Integer>` part.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1343)*

**Comment by arifogel** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 669 at r4](https://reviewable.io/reviews/batfish/batfish/1343#-LC5EXIL4t8Ld6nxO9cl:-LC5EXIL4t8Ld6nxO9cm:b-3v67wn) ([raw file](https://github.com/batfish/batfish/blob/c82b5e4516efed4f56db2129f212a2c8c7ed7de6/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L669)):*
> ```Java
>    * @param linesToCheck Map of hostnames -> ACL names -> set of line numbers for which to check
>    *     matchability
>    * @return Map of hostname -> name of acl for which named host is representative -> list of lines
> ```

`representative` here also seems to no longer apply

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1343)*

**Comment by arifogel** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1343#-:-LC5Jo-JDLR61zEfWRGk:bnfp4nl)*

**Pull request merged**
