### PR TITLE
Frr: Remove more cumulus vestiges

### PR DESCRIPTION
**Pull request by ratulm**
1. Decouple CumulusStrucutureType/Usage from FRR versions
2. Move a few more Cumulus representation classes out of FRR

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 23 of 28 files at r1, 1 of 1 files at r2, 12 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7799)* status: all files reviewed, 2 unresolved discussions (waiting on @ratulm)

___
*[projects/batfish/src/main/java/org/batfish/grammar/cumulus_interfaces/CumulusInterfacesConfigurationBuilder.java, line 472 at r3](https://reviewable.io/reviews/batfish/batfish/7799#-Mr0Rm618FmIxMR6Luds:-Mr0Rm618FmIxMR6Ludt:bn0db5l) ([raw file](https://github.com/batfish/batfish/blob/095a6ace7dcfd67f0cbf1259f27050f33d2e000f/projects/batfish/src/main/java/org/batfish/grammar/cumulus_interfaces/CumulusInterfacesConfigurationBuilder.java#L472)):*
> ```Java
>             String.format(
>                 "CumulusStructureType %s has no self-reference usage",
>                 structureType.getDescription()));
> ```

Why use the description? I feel like the enum would be more informative to a developer.
___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicStructureType.java, line 48 at r3](https://reviewable.io/reviews/batfish/batfish/7799#-Mr0Sopr4eB4ZEbO7Ff-:-Mr0SopsDQRHswfWgWoE:b-nyfnjj) ([raw file](https://github.com/batfish/batfish/blob/095a6ace7dcfd67f0cbf1259f27050f33d2e000f/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicStructureType.java#L48)):*
> ```Java
>     ImmutableMap.Builder<String, SonicStructureType> map = ImmutableMap.builder();
>     for (SonicStructureType value : SonicStructureType.values()) {
>       map.put(value.getDescription(), value);
> ```

Why are you keying on description?

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7799)* status: 30 of 35 files reviewed, 1 unresolved discussion (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicStructureType.java, line 48 at r3](https://reviewable.io/reviews/batfish/batfish/7799#-Mr0Sopr4eB4ZEbO7Ff-:-Mr0kI7Y4W_f-EsFiULL:b-2292rq) ([raw file](https://github.com/batfish/batfish/blob/095a6ace7dcfd67f0cbf1259f27050f33d2e000f/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicStructureType.java#L48)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Why are you keying on description?
</blockquote></details>

Because the map was for all enums, not just FRR-based ones. Narrowed the scope of the map now.

**Review by arifogel — COMMENTED** [review]
> Reviewed 5 of 5 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7799)* status: all files reviewed, 2 unresolved discussions (waiting on @ratulm)

___
*[projects/batfish/src/main/java/org/batfish/representation/cumulus_concatenated/CumulusStructureType.java, line 53 at r5](https://reviewable.io/reviews/batfish/batfish/7799#-Mr3indtDSOmBXtOvb6B:-Mr3indtDSOmBXtOvb6C:b-sk8imi) ([raw file](https://github.com/batfish/batfish/blob/e503da4ae33bc868e836d92783641dc8a5e1bcb8/projects/batfish/src/main/java/org/batfish/representation/cumulus_concatenated/CumulusStructureType.java#L53)):*
> ```Java
>       CumulusStructureType matchingCumulusType =
>           Arrays.stream(CumulusStructureType.values())
>               .filter(cType -> cType.getDescription().equals(frrType.getDescription()))
> ```

Why are you checking for something with the same description?
Why not just check for an enum with the same constant name?
___
*[projects/batfish/src/main/java/org/batfish/representation/cumulus_concatenated/CumulusStructureType.java, line 57 at r5](https://reviewable.io/reviews/batfish/batfish/7799#-Mr3jP1A5NouC0lf_m4H:-Mr3jP1A5NouC0lf_m4I:bayp3qb) ([raw file](https://github.com/batfish/batfish/blob/e503da4ae33bc868e836d92783641dc8a5e1bcb8/projects/batfish/src/main/java/org/batfish/representation/cumulus_concatenated/CumulusStructureType.java#L57)):*
> ```Java
>               .orElseThrow(
>                   () ->
>                       new NoSuchElementException(
> ```

Not sure, but I don't think you'll ever see an exception thrown in a static initializer. Probably better to use tests to make sure things are good (I see you deleted them).

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7799)* status: all files reviewed, 2 unresolved discussions (waiting on @ratulm)

___
*[projects/batfish/src/main/java/org/batfish/representation/cumulus_concatenated/CumulusStructureType.java, line 53 at r5](https://reviewable.io/reviews/batfish/batfish/7799#-Mr3indtDSOmBXtOvb6B:-Mr3jsR80b6ME6g6dAxO:bcgt5dx) ([raw file](https://github.com/batfish/batfish/blob/e503da4ae33bc868e836d92783641dc8a5e1bcb8/projects/batfish/src/main/java/org/batfish/representation/cumulus_concatenated/CumulusStructureType.java#L53)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Why are you checking for something with the same description?
Why not just check for an enum with the same constant name?
</blockquote></details>

(or same constant name and same description)

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7799)* status: all files reviewed, 2 unresolved discussions (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/representation/cumulus_concatenated/CumulusStructureType.java, line 53 at r5](https://reviewable.io/reviews/batfish/batfish/7799#-Mr3indtDSOmBXtOvb6B:-Mr5qRnu6oDQv7ciLxxs:b-u3f25i) ([raw file](https://github.com/batfish/batfish/blob/e503da4ae33bc868e836d92783641dc8a5e1bcb8/projects/batfish/src/main/java/org/batfish/representation/cumulus_concatenated/CumulusStructureType.java#L53)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

(or same constant name and same description)
</blockquote></details>

I did description because that is what FRR to Cumulus mapping is doing. 

Is your suggestion to do `cType.name() == frrType.name()`? (why is that better?)
___
*[projects/batfish/src/main/java/org/batfish/representation/cumulus_concatenated/CumulusStructureType.java, line 57 at r5](https://reviewable.io/reviews/batfish/batfish/7799#-Mr3jP1A5NouC0lf_m4H:-Mr5qmUVCTKQmp1fN2AY:bjak22a) ([raw file](https://github.com/batfish/batfish/blob/e503da4ae33bc868e836d92783641dc8a5e1bcb8/projects/batfish/src/main/java/org/batfish/representation/cumulus_concatenated/CumulusStructureType.java#L57)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Not sure, but I don't think you'll ever see an exception thrown in a static initializer. Probably better to use tests to make sure things are good (I see you deleted them).
</blockquote></details>

The class will fail to load. So, the error will be loud and clear in any test that uses those.

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7799)* status: 31 of 38 files reviewed, 3 unresolved discussions (waiting on @arifogel)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7799#-Mr8TdAv4kEQVPLkuXOb:-Mr8TdAw36WjdFT9oPZw:biz3nkc) (no related file):*
@arifogel - I had to revert to treating FrrStructureUsage in the manner I was treating FrrStructureType (i.e., the specific vendors creates its Usage based on FRR usage) because the code uses StructureUsages of a vendor as keys in SortedMap, which barfs if the keys are of different types.

---

**Review by arifogel — COMMENTED** [review]
> Reviewed 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7799)* status: all files reviewed, 2 unresolved discussions (waiting on @ratulm)

___
*[projects/batfish/src/main/java/org/batfish/representation/cumulus_concatenated/CumulusStructureType.java, line 53 at r5](https://reviewable.io/reviews/batfish/batfish/7799#-Mr3indtDSOmBXtOvb6B:-Mr8djo21T4nak0DBD_U:bdpe7lh) ([raw file](https://github.com/batfish/batfish/blob/e503da4ae33bc868e836d92783641dc8a5e1bcb8/projects/batfish/src/main/java/org/batfish/representation/cumulus_concatenated/CumulusStructureType.java#L53)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

I did description because that is what FRR to Cumulus mapping is doing. 

Is your suggestion to do `cType.name() == frrType.name()`? (why is that better?)
</blockquote></details>

names are guaranteed to be unique within an enum. descriptions are not (copy-paste errors happen here all the time).

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7799)* status: all files reviewed, 2 unresolved discussions (waiting on @ratulm)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7799#-Mr8TdAv4kEQVPLkuXOb:-Mr8eeOd9qRACaUU-s5W:b32wtd) (no related file):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

@arifogel - I had to revert to treating FrrStructureUsage in the manner I was treating FrrStructureType (i.e., the specific vendors creates its Usage based on FRR usage) because the code uses StructureUsages of a vendor as keys in SortedMap, which barfs if the keys are of different types.
</blockquote></details>

ok

---

**Review by arifogel — COMMENTED** [review]
> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7799)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ratulm)

**Pull request merged**
