### PR TITLE
Basics for RouteMap tracing

### PR DESCRIPTION
**Pull request by ratulm**
In this PR:
  - Add a TraceableStatement that wraps other Statements that we want to be traced. 
  - Embed the trace in TRP output (non-differential only)
 
Future PRs:
 - VS conversions to use TraceableStatements

### CODE REVIEW

**Comment by dhalperi** [comment]
*[a discussion](https://reviewable.io/reviews/batfish/batfish/7082#-McWN8B541z5DMWXgec4:-McWN8B541z5DMWXgec5:b-i93nol) (no related file):*
Matt can help you get the trace integration right.

---

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7082)* status: 0 of 15 files reviewed, 2 unresolved discussions (waiting on @anothermattbrown and @ratulm)

___
*[projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java, line 134 at r1](https://reviewable.io/reviews/batfish/batfish/7082#-McWNEn39u-Pj3siPjcE:-McWNEn39u-Pj3siPjcF:b-cb2p3f) ([raw file](https://github.com/batfish/batfish/blob/bd683fbd8c09b47f131657190e0e1954f7e94596/projects/batfish/src/main/java/org/batfish/job/ConvertConfigurationJob.java#L134)):*
> ```
>     // Simplification does not work with tracing
>     // c.simplifyRoutingPolicies();
> ```

Can you move this and ref differences to its own PR?

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 8 of 15 files at r1, 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7082)* status: 15 of 16 files reviewed, 6 unresolved discussions (waiting on @ratulm)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/Environment.java, line 539 at r2](https://reviewable.io/reviews/batfish/batfish/7082#-McjkO5f-3Yf6TMQ3dvw:-McjkO5f-3Yf6TMQ3dvx:blr97cg) ([raw file](https://github.com/batfish/batfish/blob/f0595cd48856131c6cd2dc227c74e8852fe49222/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/Environment.java#L539)):*
> ```
> setTraceTree
> ```
nit: getter and setter names should match (i.e. this should be `setTracer`)
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/If.java, line 117 at r2](https://reviewable.io/reviews/batfish/batfish/7082#-Mcjl0N173oPsN9tMkmJ:-Mcjl0N173oPsN9tMkmK:byvf2s4) ([raw file](https://github.com/batfish/batfish/blob/f0595cd48856131c6cd2dc227c74e8852fe49222/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/If.java#L117)):*
> ```
> traceIt
> ```
this is unclear to me. do you have examples of what traces this is going to produce, and why that's the right thing?

specifically:
1) when is the comment null/nonnull, and why should that impact whether we trace the branch?
2) why only trace the true branch? interesting things can happen in the false branch too. 
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/If.java, line 129 at r2](https://reviewable.io/reviews/batfish/batfish/7082#-McjmmFVC-oPjEZy_EAU:-McjmmFVC-oPjEZy_EAV:bwnvhza) ([raw file](https://github.com/batfish/batfish/blob/f0595cd48856131c6cd2dc227c74e8852fe49222/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/If.java#L129)):*
> ```
>         if (traceIt) {
>           environment.getTracer().endSubTrace();
>         }
> ```
It looks like you're trying to make sure you always call `endSubTrace` before you return. A `finally` clause is a cleaner and less error-prone way to do this, especially when you have multiple return statements.
___
*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/routing_policy/statement/IfTest.java, line 117 at r2](https://reviewable.io/reviews/batfish/batfish/7082#-McjnY0a2ixVM_3iE149:-McjnY0a2ixVM_3iE14A:b-rfa1j3) ([raw file](https://github.com/batfish/batfish/blob/f0595cd48856131c6cd2dc227c74e8852fe49222/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/routing_policy/statement/IfTest.java#L117)):*
> ```
> testExecute
> ```
looks like this is really testing the generated traces. it would be good to reflect that in the name. 

also, I think we're missing test cases for nested traces.
___
*[projects/question/src/main/java/org/batfish/question/testroutepolicies/Result.java, line 54 at r2](https://reviewable.io/reviews/batfish/batfish/7082#-McjjcMm0SLvFuN7xF0p:-McjjcMm0SLvFuN7xF0q:b-h9b31l) ([raw file](https://github.com/batfish/batfish/blob/f0595cd48856131c6cd2dc227c74e8852fe49222/projects/question/src/main/java/org/batfish/question/testroutepolicies/Result.java#L54)):*
> ```
> traceTrees
> ```
nit: this is the complete trace, so `trace` would be a better name. (it's not clear how readers would know that "traceTrees" meant "trace")

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 1 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7082)* status: all files reviewed, 6 unresolved discussions (waiting on @ratulm)

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7082)* status: all files reviewed, 2 unresolved discussions (waiting on @anothermattbrown)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/If.java, line 117 at r2](https://reviewable.io/reviews/batfish/batfish/7082#-Mcjl0N173oPsN9tMkmJ:-Mcjt6Vi8HwnrRoFtmxC:b-th0nss) ([raw file](https://github.com/batfish/batfish/blob/f0595cd48856131c6cd2dc227c74e8852fe49222/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/If.java#L117)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

> ```
> traceIt
> ```
this is unclear to me. do you have examples of what traces this is going to produce, and why that's the right thing?

specifically:
1) when is the comment null/nonnull, and why should that impact whether we trace the branch?
2) why only trace the true branch? interesting things can happen in the false branch too. 
</blockquote></details>

1. The intended invariant: During conversion, user-defined IF statements will have a comment (to be made into a TraceElement soon). Internal IF statements will not. We only trace the former.
2. This is like tracing for filters -- only trace positive matches. There are too many negative matches. If something matches on the false branch later, it will show up. (unless i am misunderstand routing policy semantics or your comment.)
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/If.java, line 129 at r2](https://reviewable.io/reviews/batfish/batfish/7082#-McjmmFVC-oPjEZy_EAU:-McjvDnDCC1UejJ7yyZ5:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/f0595cd48856131c6cd2dc227c74e8852fe49222/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/If.java#L129)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

> ```
>         if (traceIt) {
>           environment.getTracer().endSubTrace();
>         }
> ```
It looks like you're trying to make sure you always call `endSubTrace` before you return. A `finally` clause is a cleaner and less error-prone way to do this, especially when you have multiple return statements.
</blockquote></details>

Done.

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 3 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7082)* status: 13 of 16 files reviewed, 2 unresolved discussions (waiting on @anothermattbrown and @ratulm)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/If.java, line 117 at r2](https://reviewable.io/reviews/batfish/batfish/7082#-Mcjl0N173oPsN9tMkmJ:-Mck8cCW5BFOlYG-KkSe:brwp6aq) ([raw file](https://github.com/batfish/batfish/blob/f0595cd48856131c6cd2dc227c74e8852fe49222/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/If.java#L117)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

1. The intended invariant: During conversion, user-defined IF statements will have a comment (to be made into a TraceElement soon). Internal IF statements will not. We only trace the former.
2. This is like tracing for filters -- only trace positive matches. There are too many negative matches. If something matches on the false branch later, it will show up. (unless i am misunderstand routing policy semantics or your comment.)
</blockquote></details>

1. ok. we should document that contract clearly somewhere
2. if-then-else in route maps seems very different from ACLs, and there is nothing in ACL tracing that corresponds to tracing the then branch. The analog would be building a subtrace to explain why the guard evaluated to true. Perhaps we should meet and discuss?

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 3 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7082)* status: all files reviewed, 2 unresolved discussions (waiting on @anothermattbrown and @ratulm)

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7082)* status: all files reviewed, 2 unresolved discussions (waiting on @anothermattbrown)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/If.java, line 117 at r2](https://reviewable.io/reviews/batfish/batfish/7082#-Mcjl0N173oPsN9tMkmJ:-McmL195ELYAfKrFVNkg:b-1c721t) ([raw file](https://github.com/batfish/batfish/blob/f0595cd48856131c6cd2dc227c74e8852fe49222/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/If.java#L117)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

1. ok. we should document that contract clearly somewhere
2. if-then-else in route maps seems very different from ACLs, and there is nothing in ACL tracing that corresponds to tracing the then branch. The analog would be building a subtrace to explain why the guard evaluated to true. Perhaps we should meet and discuss?
</blockquote></details>

Check out the modified approach and see if it makes things explicit. Changes
1. A new TraceableStatement for explicitly tracing statements
2. Allow for both Then and Else branches of If to be traced -- the process that builds the If statement decides. 

(Tests and some other things remain, but I wanted to agree on the approach first).

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 1 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7082)* status: 16 of 19 files reviewed, 4 unresolved discussions (waiting on @anothermattbrown and @ratulm)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/If.java, line 127 at r4](https://reviewable.io/reviews/batfish/batfish/7082#-McoTWlLCHxNXUPzYrJB:-McoTWlLCHxNXUPzYrJC:b2skyq3) ([raw file](https://github.com/batfish/batfish/blob/901717d2e7649df966b0714d4a2dcd4a00aef238/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/If.java#L127)):*
> ```
> environment.getTracer().newSubTrace();
> ```
What do we want to happen if the `If` statement doesn't have a trace element, but a statement within the chosen branch does?  The way your code is written, we'll add the branch's element to the current level of the trace, which seems bad/confusing. I don't think we can safely assume that will never happen, because there's nothing enforcing that invariant (and it would be an expensive invariant to try to enforce). The safest way to prevent that is to unconditionally create the new subtrace and discard it if you don't want it (via `discardSubTrace`).
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/TraceableStatement.java, line 25 at r4](https://reviewable.io/reviews/batfish/batfish/7082#-McoVnxn3cLe8l-zAgvw:-McoVnxn3cLe8l-zAgvx:b-yu4hf1) ([raw file](https://github.com/batfish/batfish/blob/901717d2e7649df966b0714d4a2dcd4a00aef238/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/TraceableStatement.java#L25)):*
> ```
> TraceableStatement
> ```
are you planning to use this? if you're only tracing Ifs, and that doesn't use this, why add it?

if we give this a list of inner statements instead of just one, we can remove the tracing logic from `If` and just use this
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/TraceableStatement.java, line 67 at r4](https://reviewable.io/reviews/batfish/batfish/7082#-McoWPtnBiNQpIpGsa2z:-McoWPtnBiNQpIpGsa3-:b-5yvf6o) ([raw file](https://github.com/batfish/batfish/blob/901717d2e7649df966b0714d4a2dcd4a00aef238/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/TraceableStatement.java#L67)):*
> ```
>       // this isn't quite right
>       environment.getTracer().newSubTrace();
>       environment.getTracer().setTraceElement(_traceElement);
> ```

It looks like you're relying on a different precondition for `TraceableStatement.execute` than for `If.execute`:
* in `If.execute` you assume the current `TraceContext` does not yet have a trace element. So you set it and then create a new subtrace for the branch (reestablishing the precondition for the inner `Statement.execute` call. This is the precondition `AclTracer` uses.
* in `TraceableStatement.execute` you assume the current `TraceContext` already has a trace element, so you can't set it. Instead to create a new subtrace and set the element on it. 

I wonder if we can simplify `Tracer` by ensuring consistent use -- i.e. by requiring one of these invariants. It would have to be the second -- i.e. by removing the `setTraceElement` method and requiring a trace element be supplied to `newSubTrace`

```
```

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7082)* status: 14 of 19 files reviewed, 3 unresolved discussions (waiting on @anothermattbrown)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/If.java, line 127 at r4](https://reviewable.io/reviews/batfish/batfish/7082#-McoTWlLCHxNXUPzYrJB:-McwnFSACR8JerK-EE74:blib6vh) ([raw file](https://github.com/batfish/batfish/blob/901717d2e7649df966b0714d4a2dcd4a00aef238/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/If.java#L127)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

> ```
> environment.getTracer().newSubTrace();
> ```
What do we want to happen if the `If` statement doesn't have a trace element, but a statement within the chosen branch does?  The way your code is written, we'll add the branch's element to the current level of the trace, which seems bad/confusing. I don't think we can safely assume that will never happen, because there's nothing enforcing that invariant (and it would be an expensive invariant to try to enforce). The safest way to prevent that is to unconditionally create the new subtrace and discard it if you don't want it (via `discardSubTrace`).
</blockquote></details>

This bit is gone now. 
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/TraceableStatement.java, line 67 at r4](https://reviewable.io/reviews/batfish/batfish/7082#-McoWPtnBiNQpIpGsa2z:-McwncHJ7oxLue9i9MTL:b-fmtys5) ([raw file](https://github.com/batfish/batfish/blob/901717d2e7649df966b0714d4a2dcd4a00aef238/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/TraceableStatement.java#L67)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

> ```
>       // this isn't quite right
>       environment.getTracer().newSubTrace();
>       environment.getTracer().setTraceElement(_traceElement);
> ```

It looks like you're relying on a different precondition for `TraceableStatement.execute` than for `If.execute`:
* in `If.execute` you assume the current `TraceContext` does not yet have a trace element. So you set it and then create a new subtrace for the branch (reestablishing the precondition for the inner `Statement.execute` call. This is the precondition `AclTracer` uses.
* in `TraceableStatement.execute` you assume the current `TraceContext` already has a trace element, so you can't set it. Instead to create a new subtrace and set the element on it. 

I wonder if we can simplify `Tracer` by ensuring consistent use -- i.e. by requiring one of these invariants. It would have to be the second -- i.e. by removing the `setTraceElement` method and requiring a trace element be supplied to `newSubTrace`

```
</blockquote></details>

I didn't change the tracer in this PR. With tracing gone from the If statement, the invariant is that you must create a newSubTrace to add a traceElement (second in your option). 


<!-- Sent from Reviewable.io -->

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7082)* status: 14 of 19 files reviewed, 3 unresolved discussions (waiting on @anothermattbrown)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/If.java, line 117 at r2](https://reviewable.io/reviews/batfish/batfish/7082#-Mcjl0N173oPsN9tMkmJ:-McwpCdL0yliOVTK7poO:bd4t445) ([raw file](https://github.com/batfish/batfish/blob/f0595cd48856131c6cd2dc227c74e8852fe49222/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/If.java#L117)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

Check out the modified approach and see if it makes things explicit. Changes
1. A new TraceableStatement for explicitly tracing statements
2. Allow for both Then and Else branches of If to be traced -- the process that builds the If statement decides. 

(Tests and some other things remain, but I wanted to agree on the approach first).
</blockquote></details>

A sketch of the approach again, to be completed if this makes sense.

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 2 of 4 files at r4, 5 of 8 files at r5, 1 of 1 files at r6, 3 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7082)* status: all files reviewed, 4 unresolved discussions (waiting on @ratulm)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/community/CommunityStructuresVerifier.java, line 781 at r7](https://reviewable.io/reviews/batfish/batfish/7082#-Md-FLDU-CIgxnKbbG1E:-Md-FLDU-CIgxnKbbG1F:b-u0d4ji) ([raw file](https://github.com/batfish/batfish/blob/2cf4b7cc43cb67d2059d1738c6e1249c8d64de2e/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/community/CommunityStructuresVerifier.java#L781)):*
> ```
> visitTraceableStatement
> ```
we don't need to process the inner statements?
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/as_path/AsPathStructuresVerifier.java, line 510 at r7](https://reviewable.io/reviews/batfish/batfish/7082#-Md-FBB4EvNNEhFYLy1g:-Md-FBB4EvNNEhFYLy1h:b8h0fvg) ([raw file](https://github.com/batfish/batfish/blob/2cf4b7cc43cb67d2059d1738c6e1249c8d64de2e/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/as_path/AsPathStructuresVerifier.java#L510)):*
> ```
>  visitTraceableStatement
> ```
we don't need to process the inner statements?
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/TraceableStatement.java, line 20 at r7](https://reviewable.io/reviews/batfish/batfish/7082#-Md-FY8S1olhWSb1xs_j:-Md-FY8S1olhWSb1xs_k:b9aowkc) ([raw file](https://github.com/batfish/batfish/blob/2cf4b7cc43cb67d2059d1738c6e1249c8d64de2e/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/TraceableStatement.java#L20)):*
> ```
> executes its inner statements.
> ```
clarification: in a subtrace.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/TraceableStatement.java, line 38 at r7](https://reviewable.io/reviews/batfish/batfish/7082#-Md-Fy08EOyQZF8dV50U:-Md-Fy08EOyQZF8dV50V:bg04yfq) ([raw file](https://github.com/batfish/batfish/blob/2cf4b7cc43cb67d2059d1738c6e1249c8d64de2e/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/TraceableStatement.java#L38)):*
> ```
> TraceableStatement(List<Statement> innerStatements, TraceElement traceElement) 
> ```
I think usages would be more readable (particularly in tests) with the argument order reversed. 
___
*[projects/minesweeper/src/main/java/org/batfish/minesweeper/communities/RoutePolicyStatementVarCollector.java, line 159 at r7](https://reviewable.io/reviews/batfish/batfish/7082#-Md-GKS08tdOV45xWRQO:-Md-GKS12NAl6EO6EhPN:bs2x7r3) ([raw file](https://github.com/batfish/batfish/blob/2cf4b7cc43cb67d2059d1738c6e1249c8d64de2e/projects/minesweeper/src/main/java/org/batfish/minesweeper/communities/RoutePolicyStatementVarCollector.java#L159)):*
> ```
> visitTraceableStatement
> ```
don't we need to look within the inner statements?

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7082)* status: 17 of 26 files reviewed, 4 unresolved discussions (waiting on @anothermattbrown)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/community/CommunityStructuresVerifier.java, line 781 at r7](https://reviewable.io/reviews/batfish/batfish/7082#-Md-FLDU-CIgxnKbbG1E:-Md-IF1D49cfsUtXgrCL:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/2cf4b7cc43cb67d2059d1738c6e1249c8d64de2e/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/bgp/community/CommunityStructuresVerifier.java#L781)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

> ```
> visitTraceableStatement
> ```
we don't need to process the inner statements?
</blockquote></details>

Done.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/as_path/AsPathStructuresVerifier.java, line 510 at r7](https://reviewable.io/reviews/batfish/batfish/7082#-Md-FBB4EvNNEhFYLy1g:-Md-Hyk7BAKfuGQh9_uO:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/2cf4b7cc43cb67d2059d1738c6e1249c8d64de2e/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/as_path/AsPathStructuresVerifier.java#L510)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

> ```
>  visitTraceableStatement
> ```
we don't need to process the inner statements?
</blockquote></details>

Done.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/TraceableStatement.java, line 20 at r7](https://reviewable.io/reviews/batfish/batfish/7082#-Md-FY8S1olhWSb1xs_j:-Md-HPVU0WMIQ0oGpgld:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/2cf4b7cc43cb67d2059d1738c6e1249c8d64de2e/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/TraceableStatement.java#L20)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

> ```
> executes its inner statements.
> ```
clarification: in a subtrace.
</blockquote></details>

Done.
___
*[projects/minesweeper/src/main/java/org/batfish/minesweeper/communities/RoutePolicyStatementVarCollector.java, line 159 at r7](https://reviewable.io/reviews/batfish/batfish/7082#-Md-GKS08tdOV45xWRQO:-Md-IwBE70ceyoEXu_6_:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/2cf4b7cc43cb67d2059d1738c6e1249c8d64de2e/projects/minesweeper/src/main/java/org/batfish/minesweeper/communities/RoutePolicyStatementVarCollector.java#L159)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

> ```
> visitTraceableStatement
> ```
don't we need to look within the inner statements?
</blockquote></details>

Done.

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 9 of 9 files at r8.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7082)* status: all files reviewed, 1 unresolved discussion (waiting on @anothermattbrown)

**Review by anothermattbrown — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7082#-:-Md-MYwDD9wlnpPKKd-i:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ratulm)

**Pull request merged**
