### PR TITLE
Make OSPF routes non-recursive by including next-hop interface

### PR DESCRIPTION
**Pull request by arifogel**
- iBDP add next-hop interface to `OspfRoute`s
- require next-hop interface for `OspfRoute`s except when non-routing bit is set
  - next-hop interface not required for staging and export
  - set next-hop interface when imported

### CODE REVIEW

**Review by corinaminer — COMMENTED** [review]
> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, 4 of 6 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7028)* status: 12 of 15 files reviewed, 7 unresolved discussions (waiting on @arifogel and @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java, line 454 at r4](https://reviewable.io/reviews/batfish/batfish/7028#-Maj8EwU7kU8lbm6Sie4:-Maj8EwU7kU8lbm6Sie5:b4zobsy) ([raw file](https://github.com/batfish/batfish/blob/ecca3be22ef63263a9919b07a8698da009f0eb2d/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java#L454)):*
> ```Java
>     return OspfIntraAreaRoute.builder()
>         .setNetwork(ifaceAddress.getPrefix())
>         .setNonRouting(true)
> ```

please add a comment about why these are non-routing
___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java, line 608 at r4](https://reviewable.io/reviews/batfish/batfish/7028#-Maj8hdpBtl4n9EjW7Vv:-Maj8hdpBtl4n9EjW7Vw:b-qelm97) ([raw file](https://github.com/batfish/batfish/blob/ecca3be22ef63263a9919b07a8698da009f0eb2d/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java#L608)):*
> ```Java
>             .setMetric(route.getMetric() + incrementalCost)
>             .setAdmin(_process.getAdminCosts().get(route.getProtocol()))
>             .setNextHopInterface(ifaceName)
> ```

1. Comment that NHIP should be set already (maybe assert that it's there)
2. Could `setNextHop(NextHopInterface.of(ifaceName, route.getNextHopIp()`))`
___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java, line 943 at r4](https://reviewable.io/reviews/batfish/batfish/7028#-MajDuhL3xXmeDMlnwfe:-MajDuhL3xXmeDMlnwff:b-7t8j8l) ([raw file](https://github.com/batfish/batfish/blob/ecca3be22ef63263a9919b07a8698da009f0eb2d/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java#L943)):*
> ```Java
>                             .setNextHopIp(nextHopIp)
>                             .setNonRouting(true)
>                             .build())
> ```

Should we be clearing next hop interface on export? (i think you'd have to `setNextHop(NextHopIp.of(ip))`; `setNextHopIp` does not clear next hop interface)
___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java, line 1233 at r4](https://reviewable.io/reviews/batfish/batfish/7028#-MajERz66NnE2icrRTrt:-MajERz66NnE2icrRTru:b-2u944d) ([raw file](https://github.com/batfish/batfish/blob/1a8014661c20824266441c860b7b2b6c20a9f01a/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java#L1233)):*
> ```Java
>   @Nonnull
>   @VisibleForTesting
>   OspfExternalType2Route.Builder transformType2RouteOnImport(
> ```

nit: could you un-import this builder and revert this to `OspfExternalType2Route.Builder`? there are so many OSPF route types, it's nearly imperative that the builders all be explicitly labeled
___
*[projects/batfish/src/test/java/org/batfish/dataplane/ibdp/OspfRoutingProcessTest.java, line 266 at r4](https://reviewable.io/reviews/batfish/batfish/7028#-MajYoE4Dl9RaK6o18k5:-MajYoE4Dl9RaK6o18k6:b-85y80n) ([raw file](https://github.com/batfish/batfish/blob/ecca3be22ef63263a9919b07a8698da009f0eb2d/projects/batfish/src/test/java/org/batfish/dataplane/ibdp/OspfRoutingProcessTest.java#L266)):*
> ```Java
>             .setOwner(c)
>             .setVrf(vrf)
>             .setAddresses(ACTIVE_ADDR_1)
> ```

shouldn't make any practical difference, but is there any reason you switched these to `setAddresses`?
___
*[projects/batfish/src/test/java/org/batfish/dataplane/ibdp/OspfRoutingProcessTest.java, line 647 at r4](https://reviewable.io/reviews/batfish/batfish/7028#-MajZFN-8urdXdyASDN2:-MajZFN-8urdXdyASDN3:bfnfhbx) ([raw file](https://github.com/batfish/batfish/blob/ecca3be22ef63263a9919b07a8698da009f0eb2d/projects/batfish/src/test/java/org/batfish/dataplane/ibdp/OspfRoutingProcessTest.java#L647)):*
> ```Java
>                     hasNextHopIp(equalTo(nextHopIp)),
>                     hasMetric(route1.getMetric()),
>                     isNonRouting(true)))));
> ```

What do you think about actually building the exact expected route and asserting
```
assertThat(transformed, equalTo(expectedRoute))`
```
? That tends to be my preference because it rules out any surprises. I've gotten opposition to that strategy in the past because the test fails more often. but i think the pros outweigh the cons
___
*[projects/batfish/src/test/java/org/batfish/dataplane/ibdp/OspfRoutingProcessTest.java, line 845 at r4](https://reviewable.io/reviews/batfish/batfish/7028#-Maj_JVU3b2K_3K9wXyU:-Maj_JVU3b2K_3K9wXyV:bthqi53) ([raw file](https://github.com/batfish/batfish/blob/ecca3be22ef63263a9919b07a8698da009f0eb2d/projects/batfish/src/test/java/org/batfish/dataplane/ibdp/OspfRoutingProcessTest.java#L845)):*
> ```Java
>             .setArea(1L)
>             .setAdmin(0)
>             .setNonRouting(true)
> ```

should this and the next 2 tests be starting with a builder that isn't nonrouting and assert that it becomes nonrouting?
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AbstractRouteBuilder.java, line 105 at r4](https://reviewable.io/reviews/batfish/batfish/7028#-MajINhI8P89MTspMqzl:-MajINhI8P89MTspMqzm:bmfeaxm) ([raw file](https://github.com/batfish/batfish/blob/ecca3be22ef63263a9919b07a8698da009f0eb2d/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AbstractRouteBuilder.java#L105)):*
> ```Java
>       _nextHop = NextHopInterface.of(iface, ((NextHopIp) _nextHop).getIp());
>     } else if (_nextHop instanceof NextHopInterface) {
>       _nextHop = NextHopInterface.of(iface, ((NextHopInterface) _nextHop).getIp());
> ```

oh wow that really should've been there before :fearful:
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfRoute.java, line 40 at r4](https://reviewable.io/reviews/batfish/batfish/7028#-MajWu40ClcLZU2zdNZU:-MajWu40ClcLZU2zdNZV:bo49wur) ([raw file](https://github.com/batfish/batfish/blob/ecca3be22ef63263a9919b07a8698da009f0eb2d/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfRoute.java#L40)):*
> ```Java
>     checkArgument(
>         !(nextHop instanceof NextHopInterface) || ((NextHopInterface) nextHop).getIp() != null,
>         "OSPF routes with next-hop interface must have next-hop IP.");
> ```

I don't think this is strictly necessary if the route is non-routing, but I have no problem with enforcing it anyway.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7028)* status: 10 of 15 files reviewed, 3 unresolved discussions (waiting on @corinaminer and @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java, line 454 at r4](https://reviewable.io/reviews/batfish/batfish/7028#-Maj8EwU7kU8lbm6Sie4:-MajkCMU7Zelc21IRaFG:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/ecca3be22ef63263a9919b07a8698da009f0eb2d/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java#L454)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

please add a comment about why these are non-routing
</blockquote></details>

done
___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java, line 608 at r4](https://reviewable.io/reviews/batfish/batfish/7028#-Maj8hdpBtl4n9EjW7Vv:-Majk9qBDTaw2UDR1mjP:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/ecca3be22ef63263a9919b07a8698da009f0eb2d/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java#L608)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

1. Comment that NHIP should be set already (maybe assert that it's there)
2. Could `setNextHop(NextHopInterface.of(ifaceName, route.getNextHopIp()`))`
</blockquote></details>

done
___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java, line 943 at r4](https://reviewable.io/reviews/batfish/batfish/7028#-MajDuhL3xXmeDMlnwfe:-Majk9Fx5pFfDZJo8d2p:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/ecca3be22ef63263a9919b07a8698da009f0eb2d/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java#L943)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Should we be clearing next hop interface on export? (i think you'd have to `setNextHop(NextHopIp.of(ip))`; `setNextHopIp` does not clear next hop interface)
</blockquote></details>

done
___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java, line 1233 at r4](https://reviewable.io/reviews/batfish/batfish/7028#-MajERz66NnE2icrRTrt:-MajkNi_9bUNJ4X4_M5D:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/1a8014661c20824266441c860b7b2b6c20a9f01a/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java#L1233)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

nit: could you un-import this builder and revert this to `OspfExternalType2Route.Builder`? there are so many OSPF route types, it's nearly imperative that the builders all be explicitly labeled
</blockquote></details>

done
___
*[projects/batfish/src/test/java/org/batfish/dataplane/ibdp/OspfRoutingProcessTest.java, line 266 at r4](https://reviewable.io/reviews/batfish/batfish/7028#-MajYoE4Dl9RaK6o18k5:-MajkPBr8VIhFmw080Yj:b-awy26u) ([raw file](https://github.com/batfish/batfish/blob/ecca3be22ef63263a9919b07a8698da009f0eb2d/projects/batfish/src/test/java/org/batfish/dataplane/ibdp/OspfRoutingProcessTest.java#L266)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

shouldn't make any practical difference, but is there any reason you switched these to `setAddresses`?
</blockquote></details>

yeah, to clear secondary addresses
___
*[projects/batfish/src/test/java/org/batfish/dataplane/ibdp/OspfRoutingProcessTest.java, line 647 at r4](https://reviewable.io/reviews/batfish/batfish/7028#-MajZFN-8urdXdyASDN2:-MajkS2i3JQ_PyQPuNnf:b-tb84rn) ([raw file](https://github.com/batfish/batfish/blob/ecca3be22ef63263a9919b07a8698da009f0eb2d/projects/batfish/src/test/java/org/batfish/dataplane/ibdp/OspfRoutingProcessTest.java#L647)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

What do you think about actually building the exact expected route and asserting
```
assertThat(transformed, equalTo(expectedRoute))`
```
? That tends to be my preference because it rules out any surprises. I've gotten opposition to that strategy in the past because the test fails more often. but i think the pros outweigh the cons
</blockquote></details>

Asserting on exact route makes error message worse, and relies on details not under test.
___
*[projects/batfish/src/test/java/org/batfish/dataplane/ibdp/OspfRoutingProcessTest.java, line 845 at r4](https://reviewable.io/reviews/batfish/batfish/7028#-Maj_JVU3b2K_3K9wXyU:-MajmbqqElp1YWlYOl7w:bvlq4i3) ([raw file](https://github.com/batfish/batfish/blob/ecca3be22ef63263a9919b07a8698da009f0eb2d/projects/batfish/src/test/java/org/batfish/dataplane/ibdp/OspfRoutingProcessTest.java#L845)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

should this and the next 2 tests be starting with a builder that isn't nonrouting and assert that it becomes nonrouting?
</blockquote></details>

covered by updated first assertion now.
I don't see the need to do this in more than one assertion, let alone in all tests of this function.

**Review by corinaminer — COMMENTED** [review]
> Reviewed 1 of 7 files at r1, 2 of 6 files at r3, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7028)* status: all files reviewed, 2 unresolved discussions (waiting on @arifogel and @dhalperi)

___
*[projects/batfish/src/test/java/org/batfish/dataplane/ibdp/OspfRoutingProcessTest.java, line 845 at r4](https://reviewable.io/reviews/batfish/batfish/7028#-Maj_JVU3b2K_3K9wXyU:-Majt_9Z5fckUBXtCw6w:bw62jx9) ([raw file](https://github.com/batfish/batfish/blob/ecca3be22ef63263a9919b07a8698da009f0eb2d/projects/batfish/src/test/java/org/batfish/dataplane/ibdp/OspfRoutingProcessTest.java#L845)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

covered by updated first assertion now.
I don't see the need to do this in more than one assertion, let alone in all tests of this function.
</blockquote></details>

I think you should just create a fresh route for each test rather than reusing the builder. Should be possible to do this fairly succinctly; you could build one test route at the start and use `toBuilder()` for each test, or use `OspfExternalType1Route.testBuilder()`. I agree that the tests are sufficient as-is, but they're confusing because it's easy to miss that the builder has become non-routing in later tests.

Alternatively, expand your "non-routing -> non-routing" comments -- they should make it clear that in practice we expect all routes passed to this function to be routing, and all routes it returns to be non-routing, and that in these tests we're passing in non-routing routes for convenience.
___
*[projects/batfish/src/test/java/org/batfish/dataplane/ibdp/OspfRoutingProcessTest.java, line 854 at r5](https://reviewable.io/reviews/batfish/batfish/7028#-Majtwcp4xwhJWTKgyQv:-Majtwcp4xwhJWTKgyQw:b-a79kwb) ([raw file](https://github.com/batfish/batfish/blob/7808c9946e622956b0f3a0b0ccc963eea2be1ce5/projects/batfish/src/test/java/org/batfish/dataplane/ibdp/OspfRoutingProcessTest.java#L854)):*
> ```Java
>             Stream.of(new RouteAdvertisement<>((OspfExternalType1Route) builder.build())),
>             AREA0_CONFIG),
>         contains(new RouteAdvertisement<>(builder.setArea(0).setNonRouting(true).build())));
> ```

is this test passing? `transformType1RoutesOnExport` is going to modify the next hop
___
*[projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java, line 425 at r4](https://reviewable.io/reviews/batfish/batfish/7028#-MajpBxs5Ju7ONDsiA-H:-MajpBxs5Ju7ONDsiA-I:bevzofr) ([raw file](https://github.com/batfish/batfish/blob/ecca3be22ef63263a9919b07a8698da009f0eb2d/projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java#L425)):*
> ```Java
>   private static @Nonnull OspfInterAreaRoute.Builder ospfIARouteBuilder() {
>     return OspfInterAreaRoute.builder()
>         .setNextHop(NextHopInterface.of("dummyInterface", Ip.parse("3.3.3.3")))
> ```

fyi... I suspect these methods could (and should) all be swapped out for the various route types' `testBuilder()` methods, but not in this PR.
___
*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/OspfRouteTest.java, line 44 at r4](https://reviewable.io/reviews/batfish/batfish/7028#-MajsGVV34Y0owLtiIw2:-MajsGVV34Y0owLtiIw3:b-xc1glt) ([raw file](https://github.com/batfish/batfish/blob/ecca3be22ef63263a9919b07a8698da009f0eb2d/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/OspfRouteTest.java#L44)):*
> ```Java
>   }
> 
>   private static OspfIntraAreaRoute.Builder testBuilder() {
> ```

there's an existing `testBuilder()` you can use in `OspfExternalType1Route` you can use. though you'd need to give it a network every time, so if you'd prefer to keep this one for that reason, i'm ok with that

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7028)* status: 13 of 15 files reviewed, 2 unresolved discussions (waiting on @corinaminer and @dhalperi)

___
*[projects/batfish/src/test/java/org/batfish/dataplane/ibdp/OspfRoutingProcessTest.java, line 845 at r4](https://reviewable.io/reviews/batfish/batfish/7028#-Maj_JVU3b2K_3K9wXyU:-Mal9z0R-q5voPZr2u_c:btp6gzj) ([raw file](https://github.com/batfish/batfish/blob/ecca3be22ef63263a9919b07a8698da009f0eb2d/projects/batfish/src/test/java/org/batfish/dataplane/ibdp/OspfRoutingProcessTest.java#L845)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

I think you should just create a fresh route for each test rather than reusing the builder. Should be possible to do this fairly succinctly; you could build one test route at the start and use `toBuilder()` for each test, or use `OspfExternalType1Route.testBuilder()`. I agree that the tests are sufficient as-is, but they're confusing because it's easy to miss that the builder has become non-routing in later tests.

Alternatively, expand your "non-routing -> non-routing" comments -- they should make it clear that in practice we expect all routes passed to this function to be routing, and all routes it returns to be non-routing, and that in these tests we're passing in non-routing routes for convenience.
</blockquote></details>

creating fresh bulider each time now.
___
*[projects/batfish/src/test/java/org/batfish/dataplane/ibdp/OspfRoutingProcessTest.java, line 854 at r5](https://reviewable.io/reviews/batfish/batfish/7028#-Majtwcp4xwhJWTKgyQv:-Mal3y0PBkZ0ogojHRee:biq3mgj) ([raw file](https://github.com/batfish/batfish/blob/7808c9946e622956b0f3a0b0ccc963eea2be1ce5/projects/batfish/src/test/java/org/batfish/dataplane/ibdp/OspfRoutingProcessTest.java#L854)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

is this test passing? `transformType1RoutesOnExport` is going to modify the next hop
</blockquote></details>

The test is passing because that function is not modifying the next hop, and that's the bug causing the ref gendp crash.
Fixed, and updated tests.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7028)* status: 13 of 15 files reviewed, 2 unresolved discussions (waiting on @arifogel, @corinaminer, and @dhalperi)

___
*[projects/batfish/src/test/java/org/batfish/dataplane/ibdp/OspfRoutingProcessTest.java, line 845 at r4](https://reviewable.io/reviews/batfish/batfish/7028#-Maj_JVU3b2K_3K9wXyU:-ManhhyU8q6wAMMVupZn:b-8vjwen) ([raw file](https://github.com/batfish/batfish/blob/ecca3be22ef63263a9919b07a8698da009f0eb2d/projects/batfish/src/test/java/org/batfish/dataplane/ibdp/OspfRoutingProcessTest.java#L845)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

creating fresh bulider each time now.
</blockquote></details>

oops, missed this function

**Review by corinaminer — COMMENTED** [review]
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7028)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dhalperi)

___
*[projects/batfish/src/test/java/org/batfish/dataplane/ibdp/OspfRoutingProcessTest.java, line 952 at r6](https://reviewable.io/reviews/batfish/batfish/7028#-MaoAGtN8Lwx5Dyk9G6p:-MaoAGtN8Lwx5Dyk9G6q:bi1z557) ([raw file](https://github.com/batfish/batfish/blob/ead1e089c5fc1db5b63bd5e82aa995d8f782ce51/projects/batfish/src/test/java/org/batfish/dataplane/ibdp/OspfRoutingProcessTest.java#L952)):*
> ```Java
>     assertThat(
>         routingProcess.transformType1RoutesOnExport(
>             Stream.of(new RouteAdvertisement<>((OspfExternalType1Route) base.toBuilder().build())),
> ```

nit: can just use `base`. Happens again in the same place in next test. nonblocking though

**Pull request merged**
