### PR TITLE
Added IpSpace null check

### PR DESCRIPTION
**Pull request by sfraint**
Added null check for IpSpace in FwFromPrefixList

### CODE REVIEW

**Comment by dhalperi** [comment]
1. Please confirm this has fixed the end-to-end issue in the original bug report? Aka, that you've parsed the affected network and it parses successfully now?

2. Looks like we need to use nullability analysis better here. Can you please consult with @anothermattbrown on strategy? I suspect we need to put `@Nullable` annotations on all the getters and setters, and then re-run the IntelliJ nullability inspection that should have caught this bug.

**Comment by dhalperi** [comment]
2.... as an alternative to whack-a-mole that we're doing right now.

**Comment by sfraint** [comment]
1. The network parses successfully now (I tried with the full network this time instead of just the file mentioned)

2. Agreed, will do

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1286#-:-LBYuIzoAm2-4rDZHOet:bkarkhf)*

**Comment by dhalperi** [comment]
:thumbsup: 

---







*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1286#-:-LBZASzZ3rhLvrbXzx-g:b4c9lyr)*

**Comment by arifogel** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1286#-:-LBZFx169L2tKpLS_4Jo:bnfp4nl)*

**Comment by anothermattbrown** [comment]
Reviewed 4 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromPrefixList.java, line 44 at r2](https://reviewable.io/reviews/batfish/batfish/1286#-LBawwKzDR-sV7sWn9L7:-LBawwKzDR-sV7sWn9L8:b-kedwwx) ([raw file](https://github.com/batfish/batfish/blob/a34abcda33f239095f7faf38ca889b0005c99b28/projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromPrefixList.java#L44)):*
> ```Java
>               .collect(ImmutableList.toImmutableList());
> 
>       ImmutableList.Builder<IpSpace> ipSpaceBuilder = ImmutableList.builder();
> ```

Simpler:
```
IpSpace srcOrDstIpSpace = 
  IpWildcardSetIpSpaces
    .builder()
    .including(sourcePrefixList.getMatchingIps())
    .build();
headerSpaceBuilder.setSrcOrDstIps(
  AclIpSpace.union(
    srcOrDstIpSpace, 
    headerSpaceBuilder.getSrcOrDstIps());
```

`AclIpSpace::union` does the null check you need here.

Still, I don't love that `HeaderSpaceBuilder` has getters, or that we're potentially setting the `srcOrDstIps` multiple times. Seems non-idiomatic in a way that's inviting bugs to creep in.

Is it really necessary to be updating the `HeaderSpaceBuilder` in this way? How many of its fields are being updated? Can we compute the final values and then set once?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1286)*

**Comment by anothermattbrown** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromPrefixList.java, line 44 at r2](https://reviewable.io/reviews/batfish/batfish/1286#-LBawwKzDR-sV7sWn9L7:-LBb3mQ7BwukUwWpT6og:b-bk5ip0) ([raw file](https://github.com/batfish/batfish/blob/a34abcda33f239095f7faf38ca889b0005c99b28/projects/batfish/src/main/java/org/batfish/representation/juniper/FwFromPrefixList.java#L44)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

How about HeaderSpace.Builder.addSrcOrDstIps to do the union inside the builder? Same for other `IpSpace` fields in builder.
</blockquote></details>

Works for me.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1286)*

**Comment by anothermattbrown** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1286#-:-LBc6ald8DvOwz0AYua4:bnfp4nl)*

**Pull request merged**
