### PR TITLE
IpSpaceToRangeSet

### PR DESCRIPTION
**Pull request by anothermattbrown**
convert (some) IpSpaces to equivalent RangeSets.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7990#-:-MuriF-27loRkcqDgLpP:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @anothermattbrown)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/visitors/IpSpaceToRangeSet.java, line 68 at r1](https://reviewable.io/reviews/batfish/batfish/7990#-Muri3LR0ncoXYxD2ylk:-Muri3LS9zgEtUweHC4b:b-br4z6i) ([raw file](https://github.com/batfish/batfish/blob/c663e6a26d8fb2d34f2cefdf0fd01e57e15379e9/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/visitors/IpSpaceToRangeSet.java#L68)):*
> ```Java
>   @Override
>   public RangeSet<Ip> visitIpSpaceReference(IpSpaceReference ipSpaceReference) {
>     throw new UnsupportedOperationException("Converting IpWildcard to RangeSet is unsupported");
> ```

Not obvious this should be disallowed, unless it's not needed. Regardless, typo in message.

Fix at discretion.



_Code quote:_
```Java
IpWildcard
```

**Review by dhalperi — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7990#-:-Muroyy39Fc1-j_eEJ-0:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @anothermattbrown)

**Review by anothermattbrown — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7990)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @dhalperi)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/visitors/IpSpaceToRangeSet.java, line 68 at r1](https://reviewable.io/reviews/batfish/batfish/7990#-Muri3LR0ncoXYxD2ylk:-MurrBZ_0pHQw8GlZkm5:b-e9kljp) ([raw file](https://github.com/batfish/batfish/blob/c663e6a26d8fb2d34f2cefdf0fd01e57e15379e9/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/visitors/IpSpaceToRangeSet.java#L68)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Not obvious this should be disallowed, unless it's not needed. Regardless, typo in message.

Fix at discretion.
</blockquote></details>

typo fixed. yes, not needed so I didn't want to take on the extra complexity now

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7990)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown)

**Pull request merged**
