### PR TITLE
add AclTrace to tracefilters question

### PR DESCRIPTION
**Pull request by arifogel**
- implement table matchers

### CODE REVIEW

**Comment by ratulm** [comment]
:lgtm: mostly requests for javadoc

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclTrace.java, line 40 at r2](https://reviewable.io/reviews/batfish/batfish/1517#-LDj4Cg5C1KnQO4AXJtu:-LDj4Cg5C1KnQO4AXJtv:b5fubzl) ([raw file](https://github.com/batfish/batfish/blob/525c8285f44ee06cb3c6704c864af5606038ea26/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclTrace.java#L40)):*
> ```Java
>   }
> 
>   public FilterResult computeFilterResult() {
> ```

javadoc

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/ForAll.java, line 8 at r2](https://reviewable.io/reviews/batfish/batfish/1517#-LDj4fewDOT7ZYkM_uzk:-LDj4fewDOT7ZYkM_uzl:b5fubzl) ([raw file](https://github.com/batfish/batfish/blob/525c8285f44ee06cb3c6704c864af5606038ea26/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/ForAll.java#L8)):*
> ```Java
> import org.hamcrest.TypeSafeDiagnosingMatcher;
> 
> final class ForAll<E> extends TypeSafeDiagnosingMatcher<Iterable<? extends E>> {
> ```

javadoc

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1517#-:-LDj6bQL0vzGMeQnlWwn:b-w3fn4s)*

**Comment by arifogel** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/ForAll.java, line 8 at r2](https://reviewable.io/reviews/batfish/batfish/1517#-LDj4fewDOT7ZYkM_uzk:-LDnRwqh7YKBIopPjfK9:bmm5kb7) ([raw file](https://github.com/batfish/batfish/blob/525c8285f44ee06cb3c6704c864af5606038ea26/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/ForAll.java#L8)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

javadoc
</blockquote></details>

This is documented at call-site of constructor.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1517)*

**Comment by arifogel** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/ForAll.java, line 8 at r2](https://reviewable.io/reviews/batfish/batfish/1517#-LDj4fewDOT7ZYkM_uzk:-LDnS2ok2XvwY8Qj2qlW:bwwvrtr) ([raw file](https://github.com/batfish/batfish/blob/525c8285f44ee06cb3c6704c864af5606038ea26/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/ForAll.java#L8)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

This is documented at call-site of constructor.
</blockquote></details>

Sorry, let me be specific. This is documented via org.batfish.datamodel.matchers.DataModelMatchers.forAll

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1517)*

**Comment by arifogel** [comment]
Review status: 17 of 19 files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclTrace.java, line 40 at r2](https://reviewable.io/reviews/batfish/batfish/1517#-LDj4Cg5C1KnQO4AXJtu:-LDnVj0N3yyOD2EV3VxC:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/525c8285f44ee06cb3c6704c864af5606038ea26/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclTrace.java#L40)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

javadoc
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1517)*

**Comment by ratulm** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1517#-:-LDnbWsv6VohoZH2EXHE:bnfp4nl)*

**Comment by ratulm** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1517#-:-LDnj_8bCyPAaHIhqG1j:bnfp4nl)*

**Comment by ratulm** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1517#-:-LDrKuty-l08O8nmidvb:bnfp4nl)*

**Pull request merged**
