### PR TITLE
FRR bit more parsing within address families

### PR DESCRIPTION
**Pull request by ratulm**
Helps not jump out of the parent context.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6590)* status: all files reviewed, 2 unresolved discussions (waiting on @arifogel and @ratulm)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrr_bgp.g4, line 360 at r2](https://reviewable.io/reviews/batfish/batfish/6590#-MRwO1ucCfP8fkka7xEo:-MRwO1ucCfP8fkka7xEp:b-wpwkvl) ([raw file](https://github.com/batfish/batfish/blob/f865b2d492608cae488aad245e63810b0793048d/projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrr_bgp.g4#L360)):*
> ```ANTLR
> sbafi_no
> :
>    NO null_rest_of_line
> ```

This is too generic. It will prevent a top-level `no` line from causing the Kleene* to exit. We need to do at least one level deeper: sbafi_no_foo, sbafi_no_bar, ...
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4, line 1319 at r2](https://reviewable.io/reviews/batfish/batfish/6590#-MRwNj5_BiInTKraR-hi:-MRwNj5_BiInTKraR-hj:bg6ggt8) ([raw file](https://github.com/batfish/batfish/blob/f865b2d492608cae488aad245e63810b0793048d/projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4#L1319)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> M_Word_ROUTE_MAP
> :
>    'route-map' -> type (ROUTE_MAP)
> ;
> ```
</details>


@arifogel - would you do this or introduce a new syntax-specific mode?

This change as-is will prevent `route-map` from being a valid word in any context.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6590)* status: all files reviewed, 2 unresolved discussions (waiting on @dhalperi and @ratulm)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4, line 1319 at r2](https://reviewable.io/reviews/batfish/batfish/6590#-MRwNj5_BiInTKraR-hi:-MRwQzTC4F1lm8g0_78Z:b6evkpw) ([raw file](https://github.com/batfish/batfish/blob/f865b2d492608cae488aad245e63810b0793048d/projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4#L1319)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> M_Word_ROUTE_MAP
> :
>    'route-map' -> type (ROUTE_MAP)
> ;
> ```

@arifogel - would you do this or introduce a new syntax-specific mode?

This change as-is will prevent `route-map` from being a valid word in any context.
</blockquote></details>

I would definitely introduce a new mode for the use case in mind. `M_Word` should not be extended with more tokens.

If it is necessary to read ahead to know whether you actually want a `WORD` or not, there are ways to do that.

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6590)* status: all files reviewed, 2 unresolved discussions (waiting on @arifogel, @dhalperi, and @ratulm)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4, line 1319 at r2](https://reviewable.io/reviews/batfish/batfish/6590#-MRwNj5_BiInTKraR-hi:-MRwS0Vv3bOYo-e9FSWF:bdgk7g1) ([raw file](https://github.com/batfish/batfish/blob/f865b2d492608cae488aad245e63810b0793048d/projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4#L1319)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

I would definitely introduce a new mode for the use case in mind. `M_Word` should not be extended with more tokens.

If it is necessary to read ahead to know whether you actually want a `WORD` or not, there are ways to do that.
</blockquote></details>

So, if I want to be able to parse the following variants:

   **import** **vrf** my-vrf
   
   **import** **vrf** **route-map** my-route-map 

I should define a new mode that is entered on *import* and then allows for VRF, ROUTE_MAP, and Word?

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6590)* status: all files reviewed, 2 unresolved discussions (waiting on @dhalperi and @ratulm)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4, line 1319 at r2](https://reviewable.io/reviews/batfish/batfish/6590#-MRwNj5_BiInTKraR-hi:-MRwT8aM7n3bJGwf5Hq7:b8gqeoj) ([raw file](https://github.com/batfish/batfish/blob/f865b2d492608cae488aad245e63810b0793048d/projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4#L1319)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

So, if I want to be able to parse the following variants:

   **import** **vrf** my-vrf
   
   **import** **vrf** **route-map** my-route-map 

I should define a new mode that is entered on *import* and then allows for VRF, ROUTE_MAP, and Word?

</blockquote></details>

Assuming you cannot use just `vrf` as a trigger, I would recommend:
```
mode M_Import;
M_Import_VRF: 'vrf' -> mode(M_ImportVrf);
M_Import_WS: M_Whitespace+ -> skip

mode M_ImportVrf;
M_ImportVrf_ROUTE_MAP: 'route-map' -> type(ROUTE_MAP), mode(M_Word);
M_ImportVrf_OTHER: . -> more, mode(M_Word);

```

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6590)* status: all files reviewed, 2 unresolved discussions (waiting on @dhalperi and @ratulm)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4, line 1319 at r2](https://reviewable.io/reviews/batfish/batfish/6590#-MRwNj5_BiInTKraR-hi:-MRwTqdm09fhxM8C8mNW:b-rmocgo) ([raw file](https://github.com/batfish/batfish/blob/f865b2d492608cae488aad245e63810b0793048d/projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4#L1319)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Assuming you cannot use just `vrf` as a trigger, I would recommend:
```
mode M_Import;
M_Import_VRF: 'vrf' -> mode(M_ImportVrf);
M_Import_WS: M_Whitespace+ -> skip

mode M_ImportVrf;
M_ImportVrf_ROUTE_MAP: 'route-map' -> type(ROUTE_MAP), mode(M_Word);
M_ImportVrf_OTHER: . -> more, mode(M_Word);

```
</blockquote></details>

erm, may need to add a whitespace rule to `M_ImportVrf` as well

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6590)* status: all files reviewed, 2 unresolved discussions (waiting on @dhalperi and @ratulm)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4, line 1319 at r2](https://reviewable.io/reviews/batfish/batfish/6590#-MRwNj5_BiInTKraR-hi:-MRwUA9H5pXVBGnTd6Yj:b-46ow6i) ([raw file](https://github.com/batfish/batfish/blob/f865b2d492608cae488aad245e63810b0793048d/projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4#L1319)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

erm, may need to add a whitespace rule to `M_ImportVrf` as well
</blockquote></details>

also for safety, should add newline rules that pop out

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6590)* status: all files reviewed, 2 unresolved discussions (waiting on @dhalperi and @ratulm)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4, line 1319 at r2](https://reviewable.io/reviews/batfish/batfish/6590#-MRwNj5_BiInTKraR-hi:-MRwUMUd8z5ATKV9Rt4P:beshble) ([raw file](https://github.com/batfish/batfish/blob/f865b2d492608cae488aad245e63810b0793048d/projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4#L1319)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

also for safety, should add newline rules that pop out
</blockquote></details>

gah, and instead of using `.`, use something that can be part of a word, like `F_WordChar`. Of course this will be an issue if the word is a single char. I think we may have examples that deal with that elsewhere..

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6590)* status: all files reviewed, 1 unresolved discussion (waiting on @ratulm)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4, line 1319 at r2](https://reviewable.io/reviews/batfish/batfish/6590#-MRwNj5_BiInTKraR-hi:-MRwVA61ANYct5Vr0Q8T:b-uh9yf5) ([raw file](https://github.com/batfish/batfish/blob/f865b2d492608cae488aad245e63810b0793048d/projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4#L1319)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

gah, and instead of using `.`, use something that can be part of a word, like `F_WordChar`. Of course this will be an issue if the word is a single char. I think we may have examples that deal with that elsewhere..
</blockquote></details>

OK, use `less` instead of `more`, and that will rewind whatever has been read.
See `BatfishLexer::less`

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6590)* status: all files reviewed, 2 unresolved discussions (waiting on @dhalperi and @ratulm)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4, line 1319 at r2](https://reviewable.io/reviews/batfish/batfish/6590#-MRwNj5_BiInTKraR-hi:-MRwVQnvBrBZfTQr6WQ_:biugah9) ([raw file](https://github.com/batfish/batfish/blob/f865b2d492608cae488aad245e63810b0793048d/projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4#L1319)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

OK, use `less` instead of `more`, and that will rewind whatever has been read.
See `BatfishLexer::less`
</blockquote></details>

Example in `F5BigipStructuredLexer`:
```
M_VariableSubstitution_BACKSLASH
:
  '\\'
  {
    less();
  } -> popMode
;
```

Note that since `less` is not a built-in, you have to call it inside of braces before the arrow.

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6590)* status: all files reviewed, 2 unresolved discussions (waiting on @arifogel, @dhalperi, and @ratulm)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4, line 1319 at r2](https://reviewable.io/reviews/batfish/batfish/6590#-MRwNj5_BiInTKraR-hi:-MRwVnhX7cssfuC2bsZb:b1rosos) ([raw file](https://github.com/batfish/batfish/blob/f865b2d492608cae488aad245e63810b0793048d/projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4#L1319)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Example in `F5BigipStructuredLexer`:
```
M_VariableSubstitution_BACKSLASH
:
  '\\'
  {
    less();
  } -> popMode
;
```

Note that since `less` is not a built-in, you have to call it inside of braces before the arrow.
</blockquote></details>

do you feel like taking over this PR? :)

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6590)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrr_bgp.g4, line 360 at r2](https://reviewable.io/reviews/batfish/batfish/6590#-MRwO1ucCfP8fkka7xEo:-MRxJmBy881Gk36DhegI:bimqgb3) ([raw file](https://github.com/batfish/batfish/blob/f865b2d492608cae488aad245e63810b0793048d/projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrr_bgp.g4#L360)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

This is too generic. It will prevent a top-level `no` line from causing the Kleene* to exit. We need to do at least one level deeper: sbafi_no_foo, sbafi_no_bar, ...
</blockquote></details>

Just did the full sentence I wanted for now.  I am guessing things like `no neighbor foo` can occur at the parent level too.
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4, line 1319 at r2](https://reviewable.io/reviews/batfish/batfish/6590#-MRwNj5_BiInTKraR-hi:-MRxOVFI2FjSZdUJg5gv:b-hf3pkv) ([raw file](https://github.com/batfish/batfish/blob/f865b2d492608cae488aad245e63810b0793048d/projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4#L1319)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

do you feel like taking over this PR? :) 
</blockquote></details>

Ok, I think I got it :)

**Review by arifogel — COMMENTED** [review]
> Reviewed 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6590)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @dhalperi and @ratulm)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4, line 1301 at r3](https://reviewable.io/reviews/batfish/batfish/6590#-MS-4rtL6Ks_eCbtUbpN:-MS-3ys23eu2Q6ce1z8B:b76w8gc) ([raw file](https://github.com/batfish/batfish/blob/401d6035d3dfbeecba2dbbcdb8c53743411d7b82/projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4#L1301)):*
> ```ANTLR
> M_Import_Other
> :
>    F_Word
> ```

Final note - you could just emit WORD and pop here instead of switching to `M_Word`. I hope you've enjoyed the journey. Leaving it is fine too.

Separately, based on the definition of this token, might as well rename it to `M_Import_WORD`.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6590)* status: all files reviewed, 1 unresolved discussion (waiting on @ratulm)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4, line 1319 at r2](https://reviewable.io/reviews/batfish/batfish/6590#-MRwNj5_BiInTKraR-hi:-MRwV8P16yteY0O9dFSX:b-n2n852) ([raw file](https://github.com/batfish/batfish/blob/f865b2d492608cae488aad245e63810b0793048d/projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4#L1319)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

Ok, I think I got it :) 
</blockquote></details>

lgtm but I'll let Ari review finally.

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6590)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6590)* status: all files reviewed, 2 unresolved discussions (waiting on @ratulm)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4, line 1303 at r4](https://reviewable.io/reviews/batfish/batfish/6590#-MS-AFE3-Z1UcBn7dF4O:-MS-AFE3-Z1UcBn7dF4P:b-q86hxb) ([raw file](https://github.com/batfish/batfish/blob/62938526d77b12ae24eb0c4d2ccb9b5d8846d1e5/projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4#L1303)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
> M_Import_ROUTE_MAP
> :
>    'route-map' -> type ( ROUTE_MAP ), mode(M_Word)
> ;
> M_Import_WORD
> :
>    F_Word -> type ( WORD ), popMode
> ;
> ```
</details>

I think these two should be `M_ImportVrf_` not `M_Import_`. We're in the ImportVrf mode.
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4, line 1360 at r4](https://reviewable.io/reviews/batfish/batfish/6590#-MS-AJ-uAq1m3ScfRFru:-MS-AJ-uAq1m3ScfRFrv:b-za2cwh) ([raw file](https://github.com/batfish/batfish/blob/62938526d77b12ae24eb0c4d2ccb9b5d8846d1e5/projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4#L1360)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> M_Word_ROUTE_MAP
> :
>    'route-map' -> type (ROUTE_MAP)
> ;
> ```
</details>

drop this now?

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6590)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @arifogel and @dhalperi)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4, line 1303 at r4](https://reviewable.io/reviews/batfish/batfish/6590#-MS-AFE3-Z1UcBn7dF4O:-MS-BIVjBD7JGkwBIm-O:bd30ifx) ([raw file](https://github.com/batfish/batfish/blob/62938526d77b12ae24eb0c4d2ccb9b5d8846d1e5/projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4#L1303)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> M_Import_ROUTE_MAP
> :
>    'route-map' -> type ( ROUTE_MAP ), mode(M_Word)
> ;
> M_Import_WORD
> :
>    F_Word -> type ( WORD ), popMode
> ;
> ```
I think these two should be `M_ImportVrf_` not `M_Import_`. We're in the ImportVrf mode.
</blockquote></details>

good catch
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4, line 1360 at r4](https://reviewable.io/reviews/batfish/batfish/6590#-MS-AJ-uAq1m3ScfRFru:-MS-BK_wEaFRm2hGVUkq:b-a2xieb) ([raw file](https://github.com/batfish/batfish/blob/62938526d77b12ae24eb0c4d2ccb9b5d8846d1e5/projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4#L1360)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> M_Word_ROUTE_MAP
> :
>    'route-map' -> type (ROUTE_MAP)
> ;
> ```
drop this now?
</blockquote></details>

this one too

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6590)* status: all files reviewed, 2 unresolved discussions (waiting on @dhalperi)

**Pull request merged**
