### PR TITLE
Add line mapping capability

### PR DESCRIPTION
**Pull request by sfraint**
Infrastructure to support mapping flattened lines to original lines.

High level change is to make the flat `CombinedParser` aware of a `FlattenerLineMap` (if applicable) to translate flat line numbers to original line numbers.  The `CombinedParser` can then be used to lookup original line numbers in `ParseTreePrettyPrinter`, `ConfigurationBuilder`, etc.

### CODE REVIEW

**Comment by sfraint** [comment]
Review status: 0 of 12 files reviewed, 1 unresolved discussion (waiting on @anothermattbrown, @dhalperi, and @arifogel)

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1707#-LFP5E4k66LWM2sI86Fz:-LFP5E4k66LWM2sI86G-:b-744wej) (no related file):*
PAN and Juniper flat line preservation is not handled yet, those changes will follow this PR.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1707)*

**Comment by arifogel** [comment]
Reviewed 10 of 12 files at r1, 2 of 2 files at r3.
Review status: all files reviewed, 4 unresolved discussions (waiting on @arifogel, @sfraint, @anothermattbrown, and @dhalperi)

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/grammar/BatfishCombinedParser.java, line 138 at r3](https://reviewable.io/reviews/batfish/batfish/1707#-LFTfd6q0xntrrB5iksD:-LFTfd6q0xntrrB5iksE:b-yy7098) ([raw file](https://github.com/batfish/batfish/blob/f1db7ccecbb8ec87d6df7e0b6f5451b4975eb320/projects/batfish-common-protocol/src/main/java/org/batfish/grammar/BatfishCombinedParser.java#L138)):*
> ```Java
>   public int getLine(@Nonnull Token t) {
>     int line = t.getLine();
>     return (_lineMap == null) ? line : _lineMap.getOriginalLine(line, t.getCharPositionInLine());
> ```

optional: `firstNonNull` for legibility

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/grammar/flattener/Flattener.java, line 10 at r3](https://reviewable.io/reviews/batfish/batfish/1707#-LFTgAGW7J2D2ScQHsfL:-LFTgAGW7J2D2ScQHsfM:b-vpm8ao) ([raw file](https://github.com/batfish/batfish/blob/f1db7ccecbb8ec87d6df7e0b6f5451b4975eb320/projects/batfish-common-protocol/src/main/java/org/batfish/grammar/flattener/Flattener.java#L10)):*
> ```Java
>    * Return map of new line number to word map, where word map is map of position in new line to
>    * original line number.
>    */
> ```

Seems like this just gives you a `FlatterLineMap`. Details about the structure of a `FlattenerLineMap` should just go in `FlattenerLineMap`.

---

*[projects/batfish/src/main/java/org/batfish/grammar/juniper/JuniperFlattener.java, line 125 at r3](https://reviewable.io/reviews/batfish/batfish/1707#-LFTm-Fk2ekBZcRrXMr_:-LFTm-Fk2ekBZcRrXMra:bn1cxoa) ([raw file](https://github.com/batfish/batfish/blob/f1db7ccecbb8ec87d6df7e0b6f5451b4975eb320/projects/batfish/src/main/java/org/batfish/grammar/juniper/JuniperFlattener.java#L125)):*
> ```Java
>   @Override
>   public FlattenerLineMap getOriginalLineMap() {
>     throw new UnsupportedOperationException(
> ```

Is this a regression in terms of crashing? Same goes for other throwing implementations.

---

*[projects/batfish/src/main/java/org/batfish/job/ParseVendorConfigurationJob.java, line 208 at r3](https://reviewable.io/reviews/batfish/batfish/1707#-LFTmRfB-zarII3c6uHx:-LFTmRfB-zarII3c6uHy:bjm4hlw) ([raw file](https://github.com/batfish/batfish/blob/f1db7ccecbb8ec87d6df7e0b6f5451b4975eb320/projects/batfish/src/main/java/org/batfish/job/ParseVendorConfigurationJob.java#L208)):*
> ```Java
>                   currentPath));
>           try {
>             Flattener flattener =
> ```

Why do you declare a flattener here, but not above? If you are not reusing a variable, cleaner to not declare it. I.e, use earlier style consistently.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1707)*

**Comment by arifogel** [comment]
Review status: all files reviewed, 4 unresolved discussions (waiting on @arifogel, @sfraint, @anothermattbrown, and @dhalperi)

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1707#-LFP5E4k66LWM2sI86Fz:-LFTwcQ649TJgkHN9Crc:b-njy42q) (no related file):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

PAN and Juniper flat line preservation is not handled yet, those changes will follow this PR.
</blockquote></details>

If so, do you intend this to be a blocking comment?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1707)*

**Comment by sfraint** [comment]
Review status: all files reviewed, 4 unresolved discussions (waiting on @sfraint, @arifogel, @anothermattbrown, and @dhalperi)

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1707#-LFP5E4k66LWM2sI86Fz:-LFU0tnm500KjDn4ym67:bcuthlz) (no related file):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

If so, do you intend this to be a blocking comment?
</blockquote></details>

Nope, just informational; those changes are coming soon

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/grammar/BatfishCombinedParser.java, line 138 at r3](https://reviewable.io/reviews/batfish/batfish/1707#-LFTfd6q0xntrrB5iksD:-LFU39dP4__5iY0ybBQf:b-ikh750) ([raw file](https://github.com/batfish/batfish/blob/f1db7ccecbb8ec87d6df7e0b6f5451b4975eb320/projects/batfish-common-protocol/src/main/java/org/batfish/grammar/BatfishCombinedParser.java#L138)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

optional: `firstNonNull` for legibility
</blockquote></details>

Will this work since I'm dereferencing `_lineMap`? i.e. I don't think `firstNonNull(_lineMap.getOriginalLine(), line)` will work when `_lineMap` is null

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/grammar/flattener/Flattener.java, line 10 at r3](https://reviewable.io/reviews/batfish/batfish/1707#-LFTgAGW7J2D2ScQHsfL:-LFU1C4m2b-_jmJPweoT:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/f1db7ccecbb8ec87d6df7e0b6f5451b4975eb320/projects/batfish-common-protocol/src/main/java/org/batfish/grammar/flattener/Flattener.java#L10)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Seems like this just gives you a `FlatterLineMap`. Details about the structure of a `FlattenerLineMap` should just go in `FlattenerLineMap`.
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/grammar/juniper/JuniperFlattener.java, line 125 at r3](https://reviewable.io/reviews/batfish/batfish/1707#-LFTm-Fk2ekBZcRrXMr_:-LFU1GlF3odsXd9ggKvg:bvuyhoi) ([raw file](https://github.com/batfish/batfish/blob/f1db7ccecbb8ec87d6df7e0b6f5451b4975eb320/projects/batfish/src/main/java/org/batfish/grammar/juniper/JuniperFlattener.java#L125)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Is this a regression in terms of crashing? Same goes for other throwing implementations.
</blockquote></details>

Just a placeholder until the next PR is complete; this method is not used yet so it won't affect crashing.

---

*[projects/batfish/src/main/java/org/batfish/job/ParseVendorConfigurationJob.java, line 208 at r3](https://reviewable.io/reviews/batfish/batfish/1707#-LFTmRfB-zarII3c6uHx:-LFU1Ql73S1FOs8meONr:babxnn) ([raw file](https://github.com/batfish/batfish/blob/f1db7ccecbb8ec87d6df7e0b6f5451b4975eb320/projects/batfish/src/main/java/org/batfish/job/ParseVendorConfigurationJob.java#L208)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Why do you declare a flattener here, but not above? If you are not reusing a variable, cleaner to not declare it. I.e, use earlier style consistently.
</blockquote></details>

Planning on reusing it, but not yet.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1707)*

**Comment by arifogel** [comment]
Review status: 10 of 12 files reviewed, 4 unresolved discussions (waiting on @arifogel, @anothermattbrown, and @dhalperi)

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/grammar/BatfishCombinedParser.java, line 138 at r3](https://reviewable.io/reviews/batfish/batfish/1707#-LFTfd6q0xntrrB5iksD:-LFUJmMa1kWA_e8IQwCN:b-nd9kv5) ([raw file](https://github.com/batfish/batfish/blob/f1db7ccecbb8ec87d6df7e0b6f5451b4975eb320/projects/batfish-common-protocol/src/main/java/org/batfish/grammar/BatfishCombinedParser.java#L138)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

Will this work since I'm dereferencing `_lineMap`? i.e. I don't think `firstNonNull(_lineMap.getOriginalLine(), line)` will work when `_lineMap` is null
</blockquote></details>

right never mind.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1707)*

**Comment by arifogel** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed, 1 unresolved discussion (waiting on @arifogel, @anothermattbrown, and @dhalperi)

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1707#-LFP5E4k66LWM2sI86Fz:-LFUK63jC2rZw6QKbEaC:b-t570b8) (no related file):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

Nope, just informational; those changes are coming soon
</blockquote></details>

Right but you are still blocking.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1707)*

**Comment by arifogel** [comment]
:lgtm:

---

Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown and @dhalperi)

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1707#-:-LFULGvm4fJr44wRUT2w:bnfp4nl)*

**Pull request merged**
