### PR TITLE
ARP support for reachability analysis

### PR DESCRIPTION
**Pull request by arifogel**

### CODE REVIEW

**Comment by anothermattbrown** [comment]
Reviewed 1 of 18 files at r1.
Review status: 1 of 16 files reviewed at latest revision, 9 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DataPlaneArpAnalysis.java, line 20 at r1](https://reviewable.io:443/reviews/batfish/batfish/1005#-L6Xl0eZyeTaPY2EIIov:-L6Xl0eZyeTaPY2EIIow:bi5f8ov) ([raw file](https://github.com/batfish/batfish/blob/82ce7f57a88cc3f50178ea45e27c186fddaee6f6/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DataPlaneArpAnalysis.java#L20)):*
> ```Java
> 
>   public DataPlaneArpAnalysis(
>       Map<String, Configuration> configurations, DataPlane dp, Topology topology) {
> ```

It appears we only use the ribs and fibs. It's more clear to just pass those in parameters rather than the entire dataplane.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DataPlaneArpAnalysis.java, line 25 at r1](https://reviewable.io:443/reviews/batfish/batfish/1005#-L6Xkp6eDfbRyTTI3pjI:-L6Xkp6eDfbRyTTI3pjJ:b5cyrh7) ([raw file](https://github.com/batfish/batfish/blob/82ce7f57a88cc3f50178ea45e27c186fddaee6f6/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DataPlaneArpAnalysis.java#L25)):*
> ```Java
>   }
> 
>   private Map<String, Map<String, IpAddressAcl>> computeArpReplies(
> ```

Add comment

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DataPlaneArpAnalysis.java, line 33 at r1](https://reviewable.io:443/reviews/batfish/batfish/1005#-L6XlhDtaBkAok3fM5zJ:-L6XlZThn0bC-W-Phryx:b-x6332b) ([raw file](https://github.com/batfish/batfish/blob/82ce7f57a88cc3f50178ea45e27c186fddaee6f6/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DataPlaneArpAnalysis.java#L33)):*
> ```Java
>             .collect(
>                 ImmutableMap.toImmutableMap(
>                     Entry::getKey,
> ```

// Node

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DataPlaneArpAnalysis.java, line 41 at r1](https://reviewable.io:443/reviews/batfish/batfish/1005#-L6XlgccmcrQnGzt0Vd_:-L6XlcUPnIulXuYmZrg5:bh9dvyn) ([raw file](https://github.com/batfish/batfish/blob/82ce7f57a88cc3f50178ea45e27c186fddaee6f6/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DataPlaneArpAnalysis.java#L41)):*
> ```Java
>                             .collect(
>                                 ImmutableMap.toImmutableMap(
>                                     Entry::getKey,
> ```

// Vrf

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DataPlaneArpAnalysis.java, line 49 at r1](https://reviewable.io:443/reviews/batfish/batfish/1005#-L6XloWHQLfVKGvgm8Rn:-L6XloWHQLfVKGvgm8Ro:b-x6332b) ([raw file](https://github.com/batfish/batfish/blob/82ce7f57a88cc3f50178ea45e27c186fddaee6f6/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DataPlaneArpAnalysis.java#L49)):*
> ```Java
>         .collect(
>             ImmutableMap.toImmutableMap(
>                 Entry::getKey,
> ```

// Node

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DataPlaneArpAnalysis.java, line 55 at r1](https://reviewable.io:443/reviews/batfish/batfish/1005#-L6Xm1rBOpjiuLHg3Jem:-L6Xm1rBOpjiuLHg3Jen:bkb0djw) ([raw file](https://github.com/batfish/batfish/blob/82ce7f57a88cc3f50178ea45e27c186fddaee6f6/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DataPlaneArpAnalysis.java#L55)):*
> ```Java
>                   Map<String, Fib> fibsByVrf = dp.getFibs().get(hostname);
>                   Map<String, IpSpace> routableIpsByVrf = routableIpsByNodeVrf.get(hostname);
>                   return ribsByNodeEntry
> ```

Factor out a method here.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DataPlaneArpAnalysis.java, line 66 at r1](https://reviewable.io:443/reviews/batfish/batfish/1005#-L6Xm_-d_C0qfPECm1Pw:-L6Xm_-d_C0qfPECm1Px:buaun4) ([raw file](https://github.com/batfish/batfish/blob/82ce7f57a88cc3f50178ea45e27c186fddaee6f6/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DataPlaneArpAnalysis.java#L66)):*
> ```Java
>                             Fib fib = fibsByVrf.get(vrf);
>                             Map<Prefix, IpSpace> matchingIpsByPrefix = rib.getMatchingIps();
>                             Map<String, ImmutableSet.Builder<IpSpace>> interfaceIps =
> ```

Factor the construction of the sets to a helper method. End by building, so the return is a map containing the ImmutableSets.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DataPlaneArpAnalysis.java, line 94 at r1](https://reviewable.io:443/reviews/batfish/batfish/1005#-L6XnOgnum4Okp4T88FO:-L6XnOgoGCpSG8uceiEm:b-t1pigw) ([raw file](https://github.com/batfish/batfish/blob/82ce7f57a88cc3f50178ea45e27c186fddaee6f6/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DataPlaneArpAnalysis.java#L94)):*
> ```Java
>                                       ImmutableList.Builder<IpAddressAclLine> lines =
>                                           ImmutableList.builder();
>                                       IpSpace.Builder ipsAssignedToThisInterface =
> ```

factor this out into a method that returns the built IpSpace

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DataPlaneArpAnalysis.java, line 132 at r1](https://reviewable.io:443/reviews/batfish/batfish/1005#-L6XnmEltSU19OEHB6iQ:-L6XnmEltSU19OEHB6iR:b-lie1hg) ([raw file](https://github.com/batfish/batfish/blob/82ce7f57a88cc3f50178ea45e27c186fddaee6f6/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DataPlaneArpAnalysis.java#L132)):*
> ```Java
>                                     });
>                           })
>                       .collect(ImmutableMap.toImmutableMap(Entry::getKey, Entry::getValue));
> ```

This isn't readable. It's too hard to figure out what the key and value are.  We shouldn't have to do dataflow analysis in our heads to decipher our code. Would be better just to use a builder and explicitly add the elements.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/1005)*

**Comment by anothermattbrown** [comment]
Reviewed 15 of 18 files at r1.
Review status: 15 of 16 files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/1005)*

**Comment by anothermattbrown** [comment]
Reviewed 2 of 18 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/1005)*

**Comment by arifogel** [comment]
Review status: 14 of 16 files reviewed at latest revision, 9 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DataPlaneArpAnalysis.java, line 25 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1005#-L6Xkp6eDfbRyTTI3pjI:-L6XygBu4h7b9_iSG8gX:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/82ce7f57a88cc3f50178ea45e27c186fddaee6f6/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DataPlaneArpAnalysis.java#L25)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

Add comment
</blockquote></details>

Done.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DataPlaneArpAnalysis.java, line 33 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1005#-L6XlhDtaBkAok3fM5zJ:-L6Y3wip8Zya4H07olkq:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/82ce7f57a88cc3f50178ea45e27c186fddaee6f6/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DataPlaneArpAnalysis.java#L33)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

// Node
</blockquote></details>

Done.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DataPlaneArpAnalysis.java, line 41 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1005#-L6XlgccmcrQnGzt0Vd_:-L6Y3x-7CNm9LrGrTAK2:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/82ce7f57a88cc3f50178ea45e27c186fddaee6f6/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DataPlaneArpAnalysis.java#L41)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

// Vrf
</blockquote></details>

Done.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DataPlaneArpAnalysis.java, line 49 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1005#-L6XloWHQLfVKGvgm8Rn:-L6Y3xgGEvPWFaI7mCMw:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/82ce7f57a88cc3f50178ea45e27c186fddaee6f6/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DataPlaneArpAnalysis.java#L49)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

// Node
</blockquote></details>

Done.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DataPlaneArpAnalysis.java, line 55 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1005#-L6Xm1rBOpjiuLHg3Jem:-L6cPLcM2zTogTkSIJd2:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/82ce7f57a88cc3f50178ea45e27c186fddaee6f6/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DataPlaneArpAnalysis.java#L55)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

Factor out a method here.
</blockquote></details>

Done.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DataPlaneArpAnalysis.java, line 66 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1005#-L6Xm_-d_C0qfPECm1Pw:-L6cQO0F9d_oscUEbkX2:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/82ce7f57a88cc3f50178ea45e27c186fddaee6f6/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DataPlaneArpAnalysis.java#L66)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

Factor the construction of the sets to a helper method. End by building, so the return is a map containing the ImmutableSets.
</blockquote></details>

Done.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DataPlaneArpAnalysis.java, line 94 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1005#-L6XnOgnum4Okp4T88FO:-L6cRQDwD1lm2W6MSXJT:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/82ce7f57a88cc3f50178ea45e27c186fddaee6f6/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DataPlaneArpAnalysis.java#L94)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

factor this out into a method that returns the built IpSpace
</blockquote></details>

Done.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DataPlaneArpAnalysis.java, line 132 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1005#-L6XnmEltSU19OEHB6iQ:-L6cRRPT4aH5boj07GoM:begw0lt) ([raw file](https://github.com/batfish/batfish/blob/82ce7f57a88cc3f50178ea45e27c186fddaee6f6/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DataPlaneArpAnalysis.java#L132)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

This isn't readable. It's too hard to figure out what the key and value are.  We shouldn't have to do dataflow analysis in our heads to decipher our code. Would be better just to use a builder and explicitly add the elements.
</blockquote></details>

How about now?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1005)*

**Comment by arifogel** [comment]
Review status: 10 of 17 files reviewed at latest revision, 9 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DataPlaneArpAnalysis.java, line 20 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1005#-L6Xl0eZyeTaPY2EIIov:-L6coBt85foWlLpbDhwD:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/82ce7f57a88cc3f50178ea45e27c186fddaee6f6/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DataPlaneArpAnalysis.java#L20)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

It appears we only use the ribs and fibs. It's more clear to just pass those in parameters rather than the entire dataplane.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1005)*

**Comment by anothermattbrown** [comment]
Reviewed 1 of 18 files at r1, 1 of 1 files at r2, 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DataPlaneArpAnalysis.java, line 132 at r1](https://reviewable.io:443/reviews/batfish/batfish/1005#-L6XnmEltSU19OEHB6iQ:-L6ftYebEE4ARA-ygyOM:b-p36ui8) ([raw file](https://github.com/batfish/batfish/blob/82ce7f57a88cc3f50178ea45e27c186fddaee6f6/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DataPlaneArpAnalysis.java#L132)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

How about now?
</blockquote></details>

lgtm thanks

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DataPlaneArpAnalysis.java, line 266 at r3](https://reviewable.io:443/reviews/batfish/batfish/1005#-L6ftPj3y1DNSVR55TpQ:-L6ftPj3y1DNSVR55TpR:b-n6kajn) ([raw file](https://github.com/batfish/batfish/blob/bb859f0e30646c8e82d07df9035a9ec7a06488e6/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DataPlaneArpAnalysis.java#L266)):*
> ```Java
>   private Map<String, Map<String, IpSpace>> computeRoutableIpsByNodeVrf(
>       SortedMap<String, SortedMap<String, GenericRib<AbstractRoute>>> ribs) {
>     Map<String, Map<String, IpSpace>> routableIpsByNodeVrf =
> ```

just return here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/1005)*

**Comment by arifogel** [comment]
Review status: 16 of 17 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DataPlaneArpAnalysis.java, line 266 at r3](https://beta.reviewable.io/reviews/batfish/batfish/1005#-L6ftPj3y1DNSVR55TpQ:-L6j9-D2Cp41z9tDp-lo:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/1e59ac50fb5b3c3e93a2d87b6c048a49d39774b0/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DataPlaneArpAnalysis.java#L266)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

just return here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1005)*

**Comment by anothermattbrown** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1005#-:-L6j_6z4EuQmiFqiBk-S:bnfp4nl)*

**Pull request merged**
