### PR TITLE
Juniper firewall support

### PR DESCRIPTION
**Pull request by sfraint**
Changed vendor model and to-vendor-independent-conversion for Juniper devices to support firewall structures:
* Firewall filter conversion updated to allow source-interface matching
* Interface conversion updated to support more complex outgoing filters (combining security policy with existing outgoing ACL)
* Zone conversion updated to create security policy ACLs
* Added tests and configs for grammar tests
* Added matchers

### CODE REVIEW

**Comment by sfraint** [comment]
Review status: 0 of 20 files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://beta.reviewable.io/reviews/batfish/batfish/1175#-LAG2hgv9gmZ8gSdzwuf:-LAG2hgv9gmZ8gSdzwug:bxxtog) (no related file):*
Need to re-enable compression (blocking comment)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1175)*

**Comment by arifogel** [comment]
Reviewed 17 of 20 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/batfish/batfish/1175#-LAGPyQ83m8qvZ2sGvLD:-LAGPyQ83m8qvZ2sGvLE:b-h8ysle) (no related file):*
Can you add some tests that particular flows are permitted/denied?

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/HeaderSpaceMatchersImpl.java, line 37 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1175#-LAGN4e52itIzGFd2r5r:-LAGN4e64usxsbkE6U-D:b4lyr4k) ([raw file](https://github.com/batfish/batfish/blob/36962a5552a7684c1931af6fbb1046402ee8e3a9/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/HeaderSpaceMatchersImpl.java#L37)):*
> ```Java
>   static class HasState extends FeatureMatcher<HeaderSpace, SortedSet<State>> {
>     HasState(@Nonnull Matcher<? super SortedSet<State>> subMatcher) {
>       super(subMatcher, "A HeaderSpace with state:", "state");
> ```

states plural. Please change the name of the class (and calling method) as well.

---

*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 2246 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1175#-LAGNWWI00IXAiimz1hr:-LAGNWWI00IXAiimz1hs:bflxebh) ([raw file](https://github.com/batfish/batfish/blob/36962a5552a7684c1931af6fbb1046402ee8e3a9/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L2246)):*
> ```Java
>       }
> 
>       // Need to keep track of the from-zone for this filter to apply srcInterface filter to the
> ```

Please use following comment style for long comments to save from merciless autoformatter/sorter:
```
/*
 * first line of comment
 * second line of comment
 */
```
Applies in multiple places.

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/FirewallFilter.java, line 42 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1175#-LAGNyCD6SekRK18fQ9b:-LAGNyCD6SekRK18fQ9c:bl418ka) ([raw file](https://github.com/batfish/batfish/blob/36962a5552a7684c1931af6fbb1046402ee8e3a9/projects/batfish/src/main/java/org/batfish/representation/juniper/FirewallFilter.java#L42)):*
> ```Java
>   }
> 
>   public Set<String> getFromZones() {
> ```

How does this work exactly? Why is the reference here? Can a single filter apply to multiple from-zones?

---

*[projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java, line 437 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1175#-LAGPVPi1AY1PBcHAryj:-LAGPVPi1AY1PBcHAryk:brb4vaa) ([raw file](https://github.com/batfish/batfish/blob/36962a5552a7684c1931af6fbb1046402ee8e3a9/projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java#L437)):*
> ```Java
>     assertThat(
>         aclGlobalPolicyLine,
>         hasMatchCondition(equalTo(new MatchHeaderSpace(HeaderSpace.builder().build()))));
> ```

If it permits all traffic, shouldn't it just use `TrueExpr.INSTANCE`?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1175)*

**Comment by sfraint** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/HeaderSpaceMatchersImpl.java, line 37 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1175#-LAGN4e52itIzGFd2r5r:-LAJZtBo6BBXg4GHTsFe:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/36962a5552a7684c1931af6fbb1046402ee8e3a9/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/HeaderSpaceMatchersImpl.java#L37)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

states plural. Please change the name of the class (and calling method) as well.
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 2246 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1175#-LAGNWWI00IXAiimz1hr:-LAJbOq0EsquLkTwdEzj:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/36962a5552a7684c1931af6fbb1046402ee8e3a9/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L2246)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Please use following comment style for long comments to save from merciless autoformatter/sorter:
```
/*
 * first line of comment
 * second line of comment
 */
```
Applies in multiple places.
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/FirewallFilter.java, line 42 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1175#-LAGNyCD6SekRK18fQ9b:-LAJXnXa0Q6wy3IVXjX2:b-wu932c) ([raw file](https://github.com/batfish/batfish/blob/36962a5552a7684c1931af6fbb1046402ee8e3a9/projects/batfish/src/main/java/org/batfish/representation/juniper/FirewallFilter.java#L42)):*
> How does this work exactly? Why is the reference here?

From-zone is saved with the security policies (firewallFilter) so it can be decomposed into source interface matches for the resulting ACL in `toIpAccessList`.

> Can a single filter apply to multiple from-zones?

I was thinking it could, but I don't immediately see how that would be possible on SRX (maybe it was just in PAN).

---

*[projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java, line 437 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1175#-LAGPVPi1AY1PBcHAryj:-LAJaZDQ757yf4gKyHe0:bdu0e8b) ([raw file](https://github.com/batfish/batfish/blob/36962a5552a7684c1931af6fbb1046402ee8e3a9/projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java#L437)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

If it permits all traffic, shouldn't it just use `TrueExpr.INSTANCE`?
</blockquote></details>

That is possible, but I don't think we're currently analyzing and simplifying config defined ACLs.
In this case, we just happen to have a global policy defined with no constraint.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1175)*

**Comment by sfraint** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://beta.reviewable.io/reviews/batfish/batfish/1175#-LAGPyQ83m8qvZ2sGvLD:-LAK8P0bDz-hr6EdCJJe:b-896fix) (no related file):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Can you add some tests that particular flows are permitted/denied?
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/FirewallFilter.java, line 42 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1175#-LAGNyCD6SekRK18fQ9b:-LAK7ias9M3zeq8GgpXU:benxl2w) ([raw file](https://github.com/batfish/batfish/blob/36962a5552a7684c1931af6fbb1046402ee8e3a9/projects/batfish/src/main/java/org/batfish/representation/juniper/FirewallFilter.java#L42)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Recall that this is a Juniper-specific class. The representation here should closely mirror the Juniper configuration. I'll leave it up to you what to do with this. Whatever you decide, you definitely need to add comments. I still don't understand how this gets translated.
</blockquote></details>

Updated.
Also, I updated the comments where this is used (in `toIpAccessList`)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1175)*

**Comment by anothermattbrown** [comment]
Reviewed 11 of 20 files at r1, 1 of 3 files at r2.
Review status: 13 of 22 files reviewed at latest revision, 3 unresolved discussions.

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/AndMatchExprMatchersImpl.java, line 10 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1175#-LAG_Yj-C_WLrllYeLzN:-LAG_Yj-C_WLrllYeLzO:b-7bwo5v) ([raw file](https://github.com/batfish/batfish/blob/36962a5552a7684c1931af6fbb1046402ee8e3a9/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/AndMatchExprMatchersImpl.java#L10)):*
> ```Java
> import org.hamcrest.Matcher;
> 
> public class AndMatchExprMatchersImpl {
> ```

Wxxhy not put these in `AndMatchExprMatchers`? Why a separate class?

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/InterfaceMatchersImpl.java, line 83 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1175#-LAG_r9SBdPzEnYLbj8y:-LAG_r9SBdPzEnYLbj8z:br6f14t) ([raw file](https://github.com/batfish/batfish/blob/36962a5552a7684c1931af6fbb1046402ee8e3a9/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/InterfaceMatchersImpl.java#L83)):*
> ```Java
>   static final class HasZoneName extends FeatureMatcher<Interface, String> {
>     HasZoneName(@Nonnull Matcher<? super String> subMatcher) {
>       super(subMatcher, "an interface with zoneName", "zoneName");
> ```

the convention seems to be to use the class name (rather than the english word) and a colon, i.e. "an Interface with zoneName:"

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1175)*

**Comment by sfraint** [comment]
Review status: 13 of 22 files reviewed at latest revision, 5 unresolved discussions.

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/InterfaceMatchersImpl.java, line 83 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1175#-LAG_r9SBdPzEnYLbj8y:-LAKXjng6DzoOYHXvhA2:b-8iw09a) ([raw file](https://github.com/batfish/batfish/blob/36962a5552a7684c1931af6fbb1046402ee8e3a9/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/InterfaceMatchersImpl.java#L83)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

the convention seems to be to use the class name (rather than the english word) and a colon, i.e. "an Interface with zoneName:"
</blockquote></details>

Sounds good.  Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1175)*

**Comment by arifogel** [comment]
Reviewed 10 of 10 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/AndMatchExprMatchersImpl.java, line 10 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1175#-LAG_Yj-C_WLrllYeLzN:-LAKaTzc9hTKYCVw_1ZU:b9s6cfm) ([raw file](https://github.com/batfish/batfish/blob/36962a5552a7684c1931af6fbb1046402ee8e3a9/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/AndMatchExprMatchersImpl.java#L10)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

Wxxhy not put these in `AndMatchExprMatchers`? Why a separate class?
</blockquote></details>

This is the style we have been using. It corresponds to the style used by hamcrest Matchers. I'm sure there are good arguments either way, but I humbly suggest we don't litigate this right now.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1175)*

**Comment by anothermattbrown** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/AndMatchExprMatchersImpl.java, line 10 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1175#-LAG_Yj-C_WLrllYeLzN:-LAKvAgP9AtXT8M2WN7S:bh6l7u7) ([raw file](https://github.com/batfish/batfish/blob/36962a5552a7684c1931af6fbb1046402ee8e3a9/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/AndMatchExprMatchersImpl.java#L10)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

This is the style we have been using. It corresponds to the style used by hamcrest Matchers. I'm sure there are good arguments either way, but I humbly suggest we don't litigate this right now.
</blockquote></details>

Wasn't aware of the convention. This works for me.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1175)*

**Comment by sfraint** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://beta.reviewable.io/reviews/batfish/batfish/1175#-LAG2hgv9gmZ8gSdzwuf:-LAKvZET2qGlIaKQVGnj:bxjzx82) (no related file):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

Need to re-enable compression (blocking comment)
</blockquote></details>

Going to leave disabled for now.  Can reenable when BDD changes are complete.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1175)*

**Pull request merged**
