### PR TITLE
XR: parse and extract `l2transport` interfaces

### PR DESCRIPTION
**Pull request by sfraint**
Parse and extract interface `l2transport` and related properties; these can be used in conjunction with `bridge-domain`s (see [docs](https://www.cisco.com/c/en/us/td/docs/routers/asr9000/software/asr9k_r6-1/interfaces/configuration/guide/b-interfaces-cg-asr9k-61x/b-interfaces-cg-asr9k-61x_chapter_0111.html) and [related PR](https://github.com/batfish/batfish/pull/7106)).

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7107)* status: all files reviewed, 2 unresolved discussions (waiting on @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java, line 2746 at r1](https://reviewable.io/reviews/batfish/batfish/7107#-Md4VslL4bbbHmVYP70Q:-Md4VslL4bbbHmVYP70R:b3bptw) ([raw file](https://github.com/batfish/batfish/blob/60522fa7f3188d6bc04592fc529dcb8ed89896e9/projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java#L2746)):*
> ```Java
>     } else {
>       Interface iface = addInterface(namePrefix.toString(), ctx.iname, true);
>       iface.setL2transport(ctx.L2TRANSPORT() != null);
> ```

does this happen on re-entry?
___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java, line 4278 at r1](https://reviewable.io/reviews/batfish/batfish/7107#-Md4VpMr-Xb5oWRZrGkB:-Md4VpMs1rEm6yrHowHa:bprpuaf) ([raw file](https://github.com/batfish/batfish/blob/60522fa7f3188d6bc04592fc529dcb8ed89896e9/projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java#L4278)):*
> ```Java
>   @Override
>   public void exitIf_rewrite_ingress_tag(If_rewrite_ingress_tagContext ctx) {
>     Optional<TagRewritePolicy> policy = toTagRewritePolicy(ctx.ifrit_policy());
> ```

is this command accepted in non-l2transport mode?

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7107)* status: all files reviewed, 2 unresolved discussions (waiting on @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java, line 2746 at r1](https://reviewable.io/reviews/batfish/batfish/7107#-Md4VslL4bbbHmVYP70Q:-Md4WP_BBEi-LA6YlqAW:b-uxa3a6) ([raw file](https://github.com/batfish/batfish/blob/60522fa7f3188d6bc04592fc529dcb8ed89896e9/projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java#L2746)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

does this happen on re-entry?
</blockquote></details>

apparently not, fixed
___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java, line 4278 at r1](https://reviewable.io/reviews/batfish/batfish/7107#-Md4VpMr-Xb5oWRZrGkB:-Md4WHjcBd8ouPqpUmtY:b-co70cp) ([raw file](https://github.com/batfish/batfish/blob/60522fa7f3188d6bc04592fc529dcb8ed89896e9/projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java#L4278)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

is this command accepted in non-l2transport mode?
</blockquote></details>

no, we can reject this in that case

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7107)* status: 5 of 9 files reviewed, 2 unresolved discussions (waiting on @dhalperi and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java, line 2746 at r1](https://reviewable.io/reviews/batfish/batfish/7107#-Md4VslL4bbbHmVYP70Q:-Md4_A5aCRlgIF1K_Ot2:b-75ic66) ([raw file](https://github.com/batfish/batfish/blob/60522fa7f3188d6bc04592fc529dcb8ed89896e9/projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java#L2746)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

apparently not, fixed
</blockquote></details>

and you might not be able to change an existing iface into l2transport mode, confirming and I'll add a check for that too

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7107)* status: 5 of 9 files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java, line 2746 at r1](https://reviewable.io/reviews/batfish/batfish/7107#-Md4VslL4bbbHmVYP70Q:-Md4d5zw16wEzHLz43mT:b-7zti8) ([raw file](https://github.com/batfish/batfish/blob/60522fa7f3188d6bc04592fc529dcb8ed89896e9/projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java#L2746)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

and you might not be able to change an existing iface into l2transport mode, confirming and I'll add a check for that too
</blockquote></details>

like we discussed offline:
the device won't commit changes if you try to configure L2 mode when L3 config already exists `All changes made have been reverted ... Cannot configure an interface as L2 when L3 configuration exists` - not going to worry about handling this yet

**Review by dhalperi — COMMENTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7107)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

**Pull request merged**
