### PR TITLE
use z3 4.6.0

### PR DESCRIPTION
**Pull request by arifogel**
This change is [Reviewable](https://reviewable.io/reviews/batfish/batfish/816)

### CODE REVIEW

**Comment by dhalperi** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tools/install_z3_ubuntu_16.04.sh, line 1 at r1](https://reviewable.io:443/reviews/batfish/batfish/816#-L1xiozkGNQnU7lzyH_G:-L1xiozlSz-Em2sA-LKH:b-ueebmx) ([raw file](https://github.com/batfish/batfish/blob/b0b93f14fb609138ff142426703529f7ccc2f9e6/tools/install_z3_ubuntu_16.04.sh#L1)):*
> ```Shell
> #!/usr/bin/env bash
> ```

Confirmed via manual diff that this file and `install_z3_ubuntu_14.04` are the same minus 16/14.

Optionally, extract core functionality to a common file and have these as thing wrappers for the common file?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/816)*

**Comment by dhalperi** [comment]
*[a discussion](https://reviewable.io:443/reviews/batfish/batfish/816#-L1xjI_lhyKVjX3cprRk:-L1xjI_lhyKVjX3cprRl:b-we9crk) (no related file):*
Can you describe what additional vetting you did other than a version bump? The travis tests don't take a significantly different time to run, but perhaps that's expected since all inputs are relatively small.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/816)*

**Comment by arifogel** [comment]
Review status: 5 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/install_z3_ubuntu_16.04.sh, line 1 at r1](https://reviewable.io:443/reviews/batfish/batfish/816#-L1xiozkGNQnU7lzyH_G:-L1xjbiK-xqNcgNpQ6sV:btrr5w5) ([raw file](https://github.com/batfish/batfish/blob/b0b93f14fb609138ff142426703529f7ccc2f9e6/tools/install_z3_ubuntu_16.04.sh#L1)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Confirmed via manual diff that this file and `install_z3_ubuntu_14.04` are the same minus 16/14.

Optionally, extract core functionality to a common file and have these as thing wrappers for the common file?
</blockquote></details>

Didn't go the wrapper route - I just ported over the Ubuntu version auto-detection from `package_ubuntu.sh` into a common file, and made a single installer file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/816)*

**Comment by arifogel** [comment]
Review status: 5 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/batfish/batfish/816#-L1xjI_lhyKVjX3cprRk:-L1xsZlKOJOcsPqEAySV:b6q9idh) (no related file):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Can you describe what additional vetting you did other than a version bump? The travis tests don't take a significantly different time to run, but perhaps that's expected since all inputs are relatively small.
</blockquote></details>

I didn't do any special vetting other than watching the travis tests. I am concerned at the current failure. Perhaps the failing test is relying on undefined behavior that was previously thought to be deterministic? Otherwise we could be looking at either a bug OR a bug fix.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/816)*

**Comment by dhalperi** [comment]
*[tools/ubuntu_common.sh, line 4 at r2](https://reviewable.io:443/reviews/batfish/batfish/816#-L21LB-sseVYaoQ-Zgy2:-L21LB-sseVYaoQ-Zgy3:b90rex0) ([raw file](https://github.com/batfish/batfish/blob/e2a51f7347bb49c21b9b4eb6e6008598a2a766a6/tools/ubuntu_common.sh#L4)):*
> ```Shell
> 
> ubuntu_version() {
>    head -n1 /etc/issue | cut -f2 -d' ' | cut -f1,2 -d'.'
> ```

The `lsb_release` seems more tailored to this: either `lsb_release` command or `/etc/lsb-release`?

```
root@900c07598526:/# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/816)*

**Comment by dhalperi** [comment]
Reviewed 6 of 7 files at r2.
Review status: 11 of 12 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/816)*

**Comment by arifogel** [comment]
Review status: 8 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/ubuntu_common.sh, line 4 at r2](https://reviewable.io:443/reviews/batfish/batfish/816#-L21LB-sseVYaoQ-Zgy2:-L21mhQ1t382yNxwc-zY:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/e2a51f7347bb49c21b9b4eb6e6008598a2a766a6/tools/ubuntu_common.sh#L4)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

The `lsb_release` seems more tailored to this: either `lsb_release` command or `/etc/lsb-release`?

```
root@900c07598526:/# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/816)*

**Comment by dhalperi** [comment]
Reviewed 3 of 4 files at r3.
Review status: 10 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/java/org/batfish/symbolic/answers/SmtDeterminismAnswerElement.java, line 58 at r3](https://reviewable.io:443/reviews/batfish/batfish/816#-L22DE0CcMCfkEjO0OyC:-L22DE0CcMCfkEjO0OyD:b-pduq) ([raw file](https://github.com/batfish/batfish/blob/37521183b9080e04e1f9e9ce8198fca012a77e26/projects/batfish/src/main/java/org/batfish/symbolic/answers/SmtDeterminismAnswerElement.java#L58)):*
> ```Java
> 
>   @JsonIgnore
>   public VerificationResult getResult() {
> ```

why does this not need a ref change?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/816)*

**Comment by arifogel** [comment]
Review status: 10 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/java/org/batfish/symbolic/answers/SmtDeterminismAnswerElement.java, line 58 at r3](https://reviewable.io:443/reviews/batfish/batfish/816#-L22DE0CcMCfkEjO0OyC:-L22eLHjbbyguCLiI5Q7:bs6r7ac) ([raw file](https://github.com/batfish/batfish/blob/37521183b9080e04e1f9e9ce8198fca012a77e26/projects/batfish/src/main/java/org/batfish/symbolic/answers/SmtDeterminismAnswerElement.java#L58)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

why does this not need a ref change?
</blockquote></details>

Since there is no setter, the old value never makes it into the object during deserialization. During reserialization, the value is not added due to the `@JsonIgnore` annotation. If you want to argue our refs should still look correct contemporaneously, then we have to fix LOTS of other refs too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/816)*

**Comment by dhalperi** [comment]
Reviewed 1 of 7 files at r2, 1 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/816)*

**Pull request merged**
