### PR TITLE
FRR: bgp to ospf redist

### PR DESCRIPTION
**Pull request by kylehoferamzn**
NOTE:  There are a few related fixes from OSPF to BGP redistribution PR that needs to be added here.  I will do that once we merge that PR - submitting this one so we can review them in parallel and make sure that we fix any common problems.

### CODE REVIEW

**Review by kylehoferamzn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6087)* status: all files reviewed, 8 unresolved discussions (waiting on @kylehoferamzn and @progwriter)

___
*[projects/batfish/src/main/java/org/batfish/representation/cumulus/OspfProcess.java, line 70 at r2](https://reviewable.io/reviews/batfish/batfish/6087#-MG653Oh1fWyLMYPhTRs:-MGFKtOy4rjQNFjUbH2E:b79cbim) ([raw file](https://github.com/batfish/batfish/blob/248742920f22934dce05ae4180c5bc6e3abe9659/projects/batfish/src/main/java/org/batfish/representation/cumulus/OspfProcess.java#L70)):*
<details><summary><i>Previously, kylehoferamzn wrote…</i></summary><blockquote>

REF: http://docs.frrouting.org/en/latest/ospfd.html?highlight=ospf%20redistribute#redistribution

It's configurable at the command/process level - "redistribute bgp metric-type 2 metric 10000 route-map BLAH"
</blockquote></details>

Okay looking at this more I think what you're getting at, probably process level is not appropriate because we can have different directives per command.  Since it functions at a per-command level I'll need to either associate it with the redistribution policy (this is how it was coded originally, and why we created an OSPF specific class) - NXOS doesn't seem to handle this case at all, maybe I just ignore it for now and remove support from the parser?

**Review by kylehoferamzn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6087)* status: all files reviewed, 8 unresolved discussions (waiting on @progwriter)

___
*[projects/batfish/src/main/java/org/batfish/representation/cumulus/OspfRedistributionPolicy.java, line 6 at r2](https://reviewable.io/reviews/batfish/batfish/6087#-MG63ngyDLMkaHljDr5-:-MGFQYPtAG3-KG2Gj2Fh:bicz26w) ([raw file](https://github.com/batfish/batfish/blob/248742920f22934dce05ae4180c5bc6e3abe9659/projects/batfish/src/main/java/org/batfish/representation/cumulus/OspfRedistributionPolicy.java#L6)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

make final, javadoc
</blockquote></details>

Just ended up getting rid of OspfRedistributionPolicy - we kind of don't need it until we start supporting type/cost parameters in the command.
___
*[projects/batfish/src/main/java/org/batfish/representation/cumulus/RedistributionPolicy.java, line 8 at r2](https://reviewable.io/reviews/batfish/batfish/6087#-MG64SFcCz9cI9xCfhWH:-MGFQjJPE73dUrLqKa0P:bc9geoa) ([raw file](https://github.com/batfish/batfish/blob/248742920f22934dce05ae4180c5bc6e3abe9659/projects/batfish/src/main/java/org/batfish/representation/cumulus/RedistributionPolicy.java#L8)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

I don't think this is the pattern we want to setup here. [NXOS has a much better approach](https://github.com/batfish/batfish/blob/master/projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/RedistributionPolicy.java) where:
* routing protocol that is stored is VS, and redist. policies are keyed on VS protocol. 
* there is no destination protocol, that's just implied by the process that references the redistribution policy. 
* then only conversion touches VI_PROTOCOL_MAP, your extraction code, gets significantly simpler.
</blockquote></details>

Fair play, Re-designed this.  We will want to go back and fix BGP Redist to match.
___
*[projects/batfish/src/main/java/org/batfish/representation/cumulus/RedistributionPolicy.java, line 16 at r2](https://reviewable.io/reviews/batfish/batfish/6087#-MG64Lkv3rhEGmhRDhua:-MGFQoKF-8Zg7OT3Yh4-:bss4a2b) ([raw file](https://github.com/batfish/batfish/blob/248742920f22934dce05ae4180c5bc6e3abe9659/projects/batfish/src/main/java/org/batfish/representation/cumulus/RedistributionPolicy.java#L16)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

what are special attributes? they seem completely unused
</blockquote></details>

Removed.
___
*[projects/batfish/src/test/java/org/batfish/representation/cumulus/CumulusConversionsTest.java, line 1189 at r2](https://reviewable.io/reviews/batfish/batfish/6087#-MG66E5QBFzswIHh1Ut4:-MGFR-5v2W1R_X94uH7n:b-e9voo1) ([raw file](https://github.com/batfish/batfish/blob/248742920f22934dce05ae4180c5bc6e3abe9659/projects/batfish/src/test/java/org/batfish/representation/cumulus/CumulusConversionsTest.java#L1189)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

tests name needs to be more descriptive, also suggest javadocing the tests w/ what's being tested/expected
</blockquote></details>

Test is essentially voided by the change to where we are storing default metrics.

**Review by progwriter — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6087)* status: 7 of 13 files reviewed, 7 unresolved discussions (waiting on @kylehoferamzn and @progwriter)

___
*[projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConversions.java, line 1280 at r2](https://reviewable.io/reviews/batfish/batfish/6087#-MG65_1s56f9y4up5xhU:-MGFXNAK0GHGM2XLJxTQ:b-x26ak7) ([raw file](https://github.com/batfish/batfish/blob/248742920f22934dce05ae4180c5bc6e3abe9659/projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConversions.java#L1280)):*
<details><summary><i>Previously, kylehoferamzn wrote…</i></summary><blockquote>

1) I have it as a top-level policy up-front in order to ensure that it takes effect prior to the route-map.  My worry is that if I apply it as a statement, it will happen after the route-map, which is not the behavior we want.  In short, the default metric/type commands are used as a "catch all" - this means they need to happen up front and allow the route-map to override.  Let me know if my thinking is wrong or if there is some better way to handle this case.

2) Yeah good call.
</blockquote></details>

re 1: statements are always executed in order. so that you can always execute metric/type statements followed by the `if callExpr(routemap) then accept else reject`. Am I missing something?

in other words structure of the export policy as follows:

```
if (export conditions) {
  setMetric
  setType
  if (callExpr(routeMap)) {
    accept
  } else {
    reject
  }
} else {
  reject
}
```

where `export conditions` are the `matchProtocol` (at least at this time). 
obviously `if callExpr(routeMap)` only needs to be inserted if the route map actually exists 
___
*[projects/batfish/src/main/java/org/batfish/representation/cumulus/OspfProcess.java, line 70 at r2](https://reviewable.io/reviews/batfish/batfish/6087#-MG653Oh1fWyLMYPhTRs:-MGFYhgb5w93CMG-APJE:b-74fwtp) ([raw file](https://github.com/batfish/batfish/blob/248742920f22934dce05ae4180c5bc6e3abe9659/projects/batfish/src/main/java/org/batfish/representation/cumulus/OspfProcess.java#L70)):*
> I'll need to either associate it with the redistribution policy
yes, absolutely. which is why I was suggesting creating ospf redistr. policy in extractor, and keeping only VS information in there. All extraction is just some puts.

to be fair having RedistrPolicy inheritance is fine (imo) if the parameters per protocol are different. `srcProtocol` and `routeMap` will be common to all.

**Review by kylehoferamzn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6087)* status: 7 of 13 files reviewed, 7 unresolved discussions (waiting on @progwriter)

___
*[projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConversions.java, line 1280 at r2](https://reviewable.io/reviews/batfish/batfish/6087#-MG65_1s56f9y4up5xhU:-MGL-rzZ7BLf8CxMEUPE:b67qutz) ([raw file](https://github.com/batfish/batfish/blob/248742920f22934dce05ae4180c5bc6e3abe9659/projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConversions.java#L1280)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

re 1: statements are always executed in order. so that you can always execute metric/type statements followed by the `if callExpr(routemap) then accept else reject`. Am I missing something?

in other words structure of the export policy as follows:

```
if (export conditions) {
  setMetric
  setType
  if (callExpr(routeMap)) {
    accept
  } else {
    reject
  }
} else {
  reject
}
```

where `export conditions` are the `matchProtocol` (at least at this time). 
obviously `if callExpr(routeMap)` only needs to be inserted if the route map actually exists 
</blockquote></details>

I *think* I've got it set up to work this way now, take a look.
___
*[projects/batfish/src/main/java/org/batfish/representation/cumulus/OspfProcess.java, line 70 at r2](https://reviewable.io/reviews/batfish/batfish/6087#-MG653Oh1fWyLMYPhTRs:-MGL-bog0jQjWWjq5zIK:b-ln8apq) ([raw file](https://github.com/batfish/batfish/blob/248742920f22934dce05ae4180c5bc6e3abe9659/projects/batfish/src/main/java/org/batfish/representation/cumulus/OspfProcess.java#L70)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

> I'll need to either associate it with the redistribution policy
yes, absolutely. which is why I was suggesting creating ospf redistr. policy in extractor, and keeping only VS information in there. All extraction is just some puts.

to be fair having RedistrPolicy inheritance is fine (imo) if the parameters per protocol are different. `srcProtocol` and `routeMap` will be common to all.
</blockquote></details>

Given the scope of what I'm working on right now, its probably easier if I just punt on those bits, so just left it with RedistributionPolicy for now.

**Review by progwriter — COMMENTED** [review]
> Reviewed 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6087)* status: all files reviewed, 1 unresolved discussion (waiting on @kylehoferamzn)

___
*[projects/batfish/src/main/java/org/batfish/grammar/cumulus_frr/CumulusFrrConfigurationBuilder.java, line 715 at r3](https://reviewable.io/reviews/batfish/batfish/6087#-MGLSZn66-n8eNtXIKcG:-MGLSZn66-n8eNtXIKcH:bhvna12) ([raw file](https://github.com/batfish/batfish/blob/ec6d3b5e6ccf38d91ae764a5e074adad14ac457c/projects/batfish/src/main/java/org/batfish/grammar/cumulus_frr/CumulusFrrConfigurationBuilder.java#L715)):*
> ```Java
>     }
> 
>     //    BgpRedistributionPolicy oldRedistributionPolicy;
> ```

please remove stale comments
___
*[projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConversions.java, line 1280 at r2](https://reviewable.io/reviews/batfish/batfish/6087#-MG65_1s56f9y4up5xhU:-MGM6Tx66JPUDGXSLyfg:b-rdo8ii) ([raw file](https://github.com/batfish/batfish/blob/248742920f22934dce05ae4180c5bc6e3abe9659/projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConversions.java#L1280)):*
<details><summary><i>Previously, kylehoferamzn wrote…</i></summary><blockquote>

I *think* I've got it set up to work this way now, take a look.
</blockquote></details>

yeah, that's what I was thinking of, thanks!

**Review by progwriter — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6087)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
