### PR TITLE
Improvements and tests for DB authorizer

### PR DESCRIPTION
**Pull request by progwriter**
- Tests for DB authorizer
- Small style/constructor changes for easier testing
- Less reliance of MySQL-specific syntax

---
This change is [Reviewable](https://reviewable.io/reviews/batfish/batfish/703)

### CODE REVIEW

**Comment by dhalperi** [comment]
Really nice improvements, left a bunch of comments around – let me know which you want to address now before I finish review. (Since hopefully if you make some changes, have to review a lot less code ;p).

---

Reviewed 3 of 5 files at r1.
Review status: 3 of 5 files reviewed at latest revision, 8 unresolved discussions.

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/authorizer/DbAuthorizer.java, line 22 at r1](https://reviewable.io:443/reviews/batfish/batfish/703#-L-gyY__-oxeJRBhIz0R:-L-gyY__-oxeJRBhIz0S:b-o06fy9) ([raw file](https://github.com/batfish/batfish/blob/d6ef1f453064b78de67b102e8aaf718aacaad8c9/projects/coordinator/src/main/java/org/batfish/coordinator/authorizer/DbAuthorizer.java#L22)):*
> ```Java
> import org.batfish.coordinator.config.Settings;
> 
> /** And {@link Authorizer} backed by an SQL database */
> ```

typo: s/And/An/

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/authorizer/DbAuthorizer.java, line 37 at r1](https://reviewable.io:443/reviews/batfish/batfish/703#-L-h2MjPhT8jymPHgH6Q:-L-h2MjPhT8jymPHgH6R:b-obicib) ([raw file](https://github.com/batfish/batfish/blob/d6ef1f453064b78de67b102e8aaf718aacaad8c9/projects/coordinator/src/main/java/org/batfish/coordinator/authorizer/DbAuthorizer.java#L37)):*
> ```Java
>   @VisibleForTesting static final String TABLE_USERS = "batfish_members";
> 
>   private Map<String, Date> _cacheApiKeys = new HashMap<>();
> ```

I suspect you could delete/simplify a lot of code using Guava caches instead of manually managed maps. Take a look and see if you want to incorporate here.

- built-in support for timeouts
- built-in support for loading missing values with code
- +threadsafety

https://github.com/google/guava/wiki/CachesExplained

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/authorizer/DbAuthorizer.java, line 86 at r1](https://reviewable.io:443/reviews/batfish/batfish/703#-L-gyvb6nt0TTcncDLVp:-L-gyvb6nt0TTcncDLVq:bnegs8d) ([raw file](https://github.com/batfish/batfish/blob/d6ef1f453064b78de67b102e8aaf718aacaad8c9/projects/coordinator/src/main/java/org/batfish/coordinator/authorizer/DbAuthorizer.java#L86)):*
> ```Java
>     String insertContainersString =
>         String.format(
>             // REPLACE INTO is more compatible with various DBs than ON DUPLICATE KEY UPDATE
> ```

This comment does not need to make in into the final code, does it?

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/authorizer/DbAuthorizer.java, line 120 at r1](https://reviewable.io:443/reviews/batfish/batfish/703#-L-h2gxTQFgSsrdtAW0M:-L-h2gxTQFgSsrdtAW0N:bmkj0yz) ([raw file](https://github.com/batfish/batfish/blob/d6ef1f453064b78de67b102e8aaf718aacaad8c9/projects/coordinator/src/main/java/org/batfish/coordinator/authorizer/DbAuthorizer.java#L120)):*
> ```Java
>             TABLE_PERMISSIONS, COLUMN_APIKEY, COLUMN_CONTAINER_NAME);
>     try {
>       PreparedStatement insertPermissions = _dbConn.prepareStatement(insertPermissionsString);
> ```

Looks to me like we have some pretty significant leaks. Shouldn't we be closing statements?

(Can be deferred to follow-on work.)

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/authorizer/DbAuthorizer.java, line 128 at r1](https://reviewable.io:443/reviews/batfish/batfish/703#-L-gzAh7qJn36J2RZyvj:-L-gzAh7qJn36J2RZyvk:bcobo8l) ([raw file](https://github.com/batfish/batfish/blob/2bdca749ebe75c10a898daadc5d440c62aa5475a/projects/coordinator/src/main/java/org/batfish/coordinator/authorizer/DbAuthorizer.java#L128)):*
> well shit

Yeeeeep.

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/authorizer/DbAuthorizer.java, line 137 at r1](https://reviewable.io:443/reviews/batfish/batfish/703#-L-gzT75gZeWeGuj40JE:-L-gzT75gZeWeGuj40JF:b4v7qpm) ([raw file](https://github.com/batfish/batfish/blob/d6ef1f453064b78de67b102e8aaf718aacaad8c9/projects/coordinator/src/main/java/org/batfish/coordinator/authorizer/DbAuthorizer.java#L137)):*
> ```Java
>   private synchronized ResultSet executeQuery(PreparedStatement query) {
>     int triesLeft = MAX_DB_TRIES;
>     String queryString = query.toString();
> ```

Why do we need `queryString` at all? It's only ever used in `String.format` context, where you can just pass the object itself and it will get stringified.

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/authorizer/DbAuthorizer.java, line 211 at r1](https://reviewable.io:443/reviews/batfish/batfish/703#-L-h3-IJ_w7Ngo3Fnjx0:-L-h3-IJ_w7Ngo3Fnjx1:b-fq031s) ([raw file](https://github.com/batfish/batfish/blob/d6ef1f453064b78de67b102e8aaf718aacaad8c9/projects/coordinator/src/main/java/org/batfish/coordinator/authorizer/DbAuthorizer.java#L211)):*
> ```Java
>     String selectPermittedContainerString =
>         String.format(
>             "SELECT * FROM %s WHERE %s = ? AND %s = ?",
> ```

Seems like it would be simpler if we have `SELECT COUNT(*) == 1 FROM`... and then we can rely on the result always being a single boolean row.

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/authorizer/DbAuthorizer.java, line 225 at r1](https://reviewable.io:443/reviews/batfish/batfish/703#-L-h3At2tL7oiz3bDIFR:-L-h3At2tL7oiz3bDIFS:b-n7nqtf) ([raw file](https://github.com/batfish/batfish/blob/d6ef1f453064b78de67b102e8aaf718aacaad8c9/projects/coordinator/src/main/java/org/batfish/coordinator/authorizer/DbAuthorizer.java#L225)):*
> ```Java
>     try {
>       // Call next() to support TYPE_FORWARD_ONLY cursors, such as sqlite cursors
>       authorized = rs != null && rs.next();
> ```

don't we have to close result sets?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/703#-:-L-h3QBaQt9_nZEBBpNg:bqo3y9r)*

**Comment by progwriter** [comment]
Review status: 3 of 5 files reviewed at latest revision, 7 unresolved discussions.

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/authorizer/DbAuthorizer.java, line 22 at r1](https://reviewable.io:443/reviews/batfish/batfish/703#-L-gyY__-oxeJRBhIz0R:-L-h4YRqxJAoEyXXC2iL:bhy9q7g) ([raw file](https://github.com/batfish/batfish/blob/d6ef1f453064b78de67b102e8aaf718aacaad8c9/projects/coordinator/src/main/java/org/batfish/coordinator/authorizer/DbAuthorizer.java#L22)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

typo: s/And/An/
</blockquote></details>

Will fix

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/authorizer/DbAuthorizer.java, line 37 at r1](https://reviewable.io:443/reviews/batfish/batfish/703#-L-h2MjPhT8jymPHgH6Q:-L-h4ZTOs7N6osByjWHn:b3uestm) ([raw file](https://github.com/batfish/batfish/blob/d6ef1f453064b78de67b102e8aaf718aacaad8c9/projects/coordinator/src/main/java/org/batfish/coordinator/authorizer/DbAuthorizer.java#L37)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I suspect you could delete/simplify a lot of code using Guava caches instead of manually managed maps. Take a look and see if you want to incorporate here.

- built-in support for timeouts
- built-in support for loading missing values with code
- +threadsafety

https://github.com/google/guava/wiki/CachesExplained
</blockquote></details>

That's a good point. I want to do this, but perhaps in another PR where I can dedicate more attention to it.
Similarly, I wanted to also do automatic connection pooling with something like [dbcp](https://commons.apache.org/proper/commons-dbcp/) to avoid manual validity checks of open connections and retries. Do you think worth putting the effort in?

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/authorizer/DbAuthorizer.java, line 86 at r1](https://reviewable.io:443/reviews/batfish/batfish/703#-L-gyvb6nt0TTcncDLVp:-L-h5STV7LF0WQsZOabb:b-pzil1s) ([raw file](https://github.com/batfish/batfish/blob/d6ef1f453064b78de67b102e8aaf718aacaad8c9/projects/coordinator/src/main/java/org/batfish/coordinator/authorizer/DbAuthorizer.java#L86)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

This comment does not need to make in into the final code, does it?
</blockquote></details>

Just wanted to be on the cautious side to save someone future headache/googling but can remove.

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/authorizer/DbAuthorizer.java, line 120 at r1](https://reviewable.io:443/reviews/batfish/batfish/703#-L-h2gxTQFgSsrdtAW0M:-L-h6XxxAGfXEx7Ac-UE:b3vdbcn) ([raw file](https://github.com/batfish/batfish/blob/d6ef1f453064b78de67b102e8aaf718aacaad8c9/projects/coordinator/src/main/java/org/batfish/coordinator/authorizer/DbAuthorizer.java#L120)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Looks to me like we have some pretty significant leaks. Shouldn't we be closing statements?

(Can be deferred to follow-on work.)
</blockquote></details>

Yep, you are right, will fix.

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/authorizer/DbAuthorizer.java, line 137 at r1](https://reviewable.io:443/reviews/batfish/batfish/703#-L-gzT75gZeWeGuj40JE:-L-h5xjeSxg6dL9s2M6D:bhy9q7g) ([raw file](https://github.com/batfish/batfish/blob/d6ef1f453064b78de67b102e8aaf718aacaad8c9/projects/coordinator/src/main/java/org/batfish/coordinator/authorizer/DbAuthorizer.java#L137)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Why do we need `queryString` at all? It's only ever used in `String.format` context, where you can just pass the object itself and it will get stringified.
</blockquote></details>

Will fix

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/authorizer/DbAuthorizer.java, line 211 at r1](https://reviewable.io:443/reviews/batfish/batfish/703#-L-h3-IJ_w7Ngo3Fnjx0:-L-h6mNdiLANv0UiTtql:brj4q4g) ([raw file](https://github.com/batfish/batfish/blob/d6ef1f453064b78de67b102e8aaf718aacaad8c9/projects/coordinator/src/main/java/org/batfish/coordinator/authorizer/DbAuthorizer.java#L211)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Seems like it would be simpler if we have `SELECT COUNT(*) == 1 FROM`... and then we can rely on the result always being a single boolean row.
</blockquote></details>

Can do

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/authorizer/DbAuthorizer.java, line 225 at r1](https://reviewable.io:443/reviews/batfish/batfish/703#-L-h3At2tL7oiz3bDIFR:-L-h6a-jiWlWtVbgjemi:b-rhsdvo) ([raw file](https://github.com/batfish/batfish/blob/d6ef1f453064b78de67b102e8aaf718aacaad8c9/projects/coordinator/src/main/java/org/batfish/coordinator/authorizer/DbAuthorizer.java#L225)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

don't we have to close result sets?
</blockquote></details>

Those are `AutoCloseable` and will close upon `Statement` closing, which we will do 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/703)*

**Comment by dhalperi** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/authorizer/DbAuthorizer.java, line 37 at r1](https://reviewable.io:443/reviews/batfish/batfish/703#-L-h2MjPhT8jymPHgH6Q:-L-omc6Wp1GDjK354jvt:b6zf7fq) ([raw file](https://github.com/batfish/batfish/blob/d6ef1f453064b78de67b102e8aaf718aacaad8c9/projects/coordinator/src/main/java/org/batfish/coordinator/authorizer/DbAuthorizer.java#L37)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

That's a good point. I want to do this, but perhaps in another PR where I can dedicate more attention to it.
Similarly, I wanted to also do automatic connection pooling with something like [dbcp](https://commons.apache.org/proper/commons-dbcp/) to avoid manual validity checks of open connections and retries. Do you think worth putting the effort in?
</blockquote></details>

Up to you. - I trust your taste.

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/authorizer/DbAuthorizer.java, line 225 at r1](https://reviewable.io:443/reviews/batfish/batfish/703#-L-h3At2tL7oiz3bDIFR:-L-omupppyeZvwuGL_Ka:b-vmnncw) ([raw file](https://github.com/batfish/batfish/blob/d6ef1f453064b78de67b102e8aaf718aacaad8c9/projects/coordinator/src/main/java/org/batfish/coordinator/authorizer/DbAuthorizer.java#L225)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

Those are `AutoCloseable` and will close upon `Statement` closing, which we will do 
</blockquote></details>

Let's talk tomorrow about `AutoCloseable`. Maybe I'm missing something, but I don't think we're doing it right here in failure cases.

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/authorizer/DbAuthorizer.java, line 301 at r2](https://reviewable.io:443/reviews/batfish/batfish/703#-L-onUjV7bIbLvDqv7mi:-L-onUjV7bIbLvDqv7mj:b-bl18o0) ([raw file](https://github.com/batfish/batfish/blob/f4dd5622ad5d6dd6dcd1677c8cb6a502262bf1b8/projects/coordinator/src/main/java/org/batfish/coordinator/authorizer/DbAuthorizer.java#L301)):*
> ```Java
>       triesLeft--;
>       try {
>         // Gracefully close previous connection if it exists (but could be invalid)
> ```

what's the scenario we re-open a previous connection? It timed out and we have to go again?

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/authorizer/DbAuthorizer.java, line 303 at r2](https://reviewable.io:443/reviews/batfish/batfish/703#-L-onMKbB51l7oTDoiUx:-L-onMKbB51l7oTDoiUy:b24rmpn) ([raw file](https://github.com/batfish/batfish/blob/f4dd5622ad5d6dd6dcd1677c8cb6a502262bf1b8/projects/coordinator/src/main/java/org/batfish/coordinator/authorizer/DbAuthorizer.java#L303)):*
> ```Java
>         // Gracefully close previous connection if it exists (but could be invalid)
>         if (_dbConn != null) {
>           _dbConn.close();
> ```

assign null after closing?

---

*[projects/coordinator/src/test/java/org/batfish/coordinator/authorizer/DbAuthorizerTest.java, line 26 at r2](https://reviewable.io:443/reviews/batfish/batfish/703#-L-onkUgnmQ4zVCQqAn2:-L-onkUgnmQ4zVCQqAn3:b-5r4bd3) ([raw file](https://github.com/batfish/batfish/blob/f4dd5622ad5d6dd6dcd1677c8cb6a502262bf1b8/projects/coordinator/src/test/java/org/batfish/coordinator/authorizer/DbAuthorizerTest.java#L26)):*
> ```Java
>   /*
>    *  Not using in-memory databases each new connection creates a brand new database.
>    *  Instead, using slightly more presisten DB inside a temporary folder.
> ```

typo: persistent?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/703)*

**Comment by dhalperi** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/703#-:-L-ooQ3VBhUv0o1tv4zw:bnfp4nl)*

**Comment by arifogel** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/authorizer/DbAuthorizer.java, line 128 at r1](https://reviewable.io:443/reviews/batfish/batfish/703#-L-gzAh7qJn36J2RZyvj:-L-skjpB-ILctXckuOpv:b6wqr2a) ([raw file](https://github.com/batfish/batfish/blob/2bdca749ebe75c10a898daadc5d440c62aa5475a/projects/coordinator/src/main/java/org/batfish/coordinator/authorizer/DbAuthorizer.java#L128)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> well shit

Yeeeeep.
</blockquote></details>

That should be the default message inherited from `Exception`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/703)*

**Comment by progwriter** [comment]
Review status: 3 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/authorizer/DbAuthorizer.java, line 301 at r2](https://reviewable.io:443/reviews/batfish/batfish/703#-L-onUjV7bIbLvDqv7mi:-L-t3N5ZIMgRS4T5DWM0:b-5lsx7n) ([raw file](https://github.com/batfish/batfish/blob/f4dd5622ad5d6dd6dcd1677c8cb6a502262bf1b8/projects/coordinator/src/main/java/org/batfish/coordinator/authorizer/DbAuthorizer.java#L301)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

what's the scenario we re-open a previous connection? It timed out and we have to go again?
</blockquote></details>

My understanding is yes, we do is if the connection is not `isValid()`

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/authorizer/DbAuthorizer.java, line 303 at r2](https://reviewable.io:443/reviews/batfish/batfish/703#-L-onMKbB51l7oTDoiUx:-L-t3SnhB1LpXMBLn_zq:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/f4dd5622ad5d6dd6dcd1677c8cb6a502262bf1b8/projects/coordinator/src/main/java/org/batfish/coordinator/authorizer/DbAuthorizer.java#L303)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

assign null after closing?
</blockquote></details>

Done.

---

*[projects/coordinator/src/test/java/org/batfish/coordinator/authorizer/DbAuthorizerTest.java, line 26 at r2](https://reviewable.io:443/reviews/batfish/batfish/703#-L-onkUgnmQ4zVCQqAn2:-L-t3Ts1uoc118WeTqfI:b-af1832) ([raw file](https://github.com/batfish/batfish/blob/f4dd5622ad5d6dd6dcd1677c8cb6a502262bf1b8/projects/coordinator/src/test/java/org/batfish/coordinator/authorizer/DbAuthorizerTest.java#L26)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

typo: persistent?
</blockquote></details>

Yep, thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/703)*

**Comment by arifogel** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/703)*

**Comment by dhalperi** [comment]
Reviewed 2 of 2 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/703)*

**Pull request merged**
