### PR TITLE
add support for nxos major 10

### PR DESCRIPTION
**Pull request by jeffkala**
hitting this error when I init with this config from a Cisco NX-OS device:
`java.lang.IllegalArgumentException: Unsupported major version: UNKNOWN`

It looks like this is the line the error is happening on?
```
!Command: show running-config
!Running configuration last done at: Wed Jun 28 10:02:27 2023
!Time: Wed Aug  9 18:25:19 2023

version 10.1(1) Bios:version 05.43 
```

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8773)* status: all files reviewed, 3 unresolved discussions (waiting on @jeffkala)

___
*[`projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosPreprocessor.java` line 125 at r1](https://reviewable.io/reviews/batfish/batfish/8773#-NbWV09jBQ-hNN4uRwc5:-NbWV09jBQ-hNN4uRwc6:b4lv5aq) ([raw file](https://github.com/batfish/batfish/blob/2e3e0c340afa76e8a7155badf7cc6af093ca3b76/projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosPreprocessor.java#L125)):*
> ```Java
>         return NxosMajorVersion.NXOS9;
>       case '1':
>         return NxosMajorVersion.NXOS10;
> ```

Looks like this will silently include cases like when the major version is `11`.

I'd add a second switch in this case for `version.charAt(1)` - or at least a `checkArgument(version.charAt(1)) == '0'` so this fails loudly if/when version 11 is hit.
___
*[`projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosPreprocessor.java` line 192 at r1](https://reviewable.io/reviews/batfish/batfish/8773#-NbWVThQ5OI9Y6UtLSqm:-NbWVThQ5OI9Y6UtLSqn:bdtf0zk) ([raw file](https://github.com/batfish/batfish/blob/2e3e0c340afa76e8a7155badf7cc6af093ca3b76/projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosPreprocessor.java#L192)):*
> ```Java
>     }
>     if (majorVersion == NxosMajorVersion.NXOS10) {
>       // In this case, defaults are same for Nexus 3000 and Nexus 9000. So just arbitrarily choose
> ```

Is this true for version 10?
___
*[`projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosPreprocessor.java` line 301 at r1](https://reviewable.io/reviews/batfish/batfish/8773#-NbWVW5-481IKzhGNn4P:-NbWVW5-481IKzhGNn4Q:b-ser6fm) ([raw file](https://github.com/batfish/batfish/blob/2e3e0c340afa76e8a7155badf7cc6af093ca3b76/projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosPreprocessor.java#L301)):*
> ```Java
>             return true;
>           case NXOS10:
>             // TODO: add link to doc
> ```

Is that a TODO for this PR? Or do docs not exist yet?
If docs are there, I'd block on adding relevant links.

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8773)* status: all files reviewed, 2 unresolved discussions (waiting on @jeffkala)

**Review by jeffkala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8773)* status: all files reviewed, 2 unresolved discussions (waiting on @arifogel)

___
*[`projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosPreprocessor.java` line 301 at r1](https://reviewable.io/reviews/batfish/batfish/8773#-NbWVW5-481IKzhGNn4P:-NbZsJfbABFRDxKCnzTA:bgd9ga) ([raw file](https://github.com/batfish/batfish/blob/2e3e0c340afa76e8a7155badf7cc6af093ca3b76/projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosPreprocessor.java#L301)):*
<details><summary><i>Previously, jeffkala (Jeff Kala) wrote…</i></summary><blockquote>

For this PR, will get it added.
</blockquote></details>

Found documentation reference will get it added as a comment in code as well.
https://www.cisco.com/c/en/us/td/docs/dcn/nx-os/nexus9000/101x/configuration/interfaces/cisco-nexus-9000-nx-os-interfaces-configuration-guide-101x/b-cisco-nexus-9000-nx-os-interfaces-configuration-guide-93x_chapter_0101.html#:~:text=you%20would%20use.-,Default%20Settings,Admin%20state,-Shut

**Review by jeffkala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8773)* status: all files reviewed, 2 unresolved discussions (waiting on @arifogel)

___
*[`projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosPreprocessor.java` line 192 at r1](https://reviewable.io/reviews/batfish/batfish/8773#-NbWVThQ5OI9Y6UtLSqm:-NbZu1bw5YnKmMgxx0Rt:b-zfdsxg) ([raw file](https://github.com/batfish/batfish/blob/2e3e0c340afa76e8a7155badf7cc6af093ca3b76/projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosPreprocessor.java#L192)):*
<details><summary><i>Previously, jeffkala (Jeff Kala) wrote…</i></summary><blockquote>

Need to research.
</blockquote></details>

admin shut is the default for both n3k and n9k. https://www.cisco.com/c/en/us/td/docs/dcn/nx-os/nexus3548/101x/configuration/interfaces/cisco-nexus-3548-nx-os-interfaces-configuration-guide-101x/m-configuring-layer3-interfaces.html#:~:text=to%20Layer%202.-,Default%20Settings%20for%20Layer%203%20Interfaces,The%20default%20setting%20for%20the%20Layer%203%20Admin%20state%20is%20Shut.,-Configuring%20Layer%203

**Review by arifogel — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8773#-:-Nb_Yev-2ZTTwMkEYmsJ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jeffkala)

**Pull request merged**
