### PR TITLE
TransferBDD: elide some intermediate unreachable results

### PR DESCRIPTION
**Pull request by dhalperi**

### CODE REVIEW

**Review by nickgian — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/9148#-:-O3mmtft8LN3cMTVbqYj:bnfp4nl)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @millstein)

___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java` line 569 at r1](https://reviewable.io/reviews/batfish/batfish/9148#-O3mj0l29Gj5inzLNPFe:-O3mj0l29Gj5inzLNPFf:bxg95q1) ([raw file](https://github.com/batfish/batfish/blob/977c39cf4d14af9c18d8d70d0baa8014a8be40fc/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java#L569)):*
> ```Java
>                   new CommunitySetMatchExprToBDD(),
>                   new Arg(this, routeForMatching(p, context), context));
>       if (!mcPredicate.isZero()) {
> ```

is there some criteria based on which you do this optimization?
e.g., should we also do it for `MatchAsPath`, etc.?

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/9148)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @millstein)

___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java` line 569 at r1](https://reviewable.io/reviews/batfish/batfish/9148#-O3mj0l29Gj5inzLNPFe:-O3moNek5QacWvXyuk9F:b-m4yoej) ([raw file](https://github.com/batfish/batfish/blob/977c39cf4d14af9c18d8d70d0baa8014a8be40fc/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java#L569)):*
<details><summary><i>Previously, nickgian (Nick Giannarakis) wrote…</i></summary><blockquote>

is there some criteria based on which you do this optimization?
e.g., should we also do it for `MatchAsPath`, etc.?
</blockquote></details>

I did it by inserting an assertion in `TransferResult` constructor and whacking all the moles. Yes, this was lazy :p.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/9148)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @millstein)

**Review by dhalperi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/9148)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @millstein)

**Pull request merged**
