### PR TITLE
Aaa: setter should use its parameter

### PR DESCRIPTION
**Pull request by dhalperi**

### CODE REVIEW

**Comment by erikljungman** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed, all discussions resolved (waiting on @erikljungman and @arifogel)

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1776#-:-LG617G6E-Ok2t7Pz9lA:bnfp4nl)*

**Comment by dhalperi** [comment]
Review status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @erikljungman and @arifogel)

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1776#-LG6GWD0Cvuf86qRx4ls:-LG6GWD0Cvuf86qRx4lt:b-n8oc63) (no related file):*
@erikljungman did you intend to mark all the files as reviewed? Or did you have some issue you wanted addressed?

Btw, what impact will this fix have on the stuff you've been doing? Related or unrelated?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1776)*

**Comment by erikljungman** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed, 1 unresolved discussion (waiting on @erikljungman and @arifogel)

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1776#-LG6GWD0Cvuf86qRx4ls:-LG6TpZg22K2DM15AZma:bc24ff8) (no related file):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

@erikljungman did you intend to mark all the files as reviewed? Or did you have some issue you wanted addressed?

Btw, what impact will this fix have on the stuff you've been doing? Related or unrelated?
</blockquote></details>

yea my bad I meant to mark them as reviewed. And this shouldn't have any impact on what I've been doing - the only place that setter is being used it passes it a `new AaaAuthentiction()`

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1776)*

**Comment by arifogel** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1776#-:-LG6UTVn4cb2zyPyt4rx:bnfp4nl)*

**Pull request merged**
