### PR TITLE
FortiOS: zone parsing and extraction

### PR DESCRIPTION
**Pull request by sfraint**

### CODE REVIEW

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6732)* status: 0 of 13 files reviewed, all discussions resolved (waiting on @corinaminer)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6732#-MVsCYxw2UdcSGZxE8bL:-MVsCYxw2UdcSGZxE8bM:b1lp6qv) (no related file):*
Going to wrap up refs/defs, rename, and conversion in separate PR(s) to keep this one from growing too much

---

**Review by corinaminer — COMMENTED** [review]
> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6732)* status: all files reviewed, 7 unresolved discussions (waiting on @sfraint)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_zone.g4, line 37 at r1](https://reviewable.io/reviews/batfish/batfish/6732#-MVu7CcnAt7PpSNetRCW:-MVu7Cco7BvlVPLJci_h:b-bmqw93) ([raw file](https://github.com/batfish/batfish/blob/876d50f2e464ddfede8badda870679d10826d7d5/projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_zone.g4#L37)):*
> ```ANTLR
> csz_set_intrazone: INTRAZONE value = allow_or_deny newline;
> 
> csz_set_lists: csz_set_interface;
> ```

there's more stuff we'll eventually want to add to `csz_set_lists`, right? If not, i don't think we need to stick to the `set_lists` pattern. (same for `append`)
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_zone.g4, line 46 at r1](https://reviewable.io/reviews/batfish/batfish/6732#-MVu7zrb5u3MErZseixm:-MVu7zrb5u3MErZseixn:b-j2ndrc) ([raw file](https://github.com/batfish/batfish/blob/876d50f2e464ddfede8badda870679d10826d7d5/projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_zone.g4#L46)):*
> ```ANTLR
> 
> // Up to 35 characters
> zone_name: str;
> ```

This should probably go in `Fortios_common`. Ok with leaving it here until it's needed elsewhere if you prefer, though.
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 811 at r1](https://reviewable.io/reviews/batfish/batfish/6732#-MVu32uR2LgG6giXTwgF:-MVu32uR2LgG6giXTwgG:byzou4o) ([raw file](https://github.com/batfish/batfish/blob/876d50f2e464ddfede8badda870679d10826d7d5/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L811)):*
> ```Java
>   public void exitCsz_edit(Csz_editContext ctx) {
>     // If edited item is valid, add/update the entry in VS map
>     String name = _currentZone.getName();
> ```

this is only needed when the zone is valid; can go inside the `if`
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 819 at r1](https://reviewable.io/reviews/batfish/batfish/6732#-MVu3NqT91ShVD0eS_8K:-MVu3NqT91ShVD0eS_8L:b-btk0p5) ([raw file](https://github.com/batfish/batfish/blob/876d50f2e464ddfede8badda870679d10826d7d5/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L819)):*
> ```Java
>           name,
>           FortiosStructureUsage.ZONE_SELF_REF,
>           ctx.start.getLine());
> ```

Why do we want this self-reference? won't this mean zones can never show up as unused structures?
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 955 at r1](https://reviewable.io/reviews/batfish/batfish/6732#-MVu5_91CfX__7dH9v9d:-MVu5_91CfX__7dH9v9e:bhpqlst) ([raw file](https://github.com/batfish/batfish/blob/876d50f2e464ddfede8badda870679d10826d7d5/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L955)):*
> ```Java
>             String.format(
>                 "Interface %s is already in another zone and cannot be added to zone %s",
>                 name, currentZoneName));
> ```

your princess is in another castle! :o
___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/Zone.java, line 11 at r1](https://reviewable.io/reviews/batfish/batfish/6732#-MVu14qRDPPWMHC19AM0:-MVu14qRDPPWMHC19AM1:b-kw8ywp) ([raw file](https://github.com/batfish/batfish/blob/876d50f2e464ddfede8badda870679d10826d7d5/projects/batfish/src/main/java/org/batfish/representation/fortios/Zone.java#L11)):*
> ```Java
> import javax.annotation.Nullable;
> 
> /** FortiOS datamodel component containing interface configuration */
> ```

zone configuration
___
*[projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java, line 558 at r1](https://reviewable.io/reviews/batfish/batfish/6732#-MVuBACn2PBjxCAylPbl:-MVuBACn2PBjxCAylPbm:b5ihti2) ([raw file](https://github.com/batfish/batfish/blob/876d50f2e464ddfede8badda870679d10826d7d5/projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java#L558)):*
> ```Java
>                 allOf(
>                     hasComment("Zone edit block ignored: interface must be set"),
>                     hasText("edit \"zone1\"\n    next")),
> ```

this is fine, but you can also just do `hasText(containsString("zone1"))`, for future reference.
___
*[projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/zone, line 26 at r1](https://reviewable.io/reviews/batfish/batfish/6732#-MVuCPc_42TQ3_YSL6n6:-MVuCPca1RUTTS8F62aa:b-ziddvx) ([raw file](https://github.com/batfish/batfish/blob/876d50f2e464ddfede8badda870679d10826d7d5/projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/zone#L26)):*
> ```
>     next
> end
> config system zone
> ```

This test should test a line that sets multiple interfaces (eg `set interface port1 port2`). Would probably also be good to add a similar line in `zone_warn`, like `set interface port1 UNDEFINED`, and confirm the line has no effect.
___
*[projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/zone, line 30 at r1](https://reviewable.io/reviews/batfish/batfish/6732#-MVu9w8Z1UF_lHyez4vd:-MVu9w8Z1UF_lHyez4ve:b7s0lky) ([raw file](https://github.com/batfish/batfish/blob/876d50f2e464ddfede8badda870679d10826d7d5/projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/zone#L30)):*
> ```
>         set interface port1
>         set interface port2
>         append interface port1
> ```

I think this would be slightly better if you started with `set interface port3` instead of `set interface port1`. That way you can be sure the first `set` is really overwritten by the second, and you also get to check that `port3` is still fair game for adding to `zone2` after being mentioned in `zone1`.
___
*[projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/zone, line 44 at r1](https://reviewable.io/reviews/batfish/batfish/6732#-MVu8rZ08e4EWM1Sfozs:-MVu8rZ08e4EWM1Sfozt:b1l5eof) ([raw file](https://github.com/batfish/batfish/blob/876d50f2e464ddfede8badda870679d10826d7d5/projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/zone#L44)):*
> ```
>     #edit "zone3"
>     #    set intrazone allow
>         # TODO is this valid?
> ```

did you check? is there ambiguity? If it's unclear, it should be a TODO in the test rather than in the config.

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6732)* status: 7 of 13 files reviewed, 6 unresolved discussions (waiting on @corinaminer)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_zone.g4, line 37 at r1](https://reviewable.io/reviews/batfish/batfish/6732#-MVu7CcnAt7PpSNetRCW:-MVw2TVm8399gsGYEVtm:b-abol62) ([raw file](https://github.com/batfish/batfish/blob/876d50f2e464ddfede8badda870679d10826d7d5/projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_zone.g4#L37)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

there's more stuff we'll eventually want to add to `csz_set_lists`, right? If not, i don't think we need to stick to the `set_lists` pattern. (same for `append`)
</blockquote></details>

not planning on adding anything, updated
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_zone.g4, line 46 at r1](https://reviewable.io/reviews/batfish/batfish/6732#-MVu7zrb5u3MErZseixm:-MVw2acg9yIkTNw2La6N:bvgngqu) ([raw file](https://github.com/batfish/batfish/blob/876d50f2e464ddfede8badda870679d10826d7d5/projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_zone.g4#L46)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

This should probably go in `Fortios_common`. Ok with leaving it here until it's needed elsewhere if you prefer, though.
</blockquote></details>

I think singular will only be needed here, can move if end up needing it elsewhere, later
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 811 at r1](https://reviewable.io/reviews/batfish/batfish/6732#-MVu32uR2LgG6giXTwgF:-MVw2xn8-MPbiK9IMCvQ:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/876d50f2e464ddfede8badda870679d10826d7d5/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L811)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

this is only needed when the zone is valid; can go inside the `if`
</blockquote></details>

done
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 819 at r1](https://reviewable.io/reviews/batfish/batfish/6732#-MVu3NqT91ShVD0eS_8K:-MVw2yvu5pjZ4IpTFR81:b-avozic) ([raw file](https://github.com/batfish/batfish/blob/876d50f2e464ddfede8badda870679d10826d7d5/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L819)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Why do we want this self-reference? won't this mean zones can never show up as unused structures?
</blockquote></details>

right, because declaration also implicitly adds firewall policy/behavior (intrazone allow or intrazone deny)
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 955 at r1](https://reviewable.io/reviews/batfish/batfish/6732#-MVu5_91CfX__7dH9v9d:-MVw3RK951OusbMX-rZN:b-qhdkot) ([raw file](https://github.com/batfish/batfish/blob/876d50f2e464ddfede8badda870679d10826d7d5/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L955)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

your princess is in another castle! :o
</blockquote></details>

:open_mouth: :grin: 
___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/Zone.java, line 11 at r1](https://reviewable.io/reviews/batfish/batfish/6732#-MVu14qRDPPWMHC19AM0:-MVw3Y_f-vs38r569WiC:bmylu5n) ([raw file](https://github.com/batfish/batfish/blob/876d50f2e464ddfede8badda870679d10826d7d5/projects/batfish/src/main/java/org/batfish/representation/fortios/Zone.java#L11)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

zone configuration
</blockquote></details>

woops, fixed
___
*[projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java, line 558 at r1](https://reviewable.io/reviews/batfish/batfish/6732#-MVuBACn2PBjxCAylPbl:-MVw3mLG1FT-09cE98pJ:bvnrpcm) ([raw file](https://github.com/batfish/batfish/blob/876d50f2e464ddfede8badda870679d10826d7d5/projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java#L558)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

this is fine, but you can also just do `hasText(containsString("zone1"))`, for future reference.
</blockquote></details>

updated
___
*[projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/zone, line 26 at r1](https://reviewable.io/reviews/batfish/batfish/6732#-MVuCPc_42TQ3_YSL6n6:-MVw5zC5Btcn_0K2vr3u:bt2y3rv) ([raw file](https://github.com/batfish/batfish/blob/876d50f2e464ddfede8badda870679d10826d7d5/projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/zone#L26)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

This test should test a line that sets multiple interfaces (eg `set interface port1 port2`). Would probably also be good to add a similar line in `zone_warn`, like `set interface port1 UNDEFINED`, and confirm the line has no effect.
</blockquote></details>

added the multi interface line here and in `zone_warn`
___
*[projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/zone, line 30 at r1](https://reviewable.io/reviews/batfish/batfish/6732#-MVu9w8Z1UF_lHyez4vd:-MVw6Asf6gSGYepjuG95:bvnrpcm) ([raw file](https://github.com/batfish/batfish/blob/876d50f2e464ddfede8badda870679d10826d7d5/projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/zone#L30)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

I think this would be slightly better if you started with `set interface port3` instead of `set interface port1`. That way you can be sure the first `set` is really overwritten by the second, and you also get to check that `port3` is still fair game for adding to `zone2` after being mentioned in `zone1`.
</blockquote></details>

updated
___
*[projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/zone, line 44 at r1](https://reviewable.io/reviews/batfish/batfish/6732#-MVu8rZ08e4EWM1Sfozs:-MVw4-d0AMqpPOf6mcsH:b-qgffqo) ([raw file](https://github.com/batfish/batfish/blob/876d50f2e464ddfede8badda870679d10826d7d5/projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/zone#L44)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

did you check? is there ambiguity? If it's unclear, it should be a TODO in the test rather than in the config.
</blockquote></details>

it's not valid - meant to remove this (not valid)

removed

**Review by corinaminer — COMMENTED** [review]
:lgtm:

> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6732#-:-MVwEoABBT67V_psZRsn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
