### PR TITLE
CheckPoint: `host` destination translation in manual hide rules

### PR DESCRIPTION
**Pull request by sfraint**

### CODE REVIEW

**Review by corinaminer — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7631)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @arifogel and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversions.java, line 245 at r1](https://reviewable.io/reviews/batfish/batfish/7631#-MnS85pW68xY62dfU9pw:-MnS85pY8G2OfqaAru-x:b1n56a5) ([raw file](https://github.com/batfish/batfish/blob/2a028291ea8ee18a8a91dc643c45a01b3475297a/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversions.java#L245)):*
> ```Java
>                 "Manual Hide NAT rule translated-destination %s type %s does not match"
>                     + " original-destination type %s and will be ignored",
>                 dst.getName(), dst.getClass().getSimpleName(), origDst.getClass().getSimpleName()));
> ```

maybe dumb question, but how come they can't be different classes? I thought they'd be independent -- original dest for matching and translated for picking NAT dst IP

**Review by corinaminer — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7631)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel and @sfraint)

___
*[projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversionsTest.java, line 205 at r1](https://reviewable.io/reviews/batfish/batfish/7631#-MnSITH3ADCbgUcoizJS:-MnSITH3ADCbgUcoizJT:by6nkjs) ([raw file](https://github.com/batfish/batfish/blob/2a028291ea8ee18a8a91dc643c45a01b3475297a/projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversionsTest.java#L205)):*
> ```Java
>       assertThat(
>           warnings.getRedFlagWarnings(),
>           contains(hasText(containsString("translated-service foo has invalid type ServiceTcp"))));
> ```

`ServiceTcp` is an invalid service type?

Non-blocking because this is what the test already did
___
*[projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversionsTest.java, line 349 at r1](https://reviewable.io/reviews/batfish/batfish/7631#-MnSSTowC6mu7ruKcphG:-MnSSTowC6mu7ruKcphH:b-g7xnjk) ([raw file](https://github.com/batfish/batfish/blob/2a028291ea8ee18a8a91dc643c45a01b3475297a/projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversionsTest.java#L349)):*
> ```Java
>               Uid.of("9999"));
>       assertThat(
>           manualHideTransformationSteps(natRule, OBJECTS, warnings), equalTo(Optional.empty()));
> ```

this seems like a bug -- is this not a legal manual rule, which would match but not transform traffic?

Not blocking because this potential bug is unrelated to your change.

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7631)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversions.java, line 245 at r1](https://reviewable.io/reviews/batfish/batfish/7631#-MnS85pW68xY62dfU9pw:-MnSwIC19zvFEzvaPTpj:b5x7d1) ([raw file](https://github.com/batfish/batfish/blob/2a028291ea8ee18a8a91dc643c45a01b3475297a/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversions.java#L245)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

maybe dumb question, but how come they can't be different classes? I thought they'd be independent -- original dest for matching and translated for picking NAT dst IP
</blockquote></details>

Yeah, it's probably fine and Batfish can definitely handle it; I was just limiting checks to the set of combinations I'd seen

No strong reason to keep this, and we can alway dial back if needed
___
*[projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversionsTest.java, line 205 at r1](https://reviewable.io/reviews/batfish/batfish/7631#-MnSITH3ADCbgUcoizJS:-MnT-4c5426uwjjMmFIR:b7t5u46) ([raw file](https://github.com/batfish/batfish/blob/2a028291ea8ee18a8a91dc643c45a01b3475297a/projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversionsTest.java#L205)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

`ServiceTcp` is an invalid service type?

Non-blocking because this is what the test already did
</blockquote></details>

Yep, not sure why you'd want to change the destination-service on a hide NAT
___
*[projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversionsTest.java, line 349 at r1](https://reviewable.io/reviews/batfish/batfish/7631#-MnSSTowC6mu7ruKcphG:-MnT-PuH6fB8hNByoNed:b-cz9yei) ([raw file](https://github.com/batfish/batfish/blob/2a028291ea8ee18a8a91dc643c45a01b3475297a/projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversionsTest.java#L349)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

this seems like a bug -- is this not a legal manual rule, which would match but not transform traffic?

Not blocking because this potential bug is unrelated to your change.
</blockquote></details>

Probably not allowed, but

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7631)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversionsTest.java, line 349 at r1](https://reviewable.io/reviews/batfish/batfish/7631#-MnSSTowC6mu7ruKcphG:-MnT-ntn3ztIY0O0FwU-:b-44xi1l) ([raw file](https://github.com/batfish/batfish/blob/2a028291ea8ee18a8a91dc643c45a01b3475297a/projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversionsTest.java#L349)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

Probably not allowed, but 
</blockquote></details>

functionally not a big deal since we shouldn't get rules like this and maybe in some case you would want to change just the source port

**Review by corinaminer — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7631)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

___
*[projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversionsTest.java, line 205 at r1](https://reviewable.io/reviews/batfish/batfish/7631#-MnSITH3ADCbgUcoizJS:-MnWkXtz5WE3wMHkKv4S:bb6mt9b) ([raw file](https://github.com/batfish/batfish/blob/2a028291ea8ee18a8a91dc643c45a01b3475297a/projects/batfish/src/test/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversionsTest.java#L205)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

Yep, not sure why you'd want to change the destination-service on a hide NAT
</blockquote></details>

:+1:

**Pull request merged**
