### PR TITLE
OSPF topology compute unnumbered sessions

### PR DESCRIPTION
**Pull request by arifogel**
- point-to-point links need not be on the same prefix
- use ospfAddresses to determine possible OspfConfigId source addresses
  over getAllConcreteAddresses when ospfAddresses is present, e.g. for
  unnumbered interfaces

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7042)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel and @corinaminer)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfTopologyUtils.java, line 283 at r2](https://reviewable.io/reviews/batfish/batfish/7042#-MbE0DMW--Ows9EL-i_k:-MbE0DMW--Ows9EL-i_l:b-ti3y33) ([raw file](https://github.com/batfish/batfish/blob/24d6f47163aeb0fc55465974c4d6a41d1c13ce33/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfTopologyUtils.java#L283)):*
> ```Java
>       //   occur even when things are properly configured, so just silently throw out this edge with
>       //   NO_SESSION.
>       if (localNetworkType != OspfNetworkType.POINT_TO_POINT
> ```

this covers if both are set. What if only one is set?

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7042)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @corinaminer and @dhalperi)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfTopologyUtils.java, line 283 at r2](https://reviewable.io/reviews/batfish/batfish/7042#-MbE0DMW--Ows9EL-i_k:-MbE1aCq9YgddBUI-Mr5:b-7ql1td) ([raw file](https://github.com/batfish/batfish/blob/24d6f47163aeb0fc55465974c4d6a41d1c13ce33/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfTopologyUtils.java#L283)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

this covers if both are set. What if only one is set?
</blockquote></details>

fixed

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7042)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel and @corinaminer)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfTopologyUtils.java, line 289 at r3](https://reviewable.io/reviews/batfish/batfish/7042#-MbE2oYL44y-veDJAijo:-MbE2oYM9p_hVxr4Dyj8:bip5xy6) ([raw file](https://github.com/batfish/batfish/blob/fe6f40860fed7df53f368374e1694a6802a85687/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfTopologyUtils.java#L289)):*
> ```Java
>       assumedNetworkType = remoteNetworkType;
>     }
>     // - If P2P and prefixes do not match, the session is unnumbered.
> ```

Suggest something like "Skip prefix check for point-to-point sessions." I think unnumbered/etc is a red herring.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7042)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @corinaminer and @dhalperi)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfTopologyUtils.java, line 289 at r3](https://reviewable.io/reviews/batfish/batfish/7042#-MbE2oYL44y-veDJAijo:-MbE3v-r3Y85m8qoGBAn:bvnrpcm) ([raw file](https://github.com/batfish/batfish/blob/fe6f40860fed7df53f368374e1694a6802a85687/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ospf/OspfTopologyUtils.java#L289)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Suggest something like "Skip prefix check for point-to-point sessions." I think unnumbered/etc is a red herring.
</blockquote></details>

updated

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7042)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

**Pull request merged**
