### PR TITLE
Add WorkMgrServiceV2 REST endpoint for autocomplete

### PR DESCRIPTION
**Pull request by arifogel**

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 3 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8447)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @arifogel, @corinaminer, and @sfraint)

___
*[`projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java` line 71 at r1](https://reviewable.io/reviews/batfish/batfish/8447#-N8k6FMfDgd21x6KCXA-:-N8k6FMfDgd21x6KCXA0:bsgljqp) ([raw file](https://github.com/batfish/batfish/blob/ece9eea9d83a2e8531386af7702e832f559d5097/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java#L71)):*
> ```Java
>       @FormDataParam(CoordConsts.SVC_KEY_VERSION) String clientVersion,
>       @FormDataParam(CoordConsts.SVC_KEY_NETWORK_NAME) String networkName,
>       /* Optional: not needed for some completions */
> ```

Is it not true that snapshot is not always needed? I thought at least for some syntax things it indeed is not needed.



_Code quote:_
```Java
 /* Optional: not needed for some completions */
```

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8447)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @corinaminer, @dhalperi, and @sfraint)

___
*[`projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java` line 71 at r1](https://reviewable.io/reviews/batfish/batfish/8447#-N8k6FMfDgd21x6KCXA-:-N8k8YVL3lV6J0TB2sr1:b85qzq6) ([raw file](https://github.com/batfish/batfish/blob/ece9eea9d83a2e8531386af7702e832f559d5097/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java#L71)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Is it not true that snapshot is not always needed? I thought at least for some syntax things it indeed is not needed.
</blockquote></details>

The comments and annotations seem to suggest that it is not always needed. However, in practice, you will always get an error without it:
`WorkMgrService.autoComplete` -> `WorkMgr.autoComplete` -> `WorkMgr.getCompletionMetadata`
The latter begins:
```
  private CompletionMetadata getCompletionMetadata(String network, String snapshot)
      throws IOException {
    checkArgument(!isNullOrEmpty(network), "Network name should be supplied");
    checkArgument(!isNullOrEmpty(snapshot), "Snapshot name should be supplied");
```

**Comment by dhalperi** [comment]
*[`projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java` line 71 at r1](https://reviewable.io/reviews/batfish/batfish/8447#-N8k6FMfDgd21x6KCXA-:-N8kAO_I2gSqZ02OYLSM:bplvujw) ([raw file](https://github.com/batfish/batfish/blob/ece9eea9d83a2e8531386af7702e832f559d5097/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java#L71)):*
> getCompletionMetadata
cc: @anothermattbrown @ratulm - this is true, isn't this a regression? Do we care?

**Comment by dhalperi** [comment]
*[`projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java` line 71 at r1](https://reviewable.io/reviews/batfish/batfish/8447#-N8k6FMfDgd21x6KCXA-:-N8kAvbL9662ugK5Xu0W:b-kzyccw) ([raw file](https://github.com/batfish/batfish/blob/ece9eea9d83a2e8531386af7702e832f559d5097/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java#L71)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> getCompletionMetadata
cc: @anothermattbrown @ratulm - this is true, isn't this a regression? Do we care?
</blockquote></details>

cc: @anothermattbrown @ratulm - this is true, isn't this a regression? Do we care?

(in case the quote above messed up notification)

**Review by anothermattbrown — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8447)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @corinaminer, @ratulm, and @sfraint)

___
*[`projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java` line 71 at r1](https://reviewable.io/reviews/batfish/batfish/8447#-N8k6FMfDgd21x6KCXA-:-N8zBv0y0ojRJa6obhoq:b4ytr7m) ([raw file](https://github.com/batfish/batfish/blob/ece9eea9d83a2e8531386af7702e832f559d5097/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java#L71)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

cc: @anothermattbrown @ratulm - this is true, isn't this a regression? Do we care?

(in case the quote above messed up notification)
</blockquote></details>

We could let those be optional and have `getCompletionMetadata` just return null in those cases (it already returns null if the network or snapshot doesn't exist, for example).

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8447)* status: 2 of 9 files reviewed, 1 unresolved discussion (waiting on @corinaminer, @dhalperi, @ratulm, and @sfraint)

___
*[`projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java` line 71 at r1](https://reviewable.io/reviews/batfish/batfish/8447#-N8k6FMfDgd21x6KCXA-:-N8zfZSACUko7jAET9_l:blsyn8p) ([raw file](https://github.com/batfish/batfish/blob/ece9eea9d83a2e8531386af7702e832f559d5097/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrService.java#L71)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

We could let those be optional and have `getCompletionMetadata` just return null in those cases (it already returns null if the network or snapshot doesn't exist, for example). 
</blockquote></details>

@anothermattbrown I integrated your suggestion, and I made changes to allow omitting a snapshot for the v2 call by splitting into two resource locations (/networks/networkname/autocomplete vs /networks/networkname/snapshots/snapshotname/autocomplete.

v1 behavior is fixed for the case of no snapshot name.

**Review by dhalperi — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 6 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8447#-:-N9-A9lJB10ohRdI3_V7:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer and @sfraint)

**Pull request merged**
