### PR TITLE
Added -dataplaneengine parameter as part of task arguments

### PR DESCRIPTION
**Pull request by progwriter**
When running Batfish in distributed mode (i.e., manually invoking coordinator and worker in separate processes), worker arguments can get ignored when a new task is started.

I believe this is because of re-initialization of settings upon new task being executed (see https://github.com/batfish/batfish/blob/master/projects/batfish/src/main/java/org/batfish/main/Driver.java#L639-L642)

It is unclear to me what overall behavior is desired. Should `_mainSettings` be selectively overriden or selectively chosen from?

This PR picks the latter for the `-dataplaneengine` parameter.
Also, some additional logging statements were added for sanity checking.

---
This change is [Reviewable](https://reviewable.io/reviews/batfish/batfish/892)

### CODE REVIEW

**Comment by ratulm** [comment]
selectively overriden ... the attempt is to preserve all settings. how are you doing things?

**Comment by progwriter** [comment]
Hm. Could it because I'm not using allinone? When I'm invoking both, I use different entry points: one is `org.batfish.coordinator.Main` the other one is `org.batfish.main.Driver`

**Comment by ratulm** [comment]
if you want to pass an argument to batfish that is not abstracted by
coordinator (most are not) use -batfishargs argument to coordinator. (is
that what you were missing? or, am i missing something?)

**Comment by progwriter** [comment]
Attempting to implement the desired behavior of selectively overriden settings. Doesn't seem like a very elegant solution though.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/892#-:-L4IJI3MZHWv8CrvUbjA:b9t6sf6)*

**Comment by ratulm** [comment]
instead of a whitelist of settings, which is hard to maintain, why not do a blacklist of settings that shouldn't be carried over?  (that seems closer to what you want. the only blacklist entry at the moment is the running mode.)

**Comment by ratulm** [comment]
:lgtm: (when green)

---

Reviewed 1 of 2 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/892#-:-L4iquPMh4vQKVFoLKQ_:bopeokz)*

**Comment by progwriter** [comment]
Closing because #956 is a better (more general) implementation of this feature.

**Pull request closed without merging**
