### PR TITLE
Use TraceableStatement in IOS route map conversion

### PR DESCRIPTION
**Pull request by ratulm**

### CODE REVIEW

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 1 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7109)* status: 1 of 14 files reviewed, 1 unresolved discussion (waiting on @ratulm)

___
*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 2249 at r3](https://reviewable.io/reviews/batfish/batfish/7109#-MdOK6VT5dZT7hIyG-9K:-MdOK6VT5dZT7hIyG-9L:bszo7h5) ([raw file](https://github.com/batfish/batfish/blob/5d85b576d0fae48cf1176708d0c098c2f8e6955c/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L2249)):*
> ```
> vendorStructureId
> ```
This is linking to the route map itself, right? We usually use links for references to other things, like prefix lists etc. We should allow navigating to the definition of the traced route map separately.

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 7 of 13 files at r1, 1 of 2 files at r2, 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7109)* status: all files reviewed, 2 unresolved discussions (waiting on @ratulm)

___
*[projects/batfish/src/test/java/org/batfish/representation/cisco/CiscoConfigurationTest.java, line 41 at r3](https://reviewable.io/reviews/batfish/batfish/7109#-MdOi4ck5-T7UyLzZwFe:-MdOi4cl9jMZQfs79acI:b-zc19ct) ([raw file](https://github.com/batfish/batfish/blob/5d85b576d0fae48cf1176708d0c098c2f8e6955c/projects/batfish/src/test/java/org/batfish/representation/cisco/CiscoConfigurationTest.java#L41)):*
> ```
> contains(not(instanceOf(TraceableStatement.class)))
> ```
aren't we expecting this to be empty? or are putting the rest of the routemap into the else branch?

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7109)* status: 10 of 14 files reviewed, 2 unresolved discussions (waiting on @anothermattbrown)

___
*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 2249 at r3](https://reviewable.io/reviews/batfish/batfish/7109#-MdOK6VT5dZT7hIyG-9K:-MdOoSQ57GYMN3Bl_xiZ:bi73rwr) ([raw file](https://github.com/batfish/batfish/blob/5d85b576d0fae48cf1176708d0c098c2f8e6955c/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L2249)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

> ```
> vendorStructureId
> ```
This is linking to the route map itself, right? We usually use links for references to other things, like prefix lists etc. We should allow navigating to the definition of the traced route map separately.
</blockquote></details>

Yes, it was. I changed to link to route-map-clause. 

(Linking to things like prefix-lists would happen when we do deeper tracing that includes match statements. Currently, it is just clause level.)
___
*[projects/batfish/src/test/java/org/batfish/representation/cisco/CiscoConfigurationTest.java, line 41 at r3](https://reviewable.io/reviews/batfish/batfish/7109#-MdOi4ck5-T7UyLzZwFe:-MdOopTxDwChhvWex3Ek:bpqb32x) ([raw file](https://github.com/batfish/batfish/blob/5d85b576d0fae48cf1176708d0c098c2f8e6955c/projects/batfish/src/test/java/org/batfish/representation/cisco/CiscoConfigurationTest.java#L41)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

> ```
> contains(not(instanceOf(TraceableStatement.class)))
> ```
aren't we expecting this to be empty? or are putting the rest of the routemap into the else branch?
</blockquote></details>

ios conversion is putting the rest of routemap in the else branch

**Comment by ratulm** [comment]
Need some fix-ups before this is ready

**Comment by ratulm** [comment]
Ok, ready again.

**Pull request merged**
