### PR TITLE
FRR: implement route-map match ip address prefix-len

### PR DESCRIPTION
**Pull request by dhalperi**

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6617)* status: 0 of 9 files reviewed, all discussions resolved (waiting on @arifogel and @ratulm)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrr_common.g4, line 35 at r2](https://reviewable.io/reviews/batfish/batfish/6617#-MTCg8P00N5aBiXsbbaM:-MTCg8P145IX_7jWD0fN:bhyp9be) ([raw file](https://github.com/batfish/batfish/blob/70e94415f9b9db1221436a56ad5107dada1baba7/projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrr_common.g4#L35)):*
> ```
> ip_prefix_length
> ```
FYI moved here from FRR_prefix_list.g4, renamed to be less context-specific, and expanded to include 0. I checked.
___
*[projects/batfish/src/main/java/org/batfish/grammar/cumulus_frr/CumulusFrrConfigurationBuilder.java, line 382 at r2](https://reviewable.io/reviews/batfish/batfish/6617#-MTCgNTO39-qT1dIdRzc:-MTCgNTO39-qT1dIdRzd:b-jk1qp5) ([raw file](https://github.com/batfish/batfish/blob/70e94415f9b9db1221436a56ad5107dada1baba7/projects/batfish/src/main/java/org/batfish/grammar/cumulus_frr/CumulusFrrConfigurationBuilder.java#L382)):*
<details><summary><i alt="summary">Quoted 18 lines of code…</i></summary>

> ```
>   /**
>    * Convert a {@link ParserRuleContext} whose text is guaranteed to represent a valid signed 32-bit
>    * decimal integer to an {@link Integer} if it is contained in the provided {@code space}, or else
>    * {@link Optional#empty}.
>    */
>   private @Nonnull Optional<Integer> toIntegerInSpace(
>       ParserRuleContext messageCtx, ParserRuleContext ctx, IntegerSpace space, String name) {
>     int num = Integer.parseInt(ctx.getText());
>     if (!space.contains(num)) {
>       _w.addWarning(
>           messageCtx,
>           getFullText(messageCtx),
>           _parser,
>           String.format("Expected %s in range %s, but got '%d'", name, space, num));
>       return Optional.empty();
>     }
>     return Optional.of(num);
>   }
> ```
</details>


FYI: brought all this over from NX-OS.

**Review by arifogel — COMMENTED** [review]
> Reviewed 9 of 9 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6617)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi and @ratulm)

___
*[projects/batfish/src/main/java/org/batfish/representation/cumulus/RouteMapEntry.java, line 55 at r1](https://reviewable.io/reviews/batfish/batfish/6617#-MTChuxZ4t9OMdpsdHKN:-MTChuxZ4t9OMdpsdHKO:b-p1t4sm) ([raw file](https://github.com/batfish/batfish/blob/5ca23927fbdc99f56b5ad9d8676db3ad4e36369c/projects/batfish/src/main/java/org/batfish/representation/cumulus/RouteMapEntry.java#L55)):*
> ```Java
> 
>   /** Return stream of match statements for this entry. */
>   public @Nonnull Stream<RouteMapMatch> getMatches() {
> ```

Don't you need to modify this function?

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6617)* status: 8 of 10 files reviewed, all discussions resolved (waiting on @arifogel and @ratulm)

___
*[projects/batfish/src/main/java/org/batfish/representation/cumulus/RouteMapEntry.java, line 55 at r1](https://reviewable.io/reviews/batfish/batfish/6617#-MTChuxZ4t9OMdpsdHKN:-MTCirrJ6hOXBmBNzG6A:bhrwqo9) ([raw file](https://github.com/batfish/batfish/blob/5ca23927fbdc99f56b5ad9d8676db3ad4e36369c/projects/batfish/src/main/java/org/batfish/representation/cumulus/RouteMapEntry.java#L55)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Don't you need to modify this function?
</blockquote></details>

Good catch!

I added it to the existing tests in the same way.

**Review by arifogel — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6617)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ratulm)

**Pull request merged**
