### PR TITLE
Adding support to use Security Groups IDs as source or dest in Inbound/Outbound rules

### PR DESCRIPTION
**Pull request by haverma**
- Moved out conversion of SG to ACLs from the individual `toConfigurationNode` methods as we will need all associations of SGs -> IPs to populate ACLs, and for some AWS constructs(Database instances) we generate IPs on the fly. 

- Use SG->IP mapping to populate Dest/Src for IP Permissions

- Testing this in RDS and ES as that will cover the changed code

### CODE REVIEW

**Comment by dhalperi** [comment]
Reviewed 4 of 17 files at r1, 1 of 2 files at r2.
Review status: 5 of 19 files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish/src/main/java/org/batfish/representation/aws/Instance.java, line 247 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1113#-L8rkw_Q50JLxkNZI8ke:-L8rkw_Q50JLxkNZI8kf:ba1psjx) ([raw file](https://github.com/batfish/batfish/blob/f0720a6824083ae15b27c91b34c80a962620d3db/projects/batfish/src/main/java/org/batfish/representation/aws/Instance.java#L247)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

>     for (String sGroupId : _securityGroups) {
>       SecurityGroup sGroup = region.getSecurityGroups().get(sGroupId);
>       if (sGroup == null) {
>         warnings.pedantic(
>             String.format(
>                 "Security group \"%s\" for instance \"%s\" not found", sGroupId, _instanceId));
>         continue;
>       }
</details>
>  
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

>       Set<SecurityGroup> securityGroups =
>           region
>               .getConfigurationSecurityGroups()
>               .computeIfAbsent(cfgNode.getName(), k -> new HashSet<>());
>       securityGroups.add(sGroup);
</details>
>  
<details><summary><i alt="summary">Quoted 12 lines of code…</i></summary>

>       sGroup
>           .getUsersIpSpace()
>           .addAll(
>               cfgNode
>                   .getInterfaces()
>                   .values()
>                   .stream()
>                   .flatMap(iface -> iface.getAllAddresses().stream())
>                   .map(InterfaceAddress::getIp)
>                   .map(IpWildcard::new)
>                   .collect(ImmutableSet.toImmutableSet()));
>     }
</details>

This logic seems duplicated in every file. Can you reduce the reuse?

---

*[projects/batfish/src/main/java/org/batfish/representation/aws/IpPermissions.java, line 91 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1113#-L8rm8pTEWQzRKPRpq0l:-L8rln50EywydP68SlKE:b-l2ayd7) ([raw file](https://github.com/batfish/batfish/blob/f0720a6824083ae15b27c91b34c80a962620d3db/projects/batfish/src/main/java/org/batfish/representation/aws/IpPermissions.java#L91)):*
> ```Java
>     ImmutableSortedSet.Builder<IpWildcard> ipWildcardBuilder =
>         new ImmutableSortedSet.Builder<>(Comparator.naturalOrder());
>     ipWildcardBuilder.addAll(_ipRanges.stream().map(IpWildcard::new).collect(Collectors.toSet()));
> ```

seems weird to build a set to pass to addAll. Why not just use `.forEach(ipWildCardBuilder::add)`?

---

*[projects/batfish/src/main/java/org/batfish/representation/aws/IpPermissions.java, line 111 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1113#-L8rowIVCGRY6p7v46DO:-L8rowIVCGRY6p7v46DP:b-11e1i4) ([raw file](https://github.com/batfish/batfish/blob/f0720a6824083ae15b27c91b34c80a962620d3db/projects/batfish/src/main/java/org/batfish/representation/aws/IpPermissions.java#L111)):*
>             .filter(sg -> region.getSecurityGroups().containsKey(sg))
>             .flatMap(sg -> region.getSecurityGroups().get(sg).getUsersIpSpace().stream())
>             .collect(Collectors.toSet()));

clean up this logic, to reduce the `containsKey -> get`. Just do a map using get and then filter != null.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1113)*

**Comment by dhalperi** [comment]
*[projects/batfish/src/main/java/org/batfish/representation/aws/Region.java, line 33 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1113#-L8rs7vl6w3wBp_6U1c6:-L8rs7vl6w3wBp_6U1c7:b-diofvu) ([raw file](https://github.com/batfish/batfish/blob/f0720a6824083ae15b27c91b34c80a962620d3db/projects/batfish/src/main/java/org/batfish/representation/aws/Region.java#L33)):*
> ```Java
>   private Map<String, Address> _addresses = new HashMap<>();
> 
>   private Map<String, Set<SecurityGroup>> _configurationSecurityGroups = new HashMap<>();
> ```

Isn't this map backwards? Finally, shouldn't it be security group -> what nodes use it?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1113)*

**Comment by haverma** [comment]
Review status: 4 of 20 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/java/org/batfish/representation/aws/Instance.java, line 247 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1113#-L8rkw_Q50JLxkNZI8ke:-L8sJ_p8-o9atD7cKZeZ:bnig9qh) ([raw file](https://github.com/batfish/batfish/blob/f0720a6824083ae15b27c91b34c80a962620d3db/projects/batfish/src/main/java/org/batfish/representation/aws/Instance.java#L247)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

>     for (String sGroupId : _securityGroups) {
>       SecurityGroup sGroup = region.getSecurityGroups().get(sGroupId);
>       if (sGroup == null) {
>         warnings.pedantic(
>             String.format(
>                 "Security group \"%s\" for instance \"%s\" not found", sGroupId, _instanceId));
>         continue;
>       }
>  
>       Set<SecurityGroup> securityGroups =
>           region
>               .getConfigurationSecurityGroups()
>               .computeIfAbsent(cfgNode.getName(), k -> new HashSet<>());
>       securityGroups.add(sGroup);
>  
>       sGroup
>           .getUsersIpSpace()
>           .addAll(
>               cfgNode
>                   .getInterfaces()
>                   .values()
>                   .stream()
>                   .flatMap(iface -> iface.getAllAddresses().stream())
>                   .map(InterfaceAddress::getIp)
>                   .map(IpWildcard::new)
>                   .collect(ImmutableSet.toImmutableSet()));
>     }

This logic seems duplicated in every file. Can you reduce the reuse?
</blockquote></details>

separated in `Utils` method

---

*[projects/batfish/src/main/java/org/batfish/representation/aws/IpPermissions.java, line 91 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1113#-L8rm8pTEWQzRKPRpq0l:-L8sJO745lQljkMqhgbK:b-htjlaf) ([raw file](https://github.com/batfish/batfish/blob/f0720a6824083ae15b27c91b34c80a962620d3db/projects/batfish/src/main/java/org/batfish/representation/aws/IpPermissions.java#L91)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

seems weird to build a set to pass to addAll. Why not just use `.forEach(ipWildCardBuilder::add)`?
</blockquote></details>

changed and moved the same logic to a method `collectIpWildCards`

---

*[projects/batfish/src/main/java/org/batfish/representation/aws/IpPermissions.java, line 111 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1113#-L8rowIVCGRY6p7v46DO:-L8sMlcp5n4ITEPvjk9m:b-28bs46) ([raw file](https://github.com/batfish/batfish/blob/f0720a6824083ae15b27c91b34c80a962620d3db/projects/batfish/src/main/java/org/batfish/representation/aws/IpPermissions.java#L111)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

>             .filter(sg -> region.getSecurityGroups().containsKey(sg))
>             .flatMap(sg -> region.getSecurityGroups().get(sg).getUsersIpSpace().stream())
>             .collect(Collectors.toSet()));

clean up this logic, to reduce the `containsKey -> get`. Just do a map using get and then filter != null.
</blockquote></details>

cleaned and moved to `collectIpWildCards`

---

*[projects/batfish/src/main/java/org/batfish/representation/aws/Region.java, line 33 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1113#-L8rs7vl6w3wBp_6U1c6:-L8sOvo8CaNbonE8WQxv:b-k442vd) ([raw file](https://github.com/batfish/batfish/blob/f0720a6824083ae15b27c91b34c80a962620d3db/projects/batfish/src/main/java/org/batfish/representation/aws/Region.java#L33)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Isn't this map backwards? Finally, shouldn't it be security group -> what nodes use it?
</blockquote></details>

the Mapping of security group-> (Ips of nodes using it) is stored in `SecurityGroup#_userIpSpace`, but this mapping is between Configuration and the security groups applied on it, it is needed to do a conversion of SG to ACLs for each node after we form the node config object for all instances. This will be done when we have config object for all nodes, Security Group is not a part of the V.I model for a node

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1113)*

**Comment by dhalperi** [comment]
Reviewed 8 of 17 files at r1, 1 of 2 files at r2, 6 of 7 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish/src/main/java/org/batfish/representation/aws/Region.java, line 69 at r4](https://beta.reviewable.io/reviews/batfish/batfish/1113#-L8sPTRODhHDlWyXrm_f:-L8sPTRODhHDlWyXrm_g:b-ara3gz) ([raw file](https://github.com/batfish/batfish/blob/a5a4530d29c1de7b0246d84da7faa140620819e7/projects/batfish/src/main/java/org/batfish/representation/aws/Region.java#L69)):*
> ```Java
> 
>   public static String SG_INGRESS_ACL_NAME = "~SECURITY_GROUP_INGRESS_ACL~";
>   public static String SG_EGRESS_ACL_NAME = "~SECURITY_GROUP_EGRESS_ACL~";
> ```

should be public static `final`, right? Do you want this string to be modifiable?

---

*[projects/batfish/src/main/java/org/batfish/representation/aws/Utils.java, line 47 at r4](https://beta.reviewable.io/reviews/batfish/batfish/1113#-L8soDeP77ntRvsutfha:-L8soDeP77ntRvsutfhb:bwyxmoh) ([raw file](https://github.com/batfish/batfish/blob/a5a4530d29c1de7b0246d84da7faa140620819e7/projects/batfish/src/main/java/org/batfish/representation/aws/Utils.java#L47)):*
> ```Java
>   }
> 
>   public static void processSecurityGroups(
> ```

Javadoc

---

*[projects/batfish/src/main/java/org/batfish/representation/aws/Utils.java, line 69 at r4](https://beta.reviewable.io/reviews/batfish/batfish/1113#-L8soIkv7ymkdmLSZh0y:-L8soIkv7ymkdmLSZh0z:b-lycezj) ([raw file](https://github.com/batfish/batfish/blob/e75e1f0c870c03a21d610e3ad9fca85dd7221331/projects/batfish/src/main/java/org/batfish/representation/aws/Utils.java#L69)):*
> ```Java
>   }
> 
>   private Utils() {}
> ```

Why delete this? This prevents the user from instantiating this class, which I think we want.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1113)*

**Comment by haverma** [comment]
Review status: 18 of 20 files reviewed at latest revision, 3 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/representation/aws/Region.java, line 69 at r4](https://beta.reviewable.io/reviews/batfish/batfish/1113#-L8sPTRODhHDlWyXrm_f:-L8tQead0Xit6Rw6f9vF:b-crrqz1) ([raw file](https://github.com/batfish/batfish/blob/a5a4530d29c1de7b0246d84da7faa140620819e7/projects/batfish/src/main/java/org/batfish/representation/aws/Region.java#L69)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

should be public static `final`, right? Do you want this string to be modifiable?
</blockquote></details>

Yes, should be final, that was a mistake

---

*[projects/batfish/src/main/java/org/batfish/representation/aws/Utils.java, line 47 at r4](https://beta.reviewable.io/reviews/batfish/batfish/1113#-L8soDeP77ntRvsutfha:-L8tQj6o9er5yoZa5Uxd:b-7tfmjp) ([raw file](https://github.com/batfish/batfish/blob/a5a4530d29c1de7b0246d84da7faa140620819e7/projects/batfish/src/main/java/org/batfish/representation/aws/Utils.java#L47)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Javadoc
</blockquote></details>

added

---

*[projects/batfish/src/main/java/org/batfish/representation/aws/Utils.java, line 69 at r4](https://beta.reviewable.io/reviews/batfish/batfish/1113#-L8soIkv7ymkdmLSZh0y:-L8tQvtj2CApda6ie5T2:bg3zeef) ([raw file](https://github.com/batfish/batfish/blob/e75e1f0c870c03a21d610e3ad9fca85dd7221331/projects/batfish/src/main/java/org/batfish/representation/aws/Utils.java#L69)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Why delete this? This prevents the user from instantiating this class, which I think we want.
</blockquote></details>

I didn't notice the intention, restored

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1113)*

**Comment by dhalperi** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1113#-:-L8urnYO7W7toFgohLpS:bnfp4nl)*

**Pull request merged**
