### PR TITLE
FRR: Names for prefix-lists, access-list, bgp communities can be any

### PR DESCRIPTION
**Pull request by ton31337**
Add `/` as an allowed char for WORD.

Signed-off-by: Donatas Abraitis <donatas.abraitis@gmail.com>

### CODE REVIEW

**Review by ratulm — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7670)* status: all files reviewed, 2 unresolved discussions (waiting on @ton31337)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4, line 840 at r1](https://reviewable.io/reviews/batfish/batfish/7670#-MoFzj0SENsNRCbv6kBk:-MoFzj0SENsNRCbv6kBl:bdbsaz8) ([raw file](https://github.com/batfish/batfish/blob/3fb30de6d4ffdb3b4ead0dc6234f4de3d62dd2ec/projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_frr/CumulusFrrLexer.g4#L840)):*
> ```ANTLR
> F_WordChar
> :
>   [0-9A-Za-z!@#$^*_=+.;:{}/]
> ```

@arifogel - any danger to adding a '/' here?

The crux of the matter is that FRR names can have this character in them. 
___
*[projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java, line 1536 at r1](https://reviewable.io/reviews/batfish/batfish/7670#-MoFzPmaAFEMpfZDcdd8:-MoFzPmaAFEMpfZDcdd9:bkwk3k3) ([raw file](https://github.com/batfish/batfish/blob/3fb30de6d4ffdb3b4ead0dc6234f4de3d62dd2ec/projects/batfish/src/test/java/org/batfish/grammar/cumulus_frr/CumulusFrrGrammarTest.java#L1536)):*
> ```Java
>   @Test
>   public void testCumulusFrrIpPrefixList() {
>     String name = "10.0.0.0/23";
> ```

To ensure that [a-zA-Z] are still accepted, pick something that includes that too?  Or, two separate names/lines in the test.

**Comment by ton31337** [comment]
>To ensure that [a-zA-Z] are still accepted, pick something that includes that too? Or, two separate names/lines in the test.

Something like `IPv6 prefix` as a name would be covered, IMO, sounds good?

**Comment by ratulm** [comment]
> > To ensure that [a-zA-Z] are still accepted, pick something that includes that too? Or, two separate names/lines in the test.
> 
> Something like `IPv6 prefix` as a name would be covered, IMO, sounds good?

Yes.

**Review by skirmis — APPROVED** [review]

**Review by ratulm — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7670)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ton31337)

**Pull request merged**
