### PR TITLE
NXOS: applying prefix-lists for BGP peers

### PR DESCRIPTION
**Pull request by sfraint**
Add support for inbound and outbound `prefix-list`s associated with BGP neighbors.

Not yet handling the case where both `route-map` and `prefix-list` are defined (just using the `route-map` in this case, for now).

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 3 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6987)* status: 3 of 6 files reviewed, 4 unresolved discussions (waiting on @corinaminer and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/Conversions.java, line 730 at r1](https://reviewable.io/reviews/batfish/batfish/6987#-M_24NIDEE0bGpcwApFy:-M_24NIE0_Rw88Pp3dmn:b-on6owz) ([raw file](https://github.com/batfish/batfish/blob/499a711f248e0bde0c0a3a5bc989287d588bbf4b/projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/Conversions.java#L730)):*
> ```Java
> 
>     // Use inbound route-map or prefix-list if set
>     if (routeMap == null && prefixList != null) {
> ```

nit: more concise and easier to follow if you use if..else if.. else if.. else chain.
Then things like `routeMap == null` here will be unnecessary.
In each branch, can comment about the nulls if desired.
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/Conversions.java, line 733 at r1](https://reviewable.io/reviews/batfish/batfish/6987#-M_24Wp_EVEM57_Wnqua:-M_24Wp_EVEM57_Wnqub:bsk2n6z) ([raw file](https://github.com/batfish/batfish/blob/499a711f248e0bde0c0a3a5bc989287d588bbf4b/projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/Conversions.java#L733)):*
> ```Java
>       ret.addStatement(
>           new If(
>               new MatchPrefixSet(DestinationNetwork.instance(), new NamedPrefixSet(prefixList)),
> ```

What happens for undefined prefix list? Crash on DP?
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/Conversions.java, line 741 at r1](https://reviewable.io/reviews/batfish/batfish/6987#-M_24tdX0Oj_VLYKs5-G:-M_24tdX0Oj_VLYKs5-H:b18z927) ([raw file](https://github.com/batfish/batfish/blob/499a711f248e0bde0c0a3a5bc989287d588bbf4b/projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/Conversions.java#L741)):*
> ```Java
>     }
>     // Accept everything if neither is set
>     if (routeMap == null && prefixList == null) {
> ```

nit: More concise: use if..else if..else if..else for all of this.
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/Conversions.java, line 806 at r1](https://reviewable.io/reviews/batfish/batfish/6987#-M_25xCM-QFjhqAGcjLF:-M_25xCM-QFjhqAGcjLG:b-js0iik) ([raw file](https://github.com/batfish/batfish/blob/499a711f248e0bde0c0a3a5bc989287d588bbf4b/projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/Conversions.java#L806)):*
> ```Java
>               + " only the route-map will be used.");
>     }
>     if (outboundMap == null && outboundPrefixList != null) {
> ```

Can you move the `outboundMap != null` branch here, and use if..else if..else chain? Will be easier to follow.

Same applies to `getExportStatementsForIpv4`

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6987)* status: 3 of 6 files reviewed, 4 unresolved discussions (waiting on @corinaminer and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/Conversions.java, line 806 at r1](https://reviewable.io/reviews/batfish/batfish/6987#-M_25xCM-QFjhqAGcjLF:-M_26bWiAqiVTlya9eKM:byexlwu) ([raw file](https://github.com/batfish/batfish/blob/499a711f248e0bde0c0a3a5bc989287d588bbf4b/projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/Conversions.java#L806)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Can you move the `outboundMap != null` branch here, and use if..else if..else chain? Will be easier to follow.

Same applies to `getExportStatementsForIpv4`
</blockquote></details>

Actually since it looks like you are using outboundMap in 2 cases, maybe toss the warning nested in `outboundMap != null` case.

**Review by arifogel — COMMENTED** [review]
> Reviewed 3 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6987)* status: all files reviewed, 5 unresolved discussions (waiting on @corinaminer and @sfraint)

___
*[projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_bgp_peer_prefix_list, line 23 at r1](https://reviewable.io/reviews/batfish/batfish/6987#-M_27JSy4WTReG3sOe1t:-M_27JSy4WTReG3sOe1u:b-aad8x6) ([raw file](https://github.com/batfish/batfish/blob/499a711f248e0bde0c0a3a5bc989287d588bbf4b/projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_bgp_peer_prefix_list#L23)):*
> ```
>   neighbor 192.168.0.2 remote-as 65002
>     address-family ipv4 unicast
>       prefix-list PREFIX_LIST_1 in
> ```

If you use the same prefix-list for in and out, your tests will not show whether you've properly implemented all the right things for each direction.

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6987)* status: 3 of 6 files reviewed, 5 unresolved discussions (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/Conversions.java, line 730 at r1](https://reviewable.io/reviews/batfish/batfish/6987#-M_24NIDEE0bGpcwApFy:-M_2M5jy987OzwcYIUhd:bvnrpcm) ([raw file](https://github.com/batfish/batfish/blob/499a711f248e0bde0c0a3a5bc989287d588bbf4b/projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/Conversions.java#L730)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

nit: more concise and easier to follow if you use if..else if.. else if.. else chain.
Then things like `routeMap == null` here will be unnecessary.
In each branch, can comment about the nulls if desired.
</blockquote></details>

updated
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/Conversions.java, line 733 at r1](https://reviewable.io/reviews/batfish/batfish/6987#-M_24Wp_EVEM57_Wnqua:-M_2bTU22ZJ7Wmgghk-6:b-11ibnx) ([raw file](https://github.com/batfish/batfish/blob/499a711f248e0bde0c0a3a5bc989287d588bbf4b/projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/Conversions.java#L733)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

What happens for undefined prefix list? Crash on DP?
</blockquote></details>

previously, undefined prefix lists would result in no match - which I just confirmed is _not_ device behavior

updated to match device behavior, where using an undefined prefix-list means permit (which is apparently the the same behavior as referencing an undefined prefix-list from within a route-map)
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/Conversions.java, line 741 at r1](https://reviewable.io/reviews/batfish/batfish/6987#-M_24tdX0Oj_VLYKs5-G:-M_2VNWkEJ6ZLpT-pCZa:b-u0rrzq) ([raw file](https://github.com/batfish/batfish/blob/499a711f248e0bde0c0a3a5bc989287d588bbf4b/projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/Conversions.java#L741)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

nit: More concise: use if..else if..else if..else for all of this.
</blockquote></details>

updated, similar to suggestion
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/Conversions.java, line 806 at r1](https://reviewable.io/reviews/batfish/batfish/6987#-M_25xCM-QFjhqAGcjLF:-M_2K68nDJ5MP7T-avGX:b-p6bue) ([raw file](https://github.com/batfish/batfish/blob/499a711f248e0bde0c0a3a5bc989287d588bbf4b/projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/Conversions.java#L806)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Actually since it looks like you are using outboundMap in 2 cases, maybe toss the warning nested in `outboundMap != null` case.
</blockquote></details>

updated, how's that?
___
*[projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_bgp_peer_prefix_list, line 23 at r1](https://reviewable.io/reviews/batfish/batfish/6987#-M_27JSy4WTReG3sOe1t:-M_2KHvBECY6b3hKiDxa:bs77itd) ([raw file](https://github.com/batfish/batfish/blob/499a711f248e0bde0c0a3a5bc989287d588bbf4b/projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_bgp_peer_prefix_list#L23)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

If you use the same prefix-list for in and out, your tests will not show whether you've properly implemented all the right things for each direction.
</blockquote></details>

true, split into two prefix-lists

**Review by arifogel — COMMENTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6987)* status: all files reviewed, 1 unresolved discussion (waiting on @corinaminer and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/Conversions.java, line 748 at r2](https://reviewable.io/reviews/batfish/batfish/6987#-M_2tPr44ipl32GStTYM:-M_2tPr44ipl32GStTYN:b9t7i08) ([raw file](https://github.com/batfish/batfish/blob/a0d38d44bf20695c0b91bcfc0867aaf1cb331514/projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/Conversions.java#L748)):*
> ```Java
>    */
>   private static Statement getPrefixListStatement(
>       Configuration c, String prefixList, boolean fallThrough) {
> ```

Does `fallThrough` make a difference? I'm not seeing how this is properly exercised by your tests. It looks like you call it with two different values, but the tests look symmetric.

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6987)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/Conversions.java, line 748 at r2](https://reviewable.io/reviews/batfish/batfish/6987#-M_2tPr44ipl32GStTYM:-M_2ykoe4sBDE8Lxrfe2:biwjfzb) ([raw file](https://github.com/batfish/batfish/blob/a0d38d44bf20695c0b91bcfc0867aaf1cb331514/projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/Conversions.java#L748)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

its the same logic as before, but not explicitly tested - I can update the test
</blockquote></details>

actually, I don't think fall-through is needed

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6987)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/Conversions.java, line 748 at r2](https://reviewable.io/reviews/batfish/batfish/6987#-M_2tPr44ipl32GStTYM:-M_2ywtw9fprNb_zF5dl:bj7m3rl) ([raw file](https://github.com/batfish/batfish/blob/a0d38d44bf20695c0b91bcfc0867aaf1cb331514/projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/Conversions.java#L748)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

actually, I don't think fall-through is needed
</blockquote></details>

(updated)

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6987)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

**Review by corinaminer — COMMENTED** [review]
> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6987)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

**Pull request merged**
