### PR TITLE
interface properties

### PR DESCRIPTION
**Pull request by ratulm**
Code to pull out interface properties, modeled like that for node properties. In the process, factored out the shared logic in their propertyspecifier and answerer. Also added Double Schema to accommodate an interface property.

### CODE REVIEW

**Comment by dhalperi** [comment]
Review status: 5 of 15 files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/InterfacePropertySpecifier.java, line 22 at r1](https://reviewable.io/reviews/batfish/batfish/1568#-LE-m5ol5RqLHXihUVPH:-LE-m5ol5RqLHXihUVPI:bq25zi9) ([raw file](https://github.com/batfish/batfish/blob/8b186eea0b38a955f5a2850536578d7b806909a1/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/InterfacePropertySpecifier.java#L22)):*
> ```
>  *   <li>ntp-servers —> gets NTP servers using a configured Java function
>  *   <li>ntp.* gets all properties that start with 'ntp'
> ```

worth updating for Interface?

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/PropertySpecifier.java, line 71 at r1](https://reviewable.io/reviews/batfish/batfish/1568#-LE-mcxtEio5C3qkPsL0:-LE-mcxtEio5C3qkPsL1:bqkcb4f) ([raw file](https://github.com/batfish/batfish/blob/8b186eea0b38a955f5a2850536578d7b806909a1/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/PropertySpecifier.java#L71)):*
> ```
>           Constructor<?> constructor = childClass.getConstructor(String.class);
>           PropertySpecifier instance = (PropertySpecifier) constructor.newInstance(queryWithStars);
> ```

`this` is already an instance of the given class. do we need this reflection? Why isn't it something like `this.getMatchingProperties(queryWithStars)`?

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/Row.java, line 177 at r1](https://reviewable.io/reviews/batfish/batfish/1568#-LE09paj-vomztKpaPHu:-LE09paj-vomztKpaPHv:b-uxxp8z) ([raw file](https://github.com/batfish/batfish/blob/8b186eea0b38a955f5a2850536578d7b806909a1/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/Row.java#L177)):*
> ```
> isNull()
> ```

what's the scenario where this happens?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1568)*

**Comment by ratulm** [comment]
Review status: 5 of 15 files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/PropertySpecifier.java, line 71 at r1](https://reviewable.io/reviews/batfish/batfish/1568#-LE-mcxtEio5C3qkPsL0:-LE0CyKIE6YeL4Sscel_:bfca588) ([raw file](https://github.com/batfish/batfish/blob/6f507c32b9ac2baebab8fe8c73ff2c4cf3abfafc/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/PropertySpecifier.java#L71)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
>           Constructor<?> constructor = childClass.getConstructor(String.class);
>           PropertySpecifier instance = (PropertySpecifier) constructor.newInstance(queryWithStars);
> ```

`this` is already an instance of the given class. do we need this reflection? Why isn't it something like `this.getMatchingProperties(queryWithStars)`?
</blockquote></details>

its a static function, so no  `this`.  

this whole bit is ugly I admit. another option is to move the functionality of generating the instance (along with generating queryWithStars and checking for the safety of the pattern) to child classes.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/Row.java, line 177 at r1](https://reviewable.io/reviews/batfish/batfish/1568#-LE09paj-vomztKpaPHu:-LE0Emne2u89PVTah6ek:bkgoqq4) ([raw file](https://github.com/batfish/batfish/blob/6f507c32b9ac2baebab8fe8c73ff2c4cf3abfafc/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/Row.java#L177)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> isNull()
> ```

what's the scenario where this happens?
</blockquote></details>

When you insert null in the Row, Jackson converts that to `NullNode` which is not `null`. It is the first part of the disjunction that is not necessary given the check right above it. Removed that.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1568)*

**Comment by ratulm** [comment]
Ping on this PR, @dhalperi

**Comment by dhalperi** [comment]
Oh it looked like you had asked @corinaminer to review it. Remove her?

**Comment by ratulm** [comment]
It was originally an anycast. But since you started doing it, I suppose she didn't think she needed to. Removing her.

**Comment by dhalperi** [comment]
Reviewed 4 of 15 files at r1, 13 of 13 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/PropertySpecifier.java, line 71 at r1](https://reviewable.io/reviews/batfish/batfish/1568#-LE-mcxtEio5C3qkPsL0:-LET13ma9ij534SBxwyB:b-93je5v) ([raw file](https://github.com/batfish/batfish/blob/6f507c32b9ac2baebab8fe8c73ff2c4cf3abfafc/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/PropertySpecifier.java#L71)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

its a static function, so no  `this`.  

this whole bit is ugly I admit. another option is to move the functionality of generating the instance (along with generating queryWithStars and checking for the safety of the pattern) to child classes.
</blockquote></details>

Can you not just use the pattern and the `allProperties` list and skip the entire creation of new instance?

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/PropertySpecifier.java, line 77 at r3](https://reviewable.io/reviews/batfish/batfish/1568#-LET11gU4e6ct2U6BeEw:-LET11gU4e6ct2U6BeEx:b-wybsau) ([raw file](https://github.com/batfish/batfish/blob/6ed9b4d1ad3f9536a9694b340181470e79cbfe6b/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/PropertySpecifier.java#L77)):*
> ```Java
>             | IllegalAccessException
>             | InvocationTargetException e) {
>           // do nothing
> ```

at least log?

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/PropertySpecifier.java, line 83 at r3](https://reviewable.io/reviews/batfish/batfish/1568#-LET20uy9xHhB-N-WU4V:-LET20uzEFVpBPTJFCNf:b-bl74hn) ([raw file](https://github.com/batfish/batfish/blob/6ed9b4d1ad3f9536a9694b340181470e79cbfe6b/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/PropertySpecifier.java#L83)):*
> ```Java
>           suggestions.add(
>               new AutocompleteSuggestion(
>                   queryWithStars, true, "All properties matching regex " + queryWithStars));
> ```

actually, I'm currently confused about this code altogether. I thought that suggestions is supposed to be a list of properties you might be searching for.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/PropertySpecifier.java, line 98 at r3](https://reviewable.io/reviews/batfish/batfish/1568#-LET2IYp3Ztj5d53ZaUz:-LET2IYp3Ztj5d53ZaV-:b2ptz24) ([raw file](https://github.com/batfish/batfish/blob/6ed9b4d1ad3f9536a9694b340181470e79cbfe6b/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/PropertySpecifier.java#L98)):*
> ```Java
>   }
> 
>   public static Object convertTypeIfNeeded(
> ```

document.

Does this need to be public? Shouldn't it be internal to this class only and not accessible even to children?

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/Row.java, line 135 at r3](https://reviewable.io/reviews/batfish/batfish/1568#-LET2seWEJk4GxogZdJp:-LET2seWEJk4GxogZdJq:b-9mrra8) ([raw file](https://github.com/batfish/batfish/blob/6ed9b4d1ad3f9536a9694b340181470e79cbfe6b/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/Row.java#L135)):*
> ```Java
>           String.format(
>               "Cannot recover object of type %s from json %s: %s",
>               valueType.getName(), jsonNode, e.getMessage()));
> ```

why remove the stack trace?

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/Row.java, line 202 at r3](https://reviewable.io/reviews/batfish/batfish/1568#-LET2zRlCOyF46at5p7g:-LET2zRlCOyF46at5p7h:b-9mrra8) ([raw file](https://github.com/batfish/batfish/blob/6ed9b4d1ad3f9536a9694b340181470e79cbfe6b/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/Row.java#L202)):*
> ```Java
>           String.format(
>               "Cannot recover object of type %s from column %s: %s",
>               valueTypeRef.getClass(), columnName, e.getMessage()));
> ```

why remove the stack trace?

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/questions/InterfacePropertySpecifierTest.java, line 23 at r3](https://reviewable.io/reviews/batfish/batfish/1568#-LET3A-sCm-al3xUPQOb:-LET3A-sCm-al3xUPQOc:bnw335j) ([raw file](https://github.com/batfish/batfish/blob/6ed9b4d1ad3f9536a9694b340181470e79cbfe6b/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/questions/InterfacePropertySpecifierTest.java#L23)):*
> ```Java
>             .collect(Collectors.toSet()),
>         equalTo(
>             new ImmutableSet.Builder<String>()
> ```

`ImmutableSet.builder()`

---

*[projects/question/src/main/java/org/batfish/question/interfaceproperties/InterfacePropertiesAnswerer.java, line 46 at r3](https://reviewable.io/reviews/batfish/batfish/1568#-LET3vds1EXnDGSPJzFG:-LET3vds1EXnDGSPJzFH:bdga5lu) ([raw file](https://github.com/batfish/batfish/blob/6ed9b4d1ad3f9536a9694b340181470e79cbfe6b/projects/question/src/main/java/org/batfish/question/interfaceproperties/InterfacePropertiesAnswerer.java#L46)):*
> ```
> new ImmutableList.Builder<ColumnMetadata>()
> ```

ImmutableList.builder()

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1568)*

**Comment by dhalperi** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/Row.java, line 135 at r3](https://reviewable.io/reviews/batfish/batfish/1568#-LET2seWEJk4GxogZdJp:-LEVmIJn6AHUAOTZ-u2d:b-4ctixx) ([raw file](https://github.com/batfish/batfish/blob/6ed9b4d1ad3f9536a9694b340181470e79cbfe6b/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/Row.java#L135)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

why remove the stack trace?
</blockquote></details>

Oh! Based on your change not being what I expected (just `, e`) I went and looked at ClassCastException and saw it doesn't have the `, Throwable` override constructor. Now your change makes much more sense. Ok as-is now or as it was, entirely up to you.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1568#-:-LEVma-j3Ptgq8-owEUO:bnfp4nl)*

**Pull request merged**
