### PR TITLE
IPv6: fix toString

### PR DESCRIPTION
**Pull request by dhalperi**
**Stack**:
- #9248
- #9247
- #9246 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/9246)* status: 0 of 9 files reviewed, all discussions resolved (waiting on @SLarkworthy)

___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Ip6.java` line 50 at r1](https://reviewable.io/reviews/batfish/batfish/9246#-O9B1hRB3ZSYg5qxP9iC:-O9B1hRB3ZSYg5qxP9iD:b-nojdta) ([raw file](https://github.com/batfish/batfish/blob/9cbe8941b37fe0d0303c51b14ce4b34db68c0e31/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Ip6.java#L50)):*
> ```Java
>       remainder = remainder.shiftRight(16);
>     }
> ```

I feel like this should be simplifiable, but you know it wasn't easy to see how.

**Review by SLarkworthy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/9246)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Ip6.java` line 78 at r1](https://reviewable.io/reviews/batfish/batfish/9246#-O9BHCla4c_Kev34yj6C:-O9BHCla4c_Kev34yj6D:bhhvav4) ([raw file](https://github.com/batfish/batfish/blob/b256c87b6bc80bb05b01f4e78377fd636bf6f03a/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Ip6.java#L78)):*
> ```Java
>     }
> 
>     // Handle edge case where the longest sequence is at the end
> ```

Can just move this check to right after you append currentLength and you wouldn't need to handle this case separately.

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/9246)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @SLarkworthy)

___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Ip6.java` line 78 at r1](https://reviewable.io/reviews/batfish/batfish/9246#-O9BHCla4c_Kev34yj6C:-O9BL4yC-hDTtP9nkIBz:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/b256c87b6bc80bb05b01f4e78377fd636bf6f03a/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Ip6.java#L78)):*
<details><summary><i>Previously, SLarkworthy (Sarah Larkworthy) wrote…</i></summary><blockquote>

Can just move this check to right after you append currentLength and you wouldn't need to handle this case separately.
</blockquote></details>

Done.

**Review by SLarkworthy — COMMENTED** [review]
> Reviewed 8 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/9246)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dhalperi)

**Pull request merged**
