### PR TITLE
Only encode ACLs being analyzed for reachability

### PR DESCRIPTION
**Pull request by corinaminer**
Removed `disabledAcls` from project. Instead, builder for `SynthesizerInputImpl` has a field `enabledAclNames`. If this field is set, the resulting synthesizer input encodes only the specified ACLs; if it is not set, the synthesizer input encodes all ACLs as usual.

This new setup makes it much simpler to create ACL synthesizers in Batfish because it's easier to assemble ACL whitelists than blacklists.

Before this gets merged, I want to add tests to prove that the appropriate ACLs are getting encoded. Any ideas on how to capture that information?

### CODE REVIEW

**Comment by arifogel** [comment]
Regarding test: Make an ACL that references an ACL permitting something specific. On the following line of the first ACL, match that same thing. If that latter line is unreachable, you should be satisified the fix is correct.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1376#-:-LCFk7Fs592KPLemc_m8:bh1k7wb)*

**Comment by arifogel** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1376#-LCFneKw90rP2p-SR9JV:-LCFneKw90rP2p-SR9JW:b-yg2w28) (no related file):*
Blocking comment for test

---

*[projects/batfish/src/main/java/org/batfish/z3/SynthesizerInputImpl.java, line 99 at r1](https://reviewable.io/reviews/batfish/batfish/1376#-LCFnOrR749vlg4wQUOj:-LCFnOrR749vlg4wQUOk:b8162q) ([raw file](https://github.com/batfish/batfish/blob/d2f6f5beda73a0cb8180fc6dfec6e17da018c471/projects/batfish/src/main/java/org/batfish/z3/SynthesizerInputImpl.java#L99)):*
> ```Java
>     }
> 
>     public SynthesizerInputImpl build() {
> ```

It's time to change the constructor to just take the builder and set the fields from there. More maintainable, no ridiculous number of arguments to a function.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1376)*

**Comment by corinaminer** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1376#-LCFneKw90rP2p-SR9JV:-LCGCvYE7hLtvNfFUIRB:buszh0) (no related file):*
> Make an ACL that references an ACL permitting something specific. On the following line of the first ACL, match that same thing. If that latter line is unreachable, you should be satisified the fix is correct.

Good idea, will do that. Wasn't exactly what I was looking to test, though. Any ideas for a test that will fail if ACLs not listed in the whitelist still get encoded?

---

*[projects/batfish/src/main/java/org/batfish/z3/SynthesizerInputImpl.java, line 99 at r1](https://reviewable.io/reviews/batfish/batfish/1376#-LCFnOrR749vlg4wQUOj:-LCG9Scx-t64BNlF0fU-:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/d2f6f5beda73a0cb8180fc6dfec6e17da018c471/projects/batfish/src/main/java/org/batfish/z3/SynthesizerInputImpl.java#L99)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

It's time to change the constructor to just take the builder and set the fields from there. More maintainable, no ridiculous number of arguments to a function.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1376)*

**Comment by corinaminer** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/z3/SynthesizerInputImpl.java, line 99 at r1](https://reviewable.io/reviews/batfish/batfish/1376#-LCFnOrR749vlg4wQUOj:-LCGiew2EhfFkhVp-SXg:b-8t89yf) ([raw file](https://github.com/batfish/batfish/blob/d2f6f5beda73a0cb8180fc6dfec6e17da018c471/projects/batfish/src/main/java/org/batfish/z3/SynthesizerInputImpl.java#L99)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Is it OK to have removed the initial values in `Builder()`? Can't that result in NPEs later on?
</blockquote></details>

I'm not aware of any difference between initializing variables in the constructor versus initializing them where they're declared (unless of course the initialization depends on other variables, which none of these do).

In fact this seems slightly safer given the slim possibility that a Builder might someday somehow be initialized without the constructor being called.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1376)*

**Comment by arifogel** [comment]
:lgtm: modulo last test

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1376#-:-LCGmcKm5NoYuLM5zRzD:b-9snzkv)*

**Comment by arifogel** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1376)*

**Comment by anothermattbrown** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1376#-LCFneKw90rP2p-SR9JV:-LCUsjfdCtAbE-HXeK0w:b-f0p0mu) (no related file):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

@anothermattbrown  should be able to help here.
</blockquote></details>

@corinaminer You can write a test that `SynthesizerInputImpl.getAclActions` and `SynthesizerInputImpl.getAclConditions` return maps whose keys contain every/only whitelisted ACLs.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1376)*

**Comment by corinaminer** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1376#-LCFneKw90rP2p-SR9JV:-LCV6OlN-HdgGCZ2asZY:b-896fix) (no related file):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

@corinaminer You can write a test that `SynthesizerInputImpl.getAclActions` and `SynthesizerInputImpl.getAclConditions` return maps whose keys contain every/only whitelisted ACLs.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1376)*

**Comment by arifogel** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1376)*

**Comment by anothermattbrown** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/allinone/src/test/java/org/batfish/allinone/AclReachabilityTest.java, line 141 at r4](https://reviewable.io/reviews/batfish/batfish/1376#-LCVPXBYErLH_QMmCQfC:-LCVPXBYErLH_QMmCQfD:b-682juw) ([raw file](https://github.com/batfish/batfish/blob/8890af2184631483a787ee8c8b59466288bfc569/projects/allinone/src/test/java/org/batfish/allinone/AclReachabilityTest.java#L141)):*
> ```Java
> 
>   @Test
>   public void testCorrectAclsEncoded() throws IOException {
> ```

Looks good. `SynthesizerInputImplTest` may be a better home for this. A better name for this might be `testEnabledAcls`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1376)*

**Comment by anothermattbrown** [comment]
Reviewed 1 of 3 files at r1, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1376)*

**Comment by corinaminer** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/allinone/src/test/java/org/batfish/allinone/AclReachabilityTest.java, line 141 at r4](https://reviewable.io/reviews/batfish/batfish/1376#-LCVPXBYErLH_QMmCQfC:-LCVSvL6Bd82K7dJacIE:bx4nh62) ([raw file](https://github.com/batfish/batfish/blob/8890af2184631483a787ee8c8b59466288bfc569/projects/allinone/src/test/java/org/batfish/allinone/AclReachabilityTest.java#L141)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

Looks good. `SynthesizerInputImplTest` may be a better home for this. A better name for this might be `testEnabledAcls`.
</blockquote></details>

Done and done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1376)*

**Comment by arifogel** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1376)*

**Comment by anothermattbrown** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1376#-:-LCVUO0e7Tzxxr74FHN8:bnfp4nl)*

**Comment by anothermattbrown** [comment]
Reviewed 1 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1376)*

**Comment by anothermattbrown** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1376)*

**Pull request merged**
