### PR TITLE
Juniper: support ospf area interface metric

### PR DESCRIPTION
**Pull request by dhalperi**
* Fix inheritance (inverted condition on whether inheritance had been performed)
* Add parsing for metric configuration for an ospf area interface
* Add inheritance of ospf cost and ospf area
* Rename parameter in setOspfCost
* and test with new matchers and everthing.

### CODE REVIEW

**Comment by dhalperi** [comment]
Re inheritance break, the bug was introduced in https://github.com/batfish/batfish/commit/47e282393922cd9172facfbb52d5dce61c539eeb#diff-17db06163ef18e1161020de26c98df75L233 and Batfish 0.33.0

**Comment by arifogel** [comment]
:lgtm: with minor suggestions

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/InterfaceMatchersImpl.java, line 39 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1035#-L70z8SfD7dnW-7Gxe2e:-L70z8SfD7dnW-7Gxe2f:bae9o85) ([raw file](https://github.com/batfish/batfish/blob/b56a41d30ce6dee7dc2f74a5e94b85240fb100b5/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/InterfaceMatchersImpl.java#L39)):*
> ```Java
>   static final class HasOspfCost extends FeatureMatcher<Interface, Integer> {
>     HasOspfCost(@Nonnull Matcher<? super Integer> subMatcher) {
>       super(subMatcher, "an interface with ospfCost", "ospfCost");
> ```

"an interface with ospfCost" -> "an interface with ospfCost:" is the new style I am trying to apply to all matchers (note the colon on the right).

---

*[projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java, line 178 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1035#-L70zS9SBtzfnKWiOON4:-L70zS9SBtzfnKWiOON5:by7vb7k) ([raw file](https://github.com/batfish/batfish/blob/b56a41d30ce6dee7dc2f74a5e94b85240fb100b5/projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java#L178)):*
> ```Java
> 
>     // Interface override
>     assertThat(config.getInterfaces().get("fe-1/0/1.0"), hasOspfCost(equalTo(17)));
> ```

Personally I would do: `assertThat(config, hasInterface("fe-1/0/1.0", hasOspfCost(equalTo(17))));`, but I'll leave it to your preference.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1035#-:-L71-2FD8-P8bPsjlAxb:b-lyfezr)*

**Comment by dhalperi** [comment]
Review status: 5 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/InterfaceMatchersImpl.java, line 39 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1035#-L70z8SfD7dnW-7Gxe2e:-L718M-i0xeGduYNLNUz:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/39d50dc681e460d8069c0ae886c9fd908cd85519/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/InterfaceMatchersImpl.java#L39)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

"an interface with ospfCost" -> "an interface with ospfCost:" is the new style I am trying to apply to all matchers (note the colon on the right).
</blockquote></details>

Done.

---

*[projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java, line 178 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1035#-L70zS9SBtzfnKWiOON4:-L718Mlw50vjad1Vl_A3:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/39d50dc681e460d8069c0ae886c9fd908cd85519/projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java#L178)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Personally I would do: `assertThat(config, hasInterface("fe-1/0/1.0", hasOspfCost(equalTo(17))));`, but I'll leave it to your preference.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1035)*

**Comment by dhalperi** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1035)*

**Pull request merged**
