### PR TITLE
BDP: implement BGP route VRF leaking

### PR DESCRIPTION
**Pull request by progwriter**
Implements cisco-style VRF leaking using BGP routes in our dataplane. 
To do so, we
1. Create local BGP ribs and allow BDP to redistribute BGP routes into a local RIB even when BGP neighbors are not defined. (long time coming, this is the "classic" mode of operation for BGP across many vendors w/ exception being juniper). Currently this will only be used for VRF leaking.
2. Use these local RIBs (or more precisely, updates to these ribs from the previous round) as well as regular BGP rib deltas to leak BGP routes into neighboring `BgpRoutingProcess`es (if configured, of course)
3. The leaking process updates next hops of leaked routes to the special `NextHopVrf` next hop to ensure that FIBs are built correctly and packets hop VRFs during forwarding.

### CODE REVIEW

**Review by corinaminer — COMMENTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6554)* status: all files reviewed, 9 unresolved discussions (waiting on @progwriter)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java, line 149 at r1](https://reviewable.io/reviews/batfish/batfish/6554#-MQVv5sdAirYd2BdkHp-:-MQVv5sdAirYd2BdkHp0:b-t32v3v) ([raw file](https://github.com/batfish/batfish/blob/36f9d4a03562774587e93d33ec5d561cb8ab489e/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java#L149)):*
> ```Java
>   @Nonnull private Builder<Bgpv4Route> _ebgpv4DeltaBuilder = RibDelta.builder();
>   /**
>    * Keep track of redistributed routes that we have merged into our local RIB).
> ```

nit: stray parenthesis
___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java, line 261 at r1](https://reviewable.io/reviews/batfish/batfish/6554#-MQW-7hl79aTIJxoNAyk:-MQW-7hl79aTIJxoNAyl:b-rk9d6c) ([raw file](https://github.com/batfish/batfish/blob/36f9d4a03562774587e93d33ec5d561cb8ab489e/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java#L261)):*
> ```Java
>     _localBgpv4Rib =
>         new Bgpv4Rib(
>             _mainRib, bestPathTieBreaker, 1, multiPathMatchMode, true, clusterListAsIgpCost);
> ```

how come max paths should always be 1 for this rib?
___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java, line 496 at r1](https://reviewable.io/reviews/batfish/batfish/6554#-MQW9LbR9ln6uU4TN1J8:-MQW9LbR9ln6uU4TN1J9:b-gnb7c1) ([raw file](https://github.com/batfish/batfish/blob/36f9d4a03562774587e93d33ec5d561cb8ab489e/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java#L496)):*
> ```Java
>    * exists
>    */
>   private RibDelta<Bgpv4Route> redistributeRouteToLocalRib(
> ```

This method doesn't really seem necessary. If you resolve the `RoutingPolicy` in the caller, you can call `redistributeRouteToLocalRib(adv, policy)` directly, plus you'll end up resolving the policy once per iteration rather than once per `mainRibDelta` entry.
___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java, line 526 at r1](https://reviewable.io/reviews/batfish/batfish/6554#-MQWBw5C7IVwPcrbQ39P:-MQWBw5D-SUWpY9_i6iW:bh3vavm) ([raw file](https://github.com/batfish/batfish/blob/36f9d4a03562774587e93d33ec5d561cb8ab489e/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java#L526)):*
> ```Java
>             .setNonRouting(true);
>     // Hopefully, the direction should not matter here.
>     boolean accept = policy.process(route, bgpBuilder, OUT);
> ```

It looks like the only direction-dependent routing policy clause is `AutoAs`, which represents this process's AS for outbound traffic and the last AS of the route for inbound traffic. So `OUT` seems like the better option for that case, i think. no idea why you'd want this redistribution policy to mess with the AS path anyway
___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java, line 736 at r1](https://reviewable.io/reviews/batfish/batfish/6554#-MQW0kF--Aw6PaaDIkHg:-MQW0kF--Aw6PaaDIkHh:b2rckle) ([raw file](https://github.com/batfish/batfish/blob/36f9d4a03562774587e93d33ec5d561cb8ab489e/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java#L736)):*
> ```Java
>       Bgpv4Route remoteRoute = remoteRouteAdvert.getRoute();
> 
>       //      LOGGER.debug("{} Processing bgpv4 route {}", _hostname, remoteRoute);
> ```

uncomment or remove
___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java, line 1701 at r1](https://reviewable.io/reviews/batfish/batfish/6554#-MQWFKavB8muZl_N2TpK:-MQWFKawBkQ-xFhZhJdL:bw269t8) ([raw file](https://github.com/batfish/batfish/blob/36f9d4a03562774587e93d33ec5d561cb8ab489e/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java#L1701)):*
> ```Java
>           if (importPolicyName != null) {
>             accept =
>                 _policies.getOrThrow(importPolicyName).processBgpRoute(route, builder, null, IN);
> ```

here as well, why not resolve `importPolicy` outside the `forEach`?
___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java, line 1289 at r1](https://reviewable.io/reviews/batfish/batfish/6554#-MQWJl5C9a9ed8qgscbH:-MQWJl5C9a9ed8qgscbI:b1azyen) ([raw file](https://github.com/batfish/batfish/blob/36f9d4a03562774587e93d33ec5d561cb8ab489e/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java#L1289)):*
> ```Java
>       String importFromVrf = leakConfig.getImportFromVrf();
>       VirtualRouter exportingVR = _node.getVirtualRouterOrThrow(importFromVrf);
>       CrossVrfEdgeId otherVrfToOurRib = new CrossVrfEdgeId(importFromVrf, RibId.DEFAULT_RIB_NAME);
> ```

why move this stuff before short-circuit `if`?
___
*[projects/batfish/src/main/java/org/batfish/dataplane/rib/Bgpv4Rib.java, line 44 at r1](https://reviewable.io/reviews/batfish/batfish/6554#-MQWNonC4AjSKFmY6cU0:-MQWNonC4AjSKFmY6cU1:br6a5vd) ([raw file](https://github.com/batfish/batfish/blob/614c3bf2178044263b26a94d18e72c1cf221dba1/projects/batfish/src/main/java/org/batfish/dataplane/rib/Bgpv4Rib.java#L44)):*
> ```Java
>       However, due to some complications with how we create routes, we must skip this check for:
>       - routes with link-local address as next hop (i.e., next-hop interface is set to something)
>       - routes with Ip.AUTO as next hop or protocol AGGREGATE (for locally-generated routes/aggregates)
> ```

why did this change (why should we now avoid merging routes with next hop `Ip.AUTO`)?
___
*[projects/batfish/src/test/java/org/batfish/dataplane/ibdp/BgpRoutingProcessTest.java, line 568 at r1](https://reviewable.io/reviews/batfish/batfish/6554#-MQWP53S-8qC4qM2f_1N:-MQWP53S-8qC4qM2f_1O:bpzqau7) ([raw file](https://github.com/batfish/batfish/blob/36f9d4a03562774587e93d33ec5d561cb8ab489e/projects/batfish/src/test/java/org/batfish/dataplane/ibdp/BgpRoutingProcessTest.java#L568)):*
> ```Java
> 
>     // Fake up end of round before other test
>     _routingProcess.endOfRound();
> ```

why is this necessary? shouldn't the routing process be unaffected by the above redistribution since the policy denies the route?
___
*[projects/batfish/src/test/java/org/batfish/dataplane/ibdp/BgpRoutingProcessTest.java, line 582 at r1](https://reviewable.io/reviews/batfish/batfish/6554#-MQWPiUR9tzx1Nq4ALaK:-MQWPiUR9tzx1Nq4ALaL:b-h4rk1h) ([raw file](https://github.com/batfish/batfish/blob/36f9d4a03562774587e93d33ec5d561cb8ab489e/projects/batfish/src/test/java/org/batfish/dataplane/ibdp/BgpRoutingProcessTest.java#L582)):*
> ```Java
>         _routingProcess.getV4LocalRoutes(),
>         contains(
>             isBgpv4RouteThat(
> ```

Better to create the complete expected bgp route to make sure all the fields are accounted for correctly. Eg this ought to be nonrouting, right?

Same for cases in the next test where a route is successfully imported.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpProcess.java, line 421 at r1](https://reviewable.io/reviews/batfish/batfish/6554#-MQWM2gT7yG52g2fNOKk:-MQWM2gT7yG52g2fNOKl:b-3md5pt) ([raw file](https://github.com/batfish/batfish/blob/36f9d4a03562774587e93d33ec5d561cb8ab489e/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpProcess.java#L421)):*
> ```Java
>   }
> 
>   public void setRedistributionPolicy(@Nullable String redistributionPolicy) {
> ```

ugh, is it really necessary for `_redistributionPolicy` not to be final?

**Review by progwriter — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6554)* status: all files reviewed, 2 unresolved discussions (waiting on @corinaminer and @progwriter)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java, line 149 at r1](https://reviewable.io/reviews/batfish/batfish/6554#-MQVv5sdAirYd2BdkHp-:-MQYgvW01NWFC5IdkWgX:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/36f9d4a03562774587e93d33ec5d561cb8ab489e/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java#L149)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

nit: stray parenthesis
</blockquote></details>

done
___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java, line 261 at r1](https://reviewable.io/reviews/batfish/batfish/6554#-MQW-7hl79aTIJxoNAyk:-MQYgyoC0YVFJ3KxHKNf:b9pw1vo) ([raw file](https://github.com/batfish/batfish/blob/36f9d4a03562774587e93d33ec5d561cb8ab489e/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java#L261)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

how come max paths should always be 1 for this rib?
</blockquote></details>

good call, fixed
___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java, line 496 at r1](https://reviewable.io/reviews/batfish/batfish/6554#-MQW9LbR9ln6uU4TN1J8:-MQZmJIxAPLuuEH9HdOx:b-64gmm0) ([raw file](https://github.com/batfish/batfish/blob/36f9d4a03562774587e93d33ec5d561cb8ab489e/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java#L496)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

This method doesn't really seem necessary. If you resolve the `RoutingPolicy` in the caller, you can call `redistributeRouteToLocalRib(adv, policy)` directly, plus you'll end up resolving the policy once per iteration rather than once per `mainRibDelta` entry.
</blockquote></details>

sure, simplified.
___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java, line 1701 at r1](https://reviewable.io/reviews/batfish/batfish/6554#-MQWFKavB8muZl_N2TpK:-MQZnAZW5Ic7uxoqS4o9:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/36f9d4a03562774587e93d33ec5d561cb8ab489e/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java#L1701)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

here as well, why not resolve `importPolicy` outside the `forEach`?
</blockquote></details>

done
___
*[projects/batfish/src/main/java/org/batfish/dataplane/rib/Bgpv4Rib.java, line 44 at r1](https://reviewable.io/reviews/batfish/batfish/6554#-MQWNonC4AjSKFmY6cU0:-MQZnC06EiQaKRkVaFMg:by7ut28) ([raw file](https://github.com/batfish/batfish/blob/614c3bf2178044263b26a94d18e72c1cf221dba1/projects/batfish/src/main/java/org/batfish/dataplane/rib/Bgpv4Rib.java#L44)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

why did this change (why should we now avoid merging routes with next hop `Ip.AUTO`)?
</blockquote></details>

After #6545 `Ip.AUTO` is not a valid next hop ip for routes
___
*[projects/batfish/src/test/java/org/batfish/dataplane/ibdp/BgpRoutingProcessTest.java, line 568 at r1](https://reviewable.io/reviews/batfish/batfish/6554#-MQWP53S-8qC4qM2f_1N:-MQZnWxK6oYS37QifyC6:b-ornpyc) ([raw file](https://github.com/batfish/batfish/blob/36f9d4a03562774587e93d33ec5d561cb8ab489e/projects/batfish/src/test/java/org/batfish/dataplane/ibdp/BgpRoutingProcessTest.java#L568)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

why is this necessary? shouldn't the routing process be unaffected by the above redistribution since the policy denies the route?
</blockquote></details>

not really, because process state is still modified e.g., the `_toRedistribute` map for old-style redistribution
___
*[projects/batfish/src/test/java/org/batfish/dataplane/ibdp/BgpRoutingProcessTest.java, line 582 at r1](https://reviewable.io/reviews/batfish/batfish/6554#-MQWPiUR9tzx1Nq4ALaK:-MQZnq5b08LbO7fPb_rO:bf9a5fc) ([raw file](https://github.com/batfish/batfish/blob/36f9d4a03562774587e93d33ec5d561cb8ab489e/projects/batfish/src/test/java/org/batfish/dataplane/ibdp/BgpRoutingProcessTest.java#L582)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Better to create the complete expected bgp route to make sure all the fields are accounted for correctly. Eg this ought to be nonrouting, right?

Same for cases in the next test where a route is successfully imported.
</blockquote></details>

I actually do not care to test properties that aren't crucial, that makes tests harder to maintain. Good call on the non-routing though.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpProcess.java, line 421 at r1](https://reviewable.io/reviews/batfish/batfish/6554#-MQWM2gT7yG52g2fNOKk:-MQZo__BBNQOJiRgujQZ:bqu3snj) ([raw file](https://github.com/batfish/batfish/blob/36f9d4a03562774587e93d33ec5d561cb8ab489e/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpProcess.java#L421)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

ugh, is it really necessary for `_redistributionPolicy` not to be final?
</blockquote></details>

:) 
while i share the same feeling, I wasn't about to start rewriting a bunch of vendor conversion code

**Review by corinaminer — COMMENTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6554)* status: all files reviewed, 1 unresolved discussion (waiting on @progwriter)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java, line 261 at r1](https://reviewable.io/reviews/batfish/batfish/6554#-MQW-7hl79aTIJxoNAyk:-MQ_7atb6x90Bfa9vsHA:bj0buz3) ([raw file](https://github.com/batfish/batfish/blob/36f9d4a03562774587e93d33ec5d561cb8ab489e/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java#L261)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

good call, fixed
</blockquote></details>

all the other ribs have `_process.getMultipathIbgp() ? null : 1` -- is that not appropriate here?
___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java, line 481 at r2](https://reviewable.io/reviews/batfish/batfish/6554#-MQ_7ossB79yht8vzI1P:-MQ_7ossB79yht8vzI1Q:b-aape6z) ([raw file](https://github.com/batfish/batfish/blob/711e371bdcc024f117098871711ca3ca6e97ddd0/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java#L481)):*
> ```Java
>       // Place redistributed routes into our local RIB
>       String policyName = _process.getRedistributionPolicy();
>       assert policyName != null;
> ```

this was just confirmed in the if condition. not even really necessary to define `policyName` if checkstyle is giving you warnings
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpProcess.java, line 421 at r1](https://reviewable.io/reviews/batfish/batfish/6554#-MQWM2gT7yG52g2fNOKk:-MQ_9Qf5ASYOjngzrZvs:bw032nj) ([raw file](https://github.com/batfish/batfish/blob/36f9d4a03562774587e93d33ec5d561cb8ab489e/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpProcess.java#L421)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

:) 
while i share the same feeling, I wasn't about to start rewriting a bunch of vendor conversion code
</blockquote></details>

understandable :disappointed:

**Review by progwriter — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6554)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java, line 261 at r1](https://reviewable.io/reviews/batfish/batfish/6554#-MQW-7hl79aTIJxoNAyk:-MQmqgnw8N0Eq9r97CIK:b-acpdam) ([raw file](https://github.com/batfish/batfish/blob/36f9d4a03562774587e93d33ec5d561cb8ab489e/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java#L261)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

all the other ribs have `_process.getMultipathIbgp() ? null : 1` -- is that not appropriate here?
</blockquote></details>

my understanding is that those knobs are for received e/i bgp routes, local rib will keep all redistributed routes.
___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java, line 481 at r2](https://reviewable.io/reviews/batfish/batfish/6554#-MQ_7ossB79yht8vzI1P:-MQmqyx2Cs92qeyqN2TH:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/711e371bdcc024f117098871711ca3ca6e97ddd0/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java#L481)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

this was just confirmed in the if condition. not even really necessary to define `policyName` if checkstyle is giving you warnings
</blockquote></details>

done

**Review by corinaminer — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6554#-:-MQmt2G8CfzW4OWvjG4o:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
