### PR TITLE
Checkpoint mgmt merge show-gateways-and-servers pages

### PR DESCRIPTION
**Pull request by arifogel**
- slight refactor of other merge code
- documentation

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7345)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7345#-Mj2Qxlr4AnWaHvZhN3f:-Mj2Qxlr4AnWaHvZhN3g:b-rfbfgy) (no related file):*
-reviewer:@dhalperi

---

**Review by sfraint — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7345)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/parsing/CheckpointManagementParser.java, line 479 at r2](https://reviewable.io/reviews/batfish/batfish/7345#-Mj6AjkK-NImsXLOcr2E:-Mj6AjkLDR97IrS-VUTC:bok1gqv) ([raw file](https://github.com/batfish/batfish/blob/971ca16039bd4ba24e22f10cc28a71144c4c4ad6/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/parsing/CheckpointManagementParser.java#L479)):*
> ```
>     if (gatewaysAndServersList.size() == 1) {
>       return gatewaysAndServersList.get(0);
>     }
> ```
nit: is this required? can you just remove this and let the stream operate on a single item?

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7345)* status: all files reviewed, 1 unresolved discussion (waiting on @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/parsing/CheckpointManagementParser.java, line 479 at r2](https://reviewable.io/reviews/batfish/batfish/7345#-Mj6AjkK-NImsXLOcr2E:-Mj6E42N1yeQZ9luIiyh:byyeisg) ([raw file](https://github.com/batfish/batfish/blob/971ca16039bd4ba24e22f10cc28a71144c4c4ad6/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/parsing/CheckpointManagementParser.java#L479)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
>     if (gatewaysAndServersList.size() == 1) {
>       return gatewaysAndServersList.get(0);
>     }
> ```
nit: is this required? can you just remove this and let the stream operate on a single item?
</blockquote></details>

Not required, just avoids a copy as an optimization.
It's tested, so leaving it unless there is an objection.

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7345)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/parsing/CheckpointManagementParser.java, line 479 at r2](https://reviewable.io/reviews/batfish/batfish/7345#-Mj6AjkK-NImsXLOcr2E:-Mj6EN8-7ic5F_kky6an:bizlbj6) ([raw file](https://github.com/batfish/batfish/blob/971ca16039bd4ba24e22f10cc28a71144c4c4ad6/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/parsing/CheckpointManagementParser.java#L479)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Not required, just avoids a copy as an optimization.
It's tested, so leaving it unless there is an objection.
</blockquote></details>

:shipit:

**Pull request merged**
