### PR TITLE
FortiOS: interface parsing and extraction

### PR DESCRIPTION
**Pull request by sfraint**

### CODE REVIEW

**Review by corinaminer — COMMENTED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6679)* status: all files reviewed, 9 unresolved discussions (waiting on @arifogel and @sfraint)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_interface.g4, line 7 at r1](https://reviewable.io/reviews/batfish/batfish/6679#-MUq9GlpDIEDE1D0cl1F:-MUq9GlpDIEDE1D0cl1G:bawk360) ([raw file](https://github.com/batfish/batfish/blob/a440ee504e70cedd0fd05c4ea79277e3ec0b8a4c/projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_interface.g4#L7)):*
> ```ANTLR
> }
> 
> cs_interface: INTERFACE NEWLINE csi_edit*;
> ```

In all the grammar files i've worked with, the colons and semicolons get their own lines. i'm not sure why -- @arifogel? but i'd guess we want to stick to that pattern
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_interface.g4, line 26 at r1](https://reviewable.io/reviews/batfish/batfish/6679#-MUq8jc3DeuqSCD5p43z:-MUq8jc3DeuqSCD5p44-:b9zc15q) ([raw file](https://github.com/batfish/batfish/blob/a440ee504e70cedd0fd05c4ea79277e3ec0b8a4c/projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_interface.g4#L26)):*
> ```ANTLR
>     | csi_set_description
>     | csi_set_snmp_index
>     | csi_set_vrf
> ```

any logic to the ordering? I don't think order matters here technically, but i'd alphabetize so that it's easier for readers to check if something is parsed
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_interface.g4, line 45 at r1](https://reviewable.io/reviews/batfish/batfish/6679#-MUqATdG6AfLIOMY7MGF:-MUqATdG6AfLIOMY7MGG:b-2vl439) ([raw file](https://github.com/batfish/batfish/blob/a440ee504e70cedd0fd05c4ea79277e3ec0b8a4c/projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_interface.g4#L45)):*
> ```ANTLR
> csi_set_description: DESCRIPTION description = str NEWLINE;
> 
> csi_set_snmp_index: SNMP_INDEX null_rest_of_line;
> ```

Should this be extracted? If not, why bother parsing it?

If there is some reason to parse and ignore it, i think there should be a `csi_ignored` token that includes `csi_set_snmp_index` so we can just put one `exitCsi_ignored_context` in extraction that warns the line is ignored. (then other ignored stuff that we want to parse can be added to `csi_ignored`.)
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 134 at r1](https://reviewable.io/reviews/batfish/batfish/6679#-MUqBMBW6KFwgiXx7lWL:-MUqBMBW6KFwgiXx7lWM:bi71com) ([raw file](https://github.com/batfish/batfish/blob/a440ee504e70cedd0fd05c4ea79277e3ec0b8a4c/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L134)):*
> ```Java
>     Optional<String> name = toString(ctx, ctx.interface_name());
>     if (!name.isPresent()) {
>       _currentInterface = new Interface("dummy");
> ```

in this case should it warn that the interface will be ignored? Also, since `_currentInterface.getName()` is used in some of the warnings, i'd make the dummy interface's name `ctx.interface_name()` even though it's not a legal name.
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 399 at r1](https://reviewable.io/reviews/batfish/batfish/6679#-MUqCyl17Uy_ntxbfi3e:-MUqCyl20S8KBIyKKNre:betgmqq) ([raw file](https://github.com/batfish/batfish/blob/a440ee504e70cedd0fd05c4ea79277e3ec0b8a4c/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L399)):*
> ```Java
>   private static final Pattern ESCAPED_UNQUOTED_CHAR_PATTERN = Pattern.compile("\\\\([^\\r\\n])");
>   private static final Pattern INTERFACE_NAME_PATTERN = Pattern.compile("^[^\r\n]{1,15}$");
>   private static final Pattern INTERFACE_ALIAS_PATTERN = Pattern.compile("^[^\r\n]{0,25}$");
> ```

you can really make a length 0 alias? :sweat_smile: 
___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/Interface.java, line 54 at r1](https://reviewable.io/reviews/batfish/batfish/6679#-MUqDZNgDgW9C6qBRIa-:-MUqDZNgDgW9C6qBRIa0:b-6miht3) ([raw file](https://github.com/batfish/batfish/blob/a440ee504e70cedd0fd05c4ea79277e3ec0b8a4c/projects/batfish/src/main/java/org/batfish/representation/fortios/Interface.java#L54)):*
> ```Java
>   @VisibleForTesting
>   @Nullable
>   public Boolean getStatus() {
> ```

I'd call this `getEnabled` (and the field `_enabled`) -- `_status` is a confusing boolean.
___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/Interface.java, line 76 at r1](https://reviewable.io/reviews/batfish/batfish/6679#-MUqE82R1wJenXhTQYnj:-MUqE82S0WHNAHJox0XR:b-f6y1e0) ([raw file](https://github.com/batfish/batfish/blob/a440ee504e70cedd0fd05c4ea79277e3ec0b8a4c/projects/batfish/src/main/java/org/batfish/representation/fortios/Interface.java#L76)):*
> ```Java
>    */
>   public int getMtuEffective() {
>     return _mtu == null || _mtuOverride == null ? DEFAULT_INTERFACE_MTU : _mtu;
> ```

Does `_mtuOverride` indicate whether the configured MTU should override the default MTU? If so, you need to return default whenever `_mtuOverride != true` (currently you'll get the wrong result when MTU is set and override is set to false)
___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/Interface.java, line 141 at r1](https://reviewable.io/reviews/batfish/batfish/6679#-MUqHbx63OeTluy_Bzyv:-MUqHbx63OeTluy_Bzyw:b-e5ii52) ([raw file](https://github.com/batfish/batfish/blob/a440ee504e70cedd0fd05c4ea79277e3ec0b8a4c/projects/batfish/src/main/java/org/batfish/representation/fortios/Interface.java#L141)):*
> ```Java
>   public Interface(String name) {
>     _name = name;
>     _type = Type.UNKNOWN;
> ```

is there any reason after extraction to differentiate between an interface where type was never set, and an interface where type was set to an unknown value? If so, it would make sense to me to let `_type` be nullable (where null indicates it was never set).

On the other hand, is there any reason to differentiate between an interface where status, MTU override, MTU, or vrf is unset and one where it's set to its default value? If not, it would make sense to make those nonnull and set them to their defaults here.
___
*[projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/iface, line 51 at r1](https://reviewable.io/reviews/batfish/batfish/6679#-MUqGgFS5ktoqnblGJ_r:-MUqGgFS5ktoqnblGJ_s:bkosb86) ([raw file](https://github.com/batfish/batfish/blob/a440ee504e70cedd0fd05c4ea79277e3ec0b8a4c/projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/iface#L51)):*
> ```
>     next
>     edit "wl"
>         set vdom "root"
> ```

do they all need `vdom` set? Test only checks it for `port`

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6679)* status: 3 of 10 files reviewed, 9 unresolved discussions (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_interface.g4, line 7 at r1](https://reviewable.io/reviews/batfish/batfish/6679#-MUq9GlpDIEDE1D0cl1F:-MUqZWru68Q0A5mml8mK:bdl6f00) ([raw file](https://github.com/batfish/batfish/blob/a440ee504e70cedd0fd05c4ea79277e3ec0b8a4c/projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_interface.g4#L7)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

In all the grammar files i've worked with, the colons and semicolons get their own lines. i'm not sure why -- @arifogel? but i'd guess we want to stick to that pattern
</blockquote></details>

recent grammar has been deviating from that pattern in favor what is concise and legible, see comments in https://github.com/batfish/batfish/pull/6652
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_interface.g4, line 26 at r1](https://reviewable.io/reviews/batfish/batfish/6679#-MUq8jc3DeuqSCD5p43z:-MUq_0Ft9nDKfc81H4wW:b-fhz9lm) ([raw file](https://github.com/batfish/batfish/blob/a440ee504e70cedd0fd05c4ea79277e3ec0b8a4c/projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_interface.g4#L26)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

any logic to the ordering? I don't think order matters here technically, but i'd alphabetize so that it's easier for readers to check if something is parsed
</blockquote></details>

mostly from order encountering them on the cli, no harm in alphabetizing
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_interface.g4, line 45 at r1](https://reviewable.io/reviews/batfish/batfish/6679#-MUqATdG6AfLIOMY7MGF:-MUq_7pP5A0GI5XlLViK:bx13vao) ([raw file](https://github.com/batfish/batfish/blob/a440ee504e70cedd0fd05c4ea79277e3ec0b8a4c/projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_interface.g4#L45)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Should this be extracted? If not, why bother parsing it?

If there is some reason to parse and ignore it, i think there should be a `csi_ignored` token that includes `csi_set_snmp_index` so we can just put one `exitCsi_ignored_context` in extraction that warns the line is ignored. (then other ignored stuff that we want to parse can be added to `csi_ignored`.)
</blockquote></details>

I didn't want to have parse warnings or unrecognized line warnings for something that won't affect Batfish modeling
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 134 at r1](https://reviewable.io/reviews/batfish/batfish/6679#-MUqBMBW6KFwgiXx7lWL:-MUq_IZI39umog9DKdnl:bwh58ui) ([raw file](https://github.com/batfish/batfish/blob/a440ee504e70cedd0fd05c4ea79277e3ec0b8a4c/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L134)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

in this case should it warn that the interface will be ignored? Also, since `_currentInterface.getName()` is used in some of the warnings, i'd make the dummy interface's name `ctx.interface_name()` even though it's not a legal name.
</blockquote></details>

there is already a warning that the interface name is invalid, e.g. `Illegal value for interface name ...`
we can add another warning here but it feels unnecessary

also, this interface isn't saved or exposed anywhere so I didn't think we needed to worry about the interface name
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 399 at r1](https://reviewable.io/reviews/batfish/batfish/6679#-MUqCyl17Uy_ntxbfi3e:-MUq_yCd-yrivAU0A1fL:b-pn17r4) ([raw file](https://github.com/batfish/batfish/blob/a440ee504e70cedd0fd05c4ea79277e3ec0b8a4c/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L399)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

you can really make a length 0 alias? :sweat_smile: 
</blockquote></details>

you can, I meant to add a test for that :smiley: 
___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/Interface.java, line 54 at r1](https://reviewable.io/reviews/batfish/batfish/6679#-MUqDZNgDgW9C6qBRIa-:-MUqbhMy74WOLrjYAceK:b-ye5syq) ([raw file](https://github.com/batfish/batfish/blob/a440ee504e70cedd0fd05c4ea79277e3ec0b8a4c/projects/batfish/src/main/java/org/batfish/representation/fortios/Interface.java#L54)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

I'd call this `getEnabled` (and the field `_enabled`) -- `_status` is a confusing boolean.
</blockquote></details>

I agree it's a bit confusing...but the config calls it status so maybe we should convert it to an enum instead
also I got the accepted values wrong...fixed now
___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/Interface.java, line 76 at r1](https://reviewable.io/reviews/batfish/batfish/6679#-MUqE82R1wJenXhTQYnj:-MUqcHqe8309FUGNqfcf:b-7ql1td) ([raw file](https://github.com/batfish/batfish/blob/a440ee504e70cedd0fd05c4ea79277e3ec0b8a4c/projects/batfish/src/main/java/org/batfish/representation/fortios/Interface.java#L76)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Does `_mtuOverride` indicate whether the configured MTU should override the default MTU? If so, you need to return default whenever `_mtuOverride != true` (currently you'll get the wrong result when MTU is set and override is set to false)
</blockquote></details>

fixed
___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/Interface.java, line 141 at r1](https://reviewable.io/reviews/batfish/batfish/6679#-MUqHbx63OeTluy_Bzyv:-MUqccdK5e-hxYhYUYU1:bwj4npp) ([raw file](https://github.com/batfish/batfish/blob/a440ee504e70cedd0fd05c4ea79277e3ec0b8a4c/projects/batfish/src/main/java/org/batfish/representation/fortios/Interface.java#L141)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

is there any reason after extraction to differentiate between an interface where type was never set, and an interface where type was set to an unknown value? If so, it would make sense to me to let `_type` be nullable (where null indicates it was never set).

On the other hand, is there any reason to differentiate between an interface where status, MTU override, MTU, or vrf is unset and one where it's set to its default value? If not, it would make sense to make those nonnull and set them to their defaults here.
</blockquote></details>

currently, `UNKNOWN` only means not set - the grammar won't allow anything other than the values we already handle
I updated the config builder to be more clear about that
___
*[projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/iface, line 51 at r1](https://reviewable.io/reviews/batfish/batfish/6679#-MUqGgFS5ktoqnblGJ_r:-MUqcuj90KS65HuTJbXo:b-sm18c3) ([raw file](https://github.com/batfish/batfish/blob/a440ee504e70cedd0fd05c4ea79277e3ec0b8a4c/projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/iface#L51)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

do they all need `vdom` set? Test only checks it for `port`
</blockquote></details>

`vdom` is required when editing an interface - figured I'd include it here to keep these closer to correct/real config
also, I expect we will require vdom to be set for valid interfaces in Batfish in the near future

**Review by corinaminer — COMMENTED** [review]
> Reviewed 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6679)* status: all files reviewed, 3 unresolved discussions (waiting on @arifogel, @corinaminer, and @sfraint)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_interface.g4, line 7 at r1](https://reviewable.io/reviews/batfish/batfish/6679#-MUq9GlpDIEDE1D0cl1F:-MUtTFZY0i7TwUxotVpe:biht0sw) ([raw file](https://github.com/batfish/batfish/blob/a440ee504e70cedd0fd05c4ea79277e3ec0b8a4c/projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_interface.g4#L7)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

recent grammar has been deviating from that pattern in favor what is concise and legible, see comments in https://github.com/batfish/batfish/pull/6652
</blockquote></details>

oh nice :)
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 134 at r1](https://reviewable.io/reviews/batfish/batfish/6679#-MUqBMBW6KFwgiXx7lWL:-MUtWha74XgqXb6Iro86:b-l1z7tj) ([raw file](https://github.com/batfish/batfish/blob/a440ee504e70cedd0fd05c4ea79277e3ec0b8a4c/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L134)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

there is already a warning that the interface name is invalid, e.g. `Illegal value for interface name ...`
we can add another warning here but it feels unnecessary

also, this interface isn't saved or exposed anywhere so I didn't think we needed to worry about the interface name
</blockquote></details>

re warning: gotcha, never mind.

The interface name could be exposed in later warnings... i see you took out the `toStatus` warning that used it, but future editors might add a warning that references the current interface.
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 224 at r2](https://reviewable.io/reviews/batfish/batfish/6679#-MUtXCoN2lEUldT6O4th:-MUtXCoN2lEUldT6O4ti:b-ka2p6c) ([raw file](https://github.com/batfish/batfish/blob/72401f3d4a03246c24e4c298774eabcf5f752244/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L224)):*
> ```Java
>     } else {
>       assert ctx.WL_MESH() != null;
>       return Type.WL_MESH;
> ```

i take it these are all the possible interface types? (otherwise, better to have the warning)

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6679)* status: 8 of 10 files reviewed, 3 unresolved discussions (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 134 at r1](https://reviewable.io/reviews/batfish/batfish/6679#-MUqBMBW6KFwgiXx7lWL:-MUtaZF_1RbSdX-BgDLH:bvnrpcm) ([raw file](https://github.com/batfish/batfish/blob/a440ee504e70cedd0fd05c4ea79277e3ec0b8a4c/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L134)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

re warning: gotcha, never mind.

The interface name could be exposed in later warnings... i see you took out the `toStatus` warning that used it, but future editors might add a warning that references the current interface.
</blockquote></details>

updated
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 224 at r2](https://reviewable.io/reviews/batfish/batfish/6679#-MUtXCoN2lEUldT6O4th:-MUtaa7L2V7BKYUzva36:bwzxsfw) ([raw file](https://github.com/batfish/batfish/blob/72401f3d4a03246c24e4c298774eabcf5f752244/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L224)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

i take it these are all the possible interface types? (otherwise, better to have the warning)
</blockquote></details>

right, all (currently known :) ) interface types are accounted for

at any rate, we will have an unrecognized line warning for any interface type that isn't covered above

**Review by corinaminer — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6679)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 224 at r2](https://reviewable.io/reviews/batfish/batfish/6679#-MUtXCoN2lEUldT6O4th:-MUtbRcb3eYKBNPdbQwT:byedwol) ([raw file](https://github.com/batfish/batfish/blob/72401f3d4a03246c24e4c298774eabcf5f752244/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L224)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

right, all (currently known :) ) interface types are accounted for

at any rate, we will have an unrecognized line warning for any interface type that isn't covered above
</blockquote></details>

cool. and, yeah, i suppose the unrecognized line warning is good enough

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6679)* status: all files reviewed, 2 unresolved discussions (waiting on @sfraint)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_common.g4, line 21 at r2](https://reviewable.io/reviews/batfish/batfish/6679#-MUtWoIo3b7AZQ2HZhJt:-MUtWoIp19EgQSode1Vb:bryk5jw) ([raw file](https://github.com/batfish/batfish/blob/72401f3d4a03246c24e4c298774eabcf5f752244/projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_common.g4#L21)):*
> ```ANTLR
> ip_address_with_mask_or_prefix
> :
>     (ip_address subnet_mask) | ip_prefix
> ```

Parens are unnecessary here due to precedence. Could be more clear if you put on two lines.
___
*[projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/iface, line 14 at r2](https://reviewable.io/reviews/batfish/batfish/6679#-MUtVXr8EQ_EqPM0aeQf:-MUtVXr8EQ_EqPM0aeQg:b-vkr9lj) ([raw file](https://github.com/batfish/batfish/blob/72401f3d4a03246c24e4c298774eabcf5f752244/projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/iface#L14)):*
> ```
>         set snmp-index 1
>     next
>     edit "longest if name"
> ```

Is this valid? Doesn't it need a parent interface or something since it's physical?

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6679)* status: 8 of 10 files reviewed, 2 unresolved discussions (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_common.g4, line 21 at r2](https://reviewable.io/reviews/batfish/batfish/6679#-MUtWoIo3b7AZQ2HZhJt:-MUtgfQK4mQSvlNWQDZM:bvnrpcm) ([raw file](https://github.com/batfish/batfish/blob/72401f3d4a03246c24e4c298774eabcf5f752244/projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_common.g4#L21)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Parens are unnecessary here due to precedence. Could be more clear if you put on two lines.
</blockquote></details>

updated
___
*[projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/iface, line 14 at r2](https://reviewable.io/reviews/batfish/batfish/6679#-MUtVXr8EQ_EqPM0aeQf:-MUtgFwcCJfCUmayaUhq:bvpx03a) ([raw file](https://github.com/batfish/batfish/blob/72401f3d4a03246c24e4c298774eabcf5f752244/projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/iface#L14)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Is this valid? Doesn't it need a parent interface or something since it's physical?
</blockquote></details>

probably not valid on a device, changed the type

**Review by arifogel — COMMENTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6679)* status: all files reviewed, 1 unresolved discussion (waiting on @sfraint)

___
*[projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/iface, line 14 at r2](https://reviewable.io/reviews/batfish/batfish/6679#-MUtVXr8EQ_EqPM0aeQf:-MUtiJkX4mPYDsXgqU_3:b-spx1tr) ([raw file](https://github.com/batfish/batfish/blob/72401f3d4a03246c24e4c298774eabcf5f752244/projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/iface#L14)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

probably not valid on a device, changed the type
</blockquote></details>

I thought you were only putting things here that were valid on a device. Why parse invalid things?
Can be changed later, but not sure why you'd want to do extra work here.
Did you confirm that this is valid with the change?

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6679)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel)

___
*[projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/iface, line 14 at r2](https://reviewable.io/reviews/batfish/batfish/6679#-MUtVXr8EQ_EqPM0aeQf:-MUtkjVa3VqvYyzg4rZl:b-hud5lq) ([raw file](https://github.com/batfish/batfish/blob/72401f3d4a03246c24e4c298774eabcf5f752244/projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/iface#L14)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

I thought you were only putting things here that were valid on a device. Why parse invalid things?
Can be changed later, but not sure why you'd want to do extra work here.
Did you confirm that this is valid with the change?
</blockquote></details>

the point is to parse a range of valid lines to exercise parsing and extraction in a relatively short config

each individual line was valid, but since you can't create a new, custom physical interface that line wouldn't exist under a custom interface name

with type `vlan` you can set all of these other properties except mtu since we aren't parsing and extracting a couple vlan-specific properties yet

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6679)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel)

___
*[projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/iface, line 14 at r2](https://reviewable.io/reviews/batfish/batfish/6679#-MUtVXr8EQ_EqPM0aeQf:-MUto92q9SBFS4pr_bJ_:b-ayrl4c) ([raw file](https://github.com/batfish/batfish/blob/72401f3d4a03246c24e4c298774eabcf5f752244/projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/iface#L14)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

the point is to parse a range of valid lines to exercise parsing and extraction in a relatively short config

each individual line was valid, but since you can't create a new, custom physical interface that line wouldn't exist under a custom interface name

with type `vlan` you can set all of these other properties except mtu since we aren't parsing and extracting a couple vlan-specific properties yet
</blockquote></details>

I did catch a couple typos though, fix inc

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6679)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel and @sfraint)

___
*[projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/iface, line 14 at r2](https://reviewable.io/reviews/batfish/batfish/6679#-MUtVXr8EQ_EqPM0aeQf:-MUto5H25ZsGurwhXUCP:bpce9p4) ([raw file](https://github.com/batfish/batfish/blob/72401f3d4a03246c24e4c298774eabcf5f752244/projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/iface#L14)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

the point is to parse a range of valid lines to exercise parsing and extraction in a relatively short config

each individual line was valid, but since you can't create a new, custom physical interface that line wouldn't exist under a custom interface name

with type `vlan` you can set all of these other properties except mtu since we aren't parsing and extracting a couple vlan-specific properties yet
</blockquote></details>

So why not put mtu under "port1" instead?

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6679)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel)

___
*[projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/iface, line 14 at r2](https://reviewable.io/reviews/batfish/batfish/6679#-MUtVXr8EQ_EqPM0aeQf:-MUtoNig-wJjECwR_zgv:bumlgz0) ([raw file](https://github.com/batfish/batfish/blob/72401f3d4a03246c24e4c298774eabcf5f752244/projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/iface#L14)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

So why not put mtu under "port1" instead?
</blockquote></details>

We should still test defaults, but I can add another physical port.

But even without `mtu` the `vlan` interfaces are still technically invalid since they don't have vlanid or physical interface references, which we're not handling yet

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6679)* status: 5 of 10 files reviewed, 1 unresolved discussion (waiting on @arifogel, @corinaminer, and @sfraint)

___
*[projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/iface, line 14 at r2](https://reviewable.io/reviews/batfish/batfish/6679#-MUtVXr8EQ_EqPM0aeQf:-MUtp_Yx6-OmTgGGbmiw:bqmfl4t) ([raw file](https://github.com/batfish/batfish/blob/72401f3d4a03246c24e4c298774eabcf5f752244/projects/batfish/src/test/resources/org/batfish/grammar/fortios/testconfigs/iface#L14)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

We should still test defaults, but I can add another physical port.

But even without `mtu` the `vlan` interfaces are still technically invalid since they don't have vlanid or physical interface references, which we're not handling yet


</blockquote></details>

In the end you can choose what you want to do incrementally. I just recommend not doing stuff you will definitely have to undo/remove.
Resolve for now how you see fit.

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6679)* status: 6 of 10 files reviewed, 1 unresolved discussion (waiting on @corinaminer and @sfraint)

**Review by sfraint — COMMENTED** [review]
> Reviewed 4 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6679)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
