### PR TITLE
generic: use raw hostname value as human name

### PR DESCRIPTION
**Pull request by dhalperi**

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7063)* status: 0 of 29 files reviewed, 1 unresolved discussion (waiting on @dhalperi and @sfraint)

___
*[projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java, line 1844 at r1](https://reviewable.io/reviews/batfish/batfish/7063#-McBCU_s2V4rqg_KuhOR:-McBCU_s2V4rqg_KuhOS:bucqza) ([raw file](https://github.com/batfish/batfish/blob/0d42a6022e0e72b619fd02c52791235fcd6be7be/projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java#L1844)):*
> ```
>   public void testHumanName() throws IOException {
>     Configuration c = parseConfig("nxos_hostname");
>     assertThat(c.getHumanName(), equalTo("NXOS_hostname"));
> ```
FYI existing test infra checks VI hostname on `parseConfig`
___
*[projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java, line 311 at r1](https://reviewable.io/reviews/batfish/batfish/7063#-McBCaPkBnDuKVDwOmh0:-McBCaPkBnDuKVDwOmh1:b-81s6fm) ([raw file](https://github.com/batfish/batfish/blob/0d42a6022e0e72b619fd02c52791235fcd6be7be/projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java#L311)):*
> ```
> org.batfish.grammar.palo_alto.
> ```

WORKING fix this

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7063)* status: 0 of 29 files reviewed, 1 unresolved discussion (waiting on @dhalperi and @sfraint)

___
*[projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/humanname, line 11 at r1](https://reviewable.io/reviews/batfish/batfish/7063#-McBDz9B32lSQiEIgLAM:-McBDz9B32lSQiEIgLAN:b-3u3ljn) ([raw file](https://github.com/batfish/batfish/blob/0d42a6022e0e72b619fd02c52791235fcd6be7be/projects/batfish/src/test/resources/org/batfish/grammar/palo_alto/testconfigs/humanname#L11)):*
> ```
> set device-group DG1 address ADDR1 ip-netmask 1.2.3.4
> set device-group DG2 address ADDR2 ip-netmask 2.3.4.5
> # Device-group specific entities
> ```

WORKING: delete this.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7063)* status: 1 of 29 files reviewed, all discussions resolved (waiting on @sfraint)

**Review by sfraint — COMMENTED** [review]
> Reviewed 29 of 29 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7063)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dhalperi)

**Pull request merged**
