### PR TITLE
Junos: add parsing for  `fti` interface type

### PR DESCRIPTION
**Pull request by pranavbj-amzn**
Add support for  `fti` interface type.

Flexible tunnel interface (FTI) is a type of logical tunnel interface that uses static routing and BGP protocols to exchange routes over a tunnel that connects endpoints to routers.

JunOS documentation for [FTI interfaces](https://www.juniper.net/documentation/us/en/software/junos/interfaces-encryption/topics/topic-map/configuring-flexible-tunnel-interfaces.html)

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8886)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @pranavbj-amzn)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/8886#-NlyjdTJ5GJfChoJp1pp:-NlyjdTJ5GJfChoJp1pq:b-w2vtmy) (no related file):*
Dumb question: what about this is about delete? Vs Batifsh just not knowing that `fti` is a type of interface?

If it's the latter, I'd probably instead add an `fti` specific file with a bunch of the FTI-related commands we have and not over index on delete.

___

**Review by pranavbj-amzn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8886)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @dhalperi)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/8886#-NlyjdTJ5GJfChoJp1pp:-NlykTJF7Y-d1c3l8dCR:bwap3d) (no related file):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Dumb question: what about this is about delete? Vs Batifsh just not knowing that `fti` is a type of interface?

If it's the latter, I'd probably instead add an `fti` specific file with a bunch of the FTI-related commands we have and not over index on delete.
</blockquote></details>

yes this is Batifsh just not knowing that `fti` is a type of interface

okay will add `fti` specific file with some FTI-related commands

___

**Review by pranavbj-amzn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8886)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @dhalperi)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/8886#-NlyjdTJ5GJfChoJp1pp:-Nlypret4Umrt0t4LpP5:b-7rl0jq) (no related file):*
<details><summary><i>Previously, pranavbj-amzn (Pranav Bhardwaj) wrote…</i></summary><blockquote>

yes this is Batifsh just not knowing that `fti` is a type of interface

okay will add `fti` specific file with some FTI-related commands
</blockquote></details>

done!

___

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8886)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pranavbj-amzn)

**Pull request merged**
