### PR TITLE
PAN: validity checks for NAT ip-ranges

### PR DESCRIPTION
**Pull request by sfraint**
Add validity checks for Palo Alto NAT ip-ranges.

### CODE REVIEW

**Review by ratulm — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6296)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6296)* status: all files reviewed, 1 unresolved discussion (waiting on @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java, line 1298 at r1](https://reviewable.io/reviews/batfish/batfish/6296#-MJDZSyy2kfqZVJV4ujN:-MJDZSyy2kfqZVJV4ujO:bkhcism) ([raw file](https://github.com/batfish/batfish/blob/1d3361787f75bc3a5b100a9da2c457a69b8f0fb3/projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java#L1298)):*
> ```Java
>     String[] ips = range.split("-");
>     Ip low = Ip.parse(ips[0]);
>     Ip high = Ip.parse(ips[1]);
> ```

do you want to allow for `range` to have a number of dashes other than exactly 1?

**Review by corinaminer — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6296)* status: all files reviewed, 6 unresolved discussions (waiting on @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java, line 1279 at r1](https://reviewable.io/reviews/batfish/batfish/6296#-MJD_Pzj89yvYjngjsi3:-MJD_Pzj89yvYjngjsi4:b-mqw45o) ([raw file](https://github.com/batfish/batfish/blob/1d3361787f75bc3a5b100a9da2c457a69b8f0fb3/projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java#L1279)):*
> ```Java
>               return ipSpace.get();
>             }
>             w.redFlag("Could not convert RuleEndpoint range to IpSpace: " + endpoint);
> ```

will this section of code execute at most once per RuleEndpoint? Don't want to create duplicate warnings. Same question for `ruleEndpointToIpSpace`.

In fact the warning in `ruleEndpointToIpSpace` is very similar, so it'd be best if each RuleEndpoint gets run through at most one of these functions, at most once (or refactor some other way to ensure each RuleEndpoint can only generate one warning of this type).
___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java, line 1298 at r1](https://reviewable.io/reviews/batfish/batfish/6296#-MJDZhHh8W0vqw1Mibr9:-MJDZhHh8W0vqw1MibrA:b9fsxz6) ([raw file](https://github.com/batfish/batfish/blob/1d3361787f75bc3a5b100a9da2c457a69b8f0fb3/projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java#L1298)):*
> ```Java
>     String[] ips = range.split("-");
>     Ip low = Ip.parse(ips[0]);
>     Ip high = Ip.parse(ips[1]);
> ```

do you want to catch errors parsing strings as Ip?
___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java, line 1312 at r1](https://reviewable.io/reviews/batfish/batfish/6296#-MJD_IAPBp2brrujmuLx:-MJD_IAPBp2brrujmuLy:bxriawf) ([raw file](https://github.com/batfish/batfish/blob/1d3361787f75bc3a5b100a9da2c457a69b8f0fb3/projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java#L1312)):*
> ```Java
>     String[] ips = range.split("-");
>     Ip low = Ip.parse(ips[0]);
>     Ip high = Ip.parse(ips[1]);
> ```

(same questions here about parsing `range`)
___
*[projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java, line 2219 at r1](https://reviewable.io/reviews/batfish/batfish/6296#-MJDatP40jCk27dq8qrH:-MJDatP40jCk27dq8qrI:b-90pj0s) ([raw file](https://github.com/batfish/batfish/blob/1d3361787f75bc3a5b100a9da2c457a69b8f0fb3/projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java#L2219)):*
> ```Java
>     Warnings warn = ccae.getWarnings().get(hostname);
>     assertThat(
>         warn.getRedFlagWarnings().stream().map(Warning::getText).collect(Collectors.toSet()),
> ```

Would be nice to test that this warning appears exactly once (though that wouldn't guarantee that a different config using the same RuleEndpoint would only generate the warning once, so it's of limited use...)
___
*[projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java, line 2223 at r1](https://reviewable.io/reviews/batfish/batfish/6296#-MJDahCt-oVF4DW5Ylo4:-MJDahCt-oVF4DW5Ylo5:bui8sx8) ([raw file](https://github.com/batfish/batfish/blob/1d3361787f75bc3a5b100a9da2c457a69b8f0fb3/projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java#L2223)):*
> ```Java
>             String.format(
>                 "Could not convert RuleEndpoint range to IpSpace: %s",
>                 new RuleEndpoint(IP_RANGE, "11.11.11.13-11.11.11.12"))));
> ```

you've seen what this string ends up looking like, and the RuleEndpoint stringifies legibly?

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6296)* status: all files reviewed, 6 unresolved discussions (waiting on @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java, line 1279 at r1](https://reviewable.io/reviews/batfish/batfish/6296#-MJD_Pzj89yvYjngjsi3:-MJEmsXcCvZEwSe8kSGW:b-oyriga) ([raw file](https://github.com/batfish/batfish/blob/1d3361787f75bc3a5b100a9da2c457a69b8f0fb3/projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java#L1279)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

will this section of code execute at most once per RuleEndpoint? Don't want to create duplicate warnings. Same question for `ruleEndpointToIpSpace`.

In fact the warning in `ruleEndpointToIpSpace` is very similar, so it'd be best if each RuleEndpoint gets run through at most one of these functions, at most once (or refactor some other way to ensure each RuleEndpoint can only generate one warning of this type).
</blockquote></details>

good point, as it stands, we could have multiple identical warnings from this and from existing code - though, I'd prefer to do that refactoring in a separate PR

note: the two different warnings in the different functions (`ruleEndpointToIpSpace` and `ruleEndpointToIpRangeSet`) are mutually exclusive (one for headerspace matching and the other for address translation pools)
___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java, line 1298 at r1](https://reviewable.io/reviews/batfish/batfish/6296#-MJDZSyy2kfqZVJV4ujN:-MJEnlT-55kgWwy1hc2W:bxapr41) ([raw file](https://github.com/batfish/batfish/blob/1d3361787f75bc3a5b100a9da2c457a69b8f0fb3/projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java#L1298)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

do you want to allow for `range` to have a number of dashes other than exactly 1?
</blockquote></details>

the parser guarantees the format for these ranges is correct, i.e. grammar only supports valid ranges
___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java, line 1298 at r1](https://reviewable.io/reviews/batfish/batfish/6296#-MJDZhHh8W0vqw1Mibr9:-MJEntgt0zGPiigfodh1:b-j5e57o) ([raw file](https://github.com/batfish/batfish/blob/1d3361787f75bc3a5b100a9da2c457a69b8f0fb3/projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java#L1298)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

do you want to catch errors parsing strings as Ip?
</blockquote></details>

same answer as above
___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java, line 1312 at r1](https://reviewable.io/reviews/batfish/batfish/6296#-MJD_IAPBp2brrujmuLx:-MJEo3SI51LgYMfZqxw4:b-j5e57o) ([raw file](https://github.com/batfish/batfish/blob/1d3361787f75bc3a5b100a9da2c457a69b8f0fb3/projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java#L1312)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

(same questions here about parsing `range`)
</blockquote></details>

same answer as above
___
*[projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java, line 2219 at r1](https://reviewable.io/reviews/batfish/batfish/6296#-MJDatP40jCk27dq8qrH:-MJEoRCJ0ojCgzN18N_O:badf75i) ([raw file](https://github.com/batfish/batfish/blob/1d3361787f75bc3a5b100a9da2c457a69b8f0fb3/projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java#L2219)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Would be nice to test that this warning appears exactly once (though that wouldn't guarantee that a different config using the same RuleEndpoint would only generate the warning once, so it's of limited use...)
</blockquote></details>

this would probably fail today - similar to above, probably a good thing to add in that separate PR
___
*[projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java, line 2223 at r1](https://reviewable.io/reviews/batfish/batfish/6296#-MJDahCt-oVF4DW5Ylo4:-MJEo7RsCTcRycW9CM4m:b-jpdk1x) ([raw file](https://github.com/batfish/batfish/blob/1d3361787f75bc3a5b100a9da2c457a69b8f0fb3/projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java#L2223)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

you've seen what this string ends up looking like, and the RuleEndpoint stringifies legibly?
</blockquote></details>

mainly going for consistency here, but it is reasonable, iirc something like `RuleEndpoint{type=IP_RANGE, value="11.11.11.13-11.11.11.12"}`

**Review by corinaminer — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6296#-:-MJTBQl_9JL3tB_8W-wU:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java, line 2223 at r1](https://reviewable.io/reviews/batfish/batfish/6296#-MJDahCt-oVF4DW5Ylo4:-MJTBKlR3VIAHSXSrxzU:bof5xys) ([raw file](https://github.com/batfish/batfish/blob/1d3361787f75bc3a5b100a9da2c457a69b8f0fb3/projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java#L2223)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

mainly going for consistency here, but it is reasonable, iirc something like `RuleEndpoint{type=IP_RANGE, value="11.11.11.13-11.11.11.12"}`
</blockquote></details>

ok good enough

**Pull request merged**
