### PR TITLE
NX-OS enforce main RIB resolvability

### PR DESCRIPTION
**Pull request by arifogel**

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 2 files at r5, 4 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7201)* status: 8 of 12 files reviewed, 1 unresolved discussion (waiting on @arifogel)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7201#-Mf_Ay6N3jxaXRocWIWE:-Mf_Ay6N3jxaXRocWIWF:bkpqdmk) (no related file):*
After batfish/batfish#7200

---

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7201)* status: 8 of 12 files reviewed, 2 unresolved discussions (waiting on @arifogel and @corinaminer)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7201#-Mf_BQRS8jtQDqCRNvut:-Mf_BQRS8jtQDqCRNvuu:b-bzmliq) (no related file):*
Need to do performance comparison

---

**Review by arifogel — COMMENTED** [review]
> Reviewed 10 of 12 files at r8.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7201)* status: 10 of 12 files reviewed, 1 unresolved discussion (waiting on @arifogel and @corinaminer)

**Review by corinaminer — COMMENTED** [review]
> Reviewed 2 of 12 files at r8.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7201)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel)

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7201)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dhalperi)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7201#-Mf_BQRS8jtQDqCRNvut:-MghX6nq-kqy0Pik2Zah:bi76p0f) (no related file):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Need to do performance comparison
</blockquote></details>

No apparent impact on performance on network with many impacted routes.

---

**Pull request merged**
