### PR TITLE
CompareRoutePolicies: Compute relevant route attributes

### PR DESCRIPTION
**Pull request by millstein**
For each difference returned by CompareRoutePolicies, compute the set of attributes on the input route that are relevant. The key property is that for any attribute that is deemed irrelevant, any concrete value can be used for that attribute without affecting the behavior of the route policies on the input route.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/9137)* status: all files reviewed, 13 unresolved discussions (waiting on @millstein and @nickgian)

___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/MutableBDDInteger.java` line 287 at r1](https://reviewable.io/reviews/batfish/batfish/9137#-O3ZbKLaEKc49I-6YtxI:-O3ZbKLaEKc49I-6YtxJ:b-f30d6l) ([raw file](https://github.com/batfish/batfish/blob/37dc8825d3e51e47396e229f9bd07333d9a523d0/projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/MutableBDDInteger.java#L287)):*
> ```Java
>    */
>   public BDD support() {
>     return _factory.andAll(Arrays.stream(_bitvec).map(BDD::support).collect(Collectors.toSet()));
> ```

looks like this can this be `andAllAndFree` (so it should).
___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/question/compareroutepolicies/CompareRoutePoliciesUtils.java` line 320 at r1](https://reviewable.io/reviews/batfish/batfish/9137#-O3Ztf-sE6D9zmTM-8Zz:-O3Ztf-sE6D9zmTM-8_-:bssf0k1) ([raw file](https://github.com/batfish/batfish/blob/37dc8825d3e51e47396e229f9bd07333d9a523d0/projects/minesweeper/src/main/java/org/batfish/minesweeper/question/compareroutepolicies/CompareRoutePoliciesUtils.java#L320)):*
> ```Java
>       BDD differences = allDifferencesForType(d, r1, r2);
>       BDD allConstraints = inputConstraints.and(differences);
>       if (!allConstraints.isZero()) {
> ```

Use this for less work.



_Suggestion:_
```Java
      if (!inputConstraints.andSat(allConstraints)) {
```
___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/question/compareroutepolicies/CompareRoutePoliciesUtils.java` line 530 at r1](https://reviewable.io/reviews/batfish/batfish/9137#-O3ZuMYl9Cf_2EUMG1wu:-O3ZuMYl9Cf_2EUMG1wv:bax1fzp) ([raw file](https://github.com/batfish/batfish/blob/37dc8825d3e51e47396e229f9bd07333d9a523d0/projects/minesweeper/src/main/java/org/batfish/minesweeper/question/compareroutepolicies/CompareRoutePoliciesUtils.java#L530)):*
> ```Java
>             finalConstraints = allConstraints;
>           } else {
>             outputConstraints.free();
> ```

why not free this on the `if` path?
___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/question/compareroutepolicies/CompareRoutePoliciesUtils.java` line 534 at r1](https://reviewable.io/reviews/batfish/batfish/9137#-O3ZuA1I7kytaVBx_7oK:-O3ZuA1I7kytaVBx_7oL:b-k2h9ql) ([raw file](https://github.com/batfish/batfish/blob/37dc8825d3e51e47396e229f9bd07333d9a523d0/projects/minesweeper/src/main/java/org/batfish/minesweeper/question/compareroutepolicies/CompareRoutePoliciesUtils.java#L534)):*
> ```Java
>           }
>         }
>       }
> ```

I think we lost `intersection.free()` for the rejected path.
___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/question/compareroutepolicies/CompareRoutePoliciesUtils.java` line 557 at r1](https://reviewable.io/reviews/batfish/batfish/9137#-O3Zuexf0gIAB2zoZcp3:-O3Zuexf0gIAB2zoZcp4:b-eszlaq) ([raw file](https://github.com/batfish/batfish/blob/37dc8825d3e51e47396e229f9bd07333d9a523d0/projects/minesweeper/src/main/java/org/batfish/minesweeper/question/compareroutepolicies/CompareRoutePoliciesUtils.java#L557)):*
> ```Java
>     // irrelevant attributes to be considered relevant.
>     List<Result.RouteAttributeType> relevantAttributes =
>         relevantAttributesFor(inputRoutes.and(inputRoutesOther).and(outputConstraints), configAPs);
> ```

save one leak, tho the return value is also leaked.

probably not worth obsessing over this code as it's just producing an answer.



_Suggestion:_
```Java
inputRoutes.and(inputRoutesOther).andEq(outputConstraints)
```
___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/question/compareroutepolicies/CompareRoutePoliciesUtils.java` line 579 at r1](https://reviewable.io/reviews/batfish/batfish/9137#-O3ZuxjY6-lpiun5Gun6:-O3ZuxjY6-lpiun5Gun7:b-dt2rkv) ([raw file](https://github.com/batfish/batfish/blob/37dc8825d3e51e47396e229f9bd07333d9a523d0/projects/minesweeper/src/main/java/org/batfish/minesweeper/question/compareroutepolicies/CompareRoutePoliciesUtils.java#L579)):*
> ```Java
>   public static List<Result.RouteAttributeType> relevantAttributesFor(
>       BDD constraint, ConfigAtomicPredicates configAPs) {
>     List<Result.RouteAttributeType> result = new ArrayList<>();
> ```

how about `ImmutableList.Builder`? That way it will right-size and be immutable. (nothing else needs to change except return `result.build()`).
___
*[`projects/minesweeper/src/test/java/org/batfish/minesweeper/question/compareroutepolicies/CompareRoutePoliciesUtilsTest.java` line 93 at r1](https://reviewable.io/reviews/batfish/batfish/9137#-O3ZwtAg1WRd-jOA4xMz:-O3ZwtAg1WRd-jOA4xN-:b-xjcf7u) ([raw file](https://github.com/batfish/batfish/blob/37dc8825d3e51e47396e229f9bd07333d9a523d0/projects/minesweeper/src/test/java/org/batfish/minesweeper/question/compareroutepolicies/CompareRoutePoliciesUtilsTest.java#L93)):*
> ```Java
> 
>     assertThat(
>         CompareRoutePoliciesUtils.relevantAttributesFor(none, _configAPs),
> ```

suggest static import this method and all the tests will get smaller :)



_Code quote:_
```Java
relevantAttributesFor
```
___
*[`projects/minesweeper/src/test/java/org/batfish/minesweeper/question/compareroutepolicies/CompareRoutePoliciesUtilsTest.java` line 101 at r1](https://reviewable.io/reviews/batfish/batfish/9137#-O3ZvhSPA6ayMNgnnkpt:-O3ZvhSPA6ayMNgnnkpu:bm5li9z) ([raw file](https://github.com/batfish/batfish/blob/37dc8825d3e51e47396e229f9bd07333d9a523d0/projects/minesweeper/src/test/java/org/batfish/minesweeper/question/compareroutepolicies/CompareRoutePoliciesUtilsTest.java#L101)):*
> ```Java
>         CompareRoutePoliciesUtils.relevantAttributesFor(commOrMed, _configAPs),
>         Matchers.<Collection<Result.RouteAttributeType>>allOf(
>             hasSize(2),
> ```

can skip these two lines as the `containsInAnyOrder` already checks size.



_Code quote:_
```Java
        Matchers.<Collection<Result.RouteAttributeType>>allOf(
            hasSize(2),
```
___
*[`projects/minesweeper/src/test/java/org/batfish/minesweeper/question/compareroutepolicies/CompareRoutePoliciesUtilsTest.java` line 103 at r1](https://reviewable.io/reviews/batfish/batfish/9137#-O3ZwxGQ9n3YigUnPGJI:-O3ZwxGQ9n3YigUnPGJJ:b-wm3ppj) ([raw file](https://github.com/batfish/batfish/blob/37dc8825d3e51e47396e229f9bd07333d9a523d0/projects/minesweeper/src/test/java/org/batfish/minesweeper/question/compareroutepolicies/CompareRoutePoliciesUtilsTest.java#L103)):*
> ```Java
>             hasSize(2),
>             containsInAnyOrder(
>                 Result.RouteAttributeType.COMMUNITIES, Result.RouteAttributeType.METRIC)));
> ```

suggest static import all these constants and all the tests will get smaller/more readable.



_Code quote:_
```Java
Result.RouteAttributeType.COMMUNITIES
```
___
*[`projects/minesweeper/src/test/java/org/batfish/minesweeper/question/compareroutepolicies/CompareRoutePoliciesUtilsTest.java` line 140 at r1](https://reviewable.io/reviews/batfish/batfish/9137#-O3Zw7HsBy7p_hrvG8ON:-O3Zw7HsBy7p_hrvG8OO:b-gym2yb) ([raw file](https://github.com/batfish/batfish/blob/37dc8825d3e51e47396e229f9bd07333d9a523d0/projects/minesweeper/src/test/java/org/batfish/minesweeper/question/compareroutepolicies/CompareRoutePoliciesUtilsTest.java#L140)):*
> ```Java
>             _policyBuilderRef
>                 .setStatements(
>                     ImmutableList.of(new Statements.StaticStatement(Statements.ExitAccept)))
> ```

Use the built-in.



_Suggestion:_
```Java
Statements.ExitAccept.toStaticStatement()
```
___
*[`projects/question/src/main/java/org/batfish/question/testroutepolicies/Result.java` line 76 at r1](https://reviewable.io/reviews/batfish/batfish/9137#-O3ZsxArDlIIz3KNA99k:-O3ZsxArDlIIz3KNA99l:b4nb032) ([raw file](https://github.com/batfish/batfish/blob/37dc8825d3e51e47396e229f9bd07333d9a523d0/projects/question/src/main/java/org/batfish/question/testroutepolicies/Result.java#L76)):*
> ```Java
>   private final RoutingPolicyId _policyId;
>   private final R _inputRoute;
>   // if non-null, this list contains the attributes of the input route that are relevant for the
> ```

use Javadoc comments so they show up in IDEs etc? :)
___
*[`projects/question/src/main/java/org/batfish/question/testroutepolicies/Result.java` line 77 at r1](https://reviewable.io/reviews/batfish/batfish/9137#-O3Zt9CY9eafZXI-XCQP:-O3Zt9CY9eafZXI-XCQQ:b-tl3j9) ([raw file](https://github.com/batfish/batfish/blob/37dc8825d3e51e47396e229f9bd07333d9a523d0/projects/question/src/main/java/org/batfish/question/testroutepolicies/Result.java#L77)):*
> ```Java
>   private final R _inputRoute;
>   // if non-null, this list contains the attributes of the input route that are relevant for the
>   // behavior exhibited by this result
> ```

Does this need to be `@Nullable`? Or can we force it to be non-null and just use all them if all fields are relevant?

(Just trying to improve usability.)
___
*[`projects/question/src/main/java/org/batfish/question/testroutepolicies/Result.java` line 124 at r1](https://reviewable.io/reviews/batfish/batfish/9137#-O3ZtS5-8_uh5MAZn0a9:-O3ZtS50ErTm6cY6Nwek:b5q2o1y) ([raw file](https://github.com/batfish/batfish/blob/37dc8825d3e51e47396e229f9bd07333d9a523d0/projects/question/src/main/java/org/batfish/question/testroutepolicies/Result.java#L124)):*
> ```Java
>   }
> 
>   public @Nullable List<RouteAttributeType> getRelevantInputAttributes() {
> ```

Document what this means for callers?

**Review by millstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/9137)* status: all files reviewed, 3 unresolved discussions (waiting on @dhalperi and @nickgian)

___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/question/compareroutepolicies/CompareRoutePoliciesUtils.java` line 530 at r1](https://reviewable.io/reviews/batfish/batfish/9137#-O3ZuMYl9Cf_2EUMG1wu:-O3cHu8u-_LXvDn7xVqa:buna9a) ([raw file](https://github.com/batfish/batfish/blob/37dc8825d3e51e47396e229f9bd07333d9a523d0/projects/minesweeper/src/main/java/org/batfish/minesweeper/question/compareroutepolicies/CompareRoutePoliciesUtils.java#L530)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

why not free this on the `if` path?
</blockquote></details>

outputConstraints is used later on, when computing relevant attributes, so we can't free it on the `if` path.  i could free it right after computing relevant attributes though, so I've added that.
___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/question/compareroutepolicies/CompareRoutePoliciesUtils.java` line 534 at r1](https://reviewable.io/reviews/batfish/batfish/9137#-O3ZuA1I7kytaVBx_7oK:-O3cI7_C2FBMiai2BWIa:blrm50h) ([raw file](https://github.com/batfish/batfish/blob/37dc8825d3e51e47396e229f9bd07333d9a523d0/projects/minesweeper/src/main/java/org/batfish/minesweeper/question/compareroutepolicies/CompareRoutePoliciesUtils.java#L534)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I think we lost `intersection.free()` for the rejected path.
</blockquote></details>

since `allConstraints` is created through an `andEq` on `intersection`, I thought they are the same object so it suffices to free the former.
___
*[`projects/question/src/main/java/org/batfish/question/testroutepolicies/Result.java` line 77 at r1](https://reviewable.io/reviews/batfish/batfish/9137#-O3Zt9CY9eafZXI-XCQP:-O3cL77HEPU934aX5jvT:b-smbv7q) ([raw file](https://github.com/batfish/batfish/blob/37dc8825d3e51e47396e229f9bd07333d9a523d0/projects/question/src/main/java/org/batfish/question/testroutepolicies/Result.java#L77)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Does this need to be `@Nullable`? Or can we force it to be non-null and just use all them if all fields are relevant?

(Just trying to improve usability.)
</blockquote></details>

Leaving it nullable allows us to distinguish the case when relevant attribute routes are not computed (as is true today for TRP and SRP, for example, which also use this `Result` class) from the case when all attributes are in fact relevant.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/9137)* status: all files reviewed, 2 unresolved discussions (waiting on @millstein and @nickgian)

___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/question/compareroutepolicies/CompareRoutePoliciesUtils.java` line 534 at r1](https://reviewable.io/reviews/batfish/batfish/9137#-O3ZuA1I7kytaVBx_7oK:-O3cQ7JlCrvnOk-xnL-R:btujsws) ([raw file](https://github.com/batfish/batfish/blob/37dc8825d3e51e47396e229f9bd07333d9a523d0/projects/minesweeper/src/main/java/org/batfish/minesweeper/question/compareroutepolicies/CompareRoutePoliciesUtils.java#L534)):*
<details><summary><i>Previously, millstein (Todd Millstein) wrote…</i></summary><blockquote>

since `allConstraints` is created through an `andEq` on `intersection`, I thought they are the same object so it suffices to free the former.
</blockquote></details>

if `diffs.isEmpty` then that `andEq` is not hit, is that right?

This is not super important tho :)
___
*[`projects/question/src/main/java/org/batfish/question/testroutepolicies/Result.java` line 77 at r1](https://reviewable.io/reviews/batfish/batfish/9137#-O3Zt9CY9eafZXI-XCQP:-O3cOwvmDSusAlRlDzXC:b-7ue50j) ([raw file](https://github.com/batfish/batfish/blob/37dc8825d3e51e47396e229f9bd07333d9a523d0/projects/question/src/main/java/org/batfish/question/testroutepolicies/Result.java#L77)):*
<details><summary><i>Previously, millstein (Todd Millstein) wrote…</i></summary><blockquote>

Leaving it nullable allows us to distinguish the case when relevant attribute routes are not computed (as is true today for TRP and SRP, for example, which also use this `Result` class) from the case when all attributes are in fact relevant.
</blockquote></details>

You know, this makes sense but I didn't get it. Maybe add `If null, then the relevant attributes have not been computed` or something.

**Review by millstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/9137)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nickgian)

___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/question/compareroutepolicies/CompareRoutePoliciesUtils.java` line 534 at r1](https://reviewable.io/reviews/batfish/batfish/9137#-O3ZuA1I7kytaVBx_7oK:-O3d-bzq1QMX-I8E9Wq8:beuk18r) ([raw file](https://github.com/batfish/batfish/blob/37dc8825d3e51e47396e229f9bd07333d9a523d0/projects/minesweeper/src/main/java/org/batfish/minesweeper/question/compareroutepolicies/CompareRoutePoliciesUtils.java#L534)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

if `diffs.isEmpty` then that `andEq` is not hit, is that right?

This is not super important tho :)
</blockquote></details>

Got it - I added that now.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/9137)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nickgian)

**Pull request merged**
