### PR TITLE
FortiOS: parse and extract services

### PR DESCRIPTION
**Pull request by sfraint**

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 8 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6685)* status: 8 of 11 files reviewed, 6 unresolved discussions (waiting on @corinaminer and @sfraint)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_service.g4, line 13 at r1](https://reviewable.io/reviews/batfish/batfish/6685#-MUzI_iCC72FLbFA_2Um:-MUzIB_c0A7K-NPFC-44:b-jmg9z9) ([raw file](https://github.com/batfish/batfish/blob/da9803487199abdfd77a47158ad4f89307d6639a/projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_service.g4#L13)):*
> ```ANTLR
> cfsc_edit:
>     EDIT service_name NEWLINE (
>         SET cfsc_set_singletons
> ```

unset?
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/FortiosLexer.g4, line 97 at r1](https://reviewable.io/reviews/batfish/batfish/6685#-MUzHlrbB2cINgey9J7G:-MUzHlrbB2cINgey9J7H:biyzaks) ([raw file](https://github.com/batfish/batfish/blob/da9803487199abdfd77a47158ad4f89307d6639a/projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/FortiosLexer.g4#L97)):*
> ```ANTLR
> COLON: ':';
> 
> HYPHEN: '-';
> ```

As discussed offline:
Not using a mode means that you will erroneously(?) allow spaces between numbers and punctuation.
Doesn't need to be addressed now, but you should leave a TODO if you don't.
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 319 at r1](https://reviewable.io/reviews/batfish/batfish/6685#-MUzJBWpBfU5tJCKI69k:-MUzJBWpBfU5tJCKI69l:bi8qnjr) ([raw file](https://github.com/batfish/batfish/blob/da9803487199abdfd77a47158ad4f89307d6639a/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L319)):*
> ```Java
>     IntegerSpace.Builder spaces = IntegerSpace.builder();
>     for (Service_port_rangeContext range : ctx.service_port_range()) {
>       toIntegerSpace(range.dst_ports).ifPresent(spaces::including);
> ```

Shouldn't this return `Optional<IntegerSpace>` (specifically `Optional.empty()`) if there are any errors? 
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 329 at r1](https://reviewable.io/reviews/batfish/batfish/6685#-MUzJeBD24kJDG_zegnA:-MUzJeBD24kJDG_zegnB:b-tnggmq) ([raw file](https://github.com/batfish/batfish/blob/da9803487199abdfd77a47158ad4f89307d6639a/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L329)):*
> ```Java
>    * returned instead of an IntegerSpace.
>    */
>   private @Nullable IntegerSpace toSrcIntegerSpace(Service_port_rangesContext ctx) {
> ```

nit: why `null` instead of `Optional` to match existing pattern?
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 341 at r1](https://reviewable.io/reviews/batfish/batfish/6685#-MUzK6UCCQwikqp4ST4R:-MUzK6UD28E6ycoorogw:b-v1kewo) ([raw file](https://github.com/batfish/batfish/blob/da9803487199abdfd77a47158ad4f89307d6639a/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L341)):*
> ```Java
>   }
> 
>   private Optional<IntegerSpace> toIntegerSpace(@Nullable Port_rangeContext ctx) {
> ```

Why not handle `null` in the caller instead of here?
___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/Service.java, line 39 at r1](https://reviewable.io/reviews/batfish/batfish/6685#-MUzKgqO60ny5PGTp6dK:-MUzKgqO60ny5PGTp6dL:b2mpek0) ([raw file](https://github.com/batfish/batfish/blob/da9803487199abdfd77a47158ad4f89307d6639a/projects/batfish/src/main/java/org/batfish/representation/fortios/Service.java#L39)):*
> ```Java
>   @Nonnull
>   public Protocol getProtocolEffective() {
>     if (_protocol == Protocol.UNKNOWN) {
> ```

Why not just use `null` like everywhere else, and ditch `Protocol.UNKNOWN`? Is `Protocol.UNKNOWN` something you can set?

**Review by arifogel — COMMENTED** [review]
> Reviewed 3 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6685)* status: all files reviewed, 6 unresolved discussions (waiting on @corinaminer and @sfraint)

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6685)* status: 8 of 11 files reviewed, 6 unresolved discussions (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_service.g4, line 13 at r1](https://reviewable.io/reviews/batfish/batfish/6685#-MUzI_iCC72FLbFA_2Um:-MUzMvHb5jDC8NawLnhj:b5awpz1) ([raw file](https://github.com/batfish/batfish/blob/da9803487199abdfd77a47158ad4f89307d6639a/projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_service.g4#L13)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

unset?
</blockquote></details>

was trying to get the `set` syntax handled (quickly) first to unblock the firewall policy portion

I figure we're going to have to circle back for unset, references, and rename
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/FortiosLexer.g4, line 97 at r1](https://reviewable.io/reviews/batfish/batfish/6685#-MUzHlrbB2cINgey9J7G:-MUzN7bRE7Pzg23IhzxD:b42wmck) ([raw file](https://github.com/batfish/batfish/blob/da9803487199abdfd77a47158ad4f89307d6639a/projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/FortiosLexer.g4#L97)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

As discussed offline:
Not using a mode means that you will erroneously(?) allow spaces between numbers and punctuation.
Doesn't need to be addressed now, but you should leave a TODO if you don't.
</blockquote></details>

I left a TODO note in the `Fortios_service` file by the `service_port_range` rule, I can move it here if you prefer
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 319 at r1](https://reviewable.io/reviews/batfish/batfish/6685#-MUzJBWpBfU5tJCKI69k:-MUzd4mmDkM8ogzAmBW0:bd4cumo) ([raw file](https://github.com/batfish/batfish/blob/da9803487199abdfd77a47158ad4f89307d6639a/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L319)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Shouldn't this return `Optional<IntegerSpace>` (specifically `Optional.empty()`) if there are any errors? 
</blockquote></details>

parsing should ensure we don't have conversion errors at this point
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 329 at r1](https://reviewable.io/reviews/batfish/batfish/6685#-MUzJeBD24kJDG_zegnA:-MUzM-0x3ZZ6XRQfOqZG:b4blsvk) ([raw file](https://github.com/batfish/batfish/blob/da9803487199abdfd77a47158ad4f89307d6639a/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L329)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

nit: why `null` instead of `Optional` to match existing pattern?
</blockquote></details>

changed it to use `Optional` now
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 341 at r1](https://reviewable.io/reviews/batfish/batfish/6685#-MUzK6UCCQwikqp4ST4R:-MUzOBASCz9nX5HfBwEE:bvnrpcm) ([raw file](https://github.com/batfish/batfish/blob/da9803487199abdfd77a47158ad4f89307d6639a/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L341)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Why not handle `null` in the caller instead of here?
</blockquote></details>

updated
___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/Service.java, line 39 at r1](https://reviewable.io/reviews/batfish/batfish/6685#-MUzKgqO60ny5PGTp6dK:-MUzMGsi2CvjWOM6EufF:bwuxquf) ([raw file](https://github.com/batfish/batfish/blob/da9803487199abdfd77a47158ad4f89307d6639a/projects/batfish/src/main/java/org/batfish/representation/fortios/Service.java#L39)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Why not just use `null` like everywhere else, and ditch `Protocol.UNKNOWN`? Is `Protocol.UNKNOWN` something you can set?
</blockquote></details>

it is not something you will see in the config; I was mainly trying to avoid `null` values here but it doesn't buy us much

**Review by arifogel — COMMENTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6685)* status: all files reviewed, 4 unresolved discussions (waiting on @corinaminer and @sfraint)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_service.g4, line 13 at r1](https://reviewable.io/reviews/batfish/batfish/6685#-MUzI_iCC72FLbFA_2Um:-MUzlesh9EITfbtQjmlD:b-9t565a) ([raw file](https://github.com/batfish/batfish/blob/da9803487199abdfd77a47158ad4f89307d6639a/projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_service.g4#L13)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

was trying to get the `set` syntax handled (quickly) first to unblock the firewall policy portion

I figure we're going to have to circle back for unset, references, and rename
</blockquote></details>

As long as it doesn't fall off the radar. But I don't want us to be in a situation where we have to go back and audit the whole thing because we don't know what we forgot.
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/FortiosLexer.g4, line 97 at r1](https://reviewable.io/reviews/batfish/batfish/6685#-MUzHlrbB2cINgey9J7G:-MUzlnL2BFOQ6Mhh5voT:b6yxt10) ([raw file](https://github.com/batfish/batfish/blob/da9803487199abdfd77a47158ad4f89307d6639a/projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/FortiosLexer.g4#L97)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

I left a TODO note in the `Fortios_service` file by the `service_port_range` rule, I can move it here if you prefer
</blockquote></details>

as long as there's a note
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 316 at r1](https://reviewable.io/reviews/batfish/batfish/6685#-MUzlMQN1PuMldsbqpIe:-MUzlMQN1PuMldsbqpIf:b-5dxz2i) ([raw file](https://github.com/batfish/batfish/blob/da9803487199abdfd77a47158ad4f89307d6639a/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L316)):*
> ```Java
>    * ports specified by the context.
>    */
>   private @Nonnull IntegerSpace toDstIntegerSpace(Service_port_rangesContext ctx) {
> ```

Why did you remove `@Nonnull`?
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 294 at r2](https://reviewable.io/reviews/batfish/batfish/6685#-MUzm7g_1qo-UvBOl4Ms:-MUzm7g_1qo-UvBOl4Mt:b-l95ud6) ([raw file](https://github.com/batfish/batfish/blob/07ce64be1488915bb4178c8b488318186f812fe7/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L294)):*
> ```Java
>     }
>     _currentService.setTcpPortRangeDst(toDstIntegerSpace(ctx.service_port_ranges()));
>     _currentService.setTcpPortRangeSrc(toSrcIntegerSpace(ctx.service_port_ranges()).orElse(null));
> ```

style option (do whatever you like better):
`_toSrcIntegerSpace(ctx.service_port_ranges()).ifPresent(_currentService::setTcpPortRanges)`

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6685)* status: all files reviewed, 4 unresolved discussions (waiting on @arifogel, @corinaminer, and @sfraint)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_service.g4, line 13 at r1](https://reviewable.io/reviews/batfish/batfish/6685#-MUzI_iCC72FLbFA_2Um:-MUzn6Y62aHqp7lVouJX:b-g3estj) ([raw file](https://github.com/batfish/batfish/blob/da9803487199abdfd77a47158ad4f89307d6639a/projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_service.g4#L13)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

As long as it doesn't fall off the radar. But I don't want us to be in a situation where we have to go back and audit the whole thing because we don't know what we forgot.
</blockquote></details>

we have an internal project board with the things we need to revisit

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6685)* status: 10 of 11 files reviewed, 3 unresolved discussions (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 316 at r1](https://reviewable.io/reviews/batfish/batfish/6685#-MUzlMQN1PuMldsbqpIe:-MUznMnJ7CrjCvcHvvOB:b-k8gb8x) ([raw file](https://github.com/batfish/batfish/blob/da9803487199abdfd77a47158ad4f89307d6639a/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L316)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Why did you remove `@Nonnull`?
</blockquote></details>

woops, re-added
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 294 at r2](https://reviewable.io/reviews/batfish/batfish/6685#-MUzm7g_1qo-UvBOl4Ms:-MUznGuD9F5AfdtewDVw:b-9xnf3a) ([raw file](https://github.com/batfish/batfish/blob/07ce64be1488915bb4178c8b488318186f812fe7/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L294)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

style option (do whatever you like better):
`_toSrcIntegerSpace(ctx.service_port_ranges()).ifPresent(_currentService::setTcpPortRanges)`
</blockquote></details>

but that doesn't set it to null if not present, right?

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6685)* status: all files reviewed, 2 unresolved discussions (waiting on @arifogel, @corinaminer, and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 294 at r2](https://reviewable.io/reviews/batfish/batfish/6685#-MUzm7g_1qo-UvBOl4Ms:-MUzrAYQ5OvOk7N2ffhq:bohardi) ([raw file](https://github.com/batfish/batfish/blob/07ce64be1488915bb4178c8b488318186f812fe7/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L294)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

but that doesn't set it to null if not present, right?
</blockquote></details>

right. If it must be set, you should leave as is.

**Pull request merged**
