### PR TITLE
A10: better handling of newlines

### PR DESCRIPTION
**Pull request by sfraint**
Make `NEWLINE` token consistent, grabbing _all_ newline chars.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7436)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @arifogel and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7436#-MkUDGN8BOdIVs9l7lq5:-MkUDGN8BOdIVs9l7lq6:begrhwa) (no related file):*
Why in parser instead of lexer? IIRC the perf from lexer was pretty strong. See the changes to NX-OS newlines.

---

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7436)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @arifogel and @dhalperi)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7436#-MkUDGN8BOdIVs9l7lq5:-MkcHn3NC4cO0D0JqgRK:b-mra3fh) (no related file):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Why in parser instead of lexer? IIRC the perf from lexer was pretty strong. See the changes to NX-OS newlines.
</blockquote></details>

ack, updated to handle in lexer instead

---

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7436)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @arifogel and @dhalperi)

___
*[projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Lexer.g4, line 114 at r7](https://reviewable.io/reviews/batfish/batfish/7436#-Mkcp7Ky0BJs1XP3MfJO:-Mkcp7Ky0BJs1XP3MfJP:bnapkig) ([raw file](https://github.com/batfish/batfish/blob/46d390100daadb72f3cbfcf432ed7eb0ef1ff53a/projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Lexer.g4#L114)):*
> ```
>   (F_Whitespace* F_NewlineChar+)+
> ```
opted to catch trailing whitespace here - could this be worse for performance than what we're doing in NXOS? `F_NewlineChar (F_Whitespace* F_NewlineChar+)*`

alternatively, can just consume optional trailing whitespace in the relevant lexer mode(s) below, e.g. `M_RbaLine`)

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7436)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @arifogel and @dhalperi)

___
*[projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Lexer.g4, line 114 at r7](https://reviewable.io/reviews/batfish/batfish/7436#-Mkcp7Ky0BJs1XP3MfJO:-MkcxmtXEiEoHYop9H0k:bux037x) ([raw file](https://github.com/batfish/batfish/blob/46d390100daadb72f3cbfcf432ed7eb0ef1ff53a/projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Lexer.g4#L114)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
>   (F_Whitespace* F_NewlineChar+)+
> ```
opted to catch trailing whitespace here - could this be worse for performance than what we're doing in NXOS? `F_NewlineChar (F_Whitespace* F_NewlineChar+)*`

alternatively, can just consume optional trailing whitespace in the relevant lexer mode(s) below, e.g. `M_RbaLine`)
</blockquote></details>

ok, chatted w/ @arifogel and made a couple small changes here and in the RBA line mode below - skipping whitespace, lexing `NEWLINE` token, and keeping `F_Newline` fragment consistent here and elsewhere

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 6 files at r3, 1 of 6 files at r4, 2 of 3 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7436)* status: 6 of 9 files reviewed, 2 unresolved discussions (waiting on @arifogel, @dhalperi, and @sfraint)

___
*[projects/batfish/src/test/resources/org/batfish/vendor/a10/grammar/testconfigs/newlines, line 1 at r8](https://reviewable.io/reviews/batfish/batfish/7436#-MkcycHA5nnLUwizMhV1:-MkcycHA5nnLUwizMhV2:b-n59kx6) ([raw file](https://github.com/batfish/batfish/blob/1fb7d779c258d19d91f700ec648e12b87327713a/projects/batfish/src/test/resources/org/batfish/vendor/a10/grammar/testconfigs/newlines#L1)):*
> ```
> !BATFISH_FORMAT: a10_acos
> ```

what newlines before?

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7436)* status: 6 of 9 files reviewed, 2 unresolved discussions (waiting on @arifogel and @dhalperi)

___
*[projects/batfish/src/test/resources/org/batfish/vendor/a10/grammar/testconfigs/newlines, line 1 at r8](https://reviewable.io/reviews/batfish/batfish/7436#-MkcycHA5nnLUwizMhV1:-Mkd-CvfCuF1fdyDezVL:b-7tfmjp) ([raw file](https://github.com/batfish/batfish/blob/1fb7d779c258d19d91f700ec648e12b87327713a/projects/batfish/src/test/resources/org/batfish/vendor/a10/grammar/testconfigs/newlines#L1)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

what newlines before?
</blockquote></details>

added

**Review by arifogel — COMMENTED** [review]
> Reviewed 3 of 6 files at r4, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7436)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi)

**Pull request merged**
