### PR TITLE
NXOS: parsing and extraction for `track`

### PR DESCRIPTION
**Pull request by sfraint**
Add initial parsing and extraction for [object `track`ing](https://www.cisco.com/c/en/us/td/docs/switches/datacenter/nexus9000/sw/6-x/unicast/configuration/guide/l3_cli_nxos/l3_object.html).

----

* Add parsing and extraction for interface tracking
* Remove grammar for unhandled tracking methods (for now...)
* Update track ID limits in a couple places (docs, e.g. [here](https://www.cisco.com/c/en/us/td/docs/switches/datacenter/nexus9000/sw/6-x/unicast/configuration/guide/l3_cli_nxos/l3_object.html) or [here](https://www.cisco.com/c/en/us/td/docs/switches/datacenter/nexus9000/sw/9-x/unicast/configuration/guide/l3_cli_nxos/l3_route.pdf) indicate track ID should be between 1 and 500)

### CODE REVIEW

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7068)* status: 0 of 13 files reviewed, all discussions resolved (waiting on @arifogel)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_common.g4, line 516 at r1](https://reviewable.io/reviews/batfish/batfish/7068#-McGzP4d6_hvFOIU3WtK:-McGzP4eEFyFdt-_iByV:buhtxhw) ([raw file](https://github.com/batfish/batfish/blob/e722dd284d783778c845da8c64fad90fd47686cc/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxos_common.g4#L516)):*
> ```
> // 1-500
> ```
docs, e.g. [here](https://www.cisco.com/c/en/us/td/docs/switches/datacenter/nexus9000/sw/6-x/unicast/configuration/guide/l3_cli_nxos/l3_object.html) or [here](https://www.cisco.com/c/en/us/td/docs/switches/datacenter/nexus9000/sw/9-x/unicast/configuration/guide/l3_cli_nxos/l3_route.pdf) indicate track ID should be between 1 and 500

**Review by corinaminer — COMMENTED** [review]
> Reviewed 12 of 13 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7068)* status: all files reviewed, 2 unresolved discussions (waiting on @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java, line 7273 at r2](https://reviewable.io/reviews/batfish/batfish/7068#-McLGUVY-6jpsAlMKkna:-McLGUVY-6jpsAlMKknb:b-yjspp3) ([raw file](https://github.com/batfish/batfish/blob/3350348d9f9532b1ce817cad2e50574d9ff7af54/projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java#L7273)):*
> ```Java
>   private @Nonnull Optional<String> toString(
>       ParserRuleContext messageCtx, Interface_nameContext ctx) {
>     return toString(messageCtx, ctx, CiscoNxosInterfaceType.ALL_INTERFACE_TYPES);
> ```

i'd probably just make the allowedTypes nullable rather than introducing `ALL_INTERFACE_TYPES`. this works too though; nonblocking.
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/StaticRoute.java, line 113 at r2](https://reviewable.io/reviews/batfish/batfish/7068#-McLGeMV2rxS3U6WnGUS:-McLGeMV2rxS3U6WnGUT:b75oowe) ([raw file](https://github.com/batfish/batfish/blob/3350348d9f9532b1ce817cad2e50574d9ff7af54/projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/StaticRoute.java#L113)):*
> ```Java
>   public static final IntegerSpace STATIC_ROUTE_PREFERENCE_RANGE =
>       IntegerSpace.of(Range.closed(1, 255));
>   public static final IntegerSpace STATIC_ROUTE_TRACK_RANGE = IntegerSpace.of(Range.closed(1, 500));
> ```

do we really need this field in addition to `TRACK_OBJECT_ID_RANGE`? Looks like `STATIC_ROUTE_TRACK_RANGE` is now only used in `StaticRoute.Builder.build()`; would it be incorrect to replace it with `TRACK_OBJECT_ID_RANGE` there?
___
*[projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_track_warn, line 6 at r2](https://reviewable.io/reviews/batfish/batfish/7068#-McLI3-wD3OIZ6NSHjQk:-McLI3-wD3OIZ6NSHjQl:bb7u544) ([raw file](https://github.com/batfish/batfish/blob/3350348d9f9532b1ce817cad2e50574d9ff7af54/projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_track_warn#L6)):*
> ```
> !
> 
> vrf context v1
> ```

unnecessary vrf?

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7068)* status: 9 of 14 files reviewed, 2 unresolved discussions (waiting on @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java, line 7273 at r2](https://reviewable.io/reviews/batfish/batfish/7068#-McLGUVY-6jpsAlMKkna:-McLKarc1uh-n4AWWAsh:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/3350348d9f9532b1ce817cad2e50574d9ff7af54/projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java#L7273)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

i'd probably just make the allowedTypes nullable rather than introducing `ALL_INTERFACE_TYPES`. this works too though; nonblocking.
</blockquote></details>

done
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/StaticRoute.java, line 113 at r2](https://reviewable.io/reviews/batfish/batfish/7068#-McLGeMV2rxS3U6WnGUS:-McLJAU27OPyI22v7SOj:b-w7r27z) ([raw file](https://github.com/batfish/batfish/blob/3350348d9f9532b1ce817cad2e50574d9ff7af54/projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/StaticRoute.java#L113)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

do we really need this field in addition to `TRACK_OBJECT_ID_RANGE`? Looks like `STATIC_ROUTE_TRACK_RANGE` is now only used in `StaticRoute.Builder.build()`; would it be incorrect to replace it with `TRACK_OBJECT_ID_RANGE` there?
</blockquote></details>

It does feel a bit redundant to have this in both places...but I don't think we should reference the extraction range from within the VS model class

Maybe I could just move this into the new `Track` VS model class - seems slightly cleaner to reference a VS model range during extraction than the other way around
___
*[projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_track_warn, line 6 at r2](https://reviewable.io/reviews/batfish/batfish/7068#-McLI3-wD3OIZ6NSHjQk:-McLKYUi8gzQQmtUvLHW:braxtvx) ([raw file](https://github.com/batfish/batfish/blob/3350348d9f9532b1ce817cad2e50574d9ff7af54/projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_track_warn#L6)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

unnecessary vrf?
</blockquote></details>

yep, removed

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7068)* status: 7 of 16 files reviewed, 2 unresolved discussions (waiting on @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/StaticRoute.java, line 113 at r2](https://reviewable.io/reviews/batfish/batfish/7068#-McLGeMV2rxS3U6WnGUS:-McLlshm19z1Y9hj-nqI:bdpntei) ([raw file](https://github.com/batfish/batfish/blob/3350348d9f9532b1ce817cad2e50574d9ff7af54/projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/StaticRoute.java#L113)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

It does feel a bit redundant to have this in both places...but I don't think we should reference the extraction range from within the VS model class

Maybe I could just move this into the new `Track` VS model class - seems slightly cleaner to reference a VS model range during extraction than the other way around
</blockquote></details>

Ended up just removing the redundant check from `StaticRoute` (just rely on extraction to validate like we do elsewhere) and also revamping the extractor check to match the newer `toIntegerInSpace` pattern

**Review by corinaminer — COMMENTED** [review]
:lgtm:

> Reviewed 9 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7068#-:-McM4u7a0MkSSUN5kpSs:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

**Pull request merged**
