### PR TITLE
New Transform reachability graph Transition using primed BDD variable encoding

### PR DESCRIPTION
**Pull request by anothermattbrown**
A reachability graph transition that transforms a variable number of variables by applying a relation over those variables and their primes.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8212)* status: 3 of 4 files reviewed, 5 unresolved discussions (waiting on @anothermattbrown and @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transform.java, line 35 at r1](https://reviewable.io/reviews/batfish/batfish/8212#-MzcHOzA53q2rt1FT4d5:-MzcHOzA53q2rt1FT4d6:b89sho8) ([raw file](https://github.com/batfish/batfish/blob/b8b5d9ad75b130166fd82f303bce084483db4d42/projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transform.java#L35)):*
> ```Java
>       init();
>     }
>     return bdd.applyEx(_forwardRelation, BDDFactory.and, _vars).replaceWith(_swapPairing);
> ```

doesn't `replaceWith` mutate `this` and free arg? Seems like it would break `_swapPairing`.



_Code quote:_
```Java
replaceWith
```
___
*[projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transform.java, line 54 at r1](https://reviewable.io/reviews/batfish/batfish/8212#-MzcHYVaAn83YspM-uaq:-MzcHYVaAn83YspM-uar:b-4i89jr) ([raw file](https://github.com/batfish/batfish/blob/b8b5d9ad75b130166fd82f303bce084483db4d42/projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transform.java#L54)):*
> ```Java
>    * Compose this {@link Transform} with another, if possible. The semantics is that they are
>    * applied in series -- first this, then other.
>    */
> ```

Maybe `tryCompose` and `tryOr`, below? Mirrors, e.g., `Integer.tryParse`.



_Code quote:_
```Java
compose
```
___
*[projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transform.java, line 60 at r1](https://reviewable.io/reviews/batfish/batfish/8212#-MzcHtPA0SJXCPWSuhGg:-MzcHtPA0SJXCPWSuhGh:b-ee8mna) ([raw file](https://github.com/batfish/batfish/blob/b8b5d9ad75b130166fd82f303bce084483db4d42/projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transform.java#L60)):*
> ```Java
>     if (!vars.diffSat(otherVars)) {
>       // vars are not disjoint so we can't compose
>       return Optional.empty();
> ```

`diffSat` doesn't imply disjoint, does it? E.g., `a.diff(a.and(b))` is satisfiable: `a.diff(b)`.



_Code quote:_
```Java
    if (!vars.diffSat(otherVars)) {
      // vars are not disjoint so we can't compose
      return Optional.empty();
```
___
*[projects/batfish/src/test/java/org/batfish/bddreachability/transition/TransformTest.java, line 134 at r1](https://reviewable.io/reviews/batfish/batfish/8212#-MzcKrbyCxh927E5aXJ_:-MzcKrbyCxh927E5aXJa:b-5kiqxs) ([raw file](https://github.com/batfish/batfish/blob/b8b5d9ad75b130166fd82f303bce084483db4d42/projects/batfish/src/test/java/org/batfish/bddreachability/transition/TransformTest.java#L134)):*
> ```Java
>     Transform composite = _transformX0.compose(_transformY).get();
>     assertEquals(x12.and(_y3), composite.transitForward(_x0.and(_y2)));
>     assertEquals(x12.and(_y3), composite.transitForward(_one));
> ```

I'm a little bit confused about these tests.. I kinda expected to see some test somewhere that "interpreted" the composition directly:

`assertThat(t1.transitForward(t0.transitForward(value)), equalTo(composite.transitForward(value))`

`assertThat(t0.transitForward(value).or(t1.transitForward(value)), equalTo(or.transitForward(value))`

and backwards versions.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPairingFactory.java, line 44 at r1](https://reviewable.io/reviews/batfish/batfish/8212#-MzcJwYWBpvjHbbzV-3J:-MzcJwYWBpvjHbbzV-3K:bv0rizf) ([raw file](https://github.com/batfish/batfish/blob/b8b5d9ad75b130166fd82f303bce084483db4d42/projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPairingFactory.java#L44)):*
> ```Java
>   }
> 
>   public BDD getDomainVarsBdd() {
> ```

javadoc?

function meaning, and note that the caller owns the result?

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8212)* status: 3 of 4 files reviewed, 5 unresolved discussions (waiting on @anothermattbrown and @corinaminer)

___
*[projects/batfish/src/test/java/org/batfish/bddreachability/transition/TransformTest.java, line 134 at r1](https://reviewable.io/reviews/batfish/batfish/8212#-MzcKrbyCxh927E5aXJ_:-MzcMLYi9ZBMLnemeI6w:b5vua6z) ([raw file](https://github.com/batfish/batfish/blob/b8b5d9ad75b130166fd82f303bce084483db4d42/projects/batfish/src/test/java/org/batfish/bddreachability/transition/TransformTest.java#L134)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I'm a little bit confused about these tests.. I kinda expected to see some test somewhere that "interpreted" the composition directly:

`assertThat(t1.transitForward(t0.transitForward(value)), equalTo(composite.transitForward(value))`

`assertThat(t0.transitForward(value).or(t1.transitForward(value)), equalTo(or.transitForward(value))`

and backwards versions.
</blockquote></details>

I also wonder if, if we had this, then we could just actually verify the correctness on all possible 4-bit BDDs.

**Review by anothermattbrown — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8212)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @corinaminer and @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transform.java, line 35 at r1](https://reviewable.io/reviews/batfish/batfish/8212#-MzcHOzA53q2rt1FT4d5:-MzpN_PWE18EihnQyWfP:b-vt9os5) ([raw file](https://github.com/batfish/batfish/blob/b8b5d9ad75b130166fd82f303bce084483db4d42/projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transform.java#L35)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

doesn't `replaceWith` mutate `this` and free arg? Seems like it would break `_swapPairing`.
</blockquote></details>

It does not free the pairing:
```
    @Override
    public BDD replaceWith(BDDPairing pair) {
      int x = _index;
      int y = bdd_replace(x, (bddPair) pair);
      bdd_delref(x);
      bdd_addref(y);
      _index = y;
      return this;
    }
```

Perhaps we should rename it `replaceEq`
___
*[projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transform.java, line 54 at r1](https://reviewable.io/reviews/batfish/batfish/8212#-MzcHYVaAn83YspM-uaq:-MzpNrpb8ta1NqtOgDPj:b-szhbky) ([raw file](https://github.com/batfish/batfish/blob/b8b5d9ad75b130166fd82f303bce084483db4d42/projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transform.java#L54)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Maybe `tryCompose` and `tryOr`, below? Mirrors, e.g., `Integer.tryParse`.
</blockquote></details>

sure, done.
___
*[projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transform.java, line 60 at r1](https://reviewable.io/reviews/batfish/batfish/8212#-MzcHtPA0SJXCPWSuhGg:-MzpOG1pDWkIQZe9ZsGl:b-bps4tv) ([raw file](https://github.com/batfish/batfish/blob/b8b5d9ad75b130166fd82f303bce084483db4d42/projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transform.java#L60)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

`diffSat` doesn't imply disjoint, does it? E.g., `a.diff(a.and(b))` is satisfiable: `a.diff(b)`.
</blockquote></details>

I'm relying on the assumption that these are the variable set encoding (i.e. an AND of a bunch of single-variable BDDs). I can

1. document and `assert` the assumption
2. use a more expensive/general check
3. something else.

My preference is 1 -- do you have a preference?
___
*[projects/batfish/src/test/java/org/batfish/bddreachability/transition/TransformTest.java, line 134 at r1](https://reviewable.io/reviews/batfish/batfish/8212#-MzcKrbyCxh927E5aXJ_:-Mzpdra8Dlgl9BASSzkc:b-36if9) ([raw file](https://github.com/batfish/batfish/blob/b8b5d9ad75b130166fd82f303bce084483db4d42/projects/batfish/src/test/java/org/batfish/bddreachability/transition/TransformTest.java#L134)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I also wonder if, if we had this, then we could just actually verify the correctness on all possible 4-bit BDDs.
</blockquote></details>

added those tests. 
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPairingFactory.java, line 44 at r1](https://reviewable.io/reviews/batfish/batfish/8212#-MzcJwYWBpvjHbbzV-3J:-MzpWAW8DECNgWcl7F49:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/b8b5d9ad75b130166fd82f303bce084483db4d42/projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDPairingFactory.java#L44)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

javadoc?

function meaning, and note that the caller owns the result?
</blockquote></details>

done

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8212)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @anothermattbrown, @corinaminer, and @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transform.java, line 60 at r1](https://reviewable.io/reviews/batfish/batfish/8212#-MzcHtPA0SJXCPWSuhGg:-MzpqgSx9eQ-UiD4WbrH:br3zqw5) ([raw file](https://github.com/batfish/batfish/blob/b8b5d9ad75b130166fd82f303bce084483db4d42/projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transform.java#L60)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

I'm relying on the assumption that these are the variable set encoding (i.e. an AND of a bunch of single-variable BDDs). I can

1. document and `assert` the assumption
2. use a more expensive/general check
3. something else.

My preference is 1 -- do you have a preference?
</blockquote></details>

I don't see why it's correct even given that restriction - the `diffSat` doesn't know that.

e.g.,
```
a = ithVar(0).and(ithVar(1);
b = ithVar(0);
```

`a.diffSat(b)` is true per the library but there is not an answer that is a var assignment.

If I'm missing something, comment and assert is fine :)

**Review by anothermattbrown — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8212)* status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @corinaminer and @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transform.java, line 60 at r1](https://reviewable.io/reviews/batfish/batfish/8212#-MzcHtPA0SJXCPWSuhGg:-MzpwWUQ5dfe4ZeEavZw:bjq5y4p) ([raw file](https://github.com/batfish/batfish/blob/b8b5d9ad75b130166fd82f303bce084483db4d42/projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transform.java#L60)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I don't see why it's correct even given that restriction - the `diffSat` doesn't know that.

e.g.,
```
a = ithVar(0).and(ithVar(1);
b = ithVar(0);
```

`a.diffSat(b)` is true per the library but there is not an answer that is a var assignment.

If I'm missing something, comment and assert is fine :)
</blockquote></details>

You're right, thanks. Fixed

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8212)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8212)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

**Pull request merged**
