### PR TITLE
CheckPoint mgmt service-other match grammar

### PR DESCRIPTION
**Pull request by arifogel**
- add parboiled grammar and tests for parsing `match` field of `service-other` object

### CODE REVIEW

**Review by corinaminer — COMMENTED** [review]
> Reviewed 9 of 25 files at r1, 7 of 20 files at r4, 18 of 33 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7425)* status: 24 of 42 files reviewed, 1 unresolved discussion (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/parsing/parboiled/Uint16AstNode.java, line 34 at r5](https://reviewable.io/reviews/batfish/batfish/7425#-MkJqIEX3pwoK85fBnnj:-MkJqIEY---5oovGfYaX:b-1mt8e9) ([raw file](https://github.com/batfish/batfish/blob/e79f0ac99c99486d4361105c13731a2fbfcf34ad/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/parsing/parboiled/Uint16AstNode.java#L34)):*
> ```Java
>   }
> 
>   static Uint16AstNode of(int value) {
> ```

can this be private? or alternatively, should the `0 <= value && value <= 0xFFFF` be here?

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7425)* status: 23 of 42 files reviewed, 1 unresolved discussion (waiting on @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/parsing/parboiled/Uint16AstNode.java, line 34 at r5](https://reviewable.io/reviews/batfish/batfish/7425#-MkJqIEX3pwoK85fBnnj:-MkK-KbG-ZQjNcrYIoIt:b-grjfm6) ([raw file](https://github.com/batfish/batfish/blob/e79f0ac99c99486d4361105c13731a2fbfcf34ad/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/parsing/parboiled/Uint16AstNode.java#L34)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

can this be private? or alternatively, should the `0 <= value && value <= 0xFFFF` be here?
</blockquote></details>

It cannot be private because it is used in production code.
Moved the check.

**Review by corinaminer — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, 2 of 5 files at r3, 15 of 33 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7425)* status: all files reviewed, 2 unresolved discussions (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/parsing/parboiled/ServiceOtherMatchExpr.java, line 157 at r6](https://reviewable.io/reviews/batfish/batfish/7425#-MkKQvivCiI6YnHmmIdI:-MkKQvivCiI6YnHmmIdJ:bnvd93o) ([raw file](https://github.com/batfish/batfish/blob/c770c7713f400ce2b3d6a79979e5d6ca892b568f/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/parsing/parboiled/ServiceOtherMatchExpr.java#L157)):*
> ```Java
> 
>   Rule WhiteSpace() {
>     return ZeroOrMore(AnyOf(" "));
> ```

is the `AnyOf` doing anything? Looks like just a space in there. possibly autoformatting removed some other whitespace chars?
___
*[projects/batfish/src/test/java/org/batfish/vendor/check_point_management/parsing/parboiled/UhDportAstNodeTest.java, line 7 at r6](https://reviewable.io/reviews/batfish/batfish/7425#-MkKSBSG6_BN04beSYsJ:-MkKSBSG6_BN04beSYsK:b-tsfben) ([raw file](https://github.com/batfish/batfish/blob/c770c7713f400ce2b3d6a79979e5d6ca892b568f/projects/batfish/src/test/java/org/batfish/vendor/check_point_management/parsing/parboiled/UhDportAstNodeTest.java#L7)):*
> ```Java
> 
> /** Test of {@link UhDportAstNode}. */
> public final class UhDportAstNodeTest {
> ```

missing serialization test
___
*[projects/batfish/src/test/java/org/batfish/vendor/check_point_management/parsing/parboiled/Uint16AstNodeTest.java, line 24 at r6](https://reviewable.io/reviews/batfish/batfish/7425#-MkKSRCd4wW9_3QAMhji:-MkKSRCd4wW9_3QAMhjj:b-rn8isk) ([raw file](https://github.com/batfish/batfish/blob/c770c7713f400ce2b3d6a79979e5d6ca892b568f/projects/batfish/src/test/java/org/batfish/vendor/check_point_management/parsing/parboiled/Uint16AstNodeTest.java#L24)):*
> ```Java
>   public void testOfInvalidNotNumber() {
>     _thrown.expect(IllegalArgumentException.class);
>     Uint16AstNode.of("-1");
> ```

i think this one's supposed to have a non-numeric arg

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7425)* status: all files reviewed, 2 unresolved discussions (waiting on @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/parsing/parboiled/ServiceOtherMatchExpr.java, line 157 at r6](https://reviewable.io/reviews/batfish/batfish/7425#-MkKQvivCiI6YnHmmIdI:-MkKYjIr-jOTwb5D7Fhf:b-yarfk1) ([raw file](https://github.com/batfish/batfish/blob/c770c7713f400ce2b3d6a79979e5d6ca892b568f/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/parsing/parboiled/ServiceOtherMatchExpr.java#L157)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

is the `AnyOf` doing anything? Looks like just a space in there. possibly autoformatting removed some other whitespace chars?
</blockquote></details>

`AnyOf` prevents the `" "` from being treated as a string literal. String literals have a `WhiteSpace()` inserted after them (see override of `fromStringLiteral`). Without the `AnyOf`, this recurses forever.
___
*[projects/batfish/src/test/java/org/batfish/vendor/check_point_management/parsing/parboiled/UhDportAstNodeTest.java, line 7 at r6](https://reviewable.io/reviews/batfish/batfish/7425#-MkKSBSG6_BN04beSYsJ:-MkKZEx89nCPffytsiR4:b-7tfmjp) ([raw file](https://github.com/batfish/batfish/blob/c770c7713f400ce2b3d6a79979e5d6ca892b568f/projects/batfish/src/test/java/org/batfish/vendor/check_point_management/parsing/parboiled/UhDportAstNodeTest.java#L7)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

missing serialization test
</blockquote></details>

added
___
*[projects/batfish/src/test/java/org/batfish/vendor/check_point_management/parsing/parboiled/Uint16AstNodeTest.java, line 24 at r6](https://reviewable.io/reviews/batfish/batfish/7425#-MkKSRCd4wW9_3QAMhji:-MkKZXwd9OswJDRqO4te:b-7ql1td) ([raw file](https://github.com/batfish/batfish/blob/c770c7713f400ce2b3d6a79979e5d6ca892b568f/projects/batfish/src/test/java/org/batfish/vendor/check_point_management/parsing/parboiled/Uint16AstNodeTest.java#L24)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

i think this one's supposed to have a non-numeric arg
</blockquote></details>

fixed

**Review by corinaminer — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7425#-:-MkNr8S2Bfp91h_FGzYC:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Pull request merged**
