### PR TITLE
A10: Use PacketPolicy for NAT

### PR DESCRIPTION
**Pull request by sfraint**
Switch to encoding NAT transformations in PacketPolicy.

----

This is in preparation for adding support for ACLs.

ACLs and NAT transformations rely on the same virtual-server and virtual-server port matching logic, so it will be simple and less redundant to apply ACLs in PacketPolicy.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7833)* status: all files reviewed, 3 unresolved discussions (waiting on @arifogel and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/vendor/a10/representation/TraceElements.java, line 20 at r1](https://reviewable.io/reviews/batfish/batfish/7833#-MrOGdpPCvECT2JDdB7j:-MrOGdpPCvECT2JDdB7k:b-6t38tz) ([raw file](https://github.com/batfish/batfish/blob/bb694571a233fb4b1b4562fb35c57093a56f3b90/projects/batfish/src/main/java/org/batfish/vendor/a10/representation/TraceElements.java#L20)):*
> ```Java
>   public static TraceElement traceElementForVirtualServerPort(VirtualServerPort port) {
>     return TraceElement.builder()
>         .add(String.format("Matched %s %s", port.getType().toString(), toPortString(port)))
> ```

should this have VSID?
___
*[projects/batfish/src/main/java/org/batfish/vendor/a10/representation/TraceElements.java, line 24 at r1](https://reviewable.io/reviews/batfish/batfish/7833#-MrOGhMTAgqSZMH62h3a:-MrOGhMTAgqSZMH62h3b:b6fhrfi) ([raw file](https://github.com/batfish/batfish/blob/bb694571a233fb4b1b4562fb35c57093a56f3b90/projects/batfish/src/main/java/org/batfish/vendor/a10/representation/TraceElements.java#L24)):*
> ```Java
>   }
> 
>   public static String toPortString(VirtualServerPort port) {
> ```

this needs to be public?
___
*[projects/batfish/src/main/java/org/batfish/vendor/a10/representation/TraceElements.java, line 27 at r1](https://reviewable.io/reviews/batfish/batfish/7833#-MrOHCcU34vItT4TS6t5:-MrOHCcU34vItT4TS6t6:b-147xk6) ([raw file](https://github.com/batfish/batfish/blob/bb694571a233fb4b1b4562fb35c57093a56f3b90/projects/batfish/src/main/java/org/batfish/vendor/a10/representation/TraceElements.java#L27)):*
> ```Java
>     if (port.getRange() != null) {
>       return String.format("ports %d-%d", port.getNumber(), port.getNumber() + port.getRange());
>     }
> ```

I was surprised so see "number" and "range" used for "lower and number of additional ports, inclusive". That's really the semantics, with fence posting?

E.g., number = 1, range=10 means "1-11"?

Tried to look at java code, did not succeed.



_Code quote:_
```Java
    if (port.getRange() != null) {
      return String.format("ports %d-%d", port.getNumber(), port.getNumber() + port.getRange());
    }
```

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7833)* status: all files reviewed, 3 unresolved discussions (waiting on @arifogel and @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/vendor/a10/representation/TraceElements.java, line 20 at r1](https://reviewable.io/reviews/batfish/batfish/7833#-MrOGdpPCvECT2JDdB7j:-MrOL3Qr22HOVrB_Rbsl:bxpi0e8) ([raw file](https://github.com/batfish/batfish/blob/bb694571a233fb4b1b4562fb35c57093a56f3b90/projects/batfish/src/main/java/org/batfish/vendor/a10/representation/TraceElements.java#L20)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

should this have VSID?
</blockquote></details>

we're not tracking ports separate from servers - I can add a server link here if you think that is appropriate (but we're already linking to the server in the previous traceElement)
___
*[projects/batfish/src/main/java/org/batfish/vendor/a10/representation/TraceElements.java, line 24 at r1](https://reviewable.io/reviews/batfish/batfish/7833#-MrOGhMTAgqSZMH62h3a:-MrOL19qBTGuBVOzxxz_:b-8k5n1k) ([raw file](https://github.com/batfish/batfish/blob/bb694571a233fb4b1b4562fb35c57093a56f3b90/projects/batfish/src/main/java/org/batfish/vendor/a10/representation/TraceElements.java#L24)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

this needs to be public?
</blockquote></details>

not currently, removed
___
*[projects/batfish/src/main/java/org/batfish/vendor/a10/representation/TraceElements.java, line 27 at r1](https://reviewable.io/reviews/batfish/batfish/7833#-MrOHCcU34vItT4TS6t5:-MrOKQhSAHe_bAQnXA86:b-wnrbgm) ([raw file](https://github.com/batfish/batfish/blob/bb694571a233fb4b1b4562fb35c57093a56f3b90/projects/batfish/src/main/java/org/batfish/vendor/a10/representation/TraceElements.java#L27)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I was surprised so see "number" and "range" used for "lower and number of additional ports, inclusive". That's really the semantics, with fence posting?

E.g., number = 1, range=10 means "1-11"?

Tried to look at java code, did not succeed.
</blockquote></details>

Yes, sadly. Also, if you dump an A10 config with default values, a single port would show up like: `port 443 tcp range 0`

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7833)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @arifogel and @dhalperi)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7833)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Review by arifogel — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7833)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

**Pull request merged**
