### PR TITLE
Junos: Add parsing for firewall ipv4 filter commands

### PR DESCRIPTION
**Pull request by pranavbj-amzn**
Add parsing and `todo` for firewall `ipv4` filter commands.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8913)* status: all files reviewed, 2 unresolved discussions (waiting on @pranavbj-amzn)

___
*[`projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_firewall.g4` line 329 at r1](https://reviewable.io/reviews/batfish/batfish/8913#-NnGCYcDDUyqJPau51CV:-NnGCYcDDUyqJPau51CW:b-fudsjh) ([raw file](https://github.com/batfish/batfish/blob/0a0cc1bc46df91497b9cce92f7b7fba0065915aa/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_firewall.g4#L329)):*
> ```ANTLR
>    (
>      ip_protocol
>      | IPV6
> ```

this should already be in `ip_protocol` if it isn't. The value is 41 -- `IpProtocol#IPV6`.



_Code quote:_
```ANTLR
 IPV6
```
___
*[`projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_firewall.g4` line 384 at r1](https://reviewable.io/reviews/batfish/batfish/8913#-NnGCdfg0_yrLfMQYKfk:-NnGCdfg0_yrLfMQYKfl:b-7m74ok) ([raw file](https://github.com/batfish/batfish/blob/0a0cc1bc46df91497b9cce92f7b7fba0065915aa/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_firewall.g4#L384)):*
> ```ANTLR
> fftt_decapsulate
> :
>    DECAPSULATE GRE
> ```

nice.
___
*[`projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java` line 4752 at r1](https://reviewable.io/reviews/batfish/batfish/8913#-NnGChfNAT4ASRxWgA58:-NnGChfNAT4ASRxWgA59:bsmfnch) ([raw file](https://github.com/batfish/batfish/blob/0a0cc1bc46df91497b9cce92f7b7fba0065915aa/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L4752)):*
> ```Java
>   @Override
>   public void exitFftf_protocol(Fftf_protocolContext ctx) {
>     if (ctx.IPV6() != null) {
> ```

see other comment.

**Review by pranavbj-amzn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8913)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @dhalperi)

___
*[`projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_firewall.g4` line 329 at r1](https://reviewable.io/reviews/batfish/batfish/8913#-NnGCYcDDUyqJPau51CV:-NnGT6ILD0TXDhj5GCBa:bv1nw4k) ([raw file](https://github.com/batfish/batfish/blob/0a0cc1bc46df91497b9cce92f7b7fba0065915aa/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_firewall.g4#L329)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

this should already be in `ip_protocol` if it isn't. The value is 41 -- `IpProtocol#IPV6`.
</blockquote></details>

fixed, reused from within `ip_protocol`
___
*[`projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java` line 4752 at r1](https://reviewable.io/reviews/batfish/batfish/8913#-NnGChfNAT4ASRxWgA58:-NnGTRAz7bKpONnXKyBc:b-e3ku5j) ([raw file](https://github.com/batfish/batfish/blob/0a0cc1bc46df91497b9cce92f7b7fba0065915aa/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L4752)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

see other comment.
</blockquote></details>

added as part of `ip_protocol` , though kept handling as `todo` specifically for `IPV6`

**Review by dhalperi — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8913)* status: all files reviewed, 2 unresolved discussions (waiting on @pranavbj-amzn)

___
*[`projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java` line 4752 at r1](https://reviewable.io/reviews/batfish/batfish/8913#-NnGChfNAT4ASRxWgA58:-NnGTd656YfWYLpoGnQl:b-vhuohh) ([raw file](https://github.com/batfish/batfish/blob/0a0cc1bc46df91497b9cce92f7b7fba0065915aa/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L4752)):*
<details><summary><i>Previously, pranavbj-amzn (Pranav Bhardwaj) wrote…</i></summary><blockquote>

added as part of `ip_protocol` , though kept handling as `todo` specifically for `IPV6`
</blockquote></details>

I don't think we need the todo, this is correct as-is.

The part that needs the TODO is on the decapsulation.
___
*[`projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java` line 1997 at r2](https://reviewable.io/reviews/batfish/batfish/8913#-NnGTYzh4wXW6ujyOFYy:-NnGTYzh4wXW6ujyOFYz:bjnotzo) ([raw file](https://github.com/batfish/batfish/blob/877473102435d9a5f2071741779c4a2efcda1db5/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L1997)):*
> ```Java
>       return IpProtocol.VRRP;
>     } else if (ctx.IPV6() != null) {
>       return IpProtocol.IPV6;
> ```

alphabetize by `ctx.FOO()` -- so after `IPINIP`.

**Review by pranavbj-amzn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8913)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[`projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java` line 4752 at r1](https://reviewable.io/reviews/batfish/batfish/8913#-NnGChfNAT4ASRxWgA58:-NnGWjyDDL1KCxQtcUq3:b-8lb063) ([raw file](https://github.com/batfish/batfish/blob/0a0cc1bc46df91497b9cce92f7b7fba0065915aa/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L4752)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I don't think we need the todo, this is correct as-is.

The part that needs the TODO is on the decapsulation.
</blockquote></details>

removed TODO here
___
*[`projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java` line 1997 at r2](https://reviewable.io/reviews/batfish/batfish/8913#-NnGTYzh4wXW6ujyOFYy:-NnGWigI02txnBFwJ9OQ:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/877473102435d9a5f2071741779c4a2efcda1db5/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L1997)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

alphabetize by `ctx.FOO()` -- so after `IPINIP`.
</blockquote></details>

done

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8913)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pranavbj-amzn)

**Pull request merged**
