### PR TITLE
Fix HSRP model and implementation

### PR DESCRIPTION
**Pull request by arifogel**
- apply relevant fixes to VRRP model and implementation to HSRP
  - stop using Identity collections
  - only compete in same broadcast domain
  - add sourceAddress to model
  - remove redundant group number from model

Follow-on work: HSRP properties question

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 13 of 17 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7965)* status: 14 of 17 files reviewed, 2 unresolved discussions (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/InterfaceAddressWithAttributes.java, line 20 at r2](https://reviewable.io/reviews/batfish/batfish/7965#-Mu-6JeO8_TWoPAaU2Ni:-Mu-6JeO8_TWoPAaU2Nj:byzjrzi) ([raw file](https://github.com/batfish/batfish/blob/f3f462909e4c4b649a080c21f2f3bed9ca1d4f3a/projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/InterfaceAddressWithAttributes.java#L20)):*
> ```Java
>   }
> 
>   public @Nonnull ConcreteInterfaceAddress getAddress() {
> ```

I believe this is not a safe change. Why can't there be tags for an unnumbered interface route?
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/IpOwners.java, line 476 at r2](https://reviewable.io/reviews/batfish/batfish/7965#-Mu-6YAK5KhQOfNsB8ul:-Mu-6YAK5KhQOfNsB8um:bfizqns) ([raw file](https://github.com/batfish/batfish/blob/f3f462909e4c4b649a080c21f2f3bed9ca1d4f3a/projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/IpOwners.java#L476)):*
> ```Java
> 
>   /**
>    * Partitions the input set of HSPR/VRRP candidates into subsets where all candidates are in the
> ```

typo: HSRP

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7965)* status: 14 of 17 files reviewed, 1 unresolved discussion (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/InterfaceAddressWithAttributes.java, line 20 at r2](https://reviewable.io/reviews/batfish/batfish/7965#-Mu-6JeO8_TWoPAaU2Ni:-Mu-B9Uk4YZOj7kgOqCJ:b-1e1ppf) ([raw file](https://github.com/batfish/batfish/blob/f3f462909e4c4b649a080c21f2f3bed9ca1d4f3a/projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/InterfaceAddressWithAttributes.java#L20)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I believe this is not a safe change. Why can't there be tags for an unnumbered interface route?
</blockquote></details>

NM I'm crazy. At least for now.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 3 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7965)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel and @corinaminer)

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7965)* status: all files reviewed, 1 unresolved discussion (waiting on @corinaminer and @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/InterfaceAddressWithAttributes.java, line 20 at r2](https://reviewable.io/reviews/batfish/batfish/7965#-Mu-6JeO8_TWoPAaU2Ni:-Mu-90nFDC2aMyPpzZfp:b-pjpsth) ([raw file](https://github.com/batfish/batfish/blob/f3f462909e4c4b649a080c21f2f3bed9ca1d4f3a/projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/InterfaceAddressWithAttributes.java#L20)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

NM I'm crazy. At least for now.
</blockquote></details>

I was going off the only usages I saw. To be honest, I was a bit uncomfortable about this.
Solved without this change
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/IpOwners.java, line 476 at r2](https://reviewable.io/reviews/batfish/batfish/7965#-Mu-6YAK5KhQOfNsB8ul:-Mu-8yzE8XDuJ75TTEZ9:b-7ql1td) ([raw file](https://github.com/batfish/batfish/blob/f3f462909e4c4b649a080c21f2f3bed9ca1d4f3a/projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/IpOwners.java#L476)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

typo: HSRP
</blockquote></details>

fixed

**Review by dhalperi — COMMENTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7965)* status: all files reviewed, 1 unresolved discussion (waiting on @corinaminer and @dhalperi)

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7965)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

**Pull request merged**
