### PR TITLE
Cisco: parse ospf default metric

### PR DESCRIPTION
**Pull request by dhalperi**

### CODE REVIEW

**Comment by progwriter** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1123#-:-L9IEdkmCe3oavy1TUsu:bnfp4nl)*

**Comment by arifogel** [comment]
:lgtm: if values are validated

---

Reviewed 4 of 4 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/OspfProcess.java, line 107 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1123#-L9LtehE0wuZu_L3Ypwu:-L9LtehE0wuZu_L3Ypwv:bxhdn03) ([raw file](https://github.com/batfish/batfish/blob/b8d592bb689e932017060a1908a62ad9c3afba7b/projects/batfish/src/main/java/org/batfish/representation/cisco/OspfProcess.java#L107)):*
> ```Java
>   }
> 
>   public long getDefaultMetric(ConfigurationFormat format, RoutingProtocol protocol) {
> ```

For the ones not explicitly documented, I would feel much more comfortable if you can tell me you have tested them on actual devices.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1123#-:-L9LuEL_9sGG6ZoFqmoB:b-luqp9k)*

**Comment by dhalperi** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/OspfProcess.java, line 107 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1123#-L9LtehE0wuZu_L3Ypwu:-L9O_Ayi8Q5hXkLfN5Di:b6360iv) ([raw file](https://github.com/batfish/batfish/blob/b8d592bb689e932017060a1908a62ad9c3afba7b/projects/batfish/src/main/java/org/batfish/representation/cisco/OspfProcess.java#L107)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

For the ones not explicitly documented, I would feel much more comfortable if you can tell me you have tested them on actual devices.
</blockquote></details>


Vetted Cisco and NXOS manually. Before we assumed everything was 20, this is a strict improvement. More vetting needed for sure, however, as we get more VMs.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1123)*

**Comment by dhalperi** [comment]
Reviewed 1 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1123)*

**Pull request merged**
