### PR TITLE
Checkpoint convert and attach transformation and firewall session info

### PR DESCRIPTION
**Pull request by arifogel**

### CODE REVIEW

**Review by sfraint — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7319)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Review by arifogel — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7319)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Review by sfraint — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7319)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Review by arifogel — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7319)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @arifogel and @sfraint)

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7319)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Pull request merged**
