### PR TITLE
CheckPoint: add IpSpaceMetadata

### PR DESCRIPTION
**Pull request by sfraint**
This will help make address-based traces better.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7381)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @corinaminer and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/AddressSpaceToIpSpaceMetadata.java, line 10 at r1](https://reviewable.io/reviews/batfish/batfish/7381#-MjW98VGAy2sYIg0_19p:-MjW98VH2I2fAfPiXik5:b-5fom4k) ([raw file](https://github.com/batfish/batfish/blob/45d097e58bdeb497977c0f039deedda9c8c47af8/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/AddressSpaceToIpSpaceMetadata.java#L10)):*
> ```
> CpmiAny
> ```
is `CpmiAny` user facing (in the web UI)?
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/AddressSpaceToIpSpaceMetadata.java, line 21 at r1](https://reviewable.io/reviews/batfish/batfish/7381#-MjW9EXs0YATwZHIgQb3:-MjW9EXs0YATwZHIgQb4:b-a6a2dx) ([raw file](https://github.com/batfish/batfish/blob/45d097e58bdeb497977c0f039deedda9c8c47af8/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/AddressSpaceToIpSpaceMetadata.java#L21)):*
> ```
> gatewayOrServer.getClass().getSimpleName()
> ```

What is the user-facing concept here? Our internal class names are not great. If nothing else, hardcode "GatewayOrServer" (tho case matching doesn't seem right with other groups).
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/AddressSpaceToIpSpaceMetadata.java, line 39 at r1](https://reviewable.io/reviews/batfish/batfish/7381#-MjW9OTnDORYYxNddi8I:-MjW9OTnDORYYxNddi8J:b90d185) ([raw file](https://github.com/batfish/batfish/blob/45d097e58bdeb497977c0f039deedda9c8c47af8/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/AddressSpaceToIpSpaceMetadata.java#L39)):*
> ```Java
>   }
> 
>   public AddressSpaceToIpSpaceMetadata() {}
> ```

Since this is stateless, I'd probably:

1. make this private
2. create a private static final INSTANCE
3. add a public static method toIpSpaceMetadata(AddressSpace space)

and then get rid of the construction above.

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7381)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @corinaminer and @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/AddressSpaceToIpSpaceMetadata.java, line 10 at r1](https://reviewable.io/reviews/batfish/batfish/7381#-MjW98VGAy2sYIg0_19p:-MjWD5Jj67xXo-NrNx_k:b8pcydx) ([raw file](https://github.com/batfish/batfish/blob/45d097e58bdeb497977c0f039deedda9c8c47af8/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/AddressSpaceToIpSpaceMetadata.java#L10)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> CpmiAny
> ```
is `CpmiAny` user facing (in the web UI)?
</blockquote></details>

In the management UI they're going to see the object's icon and name (`*` `Any`) primarily.

I'm not sure how visible the type string is in the GUI, but the object type in the JSON representation is `CpmiAnyObject`.
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/AddressSpaceToIpSpaceMetadata.java, line 21 at r1](https://reviewable.io/reviews/batfish/batfish/7381#-MjW9EXs0YATwZHIgQb3:-MjWB3VaAER2WeYZI6PR:b2fjkex) ([raw file](https://github.com/batfish/batfish/blob/45d097e58bdeb497977c0f039deedda9c8c47af8/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/AddressSpaceToIpSpaceMetadata.java#L21)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> gatewayOrServer.getClass().getSimpleName()
> ```

What is the user-facing concept here? Our internal class names are not great. If nothing else, hardcode "GatewayOrServer" (tho case matching doesn't seem right with other groups).
</blockquote></details>

The user sees a variety of types of objects (at least as icons in the GUI and as a type string in the JSON), but the object names are the most visible piece, but I think `Gateways and Server` is a menu item when searching objects in the GUI, so that seems like a reasonable option.

Also, our class names aren't a perfect representation of all the type strings the end-user would see (e.g. `simple-gateway` vs `SimpleGateway`), but for Cpmi objects like `CpmiClusterMember` that is actually the same object type string they would see in the JSON representation.
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/AddressSpaceToIpSpaceMetadata.java, line 39 at r1](https://reviewable.io/reviews/batfish/batfish/7381#-MjW9OTnDORYYxNddi8I:-MjWHc1u9bxGIKkxwItk:bvnrpcm) ([raw file](https://github.com/batfish/batfish/blob/45d097e58bdeb497977c0f039deedda9c8c47af8/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/AddressSpaceToIpSpaceMetadata.java#L39)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Since this is stateless, I'd probably:

1. make this private
2. create a private static final INSTANCE
3. add a public static method toIpSpaceMetadata(AddressSpace space)

and then get rid of the construction above.
</blockquote></details>

updated

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7381)* status: all files reviewed, 1 unresolved discussion (waiting on @corinaminer and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/AddressSpaceToIpSpaceMetadata.java, line 7 at r3](https://reviewable.io/reviews/batfish/batfish/7381#-MjWLtcqApOtKFKgUWZU:-MjWLtcqApOtKFKgUWZV:b8xg1e1) ([raw file](https://github.com/batfish/batfish/blob/46878fe37e3fe2fdc5b45b0b44b92e3a55203931/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/AddressSpaceToIpSpaceMetadata.java#L7)):*
> ```
> public
> ```
private

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7381)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

**Pull request merged**
