### PR TITLE
Ye mo parsing

### PR DESCRIPTION
**Pull request by ratulm**

### CODE REVIEW

**Comment by arifogel** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_qos.g4, line 592 at r2](https://reviewable.io/reviews/batfish/batfish/1532#-LDrFnCABHfAWk8U2R_p:-LDrFnCABHfAWk8U2R_q:biwi2ro) ([raw file](https://github.com/batfish/batfish/blob/7ca83a5722312a7ae64e505d3bf8f954946d29c3/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_qos.g4#L592)):*
> ```ANTLR
>      | classname = variable
>    )
>    // TODO: after we solve token overload, change variable to do-until-failure
> ```

We merged fix for token overload.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 470 at r2](https://reviewable.io/reviews/batfish/batfish/1532#-LDrG5t57vtJ9l7CZP7t:-LDrG5t57vtJ9l7CZP7u:bq56epg) ([raw file](https://github.com/batfish/batfish/blob/7ca83a5722312a7ae64e505d3bf8f954946d29c3/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L470)):*
> ```Java
>     _cf = new CiscoFamily();
>     _classMapAccessGroups = new TreeSet<>();
>     _classMapAccessLists = new TreeSet<>();
> ```

Can we get rid of this (and also `_classMapAccessGroups`) now? I thought we don't need these sets for reference tracking anymore.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1532)*

**Comment by ratulm** [comment]
Review status: 9 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_qos.g4, line 592 at r2](https://reviewable.io/reviews/batfish/batfish/1532#-LDrFnCABHfAWk8U2R_p:-LDrLPTR1op8Mift-5ar:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/7ca83a5722312a7ae64e505d3bf8f954946d29c3/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_qos.g4#L592)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

We merged fix for token overload.
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 470 at r2](https://reviewable.io/reviews/batfish/batfish/1532#-LDrG5t57vtJ9l7CZP7t:-LDrM1LL8jX9tGyNaj61:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/7ca83a5722312a7ae64e505d3bf8f954946d29c3/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L470)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Can we get rid of this (and also `_classMapAccessGroups`) now? I thought we don't need these sets for reference tracking anymore.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1532)*

**Comment by arifogel** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1532#-:-LDrPrAd03ix-60ZTovZ:bnfp4nl)*

**Comment by arifogel** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1532)*

**Pull request merged**
