### PR TITLE
Juniper: parse bgp enforce-first-as

### PR DESCRIPTION
**Pull request by progwriter**
This is parsing & datamodel support only; Dataplane plumbing coming next

### CODE REVIEW

**Comment by dhalperi** [comment]
Discussion questions:

* does this go in the VI model directly, or should it just be modeled as (e.g.) the first statement of an import policy? @arifogel is there an obvious answer?
* Btw, fyi, this looks like the default on Cisco, at least some flavors: https://www.cisco.com/c/en/us/td/docs/routers/crs/software/crs_r4-2/routing/command/reference/b_routing_cr42crs/b_routing_cr42crs_chapter_01.html#wp2530843280

---

Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java, line 347 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1168#-LA6nGwo7Ck424CzwN58:-LA6nGwo7Ck424CzwN59:b736acn) ([raw file](https://github.com/batfish/batfish/blob/40f77f36a6b34460425e51cd188c7076cd2bae72/projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java#L347)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>       Boolean enforceFirstAs = ig.getEnforceFirstAs();
>       if (enforceFirstAs == null) {
>         enforceFirstAs = false;
>       }
>       neighbor.setEnforceFirstAs(enforceFirstAs);
> ```
</details>


presumably the ordering here is a bit messed up? shouldn't `setEbgpMultihop` be with the one above?

Btw, why not just `neighbor.setEnforceFirstAs(firstNonNull(ig.getEnforceFirstAs(), Boolean.FALSE))`? Seems a little more straightforward.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1168#-:-LA6oLtM5o5-rxlX6Zld:b-st1fs7)*

**Comment by arifogel** [comment]
Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java, line 255 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1168#-LAEh0t_-fEkjEjNmNAB:-LAEh0t_-fEkjEjNmNAC:bglkfmd) ([raw file](https://github.com/batfish/batfish/blob/40f77f36a6b34460425e51cd188c7076cd2bae72/projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java#L255)):*
> ```Java
>     SortedMap<Prefix, BgpNeighbor> neighbors =
>         c.getVrfs().get(Configuration.DEFAULT_VRF_NAME).getBgpProcess().getNeighbors();
>     assertThat(neighbors.get(neighbors.firstKey()).getEnforceFirstAs(), is(true));
> ```

It seems like this could all be one line (with appropriate static imports):
`assertThat(c, hasDefaultVrf(hasBgpProcess(hasNeighbors(hasValue(isEnforceFirstAs())))))`
You might have to add a matcher `isDefaultVrf` in `BgpNeighborMatchers`.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1168)*

**Comment by arifogel** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java, line 252 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1168#-LAEhv1K9bONSPZMmphN:-LAEhv1K9bONSPZMmphO:bywv0kr) ([raw file](https://github.com/batfish/batfish/blob/40f77f36a6b34460425e51cd188c7076cd2bae72/projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java#L252)):*
> ```Java
>     String hostname = "bgp-enforce-first-as";
>     Batfish batfish = getBatfishForConfigurationNames(hostname);
>     Configuration c = batfish.loadConfigurations().get(hostname);
> ```

Just use `parseConfig` or whatever instead of getting a `Batfish`

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1168)*

**Comment by progwriter** [comment]
Review status: 13 of 17 files reviewed at latest revision, 3 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java, line 347 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1168#-LA6nGwo7Ck424CzwN58:-LAEq5qX7_xBI8zh9XbE:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/40f77f36a6b34460425e51cd188c7076cd2bae72/projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java#L347)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
>       Boolean enforceFirstAs = ig.getEnforceFirstAs();
>       if (enforceFirstAs == null) {
>         enforceFirstAs = false;
>       }
>       neighbor.setEnforceFirstAs(enforceFirstAs);
> ```

presumably the ordering here is a bit messed up? shouldn't `setEbgpMultihop` be with the one above?

Btw, why not just `neighbor.setEnforceFirstAs(firstNonNull(ig.getEnforceFirstAs(), Boolean.FALSE))`? Seems a little more straightforward.
</blockquote></details>

Done.

---

*[projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java, line 252 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1168#-LAEhv1K9bONSPZMmphN:-LAEq4d19ZcLm8sbJD5G:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/40f77f36a6b34460425e51cd188c7076cd2bae72/projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java#L252)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Just use `parseConfig` or whatever instead of getting a `Batfish`
</blockquote></details>

Done.

---

*[projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java, line 255 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1168#-LAEh0t_-fEkjEjNmNAB:-LAEwxnW2htN8cCYWtBH:b-j0bgat) ([raw file](https://github.com/batfish/batfish/blob/40f77f36a6b34460425e51cd188c7076cd2bae72/projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java#L255)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

It seems like this could all be one line (with appropriate static imports):
`assertThat(c, hasDefaultVrf(hasBgpProcess(hasNeighbors(hasValue(isEnforceFirstAs())))))`
You might have to add a matcher `isDefaultVrf` in `BgpNeighborMatchers`.
</blockquote></details>

Done, but seems overkill.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1168)*

**Comment by dhalperi** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java, line 3 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1168#-LAExkBY1BuUE1eNW1BT:-LAExkBY1BuUE1eNW1BU:b-x8ph8m) ([raw file](https://github.com/batfish/batfish/blob/25281eb9cf6d89c1d98f4eb58e393482827a8234/projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java#L3)):*
> ```Java
> package org.batfish.representation.juniper;
> 
> import static org.apache.commons.lang3.ObjectUtils.firstNonNull;
> ```

prefer guava MoreObjects.firstNonNull, but up to you.

(Reasoning; every module is likely to depend on Guava, not all will depend on commons-lang3, so given alternatives choose the Guava one in the hopes this module doesn't need commons-lang3 at all.)

---

*[projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java, line 28 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1168#-LAExhk83xrn1jLbYUM7:-LAExhk83xrn1jLbYUM8:bu321o2) ([raw file](https://github.com/batfish/batfish/blob/25281eb9cf6d89c1d98f4eb58e393482827a8234/projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java#L28)):*
> ```Java
> import static org.hamcrest.Matchers.not;
> import static org.hamcrest.Matchers.nullValue;
> import static org.hamcrest.collection.IsMapContaining.hasValue;
> ```

just org.hamcrest.Matchers.hasValue

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1168#-:-LAExx1SDES2Zqbkd4Ug:bnfp4nl)*

**Comment by arifogel** [comment]
Reviewed 2 of 4 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/BgpNeighborMatchers.java, line 24 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1168#-LAExrx964JvS2SXMWBk:-LAExrx964JvS2SXMWBl:b-8gr687) ([raw file](https://github.com/batfish/batfish/blob/25281eb9cf6d89c1d98f4eb58e393482827a8234/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/BgpNeighborMatchers.java#L24)):*
> ```Java
>   }
> 
>   public static HasEnforceFirstAs hasEnforceFirstAs(Matcher<? super Boolean> subMatcher) {
> ```

javadoc please

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/BgpNeighborMatchers.java, line 24 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1168#-LAEyAun6QVU3IeoqkWI:-LAEyAun6QVU3IeoqkWJ:b-9e64xn) ([raw file](https://github.com/batfish/batfish/blob/25281eb9cf6d89c1d98f4eb58e393482827a8234/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/BgpNeighborMatchers.java#L24)):*
> ```Java
>   }
> 
>   public static HasEnforceFirstAs hasEnforceFirstAs(Matcher<? super Boolean> subMatcher) {
> ```

I was assuming you'd also provide `hasEnforceFirstAs()` (no args) that passes `equalTo(true)` to the more general version.

---

*[projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java, line 255 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1168#-LAEh0t_-fEkjEjNmNAB:-LAEy9MBBHEmEq9fMo0N:bo2uaxg) ([raw file](https://github.com/batfish/batfish/blob/40f77f36a6b34460425e51cd188c7076cd2bae72/projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java#L255)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

Done, but seems overkill.
</blockquote></details>

You can remove the `is(true)` if you add an argument-less `hasEnforceFirstAs` as I commented above. BTW isn't `is` deprecated? That is, I think you should always use `equalTo` or `sameInstance` as appropriate instead.

As to being overkill: maybe, but otherwise it seems you have to make an arbitrary choice of where to insert the matcher. BTW try breaking the test - you'll see that the error message is quite nice this way.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1168)*

**Comment by arifogel** [comment]
:lgtm: after addressing minor nits.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1168#-:-LAEz3ed0CPGFKSm_-5i:b-jn2sza)*

**Comment by progwriter** [comment]
Review status: 14 of 17 files reviewed at latest revision, 4 unresolved discussions.

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/BgpNeighborMatchers.java, line 24 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1168#-LAExrx964JvS2SXMWBk:-LAFFMAy-z0fLvSN3t98:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/25281eb9cf6d89c1d98f4eb58e393482827a8234/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/BgpNeighborMatchers.java#L24)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

javadoc please
</blockquote></details>

Done.

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/BgpNeighborMatchers.java, line 24 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1168#-LAEyAun6QVU3IeoqkWI:-LAFFMgJ4LrTnFg6WOF5:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/25281eb9cf6d89c1d98f4eb58e393482827a8234/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/BgpNeighborMatchers.java#L24)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

I was assuming you'd also provide `hasEnforceFirstAs()` (no args) that passes `equalTo(true)` to the more general version.
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java, line 3 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1168#-LAExkBY1BuUE1eNW1BT:-LAFFuTaAcuP802XiluD:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/25281eb9cf6d89c1d98f4eb58e393482827a8234/projects/batfish/src/main/java/org/batfish/representation/juniper/JuniperConfiguration.java#L3)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

prefer guava MoreObjects.firstNonNull, but up to you.

(Reasoning; every module is likely to depend on Guava, not all will depend on commons-lang3, so given alternatives choose the Guava one in the hopes this module doesn't need commons-lang3 at all.)
</blockquote></details>

Done.

---

*[projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java, line 255 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1168#-LAEh0t_-fEkjEjNmNAB:-LAFGIqp91iLtumyb3FK:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/40f77f36a6b34460425e51cd188c7076cd2bae72/projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java#L255)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

You can remove the `is(true)` if you add an argument-less `hasEnforceFirstAs` as I commented above. BTW isn't `is` deprecated? That is, I think you should always use `equalTo` or `sameInstance` as appropriate instead.

As to being overkill: maybe, but otherwise it seems you have to make an arbitrary choice of where to insert the matcher. BTW try breaking the test - you'll see that the error message is quite nice this way.
</blockquote></details>

Done.

---

*[projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java, line 28 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1168#-LAExhk83xrn1jLbYUM7:-LAFFtQf-EeFXIglkahX:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/25281eb9cf6d89c1d98f4eb58e393482827a8234/projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java#L28)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

just org.hamcrest.Matchers.hasValue
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1168)*

**Comment by arifogel** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1168)*

**Comment by arifogel** [comment]
Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1168)*

**Pull request merged**
