### PR TITLE
Dataplane: log which parts of the dataplane changed across topology iterations

### PR DESCRIPTION
**Pull request by dhalperi**
This helps users in understanding dataplane convergence behavior.

### CODE REVIEW

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8911)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @dhalperi)

___
*[`projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java` line 267 at r1](https://reviewable.io/reviews/batfish/batfish/8911#-NnBO79_-l0VLBnLCkKP:-NnBO79_-l0VLBnLCkKQ:b-9v3dga) ([raw file](https://github.com/batfish/batfish/blob/b1ebe2826266656e188457f994b484530c444439/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java#L267)):*
> ```Java
>       return Optional.empty();
>     }
>     Set<String> currentTrue =
> ```

it seems a bit more efficient to diff the cell sets so we don't format strings for cells that don't change. are we assuming there's few enough tracks that we don't need to optimize this?
___
*[`projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java` line 425 at r1](https://reviewable.io/reviews/batfish/batfish/8911#-NnBNUmN7F9kfZOCxnn7:-NnBNUmN7F9kfZOCxnn8:b-sx1wbr) ([raw file](https://github.com/batfish/batfish/blob/b1ebe2826266656e188457f994b484530c444439/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java#L425)):*
> ```Java
>         LOGGER.info("Topologies changed in this iteration");
>       }
>       Optional<String> reachabilityDiff =
> ```

are we assuming there's few enough of these tracks that we don't need put this diffing logic under `isInfoEnabled`?

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8911)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @anothermattbrown)

___
*[`projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java` line 425 at r1](https://reviewable.io/reviews/batfish/batfish/8911#-NnBNUmN7F9kfZOCxnn7:-NnBQwcQEuR-3SFyFHYw:bwnhfl0) ([raw file](https://github.com/batfish/batfish/blob/b1ebe2826266656e188457f994b484530c444439/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java#L425)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

are we assuming there's few enough of these tracks that we don't need put this diffing logic under `isInfoEnabled`?
</blockquote></details>

yes I was assuming it was all fast.

I think all the work is linear in # tracks. A ridiculous bound might be 500 tracks / device, 5000 devices? So 2.5M tracks? That's still a few seconds of work at most I think, and that feels pretty extreme.

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8911)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @anothermattbrown)

___
*[`projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java` line 267 at r1](https://reviewable.io/reviews/batfish/batfish/8911#-NnBO79_-l0VLBnLCkKP:-NnBUSHv6o1gCiukup3c:b-2g8vxt) ([raw file](https://github.com/batfish/batfish/blob/b1ebe2826266656e188457f994b484530c444439/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java#L267)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

it seems a bit more efficient to diff the cell sets so we don't format strings for cells that don't change. are we assuming there's few enough tracks that we don't need to optimize this?
</blockquote></details>

yes, see below. Check my math tho.

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8911)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dhalperi)

**Pull request merged**
