### PR TITLE
IOS XR: BGP default deny routes

### PR DESCRIPTION
**Pull request by corinaminer**
If no import/export filter is in place, all incoming/outgoing routes are default denied. After #6950.

### CODE REVIEW

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6951)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @dhalperi and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConfiguration.java, line 298 at r1](https://reviewable.io/reviews/batfish/batfish/6951#-MZ-P3eE4Fr0WedCkOfR:-MZ-P3eFDVaXYHPOG55b:b-37nnf1) ([raw file](https://github.com/batfish/batfish/blob/dbb3282ab2373aa33bc42bd08c54befd9d3c3832/projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConfiguration.java#L298)):*
> ```Java
> 
>   public static String computeBgpPeerImportPolicyName(String vrf, String peer) {
>     return String.format("~BGP_PEER_IMPORT_POLICY:%s:%s~", vrf, peer);
> ```

fyi, this is identical to the name produced by `Names.generatedBgpPeerImportPolicyName`, which I used to replace it

**Review by sfraint — COMMENTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6951)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dhalperi)

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6951)* status: 2 of 5 files reviewed, all discussions resolved (waiting on @dhalperi and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConversions.java, line 786 at r1](https://reviewable.io/reviews/batfish/batfish/6951#-MZG0FKeBGF8prv4s6ip:-MZG0FKf3cmMhpHRnk-v:b-5nrqqb) ([raw file](https://github.com/batfish/batfish/blob/fe12b68a2a56a7f84f4bb7e7dc00b2612ce024fe/projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConversions.java#L786)):*
> ```Java
>         && c.getRouteFilterLists().containsKey(inboundIpAccessListName)) {
>       importRouteFilter = inboundIpAccessListName;
>     }
> ```

Note that as of #6960, we don't handle prefix-lists or ACLs in BGP peers anymore (they were there as leftovers from the main Cisco parser).

This function might be easier to review by comparing base to r2 rather than r1 to r2.

**Review by sfraint — COMMENTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6951)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dhalperi)

**Pull request merged**
