### PR TITLE
FortiOS: Convert BGP network statements

### PR DESCRIPTION
**Pull request by corinaminer**
Working on fleshing out the test to examine the generated routing policies, but opening PR now to allow review to start.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6890)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6890)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6890)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @dhalperi and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosBgpConversions.java, line 189 at r3](https://reviewable.io/reviews/batfish/batfish/6890#-MXtA4hT7zqZX3IpMK3d:-MXtA4hT7zqZX3IpMK3e:b-j87wwv) ([raw file](https://github.com/batfish/batfish/blob/f2ba2fbceb579a70bca1049ad499c089955155c6/projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosBgpConversions.java#L189)):*
> ```Java
>                 ImmutableList.of(Statements.ReturnTrue.toStaticStatement())))
>         // Default deny
>         .addStatement(Statements.ReturnFalse.toStaticStatement())
> ```

this is the only functional change in this revision

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6890)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6890)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

**Pull request merged**
