### PR TITLE
FRR: Allow more IPv4/IPv6 addresses to be specified for address-virtual

### PR DESCRIPTION
**Pull request by ton31337**
It's a valid command like:

```
address-virtual 44:38:39:ff:ff:c8 10.0.0.254/24 10.0.1.254/24
```

Signed-off-by: Donatas Abraitis <donatas.abraitis@gmail.com>

### CODE REVIEW

**Review by ratulm — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7671)* status: all files reviewed, 2 unresolved discussions (waiting on @ton31337)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7671#-MoFyR-SDuyzx-00SH6l:-MoFyR-TB0PlnJpTDNpB:b-1kmfyo) (no related file):*
Please add tests, somewhere around here: https://github.com/batfish/batfish/blob/175a8771fa59b3c57bc555f6762f5b4737f41c19/projects/batfish/src/test/java/org/batfish/grammar/cumulus_interfaces/CumulusInterfacesGrammarTest.java#L242

---
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_interfaces/CumulusInterfacesParser.g4, line 110 at r1](https://reviewable.io/reviews/batfish/batfish/7671#-MoFy2_6EyZdOkCkE3ei:-MoFy2_6EyZdOkCkE3ej:b-vfcfqv) ([raw file](https://github.com/batfish/batfish/blob/16aa1734f500a39aa4e451de6ba71dc450d35ebc/projects/batfish/src/main/antlr4/org/batfish/grammar/cumulus_interfaces/CumulusInterfacesParser.g4#L110)):*
> ```ANTLR
>     v4 = interface_address
>     | v6 = interface_address6
>   )+ NEWLINE
> ```

This change needs to go deeper. See here: https://github.com/batfish/batfish/blob/175a8771fa59b3c57bc555f6762f5b4737f41c19/projects/batfish/src/main/java/org/batfish/grammar/cumulus_interfaces/CumulusInterfacesConfigurationBuilder.java#L226

**Comment by ton31337** [comment]
This seems to need to be rewritten a lot, because address-virtual can have multiple IPs for the same MAC, but mixed IPv4 and IPv6.

**Comment by ratulm** [comment]
The underlying datamodel supports multiple v4 virtual addresses, so that part should be easy. 

For v6 addresses, you'll need to create a separate variable (something like address6Virtual) and mimic what is happening for v4. Or, you may choose to not push v6 deeper for now (leave it at parsing level).

**Comment by ton31337** [comment]
Okay, will try to fix this.

**Comment by ton31337** [comment]
Added a test.

**Review by ratulm — COMMENTED** [review]
nice! 

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7671#-:-MoKm_xnDMbDrK2Q6ucm:b-n0svi7)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ton31337)

**Pull request merged**
