### PR TITLE
IOS-XR as-path matching conversion

### PR DESCRIPTION
**Pull request by arifogel**
- implement conversion for IOS-XR as-path matching constructs
- use new as-path API introduced in batfish/batfish#6998

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 17 of 21 files at r1, 26 of 32 files at r2, 2 of 2 files at r3, 2 of 3 files at r4, 1 of 1 files at r5, 7 of 7 files at r6.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7000)* status: 53 of 70 files reviewed, all discussions resolved (waiting on @arifogel)

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7000)* status: 53 of 70 files reviewed, 1 unresolved discussion (waiting on @arifogel)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7000#-M_xF-_e0ZMf7xN_x50T:-M_xF-_e0ZMf7xN_x50U:bkppw1v) (no related file):*
After batfish/batfish#6998

---

**Review by corinaminer — COMMENTED** [review]
> Reviewed 1 of 1 files at r8, 13 of 14 files at r9, 3 of 13 files at r12, 1 of 3 files at r13.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7000)* status: 58 of 70 files reviewed, 5 unresolved discussions (waiting on @arifogel and @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConversions.java, line 2108 at r13](https://reviewable.io/reviews/batfish/batfish/7000#-MaAQu_2DlnWOri4RXN2:-MaAQu_36xtLbCa-GrY9:b573mvy) ([raw file](https://github.com/batfish/batfish/blob/907b1c2631bb95ee69eae5d680517b2eb19eab4e/projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConversions.java#L2108)):*
> ```Java
>   }
> 
>   // Returns null for unsupported elems
> ```

This isn't true anymore, right? It returns null if the visited `AsPathSetElement` should not match on a deduped AS path.

Please javadoc these two visitor classes to make it clearer when they should return null and the way they complement each other (i.e. any `AsPathSetElem` should yield exactly one non-null `AsPathMatchExpr` when visited by both visitors).
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConversions.java, line 2110 at r13](https://reviewable.io/reviews/batfish/batfish/7000#-MaAKogt7lvskLNzrNLy:-MaAKogt7lvskLNzrNLz:bo3iqmn) ([raw file](https://github.com/batfish/batfish/blob/907b1c2631bb95ee69eae5d680517b2eb19eab4e/projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConversions.java#L2110)):*
> ```Java
>   // Returns null for unsupported elems
>   private static final class AsPathSetElemToDedupedAsPathMatchExpr
>       implements AsPathSetElemVisitor<AsPathMatchExpr> {
> ```

New visitor classes need private constructors
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConversions.java, line 2162 at r13](https://reviewable.io/reviews/batfish/batfish/7000#-MaAScuc4-HsTTelXjei:-MaAScuc4-HsTTelXjej:bx2nnyz) ([raw file](https://github.com/batfish/batfish/blob/907b1c2631bb95ee69eae5d680517b2eb19eab4e/projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConversions.java#L2162)):*
> ```Java
>     public AsPathMatchExpr visitUniqueLengthAsPathSetElem(
>         UniqueLengthAsPathSetElem uniqueLengthAsPathSetElem) {
>       // TODO: something with getAll()?
> ```

what's `getAll()`? i don't see anything wrong with the implementation as-is (same question about the same todo below with `LengthAsPathSetElem`)
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_xr/RoutePolicyBooleanAsPathLength.java, line 51 at r13](https://reviewable.io/reviews/batfish/batfish/7000#-MaAM6ve8IyQM-48yVSd:-MaAM6ve8IyQM-48yVSe:bkbjz6q) ([raw file](https://github.com/batfish/batfish/blob/907b1c2631bb95ee69eae5d680517b2eb19eab4e/projects/batfish/src/main/java/org/batfish/representation/cisco_xr/RoutePolicyBooleanAsPathLength.java#L51)):*
> ```Java
>     return MatchAsPath.of(
>         InputAsPath.instance(),
>         HasAsPathLength.of(new IntComparison(_comparator, new LiteralInt(_length))));
> ```

Please add a todo to figure out what `all` does
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_xr/RoutePolicyBooleanAsPathOriginatesFrom.java, line 57 at r13](https://reviewable.io/reviews/batfish/batfish/7000#-MaAMHUg7t6P83k_mHIO:-MaAMHUg7t6P83k_mHIP:b-og3ffw) ([raw file](https://github.com/batfish/batfish/blob/907b1c2631bb95ee69eae5d680517b2eb19eab4e/projects/batfish/src/main/java/org/batfish/representation/cisco_xr/RoutePolicyBooleanAsPathOriginatesFrom.java#L57)):*
> ```Java
>     return MatchAsPath.of(
>         _exact ? InputAsPath.instance() : DedupedAsPath.of(InputAsPath.instance()),
>         AsSetsMatchingRanges.of(true, false, _ranges));
> ```

you confirmed that `_ranges` is in the same order as the AS path (i.e., that the first range isn't supposed to match the last AS in the path)?

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7000)* status: 58 of 70 files reviewed, 4 unresolved discussions (waiting on @arifogel and @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConversions.java, line 2162 at r13](https://reviewable.io/reviews/batfish/batfish/7000#-MaAScuc4-HsTTelXjei:-MaAefkf4EyK5LzbH60c:b-r1nv00) ([raw file](https://github.com/batfish/batfish/blob/907b1c2631bb95ee69eae5d680517b2eb19eab4e/projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConversions.java#L2162)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

what's `getAll()`? i don't see anything wrong with the implementation as-is (same question about the same todo below with `LengthAsPathSetElem`)
</blockquote></details>

oh nvm i realized what that's about.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7000)* status: 49 of 74 files reviewed, 3 unresolved discussions (waiting on @arifogel, @corinaminer, and @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConversions.java, line 2108 at r13](https://reviewable.io/reviews/batfish/batfish/7000#-MaAQu_2DlnWOri4RXN2:-MaAqI-E3FadIByS-KRm:bb09p1x) ([raw file](https://github.com/batfish/batfish/blob/907b1c2631bb95ee69eae5d680517b2eb19eab4e/projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConversions.java#L2108)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

This isn't true anymore, right? It returns null if the visited `AsPathSetElement` should not match on a deduped AS path.

Please javadoc these two visitor classes to make it clearer when they should return null and the way they complement each other (i.e. any `AsPathSetElem` should yield exactly one non-null `AsPathMatchExpr` when visited by both visitors).
</blockquote></details>

merged into single visitor with boolean, documented
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConversions.java, line 2110 at r13](https://reviewable.io/reviews/batfish/batfish/7000#-MaAKogt7lvskLNzrNLy:-MaAlyol7vENLaCtUoC7:b-qk4yyu) ([raw file](https://github.com/batfish/batfish/blob/907b1c2631bb95ee69eae5d680517b2eb19eab4e/projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConversions.java#L2110)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

New visitor classes need private constructors
</blockquote></details>

This is a private class, so that isn't necessary.
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_xr/RoutePolicyBooleanAsPathLength.java, line 51 at r13](https://reviewable.io/reviews/batfish/batfish/7000#-MaAM6ve8IyQM-48yVSd:-MaAqRYmEd9MmluhyEVJ:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/907b1c2631bb95ee69eae5d680517b2eb19eab4e/projects/batfish/src/main/java/org/batfish/representation/cisco_xr/RoutePolicyBooleanAsPathLength.java#L51)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Please add a todo to figure out what `all` does
</blockquote></details>

done
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_xr/RoutePolicyBooleanAsPathOriginatesFrom.java, line 57 at r13](https://reviewable.io/reviews/batfish/batfish/7000#-MaAMHUg7t6P83k_mHIO:-MaAqSZNChVx62EGwV8y:b2nign6) ([raw file](https://github.com/batfish/batfish/blob/907b1c2631bb95ee69eae5d680517b2eb19eab4e/projects/batfish/src/main/java/org/batfish/representation/cisco_xr/RoutePolicyBooleanAsPathOriginatesFrom.java#L57)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

you confirmed that `_ranges` is in the same order as the AS path (i.e., that the first range isn't supposed to match the last AS in the path)?
</blockquote></details>

yes

**Review by corinaminer — COMMENTED** [review]
> Reviewed 1 of 2 files at r7, 1 of 3 files at r13, 14 of 14 files at r15.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7000)* status: 65 of 74 files reviewed, 1 unresolved discussion (waiting on @arifogel and @dhalperi)

___
*[projects/batfish/src/test/java/org/batfish/grammar/cisco_xr/XrGrammarTest.java, line 2623 at r15](https://reviewable.io/reviews/batfish/batfish/7000#-MaBPtcA5zYJ5VvdLguq:-MaBPtcA5zYJ5VvdLgur:b-y9z4vc) ([raw file](https://github.com/batfish/batfish/blob/f785823814c6a45b2afea7b3ea3541661710821e/projects/batfish/src/test/java/org/batfish/grammar/cisco_xr/XrGrammarTest.java#L2623)):*
> ```Java
>       assertRoutingPolicyDeniesRoute(rp, rb.setAsPath(ofSingletonAsSets(1L, 2L, 3L)).build());
>       // in (length 4)
>       assertRoutingPolicyDeniesRoute(rp, rb.setAsPath(ofSingletonAsSets(1L, 2L, 3L)).build());
> ```

duplicated assertion. assertion with `(1L, 2L, 3L, 4L, 5L)` is also duplicated, and both are also present twice in the unique-length RP assertions.

i realize those assertions are relevant to two different lines in their routing policies (e.g., here denying `(1L, 2L, 3L)` is a significant test of both `as-path length eq 2` and `as-path in (length eq 4)`), but there's no need to actually duplicate it
___
*[tests/parsing-tests/unit-tests-vimodel.ref, line 0 at r15](https://reviewable.io/reviews/batfish/batfish/7000#-MaBUMyV41TcBqDmxiOz:-MaBUMyV41TcBqDmxiP-:b7e2jsn) ([raw file](https://github.com/batfish/batfish/blob/f785823814c6a45b2afea7b3ea3541661710821e/tests/parsing-tests/unit-tests-vimodel.ref#L0)):*
The changes around the `ama-coe-as-path` AS path sets make sense, but after that this diff is kind of unintelligible to me. But I think everything else is attributable to other changes that got merged into master -- at least, i'm willing to gamble on that.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7000)* status: 65 of 74 files reviewed, 1 unresolved discussion (waiting on @arifogel and @dhalperi)

___
*[tests/parsing-tests/unit-tests-vimodel.ref, line  at r15](https://reviewable.io/reviews/batfish/batfish/7000#-MaBUMyV41TcBqDmxiOz:-MaBWlPC386p2w42RZdH:bqdzdgl) ([raw file](https://github.com/batfish/batfish/blob/f785823814c6a45b2afea7b3ea3541661710821e/tests/parsing-tests/unit-tests-vimodel.ref#L)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

The changes around the `ama-coe-as-path` AS path sets make sense, but after that this diff is kind of unintelligible to me. But I think everything else is attributable to other changes that got merged into master -- at least, i'm willing to gamble on that.
</blockquote></details>

Unfortunately we have a lot of diff instability due to simplifications. This is why it's extra important to rely on semantic - not syntactic - behavior of conversion in tests.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7000)* status: 63 of 74 files reviewed, 1 unresolved discussion (waiting on @arifogel, @corinaminer, and @dhalperi)

___
*[projects/batfish/src/test/java/org/batfish/grammar/cisco_xr/XrGrammarTest.java, line 2623 at r15](https://reviewable.io/reviews/batfish/batfish/7000#-MaBPtcA5zYJ5VvdLguq:-MaBXDX4AmbEaCw3tbaV:bslva0z) ([raw file](https://github.com/batfish/batfish/blob/f785823814c6a45b2afea7b3ea3541661710821e/projects/batfish/src/test/java/org/batfish/grammar/cisco_xr/XrGrammarTest.java#L2623)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

duplicated assertion. assertion with `(1L, 2L, 3L, 4L, 5L)` is also duplicated, and both are also present twice in the unique-length RP assertions.

i realize those assertions are relevant to two different lines in their routing policies (e.g., here denying `(1L, 2L, 3L)` is a significant test of both `as-path length eq 2` and `as-path in (length eq 4)`), but there's no need to actually duplicate it
</blockquote></details>

good catch!

Changed to increments of 3 so everything gets tested without overlap.

**Review by corinaminer — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r16.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7000#-:-MaEsURVE0jgbU-pmH_E:bnfp4nl)* status: 65 of 74 files reviewed, all discussions resolved (waiting on @arifogel and @dhalperi)

**Review by corinaminer — COMMENTED** [review]
> Reviewed 9 of 13 files at r12.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7000)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dhalperi)

**Pull request merged**
