### PR TITLE
CheckPoint: split gateway/server from `TypedManagementObject`

### PR DESCRIPTION
**Pull request by sfraint**
Split `GatewayOrServer` from `TypedManagementObject`.

After this change, `TypedManagementObject` should only contain formats for objects contained in things like `show-objects.json`.

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7320)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/GatewayOrServer.java, line 21 at r1](https://reviewable.io/reviews/batfish/batfish/7320#-MiiVOCA9uioIJ7JZhB3:-MiiVOCA9uioIJ7JZhB4:b-xeh5g2) ([raw file](https://github.com/batfish/batfish/blob/f3d50db526c8d6dbd43f32a148acf69e3e800529/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/GatewayOrServer.java#L21)):*
> ```Java
> @JsonTypeInfo(use = Id.NAME, property = "type")
> @JsonSubTypes({
>   @JsonSubTypes.Type(value = CpmiClusterMember.class, name = "CpmiClusterMember"),
> ```

You should have removed all of these from `TypedManagementObject`, not just `SimpleGatewy`.
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/GatewayOrServer.java, line 65 at r1](https://reviewable.io/reviews/batfish/batfish/7320#-MiiVa6r0yEDNe_5SvhK:-MiiVa6r0yEDNe_5SvhL:b-o237ep) ([raw file](https://github.com/batfish/batfish/blob/f3d50db526c8d6dbd43f32a148acf69e3e800529/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/GatewayOrServer.java#L65)):*
> ```Java
>   }
> 
>   public @Nonnull String getName() {
> ```

Get rid of all changes other than `@JsonTypeInfo`, and just have it extend `NamedManagementObject`.

**Review by arifogel — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7320)* status: all files reviewed, 2 unresolved discussions (waiting on @sfraint)

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7320)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/GatewayOrServer.java, line 21 at r1](https://reviewable.io/reviews/batfish/batfish/7320#-MiiVOCA9uioIJ7JZhB3:-MiiYZxtAfZjpV-XrJZv:b-ynkxm0) ([raw file](https://github.com/batfish/batfish/blob/f3d50db526c8d6dbd43f32a148acf69e3e800529/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/GatewayOrServer.java#L21)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

You should have removed all of these from `TypedManagementObject`, not just `SimpleGatewy`.
</blockquote></details>

Thought I did...fixed now

**Review by arifogel — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7320)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

**Pull request merged**
