### PR TITLE
Better Cisco support for vrf context

### PR DESCRIPTION
**Pull request by dhalperi**

### CODE REVIEW

**Comment by progwriter** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java, line 912 at r1](https://reviewable.io/reviews/batfish/batfish/1380#-LCUTzK7CIHg6ArWrUJB:-LCUTMf_7YDMSl5Z3ezB:bxxqcxq) ([raw file](https://github.com/batfish/batfish/blob/a9503d8920c33194d6a26a592bdfdb04bd6491ff/projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java#L912)):*
> ```Java
>   public void testNxosVrfContext() throws IOException {
>     Configuration vrfC = parseConfig("nxos-vrf-context");
>     assertThat(vrfC.getVrfs(), hasKey("management"));
> ```

Optional: For readability, consider making a matcher that a VRF with given name exists (just like we have `hasDefaultVrf`).

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1380#-:-LCUTs6Q8yEL-vYdE-U7:bnfp4nl)*

**Comment by sfraint** [comment]
Reviewed 4 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/CiscoParser.g4, line 4293 at r1](https://reviewable.io/reviews/batfish/batfish/1380#-LCUS2vHCIHI_IbNeueR:-LCUS2vHCIHI_IbNeueS:bj5pmxb) ([raw file](https://github.com/batfish/batfish/blob/a9503d8920c33194d6a26a592bdfdb04bd6491ff/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/CiscoParser.g4#L4293)):*
> ```ANTLR
> ;
> 
> vrfc_ip_auto_discard
> ```

It looks like `vrfc_ip_auto_discard` is redundant with one of the rules in `vrfc_null` below.  

Should it be removed from `vrfc_null` and referenced somewhere (`s_vrf_context` or w/e context is appropriate)?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1380)*

**Comment by dhalperi** [comment]
Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/CiscoParser.g4, line 4293 at r1](https://reviewable.io/reviews/batfish/batfish/1380#-LCUS2vHCIHI_IbNeueR:-LCUVhVVCwryZC2NqRaj:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/a9503d8920c33194d6a26a592bdfdb04bd6491ff/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/CiscoParser.g4#L4293)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

It looks like `vrfc_ip_auto_discard` is redundant with one of the rules in `vrfc_null` below.  

Should it be removed from `vrfc_null` and referenced somewhere (`s_vrf_context` or w/e context is appropriate)?
</blockquote></details>

Done.

---

*[projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java, line 912 at r1](https://reviewable.io/reviews/batfish/batfish/1380#-LCUTzK7CIHg6ArWrUJB:-LCUVi_ODTrK2t75fxqV:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/a9503d8920c33194d6a26a592bdfdb04bd6491ff/projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java#L912)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

Optional: For readability, consider making a matcher that a VRF with given name exists (just like we have `hasDefaultVrf`).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1380)*

**Comment by sfraint** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2.
Review status: 4 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1380#-:-LCUW4Wt1QQUvVwtlMal:bnfp4nl)*

**Comment by sfraint** [comment]
Reviewed 1 of 5 files at r1.
Review status: 4 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1380)*

**Comment by dhalperi** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1380)*

**Pull request merged**
