### PR TITLE
allowing dst (node or IP) as a traceroute parameter

### PR DESCRIPTION
**Pull request by ratulm**
Partial fix to #622.

Change dstIp parameter to dst which can be an IP or a hostname. If the latter, we use the "canonical IP" for the host. 

---
This change is [Reviewable](https://reviewable.io/reviews/batfish/batfish/805)

### CODE REVIEW

**Comment by dhalperi** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java, line 325 at r1](https://reviewable.io:443/reviews/batfish/batfish/805#-L1PPoASFGSXaPlSMArT:-L1PPoASFGSXaPlSMArU:bbjng4b) ([raw file](https://github.com/batfish/batfish/blob/d3c1260e8382719327009c69cddf3b7d64a96910/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java#L325)):*
> ```Java
> 
>   /** Returns the lowest IP across all interfaces for now. We'll improve it later. */
>   @JsonIgnore
> ```

Add `@Nullable`

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java, line 340 at r1](https://reviewable.io:443/reviews/batfish/batfish/805#-L1PPpPDxYu9y39BtpII:-L1PPpPDxYu9y39BtpIJ:bmwoxih) ([raw file](https://github.com/batfish/batfish/blob/d3c1260e8382719327009c69cddf3b7d64a96910/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java#L340)):*
> ```Java
>     } else {
>       return null;
>     }
> ```

Use the java8 built-in support for minimum over a stream.

```java
  /** Returns the lowest IP across all interfaces for now. We'll improve it later. */
  @JsonIgnore
  @Nullable
  public Ip getCanonicalIp() {
    return getVrfs()
        .values()
        .stream()
        .flatMap(v -> v.getInterfaces().values().stream())
        .flatMap(i -> i.getAllPrefixes().stream())
        .map(Prefix::getAddress)
        .min(Ip::compareTo)
        .orElse(null);
  }
```

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Ip.java, line 103 at r1](https://reviewable.io:443/reviews/batfish/batfish/805#-L1PRO-snyutMT11_RXT:-L1PRO-tcbRButzmDKOl:b-2u0p6z) ([raw file](https://github.com/batfish/batfish/blob/d3c1260e8382719327009c69cddf3b7d64a96910/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Ip.java#L103)):*
> ```Java
>   }
> 
>   public static Ip createIpOrNull(String addr) {
> ```

Would prefer to keep this logic inline where you have it now rather than in the Ip class itself. Does not seem very general.

---

*[projects/question/src/main/java/org/batfish/question/TracerouteQuestionPlugin.java, line 600 at r1](https://reviewable.io:443/reviews/batfish/batfish/805#-L1PRDmQyrtfdsRIIdWN:-L1PRDmQyrtfdsRIIdWO:bx96yet) ([raw file](https://github.com/batfish/batfish/blob/781fe4c161644c2f14a8473b8280bee2399a20cf/projects/question/src/main/java/org/batfish/question/TracerouteQuestionPlugin.java#L600)):*
> ```Java
>     }
> 
>     @Override
> ```

Why delete this `@Override`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/805)*

**Comment by ratulm** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java, line 325 at r1](https://reviewable.io:443/reviews/batfish/batfish/805#-L1PPoASFGSXaPlSMArT:-L1PTb2m-PX33kH0XNbY:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/d3c1260e8382719327009c69cddf3b7d64a96910/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java#L325)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Add `@Nullable`
</blockquote></details>

Done.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java, line 340 at r1](https://reviewable.io:443/reviews/batfish/batfish/805#-L1PPpPDxYu9y39BtpII:-L1PUC5ZSvOe9soRLqzS:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/d3c1260e8382719327009c69cddf3b7d64a96910/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Configuration.java#L340)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Use the java8 built-in support for minimum over a stream.

```java
  /** Returns the lowest IP across all interfaces for now. We'll improve it later. */
  @JsonIgnore
  @Nullable
  public Ip getCanonicalIp() {
    return getVrfs()
        .values()
        .stream()
        .flatMap(v -> v.getInterfaces().values().stream())
        .flatMap(i -> i.getAllPrefixes().stream())
        .map(Prefix::getAddress)
        .min(Ip::compareTo)
        .orElse(null);
  }
```
</blockquote></details>

Done.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Ip.java, line 103 at r1](https://reviewable.io:443/reviews/batfish/batfish/805#-L1PRO-snyutMT11_RXT:-L1PTNrult1QaHBoXRcm:bme1uuy) ([raw file](https://github.com/batfish/batfish/blob/d3c1260e8382719327009c69cddf3b7d64a96910/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Ip.java#L103)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Would prefer to keep this logic inline where you have it now rather than in the Ip class itself. Does not seem very general.
</blockquote></details>

done. had to change the visibility of a function in Ip.java.

---

*[projects/question/src/main/java/org/batfish/question/TracerouteQuestionPlugin.java, line 600 at r1](https://reviewable.io:443/reviews/batfish/batfish/805#-L1PRDmQyrtfdsRIIdWN:-L1PTHQEhsOytMPOJwJw:bfikrfq) ([raw file](https://github.com/batfish/batfish/blob/781fe4c161644c2f14a8473b8280bee2399a20cf/projects/question/src/main/java/org/batfish/question/TracerouteQuestionPlugin.java#L600)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Why delete this `@Override`?
</blockquote></details>

accident. done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/805)*

**Comment by dhalperi** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Ip.java, line 37 at r2](https://reviewable.io:443/reviews/batfish/batfish/805#-L1PaUNI_LOOn2vPzKsN:-L1PaUNJwkpZ-QUzuina:b-19jwg4) ([raw file](https://github.com/batfish/batfish/blob/cd42dae7bdcc44fd1be50853956e8d364880eafa/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Ip.java#L37)):*
> ```Java
>   public static final Ip ZERO = new Ip(0L);
> 
>   public static long ipStrToLong(String addr) {
> ```

Why do this vs just using the `new Ip(String)` constructor?, which calls `ipStrToLong` internally?

---

*[projects/question/src/main/java/org/batfish/question/TracerouteQuestionPlugin.java, line 307 at r2](https://reviewable.io:443/reviews/batfish/batfish/805#-L1PabHbP5LAVciafh-f:-L1PabHbP5LAVciafh-g:bl3s38v) ([raw file](https://github.com/batfish/batfish/blob/cd42dae7bdcc44fd1be50853956e8d364880eafa/projects/question/src/main/java/org/batfish/question/TracerouteQuestionPlugin.java#L307)):*
> ```Java
>       if (_dst != null) {
>         try {
>           Ip dstIp = new Ip(Ip.ipStrToLong(_dst));
> ```

I think this is the same as the existing `new Ip(String)` constructor without the visibility change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/805)*

**Comment by ratulm** [comment]
Review status: 9 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Ip.java, line 37 at r2](https://reviewable.io:443/reviews/batfish/batfish/805#-L1PaUNI_LOOn2vPzKsN:-L1PeB47QHNdxjIztha_:b-vmxusv) ([raw file](https://github.com/batfish/batfish/blob/cd42dae7bdcc44fd1be50853956e8d364880eafa/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Ip.java#L37)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Why do this vs just using the `new Ip(String)` constructor?, which calls `ipStrToLong` internally?
</blockquote></details>

argh.  i am stupid.

---

*[projects/question/src/main/java/org/batfish/question/TracerouteQuestionPlugin.java, line 307 at r2](https://reviewable.io:443/reviews/batfish/batfish/805#-L1PabHbP5LAVciafh-f:-L1PeFIXeZrF5ZMf6XIQ:b51zi63) ([raw file](https://github.com/batfish/batfish/blob/cd42dae7bdcc44fd1be50853956e8d364880eafa/projects/question/src/main/java/org/batfish/question/TracerouteQuestionPlugin.java#L307)):*
> argh.  i am stupid.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/805)*

**Comment by dhalperi** [comment]
Reviewed 1 of 2 files at r3.
Review status: 10 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/805)*

**Comment by dhalperi** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/805#-:-L1Pe_BXf--1mRla834Y:bnfp4nl)*

**Pull request merged**
