### PR TITLE
Juniper implement policy-statement then as-path-expand

### PR DESCRIPTION
**Pull request by arifogel**

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8095)* status: 0 of 16 files reviewed, 1 unresolved discussion (waiting on @arifogel, @corinaminer, @dhalperi, and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/8095#-Mx1NF8I4I7aA4hSCG6c:-Mx1NF8I4I7aA4hSCG6d:bn5ms3i) (no related file):*
need to add equalstest, etc.

---

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8095)* status: 0 of 18 files reviewed, 1 unresolved discussion (waiting on @arifogel, @corinaminer, @dhalperi, and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/8095#-Mx1vgqZ4hzYLM1Cq1Ve:-Mx1vgq_-NMZYe1oQQyu:b-42jrj6) (no related file):*
looks like wrong semantics. may have to rewrite.

---

**Review by corinaminer — COMMENTED** [review]
> Reviewed 16 of 16 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8095)* status: all files reviewed, 6 unresolved discussions (waiting on @arifogel, @dhalperi, and @sfraint)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4, line 3728 at r2](https://reviewable.io/reviews/batfish/batfish/8095#-Mx1mJwG0Yi6QZMuxTsI:-Mx1mJwG0Yi6QZMuxTsJ:b-11c7vp) ([raw file](https://github.com/batfish/batfish/blob/9d22bdb7ba85671a50c44810eda44512102c3631/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4#L3728)):*
> ```ANTLR
> M_AsPathExpand2_PERIOD: '.' -> type(PERIOD);
> M_AsPathExpand2_DOUBLE_QUOTE: '"' -> skip, mode(M_AsPathExpand_Inner);
> M_asPathExpand3_LAST_AS: 'last-as' -> type(LAST_AS), mode(M_AsPathExpandLastAs);
> ```

is it going to matter that the initial `a` in `M_asPathExpand` is lowercase?
___
*[projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java, line 6814 at r2](https://reviewable.io/reviews/batfish/batfish/8095#-Mx2-fM_DQjjrbcz3KZg:-Mx2-fM_DQjjrbcz3KZh:b-iilq64) ([raw file](https://github.com/batfish/batfish/blob/9d22bdb7ba85671a50c44810eda44512102c3631/projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java#L6814)):*
> ```Java
> 
>     Bgpv4Route inputRouteNonEmptyAsPath =
>         Bgpv4Route.builder()
> ```

nit: could use `testBuilder()`
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/AppendAsPath.java, line 24 at r2](https://reviewable.io/reviews/batfish/batfish/8095#-Mx23-O36G_T3ArTzdCO:-Mx23-O36G_T3ArTzdCP:b-ruzz6v) ([raw file](https://github.com/batfish/batfish/blob/9d22bdb7ba85671a50c44810eda44512102c3631/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/AppendAsPath.java#L24)):*
> ```Java
>   private static final String PROP_EXPR = "expr";
> 
>   @Nonnull private AsPathListExpr _expr;
> ```

can this be final?
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/AppendAsPath.java, line 42 at r2](https://reviewable.io/reviews/batfish/batfish/8095#-Mx22Lyj32_oS5_DBdKe:-Mx22Lyj32_oS5_DBdKf:b4o6sti) ([raw file](https://github.com/batfish/batfish/blob/9d22bdb7ba85671a50c44810eda44512102c3631/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/AppendAsPath.java#L42)):*
> ```Java
> 
>   @Override
>   public boolean equals(Object obj) {
> ```

nullable
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/AppendAsPath.java, line 65 at r2](https://reviewable.io/reviews/batfish/batfish/8095#-Mx23KpS4sFRuOrttnNq:-Mx23KpS4sFRuOrttnNr:bb9dcu2) ([raw file](https://github.com/batfish/batfish/blob/9d22bdb7ba85671a50c44810eda44512102c3631/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/AppendAsPath.java#L65)):*
> ```Java
>         environment.getReadFromIntermediateBgpAttributes()
>             ? environment.getIntermediateBgpAttributes().getAsPath()
>             : outputRoute.getAsPath();
> ```

looking at `PrependAsPath`, it always adds to the output route's AS path and does not check `getReadFromIntermediateBgpAttributes()`. Is that incorrect or is this?

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8095)* status: 4 of 23 files reviewed, 5 unresolved discussions (waiting on @corinaminer, @dhalperi, and @sfraint)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4, line 3728 at r2](https://reviewable.io/reviews/batfish/batfish/8095#-Mx1mJwG0Yi6QZMuxTsI:-Mx2Gz9SAF9O29ks8Toi:b-t75bn1) ([raw file](https://github.com/batfish/batfish/blob/9d22bdb7ba85671a50c44810eda44512102c3631/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4#L3728)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

is it going to matter that the initial `a` in `M_asPathExpand` is lowercase?
</blockquote></details>

No, but fixed.
___
*[projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java, line 6814 at r2](https://reviewable.io/reviews/batfish/batfish/8095#-Mx2-fM_DQjjrbcz3KZg:-Mx2H0IM84X0tZUrzR8R:bcxvwqu) ([raw file](https://github.com/batfish/batfish/blob/9d22bdb7ba85671a50c44810eda44512102c3631/projects/batfish/src/test/java/org/batfish/grammar/flatjuniper/FlatJuniperGrammarTest.java#L6814)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

nit: could use `testBuilder()`
</blockquote></details>

I don't like it.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/AppendAsPath.java, line 24 at r2](https://reviewable.io/reviews/batfish/batfish/8095#-Mx23-O36G_T3ArTzdCO:-Mx2H2HyBBhwtCV6ry3L:b9mdwjd) ([raw file](https://github.com/batfish/batfish/blob/9d22bdb7ba85671a50c44810eda44512102c3631/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/AppendAsPath.java#L24)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

can this be final?
</blockquote></details>

Deleted this class, so moot.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/AppendAsPath.java, line 42 at r2](https://reviewable.io/reviews/batfish/batfish/8095#-Mx22Lyj32_oS5_DBdKe:-Mx2H4nS3Re6aUIdx3MQ:b9mdwjd) ([raw file](https://github.com/batfish/batfish/blob/9d22bdb7ba85671a50c44810eda44512102c3631/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/AppendAsPath.java#L42)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

nullable
</blockquote></details>

Deleted this class, so moot.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/AppendAsPath.java, line 65 at r2](https://reviewable.io/reviews/batfish/batfish/8095#-Mx23KpS4sFRuOrttnNq:-Mx2H8rREpgv7nULSAVX:b-nm1rx9) ([raw file](https://github.com/batfish/batfish/blob/9d22bdb7ba85671a50c44810eda44512102c3631/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/AppendAsPath.java#L65)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

looking at `PrependAsPath`, it always adds to the output route's AS path and does not check `getReadFromIntermediateBgpAttributes()`. Is that incorrect or is this?
</blockquote></details>

No idea. We need to go over all this at some point.
Anyway deleted this class, so moot here.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8095)* status: 2 of 23 files reviewed, 6 unresolved discussions (waiting on @corinaminer, @dhalperi, and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/8095#-Mx5uuEc-9-drXmbVPCi:-Mx5uuEd1tuftjLet-ZZ:b-j7deb8) (no related file):*
I ported some of the cleanup I did in AppendAsPath (now deleted) to PrependAsPath. Please take a close look and reiterate any remaining concerns.

---

**Review by corinaminer — COMMENTED** [review]
> Reviewed 12 of 20 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8095)* status: 15 of 23 files reviewed, 1 unresolved discussion (waiting on @arifogel, @corinaminer, @dhalperi, and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/representation/juniper/PsThenAsPathExpand.java, line 3 at r4](https://reviewable.io/reviews/batfish/batfish/8095#-Mx5x-YM6byTozWHsE8r:-Mx5x-YN68zOHROBFp2C:bnbat6y) ([raw file](https://github.com/batfish/batfish/blob/ef06dbf1dd69b40084c67a7caf573e9f73650238/projects/batfish/src/main/java/org/batfish/representation/juniper/PsThenAsPathExpand.java#L3)):*
> ```Java
> package org.batfish.representation.juniper;
> 
> /** {@link PsThenAsPathExpandAsList} or {@link PsThenAsPathExpandLastAs} or . */
> ```

just those two, right? (nothing to follow that hanging `or`?)
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/PrependAsPath.java, line 75 at r4](https://reviewable.io/reviews/batfish/batfish/8095#-MxAyiq302dSO46P9rQQ:-MxAyiq302dSO46P9rQR:b-tlphkz) ([raw file](https://github.com/batfish/batfish/blob/ef06dbf1dd69b40084c67a7caf573e9f73650238/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/PrependAsPath.java#L75)):*
> ```Java
> 
>     // TODO: Clean up this paradigm. Currently all over we write to both output and intermediate
>     //       when write-to-intermediate is true. Using current paradigm.
> ```

fyi i don't think this is wrong -- we always write to output, the write to intermediate flag is independent of that.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8095)* status: 15 of 23 files reviewed, 1 unresolved discussion (waiting on @corinaminer, @dhalperi, and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/representation/juniper/PsThenAsPathExpand.java, line 3 at r4](https://reviewable.io/reviews/batfish/batfish/8095#-Mx5x-YM6byTozWHsE8r:-MxBgkkf3ClenugC09RY:b-7ql1td) ([raw file](https://github.com/batfish/batfish/blob/ef06dbf1dd69b40084c67a7caf573e9f73650238/projects/batfish/src/main/java/org/batfish/representation/juniper/PsThenAsPathExpand.java#L3)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

just those two, right? (nothing to follow that hanging `or`?)
</blockquote></details>

fixed
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/PrependAsPath.java, line 75 at r4](https://reviewable.io/reviews/batfish/batfish/8095#-MxAyiq302dSO46P9rQQ:-MxBgw-64EbvfwnEBW4p:bw0qgai) ([raw file](https://github.com/batfish/batfish/blob/ef06dbf1dd69b40084c67a7caf573e9f73650238/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/PrependAsPath.java#L75)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

fyi i don't think this is wrong -- we always write to output, the write to intermediate flag is independent of that.
</blockquote></details>

The semantics are not really documented anywhere. I suppose we can clean up usages at some point. For now, deleting the TODO, since it doesn't add much.

**Review by arifogel — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8095)* status: 15 of 23 files reviewed, all discussions resolved (waiting on @corinaminer, @dhalperi, and @sfraint)

**Review by arifogel — COMMENTED** [review]
> Reviewed 8 of 20 files at r3, 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8095)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dhalperi and @sfraint)

**Pull request merged**
