### PR TITLE
BDDInteger: remove getBitvec

### PR DESCRIPTION
**Pull request by anothermattbrown**
getBitvec was exposing mutable internal state. Moved some things into BDDInteger (e.g. conversion from an IP address to BDD), migrated clients onto BDDInteger::getVars, and did some minor refactoring.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8193)* status: 4 of 15 files reviewed, 3 unresolved discussions (waiting on @anothermattbrown and @dhalperi)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDInteger.java, line 229 at r1](https://reviewable.io/reviews/batfish/batfish/8193#-Mz2S8JADp4Yk4jxgLC2:-Mz2S8JADp4Yk4jxgLC3:b-9z5eqs) ([raw file](https://github.com/batfish/batfish/blob/69aa730630faf9f78fe23830ec392de89cac3c13/projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDInteger.java#L229)):*
> ```Java
>    * Note: We assume the prefix is never modified, so it will
>    * be a bitvector containing only the underlying variables:
>    * [var(0), ..., var(n)]
> ```

Why is this assumption needed? Seems to me this impl is fine regardless.



_Code quote:_
```Java
   * Note: We assume the prefix is never modified, so it will
   * be a bitvector containing only the underlying variables:
   * [var(0), ..., var(n)]
```
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDInteger.java, line 231 at r1](https://reviewable.io/reviews/batfish/batfish/8193#-Mz2SZ9PEgnQB7gPWto4:-Mz2SZ9PEgnQB7gPWto5:b-3yns7k) ([raw file](https://github.com/batfish/batfish/blob/69aa730630faf9f78fe23830ec392de89cac3c13/projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDInteger.java#L231)):*
> ```Java
>    * [var(0), ..., var(n)]
>    */
>   public BDD firstBitsEqual(Ip ip, int length) {
> ```

is it worth moving all these onto a wildcard-like private impl (long bits, long mask)?
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/IpSpaceToBDD.java, line 102 at r1](https://reviewable.io/reviews/batfish/batfish/8193#-Mz2SwYU2JZpZz9QnJG8:-Mz2SwYVEZYcFeM3Eqpb:b-q1auk5) ([raw file](https://github.com/batfish/batfish/blob/69aa730630faf9f78fe23830ec392de89cac3c13/projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/IpSpaceToBDD.java#L102)):*
> ```Java
>   @Override
>   public BDD visitIpIpSpace(IpIpSpace ipIpSpace) {
>     return _bddInteger.toBDD(ipIpSpace.getIp());
> ```

Seems like it would be less garbage-y to go the other way. ip.toIpSpace allocates objects, IpIpSpace.getIp does not.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8193)* status: 5 of 15 files reviewed, 3 unresolved discussions (waiting on @anothermattbrown and @dhalperi)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, 2 of 2 files at r4, 2 of 2 files at r5, 2 of 2 files at r6, 2 of 2 files at r7, 1 of 1 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8193)* status: all files reviewed, 7 unresolved discussions (waiting on @anothermattbrown)

___
*[projects/batfish/src/main/java/org/batfish/bddreachability/transition/TransformationToTransition.java, line 125 at r5](https://reviewable.io/reviews/batfish/batfish/8193#-Mz2TXQR-lcH2DT3JKyS:-Mz2TXQR-lcH2DT3JKyT:beubndf) ([raw file](https://github.com/batfish/batfish/blob/beaa96d68a866b9851c6dc6197ada477c6e3d200/projects/batfish/src/main/java/org/batfish/bddreachability/transition/TransformationToTransition.java#L125)):*
> ```Java
>       IpSpaceToBDD varToBdd = ipFieldToBDD(step.getIpField());
>       int len = prefix.getPrefixLength();
>       BDD erase = var.getVars(len);
> ```

something about MSB? or something like that?



_Code quote:_
```Java
getVars
```
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDInteger.java, line 470 at r5](https://reviewable.io/reviews/batfish/batfish/8193#-Mz2UP6rEMMAU0VxPqD5:-Mz2UP6rEMMAU0VxPqD6:bimoye4) ([raw file](https://github.com/batfish/batfish/blob/beaa96d68a866b9851c6dc6197ada477c6e3d200/projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDInteger.java#L470)):*
> ```Java
>         _hasVariablesOnly,
>         "getVars can only be called on a BDDInteger with hasVariablesOnly() true");
>     checkState(n <= _bitvec.length);
> ```

checkArgument for the second one? with description?
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDInteger.java, line 474 at r5](https://reviewable.io/reviews/batfish/batfish/8193#-Mz2UMxm7syqlHMs5oyh:-Mz2UMxm7syqlHMs5oyi:b-p6x8pk) ([raw file](https://github.com/batfish/batfish/blob/beaa96d68a866b9851c6dc6197ada477c6e3d200/projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDInteger.java#L474)):*
> ```Java
>       return getVars();
>     }
>     return _factory.andAll(Arrays.copyOf(_bitvec, n));
> ```

May be cheaper to use `ListsArrays.asList().subList(0,n)`? Create 2 objects, but don't copy anything. May be a wash tho.



_Code quote:_
```Java
(Arrays.copyOf(_bitvec, n)
```
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDInteger.java, line 50 at r6](https://reviewable.io/reviews/batfish/batfish/8193#-Mz2V4FCACQWKmhsTvfJ:-Mz2V4FCACQWKmhsTvfK:b-d4gk2z) ([raw file](https://github.com/batfish/batfish/blob/f05d589681242981e2b51736e9a74821a621bdef/projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDInteger.java#L50)):*
> ```Java
>   public BDDInteger(BDD[] bitvec) {
>     this(bitvec[0].getFactory(), bitvec.length);
>     _hasVariablesOnly = true; // TODO enforce this
> ```

Easy to do, right? lo is zero and hi is one.

**Review by anothermattbrown — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8193)* status: 11 of 15 files reviewed, 4 unresolved discussions (waiting on @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/bddreachability/transition/TransformationToTransition.java, line 125 at r5](https://reviewable.io/reviews/batfish/batfish/8193#-Mz2TXQR-lcH2DT3JKyS:-Mz2Z4X-6k6GkgvZglpa:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/beaa96d68a866b9851c6dc6197ada477c6e3d200/projects/batfish/src/main/java/org/batfish/bddreachability/transition/TransformationToTransition.java#L125)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

something about MSB? or something like that?
</blockquote></details>

done
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDInteger.java, line 229 at r1](https://reviewable.io/reviews/batfish/batfish/8193#-Mz2S8JADp4Yk4jxgLC2:-Mz2UOP36_b7mmlnh-yA:b-i8wpuw) ([raw file](https://github.com/batfish/batfish/blob/69aa730630faf9f78fe23830ec392de89cac3c13/projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDInteger.java#L229)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Why is this assumption needed? Seems to me this impl is fine regardless.
</blockquote></details>

agreed. I'll cut that
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDInteger.java, line 231 at r1](https://reviewable.io/reviews/batfish/batfish/8193#-Mz2SZ9PEgnQB7gPWto4:-Mz2Wp4sDYKVI6pQ3ZsI:bou9ept) ([raw file](https://github.com/batfish/batfish/blob/69aa730630faf9f78fe23830ec392de89cac3c13/projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDInteger.java#L231)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

is it worth moving all these onto a wildcard-like private impl (long bits, long mask)?
</blockquote></details>

possibly, though there are many more prefixes than wildcards, so it would make sense to optimize for that case. I don't know if there would be a difference in perf, so I'd prefer not to do it in this PR.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDInteger.java, line 470 at r5](https://reviewable.io/reviews/batfish/batfish/8193#-Mz2UP6rEMMAU0VxPqD5:-Mz2Z7krCcnmjca0-oty:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/beaa96d68a866b9851c6dc6197ada477c6e3d200/projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDInteger.java#L470)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

checkArgument for the second one? with description?
</blockquote></details>

done
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDInteger.java, line 474 at r5](https://reviewable.io/reviews/batfish/batfish/8193#-Mz2UMxm7syqlHMs5oyh:-Mz2Z6jH-yTGRlkNZNyv:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/beaa96d68a866b9851c6dc6197ada477c6e3d200/projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDInteger.java#L474)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

May be cheaper to use `ListsArrays.asList().subList(0,n)`? Create 2 objects, but don't copy anything. May be a wash tho.
</blockquote></details>

done
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDInteger.java, line 50 at r6](https://reviewable.io/reviews/batfish/batfish/8193#-Mz2V4FCACQWKmhsTvfJ:-Mz2WLiX2FLs7FmM3K9n:b-kiqwkg) ([raw file](https://github.com/batfish/batfish/blob/f05d589681242981e2b51736e9a74821a621bdef/projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/BDDInteger.java#L50)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Easy to do, right? lo is zero and hi is one.
</blockquote></details>

yes but I'm going to remove `_hasVariablesOnly` entirely in the next pr :smile: 
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/IpSpaceToBDD.java, line 102 at r1](https://reviewable.io/reviews/batfish/batfish/8193#-Mz2SwYU2JZpZz9QnJG8:-Mz2ThljCEf5hYy0VF-m:b-hwsh2v) ([raw file](https://github.com/batfish/batfish/blob/69aa730630faf9f78fe23830ec392de89cac3c13/projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/IpSpaceToBDD.java#L102)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Seems like it would be less garbage-y to go the other way. ip.toIpSpace allocates objects, IpIpSpace.getIp does not.
</blockquote></details>

Do you mean have `IpSpaceToBDD::toBDD(Ip)` call `BDDInteger::toBDD(Ip)` directly instead of going through `IpSpaceToBDD::visit(IpSpace)`? I did that so we `MemoizedIpSpaceToBDD` can cache. Not sure how the tradeoffs balance out though, and it may not be a huge difference either way.

**Review by anothermattbrown — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8193)* status: 11 of 15 files reviewed, 4 unresolved discussions (waiting on @dhalperi)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/IpSpaceToBDD.java, line 102 at r1](https://reviewable.io/reviews/batfish/batfish/8193#-Mz2SwYU2JZpZz9QnJG8:-Mz2bjozEICU-2vgIUsl:b-3490tk) ([raw file](https://github.com/batfish/batfish/blob/69aa730630faf9f78fe23830ec392de89cac3c13/projects/batfish-common-protocol/src/main/java/org/batfish/common/bdd/IpSpaceToBDD.java#L102)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

Do you mean have `IpSpaceToBDD::toBDD(Ip)` call `BDDInteger::toBDD(Ip)` directly instead of going through `IpSpaceToBDD::visit(IpSpace)`? I did that so we `MemoizedIpSpaceToBDD` can cache. Not sure how the tradeoffs balance out though, and it may not be a huge difference either way. 
</blockquote></details>

Reverted to original implementation strategy so this can be a pure-refactor PR

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 2 files at r10, 2 of 2 files at r11, 1 of 1 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8193)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown)

**Pull request merged**
