### PR TITLE
A10: Support extended access lists

### PR DESCRIPTION
**Pull request by corinaminer**
Supports extended access lists such as:
```
access-list 100 permit ip host 1.1.1.1 any
```

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8017)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java, line 344 at r1](https://reviewable.io/reviews/batfish/batfish/8017#-MvQt6Ug7SqKgUD8l0RI:-MvQt6UhBOXlS2NIaelj:bswrf8e) ([raw file](https://github.com/batfish/batfish/blob/23cb755597f417c50b3af80801fc0f5e61f29ef9/projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java#L344)):*
> ```Java
>     udp.setDestinationRange(destRange);
>     return Optional.of(udp);
>   }
> ```

What's the point of the optionality here? Seems like it can never return `Optional#empty`



_Code quote:_
```Java
  private Optional<AccessListRule> toAclRule(
      String lineText,
      AccessListRule.Action action,
      AccessListAddress source,
      AccessListAddress destination,
      A10Parser.Access_list_protocolContext protocolCtx,
      @Nullable SubRange destRange) {
    if (protocolCtx.ICMP() != null) {
      return Optional.of(new AccessListRuleIcmp(action, source, destination, lineText));
    } else if (protocolCtx.IP() != null) {
      return Optional.of(new AccessListRuleIp(action, source, destination, lineText));
    } else if (protocolCtx.TCP() != null) {
      AccessListRuleTcp tcp = new AccessListRuleTcp(action, source, destination, lineText);
      tcp.setDestinationRange(destRange);
      return Optional.of(tcp);
    }
    assert protocolCtx.UDP() != null;
    AccessListRuleUdp udp = new AccessListRuleUdp(action, source, destination, lineText);
    udp.setDestinationRange(destRange);
    return Optional.of(udp);
  }
```

**Review by dhalperi — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8017#-:-MvQtbsyD52wgJG0zgML:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel and @corinaminer)

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8017)* status: 13 of 14 files reviewed, all discussions resolved (waiting on @arifogel and @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java, line 344 at r1](https://reviewable.io/reviews/batfish/batfish/8017#-MvQt6Ug7SqKgUD8l0RI:-MvRK2FL7tVR89GfAuOZ:bt6gk1v) ([raw file](https://github.com/batfish/batfish/blob/23cb755597f417c50b3af80801fc0f5e61f29ef9/projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java#L344)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

What's the point of the optionality here? Seems like it can never return `Optional#empty`
</blockquote></details>

ah, yeah, no longer optional. fixed

**Review by dhalperi — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8017#-:-MvRuXkG834aeMyBgUu0:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Pull request merged**
