### PR TITLE
BgpPeerConfigurationQuestion: add description column

### PR DESCRIPTION
**Pull request by dhalperi**

### CODE REVIEW

**Review by corinaminer — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6403)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi and @ratulm)

___
*[projects/question/src/test/java/org/batfish/question/bgpproperties/BUILD, line 1 at r1](https://reviewable.io/reviews/batfish/batfish/6403#-MLVFb4D-e_0FvwaFrUp:-MLVFb4D-e_0FvwaFrUq:bls9ydr) ([raw file](https://github.com/batfish/batfish/blob/6449ec548554fc0b6de759f7333195595280edd9/projects/question/src/test/java/org/batfish/question/bgpproperties/BUILD#L1)):*
> ```Starlark
> load("@rules_java//java:defs.bzl", "java_library")
> ```

i don't understand what change made this build file necessary now if it wasn't before

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6403)* status: all files reviewed, 2 unresolved discussions (waiting on @dhalperi and @ratulm)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpPeerPropertySpecifier.java, line 134 at r1](https://reviewable.io/reviews/batfish/batfish/6403#-MLVFzD73YsvLdp4BtHP:-MLVFzD73YsvLdp4BtHQ:b-qccrbw) ([raw file](https://github.com/batfish/batfish/blob/6449ec548554fc0b6de759f7333195595280edd9/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpPeerPropertySpecifier.java#L134)):*
> ```Java
>           .put(
>               DESCRIPTION,
>               new PropertyDescriptor<>(BgpPeerConfig::getDescription, Schema.STRING, "Description"))
> ```

could make the description of this property something like "Configured peer description", otherwise people looking at docs might think it's something batfish will manufacture.

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6403)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @corinaminer, @dhalperi, and @ratulm)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpPeerPropertySpecifier.java, line 134 at r1](https://reviewable.io/reviews/batfish/batfish/6403#-MLVFzD73YsvLdp4BtHP:-MLZ01UH77NBhxkOU11N:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/6449ec548554fc0b6de759f7333195595280edd9/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/BgpPeerPropertySpecifier.java#L134)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

could make the description of this property something like "Configured peer description", otherwise people looking at docs might think it's something batfish will manufacture.
</blockquote></details>

Done.

**Comment by dhalperi** [comment]
___
*[projects/question/src/test/java/org/batfish/question/bgpproperties/BUILD, line 1 at r1](https://reviewable.io/reviews/batfish/batfish/6403#-MLVFb4D-e_0FvwaFrUp:-MLZ04147nUgAPb9k85E:b-oxrenq) ([raw file](https://github.com/batfish/batfish/blob/6449ec548554fc0b6de759f7333195595280edd9/projects/question/src/test/java/org/batfish/question/bgpproperties/BUILD#L1)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

i don't understand what change made this build file necessary now if it wasn't before
</blockquote></details>

I want to run the tests alone, not as part of a huge suite.

**Comment by dhalperi** [comment]
___
*[projects/question/src/test/java/org/batfish/question/bgpproperties/BUILD, line 1 at r1](https://reviewable.io/reviews/batfish/batfish/6403#-MLVFb4D-e_0FvwaFrUp:-MLZ0CTm66JyGqIIZOOv:bu24yh5) ([raw file](https://github.com/batfish/batfish/blob/6449ec548554fc0b6de759f7333195595280edd9/projects/question/src/test/java/org/batfish/question/bgpproperties/BUILD#L1)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I want to run the tests alone, not as part of a huge suite.
</blockquote></details>

This just moves these tests from the "question_tests" bazel target to the "bgpproperties:tests" target

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6403)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ratulm)

**Pull request merged**
