### PR TITLE
SearchRoutePolicies: Output route constraints are incompatible with the DENY action

### PR DESCRIPTION
**Pull request by millstein**
Updated SearchRoutePolicies to signal an error if the question is using the action DENY but also specifies constraints on the expected output route.  There are no output routes when the goal is to find input routes that are denied, so specifying both is likely an error on the part of the user.  Previously we silently ignored the output route constraints.

### CODE REVIEW

**Review by ratulm — COMMENTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7088)* status: all files reviewed, 1 unresolved discussion (waiting on @millstein)

___
*[projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/BgpRouteConstraints.java, line 170 at r2](https://reviewable.io/reviews/batfish/batfish/7088#-McgOjGU-nSLIQySxbjB:-McgOjGU-nSLIQySxbjC:bhr1lh0) ([raw file](https://github.com/batfish/batfish/blob/e4614a8a5bd848d2f5c82f46a184bdd68985ad2d/projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/BgpRouteConstraints.java#L170)):*
> ```Java
> 
>   @Override
>   public boolean equals(Object o) {
> ```

When we add an equals function, we typically also add an equality test -- e..g.., https://github.com/batfish/batfish/blob/f0595cd48856131c6cd2dc227c74e8852fe49222/projects/question/src/test/java/org/batfish/question/testroutepolicies/ResultTest.java

Add one for this class and RegexConstraints?

**Review by millstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7088)* status: 3 of 7 files reviewed, all discussions resolved (waiting on @ratulm)

___
*[projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/BgpRouteConstraints.java, line 170 at r2](https://reviewable.io/reviews/batfish/batfish/7088#-McgOjGU-nSLIQySxbjB:-McgboHF0PkvB17JDqOW:b-s1wg8f) ([raw file](https://github.com/batfish/batfish/blob/e4614a8a5bd848d2f5c82f46a184bdd68985ad2d/projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/BgpRouteConstraints.java#L170)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

When we add an equals function, we typically also add an equality test -- e..g.., https://github.com/batfish/batfish/blob/f0595cd48856131c6cd2dc227c74e8852fe49222/projects/question/src/test/java/org/batfish/question/testroutepolicies/ResultTest.java

Add one for this class and RegexConstraints? 
</blockquote></details>

Done (and doing that also made me realize that the equals method for RegexConstraints wasn't correct, since the order of regex constraints is irrelevant; fixed).

**Review by ratulm — COMMENTED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7088)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @millstein)

___
*[projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/RegexConstraints.java, line 37 at r3](https://reviewable.io/reviews/batfish/batfish/7088#-Mcgi9k-Dk2d_U7rDUkP:-Mcgi9k-Dk2d_U7rDUkQ:b-wym5ka) ([raw file](https://github.com/batfish/batfish/blob/2c7d64d9eef2a6843697eadbf4963aa195fda388/projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/RegexConstraints.java#L37)):*
> ```Java
>         regexConstraints == null
>             ? ImmutableSet.of()
>             : regexConstraints.stream().collect(ImmutableSet.toImmutableSet());
> ```

optional: shorter version -- ImmutableSet.copyOf(regexConstraints)

**Review by ratulm — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7088)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @millstein)

**Pull request merged**
