### PR TITLE
Add L3 edges between l3 vni interfaces based on VxlanTopology

### PR DESCRIPTION
**Pull request by arifogel**

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7774)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @arifogel)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7774#-MqS2Md71gVue3f8Qaa-:-MqS2Md88L4oWAV9jvsH:b-xwdzb8) (no related file):*
after batfish/batfish#7772

---

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7774)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @anothermattbrown, @arifogel, @corinaminer, and @dhalperi)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7774#-MqS7E0E4lD4ECZmEskZ:-MqS7E0E4lD4ECZmEsk_:b-1kmsjr) (no related file):*
changes start at r3, so use r2 as a base

---

**Review by arifogel — COMMENTED** [review]
> Reviewed 2 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7774)* status: 3 of 6 files reviewed, all discussions resolved (waiting on @anothermattbrown, @arifogel, @corinaminer, and @dhalperi)

**Review by corinaminer — COMMENTED** [review]
> Reviewed 1 of 3 files at r3, 1 of 1 files at r4, 1 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7774)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/vxlan/VxlanTopologyUtils.java, line 312 at r5](https://reviewable.io/reviews/batfish/batfish/7774#-MqW0OHP7WMaZz8rHgL3:-MqW0OHP7WMaZz8rHgL4:b-uf1o3c) ([raw file](https://github.com/batfish/batfish/blob/9295b4d522d6796a83574fc0055a7704f8e197dd/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/vxlan/VxlanTopologyUtils.java#L312)):*
> ```Java
>           && c2.getAllInterfaces().containsKey(iface2Name))) {
>         // VNI was either layer-2 or defective layer-3, so no interface was generated.
>         continue;
> ```

perhaps worth testing this case? your call.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7774)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/vxlan/VxlanTopologyUtils.java, line 312 at r5](https://reviewable.io/reviews/batfish/batfish/7774#-MqW0OHP7WMaZz8rHgL3:-MqW0VIQ2mq69pyHG3ha:b-qjc7d5) ([raw file](https://github.com/batfish/batfish/blob/9295b4d522d6796a83574fc0055a7704f8e197dd/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/vxlan/VxlanTopologyUtils.java#L312)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

perhaps worth testing this case? your call.
</blockquote></details>

This _is_ tested. I put layer-2 vni edges in the test vxlan topology.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/vxlan/VxlanTopologyUtils.java, line 315 at r5](https://reviewable.io/reviews/batfish/batfish/7774#-MqW0MSSEZt41Xn3ng3e:-MqW0MSSEZt41Xn3ng3f:b5tgkiw) ([raw file](https://github.com/batfish/batfish/blob/9295b4d522d6796a83574fc0055a7704f8e197dd/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/vxlan/VxlanTopologyUtils.java#L315)):*
> ```Java
>       }
>       edgesBuilder.add(Edge.of(node1Name, iface1Name, node2Name, iface2Name));
>       edgesBuilder.add(Edge.of(node2Name, iface2Name, node1Name, iface1Name));
> ```

checking whether we actually need both directions

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7774)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/vxlan/VxlanTopologyUtils.java, line 315 at r5](https://reviewable.io/reviews/batfish/batfish/7774#-MqW0MSSEZt41Xn3ng3e:-MqW19pd8sIi4VY9sjSi:bmmtr19) ([raw file](https://github.com/batfish/batfish/blob/9295b4d522d6796a83574fc0055a7704f8e197dd/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/vxlan/VxlanTopologyUtils.java#L315)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

checking whether we actually need both directions
</blockquote></details>

Seems like `Topology` constructor this eventually goes into stores a `SortedSet<Edge>`, so I suspect for now both directions are needed. At some point we may want to make `Topology` store a graph instead.

**Pull request merged**
