### PR TITLE
Vrrp properties question

### PR DESCRIPTION
**Pull request by ratulm**

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 6 of 7 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7377)* status: all files reviewed, 1 unresolved discussion (waiting on @ratulm)

___
*[projects/question/src/main/java/org/batfish/question/vrrpproperties/VrrpPropertiesAnswerer.java, line 121 at r2](https://reviewable.io/reviews/batfish/batfish/7377#-MjXki9PBmRM_dzlmzFK:-MjXki9PBmRM_dzlmzFL:bcrcvw8) ([raw file](https://github.com/batfish/batfish/blob/a8afc554090bc4005853b58569669ae1a38d8bab/projects/question/src/main/java/org/batfish/question/vrrpproperties/VrrpPropertiesAnswerer.java#L121)):*
> ```Java
>   static void populateRow(RowBuilder row, Integer id, VrrpGroup group) {
>     row.put(COL_GROUP_ID, id)
>         .put(COL_VIRTUAL_ADDRESS, group.getVirtualAddress().getIp())
> ```

Why an IP instead of a `ConcreteInterfaceAddress`?

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7377)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel)

___
*[projects/question/src/main/java/org/batfish/question/vrrpproperties/VrrpPropertiesAnswerer.java, line 121 at r2](https://reviewable.io/reviews/batfish/batfish/7377#-MjXki9PBmRM_dzlmzFK:-MjXolu76Bj1APvmwGyC:b2n41kd) ([raw file](https://github.com/batfish/batfish/blob/a8afc554090bc4005853b58569669ae1a38d8bab/projects/question/src/main/java/org/batfish/question/vrrpproperties/VrrpPropertiesAnswerer.java#L121)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Why an IP instead of a `ConcreteInterfaceAddress`?
</blockquote></details>

Can this ever be a non /32? 

(If prefix-length is important: we have schema for IP, not address. for interfaces, so we'll pack IP and mask separately.)

**Comment by arifogel** [comment]
I thought it was almost always different than 32. Certainly it is for our
modeling of cluster ips on checkpoint.
And I thought the typical cisco-like case was that the prefix length would
match that of the nterface's subnet that contains the virtual address.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7377)* status: all files reviewed, 1 unresolved discussion (waiting on @ratulm)

___
*[projects/question/src/main/java/org/batfish/question/vrrpproperties/VrrpPropertiesAnswerer.java, line 121 at r2](https://reviewable.io/reviews/batfish/batfish/7377#-MjXki9PBmRM_dzlmzFK:-Mja85jCEc1WfHnKoCVT:bngbvgi) ([raw file](https://github.com/batfish/batfish/blob/a8afc554090bc4005853b58569669ae1a38d8bab/projects/question/src/main/java/org/batfish/question/vrrpproperties/VrrpPropertiesAnswerer.java#L121)):*
Copying reply to github here:
>I thought it was almost always different than 32. Certainly it is for our
modeling of cluster ips on checkpoint.
And I thought the typical cisco-like case was that the prefix length would
match that of the nterface's subnet that contains the virtual address.

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7377)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel)

___
*[projects/question/src/main/java/org/batfish/question/vrrpproperties/VrrpPropertiesAnswerer.java, line 121 at r2](https://reviewable.io/reviews/batfish/batfish/7377#-MjXki9PBmRM_dzlmzFK:-MjaB7gF5KjxUEAJS6Mn:bp60tlb) ([raw file](https://github.com/batfish/batfish/blob/a8afc554090bc4005853b58569669ae1a38d8bab/projects/question/src/main/java/org/batfish/question/vrrpproperties/VrrpPropertiesAnswerer.java#L121)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Copying reply to github here:
>I thought it was almost always different than 32. Certainly it is for our
modeling of cluster ips on checkpoint.
And I thought the typical cisco-like case was that the prefix length would
match that of the nterface's subnet that contains the virtual address.
</blockquote></details>

Added prefix length

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7377)* status: all files reviewed, 1 unresolved discussion (waiting on @ratulm)

___
*[projects/question/src/main/java/org/batfish/question/vrrpproperties/VrrpPropertiesAnswerer.java, line 121 at r2](https://reviewable.io/reviews/batfish/batfish/7377#-MjXki9PBmRM_dzlmzFK:-MjaB_xJ0JuQl-ZeAhGz:b-uli6j8) ([raw file](https://github.com/batfish/batfish/blob/a8afc554090bc4005853b58569669ae1a38d8bab/projects/question/src/main/java/org/batfish/question/vrrpproperties/VrrpPropertiesAnswerer.java#L121)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

Added prefix length
</blockquote></details>

Did you forget to push?

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7377)* status: 6 of 8 files reviewed, 1 unresolved discussion (waiting on @arifogel)

___
*[projects/question/src/main/java/org/batfish/question/vrrpproperties/VrrpPropertiesAnswerer.java, line 121 at r2](https://reviewable.io/reviews/batfish/batfish/7377#-MjXki9PBmRM_dzlmzFK:-MjaCXbOA8z9uDym80sD:bxcgpys) ([raw file](https://github.com/batfish/batfish/blob/a8afc554090bc4005853b58569669ae1a38d8bab/projects/question/src/main/java/org/batfish/question/vrrpproperties/VrrpPropertiesAnswerer.java#L121)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Did you forget to push?
</blockquote></details>

pushed to the wrong branch. fixed :)

**Review by arifogel — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7377)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ratulm)

**Pull request merged**
