### PR TITLE
refactor junit testrig initialization

### PR DESCRIPTION
**Pull request by arifogel**
This change is [Reviewable](https://reviewable.io/reviews/batfish/batfish/715)

### CODE REVIEW

**Comment by arifogel** [comment]
Includes #707

**Comment by dhalperi** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/batfish/batfish/715#-L-mdrZ7e7-mXymPd55C:-L-mdrZ8J5cZArirIvEL:bivflq0) (no related file):*
Please merge master and fix travis.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/715)*

**Comment by arifogel** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/batfish/batfish/715#-L-mdrZ7e7-mXymPd55C:-L-n1ppkA7EbYh7CY6df:b-fjks66) (no related file):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Please merge master and fix travis.
</blockquote></details>

Done I think

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/715)*

**Comment by dhalperi** [comment]
*[projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java, line 59 at r1](https://reviewable.io:443/reviews/batfish/batfish/715#-L-nq-EV33qNIt_Ia5bn:-L-nq-EV33qNIt_Ia5bo:b-d2ln06) ([raw file](https://github.com/batfish/batfish/blob/6ede8411354ece99e95400b49b78072a3e98f8c9/projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java#L59)):*
> ```Java
>   @Test
>   public void testAaaNewmodel() throws IOException {
>     SortedSet<String> configurationNames = ImmutableSortedSet.of("aaaNoNewmodel", "aaaNewmodel");
> ```

Why does `TestrigText` require any of these to be sorted?
Why are require them to be sets?

Seems to me like `Collection`/`Map` should work just as well and be much more usable.

Where does the importance of iteration order come in?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/715)*

**Comment by arifogel** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java, line 59 at r1](https://reviewable.io:443/reviews/batfish/batfish/715#-L-nq-EV33qNIt_Ia5bn:-L-rm6cyT4pIyk9qEpe6:b-jtm0r9) ([raw file](https://github.com/batfish/batfish/blob/6ede8411354ece99e95400b49b78072a3e98f8c9/projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java#L59)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Why does `TestrigText` require any of these to be sorted?
Why are require them to be sets?

Seems to me like `Collection`/`Map` should work just as well and be much more usable.

Where does the importance of iteration order come in?
</blockquote></details>

Now I accept `Iterable<String>` in these functions. I pass in `List`s so duplicates can be detected.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/715)*

**Comment by dhalperi** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[projects/batfish/src/test/java/org/batfish/bdp/BdpDataPlanePluginTest.java, line 690 at r2](https://reviewable.io:443/reviews/batfish/batfish/715#-L-sUhTxVcbtniF1DRou:-L-sUhTxVcbtniF1DRov:bpp2mep) ([raw file](https://github.com/batfish/batfish/blob/d503834def99ee16880c6135aaeeaf39f7929cd8/projects/batfish/src/test/java/org/batfish/bdp/BdpDataPlanePluginTest.java#L690)):*
> ```Java
> 
>   @Test
>   public void testStaticInterfaceRoutesWithoutEdge() {
> ```

Just confirming: was the deletion of this test intentional or a merge conflict? I thought this was catching a real bug.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/715#-:-L-sVDi8keTkCgzRRS2P:bnfp4nl)*

**Comment by arifogel** [comment]
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/test/java/org/batfish/bdp/BdpDataPlanePluginTest.java, line 690 at r2](https://reviewable.io:443/reviews/batfish/batfish/715#-L-sUhTxVcbtniF1DRou:-L-sb9QPdPJV7QYu1RXZ:b-o1zn3n) ([raw file](https://github.com/batfish/batfish/blob/d503834def99ee16880c6135aaeeaf39f7929cd8/projects/batfish/src/test/java/org/batfish/bdp/BdpDataPlanePluginTest.java#L690)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Just confirming: was the deletion of this test intentional or a merge conflict? I thought this was catching a real bug.
</blockquote></details>

Not sure how that happened. I probably wasn't careful during a git rebase/mergetool. I added it back.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/715)*

**Comment by arifogel** [comment]
Resolved conflicts in `BatfishTestUtils`

---

Review status: 5 of 8 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/715#-:-L0BGuUe5pUv0cmhtSfe:bl2f6zr)*

**Comment by arifogel** [comment]
Merged with master and resolved conflicts in `BdpDataPlanePluginTest`

---

Review status: 5 of 8 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/715#-:-L0BVrYadTqHpqBdU_RV:bjm1ajr)*

**Comment by arifogel** [comment]
@dhalperi you might want to review this revision afresh against master to be sure I didn't screw anything up in the conflict resolutions.

---

Review status: 5 of 8 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/715#-:-L0BW4pgmPX_vM8AvoYc:b-xatxzu)*

**Pull request merged**
