### PR TITLE
FortiOS interface conversion

### PR DESCRIPTION
**Pull request by corinaminer**

### CODE REVIEW

**Review by sfraint — COMMENTED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6725)* status: 2 of 4 files reviewed, 6 unresolved discussions (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosConfiguration.java, line 268 at r1](https://reviewable.io/reviews/batfish/batfish/6725#-MVcazVVERBTQtZOnOmI:-MVcazVVERBTQtZOnOmJ:b-tt2olt) ([raw file](https://github.com/batfish/batfish/blob/3f938fd18f8975bd139fdcaf18613b94357e2308/projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosConfiguration.java#L268)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
>       case AGGREGATE:
>         // TODO Distinguish between AGGREGATED and AGGREGATE_CHILD
>         return InterfaceType.AGGREGATED;
> ...
>       case REDUNDANT:
>         // TODO Distinguish between REDUNDANT and REDUNDANT_CHILD
>         return InterfaceType.REDUNDANT;
> ```
</details>

maybe mark these as unsupported / return `null` until we handle them?
___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosConfiguration.java, line 304 at r1](https://reviewable.io/reviews/batfish/batfish/6725#-MVcbTOx1azrd1LXkmQW:-MVcbTOx1azrd1LXkmQX:b-vri83a) ([raw file](https://github.com/batfish/batfish/blob/3f938fd18f8975bd139fdcaf18613b94357e2308/projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosConfiguration.java#L304)):*
> ```
> policy.getActionEffective() == Policy.Action.ALLOW;
> ```
what about action `IPSEC`? should we add a warning here that it isn't supported?

From https://docs.fortinet.com/document/fortigate/6.0.0/handbook/554066/firewall-policies:
> IPsec - This is an ACCEPT action that is specifically for IPsec VPNs.
___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosConfiguration.java, line 311 at r1](https://reviewable.io/reviews/batfish/batfish/6725#-MVcZw0j8p2qt5IDeLkl:-MVcZw0j8p2qt5IDeLkm:bw006t6) ([raw file](https://github.com/batfish/batfish/blob/3f938fd18f8975bd139fdcaf18613b94357e2308/projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosConfiguration.java#L311)):*
> ```
> TraceElement.builder().add("Match policy", vsi).build()
> ```
for `TraceElement`s like this, I have a slight preference for formatting something like:

```
.add("Matched policy")
.add(policyName, vsi)
if (comment/descr) .add(String.format("(%s)", comment/descr))
```

that way we can embed the human-readable info and make the vsi stand out more

thoughts?
___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosConfiguration.java, line 311 at r1](https://reviewable.io/reviews/batfish/batfish/6725#-MVc_Vvf18xHOzx8Fqya:-MVc_Vvf18xHOzx8Fqyb:b-xzvbr1) ([raw file](https://github.com/batfish/batfish/blob/3f938fd18f8975bd139fdcaf18613b94357e2308/projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosConfiguration.java#L311)):*
> ```Java
>               _filename, FortiosStructureType.POLICY.getDescription(), viPolicyName);
>       AclLineMatchExpr matchExpr =
>           and(TraceElement.builder().add("Match policy", vsi).build(), matchSources, policyMatches);
> ```

also, with more complicated `TraceElement`s, might make sense to migrate these into the [fortios TE creator class](https://github.com/batfish/batfish/blob/master/projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosTraceElementCreators.java)
___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosConfiguration.java, line 322 at r1](https://reviewable.io/reviews/batfish/batfish/6725#-MVcakvg1uhvFes1FEEf:-MVcakvg1uhvFes1FEEg:b-7gok2w) ([raw file](https://github.com/batfish/batfish/blob/3f938fd18f8975bd139fdcaf18613b94357e2308/projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosConfiguration.java#L322)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>    if (lines.isEmpty()) {
>      // No policies affect traffic exiting this interface.
>      // TODO Check default action (no egress filter implies default action PERMIT)
>      return Optional.empty();
>    }
>     lines.add(ExprAclLine.ACCEPT_ALL); // TODO Check default action
> ```
</details>

> ```
>       // TODO Check default action (no egress filter implies default action PERMIT)
> ```
sounds like no firewall policy means all traffic is denied: https://docs.fortinet.com/document/fortigate/6.0.0/handbook/554066/firewall-policies

> What is not expressly allowed is denied
>
> One of the fundamental ideas that can be found in just about any firewall is the rule than anything that is not expressly allowed is by default denied. This is the foundation for any strategy of protecting your network. Right out of the box, once you have your FortiGate device connected into your network and hooked up with your ISP, your network is protected. Nothing is getting out or in so it is not very convenient, but you don’t have to worry that between the time you hooked it up and the point that you got all of the policies in place that someone could have gotten in and done something to your resources...
___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/Interface.java, line 32 at r1](https://reviewable.io/reviews/batfish/batfish/6725#-MVccv0NCPg2VLhUGw4S:-MVccv0NCPg2VLhUGw4T:bjt7j95) ([raw file](https://github.com/batfish/batfish/blob/3f938fd18f8975bd139fdcaf18613b94357e2308/projects/batfish/src/main/java/org/batfish/representation/fortios/Interface.java#L32)):*
> ```
>   public static final Type DEFAULT_TYPE = Type.VLAN;
> ```
is this right? or does it have to be explicitly set?

if it does have to be set in order for the block to be accepted, maybe add a note indicating it is irrelevant because of `edit block` enforcements that are not done yet

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6725)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @arifogel and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosConfiguration.java, line 268 at r1](https://reviewable.io/reviews/batfish/batfish/6725#-MVcazVVERBTQtZOnOmI:-MVcich5B_B2AFwj4UDi:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/3f938fd18f8975bd139fdcaf18613b94357e2308/projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosConfiguration.java#L268)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
>       case AGGREGATE:
>         // TODO Distinguish between AGGREGATED and AGGREGATE_CHILD
>         return InterfaceType.AGGREGATED;
> ...
>       case REDUNDANT:
>         // TODO Distinguish between REDUNDANT and REDUNDANT_CHILD
>         return InterfaceType.REDUNDANT;
> ```
maybe mark these as unsupported / return `null` until we handle them?
</blockquote></details>

done
___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosConfiguration.java, line 304 at r1](https://reviewable.io/reviews/batfish/batfish/6725#-MVcbTOx1azrd1LXkmQW:-MVcl8fLBy95u0LwERbO:b-vnwq6n) ([raw file](https://github.com/batfish/batfish/blob/3f938fd18f8975bd139fdcaf18613b94357e2308/projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosConfiguration.java#L304)):*
Ah, that link also covers default action! 
> for traffic to flow through the FortiGate firewall there must be a policy that matches its parameters

I'll add a warning in policy conversion about IPSEC, good catch.
___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosConfiguration.java, line 311 at r1](https://reviewable.io/reviews/batfish/batfish/6725#-MVcZw0j8p2qt5IDeLkl:-MVcrq0YBXdXgVI7G773:b-kyhez) ([raw file](https://github.com/batfish/batfish/blob/3f938fd18f8975bd139fdcaf18613b94357e2308/projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosConfiguration.java#L311)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
> TraceElement.builder().add("Match policy", vsi).build()
> ```
for `TraceElement`s like this, I have a slight preference for formatting something like:

```
.add("Matched policy")
.add(policyName, vsi)
if (comment/descr) .add(String.format("(%s)", comment/descr))
```

that way we can embed the human-readable info and make the vsi stand out more

thoughts?
</blockquote></details>

absolutely :star2: also moved to FortiosTraceElementCreators since you created it!
___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosConfiguration.java, line 311 at r1](https://reviewable.io/reviews/batfish/batfish/6725#-MVc_Vvf18xHOzx8Fqya:-MVcsQEvDl59JATyCI6N:b2igqzy) ([raw file](https://github.com/batfish/batfish/blob/3f938fd18f8975bd139fdcaf18613b94357e2308/projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosConfiguration.java#L311)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

also, with more complicated `TraceElement`s, might make sense to migrate these into the [fortios TE creator class](https://github.com/batfish/batfish/blob/master/projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosTraceElementCreators.java)
</blockquote></details>

yep. i'd do that with the address trace elements too once we get around to it
___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosConfiguration.java, line 322 at r1](https://reviewable.io/reviews/batfish/batfish/6725#-MVcakvg1uhvFes1FEEf:-MVcsgUKCe63iFQkvXLX:b-a7mt0w) ([raw file](https://github.com/batfish/batfish/blob/3f938fd18f8975bd139fdcaf18613b94357e2308/projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosConfiguration.java#L322)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
>    if (lines.isEmpty()) {
>      // No policies affect traffic exiting this interface.
>      // TODO Check default action (no egress filter implies default action PERMIT)
>      return Optional.empty();
>    }
>     lines.add(ExprAclLine.ACCEPT_ALL); // TODO Check default action
> ```
> ```
>       // TODO Check default action (no egress filter implies default action PERMIT)
> ```
sounds like no firewall policy means all traffic is denied: https://docs.fortinet.com/document/fortigate/6.0.0/handbook/554066/firewall-policies

> What is not expressly allowed is denied
>
> One of the fundamental ideas that can be found in just about any firewall is the rule than anything that is not expressly allowed is by default denied. This is the foundation for any strategy of protecting your network. Right out of the box, once you have your FortiGate device connected into your network and hooked up with your ISP, your network is protected. Nothing is getting out or in so it is not very convenient, but you don’t have to worry that between the time you hooked it up and the point that you got all of the policies in place that someone could have gotten in and done something to your resources...
</blockquote></details>

yeah i noticed that too :chart_with_upwards_trend: 
___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/Interface.java, line 32 at r1](https://reviewable.io/reviews/batfish/batfish/6725#-MVccv0NCPg2VLhUGw4S:-MVct5a94CYS9inHkHmc:b7rl85k) ([raw file](https://github.com/batfish/batfish/blob/3f938fd18f8975bd139fdcaf18613b94357e2308/projects/batfish/src/main/java/org/batfish/representation/fortios/Interface.java#L32)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
>   public static final Type DEFAULT_TYPE = Type.VLAN;
> ```
is this right? or does it have to be explicitly set?

if it does have to be set in order for the block to be accepted, maybe add a note indicating it is irrelevant because of `edit block` enforcements that are not done yet
</blockquote></details>

Setting type isn't required for the block to be accepted, and if you do `show full-configuration` with no type set, it has `set type vlan` :woman_shrugging:

**Review by sfraint — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 4 of 4 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6725)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java, line 433 at r2](https://reviewable.io/reviews/batfish/batfish/6725#-MVd3xM06wUzrehPdFAw:-MVd3xM06wUzrehPdFAx:bnnasaf) ([raw file](https://github.com/batfish/batfish/blob/6d42ef50417655c974bcad1aacc28330c585f263/projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java#L433)):*
<details><summary><i alt="summary">Quoted 15 lines of code…</i></summary>

> ```
>     assertThat(
>         warnings.getRedFlagWarnings(),
>         hasItems(
>             WarningMatchers.hasText(
>                 String.format(
>                     "Interface %s has unsupported type %s and will not be converted",
>                     "agg", Type.AGGREGATE)),
>             WarningMatchers.hasText(
>                 String.format(
>                     "Interface %s has unsupported type %s and will not be converted",
>                     "redundant", Type.REDUNDANT)),
>             WarningMatchers.hasText(
>                 String.format(
>                     "Interface %s has unsupported type %s and will not be converted",
>                     "wl", Type.WL_MESH))));
> ```
</details>

does `WarningsMatchers` `hasRedFlag` or `hasRedFlags` work instead?

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6725)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java, line 433 at r2](https://reviewable.io/reviews/batfish/batfish/6725#-MVd3xM06wUzrehPdFAw:-MVd4jYN9VhzxF_jB5Mc:bm4s6a) ([raw file](https://github.com/batfish/batfish/blob/6d42ef50417655c974bcad1aacc28330c585f263/projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java#L433)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
>     assertThat(
>         warnings.getRedFlagWarnings(),
>         hasItems(
>             WarningMatchers.hasText(
>                 String.format(
>                     "Interface %s has unsupported type %s and will not be converted",
>                     "agg", Type.AGGREGATE)),
>             WarningMatchers.hasText(
>                 String.format(
>                     "Interface %s has unsupported type %s and will not be converted",
>                     "redundant", Type.REDUNDANT)),
>             WarningMatchers.hasText(
>                 String.format(
>                     "Interface %s has unsupported type %s and will not be converted",
>                     "wl", Type.WL_MESH))));
> ```
does `WarningsMatchers` `hasRedFlag` or `hasRedFlags` work instead?
</blockquote></details>

(nit :smiley: )

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6725)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

___
*[projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java, line 433 at r2](https://reviewable.io/reviews/batfish/batfish/6725#-MVd3xM06wUzrehPdFAw:-MVd5Amx7Af_XaJD8o-9:b-oifxg8) ([raw file](https://github.com/batfish/batfish/blob/6d42ef50417655c974bcad1aacc28330c585f263/projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java#L433)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

(nit :smiley: )
</blockquote></details>

yeahh i think it would. not going to worry about it

**Pull request merged**
