### PR TITLE
IOS-XR: improve ACL accuracy, add a few more fields

### PR DESCRIPTION
**Pull request by dhalperi**
* Delete unsupported TCP flags (CWR, ECE, URG)
* Mark / flesh out ICMPv6 codes
* Flesh out ICMPv4 codes
* Delete invalid things
* Handle log-input
* Handle fragments

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7164)* status: 0 of 9 files reviewed, all discussions resolved (waiting on @arifogel and @corinaminer)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7164#-MeajSftAYLSnC4vtLy8:-MeajSftAYLSnC4vtLy9:bdxrp8f) (no related file):*
FYI going for low hanging fruit, obviously it needs a rewrite into NX-OS style version.

---
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_acl.g4, line 103 at r1](https://reviewable.io/reviews/batfish/batfish/7164#-MeajWebDn3btQU1wt_q:-MeajWebDn3btQU1wt_r:b-1hl1oc) ([raw file](https://github.com/batfish/batfish/blob/eb1b2e6e993583b9c466623dd6ef0c34b8ebd720/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_acl.g4#L103)):*
> ```ANTLR
>    | ALTERNATE_ADDRESS
>    | BEYOND_SCOPE
>    | BFD_ECHO
> ```

FYI this is a port, and handled elsewhere.
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_acl.g4, line 125 at r1](https://reviewable.io/reviews/batfish/batfish/7164#-MeajZXN6qnzl0HPETZ5:-MeajZXN6qnzl0HPETZ6:b-oxifx1) ([raw file](https://github.com/batfish/batfish/blob/eb1b2e6e993583b9c466623dd6ef0c34b8ebd720/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_acl.g4#L125)):*
> ```
>  ECN ecn = uint_legacy
> ```

FYI ecn not supported as far as I could find. Validated in docs and box.

**Review by corinaminer — COMMENTED** [review]
> Reviewed 5 of 9 files at r1, 3 of 3 files at r2, 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7164)* status: 13 of 14 files reviewed, 2 unresolved discussions (waiting on @arifogel and @dhalperi)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_acl.g4, line 106 at r3](https://reviewable.io/reviews/batfish/batfish/7164#-Mecckww7TklCRbddi_i:-Mecckww7TklCRbddi_j:bbk5z44) ([raw file](https://github.com/batfish/batfish/blob/d4c4240fad61266bc9a92511baf3f63e5cd41a64/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_acl.g4#L106)):*
> ```ANTLR
>    | CAPTURE
>    | CONVERSION_ERROR
>    | COUNT
> ```

Are all the non-tcp-flag options you've deleted (excluding the ones you've commented on) invalid, or are some just irrelevant to Batfish? Can you link the cisco docs you were referring to?
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXrLexer.g4, line 3478 at r3](https://reviewable.io/reviews/batfish/batfish/7164#-MecdHlQ0zPM-PmsQu8t:-MecdHlQ0zPM-PmsQu8u:bbp17sk) ([raw file](https://github.com/batfish/batfish/blob/2fdc309047e0d00aa7e97a92c6e39daa06cda60d/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXrLexer.g4#L3478)):*
> ```ANTLR
> 
> NEGOTIATE: 'negotiate';
> ```

can you delete `TRACKED`, `URG`?
___
*[projects/batfish/src/test/java/org/batfish/grammar/cisco_xr/XrGrammarTest.java, line 415 at r3](https://reviewable.io/reviews/batfish/batfish/7164#-MecglDgCut-fuD2ryBS:-MecglDgCut-fuD2ryBT:bn76gl) ([raw file](https://github.com/batfish/batfish/blob/2fdc309047e0d00aa7e97a92c6e39daa06cda60d/projects/batfish/src/test/java/org/batfish/grammar/cisco_xr/XrGrammarTest.java#L415)):*
> ```Java
>               .build();
>       assertThat(bdds.getPermitBdd(), equalTo(_aclToBdd.getHeaderSpaceToBDD().toBDD(expected)));
>       assertThat(bdds.getDenyBdd(), isZero());
> ```

seems odd to test the deny BDD for a `permit` ACL line. no real need to remove, though

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7164)* status: 11 of 14 files reviewed, 1 unresolved discussion (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_acl.g4, line 106 at r3](https://reviewable.io/reviews/batfish/batfish/7164#-Mecckww7TklCRbddi_i:-MeciQTZ8oRkbgnCZL7K:b-ewtpr0) ([raw file](https://github.com/batfish/batfish/blob/d4c4240fad61266bc9a92511baf3f63e5cd41a64/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_acl.g4#L106)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Are all the non-tcp-flag options you've deleted (excluding the ones you've commented on) invalid, or are some just irrelevant to Batfish? Can you link the cisco docs you were referring to?
</blockquote></details>

they're all not actual IOS-XR parsing syntax, just left over from Frankenparser.

I FYI'ed most of the ones I deleted or they went along with others.

Docs are here: https://www.cisco.com/c/en/us/td/docs/routers/asr9000/software/asr9k_r4-0/addr_serv/command/reference/ir40asrbook_chapter1.html

but we don't usually put that in the code for "this is the grammar" -- just for weird behavior to explain.
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXrLexer.g4, line 3478 at r3](https://reviewable.io/reviews/batfish/batfish/7164#-MecdHlQ0zPM-PmsQu8t:-MecjBtkDdN9W8UtAuT1:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/2fdc309047e0d00aa7e97a92c6e39daa06cda60d/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXrLexer.g4#L3478)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

can you delete `TRACKED`, `URG`?
</blockquote></details>

Done.
___
*[projects/batfish/src/test/java/org/batfish/grammar/cisco_xr/XrGrammarTest.java, line 415 at r3](https://reviewable.io/reviews/batfish/batfish/7164#-MecglDgCut-fuD2ryBS:-MeciHrjBpgU6BDcSswy:b-19vifr) ([raw file](https://github.com/batfish/batfish/blob/2fdc309047e0d00aa7e97a92c6e39daa06cda60d/projects/batfish/src/test/java/org/batfish/grammar/cisco_xr/XrGrammarTest.java#L415)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

seems odd to test the deny BDD for a `permit` ACL line. no real need to remove, though
</blockquote></details>

I agree 100%, but it seemed equally odd to not test the other half of the returned object :p.

**Review by corinaminer — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 9 files at r1, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7164#-:-Mef2FaeAOjpYM3XiZ6-:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_acl.g4, line 106 at r3](https://reviewable.io/reviews/batfish/batfish/7164#-Mecckww7TklCRbddi_i:-Mef1AKh6kGI8Ejg6BJD:b-qxfneb) ([raw file](https://github.com/batfish/batfish/blob/d4c4240fad61266bc9a92511baf3f63e5cd41a64/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_acl.g4#L106)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

they're all not actual IOS-XR parsing syntax, just left over from Frankenparser.

I FYI'ed most of the ones I deleted or they went along with others.

Docs are here: https://www.cisco.com/c/en/us/td/docs/routers/asr9000/software/asr9k_r4-0/addr_serv/command/reference/ir40asrbook_chapter1.html

but we don't usually put that in the code for "this is the grammar" -- just for weird behavior to explain.
</blockquote></details>

yep :+1: i didn't mean in the code, just wanted the link for reference while reviewing

**Pull request merged**
