### PR TITLE
SONiC: Setup for more file types

### PR DESCRIPTION
**Pull request by ratulm**
Prep for supporting more SONiC file types (snmp.yml, resolve.conf)
1. Batfish allows more than two files in the SONiC device bundle
2. Parser detects the type of each file based on filename, which should end with the well-known name string (config_db.json, snmp.yml,...). For backward compatibility, the old content-based detection is used as a fallback when there are only two files present. 

No processing of additional files is added in this PR.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8180)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @arifogel and @ratulm)

___
*[projects/batfish/src/main/java/org/batfish/job/ParseVendorConfigurationJob.java, line 114 at r2](https://reviewable.io/reviews/batfish/batfish/8180#-MyriD8zDSlgX4RFdFo-:-MyriD8zDSlgX4RFdFo0:b-5ape5v) ([raw file](https://github.com/batfish/batfish/blob/fed379a3beceb0ec294f27163b37582ecbf5a95c/projects/batfish/src/main/java/org/batfish/job/ParseVendorConfigurationJob.java#L114)):*
> ```Java
>     RESOLVE_CONF,
>     SNMP_YML
>   }
> ```

This should not be here, right? Should be somewhere inside SONiC parser.



_Code quote:_
```Java
  @VisibleForTesting
  enum SonicFileType {
    CONFIG_DB_JSON,
    FRR_CONF,
    RESOLVE_CONF,
    SNMP_YML
  }
```

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8180)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @arifogel and @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/job/ParseVendorConfigurationJob.java, line 114 at r2](https://reviewable.io/reviews/batfish/batfish/8180#-MyriD8zDSlgX4RFdFo-:-Mys4OrJ9JAFQdkJoAdd:b-sdtvor) ([raw file](https://github.com/batfish/batfish/blob/fed379a3beceb0ec294f27163b37582ecbf5a95c/projects/batfish/src/main/java/org/batfish/job/ParseVendorConfigurationJob.java#L114)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

This should not be here, right? Should be somewhere inside SONiC parser.
</blockquote></details>

Yes.  I think SONiC file type detection should also move there. My plan was to change the interface to SonicControlPlaneExtractor. I can do it part of this one. 

The main thing I wanted feedback for this PR was the method of classifying files (based on names, not content). Does that seem appropriate?

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8180)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/job/ParseVendorConfigurationJob.java, line 114 at r2](https://reviewable.io/reviews/batfish/batfish/8180#-MyriD8zDSlgX4RFdFo-:-Mys6m-x6oGz4SUsqNHu:b-fbhla2) ([raw file](https://github.com/batfish/batfish/blob/fed379a3beceb0ec294f27163b37582ecbf5a95c/projects/batfish/src/main/java/org/batfish/job/ParseVendorConfigurationJob.java#L114)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

Yes.  I think SONiC file type detection should also move there. My plan was to change the interface to SonicControlPlaneExtractor. I can do it part of this one. 

The main thing I wanted feedback for this PR was the method of classifying files (based on names, not content). Does that seem appropriate? 
</blockquote></details>

Gotcha. It looks like this was all added while I was on leave, so maybe I shoudl back off and let @arifogel review :)

**Review by dhalperi — COMMENTED** [review]
-reviewer:@dhalperi

> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8180#-:-Mys6s8RCZ6b9MohOZ0c:b-rfbfgy)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @arifogel)

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8180)* status: all files reviewed, 2 unresolved discussions (waiting on @ratulm)

___
*[projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/bb-test, line 0 at r3](https://reviewable.io/reviews/batfish/batfish/8180#-MzMAlRj5FlwAfCAtJwL:-MzMAlRj5FlwAfCAtJwM:b-e1mi4m) ([raw file](https://github.com/batfish/batfish/blob/45f56db1759cba552bcfa76a88f395b0163dfc76/projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/bb-test#L0)):*
Why are these gigantic unrelated files here?

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8180)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @arifogel)

___
*[projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/bb-test, line  at r3](https://reviewable.io/reviews/batfish/batfish/8180#-MzMAlRj5FlwAfCAtJwL:-MzMXVIm5LfbOvq9Dbde:b-icisfs) ([raw file](https://github.com/batfish/batfish/blob/6a35bfafa95be854182048de87c5be077e1b8672/projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/bb-test#L)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Why are these gigantic unrelated files here?
</blockquote></details>

Accidentally committed

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8180)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @ratulm)

**Review by ratulm — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8180)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ratulm)

**Pull request merged**
