### PR TITLE
IOS-XR parse and extract rd-set and route-policy rd in

### PR DESCRIPTION
**Pull request by arifogel**

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6903)* status: 6 of 28 files reviewed, all discussions resolved

**Review by dhalperi — COMMENTED** [review]
> Reviewed 21 of 21 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6903)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_xr/RoutePolicyBooleanRdIn.java, line 23 at r2](https://reviewable.io/reviews/batfish/batfish/6903#-MYBhTqD5aovUGs7h2xT:-MYBhTqE9UezDf5q5KMo:b4vob0r) ([raw file](https://github.com/batfish/batfish/blob/b2a33862762e4b96edb33d2e53993267104d16cd/projects/batfish/src/main/java/org/batfish/representation/cisco_xr/RoutePolicyBooleanRdIn.java#L23)):*
> ```Java
>   @Override
>   public BooleanExpr toBooleanExpr(CiscoXrConfiguration cc, Configuration c, Warnings w) {
>     // TODO: implement
> ```

no warn? we have a `w`.
___
*[projects/batfish/src/test/java/org/batfish/grammar/cisco_xr/XrGrammarTest.java, line 1331 at r3](https://reviewable.io/reviews/batfish/batfish/6903#-MYBhfBQDNVQyIqd8uZY:-MYBhfBQDNVQyIqd8uZZ:b-oomf1l) ([raw file](https://github.com/batfish/batfish/blob/4c20aee3a4cfd1d1a3d593564548e8a1205092d7/projects/batfish/src/test/java/org/batfish/grammar/cisco_xr/XrGrammarTest.java#L1331)):*
> ```
>               /* TODO: should this be something like WildcardPint16RangeExpr, since you cannot enter 0
>               as first component when using asdot? */
> ```
FYI I don't understand this; do I need to?

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6903)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_xr/RoutePolicyBooleanRdIn.java, line 23 at r2](https://reviewable.io/reviews/batfish/batfish/6903#-MYBhTqD5aovUGs7h2xT:-MYBipijBtDTf3cvgRjq:b-6wmkai) ([raw file](https://github.com/batfish/batfish/blob/b2a33862762e4b96edb33d2e53993267104d16cd/projects/batfish/src/main/java/org/batfish/representation/cisco_xr/RoutePolicyBooleanRdIn.java#L23)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

no warn? we have a `w`.
</blockquote></details>

We could, but we already have `todo` in extractor. Should I also warn here?
___
*[projects/batfish/src/test/java/org/batfish/grammar/cisco_xr/XrGrammarTest.java, line 1331 at r3](https://reviewable.io/reviews/batfish/batfish/6903#-MYBhfBQDNVQyIqd8uZY:-MYBiwiB-ztiKn4IUt66:b-5ktsw) ([raw file](https://github.com/batfish/batfish/blob/4c20aee3a4cfd1d1a3d593564548e8a1205092d7/projects/batfish/src/test/java/org/batfish/grammar/cisco_xr/XrGrammarTest.java#L1331)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
>               /* TODO: should this be something like WildcardPint16RangeExpr, since you cannot enter 0
>               as first component when using asdot? */
> ```
FYI I don't understand this; do I need to?
</blockquote></details>

The `P` in `Pint` is positive.
If you enter a literal number for the first component X in `X.Y:Z`, it must be `1-65535` (excludes 0).
You can also enter a wildcard for this component. So the question is, if you use a wildcard, will it also match a 0 in that position, or only 1-65535?

I figured it was low priority, so I would maybe address later when I implement conversion.

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6903)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_xr/RoutePolicyBooleanRdIn.java, line 23 at r2](https://reviewable.io/reviews/batfish/batfish/6903#-MYBhTqD5aovUGs7h2xT:-MYByBsg78xm_6McVO_m:b2a76lt) ([raw file](https://github.com/batfish/batfish/blob/b2a33862762e4b96edb33d2e53993267104d16cd/projects/batfish/src/main/java/org/batfish/representation/cisco_xr/RoutePolicyBooleanRdIn.java#L23)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

We could, but we already have `todo` in extractor. Should I also warn here?
</blockquote></details>

Eh, not sure. What I have seen is if we implement here we forget to remove the warn there... but there we warn on syntax. Thye're just different?
Whatever makes sense to you.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6903)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_xr/RoutePolicyBooleanRdIn.java, line 23 at r2](https://reviewable.io/reviews/batfish/batfish/6903#-MYBhTqD5aovUGs7h2xT:-MYC-1UXBs-gI7Y45TuC:b1cddy7) ([raw file](https://github.com/batfish/batfish/blob/b2a33862762e4b96edb33d2e53993267104d16cd/projects/batfish/src/main/java/org/batfish/representation/cisco_xr/RoutePolicyBooleanRdIn.java#L23)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Eh, not sure. What I have seen is if we implement here we forget to remove the warn there... but there we warn on syntax. Thye're just different?
Whatever makes sense to you.
</blockquote></details>

Similarly, if we warn here, we could still forget to remove the syntax warning. I think it's fine as is.

**Pull request merged**
