### PR TITLE
FRR: route-map match source-protocol

### PR DESCRIPTION
**Pull request by dhalperi**

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6618)* status: all files reviewed, 2 unresolved discussions (waiting on @dhalperi)

___
*[projects/batfish/src/test/java/org/batfish/representation/cumulus/RouteMapMatchSourceProtocolTest.java, line 30 at r1](https://reviewable.io/reviews/batfish/batfish/6618#-MTD9tO_8tQF91nwb3V6:-MTD9tO_8tQF91nwb3V7:b-9zxy9h) ([raw file](https://github.com/batfish/batfish/blob/f739163b698624a38b0bb75834e0ec72cf9d9692/projects/batfish/src/test/java/org/batfish/representation/cumulus/RouteMapMatchSourceProtocolTest.java#L30)):*
> ```Java
> import org.junit.Test;
> 
> public class RouteMapMatchSourceProtocolTest {
> ```

nitty nit: final and javadoc
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IsisRoute.java, line 90 at r1](https://reviewable.io/reviews/batfish/batfish/6618#-MTDARVE5Af33GPD6RT0:-MTDARVE5Af33GPD6RT1:b-ivxebl) ([raw file](https://github.com/batfish/batfish/blob/f739163b698624a38b0bb75834e0ec72cf9d9692/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IsisRoute.java#L90)):*
> ```Java
>   }
> 
>   /** Return a route builder with pre-filled mandatory values. To be used in tests only */
> ```

nit: why not put it in test lib? same question for ospf

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6618)* status: all files reviewed, 2 unresolved discussions (waiting on @dhalperi)

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6618)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel)

___
*[projects/batfish/src/test/java/org/batfish/representation/cumulus/RouteMapMatchSourceProtocolTest.java, line 30 at r1](https://reviewable.io/reviews/batfish/batfish/6618#-MTD9tO_8tQF91nwb3V6:-MTDFNzz9_57IxAkdQtB:b1ya3w3) ([raw file](https://github.com/batfish/batfish/blob/f739163b698624a38b0bb75834e0ec72cf9d9692/projects/batfish/src/test/java/org/batfish/representation/cumulus/RouteMapMatchSourceProtocolTest.java#L30)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

nitty nit: final and javadoc
</blockquote></details>

for test classes? meh.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IsisRoute.java, line 90 at r1](https://reviewable.io/reviews/batfish/batfish/6618#-MTDARVE5Af33GPD6RT0:-MTDFSoiEPtOnts_YVP0:bkjkdop) ([raw file](https://github.com/batfish/batfish/blob/f739163b698624a38b0bb75834e0ec72cf9d9692/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IsisRoute.java#L90)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

nit: why not put it in test lib? same question for ospf
</blockquote></details>

Following pattern for all existing routes.

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6618)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[projects/batfish/src/test/java/org/batfish/representation/cumulus/RouteMapMatchSourceProtocolTest.java, line 30 at r1](https://reviewable.io/reviews/batfish/batfish/6618#-MTD9tO_8tQF91nwb3V6:-MTDGC19CAbZafr9eBz3:b-u9wv8f) ([raw file](https://github.com/batfish/batfish/blob/f739163b698624a38b0bb75834e0ec72cf9d9692/projects/batfish/src/test/java/org/batfish/representation/cumulus/RouteMapMatchSourceProtocolTest.java#L30)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

for test classes? meh.
</blockquote></details>

(I did fix for the original class, which is what I had assumed you were asking about :p)

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6618)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[projects/batfish/src/test/java/org/batfish/representation/cumulus/RouteMapMatchSourceProtocolTest.java, line 30 at r1](https://reviewable.io/reviews/batfish/batfish/6618#-MTD9tO_8tQF91nwb3V6:-MTDI9gA5sXrqCoMDxIM:bxpbxcj) ([raw file](https://github.com/batfish/batfish/blob/f739163b698624a38b0bb75834e0ec72cf9d9692/projects/batfish/src/test/java/org/batfish/representation/cumulus/RouteMapMatchSourceProtocolTest.java#L30)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

(I did fix for the original class, which is what I had assumed you were asking about :p)
</blockquote></details>

I wasn't, but good think you noticed.

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6618)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[projects/batfish/src/test/java/org/batfish/representation/cumulus/RouteMapMatchSourceProtocolTest.java, line 30 at r1](https://reviewable.io/reviews/batfish/batfish/6618#-MTD9tO_8tQF91nwb3V6:-MTDI_rd7IW5psuzwbOi:bd457um) ([raw file](https://github.com/batfish/batfish/blob/f739163b698624a38b0bb75834e0ec72cf9d9692/projects/batfish/src/test/java/org/batfish/representation/cumulus/RouteMapMatchSourceProtocolTest.java#L30)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

I wasn't, but good think you noticed.
</blockquote></details>

Ha, yeah. Thanks for making me look twice :)

**Pull request merged**
