### PR TITLE
bgp: fix detection of new BGP sessions

### PR DESCRIPTION
**Pull request by dhalperi**
Fix a bug introduced in refactoring from batfish/batfish#6251, where
some routes would not be exchanged on BGP links that come up after
the snapshot starts. Fairly rare in datacenters, because BGP links in
datacenters are usually ebgp singlehop.

When sending routes to new links, we need to use the main RIB from
the previous round rather than the current RIB, because depending on
iteration order of the current round the current RIB may include
routes that were not yet advertised in the previous round. This adds
some memory overhead, but pointers to the routes are much smaller
than the routes themselves, so this should be less than 10%.

Add a test.

### CODE REVIEW

**Review by anothermattbrown — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6606)* status: 0 of 14 files reviewed, 1 unresolved discussion (waiting on @corinaminer and @dhalperi)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6606#-MSTdnt0BGPsq8wzmZym:-MSTdnt0BGPsq8wzmZyn:bf214i1) (no related file):*
(haven't looked at the code yet, but I have some questions about the description)

> depending on iteration order of the current round the current RIB may include
> routes that were not yet advertised in the previous round

This sounds like we need to advertise the current RIB, but you say we need to advertise the previous round's main RIB. Can you clarify that for me?

Also, I'm curious what kind of variance there is in the "iteration order".  Is it possible to fix that order, and would doing so allow us to avoid this overhead?

---

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 14 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6606)* status: all files reviewed, 1 unresolved discussion (waiting on @corinaminer and @dhalperi)

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6606)* status: 6 of 8 files reviewed, 1 unresolved discussion (waiting on @anothermattbrown and @corinaminer)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6606#-MSVdu47-P2LLN0ZiYJu:-MSVdu47-P2LLN0ZiYJv:b-i4j9oo) (no related file):*
Revised and added invariants per discussion.

---

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 2 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6606)* status: all files reviewed, 1 unresolved discussion (waiting on @corinaminer)

**Pull request merged**
