### PR TITLE
Allowing environment creation for delta testrigs

### PR DESCRIPTION
**Pull request by ratulm**

### CODE REVIEW

**Comment by dhalperi** [comment]
What type of test could we add that would demonstrate the new functionality? Would it be something in Java land or something in one of the demo scripts?

**Comment by ratulm** [comment]
I think we need a different testing strategy to the one we have right now to properly test such features. Lets discuss.

**Comment by arifogel** [comment]
What's happening with this pull request? Can I help?

**Comment by dhalperi** [comment]
I think Ratul was waiting for your review (you're marked as GitHub reviewer)

**Comment by dhalperi** [comment]
Green after @arifogel synced with master. Merging.

**Pull request merged**
