### PR TITLE
Add HSRP properties question

### PR DESCRIPTION
**Pull request by arifogel**
- copied from VRRP properties question, except:
  - slightly simpler implementation for populating virtual addresses in answer due to simpler model
    of HsrpGroup vs VrrpGroup

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7967)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel and @corinaminer)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7967#-Mu-La1n7-myzAaOreLb:-Mu-La1n7-myzAaOreLc:b-ljt44k) (no related file):*
FYI this is likely to cause doc failures in pybatfish. Be prepared :)

---

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7967)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @corinaminer)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7967)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

**Review by arifogel — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7967)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

**Pull request merged**
