### PR TITLE
A10: initial `interface` VS model

### PR DESCRIPTION
**Pull request by sfraint**
* Add support for extracting `ethernet` and `loopback` interfaces as well as a few common properties
* Add support for some class of string quoting in names (e.g. `"foo "and' bar'` == `"foo and bar"`)

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7408)* status: all files reviewed, 5 unresolved discussions (waiting on @sfraint)

___
*[projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Lexer.g4, line 17 at r1](https://reviewable.io/reviews/batfish/batfish/7408#-MjqkIxB90rR62NGY5C8:-MjqkIxB90rR62NGY5C9:b8hr5z3) ([raw file](https://github.com/batfish/batfish/blob/fcf9d64d693ee907f6f2808dd66eeaf4b50251c0/projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Lexer.g4#L17)):*
> ```ANTLR
> DISABLE: 'disable';
> ENABLE: 'enable';
> ETHERNET: 'ethernet';
> ```

Can you abbreviate interface type? What about mixed-case? If so, may want to use canonical interface name logic like for cisco. And that will of course make it impossible to have separate parsing without parser predicates, which are awful.
___
*[projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Lexer.g4, line 78 at r1](https://reviewable.io/reviews/batfish/batfish/7408#-MjqkCSq8p1yy-Y0TExA:-MjqkCSq8p1yy-Y0TExB:b-5dtwys) ([raw file](https://github.com/batfish/batfish/blob/fcf9d64d693ee907f6f2808dd66eeaf4b50251c0/projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Lexer.g4#L78)):*
> ```ANTLR
> 
> fragment
> F_IpSlashPrefix: '/' F_IpPrefixLength;
> ```

Whey the rename?
___
*[projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java, line 276 at r1](https://reviewable.io/reviews/batfish/batfish/7408#-Mjqmq_40XeXKl5BfDL6:-Mjqmq_40XeXKl5BfDL7:brxxoao) ([raw file](https://github.com/batfish/batfish/blob/fcf9d64d693ee907f6f2808dd66eeaf4b50251c0/projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java#L276)):*
> ```Java
> 
>   private @Nonnull Optional<String> toString(
>       ParserRuleContext messageCtx, String text, String type, Predicate<String> predicate) {
> ```

If this will only ever have one caller, can inline definition in that caller (above function?).
Better to minimize utility functions that take a raw string, to discourage use of `getText()` elsewhere.
___
*[projects/batfish/src/main/java/org/batfish/vendor/a10/representation/A10Configuration.java, line 58 at r1](https://reviewable.io/reviews/batfish/batfish/7408#-MjqixQj2Rs2zPCTcWWP:-MjqixQj2Rs2zPCTcWWQ:b-aze75i) ([raw file](https://github.com/batfish/batfish/blob/fcf9d64d693ee907f6f2808dd66eeaf4b50251c0/projects/batfish/src/main/java/org/batfish/vendor/a10/representation/A10Configuration.java#L58)):*
> ```Java
>   private Configuration _c;
>   private String _hostname;
>   private final Map<Integer, Interface> _interfacesEthernet;
> ```

Don't make these final. Add a finalize function that converts them to `ImmutableMap` that is called at end of extraction.
___
*[projects/batfish/src/main/java/org/batfish/vendor/a10/representation/Interface.java, line 24 at r1](https://reviewable.io/reviews/batfish/batfish/7408#-MjqiVsnDUUxLoPiOBa-:-Mjqi1ok0Kx43rLQp8dt:b-vftjm) ([raw file](https://github.com/batfish/batfish/blob/fcf9d64d693ee907f6f2808dd66eeaf4b50251c0/projects/batfish/src/main/java/org/batfish/vendor/a10/representation/Interface.java#L24)):*
> ```Java
>   }
> 
>   public boolean getEnabledEffective() {
> ```

Is this ever used during parsing/extraction?
I'd lean toward putting this type of thing in conversion code, especially if there is a global mutable default like on some cisco devices.

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7408)* status: 6 of 14 files reviewed, 5 unresolved discussions (waiting on @arifogel)

___
*[projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Lexer.g4, line 17 at r1](https://reviewable.io/reviews/batfish/batfish/7408#-MjqkIxB90rR62NGY5C8:-Mk3JdM95oNL_HxWUByg:bwke1xm) ([raw file](https://github.com/batfish/batfish/blob/fcf9d64d693ee907f6f2808dd66eeaf4b50251c0/projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Lexer.g4#L17)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Can you abbreviate interface type? What about mixed-case? If so, may want to use canonical interface name logic like for cisco. And that will of course make it impossible to have separate parsing without parser predicates, which are awful.
</blockquote></details>

afaict you can abbreviate anything that is unambiguous, e.g. at the top-level `in e 1` is the same as `interface ethernet 1`, and case doesn't matter: `InTeRfAcE eThErNeT 1` is the same as the others

do we want to special-case the interface type string?
also, we're not actually using the user-supplied string in the VS model - we're just tracking numbers (which is how the device appears to track them - and the device uses different case in different contexts as well)
___
*[projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Lexer.g4, line 78 at r1](https://reviewable.io/reviews/batfish/batfish/7408#-MjqkCSq8p1yy-Y0TExA:-Mk38L524FUW8rTyV2Ic:b-o82gm5) ([raw file](https://github.com/batfish/batfish/blob/fcf9d64d693ee907f6f2808dd66eeaf4b50251c0/projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Lexer.g4#L78)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Whey the rename?
</blockquote></details>

Just to avoid confusion - elsewhere (other vendors) we use `IpPrefix` to mean address + slash prefix, here we're just catching the slash prefix portion

I can change it back if you prefer
___
*[projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java, line 276 at r1](https://reviewable.io/reviews/batfish/batfish/7408#-Mjqmq_40XeXKl5BfDL6:-Mk38f8g83h0UTq9714b:bvnrpcm) ([raw file](https://github.com/batfish/batfish/blob/fcf9d64d693ee907f6f2808dd66eeaf4b50251c0/projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java#L276)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

If this will only ever have one caller, can inline definition in that caller (above function?).
Better to minimize utility functions that take a raw string, to discourage use of `getText()` elsewhere.
</blockquote></details>

updated
___
*[projects/batfish/src/main/java/org/batfish/vendor/a10/representation/A10Configuration.java, line 58 at r1](https://reviewable.io/reviews/batfish/batfish/7408#-MjqixQj2Rs2zPCTcWWP:-Mk3Er0Y5kh3ReToydrN:bvnrpcm) ([raw file](https://github.com/batfish/batfish/blob/fcf9d64d693ee907f6f2808dd66eeaf4b50251c0/projects/batfish/src/main/java/org/batfish/vendor/a10/representation/A10Configuration.java#L58)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Don't make these final. Add a finalize function that converts them to `ImmutableMap` that is called at end of extraction.
</blockquote></details>

updated
___
*[projects/batfish/src/main/java/org/batfish/vendor/a10/representation/Interface.java, line 24 at r1](https://reviewable.io/reviews/batfish/batfish/7408#-MjqiVsnDUUxLoPiOBa-:-Mk3G6G105Vc6hw1Xm01:bb7ohn6) ([raw file](https://github.com/batfish/batfish/blob/fcf9d64d693ee907f6f2808dd66eeaf4b50251c0/projects/batfish/src/main/java/org/batfish/vendor/a10/representation/Interface.java#L24)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Is this ever used during parsing/extraction?
I'd lean toward putting this type of thing in conversion code, especially if there is a global mutable default like on some cisco devices.
</blockquote></details>

sgtm

**Review by arifogel — COMMENTED** [review]
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7408)* status: all files reviewed, 3 unresolved discussions (waiting on @sfraint)

___
*[projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Lexer.g4, line 17 at r1](https://reviewable.io/reviews/batfish/batfish/7408#-MjqkIxB90rR62NGY5C8:-Mk40TUNDD9yi3klNEu_:b-7rrkab) ([raw file](https://github.com/batfish/batfish/blob/fcf9d64d693ee907f6f2808dd66eeaf4b50251c0/projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Lexer.g4#L17)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

afaict you can abbreviate anything that is unambiguous, e.g. at the top-level `in e 1` is the same as `interface ethernet 1`, and case doesn't matter: `InTeRfAcE eThErNeT 1` is the same as the others

do we want to special-case the interface type string?
also, we're not actually using the user-supplied string in the VS model - we're just tracking numbers (which is how the device appears to track them - and the device uses different case in different contexts as well)

</blockquote></details>

defer
___
*[projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Lexer.g4, line 78 at r1](https://reviewable.io/reviews/batfish/batfish/7408#-MjqkCSq8p1yy-Y0TExA:-Mk4-jML5LKODowzCKk0:b-e189d3) ([raw file](https://github.com/batfish/batfish/blob/fcf9d64d693ee907f6f2808dd66eeaf4b50251c0/projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Lexer.g4#L78)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

Just to avoid confusion - elsewhere (other vendors) we use `IpPrefix` to mean address + slash prefix, here we're just catching the slash prefix portion

I can change it back if you prefer
</blockquote></details>

Oh I missed that. Now I see what you did with the rule.
If you are going to support both mask and length, then your way is fine since it is more LL(1).
___
*[projects/batfish/src/main/java/org/batfish/vendor/a10/representation/Interface.java, line 24 at r1](https://reviewable.io/reviews/batfish/batfish/7408#-MjqiVsnDUUxLoPiOBa-:-Mk40sdE2Ekwp-XjcGSg:b-lsrgsl) ([raw file](https://github.com/batfish/batfish/blob/fcf9d64d693ee907f6f2808dd66eeaf4b50251c0/projects/batfish/src/main/java/org/batfish/vendor/a10/representation/Interface.java#L24)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

sgtm
</blockquote></details>

also getMtuEffective

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7408)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/vendor/a10/representation/Interface.java, line 24 at r1](https://reviewable.io/reviews/batfish/batfish/7408#-MjqiVsnDUUxLoPiOBa-:-Mk42M8K1wd0T8DUjZ88:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/fcf9d64d693ee907f6f2808dd66eeaf4b50251c0/projects/batfish/src/main/java/org/batfish/vendor/a10/representation/Interface.java#L24)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

also getMtuEffective
</blockquote></details>

done

**Review by sfraint — COMMENTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7408)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

**Pull request merged**
