### PR TITLE
Factor out, disable, and replace PoolMgr and Worker endpoints

### PR DESCRIPTION
**Pull request by arifogel**
- Factor out PoolMgr and Worker functionality into executor abstraction
- Create alternative executor that directly creates worker threads instead of communicating between REST endpoints
- Enable new atlernative executor and hide old implementation behind compile-time constant: `BfConsts.USE_LEGACY_POOL_WORK_EXECUTOR`

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8445)* status: 0 of 24 files reviewed, 1 unresolved discussion (waiting on @dhalperi)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/8445#-N8fBuYEA2RnKRjqK_tR:-N8fBuYEA2RnKRjqK_tS:bvbdbtc) (no related file):*
self-merge only

___

**Review by dhalperi — COMMENTED** [review]
> Reviewed 3 of 13 files at r1, 22 of 22 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8445)* status: all files reviewed, 5 unresolved discussions (waiting on @arifogel and @dhalperi)

___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/common/BatfishWorkerService.java` line 10 at r2](https://reviewable.io/reviews/batfish/batfish/8445#-N8fEdIr4rgYHjGHAOrz:-N8fEdIr4rgYHjGHAOs-:b-rzxrdt) ([raw file](https://github.com/batfish/batfish/blob/a2c2c20b49d739a463a5f99e6461e771edc8db84/projects/batfish-common-protocol/src/main/java/org/batfish/common/BatfishWorkerService.java#L10)):*
> ```Java
> 
>   /** Get task status for taskId. */
>   Task getTaskStatus(String taskId);
> ```

This is @Nullable, right?
___
*[`projects/coordinator/src/main/java/org/batfish/coordinator/BatfishWorkerServiceWorkExecutor.java` line 37 at r2](https://reviewable.io/reviews/batfish/batfish/8445#-N8fHlZz6IAnZ7-zbcEU:-N8fHlZz6IAnZ7-zbcEV:b-ibsswq) ([raw file](https://github.com/batfish/batfish/blob/a2c2c20b49d739a463a5f99e6461e771edc8db84/projects/coordinator/src/main/java/org/batfish/coordinator/BatfishWorkerServiceWorkExecutor.java#L37)):*
> ```Java
>         Main.getSettings().getContainersLocation().toAbsolutePath().toString());
>     _logger.infof("BFS:runTask(%s,%s)\n", taskId, params);
>     assert !Strings.isNullOrEmpty(taskId);
> ```

what is this assertion for? It should be a checkArgument if anything, right?
___
*[`projects/coordinator/src/main/java/org/batfish/coordinator/BatfishWorkerServiceWorkExecutor.java` line 57 at r2](https://reviewable.io/reviews/batfish/batfish/8445#-N8fHaer9M9UUWxx3ka9:-N8fHaer9M9UUWxx3kaA:bls25mf) ([raw file](https://github.com/batfish/batfish/blob/a2c2c20b49d739a463a5f99e6461e771edc8db84/projects/coordinator/src/main/java/org/batfish/coordinator/BatfishWorkerServiceWorkExecutor.java#L57)):*
> ```Java
>           return SubmissionResult.success(() -> _batfishWorkerService.getTaskStatus(taskId));
>         case BUSY:
>           _logger.warn(String.format("Work with ID: %s requeued because worker is busy\n", taskId));
> ```

I don't understand how requeued gets here. This thing returns failure.

Seems like this logging, etc., should be in the caller?



_Code quote:_
```Java
requeued because worker is busy
```
___
*[`projects/coordinator/src/main/java/org/batfish/coordinator/SubmissionResult.java` line 16 at r2](https://reviewable.io/reviews/batfish/batfish/8445#-N8fIEU45S4gHJ9Q6Ps1:-N8fIEU45S4gHJ9Q6Ps2:bvzyyl0) ([raw file](https://github.com/batfish/batfish/blob/a2c2c20b49d739a463a5f99e6461e771edc8db84/projects/coordinator/src/main/java/org/batfish/coordinator/SubmissionResult.java#L16)):*
> ```Java
>     FAILURE,
>     TERMINATED
>   }
> ```

These should be public and commented, right? Especially if one of them means "busy"?



_Code quote:_
```Java
  enum Type {
    ERROR,
    SUCCESS,
    FAILURE,
    TERMINATED
  }
```

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8445)* status: 17 of 25 files reviewed, 4 unresolved discussions (waiting on @dhalperi)

___
*[`projects/batfish-common-protocol/src/main/java/org/batfish/common/BatfishWorkerService.java` line 10 at r2](https://reviewable.io/reviews/batfish/batfish/8445#-N8fEdIr4rgYHjGHAOrz:-N8iwGEh206DvirByfNv:bi5egpn) ([raw file](https://github.com/batfish/batfish/blob/a2c2c20b49d739a463a5f99e6461e771edc8db84/projects/batfish-common-protocol/src/main/java/org/batfish/common/BatfishWorkerService.java#L10)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

This is @Nullable, right?
</blockquote></details>

It probably should be for the API to be sensible. Updated.
___
*[`projects/coordinator/src/main/java/org/batfish/coordinator/BatfishWorkerServiceWorkExecutor.java` line 37 at r2](https://reviewable.io/reviews/batfish/batfish/8445#-N8fHlZz6IAnZ7-zbcEU:-N8j33h8AP4aEg7syDeD:b-sfidww) ([raw file](https://github.com/batfish/batfish/blob/a2c2c20b49d739a463a5f99e6461e771edc8db84/projects/coordinator/src/main/java/org/batfish/coordinator/BatfishWorkerServiceWorkExecutor.java#L37)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

what is this assertion for? It should be a checkArgument if anything, right?
</blockquote></details>

sure, done
___
*[`projects/coordinator/src/main/java/org/batfish/coordinator/BatfishWorkerServiceWorkExecutor.java` line 57 at r2](https://reviewable.io/reviews/batfish/batfish/8445#-N8fHaer9M9UUWxx3ka9:-N8j6L_u8HAeaY98x7uF:bcvz5qb) ([raw file](https://github.com/batfish/batfish/blob/a2c2c20b49d739a463a5f99e6461e771edc8db84/projects/coordinator/src/main/java/org/batfish/coordinator/BatfishWorkerServiceWorkExecutor.java#L57)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I don't understand how requeued gets here. This thing returns failure.

Seems like this logging, etc., should be in the caller?
</blockquote></details>

The previous nomenclature distinguished between FAILURE and ERROR, where the former meant "failed to assign because no idle workers". Renamed to BUSY for clarity.
___
*[`projects/coordinator/src/main/java/org/batfish/coordinator/SubmissionResult.java` line 16 at r2](https://reviewable.io/reviews/batfish/batfish/8445#-N8fIEU45S4gHJ9Q6Ps1:-N8j6WrNA_1YqJf8mKIr:b-ndtd8c) ([raw file](https://github.com/batfish/batfish/blob/a2c2c20b49d739a463a5f99e6461e771edc8db84/projects/coordinator/src/main/java/org/batfish/coordinator/SubmissionResult.java#L16)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

These should be public and commented, right? Especially if one of them means "busy"?
</blockquote></details>

done, and renamed FAILURE to BUSY.

**Review by dhalperi — COMMENTED** [review]
Nice!

> Reviewed 8 of 8 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8445#-:-N8j9t0j0jsbp-PorcwP:b-83sjoh)* status: all files reviewed, 6 unresolved discussions (waiting on @arifogel)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/8445#-N8fBuYEA2RnKRjqK_tR:-N8j9o6y0cOQRYj2uB-e:b4h44vn) (no related file):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

self-merge only
</blockquote></details>

(FYI `Working` is the usual disposition here -- then it shows up as action for self, instead of action for all others)

___
___
*[`projects/coordinator/src/main/java/org/batfish/coordinator/BatfishWorkerServiceWorkExecutor.java` line 36 at r3](https://reviewable.io/reviews/batfish/batfish/8445#-N8j96duDWfZPK-wNUxo:-N8j96duDWfZPK-wNUxp:b-exhou6) ([raw file](https://github.com/batfish/batfish/blob/a0f7a50b55e9538cdcfdf43fe473318e2250f2b3/projects/coordinator/src/main/java/org/batfish/coordinator/BatfishWorkerServiceWorkExecutor.java#L36)):*
> ```Java
>   public SubmissionResult submit(QueuedWork work) {
>     try {
>       String taskId = work.getId().toString();
> ```

would suggest some helpful refactorings:

1. Create a helper so that the try is one line. Will make the code much easier to understand.
2. Create (and test?) helpers for the separate logic pieces. For example, params to args is a nice contained thing, and then would be easy to unit test.
___
*[`projects/coordinator/src/main/java/org/batfish/coordinator/BatfishWorkerServiceWorkExecutor.java` line 52 at r3](https://reviewable.io/reviews/batfish/batfish/8445#-N8j9ZSG1swL6gJAHjEk:-N8j9ZSG1swL6gJAHjEl:bglbzp1) ([raw file](https://github.com/batfish/batfish/blob/a0f7a50b55e9538cdcfdf43fe473318e2250f2b3/projects/coordinator/src/main/java/org/batfish/coordinator/BatfishWorkerServiceWorkExecutor.java#L52)):*
> ```Java
>           });
>       List<String> argsList = argsBuilder.build();
>       String[] args = argsBuilder.build().toArray(new String[argsList.size()]);
> ```

`argsList`?



_Code quote:_
```Java
argsBuilder.build()
```
___
*[`projects/coordinator/src/main/java/org/batfish/coordinator/BatfishWorkerServiceWorkExecutor.java` line 53 at r3](https://reviewable.io/reviews/batfish/batfish/8445#-N8j9bs75q4gF2DmWieS:-N8j9bs75q4gF2DmWieT:bglbzp1) ([raw file](https://github.com/batfish/batfish/blob/a0f7a50b55e9538cdcfdf43fe473318e2250f2b3/projects/coordinator/src/main/java/org/batfish/coordinator/BatfishWorkerServiceWorkExecutor.java#L53)):*
> ```Java
>       List<String> argsList = argsBuilder.build();
>       String[] args = argsBuilder.build().toArray(new String[argsList.size()]);
>       _logger.infof("Will run with args: %s\n", Arrays.toString(args));
> ```

`argsList`?



_Code quote:_
```Java
Arrays.toString(args)
```
___
*[`projects/coordinator/src/main/java/org/batfish/coordinator/SubmissionResult.java` line 26 at r3](https://reviewable.io/reviews/batfish/batfish/8445#-N8j8_rd6fELJqCAEOIV:-N8j8_rd6fELJqCAEOIW:bvag0bw) ([raw file](https://github.com/batfish/batfish/blob/a0f7a50b55e9538cdcfdf43fe473318e2250f2b3/projects/coordinator/src/main/java/org/batfish/coordinator/SubmissionResult.java#L26)):*
> ```Java
>      */
>     BUSY,
>     /** The submission succeeded, but has already terminated. */
> ```

How is this possible, and why is it needed?

If we didn't have it, wouldn't the next "Get status" succeed anyway?



_Code quote:_
```Java
The submission succeeded, but has already terminated. 
```
___
*[`projects/coordinator/src/main/java/org/batfish/coordinator/SubmissionResult.java` line 56 at r3](https://reviewable.io/reviews/batfish/batfish/8445#-N8j8kOX82EeqorwVQSP:-N8j8kOX82EeqorwVQSQ:b96tjlu) ([raw file](https://github.com/batfish/batfish/blob/a0f7a50b55e9538cdcfdf43fe473318e2250f2b3/projects/coordinator/src/main/java/org/batfish/coordinator/SubmissionResult.java#L56)):*
> ```Java
>    */
>   public @Nonnull TaskHandle getTaskHandle() {
>     checkState(_type == Type.SUCCESS, "Only a submission of type SUCCESS has a task handle");
> ```

I'd put the type of the current SR in the errors.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8445)* status: 20 of 26 files reviewed, 5 unresolved discussions (waiting on @arifogel and @dhalperi)

___
*[`projects/coordinator/src/main/java/org/batfish/coordinator/BatfishWorkerServiceWorkExecutor.java` line 36 at r3](https://reviewable.io/reviews/batfish/batfish/8445#-N8j96duDWfZPK-wNUxo:-N8jBX015wp3Ks3BZ6_r:b-l77gbo) ([raw file](https://github.com/batfish/batfish/blob/a0f7a50b55e9538cdcfdf43fe473318e2250f2b3/projects/coordinator/src/main/java/org/batfish/coordinator/BatfishWorkerServiceWorkExecutor.java#L36)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

would suggest some helpful refactorings:

1. Create a helper so that the try is one line. Will make the code much easier to understand.
2. Create (and test?) helpers for the separate logic pieces. For example, params to args is a nice contained thing, and then would be easy to unit test.
</blockquote></details>

1. done
2. done
___
*[`projects/coordinator/src/main/java/org/batfish/coordinator/BatfishWorkerServiceWorkExecutor.java` line 52 at r3](https://reviewable.io/reviews/batfish/batfish/8445#-N8j9ZSG1swL6gJAHjEk:-N8jDuWR6sjGb2T0S20E:bg5t3nw) ([raw file](https://github.com/batfish/batfish/blob/a0f7a50b55e9538cdcfdf43fe473318e2250f2b3/projects/coordinator/src/main/java/org/batfish/coordinator/BatfishWorkerServiceWorkExecutor.java#L52)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

`argsList`?
</blockquote></details>

fixed in refactor
___
*[`projects/coordinator/src/main/java/org/batfish/coordinator/BatfishWorkerServiceWorkExecutor.java` line 53 at r3](https://reviewable.io/reviews/batfish/batfish/8445#-N8j9bs75q4gF2DmWieS:-N8jDzju6WqBlX2TsHsh:bg5t3nw) ([raw file](https://github.com/batfish/batfish/blob/a0f7a50b55e9538cdcfdf43fe473318e2250f2b3/projects/coordinator/src/main/java/org/batfish/coordinator/BatfishWorkerServiceWorkExecutor.java#L53)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

`argsList`?
</blockquote></details>

fixed in refactor
___
*[`projects/coordinator/src/main/java/org/batfish/coordinator/SubmissionResult.java` line 26 at r3](https://reviewable.io/reviews/batfish/batfish/8445#-N8j8_rd6fELJqCAEOIV:-N8jLLgh39O8CwGYS3Kt:btptlmh) ([raw file](https://github.com/batfish/batfish/blob/a0f7a50b55e9538cdcfdf43fe473318e2250f2b3/projects/coordinator/src/main/java/org/batfish/coordinator/SubmissionResult.java#L26)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

How is this possible, and why is it needed?

If we didn't have it, wouldn't the next "Get status" succeed anyway?
</blockquote></details>

looks like an "optimization" in the old code. terrible abstraction. removed.
___
*[`projects/coordinator/src/main/java/org/batfish/coordinator/SubmissionResult.java` line 56 at r3](https://reviewable.io/reviews/batfish/batfish/8445#-N8j8kOX82EeqorwVQSP:-N8jMeyr2bWYbFAHS55y:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/a0f7a50b55e9538cdcfdf43fe473318e2250f2b3/projects/coordinator/src/main/java/org/batfish/coordinator/SubmissionResult.java#L56)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I'd put the type of the current SR in the errors.
</blockquote></details>

done

**Review by dhalperi — COMMENTED** [review]
:lgtm: ship it.

> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8445#-:-N8jOIon1e5-AK7knV8O:b-quxs7m)* status: all files reviewed, 2 unresolved discussions (waiting on @arifogel)

___
*[`projects/coordinator/src/test/java/org/batfish/coordinator/BatfishWorkerServiceWorkExecutorTest.java` line 123 at r5](https://reviewable.io/reviews/batfish/batfish/8445#-N8jOBM32wGuIwdKKq-A:-N8jOBN712tERWp8qhhC:bgo3oim) ([raw file](https://github.com/batfish/batfish/blob/553c79d555b8d796b3633de7401dcaa8456dac9f/projects/coordinator/src/test/java/org/batfish/coordinator/BatfishWorkerServiceWorkExecutorTest.java#L123)):*
> ```Java
>   private static @Nonnull QueuedWork getTestQueuedWork() {
>     UUID uuid = UUID.randomUUID();
>     WorkItem wi = new WorkItem(uuid, "n", "s", ImmutableMap.of("foo", "bar"));
> ```

worth adding ("novalue", "")?



_Code quote:_
```Java
WorkItem wi = new WorkItem(uuid, "n", "s", ImmutableMap.of("foo", "bar"));
```

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8445)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[`projects/coordinator/src/test/java/org/batfish/coordinator/BatfishWorkerServiceWorkExecutorTest.java` line 123 at r5](https://reviewable.io/reviews/batfish/batfish/8445#-N8jOBM32wGuIwdKKq-A:-N8jOOEEAb65YYuw_O-d:b-hgss6n) ([raw file](https://github.com/batfish/batfish/blob/553c79d555b8d796b3633de7401dcaa8456dac9f/projects/coordinator/src/test/java/org/batfish/coordinator/BatfishWorkerServiceWorkExecutorTest.java#L123)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

worth adding ("novalue", "")?
</blockquote></details>

yeah for coverage, done.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8445)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8445)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8445)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8445)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Pull request merged**
