### PR TITLE
Abstract IpOwners and create static and dataplane-based implementations

### PR DESCRIPTION
**Pull request by arifogel**
- Make `IpOwners` an interface
  - move bulk of implementation to `IpOwnersBaseImpl`
- Create `StaticIpOwners`
  - identical to old `IpOwners`
  - does not use dataplane information
- Create `DataplaneIpOwners`
  - can use data plane information and traceroute engine to evaluate HSRP/VRRP tracks
- Update `DataPlaneTrackEvaluator`
  - can now check any VRF of a node when tracking a route
  - add traceroute engine for future reachability tracking
- split `IpOwners` usage in computation of dataplane
  - initially use `StaticIpOwners`
  - for fixed point, use `DataPlaneIpOwners`
- Use same `DataPlaneTrackEvaluator` for fixed-point static route and HSRP/VRRP tracking

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8000)* status: 0 of 36 files reviewed, all discussions resolved (waiting on @corinaminer and @dhalperi)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/IpOwnersBaseImpl.java, line 1 at r1](https://reviewable.io/reviews/batfish/batfish/8000#-Mux6z7MD21-VkrTmsKl:-Mux6z7MD21-VkrTmsKm:b-7u2psr) ([raw file](https://github.com/batfish/batfish/blob/bbe41a0a6f7bcbd05225f7bdab9f10a7e10161b5/projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/IpOwnersBaseImpl.java#L1)):*
> ```Java
> package org.batfish.common.topology;
> ```

Overview of changes:
- pull in all implementation from `IpOwners`
- plumb track method evaluator provider through to hsrp/vrrp track evaluation funcitons
- add a bunch of null annotations

Otherwise, no functional differences

**Review by dhalperi — COMMENTED** [review]
> Reviewed 26 of 36 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8000)* status: 26 of 36 files reviewed, 11 unresolved discussions (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/DataPlaneIpOwners.java, line 15 at r1](https://reviewable.io/reviews/batfish/batfish/8000#-MuxL06S-aZXzTBReikP:-MuxL06S-aZXzTBReikQ:by1mpn0) ([raw file](https://github.com/batfish/batfish/blob/bbe41a0a6f7bcbd05225f7bdab9f10a7e10161b5/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/DataPlaneIpOwners.java#L15)):*
> ```Java
>  */
> @ParametersAreNonnullByDefault
> public final class DataPlaneIpOwners extends IpOwnersBaseImpl {
> ```

Should not be public, should it?
___
*[projects/batfish/src/test/java/org/batfish/dataplane/ibdp/DataplaneTrackEvaluatorTest.java, line 125 at r1](https://reviewable.io/reviews/batfish/batfish/8000#-MuxMVpd1G8ilMY_IEc-:-MuxMVpd1G8ilMY_IEc0:bx1ahih) ([raw file](https://github.com/batfish/batfish/blob/bbe41a0a6f7bcbd05225f7bdab9f10a7e10161b5/projects/batfish/src/test/java/org/batfish/dataplane/ibdp/DataplaneTrackEvaluatorTest.java#L125)):*
> ```Java
>     public SortedMap<Flow, List<TraceAndReverseFlow>> computeTracesAndReverseFlows(
>         Set<Flow> flows, Set<FirewallSessionTraceInfo> sessions, boolean ignoreFilters) {
>       return null;
> ```

This can't compile, can it? At least return an empty map.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/IpOwnersBaseImpl.java, line 96 at r1](https://reviewable.io/reviews/batfish/batfish/8000#-MuxIk9G3iyK1D_W62vG:-MuxIk9G3iyK1D_W62vH:b2qk0fc) ([raw file](https://github.com/batfish/batfish/blob/bbe41a0a6f7bcbd05225f7bdab9f10a7e10161b5/projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/IpOwnersBaseImpl.java#L96)):*
> ```Java
>   @Override
>   public boolean equals(@Nullable Object o) {
>     if (this == o) {
> ```

Why implement equals and hashCode?

if we're going to be using hashCode, we should memoize it (and use it here?). Looks rather expensive.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/IpOwnersBaseImpl.java, line 125 at r1](https://reviewable.io/reviews/batfish/batfish/8000#-MuxJFte2BpP2zKVo7Dh:-MuxJFte2BpP2zKVo7Di:b-rj5j2p) ([raw file](https://github.com/batfish/batfish/blob/bbe41a0a6f7bcbd05225f7bdab9f10a7e10161b5/projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/IpOwnersBaseImpl.java#L125)):*
> ```Java
>    * methods to evaluate track methods affecting HSRP/VRRP priorities.
>    */
>   protected IpOwnersBaseImpl(
> ```

Move this to the top of the class? Everything else is an internal implementation detail, right?

Add copious javadoc explaining why we need l3adjacencies and track? Enough that extenders/callers can know which to provide?
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/StaticIpOwners.java, line 25 at r1](https://reviewable.io/reviews/batfish/batfish/8000#-MuxJYTh5RrfLd-h8O9G:-MuxJYTh5RrfLd-h8O9H:b-444jgq) ([raw file](https://github.com/batfish/batfish/blob/bbe41a0a6f7bcbd05225f7bdab9f10a7e10161b5/projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/StaticIpOwners.java#L25)):*
> ```Java
>  */
> @ParametersAreNonnullByDefault
> public final class StaticIpOwners extends IpOwnersBaseImpl {
> ```

`Static` doesn't seem like a descriptive name here -- more how it works rather than what it does/is. And confusion with things like static routes.

Do you mean something like "Initial", which would match things like L3Adjacencies and L3Topology, or "PreDataplane", which might be useful for questions?
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/StaticIpOwners.java, line 25 at r1](https://reviewable.io/reviews/batfish/batfish/8000#-MuxK6yl2bUe7-Rasd9j:-MuxK6yl2bUe7-Rasd9k:b-kfuxar) ([raw file](https://github.com/batfish/batfish/blob/bbe41a0a6f7bcbd05225f7bdab9f10a7e10161b5/projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/StaticIpOwners.java#L25)):*
> ```Java
>  */
> @ParametersAreNonnullByDefault
> public final class StaticIpOwners extends IpOwnersBaseImpl {
> ```

This class shouldn't be public, should it? Still looks too easy to use wrong.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/StaticIpOwners.java, line 27 at r1](https://reviewable.io/reviews/batfish/batfish/8000#-MuxJv3248uWF-FG-BvX:-MuxJv3248uWF-FG-BvY:b-r2um5z) ([raw file](https://github.com/batfish/batfish/blob/bbe41a0a6f7bcbd05225f7bdab9f10a7e10161b5/projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/StaticIpOwners.java#L27)):*
> ```Java
> public final class StaticIpOwners extends IpOwnersBaseImpl {
> 
>   public StaticIpOwners(Map<String, Configuration> configurations, L3Adjacencies l3Adjacencies) {
> ```

It looks like the user can pass whatever L3Adjacencies they want here. What enforces that they use the initial L3 adjacencies?
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/StaticTrackMethodEvaluator.java, line 16 at r1](https://reviewable.io/reviews/batfish/batfish/8000#-MuxKHdy2E6sfF1hFNi3:-MuxKHdy2E6sfF1hFNi4:bz7jkaz) ([raw file](https://github.com/batfish/batfish/blob/bbe41a0a6f7bcbd05225f7bdab9f10a7e10161b5/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/StaticTrackMethodEvaluator.java#L16)):*
> ```Java
>  */
> public class StaticTrackMethodEvaluator implements GenericTrackMethodVisitor<Boolean> {
>   public StaticTrackMethodEvaluator(Configuration configuration) {
> ```

Same comment on class name here. `Static` seems wrong...

Before this was only used for static routes, but now it's used for all kinds of things?
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/TrackMethodEvaluatorProvider.java, line 12 at r1](https://reviewable.io/reviews/batfish/batfish/8000#-MuxKUef47Rc3myxyO0s:-MuxKUef47Rc3myxyO0t:b-10p4du) ([raw file](https://github.com/batfish/batfish/blob/bbe41a0a6f7bcbd05225f7bdab9f10a7e10161b5/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/TrackMethodEvaluatorProvider.java#L12)):*
> ```Java
> public interface TrackMethodEvaluatorProvider {
>   @Nonnull
>   GenericTrackMethodVisitor<Boolean> forConfiguration(Configuration c);
> ```

What is a `GenericTrackMethodVisitor`? I thought it was just called `TrackMethodVisitor`?



_Code quote:_
```Java
GenericTrackMethodVisitor
```
___
*[projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionCompatibilityAnswerer.java, line 141 at r1](https://reviewable.io/reviews/batfish/batfish/8000#-MuxKqwRBN8blPQ7doKR:-MuxKqwRBN8blPQ7doKS:b-vja228) ([raw file](https://github.com/batfish/batfish/blob/bbe41a0a6f7bcbd05225f7bdab9f10a7e10161b5/projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionCompatibilityAnswerer.java#L141)):*
> ```Java
>     Map<Ip, Map<String, Set<String>>> ipVrfOwners =
>         new StaticIpOwners(
>                 configurations, _batfish.getTopologyProvider().getInitialL3Adjacencies(snapshot))
> ```

why is this not just using getInitialIpOwners?



_Code quote:_
```Java
        new StaticIpOwners(
                configurations, _batfish.getTopologyProvider().getInitialL3Adjacencies(snapshot))
```
___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/TracerouteEngineImpl.java, line 1 at r1](https://reviewable.io/reviews/batfish/batfish/8000#-MuxM2fB8G-opStIR0o3:-MuxM2fB8G-opStIR0o4:b-i7pw2n) ([raw file](https://github.com/batfish/batfish/blob/bbe41a0a6f7bcbd05225f7bdab9f10a7e10161b5/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/TracerouteEngineImpl.java#L1)):*
> ```Java
> package org.batfish.dataplane.ibdp;
> ```

Having a hard time seeing why this happened.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8000)* status: 9 of 43 files reviewed, 9 unresolved discussions (waiting on @corinaminer and @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/DataPlaneIpOwners.java, line 15 at r1](https://reviewable.io/reviews/batfish/batfish/8000#-MuxL06S-aZXzTBReikP:-Muxjlcd6BHJSDUy2QTx:b-apbnb0) ([raw file](https://github.com/batfish/batfish/blob/bbe41a0a6f7bcbd05225f7bdab9f10a7e10161b5/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/DataPlaneIpOwners.java#L15)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Should not be public, should it?
</blockquote></details>

noipe. fixed.
___
*[projects/batfish/src/test/java/org/batfish/dataplane/ibdp/DataplaneTrackEvaluatorTest.java, line 125 at r1](https://reviewable.io/reviews/batfish/batfish/8000#-MuxMVpd1G8ilMY_IEc-:-MuxakqU9lxUHAK0W9aH:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/bbe41a0a6f7bcbd05225f7bdab9f10a7e10161b5/projects/batfish/src/test/java/org/batfish/dataplane/ibdp/DataplaneTrackEvaluatorTest.java#L125)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

This can't compile, can it? At least return an empty map.
</blockquote></details>

done
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/IpOwnersBaseImpl.java, line 96 at r1](https://reviewable.io/reviews/batfish/batfish/8000#-MuxIk9G3iyK1D_W62vG:-Muxey4c18PLroFGsyk5:buzqia7) ([raw file](https://github.com/batfish/batfish/blob/bbe41a0a6f7bcbd05225f7bdab9f10a7e10161b5/projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/IpOwnersBaseImpl.java#L96)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Why implement equals and hashCode?

if we're going to be using hashCode, we should memoize it (and use it here?). Looks rather expensive.
</blockquote></details>

equals is for convergence check at end of dataplaning
hashCode - not really needed. Made it return 0 just to satisfy contract that a=b -> hash(a)=hash(b).
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/IpOwnersBaseImpl.java, line 125 at r1](https://reviewable.io/reviews/batfish/batfish/8000#-MuxJFte2BpP2zKVo7Dh:-MuxfACu7sOJeqsIiGCJ:bosxeqs) ([raw file](https://github.com/batfish/batfish/blob/bbe41a0a6f7bcbd05225f7bdab9f10a7e10161b5/projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/IpOwnersBaseImpl.java#L125)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Move this to the top of the class? Everything else is an internal implementation detail, right?

Add copious javadoc explaining why we need l3adjacencies and track? Enough that extenders/callers can know which to provide?
</blockquote></details>

moved and added more documentation.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/TrackMethodEvaluatorProvider.java, line 12 at r1](https://reviewable.io/reviews/batfish/batfish/8000#-MuxKUef47Rc3myxyO0s:-Muxha727y4obUFbOQC2:b-518clv) ([raw file](https://github.com/batfish/batfish/blob/bbe41a0a6f7bcbd05225f7bdab9f10a7e10161b5/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/TrackMethodEvaluatorProvider.java#L12)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

What is a `GenericTrackMethodVisitor`? I thought it was just called `TrackMethodVisitor`?
</blockquote></details>

Nope. Made a subinterface anyway to make it cleaner.
___
*[projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionCompatibilityAnswerer.java, line 141 at r1](https://reviewable.io/reviews/batfish/batfish/8000#-MuxKqwRBN8blPQ7doKR:-Muxhw8L3lugOXpC_Ssn:b-7rl0jd) ([raw file](https://github.com/batfish/batfish/blob/bbe41a0a6f7bcbd05225f7bdab9f10a7e10161b5/projects/question/src/main/java/org/batfish/question/bgpsessionstatus/BgpSessionCompatibilityAnswerer.java#L141)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

why is this not just using getInitialIpOwners?
</blockquote></details>

done.
___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/TracerouteEngineImpl.java, line 1 at r1](https://reviewable.io/reviews/batfish/batfish/8000#-MuxM2fB8G-opStIR0o3:-Muxa-1B9fvJJUtqz-r5:b-860uel) ([raw file](https://github.com/batfish/batfish/blob/bbe41a0a6f7bcbd05225f7bdab9f10a7e10161b5/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/TracerouteEngineImpl.java#L1)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Having a hard time seeing why this happened.
</blockquote></details>

multi-select drag mistake.
Fixed.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/StaticIpOwners.java, line 25 at r1](https://reviewable.io/reviews/batfish/batfish/8000#-MuxJYTh5RrfLd-h8O9G:-MuxgKUR7_aAkJAUC8IX:b-c6r6gz) ([raw file](https://github.com/batfish/batfish/blob/bbe41a0a6f7bcbd05225f7bdab9f10a7e10161b5/projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/StaticIpOwners.java#L25)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

`Static` doesn't seem like a descriptive name here -- more how it works rather than what it does/is. And confusion with things like static routes.

Do you mean something like "Initial", which would match things like L3Adjacencies and L3Topology, or "PreDataplane", which might be useful for questions?
</blockquote></details>

went with `PreDataPlaneIpOwners`
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/StaticIpOwners.java, line 25 at r1](https://reviewable.io/reviews/batfish/batfish/8000#-MuxK6yl2bUe7-Rasd9j:-MuxpQ1z2QNVtaJWinZs:bvqyjzq) ([raw file](https://github.com/batfish/batfish/blob/bbe41a0a6f7bcbd05225f7bdab9f10a7e10161b5/projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/StaticIpOwners.java#L25)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

This class shouldn't be public, should it? Still looks too easy to use wrong.
</blockquote></details>

done.
Definitely should look over what I did in tests. Not sure if it defeated the purpose. I don't see a great way around it.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/StaticIpOwners.java, line 27 at r1](https://reviewable.io/reviews/batfish/batfish/8000#-MuxJv3248uWF-FG-BvX:-MuxpbJo5Di_VQSN4Er_:b-d6a115) ([raw file](https://github.com/batfish/batfish/blob/bbe41a0a6f7bcbd05225f7bdab9f10a7e10161b5/projects/batfish-common-protocol/src/main/java/org/batfish/common/topology/StaticIpOwners.java#L27)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

It looks like the user can pass whatever L3Adjacencies they want here. What enforces that they use the initial L3 adjacencies?
</blockquote></details>

moot, since no longer public
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/StaticTrackMethodEvaluator.java, line 16 at r1](https://reviewable.io/reviews/batfish/batfish/8000#-MuxKHdy2E6sfF1hFNi3:-MuxyL2U1yio40E8Ytfz:b-hff6wv) ([raw file](https://github.com/batfish/batfish/blob/bbe41a0a6f7bcbd05225f7bdab9f10a7e10161b5/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/tracking/StaticTrackMethodEvaluator.java#L16)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Same comment on class name here. `Static` seems wrong...

Before this was only used for static routes, but now it's used for all kinds of things?
</blockquote></details>

renamed

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 36 files at r1, 10 of 33 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8000)* status: 20 of 43 files reviewed, 5 unresolved discussions (waiting on @arifogel, @corinaminer, and @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java, line 402 at r2](https://reviewable.io/reviews/batfish/batfish/8000#-Mv-XRkA54v8UrraajXl:-Mv-XRkA54v8UrraajXm:bhw6hld) ([raw file](https://github.com/batfish/batfish/blob/51dfa1e8314d459a01f81fd153109401dfc21e09/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java#L402)):*
> ```Java
>   }
> 
>   private static @Nonnull DataPlaneTrackMethodEvaluatorProvider nextTrackMethodEvaluatorProvider(
> ```

This looks pretty expensive. Can we identify up front which devices have tracks that are used in dataplane, and only do this for them?

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8000)* status: 20 of 43 files reviewed, 5 unresolved discussions (waiting on @arifogel, @corinaminer, and @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java, line 402 at r2](https://reviewable.io/reviews/batfish/batfish/8000#-Mv-XRkA54v8UrraajXl:-Mv-XrW_EOE8IUsfhJyH:b-2zwgi3) ([raw file](https://github.com/batfish/batfish/blob/51dfa1e8314d459a01f81fd153109401dfc21e09/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java#L402)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

This looks pretty expensive. Can we identify up front which devices have tracks that are used in dataplane, and only do this for them?
</blockquote></details>

Or in general, do this on-demand only.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8000)* status: 18 of 44 files reviewed, 5 unresolved discussions (waiting on @corinaminer and @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java, line 402 at r2](https://reviewable.io/reviews/batfish/batfish/8000#-Mv-XRkA54v8UrraajXl:-Mv0KdhV4oVbZcQnjKRj:b4860i9) ([raw file](https://github.com/batfish/batfish/blob/51dfa1e8314d459a01f81fd153109401dfc21e09/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalBdpEngine.java#L402)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Or in general, do this on-demand only.
</blockquote></details>

solved by pre-computing `TrackRoute`s here so we don't have to save the RIBs at all.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 22 of 33 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8000)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/DataplaneTrackEvaluator.java, line 38 at r3](https://reviewable.io/reviews/batfish/batfish/8000#-Mv4S1Zj3oNUGMRI-hal:-Mv4S1Zj3oNUGMRI-ham:undefined) ([raw file](https://github.com/batfish/batfish/blob/2d5cb9186e6d4331edf9d617385411b5d7f2bc34/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/DataplaneTrackEvaluator.java#L38)):*
> ```Java
> 
>   /**
>    * Create a provider for {@link DataplaneTrackEvaluator}s given a fixed dataplane and traceroute
> ```





_Suggestion:_
```Java
given pre-evaluated route presence tracks
```

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 36 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8000)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel and @corinaminer)

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8000)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/DataplaneTrackEvaluator.java, line 38 at r3](https://reviewable.io/reviews/batfish/batfish/8000#-Mv4S1Zj3oNUGMRI-hal:-Mv4r8hZCBZCYy1btWdQ:b-igvzz1) ([raw file](https://github.com/batfish/batfish/blob/2d5cb9186e6d4331edf9d617385411b5d7f2bc34/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/DataplaneTrackEvaluator.java#L38)):*
> ```Java
> 
>   /**
>    * Create a provider for {@link DataplaneTrackEvaluator}s given a fixed dataplane and traceroute
> ```

already fixed in a subsequent open PR, so merging as is.

**Pull request merged**
