### PR TITLE
Add option to return unique inputs for SRP

### PR DESCRIPTION
**Pull request by backesj**
This change creates a new option for SRP to create unique prefixes for each new Input route it suggests to cover a new term of a route map.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8741)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @backesj)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/8741#-NZagd-S0zvvtTTmFcLg:-NZagd-S0zvvtTTmFcLh:b-20cf09) (no related file):*
Took a quick pass to unblock progress, but happy to let @millstein or @ratulm do the real review if I disappear into a hole.

___
___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesAnswerer.java` line 93 at r1](https://reviewable.io/reviews/batfish/batfish/8741#-NZafMIk8zSYTfME5s60:-NZafMIk8zSYTfME5s61:undefined) ([raw file](https://github.com/batfish/batfish/blob/a825f58aa5da664e4fb1e0401dcb1018b77fd713/projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesAnswerer.java#L93)):*
> ```Java
>           this.row = row;
>       }
>   }
> ```





_Suggestion:_
```Java
  private static class RowAndRoute {
      public Bgpv4Route _route;
      public Row _row;
      
      public RowAndRoute(Bgpv4Route route, Row row) {
          this.route = route;
          this.row = row;
      }
  }
```
___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesQuestion.java` line 27 at r1](https://reviewable.io/reviews/batfish/batfish/8741#-NZafVPi5jlKmCt1WpTB:-NZafVPi5jlKmCt1WpTC:b-88wzyg) ([raw file](https://github.com/batfish/batfish/blob/a825f58aa5da664e4fb1e0401dcb1018b77fd713/projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesQuestion.java#L27)):*
> ```Java
>   private static final String PROP_ACTION = "action";
> 
>   private static final String PROP_PATH_OPTION = "pathOption";
> ```

I mean you're not wrong in spirit, but this is a breaking API change.

Cut to the "The only thing I have to do a senior engineer is ask 'shouldn't this boolean be an enum?'" meme.

Instead, add a new parameter and deprecate the old one, where the old one gets upconverted internally.
___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesQuestion.java` line 48 at r1](https://reviewable.io/reviews/batfish/batfish/8741#-NZagSgaEoIa8zJ1HqCc:-NZagSgaEoIa8zJ1HqCd:b7tggtp) ([raw file](https://github.com/batfish/batfish/blob/a825f58aa5da664e4fb1e0401dcb1018b77fd713/projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesQuestion.java#L48)):*
> ```Java
> 
>   // if set, the analysis is run separately on each execution path in the given route map
>   // SINGLE means we return a single path that meets the input and ouput constraints
> ```

put these on the enum value javadoc itself?
___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesQuestion.java` line 103 at r1](https://reviewable.io/reviews/batfish/batfish/8741#-NZagXiR8znZK93eB86y:-NZagXiR8znZK93eB86z:bec6smn) ([raw file](https://github.com/batfish/batfish/blob/a825f58aa5da664e4fb1e0401dcb1018b77fd713/projects/minesweeper/src/main/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesQuestion.java#L103)):*
> ```Java
>       @Nullable @JsonProperty(PROP_POLICIES) String policies,
>       @Nullable @JsonProperty(PROP_ACTION) Action action,
>       @JsonProperty(PROP_PATH_OPTION) PathOption pathOption) {
> ```

@Nullable (no guarantee in an API that users set them)

**Comment by backesj** [comment]
Submitting new request

**Comment by dhalperi** [comment]
FYI It's normal and helps review to just keep pushing to the same branch and keeping the same PR alive. If you need help with that, let me know?

**Comment by dhalperi** [comment]
Reclosing given new pr #8743

**Pull request closed without merging**
