### PR TITLE
Rest api roles

### PR DESCRIPTION
**Pull request by ratulm**
Things that changed:
1) Refactored WorkMgrServiceV2Test so that resource test could sit independently
2) ServiceObjectMapper class that should be registered in client and service code to get the right Jackson behavior
3) Reported NodeRole object to include the set of nodes to the client
4) Refactored code in WorkMgr a bit to support the above by moving similar code elsewherein helper functions (and tests for those functions)

### CODE REVIEW

**Comment by dhalperi** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrServiceV2.java, line 70 at r1](https://reviewable.io/reviews/batfish/batfish/1507#-LDRsBA2EQfLKIiwDWpX:-LDRsBA2EQfLKIiwDWpY:b-ho65uo) ([raw file](https://github.com/batfish/batfish/blob/24eefa464f09df8a1434ac319cf4ef76e7042aad/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrServiceV2.java#L70)):*
> ```Java
>   @Path("containers/{id}/noderoles")
>   public NodeRolesResource getNodeRolesResource(@PathParam("id") String id) {
>     return new NodeRolesResource(_uriInfo, _apiKey, id);
> ```

This is not the proper design -- if this is a container-relative resource, it should be recursively resolved by `ContainerResource`. You use the hierarchy of the REST API to make sure all paths through the tree go through the same resolution process in terms of access and checks.

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/resources/ContainerResource.java, line 40 at r1](https://reviewable.io/reviews/batfish/batfish/1507#-LDRs6EX-LN7aw0IQNYz:-LDRs3h4-rwhafT1ZUa4:bz9vjg5) ([raw file](https://github.com/batfish/batfish/blob/24eefa464f09df8a1434ac319cf4ef76e7042aad/projects/coordinator/src/main/java/org/batfish/coordinator/resources/ContainerResource.java#L40)):*
> ```Java
>   public Response getContainer() {
>     _logger.infof("WMS2: getContainer '%s'\n", _name);
>     checkAccessToContainer(_apiKey, _name);
> ```

If you resolve NodeRolesResource relative to this class, you won't need to expose checkAccessToContainer or to check access in NodeRolesResource or any other child.

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/resources/NodeRolesResource.java, line 16 at r1](https://reviewable.io/reviews/batfish/batfish/1507#-LDRsg0p4sQ21Z6HV-jm:-LDRsg0p4sQ21Z6HV-jn:b5fubzl) ([raw file](https://github.com/batfish/batfish/blob/24eefa464f09df8a1434ac319cf4ef76e7042aad/projects/coordinator/src/main/java/org/batfish/coordinator/resources/NodeRolesResource.java#L16)):*
> ```Java
>  * The {@link ContainerResource} is a resource for servicing client API calls at container level.
>  *
>  * <p>The ContainerResource provides information about a specified container, and provides the
> ```

javadoc

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1507)*

**Comment by dhalperi** [comment]
*[a discussion](https://reviewable.io/reviews/batfish/batfish/1507#-LDRsz3s54fKVE4GcLfl:-LDRsz3s54fKVE4GcLfm:bwhs257) (no related file):*
https://docs.oracle.com/javaee/7/tutorial/jaxrs-advanced003.htm is useful, I think. (Subresources)

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1507)*

**Comment by ratulm** [comment]
Review status: 2 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrServiceV2.java, line 70 at r1](https://reviewable.io/reviews/batfish/batfish/1507#-LDRsBA2EQfLKIiwDWpX:-LDSAbDw5gYomA6QmBpz:btqjr9k) ([raw file](https://github.com/batfish/batfish/blob/24eefa464f09df8a1434ac319cf4ef76e7042aad/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgrServiceV2.java#L70)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

This is not the proper design -- if this is a container-relative resource, it should be recursively resolved by `ContainerResource`. You use the hierarchy of the REST API to make sure all paths through the tree go through the same resolution process in terms of access and checks.
</blockquote></details>

this is nice. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1507)*

**Comment by ratulm** [comment]
Review status: 2 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/batfish/batfish/1507#-LDRsz3s54fKVE4GcLfl:-LDSC0DN-Q6zW7jbyxZP:blzoa0w) (no related file):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

https://docs.oracle.com/javaee/7/tutorial/jaxrs-advanced003.htm is useful, I think. (Subresources)
</blockquote></details>

man, these oracle docs are horrible for almost all things. one always needs Google to understand how to do things.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1507)*

**Comment by ratulm** [comment]
Review status: 2 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/resources/ContainerResource.java, line 40 at r1](https://reviewable.io/reviews/batfish/batfish/1507#-LDRs6EX-LN7aw0IQNYz:-LDSCC_p471qDhvzVxyT:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/24eefa464f09df8a1434ac319cf4ef76e7042aad/projects/coordinator/src/main/java/org/batfish/coordinator/resources/ContainerResource.java#L40)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

If you resolve NodeRolesResource relative to this class, you won't need to expose checkAccessToContainer or to check access in NodeRolesResource or any other child.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1507)*

**Comment by ratulm** [comment]
Review status: 2 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/resources/NodeRolesResource.java, line 16 at r1](https://reviewable.io/reviews/batfish/batfish/1507#-LDRsg0p4sQ21Z6HV-jm:-LDSCE8uEcJ-GsbyWXyG:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/24eefa464f09df8a1434ac319cf4ef76e7042aad/projects/coordinator/src/main/java/org/batfish/coordinator/resources/NodeRolesResource.java#L16)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

javadoc
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1507)*

**Comment by ratulm** [comment]
Review status: 4 of 17 files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/ServiceObjectMapper.java, line 9 at r2](https://reviewable.io/reviews/batfish/batfish/1507#-LDh5tpR5LJeB4qZO1gW:-LDhrzdJ2rKHbzbdjL1t:b-bzietw) ([raw file](https://github.com/batfish/batfish/blob/15e0867dbc93b87610c6a80986c4c58a8555ddef/projects/coordinator/src/main/java/org/batfish/coordinator/ServiceObjectMapper.java#L9)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

Yes and no on separation. Node roles test will not pass without this change (because of improper ser/deser of Instant field in NodeRolesData). 
</blockquote></details>

PS: I can pull it out if you have a strong preference for that. Things did get intertwined with other refactoring for modularity and consistent usage. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1507)*

**Comment by dhalperi** [comment]
Really nice changes all around, actually.

Let's talk tomorrow if there's stuff worth discussing re pushing node roles resource across finish line.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/role/NodeRole.java, line 31 at r2](https://reviewable.io/reviews/batfish/batfish/1507#-LDh5b5jEUqtNBq7CsEH:-LDjQmOG7CKHiXGBRCwM:b-u244nc) ([raw file](https://github.com/batfish/batfish/blob/15e0867dbc93b87610c6a80986c4c58a8555ddef/projects/batfish-common-protocol/src/main/java/org/batfish/role/NodeRole.java#L31)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

This is a bit funky and I wasn't sure the right way to handle it. 

The issue is that I wanted to return to client a list of nodes as well when they ask for roles; just returning role regexes may not be informative enough. 

This list is populated based on the nodes in the latest snapshot in the container. 
</blockquote></details>

I think the logic to include not just container-level definition of roles but also their expansion for the current snapshot probably goes in the API endpoint handler itself (aka, FooService), not in the data model.

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/ServiceObjectMapper.java, line 9 at r2](https://reviewable.io/reviews/batfish/batfish/1507#-LDh5tpR5LJeB4qZO1gW:-LDjR3nz7xZJrUb6NU0x:b-jof3up) ([raw file](https://github.com/batfish/batfish/blob/15e0867dbc93b87610c6a80986c4c58a8555ddef/projects/coordinator/src/main/java/org/batfish/coordinator/ServiceObjectMapper.java#L9)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

PS: I can pull it out if you have a strong preference for that. Things did get intertwined with other refactoring for modularity and consistent usage. 
</blockquote></details>

In general, makes review much easier if small changes that were made "on the way" are pulled out as separate PRs. Fine as-is.

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/resources/ContainerResource.java, line 58 at r3](https://reviewable.io/reviews/batfish/batfish/1507#-LDjSMLw3EuX7S9QNIyK:-LDjSMLw3EuX7S9QNIyL:bf4mtte) ([raw file](https://github.com/batfish/batfish/blob/5d8741799898e9da7f5bff36c58478aa5579ddbf/projects/coordinator/src/main/java/org/batfish/coordinator/resources/ContainerResource.java#L58)):*
> ```Java
> 
>   /** Check the container {@link #_name} exists and {@link #_apiKey} has accessibility to it. */
>   private void checkAccessToContainer() {
> ```

keep private?

---

*[projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrTestUtils.java, line 7 at r3](https://reviewable.io/reviews/batfish/batfish/1507#-LDjSrT5CtCoN1tCTD7H:-LDjSrT5CtCoN1tCTD7I:b-4m5mlz) ([raw file](https://github.com/batfish/batfish/blob/691de4e3f39381945b91f03fc69051cf9f5db621/projects/coordinator/src/test/java/org/batfish/coordinator/WorkMgrTestUtils.java#L7)):*
> ```Java
> import org.junit.rules.TemporaryFolder;
> 
> public class WorkMgrTestUtils {
> ```

final, private constructor for utility class.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1507#-:-LDjTFKQDmmeOXIkCndQ:b-6mmv88)*

**Comment by ratulm** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/role/NodeRole.java, line 31 at r2](https://reviewable.io/reviews/batfish/batfish/1507#-LDh5b5jEUqtNBq7CsEH:-LDmppn612YJyd9KnPGM:b-ce4i1i) ([raw file](https://github.com/batfish/batfish/blob/15e0867dbc93b87610c6a80986c4c58a8555ddef/projects/batfish-common-protocol/src/main/java/org/batfish/role/NodeRole.java#L31)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I think the logic to include not just container-level definition of roles but also their expansion for the current snapshot probably goes in the API endpoint handler itself (aka, FooService), not in the data model.
</blockquote></details>

Separate classes now.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1507)*

**Comment by dhalperi** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/util/BatfishObjectMapper.java, line 72 at r4](https://reviewable.io/reviews/batfish/batfish/1507#-LDyAlRA-f-C4LV5058-:-LDyAlRA-f-C4LV50580:b-z3p7y8) ([raw file](https://github.com/batfish/batfish/blob/4b14f482f2d80e32741fd8b9ade183846014f7dd/projects/batfish-common-protocol/src/main/java/org/batfish/common/util/BatfishObjectMapper.java#L72)):*
> ```
> Returns a {@link ObjectMapper} configured to Batfish JSON standards. It 
> ```

expand? differentiate from mapper? add link to this function from #mapper and vice-versa?

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/role/NodeRole.java, line 32 at r4](https://reviewable.io/reviews/batfish/batfish/1507#-LDyBT_g6k14GnieYYk9:-LDyBT_g6k14GnieYYkA:benkdcc) ([raw file](https://github.com/batfish/batfish/blob/4b14f482f2d80e32741fd8b9ade183846014f7dd/projects/batfish-common-protocol/src/main/java/org/batfish/role/NodeRole.java#L32)):*
> ```Java
>   @Override
>   public int compareTo(NodeRole o) {
>     return _name.compareTo(o._name);
> ```

need to compare against regex -- if a != b then a.compareTo(b) cannot be 0.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/role/NodeRole.java, line 37 at r4](https://reviewable.io/reviews/batfish/batfish/1507#-LDyBJ3qBNyug5vXGBhC:-LDyBJ3qBNyug5vXGBhD:bu0qtdt) ([raw file](https://github.com/batfish/batfish/blob/4b14f482f2d80e32741fd8b9ade183846014f7dd/projects/batfish-common-protocol/src/main/java/org/batfish/role/NodeRole.java#L37)):*
> ```
> o == null || 
> ```

this is redundant with the next clause -- delete?

 (I think IntelliJ warns about this, too?).

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1507)*

**Comment by dhalperi** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1507#-:-LE39za043FQ_-JJwMyj:bnfp4nl)*

**Pull request merged**
