### PR TITLE
FortiOS: zone rename

### PR DESCRIPTION
**Pull request by sfraint**
Add support for renaming zones.

### CODE REVIEW

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6739)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @corinaminer and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6739#-MVwUAa2EyVOL329mxhJ:-MVwUAa2EyVOL329mxhK:bemndpb) (no related file):*
After https://github.com/batfish/batfish/pull/6738

---

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6739)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @corinaminer)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6739#-MVwUAa2EyVOL329mxhJ:-MVx2h18EMkwGqWvNzbC:b-jegy4c) (no related file):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

After https://github.com/batfish/batfish/pull/6738
</blockquote></details>

that is merged now, ready for review

---

**Review by corinaminer — COMMENTED** [review]
> Reviewed 3 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6739)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @sfraint)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_zone.g4, line 7 at r2](https://reviewable.io/reviews/batfish/batfish/6739#-MVx6JbRDX5OMMNR4h2Q:-MVx6JbRDX5OMMNR4h2R:bffw9r3) ([raw file](https://github.com/batfish/batfish/blob/8ade464441aea897e5828cbffd67527cb0b151b2/projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_zone.g4#L7)):*
> ```ANTLR
> }
> 
> cs_zone: ZONE newline csz*;
> ```

how come this was working before?
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 856 at r2](https://reviewable.io/reviews/batfish/batfish/6739#-MVx378QDWfU2yJoQdRg:-MVx378QDWfU2yJoQdRh:b10qj1r) ([raw file](https://github.com/batfish/batfish/blob/8ade464441aea897e5828cbffd67527cb0b151b2/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L856)):*
> ```Java
>     Optional<String> newNameOpt = toString(ctx, ctx.new_name);
>     assert currentNameOpt.isPresent();
>     assert newNameOpt.isPresent();
> ```

how come we're sure of these assertions? couldn't both names be invalid (for current, only if it's referring to an undefined zone)?
___
*[projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java, line 1101 at r2](https://reviewable.io/reviews/batfish/batfish/6739#-MVx5pdf8dY52QtmVb79:-MVx5pdf8dY52QtmVb7A:bw9f4j) ([raw file](https://github.com/batfish/batfish/blob/8ade464441aea897e5828cbffd67527cb0b151b2/projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java#L1101)):*
> ```Java
>         ccae,
>         hasDefinedStructureWithDefinitionLines(
>             filename, FortiosStructureType.SERVICE_CUSTOM, "new_service2", contains(8, 9, 10, 71)));
> ```

kind of annoying that these line numbers have to get updated whenever the config changes, but i don't see a way around it. that said... should there be an assertion here about zone definition lines? :angel: :skull_and_crossbones:

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6739)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @corinaminer)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_zone.g4, line 7 at r2](https://reviewable.io/reviews/batfish/batfish/6739#-MVx6JbRDX5OMMNR4h2Q:-MVx7Xef9RCNe9yv5r1d:bnfia6n) ([raw file](https://github.com/batfish/batfish/blob/8ade464441aea897e5828cbffd67527cb0b151b2/projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_zone.g4#L7)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

how come this was working before?
</blockquote></details>

rename wasn't used anywhere until this PR
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 856 at r2](https://reviewable.io/reviews/batfish/batfish/6739#-MVx378QDWfU2yJoQdRg:-MVxElzY5FocjdntLhuf:b-4i44o8) ([raw file](https://github.com/batfish/batfish/blob/8ade464441aea897e5828cbffd67527cb0b151b2/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L856)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

how come we're sure of these assertions? couldn't both names be invalid (for current, only if it's referring to an undefined zone)?
</blockquote></details>

forgot to update this, fixed
___
*[projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java, line 1101 at r2](https://reviewable.io/reviews/batfish/batfish/6739#-MVx5pdf8dY52QtmVb79:-MVxEkgRExvfud6K8FQz:b-7tfmjp) ([raw file](https://github.com/batfish/batfish/blob/8ade464441aea897e5828cbffd67527cb0b151b2/projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java#L1101)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

kind of annoying that these line numbers have to get updated whenever the config changes, but i don't see a way around it. that said... should there be an assertion here about zone definition lines? :angel: :skull_and_crossbones: 
</blockquote></details>

added

**Review by corinaminer — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 6 files at r1, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6739#-:-MVxGFpj5ALhde217F3L:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_zone.g4, line 7 at r2](https://reviewable.io/reviews/batfish/batfish/6739#-MVx6JbRDX5OMMNR4h2Q:-MVxG1pm7MDoY-uwlxxr:b-w85pgg) ([raw file](https://github.com/batfish/batfish/blob/8ade464441aea897e5828cbffd67527cb0b151b2/projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_zone.g4#L7)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

rename wasn't used anywhere until this PR
</blockquote></details>

oh i get it.

**Comment by dhalperi** [comment]
___
*[projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java, line 1101 at r2](https://reviewable.io/reviews/batfish/batfish/6739#-MVx5pdf8dY52QtmVb79:-MVxGyux33OiJcGOsAjF:b-r743hz) ([raw file](https://github.com/batfish/batfish/blob/8ade464441aea897e5828cbffd67527cb0b151b2/projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java#L1101)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

added
</blockquote></details>

The way around it is do not keep adding to the same file for different structures...

**Pull request merged**
