### PR TITLE
Work queue mgmt

### PR DESCRIPTION
**Pull request by ratulm**
1/ Changes for getting testrig status
2/ Rejecting duplicate work

Unlike what we discussed, support multiple parallel workers (or clients not doing things in the right order) is not part of this PR; that will come as part of another PR; this one was getting too big and I wanted to push it out.

---
This change is [Reviewable](https://reviewable.io/reviews/batfish/batfish/731)

### CODE REVIEW

**Comment by corinaminer** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/util/WorkItemBuilder.java, line 121 at r1](https://reviewable.io:443/reviews/batfish/batfish/731#-L06LKgnq_uq9fsgb3BN:-L06LKgnq_uq9fsgb3BO:bwmj8r4) ([raw file](https://github.com/batfish/batfish/blob/345415b250b9f4f4677ca769bf04938759cdbbcb/projects/batfish-common-protocol/src/main/java/org/batfish/common/util/WorkItemBuilder.java#L121)):*
> ```Java
> 
>   public static boolean isDataplaningWorkItem(
>       WorkItem workItem, String container, String testrig, String envName) {
> ```

Why use this method rather than the one above? When is it necessary to confirm the other parameters? Should the first one be private? (same questions for `isParsingWorkItem`)

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/util/WorkItemBuilder.java, line 159 at r1](https://reviewable.io:443/reviews/batfish/batfish/731#-L06QBKcn8ofD3byhI-f:-L06QBKcn8ofD3byhI-g:b-g6oqzq) ([raw file](https://github.com/batfish/batfish/blob/345415b250b9f4f4677ca769bf04938759cdbbcb/projects/batfish-common-protocol/src/main/java/org/batfish/common/util/WorkItemBuilder.java#L159)):*
> ```Java
>     } else if (deltaTestrig == null && deltaEnvName != null) {
>       deltaTestrig = testrig;
>     }
> ```

These two if statements seem risky to me. The principle of "if one field of delta isn't filled in, set it to that field of the base by default" kind of makes sense, but what if the base's environment doesn't have a matching environment on delta, or vice versa? It seems like this method has no capacity to detect such an issue, and working with its output might produce confusing errors.

It would make more sense to me to return the actual values for the delta testrig, even if they're null, and let the calling function deal with that result as appropriate.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/util/WorkItemBuilder.java, line 186 at r1](https://reviewable.io:443/reviews/batfish/batfish/731#-L06K2dWTLRDz4Lx4lnf:-L06K2dWTLRDz4Lx4lng:brk0gm3) ([raw file](https://github.com/batfish/batfish/blob/345415b250b9f4f4677ca769bf04938759cdbbcb/projects/batfish-common-protocol/src/main/java/org/batfish/common/util/WorkItemBuilder.java#L186)):*
> ```Java
>     return settings.getSecond().getFirst();
>   }
> }
> ```

Could/should we make these methods less visible, to minimize the possibility of people getting information about a `WorkItem` that isn't theirs?

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EnvironmentMetadata.java, line 52 at r1](https://reviewable.io:443/reviews/batfish/batfish/731#-L06gaThneqKuw0uympL:-L06gaThneqKuw0uympM:bmv5cin) ([raw file](https://github.com/batfish/batfish/blob/345415b250b9f4f4677ca769bf04938759cdbbcb/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EnvironmentMetadata.java#L52)):*
> ```Java
>   public void updateStatus(ProcessingStatus status) {
>     _currentStatus = status;
>     _statusHistory.add("Status changed to " + status + " at " + Instant.now());
> ```

What will we use `statusHistory` for? Might be cleaner to store each update as a `Pair<ProcessingStatus, Instant>`, or a similar json object if pairs don't serialize well.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/TestrigMetadata.java, line 25 at r1](https://reviewable.io:443/reviews/batfish/batfish/731#-L06hsnWLpInwVaF_UK1:-L06hsnXrpjp8elw_oNg:b-qvbp1r) ([raw file](https://github.com/batfish/batfish/blob/345415b250b9f4f4677ca769bf04938759cdbbcb/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/TestrigMetadata.java#L25)):*
> ```Java
>       @JsonProperty(PROP_CREATIONTIMESTAMP) Instant creationTimestamp,
>       @JsonProperty(PROP_ENVIRONMENTS) Map<String, EnvironmentMetadata> environments) {
>     this._creationTimestamp = creationTimestamp;
> ```

unnecessary `this`

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, line 715 at r1](https://reviewable.io:443/reviews/batfish/batfish/731#-L06lI1BxVh-4aSPFXRL:-L06lI1BxVh-4aSPFXRM:bwpbuml) ([raw file](https://github.com/batfish/batfish/blob/345415b250b9f4f4677ca769bf04938759cdbbcb/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java#L715)):*
> ```Java
>         .resolve(BfConsts.RELPATH_TESTRIGS_DIR)
>         .resolve(testrig)
>         .resolve(BfConsts.RELPATH_METADATA_FILE);
> ```

I believe you can resolve all these as multiple parameters to `resolve` (as in `resolve(container, BfConsts.RELPATH_TESTRIGS_DIR, ...`)

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, line 862 at r1](https://reviewable.io:443/reviews/batfish/batfish/731#-L06lhDnSVllqgxjrUT5:-L06lhDnSVllqgxjrUT6:ba48zes) ([raw file](https://github.com/batfish/batfish/blob/345415b250b9f4f4677ca769bf04938759cdbbcb/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java#L862)):*
> ```Java
>           metadata, testrigDir.resolve(BfConsts.RELPATH_METADATA_FILE));
>     } catch (JsonProcessingException e) {
>       throw new BatfishException("Could not testrigMetadata", e);
> ```

`Could not write testrigMetadata`?

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkQueueMgr.java, line 189 at r1](https://reviewable.io:443/reviews/batfish/batfish/731#-L06nRiLWB-Ue4aU96Jn:-L06nRiLWB-Ue4aU96Jo:b-2s3j86) ([raw file](https://github.com/batfish/batfish/blob/345415b250b9f4f4677ca769bf04938759cdbbcb/projects/coordinator/src/main/java/org/batfish/coordinator/WorkQueueMgr.java#L189)):*
> ```Java
>         TestrigMetadataMgr.writeMetadata(trMetadata, wItem.getContainerName(), baseTestrig);
>       }
>       if (WorkItemBuilder.isDataplaningWorkItem(wItem)) {
> ```

This could be an `else if`

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkQueueMgr.java, line 288 at r1](https://reviewable.io:443/reviews/batfish/batfish/731#-L06rbPq0cAeaoTw8Wbi:-L06rbPq0cAeaoTw8Wbj:bc64r13) ([raw file](https://github.com/batfish/batfish/blob/345415b250b9f4f4677ca769bf04938759cdbbcb/projects/coordinator/src/main/java/org/batfish/coordinator/WorkQueueMgr.java#L288)):*
> ```Java
>                           + envMetadata.getProcessingStatus());
>                 }
>                 ProcessingStatus status = ProcessingStatus.PARSED;
> ```

No worries about whether parsing might have failed because the dataplaning work item would be blocked from the start in that case, right?

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkQueueMgr.java, line 312 at r1](https://reviewable.io:443/reviews/batfish/batfish/731#-L06qmaeGLhanw0itCZA:-L06qmaeGLhanw0itCZB:b-lawwwf) ([raw file](https://github.com/batfish/batfish/blob/345415b250b9f4f4677ca769bf04938759cdbbcb/projects/coordinator/src/main/java/org/batfish/coordinator/WorkQueueMgr.java#L312)):*
> ```Java
>     return _queueIncompleteWork.enque(work);
> 
>     //  prep for multi-worker support
> ```

Do we want to keep all this commented code?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/731)*

**Comment by corinaminer** [comment]
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/TestrigMetadata.java, line 37 at r1](https://reviewable.io:443/reviews/batfish/batfish/731#-L06sNA90picPH9v0NFU:-L06sNA90picPH9v0NFV:b7k172n) ([raw file](https://github.com/batfish/batfish/blob/345415b250b9f4f4677ca769bf04938759cdbbcb/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/TestrigMetadata.java#L37)):*
> ```Java
>   public void initializeEnvironment(String environment) {
>     _environments.put(
>         environment, new EnvironmentMetadata(ProcessingStatus.UNINITIALIZED, new LinkedList<>()));
> ```

Do we care about putting a creation timestamp in environment metadata? Also, will the metadata contain any information about the environment's blacklists/whitelists?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/731)*

**Comment by ratulm** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/util/WorkItemBuilder.java, line 121 at r1](https://reviewable.io:443/reviews/batfish/batfish/731#-L06LKgnq_uq9fsgb3BN:-L07MlPpzRYLhAeDUG9o:bkywgjt) ([raw file](https://github.com/batfish/batfish/blob/345415b250b9f4f4677ca769bf04938759cdbbcb/projects/batfish-common-protocol/src/main/java/org/batfish/common/util/WorkItemBuilder.java#L121)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Why use this method rather than the one above? When is it necessary to confirm the other parameters? Should the first one be private? (same questions for `isParsingWorkItem`)
</blockquote></details>

this function is gone in the PR i am about to submit. 

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/util/WorkItemBuilder.java, line 159 at r1](https://reviewable.io:443/reviews/batfish/batfish/731#-L06QBKcn8ofD3byhI-f:-L07N-pc1d7FcUPBskHx:b-kql0uf) ([raw file](https://github.com/batfish/batfish/blob/345415b250b9f4f4677ca769bf04938759cdbbcb/projects/batfish-common-protocol/src/main/java/org/batfish/common/util/WorkItemBuilder.java#L159)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

These two if statements seem risky to me. The principle of "if one field of delta isn't filled in, set it to that field of the base by default" kind of makes sense, but what if the base's environment doesn't have a matching environment on delta, or vice versa? It seems like this method has no capacity to detect such an issue, and working with its output might produce confusing errors.

It would make more sense to me to return the actual values for the delta testrig, even if they're null, and let the calling function deal with that result as appropriate.
</blockquote></details>

i was forcing the logic to be identical to what batfish uses. but made it safer.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/util/WorkItemBuilder.java, line 186 at r1](https://reviewable.io:443/reviews/batfish/batfish/731#-L06K2dWTLRDz4Lx4lnf:-L07RcxoQ34LpRGMKp13:bhmaals) ([raw file](https://github.com/batfish/batfish/blob/345415b250b9f4f4677ca769bf04938759cdbbcb/projects/batfish-common-protocol/src/main/java/org/batfish/common/util/WorkItemBuilder.java#L186)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Could/should we make these methods less visible, to minimize the possibility of people getting information about a `WorkItem` that isn't theirs?
</blockquote></details>

hmmm...i don't understand the threat here ....

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EnvironmentMetadata.java, line 52 at r1](https://reviewable.io:443/reviews/batfish/batfish/731#-L06gaThneqKuw0uympL:-L07RjFnrJwsVm0uAwmn:b-q9y8nr) ([raw file](https://github.com/batfish/batfish/blob/345415b250b9f4f4677ca769bf04938759cdbbcb/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/EnvironmentMetadata.java#L52)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

What will we use `statusHistory` for? Might be cleaner to store each update as a `Pair<ProcessingStatus, Instant>`, or a similar json object if pairs don't serialize well.
</blockquote></details>

i put it there mostly for debugging (manual consumption for now). we can make it more structured if needed. 

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/TestrigMetadata.java, line 25 at r1](https://reviewable.io:443/reviews/batfish/batfish/731#-L06hsnWLpInwVaF_UK1:-L07SCmLAgYXLocHfZnC:b-qssebl) ([raw file](https://github.com/batfish/batfish/blob/345415b250b9f4f4677ca769bf04938759cdbbcb/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/TestrigMetadata.java#L25)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

unnecessary `this`
</blockquote></details>

fixed.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/TestrigMetadata.java, line 37 at r1](https://reviewable.io:443/reviews/batfish/batfish/731#-L06sNA90picPH9v0NFU:-L07SFAUihzpWqZOUGE9:bds4l7f) ([raw file](https://github.com/batfish/batfish/blob/345415b250b9f4f4677ca769bf04938759cdbbcb/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/TestrigMetadata.java#L37)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Do we care about putting a creation timestamp in environment metadata? Also, will the metadata contain any information about the environment's blacklists/whitelists?
</blockquote></details>

again, we can enhance as and when needed. 

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, line 715 at r1](https://reviewable.io:443/reviews/batfish/batfish/731#-L06lI1BxVh-4aSPFXRL:-L07SRnkxzTV9QbYMQ4E:b-52kaoo) ([raw file](https://github.com/batfish/batfish/blob/345415b250b9f4f4677ca769bf04938759cdbbcb/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java#L715)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

I believe you can resolve all these as multiple parameters to `resolve` (as in `resolve(container, BfConsts.RELPATH_TESTRIGS_DIR, ...`)
</blockquote></details>

good point. leaving it for now. i will do another PR to clean up all of getdir functions and have them properly build on each other. 

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, line 862 at r1](https://reviewable.io:443/reviews/batfish/batfish/731#-L06lhDnSVllqgxjrUT5:-L07SkLbqpoSDZ1JbRMp:b-7ql1td) ([raw file](https://github.com/batfish/batfish/blob/345415b250b9f4f4677ca769bf04938759cdbbcb/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java#L862)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

`Could not write testrigMetadata`?
</blockquote></details>

fixed

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkQueueMgr.java, line 189 at r1](https://reviewable.io:443/reviews/batfish/batfish/731#-L06nRiLWB-Ue4aU96Jn:-L07SnmxwBT-cXg20SWn:b9cdvgz) ([raw file](https://github.com/batfish/batfish/blob/345415b250b9f4f4677ca769bf04938759cdbbcb/projects/coordinator/src/main/java/org/batfish/coordinator/WorkQueueMgr.java#L189)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

This could be an `else if`
</blockquote></details>

technically, a workitem could be both. anyway, went down a different path in the upcoming PR.

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkQueueMgr.java, line 288 at r1](https://reviewable.io:443/reviews/batfish/batfish/731#-L06rbPq0cAeaoTw8Wbi:-L07T4Pw-_prgAPGQ4en:bb7sa0c) ([raw file](https://github.com/batfish/batfish/blob/345415b250b9f4f4677ca769bf04938759cdbbcb/projects/coordinator/src/main/java/org/batfish/coordinator/WorkQueueMgr.java#L288)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

No worries about whether parsing might have failed because the dataplaning work item would be blocked from the start in that case, right?
</blockquote></details>

yes.

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkQueueMgr.java, line 312 at r1](https://reviewable.io:443/reviews/batfish/batfish/731#-L06qmaeGLhanw0itCZA:-L07T8eF3BTCbTjujgMh:b-91mghn) ([raw file](https://github.com/batfish/batfish/blob/345415b250b9f4f4677ca769bf04938759cdbbcb/projects/coordinator/src/main/java/org/batfish/coordinator/WorkQueueMgr.java#L312)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Do we want to keep all this commented code?
</blockquote></details>

removed in an upcoming PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/731)*

**Comment by corinaminer** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r2.
Review status: 12 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/util/WorkItemBuilder.java, line 186 at r1](https://reviewable.io:443/reviews/batfish/batfish/731#-L06K2dWTLRDz4Lx4lnf:-L07e0wmne5lspMV6f4T:bi1mvbc) ([raw file](https://github.com/batfish/batfish/blob/345415b250b9f4f4677ca769bf04938759cdbbcb/projects/batfish-common-protocol/src/main/java/org/batfish/common/util/WorkItemBuilder.java#L186)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

hmmm...i don't understand the threat here ....
</blockquote></details>

Probably not a concern, then. I guess if you already have a `WorkItem` that's not yours, you could find out all the same information without using these methods.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/731#-:-L07ejHAveI0MLFcG66z:bnfp4nl)*

**Comment by ratulm** [comment]
Closing this as its superseded by #741

**Pull request closed without merging**
