### PR TITLE
Support all vrfs if in trunk mode without explicit list

### PR DESCRIPTION
**Pull request by dhalperi**

### CODE REVIEW

**Comment by saparikh** [comment]
*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 1260 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1207#-LAQejTT6hzdEbcuxCko:-LARM9e3DttndPPevX0O:by4cj1z) ([raw file](https://github.com/batfish/batfish/blob/9a4643445450a0825d4d92485c90510a90f24ef7/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L1260)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

Keep a (different) warning? If we really get to this `else`, seems like something went wrong, let's not fail silently.
</blockquote></details>

I don't really know this code, but the logic looks correct.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1207)*

**Comment by saparikh** [comment]
:lgtm:

---







*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1207#-:-LARMsHuEOXan6CQ0mtq:bnfp4nl)*

**Comment by saparikh** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1207)*

**Comment by dhalperi** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 1260 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1207#-LAQejTT6hzdEbcuxCko:-LAU-7Q1DlZP6rYflqXj:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/9a4643445450a0825d4d92485c90510a90f24ef7/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L1260)):*
<details><summary><i>Previously, saparikh (Samir Parikh) wrote…</i></summary><blockquote>

I don't really know this code, but the logic looks correct.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1207)*

**Comment by progwriter** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1207)*

**Pull request merged**
