### PR TITLE
Reachability: always apply outgoing original-flow filter

### PR DESCRIPTION
**Pull request by anothermattbrown**
Previously we incorrectly skipped creating edges to NodeDropAclOut if there was no outgoing filter, even if there was an outgoing original-flow filter.

### CODE REVIEW

**Review by anothermattbrown — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6680)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @corinaminer)

___
*[projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactoryTest.java, line 1905 at r1](https://reviewable.io/reviews/batfish/batfish/6680#-MUtF8e2EqbK0xcZ8M9K:-MUtF8e2EqbK0xcZ8M9L:b-crxbsf) ([raw file](https://github.com/batfish/batfish/blob/670ebf998ff2f556761129a4ea4570979fe9d1e8/projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactoryTest.java#L1905)):*
> ```
> testOutgoingOriginalFlowFilterWithoutOutgoingFilter_arpFailure
> ```
this test worked before this PR, but was added for consistency of coverage

**Review by corinaminer — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6680)* status: all files reviewed, 3 unresolved discussions (waiting on @anothermattbrown)

___
*[projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactoryTest.java, line 1839 at r2](https://reviewable.io/reviews/batfish/batfish/6680#-MUtkJyo4KNv6fINiorx:-MUtkJyo4KNv6fINiory:b-h5sp04) ([raw file](https://github.com/batfish/batfish/blob/18ab04091b07b7ab3a391ca17038b01fd7a317fd/projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactoryTest.java#L1839)):*
> ```Java
>    */
>   @Test
>   public void testOutgoingOriginalFlowFilterWithoutOutgoingFilter_arpSuccess() throws IOException {
> ```

fyi: the comments in this test also apply to the other new test
___
*[projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactoryTest.java, line 1888 at r2](https://reviewable.io/reviews/batfish/batfish/6680#-MUtkM3L9kjQF0gNQfF-:-MUtkM3L9kjQF0gNQfF0:byr76df) ([raw file](https://github.com/batfish/batfish/blob/18ab04091b07b7ab3a391ca17038b01fd7a317fd/projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactoryTest.java#L1888)):*
> ```Java
>             .deniedByOriginalFlowEgressFilter(i1.getName());
>     BDD oneBdd = PKT.getFactory().one();
>     BDD zeroBdd = PKT.getFactory().zero();
> ```

(nonblocking) these are probably already available as static variables in this test
___
*[projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactoryTest.java, line 1900 at r2](https://reviewable.io/reviews/batfish/batfish/6680#-MUtkNLxCvx6XIhxXgYy:-MUtkNLxCvx6XIhxXgYz:b-twbebo) ([raw file](https://github.com/batfish/batfish/blob/18ab04091b07b7ab3a391ca17038b01fd7a317fd/projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactoryTest.java#L1900)):*
> ```Java
>     assertThat(
>         edges,
>         everyItem(
> ```

there should be exactly one edge in `edges`, right? Is there a reason not to test that by using `contains` instead of `everyItem`?
___
*[projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactoryTest.java, line 1905 at r2](https://reviewable.io/reviews/batfish/batfish/6680#-MUtkOc9AsDvIPkq4sRb:-MUtkOc9AsDvIPkq4sRc:bp523ze) ([raw file](https://github.com/batfish/batfish/blob/18ab04091b07b7ab3a391ca17038b01fd7a317fd/projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactoryTest.java#L1905)):*
> ```Java
>                 hasTransition(mapsForward(deniedBdd, oneBdd)),
>                 // no flow marked as permitted can traverse this edge
>                 hasTransition(mapsForward(permittedBdd, zeroBdd)))));
> ```

nit: could move the `allOf` into `hasTransition`, like
```
hasTransition(
  allOf(
    mapsForward(...),
    mapsForward(...)
  )
)
```

**Review by anothermattbrown — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6680)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @anothermattbrown and @corinaminer)

___
*[projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactoryTest.java, line 1900 at r2](https://reviewable.io/reviews/batfish/batfish/6680#-MUtkNLxCvx6XIhxXgYy:-MUtvK6Q2xdER6Erw-wY:be790fr) ([raw file](https://github.com/batfish/batfish/blob/18ab04091b07b7ab3a391ca17038b01fd7a317fd/projects/batfish/src/test/java/org/batfish/bddreachability/BDDReachabilityAnalysisFactoryTest.java#L1900)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

there should be exactly one edge in `edges`, right? Is there a reason not to test that by using `contains` instead of `everyItem`?
</blockquote></details>

yes, for the arpSuccess case (done). the arpFailure case has multiple edges

**Review by corinaminer — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6680#-:-MUtvvIg3LbJrMup0r7A:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
