### PR TITLE
Parsers: remove BLANK_LINE, inline in F_Newline

### PR DESCRIPTION
**Pull request by dhalperi**
The `BLANK_LINE` token is a huge performance bottleneck because it is only not
used at the end of every line due to semantic predicates, which prevents
lexer caching. We can fix this by inlining its definition inside of `F_Newline`:
instead of matching a single newline, it now matches any consecutive string of
newlines-and-blank-lines. This changes both the `NEWLINE` and `COMMENT_LINE` tokens,
as well as any other tokens that use `F_Newline`.

The only remaining problem is a newline at the start of the file. For this, we add
an optional `NEWLINE` token as the first line of a file.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6778)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @arifogel)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosLexer.g4, line 2529 at r1](https://reviewable.io/reviews/batfish/batfish/6778#-MWXv42X8QA8HUL-7E66:-MWXv42X8QA8HUL-7E67:bjutu3a) ([raw file](https://github.com/batfish/batfish/blob/ae12d260940310f14fe3cd8a8368e71911cf23cd/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_nxos/CiscoNxosLexer.g4#L2529)):*
> ```
> || lastTokenType() == -1}
> ```

FYI Only NX-OS and FortiOS also caught a blank line at start of file. Necessary? Vs adding a newline preamble to the configuration rule?

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6778)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @dhalperi)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6778#-MW_a7D52-7Yhb8qkRJW:-MW_a7D6D_TX6imMb2kA:b-gfzemr) (no related file):*
> In practice, BLANK_LINE does not need to match empty lines,
> because a truly empty line will be caught by the prior
> NEWLINE: F_Newline+;

This is not true when a newline is followed by a comment line and then another newline.
You will end up with:
`NEWLINE` (default channel) `COMMENT_LINE` (hidden channel) `NEWLINE` (default channel).

---

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6778)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @dhalperi)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6778#-MW_a7D52-7Yhb8qkRJW:-MW_ajSx8Lxc7blhb1TQ:b-ibtem2) (no related file):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

> In practice, BLANK_LINE does not need to match empty lines,
> because a truly empty line will be caught by the prior
> NEWLINE: F_Newline+;

This is not true when a newline is followed by a comment line and then another newline.
You will end up with:
`NEWLINE` (default channel) `COMMENT_LINE` (hidden channel) `NEWLINE` (default channel).
</blockquote></details>

That is, you will end up with that if sequence if you remove BLANK_LINE or require BLANK_LINE to start with whitespace

---

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6778)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @dhalperi)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6778#-MW_a7D52-7Yhb8qkRJW:-MW_i9OzAj1A0fW2cFMs:bxhz598) (no related file):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

That is, you will end up with that if sequence if you remove BLANK_LINE or require BLANK_LINE to start with whitespace
</blockquote></details>

As discussed offline, my concern is mistaken since COMMENT_LINE eats up newlines after it.

But we can remove BLANK_LINE altogether if both NEWLINE and COMMENT_LINE inline its definition at the end.

---

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6778)* status: 0 of 12 files reviewed, 1 unresolved discussion (waiting on @arifogel)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6778#-MW_a7D52-7Yhb8qkRJW:-MW_uaRZ7RJ3lwZaDHzS:b-6ps8x5) (no related file):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

As discussed offline, my concern is mistaken since COMMENT_LINE eats up newlines after it.

But we can remove BLANK_LINE altogether if both NEWLINE and COMMENT_LINE inline its definition at the end.
</blockquote></details>

I just inlined this in F_Newline, rather than in the tokens themselves. That's better, right? That way we don't have to update all modes.

---

**Comment by dhalperi** [comment]
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/FortiosLexer.g4, line 439 at r2](https://reviewable.io/reviews/batfish/batfish/6778#-MW_v46E8tvgiKPaYmgX:-MW_v46E8tvgiKPaYmgY:b-2j5moa) ([raw file](https://github.com/batfish/batfish/blob/ae12d260940310f14fe3cd8a8368e71911cf23cd/projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/FortiosLexer.g4#L439)):*
> ```
>  '\r'? '\n'
> ```
Wasn't sure why this one is uniquely different

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6778)* status: 0 of 12 files reviewed, 1 unresolved discussion (waiting on @arifogel)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXrLexer.g4, line 5710 at r2](https://reviewable.io/reviews/batfish/batfish/6778#-MW_wCEu8AjAatJEr6ch:-MW_wCEu8AjAatJEr6ci:b8ywrxj) ([raw file](https://github.com/batfish/batfish/blob/d8ddfe9d4cf1086daad81ea57c0a97ff510f009a/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXrLexer.g4#L5710)):*
> ```ANTLR
> /* Other Tokens */
> 
> MULTICONFIGPART
> ```

FYI XR parser already allows any number of newlines in the mix with statements.

**Review by arifogel — COMMENTED** [review]
> Reviewed 12 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6778)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6778#-MW_a7D52-7Yhb8qkRJW:-MWa4kcrDEKqRO1zay_m:b2nign6) (no related file):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I just inlined this in F_Newline, rather than in the tokens themselves. That's better, right? That way we don't have to update all modes.
</blockquote></details>

yes

---
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/arista/AristaLexer.g4, line 5096 at r2](https://reviewable.io/reviews/batfish/batfish/6778#-MWa5K-uCFK09CsM9e5H:-MWa5K-uCFK09CsM9e5I:b-hwf6d1) ([raw file](https://github.com/batfish/batfish/blob/d8ddfe9d4cf1086daad81ea57c0a97ff510f009a/projects/batfish/src/main/antlr4/org/batfish/grammar/arista/AristaLexer.g4#L5096)):*
> ```ANTLR
> ;
> 
> COMMENT_TAIL
> ```

FYI this turned out to be invalid in a lot of lexers. Out of scope, but we may need to audit these.

**Pull request merged**
