### PR TITLE
Tool to annotate configurations with silent syntax and warnings

### PR DESCRIPTION
**Pull request by arifogel**
- add tool to annotate configurations with comments above lines with:
  - silent syntax, e.g. `*_null` rules
  - partially unsupported syntax, i.e. TODOs
  - syntax errors

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 10 of 10 files at r1, 23 of 23 files at r2, 21 of 21 files at r3, 7 of 7 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6957)* status: all files reviewed, 19 unresolved discussions (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/main/Annotate.java, line 1 at r4](https://reviewable.io/reviews/batfish/batfish/6957#-MZECsDN9oyw23ROOQ7i:-MZECsDN9oyw23ROOQ7j:bq6w7hq) ([raw file](https://github.com/batfish/batfish/blob/998948391c91763c11112e0b756c2a699a96fb03/projects/batfish/src/main/java/org/batfish/main/Annotate.java#L1)):*
> ```Java
> package org.batfish.main;
> ```

can this go in its own package and module?
___
*[projects/batfish/src/main/java/org/batfish/main/Annotate.java, line 37 at r4](https://reviewable.io/reviews/batfish/batfish/6957#-MZECPRyCx74jJa5xB-s:-MZECPRyCx74jJa5xB-t:brndrgu) ([raw file](https://github.com/batfish/batfish/blob/998948391c91763c11112e0b756c2a699a96fb03/projects/batfish/src/main/java/org/batfish/main/Annotate.java#L37)):*
> ```Java
> import org.batfish.job.ParseVendorConfigurationJob;
> 
> public final class Annotate {
> ```

Javadoc?
___
*[projects/batfish/src/main/java/org/batfish/main/Annotate.java, line 37 at r4](https://reviewable.io/reviews/batfish/batfish/6957#-MZECmxl7NEUqtMHiiTN:-MZECmxl7NEUqtMHiiTO:b-8riymg) ([raw file](https://github.com/batfish/batfish/blob/998948391c91763c11112e0b756c2a699a96fb03/projects/batfish/src/main/java/org/batfish/main/Annotate.java#L37)):*
> ```Java
> import org.batfish.job.ParseVendorConfigurationJob;
> 
> public final class Annotate {
> ```

are params non null by default, or do we need to annotate the individual files?
___
*[projects/batfish/src/main/java/org/batfish/main/Annotate.java, line 57 at r4](https://reviewable.io/reviews/batfish/batfish/6957#-MZECzXyCB5AcT_Grwv6:-MZECzXyCB5AcT_Grwv7:b-gwj24n) ([raw file](https://github.com/batfish/batfish/blob/998948391c91763c11112e0b756c2a699a96fb03/projects/batfish/src/main/java/org/batfish/main/Annotate.java#L57)):*
> ```
>     Preprocess.main(new String[] {inputPath.toString(), outputPath.toString()});
>     // Overwrite output in-place
>     annotate(outputPath, outputPath, settings);
> ```

Figure out how to pass the data not on the filesystem.
___
*[projects/batfish/src/main/java/org/batfish/main/Annotate.java, line 60 at r4](https://reviewable.io/reviews/batfish/batfish/6957#-MZED6J8BDcKDGXveL7b:-MZED6J8BDcKDGXveL7c:bq8afp5) ([raw file](https://github.com/batfish/batfish/blob/998948391c91763c11112e0b756c2a699a96fb03/projects/batfish/src/main/java/org/batfish/main/Annotate.java#L60)):*
> ```Java
>   }
> 
>   private static void annotate(Path inputPath, Path outputPath, Settings settings)
> ```

comments
___
*[projects/batfish/src/main/java/org/batfish/main/Annotate.java, line 68 at r4](https://reviewable.io/reviews/batfish/batfish/6957#-MZED8kQ7bW2_wLLSh4Y:-MZED8kQ7bW2_wLLSh4Z:b-dcz2so) ([raw file](https://github.com/batfish/batfish/blob/998948391c91763c11112e0b756c2a699a96fb03/projects/batfish/src/main/java/org/batfish/main/Annotate.java#L68)):*
> ```
>     logger.info("\n*** COMPUTING OUTPUT FILES ***\n");
>     logger.resetTimer();
> ```

Ditch this, use log4j logging. No need to add new uses of BatfishLogger.
___
*[projects/batfish/src/main/java/org/batfish/main/Annotate.java, line 76 at r4](https://reviewable.io/reviews/batfish/batfish/6957#-MZECSxKED_PX9HVt3YZ:-MZECSxKED_PX9HVt3Y_:bgoiu4j) ([raw file](https://github.com/batfish/batfish/blob/998948391c91763c11112e0b756c2a699a96fb03/projects/batfish/src/main/java/org/batfish/main/Annotate.java#L76)):*
> ```Java
>       Warnings warnings = forLogger(logger);
>       String name = inputPath.relativize(inputFile).toString();
>       System.out.println("loop1 name: " + name);
> ```

Get rid of System.out.println stuff.
___
*[projects/batfish/src/main/java/org/batfish/main/Annotate.java, line 87 at r4](https://reviewable.io/reviews/batfish/batfish/6957#-MZECVt46ulv0kp9rkJF:-MZECVt46ulv0kp9rkJG:brarzfd) ([raw file](https://github.com/batfish/batfish/blob/998948391c91763c11112e0b756c2a699a96fb03/projects/batfish/src/main/java/org/batfish/main/Annotate.java#L87)):*
> ```Java
>               ImmutableMultimap.of(),
>               null));
>     }
> ```

Comments
___
*[projects/batfish/src/main/java/org/batfish/main/Annotate.java, line 160 at r4](https://reviewable.io/reviews/batfish/batfish/6957#-MZECd3AEluh-ds13aIa:-MZECd3AEluh-ds13aIb:bod3avq) ([raw file](https://github.com/batfish/batfish/blob/998948391c91763c11112e0b756c2a699a96fb03/projects/batfish/src/main/java/org/batfish/main/Annotate.java#L160)):*
> ```Java
>         return String.format("%s PARTIALLY UNSUPPORTED\n", commentHeader);
>       default:
>         return null;
> ```

Why not annotate with the actual warning?
___
*[projects/batfish/src/test/resources/org/batfish/main/testconfigs/annotate-hierarchical-after, line 7 at r4](https://reviewable.io/reviews/batfish/batfish/6957#-MZEDKF_1ke2BAvEK9kp:-MZEDKF_1ke2BAvEK9kq:bkoua77) ([raw file](https://github.com/batfish/batfish/blob/998948391c91763c11112e0b756c2a699a96fb03/projects/batfish/src/test/resources/org/batfish/main/testconfigs/annotate-hierarchical-after#L7)):*
> ```
> RTED
> ```
Why not include the text in this case?
___
*[projects/batfish/src/test/resources/org/batfish/main/testconfigs/annotate-hierarchical-after, line 8 at r4](https://reviewable.io/reviews/batfish/batfish/6957#-MZEDNR41STjzdQ80k0g:-MZEDNR41STjzdQ80k0h:b-rxv02y) ([raw file](https://github.com/batfish/batfish/blob/998948391c91763c11112e0b756c2a699a96fb03/projects/batfish/src/test/resources/org/batfish/main/testconfigs/annotate-hierarchical-after#L8)):*
> ```
> set protocols bgp traceoptions file update
> # PARTIALLY UNSUPPORTED
> set protocols isis interface ge-0/0/0.0 level 2 priority 65
> ```

Do we have an example where a line has two annotations?
___
*[projects/batfish/src/test/resources/org/batfish/main/testconfigs/preprocess-hierarchical-after, line 11 at r4](https://reviewable.io/reviews/batfish/batfish/6957#-MZEDVxPAFBxMc9sKwOb:-MZEDVxPAFBxMc9sKwOc:b-hay66i) ([raw file](https://github.com/batfish/batfish/blob/998948391c91763c11112e0b756c2a699a96fb03/projects/batfish/src/test/resources/org/batfish/main/testconfigs/preprocess-hierarchical-after#L11)):*
> ```
> set interfaces lo0 unit 1 family inet address 192.0.3.1/24
> set garbage line4
> set garbage line5 garbage line6
> ```

revert?
___
*[projects/batfish/src/test/resources/org/batfish/main/testconfigs/preprocess-hierarchical-before, line 32 at r4](https://reviewable.io/reviews/batfish/batfish/6957#-MZEDWUqBMZKADA2fBq9:-MZEDWUs29sk7STnBX8R:b-hay66i) ([raw file](https://github.com/batfish/batfish/blob/998948391c91763c11112e0b756c2a699a96fb03/projects/batfish/src/test/resources/org/batfish/main/testconfigs/preprocess-hierarchical-before#L32)):*
> ```
> garbage line5 {
>   garbage line6;
> }
> ```

revert?
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/ParseVendorConfigurationAnswerElement.java, line 41 at r1](https://reviewable.io/reviews/batfish/batfish/6957#-MZEBqMSDp8UcvXyMuGN:-MZEBqMSDp8UcvXyMuGO:bvr596h) ([raw file](https://github.com/batfish/batfish/blob/513482300fc2d36dac3936201b59130a9b5c83e0/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/ParseVendorConfigurationAnswerElement.java#L41)):*
> ```Java
>   private SortedMap<String, ParseTreeSentences> _parseTrees;
> 
>   private Map<String, SilentSyntax> _silentSyntax;
> ```

Javadoc.

If nothing else, what's the key?
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/ParseVendorConfigurationAnswerElement.java, line 41 at r5](https://reviewable.io/reviews/batfish/batfish/6957#-MZEDd00895fgBPXFgYn:-MZEDd01-sUA6b0Y8Ys7:bqx53hb) ([raw file](https://github.com/batfish/batfish/blob/500ec7b9317ba3ce015bc2445e29a4cdcb5a18ff/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/ParseVendorConfigurationAnswerElement.java#L41)):*
> ```Java
>   private SortedMap<String, ParseTreeSentences> _parseTrees;
> 
>   private transient Map<String, SilentSyntax> _silentSyntax;
> ```

if transient, `@Nullable`
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/grammar/SilentSyntax.java, line 12 at r1](https://reviewable.io/reviews/batfish/batfish/6957#-MZEB7zf2aGgJmVLEpEU:-MZEB7zf2aGgJmVLEpEV:btxej71) ([raw file](https://github.com/batfish/batfish/blob/513482300fc2d36dac3936201b59130a9b5c83e0/projects/batfish-common-protocol/src/main/java/org/batfish/grammar/SilentSyntax.java#L12)):*
> ```
> SilentSyntax
> ```
Seems like this needs a type or a verb somewhere? SilentSyntaxCollection?

Why is `Elem` not an inner class?

Can these be in their own package, and in their own Bazel package?
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/grammar/SilentSyntaxListener.java, line 7 at r1](https://reviewable.io/reviews/batfish/batfish/6957#-MZEAbnHA-lSl6MJSX--:-MZEAbnI4Uig-uO2_yzq:b-n4bpxt) ([raw file](https://github.com/batfish/batfish/blob/513482300fc2d36dac3936201b59130a9b5c83e0/projects/batfish-common-protocol/src/main/java/org/batfish/grammar/SilentSyntaxListener.java#L7)):*
> ```
> Interface providing common parse-tree listener utility methods with default implementations.
> ```
Copypasta? What does this mean in the context of Silent Syntax?
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/grammar/SilentSyntaxListener.java, line 40 at r1](https://reviewable.io/reviews/batfish/batfish/6957#-MZEAj2J0vKRcvniXO2b:-MZEAj2J0vKRcvniXO2c:bidi62m) ([raw file](https://github.com/batfish/batfish/blob/513482300fc2d36dac3936201b59130a9b5c83e0/projects/batfish-common-protocol/src/main/java/org/batfish/grammar/SilentSyntaxListener.java#L40)):*
> ```Java
>    */
>   default boolean isSilentSyntax(ParserRuleContext ctx) {
>     return getParser().getRuleName(ctx).endsWith("_null");
> ```

What about stuff that is not overridden? That is also silent syntax, right?
___
*[tools/BUILD, line 10 at r5](https://reviewable.io/reviews/batfish/batfish/6957#-MZEDoMr2gA6sfgv0mLD:-MZEDoMr2gA6sfgv0mLE:b-rlib38) ([raw file](https://github.com/batfish/batfish/blob/500ec7b9317ba3ce015bc2445e29a4cdcb5a18ff/tools/BUILD#L10)):*
> ```Starlark
>     runtime_deps = [
>         "//projects/allinone",
>         "@maven//:org_apache_logging_log4j_log4j_core",
> ```

missing log4j config in resources?

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6957)* status: 58 of 62 files reviewed, 14 unresolved discussions (waiting on @arifogel and @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/main/Annotate.java, line 37 at r4](https://reviewable.io/reviews/batfish/batfish/6957#-MZECPRyCx74jJa5xB-s:-MZEhuDX5HyfPhxmQeqi:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/998948391c91763c11112e0b756c2a699a96fb03/projects/batfish/src/main/java/org/batfish/main/Annotate.java#L37)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Javadoc?
</blockquote></details>

done
___
*[projects/batfish/src/main/java/org/batfish/main/Annotate.java, line 57 at r4](https://reviewable.io/reviews/batfish/batfish/6957#-MZECzXyCB5AcT_Grwv6:-MZF3-4ZCyWH88rpAuvZ:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/998948391c91763c11112e0b756c2a699a96fb03/projects/batfish/src/main/java/org/batfish/main/Annotate.java#L57)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
>     Preprocess.main(new String[] {inputPath.toString(), outputPath.toString()});
>     // Overwrite output in-place
>     annotate(outputPath, outputPath, settings);
> ```

Figure out how to pass the data not on the filesystem.
</blockquote></details>

done
___
*[projects/batfish/src/main/java/org/batfish/main/Annotate.java, line 68 at r4](https://reviewable.io/reviews/batfish/batfish/6957#-MZED8kQ7bW2_wLLSh4Y:-MZF32t43ltI_2hvug6-:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/998948391c91763c11112e0b756c2a699a96fb03/projects/batfish/src/main/java/org/batfish/main/Annotate.java#L68)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
>     logger.info("\n*** COMPUTING OUTPUT FILES ***\n");
>     logger.resetTimer();
> ```

Ditch this, use log4j logging. No need to add new uses of BatfishLogger.
</blockquote></details>

done
___
*[projects/batfish/src/main/java/org/batfish/main/Annotate.java, line 76 at r4](https://reviewable.io/reviews/batfish/batfish/6957#-MZECSxKED_PX9HVt3YZ:-MZF33_VCqSof-P2HFor:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/998948391c91763c11112e0b756c2a699a96fb03/projects/batfish/src/main/java/org/batfish/main/Annotate.java#L76)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Get rid of System.out.println stuff.
</blockquote></details>

done
___
*[projects/batfish/src/main/java/org/batfish/main/Annotate.java, line 160 at r4](https://reviewable.io/reviews/batfish/batfish/6957#-MZECd3AEluh-ds13aIa:-MZF3KnxBjMrNTdhiqkV:b-h21a8) ([raw file](https://github.com/batfish/batfish/blob/998948391c91763c11112e0b756c2a699a96fb03/projects/batfish/src/main/java/org/batfish/main/Annotate.java#L160)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Why not annotate with the actual warning?
</blockquote></details>

Done for partially unsupported, need to add annotation for other warnings.
___
*[projects/batfish/src/test/resources/org/batfish/main/testconfigs/annotate-hierarchical-after, line 7 at r4](https://reviewable.io/reviews/batfish/batfish/6957#-MZEDKF_1ke2BAvEK9kp:-MZF3Q8557Q5-JMpx8rF:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/998948391c91763c11112e0b756c2a699a96fb03/projects/batfish/src/test/resources/org/batfish/main/testconfigs/annotate-hierarchical-after#L7)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> RTED
> ```
Why not include the text in this case?
</blockquote></details>

done

**Review by dhalperi — COMMENTED** [review]
> Reviewed 4 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6957)* status: all files reviewed, 11 unresolved discussions (waiting on @arifogel)

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6957)* status: all files reviewed, 8 unresolved discussions (waiting on @arifogel and @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/main/Annotate.java, line 60 at r4](https://reviewable.io/reviews/batfish/batfish/6957#-MZED6J8BDcKDGXveL7b:-MZF4cLZ-CH8Hb4dNxcq:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/998948391c91763c11112e0b756c2a699a96fb03/projects/batfish/src/main/java/org/batfish/main/Annotate.java#L60)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

comments
</blockquote></details>

done
___
*[projects/batfish/src/main/java/org/batfish/main/Annotate.java, line 87 at r4](https://reviewable.io/reviews/batfish/batfish/6957#-MZECVt46ulv0kp9rkJF:-MZF4fpH9Y-bQ7CtfX7n:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/998948391c91763c11112e0b756c2a699a96fb03/projects/batfish/src/main/java/org/batfish/main/Annotate.java#L87)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Comments
</blockquote></details>

done
___
*[projects/batfish/src/main/java/org/batfish/main/Annotate.java, line 160 at r4](https://reviewable.io/reviews/batfish/batfish/6957#-MZECd3AEluh-ds13aIa:-MZF9PAQ7VPpqOPN7s3R:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/998948391c91763c11112e0b756c2a699a96fb03/projects/batfish/src/main/java/org/batfish/main/Annotate.java#L160)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Done for partially unsupported, need to add annotation for other warnings.
</blockquote></details>

done
___
*[projects/batfish/src/test/resources/org/batfish/main/testconfigs/annotate-hierarchical-after, line 8 at r4](https://reviewable.io/reviews/batfish/batfish/6957#-MZEDNR41STjzdQ80k0g:-MZF9QPg54874D7loSzO:b-85lp4z) ([raw file](https://github.com/batfish/batfish/blob/998948391c91763c11112e0b756c2a699a96fb03/projects/batfish/src/test/resources/org/batfish/main/testconfigs/annotate-hierarchical-after#L8)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Do we have an example where a line has two annotations?
</blockquote></details>

I have tried very hard to organically produce such an example, and failed after quite a while. Giving up for now.
___
*[projects/batfish/src/test/resources/org/batfish/main/testconfigs/preprocess-hierarchical-after, line 11 at r4](https://reviewable.io/reviews/batfish/batfish/6957#-MZEDVxPAFBxMc9sKwOb:-MZF9vSu4sPy7tp9M8hn:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/998948391c91763c11112e0b756c2a699a96fb03/projects/batfish/src/test/resources/org/batfish/main/testconfigs/preprocess-hierarchical-after#L11)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

revert?
</blockquote></details>

done
___
*[projects/batfish/src/test/resources/org/batfish/main/testconfigs/preprocess-hierarchical-before, line 32 at r4](https://reviewable.io/reviews/batfish/batfish/6957#-MZEDWUqBMZKADA2fBq9:-MZF9w906pGznnxSSkUg:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/998948391c91763c11112e0b756c2a699a96fb03/projects/batfish/src/test/resources/org/batfish/main/testconfigs/preprocess-hierarchical-before#L32)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

revert?
</blockquote></details>

done
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/ParseVendorConfigurationAnswerElement.java, line 41 at r1](https://reviewable.io/reviews/batfish/batfish/6957#-MZEBqMSDp8UcvXyMuGN:-MZFA8pt2MTfVRGaER6p:bt4fzqq) ([raw file](https://github.com/batfish/batfish/blob/513482300fc2d36dac3936201b59130a9b5c83e0/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/ParseVendorConfigurationAnswerElement.java#L41)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Javadoc.

If nothing else, what's the key?
</blockquote></details>

removed, so moot.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/ParseVendorConfigurationAnswerElement.java, line 41 at r5](https://reviewable.io/reviews/batfish/batfish/6957#-MZEDd00895fgBPXFgYn:-MZFAB3Y9-hsZzzqpCFk:bt4fzqq) ([raw file](https://github.com/batfish/batfish/blob/500ec7b9317ba3ce015bc2445e29a4cdcb5a18ff/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/answers/ParseVendorConfigurationAnswerElement.java#L41)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

if transient, `@Nullable`
</blockquote></details>

removed, so moot.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/grammar/SilentSyntax.java, line 12 at r1](https://reviewable.io/reviews/batfish/batfish/6957#-MZEB7zf2aGgJmVLEpEU:-MZFGM336l_mi6uz-Bym:b4ux7bf) ([raw file](https://github.com/batfish/batfish/blob/513482300fc2d36dac3936201b59130a9b5c83e0/projects/batfish-common-protocol/src/main/java/org/batfish/grammar/SilentSyntax.java#L12)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> SilentSyntax
> ```
Seems like this needs a type or a verb somewhere? SilentSyntaxCollection?

Why is `Elem` not an inner class?

Can these be in their own package, and in their own Bazel package?
</blockquote></details>

done except moving to own package
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/grammar/SilentSyntaxListener.java, line 7 at r1](https://reviewable.io/reviews/batfish/batfish/6957#-MZEAbnHA-lSl6MJSX--:-MZFGlpw4piVb_khmZY_:b-gsu0j0) ([raw file](https://github.com/batfish/batfish/blob/513482300fc2d36dac3936201b59130a9b5c83e0/projects/batfish-common-protocol/src/main/java/org/batfish/grammar/SilentSyntaxListener.java#L7)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> Interface providing common parse-tree listener utility methods with default implementations.
> ```
Copypasta? What does this mean in the context of Silent Syntax?
</blockquote></details>

oops. fixed.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/grammar/SilentSyntaxListener.java, line 40 at r1](https://reviewable.io/reviews/batfish/batfish/6957#-MZEAj2J0vKRcvniXO2b:-MZFGnhLEW0nmbevYXMK:b-8vlnkt) ([raw file](https://github.com/batfish/batfish/blob/513482300fc2d36dac3936201b59130a9b5c83e0/projects/batfish-common-protocol/src/main/java/org/batfish/grammar/SilentSyntaxListener.java#L40)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

What about stuff that is not overridden? That is also silent syntax, right?
</blockquote></details>

I'd prefer to address in follow-on PR. Non-overrides will be extremely noisy.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 10 of 10 files at r7, 50 of 51 files at r8, 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6957)* status: all files reviewed, 3 unresolved discussions (waiting on @arifogel)

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6957)* status: 5 of 67 files reviewed, 2 unresolved discussions (waiting on @arifogel and @dhalperi)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/grammar/SilentSyntax.java, line 12 at r1](https://reviewable.io/reviews/batfish/batfish/6957#-MZEB7zf2aGgJmVLEpEU:-MZFLEaj3VuHUgzh6aNk:bxog4wn) ([raw file](https://github.com/batfish/batfish/blob/513482300fc2d36dac3936201b59130a9b5c83e0/projects/batfish-common-protocol/src/main/java/org/batfish/grammar/SilentSyntax.java#L12)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

done except moving to own package
</blockquote></details>

Moved to own java package. They _can_ be put in their own bazel package, but they are depended on by a ton of other packages (every parser package). I'm not sure of the benefit here.
___
*[tools/BUILD, line 10 at r5](https://reviewable.io/reviews/batfish/batfish/6957#-MZEDoMr2gA6sfgv0mLD:-MZFQtcu7G9pho_LBwmt:b8k69mw) ([raw file](https://github.com/batfish/batfish/blob/500ec7b9317ba3ce015bc2445e29a4cdcb5a18ff/tools/BUILD#L10)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

missing log4j config in resources?
</blockquote></details>

that appears to be for tests. added runtime libs instead.
___
*[projects/batfish/src/main/java/org/batfish/main/Annotate.java, line 1 at r4](https://reviewable.io/reviews/batfish/batfish/6957#-MZECsDN9oyw23ROOQ7i:-MZFQy6Y23q472DE-rK9:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/998948391c91763c11112e0b756c2a699a96fb03/projects/batfish/src/main/java/org/batfish/main/Annotate.java#L1)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

can this go in its own package and module?
</blockquote></details>

done
___
*[projects/batfish/src/main/java/org/batfish/main/Annotate.java, line 37 at r4](https://reviewable.io/reviews/batfish/batfish/6957#-MZECmxl7NEUqtMHiiTN:-MZFRGJs205xKwSr8qHA:ba8gqm2) ([raw file](https://github.com/batfish/batfish/blob/998948391c91763c11112e0b756c2a699a96fb03/projects/batfish/src/main/java/org/batfish/main/Annotate.java#L37)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

are params non null by default, or do we need to annotate the individual files?
</blockquote></details>

added package-info

**Review by dhalperi — COMMENTED** [review]
> Reviewed 56 of 56 files at r10, 4 of 4 files at r11, 3 of 3 files at r12.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6957)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
