### PR TITLE
IOS-XR: refactor rp extraction to use listener functions

### PR DESCRIPTION
**Pull request by arifogel**
- remove recursive rp computation functions
  - change leaf functions to listener methods

### CODE REVIEW

**Review by corinaminer — COMMENTED** [review]
> Reviewed 6 of 7 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6988)* status: all files reviewed, 5 unresolved discussions (waiting on @arifogel and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6988#-M_7bAas6dPLpGUgb1zR:-M_7bAas6dPLpGUgb1zS:brh26o4) (no related file):*
Having the stacks makes me nervous about scenarios where the parser pops out of context in a routing policy. Have you tested that this plays well with ifs/else ifs that have a guard we don't parse? Would it make sense to assert that the stacks are empty when exiting a routing policy (or more cautiously, warn if they're not empty and clear them)?

---
___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java, line 2587 at r2](https://reviewable.io/reviews/batfish/batfish/6988#-M_7T24RBkhBi1iJhiTs:-M_7T24RBkhBi1iJhiTt:bo2nfuk) ([raw file](https://github.com/batfish/batfish/blob/b878390cccbf778696862f63dd17fb5916c17a00/projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java#L2587)):*
> always replace entire policy

You tested this in gns3?
___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java, line 8436 at r2](https://reviewable.io/reviews/batfish/batfish/6988#-M_7U9rbDjIiP_1z5Kog:-M_7U9rbDjIiP_1z5Koh:b-7udz3p) ([raw file](https://github.com/batfish/batfish/blob/b878390cccbf778696862f63dd17fb5916c17a00/projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java#L8436)):*
> ```Java
>     _statementCollectors.pop();
>     RoutePolicyElseIfBlock elseIf = _elseIfs.pop();
>     _ifs.peek().addElseIfBlock(elseIf);
> ```

why not just `_ifs.peek().addElseIfBlock(currentElseIf)` in the `enter` listener -- why is `_elseIfs` necessary?
___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java, line 8577 at r2](https://reviewable.io/reviews/batfish/batfish/6988#-M_7W1ddDB1_NVnUphzJ:-M_7W1ddDB1_NVnUphzK:b-7smxav) ([raw file](https://github.com/batfish/batfish/blob/bc50e958590bad0c0ddfec201ca90798c9e295a6/projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java#L8577)):*
> ```Java
>   }
> 
>   private RoutePolicyStatement toRoutePolicyStatement(Set_extcommunity_rp_stanzaContext ctx) {
> ```

is `exitSet_extcommunity_rp_stanza` missing from the new version?
___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java, line 8640 at r2](https://reviewable.io/reviews/batfish/batfish/6988#-M_7WtcBCFsuKOGHFIDH:-M_7WtcBCFsuKOGHFIDI:bapgmat) ([raw file](https://github.com/batfish/batfish/blob/b878390cccbf778696862f63dd17fb5916c17a00/projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java#L8640)):*
> ```Java
>       addStatement(new RoutePolicySetVarMetricType(t.RP_VARIABLE().getText()));
>     } else {
>       todo(ctx);
> ```

Is it possible to reach here? If all metric types are accounted for, the usual pattern is to make the last `else if` into an `else` with `assert t.RP_VARIABLE != null`.
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_xr/RoutePolicy.java, line 31 at r2](https://reviewable.io/reviews/batfish/batfish/6988#-M_7Z-MW37Sq55xjr229:-M_7Z-MX7r73FOv2CRz3:b-54qh97) ([raw file](https://github.com/batfish/batfish/blob/b878390cccbf778696862f63dd17fb5916c17a00/projects/batfish/src/main/java/org/batfish/representation/cisco_xr/RoutePolicy.java#L31)):*
> ```Java
>             .addAll(_statements)
>             .add(statement)
>             .build();
> ```

nit: I'd probably make `_statements` mutable and have `getStatements()` return an immutable copy. Same for the list fields in if/elseIf/else block classes -- just seems like the `add` methods are expected to be called more than the `get` methods.

**Review by corinaminer — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6988)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6988#-M_7bAas6dPLpGUgb1zR:-M_7ffqC16rsgz2odvqY:b-lguqxs) (no related file):*
> because every node in which they are altered can nest arbitrarily

You can't nest route policies, right? Why isn't it safe to check the other stacks upon entering/exiting a route policy?

---
___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java, line 2587 at r2](https://reviewable.io/reviews/batfish/batfish/6988#-M_7T24RBkhBi1iJhiTs:-M_7fXrg1VilmALC45QK:b-7j76d1) ([raw file](https://github.com/batfish/batfish/blob/b878390cccbf778696862f63dd17fb5916c17a00/projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java#L2587)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Yes. You get a big fat warning that you are overwriting the route-policy. Same goes for several other structures.
</blockquote></details>

sweet
___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java, line 8640 at r2](https://reviewable.io/reviews/batfish/batfish/6988#-M_7WtcBCFsuKOGHFIDH:-M_7glbaEXNV6tVzCpCN:bsq239h) ([raw file](https://github.com/batfish/batfish/blob/b878390cccbf778696862f63dd17fb5916c17a00/projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java#L8640)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

done, and now less crashy.
</blockquote></details>

wait so we don't want a `RoutePolicySetVarMetricType` statement?

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6988)* status: all files reviewed, 1 unresolved discussion (waiting on @corinaminer and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6988#-M_7bAas6dPLpGUgb1zR:-M_7nMeV2vaR0XiIkeZR:b-trrkgk) (no related file):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

> because every node in which they are altered can nest arbitrarily

You can't nest route policies, right? Why isn't it safe to check the other stacks upon entering/exiting a route policy?
</blockquote></details>

Right, done.
I was thinking of why we couldn't assert on e.g. entering/exiting an `if`.

---
___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java, line 8640 at r2](https://reviewable.io/reviews/batfish/batfish/6988#-M_7WtcBCFsuKOGHFIDH:-M_7nDKVC90tXsjnqFiv:bshdma4) ([raw file](https://github.com/batfish/batfish/blob/b878390cccbf778696862f63dd17fb5916c17a00/projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java#L8640)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

wait so we don't want a `RoutePolicySetVarMetricType` statement?
</blockquote></details>

It's not implemented, and won't be for a very long time. It converts to dead-end VI code that crashes on evaluation. Better to just warn and do nothing.

**Review by corinaminer — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6988#-:-M_7puwN1jSbzXQanUfS:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6988)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java, line 8640 at r2](https://reviewable.io/reviews/batfish/batfish/6988#-M_7WtcBCFsuKOGHFIDH:-M_7q0WO3JHx0dlP_VG4:beofink) ([raw file](https://github.com/batfish/batfish/blob/b878390cccbf778696862f63dd17fb5916c17a00/projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java#L8640)):*
> RoutePolicySetVarMetricType

should we actually delete this class then?

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6988)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java, line 8640 at r2](https://reviewable.io/reviews/batfish/batfish/6988#-M_7WtcBCFsuKOGHFIDH:-M_7rF8SE5snYGYjchCR:b4w4skv) ([raw file](https://github.com/batfish/batfish/blob/b878390cccbf778696862f63dd17fb5916c17a00/projects/batfish/src/main/java/org/batfish/grammar/cisco_xr/CiscoXrControlPlaneExtractor.java#L8640)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

> RoutePolicySetVarMetricType

should we actually delete this class then?
</blockquote></details>

There are lots of VI statements and exprs that should just be deleted. I'd rather do that in a separate cleanup PR.

**Pull request merged**
