### PR TITLE
DHCP matchers for Interface

### PR DESCRIPTION
**Pull request by ratulm**

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7858)* status: all files reviewed, 2 unresolved discussions (waiting on @ratulm)

___
*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/InterfaceMatchers.java, line 243 at r1](https://reviewable.io/reviews/batfish/batfish/7858#-MrUjc025Ra8JxklsCOn:-MrUjc025Ra8JxklsCOo:b-6kxnhn) ([raw file](https://github.com/batfish/batfish/blob/58e4a7c5704fc92b1bd701bfed374afbac0ad37f/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/InterfaceMatchers.java#L243)):*
> ```Java
> 
>   /**
>    * Provides a matcher that matches if the interface's channelGroupMembers are matched by the
> ```

copy-paste error: `channelGroupMembers`
___
*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/InterfaceMatchersImpl.java, line 173 at r1](https://reviewable.io/reviews/batfish/batfish/7858#-MrUjk1kAzPmlwE96v9-:-MrUjk1kAzPmlwE96v90:bybwtxf) ([raw file](https://github.com/batfish/batfish/blob/58e4a7c5704fc92b1bd701bfed374afbac0ad37f/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/InterfaceMatchersImpl.java#L173)):*
> ```Java
>   static final class HasDhcpRelayAddresses extends FeatureMatcher<Interface, List<Ip>> {
>     HasDhcpRelayAddresses(@Nonnull Matcher<? super List<Ip>> subMatcher) {
>       super(subMatcher, "An Interface with dhcpRelayAddress", "dhcpRelayAddresses");
> ```

`dhcpRelayAddress` should be plural

**Review by ratulm — COMMENTED** [review]
> Dismissed @arifogel from a discussion.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7858)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @arifogel)

___
*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/InterfaceMatchers.java, line 243 at r1](https://reviewable.io/reviews/batfish/batfish/7858#-MrUjc025Ra8JxklsCOn:-MrUmDkA9uRFfmtAJiCX:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/58e4a7c5704fc92b1bd701bfed374afbac0ad37f/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/matchers/InterfaceMatchers.java#L243)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

copy-paste error: `channelGroupMembers`
</blockquote></details>

Done.

**Review by ratulm — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7858)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @ratulm)

**Review by ratulm — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7858)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ratulm)

**Pull request merged**
