### PR TITLE
IOS fix aggregate-address implementation

### PR DESCRIPTION
**Pull request by arifogel**
- update parsing and vendor model for aggregate-address
- use BGP process-level aggregates instead of vrf-level following batfish/batfish#7067
- fixes batfish/batfish#6064

### CODE REVIEW

**Review by corinaminer — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, 3 of 9 files at r2, 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7075)* status: 13 of 19 files reviewed, 2 unresolved discussions (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 3718 at r4](https://reviewable.io/reviews/batfish/batfish/7075#-McR5IqC3IykDzbi75v9:-McR5IqC3IykDzbi75vA:b-lrktc) ([raw file](https://github.com/batfish/batfish/blob/87f5522824c1d377b70009a85424d92222b03a11/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L3718)):*
> ```Java
>     // Intentional identity comparison
>     if (_currentPeerGroup == proc.getMasterBgpPeerGroup()) {
>       if (ctx.network != null || ctx.prefix != null) {
> ```

nit: might be cleaner to check `if _currentIpv4Aggregate != null` and then `else { assert _currentIpv6Aggregate != null; ... }`
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco/BgpAggregateIpv4Network.java, line 12 at r4](https://reviewable.io/reviews/batfish/batfish/7075#-McR7m6c9WG9khb_r3Kn:-McR7m6c9WG9khb_r3Ko:b-xinnfb) ([raw file](https://github.com/batfish/batfish/blob/87f5522824c1d377b70009a85424d92222b03a11/projects/batfish/src/main/java/org/batfish/representation/cisco/BgpAggregateIpv4Network.java#L12)):*
> ```Java
> 
> @ParametersAreNonnullByDefault
> public class BgpAggregateIpv4Network extends BgpAggregateNetwork {
> ```

Shouldn't there be analogous changes in `BgpAggregateIpv6Network`?
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco/BgpAggregateIpv4Network.java, line 56 at r4](https://reviewable.io/reviews/batfish/batfish/7075#-McR88P3EiIuMmqdARJ6:-McR88P3EiIuMmqdARJ7:bdjqkar) ([raw file](https://github.com/batfish/batfish/blob/87f5522824c1d377b70009a85424d92222b03a11/projects/batfish/src/main/java/org/batfish/representation/cisco/BgpAggregateIpv4Network.java#L56)):*
> ```Java
> 
>   @Override
>   public String toString() {
> ```

not really sure why you generate these in the first place, but should `omitNullValues` if you do

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7075)* status: 11 of 19 files reviewed, 1 unresolved discussion (waiting on @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 3718 at r4](https://reviewable.io/reviews/batfish/batfish/7075#-McR5IqC3IykDzbi75v9:-McRCEPi-_ASOi1eztp4:b-ruo41u) ([raw file](https://github.com/batfish/batfish/blob/87f5522824c1d377b70009a85424d92222b03a11/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L3718)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

nit: might be cleaner to check `if _currentIpv4Aggregate != null` and then `else { assert _currentIpv6Aggregate != null; ... }`
</blockquote></details>

right, this code was just moved.
done.
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco/BgpAggregateIpv4Network.java, line 12 at r4](https://reviewable.io/reviews/batfish/batfish/7075#-McR7m6c9WG9khb_r3Kn:-McRC_AO6hvBEBaOF6o0:b-vlif0o) ([raw file](https://github.com/batfish/batfish/blob/87f5522824c1d377b70009a85424d92222b03a11/projects/batfish/src/main/java/org/batfish/representation/cisco/BgpAggregateIpv4Network.java#L12)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Shouldn't there be analogous changes in `BgpAggregateIpv6Network`?
</blockquote></details>

Done, but probably a waste of time until we implement IPv6 in 2050.
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco/BgpAggregateIpv4Network.java, line 56 at r4](https://reviewable.io/reviews/batfish/batfish/7075#-McR88P3EiIuMmqdARJ6:-McRCPGA1rctQ6jQQ7gF:bo21iiv) ([raw file](https://github.com/batfish/batfish/blob/87f5522824c1d377b70009a85424d92222b03a11/projects/batfish/src/main/java/org/batfish/representation/cisco/BgpAggregateIpv4Network.java#L56)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

not really sure why you generate these in the first place, but should `omitNullValues` if you do
</blockquote></details>

Because a test failed and I couldn't read the output, of course.
Done.

**Review by corinaminer — COMMENTED** [review]
> Reviewed 5 of 9 files at r2, 1 of 1 files at r4, 1 of 2 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7075)* status: all files reviewed, 3 unresolved discussions (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/representation/cisco/BgpAggregateIpv4Network.java, line 12 at r4](https://reviewable.io/reviews/batfish/batfish/7075#-McR7m6c9WG9khb_r3Kn:-McRc2p513d_S5dtsQ_4:b-i0dhwy) ([raw file](https://github.com/batfish/batfish/blob/87f5522824c1d377b70009a85424d92222b03a11/projects/batfish/src/main/java/org/batfish/representation/cisco/BgpAggregateIpv4Network.java#L12)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Done, but probably a waste of time until we implement IPv6 in 2050.
</blockquote></details>

yeahh i hear that, but too freaky to write baseEquals/baseHashcode and then not use them in all child classes
___
*[projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java, line 6026 at r4](https://reviewable.io/reviews/batfish/batfish/7075#-McRIQq09TGs4_G53D-o:-McRIQq09TGs4_G53D-p:bhtfocv) ([raw file](https://github.com/batfish/batfish/blob/87f5522824c1d377b70009a85424d92222b03a11/projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java#L6026)):*
> ```Java
>     assertThat(
>         aggs,
>         hasEntry(
> ```

nit: you don't need all the `equalTo`s; `hasEntry(Object, Object)` exists
___
*[projects/batfish/src/test/resources/org/batfish/grammar/cisco/testrigs/bgp-agg-learned-contributors/configs/c1, line 9 at r4](https://reviewable.io/reviews/batfish/batfish/7075#-McRXW4K24q_6o6M4lb1:-McRXW4K24q_6o6M4lb2:b-jmepyd) ([raw file](https://github.com/batfish/batfish/blob/87f5522824c1d377b70009a85424d92222b03a11/projects/batfish/src/test/resources/org/batfish/grammar/cisco/testrigs/bgp-agg-learned-contributors/configs/c1#L9)):*
> ```
> !
> ! Next hop for static routes
> interface GigabitEthernet0/1
> ```

unused
___
*[projects/batfish/src/test/resources/org/batfish/grammar/cisco/testrigs/bgp-agg-learned-contributors/configs/c1, line 23 at r4](https://reviewable.io/reviews/batfish/batfish/7075#-McRXfbw4ZTRdSn127ZA:-McRXfbx-Pz0nRAtsXnV:bsr30y7) ([raw file](https://github.com/batfish/batfish/blob/87f5522824c1d377b70009a85424d92222b03a11/projects/batfish/src/test/resources/org/batfish/grammar/cisco/testrigs/bgp-agg-learned-contributors/configs/c1#L23)):*
> ```
>   neighbor 10.10.10.2 activate
>   neighbor 10.10.10.2 route-map ALLOW-ALL in
>   neighbor 10.10.10.2 route-map ALLOW-ALL out
> ```

Unlike XR, the IOS default is to allow all when no route-map is configured, so you could drop the route-maps.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7075)* status: 19 of 20 files reviewed, 3 unresolved discussions (waiting on @corinaminer)

___
*[projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java, line 6026 at r4](https://reviewable.io/reviews/batfish/batfish/7075#-McRIQq09TGs4_G53D-o:-McRgwn4BPX8r-EUADX_:bwfa8r6) ([raw file](https://github.com/batfish/batfish/blob/87f5522824c1d377b70009a85424d92222b03a11/projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java#L6026)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

nit: you don't need all the `equalTo`s; `hasEntry(Object, Object)` exists
</blockquote></details>

`hasEntry(Object, Object)` uses reference equality IIRC, unfortunately. So it's not always safe.
___
*[projects/batfish/src/test/resources/org/batfish/grammar/cisco/testrigs/bgp-agg-learned-contributors/configs/c1, line 9 at r4](https://reviewable.io/reviews/batfish/batfish/7075#-McRXW4K24q_6o6M4lb1:-McRhm105k40hJ0zpE9U:ba3dfob) ([raw file](https://github.com/batfish/batfish/blob/87f5522824c1d377b70009a85424d92222b03a11/projects/batfish/src/test/resources/org/batfish/grammar/cisco/testrigs/bgp-agg-learned-contributors/configs/c1#L9)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

unused
</blockquote></details>

Removed
___
*[projects/batfish/src/test/resources/org/batfish/grammar/cisco/testrigs/bgp-agg-learned-contributors/configs/c1, line 23 at r4](https://reviewable.io/reviews/batfish/batfish/7075#-McRXfbw4ZTRdSn127ZA:-McRhT-O9cncwbQMALt5:bsmxqt6) ([raw file](https://github.com/batfish/batfish/blob/87f5522824c1d377b70009a85424d92222b03a11/projects/batfish/src/test/resources/org/batfish/grammar/cisco/testrigs/bgp-agg-learned-contributors/configs/c1#L23)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Unlike XR, the IOS default is to allow all when no route-map is configured, so you could drop the route-maps.
</blockquote></details>

Doesn't it depend on eBGP/iBGP? Regardless, just gonna leave it for now, since it reduces uncertainty for the reader.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7075)* status: 19 of 20 files reviewed, 3 unresolved discussions (waiting on @corinaminer)

___
*[projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java, line 6026 at r4](https://reviewable.io/reviews/batfish/batfish/7075#-McRIQq09TGs4_G53D-o:-McRiBqmDMXSw4a8CJbi:b3tv5jo) ([raw file](https://github.com/batfish/batfish/blob/87f5522824c1d377b70009a85424d92222b03a11/projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java#L6026)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

`hasEntry(Object, Object)` uses reference equality IIRC, unfortunately. So it's not always safe.
</blockquote></details>

Or maybe it was that if one arg is a `Matcher`, it checks if the other arg is equal to the `Matcher` arg. Regardless, this is fail-safe, so leaving it.

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7075)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7075)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[projects/batfish/src/test/resources/org/batfish/grammar/cisco/testrigs/bgp-agg-learned-contributors/configs/c1, line 23 at r4](https://reviewable.io/reviews/batfish/batfish/7075#-McRXfbw4ZTRdSn127ZA:-McV-QKf7TMUw104NEtu:bjr8k0k) ([raw file](https://github.com/batfish/batfish/blob/87f5522824c1d377b70009a85424d92222b03a11/projects/batfish/src/test/resources/org/batfish/grammar/cisco/testrigs/bgp-agg-learned-contributors/configs/c1#L23)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Doesn't it depend on eBGP/iBGP? Regardless, just gonna leave it for now, since it reduces uncertainty for the reader.
</blockquote></details>

:+1: just to follow up: XR depends EBGP/IBGP (denies if no route-map in EBGP, permits if no route-map in IBGP); IOS permits in both cases.

**Pull request merged**
