### PR TITLE
IpAccessList cleanup

### PR DESCRIPTION
**Pull request by arifogel**
- Add traceroute support for new IpAccessListLine match exprs
- make IpAccessListLine immutable
- IpAccessListLine is no longer subclass of HeaderSpace
- update IpAccessList and IpAccessListLine to use new match API

### CODE REVIEW

**Comment by sfraint** [comment]
Reviewed 34 of 58 files at r1, 21 of 37 files at r3, 18 of 19 files at r4.
Review status: 67 of 71 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1142)*

**Comment by sfraint** [comment]
Reviewed 2 of 58 files at r1, 1 of 37 files at r3, 1 of 19 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1142)*

**Comment by anothermattbrown** [comment]
Reviewed 8 of 58 files at r1, 16 of 37 files at r3, 1 of 19 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpAccessList.java, line 111 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1142#-L9kWkSA173VGXB6euLb:-L9kWkSBCJtgP_yhJEWS:b-1fl21q) ([raw file](https://github.com/batfish/batfish/blob/0c8b89d3652011e7fda2ba3e7fcc960c7e6be8c3/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpAccessList.java#L111)):*
> ```Java
>     for (int i = 0; i < _lines.size(); i++) {
>       IpAccessListLine line = _lines.get(i);
>       if (Evaluator.matches(line.getMatchCondition(), flow, srcInterface, availableAcls)) {
> ```

Can we construct one `Evaluator` here and use `line.getMatchCondition().accept()` rather than creating a new `Evaluator` for each line?

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpAccessListLine.java, line 82 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1142#-L9kXI_BA15m1BB8bo13:-L9kXI_BA15m1BB8bo14:brj3bg7) ([raw file](https://github.com/batfish/batfish/blob/0c8b89d3652011e7fda2ba3e7fcc960c7e6be8c3/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpAccessListLine.java#L82)):*
> ```Java
>     }
>     IpAccessListLine other = (IpAccessListLine) obj;
>     return Objects.equals(_action, other._action)
> ```

Why not `_action == other._action`?

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclLineMatchExpr.java, line 28 at r3](https://beta.reviewable.io/reviews/batfish/batfish/1142#-L9ku2lz2PZYrmKuIatU:-L9ku2lz2PZYrmKuIatV:bey3rac) ([raw file](https://github.com/batfish/batfish/blob/5038b6c87f0b894a52a0132cc796849b5dd0947d/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclLineMatchExpr.java#L28)):*
> ```Java
> 
>   @Override
>   public boolean equals(Object o) {
> ```

should we change this to `return compareTo(o) == 0`? or is there an efficiency concern?

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/OrMatchExpr.java, line 15 at r3](https://beta.reviewable.io/reviews/batfish/batfish/1142#-L9kutiY8cBceUsKSYCe:-L9kutiY8cBceUsKSYCf:b9u06q1) ([raw file](https://github.com/batfish/batfish/blob/5038b6c87f0b894a52a0132cc796849b5dd0947d/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/OrMatchExpr.java#L15)):*
> ```Java
>   private static final long serialVersionUID = 1L;
> 
>   private final Set<AclLineMatchExpr> _disjuncts;
> ```

`SortedSet`?

---

*[projects/batfish/src/main/java/org/batfish/bdp/BdpEngine.java, line 75 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1142#-L9kXshe0oxY6XuGlFEZ:-L9kXshe0oxY6XuGlFE_:bys6t1h) ([raw file](https://github.com/batfish/batfish/blob/0c8b89d3652011e7fda2ba3e7fcc960c7e6be8c3/projects/batfish/src/main/java/org/batfish/bdp/BdpEngine.java#L75)):*
> ```Java
>   static Flow applySourceNat(
>       Flow flow,
>       String srcInterface,
> ```

Looks like this should be `@Nullable`

---

*[projects/batfish/src/main/java/org/batfish/bdp/BdpEngine.java, line 157 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1142#-L9kXpZc1WV-pAAPF83h:-L9kXpZc1WV-pAAPF83i:bjlrml2) ([raw file](https://github.com/batfish/batfish/blob/0c8b89d3652011e7fda2ba3e7fcc960c7e6be8c3/projects/batfish/src/main/java/org/batfish/bdp/BdpEngine.java#L157)):*
> ```Java
>       Map<String, IpAccessList> aclDefinitions = currentNode._c.getIpAccessLists();
>       String vrfName;
>       String receivingInterface;
> ```

rename `srcInterface` for consistency?

---

*[projects/batfish/src/main/java/org/batfish/representation/host/HostConfiguration.java, line 198 at r5](https://beta.reviewable.io/reviews/batfish/batfish/1142#-L9mp-lE6x9X9TL45BWA:-L9mp-lE6x9X9TL45BWB:b-ftvo5k) ([raw file](https://github.com/batfish/batfish/blob/fac3de904d6911f536a2a08588a2d1f246bc2a8d/projects/batfish/src/main/java/org/batfish/representation/host/HostConfiguration.java#L198)):*
> ```Java
>               && !((MatchHeaderSpace) line.getMatchCondition()).getHeaderspace().unrestricted()) {
>             return false;
>           }
> ```

suggestion: future-proof by throwing an exception if you get a match condition type other than MatchHeaderSpace

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1142)*

**Comment by anothermattbrown** [comment]
Reviewed 1 of 19 files at r4.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1142)*

**Comment by arifogel** [comment]
Review status: 65 of 71 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpAccessList.java, line 111 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1142#-L9kWkSA173VGXB6euLb:-L9ptwrxBfkEJ0Ogl6Dz:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/0c8b89d3652011e7fda2ba3e7fcc960c7e6be8c3/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpAccessList.java#L111)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

Can we construct one `Evaluator` here and use `line.getMatchCondition().accept()` rather than creating a new `Evaluator` for each line?
</blockquote></details>

Done.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpAccessListLine.java, line 82 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1142#-L9kXI_BA15m1BB8bo13:-L9pu30S3lOeCtxeK4DZ:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/0c8b89d3652011e7fda2ba3e7fcc960c7e6be8c3/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpAccessListLine.java#L82)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

Why not `_action == other._action`?
</blockquote></details>

Done.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclLineMatchExpr.java, line 28 at r3](https://beta.reviewable.io/reviews/batfish/batfish/1142#-L9ku2lz2PZYrmKuIatU:-L9pu7Xc6eHrQS2lbN6A:bs34oav) ([raw file](https://github.com/batfish/batfish/blob/5038b6c87f0b894a52a0132cc796849b5dd0947d/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclLineMatchExpr.java#L28)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

should we change this to `return compareTo(o) == 0`? or is there an efficiency concern?
</blockquote></details>

That's a stronger contract than is necessary, and also is slower.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/OrMatchExpr.java, line 15 at r3](https://beta.reviewable.io/reviews/batfish/batfish/1142#-L9kutiY8cBceUsKSYCe:-L9puIYoETFZD7hcjYgY:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/5038b6c87f0b894a52a0132cc796849b5dd0947d/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/OrMatchExpr.java#L15)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

`SortedSet`?
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/bdp/BdpEngine.java, line 75 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1142#-L9kXshe0oxY6XuGlFEZ:-L9puNBz6vynyxDweC2I:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/0c8b89d3652011e7fda2ba3e7fcc960c7e6be8c3/projects/batfish/src/main/java/org/batfish/bdp/BdpEngine.java#L75)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

Looks like this should be `@Nullable`
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/bdp/BdpEngine.java, line 157 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1142#-L9kXpZc1WV-pAAPF83h:-L9punZuAqktdPr6Hd4k:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/0c8b89d3652011e7fda2ba3e7fcc960c7e6be8c3/projects/batfish/src/main/java/org/batfish/bdp/BdpEngine.java#L157)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

rename `srcInterface` for consistency?
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/representation/host/HostConfiguration.java, line 198 at r5](https://beta.reviewable.io/reviews/batfish/batfish/1142#-L9mp-lE6x9X9TL45BWA:-L9puwgg7vp2mYyeRSNQ:b-kniqmi) ([raw file](https://github.com/batfish/batfish/blob/fac3de904d6911f536a2a08588a2d1f246bc2a8d/projects/batfish/src/main/java/org/batfish/representation/host/HostConfiguration.java#L198)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

suggestion: future-proof by throwing an exception if you get a match condition type other than MatchHeaderSpace
</blockquote></details>

That is not my intended behavior. The purpose of this function is just to see if the ACL is simple enough for our current level of Iptables support. Since it is a bandaid, there really is no way to make it "future-proof".
I updated the code with some comments and better behavior, though.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1142)*

**Comment by anothermattbrown** [comment]
Reviewed 24 of 24 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclLineMatchExpr.java, line 28 at r3](https://beta.reviewable.io/reviews/batfish/batfish/1142#-L9ku2lz2PZYrmKuIatU:-L9qMmeh5hTTe0r1TGwv:ba86dam) ([raw file](https://github.com/batfish/batfish/blob/5038b6c87f0b894a52a0132cc796849b5dd0947d/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclLineMatchExpr.java#L28)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

That's a stronger contract than is necessary, and also is slower.
</blockquote></details>

How so?

---

*[projects/batfish/src/main/java/org/batfish/representation/host/HostConfiguration.java, line 198 at r5](https://beta.reviewable.io/reviews/batfish/batfish/1142#-L9mp-lE6x9X9TL45BWA:-L9qNKTmBdK-OHP8gnU5:b-emp7os) ([raw file](https://github.com/batfish/batfish/blob/fac3de904d6911f536a2a08588a2d1f246bc2a8d/projects/batfish/src/main/java/org/batfish/representation/host/HostConfiguration.java#L198)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

That is not my intended behavior. The purpose of this function is just to see if the ACL is simple enough for our current level of Iptables support. Since it is a bandaid, there really is no way to make it "future-proof".
I updated the code with some comments and better behavior, though.
</blockquote></details>

By future-proof I meant we should fail loudly rather than silently if we forget to make this change when ACLs become more complicated. Currently we'll reach the end of the method and silently return false which is bad IMO. 

---

*[projects/batfish/src/main/java/org/batfish/z3/expr/visitors/AclLineMatchBooleanExprTransformer.java, line 20 at r6](https://beta.reviewable.io/reviews/batfish/batfish/1142#-L9qOUAe9LMXb0KdRb0t:-L9qOUAe9LMXb0KdRb0u:bpfydqh) ([raw file](https://github.com/batfish/batfish/blob/865419f5b6b4ef81745ff08a836555487fb92b77/projects/batfish/src/main/java/org/batfish/z3/expr/visitors/AclLineMatchBooleanExprTransformer.java#L20)):*
> ```Java
> import org.batfish.z3.expr.OrExpr;
> 
> public class AclLineMatchBooleanExprTransformer
> ```

Why are you implementing this? This was tasked to me (and I already did it)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1142)*

**Comment by arifogel** [comment]
Review status: 79 of 90 files reviewed at latest revision, 3 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclLineMatchExpr.java, line 28 at r3](https://beta.reviewable.io/reviews/batfish/batfish/1142#-L9ku2lz2PZYrmKuIatU:-L9qVPoy1gLZRK2EYZK6:b-q8wq6t) ([raw file](https://github.com/batfish/batfish/blob/5038b6c87f0b894a52a0132cc796849b5dd0947d/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/acl/AclLineMatchExpr.java#L28)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

How so?
</blockquote></details>

For `Comparable`s `a` and `b`, `a.equals(b) -> a.compareTo(b) == 0`, but not necessarily the converse.

I'm not 100% certain, but my intuition says more indirection will happen for`compareTo` vs. equals. 

---

*[projects/batfish/src/main/java/org/batfish/representation/host/HostConfiguration.java, line 198 at r5](https://beta.reviewable.io/reviews/batfish/batfish/1142#-L9mp-lE6x9X9TL45BWA:-L9qWATMEwIXV0WG-kow:bqhw3u9) ([raw file](https://github.com/batfish/batfish/blob/fac3de904d6911f536a2a08588a2d1f246bc2a8d/projects/batfish/src/main/java/org/batfish/representation/host/HostConfiguration.java#L198)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

By future-proof I meant we should fail loudly rather than silently if we forget to make this change when ACLs become more complicated. Currently we'll reach the end of the method and silently return false which is bad IMO. 
</blockquote></details>

We do fail loudly in the method that calls this method. But we don't want to crash, because we still want to be able to analyze the rest of the config.
The relevant code is in the same file:
```
    // apply acls to interfaces
    if (simple()) {
      for (Interface iface : _c.getDefaultVrf().getInterfaces().values()) {
        iface.setIncomingFilter(_c.getIpAccessLists().get(FILTER_INPUT));
        iface.setOutgoingFilter(_c.getIpAccessLists().get(FILTER_OUTPUT));
      }
    } else {
      _w.unimplemented("Do not support complicated iptables rules yet");
    }
``` 

---

*[projects/batfish/src/main/java/org/batfish/z3/expr/visitors/AclLineMatchBooleanExprTransformer.java, line 20 at r6](https://beta.reviewable.io/reviews/batfish/batfish/1142#-L9qOUAe9LMXb0KdRb0t:-L9qW_omEr5MreJ36_md:b-9usybb) ([raw file](https://github.com/batfish/batfish/blob/865419f5b6b4ef81745ff08a836555487fb92b77/projects/batfish/src/main/java/org/batfish/z3/expr/visitors/AclLineMatchBooleanExprTransformer.java#L20)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

Why are you implementing this? This was tasked to me (and I already did it)
</blockquote></details>

I didn't want to, but I could not get tests to pass without it. I kept getting ClassCastException, and this was the easiest way to fix it. Sorry, I should have conferred with you first.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1142)*

**Comment by anothermattbrown** [comment]
Review status: 79 of 90 files reviewed at latest revision, 3 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/z3/expr/visitors/AclLineMatchBooleanExprTransformer.java, line 20 at r6](https://beta.reviewable.io/reviews/batfish/batfish/1142#-L9qOUAe9LMXb0KdRb0t:-L9qYQKO16Q0TW0u48sO:bwfnffr) ([raw file](https://github.com/batfish/batfish/blob/865419f5b6b4ef81745ff08a836555487fb92b77/projects/batfish/src/main/java/org/batfish/z3/expr/visitors/AclLineMatchBooleanExprTransformer.java#L20)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

I didn't want to, but I could not get tests to pass without it. I kept getting ClassCastException, and this was the easiest way to fix it. Sorry, I should have conferred with you first.
</blockquote></details>

no problem, this is fine.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1142)*

**Comment by anothermattbrown** [comment]
Reviewed 27 of 58 files at r1, 3 of 37 files at r3, 13 of 19 files at r4, 11 of 11 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1142)*

**Pull request merged**
