### PR TITLE
Ipsec profile -> set isakmp-profile

### PR DESCRIPTION
**Pull request by ratulm**
Let me know if I missed reference counting for this

### CODE REVIEW

**Comment by dhalperi** [comment]
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_crypto.g4, line 273 at r1](https://reviewable.io/reviews/batfish/batfish/1489#-LDFtdUNBwEI1WUI9TJL:-LDFtdUNBwEI1WUI9TJM:bdyw0b) ([raw file](https://github.com/batfish/batfish/blob/78bd094201511694d201957066109bad30cbffc6/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_crypto.g4#L273)):*
> ```
> cipprf_set_null
> ```
Does the `null` rule contain `ISAKMP_PROFILE` by any chance? or something else like it that also uses names?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1489)*

**Comment by ratulm** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_crypto.g4, line 273 at r1](https://reviewable.io/reviews/batfish/batfish/1489#-LDFtdUNBwEI1WUI9TJL:-LDFu-QcB-QXQmd4WNWe:b-6ka2s7) ([raw file](https://github.com/batfish/batfish/blob/78bd094201511694d201957066109bad30cbffc6/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_crypto.g4#L273)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> cipprf_set_null
> ```
Does the `null` rule contain `ISAKMP_PROFILE` by any chance? or something else like it that also uses names?
</blockquote></details>

cipprf_set_null
:
   (
      IKEV2_PROFILE
      | SECURITY_ASSOCIATION
   ) null_rest_of_line
;

No ISAKMP_PROFILE but I imagine a name follows IKEV2_PROFILE. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1489)*

**Comment by dhalperi** [comment]
I expected a new undefined ref or at least a referrer count change. Suggestion why.

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 1141 at r1](https://reviewable.io/reviews/batfish/batfish/1489#-LDFurrJ45ZiqZDZKkk-:-LDFurrJ45ZiqZDZKkk0:bfu6z2s) ([raw file](https://github.com/batfish/batfish/blob/78bd094201511694d201957066109bad30cbffc6/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L1141)):*
> ```
> someprofile
> ```
just inline this -- put the markConcreteStructure where you call this function.

(new style, easier to read).

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 1141 at r1](https://reviewable.io/reviews/batfish/batfish/1489#-LDFuxUm1rw2VImNM9jE:-LDFuxUm1rw2VImNM9jF:b-k57s10) ([raw file](https://github.com/batfish/batfish/blob/78bd094201511694d201957066109bad30cbffc6/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L1141)):*
> ```
> ISAKMP_POLICY
> ```

ISAKMP_PROFILE

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1489#-:-LDFv0rZ-IKsGwzcNqoC:b-3tuf0k)*

**Comment by dhalperi** [comment]
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_crypto.g4, line 273 at r1](https://reviewable.io/reviews/batfish/batfish/1489#-LDFtdUNBwEI1WUI9TJL:-LDFvAvH2C6_boyl4-Jq:bdhsr0s) ([raw file](https://github.com/batfish/batfish/blob/78bd094201511694d201957066109bad30cbffc6/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_crypto.g4#L273)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

cipprf_set_null
:
   (
      IKEV2_PROFILE
      | SECURITY_ASSOCIATION
   ) null_rest_of_line
;

No ISAKMP_PROFILE but I imagine a name follows IKEV2_PROFILE. 

</blockquote></details>

Yes, you can see from the unit-tests that it does. Up to you whether to implement in this PR.

(marking satisfied as-is.)

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1489)*

**Comment by ratulm** [comment]
Review status: 7 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 1141 at r1](https://reviewable.io/reviews/batfish/batfish/1489#-LDFurrJ45ZiqZDZKkk-:-LDG-JyF1_REU8EiVM6D:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/78bd094201511694d201957066109bad30cbffc6/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L1141)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> someprofile
> ```
just inline this -- put the markConcreteStructure where you call this function.

(new style, easier to read).
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 1141 at r1](https://reviewable.io/reviews/batfish/batfish/1489#-LDFuxUm1rw2VImNM9jE:-LDG-LY00EsCyJjLrWMt:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/78bd094201511694d201957066109bad30cbffc6/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L1141)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> ISAKMP_POLICY
> ```

ISAKMP_PROFILE
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1489)*

**Comment by dhalperi** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r2, 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1489#-:-LDG5aEHA7wFAzpa9Lft:bnfp4nl)*

**Pull request merged**
