### PR TITLE
ForwardingAnalysis: refactor to use fewer maps and parallelize over nodes

### PR DESCRIPTION
**Pull request by anothermattbrown**

### CODE REVIEW

**Comment by dhalperi** [comment]
*[a discussion](https://reviewable.io/reviews/batfish/batfish/7194#-MfAQ_UvAPexBRkNPJyt:-MfAQ_UvAPexBRkNPJyu:b32vb8) (no related file):*
21

---

**Comment by dhalperi** [comment]
*[a discussion](https://reviewable.io/reviews/batfish/batfish/7194#-MfAQiM06-ZJXQK-n9Km:-MfAQiM06-ZJXQK-n9Kn:b32vbd) (no related file):*
26

---

**Comment by dhalperi** [comment]
*[a discussion](https://reviewable.io/reviews/batfish/batfish/7194#-MfAQiM06-ZJXQK-n9Km:-MfAQyC0EVbfuDIS4ej7:b2ngzf0) (no related file):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

26
</blockquote></details>

30.

---

**Comment by dhalperi** [comment]
*[a discussion](https://reviewable.io/reviews/batfish/batfish/7194#-MfAQzZz5GfVQTDIGFuV:-MfAQzZz5GfVQTDIGFuW:b2ngzf0) (no related file):*
30.

---

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7194)* status: 0 of 11 files reviewed, all discussions resolved (waiting on @anothermattbrown)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7194#-MfASE1T-SsQfMiOmV29:-MfASE1U0xHlxXC-kzLg:b-lwjl8x) (no related file):*
31! empty commit unblocked us.

---

**Review by dhalperi — COMMENTED** [review]
> Reviewed 9 of 11 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7194)* status: 9 of 11 files reviewed, all discussions resolved (waiting on @dhalperi)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7194)* status: 9 of 11 files reviewed, 1 unresolved discussion (waiting on @anothermattbrown and @dhalperi)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysisImpl.java, line 290 at r5](https://reviewable.io/reviews/batfish/batfish/7194#-MfAhp0B3momTexpmOa-:-MfAhp0B3momTexpmOa0:btly53r) ([raw file](https://github.com/batfish/batfish/blob/83898edad240eb1fd660b1cee002415f18f0dbc7/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysisImpl.java#L290)):*
> ```
>                         Set<String> ifaces =
>                             Stream.of(accepted, exitsNetwork, insufficientInfo, neighborUnreachable)
> ```
Not sure how we  know which keys need to be in this set.

E.g., is it ever the case that `accepted` isn't all of them -- some interface can send traffic out but not accept it?

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7194)* status: 9 of 11 files reviewed, 1 unresolved discussion (waiting on @anothermattbrown and @dhalperi)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 2 files at r6, 2 of 2 files at r7, 2 of 2 files at r8, 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7194)* status: 9 of 11 files reviewed, all discussions resolved (waiting on @dhalperi)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 2 files at r10, 2 of 2 files at r11, 2 of 2 files at r12, 2 of 2 files at r13, 2 of 2 files at r14, 2 of 2 files at r15, 2 of 2 files at r16, 2 of 2 files at r17, 2 of 2 files at r18, 2 of 2 files at r19, 1 of 1 files at r20, 2 of 2 files at r21, 2 of 2 files at r22, 2 of 2 files at r23, 2 of 2 files at r24, 2 of 2 files at r25, 2 of 2 files at r26, 1 of 1 files at r27, 2 of 2 files at r28, 2 of 2 files at r29, 1 of 1 files at r30, 1 of 1 files at r32.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7194)* status: all files reviewed, 1 unresolved discussion (waiting on @anothermattbrown)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysisImpl.java, line 1118 at r27](https://reviewable.io/reviews/batfish/batfish/7194#-MfAlrPp7POkHHBP_CBR:-MfAlrPp7POkHHBP_CBS:b2tfztf) ([raw file](https://github.com/batfish/batfish/blob/ffe487a916b9ca06a87610fe2fca5a4ee6d0d0a3/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysisImpl.java#L1118)):*
> ```Java
>       IpSpace arpFalse,
>       InterfaceForwardingBehavior ifb) {
>     synchronized (ipSpaceToBDD.getBDDInteger().getFactory()) {
> ```

FYI, I'd be fine with creating IpSpaceToBDD separately for each. If we're parallelizing, probably faster anyway.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysisImpl.java, line 159 at r32](https://reviewable.io/reviews/batfish/batfish/7194#-MfAoH1-7cEpVzwTozU5:-MfAoH1-7cEpVzwTozU6:b-fg0es4) ([raw file](https://github.com/batfish/batfish/blob/0c2780f1b5170a24135eee26f33821342427f89d/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysisImpl.java#L159)):*
> ```Java
>       IpSpace internalIps,
>       IpSpace externalIps,
>       Map<String, Map<String, Map<String, Set<AbstractRoute>>>> routesWithNextHop) {
> ```

Wondering if it's worth using a shared BDD; trying to figure out which state in here is actually global. Having a hard time udnerstanding how much we ever convert the same IpSpace to BDD in different VRFs.

Seems like maybe not/

**Review by anothermattbrown — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7194)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysisImpl.java, line 290 at r5](https://reviewable.io/reviews/batfish/batfish/7194#-MfAhp0B3momTexpmOa-:-MfAw_UJ6VeYyiIcDLkV:bei1kq0) ([raw file](https://github.com/batfish/batfish/blob/83898edad240eb1fd660b1cee002415f18f0dbc7/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysisImpl.java#L290)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
>                         Set<String> ifaces =
>                             Stream.of(accepted, exitsNetwork, insufficientInfo, neighborUnreachable)
> ```
Not sure how we  know which keys need to be in this set.

E.g., is it ever the case that `accepted` isn't all of them -- some interface can send traffic out but not accept it?
</blockquote></details>

yes, since vrf leaking can cause us to forward out interfaces in other vrfs. This becomes clear in a later commit.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysisImpl.java, line 1118 at r27](https://reviewable.io/reviews/batfish/batfish/7194#-MfAlrPp7POkHHBP_CBR:-MfAwwayD-2iX1nUr4K-:b-on2kvb) ([raw file](https://github.com/batfish/batfish/blob/ffe487a916b9ca06a87610fe2fca5a4ee6d0d0a3/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysisImpl.java#L1118)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

FYI, I'd be fine with creating IpSpaceToBDD separately for each. If we're parallelizing, probably faster anyway.
</blockquote></details>

yeah it's worth thinking about. we'd have to recompute ownedIps repeatedly though, which could negate some of the benefits
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysisImpl.java, line 159 at r32](https://reviewable.io/reviews/batfish/batfish/7194#-MfAoH1-7cEpVzwTozU5:-MfAwnb6AX5TJH3S6WyS:bq3yxvh) ([raw file](https://github.com/batfish/batfish/blob/0c2780f1b5170a24135eee26f33821342427f89d/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysisImpl.java#L159)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Wondering if it's worth using a shared BDD; trying to figure out which state in here is actually global. Having a hard time udnerstanding how much we ever convert the same IpSpace to BDD in different VRFs.

Seems like maybe not/
</blockquote></details>

yeah we could consider creating separate factories per node.

**Review by anothermattbrown — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7194)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysisImpl.java, line 1118 at r27](https://reviewable.io/reviews/batfish/batfish/7194#-MfAlrPp7POkHHBP_CBR:-MfDzm6MDTaB46bKJwGu:b1aknl0) ([raw file](https://github.com/batfish/batfish/blob/ffe487a916b9ca06a87610fe2fca5a4ee6d0d0a3/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysisImpl.java#L1118)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

yeah it's worth thinking about. we'd have to recompute ownedIps repeatedly though, which could negate some of the benefits
</blockquote></details>

actually we don't need to recompute ownedIps for sanity checks. I think I see the thing to do. Will do that in a separate PR though

**Review by anothermattbrown — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7194)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysisImpl.java, line 159 at r32](https://reviewable.io/reviews/batfish/batfish/7194#-MfAoH1-7cEpVzwTozU5:-MfE-8CBEQU6JF572yva:b-riust5) ([raw file](https://github.com/batfish/batfish/blob/0c2780f1b5170a24135eee26f33821342427f89d/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/ForwardingAnalysisImpl.java#L159)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

yeah we could consider creating separate factories per node.
</blockquote></details>

In a later commit I move all the bdd operations out of the per-node loop, except for sanity checking. In a separate PR I'll change how we do that. The simplest/cleanest thing would be to have every interface create a BDDFactory for its sanity checks. Caching would be better if  we lazily create one per node for all interfaces to use.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 2 files at r33, 2 of 2 files at r34, 2 of 2 files at r35, 2 of 2 files at r36, 2 of 2 files at r37, 2 of 2 files at r38, 2 of 2 files at r39, 2 of 2 files at r40, 1 of 1 files at r41, 2 of 2 files at r42, 2 of 2 files at r43, 1 of 1 files at r44, 1 of 1 files at r45.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7194)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown)

**Pull request merged**
