### PR TITLE
PacketPolicyToBDD: create fewer BDD graph states

### PR DESCRIPTION
**Pull request by anothermattbrown**
Rewrite PacketPolicyToBDD to create fewer BDD graph states (nodes) to allow more edges to be merged. The new strategy is to only create a new state when fanning in from multiple pre-states, or when we'd have to use a `Composite` transition otherwise.  The new `Transform` transition merges better than `EraseAndSet`, allowing us to merge more transitions without introducing `Composite` transitions. 

To facilitate this, `mergeComposed` now tries to merge `Or` followed by `Constraint` when the `Or` is small enough. It does this by composing each disjunct with the constraint.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8289)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @anothermattbrown and @dhalperi)

___
*[`projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transitions.java` line 217 at r1](https://reviewable.io/reviews/batfish/batfish/8289#-N15hPP80nd97Lyeu8kS:-N15hPP80nd97Lyeu8kT:b-3q0oh) ([raw file](https://github.com/batfish/batfish/blob/1209349d7538d013ebf9b2b9e71d011061d7e23f/projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transitions.java#L217)):*
> ```Java
>       return eraseAndSet(var, add.getSourceBdd());
>     }
>     if (t1 instanceof Or && t2 instanceof Constraint) {
> ```

seems worth splitting out as its own PR?

Mainly so it could be reverted / tweaks on its own?

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8289)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @anothermattbrown and @dhalperi)

___
*[`projects/batfish/src/main/java/org/batfish/bddreachability/PacketPolicyToBdd.java` line 297 at r1](https://reviewable.io/reviews/batfish/batfish/8289#-N15ifFN2fXPgluv3cFB:-N15ifFN2fXPgluv3cFC:b-w6yj69) ([raw file](https://github.com/batfish/batfish/blob/1209349d7538d013ebf9b2b9e71d011061d7e23f/projects/batfish/src/main/java/org/batfish/bddreachability/PacketPolicyToBdd.java#L297)):*
> ```Java
>     public Void visitApplyFilter(ApplyFilter applyFilter) {
>       BDD permitBdd =
>           _boolExprToBdd._ipAccessListToBdd.toBdd(new PermittedByAcl(applyFilter.getFilter()));
> ```

how about `toPermitAndDenyBdds` since that will already have done the not. Note that `toBDD` seems to already do that, then throw away the denied part? Maybe need to make an AclAclLIne or something for it.

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8289)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @anothermattbrown and @dhalperi)

___
*[`projects/batfish/src/main/java/org/batfish/bddreachability/PacketPolicyToBdd.java` line 297 at r1](https://reviewable.io/reviews/batfish/batfish/8289#-N15ifFN2fXPgluv3cFB:-N166mIp6VNOZ9334WHw:bsnb8ix) ([raw file](https://github.com/batfish/batfish/blob/1209349d7538d013ebf9b2b9e71d011061d7e23f/projects/batfish/src/main/java/org/batfish/bddreachability/PacketPolicyToBdd.java#L297)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

how about `toPermitAndDenyBdds` since that will already have done the not. Note that `toBDD` seems to already do that, then throw away the denied part? Maybe need to make an AclAclLIne or something for it.
</blockquote></details>

per discussion, yep, this is wrong.

**Review by anothermattbrown — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8289)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @dhalperi)

___
*[`projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transitions.java` line 217 at r1](https://reviewable.io/reviews/batfish/batfish/8289#-N15hPP80nd97Lyeu8kS:-N166qKhEiYo6ORyGTWW:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/1209349d7538d013ebf9b2b9e71d011061d7e23f/projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transitions.java#L217)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

seems worth splitting out as its own PR?

Mainly so it could be reverted / tweaks on its own?
</blockquote></details>

done

**Review by dhalperi — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 4 files at r1, 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8289#-:-N167bqm6qQyvUzmDbip:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown)

**Pull request merged**
