### PR TITLE
Enable pmd checks for programming issues and copy-paste detection

### PR DESCRIPTION
**Pull request by arifogel**
- Currently both checks do not fail build to allow time for others to fix violations

---
This change is [Reviewable](https://reviewable.io/reviews/batfish/batfish/615)

### CODE REVIEW

**Comment by dhalperi** [comment]
I would prefer to set the checks on by default in the parent `pom.xml`, and then disable them in specific child `pom.xml` files (with issues filed to fix and a TODO(issue) comment where disabled).

---

Reviewed 43 of 61 files at r1.
Review status: 43 of 61 files reviewed at latest revision, 21 unresolved discussions, some commit checks failed.

---

*[projects/pom.xml, line 280 at r1](https://reviewable.io:443/reviews/batfish/batfish/615#-KxOfiZec85HTgrH9Llo:-KxOfiZec85HTgrH9Llp:b-3te27b) ([raw file](https://github.com/batfish/batfish/blob/9503cbfa95331f7e13d75ba66c8573990483f68c/projects/pom.xml#L280)):*
> ```XML
>         <groupId>org.apache.maven.plugins</groupId>
>         <artifactId>maven-pmd-plugin</artifactId>
>         <version>${maven-pmd-plugin.version}</version>
> ```

move any global configuration into `pluginManagement`. This usually includes:

version, dependencies, etc. Then the entry in `plugins` section will just tell the plugin to execute or have module-specific configuration.

---

*[projects/pom.xml, line 338 at r1](https://reviewable.io:443/reviews/batfish/batfish/615#-KxOg2SEjwzGPenR-lMI:-KxOg2SEjwzGPenR-lMJ:b-kgpr1e) ([raw file](https://github.com/batfish/batfish/blob/9503cbfa95331f7e13d75ba66c8573990483f68c/projects/pom.xml#L338)):*
> ```XML
>         <groupId>org.apache.maven.plugins</groupId>
>         <artifactId>maven-jxr-plugin</artifactId>
>         <version>${maven-jxr-plugin.version}</version>
> ```

same comment - pluginManagement vs plugins

---

*[projects/pom.xml, line 668 at r1](https://reviewable.io:443/reviews/batfish/batfish/615#-KxOg7ME4uJJWEAH4-gF:-KxOg7ME4uJJWEAH4-gG:b7bvv7x) ([raw file](https://github.com/batfish/batfish/blob/9503cbfa95331f7e13d75ba66c8573990483f68c/projects/pom.xml#L668)):*
> ```XML
>          <artifactId>maven-project-info-reports-plugin</artifactId>
>          
>          <version>2.9</version>
> ```

define a version flag, don't inline 2.9

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/util/Backoff.java, line 104 at r1](https://reviewable.io:443/reviews/batfish/batfish/615#-KxOgNx6UbLm4EMZJcxU:-KxOgNx6UbLm4EMZJcxV:b-j5as7i) ([raw file](https://github.com/batfish/batfish/blob/f5ec2b30ad41476b17ffe2b3cf10ad158cf7e5c2/projects/batfish-common-protocol/src/main/java/org/batfish/common/util/Backoff.java#L104)):*
> ```Java
>     public boolean hasNext() {
>       return ((_attempts + 1) < _builder._attemptLimit)
>           && (_cumulativeBackoff.compareTo(_builder._cumulativeBackoffLimit) < 0);
> ```

not obvious this is a good change, but okay.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AsPathAccessList.java, line 88 at r1](https://reviewable.io:443/reviews/batfish/batfish/615#-KxOglS5z_pTFNF6_UF1:-KxOglS5z_pTFNF6_UF2:bptkrx4) ([raw file](https://github.com/batfish/batfish/blob/9503cbfa95331f7e13d75ba66c8573990483f68c/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AsPathAccessList.java#L88)):*
> ```Java
>   @Override
>   public int hashCode() {
>     return Objects.hash(_key, _lines);
> ```

equals does not check `_key` -- who's wrong?

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpNeighbor.java, line 547 at r1](https://reviewable.io:443/reviews/batfish/batfish/615#-KxOhQ90BKkGXCAkffoA:-KxOhQ90BKkGXCAkffoB:b-wm07om) ([raw file](https://github.com/batfish/batfish/blob/9503cbfa95331f7e13d75ba66c8573990483f68c/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpNeighbor.java#L547)):*
> ```Java
>   public int hashCode() {
>     return Objects.hash(
>         _key,
> ```

equals does not seem to compare `_key` - who's right?

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/CommunityList.java, line 84 at r1](https://reviewable.io:443/reviews/batfish/batfish/615#-KxOhWzEKsJSIPY84Ypv:-KxOhWzEKsJSIPY84Ypw:bmiu3hh) ([raw file](https://github.com/batfish/batfish/blob/9503cbfa95331f7e13d75ba66c8573990483f68c/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/CommunityList.java#L84)):*
> ```Java
>   @Override
>   public int hashCode() {
>     return Objects.hash(_key, _lines);
> ```

`_key` again

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java, line 766 at r1](https://reviewable.io:443/reviews/batfish/batfish/615#-KxOiAVNTAV3yIY5MOIH:-KxOiAVNTAV3yIY5MOII:b-tsscwr) ([raw file](https://github.com/batfish/batfish/blob/9503cbfa95331f7e13d75ba66c8573990483f68c/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java#L766)):*
> ```Java
>   public int hashCode() {
>     return Objects.hash(
>         _key,
> ```

`_key`

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java, line 778 at r1](https://reviewable.io:443/reviews/batfish/batfish/615#-KxOiCsRmWot9GSx9ou1:-KxOiCsRmWot9GSx9ou2:brc1v1h) ([raw file](https://github.com/batfish/batfish/blob/9503cbfa95331f7e13d75ba66c8573990483f68c/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java#L778)):*
> ```Java
>         _mtu,
>         _nativeVlan,
>         _outgoingFilter != null ? _outgoingFilter.getName() : null,
> ```

I'm not sure I understand the logic here, but it does match `equals`

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Ip.java, line 19 at r1](https://reviewable.io:443/reviews/batfish/batfish/615#-KxOiRT7kAeww6BzQfgv:-KxOiRT7kAeww6BzQfgw:ben7tm5) ([raw file](https://github.com/batfish/batfish/blob/9503cbfa95331f7e13d75ba66c8573990483f68c/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Ip.java#L19)):*
> ```Java
>   public static final Ip AUTO = new Ip(-1L);
> 
>   public static final Ip FIRST_CLASS_A_PRIVATE_IP = new Ip(10L << 24);
> ```

* Comment: this seems less readable than "10.0.0.0".

* Do we need a "last" in the block, or a prefix defining the range?

* While we're here, should we add the other classes?

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Ip6AccessList.java, line 79 at r1](https://reviewable.io:443/reviews/batfish/batfish/615#-KxOix8gykB0MPQMFkjU:-KxOix8gykB0MPQMFkjV:b-tsscwr) ([raw file](https://github.com/batfish/batfish/blob/9503cbfa95331f7e13d75ba66c8573990483f68c/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Ip6AccessList.java#L79)):*
> ```Java
>   @Override
>   public int hashCode() {
>     return Objects.hash(_key, _lines);
> ```

`_key`

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfAreaRoute.java, line 22 at r1](https://reviewable.io:443/reviews/batfish/batfish/615#-KxOnWFQ_0O53WgCNKq7:-KxOnWFQ_0O53WgCNKq8:b-wh3vs6) ([raw file](https://github.com/batfish/batfish/blob/9503cbfa95331f7e13d75ba66c8573990483f68c/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfAreaRoute.java#L22)):*
> ```Java
>     if (o == this) {
>       return true;
>     } else if (!getClass().equals(o.getClass())) {
> ```

this will fail on `null` `o`

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfAreaRoute.java, line 26 at r1](https://reviewable.io:443/reviews/batfish/batfish/615#-KxOn_q2YpFuqkQUPViY:-KxOn_q2YpFuqkQUPViZ:b-2oi6es) ([raw file](https://github.com/batfish/batfish/blob/9503cbfa95331f7e13d75ba66c8573990483f68c/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfAreaRoute.java#L26)):*
> ```Java
>     }
>     OspfAreaRoute other = (OspfAreaRoute) o;
>     if (_nextHopIp == null) {
> ```

Use `Objects.equals` to simplify, and probably reduce whole function to `return () && () && () ...`

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/RouteFilterList.java, line 59 at r1](https://reviewable.io:443/reviews/batfish/batfish/615#-KxOn665rot-AJyjVg3R:-KxOn665rot-AJyjVg3S:b-tsscwr) ([raw file](https://github.com/batfish/batfish/blob/9503cbfa95331f7e13d75ba66c8573990483f68c/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/RouteFilterList.java#L59)):*
> ```Java
>   @Override
>   public int hashCode() {
>     return Objects.hash(_key, _lines);
> ```

`_key`

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/TcpFlags.java, line 158 at r1](https://reviewable.io:443/reviews/batfish/batfish/615#-KxOlnWT0qRTDOvskhSs:-KxOlnWT0qRTDOvskhSt:b-94z6nd) ([raw file](https://github.com/batfish/batfish/blob/9503cbfa95331f7e13d75ba66c8573990483f68c/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/TcpFlags.java#L158)):*
> ```Java
>   }
> 
>   public boolean match(Flow flow) {
> ```

Javadoc. Suggestion:

```java
/**
 * Returns {@code true} iff the TCP flags used in this object (configured via {@link #setUseAck})
 * match the TCP flags in the given {@link Flow}.
 *
 * <p>Note this function will return {@code true} if no bits are used.
 */
```

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Zone.java, line 192 at r1](https://reviewable.io:443/reviews/batfish/batfish/615#-KxOll46ue6QbemDEHEW:-KxOll46ue6QbemDEHEX:b-tsscwr) ([raw file](https://github.com/batfish/batfish/blob/9503cbfa95331f7e13d75ba66c8573990483f68c/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Zone.java#L192)):*
> ```Java
>   public int hashCode() {
>     return Objects.hash(
>         _key,
> ```

`_key`

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/RoutingPolicy.java, line 73 at r1](https://reviewable.io:443/reviews/batfish/batfish/615#-KxOlbM3wD8VRO6G-rv6:-KxOlbM3wD8VRO6G-rv7:b-tsscwr) ([raw file](https://github.com/batfish/batfish/blob/9503cbfa95331f7e13d75ba66c8573990483f68c/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/RoutingPolicy.java#L73)):*
> ```Java
>   @Override
>   public int hashCode() {
>     return Objects.hash(_key, _statements);
> ```

`_key`

---

*[projects/batfish/src/main/java/org/batfish/bdp/BdpDataPlanePlugin.java, line 88 at r1](https://reviewable.io:443/reviews/batfish/batfish/615#-KxOlFDWJWPKPDXyDCBz:-KxOlFDWJWPKPDXyDCC-:byrkqe) ([raw file](https://github.com/batfish/batfish/blob/9503cbfa95331f7e13d75ba66c8573990483f68c/projects/batfish/src/main/java/org/batfish/bdp/BdpDataPlanePlugin.java#L88)):*
> ```Java
>                         && sourceNat.getAcl().filter(flow).getAction() != LineAction.REJECT)
>             .findFirst();
>     if (matchingSourceNat.isPresent()) {
> ```

Here's another case where i might put the `if (!matchingSourceNat.isPresent()) { // No applicable NAT rule ; return }` up front to simplify (and unnest) the rest.

It's entirely heuristic and I think I choose more based on how long the body is.

---

*[projects/batfish/src/main/java/org/batfish/grammar/assertion/AssertionExtractor.java, line 57 at r1](https://reviewable.io:443/reviews/batfish/batfish/615#-KxOl2HMT1meqMUMb7ZU:-KxOl2HNI6Q_n7f97VZI:b-lo4ebx) ([raw file](https://github.com/batfish/batfish/blob/9503cbfa95331f7e13d75ba66c8573990483f68c/projects/batfish/src/main/java/org/batfish/grammar/assertion/AssertionExtractor.java#L57)):*
> ```Java
> 
>   @SuppressWarnings("unused")
>   private AssertionParser _parser;
> ```

? this seems unnecessary

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/Interface.java, line 234 at r1](https://reviewable.io:443/reviews/batfish/batfish/615#-KxOkB-YClnCN6KDlfk0:-KxOkB-YClnCN6KDlfk1:b-hnjzpg) ([raw file](https://github.com/batfish/batfish/blob/9503cbfa95331f7e13d75ba66c8573990483f68c/projects/batfish/src/main/java/org/batfish/representation/juniper/Interface.java#L234)):*
> ```Java
> 
>   public void inheritUnsetFields() {
>     if (_parent != null && !_inherited) {
> ```

Comment: when I have the entire contents of a function inside of an if, I tend to negate the expression and return early:

```java
if (_parent == null || _inherited) {
  // No one to inherit from || already inherited properties
  return;
}

... do the inheritance
```

---

*[projects/build-tools/pom.xml, line 5 at r1](https://reviewable.io:443/reviews/batfish/batfish/615#-KxOjnYdBn3nB7_cPw1u:-KxOjnYdBn3nB7_cPw1v:b-v6r9kt) ([raw file](https://github.com/batfish/batfish/blob/9503cbfa95331f7e13d75ba66c8573990483f68c/projects/build-tools/pom.xml#L5)):*
> ```XML
>   <groupId>org.batfish</groupId>
>   <artifactId>build-tools</artifactId>
>   <version>1.0</version>
> ```

I don't have a great feeling about having this be a separate and disconnected module (you didn't set a `parent`) as opposed to being versioned with Batfish. Will we properly remember to bump the version and re-release it every time we have changes?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/615#-:-KxOo8bEj2eP26ML8Khw:b-hzf3no)*

**Comment by arifogel** [comment]
Done except TODO. I will just make separate issue instead so it can be tracked more easily.

---

Review status: 32 of 48 files reviewed at latest revision, 21 unresolved discussions.

---

*[projects/pom.xml, line 280 at r1](https://reviewable.io:443/reviews/batfish/batfish/615#-KxOfiZec85HTgrH9Llo:-KxQOJcLTMAv6OZ82ETD:bb6un1j) ([raw file](https://github.com/batfish/batfish/blob/9503cbfa95331f7e13d75ba66c8573990483f68c/projects/pom.xml#L280)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

move any global configuration into `pluginManagement`. This usually includes:

version, dependencies, etc. Then the entry in `plugins` section will just tell the plugin to execute or have module-specific configuration.
</blockquote></details>

Done

---

*[projects/pom.xml, line 338 at r1](https://reviewable.io:443/reviews/batfish/batfish/615#-KxOg2SEjwzGPenR-lMI:-KxQON1vIU6oBKQlNhDT:bb6un1j) ([raw file](https://github.com/batfish/batfish/blob/9503cbfa95331f7e13d75ba66c8573990483f68c/projects/pom.xml#L338)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

same comment - pluginManagement vs plugins
</blockquote></details>

Done

---

*[projects/pom.xml, line 668 at r1](https://reviewable.io:443/reviews/batfish/batfish/615#-KxOg7ME4uJJWEAH4-gF:-KxQONbkb0nNILkgi9I7:bb6un1j) ([raw file](https://github.com/batfish/batfish/blob/9503cbfa95331f7e13d75ba66c8573990483f68c/projects/pom.xml#L668)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

define a version flag, don't inline 2.9
</blockquote></details>

Done

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/util/Backoff.java, line 104 at r1](https://reviewable.io:443/reviews/batfish/batfish/615#-KxOgNx6UbLm4EMZJcxU:-KxQOPvNURGc4vxzahqV:b-3tzpdp) ([raw file](https://github.com/batfish/batfish/blob/f5ec2b30ad41476b17ffe2b3cf10ad158cf7e5c2/projects/batfish-common-protocol/src/main/java/org/batfish/common/util/Backoff.java#L104)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

not obvious this is a good change, but okay.
</blockquote></details>

I actually ended up disabling the check that resulted in this, but yeah let's just leave it.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Ip.java, line 19 at r1](https://reviewable.io:443/reviews/batfish/batfish/615#-KxOiRT7kAeww6BzQfgv:-KxQOUjL0xXX0T7-dbGd:buzws6a) ([raw file](https://github.com/batfish/batfish/blob/9503cbfa95331f7e13d75ba66c8573990483f68c/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Ip.java#L19)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

* Comment: this seems less readable than "10.0.0.0".

* Do we need a "last" in the block, or a prefix defining the range?

* While we're here, should we add the other classes?
</blockquote></details>

There was a dumb check that basically wanted you to never use a literal IP address. In retrospect my workaround was nonsensical, so I went back but kept the new constants.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/TcpFlags.java, line 158 at r1](https://reviewable.io:443/reviews/batfish/batfish/615#-KxOlnWT0qRTDOvskhSs:-KxQOc86jp2ER-z-pBPR:b-8b11j9) ([raw file](https://github.com/batfish/batfish/blob/9503cbfa95331f7e13d75ba66c8573990483f68c/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/TcpFlags.java#L158)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Javadoc. Suggestion:

```java
/**
 * Returns {@code true} iff the TCP flags used in this object (configured via {@link #setUseAck})
 * match the TCP flags in the given {@link Flow}.
 *
 * <p>Note this function will return {@code true} if no bits are used.
 */
```
</blockquote></details>

Added

---

*[projects/batfish/src/main/java/org/batfish/bdp/BdpDataPlanePlugin.java, line 88 at r1](https://reviewable.io:443/reviews/batfish/batfish/615#-KxOlFDWJWPKPDXyDCBz:-KxQOdnVgFiVmSWBl5dN:b1vegrf) ([raw file](https://github.com/batfish/batfish/blob/9503cbfa95331f7e13d75ba66c8573990483f68c/projects/batfish/src/main/java/org/batfish/bdp/BdpDataPlanePlugin.java#L88)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Here's another case where i might put the `if (!matchingSourceNat.isPresent()) { // No applicable NAT rule ; return }` up front to simplify (and unnest) the rest.

It's entirely heuristic and I think I choose more based on how long the body is.
</blockquote></details>

Done your way

---

*[projects/batfish/src/main/java/org/batfish/grammar/assertion/AssertionExtractor.java, line 57 at r1](https://reviewable.io:443/reviews/batfish/batfish/615#-KxOl2HMT1meqMUMb7ZU:-KxQOh-KyDT3f20RdNP-:b4tvsb5) ([raw file](https://github.com/batfish/batfish/blob/9503cbfa95331f7e13d75ba66c8573990483f68c/projects/batfish/src/main/java/org/batfish/grammar/assertion/AssertionExtractor.java#L57)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

? this seems unnecessary
</blockquote></details>

It's just for consistency for extractor instantiation, and to provide parser to be used for helper functions that might get added when `AssertionExtractor` is expanded to include things the other extractors have. I'm leaving it. FYI it was flagged as an unused constructor parameter.

---

*[projects/batfish/src/main/java/org/batfish/representation/juniper/Interface.java, line 234 at r1](https://reviewable.io:443/reviews/batfish/batfish/615#-KxOkB-YClnCN6KDlfk0:-KxQOzmEc81JoJ5jcPcq:bysdixf) ([raw file](https://github.com/batfish/batfish/blob/9503cbfa95331f7e13d75ba66c8573990483f68c/projects/batfish/src/main/java/org/batfish/representation/juniper/Interface.java#L234)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Comment: when I have the entire contents of a function inside of an if, I tend to negate the expression and return early:

```java
if (_parent == null || _inherited) {
  // No one to inherit from || already inherited properties
  return;
}

... do the inheritance
```
</blockquote></details>

Fixed your way

---

*[projects/build-tools/pom.xml, line 5 at r1](https://reviewable.io:443/reviews/batfish/batfish/615#-KxOjnYdBn3nB7_cPw1u:-KxQP0HctQHDeyeUGs8B:b1kbnjy) ([raw file](https://github.com/batfish/batfish/blob/9503cbfa95331f7e13d75ba66c8573990483f68c/projects/build-tools/pom.xml#L5)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I don't have a great feeling about having this be a separate and disconnected module (you didn't set a `parent`) as opposed to being versioned with Batfish. Will we properly remember to bump the version and re-release it every time we have changes?
</blockquote></details>

Made it a child module

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AsPathAccessList.java, line 88 at r1](https://reviewable.io:443/reviews/batfish/batfish/615#-KxOglS5z_pTFNF6_UF1:-KxQP3jO8ApNTv5VAg5W:b-rf0hb4) ([raw file](https://github.com/batfish/batfish/blob/9503cbfa95331f7e13d75ba66c8573990483f68c/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AsPathAccessList.java#L88)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

equals does not check `_key` -- who's wrong?
</blockquote></details>

All equals and hashcode changes deferred to a future PR

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpNeighbor.java, line 547 at r1](https://reviewable.io:443/reviews/batfish/batfish/615#-KxOhQ90BKkGXCAkffoA:-KxQPBd2oOGZQHnjBI6N:b-rf0hb4) ([raw file](https://github.com/batfish/batfish/blob/9503cbfa95331f7e13d75ba66c8573990483f68c/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpNeighbor.java#L547)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

equals does not seem to compare `_key` - who's right?
</blockquote></details>

All equals and hashcode changes deferred to a future PR

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/CommunityList.java, line 84 at r1](https://reviewable.io:443/reviews/batfish/batfish/615#-KxOhWzEKsJSIPY84Ypv:-KxQPCTaXCrkfk5vzSX4:b-rf0hb4) ([raw file](https://github.com/batfish/batfish/blob/9503cbfa95331f7e13d75ba66c8573990483f68c/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/CommunityList.java#L84)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

`_key` again
</blockquote></details>

All equals and hashcode changes deferred to a future PR

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java, line 766 at r1](https://reviewable.io:443/reviews/batfish/batfish/615#-KxOiAVNTAV3yIY5MOIH:-KxQPDCAjpOizh9b7mnt:b-rf0hb4) ([raw file](https://github.com/batfish/batfish/blob/9503cbfa95331f7e13d75ba66c8573990483f68c/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java#L766)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

`_key`
</blockquote></details>

All equals and hashcode changes deferred to a future PR

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java, line 778 at r1](https://reviewable.io:443/reviews/batfish/batfish/615#-KxOiCsRmWot9GSx9ou1:-KxQPEEdoJ2R-dX2mC8a:b-rf0hb4) ([raw file](https://github.com/batfish/batfish/blob/9503cbfa95331f7e13d75ba66c8573990483f68c/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java#L778)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I'm not sure I understand the logic here, but it does match `equals`
</blockquote></details>

All equals and hashcode changes deferred to a future PR

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Ip6AccessList.java, line 79 at r1](https://reviewable.io:443/reviews/batfish/batfish/615#-KxOix8gykB0MPQMFkjU:-KxQPOd8D96D4UzfM5yA:b-rf0hb4) ([raw file](https://github.com/batfish/batfish/blob/9503cbfa95331f7e13d75ba66c8573990483f68c/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Ip6AccessList.java#L79)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

`_key`
</blockquote></details>

All equals and hashcode changes deferred to a future PR

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfAreaRoute.java, line 22 at r1](https://reviewable.io:443/reviews/batfish/batfish/615#-KxOnWFQ_0O53WgCNKq7:-KxQPG-2k7JAd8CQAmhN:b-rf0hb4) ([raw file](https://github.com/batfish/batfish/blob/9503cbfa95331f7e13d75ba66c8573990483f68c/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfAreaRoute.java#L22)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

this will fail on `null` `o`
</blockquote></details>

All equals and hashcode changes deferred to a future PR

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfAreaRoute.java, line 26 at r1](https://reviewable.io:443/reviews/batfish/batfish/615#-KxOn_q2YpFuqkQUPViY:-KxQPGztfVxRvMb1-TPA:b-rf0hb4) ([raw file](https://github.com/batfish/batfish/blob/9503cbfa95331f7e13d75ba66c8573990483f68c/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/OspfAreaRoute.java#L26)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Use `Objects.equals` to simplify, and probably reduce whole function to `return () && () && () ...`
</blockquote></details>

All equals and hashcode changes deferred to a future PR

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/RouteFilterList.java, line 59 at r1](https://reviewable.io:443/reviews/batfish/batfish/615#-KxOn665rot-AJyjVg3R:-KxQPP_k4YhIPITAun2e:b-rf0hb4) ([raw file](https://github.com/batfish/batfish/blob/9503cbfa95331f7e13d75ba66c8573990483f68c/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/RouteFilterList.java#L59)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

`_key`
</blockquote></details>

All equals and hashcode changes deferred to a future PR

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Zone.java, line 192 at r1](https://reviewable.io:443/reviews/batfish/batfish/615#-KxOll46ue6QbemDEHEW:-KxQPL8rmCCjST2tYByk:b-rf0hb4) ([raw file](https://github.com/batfish/batfish/blob/9503cbfa95331f7e13d75ba66c8573990483f68c/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Zone.java#L192)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

`_key`
</blockquote></details>

All equals and hashcode changes deferred to a future PR

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/RoutingPolicy.java, line 73 at r1](https://reviewable.io:443/reviews/batfish/batfish/615#-KxOlbM3wD8VRO6G-rv6:-KxQPM7ymX6g4MgGRCF1:b-rf0hb4) ([raw file](https://github.com/batfish/batfish/blob/9503cbfa95331f7e13d75ba66c8573990483f68c/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/RoutingPolicy.java#L73)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

`_key`
</blockquote></details>

All equals and hashcode changes deferred to a future PR

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/615#-:-KxQPT69vYxVL9DEWJ5m:b-4e1i8t)*

**Comment by dhalperi** [comment]
:lgtm:

---

Reviewed 4 of 61 files at r1, 21 of 29 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/pom.xml, line 137 at r2](https://reviewable.io:443/reviews/batfish/batfish/615#-KxTigarz909QSCFrkbN:-KxTigarz909QSCFrkbO:b-nw3h3j) ([raw file](https://github.com/batfish/batfish/blob/64c54a2bbe755867a01fe4ca624d1a171257db19/projects/pom.xml#L137)):*
> ```XML
>             <excludeRoots>
>               <excludeRoot>target/generated-sources</excludeRoot>
>               <excludeRoot>target/generated-test-sources</excludeRoot>
> ```

Note to self: there's something like `${project.build.dir}` that you're supposed to use instead of `target` here (, he thinks).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/615#-:-KxTlIfarS6e9C0uWuCJ:bnfp4nl)*

**Comment by dhalperi** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/pom.xml, line 137 at r2](https://reviewable.io:443/reviews/batfish/batfish/615#-KxTigarz909QSCFrkbN:-KxTlg2P4_N7yiRx-adv:b-gio5e) ([raw file](https://github.com/batfish/batfish/blob/64c54a2bbe755867a01fe4ca624d1a171257db19/projects/pom.xml#L137)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Note to self: there's something like `${project.build.dir}` that you're supposed to use instead of `target` here (, he thinks).
</blockquote></details>

`${project.build.directory}` is the right answer.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/615)*

**Comment by arifogel** [comment]
Review status: 47 of 48 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/pom.xml, line 137 at r2](https://reviewable.io:443/reviews/batfish/batfish/615#-KxTigarz909QSCFrkbN:-KxTqC4TdxtxgQLS-pf2:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/64c54a2bbe755867a01fe4ca624d1a171257db19/projects/pom.xml#L137)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

`${project.build.directory}` is the right answer.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/615)*

**Comment by dhalperi** [comment]
:lgtm:

---

Review status: 47 of 48 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/615#-:-KxTqUuEyHGWuyV6xXDZ:bnfp4nl)*

**Comment by dhalperi** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/615)*

**Pull request merged**
