### PR TITLE
Check status for all incomplete, assigned tasks

### LINKED ISSUE #775: Assigned work items are not checked in parallel
When multiple assigned work items are on the incomplete work queue, only the first is checked on by the coordinator.  The others are ignored until the first is no longer assigned.

This means that parallel work loads are effectively serialized.

### PR DESCRIPTION
**Pull request by sfraint**
Updated checkTasks in the work manager to check on all incomplete, assigned work (and updated the work queue manager to support providing a list of these work items).

This fixes #775 where only the first incomplete, assigned work item is checked.

---
This change is [Reviewable](https://reviewable.io/reviews/batfish/batfish/777)

### CODE REVIEW

**Comment by arifogel** [comment]
Test?

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/777#-:-L0MjRlOqZf9HNCwm9hl:b-80jztk)*

**Comment by arifogel** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, line 248 at r1](https://reviewable.io:443/reviews/batfish/batfish/777#-L0MjjaUJepgUfKThI0r:-L0MjjaVdFo5ZSIDJ8cE:b-b3e5i4) ([raw file](https://github.com/batfish/batfish/blob/06d8dc52e95c75812fa0e6fe65cc2110dd258d23/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java#L248)):*
> ```Java
>           _logger.error("WM:CheckWork no assigned worker for " + work + "\n");
>           _workQueueMgr.makeWorkUnassigned(work);
>           return;
> ```

It seems to me that you shouldn't return here when `assignedWorker` is null the first time. That is, why do you not check the other work?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/777)*

**Comment by sfraint** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, line 248 at r1](https://reviewable.io:443/reviews/batfish/batfish/777#-L0MjjaUJepgUfKThI0r:-L0MknpI9J0ywOQCgetO:b59eyag) ([raw file](https://github.com/batfish/batfish/blob/06d8dc52e95c75812fa0e6fe65cc2110dd258d23/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java#L248)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

It seems to me that you shouldn't return here when `assignedWorker` is null the first time. That is, why do you not check the other work?
</blockquote></details>

Right, this should continue instead of return

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/777)*

**Comment by arifogel** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/777)*

**Comment by arifogel** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, line 248 at r1](https://reviewable.io:443/reviews/batfish/batfish/777#-L0MjjaUJepgUfKThI0r:-L0MnIHaM-tCIdvKPT7b:b-nwmxw5) ([raw file](https://github.com/batfish/batfish/blob/06d8dc52e95c75812fa0e6fe65cc2110dd258d23/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java#L248)):*
<details><summary><i>Previously, sfraint wrote…</i></summary><blockquote>

Right, this should continue instead of return
</blockquote></details>

Unresolving

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/777)*

**Comment by dhalperi** [comment]
*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkQueueMgr.java, line 6 at r1](https://reviewable.io:443/reviews/batfish/batfish/777#-L0ModP_W-gCjc--gmm5:-L0ModP_W-gCjc--gmm6:bjz3wf4) ([raw file](https://github.com/batfish/batfish/blob/06d8dc52e95c75812fa0e6fe65cc2110dd258d23/projects/coordinator/src/main/java/org/batfish/coordinator/WorkQueueMgr.java#L6)):*
> ```Java
> import java.util.List;
> import java.util.UUID;
> import javax.annotation.Nullable;
> ```

javax is a stupid name.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/777)*

**Comment by sfraint** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkQueueMgr.java, line 6 at r1](https://reviewable.io:443/reviews/batfish/batfish/777#-L0ModP_W-gCjc--gmm5:-L0MoktSobnEU9t8aKMJ:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/06d8dc52e95c75812fa0e6fe65cc2110dd258d23/projects/coordinator/src/main/java/org/batfish/coordinator/WorkQueueMgr.java#L6)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

javax is a stupid name.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/777)*

**Comment by dhalperi** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/777#-:-L0MpJq7Esy_UFisnuXt:bnfp4nl)*

**Comment by dhalperi** [comment]
*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkQueueMgr.java, line 146 at r1](https://reviewable.io:443/reviews/batfish/batfish/777#-L0MpGBYe2FOthrfuyi0:-L0MpGBYe2FOthrfuyi1:b-g98wmo) ([raw file](https://github.com/batfish/batfish/blob/06d8dc52e95c75812fa0e6fe65cc2110dd258d23/projects/coordinator/src/main/java/org/batfish/coordinator/WorkQueueMgr.java#L146)):*
> ```Java
>       if (work.getStatus() == WorkStatusCode.ASSIGNED) {
>         work.setStatus(WorkStatusCode.CHECKINGSTATUS);
>         workToCheck.add(work);
> ```

workToCheck is checky.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/777)*

**Comment by dhalperi** [comment]
*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkQueueMgr.java, line 144 at r1](https://reviewable.io:443/reviews/batfish/batfish/777#-L0MqDnQY_AvvDDCEBaW:-L0MqDnQY_AvvDDCEBaX:b-mar72r) ([raw file](https://github.com/batfish/batfish/blob/06d8dc52e95c75812fa0e6fe65cc2110dd258d23/projects/coordinator/src/main/java/org/batfish/coordinator/WorkQueueMgr.java#L144)):*
> ```Java
>     List<QueuedWork> workToCheck = new ArrayList<>();
>     for (QueuedWork work : _queueIncompleteWork) {
>       if (work.getStatus() == WorkStatusCode.ASSIGNED) {
> ```

OK assigned

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/777)*

**Comment by sfraint** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkQueueMgr.java, line 144 at r1](https://reviewable.io:443/reviews/batfish/batfish/777#-L0MqDnQY_AvvDDCEBaW:-L0MqOCzsypsG5Ki6Xy1:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/06d8dc52e95c75812fa0e6fe65cc2110dd258d23/projects/coordinator/src/main/java/org/batfish/coordinator/WorkQueueMgr.java#L144)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

OK assigned
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/777)*

**Comment by dhalperi** [comment]
*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, line 248 at r1](https://reviewable.io:443/reviews/batfish/batfish/777#-L0MjjaUJepgUfKThI0r:-L0Mqy7eQwFXKxlNPX9A:bsofdpc) ([raw file](https://github.com/batfish/batfish/blob/06d8dc52e95c75812fa0e6fe65cc2110dd258d23/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java#L248)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Unresolving
</blockquote></details>

OK Should be unresolved

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/777)*

**Comment by dhalperi** [comment]
*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, line 254 at r1](https://reviewable.io:443/reviews/batfish/batfish/777#-L0MrBka2Ahgu7deCw9d:-L0MrBka2Ahgu7deCw9e:brc0fnj) ([raw file](https://github.com/batfish/batfish/blob/06d8dc52e95c75812fa0e6fe65cc2110dd258d23/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java#L254)):*
> ```Java
>     } catch (Exception e) {
>       _logger.error("Got exception in checkTasks: " + e.getMessage());
>     }
> ```

OK sdfsdf

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/777)*

**Comment by arifogel** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, line 248 at r1](https://reviewable.io:443/reviews/batfish/batfish/777#-L0MjjaUJepgUfKThI0r:-L0QFEKCTgQ460kD_hw3:b-m1ge8e) ([raw file](https://github.com/batfish/batfish/blob/06d8dc52e95c75812fa0e6fe65cc2110dd258d23/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java#L248)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

OK fdfd
</blockquote></details>

Unresolving. Please only real responses now (when progress has been made).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/777)*

**Comment by arifogel** [comment]
I'm not clear on what behavior is being tested. Please add comments as requested.

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkQueueMgr.java, line 140 at r2](https://reviewable.io:443/reviews/batfish/batfish/777#-L0eqBvzkszIFBmDeZuG:-L0eqBvzkszIFBmDeZuH:b-g0xxdh) ([raw file](https://github.com/batfish/batfish/blob/d557feb68a5d81dfe1806308ff84e730190c4b33/projects/coordinator/src/main/java/org/batfish/coordinator/WorkQueueMgr.java#L140)):*
> ```Java
>   }
> 
>   public List<QueuedWork> getWorkForChecking() {
> ```

If you are going to bother to remove the `@Nullable` annotation, why not replace it with `@Nonnull` or whatever the correct replacement is?

---

*[projects/coordinator/src/test/java/org/batfish/coordinator/WorkQueueMgrTest.java, line 71 at r2](https://reviewable.io:443/reviews/batfish/batfish/777#-L0eqeWQD84WxdDqB-Y2:-L0eqeWR0RXZlmY-bDfJ:bw4wy2r) ([raw file](https://github.com/batfish/batfish/blob/d557feb68a5d81dfe1806308ff84e730190c4b33/projects/coordinator/src/test/java/org/batfish/coordinator/WorkQueueMgrTest.java#L71)):*
> ```Java
>     workQueueMgr.queueUnassignedWork(work2);
>     workToCheck = workQueueMgr.getWorkForChecking();
>     assertThat(workToCheck.size(), equalTo(0));
> ```

Assertion should be separated by at least one newline from setup code, and should have explanatory comment.

---

*[projects/coordinator/src/test/java/org/batfish/coordinator/WorkQueueMgrTest.java, line 75 at r2](https://reviewable.io:443/reviews/batfish/batfish/777#-L0eqjQd69W6DT3QwBzn:-L0eqjQeHqpkg5KbiGH_:bw4wy2r) ([raw file](https://github.com/batfish/batfish/blob/d557feb68a5d81dfe1806308ff84e730190c4b33/projects/coordinator/src/test/java/org/batfish/coordinator/WorkQueueMgrTest.java#L75)):*
> ```Java
>     work2.setStatus(WorkStatusCode.ASSIGNED);
>     workToCheck = workQueueMgr.getWorkForChecking();
>     assertThat(workToCheck.size(), equalTo(1));
> ```

Assertion should be separated by at least one newline from setup code, and should have explanatory comment.

---

*[projects/coordinator/src/test/java/org/batfish/coordinator/WorkQueueMgrTest.java, line 81 at r2](https://reviewable.io:443/reviews/batfish/batfish/777#-L0eqnehB7RyEaW4DIpn:-L0eqnehB7RyEaW4DIpo:bw4wy2r) ([raw file](https://github.com/batfish/batfish/blob/d557feb68a5d81dfe1806308ff84e730190c4b33/projects/coordinator/src/test/java/org/batfish/coordinator/WorkQueueMgrTest.java#L81)):*
> ```Java
>     assertThat(work2.getStatus(), equalTo(WorkStatusCode.CHECKINGSTATUS));
>     workToCheck = workQueueMgr.getWorkForChecking();
>     assertThat(workToCheck.size(), equalTo(0));
> ```

Assertion should be separated by at least one newline from setup code, and should have explanatory comment.

---

*[projects/coordinator/src/test/java/org/batfish/coordinator/WorkQueueMgrTest.java, line 86 at r2](https://reviewable.io:443/reviews/batfish/batfish/777#-L0eqo06_egq8_etlZbi:-L0eqo06_egq8_etlZbj:bw4wy2r) ([raw file](https://github.com/batfish/batfish/blob/d557feb68a5d81dfe1806308ff84e730190c4b33/projects/coordinator/src/test/java/org/batfish/coordinator/WorkQueueMgrTest.java#L86)):*
> ```Java
>     work2.setStatus(WorkStatusCode.ASSIGNED);
>     workToCheck = workQueueMgr.getWorkForChecking();
>     assertThat(workToCheck.size(), equalTo(2));
> ```

Assertion should be separated by at least one newline from setup code, and should have explanatory comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/777#-:-L0eqrLWGWgyawfvzhF4:bhcipx6)*

**Comment by arifogel** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[projects/coordinator/src/test/java/org/batfish/coordinator/WorkQueueMgrTest.java, line 66 at r3](https://reviewable.io:443/reviews/batfish/batfish/777#-L0k4sjgEWPccVG5GKQB:-L0k4sjhOI5r72TfAxl6:b-cy5p1v) ([raw file](https://github.com/batfish/batfish/blob/f615330360b127a0ab279b318dda192b3dc1c78e/projects/coordinator/src/test/java/org/batfish/coordinator/WorkQueueMgrTest.java#L66)):*
> ```Java
> 
>     // Make sure getWorkForChecking() returns no elements when the incomplete work queue is empty
>     assertThat(workToCheck.size(), equalTo(0));
> ```

Look in `org.hamcrest.Matchers` for an appropriate matcher on a `List` (or `Collection`) instead of checking that size is literally `0`. This will give you better error messages.
That is, do:
`assertThat(workToCheck, isEmptyCollection())` or something like that. There are a ton of `Collection`-related matchers that are all better than making an assertion about the size. To see what I mean about error messages, try changing the value in the `equalTo` and seeing what error message pops out. It will be relatively unhelpful.

---

*[projects/coordinator/src/test/java/org/batfish/coordinator/WorkQueueMgrTest.java, line 75 at r3](https://reviewable.io:443/reviews/batfish/batfish/777#-L0k5XdgHTkKNPzSDqPH:-L0k5XdhOx9kVvo0dXBl:b4jw96z) ([raw file](https://github.com/batfish/batfish/blob/f615330360b127a0ab279b318dda192b3dc1c78e/projects/coordinator/src/test/java/org/batfish/coordinator/WorkQueueMgrTest.java#L75)):*
> ```Java
> 
>     // Make sure unassigned items on the queue are not returned in getWorkForChecking()
>     assertThat(workToCheck.size(), equalTo(0));
> ```

Look in `org.hamcrest.Matchers` for an appropriate matcher on a `List` (or `Collection`) instead of checking that size is literally `0`.

---

*[projects/coordinator/src/test/java/org/batfish/coordinator/WorkQueueMgrTest.java, line 82 at r3](https://reviewable.io:443/reviews/batfish/batfish/777#-L0k5eMtvS_cfsbl0D3q:-L0k5eMtvS_cfsbl0D3r:bjmnai6) ([raw file](https://github.com/batfish/batfish/blob/f615330360b127a0ab279b318dda192b3dc1c78e/projects/coordinator/src/test/java/org/batfish/coordinator/WorkQueueMgrTest.java#L82)):*
> ```Java
>     // Make sure only one item is returned from getWorkForChecking() when there is only one assigned
>     // item on the queue
>     assertThat(workToCheck.size(), equalTo(1));
> ```

Look in `org.hamcrest.Matchers` for an appropriate matcher on a `List` (or `Collection`) instead of checking that size is literally `1`. In this case, probably something like `hasSize`.

---

*[projects/coordinator/src/test/java/org/batfish/coordinator/WorkQueueMgrTest.java, line 85 at r3](https://reviewable.io:443/reviews/batfish/batfish/777#-L0k5pMfBqIAIETIY1Uq:-L0k5pMfBqIAIETIY1Ur:b-fhyqyc) ([raw file](https://github.com/batfish/batfish/blob/f615330360b127a0ab279b318dda192b3dc1c78e/projects/coordinator/src/test/java/org/batfish/coordinator/WorkQueueMgrTest.java#L85)):*
> ```Java
> 
>     // Make sure the correct item was returned
>     assertThat(workToCheck.get(0), equalTo(work2));
> ```

If this should be true by reference, use `sameReference` or something like that instead of `equalTo`. That way you do don't need to worry about implementation of `equals` for the return type(s) of `work2` and `workToCheck.get(0)`.
If not, this is fine.

---

*[projects/coordinator/src/test/java/org/batfish/coordinator/WorkQueueMgrTest.java, line 90 at r3](https://reviewable.io:443/reviews/batfish/batfish/777#-L0k6HDBPq5PtSKmX8EH:-L0k6HDBPq5PtSKmX8EI:byct3ci) ([raw file](https://github.com/batfish/batfish/blob/f615330360b127a0ab279b318dda192b3dc1c78e/projects/coordinator/src/test/java/org/batfish/coordinator/WorkQueueMgrTest.java#L90)):*
> ```Java
>     assertThat(work2.getStatus(), equalTo(WorkStatusCode.CHECKINGSTATUS));
> 
>     workToCheck = workQueueMgr.getWorkForChecking();
> ```

(Optional, really) A matter of style really, but I don't like interspersed assertions and setup code. Consider making multiple  immutable copies (e.g. `ImmutableList.copyOf(workToCheck)`)of `workToCheck` at different points in time, and then having all your assertions be on those immutable copies.

---

*[projects/coordinator/src/test/java/org/batfish/coordinator/WorkQueueMgrTest.java, line 98 at r3](https://reviewable.io:443/reviews/batfish/batfish/777#-L0k6yiK9vChbV-EFH1P:-L0k6yiLLcTSSbVAKyam:b-c5nz3y) ([raw file](https://github.com/batfish/batfish/blob/f615330360b127a0ab279b318dda192b3dc1c78e/projects/coordinator/src/test/java/org/batfish/coordinator/WorkQueueMgrTest.java#L98)):*
> ```Java
>     work1.setStatus(WorkStatusCode.ASSIGNED);
>     work2.setStatus(WorkStatusCode.ASSIGNED);
>     workToCheck = workQueueMgr.getWorkForChecking();
> ```

(Optional, really) If you decide to separate assertions entirely from setup code, you might actually need to make distinct work items / work list for this check since these items get modified.

---

*[projects/coordinator/src/test/java/org/batfish/coordinator/WorkQueueMgrTest.java, line 101 at r3](https://reviewable.io:443/reviews/batfish/batfish/777#-L0k7GUsK5b_aLJ-L1Sm:-L0k7GUsK5b_aLJ-L1Sn:b4jwaod) ([raw file](https://github.com/batfish/batfish/blob/f615330360b127a0ab279b318dda192b3dc1c78e/projects/coordinator/src/test/java/org/batfish/coordinator/WorkQueueMgrTest.java#L101)):*
> ```Java
> 
>     // With multiple assigned items now queued, getWorkForChecking() should return multiple items
>     assertThat(workToCheck.size(), equalTo(2));
> ```

Look in `org.hamcrest.Matchers` for an appropriate matcher on a `List` (or `Collection`) instead of checking that size is literally `2`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/777)*

**Comment by arifogel** [comment]
:lgtm: but you have to resolve conflicts.

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/777#-:-L0kcaWJyzMZwaCtknMF:b-2rat4z)*

**Comment by arifogel** [comment]
Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/777)*

**Pull request merged**
