### PR TITLE
Checkpointing NxOs parser+extractor+conversion work

### PR DESCRIPTION
**Pull request by dhalperi**
Still disabled by default.

A lot of new extractions.
A lot of new conversions.
A few new unit tests.

### CODE REVIEW

**Comment by dhalperi** [comment]
*[a discussion](https://reviewable.io/reviews/batfish/batfish/1354#-LC693G4AoF5pNGG63XL:-LC693G4AoF5pNGG63XM:baac7ur) (no related file):*
Need to remove the printlns in unused detection stuff.

Need to fix broken unused refernees.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1354)*

**Comment by dhalperi** [comment]
@arifogel This checkpoint is ready for review.

Still not flipping the flag to use the new parser to true, there's quite a few needed unit tests before we can do that. But extraction and conversion are mostly on par with the existing Cisco BGP handling, and while not complete this is almost certainly a strong improvement.

**Comment by arifogel** [comment]
Reviewed 15 of 27 files at r1, 5 of 9 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 1878 at r3](https://reviewable.io/reviews/batfish/batfish/1354#-LCUmXp3EI3biL7ZYzrZ:-LCUmXp3EI3biL7ZYzr_:b5ss3k8) ([raw file](https://github.com/batfish/batfish/blob/dad57bf54cd58c3c5a49804047539fb9f974b14d/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L1878)):*
> ```Java
>       int line = ctx.mapname.getStart().getLine();
>       _configuration.referenceStructure(
>           ROUTE_MAP, routeMap, CiscoStructureUsage.BGP_NEIGHBOR_REMOTE_AS_ROUTE_MAP, line);
> ```

Either static import type AND usage, or neither. Maybe it would be useful to add checkstyle rule for `XXXStructure{Usage,Type}`

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 1514 at r3](https://reviewable.io/reviews/batfish/batfish/1354#-LCUnkzd3IEBL6J4k6UQ:-LCUnkzd3IEBL6J4k6UR:b7wm8eq) ([raw file](https://github.com/batfish/batfish/blob/dad57bf54cd58c3c5a49804047539fb9f974b14d/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L1514)):*
> ```Java
>                         new Not(new MatchProtocol(RoutingProtocol.IBGP)),
>                         // TODO: ban aggregates?
>                         new Not(new MatchProtocol(RoutingProtocol.AGGREGATE)),
> ```

Seems OK to me. You can probably remove TODO comment. Applies elsewhere.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/nx/CiscoNxBgpVrfAddressFamilyConfiguration.java, line 39 at r3](https://reviewable.io/reviews/batfish/batfish/1354#-LCUq06PEXDVz93FMuPJ:-LCUq06QD1p_8Zk7KliL:bt1dco3) ([raw file](https://github.com/batfish/batfish/blob/dad57bf54cd58c3c5a49804047539fb9f974b14d/projects/batfish/src/main/java/org/batfish/representation/cisco/nx/CiscoNxBgpVrfAddressFamilyConfiguration.java#L39)):*
> ```Java
>   public Map<Prefix, CiscoNxBgpVrfAddressFamilyAggregateNetworkConfiguration>
>       getAggregateNetworks() {
>     return Collections.unmodifiableMap(_aggregateNetworks);
> ```

I've been avoiding `Collections.unmodifiableMap` in favor of `ImmutableMap.copyOf`. I imagine the first is faster if you don't later copy, but also uses more space in the end. Do you have a strong opinion either way which to use?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1354)*

**Comment by dhalperi** [comment]
Review status: 17 of 21 files reviewed at latest revision, 3 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 1878 at r3](https://reviewable.io/reviews/batfish/batfish/1354#-LCUmXp3EI3biL7ZYzrZ:-LCVAsE7A3TZ0u_Nifnm:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/dad57bf54cd58c3c5a49804047539fb9f974b14d/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L1878)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Either static import type AND usage, or neither. Maybe it would be useful to add checkstyle rule for `XXXStructure{Usage,Type}`
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 1514 at r3](https://reviewable.io/reviews/batfish/batfish/1354#-LCUnkzd3IEBL6J4k6UQ:-LCV1Vce5hzx9c3emH8f:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/dad57bf54cd58c3c5a49804047539fb9f974b14d/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L1514)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Seems OK to me. You can probably remove TODO comment. Applies elsewhere.
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/nx/CiscoNxBgpVrfAddressFamilyConfiguration.java, line 39 at r3](https://reviewable.io/reviews/batfish/batfish/1354#-LCUq06PEXDVz93FMuPJ:-LCV1W_LEEMVd28NnVY4:bpipfv0) ([raw file](https://github.com/batfish/batfish/blob/dad57bf54cd58c3c5a49804047539fb9f974b14d/projects/batfish/src/main/java/org/batfish/representation/cisco/nx/CiscoNxBgpVrfAddressFamilyConfiguration.java#L39)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

I've been avoiding `Collections.unmodifiableMap` in favor of `ImmutableMap.copyOf`. I imagine the first is faster if you don't later copy, but also uses more space in the end. Do you have a strong opinion either way which to use?
</blockquote></details>

Collections.unmodifiableFoo:
* takes constant time
* uses constant space
* reflects updates made to the original
* does not allow updates to the return value

ImmutableFoo.copyOf:
* takes constant-time and uses zero space if original is an ImmutableFoo
* takes at least linear time and uses linear space otherwise
* does not reflect updates made to the original
* does not allow updates to the return value

new JavaUtilFoo:
* takes at least linear time and space
* does not reflect writes to original
* allows writes to return value

All have their uses; it didn't super seem to matter here as no one should ever be copying the result. I picked the lighter-weight version to reject writes somewhat arbitrarily.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1354)*

**Comment by arifogel** [comment]
Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish/src/test/resources/org/batfish/grammar/cisco/testrigs/nxos-bgp-default-route/configs/ios-bgp-listener, line 1 at r4](https://reviewable.io/reviews/batfish/batfish/1354#-LCVN9ybEVpo1upPD1s4:-LCVN9yc9pNDxhI9UuiQ:bopwbxw) ([raw file](https://github.com/batfish/batfish/blob/4173e2d2a5452c229e551094051ff0d1dd1cf33a/projects/batfish/src/test/resources/org/batfish/grammar/cisco/testrigs/nxos-bgp-default-route/configs/ios-bgp-listener#L1)):*
> ```
> ! Real config from iOS emulator in GNS3, edited heavily to remove unrelated bits.
> ```

Not an Apple device. Should be `IOS`. Applies elsewhere

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1354)*

**Comment by dhalperi** [comment]
Review status: 19 of 21 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/test/resources/org/batfish/grammar/cisco/testrigs/nxos-bgp-default-route/configs/ios-bgp-listener, line 1 at r4](https://reviewable.io/reviews/batfish/batfish/1354#-LCVN9ybEVpo1upPD1s4:-LCVNbOF0aLXwQ77RuGi:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/4173e2d2a5452c229e551094051ff0d1dd1cf33a/projects/batfish/src/test/resources/org/batfish/grammar/cisco/testrigs/nxos-bgp-default-route/configs/ios-bgp-listener#L1)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Not an Apple device. Should be `IOS`. Applies elsewhere
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1354)*

**Comment by arifogel** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1354#-:-LCVOqinB2AIhnUwrKnQ:bnfp4nl)*

**Pull request merged**
