### PR TITLE
IOS-XR: fix activation of bundle-ether subinterfaces

### PR DESCRIPTION
**Pull request by dhalperi**
They need to be marked as aggregate children, not aggregates themselves --
otherwise, they will be deactivate for having no physical interfaces.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6760)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @arifogel, @corinaminer, and @sfraint)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java, line 641 at r1](https://reviewable.io/reviews/batfish/batfish/6760#-MWM4bTlAa9V7wmnJ2ZM:-MWM4bTlAa9V7wmnJ2ZN:b-i2vdsh) ([raw file](https://github.com/batfish/batfish/blob/6e7782f402ff25a399cc22c55c3e2037665563ac/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/Interface.java#L641)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>       if (name.contains(".")) {
>         // Subinterface
>         return InterfaceType.AGGREGATE_CHILD;
>       } else {
>         return InterfaceType.AGGREGATED;
>       }
> ```
</details>

FYI this mirrors identical code for Port-channels below.

**Review by arifogel — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6760)* status: all files reviewed, 1 unresolved discussion (waiting on @corinaminer, @dhalperi, and @sfraint)

___
*[projects/batfish/src/test/java/org/batfish/grammar/cisco_xr/XrGrammarTest.java, line 215 at r1](https://reviewable.io/reviews/batfish/batfish/6760#-MWQ7DBb7-wfv_CTTdTY:-MWQ7DBb7-wfv_CTTdTZ:b-ot35tn) ([raw file](https://github.com/batfish/batfish/blob/6e7782f402ff25a399cc22c55c3e2037665563ac/projects/batfish/src/test/java/org/batfish/grammar/cisco_xr/XrGrammarTest.java#L215)):*
> ```Java
> 
>   @Test
>   public void testBundleEtherSubInterfaces() {
> ```

This is fine, but would be nice to also have an interface (triple?)  that does not get activated.

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6760)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @arifogel, @corinaminer, and @sfraint)

___
*[projects/batfish/src/test/java/org/batfish/grammar/cisco_xr/XrGrammarTest.java, line 215 at r1](https://reviewable.io/reviews/batfish/batfish/6760#-MWQ7DBb7-wfv_CTTdTY:-MWQIGf69fG-toq6VbBk:b-oq12xi) ([raw file](https://github.com/batfish/batfish/blob/6e7782f402ff25a399cc22c55c3e2037665563ac/projects/batfish/src/test/java/org/batfish/grammar/cisco_xr/XrGrammarTest.java#L215)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

This is fine, but would be nice to also have an interface (triple?)  that does not get activated.
</blockquote></details>

Done, TAL.

**Review by arifogel — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6760#-:-MWQTM-Y8rvcwcJ5-LHU:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer and @sfraint)

**Pull request merged**
