### PR TITLE
fortios grammar string processing

### PR DESCRIPTION
**Pull request by arifogel**
- properly process:
  - single-quoted strings
  - double-quoted strings, and escape sequences therein
  - unquoted escape sequences
  - line continuations
  - concatenated sequences of the above
- test via replacemsg, whose buffer accepts arbitrary
strings
- also add validation for device hostname to showcase strings with
  special requirements

### CODE REVIEW

**Review by sfraint — COMMENTED** [review]
> Reviewed 9 of 11 files at r1, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6662)* status: all files reviewed, 5 unresolved discussions (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_common.g4, line 43 at r2](https://reviewable.io/reviews/batfish/batfish/6662#-MUQgGay9nePKtWtWpmf:-MUQgGaz-h8cB1QnfZqG:b-nh82m) ([raw file](https://github.com/batfish/batfish/blob/3b6d3aa5b650caeee41544f3d04d8cacd90b9da4/projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_common.g4#L43)):*
> ```
> word: str;
> // can include whitespace, newlines, html tags, etc.
> str: (double_quoted_string | single_quoted_string | UNQUOTED_ESCAPED_CHAR | WORD)+;
> ```
at first glance, it is a little weird that `word` can contain multiple `WORD` tokens

is that possible / intended?
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 108 at r3](https://reviewable.io/reviews/batfish/batfish/6662#-MURDn7Y-6COiaSnJcJx:-MURDn7Y-6COiaSnJcJy:b-lryzos) ([raw file](https://github.com/batfish/batfish/blob/a68ec3f5bb3a4dcaa5e9d7c53f2a2dfd56bbcdc6/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L108)):*
> ```
>   private @Nonnull String toString(Replacemsg_major_typeContext ctx) {
>     return ctx.getText();
>   }
> ```
nit: does this buy us anything over just in-lining `.getText()` for this context?

I guess it looks a little cleaner
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 112 at r3](https://reviewable.io/reviews/batfish/batfish/6662#-MURF3VjCjXayl1W0UOQ:-MURF3VjCjXayl1W0UOR:b-w9fwq7) ([raw file](https://github.com/batfish/batfish/blob/a68ec3f5bb3a4dcaa5e9d7c53f2a2dfd56bbcdc6/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L112)):*
<details><summary><i alt="summary">Quoted 13 lines of code…</i></summary>

> ```
>   private @Nonnull Optional<String> toString(
>       ParserRuleContext messageCtx, Device_hostnameContext ctx) {
>     Optional<String> maybeHostname = toString(messageCtx, ctx.word());
>     if (!maybeHostname.isPresent()) {
>       return Optional.empty();
>     }
>     String hostname = maybeHostname.get();
>     if (!DEVICE_HOSTNAME_PATTERN.matcher(hostname).matches()) {
>       warn(messageCtx, String.format("Invalid characters in hostname: %s", hostname));
>       return Optional.empty();
>     }
>     return Optional.of(hostname);
>   }
> ```
</details>

will this be a common pattern for other named values?

if so, should we have a more reusable function for this? (even if it is more like the `toInteger` conversions we do elsewhere, where it could take a descriptor string like `hostname` and an acceptable "space" of chars or regex)
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 180 at r3](https://reviewable.io/reviews/batfish/batfish/6662#-MURFgln5Q9HpeJGzwN4:-MURFgln5Q9HpeJGzwN5:bo2fxco) ([raw file](https://github.com/batfish/batfish/blob/a68ec3f5bb3a4dcaa5e9d7c53f2a2dfd56bbcdc6/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L180)):*
<details><summary><i alt="summary">Quoted 10 lines of code…</i></summary>

> ```
>   private static @Nonnull String toString(Double_quoted_stringContext ctx) {
>     if (ctx.text == null) {
>       return "";
>     }
>     String quotedText = ctx.text.getText();
>     return ESCAPED_CHAR_PATTERN.matcher(quotedText).replaceAll("$1");
>   }
>   private static @Nonnull String toString(Single_quoted_stringContext ctx) {
>     return ctx.text != null ? ctx.text.getText() : "";
>   }
> ```
</details>

confirming: single-quoted strings don't have/support escape chars?
___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosConfiguration.java, line 38 at r2](https://reviewable.io/reviews/batfish/batfish/6662#-MUUewek4pTzUMcoxi_H:-MUUewelEKSPrVGDAY-k:b-qbpjkh) ([raw file](https://github.com/batfish/batfish/blob/3b6d3aa5b650caeee41544f3d04d8cacd90b9da4/projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosConfiguration.java#L38)):*
> ```
>   public @Nonnull Map<String, Map<String, Replacemsg>> getReplacemsgs() {
>     return _replacemsgs;
>   }
> ```
comment/docstring what the map is mapping? e.g. `// Map of major type to minor type to replacemsg`
___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/Replacemsg.java, line 6 at r2](https://reviewable.io/reviews/batfish/batfish/6662#-MUUfMwx9yMp0isNvIUW:-MUUfMwx9yMp0isNvIUX:bwtytld) ([raw file](https://github.com/batfish/batfish/blob/3b6d3aa5b650caeee41544f3d04d8cacd90b9da4/projects/batfish/src/main/java/org/batfish/representation/fortios/Replacemsg.java#L6)):*
> ```
> public final class Replacemsg implements Serializable {
> ```
is there anything that needs to be said in a docstring for this?

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6662)* status: all files reviewed, 5 unresolved discussions (waiting on @arifogel, @corinaminer, and @sfraint)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_common.g4, line 43 at r2](https://reviewable.io/reviews/batfish/batfish/6662#-MUQgGay9nePKtWtWpmf:-MUUlEno1Eth8VpEtu79:b-46bccl) ([raw file](https://github.com/batfish/batfish/blob/3b6d3aa5b650caeee41544f3d04d8cacd90b9da4/projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_common.g4#L43)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
> word: str;
> // can include whitespace, newlines, html tags, etc.
> str: (double_quoted_string | single_quoted_string | UNQUOTED_ESCAPED_CHAR | WORD)+;
> ```
at first glance, it is a little weird that `word` can contain multiple `WORD` tokens

is that possible / intended?
</blockquote></details>

`str`: single string argument that may span multiple lines, contain whitespace, etc. 
`word`: A contiguous sequence of quoted/unquoted strings that contains no whitespace or newlines.
`WORD`: A contiguous sequence of unquoted non-whitespace chars.
Can you suggest better names?
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 108 at r3](https://reviewable.io/reviews/batfish/batfish/6662#-MURDn7Y-6COiaSnJcJx:-MUUjAGNCxzjm4KAcYZh:b-p02qkz) ([raw file](https://github.com/batfish/batfish/blob/a68ec3f5bb3a4dcaa5e9d7c53f2a2dfd56bbcdc6/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L108)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
>   private @Nonnull String toString(Replacemsg_major_typeContext ctx) {
>     return ctx.getText();
>   }
> ```
nit: does this buy us anything over just in-lining `.getText()` for this context?

I guess it looks a little cleaner
</blockquote></details>

It centralizes conversion (there may be more rules in the future that include this rule).
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 112 at r3](https://reviewable.io/reviews/batfish/batfish/6662#-MURF3VjCjXayl1W0UOQ:-MUUk_0HEIYMcsZyfY5f:bkgq6q9) ([raw file](https://github.com/batfish/batfish/blob/a68ec3f5bb3a4dcaa5e9d7c53f2a2dfd56bbcdc6/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L112)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
>   private @Nonnull Optional<String> toString(
>       ParserRuleContext messageCtx, Device_hostnameContext ctx) {
>     Optional<String> maybeHostname = toString(messageCtx, ctx.word());
>     if (!maybeHostname.isPresent()) {
>       return Optional.empty();
>     }
>     String hostname = maybeHostname.get();
>     if (!DEVICE_HOSTNAME_PATTERN.matcher(hostname).matches()) {
>       warn(messageCtx, String.format("Invalid characters in hostname: %s", hostname));
>       return Optional.empty();
>     }
>     return Optional.of(hostname);
>   }
> ```
will this be a common pattern for other named values?

if so, should we have a more reusable function for this? (even if it is more like the `toInteger` conversions we do elsewhere, where it could take a descriptor string like `hostname` and an acceptable "space" of chars or regex)
</blockquote></details>

For strings that's harder if you want to give more specific feedback about why a string is valid. Let's try to pull out common stuff as it shows up in the next few PRs.
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 180 at r3](https://reviewable.io/reviews/batfish/batfish/6662#-MURFgln5Q9HpeJGzwN4:-MUUkxoJBTAUWyniAoKa:b-9m6wlo) ([raw file](https://github.com/batfish/batfish/blob/a68ec3f5bb3a4dcaa5e9d7c53f2a2dfd56bbcdc6/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L180)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
>   private static @Nonnull String toString(Double_quoted_stringContext ctx) {
>     if (ctx.text == null) {
>       return "";
>     }
>     String quotedText = ctx.text.getText();
>     return ESCAPED_CHAR_PATTERN.matcher(quotedText).replaceAll("$1");
>   }
>   private static @Nonnull String toString(Single_quoted_stringContext ctx) {
>     return ctx.text != null ? ctx.text.getText() : "";
>   }
> ```
confirming: single-quoted strings don't have/support escape chars?
</blockquote></details>

confirmed.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6662)* status: all files reviewed, 5 unresolved discussions (waiting on @arifogel, @corinaminer, and @sfraint)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_common.g4, line 43 at r2](https://reviewable.io/reviews/batfish/batfish/6662#-MUQgGay9nePKtWtWpmf:-MUUmlb87Wfu0e-KRBcy:b-sbxn5l) ([raw file](https://github.com/batfish/batfish/blob/3b6d3aa5b650caeee41544f3d04d8cacd90b9da4/projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_common.g4#L43)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

`str`: single string argument that may span multiple lines, contain whitespace, etc. 
`word`: A contiguous sequence of quoted/unquoted strings that contains no whitespace or newlines.
`WORD`: A contiguous sequence of unquoted non-whitespace chars.
Can you suggest better names?
</blockquote></details>

Sorry, `WORD` also excludes (unquoted) escape sequences

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6662)* status: all files reviewed, 3 unresolved discussions (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_common.g4, line 43 at r2](https://reviewable.io/reviews/batfish/batfish/6662#-MUQgGay9nePKtWtWpmf:-MUUoKNn6z-kfJ6ai3Km:b-ie78bp) ([raw file](https://github.com/batfish/batfish/blob/3b6d3aa5b650caeee41544f3d04d8cacd90b9da4/projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_common.g4#L43)):*
```
word: str;
```
> str: single string argument that may span multiple lines, contain whitespace, etc.
> word: A contiguous sequence of quoted/unquoted strings that contains no whitespace or newlines.

if `word` is defined as `str` how can this be true?
or are you saying this is the case after enforcing limits on what can be in the `word` rule during configuration building?

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6662)* status: all files reviewed, 3 unresolved discussions (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_common.g4, line 43 at r2](https://reviewable.io/reviews/batfish/batfish/6662#-MUQgGay9nePKtWtWpmf:-MUUpNoPCv9NpHO1kjAc:bb283re) ([raw file](https://github.com/batfish/batfish/blob/3b6d3aa5b650caeee41544f3d04d8cacd90b9da4/projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_common.g4#L43)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

```
word: str;
```
> str: single string argument that may span multiple lines, contain whitespace, etc.
> word: A contiguous sequence of quoted/unquoted strings that contains no whitespace or newlines.

if `word` is defined as `str` how can this be true?
or are you saying this is the case after enforcing limits on what can be in the `word` rule during configuration building?

</blockquote></details>

I guess I don't immediately see why the `word` and `str` definitions can't be reversed, e.g. something more like this

```
str: word+;
word: (double_quoted_string | single_quoted_string | UNQUOTED_ESCAPED_CHAR | WORD);
```

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6662)* status: all files reviewed, 3 unresolved discussions (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_common.g4, line 43 at r2](https://reviewable.io/reviews/batfish/batfish/6662#-MUQgGay9nePKtWtWpmf:-MUUplf34Qz_cMxZ6KuF:b8i5svg) ([raw file](https://github.com/batfish/batfish/blob/3b6d3aa5b650caeee41544f3d04d8cacd90b9da4/projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_common.g4#L43)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

I guess I don't immediately see why the `word` and `str` definitions can't be reversed, e.g. something more like this

```
str: word+;
word: (double_quoted_string | single_quoted_string | UNQUOTED_ESCAPED_CHAR | WORD);
```

</blockquote></details>

oh, unless we need to allow things like `"foo"bar'baz'`

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6662)* status: 9 of 11 files reviewed, 1 unresolved discussion (waiting on @arifogel, @corinaminer, and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosConfiguration.java, line 38 at r2](https://reviewable.io/reviews/batfish/batfish/6662#-MUUewek4pTzUMcoxi_H:-MUVNZQA9R71RMK3Z4TL:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/3b6d3aa5b650caeee41544f3d04d8cacd90b9da4/projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosConfiguration.java#L38)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
>   public @Nonnull Map<String, Map<String, Replacemsg>> getReplacemsgs() {
>     return _replacemsgs;
>   }
> ```
comment/docstring what the map is mapping? e.g. `// Map of major type to minor type to replacemsg`
</blockquote></details>

done
___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/Replacemsg.java, line 6 at r2](https://reviewable.io/reviews/batfish/batfish/6662#-MUUfMwx9yMp0isNvIUW:-MUVNZwX3TEgKOhUTOd-:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/3b6d3aa5b650caeee41544f3d04d8cacd90b9da4/projects/batfish/src/main/java/org/batfish/representation/fortios/Replacemsg.java#L6)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
> public final class Replacemsg implements Serializable {
> ```
is there anything that needs to be said in a docstring for this?
</blockquote></details>

done

**Review by sfraint — COMMENTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6662)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel and @corinaminer)

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6662)* status: 7 of 11 files reviewed, 1 unresolved discussion (waiting on @corinaminer and @sfraint)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_common.g4, line 43 at r2](https://reviewable.io/reviews/batfish/batfish/6662#-MUQgGay9nePKtWtWpmf:-MUVj-Mq7VfGRtQbX7YB:bdm62hl) ([raw file](https://github.com/batfish/batfish/blob/3b6d3aa5b650caeee41544f3d04d8cacd90b9da4/projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_common.g4#L43)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

oh, unless we need to allow things like `"foo"bar'baz'`
</blockquote></details>

i hope this is more clear with the new lexer tokens.

**Review by sfraint — COMMENTED** [review]
> Reviewed 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6662)* status: all files reviewed, 2 unresolved discussions (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_common.g4, line 43 at r2](https://reviewable.io/reviews/batfish/batfish/6662#-MUQgGay9nePKtWtWpmf:-MUVog5X1-948o12Njqu:b4c9lyr) ([raw file](https://github.com/batfish/batfish/blob/3b6d3aa5b650caeee41544f3d04d8cacd90b9da4/projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_common.g4#L43)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

i hope this is more clear with the new lexer tokens.
</blockquote></details>

:thumbsup: 
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/FortiosLexer.g4, line 467 at r5](https://reviewable.io/reviews/batfish/batfish/6662#-MUVkruc2G4ZilSyw9iF:-MUVkruc2G4ZilSyw9iG:b95e1g1) ([raw file](https://github.com/batfish/batfish/blob/ae3796479236c49fb1ba73e35473d9856ad652a1/projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/FortiosLexer.g4#L467)):*
> ```
> M_Str_DOUBLE_QUOTE:
> ```
should these be `M_Str2_...`?
___
*[projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java, line 57 at r5](https://reviewable.io/reviews/batfish/batfish/6662#-MUVnz5f9cJ-Qa5961aw:-MUVnz5f9cJ-Qa5961ax:bct36qs) ([raw file](https://github.com/batfish/batfish/blob/ae3796479236c49fb1ba73e35473d9856ad652a1/projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java#L57)):*
<details><summary><i alt="summary">Quoted 12 lines of code…</i></summary>

> ```
>   @Test
>   public void testInvalidHostnameWithDotExtraction() {
>     String filename = "fortios_bad_hostname_dot";
>     // invalid hostname from config file is thrown away
>     assertThat(parseVendorConfig(filename).getHostname(), nullValue());
>   }
>   @Test
>   public void testInvalidHostnameWithWsExtraction() {
>     String filename = "fortios_bad_hostname_ws";
>     // invalid hostname from config file is thrown away
>     assertThat(parseVendorConfig(filename).getHostname(), nullValue());
>   }
> ```
</details>

should we also check the warnings here?

**Review by sfraint — COMMENTED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6662)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel and @corinaminer)

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6662)* status: 8 of 12 files reviewed, all discussions resolved (waiting on @corinaminer and @sfraint)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/FortiosLexer.g4, line 467 at r5](https://reviewable.io/reviews/batfish/batfish/6662#-MUVkruc2G4ZilSyw9iF:-MUVpgTT1TMu88CeyPUe:b-nev3m7) ([raw file](https://github.com/batfish/batfish/blob/ae3796479236c49fb1ba73e35473d9856ad652a1/projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/FortiosLexer.g4#L467)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
> M_Str_DOUBLE_QUOTE:
> ```
should these be `M_Str2_...`?
</blockquote></details>

yup, fixed
___
*[projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java, line 57 at r5](https://reviewable.io/reviews/batfish/batfish/6662#-MUVnz5f9cJ-Qa5961aw:-MUVumem1xiD0gt7OXun:b33fa5h) ([raw file](https://github.com/batfish/batfish/blob/ae3796479236c49fb1ba73e35473d9856ad652a1/projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java#L57)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
>   @Test
>   public void testInvalidHostnameWithDotExtraction() {
>     String filename = "fortios_bad_hostname_dot";
>     // invalid hostname from config file is thrown away
>     assertThat(parseVendorConfig(filename).getHostname(), nullValue());
>   }
>   @Test
>   public void testInvalidHostnameWithWsExtraction() {
>     String filename = "fortios_bad_hostname_ws";
>     // invalid hostname from config file is thrown away
>     assertThat(parseVendorConfig(filename).getHostname(), nullValue());
>   }
> ```
should we also check the warnings here?
</blockquote></details>

done, and removed redundant test and corresponding file.

**Review by sfraint — COMMENTED** [review]
> Reviewed 4 of 5 files at r7.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6662)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

**Pull request merged**
