### PR TITLE
Sonic acls

### PR DESCRIPTION
**Pull request by ratulm**

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 7 of 8 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7822)* status: all files reviewed, 7 unresolved discussions (waiting on @ratulm)

___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/AclRule.java, line 126 at r2](https://reviewable.io/reviews/batfish/batfish/7822#-Mr5M7WC6wqckVN7DE2R:-Mr5M7WD8zpI4ninRpMJ:b-1whix5) ([raw file](https://github.com/batfish/batfish/blob/84a021ff79df1b66f26191e8c4bc1b59529db64c/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/AclRule.java#L126)):*
> ```Java
>   public int hashCode() {
>     return Objects.hash(
>         _ipProtocol, _dstIp, _srcIp, _l4DstPort, _l4SrcPort, _priority, _packetAction);
> ```

Use `_packetAction.ordinal()` for consistent hash value
___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/AclTable.java, line 83 at r2](https://reviewable.io/reviews/batfish/batfish/7822#-Mr5MPz19CJWn8KHbksl:-Mr5MPz19CJWn8KHbksm:b-rxsu) ([raw file](https://github.com/batfish/batfish/blob/84a021ff79df1b66f26191e8c4bc1b59529db64c/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/AclTable.java#L83)):*
> ```Java
>   @Override
>   public int hashCode() {
>     return Objects.hash(_ports, _stage, _type);
> ```

`_stage.ordinal()`
___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConversions.java, line 83 at r2](https://reviewable.io/reviews/batfish/batfish/7822#-Mr5NO7j5uEeSnMenuic:-Mr5NO7j5uEeSnMenuid:blu73u4) ([raw file](https://github.com/batfish/batfish/blob/84a021ff79df1b66f26191e8c4bc1b59529db64c/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConversions.java#L83)):*
> ```Java
>       Configuration c, String aclName, IpAccessList ipAccessList, AclTable aclTable, Warnings w) {
>     if (aclTable.getType().orElse(null) != Type.L3) {
>       // While all ACLs are added to the configuration, but only type L3 ones are attached to
> ```

nit: Remove either `While` or `but`
___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConversions.java, line 95 at r2](https://reviewable.io/reviews/batfish/batfish/7822#-Mr5NbcVBvsxg-e8dru0:-Mr5NbcVBvsxg-e8dru1:b6l61ef) ([raw file](https://github.com/batfish/batfish/blob/84a021ff79df1b66f26191e8c4bc1b59529db64c/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConversions.java#L95)):*
> ```Java
>       Interface viIface = c.getAllInterfaces().get(port);
>       if (viIface == null) {
>         if (!port.equalsIgnoreCase("CtrlPlane")) {
> ```

Should probably extract a constant.
___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConversions.java, line 117 at r2](https://reviewable.io/reviews/batfish/batfish/7822#-Mr5OJNq5YFRa1Gm1xlo:-Mr5OJNq5YFRa1Gm1xlp:b-xz148b) ([raw file](https://github.com/batfish/batfish/blob/84a021ff79df1b66f26191e8c4bc1b59529db64c/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConversions.java#L117)):*
> ```Java
>       Configuration c, String aclName, Map<String, AclRule> aclRules, Warnings w) {
>     Map<Integer, AclLine> aclLines = new HashMap<>();
>     for (String ruleKey :
> ```

Looks like running time is something like`O(num_acls*num_acl_lines*log(num_acl_lines))`. Instead, prior to this function you could iterate over the lines once to put them in a `Map<String, SortedSet<AclLine>>` `(acl name -> lines for that acl)` (could also use `SortedSetMultimap`). Then when converting ACLs here, just grab the sorted list of lines. Would be O(num_acls+num_acl_lines*log(num_acl_lines))`.

Since we have often seen huge numbers of ACL lines, I'd recommend optimizing now.
___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConversions.java, line 165 at r2](https://reviewable.io/reviews/batfish/batfish/7822#-Mr5PpG695oCE6axLU5A:-Mr5PpG74I03u7Tjuuz7:bo2sn3b) ([raw file](https://github.com/batfish/batfish/blob/84a021ff79df1b66f26191e8c4bc1b59529db64c/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConversions.java#L165)):*
> ```Java
>     AclLineMatchExpr matchExpr =
>         new MatchHeaderSpace(
>             HeaderSpace.builder()
> ```

nit: we are trying to stop using `HeaderSpace`.
Instead use static functions in `AclLineMatchExprs` (e.g. `and`, `or`, `matchDstIp`, etc.).
___
*[projects/batfish/src/test/java/org/batfish/vendor/sonic/grammar/SonicGrammarTest.java, line 159 at r2](https://reviewable.io/reviews/batfish/batfish/7822#-Mr5QLWA5S0rv0PkNUYD:-Mr5QLWA5S0rv0PkNUYE:b-6g1nq1) ([raw file](https://github.com/batfish/batfish/blob/84a021ff79df1b66f26191e8c4bc1b59529db64c/projects/batfish/src/test/java/org/batfish/vendor/sonic/grammar/SonicGrammarTest.java#L159)):*
> ```Java
> 
>     Configuration c = getOnlyElement(vc.toVendorIndependentConfigurations());
>     IpAccessList ipAccessList = c.getAllInterfaces().get("Ethernet0").getInboundFilter();
> ```

Prefer to do BDD equivalence rather than individual flow tests.

See e.g. usages of this function in `CiscoNxosGrammarTest`:

```
  private @Nonnull BDD toBDD(AclLineMatchExpr aclLineMatchExpr) {
    return _aclToBdd.toBdd(aclLineMatchExpr);
  }
```

Also applies to `testConvertAcls`

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7822)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConversions.java, line 95 at r2](https://reviewable.io/reviews/batfish/batfish/7822#-Mr5NbcVBvsxg-e8dru0:-Mr5ukICDSPjYcgqVU9_:b-f27d1p) ([raw file](https://github.com/batfish/batfish/blob/84a021ff79df1b66f26191e8c4bc1b59529db64c/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConversions.java#L95)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Should probably extract a constant.
</blockquote></details>

Made a helper to contain the "knowledge"

**Review by arifogel — COMMENTED** [review]
> Reviewed 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7822)* status: all files reviewed, 1 unresolved discussion (waiting on @ratulm)

___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConversions.java, line 231 at r3](https://reviewable.io/reviews/batfish/batfish/7822#-Mr8Zpsw-ZjVHZETUxAn:-Mr8Zpsw-ZjVHZETUxAo:b-mee60o) ([raw file](https://github.com/batfish/batfish/blob/6496f7a3a45fbe5b3198564ab138e5b607734058/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConversions.java#L231)):*
> ```Java
>       return Comparator.comparing(AclRuleWithName::getPriority)
>           .thenComparing(r -> r._name)
>           .compare(o, this); // reverse order, so higher priority goes first
> ```

You're also preferring reverse sort for name this way. Intentional?

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7822)* status: 12 of 14 files reviewed, 1 unresolved discussion (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConversions.java, line 231 at r3](https://reviewable.io/reviews/batfish/batfish/7822#-Mr8Zpsw-ZjVHZETUxAn:-Mr8gHckDbbQ_Mcyg3WM:b2g3wj2) ([raw file](https://github.com/batfish/batfish/blob/6496f7a3a45fbe5b3198564ab138e5b607734058/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConversions.java#L231)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

You're also preferring reverse sort for name this way. Intentional?
</blockquote></details>

It was because I couldn't figure out a one-step way to sort one field in ascending order and the other in descending order. Made it two step.

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7822)* status: 13 of 14 files reviewed, 1 unresolved discussion (waiting on @arifogel and @ratulm)

___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConversions.java, line 231 at r3](https://reviewable.io/reviews/batfish/batfish/7822#-Mr8Zpsw-ZjVHZETUxAn:-Mr8z2l9ByEe2XqrUNGP:b20s76q) ([raw file](https://github.com/batfish/batfish/blob/6496f7a3a45fbe5b3198564ab138e5b607734058/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConversions.java#L231)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

It was because I couldn't figure out a one-step way to sort one field in ascending order and the other in descending order. Made it two step. 
</blockquote></details>

`comparing` and `thenComparing` can take an optional second comparator arg for the comparing the return type of the key extractor (first arg). You can pass `Comparator.reverseOrder` as that second arg just for priority.

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7822)* status: all files reviewed, 1 unresolved discussion (waiting on @ratulm)

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7822)* status: all files reviewed, 1 unresolved discussion (waiting on @ratulm)

___
*[projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConversions.java, line 231 at r3](https://reviewable.io/reviews/batfish/batfish/7822#-Mr8Zpsw-ZjVHZETUxAn:-Mr8zpO9D1VgX_cfEcb0:b-up6vcs) ([raw file](https://github.com/batfish/batfish/blob/6496f7a3a45fbe5b3198564ab138e5b607734058/projects/batfish/src/main/java/org/batfish/vendor/sonic/representation/SonicConversions.java#L231)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

`comparing` and `thenComparing` can take an optional second comparator arg for the comparing the return type of the key extractor (first arg). You can pass `Comparator.reverseOrder` as that second arg just for priority.
</blockquote></details>

I think reverseOrder takes an arg, which should be `Comparator.naturalOrder` if the key is already comparable.

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7822)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ratulm)

**Pull request merged**
