### PR TITLE
IOS XR: fix OSPF router network type

### PR DESCRIPTION
**Pull request by sfraint**
https://github.com/batfish/batfish/pull/7016 incorrectly set the process-level network type for area-level settings. This PR correctly handles setting network type at the top OSPF router/process level.

Area-level network type settings are not included in this PR and will require a bit more work.

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7021)* status: all files reviewed, 1 unresolved discussion (waiting on @corinaminer and @sfraint)

___
*[projects/batfish/src/test/resources/org/batfish/grammar/cisco_xr/testconfigs/ospf-network-type-override, line 14 at r1](https://reviewable.io/reviews/batfish/batfish/7021#-MaZsKITAb3zOo6_6Gs7:-MaZsKITAb3zOo6_6Gs8:bowuh3r) ([raw file](https://github.com/batfish/batfish/blob/a779f8a9aae755cc09126ddba7176d18f1963c5b/projects/batfish/src/test/resources/org/batfish/grammar/cisco_xr/testconfigs/ospf-network-type-override#L14)):*
> ```
>  network point-to-point
>  area 0
>  interface GigabitEthernet0/0/0/1
> ```

Should the `interface` stuff be further indented?

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7021)* status: all files reviewed, 2 unresolved discussions (waiting on @corinaminer and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7021#-MaZsVMHCQdXSCJ1OrCm:-MaZsVMHCQdXSCJ1OrCn:b-k8fqm5) (no related file):*
tests?

---

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7021)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @arifogel and @corinaminer)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7021#-MaZsVMHCQdXSCJ1OrCm:-MaZtyh49kKsoF1hBcPl:b9uqamo) (no related file):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

tests?
</blockquote></details>

the tests are in `XrGrammarTest` and use `ospf-network-type-override`

---
___
*[projects/batfish/src/test/resources/org/batfish/grammar/cisco_xr/testconfigs/ospf-network-type-override, line 14 at r1](https://reviewable.io/reviews/batfish/batfish/7021#-MaZsKITAb3zOo6_6Gs7:-MaZu1fh2ygtnNR2hzYG:bb7oryy) ([raw file](https://github.com/batfish/batfish/blob/a779f8a9aae755cc09126ddba7176d18f1963c5b/projects/batfish/src/test/resources/org/batfish/grammar/cisco_xr/testconfigs/ospf-network-type-override#L14)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Should the `interface` stuff be further indented?
</blockquote></details>

sure

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7021)* status: all files reviewed, 1 unresolved discussion (waiting on @corinaminer and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7021#-MaZsVMHCQdXSCJ1OrCm:-MaZu_z63YduvCzQsi-Q:b-c9dmep) (no related file):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

the tests are in `XrGrammarTest` and use `ospf-network-type-override`
</blockquote></details>

You got 50% coverage because the `todo` for area-level type is not hit. I suppose that's fine. Let me know if you need an override for merge.

---

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7021)* status: all files reviewed, 1 unresolved discussion (waiting on @corinaminer and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7021#-MaZsVMHCQdXSCJ1OrCm:-MaZv8aB5U7R8l91LxNZ:bdiz1iu) (no related file):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

You got 50% coverage because the `todo` for area-level type is not hit. I suppose that's fine. Let me know if you need an override for merge.
</blockquote></details>

..actually maybe just add an area override back tot he test config. That will get you coverage, and we will still know it's not implemented. Then when we implement it, we'll want to see an extraction test.

---

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7021)* status: all files reviewed, 1 unresolved discussion (waiting on @corinaminer and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7021#-MaZsVMHCQdXSCJ1OrCm:-MaZvP497MsYPup780BU:b-mg6smj) (no related file):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

..actually maybe just add an area override back tot he test config. That will get you coverage, and we will still know it's not implemented. Then when we implement it, we'll want to see an extraction test.
</blockquote></details>

*will get you grammar coverage

---

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7021)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

**Pull request merged**
