### PR TITLE
BDD library: Add testsVars operator

### PR DESCRIPTION
**Pull request by corinaminer**

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8237#-:-N-QsmSq4PJaLTKew5aW:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @anothermattbrown and @corinaminer)

___
*[projects/bdd/src/main/java/net/sf/javabdd/JFactory.java, line 2665 at r2](https://reviewable.io/reviews/batfish/batfish/8237#-N-QsOZq1qcJPggdgBn0:-N-QsOZr00zzNXW1Ianr:br8toeb) ([raw file](https://github.com/batfish/batfish/blob/450fa8e32cc9dcb515075d0b06b131f507c7386b/projects/bdd/src/main/java/net/sf/javabdd/JFactory.java#L2665)):*
> ```Java
>     }
> 
>     if (INVARSET(LEVEL(r)) || testsVars_rec(LOW(r)) || testsVars_rec(HIGH(r))) {
> ```

I'd probably move this one up to `r <2 ||` .. block and shortcut it - no need to cache.



_Code quote:_
```Java
INVARSET(LEVEL(r))
```

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8237)* status: all files reviewed, 1 unresolved discussion (waiting on @corinaminer)

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8237)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @anothermattbrown and @dhalperi)

___
*[projects/bdd/src/main/java/net/sf/javabdd/JFactory.java, line 2665 at r2](https://reviewable.io/reviews/batfish/batfish/8237#-N-QsOZq1qcJPggdgBn0:-N-URfwPEFGlgwmtN4fq:b-7rl0jd) ([raw file](https://github.com/batfish/batfish/blob/450fa8e32cc9dcb515075d0b06b131f507c7386b/projects/bdd/src/main/java/net/sf/javabdd/JFactory.java#L2665)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I'd probably move this one up to `r <2 ||` .. block and shortcut it - no need to cache.
</blockquote></details>

done.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8237)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

**Pull request merged**
