### PR TITLE
Cisco prefix-set definition fix

### PR DESCRIPTION
**Pull request by sfraint**
* Fixed type used in prefix-set definition
* Added test for prefix-set

### CODE REVIEW

**Comment by dhalperi** [comment]
Reviewed 1 of 7 files at r1.
Review status: 1 of 7 files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-prefix-set, line 8 at r1](https://reviewable.io/reviews/batfish/batfish/1386#-LCW-TiRBnDpSk4J3yv4:-LCW-TiRBnDpSk4J3yv5:b-eg322m) ([raw file](https://github.com/batfish/batfish/blob/e957e6a66da0db2943ca21ae2b465cd91a2740da/projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-prefix-set#L8)):*
> ```
> end-set
> prefix-set pre_ipv6
>   2001::ffff:0/124
> ```

why not combine these into one prefix-set? They can take both...

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1386)*

**Comment by dhalperi** [comment]
Reviewed 6 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1386)*

**Comment by sfraint** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-prefix-set, line 8 at r1](https://reviewable.io/reviews/batfish/batfish/1386#-LCW-TiRBnDpSk4J3yv4:-LCW11im0xodGoxbdOvW:b-1yk46e) ([raw file](https://github.com/batfish/batfish/blob/e957e6a66da0db2943ca21ae2b465cd91a2740da/projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-prefix-set#L8)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

why not combine these into one prefix-set? They can take both...
</blockquote></details>

Was considering a test case where referencing an ipv6-only `prefix-set` was showing up undefined when the ipv4-only `prefix-set` was fine.

I think if they were combined into a single `prefix-set` we would not catch that flawed behavior.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1386)*

**Comment by dhalperi** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-prefix-set, line 8 at r1](https://reviewable.io/reviews/batfish/batfish/1386#-LCW-TiRBnDpSk4J3yv4:-LCW5C_p0RXmpHi2O0Q7:b7hiote) ([raw file](https://github.com/batfish/batfish/blob/e957e6a66da0db2943ca21ae2b465cd91a2740da/projects/batfish/src/test/resources/org/batfish/grammar/cisco/testconfigs/ios-prefix-set#L8)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

Was considering a test case where referencing an ipv6-only `prefix-set` was showing up undefined when the ipv4-only `prefix-set` was fine.

I think if they were combined into a single `prefix-set` we would not catch that flawed behavior.
</blockquote></details>

This makes sense! I'm dumb.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1386)*

**Comment by dhalperi** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 5982 at r1](https://reviewable.io/reviews/batfish/batfish/1386#-LCW5LF13akPRAV3OJ3u:-LCW5LF13akPRAV3OJ3v:b-oaoaxd) ([raw file](https://github.com/batfish/batfish/blob/e957e6a66da0db2943ca21ae2b465cd91a2740da/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L5982)):*
> ```Java
>                 .getPrefix6Lists()
>                 .computeIfAbsent(name, n -> new Prefix6List(n, _currentPrefixSetDefinitionLine));
>         _configuration.defineStructure(PREFIX_SET, name, _currentPrefixSetDefinitionLine);
> ```

As our discussion indicated, the issue is likely that we shouldn't be defining structures here. Instead, use the (CCPE.) `defineStructure` function at the top level to define the prefix set for all lines.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1386)*

**Comment by dhalperi** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1386#-:-LCW7Q077xD7D9MF2P5C:bnfp4nl)*

**Comment by dhalperi** [comment]
Yep, this looks much nicer.

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1386#-:-LCWIDbC8qJoSt4vVG5l:bfvrn75)*

**Comment by dhalperi** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1386#-:-LCWQfnnBJkkXBNmsCKR:bnfp4nl)*

**Comment by dhalperi** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1386)*

**Pull request merged**
