### PR TITLE
Junos: allow numbers and hyphens in routing-instance names

### PR DESCRIPTION
**Pull request by dhalperi**
The linked URL includes numbers, but we didn't in our fragment. It also (on
like the next page) uses underscores in a routing-instance name, also in our
tests.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/9249)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @SLarkworthy)

___
*[`projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4` line 4172 at r1](https://reviewable.io/reviews/batfish/batfish/9249#-O9KumgzAyxtYGg0LCsx:-O9KumgzAyxtYGg0LCsy:b7dv9j9) ([raw file](https://github.com/batfish/batfish/blob/220eb907e61ddb8850a925792a304611b6938cff/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4#L4172)):*
> ```ANTLR
> ;
> 
> mode M_RoutingInstanceName;
> ```

FYI I decided it's probably best to use a mode everywhere we expect a routing-instance name so that we can find these bugs and keep parsing consistent

**Review by SLarkworthy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/9249)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[`projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4` line 2464 at r1](https://reviewable.io/reviews/batfish/batfish/9249#-O9L-87g3zt6wu86cUzs:-O9L-87h5M0bf_A7Dwrz:b-saf05k) ([raw file](https://github.com/batfish/batfish/blob/220eb907e61ddb8850a925792a304611b6938cff/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4#L2464)):*
> ```ANTLR
> ROUTING_INSTANCE: 'routing-instance' -> pushMode(M_RoutingInstanceName);
> ROUTING_INSTANCE_ACCESS: 'routing-instance-access';
> ROUTING_INSTANCES: 'routing-instances' -> pushMode(M_Routing_Instances);
> ```

Shouldn't we use this inside M_Routing_Instances as well? That one still just uses name.

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/9249)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @SLarkworthy)

___
*[`projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4` line 2464 at r1](https://reviewable.io/reviews/batfish/batfish/9249#-O9L-87g3zt6wu86cUzs:-O9L1wB2-bqiO_VDgemc:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/220eb907e61ddb8850a925792a304611b6938cff/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4#L2464)):*
<details><summary><i>Previously, SLarkworthy (Sarah Larkworthy) wrote…</i></summary><blockquote>

Shouldn't we use this inside M_Routing_Instances as well? That one still just uses name.
</blockquote></details>

Done.

**Review by SLarkworthy — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/9249#-:-O9L3FOdAJvUMuUZT9nM:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dhalperi)

**Review by SLarkworthy — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/9249#-:-O9L3QRw0IyRoi9_MmJS:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dhalperi)

**Pull request merged**
