### PR TITLE
Ios: AAA server groups

### PR DESCRIPTION
**Pull request by ratulm**
Reference tracking for AAA server groups and conversion for TACACS+ groups. 

No grammar changes were needed. There is a possibility that the grammar does not capture all possible references, but it was capturing all references in the example data that I had. Might need to flesh this out if we see different examples.

Update: Minor grammar change was needed for ref test inputs

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 10 of 10 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8215)* status: all files reviewed, 12 unresolved discussions (waiting on @ratulm)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_aaa.g4, line 749 at r2](https://reviewable.io/reviews/batfish/batfish/8215#-MzpyV1P36tIGx3Eb1cM:-MzpyV1P36tIGx3Eb1cN:bj2ikqb) ([raw file](https://github.com/batfish/batfish/blob/bd47271de30ad921eaed76b461a410ec7e17aa86/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_aaa.g4#L749)):*
> ```ANTLR
>          GROUP?
>          (
>            TACACS_PLUS
> ```

This grammar is real shaky, and probably that way because it combined grammar for multiple vendors originally. Can this be simplified for actual IOS?
___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 1713 at r2](https://reviewable.io/reviews/batfish/batfish/8215#-MzpyuPf-q_yZkoyFzVL:-MzpyuPf-q_yZkoyFzVM:b-yvohlp) ([raw file](https://github.com/batfish/batfish/blob/bd47271de30ad921eaed76b461a410ec7e17aa86/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L1713)):*
> ```Java
>   @Override
>   public void enterAaa_group(Aaa_groupContext ctx) {
>     String name = ctx.name.getText();
> ```

Use `toString(ctx.name)` so this can be caught when we finally fix structure names for IOS.
___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 3831 at r2](https://reviewable.io/reviews/batfish/batfish/8215#-MzpzPd6C6Lsv6kRwhT1:-MzpzPd6C6Lsv6kRwhT2:bs550g2) ([raw file](https://github.com/batfish/batfish/blob/bd47271de30ad921eaed76b461a410ec7e17aa86/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L3831)):*
> ```Java
>   public void exitAaa_accounting_default_group(Aaa_accounting_default_groupContext ctx) {
>     List<String> groups =
>         ctx.groups.stream().map(RuleContext::getText).collect(Collectors.toList());
> ```

Use `CiscoControlPlaneExtractor::toString` or `this::toString` if non-static. Applies multiple places.
___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 3853 at r2](https://reviewable.io/reviews/batfish/batfish/8215#-Mzpzqr4DZuxVI22CFTF:-Mzpzqr4DZuxVI22CFTG:b-11mukc) ([raw file](https://github.com/batfish/batfish/blob/bd47271de30ad921eaed76b461a410ec7e17aa86/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L3853)):*
> ```Java
>     for (String group : groups) {
>       _configuration.referenceStructure(
>           AAA_SERVER_GROUP, group, AAA_ACCOUNTING_CONNECTION_DEFAULT, ctx.getStart().getLine());
> ```

Intentionally the same structure usage as in `exitAaa_accounting_default_group`?
Similar question for authentication below.
___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 3858 at r2](https://reviewable.io/reviews/batfish/batfish/8215#-Mzq-IQY1DJ7gVknVXY4:-Mzq-IQY1DJ7gVknVXY5:bhec0oy) ([raw file](https://github.com/batfish/batfish/blob/bd47271de30ad921eaed76b461a410ec7e17aa86/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L3858)):*
> ```Java
> 
>   @Override
>   public void exitAaa_authentication_list_method_group(
> ```

Is this IOS? Can you just remove this grammar rule? Similar question for other group rules.
___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 3899 at r2](https://reviewable.io/reviews/batfish/batfish/8215#-Mzq-ces-aiBbIyWlmwV:-Mzq-ces-aiBbIyWlmwW:b-evjkga) ([raw file](https://github.com/batfish/batfish/blob/bd47271de30ad921eaed76b461a410ec7e17aa86/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L3899)):*
> ```Java
>       return;
>     }
>     List<String> groups = ctx.groups.stream().map(Token::getText).collect(Collectors.toList());
> ```

Can you change groups to a list of rules rather than tokens, and use a `toString` extractor method?
___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 3923 at r2](https://reviewable.io/reviews/batfish/batfish/8215#-Mzq00nxEswmrqKrtpnZ:-Mzq00nxEswmrqKrtpn_:bjs3zvt) ([raw file](https://github.com/batfish/batfish/blob/bd47271de30ad921eaed76b461a410ec7e17aa86/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L3923)):*
> ```Java
>     String server;
>     if (ctx.IP_ADDRESS() != null) {
>       server = ctx.IP_ADDRESS().getText();
> ```

Better to extract rule for all these alternatives, and have a single toString method for that rule. Applies multiple places.
___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 3929 at r2](https://reviewable.io/reviews/batfish/batfish/8215#-Mzq0EZT5fMYCP9EHIjX:-Mzq0EZT5fMYCP9EHIjY:b-ltzg4g) ([raw file](https://github.com/batfish/batfish/blob/bd47271de30ad921eaed76b461a410ec7e17aa86/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L3929)):*
> ```Java
>       server = ctx.name.getText();
>     } else {
>       _w.addWarning(ctx, getFullText(ctx), _parser, "Unhandled AAA group server");
> ```

IMO better to remove this branch, make the last `else if` an `else`, and `assert ctx.name != null` therein. May be moot depending on how you refactor.
___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 3932 at r2](https://reviewable.io/reviews/batfish/batfish/8215#-Mzq0cM98A5mf8hza4bi:-Mzq0cM98A5mf8hza4bj:be758jj) ([raw file](https://github.com/batfish/batfish/blob/bd47271de30ad921eaed76b461a410ec7e17aa86/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L3932)):*
> ```Java
>       return;
>     }
>     _currentAaaGroup.addServer(server);
> ```

Should you be adding references or definitions here?
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco/AaaServerGroup.java, line 24 at r2](https://reviewable.io/reviews/batfish/batfish/8215#-Mzq0lU6BeruFDTln3br:-Mzq0lU6BeruFDTln3bs:bc2c6s9) ([raw file](https://github.com/batfish/batfish/blob/bd47271de30ad921eaed76b461a410ec7e17aa86/projects/batfish/src/main/java/org/batfish/representation/cisco/AaaServerGroup.java#L24)):*
> ```Java
> 
>   public void addServer(String server) {
>     _servers = ImmutableList.<String>builder().addAll(_servers).add(server).build();
> ```

nit: more efficient to use `builderWithExpectedSize` since known.
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 2399 at r2](https://reviewable.io/reviews/batfish/batfish/8215#-Mzq14SkBX6x-VESmFpZ:-Mzq14SkBX6x-VESmFp_:b-r1j27r) ([raw file](https://github.com/batfish/batfish/blob/bd47271de30ad921eaed76b461a410ec7e17aa86/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L2399)):*
> ```Java
>   @VisibleForTesting
>   static Set<String> toTacacsServers(
>       NavigableSet<String> tacacsServers, Map<String, AaaServerGroup> tacacsPlusGroups) {
> ```

Why `NavigableSet`?
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 2401 at r2](https://reviewable.io/reviews/batfish/batfish/8215#-Mzq1HJZ-W1BSgIixv9o:-Mzq1HJZ-W1BSgIixv9p:bdhkcnt) ([raw file](https://github.com/batfish/batfish/blob/bd47271de30ad921eaed76b461a410ec7e17aa86/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L2401)):*
> ```Java
>       NavigableSet<String> tacacsServers, Map<String, AaaServerGroup> tacacsPlusGroups) {
>     /* The VI model of TACACS servers is not rich enough to express the nuances of global vs. group-level servers and of private servers. We combine them all in the VI set. */
>     return ImmutableSet.<String>builder()
> ```

Can there be overlap? If not, should that be enforced somewhere?

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8215)* status: 9 of 18 files reviewed, 5 unresolved discussions (waiting on @arifogel)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_aaa.g4, line 749 at r2](https://reviewable.io/reviews/batfish/batfish/8215#-MzpyV1P36tIGx3Eb1cM:-MzrqGu96njuoPhLOkjX:b-hcccy7) ([raw file](https://github.com/batfish/batfish/blob/bd47271de30ad921eaed76b461a410ec7e17aa86/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_aaa.g4#L749)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

This grammar is real shaky, and probably that way because it combined grammar for multiple vendors originally. Can this be simplified for actual IOS?
</blockquote></details>

Simplified some. Note that I am trying to stay away from grammar mods because I don't think I get it fully. 

Based on the documentation, I did make some changes to the a ref test file; removed lines that were 6 years old and seemed broken. 
___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 3858 at r2](https://reviewable.io/reviews/batfish/batfish/8215#-Mzq-IQY1DJ7gVknVXY4:-Mzrqh1SCx3OVMndPE_s:b-n4fm9m) ([raw file](https://github.com/batfish/batfish/blob/bd47271de30ad921eaed76b461a410ec7e17aa86/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L3858)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Is this IOS? Can you just remove this grammar rule? Similar question for other group rules.
</blockquote></details>

Dunno. See comment about not monkeying with the grammar.
___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 3929 at r2](https://reviewable.io/reviews/batfish/batfish/8215#-Mzq0EZT5fMYCP9EHIjX:-Mzqyt9G9BoD_84ivnlV:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/bd47271de30ad921eaed76b461a410ec7e17aa86/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L3929)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

IMO better to remove this branch, make the last `else if` an `else`, and `assert ctx.name != null` therein. May be moot depending on how you refactor.
</blockquote></details>

Done.
___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 3932 at r2](https://reviewable.io/reviews/batfish/batfish/8215#-Mzq0cM98A5mf8hza4bi:-Mzq_1GV-YHiyuBKT_JL:b-oxe1mk) ([raw file](https://github.com/batfish/batfish/blob/bd47271de30ad921eaed76b461a410ec7e17aa86/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L3932)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Should you be adding references or definitions here?
</blockquote></details>

Hmm...these are IP address or name. (What are you thinking?)
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 2401 at r2](https://reviewable.io/reviews/batfish/batfish/8215#-Mzq1HJZ-W1BSgIixv9o:-Mzqv5Hy9I32U49L5xu2:b5mbdt8) ([raw file](https://github.com/batfish/batfish/blob/bd47271de30ad921eaed76b461a410ec7e17aa86/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L2401)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Can there be overlap? If not, should that be enforced somewhere?
</blockquote></details>

What do you mean? We are throwing everything in a set, so overlaps do not matter, right?

**Review by arifogel — COMMENTED** [review]
> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8215)* status: all files reviewed, 4 unresolved discussions (waiting on @ratulm)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_aaa.g4, line 881 at r3](https://reviewable.io/reviews/batfish/batfish/8215#-MzvA4Uu3LD0PLRXt-0I:-MzvA4Uu3LD0PLRXt-0J:b874i0z) ([raw file](https://github.com/batfish/batfish/blob/5840c8ee19f57cc38bbb4e0a9aa6384145f2c0cc/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_aaa.g4#L881)):*
> `NAME`?

Gross but I guess we're no worse off. Hopefully no one tries to use the name `name`.
___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 3932 at r2](https://reviewable.io/reviews/batfish/batfish/8215#-Mzq0cM98A5mf8hza4bi:-MzvBV3hAlqcqIvUP949:b-35151u) ([raw file](https://github.com/batfish/batfish/blob/bd47271de30ad921eaed76b461a410ec7e17aa86/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L3932)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

Hmm...these are IP address or name. (What are you thinking?)
</blockquote></details>

Do these names/ips have to be configured somewhere and referenced somewhere? Should there be a structure/refs/defs for `aaa_group_server_member`?
Generally?
Only if not IPv{4,6} address?
Too obnoxious even for just name because of built-ins?
___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 3624 at r3](https://reviewable.io/reviews/batfish/batfish/8215#-MzvANt59McJtVZmFD-q:-MzvANt59McJtVZmFD-r:b3ojucm) ([raw file](https://github.com/batfish/batfish/blob/5840c8ee19f57cc38bbb4e0a9aa6384145f2c0cc/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L3624)):*
> ```Java
>   }
> 
>   private static @Nonnull String toString(RuleContext ctx) {
> ```

This defeats the purpose of the change I asked for. The idea was to only use `toString(Some_actual_grammar_ruleContext ctx)` so that when we update the grammar this fails to compile. Please delete this function and move all usages to a function for a particular grammar rule, e.g. `variable`, `aaa_group_server_member`, etc.

Sanity check: `rule` is not a specific rule in our grammar, right?
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 2401 at r2](https://reviewable.io/reviews/batfish/batfish/8215#-Mzq1HJZ-W1BSgIixv9o:-MzvCGfn3tPrnihB22ni:b-gq9mus) ([raw file](https://github.com/batfish/batfish/blob/bd47271de30ad921eaed76b461a410ec7e17aa86/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L2401)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

What do you mean? We are throwing everything in a set, so overlaps do not matter, right?
</blockquote></details>

I'm asking if the IOS CLI rejects overlap. For this particular function I suppose it does not matter, but we should maybe warn and refuse to update vendor model for such lines if that's the case.
Fine to defer.
___
*[tests/parsing-tests/networks/unit-tests/configs/cisco_aaa, line 70 at r3](https://reviewable.io/reviews/batfish/batfish/8215#-MzvClhA-R8WZvyOuC5m:-MzvClhA-R8WZvyOuC5n:b-8u3d1w) ([raw file](https://github.com/batfish/batfish/blob/ffd3daa7c7d883878051d05a7bfd87059ad35f3c/tests/parsing-tests/networks/unit-tests/configs/cisco_aaa#L70)):*
> ```
> aaa authorization console
> aaa authorization exec default group tacacs+ local none 
> aaa authorization exec default tacacs+ none
> ```

You removed these because of documentation, or because you tested that this is invalid on IOS CLI? Personally I don't trust IOS documentation to be complete.

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8215)* status: all files reviewed, 4 unresolved discussions (waiting on @arifogel and @ratulm)

___
*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 2401 at r2](https://reviewable.io/reviews/batfish/batfish/8215#-Mzq1HJZ-W1BSgIixv9o:-MzvNc3q9w3nTQaaJ1LI:b-d8iw4w) ([raw file](https://github.com/batfish/batfish/blob/bd47271de30ad921eaed76b461a410ec7e17aa86/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L2401)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

I'm asking if the IOS CLI rejects overlap. For this particular function I suppose it does not matter, but we should maybe warn and refuse to update vendor model for such lines if that's the case.
Fine to defer.
</blockquote></details>

Deferring. (I'll be surprised if IOS rejects overlaps.)

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8215)* status: 8 of 18 files reviewed, 2 unresolved discussions (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 3932 at r2](https://reviewable.io/reviews/batfish/batfish/8215#-Mzq0cM98A5mf8hza4bi:-MzvOXXn7fYg9BMi5oos:b-tq33c0) ([raw file](https://github.com/batfish/batfish/blob/bd47271de30ad921eaed76b461a410ec7e17aa86/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L3932)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Do these names/ips have to be configured somewhere and referenced somewhere? Should there be a structure/refs/defs for `aaa_group_server_member`?
Generally?
Only if not IPv{4,6} address?
Too obnoxious even for just name because of built-ins?
</blockquote></details>

I see what you mean. 

non-private servers must refer to a globally defined server. added tracking. 
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 2401 at r2](https://reviewable.io/reviews/batfish/batfish/8215#-Mzq1HJZ-W1BSgIixv9o:-MzvZtWr5LO-PC5d6DOz:bt55xq2) ([raw file](https://github.com/batfish/batfish/blob/bd47271de30ad921eaed76b461a410ec7e17aa86/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L2401)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

Deferring. (I'll be surprised if IOS rejects overlaps.)
</blockquote></details>

Confirmed: overlaps are allowed. 
___
*[tests/parsing-tests/networks/unit-tests/configs/cisco_aaa, line 70 at r3](https://reviewable.io/reviews/batfish/batfish/8215#-MzvClhA-R8WZvyOuC5m:-MzvZnqICpWGeYSSkUb1:bmywrsx) ([raw file](https://github.com/batfish/batfish/blob/ffd3daa7c7d883878051d05a7bfd87059ad35f3c/tests/parsing-tests/networks/unit-tests/configs/cisco_aaa#L70)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

You removed these because of documentation, or because you tested that this is invalid on IOS CLI? Personally I don't trust IOS documentation to be complete.
</blockquote></details>

You were right about not trusting documentation



_Code quote:_
```
aaa authorization exec ffffff none
```

**Review by arifogel — COMMENTED** [review]
> Reviewed 10 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8215)* status: all files reviewed, 3 unresolved discussions (waiting on @ratulm)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_aaa.g4, line 753 at r4](https://reviewable.io/reviews/batfish/batfish/8215#-Mzvdizn1faOFyyCeY3q:-Mzvdizn1faOFyyCeY3r:bkcmv0w) ([raw file](https://github.com/batfish/batfish/blob/3a09f38eaaeabc12e040b3290d12d99c9931b3b2/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_aaa.g4#L753)):*
> ```ANTLR
>     |
>     (
>       aaa_authorization_method_group?
> ```

I think you can simplify by removing `aaa_authorization_method_group?`.
Then the first outer alternative covers:
- group
- group group_additional+
And the second outer alternative covers:
- group_additional+

As is, second outer alternative covers:
group group_additional+ (covered above)
group_additional+
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_aaa.g4, line 766 at r4](https://reviewable.io/reviews/batfish/batfish/8215#-Mzvexn1CV5gxkzyAC-H:-Mzvexn1CV5gxkzyAC-I:bjddkfd) ([raw file](https://github.com/batfish/batfish/blob/3a09f38eaaeabc12e040b3290d12d99c9931b3b2/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_aaa.g4#L766)):*
> ```ANTLR
>    RADIUS
>    | TACACS_PLUS
>    | groups += aaa_authorization_method_group_name
> ```

This should no longer be a list, since it can only be populated once
___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 9433 at r4](https://reviewable.io/reviews/batfish/batfish/8215#-MzvfAIJDtD-5SzgGP8r:-MzvfAIJDtD-5SzgGP8s:bvq1ts4) ([raw file](https://github.com/batfish/batfish/blob/3a09f38eaaeabc12e040b3290d12d99c9931b3b2/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L9433)):*
> ```Java
>     String hostname = ctx.hostname.getText();
>     _configuration.getTacacsServers().add(hostname);
>     _configuration.defineStructure(TACACS_SERVER, hostname, ctx);
> ```

Do you need to add a self-reference, or should we warn if not used elsewhere?

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8215)* status: all files reviewed, 3 unresolved discussions (waiting on @ratulm)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_aaa.g4, line 766 at r4](https://reviewable.io/reviews/batfish/batfish/8215#-Mzvexn1CV5gxkzyAC-H:-MzvfkWD9QTlG3-4kNuG:byo5ox) ([raw file](https://github.com/batfish/batfish/blob/3a09f38eaaeabc12e040b3290d12d99c9931b3b2/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_aaa.g4#L766)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

This should no longer be a list, since it can only be populated once
</blockquote></details>

That is, use `=` instead of `+=`

**Review by arifogel — COMMENTED** [review]
> Reviewed 3 of 4 files at r5, 1 of 1 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8215)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ratulm)

**Pull request merged**
