### PR TITLE
Add ReachabilityParameters and ResolvedReachabilityParameters.

### PR DESCRIPTION
**Pull request by anothermattbrown**
- ReachabilityParameters is like ReachabilitySettings, except it uses
  the new Location/IpSpace/Node specifiers.
- ResolvedReachabilityParameters has no specifiers. Instead it has
  the results of resolving all the specifiers.

### CODE REVIEW

**Comment by dhalperi** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/HeaderSpace.java, line 1356 at r1](https://reviewable.io/reviews/batfish/batfish/1481#-LDEeMf49I7ysVhm6wBO:-LDEeMf49I7ysVhm6wBP:byyq93j) ([raw file](https://github.com/batfish/batfish/blob/e5b9146ec6abf7526e0addee0059f44e1270b5cb/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/HeaderSpace.java#L1356)):*
> ```Java
>   }
> 
>   public Builder toBuilder() {
> ```

is this different than `rebuild()`?

(this is a better name tho, I think).

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/NodesSpecifier.java, line 264 at r1](https://reviewable.io/reviews/batfish/batfish/1481#-LDEeRAe7Ztz7mCJuajC:-LDEeRAe7Ztz7mCJuajD:b-lojpmf) ([raw file](https://github.com/batfish/batfish/blob/e5b9146ec6abf7526e0addee0059f44e1270b5cb/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/NodesSpecifier.java#L264)):*
> ```Java
> 
>   @JsonIgnore
>   @VisibleForTesting
> ```

delete annotation if this now a public function :)

---

*[projects/batfish/src/main/java/org/batfish/main/ReachabilityParameterResolver.java, line 12 at r1](https://reviewable.io/reviews/batfish/batfish/1481#-LDEh5S66Z8L4tSuCmkq:-LDEh5S66Z8L4tSuCmkr:b5fubzl) ([raw file](https://github.com/batfish/batfish/blob/e5b9146ec6abf7526e0addee0059f44e1270b5cb/projects/batfish/src/main/java/org/batfish/main/ReachabilityParameterResolver.java#L12)):*
> ```Java
> import org.batfish.specifier.SpecifierContextImpl;
> 
> public class ReachabilityParameterResolver {
> ```

javadoc

---

*[projects/batfish/src/main/java/org/batfish/main/ReachabilityParameterResolver.java, line 12 at r1](https://reviewable.io/reviews/batfish/batfish/1481#-LDEh66g0p6IpAS2qu-M:-LDEh66g0p6IpAS2qu-N:b-qsyuya) ([raw file](https://github.com/batfish/batfish/blob/e5b9146ec6abf7526e0addee0059f44e1270b5cb/projects/batfish/src/main/java/org/batfish/main/ReachabilityParameterResolver.java#L12)):*
> ```Java
> import org.batfish.specifier.SpecifierContextImpl;
> 
> public class ReachabilityParameterResolver {
> ```

final?

---

*[projects/batfish/src/main/java/org/batfish/main/ReachabilityParameterResolver.java, line 12 at r1](https://reviewable.io/reviews/batfish/batfish/1481#-LDEiGf83T2I-Rx1uwnp:-LDEiGf93FhuYBenyyvx:b-va3een) ([raw file](https://github.com/batfish/batfish/blob/e5b9146ec6abf7526e0addee0059f44e1270b5cb/projects/batfish/src/main/java/org/batfish/main/ReachabilityParameterResolver.java#L12)):*
> ```Java
> import org.batfish.specifier.SpecifierContextImpl;
> 
> public class ReachabilityParameterResolver {
> ```

I can't tell if this is a public utility or an internal implementation detail to Batfish.

Users of reachability can probably either pass in ReachabilityParams or ResolvedReachabilityParams. This is one way to get from the former to the latter -- but maybe it's internal to batfish and no one else should ever need it?

---

*[projects/batfish/src/main/java/org/batfish/main/ReachabilityParameters.java, line 1 at r1](https://reviewable.io/reviews/batfish/batfish/1481#-LDEhbys3uc4gJr-kF0u:-LDEhbys3uc4gJr-kF0v:bnzr292) ([raw file](https://github.com/batfish/batfish/blob/e5b9146ec6abf7526e0addee0059f44e1270b5cb/projects/batfish/src/main/java/org/batfish/main/ReachabilityParameters.java#L1)):*
> ```Java
> package org.batfish.main;
> ```

these both go in common, right? This and resolved?

That way a question could actually use htem.

---

*[projects/batfish/src/main/java/org/batfish/main/ReachabilitySettingsToReachabilityParameters.java, line 36 at r1](https://reviewable.io/reviews/batfish/batfish/1481#-LDIEeNvAkBFPXUDzqXf:-LDIEeNvAkBFPXUDzqXg:b-rw801h) ([raw file](https://github.com/batfish/batfish/blob/e5b9146ec6abf7526e0addee0059f44e1270b5cb/projects/batfish/src/main/java/org/batfish/main/ReachabilitySettingsToReachabilityParameters.java#L36)):*
> ```Java
>  * be made in a new question.
>  */
> public class ReachabilitySettingsToReachabilityParameters {
> ```

Consider moving into ReachabilityQuestionPlugin? Not blocking.

---

*[projects/batfish/src/main/java/org/batfish/main/ResolvedReachabilityParameters.java, line 15 at r1](https://reviewable.io/reviews/batfish/batfish/1481#-LDEierPB8wzf841zQ6J:-LDEierPB8wzf841zQ6K:b5fubzl) ([raw file](https://github.com/batfish/batfish/blob/e5b9146ec6abf7526e0addee0059f44e1270b5cb/projects/batfish/src/main/java/org/batfish/main/ResolvedReachabilityParameters.java#L15)):*
> ```Java
> import org.batfish.specifier.IpSpaceAssignment;
> 
> public class ResolvedReachabilityParameters {
> ```

javadoc

---

*[projects/batfish/src/main/java/org/batfish/main/SrcNattedConstraint.java, line 8 at r1](https://reviewable.io/reviews/batfish/batfish/1481#-LDEhPL83AN3OiMDh1ft:-LDEhPL83AN3OiMDh1fu:b-sr5usk) ([raw file](https://github.com/batfish/batfish/blob/e5b9146ec6abf7526e0addee0059f44e1270b5cb/projects/batfish/src/main/java/org/batfish/main/SrcNattedConstraint.java#L8)):*
> ```Java
>   UNCONSTRAINED;
> 
>   public static SrcNattedConstraint fromBoolean(Boolean srcNatted) {
> ```

`@Nullable`

Does this go in common?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1481)*

**Comment by anothermattbrown** [comment]
Review status: 1 of 36 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/HeaderSpace.java, line 1356 at r1](https://reviewable.io/reviews/batfish/batfish/1481#-LDEeMf49I7ysVhm6wBO:-LDIG6N7DVrBqDT73kQf:b-qjuclz) ([raw file](https://github.com/batfish/batfish/blob/e5b9146ec6abf7526e0addee0059f44e1270b5cb/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/HeaderSpace.java#L1356)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

is this different than `rebuild()`?

(this is a better name tho, I think).
</blockquote></details>

gah! No it's redundant. I removed this and changed `rebuild` to `toBuilder`

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/NodesSpecifier.java, line 264 at r1](https://reviewable.io/reviews/batfish/batfish/1481#-LDEeRAe7Ztz7mCJuajC:-LDIGWgZA5K62d1kyDrP:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/e5b9146ec6abf7526e0addee0059f44e1270b5cb/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/NodesSpecifier.java#L264)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

delete annotation if this now a public function :)
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/main/ReachabilityParameterResolver.java, line 12 at r1](https://reviewable.io/reviews/batfish/batfish/1481#-LDEh5S66Z8L4tSuCmkq:-LDIH3Oi1CBZMBmiwy95:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/e5b9146ec6abf7526e0addee0059f44e1270b5cb/projects/batfish/src/main/java/org/batfish/main/ReachabilityParameterResolver.java#L12)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

javadoc
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/main/ReachabilityParameterResolver.java, line 12 at r1](https://reviewable.io/reviews/batfish/batfish/1481#-LDEh66g0p6IpAS2qu-M:-LDIH52h0pVqEtj0EjEa:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/e5b9146ec6abf7526e0addee0059f44e1270b5cb/projects/batfish/src/main/java/org/batfish/main/ReachabilityParameterResolver.java#L12)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

final?
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/main/ReachabilityParameterResolver.java, line 12 at r1](https://reviewable.io/reviews/batfish/batfish/1481#-LDEiGf83T2I-Rx1uwnp:-LDIHFKB2kntIAixteXm:beby6ea) ([raw file](https://github.com/batfish/batfish/blob/e5b9146ec6abf7526e0addee0059f44e1270b5cb/projects/batfish/src/main/java/org/batfish/main/ReachabilityParameterResolver.java#L12)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I can't tell if this is a public utility or an internal implementation detail to Batfish.

Users of reachability can probably either pass in ReachabilityParams or ResolvedReachabilityParams. This is one way to get from the former to the latter -- but maybe it's internal to batfish and no one else should ever need it?
</blockquote></details>

Yes I think it makes sense for this to be internal, at least for now. 

---

*[projects/batfish/src/main/java/org/batfish/main/ReachabilityParameters.java, line 1 at r1](https://reviewable.io/reviews/batfish/batfish/1481#-LDEhbys3uc4gJr-kF0u:-LDIHzWA-p5GtamHaxvG:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/e5b9146ec6abf7526e0addee0059f44e1270b5cb/projects/batfish/src/main/java/org/batfish/main/ReachabilityParameters.java#L1)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

these both go in common, right? This and resolved?

That way a question could actually use htem.
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/main/ReachabilitySettingsToReachabilityParameters.java, line 36 at r1](https://reviewable.io/reviews/batfish/batfish/1481#-LDIEeNvAkBFPXUDzqXf:-LDINBMOEPYZkmlxkNk7:b-5gbyst) ([raw file](https://github.com/batfish/batfish/blob/e5b9146ec6abf7526e0addee0059f44e1270b5cb/projects/batfish/src/main/java/org/batfish/main/ReachabilitySettingsToReachabilityParameters.java#L36)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Consider moving into ReachabilityQuestionPlugin? Not blocking.
</blockquote></details>

 Moved the `convert` method to `ReachabilitySettings`, and some of the smaller methods into new `LocationSpecifiers` and `NodeSpecifiers` classes.

---

*[projects/batfish/src/main/java/org/batfish/main/SrcNattedConstraint.java, line 8 at r1](https://reviewable.io/reviews/batfish/batfish/1481#-LDEhPL83AN3OiMDh1ft:-LDIOgZn-QBW2c3Cf-Ff:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/e5b9146ec6abf7526e0addee0059f44e1270b5cb/projects/batfish/src/main/java/org/batfish/main/SrcNattedConstraint.java#L8)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

`@Nullable`

Does this go in common?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1481)*

**Comment by dhalperi** [comment]
Reviewed 58 of 62 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/specifier/LocationSpecifiers.java, line 8 at r2](https://reviewable.io/reviews/batfish/batfish/1481#-LDIkBTL9Bb0kFguV-bX:-LDIkBTL9Bb0kFguV-bY:b-hlucpn) ([raw file](https://github.com/batfish/batfish/blob/1f4ea1dcede1c118c838d01590674f040ff17c40/projects/batfish-common-protocol/src/main/java/org/batfish/specifier/LocationSpecifiers.java#L8)):*
> ```Java
> import org.batfish.datamodel.questions.NodesSpecifier;
> 
> public class LocationSpecifiers {
> ```

looks like a utility class. If so, make `final` and add a private constructor so users can't instantiate.

---

*[projects/batfish/src/main/java/org/batfish/main/ReachabilityParameterResolver.java, line 12 at r1](https://reviewable.io/reviews/batfish/batfish/1481#-LDEiGf83T2I-Rx1uwnp:-LDIuXKh1kZkbj8EsPoB:b2pwq5q) ([raw file](https://github.com/batfish/batfish/blob/e5b9146ec6abf7526e0addee0059f44e1270b5cb/projects/batfish/src/main/java/org/batfish/main/ReachabilityParameterResolver.java#L12)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

Yes I think it makes sense for this to be internal, at least for now. 
</blockquote></details>

Ok. Can we make this package-private then, assuming it's only called by `Batfish.java`?

---

*[projects/batfish/src/main/java/org/batfish/main/ReachabilityParameters.java, line 1 at r1](https://reviewable.io/reviews/batfish/batfish/1481#-LDEhbys3uc4gJr-kF0u:-LDIjwQg5GGPwamffDCD:b-wniyb1) ([raw file](https://github.com/batfish/batfish/blob/e5b9146ec6abf7526e0addee0059f44e1270b5cb/projects/batfish/src/main/java/org/batfish/main/ReachabilityParameters.java#L1)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

these both go in common, right? This and resolved?

That way a question could actually use htem.
</blockquote></details>

need to fix package.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/main/ResolvedReachabilityParameters.java, line 1 at r2](https://reviewable.io/reviews/batfish/batfish/1481#-LDIk0345qwF1x8on03s:-LDIk035EAzDb97Fc3Og:b-wniyb1) ([raw file](https://github.com/batfish/batfish/blob/1f4ea1dcede1c118c838d01590674f040ff17c40/projects/batfish-common-protocol/src/main/java/org/batfish/main/ResolvedReachabilityParameters.java#L1)):*
> ```Java
> package org.batfish.main;
> ```

need to fix package.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/main/SrcNattedConstraint.java, line 1 at r2](https://reviewable.io/reviews/batfish/batfish/1481#-LDIk2QP-JrW_uMTY3zq:-LDIk2QP-JrW_uMTY3zr:b-wniyb1) ([raw file](https://github.com/batfish/batfish/blob/1f4ea1dcede1c118c838d01590674f040ff17c40/projects/batfish-common-protocol/src/main/java/org/batfish/main/SrcNattedConstraint.java#L1)):*
> ```Java
> package org.batfish.main;
> ```

need to fix package.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1481)*

**Comment by anothermattbrown** [comment]
Review status: 30 of 36 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[projects/batfish/src/main/java/org/batfish/main/ReachabilityParameterResolver.java, line 12 at r1](https://reviewable.io/reviews/batfish/batfish/1481#-LDEiGf83T2I-Rx1uwnp:-LDJ34Nu-NxJenwDwCF4:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/e5b9146ec6abf7526e0addee0059f44e1270b5cb/projects/batfish/src/main/java/org/batfish/main/ReachabilityParameterResolver.java#L12)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Ok. Can we make this package-private then, assuming it's only called by `Batfish.java`?
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/main/ReachabilityParameters.java, line 1 at r1](https://reviewable.io/reviews/batfish/batfish/1481#-LDEhbys3uc4gJr-kF0u:-LDJ3QOlCYVOginHNRga:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/e5b9146ec6abf7526e0addee0059f44e1270b5cb/projects/batfish/src/main/java/org/batfish/main/ReachabilityParameters.java#L1)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

need to fix package.
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/main/ResolvedReachabilityParameters.java, line 15 at r1](https://reviewable.io/reviews/batfish/batfish/1481#-LDEierPB8wzf841zQ6J:-LDJ2UVLDO-5lfxbnJjR:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/e5b9146ec6abf7526e0addee0059f44e1270b5cb/projects/batfish/src/main/java/org/batfish/main/ResolvedReachabilityParameters.java#L15)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

javadoc
</blockquote></details>

Done.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/main/ResolvedReachabilityParameters.java, line 1 at r2](https://reviewable.io/reviews/batfish/batfish/1481#-LDIk0345qwF1x8on03s:-LDJ3P-23Nc67B5o31fZ:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/1f4ea1dcede1c118c838d01590674f040ff17c40/projects/batfish-common-protocol/src/main/java/org/batfish/main/ResolvedReachabilityParameters.java#L1)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

need to fix package.
</blockquote></details>

Done.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/main/SrcNattedConstraint.java, line 1 at r2](https://reviewable.io/reviews/batfish/batfish/1481#-LDIk2QP-JrW_uMTY3zq:-LDJ3C3C5RazvpArZkEs:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/1f4ea1dcede1c118c838d01590674f040ff17c40/projects/batfish-common-protocol/src/main/java/org/batfish/main/SrcNattedConstraint.java#L1)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

need to fix package.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1481)*

**Comment by anothermattbrown** [comment]
Review status: 30 of 36 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/specifier/LocationSpecifiers.java, line 8 at r2](https://reviewable.io/reviews/batfish/batfish/1481#-LDIkBTL9Bb0kFguV-bX:-LDJ3cY88M56C8brqEZ6:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/1f4ea1dcede1c118c838d01590674f040ff17c40/projects/batfish-common-protocol/src/main/java/org/batfish/specifier/LocationSpecifiers.java#L8)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

looks like a utility class. If so, make `final` and add a private constructor so users can't instantiate.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1481)*

**Comment by dhalperi** [comment]
Reviewed 8 of 16 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1481)*

**Pull request merged**
