### PR TITLE
IOS-XR tftp parsing and access-list name refactor

### PR DESCRIPTION
**Pull request by arifogel**
- parse tftp
- make `access-list` push into M_Word for all instances (including tftp)

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 14 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6936)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXrParser.g4, line 143 at r1](https://reviewable.io/reviews/batfish/batfish/6936#-MYgsCMN0zY_egmri3_M:-MYgsCMN0zY_egmri3_N:b-q6ctg3) ([raw file](https://github.com/batfish/batfish/blob/7e97d2f75b0a48e595ba7e042caf7f19870b6bc1/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXrParser.g4#L143)):*
> ```ANTLR
>   (
>     NETMASK_FORMAT
>     | UNNUMBERED
> ```

This needs to be extracted and warned on.

Do the others?

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6936)* status: all files reviewed, 2 unresolved discussions (waiting on @arifogel)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_common.g4, line 123 at r1](https://reviewable.io/reviews/batfish/batfish/6936#-MYgvi-D4-H4bis_wt37:-MYgvi-D4-H4bis_wt38:bkqpw80) ([raw file](https://github.com/batfish/batfish/blob/7e97d2f75b0a48e595ba7e042caf7f19870b6bc1/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_common.g4#L123)):*
> ```ANTLR
> dscp_type
> :
>    dscp_num
> ```

probably worth adding a simple unit test for the variants

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6936)* status: 13 of 14 files reviewed, 2 unresolved discussions (waiting on @arifogel and @dhalperi)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXrParser.g4, line 143 at r1](https://reviewable.io/reviews/batfish/batfish/6936#-MYgsCMN0zY_egmri3_M:-MYkVbnL9nLbECw2nIlo:b-x4mugd) ([raw file](https://github.com/batfish/batfish/blob/7e97d2f75b0a48e595ba7e042caf7f19870b6bc1/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXrParser.g4#L143)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

This needs to be extracted and warned on.

Do the others?
</blockquote></details>

I don't think `ipv4 netmask-format` affects anything we care about directly.
`UNNUMBERED` was accidentally added to this PR. Reverted.

`ipv4 virtual` is for configuring virtual addresses for management interfaces. I figured we don't care about that. If you think we should warn, let me know and I'll address in a separate PR.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6936)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel)

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6936)* status: 13 of 16 files reviewed, all discussions resolved (waiting on @dhalperi)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_common.g4, line 123 at r1](https://reviewable.io/reviews/batfish/batfish/6936#-MYgvi-D4-H4bis_wt37:-MYkqXEp4e-5PruHi1pX:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/7e97d2f75b0a48e595ba7e042caf7f19870b6bc1/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_common.g4#L123)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

probably worth adding a simple unit test for the variants
</blockquote></details>

done

**Review by dhalperi — COMMENTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6936)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
