### PR TITLE
Fill in dataplane doc

### PR DESCRIPTION
**Pull request by corinaminer**
Could use a supporting doc covering what a routing iteration looks like for a particular protocol, including redistribution, exports, queues, etc. Probably BGP is the prime candidate for deeper documentation.

### CODE REVIEW

**Comment by dhalperi** [comment]
Maybe @ratulm would be a good first-pass reviewer, as he's less tied into the code

**Review by ratulm — COMMENTED** [review]
At some place, perhaps after the algorithm description, also mention that the computed dataplane may not be same as the real network one when the answer depends on arrival order. 

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8463#-:-N9AGvWgA-RrHNHvB_ZJ:bbo3hpq)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @corinaminer and @dhalperi)

___
*[`docs/dataplane-computation.md` line 2 at r2](https://reviewable.io/reviews/batfish/batfish/8463#-N9ABR4T18r_k7dj1DPW:-N9ABR4T18r_k7dj1DPX:b9bjv16) ([raw file](https://github.com/batfish/batfish/blob/728de4e397a7b84ae16171895d003f48a2b93ef7/docs/dataplane-computation.md#L2)):*
> ```Markdown
> ## Dataplane computation
> Once the vendor independent (VI) model is fully generated and layer 3 topology is initialized, Batfish is ready to compute the dataplane.
> ```

"layer 3 topology is initialized"  --> "initial layer 3 topology is computed" (might be less of a surprise when you talk about layer 3 topology itself changing)
___
*[`docs/dataplane-computation.md` line 5 at r2](https://reviewable.io/reviews/batfish/batfish/8463#-N9ABlA7B6bUNs2003S-:-N9ABlA7B6bUNs2003S0:bnxzk4t) ([raw file](https://github.com/batfish/batfish/blob/728de4e397a7b84ae16171895d003f48a2b93ef7/docs/dataplane-computation.md#L5)):*
> ```Markdown
> 
> ### What is the dataplane?
> The output of Batfish's dataplane computation is a [`DataPlane`](https://github.com/batfish/batfish/blob/master/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/DataPlane.java), which contains routing and forwarding information about the network:
> ```

Would you consider the layer 3 topology as another output of data plane computation?
___
*[`docs/dataplane-computation.md` line 11 at r2](https://reviewable.io/reviews/batfish/batfish/8463#-N9AC0GbCXjGuZK2aKSK:-N9AC0GbCXjGuZK2aKSL:bug9d77) ([raw file](https://github.com/batfish/batfish/blob/728de4e397a7b84ae16171895d003f48a2b93ef7/docs/dataplane-computation.md#L11)):*
> ```Markdown
> ### When is the dataplane computed?
> Computing the dataplane can require several minutes on larger networks, and many questions can be run without it. For this reason, the dataplane is not automatically computed as part of Pybatfish's `bf.init_snapshot(SNAPSHOT_PATH)`. The computation can be kicked off automatically by running a dataplane-dependent question or manually by running `bf.generate_dataplane()`.
> ```

Nit: Replace the first two sentences with "The dataplane is not automatically computed as part of Pybatfish's `bf.init_snapshot(SNAPSHOT_PATH)` because computing it can take several minutes on large networks, and many questions can be run without it." 
___
*[`docs/dataplane-computation.md` line 12 at r2](https://reviewable.io/reviews/batfish/batfish/8463#-N9ACO3Q7b33bNHgQ3OB:-N9ACO3Q7b33bNHgQ3OC:bjz9gkj) ([raw file](https://github.com/batfish/batfish/blob/728de4e397a7b84ae16171895d003f48a2b93ef7/docs/dataplane-computation.md#L12)):*
> ```Markdown
> Computing the dataplane can require several minutes on larger networks, and many questions can be run without it. For this reason, the dataplane is not automatically computed as part of Pybatfish's `bf.init_snapshot(SNAPSHOT_PATH)`. The computation can be kicked off automatically by running a dataplane-dependent question or manually by running `bf.generate_dataplane()`.
> 
> #### Dataplane-dependent questions
> ```

Is this section needed in this doc? If you think it helps, move it to the end. When readers come to this doc, they are likely interested in how things are computed. This section just gets in the way. 
___
*[`docs/dataplane-computation.md` line 15 at r2](https://reviewable.io/reviews/batfish/batfish/8463#-N9AChIv5DLWrnczhYB7:-N9AChIv5DLWrnczhYB8:btei7uj) ([raw file](https://github.com/batfish/batfish/blob/728de4e397a7b84ae16171895d003f48a2b93ef7/docs/dataplane-computation.md#L15)):*
> ```Markdown
> Dataplane computation is triggered automatically when a dataplane-dependent question is run. Questions are dataplane-dependent if they depend on routes or forwarding; some examples are [Traceroute](https://pybatfish.readthedocs.io/en/latest/notebooks/forwarding.html#Traceroute), [Reachability](https://pybatfish.readthedocs.io/en/latest/notebooks/forwarding.html#Reachability), [Routes](https://pybatfish.readthedocs.io/en/latest/notebooks/routingTables.html#Routes), and [BGP Session Status](https://pybatfish.readthedocs.io/en/latest/notebooks/routingProtocols.html#BGP-Session-Status). You can see if a given question is dataplane-dependent by checking whether `getDataplane()` returns `true` in its Java [`Question`](https://github.com/batfish/batfish/blob/master/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/questions/Question.java) implementation.
> 
> #### Using `bf.generate_dataplane()`
> ```

Again, the interest of getting readers to what they want: move this content to "when is dataplane computed" and shrink it if possible.  
___
*[`docs/dataplane-computation.md` line 20 at r2](https://reviewable.io/reviews/batfish/batfish/8463#-N9AD-coDBb89yFK9MUn:-N9AD-cp3ROX0ZC-sQpR:b-5x1tlv) ([raw file](https://github.com/batfish/batfish/blob/728de4e397a7b84ae16171895d003f48a2b93ef7/docs/dataplane-computation.md#L20)):*
> ```Markdown
> If dataplane computation crashes, `bf.generate_dataplane()` provides a better error message than running a dataplane-dependent question.
> 
> #### Dataplane reuse
> ```

Move this section later, after you've told me how things are computed.
___
*[`docs/dataplane-computation.md` line 37 at r2](https://reviewable.io/reviews/batfish/batfish/8463#-N9ADLXX3I-pcztrQ0TX:-N9ADLXX3I-pcztrQ0TY:bb1r8wg) ([raw file](https://github.com/batfish/batfish/blob/728de4e397a7b84ae16171895d003f48a2b93ef7/docs/dataplane-computation.md#L37)):*
> ```Markdown
> * A [`Node`](https://github.com/batfish/batfish/blob/master/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/Node.java) represents each device.
> * A [`VirtualRouter`](https://github.com/batfish/batfish/blob/master/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java) represents each VRF. Most dataplane computation steps are parallelized across `VirtualRouter` objects. Each `VirtualRouter` has a main [`Rib`](https://github.com/batfish/batfish/blob/master/projects/batfish/src/main/java/org/batfish/dataplane/rib/Rib.java) containing the current active routes (corresponding to Cisco-syntax `show ip route`), as well as protocol-specific RIBs containing the routes of each active protocol.
> * In VRFs running BGP, EIGRP, or OSPF, the `VirtualRouter` does not handle the protocol RIB itself, but instead has a [`RoutingProcess`](https://github.com/batfish/batfish/blob/master/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/RoutingProcess.java) of the corresponding type to handle the routes for that protocol.
> ```

Not necessarily a recommendation, but thinking aloud: Does it help to mention that at most one process of a given protocol is supported at the moment? (Not sure how deep the limitation is -- is it just VI model specific or also present in IBDP.)
___
*[`docs/dataplane-computation.md` line 59 at r2](https://reviewable.io/reviews/batfish/batfish/8463#-N9AFbgY44Fl2pVOasxj:-N9AFbgY44Fl2pVOasxk:bo1ayby) ([raw file](https://github.com/batfish/batfish/blob/728de4e397a7b84ae16171895d003f48a2b93ef7/docs/dataplane-computation.md#L59)):*
> ```Markdown
> 1. `IncrementalBdpEngine.computeNonMonotonicPortionOfDataPlane`: Routing/EGP fixed point operation. This operation brings all devices' routes to a fixed point based on the current topology, reachability, and IP ownership state.
>    * Compute HMM and kernel routes.
>    * Redistribute: In each `VirtualRouter`, perform redistribution of routes into BGP, OSPF, EIGRP, and IS-IS. Redistribution in Batfish is a local operation that adds the redistributed routes to the target protocol's RIB, from which they may be exported later.
> ```

helps to mention redistribution policies (and point to code that evaluates it)? 

same thought about where export/import policies kick in.

**Review by corinaminer — COMMENTED** [review]
Added brief discussion of (non)determinism with mention of arrival order after the oscillation section -- they seem related as "categories of network for which batfish may not perform as you expect".

> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8463#-:-NBNkCfd-MPRmGTW4w-k:bvk0wny)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @dhalperi and @ratulm)

___
*[`docs/dataplane-computation.md` line 2 at r2](https://reviewable.io/reviews/batfish/batfish/8463#-N9ABR4T18r_k7dj1DPW:-NBJJuX06HtPVi7xcKhg:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/728de4e397a7b84ae16171895d003f48a2b93ef7/docs/dataplane-computation.md#L2)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

"layer 3 topology is initialized"  --> "initial layer 3 topology is computed" (might be less of a surprise when you talk about layer 3 topology itself changing)
</blockquote></details>

done
___
*[`docs/dataplane-computation.md` line 5 at r2](https://reviewable.io/reviews/batfish/batfish/8463#-N9ABlA7B6bUNs2003S-:-NBNeNkX4czJHBl3ZSEn:b-rfyz63) ([raw file](https://github.com/batfish/batfish/blob/728de4e397a7b84ae16171895d003f48a2b93ef7/docs/dataplane-computation.md#L5)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

Would you consider the layer 3 topology as another output of data plane computation?
</blockquote></details>

yes, it also produces other topologies. Updated.
___
*[`docs/dataplane-computation.md` line 11 at r2](https://reviewable.io/reviews/batfish/batfish/8463#-N9AC0GbCXjGuZK2aKSK:-NBJKCKX2YdgO5LH0U9q:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/728de4e397a7b84ae16171895d003f48a2b93ef7/docs/dataplane-computation.md#L11)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

Nit: Replace the first two sentences with "The dataplane is not automatically computed as part of Pybatfish's `bf.init_snapshot(SNAPSHOT_PATH)` because computing it can take several minutes on large networks, and many questions can be run without it." 
</blockquote></details>

done
___
*[`docs/dataplane-computation.md` line 12 at r2](https://reviewable.io/reviews/batfish/batfish/8463#-N9ACO3Q7b33bNHgQ3OB:-NBJL_mY-Vq6QD5TmScx:bivpf3x) ([raw file](https://github.com/batfish/batfish/blob/728de4e397a7b84ae16171895d003f48a2b93ef7/docs/dataplane-computation.md#L12)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

Is this section needed in this doc? If you think it helps, move it to the end. When readers come to this doc, they are likely interested in how things are computed. This section just gets in the way. 
</blockquote></details>

yeah, not really necessary. Removed and reworded the end of the previous section for better flow.
___
*[`docs/dataplane-computation.md` line 15 at r2](https://reviewable.io/reviews/batfish/batfish/8463#-N9AChIv5DLWrnczhYB7:-NBJMEdQCsQQAr1XE4wh:boqtmv6) ([raw file](https://github.com/batfish/batfish/blob/728de4e397a7b84ae16171895d003f48a2b93ef7/docs/dataplane-computation.md#L15)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

Again, the interest of getting readers to what they want: move this content to "when is dataplane computed" and shrink it if possible.  
</blockquote></details>

Moved the "when is dataplane computed" section to the end.
___
*[`docs/dataplane-computation.md` line 37 at r2](https://reviewable.io/reviews/batfish/batfish/8463#-N9ADLXX3I-pcztrQ0TX:-NBJNB0s9RAa9EsBw0qJ:b42ou46) ([raw file](https://github.com/batfish/batfish/blob/728de4e397a7b84ae16171895d003f48a2b93ef7/docs/dataplane-computation.md#L37)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

Not necessarily a recommendation, but thinking aloud: Does it help to mention that at most one process of a given protocol is supported at the moment? (Not sure how deep the limitation is -- is it just VI model specific or also present in IBDP.)
</blockquote></details>

hmm, Batfish does actually support multiple OSPF and EIGRP processes per vrf, but only one BGP process. When I wrote this I was thinking that wouldn't be relevant to most readers, but realize it could be misleading as-is. I reworded, and can add a sentence like "Batfish currently supports multiple OSPF and EIGRP processes per VRF, but only one BGP process" if you think that's helpful.
___
*[`docs/dataplane-computation.md` line 59 at r2](https://reviewable.io/reviews/batfish/batfish/8463#-N9AFbgY44Fl2pVOasxj:-NBNjgxzC4_Jd3sT8022:b-3xw9ua) ([raw file](https://github.com/batfish/batfish/blob/728de4e397a7b84ae16171895d003f48a2b93ef7/docs/dataplane-computation.md#L59)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

helps to mention redistribution policies (and point to code that evaluates it)? 

same thought about where export/import policies kick in. 
</blockquote></details>

Added mention of redistribution policies here.

Export/import policies is trickier to fit in because those are applied within the `computeDependentRoutesIteration` a few bullet points down, where I'm not going into specifics about any protocol. I think it would be better to have an additional docs page about what an iteration looks like within a specific protocol, presumably BGP, which would include discussion of import and export policies.

**Review by ratulm — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8463)* status: all files reviewed, 1 unresolved discussion (waiting on @corinaminer and @dhalperi)

___
*[`docs/data_plane/README.md` line 16 at r3](https://reviewable.io/reviews/batfish/batfish/8463#-NBODMZJ7DAQMrw6LmAr:-NBODMZJ7DAQMrw6LmAs:bfum0eq) ([raw file](https://github.com/batfish/batfish/blob/3684dfe53301d3603c5ea68ea0343db9c012bffb/docs/data_plane/README.md#L16)):*
> ```Markdown
> Some networks oscillate and do not have a stable state. If Batfish detects oscillation during dataplane computation, it raises a [`BdpOscillationException`](https://github.com/batfish/batfish/blob/master/projects/batfish-common-protocol/src/main/java/org/batfish/common/BdpOscillationException.java) (BDP stands for Batfish dataplane). No dataplane is generated and dataplane-dependent questions cannot be run.
> 
> ### Determinism
> ```

Nit: s/Determinism/Non-determinism/

**Review by ratulm — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8463)* status: all files reviewed, 1 unresolved discussion (waiting on @corinaminer and @dhalperi)

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8463)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dhalperi)

___
*[`docs/data_plane/README.md` line 16 at r3](https://reviewable.io/reviews/batfish/batfish/8463#-NBODMZJ7DAQMrw6LmAr:-NBTf-poEoGQfFt7LvX2:b-dzxzur) ([raw file](https://github.com/batfish/batfish/blob/3684dfe53301d3603c5ea68ea0343db9c012bffb/docs/data_plane/README.md#L16)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

Nit: s/Determinism/Non-determinism/
</blockquote></details>

done but left out the hyphen -- nondeterminism looks to be standard per wikipedia

**Review by dhalperi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8463)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

**Pull request merged**
