### PR TITLE
Cisco: support ospf redistribute without subnets set

### PR DESCRIPTION
**Pull request by dhalperi**
After #1129

### CODE REVIEW

**Comment by arifogel** [comment]
Reviewed 10 of 13 files at r1, 2 of 7 files at r2.
Review status: 9 of 13 files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/CallExpr.java, line 111 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1138#-L9fhyuh80wDdg0iVlRK:-L9fhyuh80wDdg0iVlRL:beu2smo) ([raw file](https://github.com/batfish/batfish/blob/196e5874ab80733cc492d8a1a0d0836eb7209b73/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/CallExpr.java#L111)):*
> ```Java
>   @Override
>   public String toString() {
>     return toStringHelper().add(PROP_CALLED_POLICY_NAME, _calledPolicyName).toString();
> ```

You threw away the class name.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/Conjunction.java, line 134 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1138#-L9fi88m9WWBpkCKQe4v:-L9fi88m9WWBpkCKQe4w:beu2smo) ([raw file](https://github.com/batfish/batfish/blob/196e5874ab80733cc492d8a1a0d0836eb7209b73/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/Conjunction.java#L134)):*
> ```Java
>   @Override
>   public String toString() {
>     return toStringHelper().add(PROP_CONJUNCTS, _conjuncts).toString();
> ```

You threw away the class name.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/MatchPrefixSet.java, line 99 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1138#-L9fiEIB9-DxH4N9nZwz:-L9fiEIB9-DxH4N9nZx-:bsaprbf) ([raw file](https://github.com/batfish/batfish/blob/196e5874ab80733cc492d8a1a0d0836eb7209b73/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/MatchPrefixSet.java#L99)):*
> ```Java
>   @Override
>   public String toString() {
>     return toStringHelper().add(PROP_PREFIX, _prefix).add(PROP_PREFIX_SET, _prefixSet).toString();
> ```

Please add class name.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/Not.java, line 85 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1138#-L9fiMrFEnNVvLEKJRss:-L9fiMrFEnNVvLEKJRst:bsaprbf) ([raw file](https://github.com/batfish/batfish/blob/196e5874ab80733cc492d8a1a0d0836eb7209b73/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/Not.java#L85)):*
> ```Java
>   @Override
>   public String toString() {
>     return toStringHelper().add(PROP_EXPR, _expr).toString();
> ```

Please add class name.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 100 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1138#-L9fivCEETtFG2btQLWW:-L9fivCEETtFG2btQLWX:b-8dn0xl) ([raw file](https://github.com/batfish/batfish/blob/196e5874ab80733cc492d8a1a0d0836eb7209b73/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L100)):*
> ```Java
> import org.batfish.datamodel.routing_policy.expr.NamedPrefixSet;
> import org.batfish.datamodel.routing_policy.expr.Not;
> import org.batfish.datamodel.routing_policy.expr.RouteIsClassfull;
> ```

Shouldn't this be `RouteIsClassful` (one `l`).

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 2686 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1138#-L9fj59s225SuswVBMok:-L9fj59t28HOkSDbfRs_:b-yblwa9) ([raw file](https://github.com/batfish/batfish/blob/196e5874ab80733cc492d8a1a0d0836eb7209b73/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L2686)):*
> ```Java
>   // For testing.
>   If convertOspfRedistributionPolicy(
>       OspfRedistributionPolicy rcp, OspfProcess proc, CiscoStructureUsage structureType) {
> ```

`rcp` meant `Redistribute Connected Policy`. Maybe use more general local variable name?

---

*[projects/batfish/src/test/java/org/batfish/representation/cisco/CiscoOspfTest.java, line 47 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1138#-L9fjKbX8n2ANk-UqD-y:-L9fjKbX8n2ANk-UqD-z:btjy2il) ([raw file](https://github.com/batfish/batfish/blob/196e5874ab80733cc492d8a1a0d0836eb7209b73/projects/batfish/src/test/java/org/batfish/representation/cisco/CiscoOspfTest.java#L47)):*
> ```Java
> 
>   @Test
>   public void testBasicConvertRcp() {
> ```

The `c` used to mean `connected`.  You should rename.

---

*[projects/batfish/src/test/java/org/batfish/representation/cisco/CiscoOspfTest.java, line 72 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1138#-L9fjQX14z5e3de90v25:-L9fjQX14z5e3de90v26:btjy2il) ([raw file](https://github.com/batfish/batfish/blob/196e5874ab80733cc492d8a1a0d0836eb7209b73/projects/batfish/src/test/java/org/batfish/representation/cisco/CiscoOspfTest.java#L72)):*
> ```Java
>   @Test
>   public void testConvertRcpMetric() {
>     OspfRedistributionPolicy rcp = new OspfRedistributionPolicy(BGP);
> ```

The `c` used to mean `connected`.  You should rename.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/RouteIsClassful.java, line 10 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1138#-L9fiR8tDt8rRJtKf1f1:-L9fiR8tDt8rRJtKf1f2:b-pw304e) ([raw file](https://github.com/batfish/batfish/blob/bf268b8cdc67e076f6dcc00705e393360104a2b2/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/RouteIsClassful.java#L10)):*
> ```Java
> import org.batfish.datamodel.routing_policy.Result;
> 
> /** Returns true if the IPv4 route is classful, aka it is exactly */
> ```

Exactly what?

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/RouteIsClassful.java, line 37 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1138#-L9fiZ-jD-TrlO4sAdd8:-L9fiZ-jD-TrlO4sAdd9:b-omwmbv) ([raw file](https://github.com/batfish/batfish/blob/bf268b8cdc67e076f6dcc00705e393360104a2b2/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/RouteIsClassful.java#L37)):*
> ```Java
> 
>     Result ret = new Result();
>     ret.setBooleanValue(ip.getClassNetworkSize() >= network.getPrefixLength());
> ```

Why not `==`?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1138)*

**Comment by arifogel** [comment]
Reviewed 1 of 13 files at r1, 3 of 7 files at r2.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1138)*

**Comment by dhalperi** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/CallExpr.java, line 111 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1138#-L9fhyuh80wDdg0iVlRK:-L9fnO0h7NuJc49tvK12:b-st9chu) ([raw file](https://github.com/batfish/batfish/blob/196e5874ab80733cc492d8a1a0d0836eb7209b73/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/CallExpr.java#L111)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

You threw away the class name.
</blockquote></details>

Wrong. Please see the parent implementation.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/Conjunction.java, line 134 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1138#-L9fi88m9WWBpkCKQe4v:-L9fnQnl0w6TLjc0xDZs:br3nga2) ([raw file](https://github.com/batfish/batfish/blob/196e5874ab80733cc492d8a1a0d0836eb7209b73/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/Conjunction.java#L134)):*
> Wrong. Please see the parent implementation.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/MatchPrefixSet.java, line 99 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1138#-L9fiEIB9-DxH4N9nZwz:-L9fnRZaBQ6LLRWPtHRB:b-st9chu) ([raw file](https://github.com/batfish/batfish/blob/196e5874ab80733cc492d8a1a0d0836eb7209b73/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/MatchPrefixSet.java#L99)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Please add class name.
</blockquote></details>

Wrong. Please see the parent implementation.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/Not.java, line 85 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1138#-L9fiMrFEnNVvLEKJRss:-L9fnSCF6w7YboRnraxi:b-st9chu) ([raw file](https://github.com/batfish/batfish/blob/196e5874ab80733cc492d8a1a0d0836eb7209b73/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/Not.java#L85)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Please add class name.
</blockquote></details>

Wrong. Please see the parent implementation.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 100 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1138#-L9fivCEETtFG2btQLWW:-L9fnVjVAGand02NcmLZ:b-wpvrdf) ([raw file](https://github.com/batfish/batfish/blob/196e5874ab80733cc492d8a1a0d0836eb7209b73/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L100)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Shouldn't this be `RouteIsClassful` (one `l`).
</blockquote></details>

? It is. I think maybe you were not on the right revision in browser.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 2686 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1138#-L9fj59s225SuswVBMok:-L9fp8qk1mafrziYZ41q:b-fir7px) ([raw file](https://github.com/batfish/batfish/blob/196e5874ab80733cc492d8a1a0d0836eb7209b73/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L2686)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

`rcp` meant `Redistribute Connected Policy`. Maybe use more general local variable name?
</blockquote></details>

Done (in #1129)

---

*[projects/batfish/src/test/java/org/batfish/representation/cisco/CiscoOspfTest.java, line 47 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1138#-L9fjKbX8n2ANk-UqD-y:-L9fpB7LAC51VPTBhVRJ:bsdoash) ([raw file](https://github.com/batfish/batfish/blob/196e5874ab80733cc492d8a1a0d0836eb7209b73/projects/batfish/src/test/java/org/batfish/representation/cisco/CiscoOspfTest.java#L47)):*
> Done (in #1129)

---

*[projects/batfish/src/test/java/org/batfish/representation/cisco/CiscoOspfTest.java, line 72 at r1](https://beta.reviewable.io/reviews/batfish/batfish/1138#-L9fjQX14z5e3de90v25:-L9fpBZ_7iKgH-nrJOXX:b-fir7px) ([raw file](https://github.com/batfish/batfish/blob/196e5874ab80733cc492d8a1a0d0836eb7209b73/projects/batfish/src/test/java/org/batfish/representation/cisco/CiscoOspfTest.java#L72)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

The `c` used to mean `connected`.  You should rename.
</blockquote></details>

Done (in #1129)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1138)*

**Comment by dhalperi** [comment]
Review status: 1 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/RouteIsClassful.java, line 10 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1138#-L9fiR8tDt8rRJtKf1f1:-L9fsXUK0_isp5XsPxCy:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/bf268b8cdc67e076f6dcc00705e393360104a2b2/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/RouteIsClassful.java#L10)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Exactly what?
</blockquote></details>

Done.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/RouteIsClassful.java, line 37 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1138#-L9fiZ-jD-TrlO4sAdd8:-L9fsUJl3Bjb282Jd-Vh:bs7wunb) ([raw file](https://github.com/batfish/batfish/blob/bf268b8cdc67e076f6dcc00705e393360104a2b2/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/RouteIsClassful.java#L37)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Why not `==`?
</blockquote></details>

Done..

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1138)*

**Comment by arifogel** [comment]
Reviewed 4 of 6 files at r3.
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1138)*

**Comment by arifogel** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/RouteIsClassful.java, line 37 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1138#-L9fiZ-jD-TrlO4sAdd8:-L9fuSmT5fFxNGbuGsfu:b-udfv48) ([raw file](https://github.com/batfish/batfish/blob/bf268b8cdc67e076f6dcc00705e393360104a2b2/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/expr/RouteIsClassful.java#L37)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Done..
</blockquote></details>

Including the `-1` case here makes me uneasy. I would feel much more comfortable if you could provide a reference attesting to the classfulness of prefixes of any length whose first octet is 224 or greater.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1138)*

**Comment by arifogel** [comment]
Reviewed 1 of 6 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1138)*

**Comment by arifogel** [comment]
Reviewed 3 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://beta.reviewable.io/reviews/batfish/batfish/1138#-L9g09cVA4yuUn94RiD_:-L9g09cVA4yuUn94RiDa:bt24v9f) (no related file):*
Remaining: correct default behavior for NXOS, IOS, EOS

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1138)*

**Comment by dhalperi** [comment]
*[a discussion](https://beta.reviewable.io/reviews/batfish/batfish/1138#-L9g09cVA4yuUn94RiD_:-L9gAvVN1FDbaU-ri0Ny:b-aj45wd) (no related file):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Remaining: correct default behavior for NXOS, IOS, EOS
</blockquote></details>

PTAL. Also renamed the field inside of OspfRedistributionPolicy to be more direct to what it does, and switched the default behavior to include all subnets rather than not.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1138)*

**Comment by arifogel** [comment]
Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1138)*

**Comment by arifogel** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[a discussion](https://beta.reviewable.io/reviews/batfish/batfish/1138#-L9gCg4Z8VoyFw2DHuUR:-L9gCg4Z8VoyFw2DHuUS:bmn0h6n) (no related file):*
FYI Broken `CiscoOspfTest`

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1138)*

**Comment by arifogel** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1138#-:-L9gCumgC6_nDsD4470S:bnfp4nl)*

**Comment by dhalperi** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1138)*

**Pull request merged**
