### PR TITLE
Fix jline usage

### PR DESCRIPTION
**Pull request by dspicuzzbbn**
* Don't show exception on CTRL-D
* Only look at current word when autocompleting

---
This change is [Reviewable](https://reviewable.io/reviews/batfish/batfish/882)

### CODE REVIEW

**Comment by dspicuzzbbn** [comment]
Hm, one sec, the argument is getting double-completed, I thought I fixed that...

**Comment by dspicuzzbbn** [comment]
Ok, this is fixed now. jline 3.x seems to be word-oriented now (ish?), so you probably want to rework the completer at some point. 

It's worth noting that inserting usage code you have in there is broken, and this doesn't change that. It no longer double-completes, which currently occurs with the current master.

**Comment by ratulm** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/882#-:-L42tQL03bjNRu4way-o:bnfp4nl)*

**Comment by ratulm** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/882)*

**Pull request merged**
