### PR TITLE
Arista: add set tag and a test of route-map with continue

### PR DESCRIPTION
**Pull request by dhalperi**

### CODE REVIEW

**Review by progwriter — COMMENTED** [review]
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6466)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @arifogel, @dhalperi, and @progwriter)

___
*[projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java, line 2420 at r1](https://reviewable.io/reviews/batfish/batfish/6466#-MNW7x0u0w4woSj_Ot6e:-MNW7x0u0w4woSj_Ot6f:bm3ncki) ([raw file](https://github.com/batfish/batfish/blob/fc9d556d15fe5da149edc42f94fa11ede0e710d9/projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java#L2420)):*
> ```
> 30 match metric 3
> ```

how do I read this? nothing in the route map matches (or sets) the metric to 3

**Review by progwriter — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6466)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel and @dhalperi)

___
*[projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java, line 2420 at r1](https://reviewable.io/reviews/batfish/batfish/6466#-MNW7x0u0w4woSj_Ot6e:-MNW9_R31kpdBo1gptrD:bvhcya9) ([raw file](https://github.com/batfish/batfish/blob/fc9d556d15fe5da149edc42f94fa11ede0e710d9/projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java#L2420)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

> ```
> 30 match metric 3
> ```

how do I read this? nothing in the route map matches (or sets) the metric to 3
</blockquote></details>

I think I got it, nvm
___
*[projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_route_map_exhaustive, line 19 at r2](https://reviewable.io/reviews/batfish/batfish/6466#-MNWAA9vAmejx1esFFaR:-MNWAA9vAmejx1esFFaS:b6209ur) ([raw file](https://github.com/batfish/batfish/blob/076d4d609bb1f6ad6d93d857cb7f6ae98d23ab43/projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_route_map_exhaustive#L19)):*
> ```
> route-map RM deny 30
>  match ip address pl30
>  set metric 10
> ```

should this be `set metric 30`? otherwise asserts in the test are trivial. and I'm guessing you want to test set isn't executed on deny

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6466)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @arifogel and @progwriter)

___
*[projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java, line 2420 at r1](https://reviewable.io/reviews/batfish/batfish/6466#-MNW7x0u0w4woSj_Ot6e:-MNWGvIlB4yfCjDHhx4Y:bo5k5ok) ([raw file](https://github.com/batfish/batfish/blob/fc9d556d15fe5da149edc42f94fa11ede0e710d9/projects/batfish/src/test/java/org/batfish/grammar/arista/AristaGrammarTest.java#L2420)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

I think I got it, nvm
</blockquote></details>

Removed, stale.
___
*[projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_route_map_exhaustive, line 19 at r2](https://reviewable.io/reviews/batfish/batfish/6466#-MNWAA9vAmejx1esFFaR:-MNWGx418GPH-nOvBDFJ:b-k614gh) ([raw file](https://github.com/batfish/batfish/blob/076d4d609bb1f6ad6d93d857cb7f6ae98d23ab43/projects/batfish/src/test/resources/org/batfish/grammar/arista/testconfigs/arista_route_map_exhaustive#L19)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

should this be `set metric 30`? otherwise asserts in the test are trivial. and I'm guessing you want to test set isn't executed on deny
</blockquote></details>

Yes, thanks.

**Review by progwriter — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6466)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Pull request merged**
