### PR TITLE
Plugin folders

### LINKED ISSUE #240: question jar not built during eclipse build
The question.jar that used to be built with ant in eclipse is required to be created in order to run, even if the other projects are being run directly from class files. We need question.jar to be built by m2e in eclipse when the question project is built / question project java files are modified.

### PR DESCRIPTION
**Pull request by dspicuzzbbn**
This is useful when using batfish from eclipse. Eclipse's build process doesn't automatically create JARs (as far as I can see), so you have to do a separate mvn build to create the jar. Instead of dealing with that mess, this changes the plugin process to look for jars first, and if they're not found then see if it's a folder.

This fixes #240 (which I hadn't seen previously) and is related to #206

### CODE REVIEW

**Comment by arifogel** [comment]
@dspicuzzbbn I like this in principle. Would you be able to add tests with associated test plugins (that do not get built into jars).

**Comment by dspicuzzbbn** [comment]
Are there existing tests that explicitly test a jar plugin?

**Comment by arifogel** [comment]
@dspicuzzbbn I don't believe so, but @dhalperi can chime in. We actually discussed this yesterday. @dhalperi, should we just do the tests ourselves on this branch?

**Comment by dspicuzzbbn** [comment]
If there are existing tests that test jar plugin functionality, I'm happy to update them to test a folder based plugin. However, I won't have time to create tests from scratch.

**Pull request merged**
