### PR TITLE
Add NextHop column to Routes answerer

### PR DESCRIPTION
**Pull request by arifogel**
- add `Schema.NEXT_HOP`
- populate `COL_NEXT_HOP` using modern `NextHop` route attribute

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7838)* status: 0 of 12 files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7838#-MrKgNWT67rUcExir23y:-MrKgNWT67rUcExir23z:bvbdbtc) (no related file):*
self-merge only

---

**Review by sfraint — COMMENTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7838)* status: all files reviewed, 4 unresolved discussions (waiting on @arifogel and @dhalperi)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/Row.java, line 322 at r1](https://reviewable.io/reviews/batfish/batfish/7838#-MrOB_mxDLLm3ASEXvPy:-MrOB_mxDLLm3ASEXvPz:b-bt9ebf) ([raw file](https://github.com/batfish/batfish/blob/48e033721b3f226b2935e1fdf1c99e1a7680e4e4/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/Row.java#L322)):*
> ```Java
>   }
> 
>   public @Nullable NextHop getNextHop(String column) {
> ```

why `Nullable`? should there always be *some* nexthop?



_Code quote:_
```Java
  public @Nullable NextHop getNextHop(String column) {
    return (NextHop) get(column, Schema.NEXT_HOP);
  }
```
___
*[projects/batfish-common-protocol/src/test/java/org/batfish/common/util/NextHopComparatorTest.java, line 20 at r1](https://reviewable.io/reviews/batfish/batfish/7838#-MrOCJBs-Uoiwfmm8ON6:-MrOCJBs-Uoiwfmm8ON7:b-i94o0g) ([raw file](https://github.com/batfish/batfish/blob/48e033721b3f226b2935e1fdf1c99e1a7680e4e4/projects/batfish-common-protocol/src/test/java/org/batfish/common/util/NextHopComparatorTest.java#L20)):*
> ```Java
> 
>   @Test
>   public void testCompareClass() {
> ```

nit, for this test, would be slightly more readable / easier to maintain if the different NextHop objects were stored in variables instead of repeated for each test
```
NextHopInterface nhIface = NextHopInterface.of("foo");
...
```
___
*[projects/question/src/main/java/org/batfish/question/routes/RoutesAnswerer.java, line 253 at r1](https://reviewable.io/reviews/batfish/batfish/7838#-MrOJA778o4l9jMRQITf:-MrOJA778o4l9jMRQITg:b-tujjbk) ([raw file](https://github.com/batfish/batfish/blob/48e033721b3f226b2935e1fdf1c99e1a7680e4e4/projects/question/src/main/java/org/batfish/question/routes/RoutesAnswerer.java#L253)):*
> ```Java
>   private static final Comparator<Row> BGP_COMPARATOR =
>       Comparator.<Row, String>comparing(row -> row.getNode(COL_NODE).getName())
>           .thenComparing(row -> row.getString(COL_VRF_NAME))
> ```

is this comparator needed anymore?



_Code quote:_
```Java
  private static final Comparator<Row> BGP_COMPARATOR =
      Comparator.<Row, String>comparing(row -> row.getNode(COL_NODE).getName())
          .thenComparing(row -> row.getString(COL_VRF_NAME))
          .thenComparing(row -> row.getPrefix(COL_NETWORK))
          .thenComparing(row -> row.getNextHop(COL_NEXT_HOP), NextHopComparator.instance());
```
___
*[projects/question/src/main/java/org/batfish/question/routes/RoutesAnswerer.java, line 360 at r1](https://reviewable.io/reviews/batfish/batfish/7838#-MrOI93PCyUFq3AsFjMQ:-MrOI93PCyUFq3AsFjMR:b-fk4kgh) ([raw file](https://github.com/batfish/batfish/blob/48e033721b3f226b2935e1fdf1c99e1a7680e4e4/projects/question/src/main/java/org/batfish/question/routes/RoutesAnswerer.java#L360)):*
> ```Java
>                     COL_NEXT_HOP,
>                     Schema.NEXT_HOP,
>                     "Route's Next Hop IP",
> ```

this column is not `IP`



_Code quote:_
```Java
                    "Route's Next Hop IP",
```

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7838)* status: all files reviewed, 4 unresolved discussions (waiting on @dhalperi and @sfraint)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/Row.java, line 322 at r1](https://reviewable.io/reviews/batfish/batfish/7838#-MrOB_mxDLLm3ASEXvPy:-MrONiJC-CSJy21oxxuS:b-29ip31) ([raw file](https://github.com/batfish/batfish/blob/48e033721b3f226b2935e1fdf1c99e1a7680e4e4/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/table/Row.java#L322)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

why `Nullable`? should there always be *some* nexthop?
</blockquote></details>

Should be null for some route diffs IIRC.
___
*[projects/batfish-common-protocol/src/test/java/org/batfish/common/util/NextHopComparatorTest.java, line 20 at r1](https://reviewable.io/reviews/batfish/batfish/7838#-MrOCJBs-Uoiwfmm8ON6:-MrOOmwt-EEIkRBxZ3I3:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/48e033721b3f226b2935e1fdf1c99e1a7680e4e4/projects/batfish-common-protocol/src/test/java/org/batfish/common/util/NextHopComparatorTest.java#L20)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

nit, for this test, would be slightly more readable / easier to maintain if the different NextHop objects were stored in variables instead of repeated for each test
```
NextHopInterface nhIface = NextHopInterface.of("foo");
...
```
</blockquote></details>

done
___
*[projects/question/src/main/java/org/batfish/question/routes/RoutesAnswerer.java, line 253 at r1](https://reviewable.io/reviews/batfish/batfish/7838#-MrOJA778o4l9jMRQITf:-MrOPNnf-mQxDTSHrFY6:bbcug2e) ([raw file](https://github.com/batfish/batfish/blob/48e033721b3f226b2935e1fdf1c99e1a7680e4e4/projects/question/src/main/java/org/batfish/question/routes/RoutesAnswerer.java#L253)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

is this comparator needed anymore?
</blockquote></details>

Why wouldn't it be? It has two usages in `answer`:
```
    switch (question.getRib()) {
      case BGP:
        rows.addAll(
            getBgpRibRoutes(
                dp.getBgpRoutes(),
                dp.getBgpBackupRoutes(),
                matchingVrfsByNode,
                network,
                protocolSpec,
                expandedBgpRouteStatuses,
                question.getPrefixMatchType()));
        rows.sort(BGP_COMPARATOR);
        break;
      case EVPN:
        rows.addAll(
            getEvpnRoutes(
                dp.getEvpnRoutes(),
                dp.getEvpnBackupRoutes(),
                matchingVrfsByNode,
                network,
                protocolSpec,
                ImmutableSet.of(BEST, BACKUP),
                question.getPrefixMatchType()));
        rows.sort(BGP_COMPARATOR);
        break;
```
___
*[projects/question/src/main/java/org/batfish/question/routes/RoutesAnswerer.java, line 360 at r1](https://reviewable.io/reviews/batfish/batfish/7838#-MrOI93PCyUFq3AsFjMQ:-MrOPAnn4W9ajh9o_Bm3:b-7ql1td) ([raw file](https://github.com/batfish/batfish/blob/48e033721b3f226b2935e1fdf1c99e1a7680e4e4/projects/question/src/main/java/org/batfish/question/routes/RoutesAnswerer.java#L360)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

this column is not `IP`
</blockquote></details>

fixed

**Review by sfraint — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7838)* status: all files reviewed, 2 unresolved discussions (waiting on @arifogel and @dhalperi)

___
*[projects/question/src/main/java/org/batfish/question/routes/RoutesAnswerer.java, line 253 at r1](https://reviewable.io/reviews/batfish/batfish/7838#-MrOJA778o4l9jMRQITf:-MrOPsBADIdmbmBWjmHY:bcusqkl) ([raw file](https://github.com/batfish/batfish/blob/48e033721b3f226b2935e1fdf1c99e1a7680e4e4/projects/question/src/main/java/org/batfish/question/routes/RoutesAnswerer.java#L253)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Why wouldn't it be? It has two usages in `answer`:
```
    switch (question.getRib()) {
      case BGP:
        rows.addAll(
            getBgpRibRoutes(
                dp.getBgpRoutes(),
                dp.getBgpBackupRoutes(),
                matchingVrfsByNode,
                network,
                protocolSpec,
                expandedBgpRouteStatuses,
                question.getPrefixMatchType()));
        rows.sort(BGP_COMPARATOR);
        break;
      case EVPN:
        rows.addAll(
            getEvpnRoutes(
                dp.getEvpnRoutes(),
                dp.getEvpnBackupRoutes(),
                matchingVrfsByNode,
                network,
                protocolSpec,
                ImmutableSet.of(BEST, BACKUP),
                question.getPrefixMatchType()));
        rows.sort(BGP_COMPARATOR);
        break;
```
</blockquote></details>

Sorry, I meant: is this comparator identical to the `MAIN_RIB_COMPARATOR` now that nexthop column comparison is consolidated? if so, do we need to keep two separate, identical comparator instances or can we migrate all usage onto the main rib one?

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7838)* status: all files reviewed, 2 unresolved discussions (waiting on @dhalperi and @sfraint)

___
*[projects/question/src/main/java/org/batfish/question/routes/RoutesAnswerer.java, line 253 at r1](https://reviewable.io/reviews/batfish/batfish/7838#-MrOJA778o4l9jMRQITf:-MrOVcvF1f1pMEzjZUy9:bndioge) ([raw file](https://github.com/batfish/batfish/blob/48e033721b3f226b2935e1fdf1c99e1a7680e4e4/projects/question/src/main/java/org/batfish/question/routes/RoutesAnswerer.java#L253)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

Sorry, I meant: is this comparator identical to the `MAIN_RIB_COMPARATOR` now that nexthop column comparison is consolidated? if so, do we need to keep two separate, identical comparator instances or can we migrate all usage onto the main rib one?
</blockquote></details>

Ah gotcha. It's possible we may want to sort by some BGP-rib-specific columns in the future. I'd prefer to investigate and address in a separate PR, since I consider that to be out of scope for this PR.

**Review by dhalperi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7838)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi and @sfraint)

**Pull request merged**
