### PR TITLE
ibdp: redo messageQueueStream

### PR DESCRIPTION
**Pull request by dhalperi**
1. Fixes a bug in EIGRP
2. Moves common logic
3. Improves hash by including keys

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7924)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java, line 2050 at r1](https://reviewable.io/reviews/batfish/batfish/7924#-MtAsFud93RnEwFwsLe8:-MtAsFue4Q5w8cSGHqrA:b-g6t9x7) ([raw file](https://github.com/batfish/batfish/blob/d417d7e5e036294b80cc0928306e70216c6d6093/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/BgpRoutingProcess.java#L2050)):*
> ```Java
>                 _bgpv4DeltaPrev,
>                 _bgpv4DeltaPrevBestPath),
>             // Message queues
> ```

FYI accidentally deleted in #7922 



_Code quote:_
```Java
   // Message queues
```
___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/DataplaneUtil.java, line 168 at r1](https://reviewable.io/reviews/batfish/batfish/7924#-MtAsMr96UrdNtu1CPls:-MtAsMrADsBzNnZEa9Wb:b-51xi8x) ([raw file](https://github.com/batfish/batfish/blob/d417d7e5e036294b80cc0928306e70216c6d6093/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/DataplaneUtil.java#L168)):*
> ```Java
>       Entry<E, Queue<RouteAdvertisement<R>>> entry) {
>     E key = entry.getKey();
>     Stream<RouteAdvertisement<R>> advertisementStream = entry.getValue().stream();
> ```

FYI types here intended to guarantee we're hashing messaged



_Code quote:_
```Java
Stream<RouteAdvertisement<R>> advertisementStream = entry.getValue().stream();
```
___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/EigrpRoutingProcess.java, line 603 at r1](https://reviewable.io/reviews/batfish/batfish/7924#-MtAsWDBDNjLo67fMJ2y:-MtAsWDBDNjLo67fMJ2z:b-s06r03) ([raw file](https://github.com/batfish/batfish/blob/691000b6271b0bf80a7ce7a2bc24b179d95f3180/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/EigrpRoutingProcess.java#L603)):*
> ```Java
>     return Streams.concat(
>             Stream.of(_rib),
>             _incomingInternalRoutes.values().stream(),
> ```

FYI bug was missing `Queue::stream` here



_Code quote:_
```Java
values().stream()
```

**Review by corinaminer — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7924)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java, line 1691 at r1](https://reviewable.io/reviews/batfish/batfish/7924#-MtAsoOY8QJmgHXzjBiM:-MtAsoOY8QJmgHXzjBiN:b-ltai0e) ([raw file](https://github.com/batfish/batfish/blob/691000b6271b0bf80a7ce7a2bc24b179d95f3180/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java#L1691)):*
> ```Java
>                 .flatMap(m -> m.values().stream())
>                 .flatMap(Queue::stream),
>             // Deltas
> ```

nit: could keep this comment to clarify that `_activatedGeneratedRoutes` does not fall under message queues

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7924)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java, line 1691 at r1](https://reviewable.io/reviews/batfish/batfish/7924#-MtAsoOY8QJmgHXzjBiM:-MtAtqHyEo-Y2FtyF37P:b-834ljk) ([raw file](https://github.com/batfish/batfish/blob/691000b6271b0bf80a7ce7a2bc24b179d95f3180/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/OspfRoutingProcess.java#L1691)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

nit: could keep this comment to clarify that `_activatedGeneratedRoutes` does not fall under message queues
</blockquote></details>

yeah just an accident. adding back.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7924)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Pull request merged**
