### PR TITLE
Check Point gateway: initial bonding group support

### PR DESCRIPTION
**Pull request by sfraint**
Add extraction and conversion for `bonding group`s and their interfaces.

----

Ended up adding some special extraction logic dividing `bonding group` extraction into a `configuration` and `reconfiguration` mode.

The `configuration` mode allows undefined references for member interfaces (since `bonding group` configuration appears before `interface` configuration in `show configuration` output); this mode is used until the first interface has been explicitly configured.

The `reconfiguration` mode acts more like the device CLI and rejects undefined references as well as references to interfaces whose configuration is incompatible with being bonding group members.

### CODE REVIEW

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7189)* status: 0 of 13 files reviewed, all discussions resolved (waiting on @arifogel and @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/Interface.java, line 23 at r1](https://reviewable.io/reviews/batfish/batfish/7189#-Mf4kbWfCJBBDUn0a5Fl:-Mf4kbWfCJBBDUn0a5Fm:b-nef9ef) ([raw file](https://github.com/batfish/batfish/blob/3f9310c25f26992c208b87d9ffcb87104ee883dc/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/Interface.java#L23)):*
> ```
>    _state = true;
> ```
before, we didn't really support any interfaces that could exist without an explicit `set ... state <on|off>` command

so, this was wrong, but didn't have much effect

**Review by dhalperi — COMMENTED** [review]
> Reviewed 12 of 13 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7189)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7189)* status: 12 of 13 files reviewed, all discussions resolved (waiting on @arifogel and @dhalperi)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7189)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Pull request merged**
