### PR TITLE
CheckPoint: pasre `Service` json files

### PR DESCRIPTION
**Pull request by sfraint**

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7352)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi and @sfraint)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/BfConsts.java, line 134 at r1](https://reviewable.io/reviews/batfish/batfish/7352#-Mj61eB72JGQbrHhZgPm:-Mj61eB72JGQbrHhZgPn:by88f35) ([raw file](https://github.com/batfish/batfish/blob/49d5ca6ce934fcbc4f9dcc1968cc4e69a459eebf/projects/batfish-common-protocol/src/main/java/org/batfish/common/BfConsts.java#L134)):*
> ```Java
>   public static final String RELPATH_CHECKPOINT_SHOW_NETWORKS = "show-networks.json";
>   public static final String RELPATH_CHECKPOINT_SHOW_PACKAGE = "show-package.json";
>   public static final String RELPATH_CHECKPOINT_SHOW_SERVICE_GROUPS = "show-service-groups.json";
> ```

Can you move any new such constants to `CheckpointManagementParser`?

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7352)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel and @dhalperi)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/BfConsts.java, line 134 at r1](https://reviewable.io/reviews/batfish/batfish/7352#-Mj61eB72JGQbrHhZgPm:-Mj622PM18Gb10Xnl-A0:b-7mmp82) ([raw file](https://github.com/batfish/batfish/blob/49d5ca6ce934fcbc4f9dcc1968cc4e69a459eebf/projects/batfish-common-protocol/src/main/java/org/batfish/common/BfConsts.java#L134)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Can you move any new such constants to `CheckpointManagementParser`?
</blockquote></details>

moved

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7352)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @arifogel, @dhalperi, and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7352#-Mj625EU-QYLpWMJDhff:-Mj625EV5Zi3WaG6mTwH:bxpm8pw) (no related file):*
Please test`buildObjectsList` in `CheckpointManagementParserTest`, time permitting.

---

**Review by arifogel — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7352)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @dhalperi and @sfraint)

**Review by arifogel — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7352)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi and @sfraint)

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7352)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @arifogel and @dhalperi)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7352#-Mj625EU-QYLpWMJDhff:-Mj6DUX29NX9v84GwXjM:b-7tfmjp) (no related file):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Please test`buildObjectsList` in `CheckpointManagementParserTest`, time permitting.
</blockquote></details>

added

---

**Review by arifogel — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7352)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_management/parsing/CheckpointManagementParser.java, line 460 at r3](https://reviewable.io/reviews/batfish/batfish/7352#-Mj6EdWY-xy5LoLQJeyv:-Mj6EdWY-xy5LoLQJeyw:b9408hq) ([raw file](https://github.com/batfish/batfish/blob/e449a73e2f7ddfb2abc6e95cad79107bc6f6ead6/projects/batfish/src/main/java/org/batfish/vendor/check_point_management/parsing/CheckpointManagementParser.java#L460)):*
> ```Java
>   static final String RELPATH_CHECKPOINT_SHOW_SERVICE_GROUPS = "show-service-groups.json";
>   static final String RELPATH_CHECKPOINT_SHOW_SERVICES_ICMP = "show-services-icmp.json";
>   static final String RELPATH_CHECKPOINT_SHOW_SERVICES_OTHER = "show-services-other.json";
> ```

nit: Add `@VisibleForTesting` to these

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7352)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dhalperi)

**Review by arifogel — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7352)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dhalperi)

**Pull request merged**
