### PR TITLE
NXOS: Fix default tag for BGP imports

### PR DESCRIPTION
**Pull request by corinaminer**
Currently when NX-OS devices receive BGP routes, Batfish tags them with the receiving peer's remote AS. This is incorrect; they should be tagged with the latest AS in the received route's AS-path, unless the inbound route-map explicitly sets the tag to something else.

This PR contains a 3-step fix:
1. Introduce a routing policy statement `SetDefaultTag`, which behaves like `SetTag` except that it is not applied if a tag has been explicitly set in the current routing policy (as reflected by a new `Environment` field `_tagExplicitlySet`).
2. Include AS path in the intermediate BGP attributes stored in `Environment`. This allows the default tag to reflect any modifications to the AS path made by the inbound route-map.
3. Update NX-OS BGP import policy conversion. Import policy looks the same as before if there's no inbound route-map, but otherwise uses this structure:
```
SetWriteIntermediateBgpAttributes
if (CallExpr(inboundRouteMap)):
  SetReadIntermediateBgpAttributes
  SetDefaultTag
  ExitAccept
ExitReject
```

### CODE REVIEW

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6985)* status: 0 of 11 files reviewed, all discussions resolved (waiting on @dhalperi)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6985#-MZzBgMfBAVSAVSNfdeM:-MZzBgMfBAVSAVSNfdeN:b8fjcc5) (no related file):*
Forgot to mention in description: The NX-OS conversion logic now uses `AutoAs` rather than `RemoteAs` to resolve the actual tag. `AutoAs` already existed, apparently for the purpose of determining default tag in cases like this (it resolves to latest AS when processing inbound routes).

---

**Review by dhalperi — COMMENTED** [review]
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6985)* status: all files reviewed, 5 unresolved discussions (waiting on @corinaminer)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6985#-MZzBgMfBAVSAVSNfdeM:-MZzu3mT91XevodGEd1H:b-8ft9vm) (no related file):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Forgot to mention in description: The NX-OS conversion logic now uses `AutoAs` rather than `RemoteAs` to resolve the actual tag. `AutoAs` already existed, apparently for the purpose of determining default tag in cases like this (it resolves to latest AS when processing inbound routes).
</blockquote></details>

:100:

---
___
*[projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java, line 783 at r1](https://reviewable.io/reviews/batfish/batfish/6985#-MZzttfvCrHtlDMZr6JZ:-MZzttfvCrHtlDMZr6J_:b-6i10hg) ([raw file](https://github.com/batfish/batfish/blob/5de1c83717849a0f0f7d6d95cceeb8ca8e185fb7/projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java#L783)):*
> ```
> outputRoute.build().getTag(), equalTo(200L));
> ```
FYI there is a `hasTag` matcher.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/Environment.java, line 241 at r1](https://reviewable.io/reviews/batfish/batfish/6985#-MZzsIz12b07ViwlEqXw:-MZzsIz12b07ViwlEqXx:bhqtosi) ([raw file](https://github.com/batfish/batfish/blob/5de1c83717849a0f0f7d6d95cceeb8ca8e185fb7/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/Environment.java#L241)):*
> ```
>   public boolean getTagExplicitlySet() {
>     return _tagExplicitlySet;
> ```

Dumb Q: do we need this, or can we use something like `!_outputRoute.hasTag()`, where that hypothetical function is implemented by `_tag != UNSET_TAG`
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/SetDefaultTag.java, line 19 at r1](https://reviewable.io/reviews/batfish/batfish/6985#-MZztURN7RaMGojo_V0C:-MZztURN7RaMGojo_V0D:b-1hrbbg) ([raw file](https://github.com/batfish/batfish/blob/5de1c83717849a0f0f7d6d95cceeb8ca8e185fb7/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/SetDefaultTag.java#L19)):*
> ```Java
>  */
> @ParametersAreNonnullByDefault
> public final class SetDefaultTag extends Statement {
> ```

Add tests - equals, serialization, execute.
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/SetDefaultTag.java, line 72 at r1](https://reviewable.io/reviews/batfish/batfish/6985#-MZztcTD-uFH5pN61Wlj:-MZztcTD-uFH5pN61Wlk:b-wf4p9f) ([raw file](https://github.com/batfish/batfish/blob/5de1c83717849a0f0f7d6d95cceeb8ca8e185fb7/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/SetDefaultTag.java#L72)):*
> ```Java
>     final int prime = 31;
>     int result = 1;
>     result = prime * result + _tag.hashCode();
> ```

just `_tag.hashCode()`?
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/Statements.java, line 133 at r1](https://reviewable.io/reviews/batfish/batfish/6985#-MZzt6LI5M0T3evcq-b0:-MZzt6LI5M0T3evcq-b1:bk5qvev) ([raw file](https://github.com/batfish/batfish/blob/4637031cb6842915c7355befac79386e57dfb44d/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/Statements.java#L133)):*
> ```
> BgpRoute
> ```
Use `HasReadableCommunities` instead? Same reason as below.

cc: @arifogel -- why or why not?
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/Statements.java, line 137 at r1](https://reviewable.io/reviews/batfish/batfish/6985#-MZzt0mm8pQBuYNpjvKB:-MZzt0mm8pQBuYNpjvKC:bw7wagn) ([raw file](https://github.com/batfish/batfish/blob/5de1c83717849a0f0f7d6d95cceeb8ca8e185fb7/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/Statements.java#L137)):*
> ```
> instanceof BgpRoute)
> ```

use `HasReadableAsPath` instead? That will capture things like generated routes too.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6985)* status: all files reviewed, 5 unresolved discussions (waiting on @corinaminer and @dhalperi)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/Statements.java, line 133 at r1](https://reviewable.io/reviews/batfish/batfish/6985#-MZzt6LI5M0T3evcq-b0:-MZzukx57FUcQsWulfy8:b-eqqybs) ([raw file](https://github.com/batfish/batfish/blob/4637031cb6842915c7355befac79386e57dfb44d/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/Statements.java#L133)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> BgpRoute
> ```
Use `HasReadableCommunities` instead? Same reason as below.

cc: @arifogel -- why or why not?
</blockquote></details>

Your explanation in the other comment is correct; it's for generated routes.

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6985)* status: 7 of 15 files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java, line 783 at r1](https://reviewable.io/reviews/batfish/batfish/6985#-MZzttfvCrHtlDMZr6JZ:-M_1wPF8EjJJN4HIPtNy:b6546h6) ([raw file](https://github.com/batfish/batfish/blob/5de1c83717849a0f0f7d6d95cceeb8ca8e185fb7/projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/CiscoNxosGrammarTest.java#L783)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> outputRoute.build().getTag(), equalTo(200L));
> ```
FYI there is a `hasTag` matcher.
</blockquote></details>

done (used it)
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/Environment.java, line 241 at r1](https://reviewable.io/reviews/batfish/batfish/6985#-MZzsIz12b07ViwlEqXw:-M_2080x1xTdfw0Rg6fF:bvyn5e0) ([raw file](https://github.com/batfish/batfish/blob/5de1c83717849a0f0f7d6d95cceeb8ca8e185fb7/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/Environment.java#L241)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
>   public boolean getTagExplicitlySet() {
>     return _tagExplicitlySet;
> ```

Dumb Q: do we need this, or can we use something like `!_outputRoute.hasTag()`, where that hypothetical function is implemented by `_tag != UNSET_TAG`
</blockquote></details>

I didn't want to do this just in case the incoming route already had a tag. That shouldn't happen, right, because tags should be stripped between devices? But `BgpProtocolHelper.transformBgpRouteOnImport` copies the tag from the original route, and at least in `EvpnTest.testEvpnSymmetricSingleSpine` there's a case where a route arriving for import has a tag of `0` rather than `UNSET` (i.e. -1).
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/SetDefaultTag.java, line 19 at r1](https://reviewable.io/reviews/batfish/batfish/6985#-MZztURN7RaMGojo_V0C:-M_24aHZ98sBbn-C8dBI:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/5de1c83717849a0f0f7d6d95cceeb8ca8e185fb7/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/SetDefaultTag.java#L19)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Add tests - equals, serialization, execute.
</blockquote></details>

done
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/SetDefaultTag.java, line 72 at r1](https://reviewable.io/reviews/batfish/batfish/6985#-MZztcTD-uFH5pN61Wlj:-M_1z5Nv6pjRbkZqxPV1:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/5de1c83717849a0f0f7d6d95cceeb8ca8e185fb7/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/SetDefaultTag.java#L72)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

just `_tag.hashCode()`?
</blockquote></details>

done
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/Statements.java, line 133 at r1](https://reviewable.io/reviews/batfish/batfish/6985#-MZzt6LI5M0T3evcq-b0:-M_1zuro3l3NKedbE4gh:bb6un1j) ([raw file](https://github.com/batfish/batfish/blob/4637031cb6842915c7355befac79386e57dfb44d/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/Statements.java#L133)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Your explanation in the other comment is correct; it's for generated routes.
</blockquote></details>

Done
___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/Statements.java, line 137 at r1](https://reviewable.io/reviews/batfish/batfish/6985#-MZzt0mm8pQBuYNpjvKB:-M_1zvbY1ItI3q7w8ce1:bb6un1j) ([raw file](https://github.com/batfish/batfish/blob/5de1c83717849a0f0f7d6d95cceeb8ca8e185fb7/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/statement/Statements.java#L137)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> instanceof BgpRoute)
> ```

use `HasReadableAsPath` instead? That will capture things like generated routes too.
</blockquote></details>

Done

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6985)* status: 7 of 15 files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/NxosBgpTest.java, line 191 at r3](https://reviewable.io/reviews/batfish/batfish/6985#-M_25j6yB7EPCbFZAloo:-M_25j6zE15OfYY3P48g:b-6saabs) ([raw file](https://github.com/batfish/batfish/blob/8ff11d574fc68a0d2514a0ebdaebd4efc398b02d/projects/batfish/src/test/java/org/batfish/grammar/cisco_nxos/NxosBgpTest.java#L191)):*
> ```Java
> 
>   @Test
>   public void testBgpTagImportedRoutes() throws IOException {
> ```

fyi, moved from `CiscoNxosGrammarTest` with no changes other than making it use `hasTag`

**Review by dhalperi — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 5 files at r2, 3 of 4 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6985#-:-M_27LFq-lqD_zeC9rg4:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @corinaminer)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/Environment.java, line 241 at r1](https://reviewable.io/reviews/batfish/batfish/6985#-MZzsIz12b07ViwlEqXw:-M_27PeA96ToueOllNKP:bbw2m8y) ([raw file](https://github.com/batfish/batfish/blob/5de1c83717849a0f0f7d6d95cceeb8ca8e185fb7/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/Environment.java#L241)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

I didn't want to do this just in case the incoming route already had a tag. That shouldn't happen, right, because tags should be stripped between devices? But `BgpProtocolHelper.transformBgpRouteOnImport` copies the tag from the original route, and at least in `EvpnTest.testEvpnSymmetricSingleSpine` there's a case where a route arriving for import has a tag of `0` rather than `UNSET` (i.e. -1).
</blockquote></details>

BGP routes should have unset tag between devices, yes. But up to you. My guess is that EVPN test is buggy, or modeled the current (master) behavior where the tag was shoved in before import policy.

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6985)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

___
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/Environment.java, line 241 at r1](https://reviewable.io/reviews/batfish/batfish/6985#-MZzsIz12b07ViwlEqXw:-M_3JlwT83OTJsnoc4L9:b-tzxr88) ([raw file](https://github.com/batfish/batfish/blob/5de1c83717849a0f0f7d6d95cceeb8ca8e185fb7/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/routing_policy/Environment.java#L241)):*
> My guess is that EVPN test is buggy, or...

That would've been my guess too, except that I saw that tag `0` on an incoming route during `computeDataPlane()` -- the test isn't mocking up any routes. So I suspect there's a real tag-preserving bug. Not investigating that currently, though

**Pull request merged**
