### PR TITLE
add OriginateInterface state and transitions

### PR DESCRIPTION
**Pull request by anothermattbrown**
Introducing NOD infrastructure for originate interface -- not currently used by questions (that will be a separate PR).

### CODE REVIEW

**Comment by arifogel** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[projects/batfish/src/main/java/org/batfish/z3/state/visitors/DefaultTransitionGenerator.java, line 96 at r1](https://reviewable.io/reviews/batfish/batfish/1265#-LBMtb7G75t6zEG7RCoT:-LBMtb7G75t6zEG7RCoU:b-9m41mk) ([raw file](https://github.com/batfish/batfish/blob/a3dbc70a77d08ead121a9bf67c1be49561c33b16/projects/batfish/src/main/java/org/batfish/z3/state/visitors/DefaultTransitionGenerator.java#L96)):*
> ```Java
>   private @Nonnull BooleanExpr noSrcInterfaceConstraint() {
>     Field srcInterface = _input.getSourceInterfaceField();
>     return new EqExpr(new VarIntExpr(srcInterface), new LitIntExpr(0, srcInterface.getSize()));
> ```

Did you mean to use the `NO_SOURCE_INTERFACE` constant here in place of `0`?

---

*[projects/batfish/src/main/java/org/batfish/z3/state/visitors/DefaultTransitionGenerator.java, line 613 at r1](https://reviewable.io/reviews/batfish/batfish/1265#-LBMtxfl2OgTP1X7Nd6P:-LBMtxfl2OgTP1X7Nd6Q:b-jp0rg0) ([raw file](https://github.com/batfish/batfish/blob/a3dbc70a77d08ead121a9bf67c1be49561c33b16/projects/batfish/src/main/java/org/batfish/z3/state/visitors/DefaultTransitionGenerator.java#L613)):*
> ```Java
>                       iface ->
>                           new BasicRuleStatement(
>                               srcInterfaceConstraint(hostname, iface),
> ```

Is this needed for the projection?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1265)*

**Comment by anothermattbrown** [comment]
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/z3/state/visitors/DefaultTransitionGenerator.java, line 613 at r1](https://reviewable.io/reviews/batfish/batfish/1265#-LBMtxfl2OgTP1X7Nd6P:-LBNMuBu-vKxeI0eZGbJ:b-eva5bg) ([raw file](https://github.com/batfish/batfish/blob/a3dbc70a77d08ead121a9bf67c1be49561c33b16/projects/batfish/src/main/java/org/batfish/z3/state/visitors/DefaultTransitionGenerator.java#L613)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Is this needed for the projection?
</blockquote></details>

I think so. Is there a reason it wouldn't be?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1265)*

**Comment by anothermattbrown** [comment]
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/z3/state/visitors/DefaultTransitionGenerator.java, line 96 at r1](https://reviewable.io/reviews/batfish/batfish/1265#-LBMtb7G75t6zEG7RCoT:-LBNNfa18QOTI4zIa-i8:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/a3dbc70a77d08ead121a9bf67c1be49561c33b16/projects/batfish/src/main/java/org/batfish/z3/state/visitors/DefaultTransitionGenerator.java#L96)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Did you mean to use the `NO_SOURCE_INTERFACE` constant here in place of `0`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1265)*

**Comment by arifogel** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/java/org/batfish/z3/state/visitors/DefaultTransitionGenerator.java, line 613 at r1](https://reviewable.io/reviews/batfish/batfish/1265#-LBMtxfl2OgTP1X7Nd6P:-LBNZa6N0lkJ3sJGkUFP:b-nx7w6b) ([raw file](https://github.com/batfish/batfish/blob/a3dbc70a77d08ead121a9bf67c1be49561c33b16/projects/batfish/src/main/java/org/batfish/z3/state/visitors/DefaultTransitionGenerator.java#L613)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

I think so. Is there a reason it wouldn't be?
</blockquote></details>

1. With that additional constraint it's not really a projection is it?
2. I suppose you need to enforce that constraint somewhere. If this is the only place that does it, then it is in fact needed. I'll defer to you on that.
Marking as satisfied for now.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1265#-:-LBN_L80EhlYyu4Dj3-C:bnfp4nl)*

**Pull request merged**
