### PR TITLE
Frr: Default originate with route map

### PR DESCRIPTION
**Pull request by ratulm**

### CODE REVIEW

**Review by corinaminer — COMMENTED** [review]
> Reviewed 9 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7749)* status: all files reviewed, 4 unresolved discussions (waiting on @ratulm)

___
*[projects/batfish/src/main/java/org/batfish/representation/frr/FrrConversions.java, line 702 at r2](https://reviewable.io/reviews/batfish/batfish/7749#-Mq0lyLy8TT4lO_rNHyC:-Mq0lyLy8TT4lO_rNHyD:b5ijo5v) ([raw file](https://github.com/batfish/batfish/blob/c5b5f34154f49454810926669f4b23aface1f761/projects/batfish/src/main/java/org/batfish/representation/frr/FrrConversions.java#L702)):*
> ```Java
> 
>     // If default originate is set for a neighbor, we will send it a "fresh" default route. This
>     // route is subjected to defaultOriginateRouteMap, not to the neighbor's outgoing route map.
> ```

While this is technically true, it's confusing because these route-maps serve totally different purposes. This comment is mainly about the export process for the default-originate route, so I wouldn't even bother mentioning the attribute policy (i.e. default-originate route-map) here; that was already applied when the route was generated.
___
*[projects/batfish/src/main/java/org/batfish/representation/frr/FrrConversions.java, line 1759 at r2](https://reviewable.io/reviews/batfish/batfish/7749#-Mq0mWrA8GZkI_SO0ysK:-Mq0mWrA8GZkI_SO0ysL:b-ihfbvc) ([raw file](https://github.com/batfish/batfish/blob/c5b5f34154f49454810926669f4b23aface1f761/projects/batfish/src/main/java/org/batfish/representation/frr/FrrConversions.java#L1759)):*
> ```Java
>         .setNetwork(Prefix.ZERO)
>         .setAdmin(MAX_ADMINISTRATIVE_COST)
>         .setAttributePolicy(routeMapName)
> ```

you confirmed in lab or docs that the purpose of this route-map is to set attributes? I don't see the route-map option [here](http://docs.frrouting.org/en/latest/bgp.html?highlight=default-originate#clicmd-neighbor-PEER-default-originate)
___
*[projects/batfish/src/test/resources/org/batfish/grammar/frr/snapshots/default-originate-route-map/configs/frr-originator, line 28 at r2](https://reviewable.io/reviews/batfish/batfish/7749#-Mq0r9cu2ymsJGrJ8nKT:-Mq0r9cu2ymsJGrJ8nKU:bl9s4e3) ([raw file](https://github.com/batfish/batfish/blob/c5b5f34154f49454810926669f4b23aface1f761/projects/batfish/src/test/resources/org/batfish/grammar/frr/snapshots/default-originate-route-map/configs/frr-originator#L28)):*
> ```
>  bgp router-id 2.2.2.2
>  neighbor 10.1.1.1 remote-as 1
>  neighbor 30.1.1.3 remote-as 3
> ```

this neighbor (and interface swp3) aren't necessary
___
*[projects/batfish/src/test/resources/org/batfish/grammar/frr/snapshots/default-originate-route-map/configs/frr-originator, line 38 at r2](https://reviewable.io/reviews/batfish/batfish/7749#-Mq0qELgAwkUO7TfWHqv:-Mq0qELgAwkUO7TfWHqw:b-pe4jmc) ([raw file](https://github.com/batfish/batfish/blob/c5b5f34154f49454810926669f4b23aface1f761/projects/batfish/src/test/resources/org/batfish/grammar/frr/snapshots/default-originate-route-map/configs/frr-originator#L38)):*
> ```
> !
> route-map RM_TEST permit 10
>  match ip address prefix-list PL_DEFAULT
> ```

I don't think it's necessary to have a match clause in this route-map; in fact, i'm not sure it would do anything even if the default-originate route didn't match it.

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7749)* status: all files reviewed, 1 unresolved discussion (waiting on @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/representation/frr/FrrConversions.java, line 1759 at r2](https://reviewable.io/reviews/batfish/batfish/7749#-Mq0mWrA8GZkI_SO0ysK:-Mq2puhi7LXiOJkp243q:b-1c0yvx) ([raw file](https://github.com/batfish/batfish/blob/c5b5f34154f49454810926669f4b23aface1f761/projects/batfish/src/main/java/org/batfish/representation/frr/FrrConversions.java#L1759)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

you confirmed in lab or docs that the purpose of this route-map is to set attributes? I don't see the route-map option [here](http://docs.frrouting.org/en/latest/bgp.html?highlight=default-originate#clicmd-neighbor-PEER-default-originate)
</blockquote></details>

I was trusting the user. But I'll hold off until I can understand better.

**Review by corinaminer — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7749#-:-MqFuxJgCOir2-r5X5Fa:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ratulm)

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7749)* status: 3 of 12 files reviewed, all discussions resolved (waiting on @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/representation/frr/FrrConversions.java, line 1759 at r2](https://reviewable.io/reviews/batfish/batfish/7749#-Mq0mWrA8GZkI_SO0ysK:-MqXykHW-or86LjzbLAJ:b-7eqkjg) ([raw file](https://github.com/batfish/batfish/blob/c5b5f34154f49454810926669f4b23aface1f761/projects/batfish/src/main/java/org/batfish/representation/frr/FrrConversions.java#L1759)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

I was trusting the user. But I'll hold off until I can understand better.
</blockquote></details>

In progress docs: https://github.com/FRRouting/frr/pull/10181/files

The route map decides when to generate the default route and what attributes to set.

**Review by corinaminer — COMMENTED** [review]
> Reviewed 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7749)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ratulm)

**Pull request merged**
