### PR TITLE
FortiOS: firewall policy parsing and extraction

### PR DESCRIPTION
**Pull request by sfraint**

### CODE REVIEW

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6697)* status: 0 of 9 files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6697#-MV3YuWmCuCFA1o090Bc:-MV3YuWmCuCFA1o090Bd:b-qjveu2) (no related file):*
Handling the special `any`/`all` cases will come in a subsequent PR

---

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6697)* status: 0 of 9 files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6697#-MV3YuWmCuCFA1o090Bc:-MV3ZIzTC5ek02uH5SiM:bsn5ggx) (no related file):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

Handling the special `any`/`all` cases will come in a subsequent PR
</blockquote></details>

(Same story for structure references/definitions: subsequent PR)

---

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6697)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @sfraint)

___
*[projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java, line 484 at r3](https://reviewable.io/reviews/batfish/batfish/6697#-MV3_gXg4Cxg4l6g8aKL:-MV3_gXg4Cxg4l6g8aKM:bjafh4a) ([raw file](https://github.com/batfish/batfish/blob/7917ca8a48b6ad94b055c7de3c824d9720fd1b76/projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java#L484)):*
> ```Java
>     assertThat(policyAllow.getSrcAddr(), containsInAnyOrder(addr1, addr2));
>     assertThat(policyAllow.getDstAddr(), containsInAnyOrder(addr1, addr2));
>   }
> ```

Also going to add a test of the new warnings

**Review by arifogel — COMMENTED** [review]
> Reviewed 3 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6697)* status: 3 of 9 files reviewed, 2 unresolved discussions (waiting on @corinaminer and @sfraint)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_policy.g4, line 11 at r3](https://reviewable.io/reviews/batfish/batfish/6697#-MV3b90I14OI5S30ClBy:-MV3b90I14OI5S30ClBz:b-n2lisk) ([raw file](https://github.com/batfish/batfish/blob/7917ca8a48b6ad94b055c7de3c824d9720fd1b76/projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_policy.g4#L11)):*
> ```ANTLR
> cfp_edit
> :
>     EDIT policy_number NEWLINE (
> ```

Everything in parens needs to be pulled out into a different rule for recovery. Generally applicable for `(thing starting on its own line)*`

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6697)* status: 2 of 10 files reviewed, 1 unresolved discussion (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_policy.g4, line 11 at r3](https://reviewable.io/reviews/batfish/batfish/6697#-MV3b90I14OI5S30ClBy:-MV3hL4v4IZltnjtAiaJ:bvnrpcm) ([raw file](https://github.com/batfish/batfish/blob/7917ca8a48b6ad94b055c7de3c824d9720fd1b76/projects/batfish/src/main/antlr4/org/batfish/grammar/fortios/Fortios_policy.g4#L11)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Everything in parens needs to be pulled out into a different rule for recovery. Generally applicable for `(thing starting on its own line)*`
</blockquote></details>

updated
___
*[projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java, line 484 at r3](https://reviewable.io/reviews/batfish/batfish/6697#-MV3_gXg4Cxg4l6g8aKL:-MV3lLEd6B1_6dAQOAgx:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/7917ca8a48b6ad94b055c7de3c824d9720fd1b76/projects/batfish/src/test/java/org/batfish/grammar/fortios/FortiosGrammarTest.java#L484)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

Also going to add a test of the new warnings
</blockquote></details>

done

**Review by arifogel — COMMENTED** [review]
> Reviewed 2 of 10 files at r3, 2 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6697)* status: 6 of 10 files reviewed, 3 unresolved discussions (waiting on @corinaminer and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 375 at r3](https://reviewable.io/reviews/batfish/batfish/6697#-MV3cSIYEUFfUzpUZq--:-MV3cSIYEUFfUzpUZq-0:bz35fdb) ([raw file](https://github.com/batfish/batfish/blob/7917ca8a48b6ad94b055c7de3c824d9720fd1b76/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L375)):*
> ```Java
>   public void enterCfp_edit(Cfp_editContext ctx) {
>     Optional<String> name = toString(ctx, ctx.policy_number());
>     // TODO If name.isPresent(), add structure definition
> ```

Any reason to avoid the clone/apply-on-exit pattern here?
Can add the actual validation later if necessary.
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 746 at r4](https://reviewable.io/reviews/batfish/batfish/6697#-MV3wg4478Ck78D-KPDY:-MV3wg4478Ck78D-KPDZ:bl37gnd) ([raw file](https://github.com/batfish/batfish/blob/0ca9aea1acb8768057170de37e9a2de3ebe14845/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L746)):*
> ```Java
>   }
> 
>   private Policy.Status toStatus(Policy_statusContext ctx) {
> ```

nit: `@Nonnull` return type here and other places.
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 824 at r4](https://reviewable.io/reviews/batfish/batfish/6697#-MV3wshL1wCh0E3n7a1S:-MV3wshL1wCh0E3n7a1T:bymypwv) ([raw file](https://github.com/batfish/batfish/blob/0ca9aea1acb8768057170de37e9a2de3ebe14845/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L824)):*
> ```Java
>   }
> 
>   private @Nonnull Optional<String> toString(
> ```

Why is this using `str` at all? Why not use `uintWhatever`, `toIntegerInSpace`; and ditch all the custom stuff?

**Review by arifogel — COMMENTED** [review]
> Reviewed 2 of 10 files at r3, 1 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6697)* status: 9 of 10 files reviewed, 4 unresolved discussions (waiting on @corinaminer and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 824 at r4](https://reviewable.io/reviews/batfish/batfish/6697#-MV3wshL1wCh0E3n7a1S:-MV3xpqMC7vPvVosmINr:b-i7oxr5) ([raw file](https://github.com/batfish/batfish/blob/0ca9aea1acb8768057170de37e9a2de3ebe14845/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L824)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Why is this using `str` at all? Why not use `uintWhatever`, `toIntegerInSpace`; and ditch all the custom stuff?
</blockquote></details>

Actually probably safer to leave as str internally to make it easier to ignore block if invalid.
But I would still recommend delegating to `toIntegerInSpace` if possible via another helper.
___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/Policy.java, line 119 at r4](https://reviewable.io/reviews/batfish/batfish/6697#-MV3xZav3dPYCmGj00K5:-MV3xZav3dPYCmGj00K6:bhm93my) ([raw file](https://github.com/batfish/batfish/blob/0ca9aea1acb8768057170de37e9a2de3ebe14845/projects/batfish/src/main/java/org/batfish/representation/fortios/Policy.java#L119)):*
> ```Java
>   @Nonnull private String _number;
>   @Nullable private String _name;
>   @Nonnull private Set<Interface> _srcIntf;
> ```

Can all the `Set`s be `final`?

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6697)* status: all files reviewed, 4 unresolved discussions (waiting on @corinaminer and @sfraint)

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6697)* status: all files reviewed, 4 unresolved discussions (waiting on @corinaminer and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 824 at r4](https://reviewable.io/reviews/batfish/batfish/6697#-MV3wshL1wCh0E3n7a1S:-MV3yZKD-X0yv_TLjM2R:b-l0r65e) ([raw file](https://github.com/batfish/batfish/blob/0ca9aea1acb8768057170de37e9a2de3ebe14845/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L824)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Actually probably safer to leave as str internally to make it easier to ignore block if invalid.
But I would still recommend delegating to `toIntegerInSpace` if possible via another helper.
</blockquote></details>

Actually let's discuss offline. Perhaps you shouldn't ignore the following block, and treat it as if it is at edit level.

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6697)* status: 8 of 10 files reviewed, 3 unresolved discussions (waiting on @arifogel, @corinaminer, and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 375 at r3](https://reviewable.io/reviews/batfish/batfish/6697#-MV3cSIYEUFfUzpUZq--:-MV4LGw1251gT0CgIhKg:bvnrpcm) ([raw file](https://github.com/batfish/batfish/blob/7917ca8a48b6ad94b055c7de3c824d9720fd1b76/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L375)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Any reason to avoid the clone/apply-on-exit pattern here?
Can add the actual validation later if necessary.
</blockquote></details>

updated
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 746 at r4](https://reviewable.io/reviews/batfish/batfish/6697#-MV3wg4478Ck78D-KPDY:-MV4LllD2RfPXAIy3Vqi:bvnrpcm) ([raw file](https://github.com/batfish/batfish/blob/0ca9aea1acb8768057170de37e9a2de3ebe14845/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L746)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

nit: `@Nonnull` return type here and other places.
</blockquote></details>

updated
___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/Policy.java, line 119 at r4](https://reviewable.io/reviews/batfish/batfish/6697#-MV3xZav3dPYCmGj00K5:-MV4K8Rp0o8sy6ZmFuoc:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/0ca9aea1acb8768057170de37e9a2de3ebe14845/projects/batfish/src/main/java/org/batfish/representation/fortios/Policy.java#L119)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Can all the `Set`s be `final`?
</blockquote></details>

done

**Review by arifogel — COMMENTED** [review]
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6697)* status: all files reviewed, 1 unresolved discussion (waiting on @corinaminer and @sfraint)

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6697)* status: 8 of 10 files reviewed, 1 unresolved discussion (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 824 at r4](https://reviewable.io/reviews/batfish/batfish/6697#-MV3wshL1wCh0E3n7a1S:-MVIgG4X9DCrjrO-6eKs:b5v55jr) ([raw file](https://github.com/batfish/batfish/blob/0ca9aea1acb8768057170de37e9a2de3ebe14845/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L824)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Actually let's discuss offline. Perhaps you shouldn't ignore the following block, and treat it as if it is at edit level.
</blockquote></details>

revamped a bit, how does that look?

**Review by arifogel — COMMENTED** [review]
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6697)* status: all files reviewed, 2 unresolved discussions (waiting on @corinaminer and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 947 at r6](https://reviewable.io/reviews/batfish/batfish/6697#-MVIiez98wkUP4UWu8Wf:-MVIiez98wkUP4UWu8Wg:buxs5zr) ([raw file](https://github.com/batfish/batfish/blob/bf241eacbcbf1649dd659d85ad5c664fcbf387f7/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L947)):*
> ```Java
>     String value = toString(ctx.str());
>     try {
>       Long.parseLong(value);
> ```

style option: `Longs.tryParse`returns `null` instead of throwing when invalid. I like it cause it's more concise, but this is perfectly fine as is.
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 951 at r6](https://reviewable.io/reviews/batfish/batfish/6697#-MVIj4NJ5QOy52pcPO9Q:-MVIj4NJ5QOy52pcPO9R:bw7huka) ([raw file](https://github.com/batfish/batfish/blob/bf241eacbcbf1649dd659d85ad5c664fcbf387f7/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L951)):*
> ```Java
>       warn(
>           messageCtx,
>           String.format("Illegal value for policy number: %s, must be a number", value));
> ```

nit: technically this could still be a number, but one that's out of `long` range.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6697)* status: all files reviewed, 2 unresolved discussions (waiting on @corinaminer and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 951 at r6](https://reviewable.io/reviews/batfish/batfish/6697#-MVIj4NJ5QOy52pcPO9Q:-MVIkR27EPh_qO7lqxlp:b5f6359) ([raw file](https://github.com/batfish/batfish/blob/bf241eacbcbf1649dd659d85ad5c664fcbf387f7/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L951)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

nit: technically this could still be a number, but one that's out of `long` range.
</blockquote></details>

Maybe we should just handle non-numbers in `toLongInSpace`

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6697)* status: 8 of 10 files reviewed, all discussions resolved (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 947 at r6](https://reviewable.io/reviews/batfish/batfish/6697#-MVIiez98wkUP4UWu8Wf:-MVIpa098GAytgMyxmzW:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/bf241eacbcbf1649dd659d85ad5c664fcbf387f7/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L947)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

style option: `Longs.tryParse`returns `null` instead of throwing when invalid. I like it cause it's more concise, but this is perfectly fine as is.
</blockquote></details>

done
___
*[projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java, line 951 at r6](https://reviewable.io/reviews/batfish/batfish/6697#-MVIj4NJ5QOy52pcPO9Q:-MVIp_CoCBrgfPHoBa1A:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/bf241eacbcbf1649dd659d85ad5c664fcbf387f7/projects/batfish/src/main/java/org/batfish/grammar/fortios/FortiosConfigurationBuilder.java#L951)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Maybe we should just handle non-numbers in `toLongInSpace`
</blockquote></details>

done

**Review by arifogel — COMMENTED** [review]
> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6697)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

**Pull request merged**
