### PR TITLE
Juniper ospf cost

### PR DESCRIPTION
**Pull request by dhalperi**
Review after #897.

For #873.

---
This change is [Reviewable](https://reviewable.io/reviews/batfish/batfish/899)

### CODE REVIEW

**Comment by arifogel** [comment]
:lgtm: modulo question about `enterOa_area_range`

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 1774 at r1](https://reviewable.io:443/reviews/batfish/batfish/899#-L4i52ylaklZKGTS_EQG:-L4i52ymcfdI7XZBopQa:bgmiood) ([raw file](https://github.com/batfish/batfish/blob/b1f827d581ac845371defaa466120b9d823ab042/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L1774)):*
> ```Java
>     if (ctx.IP_PREFIX() != null) {
>       /* TODO: handle ipv6 */
>       Prefix range = Prefix.parse(ctx.IP_PREFIX().getText());
> ```

It doesn't look like the data model is modified at this step, yet I feel like it should be. Doesn't something happen if you get this far?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/899#-:-L4i5hLnW8_MaQMFdGTH:b-6mp0fi)*

**Comment by dhalperi** [comment]
Review status: 4 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 1774 at r1](https://reviewable.io:443/reviews/batfish/batfish/899#-L4i52ylaklZKGTS_EQG:-L4lZ1cf_7djlpwOcKmO:b-q4rn6j) ([raw file](https://github.com/batfish/batfish/blob/b1f827d581ac845371defaa466120b9d823ab042/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L1774)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

It doesn't look like the data model is modified at this step, yet I feel like it should be. Doesn't something happen if you get this far?
</blockquote></details>

Swapped to only create the configuration on exit, taking into account all parameters. Was also much cleaner to unify multiple optional configurations.

PTAL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/899)*

**Comment by arifogel** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/899#-:-L4n9c3L5NKCIfKC0FXr:bnfp4nl)*

**Comment by dhalperi** [comment]
(Please squash my PRs unless otherwise specified -- or let me merge? This one dropped a bunch of crap commits into `master`.)

**Pull request merged**
