### PR TITLE
Frr: Liberation step 6: Move most conversion code to fully inside FRR

### PR DESCRIPTION
**Pull request by ratulm**
After #7693

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 2 of 12 files at r1, 1 of 3 files at r2, 9 of 10 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7700)* status: all files reviewed, 3 unresolved discussions (waiting on @ratulm)

___
*[projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConcatenatedConfiguration.java, line 166 at r3](https://reviewable.io/reviews/batfish/batfish/7700#-MogSkgLCwwgPXXtfq_J:-MogSkgLCwwgPXXtfq_K:b-c9uvwg) ([raw file](https://github.com/batfish/batfish/blob/1a2bfb958ac07cb4dc8546ea440ab136ae29bd28/projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConcatenatedConfiguration.java#L166)):*
> ```Java
>     addBgpUnnumberedLLAs(c, _frrConfiguration);
> 
>     // convertFrr(this, c, this, _frrConfiguration);
> ```

What's this for? Forgot to remove?
___
*[projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConcatenatedConfiguration.java, line 187 at r4](https://reviewable.io/reviews/batfish/batfish/7700#-Mogh6lK0k-VWIk2--VO:-Mogh6lK0k-VWIk2--VP:b-my7key) ([raw file](https://github.com/batfish/batfish/blob/f7caef73a30157666bb527f5e1a562c3d47d641b/projects/batfish/src/main/java/org/batfish/representation/cumulus/CumulusConcatenatedConfiguration.java#L187)):*
> ```Java
> 
>     convertStaticRoutes(c);
>     FrrConversions.convertStaticRoutes(c, _frrConfiguration);
> ```

Please comment what each of these does and/or rename this file's `convertStaticRoutes` function to something more informative.
___
*[projects/batfish/src/test/java/org/batfish/representation/cumulus/MockOutOfBandConfiguration.java, line 109 at r4](https://reviewable.io/reviews/batfish/batfish/7700#-MogiM8TAxcNA7RZo3xy:-MogiM8TAxcNA7RZo3xz:bpq643h) ([raw file](https://github.com/batfish/batfish/blob/f7caef73a30157666bb527f5e1a562c3d47d641b/projects/batfish/src/test/java/org/batfish/representation/cumulus/MockOutOfBandConfiguration.java#L109)):*
> ```Java
>     public MockOutOfBandConfiguration build() {
>       MockOutOfBandConfiguration mockOutOfBandConfiguration = new MockOutOfBandConfiguration();
>       mockOutOfBandConfiguration._vxlans = firstNonNull(this._vxlans, ImmutableMap.of());
> ```

Normally we would do all this via a constructor and make the class immutable.
But since this is a test class, whatever.

**Review by arifogel — COMMENTED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7700)* status: all files reviewed, 1 unresolved discussion (waiting on @ratulm)

**Review by arifogel — COMMENTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7700)* status: all files reviewed, 1 unresolved discussion (waiting on @ratulm)

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7700)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ratulm)

___
*[projects/batfish/src/test/java/org/batfish/representation/cumulus/MockOutOfBandConfiguration.java, line 109 at r4](https://reviewable.io/reviews/batfish/batfish/7700#-MogiM8TAxcNA7RZo3xy:-MogjlimARIdMMhfJYzT:b7c6puc) ([raw file](https://github.com/batfish/batfish/blob/f7caef73a30157666bb527f5e1a562c3d47d641b/projects/batfish/src/test/java/org/batfish/representation/cumulus/MockOutOfBandConfiguration.java#L109)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Normally we would do all this via a constructor and make the class immutable.
But since this is a test class, whatever.
</blockquote></details>

Yeah, took the lazy way out. This builder was auto-generated by IntelliJ. Made constructor private to make the class immutable.

**Pull request merged**
