### PR TITLE
This is a fix for the EIGRP redistribution problem

### PR DESCRIPTION
**Pull request by Katsuya414**
https://github.com/batfish/batfish/issues/8273

Here is a solution to the above problem

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8364)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dhalperi and @Katsuya414)

___
*[`projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java` line 1111 at r1](https://reviewable.io/reviews/batfish/batfish/8364#-N4TBt_w7rNIFl6t-Hes:-N4TBt_w7rNIFl6t-Het:b-gbvd8i) ([raw file](https://github.com/batfish/batfish/blob/c4b40823ab951e49df184f660d9fd349949fd03a/projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java#L1111)):*
> ```Java
>                           .collect(ImmutableList.toImmutableList());
>                   Conjunction redistExpr = new Conjunction(matchConjuncts);
>                   return new If(redistExpr, ImmutableList.of(Statements.ExitAccept.toStaticStatement()));
> ```

Where is the process ID matched?

That is, your bug has `redistribute eigrp 1 route-map foo` -- where is the `1` here?

**Comment by Katsuya414** [comment]
@dhalperi 
What value do you mean by process ID?

**Comment by Katsuya414** [comment]
@dhalperi 
You said.
I solved the problem about the process ID.
May I ask you to check?

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8364)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @dhalperi and @Katsuya414)

___
*[`projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java` line 1105 at r3](https://reviewable.io/reviews/batfish/batfish/8364#-N5CPtkM7I6p6kKNEg9e:-N5CPtkM7I6p6kKNEg9f:bbzh2wk) ([raw file](https://github.com/batfish/batfish/blob/4a1481c74fe3400864150edb2a969788c3a29d5c/projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java#L1105)):*
> ```Java
>                 case EIGRP:
>                   assert policy.getInstance().getTag() != null;
>                   long eigrpAsn = Long.parseLong(policy.getInstance().getTag());
> ```

I do not believe this is the right way to get the ASN from the process. The instance tag on NX-OS can be an arbitrary trying, in which case the user must set it manually. Even if the tag is a long, the user can override that long. See docs: https://www.cisco.com/c/en/us/td/docs/switches/datacenter/nexus9000/sw/6-x/unicast/configuration/guide/l3_cli_nxos/l3_eigrp.html
___
*[`projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java` line 1106 at r3](https://reviewable.io/reviews/batfish/batfish/8364#-N5CQ2EJ6903ZoMM-q9k:-N5CQ2EJ6903ZoMM-q9l:b-h7dgfw) ([raw file](https://github.com/batfish/batfish/blob/4a1481c74fe3400864150edb2a969788c3a29d5c/projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/CiscoNxosConfiguration.java#L1106)):*
> ```Java
>                   assert policy.getInstance().getTag() != null;
>                   long eigrpAsn = Long.parseLong(policy.getInstance().getTag());
>                   MatchProtocol matchEigrp =
> ```

Unfortunately you did not provide us with a network to test, so we are blocked until we are able to find time to build our own network and test.
An example of a PR that did this: https://github.com/batfish/batfish/pull/7943/files
Notice how Ari created the arista_ospf_network file and added a unit test of the new functionality in AristaGrammarTest.java

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, 1 of 2 files at r4, 1 of 1 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8364)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Katsuya414)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8364)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Katsuya414)

**Pull request merged**
