### PR TITLE
Question template for user provided L1

### PR DESCRIPTION
**Pull request by ratulm**
Used a simpler name: inputLayer1Edges

### CODE REVIEW

**Comment by dhalperi** [comment]
Why add a template? We already have one for edges.

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8142)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @anothermattbrown and @dhalperi)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/8142#-MyAoUfu1dR8XpFFUUXy:-MyAoUfu1dR8XpFFUUXz:b-emio69) (no related file):*
> Why add a template? We already have one for edges.

The edges template is not exposed to users. It's specialized versions (layer3edges, bgpEdges, ospfEdges) are exposed.  

---

**Comment by dhalperi** [comment]
Yes it is:

```
% ls questions/stable/edges.json 
questions/stable/edges.json
```

We also refer to it in our docs.

**Comment by ratulm** [comment]
> Yes it is:
> 
> ```
> % ls questions/stable/edges.json 
> questions/stable/edges.json
> ```
> 
> We also refer to it in our docs.

By "not exposed to users", I meant not exposed here: https://pybatfish.readthedocs.io/en/latest/questions.html

**Review by dhalperi — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8142)* status: all files reviewed, 1 unresolved discussion (waiting on @anothermattbrown)

**Review by dhalperi — COMMENTED** [review]
> Dismissed @ratulm from a discussion.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8142)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8142)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown)

**Pull request merged**
