### PR TITLE
VendorConfigurationFormatDetector: do a better job recognizing IOS-XR

### PR DESCRIPTION
**Pull request by dhalperi**

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6939)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @arifogel)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6939#-MYhULJNAPlVtqnPbxTu:-MYhULJNAPlVtqnPbxTv:b87mbye) (no related file):*
@arifogel thoughts on the riskiness here? These aren't that specific, but they're pretty specific given that it's Cisco already.

---

**Review by arifogel — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6939)* status: all files reviewed, 2 unresolved discussions (waiting on @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/grammar/VendorConfigurationFormatDetector.java, line 145 at r1](https://reviewable.io/reviews/batfish/batfish/6939#-MYkUV4VBRoJf5Ul82ve:-MYkUV4W2KPBSN-Y4st3:b-crneub) ([raw file](https://github.com/batfish/batfish/blob/99584520188b5f11d463e6a729b3b540ba8bd30d/projects/batfish/src/main/java/org/batfish/grammar/VendorConfigurationFormatDetector.java#L145)):*
> ```Java
> 
>   /** Assuming Cisco device, try to find things that indicate IOS-XR. */
>   private static final Pattern XR_QUALIFIERS = Pattern.compile("(Bundle-Ether|end-policy|end-set)");
> ```

This is generally dangerous IMO. It is a common pattern to add the connecting interface to the description of an interface.
E.g. An IOS or Juniper or whatever neighbor of an IOS-XR device that connects to the latter's Bundle-EtherXXX interface may have an interface description of `connects to <XR device> Bundle-Ether100`

`end-policy` and `end-set` are OK.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6939)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @arifogel and @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/grammar/VendorConfigurationFormatDetector.java, line 145 at r1](https://reviewable.io/reviews/batfish/batfish/6939#-MYkUV4VBRoJf5Ul82ve:-MZZ7lCm-L44yCVzbtMP:boyt178) ([raw file](https://github.com/batfish/batfish/blob/d58c8469f1ed9776d177c44057b996e24ad1d17d/projects/batfish/src/main/java/org/batfish/grammar/VendorConfigurationFormatDetector.java#L145)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

This is generally dangerous IMO. It is a common pattern to add the connecting interface to the description of an interface.
E.g. An IOS or Juniper or whatever neighbor of an IOS-XR device that connects to the latter's Bundle-EtherXXX interface may have an interface description of `connects to <XR device> Bundle-Ether100`

`end-policy` and `end-set` are OK.
</blockquote></details>

I pushed some commits addressing this.
And I added `ipv4 access-list` as another qualifier, as I haven't seen that outside of XR.

**Review by arifogel — COMMENTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6939)* status: 2 of 6 files reviewed, 1 unresolved discussion (waiting on @dhalperi)

**Review by arifogel — COMMENTED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6939)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi)

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6939)* status: 4 of 12 files reviewed, all discussions resolved (waiting on @arifogel)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_pim.g4, line 106 at r5](https://reviewable.io/reviews/batfish/batfish/6939#-MZ_0AfE7eHfm73N7P-U:-MZ_0AfE7eHfm73N7P-V:b20qax2) ([raw file](https://github.com/batfish/batfish/blob/34bfa30f6323ec1d854217d7f8679e945c74b9c9/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco_xr/CiscoXr_pim.g4#L106)):*
> ```ANTLR
>   (
>     EXPLICIT_RPF_VECTOR
>     | RPF_VECTOR
> ```

FYI Confirmed this is legal: https://www.cisco.com/c/en/us/td/docs/iosxr/ncs5000/multicast/65x/b-multicast-cg-ncs5000-65x/b-multicast-cg-ncs5000-64x_chapter_010.html
___
*[tests/parsing-tests/networks/unit-tests/configs/cisco_dhcp, line 21 at r5](https://reviewable.io/reviews/batfish/batfish/6939#-MZ_0N8D7JrYHJVcvOu0:-MZ_0N8D7JrYHJVcvOu1:bjierks) ([raw file](https://github.com/batfish/batfish/blob/dffba7572d0e152cdbbc997fbae253b333c17f68/tests/parsing-tests/networks/unit-tests/configs/cisco_dhcp#L21)):*
<details><summary><i alt="summary">Quoted 14 lines of code…</i></summary>

> ```
> dhcp ipv4
>  profile irnc-dhcp relay
>   helper-address vrf default 137.164.55.68
>   lease 0 0 5
>   pool mgmt-net
>   dns-server 130.59.31.251 130.59.31.248
>   domain-name switch.ch
>   subnet-mask 255.255.255.240
>   default-router 13.9.2.1
>  !
>  interface Bundle-Ether4.12 relay profile irnc-dhcp
>  interface Bundle-Ether4.13 relay profile irnc-dhcp
>  interface Bundle-Ether1.1031 relay profile irnc-dhcp
>  interface Bundle-Ether1.1032 relay profile irnc-dhcp
> ```
</details>


FYI split out this XR syntax.
___
*[tests/parsing-tests/networks/unit-tests/configs/pim, line 31 at r5](https://reviewable.io/reviews/batfish/batfish/6939#-MZ_0Q97-OO2siEd4ahQ:-MZ_0Q97-OO2siEd4ahR:b-cz6wtv) ([raw file](https://github.com/batfish/batfish/blob/dffba7572d0e152cdbbc997fbae253b333c17f68/tests/parsing-tests/networks/unit-tests/configs/pim#L31)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
> interface loopback 1
>  port-name riv-hpr3 Primary Loopback
>  ip address 137.164.17.8/32
>  ip pim-sparse
>  ipv6 address 2607:f380::108:9a41:1081/124
>  ipv6 enable
>  ipv6 pim-sparse
> !
> ```
</details>


FYI do not think this is legal.
___
*[tests/parsing-tests/networks/unit-tests/configs/xr_multicast, line 4 at r5](https://reviewable.io/reviews/batfish/batfish/6939#-MZ_0UI34AL17QBnjLux:-MZ_0UI34AL17QBnjLuy:bphv32p) ([raw file](https://github.com/batfish/batfish/blob/34bfa30f6323ec1d854217d7f8679e945c74b9c9/tests/parsing-tests/networks/unit-tests/configs/xr_multicast#L4)):*
> ```
> hostname xr_multicast
> !
> multicast-routing
> ```

FYI this was already a lot of XR syntax, mostly, but I don't think it's all legal.

**Review by arifogel — COMMENTED** [review]
> Reviewed 8 of 8 files at r5.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6939)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[tests/parsing-tests/networks/unit-tests/configs/pim, line 31 at r5](https://reviewable.io/reviews/batfish/batfish/6939#-MZ_0Q97-OO2siEd4ahQ:-MZnFXqeEFB5xeeHxvQ2:b-4270i0) ([raw file](https://github.com/batfish/batfish/blob/dffba7572d0e152cdbbc997fbae253b333c17f68/tests/parsing-tests/networks/unit-tests/configs/pim#L31)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> interface loopback 1
>  port-name riv-hpr3 Primary Loopback
>  ip address 137.164.17.8/32
>  ip pim-sparse
>  ipv6 address 2607:f380::108:9a41:1081/124
>  ipv6 enable
>  ipv6 pim-sparse
> !
> ```

FYI do not think this is legal.
</blockquote></details>

Some of it definitely isn't legal if this file is meant to be XR. Any value to splitting it out?
___
*[tests/parsing-tests/networks/unit-tests/configs/cisco_multicast, line 16 at r5](https://reviewable.io/reviews/batfish/batfish/6939#-MZnMHRc6RBqa7PPUzUl:-MZnMHRc6RBqa7PPUzUm:bjalwil) ([raw file](https://github.com/batfish/batfish/blob/dffba7572d0e152cdbbc997fbae253b333c17f68/tests/parsing-tests/networks/unit-tests/configs/cisco_multicast#L16)):*
> ```
>   nsf
>   multipath
>   interface all enable
> ```

`interface all enable` is definitely valid syntax on xr within multicast routing address-family ipv4/6.

The other deleted items can stay deleted.

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6939)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[tests/parsing-tests/networks/unit-tests/configs/pim, line 31 at r5](https://reviewable.io/reviews/batfish/batfish/6939#-MZ_0Q97-OO2siEd4ahQ:-MZna41dEco522fu6qsK:b-ivcapz) ([raw file](https://github.com/batfish/batfish/blob/dffba7572d0e152cdbbc997fbae253b333c17f68/tests/parsing-tests/networks/unit-tests/configs/pim#L31)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Some of it definitely isn't legal if this file is meant to be XR. Any value to splitting it out?
</blockquote></details>

I'd say no.
___
*[tests/parsing-tests/networks/unit-tests/configs/cisco_multicast, line 16 at r5](https://reviewable.io/reviews/batfish/batfish/6939#-MZnMHRc6RBqa7PPUzUl:-MZnaHV-5pLlXPRboI7c:b-2h14x8) ([raw file](https://github.com/batfish/batfish/blob/dffba7572d0e152cdbbc997fbae253b333c17f68/tests/parsing-tests/networks/unit-tests/configs/cisco_multicast#L16)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

`interface all enable` is definitely valid syntax on xr within multicast routing address-family ipv4/6.

The other deleted items can stay deleted.
</blockquote></details>

Yes, that was just redundant with config 3 lines up.

**Pull request merged**
