### PR TITLE
TransferBDD: SetOrigin

### PR DESCRIPTION
**Pull request by millstein**
Adds support for the SetOrigin statement in the symbolic route analysis, as well as constraints on the origin type in the SearchRoutePolicies question.

### CODE REVIEW

**Review by nickgian — COMMENTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8665)* status: all files reviewed, 2 unresolved discussions (waiting on @anothermattbrown and @millstein)

___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/BDDRoute.java` line 160 at r1](https://reviewable.io/reviews/batfish/batfish/8665#-NP9hgpRDPE5G8psQ9LA:-NP9hgpRDPE5G8psQ9LB:b-ll0k6w) ([raw file](https://github.com/batfish/batfish/blob/281e66d1d573d8ad34f06aa74fdcaf8e0ae4c56f/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/BDDRoute.java#L160)):*
> ```Java
>     int numVars = factory.varNum();
>     int numNeeded =
>         32 * 5
> ```

why did that become 5?
___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/BDDRoute.java` line 168 at r1](https://reviewable.io/reviews/batfish/batfish/8665#-NP9hjok1d1jbhwbUuVu:-NP9hjol81GIdb32sqJQ:bqfg0ui) ([raw file](https://github.com/batfish/batfish/blob/281e66d1d573d8ad34f06aa74fdcaf8e0ae4c56f/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/BDDRoute.java#L168)):*
> ```Java
>             + IntMath.log2(OriginType.values().length, RoundingMode.CEILING)
>             + IntMath.log2(RoutingProtocol.values().length, RoundingMode.CEILING)
>             + IntMath.log2(allMetricTypes.size(), RoundingMode.CEILING);
> ```

is the MetricType necessary to model OriginType?

**Review by millstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8665)* status: all files reviewed, 2 unresolved discussions (waiting on @anothermattbrown and @nickgian)

___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/BDDRoute.java` line 160 at r1](https://reviewable.io/reviews/batfish/batfish/8665#-NP9hgpRDPE5G8psQ9LA:-NPA6MsRBPjfkLFgpha_:bjysd9n) ([raw file](https://github.com/batfish/batfish/blob/281e66d1d573d8ad34f06aa74fdcaf8e0ae4c56f/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/BDDRoute.java#L160)):*
<details><summary><i>Previously, nickgian (Nick Giannarakis) wrote…</i></summary><blockquote>

why did that become 5?
</blockquote></details>

The previous count was wrong so I cleaned it up here.
___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/BDDRoute.java` line 168 at r1](https://reviewable.io/reviews/batfish/batfish/8665#-NP9hjok1d1jbhwbUuVu:-NPA6UVa9t_5JlbobLEf:b6hzaze) ([raw file](https://github.com/batfish/batfish/blob/281e66d1d573d8ad34f06aa74fdcaf8e0ae4c56f/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/BDDRoute.java#L168)):*
<details><summary><i>Previously, nickgian (Nick Giannarakis) wrote…</i></summary><blockquote>

is the MetricType necessary to model OriginType?
</blockquote></details>

The metric type was already implemented, but there was a hard-coded +2 here.  I changed it to be consistent with how the other enums are handled, so it also is more robust to later changes to the enum.

**Review by nickgian — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8665)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown)

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 7 of 8 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8665)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @millstein)

**Pull request merged**
