### PR TITLE
Allow traceroutes to check bgp session reachability.

### PR DESCRIPTION
**Pull request by progwriter**
*Purpose*:
Ensure that bgp neighbors are initialized only if the session can be established (i.e., neighbor IP is routable)

*Implementation*:
Perform a traceroute and re-init remote bgp neighbors after IGP dataplane computation is complete

### CODE REVIEW

**Comment by progwriter** [comment]
*[projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java, line 722 at r2](https://reviewable.io:443/reviews/batfish/batfish/1038#-L75iL0YD8A5MqduLWr1:-L75iL0YD8A5MqduLWr2:b-qlhy85) ([raw file](https://github.com/batfish/batfish/blob/db1f873f84d12274de4b11b090dd72e58347aa8a/projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java#L722)):*
> ```Java
>               throw new BatfishException("Cannot compute routability without a dataplane");
>             }
>             Flow.Builder fb = new Flow.Builder();
> ```

Double check fields

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/1038)*

**Comment by arifogel** [comment]
Review status: all files reviewed at latest revision, 16 unresolved discussions, some commit checks failed.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java, line 722 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1038#-L75iL0YD8A5MqduLWr1:-L7QYjLND-F4922g-78S:b-oup83a) ([raw file](https://github.com/batfish/batfish/blob/db1f873f84d12274de4b11b090dd72e58347aa8a/projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java#L722)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

Double check fields
</blockquote></details>

Source port? It will be either be standard BGP port, or something in ephemeral range. I strongly recommend emulation to find out.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1038)*

**Comment by progwriter** [comment]
Review status: 3 of 9 files reviewed at latest revision, 16 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java, line 722 at r2](https://reviewable.io:443/reviews/batfish/batfish/1038#-L75iL0YD8A5MqduLWr1:-L7QfB4hUdQWIcV2Z8at:bhny7zh) ([raw file](https://github.com/batfish/batfish/blob/db1f873f84d12274de4b11b090dd72e58347aa8a/projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java#L722)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Source port? It will be either be standard BGP port, or something in ephemeral range. I strongly recommend emulation to find out.
</blockquote></details>

According to this https://learningnetwork.cisco.com/blogs/vip-perspectives/2017/12/14/demystifying-bgp-session-establishment, ephemeral range, so I didn't put any constraints on this.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java, line 618 at r3](https://reviewable.io:443/reviews/batfish/batfish/1038#-L7QWO0C-47uMvWX1Ndv:-L7Qf80DfuRcnaW6NDiO:bz441ou) ([raw file](https://github.com/batfish/batfish/blob/0a085dd0885a959f6fed9457061f6eee1e423334/projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java#L618)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Reachability or routability? These are two different things, and only the former fixes the bug we encountered.
</blockquote></details>

Reachability

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java, line 714 at r3](https://reviewable.io:443/reviews/batfish/batfish/1038#-L7QWsH67cmlL25lmxAs:-L7Qf9dggrF4P_labIio:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/0a085dd0885a959f6fed9457061f6eee1e423334/projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java#L714)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Routability or reachability?
</blockquote></details>

Done.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java, line 717 at r3](https://reviewable.io:443/reviews/batfish/batfish/1038#-L7QWvzTEwt5uBE4pbV0:-L7QfXbVWCgY9KSuIipM:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/0a085dd0885a959f6fed9457061f6eee1e423334/projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java#L717)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Routability or reachability?
</blockquote></details>

Done.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java, line 723 at r3](https://reviewable.io:443/reviews/batfish/batfish/1038#-L7QX0EKCccxuHNNltmh:-L7QfAPXvcc9Yyetx8GD:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/0a085dd0885a959f6fed9457061f6eee1e423334/projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java#L723)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Routability or reachability?
</blockquote></details>

Done.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java, line 746 at r3](https://reviewable.io:443/reviews/batfish/batfish/1038#-L7QXGaC3QmQziofgHmI:-L7QfKhVbUyDBaeTma5Z:b-otewe9) ([raw file](https://github.com/batfish/batfish/blob/0a085dd0885a959f6fed9457061f6eee1e423334/projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java#L746)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

This looks wrong. Each of `forwardFlow` and `backwardFlow` could have multiple traces. Do you want to consider the neighbor relationship invalid if e.g. `forwardFlow` has one accepting trace and one dropping trace?
</blockquote></details>

Fixed up, PTAL.

---

*[projects/batfish/src/test/java/org/batfish/bdp/BdpDataPlanePluginTest.java, line 1023 at r3](https://reviewable.io:443/reviews/batfish/batfish/1038#-L7QXoS-7mQ774nOxe0N:-L7QfNDl4FaacA7Lixh9:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/0a085dd0885a959f6fed9457061f6eee1e423334/projects/batfish/src/test/java/org/batfish/bdp/BdpDataPlanePluginTest.java#L1023)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Routability or reachability?
</blockquote></details>

Done.

---

*[projects/batfish/src/test/java/org/batfish/bdp/RouteReflectionTest.java, line 135 at r3](https://reviewable.io:443/reviews/batfish/batfish/1038#-L7QXw1X7hGLMUWWNykB:-L7QfYgipVNd3Lx4iIkR:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/0a085dd0885a959f6fed9457061f6eee1e423334/projects/batfish/src/test/java/org/batfish/bdp/RouteReflectionTest.java#L135)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Use `Prefix.MAX_PREFIX_LENGTH` instead of `32`.
</blockquote></details>

Done.

---

*[projects/batfish/src/test/java/org/batfish/bdp/RouteReflectionTest.java, line 162 at r3](https://reviewable.io:443/reviews/batfish/batfish/1038#-L7QXzce1lm8ucF3Vbcj:-L7QfNkcBfOjfWu-5zLR:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/0a085dd0885a959f6fed9457061f6eee1e423334/projects/batfish/src/test/java/org/batfish/bdp/RouteReflectionTest.java#L162)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Use `Prefix.MAX_PREFIX_LENGTH` instead of `32`.
</blockquote></details>

Done.

---

*[projects/batfish/src/test/java/org/batfish/bdp/RouteReflectionTest.java, line 163 at r3](https://reviewable.io:443/reviews/batfish/batfish/1038#-L7QY-5h2xMUrGDQBTQi:-L7QfO0CZNljnJLFW0Al:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/0a085dd0885a959f6fed9457061f6eee1e423334/projects/batfish/src/test/java/org/batfish/bdp/RouteReflectionTest.java#L163)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Use `Prefix.MAX_PREFIX_LENGTH` instead of `32`.
</blockquote></details>

Done.

---

*[projects/batfish/src/test/java/org/batfish/bdp/RouteReflectionTest.java, line 192 at r3](https://reviewable.io:443/reviews/batfish/batfish/1038#-L7QY1712jZ_YpCb0lJS:-L7QfOIdDmyxcM-kCsiC:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/0a085dd0885a959f6fed9457061f6eee1e423334/projects/batfish/src/test/java/org/batfish/bdp/RouteReflectionTest.java#L192)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Use `Prefix.MAX_PREFIX_LENGTH` instead of `32`.
</blockquote></details>

Done.

---

*[projects/batfish/src/test/java/org/batfish/bdp/RouteReflectionTest.java, line 273 at r3](https://reviewable.io:443/reviews/batfish/batfish/1038#-L7QY1hc8rwD5B-c1wkt:-L7QfPE8Hic0wCfnudta:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/0a085dd0885a959f6fed9457061f6eee1e423334/projects/batfish/src/test/java/org/batfish/bdp/RouteReflectionTest.java#L273)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Use `Prefix.MAX_PREFIX_LENGTH` instead of `32`.
</blockquote></details>

Done.

---

*[projects/batfish/src/test/java/org/batfish/bdp/RouteReflectionTest.java, line 300 at r3](https://reviewable.io:443/reviews/batfish/batfish/1038#-L7QY9Ep9W8noDk5WsGP:-L7QfPaTHHj4aUmpJ6R6:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/0a085dd0885a959f6fed9457061f6eee1e423334/projects/batfish/src/test/java/org/batfish/bdp/RouteReflectionTest.java#L300)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Use `Prefix.MAX_PREFIX_LENGTH` instead of `32`.
</blockquote></details>

Done.

---

*[projects/batfish/src/test/java/org/batfish/bdp/RouteReflectionTest.java, line 301 at r3](https://reviewable.io:443/reviews/batfish/batfish/1038#-L7QY9mSBNb73PGO3M7k:-L7QfPyb-nbcJBzJ7QUR:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/0a085dd0885a959f6fed9457061f6eee1e423334/projects/batfish/src/test/java/org/batfish/bdp/RouteReflectionTest.java#L301)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Use `Prefix.MAX_PREFIX_LENGTH` instead of `32`.
</blockquote></details>

Done.

---

*[projects/batfish/src/test/java/org/batfish/bdp/RouteReflectionTest.java, line 325 at r3](https://reviewable.io:443/reviews/batfish/batfish/1038#-L7QYAeoB6WrgRNV10b7:-L7QfQIbo-aD5qGh7fDu:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/0a085dd0885a959f6fed9457061f6eee1e423334/projects/batfish/src/test/java/org/batfish/bdp/RouteReflectionTest.java#L325)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Use `Prefix.MAX_PREFIX_LENGTH` instead of `32`.
</blockquote></details>

Done.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/BfConsts.java, line 11 at r3](https://reviewable.io:443/reviews/batfish/batfish/1038#-L7QVynsABpNOtI0p0Xl:-L7QfSAC3h8gx2m7C6Sq:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/0a085dd0885a959f6fed9457061f6eee1e423334/projects/batfish-common-protocol/src/main/java/org/batfish/common/BfConsts.java#L11)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Either remove this constant and refer to `NamedPort.BGP.number()` directly where needed, or set this constant to `NamedPort.BGP.number()`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/1038)*

**Comment by arifogel** [comment]
Reviewed 7 of 7 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java, line 722 at r2](https://beta.reviewable.io/reviews/batfish/batfish/1038#-L75iL0YD8A5MqduLWr1:-L7Qfrx53mo4UUOFgzD2:bmpkr5b) ([raw file](https://github.com/batfish/batfish/blob/db1f873f84d12274de4b11b090dd72e58347aa8a/projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java#L722)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

According to this https://learningnetwork.cisco.com/blogs/vip-perspectives/2017/12/14/demystifying-bgp-session-establishment, ephemeral range, so I didn't put any constraints on this.
</blockquote></details>

You should still pick a port in an ephemeral range. `0` is not in the ephemeral range, so we can definitely do better. Use the most restrictive definition of ephemeral for all OSes you can find.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java, line 738 at r3](https://beta.reviewable.io/reviews/batfish/batfish/1038#-L7QgSGh2SbfVx4AcMcm:-L7QgSGh2SbfVx4AcMcn:b-2oklec) ([raw file](https://github.com/batfish/batfish/blob/0a085dd0885a959f6fed9457061f6eee1e423334/projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java#L738)):*
> ```Java
>             fb.setDstIp(localAddress);
>             fb.setSrcIp(remoteAddress);
>             Flow backwardFlow = fb.build();
> ```

Don't you need to reverse the source and destination ports here? That is, it seems to be that there should be 4 flows: a forward and reverse  for each possible initiator. It's possible the choice of initiator is handled already by the outer loop.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1038)*

**Comment by progwriter** [comment]
Review status: 8 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java, line 722 at r2](https://reviewable.io:443/reviews/batfish/batfish/1038#-L75iL0YD8A5MqduLWr1:-L7Qk2OPsq0FtcbqKULs:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/db1f873f84d12274de4b11b090dd72e58347aa8a/projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java#L722)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

You should still pick a port in an ephemeral range. `0` is not in the ephemeral range, so we can definitely do better. Use the most restrictive definition of ephemeral for all OSes you can find.
</blockquote></details>

Done.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java, line 738 at r3](https://reviewable.io:443/reviews/batfish/batfish/1038#-L7QgSGh2SbfVx4AcMcm:-L7Qk41bDtruzM4wn5Lc:buxkxlz) ([raw file](https://github.com/batfish/batfish/blob/0a085dd0885a959f6fed9457061f6eee1e423334/projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java#L738)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Don't you need to reverse the source and destination ports here? That is, it seems to be that there should be 4 flows: a forward and reverse  for each possible initiator. It's possible the choice of initiator is handled already by the outer loop.
</blockquote></details>

Good point. I think it's fine to assume that the `neighbor` from the outer loop is the initiator, so we don't do double the number of traceroutes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/1038)*

**Comment by arifogel** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java, line 740 at r5](https://beta.reviewable.io/reviews/batfish/batfish/1038#-L7Qo0vE64i1syvjiYl6:-L7Qo0vE64i1syvjiYl7:bpwu6xe) ([raw file](https://github.com/batfish/batfish/blob/0c8cb79b80386e4cc4db49634919dc17b907ca73/projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java#L740)):*
> ```Java
> 
>             fb.setIngressNode(remoteBgpNeighborCandidate.getOwner().getHostname());
>             fb.setSrcIp(remoteAddress);
> ```

To best display intent, perhaps you should directly get fields from `forwardFlow` to be switched.
E.g. `fb.setSrcPort(forwardFlow.getDstPort());`, etc. This approach in general would be less error-prone.
I guess I should have suggested that earlier :P

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1038)*

**Comment by progwriter** [comment]
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java, line 740 at r5](https://reviewable.io:443/reviews/batfish/batfish/1038#-L7Qo0vE64i1syvjiYl6:-L7Qpg2qENBzKcfK3jkA:bbqg1et) ([raw file](https://github.com/batfish/batfish/blob/0c8cb79b80386e4cc4db49634919dc17b907ca73/projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java#L740)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

To best display intent, perhaps you should directly get fields from `forwardFlow` to be switched.
E.g. `fb.setSrcPort(forwardFlow.getDstPort());`, etc. This approach in general would be less error-prone.
I guess I should have suggested that earlier :P
</blockquote></details>

Here you go :) 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/1038)*

**Comment by arifogel** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java, line 740 at r6](https://beta.reviewable.io/reviews/batfish/batfish/1038#-L7RnwFO1f0oWehLX1Jm:-L7RnwFO1f0oWehLX1Jn:b1p3wr2) ([raw file](https://github.com/batfish/batfish/blob/b9dda7eb3cebf03b921d90473a0fad0c544626a4/projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java#L740)):*
> ```Java
> 
>             fb.setIngressNode(remoteBgpNeighborCandidate.getOwner().getHostname());
>             fb.setSrcIp(remoteAddress);
> ```

And this too.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java, line 741 at r6](https://beta.reviewable.io/reviews/batfish/batfish/1038#-L7Rnxy04ABS6FceISY1:-L7Rnxy04ABS6FceISY2:b1p3wr2) ([raw file](https://github.com/batfish/batfish/blob/b9dda7eb3cebf03b921d90473a0fad0c544626a4/projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java#L741)):*
> ```Java
>             fb.setIngressNode(remoteBgpNeighborCandidate.getOwner().getHostname());
>             fb.setSrcIp(remoteAddress);
>             fb.setDstIp(localAddress);
> ```

And this too.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1038)*

**Comment by progwriter** [comment]
Review status: 9 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java, line 740 at r6](https://reviewable.io:443/reviews/batfish/batfish/1038#-L7RnwFO1f0oWehLX1Jm:-L7RomJr0z5aW0YyQR5a:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/b9dda7eb3cebf03b921d90473a0fad0c544626a4/projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java#L740)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

And this too.
</blockquote></details>

Done.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java, line 741 at r6](https://reviewable.io:443/reviews/batfish/batfish/1038#-L7Rnxy04ABS6FceISY1:-L7Rom_n9B5SBKQPSmJL:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/b9dda7eb3cebf03b921d90473a0fad0c544626a4/projects/batfish-common-protocol/src/main/java/org/batfish/common/util/CommonUtil.java#L741)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

And this too.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/1038)*

**Comment by arifogel** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/1038#-:-L7RpByA3jpF5S1Hkwps:bnfp4nl)*

**Pull request merged**
