### PR TITLE
ipsec proposal and transformset reference check

### PR DESCRIPTION
**Pull request by vasu018**
For Cisco ipsec profile and transformset reference checking: As the defineStructure and referenceStructure along with the markConcreteStructure are already present in the code. It is just matter of updating the DefinedStructure -> ComparableStructure and updating the definition Line calculation.

### CODE REVIEW

**Comment by sfraint** [comment]
Review status: 6 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpsecProposal.java, line 85 at r1](https://reviewable.io/reviews/batfish/batfish/1576#-LEAfO-O70Yj2Xxc8KO5:-LEAfO-PCL3Kg3bWt9RF:bm8hlef) ([raw file](https://github.com/batfish/batfish/blob/0a2f95a2ffac541d969e19d0057280157b1b4d89/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpsecProposal.java#L85)):*
> ```Java
>   private IpsecProtocol _protocol;
> 
>   @JsonCreator
> ```

I think this annotation needs to stay, in order for deserialization to work

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpsecProposal.java, line 85 at r1](https://reviewable.io/reviews/batfish/batfish/1576#-LEAfko9BbcTumHFMm7W:-LEAfko9BbcTumHFMm7X:bgvbpxf) ([raw file](https://github.com/batfish/batfish/blob/8ef88dc113c85ff9013df73fffad51d4f9c65cea/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpsecProposal.java#L85)):*
> ```Java
>   public IpsecProposal(String name) {
>     super(name);
>     _definitionLine = -1;
> ```

Get rid of `_definitionLine` and its uses if it is no longer needed.

---

*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 2450 at r1](https://reviewable.io/reviews/batfish/batfish/1576#-LEAghz1CHnLpPcOgmEV:-LEAghz1CHnLpPcOgmEW:bfrtm0u) ([raw file](https://github.com/batfish/batfish/blob/8ef88dc113c85ff9013df73fffad51d4f9c65cea/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L2450)):*
> ```Java
>     String name = ctx.name.getText();
>     _currentIpsecProposal =
>         _configuration.getIpsecProposals().computeIfAbsent(name, n -> new IpsecProposal(n));
> ```

If we're creating an `IpSecProposal` here, do we also need to `defineStructure` here?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1576)*

**Comment by sfraint** [comment]
Review status: 2 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpsecProposal.java, line 91 at r2](https://reviewable.io/reviews/batfish/batfish/1576#-LEBBqAd9sHlorEQE04W:-LEBBqAd9sHlorEQE04X:b-l9mmb0) ([raw file](https://github.com/batfish/batfish/blob/2963e942ec3006912095a98cebace4e56eefa850/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpsecProposal.java#L91)):*
> ```Java
>   }
> 
>   public IpsecProposal(String name, int definitionLine) {
> ```

You can (and should) still get rid of this method

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1576)*

**Comment by vasu018** [comment]
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpsecProposal.java, line 85 at r1](https://reviewable.io/reviews/batfish/batfish/1576#-LEAfO-O70Yj2Xxc8KO5:-LEBEQ_c9BQdqoP3wPtU:b6lb1s) ([raw file](https://github.com/batfish/batfish/blob/0a2f95a2ffac541d969e19d0057280157b1b4d89/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpsecProposal.java#L85)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

I think this annotation needs to stay, in order for deserialization to work
</blockquote></details>

Yes. Taken care.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1576)*

**Comment by vasu018** [comment]
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpsecProposal.java, line 85 at r1](https://reviewable.io/reviews/batfish/batfish/1576#-LEAfko9BbcTumHFMm7W:-LEBy6HYCengtFd1UsZ-:b-3brynu) ([raw file](https://github.com/batfish/batfish/blob/8ef88dc113c85ff9013df73fffad51d4f9c65cea/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpsecProposal.java#L85)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

Get rid of `_definitionLine` and its uses if it is no longer needed.
</blockquote></details>

Retaining this to accommodate the Juniper configuration which uses old reference model.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1576)*

**Comment by vasu018** [comment]
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpsecProposal.java, line 91 at r2](https://reviewable.io/reviews/batfish/batfish/1576#-LEBBqAd9sHlorEQE04W:-LEByE1m5EarFQafj7fC:b-lpzklp) ([raw file](https://github.com/batfish/batfish/blob/2963e942ec3006912095a98cebace4e56eefa850/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpsecProposal.java#L91)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

You can (and should) still get rid of this method
</blockquote></details>

Similarly, retaining this to accommodate the Juniper configuration which uses old reference model. Pushed new code changes.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1576)*

**Comment by vasu018** [comment]
*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 2450 at r1](https://reviewable.io/reviews/batfish/batfish/1576#-LEAghz1CHnLpPcOgmEV:-LEBygE27EcJ-dFw5TLv:b-lg44a7) ([raw file](https://github.com/batfish/batfish/blob/8ef88dc113c85ff9013df73fffad51d4f9c65cea/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L2450)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

If we're creating an `IpSecProposal` here, do we also need to `defineStructure` here?
</blockquote></details>

May not be required. IpsecPropsal() is used as part of the IPSEC_PROFILE and IPSEC_TRANSFORM_SET, which are actually defined and reference. Please let me know, if there is gap in my understanding.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1576)*

**Comment by sfraint** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1576#-:-LEC7JfuCU0J4o1E-baE:bnfp4nl)*

**Comment by dhalperi** [comment]
*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpsecProposal.java, line 92 at r4](https://reviewable.io/reviews/batfish/batfish/1576#-LECHVuQ2hYcuCc41NA9:-LECHVuQ2hYcuCc41NAA:bzfbscu) ([raw file](https://github.com/batfish/batfish/blob/bff03867380518a33e36ae008b8fb602cf98c7a0/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/IpsecProposal.java#L92)):*
> ```Java
> 
>   /*
>    * [TODO]: Currently IpsecProposal() is used in Juniper ConfigurationBuilder and
> ```

These should be written as `TODO: (github issue # or person)`, not `[TODO]`. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1576)*

**Pull request merged**
