### PR TITLE
Layer2Node: canonicalize ranges

### PR DESCRIPTION
**Pull request by dhalperi**
Otherwise equivalent nodes will not be considered the same.

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6975)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[projects/allinone/src/test/java/org/batfish/e2e/layer2ntc/Layer2NtcTest.java, line 43 at r2](https://reviewable.io/reviews/batfish/batfish/6975#-MZZ1CkO3gdCC10VdBOi:-MZZ1CkO3gdCC10VdBOj:b-u93git) ([raw file](https://github.com/batfish/batfish/blob/b7daa8eab1a741d86371a4b905cc9e5f47206523/projects/allinone/src/test/java/org/batfish/e2e/layer2ntc/Layer2NtcTest.java#L43)):*
> ```Java
>             NodeInterfacePair.of("rtr-1", "xe-0/0/0.10"),
>             NodeInterfacePair.of("rtr-isp-1", "xe-0/0/1.20"));
>     assertThat(layer3.getEdges(), containsInAnyOrder(forward, forward.reverse()));
> ```

What does this test prove? In the absence of L1 data, aren't these edges inferred completely independently of L1/2 semantics?

**Comment by dhalperi** [comment]
___
*[projects/allinone/src/test/java/org/batfish/e2e/layer2ntc/Layer2NtcTest.java, line 43 at r2](https://reviewable.io/reviews/batfish/batfish/6975#-MZZ1CkO3gdCC10VdBOi:-MZZ5AlE7UDBGQfbBVV4:b6zrrk4) ([raw file](https://github.com/batfish/batfish/blob/b7daa8eab1a741d86371a4b905cc9e5f47206523/projects/allinone/src/test/java/org/batfish/e2e/layer2ntc/Layer2NtcTest.java#L43)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

What does this test prove? In the absence of L1 data, aren't these edges inferred completely independently of L1/2 semantics?
</blockquote></details>

Good catch!

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6975)* status: 9 of 11 files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[projects/allinone/src/test/resources/org/batfish/e2e/layer2ntc/batfish/layer1_topology.json, line 19 at r3](https://reviewable.io/reviews/batfish/batfish/6975#-MZZ8myv7fnIskuDzBdY:-MZZ8myw-BIxobGsAUYT:bg545d2) ([raw file](https://github.com/batfish/batfish/blob/769b24165bc8c267fe02ea2fd4e58f7810a7a0df/projects/allinone/src/test/resources/org/batfish/e2e/layer2ntc/batfish/layer1_topology.json#L19)):*
> ```JSON
>             },
>             "node2": {
>                 "hostname": "sw-1",
> ```

Shouldn't this be fw-1 per your comment in the test? Same question for other json file.

**Review by arifogel — COMMENTED** [review]
> Reviewed 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6975)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi)

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6975)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
