### PR TITLE
Arista: Convert BGP peers with null remote AS

### PR DESCRIPTION
**Pull request by ratulm**

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6958)* status: all files reviewed, 1 unresolved discussion (waiting on @ratulm)

___
*[projects/batfish/src/main/java/org/batfish/representation/arista/AristaConversions.java, line 184 at r2](https://reviewable.io/reviews/batfish/batfish/6958#-MZ8fwcMB6Oe6LX2zQas:-MZ8fwcMB6Oe6LX2zQat:b-svu3st) ([raw file](https://github.com/batfish/batfish/blob/1fe1de6cd280e9bca0ba8f0205495748397ea2b4/projects/batfish/src/main/java/org/batfish/representation/arista/AristaConversions.java#L184)):*
> ```Java
>     // No remote AS set.
>     if (neighbor.getRemoteAs() == null) {
>       w.redFlag("No remote-as configured for " + name);
> ```

keep the warnings?

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6958)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/representation/arista/AristaConversions.java, line 184 at r2](https://reviewable.io/reviews/batfish/batfish/6958#-MZ8fwcMB6Oe6LX2zQas:-MZ9MW-H6KODL7BBf3Aw:b-vz97vl) ([raw file](https://github.com/batfish/batfish/blob/1fe1de6cd280e9bca0ba8f0205495748397ea2b4/projects/batfish/src/main/java/org/batfish/representation/arista/AristaConversions.java#L184)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

keep the warnings?
</blockquote></details>

ok, put the warning back. (unclear if we have a consistent strategy for surfacing broken config warnings, as opposed to batfish-does-not-understand warnings.)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6958)* status: all files reviewed, 1 unresolved discussion (waiting on @ratulm)

___
*[projects/batfish/src/main/java/org/batfish/representation/arista/AristaConversions.java, line 184 at r2](https://reviewable.io/reviews/batfish/batfish/6958#-MZ8fwcMB6Oe6LX2zQas:-MZ9w_1t23PXQHAemt8H:b-7a9tdp) ([raw file](https://github.com/batfish/batfish/blob/1fe1de6cd280e9bca0ba8f0205495748397ea2b4/projects/batfish/src/main/java/org/batfish/representation/arista/AristaConversions.java#L184)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

ok, put the warning back. (unclear if we have a consistent strategy for surfacing broken config warnings, as opposed to batfish-does-not-understand warnings.)
</blockquote></details>

Not sure what you mean? Convert warnings are ~always redFlag warnings.
___
*[projects/batfish/src/main/java/org/batfish/representation/arista/AristaConversions.java, line 215 at r3](https://reviewable.io/reviews/batfish/batfish/6958#-MZ9wVe4D9jOCLzMcvoR:-MZ9wVe4D9jOCLzMcvoS:b-8kv9z8) ([raw file](https://github.com/batfish/batfish/blob/1fe1de6cd280e9bca0ba8f0205495748397ea2b4/projects/batfish/src/main/java/org/batfish/representation/arista/AristaConversions.java#L215)):*
> ```Java
>     // No remote AS set.
>     if (neighbor.getRemoteAs() == null && neighbor.getPeerFilter() == null) {
>       w.redFlag("No remote-as configured for " + name);
> ```

Missed this one, I think?

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6958)* status: all files reviewed, 1 unresolved discussion (waiting on @ratulm)

___
*[projects/batfish/src/main/java/org/batfish/representation/arista/AristaConversions.java, line 377 at r3](https://reviewable.io/reviews/batfish/batfish/6958#-MZ9wqSF1Z0NvXU2g5xF:-MZ9wqSF1Z0NvXU2g5xG:b176q09) ([raw file](https://github.com/batfish/batfish/blob/80b281653f4f427e2f21da243e57caa79394cec7/projects/batfish/src/main/java/org/batfish/representation/arista/AristaConversions.java#L377)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
>       assert neighbor instanceof AristaBgpV4Neighbor;
>       if (neighbor.getRemoteAs() == null) {
>         warnings.redFlag(
>             String.format(
>                 "No remote-as configured for %s",
>                 getTextDesc(((AristaBgpV4Neighbor) neighbor).getIp(), vrf)));
>       }
> ```
</details>

Not sure how this covers both warnings. It looks like we're not warning on dynamics any more?

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6958)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/representation/arista/AristaConversions.java, line 184 at r2](https://reviewable.io/reviews/batfish/batfish/6958#-MZ8fwcMB6Oe6LX2zQas:-MZBog6h7WqvUvLkgj_r:bqlseb7) ([raw file](https://github.com/batfish/batfish/blob/1fe1de6cd280e9bca0ba8f0205495748397ea2b4/projects/batfish/src/main/java/org/batfish/representation/arista/AristaConversions.java#L184)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Not sure what you mean? Convert warnings are ~always redFlag warnings.
</blockquote></details>

Just meant that we don't always when a BGP peer is broken (in other ways) or for other broken things. 

(but yes, when we do, it tends to be redflag.)
___
*[projects/batfish/src/main/java/org/batfish/representation/arista/AristaConversions.java, line 377 at r3](https://reviewable.io/reviews/batfish/batfish/6958#-MZ9wqSF1Z0NvXU2g5xF:-MZBo_8e9zZ9c_dhxD9c:byi84qc) ([raw file](https://github.com/batfish/batfish/blob/80b281653f4f427e2f21da243e57caa79394cec7/projects/batfish/src/main/java/org/batfish/representation/arista/AristaConversions.java#L377)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
>       assert neighbor instanceof AristaBgpV4Neighbor;
>       if (neighbor.getRemoteAs() == null) {
>         warnings.redFlag(
>             String.format(
>                 "No remote-as configured for %s",
>                 getTextDesc(((AristaBgpV4Neighbor) neighbor).getIp(), vrf)));
>       }
> ```
Not sure how this covers both warnings. It looks like we're not warning on dynamics any more?
</blockquote></details>

yeah, had missed this one. fixed.

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6958)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/representation/arista/AristaConversions.java, line 377 at r3](https://reviewable.io/reviews/batfish/batfish/6958#-MZ9wqSF1Z0NvXU2g5xF:-MZBqFz45DT8YZbZdVRB:b-vw0tl) ([raw file](https://github.com/batfish/batfish/blob/80b281653f4f427e2f21da243e57caa79394cec7/projects/batfish/src/main/java/org/batfish/representation/arista/AristaConversions.java#L377)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

yeah, had missed this one. fixed.
</blockquote></details>

to be precise, the earlier warning would have never fired because the parser forced at least one of remote-as and peer-filter to be defined. the situation under which remote-as would have turned up empty is when the peer-filter itself rejected all remote ases. added a warning and a test.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6958)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
