### PR TITLE
A10: `access-list` extraction

### PR DESCRIPTION
**Pull request by sfraint**

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 17 of 18 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7709)* status: all files reviewed, 6 unresolved discussions (waiting on @corinaminer and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java, line 239 at r2](https://reviewable.io/reviews/batfish/batfish/7709#-Mokicab2Zg5o7DC1F56:-Mokicab2Zg5o7DC1F57:b-df20at) ([raw file](https://github.com/batfish/batfish/blob/a926e18aebe6905b74cd8389b4d65de03f6c07e0/projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java#L239)):*
> ```Java
>   @Override
>   public void enterSi_access_list(A10Parser.Si_access_listContext ctx) {
>     _currentAccessList =
> ```

add `TODO: define structure` or just do it.
___
*[projects/batfish/src/main/java/org/batfish/vendor/a10/representation/AccessList.java, line 24 at r2](https://reviewable.io/reviews/batfish/batfish/7709#-Mokjb488WlZQ6DY5fUU:-Mokjb488WlZQ6DY5fUV:b-r1mt0) ([raw file](https://github.com/batfish/batfish/blob/a926e18aebe6905b74cd8389b4d65de03f6c07e0/projects/batfish/src/main/java/org/batfish/vendor/a10/representation/AccessList.java#L24)):*
> ```Java
>     ImmutableList.Builder<AccessListRule> builder =
>         ImmutableList.<AccessListRule>builder().addAll(_rules);
>     _rules = builder.add(rule).build();
> ```

nit: could inline the local variable. Also, should probably use `builderWithExpectedSize`.
___
*[projects/batfish/src/main/java/org/batfish/vendor/a10/representation/AccessListRuleIcmp.java, line 6 at r2](https://reviewable.io/reviews/batfish/batfish/7709#-MokjzPw0L2lRytze4dC:-MokjzPw0L2lRytze4dD:b6y2y8y) ([raw file](https://github.com/batfish/batfish/blob/a926e18aebe6905b74cd8389b4d65de03f6c07e0/projects/batfish/src/main/java/org/batfish/vendor/a10/representation/AccessListRuleIcmp.java#L6)):*
> ```Java
> 
> /** An access-list rule matching icmp traffic. */
> public class AccessListRuleIcmp implements AccessListRule {
> ```

No code or type ranges needed?
___
*[projects/batfish/src/main/java/org/batfish/vendor/a10/representation/AccessListRuleTcp.java, line 29 at r2](https://reviewable.io/reviews/batfish/batfish/7709#-Mokk8ol9oS8TGV9nBLf:-Mokk8ol9oS8TGV9nBLg:btxocfc) ([raw file](https://github.com/batfish/batfish/blob/a926e18aebe6905b74cd8389b4d65de03f6c07e0/projects/batfish/src/main/java/org/batfish/vendor/a10/representation/AccessListRuleTcp.java#L29)):*
> ```Java
>   /** Destination port range this rule matches on. */
>   @Nullable
>   public SubRange getDestinationRange() {
> ```

No source range needed? Same question for UDP.
___
*[projects/batfish/src/test/java/org/batfish/vendor/a10/grammar/A10GrammarTest.java, line 2172 at r2](https://reviewable.io/reviews/batfish/batfish/7709#-MokkMFJ6nK39QhxGter:-MokkMFJ6nK39QhxGtes:b-mw8r1l) ([raw file](https://github.com/batfish/batfish/blob/a926e18aebe6905b74cd8389b4d65de03f6c07e0/projects/batfish/src/test/java/org/batfish/vendor/a10/grammar/A10GrammarTest.java#L2172)):*
> ```Java
> 
>     assertThat(rules, iterableWithSize(4));
>     assertThat(rules.get(0), CoreMatchers.instanceOf(AccessListRuleIcmp.class));
> ```

nit: we usually use `Matchers` over `CoreMatchers`, and do static import of matchers when unambiguous.
___
*[projects/batfish/src/test/java/org/batfish/vendor/a10/grammar/A10GrammarTest.java, line 2177 at r2](https://reviewable.io/reviews/batfish/batfish/7709#-Mokkone7OvT5Rm5q8xT:-Mokkone7OvT5Rm5q8xU:b-dld8cg) ([raw file](https://github.com/batfish/batfish/blob/a926e18aebe6905b74cd8389b4d65de03f6c07e0/projects/batfish/src/test/java/org/batfish/vendor/a10/grammar/A10GrammarTest.java#L2177)):*
> ```Java
>     assertThat(rules.get(3), CoreMatchers.instanceOf(AccessListRuleUdp.class));
>     AccessListRuleIcmp rule1 = (AccessListRuleIcmp) rules.get(0);
>     AccessListRuleTcp rule2 = (AccessListRuleTcp) rules.get(1);
> ```

All code paths already covered for properties of last two rules?

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7709)* status: 13 of 22 files reviewed, 6 unresolved discussions (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java, line 239 at r2](https://reviewable.io/reviews/batfish/batfish/7709#-Mokicab2Zg5o7DC1F56:-Moo6yJC59jBMavr67vc:b-2p4tdj) ([raw file](https://github.com/batfish/batfish/blob/a926e18aebe6905b74cd8389b4d65de03f6c07e0/projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java#L239)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

add `TODO: define structure` or just do it.
</blockquote></details>

I'll go ahead and add that
___
*[projects/batfish/src/main/java/org/batfish/vendor/a10/representation/AccessList.java, line 24 at r2](https://reviewable.io/reviews/batfish/batfish/7709#-Mokjb488WlZQ6DY5fUU:-MooEw6pA37Qz6rmXud4:bvnrpcm) ([raw file](https://github.com/batfish/batfish/blob/a926e18aebe6905b74cd8389b4d65de03f6c07e0/projects/batfish/src/main/java/org/batfish/vendor/a10/representation/AccessList.java#L24)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

nit: could inline the local variable. Also, should probably use `builderWithExpectedSize`.
</blockquote></details>

updated
___
*[projects/batfish/src/main/java/org/batfish/vendor/a10/representation/AccessListRuleIcmp.java, line 6 at r2](https://reviewable.io/reviews/batfish/batfish/7709#-MokjzPw0L2lRytze4dC:-Moo73S575iKssHdYqha:bh4z7) ([raw file](https://github.com/batfish/batfish/blob/a926e18aebe6905b74cd8389b4d65de03f6c07e0/projects/batfish/src/main/java/org/batfish/vendor/a10/representation/AccessListRuleIcmp.java#L6)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

No code or type ranges needed?
</blockquote></details>

Those are options, but I was shooting for a more minimal implementation to speed this up.
___
*[projects/batfish/src/main/java/org/batfish/vendor/a10/representation/AccessListRuleTcp.java, line 29 at r2](https://reviewable.io/reviews/batfish/batfish/7709#-Mokk8ol9oS8TGV9nBLf:-Moo7IsF2-SMzlbrnuGh:b-m3z7z0) ([raw file](https://github.com/batfish/batfish/blob/a926e18aebe6905b74cd8389b4d65de03f6c07e0/projects/batfish/src/main/java/org/batfish/vendor/a10/representation/AccessListRuleTcp.java#L29)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

No source range needed? Same question for UDP.
</blockquote></details>

Those (and many others) are options. I left out most things I hadn't seen exercised in real configs, as I was shooting for a more minimal implementation to speed this up.
___
*[projects/batfish/src/test/java/org/batfish/vendor/a10/grammar/A10GrammarTest.java, line 2172 at r2](https://reviewable.io/reviews/batfish/batfish/7709#-MokkMFJ6nK39QhxGter:-Moo7lpIB_35kAgyEf_L:bvnrpcm) ([raw file](https://github.com/batfish/batfish/blob/a926e18aebe6905b74cd8389b4d65de03f6c07e0/projects/batfish/src/test/java/org/batfish/vendor/a10/grammar/A10GrammarTest.java#L2172)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

nit: we usually use `Matchers` over `CoreMatchers`, and do static import of matchers when unambiguous.
</blockquote></details>

updated
___
*[projects/batfish/src/test/java/org/batfish/vendor/a10/grammar/A10GrammarTest.java, line 2177 at r2](https://reviewable.io/reviews/batfish/batfish/7709#-Mokkone7OvT5Rm5q8xT:-MooEedh6Q7cj-Gh6oGt:bvnrpcm) ([raw file](https://github.com/batfish/batfish/blob/a926e18aebe6905b74cd8389b4d65de03f6c07e0/projects/batfish/src/test/java/org/batfish/vendor/a10/grammar/A10GrammarTest.java#L2177)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

All code paths already covered for properties of last two rules?
</blockquote></details>

updated

**Review by arifogel — COMMENTED** [review]
> Reviewed 2 of 3 files at r3, 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7709)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java, line 2108 at r4](https://reviewable.io/reviews/batfish/batfish/7709#-MoooFVm2DyEzKvJsd2p:-MoooFVn2NIojcve0VrB:b-4miitu) ([raw file](https://github.com/batfish/batfish/blob/6f10d586af969e93216de5e4d43835b27ef97a30/projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java#L2108)):*
> ```Java
>               }
>               if (_c.getAccessLists().get(n).getRules().isEmpty()) {
>                 warn(ctx, String.format("Cannot reference empty ip access-list '%s'", n));
> ```

Really? wow

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7709)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java, line 2108 at r4](https://reviewable.io/reviews/batfish/batfish/7709#-MoooFVm2DyEzKvJsd2p:-MootibpDe5KydCA3OUx:b2811sq) ([raw file](https://github.com/batfish/batfish/blob/6f10d586af969e93216de5e4d43835b27ef97a30/projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java#L2108)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Really? wow
</blockquote></details>

Yeah...
```
vThunder(config)(NOLICENSE)#ip access-list acl2
vThunder(config-access-list:acl2)(NOLICENSE)#exit
```
```
vThunder(config)(NOLICENSE)#slb virtual-server VIRTSERVER2
vThunder(config-slb vserver-vport)(NOLICENSE)#access-list name acl2              
No such ACL or the ACL does not have any rules.
```

**Pull request merged**
