### PR TITLE
Initialization: add more logging

### PR DESCRIPTION
**Pull request by sfraint**

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7093)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown)

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7093)* status: all files reviewed, 1 unresolved discussion (waiting on @anothermattbrown and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 2166 at r1](https://reviewable.io/reviews/batfish/batfish/7093#-McqmF-6AdEKGXdWJQwv:-McqmF-6AdEKGXdWJQww:ba064mz) ([raw file](https://github.com/batfish/batfish/blob/6ea5fb0836b5d5aafb0d6364b35932e5a1182fc9/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L2166)):*
> ```Java
> 
>     if (_settings.getSerializeVendor()) {
>       LOGGER.info("Serializing Vendor-Specific configurations");
> ```

I think these are mostly misleading. E.g., doesn't this function actually parse first?

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7093)* status: all files reviewed, 1 unresolved discussion (waiting on @anothermattbrown and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 2166 at r1](https://reviewable.io/reviews/batfish/batfish/7093#-McqmF-6AdEKGXdWJQwv:-McqmLNC6vYcnHw7IsvH:b-i17gb4) ([raw file](https://github.com/batfish/batfish/blob/6ea5fb0836b5d5aafb0d6364b35932e5a1182fc9/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L2166)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I think these are mostly misleading. E.g., doesn't this function actually parse first?
</blockquote></details>

Prefer to put these nearer the work being done (see spans) to increase confidence of such.

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7093)* status: all files reviewed, 2 unresolved discussions (waiting on @anothermattbrown and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 2208 at r1](https://reviewable.io/reviews/batfish/batfish/7093#-McqmgOxAtjLsya2iXEA:-McqmgOyE3KQI4tpVnnj:b-695rx3) ([raw file](https://github.com/batfish/batfish/blob/6ea5fb0836b5d5aafb0d6364b35932e5a1182fc9/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L2208)):*
> ```Java
> 
>     if (_settings.getDataPlane()) {
>       LOGGER.info("Computing data-plane");
> ```

Example: after this, configurations might get loaded. There is a log ~at the beginnign of real dataplane computation:       LOGGER.info("Computing Data Plane using iBDP");

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7093)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7093)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 2166 at r1](https://reviewable.io/reviews/batfish/batfish/7093#-McqmF-6AdEKGXdWJQwv:-McttDrXAO1cdmbl33_E:b-xw5a31) ([raw file](https://github.com/batfish/batfish/blob/6ea5fb0836b5d5aafb0d6364b35932e5a1182fc9/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L2166)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Prefer to put these nearer the work being done (see spans) to increase confidence of such.
</blockquote></details>

yeah, adjusted & moved these in further
___
*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 2208 at r1](https://reviewable.io/reviews/batfish/batfish/7093#-McqmgOxAtjLsya2iXEA:-McurrUFC1q9pi157dJh:b-ju76z8) ([raw file](https://github.com/batfish/batfish/blob/6ea5fb0836b5d5aafb0d6364b35932e5a1182fc9/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L2208)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Example: after this, configurations might get loaded. There is a log ~at the beginnign of real dataplane computation:       LOGGER.info("Computing Data Plane using iBDP");
</blockquote></details>

ack, ended up just adding logging for building the topology before really starting data-plane computation

**Pull request merged**
