### PR TITLE
Checkpoint manual hide nat rule conversion

### PR DESCRIPTION
**Pull request by arifogel**
- TODO: attach to interfaces
- TOOD: install individual rules only on applicable gateways

### CODE REVIEW

**Review by sfraint — COMMENTED** [review]
> Reviewed 9 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7310)* status: all files reviewed, 4 unresolved discussions (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java, line 205 at r1](https://reviewable.io/reviews/batfish/batfish/7310#-Mid0egC6Sss5WJiCr3I:-Mid0egC6Sss5WJiCr3J:b-6eyl3n) ([raw file](https://github.com/batfish/batfish/blob/ff2c8d8db1f01fe2ea8832d95427014615fc00df/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java#L205)):*
> ```
> .filter(rule -> rule.getMethod() == NatMethod.HIDE)
> ```
should probably warn about non-hide rules if we're not going to handle them soon
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConversions.java, line 44 at r1](https://reviewable.io/reviews/batfish/batfish/7310#-Mid1NDW4mc49cGeQi8v:-Mid1NDW4mc49cGeQi8w:b-98jocp) ([raw file](https://github.com/batfish/batfish/blob/ff2c8d8db1f01fe2ea8832d95427014615fc00df/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConversions.java#L44)):*
> ```
> {@link }HeaderSpace}
> ```
nit: extra `}`
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConversions.java, line 57 at r1](https://reviewable.io/reviews/batfish/batfish/7310#-Mid1p-hEXZotrsB6bGU:-Mid1p-i8qPlRRttSeia:b-qid6s8) ([raw file](https://github.com/batfish/batfish/blob/ff2c8d8db1f01fe2ea8832d95427014615fc00df/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConversions.java#L57)):*
> ```
>     hsb.setSrcIps(ipSpaces.get(src.getName()));
> ```
somewhat general question: is it better to lookup the IpSpace and embed it, or add an IpSpaceReference?
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversions.java, line 108 at r1](https://reviewable.io/reviews/batfish/batfish/7310#-Mid4VjLD0u20UVSyGv8:-Mid4VjLD0u20UVSyGv9:b-x0l12t) ([raw file](https://github.com/batfish/batfish/blob/ff2c8d8db1f01fe2ea8832d95427014615fc00df/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversions.java#L108)):*
> ```
>   private static boolean checkValidManualHide(
> ```
would be helpful to have docstrings for at least some of these functions and visitor implementations
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversions.java, line 114 at r1](https://reviewable.io/reviews/batfish/batfish/7310#-Mid4j3p3QhX1X1Qejp1:-Mid4j3p3QhX1X1Qejp2:b-802n64) ([raw file](https://github.com/batfish/batfish/blob/ff2c8d8db1f01fe2ea8832d95427014615fc00df/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversions.java#L114)):*
> ```
>     if (!(src instanceof Machine)) {
> ```
should probably add a `TODO` here since we're only temporarily limiting scope of types of transformations we're supporting
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversions.java, line 141 at r1](https://reviewable.io/reviews/batfish/batfish/7310#-Mid58Ke2oPiOaS_GyOi:-Mid58Ke2oPiOaS_GyOj:b3n05gm) ([raw file](https://github.com/batfish/batfish/blob/ff2c8d8db1f01fe2ea8832d95427014615fc00df/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversions.java#L141)):*
> ```
> getNatRules
> ```
nit: maybe `getApplicableNatRules`? or at least add a docstring indicating filtering is occurring

here and below

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7310)* status: all files reviewed, 4 unresolved discussions (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConversions.java, line 44 at r1](https://reviewable.io/reviews/batfish/batfish/7310#-Mid1NDW4mc49cGeQi8v:-Mid6eQ7-xb0CZmYp8B3:b-ypnfrs) ([raw file](https://github.com/batfish/batfish/blob/ff2c8d8db1f01fe2ea8832d95427014615fc00df/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConversions.java#L44)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
> {@link }HeaderSpace}
> ```
nit: extra `}`
</blockquote></details>

looks like this is fixed

**Review by sfraint — COMMENTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7310)* status: all files reviewed, 4 unresolved discussions (waiting on @arifogel)

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7310)* status: 8 of 16 files reviewed, 2 unresolved discussions (waiting on @arifogel and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java, line 205 at r1](https://reviewable.io/reviews/batfish/batfish/7310#-Mid0egC6Sss5WJiCr3I:-MidNcYc5OmyC2vcon9v:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/ff2c8d8db1f01fe2ea8832d95427014615fc00df/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConfiguration.java#L205)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
> .filter(rule -> rule.getMethod() == NatMethod.HIDE)
> ```
should probably warn about non-hide rules if we're not going to handle them soon
</blockquote></details>

done
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConversions.java, line 57 at r1](https://reviewable.io/reviews/batfish/batfish/7310#-Mid1p-hEXZotrsB6bGU:-MidMjSm0HJKbcvtfuD5:b492xhs) ([raw file](https://github.com/batfish/batfish/blob/ff2c8d8db1f01fe2ea8832d95427014615fc00df/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConversions.java#L57)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
>     hsb.setSrcIps(ipSpaces.get(src.getName()));
> ```
somewhat general question: is it better to lookup the IpSpace and embed it, or add an IpSpaceReference?
</blockquote></details>

Probably better to use a reference. Makes testing easier, too.
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversions.java, line 108 at r1](https://reviewable.io/reviews/batfish/batfish/7310#-Mid4VjLD0u20UVSyGv8:-MidMqm9Db7y2RxPfDh0:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/ff2c8d8db1f01fe2ea8832d95427014615fc00df/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversions.java#L108)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
>   private static boolean checkValidManualHide(
> ```
would be helpful to have docstrings for at least some of these functions and visitor implementations
</blockquote></details>

done
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversions.java, line 114 at r1](https://reviewable.io/reviews/batfish/batfish/7310#-Mid4j3p3QhX1X1Qejp1:-MidKxGf5Kj4WIpJXL5w:b-2lgbtl) ([raw file](https://github.com/batfish/batfish/blob/ff2c8d8db1f01fe2ea8832d95427014615fc00df/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversions.java#L114)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
>     if (!(src instanceof Machine)) {
> ```
should probably add a `TODO` here since we're only temporarily limiting scope of types of transformations we're supporting
</blockquote></details>

No, this will always be a limitation for a manual hide rule.
We should have other functions for other types of rules.
___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversions.java, line 141 at r1](https://reviewable.io/reviews/batfish/batfish/7310#-Mid58Ke2oPiOaS_GyOi:-MidMbGQ2L37Lr7BYTqw:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/ff2c8d8db1f01fe2ea8832d95427014615fc00df/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckpointNatConversions.java#L141)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
> getNatRules
> ```
nit: maybe `getApplicableNatRules`? or at least add a docstring indicating filtering is occurring

here and below
</blockquote></details>

done

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7310)* status: 7 of 16 files reviewed, 1 unresolved discussion (waiting on @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConversions.java, line 57 at r1](https://reviewable.io/reviews/batfish/batfish/7310#-Mid1p-hEXZotrsB6bGU:-MiduUyy9sysS9TaVRWC:befjucz) ([raw file](https://github.com/batfish/batfish/blob/ff2c8d8db1f01fe2ea8832d95427014615fc00df/projects/batfish/src/main/java/org/batfish/vendor/check_point_gateway/representation/CheckPointGatewayConversions.java#L57)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Probably better to use a reference. Makes testing easier, too.
</blockquote></details>

done, and skipped for `CpmiAnyObject`

**Review by sfraint — COMMENTED** [review]
> Reviewed 4 of 7 files at r4, 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7310)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Pull request merged**
