### PR TITLE
CheckPoint: add warning when no access package is found

### PR DESCRIPTION
**Pull request by sfraint**

### CODE REVIEW

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7651)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @arifogel and @corinaminer)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7651#-MnYIDa47DjB4H1aH3Rn:-MnYIDa47DjB4H1aH3Ro:b-6bhuw7) (no related file):*
Arguably, you could use a firewall without access rules.
Though, imo seems more likely to be a bug / something we should warn about.

---

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7651)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7651#-MnYIDa47DjB4H1aH3Rn:-MnbD5sd1BSk0BdweeHL:bafzn3u) (no related file):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

Arguably, you could use a firewall without access rules.
Though, imo seems more likely to be a bug / something we should warn about.
</blockquote></details>

The warning for missing access package is a management-data-specific check? I'm having trouble understanding the exact situation in which this warning occurs.

---

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7651)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel and @corinaminer)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7651#-MnYIDa47DjB4H1aH3Rn:-MnbE49b1-vKmXJiVj2q:bwer0fi) (no related file):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

The warning for missing access package is a management-data-specific check? I'm having trouble understanding the exact situation in which this warning occurs.
</blockquote></details>

I think you originally wrote this code :stuck_out_tongue: 

Yes, this is when some management data exists for this device, but it doesn't contain an access policy.
We could (should?) also add a warning when no management data exists for the device.

---

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7651)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7651#-MnYIDa47DjB4H1aH3Rn:-MnbJvPR1L92e6MS7kry:bwmjh2e) (no related file):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

I think you originally wrote this code :stuck_out_tongue: 

Yes, this is when some management data exists for this device, but it doesn't contain an access policy.
We could (should?) also add a warning when no management data exists for the device.

</blockquote></details>

OK this is fine, and the other thing you mentioned is obviously orthogonal.

---

**Pull request merged**
