### PR TITLE
Infrastructure for container-wide adhoc questions

### PR DESCRIPTION
**Pull request by corinaminer**
__Definitely should be reviewed commit by commit.__ Can separate each API call into its own PR if that's appropriate; currently they're separated by commit.

Goal: Reformulate adhoc questions as container-level rather than testrig-level.

Introduces API calls that work with container-level `explore` and `compare` directories. The container-level directories have container-wide adhoc questions (differential in `compare`, non-differential in `explore`), while each testrig folder contains its own `explore` and `compare` directories to hold those questions' answers, similar to the current setup for analyses. Example file structure inside container:
image

In time we should move towards using only the new API calls for adhoc questions. For now all the old API calls are preserved. Batfish should not need to be changed again in order to start using the new ones.

---
This change is [Reviewable](https://reviewable.io/reviews/batfish/batfish/678)

### CODE REVIEW

**Comment by ratulm** [comment]
@corinaminer, is the design intent documented someplace? I find it hard to judge new functionality without it. Some of this looks counter-intuitive to me otherwise. E.g., why would you need "configureExplore" functionality? I expected the set of questions inside explore to be "organically" populated as users interact with the system. (Its easier to validate the design intent first and then validate if the code correctly implements it. Otherwise, I have to infer intent from the code, which is erroneous.)

**Comment by dhalperi** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/batfish/batfish/678#-L-4N0mFWig1jbnj9AUW:-L-4N0mGR0eusk6xy9v1:b332oop) (no related file):*
My belief is that based on follow-up design discussions, this approach will be changed in favor of one that uses existing APIs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/678)*

**Comment by corinaminer** [comment]
[Link to design doc](https://docs.google.com/document/d/1FeWmViKuCz2wnLT4S9pHZfx7gD8ofnNftGkmlquq41U/edit)

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/678#-:-L-4WR2zmndDYxoYdr8b:b4vfqle)*

**Comment by corinaminer** [comment]
Replaced by #690.

**Pull request closed without merging**
