### PR TITLE
Cisco NX-OS: extraction for bgp address-family 'nexthop route-map'

### PR DESCRIPTION
**Pull request by arifogel**

### CODE REVIEW

**Review by zergling-aws — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8852)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @arifogel, @dhalperi, @sfraint, and @SLarkworthy)

___
*[`projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/BgpVrfIpAddressFamilyConfiguration.java` line 105 at r2](https://reviewable.io/reviews/batfish/batfish/8852#-Nhnb1sG0xO89DpyfQ-B:-Nhnb1sHAvto7RI66ZPv:bol40f8) ([raw file](https://github.com/batfish/batfish/blob/190298bef09c0b6b9abbecb14339479f2aa4a3bd/projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/BgpVrfIpAddressFamilyConfiguration.java#L105)):*
> ```Java
>    * RIB's direct resolvers for the BGP RIB route's next hop.
>    *
>    * <p>See <a
> ```

what the meaning of `<a`?
___
*[`projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_bgp_nexthop_route_map` line 15 at r2](https://reviewable.io/reviews/batfish/batfish/8852#-Nhndkma7vv9EDBhbtqV:-NhndkmbAhrwN1cx7ZIj:byv2w3e) ([raw file](https://github.com/batfish/batfish/blob/190298bef09c0b6b9abbecb14339479f2aa4a3bd/projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_bgp_nexthop_route_map#L15)):*
> ```
> router bgp 1
>   address-family ipv4 unicast
>     nexthop route-map defined
> ```

when I read this, I wasn't completely sure whether `defined` was your own route map name or a keyword from NXOS syntax. After reading the test case it became clear that this was supposed to be the route map name. But I'm not very familiar with the language syntax to begin with. Also it seems people normally name route maps in all caps (NRP enforces a schema where route maps are named with the pattern "RM\_\[A-Z\]+\[-\_A-Z0-9\]+?\[A-Z0-9\]")
___
*[`projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_bgp_nexthop_route_map` line 18 at r2](https://reviewable.io/reviews/batfish/batfish/8852#-Nhne2XOExJAfxIGXcO2:-Nhne2XP8_Uo-Mxy818O:b94q5bm) ([raw file](https://github.com/batfish/batfish/blob/190298bef09c0b6b9abbecb14339479f2aa4a3bd/projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_bgp_nexthop_route_map#L18)):*
> ```
>   vrf vundefined
>    address-family ipv4 unicast
>     nexthop route-map undefined
> ```

similar comment here about the name `undefined`

**Comment by dhalperi** [comment]
*[`projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/BgpVrfIpAddressFamilyConfiguration.java` line 105 at r2](https://reviewable.io/reviews/batfish/batfish/8852#-Nhnb1sG0xO89DpyfQ-B:-Nhnho2pCVRVAhc-VEU6:bilw7bc) ([raw file](https://github.com/batfish/batfish/blob/190298bef09c0b6b9abbecb14339479f2aa4a3bd/projects/batfish/src/main/java/org/batfish/representation/cisco_nxos/BgpVrfIpAddressFamilyConfiguration.java#L105)):*
<details><summary><i>Previously, zergling-aws wrote…</i></summary><blockquote>

what the meaning of `<a`?
</blockquote></details>

Javadoc has inline html. This is the start of an HTML `<a>` anchor tag with the link inlined as `href` on the wrapped line. First google hit that looked relevant: https://www.oracle.com/technical-resources/articles/java/javadoc-tool.html

**Review by arifogel — COMMENTED** [review]
> Dismissed @zergling-aws from 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8852)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @dhalperi, @sfraint, and @SLarkworthy)

___
*[`projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_bgp_nexthop_route_map` line 15 at r2](https://reviewable.io/reviews/batfish/batfish/8852#-Nhndkma7vv9EDBhbtqV:-Nhs9B0w3NXVdwMRbMrI:bd9v7w3) ([raw file](https://github.com/batfish/batfish/blob/190298bef09c0b6b9abbecb14339479f2aa4a3bd/projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_bgp_nexthop_route_map#L15)):*
<details><summary><i>Previously, zergling-aws wrote…</i></summary><blockquote>

when I read this, I wasn't completely sure whether `defined` was your own route map name or a keyword from NXOS syntax. After reading the test case it became clear that this was supposed to be the route map name. But I'm not very familiar with the language syntax to begin with. Also it seems people normally name route maps in all caps (NRP enforces a schema where route maps are named with the pattern "RM\_\[A-Z\]+\[-\_A-Z0-9\]+?\[A-Z0-9\]")
</blockquote></details>

updated for clarity
___
*[`projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_bgp_nexthop_route_map` line 18 at r2](https://reviewable.io/reviews/batfish/batfish/8852#-Nhne2XOExJAfxIGXcO2:-Nhs9CVeAWX7eenCr3nQ:bd9v7w3) ([raw file](https://github.com/batfish/batfish/blob/190298bef09c0b6b9abbecb14339479f2aa4a3bd/projects/batfish/src/test/resources/org/batfish/grammar/cisco_nxos/testconfigs/nxos_bgp_nexthop_route_map#L18)):*
<details><summary><i>Previously, zergling-aws wrote…</i></summary><blockquote>

similar comment here about the name `undefined`
</blockquote></details>

updated for clarity

**Review by zergling-aws — COMMENTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8852)* status: all files reviewed, 2 unresolved discussions (waiting on @dhalperi)

**Pull request merged**
