### PR TITLE
Add API calls to get parsing or dataplaning work

### PR DESCRIPTION
**Pull request by corinaminer**
Adds API calls `getParsingWork` and `getDataplaningWork`. Both take in a testrig name and return the most recent parsing or dataplaning work on that testrig, complete or incomplete, in the same format you would get it from `listIncompleteWork`. Makes progress information more accessible.

---
This change is [Reviewable](https://reviewable.io/reviews/batfish/batfish/885)

### CODE REVIEW

**Comment by ratulm** [comment]
Two higher-level thoughts/questions:
  - Combine the two API calls into one that takes the type as input since the code is so similar? Actually, I am thinking, why not just expand the listIncompleteWork API call? 
  - What happens when two PARSING works are found in the queue? Right now, you'll return the first one found. If you are going to return one, then returning the last one makes sense. Or, just return all of them and let the client do what they want?

---

Reviewed 2 of 4 files at r1.
Review status: 2 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/885#-:-L483Xpx6G8b2LvOnDmy:b-uk9ccn)*

**Comment by corinaminer** [comment]
- Combine the two API calls: that seems reasonable.
- Just expand `listIncompleteWork`: I think the tasks seem different enough to merit separate API calls. If we use`listIncompleteWork` for this new functionality, then a call for most recent parsing work would return one of two things, which both seem unintuitive:
    - `{workList: stringified List<WorkStatus>}`, as usual, but the list would only have one element
    - `{work: stringified WorkStatus}`, a deviation from the normal structure returned from that function

Is there a reason to limit number of API calls at the expense of clarity? Your call; let me know what you think and I'll revise accordingly.

- Two PARSING works found in the queue: This is a great point, I didn't think about which direction to iterate through the work queues. If there are two parsing work items for the same testrig in the completed work queue, we want the more recent one; but if they're both in the incomplete work queue, we want the older one (queued earlier). Which end of the queue is the "front"?

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/885#-:-L48DYDIpwU86lOHYT_y:buk6euq)*

**Comment by ratulm** [comment]
:lgtm: (if green)

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[projects/coordinator/src/test/java/org/batfish/coordinator/WorkQueueMgrTest.java, line 318 at r2](https://reviewable.io:443/reviews/batfish/batfish/885#-L49oo7HLHOvSlXemJfe:-L49oo7HLHOvSlXemJff:b-4xp30m) ([raw file](https://github.com/batfish/batfish/blob/e7b1ae630e21f373a340747bb0d032aa79f4926b/projects/coordinator/src/test/java/org/batfish/coordinator/WorkQueueMgrTest.java#L318)):*
> ```Java
>         new QueuedWork(
>             new WorkItem(CONTAINER, "testrig"),
>             new WorkDetails("testrig2", "env", WorkType.UNKNOWN));
> ```

There is an inconsistency between the testrig name in WorkItem() and WorkDetails(). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/885#-:-L49p-BefSeXyxZ2RFDf:bopuwz4)*

**Comment by ratulm** [comment]
Travis failure is because of @Nullable annotation after @FormDataParam annotation. Putting the former before the latter should fix things. (I ran into this issue just now.)

**Comment by corinaminer** [comment]
Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/coordinator/src/test/java/org/batfish/coordinator/WorkQueueMgrTest.java, line 318 at r2](https://reviewable.io:443/reviews/batfish/batfish/885#-L49oo7HLHOvSlXemJfe:-L4CUwcjSuNU2PKy3a_X:b8gj3mz) ([raw file](https://github.com/batfish/batfish/blob/e7b1ae630e21f373a340747bb0d032aa79f4926b/projects/coordinator/src/test/java/org/batfish/coordinator/WorkQueueMgrTest.java#L318)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

There is an inconsistency between the testrig name in WorkItem() and WorkDetails(). 
</blockquote></details>

Good catch, fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/885)*

**Comment by ratulm** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/885#-:-L4CW9M25H__ieC9D3Df:bnfp4nl)*

**Pull request merged**
