### PR TITLE
Mo mo mo parsing

### PR DESCRIPTION
**Pull request by ratulm**
After #1520

### CODE REVIEW

**Comment by arifogel** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 3890 at r2](https://reviewable.io/reviews/batfish/batfish/1521#-LDnDSrd8fH6646AjUAl:-LDnDSrd8fH6646AjUAm:bae0rl4) ([raw file](https://github.com/batfish/batfish/blob/12565faa06bba02a11a79928ba78f57a0ea5fd46/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L3890)):*
> ```Java
>     String name = ctx.name.getText();
>     int line = ctx.name.getStart().getLine();
>     _configuration.referenceStructure(ACCESS_LIST, name, CLASS_MAP_ACCESS_LIST, line);
> ```

Unless I am missing something I don't see any tests exercising this code. The ref changes don't show anything about this.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 318 at r2](https://reviewable.io/reviews/batfish/batfish/1521#-LDnD-0X7c6wcdrhwoBX:-LDnD-0X7c6wcdrhwoBY:b-1ejy5v) ([raw file](https://github.com/batfish/batfish/blob/12565faa06bba02a11a79928ba78f57a0ea5fd46/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L318)):*
> ```Java
>   private final Set<String> _classMapAccessGroups;
> 
>   private final Set<String> _classMapAccessLists;
> ```

There is no difference between an access-list and access-group. This field and associated getter, marking, and usage type are unnecessary.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1521)*

**Comment by arifogel** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1521)*

**Comment by arifogel** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1521#-:-LDn_xXQ5MwdvD1rkNLc:bnfp4nl)*

**Comment by arifogel** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[test_rigs/unit-tests/configs/cisco_qos, line 21 at r3](https://reviewable.io/reviews/batfish/batfish/1521#-LDna0be4uz5juP1LYC-:-LDna0bf3TBYJupqxUJV:bd5l78r) ([raw file](https://github.com/batfish/batfish/blob/7321a643af6c64ed805ff830d880d45105d8e528/test_rigs/unit-tests/configs/cisco_qos#L21)):*
> ```
> class-map type pbr match-any boop
>  10 match ip access-group boop
>  20 match ip access-list boop2
> ```

No undefined reference for this?

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1521)*

**Comment by ratulm** [comment]
Review status: 9 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[test_rigs/unit-tests/configs/cisco_qos, line 21 at r3](https://reviewable.io/reviews/batfish/batfish/1521#-LDna0be4uz5juP1LYC-:-LDnb7pr79zJVOoNmv00:b-dvnar2) ([raw file](https://github.com/batfish/batfish/blob/7321a643af6c64ed805ff830d880d45105d8e528/test_rigs/unit-tests/configs/cisco_qos#L21)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

No undefined reference for this?
</blockquote></details>

look carefully :)

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1521)*

**Comment by arifogel** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1521)*

**Pull request merged**
