### PR TITLE
Add support for IncrementMetric in TransferBDD.

### PR DESCRIPTION
**Pull request by nickgian**
Enables support for `set metric +d` in stanzas.
If an overflow occurs, the value is set to the max value of the given field (in case of metric, 2^32-1).

### CODE REVIEW

**Review by millstein — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8678)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @anothermattbrown and @nickgian)

___
*[`projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/MutableBDDIntegerTest.java` line 96 at r1](https://reviewable.io/reviews/batfish/batfish/8678#-NQCk04QBE5_y9a0ysTi:-NQCk04QBE5_y9a0ysTj:b-axwem3) ([raw file](https://github.com/batfish/batfish/blob/e0c84f57cb32e2c643a246b2ccef594709df455f/projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/MutableBDDIntegerTest.java#L96)):*
> ```Java
>     assertTrue(x.value(0).equals(xPlus1.value(1))); // x == 0 <==> x+1 == 1
>     assertTrue(x.value(1).equals(xPlus1.value(2))); // x == 1 <==> x+1 == 2
>     assertTrue(x.value(31).imp(xPlus1.value(31)).equals(factory.one())); // x == 31 ==> x+1 == 31
> ```

I guess you could check the exact condition here, namely that x >= 30 <==> x+1 == 31, and similarly for the next test
___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java` line 177 at r1](https://reviewable.io/reviews/batfish/batfish/8678#-NQCkQ4s6AhfQIFmcYX_:-NQCkQ4s6AhfQIFmcYXa:b-9wp46c) ([raw file](https://github.com/batfish/batfish/blob/e0c84f57cb32e2c643a246b2ccef594709df455f/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java#L177)):*
> ```Java
>     } else {
>       throw new UnsupportedFeatureException(e.toString());
>     }
> ```

I would update the comment for this method to make clear that it has the clipping semantics.  Right now I think it's only used for SetMetric but in the future we may want to use it for other fields but need to make sure that the semantics is the same for overflow.
___
*[`projects/minesweeper/src/test/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesAnswererTest.java` line 1707 at r1](https://reviewable.io/reviews/batfish/batfish/8678#-NQCkusaCJCugU22SUTc:-NQCkusaCJCugU22SUTd:bdan1v3) ([raw file](https://github.com/batfish/batfish/blob/e0c84f57cb32e2c643a246b2ccef594709df455f/projects/minesweeper/src/test/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesAnswererTest.java#L1707)):*
> ```Java
>   @Test
>   public void testSetMetricIncr() {
>     RoutingPolicy policy =
> ```

I would have expected tests in TransferBDDTest rather than SRPTest, since SRP did not change.
___
*[`projects/minesweeper/src/test/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesAnswererTest.java` line 1770 at r1](https://reviewable.io/reviews/batfish/batfish/8678#-NQCl-UJ1cpkbbMzOwQ3:-NQCl-UJ1cpkbbMzOwQ4:b1ny4vg) ([raw file](https://github.com/batfish/batfish/blob/e0c84f57cb32e2c643a246b2ccef594709df455f/projects/minesweeper/src/test/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesAnswererTest.java#L1770)):*
> ```Java
>         _policyBuilder
>             .addStatement(new SetMetric(new IncrementMetric(0x80000000L)))
>             .addStatement(new StaticStatement(Statements.ExitAccept))
> ```

This test seems odd since it should not be legal to increment the metric by that much.  So really that should be rejected as part of the data model construction.  Probably better to use an example that represents a real overflow.

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8678)* status: all files reviewed, 4 unresolved discussions (waiting on @nickgian)

**Review by nickgian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8678)* status: all files reviewed, 4 unresolved discussions (waiting on @millstein)

___
*[`projects/minesweeper/src/test/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesAnswererTest.java` line 1707 at r1](https://reviewable.io/reviews/batfish/batfish/8678#-NQCkusaCJCugU22SUTc:-NQWWKXw9gQnUnWWSAZD:bfoo7rv) ([raw file](https://github.com/batfish/batfish/blob/e0c84f57cb32e2c643a246b2ccef594709df455f/projects/minesweeper/src/test/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesAnswererTest.java#L1707)):*
<details><summary><i>Previously, millstein (Todd Millstein) wrote…</i></summary><blockquote>

I would have expected tests in TransferBDDTest rather than SRPTest, since SRP did not change.
</blockquote></details>

The thing is, SRP allowed me to define constraints on input routes and check concrete values on the output.
It was not clear to me how to test this in TransferBDD, because I am not setting a concrete value.
If I were to write a unit-test in TransferBDD it would either:
1. require me to do much of the work that SRP does
2. require me to test that the result is changed via `addClipping` which seemed kind of useless in the sense that this is what the implementation already does.
___
*[`projects/minesweeper/src/test/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesAnswererTest.java` line 1770 at r1](https://reviewable.io/reviews/batfish/batfish/8678#-NQCl-UJ1cpkbbMzOwQ3:-NQWWIqeB_4oPosA-QSk:bt2vr1b) ([raw file](https://github.com/batfish/batfish/blob/e0c84f57cb32e2c643a246b2ccef594709df455f/projects/minesweeper/src/test/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesAnswererTest.java#L1770)):*
<details><summary><i>Previously, millstein (Todd Millstein) wrote…</i></summary><blockquote>

This test seems odd since it should not be legal to increment the metric by that much.  So really that should be rejected as part of the data model construction.  Probably better to use an example that represents a real overflow.
</blockquote></details>

Fixed.

**Review by nickgian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8678)* status: all files reviewed, 4 unresolved discussions (waiting on @millstein)

___
*[`projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/MutableBDDIntegerTest.java` line 96 at r1](https://reviewable.io/reviews/batfish/batfish/8678#-NQCk04QBE5_y9a0ysTi:-NQWXE8UCmsqV5bJ5imb:bt2vr1b) ([raw file](https://github.com/batfish/batfish/blob/e0c84f57cb32e2c643a246b2ccef594709df455f/projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/MutableBDDIntegerTest.java#L96)):*
<details><summary><i>Previously, millstein (Todd Millstein) wrote…</i></summary><blockquote>

I guess you could check the exact condition here, namely that x >= 30 <==> x+1 == 31, and similarly for the next test
</blockquote></details>

Fixed.
___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java` line 177 at r1](https://reviewable.io/reviews/batfish/batfish/8678#-NQCkQ4s6AhfQIFmcYX_:-NQWXAYkCCtshg-PkEBj:bt2vr1b) ([raw file](https://github.com/batfish/batfish/blob/e0c84f57cb32e2c643a246b2ccef594709df455f/projects/minesweeper/src/main/java/org/batfish/minesweeper/bdd/TransferBDD.java#L177)):*
<details><summary><i>Previously, millstein (Todd Millstein) wrote…</i></summary><blockquote>

I would update the comment for this method to make clear that it has the clipping semantics.  Right now I think it's only used for SetMetric but in the future we may want to use it for other fields but need to make sure that the semantics is the same for overflow.
</blockquote></details>

Fixed.

**Review by millstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8678)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @anothermattbrown and @nickgian)

___
*[`projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/MutableBDDIntegerTest.java` line 96 at r1](https://reviewable.io/reviews/batfish/batfish/8678#-NQCk04QBE5_y9a0ysTi:-NQXfp9GDqXF3GwPJ9VB:b-18roqt) ([raw file](https://github.com/batfish/batfish/blob/e0c84f57cb32e2c643a246b2ccef594709df455f/projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/MutableBDDIntegerTest.java#L96)):*
<details><summary><i>Previously, nickgian (Nick Giannarakis) wrote…</i></summary><blockquote>

Fixed.
</blockquote></details>

Couldn't it be the exact condition (if and only if, instead of just implication), i.e.:

x.geq(30).equals(xPlus1.value(31))

?

And similarly for the test below.
___
*[`projects/minesweeper/src/test/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesAnswererTest.java` line 1770 at r1](https://reviewable.io/reviews/batfish/batfish/8678#-NQCl-UJ1cpkbbMzOwQ3:-NQXgQ1JEmWdB2Ln413F:blj1ckr) ([raw file](https://github.com/batfish/batfish/blob/e0c84f57cb32e2c643a246b2ccef594709df455f/projects/minesweeper/src/test/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesAnswererTest.java#L1770)):*
<details><summary><i>Previously, nickgian (Nick Giannarakis) wrote…</i></summary><blockquote>

Fixed.
</blockquote></details>

I don't read hex but I'll take your word for it :)

**Comment by nickgian** [comment]
> 

Fixed for real now.

**Review by nickgian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8678)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @anothermattbrown and @millstein)

___
*[`projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/MutableBDDIntegerTest.java` line 96 at r1](https://reviewable.io/reviews/batfish/batfish/8678#-NQCk04QBE5_y9a0ysTi:-NQbmXBtDtFjM28o2gBM:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/e0c84f57cb32e2c643a246b2ccef594709df455f/projects/batfish-common-protocol/src/test/java/org/batfish/common/bdd/MutableBDDIntegerTest.java#L96)):*
<details><summary><i>Previously, millstein (Todd Millstein) wrote…</i></summary><blockquote>

Couldn't it be the exact condition (if and only if, instead of just implication), i.e.:

x.geq(30).equals(xPlus1.value(31))

?

And similarly for the test below.
</blockquote></details>

Done.
___
*[`projects/minesweeper/src/test/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesAnswererTest.java` line 1770 at r1](https://reviewable.io/reviews/batfish/batfish/8678#-NQCl-UJ1cpkbbMzOwQ3:-NQbmYIQ1jb8VsihOvVQ:br6rukx) ([raw file](https://github.com/batfish/batfish/blob/e0c84f57cb32e2c643a246b2ccef594709df455f/projects/minesweeper/src/test/java/org/batfish/minesweeper/question/searchroutepolicies/SearchRoutePoliciesAnswererTest.java#L1770)):*
<details><summary><i>Previously, millstein (Todd Millstein) wrote…</i></summary><blockquote>

I don't read hex but I'll take your word for it :)
</blockquote></details>

I used a calculator lol

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8678)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nickgian)

**Pull request merged**
