### PR TITLE
Case-insensitive matching for node names

### PR DESCRIPTION
**Pull request by millstein**
By default role inference and nodes specifiers use case-insensitive node-name matching.  For example, both border3 and BORDER5 will match the regex "border.*" by default.  There is a flag to make matching case-sensitive.

### CODE REVIEW

**Comment by dhalperi** [comment]
Review status: 8 of 30 files reviewed at latest revision, all discussions resolved.

---

*[test_rigs/example2-mixed-case/configs/bb1-border-01.cfg, line 3 at r1](https://reviewable.io/reviews/batfish/batfish/1553#-LDwa0RZ5FZcjY6TCsfM:-LDwa0RZ5FZcjY6TCsfN:b-17wuh7) ([raw file](https://github.com/batfish/batfish/blob/4adc27bed62c2d889ecd9c22c7c97884f9943e06/test_rigs/example2-mixed-case/configs/bb1-border-01.cfg#L3)):*
> ```INI
> 
> !
> version 15.2
> ```

I really don't want another copy of the example network in here if possible. Can we instead make a small interesting unit test?

Note that unit tests can be based off of configs; follow the testrigs variable linked here around that file for examples: https://github.com/batfish/batfish/blob/master/projects/batfish/src/test/java/org/batfish/grammar/cisco/CiscoGrammarTest.java#L168

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1553)*

**Comment by ratulm** [comment]
@millstein  - The way to accomplish what you want is to check in little config snippets of interest as part of the test. See, for instance, tests in CiscoGrammarTest.java. @arifogel should be able to help if it is unclear based on those example how to accomplish your testing goals.

**Comment by dhalperi** [comment]
I did some very minor refactoring to `InferRoles` to ease testing and then wrote a sample JUnit test in #1589 -- please take a look and let me know if that's helpful.

---







*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1553#-:-LEDWh5WDUiMBSv6A-aP:bxwv0l8)*

**Comment by ratulm** [comment]
:lgtm: Modulo the testing discussion.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1553#-:-LEDyuCi-V9hf0tgmBeK:b-sn6l5g)*

**Comment by millstein** [comment]
This isn't ready yet -- I still need to add a couple of new unit tests.

**Comment by dhalperi** [comment]
Use the "start a new discussion" button on reviewable and set the disposition to `Working`. This will actually prevent others from merging.


---







*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1553#-:-LELrwqeAZS0GG9fpJ2w:bp92kb9)*

**Comment by dhalperi** [comment]
*[a discussion](https://reviewable.io/reviews/batfish/batfish/1553#-LELsDy0C4dh1ChsHbBO:-LELs04y1b0Ga8dwGEW1:b-gejex0) (no related file):*
Working on unit tests.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1553)*

**Comment by arifogel** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1553)*

**Comment by arifogel** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1553#-:-LER2i4eCN91Ui45SHjY:bnfp4nl)*

**Pull request merged**
