### PR TITLE
RoutePolicyStatementMatchCollector: incorporate the BooleanExprMatchCollector

### PR DESCRIPTION
**Pull request by dhalperi**
The separation of the Statement walker and the BooleanExpr walker broke because
BooleanExpr can call policies, which have Statements. That meant that any
overrides in the StatementMatchCollector were lost when going through a call or
similar.

Unifying them actually leads to simpler code, and can still be used to just walk
BooleanExpr or RoutingPolicy.

Also, since they collect from Sets e.g., Community, drop the "Match" part.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/9068)* status: 0 of 22 files reviewed, all discussions resolved

___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/collectors/CommunityBooleanExprCollector.java` line 59 at r1](https://reviewable.io/reviews/batfish/batfish/9068#-NznmTcH-4nMWzRr9Cfx:-NznmTcH-4nMWzRr9Cfy:bcsjoxw) ([raw file](https://github.com/batfish/batfish/blob/605bd98abac24ccf496ee9b4755abb876e5340c1/projects/minesweeper/src/main/java/org/batfish/minesweeper/collectors/CommunityBooleanExprCollector.java#L59)):*
> ```Java
>             new RoutingPolicyStatementCommunityCollector()
>                 .visitAll(withEnvironmentExpr.getPostStatements(), arg))
>         .addAll(
> ```

FYI this was the problematic code. Every BooleanExprMatchCollector had to override these two functions, or the Statement handling would get lost through the Calls. So basically, the two classes were coupled. 

Moving them together simplifies the code all around, saves allocations, etc.



_Code quote:_
```Java
  public Set<String> visitCallExpr(CallExpr callExpr, Tuple<Set<String>, Configuration> arg) {
    if (arg.getFirst().contains(callExpr.getCalledPolicyName())) {
      // If we have already visited this policy then don't visit again
      return ImmutableSet.of();
    }
    // Otherwise update the set of seen policies and recurse.
    arg.getFirst().add(callExpr.getCalledPolicyName());

    return new RoutingPolicyStatementCommunityCollector()
        .visitAll(
            arg.getSecond()
                .getRoutingPolicies()
                .get(callExpr.getCalledPolicyName())
                .getStatements(),
            arg);
  }

  @Override
  public Set<String> visitWithEnvironmentExpr(
      WithEnvironmentExpr withEnvironmentExpr, Tuple<Set<String>, Configuration> arg) {
    return ImmutableSet.<String>builder()
        .addAll(withEnvironmentExpr.getExpr().accept(this, arg))
        .addAll(
            new RoutingPolicyStatementCommunityCollector()
                .visitAll(withEnvironmentExpr.getPreStatements(), arg))
        .addAll(
            new RoutingPolicyStatementCommunityCollector()
                .visitAll(withEnvironmentExpr.getPostStatements(), arg))
        .addAll(
```

**Review by millstein — COMMENTED** [review]
> Reviewed 21 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/9068)* status: 21 of 22 files reviewed, 5 unresolved discussions (waiting on @dhalperi)

___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/ConfigAtomicPredicates.java` line 215 at r1](https://reviewable.io/reviews/batfish/batfish/9068#-Nzs03if-gnQPPlVuxI1:-Nzs03if-gnQPPlVuxI2:b-lju54v) ([raw file](https://github.com/batfish/batfish/blob/ef54f1dcb83b47928517b32a30a18972a26867dd/projects/minesweeper/src/main/java/org/batfish/minesweeper/ConfigAtomicPredicates.java#L215)):*
> ```Java
>    * {@link BooleanExprVisitor} is provided that is specific to the particular items being searched
>    * for. An optional set of additional items is also included, which is used to support
>    * user-specified constraints for symbolic analysis.
> ```

This comment should be updated.
___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/aspath/RoutingPolicyCollector.java` line 443 at r1](https://reviewable.io/reviews/batfish/batfish/9068#-Nzs1Kvz3Bod-GYp4Dgh:-Nzs1Kvz3Bod-GYp4Dgi:baho6z1) ([raw file](https://github.com/batfish/batfish/blob/ef54f1dcb83b47928517b32a30a18972a26867dd/projects/minesweeper/src/main/java/org/batfish/minesweeper/aspath/RoutingPolicyCollector.java#L443)):*
> ```Java
>    * A helper function to visit all elements of a list of boolean expressions.
>    *
>    * @param visitor the specific BooleanExprMatchCollector visitor to use
> ```

update comment
___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/collectors/RoutingPolicyStatementRouteFilterCollector.java` line 16 at r1](https://reviewable.io/reviews/batfish/batfish/9068#-Nzs2h6v-fia-WYibRmV:-Nzs2h6v-fia-WYibRmW:b-u1b1r3) ([raw file](https://github.com/batfish/batfish/blob/ef54f1dcb83b47928517b32a30a18972a26867dd/projects/minesweeper/src/main/java/org/batfish/minesweeper/collectors/RoutingPolicyStatementRouteFilterCollector.java#L16)):*
> ```Java
> /** Collect all prefix-list names in a route-policy {@link Statement}. */
> @ParametersAreNonnullByDefault
> public class RoutingPolicyStatementRouteFilterCollector extends RoutingPolicyCollector<String> {
> ```

The class name talks about route filters but we're collecting prefix lists - seems confusing (though that's not a new change in this PR).
___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/collectors/RoutingPolicyStatementRouteFilterCollector.java` line 26 at r1](https://reviewable.io/reviews/batfish/batfish/9068#-Nzs4LLv9_uhpNJ9Z2OE:-Nzs4LLv9_uhpNJ9Z2OF:b-jvm9n) ([raw file](https://github.com/batfish/batfish/blob/ef54f1dcb83b47928517b32a30a18972a26867dd/projects/minesweeper/src/main/java/org/batfish/minesweeper/collectors/RoutingPolicyStatementRouteFilterCollector.java#L26)):*
> ```Java
> 
>   @Override
>   public Set<String> visitMatchPrefixSet(
> ```

Unclear how the old version ever did anything useful, without this method (and the one above) being overridden?
___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/aspath/AsPathRegexCollector.java` line 19 at r1](https://reviewable.io/reviews/batfish/batfish/9068#-Nzs1drA7FvOJgHLDkKG:-Nzs1drA7FvOJgHLDkKH:baho6z1) ([raw file](https://github.com/batfish/batfish/blob/ef54f1dcb83b47928517b32a30a18972a26867dd/projects/minesweeper/src/main/java/org/batfish/minesweeper/aspath/AsPathRegexCollector.java#L19)):*
> ```Java
> import org.batfish.minesweeper.utils.Tuple;
> 
> /** Collect all AS-path regexes in a {@link BooleanExpr}. */
> ```

update comment

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/9068)* status: 14 of 24 files reviewed, 5 unresolved discussions (waiting on @millstein)

___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/ConfigAtomicPredicates.java` line 215 at r1](https://reviewable.io/reviews/batfish/batfish/9068#-Nzs03if-gnQPPlVuxI1:-O-HKNdO5z_AGSsxZM3G:buamsu9) ([raw file](https://github.com/batfish/batfish/blob/fc4c2a892a8c52034209abe9edcd783694d85666/projects/minesweeper/src/main/java/org/batfish/minesweeper/ConfigAtomicPredicates.java#L215)):*
<details><summary><i>Previously, millstein (Todd Millstein) wrote…</i></summary><blockquote>

This comment should be updated.
</blockquote></details>

Done. Also renamed some more collectors that still had BooleanExpr in the name.
___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/aspath/RoutingPolicyCollector.java` line 443 at r1](https://reviewable.io/reviews/batfish/batfish/9068#-Nzs1Kvz3Bod-GYp4Dgh:-O-HL8TyByX1xuSP9VFJ:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/fc4c2a892a8c52034209abe9edcd783694d85666/projects/minesweeper/src/main/java/org/batfish/minesweeper/aspath/RoutingPolicyCollector.java#L443)):*
<details><summary><i>Previously, millstein (Todd Millstein) wrote…</i></summary><blockquote>

update comment
</blockquote></details>

Done.
___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/aspath/AsPathRegexCollector.java` line 19 at r1](https://reviewable.io/reviews/batfish/batfish/9068#-Nzs1drA7FvOJgHLDkKG:-O-HKVQh-bC_eXUnkSqB:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/fc4c2a892a8c52034209abe9edcd783694d85666/projects/minesweeper/src/main/java/org/batfish/minesweeper/aspath/AsPathRegexCollector.java#L19)):*
<details><summary><i>Previously, millstein (Todd Millstein) wrote…</i></summary><blockquote>

update comment
</blockquote></details>

Done.
___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/collectors/RoutingPolicyStatementRouteFilterCollector.java` line 16 at r1](https://reviewable.io/reviews/batfish/batfish/9068#-Nzs2h6v-fia-WYibRmV:-O-HMqny1r5TRNOnEpbW:ba3o3s1) ([raw file](https://github.com/batfish/batfish/blob/fc4c2a892a8c52034209abe9edcd783694d85666/projects/minesweeper/src/main/java/org/batfish/minesweeper/collectors/RoutingPolicyStatementRouteFilterCollector.java#L16)):*
<details><summary><i>Previously, millstein (Todd Millstein) wrote…</i></summary><blockquote>

The class name talks about route filters but we're collecting prefix lists - seems confusing (though that's not a new change in this PR).
</blockquote></details>

Renamed
___
*[`projects/minesweeper/src/main/java/org/batfish/minesweeper/collectors/RoutingPolicyStatementRouteFilterCollector.java` line 26 at r1](https://reviewable.io/reviews/batfish/batfish/9068#-Nzs4LLv9_uhpNJ9Z2OE:-O-HNHfSDiMWIh_VYcA0:b-80qohe) ([raw file](https://github.com/batfish/batfish/blob/fc4c2a892a8c52034209abe9edcd783694d85666/projects/minesweeper/src/main/java/org/batfish/minesweeper/collectors/RoutingPolicyStatementRouteFilterCollector.java#L26)):*
<details><summary><i>Previously, millstein (Todd Millstein) wrote…</i></summary><blockquote>

Unclear how the old version ever did anything useful, without this method (and the one above) being overridden?
</blockquote></details>

Whether or not it worked depended on the policy structure. It was actually kind of hard to create a test case that triggered it, because you had to go in and out of boolean exprs and statements -- which is why we hadn't noticed, probably.

**Review by millstein — COMMENTED** [review]
> Reviewed 1 of 22 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/9068)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dhalperi)

**Review by millstein — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/9068#-:-O-l6yxr7ZRgerAVo-zC:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dhalperi)

**Pull request merged**
