### PR TITLE
Use RFC 3339 format for timestamp

### PR DESCRIPTION
**Pull request by corinaminer**
Updated timestamp to use RFC 3339's accepted timestamp format (see [RFC 3339 sections 5.6, 5.8](https://tools.ietf.org/html/rfc3339); example: `1985-04-12T23:20:50.52Z`). Also renamed the `timestamp` property in the metadata to `creationTimestamp`.

---
This change is [Reviewable](https://reviewable.io/reviews/batfish/batfish/669)

### CODE REVIEW

**Comment by dhalperi** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, line 800 at r1](https://reviewable.io:443/reviews/batfish/batfish/669#-KyxPuiodxNOwt7UNhGO:-KyxPuiodxNOwt7UNhGP:b-q0lbcv) ([raw file](https://github.com/batfish/batfish/blob/4611a46bd3c3e6b6ba52370eb2084aafa0d4073d/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java#L800)):*
> ```Java
>     // Create metadata file (RELPATH_METADATA_FILE is "metadata.json")
>     Path metadataPath = testrigDir.resolve(BfConsts.RELPATH_METADATA_FILE);
>     CommonUtil.writeFile(
> ```

Here's my general tips for making this more future-proof: a) don't construct JSON strings manually and b) let the mapping libraries to the serialization work in a general way. Here's what I'd do:

1. Please create a class `TestrigMetadata` intended for use in Jackson serialization/deserialization. I guess right now it just has a `creationTimestamp` field of time java.time.Instant

2. Update `BatfishObjectMapper` (henceforth, "BOM") to disable serializing date-types as timestamps:     disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);

3. Add a test of BOM that verifies that some fixed date serializes in the RFC format (say your birthday, I don't care as long as all the fields are interesting).

4. Update this to use BOM.writeValueAsString on the metadata class.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/669)*

**Comment by dhalperi** [comment]
*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, line 800 at r1](https://reviewable.io:443/reviews/batfish/batfish/669#-KyxPuiodxNOwt7UNhGO:-KyxQlO0aCn5_gu7bDog:bzcise8) ([raw file](https://github.com/batfish/batfish/blob/4611a46bd3c3e6b6ba52370eb2084aafa0d4073d/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java#L800)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Here's my general tips for making this more future-proof: a) don't construct JSON strings manually and b) let the mapping libraries to the serialization work in a general way. Here's what I'd do:

1. Please create a class `TestrigMetadata` intended for use in Jackson serialization/deserialization. I guess right now it just has a `creationTimestamp` field of time java.time.Instant

2. Update `BatfishObjectMapper` (henceforth, "BOM") to disable serializing date-types as timestamps:     disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);

3. Add a test of BOM that verifies that some fixed date serializes in the RFC format (say your birthday, I don't care as long as all the fields are interesting).

4. Update this to use BOM.writeValueAsString on the metadata class.
</blockquote></details>

May also need to add and/or register the Java8 jackson library, which adds knowledge to Jackson that java.time.Instant (new in Java8) is a date-like class. https://github.com/FasterXML/jackson-modules-java8/tree/master/datetime

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/669)*

**Comment by dhalperi** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/669)*

**Comment by dhalperi** [comment]
Reviewed 6 of 6 files at r2.
Review status: 4 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/TestrigMetadata.java, line 8 at r2](https://reviewable.io:443/reviews/batfish/batfish/669#-L-3Sr8QrJrTiTq4_EoL:-L-3Sr8RybZquHENkrpe:b-42w4hi) ([raw file](https://github.com/batfish/batfish/blob/385cd4a9827c5246f06ff61eeb767bac23d5697e/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/TestrigMetadata.java#L8)):*
> ```Java
> public class TestrigMetadata {
>   private static final String PROP_CREATIONTIMESTAMP = "creationTimestamp";
>   private java.time.Instant _creationTimestamp;
> ```

just `import java.time.Instant;` and use `Instant` here. Unless there's some reason not to that I'm missing.

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/TestrigMetadataTest.java, line 22 at r2](https://reviewable.io:443/reviews/batfish/batfish/669#-L-3T6H2Kfy-7bBceo6A:-L-3T6H2Kfy-7bBceo6B:btdqxy9) ([raw file](https://github.com/batfish/batfish/blob/385cd4a9827c5246f06ff61eeb767bac23d5697e/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/TestrigMetadataTest.java#L22)):*
> ```Java
>           equalTo("{\n  \"creationTimestamp\" : \"1994-01-19T03:10:05.001Z\"\n}"));
>     } catch (Exception e) {
>       assertThat(e.getMessage(), 0, equalTo(1));
> ```

just add `throws Exception` to the function definition and drop the `try/catch`.

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, line 801 at r2](https://reviewable.io:443/reviews/batfish/batfish/669#-L-3aSAWrz59NmWEUPdB:-L-3aSAWrz59NmWEUPdC:b-bire30) ([raw file](https://github.com/batfish/batfish/blob/385cd4a9827c5246f06ff61eeb767bac23d5697e/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java#L801)):*
> ```Java
>     // Create metadata file (RELPATH_METADATA_FILE is "metadata.json")
>     BatfishObjectMapper mapper = new BatfishObjectMapper();
>     TestrigMetadata metadata = new TestrigMetadata(java.time.Instant.now());
> ```

same comment about `Instant` here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/669)*

**Comment by dhalperi** [comment]
Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/669)*

**Comment by corinaminer** [comment]
Review status: 2 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/TestrigMetadata.java, line 8 at r2](https://reviewable.io:443/reviews/batfish/batfish/669#-L-3Sr8QrJrTiTq4_EoL:-L-3f0ffcMbwGdffof-E:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/385cd4a9827c5246f06ff61eeb767bac23d5697e/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/TestrigMetadata.java#L8)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

just `import java.time.Instant;` and use `Instant` here. Unless there's some reason not to that I'm missing.
</blockquote></details>

Done.

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/TestrigMetadataTest.java, line 22 at r2](https://reviewable.io:443/reviews/batfish/batfish/669#-L-3T6H2Kfy-7bBceo6A:-L-3f1yieR7FreyW3gAC:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/385cd4a9827c5246f06ff61eeb767bac23d5697e/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/TestrigMetadataTest.java#L22)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

just add `throws Exception` to the function definition and drop the `try/catch`.
</blockquote></details>

Done.

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, line 801 at r2](https://reviewable.io:443/reviews/batfish/batfish/669#-L-3aSAWrz59NmWEUPdB:-L-3fPkNB3IbF2hNqQQc:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/385cd4a9827c5246f06ff61eeb767bac23d5697e/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java#L801)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

same comment about `Instant` here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/669)*

**Comment by dhalperi** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/669#-:-L-3kHFm_aVhiyhTOVOo:bnfp4nl)*

**Pull request merged**
