### PR TITLE
PAN: convert rules only once

### PR DESCRIPTION
**Pull request by sfraint**
Instead of converting rules each time they're used (e.g. multiple times for rules associated with many zones), just convert once before using them in `vsys` or `interface` conversion.

Follow-up to https://github.com/batfish/batfish/pull/6296

### CODE REVIEW

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6315)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @arifogel, @corinaminer, and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6315#-MJ_3XjGCEQJ0H3fKMqW:-MJ_3XjGCEQJ0H3fKMqX:bcxyk11) (no related file):*
after https://github.com/batfish/batfish/pull/6314

---

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6315)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @arifogel and @corinaminer)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6315#-MJ_3XjGCEQJ0H3fKMqW:-MJc01R-5hqkhrKtRNHb:b-48orpe) (no related file):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

after https://github.com/batfish/batfish/pull/6314
</blockquote></details>

ok, that is merged

---

**Review by corinaminer — COMMENTED** [review]
> Reviewed 3 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6315)* status: all files reviewed, 5 unresolved discussions (waiting on @arifogel and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6315#-MJdt-HT5JbGd3x6aimk:-MJdt-HT5JbGd3x6aiml:b-8x5laf) (no related file):*
Would be nice if we could proactively prevent `toIpAccessListLine` and `convertRuleToTransformation` from being called anywhere else in the future. Could at least add in their javadocs that they should only be used by your new conversion methods.

---
___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java, line 545 at r2](https://reviewable.io/reviews/batfish/batfish/6315#-MJdr_gP-IANPZ2ZGrgR:-MJdr_gP-IANPZ2ZGrgS:b913v27) ([raw file](https://github.com/batfish/batfish/blob/7adeae7ea91d056cb2f5a2f5e73d80e5d6a98a50/projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java#L545)):*
> ```Java
>     Transformation transformation =
>         _natRuleToTransformation.getOrDefault(vsysName, ImmutableMap.of()).get(ruleName);
>     return transformation == null ? Optional.empty() : Optional.of(transformation);
> ```

can simplify to `Optional.ofNullable(transformation)`
___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java, line 567 at r2](https://reviewable.io/reviews/batfish/batfish/6315#-MJdqYBTCSFsUtvj7ySV:-MJdqYBTCSFsUtvj7ySW:b-3u8td2) ([raw file](https://github.com/batfish/batfish/blob/7adeae7ea91d056cb2f5a2f5e73d80e5d6a98a50/projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java#L567)):*
> ```Java
>       ruleToExprAclLine.putAll(panoramaRules);
>       ruleToExprAclLine.putAll(vsysRules);
>       vsysToRuleToExprAclLine.put(vsysName, ruleToExprAclLine);
> ```

better if these maps are immutable. you may want to use `ImmutableMap.copyOf` just in case there's name overlap between `panoramaRules` and `vsysRules` (immutable map builders don't let you `put` conflicting keys).

Same comments about the similar NAT rules method.
___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java, line 570 at r2](https://reviewable.io/reviews/batfish/batfish/6315#-MJdqTHK1FmZXEPZiAy-:-MJdqTHL9AmOhOHMSqdJ:b-kvjkqc) ([raw file](https://github.com/batfish/batfish/blob/7adeae7ea91d056cb2f5a2f5e73d80e5d6a98a50/projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java#L570)):*
> ```Java
>     }
> 
>     return vsysToRuleToExprAclLine;
> ```

i think this one can be an `ImmutableMap.Builder` from the start
___
*[projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java, line 2275 at r2](https://reviewable.io/reviews/batfish/batfish/6315#-MJdtbH9DoxzQCrY3Jk5:-MJdtbH9DoxzQCrY3Jk6:b-3hlk9g) ([raw file](https://github.com/batfish/batfish/blob/7adeae7ea91d056cb2f5a2f5e73d80e5d6a98a50/projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java#L2275)):*
> ```Java
> 
>     // Should have a warning about invalid ip ranges and empty translation pool
>     // Confirm we have only one warning for each, *no duplicates*
> ```

Did the test config produce duplicate warnings before your change? i'm guessing that's why you have two interfaces in the config. If so, please comment in the config that both are present intentionally, so no one decides they can "clean it up" later

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6315)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @arifogel and @corinaminer)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/6315#-MJdt-HT5JbGd3x6aimk:-MJiYYccDWhi8oe5ZaAF:b-8dsn0t) (no related file):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Would be nice if we could proactively prevent `toIpAccessListLine` and `convertRuleToTransformation` from being called anywhere else in the future. Could at least add in their javadocs that they should only be used by your new conversion methods.
</blockquote></details>

updated docstrings for now

---
___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java, line 545 at r2](https://reviewable.io/reviews/batfish/batfish/6315#-MJdr_gP-IANPZ2ZGrgR:-MJh4t7mES4WDDolKYU-:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/7adeae7ea91d056cb2f5a2f5e73d80e5d6a98a50/projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java#L545)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

can simplify to `Optional.ofNullable(transformation)`
</blockquote></details>

done
___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java, line 567 at r2](https://reviewable.io/reviews/batfish/batfish/6315#-MJdqYBTCSFsUtvj7ySV:-MJiXQQ-A-Y7Telgovpp:bb7h17b) ([raw file](https://github.com/batfish/batfish/blob/7adeae7ea91d056cb2f5a2f5e73d80e5d6a98a50/projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java#L567)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

better if these maps are immutable. you may want to use `ImmutableMap.copyOf` just in case there's name overlap between `panoramaRules` and `vsysRules` (immutable map builders don't let you `put` conflicting keys).

Same comments about the similar NAT rules method.
</blockquote></details>

updated to use immutable maps in a few places
___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java, line 570 at r2](https://reviewable.io/reviews/batfish/batfish/6315#-MJdqTHK1FmZXEPZiAy-:-MJiXToUAVK1w04CVYrJ:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/7adeae7ea91d056cb2f5a2f5e73d80e5d6a98a50/projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java#L570)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

i think this one can be an `ImmutableMap.Builder` from the start
</blockquote></details>

done
___
*[projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java, line 2275 at r2](https://reviewable.io/reviews/batfish/batfish/6315#-MJdtbH9DoxzQCrY3Jk5:-MJh7q2L-JVVmX8GMZwq:b-w0ay2v) ([raw file](https://github.com/batfish/batfish/blob/7adeae7ea91d056cb2f5a2f5e73d80e5d6a98a50/projects/batfish/src/test/java/org/batfish/grammar/palo_alto/PaloAltoGrammarTest.java#L2275)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Did the test config produce duplicate warnings before your change? i'm guessing that's why you have two interfaces in the config. If so, please comment in the config that both are present intentionally, so no one decides they can "clean it up" later
</blockquote></details>

Yep we had duplicate warnings before; added comments in the config about the ifaces/zones.

**Review by corinaminer — COMMENTED** [review]
:lgtm: after that last `ImmutableMap`.

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6315#-:-MJj7Jvu1eFAEjwxxvLX:be7llhg)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java, line 521 at r3](https://reviewable.io/reviews/batfish/batfish/6315#-MJj5z0h9Ie8kXjZ88Dq:-MJj5z0i5wCJQBuOfSF9:bto7bqy) ([raw file](https://github.com/batfish/batfish/blob/09dddc900ce9e6fcd16521fa1c597943f666ad2c/projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java#L521)):*
> ```Java
>       ruleToTransformation.putAll(panoramaTransformations);
>       ruleToTransformation.putAll(vsysTransformations);
>       vsysToRuleToTransformation.put(vsysName, ruleToTransformation);
> ```

`ImmutableMap.copyOf(ruleToTransformation)`
___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java, line 555 at r3](https://reviewable.io/reviews/batfish/batfish/6315#-MJj6mfk63SJRkFdughW:-MJj6mfk63SJRkFdughX:buvh43b) ([raw file](https://github.com/batfish/batfish/blob/09dddc900ce9e6fcd16521fa1c597943f666ad2c/projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java#L555)):*
> ```Java
>       String name = entry.getKey();
>       NatRule rule = entry.getValue();
>       if (!rule.getDisabled() && !ruleToHeaderSpaceBoolExprs.containsKey(name)) {
> ```

Going to leave it optional, but it just occurred to me that we might want to file warnings if we do find rules with duplicate names... no need if you're sure there can't be duplicate names, though

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6315)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java, line 521 at r3](https://reviewable.io/reviews/batfish/batfish/6315#-MJj5z0h9Ie8kXjZ88Dq:-MJmUQb618Z1zkLIv5YB:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/09dddc900ce9e6fcd16521fa1c597943f666ad2c/projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java#L521)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

`ImmutableMap.copyOf(ruleToTransformation)`
</blockquote></details>

done
___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java, line 555 at r3](https://reviewable.io/reviews/batfish/batfish/6315#-MJj6mfk63SJRkFdughW:-MJmU6Gs9AhHKj4qva8h:b-fwo56b) ([raw file](https://github.com/batfish/batfish/blob/09dddc900ce9e6fcd16521fa1c597943f666ad2c/projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java#L555)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Going to leave it optional, but it just occurred to me that we might want to file warnings if we do find rules with duplicate names... no need if you're sure there can't be duplicate names, though
</blockquote></details>

Users can definitely supply invalid configs with duplicate rule names. Though, I'd like to wrap up these changes and maybe just add that later, with some more tests.

**Review by corinaminer — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6315)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java, line 555 at r3](https://reviewable.io/reviews/batfish/batfish/6315#-MJj6mfk63SJRkFdughW:-MJmbtlS9h5jIh2rllza:bp7vbga) ([raw file](https://github.com/batfish/batfish/blob/09dddc900ce9e6fcd16521fa1c597943f666ad2c/projects/batfish/src/main/java/org/batfish/representation/palo_alto/PaloAltoConfiguration.java#L555)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

Users can definitely supply invalid configs with duplicate rule names. Though, I'd like to wrap up these changes and maybe just add that later, with some more tests.
</blockquote></details>

sounds good.

**Pull request merged**
