### PR TITLE
Save declared interface names

### PR DESCRIPTION
**Pull request by arifogel**
This change is [Reviewable](https://reviewable.io/reviews/batfish/batfish/821)

### CODE REVIEW

**Comment by dhalperi** [comment]
Makes sense!

---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/InterfaceMatchers.java, line 13 at r1](https://reviewable.io:443/reviews/batfish/batfish/821#-L28Egh4evI8wLwiI_2q:-L28Egh4evI8wLwiI_2r:b-so686) ([raw file](https://github.com/batfish/batfish/blob/ca65dd3a680bb8eebaaa1a9c4870f4e1ed935d1c/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/InterfaceMatchers.java#L13)):*
> ```Java
> import org.hamcrest.Matcher;
> 
> public final class InterfaceMatchers {
> ```

Since this is intended as a public utility method, add Javadoc to the class and to the public functions?

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/InterfaceMatchers.java, line 14 at r1](https://reviewable.io:443/reviews/batfish/batfish/821#-L28Em7tAIjUEHD8OnXq:-L28Em7tAIjUEHD8OnXr:bx0eu88) ([raw file](https://github.com/batfish/batfish/blob/ca65dd3a680bb8eebaaa1a9c4870f4e1ed935d1c/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/InterfaceMatchers.java#L14)):*
> ```Java
> 
> public final class InterfaceMatchers {
>   private static final class HasDeclaredNames extends FeatureMatcher<Interface, Set<String>> {
> ```

For readability, put the public methods before the private ones?

Actually, perhaps separate out `HasDeclaredNames` and `IsActive`, etc., into package-private classes with separate tests, and then this class need only contain the public static utility methods.

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/InterfaceMatchers.java, line 14 at r1](https://reviewable.io:443/reviews/batfish/batfish/821#-L28F269A3k3jRxzSont:-L28F269A3k3jRxzSonu:b-knkos8) ([raw file](https://github.com/batfish/batfish/blob/ca65dd3a680bb8eebaaa1a9c4870f4e1ed935d1c/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/InterfaceMatchers.java#L14)):*
> ```Java
> 
> public final class InterfaceMatchers {
>   private static final class HasDeclaredNames extends FeatureMatcher<Interface, Set<String>> {
> ```

Must this be a `Set<String>` rather than an `Iterable<String>`? Seems more general if so.

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/InterfaceMatchers.java, line 25 at r1](https://reviewable.io:443/reviews/batfish/batfish/821#-L28F_YBZVDu7SMKq7Wg:-L28F_YBZVDu7SMKq7Wh:b-edxz7c) ([raw file](https://github.com/batfish/batfish/blob/ca65dd3a680bb8eebaaa1a9c4870f4e1ed935d1c/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/InterfaceMatchers.java#L25)):*
> ```Java
>   }
> 
>   private static final class HasSourceNats extends FeatureMatcher<Interface, List<SourceNat>> {
> ```

Iterable?

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 141 at r1](https://reviewable.io:443/reviews/batfish/batfish/821#-L28G1HuMKOJZxcthrj4:-L28G1HuMKOJZxcthrj5:b-s0v11) ([raw file](https://github.com/batfish/batfish/blob/ca65dd3a680bb8eebaaa1a9c4870f4e1ed935d1c/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L141)):*
> ```Java
>   private static final int VLAN_NORMAL_MIN_CISCO = 2;
> 
>   private static synchronized Map<String, String> getCiscoInterfacePrefixes() {
> ```

Drop synchronization?

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 143 at r1](https://reviewable.io:443/reviews/batfish/batfish/821#-L28G3-7LMKYwXhbEUhf:-L28G3-7LMKYwXhbEUhg:bhfboe3) ([raw file](https://github.com/batfish/batfish/blob/ca65dd3a680bb8eebaaa1a9c4870f4e1ed935d1c/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L143)):*
> ```Java
>   private static synchronized Map<String, String> getCiscoInterfacePrefixes() {
>     /*
>      * Entries are sorted by priority. Do not reorder unless you have a good reason.
> ```

Maybe add documentation for what priority means here? FWICT it's really-almost-alphabetical with like 3 exceptions. Could not figure out why without reading other code :).

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 144 at r1](https://reviewable.io:443/reviews/batfish/batfish/821#-L28GnefXrz9dQLTr7ee:-L28GnegGENwYlE1h2SN:biqmeuk) ([raw file](https://github.com/batfish/batfish/blob/ca65dd3a680bb8eebaaa1a9c4870f4e1ed935d1c/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L144)):*
> ```Java
>     /*
>      * Entries are sorted by priority. Do not reorder unless you have a good reason.
>      */
> ```

We should have tests of priority with equivalence classes.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 145 at r1](https://reviewable.io:443/reviews/batfish/batfish/821#-L28Fx4vYkP4NGQz82Bj:-L28Fx4vYkP4NGQz82Bk:b98pop2) ([raw file](https://github.com/batfish/batfish/blob/ca65dd3a680bb8eebaaa1a9c4870f4e1ed935d1c/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L145)):*
> ```Java
>      * Entries are sorted by priority. Do not reorder unless you have a good reason.
>      */
>     return ImmutableMap.<String, String>builder()
> ```

Just make this a private static final Map<String, String> and return it?

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/Interface.java, line 182 at r1](https://reviewable.io:443/reviews/batfish/batfish/821#-L28GKjDYaQejhxWbjyN:-L28GKjDYaQejhxWbjyO:byqmu5x) ([raw file](https://github.com/batfish/batfish/blob/ca65dd3a680bb8eebaaa1a9c4870f4e1ed935d1c/projects/batfish/src/main/java/org/batfish/representation/cisco/Interface.java#L182)):*
> ```Java
>   private String _vrf;
> 
>   private Set<String> _declaredNames;
> ```

Need it be sorted?

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/Interface.java, line 542 at r1](https://reviewable.io:443/reviews/batfish/batfish/821#-L28GG_8o0-evTDRjJlA:-L28GG_8o0-evTDRjJlB:b-440kwn) ([raw file](https://github.com/batfish/batfish/blob/ca65dd3a680bb8eebaaa1a9c4870f4e1ed935d1c/projects/batfish/src/main/java/org/batfish/representation/cisco/Interface.java#L542)):*
> ```Java
> 
>   public void setDeclaredNames(Set<String> declaredNames) {
>     _declaredNames = declaredNames;
> ```

ImmutableSet.copyOf()?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/821#-:-L28GuawvZkh8MpsM7Lr:b-dxcbu5)*

**Comment by arifogel** [comment]
*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/InterfaceMatchers.java, line 14 at r1](https://reviewable.io:443/reviews/batfish/batfish/821#-L28F269A3k3jRxzSont:-L2LvYT_whzWg4hj808m:b-ib3npg) ([raw file](https://github.com/batfish/batfish/blob/ca65dd3a680bb8eebaaa1a9c4870f4e1ed935d1c/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/InterfaceMatchers.java#L14)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Must this be a `Set<String>` rather than an `Iterable<String>`? Seems more general if so.
</blockquote></details>

Actually that would make it less general. The ancestors of `Set` are more numerous than the ancestors of `Iterable`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/821)*

**Comment by arifogel** [comment]
*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/InterfaceMatchers.java, line 14 at r1](https://reviewable.io:443/reviews/batfish/batfish/821#-L28F269A3k3jRxzSont:-L2MTiVZL4uXzC2f5FA-:b-2oqy6l) ([raw file](https://github.com/batfish/batfish/blob/ca65dd3a680bb8eebaaa1a9c4870f4e1ed935d1c/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/InterfaceMatchers.java#L14)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Actually that would make it less general. The ancestors of `Set` are more numerous than the ancestors of `Iterable`.
</blockquote></details>

FYI I assume you were referring to the `subMatcher` parameter in the `HasDeclaredNames` constructor.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/821)*

**Comment by arifogel** [comment]
Review status: 8 of 15 files reviewed at latest revision, 8 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 141 at r1](https://reviewable.io:443/reviews/batfish/batfish/821#-L28G1HuMKOJZxcthrj4:-L2MiDwES4z3urxM-zHX:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/ca65dd3a680bb8eebaaa1a9c4870f4e1ed935d1c/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L141)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Drop synchronization?
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 143 at r1](https://reviewable.io:443/reviews/batfish/batfish/821#-L28G3-7LMKYwXhbEUhf:-L2MiEjT9LL5dCNooDZD:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/ca65dd3a680bb8eebaaa1a9c4870f4e1ed935d1c/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L143)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Maybe add documentation for what priority means here? FWICT it's really-almost-alphabetical with like 3 exceptions. Could not figure out why without reading other code :).
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 144 at r1](https://reviewable.io:443/reviews/batfish/batfish/821#-L28GnefXrz9dQLTr7ee:-L2MiFKqOiA601LBOfr_:b-wsawsu) ([raw file](https://github.com/batfish/batfish/blob/ca65dd3a680bb8eebaaa1a9c4870f4e1ed935d1c/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L144)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

We should have tests of priority with equivalence classes.
</blockquote></details>

We kind of have that with refs. I can add junit tests if you want.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java, line 145 at r1](https://reviewable.io:443/reviews/batfish/batfish/821#-L28Fx4vYkP4NGQz82Bj:-L2MiMakGOwA8DV63Nk5:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/ca65dd3a680bb8eebaaa1a9c4870f4e1ed935d1c/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L145)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Just make this a private static final Map<String, String> and return it?
</blockquote></details>

Done.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/Interface.java, line 182 at r1](https://reviewable.io:443/reviews/batfish/batfish/821#-L28GKjDYaQejhxWbjyN:-L2MiNHlk5uFFBPi2VT3:bt0u9dg) ([raw file](https://github.com/batfish/batfish/blob/ca65dd3a680bb8eebaaa1a9c4870f4e1ed935d1c/projects/batfish/src/main/java/org/batfish/representation/cisco/Interface.java#L182)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Need it be sorted?
</blockquote></details>

More expensive when building, but probably not noticeably; in practice there will almost always be just one declared name.
Done.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/Interface.java, line 542 at r1](https://reviewable.io:443/reviews/batfish/batfish/821#-L28GG_8o0-evTDRjJlA:-L2MiZPkP4XaolJId8v9:bb6un1j) ([raw file](https://github.com/batfish/batfish/blob/ca65dd3a680bb8eebaaa1a9c4870f4e1ed935d1c/projects/batfish/src/main/java/org/batfish/representation/cisco/Interface.java#L542)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

ImmutableSet.copyOf()?
</blockquote></details>

Done

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/InterfaceMatchers.java, line 13 at r1](https://reviewable.io:443/reviews/batfish/batfish/821#-L28Egh4evI8wLwiI_2q:-L2MiwVaSujO1sWfTHkg:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/ca65dd3a680bb8eebaaa1a9c4870f4e1ed935d1c/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/InterfaceMatchers.java#L13)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Since this is intended as a public utility method, add Javadoc to the class and to the public functions?
</blockquote></details>

Done.

---

*[projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/InterfaceMatchers.java, line 14 at r1](https://reviewable.io:443/reviews/batfish/batfish/821#-L28Em7tAIjUEHD8OnXq:-L2MixNbpPCrGRx-Ge_J:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/ca65dd3a680bb8eebaaa1a9c4870f4e1ed935d1c/projects/batfish-common-protocol/src/test/java/org/batfish/datamodel/InterfaceMatchers.java#L14)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

For readability, put the public methods before the private ones?

Actually, perhaps separate out `HasDeclaredNames` and `IsActive`, etc., into package-private classes with separate tests, and then this class need only contain the public static utility methods.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/821)*

**Comment by arifogel** [comment]
Review status: 8 of 15 files reviewed at latest revision, 8 unresolved discussions.

---

*[projects/batfish/src/main/java/org/batfish/representation/cisco/Interface.java, line 542 at r1](https://reviewable.io:443/reviews/batfish/batfish/821#-L28GG_8o0-evTDRjJlA:-L2Mj3l6JvB2_Yzu40xD:b3ecd8x) ([raw file](https://github.com/batfish/batfish/blob/ca65dd3a680bb8eebaaa1a9c4870f4e1ed935d1c/projects/batfish/src/main/java/org/batfish/representation/cisco/Interface.java#L542)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Oh I did it for data model class. Now it's done for this one too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/821)*

**Comment by arifogel** [comment]
*[a discussion](https://reviewable.io:443/reviews/batfish/batfish/821#-L2MkitgXWqkXAm0UHQm:-L2MkitgXWqkXAm0UHQn:bze9dm0) (no related file):*
Missing: support for non-Cisco formats.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/821)*

**Comment by dhalperi** [comment]
Reviewed 11 of 13 files at r2.
Review status: 16 of 18 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 1011 at r2](https://reviewable.io:443/reviews/batfish/batfish/821#-L2MrtSFW-GnH3yMVGEz:-L2MrtSFW-GnH3yMVGF-:bfkrch4) ([raw file](https://github.com/batfish/batfish/blob/469d19e26135c0ea028e55ea8e15e687b17e850b/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L1011)):*
> ```Java
>     }
>     newInterface.setDeclaredNames(
>         new ImmutableSortedSet.Builder<String>(naturalOrder())
> ```

I think you want `ImmutableSortedSet.naturalOrder()` here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/821)*

**Comment by dhalperi** [comment]
:lgtm:

---

Review status: 16 of 18 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/821#-:-L2MsTfJPyhxzwmo1DIw:bnfp4nl)*

**Comment by dhalperi** [comment]
Reviewed 2 of 13 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/821)*

**Comment by arifogel** [comment]
*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 1011 at r2](https://reviewable.io:443/reviews/batfish/batfish/821#-L2MrtSFW-GnH3yMVGEz:-L2MsamImWcPR6gC54qN:bo8t0uo) ([raw file](https://github.com/batfish/batfish/blob/469d19e26135c0ea028e55ea8e15e687b17e850b/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L1011)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I think you want `ImmutableSortedSet.naturalOrder()` here.
</blockquote></details>

Didn't know it was there. There are tons of other places I could switch to it as well. Any particular advantage?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/821)*

**Comment by arifogel** [comment]
*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 1011 at r2](https://reviewable.io:443/reviews/batfish/batfish/821#-L2MrtSFW-GnH3yMVGEz:-L2N0zI6a1FC_gleP0WC:b-763ip1) ([raw file](https://github.com/batfish/batfish/blob/469d19e26135c0ea028e55ea8e15e687b17e850b/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L1011)):*
> ImmutableSortedSet.naturalOrder(
Never mind, looked it up.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/821)*

**Comment by arifogel** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java, line 1011 at r2](https://reviewable.io:443/reviews/batfish/batfish/821#-L2MrtSFW-GnH3yMVGEz:-L2N20lDw4lHgMvxubs7:bav4u62) ([raw file](https://github.com/batfish/batfish/blob/469d19e26135c0ea028e55ea8e15e687b17e850b/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L1011)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

> ImmutableSortedSet.naturalOrder(
Never mind, looked it up.
</blockquote></details>

OK. will add to separate PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/821)*

**Pull request merged**
