### PR TITLE
CompositeBatfishException: add suppressed exceptions

### PR DESCRIPTION
**Pull request by dhalperi**
---
This change is [Reviewable](https://reviewable.io/reviews/batfish/batfish/912)

### CODE REVIEW

**Comment by arifogel** [comment]
I wasn't aware of the existence of this suppressed exceptions concept. Perhaps this class is totally unnecessary, and we can just use BatfishException with suppressed exceptions. But otherwise :lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/912#-:-L4nA1VNFhKYtICEY_oE:btrwgpc)*

**Comment by arifogel** [comment]
:lgtm: with one minor suggestion

---

Reviewed 9 of 9 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/test/java/org/batfish/job/BatfishJobExecutorTest.java, line 116 at r2](https://reviewable.io:443/reviews/batfish/batfish/912#-L4oM5Zpx0AbY4DDeMb3:-L4oM5Zpx0AbY4DDeMb4:bbnfct2) ([raw file](https://github.com/batfish/batfish/blob/12de155df2efef8eb374b78f4bfbabadcdc4373c/projects/batfish/src/test/java/org/batfish/job/BatfishJobExecutorTest.java#L116)):*
> ```Java
>     // checking if the exception thrown has correct class
>     _thrown.expect(BatfishException.class);
>     _thrown.expectMessage("Fatal exception due to failure of at least one job");
> ```

Constant?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/912#-:-L4oMKe79_Gbc6ABNsrE:bp3lff8)*

**Comment by dhalperi** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish/src/test/java/org/batfish/job/BatfishJobExecutorTest.java, line 116 at r2](https://reviewable.io:443/reviews/batfish/batfish/912#-L4oM5Zpx0AbY4DDeMb3:-L4qPlUnC8IbYeaFlBiS:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/12de155df2efef8eb374b78f4bfbabadcdc4373c/projects/batfish/src/test/java/org/batfish/job/BatfishJobExecutorTest.java#L116)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Constant?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/912)*

**Comment by dhalperi** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/batfish/batfish/912)*

**Pull request merged**
