### PR TITLE
Parsing ospf stub command variations

### PR DESCRIPTION
**Pull request by haverma**
- allowing no-summaries and default-metric in `set protocols ospf area ID stub` command

### CODE REVIEW

**Comment by dhalperi** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_ospf.g4, line 160 at r1](https://reviewable.io/reviews/batfish/batfish/1377#-LCHVh_C-7_QZL2wzYdY:-LCHVh_C-7_QZL2wzYdZ:b-39k07f) ([raw file](https://github.com/batfish/batfish/blob/8ffde586e7c65a46c26780d0360ead0636e6ba1b/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_ospf.g4#L160)):*
> ```
> | DEFAULT_METRIC DEC
> ```

introduce a new rule -- `oas_default_metric` for this variant.

Also needs to be handled in extraction -- ospf metrics are important for dataplane building, and for checks like symmetric ospf costs. You can see some Cisco ospf metric tests, probably in CiscoGrammarTest, as a basis.

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_ospf.g4, line 161 at r1](https://reviewable.io/reviews/batfish/batfish/1377#-LCHW9iZ3e3X4zfA5QK4:-LCHW9iZ3e3X4zfA5QK5:b-pe5lj9) ([raw file](https://github.com/batfish/batfish/blob/8ffde586e7c65a46c26780d0360ead0636e6ba1b/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_ospf.g4#L161)):*
> ```ANTLR
>       oas_no_summaries
>       | DEFAULT_METRIC DEC
>    )?
> ```

what does the command with no following clauses do? is it handled correctly?

---

*[projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/ospf-stub, line 6 at r1](https://reviewable.io/reviews/batfish/batfish/1377#-LCHWP5i4JvfKOS0JmsI:-LCHWP5i4JvfKOS0JmsJ:b-bxkmnf) ([raw file](https://github.com/batfish/batfish/blob/8ffde586e7c65a46c26780d0360ead0636e6ba1b/projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/ospf-stub#L6)):*
> ```
> set protocols ospf area 0.0.0.46 stub
> set protocols ospf area 0.0.0.46 stub no-summaries
> set protocols ospf area 0.0.0.7 stub default-metric 10
> ```

just add these to the `test_rigs/unit-tests` testrig -- that way we can also see and verify the nodes model, etc..

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1377)*

**Comment by haverma** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_ospf.g4, line 160 at r1](https://reviewable.io/reviews/batfish/batfish/1377#-LCHVh_C-7_QZL2wzYdY:-LCRIrkZAztspnlaLTPS:belede0) ([raw file](https://github.com/batfish/batfish/blob/8ffde586e7c65a46c26780d0360ead0636e6ba1b/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_ospf.g4#L160)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> | DEFAULT_METRIC DEC
> ```

introduce a new rule -- `oas_default_metric` for this variant.

Also needs to be handled in extraction -- ospf metrics are important for dataplane building, and for checks like symmetric ospf costs. You can see some Cisco ospf metric tests, probably in CiscoGrammarTest, as a basis.
</blockquote></details>

added a new rule for oas_default_metric

from my current understanding after discussing with @progwriter about ospf areas in Batfish, we are not modeling stub areas for ospf and  the `default-metric` command here is specifically for configuring a default route  to the ABR of a stub-area for packets to external networks (https://www.juniper.net/documentation/en_US/junos/topics/example/ospf-stub-area-configuring.html).  So I don't think extracting this information will find any use in Batfish.  Cisco uses `default-cost` command to represent the same thing and that is also not being extracted (https://github.com/batfish/batfish/blob/e4f92b177cf257740cd0896383a4085d224ef5cc/projects/batfish/src/main/antlr4/org/batfish/grammar/cisco/Cisco_ospf.g4#L622). 
Also, it seems that `default-metric` command in Juniper and Cisco represent different concepts. (https://www.cisco.com/c/m/en_us/techdoc/dc/reference/cli/nxos/commands/ospf/default-metric-ospf.html)

---

*[projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_ospf.g4, line 161 at r1](https://reviewable.io/reviews/batfish/batfish/1377#-LCHW9iZ3e3X4zfA5QK4:-LCROzDi7Hjog7pB_L1U:b-31wuzv) ([raw file](https://github.com/batfish/batfish/blob/8ffde586e7c65a46c26780d0360ead0636e6ba1b/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_ospf.g4#L161)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

what does the command with no following clauses do? is it handled correctly?
</blockquote></details>

It declares the area as a stub area, it will just be parsed(extraction is not handled). The first line of `set-protocols` in `ospf-stub` test-config does not contain any following clauses.

---

*[projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/ospf-stub, line 6 at r1](https://reviewable.io/reviews/batfish/batfish/1377#-LCHWP5i4JvfKOS0JmsI:-LCRPsJO6VxlmoTpFX3b:bhitfuz) ([raw file](https://github.com/batfish/batfish/blob/8ffde586e7c65a46c26780d0360ead0636e6ba1b/projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/ospf-stub#L6)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

just add these to the `test_rigs/unit-tests` testrig -- that way we can also see and verify the nodes model, etc..
</blockquote></details>

Since we are not extracting anything from these commands, I don't think this will have any effect on that nodes/data-model. But still I can add it in the `unit-tests` test_rigs if  that is needed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1377)*

**Comment by dhalperi** [comment]
*[projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/ospf-stub, line 6 at r1](https://reviewable.io/reviews/batfish/batfish/1377#-LCHWP5i4JvfKOS0JmsI:-LCU7v1I7DceaHP58D64:b-c51tm1) ([raw file](https://github.com/batfish/batfish/blob/8ffde586e7c65a46c26780d0360ead0636e6ba1b/projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/ospf-stub#L6)):*
<details><summary><i>Previously, haverma (Harsh Verma) wrote…</i></summary><blockquote>

Since we are not extracting anything from these commands, I don't think this will have any effect on that nodes/data-model. But still I can add it in the `unit-tests` test_rigs if  that is needed.
</blockquote></details>

Any lines of config we require to parse now and keep parsing in the future should be exercised via the `parsing-tests`, which are primarily the `unit-tests` testrig. Additionally, when currently-unimplemented features become implemented, they will show up in the nodes model.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1377)*

**Comment by arifogel** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1377)*

**Comment by dhalperi** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1377)*

**Comment by haverma** [comment]
Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/ospf-stub, line 6 at r1](https://reviewable.io/reviews/batfish/batfish/1377#-LCHWP5i4JvfKOS0JmsI:-LCUvO2q7b1ApGjHIhep:bxsh8i1) ([raw file](https://github.com/batfish/batfish/blob/8ffde586e7c65a46c26780d0360ead0636e6ba1b/projects/batfish/src/test/resources/org/batfish/grammar/juniper/testconfigs/ospf-stub#L6)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Any lines of config we require to parse now and keep parsing in the future should be exercised via the `parsing-tests`, which are primarily the `unit-tests` testrig. Additionally, when currently-unimplemented features become implemented, they will show up in the nodes model.
</blockquote></details>

Moved the unit test to test_rigs/unit-tests

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1377)*

**Comment by dhalperi** [comment]
:lgtm:

---

Reviewed 3 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1377#-:-LCUxmKI92oHGXw_EvfH:bnfp4nl)*

**Pull request merged**
