### PR TITLE
Junos: Parse interface primary

### PR DESCRIPTION
**Pull request by ratulm**

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8015)* status: all files reviewed, 4 unresolved discussions (waiting on @dhalperi and @ratulm)

___
*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 2451 at r1](https://reviewable.io/reviews/batfish/batfish/8015#-MvMg_lMC9CbyD299rWz:-MvMg_lMC9CbyD299rX-:becbnv5) ([raw file](https://github.com/batfish/batfish/blob/bd3be2bf5b217fd00f3ab2190cc5c532649a39ea/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L2451)):*
> ```Java
>     if (currentPrimary.isPresent()
>         && !currentPrimary.get().getName().equals(_currentInterfaceOrRange.getName())) {
>       throw new WillNotCommitException(
> ```

I'd like to avoid any new `WillNotCommitException`s. Please just do something reasonable and warn. Might need to do it in conversion if you can't figure out the range meaning until then. Add a test for warning.
___
*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 2456 at r1](https://reviewable.io/reviews/batfish/batfish/8015#-MvMgrqU8HLMfhl5ZcJv:-MvMgrqU8HLMfhl5ZcJw:b931lp1) ([raw file](https://github.com/batfish/batfish/blob/bd3be2bf5b217fd00f3ab2190cc5c532649a39ea/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L2456)):*
> ```Java
>               _currentInterfaceOrRange.getName(), currentPrimary.get().getName()));
>     }
>     _currentInterfaceOrRange.setPrimary(true);
> ```

It can't be a range can it? Can you have singleton ranges?
___
*[projects/batfish/src/main/java/org/batfish/representation/juniper/Interface.java, line 172 at r1](https://reviewable.io/reviews/batfish/batfish/8015#-MvMhjNx-RKl1JFMYaox:-MvMhjNx-RKl1JFMYaoy:b-p07mda) ([raw file](https://github.com/batfish/batfish/blob/bd3be2bf5b217fd00f3ab2190cc5c532649a39ea/projects/batfish/src/main/java/org/batfish/representation/juniper/Interface.java#L172)):*
> ```Java
>   private InterfaceAddress _preferredAddress;
>   private ConcreteInterfaceAddress _primaryAddress;
>   private @Nullable Boolean _primary;
> ```

nit: Is this inheritable? Is there an explicit false setting? Seems like primitive would work just fine.
___
*[projects/batfish/src/main/java/org/batfish/representation/juniper/Interface.java, line 301 at r1](https://reviewable.io/reviews/batfish/batfish/8015#-MvMjIMw8qgQLuG5ocq1:-MvMjIMw8qgQLuG5ocq2:bdipxmw) ([raw file](https://github.com/batfish/batfish/blob/bd3be2bf5b217fd00f3ab2190cc5c532649a39ea/projects/batfish/src/main/java/org/batfish/representation/juniper/Interface.java#L301)):*
needs javadoc. I see this Juniper docs excerpt:
> By default, the multicast-capable interface with the lowest-index address is chosen as the primary interface. If there is no such interface, the point-to-point interface with the lowest-index address is chosen. Otherwise, any interface with an address can be picked.

So the doc for this function needs to differentiate between actual and configured primary.

I assume conversion code where you figure out the actual primary when none is configured will be in a  forthcoming PR?

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8015)* status: all files reviewed, 4 unresolved discussions (waiting on @arifogel, @dhalperi, and @ratulm)

___
*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 2451 at r1](https://reviewable.io/reviews/batfish/batfish/8015#-MvMg_lMC9CbyD299rWz:-MvMlLt99rA9XOGiBfeV:b-d94gq0) ([raw file](https://github.com/batfish/batfish/blob/bd3be2bf5b217fd00f3ab2190cc5c532649a39ea/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L2451)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

I'd like to avoid any new `WillNotCommitException`s. Please just do something reasonable and warn. Might need to do it in conversion if you can't figure out the range meaning until then. Add a test for warning.
</blockquote></details>

If we have a config that doesn't commit, don't we want to throw this exception?

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8015)* status: all files reviewed, 4 unresolved discussions (waiting on @dhalperi and @ratulm)

___
*[projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java, line 2451 at r1](https://reviewable.io/reviews/batfish/batfish/8015#-MvMg_lMC9CbyD299rWz:-MvMoGqa9OpwVzkGrthJ:bp8d2lj) ([raw file](https://github.com/batfish/batfish/blob/bd3be2bf5b217fd00f3ab2190cc5c532649a39ea/projects/batfish/src/main/java/org/batfish/grammar/flatjuniper/ConfigurationBuilder.java#L2451)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

If we have a config that doesn't commit, don't we want to throw this exception? 
</blockquote></details>

nah we're nicer now.

**Review by arifogel — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8015)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dhalperi)

**Pull request merged**
