### PR TITLE
IBDP: do not recompute fibs and forwarding analysis at the end

### PR DESCRIPTION
**Pull request by dhalperi**
We can instead reuse the forwarding analysis used to build topologies.
Since the topologies haven't changed, and no route exchange has been
done, the FIBs and Forwarding Analysis cannot have changed.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7617)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @anothermattbrown and @arifogel)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlane.java, line 146 at r1](https://reviewable.io/reviews/batfish/batfish/7617#-MnCMMaiC2lfMi4g78V0:-MnCMMaj03IwQDiXZ_b2:b97tzpl) ([raw file](https://github.com/batfish/batfish/blob/ed798657d202e4c3a7011dfa441a5022899fd579/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlane.java#L146)):*
> ```
>  // Order of initialization matters:
> ```
FYI, I preserved this comment but I honestly cannot figure out why order matters.

**Review by arifogel — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7617)* status: all files reviewed, 1 unresolved discussion (waiting on @anothermattbrown and @dhalperi)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7617#-MnCSJYc1kQTSvDEeG-N:-MnCSJYd5_y1BI8jaOp4:b-ty9jqw) (no related file):*
I'm having trouble seeing where you removed any computation.

It looks like there are two places nextTopologyContext was called before. Each time it was called, it computed a data plane towards the beginning.
Now there are two places where you compute next data plane, then immediately compute next topology context. What's the difference?

---

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7617)* status: all files reviewed, 1 unresolved discussion (waiting on @anothermattbrown and @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlane.java, line 138 at r1](https://reviewable.io/reviews/batfish/batfish/7617#-MnCT4NZBrp_bYZ9n5Ai:-MnCT4NZBrp_bYZ9n5Aj:b-x9b6co) ([raw file](https://github.com/batfish/batfish/blob/90897a4012f76c6367266a73e6e3e5779a368c08/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlane.java#L138)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>     // Grab the already-finalized FIBs and ForwardingAnalysis.
>     PartialDataplane dataplane = builder._partialDataplane;
>     _fibs = dataplane.getFibs();
>     _forwardingAnalysis = dataplane.getForwardingAnalysis();
> 
> ```
</details>

@arifogel - this is constant time
___
*[projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlane.java, line 155 at r1](https://reviewable.io/reviews/batfish/batfish/7617#-MnCT7HdEyBRjZ_PBA6m:-MnCT7HdEyBRjZ_PBA6n:b6tscuc) ([raw file](https://github.com/batfish/batfish/blob/ed798657d202e4c3a7011dfa441a5022899fd579/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/IncrementalDataPlane.java#L155)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>     _fibs = DataplaneUtil.computeFibs(nodes);
>     _forwardingAnalysis =
>         DataplaneUtil.computeForwardingAnalysis(
>             _fibs, configs, builder._layer3Topology, builder._l3Adjacencies);
> ```
</details>


FYI this is the removed work.

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7617)* status: all files reviewed, 1 unresolved discussion (waiting on @anothermattbrown and @arifogel)

*[a discussion](https://reviewable.io/reviews/batfish/batfish/7617#-MnCSJYc1kQTSvDEeG-N:-MnCTFdvEWwW521Rx8ey:b-ig0xqp) (no related file):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

I'm having trouble seeing where you removed any computation.

It looks like there are two places nextTopologyContext was called before. Each time it was called, it computed a data plane towards the beginning.
Now there are two places where you compute next data plane, then immediately compute next topology context. What's the difference?
</blockquote></details>

See FYIs

---

**Review by arifogel — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7617)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown)

**Pull request merged**
