### PR TITLE
Don't look for blockers for independently unmatchable lines

### PR DESCRIPTION
**Pull request by corinaminer**
Minor optimization: If a line is already known to be unmatchable, don't bother running a NoD job to find earlier more general lines blocking it.

### CODE REVIEW

**Comment by anothermattbrown** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 966 at r1](https://reviewable.io/reviews/batfish/batfish/1381#-LCVNiXPEM-OBco93SVd:-LCVNiXPEM-OBco93SVe:b-onmkju) ([raw file](https://github.com/batfish/batfish/blob/446029ceaa5877733bf65c54d70cd93b72005ff2/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L966)):*
> ```Java
>       Configuration c = configurations.get(hostname);
>       Map<String, SortedSet<Integer>> unmatchableLinesForHostname =
>           firstNonNull(unmatchableLines.get(hostname), ImmutableMap.of());
> ```

you can use `unmatchableLines.getOrDefault(hostname, ImmutableMap.of())` here and below.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1381)*

**Comment by arifogel** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1381)*

**Comment by corinaminer** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 966 at r1](https://reviewable.io/reviews/batfish/batfish/1381#-LCVNiXPEM-OBco93SVd:-LCVQY7b2bPCuaAi_Slz:b-j8hj1n) ([raw file](https://github.com/batfish/batfish/blob/446029ceaa5877733bf65c54d70cd93b72005ff2/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L966)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

you can use `unmatchableLines.getOrDefault(hostname, ImmutableMap.of())` here and below.
</blockquote></details>

Done. Also simplified a snippet in `answerAclReachability()` the same way.

---

*[projects/batfish/src/main/java/org/batfish/main/Batfish.java, line 829 at r2](https://reviewable.io/reviews/batfish/batfish/1381#-LCVQlXw-QLR0I3ls1PX:-LCVQlXw-QLR0I3ls1PY:b-vajv0k) ([raw file](https://github.com/batfish/batfish/blob/dd79a5e8763b6acb22d8ffcbee71f22b5710f93c/projects/batfish/src/main/java/org/batfish/main/Batfish.java#L829)):*
> ```Java
>           unmatchableLines
>               .getOrDefault(hostname, ImmutableSortedMap.of())
>               .getOrDefault(aclName, ImmutableSortedSet.of());
> ```

`unmatchableLines` is only used once after its declaration, and that's a call to `contains()`, so should be fine for it to become immutable if empty.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1381)*

**Comment by arifogel** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1381)*

**Comment by anothermattbrown** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1381#-:-LCVn4mkDW2mCl76kFje:bnfp4nl)*

**Comment by arifogel** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1381)*

**Pull request merged**
