### PR TITLE
Visitor interface for reachability graph Transitions

### PR DESCRIPTION
**Pull request by corinaminer**
Adds visitor interface and makes a few constructors/getters public for later accessibility.

### CODE REVIEW

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 19 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8149)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8149)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8149)* status: all files reviewed, 1 unresolved discussion (waiting on @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/bddreachability/transition/Composite.java, line 19 at r2](https://reviewable.io/reviews/batfish/batfish/8149#-MyF6q0v2rZQd1ab42qn:-MyF6q0v2rZQd1ab42qo:b-40jqt2) ([raw file](https://github.com/batfish/batfish/blob/f5891b90a1ad771bcc09d805a851751311748f56/projects/batfish/src/main/java/org/batfish/bddreachability/transition/Composite.java#L19)):*
> ```Java
> 
>   public Composite(List<Transition> transitions) {
>     checkArgument(!transitions.isEmpty(), "Cannot compose 0 Transitions. Use Identity instead");
> ```

(Similar throughout)

why make these public? Keeping these hidden has been a key decision - callers should go through `Transitions#compose`.

If we need an escape hatch for some reason we should create a different named static factory method with appropriate caveats, I'd think.



_Code quote:_
```Java
  public Composite(Transition... transitions) {
    this(ImmutableList.copyOf(transitions));
  }

  public Composite(List<Transition> transitions) {
    checkArgument(!transitions.isEmpty(), "Cannot compose 0 Transitions. Use Identity instead");
```

**Review by dhalperi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8149)* status: 14 of 19 files reviewed, all discussions resolved (waiting on @anothermattbrown)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8149)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8149)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/bddreachability/transition/Composite.java, line 19 at r2](https://reviewable.io/reviews/batfish/batfish/8149#-MyF6q0v2rZQd1ab42qn:-MyJZ9y75uKY9tAWybcU:bqcq013) ([raw file](https://github.com/batfish/batfish/blob/f5891b90a1ad771bcc09d805a851751311748f56/projects/batfish/src/main/java/org/batfish/bddreachability/transition/Composite.java#L19)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

(Similar throughout)

why make these public? Keeping these hidden has been a key decision - callers should go through `Transitions#compose`.

If we need an escape hatch for some reason we should create a different named static factory method with appropriate caveats, I'd think.
</blockquote></details>

done (reverted public constructors)

**Pull request merged**
