### PR TITLE
FortiOS: simplify naming cross-zone policies

### PR DESCRIPTION
**Pull request by sfraint**

### CODE REVIEW

**Review by corinaminer — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6755)* status: all files reviewed, 1 unresolved discussion (waiting on @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosPolicyConversions.java, line 204 at r2](https://reviewable.io/reviews/batfish/batfish/6755#-MWBG_qMA2hUPvurCb_m:-MWBG_qMA2hUPvurCb_n:b-fhgrd9) ([raw file](https://github.com/batfish/batfish/blob/5a9307473f3025f1843369b5f6642d43a5e7e935/projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosPolicyConversions.java#L204)):*
> ```Java
>    * {@code toZoneOrIface}.
>    */
>   static String computeCrossZoneFilterName(
> ```

Probably best to remove this function altogether to make it more obvious that FortiOS uses `zoneToZoneFilter` to name its cross-zone filters. callers can just call that directly

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6755)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @corinaminer)

___
*[projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosPolicyConversions.java, line 204 at r2](https://reviewable.io/reviews/batfish/batfish/6755#-MWBG_qMA2hUPvurCb_m:-MWBIg_8-iSeSGzNrB1F:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/5a9307473f3025f1843369b5f6642d43a5e7e935/projects/batfish/src/main/java/org/batfish/representation/fortios/FortiosPolicyConversions.java#L204)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Probably best to remove this function altogether to make it more obvious that FortiOS uses `zoneToZoneFilter` to name its cross-zone filters. callers can just call that directly
</blockquote></details>

done

**Review by sfraint — COMMENTED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6755)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @corinaminer)

**Review by corinaminer — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6755#-:-MWBJ9slCJ4u0rti1h63:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
