### PR TITLE
NXOS: fixup bgp allowas-in extraction

### PR DESCRIPTION
**Pull request by progwriter**
Stop warning that the feature is unsupported; plumb though full extraction, convert to the best of VI abilities

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6383#-:-MLBPeRh0qAc6aob0g6m:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by dhalperi** [comment]
___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java, line 3786 at r1](https://reviewable.io/reviews/batfish/batfish/6383#-MLBPoE00wE6rnEky6lC:-MLBPoE00wE6rnEky6lD:by08db0) ([raw file](https://github.com/batfish/batfish/blob/67821f4e017437988d474d37e7f8b6aa40d2e612/projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java#L3786)):*
> ```
> 
>     _currentBgpVrfNeighborAddressFamily.setAllowAsIn(
>         ctx.num == null ? 3 : toInteger(ctx, ctx.num).orElse(null));
> ```
Hmm, if the value is out of range it clears the existing value or leaves it?

**Review by progwriter — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6383)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java, line 3786 at r1](https://reviewable.io/reviews/batfish/batfish/6383#-MLBPoE00wE6rnEky6lC:-MLBVXrXCT3jkZnZc-4T:bz23wlk) ([raw file](https://github.com/batfish/batfish/blob/67821f4e017437988d474d37e7f8b6aa40d2e612/projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java#L3786)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> 
>     _currentBgpVrfNeighborAddressFamily.setAllowAsIn(
>         ctx.num == null ? 3 : toInteger(ctx, ctx.num).orElse(null));
> ```
Hmm, if the value is out of range it clears the existing value or leaves it?
</blockquote></details>

tested in gns3, keeps old value. fixed

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6383)* status: all files reviewed, 1 unresolved discussion (waiting on @progwriter)

___
*[projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java, line 3787 at r2](https://reviewable.io/reviews/batfish/batfish/6383#-MLBWsIg2vx20xi4ps9K:-MLBWsIg2vx20xi4ps9L:b-w9ppv9) ([raw file](https://github.com/batfish/batfish/blob/9be20413009ba72dd98666e4c253bc057e09067d/projects/batfish/src/main/java/org/batfish/grammar/cisco_nxos/CiscoNxosControlPlaneExtractor.java#L3787)):*
> ```Java
>     _currentBgpVrfNeighborAddressFamily.setAllowAsIn(
>         ctx.num == null
>             ? 3
> ```

FWIW, this is somewhat easier as:

```
Optional<Integer> value = (ctx.num == null) ? Optional.of(3) : toInteger...
value.ifPresent(_currentBVNAF::setAllowAsIn);
```

fine either way.

change or don't, please self-merge.

**Review by progwriter — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/6383)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
