### PR TITLE
Overhaul Juniper lexer and parser

### PR DESCRIPTION
**Pull request by arifogel**
- removed `VARIABLE` token, `variable*` rules, and associated lexer state variables
- all lexing of tokens that don't take up a whole word must be done in non-default mode
  - else will become `UNRECOGNIZED_WORD`, which is valid only as part of `null_filler`
  - example: lexing '1-5' as a subrange must be done in non-default mode,
    since:
       '1' `DEC`
       '-' `DASH`
       '5' `DEC`
     would now become '1-5' `UNRECOGNIZED_WORD` in default mode
  - as a result, things like URLs and timestamps are now lexed as a single word rather than a mishmash of tokens
- removed all unsafe uses of `Token.getText()`
  - centralize text extraction for things like junos-name
  - replaced many tokens in rules with rule references, e.g. `IP_ADDRESS` -> `ip_address`
  - fixed inconsistent parser rule and extractor patterns
    - all names are now `junos_name` (or a more general rule of which `junos`_name is an alternative)
    - use converter functions taking rules as arguments instead of tokens or strings
    - all policy references now support policy expressions instead of just a single name
    - all secrets are now `secret_string`, and are (somtimes decrypted and) hashed
- stricter lexing of as-path regexes, as-path expressions, community regexes
  - properly only allow spaces in quoted strings
- lex interface names as a single token, and break them apart in extractor instead
  - add extractor-internal `InterfaceId` class to support this
- clean up some broken parser rules
  - e.g. disallow some nonsense alternatives under routing-instances
- many many more lexer modes to support above changes
  - remove some broken modes

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 28 of 34 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8012)* status: all files reviewed, 4 unresolved discussions (waiting on @arifogel)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_interfaces.g4, line 562 at r2](https://reviewable.io/reviews/batfish/batfish/8012#-MvJzxn28cOxWtg8o7R-:-MvJzxn28cOxWtg8o7R0:b-d9wfu6) ([raw file](https://github.com/batfish/batfish/blob/ad877100e76e4f5d2e9c59f3bec55f90ea31c47c/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_interfaces.g4#L562)):*
> ```ANTLR
> ifiavt_route
> :
>    ROUTE IP_PREFIX ROUTING_INSTANCE ri = junos_name PRIORITY_COST dec
> ```

token or rule?



_Suggestion:_
```ANTLR
ip_prefix
```
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_ospf.g4, line 13 at r2](https://reviewable.io/reviews/batfish/batfish/8012#-MvK-49wEEfpfJTzJA1H:-MvK-49wEEfpfJTzJA1I:b45h) ([raw file](https://github.com/batfish/batfish/blob/ad877100e76e4f5d2e9c59f3bec55f90ea31c47c/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_ospf.g4#L13)):*
> ```ANTLR
>    AREA
>    (
>       area_int = dec
> ```





_Suggestion:_
```ANTLR
uint32
```
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_security.g4, line 23 at r2](https://reviewable.io/reviews/batfish/batfish/8012#-MvK-Y72DakfRKmtiEmt:-MvK-Y72DakfRKmtiEmu:b-kn9guc) ([raw file](https://github.com/batfish/batfish/blob/ad877100e76e4f5d2e9c59f3bec55f90ea31c47c/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_security.g4#L23)):*
> ```ANTLR
>   | IP_PREFIX
>   | IPV6_PREFIX
> ;
> ```

token or rule here?



_Code quote:_
```ANTLR
  | IP_PREFIX
  | IPV6_PREFIX
;
```
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_security.g4, line 314 at r2](https://reviewable.io/reviews/batfish/batfish/8012#-MvK-nTn6PsThbajr95u:-MvK-nTn6PsThbajr95v:b-mww9n4) ([raw file](https://github.com/batfish/batfish/blob/ad877100e76e4f5d2e9c59f3bec55f90ea31c47c/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_security.g4#L314)):*
> ```ANTLR
>    (
>       TO to = dec
>    )?
> ```

optional/defer: port -> some rule meaning port? / 1-65535



_Code quote:_
```ANTLR
   DESTINATION_PORT from = dec
   (
      TO to = dec
   )?
```
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_system.g4, line 321 at r2](https://reviewable.io/reviews/batfish/batfish/8012#-MvK07Jt4nb5iCgj5WfC:-MvK07Jt4nb5iCgj5WfD:b-d9wfu6) ([raw file](https://github.com/batfish/batfish/blob/ad877100e76e4f5d2e9c59f3bec55f90ea31c47c/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_system.g4#L321)):*
> ```ANTLR
> :
>   IP_ADDRESS
>   | IPV6_ADDRESS
> ```

token or rule?



_Code quote:_
```ANTLR
  IP_ADDRESS
  | IPV6_ADDRESS
```

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8012)* status: 24 of 36 files reviewed, 3 unresolved discussions (waiting on @dhalperi)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_interfaces.g4, line 562 at r2](https://reviewable.io/reviews/batfish/batfish/8012#-MvJzxn28cOxWtg8o7R-:-MvKb1kv8DIy1_9j-SAe:b-wl1its) ([raw file](https://github.com/batfish/batfish/blob/ad877100e76e4f5d2e9c59f3bec55f90ea31c47c/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_interfaces.g4#L562)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

token or rule?
</blockquote></details>

rule for when we eventually support this.
fixed.
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_ospf.g4, line 13 at r2](https://reviewable.io/reviews/batfish/batfish/8012#-MvK-49wEEfpfJTzJA1H:-MvKaXsu8gHS-S6Q4YLL:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/ad877100e76e4f5d2e9c59f3bec55f90ea31c47c/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_ospf.g4#L13)):*
> ```ANTLR
>    AREA
>    (
>       area_int = dec
> ```

done
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_security.g4, line 23 at r2](https://reviewable.io/reviews/batfish/batfish/8012#-MvK-Y72DakfRKmtiEmt:-MvKY9Ia4RNXSVJbC6pD:bgkpxm1) ([raw file](https://github.com/batfish/batfish/blob/ad877100e76e4f5d2e9c59f3bec55f90ea31c47c/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_security.g4#L23)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

token or rule here?
</blockquote></details>

explicitly don't want rule here, since these two alternatives should be treated as text. Updated comment.
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_security.g4, line 314 at r2](https://reviewable.io/reviews/batfish/batfish/8012#-MvK-nTn6PsThbajr95u:-MvKae9n3K3UtySoroOu:bn2e30k) ([raw file](https://github.com/batfish/batfish/blob/ad877100e76e4f5d2e9c59f3bec55f90ea31c47c/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_security.g4#L314)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

optional/defer: port -> some rule meaning port? / 1-65535
</blockquote></details>

fixed everything to do with ports
___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_system.g4, line 321 at r2](https://reviewable.io/reviews/batfish/batfish/8012#-MvK07Jt4nb5iCgj5WfC:-MvKawNS9CcvvDiqYz2j:b-kcud3z) ([raw file](https://github.com/batfish/batfish/blob/ad877100e76e4f5d2e9c59f3bec55f90ea31c47c/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniper_system.g4#L321)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

token or rule?
</blockquote></details>

could see eventually caring about semantic content, so changed to use rules.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 12 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8012)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4, line 3514 at r3](https://reviewable.io/reviews/batfish/batfish/8012#-MvL34doCF7NU9ic-_Z-:-MvL34doCF7NU9ic-_Z0:b4fs2fr) ([raw file](https://github.com/batfish/batfish/blob/456920221eaa5dfff19e46ffbb1fadf147a42c73/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4#L3514)):*
> ```ANTLR
>   (
>     F_Digit
>     | '0'* F_PositiveDigit F_Digit
> ```

Not sure why this is not redundant with the other `'0'*`?



_Code quote:_
```ANTLR
'0'* 
```

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8012)* status: 35 of 36 files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4, line 3514 at r3](https://reviewable.io/reviews/batfish/batfish/8012#-MvL34doCF7NU9ic-_Z-:-MvL42yj2OOOj9F9PLuP:b-hfpv0l) ([raw file](https://github.com/batfish/batfish/blob/456920221eaa5dfff19e46ffbb1fadf147a42c73/projects/batfish/src/main/antlr4/org/batfish/grammar/flatjuniper/FlatJuniperLexer.g4#L3514)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Not sure why this is not redundant with the other `'0'*`?
</blockquote></details>

removed

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/8012)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Pull request merged**
