### PR TITLE
XR: ABF conversion

### PR DESCRIPTION
**Pull request by sfraint**
Convert [Cisco XR ACL based forwarding rules](https://community.cisco.com/t5/service-providers-documents/asr9000-xr-abf-acl-based-forwarding/ta-p/3153403).

### CODE REVIEW

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7055)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @arifogel and @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConversions.java, line 1671 at r1](https://reviewable.io/reviews/batfish/batfish/7055#-Mbh_8t95seJ-cT92g8F:-Mbh_8t95seJ-cT92g8G:b-pp3nbv) ([raw file](https://github.com/batfish/batfish/blob/918e8f0a950a76a3553853a12edcc8237288a18e/projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConversions.java#L1671)):*
> ```
> canConvertAbfAclLine
> ```
this is only needed until `FibLookupOverrideLookupIp` can support different VRFs per nexthop IP.

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7055)* status: 0 of 6 files reviewed, 6 unresolved discussions (waiting on @arifogel and @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConfiguration.java, line 1335 at r1](https://reviewable.io/reviews/batfish/batfish/7055#-MbhuwsNDUngWZ5NpqQk:-MbhyNuA1Ef3debzMffA:b-uqnkc7) ([raw file](https://github.com/batfish/batfish/blob/918e8f0a950a76a3553853a12edcc8237288a18e/projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConfiguration.java#L1335)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> incomingFilter != null
> ```
what if incomingFilter == null?
</blockquote></details>

This happens with undefined references. We're treating this the same as non-ABF undefined references: don't attach anything and surface via undefined references.

Do you think we should do something different here?
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConfiguration.java, line 1346 at r1](https://reviewable.io/reviews/batfish/batfish/7055#-Mbhv0hq28NOlMM280yt:-Mbhyjm1D0dCbYxzBXfG:bi201s7) ([raw file](https://github.com/batfish/batfish/blob/918e8f0a950a76a3553853a12edcc8237288a18e/projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConfiguration.java#L1346)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Does it not apply the entire ACL, or does it just apply the acl ignoring the ABF part?
</blockquote></details>

The device doesn't let you commit it; you get an exception like this from the cli: `!!% 'pfilter-ea' detected the 'resource not available' condition 'Failed on applying ACL based forwarding rule to non-ingress interface'`

Ideally, maybe we should surface a commit-failed status like we do for other vendors
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConfiguration.java, line 1986 at r1](https://reviewable.io/reviews/batfish/batfish/7055#-Mbhv81t6DqchuBkrD6y:-MbhzD9Y7rgWyFGffxv8:bttkelf) ([raw file](https://github.com/batfish/batfish/blob/918e8f0a950a76a3553853a12edcc8237288a18e/projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConfiguration.java#L1986)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> Don't do other conversions for this ACL since ABF ACLs can't be used in non-ABF contexts
> ```

I'd say keep this, so that users will be able to run testFilters etc.

See also other questions.
</blockquote></details>

ack, updated
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConversions.java, line 1720 at r1](https://reviewable.io/reviews/batfish/batfish/7055#-Mbhx8819uauOKwF8xPL:-Mbi03VdA0O_M7dtgVet:bkthozz) ([raw file](https://github.com/batfish/batfish/blob/918e8f0a950a76a3553853a12edcc8237288a18e/projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConversions.java#L1720)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

what about when nexthop1.getIp() is null, aka, just a nexthop vrf?

(Examples in linked docs make it look like this is an option).
</blockquote></details>

Updated.

Note: this isn't allowed by Batfish grammar yet - can add support for that in another PR.
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConversions.java, line 1728 at r1](https://reviewable.io/reviews/batfish/batfish/7055#-Mbhw86cBXKPO1mR143f:-Mbi0Id67BHaDVTp_JWV:b-7ql1td) ([raw file](https://github.com/batfish/batfish/blob/918e8f0a950a76a3553853a12edcc8237288a18e/projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConversions.java#L1728)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> nexthop1.getVrf()
> ```
`nexthopVrf`?
</blockquote></details>

fixed
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConversions.java, line 1733 at r1](https://reviewable.io/reviews/batfish/batfish/7055#-MbhvdUN5di7heDRCbXU:-MbiFNB77gwxeIsX-XIP:b-gm7kpq) ([raw file](https://github.com/batfish/batfish/blob/918e8f0a950a76a3553853a12edcc8237288a18e/projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConversions.java#L1733)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> Drop.instance()
> ```
is it `Drop` or is it fall-through to normal routing?
</blockquote></details>

should actually be a normal lookup; updated

**Review by dhalperi — COMMENTED** [review]
> Reviewed 3 of 6 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7055)* status: all files reviewed, 3 unresolved discussions (waiting on @arifogel and @sfraint)

___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConfiguration.java, line 1335 at r1](https://reviewable.io/reviews/batfish/batfish/7055#-MbhuwsNDUngWZ5NpqQk:-MbiOH1kEA7mU8gzg3B4:bwgufnv) ([raw file](https://github.com/batfish/batfish/blob/918e8f0a950a76a3553853a12edcc8237288a18e/projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConfiguration.java#L1335)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

This happens with undefined references. We're treating this the same as non-ABF undefined references: don't attach anything and surface via undefined references.

Do you think we should do something different here?
</blockquote></details>

Oh, I now think it's just that the code is misleading:

```
if (a != null && f(a)) {
   ..
} else {
   g(a);
}
```

seems like it ought to be

```
if (a != null) {
   if (f(a)) {
     ...
   } else {
     g(a);
   }
} // else when a is null
```

but I am guessing that `g(a)` is the same whether or not it's null?

[aside: what is XR behavior if the ACL is undefined? Fail open, closed, not commit?]
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConfiguration.java, line 1988 at r2](https://reviewable.io/reviews/batfish/batfish/7055#-MbiMgwd47vDzO-TyzLm:-MbiMgwd47vDzO-TyzLn:b-ra9yz6) ([raw file](https://github.com/batfish/batfish/blob/c52cf1edbf4198fecddfa138308e68e80a5427aa/projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConfiguration.java#L1988)):*
> ```
> isAclUsedForRouting(eaList.getName())) {
> ```

Do we have to do the isAclUsedForAbf check wherever these are used, too?
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConversions.java, line 1720 at r1](https://reviewable.io/reviews/batfish/batfish/7055#-Mbhx8819uauOKwF8xPL:-MbiO1kZ48pjTyhmPFIK:b-hxtq48) ([raw file](https://github.com/batfish/batfish/blob/918e8f0a950a76a3553853a12edcc8237288a18e/projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConversions.java#L1720)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

Updated.

Note: this isn't allowed by Batfish grammar yet - can add support for that in another PR.
</blockquote></details>

I am guessing the update is not correct -- we can't use FibLookupOverrideIp if there aren't any IPs provided?

Maybe revert this local change for now, and defer until grammar is updated?

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7055)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @arifogel and @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConfiguration.java, line 1335 at r1](https://reviewable.io/reviews/batfish/batfish/7055#-MbhuwsNDUngWZ5NpqQk:-MbijhNv942pVGYbMbZ6:b-ujhz7r) ([raw file](https://github.com/batfish/batfish/blob/918e8f0a950a76a3553853a12edcc8237288a18e/projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConfiguration.java#L1335)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Oh, I now think it's just that the code is misleading:

```
if (a != null && f(a)) {
   ..
} else {
   g(a);
}
```

seems like it ought to be

```
if (a != null) {
   if (f(a)) {
     ...
   } else {
     g(a);
   }
} // else when a is null
```

but I am guessing that `g(a)` is the same whether or not it's null?

[aside: what is XR behavior if the ACL is undefined? Fail open, closed, not commit?]
</blockquote></details>

right; and undefined access lists permit all packets
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConfiguration.java, line 1988 at r2](https://reviewable.io/reviews/batfish/batfish/7055#-MbiMgwd47vDzO-TyzLm:-MbihCcg7PUWglEmXiJg:b-m1wk72) ([raw file](https://github.com/batfish/batfish/blob/c52cf1edbf4198fecddfa138308e68e80a5427aa/projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConfiguration.java#L1988)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> isAclUsedForRouting(eaList.getName())) {
> ```

Do we have to do the isAclUsedForAbf check wherever these are used, too?
</blockquote></details>

probably, but this is a no-op today / not used
```
  private boolean isAclUsedForRouting(@Nonnull String aclName) {
    // TODO: implement OSPF acl distribute-list
    return false;
  }
```
___
*[projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConversions.java, line 1720 at r1](https://reviewable.io/reviews/batfish/batfish/7055#-Mbhx8819uauOKwF8xPL:-Mbiii6s6bl9T8Isptwh:bvth56w) ([raw file](https://github.com/batfish/batfish/blob/918e8f0a950a76a3553853a12edcc8237288a18e/projects/batfish/src/main/java/org/batfish/representation/cisco_xr/CiscoXrConversions.java#L1720)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I am guessing the update is not correct -- we can't use FibLookupOverrideIp if there aren't any IPs provided?

Maybe revert this local change for now, and defer until grammar is updated?
</blockquote></details>

reverted

**Review by dhalperi — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7055#-:-Mbin9nYAGFA3WVHIgYE:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Pull request merged**
