### PR TITLE
fix aws interface instantiation, refactor using builders

### PR DESCRIPTION
**Pull request by arifogel**
This change is [Reviewable](https://reviewable.io/reviews/batfish/batfish/722)

### CODE REVIEW

**Comment by dhalperi** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/Utils.java, line 32 at r1](https://reviewable.io:443/reviews/batfish/batfish/722#-L-s3jfrQEQMoLVr6L2i:-L-s3jfrQEQMoLVr6L2j:b-wtdum4) ([raw file](https://github.com/batfish/batfish/blob/6c5f61f2210280ca624e09cb64a604b21b484041/projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/Utils.java#L32)):*
> ```Java
>   }
> 
>   public static Interface newInterface(String name, Configuration c, Prefix primaryPrefix) {
> ```

My inclination is to say that these should be static factory methods inside of `Interface` or `Configuration`. It's not obvious why these need to be in a separate utils class.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/722)*

**Comment by dhalperi** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/722#-:-L-sAg04JVWn5jePf6C0:bnfp4nl)*

**Comment by arifogel** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/Utils.java, line 32 at r1](https://reviewable.io:443/reviews/batfish/batfish/722#-L-s3jfrQEQMoLVr6L2i:-L-sOOZdNrr7Wh6P_Zmq:bblzxrc) ([raw file](https://github.com/batfish/batfish/blob/6c5f61f2210280ca624e09cb64a604b21b484041/projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/Utils.java#L32)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

My inclination is to say that these should be static factory methods inside of `Interface` or `Configuration`. It's not obvious why these need to be in a separate utils class.
</blockquote></details>

The behavior here is specific to AWS.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/722)*

**Comment by dhalperi** [comment]
*[projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/Utils.java, line 32 at r1](https://reviewable.io:443/reviews/batfish/batfish/722#-L-s3jfrQEQMoLVr6L2i:-L-sPGyuG3tpJi47JHfo:b-8qvflh) ([raw file](https://github.com/batfish/batfish/blob/6c5f61f2210280ca624e09cb64a604b21b484041/projects/batfish/src/main/java/org/batfish/representation/aws_vpcs/Utils.java#L32)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

The behavior here is specific to AWS.
</blockquote></details>

Okay. It's hard to tell because the classes don't reflect that.

Optional: improve this scenario, e.g.

* Name this class `AwsDatamodelUtils` or something else that reflects its actual purpose?
* Name `Interface` as `CiscoInterface`, etc?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/batfish/batfish/722)*

**Pull request merged**
