### PR TITLE
A10: extract static routes

### PR DESCRIPTION
**Pull request by sfraint**

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 9 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7458)* status: all files reviewed, 4 unresolved discussions (waiting on @corinaminer and @sfraint)

___
*[projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Parser.g4, line 6 at r2](https://reviewable.io/reviews/batfish/batfish/7458#-MknrrolE1Dev2noYNkj:-MknrrolE1Dev2noYNkk:bbe1stj) ([raw file](https://github.com/batfish/batfish/blob/1e6bd40fc88bc3d2c4e4d35c1098894a0dc7cea4/projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Parser.g4#L6)):*
> ```ANTLR
>   A10_common,
>   A10_interface,
>   A10_ip,
> ```

Seems like a weird grammar file boundary. Is `ip` not huge? Would it make sense to do `A10_ip_route` or something like that scoped to static routes?
___
*[projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java, line 702 at r2](https://reviewable.io/reviews/batfish/batfish/7458#-MknsfyG-IVPdXO8XV38:-MknsfyG-IVPdXO8XV39:b-les5j5) ([raw file](https://github.com/batfish/batfish/blob/1e6bd40fc88bc3d2c4e4d35c1098894a0dc7cea4/projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java#L702)):*
> ```Java
>     Ip address = toIp(prefixCtx.ip_address());
>     Prefix prefix = toPrefix(prefixCtx);
>     if (prefix.getStartIp() != address) {
> ```

I think in general you should use `!...equals` instead of `!=` for `Ip`, despite caching/inlining.
___
*[projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java, line 703 at r2](https://reviewable.io/reviews/batfish/batfish/7458#-Mknt0ryCjvtm6AlBodi:-Mknt0ryCjvtm6AlBodj:b-bs00o6) ([raw file](https://github.com/batfish/batfish/blob/1e6bd40fc88bc3d2c4e4d35c1098894a0dc7cea4/projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java#L703)):*
> ```Java
>     Prefix prefix = toPrefix(prefixCtx);
>     if (prefix.getStartIp() != address) {
>       warn(ctx, "Incorrect IP/mask specified");
> ```

The CLI enforces this? Can't do `ip route 10.0.0.1 /8`?
___
*[projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java, line 798 at r2](https://reviewable.io/reviews/batfish/batfish/7458#-Mkntje5Ax3Ajc6XBRQB:-Mkntje5Ax3Ajc6XBRQC:b-ry8ooi) ([raw file](https://github.com/batfish/batfish/blob/1e6bd40fc88bc3d2c4e4d35c1098894a0dc7cea4/projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java#L798)):*
> ```Java
>         messageCtx,
>         ctx.route_description().word(),
>         IP_ROUTE_DESCRIPTION_RANGE,
> ```

nit: `IP_ROUTE_DESCRIPTION_RANGE` -> `IP_ROUTE_DESCRIPTION_LENGTH_RANGE`

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7458)* status: 7 of 10 files reviewed, 4 unresolved discussions (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Parser.g4, line 6 at r2](https://reviewable.io/reviews/batfish/batfish/7458#-MknrrolE1Dev2noYNkj:-MknxYzsAGwWPIMPbRnN:b4pmzi) ([raw file](https://github.com/batfish/batfish/blob/1e6bd40fc88bc3d2c4e4d35c1098894a0dc7cea4/projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Parser.g4#L6)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Seems like a weird grammar file boundary. Is `ip` not huge? Would it make sense to do `A10_ip_route` or something like that scoped to static routes?
</blockquote></details>

yeah `ip` is pretty large - can scope it down

how's that? do we still need to fit in a plain `s_ip` rule somewhere that consists of other `ip ...` things?
___
*[projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java, line 702 at r2](https://reviewable.io/reviews/batfish/batfish/7458#-MknsfyG-IVPdXO8XV38:-MknxjOZB6bDcFVIMzu-:b-7ql1td) ([raw file](https://github.com/batfish/batfish/blob/1e6bd40fc88bc3d2c4e4d35c1098894a0dc7cea4/projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java#L702)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

I think in general you should use `!...equals` instead of `!=` for `Ip`, despite caching/inlining.
</blockquote></details>

fixed
___
*[projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java, line 703 at r2](https://reviewable.io/reviews/batfish/batfish/7458#-Mknt0ryCjvtm6AlBodi:-Mknw42C9ITJZKIu0Joa:bncs884) ([raw file](https://github.com/batfish/batfish/blob/1e6bd40fc88bc3d2c4e4d35c1098894a0dc7cea4/projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java#L703)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

The CLI enforces this? Can't do `ip route 10.0.0.1 /8`?
</blockquote></details>

correct, you get an error like the one we have in this warning
___
*[projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java, line 798 at r2](https://reviewable.io/reviews/batfish/batfish/7458#-Mkntje5Ax3Ajc6XBRQB:-Mkny2eDE4CLwaV6qhjG:b-7ql1td) ([raw file](https://github.com/batfish/batfish/blob/1e6bd40fc88bc3d2c4e4d35c1098894a0dc7cea4/projects/batfish/src/main/java/org/batfish/vendor/a10/grammar/A10ConfigurationBuilder.java#L798)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

nit: `IP_ROUTE_DESCRIPTION_RANGE` -> `IP_ROUTE_DESCRIPTION_LENGTH_RANGE`
</blockquote></details>

fixed

**Review by arifogel — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7458)* status: all files reviewed, 2 unresolved discussions (waiting on @corinaminer and @sfraint)

___
*[projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Parser.g4, line 6 at r2](https://reviewable.io/reviews/batfish/batfish/7458#-MknrrolE1Dev2noYNkj:-Mko-LrA-ameg4bxr0vC:bjbvc0s) ([raw file](https://github.com/batfish/batfish/blob/1e6bd40fc88bc3d2c4e4d35c1098894a0dc7cea4/projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Parser.g4#L6)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

yeah `ip` is pretty large - can scope it down

how's that? do we still need to fit in a plain `s_ip` rule somewhere that consists of other `ip ...` things?
</blockquote></details>

Just shove it in this file.
___
*[projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10_ip.g4, line 9 at r1](https://reviewable.io/reviews/batfish/batfish/7458#-Mko-edJDNtntTUtVp3G:-Mko-edJDNtntTUtVp3H:b-a7ljz9) ([raw file](https://github.com/batfish/batfish/blob/61208555d403038beecb9e9d366161874f2bfae9/projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10_ip.g4#L9)):*
> ```ANTLR
> }
> 
> s_ip: IP si;
> ```

Revert this change, and shove `s_ip` in `A10Parser.g4`

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7458)* status: 3 of 10 files reviewed, 1 unresolved discussion (waiting on @arifogel and @corinaminer)

___
*[projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Parser.g4, line 6 at r2](https://reviewable.io/reviews/batfish/batfish/7458#-MknrrolE1Dev2noYNkj:-Mko11HIBPOSVYKXu308:b32wtd) ([raw file](https://github.com/batfish/batfish/blob/1e6bd40fc88bc3d2c4e4d35c1098894a0dc7cea4/projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10Parser.g4#L6)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Just shove it in this file.
</blockquote></details>

ok
___
*[projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10_ip.g4, line 9 at r1](https://reviewable.io/reviews/batfish/batfish/7458#-Mko-edJDNtntTUtVp3G:-Mko0tr55Bfjg3FlHylO:bvnrpcm) ([raw file](https://github.com/batfish/batfish/blob/61208555d403038beecb9e9d366161874f2bfae9/projects/batfish/src/main/antlr4/org/batfish/vendor/a10/grammar/A10_ip.g4#L9)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Revert this change, and shove `s_ip` in `A10Parser.g4`
</blockquote></details>

updated

**Review by arifogel — COMMENTED** [review]
> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7458)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

**Pull request merged**
