### PR TITLE
use new pmd 6.4.0

### PR DESCRIPTION
**Pull request by arifogel**
- adjust checks due to reorganization of rulesets
- fix new violations, enforced now where not partial fix:
  - use isEmpty() instead of comparing Collection.size() to 0
  - avoid modifying funciton parameters (makes code hard to debug)
  - add missing `@Override` annotations
  - (partial fix) avoid calling nonfinal methods in constructors
  - (partial fix) remove unused private methods
  - fix resource leak in DbAuthorizer (not closing ResultSet)
  - avoid using Map/Collection implementations as declared types
  - use equalsIgnoreCase instead of converting case and comparing

### CODE REVIEW

**Comment by arifogel** [comment]
Requesting thorough review by ONE person, though others are welcome to review if they really want to.

---

Review status: 0 of 71 files reviewed, all discussions resolved (waiting on @anothermattbrown, @ratulm, @progwriter, and @dhalperi)

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1661#-:-LEw8Bx2AiWt4neJm3WW:bvlijcw)*

**Comment by dhalperi** [comment]
On it.

---







*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1661#-:-LEw8XeQ7Wts1-iHNFuV:bxdh81z)*

**Comment by dhalperi** [comment]
I'm not super convinced that disallowing modifying value parameters thing is a great change:

- overwriting param allows GC to remove old value
- no danger of accidentally using old value instead of `effectiveParam`

But :lgtm: 

---

Reviewed 71 of 71 files at r1.
Review status: all files reviewed, 3 unresolved discussions (waiting on @arifogel, @anothermattbrown, @ratulm, and @progwriter)

---

*[projects/pom.xml, line 80 at r1](https://reviewable.io/reviews/batfish/batfish/1661#-LEw8bdb8mn1awGDWp2Y:-LEw8bdb8mn1awGDWp2Z:bnluclz) ([raw file](https://github.com/batfish/batfish/blob/4f3f3685093939e379b94adb4122adbd36b8ef97/projects/pom.xml#L80)):*
> ```
> <pmd.vers
> ```

optional: convert tabs to spaces.

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AclIpSpace.java, line 87 at r1](https://reviewable.io/reviews/batfish/batfish/1661#-LEw9Rwu7kWgufMvbad1:-LEw9Rwu7kWgufMvbad2:behn8yz) ([raw file](https://github.com/batfish/batfish/blob/4f3f3685093939e379b94adb4122adbd36b8ef97/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AclIpSpace.java#L87)):*
> ```Java
> 
>   /** Set-theoretic difference between two IpSpaces. */
>   public static @Nullable IpSpace difference(IpSpace ipSpace1, IpSpace ipSpace2) {
> ```

mark arguments as nullable for clarity?

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, line 1075 at r1](https://reviewable.io/reviews/batfish/batfish/1661#-LEwAX2e2VWLJf10byAQ:-LEwAX2e2VWLJf10byAR:b-ykznlr) ([raw file](https://github.com/batfish/batfish/blob/4f3f3685093939e379b94adb4122adbd36b8ef97/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java#L1075)):*
> ```Java
>   public String initContainer(@Nullable String containerName, @Nullable String containerPrefix) {
>     String newContainerName = containerName;
>     if (newContainerName == null || newContainerName.equals("")) {
> ```

Strings.isNullOrEmpty is a nice shortcut here, btw.

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1661#-:-LEwAkU-6t3OWU9e8GpN:b-hzc4iu)*

**Comment by arifogel** [comment]
@dhalperi IMO the benefit to debuggability outweighs the negatives you pointed out. Although I am happy to revisit if we find this check has caused more headache than help.

---

Review status: 68 of 71 files reviewed, all discussions resolved (waiting on @dhalperi, @anothermattbrown, @ratulm, and @progwriter)

---

*[projects/pom.xml, line 80 at r1](https://reviewable.io/reviews/batfish/batfish/1661#-LEw8bdb8mn1awGDWp2Y:-LEwGBE40GYHoRgmzh23:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/4f3f3685093939e379b94adb4122adbd36b8ef97/projects/pom.xml#L80)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> <pmd.vers
> ```

optional: convert tabs to spaces.
</blockquote></details>

done

---

*[projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AclIpSpace.java, line 87 at r1](https://reviewable.io/reviews/batfish/batfish/1661#-LEw9Rwu7kWgufMvbad1:-LEwHb6V1CPvOFNmWbtc:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/4f3f3685093939e379b94adb4122adbd36b8ef97/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/AclIpSpace.java#L87)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

mark arguments as nullable for clarity?
</blockquote></details>

done

---

*[projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java, line 1075 at r1](https://reviewable.io/reviews/batfish/batfish/1661#-LEwAX2e2VWLJf10byAQ:-LEwI6JH6tE1wRWyz-YS:bb7f2mf) ([raw file](https://github.com/batfish/batfish/blob/4f3f3685093939e379b94adb4122adbd36b8ef97/projects/coordinator/src/main/java/org/batfish/coordinator/WorkMgr.java#L1075)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Strings.isNullOrEmpty is a nice shortcut here, btw.
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1661#-:-LEwIBCB-owBypBvdgMm:b2j40ld)*

**Comment by dhalperi** [comment]
Reviewed 4 of 4 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown, @ratulm, and @progwriter)

---



*Comments from [Reviewable](https://reviewable.io/reviews/batfish/batfish/1661)*

**Pull request merged**
