### PR TITLE
BDD: progress towards less garbage

### PR DESCRIPTION
**Pull request by dhalperi**
1. Add `BDD#opEq` variants of `BDD#op`. These overwrite `this` rather than creating a new BDD (allowing the old BDD to be freed).
2. Create new invariants for `Transition#traverse` -- may not `free` input, may not keep a pointer to output, must `free` all intermediate BDDs. Review existing transitions and enforce output invariant (mainly, `Identity` copies its input now). Some likely still create garbage internally.
3. Update `fixpoint` to not create garbage.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7831)* status: 0 of 12 files reviewed, 2 unresolved discussions (waiting on @anothermattbrown and @dhalperi)

___
*[projects/bdd/src/main/java/net/sf/javabdd/BDD.java, line 603 at r1](https://reviewable.io/reviews/batfish/batfish/7831#-Mr8VIKkD5PdNsOJSGYQ:-Mr8VIKkD5PdNsOJSGYR:b-u34wb9) ([raw file](https://github.com/batfish/batfish/blob/7f407ebcb94bc522f1a682d38852fac8ba3fefab/projects/bdd/src/main/java/net/sf/javabdd/BDD.java#L603)):*
> ```Java
>    * @return the result of applying the operator
>    */
>   public abstract BDD apply(BDD that, BDDFactory.BDDOp opr);
> ```

FYI removing `apply` as a public API seems to just make the whole thing more readable.



_Code quote:_
```Java
public abstract BDD apply(
```
___
*[projects/bdd/src/main/java/net/sf/javabdd/JFactory.java, line 275 at r1](https://reviewable.io/reviews/batfish/batfish/7831#-Mr8VVVwENuu_MUmZhoW:-Mr8VVVxDOycpwxn8H6x:b-bq1oa1) ([raw file](https://github.com/batfish/batfish/blob/a0b6c4be5705e0a6097ca4c1c59c75b15ca89f46/projects/bdd/src/main/java/net/sf/javabdd/JFactory.java#L275)):*
> ```Java
>     }
> 
>     public BDD apply(BDD that, BDDOp opr) {
> ```

Working: I think this can be deleted.



_Code quote:_
```Java
    public BDD apply(BDD that, BDDOp opr) {
      int x = _index;
      int y = ((BDDImpl) that)._index;
      int z = opr.id;
      return makeBDD(bdd_apply(x, y, z));
    }
```
___
*[projects/bdd/src/main/java/net/sf/javabdd/JFactory.java, line 283 at r1](https://reviewable.io/reviews/batfish/batfish/7831#-Mr8VXjpBk8gSC68yV1k:-Mr8VXjpBk8gSC68yV1l:b68l2lr) ([raw file](https://github.com/batfish/batfish/blob/a0b6c4be5705e0a6097ca4c1c59c75b15ca89f46/projects/bdd/src/main/java/net/sf/javabdd/JFactory.java#L283)):*
> ```Java
> 
>     @Override
>     public BDD apply(BDD that, BDDOp opr, boolean makeNew) {
> ```

working: this need not be public.

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7831)* status: 0 of 12 files reviewed, all discussions resolved (waiting on @anothermattbrown)

___
*[projects/bdd/src/main/java/net/sf/javabdd/JFactory.java, line 275 at r1](https://reviewable.io/reviews/batfish/batfish/7831#-Mr8VVVwENuu_MUmZhoW:-Mr8XM295MLubNH2-J3m:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/a0b6c4be5705e0a6097ca4c1c59c75b15ca89f46/projects/bdd/src/main/java/net/sf/javabdd/JFactory.java#L275)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Working: I think this can be deleted.
</blockquote></details>

Done.
___
*[projects/bdd/src/main/java/net/sf/javabdd/JFactory.java, line 283 at r1](https://reviewable.io/reviews/batfish/batfish/7831#-Mr8VXjpBk8gSC68yV1k:-Mr8XMvNCJ1zLJYyv7qu:b-896fix) ([raw file](https://github.com/batfish/batfish/blob/a0b6c4be5705e0a6097ca4c1c59c75b15ca89f46/projects/bdd/src/main/java/net/sf/javabdd/JFactory.java#L283)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

working: this need not be public.
</blockquote></details>

Done.

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 10 of 12 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7831)* status: all files reviewed, 2 unresolved discussions (waiting on @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/bddreachability/transition/AddLastHopConstraint.java, line 36 at r3](https://reviewable.io/reviews/batfish/batfish/7831#-MrO5o_e0pxKWf1-yM7_:-MrO5o_e0pxKWf1-yM7a:b-8t0ftk) ([raw file](https://github.com/batfish/batfish/blob/cf04ccbfefb58cc77abbf156e3659b06cb3c4750/projects/batfish/src/main/java/org/batfish/bddreachability/transition/AddLastHopConstraint.java#L36)):*
> ```Java
>   @Override
>   public BDD transitBackward(BDD bdd) {
>     // TODO: does existsLastHop free?
> ```

it does not, but could return the input `BDD` object



_Code quote:_
```Java
// TODO: does existsLastHop free?
```
___
*[projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transition.java, line 8 at r3](https://reviewable.io/reviews/batfish/batfish/7831#-MrO6JL911TLp2go7AM5:-MrO6JL911TLp2go7AM6:b-c4gp3x) ([raw file](https://github.com/batfish/batfish/blob/cf04ccbfefb58cc77abbf156e3659b06cb3c4750/projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transition.java#L8)):*
> ```Java
>  * Bidirectional transition function.
>  *
>  * <p>Implementation note: {@link Transition} implementations are expected to free any intermediate
> ```

would it be simpler to drop the requirement that the caller free its BDD? then the transition would be required to either free it or return it. 



_Code quote:_
```Java
 * <p>Implementation note: {@link Transition} implementations are expected to free any intermediate
 * BDDs they produce, that is, all BDDs other than the input and output. The returned {@link BDD}
 * may be {@link BDD#free freed} by downstream code, and it is the caller's responsibility to free
 * the input BDD.
```

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7831)* status: all files reviewed, 2 unresolved discussions (waiting on @anothermattbrown and @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transition.java, line 8 at r3](https://reviewable.io/reviews/batfish/batfish/7831#-MrO6JL911TLp2go7AM5:-MrOAAlzAZ73riqYb_4D:b-6ahpew) ([raw file](https://github.com/batfish/batfish/blob/cf04ccbfefb58cc77abbf156e3659b06cb3c4750/projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transition.java#L8)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

would it be simpler to drop the requirement that the caller free its BDD? then the transition would be required to either free it or return it. 
</blockquote></details>

We should discuss.

I personally find the "first argument is destroyed" contract really confusing -- `andWith` vs `andEq`. Seems simpler to say that the caller is the one that owns the input BDD. (maybe emphasis on "freeing" vs "ownership" is wrong there).

That said maybe these things are always used in a way where the input BDD can always be safely destroyed. Moves copying BDDs to the traversal code instead.

**Review by anothermattbrown — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7831)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transition.java, line 8 at r3](https://reviewable.io/reviews/batfish/batfish/7831#-MrO6JL911TLp2go7AM5:-MrOFDnREAT8TMgjqBRJ:b2oq2gw) ([raw file](https://github.com/batfish/batfish/blob/cf04ccbfefb58cc77abbf156e3659b06cb3c4750/projects/batfish/src/main/java/org/batfish/bddreachability/transition/Transition.java#L8)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

We should discuss.

I personally find the "first argument is destroyed" contract really confusing -- `andWith` vs `andEq`. Seems simpler to say that the caller is the one that owns the input BDD. (maybe emphasis on "freeing" vs "ownership" is wrong there).

That said maybe these things are always used in a way where the input BDD can always be safely destroyed. Moves copying BDDs to the traversal code instead.
</blockquote></details>

seems fine for now. we can iterate on this later if we find an opportunity to simplify

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7831)* status: 10 of 13 files reviewed, 1 unresolved discussion (waiting on @anothermattbrown)

___
*[projects/batfish/src/main/java/org/batfish/bddreachability/transition/AddLastHopConstraint.java, line 36 at r3](https://reviewable.io/reviews/batfish/batfish/7831#-MrO5o_e0pxKWf1-yM7_:-MrOIDiF2TRhCG-5SlyS:b9mc9l3) ([raw file](https://github.com/batfish/batfish/blob/cf04ccbfefb58cc77abbf156e3659b06cb3c4750/projects/batfish/src/main/java/org/batfish/bddreachability/transition/AddLastHopConstraint.java#L36)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

it does not, but could return the input `BDD` object
</blockquote></details>

Made it not return the input.

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7831)* status: 10 of 13 files reviewed, 1 unresolved discussion (waiting on @anothermattbrown)

___
*[projects/batfish/src/main/java/org/batfish/bddreachability/LastHopOutgoingInterfaceManager.java, line 97 at r4](https://reviewable.io/reviews/batfish/batfish/7831#-MrOIJqd9o5DIDkpVGhK:-MrOIJqd9o5DIDkpVGhL:bgkq10x) ([raw file](https://github.com/batfish/batfish/blob/790bf75ad47e578d79b8f5f33ab5a150f5afdcd4/projects/batfish/src/main/java/org/batfish/bddreachability/LastHopOutgoingInterfaceManager.java#L97)):*
> ```Java
>     Iterator<BDDFiniteDomain<NodeInterfacePair>> iterator = _finiteDomains.values().iterator();
>     if (iterator.hasNext()) {
>       return iterator.next().existsValue(bdd);
> ```

FYI `existsValue` already guaranteed to return a new BDD, per changes in this PR.

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7831)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dhalperi)

___
*[projects/batfish/src/main/java/org/batfish/bddreachability/LastHopOutgoingInterfaceManager.java, line 100 at r4](https://reviewable.io/reviews/batfish/batfish/7831#-MrOIUTT1hx0AybSS27Z:-MrOIUTU3L5KAQDWsaWb:b-qcrwzz) ([raw file](https://github.com/batfish/batfish/blob/790bf75ad47e578d79b8f5f33ab5a150f5afdcd4/projects/batfish/src/main/java/org/batfish/bddreachability/LastHopOutgoingInterfaceManager.java#L100)):*
> ```Java
>     }
> 
>     // No domains! Nothing to do.
> ```

probably worth documenting why this is important.  otherwise, could move the call to the transition (if `existsLastHop` returns the input BDD object)



_Code quote:_
```Java
    // No domains! Nothing to do.
    return bdd.id();
```

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7831)* status: 11 of 13 files reviewed, all discussions resolved (waiting on @anothermattbrown)

___
*[projects/batfish/src/main/java/org/batfish/bddreachability/LastHopOutgoingInterfaceManager.java, line 100 at r4](https://reviewable.io/reviews/batfish/batfish/7831#-MrOIUTT1hx0AybSS27Z:-MrOQrhJEHAozTEelSJe:bk3agat) ([raw file](https://github.com/batfish/batfish/blob/790bf75ad47e578d79b8f5f33ab5a150f5afdcd4/projects/batfish/src/main/java/org/batfish/bddreachability/LastHopOutgoingInterfaceManager.java#L100)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

probably worth documenting why this is important.  otherwise, could move the call to the transition (if `existsLastHop` returns the input BDD object)
</blockquote></details>

updated docs

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish/7831)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dhalperi)

**Pull request merged**
